### ISSUE TITLE
Grammarly Chrome Extension issues with the TinyMce editor

### ISSUE THREAD

**Issue by olexii-lysenko** [tinymce/tinymce#10002]
## 📝 Provide detailed reproduction steps (if any)
In our Vite/React.js web app, we use the TinyMCE editor for messaging between users. Many of our users use the Grammarly Chrome Extension. We are facing compatibility issues between TinyMCE and Grammarly. When the user starts typing something in the editor's input field, the web page starts blinking and jumping back and forth, with the small jumps produced because of the page's scroll bars appearing/disappearing. 

There is an error in the dev tools console:
"grm ERROR [iterable] ░░ Not supported: in app messages from Iterable" 

### ✔️ Expected result
There is no blinking or glitching of the web page during the Grammarly Chrome extension usage with the tinyMCE editor.

### ❌ Actual result
The web page is blinking and glitching if the Grammarly Chrome extension is enabled, - the issue disappears when the Grammarly is disabled.

## 📃 Other details
- Browser: Chrome
- OS: Windows (10, 11)
- First affected version: latest
- Worked in version: latest

**Comment by lostkeys** [comment]
Hi @olexii-lysenko! Because there are a lot of moving parts here, and to help, it would be helpful to know what steps have you done to try to sort out it being an issue with the grammarly extension or your own implementation? Are you able to recreate the issue using a vanilla TinyMCE instance outside of your app?

— Fredrik, Product Manager

**Comment by lostkeys** [comment]
Perfect! 👍

**Comment by khaled-bask** [comment]
@lostkeys  I get the same issue now using a different editor. The editor is Quill and the bug is still reproducable
