### ISSUE TITLE
Text Select Issue in iphone

### ISSUE THREAD

**Issue by SamPratik** [tinymce/tinymce#10009]
Hi,

there is an issue in tinymce text editor in iphone
Whenever we select texts in tinymce & drags it, the blue overlay of selection goes outside the editor in iphone.
For better explanation , I have recorded a video of the issue from Tinymce official website's text editor example.
video: https://mega.nz/file/z6h2kYLY#f2UKb89ysctEAz-P0n4wkzFR6YjOGJ93gXB-_y2CLb0

I have also taken a screenshot of the issue: https://mega.nz/file/OrBkXCzR#CdLc84E8eIsBPD0d3dqIphAYj2tzoY8EicrcAtGdfNg
I have also attached the screenshot & screen record in this ticket.

I hope these will make the issue clear to you. Please give us a fix / solution for this.

Thank you

**Comment by lostkeys** [comment]
Hi @SamPratik. This is not an issue with TinyMCE, but how iframes work on mobile Safari. You can test on any iframe and watch how the selection is still visible when you scroll away. You can use the [autoresize plugin](https://www.tiny.cloud/docs/tinymce/latest/autoresize/) to make TinyMCE grow with the content.

— Fredrik, Product Manager
