### ISSUE TITLE
Paste Handler

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1002]
Description of problem:
I have the following problem on Firefox(Chrome and IE works OK): 
When I use the paste plugin in order to have only plain text pasted in the input area, other handlers for "paste" event don't work. 

Steps to reproduce:
1. Instantiate a tinyMCE content editable div, use the paste plugin to paste only plain text.
2. Assign a handler for the "paste" event. (doesn't matter what handler, can be a function containing just an alert)

Expected result: The code in the assigned handler should be executed when I paste something in the area.

Actual result: Nothing happens. Acts like no paste event occured(maybe the plugin stops the propagation of the paste event??).
On Chrome and IE the exact same code works perfectly.

Firefox version: 23.01(last one)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6229](http://archive.tinymce.com/develop/bugtracker_view.php?id=6229) posted by [serban](http://archive.tinymce.com/profile.php?name=serban)_
> 
> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
