### ISSUE TITLE
Name attribute is removed from <input> when name="name"

### ISSUE THREAD

**Issue by reitanAndreas** [tinymce/tinymce#10032]
We are using TinyMCE 6.8.4, our customer is trying to add a Salesforce form in the source.
But when <input id="name" name="name">, both the name attribute and id is removed. Is there any way to allow name="name"?
It works when name="somethingElseThanName", but the it is important to the customer to use the name="name". 

Expected result: using name attribute like: <input name="name"> should be possible.

Actual result:
<label for="name">Contact name</label>
<input type="text" id="name" name="name"> results in: <input type="text"> 

- First affected version: 5.10.1
- Worked in version: 5.6.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
This is a security feature we added in TinyMCE 5.9 to prevent an attack known as "DOM Clobbering" where element names conflict with DOM functions and override them. Any `id` or `name` value that matches a window property is blocked.

We replaced our custom implementation with DomPurify in TinyMCE 6. To read more about about why DOM Clobbering is a problem, DomPurify has an extensive guide to their security goals including helpful links.
https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model

We do offer an option to disable sanitization but it's not recommended.
https://www.tiny.cloud/docs/tinymce/latest/security/#turning-dompurify-off
