### ISSUE TITLE
External toolbar size

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1003]
Since 4.0.1 that was the latest version I tested before my vacation, the toolbar content (menu and buttons) resizes to the wrong size inside its container. The toolbar container is 300px wide but the toolbar content sets width: 542px; and height: 69px; (every thing on the same row).

This was not the case in 4.0.1 and 4.0.1 seems to have the correct behaviour.

see fiddle.

Best regards Andreas
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6230](http://archive.tinymce.com/develop/bugtracker_view.php?id=6230) posted by [magny](http://archive.tinymce.com/profile.php?name=magny)_

> _**Tags:** [firefox msie safari chrome opera 404]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://fiddle.tinymce.com/6xdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
