### ISSUE TITLE
Select All text inside tinymce (in Iphone) shows blue select overlay outside tinymce texteditor

### ISSUE THREAD

**Issue by SamPratik** [tinymce/tinymce#10040]
Hi,

there is an issue in tinymce text editor in iphone
Whenever we select texts in tinymce & drags it, the blue overlay of selection goes outside the editor in iphone.
For better explanation , I have recorded a video of the issue from Tinymce official website's text editor example.
video: https://mega.nz/file/z6h2kYLY#f2UKb89ysctEAz-P0n4wkzFR6YjOGJ93gXB-_y2CLb0

I have also taken a screenshot of the issue: https://mega.nz/file/OrBkXCzR#CdLc84E8eIsBPD0d3dqIphAYj2tzoY8EicrcAtGdfNg
I have also attached the screenshot & screen record in this ticket.

I hope these will make the issue clear to you. Please give us a fix / solution for this.

Thank you

**Comment by lostkeys** [comment]
Hey @SamPratik! I just answered you in the other ticket you submitted https://github.com/tinymce/tinymce/issues/10009. Cheers,

— Fredrik, Product Manager
