### ISSUE TITLE
invalid css in modules/oxide/src/less/theme/content/resize-handles /resize-handle.less

### ISSUE THREAD

**Issue by dgm** [tinymce/tinymce#10044]
https://github.com/tinymce/tinymce/blob/1f53ab2e751cb18fa0c7b318019fc8be745a4b59/modules/oxide/src/less/theme/content/resize-handles/resize-handle.less#L64

background: rgba(0 0 0 / 75%);   should have commas, previous commit was

rgba(0, 0, 0, .75);

This breaks a sassc processor that this is going through in my build pipeline...
SassC::SyntaxError: Error: overloaded function rgba given wrong number of arguments

**Comment by lostkeys** [comment]
Oops, thanks for surfacing this. We'll have it fixed in an upcoming release!

— Fredrik, Product Manager

**Comment by lostkeys** [comment]
Hi again. It turns out this syntax _is_ [valid CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb) after all, it's just relatively modern. you could try upgrading your preprocessor and see if they added support for it.
— Fredrik, Product Manager

**Comment by dgm** [comment]
huh.  well I did change to another processor, which complains about a ton of old things but works.
