### ISSUE TITLE
some strings don't get translated with a language pack

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1025]
Description of problem:

The following strings don't get translated when using a language pack:
"Font Family" - fontselect in toolbar
"Font Sizes" - fontsizeselect in toolbar
"Paste as text" - pastetext in toolbar
"Edit image" - title of the edit image dialog
"Lower Alpha", "Lower Greek", "Lower Roman", "Upper Alpha", "Upper Roman" - numlist in toolbar

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6250](http://archive.tinymce.com/develop/bugtracker_view.php?id=6250) posted by [totaleasy](http://archive.tinymce.com/profile.php?name=totaleasy)_

> _**Tags:** [firefox msie safari chrome opera 4x]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
