### ISSUE TITLE
Underline color does not change when font color is changed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1026]
Steps to reproduce:

1.Click Underline and choose a color

2.Type something

3.Change the color and continue typing

Expected result: underline and font color should match

Actual result: underline and font color don't match
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6251](http://archive.tinymce.com/develop/bugtracker_view.php?id=6251) posted by [leoi11](http://archive.tinymce.com/profile.php?name=leoi11)_

> _**Tags:** [firefox msie safari chrome opera style font color underline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
