### ISSUE TITLE
SaveContent event fires BEFORE save() not after (as per the docs claim)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1030]
Description of problem:

Steps to reproduce:
1. setup an event handler on('SaveContent')
2. call save()
3. SaveContent is called before save() 

Expected result: 
textarea/input should be populated by the time SaveContent is triggered

Looking at the code,   

 self.fire('SaveContent', args);

 happens before

  elm.innerHTML = html;

save: function(args) {
            var self = this, elm = self.getElement(), html, form;

```
        if (!elm || !self.initialized) {
            return;
        }

        args = args || {};
        args.save = true;

        args.element = elm;
        html = args.content = self.getContent(args);

        if (!args.no_events) {
            self.fire('SaveContent', args);
        }

        html = args.content;

        if (!/TEXTAREA|INPUT/i.test(elm.nodeName)) {
            elm.innerHTML = html;

            // Update hidden form element
            if ((form = DOM.getParent(self.id, 'form'))) {
                each(form.elements, function(elm) {
                    if (elm.name == self.id) {
                        elm.value = html;
                        return false;
                    }
                });
            }
        } else {
            elm.value = html;
        }

        args.element = elm = null;

        if (args.set_dirty !== false) {
            self.isNotDirty = true;
        }

        return html;
    },
```

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6260](http://archive.tinymce.com/develop/bugtracker_view.php?id=6260) posted by [tomburnell](http://archive.tinymce.com/profile.php?name=tomburnell)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by cirkuitnet** [comment]
We actually rely on this event to happen "before" the content is saved. Perhaps the best solution would be to have 2 events... 1 for before save, and 1 for after? =]

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
