### ISSUE TITLE
Weird selection collapse

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1034]
Description of problem:

Steps to reproduce:
1. Open the fiddle
2. Doubleclick the first word to receive a selection for it
3. Hit the "bold" button

Expected result:
The whole selected word gets bold.

Actual result:
The selection collapses to the the first part of the word, which gets bold.

Another hint:
This same thing happens for MSIE 10 too, but i can only reproduce it inside my local development scenario.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6261](http://archive.tinymce.com/develop/bugtracker_view.php?id=6261) posted by [msvc](http://archive.tinymce.com/profile.php?name=msvc)_

> _**Tags:** [firefox opera firefox8 opera12]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://fiddle.tinymce.com/azdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
