### ISSUE TITLE
Paste plugin - Alternative to the keyboard shortcuts message

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1035]
Instead of the annoying message "Please use Ctrl+V/Cmd+V keyboard shortcuts to paste contents", i would suggest the following(at least as an option):

Accept the paste and run a code cleanup afterwards. If that is not possible, what about firing a "paste" event, where a custom handler could implement such behaviour?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6270](http://archive.tinymce.com/develop/bugtracker_view.php?id=6270) posted by [msvc](http://archive.tinymce.com/profile.php?name=msvc)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
