### ISSUE TITLE
Compatibility issue with .Net System.Web.Optimization

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1037]
Description of problem:
I am using tinymce within an ASP.NET MVC 4 project. Using Microsoft's script bundle optimizations breaks the tinymce script so it can not load.

I have identified the source of the issue to be within the EditorManager.setup function of tinymce, line 27468 in my copy of 2.0.5. There is a regex within this function intended to locate the tinymce.js, tinymce.min.js, or tinymce.dev.js script. 

However, when the bundle optimizations repackages the scripts it changes the name, in my case from "tinymce.min.js" to "tinymce?v=yJ_tRgQhK_6odwQaU1QoOEACMgDxcE9MXLywd8TMaQA1", so the regex does not match. As a result, the baseURL used by tinymce is wrong and the script crashes when it can not find the theme files.

I will work around this by not bundling the tinymce script. Please consider changing the regex to account for the .Net bundles.

Steps to reproduce:
1.Create a ASP.NET MVC 4 web project
2.Create a view with a textarea
3.Add the timymce nuget package.
4.Add tinymce to the bundle config.
5.init the area with tinymce

Expected result:
Load tinymce

Actual result:
Does not load.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6263](http://archive.tinymce.com/develop/bugtracker_view.php?id=6263) posted by [powercat97](http://archive.tinymce.com/profile.php?name=powercat97)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
