### ISSUE TITLE
getBookmark injects empty paragraph

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1040]
Description of problem:

After an editor init, calling a "selection.getBookmark()" injects an empty paragraph. The bug goes away, after the editor once received a focus.

Steps to reproduce:
1. Open the fiddle
2. Click the provided link "getBookmark" below the editor

Expected result:

A bookmark without additional paragraph injection.

Actual result:

A bookmark with additional paragraph injection ;-)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6266](http://archive.tinymce.com/develop/bugtracker_view.php?id=6266) posted by [msvc](http://archive.tinymce.com/profile.php?name=msvc)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/lzdaab_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:

**Comment by dsifford** [comment]
This still very much exists.

Reproducible simply by calling `getBookmark` on an empty editor before interacting with the editor. The exact content that is being injected is `<p><br data-mce-bogus="1"/></p>`

Affected for current WordPress tinymce and Chrome canary.

**Comment by dsifford** [comment]
Update: Fairly certain this can be mitigated by using `editor.selection.getBookmark(1)` rather than `editor.selection.getBookmark()` as the latter actually inserts dom nodes rather than just returns a Range.
