### ISSUE TITLE
Translation download contains old translations

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1042]
Downloading the latest translation for German (de) from the languages download page (http://www.tinymce.com/i18n/index.php) results in a .js file that contains old translations which are not present in Transifex anymore. I would expect the file to contain the most recent translations of that language. Especially as the date on the download page is correctly updated.

Also, all translations are approved/reviewed. If I download a .po file via Transifex (either using "Download for use" or "Download only reviewed translations"), it retrieves the latest version.

This has happend before and was manually solved (http://www.tinymce.com/develop/bugtracker_view.php?id=6259), but I think there is some bug involved.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6277](http://archive.tinymce.com/develop/bugtracker_view.php?id=6277) posted by [simon.lmn](http://archive.tinymce.com/profile.php?name=simon.lmn)_

> _**Tags:** [i18n transifex]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
