### ISSUE TITLE
setContent of selection creates uncontrollable selections in Opera

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1044]
Description of problem:

Steps to reproduce:
1. Select some text in TextArea in Opera browser
2. Click on "T" button in toolbar (calls setContent method of selection object)

Expected result:
Selected text is replaced and no selection is active (this is behavior from other browsers).

Actual result:
Selected text is replaced, but additional selections are created and can not be get rid of programmatically, because they are invisible to JavaScript.

Additional notes:
It happens both in version 3 and 4. I've tested this in Opera v12.1, but I think older versions are also affected.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6271](http://archive.tinymce.com/develop/bugtracker_view.php?id=6271) posted by [PenaPP](http://archive.tinymce.com/profile.php?name=PenaPP)_
> 
> _**Tags:** [opera opera12 setcontent selection opera uncontrollable 3x]_
> _**Status:** Verified_
> _**Resolution:** Wont Fix_
> _**Attached URL:** http://fiddle.tinymce.com/0zdaab/4_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
