### ISSUE TITLE
Images properties

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1045]
Images haven't properties like float, margins, styles, borders etc...

This is very needed when u doing samthing for manny browsers...

I will be very happy if we can get this properties/arguments back :)

With regards
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6272](http://archive.tinymce.com/develop/bugtracker_view.php?id=6272) posted by [Prezi2907](http://archive.tinymce.com/profile.php?name=Prezi2907)_

> _**Tags:** [images properties styles]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
I believe mmm is right, and the advanced tab should give you the features you requested, so I'm going to close this ticket. If not, let us know and we can look into it. 
- Millie @ TinyMCE
