### ISSUE TITLE
save button - remove "save" caption

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1048]
As we are short of space in the toolbar why not get rid of the caption ("Save") of the save button? The disc image should be self explanatory enough. In other languages the text is just too long ("Speichern", "enregistrer").

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6276](http://archive.tinymce.com/develop/bugtracker_view.php?id=6276) posted by [manu37](http://archive.tinymce.com/profile.php?name=manu37)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
