### ISSUE TITLE
Font type & size is immediately reverting to defaults when clicked on font color button

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1049]
Set font type & size is immediately reverting to defaults when clicked on font color button after typing something.

Here are the steps to regenerate,

1. Open the demo http://www.tinymce.com/tryit/classic.php.
2. Select font type as "Arial Black" & font size as "36pt".
3. Select font-color say "Red" & text-background color as "gray".
4. Type in some text say "Hello".
5. Click on the font-color button again (not the font-color drop down).
6. See the font size and type or font family changed to defaults.

Please see the attached screenshot for more Information.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6278](http://archive.tinymce.com/develop/bugtracker_view.php?id=6278) posted by [vijaysarin43](http://archive.tinymce.com/profile.php?name=vijaysarin43)_

> _**Tags:** [firefox msie safari chrome opera font default reverting]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
