### ISSUE TITLE
TypeError: t.split is not a function

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1051]
Description of problem:
When I set TinyMCE init without "toolbar",  I get javascript error:
TypeError: t.split is not a function
Script: ../tinymce.min.js
Line: 8

Steps to reproduce:
1.I set tinymce like this:
tinyMCE.init({
    //....
    inline: true,
    menubar: false,
    toolbar: {}
});

2. save script
3. refresh page in browser

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6287](http://archive.tinymce.com/develop/bugtracker_view.php?id=6287) posted by [houba](http://archive.tinymce.com/profile.php?name=houba)_

> _**Tags:** [firefox msie safari chrome opera inline toolbar]_
> _**Status:** Closed_
> _**Resolution:** Fixed_
> _**Attached URL:** none_

**Comment by Kodwings22** [comment]
Many programmers suffer from this problem. This link (https://kodlogs.net/271/split-is-not-a-function-error-in-javascript) contains the best solution I’ve ever seen. I got the solution from here, I think it will be very useful for you. Many thanks to the members of this website for discussing this topic.
