### ISSUE TITLE
Let inline external toolbar be visible on blur

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1053]
It would be nice to have the possibility to keep the toolbar even when a blur occurs. 
And keep it until the editor gets removed.

Best regards Andreas

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6280](http://archive.tinymce.com/develop/bugtracker_view.php?id=6280) posted by [magny](http://archive.tinymce.com/profile.php?name=magny)_
> 
> _**Tags:** [4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
