### ISSUE TITLE
Spell Check inserting speical characters

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1056]
Description of problem:

Steps to reproduce:
1.Create a new knowledge article
2.Open a word document and type a sentence or two with misspelled words.
3. Copy what you have typed on your word document, click the paste from word icon, dialog box will display; cntrl v to paste your text from word into the knowledge article 
4.save the knowledge article
5. click the spelling icon on the knowledge tool bar; dialog box will  display; correct your misspell words, click okay
6. This is the point where we see special characters inserted
Expected result:
There should not be any special characters inserted
Actual result:
Special characters inserted in lines of text

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6283](http://archive.tinymce.com/develop/bugtracker_view.php?id=6283) posted by [Jerry](http://archive.tinymce.com/profile.php?name=Jerry)_
> 
> _**Tags:** [msie chrome msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
