### ISSUE TITLE
tinymce 4.0.5 table plugin not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1060]
Description of problem:
Some functionality of tinymce such as the table plugin were not working on my website, after looking into the errors I was getting I found that the variables "name" and "type" on lines 2057 and 10307 of tinymce.js were being set to "override" which did not exist in the matchedNodes and matchExpr arrays. I made a post on the forum over here:

http://www.tinymce.com/forum/viewtopic.php?pid=109327#p109327

post #5 explains the 2 lines of code that needed to be modified in order to get the table plugin to work

Steps to reproduce:
I am not sure how to reproduce this bug, it is possible that our in house javascript UI framework was causing issues with tinymce.

The textareas are created using our javascript UI framework dynamically when you press a button and then tinymce is applied to it.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6288](http://archive.tinymce.com/develop/bugtracker_view.php?id=6288) posted by [dbgtboy](http://archive.tinymce.com/profile.php?name=dbgtboy)_

> _**Tags:** [firefox msie safari chrome opera table plugin override]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
