### ISSUE TITLE
have to click TWICE to submit the form with jQuery Form Plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1061]
Description of problem:
i have used jQuery Form Plugin - malsup.

when i fill and submit the 'Add books' form it works perfectly. but, when i submit edit form i have to click Twice submit button to submit.

when i click on submit button, all the fields values can be caught by php.but not "TEXTAREA".

Steps to reproduce:
1.
2.
3.
4.
5.

Actual result:
text,passoword, file,etc.. are working properly.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6289](http://archive.tinymce.com/develop/bugtracker_view.php?id=6289) posted by [malinga91](http://archive.tinymce.com/profile.php?name=malinga91)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
