### ISSUE TITLE
Progress wheel won't stop spinning

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1063]
Description of problem:

Page works fine but Progress wheel won't stop spinning in IE

How do I stop it please?

Thanks

Robert Shimield
Frimley Park Hospital
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6290](http://archive.tinymce.com/develop/bugtracker_view.php?id=6290) posted by [robshim](http://archive.tinymce.com/profile.php?name=robshim)_

> _**Tags:** [msie msie7]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** Internal intranet page_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
