### ISSUE TITLE
constrain proportions value not remembered

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1064]
Description of problem:
TinyMCE 4 is forgetting the image's or video's "constrain proportions" value set by user.

Steps to reproduce:
1. Insert an image and uncheck "constrain proportions"
2. Mark the image in the Editor and click on the image button to edit.

Expected result:
The checkbox for "constrain proportions" should be unchecked as selected by the user.
Actual result:
The checkbox is checked again as by default.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6301](http://archive.tinymce.com/develop/bugtracker_view.php?id=6301) posted by [suse](http://archive.tinymce.com/profile.php?name=suse)_
> 
> _**Tags:** [firefox msie safari chrome opera tinymce4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:

**Comment by fallen** [comment]
Hi, this issue is still present on 4.7.0.
If you uncheck the checkbox, it will get checked again automatically.
How to not put contraints on image?

**Comment by fyrkant** [comment]
What is the problem with the checkbox being checked by default? The checkbox sets whether or not the proportions should be contrained when you change the width/height in the input boxes in the dialog, so if you are going to change the values there you can unceck the checkbox, right? If you want to use the drag handles and resize an image without constraints you can do so by holding in shift and dragging.

**Comment by fallen** [comment]
The issue is that if you uncheck the checkbox, then click OK, then you go again in the image settings : the checkbox is checked again.
It seems you cannot uncheck it.

**Comment by fyrkant** [comment]
The checkbox is only relevant when the dialog is open, and it is default as checked, but if you want to change height/width without constraints you can uncheck it.  It is true that it doesn't remember whether you unchecked it last time you opened the dialog but I don't really see the value in that.

**Comment by fyrkant** [comment]
No problem!
