### ISSUE TITLE
Separate toolbar buttons for tables

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1065]
TinyMCE 3 had separate toolbar buttons for table control: add row, add column and the like. Some of my clients have to work a lot with tables, and they are missing those buttons in TinyMCE 4.

Would it be possible to optionally add these buttons again?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6292](http://archive.tinymce.com/develop/bugtracker_view.php?id=6292) posted by [Creagraphy](http://archive.tinymce.com/profile.php?name=Creagraphy)_
> 
> _**Tags:** [tables]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:

**Comment by nicohartto** [comment]
Hello,

This seems like the appropriate ticket.

As a User I would like to have the possibility to add "inserttable" to the toolbar so that I can quickly create tables without going through the submenu.

Is there a way to achieve this? Adding inserttable to toolbar does do the tick, although that is internally used. I think this would be satisfied if that option could be exposed so that it can be used in the toolbar option string.

**Comment by fyrkant** [comment]
@nicohartto I'm not sure I understand what that button would do, you still need to choose what size the table should be, right?

**Comment by donShakespeare** [comment]
Maybe a top level toolbar button such as can be found in the inlite theme?

Press the return key while in the editor
https://www.tinymce.com/docs/demo/inlite/

Maybe the OP wants `tinymce.exeCommand('mceInsertTable', true)` or something of that exposed nature.

**Comment by nicohartto** [comment]
@fyrkant I guess the command I specified was wrong, but as described in the inline demo - that is the aim. To have just a button for the "create table" that shows the grid-tool to create a table. Without all the stuff in the default "table" toolbar dropdown. 

mceInsertTable is close, but the popup is unnecessary.
