### ISSUE TITLE
Tooltip under drop-down in Opera

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1066]
Attached image explains everything.
Opera 12.16, Linux
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6293](http://archive.tinymce.com/develop/bugtracker_view.php?id=6293) posted by [nazar-pc](http://archive.tinymce.com/profile.php?name=nazar-pc)_

> _**Tags:** [opera opera12 tooltip opera]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
