### ISSUE TITLE
Duplcates of Code UL after paste 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1067]
Description of problem: When i paste code to the viwe code window i get duplicates of UL when i reopen, this gets saved in webpage. 

&ltg;div class="car-wrapper" style="margin-bottom: 0px;">
&ltg;ul style="position: relative; width: 950px; height: 234px;">
&ltg;ul style="position: relative; width: 950px; height: 234px;">
&ltg;li class="active" style="display: block; position: absolute; left: 0px; top: 0px;">
&ltg;div class="inner1">
&ltg;div>

Steps to reproduce:
1. Open viwe source
2. Paste code
3. Reopen the viwe source
4. Duplicate UL
5.

Expected result:

Actual result:
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6294](http://archive.tinymce.com/develop/bugtracker_view.php?id=6294) posted by [mako74](http://archive.tinymce.com/profile.php?name=mako74)_

> _**Tags:** [chrome chrome13 duplicates of code]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
