### ISSUE TITLE
Noneditable Token being removed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1068]
Description of problem:

Steps to reproduce:
1.	Place the cursor after the token
2.	Press enter
3.	Press delete
Expected: The p just added is removed
Actual: The token from the line above is being removed

This is also happening in the online demo http://www.tinymce.com/tryit/3_x/noneditable_content.php
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6295](http://archive.tinymce.com/develop/bugtracker_view.php?id=6295) posted by [leonardor](http://archive.tinymce.com/profile.php?name=leonardor)_

> _**Tags:** [firefox msie safari chrome opera noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Q0daab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
