### ISSUE TITLE
implement responsive model windows

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1070]
Using this for inspiration:
http://jschr.github.io/bootstrap-modal/

as I'm sure the original bootstrap model inspired the current look, it should be possible to make all the models support responsive designs, and allow for scrolling the content inside them.

Perhaps another solution would be to more easily allow the models to be replaced by 100% custom code, providing that a certain set of minimum required functions (like createModel(width, height) and so on) is present?   Over all, a more freestanding UI lib for all components of the UI would be great, modularity is always wanted.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6298](http://archive.tinymce.com/develop/bugtracker_view.php?id=6298) posted by [bubach](http://archive.tinymce.com/profile.php?name=bubach)_
> 
> _**Tags:** [responsive model windows]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
