### ISSUE TITLE
Spellchecker reports Error: General when checking the spelling a second time

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1072]
In my tests, I typed in correctly spelled text.
Click on Spellcheck button.
Displays "no misspellings found".

So far, so good.

Then, click on the spellchecker again.
You then get Error : General.

(Then, click on it a third time and it works.)

Checking this behind the scenes, it seems to NOT perform the RPC the times when I get the error.

Update:
It also seems that if I wait a few seconds before clicking on the button a second time it works. Only if I click on the spellchecker button within a few seconds do I get the odd behaviour.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6308](http://archive.tinymce.com/develop/bugtracker_view.php?id=6308) posted by [avromf](http://archive.tinymce.com/profile.php?name=avromf)_
> 
> _**Tags:** [spellchecker 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
