### ISSUE TITLE
Editor's iframe reloads whenever it's moved around the DOM

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1073]
Description of problem:
Arter moving editor around the DOM iframe reloads but don't re-initializing. As i know it's a common behaviour in all browsers.

Steps to reproduce:
1. Run TinyMCE
2. Move editor's parent node in the DOM

Expected result:
Editor should re-initialize iframe's content

Actual result:
Iframe reloads and stays empty

Solution:
As workaround we could check iframe's doctype on iframe's "load" event and if it's empty re-initialize iframe's content
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6302](http://archive.tinymce.com/develop/bugtracker_view.php?id=6302) posted by [x000000](http://archive.tinymce.com/profile.php?name=x000000)_

> _**Tags:** [firefox msie safari chrome opera iframe dom]_
> _**Status:** Closed_
> _**Resolution:** Wont Fix_
> _**Attached URL:** http://fiddle.tinymce.com/n1daab/2_

**Comment by enoh-barbu** [comment]
why you empty the iframe in the first place? it's just DOM elements moving around

**Comment by TheSpyder** [comment]
We don't. Unloading the window of an iframe when the element disconnects - a move is a combination of remove then insert - is browser behaviour. It's actually [specified by the standard](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element) (look for `The iframe HTML element removing steps, given removedNode, are to destroy a child navigable given removedNode.`)

Try it in a plain HTML page, it will be more obvious if you customise the contents of the iframe before you move it.

**Comment by enoh-barbu** [comment]
@TheSpyder understood, sorry for that, I'll delete my comment

**Comment by TheSpyder** [comment]
well now my message looks out of place 😂
