### ISSUE TITLE
Tiny V4.0.5 / Firefox / The selected last space not underlined

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1074]
Steps to reproduce:

1.Write 'AAA  BBB  CCC' with 2 spaces between words
&ltg;p>AAA&nbsp; BBB&nbsp; CCC&ltg;/p>
2.Select with the mouse BBB and the 2 spaces after 'BBB'
3.Select Underline icon

Expected result:

'AAA  BBB  CCC'
'     -----   '

Actual result:
The last space is not underlined under Firefox 23 :
'AAA  BBB  CCC'
'     ----    '

Correct under Chrome :
'AAA  BBB  CCC'
'     -----   '

Thank you Spocke for your analyse.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6303](http://archive.tinymce.com/develop/bugtracker_view.php?id=6303) posted by [fanOfTiny](http://archive.tinymce.com/profile.php?name=fanOfTiny)_
> 
> _**Tags:** [firefox]_
> _**Status:** Verified_
> _**Resolution:** Later_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
