### ISSUE TITLE
Spell Checker Not Working in TinyMCE 4.0.5

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1081]
Description of problem:

Steps to reproduce:
1. I downloaded tinymce_spellchecker_php_2_0_6_1.zip, extracted the file and uploaded the spellchecker folder to the tinymce/js/tinymce/plugsins folder
2. I added the following code to my test page:

&ltg;script type="text/javascript" src="http://www.vancouverceilidh.org/newslettertest/tinymce/js/tinymce/tinymce.min.js">&ltg;/script>
&ltg;script type="text/javascript">
tinymce.init({
    selector: "textarea",
    theme: "modern",
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor spellchecker"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons | spellchecker",
    image_advtab: true,
    templates: [
        {title: 'Test template 1', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ]
});
&ltg;/script>

3. I configured the file tinymce/js/tinymce/plugsin/spellchecker/config.php thus and uploaded to the server:

&ltg;?php
/**
 * config.php
 *
 * @package MCManager.includes
 */
	// General settings
	$config['general.engine'] = 'GoogleSpell';
	//$config['general.engine'] = 'PSpell';
	//$config['general.engine'] = 'PSpellShell';
	//$config['general.remote_rpc_url'] = 'http://some.other.site/some/url/rpc.php';

	// PSpell settings
	$config['PSpell.mode'] = PSPELL_FAST;
	$config['PSpell.spelling'] = "";
	$config['PSpell.jargon'] = "";
	$config['PSpell.encoding'] = "";

	// PSpellShell settings
	$config['PSpellShell.mode'] = PSPELL_FAST;
	$config['PSpellShell.aspell'] = '/usr/bin/aspell';
	$config['PSpellShell.tmp'] = '/tmp';

	// Windows PSpellShell settings
	//$config['PSpellShell.aspell'] = '"c:\Program Files\Aspell\bin\aspell.exe"';
	//$config['PSpellShell.tmp'] = 'c:/temp';
?>

Expected result: To spell check the textarea box

Actual result: Got message "Error: General"

Thank you, Paul Lowe

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6309](http://archive.tinymce.com/develop/bugtracker_view.php?id=6309) posted by [PaulARLowe](http://archive.tinymce.com/profile.php?name=PaulARLowe)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.vancouverceilidh.org/newslettertest/test.html_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
