### ISSUE TITLE
The order of applying 2 formats generate different HTML result 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1084]
I've configured Tinymce to use the span format of Bold and Italic.
Now when I apply Bold then underline I got this:

&ltg;p>&ltg;span style="text-decoration: underline;">&ltg;span style="font-weight: bold;">test&ltg;/span>&ltg;/span>&ltg;/p>

and when I apply the 2 formats in the other order underline then Bold I got this:
&ltg;p>&ltg;span style="text-decoration: line-through; font-weight: bold;">test&ltg;/span>&ltg;/p>

So it's much better to get the same result despite the order of the commands we execute 

Hope it's much clear now and I really hope that you fix this Bug sooner before the release of the next version

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6315](http://archive.tinymce.com/develop/bugtracker_view.php?id=6315) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_
> 
> _**Tags:** [firefox msie safari chrome opera styles formatter]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
