### ISSUE TITLE
Spell check feature doesn't work in the online demo itself

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1087]
Description of problem:

Steps to reproduce:
1.browse through above mentioned
2.enter an incorrect word
3.click on spell check button
4.
5.

Expected result: incorrect needs to be highlighted

Actual result: its throwing an error alert

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6335](http://archive.tinymce.com/develop/bugtracker_view.php?id=6335) posted by [ashok4v](http://archive.tinymce.com/profile.php?name=ashok4v)_
> 
> _**Tags:** [firefox msie safari chrome opera spellcheck]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
