### ISSUE TITLE
All the selected text is applied with the options configured inside the Format dropdown

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1088]
Description of problem:

Steps to reproduce:
1. Access to the site
2. Mark a selected text (leaving at least three words)
3. Click on Format tab
4. Put the mouse over Formats option.
5. E.g.: Put the mouser over the Headers option.
6. Select the 'Header 1' option.

Expected result:
Only the selected text should be applied with the option selected

Actual result:
All the paragraph is applied with the selected option

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6320](http://archive.tinymce.com/develop/bugtracker_view.php?id=6320) posted by [jogaevil25](http://archive.tinymce.com/profile.php?name=jogaevil25)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
I believe this is a duplicate of #1418. Could you please have a look and check if it is? Thanks,
Millie @ TinyMCE

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
