### ISSUE TITLE
Internationalization of Toolbar Buttons

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1089]
I like to suggest to add internationalization for appropriate toolbar buttons, such as B, I, U etc.  At least in German word processing software it's quite customary to have F instead of B and K instead of I, for instance.

Perhaps a solution would be to outsource the respective style rules to language dependend files?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6337](http://archive.tinymce.com/develop/bugtracker_view.php?id=6337) posted by [cmb69](http://archive.tinymce.com/profile.php?name=cmb69)_
> 
> _**Tags:** [i18n 4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
