### ISSUE TITLE
Problem with editor on initial null field and caching from somewhere

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1092]
Description of problem:
script page is editing class info from database adding class overview text from form textarea populated from database. Overview field is new fields and some records have null value. Many times when bringing up record for edit having null value but editor fills in values. Current script has debugging displays showing DB value, and intermediate string holding db value. In some cases when it doesn't work, db field is empty as is string, while editor window. When editing record with Overview value, text is truncated.
Using CDN.

steps to reproduce:
1. access url
2. select record with overview, compare editor field to displayed db value
3. use back arrow to return list
4. edit record with no value. Should see display with no value and editor window with text
5. If you wipe our text and update, when you come in and look at records, editor window is blank. My other uses of editor have worked well on site.

Expected result:
see above scenarios
Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6322](http://archive.tinymce.com/develop/bugtracker_view.php?id=6322) posted by [RLM](http://archive.tinymce.com/profile.php?name=RLM)_
> 
> _**Tags:** [firefox firefox 2301 firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** www.apics-michiana.org/newclassedit.asp_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
