### ISSUE TITLE
tiny mce 3.5.8 not at all loading in IE 8 compatibility view

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1094]
Description of problem:

Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6323](http://archive.tinymce.com/develop/bugtracker_view.php?id=6323) posted by [sravanthy](http://archive.tinymce.com/profile.php?name=sravanthy)_

> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
