### ISSUE TITLE
Mce4 - Paste plugin - img from computer (base64)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1095]
The XenForo developers have created a function on an other editor to paste an image from your computer (ctrl+c on a file, then ctrl+v on this editor) that automatically upload the image and inserts it inside the editor. I've converted this function to TinyMCE and it's working fine on Firefox, but not on IE or Chrome. Let's avoid IE since there's no log in the console.

With Chrome an error message is displayed. It's coming from the paste plugin and more precisely from the processByContentType function. When a base64 image is pasted on Chrome, the clipboardData.types return null. So clipboardData.types.length triggers an error (can't find length).

Put this aside, it seems the paste plugin on Chrome & IE can't not match other contents than text or html. Or Firefox, when I use the PastePreProcess event, I have a string with my base64 image information. Here's the way I'm doing:
https://github.com/cclaerhout/xen_TinyQuattro/blob/master/upload/js/sedo/tinyquattro/tinymce/plugins/xen_paste_img/plugin.js

Do you think you can add base64 support or at least to standardise Firefox behaviour to others browsers ?

Thanks !

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6367](http://archive.tinymce.com/develop/bugtracker_view.php?id=6367) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_
> 
> _**Tags:** [msie chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
