### ISSUE TITLE
Add some utility functions in tinymce.util.Tools

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1097]
TinyMCE API can be much more robust if it provides additional built-in functions that simplify the development process for a beginner or intermediate JavaScript developers.
The built-in utility functions are the one that make any javascript library so popular like JQuery and Underscore JS. So why not follow them.

Spocke please check my pull Request in Github: 
#244: Add some utility functions in tinymce.util.Tools

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6326](http://archive.tinymce.com/develop/bugtracker_view.php?id=6326) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_
> 
> _**Tags:** [tinymceutiltools]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
