### ISSUE TITLE
Invalid HTML when applying Bold, red color and strikethrough

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1098]
Description of problem:
Applying these 3 formats in this specified order results an invalid output HTML

Steps to reproduce:
1.You have to configure strikethrough format to be exact: true and not u tag
2.write some text
3.Select All the text
4.Apply Bold, red color then strikethrough formats on the selection
5. open up the source code window to see the output HTML

Expected result:

&ltg;p>&ltg;span style="font-weight: bold; color: #ff0000; text-decoration: line-through;">test&ltg;/span>&ltg;/p>

Actual result:
&ltg;p>&ltg;span style="text-decoration: line-through;">&ltg;span style="font-weight: bold; color: #ff0000; text-decoration: line-through;">test&ltg;/span>&ltg;/span>&ltg;/p>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6327](http://archive.tinymce.com/develop/bugtracker_view.php?id=6327) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_

> _**Tags:** [formats]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/m2daab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
