### ISSUE TITLE
Adding default classes and style attributes for root_block node

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1099]
The forced_root_block is very powerful configuration option in TinyMCE editor because it let you get rid of Br tags and wrap any non block tags in a block element (by default it's a p node)
# The problem is this p node can't be customized by the user if he want to add some HTML attributes (in most case a class and style attributes)

The solution for this problem is to add two configuration options that are set to empty by default to extend the functionality given by forced_root_block config option

Please Spocke, check my pull request on github to check this new feature out.

https://github.com/nhammadi/tinymce/commit/c153495d90581799afb06de0b4afad23af34aded

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6328](http://archive.tinymce.com/develop/bugtracker_view.php?id=6328) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_
> 
> _**Tags:** [editor forced_root_block]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
