### ISSUE TITLE
Untranslateable string "Font Sizes"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1101]
The string "Fonts Sizes" here: 

https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/ui/FormatControls.js#L618

seems to be untranslateable, or at least it doesn't show up in Transifex

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6330](http://archive.tinymce.com/develop/bugtracker_view.php?id=6330) posted by [sonicpictures](http://archive.tinymce.com/profile.php?name=sonicpictures)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
