### ISSUE TITLE
editor.dom.isBlock is returning wrong result

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1104]
Some block HTML elements are not recognized to be a Block Element

Examples:

tinymce.activeEditor.dom.isBlock('body') => false (or it must return true)

editor.dom.isBlock(editor.dom.select('figCaption')[0]) => false /or it's true
# 
# https://developer.mozilla.org/en-US/docs/HTML/Block-level_elements

I found there is many other HTML elements that are not declared in Schema.js file so I made this patch.

https://github.com/nhammadi/tinymce/commit/826848488534276dcb26d74b0fcc3f47f1b00b05

Hope it will solve this Bug.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6334](http://archive.tinymce.com/develop/bugtracker_view.php?id=6334) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_
> 
> _**Tags:** [firefox msie safari chrome opera dom utility isblock]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
