### ISSUE TITLE
Pasting from MS Word: a one-word paragraph with a period at the end gets eaten up

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1106]
Description of problem:

When you paste text from MS Word, a one-word paragraph with a period at the end gets eaten up. This is follow up on the bug reported and closed as fixed here: http://www.tinymce.com/develop/bugtracker_view.php?id=6333 - because the behavior is different now

Steps to reproduce:

1. Copy the multi-paragraph sample text below into a Word document.
2. In the Word document, press Ctrl+A, then Ctrl+C
3. In the TinyMCE Editor, paste the copied text (Ctrl+P).

Expected result: All 5 paragraphs are pasted.

Actual result: Only 3 paragraphs (## 2-4) are pasted. Those one-word with a period at the end (# 1 and # 5) are not pasted.

--- SAMPLE TEXT to copy to the Word document ---

Onewordwithaperiod.
Two words.
Noperiod
Twowords noperiod
Anotherwordwithaperiod.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6370](http://archive.tinymce.com/develop/bugtracker_view.php?id=6370) posted by [wysocki](http://archive.tinymce.com/profile.php?name=wysocki)_

> _**Tags:** [firefox msie safari chrome opera word paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
