### ISSUE TITLE
Better support for video_template_callback

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1109]
Description of problem:
I am writing a web-page where my desire is to override the functions of inserting video. I'm using an iframe that will reference another page, using the i.source1 property inside the parameter.

The embed tab will show the correct text. However, upon clicking OK the text will be altered by tinyMCE, which is not what I want.

I was originally going to report this as a bug, but it's not a bug. This problem is related to how the media plugin wants to render the content, and then read from it again in order for the user to make modifications.

Suggestions: If a user implements a video_template_callback function, have yet another optional callback that allows tinyMCE to grab the source-content from the src property in an &ltg;iframe>.

Thank you!

Steps to reproduce:
1. Open Fiddle link.
2. click media button
3. input fake file-name
4. click Embed tab and notice that the text is correct.
5. click OK.
6. examine the code with the code-plugin to notice that the Embed text is now altered.

Expected result:
&ltg;p>&ltg;iframe id="undefined" name="test_mp4" src="./jplayerFrame.php?src=test.mp4" width="300" height="150">&ltg;/iframe>&ltg;/p>

Actual result:
&ltg;p>&ltg;iframe id="undefined" src="test.mp4" name="test_mp4" width="300" height="150">&ltg;/iframe>&ltg;/p>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6341](http://archive.tinymce.com/develop/bugtracker_view.php?id=6341) posted by [jpcancienne](http://archive.tinymce.com/profile.php?name=jpcancienne)_
> 
> _**Tags:** [mediaplugin video_template_callback iframe]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/G2daab_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
