### ISSUE TITLE
Nested [color] tags broken

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1110]
Description of problem: When using bbcode and textcolor plugins and the forecolor entry on the toolbar it messes up when colours are nested

Steps to reproduce:
1. type in several words of text
2. select a portion of it and apply a colour
3. select a portion of the already coloured portion and apply a different colour

Expected result: text [color=#111111]text [color=#222222] text [/color] text [/color] text

Actual result: text [color=#111111]text &ltg;span style="color#222222"> text [/color] text &ltg;/span> text

Explanation: the conversion to bbcode is finding the nearest &ltg;/span> tag rather than the matching one. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6342](http://archive.tinymce.com/develop/bugtracker_view.php?id=6342) posted by [felgall](http://archive.tinymce.com/profile.php?name=felgall)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
