### ISSUE TITLE
change default numbering

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1111]
Description of problem:
This is a request to change the default behavior of the number list:

Steps to reproduce:
1. Press number list button
2. press enter 3 times to add a new line
3. press the number list button again
4. 
5.

Expected result:
continue with the number list from one to two or have the ability to edit the number list.

Actual result:
A new number list is started instead of the option to continue the number list or change the default numbering

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6344](http://archive.tinymce.com/develop/bugtracker_view.php?id=6344) posted by [mdgulden](http://archive.tinymce.com/profile.php?name=mdgulden)_

> _**Tags:** [firefox msie safari chrome opera list]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
