### ISSUE TITLE
height and width not getting set to 100% when setting the doctype in the parent page

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1112]
Browser: All browsers

When setting the doctype to &ltg;!DOCTYPE html> in the parent page, the editor does not render correctly. I am setting the editor's width to 100% and height to 99%, however, the size is smaller and shows a scrollbar.

FF shows the height and width correctly when setting editor's doctype as 
$wnd.tinyMCE.init({
            doctype : '&ltg;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">',
however, this does not seem to work for IE (since frames in IE always inherit the parent doctype). 

Could you please let me know if there is a fix or a workaround for this.
Thanks
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6345](http://archive.tinymce.com/develop/bugtracker_view.php?id=6345) posted by [karan](http://archive.tinymce.com/profile.php?name=karan)_

> _**Tags:** [firefox msie safari chrome opera doctype]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
