### ISSUE TITLE
Tutorial & functionality to easily add new image placeholders

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1113]
Looking over the image plugin it seem to have an exception not to handle stuff marked as placeholder for the media plugin with class "data-mce-object".  I'm not sure if other homemade modules can piggyback on this and use the same marker for it's own image based placeholders?  If not it would be great to have an option or function call to add more stuff for the image plugin to ignore.

Also a brief (or not, depending on your available time) tutorial on how one might go about making such a plugin with explanation on tinyMCE's flow and usage of the "htmlToData" & parser-like stuff would be awesome.

I think I will manage to make my own google-maps plugin without this, and can tolerate that the image button will be activated at the same time as my maps module button.

But - It would provide future plugin writers with added insight into some of the more complicated parts of tinyMCE and at the same time give way to a whole bunch of interesting plugins, like math expression replacement and so on.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6346](http://archive.tinymce.com/develop/bugtracker_view.php?id=6346) posted by [bubach](http://archive.tinymce.com/profile.php?name=bubach)_
> 
> _**Tags:** [image placeholder]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
