### ISSUE TITLE
ListBox autocomplete

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1116]
There is a problem if you have listbox with a lot of values. Standard selectbox has "autocomplete" - you can write first letter and it scrolls to options started with it.
This feature is missing in ListBox and would be nice to have it there.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6348](http://archive.tinymce.com/develop/bugtracker_view.php?id=6348) posted by [dosercz](http://archive.tinymce.com/profile.php?name=dosercz)_
> 
> _**Tags:** [tinymce4 listbox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
