### ISSUE TITLE
problem image load when focus is not present in textarea

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1118]
Description of problem:

Steps to reproduce:
1.click image button
2.Select file image
3.click button 'ok'

Expected result:

Actual result:
image load out textaera
[edit] not work on IE 8
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6392](http://archive.tinymce.com/develop/bugtracker_view.php?id=6392) posted by [forst](http://archive.tinymce.com/profile.php?name=forst)_

> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
