### ISSUE TITLE
TinyMCE not showing buttong on some IE cleints

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1120]
Description of problem:
Some of our users on IE 8 and IE 9 cannot see the buttons on tinyMCE.  This is not ALL users on IE 8 and IE 9 - only a tiny number of users.

They cannot see the buttons on tinyMCE at the tinyMCE website - it is not just an issue with our application.

I have added the following mimeMaps to my web.config to solve a couple of 404 errors we had.

&ltg;mimeMap fileExtension=".woff" mimeType="application/x-font-woff" />
&ltg;mimeMap fileExtension=".svg" mimeType="image/svg+xml" 

I cannot duplicate this issue on any of our machines but I have attached a screenshot from one of our users that shows the error.  There is also a screenshot with the exact IE9 version numbers (but someone with  IE has also reported the error).

Expected result:  See the tinyMCE buttons/

Actual result: No buttons - just small gray boxes.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6351](http://archive.tinymce.com/develop/bugtracker_view.php?id=6351) posted by [dchamber](http://archive.tinymce.com/profile.php?name=dchamber)_
> 
> _**Tags:** [msie msie8 msie9 webfonts ie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
