### ISSUE TITLE
Support searching only within the selected text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1121]
The searchreplace plugin should have an option to search only within the selected text.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6396](http://archive.tinymce.com/develop/bugtracker_view.php?id=6396) posted by [danransom](http://archive.tinymce.com/profile.php?name=danransom)_
> 
> _**Tags:** [search]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
