### ISSUE TITLE
Update AdvList plugin to catch up with Lists plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1122]
The lists plugin has a number of features that the advlist plugin does not. Specifically:
1. the AdvList plugin does not have the delete/backspace handling that is used by the regular lists plugin
2. the AdvList plugin does not expose any commands or methods so the functions cannot be called outside of the menubar

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6397](http://archive.tinymce.com/develop/bugtracker_view.php?id=6397) posted by [danransom](http://archive.tinymce.com/profile.php?name=danransom)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
