### ISSUE TITLE
Having 2 inline instances of TinyMCE on html inline elements causes issues

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1125]
Description of problem:
In Chrome double clicking the content (if it is a single word) to select it all in the first editor deletes the content of the next inline editor. Firefox doesn't allow double clicking to select and modify the first word in an editor. I couldn't get the jsfiddle to load jquery in IE and didn't try very hard to test it.

Steps to reproduce:
See JS Fiddle

Expected result:
Be able to select and type over content in first editor without it interacting with the second editor

Actual result:
Deletes content in second editor in chrome. Does nothing in Firefox
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6354](http://archive.tinymce.com/develop/bugtracker_view.php?id=6354) posted by [OzzieOrca](http://archive.tinymce.com/profile.php?name=OzzieOrca)_

> _**Tags:** [firefox msie safari chrome opera inline]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/OzzieOrca/jKmZ7/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
