### ISSUE TITLE
Drag and drop possible bug

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1128]
Description of problem: 
The change of image position break the whole text paragraphs. When an editor change the image position by drag and drop to the middle of the other paragraph tinyMCE adds a new p tag inisde this paragraph so when the image is moved again we are left with split in two paragraph. 

Steps to reproduce:
1. Drag and drop the top image to the middle of second or third paragraph.
2. Repeat the first step and drag it to different paragraph.

Expected result:
The paragraph that you dropped the image to should look the same when you started to edit this document.

Actual result:
The paragraph where the image was dropped is now broken from the editorial point of view and it's split into two paragraphs.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6357](http://archive.tinymce.com/develop/bugtracker_view.php?id=6357) posted by [Trandel](http://archive.tinymce.com/profile.php?name=Trandel)_
> 
> _**Tags:** [firefox]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/D4daab_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
