### ISSUE TITLE
In IE buttons not enabled when text dirty

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1130]
Description of problem: I have written a special plugin to handle various save functions I need for my Web site maintenance. Its based in the save plugin supplied. I have set up the toggle routines to enable/disable the buttons when the text is dirty etc. It works fine in Firefox and Chrome with the buttons enable/disabled in line with the state of the text. In IE however you can delete add change etc for ever and the buttons wont change state. Using the IE 10 debugger the events fire off as expected and the code changes the state of disabled however the button remain stubbornly disabled. You can force the issue by clicking on two other button functions (i.e. bullets and bold) then my buttons light up as expected. Just to check that there wasn't something wrong with my code I removed my plugin and set up the conventional save plugin it appears to suffer the same problem. I also noticed that the undo button is not enabled when editing the text it seems to have the same problem. I am using the latest jquery version and use jquery elsewhere for menus etc.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6358](http://archive.tinymce.com/develop/bugtracker_view.php?id=6358) posted by [septesian](http://archive.tinymce.com/profile.php?name=septesian)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** Works For Me_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
