### ISSUE TITLE
Tinymce(version '3.9.1') is not working on firefox version 24.0 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1131]
Description of problem:
I have three textareas using tinymce as text area. They all work in chrome and even with some version's of firefox but not on firefox(version 24). I am loading the text from mysql using rails code. The first textarea loads ok and works, but the other two briefly flashes the contents and then it's gone and also not able to edit the text.

Here is the script :

&ltg;script language='javascript'>
 &ltg;!--
 $(document).ready(function() {
  setTimeout(function(){
    $('#layout_name').focus();   
  },100);
  
  tinyMCE.init({
    mode : "exact",
    elements : "layout_body",
    theme : "advanced",
    theme_advanced_buttons1 : "code,|,img_upload,file_upload,|,bold,italic,underline,strikethrough,|,bullist,numlist,|,justifyleft,justifycenter,justifyright,justifyfull,|,h1,h2,h3,h4,h5,h6",
    theme_advanced_buttons2 : "fontselect,fontsizeselect,|,undo,redo",
		theme_advanced_buttons3 : "",
		theme_advanced_font_sizes : "10pt,11pt,12pt,13pt,14pt,16pt,24pt,36pt,48pt",
		plugins : "inlinepopups,paste,heading",
    // paste_strip_class_attributes: "mso",
    // paste_retain_style_properties: "text-align",
    // paste_preprocess : function(pl, o) {o.content = removeWordFirefoxBug(o.content);},
    paste_postprocess : function(pl, o) {o.node.innerHTML = removeExtraLine(o.node.innerHTML);},
		handle_event_callback : "insertTabs",
    height : "323",
    width : "500",
    setup : function(ed) {
      // Add custom buttons
      ed.addButton('img_upload', {
        title : 'Upload Image',
        image : '/images/btn_upload_image.png',
        onclick : function() {
          tb_show('UPLOAD IMAGE', '/template/upload_s3?modalbox=true&width=320&height=230&type=img', '');      
        }
      });
      ed.addButton('file_upload', {
        title : 'Upload File',
        image : '/images/btn_upload_file.png',
        onclick : function() {
          tb_show('UPLOAD FILE', '/template/upload_s3?modalbox=true&width=320&height=230&type=file', '');
        }
      });
      // Insert spacing into all p tags
      ed.onPostProcess.add(function(ed, o) {
        o.content = o.content.replace(/&ltg;p>/g, '&ltg;p style="padding-bottom: 6pt;">');
      });
    }
  });
});

function saveLayout() {
  var mce = tinyMCE.get('layout_body');
  content = mce.getContent();
  $("#layout_body").val(content);
	$('#current_app').val($('#app').val());
  showSpinner();    
}

function showTxtArea(opt){
  if (opt == "margin"){
    $("#layout_area").hide();
    $("#margin_area").show();
  }else if (opt == "layout"){
    $("#margin_area").hide();
    $("#layout_area").show();
  }
}

function addImageTag(imgName){
  tb_remove();
  imgTag = "&ltg;img src=" + imgName + ">&ltg;br/>";
  tinyMCE.execInstanceCommand('layout_body', 'mceInsertContent', false, imgTag);
  hideSpinner();
}

function addPdfLink(url, filename){
  tb_remove();
  pdfLink = "&ltg;a href='" + url + "'>"+filename+"&ltg;/a>";
  tinyMCE.execInstanceCommand('layout_body', 'mceInsertContent', false, pdfLink);
  hideSpinner();
}

function gotoCopyLayout(){
  showSpinner();
  &ltg;%=remote_function(:url=>{:controller=>"admin", :action=>"copy_printing", :type => "copy_layout", :id => "#{layout.id}" },  :complete=>"hideSpinner()") %>
}
//-->
&ltg;/script>

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6359](http://archive.tinymce.com/develop/bugtracker_view.php?id=6359) posted by [ashish singla](http://archive.tinymce.com/profile.php?name=ashish singla)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
