### ISSUE TITLE
Paste from Word convert paragraphs to numbered list (tinyMCE 4.0.6)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1132]
Description of problem:
Paste from Word convert sometimes paragraphs to numbered list (or the entire paragraph is missing).
It always happens when paragraph starts with a sentence which has only one word.
If there is a plain text from word it doesn't happen. However if there is even a part of text (whatever location it has) for example bold written then a mistake occurs.

Steps to reproduce:
Make new word document with content:
Hello.
This isn�t working properly(properly is bold).
No. I am not sure.
And some additional text.

Expected result:
&ltg;p>Make new word document with content:&ltg;/p>
&ltg;p>Hello.&ltg;/p>
&ltg;p>This isn�t working &ltg;strong>properly&ltg;/strong>.&ltg;/p>
&ltg;p>No. I am not sure.&ltg;/p>
&ltg;p>And some additional text.&ltg;/p>

Actual result:
&ltg;p>This  isn�t working &ltg;strong>properly&ltg;/strong>.&ltg;/p>
&ltg;p>And some additional text.&ltg;/p>

or 

&ltg;ol>
&ltg;li>&ltg;/li>
&ltg;/ol>
&ltg;p>This isn�t working &ltg;strong>properly&ltg;/strong>.&ltg;/p>
&ltg;ol>
&ltg;li>&ltg;/li>
&ltg;/ol>
&ltg;p>And some additional text.&ltg;/p>

Plugins:
advlist, autolink, link, image, lists, charmap, print, preview, hr, spellchecker, searchreplace, wordcount, visualblocks, visualchars, code, fullscreen, nonbreaking, table, contextmenu, directionality, emoticons, textcolor, paste
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6360](http://archive.tinymce.com/develop/bugtracker_view.php?id=6360) posted by [kohout](http://archive.tinymce.com/profile.php?name=kohout)_

> _**Tags:** [firefox msie safari chrome opera paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
