### ISSUE TITLE
Editor "blur" event is incorrectly fired inside a modal

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1136]
Description of problem:

When using tinyMCE (4.0.6) inside a Bootstrap's modal dialog, when clicking inside the editor (not on the text, but on the whitespace between the text and the bottom border) the "blur" event is fired.
I debugged it a little bit and saw that when clicking inside the editor, getActiveElement() that is used to check the focus/blur returns the modal div element.
When not inside a modal, the function correctly returns the iframe element.
So what happens eventually is the editor thinks it should fire "blur" event according to this line:
if (!isUIElement(getActiveElement()) && focusedEditor == editor)

Steps to reproduce:
1. Open the fiddle
2. Click on the button to open the modal
3. Open the browser console
4. Click on the whitespace between the editor text and the editor bottom.
Clicking on the text itself does not cause an issue
5. a message is written to the console due to "blur" event being incorrectly fired

Expected result:
"blur" event not fired when clicking the mentioned area
Actual result:
"blur" event fired

Another note:
This issue doesn't reproduce on Firefox and IE, only on latest Chrome. Didn't check other browsers.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6363](http://archive.tinymce.com/develop/bugtracker_view.php?id=6363) posted by [ohana54](http://archive.tinymce.com/profile.php?name=ohana54)_
> 
> _**Tags:** [chrome blur focus modal dialog]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/atQ55/4/_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
