### ISSUE TITLE
Pasting formated text on zoomed page add spans in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1137]
When the page with TinyMCE in Chrome is zoomed to more than 100% eg 125% while editing  pasted text it add sometimes span elements: &ltg;span style="font-size: 11px;"> around texts. Tested in Firefox too and it works well there.

Steps to reproduce it in Chrome with 2 TinyMCE editors on page:
1. Type 2x "test" into tinymce editor - it produces html "&ltg;p>test&ltg;/p>
&ltg;p>test&ltg;/p>"
2. Zoom page to 125%
3. Select text and copy it with Ctrl+C
4. Insert into another TinyMCE editor with Ctrl+V
5. Select first paraghaph and delete text with Del and blank paragraph with Backspace
6. Check source code and you will see "&ltg;p>&ltg;span style="font-size: 11px;">test&ltg;/span>&ltg;/p>" instead of right "&ltg;p>test&ltg;/p>"

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6364](http://archive.tinymce.com/develop/bugtracker_view.php?id=6364) posted by [dosercz](http://archive.tinymce.com/profile.php?name=dosercz)_
> 
> _**Tags:** [chrome chrome paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
