### ISSUE TITLE
Spaces are transformed to &nbsp; on paste

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1138]
It's an edge case, but you know...

Spaces (made with spacebar) gets transformed into &nbsp; when copy-pasting one word + a space within the editor.

Steps to reproduce:
1. Write one (only one!) word followed by a space
2. Select all and copy-paste several times

Expected result:
The word + space are pasted several times, producing breakable content on frontend.

Actual result:
The space are transformed into a non-breaking spaces, resulting in a non-breakable content on the frontend.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6365](http://archive.tinymce.com/develop/bugtracker_view.php?id=6365) posted by [jezzdk](http://archive.tinymce.com/profile.php?name=jezzdk)_

> _**Tags:** [paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
