### ISSUE TITLE
Incorrect Menu Appearance In IE 8

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1143]
Description of problem:
Not able to see menu options from Formats Sub Menus

Steps to reproduce:
1.Open url http://www.tinymce.com/tryit/full.php in IE8
2.Once editor get loaded(example), click on Formats menu.
3.Hover on sub menus e.g. Header/Inline/Blocks
4.Observer the menu's appearance. They do not appears properly.

Expected result:
Menus should appear properly in all browsers.

Actual result:
Menus are not appearing properly.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6421](http://archive.tinymce.com/develop/bugtracker_view.php?id=6421) posted by [saagar.yadav](http://archive.tinymce.com/profile.php?name=saagar.yadav)_

> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/full.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
