### ISSUE TITLE
Table alignment prevents inner alignment

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1146]
Description of problem:
Can't align the contents of the table to the same alignment of the table

Steps to reproduce:
1. insert a table
2. go into table properties
3. choose alignment (other than "none") [example: "center"]
4. align the content of the table to the same alignment chosen in section 3 [example: "center"]

Expected result:
table will be aligned to the [center].
content of the table cell will be aligned to the [center].

Actual result:
(V) table is aligned to center
(X) content of the table CAN'T be aligned to the center and the "align center" button is already checked. (it is checked once you change the alignment of the table)
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6371](http://archive.tinymce.com/develop/bugtracker_view.php?id=6371) posted by [tomlevy](http://archive.tinymce.com/profile.php?name=tomlevy)_

> _**Tags:** [table align]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
