### ISSUE TITLE
Problems orizzontal scroll on very large images on ipad

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1147]
You can reproduce the problem usingo demo (tinymce version 4.0.7) with ipad.
Inserting a very large image, the scroolbar are not shown and the image the image overwrites the right part of the page.
Se the attachement.

The problem is similar to the following bug http://www.tinymce.com/develop/bugtracker_view.php?id=5947

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6372](http://archive.tinymce.com/develop/bugtracker_view.php?id=6372) posted by [fferraiu](http://archive.tinymce.com/profile.php?name=fferraiu)_
> 
> _**Tags:** [safari safari6 ipad image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
