### ISSUE TITLE
transparent window

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1148]
Description of problem:
On Safari Mobile (Ipad) opening a dialog menu in a TinyMCE textarea will cause the cursor is visible through the opened dialog menu window

Steps to reproduce:
1. Start a start a function where it is present TinyMCE
2. Put the focus on the TinyMCE textarea
3. Open dialog window (ex: edit)
4. See the cursor through the dialog window

Expected result:
I expect the dialog has a "solid" color and I expect the cursor is hidden

Actual result:
The cursor is visible through the dialog window
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6373](http://archive.tinymce.com/develop/bugtracker_view.php?id=6373) posted by [mauro.villani](http://archive.tinymce.com/profile.php?name=mauro.villani)_

> _**Tags:** [safari]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
