### ISSUE TITLE
Focus failed on touch IOS

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1154]
Description of problem:
On Safari mobile focus on a TintMCE textarea is difficult to perform touching any point of the area without text. The only thing to do is to touch perfectly the end of the text inserted, or the last blank line.

Steps to reproduce:
1. Open a TinyMCE textarea on a Safari mobile browser
2. Get the focus of the textarea touching a blank space (not the text inserted)
3. Try to delete all the text
4. Loose the focus outside the textarea
5. Get the foucus of the textarea touching the blank area.

Expected result:
We expect the focus will trigger touching any blank space in the textarea and giving the cursor at the end of the text inserted.

Actual result:
The cursor appears only touching perfectly the end of the last blank line.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6378](http://archive.tinymce.com/develop/bugtracker_view.php?id=6378) posted by [mauro.villani](http://archive.tinymce.com/profile.php?name=mauro.villani)_

> _**Tags:** [safari]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
