### ISSUE TITLE
Paragraph with width inside edited box - cannot edit content in IE 10

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1156]
Description of problem:

I have an tinymce-editable box. Inside this box there is a paragraph, which has its width set by css. 

In Chrome/Firefox, I can just click inside this paragraph and edit its text content. 
In IE, If I click on it, its boundaries show up and I can drag-edit its height and width, but there is no way I can edit the text inside. 

I don't know, which behavior is correct and which is a bug, but it's not consistent and that's enough to bother me :-)

Submited link contains working simple demo of this problem

Steps to reproduce:
1. Create editable &ltg;div> with &ltg;p> inside
2. Set WIDTH to &ltg;p> by CSS
3. Enable tinymce-editing on &ltg;div>
4. Try to click &ltg;p> in IE and Chrome

Expected result:
The same behavior in both browsers - either size-editing or content editing. Maybe even both, but content-editing is more important.

Actual result:
Content editing in Chrome, size editing in IE 10.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6379](http://archive.tinymce.com/develop/bugtracker_view.php?id=6379) posted by [TheTomCZ](http://archive.tinymce.com/profile.php?name=TheTomCZ)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.char-t.com/tinymce/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
