### ISSUE TITLE
Page up causes viewport change

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1157]
Description of problem:
If you have a various strange margins set on the page (we do, but I don't know the reasoning), then after entering some content, hitting the page up key causes the viewport to shift to the right.

Steps to reproduce:
1. Open http://sandpit.andrewrn.co.uk/brokenscroll.html
2. Page down to the editor
3. Enter some basic content
4. Hit page up

Expected result:
Page scrolls appropriately up

Actual result:
TinyMCE is scrolled to the top (okay - not a problem)
TinyMCE is scrolled to the left (not okay - can't move back)

I've seen similar behaviour with scrollIntoView() or something before, but I can't remember how I replicated it now.

Does not affect IE10, Firefox (Linux). Haven't checked others yet.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6384](http://archive.tinymce.com/develop/bugtracker_view.php?id=6384) posted by [andrewnicols](http://archive.tinymce.com/profile.php?name=andrewnicols)_

> _**Tags:** [chrome]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://sandpit.andrewrn.co.uk/brokenscroll.html_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
