### ISSUE TITLE
Not seeing images such as preview bold etc after deploying to server. same as bug report 6351

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1161]
Description of problem:

Steps to reproduce:
1.the mouse over works
2.but the button images are missing
3.Bold,Italic,print,preview
4.I can see them in my debugger
5.in version 4.08 I have to mouseover 1 button to get images to load in my debugger
6.on the server after deployment images still do not load
7. I have added screen shot and reproduced the bug using your website 

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6383](http://archive.tinymce.com/develop/bugtracker_view.php?id=6383) posted by [dsjacobs](http://archive.tinymce.com/profile.php?name=dsjacobs)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
