### ISSUE TITLE
IE8 in compatibilty mode does not center preview window

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1162]
Description of problem:

Steps to reproduce:
1.IE8 in compatibilty mode does not center preview window
2.When you uncheck the compatibility mode of IE8 the preview window centers
3.When you check the compatibility mode of IE8 the preview window moves to the right
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6385](http://archive.tinymce.com/develop/bugtracker_view.php?id=6385) posted by [dsjacobs](http://archive.tinymce.com/profile.php?name=dsjacobs)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
