### ISSUE TITLE
Allow the readonly option to be changed after init

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1171]
Currently changing the readonly setting after the editor has loaded does not change the contenteditable setting of the editor, nor does it disable the menubar or toolbar.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6395](http://archive.tinymce.com/develop/bugtracker_view.php?id=6395) posted by [danransom](http://archive.tinymce.com/profile.php?name=danransom)_
> 
> _**Tags:** [readonly]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
