### ISSUE TITLE
tinymce.execCommand

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1172]
Description of problem:

tinymce.execCommand("mceInsertContent",false,html); 

where html is the content to be inserted in to the editor does not insert the content to the place where the user keeps the cursor. This works fine in chrome & FF but not in IE.
 
please guide if there's any solution for this.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6398](http://archive.tinymce.com/develop/bugtracker_view.php?id=6398) posted by [aship](http://archive.tinymce.com/profile.php?name=aship)_

> _**Tags:** [msie msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
