### ISSUE TITLE
External media list

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1173]
TinyMCE 3.X used to have a feature which allowed to give a list of media files, similar to external image list. This is apparently no longer present in 4.X.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6399](http://archive.tinymce.com/develop/bugtracker_view.php?id=6399) posted by [Atao](http://archive.tinymce.com/profile.php?name=Atao)_
> 
> _**Tags:** [media external]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
