### ISSUE TITLE
Image Constrain Proportions minor issue

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1179]
Description of problem:

Steps to reproduce:
1. Insert/Edit Image and choose (or click on existing image and Insert/Edit Image)
2. Tick Constrain Proportions
3. enter really low value like 1 for either height or width then immediately click OK
4.
5.

Expected result:
Proportions should be constrained

Actual result:
Image proportions are not constrained

It works fine if you move focus to another element on the form other than the OK button but when you immediately click ok it doesn't first update the proportions.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6405](http://archive.tinymce.com/develop/bugtracker_view.php?id=6405) posted by [cep](http://archive.tinymce.com/profile.php?name=cep)_

> _**Tags:** [firefox msie chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
