### ISSUE TITLE
Spaces between words are lost after upgrade from 3.3.9.2

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1182]
Description of problem:

After an upgrade from 3.3.9.2 to 3.5.8, we discovered that some of the HTML content previously entered using TinyMCE was missing spaces between the words. On inspection, we noticed that the HTML contained constructs along the lines of:

&ltg;font face="Arial">Hello&ltg;/font>&ltg;font face="Arial"> &ltg;/font>&ltg;font face="Arial">World&ltg;/font>

as well as:

&ltg;font face="Arial">&ltg;strong>Hello&ltg;/strong>&ltg;/font>&ltg;font face="Arial">&ltg;strong> &ltg;/strong>&ltg;/font>&ltg;font face="Arial">&ltg;strong>World&ltg;/strong>&ltg;/font>

Not sure where this came from (it was user-entered content), although my suspicion would be that it was pasted from Word, possibly without using the "paste from Word" feature. Regardless of its origins, TinyMCE shouldn't break the existing code - ideally it should even clean it up.

Steps to reproduce:
1. Load in content that contains HTML as described above (see fiddle URL to view the full HTML that was causing the issue)

Expected result:

Expect to see HTML rendered with spaces between the words, ideally being cleaned up in the process.

Actual result:

The elements containing only spaces are removed.

Workaround:

I added the following to Node.isEmpty just before the "Keep non whitespace text nodes" line to work around it. I'm sure there's a better way to fix it though.

if (whiteSpaceRegExp.test(node.value))
{
	nodeparent = node;
	while (nodeparent = nodeparent.parent)  // assignment
	{
		if (nodeparent.name === "font")
		{
			return false;
		}
	}
}

This may be related to bug #4915.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6468](http://archive.tinymce.com/develop/bugtracker_view.php?id=6468) posted by [crispygoth](http://archive.tinymce.com/profile.php?name=crispygoth)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/XBdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
