### ISSUE TITLE
addToTop (3.x tinymce.util.Dispatcher ) functionality in 4.x

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1183]
tinymce.util.Dispatcher in 3.x has "addToTop" for adding an event listener to the head of the listeners array. tinymce.util.Observable is responsible for binding and dispatching events in 4.x, but it only includes an "on" method.

Adding an event to the head of the listeners array (handlers array in 4.x) is useful if a plugin wants to intercept the enter key, for example, before tinymce.EnterKey has a chance to create a new block.

Was this functionality deliberately removed from 4.x, or has it just not been implemented?

I think the use case is compelling enough to add the functionality back.

Either an "onTop" method could be added to Observable, or "on" could be updated to take an options object where top could be specified like: {top: true}.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6408](http://archive.tinymce.com/develop/bugtracker_view.php?id=6408) posted by [dnerdy](http://archive.tinymce.com/profile.php?name=dnerdy)_
> 
> _**Tags:** [tinymce4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
