### ISSUE TITLE
API to change Button icon

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1185]
I want to create a button which indicates some state (alignment in this case) by an icon. The Button class exposes a text() method to change text at runtime, but does not have an API for changing the icon.

Please implement a method icon() for this, image() would be appropriate too.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6411](http://archive.tinymce.com/develop/bugtracker_view.php?id=6411) posted by [mburtscher](http://archive.tinymce.com/profile.php?name=mburtscher)_
> 
> _**Tags:** [4x api]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
