### ISSUE TITLE
Anchors are getting stripped out from links of list items if selection starts from end of the previous list item

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1186]
Description of problem:
I could reproduce it from tinyMCE site itself. The anchor tag is getting stripped out from links when deleting a list item with a link below it.
Steps to reproduce:
1. Click on Try It link from tinymce site, clear all contents.
2. Click on list item and create few list items and add links to them
3. Put your cursor at the end of the second item and drag down to select the third item.
4. Click delete, check the view source the anchor link on secod list item is gone.
5. Works fine in Chrome, but does n't work in FireFox.
Expected result:
Links should not be removed.
Actual result:
Links are getting stripped out.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6470](http://archive.tinymce.com/develop/bugtracker_view.php?id=6470) posted by [jbsrao](http://archive.tinymce.com/profile.php?name=jbsrao)_

> _**Tags:** [firefox list anchor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.screencast.com/t/rLqfAlEZ_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
