### ISSUE TITLE
IE7 MenuItem postRender function

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1187]
Description of problem:

Steps to reproduce:
1.add a menu every item have styles
2.IE7 open the menu,the preview style nor apply
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6412](http://archive.tinymce.com/develop/bugtracker_view.php?id=6412) posted by [jacky](http://archive.tinymce.com/profile.php?name=jacky)_

> _**Tags:** [msie msie7 menu]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
