### ISSUE TITLE
Bug in formatter.match function when using variable in format.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1189]
Description of problem:
As you can see in above fiddle, formatter.match method doesn't work correctly when you are using variable in format definition.
Please be aware that if you use variable same as the following definition, It works correctly. But this is not suitable for my purpose because it removes other classes.
fontsizeclass: { inline: 'span', selector: 'span,p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table', attributes: { 'class': '%value' } }
I must use variable in classes section.

Expected result:
If you type any thing in above fiddle and select one item from fontsize dropdown list, a class will be added to node. But when you select the node match method return false!

Actual result:
match method must return true in this case.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6472](http://archive.tinymce.com/develop/bugtracker_view.php?id=6472) posted by [armanforghani](http://archive.tinymce.com/profile.php?name=armanforghani)_
> 
> _**Tags:** [firefox msie safari chrome opera formatter match variable format]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/iCdaab/3_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:

**Comment by jerryorr** [comment]
This is still an issue as of 4.6.4, so I put in a PR to fix it (test included).
