### ISSUE TITLE
Wrong image handle location when editor is in a table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1195]
Description of problem:

The image handles show up in the wrong location if the editor is inside a table cell.

Steps to reproduce:
1. Create a table
2. Add a div in one of the cells
3. Setup the editor as inline
4. Open the editor
5. Add an image
6. Attempt to resize it

Expected result:

The image handles surrounding the image

Actual result:

The image handles are usually above and to the left if there is space.

Additional Notes:

It appears to be a result of this code:

		function showResizeRect(targetElm, mouseDownHandleName, mouseDownEvent) {
			var position, targetWidth, targetHeight, e, rect;

			// Fix when inline element is within a relaive container
			var offsetParent = editor.getBody().offsetParent || editor.getBody();

The offsetParent will be the table cell.

I don't know what the side effects of this are, but if you tweak the code such that the offsetParent is always the body element then it appears to work correctly in my narrow scope.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6419](http://archive.tinymce.com/develop/bugtracker_view.php?id=6419) posted by [sonstone](http://archive.tinymce.com/profile.php?name=sonstone)_

> _**Tags:** [safari chrome safari6 table image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/88daab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
