### ISSUE TITLE
Tab key press not working even after adding "tab focus" plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1196]
Description of problem:

Steps to reproduce:
1.Create a form
2.First element is any text field
3.Second element should be RTE
4.Press tab key it goes to text field but not into RTE
5.It stucks at first tool bar element for example "B" bold.

Expected result:
It should navigate through all toolbar elements and then to editor

Actual result:
Only first toolbar element is accessible by tab key.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6477](http://archive.tinymce.com/develop/bugtracker_view.php?id=6477) posted by [vkumarpal](http://archive.tinymce.com/profile.php?name=vkumarpal)_

> _**Tags:** [msie msie8 msie9 tab key press]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by rakeshkrishnan** [comment]
As I am using tinymce 4.8.5 in my application and tab is not working for the controls which has tinymce editor. Other controls does not have tinymce editor are working as expected.
Please help me on this.

**Comment by blackcathikari** [comment]
@rakeshkrishnan This ticket is quite old, and has been closed. Please create a new ticket for your problem, and please include a replication case using [fiddle.tinymce.com](fiddle.tinymce.com) if possible.
