### ISSUE TITLE
version 4.0.10 blocked in chrome 30.0.1599.101m when init

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1197]
Description of problem:
I use the last version tinymce 4.0.10, when we open the page in chrome, the tinymce block 4s--6s, and the whole page stop. I remove all the plugins but the same thing happen
Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6479](http://archive.tinymce.com/develop/bugtracker_view.php?id=6479) posted by [jacky](http://archive.tinymce.com/profile.php?name=jacky)_

> _**Tags:** [chrome blocked chrome init]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
