### ISSUE TITLE
Editor height randomly uses full browser height

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1199]
Description of problem:
I initialize TinyMCE in a function once the content of the editable DIV has been loaded via jquery ajax after the user selects the content they want to load. I am using a few customized buttons and a jquery intercept of the button click to "modify" an editor menu (=show/hide options in the menu) depending on what was loaded via ajax.
Every 10 to 15 page reloads, the editor screen goes from normal to the height of the content of the page.

Steps to reproduce:
No idea - reload the page 10-15 times does it for me...

I attached some pictures that hopefully will help. One shows the Firebug output of the mce section of the code. It clearly shows how the height of the two main elements is over 1,000px.

I'm not sure I can easily create a fiddle from this since there is a lot of PHP and ajax involved, so I hope this can be solved without it.

If this is a known issue and there is a fix for this, please let me know at rlund@lunds.us - thanks.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6482](http://archive.tinymce.com/develop/bugtracker_view.php?id=6482) posted by [semmel](http://archive.tinymce.com/profile.php?name=semmel)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
