### ISSUE TITLE
IE: Bullet list loses first style with multiple styles

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1204]
Description of problem:
If a bulleted list uses bold, italic, or underline formatting and the user adds another bullet to the list then wants to add additional formatting using the formatting icons from the toolbar, the previous formatting is lost when the new formatting is added.

Steps to reproduce in IE9 & IE10:
1. Go to: http://www.tinymce.com/index.php and use the example instance 4.0.9 (this also occurs in 4.0.7)

2. Clear the default content and select the "Bullet" icon to start a bullet list

3. Select the "Bold" icon from the toolbar and then type word(s) in bold

4. Return to add a new bullet list item and while leaving "Bold" selected, add the "Italic" formatting to this new item from the toolbar

5. You'll notice that "Bold" is no longer selected and you have to reselect it

Expected result:
The selected formatting should persist until turned off in IE as it does in other browsers.

Actual result:
Formatting is lost/mismatched while creating a bullet list in IE9 & IE10.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6427](http://archive.tinymce.com/develop/bugtracker_view.php?id=6427) posted by [kpaul](http://archive.tinymce.com/profile.php?name=kpaul)_

> _**Tags:** [msie msie9 msie10 bullet ie styles]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
