### ISSUE TITLE
script-inclusion breaks getAttribute of HTML element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1207]
Description of problem:

Just including the tinyMCE 4.0.10 script in a page breaks the getAttribute method of the html element. The error seems similar to when the getAttribute property of the element has been deleted.

Steps to reproduce:
1. Open the accompanying fiddle in IE7

Expected result:

A popup saying something along the lines of "function () { [native code] }"

Actual result:

An "Object doesn't support this property or method" error
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6488](http://archive.tinymce.com/develop/bugtracker_view.php?id=6488) posted by [PSPvZ](http://archive.tinymce.com/profile.php?name=PSPvZ)_

> _**Tags:** [msie msie7]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/6Ddaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
