### ISSUE TITLE
Incorrect positioning of tooltips and link/image lists

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1209]
Description of problem:
The positioning of tooltips and lists within a modal window (image lists, target lists, link lists) is incorrect when a TinyMCE instance is not at the top of a page and the page is scrolled. Tooltips and lists within a modal window seem to receive an offset that is the same as the scroll amount of the page.

Reproducable in Safari 6.x and Google Chrome version 30.0.1599.101 (the current version) on Mac. Firefox and Opera on Mac do not display this behavior. Not yet tested on Windows. The same problem seems to occur in Safari on iOS7.

Steps to reproduce:
1. Add a TinyMCE instance to page the regular way.
2. Add enough height to the TinyMCE instance in tinymce.init to make sure the webpage will have a scrollbar (depends on your monitor).
3. Insert a p element with a height of 400px before the form containing TinyMCE (any extra height will do to display the issue, but 400px just makes it very clear).
4. Open the page in Safari or Chrome and scroll down.
5. Mouse over the buttons and use the target list in the link modal.

Expected result:
Tooltips and lists within a modal window (image lists, target lists, link lists) should have a position that is locked to the instance of TinyMCE or locked to the modal window.

Actual result:
Positions of tooltips and lists within a modal window (image lists, target lists, link lists) seem locked to the scroll position of the page.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6432](http://archive.tinymce.com/develop/bugtracker_view.php?id=6432) posted by [Wouter Jansen](http://archive.tinymce.com/profile.php?name=Wouter Jansen)_

> _**Tags:** [safari chrome safari6 chrome13]_
> _**Status:** Closed_
> _**Resolution:** Fixed_
> _**Attached URL:** http://fiddle.tinymce.com/79daab_

**Comment by timmetj** [comment]
Issue still present in V4.2.8

When you put TinyMCE inside a modal the tooltip position is wrong. I see that the Div wich holds the tooltips is placed at the bottom of the <Body>. It needs to go inside the modal as well i think
