### ISSUE TITLE
Firefox paragraph bolding error

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1212]
Description of problem: I'm using Firefox 24 on Mac OS X (Snow Leopard) but this problem occured Firefox on PC/Windows too (don't know the version). Using editor with inline option true. 

When you click mouse pointer to a word in a paragraph (&ltg;p>&ltg;/p>) to activate the editor and after that select all text in some other paragraph to be bold, editor changes the word style bold but not the style of the selected text. Occure with ITALIC button too.

I tried this too with Inline Editing Example on this site and there's image attached to show the steps. 

Steps to reproduce: 
1. Click a word in a paragraph to activate inline editor.
2. Select all text in another paragraph with mouse
3. Hit the BOLD button

Expected result: Selected text should be bold

Actual result: Word clicked to activate the editor changes to bold

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6435](http://archive.tinymce.com/develop/bugtracker_view.php?id=6435) posted by [jony](http://archive.tinymce.com/profile.php?name=jony)_

> _**Tags:** [firefox firefox bold inline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
