### ISSUE TITLE
Incorrect highlight for inline tags

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1213]
Steps to reproduce:
1. Select some text.
2. Bold it.
3. Start new selection in the middle of bold text and end it on normal text.

Expected result: "B" icon should not be highlighted.

Actual result: "B" icon is highlighted. "B" should be highlighted only if start and end of the current selection are in bold AND if this is the same bold tag. Algorithm from other editors goes like:
1. Get selection start. Get parent node.
2. Get selection end. Get parent node.
3. Compare if selection start parent node and selection end parent node are the same. If so, highlight "B". If not, do not highlight.

Please check Microsoft Word to understand this better. They do it right in my opinion.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6437](http://archive.tinymce.com/develop/bugtracker_view.php?id=6437) posted by [Trevlon](http://archive.tinymce.com/profile.php?name=Trevlon)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
