### ISSUE TITLE
Chrome bug when applying a format to multiple paragraphs

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1222]
Description of problem:
In Chrome, the selection changes when applying a format to two or more selected paragraphs.

Steps to reproduce:
1. Use the Inline editing example.

2. Triple click on any word in the 1st paragraph, and be sure to keep the mouse button pressed on the 3rd click.

3. With the mouse button still pressed, drag the mouse downward to include one or more additional paragraphs in the selection. Do not include the last paragraph.

4. Apply a format -- e.g., bold or italics.

5. The selection unexpectedly changes, and the format gets applied to the paragraph(s) in the new selection.

It seems that the 'adjustSelectionToVisibleSelection' function in the editor.formatter.apply method is causing this bug in Chrome. The selection does not unexpectedly change if that function is not invoked.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6449](http://archive.tinymce.com/develop/bugtracker_view.php?id=6449) posted by [jashua212](http://archive.tinymce.com/profile.php?name=jashua212)_

> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
