### ISSUE TITLE
Getting then setting range loses cursor position in IE8

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1223]
Description of problem: Getting range in IE8 appears to be broken, causing mceInsertContent to insert at the wrong location.

Steps to reproduce:
1. Open IE8 on Windows XP
2. Go to http://fiddle.tinymce.com/CAdaab/3
3. Put your cursor somewhere inside the editor text
4. Press the Go button below the editor

Expected result:
Since we just got then set the same range, the image should be inserted where the cursor was.

Actual result:
getRng returns an empty range, so the image is inserted at the top of the document.

You can check http://fiddle.tinymce.com/CAdaab/2 for the same test without the get/setRng calls, which works properly. This is an IE8-specific problem; both work properly in IE9+. Note this is also an issue in the TinyMCE 3.x branch.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6450](http://archive.tinymce.com/develop/bugtracker_view.php?id=6450) posted by [Sb87](http://archive.tinymce.com/profile.php?name=Sb87)_

> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/CAdaab/3_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
