### ISSUE TITLE
Responsive Dialog Boxes

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1224]
Description of problem:

Although the main editor window resizes to fit the screen or container window, the dialog boxes and dialog content do not. They have a number of fixed widths embedded.

Steps to reproduce:
1. Resize your browser to around 320px wide
2. click the 'Link' button 

Expected result:

The dialog to format nicely in my screen so I can see all the available featured easily without the need of horizontal scroll.

Actual result:

Dialog is positioned off ot the side with much of the dialog outside the view able window. User must scroll horizontally to access the rest of it.

This is really quite a nessarry upgrade in these days with mobile browsing is more and more popular. Fixed widths are a big no no. Usage of max-width in CSS and CSS media queries would be the way forward. Alternativly, creating a Twitter Bootstrap based editor might be a plus as it's one of the most popular responsive frameworks and the default design lends itself to it.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6451](http://archive.tinymce.com/develop/bugtracker_view.php?id=6451) posted by [davidb2002](http://archive.tinymce.com/profile.php?name=davidb2002)_
> 
> _**Tags:** [firefox msie safari chrome opera responsive mobile css javascript]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
