### ISSUE TITLE
Table width is not a style

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1230]
After set table properties in HTML is this code

&ltg;table style="height: 200px;" width="700">

This code ist not working,
but change with Inspector to this code works:

&ltg;table style="height: 200px; width: 700px;">

Can you change this to style-attributes only? Thanks.

tinymce 4.0.11

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6510](http://archive.tinymce.com/develop/bugtracker_view.php?id=6510) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
