### ISSUE TITLE
two lines show when underlinig text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1232]
Description of problem: Two lines appear under underlined text. 

Steps to reproduce:
1. Change text colour.
2. Change font size.
3. Click on underline.
4. There are two lines under text.
5.

Expected result:There should only be one line in the same colour and format as the text.

Actual result: Additional thin black line appears under the text.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6457](http://archive.tinymce.com/develop/bugtracker_view.php?id=6457) posted by [annan](http://archive.tinymce.com/profile.php?name=annan)_

> _**Tags:** [firefox msie safari chrome opera underline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
