### ISSUE TITLE
Advanced tab in image plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1233]
Description of problem:
The input fields no longer work in the Advanced tab for the image plugin. If you input any value in, e.g., vertical space or horizontal space, and then press 'Ok', the image's style property no longer gets updated.

The input fields in the Advanced tab were working as expected in 4.0.6. This bug seems to have started with version 4.0.7.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6458](http://archive.tinymce.com/develop/bugtracker_view.php?id=6458) posted by [jashua212](http://archive.tinymce.com/profile.php?name=jashua212)_

> _**Tags:** [image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
