### ISSUE TITLE
Link plug-in uses "Insert/edit link" in toolbar icon but "Insert link" in menu and context menu

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1237]
See title.

A proposal is to use "Insert/edit link" in the menu and context menu as well. Do you think that is the right way? Could make a pull request in that case.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6526](http://archive.tinymce.com/develop/bugtracker_view.php?id=6526) posted by [fornwall](http://archive.tinymce.com/profile.php?name=fornwall)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
