### ISSUE TITLE
problem with inserted HTML element in table.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1239]
Description of problem:

in IE8 or less, the inserted html element becomes resizable.
funny thing is that modern browsers doesn't allow this to happen.

when you insert an html element, then there's gotta be some reason for it.
I mean, you don't expect any change or resize on the element.

But it happens in IE8.

And this is actually not related to the functionality of the editor,
when you click on the table, the cursor changes to 'move' shape.
and whereever you mouseover, it never changes to 'default' status.

as far as I know, it is designed to show users that it will be moving rightward, upward, or to diagonal direction. but it only shows 'move' shape... even when the table isn't draggable. I don't want this feature too.

is there any option for this? or is it a bug? or is it related to css or table plugin?

Steps to reproduce:
1. be sure to test this in IE8 or less
2. try to click on the red div box.
3. then handles appear.
4. and you can resize the div box.

Expected result: 

no resizing on the box is allowed if stopPropagation, preventDefault, or returnValue = false code are set in the code...

Actual result:

enabling resizing...

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6466](http://archive.tinymce.com/develop/bugtracker_view.php?id=6466) posted by [hina10531](http://archive.tinymce.com/profile.php?name=hina10531)_
> 
> _**Tags:** [msie msie7 msie8 html div table plugin]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/GBdaab/1_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
