### ISSUE TITLE
Inserting Table with Caption (IE10)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1243]
Description of problem: The newly inserted table in IE10 does contain caption even if the check box "Table caption" has been selected 

Steps to reproduce (Tested in 3.5.8):
1. Click "Insert/Edit Table" button. The "Insert/Edit Table" dialog appears.
2. Select the Checkbox "Table caption"
3. Click "Insert"

Expected result: A new table with caption is inserted.

Actual result: A new table without caption is inserted.

Possible solution: See the table plug-in. The table.js file has to be modified. The line html += '&ltg;caption>&ltg;/caption>';  can be substituted with
 html += '&ltg;caption>&nbsp;&ltg;/caption>';

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6474](http://archive.tinymce.com/develop/bugtracker_view.php?id=6474) posted by [viktorb](http://archive.tinymce.com/profile.php?name=viktorb)_

> _**Tags:** [msie msie10 table plugin caption header]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
