### ISSUE TITLE
Parent div duplication bug with Firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1244]
Description of problem:

I have fully explained the problem in the TinyMCE forum (first message): http://www.tinymce.com/forum/viewtopic.php?id=32974. The only difference to the problem description is that I have noticed that this problem lies only in Firefox. In Internet Explorer you have little graphical bug with this problem too when you edit the page, but the source code is done correctly.

I have created a test website to verify the problem: http://desertive.net/test/ (TinyMCE's init source code: http://pastebin.com/pjWkAaa6)
1. Log in with Username "test" and password "test"
2. Click the "Start"-box (it brings TinyMCE's inline texteditor)
3. Remove the content (i.e. "File" -> "New Document")
4. Add a template ("Insert" -> "Insert template" -> "One box")
5. Select both paragraphs and replace them with your own text
6. Press enter and it will create another div insted of the paragraph!

I did a three-step demoimage from the last two steps of the instructions (attachement).

So to keep it simple: the div should NOT duplicate. The paragraph tag should be duplicated instead. The problem lies in replacing the template paragraphs when the p-tag disappears.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6476](http://archive.tinymce.com/develop/bugtracker_view.php?id=6476) posted by [Desertive](http://archive.tinymce.com/profile.php?name=Desertive)_

> _**Tags:** [firefox firefox8 firefox paragraph div duplicate bug]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://desertive.net/test/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
