### ISSUE TITLE
foced_root_block: Problem with link and new line 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1245]
Go to demo or my fiddle. Insert a text, select text and set a anchor. Go with cursor to end of line and press enter. The new line is not standard text, its always the link above.

I think this is a bug or is here a setting that I miss? Thanks. :)

ADD:

In Firefox is the problem above

In Chrome after line break only the first sign is a link. After first sign its normal text. Strange.

In Opera and IE its working fine/correctly!

EDIT:
Tested with 4.0.x and 4.1.0

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6478](http://archive.tinymce.com/develop/bugtracker_view.php?id=6478) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** [firefox chrome forced_root_block]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/OCdaab_

**Comment by Daijobou** [comment]
Verified in 4.3.0

**Comment by afiedler** [comment]
If the element you are "trapped" in is an inline element, it seems like you can escape it with shift+enter.

This doesn't work for a block level element, like a blockquote in this example:
http://fiddle.tinymce.com/8xfaab

This bug causes lots of problems when using templates, especially templates that are block elements. I've taken to adding a `&nbsp;` or an empty `<p>` tag as the last element in my templates like this:
```html
<div class="well">
   <p>Content goes here</p>
</div>
&nbsp;
```

If you don't do this, when a user inserts a template as the last element in the editor, they will be trapped inside it. Very annoying!

Maybe a solution is to ensure that TinyMCE always has an empty `<p>` tag in the document as the last line? Then that could be stripped out when exporting content from the editor.

**Comment by Daijobou** [comment]
You can close this one. I have create a new ticket for this forgotten one.
