### ISSUE TITLE
Unwanted non break space after pasting chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1247]
Description of problem:

In Chrome, if you add a space at the end of a line, a non break space (&nbsp;) is actually added and if you type something after it, it is transformed to a normal space. If instead of typing after the space, you paste some text, the non break space is kept.

Steps to reproduce:
1. Copy some simple text (for instance "simple text")
2. Type "word" and then add a space with the spacebar
3. Paste

Expected result: "word simple text"

Actual result: "word&nbsp;simple text"

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6483](http://archive.tinymce.com/develop/bugtracker_view.php?id=6483) posted by [dpobel](http://archive.tinymce.com/profile.php?name=dpobel)_

> _**Tags:** [chrome paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Servicedeskprocurios** [comment]
The same issue is reported by customers using our platform, which uses the TinyMCE text editor.

**Details**

Noticed in:

Browser: Chrome Version 48.0.2564.116 (64-bit)
OS: OSX 10.9.5

Tested in the online demo-version of TinyMCE 4.3 (https://www.tinymce.com/docs/demo/basic-example/)
Tested in Fiddle for our current version: "3.5.11" and "Edge" (http://fiddle.tinymce.com/)

See screenshot for extra explanation.

![tinymce 4_3 - issue nbsp before pasted string](https://cloud.githubusercontent.com/assets/18026140/13980466/14ec2284-f0df-11e5-8a47-71efc2c16d13.png)

**Reproduce:**

1. Type a word.
2. Copy the word.
3. Type a space and paste the word (repeat several times)

Issue: the typed spaces for every pasted word, automatically get converted to a &nbsp;

**HTML source:**

`<p>pastedString typedString&nbsp;pastedString typedString&nbsp;pastedString&nbsp;pastedString typedString&nbsp;pastedString</p>`

In Safari the same issue occurs, in Firefox it doesn't

---

We would like to ask if this issue could be looked into.
If so; we would like to get a notification/update.

Regards, Servicedesk - Procurios.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
