### ISSUE TITLE
link_list plugin to accept null values in JSON

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1248]
Description of problem:

I spotted a bug whereby a null value passed as JSON to link_list causes link list not to load. I have huge lists of page links in my CMS's and I add dividers between them to help users find the section of links they require. 

Could the link_list / link plugin be updated to ignore JSON null values i.e. allow them to display in list but disable the click event to prevent the TypeError: e is undefined.

Steps to reproduce:
1. 
tinymce init

link_list: [ { "title": "------ PAGE LINKS ------" , "value": null } ]

Expected result:

I would expect the link to display but not load a value into url field when clicked

Actual result:

Plugin won't load at all. I use these types of links to simulate option groups and make it easy for a user to find a link among hundres available within my CMS.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6484](http://archive.tinymce.com/develop/bugtracker_view.php?id=6484) posted by [richard.hetherington](http://archive.tinymce.com/profile.php?name=richard.hetherington)_
> 
> _**Tags:** [firefox msie safari chrome opera link_list link plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
