### ISSUE TITLE
On an iPad, an empty editor is only focusable by clicking on the first line

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1250]
Steps to reproduce:
1. Open mobile safari in an iPad.
2. Navigate to a tinymce editor with empty content, or with content on only one line, such as the example on http://www.tinymce.com/tryit/button.php.
3. Try to focus by clicking in the editor area.

Expected result:
The editor is focused and the keyboard appears regardless of where you click in the editor area.

Actual result:
The editor is only focused when clicking in the first line, and clicks elsewhere in the editor area are ignored.

Additional note:
This is a regression compared to tinymce 3.x.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6487](http://archive.tinymce.com/develop/bugtracker_view.php?id=6487) posted by [fornwall](http://archive.tinymce.com/profile.php?name=fornwall)_

> _**Tags:** [ipad focus]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://www.tinymce.com/tryit/button.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
