### ISSUE TITLE
Anchor not visible in source view

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1251]
Description of problem:
When adding an anchor it is not visible in source view.  This is repeatable on your demo page.

Steps to reproduce:
1. Insert an anchor
2. Select source view
3. Notice that the anchor is not displayed in the code.

Expected result:
An anchor to appear in source view after inserted.

Actual result:
An inserted anchor is not visible in source view.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6489](http://archive.tinymce.com/develop/bugtracker_view.php?id=6489) posted by [farleyrw](http://archive.tinymce.com/profile.php?name=farleyrw)_

> _**Tags:** [chrome sourceview anchor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
