### ISSUE TITLE
Applying font styles to table does not apply to cells

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1252]
Description of problem:
Adding font-family and/or font-size attributes to table do not apply to cells. Inspecting the code shows that content.min.css is applying a css rule of "font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 11px;" to cells and headers, overriding the table setting.  This causes differences between the display of content being edited and published content.

Steps to reproduce:
1. Insert table of any dimension.
2. Go to source view and add font-family to the table element.
3. Observe that font styling is not applied to table cells.

Expected result:
When font styling is applied to table the cells inherit that styling.

Actual result:
Font styling on a table is not inherited by cells.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6490](http://archive.tinymce.com/develop/bugtracker_view.php?id=6490) posted by [farleyrw](http://archive.tinymce.com/profile.php?name=farleyrw)_

> _**Tags:** [firefox chrome table style font cell]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
