### ISSUE TITLE
onchange event in image advanced settings popup

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1254]
Description of problem:

Steps to reproduce:
1. Insert an image
2. Focus the inserted image and trigger context menu
3. Choose insert/edit image
4. Choose "Advanced" tab
5. enter any border value, e.g. 2
6. Press "OK" keeping the focus of the input with border width

Expected result:
Border applied

Actual result:
No border applied

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6492](http://archive.tinymce.com/develop/bugtracker_view.php?id=6492) posted by [r.osmanov](http://archive.tinymce.com/profile.php?name=r.osmanov)_

> _**Tags:** [firefox msie safari chrome opera image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
