### ISSUE TITLE
Copying Second Level Bullets (v4) Do Not Appear Correctly

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1255]
Description of problem: Pasting a bulleted list copied from word which has two levels of bullet points, fails to copy properly in IE9, FF25 or Chrom31.

Steps to reproduce:
1. Create a word doc that has bullets and sub-bullets
2. Copy and Paste into Editor

Expected result:
I should see bullets and sub-bullets as I do in my word doc. 

Actual result:
I see the first level of bullets appear as bullets but the second level appear with &ltg;p> tags.  It looks like the editor is not recognizing the sub-bullets.  Replicated in Chrome31, IE9 and FF25.

Note: Functionality works as expected in v3.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6493](http://archive.tinymce.com/develop/bugtracker_view.php?id=6493) posted by [Workopolis1](http://archive.tinymce.com/profile.php?name=Workopolis1)_

> _**Tags:** [bullet paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
