### ISSUE TITLE
title attributes for images and hyperlinks

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1257]
Description of problem:
The Editor is strongly limited. You can not add title to a link or a an image.

Steps to reproduce:
1. Install Joomla 3.2 with 4.0.10, open any Article
2. Add an Image, only description, not title is visible
3. Add an Link, only Link text, not title is visible.

Expected result:
As in Version 3.5.6, there should be more advanced options like adding a title to images and links.

Actual result:
Editors who are not able to write html can not use the editor to create proper html code.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6494](http://archive.tinymce.com/develop/bugtracker_view.php?id=6494) posted by [tifra](http://archive.tinymce.com/profile.php?name=tifra)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
