### ISSUE TITLE
inline-block elements can't be edited in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1258]
Description of problem:

When setting a "display: inline-block;" property on an element (strong, p, http://www.tinymce.com/develop/bugtracker_new.php#etc.) on IE, it can't be edited anymore because of a draggable & resizable event automatically added to that element.
Steps to reproduce:
1. Set a text
2. Wrap the text with a strong tag
3. Edit code
4. add "style: display: inline-block;" property on the "strong" element
5. Click on the text to edit it

Expected result:

The caret must be accessible to edit your text where you clicked

Actual result:

Somehow, the whole text is selected like we want to move/resize it.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6540](http://archive.tinymce.com/develop/bugtracker_view.php?id=6540) posted by [Snaven](http://archive.tinymce.com/profile.php?name=Snaven)_

> _**Tags:** [msie msie7 msie8 msie9]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
