### ISSUE TITLE
Editor retains in the heap after being removed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1259]
Description of problem:

Steps to reproduce:
1. Create an editor in "exact" mode using tinymce.init(settings) method
2. Remove the created editor using tinymce.remove(ed) method
3. Take a heap snapshop using Chrome developer tools' profiler

Expected result:
The editor is freed from memory
(I used tinymce 3.5.8)

Actual result:
The editor retains

Quick investigation shows that the editor object is referred from the global tinymce.settings via the member variable url_converter_scope. The settings is also cloned in some other objects for example Style, Dom, etc. Therefore the last created editor will never been completely destroyed.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6495](http://archive.tinymce.com/develop/bugtracker_view.php?id=6495) posted by [duong.nguyen](http://archive.tinymce.com/profile.php?name=duong.nguyen)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Closed_
> _**Resolution:** Wont Fix_
> _**Attached URL:** none_

**Comment by riyazahamedr** [comment]
Any patch to fix this issue?

**Comment by spocke** [comment]
Could you open a new ticket and explain your issue and if possible provide us with a fiddle showcasing the bug. Thanks

**Comment by riyazahamedr** [comment]
@spocke Created as new ticket #5419
