### ISSUE TITLE
Mac: Redo button is wrongful disabled, making redoing impossible in toolbar

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1260]
Description of problem:
If the keyboard shortcut to undo is applicated (cmd-z) when editing text on a Mac, the redo button is disabled / not activated, making it impossible to restore text that just have been "undone". Not so much of a problem when undoing one step, but highly critical if a lot is undone, and can't be "redone" again.

Steps to reproduce:
1. Write a new bullet in the editor on the tinymce frontpage
2. Press enter to start a new bullet
3. Cmd-z on the Mac keyboard
4. The new bullet is undone, but cannot be redone again in the tinymce toolbar.
5. The cmd-shift-z can sometimes complete the redo, and so can "tinymce.activeEditor.undoManager.redo();

Expected result:
The redo button should be enabled, when redo-levels exists

Actual result:
The redo button is never enabled, when using the cmd-z undo shortcut.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6541](http://archive.tinymce.com/develop/bugtracker_view.php?id=6541) posted by [msa](http://archive.tinymce.com/profile.php?name=msa)_

> _**Tags:** [firefox msie safari chrome opera mac redo keyboard shortcut undo tinymce4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://tinymce.com_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
