### ISSUE TITLE
Empty paragraphs getting inserted on save with inline mode

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1261]
Description of problem: When using inline mode, saving crates empty paragraphs after each element.

This only seems to affect inline mode

Steps to reproduce:
1. Go to the fiddle link.
2. Place the caret on the right of the table.
3. Type a p, press save.
4. Repeat 2 and 3
5. The issue should occur

Expected result: Expect the mark up to remain the same after clicking save

Actual result:Additional paragraphs are inserted after each element

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6542](http://archive.tinymce.com/develop/bugtracker_view.php?id=6542) posted by [cjsewell](http://archive.tinymce.com/profile.php?name=cjsewell)_

> _**Tags:** [firefox msie safari chrome opera paragraphs empty p save inline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/rGdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
