### ISSUE TITLE
Exception thrown when changing font size or font family with custom fonts

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1263]
Sorry in advance if this doesn't fit in your bug reporting standards.

I found that an exception is thrown when you attempt to change font size or font family with a custom font (.eot) in IE8.

The exception is thrown in tinymce.js (version 4.0.10) line 32574:

text: function(text) {
  var self = this, i, children;
  if (self._rendered) {
    children = self.getEl('open').getElementsByTagName('span');
      for (i = 0; i &ltg; children.length; i++) {
    //children[i].innerHTML = self.encode(text);
    $(children[i]).html(self.encode(text));
      }
  }
  return this._super(text);
},

I commented the offending line of code and replaced with something that solved the problem (jquery required).

I hope that helps, thanks!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6496](http://archive.tinymce.com/develop/bugtracker_view.php?id=6496) posted by [jmunoz](http://archive.tinymce.com/profile.php?name=jmunoz)_
> 
> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
