### ISSUE TITLE
No Documentation (anywhere on the net) on how to set Image Description Fields and Dimensions for an Image Dialog in tincy mce 4.0

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1264]
Description of problem:

Cant find any documentation on (if its possible) how to set Image Description and dimension from a custom file_browser. Can set URL using window and input parameters, but there are no parameter in the callback function for description and dimensions. 

How can I get the ids for these fields?

Have tried posting posting on the forum but nobody has responded.

Does this ability exist? I had it working fine in 3.x cause the parameters were set in the HTML for the dialog. In the new version these ids are set programmatically and can change.

Help please

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6497](http://archive.tinymce.com/develop/bugtracker_view.php?id=6497) posted by [spidersites](http://archive.tinymce.com/profile.php?name=spidersites)_
> 
> _**Tags:** [custom image manager]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
