### ISSUE TITLE
Help Icon in Toolbar does not work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1265]
Description of problem:

The help icon in the toolbar of TinyMCE 4 doesn't show any help or other information.  Tested with Chrome 31.0.1650.57 m, Firefox 25.0.1 and IE 11.0.9600.16428.

Steps to reproduce:
1. Go to &ltg;http://fiddle.tinymce.com/bEdaab>
2. Click the help icon

Expected result:

Some help or about information is shown.

Actual result:

Nothing happens.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6498](http://archive.tinymce.com/develop/bugtracker_view.php?id=6498) posted by [cmb69](http://archive.tinymce.com/profile.php?name=cmb69)_
> 
> _**Tags:** [firefox msie safari chrome opera x4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/bEdaab_

**Comment by fyrkant** [comment]
Closing this because we have the help plugin now! https://www.tinymce.com/docs/plugins/help/
