### ISSUE TITLE
Formatting bug with nested lists

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1266]
Description of problem:
Applying a format to all of the items in a nested list unexpectedly moves the last item to the top of the list.

Steps to reproduce:
1. Use the above-referenced fiddle. The nested list in this fiddle was formed by creating an ordered list of 4 items, and then individually indenting each of the 2 middle items one level deeper.

2. Select all 4 items in the nested list.

3. Press the bold button.

4. The 4th item unexpectedly gets moved to the 1st item. The 2 middle items do not get bolded.

This bug affects FF, Chrome and IE11.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6499](http://archive.tinymce.com/develop/bugtracker_view.php?id=6499) posted by [jashua212](http://archive.tinymce.com/profile.php?name=jashua212)_

> _**Tags:** [firefox msie chrome lists]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/eEdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
