### ISSUE TITLE
Editor in jQuery Dialog.. caret repositions itself to the beginning when inserting or editing link or image - IE only

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1267]
Description of problem:

I have an editor within a jQuery dialog box.  When the dialog box opens to either insert or edit a link or image, the caret repositions itself to the beginning of the editor text.  This makes it impossible to edit an image or link the highlighted element is no longer active when the dialog box opens.  And whenever I try to insert a link or image, it always shows up at the beginning of the editor text.   

This is happening even in the TinyMCE Fiddle example of including an editor in a jQuery Dialog... http://fiddle.tinymce.com/rsdaab ....

Steps to reproduce:
1. In the example page (http://fiddle.tinymce.com/rsdaab) and click the Open button.
2. Insert some text into the editor.
3. At the end of the text, click the 'Inser/edit Link' button and enter a web address and click OK.
4. The link is added to the front of the beginning of the text - not at the end where the caret started out.
5. Highlight the link to try to edit it, no information is included in the form (like you are creating a new link)

The same thing happens when working with an image dialog....  

It's as though as soon as you open the dialog box the caret gets placed at the beginning of the text and nothing is selected....  This only happens on IE - all other browsers seem to work fine.  

I did also notice (again only in IE) that on the editor example on the home page of TinyMCE, if you click on the insert image button, and click cancel, then click insert image button again, then cancel, (so do it twice) the caret is positioned at the beginning of the text - no jQuery involved....

(I hope I'm not being too confusing ;-)

Expected result:  link/image should be inserted at the original position of the caret.

Actual result:  link/image is inserted at the beginning of the text.

Thanks,
Frank

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6500](http://archive.tinymce.com/develop/bugtracker_view.php?id=6500) posted by [hulumanu](http://archive.tinymce.com/profile.php?name=hulumanu)_
> 
> _**Tags:** [msie msie7 msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
