### ISSUE TITLE
inline, version 4: triggerSave on KeyUp can insert empty paragraphs

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1268]
Description of problem:

I have an instance of the tinyMCE editor that is inline, and has a handler added to the KeyUp event. On the KeyUp event I want to .triggerSave(). The strange behavior seems to focus on the enter key: when clicking in to an inline editor, then hitting the enter key, then typing more or using an arrow to navigate, I often see "phantom" empty paragraphs being inserted into the editor, apparently one for each existing paragraph element.

I have also tried setting a bookmark and then using .moveToBookmark() to get back to that spot, but the same problem occurs.

This means that we can't implement our autosaving inline editor the way we'd like.

Steps to reproduce:
1. visit http://jsfiddle.net/alxndr/SfPpe/3/
2. click in to the text content in the Result pane
3. hit the Enter / Return key, then an arrow key, then the Enter / Return again, then an arrow key again

Expected result:

Arrow keys should simply move the cursor around

Actual result:

When pressing an arrow key directly after pressing Enter / Return, I see an additional "linebreak" (appears to be an empty paragraph tag, or a paragraph tag with a newline or nbsp in it) showing up both visually and in the HTML.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6501](http://archive.tinymce.com/develop/bugtracker_view.php?id=6501) posted by [alxndr](http://archive.tinymce.com/profile.php?name=alxndr)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/alxndr/SfPpe/3/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
