### ISSUE TITLE
Default for Formatting, Font, and Size

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1269]
I really really want to be able to set a default for formatting, font and size so that I don't have to set it every time I use it again.  I waste SOOOO much time setting the formatting, font and size _everytime_ I want to add text.  I use EDU 2.0 and believe that I speak for countless others using this LMS.

Thanks!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6502](http://archive.tinymce.com/develop/bugtracker_view.php?id=6502) posted by [brooksenglish](http://archive.tinymce.com/profile.php?name=brooksenglish)_
> 
> _**Tags:** [default formatting font size]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
