### ISSUE TITLE
Screenshot in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1270]
Description of problem: I have added tinymce on my application which is an intranet like Bugzilla. 

When I want to insert screenshot (with CTRL + V), it doesn't works on IE but it works on Firefox. 

Do you know if there are some parameter to change in my code or in IE for making it works ?

Thanks a lot in advance
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6503](http://archive.tinymce.com/develop/bugtracker_view.php?id=6503) posted by [jsi0612](http://archive.tinymce.com/profile.php?name=jsi0612)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
