### ISSUE TITLE
Certain HTML causes Chrome to crash

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1277]
Description of problem:
With certain HTML, right clicking on an image will cause Chrome to crash. I'm on version 31 in Windows 8.

Steps to reproduce:
1. Visit http://fiddle.tinymce.com/FEdaab in Chrome
2. Right click on the image in the editor.

Expected result: Context menu appear.

Actual result: Browser crashes.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6511](http://archive.tinymce.com/develop/bugtracker_view.php?id=6511) posted by [RatNeurons](http://archive.tinymce.com/profile.php?name=RatNeurons)_

> _**Tags:** [chrome chrome crash]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/FEdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
