### ISSUE TITLE
HierarchyRequestError in IE for TinyMCE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1278]
I'm using TinyMCE 3.4.8 and there I noticed that if your cursor is in editor and then if you click on any plugin like insert image then it works fine. But if your cursor is not in textarea, means you click somewhere else in Tiny like the title bar or blank space outside textarea and then after that if you click on any plugin then you'll see the below error in IE console.

Error message on IE console (see attachment)

The code in Line 6209 is given below.

g.insertNode(m.create("span", {
                    "data-mce-type": "bookmark",
                    id: i + "_start",
                    style: u
                }, l))
Now what I get from this is that when you click on any plugin it inserts a span tag for bookmarking purpose, but if the cursor was not in textarea then in that case inserting the node to undefined object causes the above error. I want to know how to solve this, so that even if user clicks outside then also the image gets inserted to last known cursor position.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6512](http://archive.tinymce.com/develop/bugtracker_view.php?id=6512) posted by [chankeypathak](http://archive.tinymce.com/profile.php?name=chankeypathak)_

> _**Tags:** [msie msie7 msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
