### ISSUE TITLE
vertical scrollbars unrecognizable in some browsers.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1279]
Description of problem: When pasting enough text into the editor to cause vertical scrolling, the "scrollbars" that appear do not look like scrollbars.

Steps to reproduce (1st example)
1. Load up one of the editors (basic, classic or full) under Try It using Chrome or Safari
2. Paste enough text into the editor to cause vertical scrolling.
Result: The vertical scrollbars shown are unrecognizable.

Steps to reproduce (2nd example)
1.Modify the TinyMCE4.MVC.Sample to preload the editors with enough text to enable vertical scrolling.
2. Load the sample in Safari. All the editors show unrecognizable vertical scrollbars.
3. Load the sample in Chrome. The basic and classic editors show normal vertical scrollbars, but the full editor shows the unrecognizable vertical scrollbars. If you then refresh the page, all of the editors now show the unrecognizable vertical scrollbars.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6514](http://archive.tinymce.com/develop/bugtracker_view.php?id=6514) posted by [EBGamer](http://archive.tinymce.com/profile.php?name=EBGamer)_

> _**Tags:** [safari chrome safari5 chrome31 windows8 tinymce4011 tinymce4mvc408]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
