### ISSUE TITLE
Show a selected state when you click on a video element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1280]
Right now if you click on any element that has formatting or an image element, the corresponding toolbar button shows a selected state. This is true for all the buttons in the toolbar that have similar behavior except for the media button. For the media button, the button doesn't have a selected state. It would be great if the button would show a selected state when you click on the element so that it is obvious where you can edit the media type and that it's a media object.

I've attached two screenshots - one of when an image is selected and one when a media object is selected. Ideally, the media object would have a similar state as the image object and would have a selected state.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6564](http://archive.tinymce.com/develop/bugtracker_view.php?id=6564) posted by [monkeydiane](http://archive.tinymce.com/profile.php?name=monkeydiane)_
> 
> _**Tags:** [media toolbar]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
