### ISSUE TITLE
Highlight text in IE 11 win7 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1282]
Description of problem:

Steps to reproduce:
1. Got to the demo with IE 11
2. Try to highlight some text
3. After releasing the mouse the text is not highlighted 
4. After second try it works
5. It also works if dragging the mouse outside of the Tinymce container

Expected result:
Highlight text with mouse

Actual result:
Looses the Highlighted text  

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6515](http://archive.tinymce.com/develop/bugtracker_view.php?id=6515) posted by [ceasar](http://archive.tinymce.com/profile.php?name=ceasar)_

> _**Tags:** [msie highlight text ie 11x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
