### ISSUE TITLE
change labels

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1285]
is there a way for us to change the label for any tinymce element? 

Example,  I am using the link_list plugin.  Right now the link modal pops up and the link list part has the label "Link list".  I want to change 'Link list' to something else like "Link Page".  Is there a way to do that? 

thanks! 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6790](http://archive.tinymce.com/develop/bugtracker_view.php?id=6790) posted by [koyz](http://archive.tinymce.com/profile.php?name=koyz)_
> 
> _**Tags:** [label links linklist list]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
