### ISSUE TITLE
Align left

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1287]
Steps to reproduce:
1. Click inside TinyMCE 4.0.11 on tinymce.com.

Expected result:
1. "Align left" button is highlighted on LTR websites at the beginning.
2. "Align right" button is highlighted on RTL websites at the beginning.
3. Clicking "align left" on a LTR website shouldn't add inline style of "text-align: left;" because it's LTR website and its default state is "nameless value" (which is "left" alignment on LTR websites) (that's to avoid "overclarification").

Actual result:
1. "Align left" is not highlighted on LTR websites when text is actually left aligned ('initial nameless value' === 'left' on LTR websites and 'initial nameless value' === 'right' on RTL websites: http://www.w3.org/TR/CSS21/text.html#alignment-prop | https://developer.mozilla.org/en-US/docs/Web/CSS/text-align)
2. Same with RTL.
3. Clicking "align left" on a LTR website adds inline style of "text-align: left;".
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6569](http://archive.tinymce.com/develop/bugtracker_view.php?id=6569) posted by [Trevlon](http://archive.tinymce.com/profile.php?name=Trevlon)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
