### ISSUE TITLE
Add ID to image in version 4

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1288]
Really need to be able to tag an image with an id in version 4 so I can work with it in the DOM. Don't understand why this was not implemented from the get-go.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6519](http://archive.tinymce.com/develop/bugtracker_view.php?id=6519) posted by [sethb74](http://archive.tinymce.com/profile.php?name=sethb74)_
> 
> _**Tags:** [4 id image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
