### ISSUE TITLE
Align Buttons Don't Reflect Table Cell

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1289]
Description of problem:

Steps to reproduce:
1.Insert a table
2.Open table properties dialog for the table and change "Alignment" to "Right" and click "Ok"
3.Notice the "Right Align" button is selected.
4.Click the "Left Align" button

Expected result: "Right Align" button is only selected.

Actual result: "Right Align" button and "Left Align" buttons are both selected.  This also happens with the center align.  Issue is the align buttons show the alignment for the whole table instead of just the cell.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6520](http://archive.tinymce.com/develop/bugtracker_view.php?id=6520) posted by [flynnformz](http://archive.tinymce.com/profile.php?name=flynnformz)_

> _**Tags:** [firefox msie safari chrome opera table align]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
