### ISSUE TITLE
Color selection not reflected correctly in tables

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1290]
Insert a table into content area 
- Select  text color (for ex. red) 
  Note : Issue reproduce for Background color
-  Type some text > move to the any of cell in table and type  text
  Error : Text in new selected cell is auto(black), but previously chosen color is still marked as selected

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6521](http://archive.tinymce.com/develop/bugtracker_view.php?id=6521) posted by [flynnformz](http://archive.tinymce.com/profile.php?name=flynnformz)_
> 
> _**Tags:** [firefox msie safari chrome opera forecolor background color]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
