### ISSUE TITLE
Anchor tags stripped on setContent

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1291]
Description of problem:

If an anchor tag is the only element within a block node, the setContent method will strip it out. If there are other nodes in the same block is it kept.

Steps to reproduce:
tinymce.init({
        selector: "textarea",
        plugins: ["anchor"],
        setup: function (ed) {
            ed.on('init', function (e) {
                tinymce.activeEditor.setContent("&ltg;p>&ltg;a id='missing anchor'>&ltg;/a>&ltg;/p>&ltg;p>&ltg;a id='found anchor'>&ltg;/a>text&ltg;/p>");
            });

```
    }
});  
```

Expected result:

The editor shows 2 anchor tags.

Actual result:

Only the anchor tag with text in the same block element is retained.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6522](http://archive.tinymce.com/develop/bugtracker_view.php?id=6522) posted by [danransom](http://archive.tinymce.com/profile.php?name=danransom)_
> 
> _**Tags:** [firefox msie safari chrome opera anchor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
