### ISSUE TITLE
jQuery remove on complex structure does not remove instance

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1292]
Version: 4.0.11
Description of problem:
When an instance is placed inside a complex html structure, after empty() on not the closest node, the instance is not being destroyed. Immediate initialization on newly created structure with same-id textarea fails 
Steps to reproduce:
1. create instance on textarea placed inside div, inside form, inside div
2. empty root div
3. insert same html as before
4. try to initialise tinymce $(...).tinymce({...})
5. it will not show up

Expected result:
jquery plugin's remove patch should go deep to the removed node an its subnodes, find all :tinymce and destroy them by instance.remove()

Actual result:
jquery plugin's remove patch does search for instances on elements exactly passed to remove, empty ... function, then searches for inline instances by find('span.mceEditor,div.mceEditor')

Proposed fix:
function removeEditors(name) {
...
+this.find(".mce-tinymce").each(function(i, node) {
-   var fi = $(node).siblings(':tinymce');
-   if(fi.size()){
-       var ed = tinymce.get(fi.attr('id'));
  +
-       if (ed) {
-           ed.remove();
-       }
-   }
  +});
  ...
  > _**Legacy information imported from TinyMCE bug tracker:**_
  >
  > _[#T6523](http://archive.tinymce.com/develop/bugtracker_view.php?id=6523) posted by [honda2](http://archive.tinymce.com/profile.php?name=honda2)_

> _**Tags:** [firefox msie safari chrome opera jquery dynamic remove]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/4Fdaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
