### ISSUE TITLE
drag and drop from chrome to firefox converting characters to chinese characters

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1294]
Description of problem:

Steps to reproduce:
1. mark some html inside chrome
2. drag this html to tinymce inside firefox
3. drop it
4. view chinese characters

Expected result:
marked characters

Actual result:
chinese characters
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6525](http://archive.tinymce.com/develop/bugtracker_view.php?id=6525) posted by [andrejlnnk](http://archive.tinymce.com/profile.php?name=andrejlnnk)_

> _**Tags:** [firefox chrome drag drop]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
