### ISSUE TITLE
Add text-align: right for beter rtl support

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1295]
Add 
text-align: right;
to .mce-menubtn.mce-fixed-width span in file skin.min.css

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6527](http://archive.tinymce.com/develop/bugtracker_view.php?id=6527) posted by [nirlewin](http://archive.tinymce.com/profile.php?name=nirlewin)_
> 
> _**Tags:** [firefox msie safari chrome opera rtl]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
