### ISSUE TITLE
selection.setNode() returns useless element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1298]
Description of problem:

selection.setNode(element) returns 'element', as written in the documentation. However, the element passed in is actually NOT the one inserted in the dom, because self.dom.getOuterHTML(elm) is applied. The returned element is useless.

Steps to reproduce:
In a plugin code:
var elm = editor.dom.create('video', { src: url });
var video = editor.selection.setNode(elm),

Expected result:
console.log(video.parentNode); // display a node element, parent of the new created element

Actual result:
console.log(video.parentNode); // display "null" because elm was kind of "duplicate" and not used to insert into the dom

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6578](http://archive.tinymce.com/develop/bugtracker_view.php?id=6578) posted by [stuffk](http://archive.tinymce.com/profile.php?name=stuffk)_
> 
> _**Tags:** [firefox msie safari chrome opera api selection]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
