### ISSUE TITLE
ALT tag for images on advanced tab

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1299]
There should absolutely be a way to set the ALT tag for images on the image advanced tab, as was the case on version 3.X
This is an accessibility issue.
I am considering downgrading back to version 3.X just because of this. Too bad.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6530](http://archive.tinymce.com/develop/bugtracker_view.php?id=6530) posted by [eytanchen](http://archive.tinymce.com/profile.php?name=eytanchen)_
> 
> _**Tags:** [image advanced]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
