### ISSUE TITLE
Drag links into TinyMCE 4.x

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1302]
SHORT:
Since 4.x I no longer can drag a link from insite a html page onto the editor to paste the link and its caption into the editor.

LONG:
I have a website where I offer a list of links pointing to the latest records one has been editing. Now when someone is writing documentation I allow then to drag theese links into his text. When displaying the documentation I add a button after internal links allowing to load a printversion of that record - inline. That is a major feature of my application.

SO:
Are there any plugins or plans to support that again?
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6582](http://archive.tinymce.com/develop/bugtracker_view.php?id=6582) posted by [eurosat7](http://archive.tinymce.com/profile.php?name=eurosat7)_

> _**Tags:** [firefox msie safari chrome opera version_4_0_x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** about:blank_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
