### ISSUE TITLE
Strikethrough text is getting reset to normal text while clicking Strikethrough icon by keeping cursor at beginning of Strikethrough text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1303]
Summary:

Strikethrough text is getting reset to normal text while clicking Strikethrough icon by keeping cursor at beginning of Strikethrough text  in tinymce.

Steps to reproduce:

1.Select the word "Welcome to the TinyMCE editor demo!"  and strikethrough the selected texts.

2.Place the cursor at the beginning of the text(before Welcome) then click on  strikethrough icon.

3.Verify the results.

Expected Result:

Strikethrough text should not reset to normal text while clicking Strikethrough icon by keeping cursor at beginning of Strikethrough text

Actual Result:

Strikethrough text is getting reset to normal text while clicking Strikethrough icon by keeping cursor at beginning of Strikethrough text  in tinymce.

Refer attachment 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6532](http://archive.tinymce.com/develop/bugtracker_view.php?id=6532) posted by [abd1341984](http://archive.tinymce.com/profile.php?name=abd1341984)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/full.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
