### ISSUE TITLE
Iframe srcdoc with a link

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1304]
Description of problem:

I try to use tinymce inside of a iframe by using srcdoc. 

version : 4.0.12

Steps to reproduce:
1. Load the page

Expected result:
load the editor with the content.

Actual result:
TypeError: e is undefined

look like we have no way to set the development version of tinymce with your fiddle. But if I use tinymce.js, I get that error

TypeError: base is undefined
base = base.substring(0, base.lastIndexOf('/')); (line 18571)

 toRelPath: function(base, path) {
    var items, breakPoint = 0, out = '', i, l;
    // Split the paths
    base = base.substring(0, base.lastIndexOf('/'));  //(line 18571)

ps. If you remove the tag A inside the textarea, the error don't happen. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6583](http://archive.tinymce.com/develop/bugtracker_view.php?id=6583) posted by [digital2](http://archive.tinymce.com/profile.php?name=digital2)_
> 
> _**Tags:** [firefox iframe]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/SIdaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
