### ISSUE TITLE
Single break lines are not working perfectly in IE9-11

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1306]
Description of problem: Single break lines are working perfectly in IE9-11 when pasting from Microsoft Word. In IE11 pasting works if the text you are pasting does not contain formatting rules like bold. There are no problems in FF. 

Steps to reproduce:
1. Create a few lines of text in Microsoft Word - include a paragraph and a single break line
2. Paste it to the fiddle with the IE browser and you will see that breaks are not respected.
3.
4.
5.

Expected result: WYSIWYG on paste.

Actual result: Not WYSIWYG on paste

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6533](http://archive.tinymce.com/develop/bugtracker_view.php?id=6533) posted by [perels](http://archive.tinymce.com/profile.php?name=perels)_
> 
> _**Tags:** [msie msie9 msie10 paste word microsoft]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/Wm8RP/7/_

**Comment by blackcathikari** [comment]
We've looked into this and believe this is a duplicate of #2229, and could come under the wider scope of #2083. Could you please take a look and let us know if you agree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
