### ISSUE TITLE
Responsive modal window

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1307]
Hello,

It's actually quite hard to make modal windows responsive since some values are automatically calculated, for example the submit/cancel buttons. For the global container is not that hard, since a max-width instead of a width setting should be enough, but for others, I don't see any easy solutions.

Could you please just tell me if you're planning to do that or if it's not in your projects? Thank you !

C�dric

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6534](http://archive.tinymce.com/develop/bugtracker_view.php?id=6534) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by breity** [comment]
Just wondering, has there been any progress on this issue? Is the slimmed down editor still even on the table? Thanks!

**Comment by mbardelmeijer** [comment]
As @breity said, any progress on this issue? Thanks!

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
