### ISSUE TITLE
href attribute with javascript is removed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1312]
When you add into href attribute value like javascript:doSomethnig() href attributes is removed.

It's caused by this change and was added in v4.0.10:
https://github.com/tinymce/tinymce/commit/eb0713baa45a2f415214fc6c22601ca262949a1a

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6544](http://archive.tinymce.com/develop/bugtracker_view.php?id=6544) posted by [dosercz](http://archive.tinymce.com/profile.php?name=dosercz)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Deleted_
> _**Resolution:** Duplicate_
> _**Attached URL:** none_

**Comment by rgriffith** [comment]
I just stumbled onto this after upgrading to 4.5.1 from 3.5.11 and all of the links containing `href="javascript:..."` were unknowingly stripped out. Are there any plans to address this issue? Thanks!

**Comment by fyrkant** [comment]
I don't think this is a bug but a feature to prevent XSS. Closing this issue.

**Comment by rgriffith** [comment]
Understood, but are there any workarounds or ways to allow the code?

**Comment by fyrkant** [comment]
@rgriffith Yes you can use the `allow_script_urls` setting: https://www.tinymce.com/docs/configure/url-handling/#allow_script_urls

**Comment by rgriffith** [comment]
Ah, didn't even see that option. Thank you @fyrkant.
