### ISSUE TITLE
Pasting from Word incorrectly converts and cleans nested lists

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1314]
Description of problem:
Pasting from Word incorrectly converts and clean numbered and bullet lists, especially with several nested levels. (tested with 4.0.12)

Steps to reproduce:
1. Create a Word document with numbered and bullet lists with several levels.
2. Copy and Paste to TinyMCE (tested with 4.0.12)

Expected result:
Nested lists should be converted right and without extra &nbsp;

Actual result:
Lists get many extra &nbsp; Nested lists are not properly converted at all.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6596](http://archive.tinymce.com/develop/bugtracker_view.php?id=6596) posted by [mitridat](http://archive.tinymce.com/profile.php?name=mitridat)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
We've looked into this and believe it is related to a few other bug reports regarding pasting lists from Word. The related reports are #2853, #3061, #1314, #1422, #1489, #1696 and #1708, and cover indentation, list styling and list item order not being preserved. Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by hasnainzia20** [comment]
when I copy and paste text in multi lines like
