### ISSUE TITLE
Add an automatic color to the forecolor and backcolor to the textcolor plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1316]
Hey spocke, 
Why not adding an automatic color to the forecolor and backcolor list so it will look exactly like word. This automatic or default color will be a configuration option and can be set by the user and if not set it will be black by default.
Example:
automatic_forecolor: '#0ff000', // in case if the user want another color to be the default one
automatic_backcolor: '#0f0f0',

hope you like this idea 
Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6547](http://archive.tinymce.com/develop/bugtracker_view.php?id=6547) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_
> 
> _**Tags:** [textcolor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by MatiasL13** [comment]
so how i can select a default color in the backcolor button  ?
