### ISSUE TITLE
Image dimensions fields have width of 0px

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1317]
Description of problem:
I�m testing TinyMCE with the image plugin on 2 different sites (both internal only so I can�t include the URLs). On one site the image dialog appears normally. On the other, the width of the dimension fields in the image plugin are set to 0px so they are not really usable. The dialog size on the site which has the dimension issues also appears not as wide as the other, so I think it may be an issue related to the way it calculates the proportions of the display.

Steps to reproduce:
1. Go to a field using TinyMCE
2. Click on the image button

Expected result:
The image dimension fields should be large enough to display the contents of them

Actual result:
The image dimension fields are too small to display any content

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6548](http://archive.tinymce.com/develop/bugtracker_view.php?id=6548) posted by [cdaveb](http://archive.tinymce.com/profile.php?name=cdaveb)_

> _**Tags:** [safari chrome image dimensions]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
