### ISSUE TITLE
Replace After Inserting Special Characters

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1318]
Description of problem:  When adding in special characters using the special character dialog, if you try to replace a group of them with a new word using the find and replace dialog, each character is replaced with the word and not the whole "word" or special characters.  THIS DOES NOT HAPPEN WHEN PASTING IN SPECIAL CHARACTERS.

Steps to reproduce:
1.  Enter in several special characters using the special characters dialog.
2.  Copy that string of characters using Ctrl+C
3.  Open the find and replace dialog
4.  Past that string into the find text box
5.  Enter anything into the replace text box, such as "test"
6.  Replace

Expected result:  Entire string of characters is replaced with word "test"

Actual result:  Each character in string is replaced with word "test" so you get "testtestesttest"

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6549](http://archive.tinymce.com/develop/bugtracker_view.php?id=6549) posted by [flynnformz](http://archive.tinymce.com/profile.php?name=flynnformz)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
