### ISSUE TITLE
Pasting Multiple Spaces From Word In IE 8

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1319]
Description of problem:  Pasting in multiple spaces from a word document shrinks spaces to a single space.  Does not happen in other browsers

Steps to reproduce:
1.  Create a word document with multiple spaces between words
2.  Paste into editor

Expected result:  Text appears as was

Actual result:  All areas where multiple spaces follow each other are changed to single spaces.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6550](http://archive.tinymce.com/develop/bugtracker_view.php?id=6550) posted by [flynnformz](http://archive.tinymce.com/profile.php?name=flynnformz)_

> _**Tags:** [msie msie8 ie8 spaces paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
