### ISSUE TITLE
Make Indent able to use margin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1322]
Description of problem:  When clicking indent in TinyMCE3 it would add a style with margin, now in 4 padding is used instead.  Would be nice if it was the same or if this was something that was able to be configured in formats.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6553](http://archive.tinymce.com/develop/bugtracker_view.php?id=6553) posted by [flynnformz](http://archive.tinymce.com/profile.php?name=flynnformz)_
> 
> _**Tags:** [firefox msie safari chrome opera indent padding margin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
