### ISSUE TITLE
Touch Screen Devices, once the editor is active, can't select a range outside the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1323]
I've only tested this on iOS. Once the editor has been activated (focus), it's no more possible to select a text range outside the editor (outside the iframe). This can be reproduced on your main page.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6604](http://archive.tinymce.com/develop/bugtracker_view.php?id=6604) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
