### ISSUE TITLE
Menus dont open in IE9 (Win 7)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1324]
Description of problem:

I can't open the dropdown menus from the menubar with IE9, works in other browsers. (IE 9, Build 9.0.8112.16421, Win 7, no service pack)

Steps to reproduce:
1.go to www.tinymce.com with IE9 and click on a menu item in the demo editor

Expected result: Menu window opens (either format, file or any other)

Actual result: Button freezes in "active" mode, mouse cursor becomes a hand anywhere and I have to click twice to get the editor to work again / accept commands.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6554](http://archive.tinymce.com/develop/bugtracker_view.php?id=6554) posted by [rhellik](http://archive.tinymce.com/profile.php?name=rhellik)_

> _**Tags:** [msie msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
