### ISSUE TITLE
Methods getText and setText on tinymce.dom.DOMUtils

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1325]
As a complement to setHTML, getOuterHTML and setOuterHTML, the methods getText and setText are useful to have. For instance, currently, the link dialog uses setHTML which causes unexpected interpretation of text as HTML.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6555](http://archive.tinymce.com/develop/bugtracker_view.php?id=6555) posted by [WiebeCnossen](http://archive.tinymce.com/profile.php?name=WiebeCnossen)_
> 
> _**Tags:** [dom]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
