### ISSUE TITLE
Changing the link text via the link dialog does not fire change

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1326]
Description of problem:

Steps to reproduce:
1. Create and save a document with a link
2. Open the document
3. Position the cursor inside the link and choose Insert link
4. Change the Text to display
5. Click OK

Expected result:
change event is fired, document is dirty

Actual result:
change event is not fired, document is not dirty

The proposed fix is to use DomUtils.setText to set the Text to display and to create an onSetText event to signal a changed text.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6556](http://archive.tinymce.com/develop/bugtracker_view.php?id=6556) posted by [WiebeCnossen](http://archive.tinymce.com/profile.php?name=WiebeCnossen)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
