### ISSUE TITLE
paste_remove_styles broken for >= 4.0.9

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1327]
Description of problem:

Steps to reproduce:
1. Open fiddle
2. Copy & Paste prepared content

Expected result:

Removed styles for pasted content.

Actual result:

Styles are kept after paste. 4.0.9 seems to have introduced the bug, exists still on edge. 4.0.7 works fine. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6557](http://archive.tinymce.com/develop/bugtracker_view.php?id=6557) posted by [msvc](http://archive.tinymce.com/profile.php?name=msvc)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/0Hdaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
