### ISSUE TITLE
Color formating not rendered in readonly mode

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1330]
Description of problem:

Steps to reproduce:
1.Add 2 textareas in a page. One editable and the other readonly such that when you save the text enter in textarea 2 it will show up in textarea 1 in readonly mode and textarea 2 goes blank
2.Add some text in textarea 2 and change the background color or foreground color of the text
3.Submit the page
4.
5.

Expected result: the applied background color should appear in textarea 1

Actual result: any formatting related to color does not get rendered in textarea 1

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6609](http://archive.tinymce.com/develop/bugtracker_view.php?id=6609) posted by [tarunajain6](http://archive.tinymce.com/profile.php?name=tarunajain6)_
> 
> _**Tags:** [firefox msie safari chrome opera color formatting]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
