### ISSUE TITLE
TinyMCE 3.5.9 and IE11, multi textareas additional line breaks

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1331]
Description of problem:

The above fiddle does use TinyMCE jQuery Version including PHP Compressor.
TinyMCE loads with 3.5.9..

The Problem is this: http://i.imgur.com/lV2peJC.png

Do see what happens, test it in IE11 and open console (F12) to watch console output...

Steps to reproduce:
1. click "open" link (dialog with tabs and 3 textareas)
2. click close icon (top right in dialog)
3. click "open" link again -> watch console, addition &ltg;br />'s
4. if this form will be posted over ajax, this additional &ltg;br />'s are also posted

Expected result:
No additional &ltg;br />'s should be on output

Actual result:
additional &ltg;br />'s

Test fiddle with TinyMCE 3.5.8
Here is a fiddle which does use same source code but TinyMCE 3.5.8 is selected: http://fiddle.tinymce.com/BHdaab/26
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6561](http://archive.tinymce.com/develop/bugtracker_view.php?id=6561) posted by [thomi](http://archive.tinymce.com/profile.php?name=thomi)_

> _**Tags:** [msie ie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/BHdaab/18_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
