### ISSUE TITLE
Adding border to images does not work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1333]
Description of problem:
When adding a border to an image nothing seem to happen.

Steps to reproduce:
1. Go here http://www.tinymce.com/tryit/full.php
2. Select the image and click the image button
3. In advanced add a border and click ok.

Expected result:

A border should be added to the image.

Actual result:

Nothing happened.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6566](http://archive.tinymce.com/develop/bugtracker_view.php?id=6566) posted by [Jim Westergren](http://archive.tinymce.com/profile.php?name=Jim Westergren)_
> 
> _**Tags:** [firefox chrome image border]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
I believe this is similar to #2754. Could you have please have a look and let us know if not? Thanks,
Millie @ TinyMCE

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
