### ISSUE TITLE
Link highlight

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1336]
Steps to reproduce:
1. Create a link.
2. Start selection from the left side and end it in the middle of the link.
3. Start selection from the right side and end it in the middle of the link.

Expected result:
In case (2) it's correct. "Link" icon is not highlighted.

Actual result:
In case (3) it's not correct. "Link" icon is highlighted even if the selection doesn't fully cover the link.

Proposed solution:
1. Get selection start, one node above text node.
2. Get selection end, one node above text node.
3. if(node1 === node2){ highlight the link icon }
4. See Microsoft Word for reference. They highlight buttons properly.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6570](http://archive.tinymce.com/develop/bugtracker_view.php?id=6570) posted by [Trevlon](http://archive.tinymce.com/profile.php?name=Trevlon)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
