### ISSUE TITLE
drag and drop picture not working in Internet Explorer 11

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1337]
Description of problem:

Steps to reproduce:
1.Add multiple images in tinymce editor
2.try to move position by dragging image, which will work on all browser except
Internet Explorer.. (IE 11)
3.it should atleast work on internet explorer 11 (which is latest and fast growing version.)
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6571](http://archive.tinymce.com/develop/bugtracker_view.php?id=6571) posted by [nirav.ce.2008](http://archive.tinymce.com/profile.php?name=nirav.ce.2008)_

> _**Tags:** [msie msie8 msie10 msie11 msie 11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
