### ISSUE TITLE
Add class, at image panel

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1340]
Hi,
in the next version you can add class, panel images?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6575](http://archive.tinymce.com/develop/bugtracker_view.php?id=6575) posted by [pmi](http://archive.tinymce.com/profile.php?name=pmi)_
> 
> _**Tags:** [firefox msie safari chrome opera media image 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
