### ISSUE TITLE
Add dataTransfer.files to moxiemanager upload

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1341]
It would be great if the moxiemanager upload API function could take the dataTransfer.files as a parameter. This would allow developers to add a custom droppable and then integrate moxiemanager to do the grunt work of uploading the files.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6576](http://archive.tinymce.com/develop/bugtracker_view.php?id=6576) posted by [bludginozzie](http://archive.tinymce.com/profile.php?name=bludginozzie)_
> 
> _**Tags:** [moxiemanager upload]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
