### ISSUE TITLE
Changing Forecolor Formats

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1342]
Description of problem:  When changing formats for forecolor to handle anchor tags differently and putting in a format to handle all other tags as they were is not working correctly when trying to clear formatting.

Steps to reproduce:
1. Go to the fiddle supplied.
2. Put in multiple lines of text with multiple words.  Make sure each line has it's own &ltg;p> tag.
3. Highlight all the text and change the forecolor.
4. Highlight a word within the text and click the clear formatting.

Expected result: Individual word should not look like others.

Actual result:  Nothing is applied to word, going to code view verifies this.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6577](http://archive.tinymce.com/develop/bugtracker_view.php?id=6577) posted by [flynnformz](http://archive.tinymce.com/profile.php?name=flynnformz)_

> _**Tags:** [firefox msie safari chrome opera forecolor formats]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/qIdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
