### ISSUE TITLE
Pasting from Word into TinyMCE not working in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1344]
Description of problem:

When copy & pasting text from Word 2013 into TinyMCE (in IE), the text gets pasted formatted.

Steps to reproduce:
1. Create a TinyMCE editor.
2. Go to MS Word 2013, and enter some text and color it.
3. Copy the text and paste it in TinyMCE. It works in Chrome & Firefox, but not in IE, tested in IE 11.

Expected result:

Not formatted text in TinyMCE.

Actual result:

Text formatted like it was in Word.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6581](http://archive.tinymce.com/develop/bugtracker_view.php?id=6581) posted by [Devils Child](http://archive.tinymce.com/profile.php?name=Devils Child)_

> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Thanks for letting us know it was fixed, I'll close this report now. Let me know if you do find this problem again though, and I'll reopen it. Thanks,
Millie @ TinyMCE
