### ISSUE TITLE
Image can't put into textarea of tinymce

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1345]
Description of problem:

Steps to reproduce:
1.Launch IE8
2.Click outside of tinymce editor.
3.Click insert image on tinymce editor, chose image then click Button insert. 

Expected result:
  I hope the image put into content textarea of tinymce.

Actual result:
  This image can't put into textarea of tinymce

tinymce version: 4.0.11
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6585](http://archive.tinymce.com/develop/bugtracker_view.php?id=6585) posted by [loln](http://archive.tinymce.com/profile.php?name=loln)_

> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/index.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
