### ISSUE TITLE
Stylemerge bug

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1347]
Description of problem:

Steps to reproduce:
1. Open fiddle
2. Place caret behind the "A"
3. Hit delete(not backspace!) on your keyboard, to bring up the "B" directly behind the "A"

Expected result:
Red "A", green "B"

Actual result:
"A" and "B" become green. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6586](http://archive.tinymce.com/develop/bugtracker_view.php?id=6586) posted by [msvc](http://archive.tinymce.com/profile.php?name=msvc)_
> 
> _**Tags:** [firefox]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://fiddle.tinymce.com/fJdaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
