### ISSUE TITLE
Page up/page down moves cursor but not scroll on Windows

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1348]
Description of problem:

Steps to reproduce:
1. Enter enough text to get a scroll bar
2. Use the page up and page down buttons

Expected result:
The scroll bar will move to the cursor position.

Actual result:
The cursor moves, but the scroll bar does not.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6587](http://archive.tinymce.com/develop/bugtracker_view.php?id=6587) posted by [aaron-nance](http://archive.tinymce.com/profile.php?name=aaron-nance)_

> _**Tags:** [msie msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
