### ISSUE TITLE
Plugin insertdatetime does not translate

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1350]
Applies still in Vers. 4.0.12

plugin.js
line 89
- is        -> title: 'Insert time',
- should be -> title: 'Insert date/time',

lines 46-49
fmt = fmt.replace("%B", "" + editor.translate(monthsLong[date.getMonth()]));
fmt = fmt.replace("%b", "" + editor.translate(monthsShort[date.getMonth()]));
fmt = fmt.replace("%A", "" + editor.translate(daysLong[date.getDay()]));
fmt = fmt.replace("%a", "" + editor.translate(daysShort[date.getDay()]));

monthsLong, monthsShort, daysLong, daysShort are not part of translation file. I couldn't figure out how to add an array to translation file to make it work. Prob. translation function doesn't support yet.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6588](http://archive.tinymce.com/develop/bugtracker_view.php?id=6588) posted by [SchuPi](http://archive.tinymce.com/profile.php?name=SchuPi)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
