### ISSUE TITLE
Paste function is not working with paste button on toolbar or from edit menu

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1351]
The problem is only with "paste button" either you access it from toolbar or from "edit" menu, Pasting contents using those buttons produces error and donot paste copied contents to the editor window.

Example: http://www.tinymce.com/tryit/basic.php

Steps to reproduce:
1. copy text from some other page or software like MS word
2. click the "Paste" button on the tool bar in tinyMCE editor to paste contents.
3. There will be some error instead of the successful paste of those copied contents.
4. Now use the "Paste" from the "Edit" menu bar.
5. It will produce the same error given above.
6. Now use "Ctrl+X/C/V" keyboard shortcuts instead, this will paste contents to editor window and there will be no errors. This issue is on tinyMCE's official demo too.

Expected result: Error with following error message
--------------------------
Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.
--------------------------

Actual result: Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6589](http://archive.tinymce.com/develop/bugtracker_view.php?id=6589) posted by [shahzad11](http://archive.tinymce.com/profile.php?name=shahzad11)_

> _**Tags:** [firefox msie safari chrome opera paste button copy]_
> _**Status:** Closed_
> _**Resolution:** Wont Fix_
> _**Attached URL:** none_

**Comment by Hypnos3** [comment]
I have the same error in the edge browser, which uses the chrome engine. So why it is allowed in Crome, but not in edge?
On other tools this is working in both browsers.

**Comment by enoh-barbu** [comment]
at least it can ask for, as word does
![Image](https://github.com/user-attachments/assets/096b618e-755a-4c4d-8618-3683d18fd1f1)
