### ISSUE TITLE
"Insert horizontal rule" button not being translates

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1352]
Description of problem:
Button "Insert horizontal rule" (hr) tooltip is not being translated.
I couldn't create a fiddle because it seems that it doesn't support other languages, it gave me a load error when trying to get the language file.

Steps to reproduce:
1. Add language: "pt_BR" in the configuration. Or other language, i tryed with dutch (nl).
2. Add the "hr" button to the toolbar.
3. Hover on "hr" the button;

Expected result:
The tooltip text will be translated, like the other buttons.

Actual result:
The tooltip text is shown in english.

I'm attaching the project since I couldn't create the fiddle.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6590](http://archive.tinymce.com/develop/bugtracker_view.php?id=6590) posted by [migore](http://archive.tinymce.com/profile.php?name=migore)_
> 
> _**Tags:** [firefox msie safari chrome opera i18n]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
