### ISSUE TITLE
Safari 6.1 cmd-v does not paste in TinyMCE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1353]
Description of problem: Safari 6.1 cmd-v does not paste in TinyMCE

Steps to reproduce:
1. Copy text to clipboard in Safari 6.1 on OS X 10.8.5
2. Go to a TinyMCE 4.0.12 editor (for example on this site's homepage)
3. Attempt to paste with command-V

Expected result: Text from clipboard should paste

Actual result: A blank line and the letter "v" are inserted

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6591](http://archive.tinymce.com/develop/bugtracker_view.php?id=6591) posted by [hyperizer](http://archive.tinymce.com/profile.php?name=hyperizer)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/index.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
