### ISSUE TITLE
Insert / Edit Link Doesn't inserts Hyperlinks to Image in version 4, however it was supported in version 3

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1354]
Description of problem:

Hi, whenever I click on Insert / Edit Link context menu option on any Image, and set a hyperlink, it replaces the Image with that hyperlink instead of linking Image with that Hyperlink.

Steps to reproduce:
1. Insert an Image in Tiny MCE editor version 4.x
2. Right click on that image to get context menu options
3. Click on Insert Link Option
4. Write any URL with Text to display field and Hit OK
5. You will see that the Image is replaced by hyperlink

Expected result:
Image should be hyperlinked with newly created link

Actual result:
Image gets replaced with the newly created hyperlink.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6592](http://archive.tinymce.com/develop/bugtracker_view.php?id=6592) posted by [mohansinfh](http://archive.tinymce.com/profile.php?name=mohansinfh)_

> _**Tags:** [firefox msie safari chrome opera insert edit link image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
