### ISSUE TITLE
TinyMCE 3.5.10 - production version comes with all src files

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1356]
TinyMCE 3.5.10 production version comes with all plugin _src.js files.
Kinda waste of space isn't it?
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6594](http://archive.tinymce.com/develop/bugtracker_view.php?id=6594) posted by [manu37](http://archive.tinymce.com/profile.php?name=manu37)_

> _**Tags:** [optimize]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
