### ISSUE TITLE
IE11 Doesn't get content in text format when plugin in popup

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1357]
Description of problem:

When trying to get only the selected text from the editor, without any markings, IE11 returns an empty string. When format is not defined, returns content mith markup.

Minimal plugin included for testing. Works with IE8, IE9 and IE10

Steps to reproduce:
1. Create plugin that opens a popup (windowManager.open)
2. Include actual javascript in popup
3. Get selection (var sel = tinyMCEPopup.editor.selection)
4. get content (sel.getContent({format : 'text'}))

Expected result:

Selected text from editor without any markup

Actual result:

An empty String

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6595](http://archive.tinymce.com/develop/bugtracker_view.php?id=6595) posted by [teroj](http://archive.tinymce.com/profile.php?name=teroj)_
> 
> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
