### ISSUE TITLE
Table inside single TD with no other elements

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1358]
Description of problem:
When inserting a table into a table with one cell, you cannot target the parent table.
In FF, you can target it if you double click on the border (or empty space if there is any).
In IE, you can't target it

Steps to reproduce:
1. Insert a 1x1 table ("parent table")
2. Insert another table ("child table") into the cell of the previous table
3. Do not add any other element to the table cell

Expected result:
When right clicking on "parent table" and choosing table properties, will open a dialog box for "parent table"

Actual result:
The dialog box is for "child table"

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6597](http://archive.tinymce.com/develop/bugtracker_view.php?id=6597) posted by [tomlevy](http://archive.tinymce.com/profile.php?name=tomlevy)_
> 
> _**Tags:** [firefox msie msie7 msie8 msie9 msie10 table firefox ie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
