### ISSUE TITLE
MCE4 - IE - Fullscreen - alt+s

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1359]
On IE with the fullscreen mode, when the alt+S shortcut is used to submit the form, the fullscreen remains (which is the previous instance of mce).

I've tried, to prevent this shortcut but it doesn't seem possible. So I've just used a basic solution:

```
        ed.on('submit', function() {
            if(parent.isFullscreen()){
                ed.execCommand('mceFullScreen');
            }
        });
```

About the fullscreen function:
            /\* Fullscreen State */  
            this.isFullscreen = function(e) { 
                if(ed.plugins.fullscreen === undefined)
                    return false
                else
                    return ed.plugins.fullscreen.isFullscreen();
            };

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6598](http://archive.tinymce.com/develop/bugtracker_view.php?id=6598) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
