### ISSUE TITLE
Invalid display of an anchor with text within it 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1360]
1.Add allow_html_in_named_anchor: true to the init function of tinymce
2. insert this HTML code to the editor directly from the source code window
&ltg;p>just a test&nbsp;&ltg;a id="test">&ltg;/a>&ltg;/p>

The display of the anchor in the editor is invalid due to the fixed width and height defined in the mce-item-anchor class

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6634](http://archive.tinymce.com/develop/bugtracker_view.php?id=6634) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_

> _**Tags:** [firefox msie safari chrome opera anchor allow_html_in_named_anchor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/QMdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
