### ISSUE TITLE
Attributes Class textfield as default (with existing value)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1361]
Hello tinymce Team!

when adding a css class through the textfield, this class is afterwards not visible in the attributes window. Not in the dropdown and not in the textfield.

But this is a must have because after saving the attributes again, the existing css class will getting deleted.

Could you please check this?

Furthermore, but not urgently needed, would be an option to set the textfield as default.

please hava a look at the attached screenshot.

Thank you so much!

Greets
Felix

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6635](http://archive.tinymce.com/develop/bugtracker_view.php?id=6635) posted by [jeffpixmex](http://archive.tinymce.com/profile.php?name=jeffpixmex)_
> 
> _**Tags:** [attributes css]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
