### ISSUE TITLE
issue with embedded Iframe tag

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1363]
Description of problem:
I use Tinymce on rails.
I have issue when I try to save it redirect to wrong unknown destination called "data;". it actually saves the data but it produces a very strange url redirection, and this only happens with chrome and only happens if I embed a iframe tag into the editor.

this issue is not appearing in Firefox. 

any clue

thank you

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6600](http://archive.tinymce.com/develop/bugtracker_view.php?id=6600) posted by [moustafasallam](http://archive.tinymce.com/profile.php?name=moustafasallam)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
