### ISSUE TITLE
Missing outline preview in formats listbox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1364]
A format with outline attribute is not well rendered in the formats listbow.
After checking, it seems that the outline attribute is missing in the preview css style attributes

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6601](http://archive.tinymce.com/develop/bugtracker_view.php?id=6601) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_
> 
> _**Tags:** [firefox msie safari chrome opera preview ouline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
