### ISSUE TITLE
IE11 bogus elements not removed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1365]
Description of problem:
In IE11 the bogus mce tags are not properly being removed when getContent() is called.  This problem does not seem to occur unless a jquery UI dialog is involved.

The problem does not occur in Chrome or in IE10.  Additionally, if the document mode is specified to be IE=10, IE11 works as well.  The problem only seems to manifest in IE11 with edge document mode.  

Steps to reproduce:
1. Navigate to http://fiddle.tinymce.com/BKdaab
2. Click "Open"
3. Input some text in to MCE (or leave it blank, doesn't matter)
4. Click "OK" in dialog
*** One thing to note is the that output before the dialog Close is called is correct and does not contain the extra elements.  Only after the dialog is closed do the extra tags appear.

Expected result:
If no text was input in to MCE, getContent() should return empty string. If text was input, it should not contain the extra &ltg;p>&ltg;br/>&ltg;br/>&ltg;/p> block.

Actual result:
When no text is input, the result from getContent() is &ltg;p>&nbsp;&ltg;/p>&ltg;p>&ltg;br/>&ltg;br/>&ltg;/p>
If the text "abcdefg" is input, the result form getContent() is 
&ltg;p>abcdefg&ltg;/p>&ltg;p>&ltg;br/>&ltg;br/>&ltg;/p>

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6602](http://archive.tinymce.com/develop/bugtracker_view.php?id=6602) posted by [jd98](http://archive.tinymce.com/profile.php?name=jd98)_

> _**Tags:** [msie ie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/BKdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
