### ISSUE TITLE
Can't move/delete float left image IE11/Win7

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1366]
Description of problem: Can't move/delete a left justified image. Windows 7 64bit / ie11

Steps to reproduce:
1. go to the demo page: http://www.tinymce.com/tryit/basic.php
2. click on the existing blue logo that's on the right, and left justify it
3. try and move the image in the page, or change the alignment or delete it

Expected result: To be able to move/delete the image

Actual result: Image is now 'lost' to tiny, you must go into the source to remove/edit it

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6640](http://archive.tinymce.com/develop/bugtracker_view.php?id=6640) posted by [Racine-Web](http://archive.tinymce.com/profile.php?name=Racine-Web)_
> 
> _**Tags:** [msie image ie11 win7]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
