### ISSUE TITLE
Adding class to images adds it to span

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1367]
Adding a class to an image via the Formats menu in fact adds it to a new span created around the image.
The result is that the class is not applied to the image.

Only way for now in 4.0.12 is to add the class manually.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6603](http://archive.tinymce.com/develop/bugtracker_view.php?id=6603) posted by [infograf768](http://archive.tinymce.com/profile.php?name=infograf768)_

> _**Tags:** [firefox msie safari chrome opera image class]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
