### ISSUE TITLE
toolbar's container (or border) is displayed vertically

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1368]
this problem occurs randomly, I cannot reproduce it at will and doesn't happen all the time but it's pretty annoying when it does

  
toolbar's container (or border) is displayed vertically and the buttons horizontally (as it should). 

it seems that width and hight for div.mce-tinymce.mce-tinymce-inline.mce-container.mce-panel and div.mce-toolbar-grp.mce-container.mce-panel.mce-first.mce-last.mce-abs-layout-item are set backwards 

I'm using tinyMCE 4.0.12 and chrome 31 (I'm going to start using other browser to see if this problem happens again and when it does I'll update this post with a screenshot)
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6605](http://archive.tinymce.com/develop/bugtracker_view.php?id=6605) posted by [juanpa](http://archive.tinymce.com/profile.php?name=juanpa)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
