### ISSUE TITLE
Skin creator / border-radius / Lag in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1369]
Description of problem: When I create a skins with the skin creator and uncheck the border-radius checkbox. The scrolling in Chrome will be disturbed. It's a laggy effect.

Steps to reproduce:
1. Create a skin without border-radius
2. Create a page where the textarea is hidden because your screen is to small
3. Start scrolling down 
4. When you approach the textarea you'll experience lag
5. (I resolved the problem by manually change the border-radius in de skin css)

Expected result: Smooth scrolling

Actual result: Laggy scrolling

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6606](http://archive.tinymce.com/develop/bugtracker_view.php?id=6606) posted by [CrushTheButton](http://archive.tinymce.com/profile.php?name=CrushTheButton)_
> 
> _**Tags:** [chrome chrome13]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://skin.tinymce.com/_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
