### ISSUE TITLE
Remove()

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1370]
Steps to reproduce:
1. Setup TinyMCE.
2. Call tinymce.remove().

Expected result:
It restores textarea or DIV as it was prior to initialization (with new content).

Actual result:
After removal:
- the DIV still has its id="mce_1",
- it has "spellcheck" attribute that wasn't present before,
- it doesn't have "contenteditable" attribute (but it had it before),
- trying to do remove(), clone() with jQuery and initialization doesn't work because of that - it initializes twice on the first contenteditable area.
- similar request created by someone else: http://stackoverflow.com/questions/17759111/tinymce-4-remove-or-destroy (the accepted answer isn't the answer to this question)
  > _**Legacy information imported from TinyMCE bug tracker:**_
  >
  > _[#T6607](http://archive.tinymce.com/develop/bugtracker_view.php?id=6607) posted by [Trevlon](http://archive.tinymce.com/profile.php?name=Trevlon)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
