### ISSUE TITLE
In IE8, dblclick textarea to edit the content is not support anymore

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1374]
Description of problem:

Steps to reproduce:
1. using Internet Explorer 8
2. invoke tinymce.activeEditor.setContent("&ltg;textarea>Hello World!!&ltg;/textarea>");
3. double click the &ltg;textarea> in editor

Expected result:
 in TinyMCE3.x @IE8 we can edit the content of textarea
 (just as http://fiddle.tinymce.com/CNdaab )

Actual result:
 in TinyMCE4.x @IE8 we cannot edit anymore
 (just as http://fiddle.tinymce.com/BNdaab )
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6648](http://archive.tinymce.com/develop/bugtracker_view.php?id=6648) posted by [grassboy](http://archive.tinymce.com/profile.php?name=grassboy)_

> _**Tags:** [msie msie8 textarea editable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/BNdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
