### ISSUE TITLE
link class attribute / styles

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1375]
Be able to define a list of css classes that should be available to define for a link when creating one.

This is critical when creating custom links on your page that should look like buttons.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6611](http://archive.tinymce.com/develop/bugtracker_view.php?id=6611) posted by [yze](http://archive.tinymce.com/profile.php?name=yze)_
> 
> _**Tags:** [link class styles]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
