### ISSUE TITLE
Duplicate an image while moving it

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1377]
Description of problem:
When an image is inserted in the editor with Internet Explorer 8, if I try to move it with the mouse, a second image is created. Each time I move the image, a new clone is made.

Steps to reproduce:
1.Insert an image
2.Move it in the text by drag'n'dropping with the mouse

Expected result:
The original image should have moved

Actual result:
A duplicate of the original image have moved
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6612](http://archive.tinymce.com/develop/bugtracker_view.php?id=6612) posted by [ElsaNelson](http://archive.tinymce.com/profile.php?name=ElsaNelson)_

> _**Tags:** [msie msie8 ie8 image move drag clone dublicate]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
