### ISSUE TITLE
Tinymce replacing current tag with new tag

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1379]
Description of problem:
The problem is when we have X number of inner elements and then main content, If we try to insert tags like heading tags or p tag to content by tinymce, It replaces current tag with new one.

Steps to reproduce:
1. Add 2 or 3 inner div's in textarea and then main content like, 
&ltg;textarea>&ltg;div>
    &ltg;div>
        &ltg;div>
        My Content
        &ltg;/div>
    &ltg;/div>
&ltg;/div>&ltg;/textarea>
2. So in editor it will show like, div > div > div > My Content
3. Try to insert H1 to My Content
4. It will replaces current node div with H1, div > div > h1 > My Content

Expected result:
The expected result is,
div > div > div > h1 > My Content

Actual result:
div > div > h1 > My Content

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6614](http://archive.tinymce.com/develop/bugtracker_view.php?id=6614) posted by [amitsukapure](http://archive.tinymce.com/profile.php?name=amitsukapure)_
> 
> _**Tags:** [firefox msie safari chrome opera formatting selection]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/3Ldaab/2_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
