### ISSUE TITLE
mce-window footer overflows horizontally

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1381]
Description of problem:
Please see the attached image

Steps to reproduce:
Attached image could be more helpful than repro steps.

Expected result:
mce window footer shouldnt overflow 

Actual result:
mce window footer overflows

Temporary Fix:
Add something like below

$("&ltg;style>.mce-window {overflow: hidden;}&ltg;/style>").appendTo("head");

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6654](http://archive.tinymce.com/develop/bugtracker_view.php?id=6654) posted by [mertdeg](http://archive.tinymce.com/profile.php?name=mertdeg)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
