### ISSUE TITLE
auto_focus and inline editor not working in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1384]
Description of problem:
Inline editors does not auto focus in MSIE 11. Works as expected in Chrome  32.0.1700.76.
Everything works as expected if you make the editor none inline, i.e. remove line 6; inline:true,.

Steps to reproduce:
1. Open fiddle link http://fiddle.tinymce.com/ONdaab/6
2. Click Edit

Expected result:
Toolbar appear and text area is focused

Actual result:
The div is editable but nothing else happens

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6656](http://archive.tinymce.com/develop/bugtracker_view.php?id=6656) posted by [jonsten](http://archive.tinymce.com/profile.php?name=jonsten)_

> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/ONdaab/6_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
