### ISSUE TITLE
Backspace after span with contenteditable="false" set will move caret to end of line in Internet Explorer 9/10.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1385]
Description of problem:

Steps to reproduce:
1. In IE9/10 type this into the source of the editor: 
&ltg;p>&ltg;span contenteditable="false">TEST SPAN&ltg;/span>TEXT OUTSIDE SPAN&ltg;/p>
2. Place caret after the first 'T' that occurs after TEST SPAN (EX: TEST SPANT|EXT OUTSIDE SPAN)
3. Press backspace.
4. Notice the caret jumps to the end of the line.

Expected result:
Caret should move one to the left.

Actual result:
Caret jumps to the end of the line.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6618](http://archive.tinymce.com/develop/bugtracker_view.php?id=6618) posted by [JYIC](http://archive.tinymce.com/profile.php?name=JYIC)_

> _**Tags:** [msie msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by trepmal** [comment]
I'm able to replicate this in the demo editor on https://www.tinymce.com/

With this content:
```
<div contenteditable="false">not this</div>
a b c d e
```

If I select `a b c d e` and hit backspace, the caret moves and the content is not deleted.

Tested in Chrome (v 58.0.3029.33 beta) and Firefox (v 52.0.1) on macOS (v 10.12.3)

Notably, this issue surfaces in WordPress, since oEmbed items are wrapped in a `contenteditable="true"` div in the _Visual_ editor.

**Comment by blackcathikari** [comment]
@trepmal Thanks for the example and environment details. Looks like the original bug is fixed, but we were able to replicate your bug on macOS. Could you please create a new ticket for this? I would, but it would be good to have your username on it so we can get back to you about it. If you could link it to this ticket by mentioning it (# 1385 without the space), I'll add a comment saying I've verified it.

**Comment by trepmal** [comment]
Thanks, issue created :) #3559

**Comment by blackcathikari** [comment]
Done, thanks for that. Since managed to replicate in Windows though it seems a bit more picky than OSX, so I added that too.
