### ISSUE TITLE
tinymce print is not working in IE9 quirks mode

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1386]
Description of problem:
Tinymce fail to print in IE9 quirks mode

Steps to reproduce:
1. Create an html without doctype with tinymce 
2. Use IE9 browser print (File > Print... or right click on the iframe, Print...)
3. The printout for text area is blank
4.
5.

Expected result:
Print out text area content

Actual result:
Print out blank content
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6619](http://archive.tinymce.com/develop/bugtracker_view.php?id=6619) posted by [JamesLien](http://archive.tinymce.com/profile.php?name=JamesLien)_

> _**Tags:** [msie msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/KLdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
