### ISSUE TITLE
BOLD in start of editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1390]
Description of problem:

Steps to reproduce:
1. Make the first paragraph or something BOLD. 
2. Try to add a new line on top
3. The new lines stays bold, whatever you try. Except when you edit in the 'code'
4. Try it on: http://www.tinymce.com/tryit/basic.php

Expected result:
New lines without formatting

Actual result:
Same formatting as the first line.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6625](http://archive.tinymce.com/develop/bugtracker_view.php?id=6625) posted by [roetje](http://archive.tinymce.com/profile.php?name=roetje)_

> _**Tags:** [firefox msie safari chrome opera bold text]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
