### ISSUE TITLE
Nopcommerce users experience <br/></p> tags??? Breking layouts

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1393]
Description of problem:
See post on nopcommerce....with so many bugs reported here..i am a bit afraid it Will not be fixed soon......??

You can log in to nop demo admin site, navigatie to catalog..--->>product or catalog.

Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:
No br and p all over the place

Actual result:
Inserts of br and p tags

Hope this Will be fixed soon(er).....

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6627](http://archive.tinymce.com/develop/bugtracker_view.php?id=6627) posted by [Quantis001](http://archive.tinymce.com/profile.php?name=Quantis001)_

> _**Tags:** [br p]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.nopcommerce.com/boards/t/27884/bug-pbr-br-br-br-br-p-on-catalog-and-product-breaking-site-layout.aspx_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
