### ISSUE TITLE
Unnecessary table styles in inline editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1397]
In the inline editor, there are styles that override the page's table styles. They come from Content.Objects.less:

https://github.com/tinymce/tinymce/blob/master/js/tinymce/skins/lightgray/Content.Objects.less#L61

and are imported into Content.inline.less:

https://github.com/tinymce/tinymce/blob/master/js/tinymce/skins/lightgray/Content.Inline.less#L3

This is undesirable for the inline editor because it overrides the table's border width, border-border-style, and border-color. This has the potential to alter the layout of the page, particularly if the table has wide borders. It also causes confusion when resizing, as the table's true width is visually indeterminable when table borders are greater than 1px.

One way to workaround this is to remove the styles from Content.Objects.less, but this isn't an option for folks that aren't compiling themselves.

It's unfortunately not easy to override, especially in a CMS environment where the table styles may vary for each page.

Another options is to create a new skin, but this seems like overkill for something that probably shouldn't be there in the first place.

Any thoughts on removing this for the inline editor?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6630](http://archive.tinymce.com/develop/bugtracker_view.php?id=6630) posted by [aksival](http://archive.tinymce.com/profile.php?name=aksival)_
> 
> _**Tags:** [css inline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
