### ISSUE TITLE
Paste from Word in IE 11 not working with line breaks

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1398]
Paste From Word in IE11 not working with line breaks  (Shift + Enter).
The br tag is removed.
In Firefox and Chrome this work 

Steps to reproduce:
1.Copy text (with line breaks) from Word 2010
2.Paste (Ctrl + V) in tinymce editor v4.0.12 in  Internet Explorer 11

Expected result:

Test
test
test
test

Actual result:

Test test test test

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6631](http://archive.tinymce.com/develop/bugtracker_view.php?id=6631) posted by [10pm](http://archive.tinymce.com/profile.php?name=10pm)_
> 
> _**Tags:** [msie v4012 ie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
We've looked into this and believe this bug could come under the wider scope of #2083. Could you please take a look and let us know if you agree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
Closing this, look at issue linked above instead.
