### ISSUE TITLE
figurecaption tag

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1401]
Current version (4.0.12) strips out the figurecaption HTML5 tag. Full HTML5 tag support would be fantastic in future versions.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6636](http://archive.tinymce.com/develop/bugtracker_view.php?id=6636) posted by [HCAdmin](http://archive.tinymce.com/profile.php?name=HCAdmin)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
