### ISSUE TITLE
Anchors are forcing text out into their parents

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1402]
Description of problem:

Steps to reproduce:
1. Open the jsfiddle
2. Tools -> Source Code
3. Paste this content: &ltg;p>&ltg;a style="color: red;" id="mylink">testing&ltg;/a>&ltg;/p>
4. Press Ok
5. Tools -> Source Code

Expected result:

a red link "testing"

Actual result:

broken link with "testing" in wrapping P tag

Additional Notes:

I can fix this bug by setting allow_html_in_named_anchor to true, although there is no HTML being used in the anchors.

Certain usage of certain attributes causes the behavior. Examples)

Break:
- &ltg;p>&ltg;a name="testing">testing&ltg;/a>&ltg;/p>
- &ltg;p>&ltg;a id="mylink">testing&ltg;/a>&ltg;/p>

Works:
- &ltg;p>&ltg;a name="testing" href="mylink">testing&ltg;/a>&ltg;/p>

Thank you tinyMCE!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6637](http://archive.tinymce.com/develop/bugtracker_view.php?id=6637) posted by [rocksfrow](http://archive.tinymce.com/profile.php?name=rocksfrow)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/QMdaab/3_

**Comment by rbaylis91** [comment]
Howdy — Here's another example of this:

```
<ul class="jp-controls"> 
<li><a class="jp-previous" tabindex="1" id="jplayer_1_prev">previous</a></li> 
<li><a class="jp-play" tabindex="1">play</a></li> 
<li><a class="jp-pause" tabindex="1">pause</a></li> 
<li><a class="jp-next" tabindex="1" id="jplayer_1_next">next</a></li> 
<li><a class="jp-mute" tabindex="1" title="mute">mute</a></li> 
<li><a class="jp-unmute" tabindex="1" title="unmute">unmute</a></li> 
</ul>
```

When you hit save, it changes line 2 to:
`<li><a class="jp=previous" tabindex="1" id="jplayer_1_prev">previous</a></li>`

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
