### ISSUE TITLE
Cursor jumps on ipad to the top of screen while editing

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1403]
Description of problem:
Cursor moves its position outside editor to the top of screen in ipad while typing text inside editor
Steps to reproduce:
1. Open editor inside div in ipad
2. when tapped focus is inside editor with bottom half keyboard
3. Start typing inside editor
4. 
5.

Expected result: cursor should maintain its position inside editor while typing text in ipad

Actual result: cursor jumps out of editor and shifts to the top of screen while typing

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6674](http://archive.tinymce.com/develop/bugtracker_view.php?id=6674) posted by [gauravshenolikar](http://archive.tinymce.com/profile.php?name=gauravshenolikar)_

> _**Tags:** [safari safari5]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Taygair** [comment]
Hi, I've experienced this problem (cursor set at beginning of text) in Safari Browser (Mac) on inserting content in these ways:
tinymce.get('editor_id').insertContent("insert content");
tinymce.activeEditor.execCommand('mceInsertContent', false, "insert content");

**Comment by dsakko** [comment]
Hi Taygair,

We haven't been able to reproduce this so far with our environments. Are you able to set up a codepen that reliably reproduces it?

Thanks.

**Comment by Taygair** [comment]
Hi 
I had some plugins running in the background of Safari-Browser. Deactivating them and everything works fine. Sorry for wrong message!
