### ISSUE TITLE
extended_valid_elements not allowing empty anchors

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1405]
Description of problem:

Empty anchors are getting removed regardless of extended_valid_elements value. With extended_valid_elements set to 'a[*]', or even '*[*]' empty anchors will get removed UNLESS they have a name attribute.

Steps to reproduce:
1. Go to jsfiddle
2. Tools -> Source Code
2. Paste: &ltg;a id="linkplaceholder">&ltg;/a>
3. Press ok
4. Tools -> Source Code

Expected result:

&ltg;p>&ltg;a id="linkplaceholder">&ltg;/a>&ltg;/p>

Actual result:

&ltg;empty>

Additional Notes:

If you paste: &ltg;a name="link" id="link">&ltg;/a> the link will stick around. That makes sense as default behavior, but even spockes statement from the thread below contradicts this behavior... extended_valid_elements should override the default behavior... yes?

See: http://www.tinymce.com/forum/viewtopic.php?pid=99873#p99873

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6638](http://archive.tinymce.com/develop/bugtracker_view.php?id=6638) posted by [rocksfrow](http://archive.tinymce.com/profile.php?name=rocksfrow)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/QMdaab/4_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
