### ISSUE TITLE
Paste as plain text popup in IE 11 hides the insert and cancel buttons initially

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1406]
Description of problem:

Steps to reproduce:
1. Try to paste a text in IE 11 (using Ctrl+V for Paste as plain text)
2. The popup to paste as plain text opens
3. The insert and cancel button are hidden
4. Can be visible after resizing the popup window
5. Only observed on IE 11. Works fine for all other browsers.

Expected result: The insert and cancel buttons should be visible on its own

Actual result: The insert and cancel buttons are visible only after popup window resize

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6682](http://archive.tinymce.com/develop/bugtracker_view.php?id=6682) posted by [shailee](http://archive.tinymce.com/profile.php?name=shailee)_

> _**Tags:** [msie paste plain text ie11 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
