### ISSUE TITLE
Resizable Preview Popup

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1408]
The Preview Popup size in TinyMCE 3.X can be configured.

 plugin_preview_width: W,
 plugin_preview_height: H,

This allows us to make it big enough for viewing.

Can we have similar feature in TinyMCE 4?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6686](http://archive.tinymce.com/develop/bugtracker_view.php?id=6686) posted by [wizlearn](http://archive.tinymce.com/profile.php?name=wizlearn)_
> 
> _**Tags:** [preview]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
