### ISSUE TITLE
Listbox doesn't stick when scroll

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1411]
Description of problem:

Steps to reproduce:
1. Click on Insert
2. Select Insert Link
3. Select Target - (click on "None")
4. Scroll. 

Expected result:
It should just scroll the listbox or select items.

Actual result:
It scrolls the background as well.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6642](http://archive.tinymce.com/develop/bugtracker_view.php?id=6642) posted by [ysrb](http://archive.tinymce.com/profile.php?name=ysrb)_

> _**Tags:** [firefox chrome chrome13 listbox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/yNdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
