### ISSUE TITLE
Advanced Link doesn't work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1412]
Description of problem:
I have older CMS - Mambo with TinyMCE, it used to work fine, but then suddenly advanced link feature stopped working - pop up comes out empty and there is no chance to add link. Not sure if it is bug in TinymCE, I rather look for idea and advice how to fix it. I upgraded to 3.5.10 and then to 4.0.11, but the behavior is still the same - I went back to 3.5.10.

Steps to reproduce:
1.I open content item in my CMS where TinyMCE is used as editor.
2. I highlight text and insert the link on that text - advanced link pop up pops up. 
3. I used to insert the link using form in the advanced link pop up in the past
4.
5.

Expected result:

Link inserted using advanced link pop up. 

Actual result:

Advanced link pop up is empty - perhaps link.htm is damaged ???

Thank you!
BR,
Roman
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6643](http://archive.tinymce.com/develop/bugtracker_view.php?id=6643) posted by [rx71](http://archive.tinymce.com/profile.php?name=rx71)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** tinymce/jscripts/tiny_mce/themes/advanced/link.htm_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
