### ISSUE TITLE
Toolbar or Menu for Database Actions

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1416]
Hey guys,

Can you add a new toolbar or menu for database actions using PHP, like connect, query, etc. so they can easily be inserted into your page with TinyMCE instead of going to source and typing everything.

Thanks.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6694](http://archive.tinymce.com/develop/bugtracker_view.php?id=6694) posted by [jfha73](http://archive.tinymce.com/profile.php?name=jfha73)_
> 
> _**Tags:** [firefox msie safari chrome opera databases]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
