### ISSUE TITLE
Bold and Italics button do not work with Hyperlink

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1417]
Description of problem:

Steps to reproduce:
1. create a hyperlink item for ex &ltg;a href="#">click here&ltg;a>
2.select the hyperlink item and then click on Bold n Italics button
3.try to select the bold n Italics button again
5.

Expected result:It should remove the formatting

Actual result:But on clicking second time the formatting is not removed.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6650](http://archive.tinymce.com/develop/bugtracker_view.php?id=6650) posted by [johnsmith](http://archive.tinymce.com/profile.php?name=johnsmith)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
