### ISSUE TITLE
Selected text mark with Headline Tag not work correct

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1418]
Description of problem:
If you select only 1 Word ("TinyMCE") in my Example and try to Format this with Format -> Formats -> Header -> H1-H7 always the hole text block will be set as Header (&ltg;h1>) not only the one word selected...this is really confusing.

Steps to reproduce:
1. Select 1 word in text
2. Format as Header 1
3.
4.
5.

Expected result: 
The 1 Word as Header 1 &ltg;h1>Word&ltg;/h1>

Actual result:
The hole text to next &ltg;p> tag is set as Header 1

Maybe its not a bug, its a future...i know some others Editor working also that way...

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6651](http://archive.tinymce.com/develop/bugtracker_view.php?id=6651) posted by [des_treichelt](http://archive.tinymce.com/profile.php?name=des_treichelt)_
> 
> _**Tags:** [firefox msie safari chrome opera headline selected text header]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/GNdaab_

**Comment by blackcathikari** [comment]
I believe this is a duplicate of #1088. Could you please have a look and check if it is? Thanks,
Millie @ TinyMCE

**Comment by fyrkant** [comment]
Closing this, look at issue linked above instead.
