### ISSUE TITLE
Don't use screenX and screenY

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1420]
Description of problem:
Zoomed in IE will not give css pixels when using screenX and screenY.

Steps to reproduce:
1. Open up IE and zoom in (when Windows DPI is changed, IE automatically zooms in)
2. Insert an image or any resizable element into tinymce
3. Try to resize the element

Steps to reproduce 2:
1. Open up IE and zoom in (when Windows DPI is changed, IE automatically zooms in)
2. Resize tinymce editor using the bottom right resizer.

Expected result:
The resize follows the mouse.

Actual result:
The resize will slide under the mouse.

To fix this, change every screenX and screenY to clientX and clientY. Using screenX and screenY will give you physical pixels instead of css pixels when zoomed in, while clientX and clientY will use css pixels. The actual screen position is not important, as only the relative change will be grabbed out of the dragStart and dragging events.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6653](http://archive.tinymce.com/develop/bugtracker_view.php?id=6653) posted by [Zenorbi](http://archive.tinymce.com/profile.php?name=Zenorbi)_

> _**Tags:** [msie msie7 msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
