### ISSUE TITLE
convert multilevel bullets list from word

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1422]
Description of problem:
When I copy multilevel bullets list created in word to tinymce (4.0.12), list is rendered incorrectly. In tinymce 3.5 and 4.0.6 it is good.

Steps to reproduce:
1. create multilevel bullets list in word
2. copy list to clipboard
3. paste list to tinymce as html

Expected result:
fair processing

Actual result:
wrong processing

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6657](http://archive.tinymce.com/develop/bugtracker_view.php?id=6657) posted by [QdaveQ](http://archive.tinymce.com/profile.php?name=QdaveQ)_
> 
> _**Tags:** [firefox safari chrome opera paste list bullets]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
We've looked into this and believe it is related to a few other bug reports regarding pasting lists from Word. The related reports are #2853, #3061, #1314, #1422, #1489, #1696 and #1708, and cover indentation, list styling and list item order not being preserved. Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
