### ISSUE TITLE
The toolbar icons that does not show up on Internet explorer.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1424]
Description of problem:
The toolbar icons that show up in Google Chrome does not show up on Internet explorer.

Steps to reproduce:
1. Please see http://derzane.com/tinyMCEToolBarIEBugRepro.php

Expected result:
Icons shows up

Actual result:
Icons dont show up
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6659](http://archive.tinymce.com/develop/bugtracker_view.php?id=6659) posted by [mertdeg](http://archive.tinymce.com/profile.php?name=mertdeg)_

> _**Tags:** [msie msie7 msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://derzane.com/tinyMCEToolBarIEBugRepro.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
