### ISSUE TITLE
selection.getContent doesnt work in tinymce

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1426]
Description of problem:

Steps to reproduce:
1. While selecting text from the start of paragraph to the end, selection.getContent() function cant get the problem.
2. see the example on the link given.

Expected result: It should get the content in any case.

Actual result:
http://stackoverflow.com/a/21330124/2165415
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6661](http://archive.tinymce.com/develop/bugtracker_view.php?id=6661) posted by [tazosmr](http://archive.tinymce.com/profile.php?name=tazosmr)_

> _**Tags:** [opera opera10 selection getcontent]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://stackoverflow.com/a/21330124/2165415_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
