### ISSUE TITLE
Cannot select text inside floated container with IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1427]
The content being edited includes some containers with content that are positioned (floated) using a class name style sheet rules.  With Firefox, Chrome, Opera and Safari I have no problems selecting the text and editing.  However on IE10 (and the Browser Modes for IE789) You simply cannot select any content inside these DIVs.

Steps to reproduce:
1. Go to the fiddle page
2. Scroll down to the content with the title "WHAT TO DO THIS SEASON"
3. Try to edit any text under there 

Expected result:
Should be able to click on text such as the link "Foundry Tours" to change

Actual result:
On IE it keeps selecting the outer container boxes. It is impossible to edit the text without going to the source code

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6701](http://archive.tinymce.com/develop/bugtracker_view.php?id=6701) posted by [fredsusedwebsites](http://archive.tinymce.com/profile.php?name=fredsusedwebsites)_

> _**Tags:** [msie msie7 msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/5Rdaab/5_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
