### ISSUE TITLE
Blockquote vs. BR vs. Enter issue

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1431]
Steps to reproduce:
1. Go to http://fiddle.tinymce.com/kieaab
2. Put cursor after "line1", press Enter and write "test". Created source will be
   &ltg;div>
   &ltg;blockquote>line1&ltg;/blockquote>
   &ltg;blockquote>test&ltg;br />line2&ltg;/blockquote>
   &ltg;/div>
3. Disable blockquote (on the line with "test") using menu Format > Formats > Blocks > Blockquote.

Effect is:
    &ltg;div>
    &ltg;blockquote>line1&ltg;/blockquote>
    test&ltg;br />line2&ltg;/div>

While my intention was to end up with:
    &ltg;div>
    &ltg;blockquote>line1&ltg;/blockquote>
    test
    &ltg;blockquote>line2&ltg;/blockquote>
    &ltg;/div>

It looks like the problem is somewhere in step 2.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6959](http://archive.tinymce.com/develop/bugtracker_view.php?id=6959) posted by [alec](http://archive.tinymce.com/profile.php?name=alec)_

> _**Tags:** [blockquote]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
