### ISSUE TITLE
copy table from word,and paste into tinymce,some cells lost

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1432]
Description of problem:

Steps to reproduce:
1.create a table in a word, and last cell of a row is blank 
2.copy this table to tinymce
3.the blank cell lost
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6666](http://archive.tinymce.com/develop/bugtracker_view.php?id=6666) posted by [jacky](http://archive.tinymce.com/profile.php?name=jacky)_

> _**Tags:** [msie chrome paste table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
