### ISSUE TITLE
Weird behavior when pressing backspace on a text after a noneditable content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1433]
Steps to reproduce:
1.type some text
2.insert a noneditable content by clicking on NumPage button
3.type some other text
4.press backspace

Expected result:
the last character you typed should be removed from the editor

Actual result:
the noneditable content was removed from the editor
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6667](http://archive.tinymce.com/develop/bugtracker_view.php?id=6667) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_

> _**Tags:** [firefox msie safari chrome opera noneditableedit]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/UOdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
