### ISSUE TITLE
v4.0.12: language overrules language_url

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1434]
why does the language property overrule the language_url property?
It's pretty hard to handle common init files for both CDN and Server version.
Why not introduce a language_pool /language_dir property?
regards
manu

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6670](http://archive.tinymce.com/develop/bugtracker_view.php?id=6670) posted by [manu37](http://archive.tinymce.com/profile.php?name=manu37)_
> 
> _**Tags:** [localization]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
