### ISSUE TITLE
Internet explorer zoom breaks alert and confirm messages

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1435]
Description of problem:

Steps to reproduce:
1. tinyMCE.activeEditor.windowManager.alert("Title is a required field."); without zoom. view set at 100% message is correct
2. tinyMCE.activeEditor.windowManager.alert("Title is a required field.") with IE zoom 90% message fails and displays scrollbars
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6671](http://archive.tinymce.com/develop/bugtracker_view.php?id=6671) posted by [dsjacobs](http://archive.tinymce.com/profile.php?name=dsjacobs)_

> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
