### ISSUE TITLE
Clear formatting doesn't remove the applied format from the childNodes of the selected node

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1442]
Description of problem:
The remove formatting command must remove any style from the selected node and its children but that is not the case

Steps to reproduce:
1. write a text (123456789)
2. select the first two or three characters
3. Apply bold on the selection
4. Now move the cursor before the last character
5. Click on clear formatting  button

Expected result:
Normally, I've to get this: &ltg;p> 123456789&ltg;/p> because the selected node was the p node

Actual result:
Nothing happen and the output HTML is &ltg;p>&ltg;strong>12&ltg;/strong>3456789&ltg;/p>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6681](http://archive.tinymce.com/develop/bugtracker_view.php?id=6681) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_

> _**Tags:** [firefox msie safari chrome opera removeformat]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by tinymce16** [comment]
Hi, I am finding inconsistent behavior with the clear formatting button.

Steps to Reproduce:
1. Insert text:testing testing
2. Format the text using multiple formats: Bold, italics, subscript, strikethrough etc. used over different parts of the text
3. Select a segment of the text overlapping different formats, including subscript on one part
4. Hit Clear formatting

The behavior for this is inconsistent and requires different variations of formatting, the same steps and formats were not returning consistent results.  Once the clear formatting was used, not all of the formats were cleared.  

The attached image is of a segment of text that clear formatting had been chosen, and this shows the formatting that was not cleared.

![image](https://cloud.githubusercontent.com/assets/18122020/14083478/87e3503c-f4db-11e5-993e-b301eb7b1778.png)

Expected Result: All formatting would be cleared
Actual Result: Formatting was cleared on one segment and not the entire highlighted piece

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
