### ISSUE TITLE
Javascript error unsyncs display and html content in 5.3.x

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1446]
Description of problem:

Steps to reproduce:
1. Have a 3.5.x version TinyMCE editor
2. Open HTML source editor
3. replace html with "&ltg;p>&ltg;span style="font-size: small;">&ltg;strong>Prompt:&ltg;/strong>&nbsp;value&ltg;/span>&ltg;/p>"
4. Close HTML source editor with Update Button
5. Highlight "Prompt: value", copy
6. Move cursor before "Prompt", paste. This will paste the text before, but inside the &ltg;strong> tag so the entire thing is bold
7. Highlight "value" which is bold and we don't want it to be, click the bold button to unbold it.
Javascript error is thrown "Uncaught NotFoundError: An attempt was made to reference a Node in a context where it does not exist."
The value now appears as unbold, but is gone from the html source.

Expected result:
value to appear as unbold and remain in html source

Actual result:
value appears as unbold but is gone in the html source

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6689](http://archive.tinymce.com/develop/bugtracker_view.php?id=6689) posted by [kyle.davis](http://archive.tinymce.com/profile.php?name=kyle.davis)_

> _**Tags:** [3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/3_x/full.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
