### ISSUE TITLE
Insert row after a cell with links, creates row with empty link

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1449]
Description of problem:
In 3.x version there is a problem when inserting new row after a row containing links. An empty link is inserted into newly created row

Steps to reproduce:
1. Create a table
2. Fill cells with links
3. Put cursor into one cell (the one with link)
4. Click on the button "Insert Row After"

Expected result:
There should be created an empty row with cells (eg. &ltg;tr>&ltg;td>&ltg;/td>...)

Actual result:
An empty "a" tag is copied from cell above.
New row looks like &ltg;tr>&ltg;td>&ltg;a href="...">&ltg;/a>&ltg;/td>&ltg;/tr>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6692](http://archive.tinymce.com/develop/bugtracker_view.php?id=6692) posted by [Snake.AAS](http://archive.tinymce.com/profile.php?name=Snake.AAS)_

> _**Tags:** [firefox msie 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
