### ISSUE TITLE
The rectangle (and dot-marks) around selected <div> is visible thru menu drop-down list.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1450]
Description of problem:
  The rectangle (and dot-marks) around selected &ltg;div> is visible thru menu drop-down list.

Steps to reproduce:
1.Use http://www.tinymce.com/tryit/basic.php
2.Menu: Tools:  &ltg;>Source code
3.Add at the beginning something like
&ltg;div style="width:200px; height:50px; background-color:#ff0;">AAAAA&ltg;/div>
4.Click onto this div twice (the small rectangle marks appeared, and on second click - the border /////////).
5.Click on "Insert" menu position. 

Expected result:
  The rectangle (and dot-marks) around selected &ltg;div> is covered by menu drop-down list and is invisible thru it. 

Actual result:
  The rectangle (and dot-marks) around selected &ltg;div> is visible thru menu drop-down list.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6693](http://archive.tinymce.com/develop/bugtracker_view.php?id=6693) posted by [SB](http://archive.tinymce.com/profile.php?name=SB)_
> 
> _**Tags:** [msie msie10 div menu zorder]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
