### ISSUE TITLE
Formatting before cursor gets removed when toggled off for continued content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1451]
Description of problem:
When you have the cursor at the end of formatted content and you try to remove the formatting for content you intend to add after the cursor, it will remove the formatting for the content before the cursor as well. 

Steps to reproduce:
1. Type any content (such as "this is a test")
2. Select all content and apply at least 2 of either bold, underline, or italic (such as bold and italic)
3. Move cursor to the end of the content such that there's nothing selected but the previously applied formats show as on
4. Toggle the formats that are on to off

Expected result:
Content before the cursor still has previously applied formatting.

Actual result:
Word right before the cursor has one of the formatting options (the 2nd one toggled off) removed.

Note that it doesn't matter what order you undo the formatting or which one of the 3 formatting options you toggle second, or whether 2 or 3 formatting options are on. 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6695](http://archive.tinymce.com/develop/bugtracker_view.php?id=6695) posted by [monkeydiane](http://archive.tinymce.com/profile.php?name=monkeydiane)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/gRdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
