### ISSUE TITLE
Font size gets smaller on bullet list

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1452]
Font size of text gets smaller when changed to bullet list

Steps to reproduce:
1. Type or paste a line of copy in the editor
2. Place cursor any place in the line of copy and hit the bullet list button

The bullet appears as normal but the text reduces in size.

This is similar to the paragraph issue you had in Chrome. This is on version 3.5.10

You can get a round it but creating the bullet first and then pasting or typing the copy in after.

This only happens on Chrome. I am using version 32.0.1700.107.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6723](http://archive.tinymce.com/develop/bugtracker_view.php?id=6723) posted by [daveprice](http://archive.tinymce.com/profile.php?name=daveprice)_

> _**Tags:** [chrome chrome10 chrome11 chrome13 bulletlist chrome 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
