### ISSUE TITLE
TabPanel and ActiveTab

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1454]
The problem with using activetab, blocks with the content in the first tab have height of 0px
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6697](http://archive.tinymce.com/develop/bugtracker_view.php?id=6697) posted by [wyster](http://archive.tinymce.com/profile.php?name=wyster)_

> _**Tags:** [firefox msie safari chrome opera tabpanel]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/nRdaab/6_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
