### ISSUE TITLE
Can't drag and drop text in Safari

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1455]
Description of problem:

Can't drag and drop text in Safari, specifically version 6.1.1.

Steps to reproduce:
1. Select a bit of text.
2. Drag it somewhere else.
3. Dropping it in the intended area doesn't work, and the cursor doesn't move either.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6698](http://archive.tinymce.com/develop/bugtracker_view.php?id=6698) posted by [avryl](http://archive.tinymce.com/profile.php?name=avryl)_

> _**Tags:** [safari safari6]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
