### ISSUE TITLE
EndContainer for Range object in FF not correct for TMCE 4.x

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1456]
Description of problem: FF for TMCE 4.x return EndContainer for Range object as span instead of TextNode 

Steps to reproduce:
1. Open fiddle link: http://fiddle.tinymce.com/zRdaab
2. Open browser console
3. Select last two symbols of any row (for example aa in row aaaa)
4. Click on button Show range
5. Look at console for results

Expected result: Start container and end container needs to be  TextNode

Actual result: Start container is TextNode, end container is span

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6699](http://archive.tinymce.com/develop/bugtracker_view.php?id=6699) posted by [mmu](http://archive.tinymce.com/profile.php?name=mmu)_
> 
> _**Tags:** [firefox firefox5 firefox6 firefox7 firefox8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/zRdaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
