### ISSUE TITLE
right click on image doesn't select it

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1458]
Description of problem:
When you right click on an image item, doesn't select the image
eg. 
Try to link an image, first, you should left click, and then right click to an image. If you don't left click, the link inserted the current cursor state.

Steps to reproduce:
1. Right click on the image
2. No selection!

Expected result:
1. Right click on the image
2. Selection!

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6702](http://archive.tinymce.com/develop/bugtracker_view.php?id=6702) posted by [trau](http://archive.tinymce.com/profile.php?name=trau)_

> _**Tags:** [firefox msie safari chrome opera image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
