### ISSUE TITLE
Apply a format to a node with the first child already styled with the selected format

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1459]
Description of problem:
There is a bug in match function in formatter.js 

			// Check start node if it's different
			startNode = selection.getStart();
			if (startNode != node) {
				if (matchParents(startNode)) {
					return TRUE;
				}
			}
Steps to reproduce:
1. type 123456789
2. select 12 and apply bold
3. we'll have &ltg;p>&ltg;strong>12&ltg;/strong>3456789&ltg;/p>
4. select all the text
5. apply bold

Expected result:

&ltg;p>&ltg;strong>123456789&ltg;/strong>&ltg;/p>

Actual result:
&ltg;p>123456789&ltg;/p>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6703](http://archive.tinymce.com/develop/bugtracker_view.php?id=6703) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_

> _**Tags:** [firefox msie safari chrome opera apply formatter]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
