### ISSUE TITLE
empty paragraphs get added when saving in inline mode

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1460]
Description of problem:
when saving the editor content in inline mode, empty paragraphs get added, creating additional line breaks.
occurs randomly, hard to reproduce, observed in firefox and opera.

Steps to reproduce:
1. click the save button in inline editor with the following content:
&ltg;p>text&ltg;/p>
 &ltg;p>&nbsp;&ltg;/p>
&ltg;p>text&ltg;/p>
 &ltg;p>&nbsp;&ltg;/p>
&ltg;p>text&ltg;/p>

Expected result:
content stays the same

Actual result:
empty paragraphs get added:
&ltg;p>text&ltg;/p>
 &ltg;p>&nbsp;&ltg;/p>
 &ltg;p>&nbsp;&ltg;/p>
 &ltg;p>&nbsp;&ltg;/p>
&ltg;p>text&ltg;/p>
 &ltg;p>&nbsp;&ltg;/p>
 &ltg;p>&nbsp;&ltg;/p>
 &ltg;p>&nbsp;&ltg;/p>
&ltg;p>text&ltg;/p>

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6704](http://archive.tinymce.com/develop/bugtracker_view.php?id=6704) posted by [totaleasy](http://archive.tinymce.com/profile.php?name=totaleasy)_

> _**Tags:** [firefox opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
