### ISSUE TITLE
watchlist - newsletter

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1464]
It looks like I don't get any notification on new tinymce releases.

On renew newsletter request I get this:

Newsletter

```
Share
Print
```

There was an error with your subscription, please try again or contact site administrators!

regards
manu

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6732](http://archive.tinymce.com/develop/bugtracker_view.php?id=6732) posted by [manu37](http://archive.tinymce.com/profile.php?name=manu37)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
