### ISSUE TITLE
Text disappears after paste IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1466]
Description of problem:
I have problem with pasted text. In some enviroments, after paste text disappears.
I found that when I remove 'setTimout' functions in paste plugin everything works great.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6707](http://archive.tinymce.com/develop/bugtracker_view.php?id=6707) posted by [l.swiszcz](http://archive.tinymce.com/profile.php?name=l.swiszcz)_

> _**Tags:** [msie msie10 paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
