### ISSUE TITLE
Lastfocusbookmark undefined

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1467]
Description of problem:

In minified version of tinyMce, on IE I have exception
Unable to get value of the property object is null or undefined

in line "e.DOM.bind(document,"focusin",function(e){var t=r.activeEditor;t&&e.target.ownerDocument==document&&(t.selection.lastFocusBookmark=o(t.lastRng),s(e.target)"

but in dev version everything works fine
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6708](http://archive.tinymce.com/develop/bugtracker_view.php?id=6708) posted by [l.swiszcz](http://archive.tinymce.com/profile.php?name=l.swiszcz)_

> _**Tags:** [msie msie10 exception null undefined]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
