### ISSUE TITLE
tabfocus should follow tabindex

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1469]
Description of problem:

Steps to reproduce:
1. goto http://fiddle.tinymce.com/51daab and press tab-key.

Expected result:
focus order should follow tabindex attributes.

Actual result:
tabindex is ignored.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6711](http://archive.tinymce.com/develop/bugtracker_view.php?id=6711) posted by [andrejlnnk](http://archive.tinymce.com/profile.php?name=andrejlnnk)_
> 
> _**Tags:** [firefox msie safari chrome opera tab tabfocus]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/51daab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
