### ISSUE TITLE
Problem with resize image 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1471]
Description of problem: FIRST PROBLEM : After add image to content  I have problem with resize because control rectangle is not visible. After refresh or few double click on image rectangle  sometimes are visible. AND SECOND PROBLEM:  When i click on rectangle body to resize image (drag) I can't drop rectangle and image is like glued  to my cursor. To fix i have to refresh page or save form but after save form is THIRD PRBLEM: in my  HTML code my image  (img tag) is cloned and i see two  image and i cant remove second.

a problem with the browser:  Firefox v27,  Chrome v32.0.1700.107
In Opera v12.16 everything i  OK but I need Firefox. 

I use: Tiny MCE 4.0.16   and i have in init script {object_resizing : true} property. 
   

Steps to reproduce:
1. press "add image" icon
2. select file from prepare list of image {image_list: ...} 
3. click confirm modal window "add image"
4. clik on image body 
5. try resize image

Expected result:
  1. after first click image body control rectangle should be visible  
  2. after drag and drop control restangle image should change size (like in oldest version )

Actual result:
1. I have problem with show  control rectangle (I must click many time on image or refresh page)
2. I can't finish resizing image because clicked control rectangle is glued to cursor.  

PS: sorry for my English.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6713](http://archive.tinymce.com/develop/bugtracker_view.php?id=6713) posted by [webimpuls](http://archive.tinymce.com/profile.php?name=webimpuls)_

> _**Tags:** [firefox chrome problem resize image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by mahesh-kulkarni** [comment]
I have the same problem, I am not able to resize image, rectangular box is not visible and images is not selectable.
