### ISSUE TITLE
relative_urls not working as expected

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1476]
Description of problem:

"relative_url: false" not applicable to links without "http://".

Steps to reproduce:
1.Click Insert/Edit link
2.Enter a link without the http:// prefix (e.g. SiteC.domain.com)
3.The link is saved as http://siteA.domain.com/sitec.domain.com.

Expected result: http://siteC.domain.com (or just siteC.domain.com)

Actual result: http://siteA.domain.com/sitec.domain.com

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6741](http://archive.tinymce.com/develop/bugtracker_view.php?id=6741) posted by [dmdj](http://archive.tinymce.com/profile.php?name=dmdj)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
