### ISSUE TITLE
No nonbreaking space with Firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1477]
Using nonbreaking space while writing text don't work correctly. There is only a normal space inserted.
Only if you insert the nonbreaking space subsequently, it works correctly.
It is an old problem in all Firefox versions (There are no such problems with Chrome or IE) 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6742](http://archive.tinymce.com/develop/bugtracker_view.php?id=6742) posted by [andreas_lippold](http://archive.tinymce.com/profile.php?name=andreas_lippold)_
> 
> _**Tags:** [firefox nbsp]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
