### ISSUE TITLE
Font style does not persist when typed after selecting the word

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1479]
Description of problem:
In TinyMCE 4.x, Font style does not persist when typed after selecting the word.  Repros on example  http://www.tinymce.com/tryit/classic.php

Steps to reproduce:
1. Start with empty editor, select font format (i.e. "Impact") and type a word
2. Use the mouse and drag over work to select it all
3. Start typing new characters
4.
5.

Expected result:
New character should be in selected font format "Impact"

Actual result:
Font format reverts to default font style.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6718](http://archive.tinymce.com/develop/bugtracker_view.php?id=6718) posted by [drew](http://archive.tinymce.com/profile.php?name=drew)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
