### ISSUE TITLE
CSS not bundled (using jake)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1481]
Running "jake minify bundle[themes:_,plugins:_]" does not bundle plugins/visualblocks/css/visualblocks.css, so this CSS file needs also to be deployed in additon to tinymce.full.min.js.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6720](http://archive.tinymce.com/develop/bugtracker_view.php?id=6720) posted by [Endif](http://archive.tinymce.com/profile.php?name=Endif)_
> 
> _**Tags:** [deployment build]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
