### ISSUE TITLE
Table default width in 4.x

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1482]
Description of problem:
In version 3.x I was able to set the default width as seen in
version http://stackoverflow.com/questions/13669114/set-initial-table-width-in-tinymce

How can I do it in 4.x?

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6721](http://archive.tinymce.com/develop/bugtracker_view.php?id=6721) posted by [acampana](http://archive.tinymce.com/profile.php?name=acampana)_

> _**Tags:** [firefox msie safari chrome opera table width]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
