### ISSUE TITLE
Add custom styles without replacing default style options in styleselect button/formats menu

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1485]
Currently if you set a list of custom styles in the style_formats menu, it replaces the items that appear in both the formats menu option and the styleselect button with the custom styles, instead of adding a new section for custom styles and maintaining the existing styles selection list. I can work around this problem by making my own copy of everything that appears in the standard style_formats list and adding my own options to it, but it would be nice if there was a way to have the custom styles be added onto the existing defaults without replacing them (perhaps there is one I'm not aware of).

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6727](http://archive.tinymce.com/develop/bugtracker_view.php?id=6727) posted by [cdaveb](http://archive.tinymce.com/profile.php?name=cdaveb)_
> 
> _**Tags:** [styles formats]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
