### ISSUE TITLE
Spell checker does not work in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1488]
Description of problem: The spell checker button is not visible in IE. It is visible in Firefox, chrome and Safari.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6733](http://archive.tinymce.com/develop/bugtracker_view.php?id=6733) posted by [eswar](http://archive.tinymce.com/profile.php?name=eswar)_
> 
> _**Tags:** [msie spell checker not visible in ie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
