### ISSUE TITLE
Pasting from MS Word: Ordered List restarts and turns letters into numbers

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1489]
Description of problem:

When you copy and paste an ordered nested list from Microsoft Word, the last item restart the numbering at 1, the nested list numbered as a,b,... turns into 1,2,...

Steps to reproduce:
1. Open the Word document at https://dl.dropboxusercontent.com/u/11887629/Ordered%20List%20TinyMCE.docx
2. Copy the ordered list in there.
3. Paste it in the editor at http://www.tinymce.com/tryit/full.php
   4a. Check the nested list against that in the Word document
   4b. Check the numbering of the last item in the list against that in the Word document

Expected result:
- The nested lists keep a, b ...
- The last item is numbered as 3

Actual result:
- The nested result changes to 1, 2 ...
- The last item restart the numbering at 1

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6734](http://archive.tinymce.com/develop/bugtracker_view.php?id=6734) posted by [wysocki](http://archive.tinymce.com/profile.php?name=wysocki)_
> 
> _**Tags:** [firefox msie chrome word paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** https://dl.dropboxusercontent.com/u/11887629/Ordered%20List%20TinyMCE.docx_

**Comment by blackcathikari** [comment]
We've looked into this and believe it is related to a few other bug reports regarding pasting lists from Word. The related reports are #2853, #3061, #1314, #1422, #1489, #1696 and #1708, and cover indentation, list styling and list item order not being preserved. Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
