### ISSUE TITLE
Pasting from MS Word: The content of table cells gets deleted if they contain one word followed by a period

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1490]
Description of problem:

When you copy and paste a table with content in cells from Microsoft Word, their content gets deleted they contain one word followed by a period

Steps to reproduce:

1. Open the Word document at https://dl.dropboxusercontent.com/u/11887629/Table%20TinyMCE.docx
2. Copy the table in there.
3. Paste it in the editor at http://www.tinymce.com/tryit/full.php
4. Check the content of the cells in Column 1 against that in the Word document

Expected result:

* The content is kept

Actual result:

* The content is deleted

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6735](http://archive.tinymce.com/develop/bugtracker_view.php?id=6735) posted by [wysocki](http://archive.tinymce.com/profile.php?name=wysocki)_

> _**Tags:** [firefox msie chrome word paste table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** https://dl.dropboxusercontent.com/u/11887629/Table%20TinyMCE.docx_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
