### ISSUE TITLE
paste_word_valid_elements Strips "strong" tags unless "b" is marked valid

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1491]
Description of problem: Using paste_word_valid_elements: "strong" will strip all STRONG tags from the pasted content, but "strong,b" will leave them intact. 

Steps to reproduce:
1. Init with paste_word_valid_elements: "strong"
2. Paste something bold

Expected result: Bold font style (wrapped in P > STRONG tags)

Actual result: Normal font style (usually in a P tag)

Notes: I can't reproduce this easily in a Fiddle because I'm not using actual Word, so I have to force Word detection on my local copy. 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6736](http://archive.tinymce.com/develop/bugtracker_view.php?id=6736) posted by [ahamilton9](http://archive.tinymce.com/profile.php?name=ahamilton9)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
