### ISSUE TITLE
url my be entered without http://

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1495]
Description of problem:

Steps to reproduce:
Enter an url without http:// in the link popup

Expected result:
The message 
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?"
should display to let user decide.

Actual result:
No message. The url is entered without http://

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6754](http://archive.tinymce.com/develop/bugtracker_view.php?id=6754) posted by [infograf768](http://archive.tinymce.com/profile.php?name=infograf768)_
> 
> _**Tags:** [firefox msie safari chrome opera link]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
