### ISSUE TITLE
Use "forced_root_block: false" resulting in IE8 hangup on 3.5.10

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1496]
Description of problem:

  Use Tinymce3.5.10 and set forced_root_block: false, IE8 with Windows7 or Windows2008 will hangup when insert links into editor use advlink plugin. 

 
Steps to reproduce:
1. set forced_root_block: false in tinyMCE.init
2. open IE8 on WIndows7 or Windows2008
3. input some words and select it to insert a link, say a.html
4. and input some other words and select it to insert another link like b.html. When push 
   [Insert] button, the IE hanguped. 

 It seems the links not in a block element this will happen.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6743](http://archive.tinymce.com/develop/bugtracker_view.php?id=6743) posted by [wce01](http://archive.tinymce.com/profile.php?name=wce01)_

> _**Tags:** [msie msie8 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
