### ISSUE TITLE
Cursor disappears after dragging image to inline editing area in FireFox Mac

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1497]
Description of problem:

Steps to reproduce:
1. Use FireFox Mac
2. Open link http://fiddle.tinymce.com/qUdaab/2
3. Drag image at bottom of page to inline editing area

Expected result:

Cursor is visible after image placed into editing area.

Actual result:

Cursor has disappeared.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6744](http://archive.tinymce.com/develop/bugtracker_view.php?id=6744) posted by [webtoad](http://archive.tinymce.com/profile.php?name=webtoad)_

> _**Tags:** [firefox cursor inline firefox drag]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/qUdaab/2_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
