### ISSUE TITLE
Spellchecker not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1498]
Description of problem:

Steps to reproduce:
1.Write anything into the editor
2. Click on Spell Check
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6745](http://archive.tinymce.com/develop/bugtracker_view.php?id=6745) posted by [wrkhan](http://archive.tinymce.com/profile.php?name=wrkhan)_
> 
> _**Tags:** [spellchecker spell check php]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
