### ISSUE TITLE
Cursor does not resize to match a smaller selected font after a large one has been selected.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1500]
Description of problem:

Steps to reproduce:
1.Start a new post in chrome
2.Select Font size of 36pt  
3.Type text
4.Select Font size of 8 point  
5.Type Text

Expected result:
When you select the smaller font size, cursor would resize to match the selected font size.

Actual result:
Cursor stays 36pt as you type

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6746](http://archive.tinymce.com/develop/bugtracker_view.php?id=6746) posted by [bubdou](http://archive.tinymce.com/profile.php?name=bubdou)_
> 
> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
