### ISSUE TITLE
Cursor in text box

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1501]
Description of problem: This seems to be sporadic, and doesn't happen all of the time... When the text editor box has no text in and is empty, you sometimes have to click in the very top section of the text box for the cursor to start flashing ready to type text. If you click at the bottom, it doesn't do anything. Like I say, this doesn't happen all the time. It happened yesterday, it doesn't happen today.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6747](http://archive.tinymce.com/develop/bugtracker_view.php?id=6747) posted by [Paul_ES](http://archive.tinymce.com/profile.php?name=Paul_ES)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
