### ISSUE TITLE
Adding bullet point then deleting

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1502]
Description of problem: This is sporadic and doesn't happen all of the time. When you create a bullet point list - say you have 5 items and you want to add an extra bullet point between points 2 and 3 - you click enter after the second bullet point and it adds the new bullet in, as it should. If you then use the backspace to delete this bullet point, and then hit the 'Delete' key on the keyboard, it doesn't delete the row below, it creates an extra space. If you keep pressing 'Delete' it keeps adding extra spaces, not deleting the spaces.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6748](http://archive.tinymce.com/develop/bugtracker_view.php?id=6748) posted by [Paul_ES](http://archive.tinymce.com/profile.php?name=Paul_ES)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
