### ISSUE TITLE
Wordcount default plugin is not counting numbers as words

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1505]
Description of problem: Wordcount plugin fail when text contains numbers 

Steps to reproduce:
1. Type any text that contains numbers
2. 
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6751](http://archive.tinymce.com/develop/bugtracker_view.php?id=6751) posted by [grrenier](http://archive.tinymce.com/profile.php?name=grrenier)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
