### ISSUE TITLE
Print button does not work on Android/IPad Tablet

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1506]
Description of problem:

Steps to reproduce:
1. Start full featured example on tinymce.com on an tablet like Android or Ipad
2. Press the Print button on the toolbar.
3. Nothing happens. Or the button should be disabled in case this feature is not working for tablet or give warning like its done for clipbpoard access, that print preview is not working
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6761](http://archive.tinymce.com/develop/bugtracker_view.php?id=6761) posted by [abaan](http://archive.tinymce.com/profile.php?name=abaan)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
