### ISSUE TITLE
Not show toolbar icon images

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1509]
Not show toolbar icon's in Firefox 27.0.1.
See attachment image.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6755](http://archive.tinymce.com/develop/bugtracker_view.php?id=6755) posted by [yones_safari](http://archive.tinymce.com/profile.php?name=yones_safari)_

> _**Tags:** [firefox firefox8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
