### ISSUE TITLE
tnymce 4.0.18 nort works in content page in asp.net..whereas older version works perfectly in content pages..

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1510]
Hello sir i have problem with new 4.0.18 version of tinymce..it does not works in content page of asp master page....older version works fine in content page.
Text area remains same dont chage in editor.
when i apply same script as mention for configuratin on official site on a simple webform of asp.net it works but not on content page

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6763](http://archive.tinymce.com/develop/bugtracker_view.php?id=6763) posted by [Tajinder](http://archive.tinymce.com/profile.php?name=Tajinder)_
> 
> _**Tags:** [firefox msie safari chrome opera masterpage problem]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
