### ISSUE TITLE
hello i have added linehight in to editor tool so when i am write something in to editor then last paragraph is not select from ctrl+a when we change line hight in to content can you help me please 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1512]
Description of problem:

Steps to reproduce:
1.write line in to editor then enter again write something and enter 
2.now change line-height from drop down and unselected all 
3.Now press CTRL + A 
4.You can see last line is not selected or highlighted 
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6764](http://archive.tinymce.com/develop/bugtracker_view.php?id=6764) posted by [Mayuraahir](http://archive.tinymce.com/profile.php?name=Mayuraahir)_
> 
> _**Tags:** [firefox msie safari chrome opera lineheight issue]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://23.91.122.215/test12/Tiny_Preview.aspx_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
