### ISSUE TITLE
noscript listed in both phrasingContent and blockElementsMap

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1513]
Description of problem: noscript elements are sometimes treated as inline elements and sometimes as block elements.

Steps to reproduce:
1. In http://fiddle.tinymce.com/jVdaab/1, note the default content has a noscript tag inline.
2. Run the fiddle
3. See "Before" and "After" in their own paragraphs
4. Go to: Tools -> Source code
5. Edit the source to: &ltg;p>Before &ltg;noscript>During&ltg;/noscript> After.&ltg;/p> (http://fiddle.tinymce.com/jVdaab/2)
6. Click OK.
7. See "BeforeAfter" with no intermediate whitespace.

Expected result:
Both tests should show "Before After" in the editor.

Actual result:
The first test shows:
"Before

After"

And the second:
"BeforeAfter"

I believe the attached diff fixes the problem. I wasn't sure what file would be the best place for some test cases.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6758](http://archive.tinymce.com/develop/bugtracker_view.php?id=6758) posted by [mdawaffe](http://archive.tinymce.com/profile.php?name=mdawaffe)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/jVdaab/1_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
