### ISSUE TITLE
Paste loses formatting and line breaks on iOS

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1515]
Description of problem: 
If you attempt to paste multiple paragraphs into TinyMCE 4.0.9 or later on a device running iOS, the formatting and breaks between paragraphs are lost. With TinyMCE versions 4.0.7 and earlier, paragraph breaks are preserved, but formatting is lost. 

This happens in both Safari and Chrome on the iPad and iPhone running iOS 7.x. The fiddle I've linked to is my configuration of TinyMCE 4.0.11, but the bug can be reproduced using the default fiddle configuration or the examples on the TinyMCE site (currently version 4.0.18). 

Choosing the "Paste as text" option (not available in my fiddle, but available on the examples on this site) preserves breaks between paragraphs.

Steps to reproduce:
1. On an iPad or iPhone, highlight and copy multiple paragraphs of text from a web page, e-mail, or app
2. Paste into TinyMCE 4.0.9 or later

Expected result:
Multiple paragraphs with formatting.

Actual result:
One long, unformatted block of text.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6767](http://archive.tinymce.com/develop/bugtracker_view.php?id=6767) posted by [sarken](http://archive.tinymce.com/profile.php?name=sarken)_

> _**Tags:** [paste 4x formatting]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/6Wdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
