### ISSUE TITLE
4.0.18 does not work at all on Fedora

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1518]
Currently running Fedora 18 with apache and Firefox.

I have downloaded the 4.0.18 full version and installed as described.

I have tried the simple example and the full example. Neither work, at all.

The text area does not display.

The link to the js file is working as I have verified this using view source and by following the link.

This is not working at all. Anyone have experience of this?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6769](http://archive.tinymce.com/develop/bugtracker_view.php?id=6769) posted by [suityou01](http://archive.tinymce.com/profile.php?name=suityou01)_
> 
> _**Tags:** [firefox msie safari chrome opera fedora apache firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
