### ISSUE TITLE
spellchecker plugin - undo after accepting suggestion

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1520]
Description of problem:
When using the spellchecker plugin and accepting suggestions no undo levels are created.

Steps to reproduce:
1. Initialise the editor with:
spellchecker_callback: function(method, words, doneCallback) {
   doneCallback({fred: ["Frederick", "Freddy"]});
},
plugins: ["spellchecker"],
2. Bring up the editor and type "fred was here"
3. Click [ABC]
4. Click the word fred (underlined in red)
5. Choose "Frederick"
6. Press [Undo]

Expected result:
Text = "fred was here"

Actual result:
Text = ""

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6762](http://archive.tinymce.com/develop/bugtracker_view.php?id=6762) posted by [saeder](http://archive.tinymce.com/profile.php?name=saeder)_
> 
> _**Tags:** [spellchecker undo]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
