### ISSUE TITLE
Vicious Paste from Word bug with Native Contextual Menu

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1522]
Description of problem:
Hello.
The known problem of "Copy-Paste from Word to TinyMCE" persists (the one including invisible Microsoft Word's tags messing around with HTML rendering in a webbrowser).

I've noticed that in the old TinyMCE 3.5 versions but also in the last 3.5.10 and in the new 4.0 which can be tested online.

If the contextual menu of TinyMCE is activated and forced (to block the "CTRL   Right click on the mouse" which allows to retreive the native menu): no pasting from here is possible -> no problem.

But if you deactivate the "contextual menu" plugin and activate the "see the source code" button in order to quickly see the HTML source, you'll be able to see the native menu while right clicking on your mouse and then, selecting the "Paste" option, it will paste your text, copied from Microsoft Word, with the messy tags, which can generate several problems. 

I think the "paste" plugin forgot to manage the pasting from the native contextual menu (because it manages very well the pastes comming from CTRL V or from the TinyMCE's buttons or forced contextual menu).

On v3, it can be tested here :
a) Without the "Paste" plugin activated: http://www.tinymce.com/tryit/3_x/custom_formats.php
b) With the "Paste" and the "Custom Menu" plugins activated: http://www.tinymce.com/tryit/3_x/full.php
For this example, you'll have to do a CTRL+Right click (keyboard and mouse) to see the native contextual menu and to be able to select the native "paste" option in it.

And here on v4 : http://www.tinymce.com/tryit/url_conversion.php

So, basically...

Steps to reproduce:
1. De-activate the "contextmenu" plugin of TinyMCE in the page which uses it
2. Activate the "paste" plugin of TinyMCE
3. Activate the "code" in the TinyMCE's theme advanced's buttons
4. Re-load your TinyMCE page.
5. Make or use (I've let an example in the attachments) a Word document (tested with Microsoft Office 2007 and above), copy all of it (CTRL+A then CTRL+C) 
6. Go on your page hosting your TinyMCE
7. Clic in the editable rich text zone (TinyMCE big text area) 
8. Clic right to open the native contextual menu of your webbrowser
9. Select the "Paste" sub-menu
10. Check the source code of what you've just pasted with the HTML "code" button in the TinyMCE UI

If you have activated the "paste" plugin, you can do the paste with CTR+ V to see that the messy tags are properly cleaned here but not when you use the native contextual menu.

Expected result:
Messy Microsoft's Word tags are cleaned as well as using the native contextual menu and its "paste" option or using the CTRL+V keyboard pasting method.

Actual result:
Messy Microsoft's Word tags are not cleaned when using the native contextual menu and its pasting option.

---
In the attachements: Lorem ipsum Word document and some screenshot of the steps and the results, for v3.5.10 and v4
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6770](http://archive.tinymce.com/develop/bugtracker_view.php?id=6770) posted by [xkliber](http://archive.tinymce.com/profile.php?name=xkliber)_

> _**Tags:** [firefox msie safari chrome opera microsoft word paste contextual menu native]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by beljand** [comment]
This is still an issue on latest 4.6.7 version.

If you paste ULR with context menu, then no URL is displayed + iz you undo at that point, you can see the URL

**Comment by blackcathikari** [comment]
@beljand Could you please create a example at [fiddle.tinymce.com](fiddle.tinymce.com) ? I can't replicate this bug. Also, what OS and browser(s) are you using?
