### ISSUE TITLE
Paste from Word not working using browser context menu in FF

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1524]
Description of problem:

Affects TinyMCE jQuery 4.0.19

When the Paste plugin is enabled, copying formatted text from Word and then pasting using FF's right-click context menu *or* FF's Edit->Paste menu causes all formatting to be lost.  The text is pasted as a giant blob in a single &ltg;p> tag.

Pasting using ctrl + v works fine.

Pasting with the paste plugin *disabled* works fine.

Only appears to affect FF. Chrome works fine with all paste methods.

Steps to reproduce:
1. Enable "paste" plugin in TinyMCE. (See fiddle for minimal case.)
2. Copy formatted text from Word.  A sample .docx is provided in this bug report.
3. Paste into TinyMCE using FF's right-click context menu or the Edit->Paste menu.

Expected result:
Text should appear formatted in TinyMCE with Word formatting cleaned up (but not removed).  This was the behavior in TinyMCE 3.x which we are switching from, and is the behavior that happens in 4.0.19 when using the ctrl + v keyboard shortcut.

Actual result:
Text loses all formatting and is pasted as a single giant blob in a &ltg;p> tag.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6772](http://archive.tinymce.com/develop/bugtracker_view.php?id=6772) posted by [acabal](http://archive.tinymce.com/profile.php?name=acabal)_

> _**Tags:** [firefox paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/TWdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
