### ISSUE TITLE
Config setting that unlinks text when it changes

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1525]
It would be nice to have a configuration switch that allows linked text to be automatically unlinked if a user edits the text.  We use the TinyMCE editor in a content management system.  What we are finding is that users will enter a URL and Tiny will "link" it after the user presses the space bar.  The user will then go back and change the text.  They think the underlining URL is changed but in reality only the label was changed.  The underlining URL is still the old one.  We would like a configuration setting that would allow us to say to Tiny, "if a user edits/changes the text of linked content then unlink the text". 

Thanks.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6773](http://archive.tinymce.com/develop/bugtracker_view.php?id=6773) posted by [lance@illinois.edu](http://archive.tinymce.com/profile.php?name=lance@illinois.edu)_
> 
> _**Tags:** [unlink]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
