### ISSUE TITLE
Cursor issues in older versions of IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1528]
Description of problem:

Steps to reproduce:
0. Open editor in IE10 or IE9.
1. Remove all content in editor.
2. Create a table.

Actual result:
Cant get cursor out of table

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6778](http://archive.tinymce.com/develop/bugtracker_view.php?id=6778) posted by [bubdou](http://archive.tinymce.com/profile.php?name=bubdou)_
> 
> _**Tags:** [msie msie9 msie10 table cursor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
