### ISSUE TITLE
: After Select-All, delete key does not delete all selected text.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1531]
Description of problem:

Steps to reproduce:
1. Open empty TinyMCE editor and focus the text area.
2. Change the style to bold
3. Type some text in the editor.
4. Select all the text using cmd+A and press delete(backward) key.
Expected result:
 It should delete all the characters.

Actual result:
Only one character is getting deleted.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6780](http://archive.tinymce.com/develop/bugtracker_view.php?id=6780) posted by [drew](http://archive.tinymce.com/profile.php?name=drew)_

> _**Tags:** [msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
