### ISSUE TITLE
setCursorLocation doesn't check node type

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1534]
setCursorLocation is trying to set range start (setStart) without checking the
type of referenced node.
1. Open code (for example) dialog. Do not click or edit anything.
2. Press "OK" button. indexSizeError is thrown

http://www.w3.org/TR/DOM-Level-2-Traversal-Range/ranges.html#Level2-Range-method-setStart

fix: 
// check node type
if (node.nodeType != 3 || node.nodeType != 4 || node.nodeType != 8 )
    offset = (node && node.childNodes) ? node.childNodes.length : 0;

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6782](http://archive.tinymce.com/develop/bugtracker_view.php?id=6782) posted by [julmis](http://archive.tinymce.com/profile.php?name=julmis)_
> 
> _**Tags:** [firefox msie safari chrome opera range setstart]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
