### ISSUE TITLE
Embed video doesn't keep size & return it to default

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1535]
Description of problem:

Today I wrote about problem in topic: 
http://www.tinymce.com/forum/viewtopic.php?id=33591

Now I was trying to test it on your site in "Try it" menu - TinyMCE 3.x (in sidebar")

The problem is the same - editor doesn't keep entered dimentions of embed video. (only help html-editing button after inserting video-link, but it's so uncomfortable in real projects)

Steps to reproduce:
1. Copy url video (for example any youtube)
2. press button to paste video code on top panel of editor
3. insert copied url
4. try to change width of frame
5. + if size set as deafult by other dimentions (not 450x320) - it doesn't keep too

Expected result: paste only url, do not touch size fields (and installed any other default dimentions)

Actual result: pasting url change frame size fields to 420x350! it's wrong

Best regards
Waiting for answer

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6783](http://archive.tinymce.com/develop/bugtracker_view.php?id=6783) posted by [Crashdiet](http://archive.tinymce.com/profile.php?name=Crashdiet)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
