### ISSUE TITLE
Bold button discards all previously applied styles to long string

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1536]
Description of problem:
Bold button discards all previously applied styles to long word/string (no spaces inside string)

Steps to reproduce:
1. Open editor instance
2. Begin typing characters
3. Click on the button Bold and continue typing characters (no spaces).
4. Click on button Italic and continue typing characters (no spaces).
5. Click on Underline button and continue typing characters (no spaces).
6. Click on Bold button again.

Actual result:
Clicking on Bold button discards all previously applied styles.

Expected result:
Previously typed characters should retain their styles.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6788](http://archive.tinymce.com/develop/bugtracker_view.php?id=6788) posted by [drew](http://archive.tinymce.com/profile.php?name=drew)_

> _**Tags:** [safari]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
