### ISSUE TITLE
Spell check is not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1542]
Description of problem:

Steps to reproduce:
1.Go the the following link:http://www.tinymce.com/tryit/classic.php
2.try to click spell check icon from the editor toolbar
3.an error appear

Expected result:
Spell check should work

Actual result:
an error appear

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6796](http://archive.tinymce.com/develop/bugtracker_view.php?id=6796) posted by [bassamAssaad](http://archive.tinymce.com/profile.php?name=bassamAssaad)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by nori-h** [comment]
We have taken a look and this issue appears to be a duplicate of #1087

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
