### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1544]
Hello,
Improve the markdown, and switch in html, in visual mode and markdwn mode...
Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6792](http://archive.tinymce.com/develop/bugtracker_view.php?id=6792) posted by [madvic](http://archive.tinymce.com/profile.php?name=madvic)_
> 
> _**Tags:** [markdown]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by on3iro** [comment]
+1

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by vanillajonathan** [comment]
Markdown support is on the roadmap.
https://www.tiny.cloud/roadmap/
