### ISSUE TITLE
Need To clean existing data from database

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1552]
Description of problem: We are using TinyMce editor whose data is getting displayed on Birt and crystal report .Due to some issue we have used paste plugin to clean HTML data while copy paste but our existing database before the issue is still showing the same data as we have not copy pasted that content .Can you suggest some way or button which when user clicks cleans the existing data as it cleans when we do copy paste

Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6811](http://archive.tinymce.com/develop/bugtracker_view.php?id=6811) posted by [AMaheshwari](http://archive.tinymce.com/profile.php?name=AMaheshwari)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
