### ISSUE TITLE
Add event when a Plugin is activated and when it closes

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1553]
For a couple of plugins (Image and CodeMirror), I need to know when the plugin is activated and when the plugin dismisses itself. In 3.x I could find out when the Image plugin closed by registering an onExecCommand listener and looking for cmd== mceInsertContent. However, plugins do not fire that event in 4.x.

This is my use case: we do special handling of external links (for instance, image links) in our application. We store them with a relative src in our database, but when the user is viewing the HTML in TinyMCE, we want to convert the src to the full path so that they don't see broken images or links. So when the user closes the image plugin after adding a new image, we want to rewrite the link. And when the user opens the CodeMirror plugin to edit the raw HTML, we want to convert back to the relative paths (and do the reverse when the CodeMirror plugin is closed).

It doesn't seem that any events are fired when a plugin is activated or closed. I have had to modify the plugin code to fire events that I can listen to.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6799](http://archive.tinymce.com/develop/bugtracker_view.php?id=6799) posted by [cahrens](http://archive.tinymce.com/profile.php?name=cahrens)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
