### ISSUE TITLE
3.5.8/IE11 : Problem with enter key after formatting the text using text highlighter feature

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1557]
Description of problem:
Currently we are facing an issue with TinyMCE 3.5.8 version with IE11 during the formatting the text in the editor.Cursor is not moving to proper position on pressing enter key after performing formatting.

Steps to reproduce:
1. Enter some text in the first line. Press Enter key.
2. Enter some text in second line.
3. Select all test of second line and highlight it with any color.
4. Press Enter key two times.

Expected result:
The cursor should come on the fourth line.

Actual result:
The cursor is not moving to fourth line, and staying at second line only and when we type any text it moves to third line.

Please note: If we perform same steps expect step 3, it is working fine.

Can you please help us to solve this here?

Please let me know for any additional information.

Thanks,
Rahul Parikh

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6802](http://archive.tinymce.com/develop/bugtracker_view.php?id=6802) posted by [rkparikh88](http://archive.tinymce.com/profile.php?name=rkparikh88)_

> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
