### ISSUE TITLE
spell check is not working with tinymce 4.0 + version

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1561]
Description of problem:

Steps to reproduce:spell check is not working with tinymce 4.0 + version
1. just use spellcheck with our cdn or downloaded version of tinymce4.0
2. spellcheck option will be there in tool menu
3. but when we click on it, alert came with no spelling mistake, when further investigate, found that there is an url need to set to run spellcheck
4. when you check spellcheck, it have only plugin.min.js
5.

Expected result: 

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6807](http://archive.tinymce.com/develop/bugtracker_view.php?id=6807) posted by [shannlove](http://archive.tinymce.com/profile.php?name=shannlove)_
> 
> _**Tags:** [firefox msie safari chrome opera spellchck with tinymce 40]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by nori-h** [comment]
We have taken a look and this issue appears to be a duplicate of #895

**Comment by nori-h** [comment]
We have taken a look and this issue appears to be a duplicate of #1087

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
