### ISSUE TITLE
line spacing

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1563]
Does TinyMCE4 have a line spacing plugin?
If not, I'd like to request it � our users consider it an important feature. 
Thanks in advance!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6813](http://archive.tinymce.com/develop/bugtracker_view.php?id=6813) posted by [Danit](http://archive.tinymce.com/profile.php?name=Danit)_
> 
> _**Tags:** [firefox msie safari chrome opera line spacing]_
> _**Status:** Deleted_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by nori-h** [comment]
We have taken a look and this issue appears to be a duplicate of #1562

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
