### ISSUE TITLE
Tabfocus does not work on firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1564]
Description of problem:
On newer versions of Firefox (tested on Firefox 27 and 28 on Win7) tabfocus plugin does not work anymore.

Steps to reproduce:
1. Go to http://www.tinymce.com/tryit/3_x/tab_focus.php
2. Click on editor to focus
3. Use tab key to try to shift focus to input 2

Expected result:
Input 2 has focus

Actual result:
Input 2 does not have focus.

On a possibly related note: If tabfocus plugin is *not* used, Firefox will correctly shift focus to next input field -- however *only* if toolbar is on top. If toolbar is positioned at the bottom of the editor (theme_advanced_toolbar_location : "bottom") then tabbing to next input element won't work.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6814](http://archive.tinymce.com/develop/bugtracker_view.php?id=6814) posted by [Krizna](http://archive.tinymce.com/profile.php?name=Krizna)_

> _**Tags:** [firefox tabfocus firefox 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/3_x/tab_focus.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
