### ISSUE TITLE
Unable to right click and edit image

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1571]
Description of problem:

Steps to reproduce in MSIE 11:
1. Float an image at the end of a p tag make sure there is text directly above the image
2. Right click on the image directly under the text from the p tag.
3. The image selects when you left click but loses the selection when you right click. Making it impossible to edit the image properties via right click.

Expected result:
The image stays selected when you right click and you can edit the image src.

Actual result:
When you right click the image deselects and the src is blank.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6824](http://archive.tinymce.com/develop/bugtracker_view.php?id=6824) posted by [byerkes](http://archive.tinymce.com/profile.php?name=byerkes)_

> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/eZdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
