### ISSUE TITLE
Safari Copy Loses Formatting

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1572]
Description of problem:

Steps to reproduce:
1. In Safari goto http://www.tinymce.com
2. In the tinymce editor copy the entire text which contain bold text and a bullet list
3. Paste text into same editor below copied text

Expected result:
The text with bold formatting and bullet list appears now twice

Actual result:
The text is not bold and the bullet points disappeared (the bullet text is still there)

If the same text is copied from Firefox on the Mac and pasted into Safari, the formatting is preserved. Also if the text is copied from Safari and pasted into Firefox, the formatting is gone.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6825](http://archive.tinymce.com/develop/bugtracker_view.php?id=6825) posted by [michaelhast](http://archive.tinymce.com/profile.php?name=michaelhast)_

> _**Tags:** [safari safari6]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
