### ISSUE TITLE
Fullscreen UI Not Painted - Java 8 JavaFx WebView

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1573]
In a JavaFX WebView component the UI does not get updated any more after switching to fullscreen using the fullscreen plugin.
That is with Java 8's JavaFx where userAgent="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.44 (KHTML, like Gecko) JavaFX/8.0 Safari/537.44"

It works just fine using Java 7's JavaFX where userAgent="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/535.14 (KHTML, like Gecko) JavaFX/2.2 Safari/535.14"

The version of TinyMCE is 4.0.20

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6823](http://archive.tinymce.com/develop/bugtracker_view.php?id=6823) posted by [saeder](http://archive.tinymce.com/profile.php?name=saeder)_
> 
> _**Tags:** [javafx webkit]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
