### ISSUE TITLE
Feature request: setup by DOM element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1574]
For newly added text areas I do:
jQuery('.text-area').addClass('setup-tinymce');
tinymce.init({
    selector: '.setup-tinymce'
});
jQuery('.text-area').removeClass('setup-tinymce');

Would be nice to be able to do:
tinymce.init({
    selector: jQuery('.text-area')[0]
});

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6826](http://archive.tinymce.com/develop/bugtracker_view.php?id=6826) posted by [Manake](http://archive.tinymce.com/profile.php?name=Manake)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I think this is possible now. Closing.
