### ISSUE TITLE
Ctr + v and right click paste is behaving diffrently in Firefox 24

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1575]
Description of problem: We have enabled paste plugin to clean the data while copy paste from word.It is cleaning the word tag while we copy paste with use of Ctr + v but if we do right click paste it is not cleaning the data.How can we handle the right click paste so that it behaves as same as Ctrl + v

Steps to reproduce:
1. Write some content on Word apply some formatting 
2. Copy paste in editor using right click .
3. HTML Data is not in getting clean.

Expected result: Clean HTML Data

Actual result: HTML data with unneccsary HTML word tags

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6827](http://archive.tinymce.com/develop/bugtracker_view.php?id=6827) posted by [AMaheshwari](http://archive.tinymce.com/profile.php?name=AMaheshwari)_
> 
> _**Tags:** [firefox firefox8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
