### ISSUE TITLE
Class in advanced tab image

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1577]
Hi,
In the tab advanced from "insert/edit image",
there is a field style,
but i want to use a class field.
"class :"
If I write for example in the style field "class="my_image_class"
then, no class is defined in the "img" tag.
I checked the source result and i've just got : 
"&ltg;" img alt="" height="562" src="http://localhost/XOOPS/uploads/filemanager/media/depot-members/Florence-Italie 163.jpg" width="1000" />

I wanted : 
"&ltg;" img alt="" height="562" src="http://localhost/XOOPS/uploads/filemanager/media/depot-members/Florence-Italie 163.jpg" width="1000" class="my_image_class" />

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6830](http://archive.tinymce.com/develop/bugtracker_view.php?id=6830) posted by [alain01](http://archive.tinymce.com/profile.php?name=alain01)_
> 
> _**Tags:** [av advanced tab iamge class]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
