### ISSUE TITLE
valid_styles doesn't work correct

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1578]
Description of problem:
width and height and maybe others will not be saved

Steps to reproduce:
1. try to edit the first cell and update

Expected result:
td style="width:100px;height:30px;text-align: right;"

Actual result:
td style="text-align: right;"
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6832](http://archive.tinymce.com/develop/bugtracker_view.php?id=6832) posted by [otter](http://archive.tinymce.com/profile.php?name=otter)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/PZdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
