### ISSUE TITLE
TinyMCE sometimes creates a UL element wrapper for a UL element.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1580]
Description of problem:

TinyMCE randomly (I have yet to find the problem) replaces some &ltg;UL>&ltg;/UL> elements with double UL's i.e. &ltg;UL>&ltg;UL>[contents]&ltg;/UL>&ltg;/UL>

Steps to reproduce:
1. I haven't found a way yet to reproduce this.
2. It does seem to happen after the first &ltg;UL>&ltg;/UL>.
3.
4.
5.

Expected result:

.. is for UL elements to not be wrapped inside another UL element.

Actual result:

&ltg;UL>&ltg;UL>&ltg;/UL>&ltg;/UL>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6833](http://archive.tinymce.com/develop/bugtracker_view.php?id=6833) posted by [Kevinn](http://archive.tinymce.com/profile.php?name=Kevinn)_

> _**Tags:** [double ul]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
