### ISSUE TITLE
Flying drop down menus

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1583]
Description of problem: On first time clicking on any of the drop down menus (File, Edit, View or Format) the related menu comes flying in from top left corner.

Steps to reproduce:
1.click on any of the drop down menus (File, Edit, View or Format)

Expected result: the menu drops down

Actual result: the menu appears in the top most left corner of the screen and flies down to where it should be. If you re-click on any of the drop downs they behave normally.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6836](http://archive.tinymce.com/develop/bugtracker_view.php?id=6836) posted by [patdes19](http://archive.tinymce.com/profile.php?name=patdes19)_
> 
> _**Tags:** [chrome flying drop down menus]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
