### ISSUE TITLE
Unable to apply format style change to Multiple Highlighted text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1586]
Description of problem:
Applying a style to multiple-highlighted text areas ONLY formats the First highlight.

Steps to reproduce:
1. Use Ctrl KEY Only, highlight TWO different, non contigous sections of the text
2. Apply A style
3. Only first area is changed, oterh one is not
4.
5.

Expected result:
BOTH to change

Actual result:
ONly first 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6839](http://archive.tinymce.com/develop/bugtracker_view.php?id=6839) posted by [shynes](http://archive.tinymce.com/profile.php?name=shynes)_

> _**Tags:** [firefox multiple select highlight formatting]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
