### ISSUE TITLE
Can't change the color or font of selected text in Adobe Air

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1587]
Description of problem:
When embedding tinymce 4 in an adobe air application, it is not possible to change the color of selected text. This is most likely due to the fact that air uses an old version of webkit.

Steps to reproduce:
1. Install and launch the attached air application (AirBrowser)
2. Enter the url of a tinymce 4 editor (exp: http://www.tinymce.com/tryit/full.php)
3. Select a word
4. Choose a font or a color in the colors drop down list

Expected result:
The selected word should be coloured with the chosen color.

Notes:
1. Simply clicking on the color control to apply the currently chosen color works fine. The problem happens when trying to apply another color from the drop down list.
2. The problem doesn't happen in tinymce 3.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6840](http://archive.tinymce.com/develop/bugtracker_view.php?id=6840) posted by [sch](http://archive.tinymce.com/profile.php?name=sch)_
> 
> _**Tags:** [air]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/full.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
