### ISSUE TITLE
Can select and move controls in nonEditable div

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1588]
Description of problem: I have a div with the class mceNonEditable so that its contents are not editable or selectable. The div's contents also contain a form. Now if I click on a label or blank space then the outer div is selected. All good so far. But in IE10 I can click on a text box, or button and move them out of the div. I don't want this. It sounds like a bug, or does nonEditable not prevent this? 

Also in Chrome if I click on the submit button in the form it actually fires of the button. Definitely don't want this as you could imagine.

The thing I am trying to do is to create a plugin that adds preset forms. These forms are handled elsewhere by the site. I want the user to see what the form looks like so they get an idea what the web page they are making looks like, but they are not to edit the form in anyway.

Steps to reproduce:
1. Create a div with class mceNonEditable (ensure you are using the nonEditable plugin)
2. Add a form to the div. I added the form using an ajax call. Have the form contain some controls, mine has a text box and a submit button.
3. In IE10 I am able to select the controls by clicking on them.
4. Now drag the control out of the div.
5.

Expected result:
I'd expect that when clicking on any of the form controls that the mceNonEditable div should be selected.

Actual result:
The control is selected and you can drag it out of the div.

For the chrome issue. Do the same again, but run it in chrome. Now click on the submit button in the form. The form is submitted.

One last thing. There is a check box on the form. If I click on the check box in ie. The div is selected. Good, but the check box is ticked. This isn't so bad, but not exactly desired. 

Thanks for your help.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6841](http://archive.tinymce.com/develop/bugtracker_view.php?id=6841) posted by [Superspazzy](http://archive.tinymce.com/profile.php?name=Superspazzy)_
> 
> _**Tags:** [msie msie10 noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
