### ISSUE TITLE
Moving a div with just text contents strips out the div

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1589]
Description of problem: I am writing a plugin that will add a snippet of html. The html is stored in a database. The html is added into a div with a class of mceNonEditable. So far this all works. The user can't edit anything in the div, which is good. They can still delete the div and move it around, all good. But if you are in IE and the div just contains some simple text, or just text in a p tag then when the div is moved the div is then stripped, this results in the text now being editable. 

Steps to reproduce:
1. Create a div with class mceNonEditable.
2. Add just some text to the div. So you should have &ltg;div class="mceNonEditable">Hello world.&ltg;/div>
3. Click on the div (in ie) The whole div is selected and you can not edit the text. Good.
4. Now drag the div to somewhere else.
5. It looks fine, but you will notice the div is gone, the text is there, but no div, so now you can edit the text.

Expected result:
The div should still be there, and the text not editable.

Actual result:
The div is not there and the text is editable.

I tried doing this in chrome and it works fine there. The div is not stripped so the text remains nonEditable. 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6842](http://archive.tinymce.com/develop/bugtracker_view.php?id=6842) posted by [Superspazzy](http://archive.tinymce.com/profile.php?name=Superspazzy)_

> _**Tags:** [msie msie10 noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
