### ISSUE TITLE
Dummy whitespaced generated after table without forced_root_block

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1591]
Description of problem:

When forced_root_blocks is false and the only content inside the editor is a table, a &ltg;br data-mce-bogus='1'> is always inserted, even when a &ltg;br data-mce-bogus='1'> is already inserted.

Steps to reproduce:
1. Go to http://fiddle.tinymce.com/kbeaab
2. Keep pressing the left cursor key

Expected result:

Only one dummy BR is generated so the cursor can be placed after the table.

Actual result:

Every keypress a dummy BR is generated

Proposed fix:

From line 240 in js/tinymce/plugins/table/classes/Quirks.js contains the following code:

} else if (last.nodeType == 1 && !last.getAttribute('data-mce-bogus')) {
   break;
}

The problem seems fixed when changing that to

 } else if (last.nodeType == 1) { 
    if (last.nodeName == 'BR' || !last.getAttribute('data-mce-bogus')) {
        break;
    }
 }

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6844](http://archive.tinymce.com/develop/bugtracker_view.php?id=6844) posted by [PaulB](http://archive.tinymce.com/profile.php?name=PaulB)_

> _**Tags:** [table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/kbeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
