### ISSUE TITLE
paste_webkit_styles fails on plain text with linebreak

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1593]
Only tested the webkit bug on Chrome 34.0.1847.116 m. Problem does not exist on Firefox. Sorry if this is long!

Description of problem:
--------------------------
Without the plugin, whenever Webkit feels like the pasted node's styles will overwrite a parent's styles, it will add a &ltg;span style="xxx"> inside to force inheritance. That's the notorious webkit bug right?

The Paste Plugin is great at stopping this behavior (with paste_webkit_styles: "none"), but only for the pasted paragraph. When pasting plain text with a linebreak, it triggers the bug everywhere else! No idea why it only triggers with a linebreak.

To demonstrate this issue, we need conflicting parent and child styles to trigger the bug. In the attached fiddle, as an example, I enclosed a styled &ltg;p> in a &ltg;table>, triggering inheritance from the skin's css (which has a "td, th" statement with different styles than my &ltg;p>'s).

Steps to reproduce:
--------------------------
1. Open the fiddle with disabled Paste plugin, and paste this simple example as source: http://pastebin.com/Nfk4DCms
2. Press enter at end of paragraph to produce a linebreak and new paragraph with same styles.
3. Now paste any plain text. In the source, you can see the &ltg;span> around the pasted paragraph that forces inheritance from the skin's content.min.css. Typical webkit so far =)

4. Now, with the same contents, enable the Paste plugin and set paste_webkit_styles: "none"
5. Repeat steps 2 and 3, but paste plain text that contains a linebreak.
6. The previous paragraph is now modified with an ugly span that looks like the one in step 3, except the font size was calculated differently!

Expected result:
--------------------------
No ugly spans inserted by webkit when pasting multi-line plain text, only styled &ltg;p> tags

Actual result:
--------------------------
Ugly webkit spans everywhere EXCEPT the pasted paragraphs
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6846](http://archive.tinymce.com/develop/bugtracker_view.php?id=6846) posted by [th3m1773n](http://archive.tinymce.com/profile.php?name=th3m1773n)_

> _**Tags:** [chrome paste paste_webkit_styles]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/3beaab/2_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
