### ISSUE TITLE
Fullpage templates

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1595]
I understand that the fullpage plugin does 2 things:

1) Allow the full page tags and their attributes (head, meta, title, body, html...). That means I could paste some full page html and it would be preserved. And that's awesome.
2) Implement default versions of these tags on every new page. Also good!

Now, the template plugin can only inject content, so if a template contains any of the tags in 1), they will simply be ignore.

I don't know if this is a reasonable request, but would it be possible that the template plugin could work with the fullpage plugin to actually inject head, title, body (and their attributes) from what's in the template, replacing the editor defaults?

Thanks!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6848](http://archive.tinymce.com/develop/bugtracker_view.php?id=6848) posted by [th3m1773n](http://archive.tinymce.com/profile.php?name=th3m1773n)_
> 
> _**Tags:** [template fullpage plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
