### ISSUE TITLE
Broken layout WindowManager (i.e. template plugin popup)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1597]
When description in template is too long, Tiny's layout doesn't wrap it to more than one line.
The layout is generated with lots of position:absolute.
Is it possible to use more 'natural' (not absolute positioned) popup's items?
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6850](http://archive.tinymce.com/develop/bugtracker_view.php?id=6850) posted by [mefjuu](http://archive.tinymce.com/profile.php?name=mefjuu)_

> _**Tags:** [firefox msie safari chrome opera template layout windowmanager]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
