### ISSUE TITLE
Paste From Word does not work in IE10

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1606]
Description of problem:
A few months ago we have implemented TinyMCE 4 in our CMS.
Now many clients have the problem they cannot paste from Word with markup.
CTRL+V simply pastes plain text;
The paste-from-word button asks to allow access to the clipboard, after allowing it nothing happens at all.

I tested it both in our CMS and on http://www.tinymce.com/tryit/basic.php
In both cases it doesn't work.

Since I can't find anyone else having this issue, am I missing something here, or is this an actual bug?

Steps to reproduce:
1. Open IE10 (we have also tested it via http://app.crossbrowsertesting.com/livetests, in Win7 + IE10)
2. Go to http://www.tinymce.com/tryit/basic.php
3. Paste text copied from Word 2010 by pressing CTRL+V

Expected result:
Text with certain markup like bold and italic is pasted in the editor

Actual result:
Plain text is pasted in the editor
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6860](http://archive.tinymce.com/develop/bugtracker_view.php?id=6860) posted by [zagrad](http://archive.tinymce.com/profile.php?name=zagrad)_

> _**Tags:** [msie msie10 paste word internet explorer plain]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
