### ISSUE TITLE
Selection isn't correctly saved when making links

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1607]
Description of problem: Within TinyMCE, if you have a link with padding and then try to modify the link via "Insert link"� in the context menu, it may not work in Safari and Chrome. Depending on where you right-click, different sections of the text are selected, and the "Insert link"� dialog seems to be using the selection to determine what link to modify. This causes problems for us because we have links styled with padding to look like buttons. 

Steps to reproduce:
1. Create a link within TinyMCE and add padding and a border around. An example block of code is &ltg;a style="padding: 50px; border: 1px solid green; line-height: 100px;" href="../testfiles/drive.jpg">some text&ltg;/a>
2. Right-click directly on the text of the link. A context menu displays. Select "Insert link"?. The Url displays "../testfiles/drive.jpg"�, and Text to Display displays "some text"�. This is correct.
3. Close the dialog and click elsewhere in the editor to clear the selection. Now right-click in the padding space on the right side within the link. A context menu displays. Select "Insert link"�. The Url and Text to Display are both empty.
4. Close the dialog and click elsewhere in the editor to clear the selection. Right-click in the padding space at the very top within the link. A context menu displays. Select "Insert link"�. The Url is empty, and Text to Display is either empty or actually displays the first word in the line of text ("Feel"� in my example code below).

Expected result: The same behavior in all regions of the link.

Actual result: Different elements can be selected, and have different links applied to them. All regions of the link do not remain consistent. 

I saw this behavior in Chrome 34.0.1847.116 on Mac and Safari 7.0.3 on Mac. The behavior in Firefox was as expected; this bug was not present.

Here'??s the sample HTML I experimented with at http://www.tinymce.com/tryit/full.php.

&ltg;h1>&ltg;img style="float: right;" title="TinyMCE Logo" src="img/tlogo.png" alt="TinyMCE Logo" width="92" height="80" />Welcome to the TinyMCE editor demo!&ltg;/h1>
&ltg;p>Feel free to try out the different &ltg;a style="padding: 50px; border: 1px solid green; line-height: 100px;" href="../testfiles/drive.jpg">some text&ltg;/a> that are provided, please note that the &ltg;strong>MoxieManager&ltg;/strong> specific functionality is part of our commercial offering. The demo is to show the integration.&ltg;/p>
&ltg;h2>Got questions or need help?&ltg;/h2>
&ltg;p>If you have questions or need help, feel free to visit our &ltg;a href="../forum/index.php">community forum&ltg;/a>! We also offer Enterprise &ltg;a href="../enterprise/support.php">support&ltg;/a> solutions. Also do not miss out on the &ltg;a href="../wiki.php">documentation&ltg;/a>, its a great resource wiki for understanding how TinyMCE works and integrates.&ltg;/p>

I found that the behavior for what gets selected is the same as when I double-click inside or outside the editor. (In Chrome, when you double click it highlights the word you're double-clicking.) I attached a diagram of what gets selected when. I get three different results depending on which of the three red regions I double-click in. The text outlined in blue ends up being selected when double-clicking in the corresponding (purple arrows) red region. Line-height makes a difference as to what gets selected when clicking at different positions vertically, but clicking the right padding seems to always select the text after the link.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6861](http://archive.tinymce.com/develop/bugtracker_view.php?id=6861) posted by [mkinney](http://archive.tinymce.com/profile.php?name=mkinney)_

> _**Tags:** [safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
