### ISSUE TITLE
Paste as Text keeps annoying user with warning

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1609]
When the Paste as Text button is clicked, the user is warned about being in plain text mode.  That same message keeps being displayed every time the page is loaded.  A user needs to see that message ONE time (the first time the button is clicked).  So the plugin needs to track that the user has already viewed the warning message.

Line 1191 - take out the "var userIsInformed;"

Line 1204 - change to:  if (!tinymce.util.LocalStorage.getItem('pasteastext_warned')) {

Line 1210 - change to:  tinymce.util.LocalStorage.setItem('pasteastext_warned', '1');

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6863](http://archive.tinymce.com/develop/bugtracker_view.php?id=6863) posted by [speednet](http://archive.tinymce.com/profile.php?name=speednet)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
