### ISSUE TITLE
"Edit CSS Style" styleprops button in 4.0

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1610]
The "Edit CSS Style" button that came from the styleprops plugin was the single best way of applying custom inline styling without diving into the HTML and made it so that my less-HTML-savvy clients could still manage some more complex content layouts.  It is an essential feature in my mind to the TinyMCE experience.

Please create a means for adding this back in to version 4.0.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6864](http://archive.tinymce.com/develop/bugtracker_view.php?id=6864) posted by [JboyJW](http://archive.tinymce.com/profile.php?name=JboyJW)_
> 
> _**Tags:** [css style styleprops]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/wiki.php/Plugin3x:style_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
