### ISSUE TITLE
iframe has scrollbar when height set to 99% (html5 doctype)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1612]
Tinymce version 3.4.5

Browser FF/IE

iframe height does not get set to 99% and shows a scrollbar in the middle of the editor.

Check example at http://fiddle.tinymce.com/Hceaab

Please let me know if there is a fix for this.

Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6867](http://archive.tinymce.com/develop/bugtracker_view.php?id=6867) posted by [karan](http://archive.tinymce.com/profile.php?name=karan)_

> _**Tags:** [firefox msie safari chrome opera html5]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Hceaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
