### ISSUE TITLE
Extra rowspan when merging all cells of a table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1613]
Description of problem:

Steps to reproduce:
1. Insert a table with 2 rows and 2 columns
2. Select all cells
3. Right click on one of the cells
4. In the context menu select Cell - Merge cells

Expected result:

&ltg;table>
  &ltg;tbody>
    &ltg;tr>
      &ltg;td>abcd&ltg;/td>
    &ltg;/tr>
  &ltg;/tbody>
&ltg;/table>

Actual result:

&ltg;table>
  &ltg;tbody>
    &ltg;tr>
      &ltg;td colspan="2" rowspan="2">abcd&ltg;/td>
    &ltg;/tr>
  &ltg;/tbody>
&ltg;/table>

Comments:

The size of the grid doesn't matter. Proposed patch is attached to the ticket.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6868](http://archive.tinymce.com/develop/bugtracker_view.php?id=6868) posted by [r.osmanov](http://archive.tinymce.com/profile.php?name=r.osmanov)_

> _**Tags:** [firefox msie safari chrome opera table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
