### ISSUE TITLE
Selected element should be there in alert box after editing TinyMce editor in Ipad.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1614]
Description of problem:
Device : Apple ipad 3  
IOS : v 7.0.3

We are trying to detect on click event of editor.Here when the editor is not focused - We are able to get selected element of editor (like &ltg;img/> or &ltg;a/>). But after editing the text inside editor, we are not able to get selected element. Please check below code snippet which we are using:

setup: function (ed) {
       ed.onClick.add(function (ed, e) {
          alert('Editor was clicked: ' + e.target.nodeName);
       });
}

Also please check below fiddle URL. Which we need to do in iOS
http://jsfiddle.net/xgPzS/5/

Steps to reproduce:
1. Go to - http://jsfiddle.net/xgPzS/5/
2. Now click on image or any other area inside the Editor, it will show selected element in a alert box.
3. Now edit text or type anything inside it, now it will not display alert box with selected element.

Expected result:
Selected element should be there in alert box after editing.

Actual result:
No alert box appears after editing  while clicking on selected element

Does any one have idea to re-bind on select event after editing inside editor ?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6869](http://archive.tinymce.com/develop/bugtracker_view.php?id=6869) posted by [RomaAmin](http://archive.tinymce.com/profile.php?name=RomaAmin)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/xgPzS/5/_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
