### ISSUE TITLE
Hyperlink tags could not be edited when using Java FX WebView.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1615]
When using the small snipplet of HTML code in a WebView component of Java FX inline editing works, but when clicking on the &ltg;a> tag, the referenced hyperlink is opened instead of allowing to edit the link in TinyMCE.

&ltg;!DOCTYPE html>
&ltg;html>
    &ltg;head>
        &ltg;meta charset="utf-8">
        &ltg;title>WebViewTest&ltg;/title>

        &ltg;script type="text/javascript" src="tinymce/js/tinymce/tinymce.min.js">
        &ltg;/script>

        &ltg;script type="text/javascript">
            function initEditor() {
                tinymce.init({
                    selector: "section",
                    inline: true,
                    plugins: ["link"],
                    toolbar: "link",
                });
            }
            initEditor();
        &ltg;/script>
    &ltg;/head>

    &ltg;body>      
        &ltg;section>This is some text.
            &ltg;p>
                &ltg;a href="http://en.wikipedia.org/wiki/W3C" rel="alternate" title="Link to W3C article">A link to the Wikipedia articel of W3C&ltg;/a>
            &ltg;p>Some more text.
        &ltg;/section>
    &ltg;/body>
&ltg;/html>

When the same code is loaded in Firefox, Internet Explorer or Safari everything works fine. Especially editing of the &ltg;a> is possible.

This is the used Java code:

public class WebViewTest extends Application {

    @Override
    public void start(Stage primaryStage) {
        WebView webView = new WebView();

        try {
            File f = new File("etc/tinymcetest/WebViewTest.html");
            webView.getEngine().load(f.toURI().toURL().toExternalForm());
        } catch (MalformedURLException ex) {
            System.err.println(ex.getMessage());
            return;
        }

        primaryStage.setScene(new Scene(webView, 640, 720));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}

I am using TinyMCE 4.0.22, Java JDK 8 and Windows 7.

Is this behaviour a bug in TinyMCE or a Java problem?
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6870](http://archive.tinymce.com/develop/bugtracker_view.php?id=6870) posted by [hacklaen](http://archive.tinymce.com/profile.php?name=hacklaen)_

> _**Tags:** [firefox msie safari chrome opera editing a tag]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Tceaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
