### ISSUE TITLE
Archive history release and regression testing

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1618]
I wish an URL to download previous releases of tinyMCE to audit behaviour of latest tinyMCE against past version.

Currently, I suspect that cut & paste behaviour has changed against release around 4.0.16

Thanks
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6873](http://archive.tinymce.com/develop/bugtracker_view.php?id=6873) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
