### ISSUE TITLE
Tiny_mce text box[textarea] is not loading properly or it is inconsistent.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1619]
Description of problem: The tiny_mce textbox control does not load on the first page visit in IE 8 and 10. If we refresh the page, the problem still exists. but if we keep the curson on the address bar and hit enter it loads the contyrol properly.

Steps to reproduce:
1. Delete browsing history and cache from the browser.
2. Load the sharepoint page.
3.It's not displaying for the first time and even after refreshing also its not displaying.
4.
5.

Expected result: The control should load all the time.

Actual result:
The control is not loading for the first time the page loads, also even after refreshing the page multiple times its not loading. But its loading with hitting enter on address bar/ reloading.

Code: .ascx where the textbox control is being called.
&ltg;div id="dvtxt1"> 
                                            &ltg;span id='spellSpan1'>
                                                &ltg;textarea id="textbox1" name="elm112" rows="10" cols="5" visible="true" style="width: 90%; display:block; visibility:visible" runat="server">&ltg;/textarea>

```
                                       &ltg;/span>
                                    &ltg;/div>
```

Code: .ascx where tiny_mce initialization happened.
tinyMCE.init({

```
            mode: "textareas",
            editor_deselector: "textarea-no-styles",
            theme: "advanced",
            plugins: "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",

            theme_simple_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_simple_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_simple_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_simple_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
            theme_simple_toolbar_location: "top",
            theme_simple_toolbar_align: "left",
            theme_simple_statusbar_location: "bottom",
            theme_simple_resizing: true,

            content_css: "/_layouts/Scripts/content.css",
            template_external_list_url: "/_layouts/QMSJS/lists/template_list.js",
            external_link_list_url: "/_layouts/QMSJS/lists/link_list.js",
            external_image_list_url: "/_layouts/QMSJS/lists/image_list.js",
            media_external_list_url: "/_layouts/QMSJS/lists/media_list.js",

            style_formats: [
        { title: 'Bold text', inline: 'b' },
        { title: 'Red text', inline: 'span', styles: { color: '#ff0000'} },
        { title: 'Red header', block: 'h1', styles: { color: '#ff0000'} },
        { title: 'Example 1', inline: 'span', classes: 'example1' },
        { title: 'Example 2', inline: 'span', classes: 'example2' },
        { title: 'Table styles' },
        { title: 'Table row 1', selector: 'tr', classes: 'tablerow1' }
        ]
        });
```

Note: The control works in chrome and firefox, but the issue is only occuring in  IE8 and IE 10. Please advise.
        }

Code: Where tiny_mce.js is being called.

&ltg;script type="text/javascript" src="/_layouts/...../jscripts/tiny_mce/tiny_mce.js">&ltg;/script>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6876](http://archive.tinymce.com/develop/bugtracker_view.php?id=6876) posted by [sunitkundu](http://archive.tinymce.com/profile.php?name=sunitkundu)_
> 
> _**Tags:** [msie msie8 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
