### ISSUE TITLE
Conditional comments not managed properly

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1620]
Description of problem: Conditional comments are displayed as if they are text. The code below is produced by Outlook

Steps to reproduce:

An html code as follows:

&ltg;!-- [if gte vml 1]>
&ltg;v:shapetype id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f">
 &ltg;v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect" />
 &ltg;o:lock v:ext="edit" aspectratio="t" />
&ltg;/v:shapetype>
&ltg;v:shape id="Dikd�rtgen_x0020_11" o:spid="_x0000_s1035" type="#_x0000_t75" alt="AA" href="http://192.168.1.5:5050/smartClick/Customer1.faces?keyValueCust=2985">
&ltg;/v:shape>
&ltg;![endif]--> 

&ltg;! [if !vml]> 
&ltg;span style="mso-ignore: vglayout;"> 
&ltg;a href="http://192.168.1.5:5050/smartClick/Customer1.faces?keyValueCust=2985">&ltg;img title="" src="images/mail/image001_71230.png" alt="AA" width="32" height="32" border="0" />&ltg;/a> 
&ltg;/span>
&ltg;![endif]>

is converted to:

&ltg;!-- [if gte vml 1]>
&ltg;v:shapetype id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f">
 &ltg;v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect" />
 &ltg;o:lock v:ext="edit" aspectratio="t" />
&ltg;/v:shapetype>
&ltg;v:shape id="Dikd�rtgen_x0020_11" o:spid="_x0000_s1035" type="#_x0000_t75" alt="AA" href="http://192.168.1.5:5050/smartClick/Customer1.faces?keyValueCust=2985">
&ltg;/v:shape>
&ltg;![endif]--> 

&lt;! [if !vml]&gt; 
&ltg;span style="mso-ignore: vglayout;"> 
&ltg;a href="http://192.168.1.5:5050/smartClick/Customer1.faces?keyValueCust=2985">&ltg;img title="" src="images/mail/image001_71230.png" alt="AA" width="32" height="32" border="0" />&ltg;/a> 
&ltg;/span>
&lt;![endif]&gt;

So as a result, the display is as follows:

&ltg;! [if !vml]> AA &ltg;![endif]>

Expected result:

AA

Actual result:

&ltg;! [if !vml]> AA &ltg;![endif]>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6874](http://archive.tinymce.com/develop/bugtracker_view.php?id=6874) posted by [yavuzselimcakir](http://archive.tinymce.com/profile.php?name=yavuzselimcakir)_
> 
> _**Tags:** [firefox msie safari chrome opera conditional comments]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by GoorMoon** [comment]
any news ?

**Comment by HaraldWalker** [comment]
`<!--[if (gte mso 9)|(IE)]>For Outlook<![endif]-->`
is being changed to:
`<!-- [if (gte mso 9)|(IE)]>For Outlook<![endif]--> `
By adding a space behind !-- it breaks the conditional comment. Only seems to do this when '[if' is following.

**Comment by fyrkant** [comment]
Closing this issue as @HaraldWalker seems to have provided a fix above. If anyone still has this problem, just leave a comment and we can open it up again.
