### ISSUE TITLE
tinyMCE inside iframe on iOS loses focus

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1621]
Description of problem:

Steps to reproduce:
1. Access the provided fiddle with an iPad (tested both iOS 6 and 7)
2. Scroll down to the editor
3. Start typing

Expected result:
Focus should stay on the editor so you can see what you're typing.

Actual result:
The caret and implicitly the focus somehow move to the top of the parent iframe, so if the editor is lower, it gets out of view.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6875](http://archive.tinymce.com/develop/bugtracker_view.php?id=6875) posted by [sergiu.nichitean](http://archive.tinymce.com/profile.php?name=sergiu.nichitean)_

> _**Tags:** [safari ios iframe]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/jdeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
