### ISSUE TITLE
Browsers slow/crash when textarea contains GT & LT like this: >>>>>03/17/2014<<<<<.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1622]
Description of problem:

Steps to reproduce:
1.Loading TinyMCE v4.0.22 jquery from javascript function

2.Textarea contains plain text

3 This seems to be the problem >>>>>03/17/2014&ltg;&ltg;&ltg;&ltg;&ltg;.

4.IE crashes, others lockup or become very slow.

5.Tested in Firefox, Safari, Chrome, and MSIE. IE Crashes have to kill MSIE and restart, Chrome locks until KILL page displaye. Not sure about other browsers. 

6.This may have little to do with TinyMCE init from within a function and more to do with the the contents of the textarea containing GT and LT characters.

7.Reducing the textarea to just >>>>>03/17/2014&ltg;&ltg;&ltg;&ltg;&ltg;. does not replicate the problm. Seems to be something to do with the amount/size of text.

Expected result: init TinyMCE and display textarea.

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6877](http://archive.tinymce.com/develop/bugtracker_view.php?id=6877) posted by [TonyRusso](http://archive.tinymce.com/profile.php?name=TonyRusso)_
> 
> _**Tags:** [msie chrome msie8 chrome11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/kdeaab/1_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
