### ISSUE TITLE
formatting issue when pasting from word doc

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1624]
Description of problem:

Steps to reproduce:
1. config tinymce v4:
paste_retain_style_properties : "all",
paste_remove_styles_if_webkit : false,

2.paste content from the attached test Word doc.

Expected result:
No major formatting problem.

Actual result:
indent not right,
order number overlaps with text.
...

Tried to adjust the config, but no way to get it right..

The behavior is different in IE. The list number doesn't look right.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6878](http://archive.tinymce.com/develop/bugtracker_view.php?id=6878) posted by [bubdou](http://archive.tinymce.com/profile.php?name=bubdou)_

> _**Tags:** [firefox msie safari chrome opera paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
