### ISSUE TITLE
Chrome and IE crash on some html code in textarea

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1625]
Description of problem: chrome and ie last updated versions crashes on loading tinymce textarea with some tags.

Last found bug on code:
&ltg;td>0-60&deg;?&ltg;/td>
&ltg;td>1&deg;F/&deg;?&ltg;/td>
&ltg;td>+1.8&deg;F/&deg;?&ltg;/td>

I have tried to change this block to:
&ltg;td>0-60 &deg;?&ltg;/td>
&ltg;td>1&deg;F / &deg;?&ltg;/td>
&ltg;td>+1.8&deg;F / &deg;?&ltg;/td>
And page started working fine in both Chrome and IE.

No such bug in Firefox.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6880](http://archive.tinymce.com/develop/bugtracker_view.php?id=6880) posted by [maytech](http://archive.tinymce.com/profile.php?name=maytech)_

> _**Tags:** [msie chrome msie9 chrome12]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
