### ISSUE TITLE
Cannot add text below a div at the end of the page

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1627]
Description of problem:
When a div is placed at the end of the contents, it is impossible to get outside of the div. Text cannot be added below the div.

Steps to reproduce (see fiddle):
1. Go to http://www.tinymce.com/tryit/basic.php
2. Open HTML source code
3. Go to the end of the file and add:
   &ltg;div>this is text&ltg;/div>
4. Try to add text after the &ltg;div>

Expected result:
Text can be added below and outside of the div.

Actual result:
Text cannot be added below and outside of the div. The cursor won't go below the div.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6882](http://archive.tinymce.com/develop/bugtracker_view.php?id=6882) posted by [mhu](http://archive.tinymce.com/profile.php?name=mhu)_

> _**Tags:** [firefox msie safari chrome opera div v4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/vdeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by jonom** [comment]
I am experiencing this or a variant of this on TinyMCE 4.6.5 and can see that it appears to happen on the latest stable version of 4.x as well. In my case the div is generated by an insert-media plugin.

If you go to https://codepen.io/tinymce/pen/NGegZK (the demo from [this page](https://www.tiny.cloud/docs-4x/demo/full-featured/)) and edit the source code as described above to add a div before the closing body tag, you can click at the end of the text in the editor and hit return. This actually does get you out of the div but it creates another div. A paragraph should probably be created instead. I think this is what users would expect and this is the behaviour if you hit return after a heading tag.

Most users will probably not realise they are working in a div at this point and creating non-semantic markup that will likely render poorly.

![Screen Shot 2020-08-18 at 11 17 39 am](https://user-images.githubusercontent.com/1079425/90551269-eb022200-e145-11ea-912d-22a822a715b9.png) ![Screen Shot 2020-08-18 at 11 22 03 am](https://user-images.githubusercontent.com/1079425/90551276-ee95a900-e145-11ea-820e-dffc660a6be6.png)

This looks to be a description of the same issue: https://core.trac.wordpress.org/ticket/28444

**Comment by sowmi3114** [comment]
I am experiencing the above issue with my application and user is not able to use the table insert option because of this. Please resolve this as soon as possible. using TinyMCE v5
