### ISSUE TITLE
Noneditable issues

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1629]
Steps to reproduce:
1. Enter http://jsfiddle.net/YXwt6/1/
2. Try to move the text cursor using keyboard arrows. Try hitting "backspace" and "delete" keys. Try writing some text before of after the node.
3. Now enable "noneditable" TinyMCE plugin and do the same.

Expected result:
It will work like the default contenteditable.

Actual result (each point shows a separate bug):
- Usage of 'mceInsertContent' inserts the element and the cursor is positioned inside of it rather than after it or nowhere.
- The element can be clicked and the cursor can be placed inside at any time, in any place. In my opinion it shouldn't be possible to insert a cursor inside of "noneditable" item at all.
- Clicking any letter (while the cursor is inside the "noneditable" link, at its very end) moves the caret after the element but does not write the letter.
- The second attempt to hit some letter works but when you click "backspace" right afterwards then the letter is not deleted but entire "noneditable" element is deleted instead.
- Clicking Ctrl+Z restores the "noneditable" element but the letter is gone (even though I didn't hit "backspace" or "delete" but only Ctrl+Z).
- Clicking any letter (while the cursor is inside the noneditable link, in the middle this time) selects the text in "noneditable" element and that's it - new letters don't appear anywhere, it doesn't get deselected if you hit any key more times, basically nothing happens but the cursor is present all the time (in the original contenteditable="false" the cursor disappears).
- positioning the cursor at the beginning of the "noneditable" element and hitting the "delete" key deletes the "noneditable" element but the paragraph that remains doesn't have BR inside which makes it have 0 height.

So, I think that all the issues would be gone if "noneditable" would work like standard contenteditable="false".

UPDATE: Even better - "noneditable" could work the same way like images do. It could even be draggable and all these cursor issues are not present with images.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6884](http://archive.tinymce.com/develop/bugtracker_view.php?id=6884) posted by [Trevlon](http://archive.tinymce.com/profile.php?name=Trevlon)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
