### ISSUE TITLE
DOM Exception when pasting multiple times to the same field

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1630]
Description of problem: After pasting a couple times, the browser throws a DOM exception. Reproduced on the TinyMCE demo with Chrome

Steps to reproduce:
1. Make sure you have a little bit of text on your clipboard ("test test")
2. Type something in the wysiwyg field (I chose "test")
3. Paste (new content is "testtest test")
4. Undo (new content is "")
5. Paste

Expected result: Text would be pasted into the field

Actual result: DOM exception: 
Uncaught NotSupportedError: Failed to execute 'createContextualFragment' on 'Range': The range's container is 'br', which is not supported. 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6885](http://archive.tinymce.com/develop/bugtracker_view.php?id=6885) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by bsuh** [comment]
I'm still seeing this behavior on TinyMCE homepage.

![image](https://cloud.githubusercontent.com/assets/47231/19824939/9e9091aa-9d28-11e6-886d-afb28696b8c3.png)

**Comment by jayarjo** [comment]
@bsuh i was not able to reproduce it using those steps. Could you record the exact steps that you do to hit that error?

**Comment by bsuh** [comment]
https://youtu.be/F4PAJpCm7B0
