### ISSUE TITLE
queryCommandState('justifyfull') never returns true

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1632]
Description of problem: I am trying to use the TinyMCE API to query the state of the text selection, but I am never able to determine if the text is using the justify format

Steps to reproduce:
1. Type some text in a paragraph
2. tinymce.activeEditor.execCommand('justifyfull')
3. tinymce.activeEditor.queryCommandState('justifyfull')

Expected result: queryCommandState would return true

Actual result: false is returned.

left, center, and right all work as expected

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6887](http://archive.tinymce.com/develop/bugtracker_view.php?id=6887) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by rafdulaf** [comment]
Hi.
The bug is still there in 4.7.11

**Comment by rafdulaf** [comment]
Looks like the FormatRegistry is registered for "alignjustify" but requested at "alignfull"

**Comment by rafdulaf** [comment]
New ticket here https://github.com/tinymce/tinymce/issues/4374
