### ISSUE TITLE
Unable to drag and drop image in tinymce editior in IE 10 and above versions.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1633]
Description of problem:
Unable to drag and drop image in tinymce editior in IE 10 and above versions. It is working fine in IE 8/9.

Steps to reproduce:
1.Go to http://www.tinymce.com/tryit/basic.php
2.Try to drag and drop image in editor in IE 10 and above versions.

Expected result: Should be able to drag and drop image.

Actual result: Unable to drag and drop image.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6888](http://archive.tinymce.com/develop/bugtracker_view.php?id=6888) posted by [Shanth Khandre](http://archive.tinymce.com/profile.php?name=Shanth Khandre)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
