### ISSUE TITLE
Image Class Dropdown Rendering Error

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1634]
Description of problem: When following your instructions to implement a drop down of classes on the image dialog for things such as alignment, the menu renders but when you click on it, the menu appears in the top left corner. I reproduced this bug under the latest versions of Chrome and IE. I downloaded the latest version and got an identical result.

Steps to reproduce:
1. See above.
2.
3.
4.
5.

Expected result: Drop down aligned with position on form

Actual result: As described above.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6889](http://archive.tinymce.com/develop/bugtracker_view.php?id=6889) posted by [JoelMurdoch](http://archive.tinymce.com/profile.php?name=JoelMurdoch)_

> _**Tags:** [msie chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
