### ISSUE TITLE
Able to resize <hr> elements vertically

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1639]
Description of problem: I am able to click and drag a horizontal line to resize it vertically. I'm also able to type inside the &ltg;hr> (no idea). Reproduced on TinyMCE's demo.

Reproduced on IE11

Steps to reproduce:
1.Insert a horizontal line
2.Click on the line to select it
3.While holding the mouse button down, drag the line down

Expected result:Nothing would happen

Actual result:Line somehow resizes. I'm also able to type "inside" the line. See attached.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6893](http://archive.tinymce.com/develop/bugtracker_view.php?id=6893) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_

> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
