### ISSUE TITLE
CustomDelete's MutationObserver is listening to elements outside of the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1640]
Description of problem:
In the Quirks.js CustomDelete function MutationObserver.observer is being called using the document as the node to observe. At least in an inline editor the document is the same as the page using the editor. One of the mutations being observed is the style attribute. TinyMCE is listening for changes to the style attribute on all the elements outside of the editor when the delete command is executed. If something else is listening to mutations on the editor and changes the style of an element during that event then TinyMCE gets the change when it calls takeRecords. And then removes the style attribute from the element.

This has been observed in Safari 7.0.3 and Chrome 34.

Steps to reproduce:
1. Listen to dom mutation events on the editor (ListenerA)
2. Type two lines of text in the editor
3. Hit backspace in the editor to delete a line
4. ListenerA changes the style of an element outside the editor

Expected result:
TinyMCE does not remove the style attribute from elements outside the editor during a delete.
Actual result:
TinyMCE removes style attributes from elements outside the editor during a delete.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6894](http://archive.tinymce.com/develop/bugtracker_view.php?id=6894) posted by [jordandh](http://archive.tinymce.com/profile.php?name=jordandh)_

> _**Tags:** [safari chrome safari6 chrome34 safari7]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
