### ISSUE TITLE
Crash when performing strategic sequence of formatting options

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1641]
Description of problem: TinyMCE crashes performing a specific sequence of events

Steps to reproduce: (Begin with an empty text area)
1.Bold the text
2.Center align the text
3.Start a bulleted list
4.Left align the text
5.Unbold the text

Expected result:Text would no longer be bold

Actual result:Browser crash in Formatter.js
// If index based end position then resolve it
if (endContainer.nodeType == 1 && endContainer.hasChildNodes()) {
   lastIdx = endContainer.childNodes.length - 1;
   endContainer = endContainer.childNodes[endOffset > lastIdx ? lastIdx : endOffset - 1];

   // *********\* endContainer is null here **********
   if (endContainer.nodeType == 3) {
      endOffset = endContainer.nodeValue.length;
   }
}

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6896](http://archive.tinymce.com/develop/bugtracker_view.php?id=6896) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_
> 
> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Tlapi** [comment]
We see the same problem on Safari 9.1.1 right on the same line.

**Comment by Revot** [comment]
The same problem on IE 9 in scenario, with empty editor:

1. Bold the text
2. Start bullet list
3. Click on empty space in the middle of editor 
4. Unblold

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
