### ISSUE TITLE
Inline css is added, from editor css, when new lines are edited

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1643]
Description of problem:

I can't reproduce the issue in fiddle because it lacks editor styles.

Steps to reproduce:
1. Add editor styles (which will format the default text)
2. Add double new lines between paraphs with a nbsp each, or paste text from another app. 
3. Select text cross-paragraphs (even triple-click an empty line)
4. Edit the selection in any way.

Expected result: No inline stiles to be added.

Actual result: 

The joined text will be wrapped in a span with inline css from the rules in the editor.

I've observed this error in wordpress for years now, but I was never able to narrow it down.
Even a cloned copy of a website hosted locally (MAMP) fails, while the live website works fine.

Even without custom editor-styles, the simple b tag, which is displayed with 1.5em height, adds that value to the edited text (always when editing cross-paragraphs)

I narrowed it down today, when I created an editor-style with background-color, and when editing a line break, the text receives the background color hardcoded in a span as inline style.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6900](http://archive.tinymce.com/develop/bugtracker_view.php?id=6900) posted by [sergiozambrano](http://archive.tinymce.com/profile.php?name=sergiozambrano)_

> _**Tags:** [chrome chrome13 inline css span added newline styles rules]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
