### ISSUE TITLE
TinyMCE 4.x glitchy with Windows Phone 8

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1647]
This was tested with Windows Phone 8, which uses IE10.  I tested the demo editor on the TinyMCE home page.

Start typing something in the editor, and when you hit the Enter key the fun begins.  The cursor seems to jump around and extra lines get inserted.

This is probably caused by some browser detection for IE that is not properly handling IE on Windows Phone.  (IE on Windows Phone is actually quite good.)

The UA String for my Windows Phone browser is:

Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; HTC; HTC6990LVW)

If you guys don't currently test for Windows Phone, I would strongly recommend it.  Windows Phone sales are growing, and in some countries outsells iOS.  It is an excellent platform.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6899](http://archive.tinymce.com/develop/bugtracker_view.php?id=6899) posted by [speednet](http://archive.tinymce.com/profile.php?name=speednet)_
> 
> _**Tags:** [msie windows phone]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
