### ISSUE TITLE
Pasting an ordered list with styles being changed to unordered list

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1648]
Description of problem:
When pasting a ordered list with styles (i.e. bold/italic) into TinyMCE 4, the list changes be unordered (bullet list).

The HTML source when pasting lists into TinyMCE 4 from IE11 is also very different from that of when lists are pasted in from any other browser (tested IE8-10, FF and Chrome).

Steps to reproduce:
1. Create a numbered list in word
2. Apply a style to it i.e. bold or italic
3. Paste into TinyMCE 4

Expected result:
The numbered list pasted will still be a numbered list, with styles still applied.

Actual result:
The numbered list has been changed to a bullet list.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6903](http://archive.tinymce.com/develop/bugtracker_view.php?id=6903) posted by [rhys.foord](http://archive.tinymce.com/profile.php?name=rhys.foord)_
> 
> _**Tags:** [msie ie11 paste list]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
