### ISSUE TITLE
Unwanted &nbsp; added when doing copy-paste in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1652]
Description of problem:

I have two paragraphs, and the source codes are 

&ltg;p>This is a copy-paste test case.&ltg;/p>
&ltg;p>This only happens in Chrome&ltg;/p>

Steps to reproduce:
1. In Editor, copy the word"chrome" with Ctrl+C in the 2nd paragraph.
2. Paste it with Ctrl+V next to "test" in the 1st paragraph so it becomes one word"testChrome"
3. Use blank key from keyboard to add a space to separate the work above to two words: test Chrome
4. Check the source code

Expected result:
Source codes should be "&ltg;p>This is a copy-paste test Chrome case&ltg;/p>"

Actual result:
Source codes are "&ltg;p>This is an copy-paste test&nbsp;Chrome case&ltg;/p>", where &nbsp; is added between.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6906](http://archive.tinymce.com/develop/bugtracker_view.php?id=6906) posted by [xwei](http://archive.tinymce.com/profile.php?name=xwei)_
> 
> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
