### ISSUE TITLE
Not hidden in Data Reveal

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1654]
Description of problem: I use the data-reveal plugin from Zurb (http://zurb.com/playground/reveal-modal-plugin) and I have my TinyMCE inside one of these. The only issue is that it shows up when the div is hidden, so the class ".mce-tinymce" needs to be "visible:inherit" not "visible:visible !important".

Expected result: To be hidden until event triggered

Actual result: Shows up where hidden element is sitting. Writing inline CSS or exact selectors like "body div.mce-tinymce {visible:inherit !important}" doesn't work either because the skin.css is triggered on document load (after all other styling) so it over rides anything you do.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6909](http://archive.tinymce.com/develop/bugtracker_view.php?id=6909) posted by [dpDesignz](http://archive.tinymce.com/profile.php?name=dpDesignz)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
