### ISSUE TITLE
pspell tinmyce not working in MSIE. Throws following error when accessed there SCRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3..

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1655]
Description of problem:

Steps to reproduce:
1. Goto any MSIE browser.
2. As soon as you click spellchecker plugin in the textarea.
3. There will be a pop up with Content as Error Response:
4.
5.

Expected result: It should check the spelling and add word to dictionary.

Actual result: SCRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6914](http://archive.tinymce.com/develop/bugtracker_view.php?id=6914) posted by [wrkhan](http://archive.tinymce.com/profile.php?name=wrkhan)_
> 
> _**Tags:** [msie msie7 msie8 msie9 msie10 msie network error 0x2ef3]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
