### ISSUE TITLE
Spellchecker not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1659]
Description of problem:

Spellchecker not working

Steps to reproduce:
1. navigate to http://www.tinymce.com/tryit/classic.php
2. Click on SpellCheck icon from Toolbar

Expected result:
Spellcheck should work

Actual result:
 Error is displayed:Spellchecker request error: 0

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6913](http://archive.tinymce.com/develop/bugtracker_view.php?id=6913) posted by [RV](http://archive.tinymce.com/profile.php?name=RV)_
> 
> _**Tags:** [firefox chrome firefox5 firefox6 firefox7 firefox8 chrome10 chrome11 chrome12 chrome13]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by nori-h** [comment]
We have taken a look and this issue appears to be a duplicate of #1087

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
