### ISSUE TITLE
tinyMCE code prevents jQuery no conflict

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1660]
Hello,

In file tinymce.min.js there is a code:
   if(!window.jQuery)throw new Error("Load jQuery first");
This code prevents certain no-conflict implementations of jQuery (where the jQuery variable is local, nor global)

I changed the code locally to: if (!jQuery)....
It works well. I want to apply a patch, but wanted to check if there is a reason to why you're using window.jQuery and not jQuery.

Kind regards,
Mati Skiba

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6915](http://archive.tinymce.com/develop/bugtracker_view.php?id=6915) posted by [matiskiba](http://archive.tinymce.com/profile.php?name=matiskiba)_
> 
> _**Tags:** [firefox msie safari chrome opera jquery]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
