### ISSUE TITLE
Copy paste issues regarding alignment, color & backcolors tags, wrapping

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1666]
Description of problem:
Fails to copy important styling.

Steps to reproduce:
1/ Copy paste the following htm code in a html file
2/ view it in a browser (Chrome 34)
3/ copy all from browser in a tinyMCE 4.0.26 editor
4/ observe the changes between original vs copy & paste

About solutions:
Possibly, remove all inline styles by a css class arbitraly identified as STY%d%d%d( i.e. STY000 to STY999) and put all style definitions in a header style (i.e. .STY000= { background-color: blabla; }, this could be achieved through hashing table.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6933](http://archive.tinymce.com/develop/bugtracker_view.php?id=6933) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
