### ISSUE TITLE
Indent/Outdent level of list sometimes select text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1667]
I have problem, sometimes when I select one item in list and want it to indent or outdent, it doesn't change indentation level, but select a whole text in textarea/div. How can I protect my customers to don't get that bug?
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6934](http://archive.tinymce.com/develop/bugtracker_view.php?id=6934) posted by [ukb65127](http://archive.tinymce.com/profile.php?name=ukb65127)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
