### ISSUE TITLE
Add non-minified version to bower package

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1673]
When installing tinymce through bower, only a minified version is provided: "tinymce/tinymce.min.js". As many projects already have a minification step, it can be redundant. It would be nice if all project assets could be minified using a single build step and consistent build tools. Additionally, when debugging, and minified sources aren't being used, it is nice to see a full stack trace on an error. Having a non-minified version would make this easier.

As a example, jQuery provides both a minified version and a non-minified version in their bower package.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6926](http://archive.tinymce.com/develop/bugtracker_view.php?id=6926) posted by [jdufresne](http://archive.tinymce.com/profile.php?name=jdufresne)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by RinkAttendant6** [comment]
This issue appears to be resolved as both tinymce.js and tinymce.min.js are in the tinymce-dist repository.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
