### ISSUE TITLE
copy- page in firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1677]
Description of problem:
I can not copy and paste text from word or text in the same textarea in firefox

Expected result:
I provide some code so that it can add to my project folder this so people from your browser ecceden not have problems

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6930](http://archive.tinymce.com/develop/bugtracker_view.php?id=6930) posted by [diana lerma](http://archive.tinymce.com/profile.php?name=diana lerma)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
