### ISSUE TITLE
Empty span is removed if inside p

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1687]
Description of problem:

See fiddle

Expected result: If I've understood the documentation correctly, none of the empty spans should be removed

Actual result: The span wrapped inside the p is not there when selecting "source code"

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6957](http://archive.tinymce.com/develop/bugtracker_view.php?id=6957) posted by [einar.stubhaug](http://archive.tinymce.com/profile.php?name=einar.stubhaug)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Uheaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
