### ISSUE TITLE
Call DomUtils.getNext/getPrev with attribute will get exception when sibling is textnode

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1688]
Description of problem:
Because text node don't have getAttribute function. But use the getNext/getPrev(refNode, '[attrName]') will call getAttribute function.

Steps to reproduce:
1. var ed = tinymce.activeEditor; ed.execCommand("mceInsertContent",'text before.&ltg;p id="testNode">aaa&ltg;/p>text after&ltg;p attrib="testAttrib">&ltg;/p>');
2. var refNode = ed.dom.get('testNode'); var nextSibling = ed.dom.getNext(refNode, '[attrib]')

Expected result:
 null

Actual result:
 Got exception

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6960](http://archive.tinymce.com/develop/bugtracker_view.php?id=6960) posted by [still_wind](http://archive.tinymce.com/profile.php?name=still_wind)_
> 
> _**Tags:** [firefox msie safari chrome opera domutils getnext getprev getattrib]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
