### ISSUE TITLE
TinyMCE 4.0.26, Spell Check is not working & MoxieManager

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1690]
Description of problem:

Well, I integrated with dot net but Spell Check is not working at all. Please, share me details. And if I include the MoxieManager, in Browsers, it shows blank. That is, no controls are visible. Please, reply me soon. 

The following code is : in Dot Net

&ltg;!-- TinyMCE -->        

```
   &ltg;script type="text/javascript" src="/TinyMCE_4.0.26_PROD/tinymce/js/tinymce/tinymce.min.js">&ltg;/script>

&ltg;script type="text/javascript">
        tinymce.init({
            selector: "textarea",
            theme: "modern",
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu paste",
                "emoticons template directionality textcolor"

            ],
            toolbar1: "insertfile undo redo | styleselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            toolbar2: "print preview media | forecolor backcolor | emoticons | spellchecker | searchreplace",
            image_advtab: true,
            templates: [
                { title: 'Test Template 1', content: 'Test 1 : Sample' },
                { title: 'Test Template 2', content: 'Test 2 : Sample' }]
        });
&ltg;/script>    
```

Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6941](http://archive.tinymce.com/develop/bugtracker_view.php?id=6941) posted by [svijay2014](http://archive.tinymce.com/profile.php?name=svijay2014)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
