### ISSUE TITLE
IE8 doesn't load text in textarea on first page load

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1691]
Description of problem:
I have two textareas to which I attach tinymce like so:

&ltg;head>
....
            &ltg;script type="text/javascript">
                tinymce.init({
                  selector: "textarea.infoText",
                  entity_encoding: "raw",
                  plugins: 'link',
                  toolbar: "undo redo | cut copy paste | bold italic | numlist bullist | link",
                  target_list: false,
                  relative_urls: false,
                  remove_script_host: true,
                  menubar: false,
                  resize: "both",
                  language: '&ltg;c:out value="${currentLanguage.toLowerCase()}"/>'
               });
            &ltg;/script>
            &ltg;style>
              &ltg;%-- http://www.tinymce.com/forum/viewtopic.php?id=31345 --%>
              .mce-path > .mce-path-item, .mce-path > .mce-divider {display: none !important;}
            &ltg;/style>

&ltg;/head>

The first textarea almost always shows the tinymce editor but without text when the page loads. The second textarea is always properly shown.  When I click on e.g. the bold icon the text appears and I can use the editor.  Reloading the page always creates a usable editor.  Sometimes the page loads fine on first load, though.  This only happens in IE8 (other IEs not tested) but not in Firefox or Opera 12.

As a test I loaded tinymce delayed with a timer.  Exactly the same result except it happens a few seconds later.

Workaround: load tinymce style sheet before calling tinymce.init().  With that I could not see the problem.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6942](http://archive.tinymce.com/develop/bugtracker_view.php?id=6942) posted by [hkk](http://archive.tinymce.com/profile.php?name=hkk)_
> 
> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
