### ISSUE TITLE
Inserting a bullet list in an empty div removes the div

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1692]
Description of problem:

Inserting a bullet list in an empty div or a div with 1 row with cursorposition 1 removes the parent div

Steps to reproduce:
1. create div 
2. insert bullet list
3. or:
4. create div
5. insert text
6. place cursor position before text
7. insert bullet list

Expected result:
bullet list in div

Actual result:
bullet list without div

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6943](http://archive.tinymce.com/develop/bugtracker_view.php?id=6943) posted by [kowa.applicatiebeheer](http://archive.tinymce.com/profile.php?name=kowa.applicatiebeheer)_

> _**Tags:** [firefox msie msie8 div bullet list]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/rheaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
