### ISSUE TITLE
IE bug when setting forced_root_block_attrs

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1695]
Description of problem:
the forced_root_block_attrs will not be forced if you select all text then typed any other character in Internet Explorer
Steps to reproduce:
1.Set forced_root_block_attrs config attribute
2.Type some text in the editor
3.select all content (ctrl + A)
4.Type any char code (like b)

Expected result:
&ltg;p class="MsoNormal" style="font-weight:bold;">b&ltg;/p>
Actual result:
&ltg;p>b&ltg;/p>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6947](http://archive.tinymce.com/develop/bugtracker_view.php?id=6947) posted by [hammadi87](http://archive.tinymce.com/profile.php?name=hammadi87)_

> _**Tags:** [msie msie7 msie8 msie9 msie10 forced_root_block_attrs ie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/7heaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
