### ISSUE TITLE
Bulleted lists and text lose format in IE11

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1696]
When copying from the attached Word documents (file2.doc, file3.doc) into the TinyMCE textarea, bulleted lists lose format and text around becomes part of the list too (but in the original file it isn't).

It happens in Internet Explorer 11.

Steps to reproduce:
1. Copy text from one of the attached documents.
2. Paste it into TinyMCE (settings in http://fiddle.tinymce.com/Bheaab/3 ).
3. You'll see that bulleted lists are not formatted as in the original file.

Sorry for the italian language used in the files.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6950](http://archive.tinymce.com/develop/bugtracker_view.php?id=6950) posted by [medicinaverona](http://archive.tinymce.com/profile.php?name=medicinaverona)_
> 
> _**Tags:** [msie msie10 paste word list formatting ie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Bheaab/3_

**Comment by blackcathikari** [comment]
We've looked into this and believe it is related to a few other bug reports regarding pasting lists from Word. The related reports are #2853, #3061, #1314, #1422, #1489, #1696 and #1708, and cover indentation, list styling and list item order not being preserved. Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
