### ISSUE TITLE
Intend not retained and special chars are seen when copy paste from msword

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1700]
When I copy a formatted text from ms-word to tinymce v4.0.19 the formatting is not retained (indent is not retained )  
Steps to reproduce
1.Create a ms doc with bulletin in a hierarchy 
2.Copy the text from word and and paste it in tinymce.
3.Intent not retained 

Expected result:
Intend should be retained.

Actual result:
Intend not retained.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6971](http://archive.tinymce.com/develop/bugtracker_view.php?id=6971) posted by [deanjones](http://archive.tinymce.com/profile.php?name=deanjones)_
> 
> _**Tags:** [firefox msie safari chrome opera copy paste msword formatting]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
