### ISSUE TITLE
Can not init editor in iframe with asynchronous mode.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1703]
Description of problem:
I found that "_wait" function in tinymce, only "win = win.top" to check if the editor need execute "_pageInit" function after window loaded. 

Steps to reproduce:
1.In iframe page.
2.use requireJS or seaJS to require tinymce after window loaded.
3.call tinymce.init in asynchronous callback function.
Expected result:
  tinymce editor should initialize correct. 
Actual result:
  Nothing happen.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6961](http://archive.tinymce.com/develop/bugtracker_view.php?id=6961) posted by [still_wind](http://archive.tinymce.com/profile.php?name=still_wind)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
