### ISSUE TITLE
Delete column leaves table in inconsistent state

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1704]
1. Insert the HTML below into the editor
2. Select the 2x2 column in right of the second row by clicking in it
3. Do Delete Column

Expected Result

Either the last two columns are deleted, or one of them

Actual Result

The second row is one cell short, so that the table is no longer rectangular.

&ltg;table style="border: 1px solid #cccccc; width: 446px; border-collapse: collapse; box-sizing: border-box; table-layout: fixed; color: #000000; font-family: verdana, geneva, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.5px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">&ltg;colgroup>&ltg;col style="width: 0px;" />&ltg;col style="width: 0px;" />&ltg;col style="width: 0px;" />&ltg;col style="width: 0px;" />&ltg;col style="width: 0px;" />&ltg;col style="width: 0px;" />&ltg;/colgroup>
&ltg;tbody>
&ltg;tr>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;" colspan="3">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;" colspan="2" rowspan="2">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;" rowspan="2">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc; cursor: col-resize;" rowspan="3">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="border: 1px solid #cccccc;" colspan="2">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc; cursor: col-resize;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #cccccc;">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6963](http://archive.tinymce.com/develop/bugtracker_view.php?id=6963) posted by [Yogu](http://archive.tinymce.com/profile.php?name=Yogu)_

> _**Tags:** [firefox chrome table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
