### ISSUE TITLE
Icons do not display when custom fonts are disabled

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1705]
When custom fonts are disabled, no icons are displayed. We're attempting to use the editor on a large organization and the security policy prohibits custom fonts. Perhaps we should fall-back to a sprite-based implementation if custom fonts aren't available?

Steps to reproduce (Firefox):
1. Go to Preferences -> Content -> Advanced
2. Uncheck "Allow pages to choose their own fonts"
3. Load TinyMCE editor
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6964](http://archive.tinymce.com/develop/bugtracker_view.php?id=6964) posted by [JChafik](http://archive.tinymce.com/profile.php?name=JChafik)_

> _**Tags:** [firefox msie safari firefox8 msie10 safari6 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
