### ISSUE TITLE
Paste from Word doesn't work properly in IE browsers

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1708]
Description of problem:
Paste from word future doesn't work properly.
It adds additional, unnecessary symbols.

Steps to reproduce:
1. Copy the text from the attached word document.
2. Paste it into TinyMCE editor in Internet Explorer browser.
3. Paste it into TinyMCE editor in other browser. 
4. Compare the results.

Expected result: 
In any other browsers i have the expected result.

Actual result:
In IE the "paste from word" functionality adds additional bullets/numbers in the bulleted/numbered list.

I'm attaching image files representing the sequence of steps, taken resulting in this issue.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6968](http://archive.tinymce.com/develop/bugtracker_view.php?id=6968) posted by [Atanas Sarafov](http://archive.tinymce.com/profile.php?name=Atanas Sarafov)_
> 
> _**Tags:** [msie msie7 msie8 msie9 msie10 word ie paste numbered bullet list]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
We've looked into this and believe it is related to a few other bug reports regarding pasting lists from Word. The related reports are #2853, #3061, #1314, #1422, #1489, #1696 and #1708, and cover indentation, list styling and list item order not being preserved. Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
