### ISSUE TITLE
Image remains selected after closing inline editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1709]
See the fiddle.  Click the image, watch the black border show up, deselect the editor and the border remains.  Same happens if there are multiple inline editors.  Inspecting the source shows that the image gets data-mce-selected="1" when it is clicked on, but the only way to remove it is to click on something else within that same editor.  If you just click away from the editor or onto another editor, the black border remains.

Thank you for investigating.

Edit: If object_resizing is on, the image will also remain in resize mode after closing the editor.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6969](http://archive.tinymce.com/develop/bugtracker_view.php?id=6969) posted by [sarthaz](http://archive.tinymce.com/profile.php?name=sarthaz)_
> 
> _**Tags:** [firefox msie safari chrome opera inline images datamceselected]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Rieaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
