### ISSUE TITLE
First two letter of word in uppercase on iOS 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1710]
Description of problem: When editing text on iOS device, selecting and then typing over the first word of a sentence ends up having two uppercase letters. 

Steps to reproduce:
1. Navigate to http://www.tinymce.com on any iOS device
2. Inside the sample editor double tap on first word of any sentence to highlight it
3. Start typing for e.g Atlanta

Expected result:Atlanta

Actual result:ATlanta

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6972](http://archive.tinymce.com/develop/bugtracker_view.php?id=6972) posted by [sanukiUdon](http://archive.tinymce.com/profile.php?name=sanukiUdon)_
> 
> _**Tags:** [safari ios editing]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
