### ISSUE TITLE
The Alignment field in the Table propertes window is always reset , when the window opens

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1712]
Description of problem:

Steps to reproduce:
1. I have a table.
2. I click in the table, and then click Table > Table properties.
3. In the Table properties window, I select Alignment = Centered, and click OK.
4. The table looks now centered.
5. Once again, i click in the table, and then click Table > Table properties.

Expected result:
The Table propertes window should show the current settings for all available table propertes.

Actual result:
The Alignment field in the Table propertes window shows 'None' instead of the current setting 'Centered'.
If I click OK without changing the Alignment setting (because this time I did not to intend to make any changes in the table alignment), the alignment of my table will be reset to 'None'

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6975](http://archive.tinymce.com/develop/bugtracker_view.php?id=6975) posted by [liliana@onevoice.no](http://archive.tinymce.com/profile.php?name=liliana@onevoice.no)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
