### ISSUE TITLE
TinyMCE 4.0.28 edit popups issue.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1714]
Description of problem:
Creating TinyMCE editor like all demos are showing. The ones you have on your homepage under "Try It".
The editor is appearing with no problems. I can enter text, format it, add smiles, but... If I'll press on "insert image", "insert link", "preview", ... On any button that should open a popup menu that have black screen behind (attachment) popup will appear on approx 1 sek and disapear. If I'll scroll (after popup is dissapeared) it will appear, but no input fields on this popup, nor the buttons (only small X). As I found out these fields located on the wery top of my page. Meening. I need to scroll to top and popup will become normal, with all input fields and buttons. If I'll start to scroll down fields will disappear (they will stay on top of the page).

Can't reproduce it visually, but this is working on Mozilla and IE, and in all your page examples.

Steps to reproduce:
1.Make centered div on z-level:1;
2.add in div another div container for editor;
3.init TinyMCE on created container (create editor as in demos);
4.editor should be created on bottom of the page, but page should be higher that screen. Better to have 1,5x of monitor height. I have it like this;
5.enter or not enter text in editor and press insert image butto;
6.view a popup. It should dissppear.

Expected result:
popup should open correctly with all fields and buttons in it.

Actual result:
popup is with no fields. Fields are hiding on the top of the page.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6977](http://archive.tinymce.com/develop/bugtracker_view.php?id=6977) posted by [garruda](http://archive.tinymce.com/profile.php?name=garruda)_

> _**Tags:** [chrome opera chrome13 opera12 popup menu image preview link video]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
