### ISSUE TITLE
The "body_class" configuration option isn't applied to the "Insert template" window's document body

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1716]
Hi All,

Description of problem:
I use the "body_class" configuration option. This option is applied to the main editor's document body and to the "Preview" window's document body. But it isn't applied to the "Insert template" window's document body. 
Therefore a preview of templates examples in this window are shown as a plain text if a code of some templates uses my custom css file and my custom body's class (as a container class).

TinyMCE Version = 4.0.28
Description of the "body_class" configuration option (http://www.tinymce.com/wiki.php/Configuration:body_class).

Steps to reproduce:
1. Add the template pligin to the plugins list in the configuration and add the template button to the toolbar.
2. Add your custom css file to the content_css option in the configuration.
3. Add your custom css class name to the body_class option in the configuration.
4. Add your custom template code to the templates list in the configuration.
5. Load a page with the editor.
6. See a souce code of a document in the main editor area.
7. Open the "Insert template" window.
6. See a souce code of a document in the "Insert template" window.

Expected result:
The "body" tag has an attribute class contained my custom css class name.

Actual result:
The "body" tag of a document in the main editor area has an attribute class contained my custom css class name.
But the "body" tag of a document in the "Insert template" window has no any attributes.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6988](http://archive.tinymce.com/develop/bugtracker_view.php?id=6988) posted by [avorobjovs](http://archive.tinymce.com/profile.php?name=avorobjovs)_

> _**Tags:** [firefox msie safari chrome opera configuration template]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/ekeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
