### ISSUE TITLE
BOM character appears when using non editable plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1717]
Description of problem:
When using the Non editable plugin BOM characters appear when mouse clicking next to the non editable text. 

The characters that appear can be seen in attached file "bom_characters.png".

The reason for this bug is that it the minification of file tinymce\plugins\noneditable\plugin.min.js codes "\uFEFF" to a BOM.

The way to avoid this bug is to remove the BOM and change it to back to "\uFEFF". This is fully reproducible!

The reason this bug cannot be reproduced in http://www.tinymce.com/tryit/3_x/noneditable_content.php is that the Javascript file on the web is not the same as in the download package. Please compare attached screenshots web_version.png with download_version_hex.png/download_version.png.

Steps to reproduce:
1. Download TinyMCE as specified in attached "download.png".
2. Setup so that you have text that is not editable.
3. Run and mouse click a couple of times right of non editable text.
4. BOM characters appear right of non editable text

Expected result:
No BOM characters should appear.

Actual result:
BOM characters appear as seen in "bom_characters.png".
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6979](http://archive.tinymce.com/develop/bugtracker_view.php?id=6979) posted by [greger](http://archive.tinymce.com/profile.php?name=greger)_

> _**Tags:** [chrome plugin non editable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
