### ISSUE TITLE
<ul> "cosmetic" bug

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1721]
Description of problem:

See: http://www.tinymce.com/forum/viewtopic.php?pid=113242#p113242

Expected result:
all bullets ought to be in same color

Actual result:
bullets use row formatting

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6993](http://archive.tinymce.com/develop/bugtracker_view.php?id=6993) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
We've investigated this and we can't reproduce this bug in TinyMCE v4.4.0 so I'm going to close this report. Let me know if this is still an issue for you though, and I can reopen it. Thanks,
Millie @ TinyMCE
