### ISSUE TITLE
lines getting merged

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1722]
Description of problem:
Hi,

Sorry I am logging a new bug because the previous one is closed and I am not sure if I can reopen it.

Here is the issue:

I have pasted some data into editor which has some bullet lines and some paragraphs which you can see in a"Before Submit.jpg". After submitting, all the lines are merged into as a paragraph which you can see in the "After Submit.jpg".

And also, after typing one line in editor if i hit enter and type something the two lines are getting merged into one line.

Note I am using majorVersion:"3",minorVersion:"5.8"
And the browser is Internet Explorer 8

Steps to reproduce:
1. enter some text in first line
2. hit enter and then enter text in second line
3. now submit
4. both the lines will be merged into a single line
5.

Expected result:
Both the lines shoule remain as two seperate lines

Actual result:
Both the lines are getting merged

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6983](http://archive.tinymce.com/develop/bugtracker_view.php?id=6983) posted by [vijaykumarr](http://archive.tinymce.com/profile.php?name=vijaykumarr)_

> _**Tags:** [firefox msie safari chrome opera 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
