### ISSUE TITLE
clicking on a hyperlink does nothing in IE11 and Chrome22

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1723]
Description of problem:

clicking on a hyperlink does not follow the link in IE11 and Chrome V22.0.1229.79 m but does work in Firefox V22

Steps to reproduce:
1. Using IE11 (not compatibility mode) or Chrome create simple tinymce box
2. With autolink plugin installed type http://www.google.co.uk
3. press space or return so that it turns into a hyperlink
4. Click on the link
5. Nothing Happens!

Expected result:
The link is followed as expected.

Actual result:
Nothing happens
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6984](http://archive.tinymce.com/develop/bugtracker_view.php?id=6984) posted by [DelboyJay](http://archive.tinymce.com/profile.php?name=DelboyJay)_

> _**Tags:** [msie chrome hyperlink ie11 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Yjeaab/1_

**Comment by adrianot** [comment]
Hi there, is there any update on this issue? 
Links are not working on both IE9 and Chrome (latest versions...).

**Comment by spocke** [comment]
That would be pretty horrible ux. All links are disabled in the editor always. If you want to use the links make a separate div with a preview or something. Closing since this is by design.

**Comment by adrianot** [comment]
Hi, I really agree with you that clicking directly could be an horrible ux. 
Anyways, the behavior sounds not consistent for all browsers, in fact if you try with Firefox it works like a charm with "Ctrl" + click. 

What do you think about extending the right-click menu like this... could provide a more consistent ux than clicking on the link itself (look attached image).

Thanks!
Cheers
![navigate](https://cloud.githubusercontent.com/assets/1771374/14354706/9bd13c0c-fcde-11e5-804f-c297f0f7be69.png)

**Comment by aiftariyani** [comment]
Hi, this issue is still remains in 4.3 https://www.tinymce.com/docs/demo/full-featured/ not at all sure why it was closed.
