### ISSUE TITLE
Ability for Table Add Row to Ignore Merged Cells

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1724]
Please add a configuration to allow merged cells to go ignored when inserting a new row into an existing table. 

Steps to Reproduce:

1). Create a 3x3 table.
2). Select cell A3 and perform a merge cells.
3). Enter the following into the Merge Cells Dialog and click Ok:
     Cells: 2
     Rows: 1
4). Select cell A3 and perform a Insert Row After.

Expected Results :

A new row be added to the table with 3 cells matching our table configuration.

Actual Results : 

A new row is added with the first two cells merged the same as the row that was selected. 

Currently there is no way to add a new row to the table without copying over the merged information. If you want a new row without merged cells you need to edit via HTML or remove the merging, and re-add the merge.

It would be nice if there was an option to disable the merge copy during row insertion. That way anyone used to the way it works now can continue as is, where we can add a setting to make it behave as we want it to. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6985](http://archive.tinymce.com/develop/bugtracker_view.php?id=6985) posted by [sonicStickMan](http://archive.tinymce.com/profile.php?name=sonicStickMan)_
> 
> _**Tags:** [table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
