### ISSUE TITLE
JQuery textarea should not be hidden when inline

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1725]
When creating an inline editor the visibility of the textarea should not be set to hidden during the initialization - this causes unnecessary flickering. In jquery.tinymce.js the visibility is set to hidden then set back to visible. This change should be avoided for inline editors the same that it is in js/tinymce/classes/Editor.js .

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6986](http://archive.tinymce.com/develop/bugtracker_view.php?id=6986) posted by [chrisaha](http://archive.tinymce.com/profile.php?name=chrisaha)_
> 
> _**Tags:** [firefox msie safari chrome opera inline jquery]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
