### ISSUE TITLE
TD in THEAD

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1726]
Description of problem:
In the plugin "table" in the "row properties" dialog, if I declare rowtype = Header, content tags "tr" rest "td". 
However, if it's a row header, I expect "th" tags.
 
Steps to reproduce:
1. Create table with many rows and many columns
2. Open "row properties" dialog
3. Set rowtype = Header for first row

Expected result:
    &ltg;table border="0" class="mce-item-table" data-mce-selected="1">
        &ltg;thead>
            &ltg;tr>
                &ltg;th>Product&ltg;/th>
                &ltg;th>Cost&ltg;/th>
                &ltg;th>Really?&ltg;/th>
            &ltg;/tr>
        &ltg;/thead>
        &ltg;tbody>
            &ltg;tr>
                &ltg;td>TinyMCE&ltg;/td>
                &ltg;td>Free&ltg;/td>
                &ltg;td>YES!&ltg;/td>
            &ltg;/tr>
            &ltg;tr>
                &ltg;td>Plupload&ltg;/td>
                &ltg;td>Free&ltg;/td>
                &ltg;td>YES!&ltg;/td>
            &ltg;/tr>
        &ltg;/tbody>
    &ltg;/table>

Actual result:
    &ltg;table border="0" class="mce-item-table" data-mce-selected="1">
        &ltg;thead>
            &ltg;tr>
                &ltg;td>Product&ltg;/td>
                &ltg;td>Cost&ltg;/td>
                &ltg;td>Really?&ltg;/td>
            &ltg;/tr>
        &ltg;/thead>
        &ltg;tbody>
            &ltg;tr>
                &ltg;td>TinyMCE&ltg;/td>
                &ltg;td>Free&ltg;/td>
                &ltg;td>YES!&ltg;/td>
            &ltg;/tr>
            &ltg;tr>
                &ltg;td>Plupload&ltg;/td>
                &ltg;td>Free&ltg;/td>
                &ltg;td>YES!&ltg;/td>
            &ltg;/tr>
        &ltg;/tbody>
    &ltg;/table>

This is not necessarily a bug. 

What do you think ?

Thanks
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6987](http://archive.tinymce.com/develop/bugtracker_view.php?id=6987) posted by [LFROTTIER](http://archive.tinymce.com/profile.php?name=LFROTTIER)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by GeertGuns** [comment]
Hi, 
I'm using TinyMCE v4.6.5 and the same issue still exists.
Could you take a look at this, please?

The generated code is as followes.  As you can see, the thead row still contains td tags in stead of th tags.

<table class="table">
<thead>
<tr>
<td>test</td>
<td>header</td>
<td>line</td>
<td> </td>
</tr>
</thead>
<tbody>
<tr>
<td>test</td>
<td>body</td>
<td>line1</td>
<td> </td>
</tr>
<tr>
<td> </td>
<td> </td>
<td>line2</td>
<td> </td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
</tr>
</tbody>
<tfoot>
<tr>
<td>test</td>
<td>footer</td>
<td>line</td>
<td> </td>
</tr>
</tfoot>
</table>


Kind regards,
Geert
