### ISSUE TITLE
After selecting multi-styled text, clicking on a word does not display the applied styles in toolbar.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1730]
Description of problem:

Steps to reproduce:
 Open compose window.
2. Type some text with different styles(eg: type a word with font name Impact and then type another word with font name Arial).
3. Select the text with different styles.
4. Click on a word.

Expected result:
Styles applied for the clicked word should be displayed in the toolbar buttons.

Actual result:
After clicking on a word, selection is removed, but the styles applied for the clicked word is not displayed in the toolbar buttons. If we click on the word again, values are displayed properly in the toolbar.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7000](http://archive.tinymce.com/develop/bugtracker_view.php?id=7000) posted by [drew](http://archive.tinymce.com/profile.php?name=drew)_

> _**Tags:** [msie msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
