### ISSUE TITLE
<div> <pre> <span> <blockquote> <ul> multi-lines selected - feature request

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1733]
Description of problem:
When selecting multiple lines, say:
&ltg;p>line 1&ltg;/p>
&ltg;p>line 2&ltg;/p>
&ltg;p>line 3&ltg;/p>

And applying a block formatting such as div, pre, span, up or blocquote, it applies on every lines and not a wrapping container.

Expected result:
&ltg;div>
&ltg;p>line 1&ltg;/p>
&ltg;p>line 2&ltg;/p>
&ltg;p>line 3&ltg;/p>
&ltg;/div>

Actual result:
&ltg;div>line 1&ltg;/div>
&ltg;div>line 2&ltg;/div>
&ltg;div>line 3&ltg;/div>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6994](http://archive.tinymce.com/develop/bugtracker_view.php?id=6994) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
