### ISSUE TITLE
Indenting text and copy & paste

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1734]
Description of problem:
Issue 1: Currently indenting text is not done in the proper way
Issue 2: Copy & Paste of indented text will loose the indent formatting.

Steps to reproduce issue 1:
1. Create 3 lines:
&ltg;p>line1&ltg;/p>
&ltg;p>line2&ltg;/p>
&ltg;p>line3&ltg;/p>
2. Select the 3 lines
3. Click on the indent button

Actual result:
&ltg;p style="padding-left: 30px;">line1&ltg;/p>
&ltg;p style="padding-left: 30px;">line2&ltg;/p>
&ltg;p style="padding-left: 30px;">line3&ltg;/p>

Expected result:
&ltg;div style="padding-left: 30px;">
&ltg;p>line1&ltg;/p>
&ltg;p>line2&ltg;/p>
&ltg;p>line3&ltg;/p>
&ltg;/div>

or possibly
&ltg;ul>
&ltg;p>line1&ltg;/p>
&ltg;p>line2&ltg;/p>
&ltg;p>line3&ltg;/p>
&ltg;/ul>

or possibly
&ltg;div class="leftIndent">
&ltg;p>line1&ltg;/p>
&ltg;p>line2&ltg;/p>
&ltg;p>line3&ltg;/p>
&ltg;/div>
and define a leftIndent css class as:
.leftIndent { padding-left: 30px; }

Reproduce issue2:
1. Copy the source output of issue 1 into a newly html file, viz:
&ltg;!DOCTYPE html>
&ltg;html>
&ltg;head>
&ltg;meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
&ltg;/head>
&ltg;body>
&ltg;p style="padding-left: 30px;">line1&ltg;/p>
&ltg;p style="padding-left: 30px;">line2&ltg;/p>
&ltg;p style="padding-left: 30px;">line3&ltg;/p>
&ltg;/body>
&ltg;/html>
1. Open the newly created file in a browser.
2. Select & copy all 3 lines from the browser
3. Paste the copy selection into tinyMCE

Actual result:
&ltg;p>line1&ltg;/p>
&ltg;p>line2&ltg;/p>
&ltg;p>line3&ltg;/p>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6995](http://archive.tinymce.com/develop/bugtracker_view.php?id=6995) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
