### ISSUE TITLE
TinyMCE 4 spell checker fails with non-breaking spaces in IE8

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1735]
Description of problem:

Steps to reproduce:
1. Spell check this paragraph:
   
   &ltg;p>There is a porblem in Internet Explorer 8.&ltg;/p>
2. Spell check this paragraph
   
   &ltg;p>There is a porblem&nbsp;in Internet Explorer 8.&ltg;/p>

Expected result:

The word 'porblem' should be detected and underlined in both instances.

Actual result:

The word 'porblem' is only detected and underlined in the first instance.

(A pull request which claimed to fix this issue in TinyMCE 3 was rejected in https://github.com/tinymce/tinymce/pull/182.)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6996](http://archive.tinymce.com/develop/bugtracker_view.php?id=6996) posted by [robtree](http://archive.tinymce.com/profile.php?name=robtree)_
> 
> _**Tags:** [msie msie8 spellchecker]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
