### ISSUE TITLE
Incorrect delete when editing text containing noneditable parts.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1736]
Description of problem:
Incorrect text is deleted when pressing backspace. 

Steps to reproduce:
1. Navigate to live test of noneditable: http://www.tinymce.com/tryit/3_x/noneditable_content.php
2. Press "html" link and replace with:&ltg;span class="mceNonEditable">greger&ltg;/span>
3. Press update
4. Add 'a' to the right of the noneditable text part.
5. Press backspace

Expected result:
The 'a' should be removed.

Actual result:
The noneditable text part is removed.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6997](http://archive.tinymce.com/develop/bugtracker_view.php?id=6997) posted by [greger](http://archive.tinymce.com/profile.php?name=greger)_

> _**Tags:** [chrome noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/3_x/noneditable_content.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
