### ISSUE TITLE
Font Size Selection Broken

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1737]
Description of problem: Choosing a font size always reverts to 8pt

Steps to reproduce:
1. Type or paste text into editor
2. Highlight text
3. Choose a font size

Expected result: Font size adjusts to selection

Actual result: Font size always falls back to 8pt font.  I am using the default font sizes.

Updated to v4.0.28 from v4.0.23 - The issue exists in both versions.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6998](http://archive.tinymce.com/develop/bugtracker_view.php?id=6998) posted by [wxwyz](http://archive.tinymce.com/profile.php?name=wxwyz)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by pjfsilva** [comment]
I tested on 4.3.12 and this is still happening. The issue only occurs when you use the legacyoutput plugin. When you do that, the font-size that gets included is always 0 no matter what option you select

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
