### ISSUE TITLE
Fonttype Webdings/Windings not working in Firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1739]
Description of problem:

Steps to reproduce:
1. Start the classic example demo on tinymce.com using Firefox 30.0
2. Select some text in editor and change font family to Windings or Webdings by using the toolbar option
3. Font will become little smaller, but will not show the character as you see for example in Chrome browser.
4.
5.

Expected result:
Font family should change

Actual result:
No change
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7003](http://archive.tinymce.com/develop/bugtracker_view.php?id=7003) posted by [vitalhealthsoftware](http://archive.tinymce.com/profile.php?name=vitalhealthsoftware)_

> _**Tags:** [firefox firefox7]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
