### ISSUE TITLE
Insert table on Tablet not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1740]
Description of problem:

Steps to reproduce:
1. Start basic demo on tinymce.com using IPad tablet.
2. From the toolbar select Insert Table and try to make a selection of the cells and columns to insert.
3. The number of cells and column chooser is not able to handle touch events from the IPad, so a table with only one cell and column is inserted.
4.
5.

Expected result:
Should be able to select number of cells and columns to insert also when using Tablet device.

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7004](http://archive.tinymce.com/develop/bugtracker_view.php?id=7004) posted by [vitalhealthsoftware](http://archive.tinymce.com/profile.php?name=vitalhealthsoftware)_

> _**Tags:** [safari chrome safari6 chrome12]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
