### ISSUE TITLE
Bug when removing noneditable blocks

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1741]
Description of problem:
I try to create an editor where the user can add non editable blocks with some editable parameters (using noneditable plugin). When removing a non editable block the non editable behavior is copied to the line underneath becomes noneditable.

Steps to reproduce:
1. Add some non editable staff to the textarea:
   &ltg;div class="mceNonEditable">
     &ltg;p>Non editable text &ltg;span class="mceEditable"> editable &ltg;/span> non editable again&ltg;/p>
   &ltg;/div>
   &ltg;p>Some text after non editable block.&ltg;/p>
2. Select non editable text by clicking on one of the non editable words (the block becomes highlighted.
3. Hit delet or backspace key
4. "Some text after non editable block." becomes noneditable.

Expected result:
  "Some text after non editable block." should stay editable and keep its style properties.

Actual result:
  "Some text after non editable block." becomes noneditable.

By the way it works fine with IE.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7005](http://archive.tinymce.com/develop/bugtracker_view.php?id=7005) posted by [Didier Nester](http://archive.tinymce.com/profile.php?name=Didier Nester)_
> 
> _**Tags:** [chrome noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Lkeaab_

**Comment by Iuriy-Budnikov** [comment]
+1

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
