### ISSUE TITLE
Add :focus style for special character selector

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1743]
When using keyboard in special character dialog I can't see which character is already selected. Please add :focus style.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7009](http://archive.tinymce.com/develop/bugtracker_view.php?id=7009) posted by [alec](http://archive.tinymce.com/profile.php?name=alec)_
> 
> _**Tags:** [accessibility]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
