### ISSUE TITLE
Chrome remove line breaks fonts

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1744]
Description of problem:
When you put 2 new lines (2 empty lines) in chrome and then delete one of them. All span styles are removed from the previous one as well.

Steps to reproduce:
1. Open TinyMCE with current font as IMPACT
2. Before typing change font to Courier New
3. Type a few letters to see it IS in Courier New
4. Put 2 empty new lines in.
5. Delete one of the 2 new lines.
6. Type some and you will see IMPACT instead of Courier new

Expected result:
Font should remain as courier new until it is changed again.

Actual result:
Font reverts back to whatever it was at the beginning because the &ltg;span> tag containing the new font gets deleted and causes the default font in the &ltg;p> tag to take over again.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7010](http://archive.tinymce.com/develop/bugtracker_view.php?id=7010) posted by [unilaterus](http://archive.tinymce.com/profile.php?name=unilaterus)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
