### ISSUE TITLE
Attribs button from xhtmlxtras in TinyMCE 4.x

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1746]
In TinyMCE 3.x there's the attribs control from the xhtmlxtras plugin that allows assigning classes and ids to html elements. This plugin is no longer supported with TinyMCE 4.x. We'd like the attribs button (or similar) to be made available for TinyMCE 4.x aswell.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7017](http://archive.tinymce.com/develop/bugtracker_view.php?id=7017) posted by [ccmprofessional](http://archive.tinymce.com/profile.php?name=ccmprofessional)_
> 
> _**Tags:** [attribs xhtmlxtras]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
