### ISSUE TITLE
Media plugin in TinyMCE 4.x does not include options for flash

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1748]
In TinyMCE 3.x it was possible to add videos of varying types including flash. In TinyMCE 4.x the dialog to insert a video will only generate html5 video tags, it does not include options for generating objects with flash.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7018](http://archive.tinymce.com/develop/bugtracker_view.php?id=7018) posted by [ccmprofessional](http://archive.tinymce.com/profile.php?name=ccmprofessional)_
> 
> _**Tags:** [media flash]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
