### ISSUE TITLE
getContent() removes subscript

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1752]
Description of problem:

Steps to reproduce:
1. Start tinymce editor having subscript option in toolbar
2. first enter character x
3. then press "substript" button from toolbar
4. now press character "y"
5. The html in editor is now: x
&ltg;span id="_mce_caret" data-mce-bogus="1">
&ltg;sub>y&ltg;/sub>
&ltg;/span>
&ltg;br data-mce-bogus="1">&ltg;p>
6. Now call getContent() of on the editor. This will return:
&ltg;p>xy&ltg;/p>

Expected result:
it should not remove the &ltg;sub> element
Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7014](http://archive.tinymce.com/develop/bugtracker_view.php?id=7014) posted by [vitalhealthsoftware](http://archive.tinymce.com/profile.php?name=vitalhealthsoftware)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
