### ISSUE TITLE
Both undo/redo buttons gets disabled

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1753]
Description of problem:

Steps to reproduce:
1. Start basic example on tinymce.com
2. press ctrl + a to select all text in editor and press delete to clean editor content
3. type a letter like "x"
4. press undo button
5. when not having focus on editor content area press again a letter like "x", then you see both undo and redo buttons getting disabled.

Expected result:
At least one button should be enabled.

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7015](http://archive.tinymce.com/develop/bugtracker_view.php?id=7015) posted by [vitalhealthsoftware](http://archive.tinymce.com/profile.php?name=vitalhealthsoftware)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
