### ISSUE TITLE
I noticed a small inaccuracy

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1759]
Hello! Lately, I noticed a small inaccuracy in the pictogram in the TinyMCE editor. Pictogram that the screenshot, has the same form every time. I think if editor deployed full, pictogram should take the form arrow going from the edges to the center. And if editor deployed not full, pictogram should take the form arrow going from the center to the edges.

P.S. Sorry for the my bad English language.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7033](http://archive.tinymce.com/develop/bugtracker_view.php?id=7033) posted by [Manzick](http://archive.tinymce.com/profile.php?name=Manzick)_
> 
> _**Tags:** [inaccuracy]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
