### ISSUE TITLE
Adding horizontal rules can result in newlines above and below

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1763]
Description of problem:
Adding a horizontal ruler can create a lot of white space.

Steps to reproduce:
1. Ensure that empty p elements will be filled (validated_elements, #p[*] or something like that)
2. Create a file a line containing "one", nothing and "two"
3. Save the file, open it again, go to line nothing, by clicking on the line (Your cursor should then be behind the non breaking white space of that line)
4. Insert a hr element in the empty line.
5. Save the document

Expected result:

A horizontal ruler with either an empty line above or below.

Actual result:

A horizontal ruler with an empty line above AND below.

It seems that the non breaking white space is interpreted as real content which gets pushed into its own paragraph above, while Tiny still recreates an empty paragraph below the hr.

The linked fiddle does not allow for saving, but as explained in the description, one can see the erroneous behaviour by looking at the generated html.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7026](http://archive.tinymce.com/develop/bugtracker_view.php?id=7026) posted by [do3cc](http://archive.tinymce.com/profile.php?name=do3cc)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/vneaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
