### ISSUE TITLE
not work property selected in listbox values item

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1766]
Description of problem:

"selected" property in values of listbox element does not work, when creating listbox with windowManager.open

Steps to reproduce:
1. click the plugin button
2. look at the listbox element

Expected result:
the 2-nd option in listbox is checked

Actual result:
1-st option is allways checked

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7040](http://archive.tinymce.com/develop/bugtracker_view.php?id=7040) posted by [death_1989](http://archive.tinymce.com/profile.php?name=death_1989)_
> 
> _**Tags:** [firefox chrome listbox selected]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/doeaab/5_

**Comment by mattan138** [comment]
The issue still remains as of 12/4/2016 using TinyMCE v4.

A current workaround is to use onPostRender and set the selected value to with the value() function.

Example:
```
{
	type: 'listbox',
	name: 'text',
	values: [
		{text : '1', value : '1'},
		{text : '2', value : '2'},
		{text : '3', value : '3'}
	],
	onPostRender: function() {
		this.value('2');
	}
}
```

I was searching around for a solution and came across this page as I figured out an alternative method to accomplish this.

**Comment by fyrkant** [comment]
@mattan138's solution works but so does setting the `value` property on the listbox like this: http://fiddle.tinymce.com/doeaab/7

Closing this issue as it seems to work using the ways explained above.
