### ISSUE TITLE
FontAwesome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1772]
Description of problem:
I'm trying to insert FontAwesome icon into editable area.

---

Steps to reproduce (method #1):
1. Use editor.execCommand('mceInsertContent', false, '&ltg;span class="font-family: FontAwesome;">&#xf080;&ltg;/span>');

Result (method #1):
1. Icon appears but when it's dragged around the text area it disappears (the &ltg;span> element is removed).
2. When trying to type text in between two icons, it appears inside of the &ltg;span> element.

---

Steps to reproduce (method #2):
1. Use editor.execCommand('mceInsertContent', false, '&ltg;span class="fa fa-arrow-up">&ltg;/span>');

Result (method #2):
1. Icon appears but it's not possible to drag it around.
2. It's not possible to position caret before it (it appears inside of the &ltg;span> element).
3. It's not possible to move it freely and create paragraphs before and after that icon.
4. Two &ltg;span> elements can be merged together resulting in disappearance of one icon.
5. It doesn't react to keyboard arrows correctly.

---

Steps to reproduce (method #3):
1. Use editor.execCommand('mceInsertContent', false, '&ltg;div class="fa fa-arrow-up" style="display: inline-block; width: 20px; height: 20px;">&ltg;/div>');

Result (method #3):
1. It's not draggable so it's probably another wrong method of doing it.

---

Expected result: Is there some way to insert FontAwesome icons in text and have it working correctly with mouse dragging and keyboard? Probably as symbol (same like in charmap plugin) or new &ltg;span> or &ltg;div>? Icons: http://fortawesome.github.io/Font-Awesome/cheatsheet/

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7049](http://archive.tinymce.com/develop/bugtracker_view.php?id=7049) posted by [Trevlon](http://archive.tinymce.com/profile.php?name=Trevlon)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by andrewnleon** [comment]
I have this issue, my fa classes and elements dont get erased but tincy mce does not render them.
