### ISSUE TITLE
tinyMCE 4.1 in RTL browser lines up incorrectly

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1773]
Description of problem: in an HTML page that is RTL (Hebrew), under chrome - the scroll bar is on the left, but there is room allocated on the right for it.

Steps to reproduce:
1.create a site where the page is RTL (HTML should have dir="rtl" tag in it.
2.place a text edit and tinyMCE 4 and up
3. Run chrome
4.enter text into the box so that it adds a scroll bar.
5.scroll bar is on the left (should be on the right).

Expected result: scroll bar should be on the right.

Actual result: scroll bar is on the left, but there's space for it on the right (as if there are 2 scrollbars)...

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7034](http://archive.tinymce.com/develop/bugtracker_view.php?id=7034) posted by [oferlaor](http://archive.tinymce.com/profile.php?name=oferlaor)_

> _**Tags:** [chrome chrome13]_
> _**Status:** Open_
> _**Resolution:** Wont Fix_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
