### ISSUE TITLE
embedded youtube inside the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1774]
I would like the option for placing youtube links and they would automatically convert into fullblown integrated player.

Also, when showing this player (as an IFRAME), I would like to see it fully formed inside the editor.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7035](http://archive.tinymce.com/develop/bugtracker_view.php?id=7035) posted by [oferlaor](http://archive.tinymce.com/profile.php?name=oferlaor)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
