### ISSUE TITLE
3.5.8 Links popup fields empty when editing link

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1779]
With Tinymce 3.5.8 (I also tried with 3.5.11) used in Xoops CMS a problem occurs only with IE ... 

When editing existing links (and images) the fields in the popup are empty ! No way to modify links ...

In Firefox no problem.

Experienced on 2 different computers:
- IE11 + windows 7
- IE9 + windows Vista

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7054](http://archive.tinymce.com/develop/bugtracker_view.php?id=7054) posted by [lionhellll](http://archive.tinymce.com/profile.php?name=lionhellll)_
> 
> _**Tags:** [msie msie9 msie10 links popup fields empty]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
