### ISSUE TITLE
image url changed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1783]
Description of problem: full url to image entered (http://www.sftradjazz.org/images/image.jpg) gets truncated to ../images/image.url

Steps to reproduce:
1. Page with textarea is  http://www.sftradjazz.org/Database/sendemail.php
2. Image files are in http://www.sftradjazz.org/images
3. Textarea creates email sent from code in http://www.sftradjazz.org/Database/
4. Image appears in tinyMCE preview but does not appear (broken link) in email.
5.

Expected result: &ltg;img src="http://www.sftradjazz.org/images/image.jpg">

Actual result: &ltg;img src="../images/image.jpg">

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7058](http://archive.tinymce.com/develop/bugtracker_view.php?id=7058) posted by [santhony94044](http://archive.tinymce.com/profile.php?name=santhony94044)_

> _**Tags:** [firefox msie safari chrome opera url image]_
> _**Status:** Closed_
> _**Resolution:** Duplicate_
> _**Attached URL:** none_

**Comment by sturzl** [comment]
If you run into this issue, here is the other bug: https://github.com/tinymce/tinymce/issues/1794
