### ISSUE TITLE
Events tab in links popup

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1789]
It seems events tab doesn't exist any more in Tinymce 4 ... a pity !
Is it possible to active it in some way ? If not how to recover this tab ?

Thx

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7053](http://archive.tinymce.com/develop/bugtracker_view.php?id=7053) posted by [lionhellll](http://archive.tinymce.com/profile.php?name=lionhellll)_
> 
> _**Tags:** [firefox msie safari chrome opera links tab popup events]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
