### ISSUE TITLE
Inline-Mode: tinymce overlays fixed header

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1799]
Description of problem:
I have a layout with a fixed header toolbar.
When using inline mode, tinymce overlays the fixed element, even if the element beeing edited is behind the fixed toolbar.

see fiddle

Steps to reproduce:
1. open jsfiddle
2. split the view vertically (instead of the horizontal default)
3. click on "tiny content" to open tiny
4. scroll the page down

Actual result:
-> the element beeing edited hides behind the fixed toolbar, but the tinymce controls are shown above the fixed toolbar element.

Expected result:
the tinymce controls should stick above or below the fixed toolbar, but should not overlay it (except the element beeing edited is within the fixed toolbar)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7103](http://archive.tinymce.com/develop/bugtracker_view.php?id=7103) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Treaab/1_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
