### ISSUE TITLE
Forced_root_block doesn't work in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1800]
Running the attached fiddle in IE, doesn't respect the forced_root_block: false in a certain case and will add a p tag.  

Steps to reproduce:
1. Using IE, type in the editor the five characters: abcde
2. Hit backspace 5 times to remove all the characters
3. A p tag will be inserted when it should not

Pressing backspace a 6th time will remove the p tag but that should not be necessary.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7066](http://archive.tinymce.com/develop/bugtracker_view.php?id=7066) posted by [scottchantry](http://archive.tinymce.com/profile.php?name=scottchantry)_

> _**Tags:** [msie msie10 forced_root_block msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Loeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
