### ISSUE TITLE
tab-table, table-tab function

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1802]
Subject: Tables
Sub-subject: Conversion of tabs to tables, and vice-versa.

Function: The ability to convert tabs to tables and back again. Would allow the user to set text in a series of tabs, and then convert that to a table instead of inserting a table and adding content to that.

Would make my life easier. :)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7074](http://archive.tinymce.com/develop/bugtracker_view.php?id=7074) posted by [mythusmage](http://archive.tinymce.com/profile.php?name=mythusmage)_
> 
> _**Tags:** [chrome chrome13 tabs tables conversion]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
