### ISSUE TITLE
Control-click on Mac does not bring up contextual menu in TinyMCE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1806]
Description of problem:
Using control-click in a Mac browser (tested so far in Chrome and Firefox) does not bring up the contextual menu in TinyMCE. This should be treated the same as a right click event.

Steps to reproduce:
1. Bring up a page with a TinyMCE editable field (that has the contextual menu plugin enabled)
2. Control click within the editor

Expected result:
Contextual menu should appear, the same as if you right clicked

Actual result:
The right click menu provided by the browser shows up instead of the contextual menu
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7070](http://archive.tinymce.com/develop/bugtracker_view.php?id=7070) posted by [cdaveb](http://archive.tinymce.com/profile.php?name=cdaveb)_

> _**Tags:** [firefox msie safari chrome opera mac]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
