### ISSUE TITLE
Paste from Word: sibling list content gets merged into first list

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1807]
Description of problem:
See the attached Word document for an example of the content to test this issue with. When pasting from word, if there's a series of ul/ol lists separated by headings, all the list content gets merged into the list that appears under the first heading. The same happens with lists within table-rows.

Steps to reproduce:
1. Open tinyMCE editor in any webkit browser
2. With the 'paste' plugin active, paste the content from the attached MS word document.
3. Observe that the first three lists get merged into one. The same happens with the lists within the cells of a table row. An example of this can be seen in the PNG.

Expected result:
Lists are present in their original position in the layout.

Actual result:
The lists that appeared under headings all get merged into one large list under the first heading. Lists that appeared under paragraphs are fine however.

Note that on IE, lists within cells of a table-row also get merged, so this occurs on all browsers.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7071](http://archive.tinymce.com/develop/bugtracker_view.php?id=7071) posted by [amaccann](http://archive.tinymce.com/profile.php?name=amaccann)_

> _**Tags:** [firefox msie safari chrome opera webkit word 4x 3x paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
