### ISSUE TITLE
tiny mce adding additional  <ul> tag

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1811]
Tiny MCES is adding extra &ltg;ul> tag directly inside &ltg;ul> tag which is is not as per w3 standards . How to fix this issue. 

Expected result:

 &ltg;ul>

 &ltg;li>abc&ltg;/li>

&ltg;li>def&ltg;/li>

&ltg;/ul>

Actual result:
 &ltg;ul>

 &ltg;li>abc&ltg;/li>
&ltg;ul>
&ltg;li>def&ltg;/li>
&ltg;/ul>
&ltg;/ul>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7075](http://archive.tinymce.com/develop/bugtracker_view.php?id=7075) posted by [vimala](http://archive.tinymce.com/profile.php?name=vimala)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
