### ISSUE TITLE
Floating tags break selection by double-click

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1814]
Description of problem:
Selecting by double click, and merging/cleanup behavior break when external css floats the tags.

Steps to reproduce:
1. Add a content_css file on init defining some floated items. background color will help.
2. Double-click a word

Expected result:
Only the clicked word should be selected.

Actual result:
The whole grand-parent tag is selected. No boundary is recognized.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7079](http://archive.tinymce.com/develop/bugtracker_view.php?id=7079) posted by [sergiozambrano](http://archive.tinymce.com/profile.php?name=sergiozambrano)_

> _**Tags:** [safari chrome safari6 chrome13 selection float block tag bug edit merge]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/xpeaab/5_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
