### ISSUE TITLE
Compressor doesn't determine correct baseURL if loaded via ajax.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1815]
Description of problem:
If I load tinymce.gzip.js via jQuery's $.getScript(), it will not properly load the corresponding tinymce.gzip.php file. 

Steps to reproduce:
1. $.getScript('http://localhost/js/vendor/tinymce/tinymce.gzip.js');

Expected result:

tinymce.gzip.js will load http://localhost/js/vendor/tinymce/tinymce.gzip.php?js=true&themes=modern

Actual result:

tinymce.gzip.js tries to load http://localhost/undefined/tinymce.gzip.php?js=true&themes=modern

It's apparent why it's failing based on the code used @ https://github.com/tinymce/tinymce_compressor/blob/master/tinymce.gzip.js#L154. (The $.getScript() method does not append the script to the page as a script element). 

What I think should be available is a method to pass in the baseURL that could be used when tinymce.init is called - 

My work around is to initialize tinymce after injecting the correct baseURL. 

tinymce.baseURL = 'js/vendor/tinymce';
tinymce.init({config});

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7080](http://archive.tinymce.com/develop/bugtracker_view.php?id=7080) posted by [aknosis](http://archive.tinymce.com/profile.php?name=aknosis)_
> 
> _**Tags:** [firefox msie safari chrome opera compressor jquery tinymce4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
