### ISSUE TITLE
Less than symbol truncating text 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1818]
Description of problem: If user enters Less than (&ltg;) symbol in TinyMCE editor followed by some text. All the text after after Less than inclusing &ltg; will be truncated or not rendered

Steps to reproduce:
1.Open Source code for Tiny MCE text Field
2.Paste "&ltg;p>Test Comparison  A&ltg;5 &ltg;/p>"
3.Press OK
4. Check Text on TimyMCE editor

Expected result:
Test Comparison A&ltg;5

Actual result:

Test Comparison A

Here &ltg;5 from text is missing

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7084](http://archive.tinymce.com/develop/bugtracker_view.php?id=7084) posted by [RV](http://archive.tinymce.com/profile.php?name=RV)_

> _**Tags:** [firefox msie safari chrome opera symbol]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by toddmay1** [comment]
Have a similar issue where users are attempting to enter a LESS THAN 3 as a shortcut for a feeling or expression.    

In my description I am typing everything out so this editor doesn't hack it up... What I am seeing is the standard HTML escape for a less than symbol that one would expect.  But tinymce truncates everything after it.

Issue:
When a user types "Marry had a little LESSTHAN3 lamb." into TinyMCE, it appears correctly.

When this is saved, it's inserted into database as ampersand LT semicolon (expected outcome).

Issue is... When the data is rendered back in html it contains AMPERSANDlt; and tinyMCE will truncate everything at the AMPERSANDlt; and everything after until it reaches a newline.

**Comment by spocke** [comment]
Make sure you properly encode the textarea contents. &amp;gt; not &gt; for < inside text.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by naazy** [comment]
We're currently having the same issue 😢  - anyone manage to resolve it?
