### ISSUE TITLE
Space in empty paragraph is navigatable

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1820]
When working in TinyMce with empty paragraphs a bogus &ltg;br> element is inserted. Once we save the contents of TinyMce these elements get replaced by &nbsp;. 

Now upon loading the same content again I would expect the &ltg;p>&nbsp;&ltg;/p> element to be replaced again by the &ltg;p>&ltg;br class="mce-bogus">&ltg;/p> again. 

Because this is not the case you actually see the whitespace character in the TinyMce editor. Thus before removing or using the empty paragraph you will need to remove it. You can see this behaviour in the JsFiddle http://fiddle.tinymce.com/vqeaab

Thus: I would expect TinyMce to replace &ltg;p>&nbsp;&ltg;/p> elements by &ltg;p>&ltg;br class="mce-bogus">&ltg;/p>.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7085](http://archive.tinymce.com/develop/bugtracker_view.php?id=7085) posted by [roelvd](http://archive.tinymce.com/profile.php?name=roelvd)_

> _**Tags:** []_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/vqeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
