### ISSUE TITLE
Undo- / Redo-Button only works partially on empty content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1821]
Description of problem:
Undo- / Redo-Buttons only works partially in Chrome 36 / IE 11 / FF 30.

Steps to reproduce:
1. Open a new form with empty tinymce
2. type in some text
3. expand the button bar which contains the redo-button
4. click the redo-button -> nothing happened

1. Open a new form with empty tinymce
2. type in some text
3. click the undo-button (button-bar is already expanded) -> works!
4. click the redo-button -> nothing happened

Expected result:
Both Undo-/Redo-Button add/delete added/removed content.

Actual result:
Undo-/Redo-Button only works partially in modern browser with tinymce v. 3.4.7. IE9 tested and works like a charm.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7086](http://archive.tinymce.com/develop/bugtracker_view.php?id=7086) posted by [mscdev](http://archive.tinymce.com/profile.php?name=mscdev)_

> _**Tags:** [firefox msie chrome undo redo 347 empty works partially 3x 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
