### ISSUE TITLE
Forced root block of div prevents cursor exiting table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1823]
Description of problem:
When using a forced root block of div, if you insert a table into an empty TinyMCE document, then type in a cell and attempt to move your cursor out of the table, it will not click on the area outside the table. This is reproducible in TinyMCE 4.1.3 on Firefox and MSIE but not in Chrome.

It appears that when using a forced root block of div, there is a div inserted around the new table created when a table is inserted. When using a forced root block of p, it does not put a p around the table but puts one below. This prevents the weird behavior with the cursor getting stuck. I'm not sure why it's trying to put a div around a table though as it's essentially a block type element

Steps to reproduce:
1. Go to an empty TinyMCE editor with the following configuration:

tinymce.init({
    plugins : "table",
    forced_root_block: 'div',
    selector: "textarea"
});

2. Insert a 5x5 table
3. Click inside a cell and type abcde
4. Attempt to click below the table

Expected result:

Cursor should appear below the table

Actual result:

Cursor does not move

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7087](http://archive.tinymce.com/develop/bugtracker_view.php?id=7087) posted by [cdaveb](http://archive.tinymce.com/profile.php?name=cdaveb)_

> _**Tags:** [firefox msie table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Iqeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
