### ISSUE TITLE
Losing <title> & <style> content in refresh while body content is kept

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1824]
Description of problem:
Tinymce 4.1.3 (I think this behaviour is new since 4.1)

Steps to reproduce:
1. As source code:
   &ltg;!DOCTYPE html>
   &ltg;html>
   &ltg;head>
   &ltg;meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   &ltg;title>Not kept&ltg;/title>
   &ltg;style type="text/css">
   .redBorder { border: 3px solid rgb(255,0,0); }
   &ltg;/style>
   &ltg;/head>
   &ltg;body>
   &ltg;p class="redBorder">dfdkf&ltg;/p>
   &ltg;/body>
   &ltg;/html>
2. Go to the browser (Chrome 36) url of tinymce and click return to refresh the editor
3. On browser prompt: select "leave current page"
4. Tinymce editor is there with the html body content, while all header content is gone.

Expected result:

Header content is stays.

Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7096](http://archive.tinymce.com/develop/bugtracker_view.php?id=7096) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
