### ISSUE TITLE
OL ordered list issue when applying from styles dropdown on selected text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1826]
Description of problem: OL ordered list issue when applying from styles dropdown on selected text

Steps to reproduce:
1.Type/Copy some unformatted text in editor
2.Apply ListNumbered custom style from the dropdown on first two lines.
3.Apply ListNumbered2 custom style from the dropdown having different list-type.
4.Text gets merged with same style as listnumbered2 for all li's before or after the selected text in step 3.

Expected result: (ListNumber1, ListNumber2, ListNumber3)
1. Bullet List 1.0
2. Bullet List 1.1
3. Bullet List 1.2
   a. Bullet List 2.0
   b. Bullet List 2.1
   c. Bullet List 2.2

Actual result: If 
1. Bullet List 1.0
2. Bullet List 1.1
3. Bullet List 1.2
   d. Bullet List 2.0
   e. Bullet List 2.1
   f. Bullet List 2.2

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7099](http://archive.tinymce.com/develop/bugtracker_view.php?id=7099) posted by [vkathunia](http://archive.tinymce.com/profile.php?name=vkathunia)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
