### ISSUE TITLE
maximizable and resizable not supported by windowManager

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1827]
Description of problem:
maximizable and resizable doesn't seem to be implemented as an argument in windowManager.open()

Steps to reproduce:
1. Modify a plugin or open a new window via windowManager.open with the resizable or maximizable option set to true
2. Notice that the dialog opens fine, but no maximize or resize options is visible

Expected result:
A resize handle should be present and a maximize button should be displayed.
According to the comments in tinymce/classes/WindowManager.js (dev version), this should be implemented

Actual result:
A normal dialog appears without any of the above. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7089](http://archive.tinymce.com/develop/bugtracker_view.php?id=7089) posted by [Wertisdk](http://archive.tinymce.com/profile.php?name=Wertisdk)_
> 
> _**Tags:** [firefox msie safari chrome opera windowmanager dialog maximizable resizable tinymce4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Mqeaab_

**Comment by chadcallahan** [comment]
+1 for maximize/fullscreen support.

**Comment by chadcallahan** [comment]
For those in need of fullscreen support, I implemented a fullscreen config feature for a codemirror tinymce plugin (https://github.com/christiaan/tinymce-codemirror/commit/a5929634225df8bd48b9f301534c8d62acb74758). While it isn't exactly the "maximizable" feature, it may work for some use cases. One could easily modify it a bit to add a maximize/restore button to their plugin.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
