### ISSUE TITLE
Spellchecker does not work in 4.1.3

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1829]
Description of problem:  When trying to invoke the spellchecker on 4.1.3, a 404 not found error comes up.  I went to the help page and it said to download the latest version which I did, and then go in and edit the config.php file which does not exist

Steps to reproduce:
1.  Type some text in the editor
2.  Click spellcheck
3.
4.
5.

Expected result:  For it to show me the typos or tell me no misspellings found

Actual result:  Error 404

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7101](http://archive.tinymce.com/develop/bugtracker_view.php?id=7101) posted by [harleycodr](http://archive.tinymce.com/profile.php?name=harleycodr)_

> _**Tags:** [firefox msie safari chrome opera spellchecker]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
