### ISSUE TITLE
Support for maxlength attribute

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1830]
'maxlength' attribute is not honoured, nor is there a way to define in the init parameters.  Using tinyMCE 4.1.3

Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7091](http://archive.tinymce.com/develop/bugtracker_view.php?id=7091) posted by [jonathanbaird](http://archive.tinymce.com/profile.php?name=jonathanbaird)_
> 
> _**Tags:** [firefox msie safari chrome opera maxlength]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
