### ISSUE TITLE
Cut & paste fails while copy & paste OK

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1832]
Description of problem:
Tinymce 4.1.3
Cut hyperlink & paste in table does not copy the hyperlink

Steps to reproduce:
1. Paste this in source code:
&ltg;ul>
&ltg;li>&ltg;a href="http://www.google.com">Google&ltg;/a>&ltg;/li>
&ltg;/ul>
&ltg;p>Cut &amp; paste below&ltg;/p>
&ltg;p>�&ltg;/p>

2. Select the "Google" hyperlink and cut it (CRTL X) and paste it below the text "Cut & paste below".

3. Only displayed content is copied

4. Compare with copy & paste procedure vs cut & paste

Thanks.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7095](http://archive.tinymce.com/develop/bugtracker_view.php?id=7095) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_

> _**Tags:** [cut hyperlinks]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by bpiec** [comment]
Fiddle: http://fiddle.tinymce.com/yufaab/2
Please follow instructions you can find there.

Browser in which it doesn't work: the latest version of Chrome.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
