### ISSUE TITLE
Inline-Mode: conditionally rendered (:hover) elements, toolbar jumpy

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1834]
Description of problem:
When editing a element which is only visible when another element is hovered (e.g. within a fly-out navi) and the elment gets hidden (because you no longer hover the element which makes it appear) things go crazy.

Since the toolbar is still visible but the element beeing edited isn't click on one button of the toolbar makes the toolbar beeing reposition at the top of the window.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7106](http://archive.tinymce.com/develop/bugtracker_view.php?id=7106) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/vseaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
