### ISSUE TITLE
save plugin: cancel button should close the toolbar

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1837]
I would expect that when clicking the "cancel" button of the toolbar, that tinymce will be disabled/disappear after the cancellation was confirmed.

If you don't think this should be the default it should at least be an option.
ATM the cancel button only restores the content but does not close the editor. This leads to confusion in "inline mode"

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7108](http://archive.tinymce.com/develop/bugtracker_view.php?id=7108) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
