### ISSUE TITLE
Cannot backspace over tags

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1838]
Description of problem:
Accidental enter press causes &ltg;p>&ltg;/p> tag that cannot be backspaced or deleted out. Have to edit code.

Steps to reproduce:
1.Create Table
2.Add data
3.Press enter after any added data
4.Backspace the "enter" to remove extra space that was added to cells
5.

Expected result: Expect backspace to remove the added space to the cells

Actual result: Keeps extra space in cells. Have to edit html code to remove &ltg;p> tag

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7109](http://archive.tinymce.com/develop/bugtracker_view.php?id=7109) posted by [casikmar](http://archive.tinymce.com/profile.php?name=casikmar)_
> 
> _**Tags:** [firefox msie firefox7 msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/1seaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
