### ISSUE TITLE
DIVs not working properly

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1840]
Description of problem: "Wrapper" DIV does not wrap all content as shown in the HTML. Also, pressing enter inside a DIV creates a new DIV thus ignoring the container div.

Steps to reproduce: 
1. Create Wrapper DIV (contains all content and images)
2. Create Content DIV (left side content)
3. Create Sidebar DIV (right side content)
4. Add border to each to see that wrapper is not containing all content
5. Place cursor in Sidebar DIV and press Enter to see a new div is created instead of just adding a paragraph in the sidebar DIV.

Expected result: Wrapper should contain all page content. Pressing enter in a DIV should create a paragraph tag inside the DIV

Actual result: Wrapper is not holding all content. Other DIVs being created when trying to add data to an existing DIV.

Source Code: (added borders to illustrate the anomalies. 

&ltg;div id="wrapper" style="background-color: #ffffff; border: 1px solid black; height: 100%; width: 1330px; position: relative;">
&ltg;div id="content" style="background-color: #ffffff; border: 1px solid black; height: 100%; width: 600px; float: left; padding: 0 10;">&ltg;br />
&ltg;p>Describe problem here&ltg;/p>
&ltg;p>&nbsp;&ltg;/p>
&ltg;hr />
&ltg;p>&nbsp;&ltg;/p>
&ltg;p>&ltg;strong> Instructions:&ltg;/strong>&ltg;/p>
&ltg;p>Describe solution here&ltg;/p>
&ltg;/div>
&ltg;div id="sidebar" style="background-color: #ffffff; border: 1px solid black; height: 100%; width: 700px; float: left;">&nbsp;&ltg;/div>
&ltg;/div>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7110](http://archive.tinymce.com/develop/bugtracker_view.php?id=7110) posted by [casikmar](http://archive.tinymce.com/profile.php?name=casikmar)_
> 
> _**Tags:** [firefox msie firefox7 msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/2seaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
