### ISSUE TITLE
Text for link with href like 'www.nieuws.nl/bla' and text like 'nieuws.nl'  is changed to 'nl'.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1841]
Description of problem:

After copying a text and pasting it in TinyMCE, text has been removed from it. For now, only reproduced in Firefox (tested in 24.5.0, 24.7.0, 30.0.0 and 31.0.0). Tested on TinyMCE 4.1.3.

Steps to reproduce:
1. Load the attached HTML in Firefox.
2. Select all text in the HTML
3. Go to http://www.tinymce.com/tryit/basic.php 
4. Paste the copied text in the TinyMCE editor.

Expected result:

The text as shown in the HTML, including links, is shown in the TinyMCE editor.

Actual result:

In the text are links with the text 'Nieuws.nl' and URL 'www.nieuws.nl/blabla'. Those texts are altered to 'nl'.

Notes:
- Pasting in i.e. Chrome seems to give the same wrong result when copied from Firefox. Perhaps copying from Firefox behaves differently than copying from i.e. Chrome.
- In an older TinyMCE, the link text doesn't get altered (tested on version 3.x on http://www.tinymce.com/tryit/3_x/full.php )

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7104](http://archive.tinymce.com/develop/bugtracker_view.php?id=7104) posted by [Mondane](http://archive.tinymce.com/profile.php?name=Mondane)_
> 
> _**Tags:** [firefox link copy paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
