### ISSUE TITLE
Cell width not taken into account

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1842]
Description of problem:

If I use the table cell properties to set the width of a column, the first time my value is taken into account.

After it is not possible to change the value. In the advanced tab of the popup, the style="width:??" is always the first value. If I submit the content, it is the first value that is submitted.

If I change the value in the advanced tab, it is ok if I submit, however TinyMCE does not draw the table with this new value (after changing in the advanced tab).

Steps to reproduce:
1. Create a table with several cells
2. Edit the width of a cell using the cell properties popup
3. Edit again the same cell, set a new width
4. Edit again the same cell, the style value in the advanced tab is the first value
5. Submit TinyMCE, the value of the cell is the first value

Expected result:

The cell width must be updated each time.

Actual result:

The cell width is updated only the first time. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7105](http://archive.tinymce.com/develop/bugtracker_view.php?id=7105) posted by [eyecanseeyou](http://archive.tinymce.com/profile.php?name=eyecanseeyou)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
I believe this is a duplicate of #1878. Could you please take a look and let us know if you disagree? Thanks,
Millie @ TinyMCE

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by j3rbr0wn** [comment]
Check your TinyMCE init for the `invalid_styles` option - this will strip out any inline styles applied by the user in TinyMCE source code.

https://www.tiny.cloud/docs/configure/content-filtering/#invalid_styles
