### ISSUE TITLE
dirty-state css class

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1843]
like the mce-edit-focus class which gets added when the editor has focus, it would be great to have a mce-dirty class which indicates that the editor contains unsafed changes.

this can later on be used to make this unsaved-state more visible to the end-user.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7112](http://archive.tinymce.com/develop/bugtracker_view.php?id=7112) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
