### ISSUE TITLE
Inline-Mode: toolbar right aligned on element which cover the whole page width

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1845]
I was not able to reproduce it in a jsfiddle, but I have this problem in 2 websites.

we are using tiny in inline-mode and sometimes we see the issue that the toolbar is rendered right aligned, although the element span over the whole page.

I would expect that the toolbar would be left aligned in such cases, see screenshot.

tested with tiny from CacheflyCDN(4.1.3 I think)
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7113](http://archive.tinymce.com/develop/bugtracker_view.php?id=7113) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_

> _**Tags:** [firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
