### ISSUE TITLE
Docs: Missing infos about using tinymce jquery bundle via CDN

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1847]
tinymce.com only describes how to use tiny as a standalone, but not how to do it when you need/like to use the jquery bundle.

Cachefly provides the plugin via
https://tinymce.cachefly.net/4.1/jquery.tinymce.min.js

so you need to include 2 files from the cdn.
https://tinymce.cachefly.net/4.1/tinymce.min.js
https://tinymce.cachefly.net/4.1/jquery.tinymce.min.js

you need to make sure that tinymce is loaded _before_ the jquery plugin

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7115](http://archive.tinymce.com/develop/bugtracker_view.php?id=7115) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_
> 
> _**Tags:** [docs]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
