### ISSUE TITLE
URL conversion not working for inline editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1851]
Description of problem:
When I set up URL conversion for an inline editor it is not working as expected. When I set the 'inline' setting to FALSE it works fine.

Steps to reproduce:
1. Go to fiddle http://fiddle.tinymce.com/Xseaab/12 (By default 'inline' is set to false in this fiddle)
3. Open image dialog and click on file browser button. The input field will get the value "logo.png".
4. Click OK to close dialog. The logo will display.
5. Now change 'inline' setting to true.
6. Rerun the fiddle and repeat steps 3 and 4. The logo wil NOT display.

Expected result:
The URL of the selected image is converted in the inline editor so it will display correctly (like it does if 'inline' is set to false).

Actual result:
When 'inline' is set to true, the URL is not converted correctly. The client tries to open the url "http://fiddle.tinymce.com/logo.png" instead of "http://fiddle.tinymce.com/images/logo.png".

The issue can be resolved by setting 'document_base_url' to "http://fiddle.tinymce.com/" and change the returned value of the file_browser_callback function to "images/logo.png". However, in my case the file browser returns "logo.png" and that's the way it should be shown in the image dialog and be stored in the DB (because of applications not running on document root).

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7119](http://archive.tinymce.com/develop/bugtracker_view.php?id=7119) posted by [neoc83](http://archive.tinymce.com/profile.php?name=neoc83)_
> 
> _**Tags:** [firefox msie chrome url conversion inline urlconverter]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Xseaab/12_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
