### ISSUE TITLE
When adding a table on touch devices, it's not possible to simply tap into cells. To edit data within cells, one must do a long tap. 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1854]
Description of problem:

Steps to reproduce:
1. Add table
2. Attempt to tap into a cell

Expected result: Cursor moves into cell and allows user to edit

Actual result: Cursor remains in last cell of the table

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7122](http://archive.tinymce.com/develop/bugtracker_view.php?id=7122) posted by [ReasonJordan](http://archive.tinymce.com/profile.php?name=ReasonJordan)_

> _**Tags:** [safari ipad tables]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
