### ISSUE TITLE
When editing a table on touch devices, if the table is empty and has over 2 rows, tapping on a cell doesn't allow you to edit the data as you would expect. Instead, it highlights the entire table. To edit data within cells, one must do a long tap. 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1855]
Description of problem:

Steps to reproduce:
1. Add table on iPad
2. Save table
3. Reopen text editor
4. Attempt to tap into a cell

Expected result: Cursor enters cell and user can edit data 

Actual result: Table is highlighted

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7123](http://archive.tinymce.com/develop/bugtracker_view.php?id=7123) posted by [ReasonJordan](http://archive.tinymce.com/profile.php?name=ReasonJordan)_
> 
> _**Tags:** [safari ipad]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
