### ISSUE TITLE
Double horizontal scrollbar - autoresize and wider images

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1857]
Description of problem:
Using the autoresize plugin there are two problems:
Problem 1: There's always at least 3 or 4 rows after the last line of text or image inserted on the editor;
Problem 2: When inserting an image that is larger (wider than the width of the editor) and select it, there'll appear two horizontal scrollbars (check image attached).

Steps to reproduce:
1.Open fiddle.tinymce.com;
2.Add the autoresize plugin;
3.Insert an image and then enlarge it so that is wider than the width of the editor;
4.Select the image and check the bottom of the editor, there are two horizontal scrollbars.

Note: I used the edge version of tinymce.

Expected result: 
No added lines below the last content in the editor and shouldn't appear two horizontal scrollbars.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7125](http://archive.tinymce.com/develop/bugtracker_view.php?id=7125) posted by [mcgoncalves](http://archive.tinymce.com/profile.php?name=mcgoncalves)_

> _**Tags:** [firefox msie chrome autoresize scrollbar]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
