### ISSUE TITLE
Convert <p> tags into <br/> while Pasting the content from Word

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1858]
To reproduce the problem, try this way - Copy text from any MS Word document and then paste into editor using 'Paste from Word' option. You'll see, TinyMCE had added extra space which I presume, is due to &ltg;p> tags. However, there is no way to use &ltg;br/> tags, instead of paragraph tags, as we can do for typing by using "forced_root_block : false" option. With this option, a &ltg;br/> tag is added when a user presses/hits the Enter key which is acceptable.

Can this issue be fixed in next release?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7126](http://archive.tinymce.com/develop/bugtracker_view.php?id=7126) posted by [ps374](http://archive.tinymce.com/profile.php?name=ps374)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
