### ISSUE TITLE
Wrong hight of new empty lines

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1859]
Description of problem:

Steps to reproduce:
1.Change font size to 36pt
2.Type some text
3.Press Enter two times
4.Type some text 
5.Show preview

Expected result:
Space between two lines with text should be same in editor and in preview.

Actual result:
Different space between lines. See picture
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7127](http://archive.tinymce.com/develop/bugtracker_view.php?id=7127) posted by [jiri_kroutil](http://archive.tinymce.com/profile.php?name=jiri_kroutil)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
