### ISSUE TITLE
not one event bubbling (dosn't popup) after the removal of all text (text should be selected with CTRL + A)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1860]
Description of problem:

Steps to reproduce:
1. enter random text
2. use CTRL+A key combination fo select all text in editor
3. delete all text, use "Enter" or "BackSpace" key

Expected result:
 should bubbling event input AND/OR change
Actual result:
 events not bubbling
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7131](http://archive.tinymce.com/develop/bugtracker_view.php?id=7131) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_

> _**Tags:** [firefox msie safari chrome opera event input change delete]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Steaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
