### ISSUE TITLE
<ol> list reset numbering is <li> is interleaved by <p> elements.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1861]
Description of problem: &ltg;ol> list reset numbering is &ltg;li> is interleaved by &ltg;p> elements. This seems caused by a reinterpretation of the source code, that adds extra lists before and after the &ltg;p> element. This issue seems to exist also for &ltg;ul>, with the difference that the effect is not visible when the browser renders it.

Steps to reproduce:
1. go to http://www.tinymce.com/
2. open the Source Code editing mode
3. change &ltg;ul> element to &ltg;ol> (see attachment 1.png)
4. between the first &ltg;li> and the second, add a &ltg;p/> (see attachment 1.png)
5. save the content
6. notice that the numbering restart (see attachment 2.png)
7. reopen the Source Code editor
8. notice that there are two more nested &ltg;ol>, causing the numbering to restart. (see attachment 3.png)

Expected result: numbering kept consistent (see attachment expected.png, taken using the same source code rendered on any browser)

Actual result: numbering resets after &ltg;p> (see attachment 3.png)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7129](http://archive.tinymce.com/develop/bugtracker_view.php?id=7129) posted by [mcodella](http://archive.tinymce.com/profile.php?name=mcodella)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Verified_
> _**Resolution:** Postponed_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
