### ISSUE TITLE
convert_urls: false breaks dragging images with relative paths

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1862]
Description of problem: Setting convert_urls to false breaks dragging images with relative paths, converting them to absolute paths.

Steps to reproduce:
1. Go to http://fiddle.tinymce.com/Rteaab in IE11
2. Insert an image with a relative path (for example, /images/logo.png )
3. Drag the image somewhere else in the editor
4. View the source

Expected result: the image should still have a relative path

Actual result: the image has an absolute path (e.g. http://fiddle.tinymce.com/images/logo.png )

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7130](http://archive.tinymce.com/develop/bugtracker_view.php?id=7130) posted by [Sb87](http://archive.tinymce.com/profile.php?name=Sb87)_
> 
> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Rteaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
