### ISSUE TITLE
not work Ctrl+Shift+Del in empty editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1863]
Description of problem:

Steps to reproduce:
1. Clear editor
2. enter Ctrl+Shift+Del

Expected result:
 view browser window with "history/cache manage"
Actual result:
 nothing

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7133](http://archive.tinymce.com/develop/bugtracker_view.php?id=7133) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_
> 
> _**Tags:** [firefox msie safari chrome opera key combination]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
