### ISSUE TITLE
Not Able to Put Caret to the Begin or the End of Table with forced_root_block

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1864]
Description of problem:
In settings, if we specify the `forced_root_block`, user in firefox browser will not be able to move the caret before or after the table by mouse click or keyboard left and right.

As far as I know, it is also related to this issue [#7087](http://www.tinymce.com/develop/bugtracker_view.php?id=7087). However, when we do add the `valid_children` to the setting like:
valid_children: '-div[table]',

We can get the table to not insert under the forced_root_block, but when inline mode is true, it only insert a bunch of the &ltg;br> tag without inserting any table.

Steps to reproduce:
1. Set `forced_root_block` to be 'div'
2. Set `inline` to be true
3. Insert table in the tinymce editor
4. Use FireFox as the browser
5. Try to use mouse to select the end or the beginning of the table

Expected result:
Expect the inline editor to insert table correctly with Firefox able to move caret to the beginning or end of the table.

Actual result:
Editor insert a bunch of &ltg;br> instead of table.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7134](http://archive.tinymce.com/develop/bugtracker_view.php?id=7134) posted by [rcliao](http://archive.tinymce.com/profile.php?name=rcliao)_

> _**Tags:** [firefox table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/rueaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
