### ISSUE TITLE
Elements with display: table are resizable in IE 11.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1868]
Description of problem:
Elements inserted into the editor with display: table are resizable in IE 11. This even occurs with object_resizing set to false.

Steps to reproduce:
1. See fiddle.
2. Click on the inserted element in IE 11. It shows resizing handles and is movable.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7138](http://archive.tinymce.com/develop/bugtracker_view.php?id=7138) posted by [rax](http://archive.tinymce.com/profile.php?name=rax)_

> _**Tags:** [msie table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Nueaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
