### ISSUE TITLE
Hidden TinyMCE dismisses changes to the plain textarea

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1869]
Description of problem:
If the editor is hidden via `hide()`, it's onsubmit handler will dismiss any changes made to the plain textarea before submitting the form.

Steps to reproduce (see fiddle):
1. Type some text in the editor.
2. Click "Toggle" to hide the editor.
3. Change the contents of the plain textarea.
4. Click "Submit".

Expected result: The content you've typed into the plain textarea.

Actual result: The content you've typed into the editor before hiding it.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7139](http://archive.tinymce.com/develop/bugtracker_view.php?id=7139) posted by [Callidior](http://archive.tinymce.com/profile.php?name=Callidior)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Pueaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
