### ISSUE TITLE
It's not possible to change style attributes on tables

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1870]
Description of problem:
If a table has a width set and you try to change these values in the editor and then run activeEditor.getContent() the initial values is returned. This is a regression, it worked in version 4.1.0 but doesn't work after version 4.1.1

Steps to reproduce:
1. Open the fiddle
2. Click getContent button see the correct output being alerted
3. Enter cell properties and change the width
4. Click getContent button and the output is unchanged... The old width is still returned.

The same issue seem to appear when trying to change table properties as well but not on a consistent basis...

The width and height css-properties are updated correctly, ie the table changes size, but the internal data-mce-style is not updated. And when I hit getContent the data-mce-style is returned. (See attached picture)

Note. This only occurs when changing existing values not when setting width or height for the first time.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7140](http://archive.tinymce.com/develop/bugtracker_view.php?id=7140) posted by [albinohrn](http://archive.tinymce.com/profile.php?name=albinohrn)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Yueaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
