### ISSUE TITLE
TinyMCE crashes in Chrome on contenteditable=false

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1872]
Description of problem:

Steps to reproduce:
1. Open the file in Chrome.  I am using 37.0.2062.102 m on Windows 7 x64.
2. Click in between the highlighted {...} sections in the textarea (which is actually a TinyMCE field.)  These blocks are set as "contenteditable=false".
3. Backspace them, or delete from behind.

Expected result:
The entire block gets deleted as one piece.  (This works correctly in FF and IE.)

Actual result:
Chrome crashes
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7142](http://archive.tinymce.com/develop/bugtracker_view.php?id=7142) posted by [krtaylor](http://archive.tinymce.com/profile.php?name=krtaylor)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
