### ISSUE TITLE
Autpmatically adds empty paragraph after single table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1873]
Description of problem:
If there is only a single table in the editor, it automatically adds an empty paragraph after saving. Even after manually deleting that paragraph, it's there again as soon as you save.

Expected result:
No paragraph after the table.

Actual result:
Empty paragraph automatically added after the table.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7143](http://archive.tinymce.com/develop/bugtracker_view.php?id=7143) posted by [NinaG](http://archive.tinymce.com/profile.php?name=NinaG)_
> 
> _**Tags:** [firefox table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
