### ISSUE TITLE
continue deleting content is not remove the formatting 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1874]
Description of problem:

Steps to reproduce:
1.go to demo page (i have used this http://www.tinymce.com/tryit/basic.php)
2.click Ctrl+A and click DELETE button
3.type some text with both bold and normal case.
4.press backspace and not release backspace button until all bold text is not removed. 
5.start typing text from there 
6.check that bold text is still typed in editor.

Expected result: normal case text must have to typed in editor 

Actual result: bold text is typed in editor

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7144](http://archive.tinymce.com/develop/bugtracker_view.php?id=7144) posted by [snehal1112](http://archive.tinymce.com/profile.php?name=snehal1112)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
