### ISSUE TITLE
Paste in Chrome, editor scrolls to top

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1875]
Description of problem:
Related to this closed bug: http://www.tinymce.com/develop/bugtracker_view.php?id=6639  But seems to be around the 'paste' plugin.  Follow the same steps and I can recreate this bug on edge (4.1.4 at the time of posting)

Steps to reproduce:
1. http://fiddle.tinymce.com/uveaab
2.  Fill with more than 1 page of content
3.  Go to new line near bottom of content
4.  Paste any text on the new line
5.  Observe that the browser scrolls back to the top. 

Chrome: Version 37.0.2062.102 m

Expected result: No scroll

Actual result:  Scrolls to top of page/frame. 

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7145](http://archive.tinymce.com/develop/bugtracker_view.php?id=7145) posted by [justintime](http://archive.tinymce.com/profile.php?name=justintime)_

> _**Tags:** [chrome chrome paste scroll]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/uveaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by speller** [comment]
The issue still present in inline mode.

**Comment by blackcathikari** [comment]
@speller Thanks for commenting. Could you please tell me what environment you're using Tiny in? Tiny version, OS and browser would be very helpful. Tiny config as well if possible. I still can't replicate this using the latest version of Tiny in inline mode on Win 7 Firefox or Chrome unfortunately, so looks like I need more information. Are you following the steps given in the original bug report, or doing something different? And are you able to create an example at [fiddle.tinymce.com](fiddle.tinymce.com) please?

**Comment by speller** [comment]
@blackcathikari Here is the example: http://fiddle.tinymce.com/3Qfaab . Open any dialog (such as Image insert) and close it. Editor window will be scrolled to top after closing. I'm using latest Chrome.

**Comment by spocke** [comment]
@speller This seems like a proper issue could you open a new ticket though since it doesn't seem to be related to paste but rather with focus/blur of the editor instance when opening dialogs. Thanks.

**Comment by bhol** [comment]
I am having the same issue with the inline tools. When adding a link or an image via the inline toolbar, the item gets placed at the top of the document as it appears focus is lost when the dialog is popped. Can someone paste the new ticket here so I can track the solution?

**Comment by blackcathikari** [comment]
@bhol The new ticket is #3669
