### ISSUE TITLE
No activate event is fired on first click in editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1876]
Description of problem:
I am not sure if this is a feature or a bug. It causes me problem so it would be nice to hear what you have to say about it.

I have a page with multiple editors. When an editor are added it will be set as the activeEditor, this mean that when the page is loaded all scripts are finished the editor that was added last will be the "activeEditor". So if I click on this editor, the one that was added last, I get no activate event. I depend on this event for other functions in my app, so this is a problem for me. :) 
If I only have one editor on a page I cannot get a activate event at all. When I have multiple I can at least click between the editors to trigger activate.

It would not be an option for me to do the operations on setup. I just want the editor to be active when someone has clicked in it. I would like to skip the part in EditorManager#add where it sets the "activeEditor" to the newly created.

Is this a bug or is there a way I could work around this issue?

Steps to reproduce:
1. Open the fiddle
2. Click "Last editor"

Expected result:
Alert that says activate

Actual result:
No alert
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7146](http://archive.tinymce.com/develop/bugtracker_view.php?id=7146) posted by [albinohrn](http://archive.tinymce.com/profile.php?name=albinohrn)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/4veaab/2_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
