### ISSUE TITLE
Paste bug from Word when tinymce is contained within an li element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1877]
Description of problem:

Steps to reproduce:
1.Copy the content of the attached word document
2.Paste it in the "Paste here"

Expected result:
The editor should contain pasted text from word

Actual result:
The editor content doesn't change. A span is created after the editor and a second li is created after the span. This newly created li is an exact copy of the first one. Take a look at capture.png.
An error appears in the console : ConsoleError.png

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7147](http://archive.tinymce.com/develop/bugtracker_view.php?id=7147) posted by [Victor Hautevolta](http://archive.tinymce.com/profile.php?name=Victor Hautevolta)_

> _**Tags:** [firefox paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/5veaab/3_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
