### ISSUE TITLE
Width of Table Cell Properties not updated

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1878]
Description of problem:
After I created a Table,it works well after I edit the Width of first Cell and save for the first time.But starting from second time,even though I changed the Width again and the editor did shown the changes,however the value in Source Code and Style under Advanced tab is not changed,unless I edit the value under Style manually as well.

Steps to reproduce:
1. Create a table with 2x2.
2. Update first cell Width to 50 under Cell Properties.
3. Save.
4. Go to edit the Width again under Cell properties, change the value to 100,click OK.
5. The editor shown the changes, however when go to Source Code,the value is not updated.Style under Advanced Tab not updated as well.

Expected result: Value of Width under Style and Source Code updated after changes made and clicked "OK".

Actual result: After save,the Width value is not updated.

I tried to create an example at fiddle however after I created a Table in the editor and save,the content gone.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7148](http://archive.tinymce.com/develop/bugtracker_view.php?id=7148) posted by [IreneLing](http://archive.tinymce.com/profile.php?name=IreneLing)_
> 
> _**Tags:** [firefox chrome opera firefox5 chrome10 opera12 table cell width properties]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
I believe this is a duplicate of #1842. Could you please take a look and let us know if you disagree? Thanks,
Millie @ TinyMCE

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
