### ISSUE TITLE
 Cmd+Shift+Arrow does not select text in Firefox on a Mac,

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1880]
Description of problem:

In Firefox on a Mac, when editing existing text in TinyMCE, pressing Cmd+Shift+Left Arrow or Cmd+Shift+Right Arrow does not select the text next to the cursor.

In Chrome and Safari this key combination can be used to select text to either direction of the cursor.

Steps to reproduce:
1. Visit http://www.tinymce.com in Firefox on a Mac
2. Place your cursor in the middle of a word
3. Press Cmd+Shift+Left Arrow
4. Note that the text to the left of the cursor is not selected

Expected result:
Cmd+Shift+Left Arrow should select text to the left of the cursor.
Cmd+Shift+Right Arrow should select text to the right of the cursor.

Actual result:
The cursor moves to the left or right, but no text is selected.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7150](http://archive.tinymce.com/develop/bugtracker_view.php?id=7150) posted by [jdietrich](http://archive.tinymce.com/profile.php?name=jdietrich)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
