### ISSUE TITLE
formatting gets lost after pressing enter key two time and then press backspace one time

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1881]
Description of problem:

Steps to reproduce:
1.i have used classical demo of tinyMCE4.
2.select font size and type from drop down 
3.type something 
4.press enter 2 time 
5.press backspace 1 time 
6.check that formatting get lost 

Expected result: formatting should not get lost.

Actual result: select font size and type get lost.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7151](http://archive.tinymce.com/develop/bugtracker_view.php?id=7151) posted by [snehal1112](http://archive.tinymce.com/profile.php?name=snehal1112)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
