### ISSUE TITLE
Editor throws exception if destroyed from within keydown handler

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1882]
Editor proceeds to process event handlers after actually been destroyed.

Steps to reproduce:
1. Put focus inside editor
2. Press Ctrl+Q (this is my combination for destroy editor)

Expected result:
no errors, editor removed

Actual result:
editor removed, but exception in console (FF), some plugins can die trying to act with editor.selection from onkeydown handler

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7152](http://archive.tinymce.com/develop/bugtracker_view.php?id=7152) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_

> _**Tags:** [firefox keydown exception]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Oveaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
