### ISSUE TITLE
Pasting anchor places anchor text outside of the anchor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1883]
Description of problem:

Steps to reproduce:
1. Display a text with an anchor &ltg;a id="anchor">ANCHOR&ltg;/a> in Google Chrome
2. Select and copy a text with this anchor from Chrome.
3. Paste it in tinyMCE

Expected result:
&ltg;a id="anchor">ANCHOR&ltg;/a>

Actual result:
&ltg;a id="anchor">&ltg;/a>ANCHOR

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7153](http://archive.tinymce.com/develop/bugtracker_view.php?id=7153) posted by [lborgman](http://archive.tinymce.com/profile.php?name=lborgman)_

> _**Tags:** [chrome chrome13 paste anchor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
