### ISSUE TITLE
extra space are added after changing font size

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1884]
Description of problem:

Steps to reproduce:
1.i have used classical demo of tinyMCE4.
2.change font type and size (36)
3.type something (dont press enter key)
4.change font size to (10)
5.type something and press enter key
6.type something in new line.
7.check that extra space are added in between two lines.

Expected result:no extra space are required between two lines 

Actual result: there are some extra space are between two line.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7154](http://archive.tinymce.com/develop/bugtracker_view.php?id=7154) posted by [snehal1112](http://archive.tinymce.com/profile.php?name=snehal1112)_
> 
> _**Tags:** [firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
