### ISSUE TITLE
Images not aligning or showing caption

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1886]
The images on this page have captions and are aligned center in my wordpress dashboard. However, on the page they show no caption or alignment. It does this for every new page I produce or edit. 

This started the minute I updated to wordpress 4.0 and I have isolated it to be TinyMCE. I disabled each plugin one by one, and the only time I can get my pictures to work accurately is when I disable TinyMCE.

Expected result: Pictures at this url should be aligned center and showing a caption.

Actual result: Not aligned, not showing caption.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7156](http://archive.tinymce.com/develop/bugtracker_view.php?id=7156) posted by [joehackett](http://archive.tinymce.com/profile.php?name=joehackett)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tudorcoaching.com/how-we-do-it_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
