### ISSUE TITLE
Inserting external template adds empty p tags

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1887]
Description of problem:
Inserting HTML template causes additional p tags to be added - the template is broken as result. TinyMCE Version: 3.5

Steps to reproduce:
1. Insert template provided in fiddle
2. Check source

Expected result:
&ltg;figure class="right">&ltg;img src="http://wiki.tripwireinteractive.com/images/4/47/Placeholder.png" alt="" width="300" height="250" /> &ltg;figcaption>Lorem ipsum dolor sit amet enim.&ltg;/figcaption>&ltg;/figure>
&ltg;p>Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi.&ltg;/p>
&ltg;div class="clear"> &ltg;/div>

Actual result:
&ltg;p> &ltg;/p>
&ltg;figure class="right">&ltg;img src="http://wiki.tripwireinteractive.com/images/4/47/Placeholder.png" alt="" width="300" height="250" /> &ltg;figcaption>Lorem ipsum dolor sit amet enim.&ltg;/figcaption>&ltg;/figure>
&ltg;p> &ltg;/p>
&ltg;p>Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi.&ltg;/p>
&ltg;div class="clear"> &ltg;/div>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7157](http://archive.tinymce.com/develop/bugtracker_view.php?id=7157) posted by [ozzymir](http://archive.tinymce.com/profile.php?name=ozzymir)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/qweaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
