### ISSUE TITLE
Preventing the default action of close event destroys window parameters

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1888]
Description of problem:
In TinyMCE 4.1.5, one can forbid the user to close a dialog (loaded inside of an iframe) window by preventing the default action of the close event, like this:

top.tinymce.activeEditor.windowManager.windows[op.tinymce.activeEditor.windowManager.windows.length - 1].on('close', function(evt) {
    if (cond) {
        evt.preventDefault();
        evt.stopPropagation();
    },
true);

However, doing so destroys any parameters passed to the window. The can be retreived with top.tinymce.activeEditor.windowManager.getParams(), but as soon as the user attempts to close the dialog and the callback fires, that function will return an empty object.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7158](http://archive.tinymce.com/develop/bugtracker_view.php?id=7158) posted by [Callidior](http://archive.tinymce.com/profile.php?name=Callidior)_
> 
> _**Tags:** [firefox msie safari chrome opera windowmanager dialog]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
