### ISSUE TITLE
Incorrect cursor position after use "Edit link" and tap left arrow key

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1889]
Description of problem:

Steps to reproduce:
1. set cursor on link in editor
2. click on link-button "Insert/edit link"
3. click "OK" (then the text is highlighted/selected in the editor)
4. tap a few times on left arrow key

Expected result:
cursor stop at the beginning of words

Actual result:
cursor moves in a circle (from the beginning to the end of the word), but does not stop at the beginning of words after first tap
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7159](http://archive.tinymce.com/develop/bugtracker_view.php?id=7159) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/tweaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
