### ISSUE TITLE
Opening search-dialog should default to current selection

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1890]
In tinyMCE-versions before 4.x afaik the search-dialog contained the currently selected text in the search-field. It was possible to select a word from the text, open the dialog and search right away. Also it was possible to then do modifications (like setting the found part to bold or underlined) and open the search-dialog again to search further.

With 4.x the search-dialog is always initially empty.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7160](http://archive.tinymce.com/develop/bugtracker_view.php?id=7160) posted by [neufeind](http://archive.tinymce.com/profile.php?name=neufeind)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
