### ISSUE TITLE
IE11: valid_elements cause problem for table_tab_navigation

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1891]
Description of problem:
Using the default configuration, adding valid_elements : "*[*]". See http://fiddle.tinymce.com/3weaab
Tested on MSIE 11, TinyMCE_4.1.5
It works with Firefox.

Steps to reproduce:
1. Using MSIE 11 to insert a new table (for example: 1 row x 2 columns) 
2. Enter text in the first cell
3. Use tab to navigate to the next cell
4. Enter text in the next cell
5. An error occurs

Expected result:
The table is not changed and the navigation with tab can be continued.

Actual result:
A new cell is added automatically at the end. And the navigation with tab does not work anymore.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7161](http://archive.tinymce.com/develop/bugtracker_view.php?id=7161) posted by [tcnguyen](http://archive.tinymce.com/profile.php?name=tcnguyen)_

> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/3weaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
