### ISSUE TITLE
A div without any attributes is removed when the text in a paragraph is deleted

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1892]
When deleting the paragraph (either of them) from this block of code:

&ltg;div class="box">
    &ltg;div>
        &ltg;div class="palette4 swatch1">
            &ltg;p>The content&ltg;/p>
            &ltg;p>Goes here&ltg;/p>
        &ltg;/div>
    &ltg;/div>
&ltg;/div>

It will remove the second div, unless that div has any kind of attribute applied, such as:

&ltg;div class="box">
    &ltg;div data-stub="1">
        &ltg;div class="palette4 swatch1">
            &ltg;p>The content&ltg;/p>
            &ltg;p>Goes here&ltg;/p>
        &ltg;/div>
    &ltg;/div>
&ltg;/div>

Expected result:

&ltg;div class="box">
    &ltg;div>
        &ltg;div class="palette4 swatch1">
            &ltg;p>The content&ltg;/p>
        &ltg;/div>
    &ltg;/div>
&ltg;/div>

Actual result:

&ltg;div class="box">
    &ltg;div class="palette4 swatch1">
        &ltg;p>The content&ltg;/p>
    &ltg;/div>
&ltg;/div>

This happens on TinyMCE3 and TinyMCE4.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7162](http://archive.tinymce.com/develop/bugtracker_view.php?id=7162) posted by [amnuts](http://archive.tinymce.com/profile.php?name=amnuts)_
> 
> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/8weaab_

**Comment by nori-h** [comment]
I believe this is similar to #2510 and #2638. Could you have please have a look and let us know if not? Thanks, Nori @ TinyMCE

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by batata004** [comment]
@fyrkant  I am still having this issue with the latest TINYMCE. I detailed it here -> https://github.com/tinymce/tinymce/issues/3888

**Comment by batata004** [comment]
@spocke could you open this???

**Comment by batata004** [comment]
unbeliveable, nobody cares with this bug.
