### ISSUE TITLE
Editor.formatter changes not tracked

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1893]
Changes made with editor.formatter does not change isDirty state of editor if called from UI elements.

Steps to reproduce:
(Custom try)
1. Put cursor into text.
2. Push button "Color" on editor panel.

(Plugin try)
1. Use default textcolor plugin
2. Put cursor into text.
3. Use forecolor or backcolor buttons to change text|background color.

(Etalon)
1. Put cursor into text.
2. Press Ctrl+ArrowUp or Ctrl+ArrowDown

Expected results:
After changing content through editor.formatter onChange event should be called, and isDirty should be set to true.

Actual result:
First end second examples will not cause onChange event to rise or isDirty to become true.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7163](http://archive.tinymce.com/develop/bugtracker_view.php?id=7163) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Aweaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
