### ISSUE TITLE
Wrong getSelectedBlocks behaviour

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1895]
Steps to reproduce:
1. Disable "lists" plugin.
2. Put cursor into third list item (first empty item).
3. Use toolbar button Bullet list to break the list.
4. Use toolbar button Align right.

Expected results:
line with cursor will get aligned to right.

Actual results:
All lines after cursor will get aligned

Comment:
In this situation getStart and getEnd functions of editor.selection will be in wrong order, so treewalker in getSelectedBlocks will trying to find previous element using next() func.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7165](http://archive.tinymce.com/develop/bugtracker_view.php?id=7165) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Dweaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
