### ISSUE TITLE
Clearing Editor Removes any Preset Fonts

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1896]
Description of problem: The default font that is set when the editor is loaded if they users holds backspace and deletes all the characters in the editor. 

Steps to reproduce:
1. init the editor with a preset font 
init:
ed.execCommand("FontName", false, value);
2. Type in text and click on view source. The font is in the predefined font
3. Hold backspace and delete all the characters even if it looks like none are there
4. Type in additional text in the text box and click view source again
5.

Expected result:
The text will still be in the original font setup from step 1

Actual result:
The font has no formatting at all
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7167](http://archive.tinymce.com/develop/bugtracker_view.php?id=7167) posted by [dummyname](http://archive.tinymce.com/profile.php?name=dummyname)_

> _**Tags:** [font]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
