### ISSUE TITLE
Tinymce Steals Focus

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1897]
Description of problem: I have read bug reports of tinymce stealing focus on init and possible ways around it but I can't get any of them to work. Using Tinymce 4.x

Steps to reproduce:
1. Have a page with a textbox and a tinymce editor
2. In the tinymce init function set the focus to the textbox
3. Load the page

Expected result:
The textarea gets focus after the editor is initialized 

Actual result:
Tinymce always steals the focus even though the focus for a split second is set to the textbox
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7168](http://archive.tinymce.com/develop/bugtracker_view.php?id=7168) posted by [dummyname](http://archive.tinymce.com/profile.php?name=dummyname)_

> _**Tags:** [firefox msie safari chrome opera focus steals]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by thooyork** [comment]
Same issue on tinyMCE 6.7.0 .
Doing execCommand in either editor.on("init"), or in  init_instance_callback, leads tinyMCe to steal focus from other form inputs. Have tinyMCE running in an angular application, but as far as I can tell this has nothing to do with angular. It is a tinyMCE problem. If I get rid of my execCommand during setup everything works as expected.

**Comment by TheSpyder** [comment]
There's a setting for it now.
https://www.tiny.cloud/docs/tinymce/latest/editor-important-options/#auto_focus
