### ISSUE TITLE
Advanced Image Style

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1899]
Description of problem:
If you add margin-right on image without placing a horizontal space. The margin is remove.

Steps to reproduce:
1. Insert a image
2. Go to the advanced tab in edit image
3. Add a "margin-right:10px" inside style
4. Click "OK"
5. Check the resulting HTML, no margin-right ??

Expected result:
 The margin need to stay

Actual result:
 The margin is remove
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7170](http://archive.tinymce.com/develop/bugtracker_view.php?id=7170) posted by [russe](http://archive.tinymce.com/profile.php?name=russe)_

> _**Tags:** [firefox chrome image margin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
