### ISSUE TITLE
Support for attribute class for table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1900]
Add support for attribute class for table, table rows and table columns like attribute style

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7171](http://archive.tinymce.com/develop/bugtracker_view.php?id=7171) posted by [StAniS](http://archive.tinymce.com/profile.php?name=StAniS)_
> 
> _**Tags:** [table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
