### ISSUE TITLE
Content Security Policy Violation (Compatibility Issue)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1901]
Description of problem: If using a strict Content-Security-Policy, TinyMCE does not work and creates an Javascript error.

Steps to reproduce:
1. The HTTP-header of the page must include CSP (X-Content-Security-Policy: allow 'self')
2. Apply TinyMCE to a textarea in the same page
3. A CSP violation is triggered (visible in debug console of Google Chrome)

Expected result: TinyMCE works

Actual result: Line 1274: return a = h(t, "string") ? o.doc.createElement(t) : t, o.setAttribs(a, n), r && (r.nodeType ? a.appendChild(r) : o.setHTML(a, r)), i ? a : e.appendChild(a)

Refused to execute Javascript URL because it violates the Content Security Policy directive script-src:'self'

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7172](http://archive.tinymce.com/develop/bugtracker_view.php?id=7172) posted by [Blackbam](http://archive.tinymce.com/profile.php?name=Blackbam)_
> 
> _**Tags:** [csp]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by parmarg** [comment]
Any update on this?

**Comment by spocke** [comment]
I added this to our internal backlog will see if we can schedule this in for the next sprint it's been in here for way to long.

**Comment by spocke** [comment]
Had a go at this and it seems that this works:
Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self';

We need to be able to set styles inline since we use it to place dialogs, menus etc absolute.

**Comment by maarten-v** [comment]
Is it also really necessary to use inline javascript? It would be great if we could get rid of the insecure "script-src unsafe-inline" setting.

**Comment by spocke** [comment]
I pushed a change where it would not set the inline source to javascript: if the browser has CSP support.
So after that patch a CSP header like this would work:
Content-Security-Policy: default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self';

The UI requires us to position things at absolute positions with code so unsafe-inline for styles is still  required.

**Comment by Daijobou** [comment]
Is this in 4.4.3 included? Actual I get still

> tinymce.min.js:4 Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

with (apache) line
`Header add Content-Security-Policy "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'"`

**Comment by phinor** [comment]
Still an issue as of 4.5.1

**Comment by chrisconover** [comment]
Adding more detail about my situation and wishes for stricter CSP support in TinyMCE per Andrew's request: https://twitter.com/andrew_roberts/status/826464180727275521

Here's my CSP:
```
self.response.headers['Content-Security-Policy'] = (
         "object-src 'none'; script-src 'nonce-{nonce}' *.googletagmanager.com "
         "*.tagmanager.google.com *.google-analytics.com "
         "'unsafe-inline' 'unsafe-eval' 'strict-dynamic'"
     ).format(nonce=nonce)
```

When trying to use TinyMCE in Google Chrome I get the following console error:
```Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'nonce-eF1gMLVup8MP6Fj2uqv0nQ==' *.googletagmanager.com *.tagmanager.google.com *.google-analytics.com 'unsafe-inline' 'unsafe-eval' 'strict-dynamic'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.```

Looking at the static trace it looks like its failing in the "add" method in the final "appendChild(a)":
```
add: function(e, t, n, r, i) {
                var o = this;
                return this.run(e, function(e) {
                    var a;
                    return a = g(t, "string") ? o.doc.createElement(t) : t,
                    o.setAttribs(a, n),
                    r && (r.nodeType ? a.appendChild(r) : o.setHTML(a, r)),
                    i ? a : e.appendChild(a)
                })
            },
```

Ideally I would be able to pass my nonce value as a TinyMCE option config and the library would use it anytime it needs to make a request. Requests with the nonce value should prevent any CSP violations.

Even with the error mentioned above, the editor still *seems* to work fine in Chrome, but completely fails to render in Safari or Firefox.

**Comment by iamandrewluca** [comment]
Something new on this issue?

**Comment by thecoderok** [comment]
Still an issue in 4.5.3:
`DOM.setAttrib(ifr, "src", url || 'javascript:""');`

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by manishchourasia2000** [comment]
Yes issue still persist in 4.6.6. Please see the attached 

![1](https://user-images.githubusercontent.com/31951895/30738146-b5811d9a-9fa6-11e7-8651-e5447ccde3c1.png)
![2](https://user-images.githubusercontent.com/31951895/30738148-b588db2a-9fa6-11e7-9a7e-fbb8aa62324e.png)
![3](https://user-images.githubusercontent.com/31951895/30738147-b584420e-9fa6-11e7-94e0-4a1c854c97d2.png)


screenshot

**Comment by manishchourasia2000** [comment]
I observe that issue is still persist. Please see the screen shot.
my headers are 
default-src 'self';

script-src 'self' 'nonce-1wgmf3EKeHagCs+V+Twq' 'unsafe-eval';
object-src 'self';

style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://localhost:44322;

img-src 'self' ;
font-src 'self' https://fonts.gstatic.com data:;

connect-src 'self' https://localhost:44322;plugin-types application/pdf;report-uri /WebResource.axd?cspReport=true

and all scripts & style loads with nonce hence it ignore unsafe inline parameter.

![1](https://user-images.githubusercontent.com/31951895/30773318-244b3f5e-a08c-11e7-8600-3ec75749b7d1.png)
![2](https://user-images.githubusercontent.com/31951895/30773319-244e55a4-a08c-11e7-94bc-e6430cf093d5.png)
![3](https://user-images.githubusercontent.com/31951895/30773320-244f0b5c-a08c-11e7-826f-faef95320c10.png)

**Comment by fabienbranchel** [comment]
@manishchourasia2000 , me too !

I'm using your latest version, the 4.9.2.
@fyrkant : Is it possible to re-open this issue ?

**Comment by spocke** [comment]
Have you tried these official CPS headers:
https://www.tiny.cloud/docs/advanced/security/#qhowdoisetupcontentsecuritypolicycspwithtinymce

Can't seem to get the same problem with those.

**Comment by fabienbranchel** [comment]
Yes, except for : 

`style-src 'self' 'unsafe-inline';`

In my opinion, it's not a solution. I was thinking that this issue was closed because a better way was found...

**Comment by ricardovdbroek** [comment]
I don't feel this is fixed either. @spocke I understand settings styles on elements from JS is needed, but can't it be achieved using: `Element.style.property = "value"`? That seems to work without needing `'unsafe-inline'`, please correct me if I'm wrong here.

I agree with @fabienbranchel that adding `'unsafe-inline'` is not really a solution, because the solution to "this library isn't safe" shouldn't be "just lower your standards".

**Comment by TheSpyder** [comment]
There would probably be _hundreds_ of `element.style.propery = 'value'` entries required to work without `unsafe-inline`. It's difficult to understate the level of work required to achieve it and it would place a large burden on future features.

TinyMCE is a complex editor with a complex UI that supports a wide variety of use cases. Updating the `style` attribute directly makes this wide variety of support easier on us as developers and allows us to offer better experiences more frequently.

**Comment by phinor** [comment]
Clearly the wide range of use cases does not include "rich text editors on CSP-secure sites".

**Comment by TheSpyder** [comment]
Certainly if running CSP fully secure becomes so popular that we get a lot of requests for this we can do it. If using `style.property = value` allows this it's not impossible to fix it will just place a huge burden on the team.

Until that happens, or we drastically change our use of CSS such that it's less of a burden, we will continue to require security to be weakened with the `style-src ‘self’ ‘unsafe-inline’;` loophole. Sorry.

**Comment by alfonsoII** [comment]
Using ```unsafe-inline``` **effectively removes any CSP protection against XSS.**

**Comment by josuemy** [comment]
Something I took from https://developers.google.com/web/fundamentals/security/csp and I think it's relevant to this:

>  Banning inline script is the biggest security win CSP provides, and banning inline style likewise hardens your application. It's a little bit of effort up front to ensure that things work correctly after moving all the code out-of-line, but that's a tradeoff that's well worth making.

**Comment by TheSpyder** [comment]
We appreciate the importance of a good CSP, but you have to appreciate the scope of this request.

We do not require inline scripts, but inline styles are core to how the editor functions. Parts of the UI use it, in ways that could certainly be switched to style property updates, but content is where inline styles are used everywhere and thus where our problem lies. Some very quick examples:

* `<span style="text-decoration: underline;">text</span>`
* `<span style="color: #e03e2d;">text</span>`
* `<p style="padding-left: 40px;">text</p>`

And beyond that, our paste plugin manipulates the styles of pasted HTML. Our table plugin has features that update the style attribute on every cell in a table. The list goes on.

There are so many scenarios where `style` attributes are the best practice for HTML content that it becomes a monumental challenge to avoid setting the `style` attribute on any element.

**Comment by PhilippMDoerner** [comment]
I appreciate the the open communication here TheSpyder, thanks !

>Certainly if running CSP fully secure becomes so popular that we get a lot of requests for this we can do it. 
In this case I'd like to also throw my hat in the ring and write this comment as another request for this feature.

**Comment by sumitkd199** [comment]
I was trying to use premium plugin through cdn and i get the following error on my browser 
![image](https://user-images.githubusercontent.com/29367953/229761063-8e199260-e33e-4123-a2f0-eb728d735b0f.png)

This is the meta tag i have used it resolved a few errors but i am still left with this error:
 <meta http-equiv="Content-Security-Policy"
        content="default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.tinymce.com *.tiny.cloud; connect-src 'self' *.tinymce.com *.tiny.cloud blob:; img-src 'self' *.tinymce.com *.tiny.cloud data: blob:; style-src 'self' 'unsafe-inline' *.tinymce.com *.tiny.cloud; font-src 'self' *.tinymce.com *.tiny.cloud;" />

any suggestion on fixing this ?

**Comment by some1ataplace** [comment]
I am using the latest tinymce version 6 and having the same problems with content security policy style-src unsafe-inline. 

This is a real shame if the tinymce team refuses to make this a top priority to improve security. I understand there are a lot of scenarios and it is a big ask, but this issue has already been brought to your attention years ago and it seems like it will take forever to get this essential security feature done. Leaving unsafe-inline the way it is now is not acceptable. Just get it done. 

ckeditor 5 allows users to download an external css stylesheet to use instead of unsafe-inline css. 

https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/csp.html

Guess a lot of us will be forced to move to your biggest competitor simply because they found a way to respect user security. To bad because ckeditor is a lot harder to use compared to tinymce. If the tinymce team got rid of style-src unsafe-inline, the tinymce product would easily be ranked #1 for security enthusiasts.

**Comment by TheSpyder** [comment]
As I explained 3 years ago, `unsafe-inline` is about more than just using an external stylesheet; it requires avoiding `style` attributes completely which is quite challenging to retrofit on an editor.

I understand this is no excuse and we are are considering whether, similar to CKEditor, we can recommend a list of configuration settings that allow the editor to operate in Strict CSP mode.

> Guess a lot of us will be forced to move to your biggest competitor 

Funny story about that...
https://www.tiugotech.com/news

**Comment by AbdulnaserMohsen** [comment]
I solved it before printing the content using nonce
check the code here
https://github.com/AbdulnaserMohsen/Solve-Content-Security-Policy-Violation

**Comment by TheSpyder** [comment]
Yes, exclusive use of the `class` attribute is as far as we know the only viable way to edit content in a strict CSP environment. However a lot of TinyMCE features are incompatible with this approach.
