### ISSUE TITLE
[Inline editing] 'Text to display' is not set on the Insert Link dialog.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1903]
Description of problem:
On the inline editing mode, 'Text to display' is not set on the Insert Link dialog from the menu.

Steps to reproduce:
1. on the inline mode.
2. select a text in the editor.
3. select 'Insert' -> 'Insert Link' from the menu, and open 'Insert Link' dialog.

Expected result:
Selected text should be set into the 'Text to display' field. 

Actual result:
The field is empty.

Note:
On the basic editing mode, it works.
'Insert Link' from the toolbar button works, too.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7174](http://archive.tinymce.com/develop/bugtracker_view.php?id=7174) posted by [hogedigo](http://archive.tinymce.com/profile.php?name=hogedigo)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/inline.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
