### ISSUE TITLE
First empty line styling issue

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1904]
Description of problem:

Steps to reproduce:
1. Remove all content in an editor
2. Press Enter to have the first line blank
3. Type something on the second line
4. Select all
5. Set the selection's style to bold, italic or underlined
6. Repeat step 5

Expected result:
The whole selection become bold, italic or underlined on step 5.
On step 6, it should lose its style, but does not.

Actual result:
The whole selection stays bold, italic or underlined, and the buttons don't even toggle.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7175](http://archive.tinymce.com/develop/bugtracker_view.php?id=7175) posted by [nseptier](http://archive.tinymce.com/profile.php?name=nseptier)_
> 
> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
