### ISSUE TITLE
IE 10 - storageElm

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1905]
Hello, I've a bug when I try to load TinyMCE on IE10 (even with your basic demo). The issue comes from this line "storageElm.load(userDataKey);".
Could you please confirm me the error? I've checked and my msie console doesn't use any quirks.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7176](http://archive.tinymce.com/develop/bugtracker_view.php?id=7176) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
