### ISSUE TITLE
ctrl + click on link do not fonction

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1906]
Description of problem:

When you want to follow a link inside the editor (with a CTRL + Click), in chrome/chromium, it doesn't work. It means you can't open an external link from the content fo the editor.

Steps to reproduce:
1. Open chrome/Chromium browser
2. Make � link to another website
3. try to open this link (thraught CTRL + click)

Expected result:
Link is open in new window

Actual result:
Nothing append

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7177](http://archive.tinymce.com/develop/bugtracker_view.php?id=7177) posted by [SpOOnisBacK](http://archive.tinymce.com/profile.php?name=SpOOnisBacK)_
> 
> _**Tags:** [chrome chrome link]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/pxeaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
