### ISSUE TITLE
remove() problem after 4.1.1

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1907]
On version 4.1.2 was some changes with clean up procedure and now:

tinymce.get(editor_id).remove();

causes JavaScript Exception on Firefox.
With 4.1.1 and before all works fine.
Same problem appears on versions up to 4.1.5

NS_ERROR_XPC_CANT_MODIFY_PROP_ON_WN: Cannot modify properties of a WrappedNative

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7178](http://archive.tinymce.com/develop/bugtracker_view.php?id=7178) posted by [pH4Lk0n](http://archive.tinymce.com/profile.php?name=pH4Lk0n)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by pH4Lk0n** [comment]
Problem is related to https://github.com/tinymce/tinymce/issues/2671
And this fix in: classes/dom/Serializer.js

```
// Nodes needs to be attached to something in WebKit/Opera
// This fix will make DOM ranges and make Sizzle happy!
impl = node.ownerDocument.implementation;
if (impl.createHTMLDocument) {
	// Create an empty HTML document
	doc = impl.createHTMLDocument("");

	// Add the element or it's children if it's a body element to the new document
	each(node.nodeName == 'BODY' ? node.childNodes : [node], function(node) {
		doc.body.appendChild(doc.importNode(node, true));
	});

	// Grab first child or body element for serialization
	if (node.nodeName != 'BODY') {
		node = doc.body.firstChild;
	} else {
		node = doc.body;
	}

	// set the new document in DOMUtils so createElement etc works
	oldDoc = dom.doc;
	dom.doc = doc;
}
```

If this is only for Webkit and Opera can it just be disabled in Firefox?

Problem with SmartClient integration is that when some parent object is destroyed it removes elements from DOM so textarea and forms are no longer accessible.
Maybe that's a problem but I cannot find any workaround to this.

Change first line to global implementation resolved issue but I don't know how this affect Webkit or other elements.
`
impl = document.implementation;
`

Another thing is puzzling why there is serialization when editor is going to be destroyed.
Why is that?

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
