### ISSUE TITLE
cleanup DOM when save() or remove()-ed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1908]
Description of problem:

Steps to reproduce:
1. use the editor on &ltg;h1 class="editable">Editable header&ltg;/h1>
2. do a change, get
3. &ltg;h1 class="editable" id="mce_0" spellcheck="false" style="position: relative;">Editable header....&ltg;/h1>
4. try to quit the editor with tinymce.remove() or save() or whatever...
5. still same markup

Expected result:
I'd love to see a way where the parent element's markup can be preserved/cleaned on save, not just the content and its placeholders.  I save more HTML at one go then just whats inside an individual tinymce instance tag.

Actual result:
lot's of added inline styles, temporary ID, spellcheck and other garbage i don't want.

perhaps there already is a way, if so i'd love to hear it, tried most methods to "quit" the editor instance in the API, but none of them seem to clean up after itself.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7179](http://archive.tinymce.com/develop/bugtracker_view.php?id=7179) posted by [bubach](http://archive.tinymce.com/profile.php?name=bubach)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by sites21** [comment]
Is It fixed?
