### ISSUE TITLE
Spellchecker request error: 405

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1909]
Description of problem:

Steps to reproduce:
1. download, install and initialize tinymce 4.1.5
2. Add spellchecker to plugins:
        plugins: [
                "print preview hr spellchecker",
                "searchreplace visualchars fullscreen insertdatetime",
                "save paste textcolor"
        ],
3. Add textarea to html page content
4. Run project
5. Type misspelled word and click on Spellcheck tool icon

Expected result: Spellchecker to work

Actual result:  Spellchecker throws 405 error

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7180](http://archive.tinymce.com/develop/bugtracker_view.php?id=7180) posted by [yuut](http://archive.tinymce.com/profile.php?name=yuut)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by peterpyc** [comment]
Hi. I also get this error. Any news?

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
