### ISSUE TITLE
3.5.11 with spellchecker 2.0.6.1 fullscreen error

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1910]
Description of problem: Using 3.5.11 and the 2.0.6.1 spellchecker plugin (problem does not occur with the bundled spellchecker plugin) a JS error occurs when entering and leaving fullscreen mode.  The error upon leaving fullscreen mode means it is not possible to return to the underlying page.

Steps to reproduce (for reference I am doing this in Ff 32.0.2 on OS X 10.9.5, but the problem occurs across all browsers and operating systems):
1. Load a page that includes the editor with the spellchecker (2.0.6.1) and fullscreen plugins
2. Click the fullscreen button (in console a JS error will appear (TypeError: newEditor.plugins.spellchecker.setLanguage is not a function); the editor will switch to fullscreen mode despite this error.
3. Click the fullscreen button a second time to return to non-fullscreen mode; the editor will remain in fullscreen mode.  The console will again display "TypeError: newEditor.plugins.spellchecker.setLanguage is not a function"

Expected result:
It should be possible to exit fullscreen mode

Actual result:
The editor remains in fullscreen mode and the user cannot access the underlying page.

The bug is that the fullscreen plugin uses the spellchecker setLanguage function to ensure the language is maintained across the two editors (non-fullscreen and fullscreen).  But while the bundled spellchecker plugin includes the setLanguage function, the 2.0.6.1 spellchecker plugin does not.

I could not see how to load the alternative spellchecker plugin in order to create a fiddle.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7181](http://archive.tinymce.com/develop/bugtracker_view.php?id=7181) posted by [seade](http://archive.tinymce.com/profile.php?name=seade)_
> 
> _**Tags:** [firefox msie safari chrome opera spellchecker fullscreen]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
