### ISSUE TITLE
removing anchor in chrome is hard

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1911]
Description of problem:
Removing an anchor (that was added by tinymce4) in chrome removes the style of the text that's next to it or acts weird, jumps to the top of the page, removes focus, etc.

Steps to reproduce:
1. right some text
2. add style to the text (color, bold, etc.)
3. add an anchor element using the anchor button
4. try removing the anchor with backspace / delete

Expected result:
the anchor should be removed and nothing else

Actual result:
one of the following:
1. the anchor is removed and the style of the text is ALSO removed
2. the anchor is NOT removed and the editor loses focus
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7182](http://archive.tinymce.com/develop/bugtracker_view.php?id=7182) posted by [tomlevy](http://archive.tinymce.com/profile.php?name=tomlevy)_

> _**Tags:** [chrome anchor tinymce4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
