### ISSUE TITLE
Error in italian translation

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1912]
--- tinymce/langs/it_IT.js
+++ tinymce/langs/it_IT.js
@@ -89,7 +89,7 @@ tinymce.addI18n('it',{
 "Vertical space": "Spazio Verticale",
 "Image description": "Descrizione Immagine",
 "Style": "Stile",
-"Dimensions": "Dimenzioni",
+"Dimensions": "Dimensioni",

It's "Dimensioni", not "Dimenzioni".

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7183](http://archive.tinymce.com/develop/bugtracker_view.php?id=7183) posted by [gtozzi](http://archive.tinymce.com/profile.php?name=gtozzi)_

> _**Tags:** [firefox msie safari chrome opera i18n]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
