### ISSUE TITLE
Youtube video's aren't displayed after update

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1914]
Description of problem:
When inserting a video (insert - Insert video, even tried a youtube plugin) the youtube video isn't displayed. This used to be working in 4.1.4

Steps to reproduce:
1. Click on insert
2. Click on Insert video
3. Enter a Youtube url in the source field or try to inter the embed link into embed
4. Hit insert and save your result
5. NO youtube video is displayed

Expected result:
Youtube video showing with video controls

Actual result:
White field where the youtube content should be. Source tag is change to img tag instead of iframe or html5 video tag

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7185](http://archive.tinymce.com/develop/bugtracker_view.php?id=7185) posted by [boetn](http://archive.tinymce.com/profile.php?name=boetn)_

> _**Tags:** [firefox msie safari chrome opera video youtube 415]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
