### ISSUE TITLE
Error when pressing enter twice before table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1915]
Description of problem:

Steps to reproduce:
1. Open the editor with an empty document
2. Insert a table
3. Place the cursor before the table (in first column, then press left)
4. Hit enter twice

Expected result:

Two paragraphs are inserted

Actual result:

Only one paragraph is inserted, in Firefox the table is corrupted (a &ltg;br> is inserted in a &ltg;tr>), and an error occurs (in EnterKey.js line 315, parentNode is null).
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7186](http://archive.tinymce.com/develop/bugtracker_view.php?id=7186) posted by [Yogu](http://archive.tinymce.com/profile.php?name=Yogu)_

> _**Tags:** [firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
