### ISSUE TITLE
IE bug with css overflow

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1917]
Description of problem: In IE 10, setting overflow: hidden on a container div makes the content very difficult to edit and in some cases can crash the browser.

Steps to reproduce:
1. Go to the linked fiddle in IE 10.
2. Click on the link text. 
3. The container element with overflow: hidden will be selected instead of the actual text.
4. Repeated clicking on the text will occasionally select the actual text inside the div.
5. After selecting the link, open the edit link dialog and click Ok.
6. The browser crashes.

Expected result: Clicking once on the text should select the text and not the containing element with overflow: hidden. Editing a link inside an element with overflow: hidden should not crash the browser.

Actual result: All kinds of selection madness and crashing.

Note that it works as expected in Chrome. It appears to be an issue with how IE handles overflow. I haven't tested any other browsers.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7188](http://archive.tinymce.com/develop/bugtracker_view.php?id=7188) posted by [johsbrit](http://archive.tinymce.com/profile.php?name=johsbrit)_

> _**Tags:** [msie msie10 ie overflow crash]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Sxeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
