### ISSUE TITLE
Can't see/access text area

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1918]
Description of problem:Using TinyMCE in two different instances of Moodle (2.2 & 2.6) two versions of TMCE (3.4 & 3.5).  About 2 months ago the text area began disappearing but the buttons remain functional.  The same thing happens with your version 4 demo on this site.  Works with FF.

Steps to reproduce:
1.Go to any page with TMCE in IE or Chrome.

Expected result: Functional editor

Actual result: only toolbars function; no edit space.  Full screen expands the tool bar but the edit space is invisible--you can see the underlying web page where the text area should be.

See attached screenshot from this site, in Chrome 37. Notice the text area is completely closed.  The resize handle has no effect.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7189](http://archive.tinymce.com/develop/bugtracker_view.php?id=7189) posted by [jerrycobbs](http://archive.tinymce.com/profile.php?name=jerrycobbs)_

> _**Tags:** [msie chrome msie10 chrome13]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
