### ISSUE TITLE
Scroll edge bug

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1920]
Editor should scroll to block edge when scroll occurs by arrow up/down keypress.

Steps to reproduce:
1. Scroll up (to have some space to scroll down)
2. Put cursor into text
3. Push arrow down till editor stops scrolling down

Expected result:
Scroll position will cover bottom edge of &ltg;p> tag.

Actual result:
You will see that there are some space to scroll down more and current scroll position does not cover whole last &ltg;p> tag even if it has no paddings and margins (just line-height).
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7191](http://archive.tinymce.com/develop/bugtracker_view.php?id=7191) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_

> _**Tags:** [firefox msie safari chrome opera scroll]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/jyeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
