### ISSUE TITLE
HierarchyRequestError with <hr> tag

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1922]
Description of problem:
In some cases when &ltg;hr> tag exists in document enter causes HierarchyRequestError

Steps to reproduce:
1. Put cursor into end of firs line (after word "text")
2.
  a) Press Enter, Delete, Enter (FF)
  b) Press ArrowDown, Enter, Enter

Expected result:
No errors

Actual result:
HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7193](http://archive.tinymce.com/develop/bugtracker_view.php?id=7193) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/lyeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
