### ISSUE TITLE
Add support for table cells in textcolor plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1923]
Add bgcolor to table cell when it selected instead of adding span with background color for textcolor plugin

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7194](http://archive.tinymce.com/develop/bugtracker_view.php?id=7194) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_
> 
> _**Tags:** [textcolor tables]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
