### ISSUE TITLE
Copy Paste issue on IE9 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1924]
Description of problem:
This problem used to reproduce in IE9 browser (IE10 it is working fine) using version number 4.0.7
Steps to reproduce:

1.Open Excel sheet and select & copy a range (A4:D4)
2.open tinyMCE editor and enter text in two different lines
3.in third row, paste the selected range from excel sheet
4.the selected range is appearing at the last after adding a number of empty rows
please refer uploaded snapshot (copyPastError2.png)

Expected result: The number of blank rows should not appear immediately after the text (#2 above) 

I have also downloaded the new version number #4.1.5 from http://www.tinymce.com/ and found a new prompt (Please use Ctrl+V/Cmd+V keyboard shortcuts to paste contents) issue while doing the PASTE operation.

Expected result: Prompt should not appear while doing any Paste operation.

Need solution to resolve this issue.

Note: Please refer attached snapshots for more details.

Thanks,
Prashant
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7195](http://archive.tinymce.com/develop/bugtracker_view.php?id=7195) posted by [prashantpadhi](http://archive.tinymce.com/profile.php?name=prashantpadhi)_

> _**Tags:** [msie msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Trapulo** [comment]
abandoned?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
