### ISSUE TITLE
Add a Combo box control on editor toolbar 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1925]
Hi,

Can you please provide me  a solution to add a "Combo box control" on editor toolbox (using the version #4.0.7). Currently I have added  a list box which is working fine but my requirement is to add a combo box control with search functionality. 

Appreciate if somebody can give me a solution to resolve this issue. 

Thanks,
Prashant

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7196](http://archive.tinymce.com/develop/bugtracker_view.php?id=7196) posted by [prashantpadhi](http://archive.tinymce.com/profile.php?name=prashantpadhi)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
