### ISSUE TITLE
Search for bug and feature lists

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1926]
Hi,

it would be nice to have an option to search the bug reports.
It is a pretty basic option for systems of this kind and would help a lot to avoid doubles. So less work for the people working the requests.

Just an idea.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7197](http://archive.tinymce.com/develop/bugtracker_view.php?id=7197) posted by [garyee](http://archive.tinymce.com/profile.php?name=garyee)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
