### ISSUE TITLE
No min-height

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1927]
Hi,

I wanted to have an editor-area looking like one row. So I set the height to 25, but it did not work, the area did not go under 100px. So I concluded that there is a min-height... But it is written nowhere!
Please get rid of it, or at least put it in the configuration documentation!!

Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7198](http://archive.tinymce.com/develop/bugtracker_view.php?id=7198) posted by [garyee](http://archive.tinymce.com/profile.php?name=garyee)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
