### ISSUE TITLE
Inserting anchor on img does not work when img is inside figure element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1928]
Description of problem:
Version: 3.5.11

Steps to reproduce:
1. &ltg;figure>&ltg;img src="image-placeholder.png" alt="" width="300" height="250" />&ltg;/figure>
2. Try to add anchor on the image, click OK

Expected result:
&ltg;figure>&ltg;a href="#">&ltg;img src="image-placeholder.png" alt="" width="300" height="250" />&ltg;/a>&ltg;/figure>

Actual result:
TypeError: elm is null
tiny_mce/plugins/advlink/js/advlink.js:77
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7199](http://archive.tinymce.com/develop/bugtracker_view.php?id=7199) posted by [ozzymir](http://archive.tinymce.com/profile.php?name=ozzymir)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
