### ISSUE TITLE
Unable to overwrite video source 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1929]
Description of problem:
Once we insert a video and then we if try to edit the source of that video to another video it does not work.

Steps to reproduce:
1. Insert a video and save.
2. Select the video just inserted, click on the "insert/edit video" link.
3. Change the source to another video, click save.
4. Instead of displaying the 2nd video, it still displays the 1st video inserted.

Expected result: Once we insert a video and overwrite it with another one, the second video should be set as source.

Actual result: Original video is set as source no matter what.

As an update, we are able to do it, if we change the file name from the "Embed" tab.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7200](http://archive.tinymce.com/develop/bugtracker_view.php?id=7200) posted by [ravish](http://archive.tinymce.com/profile.php?name=ravish)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
