### ISSUE TITLE
Copy & Paste in IE11

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1930]
Description of problem: When using the paste plugin with IE 11; the strip out of a "shift return" is not producing the expect &ltg;br> and is being ignored causing a continuous line.

Steps to reproduce:
1. Cut and paste from attached
2. View results

Expected result: insert of BR
Actual result: continuous line

Additional Notes: The �paste� plugin which is responsible for cleaning the unwanted HTML elements from the source. Only happens in IE11 with a combination of SHIFT+ENTER used for braking new lines.    

We upgrades the versions from 4.0.14 to 4.1.5 and here is the code snippet of the our implementation of the library. 

plugins: "advlist autolink link lists anchor paste autoresize"
mode: "exact",
theme: "modern",
menubar: false,
statusbar: false,
relative_urls: false,
autoresize_min_height: 200,
pagebreak_separator: "&ltg;br/>",
fix_list_elements: true,
language: lang,
valid_elements: "p,ul,ol,li,a[href|target=_blank],strong/b,strong/h1,strong/h2,strong/h3,div,br,em/i",
paste_auto_cleanup_on_paste: true,
paste_strip_class_attributes: "all",
paste_retain_style_properties: "text-align,list-style-type,ul,ol,li",
elements: attrs.id

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7201](http://archive.tinymce.com/develop/bugtracker_view.php?id=7201) posted by [jmccloy](http://archive.tinymce.com/profile.php?name=jmccloy)_

> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
