### ISSUE TITLE
ie11 and ie9 show blank tool buttons

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1932]
Description of problem:

Steps to reproduce:
1. start page with tinymci control in it using a msie browser

Expected result:
see the button icons.

Actual result:
see attachment
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7203](http://archive.tinymce.com/develop/bugtracker_view.php?id=7203) posted by [kimr8r](http://archive.tinymce.com/profile.php?name=kimr8r)_

> _**Tags:** [msie msie9 msie10 msie toolbuttons]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
