### ISSUE TITLE
TinyMCE replace title value to alt value, and alt value set empty

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1933]
Description of problem:

Steps to reproduce:
1. Click ADD Image (mce_swimage)
2. Select image adn set his title & alt
3. Save
4. Open the text with added image

Expected result:

In the html image title replaced to alt value and alt value defined to empty ( after save &ltg;img title="text_title" src="logo.png" alt="text_alt" width="681" height="76" border="0" />)

Actual result:

After load text &ltg;img title="text_alt" src="logo.png" alt="" width="681" height="76" border="0" />

TinyMCE vesion:

		majorVersion : '3',

		minorVersion : '4.8',

		releaseDate : '2012-02-02',

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7208](http://archive.tinymce.com/develop/bugtracker_view.php?id=7208) posted by [Dewilas](http://archive.tinymce.com/profile.php?name=Dewilas)_

> _**Tags:** [alt title imageinsert]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
