### ISSUE TITLE
Can't type into provided plugin text fields when in blockUI

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1934]
Description of problem:  when using tinymce-provided plugins (such as link or insert video) with 4.1.5, not able to edit or put focus on text fields when using malsup's blockUI.  Am able to type into the editor window without issue and able to use other non-text controls in plugins.  

Steps to reproduce:
1.   The referenced fiddle demonstrates this.
2.   Using non-Jquery version of TinyMCE 4.1.5
3.   Using JQuery 1.11.1 & jquery.blockUI 2.66.0
4.   See http://fiddle.tinymce.com/bzeaab/16
5.   Press Show Dialog button.
6.   Click link plugin button.
7.   Attempt to type into URL field
8.   Attempt to put focus into another text field (say, 'Title')

I see now that http://fiddle.tinymce.com/Fhdaab/3 demonstrates the same behavior, but I'm not using a jquery UI dialog.

Expected result:   In step 7., should show what is being typed; in 8., should put focus into Title field.

Actual result:  No response.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7204](http://archive.tinymce.com/develop/bugtracker_view.php?id=7204) posted by [rdnewman](http://archive.tinymce.com/profile.php?name=rdnewman)_
> 
> _**Tags:** [firefox msie safari chrome opera text fields plugins]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/bzeaab/16_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
