### ISSUE TITLE
link_list special characters in title

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1935]
It looks like the link_list in the link plugin does not accept special characters. A euro (�) is shown as a questionmark (?). Using a non breaking space (& nbsp;) doesn't work either.

I am using the editor in iso-8859-1, changing it to utf-8 doesn't fix it.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7205](http://archive.tinymce.com/develop/bugtracker_view.php?id=7205) posted by [white-frank](http://archive.tinymce.com/profile.php?name=white-frank)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
