### ISSUE TITLE
One of the hyperlinks "Installing it as a TinyMCE plugin" redirects to the wrong section

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1936]
Description of problem:

Both hyperlinks in the Table of Contents labeled "Installing it as a TinyMCE plugin" will redirect to the same section below.

Steps to reproduce:
1. Navigate to web page.
2. Click the first link that's labeled "Installing it as a TinyMCE plugin" in the Table of Contents.
3. Notice that you're redirected to the "Installing it as a TinyMCE plugin" section in the PHP section.
4. Click the second link that's labeled "Installing it as a TinyMCE plugin" in the Table of Contents.
5. Notice that you're STILL redirected to the "Installing it as a TinyMCE plugin" section in the PHP section.

Expected result:

Clicking the second link labeled "Installing it as a TinyMCE plugin" should redirect to the .NET section

Actual result:

Still redirected to the PHP section.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7206](http://archive.tinymce.com/develop/bugtracker_view.php?id=7206) posted by [MPaul](http://archive.tinymce.com/profile.php?name=MPaul)_

> _**Tags:** [firefox msie safari chrome opera wiki website]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/wiki.php/MCImageManager:Installation_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
