### ISSUE TITLE
iframe not working with embed code

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1938]
Description of problem:
iframe not working with embed code from http://www.gettyimages.com/
in version 4.1.6. With version 3.4.2 working good

Steps to reproduce:
1. go to Tools -> Source Code 
2. paste any embed code from http://www.gettyimages.com/
3. You will see empty editor textarea. 

Expected result:
Should be shown image like in old version 3.4.2 http://screencast.com/t/Wxl89iUx

Actual result:
Displayed empty textarea http://screencast.com/t/z6RCSUnqu9j

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7209](http://archive.tinymce.com/develop/bugtracker_view.php?id=7209) posted by [fearlesslord](http://archive.tinymce.com/profile.php?name=fearlesslord)_
> 
> _**Tags:** [firefox msie safari chrome opera iframe]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/ozeaab/1_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
