### ISSUE TITLE
Cannot read property 'getRng' of undefined

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1940]
Description of problem:

When going full-screen programmatically right after initialization, an error is thrown:

Cannot read property 'getRng' of undefined
Steps to reproduce:

editor.on('init', function(e) {editor.execCommand('mceFullScreen');});

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7210](http://archive.tinymce.com/develop/bugtracker_view.php?id=7210) posted by [meglio](http://archive.tinymce.com/profile.php?name=meglio)_

> _**Tags:** [chrome 4_1_6 fullscreen]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by mikeelemuel** [comment]
We should re-open the ticket as it is happening on version 5

**Comment by metricjs** [comment]
Hey @mikeelemuel, thanks for commenting on this ticket! We still can't replicate this bug unfortunately. This if the fiddle I created while trying to replicate it: https://fiddle.tiny.cloud/r0haab . Could you please make a [Fiddle](https://fiddle.tiny.cloud) showing the bug?

**Comment by metricjs** [comment]
Apologies, if you can create a replication case, could you please make a new ticket? That will be easier for us to track than this older ticket.
