### ISSUE TITLE
right click on area without blinking cursor can't copy, cut or paste...

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1941]
Description of problem:

Steps to reproduce:
1. Right click lower than where there is a new line.
2. Next it will open a menu to go "Back, Forward, Reload..."
3. Next right click when the cursor is a text cursor and now it will bring up a menu to "Undo, Redo, Copy, Cut, Paste..."

Now if a user tries a TinyMCE 3 editor as found here... 
http://www.tinymce.com/tryit/3_x/custom_formats.php

The user can click anywhere in the editbox and have the option to copy, cut or paste...

I know that users can use keyboard shortcuts, however the use I am using it for makes it so that many people with little computer knowledge can use it and have been having lots of people complaining that there isn't any way to copy, cut or paste...

This happens on all of the latest browsers I have tried, except for IE.
I have not tried on Opera, but not many people have seemed to be using Opera.

Would really appreciate if this could be fixed or do I have to go back to an older TinyMCE? Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7211](http://archive.tinymce.com/develop/bugtracker_view.php?id=7211) posted by [smandres](http://archive.tinymce.com/profile.php?name=smandres)_
> 
> _**Tags:** [firefox safari chrome firefox5 firefox6 firefox7 firefox8 safari4 safari5 safari6 chrome10 chrome11 chrome12 chrome13 copy cut paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/wzeaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
