### ISSUE TITLE
Config option to control the size of the statusbar

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1942]
Since the size of the toolbar items is already changeable by settings toolbar_items_size : 'small', it would be nice to have a configuration option to also control the size of the statusbar, whose font size seems to be quite big to several users.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7212](http://archive.tinymce.com/develop/bugtracker_view.php?id=7212) posted by [Callidior](http://archive.tinymce.com/profile.php?name=Callidior)_
> 
> _**Tags:** [statusbar skin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
