### ISSUE TITLE
Showing a menu in custom_style based on selector

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1944]
It would be neat with some way to show or hide a "submenu" in custom_style based on either a selector on the sub-menu or by hiding sub-menus with no children. 

The fiddle demonstrates that this is not currently implemented. 
In my specific usecase, I have a lot of different styling based on the markers context. This gets cluttered and is frustrating for the user - "Why show me six menus when only one is relevant" 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7216](http://archive.tinymce.com/develop/bugtracker_view.php?id=7216) posted by [Wertisdk](http://archive.tinymce.com/profile.php?name=Wertisdk)_
> 
> _**Tags:** [tinymce4 custom_style formatting]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/8zeaab/2_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
