### ISSUE TITLE
Add setting to extend TinyMCE icon library

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1945]
Description of problem:
Currently TinyMCE has a set of icons and is a user wishes to extend these icons they have to go through a number of cumbersome steps to do so.  First they must add a content_css setting to their init script to link their custom icon font css file. Then they have to edit every single class in that file to include mce-i-[customicon] classes in order to be able to use them as TinyMCE icons - this is fine if you only have a few custom icons, but if you have a lot (say 500) that is hours of css editing to make those icons available in MCE.

Solution:
It would be far better to have a new setting, something like:

extend_icons: '/path/to/icon_file.css'

that way all the classes in the new icon file would be accessible in TinyMCE which means no matter which icon font generator you are using (fontastic, moon.io etc) you can use their standard output css files without having to spend hours adding TinyMCE specific classes.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7215](http://archive.tinymce.com/develop/bugtracker_view.php?id=7215) posted by [Paladine](http://archive.tinymce.com/profile.php?name=Paladine)_
> 
> _**Tags:** [firefox msie safari chrome opera icons]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
