### ISSUE TITLE
"theme_advanced_resizing" not working in version 4

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1946]
In tinyMCE3 the editor remember the old custom size. In tinyMCE4 this not working anymore. Coming this feature next time back?

http://www.tinymce.com/wiki.php/Configuration3x:theme_advanced_resizing_use_cookie

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7217](http://archive.tinymce.com/develop/bugtracker_view.php?id=7217) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
