### ISSUE TITLE
autoresize has false size with start

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1947]
With plugin "autoresize" the editor starts in false(maximum?) dimensions. See fiddle example above. In my (localhost) webpage the editor loading very fast so I see a big editor and after ~1s the editor magical minimized (not animated) to standard size. This looks not so fine. ;)

Remove plugin "autoresize" _fix_ this problem, but now the cool feature autoresize is missing. :D

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7218](http://archive.tinymce.com/develop/bugtracker_view.php?id=7218) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/9zeaab_

**Comment by FabriceGaudin** [comment]
@spocke Hello,
This problem is still occuring, it's not only in Chrome, but also in Firefox and Internet Explorer
Any news ?

**Comment by fyrkant** [comment]
@FabriceGaudin Are you still having problems with this? If so, can you create a new issue with a [fiddle](http://fiddle.tinymce.com/) reproducing it? Thank you!

**Comment by FabriceGaudin** [comment]
@fyrkant Thank you, I still face this issue so I created a new one here: https://github.com/tinymce/tinymce/issues/3699
