### ISSUE TITLE
"No misspellings found" always displayed in English

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1948]
Description of problem:

Steps to reproduce:
1. use spellchecker with no wrongly spellde words

"No misspellings found" in spellckecker plugin is hardcoded and always displayed in English.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7219](http://archive.tinymce.com/develop/bugtracker_view.php?id=7219) posted by [bubdou](http://archive.tinymce.com/profile.php?name=bubdou)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
