### ISSUE TITLE
Issue with full screen plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1949]
Description of problem:
Jquery version:2.0.3
JqueryUI version:1.10.3
Tinymce version 3.4.6
Steps to reproduce:
1.Create jqueryUI dialog with tinymce editor in it
2.Click on full screen button

Expected result:
we should be able to type in full screen editor

Actual result:
State remains in original editor and it is not migrating to full screen editor .

This is happening only when tinymce editor is in jquery UI dialog
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7220](http://archive.tinymce.com/develop/bugtracker_view.php?id=7220) posted by [sreedivya](http://archive.tinymce.com/profile.php?name=sreedivya)_

> _**Tags:** [msie msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
