### ISSUE TITLE
Font-family not inherited by default in table cell using Chrome or Firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1950]
Description of problem:

In TinyMCE 4.1.6 (using Chrome version 37.0.2062.124 m or Firefox version 31), Font-family inside a table cell revert to Arial no matter what font-family you specify in the body tag of your css file attached to the TinyMCE editor. The workaround I found is to set "font-family: inherited" in the td tag of your css file.

Expected result:

Font-family should be inherited by default from the closest parent when in a table cell.

Actual result:

TinyMCE revert to Arial font unlet you specify "font-family: inherited" in the td tag of your css file.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7221](http://archive.tinymce.com/develop/bugtracker_view.php?id=7221) posted by [Steph](http://archive.tinymce.com/profile.php?name=Steph)_
> 
> _**Tags:** [firefox chrome table cell chrome firefox fontfamily]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/full.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
