### ISSUE TITLE
IT - Translation

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1951]
Description of problem:
Error in translation of word View. 
For correct from "Visualiza" to "Visualizza"

Steps to reproduce:
1. Open folder of tinymce
2. Open folder langs
3. Open file it_if.js
4. Search string '"View": "Visualiza"'
5. Correct the word and save the file

Expected result: Bug Fix

Actual result: have bug

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7222](http://archive.tinymce.com/develop/bugtracker_view.php?id=7222) posted by [jam830](http://archive.tinymce.com/profile.php?name=jam830)_
> 
> _**Tags:** [firefox msie safari chrome opera it visualiza traduzione]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
