### ISSUE TITLE
Inserting Bullet points, inserts only 1

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1952]
Description of problem:

Steps to reproduce:

When the following multiple lines of text from notepad is pasted into the WYSIWYG editor part and you highlight it and choose numbered bullet points:
Text
Text
Text

And highlighted - > And the bullet point icon is used then only the first line will have a bullet point (should be all 3).
1. text
   text
   text

Expected result:
1. text
2. text
3. text

Actual result:
1. text
   text
   text

I was able to replicate this in your tool:
http://fiddle.tinymce.com/

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7223](http://archive.tinymce.com/develop/bugtracker_view.php?id=7223) posted by [Ulrik_Lumesse](http://archive.tinymce.com/profile.php?name=Ulrik_Lumesse)_
> 
> _**Tags:** [firefox msie firefox5 firefox6 firefox7 firefox8 msie7 msie8 msie9 msie10 bullet points firefox msie ie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
