### ISSUE TITLE
HTML-Comment delete after removing nearby character

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1953]
Description of problem:

Steps to reproduce:
1. source code: a&ltg;!--comment-->b 
2. remove b in editor

Expected result:
a&ltg;!--comment-->

Actual result:
a
## 

This is really annoying when using protected controlstructures (if's) that get deleted all the time

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7224](http://archive.tinymce.com/develop/bugtracker_view.php?id=7224) posted by [Royvdb](http://archive.tinymce.com/profile.php?name=Royvdb)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Wzeaab_

**Comment by bariscicek** [comment]
I got bite with this bug. I want to submit a patch, though I could not find what could remove the #comment. I can see before saxparser, during sanitize #comment is already deleted. As I could not trace it yet after 'key press' or 'edit' event yet, but if someone give a hand it would help me to find the source of the problem quicker.

**Comment by bariscicek** [comment]
This bug does not exist on Firefox (49) and IE 11.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
