### ISSUE TITLE
corrupt file with download function

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1954]
Description of problem:
If you try to download a file, eG image, the file will be downloaded corrupt.

I solved the problem:
Added the function ob_clean() in line 177 in the file plugins/moxiemanager/classes/Http/Response.php:

```
protected function streamLocalFile($localPath) {
    ob_clean();
    readfile($localPath);
}
```

That deletes the output buffer.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7225](http://archive.tinymce.com/develop/bugtracker_view.php?id=7225) posted by [noah](http://archive.tinymce.com/profile.php?name=noah)_
> 
> _**Tags:** [firefox msie safari chrome opera download moxiemanager]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
