### ISSUE TITLE
Alignment issue of word copy pasted content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1955]
Description of problem:

Steps to reproduce:
1.type some content in ms-word 2007. center align the text.
2.select all & copy
3.paste in tinymce editor

Expected result: text should be center aligned

Actual result: text is left aligned

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7226](http://archive.tinymce.com/develop/bugtracker_view.php?id=7226) posted by [dj_borkar](http://archive.tinymce.com/profile.php?name=dj_borkar)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
