### ISSUE TITLE
How to make tinymce read-only after it has been initialized 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1956]
Description of problem:Tinymce 3.4.8 version

Steps to reproduce:
1.In my project i am using tinymce
2.At a particular senior i want to make tinymce as read-only for that i used a property contenteditable="false"  
3.when i use that it make that as readonly but the problem is, in the tinymce body right click functionality is working
4.by that i can able to add image or paste the data etc.. when it is in readonly mode

Expected result: editing related things should not work when i use contenteditable="false"

Actual result: contenteditable="false" when i use this editing related options are working

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7227](http://archive.tinymce.com/develop/bugtracker_view.php?id=7227) posted by [rakesh4231](http://archive.tinymce.com/profile.php?name=rakesh4231)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
