### ISSUE TITLE
image plugin doesn't respect document_base_url

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1957]
Description of problem:
When opening a image-dialog and you enter a image URL (or select using a filemanager) the image will be checked to get the image-dimensions. If this URL is relative it should respect the base url that's set in the document_base_url settings of TinyMCE. It doesn't.

Steps to reproduce:
1. Have a document_base_url set in the tinymce settings
2. Add an image to the editor and enter a relative path
3. onChange of the path-field the image will be checked for it's dimensions
4. This will use use the given path relative to the current path instead of the given base url

Expected result:
It uses the base_url set in the editor settings

Actual result:
It uses the current url to check relative image-paths.

Possible solution (Partial code of the plugins/image/plugin.js file, this is what i have done now):
if (!meta.width && !meta.height) {
	// Rewrite if document_base_url is used
	var thisUri = this.value();
	var pattern = /^https?:\/\//i;
	if (!pattern.test(thisUri) && editor.settings.document_base_url) thisUri = editor.settings.document_base_url + thisUri;
	// Get image width
	getImageSize(thisUri, function(data) {
		if (data.width && data.height && imageDimensions) {
			width = data.width;
			height = data.height;

			win.find('#width').value(width);
			win.find('#height').value(height);
		}
	});
}

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7228](http://archive.tinymce.com/develop/bugtracker_view.php?id=7228) posted by [TheCollector](http://archive.tinymce.com/profile.php?name=TheCollector)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
