### ISSUE TITLE
select element will be deleted

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1959]
Description of problem:
  Using source editor to input something like following.
&ltg;p>&ltg;select name="xxx">
&ltg;option selected="selected" value="1">a&ltg;/option>
&ltg;option value="2">b&ltg;/option>
&ltg;/select>&ltg;/p>

  when return to the main editor and push enter key, the select element will be deleted!!

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7230](http://archive.tinymce.com/develop/bugtracker_view.php?id=7230) posted by [wce01](http://archive.tinymce.com/profile.php?name=wce01)_

> _**Tags:** [msie msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
