### ISSUE TITLE
If put full-screen programmatically, the vertical page scrollbar position is lost once TinyMCE exists full-screen mode

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1960]
Description of problem:

If you initialize tinymce and make it full-screen programmatically, the vertical scrollbar position of the page is lost once TinyMCE exists full-screen mode.

Please see the fiddle for a quick reproduction.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7231](http://archive.tinymce.com/develop/bugtracker_view.php?id=7231) posted by [meglio](http://archive.tinymce.com/profile.php?name=meglio)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/u0eaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
