### ISSUE TITLE
Menu should change from "Insert" to "Edit" for selected Image and Link

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1961]
The tooltip text of the toolbar buttons has the text "Insert/edit image" and "Insert/edit link" which is fine.

However both the right click context menu and the drop down menu will always be labeled "Insert Image" and "Insert Link".
However, if an image or link is selected, it will do an edit of the currently selected image or link, not an insert.
Therefore, for it to say "Insert" is misleading to the user. (And I had a user who was actually mislead by it.)
It should change the text to "Edit ..." and then back to "Insert ..." when the element is not selected anymore.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7232](http://archive.tinymce.com/develop/bugtracker_view.php?id=7232) posted by [avromf](http://archive.tinymce.com/profile.php?name=avromf)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
