### ISSUE TITLE
Undo/Redo not working correctly after text/background color change

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1962]
Description of problem: Undo/Redo not working correctly after text/background color change

Steps to reproduce:
1.Go to link above and enter text anywhere inside editor
2.Select text somewhere else in page and change either its text or background color
3.Hit undo to undo color change

Expected result:
Hitting undo should undo color change

Actual result:
Hitting undo does remove the color change but it also removes the text entered before the color change. Also, when hitting redo it never bring back the color change.

Interestingly, if another action is performed after the color change then undo/redo work correctly.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7234](http://archive.tinymce.com/develop/bugtracker_view.php?id=7234) posted by [primet21](http://archive.tinymce.com/profile.php?name=primet21)_

> _**Tags:** [firefox msie safari chrome opera undo redo color]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/full.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
