### ISSUE TITLE
Range error when clicking between editors using the noneditable plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1964]
Description of problem:

When clicking between editors that contains noneditable elements. A range error occurs in some browsers

Steps to reproduce:
1. Open the fiddle
2. Click back and forth between the to editors

Expected result:
No error

Actual result:
An error is thrown(See attached image)

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7236](http://archive.tinymce.com/develop/bugtracker_view.php?id=7236) posted by [albinohrn](http://archive.tinymce.com/profile.php?name=albinohrn)_

> _**Tags:** [safari chrome safari8 chrome chromecanary chromedev noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/C0eaab/4_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
