### ISSUE TITLE
Editor object replicated infinitely when Safari 7.1 Trashmail extension is enabled

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1965]
Description of problem: the editor is spawned within itself infinitely. You must have Trashmail installed in Safari 7.1. Occam says this is a bug with Trashmail. But who knows? It worked in Safari 7.0. I have not tried with OS X Yosemite.

Steps to reproduce:
1. Upgrade to Mavericks 10.9.5, Safari 7.1
2. Install Trashmail extension 1.1.10
3. Enjoy editor inception (see attached; ah nope tried to attach a .swf, you don't accept it. Please switch over to JIRA, we'll give it to you free! BTW we use TinyMCE in Confluence)

Expected result: 
Single editor object on page

Actual result:
Infinite series of editors spawned, each new one within the last. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7237](http://archive.tinymce.com/develop/bugtracker_view.php?id=7237) posted by [waden](http://archive.tinymce.com/profile.php?name=waden)_
> 
> _**Tags:** [safari safari7]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
