### ISSUE TITLE
Firefox unwanted style cleanup

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1966]
Description of problem:

Steps to reproduce:
1. go to http://fiddle.tinymce.com/P0eaab (config adapted such that &ltg;i> with class info is not cleaned)
2. click in the menu bar on "tools" and then on "Source code"
3. paste the following html code
&ltg;div class="eight columns row">
&ltg;h2>Tarieven seizoensopening 2014&ltg;/h2>
Prijs per persoon per nacht met inbegrip van een uitgebreid ontbijt en 's avonds een culinair driegangenmenu (apero-wijn-water-koffie):
&ltg;ul class="list unstyled-list">
&ltg;li>&ltg;i class="small-arrows">&ltg;/i>Kamer 1: 125 &euro; ppppn*&ltg;/li>
&ltg;li>&ltg;i class="small-arrows">&ltg;/i>Kamer 2: 115 &euro; ppppn*&ltg;/li>
&ltg;li>&ltg;i class="small-arrows">&ltg;/i>Kamer 3: 115 &euro; ppppn*&ltg;/li>
&ltg;li>&ltg;i class="small-arrows">&ltg;/i>Kamer 4: 100 &euro; ppppn*&ltg;/li>
&ltg;/ul>
&ltg;/div>
4. Hit the "OK" button
5. Put cursor in editor window right behind the "5" in "125"
6. Hit backspace such that "125" is changed in "12"
7. Click in the menubar on "Tools" then on "Source code"

Expected result (only snippet with problem shown):
&ltg;li>&ltg;i class="small-arrows">Kamer 1: 12 &euro; ppppn*&ltg;/li>
&ltg;li>&ltg;i class="small-arrows">&ltg;/i>Kamer 2: 115 &euro; ppppn*&ltg;/li>

Actual result (only snippet with problem shown):
&ltg;li>Kamer 1: 12 &euro; ppppn*&ltg;/li>
&ltg;li>&ltg;i class="small-arrows">&ltg;/i>Kamer 2: 115 &euro; ppppn*&ltg;/li>

Additional Notes:
-somehow the backspace did clean up the "&ltg;i class="small-arrows">" on the first li element
-performing the same experiment in chrome does not yield the error
-all plugins in FireFox were disabled in this test to avoid any interference

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7238](http://archive.tinymce.com/develop/bugtracker_view.php?id=7238) posted by [danielles](http://archive.tinymce.com/profile.php?name=danielles)_

> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/P0eaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
