### ISSUE TITLE
Plugin 'Table' enhancement

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1967]
Can we have a field for caption text instead of check box, so that the content publisher will not have to go into HTML and add a caption text. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7239](http://archive.tinymce.com/develop/bugtracker_view.php?id=7239) posted by [rakshith](http://archive.tinymce.com/profile.php?name=rakshith)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
