### ISSUE TITLE
The dropdown formats not working for selected table.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1968]
The dropdown formats not working for selected table.

Steps to reproduce:
1. Select table by selecting text in whole table
2. Choose from formats dropdown the default item

Expected result:
Table should have selected style.

Actual result:
No style selected
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7240](http://archive.tinymce.com/develop/bugtracker_view.php?id=7240) posted by [macem](http://archive.tinymce.com/profile.php?name=macem)_

> _**Tags:** [firefox msie safari chrome table formats]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Y0eaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
