### ISSUE TITLE
Cannot cut and paste table if it's the only element cut.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1969]
Description of problem: Cannot cut and paste table if it's the only element cut.

- Tested on 4.x and edge version.  
- This is not reproducible in 3.x.
- Can cut and paste table if copy element above or below table together with table.
- Copy and paste table works correctly.

Steps to reproduce:
1. Create a table with multiple rows and columns
2. Highlight from first cell to last cell to cover entire table
3. Press Ctrl+X to cut 
4. Press Ctrl+P to paste

Expected result: Entire table is pasted

Actual result: Only table content is pasted (with no table tags)

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7241](http://archive.tinymce.com/develop/bugtracker_view.php?id=7241) posted by [wy](http://archive.tinymce.com/profile.php?name=wy)_

> _**Tags:** [chrome chrome table paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/j1eaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
