### ISSUE TITLE
Image resizer is visible outside the text editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1973]
Description of problem:
The problem is, when I inserted picture which is bigger than tinyMce editor. On IE9 and IE10, the resizable rectangles are visible outside the tinymce editor, as you can see on picture. I tested it on your current version(4.1.6) on your web site.

Steps to reproduce:
1. Insert image into editor.
2. Make image bigger by mouse dragging 

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7251](http://archive.tinymce.com/develop/bugtracker_view.php?id=7251) posted by [jiri_kroutil](http://archive.tinymce.com/profile.php?name=jiri_kroutil)_

> _**Tags:** [msie msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
