### ISSUE TITLE
[Paste Plugin] Fake Word Lists conversion needs to be optional

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1975]
Fake Word Lists are always converted to lists using the paste plugin.

It is a nice feature brought by the Word filter, but sometimes it is not desirable to convert these list. For example when "bullist" and "numlist" toolbar are not used.
In these cases you do want to filter the Word content, but no generation of ul, ol and li tags.

Skipping the conversion should be a nice configuration option.

e.g. editor.settings.paste_skip_convert_word_fake_lists = true;

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7246](http://archive.tinymce.com/develop/bugtracker_view.php?id=7246) posted by [cst](http://archive.tinymce.com/profile.php?name=cst)_
> 
> _**Tags:** [firefox msie safari chrome paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/p1eaab/4_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
