### ISSUE TITLE
On iOS any keypress in editor makes cursor outside the box

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1976]
Description of problem:

Steps to reproduce:
1. On start typing in editor, cadet goes elsewhere on page and also page layout changes on iPad

Expected result: Cadet should be in editor

Actual result: Cadet position changes

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7254](http://archive.tinymce.com/develop/bugtracker_view.php?id=7254) posted by [amolshevkari](http://archive.tinymce.com/profile.php?name=amolshevkari)_

> _**Tags:** [safari]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by bartonsprings** [comment]
@TinyMCE-User, How did you solve the issue. I am having similar issue. I am using 4.5.6 version.

**Comment by blackcathikari** [comment]
@bartonsprings Would you be able to tell us more about this bug? We weren't able to replicate it before, but we also weren't quite sure how to. I'm assuming this happens when TinyMCE is used as part of a website, not an app?
