### ISSUE TITLE
CTRL + mouse drag move the content instead of copy it

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1977]
Description of problem:
CTRL + mouse drag move the content instead of copy it

Steps to reproduce:
1. keep CTRL key down and drag selected context in the editor.
(problem on Chrome. IE11 and FF32 is ok)

Expected result:
copy content

Actual result:
move content.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7247](http://archive.tinymce.com/develop/bugtracker_view.php?id=7247) posted by [bubdou](http://archive.tinymce.com/profile.php?name=bubdou)_

> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
