### ISSUE TITLE
formatting gets lost while shifting last line to above line 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1978]
Description of problem:

Steps to reproduce:
1.select font size and type
2.type 2-3 line in editor
3.shift last line to above line pressing delete button
4.check that formatting gets lost of last line 

Expected result:formatting not gets lost 

Actual result:last lines formatting gets lost.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7250](http://archive.tinymce.com/develop/bugtracker_view.php?id=7250) posted by [snehal1112](http://archive.tinymce.com/profile.php?name=snehal1112)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
