### ISSUE TITLE
TinyMCE replaces <canvas> tags with <p>&nbsp;</p> despite valid_elements allowing *[*]

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1979]
Description of problem: In the source editor if the user adds a &ltg;canvas> tag outside a paragraph the editor removes it and replaces it with an empty &ltg;p> tag or a &ltg;p> tag with an &nbsp; in it.

In our testing we noticed that if the canvas tag was placed inside a &ltg;p> tag along with at least another character the editor will keep it. However, if the canvas tag was alone inside the p tag or was outside, the editor will remove it. 

This happens while valid_elements is set to '_[_]' and invalid_elements is not set. 

Steps to reproduce:
1. Open source editor
2. Scroll to the bottom of the mark-up
3. Type &ltg;canvas id="myCanvas" width="200" height="100" style="border:1px solid #000000;">&ltg;/canvas>
4. Click OK
5. Open source editor again and look for the &ltg;canvas> tag.

Expected result: Canvas tag should stay.

Actual result: Canvas tag is replaced by &ltg;p> tag.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7256](http://archive.tinymce.com/develop/bugtracker_view.php?id=7256) posted by [bahar_mohammadi](http://archive.tinymce.com/profile.php?name=bahar_mohammadi)_
> 
> _**Tags:** [msie msie10 msie11 valid_elements canvas]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by sriram-rajendran** [comment]
> Description of problem: In the source editor if the user adds a &ltg;canvas> tag outside a paragraph the editor removes it and replaces it with an empty &ltg;p> tag or a &ltg;p> tag with an   in it.
> 
> In our testing we noticed that if the canvas tag was placed inside a &ltg;p> tag along with at least another character the editor will keep it. However, if the canvas tag was alone inside the p tag or was outside, the editor will remove it.
> 
> This happens while valid_elements is set to '_[_]' and invalid_elements is not set.
> 
> Steps to reproduce:
> 
> 1. Open source editor
> 2. Scroll to the bottom of the mark-up
> 3. Type &ltg;canvas id="myCanvas" width="200" height="100" style="border:1px solid #000000;">&ltg;/canvas>
> 4. Click OK
> 5. Open source editor again and look for the &ltg;canvas> tag.
> 
> Expected result: Canvas tag should stay.
> 
> Actual result: Canvas tag is replaced by &ltg;p> tag.
> 
> > _**Legacy information imported from TinyMCE bug tracker:**_
> > _[#T7256](http://archive.tinymce.com/develop/bugtracker_view.php?id=7256) posted by [bahar_mohammadi](http://archive.tinymce.com/profile.php?name=bahar_mohammadi)_
> > _**Tags:** [msie msie10 msie11 valid_elements canvas]_
> > _**Status:** Open_
> > _**Resolution:** None_
> > _**Attached URL:** none_

How did you fix this issue?

**Comment by gregBerthelot** [comment]
Issue is still there
