### ISSUE TITLE
Color selection not working correctly in IE when valid_styles exists

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1980]
Description of problem: When valid_styles option is present (even if empty) it causes color (fore and back) not to work correctly in IE

Steps to reproduce:
1.Enter text
2.Highlight text and attempt to change its color

Expected result:
The text changes color

Actual result:
A span is created but color doesn't change. Clicking color again sometimes causes color to change

If the valid_styles option is removed then everything works as expected
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7249](http://archive.tinymce.com/develop/bugtracker_view.php?id=7249) posted by [primet21](http://archive.tinymce.com/profile.php?name=primet21)_

> _**Tags:** [msie msie8 msie9 msie10 msie11 ie color]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/71eaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
