### ISSUE TITLE
Formatting button goes off state

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1981]
Description of problem:

Steps to reproduce:
1. Load demo
2. Click bold and italic button
3. Click on edit area
4. Bold and italic formatting goes off

Expected result: These button should be in clickable state

Actual result: Button state goes off

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7252](http://archive.tinymce.com/develop/bugtracker_view.php?id=7252) posted by [amolshevkari](http://archive.tinymce.com/profile.php?name=amolshevkari)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** https://tickets.ingramcontent.com/browse/OUPOP-581_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
