### ISSUE TITLE
Formatting is not working when we focus out the mouse from the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1982]
Description of problem:

Steps to reproduce:
1. Go to the http://www.tinymce.com/
2. Select some text in the editor and remove the focus from the editor
3. Again without clicking in the editor, select any formatting options like bold, underline, etc..
4. Changes are not reflecting in the editor for previously selected text.
5. This is working as expected in Chrome.

Expected result: Formatting should work for selected text even we focus out the mouse from the editor.

Actual result: Nothing seen when we try to apply formatting.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7253](http://archive.tinymce.com/develop/bugtracker_view.php?id=7253) posted by [samvegolap](http://archive.tinymce.com/profile.php?name=samvegolap)_
> 
> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
