### ISSUE TITLE
Formatting toolbar buttons not reflecting state of selected text in IE 11 (4.x)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1983]
This problem is reproducible on the TinyMCE site demo using IE 11:

Steps to reproduce:
1. Select text
2. Use formatting buttons(Bold, Italic, Underline, for example)
3. Deselect the text
4. Select the formatted text again

Expected result:
Appropriate formatting buttons should have a pressed state.

Actual result:
Appropriate formatting buttons don't have the pressed state. 
However, when just have the cursor inside the formatted text, or partially selecting the formatted text, the buttons do reflect the correct state. 
Also noticed, that whenever the first character from the formatted (e.g. bold) text is selected, the state is not reflected by the button.

I'm interested in workarounds too.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7255](http://archive.tinymce.com/develop/bugtracker_view.php?id=7255) posted by [beerwin](http://archive.tinymce.com/profile.php?name=beerwin)_

> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
