### ISSUE TITLE
paste_preprocess not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1984]
Description of problem:

Steps to reproduce:
1.as per your demo example
tinymce.init({
    paste_preprocess: function(plugin, args) {
        console.log(args.content);
        args.content += ' preprocess';
    }
});
2.
Copy the text from some file
3.
Paste it on editor
4.
no event will be generated
5.

Expected result:
should log pasted contents
Actual result:
No event raised
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7257](http://archive.tinymce.com/develop/bugtracker_view.php?id=7257) posted by [rohit123](http://archive.tinymce.com/profile.php?name=rohit123)_

> _**Tags:** [firefox paste_preprocess]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
