### ISSUE TITLE
Draggable stick to the cursor 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1985]
Description of problem:

Steps to reproduce:
1. While we dragging to resize box. Dragger sticks to pointer. Then without clicking we can resize box.

Expected result: When mouse up from dragger, resize of box shouldn't be happen

Actual result: Box resizing after dragging stops.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7258](http://archive.tinymce.com/develop/bugtracker_view.php?id=7258) posted by [amolshevkari](http://archive.tinymce.com/profile.php?name=amolshevkari)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
