### ISSUE TITLE
Add and extend_entities option

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1986]
I would like to be able to extend the entities list to include &hairsp; without the need to list the full default list and then append mine to the end, having an extend_entities option would be great

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7260](http://archive.tinymce.com/develop/bugtracker_view.php?id=7260) posted by [reholmes27](http://archive.tinymce.com/profile.php?name=reholmes27)_
> 
> _**Tags:** [entities]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by TrevorPT** [comment]
+1

We just ran into this ourselves.  Or maybe update TinyMCE to include [HTML5 entities](https://dev.w3.org/html5/html-author/charref)?  I looked at doing this but to include them all would create one nasty string (there are over 1400).

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
