### ISSUE TITLE
import css merging ignores background colors

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1987]
Description of problem:
When using the link_class_list, image_class_list and table_class_list, the font color and size, as well as border colors seem to be merged as expected, but background colors are ignored. When viewing the dropdown list that is generated the background-color value that's included in the merged span tag is set to "rgb (0,0,0,0) no matter what it's set to in the imported css file.

(See attached file for visual comparison or, using the fiddle link above, click the "image" icon and click the "class" dropdown menu.)

Steps to reproduce:
1.Create external image_class_list defining black text, grey border with a black background gradients. Like this...
.colorbox_black {
border-radius:5px; /\* for all css3 browsers except firefox _/
-moz-border-radius: 5px; /_ for firefox 3.6+ _/
border:1px #000000 solid;
background:#000000; /_ for non-css3 browsers */

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#000000', endColorstr='#3f3f3f'); /\* for IE _/
background: -moz-linear-gradient(top,  #000000 0%, #3f3f3f 100%); /_ FF3.6+ _/
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#000000), color-stop(100%,#3f3f3f)); /_ Chrome,Safari4+ _/
background: -webkit-linear-gradient(top,  #000000,  #3f3f3f); /_ Chrome10+,Safari5.1+ _/
background: -o-linear-gradient(top,  #000000,  #3f3f3f); /_ Opera 11.10+ _/
background: -ms-linear-gradient(top,  #000000 0%,#3f3f3f 100%); /_ IE10+ _/
background: linear-gradient(top,  #000000 0%,#3f3f3f 100%); /_ W3C */
padding:5px;

-webkit-box-shadow: 0px 0px 3px 1px rgba(0, 0, 0, .1);
-moz-box-shadow: 0px 0px 3px 1px rgba(0, 0, 0, .1);
box-shadow: 0px 0px 3px 1px rgba(0, 0, 0, .1);
color:#FFFFFF !important;
}

Expected result:
Dropdown list item with white text inside a black box with a black border

Actual result:
Dropdown list item with white text inside a white box with a black border. Since the box background is being set to transparent the white text is not visible and the only thing the end user sees is a black box outline.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7261](http://archive.tinymce.com/develop/bugtracker_view.php?id=7261) posted by [CF_freak](http://archive.tinymce.com/profile.php?name=CF_freak)_
> 
> _**Tags:** [firefox msie safari chrome styles backgroundcolor dropdown classes link_class_list image_class_list table_class_list table_cell_class_list]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/72eaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
