### ISSUE TITLE
Garbage characters showing

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1988]
Description of problem:

Steps to reproduce:
1. Go to http://www.tinymce.com/tryit/basic.php
2. Press Tools > Source code and input this:

&ltg;p>This is a Job Description field.&ltg;/p>
&ltg;ul>
&ltg;li>This is a Job Description field.&ltg;/li>
&ltg;li>This is a Job Description field.&ltg;/li>
&ltg;li>This is a Job Description field.&ltg;/li>
&ltg;/ul>
&ltg;ol>
&ltg;li>This is a Job Description field.&ltg;/li>
&ltg;li>This is a Job Description field.&ltg;/li>
&ltg;li>This is a Job Description field.&ltg;/li>
&ltg;/ol>
&ltg;p>&ltg;strong>This is a Job Description field. &ltg;/strong>&ltg;em>This is a Job Description field.&ltg;/em> &ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span> &ltg;strong>&ltg;em>&ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span>&ltg;/em>&ltg;/strong>&ltg;/p>
&ltg;p>&ltg;a href="htt://www.test.com/" title="test link">This is a Job Description field.&ltg;/a>&ltg;/p>
&ltg;p style="text-align: left;">This is a Job Description field.&ltg;/p>
&ltg;p style="text-align: center;">This is a Job Description field.&ltg;/p>
&ltg;p style="text-align: right;">This is a Job Description field.&ltg;/p>
&ltg;p>&ltg;span style="color: #ff0000;">&ltg;strong>This is a Job Description field. &ltg;/strong>&ltg;em>This is a Job Description field.&ltg;/em> &ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span> &ltg;strong>&ltg;em>&ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span>&ltg;/em>&ltg;/strong>&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span style="background-color: #000000; color: #ffff00;">&ltg;strong>This is a Job Description field. &ltg;/strong>&ltg;em>This is a Job Description field.&ltg;/em> &ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span> &ltg;strong>&ltg;em>&ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span>&ltg;/em>&ltg;/strong>&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span style="font-family: comic sans ms,sans-serif;">&ltg;strong>This is a Job Description field. &ltg;/strong>&ltg;em>This is a Job Description field.&ltg;/em> &ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span> &ltg;strong>&ltg;em>&ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span>&ltg;/em>&ltg;/strong>&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span style="font-family: comic sans ms,sans-serif; font-size: medium;">&ltg;strong>This is a Job Description field. &ltg;/strong>&ltg;em>This is a Job Description field.&ltg;/em> &ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span> &ltg;strong>&ltg;em>&ltg;span style="text-decoration: underline;">This is a Job Description field.&ltg;/span>&ltg;/em>&ltg;/strong>&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span style="font-family: comic sans ms,sans-serif;">&ltg;strong>&ltg;em>&ltg;span style="text-decoration: underline;">&ltg;br />&ltg;/span>&ltg;/em>&ltg;/strong>&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span style="background-color: #000000; color: #ffff00;">&ltg;strong>&ltg;em>&ltg;span style="text-decoration: underline;">&ltg;br />&ltg;/span>&ltg;/em>&ltg;/strong>&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span style="color: #ff0000;">&ltg;strong>&ltg;em>&ltg;span style="text-decoration: underline;">&ltg;br />&ltg;/span>&ltg;/em>&ltg;/strong>&ltg;/span>&ltg;/p>
1. Press submit
2. Notice that there are garbage characters. Perhaps this is because of the last few lines of the code having &ltg;p>&ltg;/p> but does not have any content
3. This does not happen in the previews 3.x series.

Expected result: html Tags having no content should NOT show

Actual result: html tags having no content shows

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7262](http://archive.tinymce.com/develop/bugtracker_view.php?id=7262) posted by [danieljohn](http://archive.tinymce.com/profile.php?name=danieljohn)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
