### ISSUE TITLE
Can't use inside web components due to lack of shadow DOM traversal

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1989]
Description of problem:

TinyMCE will not work when the selector refers to an element that is inside a web component's shadow DOM. Now that shadow DOM traversal is a standard browser feature, this should be an init option. The referenced URL demonstrates code that would work if TinyMCE supported shadow DOM traversal.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7263](http://archive.tinymce.com/develop/bugtracker_view.php?id=7263) posted by [cayblood](http://archive.tinymce.com/profile.php?name=cayblood)_
> 
> _**Tags:** [firefox msie safari chrome polymer webcomponents shadowdom installation]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/H2eaab_

**Comment by MeloJR** [comment]
Hi! I'm new to TinyMCE but I'm planning to use it inside a Polymer element too. I don't know if TinyMCE has this feature but this problem can be solved if the `selector` option (or a different `init` option) accepts an HTML element. With this change, the following code should work.
````
ready: function() {
                tinymce.init({
                    selector: this.$.content,
                    ...
                });
            }
````

**Comment by spocke** [comment]
We have thoughts on having the ability to init on an element instead of a selector and also improve web component support but it's a tricky since there needs to be a bunch of core changes to have it working properly in shadow dom.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
