### ISSUE TITLE
The toolbar options appear in top to bottom fashion on IE 9 with tinymce 4.1.6

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1990]
Tiny mce version - 4.1.6

IE version - 9

Description of problem: The tool bar menu items come in top to bottom fashion as shown in attached screenshot. I have tried the meta tag solution prescribed in the last post. However, it does not work.

  &ltg;meta http-equiv="X-UA-Compatible" content="IE=edge" />

Steps to reproduce:
1. View the page on IE 9

Expected result: The menu items should appear in arranged fashion.

Actual result: It appears in top to bottom fashion.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7266](http://archive.tinymce.com/develop/bugtracker_view.php?id=7266) posted by [rohitiscancerian](http://archive.tinymce.com/profile.php?name=rohitiscancerian)_

> _**Tags:** [msie msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
