### ISSUE TITLE
Paste using the browser contextmenu fails on Firefox 20-29

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1991]
Description of problem:
When using copy/paste from the rightclick browser contextmenu the paste plugin does not get triggered (using keyboard keys to copy/paste works).
Verified on FF 24.8.1 ESR. Tinymce-Version 3.5.8 to 3.5.11 .
Not tested much on versions before 3.5.8 except 3.4.4 - works here.

Steps to reproduce:
1. Select one word in the editor using the mouse
2. rightklick and choose copy from the browser contextmenu
3. set the cursor to an empty line in the editor
4. rightklick and choose paste from the browser contextmenu
5. the text is not visible, but got put into the editor DOM inside a DIV
---> i did some research and found out that the onPaste event got fired from FF, but that the paste Plugin does nothing

Expected result:
copied text is visible in the DOM

Actual result:
copied text is invisible in the DOM in the wrong html element and much worse pastepreprocess was not triggered!

The image attached shows the Element in the DOM using Firebug.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7264](http://archive.tinymce.com/develop/bugtracker_view.php?id=7264) posted by [stefanw](http://archive.tinymce.com/profile.php?name=stefanw)_
> 
> _**Tags:** [firefox ff paste firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
