### ISSUE TITLE
Media Plugin - Cannot Change SWF Source

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1992]
Description of problem:
Cannot change Flash/SWF source file within the "Insert Video" window. You CAN make changes if you edit the "Embed" code directly, but you cannot change the source using the "Source" textbox or by selecting a new Flash/SWF file within MoxieManager. 

Steps to reproduce:
1. Insert an SWF video object using the "Insert Video" dialog (i.e. using the tinymce media plugin).
2. Attempt to update the video source by changing the "Source" textbox (either manually or by selecting a new file within MoxieManager)
3. Hit "OK" to accept the change

Expected Result:
The object tag should be updated with the new source file location, such as: &ltg;object data="new-source.swf" ...>

Actual result:
The old SWF location is used.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7265](http://archive.tinymce.com/develop/bugtracker_view.php?id=7265) posted by [crazy888s](http://archive.tinymce.com/profile.php?name=crazy888s)_

> _**Tags:** [firefox msie safari chrome flash swf media embed]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
