### ISSUE TITLE
Autosave plugin reports empty textarea as modified

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1993]
Description of problem:

The autosave plugin reports an unmodified empty textarea as being modified, and pops up an alert when trying to leave the page. This behavior is specific to IE 11, and happens with TinyMCE 3.5.11 (I have not checked that with TinyMCE 4.x).

Steps to reproduce:
1. Go to http://fiddle.tinymce.com/y3eaab/1
2. Click the link below the editor

Expected result:

Navigate to http://tinyme.com/ without any alert.

Actual result:

Alert about unsaved modifications pops up.

This issue is caused by a strange behavior in IE 11, where document.body.innerHTML == "&ltg;br>", even though document.body.firstChild === null.

A possible workaround for the IE 11 issue seems to be to modify tinymce.Editor.getContent() (line 14583 in tiny_mce_src.js) from:

  content = body.innerHTML;

to 

  content = body.firstChild ? body.innerHTML : "";

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7267](http://archive.tinymce.com/develop/bugtracker_view.php?id=7267) posted by [cmb69](http://archive.tinymce.com/profile.php?name=cmb69)_
> 
> _**Tags:** [msie msie11]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/y3eaab/1_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
