### ISSUE TITLE
Incorrect copy/paste from Word file

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1994]
Description of problem:

Steps to reproduce:
1.open attached file with Word
2.copy the whole text
3.paste in the tinymce area
4.
5.

Expected result:
obtain an identical text
Actual result:
the line beginning with "M." becomes the first paragraph of an ordinated list
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7268](http://archive.tinymce.com/develop/bugtracker_view.php?id=7268) posted by [emgepub](http://archive.tinymce.com/profile.php?name=emgepub)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
