### ISSUE TITLE
search & replace regular expressions, up/down/all, in selection

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1995]
It would be nice to have search & replace possibility for regular expressions, search direction up/down/whole file, and search/replace in selection available.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7269](http://archive.tinymce.com/develop/bugtracker_view.php?id=7269) posted by [sevec](http://archive.tinymce.com/profile.php?name=sevec)_
> 
> _**Tags:** [search replace regular expression selection]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
