### ISSUE TITLE
button:hover { background: red; }  goes into tinymce ui widgets

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1996]
Description of problem:

Steps to reproduce:
1. use button:hover { background: red; } in the document which contains tinymce
2. hover any menu or button inside tinymce

Expected result:
tinymce skin's button color

Actual result:
red buttons, ignoring tinymce's skin

Fix:
.@{prefix}-container button:hover {
    background: transparent;
}
in the tinymce css/less file
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7270](http://archive.tinymce.com/develop/bugtracker_view.php?id=7270) posted by [cirix](http://archive.tinymce.com/profile.php?name=cirix)_

> _**Tags:** [firefox msie safari chrome css]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/l4eaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
