### ISSUE TITLE
changed content is not getting saved

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1998]
Description of problem:
Hi,

I am using TinyMce(4.x) editor attached to text-area in a dialog with ok button(ajax form submit),
The issue is if I edit/change the content in tinymce editor and press the ok button,
ideally the changed content should be saved and send to the server, but in my case it is not happening 
it is sending the old data itself to server.

Can any one give a solution to save the content before I click on the Ok button.
The solution should also support for IE8+, firfox, chrome, mac safari browsers

Regards,
Ramesh

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7272](http://archive.tinymce.com/develop/bugtracker_view.php?id=7272) posted by [valasa](http://archive.tinymce.com/profile.php?name=valasa)_

> _**Tags:** [firefox msie safari chrome firefox msie8 msie9 msie10 msie11 safari9 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
