### ISSUE TITLE
No translation for the "Link list"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1999]
Description of problem:

There is no translation for the "Link List" in the Link Dialog. The Link List field appears not always, but only if the link_list property is set. Possibly, that is why it has no translation. I looked into the language files, the translation is really missing.

Steps to reproduce:
1. Use the editor in the German language.
2. Specify some links for the property "link_list".
3. Call the Link Dialog.

Expected result:

The caption of the Link List field should be in German.

Actual result:

The caption of the Link List field is always in English.

All translation files for all languages should be updated!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7273](http://archive.tinymce.com/develop/bugtracker_view.php?id=7273) posted by [qtx](http://archive.tinymce.com/profile.php?name=qtx)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
