### ISSUE TITLE
The tooltip is shown and then hidden immediately for a nested menu item

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2000]
Visually, there is no tooltip shown while I expect it.
However, debugging shows that the tooltip is shown and then hidden immediately.

First, the tooltip gets shown:
2014-11-24_20-18-56.png

Then, the mouseenter event bubbles to all parents of the menu item:
2014-11-24_20-28-04.png and 2014-11-24_20-26-10.png

Finally, the tooltip disappears once the event is fired for one of parents:
2014-11-24_20-34-52.png

It seems as if the problem is with the bubbling of the "mouseenter" event. It probably shouldn't bubble to parents.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7274](http://archive.tinymce.com/develop/bugtracker_view.php?id=7274) posted by [meglio](http://archive.tinymce.com/profile.php?name=meglio)_
> 
> _**Tags:** [firefox msie safari chrome 4_1_6 tooltips]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
