### ISSUE TITLE
<br> is being converted to <div> no matter what..

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2002]
Description of problem:

Steps to reproduce:
1.&ltg;div dir="ltr">line1&ltg;div>line2&ltg;/div>&ltg;div>line3&ltg;/div>&ltg;div>&ltg;br>&ltg;/div>&ltg;div>line5&ltg;/div>&ltg;/div> is being converted to &ltg;div dir="ltr">line1
&ltg;div>line2&ltg;/div>
&ltg;div>line3&ltg;/div>
&ltg;div>&ltg;/div>
&ltg;div>line5&ltg;/div>
&ltg;/div>
2.
3.The BR is missing
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7276](http://archive.tinymce.com/develop/bugtracker_view.php?id=7276) posted by [nadavb](http://archive.tinymce.com/profile.php?name=nadavb)_
> 
> _**Tags:** [br div]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
