### ISSUE TITLE
Bug: background-color not inherited in nested span

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2003]
Description of problem: To create a single line of text side-by-side with different emphasis (bold, italics, underline) or different font sizes we have to create a span inside span. The CSS background-color property is not inherited by other span elements.

Steps to reproduce:
Procedure 1-
1. type text
2. change font-size type more text
3. select all text
4. change background-color
5. tinyMCE will create a nested spanned text &ltg;p>&ltg;span style="background-color: #ff6600;">small&ltg;span style="font-size: 36pt;">Big&ltg;/span>&ltg;/span>&ltg;/p>

Procedure 2-
1. type text
2. change background-color
3. select part of the text
4. change font size
5. &ltg;p>&ltg;span style="background-color: #ff6600;">small&ltg;span style="font-size: 36pt;">bigsmall&ltg;/span>&ltg;/span>&ltg;/p>
Expected result:
tinyMCE will apply background-color style in all selected text (spans elements)

Actual result:
background-color is only applied to the first span and not the children.

Feature request:
Apply background-color to every child element.

Notes:
Other CSS properties by default are inherited. (color, underline, bold, italicize). Only background-color cannot be inherited.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7277](http://archive.tinymce.com/develop/bugtracker_view.php?id=7277) posted by [SonnG](http://archive.tinymce.com/profile.php?name=SonnG)_
> 
> _**Tags:** [firefox msie safari chrome firefox chrome backgroundcolor span fontsize nested]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/LReaab/2_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
