### ISSUE TITLE
Ability to append the toolbar to a specific element (in inline mode)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2004]
Description of problem: When you use inline mode to edit contents inside a scrollable/overflowing element the toolbar is appended to "body" and when you scroll it slip away.

Expected result: To be able to specify an element for the toolbar to be appended instead of "document.body" so that it will scroll together with the edited content.
## panel.renderTo(inlineToolbarContainer || document.body).reflow(); 

Note that specifying an inlineToolbarContainer doesn't work because in that case it doesn't use a floatPanel but a simple panel that will not be positioned near the edited content.

FYI jQueryUI widgets supports an "appendTo" property to alter the default behaviour (appending to body).

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7278](http://archive.tinymce.com/develop/bugtracker_view.php?id=7278) posted by [bago](http://archive.tinymce.com/profile.php?name=bago)_
> 
> _**Tags:** [firefox msie safari chrome inline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by zlepper** [comment]
Has there been any progress on this?

**Comment by donShakespeare** [comment]
Doesn't this fix the issue completely?
https://www.tinymce.com/docs/configure/editor-appearance/#fixed_toolbar_container

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
