### ISSUE TITLE
mceNonEditable not working on Nexus

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2005]
Description of problem:

Steps to reproduce:
1. The non-editable part is also editable. When we click on the non-editable then the whole text get replaced by typing character. 
This happens only in Nexus.

Expected result: Non-Editable part should be there.

Actual result: Non-editable part is replaced by new input.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7279](http://archive.tinymce.com/develop/bugtracker_view.php?id=7279) posted by [amolshevkari](http://archive.tinymce.com/profile.php?name=amolshevkari)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/3_x/noneditable_content.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
