### ISSUE TITLE
Line Break is not being recognised as new li item

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2008]
Description of problem:

Steps to reproduce:
1.goto http://www.tinymce.com/tryit/3_x/full.php in source code add b1&ltg;br/>b2&ltg;br/>b3
2.go back to normal view, highlight all 3 rows of text
3.press unordered list this creates code 
&ltg;ul>
&ltg;li>b1&ltg;/li>
&ltg;li>b2&ltg;/li>
&ltg;li>b3&ltg;/li>
&ltg;/ul>
4.go to http://www.tinymce.com/tryit/full.php (or any other version 4 tryit) and perform same test
5.code created this time is
&ltg;ul>
&ltg;li>b1&ltg;br />b2&ltg;br />b3&ltg;/li>
&ltg;/ul>

Expected result:
&ltg;ul>
&ltg;li>b1&ltg;/li>
&ltg;li>b2&ltg;/li>
&ltg;li>b3&ltg;/li>
&ltg;/ul>
Actual result:
&ltg;ul>
&ltg;li>b1&ltg;br />b2&ltg;br />b3&ltg;/li>
&ltg;/ul>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7282](http://archive.tinymce.com/develop/bugtracker_view.php?id=7282) posted by [mflowers](http://archive.tinymce.com/profile.php?name=mflowers)_
> 
> _**Tags:** [firefox msie chrome firefox msie9 msie11 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/3_x/full.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
