### ISSUE TITLE
Layout enhancements (minor)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2010]
Description of problem:
The mouse pointer image hovering over buttons only shows "pointer" if it is inside the &ltg;b> element but not outside.

Easy fix:
These style rules can fix this easily (watch out for reset rules!).

.mce-btn {
    cursor: pointer;
}

.mce-btn.mce-disabled {
    cursor: default;
}

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7284](http://archive.tinymce.com/develop/bugtracker_view.php?id=7284) posted by [Felix Riesterer](http://archive.tinymce.com/profile.php?name=Felix Riesterer)_
> 
> _**Tags:** [firefox msie safari chrome css ui widgets]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
