### ISSUE TITLE
multiline confirm dialog messages

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2011]
I'd like the confirm dialog (editor.windowManager.confirm) to take an array of strings. Each item in the array would render as a separate line in the confirmation dialog.

Additionally I'd like the confirm dialog to split any string at their \n characters so you can do both hand over a \n-separated string or an array of strings.

This would work nicely with i18n support... ;-)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7285](http://archive.tinymce.com/develop/bugtracker_view.php?id=7285) posted by [Felix Riesterer](http://archive.tinymce.com/profile.php?name=Felix Riesterer)_
> 
> _**Tags:** [dialog ui widget]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
