### ISSUE TITLE
Adding media is not working in mvc4 razor asp.net application

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2013]
Description of problem:

Steps to reproduce:
1.go to tinyMCE toolbar click on insert media button
2.add youtube url and click insert
3.showing video in preview but not in editor
4.not showing anything in editor
5.

Expected result:must show video in editor

Actual result:not showing video in editor only showing control box

Please reply as soon as possible

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7287](http://archive.tinymce.com/develop/bugtracker_view.php?id=7287) posted by [shailendrashinde](http://archive.tinymce.com/profile.php?name=shailendrashinde)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
