### ISSUE TITLE
Latest Version Does not save in IE10

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2014]
We upgraded from 4.0.7 to 4.1.7 and noticed that we now have an issue with clients on older versions of IE.

The TinyMCE loads up fine and the editor works, but when you save no values are changed.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7288](http://archive.tinymce.com/develop/bugtracker_view.php?id=7288) posted by [trevski](http://archive.tinymce.com/profile.php?name=trevski)_

> _**Tags:** [msie msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
