### ISSUE TITLE
Save state of custom package

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2019]
When building a custom download, it would be very useful if a file or string was generated that could be then uploaded or pasted to generate a new download.

Currently, when a new version comes out, I need to re-evaluate all the plugins to see which ones I want to include.  Sometimes I'll forget one.  Having a record of the plugins & other options I chose previously, would make it much easier for me to upgrade versions

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7293](http://archive.tinymce.com/develop/bugtracker_view.php?id=7293) posted by [pickle](http://archive.tinymce.com/profile.php?name=pickle)_
> 
> _**Tags:** [custom package download]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
