### ISSUE TITLE
bug/feature filter: "created by me"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2020]
would be great to have a filter in this issue tracker, so one can filter the issues to the subset which was created by the current logged-in user

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7294](http://archive.tinymce.com/develop/bugtracker_view.php?id=7294) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
