### ISSUE TITLE
Tinymce overlays element beeing edited

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2021]
Didn't found a reduced testcase yet, but describing the issue here nevertheless. maybe it rings a bell for somebode.

Using the Tiny in inline-mode and opening the editor on a element which is at the very top of the page makes it overlay the actual element beeing edited.

Since my element is smaller then the tinymce toolbar users are not able to edit the content at all (except using the "source" button).

see the screeshots. If required I could send a user/pw so you could see this issue at one of our servers.

side-note: our website users a fixed table header
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7295](http://archive.tinymce.com/develop/bugtracker_view.php?id=7295) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_

> _**Tags:** [firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
