### ISSUE TITLE
Tinymce looses focus when trying to type on ipad 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2022]
Description of problem:when Tinymce inculded in IFRAME it looses its focus when trying to type on ipad it works fine with android devices but it fails when run on ipad .

Steps to reproduce:
1.Include tinymce in iframe 
2.try to type anything on ipad on portrait & landscape mode 
3. cursor jumps anywhere on the page 
4.
5.

Expected result:cursor should be stick with current text we are typing in .

Actual result:Cursor jumps anywhere on the page .

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7296](http://archive.tinymce.com/develop/bugtracker_view.php?id=7296) posted by [ranjeet.hange](http://archive.tinymce.com/profile.php?name=ranjeet.hange)_

> _**Tags:** [ipad ios ios7 ios8 iframe]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by alanwong22** [comment]
This problem happens in iOS Versions 8.3 and 9.1 but seems fine in 9.0.
Is there an expected timeline for this fix?
Thanks

**Comment by yuridsi** [comment]
Any updates about this one guys?

**Comment by spocke** [comment]
Couldn't reproduce it here:
https://www.tinymce.com/docs/demo/basic-example/

That page has tinymce inside a iframe since code pen is on another domain.

**Comment by yuridsi** [comment]
@spocke Thank you for your quick response!

I'm using iPhone 6 with iOS 9.2. It's reproducible on the page you pointed. 

HTR

1. Put the cursor before the logo (it's on the first row in content example)
2. Start typing 

AR 
The screen jumps so only HMTML/JS/RESULT line will be displayed

ER
The screen should stay on the editor screen

On this screen it doesn't seem to be painful but on pages where tinyMCE is placed in the bottom on the page it looks very weird when it jumps back and forth. 

Thanks Johan!

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
