### ISSUE TITLE
TinyMCE replace selected text when contenteditable=false

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2023]
Description of problem:

TinyMCE is replacing selected text when contenteditable body attribute is set to false.

Steps to reproduce:
1. Open the url to the example
2. Select the word "content" on the editor text.
3. Press any key, such as space, letter or number

Expected result:

The content suppose to be unchanged.

Actual result:

TinyMCE is replacing the selected text to the typed key.

-- This situation was testes on MSIE, Chrome and Firefox, and the bug was reproduced only on Chrome.

Thanks for the attention.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7297](http://archive.tinymce.com/develop/bugtracker_view.php?id=7297) posted by [leandro.bueno](http://archive.tinymce.com/profile.php?name=leandro.bueno)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/15eaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
