### ISSUE TITLE
contenteditable attribute removed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2025]
Description of problem:
The contenteditable attribute is removed from source html when editor is loaded, but attribute is not added after

Steps to reproduce:
1. load a page with content with contenteditable="false"
2. submit form
3. submited source has no contenteditable attribute

1. load a page with content with contenteditable="false"
2. open the "source code"
3. no contentedutable attribute either

Expected result:
Having the contenteditable attribute still present

Actual result:
attribute is stripped from source

Idea:
Having a way to choose either to have the "contenteditable" attribute, "mceNonEditable" class, or both, added to source code (source tool) and submited value (I am using angularjs with ui-tinymce), so behavior is persisted correctly.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7299](http://archive.tinymce.com/develop/bugtracker_view.php?id=7299) posted by [MaitreDede](http://archive.tinymce.com/profile.php?name=MaitreDede)_

> _**Tags:** [chrome chrome contenteditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/75eaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
