### ISSUE TITLE
IndexSizeError in moveToBookmark on IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2027]
Description of problem: When showing a dialog to a user in IE, any content selection the user has made is lost. So, we call getBookmark() before the dialog opens, and moveToBookmark in the dialog callback. But, the moveToBookmark call fails due to an IndexSizeError in getRng, which is part of the moveToBookmark call stack.

Steps to reproduce:
1. Double-click one of the words in the editor to select it.
2. Click the link button in the toolbar
3. Select Ok from the dialog window.
4. Check the IE dev tools console window for the error.

Expected result: In Chrome, the content selection is never lost. IE should restore it through the bookmark. This worked in 3.5.11: http://fiddle.tinymce.com/g6eaab

Actual result: IndexSizeError, and selection isn't restored.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7301](http://archive.tinymce.com/develop/bugtracker_view.php?id=7301) posted by [dspeer](http://archive.tinymce.com/profile.php?name=dspeer)_

> _**Tags:** [msie msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/h6eaab_

**Comment by DmitriyTrt** [comment]
Experienced the same issue and found out that we don't need to bookmark selection and restore it anymore in TinyMCE 4. The class tinymce.FocusManager handles all that for us and we don't have to implement this workaround over and over again in plug-ins.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
