### ISSUE TITLE
isDirty returns false even if content in editor is changed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2028]
Description of problem:
editor.isDirty() is returning false even if the content in the editor is changed.

Steps to reproduce:
1. Open the fiddle
2. Add more "!" or uppercase letters

Expected result:
The isDirty should change to true

Actual result:
It's not. It will change when i write something without holding the shiftKey. 
I realize that this might seem like a corner case but this means that isDirty cannot be relied on to know whether data is changed or not.

The problem is in the UndoManager.js (https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/UndoManager.js#L146). I checks if any modifier key is pressed. I can se why ctrl and cmd keys are a problem since that they cannot be used to add text, but the shift key can. I think at least shiftKey should be excluded from this check since many people starts their typing with a capital letter.

What is your opinion on this?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7304](http://archive.tinymce.com/develop/bugtracker_view.php?id=7304) posted by [albinohrn](http://archive.tinymce.com/profile.php?name=albinohrn)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/s6eaab_

**Comment by nathancarter** [comment]
For convenience, the link in my previous comment is now https://github.com/tinymce/tinymce/issues/2224 in the new GitHub issues tracker.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
