### ISSUE TITLE
Noneditable span deleted on backspace even when cursor is not next to it.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2029]
Description of problem:
When using a noneditable span and typing text behind it, backspace will not delete the newly typed text, but the noneditable span.

Steps to reproduce:
1. load tinymce with noneditable plugin and define class for noneditable
2. create a noneditable span in the editor
3. put cursor after noneditable span
4. type a few letters
5. hit backspace

Expected result:
I'd expect the last of the typed letters to be deleted

Actual result:
The newly typed letters stay intact, but the noneditable span in the beginning of the line is deleted.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7302](http://archive.tinymce.com/develop/bugtracker_view.php?id=7302) posted by [efrancis](http://archive.tinymce.com/profile.php?name=efrancis)_

> _**Tags:** [firefox msie safari chrome noneditable delete]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/k6eaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
