### ISSUE TITLE
Cursor "stuck" in non-editable span

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2030]
Description of problem:

Steps to reproduce:
1. Open http://fiddle.tinymce.com/l6eaab/1
2. Place the cursor on "end" in the first line
3. Move the cursor left toward start with the keyboard

Expected result:
Cursor moves past the noneditable span.

Actual result:
Cursor ends up "stuck" at the start of the noneditable span.

Reproduced in firefox 34.0.1.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7303](http://archive.tinymce.com/develop/bugtracker_view.php?id=7303) posted by [PSPvZ](http://archive.tinymce.com/profile.php?name=PSPvZ)_

> _**Tags:** [firefox firefox noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/l6eaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
