### ISSUE TITLE
Broken Ctrl+Left/Right behaviour on FF mac

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2031]
Description of problem:
tinyMCE prevents default behaviour for FF in case 
Ctrl+Left/Right was pressed. In MacOS this hotkey acts
like Home/End on Windows, and there is no preventDefault called for Chrome,
so in Chrome it acts like in whole system (for a MacOS it is Home/End).

Steps to reproduce:
1.Go to http://www.tinymce.com (u must be on MacOS)
2.Put cursor in mid of any non-empty line
3.Press Ctrl+Left

Expected result:
Cursor will jump into start of line

Actual result:
Cursor jumps through the word

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7307](http://archive.tinymce.com/develop/bugtracker_view.php?id=7307) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_
> 
> _**Tags:** [firefox firefox macos firefox hotkey]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
