### ISSUE TITLE
Define to allow only one class in an element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2032]
In some cases, it makes sense to add one class only, 
i.e. I have defined groups with "relative font-sizes", "predefined font-colors", etc.

Idea is to have an new command word like "group" with a number, that allows only one class that are in the same group (number),
ie:

{title: 'Relative font-size', items: [
    {title: '90%', classes: "fs90", group: 1},
    {title: '110%', classes: "fs110", group: 1},
    {title: '120%', classes: "fs120", group: 1},
]},   

{title: 'Font color', items: [
    {title: 'Important', classes: "cImportant", group: 2},
    {title: 'Highlight', classes: "cHighlight", group: 2}
]},   

In this way you could have separate groups where only one selected class is allowed.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7305](http://archive.tinymce.com/develop/bugtracker_view.php?id=7305) posted by [Pfoto](http://archive.tinymce.com/profile.php?name=Pfoto)_
> 
> _**Tags:** [classes style_formats class]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by sgalinski** [comment]
I just looked for exactly this feature in tinymce. If there is any priorization, I'm pretty sure that this one is needed by many people out there. I would just add that not only the classes should be respected, but all attributes and styles of this format. Thanks for this awesome editor! :+1:

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
