### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null in tinymce.js:22561

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2033]
Description of problem:
I'm currently trying to implement a plugin for v. 4.1.7 (see: attachment). I created a button which, when clicked, opens a new window. The window is initialized with a body/items array which contains both inline object literals and variables of type "Control" created by tinymce.ui.Factory.create() .

[...]
body: [
    {
        type: 'label',
        text: editor.editorManager.i18n.translate('code_input')
    },
    textbox, // created by factory
    {
        type: 'label',
        text: editor.editorManager.i18n.translate('preview')
    },
    preview // created by factory
],
[...]

When the defined onPostRender-callback is triggered I try to access one of the ui elements (preview variable) created by the factory to exchange its content by calling &ltg;control>.innerHtml('x'). This works fine, but leads to the described TypeError when the window is rendered internally by the tinymce library.

Steps to reproduce:
1. Install the attached "latex" plugin (file system)
2. Run a TinyMCE v. 4.1.7 with the "latex" plugin added to the tinymce configuration
3. Enter some text
4. Select the text with your mouse
5. Click on the left plugin button
6. Check your firebug or developer console.

By examining the TinyMCE v. 4.x API I'm not able to identify where I did something wrong.

I attached a patch (screenshot) which solves the problem on my local mashine.

Please advise.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7308](http://archive.tinymce.com/develop/bugtracker_view.php?id=7308) posted by [mjansenDatabay](http://archive.tinymce.com/profile.php?name=mjansenDatabay)_
> 
> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
