### ISSUE TITLE
Input field cannot be edited when cursor left in TinyMCE editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2034]
Description of problem:
Input field cannot be edited when cursor left in editor and clicking Next (see fiddle). 

Latest TinyMCE version.

Browser: at least MSIE 11. Maybe other IE?

Steps to reproduce:
1. Enter text in editor and leave cursor visible (ie do not remove the focus from editor)
2. click Next
3. Try adding in input field. You cannot in IE.

Note: If we add text in editor and then click on document (blur the editor) before clicking Next... the input field can accept edits.

Expected result: input can always be editable.

Actual result: input cannot be editable when cursor in tinyMCE editor

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7309](http://archive.tinymce.com/develop/bugtracker_view.php?id=7309) posted by [Fab](http://archive.tinymce.com/profile.php?name=Fab)_
> 
> _**Tags:** [msie msie11 input msie edit focus blur]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/z6eaab/5_

**Comment by mykbaker** [comment]
This is a major issue for me and has taken me forever to track down. Is there any work around for this?

**Comment by fyrkant** [comment]
@mykbaker Are you still having this issue? If so can you please create a new issue with a fiddle reproducing it? Thank you.
