### ISSUE TITLE
Feature: add custom XML enclosing tag buttons/style

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2035]
Hi,

I wish to use tinymce as a nice XML editor, so I need to be able to select some text and than apply some custome XML tag, just as other tags such as &ltg;strong>, &ltg;dfn>, &ltg;cite>, etc.

For example, let's suppose I select some text, say "This is a test" than I click on a created button/or select some style and the inner html would than become "&ltg;mytag>This is a test&ltg;/mytag>"

Unfortunately this does not work

style_formats: [
        {title: 'my XML', items: [
        {title: 'tag1', inline: 'tag1'},
        {title: 'tag2', inline: 'tag2'},
        {title: 'tag3', inline: 'tag3'},
        {title: 'tag4', inline: 'tag4'},
        ]},
]},

Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7310](http://archive.tinymce.com/develop/bugtracker_view.php?id=7310) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_
> 
> _**Tags:** [firefox msie safari chrome xml tag button]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
