### ISSUE TITLE
Wrapper with div ignores ul if there is a sub-ul (makes 3 divs)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2036]
Description of problem:
If I select a block of text (paragraph with one ul and a sub-ul and wrap around a div the div ist closed before the ul and started again in the sub-ul.

Steps to reproduce:
Copy the following text in the editor:
&ltg;p>First Paragraph&ltg;/p>
&ltg;ul>
&ltg;li>First List-Item
&ltg;ul>
&ltg;li>First Sub-List-Item&ltg;/li>
&ltg;/ul>
&ltg;/li>
&ltg;li>Second Item&ltg;/li>
&ltg;/ul>

Expected result:
The whole selection should be wrapped with the div.

Actual result:
3 div are created (instead of one).

&ltg;div>First Paragraph&ltg;/div> &ltg;!-- 1st div here -->
&ltg;ul>
&ltg;li>
&ltg;div>First List-Item  &ltg;!-- 2nd div re-opened here -->
&ltg;ul>
&ltg;li>First Sub-List-Item&ltg;/li>
&ltg;/ul>
&ltg;/div>&ltg;!-- 2nd div closed here -->
&ltg;/li>
&ltg;li>
&ltg;div>Second Item&ltg;/div>&ltg;!-- 3rd div here -->
&ltg;/li>
&ltg;/ul>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7306](http://archive.tinymce.com/develop/bugtracker_view.php?id=7306) posted by [Pfoto](http://archive.tinymce.com/profile.php?name=Pfoto)_

> _**Tags:** [chrome chrome wrapper list div]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
