### ISSUE TITLE
Context menu removing image selection

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2037]
Description of problem: image selection is removing when content menu is opened

Steps to reproduce:
1. select image
2. right click on image

Expected result:
context menu is open and image remain selection.

Actual result:
context menu is open and previous element get selection.

PS: work in IE 11.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7311](http://archive.tinymce.com/develop/bugtracker_view.php?id=7311) posted by [ZDIMA](http://archive.tinymce.com/profile.php?name=ZDIMA)_

> _**Tags:** [safari chrome safari7 chrome image context_menu]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
