### ISSUE TITLE
fullscreen broken in 4.1.8 ?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2038]
Description of problem:

Steps to reproduce:
1. Create simple page that uses TinyMCE 4.1.7 from cachefly - //tinymce.cachefly.net/4.1/tinymce.min.js
2. In your tinyMCE.init statement, make sure fullscreen is one of the plugins and you have a setup value like 

    setup: function(editor) {
      editor.on('init', function(e) {
        editor.execCommand('mceFullScreen');
      });
    }

3. Open the page and note that fullscreen works, although sometimes you have to resize the browser to really get it to work.
4. Get the latest sources from github, which is 4.1.8 and build them and change your page to references the tinymce.min.js that you build.
5. Open the page and note that fullscreen does not work.  It doesn't matter if you resize the page or do anything else.

Expected result:  fullscreen should work

Actual result: fullscreen doesn't work

My hunch is the code that calculates the height in pixels isn't accounting for the fullscreen setting, as I'm seeing the height explicitly set to a height that isn't 100%.  Instead it's about 50%.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7312](http://archive.tinymce.com/develop/bugtracker_view.php?id=7312) posted by [bminer](http://archive.tinymce.com/profile.php?name=bminer)_

> _**Tags:** [firefox msie safari chrome fullscreen]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
