### ISSUE TITLE
media plugin and broken audio altenrative

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2039]
Description of problem:

Steps to reproduce:
1. insert -> insert video
2. in source input paste http://www.blogdrive.com/music/Savage_Land_hi.mp3 (or other audio url)
3. change tab to embed
4. change tab to General
5. in alternative source input paste http://wikidpad.sourceforge.net/help/html/demo/files/demo/ballon.mp3 (or other audio file)
6. change tab to embed

Expected result:
&ltg;audio controls="controls" src="http://www.blogdrive.com/music/Savage_Land_hi.mp3">
&ltg;source src="http://wikidpad.sourceforge.net/help/html/demo/files/demo/ballon.mp3" type="audio/mpeg" />
&ltg;/audio>

Actual result:
&ltg;audio controls="controls" src="http://www.blogdrive.com/music/Savage_Land_hi.mp3">&ltg;/audio>
and alternative source input is empty afte going back

If You do it in one go without switching tabs after You change tabs alternative source input is empty and embed doesn't change if You change any field

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7313](http://archive.tinymce.com/develop/bugtracker_view.php?id=7313) posted by [JakubZ](http://archive.tinymce.com/profile.php?name=JakubZ)_
> 
> _**Tags:** [firefox msie safari chrome media audio]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
