### ISSUE TITLE
word wrapping not work on firefox and IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2041]
TinyMCE 4.1.7.
Word wrapping seems not work on last version of firefox and IE, if i write long text that go over the border of box, this not wrap and go over with a scroll bar.
I want line breaks once the width of my text area is reached for continuous strings such as web links.
With chrome seems work well, but with other browsers i need declare word-wrap: break-word; in my css

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7315](http://archive.tinymce.com/develop/bugtracker_view.php?id=7315) posted by [hanser](http://archive.tinymce.com/profile.php?name=hanser)_
> 
> _**Tags:** [firefox msie firefox msie11 nowrap wordwrap]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
