### ISSUE TITLE
ForeColor execCommand is no longer fired

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2043]
Description of problem:
In previous versions of TinyMCE's textcolor plugin, you could catch the color it was changing to and make adjustments. Now this command is not 

Steps to reproduce:
1. Run the following code from a page with mce-editor in wp3.9:
tinymce.activeEditor.on('execCommand', function() {console.log(arguments);} )
1. Note that it fires a ForeColor event.
2. Update wp4.0, which has the later textcolor plugin.
3. Run the same code, note that it doesn't fire the execCommand.

Previously it seems it was registering a command with:

```
editor.addButton('forecolor', {
    type: 'colorbutton',
    tooltip: 'Text color',
    selectcmd: 'ForeColor',
    panel: {
        role: 'application',
        ariaRemember: true,
        html: renderColorPicker,
        onclick: onPanelClick
    },
    onclick: onButtonClick
});
```

Expected result:
It should fire execCommand

Actual result:
There's no way to catch the changed-font-color event.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7317](http://archive.tinymce.com/develop/bugtracker_view.php?id=7317) posted by [Luke_sf](http://archive.tinymce.com/profile.php?name=Luke_sf)_
> 
> _**Tags:** [firefox msie safari chrome textcolor]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
