### ISSUE TITLE
Add data-width or some other identifier to media width/height field

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2045]
In the "insert image" dialog, the width and height input fields have aria-label="Width" and aria-label="Height" attributes in the DOM. This enables one to populate the fields after selecting an image. The callback called by TinyMCE is provided with the id of the file name input field, so:
        $(win.document.getElementById(input).parentNode.parentNode.parentNode.parentNode.parentNode).find('[aria-label="Width"]').attr('value', '50%');
        $(win.document.getElementById(input).parentNode.parentNode.parentNode.parentNode.parentNode).find('[aria-label="Height"]').attr('value', '');

This is an ugly hack, but it works; it also enables one to populate this fields with values from a database.

Feature requests:
- If it is possible, add some other attributes to these fields, for example "data-width" and "data-height", the aria attributes feel like they might change (or be translated) some time in the future, and then the above code will be broken.
- Add some similar attributes to the "insert media" dialog. In that dialog, the width and height input fields don't have a unique attribute, which would enable one to write a selector.
  > _**Legacy information imported from TinyMCE bug tracker:**_
  >
  > _[#T7319](http://archive.tinymce.com/develop/bugtracker_view.php?id=7319) posted by [cirix](http://archive.tinymce.com/profile.php?name=cirix)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
