### ISSUE TITLE
Not able to insert or paste two consecutive tables in editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2047]
Description of problem:

Steps to reproduce:
1.I copied two consecutive tables from word
2.tried to paste in edition using copy from word option
3.on update click it does nothing, no text is being copied to the editor

Expected result:
Tables along with text and css needs to be copied successfully on update click in paste form word option.It happens only in case when we try to copy more than one table
Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7322](http://archive.tinymce.com/develop/bugtracker_view.php?id=7322) posted by [swatipandey1](http://archive.tinymce.com/profile.php?name=swatipandey1)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
