### ISSUE TITLE
advlist adjust order of options

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2048]
It would be nice if it could be possible to group list item styles or specify an order.

We would like to have this order:
Default
Lower Alpha
Upper Alpha
Lower Roman
Upper Roman
Lower Greek

Because our langauge is in dutch it is not very nicely grouped.

Thx

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7321](http://archive.tinymce.com/develop/bugtracker_view.php?id=7321) posted by [jeroenc](http://archive.tinymce.com/profile.php?name=jeroenc)_
> 
> _**Tags:** [advlist]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
