### ISSUE TITLE
Pop-ups do not display buttons on smartphones in portrait view

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2049]
Although they show OK in landscape view, can it be solved?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7323](http://archive.tinymce.com/develop/bugtracker_view.php?id=7323) posted by [infograf768](http://archive.tinymce.com/profile.php?name=infograf768)_
> 
> _**Tags:** [firefox msie safari chrome popups]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
