### ISSUE TITLE
Copy and Paste results in error

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2050]
Description of problem:

Steps to reproduce:
1.Copy some text from either external application using either menu or CTRL C
2.Paste using menu or CTRL V

Expected result: Pasted text

Actual result: No text is pasted. Error message on Console: Object doesn't support property or method 'split' plugin.min.js, line 1 character 10646

Attachment shows code snippet. 

My analysis:  The variable "retainStyleProperties" is a Boolean and does not contain the "split" method.
 

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7324](http://archive.tinymce.com/develop/bugtracker_view.php?id=7324) posted by [GLanph](http://archive.tinymce.com/profile.php?name=GLanph)_

> _**Tags:** [msie chrome msie10 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
