### ISSUE TITLE
Tinymce init with id of the textarea not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2051]
Description of problem:

While init the tinymce with id of textarea, It is not working.

Steps to reproduce:
1.place an textarea inside form element.
2.now, init the tinymce with 'exact' mode.

Solution :

Bug resides switch case  handling in readyHandler method which is a defined inside init method.

while checking for textarea with given id inside form elements, have to check e.id === id instead of e.name === id

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7325](http://archive.tinymce.com/develop/bugtracker_view.php?id=7325) posted by [kirubachari](http://archive.tinymce.com/profile.php?name=kirubachari)_
> 
> _**Tags:** [firefox msie safari chrome init]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
