### ISSUE TITLE
TinyMCE with angularjs and reordering

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2052]
Description of problem:

(I am not sure if this is the right place, but couldn't find anything related to this yet.)

I am using angularjs, jquery-ui and tinymce together. 
I have a simple textarea that is shown only when you are clicking on it, otherwise you will only see a div with the same text. Once you render the page for the first time the tinymceInstance is initialized like this: 

/**
- Binds a TinyMCE widget to &ltg;textarea> elements.
  */
  (function () {
  angular.module('ui.tinymce', [])
      .directive('uiTinymce', uiTinymce);
  
  function uiTinymce() {
      var uiTinymceConfig = {
          toolbar: false,
          menubar: false,
          statusbar: false,
          width: '100%',
          height: '100%',
          autoresize: true,
      };
  
  ```
  var generatedIds = 0;
  var directive = {
      require: 'ngModel',
      link: link
  };
  
  return directive;
  
  function link(scope, elm, attrs, ngModel) {
      var expression, options, tinyInstance;
  
      // generate an ID if not present
      if (!attrs.id) {
          attrs.$set('id', 'uiTinymce' + generatedIds++);
      }
      options = {
          // Update model when calling setContent (such as from the source editor popup)
          setup: elementSetup,
          mode: 'exact',
          elements: attrs.id,
          skin: 'licor'
      };
  
      if (attrs.uiTinymce) {
          expression = scope.$eval(attrs.uiTinymce);
      } else {
          expression = {};
      }
  
      angular.extend(options, uiTinymceConfig, expression); //TODO: Try to test me
  
      setTimeout(tinymceInit);
  
      scope.$on('editMode', editModeHandler);
      scope.$on('setContainerSize', setContainerSizeHandler);
      ngModel.$myRender = modelRender;
  
      function elementSetup(ed) {
          //TODO: Test me (from angular.extend())
          ed.on('init', init);
          ed.on('ExecCommand', execCommand); // Update model on button click
          ed.on('KeyUp', keyUp); // Update model on keypress
  
          ed.on('blur', blur);
  
          function init() {
              ngModel.$myRender();
          }
  
          function execCommand() {
              ed.save();
              ngModel.$setViewValue(elm.val());
              if (!scope.$$phase) {
                  scope.$apply();
              }
          }
  
          function keyUp() {
              ed.save();
              ngModel.$setViewValue(elm.val());
              if (!scope.$$phase) {
                  scope.$apply();
              }
          }
  
          function blur() {
              scope.$emit('mceBlur', 'attrs.id: ' + attrs.id);
          }
      }
  
      function tinymceInit() {
          tinymce.init(options);
      }
  
      function editModeHandler(event, data) {
          console.log(elm);
          if (data) {
              ngModel.$myRender();
              tinymce.get(attrs.id).focus();
              var container = $(elm).closest('.drag-container-div');
              $(elm).parents().find('.mce-edit-area').height(container.height());
          }
      }
  
      function setContainerSizeHandler(event, data) {
          $(elm).parents().find('.mce-edit-area').height(data.height);
      }
  
      function modelRender() {
          if (!tinyInstance) {
              tinyInstance = tinymce.get(attrs.id);
          }
          if (tinyInstance) {
              tinyInstance.setContent(ngModel.$viewValue || '');
              tinyInstance.selection.select(tinyInstance.getBody(), true); //places cursor at the end of the current text
              tinyInstance.selection.collapse(false);
          }
      }
  }
  ```
  
  }
  })();
  and after that its listening to the 'editMode' event. Everything works fine from in the beginning. All changes are registered and I haven't had any trouble. 

I am implementing a new feature now that lets the user reorder sections. The textarea is part of a section, and there can be multiple sections (as an array of objects) on a page. 

Now the problem:
When I reorder the sections something strange happens. When the index of an item in the array get smaller I lose the ability to edit the text with tinymce, e.g. item[0] is moved to item[1], then item[1] is moved up to item[0], the new item[0] cannot be edited anymore, the old item[0](now item[1]) is still working as before. You can repeat this in any iteration, any item that is moved up loses its editing ability (also true for moving multiple items).

The original array looks like this:
Sections[{textareatext0, otherstuff0...}, {textareatext1, otherstuff1...}, ...]

The reordered array looks like this:
Sections[{textareatext1, otherstuff1...}, {textareatext0, otherstuff0...}, ...]

Something that stood out at me was this: The generated html is the only place that lets me know when something is wrong. In the original (working), the generated iframe has a body with the correct text. The reordered (wrong) version has a completely empty body tag. Other than that the rest of the generated iframes (and all other generated tags) are exactly identical. 

I know that a refresh can fix this, since everything is re-rendered. So I am wondering if there is a way I could manually re-render the bindings of tinymce? Or if there is any other way to rebind the items? A full refresh would be very expensive and would not be a realistic solution for me.

I have been stuck on this for the last 3 days, and I finally found that the issue is somewhere with using tinymce, by removing different parts of the code. 

Any help would be greatly appreciated! If you want to see more code let me know. Its part of a bigger project, and isolating this part into a sample app is not trivial, so I wanted to try this route first.

Thanks!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7326](http://archive.tinymce.com/develop/bugtracker_view.php?id=7326) posted by [bballjo](http://archive.tinymce.com/profile.php?name=bballjo)_
> 
> _**Tags:** [chrome chrome angular angularjs sortable ordering reorder jqueryui]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by shopblocks** [comment]
I have just come across the same issue. Has anybody got an update / a way to solve this?

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
