### ISSUE TITLE
Lists not working in style_formats

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2053]
Description of problem:

Go to http://fiddle.tinymce.com/x8eaab and show in "Formats" popup. All "Lists" elements are disabled.

Expected result:

Enabled lists elements.

----

Is this a bug or something wrong? I want hide the lists buttons and use the popup instead. 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7327](http://archive.tinymce.com/develop/bugtracker_view.php?id=7327) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/x8eaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
