### ISSUE TITLE
Toggle Toolbars / kitchen sink (with solution)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2055]
I found hidden in forum a post:
http://www.tinymce.com/forum/viewtopic.php?pid=110878#p110878

[quote=spocke]I guess you mean a kitchen sink? A button that shows more tools when you click it.

I toyed around with this and had to do some minor modifications to tinymce to get it working but you can now basically do a kitchen sink using the BeforeRenderUI event.

[code]
// Hide all the toolbars except the first one
editor.on('BeforeRenderUI', function(e) {
    editor.theme.panel.find('toolbar').slice(1).hide();
});

// Add a sink button that toggles toolbar 1+ on/off
editor.addButton('sink', {
    text: 'Kitchen sink',
    onclick: function() {
        if (!this.active()) {
            this.active(true);
            editor.theme.panel.find('toolbar').slice(1).show();
        } else {
            this.active(false);
            editor.theme.panel.find('toolbar').slice(1).hide();
        }
    }
});
[/code]

Note you need the current GitHub version. This will be released in TinyMCE 4.0.11. The BeforeRenderUI enables you to do all sorts of things to the the UI before it gets rendered. The theme.panel is the main UI panel for the editor.[/quote]

Impressive! Why you hide this genial piece of code here in a forum post? This is so cool and should be a default plugin. Only add a icon for it. ;)

Much thanks for it! This resolve so much problems for me. _praise_

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7329](http://archive.tinymce.com/develop/bugtracker_view.php?id=7329) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
