### ISSUE TITLE
center tag not recognized like "center"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2056]
Sorry for my english.

Description of problem:

Steps to reproduce:
1. Just have center tag in editor.
2. You can't anymore remove it and use left/right align anywhere...

Expected result:
Center should be recognized like "&ltg;div style='text-align:center'>" and don't break editing of texts.

Actual result:
Broke text editing if this tag used inside html.

This happens if you switch to tinymce in some CMS what used center tag for centering text, and then you can't anymore correct edit this news/page without manually edit html code...

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7330](http://archive.tinymce.com/develop/bugtracker_view.php?id=7330) posted by [AlexALX](http://archive.tinymce.com/profile.php?name=AlexALX)_
> 
> _**Tags:** [firefox msie safari chrome center]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/G8eaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
