### ISSUE TITLE
font family style is removed and name doesn't appear in font menu when you backspace to a blank line.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2058]
Tinymce: Font style is removed and name doesn't appear in font menu when you backspace to a blank line. The font does not appear even when you change the position of the cursor. 

* STEPS TO REPRODUCE
1. Go to TinyMCE example UR above
2. Enter multiple lines of text with different font families
3. Click the Return key at the beginning of any line multiple times.
4. Click the Delete/Backspace key. 
5. Note that the selected Font no longer appears in the Font Menu, and the font formatting is gone.

* RESULTS 
Expected: Current font name would appear in the font menu,  the font family is retained.
Actual: the font name does not appear in the Font Picker even when you move the cursor.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7332](http://archive.tinymce.com/develop/bugtracker_view.php?id=7332) posted by [drew](http://archive.tinymce.com/profile.php?name=drew)_

> _**Tags:** [safari chrome safari5 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
