### ISSUE TITLE
Word count limit

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2059]
Feature request:

When will you decide to provide a word count limit ??

I agree that character counting is a problem but word counting no.

So we all have many reasons to want to limit the number of words input. 

Regards,
Alain

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7333](http://archive.tinymce.com/develop/bugtracker_view.php?id=7333) posted by [caBBAlainB](http://archive.tinymce.com/profile.php?name=caBBAlainB)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
