### ISSUE TITLE
when merge empty cell we have merged br

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2060]
Description of problem:
Empty cells are filled with br tags. When we merge 3 or more cells we get merged br.

Steps to reproduce:
1. Add table with 3x3
2. Add some text to first cell
3. Select 3 cells in row
4. Merge cells

Expected result:
We should get one cell with text (without br tags)

Actual result:
We get text and br tags

Solution:

add to /plugins/table/plugin.js
// remove empty cell with br inside
if (node.nodeName == 'DIV' && node.innerHTML == '&ltg;br>' ||
    node.nodeName == 'BR' && dom.getAttrib(node, 'data-mce-bogus') && count++ &ltg; children.length - 1) {
  startCell.removeChild(node);
}

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7334](http://archive.tinymce.com/develop/bugtracker_view.php?id=7334) posted by [macem](http://archive.tinymce.com/profile.php?name=macem)_

> _**Tags:** [firefox msie safari chrome merge cell br]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
