### ISSUE TITLE
noneditable plugin: backspace deletes wrong content after mceNonEditable insertion

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2061]
Hello,

Afraithe asked me to report my problem in the tracker that I have posted in the forum yesterday:
http://www.tinymce.com/forum/viewtopic.php?pid=115468

Description of problem:

There are two problems:
a) After inserting a non editable content and typing some additional text, the first typed character does not appear.

b) The main problem: When trying to delete the last character with the backspace key, the wrong content is deleted.

In my case tested with tinymce 4.1.5 with Firefox (Linux).

Steps to reproduce:
(see the attached example test page; It is using the tinymce from the URI http://tinymce.cachefly.net/4.1/tinymce.min.js - currently 4.1.7)

1. Click the button "Insert Tag". This inserts a noneditable tag "[DATE-TAG]".
2. Now type something, e.g. "abc".
3. Try to delete the "c" by pressing backspace once

Expected result:
a) Typing "abc" should enter these three characters "abc" into the editor.
b) Pressing the backspace key should delete the "c".

Actual result:
a) When typing "abc" only "bc" appears in the editor.
b) When pressing backspace the "c" is not deleted. Instead the "[DATE-TAG]" is removed.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7335](http://archive.tinymce.com/develop/bugtracker_view.php?id=7335) posted by [g111](http://archive.tinymce.com/profile.php?name=g111)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
