### ISSUE TITLE
paste_webkit_styles option seems to be broken

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2062]
Description of problem: This appears to be related to http://www.tinymce.com/develop/bugtracker_view.php?id=5575. I believe recent versions of Chrome have changed behavior and that the workarounds in removeWebKitStyles (line 1439 in paste plugin) are no longer functioning as designed.

When specifying styles to keep, none are kept. The "all" option works, but the logic there is wholly different.

Steps to reproduce:
1. Initialize editor with paste_webkit_styles: "font-family" set
2. Enter some text into editor
3. Change font-family of text (this could be done with any style that appears in the style attribute)
4. Select all text, copy, paste

Expected result: Text will be pasted with specified styles intact (in this case, font-family)

Actual result: Text is pasted without any styles

Addendum: Simply removing the check in line 1475:

if(currentValue != inptuValue) { }

and forcing the action, outputStyles[webKitStyles[i]] = inputValue, to always execute, seems to fix the issue. But I do not want to maintain hacks on tinyMCE core plugins.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7336](http://archive.tinymce.com/develop/bugtracker_view.php?id=7336) posted by [yaviner](http://archive.tinymce.com/profile.php?name=yaviner)_

> _**Tags:** [chrome chrome paste paste_webkit_styles]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
