### ISSUE TITLE
increase indent button gets disable while bulletining is applyed 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2063]
Description of problem:

Steps to reproduce:
1.go to the http://www.tinymce.com/tryit/classic.php
2.type one line 
3.press enter.
4.select any bullet.

Expected result: increase indent button should not be get disabled 

Actual result: increase indent button is gets disable.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7337](http://archive.tinymce.com/develop/bugtracker_view.php?id=7337) posted by [snehal1112](http://archive.tinymce.com/profile.php?name=snehal1112)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by ArunChitumalla** [comment]
Any update on this bug?

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by abhinav-nehra** [comment]
I am still getting this error

**Comment by dererer** [comment]
> I am still getting this error

Hello, please use one of them in plugin list ('advlist' or 'lists').

It`s helpull for me.

Svyatoslav
