### ISSUE TITLE
more space between line and bullet.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2064]
Description of problem:

Steps to reproduce:
1. Write one line
2. Press increase indent button five to 7 times
3. Select bullet and write one word
4. Press enter and type one more word

Expected result:Space between word and bullet is not more than required

Actual result:Space between word and bullet is more than required

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7338](http://archive.tinymce.com/develop/bugtracker_view.php?id=7338) posted by [snehal1112](http://archive.tinymce.com/profile.php?name=snehal1112)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
