### ISSUE TITLE
IE11: Changing a font size is not getting applied to the selected word

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2066]
Description of problem:
Changing a font size of selected word is not getting applied to it

Steps to reproduce:
1. Load TinyMCE example URL in IE11
2. Select a font name(eg: Impact)
3. Type some text in the editor
4. Hit space key
5. Select some other font size(eg: 18)
6. Type some text and hit space key
7. Select some other font name(eg:Helvetica) and type some text
8. Click on the 2nd word, font name and size will show the proper values
9. Double click on 2nd word and select a new font size(eg: 16)

Expected result:
Font size should change to the newly selected size

Actual result:
New font size is not getting applied to the selected word

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7340](http://archive.tinymce.com/develop/bugtracker_view.php?id=7340) posted by [drew](http://archive.tinymce.com/profile.php?name=drew)_

> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
