### ISSUE TITLE
Layout error at Movable.js:180

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2068]
Movable.js has a bug at lines 180-186.
The current version:

if (self.settings.constrainToViewport) {
    var viewPortRect = DomUtils.getViewPort(window);
    var layoutRect = self.layoutRect();

```
x = contrain(x, viewPortRect.w + viewPortRect.x, layoutRect.w);
y = contrain(y, viewPortRect.h + viewPortRect.y, layoutRect.h);
```

}

This should be:
if (self.settings.constrainToViewport) {
    var viewPortRect = DomUtils.getViewPort(window);
    var layoutRect = self.layoutRect();

```
x = contrain(x, viewPortRect.w, layoutRect.w);
y = contrain(y, viewPortRect.h, layoutRect.h);
```

}

This is because the contraint() function that is called, already takes the size of the rectangle into account (that is what its third parameter is for).

This bug causes big menus to appear offscreen.

The first image shows the bug: the text has 10 anchors (labeled 0-9), and the anchor combobox opened in the link insert dialog. The second image shows the fixed version.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7342](http://archive.tinymce.com/develop/bugtracker_view.php?id=7342) posted by [cirix](http://archive.tinymce.com/profile.php?name=cirix)_
> 
> _**Tags:** [firefox msie safari chrome movablejs]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
