### ISSUE TITLE
TinyMCE crashes on invalid HTML

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2069]
Description of problem:
TinyMCE crashes if there are two different style tags on an element.

Steps to reproduce:
1. Go to TinyMCE home page.
2. See the sample editor on the top.
3. Enter source code view.
4. Change the first h3 to: &ltg;h3 style="background: red;" class="xyz" style="">TinyMCE 4.1.7, edit right here if you want&ltg;/h3>
5. Click yes.

Expected result:
Handle situation :D

Actual result:
TypeError: e is undefined at tinymce.min.js:3, and crash. The dialog cannot be closed.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7343](http://archive.tinymce.com/develop/bugtracker_view.php?id=7343) posted by [cirix](http://archive.tinymce.com/profile.php?name=cirix)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by raquelhortab** [comment]
I am trying to use tinymce to preview an html text as it is writen, but it crashes when you start typing a tag "<" because it is incorrect html. The whole browser tab crashes and I need to force-close it.

**Comment by sai-kiran-dannana** [comment]
Hey @metricjs 
I'm using version v4.2.0. You should be able to reproduce above issue with below value.

<div style="display: flex; align-items: flex-end;">
 <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEUAAAAxCAYAAACMPmT
