### ISSUE TITLE
nonbreaking plugin documentation for nonbreaking_force_tab setting

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2071]
this is from plugins/nonbreaking.js:

if (setting) {
    var spaces = +setting > 1 ? +setting : 3;  // defaults to 3 spaces if setting is true (or 1)

please document this behavior at nonbreaking_force_tab.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7345](http://archive.tinymce.com/develop/bugtracker_view.php?id=7345) posted by [cirix](http://archive.tinymce.com/profile.php?name=cirix)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
