### ISSUE TITLE
img tag in editor: sizes attribute gets lost on save

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2072]
When using the "Source Code" tool in the TinyMCE-editor, I manually add a sizes attribute to an img tag.

After save, the added sizes tag gets cut out.

The wanted result is a responsive HTML5 img tag with a srcset attribute as well as a sizes attribute.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7346](http://archive.tinymce.com/develop/bugtracker_view.php?id=7346) posted by [Lemmiwinx](http://archive.tinymce.com/profile.php?name=Lemmiwinx)_

> _**Tags:** [firefox msie safari chrome editor srcset sizes]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
