### ISSUE TITLE
mce-content-body is not used in template plugin dialog

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2073]
plugins/template/plugin.js line 70 should be:
    '&ltg;body class="mce-content-body">' +
instead of
    '&ltg;body>' +

because the user css file (via configuration options, content_css) might contain extra styling for mce-content-body. without the class, these extra styles are not applied in the template preview.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7347](http://archive.tinymce.com/develop/bugtracker_view.php?id=7347) posted by [cirix](http://archive.tinymce.com/profile.php?name=cirix)_
> 
> _**Tags:** [firefox msie safari chrome template]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
