### ISSUE TITLE
Inline toolbar does not close after click on empty toolbar section

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2074]
Description of problem:

Inline toolbar does not close when you click on non editable elements (elements that do not have TinyMCE attached to them) after clicking on an empty section of the toolbar.

Steps to reproduce:
1. Go to: http://www.tinymce.com/tryit/inline.php
2. Click on the paragraph that starts with "This is an editable div element element"
3. Click on the empty section of the inline toolbar just to the right of the Tools menu button. (The section that does not have any buttons)
4. Click somewhere else on the page that does not have an inline editor attached to it.

Expected result:

The inline toolbar should close.

Actual result:

The toolbar remains open.

To close the inline editor you must click on: 
- a button in the editor then elsewhere on the page 
- inside the editable area then elsewhere on the page 
- a different editable area (unless it is covered by the current toolbar)
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7348](http://archive.tinymce.com/develop/bugtracker_view.php?id=7348) posted by [brainybiz](http://archive.tinymce.com/profile.php?name=brainybiz)_

> _**Tags:** [firefox safari chrome firefox safari5 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/inline.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
