### ISSUE TITLE
mceFocus works incorrectly in IE 11

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2075]
Description of problem:
the following call works incorrectly in Internet Explorer 11:
$wnd.tinyMCE.execCommand('mceFocus', false, id);

where:
id - identifier of the TinyMCE object.

Steps to reproduce:
1. focus on another element on the page.
2. try to focus programmatically by calling mceFocus.
Environment: IE11, TinyMCE 3.
(the same reproduces on TinyMCE 4,  but the call is a bit different).
Not reproducible on Chrome/Firefox.

Expected result:
rich text area receives focus and new text is written here,
specifically: focus goes to this html element: 
&ltg;iframe title="Rich Text Area...>
     ...
     &ltg;html...>
        &ltg;body class="mceContentBody " id="tinymce" ...>
         ...
        &ltg;/body>
     &ltg;/html>
&ltg;/iframe>
and content is written inside body of html node internal to this iframe.

Actual result:
the focus goes to global &ltg;html> -> &ltg;body> element, outside the tinyMCE's iframe,
new text is written inside the global body element, just before the closing tag &ltg;/body>.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7349](http://archive.tinymce.com/develop/bugtracker_view.php?id=7349) posted by [Ivan Golubev](http://archive.tinymce.com/profile.php?name=Ivan Golubev)_
> 
> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by mihaifaget** [comment]
this is still not working, but you seem anxious to close any issue regarding IE problems. Throwing 3 lines of code with no explanation where to put them or what focus() are you talking about is not a real fix. Neither mentioning 2 urls that don't work.
