### ISSUE TITLE
filemanager same file name upload

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2076]
Description of problem:

Steps to reproduce:
1. upload a image ex. test.jpg from editor.
2. then upload another image the same filename test.png
3.
4.
5.

Expected result:
it should display both with different image.

Actual result:
same  image display  
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7350](http://archive.tinymce.com/develop/bugtracker_view.php?id=7350) posted by [melmagaling](http://archive.tinymce.com/profile.php?name=melmagaling)_

> _**Tags:** [firefox msie safari chrome filemanaer filename]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
