### ISSUE TITLE
Autoresize plugin causes page to jump to top when selecting text with mouse in Safari

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2077]
I have a tinymce editor on a page with a scrollbar. That tinymce editor is in the middle of the page. When I select the text inside the editor, there is a page jump to the top of the page. That only happens when the autoresize plugin is in use.

Steps to reproduce:
1. Use autoresize plugin and initialize full editor on a page with a scrollbar (can't use fiddle)
2. Tinymce editor should be in the middle of the page
3. Scroll to tinymce editor
4. Select text with mouse

Expected result:
Text is selected with mouse.

Actual result:
Page jump to top of the page.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7351](http://archive.tinymce.com/develop/bugtracker_view.php?id=7351) posted by [michaelhast](http://archive.tinymce.com/profile.php?name=michaelhast)_
> 
> _**Tags:** [safari safari8 autoresize text selection mouse page jump]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by AndrewLang** [comment]
Is there a solution?

I meet the same problem.

**Comment by jayarjo** [comment]
@AndrewLang do you also experience it in Safari?

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
