### ISSUE TITLE
Source view removing nested HTML

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2078]
Description of problem: Source view removing nested HTML

Steps to reproduce:
1. View source and enter:
&ltg;div class="foo">&ltg;a href="">&ltg;i class="fa fa-play">&ltg;/i>&ltg;/a>&ltg;/div>

2. Close and reopen source it converts it to:
&ltg;div class="foo">&nbsp;&ltg;/div>

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7352](http://archive.tinymce.com/develop/bugtracker_view.php?id=7352) posted by [web2works](http://archive.tinymce.com/profile.php?name=web2works)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
