### ISSUE TITLE
styleselect toolbar button has wrong css class assigned

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2079]
Description of problem:
I was trying to style the editor's toolbar buttons in favor of smaller icons and paddings, so i came up with some basic reset css to do so.

[code]
body .mce-container \* {padding: 0px; margin:0px; font-size:11px; line-height:12px; border-radius: 0px !important;}
body .mce-container .mce-listbox {padding:2px;}
[/code]

As a result, almost all icons were properly resized, with the only (?) exception of the styleselect button which was too small in height.

When looking into the tinymce code and into the generated toolbar code, i found out that the styleselect button is of type 'menubutton' whereas the other dropdowns are assigned a 'listbox' type, which later translates to a 'mce-menubtn' css class instead of a 'mce-menubtn mce-listbox' css class combo.

Additionally the styleselect button should be with a fixedWidth property value of true, so one can see the caret, too :-)

Steps to reproduce:
1. add styleselect to toolbar
2. try to change editor toolbar css for smaller paddings & font sizes with above css

Expected result:
all toolbar icons at the same height

Actual result:
all buttons but the styleselect button are styled properly.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7353](http://archive.tinymce.com/develop/bugtracker_view.php?id=7353) posted by [flashworks](http://archive.tinymce.com/profile.php?name=flashworks)_
> 
> _**Tags:** [firefox msie safari chrome styleselect tinymce4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by nori-h** [comment]
We have taken a look and this issue appears to be similar with #2786

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
