### ISSUE TITLE
Link plugin width problem

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2080]
When you open popup for link the target label is covered. We are using bootstrap.
See attachment.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7356](http://archive.tinymce.com/develop/bugtracker_view.php?id=7356) posted by [Majstr](http://archive.tinymce.com/profile.php?name=Majstr)_

> _**Tags:** [firefox msie chrome firefox msie11 chrome link plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
