### ISSUE TITLE
paste_data_images removes existing images

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2081]
Description of problem:
Hello.

I enabled paste_data_images in my configuration, but after realizing that every image that was pasted was converted into data:uri image, instead of using the image link, I disabled the option. 

Now, all the existing images are being filtered out by tinyMCE.

There are two problems here:
1) Why enabling paste_data_images converts every image to data uri? If I am copying text from a web page that includes images, it should just paste the &ltg;img> tag src attribute as it is in the clipboard...

2) Why does the option messes up existing images?

Steps to reproduce:
1. Set paste_data_images to true. 
2. Select some content of a website that includes images and paste them in tinyMCE.
3. The images src attribute is converted to data:uri.
4. Save the content with Editor.getContent().
5. Set paste_data_images to false.
6. Reload the page and use Editor.setContent() with the previously saved content.

Expected result:
- Images should not be converted to data:uri.
- Content should not change after changing paste_data_images.

Actual result:
- Images are converted to data:uri even though the clipboard had image locations.
- The data:uri images disappear.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7358](http://archive.tinymce.com/develop/bugtracker_view.php?id=7358) posted by [yaron](http://archive.tinymce.com/profile.php?name=yaron)_

> _**Tags:** [firefox msie safari chrome paste image data_uri paste_data_images]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
