### ISSUE TITLE
Add a setting for elements that are valid to split on newline

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2082]
The force_p_newlines setting already exists but in some cases it does not actually force &ltg;p> elements on newlines:

&ltg;div class="fancy styles">Hello World&ltg;/div>

If a line return is added between Hello and World, a second copy of &ltg;div class="fancy styles"> will be created:

&ltg;div class="fancy styles">Hello &ltg;/div>&ltg;div class="fancy styles">World&ltg;/div>

Instead, this result on newline is more desirable:

&ltg;div class="fancy styles">&ltg;p>Hello &ltg;/p>&ltg;p>World&ltg;/p>&ltg;/div>

To enact this functionality, inside tinymce/EnterKey the canSplitBlock function can use a new invalid_split_elements setting:

function canSplitBlock(node) {
var invalid_split_elements = /^(TD|TH|CAPTION|FORM|DIV)$/;
return node &&
dom.isBlock(node) &&
!invalid_split_elements.test(node.nodeName) &&
!/^(fixed|absolute)/i.test(node.style.position) &&
dom.getContentEditable(node) !== "true";
}

Ideally, the invalid_split_elements would be provided by a setting instead of inline. To avoid breaking existing code it would default to 'TD|TH|CAPTION|FORM'.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7355](http://archive.tinymce.com/develop/bugtracker_view.php?id=7355) posted by [JoeCoder](http://archive.tinymce.com/profile.php?name=JoeCoder)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
