### ISSUE TITLE
Inline mode, toolbar position problem

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2084]
Description of problem: 
When using tinymce on inline mode, toolbar will appear on last known position, if we scroll down the page, making the toolbar close to the top of the page and select another field and then go back up and select previous selected field toolbar will appear closed to the top of the page, far from the element selected.

Steps to reproduce:
1. Open the URL attached to this report (it's the inline example from tinymce);
2. Focus mouse on title "Editable header" inside the example, this way a tiny toolbar will appear on top of it;
3. Now scroll down the page until you hit the bottom (until the toolbar is glued to the top of the page)
4. Hit the text in front of you (another toolbar will appear);
5. Now scroll up and hit the Title "Editable header" again (the toolbar appears glued to the top of the page instead of appearing along with the element);

Expected result:
Toolbar should always appear close to the selected element.

Actual result:
Toolbar appears glued to the top of the page.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7359](http://archive.tinymce.com/develop/bugtracker_view.php?id=7359) posted by [mcgoncalves](http://archive.tinymce.com/profile.php?name=mcgoncalves)_
> 
> _**Tags:** [firefox msie chrome firefox msie11 chrome chromecanary inline toolbar]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/inline.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
