### ISSUE TITLE
Word Count error with individual characters' formatting

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2085]
Description of problem:

Steps to reproduce:
1. Go to a large text box
2. Type in one word (word count recognises 1 word and count it as such)
3. select the second letter of the word and make it bold, select the third letter of the word, make it italic, select the fourth letter and underline it

Expected result: The word count should still be 1

Actual result: The word count is 5 words despite there only being 1 single word. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7361](http://archive.tinymce.com/develop/bugtracker_view.php?id=7361) posted by [tinymouse](http://archive.tinymce.com/profile.php?name=tinymouse)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
