### ISSUE TITLE
Not going to set content to TinyMCE in firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2086]
Description of problem:Not going to set content to TinyMCE in firefox

Steps to reproduce:
1. tinyMCE.get(document.getElementById("editor").id).setContent('hi');
2.  tinyMCE.activeEditor.setContent('hi');
3.
4.
5.

Expected result:must assign 'hi' to editor

Actual result:
Not showing anything
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7362](http://archive.tinymce.com/develop/bugtracker_view.php?id=7362) posted by [shailendrashinde](http://archive.tinymce.com/profile.php?name=shailendrashinde)_

> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
