### ISSUE TITLE
Inline attachment when placing from clipboard

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2087]
Is there an option to enable automatic image upload when pasting them from clipboard?
Currently we can include images as base64, but this way images are "included" in content.
I would like to have functionality like in GitHub:
When dropping image or placing from clipboard it is automatically uploaded and img tag with scr to that image is placed.

I found library called InlineAttachment (https://github.com/Rovak/InlineAttachment) maybe this functionaly can be build in tinyMCE?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7363](http://archive.tinymce.com/develop/bugtracker_view.php?id=7363) posted by [Misiu](http://archive.tinymce.com/profile.php?name=Misiu)_
> 
> _**Tags:** [firefox msie safari chrome feature request]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
