### ISSUE TITLE
TinyMCE editor changing my content formatting and removing data-{xxx} attributes

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2088]
TinyMCE editor changing my content formatting and removing data-{xxx} attributes

How to solve it.

Expected result:
It should be same whatever I entered in source code.

Actual result:
It is removing custom attributes, or empty attributes.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7365](http://archive.tinymce.com/develop/bugtracker_view.php?id=7365) posted by [amtprajapati](http://archive.tinymce.com/profile.php?name=amtprajapati)_
> 
> _**Tags:** [firefox msie safari chrome valid_elements formatting]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
