### ISSUE TITLE
Image plugin inserting incorrect url path when selecting local file

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2089]
Description of problem:
image plugin moxie manager is returning a full path with domain host and current directory instead of an absolute path.  It's also returning double forward slashes.

Steps to reproduce:
1.set relative_urls to false in Tinymce init
2.enable image plugin and moxiemanager external plugin
3.click "Insert/edit image" button in Tinymce menu
4.click the browse files button in the image dialog
5.select image from moxie manager

Expected result:
I expected the returned source path to be an absolute path, for example "/images/test.jpg"

Actual result:
actual returned path from moxie manager looks like "http://www.domain.com/currentdir//images/test.jpg"

tinymce version is 4.1.7 (targeting the CDN script //tinymce.cachefly.net/4.1/tinymce.min.js)

Not entirely sure this isn't a bug in moxie manager, but it's worth pointing out that when I target Tinymce 4.0 (4.0.28) instead of 4.1, it works perfectly.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7366](http://archive.tinymce.com/develop/bugtracker_view.php?id=7366) posted by [TomWebSolutions](http://archive.tinymce.com/profile.php?name=TomWebSolutions)_
> 
> _**Tags:** [firefox msie safari chrome moxie manager]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
