### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2090]
I'm new to tinymce and relatively painlessly I have got a first sample working on an asp net page. I want to do custom configuration of the menu and have not yet found how to (easily) find which menu items are generated by which plugins. For example I'd like users to be able to insert pictures but not videos. It would be great to have the menu item names listed with the plugin and a brief description of what each plugin does

Thanks, its a great bit of coding.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7367](http://archive.tinymce.com/develop/bugtracker_view.php?id=7367) posted by [Exglider pilot](http://archive.tinymce.com/profile.php?name=Exglider pilot)_
> 
> _**Tags:** [documentation menu configeration]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/full.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
