### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2091]
Go to http://www.tinymce.com/tryit/basic.php and click on media button. Now simple use scrolling with mouse-wheel. The webpage in background is scrolling. This should not happen. The same with "source code"-dialog.

Something like: http://api.jquery.com/event.preventdefault/

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7369](http://archive.tinymce.com/develop/bugtracker_view.php?id=7369) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
