### ISSUE TITLE
media: missing fullscreen button in youtube videos

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2092]
Tinymce create a url with iframe for youtube videos. Working fine, but all iframe missing this iframe-attribute:

allowfullscreen="1"

without this parameter the "Fullscreen" button is missing in youtube videos.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7372](http://archive.tinymce.com/develop/bugtracker_view.php?id=7372) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** [media]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
