### ISSUE TITLE
All formats disabled when disabling one at end of node

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2093]
Description of problem:
All applied formats are disabled, when disabling one by clicking its button, when cursor is at end of content.

Steps to reproduce:
1. Open an editor with custom formats such as http://fiddle.tinymce.com/8Beaab or http://www.tinymce.com/tryit/custom_formats.php
2. Type some text (ex. "Hello world")
3. Select all
4. Apply Bold formatting (either with the button or keyboard shortcut)
5. Apply Italic formatting (either with the button or keyboard shortcut)
6. Move cursor to end of content (either with arrow keys or mouse)
7. See that Bold and Italic buttons are active and enabled.
8. Disable Italic formatting (either with the button or keyboard shortcut)
9. See that Bold has also been disabled.

Expected result: Only the format which was toggled should be disabled. The other(s) should remain enabled so that continued typing with those formats is possible without reapplying them.

Actual result: All applied formats are disabled, so that continued typing has no formatting applied. Formats must be reapplied for continued typing.

Note: This behavior exists in both TinyMCE 3.x and 4.x

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7373](http://archive.tinymce.com/develop/bugtracker_view.php?id=7373) posted by [gfullam](http://archive.tinymce.com/profile.php?name=gfullam)_
> 
> _**Tags:** [firefox msie safari chrome formatting custom formats]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/8Beaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
