### ISSUE TITLE
Tinymce error in IE8 - 'p[�][�]' is null or not an object

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2094]
Description of problem:
Getting below error in IE8 when trying to move away from page.
JS Error Message: 'p[...][...]' is null or not an object

Steps to reproduce:
1. Open IE 8
2. Load Tinymce
3. Do nothing, move away from the page
4. Before page gets redirected, a Javascript error is thrown
5.

Expected result:
There should not be any javascript error while moving away from page containing Tinymce

Actual result:
Below JS error is thrown.

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E)
Timestamp: Thu, 29 Jan 2015 15:15:46 UTC

Message: 'p[...][...]' is null or not an object
Line: 1
Char: 60310
Code: 0
URI: http://xyz.com/cassette.axd/asset/Scripts/Utilities/tiny_mce/tiny_mce.js?b902a944f3d7278d9794b96aa9402e25f0c12269

Message: 'p[...][...]' is null or not an object
Line: 1
Char: 60310
Code: 0
URI: http://xyz.com/cassette.axd/asset/Scripts/Utilities/tiny_mce/tiny_mce.js?b902a944f3d7278d9794b96aa9402e25f0c12269

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7374](http://archive.tinymce.com/develop/bugtracker_view.php?id=7374) posted by [pavannpt](http://archive.tinymce.com/profile.php?name=pavannpt)_

> _**Tags:** [msie msie8 tinymce]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
