### ISSUE TITLE
PHP Spellchecker 4.0 - Not Working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2095]
The first issue is that the rpc points to tinymce/plugins/spellchecker/ by default however the file is called spellchecker.php (not index.php) and as such you get an error 404. 

This was fixed by adding the following to the init

spellchecker_rpc_url: 'https://www.example.com/tinymce/plugins/spellchecker/spellchecker.php',

The second issue with the spell checker plugin is that in spellchecker.php lower case names are used for example:

```
// PSpell options
"pspell.mode" => "fast",
"pspell.spelling" => "",
"pspell.jargon" => "",
"pspell.encoding" => ""
```

However in the includes these same class names have uppercase extensions for example:

```
    switch ($config['PSpell.mode']) {
```

This was causing an error saying that the response was not json and was because the response started with an PHP error indicating that the PSpell functions did not exist.

After having navigated through the following files EnchantEngine, Engine, PSpellEngine and Spellchecker and fixed the case to lowercase I managed to get off the initial errors of not valid json.

As it stands now if there are no miss spellings I get a box telling me there are no miss spellings.

If there are spelling mistakes then I get a loading gif and then the gif disappears and no windows are spawned. (tinymce/skins/lightgray/img/loader.gif

I get the same issue with

TinyMCE 4.1.7 jQuery package + PHP Spellchecker 4.0

TinyMCE 4.1.7 + PHP Spellchecker 4.0

The RPC now works as expected (example below) it seems that the issue is with tinymce not doing anything with the response.

{
    "words": {
        "0": "OpenOffice",
        "1": "isn",
        "2": "shouldn",
        "3": "spelt",
        "4": "recognise",
        "5": "isn",
        "6": "wouldn",
        "7": "hadn",
        "8": "hasn",
        "9": "doesn",
        "10": "Multitool"
    }
}

Above is what the RPC is returning im using pspell in that example i have used the example php script from http://www.tinymce.com/wiki.php/Plugin3x:spellchecker and verified that way that the pspell is working and i can see from the json that it is working.

Ive also tried adding my own callback to the init 

```
spellchecker_callback: function(method, text, success, failure) {

    alert(method);
    alert(text);
    alert(success);
    alert(failure);

}
```

the outputs are

method = spellcheck

text = my text block

success = function y(a){
"use strict";
var c;return a.words?(D=!!a.dictionary,c=a.words):c=a,b.setProgressState(!1),l(c)?(b.windowManager.alert("No misspellings found"),void(B=!1)):(A=c,j().find(n()).filter(function(a){return!!c[a.text]}).wrap(function(a){return b.dom.create("span",{"class":"mce-spellchecker-word","data-mce-bogus":1,"data-mce-word":a.text})}),B=!0,void b.fire("SpellcheckStart"))}

failure = function a(a){
"use strict";
b.windowManager.alert(a),b.setProgressState(!1),u()}

I dont know wnough javascript to debug why no modal pops up and offers sugestions.

Whats the next step ?

Anasule

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7375](http://archive.tinymce.com/develop/bugtracker_view.php?id=7375) posted by [Anasule](http://archive.tinymce.com/profile.php?name=Anasule)_
> 
> _**Tags:** [firefox msie safari chrome spell checker spellchecker]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
