### ISSUE TITLE
Paste Word paragraph with nested comments

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2096]
Description of problem:
I have tested only with IE11 and latest Firefox.

Steps to reproduce:
1. Create a word file (or use attached) with nested/overlapping comments (from the review ribbon) within one paragraph.
2. Select the paragraph and copy it.
3. Paste the text to TinyMCE

Expected result:
The whole text of the paragraph should be copied to TinyMCE editor.

Actual result:
Only a fraction of the text is copied. Even the 'paste_preprocess' event of the paste plugin shows only the fraction of text and not the whole paragraph as html.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7376](http://archive.tinymce.com/develop/bugtracker_view.php?id=7376) posted by [burnaster](http://archive.tinymce.com/profile.php?name=burnaster)_

> _**Tags:** [paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/KBeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
