### ISSUE TITLE
IE 11 - Resize plugin - autoresize_min_height doesn't work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2097]
It seems the problem comes from body.offsetHeight value on IE11. There's always a difference of 100px which results with a 50px blank area at the bottom of the iframe.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7377](http://archive.tinymce.com/develop/bugtracker_view.php?id=7377) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_
> 
> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by drormat** [comment]
Is there any chance to expect for a fix to this bug anytime soon?

**Comment by blackcathikari** [comment]
I believe this is related to #2945. Could you take a look please and let me know if you disagree? Thanks,
Millie @ TinyMCE

**Comment by mesche** [comment]
Try it with the setting  "autoresize_bottom_margin: 1"

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
