### ISSUE TITLE
Ending <br /> is eaten in list?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2098]
Here's a simple code to copy inside the editor using the source code window:
&ltg;ol>
&ltg;li>a&ltg;br />
&ltg;br />
&ltg;/li>
&ltg;li>b&ltg;br />
&ltg;br />
&ltg;br />
a&ltg;/li>
&ltg;/ol>

Once paste, the display is correct. But if you open again the source code windows, one &ltg;br /> will be missing.
&ltg;ol>
&ltg;li>a&ltg;br /> &ltg;/li>
&ltg;li>b&ltg;br /> &ltg;br /> &ltg;br /> a&ltg;/li>
&ltg;/ol>

A temporary fix is to directly put the missing br after the first one (without any whitespace):
&ltg;ul>
&ltg;li>a&ltg;br />&ltg;br />&ltg;/li>
&ltg;li>b&ltg;br /> &ltg;br /> &ltg;br /> a&ltg;/li>
&ltg;/ul>

Could you please look at it?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7378](http://archive.tinymce.com/develop/bugtracker_view.php?id=7378) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
