### ISSUE TITLE
HTML parser splits <a> tags around block-level elements even if schema config allows block children

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2099]
Description of problem:

It is valid in HTML5 to have an &ltg;a> element wrap block-level elements, such as &ltg;p>. Example:

```
&ltg;a href="http://example.com/" style="border: 2px solid red;">
    &ltg;p>hello&ltg;/p>
    &ltg;p>world&ltg;/p>
&ltg;/a>
```

However, TinyMCE 4.1.9 does not allow this. Even if I use the addValidChildren method of Schema to define block-level elements as valid children of &ltg;a>, TinyMCE will break up the wrapping &ltg;a> element into multiple &ltg;a> elements inside the child blocks. If I don't use addValidChildren, TinyMCE will simply strip the &ltg;a> tags.

Please change this behavior to allow &ltg;a> elements to contain blocks, as allowed by HTML5.

Steps to reproduce:
1. Give TinyMCE 4 some HTML like the above example, in which an &ltg;a> element contains one or more block-level elements.

Expected result:

The &ltg;a> tag should persist in the parsed DOM.

Actual result:

The wrapping &ltg;a> tag is removed, and new &ltg;a> children of the block elements will wrap the block contents.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7471](http://archive.tinymce.com/develop/bugtracker_view.php?id=7471) posted by [ckimou](http://archive.tinymce.com/profile.php?name=ckimou)_
> 
> _**Tags:** [firefox msie safari chrome a anchor html schema]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
