### ISSUE TITLE
tinymce is not initializing in IE10

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2100]
Description of problem:tinyMCE not initializing in IE10 and IE11 

showing activeEditor null for same code running on Firefox and Chrome

Steps to reproduce:
1.
 tinyMCE.init({
                mode: "exact",
                theme: "advanced",
                height: "500",
                width: "100%",
                verify_html: false,
                file_browser_callback: 'myFileBrowser',
                extended_valid_elements: "iframe[src|width|height|name|align]",
                plugins: "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,save",
                setup: function (ed) {
                    ed.onKeyPress.add(
                    function (ed, evt) {
                    }
                    );
                },
                // Theme options 
                theme_advanced_buttons1: "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
                theme_advanced_toolbar_location: "top",
                theme_advanced_toolbar_align: "left",
                theme_advanced_statusbar_location: "bottom",
                theme_advanced_resizing: true,
                // Example content CSS (should be your site CSS) 
                //content_css: "css/content.css",
                // Drop lists for link/image/media/template dialogs 
                template_external_list_url: "lists/template_list.js",
                external_link_list_url: "lists/link_list.js",
                external_image_list_url: "lists/image_list.js",
                //   media_external_list_url: "lists/media_list.js",  on 181214
                // Style formats 
                style_formats: [
                { title: 'Bold text', inline: 'b' },
                { title: 'Red text', inline: 'span', styles: { color: '#ff0000' } },
                { title: 'Red header', block: 'h1', styles: { color: '#ff0000' } },
                { title: 'Example 1', inline: 'span', classes: 'example1' },
                { title: 'Example 2', inline: 'span', classes: 'example2' },
                { title: 'Table styles' },
                { title: 'Table row 1', selector: 'tr', classes: 'tablerow1' }
                ],
                // Replace values for the template plugin 
                template_replace_values: {
                    username: "Some User",
                    staffid: "991234"
                }
            });
            
            tinyMCE.execCommand('mceAddControl', true, 'editor');

2.
for (var k = 0; k &ltg;= tinymce.editors.length; k++) {
                alert(k + "count of tinymce ");
            }

 tinymce.editors.length  showing 0

3. tinyMCE.get('editor').setContent('');  

showing error 'JavaScript runtime error 'unable to get property 'setContent' of undefined or null reference

Expected result:should set content to editor

Actual result:
getting javascript error
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7384](http://archive.tinymce.com/develop/bugtracker_view.php?id=7384) posted by [shailendrashinde](http://archive.tinymce.com/profile.php?name=shailendrashinde)_

> _**Tags:** [msie msie10 msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
