### ISSUE TITLE
Firefox introducing unwanted tags

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2101]
Description of problem:
Wrapping block-level elements in an &ltg;a> tag (with valid_children set up to allow this) works as expected in Chrome, IE, Safari. In Firefox unwanted &ltg;p>&nbsp;&ltg;/p> is inserted at the start of the content.

Steps to reproduce:
1. Open fiddle in Firefox
2. Click Source Code to view source & see '&ltg;p>&nbsp;&ltg;/p>' at start of content
3. Compare same fiddle in Chrome/IE/Safari - no '&ltg;p>&nbsp;&ltg;/p>' present

Expected result:
no '&ltg;p>&nbsp;&ltg;/p>' present at start of content

Actual result:
&ltg;p>&nbsp;&ltg;/p> is inserted at start of content

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7385](http://archive.tinymce.com/develop/bugtracker_view.php?id=7385) posted by [caitrionad](http://archive.tinymce.com/profile.php?name=caitrionad)_
> 
> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/bDeaab_

**Comment by MarekSupruniuk** [comment]
+1 
the bug breaks my validation, editor returns '<p>&nbsp;</p>' instead of empty value (in firefox only)

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
