### ISSUE TITLE
TinyMCE 4.1.7 inline mode removes anchors when pasting contents from Microsoft Word

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2102]
Description of problem:
TinyMCE removes anchors when pasting contents from Microsoft Word in inline mode when using Firefox. It works as expected in all other browsers. (Tested: Opera, IE, Safari, Chrome)

Steps to reproduce:
1. Open http://fiddle.tinymce.com/dDeaab/2 in Firefox
2. Open Microsoft word and add some test content
3. Copy your test contents from word
4. Paste anywhere in example page

Expected result:
Content is inserted and pre-existing anchors remain.

Actual result:
Content is inserted, but pre-existing anchors get removed.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7386](http://archive.tinymce.com/develop/bugtracker_view.php?id=7386) posted by [bvisto](http://archive.tinymce.com/profile.php?name=bvisto)_

> _**Tags:** [firefox firefox inline firefox word paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/dDeaab/2_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
