### ISSUE TITLE
Media plugin - Capital letters in file extension problem

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2103]
Description of problem:
Media files in audio format with capital letter file extension (e.g. ".MP3" instead of ".mp3") is added in video tags ("&ltg;video>") and cannot be played.

Steps to reproduce:
1. Add an audio file with capital letter file extension (".MP3")
2. Insert audio file 
3. Test

Expected result:
Display audio player and "&ltg;audio>"-tag.

Actual result:
Display video player and "&ltg;video>"-tag.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7387](http://archive.tinymce.com/develop/bugtracker_view.php?id=7387) posted by [alphabrik](http://archive.tinymce.com/profile.php?name=alphabrik)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
