### ISSUE TITLE
Command +  delete key deletes only previous word, not the whole previous line

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2104]
Command + Delete key deletes previous word, but should delete whole previous line as expected.

Steps to reproduce:
1. Type a line of text in TinyMCE examples 
2. Hit Command Key + Delete (on Mac).

Expected result:
The whole previous line should be deleted.

Actual result:
Only previous word is deleted.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7388](http://archive.tinymce.com/develop/bugtracker_view.php?id=7388) posted by [drew](http://archive.tinymce.com/profile.php?name=drew)_
> 
> _**Tags:** [firefox safari chrome firefox safari6 safari7 safari8 safari9 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
