### ISSUE TITLE
TinyMCE not works in IE11

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2106]
Description of problem:

Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7390](http://archive.tinymce.com/develop/bugtracker_view.php?id=7390) posted by [shailendrashinde](http://archive.tinymce.com/profile.php?name=shailendrashinde)_

> _**Tags:** [msie msie10 msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
