### ISSUE TITLE
On Demand toggle on v.4.1.7

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2107]
Description of problem:

Steps to reproduce:
1. Show regular textbox and a button to toggle the textbox into tinymce rich textbox.
2. Fill in the following text inside the text area:

An ICD can be useful in select patients with NSVT (particularly those &ltg;30 years of age) or an abnormal blood pressure response to exercise in the presence of other SCD risk.
1. click the button. This should call initialization on tinyMCE
2. Browser will freeze and (firefox) shows that "A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue."

Expected result: tinyMCE will show up.

Actual result: browser frozen

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7391](http://archive.tinymce.com/develop/bugtracker_view.php?id=7391) posted by [awan2008](http://archive.tinymce.com/profile.php?name=awan2008)_
> 
> _**Tags:** [firefox msie safari chrome ondemand toggle script error]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/uDeaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
