### ISSUE TITLE
The find don't move the text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2108]
Description of problem:
with the version: 40.0.2214.111 of chrome and the canary
with the versi�n 3 of the TinyMCE; when you find the text, the tinyMCE 3.5.11 don't scroll down

Steps to reproduce:
1. open the find and search anything
2. the search find the text but don't move the textarea

Expected result:
when you find the text, the tiny scroll down to see the text finded

Actual result:
only see the original position of the text (in the top of text area)
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7392](http://archive.tinymce.com/develop/bugtracker_view.php?id=7392) posted by [render](http://archive.tinymce.com/profile.php?name=render)_

> _**Tags:** [chrome chrome chromecanary find text ver 3]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
