### ISSUE TITLE
can't edit absolute div content in firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2109]
Description of problem:

can't edit content in an absolute positionned div in firefox

Steps to reproduce:
check the fiddle and try to edit content in the black div

Expected result: editable

Actual result: not editable

using fullpage plugin

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7393](http://archive.tinymce.com/develop/bugtracker_view.php?id=7393) posted by [gabole](http://archive.tinymce.com/profile.php?name=gabole)_

> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/zDeaab_

**Comment by e-gaulue** [comment]
I confirm this behavior.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
