### ISSUE TITLE
Incorrect font name in toolbar when the word is selected using double click after changing font

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2110]
Description of problem:
Font name shows wrong font in toolbar when the word is selected using double click after changing  font.

Steps to reproduce:
1.Open http://www.tinymce.com/tryit/classic.php
2.Select font name as Impact.
3. Type one word in the editor and hit space.
4. Now select font name as Helvetica and type 2 words.
5. Select last 2 words and change font name to different font name.
6. Now select 2nd using double click and observe font name in toolbar.

Expected result:
Styles applied for the clicked word should be displayed in the toolbar buttons

Actual result: Incorrect font name shows up. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7394](http://archive.tinymce.com/develop/bugtracker_view.php?id=7394) posted by [sriram](http://archive.tinymce.com/profile.php?name=sriram)_
> 
> _**Tags:** [firefox msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
