### ISSUE TITLE
Description field with text is not allowing space at th end of the text, instead control is moving to the begining of the Descritpion Field

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2111]
Description of problem:

Steps to reproduce:
1. Open the page with tinymce editor in it that already has text in the Description field
2. Now try to give the space at the end of the existing text in the description, this is taking me the cursor to the begining of the description instead of allowing me to add the text
3 TinyMCE version I am using 4.0.23
4.
5.

Expected result:
Space should be allowed at the end of exisint text in the Description

Actual result:
Cursor is moving to the begining of the text instead of moving right side
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7395](http://archive.tinymce.com/develop/bugtracker_view.php?id=7395) posted by [igprasad](http://archive.tinymce.com/profile.php?name=igprasad)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
