### ISSUE TITLE
paste_word_valid_elements unexpected behavior

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2112]
Description of problem:

When I use 'paste_word_valid_elements' to specify valid elements when pasting from word, rich text formatting breaks when pasting from other sources, such as Google Docs. Some formats will work, such as list items. However, things like bold, italics and links will no longer work when pasting from Google Docs when 'paste_word_valid_elements' is used.

Steps to reproduce:
1. Use the fiddle (basic tinyMCE example with declared paste_word_valid_elements)
2. Paste rich text from Google Docs, including bold, italics and links.

Expected result: To have formatting (bold, italics, links) pasted.

Actual result: Formatting (bold, italics, links) is not pasted.

1. Compare to using the basic TinyMCE example with the 'paste_word_valid_elements' line removed. 
2. When pasting from Google Docs in this case, everything pastes perfectly.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7398](http://archive.tinymce.com/develop/bugtracker_view.php?id=7398) posted by [scsmith](http://archive.tinymce.com/profile.php?name=scsmith)_

> _**Tags:** [firefox safari chrome firefox safari9 chrome word paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/EDeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
