### ISSUE TITLE
line-break after link not always working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2113]
I put links in the editor and press after each enter-key for a line-break. this automaically transform the link-text in clickable link. this plugin have a bug. After press enter the editor insert that html BR before end-tag for A so i type still as link. In one case its closed the A after one character, in other cases its not stop.

Expected:
The line-break should always close a link and write only in text mode.

Actual
The line-break close random link or write after line-break still as link, because BR is included in A.

Is tested in chrome and firefox and both have this problem and firefox much more than chrome.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7411](http://archive.tinymce.com/develop/bugtracker_view.php?id=7411) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** [firefox chrome firefox chrome]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Daijobou** [comment]
You can close this one. I have create a new ticket for this forgotten one.
