### ISSUE TITLE
toolbar button to remove bullet formatting leaves text in bad shape

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2114]
Description of problem:

Steps to reproduce:
1. Navigate to http://www.tinymce.com/
2. In the TinyMCE editor select middle four bullet points with mouse
3. Hit [tab] to indent
4. From toolbar, click bullet button to remove bullets

Expected result:
4 lines have their bullet formatting removed

Actual result:
Combination of empty bullets and normal text
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7400](http://archive.tinymce.com/develop/bugtracker_view.php?id=7400) posted by [ribbles](http://archive.tinymce.com/profile.php?name=ribbles)_

> _**Tags:** [ul list]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://www.tinymce.com/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
