### ISSUE TITLE
Hyperlink text with sup in table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2115]
Description of problem:

Steps to reproduce:
1. Create a table
2. Add text to the table cell
3. Add a superscript next to the text
4. Hyperlink just the text

Expected result:
You should get the hyperlink only on the text and not include the superscript text.

Actual result:
The hyperlink text is inside the superscript tags.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7401](http://archive.tinymce.com/develop/bugtracker_view.php?id=7401) posted by [ebozzetti](http://archive.tinymce.com/profile.php?name=ebozzetti)_
> 
> _**Tags:** [firefox msie safari chrome hyperlink superscript]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/cEeaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
