### ISSUE TITLE
Edits to Hyperlink Not Saved in AngularJS App

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2116]
I'm using tinyMCE 4.1.7 in an angularjs application. When a user inserts a new hyperlink (using the dialog box in the menu bar) it works fine. When they later try to edit that same link, the edits to the link will appear on the display correctly, but when the edited material is saved, the edited link is not saved correctly, but reverts back to the unedited version. All other edits save correctly, and deleting the link entirely, saving, and inserting a new link also works.

Steps to reproduce:
1. Create textarea that includes a hyperlink
2. Save
3. Select the hyperlink, and change it using the "Insert Hyperlink" dialog. The dialog is diplaying the previous hyperlink information correctly, but the title of the dialog says "Insert" not "Edit"
4. Save
5. Hyperlink is back to old version

Expected result:
Hyperlink should have changes.

I've reproduced this in Chrome, Safari, and Firefox. Since its an AgularJS app, I'm including the directive:

Actual result:

Angular Directive Code:
/**
- Binds a 4.0 TinyMCE widget to &ltg;textarea> elements.
  */
  angular.module('ui.tinymce', [])
  .value('uiTinymceConfig', {width: '100%' , height:400 })
  .directive('uiTinymce', ['uiTinymceConfig', function (uiTinymceConfig) {
      uiTinymceConfig = uiTinymceConfig || {};
      var generatedIds = 0;
      return {
          priority: 10,
          require: 'ngModel',
          link: function (scope, elm, attrs, ngModel) {
              var expression, options, tinyInstance,
                  updateView = function () {
                      ngModel.$setViewValue(elm.val());
                      if (!scope.$root.$$phase) {
                          scope.$apply();
                      }
                  };
  
  ```
          // generate an ID if not present
          if (!attrs.id) {
              attrs.$set('id', 'uiTinymce' + generatedIds++);
          }
  
          if (attrs.uiTinymce) {
              expression = scope.$eval(attrs.uiTinymce);
          } else {
              expression = {};
          }
  
          // make config'ed setup method available
          if (expression.setup) {
              var configSetup = expression.setup;
              delete expression.setup;
          }
  
          options = {
              // Update model when calling setContent (such as from the source editor popup)
              setup: function (ed) {
                  var args;
                  ed.on('init', function(args) {
                      ngModel.$render();
                      ngModel.$setPristine();
                  });
                  // Update model on button click
                  ed.on('ExecCommand', function (e) {
                      ed.save();
                      updateView();
                  });
                  // Update model on keypress
                  ed.on('KeyUp', function (e) {
                      ed.save();
                      updateView();
                  });
                  // Update model on change, i.e. copy/pasted text, plugins altering content
                  ed.on('SetContent', function (e) {
                      if (!e.initial && ngModel.$viewValue !== e.content) {
                          ed.save();
                          updateView();
                      }
                  });
                  ed.on('blur', function(e) {
                          elm.blur();
                  });
                  // Update model when an object has been resized (table, image)
                  ed.on('ObjectResized', function (e) {
                      ed.save();
                      updateView();
                  });
                  if (configSetup) {
                      configSetup(ed);
                  }
              },
              plugins: "link searchreplace paste template code hr",
              external_plugins: { "nanospell": "/campaign-mail/app/lib/tinymce4.1.7/plugins/nanospell/plugin.js" },
              nanospell_server:"php",
              templates: [ 
                  {title: 'Campaign Welcome', description: 'Notification of Acceptance', url: 'templates/welcome.html'}, 
                  {title: 'Post Reminder', description: 'Reminder to submit Proof of Post', url: 'templates/reminder.html'}, 
                  {title: 'Post Past Due', description: 'Notice that Proof of Post is past due', url: 'templates/final.html'},
                  {title: 'Breach of Contract',description: "Notice that Proof of Post is missing after campaign is done", url: 'templates/breach.html'},
                  {title: 'Blog Post/Amplication Edits',description: "Request for changes to Proof of Post form", url: 'templates/edits.html'},
                  {title: 'Carmen Signature',description: "Personalized signature block", url: 'templates/carmen.html'},
                  {title: 'Edita Signature',description: "Personalized signature block", url: 'templates/edita.html'},
                  {title: 'Jenny Signature',description: "Personalized signature block", url: 'templates/jenny.html'},
                  {title: 'Robin Signature',description: "Personalized signature block", url: 'templates/robin.html'},
                  {title: 'Sarah Signature',description: "Personalized signature block", url: 'templates/sarah.html'},
              ],
              menubar: "format edit insert tools",
              toolbar: "bold italic underline | fontselect fontsizeselect | bullist numlist indent outdent | alignleft aligncenter alignright | link template | undo redo",
  ```

// "bold italic underline | link unlink bullist numlist | fontselect fontsizeselect formatselect",
                    mode: 'exact',
                    elements: attrs.id
                };
                // extend options with initial uiTinymceConfig and options from directive attribute value
                angular.extend(options, uiTinymceConfig, expression);
                setTimeout(function () {
                    tinymce.init(options);
                });

```
            ngModel.$render = function() {
                if (!tinyInstance) {
                    tinyInstance = tinymce.get(attrs.id);
                }
                if (tinyInstance) {
                    tinyInstance.setContent(ngModel.$viewValue || '');
                }
            };

            scope.$on('$destroy', function() {
                if (!tinyInstance) { tinyInstance = tinymce.get(attrs.id); }
                if (tinyInstance) {
                    tinyInstance.remove();
                    tinyInstance = null;
                }
            });
        }
    };
}]);
```

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7402](http://archive.tinymce.com/develop/bugtracker_view.php?id=7402) posted by [sheilatabuena](http://archive.tinymce.com/profile.php?name=sheilatabuena)_
> 
> _**Tags:** [firefox safari chrome firefox safari7 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
