### ISSUE TITLE
formatting gets lost while selecting all text and type some text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2117]
Description of problem:

Steps to reproduce:
1.select font type(courier new) and size(36).
2.type some line of text 
3.select all and 
4.type some text 

Expected result: formatting should not have to lost, select formatting should remains present.

Actual result: selected formatting gets lost.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7403](http://archive.tinymce.com/develop/bugtracker_view.php?id=7403) posted by [snehal1112](http://archive.tinymce.com/profile.php?name=snehal1112)_

> _**Tags:** [firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by khushangmbhavnagarwala** [comment]
I have still found this issue in v4.5.7 where I am applying any settings into the paragraph and select all text using Ctrl + A and write something then It will be losing all the formatting. 
![awesomescreenshot-2017-05-23t10-59-33-149z](https://cloud.githubusercontent.com/assets/28893663/26351828/c098bd3a-3fd6-11e7-9097-1fc27dad0918.gif)
