### ISSUE TITLE
TinyMCE scrolls automatically down on editing

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2119]
Description of problem:
Editor automatically scrolls down on editing the text.
Steps to reproduce:
1.Click on tinymce editor area to edit
2.Page scrolls down automatically

Expected result:
It should allow to edit without any scroll.
Actual result:
Scrolls automatically down
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7405](http://archive.tinymce.com/develop/bugtracker_view.php?id=7405) posted by [Prabhakar.M](http://archive.tinymce.com/profile.php?name=Prabhakar.M)_

> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by cpalafox** [comment]
So they don't plan on fixing this issue ever right?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
