### ISSUE TITLE
The add method in the I18n class ignores the language code

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2120]
The method documented here:
- http://www.tinymce.com/wiki.php/api4:method.tinymce.util.I18n.add

seems to ignore the first parameter (the language code).

Method code:
add: function(code, items) {
                        for (var name in items) {
                                data[name] = items[name];
                        }

```
                    this.rtl = this.rtl || data._dir === 'rtl';
```

},

As a result, this way of using the above method doesn't work:

tinymce.addI18n('pl', {  
    "insert":"Wstaw",
    "cancel":"Anuluj"  
});

I have to write something like this:
tinymce.addI18n('pl', {  
    "pl.insert":"Wstaw",
    "pl.cancel":"Anuluj"  
});

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7406](http://archive.tinymce.com/develop/bugtracker_view.php?id=7406) posted by [mzakrzewski](http://archive.tinymce.com/profile.php?name=mzakrzewski)_
> 
> _**Tags:** [firefox msie safari chrome i18n]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
