### ISSUE TITLE
TypeError when calling tinymce.remove() in onblur handler

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2121]
Description of problem: TinyMCE throws a TypeError if you call tinymce.remove() in an onblur event handler.

Steps to reproduce:
1. Initialize a tinymce instance with a setup() function.
2. In the setup() function, add an onblur event listener that calls tinymce.remove() to remove the instance.
3. After the editor appears, type some text and click away so it loses focus.

Expected result: The editor is removed without errors.

Actual result: tinymce removes the editor but throws a TypeError. In version 4.0.11, the error is: "Uncaught TypeError: Cannot set property 'lastFocusBookmark' of null".

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7407](http://archive.tinymce.com/develop/bugtracker_view.php?id=7407) posted by [stenrap](http://archive.tinymce.com/profile.php?name=stenrap)_
> 
> _**Tags:** [firefox chrome firefox chrome lastfocusbookmark]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/EEeaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by rart** [comment]
This issue still persists on the latest (v5).

```
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
tinymce.init({
  target: myElementRef,
  plugins: ['quickbars'],
  toolbar: false,
  menubar: false,
  inline: true,
  suffix: '.min',
  setup(editor) {
    editor.on('init', function (e) {
      editor.focus();
      editor.selection.select(editor.getBody(), true);
      editor.selection.collapse(false);
    });
    editor.on('blur', function (e) {
      editor.destroy(false);
    });
  }
});
</script>
```

```
tinymce.min.js:9 Uncaught TypeError: Cannot read property 'childNodes' of null
    at dg (tinymce.min.js:9)
    at gg (tinymce.min.js:9)
    at tinymce.min.js:9
    at Object.add (tinymce.min.js:9)
    at EE.i (tinymce.min.js:9)
    at Gz.fire (tinymce.min.js:9)
    at EE.fire (tinymce.min.js:9)
    at tinymce.min.js:9
    at tinymce.min.js:9
```

<img width="615" alt="image" src="https://user-images.githubusercontent.com/3928341/71717293-f05d6700-2e17-11ea-8086-0383dbfc3fd5.png">

Adding a timeout seems to do the trick.
```js
    editor.on('blur', function (e) {
      setTimeout(() => editor.destroy(false));
    });
```
