### ISSUE TITLE
Chrome crash after submitting the form (TinyMCE 3.x)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2123]
Description of problem: 

After opening a dialog (I've seen this in different plugins using mceInsertContent, but I don't know if that's related to the problem) and submitting the form, you press Ctrl-Z and G. Chrome crashes.

Steps to reproduce:
1. Go to the full featured example (3.x): http://www.tinymce.com/tryit/3_x/full.php
2. Click on "Edit HTML source".
3. Write something and click on "Update".
4. Submit the form.
5. Press Ctrl+Z.

Expected result:

None.

Actual result:

...
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7409](http://archive.tinymce.com/develop/bugtracker_view.php?id=7409) posted by [ignaciogros](http://archive.tinymce.com/profile.php?name=ignaciogros)_

> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
