### ISSUE TITLE
Character < followed by combination of other characters causes js crash

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2124]
Description of problem:
Initialization of TinyMCE causes browser to freeze.

Steps to reproduce:
1.Open provided fiddle
2. Copy and paste the following paragraphs:

--- start of paragraph
An ICD can be useful in select patients with NSVT (particularly those &ltg;30 years of age) or an abnormal blood pressure response to exercise in the presence of other SCD risk.
--- end of paragraph

3. Click 'Activate RichTextbox'
4. RichTextbox will not appear and browser will freeze

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7410](http://archive.tinymce.com/develop/bugtracker_view.php?id=7410) posted by [awan2008](http://archive.tinymce.com/profile.php?name=awan2008)_

> _**Tags:** [firefox msie safari chrome bug character freeze]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/uDeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
