### ISSUE TITLE
4 fields for margins in the image insert form

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2127]
Most usually pictures are inserted floating right or left, so they should have, for example, only margin-left and margin-bottom set to some pixels.
But the Insert Image form sets margins only in pairs, as if it were hspace & vspace. It looks awful. Manual correction of that is a PITA, because clearing Horisontal or Vertical Space field clears any margins in style, even those corrected manually. And if not cleared they reset manual margins on pressing Save button or the like.
So PLEASE, if modern TinyMCE uses margins instead of hs,vs, MAKE 4 SEPARATE fields for margins, preferably placed in a cross manner.
It will be much more convenient in most cases.
Thanx!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7414](http://archive.tinymce.com/develop/bugtracker_view.php?id=7414) posted by [alancast](http://archive.tinymce.com/profile.php?name=alancast)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
