### ISSUE TITLE
Inappropriate non-breaking space

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2129]
Description of problem:

If I type two spaces after a full stop (period) in Chrome, TinyMCE replaces this with a space followed by a non-breaking space.  See the example below:

&ltg;p>This is one sentence. &nbsp;This is another sentence.&ltg;/p>

This means that if the text wraps between sentences, the second one is indented.  For example:

This is one sentence.
 This is another
sentence.

If I do the same in IE, the &nbsp; is before the space, which means the text wraps appropriately.

Steps to reproduce:
1.  In Chrome, go to the sample editor on the website (http://www.tinymce.com/tryit/basic.php).
1. Type text that includes a full stop followed by two spaces, like the example above.
2. View the source.

Expected result:
&ltg;p>This is one sentence.&nbsp; This is another sentence.&ltg;/p>

Actual result:
&ltg;p>This is one sentence. &nbsp;This is another sentence.&ltg;/p>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7416](http://archive.tinymce.com/develop/bugtracker_view.php?id=7416) posted by [Don B](http://archive.tinymce.com/profile.php?name=Don B)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
