### ISSUE TITLE
Cannot insert Table after Undo clears all content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2133]
Description of problem: Attempting to insert a table is throwing an error after using Undo under specific circumstances.

Steps to reproduce:
1.Open http://www.tinymce.com/tryit/inline.php
2.Inside the editor, press Ctrl+A To Select All
3.Delete all content with Delete key
4.Press Enter
5.Type a word into the editor
6.Press Enter
7.Insert a 3x3 Table via the Table drop-down
8.Press Ctrl+Z to Undo (Table will disappear)
9.Press Ctrl+Z to Undo (Word will disappear)
10.Attempt to insert a table again via the Table drop-down

Expected result: A table is inserted into the editor

Actual result: Nothing displays and the console shows the following error:
"Uncaught NotSupportedError: Failed to execute 'createContextualFragment' on 'Range': The range's container is 'br', which is not supported."

Easiest fix appears to be to modify the setContent function to detect when there is only one child node that is the &ltg;br data-mce-bogus="1"> node.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7441](http://archive.tinymce.com/develop/bugtracker_view.php?id=7441) posted by [Brandon.Tracy](http://archive.tinymce.com/profile.php?name=Brandon.Tracy)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
