### ISSUE TITLE
link_list no focus for current link

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2134]
Tested with 4.1.7

Description of problem:

Steps to reproduce:
1. add the link _Category Level 24_
2. edit it again
3. in link form you see, which link it is, but if you open link list, you have to scroll down to exact see, which one it is (colorized one)

Expected result:

on edit the link and open the link list, scroll position should be at position of selected link

Actual result:

if you edit the link and open link list, scroll position is on top

In this fiddle: http://fiddle.tinymce.com/pFeaab/2 for _Category Level 24_ there are submenus... same happen here...
Here if you scroll down, and open _Category Level 24_ only select submenu are colorized.. In this case, the whole path should be colorized...

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7420](http://archive.tinymce.com/develop/bugtracker_view.php?id=7420) posted by [thomi](http://archive.tinymce.com/profile.php?name=thomi)_
> 
> _**Tags:** [msie safari chrome msie11 safari5 safari7 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/pFeaab/1_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
