### ISSUE TITLE
Wrong translation string

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2135]
I'm using a translation and all the tooltips are in Italian, so I guess I link the right translation (it.js).

As you can see in the image I still get the English version of this message:
http://note.io/18F7MbE

While my it.js, line 5, is:

"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Il tuo browser non supporta l'accesso diretto negli Appunti. Per favore usa i tasti di scelta rapida Ctrl+X\/C\/V.",

Is it possible that tinymce while replacing the text: "Ctrl" as I'm on a Mac, forgets to do it in the translated string?

Or is there another string for the Mac that I was not able to find at https://www.transifex.com/projects/p/tinymce/language/it/ ?

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7421](http://archive.tinymce.com/develop/bugtracker_view.php?id=7421) posted by [ugrandolini](http://archive.tinymce.com/profile.php?name=ugrandolini)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
