### ISSUE TITLE
Multi-column support in Tiny MCE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2137]
Currently TinyMCE plugin supports lots of features available in MSWord. One such feature which my project is looking for is Multi-column support. Can this feature be added in future releases of TinyMCE

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7423](http://archive.tinymce.com/develop/bugtracker_view.php?id=7423) posted by [pagupta](http://archive.tinymce.com/profile.php?name=pagupta)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
