### ISSUE TITLE
Spellcheck request missing charset spec, causing content being decoded incorrectly at server side.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2147]
Description of problem:
Spellcheck request missing 'charset=UTF-8' spec in contentType, causing content being decoded incorrectly at server side.

example:
char 'ê' has been encoded as "%C3%AA" in request but later decoded as two char:
�?    %C3
ª  %AA 

---all right the example doesn't seem to display correctly due to the encoding issue.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7433](http://archive.tinymce.com/develop/bugtracker_view.php?id=7433) posted by [bubdou](http://archive.tinymce.com/profile.php?name=bubdou)_
> 
> _**Tags:** [msie chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
