### ISSUE TITLE
<input type="text"/> can't be edited/click on chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2148]
Description of problem:

I am using the CDN version of tinymce, hence, the latest (v4.1.9).
My Google Chrome is also updated to the latest version.
&ltg;input type="text"/> can't be edited/click on chrome, but on firefox it is working fine.

Steps to reproduce:
1. See fiddle.tinymce.com/cGeaab
2. Browse it using Chrome
3. Try to edit the input form, and you'll see it can't be clicked.
4. Now browse it on Firefox, you'll see it's working fine.

Expected result:
&ltg;input /> Should be editable/click-able in Chrome just like in Firefox

Actual result:
&ltg;input /> Can't be edit/click on Google Chrome.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7434](http://archive.tinymce.com/develop/bugtracker_view.php?id=7434) posted by [sirjhep](http://archive.tinymce.com/profile.php?name=sirjhep)_

> _**Tags:** [chrome chrome input forms chrome click edit focus]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/cGeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
