### ISSUE TITLE
Collision with drag/drop events

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2149]
Description of problem: When using Tinymce and jquery-file-upload (https://github.com/blueimp/jQuery-File-Upload/) on the same page, images are duplicated when dragged and redirect to themselves when dropped hover them (Firefox only)

Steps to reproduce:
1. Load tinymce & jquery-file-upload
2. Insert an image
3. Try to move it or drop it hover itself

Expected result: Image should move

Actual result: Image is duplicated or redirects to itself.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7435](http://archive.tinymce.com/develop/bugtracker_view.php?id=7435) posted by [Tyrius](http://archive.tinymce.com/profile.php?name=Tyrius)_
> 
> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** https://jsfiddle.net/Lxk9vvo4/2/_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
