### ISSUE TITLE
numlist, bullist unexpected behavior on backspace/delete when Font size/family is not default

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2150]
Description of problem: numlist,bullist problem in IE. It works as expected in Chrome and FF. (I have tested using tinyMCE 4.1.7 and tinyMCE 4.1.9)

Steps to reproduce:
1.Type something in the editor in IE
2.Change Font Size and/or Font Family
3.Click on numlist/bullist and add few lines
4.Use backspace to delete line in between
5.

Expected result: numlist should be reset

Actual result: it deletes the line but add new line/s after that. If I change fontsize/fontfamily to default then backspace to remove line from list gives error: "Line: 1
Error: Unable to get property 'firstChild' of undefined or null reference" in plugin.min.js file.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7436](http://archive.tinymce.com/develop/bugtracker_view.php?id=7436) posted by [tinymcetesting](http://archive.tinymce.com/profile.php?name=tinymcetesting)_
> 
> _**Tags:** [msie msie9 msie10 msie11 numlist bullist numbered tinymce]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
