### ISSUE TITLE
newdocument: text goes to next line, bullist,numlist do not appear

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2151]
Description of problem: newdocument: text goes to next line and bullist,numlist do not appear in the editor.(I have tested using tinyMCE 4.1.7 and tinyMCE 4.1.9)

Steps to reproduce:
1.Load the page with editor
2.Type something.
4.Click newdocument from File menu
5.Enter some text (goes to next line)
OR
6.Select numlist/bullist (does not appear until some text is entered into the editor)

Expected result: 1. Text should be in first line of the editor after doing new document.
2.numlist/bullist should be displayed

Actual result:
1. text goes to next line.
2. numlist/bullist do not appear unless some text is entered into the editor

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7437](http://archive.tinymce.com/develop/bugtracker_view.php?id=7437) posted by [tinymcetesting](http://archive.tinymce.com/profile.php?name=tinymcetesting)_

> _**Tags:** [firefox msie safari chrome numlist bullist newdocument]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
