### ISSUE TITLE
Error with text selections on inline elements (inline mode)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2153]
Description of problem:

In inline editing mode, making a selection on an inline element and then typing throws the following error:

Chrome/Opera: "Uncaught TypeError: Cannot read property 'firstChild' of null"

Safari: "TypeError: null is not an object (evaluating 'node.firstChild')"

Steps to reproduce:
1. Go to http://fiddle.tinymce.com/aJeaab/2
2. Make a selection over some text.
3. Type a letter.

Expected result:

The selection is replaced with the letter you type.

Actual result:

The selection is removed, but the letter you typed doesn't appear and an error is shown in the console.

Notes:
- This only appears to affect inline elements. If you change the &ltg;span> to a &ltg;div>, the error doesn't appear.
- Started happening in 4.1.8, still happening in edge.
  
  > _**Legacy information imported from TinyMCE bug tracker:**_
  > 
  > _[#T7460](http://archive.tinymce.com/develop/bugtracker_view.php?id=7460) posted by [aksival](http://archive.tinymce.com/profile.php?name=aksival)_

> _**Tags:** [safari chrome inline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/aJeaab/2_

**Comment by guilherme6191** [comment]
+1

I'm also getting this error in production.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
