### ISSUE TITLE
Display:table element seriously breaks editing.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2154]
Description of problem:

Steps to reproduce:
1. Go to http://www.tinymce.com/tryit/inline.php
2. Add a new Heading-1 h1, between paragraphs, and type something, like "Hello there"
3. Have that element be display:table. You can do so on example page in f12 console with: jQuery('h1').css('display','table')
4. Select most or all of the h1 text and type something over it

Expected result:
It should type in the header as usual

Actual result:
It removes the h1, and sometimes even puts the cursor on another paragraph. (Only in Chrome)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7439](http://archive.tinymce.com/develop/bugtracker_view.php?id=7439) posted by [Luke_sf](http://archive.tinymce.com/profile.php?name=Luke_sf)_
> 
> _**Tags:** [chrome chrome table display]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Luke-SF** [comment]
Furthermore, it breaks when you create a new heading: Click in the main editor here, remove all text, select Formats->Headings->H2, then note that you can't type text in the new heading, it is just a red border! This is still happening in Chrome 54.

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by Luke-SF** [comment]
While the table element bug was fixed in Chrome, the bug in codepen above still happens (4.6.1).
