### ISSUE TITLE
ExecCommand event is not fired when changing element color

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2155]
See this TinyMCE fiddle:  http://fiddle.tinymce.com/vGeaab

console.log is called when bolding text, but not when changing is foreground or background color.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7442](http://archive.tinymce.com/develop/bugtracker_view.php?id=7442) posted by [JoeCoder](http://archive.tinymce.com/profile.php?name=JoeCoder)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
