### ISSUE TITLE
Class applied to parent of block element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2156]
Description of problem:

When applying a class from the Format list that is a "mixed format inline + block level" to a block element (eg: paragraph) inside another block element, the class is applied to the parent element, not the intended block element.

Steps to reproduce:
1.In the Fiddle example, select the paragraph using the Path.
2. Select one of the classes from the Format list

Expected result:

The class should be applied to the paragraph.

Actual result:

The class is applied to the div.

If the style_format is created with an element selector, eg:

{title: "Red", classes: "red", selector: "p"}

this obviously does not happen, but the mixed inline/block format is much more useful, as it allows classes to be applied to any element.

A possible fix is to change the condition on line 1363 of Formatter.js 

https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/Formatter.js#L1363

from 

if (!format[0].block_expand && isBlock(parent)) {

to

if (isBlock(parent)) {

This seems to work fine in all my tests.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7443](http://archive.tinymce.com/develop/bugtracker_view.php?id=7443) posted by [happy_noodle_boy](http://archive.tinymce.com/profile.php?name=happy_noodle_boy)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/zGeaab/1_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
