### ISSUE TITLE
accessibility issue with textarea

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2158]
Dear TinyMCE support team: 
We use your text editor in ours Websites and we found an important issue working with it.
We have some people with disabilities in our company that need to use a ScreenReader (some people are blind).
The thing is that  trying to use the TinyEditor with ScreenReaders is impossible. 

We notice that in your JavaScript file named tinymce.js, the role=�application� is assigned to the whole page (body), and this is the reason because a screenreader user can�t navigate properly a page with Tiny (the role assigned tells screenreaders the whole page is an application). 

Perhaps you wanted to asign, or should assign, the role application just for the container div with the text editor (or to the textarea directly), or not (maybe this role shoudn�t be assigned/used).

Would be possible to observe this in your files in order to be able to use your editor with ScreenReaders?

Thanks in advance. 
Best Regards. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7445](http://archive.tinymce.com/develop/bugtracker_view.php?id=7445) posted by [AccONCE](http://archive.tinymce.com/profile.php?name=AccONCE)_
> 
> _**Tags:** [firefox msie safari chrome accessibility screenreaders]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
