### ISSUE TITLE
fontsize_formats does not work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2159]
Description of problem:

cannot change "fontsize_formats":

tinyMCE.init({
	    fontsize_formats: "1pt 2pt 3pt 4pt 5pt 6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 17pt 18pt 19pt 20pt 21pt 22pt 23pt 24pt 25pt 26pt 27pt 28pt 29pt 30pt 31pt 32pt 33pt 34pt 35pt 36pt",
		

will leave that fonts list by default...

Steps to reproduce:
1. usage of tinymce majorVersion:"3",minorVersion:"5.10",releaseDate:"2013-10-24"
2.
3.
4.
5.

Expected result:
More fonts in fonts list

Actual result:
Font still by default
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7446](http://archive.tinymce.com/develop/bugtracker_view.php?id=7446) posted by [jmar83](http://archive.tinymce.com/profile.php?name=jmar83)_

> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by kosuodhmwa** [comment]
Not really with version 3.5.8 , here we need **_"theme_advanced_font_sizes"_** instead of **_"fontsize_formats"_**

SO:

...,
...,
theme_advanced_font_sizes : "8pt,9pt,10pt,11pt,12pt,14pt,18pt,24pt,30pt,36pt,48pt,60pt,72pt,96pt",
...,
...
