### ISSUE TITLE
iframe: aligncenter classes get lost?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2160]
Description of problem:

iframe is not centered in source code and after submit

Steps to reproduce:
1. go to http://fiddle.tinymce.com/VGeaab
2. scroll down to iframe
3. center iframe with button "center"
4. open source editor
5. you can see that iframe have no styles for centering, but in editor its centered.

Expected result:

center iframe in souce code and after submit

Actual result:

iframe stick always left in source code and after submit
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7447](http://archive.tinymce.com/develop/bugtracker_view.php?id=7447) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [firefox msie safari chrome iframe forced_root_block]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/VGeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
