### ISSUE TITLE
Cellpadding is attribute and not style

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2162]
Description of problem:

https://ajaxcontroltoolkit.codeplex.com/workitem/27075

The cellpadding attribute of &ltg;table> is not supported 
in HTML5. Use CSS(Style) instead.

Config is with

schema:'html5'

but editor set table attribut instead of style in td.

maybe that is the same here since long time:
http://www.tinymce.com/develop/bugtracker_view.php?id=5835
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7449](http://archive.tinymce.com/develop/bugtracker_view.php?id=7449) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [firefox msie safari chrome table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
