### ISSUE TITLE
Add CSS src to Template Plug-In

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2163]
Description of feature:

I propose adding an option to the template plugin to provide a custom CSS location. As it stands, as far as I can tell, the only css being pulled at this time is the "content.inline.min.css" file.

The reason for this change is to add your custom css to various templates to have them display properly in the preview window.

To use, you declare your template as normal, except you can optionally add your css source, like:

{
    title           : 'My Template',
    url             : '/templates/my_template.html',
    description     : 'This is an template description.',
    css             : [
                        '/css/my_template_css1.css',
                        '/css/my_template_css2.css'
                    ]
}

For the plug-in file, the changes are fairly simple (using version 4.1.9): 

Line 41 Change:

tinymce.each(templateList, function(template) {
    values.push({
        selected: !values.length,
        text: template.title,
        value: {
            url: template.url,
            content: template.content,
            description: template.description
        }
    });
});

... to ...

tinymce.each(templateList, function(template) {
    values.push({
        selected: !values.length,
        text: template.title,
        value: {
            url: template.url,
            content: template.content,
            description: template.description,
            css: template.css || []
        }
    });
});

Line 56 change:

function insertIframeHtml(html) {
    if (html.indexOf('&ltg;html>') == -1) {
        var contentCssLinks = '';

```
    tinymce.each(editor.contentCSS, function(url) {
        contentCssLinks += '&ltg;link type="text/css" rel="stylesheet" href="' + editor.documentBaseURI.toAbsolute(url) + '">';
    });
           ...
```

... to ...

function insertIframeHtml(html, css) {
    if (html.indexOf('&ltg;html>') == -1) {
        var contentCssLinks = '';

```
    tinymce.each(editor.contentCSS, function(url) {
        contentCssLinks += '&ltg;link type="text/css" rel="stylesheet" href="' + editor.documentBaseURI.toAbsolute(url) + '">';
    });

    tinymce.each(css, function(url) {
        contentCssLinks += '&ltg;link type="text/css" rel="stylesheet" href="' + editor.documentBaseURI.toAbsolute(url) + '">';
    });
            ...
```

And finally line 90 change

insertIframeHtml(templateHtml);

... to ...

insertIframeHtml(templateHtml, value.css);

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7450](http://archive.tinymce.com/develop/bugtracker_view.php?id=7450) posted by [stldoug](http://archive.tinymce.com/profile.php?name=stldoug)_
> 
> _**Tags:** [firefox msie safari chrome template plugin css]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
