### ISSUE TITLE
Right-click context menu should include Table Properties

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2165]
Description of problem:

Steps to reproduce:
1. Insert a table into the editor
2. Right-click on the table

Expected result:
Context menu should include Table Properties item.

Actual result:
It does not appear in the Context menu -- only available by clicking the Table button in the main editor toolbar.  (Many users don't know to look there.)

Thanks!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7452](http://archive.tinymce.com/develop/bugtracker_view.php?id=7452) posted by [speednet](http://archive.tinymce.com/profile.php?name=speednet)_
> 
> _**Tags:** [firefox msie safari chrome table context menu]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
