### ISSUE TITLE
Empty DIV disappears if its CSS is set to float: left; or display: inline-block;

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2166]
Description of problem:

In latest Chrome (or Opera) if a DIV has a float: left; or display: inline-block; styling and I delete the last character from this DIV in visual mode then it disappears.

Steps to reproduce:
1. Insert this code in HTML mode: &ltg;div style="background-color: #ccc; width: 50%; float: left;">testing&ltg;/div>
2. Switch to visual mode and remove the text from the box

Expected result:

The DIV should be still there after removing text from it (like in FF or IE).

Actual result:

The DIV disappears.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7453](http://archive.tinymce.com/develop/bugtracker_view.php?id=7453) posted by [divpusher](http://archive.tinymce.com/profile.php?name=divpusher)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/iIeaab_

**Comment by kangarolf** [comment]
I am also experiencing this issue on all version after 4. Older versions do not have this issue. You also get some weird selection issues when double clicking or highlighting the contents of floated elements.

This issue completely disappears when you use Edge, Firefox or IE.

http://fiddle.tinymce.com/rnfaab/3

If you use Chrome the divs disappear, but also try double clicking on the text 'Div' in the left column..it highlights 'Right' as well in the right column.

**Comment by vitorcoxta** [comment]
I'm also noticing this on Chrome, and not in other browsers

**Comment by nori-h** [comment]
I believe this is similar to #1892 #2510 and #2638. Could you have please have a look and let us know if not? Thanks, Nori @ TinyMCE

**Comment by kangarolf** [comment]
Hi Nori-h no its not the same behaviour as those other issues, though it is probably tied up to similar issues. Here we also have the complication of the floated elements and how it selects them. If you select the left floated div in the fiddle;

http://fiddle.tinymce.com/rnfaab/3

And delete the right floated element is removed.

Rolf

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by batata004** [comment]
@fyrkant I am having this issue my friend. You can try a use case here -> https://github.com/tinymce/tinymce/issues/3888   we use the third version of tinymce in https://www.sitepor500.com.br (there is an editor at the bottom when the user sends a contact form to us) and this bug does not happen, it only happens with the version 4. That's why we still didnt update the editor of our website to version 4 cause in the version 3 it works fine.

**Comment by batata004** [comment]
@fyrkant  could you please open this???
