### ISSUE TITLE
Webkit deletes single cell table after backspace if cell is empty...

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2167]
Description of problem: on Webkit browsers if there is a table with a single cell (1x1) and the user types something and then backspaces to erase everything typed the table will be deleted after the last character is cleared. This does not happen in Trident or Gecko browsers.

Steps to reproduce:
1. Make a 1x1 table.
2. In the single cell type "test".
3. Backspace until all text is cleared.

Expected result: The table should remain (albeit empty).

Actual result: The table is deleted.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7455](http://archive.tinymce.com/develop/bugtracker_view.php?id=7455) posted by [JYIC](http://archive.tinymce.com/profile.php?name=JYIC)_
> 
> _**Tags:** [chrome table webkit]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by adotout** [comment]
This is still happening in 4.3.12. Is there any workaround?

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
