### ISSUE TITLE
Old releases

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2169]
I am looking for 3.3.9.1 but cannot find it anywhere. I would like to propose that old releases would be made available because there are situations where one might not want to update from 3.3.9.0 to too new because it may cause problems.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7456](http://archive.tinymce.com/develop/bugtracker_view.php?id=7456) posted by [ZiaHxp](http://archive.tinymce.com/profile.php?name=ZiaHxp)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
