### ISSUE TITLE
Getting TypeError: Argument 1 of Range.setStart is not an object. on code edit

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2170]
Description of problem:
Getting TypeError: Argument 1 of Range.setStart is not an object. error after clicking of "Ok" button in code edit popup

Steps to reproduce:
1.Click "Source code"/Code button in template
2.Change something in that view
3.Click on "Ok" button

Expected result:
The changes made in Code edit popup should reflect in template content

Actual result:
Getting error on click of "Ok" in code edit popup

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7457](http://archive.tinymce.com/develop/bugtracker_view.php?id=7457) posted by [chethankswamy](http://archive.tinymce.com/profile.php?name=chethankswamy)_

> _**Tags:** [firefox msie safari chrome code plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
