### ISSUE TITLE
Tinymce clearly adding <br /> tags to content with screenshots

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2171]
In your FAQs page, for the question "TinyMCE adds BR elements to my content", you state that it is not your doing and that we're probably using the php function nl2br(). This appears to be incorrect. Through the following screenshots, i'll show you that you are adding &ltg;br /> tags in the tinymce editor without my doing.

1) This is html inside the tinymce editor (I used google chrome > inspect element to look at the html within your iframe). As you can see, within each &ltg;div> there is a &ltg;br /> tag. These br tags are not in the actual html. That was added after it was compiled on your servers. 

http://gyazo.com/8ad0fcea49c73b025ae1cab4b4a5dc5b

2) This is the html that's actually stored in our database. This just proves that there is no &ltg;br /> tags within each &ltg;div>.

http://gyazo.com/5fe8a95671901597f7f0b0dd005030fb

3) This is the ONLY php code were using to gather and output the html that is used within the tinymce editor. As you can see, were not using nl2br().

http://gyazo.com/6827a0efa22ac312ca5dbe23e869407c

I'm bringing this to your attention because there is a significant difference between the html that is portrayed within the tinymce editor and the html that is actually used on our website. The html in the tinymce editor obviously has several br tags added, making the content look much different than the other version that has no br tags.

Thanks
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7458](http://archive.tinymce.com/develop/bugtracker_view.php?id=7458) posted by [JoshW816](http://archive.tinymce.com/profile.php?name=JoshW816)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Closed_
> _**Resolution:** Wont Fix_
> _**Attached URL:** none_

**Comment by ildarius** [comment]
issue persists, if this is a config issue can someone clarify where we can modify it?
