### ISSUE TITLE
iam using tinymce 3.x version.i have created custom file browser, but iam getting an empty pop-up after selecting the image from my local pc.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2172]
Description of problem:

Steps to reproduce:
1.when clicking on image icon getting new pop-up with custom file browse button.
2.when clicking on custom-file browse button opening new pop-up which is allowing me to select an image 
3.After selecting an image an empty pop-up with title  "#advanced_dlg.image_title" is opening, thas it there is no image in the notes.

Expected result:image should appear on the notes part.

Actual result:not getting image,only blank pop-up is showing.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7461](http://archive.tinymce.com/develop/bugtracker_view.php?id=7461) posted by [swathi.k](http://archive.tinymce.com/profile.php?name=swathi.k)_
> 
> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
