### ISSUE TITLE
Feature request: format painter

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2173]
Description of problem:
Add a button like on any Office like text editor to copy a style of a word or paragraph and apply it on a selection.

Steps to reproduce:
&ltg;p class="someStyleIwishToCopy">style to copy to another paragraph&ltg;/p>
&ltg;p>Classic paragraph&ltg;/p>
&ltg;div class="aDivStyleToApplyToABunchOfParagraphs">This is another style to copy, but defined here as a div&ltg;/div>

Expected result:
See for instance,
https://support.office.com/en-za/article/Use-the-Format-Painter-4bb415a9-d4e4-42b7-b579-170adc594e40

Actual result:
No possible in 4.1.9 to my knowledge

Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7462](http://archive.tinymce.com/develop/bugtracker_view.php?id=7462) posted by [artofit](http://archive.tinymce.com/profile.php?name=artofit)_
> 
> _**Tags:** [firefox msie safari chrome format painter]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
