### ISSUE TITLE
IE8 - file_picker_callback is not called

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2174]
Description of problem: file_picker_callback is not called. Debugging Tinymce.js I can see actionCallback is built correctly but not called for IE 8, it does get called though on IE 11, so I assume there is some issue with The IE 8 event firing.

Steps to reproduce:
1.configure tinymce with imagemanager 
2.set file_picker_callback in the configuration
3.open a test page with tinymce configured as above. click on insert / edit image
4.when dialog opens. click on the browse icon next to the source text box
5.

Expected result:file_picker_callback is called

Actual result:file_picker_callback is not called

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7463](http://archive.tinymce.com/develop/bugtracker_view.php?id=7463) posted by [bouncy](http://archive.tinymce.com/profile.php?name=bouncy)_
> 
> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
