### ISSUE TITLE
Pressing delete in an empty cell, with format <p>, will break the cell

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2175]
Description of problem:

Pressing delete in an empty cell ,with format &ltg;p>, removes the &ltg;br data-mce-bogus> in the first cell and the &ltg;p> tag in the cell next to it. Selection is moved to the next cell. The cell where the delete event was fired is not selectable. The range is expanded between blocks, which is a problem in tables.

Steps to reproduce:
1.
Create a 2x1 table and use format with &ltg;p> in the cells. Add content to the cells.
2.
Delete cell content with backspace.
3.
Set the cursor in the first cell and press delete.

Expected result:
The &ltg;p> and &ltg;br data-mce-bogus> tags are kept and selection is not moved (should work like delete in an empty editor).

Actual result:
The &ltg;br data-mce-bogus> is deleted in the first cell. The &ltg;p> tag is deleted from the second ---> cells are broken.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7464](http://archive.tinymce.com/develop/bugtracker_view.php?id=7464) posted by [robinlagren](http://archive.tinymce.com/profile.php?name=robinlagren)_

> _**Tags:** [safari chrome chrome table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/sJeaab/3_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
