### ISSUE TITLE
Issue seeing code view in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2177]
Description of problem: some text overlays the code in source code view

Steps to reproduce:
1. go to http://www.tinymce.com/tryit/basic.php in chrome
2. choose source code view
3.
4.
5.

Expected result:

Actual result:

Attached is screen shot. 

Thanks. 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7466](http://archive.tinymce.com/develop/bugtracker_view.php?id=7466) posted by [tiny764de3ws](http://archive.tinymce.com/profile.php?name=tiny764de3ws)_

> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
