### ISSUE TITLE
Save plugin, save action disables save buttons in other editors

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2178]
Description of problem:
I'm using tinymce inline more for Title and for Text, just like in usage example: http://www.tinymce.com/tryit/inline.php
If i edit Title and Text, then press Save button on Title: save action work like a charm, but Text seve button becomes disabled.

Steps to reproduce:
1.Open page with more then one tinemce editors
2.Change content in more then one editor
3.Press "Save" button in one of them

Expected result:
Current editor triggers save action and disables save button

Actual result:
Current editor triggers save action and disables save button on all editors, so thers no way to inform user, thats some of the page contents wasn't saved!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7467](http://archive.tinymce.com/develop/bugtracker_view.php?id=7467) posted by [mastir](http://archive.tinymce.com/profile.php?name=mastir)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
