### ISSUE TITLE
Allow TinyMCE container to move around DOM

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2179]
When an iframe element moves in the DOM, a new document is created for it.

As far as I can tell, this is cross-browser functionality at the moment. This behavior isn't defined in HTML spec, and a brief chat in the WHATWG IRC room led to James Graham telling me this behavior should be spelled out in the HTML spec explicitly, although it is not at the moment. Full disclosure: I disagree with the current implementations, and I see no reason why a document shouldn't travel with an iframe when its moved around inside its parent document.

As TinyMCE uses an iframe for the WYSIWYG editor, it is in the middle of this browser issue.

While the spec gets sorted, there's something we can do in TinyMCE core in the meantime. If you move a TinyMCE instance around in the DOM, the document is emptied, and the editor deemed unusable. We should be able to jam state from the previous document into the new document.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7468](http://archive.tinymce.com/develop/bugtracker_view.php?id=7468) posted by [ericlewis](http://archive.tinymce.com/profile.php?name=ericlewis)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** https://jsfiddle.net/2L25rz3s/1/_

**Comment by paaljoachim** [comment]
How is this issue coming along?
As it would be nice to have a solution be found so that issue can be fixed.
Have a great day!

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
