### ISSUE TITLE
Unable to tab out of TinyMCE with noneditable

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2181]
Description of problem:
As part of our accessibility requirement, we want to be able to navigate out of TinyMCE via tab key.  However, when we have configured TinyMCE to use noneditable and have made the section non-editable, the tab key is not being recognized anymore.  End result is that the user is unable to tab out and is stuck within TinyMCE.

Steps to reproduce:
1. Put cursor into the non-editable section
2. Press Tab key

Expected result:
Expect to tab out of TinyMCE and move focus to next focusable component.

Actual result:
Focus is 

Temporary workaround:

changed the disable keypress section to exclude tab key

here's a fragment of code that was changed in the noneditable plugin.

// Disable all key presses in contentEditable=false except delete or backspace
			nonEditableParent = getNonEditableParent(startElement) || getNonEditableParent(endElement);
			if (nonEditableParent && (keyCode &ltg; 112 || keyCode > 124) && keyCode != VK.DELETE && keyCode != VK.BACKSPACE
				&& keyCode != VK.TAB) {

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7470](http://archive.tinymce.com/develop/bugtracker_view.php?id=7470) posted by [kdeleon](http://archive.tinymce.com/profile.php?name=kdeleon)_

> _**Tags:** [firefox msie safari chrome noneditable accessibility]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/YJeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
