### ISSUE TITLE
Tooltip position is broken by combination of position:fixed and transform:translate

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2182]
Description of problem: Tooltip is offset when editor is placed inside the container with transform:translate applied if parent of this container has position:fixed.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7380](http://archive.tinymce.com/develop/bugtracker_view.php?id=7380) posted by [growtofill](http://archive.tinymce.com/profile.php?name=growtofill)_

> _**Tags:** [firefox msie safari chrome tooltips]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsbin.com/habagonese/1/edit?html,output_

**Comment by jens1101** [comment]
I had to get this fixed for our application, because the incorrect positions broke the usability. See pull request #3030 
It is most likely not up to standard, but I thought I'd share my changes.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Nickproger** [comment]
I have the same issue with latest version of tinemce 
https://github.com/tinymce/tinymce/issues/3802
