### ISSUE TITLE
Inconsistent link editing in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2183]
Description of problem:
Editing a link's text via highlighting it in Chrome does not work, this approach works in other browsers.

Big issue for WordPress as this CMS does not implement 'Text to display' in link dialogue popup box so chrome users of WordPress are unable to easily edit hyperlink text.

Steps to reproduce:
1. Go here in Chrome http://www.tinymce.com/tryit/full.php
2. Highlight 'community forum' link
3. Start typing something else

Expected result:
Link remains and the text changes to whatever you type (tested in latest IE and FF)

Actual result:
The link is removed

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7381](http://archive.tinymce.com/develop/bugtracker_view.php?id=7381) posted by [latro888](http://archive.tinymce.com/profile.php?name=latro888)_
> 
> _**Tags:** [chrome chrome hyperlinks editing]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
