### ISSUE TITLE
Browser hangs after inserting of invalid html

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2186]
Description of problem:
Browser hangs after inserting of invalid html.

Steps to reproduce:
1. Go to http://www.tinymce.com/
2. In editor click Tools - Source Code
3. Insert following html:

&ltg;p>&ltg;span style="font: 13px/normal Arial, Verdana, Helvetica; color: #000000; text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; float: none; display: inline !important; white-space: normal; font-size-adjust: none; font-stre
1. Click Ok
2. Verify that browser just hangs and nothing happens.

Expected result:
Even if html is invalid, user should be able to continue working with page.

Actual result:
Browser hangs and user should restart it.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7472](http://archive.tinymce.com/develop/bugtracker_view.php?id=7472) posted by [pavel.kocherov](http://archive.tinymce.com/profile.php?name=pavel.kocherov)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/_

**Comment by fyrkant** [comment]
This should have been fixed! Closing.
