### ISSUE TITLE
Color picker dropdown appears off-screen

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2187]
Description of problem:

Discussion around the issue can be seen here: http://stackoverflow.com/questions/29493496/tinymce-color-picker-dropdown-appears-off-screen

A commenter there suggested this: "Problem has to be they use body height, but they should use scrollHeight instead. I tried to dig into scripts, but can't find the way windowManager calculates the position."
## 

Steps to reproduce: 

I'm including two TinyMCE editors on a page with one partially off-screen to start. When I select the color picker dropdown option from the toolbar on the first TinyMCE instance, the dropdown appears where it should. But if I scroll down and select the color picker dropdown in the second instance, that dropdown appears way below the editor and typically off the page. 

I've traced the problem down to setting CSS on the html, body elements.

html, body {
    width: 100%;
    height: 100%;
    overflow-x: hidden;
}

Expected result:

See attachment using the jsFiddle on Chrome

Actual result:

See attachment using the jsFiddle on FF

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7474](http://archive.tinymce.com/develop/bugtracker_view.php?id=7474) posted by [dewcandle](http://archive.tinymce.com/profile.php?name=dewcandle)_
> 
> _**Tags:** [firefox msie firefox msie9 msie10 msie11]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/nm6wtca3/_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Comment by abdessamadpas** [comment]
I still have this bug and I've searched everywhere for a solution but haven't had any luck 😔. I'm using Angular 15 with @tinymce/tinymce-angular version 7.0.0. Any ideas on how to resolve it or get closer to a solution?

**Comment by TheSpyder** [comment]
This issue related to TinyMCE 4. If you're still having the issue on TinyMCE 7, please log a new issue.
