### ISSUE TITLE
JS error thrown on removing tinyMCE holder before plugin script loads

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2188]
Description of problem:
If I remove the editor holder before script loads of tinyMCE editor, js error is thrown in function init of EDITOR

Steps to reproduce:
1.Open the link provided
2.Click on reinit twice before the editor is visible

Expected result: Init should not be called as the holder element of editor is removed.

Actual result: JS error "Uncaught TypeError: Cannot read property 'style' of null" is thrown.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7475](http://archive.tinymce.com/develop/bugtracker_view.php?id=7475) posted by [mayurvijay](http://archive.tinymce.com/profile.php?name=mayurvijay)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Ddeaab/14_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
