### ISSUE TITLE
Source Editor Blank using Windows 8

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2189]
Description of problem:
tinymce/jscripts/tiny_mce/themes/advanced/source_editor.htm shows blank screen version 3.5.11 using Windows 8.  OK using Windows 7.
Steps to reproduce:
1. Run the source editor with any content.
2. The 'HTML Source Editor' Popup will be blank.

Expected result:
Expect content in HTML Source Editor
Actual result:
Blank Screen instead.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7476](http://archive.tinymce.com/develop/bugtracker_view.php?id=7476) posted by [mikeredbike](http://archive.tinymce.com/profile.php?name=mikeredbike)_
> 
> _**Tags:** [msie chrome msie11 chrome editor blank]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
