### ISSUE TITLE
Multiple properties for forced_root_block_attrs generates js error when deleting text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2190]
Description of problem:

Steps to reproduce:
1. In the configuration of the editor set a forced_root_block and a forced_root_block_attrs with two properties (e.g. class and style)
2. Type some text in the editor
3. Select some text and press the delete button

Expected result: The selected text should be deleted without Javascript errors 

Actual result: The text is deleted but a javascript error is generated (see the console). In Chrome: Serializer.js:107 Uncaught TypeError: Cannot read property 'attributesOrder' of undefined

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7477](http://archive.tinymce.com/develop/bugtracker_view.php?id=7477) posted by [ronaldt](http://archive.tinymce.com/profile.php?name=ronaldt)_

> _**Tags:** [firefox msie safari chrome forced_root_block_attrs]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** https://jsfiddle.net/naqa67ua/13/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
