### ISSUE TITLE
"Remove link" does nothing if insertion cursor is within HTML span tags

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2191]
Description of problem:
After adding a link to the editor and surrounding the link text with span tags, the "Remove link" button no longer works if the insertion cursor is within the span tags.

Steps to reproduce:
1. Go to: http://www.tinymce.com/tryit/classic.php
2. Type in some text
3. Make a portion of the text red, or some other color
4. Highlight the text created in step 2
5. Click on the "Insert/Edit" link button and give the text a URL to link to
6. After saving, click within the colored text
7. Try to use the "Remove link" button, and notice you cannot
8. Click outside of the colored text and notice that removing the link is possible

Expected result: Instead it should be consistent, allowing the user to remove links anywhere the insertion cursor is placed within the link text

Actual result: If there are span tags within the a tags and the user places the insertion cursor within the span tags, you cannot remove links.

Example code: &ltg;p>&ltg;a href="http://google.com">This link had &ltg;span style="color: #ff99cc;">THIS TEXT&ltg;/span> colored pink using, then a link was added&ltg;/a>&ltg;/p>

Screencast: http://screencast.com/t/adYWaKbOgm9q
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7478](http://archive.tinymce.com/develop/bugtracker_view.php?id=7478) posted by [jpoulos](http://archive.tinymce.com/profile.php?name=jpoulos)_

> _**Tags:** []_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
