### ISSUE TITLE
Editor issue

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2192]
Description of problem:

there's a problem when adding css,html links references into my tiny editor.
please check attached document for more info

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7479](http://archive.tinymce.com/develop/bugtracker_view.php?id=7479) posted by [bassamAssaad](http://archive.tinymce.com/profile.php?name=bassamAssaad)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
