### ISSUE TITLE
TinyMCE Editor Bug

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2193]
Description of problem:

Steps to reproduce:
1. Just place the html code in the code part
2. On reloading the design page the image populates correctly
3. On returning back to the code editor the href applied for the table gets automatically removed
4. the same issue we could find out in http://www.tinymce.com/tryit/basic.php
5. But when we tried in fiddler.timymce.com, the URL was working fine

Expected result: the href applied to the entire table has to have all links redirected to the href provided

Actual result: Href applied to the table gets removed automatically on loading the design view

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7480](http://archive.tinymce.com/develop/bugtracker_view.php?id=7480) posted by [althafas](http://archive.tinymce.com/profile.php?name=althafas)_
> 
> _**Tags:** [firefox msie safari chrome a]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/7Keaab_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
