### ISSUE TITLE
Exception in Firefox if a file input element has focus when tinymce is initialized

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2194]
Description of problem:

In Firefox, window.getSelection().getRangeAt(0).startContainer.nodeType throws the following exception if a file input has the focus:

Error: Permission denied to access property "nodeType"

This causes tinymce.init to fail in inline mode, if a file input has the focus.

Steps to reproduce:
1. Open http://fiddle.tinymce.com/CKeaab/1 in Firefox (tested with FF 37)
2. Observe it crash

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7481](http://archive.tinymce.com/develop/bugtracker_view.php?id=7481) posted by [ChristophK](http://archive.tinymce.com/profile.php?name=ChristophK)_
> 
> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/CKeaab/1_

**Comment by ChristophKaser** [comment]
Just an update: This bug still occurs on the latest TinyMCE (4.3.8) and Firefox (45)

**Comment by PetrBorisov** [comment]
Just an update: This bug still occurs on the latest TinyMCE (4.4.1) and Firefox (53)

**Comment by tfrommen** [comment]
This also occurs for `input[type="number"]´, as [reported here](https://github.com/WordPress/gutenberg/issues/4744#issuecomment-364585690).

It's bit sad that nothing actually happened since reporting this.

**Comment by spooky** [comment]
Issue still occurs on TinyMCE 4.7.11 and FF 59

**Comment by SuperGeniusZeb** [comment]
I can also confirm this issue, both for `input[type="file"]` and `input[type="number"]`. :disappointed: (Found out about the latter while testing a Gutenberg plugin I was working on.)

**Comment by tn3rb** [comment]
also experiencing this issue using the Gutenberg `RangeControl` component (which renders an `input[type="number"]`) with Firefox 60.0.2 and 61.0 (after updating) on Windows 10 Home Version 1803.

Occasionally the `Permission denied to access property "nodeType"` error is followed by the following:
```js
TypeError: Argument 1 of Node.contains does not implement interface Node.[Learn More] wp-tinymce.php:2:54913
Dr<               http://local.wordpress.test/wp-includes/js/tinymce/wp-tinymce.php:2:54913
wm                http://local.wordpress.test/wp-includes/js/tinymce/wp-tinymce.php:2:173214
Nm/<            http://local.wordpress.test/wp-includes/js/tinymce/wp-tinymce.php:2:173285
filter               http://local.wordpress.test/wp-includes/js/tinymce/wp-tinymce.php:2:2003
Tm                  http://local.wordpress.test/wp-includes/js/tinymce/wp-tinymce.php:2:173637
store               http://local.wordpress.test/wp-includes/js/tinymce/wp-tinymce.php:2:174032
tx/o<              http://local.wordpress.test/wp-includes/js/tinymce/wp-tinymce.php:2:334794
throttle/r<      http://local.wordpress.test/wp-includes/js/tinymce/wp-tinymce.php:2:208700
```

**Comment by SuperGeniusZeb** [comment]
Should this issue be renamed to mention the fact that this happens with `input[type="number"]` or should a separate issue be opened for that?

**Comment by Pross** [comment]
Still an issue with Firefox 62.0.3 (64-bit)

**Comment by TheSpyder** [comment]
The exception is happening because the selection is on a restricted object. This is usually reserved for cross-origin access, it's weird that this is happening on certain input elements, but regardless the fix should be fairly simple:
https://github.com/tinymce/tinymce/blob/master/src/core/main/ts/api/dom/Selection.ts#L342

Using `HTMLElement.prototype.isPrototypeOf(rng.startContainer)` will be a clean way to fix it without a try/catch. I'm hoping we can start working through older issues soon, in the meantime this would be a simple PR (the `if` condition should return true in this case).

**Comment by rogerlos** [comment]
Noting this is still an issue, using firefox on windows 10.

**Comment by real-artswan** [comment]
Still have an issue. TinyMCE 4.9.2 Firefox 66

**Comment by t00** [comment]
The PR https://github.com/tinymce/tinymce/pull/4961 fixes this issue.

**Comment by TheSpyder** [comment]
This should be fixed (the PR was merged nearly two months ago).
