### ISSUE TITLE
No icon set for menu item / button of template plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2195]
No icon is set for both the menu item & toolbar button of the template plugin, while there is a template icon available. 

Version: 4.1.9

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7482](http://archive.tinymce.com/develop/bugtracker_view.php?id=7482) posted by [sDebke](http://archive.tinymce.com/profile.php?name=sDebke)_

> _**Tags:** [firefox msie safari chrome template]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
