### ISSUE TITLE
Can't switch content to not be heading.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2196]
Description of problem:

Steps to reproduce:
1. Try to change a heading to a paragraph (set as 'div' in the MCE settings.)

Expected result:
It should change from h1 to div.

Actual result:
It won't change h1 to div. Clear-formatting won't do anything either.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7483](http://archive.tinymce.com/develop/bugtracker_view.php?id=7483) posted by [Luke_sf](http://archive.tinymce.com/profile.php?name=Luke_sf)_

> _**Tags:** [firefox chrome firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/IKeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
