### ISSUE TITLE
Language files missing RGB translation

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2197]
Description of problem:

Steps to reproduce:
1. Add "textcolor colorpicker" to the plugins
2. Add "forecolor" to the toolbar
3. Set the language to one of Italian, Turkish, Portuguese, Finnish, or Chinese
4. Click on the foreground color button
5. Click on Custom...

Expected result:
R, G, B translated for the various languges
IT: RVB
TR: KYM
PT: VVA
FI: PVS
zh-CN:
R should be translated as ?
G should be translated as ?
B should be translated as ?

Actual result:
RGB for languages

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7484](http://archive.tinymce.com/develop/bugtracker_view.php?id=7484) posted by [monkeydiane](http://archive.tinymce.com/profile.php?name=monkeydiane)_
> 
> _**Tags:** [firefox msie safari chrome international translation i18n language]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
