### ISSUE TITLE
paste_data_images - Pastes Word content as an image instead of HTML

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2198]
Description of problem:
paste_data_images - Pastes Word content as an image instead of HTML

Steps to reproduce:
1. Create a table in MS Word
2. Create an editor with paste_data_images:true
3. Copy/Paste the table from MS Word to TinyMCE

Expected result:
An editable table in TinyMCE editor

Actual result:
A base64 image

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7485](http://archive.tinymce.com/develop/bugtracker_view.php?id=7485) posted by [jeroenc](http://archive.tinymce.com/profile.php?name=jeroenc)_

> _**Tags:** [chrome chrome paste_data_images paste word]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/KKeaab_

**Comment by XavierBoubert** [comment]
:+1:

**Comment by qianzhao** [comment]
:+1:

**Comment by spocke** [comment]
Fixed here:
https://github.com/tinymce/tinymce/commit/a1e4a25ea433972bbce5c2bcd913969be5b263f4
