### ISSUE TITLE
Highlighting sentence in chrome is removed after a right click

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2200]
Description of problem:
In Chrome, when highlighting a sentence and then right clicking to call the context menu, the highlighting disappears. This works in Firefox, but not in Chrome. 

Steps to reproduce:
1. In Chrome, Go to http://fiddle.tinymce.com/ or use http://www.tinymce.com/tryit/full.php
2. Highlight a sentence.
3. Right click to open the context menu.

Expected result:
Sentence remains highlighted and context menu is displayed.

Actual result:
The highlight is removed on the sentence and the context menu is displayed.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7487](http://archive.tinymce.com/develop/bugtracker_view.php?id=7487) posted by [bbruthbar](http://archive.tinymce.com/profile.php?name=bbruthbar)_

> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
