### ISSUE TITLE
Paste, Paste TExt and Pate word buttons not working with IE 11

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2202]
Description of problem:
Paste, Paste TExt and Pate word buttons not working with IE 11

Using TinyMCE as the inline editor in TeamSite content management system

Our TinyMCE version 3.1.2 does not work with IE 11. Paste, Paste Text and Paste word button do not insert the text, We cannot upgrade unless we upgrade entire teamSite system. Is there any workaround for this? Bug 6307 thread helped me with Blank HTML source view window issue. 

Thank You

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7489](http://archive.tinymce.com/develop/bugtracker_view.php?id=7489) posted by [t70xxku](http://archive.tinymce.com/profile.php?name=t70xxku)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
