### ISSUE TITLE
vertical scrollbar appears in IE11

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2203]
vertical scrollbar appears in IE11

I'm using TinyMCE 4.1.9.

Vertical scrollbar of textarea appears in only IE11.
It doesn't appears in other browsers, chrome, firefox, IE10. 
This happens in almost default settings.

&ltg;script type="text/javascript">
tinymce.init({
    selector: 'textarea'
});
&ltg;/script>
&ltg;textarea name="content" id="content">&ltg;/textarea>

I think default height of tinymce edit-area is about 172px in IE11.

If I set following 171px height, scrollbar is appeared.

tinymce.init({
    selector: 'textarea',
    height: 171
});

On the other hand, 172px height, scrollbar is not appeared.

tinymce.init({
    selector: 'textarea',
    height: 172
});

This is why autoresize_min_height of autoresize plugin is invalid in IE11.
Please try this.

tinymce.init({
    selector: 'textarea',
    plugins: 'autoresize',
    autoresize_min_height: 100,
});

Is it a spec of tinymce4?
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7490](http://archive.tinymce.com/develop/bugtracker_view.php?id=7490) posted by [roy123](http://archive.tinymce.com/profile.php?name=roy123)_

> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
