### ISSUE TITLE
"paste" plugin valid elements / style filter do not work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2204]
Description of problem:
"paste" plugin valid elements / style filter do not work on word / openoffice content

Steps to reproduce:
1. copy some text from a word file or openoffice document
2. paste into the editor
3. and check the code, there is nothing filtered

Expected result:
only create the allowed tags/styles

Actual result:
no filter, only the filter "paste_as_text" seems to work.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7491](http://archive.tinymce.com/develop/bugtracker_view.php?id=7491) posted by [des_treichelt](http://archive.tinymce.com/profile.php?name=des_treichelt)_
> 
> _**Tags:** [firefox msie safari chrome paste plugin word]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/1h3g68Lj/2/_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Comment by yhaiovyi** [comment]
It still works like that
