### ISSUE TITLE
URL conversion does not work as expected for images

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2205]
Description of problem:
The URL conversion options are not working the same for images as they are for links in my environment. I have a site using Zend framework with URLs in this format:
/indicators/index/create

I configured TinyMCE to use the following options:
convert_urls: true
relative_urls: false
remove_script_host: true

Using those options, the script host URLs are being stripped properly when I select a file from the link dialog using the file manager (I'm using Responsive File Manager), but when I select an image from the image dialog using the same file manager, it's giving different results.

For example if I have an image at http://hostname.com/content/image.gif which I select using the file manager, in the link dialog I get /content/image.gif, which is what I want. If I select that same image using the image dialog I get /indicators/index//content/image.gif which is not a valid URL.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7492](http://archive.tinymce.com/develop/bugtracker_view.php?id=7492) posted by [cdaveb](http://archive.tinymce.com/profile.php?name=cdaveb)_
> 
> _**Tags:** [firefox msie safari chrome responsivefilemanager links images]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
