### ISSUE TITLE
Right Click Conflict with third party plugin's right click

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2207]
Description of problem:

Steps to reproduce:
1. I am using TinyMCE as an Editor in our project
2. I have implemented ATD Grammar check plugin with the TinyMCE.
3. While right clicking on the Grammar Checker result, Default right click of TinyMCE is overlapping it.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7494](http://archive.tinymce.com/develop/bugtracker_view.php?id=7494) posted by [kaviaspire](http://archive.tinymce.com/profile.php?name=kaviaspire)_
> 
> _**Tags:** [msie safari chrome msie10 safari9 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
