### ISSUE TITLE
table width bug inline editing

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2210]
Description of problem:

Steps to reproduce:
1. go to http://www.tinymce.com/tryit/inline.php
2. create 2*3 table
3. drag the points to make table wider
4.
5.

Expected result:
table width visibly larger

Actual result:
sourcecode width css applied, but not visible in editor inline mode

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7497](http://archive.tinymce.com/develop/bugtracker_view.php?id=7497) posted by [bubach](http://archive.tinymce.com/profile.php?name=bubach)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
