### ISSUE TITLE
Popup 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2211]
In the popup tab once you create a link you have the setting to center / center to popup. This is the center / center of the whole screen. Can this be the center of the browser window?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7498](http://archive.tinymce.com/develop/bugtracker_view.php?id=7498) posted by [johansterc](http://archive.tinymce.com/profile.php?name=johansterc)_
> 
> _**Tags:** [firefox msie safari chrome popup]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
