### ISSUE TITLE
Blockquote

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2212]
Once you create a block quote and select the text again the dropdown is set back to paragraph instead of block quote but the styling is like a block quote. Also when you hit enter within the block quote you don't get a new paragraph instead you stay within the block quote which is annoying.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7499](http://archive.tinymce.com/develop/bugtracker_view.php?id=7499) posted by [johansterc](http://archive.tinymce.com/profile.php?name=johansterc)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
