### ISSUE TITLE
Named Anchor On Own Line Not Added to Source

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2213]
Description of problem:

If you add a named anchor on an empty line, the anchor doesn't seem to be added to the source code. Effectively stripping it if you try to save the HTML.

Steps to reproduce:
(note it can be reproduced in the demo editor on TinyMCE's site)
1. Write some text in a paragraph.
2. Hit return to start a new paragraph.
3. Add anchor 
4. View source code
5. Note the anchor isn't in the paragraph. Just a non-breaking space.

Expected result:

Anchor element is in the HTML

Actual result:

Anchor element is missing in the source HTML. Only visible in the preview. See attached image.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7500](http://archive.tinymce.com/develop/bugtracker_view.php?id=7500) posted by [eponym](http://archive.tinymce.com/profile.php?name=eponym)_
> 
> _**Tags:** [safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️].
