### ISSUE TITLE
Change event not trigger on insertContent after undoManager.clear

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2214]
Description of problem:

Steps to reproduce:
1.call "editor.undoManager.clear()"
2. append content by using "editor.insertContent(myContent)
3. editor.on('change',myCallback) we never enter in the function

Expected result:

We should listen the change event

Actual result:

The change event is never triggered in this case

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7501](http://archive.tinymce.com/develop/bugtracker_view.php?id=7501) posted by [xiu](http://archive.tinymce.com/profile.php?name=xiu)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by TrevorPT** [comment]
I just encountered this issue in TinyMCE 4.

The fix appears to be adding `self.add()` to UndoManager.clear:
```javascript
clear: function() {
    data = [];
    index = 0;
    self.typing = false;
    editor.fire('ClearUndos');
    self.add(); // <-- add this line
}
```

This way the state of the UndoManager is the same as it is after the editor is first initialized with
```javascript
// Add initial undo level when the editor is initialized
editor.on('init', function() {
    self.add();
});
```

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
