### ISSUE TITLE
When you apply strikeThrough format it does not apply correct.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2215]
Description of problem:

Steps to reproduce:
1.Use FF v.37.0.2
2.Type word
3.Change Font size
4.Apply strikethrough

Expected result: The line is in a middle of the word.

Actual result: The line is below the middle of the word.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7502](http://archive.tinymce.com/develop/bugtracker_view.php?id=7502) posted by [Nadya](http://archive.tinymce.com/profile.php?name=Nadya)_

> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
