### ISSUE TITLE
adding a link window can be moved without a drop-down list

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2217]
Description of problem:adding a link window can be moved without a drop-down list

Steps to reproduce:
1.open page with tinymce (for example http://www.tinymce.com/index.php)
2.click on the link button
3.Open the drop-down list
4.move window
5.

Expected result:
The window is moved entirely
Actual result:
The window is moved, and a drop-down list remains in place.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7504](http://archive.tinymce.com/develop/bugtracker_view.php?id=7504) posted by [Mahaton](http://archive.tinymce.com/profile.php?name=Mahaton)_

> _**Tags:** [firefox msie chrome firefox msie11 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/index.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
