### ISSUE TITLE
Text format applies to all the text in the field, and not only to selected

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2218]
Description of problem:

Steps to reproduce:
1.Enter the text in the tinymce
2.Select a part of text
3.Apply Format -> headers -> Heading 1
4.
5.

Expected result:
It applies only to the selected text
Actual result:
It applies to all text

Similarly, all of the items from the menu Format - Headlines
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7505](http://archive.tinymce.com/develop/bugtracker_view.php?id=7505) posted by [Mahaton](http://archive.tinymce.com/profile.php?name=Mahaton)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/index.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Dannybevers** [comment]
Hi, i got this issue on my environment. I'm using the inline mode, selecting 2 words in a text. Next i select header 1 in formats. After that the whole paragraph turns into a header 1 not the 2 words i selected.

Is there a fix for it, i got the latests version.
