### ISSUE TITLE
Should remove table attributes when using table_style_by_css

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2219]
Description of problem:
I think TinyMCE should remove border, cellspacing and cellpadding table attributes, when table_style_by_css is enabled. It already recognizes them, but it should also remove the old style attributes.

Steps to reproduce:
1. Open an editor with table_style_by_css = true.
2. Open the HTML source code editor.
3. Copy this source there:
&ltg;table border="5" cellspacing="3" cellpadding="4">
&ltg;tbody>
&ltg;tr>
&ltg;td>x&ltg;/td>
&ltg;td>y&ltg;/td>
&ltg;td>z&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
4. Close HTML editor, and open it again.

Actual result:
Style attributes are added,  but the old "border", "cellspacing" and "cellpadding" attributes are not removed. If the style="..." attributes are added, the old attributes are redundand.
Also, when the new attributes are used, TinyMce should do the conversion and removing the old tags, right after loading the text to be edited.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7506](http://archive.tinymce.com/develop/bugtracker_view.php?id=7506) posted by [cirix](http://archive.tinymce.com/profile.php?name=cirix)_
> 
> _**Tags:** [firefox msie safari chrome table table_style_by_css]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
