### ISSUE TITLE
Change event fires when no change occurred

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2224]
Description of problem: After a call to setContent(), even cursor movements can cause change events to be sent, which is erroneous.

Steps to reproduce:
1. Open the fiddle above.
2. Wait 1 second until it populates the editor with some content and puts focus in it.
3. Notice that no change event has yet been fired.
4. Wait as long as you like, then press the down-arrow key.
5. Notice that a change event was fired when no change occurred.

Expected result: No change event should be fired merely upon cursor movement.

Actual result: A change event is fired when all that happened was the cursor moved.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7511](http://archive.tinymce.com/develop/bugtracker_view.php?id=7511) posted by [nathancarter](http://archive.tinymce.com/profile.php?name=nathancarter)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/rj72t57w/_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
