### ISSUE TITLE
Clickable images with maybe lytebox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2226]
Hi

Is there ANYway except source code to add a link to a image so it can popup with for example lytebox?

Using justboil.me plugin to upload images.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7513](http://archive.tinymce.com/develop/bugtracker_view.php?id=7513) posted by [downup](http://archive.tinymce.com/profile.php?name=downup)_
> 
> _**Tags:** [image link popup]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
