### ISSUE TITLE
Feture Request: Native functions list or library inspector please?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2227]
This is NOT a bug, but since there's no option in the "feature request" forum page�

I understand the code is properly commented, but in order for me to know if there is an existing function for the purpose I need, it takes me HOURS! of scanning the code!

It's not that I don't understand it, but loading all that in my brain (or anyone else other than RayMan's) is probably stopping mid-level programmers like me to develop plugins which would be an awesome achievement.

If every function had tags in the leading comments, all of them could be easily scanned and a guide could be built. That way I don't have to waste hours googling a function to do something is already there. The only problem is what we think as "wrap elements in paragraphs if needed" or "cleanup" or what wordpress calls "autop", here is probably there, BUT named differently (properly for YOUR puprposes), but the only one who knows what that means is you. We, who were not involved in the development, don't know "forcing a block" or "splitting an element" are related to "wrap with paragraphs if needed". 

The comments in the code still don't help me to know what the variables mean, which adds long times tracking them all over the document, and my brain can't retain more than the last two, so basically I spend all night just finding how to use a function properly (e.g. once I understand what the script calls a "newBlock", I am already forgetting why I was even looking for it!

I can't digest the whole script functions, variable names and meaning, usage, etc in� a whole month.

An automatically built guide (scanning for "function functionName(" and the tags in the comments above could be easily deployed and would provide a powerful resource!

Thanks.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7514](http://archive.tinymce.com/develop/bugtracker_view.php?id=7514) posted by [sergiozambrano](http://archive.tinymce.com/profile.php?name=sergiozambrano)_
> 
> _**Tags:** [functions classes variables]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
