### ISSUE TITLE
Feature Request: container/selector-based settings to override general

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2228]
I'd like to choose settings that are currently global, to be applied per-container.

For example, I want paragraphs being forced or not in specific containers, so my plugins DON'T HAVE to fight against ten functions in your editor.

Other platforms (like wordpress) are depending on "views" to represent shortcodes, or other complex elements, and, considering there's no way (yet) to "lock" elements to prevent the user to break them (like little templates/forms) - i.e. contenteditable=false disables editing for the children as well -  at least it would be cool to have some way to prevent or enforce different block containers depending on the class of the parent.

E.g. A parent with a class of "box-preview", could have paragraphs enforced with a certain class, or no paragraphs at all, or different valid elements or children could exist per-container/selector, or having the code NOT verified so certain spacing or non-valid code is allowed. The code being SHOWN to the user could be NOT the one to finally be output to the masses, so it doesn't matter if it's valid or semantic, as long as the browser doesn't break.

Thanks.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7515](http://archive.tinymce.com/develop/bugtracker_view.php?id=7515) posted by [sergiozambrano](http://archive.tinymce.com/profile.php?name=sergiozambrano)_
> 
> _**Tags:** [settings block formats container based valid children]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
