### ISSUE TITLE
Line breaks lost when pasting from word

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2229]
This bug was reported by one of our clients. I have seen other issues similar to this one but none that are exactly the same thing.  We are unable to reproduce this issue.

Description of problem: When pasting from a word document, the line breaks are lost.

Steps to reproduce:
1.
2.
3.
4.
5.

Expected result: Text is copied and appears as it does in word

Actual result: Text is copied without line breaks which appear in word

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7516](http://archive.tinymce.com/develop/bugtracker_view.php?id=7516) posted by [J.Bondware](http://archive.tinymce.com/profile.php?name=J.Bondware)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
We've looked into this and believe this is a duplicate of #1398, and could come under the wider scope of #2083. Could you please take a look and let us know if you agree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
