### ISSUE TITLE
Provide an editor setting to disallow non-proportional image resizing

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2230]
In version 4 when resizing images the default is now to keep the aspect ratio, which is great.  Previously we had to hold down the shift key to keep images proportional.  Since it's now habit to hold down the shift key when resizing, since updating to version 4, we frequently find that we're mistakenly distorting images when resizing.  I've hacked the source to disable modifier keys for resizing images (since I can think of very few use cases where it would be wanted), but it would be great to be able to set this in the options.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7517](http://archive.tinymce.com/develop/bugtracker_view.php?id=7517) posted by [marshy](http://archive.tinymce.com/profile.php?name=marshy)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
