### ISSUE TITLE
Not all formatting is striped from text when pasted using Paste plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2232]
Description of problem: No options exist to stop the strike though option from being pasted using the Paste plugin

Steps to reproduce:
1. Try setting the paste plugin parameter to: paste_remove_styles: true
2. And/Or: paste_strip_class_attributes: true
3. And/Or: paste_remove_styles_if_webkit:true

Expected result:
ALL formatting should be removed when pasted

Actual result:
Some formatting is still retained: Bold, italic, bullets, numbering, indents, hyperlinks, and strike through. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7520](http://archive.tinymce.com/develop/bugtracker_view.php?id=7520) posted by [daviator00](http://archive.tinymce.com/profile.php?name=daviator00)_
> 
> _**Tags:** [firefox msie safari chrome paste plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
