### ISSUE TITLE
Image is cloned after moving it on IE8 in TinyMCE window

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2234]
Description of problem: On IE8, when user inserts an image into the TinyMCE window and then tries to hold&move it, the image is not moved. It is cloned instead, as seen on the screenshot. 

Steps to reproduce:
1. Launch IE8
2. Go to http://www.tinymce.com
3. Insert an image into the TinyMCE window
4. Try to hold & move the image inside of the window

Expected result: Image is moved to a new position inside of TinyMCE window

Actual result: Image is cloned, so instead seeing a moved image there are two identical images next to each other.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7522](http://archive.tinymce.com/develop/bugtracker_view.php?id=7522) posted by [tomasz.lakomy.stx](http://archive.tinymce.com/profile.php?name=tomasz.lakomy.stx)_

> _**Tags:** [msie msie8 ie8 internet explorer image clone]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
