### ISSUE TITLE
Tinymce not working in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2235]
Description of problem:

We use TinyMCE with MODX and over the last couple of days the editor has stopped working in chrome. The editor is locked (can't insert your mouse into the editor) and the content within it looks blank. Although can be seem when using a different browser - eg firefox!

Steps to reproduce:
1. Login to any MODX revolution CMS using the latest Chrome browser
2. Select a page to edit
3. Select a content which uses the Tiny MCE editor
4. The content box will appear blank and you will be unable to insert your mouse
5. Viewing the same content using Firefox - and Tinymce displays the content and it's editable

Expected result:
I'd expect that Tinymce will work with chrome 

Actual result:
As of the last couple of days - it's unusable - and clients are starting to report the same problem

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7523](http://archive.tinymce.com/develop/bugtracker_view.php?id=7523) posted by [loyaltymatters](http://archive.tinymce.com/profile.php?name=loyaltymatters)_

> _**Tags:** [chrome chrome chrome editor blank in text not displating]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by frogjimjaff** [comment]
Hi
This is still a problem we are having we a number of our clients..
Any news on a fix??.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by tdsbtoes** [comment]
Actually, this has become an issue just in the last week or two, in Chrome, for my users. In our case, the content is loaded from an ajax call, using setContent. Clicking the HTML button confirms the content is there, but it is not visible, nor selectable. I was using tinyMCE 2, but I just tried with the latest cloud version - same problem:
![tinymce not visible in chrome](https://cloud.githubusercontent.com/assets/10860587/23220139/056a08a8-f8ef-11e6-8ce7-803f72433c27.png)
And the image I attached shows a freshly initialized editor (version 4), that I was typing into, but nothing is visible in the editor. However, I think this is more a Chrome problem than a tinyMCE one, as Firefox works great. But I'm surprised the tinymce team has never seen this....

**Comment by blackcathikari** [comment]
@tdsbtoes Thank you for the screenshot. Could you tell me more about the environment you're using TinyMCE within - e.g. are you using it with MODX as mentioned above? - and how you've got TinyMCE set up - e.g. are you using Templates, as also mentioned above? I'm thinking we haven't seen it because we haven't been able to reproduce the environment properly. This sounds like it's perhaps an integration issue.

**Comment by tdsbtoes** [comment]
Hi,

Thanks for the reply, sorry for the delay!

I jumped on the wrong forum, I think, as I am not using MODX, nor templates, as far as I remember. It is an old version 2 installation that I host.

Upon searching, I'm found many similar issues of content not showing up in an iframe (in Chrome), going back to at least 2015. But my implementation was working great until the last few weeks. Once the editor loads in, the iframe with the invisible content is 3 iframes deep. Could be Chrome thinks that's too weird.

And I can confirm this issue exists on PC and Mac, and not just my machines, but dozens of coworkers.

The only thing that's changed is Chrome.

I did install Tinymce 4, and got the same result. So I think this is a Chrome rendering problem/limitation.

If you can shed any light on this, I would be eternally grateful!

Chris Metropolis
Toronto Urban Studies Centre
Toronto Outdoor Education Schools
O - 416-393-0826
C - 416-995-3087
________________________________

**Comment by blackcathikari** [comment]
From the Chrome dev blog, it looks like there was a major update on Jan 25 that contains a lot of iframe changes. Would that be about the right date? Rollout across your users could have taken a few days. 

I made a test page (unfortunately not one I can link to) with TinyMCE inside nested iframes and had no trouble with it in any browser so I'm afraid I still can't replicate the problem. If there's any messages in the console we might be able to figure something out, but unfortunately it sounds like it's a problem specific to your implementation - maybe interaction between TinyMCE and other scripts in your page?

If you do figure this out, I'd be interested in hearing how you fix it. Sorry I can't help any further.

**Comment by tdsbtoes** [comment]
Thanks so much for trying to recreate the issue. The timeframe is about right, but I think it might have started a bit earlier. Can’t remember!

And no, I see no error messages in Chrome; I mean, the content is getting loaded, I can see it in the source and in the request to the page. Opening the tinymce html viewer shows the content. It just doesn’t get rendered, nor is the text selectable. While I haven’t changed my JS in awhile, it could be something interfering.

If you have the time, I can give you a login that opens a test database, and you can (hopefully) see it in action.

Many thanks!
--
Chris Metropolis
Toronto Urban Studies Centre
Toronto Outdoor Education Schools
O - 416-393-0826
C - 416-995-3087

**Comment by tdsbtoes** [comment]
Another note: I have a similar tinymce setup in another part of my CMS that ends up being 2 iframes deep, and it works fine. So there is certainly something about nesting iframes 3 deep.

Guess I’ll have to change the layout to use one less iframe…..
--
Chris Metropolis
Toronto Urban Studies Centre
Toronto Outdoor Education Schools
O - 416-393-0826
C - 416-995-3087

**Comment by SravaniPothala** [comment]
We have faced the same issue with tiny mce editor in chrome. The issue is coming due to spaces between html tags.After removing the spaces between tags, it' s working properly.
