### ISSUE TITLE
Allowing access to togglePlainTextPaste in paste plugin.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2236]
Is there anyway the togglePlainTextPaste could be exposed you it can be accesed via the paste plugin? Is there anything that could serve as an alternative? In version 3.5.6 there was a mcePasteText command that is no longer in use could something like that be brought back so that we can access the plain text paste?

Thanks

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7524](http://archive.tinymce.com/develop/bugtracker_view.php?id=7524) posted by [lawrencew](http://archive.tinymce.com/profile.php?name=lawrencew)_

> _**Tags:** [firefox msie safari chrome paste pasteplugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
