### ISSUE TITLE
Paste with bullet/ordered lists results in overlap 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2237]
Description of problem:
When pasting with bullet or ordered lists, the bullet/number is overlapped with the rest of the point. In chrome and firefox a style of 'text-indent: -.25in" and data-mce-style="text-indent: -.25in;" is causing this. Not sure where that is being appended from.

Expected result:
No overlap of bullets/numbers and text

Actual result:
Overlap
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7525](http://archive.tinymce.com/develop/bugtracker_view.php?id=7525) posted by [lawrencew](http://archive.tinymce.com/profile.php?name=lawrencew)_

> _**Tags:** [firefox chrome paste lists]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by emanlangit** [comment]
I am experiencing the same issue. Is there an estimate or time frame for this item's disposition?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
