### ISSUE TITLE
Inline tinyMCE strips out form tag

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2238]
Description of problem: If inline option is set to true, tinyMCE strips out form tag.

Steps to reproduce:
1. Go to http://www.tinymce.com/tryit/full.php, in editors source code view paste " &ltg;form>&ltg;input name="firstname" type="text" />&ltg;/form> ".
2. Close source code view and open it again.
3. Form tag is present.
4. Go to http://www.tinymce.com/tryit/inline.php, in editors source code view paste " &ltg;form>&ltg;input name="firstname" type="text" />&ltg;/form> ".  
5. Close source code view and open it again.
6. Form tag is stripped out.

Expected result:
Form tag must not be stripped out in both cases.

Actual result:
Form tag is stripped out if tinyMCE is in inline mode.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7526](http://archive.tinymce.com/develop/bugtracker_view.php?id=7526) posted by [juris.vaiders](http://archive.tinymce.com/profile.php?name=juris.vaiders)_

> _**Tags:** [firefox msie safari chrome form inline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
