### ISSUE TITLE
Ability to add custom multiple select

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2239]
Should be object like `listbox` with multiple select abilities. Thanks.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7527](http://archive.tinymce.com/develop/bugtracker_view.php?id=7527) posted by [Helen_Laktionova](http://archive.tinymce.com/profile.php?name=Helen_Laktionova)_
> 
> _**Tags:** [select multiple]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
