### ISSUE TITLE
There is no onchange event for removing all content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2240]
Description of problem:
No onchange if you type something and then press Ctrl+A, Del (or Backspace)
Steps to reproduce:
1.Type some text
2.Press Ctrl+A to select all content
3.Press Del (or Backspace) to delete selected content

Expected result:
Onchange and/or input event fired
Actual result:
No events fired
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7528](http://archive.tinymce.com/develop/bugtracker_view.php?id=7528) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_

> _**Tags:** [firefox msie safari chrome onchnage events]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/GNeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
