### ISSUE TITLE
Wrong keydown processing 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2241]
Description of problem:
Browser clear cache hotkey is broken in some cases

Steps to reproduce:
1.Press Ctrl+A to select all content
2.Press Del (or Backspace) to delete all content
3.Press Ctrl+Shift+Del to trigger browser clear cache

Expected result:
Browser will provide UI for clearing cache
Actual result:
Browser behaviour is broken by tinymce

Extra: 
If there is some text inside tinymce Ctrl+Shift+Del will probably work but not in Chrome. In Chrome it will act as Ctrl+Del (delete word) and will ignore pressed Shift.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7529](http://archive.tinymce.com/develop/bugtracker_view.php?id=7529) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_

> _**Tags:** [firefox msie safari chrome keydown]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/GNeaab/2_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
