### ISSUE TITLE
tinymce fails to load in IE11 when script name is renamed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2242]
Description of problem: Tinymce fails to load plugins, langs and themes in IE11 when script name is different than 'tinymce.min.js'. In script tinymce looks for base URL and checks for scripts which starts with 'tinymce'. If it does not find any it will use property document.currentScript which is undefined in IE11. That's leads to wrong base url for plugins and prevents tinymce from loading.

Steps to reproduce:
1. Rename script to eg. 'tiny_mce.min.js'
2. Open IE11
3. Check console for load errors.

Expected result: Tinymce loads.

Actual result: Blank editor window.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7530](http://archive.tinymce.com/develop/bugtracker_view.php?id=7530) posted by [Lesmian](http://archive.tinymce.com/profile.php?name=Lesmian)_
> 
> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by cscleison** [comment]
Workaround:
- bundle all js with 'grunt bundle' as described [here](https://github.com/tinymce/tinymce#build-tasks)
- set a init prop 'skin_url', for example:

`tinymce.init({ skin_url: window.location.origin + '/css/tinymce' });`

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Comment by minusdavid** [comment]
Think I just got bitten by this...
