### ISSUE TITLE
Selection handles incorrect when focus is moved to another inline editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2244]
Description of problem: if you have multiple inline editors and you change focus from one to another while an object (such as an image) is selected, the selection handles do not always move to the active editor.

Steps to reproduce:
1. create multiple inline editors (see fiddle) containing objects such as images
2. click to select image in one editor
3. click to select image in the other editor
4. click to image in first editor

Expected result: selection handles on image should be in the active editor instance.

Actual result: after step 3 or 4 the selection handles remain behind in the editor instance which lost focus. If you use the handles in the inactive editor to resize the image, it will resize the one in the active editor.

This also happens in nw.js v0.12.0-win-ia32
Thanks.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7532](http://archive.tinymce.com/develop/bugtracker_view.php?id=7532) posted by [TrevorPT](http://archive.tinymce.com/profile.php?name=TrevorPT)_

> _**Tags:** [chrome chrome selection handles inline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/WNeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
