### ISSUE TITLE
Selection handles not repositioned if object resized by container

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2245]
Description of problem: when objects (such as images) are tied to their container size (eg. by using "max-width: 100%" or "width: 100%"), if the container holding an inline editor is resized while the object is selected, the selection handles are not repositioned.

Steps to reproduce:
1. create multiple inline editors (see fiddle) in divs sized to their parent (eg. width: 45%)
2. add images to divs, sized through css with either max-width: 100% or width: 100%
3. select an image
4. resize the browser window; this will resize the divs which will resize the child images

Expected result: selection handles on selected object (image) should be repositioned to the new image dimensions.

Actual result: selection handles remain in their previous positions.

Thanks.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7533](http://archive.tinymce.com/develop/bugtracker_view.php?id=7533) posted by [TrevorPT](http://archive.tinymce.com/profile.php?name=TrevorPT)_

> _**Tags:** [chrome chrome selection handles resizing]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/WNeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
