### ISSUE TITLE
"Add link" button is active when caret is positioned outside of the link element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2246]
Description of problem:

When a new hyperlink is added to the end of the text (&ltg;a> tag is the last element in editor's body), state of the "Add link" button would incorrectly change to active. If I click the button now, the dialog fields will be empty.

Steps to reproduce:
1. Make sure the editor body is empty.
2. Click "Add link" button in the toolbar. Fill out the fields and click OK to add the link.
3. "Add link" button has now changed its state to "active" as if the caret was positioned inside the link (while it's actually outside).
4. Click the button again to reopen the dialog.

Expected result: Fields in the dialog are not empty

Actual result: Fields in the dialog are empty

The proper behaviour would actually be to not highlight the button when the caret is positioned outside of the link.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7534](http://archive.tinymce.com/develop/bugtracker_view.php?id=7534) posted by [alan](http://archive.tinymce.com/profile.php?name=alan)_

> _**Tags:** [safari chrome safari8 chrome link]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
