### ISSUE TITLE
The "full featured" example loses formatting of pasted content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2247]
Description of problem:

Steps to reproduce:
1. Go to http://www.tinymce.com/tryit/full.php
2. Paste the contents of this Google Doc - https://docs.google.com/document/d/11HIrMPLWsxYjcBlMUIqrE4ELiQWpyYk-mj5nbhjOLrg/edit#
3. Note how the image is lost.
4. Paste the first code block from http://addyosmani.com/resources/essentialjsdesignpatterns/book/#summarytabledesignpatterns
5. Note how the formatting is lost.

The Formatting example (http://www.tinymce.com/tryit/custom_formats.php) works well, but new users who evaluate TinyMCE and go to the "Full" example may believe that it doesn't support pasting properly.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7535](http://archive.tinymce.com/develop/bugtracker_view.php?id=7535) posted by [dandv](http://archive.tinymce.com/profile.php?name=dandv)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
