### ISSUE TITLE
I can't chose chinese word on tinymce when I enable wordcount plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2250]
Description of problem:
When using the Windows IME input mechanism to type in Chinese text into a TinyMCE editor,
My client uses the MS Pinyin (http://www.pinyinjoe.com/windows-7/win7-pinyin-setup-p2-fanti.htm) to input the data in the editor. 
For example, 
if I start typing Chinese text at the beginning of an existing paragraph, 
press Down Arrow, the Pinyin window will be poped up automatically so that I can choose word from it, 
but this can't work on Windows 7 using Internet Explorer When I enable word count plugin to TinyMCE.

Steps to reproduce:
1. enable word count plugin to TinyMCE.
2. enable the Chinese IME and type the word "ji3" in the TinyMCE editor.
3. Don't exit the IME mode - just press Down Arrow 
4. the Pinyin window can't be poped up

Expected result:
the Pinyin window will be poped up automatically when I type chinese word "ji3" and press  Down Arrow .

Actual result:
the Pinyin window can't poped up automatically when I type chinese word "ji3" and press  Down Arrow .

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7538](http://archive.tinymce.com/develop/bugtracker_view.php?id=7538) posted by [loln](http://archive.tinymce.com/profile.php?name=loln)_

> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
