### ISSUE TITLE
Bullet/numbering with indent

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2251]
I am using 3.5 version. 
Description of problem: Text is rearranging when we apply numbering->indent->bold(or apply any formats).

Steps to reproduce:
1.write three word in three lines and apply numbering for all.
2.Apply indent on second word(i.e on second line.)
3. And select all and apply bold, then the third line text move to first.

Expected result: Bold should apply with out rearranging the text.

Actual result: The third line is moving to first line.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7539](http://archive.tinymce.com/develop/bugtracker_view.php?id=7539) posted by [anilkalal](http://archive.tinymce.com/profile.php?name=anilkalal)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
