### ISSUE TITLE
Entering a uppercase weblink does not add "http://"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2252]
Description of problem:
Entering a web address (e.g. www.something.com) in uppercase (WWW...) does not include "http://" in the href of the anchor tag.

Steps to reproduce:
Enter two links one in lowercase, one in in all uppercase:
www.test.com
WWW.TEST.COM

Actual result:
&ltg;p>&ltg;a href="http://www.test.com">www.test.com&ltg;/a>&ltg;/p>
&ltg;p>&ltg;a href="WWW.TEST.COM">WWW.TEST.COM&ltg;/a>&ltg;/p>

The uppsercase WWW.TEST.COM did not receive a "http://" prefix.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7540](http://archive.tinymce.com/develop/bugtracker_view.php?id=7540) posted by [mcain66](http://archive.tinymce.com/profile.php?name=mcain66)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
