### ISSUE TITLE
Internet Explorer not renderring the HTML area

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2258]
Description of problem:
Attached is how the HTML area shows up for one of our users (homepage of this site). This is only happening to this one user when they're using IE so far out of hundreds of others who've used it just fine in IE 10 so it's gotta be something on this users machine but I've re-installed the browser, I've cleared all chache etc. , and I've even uninstalled and installed java in the off chance that had anything to do with it. No dice. 
Note that if this same user uses chrome, it works just fine. Is there some strange checkbox in IE that forces it to use HTML 5 for example? Just throwing stuff out...

Steps to reproduce:
I haven't been able to re-create the issue in any other environment, I'm hoping someone can give me a little direction that may have seen this behavior before. Very likely could be a browser setting, cross site scripting, something...

Expected result:
The HTML editor should appear with menu options and the tool bar.

Actual result:
The text box appears as plain text, there is no HTML bar available.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7546](http://archive.tinymce.com/develop/bugtracker_view.php?id=7546) posted by [blackburn.171](http://archive.tinymce.com/profile.php?name=blackburn.171)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
