### ISSUE TITLE
Code for buttons is being removed after saving

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2262]
Description of problem: I am using JA Kranos template on my site www.finnislam.no

When I add this code:

&ltg;p style="text-align: justify;">&ltg;a class="ja-typo-btn btn-red ja-typo-btn-big btn-big-red" href="laere/hvordan-forstar-vi-gud">&ltg;span>Neste steg: Hvordan forst�r vi Gud?&ltg;/span>&ltg;/a>&ltg;/p>

TinyMCE turns it into this code:

&ltg;p style="text-align: justify;">&ltg;a class="ja-typo-btn btn-red ja-typo-btn-big btn-big-red" href="laere/hvordan-forstar-vi-gud">Neste steg: Hvordan forst�r vi Gud?&ltg;/a>&ltg;/p>

The &ltg;span> and &ltg;/span> is removed. How can I gix this?

Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7550](http://archive.tinymce.com/develop/bugtracker_view.php?id=7550) posted by [fahadqu](http://archive.tinymce.com/profile.php?name=fahadqu)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by spocke** [comment]
This is a config issue. So closing.
