### ISSUE TITLE
Cannot copy links or part of links

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2264]
Description of problem:

When I select a link and press CMD+C, nothing is actually copied...

works with normal text...

Example: http://cl.ly/image/3F1d0A0F253T

(TEST was on clipboard and then I selected the link and pressed CMD+C and TEST was still the last thing on clipboard)

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7552](http://archive.tinymce.com/develop/bugtracker_view.php?id=7552) posted by [davidhq](http://archive.tinymce.com/profile.php?name=davidhq)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
