### ISSUE TITLE
Inline editing example - Copy Paste issue

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2265]
Description of problem:
when you select the text inside of an inline editing box copy & paste the text into the same field the html tags will also be copied. 

Steps to reproduce:
1.got to http://www.tinymce.com/tryit/inline.php
2. click into the "Editable header" field
3. Select all, copy & paste (ctrl+a - crtl+c - crtl+v)
4. the result ist the styled h1 in h1 in h1 etc. 

Expected result:

If i do the steps i want only to copy and paste the text without the tags.

&ltg;h1 contenteditable="true" class="editable mce-content-body mce-edit-focus" id="mce_0" style="position: relative;" spellcheck="false">
Editable header
Editable header
Editable header
&ltg;h1>

Actual result:
&ltg;h1 contenteditable="true" class="editable mce-content-body mce-edit-focus" id="mce_0" style="position: relative;" spellcheck="false">&ltg;h1 contenteditable="true" class="editable mce-content-body mce-edit-focus" id="mce_0" style="position: relative;" spellcheck="false">Editable header&ltg;h1 contenteditable="true" class="editable mce-content-body mce-edit-focus" id="mce_0" style="position: relative;" spellcheck="false">Editable header&ltg;h1 contenteditable="true" class="editable mce-content-body mce-edit-focus" id="mce_0" style="position: relative;" spellcheck="false">Editable header&ltg;/h1>&ltg;/h1>&ltg;/h1>&ltg;/h1>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7553](http://archive.tinymce.com/develop/bugtracker_view.php?id=7553) posted by [cubasepp](http://archive.tinymce.com/profile.php?name=cubasepp)_

> _**Tags:** [firefox copy paste inline header duplicate]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/inline.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
