### ISSUE TITLE
Backspace deletes multiple empty paragraphs at once in the beginning of the document

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2267]
Description of problem: #7444 is here again in Chrome, but this time it shows only at the beginning of the content.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7555](http://archive.tinymce.com/develop/bugtracker_view.php?id=7555) posted by [thorn](http://archive.tinymce.com/profile.php?name=thorn)_

> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/develop/bugtracker_view.php?id=7444_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
