### ISSUE TITLE
Table CSS "class" and "id" property edit 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2269]
Description of problem: I can't edit CSS class and ID properties of the &ltg;table> elements via TinyMCE table property editor plugin by default. Is there any way to resolve this problem?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7558](http://archive.tinymce.com/develop/bugtracker_view.php?id=7558) posted by [netdjw](http://archive.tinymce.com/profile.php?name=netdjw)_
> 
> _**Tags:** [firefox msie safari chrome table css class]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
