### ISSUE TITLE
Inline editor enter key copies styles outside the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2270]
Description of problem:

Steps to reproduce:
1. Open the attached fiddle
2. Position the cursor at the end of the line
3. Press the enter key
4. Observe how the red border from outside the editor is copied into the editor

Expected result:
The red broder from outside the editor should not have any influence on the contents of the editor

Actual result:
The red border is copied into the editor

I will provide a pull request that fixes this bug.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7559](http://archive.tinymce.com/develop/bugtracker_view.php?id=7559) posted by [ChristophK](http://archive.tinymce.com/profile.php?name=ChristophK)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/QPeaab_

**Comment by ChristophKaser** [comment]
What is the status of this bug? Is there an issue with my pull request?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
