### ISSUE TITLE
protect setting: comment not removed on save for inline matches

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2271]
Description of problem:
I use the protect setting (http://www.tinymce.com/wiki.php/Configuration:protect) to prevent inline code being changed or removed by tinymce. 

This works perfectly for blocks or complete lines of code, but for example a match inside an attribute of an HTML tag that is displayed in the editor will be passed back to the textarea including the protecting comment. My current workaround is to replace and decode the remaining protection in my backend method.

Steps to reproduce:
1. have a string like 
&ltg;pattern>
&ltg;a href="&ltg;pattern>">something&ltg;/a>"
in a textarea
1. init tinymce on that text area with
   protect: [/&ltg;pattern>/g]
2. editor content will be like
   &ltg;!--mce:protected %3Cpattern%3E-->
   &ltg;a href="&lt;!--mce:protected %3Cpattern%3E--&gt;" data-mce-href="&ltg;!--mce:protected %3Cpattern%3E-->">something&ltg;/a>
3. trigger save on tinymce

Expected result:
textarea content
&ltg;pattern>
&ltg;a href="&ltg;pattern>">something&ltg;/a>

Actual result:
textarea content
&ltg;pattern>
&ltg;a href="&ltg;!--mce:protected %3Cpattern%3E-->">something&ltg;/a>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7557](http://archive.tinymce.com/develop/bugtracker_view.php?id=7557) posted by [PhiBo](http://archive.tinymce.com/profile.php?name=PhiBo)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by alejandromagnorsky** [comment]
Any update on this? I'm having the exact same issue.

**Comment by noc2spam** [comment]
Any update on this? The issue still seems to persist.

**Comment by imxike** [comment]
i have same problem on version 4

**Comment by IlCingalese** [comment]
i had same problem and resolve with this code passed in options
`init_instance_callback: function (editor) {
        editor.on('PostProcess', function (e) {
            e.content = e.content.replace(/()/g, function(text, p1, p2, p3){
              return decodeURIComponent(p2);
            })
            e.content = e.content.replace(/(&lt;!--mce:protected)(.*)(--&gt;)/g, function(text, p1, p2, p3){
              return decodeURIComponent(p2);
            })
          });
    },`

**Comment by IlCingalese** [comment]
sry i made some test and suggest don't use the "preprocess" event because tinymce  make some internal check with <a> tags, but use "postprocess" replacing "e.node.innerHTML" with "e.content"
like this:

`init_instance_callback: function (editor) {
        editor.on('PostProcess', function (e) {
            console.log(e.content);

            e.content = e.content.replace(/()/gm, function(text, p1, p2, p3){
                if (unescape) {
                    //console.log(text);
                    return unescape(p2);
                } else {
                    //console.log("ssss");
                    return decodeURIComponent(p2);
                }
            });

            e.content = e.content.replace(/(&lt;!--mce:protected\s)(.*?)(--&gt;)/gm, function(text, p1, p2, p3){
                if (unescape) {
                    return unescape(p2);
                } else {
                    return decodeURIComponent(p2);
                }
            });
            console.log(e.content);
        });

    },`

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
