### ISSUE TITLE
Internal Server Error when changing email address in forum software

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2272]
Description of problem:

Steps to reproduce:
1. login to TinyMCE forum
2. goto profile page
3. click on "Change your e-mail address"
4. enter new email address and password
5. click on submit
6. check email and open email with subject "Change e-mail address requested"
7. click on link to confirm email address change

Expected result: email address successfully changes

Actual result: no change of email address, error shown is: "The page cannot be displayed because an internal server error has occurred."

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7560](http://archive.tinymce.com/develop/bugtracker_view.php?id=7560) posted by [McPringle](http://archive.tinymce.com/profile.php?name=McPringle)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/forum/profile.php?action=change_email&id=xxxxxx&key=xxxxxx_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
