### ISSUE TITLE
Colorless table border in tinymce

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2273]
When I copy tables from Word to tinymce editors under IE 8 and IE 11, the table border color in black could be shown in IE 11 but the table border is colorless in IE 8. When I save the record in IE 8 and IE 11, I find the following difference between IE 8 and IE11:

IE 8:
&ltg;table style="margin: auto auto auto 0.25pt; width: 56.82%; border-collapse: collapse;" width="56%">

IE 11:
&ltg;table style="margin: auto auto auto 0.25pt; border: currentColor; width: 56.82%; border-collapse: collapse;" width="56%">

The tiny MCE inititation code is provided as below:

tinyMCE.init({

```
    doctype : '&ltg;!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">',
    selector: "&ltg;%=tinymceElementsStr%>",
    theme: "modern",
    plugins: [
        "table save emoticons paste noneditable searchreplace textcolor colorpicker"
    ],
    language : "en",
    content_css : "&ltg;% out.write(padding + "stylesheet/word.css"); %>",
    add_unload_trigger: false,
    autosave_ask_before_unload: false,
    toolbar1 : "bold italic underline strikethrough alignleft aligncenter alignright | outdent indent | forecolor backcolor fontselect fontsizeselect bullist numlist undo redo",
    menubar: false,
    toolbar_items_size: 'small',
    resize: false,
    statusbar: false,
    relative_urls : false,
    remove_script_host : false,
    element_format : "html",
    //entity_encoding : "raw",
    paste_retain_style_properties: "all",
    keep_styles: true,
    schema: "html4"


});
```

Compared to IE 8, in IE 11, "border: currentColor" is appended in the table tag.

Which configuration files should I revise so that the border color should be shown in black when copying tables from Word to tinymce editors using tinymce editor in IE 8? Thanks you.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7561](http://archive.tinymce.com/develop/bugtracker_view.php?id=7561) posted by [inhse.ogcio](http://archive.tinymce.com/profile.php?name=inhse.ogcio)_
> 
> _**Tags:** [msie msie8 msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
