### ISSUE TITLE
Problem Working with JQuery UI Sortable

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2277]
Working with Jquery UI Sortable.  But when the textarea is inside the sortable, something strange happens:
1. The toolbar seems not display correctly
2. After drag and drop, the text inside the textarea is lost
3. After drag and drop, I can no longer input text in the textarea

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7565](http://archive.tinymce.com/develop/bugtracker_view.php?id=7565) posted by [terence2003](http://archive.tinymce.com/profile.php?name=terence2003)_
> 
> _**Tags:** [chrome chrome jquery ui sortable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/YPeaab_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
