### ISSUE TITLE
paste plugin doesn't use paste_block_drop setting

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2278]
Description of problem:
paste_block_drop setting is not used in plugin paste

Steps to reproduce:
1. set paste_block_drop=true in tinymce setup
2.drag & drop an image on editor
3.the image is dropped
4.
5.

Expected result:
the image should not be dropped

Actual result:
by looking in paste/plugin.js, on line 1571, there is :
if (editor.paste_block_drop {

may be it should be 
if (editor.settings.paste_block_drop {

as there is no 'editor.paste_block_drop' value...
I've tried it : it looks like it works.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7567](http://archive.tinymce.com/develop/bugtracker_view.php?id=7567) posted by [oliviern](http://archive.tinymce.com/profile.php?name=oliviern)_

> _**Tags:** [firefox msie safari chrome paste plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by spocke** [comment]
Fixed this by merging the pull request. Thanks.
