### ISSUE TITLE
tinymce code is looking for DOM property on activeEditor instead of top level tinymce object

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2280]
Description of problem:

I have a windows store app targeted at windows 8.0 that contains a webview (which uses IE 10 in document mode). Into this webview a local html file is loaded along with the tinymce configuration file, tinymce.min and jquery.tinymce.min. 

For some reason, the tinymce code is looking for parser and DOM properties respectively on the activeEditor instead of the top level tinymce object.

When attempting to set the content of the editor using this:
tinymce.activeEditor.setContent("test");

I get this:
Unable to get property 'parse' of undefined or null reference	

The error is occurring in this chunk of code in the setContent method:
if (args.format !== 'raw') {
     content = new Serializer({}, self.schema).serialize(
          self.parser.parse(content, {isRootContent: true})
      );
}

If I modify my original call to be this:
tinymce.activeEditor.setContent("test", {format:'raw'});

Then on this chunk of code in the setContent method:
self.dom.setHTML(body, args.content);

I get this:
Unable to get property 'setHTML' of undefined or null reference	

For some reason, the tinymce code is looking for parser and DOM properties respectively on the activeEditor instead of the top level tinymce object.

Everything appears to work fine in an actual IE10 instance.

Steps to reproduce:
1. See above

Expected result:
A call to the setContent method will set the content of the active editor.

Actual result:
A call to the setContent method does not set the content of the active editor and throws an exception

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7568](http://archive.tinymce.com/develop/bugtracker_view.php?id=7568) posted by [alan1738](http://archive.tinymce.com/profile.php?name=alan1738)_

> _**Tags:** [msie msie10 windows store app webview 80 jquery modal]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
