### ISSUE TITLE
Using formats and style_formats I'm unable to wrap elements in a <div> if the editor is inline using <div>

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2283]
Description of problem: using formats and style_formats I'm unable to wrap elements in a &ltg;div> if the editor is inline using &ltg;div>.  For example, I want to wrap an image and some &ltg;p> elements in a &ltg;div> so the text will flow around the image (which is using float) within the div.

It works if the editor is not inline (remove 'inline: true' from the jsfiddle).

Tested with 4.1.10 dev download in nw.js, and with edge (4.2.0) in fiddle under Chrome.

Steps to reproduce:

1. Have some HTML like
    &ltg;p>Line 1&ltg;/p>
    &ltg;p>Line 2&ltg;/p>
    &ltg;p>Line 3&ltg;/p>

2. Intialize TinyMCE with:
selector: 'div#id',
inline: true,
formats: { div_wrapper: { block: 'div', wrapper: 1 } },
style_formats_merge: true,
style_formats: [ { title: "Wrappers", items: [ { title: 'Div', format: 'div_wrapper' } ] } ]

3. Select all the HTML elements.
4. Use "Formats > Wrappers > Div" from the toolbar.

Expected result:
    &ltg;div>
        &ltg;p>Line 1&ltg;/p>
        &ltg;p>Line 2&ltg;/p>
        &ltg;p>Line 3&ltg;/p>
    &ltg;/div>
    
Actual result:
    &ltg;p>Line 1&ltg;/p>
    &ltg;p>Line 2&ltg;/p>
    &ltg;p>Line 3&ltg;/p>

-- 

I traced it to function applyRngStyle, inside the
    each(newWrappers, function(node) {

and the block following the comment
    // Remove child if direct parent is of same type

The first matchNode (outside of where format.merge_with_parents is checked) is removing the &ltg;div> from the new wrapper because the parent (the inline editor) is a &ltg;div>.  Not sure what to do here, maybe check if inline and if node.parentNode is the editor div?

Thanks.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7571](http://archive.tinymce.com/develop/bugtracker_view.php?id=7571) posted by [TrevorPT](http://archive.tinymce.com/profile.php?name=TrevorPT)_

> _**Tags:** [chrome chrome formats style_formats]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/eQeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
