### ISSUE TITLE
Spellchecker - Remove whitespace before wrong word.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2286]
Description of problem:
Remove whitespace in the first row of 'li' between correct word and wrong word

Steps to reproduce:
1.Added this to source code:
&ltg;ul>
&ltg;li>First wwwwrongg wrong
&ltg;ul>
&ltg;li>abc abc abc&ltg;/li>
&ltg;/ul>
&ltg;/li>
&ltg;li>abc abc abc&ltg;/li>
&ltg;/ul>
2.Enable spellchecker
3.Show sourcecode

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7574](http://archive.tinymce.com/develop/bugtracker_view.php?id=7574) posted by [Kitzi16](http://archive.tinymce.com/profile.php?name=Kitzi16)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
