### ISSUE TITLE
Buttons don't display font image with IE and disabled font loading

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2287]
Description of problem:
No way to use tinymce in IE when unable to enable loading of fonts for the font images. I work for the government which uses IE as the standard. Depending on the agency, the control we have of IE via Internet Options varies, but none of us guaranteed can enable loading of fonts. In looking at the tinymce code, the amount of work I would have to do to use an image instead of the font is quite a lot then I would be locked into my custom version.

Steps to reproduce:
1. In IE (any version) disable loading fonts. (I cannot give the steps to do this as I cannot access this at all in my IE)
2. Open even the tinymce home page with the sample.

Expected result:
You see the menu buttons with images like a printer to print or an eye to preview.

Actual result:
Blank buttons or with an empty box on the button because the font image cannot render.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7575](http://archive.tinymce.com/develop/bugtracker_view.php?id=7575) posted by [ibkliewer](http://archive.tinymce.com/profile.php?name=ibkliewer)_
> 
> _**Tags:** [msie msie7 msie8 msie9 msie10 msie11 ie and disabled font loading tinymce 4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
