### ISSUE TITLE
Unknown icon appears using IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2288]
Description of problem: Sorry this is old version i guess Version 3.5.8
This problem came from post back but now i can't reproduce it again.

Steps to reproduce:
1.It was came from post back then unknown icons appears
2.
3.
4.
5.

Expected result:

Actual result: http://prntscr.com/7mypmj

Do you guys have any idea where it come from and how to reproduce it again the two red mark in image above.
Thanks in advance.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7576](http://archive.tinymce.com/develop/bugtracker_view.php?id=7576) posted by [suangetss](http://archive.tinymce.com/profile.php?name=suangetss)_

> _**Tags:** [msie msie8 msie9 msie10 msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
