### ISSUE TITLE
Heading select box expand onclick element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2289]
Description of problem:

Steps to reproduce:
1. Go to http://www.tinymce.com/tryit/classic.php
2. Click on 'Welcome to the TinyMCE editor demo!'
3. Now click on a paragraph
4. Click again on the header tag
5. The header select box expands to the right because the text Paragraph is wider then Heading 1

With other languages like dutch it jumps way more

Solution

Make the select boxes at wide as the longest text

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7577](http://archive.tinymce.com/develop/bugtracker_view.php?id=7577) posted by [ceasar](http://archive.tinymce.com/profile.php?name=ceasar)_

> _**Tags:** [firefox msie safari chrome heading onclick]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
