### ISSUE TITLE
Select-all then delete leaves a blank editor with an empty <p> and no <br> in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2291]
Description of problem: if I select all contents of an inline editor and then delete them, an empty &ltg;p>&ltg;/p> tag is left behind without a bogus &ltg;br>, and the cursor disappears or shrinks.  The empty &ltg;p> happens in any inline editor instance, but is most visually obvious in an editor with a flex column layout (the real issue is the empty &ltg;p>&ltg;/p> left behind in Chrome where other browsers insert a &ltg;br> -- it's not a flex issue).

This only occurs if multiple elements are deleted; if there's only one element in the editor and it is deleted, a bogus &ltg;br> is inserted correctly in the &ltg;p>.

It only happens in Chrome. In Firefox and SeaMonkey (a Mozilla derivative) it works fine (the &ltg;br> is inserted and the cursor appears).

Steps to reproduce:
1. set up an inline editor with multiple elements (eg. lines of text)
2. select-all
3. delete
4. the cursor may go to the first line, but jump down when any text is entered (or even just hitting &ltg;enter>
5. in a flex column layout (vertically centered), the cursor disappears completely and can only be restored by typing in the editor (see fiddle)

Expected result: a &ltg;br> bogus element should be left behind after the editor's contents are removed.

Actual result: only an empty &ltg;p>&ltg;/p> is left behind (as seen in the DOM inspector), leaving the cursor state indeterminate.

Here's another fiddle without flex layout; the cursor doesn't disappear but is diminished because the &ltg;p> is empty: http://fiddle.tinymce.com/pQeaab/4

Thanks.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7579](http://archive.tinymce.com/develop/bugtracker_view.php?id=7579) posted by [TrevorPT](http://archive.tinymce.com/profile.php?name=TrevorPT)_

> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/pQeaab/3_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
