### ISSUE TITLE
Deleting first <p> element leaves style behind in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2292]
Description of problem: 1) if all elements within the editor are selected and deleted, the &ltg;p> left behind keeps any styles in Chrome; 2) if the first element in the editor is a &ltg;p> and is deleted, any styles on that &ltg;p> are adopted by the next &ltg;p>.

This happens in Chrome, but works properly in Firefox.

Steps to reproduce (1):
1. select all elements (ctrl+a)
2. apply a format
3. select all elements
4. delete (to delete everything)

Expected result: an empty editor with a &ltg;p> left behind with no style.

Actual result: the &ltg;p> left behind keeps any styles from the first element that was in the editor prior to deletion.

Steps to reproduce (2):
1. select first &ltg;p> line of text
2. apply a format
3. delete first &ltg;p> line of text

Expected result: the first &ltg;p> line of text should be deleted with its styles.

Actual result: the line is deleted but the next line of text takes on the styles from the deleted &ltg;p>

Thanks.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7580](http://archive.tinymce.com/develop/bugtracker_view.php?id=7580) posted by [TrevorPT](http://archive.tinymce.com/profile.php?name=TrevorPT)_

> _**Tags:** [chrome chrome]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/pQeaab/6_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
