### ISSUE TITLE
spellchecker- activation

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2293]
Description of problem:
spellcheck "standard" and current tinymce support ? note: i'm new to the library, and this report is only a question.

Steps to reproduce:
1.spellcheck functions available on Win/IE 10
2.it work with the language attribute
3.

Expected result:
Using the computer/browser capabilities for a function (spellcheck)
Can make correction as you type, by DEFAULT ! here on the try it I don't have spellcheck and editing this field it's available = can this function become available by default ? as in HTML, each element will have it's language attribute value set and it's toolbar item...

Actual result:
spellcheck available but need to pass from an enterprise function to a standard function ?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7581](http://archive.tinymce.com/develop/bugtracker_view.php?id=7581) posted by [Moglane](http://archive.tinymce.com/profile.php?name=Moglane)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
