### ISSUE TITLE
Missing imagetools icons if tollbar_items_size is set to small

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2295]
Description of problem:

Icons for imagetools icons are missing if toolbar_items_size is set to small. See attachment.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7583](http://archive.tinymce.com/develop/bugtracker_view.php?id=7583) posted by [eustach](http://archive.tinymce.com/profile.php?name=eustach)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
