### ISSUE TITLE
TinyMCE 4 doesn't undo non-typing edits (e.g. Cut) as reliably as on TinyMCE 3

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2296]
Description of problem:

TinyMCE 4's undo behavior is less reliable than TinyMCE 3, because of the circumstances in which TinyMCE 3 set UndoManager's typing state to true, causing more aggressive registration of transient changes during the undo method itself.

Steps to reproduce:

1. Go to http://fiddle.tinymce.com/8Qeaab/3
2. Double click the word "Two" in the editor.
3. Press Cmd-X to cut the word.
4. Press Cmd-Z to undo the cut.

Expected result:

The word two should reappear in the document.

Actual result:

Nothing happens, because at this phase no additional undo level has been added to the stack.

This bug happens on TinyMCE 4 but not on TinyMCE 3, because 3.x benefited from a combination of UndoManager's "typing" state being aggressively set (in Editor.js the event handler that sets typing = true didn't filter out Cmd-key presses), and UndoManager's undo method aggressively re-registering the current changes if typing was set to true.

As a crude workaround I'm aggressively adding an undo registration EVERY time undo is called. It seems innocuous most of the time when there are no content changes. But surely there is a better, more systematic fix.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7584](http://archive.tinymce.com/develop/bugtracker_view.php?id=7584) posted by [danielpunkass](http://archive.tinymce.com/profile.php?name=danielpunkass)_

> _**Tags:** [safari safari9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/8Qeaab/3_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
