### ISSUE TITLE
ASP.NET MVC Codes Doesnt Save

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2297]
Hey,

I'm using tinymce 4.2.1 with visual studio for .net development. (MVC5, Razor Codes)
I have a website for save mvc5 code parts but sometimes doesnt work. (no problem about html,css,js codes)

Generally this type mvc5 codes give me error. for example:

&ltg;pre>
        public ActionResult index(string lang)
        {
            string finalLang = CheckLang(lang);
            ViewBag.Seo1 = XMLNodeReader.GetValueFromXML(GetStaticTextsByBrowserLanguage(finalLang), finalLang, "index_title");
            ViewBag.Seo2 = XMLNodeReader.GetValueFromXML(GetStaticTextsByBrowserLanguage(finalLang), finalLang, "index_description");
            ViewBag.Seo3 = XMLNodeReader.GetValueFromXML(GetStaticTextsByBrowserLanguage(finalLang), finalLang, "index_keyword");

```
        if (string.IsNullOrEmpty(finalLang))
        {
            Session["selectedLang"] = finalLang;
            return RedirectToAction("Index", new { lang = finalLang });
        }
        return View();
    }
```

&ltg;/pre>

Can you help me pls ?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7594](http://archive.tinymce.com/develop/bugtracker_view.php?id=7594) posted by [kayakiranh](http://archive.tinymce.com/profile.php?name=kayakiranh)_
> 
> _**Tags:** [chrome chrome mvc5 razor code]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
