### ISSUE TITLE
Return key inserts multiple newlines on Safari

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2298]
Hitting the return key inserts multiple paragraphs. Won't do it if I press return after typing some text.

Steps to reproduce:
1.Go to http://www.tinymce.com/tryit/basic.php
2.File > New Document
3.Hit return key

Expected result:
Source code should show
&ltg;p>&nbsp;&ltg;/p>
&ltg;p>&nbsp;&ltg;/p>

Actual result:
Source code shows:
&ltg;p>&nbsp;&ltg;/p>
&ltg;p>&nbsp;&ltg;/p>
&ltg;p>&nbsp;&ltg;/p>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7586](http://archive.tinymce.com/develop/bugtracker_view.php?id=7586) posted by [ndebarnot](http://archive.tinymce.com/profile.php?name=ndebarnot)_

> _**Tags:** [safari safari8 newlines safari]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
