### ISSUE TITLE
Add a way to determine if TinyMCE is initialized globally

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2299]
Description of problem:

When using the jQuery TinyMCE plugin, there doesn't seem to be any way to tell when all of the TinyMCE objects are ready without having access to the TinyMCE object first (catch-22 I can't access it until after initialization).

I am developing a jQuery plugin that should work seamlessly with TinyMCE, but I don't have access to the settings of TinyMCE because that is an "end developer" function.

The ":tinymce" selector does not function until TinyMCE is initialized, and this is not yet completed on jQuery document ready. So, this code will never return true:

$( document ).ready(function() {
    alert($('form').find(':tinymce').length > 0);
});

The only solution I have found to fix this is to add a setTimeout call in order to wait for TinyMCE to initialize. But that is just a hack.

Ideally, the plugin would send a document event when all instances are initialized. Like...

$(document).trigger('init.tinymce');

Then I just need to bind to the event to run my logic.

$(document).bind('init.tinymce', function() {
    alert($('form').find(':tinymce').length > 0);
});

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7587](http://archive.tinymce.com/develop/bugtracker_view.php?id=7587) posted by [NightOwl888](http://archive.tinymce.com/profile.php?name=NightOwl888)_
> 
> _**Tags:** [firefox msie safari chrome initializaion]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
