### ISSUE TITLE
.isDirty() doesn't correctly manage state

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2300]
Description of problem:

.isDirty() returns true even when the text is returned to the original state.

Steps to reproduce:
1. Edit the text in TinyMCE.
2. Edit the text again, this time reverting the changes made in step 1.

Expected result:

If the user returns the text to its original state, .isDirty() should return false.

Actual result:

.isDirty() returns true.

Note that this behavior works correctly on the CKEditor plugin.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7588](http://archive.tinymce.com/develop/bugtracker_view.php?id=7588) posted by [NightOwl888](http://archive.tinymce.com/profile.php?name=NightOwl888)_

> _**Tags:** [firefox msie safari chrome isdirty dirty]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by spocke** [comment]
This behavior has been changed an editor is now always dirty when it has been changed until you tell it not to be using setDirty API call.
