### ISSUE TITLE
Use toggle button INSTEAD of area onclick for inline editing

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2301]
Is there a way to use the inline editor (since it's a seamless transition back and forth to edit mode), but to use a toggle button instead of clicking in the div? And turn off the event that is triggered by clicking inside and outside the edit area?

What I mean is, I want the page to act as a normal web page (not go into edit mode if somebody clicks on the div area), and then have a toggle button that would switch it back and forth to edit mode rather than the inline clicking.

Also, if there are multiple editors, how to target a specific editor instance.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7600](http://archive.tinymce.com/develop/bugtracker_view.php?id=7600) posted by [EasyProWebTools](http://archive.tinymce.com/profile.php?name=EasyProWebTools)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by rambo666** [comment]
Has this been fixed on version 5?
