### ISSUE TITLE
Unable to get the exact length of the content.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2302]
Description of problem:

Steps to reproduce:
1. Created one RichText editor using 'mceIframeContainer' which is used to display the content in the field,modify the content and apply the basic styles like bold,underline,italic.
2. On double click on this field, it will open a new page to display the content and can apply all styles like color, etc.,
3. We have validation to restrict the user to enter fixed length in both the windows and before saving the the content.
4. While checking the length in both the fields, the length is varying. It is causing due to below reasons:
a) Tags attribute are separated with ';' even it is end tag attribute in one window, ';' not appending in other windows.
b) while copying and paste from different sources like MS-Word, the tags are varying in both the windows.

Expected result: It has to give exact length in both the windows along with same html specific tags.

Actual result: It gives different length.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7601](http://archive.tinymce.com/develop/bugtracker_view.php?id=7601) posted by [ashokrajaboda](http://archive.tinymce.com/profile.php?name=ashokrajaboda)_

> _**Tags:** [msie msie9 msie10 msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
