### ISSUE TITLE
Download of multiple languages is not possible

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2303]
Description of problem:

It is not possible to download multiple languages as a zip file.

Steps to reproduce:
1. Go to http://www.tinymce.com/i18n/index.php
2. Check all languages
3. Go to the bottom and click download

Expected result:

A zip file containing all language files.

Actual result:
A error message appears.

"Error, language not defined."

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7590](http://archive.tinymce.com/develop/bugtracker_view.php?id=7590) posted by [jogep](http://archive.tinymce.com/profile.php?name=jogep)_
> 
> _**Tags:** [firefox chrome firefox chrome download distribution]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/i18n/index.php_

**Comment by blackcathikari** [comment]
We've taken a look and believe this is related to #2326 (due to 'Russian Petrine orthograph' causing an error) and #2325 (wanting to download all languages more easily). Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
