### ISSUE TITLE
valid_children does not work as expected if invalid child is attempted to be wrapped in a parent

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2304]
Description of problem:
With the parameter: valid_children : '-h1[strong]', if text is surrounded by a strong tag, and the user attempts to apply an h1 tag to replace the standard p tag the source code will remain &ltg;p>&ltg;strong>content&ltg;/strong>&ltg;/p> but the editor will display &ltg;h1>&ltg;strong>content&ltg;/strong>&ltg;/h1>

Steps to reproduce:
1. Add the above parameter to the config
2. Type text into TinyMCE
3. Highlight text, apply strong tag
4. Apply H1 to text.
5. View source and the WYSIWYG editor

Expected result:
My hope was that applying an h1 tag would remove the child strong tag, but it appears that the intended functionality would prevent an h1 tag from being added.

Ideally I would like a solution to a problem where bold text is commonly turned into a heading which leaves the strong tag inside the heading. This leads to one of 2 problems, either it doesn't actually do anything because the heading is already bold making it redundant. Or it bolds the heading which is contrary to the styleguide for the site, but the content editors don't always notice.

Actual result:
The WYSIWYG and code are not aligned with eachother. the WYSIWYG allows the change to be made, but the code display shows that the change was not made.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7591](http://archive.tinymce.com/develop/bugtracker_view.php?id=7591) posted by [cole](http://archive.tinymce.com/profile.php?name=cole)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/qReaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
