### ISSUE TITLE
Multiple document_base_url via array to handle www vs non-www

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2305]
It would be great if document_base_url could handle multiple entries. Currently I would like to re-write all URLs that direct to the same site to root relative URLs ("http://www.testdomain.com/content" becomes "/content"). However, our site currently redirects all www.testdomain.com traffic to testdomain.com. Writers will commonly still add the www. 

With the current functionality of document_base_url, convert_urls, and relative_urls we must choose between re-writing www. and non-www to the root relative URL

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7592](http://archive.tinymce.com/develop/bugtracker_view.php?id=7592) posted by [cole](http://archive.tinymce.com/profile.php?name=cole)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
