### ISSUE TITLE
Merge into style_formats categories

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2306]
When styles_format_merge is set to true, it would be nice if declaring style formats in a default category such as blocks or inline styles would add to that category.

If you look at the formats dropdown in the attached URL, it would be ideal if only 1 blocks and 1 inline category were created instead of multiples.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7593](http://archive.tinymce.com/develop/bugtracker_view.php?id=7593) posted by [cole](http://archive.tinymce.com/profile.php?name=cole)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/rReaab/1_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
