### ISSUE TITLE
Cut a Text and use undo to revert does not work on OSX

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2307]
Description of problem:

OSX: Using &ltg;cmd>-&ltg;x> to cut a part of the tinymce text content and directly afterwards use &ltg;cmd>-&ltg;z> to undo is not working. 
(It seems the cut event is not triggering a undo-level. moving the caret between the two shortcuts fixes undo)

Steps to reproduce:
1. &ltg;cmd>-&ltg;x> text
2. &ltg;cmd>-&ltg;z> to undo

Expected result:
text is appearing again

Actual result:
text does not appear again

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7595](http://archive.tinymce.com/develop/bugtracker_view.php?id=7595) posted by [freetwix](http://archive.tinymce.com/profile.php?name=freetwix)_

> _**Tags:** [firefox chrome firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
