### ISSUE TITLE
ChromeOS Japanese input content disappear 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2308]
Description of problem:

Steps to reproduce:
1. Open a page with tinymce and focus on tinymce textarea
2. Using "Google Japanese Typing mode"
3. Type random input
4. Select all text with "Ctrl+A"

Expected result: The text gets selected

Actual result:  The text disappears

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7596](http://archive.tinymce.com/develop/bugtracker_view.php?id=7596) posted by [Frankzhu](http://archive.tinymce.com/profile.php?name=Frankzhu)_
> 
> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** Using ChromeOS v42&43 and operate Ctrl+A results disappearing all contents_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
