### ISSUE TITLE
Numbered list sequence changed when a bullet list below is changed to a numbered list

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2311]
Description of problem:
When a bullet list under a numbered list is changed to a numbered list the sequence of the top numbered list is re-arranged

Steps to reproduce:
1. Create a numbered list with more than 2 or more items
2. Create a bullet list below the numbered list
3. Change the bullet list to a numbered list

Expected result:
The list will merge into one numbered list

Actual result:
The sequence of the items in the top are re-arranged

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7599](http://archive.tinymce.com/develop/bugtracker_view.php?id=7599) posted by [SonnG](http://archive.tinymce.com/profile.php?name=SonnG)_
> 
> _**Tags:** [firefox msie safari chrome bullet list numbered ul li ol]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/NReaab/1_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
