### ISSUE TITLE
On iOS devices, focus has problems with multiple tinymce fields

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2312]
Description of problem: The text cursor doesn't always go to the correct field when clicking between multiple tinymce fields on iOS.

Steps to reproduce on iOS:
1. Click on the first tinymce field and type something
2. Click on the second tinymce field and type something
3. Click back to the first one. Notice the cursor is still on the second field.
4. Start typing. The text appears in the first tinymce field.

Expected result:
The cursor is shown on the tinymce field in focus

Actual result:
The cursor can be on the incorrect tinymce field.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7602](http://archive.tinymce.com/develop/bugtracker_view.php?id=7602) posted by [allenwp](http://archive.tinymce.com/profile.php?name=allenwp)_

> _**Tags:** [safari chrome safari9 chrome ios safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/6Seaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
