### ISSUE TITLE
Inline editing an "inline" tag (span) produce misc issues (ending <br> and worse)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2313]
Description of problem:
Sometimes tinymce leave trash &ltg;br> in inline elements.

Steps to reproduce:
Add inline mode editor to a "span" element. Move to the end, add a new line (enter) and then remove it. Tinymce will leave a &ltg;br/>:
http://fiddle.tinymce.com/CSeaab/1

Expected result:
No ending &ltg;br/> when we are on a "single line".

Actual result:
Ending &ltg;br/> that cannot be removed.

MAJOR: In IE11 there is a much bigger issue because when you hit "enter" the container element is duplicated inside the content and the whole thing is messed up!
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7604](http://archive.tinymce.com/develop/bugtracker_view.php?id=7604) posted by [bago](http://archive.tinymce.com/profile.php?name=bago)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/CSeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
