### ISSUE TITLE
jquery plugin seems to fail to recreate tinymce instance after its dom is removed and recreated

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2314]
see JSFiddle provided. This type of behavior (removal of DOM, and then recreation of the same DOM) occurs with tabs loaded via AJAX and jQuery UI dialogs.

Edit: updated Fiddle.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7605](http://archive.tinymce.com/develop/bugtracker_view.php?id=7605) posted by [pmcquay](http://archive.tinymce.com/profile.php?name=pmcquay)_

> _**Tags:** [jquery]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/ffxgfn66/2/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
