### ISSUE TITLE
Image Browser not updating in editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2315]
Description of problem:
I'm using kcfinder for file manager (actually image management) and is set up as the documentation suggests:
http://www.tinymce.com/wiki.php/Configuration:file_browser_callback
The browse button does open the new window, when you click on an image it does closes and updates the input field, but when you press ok the window closes and nothing gets inserted into the editor.
I've been trying to get around this for a few hours, so I did noticed that if I focused on the input field and press the control key (only control) the image did got inserted.
this happens only on version 4.2 + 
I believe has something to do with new image support

Steps to reproduce:
1.click on add image icon
2.click on browse
3.select an image (kcfinder)
4.click ok on popup window

Expected result:
Image gets inserted on editor

Actual result:
nothing

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7606](http://archive.tinymce.com/develop/bugtracker_view.php?id=7606) posted by [vallarinoj](http://archive.tinymce.com/profile.php?name=vallarinoj)_
> 
> _**Tags:** [firefox msie safari chrome file_browser images]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
