### ISSUE TITLE
Editor removes name file extension in lists

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2316]
Description of problem:

Steps to reproduce:
1.open the attached file
2.copy its content
3.paste it in the editor (use the one here: http://www.tinymce.com/tryit/basic.php)

Expected result:
The text should be pasted and formatted as it is in MsWord

Actual result:
It looks like the text after a period (detected as a fie extension?) is stripped out

Note: if you do not use a list, it will be fine
Note2: if you add double quotes, the text after the period is not removed

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7607](http://archive.tinymce.com/develop/bugtracker_view.php?id=7607) posted by [OlivierS](http://archive.tinymce.com/profile.php?name=OlivierS)_
> 
> _**Tags:** [firefox msie safari chrome msword list copy paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
