### ISSUE TITLE
Support an official Rails gem

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2320]
There is a Rails gem called tinymce-rails, which makes supporting tinymce in a Rails app just a simple Gemfile drop-in.  

The version of the gem on github hasn't been updated in months (it's at 4.1.6) despite several pull requests, so it looks like it's been abandoned. 

According to rubygems.org, the existing gem has been downloaded 600K+ times, so it's clearly of value. It would be very helpful if this gem was maintained and kept in synch by the tinymce project instead of depending on others to maintain it. 

I'd be happy to help with this, except that I don't know much about creating gems. If you think this is a good idea, I'll volunteer.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7611](http://archive.tinymce.com/develop/bugtracker_view.php?id=7611) posted by [jhaungs](http://archive.tinymce.com/profile.php?name=jhaungs)_
> 
> _**Tags:** [ruby rails gem]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
We won't create an official rails gem.
