### ISSUE TITLE
i-tag gets removed by the editor although i[*] has been set

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2323]
TinyMCE: 3.5.11
Description of problem:
The editor removes a &ltg;i class="icon-info">&ltg;/i> inserted into the editor area using the html input. I've set the extended_valid_elements parameter to i[*] and have tested i[class|style|id] too. It didn't help.
I also have set the schema to html5.

Same in your full featured example.

Steps to reproduce:
1. open the html input
2. insert a &ltg;i class="yourclass">&ltg;/i> or this example code

&ltg;div class="feature-box fbox-border fbox-light fbox-effect">
&ltg;div class="fbox-icon">&ltg;i class="icon-ok">&ltg;/i>&ltg;/div>
&ltg;h3>Text&ltg;/h3>
&ltg;p>AnotherText&ltg;/p>
&ltg;/div>

3. hit the insert button
4. reopen the html input
5. see that the &ltg;i...>&ltg;/i> is gone

Expected result:
The code should be there as inserted.

Actual result:
After inserting the code the editor removes the i-tag.

Further tests:

1. Tried valid_elements : "+*[*]" >> no success, code is removed
2. Disabled css checking by verify_css_classes : false >> no success, code is removed
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7614](http://archive.tinymce.com/develop/bugtracker_view.php?id=7614) posted by [Hurga_Gonzales](http://archive.tinymce.com/profile.php?name=Hurga_Gonzales)_

> _**Tags:** [firefox msie safari chrome itag extended_valid_elements]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
