### ISSUE TITLE
Make all languages downloadable

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2325]
Description of problem:

I want to download all languages at once

Expected result:

Get one big ZIP file without checking all checkboxes first

Actual result:

I need to manually check all checkboxes of all languages

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7616](http://archive.tinymce.com/develop/bugtracker_view.php?id=7616) posted by [phax](http://archive.tinymce.com/profile.php?name=phax)_
> 
> _**Tags:** [firefox msie safari chrome language]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
You can now just click the select all button here: https://www.tinymce.com/download/language-packages/
