### ISSUE TITLE
Language 'Russian Petrine orthography' not downloadable

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2326]
Description of problem:

The language "Russian Petrine orthography" cannot be downloaded. It results in an internal error.
Btw. please update the internal error text stating what language cannot be downloaded.

Update: the same seems to be the case for language 'Norwegian Bokm�l (Norway)'

Expected result:

Either remove it, or make it downloadable.
Change the error text to sthg. like 'Error, language 'Russian Petrine orthography' not defined.'

Actual result:

An internal error stating 'Error, language not defined.' 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7617](http://archive.tinymce.com/develop/bugtracker_view.php?id=7617) posted by [phax](http://archive.tinymce.com/profile.php?name=phax)_
> 
> _**Tags:** [firefox msie safari chrome language]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by phax** [comment]
This problem still exists. Currently the following language cannot be downloaded at all:
  * Russian Petrine orthography

When selecting all languages (except Russian Petrine) the same error occurs. When deselecting "Norwegian Bokmål (Norway)" it works. When downloading only "Norwegian Bokmål (Norway)" it also works - this is kind of weird behaviour...

**Comment by fyrkant** [comment]
Closing this as it doesn't seem like we have 'Russian Petrine orthography' available for download anymore.
