### ISSUE TITLE
link_assume_external_targets Doesn't Seem to Work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2327]
Description of problem:

Steps to reproduce:
1. Click the toolbar to add a link.
2. Add a link to www.google.com and click OK.
3. The "Do you want to add the required http:// prefix?" dialog always displays regardless of whether link_assume_external_targets is set to true or false.

Expected result:
The "Do you want to add the http prefix" dialog not to display.

Actual result:
The "Do you want to add the http prefix" dialog displays.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7618](http://archive.tinymce.com/develop/bugtracker_view.php?id=7618) posted by [jpragit](http://archive.tinymce.com/profile.php?name=jpragit)_

> _**Tags:** [chrome chrome link]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/8Teaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
