### ISSUE TITLE
Undo button not working when table item is deleted

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2328]
Description of problem:

Steps to reproduce:
1.Select the cell item highlighting the whole cell/cells
2.delete
3.click undo

Expected result: Undo will work. This works in 4.1

Actual result: Deleted text/item is not restored.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7619](http://archive.tinymce.com/develop/bugtracker_view.php?id=7619) posted by [SonnG](http://archive.tinymce.com/profile.php?name=SonnG)_

> _**Tags:** [firefox msie safari chrome table delete undo]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/FTeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
