### ISSUE TITLE
Aligning content inside a centered table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2329]
I'm having problem when trying to align (center or justify for example) text inside a table when the table itself is centered.

Let's create a 1 cell table 80% width centered. Put text inside the table cell and try to center or justify it.

On chrome it will sometime work but both centered and justify icons will be on when cursor in the text.
On safari or Firefox, clicking the center or justify icons just won't work. Both icons are also on.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7620](http://archive.tinymce.com/develop/bugtracker_view.php?id=7620) posted by [ndebarnot](http://archive.tinymce.com/profile.php?name=ndebarnot)_

> _**Tags:** [firefox safari chrome firefox safari8 chrome table alignment]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
