### ISSUE TITLE
Safari Slow Page Loading, Console Reports Errors (TinyMCE 4.22)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2331]
Description of problem:

Steps to reproduce:
1. Open page in Safari that contains TinyMCE, loads slow with spinning beach ball
2. View page source and from source, view Console for errors
3. Discover about ten TinyMCE errors, all say "Can't find variable: safari"
4. FYI, had same errors in TinyMCE 3.x
5. (I'm wondering if it's happening because your don't capitalize Safari?)

Expected result:  Same as Firefox, fast page loading, no errors

Actual result:  Slow page loading, errors.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7622](http://archive.tinymce.com/develop/bugtracker_view.php?id=7622) posted by [Cave_Dweller](http://archive.tinymce.com/profile.php?name=Cave_Dweller)_
> 
> _**Tags:** [safari safari7 safari slow loading errors]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
