### ISSUE TITLE
insertdatetime: no localized day and month names

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2333]
Description of problem:
insertdatetime produces only english instead of localized day and month names

Steps to reproduce:
1. use plugin insertdatetime
2. set language to dutch (could be any language)
3. set insertdatetime_formats: ["%A %d %B %Y "]
4. insert a date time

Expected result: localized day and month name

Actual result: english day and month nam

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7624](http://archive.tinymce.com/develop/bugtracker_view.php?id=7624) posted by [RobF](http://archive.tinymce.com/profile.php?name=RobF)_
> 
> _**Tags:** [firefox msie safari chrome plugin localization]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/RTeaab_

**Comment by GTTo** [comment]
+1

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
