### ISSUE TITLE
Pasting in Microsoft Edge Results in Chinese Characters

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2336]
Description of problem: As far as I can tell it is only in Microsoft Edge. If I copy any piece of text and paste it into tinymce, it results in a huge block of Asian characters. For example: ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????�?�?????????????�?�?????�?�?????�?�????????????????????????????????????�?�??????????????????????????????????????????????????????????????????????????????�?�????????�?�????????????�?�??????????????????�?�???????????????????????????�?�???????????????????????????????????�?�????????????????????????????????????????????????????�?�????????�?�??????�?�????????�?�????????????�?�???????????????????????????????????????????????????????�?�?????????????????????????????????�?�????????????????????�?�???????????????????�?�????????????????????�?�??????????????????????�?�????????????????????????????�?�????????????�?�???????�?�????????????????????????????�?�????????????????????????????????????????????????????????????????????????�?�???????????????????????????�?�????????????????????????????????????????????????? 

Steps to reproduce:
1. Copy any text from anywhere
2. Paste into TinyMCE in Microsoft Edge

Expected result: For the same text I copied to be pasted

Actual result: Huge block of Asian charactetrs

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7636](http://archive.tinymce.com/develop/bugtracker_view.php?id=7636) posted by [Rothalack](http://archive.tinymce.com/profile.php?name=Rothalack)_

> _**Tags:** [msie msie11 edge microsoft]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://wonderwise.guildlaunch.com/sections/raiders/?gid=480202_

**Comment by spocke** [comment]
Fixed this issue in the latest release.
