### ISSUE TITLE
Document changes to "mode" in v4.0.26+

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2338]
Description of problem:
Undocumented changes to how 'mode' works has broken AJAX implementations.

Steps to reproduce:
1. Implement TinyMCE 4.0.19 with an ajax loaded editor. Use mode "exact".
2. Submit or cancel which goes back to an interface which has a button to load the editor again.
3. Load the editor again. It works, yay!
4. Do the same with 4.0.26. Doesn't work! Boo!

Expected result:
Using mode "exact", I could init TinyMCE on an element with the same ID as many times as I wanted. 

Actual result:
With more recent (4.0.26+) versions, this is not possible.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7629](http://archive.tinymce.com/develop/bugtracker_view.php?id=7629) posted by [archonic](http://archive.tinymce.com/profile.php?name=archonic)_

> _**Tags:** [firefox msie safari chrome documentation mode v4019 v4026]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
