### ISSUE TITLE
Background color is not working correctly when increasing the text size.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2340]
Description of problem:

Steps to reproduce:
1. Type some text like test
2. Apply background color and text color on the text.
3. Type some more text.
4. Increase the font size to 36.
5. Type more text and observe

Expected result:
Text should be inside the background color.

Actual result:
Text moves out of the background color.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7634](http://archive.tinymce.com/develop/bugtracker_view.php?id=7634) posted by [asadzaidi](http://archive.tinymce.com/profile.php?name=asadzaidi)_

> _**Tags:** []_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
