### ISSUE TITLE
custom html tags are  not showing in IE browser but its working other browsers

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2341]
Description of problem:

Steps to reproduce:
1.create custom tags in the editor ex " &ltg;mergefield:company_address select="@companyAddress" title="{COMPANY ADDRESS}" class="mfield">&ltg;/mergefield:company_address>"
2.its not showing in the editor 
3.
4.
5.

Code :

  tinymce.init({
        selector: "textarea#editor",
        height: "278px",
        width: "100%",
        statusbar : false,
        plugins: [
            "advlist autolink lists link image charmap print preview",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime nonbreaking save table contextmenu directionality",
            "template paste textcolor colorpicker textpattern","pagebreak"

```
    ],
    toolbar1: "insertfile undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview | forecolor backcolor | styleselect | fontselect |  fontsizeselect",
    removed_menuitems: 'newdocument',
    image_advtab: true,
    apply_source_formatting : true,
    remove_linebreaks : false,
    force_br_newlines : true,
    contextmenu: "bold italic preview",
    extended_valid_elements : "*[*]",
    custom_elements: "~mergefield,span",
    content_css: "../css/default/mail_merge_template_editor.css",
    pagebreak_separator : "&ltg;p style=\"page-break-before: always;\">&ltg;/p>",
    init_instance_callback : function(editor) {
        if (document.forms['mailMergeTemplateForm'].elements['template.content'].value != null) {
            editor.setContent(document.forms['mailMergeTemplateForm'].elements['template.content'].value);
        }
    }
});
```

css code : 

.mfield {
    background-position: left -3px bottom -3px;
    padding: 0px 0px 0px 0px;
    border:1px solid #CCCCCC;
    height:10px;
    width:100px;
    color: black;

}
.mfield:hover{
    color: red;
}
.mfield:before {
    content: attr(title);
    background-color:  #ffff32;
}

.mfield[select]:hover:after {
    content: attr(select);
    padding: 4px 8px;
    color: #333;
    left: 0;
    top: 100%;
    white-space: nowrap;
}

Inserting the below content in the source code :
&ltg;p>&ltg;mergefield:company_address select="@companyAddress" title="{COMPANY ADDRESS}" class="mfield">&ltg;/mergefield:company_address>&nbsp;&ltg;/p>

Expected result: custom html tags should be shown.

Actual result: custom tags are not showing the editor

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7631](http://archive.tinymce.com/develop/bugtracker_view.php?id=7631) posted by [pradeepa](http://archive.tinymce.com/profile.php?name=pradeepa)_
> 
> _**Tags:** [msie msie9 msie10 msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
