### ISSUE TITLE
Paste as text functionality is not pasting the HTML text as plain text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2342]
Description of problem:

Steps to reproduce:
1. Type some text like test
2. Apply background color and text color on the text.
3. Copy the text
4. Select option 'Paste as text'
5. Paste the text.

Expected result:
Text should be pasted as plain text.

Actual result:
Text is pasted in HTML format.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7633](http://archive.tinymce.com/develop/bugtracker_view.php?id=7633) posted by [asadzaidi](http://archive.tinymce.com/profile.php?name=asadzaidi)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
