### ISSUE TITLE
Changing video dimensions when constrain proportions is checked and clicking the ok button does not resize the video properly

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2343]
Description of problem:
This is after inserting a video with 'insert/edit video' dialogue. Changing the height of the video and the 'Constrain proportions' check box is checked, clicking the 'OK' button resizes the height but not the width. The same thing happens if you change width instead.

Although if you change the height and click anywhere in dialogue box the value in the width text box value changes.

Steps to reproduce:
1. Insert video, make sure 'Constrain proportions' is checked
2. Go back to the 'insert/edit video' dialogue
3. Change the height of the video
4. Click the OK button

Expected result:
Both height and width should change

Actual result:
Only the height changes

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7635](http://archive.tinymce.com/develop/bugtracker_view.php?id=7635) posted by [esmondPunsalan](http://archive.tinymce.com/profile.php?name=esmondPunsalan)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
