### ISSUE TITLE
tinymce.com: Bugs search issue with html entities

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2344]
Steps:
1. Go to http://www.tinymce.com/develop/bugtracker_bugs.php
2. Enter &nbsp in the search input, press Enter.
3. Use page navigation to see next (or any other) page.

Observe the filter argument in URL is wrong and displaying other pages does not work.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7637](http://archive.tinymce.com/develop/bugtracker_view.php?id=7637) posted by [alec](http://archive.tinymce.com/profile.php?name=alec)_
> 
> _**Tags:** []_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
