### ISSUE TITLE
Rearrange Style value when highlight on some text and click underline in IE.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2345]
Description of problem:
The original span style was "font-size: 10pt; font-family: Calibri;", after highlight some text and click underline in IE, the value inside the span style will change order, eg: "font-family: Calibri; font-size: 10pt;"

Please refer to : http://fiddle.tinymce.com/ZUeaab

Steps to reproduce:
1. Highlight some text with your mouse.
2. Click on "underline"
3. Click on source code button
4. You will notice the value of span style has change the order compare with the before change.

Expected result: The order of the value in span style should remain unchanged.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7638](http://archive.tinymce.com/develop/bugtracker_view.php?id=7638) posted by [wilson.mak](http://archive.tinymce.com/profile.php?name=wilson.mak)_

> _**Tags:** [msie msie9 msie10 msie11 ie underline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/ZUeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
