### ISSUE TITLE
Wrap again toolbar button text in a span

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2346]
Description of problem:
Since upgraded to version 4.2 I see the toolbar buttons text is no longer wrapped in a span tag, which breaks my custom toolbar styling and it's hard to do it on my own.

Steps to reproduce:
1. Load tinymce v4.2 and above into fiddle.tinymce.com and inspect "Formats" button text (see tinymce-4.2.JPG)
2. Load tinymce below v4.2 into fiddle.tinymce.com and inspect "Formats" button text (see tinymce-4.0.JPG)

Expected result:
"Formats" text to be in a span tag
Actual result:
"Formats" is just a plain text
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7639](http://archive.tinymce.com/develop/bugtracker_view.php?id=7639) posted by [todorpr](http://archive.tinymce.com/profile.php?name=todorpr)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by spocke** [comment]
Fixed this one.
