### ISSUE TITLE
page support for tinyMCE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2348]
Hi!

I was wondering if anyone tried to add page support to tinyMCE (like google docs / ms word has). I searched the features section + a lot of the web these days, and no one seems to have implemented that...

Thanks!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7641](http://archive.tinymce.com/develop/bugtracker_view.php?id=7641) posted by [ra00l](http://archive.tinymce.com/profile.php?name=ra00l)_
> 
> _**Tags:** [page]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
