### ISSUE TITLE
Multiple selected spans do not get the same background color height

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2349]
Description of problem:

Steps to reproduce:
1. type small text
2. change font size to something larger
3. type more larg text
4. highlight all text
5. change background color

Expected result:
all text will be highlighted with the correct background-color height.

Actual result:
only 1 span has background color property causing the background-color height to be incorrect on other span

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7642](http://archive.tinymce.com/develop/bugtracker_view.php?id=7642) posted by [SonnG](http://archive.tinymce.com/profile.php?name=SonnG)_

> _**Tags:** [firefox msie safari chrome backgroundcolor span]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/vVeaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
