### ISSUE TITLE
Fancybox + Tinymce multiple open "id" param bug

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2351]
Description of problem:

I have used 4.0 for a long time with fancy box. After i have updated 4.2.x my textareas getting wrong.
I open textareas in fancybox with Tiny Mce. 
As you see in example if you open textarea without "id" parameter, everything works fine, i can open the popup as many times as i want.
But if the textarea has "id" parameter, and the popup was opened second, the textarea getting hide and mce not initialized.

I have set up everythimg same with Tinymce 4.0
https://www.totalstudio.hu/tinymce_test/index_old.html

Steps to reproduce:
1. Visit https://www.totalstudio.hu/tinymce_test/index.html
2. Click on links many times.
3. Try it with version 4.0 https://www.totalstudio.hu/tinymce_test/index_old.html
4.
5.

Expected result:

TExtarea With id param render correctly after second open without page refresh

Actual result:

Textarea with id param stays hidden, and TinyMce not initialized. No javascript errors.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7644](http://archive.tinymce.com/develop/bugtracker_view.php?id=7644) posted by [lamasgergo](http://archive.tinymce.com/profile.php?name=lamasgergo)_
> 
> _**Tags:** [firefox msie safari chrome fancybox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** https://www.totalstudio.hu/tinymce_test/index.html_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
