### ISSUE TITLE
Can't submit a new language that only has a three letter ISO language code 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2353]
Description of problem:
The interface for adding a new language to TinyMCE expects a two letter language code, but there are languages that only have three letter codes.

I was trying to add Filipino, which only has the three letter code "fil".

NOTE: Filipino is slightly different from Tagalog.

Steps to reproduce:
1. Go to the &ltg;&ltg;Languages for "tinymce">> page
2. Add a new language
3. Enter a three letter language code for the new language
4. Fill out the rest of the fields
5. Click "Create"

Expected result:
The new language is created

Actual result:
An error message saying "Language Code seems to be wrong, recheck and try again."

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7646](http://archive.tinymce.com/develop/bugtracker_view.php?id=7646) posted by [popeyoni](http://archive.tinymce.com/profile.php?name=popeyoni)_
> 
> _**Tags:** [firefox msie safari chrome translations languages]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
