### ISSUE TITLE
Add Column Before/After will add a column to all tables if table has more tables within it

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2354]
Description of problem:

Steps to reproduce:
1. Insert a 2 column table 
2. Insert a table inside first cell
3. Go to a sibling cell of the parent table and insert a column before/after

Expected result:
 Column should be added only to the table where the caret is positioned

Actual result:
 Column is also being added to all tables inside the parent table

This is only happening to the next sibling cell, if you add a 3 column table. Put the table in the 1st cell, and add a column placing caret in 3rd cell, it won't happen.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7647](http://archive.tinymce.com/develop/bugtracker_view.php?id=7647) posted by [msqar](http://archive.tinymce.com/profile.php?name=msqar)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
