### ISSUE TITLE
setRng issue with Edge in 4.2.X

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2355]
Description of problem:

We had a plugin that used touch and pointer events that allowed you to drag an image inside of tinyMCE with your finger or a stylus. This plugin was working fine in iOS, Android, Firefox for Android, and IE10/11 on 8/8.1.

In Edge it seems that programmatically creating a range using caretRangeFromPoint and then inserting content (the originally dragged image) into the range and then placing that range back into the selection using setRng will not cause the range to appear. It appears to move all the way up to the HTML element most of the time, though sometimes it says the 

Addendum: it seems the issue only occurs when:

1) You have multiple editors on one page.
2) The editors are floated (VERY important)

You can detect and work-around this issue by checking the range's commonAncestorContainer to see if it /its parent match the elementFromPoint from the X/Y point. The detection and work-around are included.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7648](http://archive.tinymce.com/develop/bugtracker_view.php?id=7648) posted by [powrsurg](http://archive.tinymce.com/profile.php?name=powrsurg)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://powrsurg.com/work/tinymce/index4.html_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
