### ISSUE TITLE
Copy paste using Keyboard creates a new line in Firefox

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2357]
Description of problem:
Copy paste using Keyboard created a new line in Firefox

Steps to reproduce:
1. Write something in the editor ("Hello World")
2. Press Ctrl+A to select everything
3. Press Ctrl+C to copy
4. Press Ctrl+V to paste

Expected result:
Copied line should be pasted right after copied text.
Example: 
Hello worldHello worldHello world

Actual result:
Copied line will be pasted in a new line every time.
Example: 
Hello world

Hello world

Hello world
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7654](http://archive.tinymce.com/develop/bugtracker_view.php?id=7654) posted by [ananto](http://archive.tinymce.com/profile.php?name=ananto)_

> _**Tags:** [firefox firefox]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
