### ISSUE TITLE
Clicking editor borders opens edit menu automatically

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2359]
Description of problem:
We are using tinymce in our CMS, and we load tinymce into a bootstrap modal. The cms has some theme and utility css files, but I have removed those and still get the same problem.

If I click anywhere on the tinymce user interface border, except for the content box or other editor buttons, it causes the edit menu to open. In the fiddle provided, we use the small-block-grid-* class styles for responsive sites. In order to apply these style formats to the proper html element ( ul ) we use the "breadcrumb" at the bottom of the editor to select the UL and then apply the style. But when we click the ul in the breadcrumb, the edit menu opens.

Steps to reproduce:
1. load the TinyMCE into a bootstrap modal
2. click anywhere on the border
3. observe as the edit menu opens.

Expected result:
The edit menu, or any other menu item should not open

Actual result:
The edit menu opens.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7652](http://archive.tinymce.com/develop/bugtracker_view.php?id=7652) posted by [HunterJoe](http://archive.tinymce.com/profile.php?name=HunterJoe)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/HunterJoe/Lf1j5znx/2/_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
