### ISSUE TITLE
tinymce_4.2.3 is not responsive

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2360]
Description of problem: not responsive

Steps to reproduce:
1.Open source code
2.And source code pop up is not 100% width, especially on mobile pixels.
3.Try to re-size the browser, and found source pop up cannot be less than 320px for mobile purpose edit mode.

Expected result: source code is responsive to smartphones, tabs, and desktop pixel width.

Actual result: source code is not responsive to smartphones.

Thank you

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7653](http://archive.tinymce.com/develop/bugtracker_view.php?id=7653) posted by [tzar](http://archive.tinymce.com/profile.php?name=tzar)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
