### ISSUE TITLE
Formatting bugs on some special cases

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2362]
Description of problem:
There are some special cases with the combination of pasted text and highlight to unbold the selected text will cause the next formatting actions after it not working correctly. Can also be reproduced using the tinymce.com example.

Steps to reproduce:
1. Please refer to the attached .gif file for the exact steps on how to reproduce it.

Expected result:
The formatting (italic in this case) should only be applied to the selected text instead of the unselected one.

Actual result:
The formatting (italic in this case) is applied to the unselected text.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7656](http://archive.tinymce.com/develop/bugtracker_view.php?id=7656) posted by [siangsin](http://archive.tinymce.com/profile.php?name=siangsin)_

> _**Tags:** [firefox msie safari chrome formatting paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
