### ISSUE TITLE
imageUpload - callback also on fail?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2364]
At the end I have to wait anyway for the callback of imageUpload. I would appreciate to have triggered the callback on fail also, where I could show a msg or cleanup something.
But still.. a nice enhancement.
regards manu

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7658](http://archive.tinymce.com/develop/bugtracker_view.php?id=7658) posted by [manu37](http://archive.tinymce.com/profile.php?name=manu37)_
> 
> _**Tags:** [plugin imageupload]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
