### ISSUE TITLE
imageUpload - retain original file name

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2365]
How about to retain the original file name in an attribute? And then upload with this name? Handling of duplicates could be done anyway on server side.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7659](http://archive.tinymce.com/develop/bugtracker_view.php?id=7659) posted by [manu37](http://archive.tinymce.com/profile.php?name=manu37)_
> 
> _**Tags:** [imageupload]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
