### ISSUE TITLE
Some language can't be typed  in table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2371]
Description of problem:

Some languages which require conversion by IME such as Chinese, Japanese, etc can not be typed in a table.

This problem occur in IE11.

Steps to reproduce:
1. insert table
2. click a cell
3. type Japanese words
4. the word  is input without conversion

Expected result: the word can be converted
Actual result: the word  is input without conversion

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7665](http://archive.tinymce.com/develop/bugtracker_view.php?id=7665) posted by [roy123](http://archive.tinymce.com/profile.php?name=roy123)_
> 
> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Xiphe** [comment]
I can confirm this bug. 

Steps to reproduce on Windows + IE11

- Install Japanese keyboard
- use Hiragana input method
- add a table in tinymce
- press keys `h` and `o`
- see `h` + `お` (`ほ` would be correct)
- use any other input to see the correct behaviour


_Disclaimer: i can't speak Japanese and don't know what i've written, used that just as an illustration of the problem_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
