### ISSUE TITLE
Image is not displaying if I copy the image from my google docs

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2375]
Description of problem:

Steps to reproduce:
1. Copy the content from Google Docs.(content must have an image.)
2. Paste it into tinyMCE editor 4.2.4 version.
3. Image is not available.

Expected result:
Image must be available
Actual result:
Image is not available. Looks like image is being stripped of by TinyMCE.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7669](http://archive.tinymce.com/develop/bugtracker_view.php?id=7669) posted by [Amardeep](http://archive.tinymce.com/profile.php?name=Amardeep)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by ca2hill** [comment]
Seeing the same problem, is this going to get fixed.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
