### ISSUE TITLE
Adding a Hyperlink to Bold/Italic text removes formatting

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2378]
Description of problem:

Steps to reproduce:
1. Add a plain text word ("hello").
2. Highlight it and make it bold.
3. Un-highlight it so the cursor blinks somewhere after the word.
4. Re-highlight the entire (single) word.
5. click the "link" button to add a link to the highlighted word.

Expected result:

"hello" should be a link and still bold.

Actual result:
"hello" is a link but no longer bold. 

This also only seems to happen when adding links to single words: For multi word links the formatting appears to persist as expected.

Also reproducible when formatting with italics. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7674](http://archive.tinymce.com/develop/bugtracker_view.php?id=7674) posted by [Sushicoma](http://archive.tinymce.com/profile.php?name=Sushicoma)_
> 
> _**Tags:** [firefox msie safari chrome formatting links]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com_

**Comment by mcavalletto** [comment]
We're hitting this problem as well.

Unlike the first comment above, this does seem to affect multiple word selections, and unlike the second comment it doesn't require that the formatting and the hyperlink are exactly matching -- in my tests here, the key characteristic appears to be that the link starts at the same character positions as the formatting does.

**Comment by fyrkant** [comment]
@mcavalletto Are you still having this issue with the latest version of TinyMCE (4.6.2)?

**Comment by mcavalletto** [comment]
No, seems fixed now, thanks!
