### ISSUE TITLE
no border option for tinymce4

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2380]
When following readonly mode , I would like to remove borders of editor.

---

readonly : true,
statusbar : false,
toolbar : false,
menubar: false,

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7672](http://archive.tinymce.com/develop/bugtracker_view.php?id=7672) posted by [roy123](http://archive.tinymce.com/profile.php?name=roy123)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
