### ISSUE TITLE
Paste from word option

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2384]
Paste from word option does not retain style properties of text copied from MS-Word. It copies formatted text. Can you please guide on this?

Thanks,
Shweta

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7678](http://archive.tinymce.com/develop/bugtracker_view.php?id=7678) posted by [shweta.kharade](http://archive.tinymce.com/profile.php?name=shweta.kharade)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
We've looked into this, and believe this is related to #2083. Could you please take a look and let us know if you agree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
