### ISSUE TITLE
Text pasted from notepad with hard returns breaks heading styles 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2387]
Description of problem:
When you copy paste text from notepad into the editor, the heading styles in tables gets broken if the pasted text had any hard return (2 line breaks together) in it.
To the heading, appends &ltg;font> dom element and sometimes a &ltg;span> element, making the original h1 lose their original styling.

Steps to reproduce:
1. Create a table with X number of cells and rows
2. Write a text with Heading 1
3. Go to notepad and write a text like this:

asdasd

asd
asd
sa

asd

asd

4. Copy all that and paste it anywhere inside the editor
5. You will see that the old Heading 1 you placed inside the table was broken. Check the HTML view and see for yourself how it added the font and span (sometimes) inside the h1 tag.

Expected result:
It shouldn't be modifying the HTML

Actual result:
It breaks the heading styles for example of the content inside tables.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7681](http://archive.tinymce.com/develop/bugtracker_view.php?id=7681) posted by [msqar](http://archive.tinymce.com/profile.php?name=msqar)_

> _**Tags:** [table cell notepad copypaste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/classic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
