### ISSUE TITLE
bullet is not working well

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2388]
Description of problem:

Steps to reproduce:
1.Apply the Email signature on the tinymce 4.2.5 and Type the 2 sentences.
2.Select the second sentence and align right and put the bullet.
3.Then select the First sentence and also align right and select all Two sentences and align right and put the bullets.
4.It makes 3 bullets and abnormal alignment - This is an Issue.
5.

Expected result:We need correct alignment and particular bullets only while set the Email signature.

Actual result: Abnormal alignment and extra bullets and new line sapcing is created.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7682](http://archive.tinymce.com/develop/bugtracker_view.php?id=7682) posted by [suthakar](http://archive.tinymce.com/profile.php?name=suthakar)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
