### ISSUE TITLE
Copy Table from Excel with Inline Optrion set to true

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2391]
Some tables copied from Excel does not preserve the formatting .

This happens when the initialization tinyMCE inline attribute is set to true.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7683](http://archive.tinymce.com/develop/bugtracker_view.php?id=7683) posted by [rvannini](http://archive.tinymce.com/profile.php?name=rvannini)_
> 
> _**Tags:** [firefox msie safari chrome inline excel copy table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
We've looked into this and believe this to be a duplicate of #2756. Could you please have a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
