### ISSUE TITLE
Character Count and Limit Plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2392]
Hi

In CKEditor, there is a plugin that does both word and character counting (http://w8tcha.github.io/CKEditor-WordCount-Plugin/). Will there be a character counting one for TinyMCE?

The reason I ask is for SEO purposes. I allow my clients to add keyword and description tags. These are best kept around 255 characters.

So having a plugin that displays the character count as they type would be very useful. Also some text zones need to be kept within a certain limit, so having a limit on either words or characters would be awesome.

Cheers
G

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7690](http://archive.tinymce.com/develop/bugtracker_view.php?id=7690) posted by [gwow](http://archive.tinymce.com/profile.php?name=gwow)_
> 
> _**Tags:** [character count plugin seo description tag keyword limit]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by nori-h** [comment]
I believe this is a duplicate to #2059. Could you please have a look and let us know if not? Thanks, Nori @ TinyMCE

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Comment by naXa777** [comment]
See this question on StackOverflow https://stackoverflow.com/q/34481959/1429387
Or this gist on GistHub https://gist.github.com/ClementParis016/ab06847c41160c22f278e4cabe4a0879
