### ISSUE TITLE
misplaced HTML variables({repeater_start},{repeater_end} at the time of clicking 'update' button of 'Edit HTML Source' 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2394]
Description of problem:
------------------------
misplaced HTML variables({repeater_start},{repeater_end} at the time of clicking 'update' button of 'Edit HTML Source' using tinymce editor.

Expected result:
------------------
&ltg;div style="width: 700px; margin: 0px auto; font-family: Arial,Helvetica,sans-serif;"> &ltg;table style="width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0"> &ltg;tbody> &ltg;tr> &ltg;td align="left" height="69" valign="bottom" width="160">{logo_pdf}&ltg;/td> &ltg;td style="color: #000; font-size: 14px;" align="right" height="30" valign="middle" width="555">Invoice # : {invoices.name}&ltg;/td> &ltg;/tr> &ltg;tr style="height: 22px;"> &ltg;td colspan="2" style="color: #0073ae; font-size: 21px; font-weight: bold; border-bottom: 4px solid #656A6D;" align="right" height="25" valign="middle">&ltg;strong>{invoices.name}&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;table style="font-family: Arial,Helvetica,sans-serif; margin-top: 5px; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0"> &ltg;tbody> &ltg;tr> &ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="100">Account Name&ltg;/td> &ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="5">:&ltg;/td> &ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="390">&ltg;strong style="font-size: 13px;">&nbsp;{invoices.account_id}&ltg;/strong>&ltg;/td>
&ltg;td style="font-size: 14px;" align="right" height="20" valign="top" width="206">Date : &ltg;strong>{invoices.invoice_date} &ltg;/strong>&ltg;/td> &ltg;/tr> &ltg;tr> &ltg;td style="font-size: 14px;" align="left" height="20" width="100">Contact Name&ltg;/td> &ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="5">:&ltg;/td> &ltg;td colspan="2" style="font-size: 14px;" align="left" height="20" width="596">&ltg;strong>&nbsp;{invoices.contact_id}&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="font-size: 14px;" align="left" height="20" width="100">Deal Name&ltg;/td> &ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="5">:&ltg;/td> &ltg;td colspan="2" style="font-size: 14px;" align="left" height="20" width="596">&ltg;strong>&nbsp;{invoices.deal_id}&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;br>
&ltg;table style="padding: 0px; margin: 0px; font-family: Arial,Helvetica,sans-serif; width: 700px;" bordercolor="#656A6D" cellpadding="0" cellspacing="0"> &ltg;tbody> &ltg;tr> &ltg;td width="330">&ltg;span style="font-size: 14px; font-family: Arial,Helvetica,sans-serif normal;" face="Arial, Helvetica, sans-serif normal">Bill To &ltg;br>&ltg;/span>&ltg;/td> &ltg;td width="17">&nbsp;&ltg;/td> &ltg;td width="330">&ltg;span style="font-size: 14px; font-family: Arial,Helvetica,sans-serif normal;" face="Arial, Helvetica, sans-serif normal">Ship To &ltg;br>&ltg;/span>&ltg;/td> &ltg;/tr> &ltg;tr> &ltg;td style="border: 1px solid #656A6D; padding: 10px 0 0px 10px; font-size: 12px;" bgcolor="#F3F3F4" height="65" width="327"> {invoices.billing_address_street}&ltg;br>

{invoices.billing_address_street_2}&ltg;br>

{invoices.billing_address_city}&ltg;br>

{invoices.billing_address_state}&ltg;br>

{invoices.billing_address_postalcode}&ltg;br>

{invoices.billing_address_country}
&ltg;/td>
&ltg;td width="17">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #656A6D; padding: 10px 0 0px 10px; font-size: 12px;" bgcolor="#F3F3F4" height="65" width="327"> {invoices.shipping_address_street}&ltg;br>

{invoices.shipping_address_street_2}&ltg;br>

{invoices.shipping_address_city}&ltg;br>

{invoices.shipping_address_state}&ltg;br>

{invoices.shipping_address_postalcode}&ltg;br>

{invoices.shipping_address_country}
&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;br>
&ltg;table style="font-family: Arial,Helvetica,sans-serif; font-size: 13px; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0"> &ltg;tbody> &ltg;tr> &ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" bgcolor="#D2D3D5" height="22" valign="middle" width="200">&ltg;strong>&nbsp;&nbsp;Task/Product&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" align="center" bgcolor="#D2D3D5" height="22" valign="middle" width="95">&ltg;strong>Rate&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" align="center" bgcolor="#D2D3D5" height="22" valign="middle" width="95">&ltg;strong>Hours/Qty&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" align="center" bgcolor="#D2D3D5" height="22" valign="middle" width="95">&ltg;strong>Tax&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" align="center" bgcolor="#D2D3D5" height="22" valign="middle" width="95">&ltg;strong>Tax&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;td style="font-size: 14px; border: 1px solid #656A6D;" align="right" bgcolor="#D2D3D5" height="22" valign="middle" width="103">&ltg;strong>Line Total ({invoices.currency})&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;/tr>
{invoices.repeater_start}
&ltg;tr bgcolor="#F3F3F4">
&ltg;td style="border-left: 1px solid #656A6D; font-size: 12px;" height="20" valign="middle" width="200">&nbsp;&nbsp;{invoices.product}&ltg;/td>
&ltg;td style="font-size: 12px; border-left: 1px solid #656A6D;" align="center" height="20" valign="middle" width="95">{invoices.list_price}&ltg;/td>
&ltg;td style="font-size: 12px; border-left: 1px solid #656A6D;" align="center" height="20" valign="middle" width="95">{invoices.quantity}&ltg;/td>
&ltg;td style="font-size: 12px; border-left: 1px solid #656A6D;" align="center" height="20" valign="middle" width="95">{invoices.tax_1}&ltg;/td> &ltg;td style="font-size: 12px; border-left: 1px solid #656A6D;" align="center" height="20" valign="middle" width="95">{invoices.tax_2}&ltg;/td> &ltg;td style="border-left: 1px solid #656A6D; border-right: 1px solid #656A6D; font-size: 12px;" align="right" height="20" valign="middle" width="103">{invoices.total}&nbsp;&ltg;/td>
&ltg;/tr>
{invoices.repeater_end}
&ltg;tr bgcolor="#F3F3F4">
&ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="200">&nbsp;&ltg;/td> &ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="95">&nbsp;&ltg;/td> &ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="95">&nbsp;&ltg;/td> &ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="95">&nbsp;&ltg;/td> &ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="95">&nbsp;&ltg;/td> &ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D; border-right: 1px solid #656A6D;" width="103">&nbsp;&ltg;/td> &ltg;/tr> &ltg;/tbody> &ltg;/table> &ltg;br> &ltg;table style="font-family: Arial,Helvetica,sans-serif; font-size: 12px; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0"> &ltg;tbody> &ltg;tr> &ltg;td height="20" valign="middle" width="485">&ltg;strong style="font-size: 14px;">Questions?&ltg;/strong>&ltg;/td> &ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Subtotal&ltg;/td>
&ltg;td style="border-left: 1px solid #656A6D; border-top: 1px solid #656A6D; border-right: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">{invoices.sub_total}&nbsp;&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td height="20" width="485">&ltg;span style="font-size: 12px;">Contact us at {accountsettings.name} {accountsettings.phone} or &ltg;/span>&ltg;a href="mailto:{invoices.company_email}">{accountsettings.email}&ltg;/a>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Total discount&ltg;/td> &ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-right: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">(-) {invoices.discount}&nbsp;&ltg;/td> &ltg;/tr> &ltg;tr> &ltg;td>&nbsp;&ltg;/td> &ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Total tax&ltg;/td> &ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-right: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">(+){invoices.tax}&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Shipping Cost&ltg;/td> &ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-right: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">{invoices.shipping_cost}&nbsp;&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Adjustments&ltg;/td>
&ltg;td style="border: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">{invoices.adjustment_type} {invoices.adjustment}&nbsp;&ltg;/td> &ltg;/tr> &ltg;tr> &ltg;td width="485">&nbsp;&ltg;/td> &ltg;td align="left" height="20" valign="middle" width="115">&ltg;strong style="font-size: 15px; line-height: 35px;">TOTAL&ltg;/strong> &nbsp;&ltg;/td> &ltg;td align="right" valign="middle" width="103">&ltg;strong style="font-size: 15px;">{invoices.currency_id}{invoices.grand_total}&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td align="left" height="20" valign="middle" width="115">&ltg;strong style="font-size: 15px; line-height: 35px;">Paid Amount&ltg;/strong> &nbsp;&ltg;/td> &ltg;td align="right" valign="middle" width="103">&ltg;strong style="font-size: 15px;">{invoices.currency_id}{invoices.paid_amount}&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td align="left" height="20" valign="middle" width="115">&ltg;strong style="font-size: 15px; line-height: 35px;">Balance Due&ltg;/strong> &nbsp;&ltg;/td> &ltg;td align="right" valign="middle" width="103">&ltg;strong style="font-size: 15px;">{invoices.currency_id}{invoices.due_amount}&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;br>
&ltg;table style="padding: 0px; margin: 0px; font-family: Arial,Helvetica,sans-serif; font-size: 13px; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0"> &ltg;tbody> &ltg;tr> &ltg;td style="font-size: 14px;" align="left" width="715">&ltg;strong>Terms &amp; Condition:&ltg;/strong>&ltg;/td> &ltg;/tr> &ltg;tr> &ltg;td style="font-size: 11px;" align="left" width="715">{invoices.terms_conditions}&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td align="left" height="20" width="715">&nbsp;&ltg;/td> &ltg;/tr> &ltg;tr> &ltg;td style="font-size: 14px;" align="left" width="715">&ltg;strong>Notes:&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="font-size: 11px;" align="left" width="700">{invoices.description}&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;table style="padding: 0px; margin: 0px; font-family: Arial,Helvetica,sans-serif; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0"> &ltg;tbody> &ltg;tr> &ltg;td align="left" valign="top" width="180">&nbsp;&ltg;/td> &ltg;td align="left" valign="top" width="40">&nbsp;&ltg;/td> &ltg;td align="left" valign="top" width="180">&nbsp;&ltg;/td> &ltg;td align="left" valign="top" width="85">&nbsp;&ltg;/td> &ltg;td style="font-weight: bold; font-size: 16px;" align="right" valign="middle" width="218">&ltg;strong>{accountsettings.name}&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>&ltg;td align="left" valign="top" width="180">&nbsp;&ltg;/td> &ltg;td align="left" valign="top" width="40">&nbsp;&ltg;/td> &ltg;td align="left" valign="top" width="180">&nbsp;&ltg;/td> &ltg;td align="left" valign="top" width="85">&nbsp;&ltg;/td> 
 &ltg;td style="font-size: 12px;" align="right" valign="top" width="218" rowspan="2">&ltg;span style="font-size: 12px;">{accountsettings.primary_address_street}&ltg;br>
 {accountsettings.primary_address_street_2}&ltg;br>
 {accountsettings.primary_address_city}&ltg;br>
 {accountsettings.primary_address_postalcode}&ltg;br>
 {accountsettings.primary_address_state}&ltg;br>
 {accountsettings.primary_address_country}&ltg;/span>&ltg;/td>
&ltg;/tr>
  &ltg;/tbody> &ltg;/table> &ltg;/div>

Actual result:
---------------
&ltg;div style="width: 700px; margin: 0px auto; font-family: Arial,Helvetica,sans-serif;">
&ltg;table style="width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0">
&ltg;tbody>
&ltg;tr>
&ltg;td align="left" height="69" valign="bottom" width="160">{logo_pdf}&ltg;/td>
&ltg;td style="color: #000; font-size: 14px;" align="right" height="30" valign="middle" width="555">Invoice # : {invoices.name}&ltg;/td>
&ltg;/tr>
&ltg;tr style="height: 22px;">
&ltg;td colspan="2" style="color: #0073ae; font-size: 21px; font-weight: bold; border-bottom: 4px solid #656A6D;" align="right" height="25" valign="middle">&ltg;strong>{invoices.name}&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;table style="font-family: Arial,Helvetica,sans-serif; margin-top: 5px; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0">
&ltg;tbody>
&ltg;tr>
&ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="100">Account Name&ltg;/td>
&ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="5">:&ltg;/td>
&ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="390">&ltg;strong style="font-size: 13px;">&nbsp;{invoices.account_id}&ltg;/strong>&ltg;/td>
&ltg;td style="font-size: 14px;" align="right" height="20" valign="top" width="206">Date : &ltg;strong>{invoices.invoice_date} &ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="font-size: 14px;" align="left" height="20" width="100">Contact Name&ltg;/td>
&ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="5">:&ltg;/td>
&ltg;td colspan="2" style="font-size: 14px;" align="left" height="20" width="596">&ltg;strong>&nbsp;{invoices.contact_id}&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="font-size: 14px;" align="left" height="20" width="100">Deal Name&ltg;/td>
&ltg;td style="font-size: 14px;" align="left" height="20" valign="top" width="5">:&ltg;/td>
&ltg;td colspan="2" style="font-size: 14px;" align="left" height="20" width="596">&ltg;strong>&nbsp;{invoices.deal_id}&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;br />
&ltg;table style="padding: 0px; margin: 0px; font-family: Arial,Helvetica,sans-serif; width: 700px;" bordercolor="#656A6D" cellpadding="0" cellspacing="0">
&ltg;tbody>
&ltg;tr>
&ltg;td width="330">&ltg;span style="font-size: 14px; font-family: Arial,Helvetica,sans-serif normal;" face="Arial, Helvetica, sans-serif normal">Bill To &ltg;br />&ltg;/span>&ltg;/td>
&ltg;td width="17">&nbsp;&ltg;/td>
&ltg;td width="330">&ltg;span style="font-size: 14px; font-family: Arial,Helvetica,sans-serif normal;" face="Arial, Helvetica, sans-serif normal">Ship To &ltg;br />&ltg;/span>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="border: 1px solid #656A6D; padding: 10px 0 0px 10px; font-size: 12px;" bgcolor="#F3F3F4" height="65" width="327">{invoices.billing_address_street}&ltg;br /> {invoices.billing_address_street_2}&ltg;br /> {invoices.billing_address_city}&ltg;br /> {invoices.billing_address_state}&ltg;br /> {invoices.billing_address_postalcode}&ltg;br /> {invoices.billing_address_country}&ltg;/td>
&ltg;td width="17">&nbsp;&ltg;/td>
&ltg;td style="border: 1px solid #656A6D; padding: 10px 0 0px 10px; font-size: 12px;" bgcolor="#F3F3F4" height="65" width="327">{invoices.shipping_address_street}&ltg;br /> {invoices.shipping_address_street_2}&ltg;br /> {invoices.shipping_address_city}&ltg;br /> {invoices.shipping_address_state}&ltg;br /> {invoices.shipping_address_postalcode}&ltg;br /> {invoices.shipping_address_country}&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;br />{invoices.repeater_start}{invoices.repeater_end}
&ltg;table style="font-family: Arial,Helvetica,sans-serif; font-size: 13px; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0">
&ltg;tbody>
&ltg;tr>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" bgcolor="#D2D3D5" height="22" valign="middle" width="200">&ltg;strong>&nbsp;&nbsp;Task/Product&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" align="center" bgcolor="#D2D3D5" height="22" valign="middle" width="95">&ltg;strong>Rate&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" align="center" bgcolor="#D2D3D5" height="22" valign="middle" width="95">&ltg;strong>Hours/Qty&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" align="center" bgcolor="#D2D3D5" height="22" valign="middle" width="95">&ltg;strong>Tax&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D; font-size: 14px;" align="center" bgcolor="#D2D3D5" height="22" valign="middle" width="95">&ltg;strong>Tax&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;td style="font-size: 14px; border: 1px solid #656A6D;" align="right" bgcolor="#D2D3D5" height="22" valign="middle" width="103">&ltg;strong>Line Total ({invoices.currency})&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr bgcolor="#F3F3F4">
&ltg;td style="border-left: 1px solid #656A6D; font-size: 12px;" height="20" valign="middle" width="200">&nbsp;&nbsp;{invoices.product}&ltg;/td>
&ltg;td style="font-size: 12px; border-left: 1px solid #656A6D;" align="center" height="20" valign="middle" width="95">{invoices.list_price}&ltg;/td>
&ltg;td style="font-size: 12px; border-left: 1px solid #656A6D;" align="center" height="20" valign="middle" width="95">{invoices.quantity}&ltg;/td>
&ltg;td style="font-size: 12px; border-left: 1px solid #656A6D;" align="center" height="20" valign="middle" width="95">{invoices.tax_1}&ltg;/td>
&ltg;td style="font-size: 12px; border-left: 1px solid #656A6D;" align="center" height="20" valign="middle" width="95">{invoices.tax_2}&ltg;/td>
&ltg;td style="border-left: 1px solid #656A6D; border-right: 1px solid #656A6D; font-size: 12px;" align="right" height="20" valign="middle" width="103">{invoices.total}&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr bgcolor="#F3F3F4">
&ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="200">&nbsp;&ltg;/td>
&ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="95">&nbsp;&ltg;/td>
&ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="95">&nbsp;&ltg;/td>
&ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="95">&nbsp;&ltg;/td>
&ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D;" width="95">&nbsp;&ltg;/td>
&ltg;td style="border-bottom: 1px solid #656A6D; border-left: 1px solid #656A6D; border-right: 1px solid #656A6D;" width="103">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;br />
&ltg;table style="font-family: Arial,Helvetica,sans-serif; font-size: 12px; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0">
&ltg;tbody>
&ltg;tr>
&ltg;td height="20" valign="middle" width="485">&ltg;strong style="font-size: 14px;">Questions?&ltg;/strong>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Subtotal&ltg;/td>
&ltg;td style="border-left: 1px solid #656A6D; border-top: 1px solid #656A6D; border-right: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">{invoices.sub_total}&nbsp;&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td height="20" width="485">&ltg;span style="font-size: 12px;">Contact us at {accountsettings.name} {accountsettings.phone} or &ltg;/span>&ltg;a href="mailto:{invoices.company_email}">{accountsettings.email}&ltg;/a>&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Total discount&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-right: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">(-) {invoices.discount}&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td>&nbsp;&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Total tax&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-right: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">(+){invoices.tax}&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Shipping Cost&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-right: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">{invoices.shipping_cost}&nbsp;&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td style="border-top: 1px solid #656A6D; border-left: 1px solid #656A6D; border-bottom: 1px solid #656A6D;" align="left" bgcolor="#F3F3F4" height="20" valign="middle" width="115">&nbsp;&nbsp;Adjustments&ltg;/td>
&ltg;td style="border: 1px solid #656A6D;" align="right" bgcolor="#F3F3F4" valign="middle" width="103">{invoices.adjustment_type} {invoices.adjustment}&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td align="left" height="20" valign="middle" width="115">&ltg;strong style="font-size: 15px; line-height: 35px;">TOTAL&ltg;/strong> &nbsp;&ltg;/td>
&ltg;td align="right" valign="middle" width="103">&ltg;strong style="font-size: 15px;">{invoices.currency_id}{invoices.grand_total}&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td align="left" height="20" valign="middle" width="115">&ltg;strong style="font-size: 15px; line-height: 35px;">Paid Amount&ltg;/strong> &nbsp;&ltg;/td>
&ltg;td align="right" valign="middle" width="103">&ltg;strong style="font-size: 15px;">{invoices.currency_id}{invoices.paid_amount}&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td width="485">&nbsp;&ltg;/td>
&ltg;td align="left" height="20" valign="middle" width="115">&ltg;strong style="font-size: 15px; line-height: 35px;">Balance Due&ltg;/strong> &nbsp;&ltg;/td>
&ltg;td align="right" valign="middle" width="103">&ltg;strong style="font-size: 15px;">{invoices.currency_id}{invoices.due_amount}&nbsp;&nbsp;&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;br />
&ltg;table style="padding: 0px; margin: 0px; font-family: Arial,Helvetica,sans-serif; font-size: 13px; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0">
&ltg;tbody>
&ltg;tr>
&ltg;td style="font-size: 14px;" align="left" width="715">&ltg;strong>Terms &amp; Condition:&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="font-size: 11px;" align="left" width="715">{invoices.terms_conditions}&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td align="left" height="20" width="715">&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="font-size: 14px;" align="left" width="715">&ltg;strong>Notes:&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td style="font-size: 11px;" align="left" width="700">{invoices.description}&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;table style="padding: 0px; margin: 0px; font-family: Arial,Helvetica,sans-serif; width: 700px;" border="0" bordercolor="#656A6D" cellpadding="0" cellspacing="0">
&ltg;tbody>
&ltg;tr>
&ltg;td align="left" valign="top" width="180">&nbsp;&ltg;/td>
&ltg;td align="left" valign="top" width="40">&nbsp;&ltg;/td>
&ltg;td align="left" valign="top" width="180">&nbsp;&ltg;/td>
&ltg;td align="left" valign="top" width="85">&nbsp;&ltg;/td>
&ltg;td style="font-weight: bold; font-size: 16px;" align="right" valign="middle" width="218">&ltg;strong>{accountsettings.name}&ltg;/strong>&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td align="left" valign="top" width="180">&nbsp;&ltg;/td>
&ltg;td align="left" valign="top" width="40">&nbsp;&ltg;/td>
&ltg;td align="left" valign="top" width="180">&nbsp;&ltg;/td>
&ltg;td align="left" valign="top" width="85">&nbsp;&ltg;/td>
&ltg;td style="font-size: 12px;" align="right" valign="top" width="218" rowspan="2">&ltg;span style="font-size: 12px;">{accountsettings.primary_address_street}&ltg;br /> {accountsettings.primary_address_street_2}&ltg;br /> {accountsettings.primary_address_city}&ltg;br /> {accountsettings.primary_address_postalcode}&ltg;br /> {accountsettings.primary_address_state}&ltg;br /> {accountsettings.primary_address_country}&ltg;/span>&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>
&ltg;/div>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7684](http://archive.tinymce.com/develop/bugtracker_view.php?id=7684) posted by [Sujata](http://archive.tinymce.com/profile.php?name=Sujata)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
