### ISSUE TITLE
TinyMCE Editor not working with Google Meterial Light framwork

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2395]
When TinyMCE using with GOogle Meterial Design Light (http://www.getmdl.io/) Layout. TinyMCE stop responding. 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7686](http://archive.tinymce.com/develop/bugtracker_view.php?id=7686) posted by [nmondal28](http://archive.tinymce.com/profile.php?name=nmondal28)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Verified_
> _**Resolution:** Later_
> _**Attached URL:** http://fiddle.tinymce.com/GZeaab_

**Comment by fdkhadra** [comment]
Hi,
This is my workaround for the moment, can be useful for others widget that conflict with mdl-js-layout

```javascript
document.addEventListener('mdl-componentupgraded', function(e){
  tinymce.init({
    selector: 'textarea'
  });
});
```
Maybe it will be safer to check first that the layout is correctly updated before initialize TinyMce

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
