### ISSUE TITLE
Accessibility features for the blind are unavailable on a Mac

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2396]
Description of problem: 
The accessibility of TinyMCE is wonderful�but only if you use a PC. There is no support for Safari and Mac OS X, which is the only operating system to natively include full text-to-speech accessibility used by blind people. The keyboard shortcuts (using option or control instead of alt) do not activate, and it requires several levels of "start interacting"/"stop interacting"�and even so, the VoiceOver cursor frequently loses focus.
Expected result:

Certainly I can access the raw source code but this defeats the purpose of TinyMCE! To do so, though, interact with the toolbar, go to the source code button and enter that popover. At that point, the VoiceOver focus jumps to the "save" button�not the beginning of the text area. Even so, there is no fast/easy way to get to that toolbar button. 

Actual result:
At best, users can read but not edit content in the area. At worst, VoiceOver crashes, reboots automatically and loses focus.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7696](http://archive.tinymce.com/develop/bugtracker_view.php?id=7696) posted by [oconsulting](http://archive.tinymce.com/profile.php?name=oconsulting)_
> 
> _**Tags:** [firefox msie safari chrome accessibility keyboard shortcuts]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by church29** [comment]
Even if you do manage to access the toolbar on OS X, the voiceover is not very helpful. It will read "selected, button" every time. All of the aria labels are on the parent div rather than the button element itself.
<img width="1298" alt="screen shot 2016-05-18 at 9 35 17 am" src="https://cloud.githubusercontent.com/assets/3653981/15367049/1064f12c-1cdc-11e6-8bfd-bca491e3fb53.png">

**Comment by fyrkant** [comment]
@church29 The button accessibility has been improved now since ... 4.6.0 I think? I forgot exactly what version, but it should read what the button does now also. 

Closing this issue but can open it up if anyone has something else to say, just leave a comment!
