### ISSUE TITLE
Possible exception not caught at getRng 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2399]
Description of problem:
In IE11 an exception in the getRng function leads to a stuck application/browser.
The function should return an empty Range object if any exception occurs.

Steps to reproduce:
1. call setStart with invalid argument
2. looks like TinyMCE tries to call the same function over and over again but fails every time.

15386         /**
15387          \* Returns the browsers internal range object.
15388          *
15389          \* @method getRng
15390          \* @param {Boolean} w3c Forces a compatible W3C range on IE.
15391          \* @return {Range} Internal browser range object.
15392          \* @see http://www.quirksmode.org/dom/range_intro.html
15393          \* @see http://www.dotvoid.com/2001/03/using-the-range-object-in-mozilla/
15394          */
15395         getRng: function(w3c) {
15396             var self = this, selection, rng, elm, doc = self.win.document, ieRng;
15397 
[...]
15410 
15411             // Use last rng passed from FocusManager if it's available this enables
15412             // calls to editor.selection.getStart() to work when caret focus is lost on IE
15413             if (!w3c && self.lastFocusBookmark) {
15414                 var bookmark = self.lastFocusBookmark;
15415 
15416                 // Convert bookmark to range IE 11 fix
15417                 if (bookmark.startContainer) {
15418                     rng = doc.createRange();
15419                     rng.setStart(bookmark.startContainer, bookmark.startOffset);  &ltg;--- Exception here!
15420                     rng.setEnd(bookmark.endContainer, bookmark.endOffset);
15421                 } else {
15422                     rng = bookmark;
15423                 }
15424 
15425                 return rng;
15426             }

Expected result:
get an empty Range Object

Actual result:
Browser/Application crashed/stuck

Solution:
Surrounded the If block with try/catch.
Got the idea with try/catch from this post:
http://www.tinymce.com/develop/bugtracker_view.php?id=6797

IE11 Version: 11.0.10240.16431
Updateversion: 11.0.22

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7692](http://archive.tinymce.com/develop/bugtracker_view.php?id=7692) posted by [gap](http://archive.tinymce.com/profile.php?name=gap)_
> 
> _**Tags:** [msie msie11 uncaught exception invalide argument]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
