### ISSUE TITLE
can not create table with table_default_styles when set extended_valid_elements with -table[!style]

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2400]
Description of problem:
 I need to remove all table if not have style, and using create table button to make new one by default it not has style so i setup table_default_styles for it.. but the table still can not create
Steps to reproduce:

extended_valid_elements : '-table[!style]',
valid_classes: {'*': 'xaluanclass'},
table_default_styles: {width: '100%'},
plugins: ['table'],

Expected result:
 .. create new table with default width 100%
 all table copied in will be remove if not has style ( only keep its content)
Actual result:
  Can not create table , all blank
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7693](http://archive.tinymce.com/develop/bugtracker_view.php?id=7693) posted by [binhaus](http://archive.tinymce.com/profile.php?name=binhaus)_

> _**Tags:** [firefox msie safari chrome table table_default_styles extended_valid_elements]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
