### ISSUE TITLE
Paste plugin - option to get rid of text mode nag message

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2401]
The "Paste as Text" feature desperately needs a simple option to silence the nag message that pops up every time you click the button.

I understand showing a message the very first time a user clicks the button, but doing it every time you load a new page containing a text editor is really annoying to users.

The easiest and quickest way is to add a simple option called "paste_text_mode_silent".  Setting it to a true value will disable the nag message.

In the plugin code, simply change line 1554 from:

```
var userIsInformed;
```

to:

```
var userIsInformed = !!editor.settings.paste_text_mode_silent;
```

Another feature that could be optionally added would be an event that is triggered when the user toggles the text mode.  For example, an event name of "PasteTextMode".  The event parameters would include the self.clipboard object, so the event callback function could easily discover if text mode was turned on or off.

Adding this event, combined with the ability to silence the default message would allow a developer to create their own message that is only displayed once per user.  (Rather than once per page load.)  Or they could trigger whatever else they want upon text mode toggle.

If development time is an issue, please prioritize the simple ability to silence the message, with the event as a nice-to-have.

Thanks!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7694](http://archive.tinymce.com/develop/bugtracker_view.php?id=7694) posted by [speednet](http://archive.tinymce.com/profile.php?name=speednet)_
> 
> _**Tags:** [paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
