### ISSUE TITLE
Word being deleted after formatting on lists

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2402]
Description of problem: 
When pasting from Word in Chrome, a list that has a formatted word as the second to last word of the &ltg;li> is deleting the last word of the &ltg;li>  on paste.

Steps to reproduce:
1. Create Word document with an un-ordered list
2. Format the second to last word of the un-ordered list (ex: * This is &ltg;b>a&ltg;/b> test)
3. Paste this into a TinyMCE Chrome window with the paste option

Expected result:
All text with formatting will come over
* This is &ltg;b>a&ltg;/b> test

Actual result:
The last word is being deleted:
* This is &ltg;b>a&ltg;/b>             &ltg;-- Test was deleted

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7695](http://archive.tinymce.com/develop/bugtracker_view.php?id=7695) posted by [TrevBart](http://archive.tinymce.com/profile.php?name=TrevBart)_

> _**Tags:** [chrome chrome paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Aafaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
