### ISSUE TITLE
Allow adding ID attribute to table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2403]
Allow adding the ID attribute to tables. A table can be a link-target and therefore setting an ID is required. (Same is for images, but a feature request to allow setting an ID for an images already exists).

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7697](http://archive.tinymce.com/develop/bugtracker_view.php?id=7697) posted by [Loweee](http://archive.tinymce.com/profile.php?name=Loweee)_
> 
> _**Tags:** [table attribute id]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
