### ISSUE TITLE
Missing language js files with quick Install

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2404]
Description of problem:

Steps to reproduce:
1. Use &ltg;script src="//tinymce.cachefly.net/4.2/tinymce.min.js">&ltg;/script>
1. add Language: 'zh_TW' or Language: 'zh_CN onInit
2. reload TinyMCE

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7698](http://archive.tinymce.com/develop/bugtracker_view.php?id=7698) posted by [Michael Yuen](http://archive.tinymce.com/profile.php?name=Michael Yuen)_
> 
> _**Tags:** [firefox msie safari chrome language]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Pafaab_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
