### ISSUE TITLE
tinymce.init(initParams) fails in JavaFX WebView under Java 8u60 using Webstart

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2405]
I have a Java Swing GUI running TinyMCE in in a JavaFX WebView component.
The method tinymce.init(initParams) fails under Java 8u60 using Webstart.
It works with Java 8u51 (and presumably other versions, too) and Webstart and it also works with Java 8u60 when Webstart ist not used to launch the GUI.

And - it fails without throwing an exception!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7699](http://archive.tinymce.com/develop/bugtracker_view.php?id=7699) posted by [saeder](http://archive.tinymce.com/profile.php?name=saeder)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
