### ISSUE TITLE
block or element merging is inconsistent between browsers

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2406]
Description of problem:
when you have a any block/elements with ids in tinymce the behaviour when using the "Delete" key is inconsistent between browsers (tested between chrome and FF

Steps to reproduce:
1. open tinymce in source mode
2. add the following paras:
&ltg;p id="1">para 1&ltg;/p>
&ltg;p id="2">para 2&ltg;/p>
&ltg;p id="3">para 3&ltg;/p>

3. if i place the cursor before the 2 in para 2 and click the "Delete" key i would expect for either para 2 to be completely deleted or it to pull para 3 into para 2 element but the behavior is inconsistent between browsers

Expected result:
&ltg;p id="1">para 1&ltg;/p>
&ltg;p id="3">para 3&ltg;/p>

Actual result:
On FF:
&ltg;p id="1">para 1&ltg;/p>
&ltg;p id="3">para 3&ltg;/p>

On Chrome:
&ltg;p id="1">para 1&ltg;/p>
&ltg;p id="2">para 3&ltg;/p>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7700](http://archive.tinymce.com/develop/bugtracker_view.php?id=7700) posted by [richhart](http://archive.tinymce.com/profile.php?name=richhart)_

> _**Tags:** [firefox msie safari chrome block merge]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by christianwach** [comment]
The bug is indeed valid, although the description is awkwardly written. To re-state it: consider the following raw editor content:

```html
<p class="a">Blah</p>
<p class="b">Blah</p>
```

Place the cursor at the beginning of the second paragraph and hit `backspace` to merge the two paragraphs.

Webkit result: `<p class="a">BlahBlah</p>`
Gecko result: `<p class="b">BlahBlah</p>`

There is clearly inconsistent behaviour between browsers here.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by christianwach** [comment]
@blackcathikari I have just verified that this bug is still present in TinyMCE v4.4.1 which ships with WordPress 4.5.3. The bug is therefore still present for millions on WordPress users.
