### ISSUE TITLE
security issue in tiny_mce.js

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2407]
We are using tinymce version 3.9 and found that it is having security issue Client_DOM_Code_Injection in tiny_mce.js when scanned using security tool. 

Details:

Source object: replace, sourceline: 7209
Destination Object: OnBeforeUnload sourceline: 7215

can you let us know by when this will be fixed 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7717](http://archive.tinymce.com/develop/bugtracker_view.php?id=7717) posted by [sreenivask](http://archive.tinymce.com/profile.php?name=sreenivask)_

> _**Tags:** []_
> _**Status:** Closed_
> _**Resolution:** Wont Fix_
> _**Attached URL:** none_

**Comment by damkondwarpravin** [comment]
It's **CheckMarx Scan Report**. I also got the same issue today.

**Comment by damkondwarpravin** [comment]
The application's function method receives and dynamically executes user-controlled code using onBeforeUnload, at line 8847 of /tiny_mce/tiny_mce_src.js. This could enable an attacker to inject and run arbitrary code. 

The attacker can inject the malicious payload into the victim's browser, via external input replace. This is read by the browser in the function method, at line 8847 of /tiny_mce/tiny_mce_src.js. The browser then executes this code itself.
