### ISSUE TITLE
IE10/11 inline editing of TD is not supported, Tinymce doesn't detect this

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2408]
IE does not allow contenteditable in TD and Tinymce doesn't "detect" this.

https://msdn.microsoft.com/en-us/library/ms537837%28v=VS.85%29.aspx?f=255&MSPPError=-2147217396

I would expect tinymce to refuse to apply to a TD in this case or otherwise, if possible, introduce a workaround (nested DIV?) automatically.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7701](http://archive.tinymce.com/develop/bugtracker_view.php?id=7701) posted by [bago](http://archive.tinymce.com/profile.php?name=bago)_
> 
> _**Tags:** [msie msie7 msie8 msie9 msie10 msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Ebfaab_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
