### ISSUE TITLE
Error on the web site documentation section

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2410]
Description of problem:

When in Documentation/Configuration section of the web site, I hit the following two links under Code plugin, I get an error message that I am not allowed to edit Wiki instead of documentation on those config options:

    code_dialog_width
    code_dialog_height

Steps to reproduce:
1. Navigate to http://www.tinymce.com/wiki.php/Configuration
2. Scroll down to Code Plugin
3. Hit any of two links code_dialog_width or code_dialog_height
4.
5.

Expected result: Should see the documentation

Actual result: Seeing error message:

You don't have permissions to edit this page

You need to be an Wiki Member to be able to edit the wiki. Send a mail to info@moxiecode.com to request access.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7702](http://archive.tinymce.com/develop/bugtracker_view.php?id=7702) posted by [dca](http://archive.tinymce.com/profile.php?name=dca)_

> _**Tags:** [msie msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/wiki.php/Configuration_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
