### ISSUE TITLE
form tag removed in inline editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2413]
Description of problem: the form tag is removed when using the inline editor

Steps to reproduce:
1. add a form in the html plugin
2. validate

Expected result:
have a form

Actual result:
form tag is removed
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7705](http://archive.tinymce.com/develop/bugtracker_view.php?id=7705) posted by [gabole](http://archive.tinymce.com/profile.php?name=gabole)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by abren84** [comment]
Any update on this?  I used to be able to add PayPal buttons into my TinyMCE instance, but now the form tags get stripped out.  Even the "extended_valid_elements" option no longer has any impact on this.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
