### ISSUE TITLE
list-style-position: inside, caret position bug

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2414]
Description of problem:
When 'list-style-position' is set to inside, the caret is set on the wrong location when a li is empty. Only happens when loading already existing data, when adding it using the editor it works correctly.

Steps to reproduce:
1. ensure that you have the 'list-style-position' set to inside. (content_style: "ul {list-style-position : inside}")
2. add some default value to the textarea.
(
&ltg;ul>
&ltg;li>hello&ltg;/li>
&ltg;li>&ltg;span style="font-family: 'arial black', 'avant garde';">world&ltg;/span>&ltg;/li>
&ltg;li>&ltg;/li>
&ltg;/ul>
)
1. load the page and try to edit the empty li

Expected result:
Caret is placed after the bullet.

Actual result:
Caret is placed before the bullet.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7707](http://archive.tinymce.com/develop/bugtracker_view.php?id=7707) posted by [Riuujin](http://archive.tinymce.com/profile.php?name=Riuujin)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Kcfaab/1_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
