### ISSUE TITLE
can not display facebook embed video on editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2415]
Description of problem:

When I add Facebook embed video code to the editor source code manually, it show nothing on editor view area so I cant know if there is a video from Facebook or nothing, please fix this bug to be like YouTube.
Please check attachments, you can see in source code two embed videos first one from facebook another one from youtube and you can notice there is no frame for facebook video otherwise a nice frame appear for youtube.

Regards,

Steps to reproduce:
1. add facebook embed video to source code 
2. save the changes

Expected result:
video frame
Actual result:
nothing
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7709](http://archive.tinymce.com/develop/bugtracker_view.php?id=7709) posted by [jeddahart](http://archive.tinymce.com/profile.php?name=jeddahart)_

> _**Tags:** [firefox msie safari chrome facebook embed video]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by willCodebit** [comment]
I'm with TinyMCE v4.4.1 and the facebook embed video do not appear, inspecting the code in the developer options I can found the script but it's not visible in the editor.

I can't figure out what is going on,
thanks in advance.

**Comment by blackcathikari** [comment]
@willCodebit Unfortunately I still can't replicate this, based on the information I've got. What browser and OS are you using, do you know what the editor's config is, and what does the editor source code look like after trying to embed the video? Also, could you please try to replicate this problem on http://fiddle.tinymce.com/ and let me know if there's any difference? Thanks, Millie.

**Comment by willCodebit** [comment]
Hi @blackcathikari, I'm using Chrome 53 in Ubuntu 16.04, the editor is mostly like the full example found in the docs.
This is the code what I'm trying to embed, and in the place where I'm trying, it don't have any changes:
`
<div id="fb-root">&nbsp;</div>
<p>
<script>// <![CDATA[
window.fbAsyncInit = function() {
      FB.init({
        appId      : '{your-app-id}',
        xfbml      : true,
        version    : 'v2.5'
      });
    
      // Get Embedded Video Player API Instance
      var my_video_player;
      FB.Event.subscribe('xfbml.ready', function(msg) {
        if (msg.type === 'video') {
          my_video_player = msg.instance;
        }
      });
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
// ]]></script>
</p>

<div class="fb-video" data-href="FACEBOOK_VIDEO_URL" data-width="620" data-allowfullscreen="true">&nbsp;</div>`

and this is the result in http://fiddle.tinymce.com/
`
<div id="fb-root">&nbsp;</div>
<p>&nbsp;</p>

<div class="fb-video" data-href="FACEBOOK_VIDEO_URL" data-width="620" data-allowfullscreen="true">&nbsp;</div>`

I've found in a facebook page two types of embed code that can be used, the javascript based embed (code above) and the iframe based, that give me problems with other scripts.

PS: sorry for my bad english, it is not my native language.

**Comment by spocke** [comment]
We don't allow scripts to be executed within the editor. This is both a security feature but also something that the contentEditable mode blocks so both us and the browser block script execution. Also having a script that updates stuff within the editor is very problematic so even if it was possible we would still not recommend it. If we are to fix this we likely produce a placeholder for it while editing and then convert to/from scripts when you load/save contents.

**Comment by willCodebit** [comment]
A placebolder should be enough, at least the users will not open a ticket to IT support saying "the embed disappears everytime!"

Thanks for all attention!
