### ISSUE TITLE
problem with facebook video embed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2416]
Description of problem:

I have a problem inserting embed Facebook video using insert video tool from editor when I paste the code then click ok nothing added to source code, so I have to view source code and paste it manual. and this is hard if I want to insert it between two sections!

Please check example code from Facebook reference link
https://developers.facebook.com/docs/plugins/embedded-video-player

Steps to reproduce:
1. click on insert menu
2. video insert
3. embed tab
4. paste Facebook ember code
5. save changes

Expected result:
add Facebook code with video frame

Actual result:
nothing there is no code in source code and of course there is no frame for video

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7710](http://archive.tinymce.com/develop/bugtracker_view.php?id=7710) posted by [jeddahart](http://archive.tinymce.com/profile.php?name=jeddahart)_
> 
> _**Tags:** [firefox msie safari chrome facebook video embed]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Hi! I am closing this issue due to old age.

If you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.  

Thank you!
