### ISSUE TITLE
Subscript and Superscript should be mutually exclusive

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2418]
Description of problem: Superscript and Subscript should be mutually exclusive.

Steps to reproduce:
1. Type some text
2. Select format Subscript, type some text
3. Select format Superscript, type some text
4. Enter a newline and clear formatting
5. Type more text
6. Select format Superscript, type some text
7. Select format Subscript, type some text

Expected result:
Superscript and Subscript should be relative to original text being applied to. Otherwise selecting both superscript and subscript should yield the same results.

Actual result:
Superscript and Subscript are applied directly to each other. The order in which they are selected also affects the formatting when both are selected.
Cursors also appear misaligned when both are selected.

*Possible feature request would be to offer an option to make them mutually exclusive.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7738](http://archive.tinymce.com/develop/bugtracker_view.php?id=7738) posted by [emanlangit](http://archive.tinymce.com/profile.php?name=emanlangit)_
> 
> _**Tags:** [firefox msie subscript superscript]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by emanlangit** [comment]
Is there an estimate or time frame for this item's disposition?

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
