### ISSUE TITLE
Can you please add onPreview callback?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2419]
Would it be at all possible to add a callback in order to perform some manipulation on HTML before it is previewed?

For instance, that would make it easier to substitute variables in HTML with their sample values.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7713](http://archive.tinymce.com/develop/bugtracker_view.php?id=7713) posted by [dca](http://archive.tinymce.com/profile.php?name=dca)_
> 
> _**Tags:** [callback]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by JbalTero** [comment]
This would be useful.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
