### ISSUE TITLE
Focus does not set cursor at end of content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2420]
Description of problem:

When focusing an editor with content the cursor/caret stays at the beginning of the content rather than moving to the end. 

Steps to reproduce:
1. Initialize an editor with content
2. Focus the editor

Expected result:

The cursor/caret is at the end of the content

Actual result:

The cursor/caret is at the beginning of the content.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7728](http://archive.tinymce.com/develop/bugtracker_view.php?id=7728) posted by [deeg](http://archive.tinymce.com/profile.php?name=deeg)_

> _**Tags:** [focus cursor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/kgfaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by chloe-1903** [comment]
I still have the issue on Chrome, with v4.5.23. I'm using tinymce-angular v3.5.0 too, it might come from it.
