### ISSUE TITLE
Merging whole rows adds columns

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2421]
Description of problem:

Steps to reproduce:
1. Make a table of 3 columns and 3 rows.
2. Merge the cells of rows 1 and 2.

Expected result:
3 columns, 2 rows

Actual result:
4 columns, 1 row

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7716](http://archive.tinymce.com/develop/bugtracker_view.php?id=7716) posted by [yecril15sr](http://archive.tinymce.com/profile.php?name=yecril15sr)_
> 
> _**Tags:** [merge table cells]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/ydfaab/1_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
