### ISSUE TITLE
toggleFormat implementation

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2423]
Description of problem:

Current toggleFormat implementation makes it impossible to use custom format calls like: 
tinyMCE.activeEditor.execCommand("FontSize", false, {value:'12px',fontclass:'font12'}); 

Current implementation is:
function toggleFormat(name, value) {
     formatter.toggle(name, value ? {value: value} : undefined);
     editor.nodeChanged();
}

So there is 2 problems:
1) you can not use falsy values
2) you can not pass objects

I suggest to change it to something like that:
 function toggleFormat(name, value) {
     formatter.toggle(name, (typeof(value)!='undefined' && value!=null) ? (typeof(value)=='object' ? value : {value: value} ) : undefined);
     editor.nodeChanged();
}

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7720](http://archive.tinymce.com/develop/bugtracker_view.php?id=7720) posted by [roshen](http://archive.tinymce.com/profile.php?name=roshen)_
> 
> _**Tags:** [firefox msie safari chrome core formatter]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** tinymce.com_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
