### ISSUE TITLE
Font size label hides 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2424]
Description of problem:

Steps to reproduce:
1.Choose font family as times new roman . 
2.font size lable hides automatically

Expected result:font size text should visible properly

Actual result:font size text not visible properly

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7715](http://archive.tinymce.com/develop/bugtracker_view.php?id=7715) posted by [Nixon](http://archive.tinymce.com/profile.php?name=Nixon)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/vdfaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
