### ISSUE TITLE
Copy from Excel pasting as image in chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2426]
Description of problem:
pasting as an image while copying from excel and pasting in editor on chrome. its working fine in version 4.0.28 but from the next versions its pasting as an image.

Steps to reproduce:
1.open the fiddler url mentioned above
2.set version as latest
3.copy content from excel and paste in editor
4.content is pasting as image but its excel content
5.issue exists in latest release after 4.0.28

Expected result: should be pasted as html content (please see attached expectedResult.PNG)

Actual result:pasting as an image (please see attached actualResult.PNG)

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7722](http://archive.tinymce.com/develop/bugtracker_view.php?id=7722) posted by [sherikarss](http://archive.tinymce.com/profile.php?name=sherikarss)_

> _**Tags:** [chrome chrome paste from excel]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/UAeaab/1_

**Comment by XavierBoubert** [comment]
:+1:

**Comment by qianzhao** [comment]
:+1:

**Comment by spocke** [comment]
Fixed here:
https://github.com/tinymce/tinymce/commit/a1e4a25ea433972bbce5c2bcd913969be5b263f4
