### ISSUE TITLE
list-style-type always overridden by a list-style-image in CSS

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2428]
Description of problem:
If you have CSS rule with list-style-image set for UL elements, you can't ever change the way UL list bullets appear by changing bullet-list in TinyMCE.

Steps to reproduce:
1. Have a CSS rule: ul { list-style-image: url(/my/image.gif); }
2. In TinyMCE, change the Bullet list type to Circle (or anything other than Default)
3. No change in list.

Expected result:
I would expect the bullet list type to apply and change how the list bullets appear.

Actual result:
The list-style-image rule in CSS overrides the list-style-type style applied to the list element so you always see the image as the bullet.

Possible fix:
In advlist/plugin.js, in applyListFormat() after you set the listStyleType style, set the listStyleImage style accordingly, eg:

dom.setStyle(list, 'listStyleImage', (styleValue && styleValue !== '') ? 'none' : null);

So, explicitly set list-style-image to 'none' when the list-style-type is set.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7724](http://archive.tinymce.com/develop/bugtracker_view.php?id=7724) posted by [gtinovem](http://archive.tinymce.com/profile.php?name=gtinovem)_

> _**Tags:** [firefox msie safari chrome list advlist]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by ryneeverett** [comment]
Given that the advlist plugin does not provide a way to change the `list-style-image` attribute, overriding the css rule as suggested would eliminate the only way of setting the `list-style-image` if that is what is desired.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by DunuAname** [comment]
Hi there, `list-style-image` and `list-style-type` are two different things, if you've set an image as bullet, it wil override a "type". if you also want, for example, a square bullet, you need to set image to "none" for the selector where you want a different bullet.
here's an example.

ul{
    list-style-image: url(image.gif);
}
li>ul{
    list-style-image: none;
    list-style-type: square;
}

first, you need to undo "list-style-image" by setting it to "none" and then add a "list-style-type"

Kind regards
