### ISSUE TITLE
Partial translation when two languages used on the same page

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2429]
Description of problem:

Steps to reproduce:
1. Create 2 textareas on the page.
2. Init one with en_CA and another with fr_FR language.

Expected result:

English editor should have entirely English UI

Actual result:

Only top level menus are in English, but the drop down menus, tooltips and dialogue buttons are all in French.

I could not create a fiddle with that as it seems to not have languages installed, so attaching it below

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7725](http://archive.tinymce.com/develop/bugtracker_view.php?id=7725) posted by [dca](http://archive.tinymce.com/profile.php?name=dca)_
> 
> _**Tags:** [firefox msie safari chrome language translation]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by rkaartikeyan** [comment]
I am too having same issue.

i created Two Editor with English and Arabic. like Bellow

```
tinymce.init({
	height : 250, 
	width: '99.9%', 
	mode : "textareas",
	selector: "#textAreaEnId", 
	theme: "modern",
	language: "en",
	directionality: "ltr"
});
```
and
```
tinymce.init({
	height : 250, 
	width: '99.9%', 
	mode : "textareas",
	selector: "#textAreaArId", 
	theme: "modern",
	language: "ar",
	directionality: "rtl"
});
```

but the output of First Text Editor with English Submenus are in Arabic. see the Screenshot below.

![screen shot 2016-03-04 at 8 25 52 pm](https://cloud.githubusercontent.com/assets/3778591/13530477/8bf65aa8-e247-11e5-9740-07d93d71841b.png)

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Comment by dca00** [comment]
Way to go!
