### ISSUE TITLE
TinyMCE fiddle does not have language packs installed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2430]
Description of problem:

Fiddles using languages do not render in the fiddle

Steps to reproduce:
1. Use any non-default language in the fiddle, example fr_FR

Expected result: editor should render

Actual result: no editor rendered

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7726](http://archive.tinymce.com/develop/bugtracker_view.php?id=7726) posted by [dca](http://archive.tinymce.com/profile.php?name=dca)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** fiddle.tinymce.com_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
