### ISSUE TITLE
ReferenceError: tinyMCEPopup is not defined

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2431]
we are upgrading to 4.2.6v, during this I am facing "ReferenceError: tinyMCEPopup is not defined" for tinyMCEPopup instances. Please suggest me.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7729](http://archive.tinymce.com/develop/bugtracker_view.php?id=7729) posted by [anilkalal](http://archive.tinymce.com/profile.php?name=anilkalal)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
