### ISSUE TITLE
TinyMCE causes unpredictable page scrolling in Apple Cocoa Webview

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2435]
Description of problem:

When using the TinyMCE editor control within a web page rendered by Apple's Cocoa Webview, there is inappropriate page scrolling behavior while typing within the control.  This behavior can be intermittent, but it is not difficult to reproduce in a reasonably consistent manner.

The behavior typically manifests as a scroll to the top of the page when any key is pressed, so that the control is no longer in view.

Steps to reproduce:

You can see this using any browser application based on Apple's Cocoa Webview, such as "It's a Browser":

 http://itsabrowser.com/

and navigating to the following page:

 http://www.tinymce.com/enterprise/enterprise.php

Scroll to the bottom of the page where the TinyMCE control is, select some text within the control, and start typing.  You should see the screen scroll all the way to the top of the page.  If you scroll back down, you should see the cursor still located within the control.  Press another key and you should see the behavior occur again.

Expected result:

The browser page should not scroll when editing text in TinyMCE.

Actual result:

The browser page scrolls unexpectedly when editing text in TinyMCE.

Additional Information:

In my testing, I can easily reproduce this in any browser window based on the Apple Cocoa Webview.  I have reproduced the behavior in both Yosemite and El Capitan.  I can reproduce it very consistently, but my customers indicate that the behavior can be intermittent.  In my testing, I find I have to select (highlight) some text in the control before I can get the behavior to occur.

It does seem that this behavior does not occur in the full screen mode of the editor control, but my customers largely do not view this as an acceptable workaround.

This behavior also does not occur in the Safari browser, because it is not based on Apple's public Cocoa Webview for developers, but on a private framework instead.

In my testing I have been using the default user agent string provided by the Apple Cocoa Webview, which is as follows:

 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko)"

In looking through the bug database, I noticed the following two entries:

 TinyMCE - Bug #2823
 http://www.tinymce.com/develop/bugtracker_view.php?id=2823

 TinyMCE - BUg #7351
 http://www.tinymce.com/develop/bugtracker_view.php?id=7351

Given the information is these entries, is it possible that my issue is related to some aspect of the 'autoresize' functionality?

As a developer that uses the Apple Cocoa Webview in custom browser windows, I want to be able to support the use of TinyMCE in web pages, but cannot do so currently because I cannot resolve this problem.

If there were a workaround I could implement (such as knowing what javascript I could inject to avoid or mitigate the issue), that would be just as helpful as a fix to the control.

Since I can reproduce the issue consistently, I would be glad to help test any approach you suggest.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7733](http://archive.tinymce.com/develop/bugtracker_view.php?id=7733) posted by [mmerritt](http://archive.tinymce.com/profile.php?name=mmerritt)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/enterprise/enterprise.php_

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
