### ISSUE TITLE
Font Color and Background color change does not trigger 'change' event

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2436]
Description of problem: Font Color and Background color change on a selection does not trigger 'change' event. 

Prerequisite:
* tinyMCE onChange handler is attached on init

Steps to reproduce:
1. Type in some text into the WYSIWYG editor "This is a sample text."
2. Add Font color to 'sample' and background color to 'text' such that the html source is as shown below

&ltg;p>This is a &ltg;font color="#99CC00">sample&ltg;/font> &ltg;font style="background-color: #ff6600;">text&ltg;/font>.&ltg;/p>

3. While actions like BOLD, UNDERLINE, ITALIC triggers the change event, the font color and background color change does not trigger the change event.

Expected result:
Font Color change and Background Color change should trigger change event
Actual result:
Font Color change and Background Color change does not trigger change event.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7734](http://archive.tinymce.com/develop/bugtracker_view.php?id=7734) posted by [natesan](http://archive.tinymce.com/profile.php?name=natesan)_

> _**Tags:** [firefox msie safari chrome change event font color background]_
> _**Status:** Closed_
> _**Resolution:** Works For Me_
> _**Attached URL:** none_

**Comment by jkrth617** [comment]
if you edit the event off of "change" to "ExecCommand" it does not fire an event for the font/background color change.
Is this intentional? I am trying to just catch the changes from the menu items and it works for all of them except the color changes.
