### ISSUE TITLE
getContent with text format does not preserve formatting (spaces, new lines etc)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2439]
Description of problem:
getContent({format : 'text'}) looses format in Firefox. Works fine with Chrome

Steps to reproduce:
1. In Firefox navigate to http://www.tinymce.com/tryit/basic.php
2.Open console. 
3.enter: alert(tinyMCE.get('content').getContent({format : 'text'}))
4.Notice that text is not formatted
5.Repeat the same steps in Chrome and notice the difference

Expected result:
getContent in text format should preserve formatting (spaces, new lines etc)

Actual result:
getContent in text format does not preserve formatting (spaces, new lines etc)

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7737](http://archive.tinymce.com/develop/bugtracker_view.php?id=7737) posted by [ydench](http://archive.tinymce.com/profile.php?name=ydench)_

> _**Tags:** [firefox firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
