### ISSUE TITLE
Bold and Italic buttons aren't highlighted

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2440]
Description of problem:

Steps to reproduce:
1. http://www.tinymce.com/tryit/basic.php
2. Select Bold and/or Italics button
3. Type some text
4. Delete the text using Backspace key just until the text is gone and Bold/Italics button is no longer highlighted
5. Type some text again

Expected result:
The text should not have any formatting when the font buttons are toggled off

Actual result:
The text retains Bold/Italic formatting.  Note* when cursor is moved, the buttons become highlighted appropriately. MSIE only.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7739](http://archive.tinymce.com/develop/bugtracker_view.php?id=7739) posted by [emanlangit](http://archive.tinymce.com/profile.php?name=emanlangit)_

> _**Tags:** [msie font bold italics]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by emanlangit** [comment]
Is there an estimate or time frame for this item's disposition?

**Comment by arjunasuresh3** [comment]
+1

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
