### ISSUE TITLE
Default Font Family and Size

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2441]
I have customized the editor to contain a default font family and font size.  This works somewhat consistently for normal content, but does not apply defaults for tables and Copy/Paste from External sources.

A customizable default setting would be nice to have.

I don't expect external formatting to be carried over but a 'destination formatting' option could be available that would apply the defaults set (for regular content as well as tables). 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7740](http://archive.tinymce.com/develop/bugtracker_view.php?id=7740) posted by [emanlangit](http://archive.tinymce.com/profile.php?name=emanlangit)_
> 
> _**Tags:** [default font table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by emanlangit** [comment]
Is there an estimate or time frame for this item's disposition?

**Comment by fyrkant** [comment]
Hi! I am closing this issue due to old age.

If you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.  

Thank you!
