### ISSUE TITLE
Unexpected behaviour when deleting nested empty list items

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2442]
Description of problem:

Steps to reproduce:
1. create a nested list items
2. remove the text from the list items but leave the nested list items in place
3. from the deepest list items start deleting
4.
5.

Expected result: the list items get removed one by one as the user hits backspace

Actual result: the cursor starts jumps upwards in an unexpected way and leaves the list items in place.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7741](http://archive.tinymce.com/develop/bugtracker_view.php?id=7741) posted by [excentric](http://archive.tinymce.com/profile.php?name=excentric)_

> _**Tags:** [li nested]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/vhfaab_

**Comment by thorn0** [comment]
One more related bug. Place the caret where the first arrow points to, and press Del twice.
![image](https://cloud.githubusercontent.com/assets/94334/11698409/14243e46-9ec7-11e5-990b-df121b056aa5.png)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
