### ISSUE TITLE
duplicates the image instead of moving the image to the new place

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2444]
Description of problem:

I am using IE11 will appear follow problem . When i am using Chrome is ok. 

The current tinyMCE editor when I insert a file (an image), and I drag the image to a different place inside the main content editing area, it duplicates the image instead of moving the image to the new place.

Expected result:No duplicates the image

Actual result:t duplicates the image instead of moving the image to the new place

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7743](http://archive.tinymce.com/develop/bugtracker_view.php?id=7743) posted by [laukashing](http://archive.tinymce.com/profile.php?name=laukashing)_

> _**Tags:** [msie chrome msie11 chrome ie11 httpattuindzzcomnews452]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://attu.indzz.com/news/452_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
