### ISSUE TITLE
RichText Editor tinymce V4.2.7, "Insert/Edit link" not working in IE 11.0.22

### ISSUE THREAD

**Issue by Suraj1189** [tinymce/tinymce#2447]
I am using tinymce rich text editor V4.2.7. When i inserted link,it is not working in IE V11.0.22. Is this is a known issue? What will be the solution for it. will it going to resolved in upcoming release?

Thanks & Regards,
Suraj

**Comment by spocke** [comment]
Works fine when I try it here:
http://www.tinymce.com/tryit/basic.php

Could it be some implementation issue?
How are you inserting the link?
Can you create a fiddle at fiddle.tinymce.com where it gets reproduced?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by ridwanpranata** [comment]
[ewfewf](url)
