### ISSUE TITLE
Underline/Strikethrough  color does not change when font color is changed

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2448]
Steps to reproduce:

1.Click Underline/Strikethrough and choose a color

2.Type something

3.Change the color and continue typing

Expected result: underline/strikethrough and font color should match

Actual result: underline/strikethrough and font color don't match

**Comment by spocke** [comment]
This is a know issue with the browsers rendering engine. It will not change the color of the underline or strikethough if you change the color of the text. Not sure if we can solve this.

**Comment by PetrBorisov** [comment]
But, if parent of selection tag have underline/strikethrough  css properties  you can set this property of each selection tag ( if he dont`t have repealing css properties)


for example :
<span id='parent span' style="text-decoration: underline; color: rgb(255, 0, 0);">
		parent span
		<span  id='child' style="color: rgb(0, 0, 0); text-decoration: underline;">
			child span
		</span>
		<span  id='child2' style="color: rgb(0, 0, 0);  text-decoration: underline;">
			second child span
		</span>
</span>



now we have :

<span id='parent span' style="text-decoration: underline; color: rgb(255, 0, 0);">
		parent span
		<span  id='child' style="color: rgb(0, 0, 0);">
			child span
		</span>
		<span  id='child2' style="color: rgb(0, 0, 0);">
			second child span
		</span>
</span>

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
