### ISSUE TITLE
Font size is not kept when using backspace on first character

### ISSUE THREAD

**Issue by webflo-dev** [tinymce/tinymce#2449]
Description of problem:
When you have few new lines before a text, when you want to remove some of them, the font size of the text is not kept.

Tested with the online "Try it" page for "Classic example" (the only on example that allow to change the font size). At this time, it's version 4.2.7

Expected result: font size should not change.

Steps to reproduce this bug:
- Add few empty new line with default font size.
- Write some text with a specific font size (like 14pt)
- Move the cursor before the first character.
- Press "backspace" to remove a line.
  => Font size is lost.

**Comment by fyrkant** [comment]
This has been fixed since a while back.
