### ISSUE TITLE
Allow styling changes for elements with class="mceNonEditable" by default

### ISSUE THREAD

**Issue by Bhavesh1976** [tinymce/tinymce#2450]
Enable (by default) formatting for elements with class="mceNonEditable".
Editor correctly disables any content changes but also restricts formatting
There are a few use cases we are running into where a non editable element is a variable and is replaced by actual content at runtime
When this occurs the styling looks inconsistent.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
