### ISSUE TITLE
A href removed arround DIV

### ISSUE THREAD

**Issue by team4music** [tinymce/tinymce#2451]
Hi, sadly the a:link is beeing removed before a div if someone change from code to visual editor
example

http://pastebin.com/J7tuDTyq

**Comment by fabsn182** [comment]
Any informations about when this will be fixed? `<a>` Elements can contain block elements in html5.

**Comment by triplejumper12** [comment]
I am also running into this issue in both html5 and html5-strict schemas. As per the HTML5 spec, <a> elements can contain flow (block) elements as long as the <a> element's parent is also a flow element. So just `<a href="test"><div>ARST</div></a>` is invalid while `<div><a href="test"><div>ARST</div></a></div>` is valid.

(If I'm understanding the spec properly on: https://www.w3.org/TR/html-markup/a.html#a-changes right under "Changes in HTML5")

As a temporary fix, I'm using `valid-children: '+a[h1|h2|h3|h4|h5|h6|div|p]'`, but this obviously doesn't include all the possible flow elements, just the ones that we need for now.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
