### ISSUE TITLE
Inline editor - after init tinymce on li element all text is gone from this tag

### ISSUE THREAD

**Issue by omeha2** [tinymce/tinymce#2453]
All what i do is this

> http://fiddle.tinymce.com/wifaab

I readed lot of documentation pages, but didn't find any explanation why it happened

**Comment by Ramonlord** [comment]
Browser Chrome 46.0.2490.80 m

**Comment by flack** [comment]
I can reproduce this in Firefox as well. Is there any sort of workaround I can do in tinymce config? I can't change the markup unfortunately

**Comment by Ramonlord** [comment]
Please check this animation, as you can see the label "Test1" disappear when inline editor is activated on the li element
![Animation](http://ipic.su/img/img7/fs/Animation0.1450350380.gif)

**Comment by flack** [comment]
I've made a clunky workaround by setting the value again in the init function:

```javascript
var config = {inline: true}; //contains all normal tinymce config stuff

if ($(element)[0].nodeName === 'LI')
{
    var content = $(element).text()
    config.setup = function(editor) {
        editor.on('init', function() {
            editor.setContent(content);
        });
    }
}

var ed = new tinymce.Editor($(element).attr('id'), config, tinymce.EditorManager);
ed.render(true);
```
It's not very generic, but a variation of this should get the job done for the time being

**Comment by tinydylan** [comment]
Hi,

I believe this issue has been corrected. I tested the above fiddle on TinyMCE 5.2.1 and the issue no longer occurs. 

Kind regards,

Dylan Just
Tiny
