### ISSUE TITLE
Cursor gets stuck in noneditable

### ISSUE THREAD

**Issue by ManojSridhar** [tinymce/tinymce#2457]
I have a div with data-mce-contenteditable set to false. I have image tag inside it. The cursor gets strucked inside the div and cannot add text in the tinymce once I select that div. The same issue is posted in http://www.tinymce.com/develop/bugtracker_view.php?id=5698 but no solution has been proposed yet. Please suggest any workaround for this issue.

**Comment by ManojSridhar** [comment]
Is this really a bug in timy mce without any solution or is there any workaround for this.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
