### ISSUE TITLE
How to make bundle with jquery-based core?

### ISSUE THREAD

**Issue by nazar-pc** [tinymce/tinymce#2460]
It is possible on website, but not using `grunt bundle`.
I need to create custom build with out-of-tree patches and I need it to be with jQuery-based core instead standalone.
Additional option would be very suitable.

**Comment by spocke** [comment]
I guess we could have a grunt jquery-bundle or something or that the bunde task creates two files.

**Comment by nazar-pc** [comment]
Any chance to get this resolved in near future?

**Comment by spocke** [comment]
Not sure if it even makes sense to have the jquery version anymore since the size gain of dropping the internal sizzle is next to nothing. We have though about removing this separate build in the process the jquery plugin will be kept though.

**Comment by nazar-pc** [comment]
I'm switching to standalone core, so if no one else needs this - I'm closing issue.
