### ISSUE TITLE
Paste copied text after ctrl+shift+right select

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2461]
inline: true

Steps:

1) typing a few strings
2) select last word(cursor before him and ctrl+shift+right ) or few last words(ctrl+shift+ double/triple/.. right)  in string (not last string)
3) paste
pasting with creating new string, cursor placed in begin of next string

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
