### ISSUE TITLE
PNG increase filesize after Drag&drop upload

### ISSUE THREAD

**Issue by nikmauro** [tinymce/tinymce#2463]
Hello i use the drag&drop plug with images_upload_handler function.
When upload png or edit files, the editor increase the filesize of current image.
Upload image with 120kb and the image after upload has 1mb filesize, if upload the image direct to the php script the image have the same file size.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
