### ISSUE TITLE
Upgrade to Babel 6

### ISSUE THREAD

**Issue by HMAZonderland** [tinymce/tinymce#2465]
When compiling from source I get this mention;

> WARN deprecated babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6. 

Compiling still works, tho.

**Comment by spocke** [comment]
Yes, seems to be jscs using the older version of babel. Not sure that we need jscs since eslint handles most of it's cases now days.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
