### ISSUE TITLE
Blur event does not fire in ios(iPad) when we click anywhere outside tiny mce

### ISSUE THREAD

**Issue by goyalvarun601** [tinymce/tinymce#2471]
Tiny mCe does not loose focus when we click anywhere outside the text-area.
If I have some text selected inside tiny mce and I click outside, it remains highlighted with the options to select/copy/paste given by ios(iPad).
This gives a bad user experience.

**Comment by chriscfox** [comment]
This also means that you can't use Ajax to post changes to tinyMCE content on the iPad.

**Comment by dblVs** [comment]
Any updates on this ?

**Comment by chriscfox** [comment]
@dblVs I managed to achieve what I needed (which was to be able to call Ajax updates on blur, using the following code:
`setup: function (tmced) {
    tmced.on('blur', function (ed, evt) {
                tinyMCEAutoSave();
            });
            tmced.on('mouseout', function (ed, evt) {
                if (isiPadoriPhone()) {
                    console.log("mouse out");
                    tinyMCEAutoSave();
                }
                return true;
            });
}`

And
`function isiPadoriPhone() {
    return (
        (navigator.userAgent.match(/iPad/i) != null) ||
        (navigator.platform.indexOf("iPhone") != -1) ||
        (navigator.platform.indexOf("iPod") != -1)
        )
}`

(I don't want to trigger an Autosave every time the mouse moves across the TinyMCE control if it is not on an iOS device.) 

Its not ideal, but so far it seems to work.

**Comment by dblVs** [comment]
@chriscfox Thank you so much dude! YOU ARE A LEGEND!

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
