### ISSUE TITLE
Inline Editor Fullscreen not working

### ISSUE THREAD

**Issue by CaptinJackSparow** [tinymce/tinymce#2474]
With using the inline editor the fullscreen capabilities seems to have stopped since I updated to tinyMCE 4.2.7.
Even though the plugin and toolbar options are there, no button when using the inline editor shows. I tried to trigger it so that it would launch fullscreen as soon as it was initialized and still no fullscreen. It worked before.

**Comment by spocke** [comment]
Not sure what you want the editor to do when you switch to fullscreen in an inline environment.

**Comment by CaptinJackSparow** [comment]
Well would be so that one could see all the content inline, because I'm experiencing something that I believe is a problem in my code with the editor... 
Which because the project I am working on is very large, I currently don't have the time to figure out what the exact issue is. Which the issue is that when using the inline editor when I get near to the bottom of the editable div, the editor controls jump way down the screen and out of visibility, unless I scroll down with the scroll bar. Not sure if this is because I'm using a antiscroll plugin around the outer div or if I'm missing something like I noticed on the tinyMCE site called a fieldset wrapped around the div. 
Is just a little strange and thought that if there was the fullscreen, that one could just click on that if they are having issues, but I guess just removing the inline for now works. :)

**Comment by CaptinJackSparow** [comment]
Yep, actually just found out why it does that, is because of the antiscroll where two divs have a set height that are nested inside each other then the editable div is inside that and for some reason the inline editor doesn't seem to like that... :(

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
