### ISSUE TITLE
https changed into http when pasting https schemed youtube clip into media source

### ISSUE THREAD

**Issue by Doz93** [tinymce/tinymce#2475]
Hello.

I've discovered an issue when embedding a youtube clip by using the media plugin. For some reason the embedded link is changed to http://.. instead of https:// when I paste an original youtube link into the source dialogue. But it keeps the https scheme if I either paste the iframe directly into the embed tab dialogue or if I take the embed link instead of the original youtube link and paste it into the source dialogue. 
![youtubeoriginallink](https://cloud.githubusercontent.com/assets/9719878/11207277/97c124a4-8d14-11e5-89e1-b01c77e6583c.PNG)

![linkchangedtoembedded](https://cloud.githubusercontent.com/assets/9719878/11207287/a9d75abe-8d14-11e5-935f-a24ac0a2eb98.PNG)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
