### ISSUE TITLE
Pasting Excel table regression from 4.1.x

### ISSUE THREAD

**Issue by varoot** [tinymce/tinymce#2477]
On v4.2.x, pasting some tables from Excel generates wrong HTML. All cells become one row.

This does not happen to all Excel files, and I'm not sure what caused this on Excel side but I have a file that will cause this error uploaded here: https://www.dropbox.com/s/3cwmo5kpspteviv/Excel%20bug%20TinyMCE.xlsx?dl=0

If you copy and paste the four cells in v4.1.x, it displays correctly like:
A  B
C  D

But in v4.2.x, they become:
A  B  C  D

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
