### ISSUE TITLE
Japanese Kanji characters can not be entered in the table

### ISSUE THREAD

**Issue by emaeba** [tinymce/tinymce#2479]
Hi

We're using the TinyMCE4.28.
IE11 or if you use the Microsoft Edge, 
Japanese Kanji characters can not be entered in the table.

**Comment by katoxp** [comment]
I'm using ver.4.30.

fix line:15640 in tinymce.js 

< if (selectedElm && selectedElm.nodeName == "TALBLE") {
---
> if (selectedElm && selectedElm.nodeName == "TALBLE" && e.keyCode != 229) {

**Comment by Xiphe** [comment]
seems to be duplicate of or related to #2371 

i can confirm the issue, see [steps to reproduce](https://github.com/tinymce/tinymce/issues/2371#issuecomment-162834843)

**Comment by blackcathikari** [comment]
We've taken a look and agree that this is probably a duplicate. Please take a look and let us know if you think it isn't. Thanks, the TinyMCE team.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
