### ISSUE TITLE
mceNotEditable incorrect delete

### ISSUE THREAD

**Issue by davidemoro** [tinymce/tinymce#2480]
Let's consider the following markup:
```
<p class="mceNonEditable">Not editable<span class="mceEditable">EDITABLE</span>Not Editable</p>
```
How to reproduce:
* go here (same behaviour occurs with tinymce 4) http://www.tinymce.com/tryit/3_x/noneditable_content.php
* put the above markup in HTML mode
* place the cursor after “NoteditableEDIT”<cursor>
* select the “Not Editable EDIT” pressing Home (jump on the start of the line or randomly using arrow keys to the start of the line)
* press delete

You'll obtain: **ABLENot Editable** 

See forum discussion here:
* http://www.tinymce.com/forum/viewtopic.php?pid=117817

Tested with Firefox 42.0

**Comment by spocke** [comment]
Is this still a problem with 4.3.0 since it's a complete rewrite of this plugin?

**Comment by davidemoro** [comment]
Hi @spocke,

thank you.
I'm sure I've tested on the previous moxiecode platform but probably I haven't picked the latest version.

I've tested it on codepen: it works fine with 4.0.
And the 4.3 version looks great:
* http://codepen.io/davidemoro/pen/EVBmYy
