### ISSUE TITLE
Formatting is not applying to bullets.

### ISSUE THREAD

**Issue by SoumyaWeb** [tinymce/tinymce#2483]
Hi,
Please follow the below error steps
1.Go to http://www.tinymce.com/
2.Select the bulleted contents inside the editor.
3.Click on allign center.
4.Only text against bullet is centre aligned and not the bullet itself.
![image](https://cloud.githubusercontent.com/assets/15976035/11331221/b7f5ed3c-91af-11e5-81d7-1586572c6ef1.png)

Thanks & REgards,
Soumya Kanta Nayak

**Comment by alecpl** [comment]
Confirmed. Looks like regression in 4.3.

**Comment by SoumyaWeb** [comment]
Issue persists in 4.3

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
