### ISSUE TITLE
Table resize regression in 4.3.0

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#2485]
When you resize the table with dragginig, the table height stops moving too early. Probably it takes table toolbar height into account, but it shouldn't.

Steps:
1. Create a table with e.g. two rows
2. Resize it to be big
3. Make it smaller by dragging right-bottom corner, move to the top and see that the dotted border stops moving at some point, but too early. Not like in 4.2.

**Comment by jhaines** [comment]
This particular regression has been fixed.  But there's still an underlying issue with the controlselection code.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
