### ISSUE TITLE
Copying/Pasting an image insert content from an attribute value instead of cloning image in Chrome,Edge

### ISSUE THREAD

**Issue by neexite** [tinymce/tinymce#2487]
1. Set the attribute 'alt' for an image using UI("Image description"): 
> &lt;html&gt; &lt;head&gt;&lt;/head&gt; &lt;body&gt; &lt;h1 &gt;Welcome&lt;/h1&gt; &lt;/body&gt; &lt;/html&gt;

2. Copy the image (Ctrl+C).
3. Paste it somewhere in the editor (Ctrl+P).

Expected: The copy of the image is pasted.
Actual: Only the "Welcome" is pasted 

-any attribute name
-source looks like
>&lt;img src=&quot;images/glyph-tinymce@2x.png&quot; alt=&quot;&amp;lt;html&amp;gt; &amp;lt;head&amp;gt;&amp;lt;/head&amp;gt; &amp;lt;body&amp;gt; &amp;lt;h1 &amp;gt;Welcome&amp;lt;/h1&amp;gt; &amp;lt;/body&amp;gt; &amp;lt;/html&amp;gt;&quot; width=&quot;110&quot; height=&quot;97&quot; /&gt;

-simple &lt;div contenteditable=&quot;true&quot;&gt;...&lt;/div&gt; have same behevior for copy(clipboard the same) but inserted as an image.
-Clipboard properies
Quick view: 
>&lt;html&gt; &lt;head&gt;&lt;/head&gt; &lt;body&gt; &lt;h1 &gt;Welcome&lt;/h1&gt; &lt;/body&gt; &lt;/html&gt;

HTML Format:
>Version:0.9
StartHTML:0000000141
EndHTML:0000000891
StartFragment:0000000177
EndFragment:0000000855
SourceURL:https://www.tinymce.com/
&lt;html&gt;
&lt;body&gt;
&lt;!--StartFragment--&gt;&lt;img src=&quot;https://www.tinymce.com/images/glyph-tinymce@2x.png&quot; alt=&quot;&lt;html&gt; &lt;head&gt;&lt;/head&gt; &lt;body&gt; &lt;h1 &gt;Welcome&lt;/h1&gt; &lt;/body&gt; &lt;/html&gt;&quot; width=&quot;110&quot; height=&quot;97&quot; data-mce-src=&quot;images/glyph-tinymce@2x.png&quot; caption=&quot;false&quot; data-mce-selected=&quot;1&quot; style=&quot;outline: black solid 1px; resize: none; color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 15px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);&quot;&gt;&lt;!--EndFragment--&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by spocke** [comment]
This only happens because there is a body element within the alt attribute not sure why you need that. Seems very edge case. We could fix this but it would require us to sax parse the clipboard contents instead of doing some regexp filtering.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
