### ISSUE TITLE
Do we really need base64 inside CSS?

### ISSUE THREAD

**Issue by dev-101** [tinymce/tinymce#2488]
here: https://github.com/tinymce/tinymce/blob/ddfa0366fc700334f67b2c57f8c6e290abf0b222/js/tinymce/skins/lightgray/Content.Objects.less#L38

It is not consistent with the work so far, plus I don't really like base64 inside CSS, or anywhere else for that matter, unless really necessary.

Thanks

**Comment by spocke** [comment]
Yes, base64 is better than small images for performance unless you use HTTP 2.0 so transparent stuff or small icons is fine to embed in css.

**Comment by dev-101** [comment]
Hi, thanks, but what is the purpose of this image that cannot be replaced with pure CSS? Unless I am wrong.
