### ISSUE TITLE
Unexpected behavior with noneditable plugin in 4.3.0 with multiple editors on the same page

### ISSUE THREAD

**Issue by triplejumper12** [tinymce/tinymce#2489]
If you have multiple editor instances on the same page and click on a noneditable piece, it either removes everything in the editor's element if it is the first editor instance, or copies the contents from the current editor to be in the first one.

If you go to http://fiddle.tinymce.com/dDeaab/3, run the code, and click on "not editable" it triggers the unexpected behavior which is pretty obvious.

This just started happening in 4.3.0 with the new noneditable plugin. Can be reproduced in Chrome, Firefox, Safari, and Edge on Linux, Mac, and Windows.

**Comment by spocke** [comment]
Fixed this one. So we will release a 4.3.1 probably today. Thanks for reporting this one.
