### ISSUE TITLE
Table resize = big height in 4.3.0

### ISSUE THREAD

**Issue by chrispcb** [tinymce/tinymce#2492]
When you resize the table by dragging right-bottom corner to the bottom, the table height is very big.

Steps:
1. Create a table with e.g. two or 4 rows and columns
2. Resize by dragging right-bottom corner to the bottom, (or to the bottom right)
3. Stop resize, table's height is very big.

**Comment by jhaines** [comment]
This has been fixed in master and should be in the 4.3.1 release soon.  Thanks for the report.
