### ISSUE TITLE
[4.3.0] Table toolbar on top of first table rows

### ISSUE THREAD

**Issue by thomich** [tinymce/tinymce#2494]
If you add a table and edit first rows, you can't cause table toolbar is on top of first rows.

How to reproduce
1. go to https://www.tinymce.com/
2. add a table with 4 colums and about 16+ rows, you should get scroll bar inside editor
3. scroll to top and try to enter data

What happens
you can't edit first rows
![shot-selection-007](https://cloud.githubusercontent.com/assets/4398840/11392851/a057cd9a-935c-11e5-97d5-e392dfa9222e.png)

Solutions
1. give option to disable table toolbar
```
table_toolbar_enabled: false;
```

2. move/hide table toolbar if cursor is behind it

3. add a icon/option, to hide the table toolbar temporary

**Comment by alecpl** [comment]
Or make the toolbar draggable.

**Comment by spocke** [comment]
Yes, we need to think this one over. Could in theory move it depending on where the caret is at or allow it to be at the bottom but out side of the content view port.

**Comment by spocke** [comment]
I don't think we manage to fix this one for 4.3.1 that we probably will be releasing tomorrow.

**Comment by enniob** [comment]
Is it possible to remove the table toolbar? I have the same issue

**Comment by cgoess** [comment]
We have the same issue. 
You can turn the table toolbar off by setting the option `table_toolbar` to an empty string (https://www.tinymce.com/docs/plugins/table/#table_toolbar).

**Comment by CodeOfDavid** [comment]
+1 This is still an issue.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
