### ISSUE TITLE
Some content of editor take place out

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#2495]
When sometimes i insert html templates into editor tinymce,i have such picture: 
![screenshot_1](https://cloud.githubusercontent.com/assets/14040818/11397887/7fd11f62-9385-11e5-97e2-345d945617c6.png)
How i can correct it?

**Comment by spocke** [comment]
Huh. What browser is this happening in. Could you provide steps for us to reproduce it thanks.

**Comment by fyrkant** [comment]
Never got any more information, closing the issue.
