### ISSUE TITLE
Bullets inside tables in Word get converted to middot

### ISSUE THREAD

**Issue by grahammmiles** [tinymce/tinymce#2497]
When pasting a table from Word, bulleted lists are converted to middot and non-breaking spaces.

Expected behaviour: Word bullets should convert to ul / li etc.

Noticed in v4 branch, including latest v4.3

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
