### ISSUE TITLE
TinyMCE 4 : tinymce.activeEditor.selection.getContent() Wierd Behavior

### ISSUE THREAD

**Issue by vindubey05** [tinymce/tinymce#2499]
I am working on TinyMCE 3.x to 4.x migration. I have encountered a specific issue and could not find any means of resolving it and therefore posting it as issue here - 

So I have an editor which is filled with data like this 

< p > Hello hi how are you 1000 < /p >

When I select on '1000', the onselect event is defined and inside it, the below code is writeen 
var formattedContents = tinymce.activeEditor.selection.getContent();

Here the problem is that tinymce.activeEditor.selection.getContent() returns < div > 1000< /div > and not 1000.

This is causing issues in the application.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
