### ISSUE TITLE
Image + Ordered list Bullets overlap

### ISSUE THREAD

**Issue by Mangesh-P** [tinymce/tinymce#2500]
I am left aligning the embedded image and on the right trying to put the ordered list 
but doing so overlaps the ordered list on top of image.

Is there a way to fix it without using the tables.

![codepen](https://cloud.githubusercontent.com/assets/10228993/11407515/328f52ae-9368-11e5-9396-f31d5c63d6f7.png)

**Comment by tinydylan** [comment]
Hi,

This rendering is controlled by the [CSS list-style-position](https://www.w3schools.com/css/css_list.asp) attribute. What you're seeing is the how browsers render when list-style-position is set to "outside", whereas you want it set to "inside". 

According to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position) different browsers choose a different value for their default, so you may wish to set a value yourself in the CSS.

If you look at [this codepen](https://codepen.io/tinymce/pen/KKdMbMX), I've added this style to the [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) option when initializing TinyMCE. You could alternatively add this to a stylesheet specified by [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_css). 

Unfortunately, TinyMCE doesn't have a button to change the list-style-position attribute. We could consider this as a feature request.

Hope this helps.
