### ISSUE TITLE
Media plugin new behaviour

### ISSUE THREAD

**Issue by jahudka** [tinymce/tinymce#2501]
The media plugin now always inserts a live preview of the embedded content; this is supposedly configurable via the "media_live_embeds" option as per the docs, but that isn't actually true - indeed searching the repository for the string "media_live_embeds" yields no results and as the docs state the default behaviour is to show the live previews. But that means that any embed with autoplay will start playing automatically when the editor is shown; imagine having multiple editors on the same page with autoplay embeds in them.. not to mention that the UX of not being able to select / edit the embed in this new "live preview" mode kind of sux.

**Comment by spocke** [comment]
Yes, you where right I renamed the option to match the docs.

They can be selected that's the whole point also youtube doesn't autoplay what stuff are you embedding that auto plays.

If they can't be selected then please create a new ticket with steps for us to reproduce that.

**Comment by jahudka** [comment]
Thanks!

YouTube, like most of the embeds that I know, *does* indeed support autoplay via the "autoplay" GET parameter in the iframe URL, by the way.

And how do you select an embed / iframe in the editor when live preview is on? With live preview I'm clicking *inside* the iframe so as far as I know there's no way the editor could catch that click and react to it (since cross-origin restrictions apply). I *can* select the iframe using the keyboard, but then it still doesn't behave like a selected "object", e.g. there are no resize handles etc. I don't think it's a bad feature to have, I'm just arguing that maybe it shouldn't be on *by default*.

Thanks for the fix again!

**Comment by spocke** [comment]
We wrap the iframe in a span with a shim placed on top of it so you click on that shim to select the iframe. I guess you either have a cache issue or some custom skin blocking that shim from working properly.

Would appreciate if you could help me understand why it's not working as it should could be some browser specific bug or similar as well.

**Comment by jahudka** [comment]
Aha, okay I see now. The problem is the skin: I'm using a custom skin I've generated at http://skin.tinymce.com and I've noticed before that the generator doesn't include everything it should (for example the notifications styles are missing in the outputted CSS). I've now tried compiling the skin from source and there are still no styles for the .mce-shim class name in the generated skin.min.css.

**Comment by spocke** [comment]
I updated the skin site with the latest less files. Sorry about that. I guess we should inform users to re-generate skins when we release minor feature releases.

So regenerate the skin and it should work fine. So I'm closing this one.
