### ISSUE TITLE
File names of images pasted / dropped into editor are lost

### ISSUE THREAD

**Issue by jahudka** [tinymce/tinymce#2502]
When I drop an image from Finder to the editor or paste it from clipboard the script has access to the underlying File object and it should be able to get the name of the dropped / pasted file, but that information isn't stored anywhere and the uploaded file then has a "generated" name like blob1.png. Fixing this from outside of TinyMCE is practically impossible, while fixing this from within would only take a couple of changes.

**Comment by jahudka** [comment]
(hope I didn't botch this somehow, sorry, this is one of my first attempts at contributing to an OSS project ^_^)

**Comment by fyrkant** [comment]
I think this was fixed some while ago, but if I'm wrong please open up a new issue.
