### ISSUE TITLE
make widget / popup windows mobile friendly

### ISSUE THREAD

**Issue by dev-101** [tinymce/tinymce#2506]
Hi, currently many widget / popup windows are NOT mobile friendly, and particularly, since they are fixed in position, the widget windows gets centered with areas falling outside viewport . Most critical (beside the content itself), are the CLOSE / OK and "x" buttons.

For example: view source; preview; color picker (vertical mode seems to be much better); table properties and many other panels are too large for 320-480 px wide screens. Yes, they can be dragged around to move "x" into visible part of the screen, but how many users will figure that out? Also, drag does not really work smooth on touch screens, as it does with mouse on desktop.

**Comment by fyrkant** [comment]
We now have a [mobile theme](https://www.tinymce.com/docs/themes/mobile/) that we recommend for mobile editing.
