### ISSUE TITLE
Superscript/Subscript adding illegal characters into the edior.

### ISSUE THREAD

**Issue by salimmhd01** [tinymce/tinymce#2509]
When superscript/subscript button selected, an invalid character - &#65279; - has been added into the Editor. Please look at the screenshot and advise.

![superscript-tinymce](https://cloud.githubusercontent.com/assets/16051566/11447748/7d9e9e14-9519-11e5-9c84-015165b33158.png)

**Comment by spocke** [comment]
How do I reproduce this on fiddle.tinymce.com or provide steps for me to reproduce it. Thanks.

**Comment by salimmhd01** [comment]
Hi Johan,

Go to format – dropdown – and select superscript.
Then go to Tools – dropdown – and select Source Code.

But I don’t see this issue in fiddle.tinymce.com

[cid:image002.png@01D12911.D8AB8FC0]

Thanks,
Salim.

**Comment by salimmhd01** [comment]
Hi Johan,

Do you have any update on below one ?

Thanks,
Salim.

From: Salim Muhammed
Sent: Monday, November 30, 2015 10:54 AM
To: 'tinymce/tinymce'; tinymce/tinymce
Subject: RE: [tinymce] Superscript/Subscript adding illegal characters into the edior. (#2509)

Hi Johan,

Go to format – dropdown – and select superscript.
Then go to Tools – dropdown – and select Source Code.

But I don’t see this issue in fiddle.tinymce.com

[cid:image002.png@01D12911.D8AB8FC0]

Thanks,
Salim.

**Comment by spocke** [comment]
Can't fix this one until we can reproduce it on a fiddle on for example fiddle.tinymce.com could be some form of integration issue since it's not happening out of the box. But impossible to tell by guessing. Thanks.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
