### ISSUE TITLE
BUG with div being removed

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#2510]
Hi,

This bug causes me a lot of problems. Suppose you have the HTML codes below in your tinymce with default configuration:

OPTION 1)
    `<div style="background:#FF0000;">HI</div>`
OPTION 2)
    `<div style="background:#FF0000; float:left;">HI</div>`

In the first case, when I select the word HI, hit the BACKSPACE key and type a new text everything will work fine, I mean, the element with background "#FF0000" will be kept, as expected.
In the second case, if I select the word HI, hit the BACKSPACE key and type a new text the element with background "#FF0000" will disappear.

This is not an expected result cause in both cases I would like the element to be kept. 

Any idea how to solve this problem?

**Comment by cauburtin** [comment]
I don't see your html

**Comment by gilperon** [comment]
Sorry @cauburtin I edited the question and made the code visible. How you can help me :)

**Comment by cauburtin** [comment]
make a quick fiddle/jsbin with those 2 html elements and tiny mce, please

**Comment by gilperon** [comment]
Sorry, -> http://codepen.io/anon/pen/GpVWrj

With this link you can reprocude it :)

**Comment by cauburtin** [comment]
yeah I tried other options http://s.codepen.io/crl12/debug/aveJRb but same bug occurs. Idk for the moment sorry

**Comment by gilperon** [comment]
Thank you! The bug also happens if you have div with "display:inline-block". If you try to remove the content of the div, when it gets empty the tag gets removed which is not desired. Hope you can find a fix :) If you cant find, could you please tell me which file manages the keyboard events so I can change it and fix it myself?

**Comment by spocke** [comment]
Yes, I guess we will have to completely take over the broken browser behavior here.

**Comment by gilperon** [comment]
If you need help I will be really glad to help you. I appreciate your really nice work, my company wouldnt be the same without your really nice tinymce which works really great with CDN. That's really awesome.

**Comment by tinydylan** [comment]
Hi,

I can't reproduce this behaviour in TinyMCE 5. It's most likely something that has been fixed since this issue was logged. I'm going to close out this issue for now, but if the problem continues to occur, please let us know.
