### ISSUE TITLE
ctrl+x/ctrl+v and drag don't preserve style

### ISSUE THREAD

**Issue by caub** [tinymce/tinymce#2511]
http://codepen.io/crl12/pen/pjMeqq?editors=110 Unlike a default contenteditable, the cut/paste and the drag/drop don't preserve the style of elements, even copy/paste don't always work well (try to copy the 'World' in blue in the tinymce area, and paste it, it loses its style too (tested on Chrome)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
