### ISSUE TITLE
renderEmptyBlocksFix break my page 

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2512]
not iframe mode
Inline: true
div contenteditable: true
browser: ie11

renderEmptyBlocksFix  function push styles in my page head
"
p:empty, div:empty, h1:empty, h2:empty, h3:empty, h4:empty, h5:empty, h6:empty {
    padding-right: 1px !important;
}
"

decision: 
add unique editor selector in renderEmptyBlocksFix()

but better will be not push it in head, just add this styles in theme or  in skin

**Comment by fyrkant** [comment]
Hi! I am closing this issue due to old age.

If you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.  

Thank you!
