### ISSUE TITLE
Turbolinks integration not working

### ISSUE THREAD

**Issue by sebastianzillessen** [tinymce/tinymce#2513]
Hi. 
In one of my applications I use `tinymce`. Now we wanted to include `Turbolinks` into that project.

We use the `jquery-turbolinks` gem to handle the process of replacing all `$(function() ...)` with the according events from turbolinks. For the rest of the application everything works. 
But when I change from a page to a page where there is a `tinymce`-editor, I always get this error:

```
Uncaught TypeError: c is not a function
_.init @ tinymce.min.js?body=1:8
(anonymous function) @ tinymce.min.js?body=1:8
(anonymous function) @ tinymce.min.js?body=1:4
o @ tinymce.min.js?body=1:3
m @ tinymce.min.js?body=1:4
(anonymous function) @ tinymce.min.js?body=1:4
n @ tinymce.min.js?body=1:4
```

unfortunately I don't have the possibility to include the src code of tinymce as we use then `tinymce-dist` repository (over Rails asset).

Did anyone have similar problems?

Thanks a lot.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
