### ISSUE TITLE
JIRA comma separated URLs conflict

### ISSUE THREAD

**Issue by andreyluiz** [tinymce/tinymce#2514]
I'm using TinyMCE with a Jira plugin.

Jira has a very especific way to provide js and css files. It "compresses" everything in several files called batch.js, batch.css, etc. TinyMCE is being compressed this way to, except for the skin.min.css and the content.min.css.

To provide acess to theses static css files, Jira creates URLs based on contexts defined in the atlassian-plugin.xml, which is a descriptor for the Jira Plugin. For example, if I have the following:

```
<web-resource key="ktm-tinymce" name="TinyMCE rich text editor">
  <context>jira.view.issue</context>
  <resource type="download" name="skins/" location="com/example/frontend/tinymce/skins"/>
</web-resource>
```

It will provide my /skins content in a URL like this:

http://jira.example.com/s/e76444e9fda7bacbc2cd96106378a4ce-CDN/en_US-qxexoz/64016/110/f1107cbf0c147263f997c4a09fd4a9f0/_/download/contextbatch/js/jira.navigator.simple,jira.navigator.advanced,jira.view.issue,atl.general,jira.navigator.kickass,jira.global,jira.general/skins/<my content>

Notice that there are several contexts comma separated in this URL, like jira.navigator.advanced, jira.navigator.simple, jira.view.issue (which is the one I declared in the atlassian-plugin.xml), etc. In other words, the web-resources with these contexts will be in the folder "js/jira.navigator.simple,jira.navigator.advanced,jira.view.issue,atl.general,jira.navigator.kickass,jira.global,jira.general". That's the case of my /skins folder.

That's where my problems start to appear.

There's a method in TinyMCE called loadCSS which have the piece of code below:

```
7738 each(url.split(','), function(url) {
7739   var link;
7740 
7741   url = Tools._addCacheSuffix(url);
7742
7743   if (self.files[url]) {
7744     return;
7745   }
7746
7747   self.files[url] = true;
7748   link = self.create('link', {rel: 'stylesheet', href: url});
7749
7750   // IE 8 has a bug where dynamically loading stylesheets would produce a 1 item remaining bug
7751   // This fix seems to resolve that issue by recalcing the document once a stylesheet finishes loading
7752   // It's ugly but it seems to work fine.
7753   if (isIE && doc.documentMode && doc.recalc) {
7754     link.onload = function() {
7755       if (doc.recalc) {
7756         doc.recalc();
7757       }
7758
7759       link.onload = null;
7760     };
7761   }
7762
7763   head.appendChild(link);
7764 });
```

It takes a big string with several URLs comma separated and breakes it in URLs to create <link> tags.

Because Jira uses comma to separate the contexts in the URL, this code separates de entire URL in invalid URLs. The result:

![Errors](http://i66.tinypic.com/wly8pj.png)

Notice that the content after the /browse is the exact result of the URL separated in the loadCSS function. Because some of these separated content were just a string (e.g. jira.view.issue), and the intent of this function is to create a link, the browser concatenates the "http://jira.example.com/browse", which is the current path.

According to [this answer in StackOverflow](http://stackoverflow.com/a/1547940), which refers to the [RFC-3986](https://tools.ietf.org/html/rfc3986), the comma is a valid character in a URL.

I don't know if the problem is clear. If not, I can provide more in dept details.

Is there a way to workaround this, or it is indeed a bug?

Thank you. :)

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
