### ISSUE TITLE
Make ResizeBars of table plugin optional

### ISSUE THREAD

**Issue by adoerler** [tinymce/tinymce#2515]
Hi,

sometimes one does not want to store width/height of the table and its cells.

Therefore it would be great to have the ResizeBars plugin optional.
My current workaround is to delete the style attributes of table, tr, td and th before saving the contents.

I'm talking about the newest table plugin in release 4.3.1.

Kind regards and many thanks for the great table plugin!
Andreas

**Comment by jhaines** [comment]
Setting the new table_resize_bars configuration property to false will disable the resize bars.  Thanks for the report.

**Comment by eweso** [comment]
This is still not in the documention and should be added! For me the resize bars are not working. They are always inside the columns and prevent the user from writing text. Maybe it's because of the flex layout of my application, I don't know yet. But this helped me a lot.

**Comment by speehive-admin** [comment]
https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#object_resizing

**Comment by kishoresahas** [comment]
**object_resizing**
https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#object_resizing
This options allows you to turn on/off the resizing handles on images, tables or media objects. This option is enabled by default and allows you to resize table and images. You can also specify a CSS3 selector of what you want to enable resizing on.
