### ISSUE TITLE
Additional options to specify padding, margin, hspace, vspace, border etc for image

### ISSUE THREAD

**Issue by AmitPatel-BoTreeConsulting** [tinymce/tinymce#2516]
Image toolbar supports setting width and height of an image in image editing toolbar.

It would be great if support for following also added.
-  padding
- margin
- hspace
- vspace
- border

**Comment by HaraldWalker** [comment]
You can enable advanced image settings.
https://www.tinymce.com/docs/plugins/image/#image_advtab
It will offer you hspace, vspace, border and style. Compared to 3.x version the vertical alignment options are gone and I've already received a complaint about that from users.

**Comment by spocke** [comment]
Vertical alignment can be done with the formats menu or classes so this is not something we will bring back. So some of these things are available though the advanced tab. So closing this one.

**Comment by HaraldWalker** [comment]
Yes, the 2nd example on https://www.tinymce.com/docs/configure/content-formatting/#style_formats
shows how to set custom styles for an image element. It is more user friendly like that and those users that know html/css can still set custom styles in the style field of the advanced tab.
