### ISSUE TITLE
TinyMCE 4.3.1 - IE 11 - Text not selectable by double click

### ISSUE THREAD

**Issue by adoerler** [tinymce/tinymce#2517]
Hi,

after Upgrading to 4.3.1 it is no longer possible to select text by double clicking it.
This happens in IE11, see https://www.tinymce.com/docs/demo/basic-example/
This problem did not exist in 4.2.8.
It is working in Chrome and Firefox.

Does anyone know, what is causing this new behaviour?

Kind regards
Andreas

**Comment by spocke** [comment]
This has to do with the async selection model IE has. So fixed in this commit: https://github.com/tinymce/tinymce/commit/e6062567083bb41a88fc1d4e363b82b694b8bb87
