### ISSUE TITLE
TinyMCE 4.3.1 - Table plugin - IE11 &nbsp; in cells

### ISSUE THREAD

**Issue by adoerler** [tinymce/tinymce#2518]
Hi,

if you insert a new table, IE1 places &nbsp; into each cell.
I think this happens in TableGrid.js
```javascript
					// Add something to the inner node
					if (curNode) {
						curNode.innerHTML = Env.ie ? '&nbsp;' : '<br data-mce-bogus="1" />';
					}
```

As far as I know this has been added to be able clicking into a cell (in older IE versions).
If you add a column or row, the &nbsp; is not added and (at least in IE11) selecting cells is no problem.

As an excample you could try it in the full featured demo: https://www.tinymce.com/docs/demo/full-featured/

Do you see a problem or any side effects if &nbsp; would not be added in newer versions of IE?

Kind regards
Andreas

**Comment by jhaines** [comment]
https://github.com/tinymce/tinymce/commit/de92f166178ecb0609ba45413c2732c29bd9d5e6 This has been fixed in this commit.  Thanks for the report.

**Comment by spocke** [comment]
The fix is here:
https://github.com/tinymce/tinymce/commit/18fbfcac2f6ab2b9e4abffc2093cee881217ab0b
