### ISSUE TITLE
Tables Plug-in: Cell drag to resize does not trigger 'change' event

### ISSUE THREAD

**Issue by matthewwallace** [tinymce/tinymce#2521]
Dragging the entire table continues to trigger the change event; however, the new cell resize dragging does not trigger the same event.

**Comment by spocke** [comment]
Yes, it should add an undo level for each resize I guess.

**Comment by obuliraj323** [comment]
if any possibility to resizing cells without using the editor menu

**Comment by spocke** [comment]
What do you mean as of 4.3 you can just drag the cells to resize.

**Comment by obuliraj323** [comment]
yes i change it 4.3 its work fine. thanks

**Comment by obuliraj323** [comment]
Another issue. I copy the table in a word document into the editor. And click submit then its send a mail. But in mail body table width differs and some column contents are wrapped. If any options are there to display what we are copied.

**Comment by jhaines** [comment]
This has been fixed.  Thanks for the report.

**Comment by obuliraj323** [comment]
tinyMCE editor shows error as "NS_ERROR_UNEXPECTED:" in firefox when calling a editor second time without page reload. anyone plz help me.
