### ISSUE TITLE
TinyMCE 4.3.1 - Table plugin - caption height ignored when toolbar is under table

### ISSUE THREAD

**Issue by zmoky** [tinymce/tinymce#2523]
When then the floating table toolbar is displayed under the table the height of  the caption is not calculated and the toolbar overlaps the table.

Reproduce: Set a table caption text. Insert a table and force the toolbar to be displayed under the table by putting the table to be the first element in the document.

![capture](https://cloud.githubusercontent.com/assets/5340581/11528170/c4b91fa4-98ed-11e5-8d73-578867688c39.PNG)

**Comment by spocke** [comment]
Yes, FF seems to give the wrong size of the table here. This is a firefox bug that we might need to work around but also report upstream.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
