### ISSUE TITLE
Removing style tag from HTML output

### ISSUE THREAD

**Issue by Brunes** [tinymce/tinymce#2524]
Hi guys,
I searched everywhere on google, I found something but my problem isn't solved. I have problem with removing "style" tag from HTML. When I set style tag float on image and when I save a content, TinyMCE remove "style" tag from html. Is marked as [removed].

Example:
```
<img [removed] left;" src="xxx/uploads/2015/10/cut-redye.jpg" alt="cut redye" width="66" height="96">
```

I'm using latest TinyMCE.
My settings:
```javascript
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
  selector: 'textarea',
  height: 500,
  valid_elements : '*[*]',
  plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code'
  ],
  toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image'
});
</script>
```

Can somebody help me?
It's very important for me.
Thanks and sorry for my Slovak-English. :)

**Comment by Brunes** [comment]
Resolved. Is problem with CodeIgniter - xss_clean

**Comment by spocke** [comment]
Ok. Nice to know that it wasn't a tinymce problem. Closing.
