### ISSUE TITLE
nonEditable plugin scrolling bug on firefox

### ISSUE THREAD

**Issue by ryandang** [tinymce/tinymce#2525]
http://plnkr.co/edit/4vL2JiCO16f6BYAhTidH?p=preview

On Firefox version 38.4.0, When I click on the editable section inside the nonEditable block, it scrolls to the bottom. It works fine on Chrome and Safari

STR:

1. Click on the blank area to select the whole noneditable block
2. click on "Editable Content"

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
