### ISSUE TITLE
Pasting divs makes alignment mess up.

### ISSUE THREAD

**Issue by programmin1** [tinymce/tinymce#2527]
As you can see in this fiddle, pasting content with divs in it usually puts the editor in a weird state due to nested divs: http://fiddle.tinymce.com/2lfaab

Copy all content divs, paste it after the last div,
then click an alignment button with the cursor near the first c.
It aligns the whole outer div, multiples lines!

Is there an option to normalize divs and make them the top level when pasted?
It seems this happens in both inline and iframe mode.

**Comment by spocke** [comment]
Since divs within divs are valid HTML we can't normalize that since then we would get bug reports of it normalizing and not keeping the nested structure. You can however augment the HTML5 schema to not allow div within div or use P tags for line breaks then all these problems goes away.

**Comment by programmin1** [comment]
How do you "augment the HTML5 schema"? And why not just move divs that have no id, no class or specific styling, to just after the div they were inserted in, along with the nodes after?

**Comment by spocke** [comment]
Use the valid_childen config option and exclude div from div. Yeah, if we do that then we get a bug report of us removing nested div elements. It's like a wack a mole game you bash one thing another one pops up.

**Comment by programmin1** [comment]
Exactly, and that would break wp-views in Wordpress for example - that's why I suggest that when they paste line-of-text divs (with no id, class) into a div (with no id, class), contents could be appended after - or perhaps the cursor could be set to just after the outer div, before paste.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
