### ISSUE TITLE
TinyMCE 4.3.1 noneditable plugin should not encode contents

### ISSUE THREAD

**Issue by adoerler** [tinymce/tinymce#2529]
Hi,

the new option `nonEditableRegExps` of the all new `noneditable` plugin is great.
Unfortunately the function `replaceMatchWithSpan` encodes the macht before reinserting it into the noneditable span-tag.

If you want to use this plugin for an icon font, e.g. `nonEditableRegExps = [/(<i class="my-symbolfont-[a-z]+?">.<\/i>/g]`, the font is no longer displayed, as the tag gets encoded.
    

While it's perfectly okay (and necessary) to encode the value bevor placing into `data-mce-content`, it should imho be left untouched when inserting back into the span-tag.

What do you think?

Kind regards
Andreas

**Comment by spocke** [comment]
Looking over this it seems to be decoding it properly when adding it back. At least I couldn't reproduce it.

**Comment by adoerler** [comment]
Hi,

thanks for looking into this.
I think it's easier to understand using jsfiddle.
Please have a look at:
https://jsfiddle.net/p9syzwj6/2/

Place one of the two available icons.
If you than remove the `noneditable_regexp` parameter you'll see how it should look like in the contents. 

Kind regards
Andreas

**Comment by spocke** [comment]
You don't need noneditable for that I updated your example to just use cE=false.
https://jsfiddle.net/p9syzwj6/3/

**Comment by adoerler** [comment]
Okay, thank you for pointing this out.
I've implemented it with contenteditable=false.

Have a nice weekend
