### ISSUE TITLE
TinyMCE 4.3.1 - Table plugin - shows table widget when tinymce inline is in table

### ISSUE THREAD

**Issue by sowirepo** [tinymce/tinymce#2530]
We use tinymce inside a table. When we enable tinymce inline, with the table plugin on, the table plugin pops up immediately. 

for instance with the following html
```<table><tr><td><div id="tiny"></div></tr></td></table>```

and initialising on the #tiny selector with the table plugin and inline=true, it goes wrong in 4.3.1.

**Comment by sztanpet** [comment]
a tiny repro for it, so we can add the verified tag sooner :)
http://plnkr.co/edit/HbrL3M95D6xsZjoBcxQd?p=preview

**Comment by jhaines** [comment]
This has been fixed in master.  Thanks for the report.
