### ISSUE TITLE
TinyMCE 3.x crashes Windows 10 Edge on repeated font change

### ISSUE THREAD

**Issue by jeffreymolina** [tinymce/tinymce#2531]
Repro steps:
Using http://archive.tinymce.com/tryit/3_x/full.php select a section of text and continuously change font until browser crashes (and refreshes).  Sometimes crash happens immediately other times this has to be done around 10 times in a row.

Windows 10 Edge crash info:
Fault bucket 133168225902, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.MicrosoftEdge_20.10240.16384.0_neutral__8wekyb3d8bbwe
P2: praid:MicrosoftEdge
P3: 11.0.10240.16384
P4: 559f3853
P5: EDGEHTML.dll
P6: 11.0.10240.16401
P7: 55b1a774
P8: c0000602
P9: 000000000053d636
P10: 

Attached files:
C:\Users\IEUser\AppData\Local\Temp\WER9E36.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Micros_5af5ccb5df211c4e69771399856eb7bd685ad796_fae04a53_09f3a133

Analysis symbol: 
Rechecking for solution: 0
Report Id: c42c83de-70f6-4ec4-a96c-99bfa950725f
Report Status: 0
Hashed bucket: bdbbf3a8de3c14ded870b7bf359e63e1

This also happens in Windows 7 IE11.
Crash info from IE11:

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: IEXPLORE.EXE
  Application Version:  11.0.9600.18057
  Application Timestamp:    55f8d3e4
  Fault Module Name:    MSHTML.dll
  Fault Module Version: 11.0.9600.18057
  Fault Module Timestamp:   55f8e889
  Exception Code:   c0000602
  Exception Offset: 006d6142
  OS Version:   6.1.7601.2.1.0.256.4
  Locale ID:    1033
  Additional Information 1: cbe9
  Additional Information 2: cbe91ba6982fc7aeceeb30dd896f08ed
  Additional Information 3: 60f9
  Additional Information 4: 60f92cbdcae1a015320f08ad480aa4db

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
