### ISSUE TITLE
Media plugin strips out characters from the Youtube Video id if it contains a hyphen

### ISSUE THREAD

**Issue by helloszabi** [tinymce/tinymce#2532]
If you paste a Youtube video with a hyphen in the id in the Media plugin dialog, then the plugin strips out the characters starting from the hyphen, and embeds a wrong Video ID containing only the first part of the string.

Test:
https://www.youtube.com/watch?v=wNRFE5J-4aE - **error**, result: wNRFE5J
https://www.youtube.com/watch?v=7V-fIGMDsmE - **error**, result: 7V
https://www.youtube.com/watch?v=_p8AsQhaVKI - **ok**, so the underscore is good to go

The corresponding line from the source code is this, if I'm correct:
https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/media/plugin.js#L18

And the regexp seems ok: http://regexr.com/3cbtc, but still, last part of the string is stripped out.

**Comment by spocke** [comment]
Fixed this issue.

**Comment by helloszabi** [comment]
Thanks @spocke!
