### ISSUE TITLE
Drag&Drop allows to move Text into contenteditable=false area when using IE11

### ISSUE THREAD

**Issue by adoerler** [tinymce/tinymce#2535]
Hi,

I've created a fiddle to reproduce the issue: https://jsfiddle.net/p9syzwj6/7/

* Open the fiddle in IE11
* Select one or more of the "x" characters
* Drag them over the Text "NONEDITABLE CONTENT" and release the mouse

Chrome and IE Edge will not allow to drop the text if the cursor is placed above contenteditable=false elements, IE11 does.

We have an icon font and our users are dragging text around in the editor. If they place them next to an web font icon, the content is moved into the i-tag instead behind/before.

Kind regards
Andreas

**Comment by spocke** [comment]
Fixed this one and released it.
