### ISSUE TITLE
tinymce.com/license: 404 - Unable to generate WebJar

### ISSUE THREAD

**Issue by damienbeaufils** [tinymce/tinymce#2537]
With the new version of tinymce.com website, the license with url http://www.tinymce.com/license could not be found. The are multiple occurrences of this url in [Gruntfile.js](https://github.com/tinymce/tinymce/blob/master/Gruntfile.js#L522).
Because of this 404, we are unable to generate [Bower WebJar](http://www.webjars.org/bower) for the new TinyMCE version, because it needs to check license in prerequirements.

**Comment by spocke** [comment]
We will look into this and make a redirect on the site. Thanks for the report.

**Comment by spocke** [comment]
We fixed this with a redirect to the github license file.
