### ISSUE TITLE
Add version 3.5.11 to Nuget

### ISSUE THREAD

**Issue by gentoo90** [tinymce/tinymce#2542]
Please publish `TinyMCE 3.5.11` and `TinyMCE.JQuery 3.5.11` in Nuget.
Currently only version 3.5.8 is published in nuget, so if user wants to get the bugfixes and can't upgrade to version 4, he must remove nuget package and install tinymce manually.

**Comment by spocke** [comment]
Nah. Update to tinymce 4 instead there is no reason to use that old version of tinymce. With the compat3x plugin 99% of all plugins work on 4.x.
