### ISSUE TITLE
Style tags get stripped

### ISSUE THREAD

**Issue by Fjan** [tinymce/tinymce#2545]
The `<style>` tags get removed from the output even when we set `extended_valid_elements: style`

This happens on all tested TinyMCE v.4 versions, which should be HTML5 compliant (Note that in HTML5 a style tag in the body is now [allowed](http://www.w3schools.com/tags/att_style_scoped.asp))

**Comment by spocke** [comment]
Yes, only when the scope attribute is specified.
http://www.w3.org/TR/html51/semantics.html#the-style-element

The schema logic can't currently handle edge cases like this so if you want style elements inline then augment the html5 spec by valid_children.

**Comment by Fjan** [comment]
Thanks, that work around will do for now

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
