### ISSUE TITLE
Insert video is breaking youtube url

### ISSUE THREAD

**Issue by afsadilson** [tinymce/tinymce#2547]
I have updated tinyMCE to the latest version and some youtube embed code is breaking at the insert moment.

```<iframe width="560" height="315" src="https://www.youtube.com/embed/K0n7I_HnV18?list=PLxmGWMXKfr9pdfc-Vxi81hZpNJyHJy8YA" frameborder="0" allowfullscreen></iframe>```

This embed code doesn't works, breaks after (_) underscore.

**Comment by spocke** [comment]
Underscore fixed in private branch.

**Comment by thaeriac** [comment]
@spocke If is in url - there is same problem.
Version 4.3.4
