### ISSUE TITLE
Not visible some Cell properties

### ISSUE THREAD

**Issue by pliasetski** [tinymce/tinymce#2548]
Hello,
If you open table cell options, some cell properties are not visible: https://dl.dropboxusercontent.com/u/73896408/cell-options.PNG
Is there a way to fix it?
Thanks, Pavel

**Comment by fyrkant** [comment]
Closing this as we've rewritten the Table plugin recently so old issues like this one is probably not applicable any more. If you still have an issue with Cell properties not showing up correctly please open up a new issue.
