### ISSUE TITLE
EventUtils.unbind is not a function

### ISSUE THREAD

**Issue by nikolas** [tinymce/tinymce#2549]
Using `tinymce.dom.EventUtils.unbind` in TinyMCE 4.3.1, I'm getting this error:

```
Uncaught TypeError: EventUtils.unbind is not a function
ed.addCursorWindow.onUnload @ plugin.min.js:163
tinymce.create._closeWindow @ plugin.min.js:179
(anonymous function) @ plugin.min.js:174
m.event.dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4
jquery-1.11.3.min.js:5 XHR finished loading: POST "http://localhost:8000/project/save/23929/".send @ jquery-1.11.3.min.js:5
m.extend.ajax @ jquery-1.11.3.min.js:5ProjectPanelHandler.saveProject @ projectpanel.js:763
(anonymous function) @ projectpanel.js:869
```

This is also happening when I call `EventUtils.clean`.

**Comment by spocke** [comment]
Could be some integration issue addCursorWindow is not part of tinymce. Also please use editor.on/off if possible.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
