### ISSUE TITLE
Tables [4.3.1]: Can't select text when border-collapse applied to table 

### ISSUE THREAD

**Issue by matthewwallace** [tinymce/tinymce#2552]
If a table applies CSSS:'border-collapse: collapse' and an associated cell applies no padding, text selection becomes a problem.  

When selecting text the first character closest to an inner cell border (first character of a line) may be un-selectable due to interference by the drag bar element.  Large font sizes may still be selectable.

If a solution to this issue is problematic providing a toggle to turn cell dragging on and off may help.  It would be best if such a toggle could be triggered at any time (not just on editor configuration).

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.
