### ISSUE TITLE
Tables error with chrome, at least with chrome 47

### ISSUE THREAD

**Issue by diolermore** [tinymce/tinymce#2554]
Hi, first of all, cool editor. I´m trying it and i thinks there is an error with tables and chrome. When you insert a table in chrome, it dosent insert a <p>, so editor becomes a bit crazy, yo cant insert another paragraph. In firefox and ie works properly. If the first thing you insert is a table, the <p> root element is also deleted. You will only have a table, while in explore and firefox you´ll have a table and a <p>.

**Comment by spocke** [comment]
Could you provide step by step instructions on how to reproduce this thanks?

**Comment by diolermore** [comment]
Sure. First of all i activate show blocks. Then I insert a table, for example 2x2. Now you can see that the <p> root element has dissapeard. Without creating a new <p> I insert and image in the first row of the table, for example. Or just make it big. Then, try to go to the next line. I usually write something and  when i mouse over the table, text dissapears. Iv e checked also in the examples from web.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
