### ISSUE TITLE
Custom build is broken

### ISSUE THREAD

**Issue by nazar-pc** [tinymce/tinymce#2555]
When building `4.3.2` with following command:

```
grunt bundle --themes modern --plugins advlist,anchor,charmap,code,colorpicker,contextmenu,fullscreen,hr,image,link,lists,media,nonbreaking,noneditable,pagebreak,paste,preview,searchreplace,tabfocus,table,textcolor,visualblocks,visualchars,wordcount
```

I'm getting build that starts with `tinymce.ThemeManager.add("modern",`, while TinyMCE core is expected. Because of this obtained build is broken, since `tinymce` and `tinymce.ThemeManager` are not defined yet at that point.

**Comment by nazar-pc** [comment]
Wow, running just `grunt` before it helps.
Maybe add this step as required to docs or generate `tinymce.js` if it doesn't exists enyway?

**Comment by spocke** [comment]
Yes, I guess bundle should throw an error if there is no core.

**Comment by nazar-pc** [comment]
Agree :+1:

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by nazar-pc** [comment]
@blackcathikari, but how did you test it?
Seriously:
```
git clone https://github.com/tinymce/tinymce.git
cd tinymce
npm install
grunt bundle --themes modern --plugins advlist,anchor,charmap,code,colorpicker,contextmenu,fullscreen,hr,image,link,lists,media,nonbreaking,noneditable,pagebreak,paste,preview,searchreplace,tabfocus,table,textcolor,visualblocks,visualchars,wordcount
```
Result will be:
```
Running "bundle:minified" (bundle) task
Fatal error: Could not find file: js/tinymce/themes/modern/theme.min.js
```

**Comment by nazar-pc** [comment]
I expect build process to identify that necessary files are not in place and create them automatically.

Maybe, just execute `bolt-init` (not sure about this) and `minify` tasks before `bundle` task as simple and reliable solution?

**Comment by dsakko** [comment]
Will reopen this for now.

**Comment by TuningGuide** [comment]
When I build and execute the tinymce.full.js and the browser runs into `defineGlobal("global!tinymce.util.Promise", tinymce.util.Promise);` I get a tinymce.util is undefined. Any ideas?

**Comment by TuningGuide** [comment]
#https://github.com/tinymce/tinymce/issues/3130
