### ISSUE TITLE
Update skin building documentation to use grunt instead of jake

### ISSUE THREAD

**Issue by meglio** [tinymce/tinymce#2561]
Currently, skin building documentation still refers to `jake` build tool:
http://archive.tinymce.com/wiki.php/Tutorials:Creating_a_skin

It says:

> Then go to the root directory of tinymce in a console and invoke "jake less" this command will automatically build css files out of the less files contained in the skins directories.

However, since some time ago, jake has been replaced by grunt.

**Comment by spocke** [comment]
Updated the new docs:
http://127.0.0.1:4000/advanced/creating-a-skin/
