### ISSUE TITLE
Backspace from the beginning of a line with strikethrough or underline removes the formatting

### ISSUE THREAD

**Issue by lycurgus** [tinymce/tinymce#2563]
With a strikethrough- or underline-styled line that's preceded by an empty line, backspacing from the beginning of the styled line (deleting the empty line) also removes the styling from the line.

This was observed in 4.2.6 but persists in the version on the front page of http://tinymce.com (which I assume is 4.3.2?).

Occurs in Chrome but not in IE9. Untested in other browsers.

**Comment by fyrkant** [comment]
This has been fixed since a while back!
