### ISSUE TITLE
Problems with media plugin

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2566]
Insert a image:
1. in smartphone the media box is greater than the viewport, its not responsive. I can't see submit buttons.
2. maybe, image should have style instead attribute height and width
   https://gist.github.com/simshaun/7592631#gistcomment-994764

EDIT: I have remove 3. because in css you can set for responsive design "img{max-width:100%;height:auto;}" to fix this issue.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Daijobou** [comment]
Please stop closing valid tickets! Nothing is fixed here.

**Comment by dsakko** [comment]
Hi Daijobou, I'll reopen this, however please be aware that Tiny is not currently optimised for mobile devices.
