### ISSUE TITLE
Creating checkbox's like OneNote

### ISSUE THREAD

**Issue by SoaresMG** [tinymce/tinymce#2570]
Is there any plugin to produce a checkbox list while pressing enter, just like OneNote? if not, it would be a great plugin

**Comment by spocke** [comment]
We don't have such a plugin.

**Comment by mindware** [comment]
+1 This would be an awesome plugin.

**Comment by tinydylan** [comment]
TinyMCE now has a [checklist plugin](https://apps.tiny.cloud/products/checklist/). It sounds like it does what you've described.
