### ISSUE TITLE
Extreme sluggishness in IE and sometimes Chrome due to setTimeout with 0

### ISSUE THREAD

**Issue by Luke-SF** [tinymce/tinymce#2572]
There are numerous cases where MCE causes a huge lag, or worse yet constantly running this code:

```
 window.setInterval(function() {
                var e = window.innerWidth
                  , n = window.innerHeight;
                (t.w != e || t.h != n) && (t = {
                    w: e,
                    h: n
                },
                r(window).trigger("resize"))
            }, 0),
            r(window).on("resize", e)
```
it's a big problem in MCE4 - http://stackoverflow.com/questions/34034040/why-does-tinymce-has-settimeout-with-0-slowing-down-the-browser

How is this loop supposed to stop?

**Comment by spocke** [comment]
Make sure you have the latest version since 4.3.2 fixed this a.f.a.i.k.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
