### ISSUE TITLE
Email addresses with periods in bulleted text truncated upon copy/paste

### ISSUE THREAD

**Issue by JiveJeremy** [tinymce/tinymce#2573]
* Originally posted on Wordpress bug tracker - https://core.trac.wordpress.org/ticket/35159 *

A colleague of mine had recently tried to copy/paste a large Word document into a post using the Visual editor but noticed that many of the email addresses were truncating. 

With some testing, I have been able to replicate this with email addresses that are in a list (ul in this case) and with one or more periods in the first half of the email address (i.e. firstname.lastname@). The truncation only appears in the display text, not the underlying html and is cut at the first period, leaving just the lastname@ portion (see screenshots for example).

To test, type a test paragraph or just an email with a period in the mailbox, then a second email with a period in the mailbox name but this time in a bulleted list into a Word document. Copy/paste this into a new post to see the bug.

![blog-screenshot](https://cloud.githubusercontent.com/assets/4359376/11915205/dfe5fb6a-a650-11e5-841d-f7b937404ab8.jpg)

Unfortunately, I am not an admin on this particular site and so cannot tell you at this time what plugins we have installed but I have asked the admin to get me a list (as well as have his blessing for posting this year, no toes getting stepped on). I will post the plugins as soon as I hear back but I do not believe that we have many installed beyond the defaults. I have asked that the admin update the system and I can test again with the newer version. I will continue to update this note as I find more information.

**Comment by JiveJeremy** [comment]
Can't seem to get the screenshot to work but following the steps above should replicate for you.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
