### ISSUE TITLE
Grammarly Plugin issues with TinyMce

### ISSUE THREAD

**Issue by dustinboulton** [tinymce/tinymce#2577]
Our content publishing company is expieirencing duplicated content when using Grammarly combined with TinyMce.

The issue occurs for me only
* when Grammarly is active 
* Text is modified within an existing paragraph.
* Enter/return are pressed before grammarly can finish spelling checking on the document change.

Is there something we can do with javascript to prevent this from happening?

**Comment by spocke** [comment]
Since Grammarly is a extension in the browser I doubt there is much we can do here. Except that you report the issue to them instead.

**Comment by spocke** [comment]
Closing. Since 3rd party needs to be involved.
