### ISSUE TITLE
Not recognize <a> tag, if inside this tag has another tag like <a><h3>title</h3></a>

### ISSUE THREAD

**Issue by DuongMich** [tinymce/tinymce#2578]
- Not recognize <a> tag, if inside this tag has another one like <a><h3>title</h3></a>
- You can copy the contents from here http://m.dantri.com.vn/xa-hoi/cu-rua-ho-guom-phoi-nang-hon-2-tieng-trong-ngay-dong-2015122209512646.htm to insert into demo tinymce editor
- The problem appear from 3.4 till now, but 3.3.9.4 is ok

**Comment by DuongMich** [comment]
[a][h3] title [/h3][/a] -> "[a]" will be removed

**Comment by Shakil-Shahadat** [comment]
This is not a bug. You have written a block level element inside an inline element. Do it otherwise and you are good to go.

**Comment by drumsibumsi** [comment]
HTML5 allows block elements inside of [a] tag - as far as I remember.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
