### ISSUE TITLE
Embed video not working/playing in preview

### ISSUE THREAD

**Issue by Ishanjn** [tinymce/tinymce#2579]
When adding a youtube video (via link or embed code) are playing correctly in editor (this is new feature in tinymce 4.3). But when i trying to preview and play video, its not working.

See below screenshot -

![tinymce the most advanced wysiwyg html editor](https://cloud.githubusercontent.com/assets/16400078/11953878/c58c108a-a8c9-11e5-9fc5-e75e2244c3ac.png)

**Comment by Ishanjn** [comment]
Is there any good news regarding to "video issue" when preview?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
