### ISSUE TITLE
How to make Tinymce readonly at runtime?

### ISSUE THREAD

**Issue by Suraj1189** [tinymce/tinymce#2580]
I want to make tinymce rich textbox readonly i.e. text editor and toolbars to be disabled at runtime. I want to know how it can be achieved? I found out the way by setting its prop. readonly to true during "Init" method. But i don't want to call "Init" method again to make it readonly. Is there any way to do it by another way? Please help me out to figure it out.

Thanks,
Suraj

**Comment by spocke** [comment]
tinymce.activeEditor.setMode('readonly'); and tinymce.activeEditor.setMode('design'); I'm closing this one since this is a question.

**Comment by Suraj1189** [comment]
tinymce.activeEditor.setMode('readonly'); My code gives an error 0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'setMode'. 

Thanks,
Suraj

**Comment by spocke** [comment]
Only works on tinymce 4.3.x.

**Comment by Suraj1189** [comment]
Thank you very much SPOCKE for clarify my questions.

Still I have one query as i want to toggle the specific richtextbox editor state, depending on the ID of textarea. tinymce.activeEditor.setMode('readonly'); and tinymce.activeEditor.setMode('design'); 
toggle the state of active editor only. 
In my scenario,i want it to be done on the configuration which i will get from the server and even the editor not being active. Is there any way to do it?

Thanks,
Suraj

**Comment by 1sunny** [comment]
tfdfgsdafsd

**Comment by 1sunny** [comment]
dfsfsaf
