### ISSUE TITLE
Table cells have a leading space when entering data (IE Only)

### ISSUE THREAD

**Issue by AdamJorgenson** [tinymce/tinymce#2583]
Table cells have a leading space when entering data (IE Only)

1 - Insert a table and begin entering data in a cell

Expected Result: Data is entered as typed

Actual Result: IE has a leading space in the table cell. The workaround is to backspace before entering any data.

**Comment by Afraithe** [comment]
This seems to be a duplicate of #2518

**Comment by jhaines** [comment]
Fixed as per #2518 Thanks for the report.
