### ISSUE TITLE
Unable to submit the form because of html5 required attribute

### ISSUE THREAD

**Issue by heaven** [tinymce/tinymce#2584]
I believe tinymce should handle this case.

Solutions like this:

```
// fix tinymce bug
        if($this.is('[required]')){
            options.oninit = function(editor){
                $this.closest('form').bind('submit, invalid', function(){
                    editor.save();
                });
            }
        }
```

should be integrated into tinymce.

**Comment by nicolabeghin** [comment]
any news on this?

**Comment by nicolabeghin** [comment]
Workaround for TinyMCE 4 and HTML5 `required` validation, failing on Chrome with

> An invalid form control with name='data[Communication][body]' is not focusable.

Just use this code when initializing TinyMCE

    tinymce.init({ 
    	selector:'textarea:not(.mceNoEditor)',
    	setup: function(ed) {
    		ed.on('change', function(e) { ed.save(); });
    	}
    });

**Comment by nicolabeghin** [comment]
update: not working, made wrong tests. but it should be a starting point

**Comment by rcluan** [comment]
Hello, mates. In case you haven't found a workaround on this issue yet, here it goes my suggestion.

@nicolabeghin tried `ed.save()` on the **submit** event and, according to himself it didn't work. Well, I've followed this idea but used the **init** event instead of **submit** and worked like a charm.

Currently I'm using Angular 1.5 and, therefore, angular-ui-tinymce. My forms are built using formly and the code is something like this:

```
{
key: 'content',
type: 'composer_tinymce',
templateOptions: {
    label: 'Content',
    placeholder: 'Content',
    showPreview: true,
    required: true,
    tinymceOptions : {
      height: "400px",
      resize: false,
      setup: function(editor){
        editor.on('init', function(){
          editor.save();
        });
      }
    }
  }
}
```

Notice the setup attribute in my tinymceOptions. I guess for non-angular users it would be as @nicolabeghin suggested but using 'init' instead of 'submit'.

Hope it works. Cheers.

**Comment by Theolodewijk** [comment]
Still nog fix !!!

**Comment by scottux** [comment]
I changed `init` to `change`, and it seems to be fine for me. Not sure of the repercussions yet.

**Comment by lorrandavid** [comment]
@scottux it works fine at first but after validations (using CakePHP or Laravel for example) it doesn't work anymore because the field has been set up already.

**Comment by lorrandavid** [comment]
I got it working using CSS, I know it's not the very semantic and beautiful but for me it was the best way to deal with the problem. In my case I just set my CSS like this:

```
.tiny-group{
  position:relative;
}

.tiny-group #tinyTextarea {
  position:absolute;
  bottom:0;
  left:50%;
  transform:translateX(-50%);
  display:block !important;
  width:1px;
  height:1px;
  opacity:0;
}
```

**Comment by mightym** [comment]
Same issue here. Chrome/Safari, when having a textarea which is required I get the error: ```An invalid form control with name='textarea-name' is not focusable.```. If I removed the `required`html5 attribute everything works fine

**Comment by matthewcornell** [comment]
Tinymce newbie here. Until I found this thread I was using `<button type="submit" formnovalidate class="save btn btn-success">Submit</button>`, which turned off browser validation, leaving validation to my back end via an actual POST. Not great. However, now I have a form that would be hard to refill, so I'd like a fix. I tried @scottux 's solution, and while it does correctly detect whether my `<textarea>` has content, the "Please fill out this field" browser popup is located in the extreme upper left. Please: Has anyone found a fix for this positioning? Thank you.

**Comment by harunthuo** [comment]
@mightym solution did it for me. removing the **required** attribute from the **textarea** solves the issue

**Comment by csgenius786** [comment]
take submission of your form through this function

`<script type="text/javascript">

    //
    function submitform(that)
    {
        // remove all errors first
        $(".error_not_filled").remove();

        var can_submit = 1;

        // define error div contents
        var error_div = "<div class='error_not_filled' style='background: red;color: #fff;padding: 5px;margin-bottom: 5px;'>Please fill out this field</div>";

        // select all required fields BUT only within current form
        var x = $(that).closest('form').find("*[data-required]");

        //loop through
        $(x).each(function(i,v)
        {
            var tthis = $(this);
            var vv_ = $(tthis).val();

            if(vv_=="")
            {
                can_submit = 0;
                $(tthis).prev().before(error_div);
                if(i==0)
                    $(tthis).next().focus();
            }
        });
       
        if(can_submit==1)
        {
            $(that).closest('form').submit();
        }
        else
        {
            return;
        }
    }
</script>`

**Comment by Tomicapo** [comment]
Really??? TinyMCE doesnt support HTML5 required attribute? And we need to write such a function to do that? I'm impressed... 
Any chance this could be implemented?

**Comment by natatkinson** [comment]
Any word on if this will be fixed?

**Comment by triion** [comment]
Having the same problem... Any effective solutions yet?

**Comment by csgenius786** [comment]
//
function submitform(that)
{
    // remove all errors first
    $(".error_not_filled").remove();

    var can_submit = 1;

    // define error div contents
    var error_div = "<div class='error_not_filled' style='background:
red;color: #fff;padding: 5px;margin-bottom: 5px;'>Please fill out this
field</div>";

    // select all required fields BUT only within current form
    var x = $(that).closest('form').find("*[data-required]");

    //loop through
    $(x).each(function(i,v)
    {
        var tthis = $(this);
        var vv_ = $(tthis).val();

        if(vv_=="")
        {
            can_submit = 0;
            $(tthis).prev().before(error_div);
            if(i==0)
                $(tthis).next().focus();
        }
    });

    if(can_submit==1)
    {
        $(that).closest('form').submit();
    }
    else
    {
        return;
    }
}

**Comment by kironet** [comment]
Instead of adding more and more paid features,
CAN YOU ALREADY FIX THIS?

**Comment by CodingAnarchy** [comment]
I'm surprised this has been out here for three years without being addressed.  It's a rather important bit of functionality that should be supported, IMO.

**Comment by ivanmart** [comment]
Same here, fresh update 1.1.3 => 1.1.10, publish assets with -force flag, still have `An invalid form control with name='body' is not focusable.`

**Comment by ivanmart** [comment]
As workaround is to set thefield to NULLable and set `required` to `0` in `data_rows` table.

**Comment by tripflex** [comment]
But really though ... workarounds?  It's 2019 this should be something standard :(

**Comment by tripflex** [comment]
If anybody is looking for a way to handle this in the WordPress implementation of TinyMCE, here's what I came up with:

```javascript
	tinymce.on( 'AddEditor', function ( e ) {
		console.log( 'Added editor with id: ' + e.editor.id, e.editor );

		var $editor = tinymce.get( e.editor.id );

		$editor.on( "change", function (e){
			$editor.save();
		});

	});
```

**Comment by jobsonkakule** [comment]
> I changed `init` to `change`, and it seems to be fine for me. Not sure of the repercussions yet.
> 
> ```js
> tinymce.init({ 
>     selector: 'textarea',
>     setup: function (editor) {
>         editor.on('change', function (e) {
>             editor.save();
>         });
>     }
> });
> ```

Thx, this helped me !

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .

**Comment by jainam2385** [comment]
> I changed `init` to `change`, and it seems to be fine for me. Not sure of the repercussions yet.
> 
> ```js
> tinymce.init({ 
>     selector: 'textarea',
>     setup: function (editor) {
>         editor.on('change', function (e) {
>             editor.save();
>         });
>     }
> });
> ```

This worked for me thanks!
