### ISSUE TITLE
insert text in bold word

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2585]
When i copy something content and insert him in bold word, my content  inserted bold

before insert: <strong>word</strong>
now(after insert) :   <strong>woMYCONTENTrd</strong>
expected(after insert): <strong>wo</strong>MYCONTENT<strong>rd</strong>

for example CKEditor and MSWord working like expected

it repeated for bold italic underline etc

**Comment by alecpl** [comment]
That's not what I would expect. That's also not what LibreOffice would do. I mean current behaviour is fine and expected for some people.

**Comment by spocke** [comment]
The nasty part of that is it basically needs to split nodes downward and produce more HTML tags.
So a paste of "x" in here: <b><i>abc|123</i></b> would have to become <b><i>abc</i></b>x|<b><i>123</i></b>.
