### ISSUE TITLE
Browser "Stop Script" Error

### ISSUE THREAD

**Issue by MichaelSamteladze** [tinymce/tinymce#2587]
I think I've found an issue with tinymce, browser completely stucked. Please see Example

I was trying to download an Event description from facebook and modify it with tinymce and ended up with a bug.

http://fiddle.tinymce.com/Fmfaab/1

Question marks is my unicode text from facebook

**Comment by alecpl** [comment]
Confirmed with recent Firefox version and tinyMCE edge. The error points to this line
`
while ((matches = tokenRegExp.exec(html))) {
`

**Comment by fyrkant** [comment]
I think that this bug in the parser has been fixed so I'm closing this issue.
