### ISSUE TITLE
getContent === "" after execCommand('InsertUnorderedList/InsertOrderedList')

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2588]
i call execCommand('InsertUnorderedList/InsertOrderedList')  
after i call getContent and returned content === " "

and getContent({format: 'text'}) == '\n'

expected: getContent() == '`<ol><li><br data-mce-bogus="1"></li></ol>`'

**Comment by spocke** [comment]
If a list element is treated as empty it's removed by the serialization layer. If you want the raw html use the format: 'raw' parameter or getBody().innerHTML however this is normally not recommended.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
