### ISSUE TITLE
Tinymce website SSL certificate handshake failure

### ISSUE THREAD

**Issue by damienbeaufils** [tinymce/tinymce#2589]
Hello,

There is an issue with the SSL certificate which is installed on tinymce.com website (handshake failure):
```
$ openssl s_client -connect www.tinymce.com:443 -showcerts
CONNECTED(00000003)
140470466995864:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
```

Because of this error, it is impossible for to create new WebJars for TinyMCE (see https://github.com/webjars/webjars/issues/1265#issuecomment-165199217).

**Comment by spocke** [comment]
We will fix that in the bowser package not the site.

**Comment by damienbeaufils** [comment]
It seems to be fixed. The TinyMCE 4.3.3 is available on WebJars: http://www.webjars.org/listfiles/org.webjars.bower/tinymce/4.3.3
