### ISSUE TITLE
It is determined by the first byte of the input at multi-byte character input

### ISSUE THREAD

**Issue by morizox** [tinymce/tinymce#2590]
In character input to the cell in the table tag, a phenomenon which is not expected occurs in IE11 & WP4.4 & TinyMCE Advanced 4.2.8.
it has happened in the example on https://www.tinymce.com.
Is the problem in TinyMCE or in WordPress?

For more information please refer to the following

https://wordpress.org/support/topic/it-is-determined-by-the-first-byte-of-the-input-at-multi-byte-character-input?replies=6#post-7824652

**Comment by spocke** [comment]
I think this was fixed in this commit:
https://github.com/tinymce/tinymce/commit/18fbfcac2f6ab2b9e4abffc2093cee881217ab0b

We haven't released that fix yet though.

**Comment by morizox** [comment]
will fix, soon.
https://github.com/tinymce/tinymce/issues/2710

Thanks.
