### ISSUE TITLE
ctr+shift+right not select last word in ff (inline mode)

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2592]
inline: true
for example:  http://codepen.io/tinymce/pen/YydQoj

firefox
type a few words
set cursot in begin
press ctrl+shift+right

not selected last word

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
