### ISSUE TITLE
insert link, remove space before text

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2595]
In 4.3.1 und 4.3.2 I see often (not always) that when I set a link, the space before is removed. That Problem coming with 4.3.x before I never see that. Example: "this is a text". After set a link on "text" the line is "this is atext". Missing space between "a" and "text".

**Comment by spocke** [comment]
Fixed this seems to be a webkit specific bug.

**Comment by Daijobou** [comment]
Thank you very much. :)

**Comment by 0xbadc0de** [comment]
In which commit this was fixed?

**Comment by teeej** [comment]
@spocke It looks like this issue still persists on mobile Safari. Currently using v5+. Any workaround I should know about?

**Comment by rohitvishwakarma-sf** [comment]
@spocke issue still persist on Wkwebview mac-catalyst

**Comment by rohitvishwakarma-sf** [comment]
> @spocke It looks like this issue still persists on mobile Safari. Currently using v5+. Any workaround I should know about?

@teeej  were you able to resolve it ?
