### ISSUE TITLE
How to toggle state of  TinyMCE RichText editor?

### ISSUE THREAD

**Issue by Suraj1189** [tinymce/tinymce#2596]
I have one query as i want to toggle the specific richtextbox editor state, depending on the ID of textarea. tinymce.activeEditor.setMode('readonly'); and tinymce.activeEditor.setMode('design'); 
toggle the state of active editor only. 
In my scenario,i want it to be done on the configuration which i will get from the server and even the editor not being active. Is there any way to do it?

Thanks,
Suraj

**Comment by spocke** [comment]
Closing since this is a question. But anyway there is a readonly: true option.
