### ISSUE TITLE
Some youtube links not working (special character in link)

### ISSUE THREAD

**Issue by Ishanjn** [tinymce/tinymce#2597]
For Some youtube videos live preview feature is not working into editor. 

For example- "https://www.youtube.com/watch?v=lvtfD_rJ2hE" it's now working(because of "_" character);
But "https://www.youtube.com/embed/u2l6nk7pMQ0" is working correctly

As far as i understand it's special character issue. because when i open popup for edit video link, the link is not showing truncated with special character (means in edit link popup only showing "//www.youtube.com/embed/lvtfD" you can see "_rJ2hE" is missing)

**Comment by cirkuitnet** [comment]
This goes hand-in-hand with a bug I just reported. I suggested a patch as well too if you want to hot-fix your package until an official patch is in place. I don't mention the underscore in my report, but saw it was missing and included it in the patch:
https://github.com/tinymce/tinymce/issues/2594

**Comment by VizuaaLOG** [comment]
@cirkuitnet Thanks, that patch works great!

**Comment by Ishanjn** [comment]
@cirkuitnet Thanks, works great!
