### ISSUE TITLE
nofollow links in tinymce

### ISSUE THREAD

**Issue by vahidalvandi** [tinymce/tinymce#2598]
i seo external links should nofollow 

DO IN TINYMCE SUPPORT THIS?

**Comment by vahidalvandi** [comment]
i solved this


plugins: [
			'link'
],


rel_list: [
			{title: 'follow', value: 'follow'},
			{title: 'nofollow', value: 'nofollow'}
			]

**Comment by akayjangra** [comment]
i make blog using python Django that is [kho kho ground ](https://www.wishcard.ooo/kho-kho-ground-or-court-measurement) . how can i add external link no follow so i can do good seo for my website.
