### ISSUE TITLE
tinymce 4.3.2 jquery integration

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#2599]
Hi,

I am upgrading tinymce from 3.5.6 to 4.3.2 now. I could not able to found a jquery integration for that. Can you please share the sample code for consume jquery.

I used the below code.

<script src="Scripts/jquery-1.10.2.min.js"></script>

<script src="Scripts/tinymce_4.3.2/tinymce.jquery.js"></script>

<script src="Scripts/tinymce_4.3.2/tinymce.js"></script>

<script type="text/javascript">
    $(function () {
        $('textarea.tinymce').tinymce({
            // Location of TinyMCE script
            script_url: 'Scripts/tinymce_4.3.2/tinymce.js',

            // General options
            theme: "advanced",
            plugins: "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

            // Example content CSS (should be your site CSS)
            content_css: "css/content.css",

            // Drop lists for link/image/media/template dialogs
            template_external_list_url: "lists/template_list.js",
            external_link_list_url: "lists/link_list.js",
            external_image_list_url: "lists/image_list.js",
            media_external_list_url: "lists/media_list.js",

            // Replace values for the template plugin
            template_replace_values: {
                username: "Some User",
                staffid: "991234"
            }
        });
    });
</script>

<form method="post" action="somepage">
    <textarea id="content" name="content" class="tinymce" style="width:100%"></textarea>

    
    <a href="javascript:;" onmousedown="$('#content').tinymce().show();">[Show]</a>
    <a href="javascript:;" onmousedown="$('#content').tinymce().hide();">[Hide]</a>
    <a href="javascript:;" onmousedown="$('#content').tinymce().execCommand('Bold');">[Bold]</a>
    <a href="javascript:;" onmousedown="alert($('#content').html());">[Get contents]</a>
    <a href="javascript:;" onmousedown="alert($('#content').tinymce().selection.getContent());">[Get selected HTML]</a>
    <a href="javascript:;" onmousedown="alert($('#content').tinymce().selection.getContent({format : 'text'}));">[Get selected text]</a>
    <a href="javascript:;" onmousedown="alert($('#content').tinymce().selection.getNode().nodeName);">[Get selected element]</a>
    <a href="javascript:;" onmousedown="$('#content').tinymce().execCommand('mceInsertContent',false,'<b>Hello world!!</b>');">[Insert HTML]</a>
    <a href="javascript:;" onmousedown="$('#content').tinymce().execCommand('mceReplaceContent',false,'<b>{$selection}</b>');">[Replace selection]</a>
</form>

**Comment by cirkuitnet** [comment]
I had the same issue - I found the jQuery plugin files within TinyMCE's "Development Package" though, so I just copied them from there. They work fine. I figured the files were accidentally left out of the "Community" edition:
https://www.tinymce.com/download/

**Comment by fyrkant** [comment]
Like said above, the jquery integration is in the development download.
