### ISSUE TITLE
Spellcheck: AddToDictionary should use the 'lang' parameter

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#2601]
data.lang should also be set for AddToDictionary requests.

https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/spellchecker/classes/Plugin.js#L170

For implementations that distinguish stored words per language. I.e. the word used in French don't have to be valid for English.

**Comment by alecpl** [comment]
PR #2603

**Comment by fyrkant** [comment]
The PR seems to be closed so I guess this is fixed.
