### ISSUE TITLE
Script Error When Mousing Over Table Cell Borders

### ISSUE THREAD

**Issue by jtark** [tinymce/tinymce#2604]
I've encountered a bug where mousing over the borders of table cells under certain conditions raises the following script error:
```
Line: 2826
Char: 7
Error: Unable to get property 'rowIndex' of undefined or null reference
Code: 0
URL: <snip>/tinymce/js/tinymce/plugins/table/plugin.js
```

I've found two ways to reliably reproduce the issue.

The first method is to create a table with more than one `<tr>` element and put another table inside of one of the `<tr>` elements. When mousing over the border of any cell in the outer table, the script error is raised. When mousing over a border in the inner table, no error occurs. It does not appear to occur at all if the outer table has only one `<tr>` element.

The second method is to create a table with multiple `<tr>` elements that do not all have the same total column span. In this case, mousing over any border in the table will raise the error. Nested tables are not required to reproduce it in this manner. It also does not appear to matter whether the `<tr>` elements have an equal number of `<td>` elements as long as at least one `<tr>` element has a different total column span.

I encountered this issue while using version 4.3.2 of TinyMCE.

I've attached a .TXT file containing HTML that demonstrates the issue.

[table border test.htm.txt](https://github.com/tinymce/tinymce/files/78887/table.border.test.htm.txt)

**Comment by spocke** [comment]
Fixed in: https://github.com/tinymce/tinymce/commit/d47986ac62be500e102878ee898b93ab42f65ade

**Comment by jtark** [comment]
I see what happened with the nested table - the column span in the top row of the outer table was defined incorrectly. Nothing to do with the fact that there's a nested table, only with the total column span in each row.
