### ISSUE TITLE
'auto_focus' not working

### ISSUE THREAD

**Issue by Shakil-Shahadat** [tinymce/tinymce#2606]
Here is a sample http://codepen.io/shakil/pen/QypMqK

It shows a warning `Uncaught TypeError: Cannot read property 'destroyed' of null` in the console.

Thanks.

**Comment by alecpl** [comment]
I confirm the bug, but according to the documentation you should not use # in the editor id.

**Comment by Shakil-Shahadat** [comment]
Hi, I removed # and now it is working. Thanks for pointing me that. Its not a bug then.

**Comment by venu222** [comment]
i am using ui-tinymce, i am still getting the same issue even though i removed '#' from the element

**Comment by Shakil-Shahadat** [comment]
Share your code.

**Comment by venu222** [comment]
Hey thanks for the responce.. i figured it out. i got the solution

**Comment by CarlosAguA** [comment]
@venu222 what was your solution?

**Comment by Shobhit-K** [comment]
> Hey thanks for the responce.. i figured it out. i got the solution

@venu222 What was the solution that you got?
