### ISSUE TITLE
Line break after <br> tag changed to a space

### ISSUE THREAD

**Issue by arlomedia** [tinymce/tinymce#2607]
Steps to reproduce:
1. From the TinyMCE demo on the tinymce.com home page, click Tools &gt; Source Code.
2. Paste this HTML:
&lt;p&gt;line 1&lt;br /&gt;
line2&lt;/p&gt;
3. Click OK.
4. Open Tools &gt; Source Code again.

Expected result:
The HTML appears as I entered it, or is changed to:
&lt;p&gt;line 1&lt;br /&gt;line2&lt;/p&gt;

Actual result:
A space has been added after the &lt;br /&gt; tag:
&lt;p&gt;line 1&lt;br /&gt; line2&lt;/p&gt;

The same thing happens when activating TinyMCE on a field that contains this HTML -- it's not just an issue with the source code editing window.

I think it's okay to remove the line break, because that only affects the source code display. But it's not okay to change it to a space, because that affects the content. I added some pre-processing to strip line break characters from the HTML before loading it into TinyMCE, to avoid the problem. But I think TinyMCE should be changed so it doesn't add these spaces.

**Comment by arlomedia** [comment]
Here's another way to reproduce the problem. Select and copy a paragraph of text in MS Word or another program that distinguishes between paragraphs and line breaks. For example, text like this in Word:

Line 1[break]
Line 2[break]
Line 3[paragraph]

Now paste this into the demo editor on the TinyMCE home page, then look at the source. It will show this:

&lt;p&gt;Line 1&lt;br /&gt; Line 2&lt;br /&gt; Line 3&lt;/p&gt;

But I think it should show this:

&lt;p&gt;Line 1&lt;br /&gt;Line 2&lt;br /&gt;Line 3&lt;/p&gt;

In this situation, my pre-processing workaround doesn't help. And I can't simply remove any space at the start of a line when saving, because I don't know if the user intended for a space to be there or not.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Georg-Git** [comment]
TinyMCE **v4.6.1**: Space after br tag is back.

Steps to reproduce:

TinyMCE Full featured demo, click Tools > Source Code.
Enter:
```
<p>line 1<br />
line2</p>
```
Click OK, Open Tools > Source Code again.
Expected result:
`<p>line 1<br />line2</p>`

Actual result:
`<p>line 1<br /> line2</p>`

=> A space has been added after the `<br />` tag.

By the way:
Why is the linebreak in the html source code stripped away??
With Linebreaks in front of every `<br />` tag the html source code in the source code editor is much more easier to read!

**Comment by arlomedia** [comment]
I can still reproduce it in the demo on your home page, which I assume is the current version 4.7.4. I just followed the steps in my original post and the problem still happens. The problem happens consistently in Safari, Chrome and Firefox on my Mac.

I'll attach some screen shots showing how I reproduced it. In the final screen shot, there's a space between the line break tag and the "line 2" text. This space doesn't render in TinyMCE's WYSIWYG editor, but it causes problems when the generated HTML is used in other systems.


![screen shot 2017-12-06 at 9 30 33 am](https://user-images.githubusercontent.com/1878401/33675765-8e203266-da68-11e7-97bb-683a50ffad5a.png)
![screen shot 2017-12-06 at 9 30 44 am](https://user-images.githubusercontent.com/1878401/33675766-8e38cf24-da68-11e7-8a73-bcf79f3e0a17.png)
![screen shot 2017-12-06 at 9 30 49 am](https://user-images.githubusercontent.com/1878401/33675767-8e4f896c-da68-11e7-8b1c-743fbd10ff86.png)
![screen shot 2017-12-06 at 9 30 54 am](https://user-images.githubusercontent.com/1878401/33675768-8e66304a-da68-11e7-9ed7-646ef320de8a.png)
![screen shot 2017-12-06 at 9 30 59 am](https://user-images.githubusercontent.com/1878401/33675769-8e8007c2-da68-11e7-81e6-82c1238f645e.png)
![screen shot 2017-12-06 at 9 31 05 am](https://user-images.githubusercontent.com/1878401/33675770-8e97d730-da68-11e7-9f7f-18ba5d6a1d71.png)
![screen shot 2017-12-06 at 9 31 11 am](https://user-images.githubusercontent.com/1878401/33675771-8eb2309e-da68-11e7-8736-11b55f3ae7be.png)

**Comment by kemosite** [comment]
I'm also seeing this behaviour in 4.7.4

**Comment by blackcathikari** [comment]
Thanks for the comment @kemosite and for the screenshots @arlomedia. I've referred this to the dev team. :)

**Comment by spocke** [comment]
We can look into this however not sure why this is even a problem a space after a br is not rendered by the browser anyway.

**Comment by wbswbs** [comment]
Not in the browser, but when you work with the text and pass it to other engines, it can be disturbing.

**Comment by kemosite** [comment]
This bug makes the source code output clumsy and awkward. Some people, myself included, want line breaks as appropriate. When I expect to see line breaks in my source code and they are instead converted to spaces, the source code is incorrect.

**Comment by arlomedia** [comment]
In my case, I have a mobile app that integrates with a website, and the mobile app's text fields render the spaces. Adding these extra spaces indents every line except the first line by one space, which looks sloppy and is annoying for the user to clean up. I can't trim spaces from lines in my code because it is a lyrics editing app and users often use spaces to indent the choruses.

I don't care if TinyMCE removes line breaks from source code, but if it does, it shouldn't replace them with spaces. I can't imagine any benefit to doing that. And when the extra spaces are added inside text blocks like paragraph tags, that has the potential to interfere with the user's content.

**Comment by tovic** [comment]
Try adding CSS:

~~~ .css
textarea {
  white-space: pre-wrap !important;
}
~~~

**Comment by fyrkant** [comment]
This was fixed a few releases ago.

**Comment by arlomedia** [comment]
Excellent. I just confirmed the problem no longer occurs using the demo on your home page. Thanks!

**Comment by augustography** [comment]
This problem is now occurring again in the current version, including the demo on the homepage.

This is important when working with very large/complex code. Of course P and BR tags render in the browser, but other white space like line breaks / tabs which aren't rendered by the browser make managing and editing various sections of code much easier.

Is there a configurable option for this? in v3 there used to be remove_linebreaks, but this isn't available in v4?

**Comment by arlomedia** [comment]
@augustography I just checked this on the home page and I don't see the problem. You might have misunderstood what issue I described here -- it's not removing the line breaks within the source code, it's adding spaces after the <br> tags. That was a problem for me because those spaces did render in browsers, but that was fixed and hopefully it will remain fixed.
