### ISSUE TITLE
Is here a way to download the "nightly" build?

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2608]
I have often download a fresh updated version here http://community.tinymce.com/develop/nightly.php

Is this feature still available? ;)

**Comment by spocke** [comment]
We will look into this one.

**Comment by Daijobou** [comment]
Found here https://www.tinymce.com/download/additional-downloads/ as last entry. Its missing in sidebar menu.

**Comment by Daijobou** [comment]
I close this ticket, but the entry is still missing. After one year I dont't think this will be fixed.
