### ISSUE TITLE
Crash with Windows 10 Mobile Edge when hitting "Enter"-key

### ISSUE THREAD

**Issue by kkarimak** [tinymce/tinymce#2610]
When hitting "Enter"-key (when there is nothing below) in tinymce editor with Windows 10 Mobile Edge -> it creates some sort of "loop" of key pressings and occurs website to crash. So try to hit "Enter"-key as the first thing to press or just write something and hit "Enter" -> it creates loop and crash.

If there are some letters (even one) after when one presses "Enter" it works correctly. 

This happens with every TinyMCE I have tried with Windows 10 Mobile Edge (this does not happen with Windows 10 touch devices like Surface nor with Windows Phone 8.1, I think not either with Windows 10 Mobile "Surfy Browser" or any other devices, like iOS or Android).

I have catched at tinymce.init( setup the "keypress" event that seems to be at least some sort of problem -> haven't been able to create any elegant solution to fix it without making it compromise for all other devices / platforms.

Problem with TinyMCE or Windows 10 Mobile Edge? Any ideas?

**Comment by kkarimak** [comment]
Seems that this same behavior occurs also with CKEditor and Summernote etc. so most probably this not an issue with TinyMCE, or if it is -> then it is an issue of all of these type of editors.

**Comment by spocke** [comment]
I was able to install Windows 10 on a Lumia device however it doesn't seem to crash when I press enter but the selection seems broken so that is another issue.

**Comment by fyrkant** [comment]
Closing this issue as windows 10 phones are pretty much extinct by now.
