### ISSUE TITLE
Right-clicking an image should select the image first

### ISSUE THREAD

**Issue by brianmfranklin** [tinymce/tinymce#2611]
If not, then this can cause problems when trying to Insert/Edit Link.  If you are on an existing linked element (either text or image), and you right-click some separate image, then click Insert/Edit Link, you'll actually be editing the link on the existing linked element, NOT editing the link on the image you right-clicked.

To reproduce in the live demo:
1) Select the word "Welcome".
2) Right-click and choose Insert/edit link.
3) Put in "example.com" as the URL.
4) Click OK.
5) Place the cursor/insertion point somewhere inside the word Welcome, such that the Link button on the toolbar has an active state.
6) Right-click on the TinyMCE logo image and choose Insert/edit link.
7) This SHOULD be creating a new link on the logo image, but instead is editing the link on the word Welcome.

This behavior does not happen when right-clicking onto text.  The insertion is first moved to the right-clicked text, so that the original link does not get modified.

**Comment by tinydylan** [comment]
Thank you for you bug report.

I believe this issue has been corrected. I am unable to reproduce the issue in the current TinyMCE 5.2.1. Right-clicking the image selects the image and the dialog lets me add a new link on the image.

Please let us know if you still encounter the issue.
