### ISSUE TITLE
Some Google Maps Urls are being partially converted to email address, breaking the url

### ISSUE THREAD

**Issue by andergmartins** [tinymce/tinymce#2612]
Paste this url on the editor:

`https://www.google.com/maps/place/Mt.+Rainier,+Washington+98304/@46.8523056,-121.7778325,14z/data=!3m1!4b1!4m2!3m1!1s0x5490d193f70860fb:0x5b5e4fe17ad6b707`

This fragment: `+Rainier,+Washington+98304/@46.8523056` is treated as an email address and converted to `mailto:+Rainier,+Washington+98304/@46.8523056`, becoming later a link and breaking the url.

The same will happens with this urls:

`https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.847938957973!2d-52.03876968428612!3d-23.537970984694578!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjPCsDMyJzE2LjciUyA1MsKwMDInMTEuNyJX!5e0!3m2!1sen!2sbr!4v1452111249095root@84bd9e8a25b7`

Treating `4v1452111249095root@84bd9e8a25b7` as email address.

The regex on the following file/line:
https://github.com/tinymce/tinymce/blob/e689d2c7f0b10bdb7e60405c5d484068af2ecb57/js/tinymce/plugins/autolink/plugin.js#L192
needs to be modified by something like: `[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}` (from http://www.regular-expressions.info/email.html)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
