### ISSUE TITLE
Incorrect encoding of URLs

### ISSUE THREAD

**Issue by aparod** [tinymce/tinymce#2614]
Certain characters in URLs are getting incorrectly converted to HTML entities when retrieved from the `getContent()` method, when they should be percent-encoded instead.

I encountered the problem by entering a URL via the image plugin, then calling `tinymce.activeEditor.getContent()`. The `src` attribute for the `img` tag is not encoded properly.

For example:

```
file name: image&>.jpg
expected:  image&%3e.jpg      // & is a valid char in a URL, but could also be encoded as %26
actual:    image&amp;&gt;.jpg // both chars incorrectly converted to HTML entities
```

**Comment by spocke** [comment]
Not sure this is a bug the HTML spec allows you to entity encode values this way.

**Comment by aparod** [comment]
I haven't tested other browsers, but Chrome, at least, does support entity-encoded URLs. Regardless, it doesn't conform to [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.1) which specifies URLs should be percent-encoded.  So, maybe this request is less of a "bug" and more of an "improvement".

**Comment by aparod** [comment]
After thinking about this further, I believe it comes down to whether TinyMCE expects the URL entered in the "source" field to be percent-encoded or not.

If the URL is expected to be percent-encoded then the current behavior is correct.  This seems reasonable since the entered URL would not be valid if special characters were not properly percent-encoded.

However, an end-user might expect a WYSIWYG to encode their values for them since they may be entering the value manually (this was my original expectation). It may be difficult or impossible for the editor to do this, however, since the editor does not necessarily know which characters to encode and which not.  For example, the URL `images/file<.jpg` would need the less-than sign encoded but NOT the forward slash.

Given all that, I think the current behavior is correct.  Please feel free to close this issue if you agree with my reasoning.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by spiringwriter2** [comment]
Thanks for fix it       [![Image](https://github.com/user-attachments/assets/2ebbf17e-775c-469f-8b23-e88b2731f3a5)](https://rickycasino3.com/au)
