### ISSUE TITLE
IE altering colspan value, where Chrome/FF/Opera do not.

### ISSUE THREAD

**Issue by d00n** [tinymce/tinymce#2615]
In Chrome, Firefox, and Opera, TinyMCE do not alter this on load:
`colspan="100%"`

In IE, TinyMCE drops the % on load:
`colspan="100"`

Load this in IE and Chrome, and view code to see the missing % in IE:

http://fiddle.tinymce.com/unfaab/4

`verify_html: false` has no effect:

http://fiddle.tinymce.com/unfaab/5

Chrome 47, Firefox 40, Opera 34, IE 11
TinyMCE 4.2.6

I know this is not a valid value for colspan, but that begs the question about why the behavior differs on IE.

**Comment by spocke** [comment]
I would guess it fixes the issue. This is not something we will workaround. It's not worth it. So if it's important to you to have exactly the same invalid input as output then do a custom plugin that listens for that attribute value or something and re-convert it back. Might need a custom data-colspan to hold the original value.
