### ISSUE TITLE
Blockquote not working in demo

### ISSUE THREAD

**Issue by olimits7** [tinymce/tinymce#2617]
I try using the blockquote on the following demo in Firefox but nothing happens:

https://www.tinymce.com/docs/demo/full-featured/

**Comment by alecpl** [comment]
Confirmed. It works by the blockquote margins are overwritten by style from codepen.min.css.

**Comment by fyrkant** [comment]
Just like @alecpl says it's an issue with the styles being overwritten by codepen, so not really an issue with TinyMCE. And it seems like we've "fixed" it by removing the blockquote from that example, hehe. Anyway, closing this issue.
