### ISSUE TITLE
Change event only fires once & documentation complications

### ISSUE THREAD

**Issue by ttante** [tinymce/tinymce#2618]
Hey there, so my first issue is that my change event example below only fires the first time and gives me nothing after that, however I realize it may not have been the most optimal (or modern) way to do what I wanted: 

tinymce.init({
selector: '#Description',
setup : function(ed) {
               ed.on('change', function(e) {
               console.log('the content '+ed.getContent());
            });
         }
});

This works the first time but does not fire after that until i press an arrow key.

I found a solution, but it turns out there was an issue with documentation as well. I'm assuming you guys changed the documentation website recently because most of the links on the net leading to specific topics now lead to the root of the documentation... example: http://www.tinymce.com/wiki.php/api4:class.tinymce.Editor
The above leads you to the root of the docs :( ... I wish they wouldn't have changed the url's from before. 

Moving on, I was unable to find what I was looking for in the official docs and luckily was able to get help from the community site. I feel very strongly that what I was looking for should be added to the official docs page, that being: 

(from http://archive.tinymce.com/wiki.php/api4:class.tinymce.Editor)

tinymce.Editor
This class contains the core logic for a TinyMCE editor.
Examples

// Add a class to all paragraphs in the editor.
tinymce.activeEditor.dom.addClass(tinymce.activeEditor.dom.select('p'), 'someclass');

// Gets the current editors selection as text
tinymce.activeEditor.selection.getContent({format: 'text'});

// Creates a new editor instance
var ed = new tinymce.Editor('textareaid', {
    some_setting: 1
}, tinymce.EditorManager);

// Select each item the user clicks on
ed.on('click', function(e) {
    ed.selection.select(e.target);
});

ed.render();

The above should be added to the top of this page on the official docs:
https://www.tinymce.com/docs/api/class/tinymce.editor/#change

That would have saved me hours!
 Thank you for your help and hopefully this saves other developers as much time as it would have for me :)

**Comment by GurumurthyPana** [comment]
I am also facing same problem, con't able to trigger second time on change event.

**Comment by ryd0rz** [comment]
Same issue here... why is a change event NOT really a change event? Sounds like an architectural flaw.
