### ISSUE TITLE
set text direction

### ISSUE THREAD

**Issue by Saad1988** [tinymce/tinymce#2620]
Hi,
i'm iranian and our language is Persian(Farsi). it's Right-to-Left language. like Arabic. in TinyMCE we had problem. because we can just set a Paragraph RTL and  when in a sentence we use both LTR and RTL we can't set true.
for example:
"i love .NET"
to persian :
من عاشق .NET هستم.

we need a feature like Microsoft Word, to select just a word, or multi words, a sentence or a paragraph and set it as RTL or LTR.

Please made it. Thanks.

**Comment by spocke** [comment]
Bidi text is somewhat difficult to handle at the moment since all browsers return a singe DOM range from the selection API. In theory it should return an array of ranges. The W3C people are working on better support for bidi selection at the moment.

**Comment by tinydylan** [comment]
The [Directionality](https://www.tiny.cloud/docs/plugins/directionality/) plugin allows you to change text direction between RTL and LTR. It sounds like this should meet your needs.
