### ISSUE TITLE
Feature: placeholder

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2623]
Need placeholder option, work like 'placeholder' attribute in `<input>`

**Comment by salkiducky** [comment]
Also wanting this if possible!

**Comment by vrinceanuv** [comment]
why was this closed? no placeholder feature?

**Comment by lostkeys** [comment]
I just wanted to let you guys know we released a [placeholder option](https://www.tiny.cloud/docs/configure/editor-appearance/#placeholder) in TinyMCE 5.2
