### ISSUE TITLE
table plugin, multiple inline editors, errors on row/column resize

### ISSUE THREAD

**Issue by deldreth** [tinymce/tinymce#2624]
Can be seen here http://codepen.io/anon/pen/jWLmxB

Resizing any of the rows/columns on a table will throw a TypeError.

`Uncaught TypeError: Cannot read property 'rows' of undefined` `tinymce.min.js:49`

**Comment by headcrab-in-my-room** [comment]
Got the same after re-adding editor https://jsfiddle.net/gxdu4msn/1/
Latest ver 4.3.3 (2016-01-14) in Chrome.
`Uncaught TypeError: Cannot read property 'body' of null`

**Comment by adambiggs** [comment]
Also seeing this error.

```
TypeError: Cannot read property 'body' of undefined
```

**Comment by spocke** [comment]
What browser is this happening in and also what tinymce version?

**Comment by adambiggs** [comment]
I'm using Chrome 51.0 with the latest `4.3.13` version of tinymce.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
