### ISSUE TITLE
Fullscreen toggling when closing source code window

### ISSUE THREAD

**Issue by effetb** [tinymce/tinymce#2625]
Hi,

I use tinymce 4 (CDN).
When you go to fullscreen mode, a mce-fullscreen class is added to html and body tags, but if you open the source code window, when you close the window, the mce-fullscreen class is removed from html and body tags.
It's a problem for me as my interface as some fixed positionned elements that I hide with the mce-fullscreen class to prevent mce editor from being overlayed by my elements :
.mce-fullscreen #sidebar{display : none;}

Thank you.

Regards

**Comment by pH4Lk0n** [comment]
The problem still exist in latest version (4.3.12) and it's visible on main TinyMCE site.
It affects any window closing.
Simple test case:
1. Enter https://www.tinymce.com/
2. Turn on fullscreen
3. Open any TinyMCE window (link, source code, etc)
4. Close window
5. Look at the top (site menu and social icons are visible above TinyMCE menu).

Best regards

**Comment by effetb** [comment]
Hi,

No update ?
The bug is still here.

Regards

**Comment by fyrkant** [comment]
This has been fixed in a coming release, to get a hold of the newest build before the release you can download the nightly build from [this page](https://www.tinymce.com/download/additional-downloads/).
