### ISSUE TITLE
Dropdown inputs too small in table cell properties box

### ISSUE THREAD

**Issue by andrejsverza** [tinymce/tinymce#2627]
There are several "selects" in table cell properties window, which cannot accommodate option texts. This should be fixed by reorganizing the form and at least doubling the width for "selects".
![tinymce433](https://cloud.githubusercontent.com/assets/2128661/12320851/a2173a2a-bab3-11e5-81ed-2cf502fdf2ec.png)

**Comment by tinydylan** [comment]
In TinyMCE 5, we rearranged this form to address this issue. It now looks like this:

![image](https://user-images.githubusercontent.com/41112113/79700550-d7e75e80-82d9-11ea-9f5c-9406704cd205.png)
