### ISSUE TITLE
Issue with Quoting when last text is URL

### ISSUE THREAD

**Issue by networkn** [tinymce/tinymce#2630]
Hi We have noticed an issue on geekzone.co.nz which as I understand it uses a CDN version of TINY MCE, whereby if you QUOTE a post, and the last part of the quote is a URL, when you start typing, the first letter has an underline, like a URL, and you can't do anything with it, and if you click post, it says the open/close tags are not correct. 

The workaround is to put 2 spaces on the end of the URL but this isn't exactly intuitive.

**Comment by spocke** [comment]
On what browser is this happending? Could you provide step by step instructions for us to reproduce it on the tinymce.com or fiddle.tinymce.com site.

**Comment by networkn** [comment]
Hi There!

I am using Chrome. I am not sure how I can reproduce it on either of those sites, however ;

Make a post, make a url such as http://www.geekzone.co.nz the very last thing in that post. 

Then REPLY to that Post, using the quote button so that the url is included. 

I have tried to include a screenshot,  

![image](https://cloud.githubusercontent.com/assets/16710483/12348382/ab7c68c4-bbcb-11e5-97bd-5c3df8f02778.png)

**Comment by networkn** [comment]
If you try and post that reply, it will tell you the open/close tags are not correct. 

The work around is that you manually put 2 spaces before the carriage return after the [/quote] and it works fine.

**Comment by spocke** [comment]
If we can't reproduce it out side you environment it might be an integration issue so we need to have a way to reproducing it locally. Thanks

**Comment by networkn** [comment]
Hi. 

I have explained how you can reproduce it step by step, but I can't do it in the environments you provided because I can't simulate a reply with quote? If you have another forum I can try it with I am happy to do this, but I expect it will need to be the exact same version that is included in the cloudflare CDN?

How can we proceed in order to fix it?
