### ISSUE TITLE
cache_suffix breaks importcss, better fix for #2223

### ISSUE THREAD

**Issue by PromontoryProtean** [tinymce/tinymce#2632]
I had been using a workaround in v4.1.x to address #2223. My work around broke in v4.3.x due to the new image features. Classes such as figure.align-left were getting imported into my formats list, so I went back and took another look at my fix. I believe my solution is better now.

The only thing I needed to change in importcss/plugin.js (after removing my old fix) was add the following:
```if (href)
       href = href.split("?")[0];```

So now the entire append function (inside the getSelections(doc, filFilter) function is as follows. Are there any potential side effects that I might have missed here? Is this a candidate for inclusion if I submit it as a pull request?

```
function append(styleSheet, imported) {
    var href = styleSheet.href, rules;

    // the following 2 lines are the only alterations needed in this file to fix https://github.com/tinymce/tinymce/issues/2223
    // had to change my approach due to v4.3.x adding figure.align-left type classes - I think this is a better spot to handle it either way
    if (href)
        href = href.split("?")[0];

    if (!href || !fileFilter(href, imported) || isSkinContentCss(href)) {
        return;
    }

    console.log("append");

    each(styleSheet.imports, function (styleSheet) {
        append(styleSheet, true);
    });

    try {
        rules = styleSheet.cssRules || styleSheet.rules;
    } catch (e) {
        // Firefox fails on rules to remote domain for example:
        // @import url(//fonts.googleapis.com/css?family=Pathway+Gothic+One);
    }

    each(rules, function (cssRule) {
        if (cssRule.styleSheet) {
            append(cssRule.styleSheet, true);
        } else if (cssRule.selectorText) {
            each(cssRule.selectorText.split(','), function (selector) {
                selectors.push(tinymce.trim(selector));
            });
        }
    });
}
```

**Comment by spocke** [comment]
Fixed this one slightly different. https://github.com/tinymce/tinymce/commit/753c79a86e5ce5254d2cf50f90309fc06f7a26bd
