### ISSUE TITLE
is forced_root_block: false deprecated?

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2634]
A important basic function not working since one year with the button for "align left", "align right" and "align center": https://github.com/tinymce/tinymce/issues/2161

is forced_root_block: false not supported anymore?

I know here are many reports, but the error is one of the basic functions and ought to be corrected quickly, or?

Another problem with a basic function is with links in forced_root_block. In chrome, when I set a link and press return, the new line beginning with a link, but after this first character the second character and so on is a normal text: https://github.com/tinymce/tinymce/issues/2113 and https://github.com/tinymce/tinymce/issues/1245

**Comment by spocke** [comment]
Have had thoughts of removing it since since paragraphs is what makes sense in any rich text editor that edits documents. Also all formatting code needs to handle basically two separate scenarios with that option.

**Comment by Daijobou** [comment]
I see your point, but in my eyes this option is far more important. In my opinion “forced_root_block=false” should be the default setting. you're right, of course, that news/blog articles, which are written in paragraphs are the “correct” way, but a normal user using forums or comment systems doesn't usually write (or think) in “paragraphs.”

The easiest explanation: Tinymce is an extension for textarea; textarea doesn't write paragraphs. Ckeditor doesn't write paragraphs in vbulletin. The editor in phpbb3 doesn't write paragraphs. If you cancel your support for “forced_root_block=false,” tinymce will no longer be a viable option for small community projects; only blogs or similar projects will be able to make any meaningful use of it.

You do great work and I hope you will reconsider and “forced_root_block=false” will get further support. Thank you.

**Comment by Daijobou** [comment]
Is here a chance that you will fix it?

**Comment by Daijobou** [comment]
I would appreciate a short answer. ;)

**Comment by alphestdev** [comment]
We and all our (TinyMCE) users are developers. We never write in paragraphs. We write code, descriptions, comments. We need exact spacing and new lines. `<p>`'s break our desired formatting.

**Comment by voku** [comment]
same here, if we use "forced_root_block: false" we can't save (show) nbsp or breaks (<br />) with TinyMce ... :/

**Comment by Afraithe** [comment]
But, what is a paragraph for users? You can CSS paragraphs to behave just like a SHIFT+ENTER and noone would know the difference?

**Comment by voku** [comment]
What if we want to wrap the content with <p>-tags in the backend, so we can use the content e.g. in a newsletter?

**Comment by alphestdev** [comment]
@Afraithe The difference becomes visible when applying per-line Identation, formatting like blockquote, pre and many more. TinyMCE 4.3.8 is unable to do that properly with `<p>`'s placed everywhere.

**Comment by Afraithe** [comment]
II would say it's the other way around, most features wont work properly unless wrapped in paragraphs.

@voku I would say your doing something wrong if your having that issue.

That said, it is more likey we will be rewriting this logic into a plugin instead of an option like it is now, and it will work with paragraphs internally, but on output will convert it to BR's for example.

**Comment by alphestdev** [comment]
@Afraithe If you can make plain-text-like editing experience using solely a paragraph structure, we would most probably not even need BR conversion plug-in. Cleaner code, less chance for bugs. Everybody wins. But can it be produced? Or will we be left with unpredictable behavior.

**Comment by andybak** [comment]
Here's my scenario. I have two mce fields on the same page: summary and content. The content goes to an email newsletter. Control over CSS in emails is very limited.

If the summary is wrapped in p then it has way too much padding. I need this markup to be directly inside a td for the spacing to match the design. I want to allow br, a, strong, em etc.

A hacky workaround is to strip p upon rendering. But this breaks the wysiwyg aspects and has the potential for the user to send an email out to thousands of users with unexpected formatting (yes - I always tell them to preview or send a test email first but your know what people are like). There are edge cases such as how to handle multiple paragraphs etc.

**Comment by donShakespeare** [comment]
https://github.com/donShakespeare/twExoticMarkdownEditor
This superb pure Markdown Editor plugin will die without this feature. 
**PLEASE** leave this option.

```
tinymce.init({
  selector: "textarea",
  forced_root_block : "", //!important
  force_br_newlines : true, //!important
  force_p_newlines : false, //!important
  valid_elements: "br", //!important
  paste_as_text: true, //!important
  external_plugins: {
    twExoticMarkdownEditor: "[[++assets_url]]components/tinymcewrapper/tinymceplugins/twExoticMarkdownEditor.js", //!important
  ...
  },
});
```

**Comment by lawrenz1337** [comment]
As a user of 
> https://github.com/donShakespeare/twExoticMarkdownEditor

this option is very important. PLEASE leave this option, otherwise  the markdown editor will die :(

**Comment by rthrash** [comment]
Chiming in in support for putting control back in the developers'/site owners' hands per @donShakespeare's request.

**Comment by andybak** [comment]
The ideal solution would be a "snippet mode". For times when we want TinyMCE to edit text that will be included inside a element that disallows other block level or inline elements (such as p or li).

In this mode all that would be allowed would be other inline elements. And wrapping with a root element would be disabled.

**Comment by ethernidee** [comment]
Forced_root_block is really handy for inline mode. When you allow to edit many blocks on page just-in-place without any extra div/p, but with possibility to insert any markup, if desired.

**Comment by xantari** [comment]
Still no solution to this in TinyMCE 5?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
