### ISSUE TITLE
YouTube link being broken when inserted by media plugin

### ISSUE THREAD

**Issue by cristianfraser** [tinymce/tinymce#2636]
I'm trying to insert a YouTube video into TinyMCE with the media plugin, but every link is changed from `https://www.youtube....` into `//www.youtube....`, so the embedded iframe is shown as `<iframe src="//www.youtube.com/embed/8Nq-gEG-E04" frameborder="0" width="420" height="315" allowfullscreen="allowfullscreen"></iframe>`, with the `src` attribute missing the starting `https:`, so no video is shown as the URL isn't resolved.

I was wondering why it happened, and the only answer I can come up with is the regex expressions for YouTube links:

	{regex: /youtu\.be\/([\w\-.]+)/, type: 'iframe', w: 560, h: 314, url: '//www.youtube.com/embed/$1', allowFullscreen: true},
	{regex: /youtube\.com(.+)v=([^&]+)/, type: 'iframe', w: 560, h: 314, url: '//www.youtube.com/embed/$2', allowFullscreen: true},
	{regex: /youtube.com\/embed\/([a-z0-9\-_]+)/i, type: 'iframe', w: 560, h: 314, url: '//www.youtube.com/embed/$1', allowFullscreen: true},

where the URL is set to start with `//`, and then a little below in the code, the original URL is replaced with that one, making the resulting iframe have that URL as source instead of the one starting with `https:`.

And as I can't find any other people with this problem, I was wondering why this is like this, and what solution does it have? If its a bug how come it hasn't been noticed?

**Comment by spocke** [comment]
// is a valid prefix and should resolve to the same protocol as the current page. So can't reproduce this one.

**Comment by cristianfraser** [comment]
Ok, if that's the case then it's alright. Probably has to do more with YouTube being blocked at work (was unblocked when I tested this). Probably only https YouTube was unblocked and not the http version. I'll look into that.
