### ISSUE TITLE
[IE11] Japanese Kanji characters may be cleared

### ISSUE THREAD

**Issue by joshvo89** [tinymce/tinymce#2639]
Hi, I have an issue
Enter an empty line (a line break only) at the first line.
Type 32 kana characters at the second line, pressing neither the enter key nor the space key.
     e.g., あああああああああああああああああああああああああああああああい
-> Japanese Kanji is cleared and the character my last typed is left alone.

Thanks,

**Comment by spocke** [comment]
What is the problem does't IME work as it's supposed to?

**Comment by joshvo89** [comment]
Hi, I run on this site on IE 11: https://www.tinymce.com/docs/demo/basic-example/#liveexample

1. Enter an empty line (a line break only) at the first line.
2. Type 32 kana characters at the second line, pressing neither the enter key nor the space key.
e.g., あああああああああああああああああああああああああああああああ

-> Current Result: There are 2 characters on editor
ああ
-> Expected result
No characters must be cleared.

Is this a bug on tinymce??? Because my site use tinymce have a same problem like this.

Thanks

**Comment by spocke** [comment]
Hmm, can't seem to reproduce this on IE 11 on Windows 10 using Hiragana. I pressed Enter after the "integration." text and entered "ぉぉぉぉぉぉ" since I don't usually use IME:s I hope this would reproduce the issue. Do you use IME Pad or keyboard? What version OS etc is used?

**Comment by joshvo89** [comment]
Hi, I use IME, my OS is window 8.1 Pro.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
