### ISSUE TITLE
 Paste the copied image from the list

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2640]
Hello.
Your product - it's a best js library, widely used in developing.
Recently problem has been discovered:

paste_as_text: true
1)insert list from editor
2)insert image in list ( and add attribute "alt" if he empty)
3)select image
4)copy image
5)ctv +v
bug: insert alt attribute

example:http://codepen.io/anon/pen/OMOwzN

problem is inside copy process, when i copy selected image in buffer is obtained : 
`<ul><li><img ></li></ul>`

**Comment by spocke** [comment]
I guess it shouldn't paste anything then? Now if pastes the alt attribute as text.
