### ISSUE TITLE
Javascript error when handling multiple editor instances on Edge 

### ISSUE THREAD

**Issue by gwissem-mention** [tinymce/tinymce#2642]
Hi,

To reproduce the bug, you need a textarea and an input button in your html, and then you need to write some javascript that : 

- calls tinymce.init() with selector equals to '#textarea_id'
- onclick on the button will remove the textarea from the DOM, injects a new one and calls tinymce on it again.

When i tried to do this, it works pretty fine everywhere but on Edge under windows 10 (running inside a virtual machine).
Further details about the error : 

- on the console i get the exception : Object Excected 
    tinymce.js (1168, 2)

- when i go to this line here is the block of code i find : 
```
        // Support: IE>8
	// If iframe document is assigned to "document" variable and if iframe has been reloaded,
	// IE will throw "permission denied" error when accessing "document" variable, see jQuery #13936
	// IE6-8 do not support the defaultView property so parent will be undefined
	if ( parent && parent !== parent.top ) {
		// IE11 does not have attachEvent, so all must suffer
		if ( parent.addEventListener ) {
			parent.addEventListener( "unload", function() {
				setDocument();
			}, false );
		} else if ( parent.attachEvent ) {
			parent.attachEvent( "onunload", function() {
				setDocument();
			});
		}
	}
```
the error is on the line `if ( parent && parent !== parent.top ) { ` and by debugging a bit, 'parent' is an object that doesn't have a 'top' attribute.

- here is the stacktrace of the exception : 
```
[Main Thread]
Sizzle.setDocument [Line: 1168, Col: 2], tinymce.js
Sizzle [Line: 878, Col: 3], tinymce.js
DOMUtils.prototype.select [Line: 7179, Col: 4], tinymce.js
serialize [Line: 13299, Col: 5], tinymce.js
Editor.prototype.getContent [Line: 32278, Col: 5], tinymce.js
Editor.prototype.save [Line: 32118, Col: 4], tinymce.js
Editor.prototype.remove [Line: 32511, Col: 5], tinymce.js
EditorManager.remove [Line: 33588, Col: 4], tinymce.js
EditorManager.remove [Line: 33545, Col: 6], tinymce.js
window.tinymceRegisterEvents [Line: 73, Col: 9], _tinymce.js
Anonymous function [Line: 5809, Col: 17], guided.js
[Async Call]
Anonymous function [Line: 5808, Col: 13], guided.js
j [Line: 1, Col: 1], vendor.js
k.add [Line: 1, Col: 1], vendor.js
render [Line: 5805, Col: 9], guided.js
Anonymous function [Line: 3976, Col: 13], guided.js
j [Line: 1, Col: 1], vendor.js
k.add [Line: 1, Col: 1], vendor.js
Anonymous function [Line: 4241, Col: 17], guided.js
j [Line: 1, Col: 1], vendor.js
k.add [Line: 1, Col: 1], vendor.js
```

For those who wanna investigate, if this could help, i noticed this line on the file tinymce/classes/Env.js : 
```
ie12 = (userAgent.indexOf('Edge/') != -1 && !ie && !ie11) ? 12 : false;
```
and i solved the problem by going to the file tinymce/classes/dom/Serializer.js and in the following block of the method 'serialize' : 
```
                                // Explorer won't clone contents of script and style and the
				// selected index of select elements are cleared on a clone operation.
				if (Env.ie && dom.select('script,style,select,map').length > 0) {
					content = node.innerHTML;
					node = node.cloneNode(false);
					dom.setHTML(node, content);
				} else {
					node = node.cloneNode(true);
				}
```
i changed the condition `if (Env.ie && dom.select('script,style,select,map').length > 0) {` to `if (Env.ie && Env.ie < 12 && dom.select('script,style,select,map').length > 0) {`

This prevents doing a IE specific logic on Edge, and seems to be working. Not sure if i broke something elsewhere though.

Any chance you investigate and eventually fix this issue guys ?

**Comment by Zerstoren** [comment]
I have the same problem with MS Edge in Windows 10.
Problem retrying when we re-initialize editor with equals IDs.

For remove trash from "cache" tinymce I remove tinymce instance after DOM clear (before init new tinymce instance), in chrome, ie, firefox etc all work fine but not in edge. Problem solved if you destroy editor before clear DOM.

**Comment by Zerstoren** [comment]
I fix the problem. Need update "if ( parent && parent !== parent.top ) { " to "if ( window.parent && window.parent !== window.parent.top ) {"

Waiting for pull request.

**Comment by spocke** [comment]
Thanks for the patch and reports.
