### ISSUE TITLE
noneditable dragging broken if nested HTML is present

### ISSUE THREAD

**Issue by abecks** [tinymce/tinymce#2644]
System:
noneditable plugin

Description of Problem:
If HTML tags are present inside a noneditable element, that element can no longer be dragged around the editor.

Please see this CodePen for an example of the problem:
http://codepen.io/anon/pen/EPomaV?editors=101

```html
<textarea>
  <p>blah blah blah...</p>
  
  <!-- noneditable's with no HTML tags inside are draggable -->
  <div class="mceNonEditable">
    This is draggable
  </div>
  
  <!-- as soon as they have HTML tags, they are no longer draggable -->
  <div class="mceNonEditable">
    <div class="test">This is not draggable</div>
  </div>
  
  <p>blah blah blah....</p>
</textarea>
```

```js
tinymce.init({
  selector: 'textarea',
  height: 500,
  plugins: [
    'noneditable'
  ]
});
```

I would like to insert rich HTML content into a TinyMCE editor, without it being editable, while maintaining the ability to select it as a whole and drag it around.

I have noticed that the new code and media embeds avoid nesting HTML, perhaps for the same reason?

**Comment by spocke** [comment]
Fixed this in https://github.com/tinymce/tinymce/commit/5dbe0d3cddd21c0d4236bede90365d466e104515

Thanks for reporting this issue.
