### ISSUE TITLE
<p> tag in <li> bullet list causes problem, <p> tag separates line from bullets 

### ISSUE THREAD

**Issue by kwang75** [tinymce/tinymce#2645]
I'm pasting the job description in http://www.indeed.jobs/positions?jvi=o90FZfwx,Job into WYSIWIG block using tinymce. It seems like in the bullet list, since <p> tags are in the <li> tag, it separates another line from bullets.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
