### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range'

### ISSUE THREAD

**Issue by dok** [tinymce/tinymce#2646]
majorVersion: "4", minorVersion: "3.3", releaseDate: "2016-01-14"

to reproduce:
1. copy and paste text (down below)
2. editor.formatter.register({ textSize: {inline: 'span', styles: {'font-size': '%value'}} })
3. select some text
4. tinymce.activeEditor.formatter.remove(styleName, {value : '52px'});

it will throw a ridiculous amount of range selection errors
![screen shot 2016-01-21 at 2 43 03 pm](https://cloud.githubusercontent.com/assets/1214868/12496898/5e6b43d0-c04d-11e5-946d-bda42a09c1ad.png)

![screen shot 2016-01-21 at 2 37 26 pm](https://cloud.githubusercontent.com/assets/1214868/12496783/8c7d69ca-c04c-11e5-9506-87870a5027da.png)

**Comment by spocke** [comment]
Can it be reproduced here:
https://www.tinymce.com/docs/demo/full-featured/

Need steps to reproduce it on fiddle.tinymce.com or the tinymce.com site.

**Comment by adambiggs** [comment]
+1 our users are running into these errors as well.

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
