### ISSUE TITLE
Set height in 4.3.3

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#2647]
Hi,
Currently I am upgrading tinymce from 3.5.6 to 4.3.3. 

I have used the below code to resize the editor by getting the width of the table inside the editor in 3.5.6. But I could not able to find any table inside editor in 4.3.3.

var editorTbl = document.getElementById( "<%= EditorClientID %>_tbl" );

Can you please provide me the opt code for the above code in 4.3.3

Regards,
Kavi

**Comment by Shakil-Shahadat** [comment]
You should have checked the documentation first. Anyway, here it is https://www.tinymce.com/docs/configure/editor-appearance/#height
