### ISSUE TITLE
Cant download Chinese (China) (GB2312) language pack

### ISSUE THREAD

**Issue by JohnnyWoong** [tinymce/tinymce#2662]
Cant download Chinese (China) (GB2312) language pack

**Comment by lnewson** [comment]
I'm going to close this, as this is 4 years old and we no longer have that specific language pack available. I tested downloading both "Chinese (China)" and "Chinese (Taiwan)" language packs from https://www.tiny.cloud/get-tiny/language-packages/ and they both worked as expected. If you can still reproduce this issue though, please do let us know and we'll reopen this.
