### ISSUE TITLE
Re-init for selectors on DOM update

### ISSUE THREAD

**Issue by alexcroox** [tinymce/tinymce#2668]
I have a comment box on a forum always at the bottom. This inits fine with a selector `body.Vanilla textarea`.

However further up the thread there are edit buttons next to each forum post, and these transform a post content box into a textbox to edit the comment.

Calling the init again with the same selector doesn't do anything.

If I run `tinymce.remove();` before the init it successfully activates on the comment box further up, but the bottom original text area doesn't re-init.

```
_jQuery('.EditComment').click(function(e) {

        tinymce.remove();

        setTimeout(function() {

            textEditor.init('body.Vanilla textarea');
        }, 1000);
    });
```

What am I missing?

**Comment by alexcroox** [comment]
If I give the 2nd textarea a unique ID and call init on that after the above it works, so it's failing to loop through all the selector matches on the page it seems, opting to just setup one and not multiple.

**Comment by alexcroox** [comment]
Worth noting, the textareas all have the same ID (I'm using Vanilla forums, so it's out of my control)

**Comment by spocke** [comment]
I think the same id causes problems here. TinyMCE inits editors and uses the id of the textarea as it's unique id. So if there are two editors with the same id the last one will be removed/overwritten.

**Comment by alexcroox** [comment]
OK I'll revisit with a JS solution to randomising the IDs after page load before initializing the editors and let you know if that fixes it
