### ISSUE TITLE
data-mce-resize="false"  not work in ie <=10

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2669]
ie10(can use emulation)
demo:  http://codepen.io/anon/pen/MKXwML

when i click on image with `data-mce-resize="false" ` i see  8(4) little squares for resize image, i cant resize and i wanna see just image select witot squares

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
