### ISSUE TITLE
Error when specifying array in content_css

### ISSUE THREAD

**Issue by Nikita240** [tinymce/tinymce#2670]
This is from the tinymce documentation website:

![image](https://cloud.githubusercontent.com/assets/6479817/12693352/5c57a1f4-c6bc-11e5-8515-95c82f70088a.png)

If you enter an array for the content_css property like in the docs, you receive an error.

![image](https://cloud.githubusercontent.com/assets/6479817/12693386/4c1234c0-c6bd-11e5-8700-122e644c2f2e.png)

Looking at the actual code, it seems that the JS tries to explode the `content_css` property without regard for what kind of input was given. 

```javascript
// Load specified content CSS last
if (settings.content_css) {
	each(explode(settings.content_css), function(u) {
		self.contentCSS.push(self.documentBaseURI.toAbsolute(u));
	});
}
```

The code errors when it tries to execute the javascript [`split()`] (http://www.w3schools.com/jsref/jsref_split.asp) method on an array.

```javascript
/**
 * Splits a string but removes the whitespace before and after each value.
 *
 * @method explode
 * @param {string} s String to split.
 * @param {string} d Delimiter to split by.
 * @example
 * // Split a string into an array with a,b,c
 * var arr = tinymce.explode('a, b,   c');
 */
function explode(s, d) {
	if (!s || is(s, 'array')) {
		return s;
	}

	return Arr.map(s.split(d || ','), trim);
}
```

v4.3.3

**Comment by spocke** [comment]
It checks if the item it splits is an array if it is it will return that array. Do you use cross frame calls or something since it seems to fail to recognize that the object is an array.

**Comment by Nikita240** [comment]
Confirmed. I am retard.

Turns out I was accidentally passing an object.
