### ISSUE TITLE
NS_ERROR_UNEXPECTED on Firefox when init again same id after Ajax reload

### ISSUE THREAD

**Issue by paradise-phantom** [tinymce/tinymce#2671]
When init again Tinymce on same id after ajax reload Firefox has a problem at line 370 in dom/Serializer.js and throw an exception NS_ERROR_UNEXPECTED : 

`impl = node.ownerDocument.implementation;`

I fixed it by adding a condition : 

`if (Env.webkit || Env.opera) {
...
}`

Is there another way to fix that for good ?

**Comment by spocke** [comment]
Did you remove it first. Remove cleans up any resources the editor has.

tinymce.remove(<selector>);
tinymce.init({});

**Comment by paradise-phantom** [comment]
Yes i use tinymce.remove() before initializing. It works perfectly on Chrome or Safari but not on Firefox.

**Comment by spocke** [comment]
I need a way to reproduce this. Can you setup a test case at http://fiddle.tinymce.com thanks.

**Comment by paradise-phantom** [comment]
I reproduce the way to the bug here : http://fiddle.tinymce.com/Xofaab
I init Tinymce a first time, i empty the form, i fill my form with the same content (like an ajax reload), i init Tinymce again and Firefox send an exception : NS_ERROR_UNEXPECTED

**Comment by spocke** [comment]
Can be avoided by using tinymce.remove(); see: http://fiddle.tinymce.com/spfaab

**Comment by Roshanshetty** [comment]
Thanks. It worked for me.. !!

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
