### ISSUE TITLE
cursor before last symbol

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2674]
demo: http://codepen.io/anon/pen/vLaBoK?editors=1010
browser:chrome

type 1 symbol
press "button"
not return focus in editor type more 1 symbol

bug: cursor will be before last symbol

but if press editor buttons (bold for example) this not repeats
may be you have options for fix it?

**Comment by PetrBorisov** [comment]
if delete this `var focusedEditor = editorManager.focusedEditor, lastRng;

				if (editor.selection.lastFocusBookmark) {
					lastRng = bookmarkToRng(editor, editor.selection.lastFocusBookmark);
					editor.selection.lastFocusBookmark = null;
					editor.selection.setRng(lastRng);
				}

				if (focusedEditor != editor) {
					if (focusedEditor) {
						focusedEditor.fire('blur', {focusedEditor: editor});
					}

					editorManager.setActive(editor);
					editorManager.focusedEditor = editor;
					editor.fire('focus', {blurredEditor: focusedEditor});
					editor.focus(true);
				}

				editor.lastRng = null;`
then bug not repeats

**Comment by spocke** [comment]
This is by design. Focus should be lost if you focus something outside the editor in this case the button.

**Comment by PetrBorisov** [comment]
how i can make this button a part of editor(not make 'focusin/out' events)?
(add in toolbar not needed)

i want make my button not in toolbar, but  she work like toolbar buttor (part of editor)
