### ISSUE TITLE
new image caption / figure tag changes

### ISSUE THREAD

**Issue by tombro32** [tinymce/tinymce#2676]
Love the new caption feature when adding/editing an image.

1. However, a class of "image" gets added to the figure tag.  Can this be optional?  Ideally the generated markup does not include any classes.

2. Also, we have the following style_formats set up:

{ title: 'Align Right', selector: 'figure,img', classes: 'photoright' },
{ title: 'Align Left', selector: 'figure,img', classes: 'photoleft' }

when trying to apply one of those styles to the figure tag, nothing happens.  If i manually edit the source code and remove the class="image" on the figure tag and try again, it works properly.

**Comment by spocke** [comment]
There is a undocumented ceFalseOverride option that lets you apply format classes to content editable false elements. See: https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/Formatter.js#L104

Will add some docs to that.

The image class is added for us to know that it's a figure for an image. In theory a figure can contain all sorts of things so it's a safe guard to know that's being edited it also adds some styling to the figure element.

**Comment by tombro32** [comment]
The ceFalseOverride option worked great, thanks!

**Comment by andemt** [comment]
This is still a problem. The ceFalseOverride link above is not working.

**Comment by cmgharris** [comment]
"Will add some docs to that."
That would be great! I've just spent half a day figuring out that I need to add this undocumented option to get my formats to work.
Searching for 'ceFalseOverride' in the tinyMCE 5 docs returns no results.
