### ISSUE TITLE
Insert Link doesn't work in inline mode

### ISSUE THREAD

**Issue by rusmaxim** [tinymce/tinymce#2678]
Link inserted before editor block in Chrome and Safari. In Firefox it gives error
```
TypeError: Argument 1 of Range.setStartBefore is not an object.
```

Fiddle: https://jsfiddle.net/rusmaxim/y0qjva9s/3/

Browser: Safari 9.0.3, Chrome 48, Firefox 44
OS: OS X

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
