### ISSUE TITLE
selecting multiple nodes then start typing should wrap in first node 

### ISSUE THREAD

**Issue by ElBayaa** [tinymce/tinymce#2681]
**Description of problem:**
in inline mode (and may be classic mode as well) when selecting more than one node and replace them, the resulting text is wrapped in a node of the type defined in the option "forced_root_block" or it is not wrapped at all (text node) if the option is set to false or empty, while it should be wrapped in the first selected node.

**Steps to reproduce:**
consider starting with:
````
<div id="editable">
  <h1>header</h1>
  <p> paragraph</p>
</div>
````
1. init tinymce on "editable" div with inline set to true and forced_root_block to false
2. select both header and paragraph (using the mouse or Ctrl+A)
3. with both selected, start typing new text, "new text replacing the header and paragraph" for example

**Expected result:**
````
<div id="editable">
  <h1>new text replacing the header and paragraph</h1>
</div>
````

**Actual result:**
````
<div id="editable">
  new text replacing the header and paragraph
</div>
````

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
