### ISSUE TITLE
4.3.3 community download does not have jQuery plugin

### ISSUE THREAD

**Issue by jayhoytt** [tinymce/tinymce#2684]
The download page (https://www.tinymce.com/download/) Lists the "Download TinyMCE Community" option as having "everything you need for production usage (including a jQuery integration plugin)" however the current download (4.3.3) does not have the jQuery plugin in the zip archive.

**Comment by spocke** [comment]
We fixed this now the latest 4.3.4 version of tinymce has the jquery plugin baked in. So the jQuery package is now removed.
