### ISSUE TITLE
img tag is not working in Firefox. 

### ISSUE THREAD

**Issue by jeanpan** [tinymce/tinymce#2688]
Tried to bind tinymce to img tag, but it's not working in firefox ( my version is 44.0.2 ). 
Here is the JSFiddle link : https://jsfiddle.net/00c7ap1b/2/
As we can see, the img element can be clicked in Chrome and Safari but not Firefox. 
However, the p element is fine in three browsers.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
