### ISSUE TITLE
Tables issue in Chrome

### ISSUE THREAD

**Issue by alejandrogutierrez** [tinymce/tinymce#2690]
I created a table and added another table inside. If I add a col to the parent table a new col is added in the parent table and in the table inside. Im using chrome with the latest  tinymce version.

**Comment by spocke** [comment]
I wasn't able to reproduce does it happen with a existing table if so could you setup a test case for it here http://fiddle.tinymce.com

Thanks.

**Comment by alejandrogutierrez** [comment]
It was my fault
