### ISSUE TITLE
Content not inserted when <hr /> is first child of contenteditable element

### ISSUE THREAD

**Issue by gcorne** [tinymce/tinymce#2693]
See http://fiddle.tinymce.com/wpfaab and 

In Chrome, if the caret is positioned so that the `careElement` === `body`, and then content is inserted an error is thrown in chrome.

```Uncaught NotSupportedError: Failed to execute 'createContextualFragment' on 'Range': The range's container is 'hr', which is not supported.```

This is because the range has been set to use the `<hr />`.

**Comment by spocke** [comment]
Fixed this issue. It was some faulty logic that tired to move the range into the closest block and since HR is kind of a block it tried to move the range into that.

**Comment by gcorne** [comment]
:+1:
