### ISSUE TITLE
Problem when pasting table from Excel.

### ISSUE THREAD

**Issue by bubdou** [tinymce/tinymce#2695]
Make sure TinyMCE is using "paste" plugin.
Create an Excel file with some simple data (2x2 is enough),
Copy/Paste the table to TinyMCE.

It used to work that a table is pasted in TinyMCE, now it just one line plain text.

The issue started from v4.2.6, which is caused by the extractFragment function in
https://github.com/tinymce/tinymce/commit/3039bad250eecc137a965ec764d03af3217d45cb

**Comment by spocke** [comment]
Fixed this one by removing the edge fix since it's solved in the browser.

**Comment by tsuijie** [comment]
Copy/Paste table from excel will strip all styles under chrome v66. Works fine under Microsoft Edge v41. Maybe related to different clipboard funationality?
Tested for v4.7.1 and up.
