### ISSUE TITLE
TinyMCE throws exception when there are focusable shadow-dom elements on the page.

### ISSUE THREAD

**Issue by viridia** [tinymce/tinymce#2697]
I'm seeing an exception in this code because 'elm' has no className attribute:

```
FocusManager.isEditorUIElement = function(elm) {
  // Needs to be converted to string since svg can have focus: #6776
  return elm.className.toString().indexOf('mce-') !== -1;
};
```

This seems to occur when I am changing focus from a polymer component to the TinyMCE editor - looking in the debugger, I see that 'elm' is "#shadow-root". (Note that this has nothing to do with putting TinyMCE inside of a web component, as mentioned in a different bug.)

**Comment by lnewson** [comment]
A fix for this has been merged and will be released as part of the upcoming TinyMCE 5.6 release.
