### ISSUE TITLE
# and @ hints

### ISSUE THREAD

**Issue by antonioaltamura** [tinymce/tinymce#2703]
Hi, some other editors have a very useful feature:
the hashtag and the @.
I mean try to type "@" in github editor and you will get immediately what I mean: some ajax suggestions.
There is a way to accomplish this in tinymce?

**Comment by alfredopacino** [comment]
I noticed there is a plugin already
https://github.com/CogniStreamer/tinyMCE-mention

But I'm having trouble with the angular.js integration :/

**Comment by lnewson** [comment]
Hi,

This feature was added in TinyMCE 5, via the autocompleter functionality. Details on how that can be configured can be found in our documentation: https://www.tiny.cloud/docs/ui-components/autocompleter/. If you have any questions please feel free to log a new issue.

Thanks!

**Comment by roy2651** [comment]
@lnewson hello, Newson, I'm reading doc about autocompleter and minChars must least 1. I'm working on some plugin such as feishu and  shimo.im  when I type @  and show a selection or dialog
