### ISSUE TITLE
Video selection issue

### ISSUE THREAD

**Issue by triplejumper12** [tinymce/tinymce#2704]
In version 4.3.4, when you try to select an embedded video, a preview of the video follows your cursor around, and it appears that the select element changes to what you are currently hovering over and you aren't able to apply any formatting or classes to the video's container.

I have an example at http://fiddle.tinymce.com/dDeaab/6. If you click on the video and try to add the left class, it doesn't actually add the class. But clicking on the paragraph I have, I can add the class to that. (looking at the code to see if the class has been added)

I wasn't able to add a class to the video in version 4.3.3 either, but I was able to see that the left and right classes were available for the video container.

In 4.3.4, I can see that the classes are available if I don't hover over anything on my way to the formats menu, but when I hover over something else, the classes are no longer available.

Not sure if there is a better way of going about adding a class to a video's container?

**Comment by Daijobou** [comment]
I have this issue too in 4.3.4. (Chrome)

**Comment by spocke** [comment]
Fixed this issue. It was problems with the custom drag/drop of cE=false and the shim.
