### ISSUE TITLE
Inconsistent 'paste' behavior in Safari on Mac OS X

### ISSUE THREAD

**Issue by VasiliyZhushma** [tinymce/tinymce#2705]
When pasting web-page content to TinyMCE, Safari inserts plain text when pasting using context menu  command 'Paste'. But when pasting with Cmd+V shortcut, formatted content is pasted.

**Comment by vovashevchenko** [comment]
+

**Comment by masterOL** [comment]
+

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
