### ISSUE TITLE
Dragging selected link removes styling

### ISSUE THREAD

**Issue by starzew** [tinymce/tinymce#2706]
Hi,
I would like to point an issue with moving links in editor.
Steps to reproduce:
1. Go to full featured tinyMce http://archive.tinymce.com/tryit/3_x/full.php
2. Select 'compatible' word (link)
3. Change styles to 'example2' (red one)
4. Move the selection to the other paragraph.
5. Styling disappears.

Expected behaviour: Styling is preserved.
I was using IE11 and Firefox 44.0.2.

Please investigate. Is there a fast workaround for this? 
If you need more detail please reply.
Thanks,
Daniel

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
