### ISSUE TITLE
Omitting TD and TR Closing Tags Causes Subsequent TR to Render on Same Row

### ISSUE THREAD

**Issue by jtark** [tinymce/tinymce#2709]
I've encountered an issue in version 4.3.3 where omitting the closing tag for the last TD and TR elements before beginning a new TR element will cause the new TR element to render on the same row. I've attached a TXT file containing HTML that demonstrates the issue.
[close tag omission test.txt](https://github.com/tinymce/tinymce/files/135273/close.tag.omission.test.txt)

**Comment by spocke** [comment]
Use valid HTML and the editor will work just fine. Thanks.

**Comment by jtark** [comment]
According to the HTML 4.01 spec at https://www.w3.org/TR/html401/struct/tables.html, the closing tags for `<tr>`, `<td>`, and `<th>` elements (among others) can be omitted.

They have a sample table in [section 11.1](https://www.w3.org/TR/html401/struct/tables.html#h-11.1) that omits closing tags for all three of those elements:
``` html
<TABLE border="1"
          summary="This table gives some statistics about fruit
                   flies: average height and weight, and percentage
                   with red eyes (for both males and females).">
<CAPTION><EM>A test table with merged cells</EM></CAPTION>
<TR><TH rowspan="2"><TH colspan="2">Average
    <TH rowspan="2">Red<BR>eyes
<TR><TH>height<TH>weight
<TR><TH>Males<TD>1.9<TD>0.003<TD>40%
<TR><TH>Females<TD>1.7<TD>0.002<TD>43%
</TABLE>
```
When pasted into the source code dialog (tested at https://www.tinymce.com/docs/demo/full-featured/), every cell is rendered on the same row below the caption, with several cells merged together. Opening the source code dialog again, it displays the following HTML:
``` html
<table border="1" summary="This table gives some statistics about fruit flies: average height and weight, and percentage with red eyes (for both males and females)."><caption><em>A test table with merged cells</em></caption>
<tbody>
<tr>
<th rowspan="2">&nbsp;</th>
<th colspan="2">Average</th>
<th rowspan="2">Red<br />eyes</th>
<th>height</th>
<th>weight</th>
<th>Males1.90.00340%</th>
<th>Females1.70.00243%</th>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
```

As for HTML5, the end tag for `<tr>`, `<td>`, and `<th>` elements may be omitted if there is no more content in the parent element or if it is immediately followed by an appropriate element (another `<tr>` element for `<tr>` elements, or a `<td>` or `<th>` element for those elements). See the spec for [tr](https://www.w3.org/TR/html-markup/tr.html#tr-tags), [td](https://www.w3.org/TR/html-markup/td.html#td-tags), and [th](https://www.w3.org/TR/html-markup/th.html#th-tags) tags for references there.

As for the improperly placed closing tags for `<tr>` elements in the file I attached earlier, I only put them in to demonstrate that it would end the row that had no closing tags even though there was a fully closed row in between. I was hoping it would assist in narrowing down how the row was being closed (or not).
