### ISSUE TITLE
Headings are not removed on "Clear Formatting"

### ISSUE THREAD

**Issue by VonRehberg** [tinymce/tinymce#2712]
Hey guys,

I can see, that the unit tests cover removing H1-tags from the editor on pressing "Clear Formatting" but in practice this doesn't work.
This is reproducible on http://archive.tinymce.com/tryit/basic.php by adding a header 1, typing something and then trying to clear the formatting.
Using the removeformat option doesn't work as well.

Could you please check and advice what to do?

Thanks and regards!

**Comment by spocke** [comment]
This is by design. Only formatting like bold, italic fonts etc get removed. Semantic things like tables, paragraphs and headers are kept intact.

**Comment by hiteshkumar2187** [comment]
@spocke Can you suggest how can we remove semantic's as well on remove formatting
