### ISSUE TITLE
Changelog not updated?

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2714]
New version is 4.3.4, but changelog said since days still 4.3.3

https://www.tinymce.com/docs/changelog/

**Comment by spocke** [comment]
Fixed this thanks for reporting.

**Comment by Daijobou** [comment]
Yes its fixed, but under https://www.tinymce.com/ its still 4.3.3

"(News) TinyMCE 4.3.3 maintenance release now available via CDN and download. Changelog."
