### ISSUE TITLE
Multiple instance on same page with different configuration

### ISSUE THREAD

**Issue by mmohamed** [tinymce/tinymce#2717]
When I call "init" with two different configurations for two textarea in the same page, the first is not instantiate (Test Chrome 48.0.2564.109 m) with tinymce 4.2.6
HTML : 
**`<textarea id="a"></textarea>
<textarea id="b"></textarea>`**
JS:
**`tinymce.init({selector: 'a', height: 300});
tinymce.init({selector: 'b', height: 600});`**

**Comment by spocke** [comment]
Should be "#a" and "#b" as selectors. Is that just a sample code, can you provide is with a fiddle at fiddle.tinymce.com thanks.

**Comment by mmohamed** [comment]
Thanks, it's OK
