### ISSUE TITLE
getContent with selector different from id

### ISSUE THREAD

**Issue by alfredopacino** [tinymce/tinymce#2718]
Hi, I have several tinymce editors, there is a way to get the data in this way, without the id attribute?
```
        $('[data-editor]').each(function() {
            var name =  $(this).attr('name');
            form[name] = tinyMCE.get($(this)).getContent();
        });

```

**Comment by spocke** [comment]
You need to correlate it using something like id:s, a selector or a index.

**Comment by alfredopacino** [comment]
I'm sorry I don't get what you mean by "id:s"
