### ISSUE TITLE
TinyMCE Inline Editing Issue

### ISSUE THREAD

**Issue by comparemymove** [tinymce/tinymce#2719]
I have added a TinyMCE WYSIWYG to my page to allow inline editing but for some reason when I try to use Blockquotes or Divs, it doesn't do it. My code is below: -

    $('.template-choice').on('click', function(){
        var template = $(this).children('.template-style').attr('data-template');
        $('#load-template').show();
        $('#page-editor-tools').show();
        $(this).parent('#template-options').hide();
        $('#form_template').val(template + '.twig');
        $('#load-template').load('/assets/admin/templates/' + template, function(){
            // CONTENT BOX
            tinymce.init({
                selector:'.block-region',
                inline: true,
                plugins: [
                    'advlist autolink lists link image charmap print preview anchor',
                    'searchreplace visualblocks code fullscreen',
                    'insertdatetime media table contextmenu paste'
                ],
                content_css: "/assets/stylesheets/style.min.css",
                formats: {
                    alignleft: {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes : 'align-left'},
                    aligncenter: {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes : 'align-center'},
                    alignright: {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes : 'align-right'},
                    alignfull: {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes : 'align-full'},
                    bold: {inline : 'strong'},
                    italic: {inline : 'em'},
                    underline: {inline : 'span', 'classes' : 'underline', exact : true},
                    strikethrough: {inline : 'del'}
                },
                style_formats: [
                    {title: "Headers", items: [
                      {title: "Header 1", format: "h1"},
                      {title: "Header 2", format: "h2"},
                      {title: "Header 3", format: "h3"},
                      {title: "Header 4", format: "h4"},
                      {title: "Header 5", format: "h5"},
                      {title: "Header 6", format: "h6"}
                    ]},
                    {title: "Inline", items: [
                      {title: "Bold", icon: "bold", format: "bold"},
                      {title: "Italic", icon: "italic", format: "italic"},
                      {title: "Underline", icon: "underline", format: "underline"},
                      {title: "Strikethrough", icon: "strikethrough", format: "strikethrough"},
                      {title: "Superscript", icon: "superscript", format: "superscript"},
                      {title: "Subscript", icon: "subscript", format: "subscript"},
                      {title: "Code", icon: "code", format: "code"}
                    ]},
                    {title: "Blocks", items: [
                      {title: "Paragraph", format: "p"},
                      {title: "Blockquote", format: "blockquote"},
                      {title: "Div", format: "div"},
                      {title: "Pre", format: "pre"}
                    ]},
                    {title: "Alignment", items: [
                      {title: "Left", icon: "alignleft", format: "alignleft"},
                      {title: "Center", icon: "aligncenter", format: "aligncenter"},
                      {title: "Right", icon: "alignright", format: "alignright"},
                      {title: "Justify", icon: "alignjustify", format: "alignjustify"}
                    ]},
                    {title: "Colours", items: [
                      {title: "Black", inline: 'span', 'classes': 'font-black'},
                      {title: "White", inline: 'span', 'classes': 'font-white'},
                      {title: "Purple", inline: 'span', 'classes': 'font-purple'},
                      {title: "Green", inline: 'span', 'classes': 'font-green'},
                      {title: "Blue", inline: 'span', 'classes': 'font-blue'},
                      {title: "Red", inline: 'span', 'classes': 'font-red'},
                      {title: "Yellow", inline: 'span', 'classes': 'font-yellow'},
                    ]}
                ],
                fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt"
            }); 
        });
    });

Can Anyone help me with this? The TinyMCE is loaded after a template has been loaded into the site. This is for an inline editing for a Content Management System I am building in Symfony2. As you can see the template is loaded using jQuery so is there a possibility that they are not loaded properly?

**Comment by spocke** [comment]
Seems more like a community support question than a bug. Use the tinymce forums at community.tinymce.com thanks.
