### ISSUE TITLE
Import CSS Plugin adds unwanted <span> tags

### ISSUE THREAD

**Issue by jbogdani** [tinymce/tinymce#2721]
To reproduce:
1. Insert an image (`<p><img src="path-to-image" /></p>`)
2. Select it
3. Format > Other styles > click on a css class, eg.: round-corners

Expected output:
`<p><img src="path-to-image" class="round-corners" /></p>`

Actual output:
`<p><span class="round-corners"><img src="path-to-image" /></span></p>`

It happens the same with block elements, like h*, div, etc.

Tested on latest stable v.4.3.4

**Comment by spocke** [comment]
The imported rule needs to be in the form img.class {} so it knows that it will only apply to images. We can't know the intent otherwise.
