### ISSUE TITLE
Bug selected text in tabCell

### ISSUE THREAD

**Issue by tups** [tinymce/tinymce#2723]
Hello,
I have a bug since the new update tables.
I can not select two lines of text in a table cell (in two different paragraphs or if a text bold or italic)

![sans titre-1](https://cloud.githubusercontent.com/assets/868611/13255346/16c68e1e-da46-11e5-9261-d774edfe8003.png)
![sans titre-2](https://cloud.githubusercontent.com/assets/868611/13255353/1c4d14de-da46-11e5-816d-8f1959497d28.png)

Thanks in advance

**Comment by spocke** [comment]
I fixed this one.

**Comment by zacharyjt** [comment]
I am experiencing this issue as well.  Will the fix be available in the next release, or is there another way to get it?

**Comment by zacharyjt** [comment]
Wanted to check in on this one again, as we have customers asking about it.  Thanks!
