### ISSUE TITLE
Content Security Policy unsafe-inline-styles

### ISSUE THREAD

**Issue by granthoff1107** [tinymce/tinymce#2726]
Editor will cause errors on content security policy for style-src 'self' 

All styles should be converted into classes and only applied through classes instead of inline styling

Currently you can us 'unsafe-inline'; as a work around

**Comment by bwbecker** [comment]
Agreed that this should be fixed.

**Comment by RinkAttendant6** [comment]
This seems to be a duplicate of #1901

**Comment by fyrkant** [comment]
I think this has been fixed so I'm closing this but if you still have the problem leave a comment or open up a new issue.
