### ISSUE TITLE
TinyMCE 4.3.4 - IE11 - Copy&Paste noneditable content

### ISSUE THREAD

**Issue by adoerler** [tinymce/tinymce#2729]
Hi,

I've two cases:

**Paste plugin loaded**
https://jsfiddle.net/p9syzwj6/9/

* Select the X and press Ctr+c => Ctr+v => `<i contenteditable="false">X</i>` gets converted into `<em>X</em>`
* If you select the X, press Ctr+c, than place the cursor behind X you will get `<i contenteditable="false">X<em>X</em></i>` => X is surrounded with `<em>` and inserted INTO noneditable content area.

Please note, that "pastetext" is not enabled!

In Chrome everything works es expected.

**Paste plugin not loaded**
https://jsfiddle.net/p9syzwj6/10/)
* Noneditable content selected

=> IE11: You are not able to paste at all
=> Chrome creates:
```
<i contenteditable="false">X</i><i>X</i>
<div>&nbsp;</div>
```
* Cursor placed after nonedtable content

=> IE11: Tinymce will insert `<em>X</em>` after the noneditable content
=> Chrome creates:
```
<i contenteditable="false">X</i>
<div><i>X</i></div>
```

Please let me know if you need more informations to debug this.

Many thanks in advance
Andreas

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
