### ISSUE TITLE
Inconsistent HTML for underlines

### ISSUE THREAD

**Issue by arlomedia** [tinymce/tinymce#2730]
If I select existing text in the editor and then click the Underline button in the toolbar, the text gets styled with a span tag:

&lt;span style="text-decoration: underline;"&gt;test 1&lt;/span&gt;

If I paste underlined text from another source, like a Word document, the text gets styled with an underline tag:

&lt;u&gt;test 2&lt;/u&gt;

You can see this in the sample editor on the tinymce.com home page.

It would be nice if the two situations used the same HTML. Of the two, I would personally prefer the span style.

**Comment by arlomedia** [comment]
Actually I don't know at what point the formatted text in Word gets changed to HTML text; maybe that is a function of the OS and TinyMCE just takes the converted HTML. I'm using Mac OS 10.11.3 and Safari 9.0.3.

**Comment by spocke** [comment]
This is a matter of config. You can configure tinymce to produce U elements when you what to underline something. We haven't changed that behavior since it could break integrations.

**Comment by arlomedia** [comment]
Is there a way to make it produce span elements when you paste? If so, can you tell me what to search for in the documentation?

Meanwhile, I am using this setup code:

		paste_preprocess: function(plugin, args) {
			args.content = args.content.replace(/&lt;u&gt;/g, "&lt;span style=\"text-decoration: underline;\"&gt;");
			args.content = args.content.replace(/&lt;\/u&gt;/g, "&lt;/span&gt;");
		},

**Comment by fyrkant** [comment]
I think the paste_preprocess init is the place to go if you want to edit the pasted content! 👍
