### ISSUE TITLE
Codesample plugin removes HTML code

### ISSUE THREAD

**Issue by felipegtx** [tinymce/tinymce#2732]
I've used de codesample plugin to save some HTML code but when I'm trying to edit that information, tinyemce removes all the html code from there. 

PS: I'm using the angularJS plugin [suggested here](https://www.tinymce.com/docs/integrations/angularjs/)

My code goes as follows:
```javascript
$scope.tinymceOptions = {
            height: 400,
            inline: false,
            plugins: "textcolor colorpicker image link hr table fullscreen code codesample",
            menubar: false,
            default_link_target: "_blank",
            toolbar1: "alignleft aligncenter alignright alignjustify bold italic bullist numlist | forecolor backcolor styleselect fontselect fontsizeselect | hr",
            toolbar2: "undo redo removeformat | image link table codesample code | fullscreen"
        };
```

Edit: I'm using version `4.3.4 (2016-02-11)`

**Comment by felipegtx** [comment]
Well, I took the time to take a look into the problem and came up with a solution materialized in the PR #2734

**Comment by spocke** [comment]
Might be a bug in the angular plugin. But the contents in a textarea needs to be properly encoded:
This is wrong:
<textarea><pre class="language-markup"><code>&lt;b&gt;hello world&lt;/b&gt;</code></pre></textarea>
This is right:
<textarea>&lt;pre class=&quot;language-markup&quot;&gt;&lt;code&gt;&amp;lt;b&amp;gt;hello world&amp;lt;/b&amp;gt;&lt;/code&gt;&lt;/pre&gt;</textarea>

So I can't fix this since the angular project isn't within our control.

**Comment by felipegtx** [comment]
Feedback for this issue (copy/paste from the **[angularJS plugin thread](https://github.com/angular-ui/ui-tinymce/issues/236)** - just in case anyone else falls for this)

> As I was working on the Plunker code I found out what the problem was. Turns out that I was asking my .Net code to write the raw contents into the textarea. That was messing up the blocks start/end data since it doesn't HtmlEncode the information.
>That solved the problem for me :+1:

**Comment by sawang1990** [comment]
`<link rel="stylesheet" type="text/css" href="prism.css">
<script src="prism.js"></script>`

**Comment by sawang1990** [comment]
`<link rel="stylesheet" type="text/css" href="prism.css">
<script src="prism.js"></script>`
