### ISSUE TITLE
Custom text color is discarded on page reload

### ISSUE THREAD

**Issue by carlosvini** [tinymce/tinymce#2733]
When you select a custom text color from the Datepicker, the color is discarded when the page is reloaded.

Would be nice if the selected color was saved, using cookies or whathever you think is better.

You can test this behavior here: https://www.tinymce.com/docs/demo/full-featured/

**Comment by staabm** [comment]
I guess localStorage would be a great fit.

**Comment by tinydylan** [comment]
Hi,

TinyMCE now has this feature. The custom colors are stored in localStorage.

Thanks!
