### ISSUE TITLE
Localization doesn't work well with multiple editor instances with different language for each instance in TinyMCE 4.3.4

### ISSUE THREAD

**Issue by DamienLaw** [tinymce/tinymce#2740]
How to reproduce:

    <script type="text/javascript">
        tinymce.init({
			selector: "#textarea1",
			plugins: [
				"advlist autolink lists link image charmap print preview anchor",
				"searchreplace visualblocks code fullscreen",
				"insertdatetime media table contextmenu paste"
			],
			toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
			language: "en_GB"
		});

		tinymce.init({
			selector: "#textarea2",
			plugins: [
				"advlist autolink lists link image charmap print preview anchor",
				"searchreplace visualblocks code fullscreen",
				"insertdatetime media table contextmenu paste"
			],
			toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
			language: "zh_CN"
		});
    </script>

    <form method="post" action="dump.php">
        <textarea id="textarea1" name="textarea1"></textarea>
	    <br />
    	<textarea id="textarea2" name="textarea2"></textarea>
    </form>

If you run this, two editors will be initialized with different languages. The first editor is in English and the second in Chinese.

- [ ] Click on any menu item in the menu bar of the first editor (English)

<table>
<tr>
<th>Expectation</th>
<td>Dropdown menu should be in English.</td>
</tr>
<tr>
<th>Reality</th>
<td>Dropdown menu is in Chinese.</td>
</tr>
</table>

-----------------------------------------------------

- [ ] Hover over any button on the first editor (English)

<table>
<tr>
<th>Expectation</th>
<td>Resulting tooltip should be in English.</td>
</tr>
<tr>
<th>Reality</th>
<td>Resulting tooltip is in Chinese.</td>
</tr>
</table>

-----------------------------------------------------

- [ ] Use `inline: true` while initializing both editors

<table>
<tr>
<th>Expectation</th>
<td>First editor should be in English.</td>
</tr>
<tr>
<th>Reality</th>
<td>Both editors display in Chinese without a single shred of English text on any of them.</td>
</tr>
</table>

**Comment by spocke** [comment]
Yes, we don't support this since the common case is to have the UI in one language.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
