### ISSUE TITLE
Upon resizing tables width, height becomes 2 pixels smaller, vice versa upon resizing height

### ISSUE THREAD

**Issue by jesse2612** [tinymce/tinymce#2741]
Whenever you resize a table's width, the height automatically decreases by 2 pixels. vice versa upon resizing a table's height: the width automatically decreases by 2 pixels.
![320x138](https://cloud.githubusercontent.com/assets/16253085/13372072/cb8c6168-dd37-11e5-8595-2c100fd778c2.jpg)
![400x136](https://cloud.githubusercontent.com/assets/16253085/13372071/cb8bce4c-dd37-11e5-9d81-2b8993c09290.jpg)

**Comment by fyrkant** [comment]
We have rewritten the table plugin so old table issues are no longer relevant, if you still have this problem please open up a new issue.
