### ISSUE TITLE
Submenu and tooltips with wrong positions

### ISSUE THREAD

**Issue by DQvsRA** [tinymce/tinymce#2742]
Hello
Tinymce is great tool thank you.
But we have an issue when use it inside tab that inside modal in semantic-ui
![image](https://cloud.githubusercontent.com/assets/442111/13397568/9ce3de88-df0b-11e5-8944-3ab60b290d15.png)

And this offset about the height of toolbar (30px)

It's Chrome 48.0.2564
Please help us to fix this.

**Comment by spocke** [comment]
I'm guessing a CSS conflict possible a forced margin on all divs. So this is more of a integration issue than a tinymce bug. We have a few reset rules to remove the common conflicts but not this one.

**Comment by DQvsRA** [comment]
Pleace take a look on that, that shown wrong calculated position 
![gif](https://cloud.githubusercontent.com/assets/442111/13398360/1651e406-df0f-11e5-9f65-0b9bc8a47c42.gif)

**Comment by DQvsRA** [comment]
And when i setup with two toolbars like:
textEditor.tinymce({
toolbar1     : '.....',
toolbar2    : '...',
...}
everything works fine.

**Comment by spocke** [comment]
If it can be reproduced at fiddle.tinymce.com I can look into it. See if it's possible to add more css reset rules.

**Comment by DQvsRA** [comment]
This css rules fix the problem

  .mce-tooltip {
        position: fixed !important;
  }
  .mce-panel.mce-floatpanel.mce-menu {
        position: fixed !important;
  }

**Comment by akbarpn136** [comment]
Yup, it works for me too, i have the same problem.. thanks @DQvsRA for great solution.
![screenshot from 2016-04-06 15-10-59](https://cloud.githubusercontent.com/assets/2337170/14310064/24c093c6-fc0a-11e5-813a-bd57c6c64719.png)

**Comment by marcel-k** [comment]
Thanks @DQvsRA for a simple but effective solution!

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by rommeliusAlejandro** [comment]
Just an update, to have a complete fix for this problem remove the .mce-menu class from the second set of rules:
.mce-tooltip {
position: fixed !important;
}
.mce-panel.mce-floatpanel {
position: fixed !important;
}

otherwise the color picker and emojis menu and I guess all the ones with arrow persist with the problem.

**Comment by Michal0307** [comment]
My solution was removing table rows which were before textarea(tinymce)
