### ISSUE TITLE
Sometimes whitespace removed before link insertion

### ISSUE THREAD

**Issue by Koc** [tinymce/tinymce#2743]
#2595 still occurs in 4.3.4 using mozilla firefox 43. Video with bug https://www.youtube.com/watch?v=lfBHjiglp3s&feature=youtu.be&hd=1

**Comment by spocke** [comment]
I can't reproduce it here:
http://fiddle.tinymce.com/1qfaab

I double clicked on a word like "aaaa" and made a link without any removal of whitespace.

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
