### ISSUE TITLE
Add New Template Below and Outside of Original Template

### ISSUE THREAD

**Issue by johncoughlin** [tinymce/tinymce#2745]
Hi,

I have created some custom templates for TinyMCE. The goal is to allow the user to insert a template and edit the content. This part of the process is working well.

I would then like the user to be able to click below that template to get a cursor outside of the TinyMCE template area, so they can add non-template content, or possibly even another template.

It seems though, once the user is in a template, there is no way to "click outside" of the template to reposition the cursor. The only way I am able to achieve this is by "view source" and then adding some code below where the template ends.

Any feedback is appreciated.

Thanks

![tinymceissue_01](https://cloud.githubusercontent.com/assets/9734901/13405033/7689aec8-ded1-11e5-9591-1728c3ad87a9.jpg)

**Comment by fyrkant** [comment]
I think that we have fixed this so I am closing this issue, but if I'm wrong just leave a comment or open up a new issue.
