### ISSUE TITLE
text in table is smaller

### ISSUE THREAD

**Issue by bgailer** [tinymce/tinymce#2747]
HTML:
![screenshot028](https://cloud.githubusercontent.com/assets/1512596/13414309/afd3b82e-df1f-11e5-9b12-08c10ee5a423.gif)
Style:
`.o1{color:gray; margin:14px;}
.o2{color:blue; margin:1px;}
`
Result:
![screenshot027](https://cloud.githubusercontent.com/assets/1512596/13414318/c7a2f76c-df1f-11e5-80b1-4b25836f0873.gif)
Is this by design or is it a bug?

**Comment by spocke** [comment]
The default content.css has overrides for td,th so it interferes. I'm guessing we should fix this since it's for older version of IE that didn't properly inherit table styles.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
