### ISSUE TITLE
IE11 and Tamil Font Rendering in Tables not working as Intended

### ISSUE THREAD

**Issue by Chris-Developer** [tinymce/tinymce#2748]
Hello,

We are running into an issue when entering Tamil fonts into tables. Outside of the table they render correctly.

If we enter the text 'qkqkf' it should render as 'ஆமாம்' however you can see from the screenshot below that inside tables, it does not render correctly.
![image](https://cloud.githubusercontent.com/assets/17561361/13417955/a1c3ac9e-dfc4-11e5-8eb8-4a36108df63f.png)

This issue also occurs on the TinyMCE editor on tinymce.com shown below.
![image](https://cloud.githubusercontent.com/assets/17561361/13418023/4ef54c42-dfc5-11e5-9d17-c166dfa5f294.png)

This does not affect Chrome or Firefox, only IE11.

In addition, when using Chinese Simplified, typing outside of tables will display the language auto complete selector, however inside the tables, it does not open long enough (sometimes can't even be seen) to select the chinese equivalent, it will disappear not allowing a selection. Again works fine in Chrome and Firefox, but not in IE11.

**Comment by spocke** [comment]
Is Tamil using IME composing. If yes then it could be related to another fix we made on tables that has yet been released.

**Comment by Chris-Developer** [comment]
Hi spocke,

Thanks for taking the time to reply. I don't believe the Tamil font is using IME composing, however the Chinese Simplified is.

I went ahead and copied the following commits locally.

c1d1b11831afd5f2e579417710058d76383e7bc6
06fcb0eeee5d74731ab5acb28a9db0eb5ac53c62

We are using v4.3.1 so I went ahead and copied over 18fbfcac2f6ab2b9e4abffc2093cee881217ab0b as well.

These did not change anything, the rendering is still broken in IE11, I've attached a .swf (can be opened in your browser) video to help illustrate the issue.

[TinyMCE-Table-Bug.zip](https://github.com/tinymce/tinymce/files/153817/TinyMCE-Table-Bug.zip)

This was recorded using IE11 on the tinymce editor on the tinymce website, our local version containing the commits copied over functions exactly the same as in the video.

First I write the Chinese Simplified inside and outside the tables, you can notice the IME does not display at all when inside the table.

I then write using Tamil, one thing to note, you can see the text remains red when entered outside the table, like it's still being evaluated, however inside the table it will flash red for mere milliseconds (might not even show on the video but it does). I gather that the evaluation is being canceled after every input, rather then continuing to evaluate the entire input like outside of the table.

Finally, it seems this is similar to: #2661(Seems like the input evaluation is getting cancelled per character rather then continuing when inside the table, same as our issue)

**Comment by Chris-Developer** [comment]
Hi spocke,

Do you have any updates on this issue?

Thanks.

**Comment by spocke** [comment]
Make sure you guys have 4.3.7 since I can't reproduce any IME issues on IE 11 in tables using that version.

**Comment by Chris-Developer** [comment]
Hi spocke,

I've re-tested this on the editor found on the tinymce homepage (www.tinymce.com) which is running 4.3.7 and the issue is still the same as before in IE11 which is shown in the video in my previous comment. Chrome and Firefox continue to work correctly.

**Comment by fyrkant** [comment]
We have rewritten the table plugin so old table issues are no longer relevant, if you still have this problem with the new table plugin please open up a new issue.
