### ISSUE TITLE
Inconsistency when pasting text with bullets from word in IE, EDGE

### ISSUE THREAD

**Issue by thewraith** [tinymce/tinymce#2749]
When "Paste as text" is active and I paste text formatted with bullets from word 2013, IE11 and EDGE renders it differently than Chrome, Mozilla and IE10, IE9.

In Chrome the numbering/bullets are pasted as part of the text and in IE11 numbers/bullets are missing.

TinyMCE version 4.3.4 (2016-02-11)
IE11 version is 11.0.9600.17420

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
