### ISSUE TITLE
tinyMCE editor not support XHTML

### ISSUE THREAD

**Issue by NTMan** [tinymce/tinymce#2751]
Demonstration: http://tinymce.sy24.ru/

`tinymce.dev.js:119 Uncaught InvalidStateError: Failed to execute 'write' on 'Document': Only HTML documents support write().writeScripts @ tinymce.dev.js:119(anonymous function) @ tinymce.dev.js:283(anonymous function) @ tinymce.dev.js:284

plugin.dev.js:119 Uncaught InvalidStateError: Failed to execute 'write' on 'Document': Only HTML documents support write().writeScripts @ plugin.dev.js:119(anonymous function) @ plugin.dev.js:139(anonymous function) @ plugin.dev.js:140

plugin.dev.js:119 Uncaught InvalidStateError: Failed to execute 'write' on 'Document': Only HTML documents support write().writeScripts @ plugin.dev.js:119(anonymous function) @ plugin.dev.js:139(anonymous function) @ plugin.dev.js:140
(index):11 Uncaught ReferenceError: tinymce is not defined`

Can you refuse from write function?

**Comment by NTMan** [comment]
Hi, I know how to fix it!
But, you must answer for my question:
Why you make separate define and require function in each plugin?

My fix is:
```
1. replace load

	function load(path) {
		html.push(path);
		//html += '<script type="text/javascript" src="' + baseDir + '/' + path + '"></script>\n';
		moduleCount++;
	}

2. replace writeScripts

	function writeScripts() {
		html.forEach(function(src) {
			var script = document.createElement('script');
			script.src = baseDir + '/' +src;
			script.async = false;
			document.head.appendChild(script);
		});
		//document.write(html);
	}
```
document.write is evil and not allowed in XHTML.

Finally for forking needed place all modules in one scope, for this needed remark in all plugins. 
```
	//exports.define = define;
	//exports.require = require;
```
After this changes TinyMCE works fine.

I really don't know why you use separate scope of modules for each plugin.

**Comment by NTMan** [comment]
If into Google Chrome will be fixed script executing order 
https://bugs.chromium.org/p/chromium/issues/detail?id=594444

This change will be not needed:
//exports.define = define;
//exports.require = require;

TinyMCE will be works with plugins which have private scopes for modules.
You can stare this issue for help in fixing.

**Comment by fyrkant** [comment]
As it seems like you have found a way to fix it I'll close this.
