### ISSUE TITLE
Image Border Does not work & no color attribute selector for image border

### ISSUE THREAD

**Issue by ktroendle** [tinymce/tinymce#2754]
Edit Image -> Border   does nothing.  Similar to Table Edit border you have to go to Advanced -> Styles and manually add border-style: solid; or similar to get border.  In addition there is no color attribute selector for image border.

**Comment by spocke** [comment]
Just provide a css with img {border: 0 solid black} and it will then present a border.

**Comment by ktroendle** [comment]
I may be confused..

Doesn't this still require a user to manually edit the style attribute to
add a border?

Shouldn't a user be able to add a border using the without having to know
about html css styles?

Thanks, Kevin

**Comment by blackcathikari** [comment]
I believe this is similar to #1333. Could you have please have a look and let us know if not? Thanks,
Millie @ TinyMCE

**Comment by tinydylan** [comment]
I am unable to reproduce this issue, per the following steps:

1. Open [this page](https://www.tiny.cloud/docs/demo/full-featured/)
2. Right-click on the image, select "Image..."
3. The image dialog displays.
4. Click "Advanced".
5. Set border width to 1 and border style to solid.
6. Click "Save".
7. The image now has a border.

**Comment by ktroendle** [comment]
Still no option to add color to image border with UI controls?
