### ISSUE TITLE
ul select-all throw error on firefox

### ISSUE THREAD

**Issue by ramzes13** [tinymce/tinymce#2755]
Tinymce version 4.3.4
Hello, I discovered a small problem on Firefox 44,
when an unordered list is select all and click on bullist, I get error: 

IndexSizeError: Index or size is negative or greater than the allowed amount

unit test for that:

```js
(function() {
    module("tinymce.plugins.custom-list", {
        setupModule: function() {
            QUnit.stop();

            tinymce.init({
                menubar: false,
                toolbar: 'bullist',
                selector: 'textarea',
                init_instance_callback: function(ed) {
                    window.editor = ed;
                    QUnit.start();
                }
            });
        }
    });

    test("bug", function(assert) {
        editor.setContent('<ul><li>test1</li><li>test2</li><li>test3</li></ul>');

        editor.selection.setCursorLocation(editor.getBody().firstChild, 1);
        Utils.setSelection('ul', 2);
        editor.execCommand('SelectAll');

        editor.buttons['bullist'].onclick()

        assert.equal(editor.getContent({format: "raw"}), '<p>test1<br>test2<br>test3<br></p>');
    });
})();

```

**result firefox:**
tinymce.plugins.custom-list: bug (1, 0, 1)Rerun282 ms

    Died on test #1 vendor/tinymce/tests/bu/listes.test.js:18:5
    vendor/tinymce/tests/bu/listes.test.js:1:2
    : Index or size is negative or greater than the allowed amount
    Source: 	

    setRange vendor/tinymce/tests/js/utils.js:47:5
    setSelection vendor/tinymce/tests/js/utils.js:53:3
     vendor/tinymce/tests/bu/listes.test.js:22:9

**result chrome:**

Died on test #1     at vendor/tinymce/tests/tinymce/EditorCommands.js:50:1: Failed to execute 'createContextualFragment' on 'Range': The range's container is 'hr', which is not supported.
Source: 	
Error: Failed to execute 'createContextualFragment' on 'Range': The range's container is 'hr', which is not supported.
    at Error (native)
    at Object.Selection.setContent (vendor/tinymce/js/tinymce/classes/dom/Selection.js:186:27)
    at addCommands.mceInsertContent (vendor/tinymce/js/tinymce/classes/EditorCommands.js:677:16)
    at execCommand (vendor/tinymce/js/tinymce/classes/EditorCommands.js:68:5)
    at Object.Editor.execCommand (vendor/tinymce/js/tinymce/classes/Editor.js:1463:31)
    at Object.<anonymous> (vendor/tinymce/tests/tinymce/EditorCommands.js:59:9)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
