### ISSUE TITLE
Web Component/Custom Tag Support?

### ISSUE THREAD

**Issue by iam1me** [tinymce/tinymce#2757]
I'm evaluating TinyMCE for use in a project. So far I like it a lot, but I would like to be able to use custom tags/web components developed with Angular2 with it. In essence I want to be able to insert templated fields seamlessly into the editor, with the result being that when I retrieve the HTML it contains _my-template-field_ tags, potentially with attributes. 

I know I can always have the users put things like [FIELD: fieldname] or the like into the text editor and parse it later, but I'd prefer fully integration with the editor. 

Is this reasonable to achieve with TinyMCE? Perhaps with a custom plugin? Are there any examples out there for this kind of thing? I tried using the 'code' plugin and inserting it that way - but the custom tags are stripped out and replaced with p tags.

Thanks

**Comment by liamzebedee** [comment]
Hey mate, I managed to do something similar yesteday -- http://stackoverflow.com/questions/38733649/can-i-use-polymer-elements-webcomponents-with-tinymce

**Comment by ataraxus** [comment]
still no progress? i'm also stuck with this issue

**Comment by jbjhjm** [comment]
@ataraxus I think I found a solution.
My use case: Editor content contains inline web components created using @angular/elements.
The tag name of the web element is web-mailer-editor-snippet.
Note that this will only work using inline mode.

```ts
{
  // this tells tinyMCE not to strip this element and that it is a block element.
  // set the value to "~web-mailer-editor-snippet" to set it to display inline.
  custom_elements: 'web-mailer-editor-snippet'

  // the web component will now stay in dom, however if it relies on any attributes, it will look different or fail to render entirely.
  // It seems TinyMCE clones the element on initialization and will only set known attributes to the clone.

  // to make TinyMCE clone the element including all attributes, I added following.
  // note the "[*]" at the end. This is essential as it stops TinyMCE from stripping attributes.
  extended_valid_elements: 'web-mailer-editor-snippet[*]'
}
```

**Comment by lostkeys** [comment]
I've been researching this quite extensively and no, you probably won't get your react, vue or angular components to work inside TinyMCE. However, as @jbjhjm points out, TinyMCE has quite extensive capabilities to handle custom elements, but you need to think of them as placeholders. And using actual Web Components allows you to wrap pretty complex HMTL and CSS behind a single tag. 
What you can't do is add any advanced controls or input inside these web componets, such as a form, as TinyMCE will listen and intercept all key-presses so backspace/delete will remove the whole block instead of the thing you had inside it.

Here are two demos using web components.
* https://tinymce.github.io/tinymce-demos/cool-demos/conditional-blocks.html
* https://tinymce.github.io/tinymce-demos/tokens/web-component-token.html

Note that this is not officially supported, but keep postin issues here and we'll try to help.

**Comment by zjhr** [comment]
I take this issue very seriously and hope that the official will support it.

**Comment by zjhr** [comment]
I take this issue very seriously and hope that the official will support it.

**Comment by lostkeys** [comment]
Hi @zjhr! Since we do support web components to some degree, what is it that you seek to have TinyMCE support more specifically?

**Comment by zjhr** [comment]
Hello @lostkeys , I am currently building a project using the UI framework. I hope tinyMCE can use UI components in inline mode. Is it feasible?

**Comment by zjhr** [comment]
@lostkeys 

> Hello @lostkeys , I am currently building a project using the UI framework. I hope tinyMCE can use UI components in inline mode. Is it feasible?

I mean the project built by the vue/react UI framework.

**Comment by lostkeys** [comment]
@zjhr It totally depends on how the components are written. Is it a public UI framework, in that case I can give you more details of what would work and what is problematic.

**Comment by zjhr** [comment]
@lostkeys Yes, it is public. Are there examples? My project uses Ant Design. How can I use the button of Ant Design in the text box of TinyMCE, and ensure that the event and style of the button are complete?

**Comment by lostkeys** [comment]
@zjhr Alright, here are some guidelines.

TinyMCE is first and foremost an HTML editor. It reads HTML and outputs HTML. It also uses the DOM as it's model, meaning you actually edit the HTML, not some virtual document that is transformed into HTML at run-time. 

Finally, TinyMCE sees the run-time HTML, not the framework's abstraction that you use to author components and pages. This also means TinyMCE will output the rendered HTML, not the custom element you used with React, Vue or Angular. _There are simply no way around this in TinyMCE other than to find a UI library that actually uses real [web components](https://developer.mozilla.org/en-US/docs/Web/Web_Components)._

**What works fine** 

A single element component, like a button, is not different than any other tag, like `<code>` or `<strong>`. Using [extended_valid_elements](https://www.tiny.cloud/docs/configure/content-filtering/#extended_valid_elements) you fully control what attributes you support, and using something like the `styleselect` you can give your end users control over the attributes [as shown in this demo](https://tinymce.github.io/tinymce-demos/tinymce-basics/format-link-as-button.html)

**Where you might get into trouble**

When a component renders into a nested HTML structure, TinyMCE does not know what is what any more. An example would be [the alert component](https://ant.design/components/alert/). To give TinyMCE pointers to what is structural HTML and what is editable HTML you must use the [noneditable plugin](https://www.tiny.cloud/docs/plugins/opensource/noneditable/). It relies on classes so you need some way to add the necessary classes to your components before they are loaded into TinyMCE.

The second problem is TinyMCE returning the rendered HTML, not the component. This is where actual Web Components come in handy as they can hide away complex HTML behind a single custom element, so TinyMCE sees and treats the component as its a single  element component, and it will return the custom-element intact as well. 

**What flat-out won't work**

Anything that relies on keyboard input wont work. Any type of input simply just don't work properly inside TinyMCE. The solution is to treat these as noneditable placeholders. The [noneditable plugin](https://www.tiny.cloud/docs/plugins/opensource/noneditable/) is your friend here.

**Comment by zjhr** [comment]
@lostkeys Thank you very much for your help, I know how to achieve it! The UI component analysis must be mounted under the Web component, and this is the only way to achieve it.
