### ISSUE TITLE
Delete fails with raw encoding and "paste as text" and long text (vertical scrollbar is dislayed)

### ISSUE THREAD

**Issue by chrispcb** [tinymce/tinymce#2758]
This is a strange bug !

Config : entity_encoding : "raw"

Insert this code (from libreoffice):
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eleifend varius justo ut suscipit. Integer venenatis quis elit non hendrerit. Curabitur magna ex, euismod nec ultricies condimentum, pharetra ac risus. Aliquam pellentesque scelerisque leo et venenatis. Donec ut mauris quis diam tempor posuere. Cras porttitor leo nec eros aliquet eleifend. Vivamus sodales ac nulla in dictum. Praesent sit amet egestas sapien. Aenean feugiat congue risus, eget imperdiet TEXT 1.</p>
<p> </p>
<p><br />TEXT 2 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet gravida libero, commodo placerat eros. Aliquam viverra eget neque sit amet tempor. Praesent lacinia ut dui vitae mattis. Nulla facilisi. Vestibulum sed euismod neque. Sed ullamcorper posuere neque eu tempor</p>
```

Notice : there isn't **`&nbsp;`** between `<p> </p>` but a espace.
the bug is active if vertical scrollbar is allways dislayed after delete. TEXT 1 or TEXT 2 must to be a long text or reduce editor height.

1. In wysiwyg, place the carret at the end of "Text 1", delele to get "Text 1.Text2"
2. the carret is between **1** and **.**, so press enter, "text 2" is deleted

.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by chrispcb** [comment]
Yes this issue looks solved !
