### ISSUE TITLE
Inconsistent 'paste as text' behavior on Mac OS X ans Windows

### ISSUE THREAD

**Issue by PavelKocherov** [tinymce/tinymce#2759]
There is no ability to past html content without formatting in Mac OS X.

Steps to reproduce:
1) Open https://www.tinymce.com/.
2) Select "Full featured web editing." text and copy this.
3) Select 'past as text' option in tinyMCE.
4) Insert copied text to editor.
5) Verify that in Chrome on Windows text will be inserted without formatting, but in Chrome on Mac OS it will be inserted with formatting even if  'past as text' option was selected.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
