### ISSUE TITLE
Tiny MCE 4.3.6 fullscreen plugin not working fine in IE when used inside accordian.

### ISSUE THREAD

**Issue by mohdowais107** [tinymce/tinymce#2761]
Hi,

Tiny MCE 4.3.6 full screen plugin not working fine in IE when used inside accordian. However, It is working fine in Chrome and Firefox.

It is also working fine in IE when not used with accordian.

On clicking fullscreen icon, it is going to full screen but nothing is visible. once I hover on screen, the text inside textbox and Tiny MCE controls starting coming on screen on those places only where I have hovered.  

Extract of my code

For TinyMCE Init

 tinymce.init({

```
           selector: '.tinyClass3',
          plugins: "fullscreen, link",
           toolbar: "undo,redo,|,bold,italic,underline,|,alignleft, aligncenter, alignright, alignjustify,|,bullist,numlist,|,outdent,indent,|,formatselect,fontselect,fontsizeselect,|,removeformat,link,unlink,|,fullscreen",
          menubar: false,
          statusbar: false

         });
```

Accordian Code

```
     $(".multipleaccordion").accordion({
            collapsible: true,
            autoHeight: false,
            heightStyle: "content",
            navigation: true,
            active: false
        });
```

Aspx code

[aspx code.txt](https://github.com/tinymce/tinymce/files/156736/aspx.code.txt)

Please note that issue is due to combination of accordian and TinyMCE. Code is working fine with repeators(pls see attached file) if if am not writing accordian code but off course then accordian will not be implemented which is my requirement.
Also, same issue is coming if I use textarea inplace of textbox.

Any help is highly appreciated.
Screen shots of the issue are present in following links.

https://cloud.githubusercontent.com/assets/17615461/13494943/95778794-e16d-11e5-9604-5452c455fbfa.jpg
https://cloud.githubusercontent.com/assets/17615461/13494949/9bf73d26-e16d-11e5-84e9-5e5a08e76e59.jpg
https://cloud.githubusercontent.com/assets/17615461/13494953/a15011bc-e16d-11e5-8f96-d7e4c715f635.jpg

Thank you.

**Comment by mohdowais107** [comment]
please can anyone will try to help me on this. Don't know if it is a know bug or only I am facing this issue.

**Comment by tinydylan** [comment]
Hi,

Sincere apologies for the delay in responding. If you are still encountering this issue, are you able to produce a simple, self-contained example demonstrating the issue? Ideally, this would be client-side only code, e.g. as a codepen.io example.

Thanks.
