### ISSUE TITLE
Preview Plugin - width issue

### ISSUE THREAD

**Issue by pynews** [tinymce/tinymce#2765]
Hello,

If I set my textarea to have a width of 192, and then the plugin preview to the same value.
ie.
  max_width: 192,
  width: 192,
  plugin_preview_width: 192,

If I type a paragraph of text and then view it in preview, it does not show/wrap correctly. It seems the preview window will only go so narrow.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
