### ISSUE TITLE
edit area padding

### ISSUE THREAD

**Issue by pynews** [tinymce/tinymce#2766]
It appears the padding area by default has about 20px (guesstimate).

I have a CSS setup for example:

div.mce-edit-area{
    background:#FFF;
    filter:none;
    padding:0px;
}

The 0px value for padding appears to be the default padding for tinymce. How can I change this padding to be closer to the top/left side of the editor ?

thank you

**Comment by spocke** [comment]
You can use the content_css config option or if it's inline just the page css. I'm closing this one since this is more of a question than a bug or feature.
