### ISSUE TITLE
Selecting text and writing breaks word and makes extra invalid paragraph

### ISSUE THREAD

**Issue by pavel-j** [tinymce/tinymce#2767]
When you make following selection by mouse drag: from _ending_ of any paragraph in editor, to beginning of the document 
and try to write text (replace selection by writing), weird behavior follows:
1. after first character written, editor closes paragraph (which consists of single character) and thus breaks word you want to write after first character written. When you continue writing, it comes to another paragraph bellow.
2. at the same time, blank paragraph is created at the beginning of the document (before first character written). this paragraph is completely invisible in tinymce at that time - but it is there and it becomes visible when you use "view source code" and press OK (or when you submit the form). 

This creates unwanted and unexpected linefeeds, e.g. when you write new mail, send it and then see - it has unwanted paragraphs/vertical spaces in places you don't want (and which were hidden in time of editing). moreover, it breaks word after first character. both looks quite unprofessional to customer.

Problem is reproducible even in https://www.tinymce.com/docs/demo/basic-example/
Browser: Google Chrome latest version (tried on multiple computers)

**Comment by pavel-j** [comment]
Just update - problem occurs not only for selection at begining of the document, but quite often and in general (but not always), when you select some text and write.

example: editor at tinymce homepage (https://www.tinymce.com/)
- select both paragraphs of text and press "a"
another example: https://www.tinymce.com/docs/demo/basic-example/
- select heading "Found a bug?" together with text bellow, and press "a"

another info - when you type very fast (unnaturally - by multiple fingers at once), problem does not occur.

Please fix this, it is quite annoying. Thank you.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by pavel-j** [comment]
Hello, it is not corrected yet. 
It can be reproduced easily even at www.tinymce.com (editor at homepage), 
which is 4.4 already. Same problem in other demos, I just tried "basic demo".

Step 1 - make text selection by mouse drag: 
- start dragging at the right side of sentence "HTML elements to editor instances."
- drag to begin of document. 

Step 2 - type "a" ("a" three times in succession).

Result is:
a
aa

In source code:
<p>&nbsp;</p>
<p>a</p>
<p>aa</p>

So, there is paragraph broken after first letter written, and another blank paragraph in source code. This blank paragraph is also user invisible, which breaks WYSIWYG.

You can write "aaa" any speed, slow or fast, problem occurs everytime. 

I just tried - even when you press "a" just once, paragraph is broken immediately. 

It occurs **every time**. Google Chrome last version (non beta) on Windows 10. Same problem was in previous versions. Tried that on multiple computers.

If you need, I can record some video - but it should by easily reproducible using steps above, it happens everytime.

Thank you for your concern, it would be nice to fix this annoying bug - steps such are described before are quite usual,
I meet this bug every day (and so do our customers).

**Comment by pavel-j** [comment]
Hello, because source code example in message above was "cleaned", i try to post this with spaces inside tags (hopefully they will be preserved)
< p >&nbsp;< /p >
< p >a</ p >
< p >aa</ p >

**Comment by pavel-j** [comment]
Again - nbsp needed another space
< p >& nbsp;< /p >
< p >a< /p >
< p >aa< /p >

**Comment by dsakko** [comment]
Thanks for the extra info. The initial testing we did failed to reproduce the bug but your steps help to reproduce it. I'll reopen this one so we can look at fixing it in a future release.

**Comment by pavel-j** [comment]
Just comment - this bug is still appearing for 4.5.3 and www.tinymce.com demo.

Reproducing is totally easy (**much simplier reproducing, than above**).
Please do just this in Chrome/Windows:
- open www.tinymce.com, default demo
- select all three paragraphs of text there
- press "a" two times

This is supposed to create 
`<p>aa</p>`

Instead, this creates:

`<p style="text-align: center; color: #7e7e7e; font-size: 15px; font-family: avenir; font-weight: 200;">&nbsp;</p>
<p>a</p>
<p>a</p>`

You can see, that second "a" is in separate paragraph. 
Another part of this bug is empty paragraph with nbsp created (first line in example above). This paragraph is created unwantedly and it is also invisible (which breaks WYSIWYG - it is regular blank line, just invisible in tinymce).
It occurs everytime.

**Comment by pavel-j** [comment]
seems to be fixed in 4.6

**Comment by dsakko** [comment]
Thanks for checking it out and confirming the fix is working for you pavel-j.
