### ISSUE TITLE
Wrong row type in row properties

### ISSUE THREAD

**Issue by IProbablyFoundABug** [tinymce/tinymce#2768]
When we have a table and one of its rows has the row type "Header", in the row properties it will (always or mostly) show row type "None".

It can be reproduced in all major browsers i.e. here: [https://www.tinymce.com/docs/demo/full-featured/](url)

**Comment by tinydylan** [comment]
Hi,

I am unable to reproduce this issue in the latest TinyMCE. I suspect the issue has been corrected since you logged it.

Note that the URL you linked to has moved to https://www.tiny.cloud/docs/demo/full-featured/. 

If the issue persists, please let us know.
