### ISSUE TITLE
z-index issue with table panel and source code dialog

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2772]
In my tinymce 4.3.7 the table panel popup have a higher z-index than the source code dialog z-index.

See: https://picload.org/image/wpggcoc/zindexxt.png

Result: table panel is over source code dialog visible.

**Comment by spocke** [comment]
Can you provide step by step instructions on how to reproduce this. Thanks

**Comment by Daijobou** [comment]
I have search the reason and found out, thats problem comes with 

```
            external_plugins: {
			"codemirror": "path/plugins/codemirror-1.4/plugin.min.js"
    		},
```
https://github.com/christiaan/tinymce-codemirror

So I think the bug is not in tinymce.
