### ISSUE TITLE
Feature: Column support

### ISSUE THREAD

**Issue by egut** [tinymce/tinymce#2774]
It would be nice if you could add columns to the layout. Columns have been supported in css for a while now https://developer.mozilla.org/en-US/docs/Web/CSS/columns so it should be quite safe to use them.

Even cooler would be if they have built in responsiv support (maybe optional). Meaning that on a small screen its fewer or just one columns and on larger screens several columns.

**Comment by lostkeys** [comment]
Revisiting some old tickets. This is doable in TinyMCE using formats: http://fiddle.tinymce.com/aihaab/1. The responsive part is done using mediaqueries in the content css.
