### ISSUE TITLE
change link color

### ISSUE THREAD

**Issue by alfredopacino** [tinymce/tinymce#2778]
I'm not clear with the choice of keep the default text color for the anchors in editor, it could be very confusing for the average user.
How can I change that color?

Side question: I want to keep just the basic text style (list, links, bold, italic). Do you think I forgot something? ```valid_elements : "a[href|target=_blank],strong/b,div[align],br,li,ol,ul,i"```

**Comment by spocke** [comment]
This issue tracker is for bug reports or feature requests. Use the community.tinymce.com forum for community support.
