### ISSUE TITLE
Switch to using SVG instead of font icons

### ISSUE THREAD

**Issue by vangheem** [tinymce/tinymce#2782]
Font icons are blocked by some browser configurations, SVG is easy to implement and more widely compatible.

We've had to replace all TinyMCE icons in a project with SVG alternatives.

**Comment by dhknudsen** [comment]
@vangheem Could you perhaps elaborate a little on how you ended up replacing the icons with SVGs? We have a similar issue at my company that we need to address. I haven't quite gotten my head around yet, how to do accomplish this without sticking our hands too deep into the tinymce implementation (hopefully and preferably, we don't need to do that at all..)
Thank you in advance.

**Comment by vangheem** [comment]
We just used CSS to override the icons with svg versions.

**Comment by vangheem** [comment]
https://github.com/castlecms/castle.cms/blob/master/castle/cms/static/less/logged-in/icons.less#L472 is some of the code.

**Comment by tinydylan** [comment]
Thanks for the suggestion - I agree that SVG is a better option these days. TinyMCE icons are now SVG.
