### ISSUE TITLE
<p> being automatically selected on page load if CSS has padding

### ISSUE THREAD

**Issue by elitedesignsoftware** [tinymce/tinymce#2788]
When you've adding padding to p elements, the element is highlighted on the page load.  It shouldn't highlight this, it should be sitting at the first text position.
![tinymce p](https://cloud.githubusercontent.com/assets/17338225/13864216/6aa6d4e6-eceb-11e5-9e57-32d9194eb6e3.jpg)

**Comment by tinydylan** [comment]
Hi,

I am unable to reproduce this issue on the latest TinyMCE. I tested using [this test page](http://fiddle.tinymce.com/Nghaab) on several browsers. If the issue still occurs, please let us know.

The screenshot looks like an old version of TinyMCE, so you may need to update for the issue to be fixed.

Thanks!
