### ISSUE TITLE
Using fixed_toolbar_container , inline and emoticons. Popover position changes on scroll

### ISSUE THREAD

**Issue by aamirmukaram** [tinymce/tinymce#2791]
Issue screenshot: https://i.imgsafe.org/71d4037.png

Description:
Using inline mode ,fixed_toolbar_container with emoticon plugin.Popover of emoticon does not keeps its position while scrolling outside the popover.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
