### ISSUE TITLE
{FIXED BUG} Spellchecker_callback function returns error when i send an empty string

### ISSUE THREAD

**Issue by gtzinos** [tinymce/tinymce#2796]
You need to add this code : if(words != null) { ... }

Full fixed code : 
spellchecker_callback: function(method, text, success, failure) {
          var words = text.match(this.getWordCharPattern());
          if (method == "spellcheck") {
              var suggestions = {};
              if(words != null)
              {
                for (var i = 0; i < words.length; i++) {
                  suggestions[words[i]] = ["First", "Second"];
                }
              }
              success(suggestions);
          }
      }

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by gtzinos** [comment]
Ok thank you.
