### ISSUE TITLE
Inserting newlines at end of blocks in inline mode can clone ancestor elements of the TinyMCE editor

### ISSUE THREAD

**Issue by Shenlok** [tinymce/tinymce#2798]
[Codepen to repro](http://codepen.io/Shenlok/pen/RapMoO)
# Problem

When inserting newlines at the end of a block, some ancestor elements of the TinyMCE editor can be cloned and inserted into the editor's contents. This can be problematic if any ancestors have styles beyond simple text styling, e.g a margin or border.
# Setup

See the linked codepen for a working reproduction of this issue.

Key items to repro are:
- `keep_styles != false` and `inline === true` in the tinymce config
- The element on which you are initializing tinymce (the editor container) must be inside a "text inline element" as returned by `schema.getTextInlineElements()` ([source](https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/EnterKey.js#L204)) that has visual styling applied to it e.g border, margin.
# Explanation and possible solution

The problematic code is [this loop](https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/EnterKey.js#L216-L236), where the `onEnterKey` handler attempts to create a new block that maintains text styling from the previous block. It does this by traversing the parent nodes of the block the caret was in when the enter key was pressed, and if they are "text inline elements" (see above) it will clone them and append them to the "new" block where the caret will be positioned (the new line). In the loop, the only terminating condition is where there is no more parent node to look at. In non-inline mode, this means we have reached the root of the editable content area (the TinyMCE editor iframe). But in inline mode, this search will continue until reaching the document element since there is no iframe.

Perhaps a fix would be to add an additional check to this loop so that we don't traverse outside of the tinymce "editable area" boundary.

**Comment by gonguinguen** [comment]
Hi, sorry to bother here with this, but I think it's related.
I have a similar problem, but not using inline, just the classic editor.
I use <p> as root blocks. 
However, I have a custom button that adds a <div> with an <iframe> inside. I cannot put all that inside a <p> tag. The <div> with the <iframe> are inserted ok.

However, if I set the cursor at the end of the iframe (that is, inside the div), and press the Enter key, then the entire div is copied. Is that a bug?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by gonguinguen** [comment]
Hi @blackcathikari , I've just tested in the online demo of tinymce, and the problem is still there. I've attached a screen capture:
![captura](https://cloud.githubusercontent.com/assets/3819939/17180818/17f227bc-53f4-11e6-933a-4deb91aed69b.png)

Steps to reproduce the problem:

1. Change to source view and add a div as root block element, and add an iframe inside that div. Assign some random css class to the div. (the reason I put it inside a div is because I need the "embed-responsive" bootstrap class. It doesn't work with paragraphs. I need it to be a div, and to be in the root).
2. Change back to the editor view.
3. Set the cursor position at the right of the inserted div.
4. Press enter a few times.
5. Inspect the source code again. You'll see that with every enterkey a new div is created, with the css class attached.

Is that a bug? Or is it the expected behaviour?

**Comment by Shenlok** [comment]
Hi @blackcathikari,

Thanks for getting back to me, and for looking into this. It does seem as though with the latest version of TinyMCE, the bug no longer occurs upon pressing enter to insert a newline. However, if you open up the codepen example in my original comment, press enter a few times, then start pressing backspace, you will see the bug manifest again. It seems it was solved for one case but not for all.

I have updated the pen's repro instructions to reflect this.

Thanks for your time.

**Comment by blackcathikari** [comment]
Thanks for the additional information, @gonguinguen and @Shenlok. It helped a lot with replicating both bugs.

@Shenlok I was only able to reproduce your issue in IE, not Chrome or Firefox. Is it the same for you, or should I check another browser? If you could also check out the fiddle I made to test this and confirm whether or not the issue there is the same, that would be much appreciated. Link: http://fiddle.tinymce.com/q4faab/2. 

@gonguinguen I did replicate the behaviour you reported but I'm unsure myself if it's a bug or the expected behaviour. I'll check with the developers and get back to you on that.

**Comment by Shenlok** [comment]
@blackcathikari I'm able to reproduce the issue in my CodePen using Chrome 52.0.2743.82 (64-bit) on Mac OSX 10.10.4. I'm also able to reproduce it in your TinyMCE fiddle.

**Comment by Shenlok** [comment]
I'm also able to reproduce it in a Windows 8 VM running Chrome 51.0.2704.106 m and Chrome 52.0.2743.82 m.

**Comment by blackcathikari** [comment]
Thanks @Shenlock. This is definitely a bug, so I'll reopen this now. As a summary for our notes, the bug can be replicated on Windows 7/8 IE & Chrome and Mac OSX Chrome. 
- Millie @ TinyMCE

**Comment by blackcathikari** [comment]
@gonguinguen The behaviour you saw with the divs cloning themselves on enter is as expected, as usually you would want to retain your formatting when creating a new line. Unfortunately it results in slightly odd behaviour in your case, but hopefully it's not an inconvenience. 
- Millie @ TinyMCE

**Comment by coder-pm** [comment]
Issue reported by @gonguinguen is pretty serious. He was doing same thing as I did, wrapping iframe to make it responsive (http://getbootstrap.com/components/#responsive-embed). Wrapper is cloned and "padding-bottom: 56.25%;" is added to following elements.

**Comment by Shenlok** [comment]
Hi there @blackcathikari. Sorry to ping you directly like this, but I was hoping there might be some progress with this bug? It's causing quite a few headaches in our app, and I've not been successful in figuring out a hotfix to apply in the meantime.

**Comment by fr00x** [comment]
I have the same issue with templates where the template has multiple divs where within one enters content, e.g. text or images.

Any news from Ephox regarding this?

**Comment by blackcathikari** [comment]
@fr00x I'm afraid I can't figure out how to replicate that. Would you be able to set up an example on http://fiddle.tinymce.com please?

**Comment by fr00x** [comment]
http://fiddle.tinymce.com/RYfaab

- Ignore the missing bootstrap CSS
- Place your cursor within the column 1, eg at col|umn 1
- Hit enter
- Inspect code and see duplicated divs

**Comment by fr00x** [comment]
Thank you. That helps the case if I add empty paragraphs. 

But that can't be the indended behaviour as it renders complex templates unusable. What if I have only images within a div as my template?

**Comment by spocke** [comment]
The original bug about tinymce cloning elements out side of the editor body has been fixed as far I can I tell. If you want templates that doesn't clone the columns use noneditable feature it allows you to specify a class to the root of the template mceNonEditable then a class on the columns mceEditable and only those sections in the template will be editable.

If you still think this is a bug and not related to this bug file a new one. If it is still the exact same issue as the one in the original report then we can re-open this ticket. Thanks.
