### ISSUE TITLE
Word count is not updating when word is deleted

### ISSUE THREAD

**Issue by kaviyarasanpearson** [tinymce/tinymce#2801]
Hi,

We are using tinymce in our project and recently we migrated into tinymce 4.3.3 and faced the issue in wordcount. I came to know that there is an issue with tinymce demo as well.

Can you please take a look at it and give us a solution for this. Meanwhile we changed the wordcount plugin code to make it works.

**Word count is not updating when word is deleted
tinymce version: 4.3.3**

**Comment by fyrkant** [comment]
This has been fixed.
