### ISSUE TITLE
Drag&Drop image from desktop is broken in 4.3.6 - 4.3.8 on Ubuntu Firefox 45

### ISSUE THREAD

**Issue by PHPGangsta** [tinymce/tinymce#2802]
paste_data_images: true

Firefox 45 on Windows is working, Chrome on Ubuntu is working, Firefox 45 on Ubuntu is broken.

Drag&Drop an image from desktop into the editor is working in 4.2.6 and 4.3.4, but broken in 4.3.6 - 4.3.8

In the broken versions not the image itself is pasted, but the local URI  file:///xxxxx

JSFiddle for testing:
cdn.tinymce currently is using 4.3.8, it's broken:
https://jsfiddle.net/wq879xah/1/
Cachefly currently uses 4.3.3, it's working:
https://jsfiddle.net/k0bj7kdp/1/

**Comment by spocke** [comment]
Fixed this issue now.
