### ISSUE TITLE
Caret jumps to the end of previous line and blocks arrow keys navigation

### ISSUE THREAD

**Issue by Reaverart** [tinymce/tinymce#2804]
Observed in Firefox
If second line of paragraph starts from any inline tag, i.e. strong it blocks arrow key navigation. [**Here is fiddle**](https://jsfiddle.net/d2628nn2/6/)
Steps to reproduce:
1. Insert some text (it should be at least two lines length)
2. Make first word of second line bold or wrap it in any tag
3. Put cursor at the very beginning of first line
4. Press arrow down
Cursor will jump to the end of first line instead of begining of second line

**Comment by alexyuryev** [comment]
Also the bug blocks mouse navigation: in the same fiddle try to put a mouse cursor before the first letter of an inline tag on the second line: the cursor also jumps to the end of the first line. 
Does anybody know any workaround?

**Comment by tinydylan** [comment]
Hi,

I am unable to reproduce this issue - the cursor ends up in the correct place in the scenarios you described. It's likely that this is an issue that we've corrected since you've logged this report. If the issue persists, please let us know.

Thanks.
