### ISSUE TITLE
Images cannot be selected in Firefox

### ISSUE THREAD

**Issue by kaviyarasanpearson** [tinymce/tinymce#2805]
Hi,

We are using tinymce 3.5.6 in our project. I can not able to select the image after uploaded into tinymce in Firefox 45.

Is there any solution for this?

Regards,
Kavi

**Comment by spocke** [comment]
Can images be selected on the examples at the tinymce.com web site?

**Comment by kaviyarasanpearson** [comment]
Yes I can able to select images in tinymce website, But I don't have demo for 3.5.6 version.

**Comment by spocke** [comment]
Update to the latest 3.x version and see if that helps.

**Comment by kaviyarasanpearson** [comment]
Is there any possibility to fix the issue without upgrading to 3.x?

**Comment by siddhartha2083** [comment]
Hi **kaviyarasanpearson**, I had the same problem too and yesterday I made it resolved, so if you share your code, I can help you out.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
