### ISSUE TITLE
paste - how strip class and other attributes?

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2807]
In tinymce 3 you have a option "paste_strip_class_attributes". see http://archive.tinymce.com/wiki.php/Plugin3x:paste

In tinymce 4 this useful option is not available anymore? see https://www.tinymce.com/docs/plugins/paste/

I want copy a table from a html website, but without all his classes, ids and other data-tags. Is this possible?

a little workaround maybe for all other that use jquery:

```
			paste_preprocess: function(plugin, args)
			{
            	var elem = $('<div>' + args.content + '</div>');
            	elem.find('*').each(function()
				{
					var attributes = this.attributes, i = attributes.length;
				    while (i--)
					{
				    	this.removeAttributeNode(attributes[i]);
				    }
				});
                //elem.find('*').removeAttr('id').removeAttr('class');
                args.content = elem.html();
			},

```
When only need remove id and class, so use the comment-line instead for elem.find(*)-block.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by dsakko** [comment]
Given the option has been depreciated in 4.x your preprocessor is a good workaround. The option "paste_webkit_styles" will only give you control over the block and inline styles copied from other websites. Which tags are you currently trying to strip?

**Comment by mguinness** [comment]
FWIW, the original source for `paste_strip_class_attributes` is below.  I needed to strip all class attributes from the source, so I ended up just using the two replace functions within the [paste_preprocess](https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_preprocess) option.  Maybe there's a better way to do this.

```JS
// Class attribute options are: leave all as-is ("none"), remove all ("all"), or remove only those starting with mso ("mso").
// Note:-  paste_strip_class_attributes: "none", verify_css_classes: true is also a good variation.
stripClass = getParam(ed, "paste_strip_class_attributes");

if (stripClass !== "none") {
    function removeClasses(match, g1) {
        if (stripClass === "all")
            return '';

        var cls = grep(explode(g1.replace(/^(["'])(.*)\1$/, "$2"), " "),
            function (v) {
                return (/^(?!mso)/i.test(v));
            }
        );

        return cls.length ? ' class="' + cls.join(" ") + '"' : '';
    };

    h = h.replace(/ class="([^"]+)"/gi, removeClasses);
    h = h.replace(/ class=([\-\w]+)/gi, removeClasses);
}
```
