### ISSUE TITLE
Pasting from Word: List items starting with single word followed by a dot, will remove that word

### ISSUE THREAD

**Issue by Cordemans** [tinymce/tinymce#2810]
Hi,

List items starting with a single word followed by a dot are removed because they are mistakenly being seen as part of the list.
Best to describe it with an example.

**From Word:**
- foo. bar
- foo bar. baz

**Result in TinyMCE:**
- bar
- foo bar. baz

I traced it back to [WordFilter.js](https://github.com/tinymce/tinymce/blob/master/src/plugins/paste/src/main/js/core/WordFilter.js) on (currently) line 184:
`trimListStart(paragraphNode, /^\s*([\u2022\u00b7\u00a7\u25CF]|\w+\.)/);`

The `\w+\.` part of the Regex is the cause of this removal.
I can only assume that this is needed for ordered lists starting with alpha characters (a. b. c.)

It is reproducible with the following Word document containing a small and simple list:
[simplelist.docx](https://github.com/tinymce/tinymce/files/190469/simplelist.docx)

On pasting this content to tinymce, the "foo." part of the first list gets removed.
https://www.tinymce.com/docs/demo/basic-example/

Tested it with Word 2008 and 2011 (mac)
Latest TinyMCE (version 4.3.8)

Let me know if you need more info.

**Comment by aguasch** [comment]
The same behavior occurs, but not necessarily at the start of the list item, if the text is italicized. So

- Foo _Bar._

will paste as

- Foo

but only if the dot is included in the italicized portion of the text.

Word 2010 on Windows 7, TinyMCE 4.3.11 in Chrome 50.

**Comment by hegemanjr** [comment]
I would love to see this fixed!

**Comment by smares** [comment]
This bug is open for so long and still present in the latest version 5. We're using TinyMCE on a page for publishing press releases and this bug affects a lot of users.

**Comment by TheSpyder** [comment]
The open source paste plugin makes some effort to clean up word content but lists in particular are a mess of HTML and very very challenging to import correctly.

For professional-grade word import our investment went into a [premium PowerPaste plugin](https://apps.tiny.cloud/products/powerpaste/). It doesn't have this issue.
