### ISSUE TITLE
Checkboxes are not checkable or uncheckable in Firefox (until v45.0 at least)

### ISSUE THREAD

**Issue by rbecheras** [tinymce/tinymce#2817]
I'am developing a plugin to allow users to insert form elements: https://github.com/sirap-group/tinymce-plugin-forminputs

I started with checkboxes but there is an issue with Firefox, while it works fine with Chromium (or Google Crome).

Let insert the following HTML into a tinymce instance:

    <label>
        mybox
        <input type="checkbox"></input>
    </label>

Or 

        <input type="checkbox"></input>

The element will be correctly rendered. But in Firefox, it wont be checkable, nor uncheckable. In fact, it wont be clickabe neither. No one registred `click` event handler are triggered. However, `mouseover` event is correctly fired.

Do you know if is it a bug from tinymce or from firefox ?
Is this bug fixable for soon ?

I would want to fix it but I don't know where it come from so I ask your help.

Rémi.

**Comment by rbecheras** [comment]
I suspect the bug comes from Tinymce, not fro Firefox itself, because it tested to run the following HTML in firefox:

in `index.html`

    <iframe src="iframe.html" width="" height=""></iframe>

in `iframe.html`

    <h1>test iframe</h1>

    <input type="checkbox">

    <br>

    <label>
      mybox1
      <input type="checkbox" name="mybox">
    </label>

    <br>

    <label for="mybox2">
      mybox2
      <input type="checkbox" id="mybox2">
    </label>

And the result is that the checkboxes are checkable on click, without any problem. So I think that somewhere in tinymce, an event handler stop the click propagation.

**Comment by spocke** [comment]
Firefox blocks checkbox interaction in a contentEditable element.
<div contenteditable="true"><input type="checkbox"></div> so this won't work in FF. So you would have to either stick it in a contentEditable="false" or handle the check state manually with a click handler.

**Comment by rbecheras** [comment]
But click handlers

**Comment by spocke** [comment]
Yes, you are right it seems that FF doesn't fire events at all on input within contentEditable=true that is a browser bug we can't work around. So we need to report that to mozilla but you can wrap the inputs in contentEditable=false.

**Comment by rbecheras** [comment]
Thank you @spocke !
For now, I will force to wrap the input in my plugin. Thanks a lot!

**Comment by rbecheras** [comment]
I just reported the issue on Firefox bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1261296

> Please confirm the bug if you seen it too.

**Comment by spocke** [comment]
Awesome. Thanks. I was meaning to do that.

**Comment by rbecheras** [comment]
Hi @spocke , coud you confirm the bug on bugzilla plase ?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
