### ISSUE TITLE
Bug: Text cursor (blinking caret) disappears permanently after drag&drop operation into editor (Firefox)

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2823]
Using latest version from CDN (4.3.8), dragging and dropping anything into the editor results in text cursor (blinking caret) to permanently disappear. Selecting text works, but no blinking caret. Changing caret position by clicking works also, but the caret is invisible.

`editor.focus();` or `editor.getBody().focus();` don't help.

The only workaround is to manually click outside the editor and click again inside the editor. Please fix.

To reproduce, select and drag "A Pen By Captain Anonymous" at the top left corner, and drop into the editor. http://codepen.io/anon/pen/ONOVXN?editors=1010 (reproducable in Firefox)

**Comment by spocke** [comment]
Fixed in latest version.
