### ISSUE TITLE
<br data-mce-bogus="1">

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2826]
Hi.

I want use inline:true and found that not working correct with TEXTAREA
http://stackoverflow.com/questions/20008384/tinymce-how-do-i-prevent-br-data-mce-bogus-1-text-in-editor

so I use a DIV, but now I found out that after clear input its add a "&lt;br data-mce-bogus="1"&gt;" again.

click on "A" and press two times backspace and click on "show":
http://fiddle.tinymce.com/kufaab/1

Is this a bug?

Workaround for all that need a clean data for database, use before save a regex like
replace(/&lt;br[^&gt;]*&gt;$/gi, '');

**Comment by spocke** [comment]
No it's by design you need to padd elements to be able to place the caret.
