### ISSUE TITLE
Bug: all text disappear after table

### ISSUE THREAD

**Issue by hello-sorabh** [tinymce/tinymce#2828]
If I add a table and then I type anything below that table then all text disappeared automatically after sometime.I also tried and checked this issue on your website's Demo editor but Same thing is happening.

Step's to reproduce:
1. create "New Document"
2. create "table 2x2"
3. Resize table size (reduce table size)
4. Fill some text in table
5. Type some text below the table

Now all text will be disappear after the table automatically without doing anything.

**Comment by spocke** [comment]
Couldn't reproduce this one? Can it be reproduced on fiddle.tinymce.com?

**Comment by cristi1abaianit** [comment]
I have the same problem, insert a table, add some text inside it and add some text after the table on the next row, move the cursor and the text will disappear in 1,2 seconds. 
This wasn't a problem until the new context menu for tables was implemented.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
