### ISSUE TITLE
IE Issue With Text Selection Including Blank Lines

### ISSUE THREAD

**Issue by JasonGehl-D2L** [tinymce/tinymce#2829]
Only noticed in IE10 and IE11 (and partly in Edge), not noticed in Chrome or Firefox

Fiddle link: [http://fiddle.tinymce.com/mufaab/5](http://fiddle.tinymce.com/mufaab/5)

<h5>Issues:</h5>

<p><i>IE10,11,Edge - Selection from top to bottom</i><br/>
Performing keyboard selection (shift+arrow), starting at the beginning of the first line, press down to select each line in order until the entire editor is selected<br/>
<b>Expected:</b> All text in the editor is selected <br/>
<b>Actual:</b>The first line becomes selected, but no text from the second text line or either blank line are selected<br/>
</p>

<p><i>IE10,11 - Selection from bottom to top</i><br/>
Performing keyboard selection (shift+arrow), starting at the last line (which is blank), press up to select each line in order until the entire editor is selected<br/>
<b>Expected:</b> All text in the editor is selected <br/>
<b>Actual:</b> Each line is selected in order, but separately, and, at the end, only the first line is selected.<br/>
<b>Note:</b> If selection starts from the end of the second line with text, the selection works as expected, except that the last blank line is not included. Also not an issue in Edge.<br/>
</p>

**Comment by tinydylan** [comment]
Hi,

Thanks for the detailed bug report.

The fiddle you linked to uses TinyMCE 4.3.8 - I can reproduce the issue. 

If you change to the latest TinyMCE (5.2.2), the issue no longer occurs. It looks like this is something we've addressed somewhere between 4.3.8 and 5.2.2. I'd suggest updating.

If you have any further issues, please feel free to log them. Thanks again for you help.

Kind regards,

Dylan
