### ISSUE TITLE
The backspace key does not work properly when trying to remove nonEditable elements

### ISSUE THREAD

**Issue by ugamas** [tinymce/tinymce#2830]
[http://fiddle.tinymce.com/nufaab](http://fiddle.tinymce.com/nufaab)

**In Internet Explorer 11**

nonEditable elements are not completely eliminated, but are deleted character by character

**In Chrome**

the cursor is lost when trying to remove a nonEditable element with the backspace. This occurs when the cursor is in an empty line after the line that contains the item to delete.

**In Firefox**

the backspace doesn´t work well

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
