### ISSUE TITLE
Problem with loading of tinymce and webpack

### ISSUE THREAD

**Issue by mdudek** [tinymce/tinymce#2835]
I have already tried all related recommendations, but it does not work. Some plugins (table & paste) failed to load with errors:
- 'module definition dependecy not found: tinymce/util/Tools'
- 'module definition dependecy not found: tinymce/Env'

and theme.js fail with:
- 'cannot read property 'Factory' of undefined'

It seems that there are problems with dynamic loading of tinymce components using requirejs ...

Any tips how to resolve it?

**Comment by spocke** [comment]
We use a variant of amd so webpack wont work directly. We are currently thinking of ways to improve this but need to discuss that since it would be a dramatic shift on in how the project is structured.

**Comment by timelf123** [comment]
Hi @mdudek have you seen https://github.com/tinymce/tinymce/issues/2836

**Comment by IAMtheIAM** [comment]
+1 for easy webpack2 integration

**Comment by IAMtheIAM** [comment]
If it does not work with webpack, then this software will be left in the dust, as most front-end developers are using webpack, browserify, or other module bundlers for their applications. Asking us to put <script> tags in our document is **old school**. The new way is module bundlers.

I recommend you make your software compatible with modern web applications, unless you want to only target Wordpress developers and other ancient technology.

**Comment by timelf123** [comment]
I think what @IAMtheIAM is asking is:
- how can we maintain commonjs compat
- which plugins are broken
- who is responsible
- how can we help

**Comment by blackendstudios** [comment]
the editor should be wrapped with UMD and that's it, it'll be much easir ti work with, you already made the editor, so moving some files and let webpack do its job :)

**Comment by jayarjo** [comment]
Related thread here: https://github.com/tinymce/tinymce/issues/2836

**Comment by jayarjo** [comment]
Plugins are not broken, they are split for easier maintenance. And simply should be built (compiled) using bundled grunt tasks, before they can be wrapped and served via webpack or any other solution.

**Comment by jayarjo** [comment]
Closing this. We will post updates on this in https://github.com/tinymce/tinymce/issues/2836.
