### ISSUE TITLE
How to get TinyMCE to work with webpack and babel

### ISSUE THREAD

**Issue by hkjorgensen** [tinymce/tinymce#2836]
I have a couple of projects that uses TinyMCE and I think it's one of the better editors when HTML is the document model.

I wanted to use TinyMCE with a webpack setup so I tried: `npm i --save tinymce` and then `import tinymce from 'tinymce'` - but that didn't work.

After some time researching I got a solution to work. I just want to share it here if it can help others with the same issue. A couple of people have already asked for it.

This is not an issue but just a simple guide to get up and running :-)
## Requirements

A working webpack setup with Babel (es2015 presets)
## Dependencies

You need tinymce and a couple of loaders for webpack.

``` bash
npm i --save tinymce
npm i --save-dev imports-loader exports-loader
```
## Webpack config

Use `window` as `this` in the wrapping function generated by webpack

``` js
const config = {
  module: {
    loaders: [
      {
        test: require.resolve('tinymce/tinymce'),
        loaders: [
          'imports?this=>window',
          'exports?window.tinymce'
        ]
      },
      {
        test: /tinymce\/(themes|plugins)\//,
        loaders: [
          'imports?this=>window'
        ]
      }    
    ]
  }
}
```
## Implementation

Create a file in your source and add the following:

``` js
// Core - these two are required :-)
import tinymce from 'tinymce/tinymce'
import 'tinymce/themes/modern/theme'

// Plugins
import 'tinymce/plugins/paste/plugin'
import 'tinymce/plugins/link/plugin'
import 'tinymce/plugins/autoresize/plugin'

// Initialize
tinymce.init({
  selector: '#tinymce',
  skin: false,
  plugins: ['paste', 'link', 'autoresize']
})
```

I've added `skin: false` because I assume the project want to use it's own pipeline to provide the CSS as a bundle. TinyMCE won't work until the CSS is included(!)

**Comment by spocke** [comment]
We are going to look into improving webpack/browserify support. We really want people to be able to stitch together their own editor using the parts. Thanks for sharing these details.

**Comment by ahmedelgabri** [comment]
Thanks @hkjorgensen this works perfectly! :+1: 

@spocke this would be really great if we have proper support.

**Comment by artokun** [comment]
Ah, this works awesome! This is exactly what I needed

**Comment by AngeIII** [comment]
I'we got an error:
```
theme.js:14 Uncaught TypeError: Cannot read property 'Factory' of undefined
```
 that tinymce.ui is undefined. What can cause this?

**Comment by criticalbh** [comment]
this is not working

**Comment by fordream001** [comment]
Thanks for sharing!

**Comment by sassanh** [comment]
@hkjorgensen Thanks for sharing this, what about browserify?

**Comment by sassanh** [comment]
Some plugins like imagetools don't work and I guess they need other files to be imported in bundle. If I don't use these plugins everything works fine.

**Comment by sassanh** [comment]
For example imagetools needs "global!tinymce.dom.DOMUtils", but doing a `find . | grep -i dim` in its `node_modules/tinymce/` returns nothing.

**Comment by jboat** [comment]
Thanks a lot!

**Comment by samturrell** [comment]
Has anyone figured out how to set content_css using webpack?

**Comment by gesposito** [comment]
One possible solution is to use [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin#usage-example-with-css) so the CSS is actually bundled into a CSS file that you can import into 'content_css';

Only caveat I see is that you loose Hot Module Replacement.

**Comment by chrisjons** [comment]
Thanks @hkjorgensen for sharing!

Works great (though I'm skipping the babel-part, just using regular require()'s).


However I can't seem to get the paste-plugin to work for me. :cry: 
I keep getting this error: 
`Uncaught module definition dependecy not found: tinymce/util/Tools    plugin.js:19`

Commenting out the require of the paste-plugin gets core tinymce work like a charm, though.

**Comment by StevenIseki** [comment]
@chrisjons same issue with using any plugins and themes for me. Also not sure how you add in additional tinymce themes using npm. I have had to use tinymce as a global due to these issues.

**Comment by phdesign** [comment]
I found that the loader test didn't work on Windows, this regex seems to be more compatible.
```
{
    test: /tinymce[\\/](themes|plugins)[\\/]/,
    loader: 'imports?this=>window'
},
```

**Comment by victorpfm** [comment]
I'm getting these errors:

```
Uncaught module definition dependency not found tinymce/util/tools
Uncaught type error: Cannot read property Factory of undefined
```

Don't know more what to do, I think I'll give up and use the cdn.

**Comment by phdesign** [comment]
@victorpfm Make sure you are importing all the plugins, themes and skins you're using as well. I found it best to use the file loader to include the skin styles / fonts in the output folder so they were available for the stylesheet manager to import at runtime. I did this by using `require.context` to require everything in the skins folder, like this:

```
require.context('tinymce/skins', true, /.*/);
```
 
Then in my `webpack.config.js` I use file-loader for everything in the skins folder, e.g:

```
{
  test: /tinymce[\\/]skins[\\/]/,
  loader: 'file?name=[path][name].[ext]&context=node_modules/tinymce'
},
```

Unfortunately with this approach you have to exclude the tinymce/skins folder from every other loader. I'm sure there's a better approach if I dug deeper.

```
{
  test: /\.css$/,
  exclude: /tinymce[\\/]skins[\\/]/,
  loader: ExtractTextPlugin.extract("style-loader", "css-loader")
},
```

**Comment by fyrkant** [comment]
@phdesign If you only use the file loader for the tinymce/skins folder it might be easiest to skip the `webpack.config.js` settings and just put the settings in the require call, like so:
```js
require.context(
  'file?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/skins', 
  true, 
  /.*/
)
```

Then you shouldn't have to exclude the tinymce/skins folder from all the other loaders, right? 🤔

**Comment by IAMtheIAM** [comment]
Doesn't work with webpack and Angular2 as described here

**Comment by fyrkant** [comment]
@IAMtheIAM Does it work if you use `import 'tinymce/tinymce'` and then for the init use `window.tinymce.init({/* stuff */})`?

**Comment by ChrisBrittOSU** [comment]
@fyrkant Where do we put the:
```
require.context(
  'file?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/skins', 
  true, 
  /.*/
)
```
I have been trying to get tinymce to function with webpack, but none of the css is functioning. (It correctly finds the field, and initializes, but no css is showing / rendering. (It just makes a blank space.)

**Comment by jarrettj** [comment]
@hkjorgensen Thanks for the post. But if I import tinymce from the tinymce folder it does not work.

`import tinymce from '../../node_modules/tinymce'`

It says it can't find module. Adjusted your example to point at my node_modules folder.

**Comment by fyrkant** [comment]
To show how to put the tips in this thread together I made a simple lite example app [here](https://github.com/fyrkant/simple-tinymce-webpack).

**Comment by Darkside73** [comment]
@fyrkant Thanks for the great workaround with ```require.context```.
But there is a small notice to get things work: you should overwrite any loaders by putting ```!``` at the beginning:
```javascript
require.context(
  '!file?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/skins', 
  true, 
  /.*/
)
```
In this case webpack emit the actual content of CSS files instead of JS wrapping

**Comment by hkjorgensen** [comment]
@jarrettj you shouldn't required npm packages with a relative path, you should use the `import tinymce from 'tinymce/tinymce'`. Webpack will resolve that internally to `PROJECT_DIR/node_modules/tinymce/tinymce.js`. I hope that helps.

**Comment by dmi3y** [comment]
Have issue with skin styles bleed over to global style scope (body). 
Basically the skin being imported into javascript like so:

```js
import 'tinymce/skins/lightgray/skin.min.css'
import 'tinymce/skins/lightgray/content.min.css'
```

With following webpack config related part:

```js
    ...
    {
      test: /\.css$/,
      loader: 'style-loader!css-loader'
    },
    ...
```

And as a result the lightgray skin applied its styles globally when it suppose to be only tinymce sandboxed iframe. What the less cumbersome way to address this issue? 

I might missing something obvious and doing it wrong way though...

**Comment by ollycross** [comment]
If anyone is having problems with the Paste plugin and browserify I have fixed it in my current dev build by nicking some code from the media plugin to simulate global dependencies.

I've duplicated the `/plugins/paste/Plugin.js` file into `myapp/js/utils/tinymce-paste.js` so it won't get overwritten by npm updates and then added the following near the top of the file.

    // Plugin.js
    // Line 12
    var defineGlobal = function (id, ref) {
      define(id, [], function () { return ref; });
    };

    defineGlobal("tinymce/util/Tools",TinyMCE.util.Tools);
    defineGlobal("tinymce/html/DomParser",TinyMCE.html.DomParser);
    defineGlobal("tinymce/html/Schema",TinyMCE.html.Schema);

    defineGlobal("tinymce/Env", TinyMCE.Env);
    defineGlobal("tinymce/dom/RangeUtils", TinyMCE.dom.RangeUtils);
    defineGlobal("tinymce/util/VK", TinyMCE.util.VK);
    defineGlobal("tinymce/util/Delay", TinyMCE.util.Delay);
    defineGlobal("tinymce/util/Tools", TinyMCE.util.Tools);
    defineGlobal("tinymce/html/DomParser", TinyMCE.html.DomParser);
    defineGlobal("tinymce/html/Schema", TinyMCE.html.Schema);
    defineGlobal("tinymce/html/Serializer", TinyMCE.html.Serializer);
    defineGlobal("tinymce/html/Node", TinyMCE.html.Node);
    defineGlobal("tinymce/PluginManager", TinyMCE.PluginManager);



   // app.js
   // ...
    global.TinyMCE = require(tinymce);
    var require("utils/tinymce-paste");

Obviously this is not ideal but for the moment it allows me to load the paste plugin via Browserify without errors until the wider plugin compatability are resolved.

Presumably the same method could be used to crowbar the tables plugin into Browserify as well.

Hope this helps someone (@sassanh)?

**Comment by fyrkant** [comment]
@ollycross What version of TinyMCE are you using? Just writing `import 'tinymce/plugins/paste';` whould work with the latest version 4.5.1.

**Comment by TNovalis** [comment]
Note if you are using Elixir and use Elixir's official webpack plugin you need to change `test:` to an array.

``` js
const config = {
    module: {
        loaders: [
            {
                test: [
                    require.resolve('tinymce/tinymce'),
                ],
                loaders: [
                    'imports?this=>window',
                    'exports?window.tinymce'
                ]
            },
            {
                test: [
                    /tinymce\/(themes|plugins)\//,
                ],
                loaders: [
                    'imports?this=>window'
                ]
            }
        ]
    }
};
```

**Comment by bjohnson-va** [comment]
I'm also having trouble with getting this working but I don't want to hijack the current thread.
Please see my issue: https://github.com/tinymce/tinymce/issues/3396

**Comment by doberkofler** [comment]
@spocke I read your post on better integration with webpack/browserify and was wondering if there is any update or road map on when this might land?

**Comment by jayarjo** [comment]
@doberkofler actually as far as I know it has landed and @bjohnson-va was able to load it in #3396. COuld you guys please confirm that it works as expected? Suggestions are welcome.

**Comment by aj-anuragjain** [comment]
webpack 2 loaders for tinyMCE 

```
             {
                test: require.resolve('tinymce/tinymce'),
                use: [
                    'imports-loader?this=>window',
                    'exports-loader?window.tinymce',
                ]
            },
            {
                test: /tinymce\/(themes|plugins)\//,
                use: [
                    'imports-loader?this=>window'
                ]
            },
```

Just replace imports with imports-loader & exports with exports-loader

**Comment by fyrkant** [comment]
You shouldn't have to use the imports-/exports-loaders with the latest version of tinymce, is it not working without them for you @aj-anuragjain ?

**Comment by aj-anuragjain** [comment]
@fyrkant you're right it works now with v4.5.1

**Comment by blackendstudios** [comment]
well, it worked for met too, amazing contribution but I've only one problem and is not loading the fonts from the skins folder, even the folder has been copied with all if its assets it the editor can't find the font that it needs for the buttons, it throws the following:

`Failed to decode downloaded font: http://localhost:8080/skins/lightgray/fonts/tinymce.woff
OTS parsing error: invalid version tag
`
`Failed to decode downloaded font: http://localhost:8080/skins/lightgray/fonts/tinymce.ttf
OTS parsing error: invalid version tag`

![screen shot 2017-02-24 at 9 58 26 pm](https://cloud.githubusercontent.com/assets/4050205/23316718/a2de6aae-fadc-11e6-8d6a-3af577520adc.png)

![screen shot 2017-02-24 at 9 58 44 pm](https://cloud.githubusercontent.com/assets/4050205/23316721/a7fab9ac-fadc-11e6-8cd4-7330695d3d10.png)

and by checking the Resources panel, everything is in there, can anybody tell me or knows if there's some extra workaround to let this work properly?

**Comment by jamelt** [comment]
@blackendstudios I'm having the same issue. My font loader can't find these files. It's so frustrating.

**Comment by ahmedelgabri** [comment]
The latest version only fixes the issue with resolving the plugin when you `import`/`require` it, but doesn't handle resolving the assets. If you are using Webpack you still need to do this https://github.com/tinymce/tinymce/issues/2836#issuecomment-257343190

**Comment by fyrkant** [comment]
Yeah like it says in [the documentation](https://www.tinymce.com/docs/advanced/usage-with-module-loaders/#gettingtheskin) you have to load the skin, but you can choose how you want to do that. Either by just copying the files to where you want them, by using the file-loader or by some more complicated loader combo like @jamelt showed above.

**Comment by fyrkant** [comment]
I'm going to close this issue as I think that we have fixed a lot of the problems with using tinymce with webpack and also added the [documentation](https://www.tinymce.com/docs/advanced/usage-with-module-loaders/).

**Comment by foodaka** [comment]
is there a way to import all plugins in one line from tinymce ?

**Comment by fyrkant** [comment]
@foodaka No there is no way to import all plugins, and it really isn't something I would recommend doing either. Just importing the plugins you need will keep your bundle as small as possible.

**Comment by goartur** [comment]
Is there a solution to it right now? I do not get any errors, but still my component do not render it correctly. I don't see the element with the eye, it's invisible and in the element inspector all the classes are added...

**Comment by davegahn** [comment]
I decided to copy tinyMCE .css and font files into a folder with static files and fonts of my project. Then attached them to scss bundle.  It's not good but anyway it works...

**Comment by davegahn** [comment]
One possible solution was to use `content_css;` settings. So why does tinyMCE still looking for skin directory? 
![image](https://user-images.githubusercontent.com/16261282/28227195-8b39196c-68e1-11e7-8c25-4c154a7e1473.png)

**Comment by guangmiw8** [comment]
I used the approach listed in tinymce document: https://www.tinymce.com/docs/advanced/usage-with-module-loaders/#gettingtheskin. It works but the consumer of my bundle has to specify the url to the skin folder via the config because tinymce skin manager looks for skins folder under root and in my single page application the root is not where the output js bundle and skins folder are.

Would it be possible to bundle all resources file along with the js files into a single file? It seems unrealistic because the skin manager of tinymce dynamically loads skin files. I am asking in case I missed anything.

**Comment by lakesare** [comment]
This comment worked for me perfectly well, with webpack 2: https://github.com/tinymce/tinymce/issues/2836#issuecomment-256623192. Together with skins and everything.
It links to this example: https://github.com/fyrkant/simple-tinymce-webpack.

**Comment by guangmiw8** [comment]
@lakesare thanks! that's how I am doing it now, but it's not bundling the css inline with the js files. What I wanted is a single js file that contains everything.

**Comment by ssilve1989** [comment]
Does anyone have an example of how to use `content_css` with webpack to get CSS working on the tinyMCE iframe?

**Comment by VersaceAndy** [comment]
@aneurysmjs  Is this problem solved?

**Comment by VersaceAndy** [comment]
good job

**Comment by kopax** [comment]
Did anyone solved this for webpack > 3.5.5 ?

**Comment by szityi** [comment]
Has someone fixed the issue reported by @ssilve1989 in [this](https://github.com/tinymce/tinymce/issues/2836#issuecomment-323825947) comment?

**Comment by wcrisman** [comment]
This post was a huge help.  I just spend hours trying to figure out why Tinymce was almost working, but not quite.  Adding the imports for all the plugins was what I was missing.

**Comment by Fasani** [comment]
I just wanted to add my solution for a custom skin here because I couldn't find a simple explanation and this is working for me plus our webpack setup is a little complex.

We made a custom skin using http://skin.tiny.cloud/

Then I manually copy the whole folder to a different location, we also use different relative paths so I ended up doing something like this:

webpack.config.js additions:
```
let CopyWebpackPlugin = require('copy-webpack-plugin');

let plugins = [
    // Used to copy TinyMCE custom skin
    new CopyWebpackPlugin([{
        from: path.join(root, 'tiny-mce-squirro-skin'),
        to: 'tiny-mce-squirro-skin',
    }]),
];
```

Then the Tiny MCE part:
```
const skinUrl = DEVELOPMENT ?
    'static/js/require/tiny-mce-squirro-skin' :
    'static/min/js/require/tiny-mce-squirro-skin';

TinyMCE.init({
    // Options Here
    skin_url: skinUrl,
});
```

Hope that helps some people who are also stick on this.

**Comment by ryanerato** [comment]
For those looking to bundle the skin and/or content CSS, this can be achieved with a combo of `css-loader` and `style-loader`. Due to limitations in the asset pipeline, I needed to output just a single bundle.

webpack.config.js
```javascript
rules: [
  {
    test: /\.css$/,
    use: ['css-loader']
  },
  {
    test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
    loader: 'url-loader'
  }
]
```

```javascript
import tinymce from "tinymce/tinymce";

import "style-loader!tinymce/skins/lightgray/skin.min.css";
import contentStyle from "tinymce/skins/lightgray/content.min.css";

tinymce.init({
  skin: false,
  content_style: contentStyle.toString()
});
```

**Comment by rasco** [comment]
thanks @ryanerato 
https://github.com/tinymce/tinymce/issues/2836#issuecomment-433991854 this worked for me!

**Comment by szityi** [comment]
@ryanerato, I just tried your approach, and it's still not working for me. I'm using TinyMCE5, and Symfony's WebpackEncore bundler system. Below are the affected lines of my config:

webpack.config.js
```
    .addLoader({
        test: require.resolve('tinymce/tinymce'),
        loaders: [
            'imports-loader?this=>window',
            'exports-loader?window.tinymce'
        ]
    })
    .addLoader({
        test: /tinymce[\\/]themes[\\/]/,
        loader: 'imports-loader?this=>window'
    })
    .addLoader({
        test: /tinymce[\\/]plugins[\\/].*\.js$/,
        loader: 'babel-loader'
    })
```
my separate js module responsible for returning default configs:
```
import 'tinymce';
import 'tinymce/themes/silver';

import 'tinymce/plugins/advlist';
import 'tinymce/plugins/autolink';
import 'tinymce/plugins/link';
import 'tinymce/plugins/image';
import 'tinymce/plugins/lists';
import 'tinymce/plugins/charmap';
import 'tinymce/plugins/print';
import 'tinymce/plugins/preview';
import 'tinymce/plugins/hr';
import 'tinymce/plugins/anchor';
import 'tinymce/plugins/pagebreak';
import 'tinymce/plugins/spellchecker';
import 'tinymce/plugins/searchreplace';
import 'tinymce/plugins/wordcount';
import 'tinymce/plugins/visualblocks';
import 'tinymce/plugins/visualchars';
import 'tinymce/plugins/code';
import 'tinymce/plugins/fullscreen';
import 'tinymce/plugins/insertdatetime';
import 'tinymce/plugins/media';
import 'tinymce/plugins/nonbreaking';
import 'tinymce/plugins/save';
import 'tinymce/plugins/table';
import 'tinymce/plugins/directionality';
import 'tinymce/plugins/emoticons';
import 'tinymce/plugins/template';
import 'tinymce/plugins/paste';
import 'tinymce/plugins/importcss';

import '!style-loader!css-loader!tinymce/skins/ui/oxide/skin.min.css';
import contentStyle from 'tinymce/skins/ui/oxide/content.min.css';

        exports.TinyMce.getDefaultTinyMceConfig = function (base_path, file_browser_url) {
            return {
                selector: 'textarea.tinymce',
                width: 'auto',
                height: '300',
                theme: 'silver',
                skin: false,
                // content_style: false,
                content_style: contentStyle.toString(),
            ...
            };
        };
```
And I'm getting the following errors in browser's console:
![image](https://user-images.githubusercontent.com/19792700/53086111-be475d00-3504-11e9-9a06-7e3deb0dec0c.png)

However it seems like TinyMCE gets initialized properly but the errors annoys me anyway. Thanks in advance!

**Comment by zhangsanshi** [comment]
It works with TinyMCE5 and webpack4.


```javascript
// Import TinyMCE
import 'tinymce/tinymce';

// A theme is also required
import 'tinymce/themes/silver';
import 'tinymce/skins/ui/oxide/skin.css';

// Any plugins you want to use has to be imported
import 'tinymce/plugins/advlist';
import 'tinymce/plugins/autolink';
import 'tinymce/plugins/lists';
import 'tinymce/plugins/link';
import 'tinymce/plugins/image';
import 'tinymce/plugins/charmap';
import 'tinymce/plugins/print';
import 'tinymce/plugins/preview';
import 'tinymce/plugins/anchor';
import 'tinymce/plugins/searchreplace';
import 'tinymce/plugins/visualblocks';
import 'tinymce/plugins/code';
import 'tinymce/plugins/fullscreen';
import 'tinymce/plugins/insertdatetime';
import 'tinymce/plugins/media';
import 'tinymce/plugins/table';
import 'tinymce/plugins/paste';
import 'tinymce/plugins/help';
import 'tinymce/plugins/wordcount';
import contentStyle from '!!raw-loader!tinymce/skins/ui/oxide/content.css';
import contentStyle2 from '!!raw-loader!tinymce/skins/content/default/content.css';
import Editor from '@tinymce/tinymce-vue';
export default {
    extends: Editor,
    props: {
        init: {
            type: Object,
            default() {
                return {
                    skin: false,
                    content_css: false,
                    content_style: contentStyle.toString() + '\n' + contentStyle2.toString(),
                };
            },
        },
    },
};
```

**Comment by KirillLogin** [comment]
Unfortunately, none of the described solutions were suitable out-of-the-box for my context.
I use TinyMce 4.9.7 with AngularJS via the **angular-ui-tinymce** directive.

I need a modern theme and 3 plugins: 'codesample', 'link', 'code'. So I have added this to my main index.ts:
```
import 'tinymce/tinymce'
import 'tinymce/themes/modern'
import 'tinymce/plugins/codesample'
import 'tinymce/plugins/link'
import 'tinymce/plugins/code'
```

Then I have faced the '404'-problem with the styles. So I have added this to my main index.ts
```
import "style-loader!tinymce/skins/lightgray/skin.min.css";
import "style-loader!tinymce/skins/lightgray/content.min.css";
```
and this to my TinyMce options:
```
tinyMceOptions: {
  skin: false,
  ...
}
```

And then one more problem with the **codesample** plugin because of this in it's code:
```
if (contentCss !== false) {
        linkElm = editor.dom.create('link', {
          rel: 'stylesheet',
          href: contentCss ? contentCss : pluginUrl + '/css/prism.css'
        });
        editor.getDoc().getElementsByTagName('head')[0].appendChild(linkElm);
      }
```
Result href value will be an absolute path and it will know nothing about the webpack bundle. So I didn’t come up with anything better than copying the required file **prism.css** right into my webpack **dist/** folder.
So finally i have added this to my main index.ts:
```
require.context(
    'file-loader?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/plugins/codesample/css',
    true,
    /.*/
);
```

And my Webpack 4 rules by the way:
```
{
   test: /\.css$/i,
  use: ['style-loader', 'css-loader'],
},
{
  test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
  loader: 'url-loader'
}
```

**Comment by munitioner** [comment]
Thanks for your answer
my codesandbox project https://codesandbox.io/s/async-surf-srhqk?file=/src/App.vue

**Comment by Townsheriff** [comment]
Got me working with react:

```
// Import TinyMCE
import "tinymce/tinymce";

import "tinymce/icons/default";

// A theme is also required
import "tinymce/themes/silver";
import "tinymce/skins/ui/oxide/skin.css";

// Any plugins you want to use has to be imported
import "tinymce/plugins/advlist";
import "tinymce/plugins/autolink";
import "tinymce/plugins/lists";
import "tinymce/plugins/link";
import "tinymce/plugins/image";
import "tinymce/plugins/charmap";
import "tinymce/plugins/print";
import "tinymce/plugins/preview";
import "tinymce/plugins/anchor";
import "tinymce/plugins/searchreplace";
import "tinymce/plugins/visualblocks";
import "tinymce/plugins/code";
import "tinymce/plugins/fullscreen";
import "tinymce/plugins/insertdatetime";
import "tinymce/plugins/media";
import "tinymce/plugins/table";
import "tinymce/plugins/paste";
import "tinymce/plugins/help";
import "tinymce/plugins/wordcount";
export { Editor } from "@tinymce/tinymce-react";

const getGlobal = (): any => (typeof window !== "undefined" ? window : global);

export const getTinyMCE = (): any | null => {
  const global = getGlobal();

  return global && global.tinymce ? global.tinymce : null;
};

```

**Comment by yanqing6628780** [comment]
Hi [zhangsanshi](https://github.com/zhangsanshi), Can you share the webpack.config.js about TinyMCE?
It does not work for me.
> ```js
> import 'tinymce/tinymce';
> ```

I fellow the TinyMCE's document, here is my config:
```js
module:
  rules: [
     {
        test: /skin\.css$/i,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader'],
      },
      {
        test: /content\.css$/i,
        use: ['css-loader'],
      },
  ]
....
optimization: {
    splitChunks: {
      chunks: 'all',
      minSize: 30000,
      minChunks: 1,
      maxAsyncRequests: 6,
      maxInitialRequests: 3,
      enforceSizeThreshold: 50000,
      cacheGroups: {
        defaultVendors: {
          name: 'vendors',
          test: /[\\/]node_modules[\\/]/,
          priority: -10,
          reuseExistingChunk: true,
          chunks: 'all',
        },
        default: {
          minChunks: 2,
          priority: -20,
          reuseExistingChunk: true,
        },
        tinymceVendor: {
          chunks: 'all',
          test: /[\\/]node_modules[\\/](tinymce)[\\/](.*js|.*skin.css)|[\\/]plugins[\\/]/,
          name: 'tinymce',
          priority: 20,
        },
        vue: {
          name: 'vue',
          test: /vue/,
          priority: 10,
          chunks: 'all'
        }
      },
    }
  },
```
