### ISSUE TITLE
Callback when removing inline images

### ISSUE THREAD

**Issue by alvarotrigo** [tinymce/tinymce#2839]
I am currently uploading images on my server when a user adds an inline image.

I believe having a callback to know which element has been removed would be ideal for this cases so I can remove the image from my server if the user decides to remove it.

[Similar questions](http://stackoverflow.com/questions/23606559/tinymce-get-image-details-on-deletion) have been raised on stackoverflow but it seems there's no proper way of this this.

**Comment by spocke** [comment]
It's some what tricky to monitor when images gets removed since there are a bunch of ways they can be removed using backspace/delete/type over/paste/cut etc. It's better to just check what src attributes you have on save match that with the uploaded files and delete anyone not in that set.

**Comment by spocke** [comment]
I think this is more of a forum topic than a bug/feature request since it can be handled externally from tinymce.

**Comment by sovetski** [comment]
8 years later, we have exactly the same problems :/

**Comment by TheSpyder** [comment]
And we still can't solve it in TinyMCE. If we emit an event when an image is deleted, should we emit another event if the user restores it with undo? How many edge cases will that leave us with?

It's just better to compare the list of images on save, that way you are totally in control of deleted image references. But do keep in mind, if your backend supports loading older versions an image can never truly be deleted (much like the undo scenario on the frontend).
