### ISSUE TITLE
Background Attribute Stripped from TD Elements

### ISSUE THREAD

**Issue by jtark** [tinymce/tinymce#2840]
When setting HTML through the Source Code dialog or through a call to `editor.setContent`, the `background` attribute is stripped out of `<td>` elements (tested with version 4.3.8).

For example,
```html
<table>
	<tbody>
		<tr>
			<td width="1200" height="630" align="center" background="http://assets-cdn.github.com/images/modules/open_graph/github-mark.png">
				<!--[if gte mso 9]>
					<v:rect xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false" style="width:1200px;height:630;">
					<v:fill type="tile" src="http://assets-cdn.github.com/images/modules/open_graph/github-mark.png" color="#eaf8f8" />
					</v:rect>
				<![endif]-->
			</td>
		</tr>
	</tbody>
</table>
```

becomes
```html
<table>
	<tbody>
		<tr>
			<td align="center" width="1200" height="630">
				<!-- [if gte mso 9]>
					<v:rect xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false" style="width:1200px;height:630;">
					<v:fill type="tile" src="http://assets-cdn.github.com/images/modules/open_graph/github-mark.png" color="#eaf8f8" />
					</v:rect>
				<![endif]-->
			</td>
		</tr>
	</tbody>
</table>
```

While the `background` attribute is not standard, it is necessary for displaying a background image in the browser-based version of Outlook. Neither the `background-image` CSS rule nor the VML provided here will cause it to display (though the VML is necessary for other clients, including the Outlook 2013 desktop client).

**Comment by spocke** [comment]
You can allow custom attributes using extended_valid_elements by default we only support proper HTML5 syntax.

**Comment by jtark** [comment]
Perfect! I must have missed that setting. Thanks!
