### ISSUE TITLE
tinymce

### ISSUE THREAD

**Issue by AyeletGol** [tinymce/tinymce#2841]
I am using tinymce and I added new custom listbox button:
editor.addButton('SelectField', {
                type: 'listbox',
                text: 'Select Field  ...  ',
                icon: false,
                onselect: function (e) {                
                    tinymce.get("content").execCommand('mceInsertContent', false, this.value());
                    this.text('Select Field  ...  ');
                },
                values: ListBoxValues,
                onPostRender: function () {
                }
            });
Some of the values included string ofr example: {{xxxxx Original Currency}} - on execute the mceInsertContent for these items inserts:
{{xxxxx Orig</span>inal Currency}}
As I found it happened when I insert item length 30+  from the 30 the tinymce adds </span> with class of mceNonEditable (from the span).

**Comment by AyeletGol** [comment]
**mceInsertContent for these items inserts:
`{{xxxxx Orig<span>inal Currency}}`

**Comment by spocke** [comment]
Seems like a forum topic rather than a bug/feature request. Closing.
