### ISSUE TITLE
Content in blank editor prefilled from editor on previous screen

### ISSUE THREAD

**Issue by Iteracy** [tinymce/tinymce#2843]
After entering text into a TinyMCE v4.0.11 editor then submitting the form, when a new screen is displayed with a blank editor the text from the previous editor is displayed.

This behaviour happens in Chrome Version 49.0.2623.112, Firefox 44.02 and IE v11

Code to instantiate TinyMCE is:
```
<script language="javascript" type="text/javascript" src="../jscript/tinymce/tinymce.min.js?r=<?=$rand?>"></script>
<script language="javascript" type="text/javascript">
	tinymce.init({
		editor_deselector: "not_rich",
	    mode: "textareas",
		editor_selector: "rich",
	    width: 750,
	    height: 300,
	    plugins: [
	         "autolink autosave charmap code contextmenu fullscreen hr image link lists media moxiemanager nonbreaking paste searchreplace spellchecker table anchor textcolor"
	   ],
		link_list: "link_list.php", 	 
		document_base_url : "' . $db->document_base_url . '",
		relative_urls : false, 
		menubar: "insert edit format view tools table",
		statusbar : false, 
		contextmenu: "link image file inserttable | cell row column deletetable",
	   content_css: "css/content.css",	   
		browser_spellcheck : true,
	   toolbar: "undo redo | styleselect | bold italic underline forecolor | alignleft aligncenter alignright | bullist numlist outdent indent | l link anchor | image file media", 
	   style_formats: [
	        {title: "Heading 1", block: "h1"},
	        {title: "Heading 2", block: "h2"},
	        {title: "Heading 3", block: "h3"},
	        {title: "Heading 4", block: "h4"},
	        {title: "Paragraph", block: "p"},
			{title: "Image Left", selector: "img", 
				styles: {
					"float" : "left", 
					"margin": "0 10px 0 10px"
				}
			},
			{title: "Image Right", selector: "img", 
				styles: {
					"float" : "right", 
					"margin": "0 0 10px 10px"
				}
			}
	    ]
	 }); 

</script>
```

**Comment by spocke** [comment]
Can it be reproduced here:
http://fiddle.tinymce.com/Hufaab/2

This page just posts to the same page and the content gets removed each time in google Chrome.

**Comment by Iteracy** [comment]
Hi,

No, the error does not happen there. The content is cleared out.

But it does happen here:

https://www.savvykernow.org.uk/test.php

It doesn't need a form to be submitted to show the problem.

   1. Go to the page, enter something in the test page
   2. Reload the page
   3. The content you entered previously is displayed.

This is the script from that page:

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>test</title>
</head>
<body>
<script language="javascript" type="text/javascript" src="
https://www.savvykernow.org.uk/jscript/tinymce/tinymce.min.js?r=
<?=$rand?>"></script>
<script language="javascript" type="text/javascript">
tinymce.init({
editor_deselector: "not_rich",
   mode: "textareas",
editor_selector: "rich",
   width: 750,
   height: 300,
   plugins: [
        "autolink autosave charmap code contextmenu fullscreen hr image
link lists media moxiemanager nonbreaking paste searchreplace spellchecker
table anchor textcolor"
  ],
  link_list: "link_list.php",
  document_base_url : "https://www.savvykernow.org.uk/",
relative_urls : false,
    menubar: "insert edit format view tools table",
    statusbar : false,
  contextmenu: "link image file inserttable | cell row column deletetable",
browser_spellcheck : true,
  toolbar: "undo redo | styleselect | bold italic underline forecolor |
alignleft aligncenter alignright | bullist numlist outdent indent | l link
anchor | image file media"
});
</script>
<form id="form2" name="form2" method="post" action="test.php">
<textarea name="feedback" id="feedback" class="rich"></textarea>
<input type="submit" name="submit_feedback" id="submit_feedback"
value="Save feedback" />
</form>
</body>
</html>

Cheers, Kat

On 12 April 2016 at 14:12, Johan Sörlin <notifications@github.com> wrote:

> Can it be reproduced here:
> http://fiddle.tinymce.com/Hufaab/2
>
> This page just posts to the same page and the content gets removed each
> time in google Chrome.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tinymce/tinymce/issues/2843#issuecomment-208897973>
>



-- 

*Kathryn Smith*
Director
Iteracy Ltd
kat@iteracy.com 01208 873242 07876 516191
www.iteracy.com 5 Clifden Terrace, Lostwithiel, PL22 0AW

**Comment by rohan210** [comment]
Hi,
I'm guessing it is because the "autosave" plugin.

http://fiddle.tinymce.com/Hufaab/2
1. Just add the autosave plugin to the list and run 
2. Write some text in tinymce
3. Then reload the frame of tinymce(I used right click > This frame > reload frame )
The text is still there in tinymce after the frame is refreshed

**Comment by Iteracy** [comment]
Hi,

I have managed to workaround the problem by giving the textarea a different
name/ID - the form was posting to itself and displaying a different form
with a field of the same name/ID, which showed the contents of the previous
textarea field. When I set the textarea to use a different name/ID this no
longer happens.

Many thanks for looking into this.

Cheers, Kat

On 1 June 2016 at 11:41, Rohan <notifications@github.com> wrote:

> Hi,
> I'm guessing it is because the "autosave" plugin.
>
> http://fiddle.tinymce.com/Hufaab/2
> 1. Just add the autosave plugin to the list and run
> 2. Write some text in tinymce
> 3. Then reload the frame of tinymce(I used right click > This frame >
> reload frame )
> The text is still there in tinymce after the frame is refreshed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tinymce/tinymce/issues/2843#issuecomment-222956473>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABwy9AafgNSEwyRnYgpbEbejGehLoNIWks5qHWHQgaJpZM4IEfVh>
> .
>



-- 

*Kathryn Smith*
Director
Iteracy Ltd
kat@iteracy.com 01208 873242 07876 516191
www.iteracy.com 5 Clifden Terrace, Lostwithiel, PL22 0AW

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by dalipcse91** [comment]
Just remove AutoSave plugin from init method will resolve problem.
