### ISSUE TITLE
Cannot type small letter 'y' in tinymce 4.3.9 editor

### ISSUE THREAD

**Issue by reddyagile** [tinymce/tinymce#2844]
Good see updated version. Unfortunately we found an issue which is impacting high to our customers. The issue is, when we manually typing letter 'y' from keyboard, its not getting displayed on the editor (version 4.3.9 released on 2016-04-12) but working for capital letter 'Y'.

**Comment by spocke** [comment]
Fixed this bug now and released an updated version.
