### ISSUE TITLE
Static width for the cell inside the table in tinymce 4

### ISSUE THREAD

**Issue by kaviyarasanpearson** [tinymce/tinymce#2845]
Hi,

We are using tinymce 4 and we found the default option in the table that while entering the text in the table the table cell width is changing automatically.

Is there any option available in tinymce 4 to make the table cell width as static.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
