### ISSUE TITLE
removing and adding tinyMce control not working in firefox

### ISSUE THREAD

**Issue by ArunChitumalla** [tinymce/tinymce#2847]
I am removing and adding tinyMce control as per my requirement(on click of a button). Below code is not working in firefox. It is working in chrome and IE

  tinymce.execCommand('mceRemoveEditor', false, 'strTextContent');

  tinymce.execCommand('mceAddEditor', false, 'strTextContent');

I am using tinymce 4.3.8

**Comment by spocke** [comment]
I can't reproduce it here:
http://fiddle.tinymce.com/Mufaab

Need steps to reproduce this one thanks.

**Comment by ArunChitumalla** [comment]
I am hiding the div before calling tinymce.execCommand('mceRemoveEditor', false, 'strTextContent');

For some reason this is throwing NS_UNEXPECTED_ERROR in **firefox**. 

Solved this by calling mceRemoveEditor before hiding my div. This solved problen
