### ISSUE TITLE
On Windows insert the char "€" is impossible

### ISSUE THREAD

**Issue by valix** [tinymce/tinymce#2848]
TinyMce 4.3.10  on Chrome or Firefox on Windows insert the char "€" is impossible.

**Comment by spocke** [comment]
You are correct. I switched the a11y key now to ctrl+shift+e not sure how google docs gets around the alt gr = ctrl + alt problem on key events though. I fixed this now in the master branch will probably do a release next week sometime.

**Comment by valix** [comment]
Perfect!

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
