### ISSUE TITLE
applying foreground color to text after applying background color is not working in Firefox

### ISSUE THREAD

**Issue by ArunChitumalla** [tinymce/tinymce#2849]
1) open tinyMce Editor in firefox
2) write some text
3) apply some background color
4) apply some foreground color
5) foreround color is not applied

Issue occurs only in firefox

link for testing is http://codepen.io/tinymce/pen/NGegZK

**Comment by spocke** [comment]
Wasn't able to reproduce this. Give me an example where to type and what. Do you apply color by selection or while typing?

**Comment by ArunChitumalla** [comment]
open the given link in firefox....type some text and then apply background color then select the same text apply some other color. Now text color is not applied.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
