### ISSUE TITLE
TinyMCE will load its skin (same skin) 100 times for 100 textareas

### ISSUE THREAD

**Issue by donShakespeare** [tinymce/tinymce#2850]
http://archive.tinymce.com/forum/viewtopic.php?pid=118438

The browser shows that the skin.css loads as many times as the number of selectors is used to create an editor.

**Comment by spocke** [comment]
Need steps to reproduce it only loads once on my chrome on this test page:
http://fiddle.tinymce.com/Xufaab/2

**Comment by donShakespeare** [comment]
After extensive testing:

For traditional mode (iframe) - Chrome will show in Sources Tab all the iframes (i.e each editor) evoked, and what resources they are using - this is where the skin shows up.
But in the Network Tab it shows that the skin was indeed loaded once.

For inline mode - there is no confusion

**Comment by Afraithe** [comment]
That is content css, it will be loaded for each iframe.

Skin css file is still only loaded once.
