### ISSUE TITLE
Keep_styles still copying styles on enter

### ISSUE THREAD

**Issue by ETPac** [tinymce/tinymce#2855]
When entering content in tinymce and hitting enter, styles on previous paragraph are copied despite having initialized with the keep_styles:false flag being set. 

![image](https://cloud.githubusercontent.com/assets/9255238/14575755/2292b9da-0321-11e6-8bba-071667abd858.png)

![image](https://cloud.githubusercontent.com/assets/9255238/14575780/44727ad6-0321-11e6-90f9-cc5fdfcdac2d.png)

![image](https://cloud.githubusercontent.com/assets/9255238/14575788/573b468e-0321-11e6-9299-13e4f8cadf9d.png)

**Comment by spocke** [comment]
Keep styles just controls if spans, b, i tags are cloned or not so I guess in theory style and class attributes shouldn't be cloned when it's set to false.

**Comment by ETPac** [comment]
Awesome.  Thank you for taking a look at this!

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
