### ISSUE TITLE
Is setMceInteralContent in quirks.js an intentional typo?

### ISSUE THREAD

**Issue by bobbingwide** [tinymce/tinymce#2856]
I raised a TRAC in WordPress to correct the spelling of "interal" to "internal" then searched for other potential mispellings and came across this function.

Can the name be changed to `setMceInternalContent` ?

**Comment by spocke** [comment]
Fixed this issue thanks for reporting it.

**Comment by bobbingwide** [comment]
OK, I've updated the WordPress TRAC. https://core.trac.wordpress.org/ticket/36548
