### ISSUE TITLE
how to customize tinyMCE editor image tools toobar

### ISSUE THREAD

**Issue by siddhartha2083** [tinymce/tinymce#2860]
I am looking for a code where I can remove the following tools from toolbar appearing in the inline toolbar when clicking on a particular image.

The tools that I want to omit from toolbar is
1. Rotate clockwise/anticlockwise & 
2. Flip vertically/horizontally.

I do appreciate for your quick response.

**Comment by spocke** [comment]
https://www.tinymce.com/docs/plugins/imagetools/#imagetools_toolbar
Since this is more of a question than a issue I'm closing this one.
