### ISSUE TITLE
Add "Format painter" button and functionality

### ISSUE THREAD

**Issue by loennerheden** [tinymce/tinymce#2861]
After speaking to many TinyMCE users I got the feedback that one of the most sought-after features was the "Format painter" functionality with which a format in a text (mail) can be chosen and pasted over an existing text that then gets this new format automatically. I can't find any plug in with this feature and also no existing Github entry on this topic.

Is this feature already part of an existing "Upcoming features" list? If not, please add it.
[Format painter in Outlook.pptx](https://github.com/tinymce/tinymce/files/223409/Format.painter.in.Outlook.pptx)

Thanks and kind regards
Ing-Marie

**Comment by AdamFu** [comment]
We need it too!

**Comment by tinydylan** [comment]
Hi,

We have implemented this as a premium feature of TinyMCE. Please [see here](https://www.tiny.cloud/docs/enterprise/formatpainter/) for more details.

Thanks!
