### ISSUE TITLE
http prefix window not redered properly in IE7

### ISSUE THREAD

**Issue by ArunChitumalla** [tinymce/tinymce#2862]
steps 
1)open tinymce (with plugin "link") in IE compatibility mode(say IE 7). 
2)open add link button and enter some url(say www.google.com and do not prefix "http" or "https")
3) click on "OK"
4) dialog for adding "http" is not rendered properly.

Same is working fine IE11, chrome and firefox.

issue can be reproduced by opening http://fiddle.tinymce.com/ in IE compatibility mode(IE 7)

![image](https://cloud.githubusercontent.com/assets/6815346/14601784/da421eec-0581-11e6-9d87-11ba4565f079.png)

**Comment by spocke** [comment]
We don't support IE 7 anymore since Microsoft doesn't even support it.
