### ISSUE TITLE
noneditable blocks full width of editor instead of container

### ISSUE THREAD

**Issue by strikernl** [tinymce/tinymce#2863]
I have created a demo in Codepen to show the problem:

http://codepen.io/strikernl/pen/yOjrbq

On the left, I have three divs (containing LEFT1, LEFT2, LEFT3).
On the right, I also have three (containing RIGHT1, RIGHT2, RIGHT3)

RIGHT2 has been made `mceNonEditable`.

This works fine, except that `LEFT2` can't be clicked on. It also seems to be blocked, but it shouldn't be.

HTML for the test:

```html
<textarea><table>
<tbody>
<tr>
<td><div>LEFT1</div>
<div>LEFT2</div>
<div>LEFT3</div></td>
<td><div>RIGHT1</div>
<div class="mceNonEditable">RIGHT2</div>
<div>RIGHT3</div></td>
</tr>
</tbody>
</table></textarea>
```

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
