### ISSUE TITLE
UL/OL lists can no longer be created from a selection separated by linebreaks

### ISSUE THREAD

**Issue by ryandemmer** [tinymce/tinymce#2865]
TinyMCE 3.x supported the creation of lists from a selection separated by linebreaks, eg:

```
item1<br />
item2<br />
item3<br />
```

but in TinyMCE 4.x, only paragraphs are supported, eg:

```
<p>item1</p>
<p>item2</p>
<p>item3</p>
```

**Comment by tinydylan** [comment]
Hi,

We have evaluated this and decided to keep the current behaviour. 

TinyMCE aims to have a "familiar" user experience, so we often compare intricacies like this to other popular products. I tested Google Docs, Word 2019, Apple Pages, Froala and CKeditor, and they all behave like this.

Thanks.
