### ISSUE TITLE
How to select background image in tinyMCE

### ISSUE THREAD

**Issue by siddhartha2083** [tinymce/tinymce#2866]
I got stock in an issue, I have a div and inside that div, I have a background image using style tag, now what I want is to select that particular image so that on clicking that image I can pop up the tinyMCE image tools. Currently I'm not able to select the image in background. Please help !

**Comment by spocke** [comment]
This is more of a forum question than a ticket. So closing this one.

**Comment by siddhartha2083** [comment]
so, how do I can do this ?
