### ISSUE TITLE
Textarea html tag not removed when name attribute is used. v4.3.2

### ISSUE THREAD

**Issue by JoshuaToth** [tinymce/tinymce#2869]
Hi there people,
I've noticed that the editor strips out tags for `<textarea></textarea>`
unless it has the name attribute: 
` <textarea name="foo"></textarea>`

Not sure if this is intended or not, but not having it stripped out with the name attribute present.. It's a bit of a pain leaving it there.
^_^

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
