### ISSUE TITLE
Image tools: allow user to pass original filename to upload_handler

### ISSUE THREAD

**Issue by donShakespeare** [tinymce/tinymce#2871]
http://community.tinymce.com/forum/viewtopic.php?pid=118502#p118502

Allow option to overwrite existing images.
User would then be able to edit the exact same file without flooding server with numerous image edits of different names.
User can then disable automatic upload and, since all changes are stored in blobs of different urls, user can still benefit from Undo Redo. Then on save, blob is renamed to original filename in handler

**Comment by applecat** [comment]
We also need this feature to have original filename on our server save script to replace original image if exists. For now we uploads our images on server with Django related inline model in site admin and if image is changed we wand to replace original image instead of creating new one. Only one thing in need to know -- it's original filename in images_upload POST request.
Thank you.

**Comment by EvanEdwards** [comment]
I need to know the original name as it was in the HTML, a la "/link/in/cms/puppy.jpg," as I would normally just add a new version to that image after it is edited.  Or _any_ kind of identifying id to compare against the specific images after the edit is made.

**Comment by donShakespeare** [comment]
Anybody found a ack for this yet? I haven't!

**Comment by donShakespeare** [comment]
Well, as I sat down, it happens I found myself a perfect solution.
And yes ` blobInfo.filename();` is the exact thing we want to hijack. Still working on this, so I'll share later.

**Comment by pesla** [comment]
I second this feature request. Can't really implement `imagetools` without being able to identify the image that has been edited. Otherwise, I would flood our servers with numerous (unused) images.

Is there a milestone for this improvement?

**Comment by donShakespeare** [comment]
@pesla this is what I am doing. You need to interrupt the post of the data to the server. So, before `xhr.send` use input prompt or your own logic to ask the user if he wants to save this image with its existing filename (overwrite) or with a new one (thus duplicate).
At this point you can make things really elegant and smooth.

```
 /*replace blobInfo.filename() with the result of your input prompt.
blobInfo.filename() is the random name + actual extension - split that and get the extension part, then join it with the cool name you got from your prompt/logic */
 
formData.append('file', blobInfo.blob(), blobInfo.filename();
xhr.send(formData);
```
I even pre-filled the input field with existing filename and extension, so that the user just needs to press okay. All he needs to do is use a different name in the case he wants to preserve anything.

https://www.tinymce.com/docs/configure/file-image-upload/#images_upload_handler
```
tinymce.init({
  images_upload_handler: myJShandler, //replace the default one
  },

**Comment by jayarjo** [comment]
We've added an option to use original filename for the uploaded images. It will be out with next community release.

**Comment by donShakespeare** [comment]
@jayarjo I am not sure how you implemented it, but it would be doubly useful if the variable  `images_reuse_filename: true` could be altered on the fly, with:
 `editor.settings.image_reuse_filename = fasle` and
 `editor.getParam("images_reuse_filename") = false;`

Thanks for listening and reporting back ...

**Comment by jayarjo** [comment]
It can be altered on the fly. But could describe why would you need that?

**Comment by jayarjo** [comment]
Fix for this has been merged now.

**Comment by donShakespeare** [comment]
`images_reuse_filename` is excellent. 
Is it a bug that `blobInfo.fileName()' does not get the filename of a dragged and dropped file?

**Comment by alexkasina** [comment]
@jayarjo That patch still doesn't return the original file name. If I upload `image.png`, it gets renamed to something like `blob01.png`. Is there a workaround on this so that the server gets `image.png` as the filename?

**Comment by AkashicSeer** [comment]
2020 and images_reuse_filename doesn't work. Why am i not surprised nothing in programming ever, ever, ever fucking works ever

**Comment by AkashicSeer** [comment]
I will not be forced into buying your BS moxiemanager I'll just find a working solution this is utter nonsense
