### ISSUE TITLE
Error when resizing TinyMCE editor when using with angular and angular material

### ISSUE THREAD

**Issue by deeg** [tinymce/tinymce#2875]
First off, thanks for the great library. I am now the active maintainer of the Angular-UI wrapper. Thanks for the link on the website!

Came here to report a small bug I found when using TinyMCE with Angular & Angular Material. [See this plunker for an example](https://plnkr.co/edit/TjhkdC?p=preview)
- Resize the editor and see the error in the console
- Remove the ngMaterial inclusion from the app in demo.js
- Resize the editor and see the error no longer in the console.

I did some digging into this and realized Angular Material is putting a mousemove watch on the document. That fires an angular event callback which ends up hitting [this line](https://github.com/angular/angular.js/blob/0348347841191530417f6c9eb6e991c33f0e8c99/src/jqLite.js#L772).

Then in the TinyMCE code when [this check](https://github.com/tinymce/tinymce/blob/4de35e8b588761a728352305b77a3f0303f8e1be/js/tinymce/classes/dom/EventUtils.js#L140) happens, event.isDefaultPrevented is already defined so it does not get the other function isPropagationStopped attached which ends up throwing the error.

I've done all this testing with the latest TinyMCE and Angular 1.4.8 and Angular Material 1.0.7

**Comment by hassancode** [comment]
Hi, Any updates on this?  I am also using Angular and Angular Material 1.0.0 and can see this error upon resizing editor in console.

**Comment by Afraithe** [comment]
There is an official Angular wrapper project now (tinymce-angular). Closing this ticket, any Angular related issues should be open in that project.
