### ISSUE TITLE
Problem prismjs and tinymce

### ISSUE THREAD

**Issue by viriis** [tinymce/tinymce#2876]
Hi,

I would like to know how to do for have 2 tinymce with "prismjs" in the same page

Exemple: http://www.viriis.com/testTynimce.php

The first it's ok but the seconde doesn't work

Thank you very much for your help

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by viriis** [comment]
I add "/editor/plugins/codesample/css/prism.css" in tynimce and everything work

example:
`<script>
  tinymce.init({
    selector: '#commentProprio',
    content_css : "/editor/plugins/codesample/css/prism.css",
    plugins:"codesample",
    menubar:false,
    toolbar: "codesample",
    default_link_target: "_blank"
  });
 </script>`

Thank you for your answer

bye
