### ISSUE TITLE
Tinymce 4.3.10, inline:true, It is not possible to reaize columns / rows using mouse

### ISSUE THREAD

**Issue by bill8000** [tinymce/tinymce#2877]
Dear Tinymce team,

if I set the inline to FALSE everything works fine, i can resize the columns / rows. I see the moving lines
but as soon as i set the inline to TRUE, not only i can not resize the  columns / rows but also i do not see the moving lines.

Help!
Thx

**Comment by bill8000** [comment]
Hi There!
I have hacked the code of table plugin.js ( see .js and .css changs below ). This happens due to the fact that we are using the tinymce ( inline=true) in a layer which is absolute with z-index already higher than the BODY element. Therefore not only the resize bars are not displayed also when it comes to the BLOCKER element, the blocker element ( which is added to the body element ) also gets placed under the layer in which the tinymce is placed! 
So the fix is simple: give us the proper css class for the BLOCKER element so that we can adjust the z-indexes according to our apps!

Like all the hacks, it is a temporary solution till you dear TinyMCE team come to rescue.
Love you all out there,
Cheers!

```
function getBlockerElement() {
			var blocker = document.createElement("div");

			blocker.setAttribute("style", "margin: 0; " +
						"padding: 0; " +
						"position: fixed; " +
						"left: 0px; " +
						"top: 0px;"+
						"height: 100%; " +
						"width: 100%;");
            /**
             * AcroJ_3_xFix@240416:fix for inline:true and problem of resizing columns/rows with mouse, see css with the same tag
             */
			blocker.setAttribute("class" "table-mce-blocker");
			blocker.setAttribute("data-mce-bogus", "all");

			return blocker;
		}

```

```
In addition the following css styles should be applied:


.mce-resize-bar.mce-resize-bar-row,
.mce-resize-bar.mce-resize-bar-col
{
  z-index: 65536;
}
.mce-resize-bar.mce-resize-bar-row.mce-resize-bar-dragging,
.mce-resize-bar.mce-resize-bar-col.mce-resize-bar-dragging
{
    z-index: 65536;
}

.table-mce-blocker
{
    z-index: 65535;
}
```

**Comment by bill8000** [comment]
Hi Spocke!
Thanks for the tags, what's the next step?
Cheers

**Comment by kaviyarasanaspire** [comment]
Is there any update on this issue? I too not getting the cell resize option while I am loading the tinymce in modal popup with inline mode

**Comment by srirampearson** [comment]
Hi bill8000,

I am trying to implement the resize option as per your code. I got struck from which method you are calling getBlockerElement() method.

Can you share more details on how to implement it. 

It will be helpful if you share the full code or some sample implementation logic.

Regards,
Sriram

**Comment by kaviyarasanaspire** [comment]
Hi @spocke 

Is there any possibilities to have a solution for this issue?

Regards,
Kavi

**Comment by zortext** [comment]
If yo have similar z-index problem add this rule to your stylesheet

```
[class*=ephox-snooker], .ephox-dragster-blocker {
    z-index: 6999999 !important;
}

```

**Comment by blackcathikari** [comment]
To anyone who is seeing this bug, could you please:

- Tell us which version of TinyMCE you're using, and on which OS/browser combinations
- Create a fiddle that replicates the bug: [http://fiddle.tinymce.com](http://fiddle.tinymce.com)
- Tell us any details about the environment you're using TinyMCE in that might affect this? 

I had a quick look at this and wasn't able to replicate it on a basic inline demo: http://fiddle.tinymce.com/sCgaab

**Comment by davidpede** [comment]
Have this issue with v4.9 using chrome. It's caused by setting a z-index value on any parent element. Fiddle: http://fiddle.tinymce.com/6Kgaab

As the 'mce-resizehandle' divs are contained in a div with no id or class the only way I could see to get round it is:
```
div[style*='position: static; height: 0px; width: 0px; padding: 0px; margin: 0px; border: 0px;'] {
    z-index: 999999999999999;
}
```

**Comment by bmatto** [comment]
I am observing this issue as well with `inline: true` where there is a `z-index` on the element which is the tinymce target.  This is for all browsers with 4.9.4.

Further as the class names on those resize wires no longer contain `mce` - interacting with them is causing the inline toolbar to disappear as the editor is "unfocused" at that time; which to me feels like unexpected behavior.

**Comment by bmatto** [comment]
I also noticed that the container created to append the resize "wires" to, does not have a `tabIndex` on it which is contributing to the inline toolbar trashing.

**Comment by peter-nt** [comment]
> If you have similar z-index drag sizer problem add this rule to your stylesheet
> 
> ```
> [class*=ephox-snooker], .ephox-dragster-blocker {
>     z-index: 69999 !important;
> }
> ```

Thanks Zortext, this did the trick!
