### ISSUE TITLE
Insert/Edit Link/Anchor/Image popup dissappears

### ISSUE THREAD

**Issue by tinymcelogin** [tinymce/tinymce#2879]
I have taken upgrade to tinymce version 4.3.8 .I am facing issues with Insert/Edit Link popup.
when i click on the URL /Text to Display or any other text box in the popup, the popup disappears.
I am not sure what causes the issue. It occurs for Anchor, Insert/Edit Image popups aswell.
Kindly help.Thank you.

**Comment by spocke** [comment]
I couldn't reproduce this one. Can it be reproduced on the fiddle.tinymce.com site?

**Comment by tinymcelogin** [comment]
It works fine in the fiddle.tinymce.com. Its not working in my application . I am not sure if any plugin is missed. The older version seems to work fine.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
