### ISSUE TITLE
how to remove line breaks between tags

### ISSUE THREAD

**Issue by lietzi** [tinymce/tinymce#2881]
Hi there!

Is there a way to remove the unnecessary line breaks between html-tags in the tinymce-output?

For example:
```
<ul>
<li>BulletPoint 1</li>
<li>BulletPoint 2</li>
</ul>
```

should be saved like this:

`<ul><li>BulletPoint 1</li><li>BulletPoint 2</li></ul>`
 
Thank you!

Cheers,
Sebastian

**Comment by spocke** [comment]
This ticket seems to be more of a general support question rather than a bug/feature request. Please use the community forums or register for an Enterprise license for commercial support. Thanks.
