### ISSUE TITLE
Blockquote html cleaning a little too agressive?

### ISSUE THREAD

**Issue by cclaerhout** [tinymce/tinymce#2882]
When I insert this in the source code:
`<p><font size="3"><blockquote>test</blockquote></font></p>`
It gives me this:
`<blockquote>test</blockquote>`

Same thing occurs if I use the 'span' tag instead of 'font' one
`<p><span style="font-size: 12px;"><blockquote>test</blockquote></span></p>`
=>
`<blockquote>test</blockquote>`

Any particular reason for this? The parent and children are designed to be 'flow content':
https://www.w3.org/TR/html/grouping-content.html#the-blockquote-element

P.S: I've tried to configure valid_children... I didn't work:
`valid_children: '+blockquote[font],+font[blockquote]'`

**Comment by spocke** [comment]
Hmm if I run the HTML5 validator on W3C on this content:
<!DOCTYPE html>
<html>
<head>
<title>title</title>
</head>
<body>
<span><blockquote>a</blockquote></span>
<blockquote>b</blockquote>
</body>
</html>

The blockquote is invalid within the span element. Blockquotes are not part of "Phrasing content" so they can't be inside say a P tag.

**Comment by cclaerhout** [comment]
Thanks for the fast feedback, I will try to update the html parser to overcome this.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
