### ISSUE TITLE
Translation "Image uploading..." does not work.

### ISSUE THREAD

**Issue by wongyouth** [tinymce/tinymce#2883]
Translation for "Image uploading..." in https://github.com/tinymce/tinymce/blob/4.3.11/js/tinymce/classes/EditorUpload.js#L67 does not work.

I added translation in a i18n file zh_CN.js, but it didn't show up.

`"Image uploading...": "\u56fe\u7247\u4e0a\u4f20\u4e2d...",`

But `tinymce.translate('Image uploading...')` does the job.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
