### ISSUE TITLE
Colorbox in table dialog doesn't preview populated colors until the colorpicker has been used.

### ISSUE THREAD

**Issue by bdf2** [tinymce/tinymce#2886]
Colorbox in table color picker property dialogs should preview the current color if the value is populated when the dialog loads.

This is an image of the cell properties advanced tab on initial load: 

![screen shot 2016-04-27 at 4 15 24 pm](https://cloud.githubusercontent.com/assets/394898/14871057/bead0d72-0c93-11e6-855c-276bd0918af9.png)

Note the preview "chip" has no color though a value of #ff7d7d has been set on the table cell previously.

This is a shot of the same field after opening the color picker and clicking "OK".

![screen shot 2016-04-27 at 4 17 51 pm](https://cloud.githubusercontent.com/assets/394898/14871087/f53cc4fe-0c93-11e6-916e-4138066960e1.png)

Note the color preview has now been set.

**Comment by spocke** [comment]
Fixed this issue in the master branch. It's currently not released so either build tinymce from the github source or wait for the nightly build to help us verify that this bug has been resolved. Thanks.
