### ISSUE TITLE
Table Row properties show "None" instead of real row type

### ISSUE THREAD

**Issue by balmma** [tinymce/tinymce#2889]
When I set a table row to "header" and save it, the table row is correctly changed to a header row. When I now reopen the row properties dialog, the row type select box shows "None" instead of "Header".

When I then click on the select box, "Header" is preselected.

![selection_213](https://cloud.githubusercontent.com/assets/1055447/14934490/dd1f8a9e-0eb1-11e6-9fe9-9a466d0e0545.png)

![selection_214](https://cloud.githubusercontent.com/assets/1055447/14934491/e2e3dd54-0eb1-11e6-9311-fa98d1029bf4.png)

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by balmma** [comment]
Do you mean the latest release version? Still happens in 4.3.12.

**Comment by spocke** [comment]
It moves the selected row to the thead/tfoot and the selection is changed to the body so it's no longer the same cell you are editing type something into the cell and verify that that is the case.

**Comment by balmma** [comment]
Alright, it also happens if I edit the cell and open the row settings again.

I've just captured a video which shows the behaviour.
[table_header.avi.zip](https://github.com/tinymce/tinymce/files/263742/table_header.avi.zip)

**Comment by balmma** [comment]
I've just created pull request #2912 which seems to solve the issue.
