### ISSUE TITLE
Noneditable Plugin does not work correctly

### ISSUE THREAD

**Issue by KrisFoxx** [tinymce/tinymce#2895]
The noneditable plugin is not working the same way in all browsers.

Chrome - Can be dragged and is not editable as I would expect
IE11 - Cannot be dragged
IE8 - Acts very wierd

**IE8 Issues:**
- You can't put your marker directly next to an noneditable element
- You can delete the noneditable element by placing a character right beside it and navigate using arrowkeys, but only one letter at a time, you are not able to delete the whole element at once
- You are not able to just delete the element
- When trying to delete the element, then the marker jumps
- When navigating through the text using arrowkeys and you hit an noneditable element the marker jumps to the end of the line

Try this simple fiddle in IE8 and you should be able to reproduce all of it
http://fiddle.tinymce.com/7wfaab/1

**Comment by spocke** [comment]
IE8 is not supported for cE=false and we have no plans of adding support. Will update the compatibility chart to reflect this.

I will look into the IE 11 drag/drop issue see if it can be improved.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by dsifford** [comment]
@spocke The noneditable plugin in this repo hasn't been updated in 6 months. Can you please specify where this update happened?

**Comment by spocke** [comment]
The noneditable just maps to the core and the core now handles cE=false elements.
