### ISSUE TITLE
Enter press console error

### ISSUE THREAD

**Issue by pliasetski** [tinymce/tinymce#2898]
Hello,
I'm adding table and then resizing it. After I've press enter and console error occurred.
Please see this video for more details: 
https://dl.dropboxusercontent.com/u/73896408/Tinymce%20bug.mp4

Could you help with this issue.

With best regards, Pavel

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
