### ISSUE TITLE
Empty paragraph at the beginning if you start typing after selecting all content

### ISSUE THREAD

**Issue by Thealoner** [tinymce/tinymce#2899]
Steps to reproduce:
1. Add two or more paragraphs of text.
2. Select all text with the mouse or by pressing Ctrl-A.
3. !important: do not press "Delete". Just start typing new text instead.
4. An empty paragraph will be added at the beginning. It is not visible in the visual editor, but you can see it in the source code.

Expected result:
`<p>New text</p>`

Actual result:
`<p>&nbsp;</p>`
`<p>New text</p>`

If you press "Delete" on step 3, it works correctly.

**Comment by pavel-j** [comment]
this is related to: [https://github.com/tinymce/tinymce/issues/2767]

**Comment by tinydylan** [comment]
Hi,

Thanks for logging this report. I agree with pavel-j - this does appear to be the same issue as #2767. 

We believe this defect has been corrected, so we're closing this issue. If you encounter any other issues, feel free to let us know.

Thanks!
