### ISSUE TITLE
Tinymce deletes js-tags from source code

### ISSUE THREAD

**Issue by lepton-dev** [tinymce/tinymce#2900]
Please see description here
http://community.tinymce.com/forum/viewtopic.php?pid=118583#p118583

Js-tags should not be removed using schema:"html5"

**Comment by spocke** [comment]
You need to opt in to allow javascript this is for handing xss filtering. So extended_valid_elements: 'script[src|type|language]' should do the trick.

**Comment by lepton-dev** [comment]
Thats what I did, as you can read on the forum (link above)
But:
if schema is html 5, script tags should be allowed because they are part of html5.
So the question is, why have I to enable them via extended_valid_elements?

**Comment by spocke** [comment]
You need to opt in to allow javascript this is for handing xss filtering. xss is stands for cross site scripting meaning a hacker could trick a user into pasting html contents with scripts that for example steal the login details from the user.

By default we try to prevent as much as possible of common xss patterns like onclick handlers, script urls, script tags etc etc.

**Comment by lepton-dev** [comment]
ok, thanks for information.
A small hint in the docu would be nice.
