### ISSUE TITLE
Loading TinyMCE over HTTPS, yet CSS files are loaded over HTTP and Chrome stops it

### ISSUE THREAD

**Issue by jwatte** [tinymce/tinymce#2902]
I've downloaded a "custom" zip of tinymce, and un-zipped it in a subdirectory of my server. I do not use the TinyMCE CDN, because I'll be integrating this into an app that manages cross-domain issues.
The hosting page, and the tinymce script, are served over HTTPS. However, after doing that, the script turns around and attempts to load two CSS files over HTTP, which Chrome blocks, which causes the load to fail and the editor to not appear.

I've tried configuring for https, but it doesn't seem to "take."

Here's how I initialize it:

        var baseurl = document.location.protocol + "//" + document.location.host + "/(removed)/tinymce";
        tinymce.init({
            'selector': '#stencils_temp',
            width: 960,
            height: 800,
            relative_urls: true,
            remove_script_host: true,
            document_base_url: baseurl,
            protocol: 'https',
            plugins: 'advlist autoresize charmap colorpicker emoticons hr link nonbreaking paste tabfocus textcolor visualchars anchor code contextmenu image insertdatetime lists noneditable preview searchreplace table wordcount autolink directionality fullscreen imagetools media pagebreak print spellchecker template visualblocks'
        });

(The same problem happens with only the selector: configuration)

Here are the errors I get:

(index):1 Mixed Content: The page at 'https://(removed)/stencils/' was loaded over HTTPS, but requested an insecure stylesheet 'http://(removed)/tinymce/skins/lightgray/skin.min.css'. This request has been blocked; the content must be served over HTTPS.

(index):1 Mixed Content: The page at 'https://(removed)/stencils/' was loaded over HTTPS, but requested an insecure stylesheet 'http://(removed)/tinymce/skins/lightgray/content.min.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by jwatte** [comment]
By the way, the version is // 4.3.11 (2016-04-25)
It's configured/downloaded from https://www.tinymce.com/download/custom-builds/

**Comment by spocke** [comment]
Couldn't reproduce this locally or on jsfiddle:
https://jsfiddle.net/bbkskezg/

Need a way to reproduce it in order to fix it. Everything loads fine for me except the icon fonts needs to have cors headers properly setup on the server.

**Comment by rgl2811** [comment]
I am having the same problem. I've tried every possible configuration I think.
This is my current configuration:

`    $(function(){
        tinymce.baseURL = "https://serverurl/js/tinymce"
        tinymce.suffix = ".min"
        tinymce.init({
            selector: "textarea",
            language : "es",
            relative_urls : true,
            remove_script_host : false,
            convert_urls : false,
            plugins: [
                "advlist autolink lists link print preview",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime table contextmenu paste hr"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image| preview"
        });
    });`

The server has a valid SSL Certificate by Symantec. The tinymce.min.js is loaded by https, and when the plugin inits it tries to load the specified plugins with http protocol, getting Mixed Content from my browser (Mozilla) and it is blocking the static content. 

@jwatte Did you solve it?

**Comment by jwatte** [comment]
For me, it was a server side redirect triggered by a missing path. So, entirely operator error.

**Comment by spocke** [comment]
So how exactly are you guys loading the tinymce script it needs to be loaded over https as well to get everything else loaded from the same protocol.

@jwatte I can't reproduce your example on jsfiddle https://jsfiddle.net/nutmjr6k/ I checked that the protocol is https and everything works fine.

Not much else I can do unless it can be reproduced. If it was a major issue that tiny wouldn't load at all in chorme there would be tons and tons of bug reports. So I'm guessing this is a local issue either an implementation issue or some chrome extension issue or possible some proxy like squid.

**Comment by spocke** [comment]
@jwatte Didn't see your comment since it was while I was adding mine. Apologies for any confusion.

**Comment by jwatte** [comment]
The problem for me was that an unrelated error caused a redirect to an insecure version of the page.

**Comment by CuriousChad** [comment]
Thanks jwatte - your "redirect to an insure page" comment prompted me to look at things I assumed would be unrelated and I found the problem.

Thanks and BeGreat

**Comment by ChristophAnastasiades** [comment]
If you are using Cloudflare make sure to install a plugin like [Cloudflare SSL](https://wordpress.org/plugins/ctw-ssl-for-cloudflare/) as this fixed the problem in my case.

**Comment by AdityaV025** [comment]
> If you are using Cloudflare make sure to install a plugin like [Cloudflare SSL](https://wordpress.org/plugins/ctw-ssl-for-cloudflare/) as this fixed the problem in my case.

Thanks it worked

**Comment by merwok** [comment]
FWIW, protocol-relative URLs are valid (e.g. `script src="//cdn.example.com/file.js"`), but it’s simpler to hard-code https URLs given that both http and https pages can load https resources.
