### ISSUE TITLE
Backtick inline text pattern not working on German keyboard

### ISSUE THREAD

**Issue by djkrose** [tinymce/tinymce#2903]
Support for inline `code` using backticks is not working on German keyboards, and probably other European keyboards too.

The backtick character (`), forward tick (´), and circumflex (^) are _modifier keys_ on German keyboards that work differently, because they also allow creating things like à, ê, ó.

That's how it works:

1) You press backtick (needs shift key). keyup event with keyCode 221 is fired, but **no character** is inserted.

2a) You press space key. keyup event with keyCode 32 is fired, but **only the backtick** is inserted.
_or_
2b) You press a supported modifiable character like aeiou, its keyCode is fired and the modified character **àèìòù** is inserted only.
_or_
2c) You continue typing with a non-modifiable character, like a comma (,) or an X. The keyup event is fired with its keyCode, but **both** the backtick (`) and the second character are inserted simultaneously.

You would want to make inline formatting work for 2a and 2c, but obviously not for 2b. This can only be achieved when space key also calls `inline()`(it currently calls only `space()` even though with a backtick before it wouldn't even insert a space), and when inline is called also looking at the character that was inserted before the last one.

I think you need a German keyboard to fully understand ... :)

--
Relevant code: wptextpattern/plugin.js
Tested in TinyMCE 4.3.0

**Comment by spocke** [comment]
I think this is a wordpress specific question please create a ticket in their ticket system. Thanks.

**Comment by mpdude** [comment]
Also reported for Confluence: https://jira.atlassian.com/browse/CONFCLOUD-58002
