### ISSUE TITLE
Issue with YouTube Embed Code in TinyMCE

### ISSUE THREAD

**Issue by PeopleInside** [tinymce/tinymce#2910]
Hi,
I AM using the "Incert/Edit video" button in TinyMCE to add the embed code that me copied from Youtube. 

(That opens a modal dialog with an area you can paste that code).
- After pasting it there and clicking OK, the query arg is removed

So IF paste this Embed code:
`<iframe width="853" height="640" src="https://www.youtube.com/embed/b7XnlhIDz1U**?rel=0**" frameborder="0" allowfullscreen></iframe>`

after saving the post the code miss ?rel=0
so is changed to:

`<iframe src="//**www.youtube.com/embed/b7XnlhIDz1U**" width="853" height="640" frameborder="0" allowfullscreen="allowfullscreen"></iframe></center><center><img class="alignright size-full wp-image-37" src="https://www.peopleinside.it/wpi15/wp-content/uploads/2014/01/MarcoBorla_piccola.png" alt="MarcoBorla_piccola" width="160" height="126" />`

this issue cause the video will show related video at the end of the video when I take the code in YouTube with the option to not show relative video at the end.

Hope you can fix soon this issue, thanks.
[I have alerted](https://wordpress.org/support/topic/issue-with-youtube-embed-code?replies=4) [TinyMCE Advanced](TinyMCE Advanced) plug in but seems is an issue with TinyMCE

**Comment by chaiml** [comment]
Hi, we are also facing this issue and need to resolve it promptly. Is there any ETA or suggested workaround?

**Comment by spocke** [comment]
Fixed this issue in the master branch. It's currently not released so either build tinymce from the github source or wait for the nightly build to help us verify that this bug has been resolved. Thanks.

**Comment by PeopleInside** [comment]
Hi, thank you! 
How to know when this issue will be solved in my Wordpress ... ? I mean know when this issue will be pushed to Wordpress.
Thanks!

**Comment by PeopleInside** [comment]
I continue to see this issue in my website. Tested today.
