### ISSUE TITLE
Text disappears under table in Chrome

### ISSUE THREAD

**Issue by Oleksandr-B** [tinymce/tinymce#2911]
Steps to reproduce:

1. Insert a table with table plugin.
2. Click on the right side of table. Cursor will be active on the whole high of right table border.
3. Press enter to move to next line and type text. Text will be added inside div with class mce-resize-bar like this:
`<div data-mce-bogus="all" class="mce-resize-bar mce-resize-bar-row" unselectable="on" data-mce-resize="false" data-mce-style="cursor: row-resize; margin: 0; padding: 0; position: absolute; left: 25px; top: 48px; height: 4px; width: 576px; " style="cursor: row-resize; margin: 0; padding: 0; position: absolute; left: 25px; top: 48px; height: 4px; width: 576px; " data-row="0">
<p></p>
<p><br data-mce-bogus="1"></p>
<p>jjjjjjjjjjjjjjjjjjjj</p>
</div>`
4. Click again on the right side of table and text under table will disappear.
Can be reproduced here https://www.tinymce.com/docs/demo/basic-example/ only in Chrome, in Firefox works ok.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by shigg1120** [comment]
I am having the same problem
