### ISSUE TITLE
Laravel Elixir Issue

### ISSUE THREAD

**Issue by michaeldalyuk** [tinymce/tinymce#2914]
I am trying to use tinymce with VueJs so decided to import it as an npm module rather than download and add a script tag to a template.

I have version 4.3.12 and I don't receive any errors when running Gulp, however, I receive the following console error when I run the page in Google Chrome.

`theme.js:14 Uncaught TypeError: Cannot read property 'Factory' of undefined`

I am not sure what the issue is referring to and cannot seem to find much information on the internet about it. I thought it would be useful to log it here so I can get some feedback from the tinymce team and other users.

Here is an example script of how I am using it in my app - please note this is within a Vue file - so FileName.vue which gets compiled down using gulp.

```
require('tinymce/tinymce.min.js');

export default {
    ready: function() {
        tinyMCE.init({
            selector: '#test'
        });
    },
```

Is it possible to confirm if this is a known issue, or if you have any information I can refer to in order to resolve the problem.

Any help is greatly appreciated.

Michael

**Comment by mtkdaly** [comment]
Just a quick update to ask if anyone has been able to look at the issue I have reported?

Any feedback would be great, thank you.

**Comment by mtkdaly** [comment]
I have started using CKEditor as it just works out the box without any problems. I do think TinyMCE is a better solution but it is causing too many problems.

I will keep watching this issue and when it is fixed I will consider switching back if I am not too far down the road with adding file managers and other plugins to CKEditor.

**Comment by spocke** [comment]
We don't support loading tinymce as a common js module at this point since you need to load the skin css files, plugins and themes as well and stitching those together might be difficult. However we have looked into this issue in the past and it's something we would want people to do since it's a common pattern. But the lazy loading feature of tinymce makes it a bit harder.

**Comment by eugenevdm** [comment]
> and it's something we would want people to do since it's a common pattern

+1

**Comment by hezhongfeng** [comment]
+1

**Comment by fyrkant** [comment]
@hezhongfeng 
You should be able to use commonjs to load tinymce now, although the skin files will have to be pulled in separately. See this page in docs for info: https://www.tinymce.com/docs/advanced/usage-with-module-loaders/

**Comment by hezhongfeng** [comment]
```
import tinymce from 'tinymce/tinymce';
import 'tinymce/langs/zh_CN.js';
import 'tinymce/themes/modern/theme';
import 'tinymce/skins/lightgray/skin.min.css';
import 'tinymce/skins/lightgray/content.min.css';
import 'tinymce/plugins/hr/plugin';
import 'tinymce/plugins/image/plugin';
import 'tinymce/plugins/imagetools/plugin';
import 'tinymce/plugins/link/plugin';
import 'tinymce/plugins/textcolor/plugin';
import 'tinymce/plugins/colorpicker/plugin';
import 'tinymce/plugins/lists/plugin';
import 'tinymce/plugins/advlist/plugin';
import 'tinymce/plugins/paste/plugin';
```
 Hi @fyrkant  This is my code.And work well.
But `tinymce.js` will get `langs/zh_CN.js ` `skins/lightgray/skin.min.css ` and `skins/lightgray/content.min.css ` still. Do you know how to solve it?
