### ISSUE TITLE
Drag and drop image upload in IE11 gives error

### ISSUE THREAD

**Issue by Manachi** [tinymce/tinymce#2918]
Uploading of images in IE11 doesn't appear to work.

Attempting to upload an image via drag and drop from the desktop into IE11 browser gives an error:

> SCRIPT87: Invalid Argument.

A simple configuration exhibits this behaviour:

```
tinymceOptions = {
        selector: "textarea",
        plugins: ["paste"],
        paste_data_images: true
}
tinymce.init(tinymceOptions);
```

I've created a fiddle to demonstrate:

https://jsfiddle.net/s00fka6u/6/

Tested using IE version 11.0.10240.16766 and Windows 10

Works fine in FireFox and Chrome.

**Comment by henrythewasp** [comment]
Some more info, if it helps.  In addition to FF and Chrome, it also works OK in Edge 25.10586.0.0 and Opera 38 on Windows.  Just IE11 (and IE10) fail on this.

I've patched my own fork to fix this.:
/plugins/paste/classes/Clipboard.js (line 307, in getDataTransferItems() func)

changed:
`items[contentType] = dataTransfer.getData(contentType);`

to
`items[contentType] = dataTransfer[contentType.toLowerCase()] || dataTransfer.getData(contentType);`

**Comment by hh2k** [comment]
@henrythewasp This fix works for me too. Hope it will make it into an release soon.
