### ISSUE TITLE
Insert clickable image plugin

### ISSUE THREAD

**Issue by freeads777** [tinymce/tinymce#2919]
Is there a plugin that allows to insert clickable images? I know I can insert an image and then make it clickable by inserting a link while the image is highlighted, but I am wondering if there's a plugin that has two input fields in it one for image and the other one for a link to insert a clickable image right away? Sorry if that question has already been answered.

**Comment by spocke** [comment]
This ticket seems to be more of a general support question rather than a bug/feature request. Please use the community forums or register for an Enterprise license for commercial support. Thanks.
