### ISSUE TITLE
How do I open a link in a new window within the editor?

### ISSUE THREAD

**Issue by freeads777** [tinymce/tinymce#2920]
Note: I am not asking how to open a link in a new window after it's posted. I want it to become clickable and open in a new window while it's in the editor. Somebody suggested using:

$('a#my_editor').click(function() {
    $(this).attr('target', '_blank');
});

but it didn't do the trick. Is there a way to make links clickable within the editor?

**Comment by spocke** [comment]
This ticket seems to be more of a general support question rather than a bug/feature request. Please use the community forums or register for an Enterprise license for commercial support. Thanks.
