### ISSUE TITLE
How can I stop the drop down menu to open upward?

### ISSUE THREAD

**Issue by freeads777** [tinymce/tinymce#2922]
Is there a way to prevent the drop downs to open upward?

![Image of DropDown](http://s32.postimg.org/3rpv94b2d/image.png)

I tried everything, it still goes up if the bottom of the screen is too close.

**Comment by spocke** [comment]
It will render it upwards if the page doesn't have enough room to place it at the normal location. So is the page tall enough?

**Comment by freeads777** [comment]
Hi! Thank you for your prompt reply. The page is long enough. When a user scrolls the page more down, the popup renders downwards just fine. It's just when a user didn't scroll far down enough and clicked on the button then the popup goes up. It looks more or less fine now since I removed close to half of the fonts. However, it doesn't look aesthetic when I have all the fonts and this long popup goes up. Any suggestions how I can make it always go down?

**Comment by batata004** [comment]
@spocke  you are correct when you say that it will render upwards if the page does not have enought room to place it at the normal location. But this is not true when woeking with forecolor, please take a look at this bug documented here: https://github.com/tinymce/tinymce/issues/2927

**Comment by batata004** [comment]
wasnt this solved yet? Is there any person at Tinymce which nows how to deal with bugs and requests? My last request was very badly handled, there is a huge lack of responsability and profissionalism here.

**Comment by spocke** [comment]
It checks if the viewport has enough room for any floating panel so menus, dialogs etc gets constrained to the visual part of the page. This is to make sure that the user can always select things.

So @freeads777 want's the behavior @batata004 doesn't want. So either fixed in position always downwards or dynamic depending on viewport size. As you see it's hard to please everyone.

We will take these requests into consideration to see what behavior should be default and if any other behavior should be something to opt-into.

**Comment by batata004** [comment]
@spocke me and @freeads777 want the same: ability to customize tinymce dialog position. But my request goes further: it shows you inconsistencies within your tinymce plugin. While all the other button's dialogs show the dialog at the correct position (above if there is no available space below, and below if there is no available space above) the COLOR buttons (foreground and color) always display the color dialog below, ALWAYS. Even if there is no available space below, it will show the dialog below which is a bug, it's not a "feature request", it's a simple and plain bug as I already showed you at http://fiddle.tinymce.com/5xfaab/2

**Comment by fyrkant** [comment]
We are fixing the textcolor panel positioning problem in an upcoming release, closing this.
