### ISSUE TITLE
How could I embed all Images even from server as base64 code?

### ISSUE THREAD

**Issue by Mannshoch** [tinymce/tinymce#2924]
I use tinymce for creating E-Mails and because of the external resource suppressing in all mail clients do I wish to transfer images embedded. How could I do that?

I Use tinymce with open-letters.de newsletter system.

**Comment by spocke** [comment]
This ticket seems to be more of a general support question rather than a bug/feature request. Please use the community forums or register for an Enterprise license for commercial support. Thanks.
