### ISSUE TITLE
How to hide and show -  plugins

### ISSUE THREAD

**Issue by spacejang** [tinymce/tinymce#2925]
I would like to hide and show of Plugins like tool bar.
I am able to hide tool bar when page loaded using "("div.mce-toolbar-grp").hide();" and show the tool bar when it is focus by using " ("div.mce-toolbar-grp").show()".
Wondeing if there is a way hide and show for plugins as well. 
Thank you.

**Comment by spocke** [comment]
This ticket seems to be more of a general support question rather than a bug/feature request. Please use the community forums or register for an Enterprise license for commercial support. Thanks.
