### ISSUE TITLE
Drag and drop images is not working

### ISSUE THREAD

**Issue by carlosramz** [tinymce/tinymce#2926]
I was testing a project in which I have a tinymce included. It was working fine a few days ago but today I realize that the drag and drop images feature is not working anymore.

It has this the plugin paste included and the paste_data_images option set to true. 

I checked on the console and when I drag the image to the editor pops an error:

_Uncaught TypeError: Cannot read property 'indexOf' of undefined_

I noticed that this is happening on Chrome and OSX

Could you help me please?

**Comment by spocke** [comment]
Hmm, I couldn't reproduce this can you provide me with a fiddle.tinymce.com url and also what version of chrome are you using on Mac OS X. I tested with: Version 50.0.2661.102 (64-bit)

**Comment by carlosramz** [comment]
I'm runing Chrome Versión 50.0.2661.102 (64-bit)

and OSX 10.10.2

I tried on mi windows laptop and works perfect, but the problem persists on OSX and other computers of the place I work, also running OSX.

**Comment by carlosramz** [comment]
I put the fiddle here:

[http://fiddle.tinymce.com/Vxfaab/4](url)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
