### ISSUE TITLE
Bug with off display forecolor color picker

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#2927]
Please take a look at this really simple example:

http://fiddle.tinymce.com/5xfaab/2

I want the toolbar to be fixed positioned to the bottom left of the screen. I just made a really simple script that after 3 seconds from page load, the script positions the toolbar fixedly to the bottom left. It works great, but there is a problem: click in the FONT FAMILY button, FORMATS button, LIST button... the dialog displays itself in the upper position which is awesome. But click in the FORECOLOR button, the color picker does not show correctly, it shows down and gets off screen.

There is also a bug with the "title" (legend) of the buttons, it gets displayed at the bottom and nothing gets shown cause it's off screen. Apart from these 2 problems, everything works really fine but this bug really upsets me.

You are doint a really great job guys with this plugin! Hope someone can solve this bug or at least tell me some workaround!

**Comment by spocke** [comment]
It's designed to have the toolbar on top if you want some other UI you need to roll your own. Not sure this is a bug/feature request so closing.

**Comment by batata004** [comment]
@spocke ?? it's not a bug? So why the other buttons display the dialog/box above when the toolbar is bottom positioned? Why? Why only the color button does not work??? Why is this not a bug?

I cant understand what you say and I believe you dont know what you are saying cause if the other buttons use some kind of algorithm to show the box/dialog above why cant you use the same algorithm with the color button? And with the title?
