### ISSUE TITLE
Bug: Buttons sometimes disappear

### ISSUE THREAD

**Issue by freeads777** [tinymce/tinymce#2929]
I started using your editor a few days ago. Once in a while the icons suddenly stop showing. Reloading the browser (I am using Chrome) doesn't fix the issue. Opening a new tab or opening a new window and entering the URL again fixes the issue. I researched and found out that some too had the same issue. Somebody suggested adding this to a .htaccess file (that's added to the fonts folder):

`<FilesMatch "\.(ttf|otf|eot|woff)$">`
  `<IfModule mod_headers.c>`
    `Header set Access-Control-Allow-Origin "*"`
  `</IfModule>`
`</FilesMatch>`

I did and at first I thought the issue was taken care of. However, it happened again just a few moments ago. Please, advise.

**Comment by spocke** [comment]
Probably a cache issue. Fonts needs cors headers cross domain for example when loading the editor form a cdn.

**Comment by spocke** [comment]
This is to vague for to look into. I will reopen this one if you provide more details.

**Comment by freeads777** [comment]
I too believe it's a cache related issue. I use other functions that cache stuff along with the editor and somewhere, somehow they cause this issue. When I clear the cache with a "cache buster" the issue never happens. But then, of course, it slows down the editor's loading time:

`<script type="text/javascript" src="../tinymce/js/tinymce.min.js?<?php echo(rand(1,10));?>"></script>`

I'll figure something out. Thankfully there's a ton of info out there on the web regarding tinymce.
