### ISSUE TITLE
Is moxieplayer.swf still being used?

### ISSUE THREAD

**Issue by jbalsas** [tinymce/tinymce#2930]
Hi,

The file [moxieplayer.swf](https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/media/moxieplayer.swf) is still bundled in with tinymce, but I couldn't really figure out if there's still a live branch that makes use of it.

Best guess based on https://github.com/tinymce/tinymce/search?utf8=%E2%9C%93&q=flashPlayerUrl is that it is just a remnant from the past, but I'd like to verify it.

**Comment by spocke** [comment]
It doesn't seem to be used so it should probably be removed form the repo.

**Comment by jbalsas** [comment]
Sent PR for it https://github.com/tinymce/tinymce/pull/2937 😉
