### ISSUE TITLE
Bug displaying K<sub>eq</sub>&lt;...?

### ISSUE THREAD

**Issue by cprguy** [tinymce/tinymce#2931]
Students are pasting text like this into TinyMCE:

<p>The second reaction (#2) with K<sub>eq</sub>&lt;1 is green-yellow. Bluer reactions form more product, are more complete, and have K<sub>eq</sub>&gt;&gt;1, so #3 is very blue.</p>

The text initially appears correctly and saves to disk correctly, but when it's displayed in TinyMCE again they see this:

The second reaction (#2) with Keqeq>>1, so #3 is very blue.

So, everything between the first &lt; and the subsequent <sub> is being omitted. I assume this is a bug in TinyMCE?

Any comments would be appreciated!

**Comment by spocke** [comment]
You need to do proper encoding:
https://github.com/tinymce/tinymce/issues/2906

So if it can be reproduced on fiddle.tinymce.com then we can look into it.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
