### ISSUE TITLE
cannot remove font-size style

### ISSUE THREAD

**Issue by phamcuongquyet** [tinymce/tinymce#2932]
The tinymce version is 4.3.12. If the content of is set to: 
`<p><span style='font-size: 36px;'>Hello world</span></p>`
I want to remove font-size property of all text in editor. After select all text in editor, calling:  `editor.formatter.apply('fontsize', {value: null});`
or
`window.editor.formatter.remove('fontsize');`
but the command seem to be not working.
Here is my testing code:
```
<!DOCTYPE html>
<html>
	<head>
		<script type="text/javascript" src="./tinymce.min.js"></script>
	</head>
	<body>
		<div contenteditable="true" id = 'text_editor'>
			<p><span style='font-size: 36px;'>Hello world</span></p>
		</div>
		<input type = 'button' value='test' id='button'/>
		<script>
			window.onload = function() {
				editor = tinymce.EditorManager.createEditor('text_editor', {
					plugins: [ "advlist  lists code textcolor colorpicker"],	
					toolbar1: "bold italic underline strikethrough | fontselect fontsizeselect | alignleft aligncenter alignright alignjustify",
					toolbar2: "code | forecolor backcolor | subscript superscript | bullist numlist"
				});
				editor.render();
				
				document.getElementById('button').onclick = function() {
					editor.execCommand("selectall");
					editor.formatter.apply('fontsize', {value: null});
					//window.editor.formatter.remove('fontsize');
				};
			};
		</script>
	</body>
</html>
```
Thank very much!

**Comment by freeads777** [comment]
I removed it in my tinymce.min.js 

Go to your tinymce.min.js  find:

`r = "8pt 10pt 12pt 14pt 18pt 24pt 36pt",`

and then delete 36pt from that line. But maybe your question is about something totally different.

**Comment by phamcuongquyet** [comment]
Thanks @freeads777 for reply!
This problem also occur with other CSS properties. I tried the same test with text color and font family and got the same result. 
` <p><span style='color: #000000;'>Hello world</span></p>`

`editor.formatter.apply('fontsize', {value: null});`
or
`editor.formatter.remove('fontsize');`

**Comment by spocke** [comment]
This ticket seems to be more of a general support question rather than a bug/feature request. Please use the community forums or register for an Enterprise license for commercial support. Thanks.

**Comment by vickyBHG** [comment]
Has anything been done to resolve this issue? Curious to know.

**Comment by naveenakadaba** [comment]
`Please use editor.formatter.toggle('fontSize', { value: 'inherit' });`
