### ISSUE TITLE
Cell options for table in right click menu are disabled for certain selections

### ISSUE THREAD

**Issue by mykbaker** [tinymce/tinymce#2934]
When I am using IE11 selections within a column and selections done top-to-bottom will show the cell options disabled on right click. Selections done bottom-to-top that consisting of multiple columns work fine.  Selections from left to right in the same row show the cell options disabled while right to left work fine. I have not seen these issues with Chrome.

**Comment by mykbaker** [comment]
Any updates on this issue?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
