### ISSUE TITLE
Build Customizer still uses v4.3.11

### ISSUE THREAD

**Issue by sea75300** [tinymce/tinymce#2935]
I'm using TinyMCE for a small project and use the Build Customizer for my TinyMCE pack. I checked the tinymce.min.js and the version is still 4.3.11 instead of 4.3.12.

![tinymce_min_js](https://cloud.githubusercontent.com/assets/13407962/15447091/66337000-1f35-11e6-89ab-c2e469ddda2e.png)

**Comment by spocke** [comment]
Fixed this one now.
