### ISSUE TITLE
Skin Creator creates broken content.min.css

### ISSUE THREAD

**Issue by sea75300** [tinymce/tinymce#2936]
I use the Skin Creator for a custom TinyMCE skin. It's been a while, I noticed that the final skin was partially broken. The design for TinyMCE itself works fine, but the inline styles does not. (wrong font, font-size) I checked the content.min.css and noticed that files from Skin Creator does not contain the css class block before ".mce-content-body .mce-reset".

Bug or correct behavior?

**Comment by spocke** [comment]
Fixed this. I think it was just out of date.
