### ISSUE TITLE
Everything else doesn't matter, you need to address the loading speed first

### ISSUE THREAD

**Issue by freeads777** [tinymce/tinymce#2938]
I got really hopeful when I implemented your editor. Prior to that I tried all kinds of wysiwyg editors and they all fell short. Yours gave me hope. Everything seems perfect as far as the plugins and functionality, but your loading speed is horrible. The first time someone visits the site it may take up to 5 seconds for the editor to load. If the internet connection is slow, who knows, it may take 10-15 seconds. It's terrible. Why is nobody addressing this? Every other bug is nothing compared to this, you have a real issue on your hands to deal with.

First, you need to get rid of those dumb bootstrap icons. They alone can take a second to upload with a slow internet connection. Second, your tinymce.min,js is anything but tiny. It's overbloated and needs to be cut in half. Thirdly, the way you cache stuff ends up interfering with a normal function of your editor. Sometimes the icons disappear for no reason and unless the browser is closed and opened again they ain't coming back. Your cache (the way you do it) is the cause.

Anyway, after struggling for the last 4 days to make it work faster (trust me I tried everything I could find online to make it load up faster) I gave up. I still believe your editor is one of the best out there, but it's overbloated and slow nonetheless.

Sincerely, frustrated user.

**Comment by spocke** [comment]
It's not a priority right now to decrease the size of the script since it loads fast enough as long as you load it from a CDN and gzipped it's around 200k and these are the download times for 200k.

```
ADSL     256 kbit/s    00:00:06
ADSL     512 kbit/s    00:00:03
ADSL     1 Mbit/s      00:00:01
ADSL     2 Mbit/s      00:00:00
ADSL     8 Mbit/s      00:00:00
ADSL     24 Mbit/s     00:00:00
LAN      10 Mbit/s     00:00:00
LAN      100 Mbit/s    00:00:00
3G       7,2 Mbit/s    00:00:00
4G       80 Mbit/s     00:00:00
```

So I'm guessing your users are on the lower bound of that list having slow ADSL connections so I suggest prefetcing the editor or simply have a plain textarea since loading any editor would always be slow under such strict bandwidth requirements.

I strongly suggest using the CDN since it will both gzip, bundle the requests into one and serve a geographically local cached file closest the the user.

I'm closing this one since it's not something we will address. Unless it becomes seconds of download time for the middle of that list.

**Comment by freeads777** [comment]
If you google "tinymce slow loading speed" you'll see how many folks out there are complaining about this very issue. If it wasn't an issue you wouldn't see these many complaints, I guess. It's sad that the loading speed is not and will not be addressed anytime soon. Speed is everything. Many webmasters will prefer faster loading over cool features.

**Comment by androb** [comment]
@freeads777 if you could more details around what are you seeing we might be able to understand the issue better. 

As @spocke mentioned there is a lot you can do today to speed things. For example, GZIP and proper cache headers (such as on the CDN). You could also pre-fetch it prior to it being called. Download size really shouldn't be an issue.

Or is the issue occurring after the script loads? If so some use cases with some sort of timings you are seeing and what you would expect would be useful.

**Comment by freeads777** [comment]
I don't know what else I can say. I am on a Hostgator's dedicated server, my site is lightening fast. As far as the script concerned, I do the normal usage, as you'd expect:

`<script src="../tinymce.min.js"></script>`

`<textarea id="mytextarea"> </textarea>`

`<script>
tinymce.init({
selector: '#mytextarea',
autoresize_bottom_margin: 5,
autoresize_min_height: 350,
	plugins: [
		"autoresize autolink link image lists",
		"media",
		"textcolor colorpicker example imagetools"
	],
	toolbar1: "undo redo | link image media | bold italic underline | fontselect fontsizeselect | forecolor backcolor | alignleft aligncenter | bullist numlist | example",
       menubar: false,
       statusbar: false,
       menu: {
       }
});
</script>`

I use the minimum amount of buttons / plugins. It's not about how I use it. It's about the thing being slow. It's mostly slow for a new user or if someone closes the browser and then comes back to the site. Once the editor is loaded it loads up fast(er). But even then it can have hickups, it can be a whole second or two before it shows up. On top of its slow loading, the icons vanish for no apparent reason from time to time. I placed this in the htaccess file I created in the fonts folder in hopes it would stop the issue, but it didn't:

`<FilesMatch "\.(ttf|otf|eot|woff)$">
  <IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
  </IfModule>
</FilesMatch>`

**Comment by androb** [comment]
@freeads777 I'd recommend trying the CDN version. We've optimized the cache headers there and your users will get it from an edge server closer to them. We use Amazon CloudFront so there are edge servers all over the world.

Aside from that we are going to need way more specifics other than "slower" or "slowest"... i.e. exact timing and diagnosis on what is causing the problem using browser developer tools. And what you would expect. For example: this specific step takes 400ms and it should ideally take less than 100ms.

**Comment by freeads777** [comment]
What's the link to your CDN version?

**Comment by androb** [comment]
The CDN link is //cdn.tinymce.com/4/tinymce.min.js
You can find instructions at https://www.tinymce.com/download/
