### ISSUE TITLE
Unable to install npm packages

### ISSUE THREAD

**Issue by artyomszasa** [tinymce/tinymce#2942]
running
```
sudo npm i -g grunt-cli
npm i
```
on master gives me the following error:
```
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'ephox/bolt' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'tinymce'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.2.0-37-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /home/artyom/Coding/tinymce
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code E404
```

**Comment by spocke** [comment]
I wasn't able to reproduce this. I'm guessing you have a very old version of node and npm could be that it's pre namespaced modules support. Try upgrading all that and try again.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by amaranthrose** [comment]
I'm facing the same issue on Ubuntu 14.04. Furthermore, visiting failing links in the browser returns errors as well. Failing packages:
```
https://registry.npmjs.org/ephox/imagetools/1.0.6
https://registry.npmjs.org/ephox/bolt
```
They both return 404. 
@artyomszasa were you able to get it to work? Thanks in advance.

**Comment by abeMedia** [comment]
@amaranthrose try running `npm install -g npm`, then retry `npm i`, that should fix it!
