### ISSUE TITLE
Why hasen't tinymce prefixed their element ids

### ISSUE THREAD

**Issue by basickarl** [tinymce/tinymce#2943]
I spent the last hour trying to figure out after including tinymce why it broke my application. Apparently tinymce uses the element id "holder" which I was also using.

Why hasn't tinymce prefixed all of their element id's to prevent such collisions?

**Comment by spocke** [comment]
I think we prefix everything can you setup a fiddle where this is happening.
Searching for the word "holder" returned no results that would indicate that "holder" as an ID exists:
https://github.com/tinymce/tinymce/search?utf8=%E2%9C%93&q=holder

**Comment by basickarl** [comment]
Very weird, but the issue is now resolved. All I had to do was remove the textarea and it was working again. Anyhow resolved!
