### ISSUE TITLE
Strong is replaced with span 

### ISSUE THREAD

**Issue by liamsir** [tinymce/tinymce#2944]
![test3](https://cloud.githubusercontent.com/assets/18295983/15543324/bb19d5a2-2294-11e6-8db3-a9a962cddad3.gif)
I'm having an issue with TinyMCE, I don't know if its general bug or I'm missing something in the configuration.
The problem is with strong elements. If you start typing with bold highlighted, then select all text and press backspace, then you start typing again, the new text will be formatted with``` <span style="font-weight"> </span>.```

I tried using valid_elements, invalid_elements but that works only when getting content. 
Also, I used formats: 
```
formats: {
                underline: { inline: 'u', exact: true , styles: {  'text-decoration': 'underline' } },
                strikethrough: { inline: 'strike', exact: true , styles: {  'text-decoration': 'line-through' } },
                bold: { inline: 'strong', exact: true }
            },

```

I've included a gif for clarification.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
