### ISSUE TITLE
Newbie question: how to replace add/edit image dialog with browse dialog?

### ISSUE THREAD

**Issue by denised** [tinymce/tinymce#2948]
If I initialize tinymce 4.1 with image and imagetools plugins:

`tinymce.init({selector: '#myselector', plugins: 'image imagetools'});
`

I would like to have the option to browse for files instead of having to paste a path into the add/edit image dialog.  I tried implementing the `file_picker_callback` option but that doesn't do anything, which is not surprising because the add/edit dialog doesn't have an file picker button to customize.

This seems like such a common use case that I'm sure I'm missing something obvious.  What option am I missing or what hook do I need to override?

thanks

**Comment by spocke** [comment]
There should be a browse icon next to the input field for image if you implement file_picker_callback so if you could provide us with a fiddle illustrating this issue it would be great thanks.
