### ISSUE TITLE
Misspelled glyph name "removefromat"

### ISSUE THREAD

**Issue by mcavalletto** [tinymce/tinymce#2950]
In skins/lightgray/fonts/tinymce.svg there's a definition for `glyph-name="remove format"`, but in skins/lightgray/fonts/tinymce-small.svg the equivalent is misspelled as `"removefromat"`.

**Comment by spocke** [comment]
Fixed this issue in the master branch. It's currently not released so either build tinymce from the github source or wait for the nightly build to help us verify that this bug has been resolved. Thanks.
