### ISSUE TITLE
Every dropdown in inline edition opens but immediately hides (blink)

### ISSUE THREAD

**Issue by andreyluiz** [tinymce/tinymce#2956]
Hard to explain but here's a gif.

![](http://s33.postimg.org/fwx3wmdmn/ezgif_3784265399.gif)

It simply closes as soon as it opens.

I was debugging the js but I was not able to find out what happens.

Any tips?

**EDIT**
In most of times the dropdown simply does not drop. Then, eventually, it drops but hides again.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Couldn't reproduce this one. Thanks

**Comment by andreyluiz** [comment]
Well, I could not reproduce this behavior outside my application.

But I was able to figure out what TinyMCE is doing wrong in my case.

As soon as it opens the drop down, It calls the `FloatPanel.hideAll()` function and hides it again.
When it calls this function, there are two active FloatPanels. The TinyMCE itself, because it is inline and the font size selector. The TinyMCE Float Panel is autohide false, so, it does not hides. But the other one is autohide true. So it hides.

Is there any configuration to disable the FloatPanel autohide? Or, any clues why it is calling the `hideAll()` at this point?

**Comment by andreyluiz** [comment]
Oh, figured it out.

I'm using it inside an iframe. And I'm using a lib called Iframe Resizer. This lib triggers the window's resize event of the iframe whe it loads, then TinyMCE catches this event and triggers the FloatPanel.hideAll(), resulting in my weird behavior.

So, **IFrame Resizer can mess up the TinyMCE's dropdowns**.

Thank you. :)

**Comment by andreyluiz** [comment]
A possible solution:

tinymce.dom.EventUtils.Event.unbind(window, 'resize');

Just for the inline mode.
