### ISSUE TITLE
TinyMCE.init should allow a DOM element or a jQuery selector as its 'selector' argument

### ISSUE THREAD

**Issue by myklemykle** [tinymce/tinymce#2957]
This would avoid the excess computation to find the selection in cases where the calling party already knows the element needed.  In a complicated DOM with several edit windows, that can become a time-waster.

It would also solve the problem of needing an input element to have a globally unique selector in order to attach TinyMCE to it.  That's a bigger problem for me.  I have a form with several editors, each one of which is handled by a Backbone.View with a (potentially) different life cycle.  These can come and go from the DOM, and while I can force them all to have unique element IDs just so TinyMCE can find them, that is not necessary for any other reason in the rest of our app. I'd much rather have the view pass the specific element to TinyMCE when the view calls tinyMCE.init() .

**Comment by sijad** [comment]
any update on this?

**Comment by Afraithe** [comment]
You don't have to use unique ID's, you can use a class selector as well, would that not solve your issue?

**Comment by sijad** [comment]
@Afraithe in my case it does not, using classes for selector make it hard to work with multiple editors. I need to know which editor is which to change their contents.

**Comment by sijad** [comment]
Using only selector make it really hard to use TinyMCE in react and angular, etc

**Comment by Afraithe** [comment]
Alright, thanks for the detailed feedback, really helps. We will consider this feature.

**Comment by Afraithe** [comment]
Hey, whaddaknow, we found an undocumented option called "target" that replaces selector and takes an element. Reason it is ondocumented is that there is no unit tests on it, we will add it to docs soon.

So that should work for you?

**Comment by sijad** [comment]
@Afraithe thanks, that fixes my promlem

**Comment by Afraithe** [comment]
Great!

**Comment by mscreenie** [comment]
This is nice to see as jQuery selector is causing me issues.  But need something like this for fixed_toolbar_container .
