### ISSUE TITLE
Paste long text in Chrome takes very long or hangs the browser

### ISSUE THREAD

**Issue by prp1** [tinymce/tinymce#2958]
Steps to reproduce:
- open https://www.tinymce.com/docs/demo/basic-example/ in Chrome (tested in Version 50.0.2661.102 m (64-bit))
- paste text from this file (~8000 words)
  [long long text.txt](https://github.com/tinymce/tinymce/files/293589/long.long.text.txt)

**Actual result:** it takes ~10 seconds before text is inserted. For some other colleagues Chrome hangs up completely and text does not get inserted
**Expected result:** text is inserted instantly

In Firefox & IE11 text is inserted instantly.

**Comment by alecpl** [comment]
The same Chromium version on Linux and the same text is pasted in 2 seconds on my laptop. Still it could be faster.

**Comment by spocke** [comment]
Probably the html parser doing way to much back tracking in it's regexps.

**Comment by honkmother** [comment]
years later this bullshit still isn't fixed in 2019
 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏
