### ISSUE TITLE
Safari 9.0.3 and up bug with tiny MCE not rendering

### ISSUE THREAD

**Issue by JeremyJackson** [tinymce/tinymce#2959]
Since 5/27/2016 we have seen TinyMCE not rendering in Safari. This seems to be related to a security patch of some sort. This only effects newer versions of Safari.

Has any one else seen this issue?

**Comment by tinydylan** [comment]
Hi,

Apologies for the delay in responding. 

In my testing, TinyMCE displays fine on [this demo page](https://www.tiny.cloud/docs/demo/full-featured/) in Safari 13.1 on macOS 10.15.4. 

If the issue happens again, can you please provide some more details? It could be a specific scenario or config that's broken.

Hopefully, it's just an issue that has already been corrected. However, if you do encounter this, or any other issue, please let us know.

Thanks!
