### ISSUE TITLE
delete list instead smile

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2961]
steps:
1)create bullet list
2)insertsmile
3)press backspace

expected: delete smile
really: delete bullet list

**Comment by spocke** [comment]
What browser does this happen on? And can it be reproduced on fiddle.tinymce.com wasn't able to reproduce it.

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
