### ISSUE TITLE
Bug: paste_preprocess: doesn't work for multiple URLs

### ISSUE THREAD

**Issue by freeads777** [tinymce/tinymce#2962]
When I try to paste multiple URLs (ie http://someurl.com http://someotherurl.com etc) only one gets converted to a clickable link the rest don't:

`paste_preprocess: function(plugin, args) {`
`args.content = args.content.replace(/(https?:\/\/[a-z0-9_.\/?=&-]+)/i, '<a href="$1" target="_blank">$1</a>'); 
},`

Question. Is it how the paste plugin supposed to work or is there something wrong with the code I am using?

**Comment by spocke** [comment]
You probably need g in you regexp/(https?:\/\/[a-z0-9_.\/?=&-]+)/gi

**Comment by freeads777** [comment]
Thanks! Regex isn't my strongest. It's working now.

**Comment by freeads777** [comment]
I need further assistance. I just realized that it also uses the same regex for images, so what happens  is when I copy and paste a page that has images in it, the images stop showing. When I did "Inspect" I noticed that the images were wrapped with the regex I am using for URLs. I guess global (gi) means global. Is there a way to avoid it?
