### ISSUE TITLE
How to initialize an DOM object rather than using selector

### ISSUE THREAD

**Issue by guoyunhe** [tinymce/tinymce#2963]
Hi, since some reasons, I want to initialize an DOM element rather than provide a selector.

Could I do something like this?

```
tinymce.init({
    element: el,
    ...
});
```

**Comment by kyptov** [comment]
Its look like the same issue: https://github.com/tinymce/tinymce/issues/2957.

**Comment by Afraithe** [comment]
Use "target" option to set an element, replaces selector.

Docs will he updated with this.
