### ISSUE TITLE
Text styling (bug?)

### ISSUE THREAD

**Issue by theosanonym** [tinymce/tinymce#2965]
Hello!

I have struggle with an interesting problem.
The issue:
- I have editing the text with tinymce.
- Making a heading (H2), aligned center
- Saving the form (Big green button)

You can watch the video at:
https://drive.google.com/file/d/0B72AEWrKv9-nQzRQN0RuUEJXdXc/view?usp=sharing

As you can see, the Tinymce has completely messing up the H2 element, the style="xyz" falls apart.
Also you can see, that happens only at the "first" click event. At the second click, everything is error-free in the source code.
Of course, this is not okay, because the form submit starts with the first click, and in this case it's stored the wrong code in the database.
(The script doesn't manipulated, this console log comes directly from the Tinymce)

tinymce version: 4.3.12
chrome version: 51.0.2704.79 m
firefox version: 46.0.1

**Comment by spocke** [comment]
Can it be reproduced out side your environment I think this is some form of integration issue not a problem with tinymce. Make sure you use editor.getContent() to get the editor content out.

**Comment by theosanonym** [comment]
Dear Spocke!

You're right, after a few days spent with debugging we realized the problem.
The problem was caused by own system, all _GET and _POST data are too safe, and this cuts off the style codes.

You can set closed or delete this issue.
Excuse me
