### ISSUE TITLE
Chrome: <a> disappear when moving <a><img></a>

### ISSUE THREAD

**Issue by linux-man** [tinymce/tinymce#2967]
This can be confirmed on the online demo.
On a side note, because I can't duplicate the issue, an `<a><img></a>` without a defined alignment draw its handles way outside the image. Since this happens on Electron, with a mix of css files, must be hard to debug.
Image:
![img](https://cloud.githubusercontent.com/assets/1733538/15779424/217f7bd4-2994-11e6-89b1-11bfb1d82609.png)
Image with link:
![aimga](https://cloud.githubusercontent.com/assets/1733538/15779436/3a062cca-2994-11e6-9522-b031fa72efe3.png)

**Comment by spocke** [comment]
We only officially support browser environments you should be able to launch the developer tools in electron since atom has the ability to launch them and it's based on electron that way you can figure out why it's positioned in correctly.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
