### ISSUE TITLE
Can't click links

### ISSUE THREAD

**Issue by drakeywakey** [tinymce/tinymce#2968]
This may actually be an iframe issue? Or a tinymce inside iframe issue.

Inserting a link works just fine, the anchor tag gets placed with the correct href and everything, but I can't follow the link.

Even tried in the tinyMCE demo to be sure I wasn't going crazy. 

![tinymce](https://cloud.githubusercontent.com/assets/18608076/15793179/8d323e1a-299f-11e6-8b0f-3beccc310ca7.PNG)

**Comment by spocke** [comment]
Making links inside the editor would be a UX disaster. How would you be able to edit the links it would be impossible to place the caret inside the link using the mouse. You could have some form of ctrl+click that would open the link though or a context menu with navigate to menu item.

**Comment by drakeywakey** [comment]
I see, I must have misunderstood -- I thought that was why the link plugin was insert/edit link, since you can edit the link through that popup. Thanks for your help!
