### ISSUE TITLE
paste image directly from clipboard is skipped in Chrome on Windows and Linux

### ISSUE THREAD

**Issue by gera2ld** [tinymce/tinymce#2969]
Fails in Chrome 50 on Linux and Windows, but works on Mac OS X.

When an image is copied on Linux and Windows in Chrome via right click -> Copy image, the `e.clipboardData` will have both `text/html` and `File` types.
The `text/html` data is something like this:

``` html
<html>
<body>
<!--StartFragment--><img src="data:image/jpeg;base64,..."/><!--EndFragment-->
</body>
</html>
```

As a result, the paste-image operation is skipped due to `!hasHtmlOrText(clipboardContent)` at tinymce/tinymce@a1e4a25 .

**Comment by gera2ld** [comment]
I think it's better to make `hasHtmlOrText` something configurable because sometimes we may exactly want the image instead of a table from Excel.

**Comment by spocke** [comment]
Couldn't reproduce this one how exactly do you copy the image in. I tested to paint something with gimp and copy that one in if I configure paste_data_images: true and it pasted ok on Chrome 53.

**Comment by gera2ld** [comment]
Copying from GIMP or screenshots is OK, but copying by **Right click -> Copy image** in Chrome 50 on Windows and Linux like this fails:
![Copy image](https://cloud.githubusercontent.com/assets/3139113/15857380/b6915d94-2ced-11e6-8c19-224afc1660a4.png)

The code below shows what happens:
``` js
tinymce.init({
  selector: '#editor',
  paste_as_text: true,
  paste_data_images: true,
  plugins: 'paste',
  setup: function (editor) {
    editor.on('paste', function (e) {
      console.log(e.clipboardData.types);
      // ["text/html", "Files"]

      console.log(e.clipboardData.getData('text/html').replace(/[\w\/+]{100}[\w\/+]+/g, '...'));
      // <html>
      // <body>
      // <!--StartFragment--><img src="data:image/jpeg;base64,...==" alt="Image result for kenny"/><!--EndFragment-->
      // </body>
      // </html>

      console.log([].map.call(e.clipboardData.items, function (item) {
        return item.kind + ':' + item.type;
      }));
      // ["string:text/html", "file:image/png"]

      // Since there are `text/html` contents, `hasHtmlOrText(clipboardContent)` will be true, and pasting data image is skipped
    });
  },
});
```

This only happens on Windows and Linux. The `text/html` data will be empty on Mac OS X.

**Comment by spocke** [comment]
Couldn't reproduce any issue with this test page:
http://fiddle.tinymce.com/Lzfaab

Copy pasted both the url based image and the data url image tested on Chrome 53 Linux and 51 Windows 10.

**Comment by gera2ld** [comment]
You need to set `paste_as_text: true`, which means I accept only plain text or image data.

**Comment by spocke** [comment]
Actually that mean it will only accept tests. So it pastes spaces and that is correct since images are not text.

**Comment by gera2ld** [comment]
But it works well before that commit... So this was a bug and fixed now? I think I will change my way to handle this. Thank you.

**Comment by barteksekula** [comment]
I'm also seeing this issue.
just try to select an image in windows explorer, ctrl+c
then go to https://codepen.io/anon/pen/jKqGaP
and try to ctrl+v

it will not work in Chrome
it works fine in FF

**Comment by saaiful** [comment]
One simple way to solve this is removing the 'contextmenu' plugin.

**Comment by acrens** [comment]
@barteksekula How to solve it?

thanks!

**Comment by acrens** [comment]
@barteksekula i am using tinyTCE version 4.5.1，PowerPaste plugins https://go.tiny.cloud/powerpaste/ you see.

**Comment by eslepova** [comment]
Hi, it is still reproducible in 2020

Windows10 version 1909 build 18363.900
Browsers:
Google Chrome 83.0.4103.116 (64-bit)
Yandex Browser 20.6.1.148 (64-bit)

Ctrl+C Ctrl+V from local file system doesn't work http://fiddle.tinymce.com/k5faab
I also tried
```
navigator.permissions.query({name: "clipboard-read"})
```
the result is 'granted'. Seems that everything is ok with permissions and something is wrong with TinyMCE.

**Comment by peppot** [comment]
Having this issue on Chrome 85 -- when copying a normal sized image, like 800x600 from image context menu in Chrome into something like Signal or GIMP, nothing happens! Firefox works on the exact same scenario

**Comment by 1161740194** [comment]
> 在Chrome 85上出现此问题-将正常大小的图像（例如从Chrome的图像上下文菜单中的800x600复制到Signal或GIMP）中时，什么都不会发生！Firefox在完全相同的情况下工作

you Problem solving problem? I also encountered this problem.

**Comment by 1161740194** [comment]
> Having this issue on Chrome 85 -- when copying a normal sized image, like 800x600 from image context menu in Chrome into something like Signal or GIMP, nothing happens! Firefox works on the exact same scenario

you Problem solving problem? I also encountered this problem.
