### ISSUE TITLE
NS_ERROR_UNEXPECTED when trying to remove editors in Firefox

### ISSUE THREAD

**Issue by VaLeXaR** [tinymce/tinymce#2970]
I have error when i trying to do
`tinymce.remove();`
for all current editors and reinit new editors.

In another browsers this error not exist.

Firefox 46.0.1, Windows 10.

**Comment by VaLeXaR** [comment]
Resolved.
If editor code delete from html before call `tinymce.remove();`, then appear this error in Firefox.
Chrome and other call `tinymce.remove();` without errors.

**Comment by spocke** [comment]
Will see if we can auto detect clobbering better.

**Comment by akshayjai1** [comment]
@VaLeXaR ,
Thank you very much for posting this issue, but
 I did not get your comment
If editor code delete from html before call tinymce.remove();, then appear this error in Firefox.
Chrome and other, call tinymce.remove(); without errors.

please let us know what is the solution.

**Comment by VaLeXaR** [comment]
@akshayjai1 ,
I am calling `tinymce.remove();` before deleting or replacing area, which contains generated editor code.

**Comment by akshayjai1** [comment]
Thank you @VaLeXaR ,for explaining your solution, 

we did similar thing.

for us we replaced the code tab.destroy(), with >>>> tab.domNode.remove()
 
and it solved our issue
Hope it is helpful to someone
