### ISSUE TITLE
www.tinymce.com cdn

### ISSUE THREAD

**Issue by xxvii27** [tinymce/tinymce#2971]
Don't know where to report this issue. but the tinymce from cdn.tinymce.com seems, to break in IE Edge, with an error invalid character. It works when using other cdn from cloudflare, might want to update the library there.

**Comment by spocke** [comment]
Some specific page where this is happening? Also what country are you accessing it from could be some local cdn endpoint issue since I'm not seeing it.

**Comment by xxvii27** [comment]
I'm accessing it from US, pretty sure not a page issue, as it breaks in www.tinymce.com

**Comment by hardberry** [comment]
I have same issue though it's far from this issue posted

**Comment by fyrkant** [comment]
Haven't heard any more reports on the CDN being broken so I'll close this.
