### ISSUE TITLE
Notification Manager Positioning Issues

### ISSUE THREAD

**Issue by benkolera** [tinymce/tinymce#2975]
If I create two notifications at once with the notification manager, the second notification seems to get drawn off-center. If I force a redraw of the screen it gets back to where it needs to be just fine.

Replicated here: http://fiddle.tinymce.com/Czfaab/1

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
