### ISSUE TITLE
win 10 edge not work paste from context menu

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#2976]
1)Windows 10
2) browser = edge
3) http://codepen.io/anon/pen/xOwbgZ
4) Right mouse button click choose "paste"

e: paste text
r:  editor.windowManager.alert('Please use Ctrl+V/Cmd+V keyboard shortcuts to paste contents.');

**Comment by spocke** [comment]
Yes, paste doesn't work on modern browsers. The message is there to teach noobs about the shortcuts.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by bubdou** [comment]
This issue is still reproducible with the latest TinyMCE version. Please reopen.

**Comment by nriahi** [comment]
@spocke , Which other "Modern" browser? Looks to me like Edge is the only "Modern" here. 
Seems more like a bug to me.

**Comment by dsakko** [comment]
Latest versions of Safari (OSX), Chrome, Firefox and Edge for security reasons don't allow the browser to access the clipboard. IE 8,9,10,11 give you an option on first use to allow access.

**Comment by PetrBorisov** [comment]
@spocke reopen, reproduce in 4.4

**Comment by agupta1989** [comment]
@PetrBorisov I think its because `paste` plugin is listed inside `plugins` array. just remove it and it should be working fine. For me this was the case specific to IE EDGE (TinyMCE v4.5.6)
