### ISSUE TITLE
Toolbar button's sub menu doesn't appear in IE 8

### ISSUE THREAD

**Issue by majidzn** [tinymce/tinymce#2979]
Hi.
I use TinyMce editor and set it's height to 100 pixel.The height of some toolbar buttons those have sub menu like 'select font family' or 'select font size' is more than TinyMce editor's  height. (more than 100 pixel)
but description of problem:
in IE 8 , when i click on button, sub menu appear for a second and then disappear automatically and i cant't select any item !!!
**this error occurred just when height of TinyMce editor is less than height of toolbar button's sub menu (and just in IE 8).**

other info :
My windows is 7.
My browser is IE 8.0.7600.16385

**Comment by majidzn** [comment]
please fix this bug, i need it

**Comment by TheSpyder** [comment]
I'm sorry we didn't get to this. I can only assume that 2 and a half years later it's long past the time when a fix would be relevant. Please let us know if that isn't the case.
