### ISSUE TITLE
When you double click a line and apply bullet list, the following paragraph is affected.

### ISSUE THREAD

**Issue by rainbowland302** [tinymce/tinymce#2983]
![tinymcedemo1](https://cloud.githubusercontent.com/assets/6778864/15883758/d06017a2-2d7d-11e6-9cfa-dbb2ba575ae2.gif)

**Comment by Afraithe** [comment]
Could not replicate on Firefox, but it happens on Chrome.

**Comment by tinydylan** [comment]
I can't replicate this on Chrome or Firefox (mac). The issue has probably been corrected since it was logged. If the issue still occurs, please let us know. Thanks!
