### ISSUE TITLE
Links getting stripped out in Joomla

### ISSUE THREAD

**Issue by BamBam2009** [tinymce/tinymce#2986]
Hey everyone,

I hope you can help me: I got TinyMCE 4.3.3 running in CMS Joomla 3.5.1. Everytime I'd like to insert a link or an image both gets stripped out by tinyMCE while inserting (in popup everything is alright, by clicking "insert" the code is gone). 

I tried: 
- disabling text filtering
- adding tags (like "a" or "href") in the "valid elements"-section of the plugin -> then at least the <a> - tag survives but not "href".

I saw that even "class" gets stripped out, although it is listed in "valid elements".

Has anyone an idea what did go wrong?

Kind regards
Matthew

**Comment by Afraithe** [comment]
This is not the right place for support, contact the Joomla devs doing the integration first.
