### ISSUE TITLE
Image relative urls

### ISSUE THREAD

**Issue by abhishekv01** [tinymce/tinymce#2988]
Experts,

We are having an issue with the relative urls for the images. We have the following parameters in init

relative_urls : true
remove_script_host : true

But after adding the image , the following url is added
../../image/a.jpg

Is there a way to remove the initial ../.. before the image url

Thank you

**Comment by An9k** [comment]
abhishekv01,

Check out -- > https://www.tinymce.com/docs/configure/url-handling/#document_base_url

Try to set your below default param accordingly

Ex: document_base_url : "http://www.example.com/path1/"

**Comment by abhishekv01** [comment]
Thank you An9k. 
I have added the server name in the document_base_url .
And added the remove_script_host : true
But we need the relative path for the image. But the hostname is added to the image url.
It can be removed manually , but is there a way for the hostname not to be added when adding the image.

Thank you

**Comment by An9k** [comment]
Try removing this parameter all together --> "remove_script_host : true"

**Comment by Afraithe** [comment]
This is not the right place for support, closing.
