### ISSUE TITLE
Change height after init

### ISSUE THREAD

**Issue by svkmedia** [tinymce/tinymce#2990]
How can I change height or other configuration after tinymce init ?

**Comment by An9k** [comment]
check out --> https://www.tinymce.com/docs/configure/editor-appearance/#height and 
https://www.tinymce.com/docs/configure/editor-appearance/

Ex:
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  **height : 300**
});

**Comment by svkmedia** [comment]
Ok you didn't understand me. I have main js file where I have tinymce init with all configuration.
In another custom file, where I load main js file I want to change height...

**Comment by An9k** [comment]
There is a good article on changing height dynamically .. http://stackoverflow.com/questions/9588025/change-tinymce-editors-height-dynamically

**Comment by spocke** [comment]
Closing this one since it's more of a question than a issue. We will soon release a community portal that would be the ideal place for these kinds of questions. Stay tuned.
