### ISSUE TITLE
tinymce re-order html in a wrong way and remove code

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#2991]
I put this in the source-code editor:

`<ul class="myclass"><li><a href="..." style="background-image: url(image.png);"><div class="mytitle"><h2>Here is a title</h2></div>X</a></li></ul>`

I close the source-code box and open it again and see this:

`<ul class="myclass"><li><div class="mytitle"><h2>Here is a title</h2></div><a style="background-image: url('image.png');" href="...">X</a></li></ul>`
1. you can see the div with h2 is now outside of a
2. remove "X" above and the result is now without a:

`<ul class="myclass"><li><div class="mytitle"><h2>Here is a title</h2></div></li></ul>`

How i prevent removing empty elements and re-order html?
I use option schema with 'html5' and in html5 block element div is valid in a anchor: http://html5doctor.com/block-level-links-in-html-5/
Set option verify_html to false not help here.

reference: https://github.com/tinymce/tinymce/issues/1584
- solution for prevent remove empty a, add option:
  extended_valid_elements: "a[*]",

**Comment by spocke** [comment]
This is the only thing we don't support from HTML5 since it would be hard to edit inline and block level anchors in a sane way. Since a user can potentially have links inside a block text and there is no way to switch between them etc. Say you want to link this content: <p>a</p> it could be linked like this: <a href="#"><p>a</p></a> or <p><a href="#">a</a></p> but the user would select the same thing in both scenarios <p>[a]</p>.

**Comment by Daijobou** [comment]
I founded a workaround setting for this problem
`valid_children : '+a[div]',`

solution for prevent empty tags have a unnecessary _feature_
`extended_valid_elements : 'div[*]',`
this add a "br"-tag in the empty div. Its should stay empty.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Daijobou** [comment]
how can that be? Thats wrong. That problem still exists in 4.4.0.

http://fiddle.tinymce.com/R3faab

**Comment by dsakko** [comment]
Thanks for the link. Agreed, I will reopen this one.
