### ISSUE TITLE
contenteditable autoscroll in editor

### ISSUE THREAD

**Issue by thaylin79** [tinymce/tinymce#2997]
On click from contenteditable=true to parent of contenteditable=false forces editor to auto scroll to top.
An example can be seen in the image plugin with caption applied. A user adds an image with caption checkbox selected. User clicks in caption, then clicks on image after added. Observe editor scroll position now set to top of content.
This seems to be a chrome issue

**Comment by spocke** [comment]
Fixed this issue in the master branch. It's currently not released so either build tinymce from the github source or wait for the nightly build to help us verify that this bug has been resolved. Thanks.

**Comment by thaylin79** [comment]
Great! I'll try to check out and verify today!

**Comment by claviska** [comment]
I was about to file a very similar issue when I found this one. Here's a minimal fiddle to demonstrate the behavior I'm seeing in Chrome:

http://fiddle.tinymce.com/A0faab

**Comment by thaylin79** [comment]
Awesome! What a simple fix! Works great.

**Comment by thaylin79** [comment]
What's the roadmap for getting this into tinymce-dist?

**Comment by spocke** [comment]
Will be out in the next release looks like the end of this month will be a more major release.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
