### ISSUE TITLE
home/end on contenteditable="false" incorrect cursor behaviour on chrome

### ISSUE THREAD

**Issue by tkanafa** [tinymce/tinymce#2998]
When inserting <a> link with contenteditable="false" in separate line move cursor to this line by either pressing key up or down.
press home (ok cursor is at the beginning of line), press end (wrong, selection selects the parent **p** element), press home - cursor is moved to the beginning of the first line (should move to the beginning of current line). Suspecting that the parent **p** element is selected and from there it breaks when pressing home/end keys (home goes to the beginning of the first line, end goes to the end of the last line)

Example generated code:
`<body id="tinymce" class="mce-content-body " data-id="mce_0" contenteditable="true" spellcheck="false">`
`<p>test1</p>`
` <p><a href="#" contenteditable="false">link contenteditable false</a></p>`
`<p>test2</p>`
`</body>`

Env:
Linux, google chrome 51.0.2704.63 (64-bit)
Tinymce 4.3.13

It seems to be working fine under firefox (different contenteditable implementation?)

there is some keys handling in tinymce (sometimes adds zero length space after element that is contenteditable=false). maybe some specific code could be added for home/end handling:
`
editor.on('keydown', function(e) {
				if (VK.modifierPressed(e)) {
					return;
				}

				switch (e.keyCode) {
					case VK.RIGHT:
						override(e, right);
						break;

					case VK.DOWN:
						override(e, down);
						break;

					case VK.LEFT:
						override(e, left);
						break;

					case VK.UP:
						override(e, up);
						break;

					case VK.DELETE:
						override(e, deleteForward);
						break;

					case VK.BACKSPACE:
						override(e, backspace);
						break;

					default:
						if (isContentEditableFalse(editor.selection.getNode())) {
							e.preventDefault();
						}
						break;
				}
			});
`

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
