### ISSUE TITLE
pressing enter on selected contenteditable=false causes editor.execCommand('Delete');

### ISSUE THREAD

**Issue by tkanafa** [tinymce/tinymce#2999]
when you have some contenteditable=false element in editor and you select it (focus it) and you start pressing enter key then editor starts deleting content from the end.
after debugging there is some condition
`if (!rng.collapsed) {
				editor.execCommand('Delete');
				return;
			}
`
in EnterKey.js, function handleEnterKey(evt)

that seems to be the culprit

Tinymce 4.3.13
Chrome 51

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
