### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by gagan0** [tinymce/tinymce#3001]
The following files not found and are throwing error (as picked up from Console):

> 1. file:///C:/Users/.../MCE/tinymce/www.tinymce.com/images/glyph-tinymce@2x.png Failed to load resource: net::ERR_FILE_NOT_FOUND
> 
> 2. file://fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css Failed to load resource: net::ERR_FILE_NOT_FOUND
> 
> 3. file://www.tinymce.com/css/codepen.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND
> 

Am I missing something here?

**Comment by spocke** [comment]
Where are you getting these errors on the tinymce.com site. I check the examples and they don't produce the errors above when I try it.

**Comment by gagan0** [comment]
oh! Its working. I hadn't updated my code to include https:// as the prefix.
Thanks for the support :+1:

**Comment by PaykomanVll** [comment]
i have seen i have same probleme :( with this file 

http://fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css 

anybody a idea? =(

**Comment by MNF** [comment]
@PaykomanVll , it's probably too late, but you can delete it .See http://stackoverflow.com/questions/41724713/tinymce-get-http-fast-fonts-error-in-console/41725101#41725101
