### ISSUE TITLE
Tinymce+React. Setting textarea name property

### ISSUE THREAD

**Issue by noirwave** [tinymce/tinymce#3007]
Hi.
How can I set "name" property to textarea component with &lt;TinyMCE/&gt; component?
I can set "content", "config" and what about the "name"?
Thanks.

**Comment by spocke** [comment]
We don't have an official react component we link on the site to the most popular third party one. So I suggest posting this ticket there. Thanks

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
