### ISSUE TITLE
NonEditable Firefox issue

### ISSUE THREAD

**Issue by KrisFoxx** [tinymce/tinymce#3008]
It is not possible to move noneditable fields in the newest versions of TinyMCE on Firefox (Tested on FF 47)

You can move in 4.2.7, but not in 4.3.9

Works as a charm in Chrome

http://fiddle.tinymce.com/H0faab

**Comment by KrisFoxx** [comment]
@spocke Any thoughts of when this is being fixed?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
