### ISSUE TITLE
error in console after set content

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#3013]
http://codepen.io/anon/pen/GqNJMr

steps:
1) type text in editor
2) move cursor to input
3)click on button
see in console: 'The given range isn't in document'

it`s cause on focusout you save lastfocusbookmark in editor.selection

if content change (new content length <  editor.selection.lastfocusbookmar range length) and focus not in container last focusbookmar not set null in setContent

decision: editor.selection.lastfocusbookmark= null in setContent()

**Comment by jhao** [comment]
I also meet this issue, I guess when focus not on the editor, it could not get the range from the editor

**Comment by nelsonc24** [comment]
Same +1

**Comment by pribilinskiy** [comment]
This happens constantly in Inline mode when deleting content while holding backspace
