### ISSUE TITLE
forecolor backcolor css problem

### ISSUE THREAD

**Issue by wxlfight** [tinymce/tinymce#3015]
<img width="124" alt="screen shot 2016-06-22 at 3 05 44 pm" src="https://cloud.githubusercontent.com/assets/5794010/16257395/ea752f66-388a-11e6-95c6-da4b5c101069.png">

enviroment:
chrome: Version 51.0.2704.103 (64-bit)
tinyMCE verison: 4.3.13(newest)

**Comment by spocke** [comment]
Not seeing it here:
https://www.tinymce.com/docs/demo/full-featured/

Could you provide me with a fiddle or something that reproduces this issue thanks.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
