### ISSUE TITLE
Font size shown in drop down list is not correcct

### ISSUE THREAD

**Issue by majidzn** [tinymce/tinymce#3016]
1 - I have a text in Tinymce editor with diffrent font size.for example, font size of  the first line is set to 12pt, font size of the second line is set to 20pt and font size of the last line is set to 34pt.

2 - When select all the text, tinymce chooses one of the 12pt,20pt or 34pt items in the font size drop down list on toolbar Randomly, while it has not choose any item of the font size list.

**Is it a bug? How can i fix it?**

**Comment by spocke** [comment]
Same here need a way to produce it http://fiddle.tinymce.com/Y0faab it always shows the font size of where the start of the selection is. In theory we should check both start and end but we just check the start of a non collapsed range.

**Comment by majidzn** [comment]
hi, i want no item select like MS Word, how can i change it?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by majidzn** [comment]
Hi, Which version would you want to fix this bug?

**Comment by dsakko** [comment]
Apologies for this, there hasn't been a change to set the font size to blank when the selection includes multiple font sizes. I'll reopen this one as a feature request.
