### ISSUE TITLE
Font family doesn't work well in Google Chrome

### ISSUE THREAD

**Issue by majidzn** [tinymce/tinymce#3018]
When A tow-word font family witch separated by space (**like Arial Black or Courier New**) is set to a text, Tinymce puts the font family in a double quotation.
for example the created html by Tinymce will be like this : 
`<span style=`**"**`font-family:`**"**`arial black`**"**`;`**"**`> some text </span>` 
**Pay attention,it puts double quotation in another double quotation !!!**

then when i get Tinymce html content and set it to another object like DIV, the style of the text does not work.because Google Chrome doesn't support double quotation in another double quotation and change html like this :
`<span style=`**"**`font-family:;`**"**` arial=`**""**` black=`**""**` > some text </span>` 

**Why does Tinymce put double quotation around tow-word font family witch separated by space** **How can i fix this bug?**

**this bug is just in Google Chrome**

**Comment by spocke** [comment]
I couldn't reproduce it here: http://fiddle.tinymce.com/X0faab please provide a fiddle where it can be reproduced and I look into it. Thanks.

**Comment by majidzn** [comment]
hi, please see your link in **Google Chrome Version 51.0.2704.103 m or 51.0.2704.106 m**.
the **third** "some text" don't has any font family.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by majidzn** [comment]
Hi, Which version would you want to fix this bug?

**Comment by dsakko** [comment]
Hi, at this stage I'm unable to reproduce your issue. I can see the end result you are reporting, but I can't seem to get TinyMCE to make it happen. When reporting these we really need to have a fiddle or code pen example and the steps that you go through to recreate the issue.

If you can provide this it will help us look into it further. Thanks :)

**Comment by guihuxiansheng** [comment]
@spocke I also meet this bug.It show when I set font_formats config and the font-family has whitespace.The plugin will set font-family value width double quotation mark.It will break the style and add font-family value to the attribule of element.we hope that setting font-family value width single quotation mark.
