### ISSUE TITLE
Link plugin: mailto confirmation

### ISSUE THREAD

**Issue by church29** [tinymce/tinymce#3019]
More of a request than a bug, but the mailto confirmation should also be placed behind a setting variable similar to "link_assume_external_targets".

**Comment by lnewson** [comment]
Hi,

I've just tested this using TinyMCE 4.9.10 and 5.2.2 and it appears that this feature has been implemented at some stage since you logged this request. I'll go ahead and close this, but if it doesn't meet your expectations then let us know and we'll reopen this feature request.

Thanks!
