### ISSUE TITLE
&lt; Causes problems when loading content

### ISSUE THREAD

**Issue by mjbc** [tinymce/tinymce#3022]
If I try to load content that has a &lt;3, for example, it causes the following text to be interpreted as attributes

Example:
`&lt;3 this is some text`

is loaded as
<3 this="" is="" some="" text=""

I tried the version 4.3.12. I also edited the "official" pen to make sure it wasn't a "setup" problem, and It has the same problem.

**Comment by spocke** [comment]
Properly encode your content `&amp;&lt;` not `&lt;` this is not a tinymce bug since you need to properly encode the contents in a textarea this is explained in other tickets in great detail.
