### ISSUE TITLE
Allow alignment buttons to add classes instead of inline styles for images.

### ISSUE THREAD

**Issue by christianmagill** [tinymce/tinymce#3023]
I'd like to see an option to allow the alignment buttons to add classes instead of inline styles to images.

TinyMCE is already doing this for "figure" tags and it allows for desired margins to be set in addition to the floats through css.

For images we are stuck with inline style, or creating a style format, which isn't as intuitive especially when you have to tell clients to align images with captions one way, and images without another.

Thanks.

**Comment by spocke** [comment]
This is a config option check the formats setting.

**Comment by christianmagill** [comment]
@spocke Is there any way to just change the settings for figure, img, and table without affecting the way TinyMCE works for paragraphs and other text based alignment?

**Comment by JayAdra** [comment]
+1 Would be great to have this.
