### ISSUE TITLE
Multiple inline editors weird mouse selection failure on menu style

### ISSUE THREAD

**Issue by Rycochet** [tinymce/tinymce#3028]
Sadly this is in a large project that's Chrome only, so I haven't had the time to fiddle / test on anything else.

Description of problem:

The selection with multiple inline editors doesn't seem to refresh correctly, however when pressing a key the selection updates even when it's a modifier key and nothing is actually changing - only affects menu styles and not button clicks.

Steps to reproduce:
1. Create multiple inline editors (only tested on "P" nodes).
2.Select a word (either by keyboard or mouse).
3. Click any format (bold / italic etc) - style applied.
4. Double click / drag select in a different editor.
5. Change the style via the "Font Sizes" or "Format" dropdowns.

Expected result: Style applied

Actual result: Style *NOT* applied, and bogus element added at top of "P"

1-4. Refresh and run through steps 1-4 again (select in second editor).
5. Press and release a modifier key such as ctrl (ie, don't change the selection).
6. Change the style via the "Font Sizes" or "Format" dropdowns.

Expected result: Unsure at this stage...

Actual result: Style applied

TinyMCE: 4.3.12 (2016-05-10)
Chrome: 51.0.2704.103

**Comment by Rycochet** [comment]
Found a workable workaround that shows how weird the bug is, add this to the init -

``` javascript
setup: function(editor) {
	editor.on("selectionchange", function(event) {
		editor.bodyElement.dispatchEvent(new KeyboardEvent("keyup", {}));
	});
}
```

Interestingly it doesn't work on `document.body`, but does on any element within the editor.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
