### ISSUE TITLE
translate() fails with untranslated Object.prototype functions names

### ISSUE THREAD

**Issue by aruben-c** [tinymce/tinymce#3029]
Hi,
I found a bug in the 'translate()' function:
when we try to translate a word with the same name of a Object.prototype function, without giving it translation before, the 'translate()' return the function itself and not the initial text.

**Ex:**
- load a translation file for a language, but without the translation of the word "hasOwnProperty";
- call translate('hasOwnProperty');
-> it returns the function hasOwnProperty() and not the word untranslated 'hasOwnProperty'
- add a translation for the word "hasOwnProperty" (ex: 'good');
- call translate('hasOwnProperty');
-> it returns the translation for the word 'hasOwnProperty': 'good'
-> but the function 'hasOwnProperty()' doesn't work anymore

**Where is located the bug?**
in 'translate()' function at: "(langData[text] || text)"  and  "(langData[text[0]] || text[0])"

**What are the affected words?**
all Object.prototype functions names:
<pre>__defineGetter__
__defineSetter__
__lookupGetter__
__lookupSetter__
eval
hasOwnProperty
isPrototypeOf
propertyIsEnumerable
toLocaleString
toSource
toString
unwatch
valueOf
watch</pre>
+all others created by js frameworks + all future functions.

**How to correct?**
I think a simple test with " typeof langData[text]==='string' " can resolve this issue:
*before:*
return (langData[text] || text).replace(/{context:\w+}$/, '');
*after:*
return ((typeof langData[text]==='string'?(langData[text] || text):text).replace(/{context:\w+}$/, '');

Thanks,
ARuben

**Comment by jayarjo** [comment]
While it shouldn't return a function for `hasOwnProperty`, there's no way you can have translation for `hasOwnProperty` (e.g. `good`) and still have `hasOwnProperty()` method working on the dictionary. Why would you want it to anyway (or any other listed methods)?

**Comment by aruben-c** [comment]
Hi,
I found this issue when I try to translate the word "watch" for my plugin: I had not yet provided the translation when I was trying to test my plugin and I get an error on Firefox (currently, this function only works in Firefox/gecko, but a polyfill exist). After providing the translation, the issue disappear, of course, because the provided translation override the function 'watch'.

I talk about "hasOwnProperty" on my bug explanation because this function works on all browser. It's only an exemple. 'watch' is very specific to Firefox currently.

The issue is more global: if a third party js code adds a prototype function to Object (for exemple the function "subscribe()") and a plugin forgets to provide the translation for the word "subscribe", the plugin/interface/tinymce could be broken.

So, as this Library I18n is a translation Library, we expect that it always returns a string text, and better, the original word or empty string if the translation is not found.

ARuben

**Comment by jayarjo** [comment]
Here is the code after my changes:

```javascript
translate: function(text) {
	var langData = data[code] || {};

	function toString(obj) {
		return obj + "";
	}

	function getLangData(text) {
		return {}.hasOwnProperty.call(langData, text) ? toString(langData[text]) : text;
	}

	if (text === null) {
		return 'null';
	}

	if (Tools.is(text, 'object') && text.hasOwnProperty('raw')) {
		return toString(text.raw);
	}

	if (Tools.is(text, 'array') && Tools.is(text[0], 'string')) {
		var values = text.slice(1);

		text = getLangData(text[0]).replace(/\{([0-9]+)\}/g, function($1, $2) {
			return values.hasOwnProperty($2) ? toString(values[$2]) : $1;
		});
	}

	return getLangData(toString(text)).replace(/{context:\w+}$/, '');
}
```

Could you try if it solves your problems? It uses `Tools` methods to test variable type but you can fallback to your way of doing the same.

**Comment by aruben-c** [comment]
Hi,

I think there are some improvements to do:

**toString()**
According to  https://github.com/airbnb/javascript/tree/es5-deprecated/es5#type-casting--coercion , it's better to do  ""+obj  (instead of  obj+"" ).
I prefer to write   ""+obj  each time: better minification and speed (no define + multiple call to a function).

**getLangData()**
According to  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty , it's better to do  
Object.prototype.hasOwnProperty.call(...  rather than  {}.hasOwnProperty.call(...  because there are no newly created objects.

**test  if (text === null) {**
It doesn't test undefined.
But :
if (text == undefined) { return toString(text);}
returns 'null' or 'undefined'

**test  Tools.is**
Of course, I prefer to use the method  Object.prototype.toString.call(text) === '[object Object]'  because currently I18n has no dependancies. With the use of "Tools.is", I18n has a dependency with Tools now ; so the "define/require" must be changed:
from
define("tinymce/util/I18n", [], function() {
to
define("tinymce/util/I18n", ["tinymce/util/Tools"], function(Tools) {

**values returned for 'null' and 'undefined'**
You return 'null' and 'undefined'. It's a choice. As I say in #3192, I prefer an empty string due to my point of view (philosophical?): "when we give nothing, we receive nothing!".

**test with $1 $2**
I like it, it also solves another potential bug when the value is not provided.

Your code solves my issue, thanks to getLangData() and toString().
Thanks,
ARuben

**Comment by aruben-c** [comment]
Correction to my previous comment:
**getLangData**
It's fail for "new String" and "new Number" and "numbers".
So:
```
function getLangData(txt) {
     return Object.prototype.hasOwnProperty.call(langData, txt) ? ''+langData[txt] : 
                   (Object.prototype.toString.call(txt) === '[object String]' ||
                    Object.prototype.toString.call(txt) === '[object Number]' ?
                             ''+txt : Object.prototype.toString.call(txt));
}
```

**Comment by jayarjo** [comment]
Next release will contain the fix.
