### ISSUE TITLE
Loading TinyMCE triggers mocha.js error

### ISSUE THREAD

**Issue by myklemykle** [tinymce/tinymce#3035]
I've added tinyMCE to a web application, but it causes our test suite to throw errors. 

We use mocha.js, which detects 'global leakage', i.e. the creation of global variables in the browser during tests.  (It's a very useful test, because it catches when we forgot to put 'var' in front of something.)

When TinyMCE loads, it creates three globals: 'tinyMCE', 'tinymce', and a third variable that always has a different name: 'mce-data-xxxxxxx' where x is a random alphanumeric character.  mocha.js throws 'global leakage' errors because of these globals.

Of course, mocha.js can be taught to ignore the globals created by a third-party library like tinyMCE ... but only if it knows what they're named!  Because tinyMCE creates a randomly named global, I don't have a way to make our test suite pass.

Is there truly a need for a random, uniquely-named global variable?  Could this not just be a randomly-named property on the global tinymce object?  Or a randomly-named property of a global object with a predictable name?

**Comment by lnewson** [comment]
Hi,

TinyMCE now only registers 2 globals: `tinyMCE` and `tinymce`, sorry this wasn't updated when the change was made. I'll go ahead and close this since it's been fixed in the latest version, but let us know if you are still having issues and we'll reopen this issue.

Thanks!
