### ISSUE TITLE
Re-applying the bullet/numbered list format to a list fails

### ISSUE THREAD

**Issue by DanielDIQA** [tinymce/tinymce#3037]
1) enter a multiline bullet/numbered list into the editor, e.g.

* bullet 1

* bullet 2

2) select the list and click on the "bullet list"- or "numbered list"-icon in order to remove the bullets/numbers. Keep the selection!
3) click again on the "bullet list"- or "numbered list"-icon in order to apply this format again to the list.

==> result: one bullet/number for the **entire** selection, e.g.
* bullet 1

    bullet 2

==> expected result: one bullet/number **per line**
This behavour is a problem if during editing the user wants to re-apply the bullet/numbered format to a huge list since the user has to manually add another linefeed at the end of each line of the list.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
