### ISSUE TITLE
Table plugin format error

### ISSUE THREAD

**Issue by daver182** [tinymce/tinymce#3041]
When adding table plugin I get "format.replace is not a function", and fails to load.
If I remove table plugin it loads everything ok.

Tinymce 4.4.0

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
