### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by Fouzyyyy** [tinymce/tinymce#3042]
Greetings,

I have noticed an overflow in certain breakpoints when using the "link" plugin, actually the modal that is used for setting the page url of a link overflows under certain screen width and become "ugly". This happens in screens of a width that are smaller than 430 px. It is possible to see this in action by using the responsive tool of one of the web browsers (using firefox for my case).

I don't want to use a bad fix for this issue so, is there a clean way to get rid of the part that overflows ?

Thank's in advance

**Comment by lnewson** [comment]
Hi,

This should be resolved with TinyMCE 5, as its dialogs are responsive so they'll shrink and reorder grid items when displayed on smaller viewports. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!
