### ISSUE TITLE
navigation left skipps some contenteditable=false nodes

### ISSUE THREAD

**Issue by tkanafa** [tinymce/tinymce#3048]
insert this markup into editor
```<p><a tabindex="-1" class="user-hover" contenteditable="false" href="../secure/ViewProfile.jspa?name=tkanafa" rel="tkanafa" data-mce-href="../secure/ViewProfile.jspa?name=tkanafa" data-mce-tabindex="-1"> space full name </a>test <a tabindex="-1" class="user-hover" contenteditable="false" href="../secure/ViewProfile.jspa?name=tkanafa" rel="tkanafa" data-mce-href="../secure/ViewProfile.jspa?name=tkanafa" data-mce-tabindex="-1"> space full name </a> <a tabindex="-1" class="user-hover" contenteditable="false" href="../secure/ViewProfile.jspa?name=tkanafa" rel="tkanafa" data-mce-href="../secure/ViewProfile.jspa?name=tkanafa" data-mce-tabindex="-1"> space full name </a> test <a tabindex="-1" class="user-hover" contenteditable="false" href="../secure/ViewProfile.jspa?name=tkanafa" rel="tkanafa" data-mce-href="../secure/ViewProfile.jspa?name=tkanafa" data-mce-tabindex="-1"> space full name </a>​</p>```
go to the end of the line and start navigating left (left arrow on keyboard)
last element with ce=false is selected with some border, next you can iterate left over the last text "test" and when the cursor is after "e" and you press left then cursor skips the two ce=false element and is placed after the first "test" text

Expected behavior
- when navigating left the cursor should go through the secod "test" string and allow all ce=false element to be selected

Tinymce 4.4.0

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
