### ISSUE TITLE
Request for reduced default codesample plugin dialog window height & width

### ISSUE THREAD

**Issue by ephox-allen** [tinymce/tinymce#3051]
[User known issues](http://stackoverflow.com/questions/37219576/tinymce-codesample-plugin-dialog-height). Currently the default input window size is 800 x 650 which is quite large for smaller view port. Smaller size of **600x450** would fit much nicer(including TinyMCE fiddle display).

```
  editor.windowManager.open({
            title: "Insert/Edit code sample",
            minWidth: Math.min(DOM.getViewPort().w, 800),
            minHeight: Math.min(DOM.getViewPort().h, 650),
            layout: 'fit',
```

**Comment by lnewson** [comment]
Hi,

This should be resolved with TinyMCE 5, as it's dialogs are responsive so they'll shrink when used on smaller viewport. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!
