### ISSUE TITLE
tinymce.com Build Customizer contains outdated version (old version 4.4.1 instead of 4.4.3)

### ISSUE THREAD

**Issue by acshef** [tinymce/tinymce#3053]
`tinymce.min.js` file is dated 2016-05-10

The CDN and download packages have a badge that displays whatever version is being offered by those links. How come the Build Customizer doesn't have that?

**Comment by JayAdra** [comment]
+1 This needs to be either updated at the time of release, or a note with the version it is using needs to be displayed on the page.

Would be great to see this fixed soon.

**Comment by acshef** [comment]
Update: 4.4.1 is available, and the Build Customizer version is still at 4.3.12.

**Comment by acshef** [comment]
Update: 4.4.3 is available, and the Build Customizer version is now at 4.4.1 (still out of sync)

**Comment by acshef** [comment]
This issue can be closed -- the Build Customizer appears to be in sync with the current version. **However,** I have to ask: has anything changed to ensure this issue won't come up again? This has happened a few times already.

**Comment by Afraithe** [comment]
Yes the service has been replaced so it should function better now from the webpage.
