### ISSUE TITLE
Anchor title trimming off  when blank

### ISSUE THREAD

**Issue by bsunilkumar** [tinymce/tinymce#3058]
Anchor tag title value  is trimming when there is a blank value below is the code snippet

```
<!DOCTYPE html>
<html>
<head>
  <script src="http://cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>tinymce.init({ 
  
  selector:'textarea',
  plugins: 'code',
    valid_elements: "*[*]",
	extended_valid_elements : "*[*]"
  });</script>
</head>
<body>
  <a title="" href="https://www.google.com/">google</a>
  </textarea>
</body>
</html>
```

Output:
`<a title href="https://www.google.com/" data-mce-href="https://www.google.com/">google</a>`

Expected Output:

`<a title="" href="https://www.google.com/" data-mce-href="https://www.google.com/">google</a>`

**Comment by spocke** [comment]
How do you get the content out from the editor?

**Comment by bsunilkumar** [comment]
Thanks for the reply.

I did right click on the "link" and click on "inspect"  Please find the attached images.

![tinymce1](https://cloud.githubusercontent.com/assets/8065615/16933062/0102a926-4d8e-11e6-83b2-65d67148d200.JPG)
![tinymce2](https://cloud.githubusercontent.com/assets/8065615/16933061/00fcaecc-4d8e-11e6-89de-178a736c58bb.JPG)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
