### ISSUE TITLE
Why not package languages?

### ISSUE THREAD

**Issue by guoyunhe** [tinymce/tinymce#3059]
Currently, if we want to use localization, we have to download these translation files by hand, which is not so convenient.

**Comment by emanuelschuetze** [comment]
We (from OpenSlides) created a tinymce-i18n repository to install all tinymce languages via bower:
https://github.com/OpenSlides/tinymce-i18n
But note: We does not maintain/coordinate the translations and does not update the language files if something changed in http://archive.tinymce.com/i18n/. It's just a temporary respository which we will delete if tinymce provide an official i18n repo.

Tinymce team: Can you provide such a tinymce-i18n repo to install it via bower?
