### ISSUE TITLE
fullpage_default_font[_]size

### ISSUE THREAD

**Issue by tapotu** [tinymce/tinymce#3060]
Version 4.4.0 - fullpage plugin - default font size
The documentation says fullpage_default_fontsize but it doesn't seem to be interperted. When I try the older fullpage_default_font_size (underscore between font and size) the default font size is set the body's style attribute.

**Comment by lnewson** [comment]
This appears to have been an issue with our documentation and was fixed at some stage in the past, as both the [TinyMCE 4](https://www.tiny.cloud/docs-4x/plugins/fullpage/#fullpage_default_font_size) and [TinyMCE 5](https://www.tiny.cloud/docs/plugins/fullpage/#fullpage_default_font_size) documentation now correctly use `fullpage_default_font_size`.
