### ISSUE TITLE
Possible bug - Formats (styleselect) tooltip not showing

### ISSUE THREAD

**Issue by fernandodof** [tinymce/tinymce#3064]
Hello,

I noticed that all the buttons on the editor toolbar have a tootip, exept the "Formats" button.
Has this bug already been addressed ? (is it a bug ?) 

Example: https://www.tinymce.com/

Thanks.

**Comment by spocke** [comment]
The formats button already have a visual text label so it doesn't have a tooltip since it would have the same information.

**Comment by fernandodof** [comment]
Thanks @spocke thats what I wanted to hear.
