### ISSUE TITLE
TinyMce not working in IE 11. Im using version 3.4.4

### ISSUE THREAD

**Issue by gladiator99** [tinymce/tinymce#3065]
TiinyMce editor is not loading in IE 11. Loading okay in Chrome and Firefox. I have implemented following version in my solution. Please help. thanks. 

majorVersion:"3",minorVersion:"4.4",releaseDate:"2011-08-04"

**Comment by ankitjs** [comment]
In my case, it is working when I work on localhost, but when i deployed it to server, TinyMce editor is not loading and gives error " Object doesn't support this action  " at line:36415. it is working fine with edge provided with window 10.1

lines in tinymce.js are:   Theme = ThemeManager.get(settings.theme);
					self.theme = new Theme(self, ThemeManager.urls[settings.theme]);

**Comment by NatalieFrecka** [comment]
I'm having the exact same issue as @ankitjs in the version I downloaded from tinymce.com. Says it's version 4.6.4 (2017-06-13). Works in Chrome, Safari, Firefox, and locally on IE11, but once it's in dev or prod IE11 throws a SCRIPT445 Object doesn't support this action error.

My version is minified, but it appears to be on the same lines as previously mentioned.
`a.theme=new b(a,g.urls[c.theme])`

**Comment by tinydylan** [comment]
Hi,

TinyMCE 3 is no longer supported, and TinyMCE 4 is reaching its end of life. Please see our list of [supported versions](https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/#supportedtinymceversions).

I tested several versions of TinyMCE on http://fiddle.tinymce.com/ in IE11, including 4.6.4, 4.9.9 and 5.2.2 and I am unable to reproduce any errors.

If the issue persists, are you able to please produce a simple self-contained example demonstrating the issue, and send the files or URL? 

As I'm unable to reproduce any errors, this issue will be closed. Please let us know if any issues persist and we will re-open and investigate.

Thanks!
