### ISSUE TITLE
Deleting from end of line in nested list leaves orphan li

### ISSUE THREAD

**Issue by Jeff-14159** [tinymce/tinymce#3067]
I'm noticing some strange behavior when deleting from the last position of a nested list....
............................................
1. Test
2. Test*
.....A. Test
.....B. Test
..........I. Test
..........II. Test
.....C. Test
3. Test
.......................................................
If I where to put my cursor at the **end** of "_2. Test_" and press delete it moves the text from the next LI up into the active node however it leaves an empty orphaned LI that cannot be selected.... this seems to only happen when there is **3+ levels** deep OL.... if you try this from "_2.B. Test_" the normal behavior happens and the first child is rolled up into the parent.

using 4.4.0 & IE 11

**Comment by Jeff-14159** [comment]
Thought I would add a video on here too to show the issue to help it get verified sooner :) 
Also notice at  00:28  the breadcrumb is showing  _ul>ul>li>ul_  .... I think there should still be a _li_ between each _ul_....

[TinyMCE deleting with 3 levels deep.zip](https://github.com/tinymce/tinymce/files/372212/TinyMCE.deleting.with.3.levels.deep.zip)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
