### ISSUE TITLE
Width 100% handle overflow issue

### ISSUE THREAD

**Issue by JayAdra** [tinymce/tinymce#3070]
I have an editor which has a set width (980px), with no padding/margin/border on the left or right sides, so as to display a true representation of what the user will see when previewing their work. For example, the bottom of the editor may look like this:

![table-1](https://cloud.githubusercontent.com/assets/2704964/16942164/efdd33b0-4dd7-11e6-8ca4-5e546d42ee8b.JPG)

The problem I have is with images, tables, video etc. (anything which can be resized). The handles get cut off when the object has a width of 100% and a horizontal scrollbar appears, as can be seen below:

![table-2](https://cloud.githubusercontent.com/assets/2704964/16942185/10d4427a-4dd8-11e6-901e-99a40b686877.JPG)

Does anyone know of a way around this or is there a setting which can control this? Either placing the handles within the container or increasing the container size, but wrapping its content?

I've tried everything I can think of but have had no success. Thanks.

**Comment by spocke** [comment]
You can avoid this by having a margin inside the element so that the resize handles fit. We currently don't crop the resize handles if they don't for nor do we constrain them further maybe we should.

**Comment by JayAdra** [comment]
I thought of this, but didn't want to shrink the width of the content wrapper at all (even if by ~5px), to ensure the "editor" showed an exact preview of the layout in its final form. If it was 975px wide instead of 980px, the breaks in lines/words may be different and cause differences.

I may just have to live with the small discrepancy if there are no ways to achieve this.
