### ISSUE TITLE
Kind of scroll bug in inlite theme

### ISSUE THREAD

**Issue by ozgrozer** [tinymce/tinymce#3071]
In this sample everythings great. Editor works seamlessly.
[http://codepen.io/anon/pen/zBRajX](http://codepen.io/anon/pen/zBRajX)

But when I give it `margin-top`
[http://codepen.io/anon/pen/xOYzjv](http://codepen.io/anon/pen/xOYzjv)

or if there are `<br>` tags above it, the editor doesn't work.
[http://codepen.io/anon/pen/mEXKKO](http://codepen.io/anon/pen/mEXKKO)

This scroll bug only seems in inlite theme. There is no problem in modern theme.

**Comment by spocke** [comment]
Fixed this issue in the master branch. It's currently not released so either build tinymce from the github source or wait for the nightly build to help us verify that this bug has been resolved. Thanks.
