### ISSUE TITLE
Including Web Components JS polyfills on the same page as TinyMCE 4.3.3 causes text justify controls to break in FireFox

### ISSUE THREAD

**Issue by gbdrummer** [tinymce/tinymce#3073]
When one of the webcomponentsjs polyfills is loaded in the `<head>`, before or after tinymce.js, if you attempt to use the Justify Left, Justify Center, or Justify Right controls in a shared TinyMCE toolbar, FireFox will throw this error:

``` console
15:08:33.236 TypeError: e is undefined 

p() webcomponents-lite-pack-1468867145000.js:2
A.prototype.create() tinymce-pack-1468867145000.js:1
aJ() tinymce-pack-1468867145000.js:1
at() tinymce-pack-1468867145000.js:1
V() tinymce-pack-1468867145000.js:1
Q() tinymce-pack-1468867145000.js:1
["JustifyLeft,JustifyCenter,JustifyRight,JustifyFull,JustifyNone"]() tinymce-pack-1468867145000.js:1
M() tinymce-pack-1468867145000.js:1
A.prototype.execCommand() tinymce-pack-1468867145000.js:1
A.prototype.addButton/aa.onclick() tinymce-pack-1468867145000.js:1
n() tinymce-pack-1468867145000.js:1
p.fire() tinymce-pack-1468867145000.js:1
J() tinymce-pack-1468867145000.js:1
w() tinymce-pack-1468867145000.js:1
F() tinymce-pack-1468867145000.js:1
1 webcomponents-lite-pack-1468867145000.js:2:1332
```

The source of the error seems to be tinymce.js line 18840:

``` JS
wrapName = format.inline || format.block;
```

Both `format.inline` and `format.block` return `undefined` in some cases (I'm not aware of all the cases in which this may happen). As a temporary fix I amended that line to be:

``` JS
wrapName = format.inline || format.block || format.defaultBlock || 'span';
```

When the webcomponents polyfills are not included on the page, the problem does not occur; From what I can tell, the conflict appears to happen when `document.createElement()` is called by TinyMCE and passed an argument of `undefined`.

**Comment by nyroDev** [comment]
I have the same problem.

**Comment by archonic** [comment]
Ditto
