### ISSUE TITLE
elementpath display in next statusbar?

### ISSUE THREAD

**Issue by bright-pan** [tinymce/tinymce#3074]
the tinymce version is v4.40, i use it for multi tinymce object in one page, 

but i found the elementpath display in the statusbar of next tinymce object.

![a](https://cloud.githubusercontent.com/assets/463740/17020593/0a2ec686-4f75-11e6-87c5-58fbf30392d5.png)

**Comment by spocke** [comment]
Duplicate of #3066 #3046

**Comment by bright-pan** [comment]
thanks
