### ISSUE TITLE
Required http:// prefix message

### ISSUE THREAD

**Issue by ozgrozer** [tinymce/tinymce#3077]
http://codepen.io/anon/pen/zBRajX

After I select a text I'm typing an URL like "http://google.com" or "http://www.google.com" to the insert link box but I'm getting this message "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?".

I already added the http:// prefix but even though it says me "do you want to add". Is it a bug or is there a way to hidden that message?

**Comment by jayarjo** [comment]
Your codepen doesn't seem to load. TinyMCE has its own playground here: http://fiddle.tinymce.com/. You can fork default example and put up your case. 

I was not able to replicate this problem in Chrome 51, Mac OS X, TinyMCE 4.4.0.

**Comment by ozgrozer** [comment]
There is no problem in my codepen. It's working. Maybe you didn't notice that I'm using inlite theme. Here's a screenshot what the problem is.

![screen shot 2016-07-24 at 16 31 34](https://cloud.githubusercontent.com/assets/651938/17084053/d46d7c82-51bc-11e6-9e53-109b3cbb6876.png)

**Comment by spocke** [comment]
Fixed this issue in the master branch. It's currently not released so either build tinymce from the github source or wait for the nightly build to help us verify that this bug has been resolved. Thanks.
