### ISSUE TITLE
 remove iframe width & height

### ISSUE THREAD

**Issue by DrDeath72** [tinymce/tinymce#3079]
```
plugins: 'media',
valid_elements : 'span,iframe[!src|width|height|frameborder:0|allowfullscreen]',
```

when insert youtube iframe, width and height removed, if remove "span" from valid_elements , all ok
http://codepen.io/anon/pen/kXJEkQ

**Comment by jayarjo** [comment]
Does it happen in a specific browser? I cannot replicate it in Chrome on Mac.

**Comment by DrDeath72** [comment]
vivaldi

**Comment by jayarjo** [comment]
Ok so the problem is, that it removes width/height from source code listing under `Tools > Source Code`. Sorry wasn't clear from your first comment.

**Comment by DrDeath72** [comment]
i think it's not `code` plugin bug, when you add to config
```
setup: function(editor) {
	editor.on('change', function() {
		editor.save();
	});
}
```
and type content without open `code` width&height clean to... it's valid_elements cleanup bug

**Comment by DrDeath72** [comment]
`span[*]` looks like fix problem but not secure...

**Comment by jimmyhchan** [comment]
Hello from the future. Thanks for filing this bug so long ago and for the workaround.

It seems `span[*]` can be made more specific `span[contenteditable:false|data-mce-object|class|data-mce-p-frameborder|data-mce-p-frameborder|data-mce-p-allowfullscreen|data-mce-p-src]`  https://codepen.io/jimmyhchan/pen/rNVKPJe and `extended_valid_elements` may allow one to limit this to the instance that need it.

**Comment by D4rkSeeds** [comment]
Hi there, after hours of debugging and trying the solution with span[*] i found another point of attention in the configuration. If you set valid_classes options, span[*] is inoperent. In exemple, I had to remove this for valid_classes: { 'span': 'smt'} in order to make span[*] works

**Comment by lsycxyj** [comment]
So why does span rules remove iframe's attributes? This bug has been a long time.

**Comment by aka-wintermute** [comment]
It looks like it is interference between the Content filtering options and the Media plugin. The latter uses temporary additional markup in [media_live_embeds](https://www.tiny.cloud/docs/plugins/opensource/media/#media_live_embeds) mode to display the iframe preview, which is removed by the filter.

A possible workaround (sort of) is to disable this mode: 
`media_live_embeds=false`

**Comment by aka-wintermute** [comment]
> It seems `span[*]` can be made more specific `span[contenteditable:false|data-mce-object|class|data-mce-p-frameborder|data-mce-p-frameborder|data-mce-p-allowfullscreen|data-mce-p-src]` https://codepen.io/jimmyhchan/pen/rNVKPJe and `extended_valid_elements` may allow one to limit this to the instance that need it.

When using `valid_classes`, you must also add `'span': 'mce-preview-object mce-object-iframe, mce-shim'` to the list
