### ISSUE TITLE
Update image error in MS Edge

### ISSUE THREAD

**Issue by sharpchi** [tinymce/tinymce#3083]
Using TinyMCE 3.5.11 and Windows 10 (with MS Edge) IE11 works ok, as do other browsers. Tested on http://archive.tinymce.com/tryit/3_x/full.php

When updating an image in the textarea using the Insert/edit image button, an image gets duplicated - see screenshots.
1. Click "Insert/ edit image" button in menu
2. Select image
3. Add description
4. Click "Insert"
5. In the text editor, select the inserted image
6. Click on the "Insert/ edit image" icon again (not the context menu item)
7. Click Update
8. There are now two images

![tinymce](https://cloud.githubusercontent.com/assets/3774280/17135784/520e2fc0-5329-11e6-8a65-b8df463874bf.png)

**Comment by lnewson** [comment]
Hi,

Thanks for the report, however I'm sorry we no longer support TinyMCE 3. At this time TinyMCE 5 is our supported version, however we're still fixing major issues identified in the latest version of TinyMCE 4. So it's our recommendation to upgrade to a newer version if you're still having issues, as it's likely been fixed given the age of this issue.

Thanks!
