### ISSUE TITLE
Disable insert_toolbar

### ISSUE THREAD

**Issue by ozgrozer** [tinymce/tinymce#3087]
http://codepen.io/anon/pen/PzaJJY

I'm trying to disable `insert_toolbar` in inlite theme. I looked at the [API page](https://www.tinymce.com/docs/configure/editor-appearance/#insert_toolbar) but there is nothing to help. I tried some methods like `insert_toolbar: ""` or `insert_toolbar: false` but they didn't work. So how can I disable it?

**Comment by spocke** [comment]
Yes, an empty or false should disable the toolbar. Currently it doesn't support this. Will look into this.

**Comment by NitroBAY** [comment]
+1 I tried both and none works for now.

**Comment by ozgrozer** [comment]
@NitroBAY it works now.

**Comment by NitroBAY** [comment]
Thanks and congrats for this plugin and your reactivity.

**Comment by Flobin** [comment]
I am actually still having this issue. Using tinymce 4.5.1 through NPM. My tinymceconf:

    var tinymceConf = {
      selector: '.tinymce',
      inline: true,
      theme: 'inlite',
      selection_toolbar: 'undo redo | h2 h3 | bold italic | bullist numlist | blockquote | removeformat',
      insert_toolbar: false,
      menubar: false,
      statusbar: false,
      schema: 'html5',
      max_height: 500,
      max_width: 500,
      min_height: 100,
      min_width: 400,
      content_css: '/static/articles/build/css/tinymce.css',
    }

But the insert_toolbar still appears. There's a git repo [here](https://github.com/Togethere-com/togethere/tree/b1d82f36f8a8557ba4fd68de5fa14db5a4d37a7a) that shows it.

**Comment by dougdot3** [comment]
Has this issue been solved? It still seems to occur in the latest version.

**Comment by NitroBAY** [comment]
For me it did work.

**Comment by dougdot3** [comment]
But even in their code sample if you change to false it doesn't work:

https://codepen.io/tinymce/pen/Gqmkja

From console, am on 

tinymce.majorVersion + '.' + tinymce.minorVersion
"4.6.3"
