### ISSUE TITLE
Do not delete the image while it is on a new line

### ISSUE THREAD

**Issue by cmoneverybody** [tinymce/tinymce#3096]
Hello.
Do not remove the image by **backspace** while it is on a new line.
See demo:
http://codepen.io/anon/pen/GqBXVG
and screens:
![1](https://cloud.githubusercontent.com/assets/7736571/17277127/46476b92-5744-11e6-8abb-bbe527cb00b2.png)
![2](https://cloud.githubusercontent.com/assets/7736571/17277128/464a6a9a-5744-11e6-8019-19db7a1eeb4f.png)

**Comment by tinydylan** [comment]
Hi,

I am unable to reproduce this issue in the latest version of TinyMCE. I believe the issue has been corrected. If the issue comes back, please let us know.

Thank you!
