### ISSUE TITLE
Font size shown in drop down list is not correcct

### ISSUE THREAD

**Issue by majidzn** [tinymce/tinymce#3099]
1 - I have a text in Tinymce editor with diffrent font size.for example, font size of the first line is set to 12pt, font size of the second line is set to 20pt and font size of the last line is set to 34pt.

2 - When select all the text, tinymce chooses one of the 12pt,20pt or 34pt items in the font size drop down list on toolbar Randomly, while it has not choose any item of the font size list.

 i want no item select like MS Word, how can i change it?
Is it a bug? How can i fix it?

**Comment by jayarjo** [comment]
https://github.com/tinymce/tinymce/issues/3016
