### ISSUE TITLE
IE bullet point editing

### ISSUE THREAD

**Issue by adeansworth** [tinymce/tinymce#3111]
Hi all,
We're having an issue in IE when it doesn't perform the same as Chrome when adding bullet points then going back to edit them.

The way to create this issue is add some bullet points using ie then highlight the text and click the bullet point button again.

In Chrome the bullet points get removed similar to any other word editor. In IE the button does nothing.

Is there a fix already available for this?

Thanks in advance

**Comment by spocke** [comment]
Couldn't reproduce this in IE 11 make sure that you have the lists plugin enabled. Also please provide a fiddle and detailed steps for us to reproduce it. Thanks.
