### ISSUE TITLE
NS_ERROR_UNEXPECTED Errors in FireFox

### ISSUE THREAD

**Issue by duranmg** [tinymce/tinymce#3113]
I keep getting these errors when running in firefox.  A good example is the github project sukobuto/aurelia-tinymce-sample.  Just run  it and swtich between the menu options and you will see the errors.

The errror is on line 13330 of tinymce.js

```
impl = node.ownerDocument.implementation;
```

and the error is 

```
[Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: debugger eval code :: <TOP_LEVEL> :: line 1"  data: no]
```

**Comment by spocke** [comment]
Could be this line:
https://github.com/sukobuto/aurelia-tinymce-sample/blob/master/src/feature-tinymce/tiny-mce.js#L70

Should probably be remove not destory since it's mostly an internal api call. I wasn't able to build that project so I couldn't test this my self.

**Comment by duranmg** [comment]
hmmm i was able to build and run the project ...  
npm i
jspm i
gulp build
npm start

then got to http://localhost:3000

**Comment by duranmg** [comment]
And I updated my original comment with more info about where the error is occurring and the error message.  It has something to do with the browser...

**Comment by duranmg** [comment]
I created my own demo project at https://github.com/duranmg/demo-aurelia-tinymce

I get the same error in Firefox as stated in my earlier comment.

And I don't understand why when I use **this.editor.remove()** the editor seems to stop working.  It just shows the textarea without the editor on it.  It will work if I use **tinymce.remove()**.  My guess it has something to do with Aurelia.

**Comment by IntellectProductions** [comment]
I'm getting the same error when using `tinymce.remove()` or `tinymce.remove(editor.id)` or `tinymce.EditorManager.get(editor.id).remove()` ... it's only in Firefox. It works great in Chrome and everywhere else.. :/
