### ISSUE TITLE
Allow inline editor to target element within an iframe

### ISSUE THREAD

**Issue by chiefego** [tinymce/tinymce#3117]
We are working on an authoring tool that needs an inline editor that targets elements within an iframe to take advantage of proper font resizing. When passing the iframe element via settings.target it triggers events to the editor but not from the editor. Not sure if this is supported as of now.

**Comment by chiefego** [comment]
Ok - after digging around it seems this works when configuring Tiny like so:

```javascript
tinymce.init({
        target: target[0], //target element within the iframe,
        content_window: self.$iframe[0].contentWindow,
        content_document: self.$iframe[0].contentWindow.document,
        menu: {},
        plugins: "textcolor colorpicker",
        toolbar: 'undo redo | bold italic | bullist numlist | alignleft aligncenter alignright alignjustify | link | fontselect fontsizeselect | forecolor',
        inline: true,
        fixed_toolbar_container: "#editor",
        fontsize_formats: "2vw 4vw 6vw 8vw 10vw 15vw 20vw 25vw 30vw 35vw 40vw 45vw 50vw",
});
```
This works well. The only issue we have now is that when using either of the combo boxes (font-family, font-size) and selecting a value the editor looses focus and auto hides. It does not do that when applying other formats such as alignment, font-weight or lists.
Any thoughts?

**Comment by mansooraziz** [comment]
what is target[0] in this case? I have a document which in which I want to edit certain parts i.e. '*[data-editable="true"]' but it doesn't seem to work when I use iframe.

**Comment by niklaswulff** [comment]
@chiefego Did you solve this? I am facing the same issue and your comment on 15 sep 2016 is somewhat vague. Could you post a more complete code? Thanks!

**Comment by VitaliyOnRule** [comment]
@niklaswulff hello from 2020) Did @chiefego answer?)

**Comment by lostkeys** [comment]
Unfortunately this is not something we have any plans to fix. The options were added a long time ago as private APIs but had all sorts of issues, mainly memmory leaks so they were not carried over to TinyMCE 5. What is preventing you from just running TinyMCE inside the iframe?
