### ISSUE TITLE
Conditional comment handling adds a space

### ISSUE THREAD

**Issue by jasonsamuels** [tinymce/tinymce#3119]
An extra space added to conditional comments wreaks havoc with an HTML email template.

Pasting HTML source code in to TinyMCE results in the following change:

`<!--[if (gte mso 9)|(IE)]>

_becomes_

<!-- [if (gte mso 9)|(IE)]>`

The extraneous space after the fourth character causes Microsoft Outlook to disregard conditional comments which are supposed to constrain content block widths in that email client. Here's what happens as a result:

[Test result before TinyMCE](https://www.emailonacid.com/app/acidtest/display/summary/LiYq3Ai4J8zQn6reERTOlZnCpmVG5ddtUQiU1aOqd6Gm9/shared)
[Test result after TinyMCE](https://www.emailonacid.com/app/acidtest/display/summary/5HWGYJfTpsjzNNiYoHcA0X8Ebv6ulZufwZ9BtnGYA0Mrr/shared)

**Comment by spocke** [comment]
I think this can be avoided by:
https://www.tinymce.com/docs/configure/content-filtering/#allow_conditional_comments

By default they are stipped/modified since they might produce a xss security issue. Also the are not valid html so you might need to fiddle with:
https://www.tinymce.com/docs/configure/content-filtering/#protect

**Comment by spocke** [comment]
Closing since this seems more of a question than a bug. Will re-open if you think otherwise.Thanks.

**Comment by jasonsamuels** [comment]
Thank you for the quick reply and the pointer. I tried changing the Allow Conditional Comments setting via the demo on Codepen and it does seem to prevent the issue. Am now working through the process of getting our member database vendor to change it so I can test on that production system.
