### ISSUE TITLE
inline mode toolbars/menu bar not responsive

### ISSUE THREAD

**Issue by Jeff-14159** [tinymce/tinymce#3121]
The toolbar/menu bar is responsive and wraps when it is in an iframe....  but when it is in the inline mode they do not wrap? this makes is difficult to use on small screens.  

is there some workaround or style than can be applied to make the toolbar groups wrap?

![tinymce hidden buttons](https://cloud.githubusercontent.com/assets/8378376/17574063/5f51a6d0-5f2c-11e6-860f-5bc30edf8b0c.png)

IE 11.0.9
TinyMCE 4.4.0

**Comment by donShakespeare** [comment]
Try https://github.com/donShakespeare/tinymceBubbleBar

**Comment by lnewson** [comment]
Hi,

This should be resolved with TinyMCE 5, as it's inline menu bar/toolbar will wrap when used on smaller viewports. It also has the new [Toolbar Drawer](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_mode) feature which can allow items to be collapsed into a secondary toolbar that displays when clicking the "More" button. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!
