### ISSUE TITLE
Imposed Styles

### ISSUE THREAD

**Issue by JerrodV** [tinymce/tinymce#3126]
In the nature of my app, I need the user to be able to drag a data filled html node to a canvas. When that happens, I need to be able to read my data and create the initial style tiny will allow text editing in. 

The obvious method is to use setContent which responds very well to my command, assuming I have content. However, I see a flaw that is made apparent by me attempting to impose no content and also maintain my styles.

If I leave html validation on, which I would like to, because you're awesome at it, I can't make the editor do what I want. See: http://stackoverflow.com/questions/34981402/tinymce-4-apply-one-block-format-to-new-blocks-automatically/38485800#38485800 

- I am stickman. Please note my [UPDATE]
Can we make it so that second backspace does not kill my styles? I think there is a strong use case here. My goal would be to be able to load content, then have it validated later. So we can pass "<p><span style"..."></span></p>" in setContent allowing the user a predefined style set into an existing tiny instance.  Also, I would like for the editor not to see the potential backspace that kills the current style. If I pass the same html to the editor, and place an &nbsp; in the span, That is when I get the right results, with the backspace problems. If the user wants their style removed, we have that button. I'm not sure why the style killing backspace is allowed, foremost. 

Validation on a toggle would fix it all. It is easy to see if it changed, and if it's new. I feel like I (me) should detect these things, then validate... seems reasonable atm. I realize you need structure to make things work though. Any edit to nothing is something though. Maybe validation can be deferred?.. if anything changes but focusContentLenght is 0 and key =="backspace", don't validate? 
User setting? Validate empty html?.. (Better)ExcludeEmptyNodes = false...?

Thanks for the read.

**Comment by spocke** [comment]
This ticket seems to be more of a general support question rather than a bug/feature request. Please use the community forums or register for an Enterprise license for commercial support. Thanks.
