### ISSUE TITLE
Inline toolbar can overlap modal dialog [Chrome & Firefox]

### ISSUE THREAD

**Issue by metricjs** [tinymce/tinymce#3127]
Using the TinyMCE Fiddle (version: edge), it's possible for an inline toolbar (e.g. the table menu) to overlap a modal dialog (e.g. Source Code). See the attached screenshot. Replicated in Chrome and Firefox.

Steps to reproduce:
1. Open a fiddle and insert a table
2. Move your cursor into a table cell so the inline table toolbar opens
3. Open the Source Code dialog
4. Click on the grey background outside the Source Code dialog
5. Press tab

Expected result: Nothing changes, except maybe the focus
Actual result: The table toolbar appears above the Source Code dialog and the grey background.

![table context dialog overlap](https://cloud.githubusercontent.com/assets/4361382/17653322/ef5c81f2-62d6-11e6-8aee-3120b43f1eb3.png)

**Comment by lnewson** [comment]
This appears to have been fixed, as I can't reproduce it in TinyMCE 4.9.10 or 5.2.2.
![Selection_193](https://user-images.githubusercontent.com/1575550/81470371-cf75aa00-922d-11ea-825f-9104230f9539.png)
