### ISSUE TITLE
cE=false eventless in 4.4+ and 5+, worked in 4.3

### ISSUE THREAD

**Issue by TinoDidriksen** [tinymce/tinymce#3132]
iOS/Android: We dynamically add in some cE=false popups with jQuery-bound click events on them. In 4.4, these events no longer bubble through to the element. They work fine in 4.3.

Discovered this as we were using the CDN /4/ and it suddenly broke. Changed to /4.3/ and it all works again.

**Comment by jayarjo** [comment]
@TinoDidriksen could you help us by creating a test case for this on CodePen?

**Comment by TinoDidriksen** [comment]
Test cases:
- https://codepen.io/anon/pen/oWGpyK - works, version 4.3 - shows the alert on tapping the element in the editor
- https://codepen.io/anon/pen/ybzpWq - doesn't work, any version after 4.3, here set to 4.6

Tested just now with latest Android versions of Firefox and Chrome.

**Comment by TinoDidriksen** [comment]
Looks like I can work around the issue with `touchend` as mentioned in https://github.com/tinymce/tinymce/issues/5386 - can finally upgrade from v4.3.
