### ISSUE TITLE
empty line after paste

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#3136]
steps:
1)type multiline text
2) set cursor before string
3) select few string with "shift+down"/ "shift+up"
4)make cut
5) make paste

really: empty string after text

see: https://www.youtube.com/watch?v=yt1timSzT_8&feature=youtu.be

**Comment by spocke** [comment]
This has to do with how webkit/blink produces ranges:
This is the range: <p>[a</p><p>]b</p>
This the range it should be: <p>[a</p>]<p>b</p> or even <p>[a]</p><p>b</p>

We could also potentially trim the content being pasted so if it looks like:
<p>a</p><p></p> we simply remove that empty P.

**Comment by PetrBorisov** [comment]
@spocke trim emty P  would be cool
