### ISSUE TITLE
Native Chrome spellcheck acting weird in TinyMCE

### ISSUE THREAD

**Issue by kokoglen** [tinymce/tinymce#3139]
Intermittant problem (I hate those)

We have TinyMCE set to use Chrome's native spellcheck. I am getting wavy red lines in bizarre places that don't even map to dom nodes. The words aren't even spelled incorrectly. This happens some of the time, but not all of the time.

Also, sometimes I will write a word incorrectly spelled and the red squiggly line doesn't show up at all. Then it does, then it disappears.

![image](https://cloud.githubusercontent.com/assets/62608/17826747/d00c24b0-6628-11e6-9a3d-f41f65dc222e.png)

What can we do?
Thank you,

**Comment by spocke** [comment]
Yes, this is why the native spellchecker is disabled by default. It simply doesn't work and there is no way for us to fix it.
