### ISSUE TITLE
how to delete inserted template in tinymce

### ISSUE THREAD

**Issue by techno-serv** [tinymce/tinymce#3143]
Is there any plug in available in tinymce to delete the inserted template?

**Comment by spocke** [comment]
Not really you can put it in a contentEditable="false" block or nonediable and then it will be one big unit that you can delete using backspace or the delete key.

**Comment by techno-serv** [comment]
Like template if I have created new plugin for "delete template".
I have used the command "mceRemoveNode" to delete the template in submit function.
But its not working.

**Comment by androb** [comment]
@techno-serv what is the goal you were trying to achieve here? It sounds like you wanted to remove some content when the editor was submitted? 

Given this issue is 2 years old I am going to close this, but feel free to re-open it if it is still an issue for you.
