### ISSUE TITLE
body_class doesn't work

### ISSUE THREAD

**Issue by erionalite** [tinymce/tinymce#3144]
the body_class doesn't work. 

The class name does get added to the html, but the browser doesn't apply the css of the matching class to the body_class value. This is happening in chrome. 

Anyone noticed this ?

**Comment by spocke** [comment]
Use the chrome style inspector and see if there is conflicts with styles. If the class is there it's an implementation detail if the CSS isn't properly applied. This isn't a bug or feature request so I'm closing this one.

**Comment by erionalite** [comment]
I actually was able to make it work. Since the body of the tinymce is in the iframe, you can't just apply site css styles to the class. 

I had to move my custom class into it's own css file then have to set the path to the content_css to my new css file in order for the styles to get applied. 

The documentation in my opinion needs to state that more verbosely about this detail. The documentation implies that one can just add the body_class and the styles will be applied, which is not true. .
