### ISSUE TITLE
While working with tinymce 4.3.3 in latest chrome gives a warning message

### ISSUE THREAD

**Issue by gaut4m** [tinymce/tinymce#3145]
"'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details."
The line where the warning message is generated is tinymce.js line 759.
Although I could not see Tinymce using keyIdentifier anywhere but wanted to confirm

**Comment by spocke** [comment]
It clones the event by looping it's keys and when that happens these warnings appear. We black list them one by one and this one has been added to the list since that release. Thanks for reporting though.

**Comment by goldandsilver** [comment]
Does this mean that tinymce will continue to work even after September 2016 even if we are using tinymce version 4.3.3 with events like 'onKeyUp'?

**Comment by mluyties** [comment]
This issue affects me as well. Can we get clarification that after September TinyMCE will continue to work normally or will an upgrade be released that we need to migrate to?

**Comment by gaut4m** [comment]
The issue is not showing up on 4.3.11 and newer so you guys can upgrade to any version after 4.3.11

**Comment by rafaelmaciel** [comment]
Hi, in 4.3.12 this issue continues.

**Comment by taltas** [comment]
Tried it on Canary with Chrome 55. Works fine for me.

**Comment by spocke** [comment]
All those warnings about using deprecated stuff can be ignored. It's reported since we clone all properties of the event and when that clone is done it the warning is passed out.
