### ISSUE TITLE
Can't manually focus an inline editor

### ISSUE THREAD

**Issue by taberrr** [tinymce/tinymce#3149]
Hi all, I'm trying to call .focus() on an inline instance of the editor but it isn't focused. I was able to reproduce it using one of your codepen examples: http://codepen.io/tinymce/pen/YydQoj

Just open the web inspector/console, set the context to "CodePen (index.html)" and add:
`tinymce.editors[0].focus();` - nothing happens, no errors, and the editor isn't focused. No toolbar appears, etc.

However, if I use `auto_focus: true` in the .init, the editor is indeed focused on page load. Not sure what the discrepancy is here, but it seems like a bug to me.

**Comment by spocke** [comment]
The chrome console has special focus it works if there is buttons on the page doing the focus. Not much we can do about this though since it's up to chrome if they want to allow focus to be dropped from the console or not.

**Comment by taberrr** [comment]
Jeeze, can't believe I didn't realize that. Sorry for the false alarm.
