### ISSUE TITLE
Inlite theme ignores skin_url property ?

### ISSUE THREAD

**Issue by NitroBAY** [tinymce/tinymce#3152]
js/tinymce/themes/inlite/src/main/js/tinymce/inlite/core/SkinLoader.js doesn't seems to care about skin_url init property...

**Comment by spocke** [comment]
Fixed and released in 4.4.2.

**Comment by NitroBAY** [comment]
Wahou THANKS and CONGRATULATIONS for such reactive response. +1 (I didn't test already)
