### ISSUE TITLE
Allow configuration for window dimensions of `codesample` plugin

### ISSUE THREAD

**Issue by pesla** [tinymce/tinymce#3154]
The `codesample` plugin opens a rather large window, which — in some contexts — is too large, making it impossible to save its contents. For example, we've got custom dialogs containing editors. The window spawned by the plugin has a `min-height` of `650px` which is taller than our dialog, making the bottom part of the window disappear.

An easy solution might be to allow users to config the dimensions of the window (in [Dialog.js](https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/codesample/classes/Dialog.js)):

```javascript
editor.windowManager.open({
	title: "Insert/Edit code sample",
	minWidth: Math.min(DOM.getViewPort().w, 800),
	minHeight: Math.min(DOM.getViewPort().h, 650)
)};
```

**Comment by pesla** [comment]
If you're dealing with the same issue, for now I've fixed it for all windows with listening to the `OpenWindow` event and resizing windows that fall outside the viewport:

```javascript
editor.on('OpenWindow', function (event) {
    if (!('win' in event)) {
        return;
    }

    var openedWindow = event.win;
    var windowLayout = openedWindow.layoutRect();
    
    if (!('h' in windowLayout) || !('w' in windowLayout)) {
        return;
    }
    
    var windowHeight = windowLayout.h;
    var windowWidth = windowLayout.w;
    var viewportWidth = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
    var viewportHeight = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);

    if (windowWidth > viewportWidth || windowHeight > viewportHeight) {
        var resizeToHeight = (windowHeight > viewportHeight) ? viewportHeight - 20 : windowHeight;
        var resizeToWidth = (windowWidth > viewportWidth) ? viewportWidth - 20 : windowWidth;

        openedWindow.resizeTo(resizeToWidth, resizeToHeight);
        openedWindow.moveBy(0, 10); // Vertically center
    }
});
```

**Comment by spocke** [comment]
Yes, we should probably deal with this in a more global manner. Anyway, I added configs and fixed the codesample plugin.
