### ISSUE TITLE
Right-Align button not working, same with setting "formats"

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3155]
I use setting forced_root_block: false

click on "right align", nothing change:
http://fiddle.tinymce.com/L5faab
click now "center align" and again "right align" now its working.

with setting "formats" the align (left,center,right) not working
http://fiddle.tinymce.com/M5faab
```
formats: {
    alignleft: {selector: 'p,h1,...', classes: 'myleft'},
    aligncenter: {selector: 'p,h1,...', classes: 'mycenter'},
    alignright: {selector: 'p,h1,...', classes: 'myright'},
    alignfull: {selector: 'p,h1,...', classes: 'myfull'}
},
```
Only workaround is to click on "Justify"-button, to make center or right align working. A normal user will never expect that he must first use "Justify"-button.

**Comment by spocke** [comment]
Simple answer don't use: forced_root_block: false paragraphs are fantastic.
Longer answer read the source: https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/Formatter.js#L103

There is a way to specify a default element to be generated when there is none.

**Comment by Daijobou** [comment]
Its a bug, so this ticket should not so easily closed. Nobody use in forum/comment/code software "paragraphs" that a was a really wrong answer. This comment-system in github don't use paragraphs!

Please delete support for "forced_root_block: false" at last completely as your final solution. I'm very disappointed and go to look for ckeditor. Years of development for own plugins now for nothing. :(

Justify and Center-Align buttons working but not Left- and Right-Align. What is here the problem to fix this _minor_ bug?

:-1:

**Comment by spocke** [comment]
The source had the formats you needed. You just needed to add defaultBlock: 'div' I updated the fiddle:
http://fiddle.tinymce.com/M5faab/1

Right/Center/Left align works fine in now at least in Chrome. So this is not a bug since it's working if you specify that option. I guess we could document that you need to configure that if you use forced_root_blocks: false.

**Comment by Daijobou** [comment]
Thanks that help much! :+1: 

The settings "formats" was only to find a way to fix the bug in 
http://fiddle.tinymce.com/L5faab
"Justify" and "Center Align"-Button working fine, but not the "Right Align"-Button. (Chrome)

So I will use your workaround with custom classes and "format" to bypass this bug. Thanks you.
