### ISSUE TITLE
[FEATURE] Stop making inlite stuck inside element where it's been init

### ISSUE THREAD

**Issue by NitroBAY** [tinymce/tinymce#3156]
I'm making a system where you can edit little rectangles but as my rectangles can be little, the inlite editor always hide the content thus it's nearly not usable. As an image worth 1000 words
![image](https://cloud.githubusercontent.com/assets/9869317/17973752/e690be48-6ae3-11e6-80bc-05ef4c5792d6.png)
 Thanks for you incredible work by the way.

**Comment by spocke** [comment]
This is kind of a support request but there is an undocumented option that allows you to override where the toolbar will be placed. This way you can on these very small rectangles re-position it.

http://fiddle.tinymce.com/P5faab

**Comment by NitroBAY** [comment]
Perfect. 
Maybe (but it's up to you) you should document it
