### ISSUE TITLE
Windows 10 with Edge, plus Content Security Policy blocking javascript urls

### ISSUE THREAD

**Issue by aeular** [tinymce/tinymce#3157]
With Windows 10, Edge browser, use a content security policy which prohibits javascript: urls, don't set an initial url for the iframe (a setting I couldn't find), then try to load the editor.  Editor will fail to finish its iframe due to the disallowed initial url of javascript:"".

This can be resolved by changing line 716 of js/tinymce/classes/Editor.js from
`DOM.setAttrib(ifr, "src", url || 'javascript:""');`
to
`DOM.setAttrib(ifr, "src", url || '');`

There may be other ways to do this.
Example CSP header set that will cause this:
`default-src 'self' 'unsafe-eval' http://cdn.example.net; script-src: 'self' 'unsafe-eval' http://cdn.example.net; object-src 'none'; img-src * data:; media-src 'none';`

There may be other error(s) you guys have with CSP that blocks that, however thats the major one that was breaking Edge for me.

**Comment by spocke** [comment]
This is a duplicate of #1901 so closing this one. Read up in that. Thanks.
