### ISSUE TITLE
Bug dimensions on image popup

### ISSUE THREAD

**Issue by NitroBAY** [tinymce/tinymce#3159]
Hello when I click on image btn it popup a modal with a dimensions line a little buggy. It is the same in english that in french.
![tinymce image bug](https://cloud.githubusercontent.com/assets/9869317/18013635/496e5d3c-6bbf-11e6-9db3-68993b8ba790.PNG)
If I remove the checkbox keep ratio the UI is still weird :
![tinymce image](https://cloud.githubusercontent.com/assets/9869317/18013678/81e5cf24-6bbf-11e6-9ca7-90c392875c88.PNG)
I tried on a chromium base navigator but also with Firefox, the UI is still buggy.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Could be a css conflict since I've seen no other reports and it seems to be working fine when I try it locally. Thanks

**Comment by NitroBAY** [comment]
Can't reproduce on Fiddle I'll look if my CSS could cause trouble to tinymce.
Thanks, I close the issue.
