### ISSUE TITLE
[FEATURE] Make resizing responsive or add an eventlistener onresize

### ISSUE THREAD

**Issue by ilan-schemoul** [tinymce/tinymce#3160]
I understand that tinyMCE has been built 10 years before when only a few resolutions existed and so when use of px could be imaginable but in 2016 every website should be responsive and so I think when we resize an image or whatever you shouldn't change attr width of img to X px (500px for instance) BUT add `style="width: ${newWidthOfImage / widtOfContainer } %"`. I really think you should implement that but if you don't and stuck with px (which is surprising as I built as always my entire app responsive and see images who are totally static is not common for me) could I know if  there's a event listener onImageResize.
Please note that I spent a day to implement a MutationObserver who would add automaticaly a jqueryUI resize which support options as containment (I don't want, nor my users, to let images be more important that my input/textarea/diveditable area) to finally understand that massive junk css/html/iframe makes jquery ui not possible to add resizable element in the editable area.
I truly appreciate this full editor so I did share my own thought about resizing problems instead of just asking for an event listener on stop resize.

**Comment by spocke** [comment]
Yes, we should probably support percentages on everything.

**Comment by NitroBAY** [comment]
Yes, I think there's no disadvantages in there and that  it's needed. Thanks.

**Comment by NitroBAY** [comment]
Any kind of ETA or a workaround or code of a beginning of a work ? Even something for ETA like : "not on short-plan (less than 1 month)" etc.

**Comment by NitroBAY** [comment]
@spocke or someone of the team : sorry but is there any kind of ETA or a workaround or code of a beginning of a work ? Even something like "Around a month, around 6 months, around a week etc." just to know.

**Comment by NitroBAY** [comment]
@spocke or someone of the team : sorry but is there any kind of ETA or a workaround or code of a beginning of a work ? Even something like "Around a month, around 6 months, around a week etc." just to know because it's a production project.

**Comment by NitroBAY** [comment]
@spocke any update on this ?

**Comment by NitroBAY** [comment]
@spocke any update on this ?

**Comment by NitroBAY** [comment]
@spocke any update on this ?

**Comment by NitroBAY** [comment]
@spocke sorry but may I ask you if this is on you're roadmap ?
Best regards,

**Comment by NitroBAY** [comment]
@spocke I think this feature is still very much needed. I'm surprised only one person upvoted my comment. I may create a package or share my code with the MutationObvserver method if needed.

**Comment by frankieali** [comment]
I'm facing what seems like a simple issue similar to the OP's issue. My site has a simple style to make all images responsive `img: { width: 100%; height: auto; }`. However, this will override any image width or height attributes set by a user. If the image's width and height were set in a style attribute, then this common generic style would be overridden. `width: unset` or `width:revert` will set the image to it's native size, but still ignores the user specified size.

**Comment by frankieali** [comment]
For anyone else facing this issue, I found this to work:
```
tinymce.init({
    ...
    setup: (editor) => {
          editor.on('ObjectResizeStart', (e) => {
            if (e.target.nodeName === 'IMG') {
        
              const selectedImage = editor.selection.getNode()
              editor.dom.setStyle(selectedImage,'width', e.width)
              editor.dom.setStyle(selectedImage,'height', e.height)
      
              selectedImage.removeAttribute('width')
              selectedImage.removeAttribute('height')
            }
          })
        }
      })
```

**Comment by velly** [comment]
any event to monitor the height change events? especially for inline mode?
