### ISSUE TITLE
'tinymce' is undefined in IE 8

### ISSUE THREAD

**Issue by amr1tv1rd1** [tinymce/tinymce#3167]
I am including tinymce min file in file p1 and it is initiated in file p2 (which is loaded in p1 via jquery load). Everything works fine at first when i hit submit in p2 , it is loaded again with jquery load and this error appears 'tinymce' is undefined. 

Kindly help me out

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
