### ISSUE TITLE
IE8 Can't getContent({format:'text'}) when nothing on editor

### ISSUE THREAD

**Issue by ekoneko** [tinymce/tinymce#3174]
`function replaceBlobUris(content)`  throw an exception,

the param `content` is null.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by ekoneko** [comment]
Like this: http://fiddle.tinymce.com/E6faab/1

**Comment by TheSpyder** [comment]
I'm sorry we didn't get to this. I can only assume that 2 and a half years later it's long past the time when a fix would be relevant. Please let us know if that isn't the case.
