### ISSUE TITLE
Missing Dutch translation for "No misspellings found."

### ISSUE THREAD

**Issue by pesla** [tinymce/tinymce#3178]
The file [spellchecker/classes/Plugin.js:379](https://github.com/tinymce/tinymce/blob/b98786bc0813dda141bad069e285c11cd4485e59/js/tinymce/plugins/spellchecker/classes/Plugin.js#L379) contains a source text that doesn't seem to be translated:

``` javascript
var message = editor.translate('No misspellings found.');
```

I have created an account at Transifex to translate the string myself, but I couldn't [find](https://www.transifex.com/moxiecode/tinymce/viewstrings/#nl/plugin-spellchecker/12234524) this particular source text. As I'm not familiar with the process on adding source texts, this is where I have stranded.

Can anyone fix this issue or point me in the right direction?

**Comment by garak** [comment]
Sadly, this is true for other plugin strings.
I spent some minutes trying to figure out if it's possible to add missing strings, but I could only find how to manage existing one.

For the record, missing string I found is ["Alternative description"](https://github.com/tinymce/tinymce/blob/73ce0fefbdf1213e3e45570aadecce59b882e47f/modules/tinymce/src/plugins/image/main/ts/ui/MainTab.ts#L27) from image plugin.
