### ISSUE TITLE
Broken positioning of floatpanel arrow

### ISSUE THREAD

**Issue by pesla** [tinymce/tinymce#3179]
Floatpanels don't seem to break out of the editor viewport, which is great. When positioning a floatpanel near the right edge of the editor, the position of the arrow isn't adjusted. For example, this is a float panel for the (text) color picker which is positioned on the right side of the toolbar:

![screen shot 2016-09-05 at 15 11 11](https://cloud.githubusercontent.com/assets/94700/18248869/2a929f2c-737b-11e6-953f-2946ff0b77d1.png)

As you can see, the arrow of the floatpanel is pointing to the `redo` button, instead of the button that is selected by the user.

**Comment by tinydylan** [comment]
Hi,

This issue appears to have been corrected. These UI elements got a major overhaul as part of TinyMCE 5, which addressed a lot of bugs like this.

If you encounter any other issues, please let us know.
