### ISSUE TITLE
Lists plugin: Add setting to allow padding of lists as a whole

### ISSUE THREAD

**Issue by church29** [tinymce/tinymce#3183]
When initially creating a list, the indent button is disabled when you are on the first list item. I would like to be able to add padding just as I would with any other element.

**Comment by lnewson** [comment]
Hi,

I've just tested this using TinyMCE 4.9.10 and 5.2.2 and it appears that this feature has been implemented at some stage since you logged this request. I'll go ahead and close this, but if it doesn't meet your expectations then let us know and we'll reopen this feature request.

Thanks!
