### ISSUE TITLE
the anchor link does not work

### ISSUE THREAD

**Issue by aiftariyani** [tinymce/tinymce#3189]
Description of problem:

Steps to reproduce:
1. Go to https://www.tinymce.com/docs/demo/full-featured/
2. Add a large volume of text
3. Add an anchor (click anchor icon) to the end of the text with the name 'End of page'
4. Go to the beginning of the article and add a link that uses the anchor created in previous step
 
actual result : the anchor link does not work

**Comment by jayarjo** [comment]
I don't think links were ever meant to work while the text is being edited @spocke? What makes you think it should otherwise @aiftariyani?

**Comment by jayarjo** [comment]
We are working on way to enable links and anchors indirectly - small pop up will show up on hover and give user an opporotunity to follow the link.

**Comment by fauzi16** [comment]
Hi @jayarjo 

Would be great if I can get the patch.

has this already been fixed ? 
if yes, this must be exist in nightly build, But could I know what specific changes/ line of code has been made for this fixed ?

**Comment by jayarjo** [comment]
@fauzi16 for now you can simply take the raw copy of the [Link](https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/link/plugin.js) plugin.

You will also need to set link_context_toolbar option to true.
