### ISSUE TITLE
Table alignment and structure (rows/columns/cells) are sometimes incorrect (particularly when there are merged cells).

### ISSUE THREAD

**Issue by aiftariyani** [tinymce/tinymce#3190]
step to reproduce:

1. Go to tinyMCE v4 https://www.tinymce.com/docs/demo/classic/
2. Copy tables from Hostile Customer Incident Report.docx (docx attached)
3. Paste on tinyMCE editor
4. See the table on TinyMCE
5. Actual result : incorrect table alignment and structure 

[Hostile Customer Incident Report.docx](https://github.com/tinymce/tinymce/files/463677/Hostile.Customer.Incident.Report.docx)
![table1](https://cloud.githubusercontent.com/assets/22090142/18382837/ef797c82-76ac-11e6-877c-d11924ae5032.PNG)

Attached DOCX
[Hostile Customer Incident Report.docx](https://github.com/tinymce/tinymce/files/463689/Hostile.Customer.Incident.Report.docx)

**Comment by jayarjo** [comment]
There seem to be three columns in that table. At least this is what I see when I check Table Properties in Word and click through columns (via Next/Previous column buttons).

Also our [PowerPaste](https://www.tinymce.com/docs/plugins/powerpaste/) does much better job, optionally retaining the formatting and hiding away that empty column, the way Word hides it.

![powerpaste](https://cloud.githubusercontent.com/assets/150075/18615377/81030758-7db6-11e6-9849-1105dc23f846.jpg)
