### ISSUE TITLE
Sometimes (intermittent) Redo Undo is not working

### ISSUE THREAD

**Issue by aiftariyani** [tinymce/tinymce#3191]
1. On TinyMCE https://www.tinymce.com/docs/demo/classic/
2. Copy all content from Paste Issues.docx to tinymce editor
3. Make changes on the editor as much as possible such as change text color, font size, adding table, adding row or coloumn, change background color of cell, cut all text then paste, etc
- Check the undo process, sometimes it is working and sometimes not.
- Check the redo process, sometimes it is working and sometimes not.

Attached doxc
[Paste Issues.docx](https://github.com/tinymce/tinymce/files/463713/Paste.Issues.docx)

**Comment by michaeljohnstonverint** [comment]
video of issues: https://youtu.be/h7Z4ggW2ks8

**Comment by jayarjo** [comment]
Could you advise an exact sequence, 'cause it seems to work as expected for random operations.

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
