### ISSUE TITLE
translate() fails with empty/undefined/null/boolean/0 for the value or {raw}

### ISSUE THREAD

**Issue by aruben-c** [tinymce/tinymce#3192]
Hi,
I found a bug in the 'translate()' function in the i18n library:

when we try to translate a null value, we get the error message:
"Unable to get property 'raw' of undefined or null reference"

when we try to translate an empty/undefined/null raw object, we get the error message:
Object doesn't support property or method 'replace'

when we try to translate the value: true / false / 0, we get the error message:
Object doesn't support property or method 'replace'

**Test:**
Simply add one of this line in a js plugin:

tinymce.i18n.translate(null);

tinymce.i18n.translate(0);
tinymce.i18n.translate(true);
tinymce.i18n.translate(false);

tinymce.i18n.translate({});
tinymce.i18n.translate({raw:""});
tinymce.i18n.translate({raw:false});
tinymce.i18n.translate({raw:undefined});
tinymce.i18n.translate({raw:null});

**Where is located the bug?**
Theses issues come from the "if" in translate() function.

if (typeof text == "undefined")
-> it doesn't work for null.

if (typeof text != "string" && text.raw)
-> it doesn't test if 'text.raw' exists but it tests if 'text.raw' is true.
But ''/false/null/undefined are all false with this test.

if (text.push)
-> it doesn't test if 'text' is an array but if the function 'push' exists.

return (langData[text] || text).replace(/{context:\w+}$/, '');
-> it supposes that 'text' is a string (but above tests are failed).

**How to correct?**
I suggest a whole correction here (+ my previous issue #3029) :

```
translate: function(text) {
    var langData;

    langData = data[code];
    if (!langData) {
        langData = {};
    }

    if (text == undefined) {
        return "";
    }

    if (Object.prototype.toString.call(text) === '[object Object]') {
        if (text.raw == undefined) return '';
        return '' + text.raw;
    }

    if (Object.prototype.toString.call(text) === '[object Array]') {
        var values = text.slice(1);

        text = (''+(typeof langData[''+text[0]]==='string'?(langData[''+text[0]] || text[0]):text[0])).replace(/\{([0-9]+)\}/g, function(match1, match2) {
            return ''+values[match2];
        });
    }

    return (''+(typeof langData[''+text]==='string'?(langData[''+text] || text):text)).replace(/{context:\w+}$/, '');
},

```

Thanks,
ARuben

**Comment by jayarjo** [comment]
I got this fixed. However I chose to convert any type of unknown variable to string and not return emty string for falsy values. So it will return "null" for `null` argument, "false" for boolean `false` and "[object Object]" for any unknown variable of object type, etc.

**Comment by aruben-c** [comment]
Hi,

I had a comment on the issue #3029

I agree with you for "false" for boolean 'false' and "[object Object]" for any unknown variable of object type.
However, I thinks that for the other cases, it would be return:
- for a number: the number in string format (5 => "5")
- for empty, null, undefined, NaN: an empty string (my point of view: "when we give nothing, we receive nothing!")

I will comply with your decision!

ARuben

**Comment by jayarjo** [comment]
Thank you for your suggestions and cooperation. Next release will contain the fix.
