### ISSUE TITLE
Problem redisplaying HTML/JSX code inside codesample

### ISSUE THREAD

**Issue by ZigaStrgar** [tinymce/tinymce#3193]
Codesample plugin is having issues with re-displaying HTML tags inside codesample area.

The issue occours in HTML/XML and React JSX (not added by default). When you create the codesample everything is OK. But when you want to edit the codesample it renders (executes) the HTML back into textarea of tinymce instead displaying it in codesample pre block.

**Comment by jayarjo** [comment]
Could you provide an example via [TinyMCE Fiddle](http://fiddle.tinymce.com/) or [CodePen](http://codepen.io/)?

**Comment by ZigaStrgar** [comment]
This one is hard to reproduce, when I create new codesample with HTML content even if it is inside JSX code it's rendered correctly. But when I want to edit that same blog post containing the HTML code snippet new page loads, the content is loaded into textarea via Blade and the HTML snippet is not showing inside codesample area but is rather rendered as the actual HTML.

This is the article it self upon adding.
![image](https://cloud.githubusercontent.com/assets/5392538/18627714/ad58b4aa-7e5c-11e6-9c4c-5b1f3bf9395d.png)

This is the article itself.
![image](https://cloud.githubusercontent.com/assets/5392538/18627738/d60af82c-7e5c-11e6-890d-ca84bb7a997a.png)

When I click edit post, this is the content of the tinymce.
![image](https://cloud.githubusercontent.com/assets/5392538/18627755/f0811f38-7e5c-11e6-9566-cee1a2bea874.png)

**Comment by jayarjo** [comment]
Check if this helps: https://github.com/tinymce/tinymce/issues/3162

**Comment by ZigaStrgar** [comment]
Helped :) thanks
