### ISSUE TITLE
During scroll ResizeWindow Event is fired

### ISSUE THREAD

**Issue by TuningGuide** [tinymce/tinymce#3195]
When I scroll down a page where a editor is loaded globalEventDelegate in classes/EditorManager checks for type == scroll. The first time it is indeed scroll and so it fires ScrollWindow. The second time it is ScrollWindow which is != scroll so it fires ResizeWindow

Should we add a check for type != ScrollWindow && ResizeWindow?

	function globalEventDelegate(e) {
		if(e.type != 'ScrollWindow' && e.type != 'ResizeWindow') {
			each(EditorManager.editors, function(editor) {
				if (e.type === 'scroll') {
					editor.fire('ScrollWindow', e);
				} else {
					editor.fire('ResizeWindow', e);
				}
			});
		}
	}

**Comment by TuningGuide** [comment]
I'm using Tinymce with React so it could be that globalEventDelegate with ScrollWindow is called because https://github.com/instructure-react/react-tinymce is rewritting some events.

**Comment by TuningGuide** [comment]
Forget react-tinymce it has nothing to do with it. Either my debugger is bugging me or editor.fire changes the event type to the passed event type and subsequent loop passes then get the changed event type. Added `editor.fire('ScrollWindow', Object.create(e))`

**Comment by jayarjo** [comment]
Cannot repeat it here: http://codepen.io/anon/pen/BLLQZa?editors=1010. Can you alter the Pen to help us repeat the issue?

**Comment by TuningGuide** [comment]
With newest tinymce I can't reproduce ether.

**Comment by Lughino** [comment]
I have the same problem with Firefox (49, 50, 51).
I tested the versions of tinymce 4.5.3, 4.5.2, 4.4.1, 4.3.1 and all feedback this issue.
In my specific case I have several instances of tinymce inside the page, then the problem is quite evident as every scroll freeze the browser.
If you put a breakpoint in `globalEventDelegate` you can view the problem.
