### ISSUE TITLE
Adding new html to existing html can cause bad syntax

### ISSUE THREAD

**Issue by gidmeister2** [tinymce/tinymce#3196]
I have a website where I have embedded the tinyMce editor.  (not inline).  My website does a check on the output of the editor to be sure the tags are balanced and there are no major syntax errors.  If there are, it removes most tags that were produced.

 I put in some tricky syntax (for testing purposes) and tinyMce had no problem.  The tags I put in were:
`<p id="RFSkid1_P">first test this:</p>
<p id="RFSkid1_P">Now the <span id="RFSkid2_SPAN" style="background-color: #ffff00;">reason that the <span id="RFSkid3_SPAN" style="color: #ff0000;">black hawk tribe could not foresee the future</span> of the internet</span> was that they were natives to the forest who were only interested in making stuff out of natural materials</p>
<hr id="RFSkid4_HR" />
<p id="RFSkid5_P">then test <strong id="RFSkid6_STRONG">the RAIN in spain FALLS mainly</strong> in the plain and this <strong id="RFSkid7_STRONG">the last <em id="RFSkid8_EM">Mohican</em> could not win</strong> and IRIQUOIS</p>
<div id="RFSkid9_DIV">Nation of Islam could not DECIPHER the CODEX of Allah and Rembrandt beleaguer the red snail</div>`
So then I tried adding some more tricky syntax.  I added a few sentences and highlighted maybe 10 words in the middle of them, and within that highlight, I made 4 consecutive words bold.   If I submit that to my website, my website detects something wrong, and removes most of the formatting.  So the question is, what is wrong.  Interestingly, if I first VIEW-SOURCE and hit OK, and then try to submit the tinyMCE content, my website gives an all-clear, and allows the output of the editor to remain untouched.  I will put some debug statements in my code to find the exact output of the tinyMCE editor that is rejected, and will add that later to this issue.  But the problem is a real one, it happens quite often, and it happens with text I type into the regular view of the editor, not the source view.  UPDATE: it seems to have started working now, and I don't know why.  Perhaps you can duplicate it or think of a reason why it happened?

**Comment by jayarjo** [comment]
Sorry, without an actual case we obviously won't be able to progress on this one.
