### ISSUE TITLE
DOMUtils.get return elm instead of null

### ISSUE THREAD

**Issue by TuningGuide** [tinymce/tinymce#3197]
the jsdocs of get state that is returns null if string/element was not found but instead it returned the passed elm parameter. In my case this.doc is empty when get is called in hideResizeRect is this normal?

		/**
		 * Returns the specified element by ID or the input element if it isn't a string.
		 *
		 * @method get
		 * @param {String/Element} n Element id to look for or element to just pass though.
		 * @return {Element} Element matching the specified id or null if it wasn't found.
		 */
		get: function(elm) {
			var name;

			if (elm && this.doc && typeof elm == 'string') {
				name = elm;
				elm = this.doc.getElementById(elm);

				// IE and Opera returns meta elements when they match the specified input ID, but getElementsByName seems to do the trick
				if (elm && elm.id !== name) {
					return this.doc.getElementsByName(name)[1];
				}
			}

			return elm;
		}

**Comment by jayarjo** [comment]
Sorry, I couldn't grasp the problem. `get` returns an element by ID or `elm` itself, if it wasn't a string (was some node for example).

**Comment by TuningGuide** [comment]
My problem is that this.doc is in some situations null. In this case the get method returns elm directly. In case elm was a string, a string is returned. Which is against the jsdoc.

**Comment by jayarjo** [comment]
Ok, I see now. Could you describe or create a case when `this.doc` is null? You can use [TinyMCE Fiddle](http://fiddle.tinymce.com/) or [CodePen](http://codepen.io/) for this.

**Comment by TuningGuide** [comment]
Hi jayarjo. My "stacktrace" is like this:
 editor.getContent -> self.getBody -> this.getDoc().body -> getWin == null ? : self.contentDocument. Where contentDocument is null. I'm working with React and maybe react unmounts / rerenders tinymce when tinymce tries to execute getContent

**Comment by TuningGuide** [comment]
It seems it is related to react-tinymce + mobx. as that react rerenders the editor in the moment tinymce wants to access the doc. I recommend to close this issue. Sry for the hazzle
