### ISSUE TITLE
Empty blocks after nline format change

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#3198]
steps:
1) pick format ( inline (sub for example))
2) unpick format

empty block in html

it is not terrible to inline formats like sub/sup/b/i/etc

but i make custom formats:

formats: {
               title: {inline: 'span', classes: 'titleText'},
               subTitle: {inline: 'span', classes: 'subTitleText'},
               selectedMainText: {inline: 'span', classes: 'selectedMainText'},
               additionalText: {inline: 'span', classes: 'additionalText'}
            },

and this classes have different line-height

and after i pick and unpick format(title class) i have <P> with big line height

**Comment by jayarjo** [comment]
Here's the basic Pen: http://codepen.io/anon/pen/LRRbgm?editors=1010, could you put in your cases?
