### ISSUE TITLE
Wrong tab / Ancor Content -> on WordPress

### ISSUE THREAD

**Issue by PeopleInside** [tinymce/tinymce#3199]
In my Wordpress I have this page code:
Code has been pasted here:
http://pastebin.com/TfLaEK1n

Here on GitHub is showed correctly, in my Wordpress not.

<hr />
<p style="text-align: center;"><span style="font-size: 13pt; font-family: book antiqua,palatino; color: #003366;">Benvenuti al cinema di .:.PeOPLeInSiDE.:.! </span></p>
<p style="text-align: left;"><span style="font-size: 13pt; font-family: book antiqua,palatino; color: #003366;">Qui saranno riportati in tabella quei film che sono stati in grado di trasmettermi emozioni, trasportarmi in magnifici viaggi e darmi nuove visioni sulla vita. Per chi li vorrà scoprire e apprezzare sono qui a disposizione!</span></p>
<hr />
<p style="text-align: left;"><span style="font-size: 13pt; font-family: book antiqua,palatino; color: #003366;">Qui troverai la tabella dei Film e, più in basso, quella dei &gt;&gt; Cartoni &lt;&lt;</span></p>
<p style="text-align: center;"><span style="font-size: x-large; font-family: book antiqua,palatino; color: #003366;">Film</span></p>
<div>
<table class=" aligncenter" style="width: 768px; height: 1338px;" border="0">
<tbody>
<tr>
<td><span style="font-size: x-large;">Titolo</span></td>
<td><span style="font-size: x-large;">Anno</span></td>
<td><span style="font-size: x-large;">Regista</span></td>
<td><span style="font-size: x-large;">Data di Visione</span></td>
<td><span style="font-size: x-large;">Voto<br />
 </span></td>
<td><span style="font-size: x-large;">Note</span></td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino,serif;"><span style="font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2013/marina/" target="_blank"><span style="font-family: book antiqua,palatino;">Marina</span></a></span></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2013</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">domenica 09/08/2015 </span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">8/10</span></td>
<td><span style="font-size: 13pt;">Emozionante. Dalla canzone al film e la scoperta di quanta sofferenza, amore, storia è fatta una canzone.</span></td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino,serif;"><a href="http://www.mymovies.it/film/2009/iloveshopping/" target="_blank"><span style="font-family: book antiqua,palatino;">I Love Shopping</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2009</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">22/05/2015</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7/10</span></td>
<td><span style="font-size: 13pt;">Film colorato, divertente con il racconto della mania per lo shopping. Un difetto che però può prendere anche un'altra angolazione.</span></td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-7762cc15-d666-4377-8306-b103a34d8188.html" target="_blank"><span style="font-family: book antiqua,palatino;">Santa Barbara</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">martedì 21/04/2015</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">6,5/10</span></td>
<td><span style="font-size: 13pt;">Non per il Cristianesimo... ma per chiedermi fino a dove può arrivare la sofferenza umana e la cattiveria di qualche cuore marcio.. e l'Amore che come sempre sa' a distinguersi brillando di luce.. ma quanto costa?</span></td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2013/termsandconditionsmayapply/" target="_blank"><span style="font-family: book antiqua,palatino;">Terms and Conditions May Apply </span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2013</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">sabato 11/10/2014</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7/10</span></td>
<td><span style="font-size: 13pt;">Documentario che esamina il costo dei cosiddetti servizi liberi e la continua scomparsa della privacy online. Cosa accade e a cosa si rinuncia quando clicchiamo 'Accetto' con aziende come Facebook e Google? (descrizione da mymovies)</span></td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2014/ilcapitaleumano/" target="_blank"><span style="font-family: book antiqua,palatino;">Il capitale umano</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2014</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">mercoledì 2/07/2014</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7/10</span></td>
<td><span style="font-size: 13pt;">La storia di diverse storie umane, gli incroci tra ricchezza e povertà, l'immagine del nobile confrontata alla storia del povero. Un viaggio emozionante che ci fà capire tante cose. Il Capitale Umano.</span></td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2010/hereafter/" target="_blank"><span style="font-family: book antiqua,palatino;">Hereafter</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2010</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">martedì 1/07/2014</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">8,5/10</span></td>
<td><span style="font-size: 13pt;">Mi ha aperto gli occhi un po' sulla fiducia che non sono tutti falsi e un po' sulle storie diverse di difficoltà umane. Molte volte ciò che sembra bello non appare così all'altro. Forte storia umana carica di emozioni.</span></td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2013/lesmiserables/" target="_blank"><span style="font-family: book antiqua,palatino;">Les miserables</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"> /</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">mercoledì 15/01/2014<br />
 </span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"> 8,5/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2007/nonemaitroppotardi/" target="_blank"><span style="font-family: book antiqua,palatino;">Non è mai troppo tardi</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2007</span></td>
<td><span style="font-size: 13pt;"> /</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">martedì 29/05/2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7,9/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2002/secretary/" target="_blank"><span style="font-family: book antiqua,palatino;">Secretary</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2002</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">Steven Shainberg</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">lunedì 28/05/2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">6,5/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2012/thebestexoticmarigoldhotel/" target="_blank"><span style="font-family: book antiqua,palatino;">Marigold Hotel</span></a><br />
 </span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">venerdì 30/05/2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">8/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2011/intouchables/" target="_blank"><span style="font-family: book antiqua,palatino;">Quasi amici (intouchables)</span></a><br />
 </span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">domenica 25/05/2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">9/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2011/hugocabret/" target="_blank"><span style="font-family: book antiqua,palatino;">Hugo Cabret</span></a><br />
 </span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2011</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">domenica 18/05/2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">xx/xx</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/dizionario/recensione.asp?id=32973" target="_blank"><span style="font-family: book antiqua,palatino;">La voce dell'amore</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">1998</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">Carl Franklin</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">domenica 19/02/2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">xx/xx</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/dizionario/recensione.asp?id=18905" target="_blank"><span style="font-family: book antiqua,palatino;">Powder</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">1995</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">Victor Salva</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">8,5/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2001/moulinrouge/" target="_blank"><span style="font-family: book antiqua,palatino;">Moulin Rouge</span></a></span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-size: 13pt;"> <span style="font-family: book antiqua,palatino;">9/10</span></span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.thesecretitalia.it/" target="_blank"><span style="font-family: book antiqua,palatino;">The secret</span></a><br />
 </span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.filmtv.it/film/49594/la-forza-del-campione/" target="_blank"><span style="font-family: book antiqua,palatino;">La forza del campione</span></a><br />
 </span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">8,5/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="https://www.google.it/search?q=patch+adams" target="_blank"><span style="font-family: book antiqua,palatino;">Patch adams</span></a><br />
 </span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">9/10</span></td>
<td><span style="font-size: 13pt;"><span style="font-family: book antiqua,palatino;"> &gt;&gt; </span><span style="font-family: book antiqua,palatino;"><a href="http://www.patchadams.org/" target="_blank">Sito web del Dott. Patch </a>&lt;&lt;</span></span></td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2012/sex3d/" target="_blank"><span style="font-family: book antiqua,palatino;">Com'è bello fare l'amore</span></a><br />
 </span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">giovedì 29/11/2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">xx/xx</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="http://www.mymovies.it/film/2012/thechef/" target="_blank"><span style="font-family: book antiqua,palatino;">Chef</span></a><br />
 </span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">/</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">mercoledì 09/04/2013</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7,5/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2002/illadrodiorchidee/" target="_blank"><span style="font-family: book antiqua,palatino;">Il ladro di orchidee</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">giovedì 25/07/2012</span></td>
<td><span style="font-size: 13pt;"> <span style="font-family: book antiqua,palatino;">xx/xx</span></span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2013/civediamodomani/" target="_blank"><span style="font-family: book antiqua,palatino;">Ci vediamo domani</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2013</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">mercoledì 28/08/2013</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7,5/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="https://www.google.it/search?q=antwone+fisher" target="_blank"><span style="font-family: book antiqua,palatino;">Antwone Fisher</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2013</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">mercoledì 27/11/2013</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7,5/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2001/ilfavolosomondodiamelie/" target="_blank"><span style="font-family: book antiqua,palatino;">Il favoloso mondo di Amélie</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">martedì 31/12/2013</span></td>
<td><span style="font-size: 13pt;"> <span style="font-family: book antiqua,palatino;">7/10</span></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">Il film non è subito di facile comprensione e può risultare noioso. Bisogna arrivare fino al finale, per poter apprezzarlo.</span></td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2012/thebestoffer/" target="_blank"><span style="font-family: book antiqua,palatino;">La migliore offerta</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2012</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">mercoledì 26/02/2014</span></td>
<td><span style="font-size: 13pt;">8/10</span></td>
<td>&nbsp;</td>
</tr>
<tr>
<td><span style="font-size: 13pt;"><a href="http://www.mymovies.it/dizionario/recensione.asp?id=44431" target="_blank"><span style="font-family: book antiqua,palatino;">La musica nel cuore</span></a></span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">2007</span></td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td>
<p><span style="font-size: 13pt; font-family: book antiqua,palatino;">domenica, 05/04/2015</span></p>
</td>
<td><span style="font-size: 13pt; font-family: book antiqua,palatino;">7/10</span></td>
<td><span style="font-family: book antiqua,palatino; font-size: 13pt;">Visto per la seconda volta oggi.</span></td>
</tr>
</tbody>
</table>
</div>
<p style="text-align: center;"> </p>
<center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center>.</center><center></center><center></center><center></center><center></center><center></center><center></center><center></center><center><span style="font-size: 13pt; font-family: book antiqua,palatino; color: #003366;">Cartoni</span></center>
<div>
<table class="aligncenter" style="width: 866px; height: 413px;" border="0" align="center">
<tbody>
<tr style="height: 97px;">
<td style="height: 97px;"><span style="font-size: x-large;">Titolo</span></td>
<td style="height: 97px;"><span style="font-size: x-large;">Anno</span></td>
<td style="height: 97px;"><span style="font-size: x-large;">Produttore o Regista</span></td>
<td style="height: 97px;"><span style="font-size: x-large;">Data di Visione</span></td>
<td style="height: 97px;"><span style="font-size: x-large;">Voto<br />
 </span></td>
<td style="height: 97px;"><span style="font-size: x-large;">Note</span></td>
</tr>
<tr style="height: 26px;">
<td style="height: 26px;">
<p><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2016/zootopia/" target="_blank"><span style="font-family: book antiqua,palatino,serif;"><span style="font-family: book antiqua,palatino;">Zootropolis</span></span></a></span></p>
</td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">2016</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Disney</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">venerdì 27/05/2016</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">9/10</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Ognuno è speciale. Insegui i tuoi sogni!</span></td>
</tr>
<tr style="height: 56px;">
<td style="height: 56px;">
<p><span style="font-size: 13pt; font-family: book antiqua,palatino,serif;"><a href="http://www.mymovies.it/film/2012/theguardians/" target="_blank"><span style="font-family: book antiqua,palatino;">Le 5 leggende</span></a></span></p>
</td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">2012</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">giovedì 01/10/2015</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">8/10</span></td>
<td style="height: 56px;"><span style="font-family: book antiqua,palatino; font-size: 13pt;">Fantastico! Riscopriamo la forza magica e bambina dentro di noi!</span></td>
</tr>
<tr style="height: 104px;">
<td style="height: 104px;">
<p><span style="font-size: 13pt;"><a href="https://www.google.it/search?q=Trilli+e+la+creatura+leggendaria" target="_blank"><span style="font-family: book antiqua,palatino;">Trilli e la creatura leggendaria</span></a></span></p>
</td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;"> 2014</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Disney</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;"> sabato 11/04/2015</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;"> 8/10</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Da vedere :)</span></td>
</tr>
<tr style="height: 48px;">
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;"><a href="https://www.google.it/search?q=Doraemon+–+Il+film" target="_blank"><span style="font-family: book antiqua,palatino;">Doraemon il film</span></a></span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">2014</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">lunedì 23/02/2015</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">7/10</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Molto significativo. Commuovente, bisogna solo guardarlo fino alla fine.</span></td>
</tr>
<tr style="height: 48px;">
<td style="height: 48px;"><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2014/lapemaia/" target="_blank"><span style="font-family: book antiqua,palatino;"><span style="font-family: book antiqua,palatino;">L'Ape Maia Il Film</span></span></a></span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">2014</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">domenica 25/01/2015</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">7,5/10</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Grafica bellissima e storia ricca di bellissimi messaggi! Da vedere, assolutamente!</span></td>
</tr>
<tr style="height: 72px;">
<td style="height: 72px;"><span style="font-size: 13pt;"><a href="https://www.google.it/search?q=hero+6" target="_blank"><span style="font-family: book antiqua,palatino;">Big Hero 6</span></a></span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">2014</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Disney</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">domenica 11/01/2015</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">9/10</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Consigliata la visione al CINEMA per una miglior esperienza immagine/musica. Questo è un capolavoro della Disney</span></td>
</tr>
<tr style="height: 72px;">
<td style="height: 72px;"><span style="font-size: 13pt;"><a href="http://www.mymovies.it/film/2013/frozen/" target="_blank"><span style="font-family: book antiqua,palatino;"> Frozen: il regno di ghiaccio</span></a></span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;"> 2013</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;"> Disney</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;"> domenica 02/02/2014</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;"> 9/10</span></td>
<td style="height: 72px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Consigliata la visione al CINEMA per una miglior esperienza immagine/musica. Questo è un capolavoro della Disney</span></td>
</tr>
<tr style="height: 48px;">
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Shrek (DVD 1,2,3,4)</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">/</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">**/06/2012</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">9/10</span></td>
<td style="height: 48px;"><span style="font-size: 13pt; font-family: book antiqua,palatino;">Divertentissimo</span></td>
</tr>
</tbody>
</table>
</div>
<p style="text-align: center;"> </p>
<p style="text-align: center;"> </p>
<p style="text-align: center;">. . .</p>`

Here the two tab are showed separately correctly, in my website not:
![1](https://cloud.githubusercontent.com/assets/5006150/18438982/d137face-7903-11e6-9d86-3a8508fd4e5f.png)
![2](https://cloud.githubusercontent.com/assets/5006150/18438984/d46ec664-7903-11e6-87ae-5062ff129be7.png)

The results is one table go over the other table so I added fullstop in the page for made one table be under the other. 
Can you fix?
This is the URL where my page is: https://www.peopleinside.it/su-di-me/film/

Code has been pasted here:
http://pastebin.com/TfLaEK1n

**Comment by jayarjo** [comment]
I can't repeat it on the fresh installation of wordpress, so it might be some other wordpress plugin interfering with tinymce styles. I see you have tinymce add-ons - I'd recommend to disable them one by one and see if it makes the issue disappear.

**Comment by PeopleInside** [comment]
Seems you are right... @jayarjo I will investigate thanks.

**Comment by PeopleInside** [comment]
I deactivated all plug in but issue persist...

**Comment by PeopleInside** [comment]
I AM able to reproduce in a new Wordpress Installation.
Sorry the message og @jayarjo confused me.

https://www.softaculous.com/demos/WordPress

**Comment by jayarjo** [comment]
I tried it in WP 4.4 and it worked there. Ok, it seems they've changed something in recent release. Can't tell you what at the moment - it's quite a broad topic. However looking at your code now I see that you specify very specific dimensions for your tables.

```html
<table class="aligncenter" style="width: 866px; height: 413px;" border="0" align="center">
<tbody>
```

And they simply do not fit. I'd suggest that you remove explicit width/height.

**Comment by PeopleInside** [comment]
Last WordPress is 4.61 so 4.4 is a bit old. This is not recent issue I have from many and many month but never reported before.

My code is generated from TinyMCE i never customize it.
Also if I paste the code here in GitHub is all showed correctly as is showed correctly on the Tinymce demo website: https://www.tinymce.com/docs/demo/basic-example/

@jayarjo thanks for your advice but I will wait here a fix. I cannot edit all the code manually and maybe yours is not the solution. There are something wrong as the same code works well here and on Tinymce website demo... so maybe there are some issue with WordPress but also a standard clean install.

In fact I copy the code provide here and put in the Softaculous demo and not works as expected. As in my website tab are showed badly..

**Comment by jayarjo** [comment]
TinyMCE doesn't apply width/height on a table, unless you explicitly tell it to do so from Table Properties. I do not see why you would want to have strict width/height on that table, when it obviously is meant to accommodate to the content and page layout.

The fact that you cannot replicate it anywhere else, tells that it has something to do with the environment, rather than TinyMCE itself.

**Comment by PeopleInside** [comment]
Hi @jayarjo thanks for your help but let this topic be replied by the proper staff person. Thank you.
As I told I never put in the code height and width. Everything was done from the visual editor.

However height or width works well here. If code, the same code on my website is pasted here in GitHub the issue is not present also in the TinyMCE demo but is present in a WordPress so this issue should be fixed. Again thank you for your help but I will no reply to more post like this. Is not true I cannot replicate elsewhere. Have a nice time, sorry if you will not read any other reply from me. I will wait for support about this topic and do not want spamming.

Thanks.

**Comment by Afraithe** [comment]
jayarjo is en Ephox employee, maintains and develops the TinyMCE Open Source project.

As this seems to be related to your environment, I am closing this.

**Comment by PeopleInside** [comment]
Hi @Afraithe sorry but as I can see here just a Member.
You say this issue seems to be related to my environment: how you can say this if this happen on a clean Wordpress install?

**Comment by Afraithe** [comment]
Question: Can you reproduce it on tinymce.com or fiddle.tinymce.com?
Answer: No (as your saying yourself).

Case closed, we are not going to investigate any further, not feasible.

**Comment by PeopleInside** [comment]
How to see the results on fiddle.tinymce.com?
Tinymce.com is a website made by with Wordpress?

**Comment by PeopleInside** [comment]
As you can see from the screenshot below 
in a clean demo of Wordpress without any plug in active
the code I mad available here
is not well showed on TinyMCE of Wordpress.

The screenshot are from a Clean Wordpress demo but the issue is also present on my website. A completely different website and Wordpress installation.
The issue is still present also if I deactivate all plug in.

So this is a BUG in Wordpress?
Or can be some conflit between Wordpress and TinyMCE?
Or is an issue of TinyMCE only for Wordpress?

![1](https://cloud.githubusercontent.com/assets/5006150/18708646/41123ebe-7ffc-11e6-9b0d-f5bc67e5e3c7.png)
 
![2](https://cloud.githubusercontent.com/assets/5006150/18708657/4d16e994-7ffc-11e6-9389-dfbb4e4b369d.png)

Hope you can help. I really want solve this issue, now. Too many time is past and issue persist. Now I do better test and I AM able to reproduce also outside of my website in a Wordpress DEMO.

This made me think the issue is no related to me as you told.

**Comment by Afraithe** [comment]
If it is not related to tinymce, and not related to your environment, then its a wordpress issue? We do not patch wordpress, this ticket is pointless in our system, unless an issue in Wordpress is found that somehow relates to the TinyMCE implementation of Wordpress. You may want to solve this very much, but it will not be from our side at this point.

**Comment by PeopleInside** [comment]
Ok sorry and thank you @Afraithe and @jayarjo 

I opened a ticket on WordPress as BUG https://core.trac.wordpress.org/ticket/38120#ticket
