### ISSUE TITLE
Null Reference when Deleting Table Rows

### ISSUE THREAD

**Issue by jtark** [tinymce/tinymce#3206]
We encountered an issue with the table plugin where under certain conditions, deleting a table row would cause a null reference. I've replicated the issue in the full-featured demo, so I don't think it's an implementation issue.

I replicated it like so:
1. Have at least two rows in a nested table, one of which contains only an empty TD element (it can have a non-breaking space, though).
2. Select a non-empty row and click the Delete Row button that appears.
3. Click the Delete Row button that appears until the empty row is automatically selected.
4. Click the Delete Row button one more time.
5. A null reference occurs.

The null reference I replicated appeared to occur on line 1314 of the table plugin (not minified), where it attempted to reference the position of the selected cell, but getPos did not return a valid reference.

I've attached sample HTML that you can use to replicate the issue.

[Row Deletion Test.zip](https://github.com/tinymce/tinymce/files/475261/Row.Deletion.Test.zip)

**Comment by jtark** [comment]
Has there been any progress on this issue?

**Comment by tinydylan** [comment]
Hi,

I am unable to replicate this error. Since we ported the codebase to TypeScript, this sort of error has become less common. For now, I'm going to close this issue, but if you see it again, please let us know.

Thanks for the bug report. We appreciate all efforts like this to improve TinyMCE.
