### ISSUE TITLE
Codesample plugin: allow inline code samples

### ISSUE THREAD

**Issue by TimVevida** [tinymce/tinymce#3208]
Currently, the code sample plugin only supports code blocks (`<pre>`), while PrismJS supports two types of code:
1. Block code, in the form `<pre class="language-markup"><code> ... </code></pre>`
2. Inline code, in the form `<code class="language-markup"> ... </code>`

When using both inside an editor, the inline code is displayed partially according to the PrismJS styling (background color and padding), but the language-specific styling is not applied, and the inline code is not editable using the codesample dialog.

**Comment by jayarjo** [comment]
@spocke

**Comment by Afraithe** [comment]
We have this as an internal ticket to work on, can't promise any specific release date though.

**Comment by TimVevida** [comment]
Related question: the [PrismJS documentation](http://prismjs.com/#basic-usage) states that the class should be put on the code element, like so:

```<pre><code class="language-markup"> ... </code></pre>```

But the codesample-plugin puts the class on the `<pre>` element. Existing sources with the class on the `<code>` element rather than the `<pre>` element are not displayed correctly.

For backward compatibility, I think both methods should be supported (I noticed that PrismJS puts the class on both the `<pre>` **and** the `<code>` when rendering the highlighted code).
