### ISSUE TITLE
Newbie needs help

### ISSUE THREAD

**Issue by jessemartin1** [tinymce/tinymce#3209]
I'm an expert in how people learn, and am developing an online learning platform that is centred on the learner rather than the teacher (as every other platform is). I need to incorporate an editor that can be called when it is needed, and the TinyMce looks ideal. I'm doing well with coding most of the platform, but can't figure out this one. How do I incorporate the editor in my site?

**Comment by Taygair** [comment]
This is not an issue what you are asking. tinyMCE does explain it well how to implement the editor: https://www.tinymce.com/docs/configure/integration-and-setup/
