### ISSUE TITLE
Resize seems not to work, min-values ignored

### ISSUE THREAD

**Issue by Taygair** [tinymce/tinymce#3210]
Using these parameters to init tinyMCE: 
        tinymce.init({
            selector: '#texteditor',
            inline: false,
            height: 400,
            width: 400,
            min_height: 200,
            min_width: 200,
            resize: 'both',
            statusbar: false
        });

.. seems not to work:
- resize: does not work on statusbar = false. There is no more resizer there. 
- min_height and min_width do not catch, I can drag it smaller than set values

Tested all on Mac Notebook in Safari, Firefox and Chrome.

**Comment by jayarjo** [comment]
Here is a Pen: http://codepen.io/anon/pen/WGxBEN?editors=1010. Seems to work as expected?

Since resize handle resides on status bar, isn't it logical that it disappears when status bar is hidden?

**Comment by Taygair** [comment]
Thank you for your answer. It works with the statusbar but not without, had the same issue. 
Erm, no, it was not obvious to me that it wouldn't work without statusbar. I couldn't find anything in the documentation something like "Resize works only with active statusbar". Why should the resizer only rely on that? I could imagine that the resizer symbol resides in the lower right corner in the white area (without statusbar). That wouldn't affect the over all viewing that much. Why should resizing only be possible with statusbar? Just my 2 cents...
