### ISSUE TITLE
[Help] Valid HTML Elements

### ISSUE THREAD

**Issue by sancel22** [tinymce/tinymce#3211]
Hi all,
I set several html tag as valid. It works as expected. Those html tag not defined as `valid_elements` was removed. My question is, Is it possible to display warning to the user before removing those invalid elements?

Thank you,

Cel

**Comment by spocke** [comment]
This ticket seems to be more of a general community question rather than a bug/feature request. Please use the community forums at https://community.tinymce.com/ or register for an Enterprise license for commercial support. Thanks.
