### ISSUE TITLE
typeover still have issues in 4.4.x in Chrome/Safari in inline mode

### ISSUE THREAD

**Issue by bago** [tinymce/tinymce#3222]
Hi,

I use tinymce in inline mode to edit many kind of tags.

I see this issue happening in A tags, here is the reproducing fiddle:
http://fiddle.tinymce.com/17faab/3

I see 4.4.0 introduced some code to deal with the issue, but unfortunately I see 4.4.x works fine in Chrome in both Windows and Linux, but still show the issue (albeight with some differences) in both Chrome and Safari for MacOSX.

**Comment by jhorowitz-firedrum** [comment]
@spocke Expanding on this issue:

git bisect identifies commit 4c9bfc5501df334b6879e8d45523865068761495 as the source of this bug.

It appears that during the refactoring of "delete all" logic into BlockRangeDelete, some functionality for "typeover all" was lost. Specifically, the [onkeypress code in Quirks.js lines 1070 through 1080 that were deleted in the above referenced commit](https://github.com/tinymce/tinymce/commit/4c9bfc5501df334b6879e8d45523865068761495#diff-d72d754be12b3d0b6a4c7439c3e7dabaL1070) are essential for WebKit and Gecko to properly handle the typeover all case.

[This patch](https://github.com/tinymce/tinymce/files/1949446/issue-3222-typeover-fix.patch.txt) fixes the issue on the current master commit cf05d84ca4d62ff730d7c34b784f0d35419e9b03.

**Comment by bago** [comment]
I checked the fiddle and while tinymce 4.4.0 fixed it, sounds like 4.6.5 broke it again and it is broken in 5.2.2 too.

So sounds like a regression.
