### ISSUE TITLE
Facing issues when copying content from MS word

### ISSUE THREAD

**Issue by rimpleshah** [tinymce/tinymce#3224]
Hi,

When we copy content from MS word to Our application(Atlas), bullets and tables format is disturbed. We are facing multiple issues with regards to this. What should we do? 

Below is our code:

tinyMCE.init({
    mode : "exact",
    theme : "advanced",
    inline_styles : false,
    elements:"<%=request.getAttribute("tinyMCEElements")%>",
    plugins : "<%=pluginList%>",

```
theme_advanced_buttons1 : "fullscreen,search,spellchecker,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,tablecontrols,|,hr,pastetext,removeformat",
theme_advanced_buttons2 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect,forecolor,backcolor,nonbreaking,charmap,|,link,unlink<%=!isStandard?"":",|,image"%>",
theme_advanced_buttons3: "<%=!isAutoFill?"":",defaultcontent,mainBodyContent,confInstruction,confInsNoInterview,questionnaire,globalvars"%>",
theme_advanced_toolbar_location : "top",
theme_advanced_toolbar_align : "left",
theme_advanced_statusbar_location : "bottom",
theme_advanced_resizing : <%= isResizing %>,
theme_advanced_resizing_use_cookie : 0,
theme_advanced_resize_horizontal : <%= isResizeHorizontal %>,
theme_advanced_resizing_min_width : 650,
theme_advanced_resizing_min_height : 160,
theme_advanced_path: false,
relative_urls : false,
convert_urls : false,
paste_auto_cleanup_on_paste: false,
paste_convert_middot_lists: false,
paste_retain_style_properties:"all",
paste_postprocess: function(pl, o) {cleanPasteRecursive(pl.editor.getDoc(), o.node);},
convert_fonts_to_spans: false,

spellchecker_languages : "+English=en-us,German=de-de",
spellchecker_rpc_url    : "<%=request.getContextPath()%>/jmyspell-spellchecker", 
external_image_list_url : "<%=request.getContextPath()%>/tiny_mce/imagelist.jsp",
valid_elements : '@[id|class|style|title|dir<ltr?rtl|lang|xml::lang|float],a[rel|rev|charset|hreflang|tabindex|accesskey|type|name|href|target|title],strong/b,em/i,strike/s,u,style,#p[align],-ol[type|compact|start],-ul[type|compact],-li,br,img[longdesc|src|border|alt=|hspace|vspace|width|height|align],-sub,-sup,-table[border|cellspacing|cellpadding|width|frame|rules|height|align|summary|bgcolor|background|bordercolor],-tr[rowspan|width|height|align|valign|bgcolor|background|bordercolor],tbody,thead,tfoot,#td[colspan|rowspan|width|height|align|valign|bgcolor|background|bordercolor|scope],#th[colspan|rowspan|width|height|align|valign|scope],caption,-div[align],-span,-h1,-h2,-h3,-h4,-h5,-h6,hr[size|noshade],-font[face|size|color],bdo,col[align|char|charoff|span|valign|width],colgroup[align|char|charoff|span|valign|width],small,tt,big,address,pre',
init_instance_callback: "initInstanceCallback",
content_css: "/PolicyAtlas/tiny_mce/themes/advanced/skins/default/richtextedt.css",
formats : {
    alignleft : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div', 'classes' : 'alignleft' },
    aligncenter : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div', 'classes' : 'aligncenter' },
    alignright : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div', 'classes' : 'alignright' },
    alignfull : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div', 'classes' : 'alignfull' },
    bold : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,table', 'inline' : 'span', 'classes' : 'bold' },
    italic : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,table', 'inline' : 'span', 'classes' : 'italic' },
    underline : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,table', 'inline' : 'span', 'classes' : 'underline' },
    strikethrough : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,table', 'inline' : 'span', 'classes' : 'strikethrough' },
    fontname : { 'selector' : 'h1,h2,h3,h4,h5,h6,td,th,div,table', 'inline' : 'span', 'toggle': false, 'styles' : {'font-family' : '%value'}},
    fontsize : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,table', 'inline' : 'span', 'styles' : {'font-size' : '%value'}},
    forecolor : { 'selector' : 'p,h1,h2,h3,h4,h5,h6,td,th,div,table', 'inline' : 'span', 'styles' : {'color' : '%value'}},
    hilitecolor : { 'selector' : 'h1,h2,h3,h4,h5,h6,td,th,div,table', 'inline' : 'span', 'toggle': false, 'styles' : {'background-color' : '%value'}}
}});
```

**Comment by rimpleshah** [comment]
<%
boolean isStandard=!"simple".equalsIgnoreCase((String)request.getAttribute("rte_profile"));
boolean isAutoFill="true".equalsIgnoreCase((String)request.getAttribute("autofill"));
String pluginList=(isAutoFill?"autofill,":"")+(isStandard?"advimage,":"")+"table,paste,spellchecker,searchreplace,print,fullscreen,visualchars,nonbreaking,inlinepopups,lists,advlist,olstartat";
String attrResizing = (String)request.getAttribute("resizing");
String attrResizeHorizontal = (String)request.getAttribute("resizeHorizontal");
boolean isResizing = "true".equalsIgnoreCase(attrResizing) || attrResizing == null; 
boolean isResizeHorizontal = "true".equalsIgnoreCase(attrResizeHorizontal) || attrResizeHorizontal == null;
String onInit = (String)request.getAttribute("onInit");
String onResize = (String)request.getAttribute("onResize");
boolean isWordCleanupEnabled = pagecode.PageCodeBase.isMSWordCleanupEnabled();
%>

**Comment by rimpleshah** [comment]
When I copy paste from MS word normally it is working. But when I copy bullets and tables, formatting is disturbed. There are exceptions generated when copying. and font size / type is not reecognized. I tried all possible combination of properties. 
why is it happening?
What is the way out?
Is there a work around? 
Will this problem be solved if I upgrade to later version?

**Comment by rimpleshah** [comment]
Exceptions generated:

"<p></p>
<p></p>
<p style="text-align: center;" align="center"><strong><span style="color: black;">Privileged and Confidential-cleanup-false</span></strong><strong><span style="color: black;"><br /> <strong>Attorney Work Product</strong></span></strong></p>
<p class="MsoNormal"><span style="mso-fareast-font-family: 'Times New Roman'; color: black;">&nbsp;</span></p>
<p class="MsoNormal"><strong><span style="color: #888888;">CLG</span></strong></p>
<p class="MsoNormal" style="text-align: center;" align="center"><span style="color: black;">&nbsp;</span></p>
<p style="margin-bottom: .0001pt; text-align: center;" align="center"><span style="color: black;">&nbsp;</span></p>
<p style="margin-bottom: .0001pt; text-align: center;" align="center"><strong><span style="color: black;">LEGAL HOLD NOTICE</span></strong></p>
<p><span style="color: black;">&nbsp;</span></p>
<p style="margin-bottom: .0001pt; mso-outline-level: 1;"><strong><span style="color: black;">From: $MatterAttorney</span></strong></p>
<p style="margin-bottom: .0001pt;"><strong><span style="color: black;">Subject: $MatterName</span></strong></p>
<p style="margin-bottom: .0001pt;"><strong><span style="color: black;">Litigation Matter #: $MatterID</span></strong></p>
<p style="margin-bottom: .0001pt;"><span style="color: black;">&nbsp;</span></p>
<p style="margin-bottom: .0001pt;"><strong><span style="color: black;">Recipients of this notice: $Recipients</span></strong></p>
<div class="MsoNormal" style="text-align: center;" align="center"><hr size="2" /></div>
<p><span style="color: black;">&nbsp;</span></p>
<p style="margin-bottom: 12.0pt;"><strong><span style="color: black;">This Legal Hold Notice (&ldquo;Hold Notice&rdquo;) contains important information about your obligation to preserve and protect documents and other information related to this lawsuit. Please read this Hold Notice in its entirety, and then click on the link below to confirm your understanding of and agreement to comply with the terms of this Hold Notice.</span></strong></p>
<p><span style="color: black;">$ConfirmationInstruction</span></p>
<p class="MsoNormal"><span style="mso-fareast-font-family: 'Times New Roman'; color: black;"><br /> <br /> If you are responding from a&nbsp;<span class="mceitemhidden">mobile device (e.g., </span><span class="mceitemhiddenspellword1">iPhone</span><span class="mceitemhidden">, iPad, Android, Blackberry, or tablet) </span>or from outside of the Travelers firewall, please respond by email. Indicate whether you understand and agree to comply with the terms of this Hold Notice using a one-word response &ndash; Yes or No &ndash; with no other words or punctuation.</span></p>
<p><span style="color: black;">&nbsp;</span></p>
<p><strong><span style="color: black;">The Reason You Have Received This Hold Notice</span></strong></p>
<p><span style="color: black;">You have received this Hold Notice because you have been identified as a person who may be in possession, custody, or control of information potentially relevant to the above-referenced lawsuit. It is expected that you will help preserve and protect such information from inadvertent destruction, including during your business area&rsquo;s annual records cleanup event. Please check your </span><a href="http://atlas.prodlb.travp.net/PolicyAtlas/faces/pages/client/communication.jsp?tabSelection=holdNotices#com.secretseal.gwt.communication.client.holdnotice.HoldNoticeInboxScreen">My Holds</a><span style="color: black;"> page to see a complete list of all currently active Hold Notices that apply to you.</span></p>
<p><strong><span style="color: black;">What is the Case About and What Needs to be Preserved?</span></strong></p>
<table class="MsoNormalTable" style="border-collapse: collapse; border: none; mso-border-alt: solid black .75pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 0in 0in 0in;" border="1" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 101.4pt; border: solid windowtext 1.0pt; background: #CCCCCC; padding: 0in 5.4pt 0in 5.4pt;" width="135" valign="top">
<p><strong><span style="font-size: 11.0pt; color: black;">Lawsuit Description</span></strong></p>
</td>
<td style="width: 281.4pt; border: solid windowtext 1.0pt; border-left: none; padding: 0in 5.4pt 0in 5.4pt;" width="375" valign="top">
<p class="MsoNormal" style="margin-bottom: 6.0pt;"><span style="mso-fareast-font-family: 'Times New Roman'; color: black;">$MatterDescription</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1;">
<td style="width: 101.4pt; border: solid windowtext 1.0pt; border-top: none; background: #CCCCCC; padding: 0in 5.4pt 0in 5.4pt;" width="135" valign="top">
<p><strong><span style="font-size: 11.0pt; color: black;">Description of Information to Preserve</span></strong></p>

**Comment by rimpleshah** [comment]
I tried various combincations of below mentioned properties, but it didnt work:

paste_use_dialog : false,
paste_auto_cleanup_on_paste : true,
paste_convert_headers_to_strong : false,
paste_strip_class_attributes : "all",
paste_remove_spans : true,
paste_remove_styles : true,
paste_retain_style_properties : "",
fix_list_elements : true,
paste_text_sticky : true,
paste_remove_styles_if_webkit: true,
valid_elements :"*[*]",

**Comment by rimpleshah** [comment]
Exception:

  <w:LsdException Locked="false" Priority="0" QFormat="true" Name="Normal"/>
  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 1"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 2"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 3"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 4"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 5"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 6"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 7"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 8"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 9"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"

**Comment by rimpleshah** [comment]
Tinymce version used: 3.5.11

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
