### ISSUE TITLE
Only strong tag, it replaces b

### ISSUE THREAD

**Issue by copenhagen72** [tinymce/tinymce#3226]
By default TinymCE uses `<strong>` for bold text. I tried correct example from SO to replace `<strong>` to `<b>`:
`    formats: {
        bold: {inline: 'b'}, 
    },`

As I result I see `p > b` instead of `p > strong` in tag navigation line, as it should be, but still have `<strong>` in code explorer.
![image](https://cloud.githubusercontent.com/assets/2892011/18871503/4cf8b1e2-84be-11e6-8e5d-5b6ce575ae1b.png)

**Comment by spocke** [comment]
You also need to configure extended_valid_elements by default b gets converted to strong.
