### ISSUE TITLE
[Contextmenu] When selecting image and opening contextmenu with rightclick the image is deselected

### ISSUE THREAD

**Issue by TuningGuide** [tinymce/tinymce#3227]
The following code is preventing that an image stays selected if im right clicking on it.
I suggest to add something like:  && editor.selection.getNode().textContent != ""

```
/**
         * WebKit/Blink on Mac has the odd behavior of selecting the target word or line this causes
         * issues when for example inserting images see: #7022
         */
        if (tinymce.Env.mac && tinymce.Env.webkit) {
            if (e.button == 2 && doc.caretRangeFromPoint) {
                editor.selection.setRng(doc.caretRangeFromPoint(e.x, e.y));
            }
        }
```

**Comment by TuningGuide** [comment]
I have another improvement suggestion: When selecting a word +  right click -> Insert / edit link, the selected word could be inserted as title into the popup. Right now the word is deselected and the title stays blank.

**Comment by valorize** [comment]
I just experienced the same issue.

**Comment by valorize** [comment]
But the code changed a bit since then. The current unfixed code is:
```
editor.on('mousedown', function (e) {
		if (isMacWebKit() && e.button === 2 && !isNativeOverrideKeyEvent(e)) {
			if (editor.selection.isCollapsed()) {
				editor.once('contextmenu', function (e) {
					editor.selection.placeCaretAt(e.clientX, e.clientY);
				});
			}
		}
	});
```
The issue seems only to occur on inline mode. Apparently it tries to set the cursor to the opened context menu as the context menu is at e.clientX and e.clientY

**Comment by valorize** [comment]
A quick fix is to use e.clientX-1 as doc.caretRangeFromPoint(clientX, clientY); otherwise returns the first link of the context menu.

**Comment by valorize** [comment]
@jayarjo Do you think the quick fix is good enough for a merge request or should another approach be taken?
