### ISSUE TITLE
[Links] Develop a plugin which makes links in editor linkable

### ISSUE THREAD

**Issue by TuningGuide** [tinymce/tinymce#3229]
I would like to develop a plugin which enables links to behave like:
if plugin is active a click on a link should lead to the href, right click should open the contextmenu.

Do you have suggestions how I could do that?

**Comment by jayarjo** [comment]
We've something similar in works now. Do you have more details on how you see it functioning? We will bear it in mind.

**Comment by TuningGuide** [comment]
I think it should be either switchable by a plugin and / or when you keep ALT pressed during click on link that you get directed to src.
