### ISSUE TITLE
Unable to insert text in inline editor on Safari

### ISSUE THREAD

**Issue by zlepper** [tinymce/tinymce#3232]
I initialize my editor with this:

``` javascript
tinyMCE.init({
     selector: `#${tinyMCEEditor.id}`,
     inline: true 
})
```

Now when i use it in Chrome it works fine. However when i attempt to use it in safari on OSX the following happens:
- The menu with all the buttons opens
- The input looks like it's focused as intended. 
- Typings doesn't work
- No caret is shown. 

I'm using version 4.4.1 of tinymce.
I have tested on safari for OSX 10.10.5 and OSX 10.12.
Neither of which are working. 
Using normal (iframe) mode everything works as intended. 

Additionally the example for inline mode on the tinymce webpage works fine.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by watway** [comment]
I have come across the same problem with Safari when using the `draggable` attribute.  Should see the problem here [http://fiddle.tinymce.com/3Cfaab/6](url)

**Comment by ovcharenkokatia** [comment]
Hello, I have the same problem. Does anyone find a solution to fix it?

**Comment by pribilinskiy** [comment]
@spocke this issue should not have the label "needs more info" anymore

@wayway created a fiddle.

We also suffer from the same problem when using TinyMCE along with jQuery UI Sortable plugin. [Disabling sortables](http://api.jqueryui.com/sortable/#method-disable) before TinyMCE initialization doesn't help

**Comment by revaxarts** [comment]
Had the same problem and found a CSS rule which may cause the problem. Adding
`-webkit-user-select: text` to the draggable div fixes it for me:
http://fiddle.tinymce.com/3Cfaab/15
You may add an `!important` rule as well. Hope someone finds it useful.

@spocke @wayway @ovcharenkokatia @pribilinskiy

**Comment by fyrkant** [comment]
A solution seems to have been found by @revaxarts above so I'm closing this issue.
