### ISSUE TITLE
iOS 10 - Pressing Keyboard Arrow key scrolls the browser to the bottom of the page

### ISSUE THREAD

**Issue by kzink** [tinymce/tinymce#3242]
Using an IOS device (using 10.0.2 currently) w/ a bluetooth keyboard.

1) Load up a page with Tinymce on your device: (this works: https://www.tinymce.com/docs/demo/basic-example/) 
2) Focus Tinymce instance.
2) Hit arrow key on keyboard.
3) Browser will scroll to the bottom of the page.

Couple of observations: If you scroll back up to the Tinymce content area, the cursor is in fact moving even though you can't see it. 

The issue seems to only affect Tinymce instances that are below the initial viewport of the browser. As an example, the editor at the top of https://www.tinymce.com/ doesn't scroll to the bottom when keyboard arrows are pressed.

**Comment by Josheua** [comment]
I am having this same issue. It was not present in iOS 9, but is in iOS 10. Has anyone made any progress on this issue?

**Comment by Josheua** [comment]
Has anyone made any progress with this issue? I run a small science fiction community driven website and our site relies heavily on custom forms using TinyMCE and this bug completely prevents our ability to edit stuff on the go using the iPad with bluetooth keyboards. Any assistance with this would be extremely helpful!

**Comment by Josheua** [comment]
Here is a video of the issue:

https://m.youtube.com/watch?v=mp9tpAy6Asg

**Comment by Josheua** [comment]
I have confirmed this issue now for iPhone and iPad using bluetooth keyboard and the Apple Smart Keyboard. This now affects every iOS device using any external input. Can we get any traction on this post? It is completely limiting my ability to use TinyMCE for anything on iOS.

**Comment by fyrkant** [comment]
This seems to be related to the bug in webkit discussed in this issue: https://github.com/tinymce/tinymce/issues/2557 .

**Comment by agupta1989** [comment]
"Jumping to the bottom of page" This behaviour was observed once you try to tap / touch on to Menubar dropdown. As soon as I tried to touch File menu or Format menu, it immediately jumps to bottom of the page.

**Comment by claviska** [comment]
Here's a minimal test case: http://fiddle.tinymce.com/HRfaab/4

This makes it very easy to reproduce. It seems to only affect content from the first heading down. For example, place the cursor at the top of the document and press down multiple times. Everything works fine until the cursor reaches the heading.

It's worth mentioning that it's not scrolling to the bottom. With enough content, you'll notice an incremental scroll downwards. It may be that the scroll position or an element's offset is being measured incorrectly.

**Comment by claviska** [comment]
Just tested this in the WordPress admin panel (default install, same dummy content) and I can confirm the same behavior, so this affects both default and inline modes.

**Comment by claviska** [comment]
@fyrkant I'm not sure this is a third party fix. It looks like both Webkit issues ([152332](https://bugs.webkit.org/show_bug.cgi?id=152332), [152541](https://bugs.webkit.org/show_bug.cgi?id=152541)) were marked fixed/resolved yet the problem persists.

Could you take another look at it?

**Comment by Josheua** [comment]
I can confirm this issue remains present in iOS 10.3.2 and 10.3.3 Beta 3.

**Comment by Josheua** [comment]
This issue persists in iOS 11 Beta 1 as well. Are we certain this issue is apple’s and not something with TinyMCE?

**Comment by dgfraser** [comment]
I see this issue editing a confluence page in safari and in chrome on an iPadPro 10.3.3 with smartkeyboard. Very annoying.

**Comment by Josheua** [comment]
Issue continues to be present in iOS 11 final release. Both Chrome and Safari affected. Is there any update on troubleshooting this issue and or identifying if it is related to something on TinyMCE or Apple’s side?

**Comment by DigitalLeaves** [comment]
Yes, I can confirm this issue. For me, it’s especially annoying while trying to write a Wordpress post on my iPad Pro with the smart keyboard.

**Comment by jagooch** [comment]
I confirm the issue with Chrome and Apple Smart Connector keyboard. IOS 11 and Chrome iOS current version.

**Comment by maxledoux** [comment]
Has anyone fixed this yet?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
