### ISSUE TITLE
Resizing table column issue after indenting the table

### ISSUE THREAD

**Issue by fauzi16** [tinymce/tinymce#3254]
I found an issue that regarding with indenting table, below are steps to reproduces
1. Create Table
2. Move the pointer to before of table
3. Click on Increase Indent  button
4. Resize the table by dragging the table border.
5. Notice That table cannot be resized freely as before indented.

Please look at the record
![table issue](https://cloud.githubusercontent.com/assets/20159853/19182632/785c8880-8c9e-11e6-9c74-9d7d8b7c50f5.gif)

Could tinyMCE please resolve this ?

Thanks.

**Comment by fyrkant** [comment]
Thank you for the extremely clear bug report, love the gif! 👍

**Comment by fauzi16** [comment]
Hi @fyrkant ,

Is this issue still being fixed ?

I would like to get the patch when this has already been solved

**Comment by fyrkant** [comment]
This has been fixed and the fix will be included in a coming release. You can download the latest nightly build [from this page](https://www.tinymce.com/download/additional-downloads/).
