### ISSUE TITLE
editor.getContent() deactivates visualchars

### ISSUE THREAD

**Issue by berengerzyla** [tinymce/tinymce#3256]
Hi!

I noted that calling a `getContent()` on an editor where the `visualchars` plugin is installed and the visualization of hidden characters is actually turned ON will turn OFF the display, without reactivating it after.
This is particularly annoying in WordPress, where WordPress itself and plugins call the getContent() quite often, making the display of hidden characters last only several seconds, before being toggled OFF.
Is there a way to correct this?
Thank you!

TinyMCE version used: 4.4.1 (2016-07-26)

How to reproduce:

Init an editor with the visualchars plugin activated.
Insert hidden characters (ie. &nbsp; or else)
Toggle the visualchars ON (to display the hidden characters)
Call the editor.getContent(), the visualchar will toggle OFF, to stay OFF.

**Comment by berengerzyla** [comment]
No update yet?

**Comment by tinydylan** [comment]
Hi,

Apologies for the delay in responding. I'm unable to reproduce this issue in the latest version of TinyMCE (5.2.1). I believe the issue has been corrected, so I'd suggest updating. However, if you can still see this issue, please let us know.

Many thanks.
