### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clearBars' of undefined

### ISSUE THREAD

**Issue by wuifdesign** [tinymce/tinymce#3260]
If i disable "object_resizing" for tables, but loading the tables plugin, i always get an JS-Error if i try to select content of more than one TableCell.

Reproduce with this code:

``` javascript
tinymce.init({
    selector: 'textarea',
    object_resizing : 'img',
    plugins: [ 'table' ]
});
```

Problem seams to be in `tinymce/js/tinymce/plugins/table/classes/Plugin.js` line `350`:

```
resizeBars.clearBars();
```

but `resizeBars` is undefined if "object_resizing" isn't enabled for tables. It gets set at `tinymce/js/tinymce/plugins/table/classes/Plugin.js` line `35` (inside an if)

**Comment by ov-developer** [comment]
I had the same problem. One solution is to replace the table plugin with the 4.3.1 version. It looks as if something at the fixes of 4.3.2 went wrong.

**Comment by spocke** [comment]
We fixed this in master. Will soon release a version that has this fix included.

**Comment by Afraithe** [comment]
This is in 4.5.2.
