### ISSUE TITLE
Ignore custom attributes

### ISSUE THREAD

**Issue by speculees** [tinymce/tinymce#3261]
Hello, inside of tinymce editor I have the following HTML:

&lt;p data-merged="yes"&gt;some lorem ipsum text &lt;/p&gt; &lt;p data-merged="yes"&gt;Lorem ipsum dolor sit amet,pri salutatus tincidunt reformidans id, ex nec magna epicuri delicata. Sea ne melius deseruisse, vix ut libris causae tractatos. &lt;strong data-merged="yes"&gt;Vix &lt;/strong&gt; facete virtute eu, ea iriure aliquip adversarium usu. Augue animal nostrud ei mei.&lt;/p&gt;

I need to know which new elements are added. So when I press enter after "some lorem ipsum text" i expect to get the following html:

&lt;p data-merged="yes"&gt;some lorem ipsum text &lt;/p&gt; <strong>&lt;p&gt;&amp;nbsp;&lt;/p&gt;</strong> &lt;p data-merged="yes"&gt;Lorem ipsum dolor sit amet,pri salutatus tincidunt reformidans id, ex nec magna epicuri delicata. Sea ne melius deseruisse, vix ut libris causae tractatos. &lt;strong data-merged="yes"&gt;Vix &lt;/strong&gt; facete virtute eu, ea iriure aliquip adversarium usu. Augue animal nostrud ei mei.&lt;/p&gt;

However I get:

&lt;p data-merged="yes"&gt;some lorem ipsum text &lt;/p&gt; <strong>&lt;p data-merged="yes" &gt;&amp;nbsp;&lt;/p&gt;</strong> &lt;p data-merged="yes"&gt;Lorem ipsum dolor sit amet,pri salutatus tincidunt reformidans id, ex nec magna epicuri delicata. Sea ne melius deseruisse, vix ut libris causae tractatos. &lt;strong data-merged="yes"&gt;Vix &lt;/strong&gt; facete virtute eu, ea iriure aliquip adversarium usu. Augue animal nostrud ei mei.&lt;/p&gt;

I need to get the <strong>&lt;p&gt;&amp;nbsp;&lt;/p&gt;</strong> without custom data-merged attributes so I can know which elements are new.

**Comment by donShakespeare** [comment]
As reported somewhere else, it appears that the return key clones the previous node with all its attributes. Maybe a plugin can alter that behaviour.... I'll check.

**Comment by spocke** [comment]
We want to clone the styles and some users might want to clone all attributes as well there is an event fires when new blocks gets created by enter though that might be used.
