### ISSUE TITLE
Firefox: Cursor is not moving back/forth by using arrow key when we have the input type button 

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3265]
Firefox: Cursor is not moving by using arrow key when we have the input type button. This is happening only in Firefox and working fine in other browsers. I have inserted the button by using source code editor.

**Comment by tinydylan** [comment]
Hi,

I am able to reproduce this issue on Firefox 75 on macOS 10.15.4, using TinyMCE 5.2.1. It appears to behave correctly on Chrome 80.

Open [this demo page](https://www.tiny.cloud/docs/demo/full-featured/)

Set the following content using the source code editor.
```
<p>hello1</p>
<form>
<p><input type="button" value="my button" /></p>
<p>hello2</p>
</form>
```

Place the caret after "hello2" and press up. 
Expected: caret to the right of "my button". 
Actual: caret to the right of "hello1".

Place the caret before "hello1" and press down.
Expected: caret to the left of "my button".
Actual: caret to the left of "hello2".

Click to the left of "my button".
Expected: caret to the left of "my button".
Actual: caret to the right of "my button".

Click to the right of "my button". Press left.
Expected: caret to the left of "my button".
Actual: caret to the right of "hello1".

Thanks!
