### ISSUE TITLE
HTML style for activeEditor.windowManager.alert

### ISSUE THREAD

**Issue by dsifford** [tinymce/tinymce#3270]
Hi there,

Just a friendly suggestion for the suggestion box: It would be nice to be able to apply basic HTML style to an alert message (bold, italics, etc). Possibly consider allowing sanitized HTML rather than just a string?

Thanks so much.

**Comment by dsifford** [comment]
Still interested in this. Most of all, the ability to simply add a linefeed character to an alert box. Currently all whitespace characters including tabs, linefeeds, etc are converted into a single space.

**Comment by lostkeys** [comment]
We're cleaning up old feature requests and being able to [use HTML in alerts are available in TinyMCE 5](https://www.tiny.cloud/docs/ui-components/dialogcomponents/#alertbanner).
