### ISSUE TITLE
Pasting text from notepad adds unnecessary empty paragraph in Chrome/Opera

### ISSUE THREAD

**Issue by viktorzen** [tinymce/tinymce#3277]
reproduction steps in chrome/opera with tinymce 4.4.3

1 integrate tinymce without any plug-ins

```
tinymce.init({
  selector: 'textarea',
});
```

2 copy paste from notepad

```
test

test
```

3 paste "test\r\n\r\ntest" into tinymce

tinymce creates an extra empty paragraph in Chrome/Opera but not in Edge

```
<p>test</p>
<p> </p>
<p>test</p>
```

**Comment by jayarjo** [comment]
We are addressing this at the moment. Check the referenced issue for the updates.
