### ISSUE TITLE
Image not deleted when following a block level element (webkit)

### ISSUE THREAD

**Issue by adamayres** [tinymce/tinymce#3279]
Issue on: TinyMce 4.1.8-4.4.3, Chrome 53, Safari 10
Works on: IE11, Firefox
### Steps to reproduce
1. Open fiddle: https://jsfiddle.net/magicaj/muz06az0/1/
2. Place cursor after image
3. Press delete
### Expected results

Image is deleted.
### Actual results

Image is not deleted, image is instead merged into preceding block level element.
### Notes
- Last working version 4.1.7 (breaks in 4.1.8+ up to latest 4.4.3). 
- Working fiddle in 4.1.7: https://jsfiddle.net/magicaj/y30gfhyz/
- Possibly related to: https://github.com/tinymce/tinymce/commit/7519f9c4bef9ced1564fec03a6994e5f36b09ca4 or https://github.com/tinymce/tinymce/commit/b7459a5d6d73a86db743d4285d14ce3be4795fd8

**Comment by tinydylan** [comment]
Hi,

I am unable to reproduce this issue on the latest TinyMCE, using [this example code](http://fiddle.tinymce.com/Rghaab). It's likely that this issue has been corrected since you logged this issue.

If the issue persists, please let us know and we'll reopen the case.

Thanks,

Dylan
