### ISSUE TITLE
Incorrect RegExp in AddValidChildren method (childRuleRegExp)

### ISSUE THREAD

**Issue by rzymek01** [tinymce/tinymce#3280]
One can find in the TinyMCE docs that custom elements are supported.
However TinyMCE does not support valid names of custom elements. In particular, there is a bug in this RegExp: `var childRuleRegExp = /^([+\-]?)(\w+)\[([^\]]+)\]$/;` because `\w` is equivalent to the `[A-Za-z0-9_]`. As a result the valid custom element name (which has to contain dash "-") will not be matched.

Rules of valid custom element name can be found in the following spec: https://www.w3.org/TR/custom-elements/#valid-custom-element-name

PS. In the same method `addValidChildren` the following line is redundant
`parent = children[matches[2]];`

**Comment by spocke** [comment]
Yes, we should probably support at least - as a separator.
