### ISSUE TITLE
Pasting text from notepad puts text into divs instead of paragraphs in Edge

### ISSUE THREAD

**Issue by viktorzen** [tinymce/tinymce#3287]
reproduction steps in Edge with tinymce 4.4.3

1 integrate tinymce with the paste plugin

```
tinymce.init({
  selector: 'textarea',
  plugins: 'paste code'
});
```

2 Copy text from notepad into Microsoft Edge

```
test

test
```

3 Paste "test\r\n\r\ntest" into tinymce in Microsoft Edge
tinymce puts the text into divs instead of paragraphs in Microsoft Edge

```
<div>test</div>
<div>test</div>
```

**Comment by jayarjo** [comment]
We are addressing this at the moment. Check the referenced issue for the updates.
