### ISSUE TITLE
Fullscreen issue, mce-fullscreen is removed when inserting image, special char, video, etc that use popup

### ISSUE THREAD

**Issue by fauzi16** [tinymce/tinymce#3289]
Hi,

When performing some third party product test, I found fullscreen issue. See Attachment, When fullscreen is enabled and inserting image, video, anchor that use popup, they remove mce-fullscreen class (See Attachment)
![fullscreen issue-html](https://cloud.githubusercontent.com/assets/20159853/19586718/1b9aff70-9782-11e6-8a5d-9ca0c367b648.gif)

It means the css rules to control z-index of tinymce container isn't used in that point and makes other div elements around it which has bigger z-index value will stack on it.

![fullscreen issue](https://cloud.githubusercontent.com/assets/20159853/19586716/1a1c4122-9782-11e6-87ab-b2e6b374b9fe.gif)

I tested that on https://www.tinymce.com, seems how the website menu stacks on tinyMCE toolbar, and it makes me can't click any tinymce's toolbar button.

I have checked fullscreen plugin code and found that it adds mce-fullscreen class for 3 different divs
```
var body = document.body, documentElement = document.documentElement, editorContainer;
editorContainer = editor.getContainer();
...
DOM.addClass(body, 'mce-fullscreen');
DOM.addClass(documentElement, 'mce-fullscreen');
DOM.addClass(editorContainer, 'mce-fullscreen');
```

and they (performing insert with popup) remove 2 of them

```
DOM.addClass(body, 'mce-fullscreen');
DOM.addClass(documentElement, 'mce-fullscreen');
```

**Comment by fauzi16** [comment]
Seems like duplicate issue, Another issue has been raised earlier https://github.com/tinymce/tinymce/issues/3135

**Comment by fyrkant** [comment]
Yep, a duplicate, and it has already been fixed! Will be included in the next release. ✌️

**Comment by fauzi16** [comment]
@fyrkant, can i get the patch ?

**Comment by fyrkant** [comment]
@fauzi16 Yes, you can download the nightly build from  [here](https://www.tinymce.com/download/additional-downloads/)!

**Comment by fauzi16** [comment]
@fyrkant thanks, I have identified the changes in Window.js and included in tinymce.js, and that works fine.

But, Could I know when the next version will be released ?

**Comment by MichaelFromin** [comment]
@fauzi16 Current plans are to have the next release out in December.
