### ISSUE TITLE
Meta data returned from custom file browser is not handled correctly/at all.

### ISSUE THREAD

**Issue by sigmatec** [tinymce/tinymce#3297]
According to the documentation here: [https://www.tinymce.com/docs/configure/file-image-upload/#file_picker_callback](https://www.tinymce.com/docs/configure/file-image-upload/#file_picker_callback) when linking to a URL, we are supposed to be able to use meta data value "text" to set the "Text to display" field.  No matter what I pass back in this, nothing happens.

Images work fine using the "alt" parameter, but nothing seems to work for adding a standard hyperlink.

Either the documentation needs to be updated with the correct identifiers (ideally for all fields), or there is a bug where it is not handling the meta data upon return.

**Comment by jayarjo** [comment]
Correct name for the given meta key depends on the dialog that you would like it to insert into. For link dialog it should be either `text` or `title`.

Seems to work in this fiddle: http://codepen.io/tinymce/pen/QKXqJm.

**Comment by sigmatec** [comment]
Ugh, I'm so sorry. This issue has been plaguing me for months to the point where I assumed it must be a bug. Your fiddle brought my attention to what the actual issue was, which was entirely my fault. Please accept my apologies for wasting your time.
