### ISSUE TITLE
Remove styles removing unrelated empty tags

### ISSUE THREAD

**Issue by ETPac** [tinymce/tinymce#3299]
Steps to reproduce:

1) paste following code into source `<p>here is some text that I<strong> <i></i>am testing with</strong></p>`
2) place cursor before "testing"
3) click the "bold" style to deselect bold style.

notice that not only "texting" is unbolded and the <i></i> tags have been removed from the source. 

Thank you for your time!

**Comment by jayarjo** [comment]
TinyMCE internally sanitizes the content, stripping away invalid tags and empty blocks. So what you observe is intended. You can customise what is being considered valid or invalid via [Content Filtering](https://www.tinymce.com/docs/configure/content-filtering/) options.

**Comment by ETPac** [comment]
We are using *[*] for valid elements so this should not be an issue.  Is there a something else that would allow for the bold styling removal to remove these elements?
