### ISSUE TITLE
"less than" entity character followed immediately by alphanumeric causes page to become unresponsive

### ISSUE THREAD

**Issue by etalcott** [tinymce/tinymce#3300]
As the title says, if the source code contains "&lt;" directly followed by an alphanumeric character and enough additional content, the page will stop responding prior to fully loading.

I have reproduced this in the simplest possible form. I was able to reproduce it on fiddle.tinymce.com and codepen.io, but seeing as the pages became unresponsive as soon as I did (and now every time I load the fiddle page), I can't link to them. In the code below, before 0.05 should be the entity character for less than, not a literal less than symbol (so you'll have to edit it after copy/pasting).

`<!doctype html>
<html>
<head>
  <link type="text/css" rel="stylesheet" media="screen" href="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.4.3/skins/lightgray/skin.min.css" />
<script language="javascript" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.4.3/tinymce.min.js"></script>

<script language="javascript" type="text/javascript">

tinymce.init({
  selector: 'textarea',
  height: 500,
  plugins: [
    'code'
  ],
  toolbar: 'image'
});
</script>

</head>
<body>

<TEXTAREA NAME="descr" ROWS=20 COLS=80 class="wysiwyg">
&lt;0.05. Optimizing torque should result in screws having the highest torque test test
</TEXTAREA>

</body>
</html>`

Once you have reproduced it, any of the following changes to the textarea content will cause the page to load fully:

1) Add any non-alphanumeric character between the &lt; and the 0.

2) remove sufficient characters after it in the textarea. for me, simply removing "test test" gets it to load, though it does take 10 or 11 seconds, compared to sub-1-second if you do step #1.

It's almost as if that specific string is causing some incredibly inefficient processing of the remaining content in the textarea, so the more content there is, the more likely the page is to hang.

**Comment by wilkesreid** [comment]
Are there any updates on this?

**Comment by EZWrighter** [comment]
reduced test case: <4 blah blah blah blah blah blah <7 blah blah blah blah blah blah
Enter that in the source editor of tinymce, click "OK" and browser tab will crash in Chrome.  CPU will max.

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by lujuliang** [comment]
Hi @fyrkant Could you tell me which version fixed this issue? I used Version:4.5.9 and reproduced this issue.
