### ISSUE TITLE
Can't set (or change) the title for a menubutton.

### ISSUE THREAD

**Issue by Luke-SF** [tinymce/tinymce#3301]
If you look through the example full-featured codepen (https://www.tinymce.com/docs/demo/full-featured/), you can find the button for "undo" for example, and make its popup text whatever you want:

tinymce.activeEditor.theme.panel.settings.items[1].items[0].items[0].items[0].settings.tooltip = "hello! changed"
That is the undo button as you can see if you inspect:
tinymce.activeEditor.theme.panel.settings.items[1].items[0].items[0].items[0].$el[0]

However, you can neither change nor set the default for the formats menu button's popup:
tinymce.activeEditor.theme.panel.settings.items[1].items[0].items[1].items[0].$el[0] //the formats button
tinymce.activeEditor.theme.panel.settings.items[1].items[0].items[1].items[0].settings.tooltip = "This will never show";

**Comment by jayarjo** [comment]
This is not how you customise text strings. I highly discourage anyone following this approach. 

As an alternative you could customise english language pack with your own strings and load it as any other language pack. Check [Localize TinyMCE](https://www.tinymce.com/docs/get-started/localize-your-language/).

**Comment by Luke-SF** [comment]
I agree, if there were a tooltip popup on this item it would be preferable to go through the localization function.

However, there is no tooltip, and there needs to be a way to add one to your menu button.
In the style_formats documentation there is no help on how to set the tooltip for it - You can restyle the button to have an icon rather than text, naturally, but if you want to make the button have a tooltip like other buttons there is no option for this :(
https://www.tinymce.com/docs/configure/content-formatting/#style_formats

**Comment by jayarjo** [comment]
We do not currently support tooltips on menu buttons. Maybe you should rephrase your original message to request that. And then we will be able to mark as feature request. It is confusing at the moment.

**Comment by programmin1** [comment]
Menubutton does not support tooltips, really? If so that would be a pretty big bug - and the default font menu and size menus _do_ in fact have handy tooltips shown by default as you can see in this codepen:

http://codepen.io/anon/pen/RoWRWq

**Comment by Luke-SF** [comment]
Can you reopen this bug/feature-request please? There should be some option to set a tooltip for the styles menu.
