### ISSUE TITLE
Media plugin have not title attribut, but the link plugin have it

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3308]
Hey. In media pluginI can enable/disable the ALT attribut
https://www.tinymce.com/docs/plugins/media/#media_alt_source
but here is no TITLE attribut setting.

The link plugin have a TITLE attribut, so its not deprecated.
https://www.tinymce.com/docs/plugins/link/#link_title

**Comment by rgriffith** [comment]
I second this request. [According to WCAG 2.0](https://www.w3.org/TR/WCAG20-TECHS/H64.html), `<iframe>` elements should have a title attribute for accessibility.
