### ISSUE TITLE
Formatting removed when deleting multiple lines

### ISSUE THREAD

**Issue by gitsnuit** [tinymce/tinymce#3309]
Could only reproduce this in Firefox (Tested with FF 49.0.2)
Tested with and without powerpaste plugin with Tiny 4.4.3

1. Apply styling (Bold, italic etc)
2. Type 3 lines
3. Select the last 2 lines and remove them (Delete or backspace)
4. Type a new line

*Result*: No formatting is applied

**Comment by fyrkant** [comment]
This seems to be a problem related to inconsistencies in how the browsers handle deleting text and a fix would probably involve overriding the native delete event and implement our own functionality. This is not something that we can fix in the nearby future, but we are aware of the problem! Thanks for the bug report!

**Comment by fcherny** [comment]
I believe I'm having the same issue:
1) Set font size to 14pt. Type a line of text.
2) Press carriage return twice (font size is still set to 14pt)
3) Press delete (backspace) once.
4) I go back to the previous line but the font size has changed to the default (9pt). It should be set to size 14pt.
I'm running in Chromium Embedded Framework.
Does this sound like the same issue to you?
