### ISSUE TITLE
Font-family and font-size resets when text color is removed

### ISSUE THREAD

**Issue by gitsnuit** [tinymce/tinymce#3310]
Checked with 
4.4.3 with and without powerpaste (2.1.0 + 2.1.7-69)
Chrome 54
Firefox 49.0.2

1. Add font-family + font-size to the toolbar
2. Define a font-family + size
3. Choose a font color
4. Hit enter
5. Remove font color

_Result_ Font-family and font-size is removed

**Comment by jayarjo** [comment]
What do you mean by `Font-family and font-size is removed`? Removed from where? The text seems to retain both - font family and size.

**Comment by MartyBum** [comment]
Instead of e.g. Tahoma this is shown: 
![test](https://user-images.githubusercontent.com/10170481/27737137-56ce180c-5da7-11e7-8043-bda65a71fe8b.png)

**Comment by lostkeys** [comment]
Could not replicate this in the latest 4.x version. Closing as resolved.
