### ISSUE TITLE
Color Content Selection Issue in IE

### ISSUE THREAD

**Issue by ubaidsaeed** [tinymce/tinymce#3312]
Please check the screenshots.
![1](https://cloud.githubusercontent.com/assets/16667083/20176731/f68317c4-a76a-11e6-812e-d0a866b63566.PNG)
![2](https://cloud.githubusercontent.com/assets/16667083/20176732/f6af6bee-a76a-11e6-9a86-4217bc7f72b2.PNG)
![3](https://cloud.githubusercontent.com/assets/16667083/20176733/f6cfbfe8-a76a-11e6-915e-8ca9cb31e397.PNG)

**Comment by spocke** [comment]
You could try to stick this into your css file:
::selection {
	color: HighlightText;
	background: Highlight;
}

**Comment by ubaidsaeed** [comment]
Thanks it works...
