### ISSUE TITLE
Question to "Help us improve TinyMCE with a 1 minute survey!"

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3317]
Its not possible to register in new "community" on tinymce.com, so I will ask here. There is a survey on tinymce.com:

"At what price would you begin to think a Premium version is TOO EXPENSIVE to consider?"

What means "per end user/month" in the options? What exactly is a "end user"?

**Comment by androb** [comment]
Hi @Daijobou - I was the one running the surveys :)

First of all, it is important to note that the open source version will always be free and we are committed to making it better and better!

But, of course, we have to keep the lights on and eat, etc. so we are always excited to get paying customers... and this survey was part of me trying to understand what is should look like.

Over the years we have considered and sometimes tried different usage metrics to determine price - domains, developers, servers, named users, concurrent users, number of editor loads, number of editor sessions etc. etc. 

I keep coming back to users being the best. We have some customers who are small (1-10 users) and some that literally have hundreds of thousands of users. The small customers tend to not be able to afford much and the big customers tend to have larger budgets. We also invest almost all of our development into front-end JavaScript code that doesn't have much server load ... so to align our development priorities with our customers it makes sense to have some sort of pricing tied to usage.

As to the exact definition of "end user" this is most likely going to be the number of users active in a 30-day period. Something equivalent to what Google Analytics shows as their "30 Day Active User" metric. We do not actually have mechanisms to track this right now, so we are relying on the "honor system" for you to use Google Analytics or similar to purchase the right number of licenses. In time, we may offer a usage measurement plugin to help.

Hope that all makes sense!

FWIW, the survey showed that most people felt $0.50-$0.70/user/month or $6.00-$8.40/user/year was about the right price. About 40% thought it was a bargain and about 40% thought it was getting expensive.... a nice happy medium.

We should be rolling out some more affordable plans around TinyMCE Pro soon. At $29/month right now we realize it is a bit expensive for very small sites.

**Comment by WVEphox** [comment]
Hi @Daijobou 

This is Wynne the community manager--you should be able to make an account by resetting your password. Did you try that? You can find the appropriate link here: https://community.tinymce.com/ForgotPassword

Let me know how that works for you. You should be set once it's done. 

:)

Wynne

**Comment by Daijobou** [comment]
I understand and I was always willing to pay a price for your hard work. But "per user" is a very one-sided system. I think i can't never pay any price for this system. I do not mean that bad or stingy.

Reason: I have a website with very fluctuation registered members. I use tinymce as public advanced "comment" editor. To pay for every this user is for me hard to trackable, not calculable and insane to pay for a community or fansite. That costs in year coult be extremly high.

Make a fixed price per year, maybe without support ticket option and one with priority support tickets. Your system is maybe very good for a newspaper office or greater companies, but not for poeple that use tinymce as editor for comments (forum, guestbook, comments). Like you said, small sites.

The community version must not be free, but payable. I hope you found a good way for this great project.
