### ISSUE TITLE
Setting option "object_resizing" to "false" disables table cell selection by dragging

### ISSUE THREAD

**Issue by morphine00** [tinymce/tinymce#3318]
Setting the option "object_resizing" to false disables the table cell selection by dragging.

As you try to click-and-drag over table cells, repeated instances of the same error pop up in the console log:

`tinymce.min.js:52 Uncaught TypeError: Cannot read property 'clearBars' of undefined(…)`

**Comment by fyrkant** [comment]
This has been fixed in an upcoming release, if you want to get to it now please download the [nightly build](https://www.tinymce.com/download/additional-downloads/). 

If you have anything else you are wondering about, please write a comment and we can open this issue again.
