### ISSUE TITLE
How to use Angular 2 tinymce under SystemJS in Visual Studio?

### ISSUE THREAD

**Issue by RavishankarR** [tinymce/tinymce#3326]
When installing from NuGet package manager, the package gets installed outside the project files folder under the packages folder.

I am working with Angular 2. How do I import the package into the typescript components?

**Comment by fyrkant** [comment]
Hi!

I have unfortunately not used SystemJS enough to help you with that, but if you can change to using the Angular CLI we have a guide on how to use TinyMCE with that [here](https://www.tinymce.com/docs/integrations/angular2/).

**Comment by RavishankarR** [comment]
Thanks for replying @fyrkant 

I did manage to use the package in Angular CLI very easily. But the project I am working on uses SystemJS exclusively. Is there any way I can accomplish importing the package?

**Comment by fyrkant** [comment]
I think think maybe [this could help](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#shim-dependencies) but I like I said I really don't know what I'm talking about with SystemJS, hehe.

**Comment by ddivita** [comment]
I have not tested [this](https://github.com/Ledzz/angular2-tinymce), but perhaps it could get you closer.

**Comment by Afraithe** [comment]
There is an official Angular wrapper project now (tinymce-angular). Closing this ticket, any Angular related issues should be open in that project.
