### ISSUE TITLE
forecolor command

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3328]
Hi I have recently upgraded the tinymce version from 4.3.12 to 4.4.3 and the below mentioned forecolor event is not at all firing. Can you please check and let me know the solution.

editor.on('forecolor', function (args) {
                console.log('forecoor');
            });

**Comment by fyrkant** [comment]
When exactly did it fire in 4.3.12?

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
