### ISSUE TITLE
TiniMCE v4 editor does not take focus by clicking

### ISSUE THREAD

**Issue by sim1-81** [tinymce/tinymce#3329]
Hi,
i'm banging head on this issue. The editor is initialized, but when I click on it, the caret text cursor does not appear so i can't write. It seem like if the editor hasn't been activated.
If i use the "code" plugin to insert HTML, i can write, but once clicked on "Ok" to apply changes, no text appears in the editor. Clicking another time on "code" the HTML is still there, but it doesn't shown.

I tried my code on crhome and firefox and i got the same problem on both.

To configure  my script i followed this guide https://www.tinymce.com/docs/get-started/first-steps/

So i added tinymce v4 by the CDN script
and the following is my init

tinymce.init({
                    selector: 'textarea.tinymce',
                    language_url: '//' + window.location.hostname + '/js/langs/it.js',
                    plugins: 'advlist autolink link image lists charmap print preview code searchreplace',
                    toolbar: ['undo redo searchreplace | cut copy paste | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | formatselect | fontsizeselect | removeformat | code'],
                   
                });

Do you have some idea which can help?

**Comment by fyrkant** [comment]
Can you reproduce the problem in a [fiddle?](http://fiddle.tinymce.com/)?

**Comment by sim1-81** [comment]
unlukliy i can't,

i've already tried to set up a fiddle with my code (http://fiddle.tinymce.com/ZBfaab), but there my tinymce.init() works properly, so i don't know what hurts the editor.

The page which contains the editor has several other script, maybe some of those may cause this issue, but i don't know which could be, because the browser console does not show any error.

If you are interested in solving this weird behavior, I can set up a page in my application where all the scripts are loaded and give you the access. 

I'm really sorry, but for now i was forced to use a different wysiwyg editor.

**Comment by fyrkant** [comment]
It seems like this is an implementation problem on your side, probably some other script getting in the way, and not a problem with TinyMCE, so I am closing this issue.

Please comment if there is something else you are wondering and I can open the issue again.

**Comment by sim1-81** [comment]
i've found the gulty!

The problem was caused by a conflict between tinymce script and [mCustomScrollbar](http://manos.malihu.gr/jquery-custom-content-scroller/).

This conflict makes the tinymce editor not focusable, so i've changed the scrollbar plugin and all works fine.

For your information the scrollbar plugin which i use now is [nanoscroller.js](https://jamesflorentino.github.io/nanoScrollerJS/).
I hope this may help those had my same problem.

**Comment by fyrkant** [comment]
Awesome that you found out what the problem!

**Comment by sim1-81** [comment]
Unfortunately no,

like i've said few days ago, the browser console does not show anything, so I tried to exclude all the js scripts one by one until i've found the responsable.

the weird thing is that the inline tinymce editor instead works properly even if you using mCustomScrollbar plugin.
