### ISSUE TITLE
Input field widget or writable select field widget?

### ISSUE THREAD

**Issue by dingo-d** [tinymce/tinymce#3330]
I am wondering if it's possible, and if it exists, an input field widget, or writable select field.

The reason why I'm asking is that - say that you want to add more font sizes to your tinyMCE. Currently the `fontsizeselect` in the toolbar offers fixed select drop down, so you can only add more font sizes inside, and what you have is (a possibility, if you want to add many font sizes) a huge select. This is ugly.

Word, LibreOffice, WordPad, all have writable select - you can place any number you want inside, and select from predetermined values. 

Can this be added as a plugin maybe? I thought that it would be a good thing to have in the tinyMCE.

**Comment by fyrkant** [comment]
Hi! 

This is not possible to do right in TinyMCE at the moment, but it's an interesting feature request and something we will discuss.

**Comment by lostkeys** [comment]
Hey all! With TinyMCE 6.4, [we released a new font size input button](https://www.tiny.cloud/docs/tinymce/6/6.4.1-release-notes/#new-fontsizeinput-toolbar-item-which-allows-the-user-to-set-the-size-via-input-and-also-increase-and-decrease-it-with-and-buttons) which allows end-user to type any font-size.
