### ISSUE TITLE
Usage of tinymce in latest Angular2 (2.1.1) with webpack

### ISSUE THREAD

**Issue by Abhijith-Nagaraja** [tinymce/tinymce#3332]
I am trying install tinymce in an angular2 project. But till now I am unable to do so.

Here is what I have done till now.

package.json dependency
`"tinymce": "4.4.3",`

Webpack configuration

```
const webpack = require('webpack');
const TinyMcePlugin = require.resolve('tinymce/tinymce');
```

```
{ test: TinyMcePlugin, loaders: [ 'imports?this=>window', 'exports?window.tinymce' ] },
{ test: /tinymce[\\/](themes|plugins)[\\/]/, loader: 'imports?this=>window' }
```

`new webpack.ProvidePlugin({ tinymce: "tinymce"})`

**My directive class: wysiwyg.directive**
```
import {Directive} from '@angular/core';

declare var tinymce: any;

@Directive({
  inputs: ['wysiwygEditor'],
  selector: '[wysiwygEditor]'
})
export class WysiwygEditorDirective{
    constructor(){
        tinymce.init({
            selector: '.wysiwyg',
            schema: 'html5',
            skin: false,
            plugins: ['paste', 'link', 'autoresize']
        });
    }
}
```

I am getting the following error.

> ERROR in ......./directives/wysiwyg/wysiwyg.directive.ts
> Module not found: Error: Can't resolve 'tinymce' in '...../directives/wysiwyg'

**PS:** I have included my directive in app.module.ts

**Comment by fyrkant** [comment]
Hi!

I think your Angular 2 code is faulty, shouldn't tinymce be a component? 

If you can I recommend using the Angular CLI, we have some documentation on how to get started [here](https://www.tinymce.com/docs/integrations/angular2/).

**Comment by Abhijith-Nagaraja** [comment]
There is no seamless integration with angular2/webpack.
I couldn't load the JS file with the loaders. I included the reference in index.html and then it started working.

However,  the issue I have opened is a valid one.

Saying that,

No, tinymce need not be a component. It can be a directive. I made it work as a directive with ngModel two-way binding.
I will update that readme and create a pull request in [tinymce-docs](https://github.com/tinymce/tinymce-docs/blob/master/integrations/angular2.md) on how to use tinymce as a directive with ngModel binding.

**Comment by fyrkant** [comment]
Ok, I am sorry for that then, I am no Angular 2 expert.  🙇 I'll take a look at your PR. 

Regarding your issue I think it might be solved in an upcoming release of TinyMCE where we've made some changes that should make it easier to use TinyMCE with module loaders like webpack without using the imports- and exports loader. So I recommend either getting the nightly build [from here](https://www.tinymce.com/download/additional-downloads/) or waiting on the upcoming release.

**Comment by Afraithe** [comment]
There is an official Angular wrapper project now (tinymce-angular). Closing this ticket, any Angular related issues should be open in that project.
