### ISSUE TITLE
incorrect 'preview_styles' description in documentation

### ISSUE THREAD

**Issue by sludgedeath** [tinymce/tinymce#3333]
https://www.tinymce.com/docs/configure/editor-appearance/#preview_styles
possible values are not `true/false` , but `false/string`
string must contain list of style attributes to preview. 

so the default value is not `true` ,but:
`'font-family color font-size font-weight font-style text-decoration text-transform background-color border border-radius outline text-shadow',`

**Comment by fyrkant** [comment]
Thank you for the bug report!
