### ISSUE TITLE
button icons are not visible when open from google chrome second time 

### ISSUE THREAD

**Issue by nishantjadhavcg** [tinymce/tinymce#3338]
Implemented tinymce version 4.4.3.  Implemented in the bootstrap modal. first open working fine but for second open the button icons are not visible. works fine in internet explorer and Mozilla fire fox.
The tinymce is implemented in the asp.net mvc 5 application.
 
![tinymce chrome issue](https://cloud.githubusercontent.com/assets/23655275/20521487/78962aa2-b0d1-11e6-8134-9df536a185a4.PNG)

**Comment by fyrkant** [comment]
Hi!
Can you reproduce the error in a [fiddle](http://fiddle.tinymce.com/)?
