### ISSUE TITLE
Jquery docs example does not work

### ISSUE THREAD

**Issue by mscreenie** [tinymce/tinymce#3339]
The example fiddle in the docs under jquery integration does not work. I am also unable to get it to work with jquery in my dev install. Please advise on how to fix ? Thank you for tinymce.

**Comment by fyrkant** [comment]
Seems like the fiddle was set up incorrectly, just using the normal TinyMCE build and not the one with the added jQuery plugin! I think I corrected it and saved it now, so you can check the fiddle again.

**Comment by fyrkant** [comment]
Otherwise you can check out [this codepen](http://codepen.io/anon/pen/GNmXVO?editors=1010) that I spun up. Check the Javascript and CSS settings (by clicking the Settings button up to the right  and selecting JavaScript/CSS in the dialog) to see which external scripts that you have to add to get it to work.

**Comment by mscreenie** [comment]
I wasn't aware there was a separate build for jquery, any idea how I can use mce online bundler to output a jquery build instead of a native js one?

**Comment by fyrkant** [comment]
It's not a separate build of TinyMCE but a plugin for jQuery. So you need jQuery, TinyMCE and the jQuery plugin for it to work. 

The full example, which also contains jQuery-ui script and CSS, would look like this:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js"></script>
  <script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
  <script src="https://cdn.tinymce.com/4/jquery.tinymce.min.js"></script>
  <title>JS Bin</title>
</head>
<body>
  
  
  <div id="dialog" title="TinyMCE dialog" style="display: none">
      <textarea></textarea>
  </div>

  <button id="open" type="button">Open</button>

  
  <script>
  // Prevent jQuery UI dialog from blocking focusin
  $(document).on('focusin', function(e) {
      if ($(e.target).closest(".mce-window, .moxman-window").length) {
      e.stopImmediatePropagation();
    }
  });

  // Open dialog and add tinymce to it
  $('#open').click(function() {
    $("#dialog").dialog({
      width: 800,
      modal: true
    });

    $('textarea').tinymce({
      toolbar: 'link',
      plugins: 'link'
    });
  });
  </script>


</body>
</html>
```

**Comment by fyrkant** [comment]
As this does not seem to be an issue with TinyMCE I am closing this issue, but please comment if there is anything else you are wondering about and I can open it again.

**Comment by mscreenie** [comment]
Great, checked out the pen and works good except for inline.

http://codepen.io/anon/pen/oYWKNr?editors=1010
