### ISSUE TITLE
MS Word styling 'error message' about images

### ISSUE THREAD

**Issue by Servicedeskprocurios** [tinymce/tinymce#3340]
Good Afternoon, for a few months we have been using the TinyMCE 4.4.2 version editor.
One of our clients just noticed a bug.

This client uses MS Word (newest version). Writes and styles text, (making several words bold, one italic) and wishes to paste the text from Word into the editor. When he tries this, the following message pops up "pasting local images is deactivated. local images are removed from the pasted content" (roughly translated). I am able to reproduce this.

Strange thing is: the client nor me are not using or pasting images.
I presume the editor displays this message when any word-specific styles are being found in the content that is being copied.

Since no images are being copied, it's very frustrating for clients to have to:
- A: alter all their text since the bold/italic/underlined styles have to be set in every text.

- B: the error message is being displayed every time a sentence is being copied, while no image is being copied over. Realistically, many companies use Word to alter and edit text before using pasting it into the editor, i see this as a low priority bug.

Question-time:
- Can it be made possible for clients to be able to paste "styled" text from MS Word. (Bold, italic, underlined) ?
- Can it be made possible with settings to "Activate" pasting local images ?
- Can the error-message be changed to be only displayed when actual images are being pasted? (When no images are being pasted, the error isn't displayed).

Regards, the Procurios Servicedesk

**Comment by fyrkant** [comment]
Hi!

Is this an issue regarding the Powerpaste enterprise plugin? Then the quickest way to get help is by submitting a technical support request from [this page](https://support.ephox.com/hc/en-us).

**Comment by Servicedeskprocurios** [comment]
Thank you fyrkant for your hand and the provided information. I can work with that and will close this ticket.
