### ISSUE TITLE
Letter y not working with webkit

### ISSUE THREAD

**Issue by mhuntley** [tinymce/tinymce#3343]
I seem to be encountering an issue using the letter y. It works as a capital but not by itself.

installed using bower
using version 4.4.3 (2016-09-01)
and angular-ui-tinymce 0.0.17

If you need any further info let me know.

Thanks.

**Comment by fyrkant** [comment]
Hi! I am having trouble reproducing this, are you able to reproduce this on a fiddle? http://fiddle.tinymce.com/

**Comment by mhuntley** [comment]
It seems that when  using bower to intall angular-ui-tinymce it was installed an older version. i have now installed added  "tinymce": "^4.5.0", to the package.json and it now works.
