### ISSUE TITLE
Icon for "Table of Contents" plugin missing when using a custom style

### ISSUE THREAD

**Issue by sea75300** [tinymce/tinymce#3344]
Yesterday I updated TinyMCE to version 4.5. I went to http://skin.tinymce.com/ to update my custom style for the new version.

I enabled the new "Table of Contents" (toc) plugin and added a button to the editor toolbar. I noticed the icon of the new button is missing. If I replace my own style with lightgrey, the icon shows up.

![missing_icon](https://cloud.githubusercontent.com/assets/13407962/20618124/be7583c4-b2ed-11e6-9119-95ed69fd6586.png)

**Comment by spocke** [comment]
I've updated the skin.tinymce.com site now we forgot to update the less file there.

**Comment by sea75300** [comment]
The problem re-appeared when I updated to TinyMCE 4.6 today. No matter if i use my own style running through skin.tinymce.com or one of the other skins. In custom style the icon is still missing.
