### ISSUE TITLE
feature request: search font names using keyboard

### ISSUE THREAD

**Issue by mscreenie** [tinymce/tinymce#3347]
I've added 50 or so Google fonts to tinymce and in another case I've added about 20 or so non-google fonts.

 It would be a good user experience if the user could press a letter while in fontselect drop down and select the related font as per key press.

Thanks, let me know what you think.

**Comment by fyrkant** [comment]
Yeah that sounds like a pretty good feature, thank you for that request, we will discuss it internally and see if we can come up with something.

**Comment by mscreenie** [comment]
Great, thanks. I've had my app end users tested and have got back a few more suggestions. I didn't think of these myself as it had not occurred to me, which reminds me of the importance of another perspective.  I was hoping I would be able to implement myself by extending tinymce but don't think it would be possible. 

- Commonly used fonts list at top of fontselect.
- Hover preview of fonts, modify selected text on mousein of a font name and revert on mouseout. 

I'll try and create separate issues for each of these sometime. But they remind me of Word user experience.
