### ISSUE TITLE
adding class in custom style format does not work

### ISSUE THREAD

**Issue by maximilienborne** [tinymce/tinymce#3351]
Hi everyone,
I'm trying to add custom format in my tinymce WISIWIG, but i'm facing a problem.
Adding custom styles works, like this : 
`tinymce.init({
  selector: 'textarea',  // change this value according to your html
  style_formats: [
    {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}}
  ]
});`
but when i want to add to my content a class like this :
`tinymce.init({
  selector: 'textarea',  // change this value according to your html
  style_formats: [
    {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
  ]
});`

styles seems to work in WISIWIG area, but when i check the code source tab, my class is not added.
Any idea concerning this issue ?

**Comment by fyrkant** [comment]
Hi! Can you recreate the problem in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
