### ISSUE TITLE
Error when pressing bullist or numlist twice with empty list element 

### ISSUE THREAD

**Issue by mesche** [tinymce/tinymce#3354]
**Description of problem:**
Error when pressing the bullist or numlist icon twice with an empty list element 

Tested with: tinyMce 4.5.0 (2016-11-23)
Issue on: IE11, Firefox, Edge

**Steps to reproduce**
Fiddle: http://fiddle.tinymce.com/PCfaab

1. run fiddle code
2. place cursor into editor
3. enter "aaa"
4. press "return" key
5. mark all text (STRG+a)
6. press bullist or numlist icon
7. press icon again

**Expected result**
disable enumeration

**Actual result**
JS Error
TypeError: ul is null    plugin.js (Line 363, Column 28)
Unable to get property 'parentNode' of undefined or null reference

**Comment by fyrkant** [comment]
This has been fixed in the newly released version 4.5.1!
