### ISSUE TITLE
Cannot apply basic style to non editable elements

### ISSUE THREAD

**Issue by TimotheeJeannin** [tinymce/tinymce#3355]
I use TinyMce with the [noneditable plugin](https://www.tinymce.com/docs/plugins/noneditable/).

I want to be able to wrap non editable elements with basic styling tags.

For example if I have :

```html
Hello <span class="mceNonEditable">user_name</span> how are you today ?
```

If I click on `user_name` to select the non editable span and click on the **TinyMce Bold button**.

![Image](https://i.stack.imgur.com/L68ZB.png)

I would like the result to be :

```html
Hello <b> <span class="mceNonEditable">user_name</span> </b> how are you today ? 
```

But instead of this, nothing happens. When I click the TinyMce Blod button, the code doesn't change.

I created a small jsFiddle to demonstrate this : https://jsfiddle.net/timotheejeannin/2hhpenm5/

I tried to use the `data-mce-contenteditable` attribute to override the non editable behavior when a button is clicked. It looks like it's used in [DOMUtils.js line 1739](https://github.com/tinymce/tinymce/blob/4.5.0/js/tinymce/classes/dom/DOMUtils.js#L1744) to determine if the element is editable or not.

I think the issue comes from the fact that [Formatter.js line 715](https://github.com/tinymce/tinymce/blob/4.5.0/js/tinymce/classes/Formatter.js#L715) just returns instead of doing work if a non editable element is found.

I posted a StackOverflow question here : http://stackoverflow.com/questions/40885928/apply-basic-style-to-non-editable-elements-in-tinymce

How can I solve this ? Is this a bug ?

**Comment by spocke** [comment]
This isn't a bug but rather by design. However we have seen people wanting this behavior so maybe we should change the code to allow elements to be styled.

**Comment by TimotheeJeannin** [comment]
Yes, I think the *noneditable* plugin is usually used to make some kind of variable replacement and most of the time styling makes sense for those variables. 

Can you give me pointers on what to code to build this feature ? Maybe the *noneditable* plugin should have more options.

**Comment by qodo** [comment]
I too would like to see this added so that users can style these. I use this as placeholders for values that are replaced afterwards so would like them to be able to style. Could this be a config option perhaps?

**Comment by mauro13983** [comment]
Any news on that? I really need this behavior too!

**Comment by Roudoudou** [comment]
We really need this too, any update on the matter please?

**Comment by nicholas-ooi** [comment]
Any updates to this feature?

**Comment by bent0b0x** [comment]
We also would really like this :)

**Comment by catalinbuletin** [comment]
Any news on this? This you be awesome to have it available!

**Comment by dranik** [comment]
While there should definitely be an ability to whitelist some formatting for this plugin, that is my workaround for the problem:
````
tinyMCE.init({
  /*your initializer settings*/
  setup: function (ed) {
    ed.on('ExecCommand', function(e) {
      var selection = tinyMCE.activeEditor.selection.getContent();
      var el = document.createElement( 'html' );
      el.innerHTML = "<head></head><body>"+selection+"</body>";
      var datapoints =  Array.from(el.getElementsByClassName('mceNonEditable'));
      if (datapoints.length>0) {
        var styleToggle = function(key, value) {
          var criteria = (datapoints.map(function(datapoint){
            return (datapoint.style[key] == value);
          }).reduce(function(a,b) {
            return a&&b;
          }));
          if (criteria) {
            datapoints.forEach(function(datapoint){
              datapoint.style[key] = "";
              datapoint.contentEditable = false;
            });
          } else {
            datapoints.forEach(function(datapoint){
              datapoint.style[key] = value;
              datapoint.contentEditable = false;
            });
          };
        }
        switch (e.command) {
           case 'mceToggleFormat':
            switch (e.value) {
              case 'bold':
                styleToggle("font-weight", "bold");
                break;
              case 'italic':
                styleToggle ("font-style", "italic");
                break;
              case 'strikethrough':
                styleToggle ("text-decoration", "line-through");
                break;
              case 'underline':
                styleToggle ("text-decoration", "underline");
            };
            tinyMCE.activeEditor.selection.setContent(el.children[1].innerHTML);
            break;
           case ("mceApplyTextcolor"):
             styleToggle ("color", e.value);
             tinyMCE.activeEditor.selection.setContent(el.children[1].innerHTML);
             break;
           case ("FontName"):
             styleToggle ("font-family", e.value);
             tinyMCE.activeEditor.selection.setContent(el.children[1].innerHTML);
             break;
           case ("FontSize"):
             styleToggle ("font-size", e.value);
             tinyMCE.activeEditor.selection.setContent(el.children[1].innerHTML);
             break;
           case ("RemoveFormat"):
             datapoints.forEach(function(datapoint){
               ["font-weight", "font-style", "text-decoration",
               "text-decoration", "color", "font-family", "font-size"].forEach(function(key){
                 datapoint.style[key]="";
               })
               datapoint.contentEditable = false;
             });
             tinyMCE.activeEditor.selection.setContent(el.children[1].innerHTML);
             break;
         };
       }
    });
    /*more stuff*/
  }
});
```

**Comment by virtualestate** [comment]
+1 Using .mceNonEditable for placeholders also. I can understand preventing further styling _inside_ the  .mceNonEditable element, but our users are currently having to add a block of formatted dummy text prior to adding the placeholder, and then remove said dummy text. Thinking the interim solution might be to temporarily remove the noneditable class and add it back afterward, though its more tech debt we have to endure. A fix for this will be warmly welcomed. :)

**Comment by kakauandme** [comment]
+1 Sometimes it's required to keep content uneditable, but styles should match the rest of the content.

**Comment by ChrisDrozdowski** [comment]
+1 Please implement an editor setting to allow, among other basic formatting, alignment formatting for contenteditable="false" block-level elements. The setting to be independent of noneditable plugin

I have placeholder-like/template code as follows that I want to allow users to specify div alignment (e.g. margin:auto for centering).

`<div data-generated-table="true" style="display:table" contenteditable="false">{{GENERATED_TABLE}}</div>`

**Comment by tbracken** [comment]
+ 1 need this desperately!

**Comment by tmmarchese2** [comment]
+1 this is critical for our offering.  please make possible!!

**Comment by bpajk** [comment]
I also want to style the custom placeholders. This would be a great feature.

**Comment by HadrienRussier** [comment]
I need this feature too

**Comment by hunterae** [comment]
I figured out a "slightly" less hacky way to do this. Essentially, I register a "BeforeExecCommand" event that, for certain events, removes the contenteditable attribute, allows the command to run, and readds the contenteditable false attribute in the "ExecCommand" event. Doing so allowed me to avoid having to custom handle the various possible events that I have seen in other proposed solutions. I have forked your original example to demonstrate the solution (and added a couple of additional formatting options and a "Variables" feature) which can be found here: https://jsfiddle.net/hunterae/8fsnv3h6/40/

Here are the most relevant pieces of the solution:

    tinymce.init({
      // Additional options here
      setup: function (editor) {
      	var $ = tinymce.dom.DomQuery;
      	var nonEditableClass = editor.getParam('noneditable_noneditable_class', 'mceNonEditable');
        // Register a event before certain commands run that will turn contenteditable off temporarilly on noneditable fields
        editor.on('BeforeExecCommand', function (e) {
          // The commands we want to permit formatting noneditable items for
          var textFormatCommands = [
            'mceToggleFormat',
            'mceApplyTextcolor',
            'mceRemoveTextcolor'
          ];
          if (textFormatCommands.indexOf(e.command) !== -1) {
          	// Find all elements in the editor body that have the noneditable class on them
          	//  and turn contenteditable off  
            $(editor.getBody()).find('.' + nonEditableClass).attr('contenteditable', null);
          }
        });
        // Turn the contenteditable attribute back to false after the command has executed
        editor.on('ExecCommand', function (e) {
        	// Find all elements in the editor body that have the noneditable class on them
          //  and turn contenteditable back to false
          $(editor.getBody()).find('.' + nonEditableClass).attr('contenteditable', false);
        });
      },
      init_instance_callback: function (editor) {
    	  
      	/* 
        	The following two hacks fix some weirdness with the way the textcolor
          plugin works - namely, it was attemping to apply color and background-color
          directly on the element that had the noneditable css class on it instead of putting
          a span around it as underline does.
      	*/
      	editor.formatter.get('forecolor')[0].exact = true;
        editor.formatter.get('hilitecolor')[0].exact = true;
        
        
      }
    });

**Comment by blasterpistol** [comment]
A simpler version that works well in my case
```js
{
  setup: editor => {
    let nodes = []
    editor.on('BeforeExecCommand', () => {
      const b = editor.getBody()
      nodes = Array.from(b.querySelectorAll('[contenteditable=false]'))
      nodes.forEach(n => n.removeAttribute('contenteditable'))
    })
    editor.on('ExecCommand', () => {
      nodes.forEach(n => n.setAttribute('contenteditable', 'false'))
    })
  },
}
```

**Comment by ianterrell** [comment]
Here is an updated fiddle based on the above solution that works with TinyMCE 5: https://jsfiddle.net/uv9bre5h/2/

It only changes the usage of `listbox` in the `variables` example code.

**Comment by atul-jalan** [comment]
+1 on getting this fixed. Would be a huge win for our users! I see the various hacky solutions listed here, though a first-party fix would be best.

**Comment by ianterrell** [comment]
TinyMCE 6 removed the DomQuery API, so the fiddles need adjusted to use vanilla JS queries instead: https://jsfiddle.net/37fo4n21/

**Comment by TheSpyder** [comment]
Just wanted to note that while we have been silent we haven't forgotten about this. It's currently under consideration for a release later this year - this doesn't guarantee we're going to do it this year, but it is on the radar.

**Comment by rprussinSV** [comment]
My team is very much looking forward to the day this gets an official fix -- the non-editable functionality is amazing from a UX standpoint and is a feature we would love to use, it's really just the inability to apply styles to non-editable fields that makes it a dealbreaker for us right now (short of making a hacky solution that we then have to maintain, which we also would like to avoid).

**Comment by sakumashirayuki** [comment]
tinymce now supports this feature!!
Thank you for the brilliant work! This is a very useful feature.
see the docs：https://www.tiny.cloud/docs/tinymce/6/content-formatting/#format_noneditable_selector
```
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  format_noneditable_selector: 'span,p.special'
});
```
noneditable elements that matching the `format_noneditable_selector` can be formatted by the toolbar buttons!

**Comment by TheSpyder** [comment]
correct, my apologies for not closing this ticket when it was released 3 or 4 months after my last message 🤭
