### ISSUE TITLE
Images supplied with Object URL won't upload

### ISSUE THREAD

**Issue by moraleja39** [tinymce/tinymce#3357]
When inserting an image given a source Object URL, the image never goes throught the upload process, neither automatically or when calling tinymce.Editor.uploadImages().
If a custom image upload handler is provided, it will never be called for such images. Also, the uploadImages() callback param never executes.

TinyMCE version: 4.5.0
Browser: Chrome 54

**Sample**
http://fiddle.tinymce.com/qDfaab/1

**Steps to reproduce**
1. Click on insert image
2. Click on the browse button
3. Click the "Ok" button. The image works fine in the editor.
4. Click on the submit button to submit the form.

**Expected result**
imgUpload() and uploadImages() callback get called, producing console output.

**Actual result**
Nothing

Using data URLs works fine, but not for heavy images, so I don't see it as a solution.

**Comment by spocke** [comment]
I think we should just ignore blobs that isn't created by tinymce since the it's up to the implementor to do all the heavy lifting of uploading and updating urls. We need it to be in blob cache to be able to produce base64 of them as a sync call to getContent in case they weren't uploaded.

**Comment by moraleja39** [comment]
Didn't notice that caveat as I'm explicitly uploading the images before calling getContent. However you could load the image with a sync XHR call when added to the editor and add it to the cache.

The problem is that, at this point, adding an image via blob will break several tinymce functionalities. There is no mention anywhere on the docs if blob images are supported or not, and is rather caused by the implementation. As blob urls work after all like any other url on the document scope, I would consider this a bug, unless clearly stated on the image plugin docs to not use blob urls.
