### ISSUE TITLE
Margin between whitespaces after second activation of invisible characters

### ISSUE THREAD

**Issue by mesche** [tinymce/tinymce#3359]
**Description of problem:**
Margin between whitespaces after second activation of invisible characters 

Tested with: tinyMce 4.5.0 (2016-11-23)
Issue on: IE11, Firefox, Edge

**Steps to reproduce**
Fiddle: http://fiddle.tinymce.com/xDfaab

1. run fiddle code
2. place cursor into editor
3. enter "     " (five whitespaces)
4. click "show invisible characters" icon
5. click icon to hide invisible characters
6. click icon to show  invisible characters again 

**Expected result**
how invisible characters without margin

**Actual result**
margin between whitespaces

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
