### ISSUE TITLE
Visual glitch in UI for file_picker_callback

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#3361]
In TinyMCE version 4.4 and earlier this works fine.
In version 4.5 it shows a visual glitch, a `<top>` and `<bottom>` floating over the UI for the `file_picker_callback`.

# Reproduce
Reproduced in this test case:
http://fiddle.tinymce.com/yDfaab

# Screenshot
![image](https://cloud.githubusercontent.com/assets/10222521/20799634/0a5d39c2-b7e3-11e6-90aa-fd4cdf7e0d75.png)

**Comment by spocke** [comment]
What browser is this happening on? Can't seem to reproduce it.

**Comment by vanillajonathan** [comment]
Firefox 50, Chrome 54 & 55, and Edge 14.

The popup with `<top>` and `<bottom>` belongs to the Url input field in the "Insert Link" dialog. It seems to be some autocomplete feature.

![image](https://cloud.githubusercontent.com/assets/10222521/20828635/c4badcda-b878-11e6-9169-b76174080efa.png)

**Comment by vanillajonathan** [comment]
I can reproduce this in 4.5.0 but not in 4.5.1. This bug seems to have been fixed.

**Comment by fyrkant** [comment]
Yes, this has been fixed in 4.5.1!
