### ISSUE TITLE
Regression in 4.5.0 with not being able to type the letter "y"

### ISSUE THREAD

**Issue by cmeredith** [tinymce/tinymce#3363]
There seems to be a regression in version 4.5.0 that recreates this bug: https://github.com/tinymce/tinymce/issues/2844

You can no longer type lowercase "y" in the rich text editor. Rolling back to 4.4.3 resolves the issue.

**Comment by fyrkant** [comment]
Are you able to reproduce this in a [fiddle](http://fiddle.tinymce.com/)? How are you installing TinyMCE? We had some problem with another user where some caching issue caused this (I think that user installed Tiny with Bower).

**Comment by spocke** [comment]
I think this is a cache issue or not all files being updated. The theme and the core tinymce.min.js needs to be updated and in sync. If this doesn't solve the problem it's could be something else but we have tested this on IE 8-11, Edge, Safari, Firefox and Chrome so then it might be something user environment specific.

**Comment by cmeredith** [comment]
@spocke @fyrkant Thanks guys for your quick replies. Yes, I had installed TinyMCE through node which was installed at 4.4.3, but was pointing at the 4.5.0 script. Updating all of the node package to 4.5.0 (or reverting the script to 4.4.3) fixes the issue. Thanks!

**Comment by fyrkant** [comment]
Great to hear!
