### ISSUE TITLE
Regression in 4.5.0: style_formats with float break GUI/no functionality

### ISSUE THREAD

**Issue by Fiona-TU** [tinymce/tinymce#3364]
When using a custom style format with float property, it breaks the Formats drop-down menu in tinymce 4.5.0. and the style format doesn't get applied to the selected element.

Didn't happen in 4.4.3

Fiddle:
http://fiddle.tinymce.com/UCfaab

Header-formats are working as expected, custom float format not

**Comment by fyrkant** [comment]
Hi! Thanks for the bug report, the issue seems not to be the float styles, but the `selector: '*'` part! This will be fixed in an upcoming patch release, but if you want to get it working right now, try defining some selectors, like `selector: 'span, p, h1, h2'`, instead of using the star.

**Comment by fyrkant** [comment]
This has now been fixed in the newly released version 4.5.1!
