### ISSUE TITLE
Transifex (translations) are not in sync with TinyMCE 4.5

### ISSUE THREAD

**Issue by drumsibumsi** [tinymce/tinymce#3367]
Just upgraded my TinyMCE from 4.4.3 to 4.5 and noticed that several strings are missing their translations. Went to Transifex to check which strings were added and - nothing new there.

For example, media plugin has term "Media" which was previously "Insert/edit video". The transifex allows to translate the old term and not the new one.

**Comment by spocke** [comment]
The language packs has now been updated. Thanks for reporting this.
