### ISSUE TITLE
Drop support for IE7 and IE8

### ISSUE THREAD

**Issue by redaxmedia** [tinymce/tinymce#3368]
Hello,

I really like your project, but I wonder why you still support these old browsers instead of focusing on future technologies? Isn't this a wasting of time and human resources!? People who need to support old browsers can still use an outdated version of TinyMCE.

Best regards

**Comment by jayarjo** [comment]
I guess for now we'll keep an eye on how much votes and attention this thread will get.

**Comment by TheSpyder** [comment]
I don't recall when exactly this changed but for the current release of 4.x, and the upcoming 5.x, IE11 is the minimum.
