### ISSUE TITLE
emty clipboard after shift+delete

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#3369]
steps:
1) type text in editor
2) ctrl+a
3)shift+delete

expect: all text in clipboard
really: empty clipboard

**Comment by fyrkant** [comment]
Hmm, I have never heard about shift+delete putting anything in the clipboard, is that a Windows thing? You should be able to get the same functionality with the cut shortcut, ctrl+C

**Comment by PetrBorisov** [comment]
@fyrkant shift+delete  it`s like ctrl+x  (windows)

**Comment by fyrkant** [comment]
What is the use case for this that the cut shortcut (Ctrl + C) doesn't fulfill?

**Comment by PetrBorisov** [comment]
@fyrkant  
It`s same like base keyboards number and numpad
someone as comfortable

**Comment by fyrkant** [comment]
But is it working in other editors? Or in just a normal textarea (like the one here on github)? I can't reproduce that shift + delete cuts the text anywhere.

**Comment by PetrBorisov** [comment]
@fyrkant 
in github editor all work normal

in tinyMCE editor after ctrl+a not work shiift+delete  (delete text, but clipboard is empty and after ctrl+v i see empty editor)

**Comment by Rycochet** [comment]
It's a non-standard Windows thing, however it should also fire off the event.key "Cut" (the same as a dedicated Cut key on the keyboard itself) - might be worth adding support for those specific keys as well as the standard keyboard combinations - https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#Editing_keys

**Comment by iJungleboy** [comment]
What confuses me is this: I have different tiny-mce implementation, and on some it works, on others it doesn't. Same PC, same browser (chrome) just different tiny-mces. Any idea why?

**Comment by donShakespeare** [comment]
So Windows is at it again ... I thought shift+delete was to delete something past therecycle bin ... interesting!
