### ISSUE TITLE
inlite theme with forced_root_block: false on element containing only a newline, will bug caret position in firefox

### ISSUE THREAD

**Issue by Cordemans** [tinymce/tinymce#3370]
Using the `inlite` theme with `forced_root_block: false` on a div containing only a newline, will put the caret above the `<div>` in Firefox (50.0.2)

When you start typing, the caret will return back to the normal position.
After pressing return, the caret bugs again until you resume typing.

[http://fiddle.tinymce.com/CDfaab](http://fiddle.tinymce.com/CDfaab)

Removing the newline inside the `<div>` will fix the issue.

```
from:
<div class='tinymce'>
</div>

to:
<div class='tinymce'></div>
```

tried with:
Firefox 50.0.2
macOS 10.12.1

**Comment by SimonFc** [comment]
Closing this issue since it's limited to Tiny 4 and it's not critical.
