### ISSUE TITLE
Custom Style format

### ISSUE THREAD

**Issue by venkatbaggu** [tinymce/tinymce#3375]
We are creating the custom style formats using the below example [http://codepen.io/tinymce/pen/QjzgRW](url)

It was working fine for single elements.

Now we want to create the nested elements like 

> < section class="page-title" style="margin:0 !important;" >
>      < h1 class="rg-title" >
>          < span>Test</span> solutions 
>      < /h1>
> </ section>

How we are going to add this type of custom formats. Is it possible?

**Comment by fyrkant** [comment]
I think the [template plugin](https://www.tinymce.com/docs/plugins/template/) should provide the functionality you are after.
