### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by BogdanAdrian** [tinymce/tinymce#3376]
Steps to reproduce:
Right after uploading an image, close the window.

Result: It will throw the following error "Uncaught TypeError: Cannot read property 'value' of undefined" (See screenShot below)

![screen shot 2016-12-06 at 2 59 34 pm](https://cloud.githubusercontent.com/assets/9161718/20926393/beb4a06a-bbc4-11e6-9e89-53afc13c8837.png)

I think the error is inside rebuildImageList()

**Comment by fyrkant** [comment]
Hi! Could you provide some more information about what version of TinyMCE you are using and which plugins you are using?

**Comment by BogdanAdrian** [comment]
Hi Mattias,

Sure, I'm using image plugin, V4.x. Not sure what value "x" has.
The project I'm using it lacks documentation, and I'm relatively new on it,
but I added the minified version of the plugin, maybe it helps.

Cheers,
Adrian

2016-12-07 12:41 GMT+02:00 Mattias <notifications@github.com>:

**Comment by BogdanAdrian** [comment]
I'm using an outdated version. I see it's fixed in this version.

I was talking about the check from line 95 from here
https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/image/plugin.js

Thanks anyway,
Adrian

2016-12-07 14:06 GMT+02:00 Bogdan Adrian <bogdanbadrian@gmail.com>:

**Comment by fyrkant** [comment]
Ok! Then I am closing this issue, but if there is anything else you are wondering about just write a comment and I can open it up again!

**Comment by BogdanAdrian** [comment]
Sure thing! Thanks!

2016-12-07 16:26 GMT+02:00 Mattias <notifications@github.com>:
