### ISSUE TITLE
Visual Chars Plugin does not work.

### ISSUE THREAD

**Issue by hartmann93** [tinymce/tinymce#3379]
Hi, I have tried using the Visual Chars Plugin on your [full-featured demo version](https://www.tinymce.com/docs/demo/full-featured/) and I have noticed that it does not work.

I tried it with other demos and it didn't worked either

I'm using Firefox 50, Chrome 55, Edge, IE 11 on Windows 10.

Cheers

**Comment by jayarjo** [comment]
Visual Chars plugin works only on `&nbsp;` and `&shy;` characters.

**Comment by jayarjo** [comment]
We will post updates in this thread: https://github.com/tinymce/tinymce/issues/3359.

**Comment by hartmann93** [comment]
Indeed @mesche !
Moreover I expected that **line breaks** are shown as invisble characters too.
Could you please reopen the issue?

**Comment by ppant** [comment]
It seems that  "show invisible characters" plug-in only supports two chars  `&nbsp;` and` &shy; `I want to add few more chars like soft enter (`<br/>`) and enter (`\u000D`). Is there a way to expand char list to incorporate more chars? I have tried adding in charmap[] in plugin.js 

```
charMap = {

'\u00a0': 'nbsp',

'\u00ad': 'shy',

'\u00b6': 'para',

'\u000D': 'cr',

', '\u2009': 'thinsp', };
```
but this is only giving results for `&nbsp;` and` &shy;`

Any help is much appreciated.

**Comment by fyrkant** [comment]
@ppant Yes the invisible characters plugin only shows `&shy;` and `&nbsp;` right now and there is no way to add more because that would have to include how to visually represent the characters too and I am not sure how that would work.

**Comment by ppant** [comment]
@fyrkant Thanks for your response. I can understand but you know users try to see the MS Word kind of effect and don't understand that this is an HTML editor but users least bothered about that they need the similar look.  I am also trying figure out a strategy for writing new plug-ins but as you mentioned visualization needs to be handled. Hope TinyMCE will provide a way to add more chars with different visualization for each.
Thanks,

**Comment by mesche** [comment]
I hope the function can be more like _MS Word_ soon, because this is the effect what a "normal" user expected....
