### ISSUE TITLE
Nested <div> tags with attributes removed

### ISSUE THREAD

**Issue by ShivaliTayal** [tinymce/tinymce#3380]
I am adding this source code to my editor version-4.1.4:

```html
<div id="example" class="k-content">
<div id="gauge-container">
<div id="gaugePercentPointsCompleted"></div>
<div id="valPercentPointsCompleted" class="gaugeVal"></div>
<div id="statementPercentPointsCompleted" class="gaugeStatement"></div>
</div>
</div>
```

but after saving it if I go back to the editor I get this 
 
```html
<div id="example" class="k-content">&nbsp;</div>
````

With what I have inferred by reading other posts related to this is ,the inside divs are empty because of which the editor considers them to be useless and adds &nbsp. But I have two points here:

1.My inside divs are empty but have class or Id attr because of which this shouldn't be considered to be useless.
2.I tried overriding the existing rules by using extended_valid_elements : '#div[*]' which will again add space to my div
3.I also changed default option to verify_html: false , but this is seemingly a dangerous thing to do.

Can you please suggest something to rectify this or tell if this is by design & cann't be fixed

Thanks,
Shivali

**Comment by fyrkant** [comment]
Can you provide a [fiddle](http://fiddle.tinymce.com/) showing this problem? Or add backticks (by pressing the `<>` button in above the input) to your source code samples, I can't see anything but whitespace right now.

**Comment by ShivaliTayal** [comment]
I am adding this source code to my editor version-4.1.4:
`<div id="example" class="k-content">
<div id="gauge-container">
<div id="gaugePercentPointsCompleted"></div>
<div id="valPercentPointsCompleted" class="gaugeVal"></div>
<div id="statementPercentPointsCompleted" class="gaugeStatement"></div>
</div>
</div>`

but after saving it if I go back to the editor I get this
`<div id="example" class="k-content">&nbsp;</div>`

With what I have inferred by reading other posts related to this is ,the inside divs are empty because of which the editor considers them to be useless and adds &nbsp. But I have two points here:

1.My inside divs are empty but have class or Id attr because of which this shouldn't be considered to be useless.
2.I tried overriding the existing rules by using extended_valid_elements : '#div[*]' which will again add space to my div
3.I also changed default option to verify_html: false , but this is seemingly a dangerous thing to do.

Can you please suggest something to rectify this or tell if this is by design & cann't be fixed

Thanks,
Shivali

**Comment by ShivaliTayal** [comment]
I am adding this source code to my editor version-4.1.4:
`<div id="example" class="k-content">
<div id="gauge-container">
<div id="gaugePercentPointsCompleted"></div>
<div id="valPercentPointsCompleted" class="gaugeVal"></div>
<div id="statementPercentPointsCompleted" class="gaugeStatement"></div>
</div>
</div>`
but after saving it if I go back to the editor I get this
<div id="example" class="k-content">&nbsp;</div>

With what I have inferred by reading other posts related to this is ,the inside divs are empty because of which the editor considers them to be useless and adds &nbsp. But I have two points here:

1.My inside divs are empty but have class or Id attr because of which this shouldn't be considered to be useless.
2.I tried overriding the existing rules by using extended_valid_elements : '#div[*]' which will again add space to my div
3.I also changed default option to verify_html: false , but this is seemingly a dangerous thing to do.

Can you please suggest something to rectify this or tell if this is by design & cann't be fixed

Thanks,
Shivali

**Comment by ShivaliTayal** [comment]
I am adding this source code to my editor version-4.1.4:
![whatwassaved](https://cloud.githubusercontent.com/assets/24453586/21018752/0e2ec848-bd94-11e6-842a-49f63855e157.png)

but after saving it if I go back to the editor I get this
![what_you_got_after_going_back](https://cloud.githubusercontent.com/assets/24453586/21018756/190c5532-bd94-11e6-8a16-4a1e90c93f2b.png)

With what I have inferred by reading other posts related to this is ,the inside divs are empty because of which the editor considers them to be useless and adds &nbsp. But I have two points here:

1.My inside divs are empty but have class or Id attr because of which this shouldn't be considered to be useless.
2.I tried overriding the existing rules by using extended_valid_elements : '#div[*]' which will again add space to my div
3.I also changed default option to verify_html: false , but this is seemingly a dangerous thing to do.

Can you please suggest something to rectify this or tell if this is by design & cann't be fixed

Thanks,
Shivali

**Comment by ShivaliTayal** [comment]
Can I please get a quick reply on this.?

Thanks,
Shivali

**Comment by jayarjo** [comment]
@ShivaliTayal empty tags are stripped. This is expected behavior. You can either turn off validation (not recommended). Or add something like `&nbsp;` in your empty divs. That should help.

**Comment by ShivaliTayal** [comment]
Can I override the configuration option `extended_valid_elements: 'div[*]'`  so that &nbsp; is not added to the empty divs, and they remain as it is ?

**Comment by ShivaliTayal** [comment]
Can someone please reply to my query.It would be really helpful. I know empty divs are stripped off. In my case empty divs are being added with `&nbsp;` . But what if I don't want that , I just want the code to be as it was entered without any space added to empty divs . So trying to achieve that I overrided the rule 
`extended_valid_elements:'div[*]'` . So is this the right way to achieve it. Can I override the configuration option so that `&nbsp;` is not added to my empty divs

**Comment by jayarjo** [comment]
`&nbsp;` are required by tinymce, otherwise you won't be able to place a cursor into an empty container.

**Comment by ShivaliTayal** [comment]
Thanks jayarjo for your reply. But divs with id & class attributes should not be stripped off as they are not meaningless , right ?
Also if we want to add font awesome icons <i></i> , they are also stripped off. Adding `&nbsp;` is a workaround to this , but isn't it a bug that empty tags are stripped off even the ones with id & attribute ?

**Comment by ShivaliTayal** [comment]
Can anyone please reply to the above comment ? It would be really helpful.

**Comment by fyrkant** [comment]
Like @jayarjo said the `&nbsp;` are required by the editor to be able to place a cursor into an empty container right now.

**Comment by ShivaliTayal** [comment]
And what about the font awesome icons `<i></i>`  those are stripped off. We can't use them.

**Comment by ShivaliTayal** [comment]
Can anyone please reply to what about the font awesome icons? Using `<i class='fa fa-check-circle '></i>` is completely removed from the source code which unables me to use the icons.
What about this ?

**Comment by ekarda-hub** [comment]
<i class='fa fa-check-circle '>&nbsp;</i> is what you must use.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
