### ISSUE TITLE
After adding code sample with codesample plugin, edit again not working

### ISSUE THREAD

**Issue by thomich** [tinymce/tinymce#3383]
If you add any code sample with codesample plugin you are not able to edit it again.

1. add any text/code with codesample editor

2. click to code sample area in editor and click codesample icon again

3. nothing happens...

You can reproduce this on http://fiddle.tinymce.com/CCfaab/5.

**Comment by Cordemans** [comment]
This seems to work again in 4.5.2

**Comment by fyrkant** [comment]
Yes it should be working now with 4.5.2, so closing this!

**Comment by thomich** [comment]
upgraded to 4.5.5 and confirming that this issue is solved also ;)...

thanks..

**Comment by HFTSxRiDeR** [comment]
tinymce#4.7.1
I have same problem...

**Comment by iqbalfn** [comment]
@HFTSxRiDeR I just try use the `master` branch, and it's already fixed.
