### ISSUE TITLE
Layer plugin import

### ISSUE THREAD

**Issue by urre** [tinymce/tinymce#3388]
Hey,

The unminified version (layer/plugin.js) of the layer plugins seems to be missing when i browse node_modules. 

![](https://res.cloudinary.com/urre/image/upload/v1481534381/bpjp8fzjuejdqtbk3kfo.png
)

**Comment by spocke** [comment]
Yes, we removed that plugin since it was never ported over properly from 3.x to 4.x.

**Comment by fyrkant** [comment]
Closing this issue, but if you have anything else you want to ask just leave a comment and I can open it again.
