### ISSUE TITLE
Media plugin failure in IE8

### ISSUE THREAD

**Issue by robtree** [tinymce/tinymce#3390]
Between 4.3.12 and 4.5.1, the media plugin no longer works in IE8.

![jsfiddle-tinymce](https://cloud.githubusercontent.com/assets/3150192/21099169/8c61256c-c064-11e6-84f3-68b30fa9410d.png)

Steps to reproduce:

1. Open http://fiddle.tinymce.com in IE8 (Win XP)

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; .NET4.0E; .NET CLR 1.1.4322)
Timestamp: Mon, 12 Dec 2016 12:14:07 UTC

Message: Expected identifier
Line: 696
Char: 6
Code: 0
URI: http://fiddle.tinymce.com/tinymce/4.5.1/plugins/media/plugin.js

**Comment by fyrkant** [comment]
Sorry about this, it's a problem with `catch` being reserved only to try-catch in IE8, but being used in a promise chain in the updated media plugin. We will fix this for an upcoming version.

**Comment by robtree** [comment]
Thanks! Looks like https://github.com/tinymce/tinymce/commit/c2406d032c085382e093c35f28506b7d8afca155 has it covered.

**Comment by fyrkant** [comment]
This should be working now (works for me in IE8 on Win7 at least)! You can try it out and close it if it works, thank you for the issue report!

**Comment by robtree** [comment]
No problem. Checked IE8 and looks good in 4.5.2. Thanks for the quick fix!
