### ISSUE TITLE
Display uploading fails

### ISSUE THREAD

**Issue by dunets** [tinymce/tinymce#3391]
How to display that image wasn't successfully uploaded?

There are nothing about that on Documentation... 

![sem titulo](https://cloud.githubusercontent.com/assets/6217617/21101535/962593aa-c071-11e6-8cd4-4dd51c6a0480.png)

**Comment by jayarjo** [comment]
We will be addressing this problem in a coming release. Meanwhile you could simply override uploader using [images_upload_handler](https://www.tinymce.com/docs/configure/file-image-upload/#images_upload_handler) option and throw some feedback in the case of failure yourself.

**Comment by fyrkant** [comment]
I believe this should be fixed now in version 4.5.2, can you test it out again @dunets and close this issue if you are satisfied?
