### ISSUE TITLE
plugins/paste breaks in ES6 import

### ISSUE THREAD

**Issue by gera2ld** [tinymce/tinymce#3392]
The following code breaks due to incorrect `this`:
``` js
import 'tinymce/plugins/paste';
```

The problem is that `exports` is defined as `this` and is not `window` when packing with webpack.

This will work:
``` js
import 'imports?this=>window!tinymce/plugins/paste/plugin';
```

Anyway, it does not make sense to provide a special loader for each plugin. Could you fix this? Thanks.

---

Updated typo:
~~`import 'imports?this=>window!tinymce/plugins/paste';`~~
`import 'imports?this=>window!tinymce/plugins/paste/plugin';`

**Comment by fyrkant** [comment]
What version of Tiny are you using? This should be fixed in the latest release 4.5.1.

**Comment by gera2ld** [comment]
I am using the latest release v4.5.1.

**Comment by fyrkant** [comment]
We updated to 4.5.2 earlier this week and this should now be fixed! Please try it out and close this issue if it is working for you.

**Comment by gera2ld** [comment]
Fixed, thanks a lot.
