### ISSUE TITLE
Getting an error when trying to minify and bundle tinymce.min.js with other files

### ISSUE THREAD

**Issue by abelski21** [tinymce/tinymce#3400]
Hi, I'm getting this error when we use the minified version of all our js files together with tinymce plugins.

`Potentially unhandled rejection [3] Error loading "only screen and (max-device-width: 480px)" at only screen and (max-device-width: 480px).js
Error loading "only screen and (max-device-width: 480px)"`

It tried to call `http://localhost:3000/only%20screen%20and%20(max-device-width:%20480px).js` for some reason. I'm blocked now and don't know what to do. It runs fine when we use the dev environment and calls tinymce plugins in a usual way. We're using steal to bundle our js files and plugins. I'm just having trouble when trying to build our project as production file. We minify this into one js file and the error I'm getting above points to the tinymce.js line #761 and #762 under the method definition of "tinymce/Env". Can someone help me on this?

**Comment by abelski21** [comment]
Just an update, I've tried using the unminified version of tinymce and its plugins...and now I'm seeing a different error:

`Uncaught module definition dependecy not found: tinymce/util/Promise`

I've tried some ways to fix this, I've added skin:false, remove paste plugin..but I'm still getting the same error.

**Comment by jayarjo** [comment]
Are you trying to reminify already minified tinymce?
