### ISSUE TITLE
Webkit + plugin table: error when recreating tinymce

### ISSUE THREAD

**Issue by Jatixo** [tinymce/tinymce#3401]
Webkit (example Opera 12) and enable plugin table.
JS:
```
tinymce.init();
tinymce.remove();
tinymce.init();
```
Error line table plugin.js:
```
function clear(force) {
	// Restore selection possibilities
	editor.getBody().style.webkitUserSelect = '';
```
Quick fix:
```
	if (editor.getBody()) {
		editor.getBody().style.webkitUserSelect = '';
	}
```

**Comment by jayarjo** [comment]
Initialization is not synchronous operation. You should wait until editor initializes and only then try to remove it with `tinymce.remove` (check [init_instance_callback](https://www.tinymce.com/docs/configure/integration-and-setup/#init_instance_callback))

**Comment by spocke** [comment]
Closing this issue since it can be resolved by using the recommended option.
