### ISSUE TITLE
Menu appearance and Firefox 50.1.0

### ISSUE THREAD

**Issue by madflow** [tinymce/tinymce#3406]
+ Ubuntu 16.04.1 LTS
+ Firefox 50.1.0
+ http://plnkr.co/edit/3DLcTXLxYjs4Ksseyanl?p=preview

When clicking on a menu item that opens a submenu, that submenu is "nailed" to the top - left of the screen.

![tiny](https://cloud.githubusercontent.com/assets/183248/21305457/25d6c118-c5cc-11e6-9079-9dd9c63f8595.png)

**Comment by alecpl** [comment]
Works for me with the same browser version and system.

**Comment by madflow** [comment]
@alecpl Thanks for checking! I just deleted the FF cache and deleted all "offline" data - now it works again.  Hard to say what caused this now. I am closing this - since I assume an unforced Browser error on my part.
