### ISSUE TITLE
Unable to use webpack to import tinymce

### ISSUE THREAD

**Issue by doberkofler** [tinymce/tinymce#3411]
I have been following the [Usage with module loaders](https://www.tinymce.com/docs/advanced/usage-with-module-loaders/) instruction but when running the example application a `TypeError: target is undefined` in shown in the console and the editor is not displayed.

```
/*global require: false*/

// Import TinyMCE
import tinymce from 'tinymce/tinymce';

// A theme is also required
import 'tinymce/themes/modern/theme';

// Any plugins you want to use has to be imported
import 'tinymce/plugins/paste';
import 'tinymce/plugins/link';
import 'tinymce/plugins/autoresize';

require.context('file-loader?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/skins', true, /.*/);

// Other
import $ from 'jquery';

// constants
const EDITOR_ID = 'editor';

$(document).ready(function () {
	// Initialize TinyMCE
	tinymce.init({
		selector: '#' + EDITOR_ID,
		height: 300,
		plugins: ['paste', 'link', 'autoresize']
	});

	$('#get').on('click', function (event) {
		event.preventDefault();

		const CONTENT = tinymce.get(EDITOR_ID).getContent();

		alert(CONTENT);
	});

	$('#set').on('click', function (event) {
		event.preventDefault();

		const CONTENT = prompt('html', '<ul><li>one</li><li>two</li></ul>');
		if (CONTENT) {
			tinymce.get(EDITOR_ID).setContent(CONTENT);
		}
	});
});
```

I have uploaded my example code and would really appreciate some help on what I'm doing wrong?

[tinyMCE2.zip](https://github.com/tinymce/tinymce/files/665840/tinyMCE2.zip)

**Comment by fyrkant** [comment]
Hi!
Unfortunately there seems to be a problem with the version of tinymce published on NPM so that page in the documentation doesn't work as it should right now. We will try and fix the npm version as soon as possible. Sorry! 🙇

**Comment by doberkofler** [comment]
Thank you for your quick feedback. I'm looking forward to the fix.

**Comment by fyrkant** [comment]
Should be working (I've got it working with [this example](https://github.com/fyrkant/simple-tinymce-webpack)) with the smoking-hot, off the presses new 4.5.2 release! Please try it out and close this issue if it works! 🌸

**Comment by doberkofler** [comment]
@fyrkant Yes, 4.5.2 solves this issue. I just noted that the changelog does not mention this fix. Thank you!

**Comment by yakobe** [comment]
@fyrkantI am trying to get tinymce to work with webpack. I see https://github.com/fyrkant/simple-tinymce-webpack/commit/d23e81d58b318b5f274a9c7f8caea5b58ca8652b in your repo where you say to "copy the files yourself". Could you explain how and where you copy them? It would be a great help to me. I am using the file-loader which semi-works but I cannot get asset versioning etc.
