### ISSUE TITLE
"Uncaught SyntaxError: Invalid regular expression" with "webpack -p" / ufligy-js

### ISSUE THREAD

**Issue by uncleyo** [tinymce/tinymce#3412]
When Webpack runs UglifyJS with tinyMCE imported, the output is broken and throws this in the console:
```
Uncaught SyntaxError: Invalid regular expression /...some very long garbage symbols here.../
```
(npm tinymce@4.5.1)

**Comment by fyrkant** [comment]
I'm having problems reproducing this, could you share some more info on your project, maybe direct me to a Github repo that I can check out?

**Comment by uncleyo** [comment]
@fyrkant, sure!
Here you go: https://github.com/uncleyo/tiny-uglify.
Reproduced with only `uglify-js`

**Comment by fyrkant** [comment]
Seems to be connected to this: https://github.com/mishoo/UglifyJS2/issues/54

So if you change the uglify call to this it should work:
```bash
uglifyjs node_modules/tinymce/tinymce.js -b ascii_only=true,beautify=false -o out.js
```

**Comment by uncleyo** [comment]
Thanks, that does the trick! I've made a PR for docs to cover this topic

**Comment by AlastairTaft** [comment]
Getting the same issue as this

**Comment by fozersahin** [comment]
When I served my app in S3 bucket, I got similar issue. But in firefox everything is working fine. Problem is in Chrome UTF-8 settings probably.

**Comment by crustamet** [comment]
im having the same problem, i just copied tinymce and try to make it work.
maybe the config must be different ?
