### ISSUE TITLE
Parse error in setContent

### ISSUE THREAD

**Issue by OscarDeDios** [tinymce/tinymce#3413]
Hi.

When I do a tinyMce.setContent(someHtmlCode);

I have the error:

tinymce.min.js:12 Uncaught TypeError: Cannot read property 'parse' of undefined
    at D.setContent (tinymce.min.js:12)

It works well in my previous version 4.3.3

Thanks.

**Comment by fyrkant** [comment]
Hi!
Can you reproduce the problem in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by OscarDeDios** [comment]
Hi, thanks for answer.

Here is the fiddle with similar parameters that I use in my program:

http://fiddle.tinymce.com/8Ffaab/1

tinymce.js:39717 Uncaught TypeError: Cannot read property 'parse' of undefined
setContent @ tinymce.js:39717
(anonymous) @ preview.php?key=9Ffaab:38
tinymce.js:39717 Uncaught TypeError: Cannot read property 'parse' of undefined
    at Editor.setContent (tinymce.js:39717)
    at preview.php:38


I do a setContent after a little timeout, the error doesn't appear if the timeout is longer.

In my program I didn't have any timeout beetween initialization and setContent and it worked until now. But in my program I have the error even with a timeout.

Regards.
Oscar.

**Comment by OscarDeDios** [comment]
I answer to myself:

init_instance_callback ;)

Then do I close the issue?

**Comment by fyrkant** [comment]
I was just about to link you to the init_instance_callback! 👍 

I can close it for you! :)

**Comment by OscarDeDios** [comment]
Thanks @fyrkant I'm sorry for make you loose time, I should had studied better the docs before open a issue.

Regards.

**Comment by justin-romano** [comment]
This seems to only work on the first editor in the editors container. If you use createEditor to add further instances you get this error. Not sure this callback function solved this.

**Comment by MukeshSherawat61** [comment]
tinymce.remove();
                                 tinymce.init({
                                     selector: '#tt_task_details_box',
                                     setup: function (editor) {
                                       editor.on('init', function (e) {
                                         editor.setContent(data.task_data.description);
                                       });
                                     }
                                   });
