### ISSUE TITLE
nested Divs with id & class attributes are stripped off

### ISSUE THREAD

**Issue by ShivaliTayal** [tinymce/tinymce#3418]
If I add a single div with id & class attribute to it , `&nbsp` is added to the div. i.e. `<div id='123'></div>` becomes `<div id='123'>&nbsp;</div>` . We want to avoid this space in case if id or class attribute is added to the div making it a meaningful tag. For this overriding the extended_valid_elements rule.
Also in case of nested div `<div><div id="123"></div></div>` even if inner div has id but the outer div is without any attribute the inner div is stripped off like this `<div>&nbsp;</div>`. 

Please can anyone verify if it's a bug & is this way to do this is correct `extended_valid_elements = div[*]` ?

**Comment by fyrkant** [comment]
Duplicate of #3380 so I am closing this.
