### ISSUE TITLE
Code with external js files

### ISSUE THREAD

**Issue by Lachiave** [tinymce/tinymce#3420]
Hello. I put tinymce editor in the desktop folder that contains the files of my website. When I copy and paste the code of a page in the editor, the preview works, but external js files are not read. Why? Other editors (like Cazary for example) read the js files and the preview is perfect. Thank you

**Comment by Lachiave** [comment]
This is complicated, I'll see what I can do. Thank you

**Comment by spocke** [comment]
We don't allow scripts in the editor for xss security reasons you can opt in to load scripts but they don't always execute. I recommend not including scripts like this in the content. You can use extended_valid_elements: 'script[type|src]' to opt into scripts in the editor.
