### ISSUE TITLE
Tinymce 4.3.10 in bootstrap modal not showing menu drop down

### ISSUE THREAD

**Issue by malik-umair** [tinymce/tinymce#3421]
I'm using Tinymce 4.3.10 inside bootstrap modal but it's not displaying any menu drop down or insert link or image popup, everything is hiding behind the modal. I found that it's because bootstrap blocks all focus events on contents within the dialog and tried following code as given [here ](https://www.tinymce.com/docs/integrations/bootstrap/)but it didn't worked for me.

My code is a below:

    <script type="text/javascript">
    tinymce.init({
    selector: "textarea:not(.mceNoEditor)",
    browser_spellcheck: true,
    force_br_newlines: true,
    force_p_newlines: false,
    forced_root_block: '',
    font_formats: 'Arial=arial,helvetica,sans-serif;Courier New=courier new,courier,monospace;AkrutiKndPadmini=Akpdmi-n;Comic Sans MS=comic sans ms,sans-serif;Times New Roman=times new roman,times;',
    fontsize_formats: '8pt 10pt 12pt 14pt 18pt 24pt 36pt',
    plugins: ["textcolor", "advlist autolink lists link image charmap print preview anchor", "searchreplace visualblocks code fullscreen", "insertdatetime media table paste"],
    toolbar: "fontselect | fontsizeselect | forecolor backcolor | insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    height: "200",
    content_css: [
        '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
        '//cdnjs.cloudflare.com/ajax/libs/prism/0.0.1/prism.css',
        '//www.tinymce.com/css/codepen.min.css'
    ],
    image_title: true,
    // enable automatic uploads of images represented by blob or data URIs
    automatic_uploads: true,
    images_upload_url: '../postAcceptor',
    // here we add custom filepicker only to Image dialog
    file_picker_types: 'image',
    // and here's our custom image picker
    file_picker_callback: function (cb, value, meta) {
        var input = document.createElement('input');
        input.setAttribute('type', 'file');
        input.setAttribute('accept', 'image/*');
        input.onchange = function () {
            var file = this.files[0];

            // Note: Now we need to register the blob in TinyMCEs image blob
            // registry. In the next release this part hopefully won't be
            // necessary, as we are looking to handle it internally.
            var id = (new Date()).getTime();
            var blobCache = tinymce.activeEditor.editorUpload.blobCache;
            var blobInfo = blobCache.create(id, file);
            blobCache.add(blobInfo);

            // call the callback and populate the Title field with the file name
            cb(blobInfo.blobUri(), {title: file.name});
        };

        input.click();
    }
    });

    // Prevent bootstrap dialog from blocking focusin
    $(document).on('focusin', function(e) {
    if ($(e.target).closest(".mce-window").length || $(e.target).closest(".moxman-window").length) {
        e.stopImmediatePropagation();
    }
    });  
    </script>

**Comment by spocke** [comment]
Seems to work fine here: http://fiddle.tinymce.com/qGfaab
I'm closing this one since this is more of a support request/integration issue rather than a bug. If you still think it's a bug we can re-open it.
