### ISSUE TITLE
Redundant files in tinymce non-development package

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#3428]
The community package (4.5.1) contains redundant files.
1. License.txt file is in tinymce/ and tinymce/js/tinymce/
2. I don't think anyone needs tinymce/js/tinymce/skins/lightgrey/*.less files in non-development package.

**Comment by fyrkant** [comment]
Thank you for the issue report, this has been fixed in the next release of TinyMCE!

**Comment by fyrkant** [comment]
This has now been fixed with the 4.5.2 release, closing this issue!
