### ISSUE TITLE
Find/replace whole word in Greek not working

### ISSUE THREAD

**Issue by demosphereeu** [tinymce/tinymce#3430]
Hi,

Thanks for Tinymce, we use it a lot and appreciate it.

A small bug report:

Search and/or replace using "whole word" does not work in Greek:
For example, if you search for the whole word "το" in this text "το πρωί του Σαββάτου", nothing is found.

Cheers,

Demosphere.

**Comment by demosphereeu** [comment]
bump

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.2.1 which was released to the community late last month. Please let us know if you experience any further issues. Thanks!
