### ISSUE TITLE
Second pop-up layer no effect

### ISSUE THREAD

**Issue by JayenLee** [tinymce/tinymce#3437]
With the bootstrap modal bomb box using TinyMCE to refresh the page will display the open window, close the editor, and then opening, not the effect of the editor. Do you need to reload JS every time you initialize the editor?

**Comment by fyrkant** [comment]
I'm not that informed with bootstrap, so can you reproduce this in a [fiddle](http://fiddle.tinymce.com) or somewhere else so it will be easier for me to see what's happening?

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.

**Comment by kkYFL** [comment]
> No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.

https://github.com/tinymce/tinymce/issues/4411
