### ISSUE TITLE
fontselect breaks editor on firefox with hidden instances

### ISSUE THREAD

**Issue by richinnz** [tinymce/tinymce#3442]
See fiddle - http://fiddle.tinymce.com/OGfaab
If you have multiple instances on a page and there is a hidden one (usually first one that will get shown when the user is ready for it) then the editors are not shown because fontselect breaks .  Error is possibly that the fontFamily variable is 'not defined' and therefore dies in this function: Adding the check appears to solve it - maybe?

var normalizeFontFamily = function (fontFamily) {
        // 'Font name', Font -> Font name,Font
        return (fontFamily) ? fontFamily.replace(/[\'\"]/g, '').replace(/,\s+/g, ',') : ''; 
    };

**Comment by fyrkant** [comment]
Fixed in yesterdays 4.5.3 release.

**Comment by t0v1n** [comment]
Confirmed that this issue was fixed in 4.5.3, but it seems to be present again in 4.6.3

**Comment by fyrkant** [comment]
@t0v1n You are able to reproduce it with the same fiddle linked above using 4.6.3 in Firefox?
