### ISSUE TITLE
eternal_plugins issue 

### ISSUE THREAD

**Issue by artemijan** [tinymce/tinymce#3443]
Hello. Is there a way to order custom plugins loading?
because eternal_plugins is an object (It is an unordered collection of properties ) and some of plugins requires loading before others.
Maybe make sense make this option member of Array?
Thanks

**Comment by fyrkant** [comment]
You could load the plugins with separate script tags and in that way decide what order it is loaded. 

So instead of: 
```js
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  external_plugins: {
    'testing': 'http://www.testing.com/plugin.min.js',
    'maths': 'http://www.maths.com/plugin.min.js'
  }
});
```

You would write do the imports in separate script tags: 
```html
<script src="http://www.testing.com/plugin.min.js"></script>
<script src="http://www.maths.com/plugin.min.js"></script>
```
And just add the plugins to the "normal" plugins setting:

```js
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'testing maths'
});
```

I think that should work!

**Comment by fyrkant** [comment]
If that works for you please close this issue.

**Comment by k644606347** [comment]
be from：js/tinymce/classes/Editor.js

each(settings.external_plugins, function(url, name) {
					PluginManager.load(name, url);
					settings.plugins += ' ' + name;
				});


You can refer to this code, and do a module loader based on array

**Comment by artemijan** [comment]
thanks, it's very helpful.
