### ISSUE TITLE
selectAll with a codesample as first element fails in chrome

### ISSUE THREAD

**Issue by 0xor1** [tinymce/tinymce#3444]
in chrome, with a new blank editor, inject a codesample then enter some regular text beneath it, then do a ctrl+a to select all, it doesnt highlight any text in the editor. If you try this again with some text above the codesample entered first, ctrl+a will highlight everything. seems to be a chrome bug, it works in FF

**Comment by fyrkant** [comment]
Verified and reproduced in this fiddle:
http://fiddle.tinymce.com/FHfaab

**Comment by fyrkant** [comment]
Same problem in Safari. Works in Edge and IE.

**Comment by androb** [comment]
Cannot replicate in Chrome in TinyMCE edge

**Comment by TheSpyder** [comment]
Still replicable in Safari 😞
