### ISSUE TITLE
disabled editor does not look disabled

### ISSUE THREAD

**Issue by mykbaker** [tinymce/tinymce#3445]
When I mark the editor as disabled it doesn't allow entry but it doesn't appear to be disabled. Is there a way to change the textarea background to gray to show it is disabled? Should this be the default functionality?

**Comment by fyrkant** [comment]
How are you disabling the editor, just putting disable on the textarea? You can initialize tinymce with the `readonly: true` option to set it in the readonly mode, and then change back to the normal "design" mode with the setMode method. Sett [this example](http://fiddle.tinymce.com/EHfaab) for clarification.

**Comment by mykbaker** [comment]
Thanks @fyrkant, this will work great. Might consider making this the default functionality for marking the control disabled using standard disabled tag on the textarea to make it more intuitive.

**Comment by fyrkant** [comment]
Yes that is something we really should consider, just putting the editor into readonly mode if the textarea is disabled.

Closing this issue as the issue seems to have been solved!
