### ISSUE TITLE
[Question - Paste]: retain text colors but not font-family

### ISSUE THREAD

**Issue by SebSob** [tinymce/tinymce#3447]
When i paste text from word into the editor, how can i keep everything but the font-family?

My current settings are:
```
paste_word_valid_elements: "p,b,strong,i,em,h1,h2,h3,color",
paste_retain_style_properties: "font-color color background-color",
```

[See image](https://i.gyazo.com/af17457596eee04fded97bbf681b5f7f.png)

But when i paste my text, the font-family is removed, great, but the text-colors fill-colors are also removed.. any idea how i can keep the color ?

**Comment by SebSob** [comment]
Fixed by removing the paste_word_valid_elements , and use this 

`paste_retain_style_properties: "color, background"`

**Comment by fyrkant** [comment]
Great that you found a solution to the problem 👍 

Closing this issue, but if you have any more questions just write a comment and we can open it again.
