### ISSUE TITLE
Space between links and bold text disappear after add image

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3448]
Since few versions I see this very annoying bug. This new bug comes with plugin paste?

Testcase: http://fiddle.tinymce.com/DHfaab

Now add somewhere a image url like https://www.google.de/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

Result: all spaces between text and link or text and bold text are disappeared.

Tested in Chrome and Firefox

**Comment by fyrkant** [comment]
Fixed in yesterdays 4.5.3 release.
