### ISSUE TITLE
Space between links and bold text disappear after undo

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3449]
Maybe thats related to https://github.com/tinymce/tinymce/issues/3448 

Use the same testcase: http://fiddle.tinymce.com/DHfaab

Now add a character or word... anything and go to menubar "edit" and click "undo".

Result: all spaces between text and link or text and bold text are disappeared.

Tested in Chrome and Firefox

**Comment by fyrkant** [comment]
Yes I believe this is the same problem as #3448. We have found the bug in the UndoManager and it will be a part of an upcoming patch release. Closing this issue.
