### ISSUE TITLE
list-buttons (bulllist, numlist) don't work without lists-plugin since 4.5.0

### ISSUE THREAD

**Issue by Fiona-TU** [tinymce/tinymce#3450]
Fiddle:
http://fiddle.tinymce.com/HHfaab

(Working in 4.4.3)

**Comment by fyrkant** [comment]
This is not a bug but an intended change, like spocke said in #3342, 

> We removed the list buttons from core since it was using the browsers built in broken behavior and we have a lot of bug reports that would be resolved by using our custom lists implementation. 

So please enable the lists plugin to use lists.

**Comment by Fiona-TU** [comment]
Thank you for that information.
Would be nice if it was added to the official changelog (https://www.tinymce.com/docs/changelog/) because it's a major change.

**Comment by LeonardChallis** [comment]
And maybe also in teh documentation: https://www.tinymce.com/docs/advanced/editor-control-identifiers/#toolbarcontrols

thanks :)
