### ISSUE TITLE
what are these anchor menu items for?

### ISSUE THREAD

**Issue by 0xor1** [tinymce/tinymce#3453]
when we use the insert link modal we get a drop down with:
```
<top>
<bottom>
```
in it, which seem to come from here:
```
              var anchorMenuItems = function () {
			var anchorMenuItems = fromMenuItems('anchor');
			var topAnchor = getSetting(editorSettings, 'anchor_top', '#top');
			var bottomAchor = getSetting(editorSettings, 'anchor_bottom', '#bottom');

			if (topAnchor !== null) {
				anchorMenuItems.unshift(staticMenuItem('<top>', topAnchor));
			}

			if (bottomAchor !== null) {
				anchorMenuItems.push(staticMenuItem('<bottom>', bottomAchor));
			}

			return anchorMenuItems;
		};
```
what's the purpose of these entries? Im not even sure why the url text box is a drop down, isnt it just for users to paste in a link

**Comment by spocke** [comment]
Just set anchor_top and anchor_bottom to false and they should not be rendered. Will add docs for this.

**Comment by lnewson** [comment]
These settings are documented now: https://www.tiny.cloud/docs/configure/url-handling/#anchor_bottom
