### ISSUE TITLE
Bug when not adding a 'space' after the less-than sign '&lt;'

### ISSUE THREAD

**Issue by Kleppo** [tinymce/tinymce#3454]
See fiddle for example: http://fiddle.tinymce.com/OHfaab

**Comment by jeroencornelissen** [comment]
+1

**Comment by M4R7iNP** [comment]
I believe this is the intended behaviour. You are actually supposed to escape _all_ the html inside `<textarea>`-tags, so in your case the browser decodes `&lt;3` into `<3` which is discarded an invalid html tag before TinyMCE runs.

See this: http://fiddle.tinymce.com/zKfaab

**Comment by dylmye** [comment]
Related: #1818

Anyone got a fix for this? Passing `&lt;` just truncates the entire line: http://fiddle.tinymce.com/A6gaab

**Comment by TheSpyder** [comment]
This is not a TinyMCE issue specifically. While browsers may appear to support raw HTML tags in a textarea, that's actually invalid, content is supposed to be encoded. When you put an encoded half-tag in the content the browser tries to parse it.

Here is an example without using TinyMCE at all, including a properly encoded example that works:
http://fiddle.tinymce.com/S6gaab
