### ISSUE TITLE
editor.insertContent crash

### ISSUE THREAD

**Issue by akshaykumar12527** [tinymce/tinymce#3456]
Cannot read property 'getRng' of undefined

code is crashing when  i am trying to insertContent into editor

**Comment by fyrkant** [comment]
Hi! 
Are you able to reproduce this issue in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
