### ISSUE TITLE
Paste as text option for toolbar not showing up

### ISSUE THREAD

**Issue by tonynd** [tinymce/tinymce#3464]
I am using tinyMCE 4.5.2 and for some reason, the paste as text button does not show up on the toolbar even with the paste plugin.

I also tried making the paste plugin and external plugin, but for some odd reason, the external plugin does not function the same way I prefer when adding paste in the plugin of the init file (when paste is added via plugins, num lists/list keeps the format so when I copy back to (let say Google Docs), it keeps the numbering. When added externally, the paste as text button shows up, but the formatting of the list gets lost).

Any idea why is does not show up?

Here is my init file (where the paste as text option DOES NOT show up.)

```
tinymce.init({
      cleanup_on_startup: true,
      convert_url: false,
      external_plugins: {
        "advlist": "/assets/plugins/advlist/plugin.min",
        "lists": "/assets/plugins/lists/plugin",
      },
      invalid_elements: "form, script",
      paste_preprocess: function(plugin, args) {
        args.content = args.content.replace(/<pre>/gi, "<p>");
        args.content = args.content.replace(/<\/pre>/gi, "</p>");
      },
      paste_remove_styles_if_webkit: true,
      paste_retain_style_properties: "all",
      plugins: [
        'autolink link image charmap anchor',
        'visualblocks code fullscreen',
        'insertdatetime media table paste'
      ],
      selector: selector,
      statusbar: false,
      toolbar: "bullist numlist outdent indent cut paste pastetext",
    });
```

**Comment by jayarjo** [comment]
Here's the fiddle with your config: http://fiddle.tinymce.com/FUfaab. Seems to work as expected (external plugins obviously not found).
