### ISSUE TITLE
Plugins Not Loading - Incorrect Paths

### ISSUE THREAD

**Issue by shefik** [tinymce/tinymce#3472]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Version 4.5.3 is loading plugins at `tinymce-4.5.3/js/tinymce/plugins/imagetools/plugin.js`, but only the minified files exist `tinymce-4.5.3/js/tinymce/plugins/imagetools/plugin.min.js`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Version 4.5.3

**Comment by shefik** [comment]
The same bug is also indicated here:

http://archive.tinymce.com/forum/viewtopic.php?id=31520

**Comment by shefik** [comment]
Looks like the problem is with the download itself. The TinyMCE Community package at http://download.ephox.com/tinymce/community/tinymce_4.5.3.zip?_ga=1.14143159.1084774938.1481781524 contains incorrect code, whereas the TinyMCE Dev Package package has correct code at http://download.ephox.com/tinymce/community/tinymce_4.5.3_dev.zip?_ga=1.14143159.1084774938.1481781524.

**Comment by fyrkant** [comment]
Are you getting an error that the plugin cannot be loaded? Can you reproduce it in a fiddle? The plugin seems to work for me.

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
