### ISSUE TITLE
Problem with autolink and new line

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3473]
This bug is now more than 4 years old and very really very annoying. Is here a chance to fix this? 

Go to fiddle and set cursor after URL and press enter-key
http://fiddle.tinymce.com/OCdaab

Result:
- Firefox and Edge; After line break the new line is still a link and not normal text
- Chrome; After line break only the first char is a link. After first char its normal text.

The enter-key should stop the autolink plugin, actual its add a &lt;br&gt; before &lt;/a&gt;. Its must be "&lt;/a&gt;&lt;br&gt;"

**Comment by alecpl** [comment]
I agree. I guess this has something to do with cursor position handling. Right-arrow key press allows continuation out of the link.

**Comment by Daijobou** [comment]
Right-arrow is a solution, but not for most users, that not known this hidden function. Here should maybe be a tinymce setting that always end links with space or/and newline.

**Comment by thedrjim** [comment]
Marking as verified as we can replicate this in 5.5

**Comment by levanduc94** [comment]
Hi, it's now more than 7 years. Is there any chance that this bug gets fixed?

**Comment by TheSpyder** [comment]
Looks like it was fixed nearly 2 years ago and nobody followed up. Apologies.https://fiddle.tiny.cloud/OCdaab/5
