### ISSUE TITLE
Update documentation type_ahead_urls

### ISSUE THREAD

**Issue by lebbers** [tinymce/tinymce#3474]
The documentation about [type_ahead_urls](https://www.tinymce.com/docs/configure/advanced-editing-behavior/#type_ahead_urls) is incorrect. 

The name of the [setting in code](https://github.com/tinymce/tinymce/blob/2d978de22643e8d6f7612a1a5ffa5ea342ef57a6/js/tinymce/classes/ui/FilePicker.js#L122) is `typeahead_urls` but the documentation is refering to `type_ahead_urls`.

**Comment by fyrkant** [comment]
Thank you!

Fixed by tinymce/tinymce-docs#484
