### ISSUE TITLE
Suggestions about the image plugin

### ISSUE THREAD

**Issue by k644606347** [tinymce/tinymce#3477]
**I hope the image plugin can integrate the "local upload button" feature and upload URL configuration.**

Many editors now have "local upload button", such as **CKEditor / UEditor**, but Tinymce has no such common features, this is a very regrettable thing;

Although the "paste_data_images" feature, but only when the paste and drag and drop trigger;
Although there are "MoxieManager" and "Image-Tools" and other functions, but they are not free;

**Comment by donShakespeare** [comment]
Very simple
http://justboil.me/

**Comment by k644606347** [comment]
Very grateful, although I have written an upload plugin, but you provide the plugin I am very interested.
"tinymceBubbleBar" is what I want. :)
I can not wait for Tinymce to provide me with these features!

**Comment by donShakespeare** [comment]
Glad you like it.
tinymceBubbleBar was my herald of sweetness, then TinyMCE came out with their own nice inline theme which has a floating selection toolbar.
I don't use the inline theme because it forces too much on me, so I am still using tinymceBubbleBar, especially version 2.

**Comment by jayarjo** [comment]
This has been implemented now in 4.6.5. Check: https://github.com/tinymce/tinymce/issues/3876 for details.
