### ISSUE TITLE
image_caption unable to link image

### ISSUE THREAD

**Issue by gwhitcher** [tinymce/tinymce#3478]
Hello TinyMCE,
I am using the latest version of TinyMCE and am using the image_caption option.  I am trying to apply a link to the image but am unable to do so.  I am able to apply a link to an image without the caption just fine, however when the caption is checked I am only able to edit the caption text to add a link and not the image itself.  I would like to apply a link to the image itself so I can add a rel for a lightbox.  Thanks!

**Comment by spocke** [comment]
Related https://github.com/tinymce/tinymce/issues/3596

**Comment by brianlenz** [comment]
FWIW, we're having the same issue, which is still present in 4.5.7.

**Comment by jayarjo** [comment]
There is a fix for this in the works.

**Comment by jayarjo** [comment]
Related: https://github.com/tinymce/tinymce/issues/2680

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
