### ISSUE TITLE
Tooltips in floating toolbar in tables in TinyMCE 4.5.3

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#3485]
If the TinyMCE textbox it's located at the bottom of the page, and you are editing a table, the tooltip of the buttons in the floating toolbar will appear below the toolbar and will increase the height of the page for a few moments. I'm guessing that the tooltips should appear over the toolbar instead of below in order to prevent that.

**Comment by SimonFc** [comment]
I'm closing this since it's limited to Tiny 4 which only will receive fixes for critical issues. In Tiny 5 everything works as it should.
