### ISSUE TITLE
Performance issue when typing text in IE11 (inline:true)

### ISSUE THREAD

**Issue by zhijunzhou** [tinymce/tinymce#3492]
**version**: _4.5.2 (2017-01-04)_
**browser** : _IE11_
**os**: _win7_
**javascript setting**: 
```
self.config = {
  selector: areaSelector,
  menubar: false,
  statusbar: false,
  toolbar: false,
  inline: true,
  browser_spellcheck : true,
  object_resizing: "table",
  fix_list_elements : true,
  convert_urls:false,
  end_container_on_empty_block:true,
  fixed_toolbar_container: toolBarSelector,
  toolbar1: barconf,
  image_advtab: true
}
```

**description:**  In my html page, there are more than 1 tinymce components. And I'm use the IE developer tools 'UI Responsiveness ' to record the timelines when i type something. you can check it with the following gif.
![test](https://cloud.githubusercontent.com/assets/15681407/23060992/fc30c37e-f53a-11e6-97bd-e1c30fffafe3.gif)

And it seems that the 'inline:true' mode will lead to much more browser reflow than "inline:false". That settings will cause about more than 1sec delay when i typing something. But when i remove 'inline: true', the performance is great. However, I need this configuration to have a preview of our attachment uploaded.

So, could you have any ideas?

**Comment by fyrkant** [comment]
Hi! Could you create a [fiddle](http://fiddle.tinymce.com/) showing the issue? That would make it a lot easier for us to understand the problem.

Just looking at your GIF it seems like it's the CSS recalculations that are slow, so we might have to look into the CSS for the inline theme. But as I said, it would help a lot if you could create a fiddle!

Thanks!

**Comment by zhijunzhou** [comment]
@fyrkant 
Thank you for your reply! And I have created a [fiddle](http://fiddle.tinymce.com/nKfaab/12). But i cannot reproduce the issues i have mentioned.

So, I guess the crux of low performance in my site maybe caused by the large number of CSS recalculations. But as we know, the inline theme will cause a lot of CSS recalculations every time when you  input or delete some words. Do you have any good ideas to reduce these recalculations?

**Comment by skintagain** [comment]
We were having the same issue using inline: false. After a lot of testing we found that Microsoft KB3205401 (December 2016 Security Monthly Rollup for Windows 8.1) resolves the issue on Windows 8 (Windows 7 equivalent  KB3207752). After installing this issue went away.

**Comment by zhijunzhou** [comment]
@skintagain 
I am try to install this fix([KB3207752](http://www.catalog.update.microsoft.com/search.aspx?q=3207752)), and my os is windows 7(x64). But I got an error message 'The update is not applicable to your computer'. 

Could you give me your download url? 
Thanks!

**Comment by skintagain** [comment]
@zhijunzhou It may already be installed (check control panel to see if it is).

Alternatively you can download the x64 version from here: https://www.catalog.update.microsoft.com/Search.aspx?q=KB3207752

**Comment by zhijunzhou** [comment]
Thanks a lot!

I have resolved this issues by uncompressed my css files. It works great!
