### ISSUE TITLE
Unable to scroll if add youtube video

### ISSUE THREAD

**Issue by jatwasandeep** [tinymce/tinymce#3494]
It seems a bug.

Step to reproduce 
- Add youtube video in editor
- drag and drop scroll bar to top

Current behavior 
- unable to scroll to top
- auto jumps to cursor location

expected behavior
- should be able to scroll

**Comment by fyrkant** [comment]
How are you adding the youtube video? With the media plugin? Could you reproduce the issue in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by jatwasandeep** [comment]
Have save fiddle here : http://fiddle.tinymce.com/WJfaab
To reproduce : add any youtube video and try scrolling in editor using up/down button. It doesn't allow to go on top.

**Comment by fyrkant** [comment]
Thank you!

**Comment by fyrkant** [comment]
I think this was fixed a while back.
