### ISSUE TITLE
The editor is loosing the scrollbar in some cases

### ISSUE THREAD

**Issue by YovavGad** [tinymce/tinymce#3495]
For example when the editor is used inside of tabs, when moving to another tab and then back to the tab with the editor - the IFrame scrollbar is missing (not re-painted), it does appear again if the window is resized or if the editor height is resized manually, but I was not able to do that through code, also tried to update the IFrame styles but that was not working,

In the meantime, I use this as a hack to fix this issue (but it triggers the node change event):
tinyMCE.get(formPostContentBody.prop("id")).setContent(tinyMCE.get(formPostContentBody.prop("id")).getContent());

tinymce version 4.5.2

**Comment by fyrkant** [comment]
Hi! Could you reproduce this issue in a [fiddle](http://fiddle.tinymce.com/)? That would make it a lot easier for us to understand and possible fix the problem.

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
