### ISSUE TITLE
Prohibit list nesting

### ISSUE THREAD

**Issue by hjagodzinski** [tinymce/tinymce#3501]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

I want to limit HTML to given subset defining `valid_children: '-h1[b],-h2[b],-li[h1|h2|ul|ol],-ul[ul|ol],-ol[ul|ol]'`.

Provided this configuration it's possible to create nested list with TAB key and by pasting it from already existing HTML. Here is an example of a nested list:

- Coffee
- Tea
  - Black tea
  - Green tea
  - Green tea
- Milk

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

[demo](http://fiddle.tinymce.com/gKfaab)

**What is the expected behavior?**

It's not possible to create a nested list by a TAB key or by pasting it from already existing HTML. The pasting should strip nested list tags (ol, ul, li).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I was able to reproduce it with various 4.* versions.

**Comment by tinesoft** [comment]
Hi,

Any update on this? Have you found a fix/workaround @hjagodzinski ?

I have the exact same problem, restrictions  expressed by `valid_children` are not taken into account...
Tested on v5.10 and v6 of TinyMCE, no success...

**Comment by tinesoft** [comment]
Update : 

> Provided this configuration it's possible to create nested list with TAB key 

For that part, you can set the option [lists_indent_on_tab](https://www.tiny.cloud/docs/tinymce/6/lists/#lists_indent_on_tab) (from lists plugin) to `false` to prevent creating nested lists by pressing TAB on an existing list item

But still,  the current config `valid_children: '-li[h1|h2|ul|ol],-ul[ul|ol],-ol[ul|ol]'`. still does NOT prevent nesting lists through Copy-Paste into the editor....
