### ISSUE TITLE
Copy/Paste break lines in Edge

### ISSUE THREAD

**Issue by megabast23** [tinymce/tinymce#3505]
Hello guys,

I detected a bug with Tinymce 4.3 in Edge browser.

If you copy some text with break lines from a text editor (notepad ++, sublime-text, etc..)

For example:

"John

   

Doe"

The result in Tinymce is:

"John

Doe"

Best regards,

Bastien

**Comment by fyrkant** [comment]
I can't see what is wrong with the result, it looks the same to me? 

Maybe the GH markdown removed your line breaks? Try surrounding the text in three backticks, like these ```,  to create a code block that shows all line breaks like this: 

```
Some code




with all line breaks left
```

But more importantly, is this still a problem with the latest version of TinyMCE (4.5.4)?

**Comment by megabast23** [comment]
Hello,
I can still reproduce the bug with tinyMCE 4.5.4

I do a copy with notepad
![capture1](https://cloud.githubusercontent.com/assets/26004820/23355160/d3ac5728-fcd4-11e6-9c6c-110853719fbf.PNG)
:

And I paste in tinyMCE:

![image](https://cloud.githubusercontent.com/assets/26004820/23355197/fa45c360-fcd4-11e6-8448-75d5b1c7ffa2.png)

**Comment by megabast23** [comment]
This bug only appears with edge :)

**Comment by megabast23** [comment]
up !

**Comment by fyrkant** [comment]
Hmm, seems like edge turns the input into divs instead of p tags. That's interesting! 😅

**Comment by jayarjo** [comment]
Related: https://github.com/tinymce/tinymce/issues/3541

**Comment by jayarjo** [comment]
This also seems to be somewhat related: https://github.com/tinymce/tinymce/issues/1952.

**Comment by trevorjay** [comment]
Doing some testing it looks like this is fixed in the latest version of 4 and 5. Looking back at the changelog, it looks like this particular issue was fixed in 4.6.0. I'm closing this issue and we'll handle the related issues separately. Of course, if anyone is still experiencing problems, please let us know.
