### ISSUE TITLE
The Escape key is eaten in the editor

### ISSUE THREAD

**Issue by cskwg** [tinymce/tinymce#3514]
*BUG*

Symptom: The Escape key  is not passed to surrounding code.
In my case, the editor is embedded into a "dialog" (a DIV).
The dialog should react on the Escape key by vanishing.
But the keydown event does not reach the relevant handler because it is "eaten" before in the Editor.
This does NOT happen when the focus is in the Editor toolbar, but ONLY in the editing area.

The problem seems to be in "tinymce/UndoManager":

		editor.on('KeyDown', function(e) {
			var keyCode = e.keyCode;

			// If key is prevented then don't add undo level
			// This would happen on keyboard shortcuts for example
			if (e.isDefaultPrevented()) {
				return;
			}

			// Is character position keys left,right,up,down,home,end,pgdown,pgup,enter
			if ((keyCode >= 33 && keyCode <= 36) || (keyCode >= 37 && keyCode <= 40) || keyCode === 45) {
				if (self.typing) {
					addNonTypingUndoLevel(e);
				}

				return;
			}
			// If key isn't Ctrl+Alt/AltGr
			var modKey = (e.ctrlKey && !e.altKey) || e.metaKey;
                         // >>>>>>>>>> HERE  >>>>>>>>>> 
			if ((keyCode < 16 || keyCode > 20) && keyCode !== 224 && keyCode !== 91 && !self.typing && !modKey) {
				self.beforeChange();
				self.typing = true;
				self.add({}, e);
				isFirstTypedCharacter = true;
			}
		});

*Expected Behavior:*
Do not register the Escape key like a standard key. Let it bubble up to the surrounding code.

*TinyMCE Version:*
tinymce_4.5.3_dev

*In previous version:*
AFAIK, this problem is new to this version.

Kind regards
Karl

**Comment by lnewson** [comment]
The editor isn't "eating" any events here and instead the editor renders its content in an iframe which effectively sandboxes it. So it's actually just normal browser behaviour that's happening here, as you'd see the same thing if you press escape from within an iframe.

If you want to receive an event fired from within the content outside of the editor, then you'll need to either use inline mode or listen to for the event using `editor.on('keydown', ...)` and the fire it manually outside the iframe.
