### ISSUE TITLE
Scroll values of editor.getBody() is wrong

### ISSUE THREAD

**Issue by sentiasa** [tinymce/tinymce#3517]
I am trying to make a side by side sync preview to TinyMCE. I have placed it correctly so it looks like: 
![screen shot 2017-02-27 at 15 59 16](https://cloud.githubusercontent.com/assets/9021386/23370709/e0a46a1a-fd15-11e6-806d-1ab8616bdfd0.png)

When the preview is 50%, I can detect it successfully. However, when I check the values of `editor.getBody()`, the values seem wrong to me.

In init,
```
setup : function(ed) {
   ed.on('init', function() {
      $('.editorContainer > .mce-tinymce > .mce-container-body').children().eq(2).on('scroll', function () {
         var tmceBody = ed.getBody();

         console.log("this offsetHeight: " + this.offsetHeight);   // 501
         console.log("this scrollTop: " + this.scrollTop);             // 160
         console.log("this scrollHeight: " + this.scrollHeight);    //  806

         var percentage = this.scrollTop / (this.scrollHeight - this.offsetHeight);
         console.log("this percentage: " + percentage);    // 0.5

         console.log("TMCE offsetHeight: " + tmceBody.offsetHeight);    // 1009
         console.log("TMCE scrollTop: " + tmceBody.scrollTop);              // 14
         console.log("TMCE scrollHeight: " + tmceBody.scrollHeight);     // 1037

         var x = percentage * (tmceBody.scrollHeight - tmceBody.offsetHeight);

         console.log("TMCE x: " + x);       // 14.2
     
         (tmceBody).scrollTop(x);
       })
      }
     }
  }
```

So when I move preview, editor scrolls but not right value. What am I doing wrong?

**Comment by lnewson** [comment]
Hi,

I think you've misunderstood how things are working here, as the element returned by `ed.getBody()` is the element inside the iframe. As such it is inside a different frame/window and will not have the same values as the `.mce-container-body` which is in the top level frame/window.

To do what you're attempting to do, you'd have to translate the inner iframe window coordinates to the outer/top level window coordinates. Unfortunately, there's not really enough information to provide further guidance, but if you're still experiencing issues please log a new issue with a [fiddle](http://fiddle.tinymce.com/) or similar to reproduce the issue and we'll try to help you.

Thanks!
