### ISSUE TITLE
safari IOS bug with unexpected jump down

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#3518]
Bug on website https://gh-immoprojekt.de on the sites which have embedded iframes. 
For example:
https://gh-immoprojekt.de/angebote/
https://gh-immoprojekt.de/leistungen/verkauf/

If I open this website, content jumps automatically down to the embedded iframe. This behavior is ONLY on the sites with have embedded iframes. The other sites were shown normally with header, logo and the navigation and you can scroll down manually. On Firefox, Chrome and other browsers and on Microsoft the browser view works also fine.

Please support to resolve this buggy view. Thanks
Pe

**Comment by fyrkant** [comment]
How is this connected to TinyMCE?

**Comment by pegrem** [comment]
Sorry - but I have found any threads about IOS Safari bugs. So I have added my browser view problem.
May I remove the thread?
