### ISSUE TITLE
Inconsistent focus behavior for inline nested contenteditable

### ISSUE THREAD

**Issue by aduth** [tinymce/tinymce#3522]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When in inline mode, if the editable content includes a `contenteditable=false` element which itself contains `contenteditable=true`, it is often difficult to focus the nested `contenteditable`, especially when changing focus from another element.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/LKfaab

1. Click "Caption" text
2. Note that occasionally, focus is lost or the cursor is repositioned not where intended (usually to the start or end of the previous or next paragraph)
3. (If working correctly in step 2, try unfocusing editor or moving selection to one of the adjacent paragraphs, then repeat step 1)

If you change to `inline: false` in the configuration and re-run, you should note that in the iframe context the focus behavior is much more consistent.

**What is the expected behavior?**

That the caret is positioned in the "Caption" text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE Edge (4.5.4)
Chrome 56.0.2924.87 (64-bit)
macOS Sierra 10.12.3 (16D32)

**Comment by spocke** [comment]
I think this has been corrected now in the nightly.

**Comment by aduth** [comment]
@spocke Yep, appears to work much better now in nightly. Would you like to go ahead and close the issue or keep it open until a release is tagged?

**Comment by androb** [comment]
@Afraithe can you confirm if this is fixed in 4.8.1?

**Comment by androb** [comment]
Per @aduth this isn't a priority right now as the way in which Gutenberg uses TinyMCE has changed since it was first raised
