### ISSUE TITLE
Textpattern doesn't convert words proceeded by punctuation.

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#3524]
The textpattern plugin only applies start/end formatting when space is pressed, which makes it fail when a word is proceeded by a comma, period, or other punctuation.

Example:

![textpattern](https://cloud.githubusercontent.com/assets/55639/23562481/9a0b8fc2-0010-11e7-939f-e4716206650d.gif)

## Fiddle

The behavior can be observed in any browser, using the latest version of TinyMCE.

http://fiddle.tinymce.com/SKfaab

## Steps to reproduce

1. Enable the textpattern plugin.
2. Type this: `*This* will *work*.`

Expected result:

```html
<p><em>This</em>&nbsp;will <em>work</em>.</p>
```

Actual result:

```html
<p><em>This</em>&nbsp;will *work*.</p>
```

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by claviska** [comment]
Thanks. I tested against edge and it does appear resolved. 👍
