### ISSUE TITLE
Why Custom Embeded Video Code Not Working 

### ISSUE THREAD

**Issue by Ananddwivedi92** [tinymce/tinymce#3529]
Hi ,
 I have started with tinyMCE . I was trying to copy paste below code into HTMl Source Editor  like 
   `<video  id="testplayer"
      data-account="4338955589001"
      data-player="Bkh63tBcx"
      data-embed="default" 
class="video-js" controls=""
      data-video-id="5347595845001"
      style="width: 100%; height: 100%; position: absolute; top: 0px; bottom: 0px; right: 0px; left: 0px;"></video>`
.But When i click on updated it appear on Editor but again if i click on HTML Source editor it clear above code . please let me know what i am missing 

go through : http://archive.tinymce.com/tryit/3_x/full.php and copy pasted above code but after re -open HTML Source Editor it clear .

**Comment by fyrkant** [comment]
Are you using an older version of TinyMCE? If not you should look at the current version documentation page instead of the archive: https://www.tinymce.com/docs/

Can you create a fiddle reproducing the issue? 
http://fiddle.tinymce.com/

**Comment by Ananddwivedi92** [comment]
I am using 4.0 version. and live fiddle is : http://fiddle.tinymce.com/rLfaab/2

**Comment by fyrkant** [comment]
Hmm, no that fiddle is using an old 3.5 version. If you have the possibility my tip is to update to the latest version (4.5.5).

**Comment by Ananddwivedi92** [comment]
It's very hard to update the version of TinyMCE  since it is running on production . is there a way to recover error on same version . and in 3.5 iframe also won't support allowfullscreen attribute if we add explicitly it stripped that attribute

**Comment by Ananddwivedi92** [comment]
Got the solution for this and it works too  closing this issue  : 
`valid_elements: "*[*]"` or if only wants for iframe tag then use `valid_elements: "iframe[*]"`
