### ISSUE TITLE
iPad: Cut and Paste issue in TinyMCE editor

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#3530]
When I have a editor open and type some text... let's say 3 paragraphs. Then, I want to move the 2nd paragraph to the bottom so I highlight the 2nd paragraph and choose [Cut] from pop-up menu after I highlight the text on my iPad. I move my cursor to where I want to paste and hold down the cursor with my finger... the pop-up menu will appear but [Paste] is NOT available. It is as if it never copied the text into memory in the first place.

Interestingly, when I use [Copy] command, it always gives me [Paste] option. I just cannot use [Cut]. Which is annoying since I have to go back and delete the original text.

![image](https://cloud.githubusercontent.com/assets/2102705/23704859/e568b43e-042c-11e7-8049-aa250c327b99.png)

![image](https://cloud.githubusercontent.com/assets/2102705/23704895/111f8e22-042d-11e7-9c7d-4c9aa4df8564.png)

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by poonamkapoor** [comment]
Thanks.
