### ISSUE TITLE
Uncaught TypeError: Cannot read property 'control' of undefined

### ISSUE THREAD

**Issue by zghosts** [tinymce/tinymce#3531]
Since version 4.5.3 the lists plugin it throwing this error due to 'e' not being defined in the onPostRender call.

src/plugins/lists/src/main/js/Plugin.js:125

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Seems to be working fine when I try it and haven't seen any other similar reports. Thanks

**Comment by zghosts** [comment]
Seems to have been caused by an old version of the compat3x plugin, updating it solved the issue, i'll close the issue and the pull request, thanks none the less
