### ISSUE TITLE
Tooltip position misaligned

### ISSUE THREAD

**Issue by vedankita** [tinymce/tinymce#3533]
I am using Tinymce 2.1. I have created form in bootstrap modal, in that I have used tinymce. Problem is tooltip for options not coming correctly.

**Comment by fyrkant** [comment]
Are you sure that you are using version 2.1 of TinyMCE? That is a very old version, so my first advice would be to upgrade to the latest version.

**Comment by vedankita** [comment]
I will try using latest version.

**Comment by fyrkant** [comment]
Yes please do that. I am closing this issue, but if you still have any problem after updating write a comment and we can open it again.

**Comment by vedankita** [comment]
Hi I have used updated version tinymce_4.5.5_dev but problem is still there. Could you please tell me is there any option available for tooltip positioning.

**Comment by Zertuk** [comment]
Are you using transform: translate on the container with a body set to position:relative?

I am running into an issue with that, here is a fiddler example: http://fiddle.tinymce.com/tMfaab

Is there a workaround for this?

**Comment by vedankita** [comment]
Yes I am using position:relative to body. Thank you so much. Could you please tell me how to solve this if I want to give relative position to body?

**Comment by Zertuk** [comment]
I havent been able to figure out a fix yet aside from editing the tinymce source as in: https://github.com/tinymce/tinymce/pull/3030

But I want to avoid doing that,  I will reply here if I figure it out too

**Comment by Zertuk** [comment]
@fyrkant any input on this issue?

**Comment by Zertuk** [comment]
@vedankita not sure if you still need a fix for this, but I was able to fix this by using flex to vertically center the modal with the following css instead of using translate, if you are able to switch to flex this is a quick fix:

`   display: flex;
    flex-direction: column;
    justify-content: center;
    height: 100%;
`

**Comment by Nickproger** [comment]
I have the same issue with latest version of tinemce 
https://github.com/tinymce/tinymce/issues/3802
