### ISSUE TITLE
How do you configure debounce?

### ISSUE THREAD

**Issue by boldwade** [tinymce/tinymce#3535]
I'd like to understand how to configure debounce... 
This would be for version4. The docs show api for it but it's not clear how one actually implements that behavior. Is this something we do on our own or is this built into the editor? I'd simply like to call onkeyup after a certain period of debounce time.

**Comment by fyrkant** [comment]
Here's a simple fiddle showing how you can use the debounce: 
http://fiddle.tinymce.com/9Lfaab

Here are also some examples of us using them in some plugins, like here in the visualchars plugin:
https://github.com/tinymce/tinymce/blob/master/src/plugins/visualchars/src/main/js/Plugin.js#L31-L33

And here in the wordcount plugin:
https://github.com/tinymce/tinymce/blob/master/src/plugins/wordcount/src/main/js/Plugin.js#L34

**Comment by fyrkant** [comment]
@boldwade Did my explanation make this clearer for you? If it did, please close the issue. ✌️

**Comment by boldwade** [comment]
I'm so sorry! Yes it was perfect, thank you so much!!
