### ISSUE TITLE
How to pass data from popup window to the editor?

### ISSUE THREAD

**Issue by danspurway** [tinymce/tinymce#3537]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
I can send variables to popup window. How do I send data back to the editor?
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

**What is the expected behavior?**
Be able to send data back to the editor
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.5.5 (2017-03-07)

**Comment by fyrkant** [comment]
What do you mean with sending data back to the editor? Inserting content?

**Comment by fyrkant** [comment]
No answer so closing this.
