### ISSUE TITLE
useless scrollbar on ie11

### ISSUE THREAD

**Issue by megabast23** [tinymce/tinymce#3538]
- with IE 11, go to https://www.tinymce.com/docs/demo/full-featured/

- remove all editor content

- reduce editor height...

- if you reduce enough, you will see a scrollbar has appeared

**Comment by fyrkant** [comment]
This seems to happen because ie/edge default styles adds some min-height to the body element, can be fixed like this: 

http://fiddle.tinymce.com/ALfaab

**Comment by fyrkant** [comment]
Closing this but if you still have something you want to ask just write a comment and we can open it again. ✌️

**Comment by megabast23** [comment]
Thanks a lot :)
