### ISSUE TITLE
Cannot read property 'nodeName' of null during init "angular 2"

### ISSUE THREAD

**Issue by djleonskennedy** [tinymce/tinymce#3539]
**Do you want to request a *feature* or report a *bug*?**
Clarification

**What is the current behavior?**
Throws exception if plugins are using

related: https://github.com/Ledzz/angular2-tinymce/issues/10

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?** 
tinymce@^4.5.2

**Comment by fyrkant** [comment]
Is this a problem with TinyMCE or with the angular2-tinymce package you linked to? I can't really help you with some third party package, you are probably better off waiting for someone answering you issue on that repo, but by gut reaction is that you haven't imported the plugins correctly, have you followed the steps in the readme over there? https://github.com/Ledzz/angular2-tinymce#plugins

**Comment by djleonskennedy** [comment]
@fyrkant solved, by preload plugins globaly during application load

**Comment by joseroberto** [comment]
I don't know how to resolve this.  Can you @fyrkant explain how can I do that (preload plugins globaly during application load)?  I'm beginner in angular2...

**Comment by antonyjclements** [comment]
I know this is an old issue but what do you mean by "preload plugins globally during application load"? How did you do this?

**Comment by maxyharr** [comment]
> @fyrkant solved, by preload plugins globaly during application load

Can you clarify this? Running into the same issue.
