### ISSUE TITLE
TinyMCE link plugin: link_assume_external_targets does not working as expected

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#3547]
TinyMCE version: 4.5.5 

With TinyMCE link plugin when add link without "http" it shows up confirm dialog asking if the link should be prefixed with `http://`. As per link plugin documentation, confirm dialog will be displayed according to `link_assume_external_targets` settings. By default `link_assume_external_targets` setting is `false` and in that case confirm dialog should not display. When set `link_assume_external_targets` setting  `true` then confirm dialog should display. 

When `link_assume_external_targets:false` ,  it is still displaying confirm dialog when link have `www`  like `www.bbc.com ` while if link is without `www`  like `bbc.com` then its not displaying confirm dialog. As per documentation, it should not display confirm dialog in both cases.

![tinymce link1](https://cloud.githubusercontent.com/assets/2102705/24090905/479353bc-0d6a-11e7-985e-c953a558c490.png)

![tinymce_link](https://cloud.githubusercontent.com/assets/2102705/24090908/51091a26-0d6a-11e7-92b0-ca6f7a004524.png)

**Comment by fyrkant** [comment]
Actually seems like this is working as it should, only the documentation that was a little bit hard to understand. I have updated it now: https://www.tinymce.com/docs/plugins/link/#link_assume_external_targets

Closing this issue as it isn't a bug.
