### ISSUE TITLE
[BUG] Source code view doesn't work on IE11

### ISSUE THREAD

**Issue by Misiu** [tinymce/tinymce#3550]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
After clicking in Tools ->Source code I get empty window.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

**What is the expected behavior?**
After clicking in Tools->Source code source in IE11 code should be visible just like in Chrome
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest - https://www.tinymce.com/docs/demo/full-featured/

After going to https://www.tinymce.com/docs/demo/full-featured/ and trying to view source code (Tools->Source code) in Internet Explorer 11 I get empty window:
![snap 2017-03-21 at 12 23 18](https://cloud.githubusercontent.com/assets/1741838/24145380/3197c878-0e31-11e7-84bf-722c013c0811.png)

I've checked same URL in EDGE and in Chrome 57 and it works fine.
When I visit [main page](https://www.tinymce.com/) I can see source code in IE11, but this looks like different plugin because of syntax highlighting:
![snap 2017-03-21 at 12 25 54](https://cloud.githubusercontent.com/assets/1741838/24145487/95a3080a-0e31-11e7-8f27-f83cad8a90ac.png)

Is there an option to view source on IE11? Maybe this isn't supported by design?

**Comment by Misiu** [comment]
It looks like problem is bug in CSS file - http://www.tinymce.com/css/codepen.min.css:
`.codepen body textarea{display:none}`
after disabling that rule source code is visible again:
![snap 2017-03-21 at 12 49 06](https://cloud.githubusercontent.com/assets/1741838/24146218/06ecac16-0e35-11e7-9f35-c9e35c92b348.png)

Please remove that line if possible.

**Comment by Misiu** [comment]
any updates on this?

**Comment by Misiu** [comment]
@spocke any updates?

**Comment by fyrkant** [comment]
@Misiu Are you still having problems with this? It should have been fixed and it works in ie11 for me.

**Comment by Misiu** [comment]
@fyrkant I'll check that again right away. Maybe my IE has something cached.

**Comment by Misiu** [comment]
After clearing cache everything works fine. Thank You.
