### ISSUE TITLE
Word "Paste" Plugin removing levels of domain

### ISSUE THREAD

**Issue by wddoodle** [tinymce/tinymce#3556]
The following happens when using the Word "Paste" Plugin.

If you copy and paste form Microsoft Word or Outlook content that has bullet points and there is text within the bullet points that has been hyperlinked, then tinymcy will removes one level of the domain from the text being displayed on the screen.

For instance, copying the bulleted item below from Outlook would display the link as "engineering.illinois.edu", it loses the "status.".  The hyperlink itself still functions properly.  And if "http://" is included then everything works properly.  Or if the bullet is removed it pastes correctly.

•	Josh Dotts completed transition of status.engines.illinois.edu over to new data coming from Roberts XI.

**Comment by fyrkant** [comment]
With the "word paste" plugin, do you mean the enterprise [PowerPaste](https://www.tinymce.com/docs/plugins/powerpaste/) plugin? If so you should probably contact the [support](https://support.ephox.com/) to get the best and fastest help!

**Comment by wddoodle** [comment]
No, I was referring to the “paste” plugin that comes with TinyMCE.  Thanks.

**Comment by jayarjo** [comment]
Tried to copy/paste the string from Word, can't repeat the problem. Should the domain portion be linked in Word?

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
