### ISSUE TITLE
Run multiple versions of tinyMCE at the same time on the same page

### ISSUE THREAD

**Issue by nicklasisraelsson** [tinymce/tinymce#3562]
*feature* ?

My company have several products that is using TinyMCE 3.5.11 now but we are looking at if it's possible for us to upgrade.

For us to keep backwards compatibility and make it easier to upgrade in the future we need to investigate if it's at all possible to run our current version at the same time as a new version (4.x) on the same page?

Since TinyMCE needs to be globally accessible to work it doesn't look possible but perhaps we've missed something. 

Is there something that we can do to run multiple version at the same time?

**Comment by Afraithe** [comment]
Hey Nicklas, not really a feature we are looking to implement. Can you not control that via some backend feature/option/sertting of either loading the tinymce 3.x script + init OR the tinymce 4.x script + init?

**Comment by nicklasisraelsson** [comment]
Ok, we were really hoping that there were some way of scoping tinyMCE outside the global scope in newer versions. We'll have to try to find some other way then. Thanks.

**Comment by Afraithe** [comment]
Well you could scope tinymce, but it doesn't help you, the plugins still look for the tinymce. api to interact so no plugins would work.

Some ideas for you: Try the compat3x layer if you have integrations that need the old api etc.

But, can't quite understand why you would need to load 2 scripts in the same page, twice the size and if you can use 4, why keep the other in the same page?

**Comment by nicklasisraelsson** [comment]
It’s a very good question why we would need to run two different versions at the same time. The answer is complicated :)

We provide a framework that is used by different products and developers. At the moment we have a very tight integration with tinyMCE that is locked to the old 3.5.11 version. We want to loosen that integration and make it easier for third party developers to upgrade tinyMCE themselves or even choose their own editor if necessary. We want to create an “editor-package” that would contain the upgraded tinyMCE that users could install on top of the current installation. I think we’ll have to keep the old version as default editor if no “editor-package” is installed for some time going forward. 

So no, we don't _need_ to load the two versions side by side. It would just have been good for us to be backwards compatible by being able to run them side by side. If possible we would like to avoid forcing third party developers to fix any plugin code but still have it as a possibility for them to use the new editor (without their old plugin) side by side.

As you can see there are lots of uncertainties here but we’re only at the start of this process so we’re just looking at what options are available to us.

**Comment by Afraithe** [comment]
I highly suggest you provide an option in the "editor-package" that loads and runs 3 OR 4, not both.

**Comment by maf1a** [comment]
having the same issue. need to run a microfrontend React app with version 5 inside of the page with version 4. 

Microfrontend app will use the one from the page, skipping the tinymceScriptSrc path.
Is there any solution?
