### ISSUE TITLE
modify media plugin popup

### ISSUE THREAD

**Issue by sergiownd** [tinymce/tinymce#3582]
Hei, is there any way to modify how the media plugin renders the pop up? I want to customize it. Thanks.

**Comment by mvkampen** [comment]
Just visually, by using CSS i guess.

I tried to add some javascript functionality to the 'insert link' pop up.
Sadly the event model is limited to the editor, and there is nothing for pop up lifecycle.
Also looked into Command, but didn't give me options for any callback solution.

**Comment by donShakespeare** [comment]
>I tried to add some javascript functionality to the 'insert link' pop up.

I simply forked the link plugin and made it do all the things I ever wanted it to do. I marked all my edits so that I could easily upgrade the code with official plugin

**Comment by fyrkant** [comment]
Hi! There is no way to modify how a plugin dialog should render. The things you can do is either create your own skin to change the look of the whole editor or like @donShakespeare said, fork the plugin and create your own version.
