### ISSUE TITLE
ARM Binary non-existent

### ISSUE THREAD

**Issue by phpmydev** [tinymce/tinymce#3583]
**Do you want to request a *feature* or report a *bug*?**
Request a feature
**What is the current behavior?**
No binary for ARM architecture

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by spocke** [comment]
Not sure what TinyMCE has to do with binaries on ARM?
