### ISSUE TITLE
Tinymce baseURL different in Chrome vs IE

### ISSUE THREAD

**Issue by mboudreau** [tinymce/tinymce#3584]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The baseURL for my project for Tinymce isn't the same for all browsers.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

1. Bundle tinymce or change the script name to anything other than tinymce, like `richtexteditor.js`, and make put it in a path that's not root, like `/js/richtexteditor.js`
2. Try to load tinymce and watch as it works in Chrome/Firefox/Opera but not in IE

**What is the expected behavior?**
It should work consistently between all browsers.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.5.5, All IE (until edge), don't know.

The problem is specifically here: https://github.com/tinymce/tinymce/blob/136c0341aa9f43b720d5942498ed1796f1cb2ccf/src/core/src/main/js/EditorManager.js#L210

I don't see why anyone would want to have a different code path only for [specific browsers that support modern javascript engines](http://caniuse.com/#feat=document-currentscript) for a product that's meant to fully work from IE10 and up.  This just caused me a lot of headaches when a simple path change that was deployed and worked in chrome, but failed to work in IE; since no code was actually changed, I wouldn't think I would need to do a full QA test of code that should already be QA tested.

**Comment by jayarjo** [comment]
Have you tried: [document_base_url](https://www.tinymce.com/docs/configure/url-handling/#document_base_url)?

**Comment by mboudreau** [comment]
Yes, it works, but that isn't the point of this bug. There's still a
blatant issue.

**Comment by spocke** [comment]
I guess we should try to normalize this. However this is limited in scope since if you use cloud, cdn or default bundling of tinymce it will not even use that fallback.

**Comment by techmet** [comment]
We are also having same issue, tinymce is loading themes/skins from correct location where as it is trying to fetch them different location.

I used webpack to bundle the tinymce code and copied the themes and skins in output folder.

Final Output folder is like below

+--bundle.js (where tinymce code exists)
+--themes  (tinymce themes folder)
+--skins  (tinymce skins folder)

Is there any workaround for this issue in IE?

**Comment by mboudreau** [comment]
@techmet I've fixed it on my project by using this semi-hacky workaround with webpack, it's written in typescript, but I'm sure you can understand and just replace a few things to get it working with javascript:

```
let scriptDom: HTMLScriptElement;
const scriptRegex: Regex = /your-javascript-package(\.min)?\.js$/;
// If browser has capability, use currentScript to find Script DOM element
if (document.currentScript) {
	scriptDom = document.currentScript as HTMLScriptElement;
} else { 
	// Fallback for IE
	const scripts = Array.prototype.slice.call(document.querySelectorAll("script"), 0);
	for (let script of scripts) {
		let src = script.getAttribute("src");
		if (src && src.match(scriptRegex)) {
			scriptDom = script;
			break;
		}
	}
}
if (scriptDom) {
	// remove the javascript bit to get the base path for all files
	__webpack_require__.p = scriptDom.src.replace(scriptRegex, "");
}
```

**Comment by vyruss** [comment]
Hi, we've tagged the issue as it affects potentially thousands of users on our services so a documented work-around or fix would be much appreciated - thanks!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
