### ISSUE TITLE
Unpredictable behaviour of UndoManager

### ISSUE THREAD

**Issue by a-a-davydov** [tinymce/tinymce#3586]
_**bug**_

There is code in UndoManager.js lines 48 - 65

      // Get position before an execCommand is processed
      editor.on('BeforeExecCommand', function (e) {
        var cmd = e.command;

        if (cmd !== 'Undo' && cmd !== 'Redo' && cmd !== 'mceRepaint') {
          endTyping();
          self.beforeChange();
        }
      });

      // Add undo level after an execCommand call was made
      editor.on('ExecCommand', function (e) {
        var cmd = e.command;

        if (cmd !== 'Undo' && cmd !== 'Redo' && cmd !== 'mceRepaint') {
          addNonTypingUndoLevel(e);
        }
      });

So it ignores Undo and Redo commands. But commantd is always 'undo' and 'redo', so additional levels always added to stack. It seem it cause some errors in UndoManager logic. (sometimes redo no awilable after undo)

When I change code to

		// Get position before an execCommand is processed
		editor.on('BeforeExecCommand', function(e) {
			var cmd = e.command.toLowerCase();

			if (cmd !== 'undo' && cmd !== 'redo' && cmd !== 'mcerepaint') {
				endTyping();
				self.beforeChange();
			}
		});

		// Add undo level after an execCommand call was made
		editor.on('ExecCommand', function(e) {
			var cmd = e.command.toLowerCase();

			if (cmd !== 'undo' && cmd !== 'redo' && cmd !== 'mcerepaint') {
				addNonTypingUndoLevel(e);
			}
		});

theese problems goes out.

**Comment by fyrkant** [comment]
Hi! 
Could you reproduce the issue in a [fiddle](http://fiddle.tinymce.com/)? When is redo not available after undo?

**Comment by a-a-davydov** [comment]
See http://fiddle.tinymce.com/ZNfaab

I implememt in fiddle small piece of logic from my project, where I have to wrap all table with div.

1. To reproduce issue type "abc" in editor area

2. Put carret between a and b and create table via menu

3. Put carret between b and c (to avoid div inside div) and create another table via menu

4. Click undo button

So last table is removed. It is ok. But Redo button is disabled and Undo button is enabled but has no any effect.

**Comment by abeckh** [comment]
@fyrkant can you have a look at this again, please? I also encounter this problem when inserting spans or divs via custom buttons and the fix posted here saved me quite some time looking for the bug. I can also provide another fiddle, if needed.

**Comment by trevorjay** [comment]
If anyone else is trying to reproduce this bug, here's a version of the fiddle that draws slightly more direct attention to the issue:

    http://fiddle.tinymce.com/gkhaab
