### ISSUE TITLE
Spellchecker plugin throws Error

### ISSUE THREAD

**Issue by umbertoo** [tinymce/tinymce#3587]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It throws error:

> Uncaught module definition dependecy not found: tinymce/PluginManager

**Code:**
```
import tinymce from 'tinymce';
import 'tinymce/themes/modern';
import 'tinymce/plugins/spellchecker';
import 'tinymce/plugins/paste';
import 'tinymce/plugins/link';
import 'tinymce/plugins/table';
import 'tinymce/plugins/lists';
import 'tinymce/plugins/image';
import 'tinymce/plugins/autolink';
import 'tinymce/plugins/textcolor';
import 'tinymce/plugins/noneditable';

require.context(
  '!file-loader?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/skins',
  true,
  /.*/,
);
```

**What is the expected behavior?**
It worked without errors, before update to 4.5.6 v.

**Possible solution:**
it works without errors, if I change the last line of plugin.js file in spellchecker folder:

**from:** (this)
```
...
expose(["tinymce/spellcheckerplugin/DomTextMatcher"]);
})(this);
```
**to:** (window)
```
...
expose(["tinymce/spellcheckerplugin/DomTextMatcher"]);
})(window);
```

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
