### ISSUE TITLE
tinymce-dist@4.5.6

### ISSUE THREAD

**Issue by jgoknowis** [tinymce/tinymce#3590]
cannot use bower and tinymce for dojo build, got following error after 

`npm i`

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.9.5
npm ERR! npm  v4.0.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: tinymce-dist@4.5.6
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'isf-webclient'
npm ERR! notarget
```

after change back to tinymce, it works.

**Comment by fyrkant** [comment]
What do you mean with "tinymce for dojo build"? Is this about some third party package?

**Comment by jgoknowis** [comment]
when i collect tinymce with bower, all is alrigth. but tinymce-dist doesnt work, when i collect with bower and build with dojo (yes Third Party)

**Comment by fyrkant** [comment]
Are you trying to install `tinymce-dist`? That is not correct, please install the `tinymce` package.

**Comment by jgoknowis** [comment]
yes we have used tinymce pure and it will still work.
