### ISSUE TITLE
Invalid paste result on Edge

### ISSUE THREAD

**Issue by PSPvZ** [tinymce/tinymce#3593]
There seems to be an issue when copy-pasting text in the latest version of Microsoft Edge.

1. Go to https://www.tinymce.com/docs/demo/basic-example/
2. Select the word "welcome" (or some other text)
3. Use ctrl-c to copy the text
4. Use ctrl-v to paste the text

The text pasted includes all the headers of the HTML clipboard format and looks as follows:

> Version:1.0 StartHTML:000000238 EndHTML:000002001 StartFragment:000001957 EndFragment:000001964 StartSelection:000001957 EndSelection:000001964 SourceURL:https://s.codepen.io/tinymce/fullembedgrid/YydQrY?type=embed&animations=run
> Welcome
> 

As far as I can tell, this only occurs in the newest release of Edge (the one installed for the Creators update of win10), so Microsoft Edge 40.15063.0.0 (Microsoft EdgeHTML 15.15063).

**Comment by jayarjo** [comment]
This has been resolved now in both 4.5.7 and 4.6.
