### ISSUE TITLE
Initialization promise not resolved

### ISSUE THREAD

**Issue by pdfrod** [tinymce/tinymce#3595]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The Promise object returned by `init` method, is forever stuck in the "Pending" state if there were no editors to initialize (because no element matched the "select" query, or because the matching elements were already initialized). Therefore I can't know, in a reliable way, when initialization is done.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
```
tinymce.init({select: 'unexisting-element'}).then(function() { console.log("done"); }, function() { console.log("failed"); });
```

Nothing is ever print to the console.

**What is the expected behavior?**
I'd expect that the Promise would be resolved with the (possible empty) list of editors.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested with:
- TinyMCE 4.4.1 and 4.5.6
- Ubuntu 16.04.2 LTS
- Google Chrome v57.0.2987.133 (64-bit)

**Comment by spocke** [comment]
Yes, would make total sense to produce a empty array.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
