### ISSUE TITLE
mso-margin-top-alt : auto

### ISSUE THREAD

**Issue by FJancsi** [tinymce/tinymce#3599]
**Bug report**

**MS Word paste functionality**

_Step to reproduce:_

 - Copy some MS word texts with spacing "auto" is set

Expected behaviour:
 - In the parsed HTML there will be: "margin-top: 16px" or "margin-top: 1em" [(MS Word spacing)](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_other/what-does-auto-paragraph-spacing-do/16a4c7c4-f743-e011-9577-d485645a8348)

Current behaviour:
 - In the parsed HTML there will be: "margin-top: px".

TinyMCE version: 3.5.7

**Comment by spocke** [comment]
Not a critical bug and on a version that is maintenance mode only for critical fixes. I suggest upgrading to 4.x and possible tying out our awesome powerpaste plugin that retains word contents.
