### ISSUE TITLE
Selected image is not deleted in Edge and IE when it is the first node in a paragraph

### ISSUE THREAD

**Issue by ChristophKaser** [tinymce/tinymce#3601]
Steps to reproduce:

- Open the following pen in **IE or Edge**: http://codepen.io/anon/pen/eWBNZV
- Select the image of the red triangle
- Press the **delete** key

**Behavior**:
The caret moves before the image, the image remains in the document
**Expected**:
The image should be deleted. This is the behavior in Chrome and Firefox

This seems to be connected to the fact that the image resize handles have contenteditable="false" attributes (only) in IE and therefore isEditableCaretCandidate(resizeHandle) returns true.
(See [ControlSelection.js:347](https://github.com/tinymce/tinymce/blob/master/src/core/src/main/js/dom/ControlSelection.js#L347))

**Comment by spocke** [comment]
This seems to be fixed in the nightly build can you help us verify that. Thanks

**Comment by ChristophKaser** [comment]
I could not reproduce this in the nightly build, so it seems to be fixed :)
Thank you very much!
