### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fontFamily' of undefined

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#3603]
**Do you want to request a *feature* or report a *bug*?**
its a bug

**What is the current behavior?**
see http://codepen.io/manu37/pen/WjoogZ

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.
see http://codepen.io/manu37/pen/WjoogZ

As soon as there's a HTML comment in the 1st line of the source-code , TinyMCE throws:

`Uncaught TypeError: Cannot read property 'fontFamily' of undefined.`

That doesn't seem to happen with TinyMCE 4.5.0, but with >=4.5.3.

However if you insert 
`if (elm.nodeType === 8) return ''; `
just before the error causing [line  #](https://github.com/tinymce/tinymce/blob/master/src/core/src/main/js/fmt/FontInfo.js#L24) tinymce seem to work.

We need the comment tag as split marker in our project.

**Comment by eroomekim** [comment]
We are using this version as well in our system and have run into the same bug. Errors out only when there is an HTML comment in the 1st line.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by nalmar26** [comment]
@spocke  Which release is this fixed in?
