### ISSUE TITLE
error in console after combo-wombo

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#3605]
steps: 
1 type word
2 click bold-button and type word
3 copy 
4 click bold-button
5 insert
6 click bold button

error in console: DOMException: Failed to execute 'setStart' on 'Range': The offset 3 is larger than the node's length (1).

demo: http://codepen.io/tinymce/pen/NGegZK
see: https://youtu.be/sHOMtkc4K_s
win 7 chrome 58

**Comment by shahchaitanya** [comment]
@PetrBorisov Did you find any solution to resolve this issue? I'm facing same error.
