### ISSUE TITLE
how to use language in react-tinymce

### ISSUE THREAD

**Issue by yangguixue** [tinymce/tinymce#3607]
feature

i want to change language, but i used react-tinymce

"react-tinymce": "^0.5.1",

**Comment by spocke** [comment]
Not sure I understand?

**Comment by saitonakamura** [comment]
I have the same question: how to change language using `react-tinymce`?
When I set it like this
```
      <TinyMCE
        content={value}
        onChange={handleChange}
        config={{
          statusbar: false,
          toolbar: 'bold italic bullist numlist undo redo styleselect outdent indent',
          language: 'ru',
        }}
      />
```

It goes to `https://cloud.tinymce.com/stable/langs/ru.js` and gets `Access denied`
I also tried `ru_RU`

**Comment by fyrkant** [comment]
Closing this as we do not have anything to do with the `react-tinymce` package, instead try our official react wrapper: https://github.com/tinymce/tinymce-react
