### ISSUE TITLE
Several issues/bugs on media plugin

### ISSUE THREAD

**Issue by Taygair** [tinymce/tinymce#3614]
All tested on Mac (OS Sierra) in Safari, Firefox and Chrome browser with tinymce 4.5.7

**Adding mp4-video (media plugin):**
After inserting there is the following error in Javascript console: "Failed to load resource: Last von Plug-In bearbeitet"

**Adding video/reopening tinymce editor:**
After adding a mp4-video (media plugin) reopening the editor or switching to preview any video embedded from localhost starts playing (as it would be set to autoplay) while f.e. an embedded video from youtube will not start right away. This happens only if the video is embedded in iframe. If there is a placeholder video image the video wouldn't autoplay switching to preview. 

**Adding video:**
Added videos in different ways from localhost will not be embedded in iframe:
a) Entering this in source input (relative): ../gallery/video/555613a2-0023-c6ec-546e-a34e39c215c3.mp4
b) Entering this in source input (absolute): http://localhost/myproject/gallery/video/555613a2-0023-c6ec-546e-a34e39c215c3.mp4

Entering a youtube video-link will be embedded in iframe (correct). Its not clear in documentation how to embed a video correctly so it will be embed in iframe and can be played inside tinymce editor.

**Align video**
It took me a while to find this bug. You can't mark a video and f.e. align it to middle (center). Nothing will happen. But if you set the cursor right or left to the video, press any align button then the embeded video will be aligned.
This is confusing because you can select an image (even a video not embeded) and then it will be aligned.

**Resize video:**
While it is possible to set a height or width of an image using '%' you can't do that on embeded videos. Height or width are always fixed. I tried to override it programmatically but even this will be ignored.

**Comment by Taygair** [comment]
The autoplay behaviour relates also audio files from localhost

**Comment by whol019** [comment]
Now TinyMce display iframe site within editor, I found it is confusing:

1. Quite some pages use iframe to embed google doc, youtube videos or other sources. when editing these pages with iframe, the say google doc window display within tinymce editor, with the google tool bars and editable areas within iframe in the tinymce iframe editor, these double editing interface is quite confusing.

2. difficult to select the iframe, set alignment or design LTI plugins around the iframe resource.

I like the previous iframe display as an image design. Dont quite understand why make the change now to display iframe website within editor, it feel like a backward step for me.

**Comment by Taygair** [comment]
@whoI019 : If I got you right: You still can use the image design. Just don't use the embed functionality. That means on init tinymce add: "media_live_embeds: false" (default is true)

**Comment by whol019** [comment]
Thanks for the pointer. Some instances we cannot tweak.
( our LMS is controlled by external company in other country ). 
I will suggest them. 
Thanks
Wen

**Comment by jltavares** [comment]
Hello people,

there is some concern about the "Resize video" item? I am having trouble with resizing of embedded YouTube iframe in TinyMCE. There is no problem with other sources, e.g. Vimeo. But, when the embedded media is from YouTube, the size of the iframe is hardcoded to 425x350 and cannot be changed anywhere in the dialog. The functionality of add embedded media via TinyMCE dialog is great for final users, but is not so evident to change these stuffs via CSS, so it will be great trying to address this issue.

Thank you very much in advance.

**Comment by cantuket** [comment]
Can someone provide an example on how to add resizing handles to any element?

**Comment by sitecarp** [comment]
Any update on this? The following are still not possible for media elements:

- right, left, or center-align
- re-position by dragging WHILE the iframe is selected/highlighted.
 - This is presumably because the iframe content becomes interactive.
- resize with corner handles
- apply formatting (such as wrapping the iframe in <blockquote>)
 - or in my case, wrapping it in a custom format to add a border

**Comment by SIMRAN88** [comment]
Hi There, 
In TinyMCE 5 some of the embed media which was not appearing in preview is fixed. It is working properly in TinyMCE 5.

**Comment by jycoldhands** [comment]
> Hi There,
> In TinyMCE 5 some of the embed media which was not appearing in preview is fixed. It is working properly in TinyMCE 5.

Hi，
I still find that the user will not be able to preview the video in real time in the editable area, and the placeholder image will still be displayed. 
This means that the media_live_embeds attribute does not take effect.
![1577185245(1)](https://user-images.githubusercontent.com/31240067/71428506-2a35bb80-26fc-11ea-8e6d-efb0345e4a38.jpg)

**Comment by gdoudeng** [comment]
> > Hi There,
> > In TinyMCE 5 some of the embed media which was not appearing in preview is fixed. It is working properly in TinyMCE 5.
> 
> Hi，
> I still find that the user will not be able to preview the video in real time in the editable area, and the placeholder image will still be displayed.
> This means that the media_live_embeds attribute does not take effect.
> ![1577185245(1)](https://user-images.githubusercontent.com/31240067/71428506-2a35bb80-26fc-11ea-8e6d-efb0345e4a38.jpg)

+1

**Comment by lnewson** [comment]
Can you include the url you are trying to embed? As I believe this is expected, as currently iframe's are the only thing that works with live embeds. We can re-evaluate that and see if native rendering of videos, etc... works on all supported browsers, however I believe the last time it was evaluated there were still issues.

**Comment by luisdiaslima** [comment]
Any update? I still can't align my videos

**Comment by tcdtist** [comment]
i just want to have the function to select and align the video so please add it if possible. thank you

**Comment by shanereichart** [comment]
@tcdtist @luisdiaslima, there's another ticket for the more specific issue of being unable to align/float media/iframes. It might be worth commenting there also to cast your vote. #3665

**Comment by theZappr** [comment]
Hello. We are still on TinyMCE 6 was this fixed before/in v7 ?
