### ISSUE TITLE
Insert link inserts newlines before and after link

### ISSUE THREAD

**Issue by dhalbert** [tinymce/tinymce#3615]
Using TinyMCE 4.5.1 in conjunction with Wysiwyg module in Drupal 7.x:

Inserting a link also inserts newlines before and after link. E.g.:

`abcdef`  

Clicking between `c` and `d` and inserting a link `http://example.org` yields:
```
abc

http://example.org

def
```

I am trying to figure out if this is a bug or a mistake in some setting. I haven't found a setting that would seem to control this.

**Comment by fyrkant** [comment]
I'm having problems reproducing this, can you create a [fiddle?](http://fiddle.tinymce.com/)

**Comment by dhalbert** [comment]
Sorry, turns out this is a Drupal issue. If the [Wsiwyg Linebreaks
](https://www.drupal.org/project/wysiwyg_linebreaks) module is installed and "Force Linebreaks" is set in the Wysiwyg profile, I see this problem. I haven't debugged that yet but am recording it here for posterity.
