### ISSUE TITLE
Icon for "Table of Contents" plugin missing when using a custom style again

### ISSUE THREAD

**Issue by sea75300** [tinymce/tinymce#3622]
I already reported this issue last year.

Using a custom skin and a toolbar button for the table of contents plugins results in an empty button. Using lightgrey and co. is fine from the default TinyMCE package, but not from skin customizer. The problem re-appeared in March or so during one of the last 4.5.x releases.

**Comment by Afraithe** [comment]
We will update the skin customizer this week and it should take care of these issues.

**Comment by Afraithe** [comment]
The skin website is updated, so this is fixed now.
