### ISSUE TITLE
Cannot backspace a link to the previous line

### ISSUE THREAD

**Issue by doneholmes** [tinymce/tinymce#3626]
Steps to Reproduce:

1. Type some text on line 1 and press enter
2. Type some text on line 2
3. Highlight the text and use the insert/edit link tool to make it a link
4. Put cursor before the link text at the beginning of line 2 and press backspace.

Result: The link text is stuck on line 2.
Desired result: The new line should be deleted and the link text should be moved to the end of line 1.

This issue was introduced in the latest release (4.6.0) and is not present in the previous release (4.5.7).

**Comment by spocke** [comment]
We noticed this one as well. We have a fix for it in the works for 4.6.1.

**Comment by fyrkant** [comment]
Hi @doneholmes ! This should be fixed now in the 4.6.1 version we releases yesterday, can you try it out and close the issue if it seems to be working?

**Comment by doneholmes** [comment]
It looks to be working, thanks!
