### ISSUE TITLE
V4.6.0 loading error with jquery (and compressor)

### ISSUE THREAD

**Issue by chrispcb** [tinymce/tinymce#3627]
**Chrome log:**
Uncaught TypeError: Cannot read property 'dom' of undefined
    at HTMLScriptElement.o.onload.o.onreadystatechange (jquery.tinymce.min.js:1)
o.onload.o.onreadystatechange @ jquery.tinymce.min.js:1

**Firefox log:**
TypeError: h is undefined  jquery.tinymce.min.js:1:3947
	f.fn.tinymce/o.onreadystatechange

Works fine if you replace jquery.tinymce.min.js with 4.5.7 version.

**Comment by fyrkant** [comment]
Hi @chrispcb ! This should be fixed now in the 4.6.1 version we releases yesterday, can you try it out and close the issue if it seems to be working?

**Comment by chrispcb** [comment]
Yes, fixed ! thanks !

**Comment by thomich** [comment]
jup.. also tested and it's fixed, many thanks for fast fix ;)
