### ISSUE TITLE
4.6.0 jquery.tinymce.js 'define is not defined' 

### ISSUE THREAD

**Issue by dorianfm** [tinymce/tinymce#3629]
After upgrading to tinymce 4.6.0 from 4.5.7, using npm or composer, my application reports this error:

Chrome:
> jquery.tinymce.js:17 Uncaught ReferenceError: define is not defined
>     at jquery.tinymce.js:17
> 

Firefox:
> ReferenceError: define is not defined[Learn More]  jquery.tinymce.js:17:1

Safari:
> [Error] ReferenceError: Can't find variable: define
> 	Global Code (jquery.tinymce.js:17)

The code in jquery.tinymce.js appears to now be written as a RequireJS module include, 

4.6.0:
> /**
>  * Jquery integration plugin.
>  *
>  * @class tinymce.core.JqueryIntegration
>  * @private
>  */
> define(
>   tinymce.core.JqueryIntegration',
>   [
>   ],
>   function () {{
> 

vs 4.5.7
> /*global tinymce:true, jQuery */
> 
> (function($) {
> 

Is this an intended change, if so where is the reference to it in the change log or the documentation about the change and how to avoid this error - is RequireJS or another module loader now a requirement to use jquery integration?

**Comment by spocke** [comment]
This was a mistake it should be the built version. This will be corrected in 4.6.1.

**Comment by fyrkant** [comment]
Hi @dorianfm ! This should be fixed now in the 4.6.1 version we releases yesterday, can you try it out and close the issue if it seems to be working?

**Comment by dorianfm** [comment]
hi @fyrkant , it appears to be working correctly now. 

One thing to note is that jquery.tinymce.js appears is the same as jquery.tinymce.min.js - ie the un-minfied version it is minified. Not a serious issue (for me) but probably something you want to resolve in future.
