### ISSUE TITLE
Feature: Can Skin Generator be released to be downloadable?

### ISSUE THREAD

**Issue by donShakespeare** [tinymce/tinymce#3630]
It would be great to have some open source/community Skin Generator.
At least downloadable, so that we can carry on the TinyMCE skin magic.

There are a few things I'd like to add (right from the generator), smaller toolbar buttons and many other awesome things.

Thanks.

**Comment by Afraithe** [comment]
Hey Don, thanks for the feedback. We are kind of contemplating remaking the skin tool, it could be so much simpler, would also like to be able to save and load skins in a repository so ppl can search/view community created skins. This is some ways off though.
