### ISSUE TITLE
[4.6.1] Configured link_list URL not working same as in v4.5.x

### ISSUE THREAD

**Issue by thomich** [tinymce/tinymce#3637]
**Do you want to request a *feature* or report a *bug*?**
Bug, feature changed

**What is the current behavior?**
Using a URL in link_list option stops working, if using same URL then eg. for v4.5.7.
Our output until v4.5.7 from the link_list URL is similar to this:
[
    {title: 'TinyMCE', value: 'http://www.tinymce.com'},
    {title: 'Moxiecode', value: 'http://www.ephox.com'},
    {title: 'TinyMCE resources', menu: [
      {title: 'TinyMCE documentation', value: 'http://www.tinymce.com/docs/'},
      {title: 'TinyMCE forum', value: 'http://www.tinymce.com/forum/'}
    ]}
  ]

We wrote a PHP script, which does load the link_list content from the database (whole menu structure).
Check this for the output: http://demo.nilooma.com/system/plugins/tinymce/4.5.7/lists/link_list.php

**What is the expected behavior?**
Currently with 4.6.1 if using same PHP script, it shows JS error:
11:51:37.054 VM16675 ?lid=1:1 Uncaught SyntaxError: Unexpected token ' in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.success (plugin.js?v=4.6.1:483)
    at ready (tinymce.js:46736)
success @ plugin.js?v=4.6.1:483
ready @ tinymce.js:46736

![image](https://cloud.githubusercontent.com/assets/4398840/25943519/65fe8e94-3640-11e7-821c-25c1baf0c1ff.png)

If it is a feature change, let us know, cause i don't see anything about link_list in changelog for 4.6.0 or 4.6.1: https://www.tinymce.com/docs/changelog/

Many thanks for test and feedback.

Regards
thomi

**Comment by alecpl** [comment]
Your response is not valid JSON. I think it's about the single quotes.

**Comment by thomich** [comment]
Hey @alecpl 

I know that ;) i just wanted to inform, that earlier made scripts no longer work, as earlier, i think since v3 we could use exact same response...

I will change my script to the need, but it would be nice, if there are some examples for main dev languages, like PHP, PY and any other big dev language...

Examles should be here: https://www.tinymce.com/docs/plugins/link/#link_list

thomi

**Comment by thomich** [comment]
Okey.. some hours later ;)

its about escape strings... as i have to escape string in my PHP script, cause we can use title like "Test's" and similar. I changed needed stuff in my PHP Script and now TinyMCE 4.6.1 link_list with PHP URL does work..

Here a output what i got from PHP script, which will now work:
![image](https://cloud.githubusercontent.com/assets/4398840/25949280/403cf1b6-3657-11e7-8973-97c141ab16c6.png)

I made a small snippset about a possible way in PHP.
https://bitbucket.org/snippets/thomi/Grrox/tinymce-link_list-php-script 

regards
thomi
