### ISSUE TITLE
Color picker for forecolor unusable because it is clipped by browser window

### ISSUE THREAD

**Issue by davidearl** [tinymce/tinymce#3639]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Using the forecolor menu item for textcolor, when it is the last button in the row and the row is more-or-less the same width as the browser window, then the color picker is largely clipped by the browser window and therefore unusable

This is a particular problem in full window mode on narrow-ish windows, and especially on smaller screens with the browser set as wide as it will go, with a long row of buttons where the color picker happens to be last in a group and the group is last in the row, which is only just wide enough to fit the window.  In that case, the user is essentially stuck if they want to use this button.

![colorpickerclipped](https://cloud.githubusercontent.com/assets/1050651/25960552/2df5b3fe-366f-11e7-9d18-063b7eee0843.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

https://codepen.io/anon/pen/YVaYaL

**What is the expected behavior?**

I'd expect it to adjust the color picker position so as to be entirely visible, not to be off the edge.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

The one in your codepen fails, as does 4.5.7 in my own project. Certainly Chrome and Firefox: I don't suppose it is browser specific.

**Comment by tinydylan** [comment]
It looks like this issue has been corrected since you logged it. If the issue still occurs, please let us know.

**Comment by davidearl** [comment]
Yes, the color picker has been completely changed in 5. I can confirm it works now. Thank you.
