### ISSUE TITLE
Issue with CSP

### ISSUE THREAD

**Issue by ivp199** [tinymce/tinymce#3640]
#I am using tinymce and it was working great till this morning. I have also added Content-Security-Policy header in the application.

However, with the latest release 4.6.1 (released yesterday), I am getting an error about violation of Content-Security-Policy. Below is the error.

```
tinymce.min.js:14 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' http://cloud.tinymce.com/stable/tinymce.min.js https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.8/clipboard.min.js".
    at Function (<anonymous>)
    at tinymce.min.js:14
    at b (tinymce.min.js:8)
    ...
```

When I use the older version 4.5.7, tinymce works perfectly fine.

Can you please have a look into this? And kindly remove inline script in case it is added.

Thanks in advance.

**Comment by Daijobou** [comment]
Here is another issue with CSP https://github.com/tinymce/tinymce/issues/1901

Which CSP setting you use?

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
