### ISSUE TITLE
How to change font size dynamically?

### ISSUE THREAD

**Issue by jonjie0317** [tinymce/tinymce#3642]
How to change font size dynamically? hmm, is it for static only?  what if the user wants to change the font size according to the desire font? is this means that I have to put 1pt-1000pt statically ??  I can't imagine how that long, this is heavy to load as well. Thanks much for your package by the way :)

**Comment by lostkeys** [comment]
This is a rather old issue and I don't fully understand exactly what's asked for, so I'm closing this issue. Please feel free to reopen it and add more details if you still need this fixed.

**Comment by lostkeys** [comment]
Related issue: #3330
