### ISSUE TITLE
Can't delete previous tag block without destroying format

### ISSUE THREAD

**Issue by linux-man** [tinymce/tinymce#3646]
Example:
```
<h1>Title</h1>
<h2>Text</h2>
```
If I delete "Title", "Text" becomes \<h1>.
That's an unexpected behavior. \<h1> tag should be deleted.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by linux-man** [comment]
Almost there...
If I delete Title with backspace, H1 is deleted, but using delete key the behavior stays the same.
I assume that tinymce.com demo is updated.
