### ISSUE TITLE
console errors when opening tinymce in a lighbox more than once on the same page

### ISSUE THREAD

**Issue by propertunist** [tinymce/tinymce#3648]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
if i load tinymce inside a colorbox lightbox, then close the lightbox and then reopen the lightbox and type something in tinymce, then i see this error in the console:
```
TypeError: e.replace is not a function -   tinymce.min.js:13:19142
```
**What is the expected behavior?**
tinymce should loud and function without error

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
i am using tinyMCE 4.6.1 and have tested several earlier versions - they all fail in the same way.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by propertunist** [comment]
this has now been resolved, it was an issue with a plugin unrelated to tinymce. closing
