### ISSUE TITLE
Can't go to second level in list when in a table

### ISSUE THREAD

**Issue by e11en** [tinymce/tinymce#3657]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you are in a table and you're making a list then you can't go to the next level of the list. When you press tab you just go to the next field or row.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo**
![demo](https://i.makeagif.com/media/5-17-2017/Hyox8w.gif)

**What is the expected behavior?**
Go to the next level when pressing tab

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Wordpress TinyMCE Advance v4.5.6 but this also happens on the demo on your website.

**Comment by fyrkant** [comment]
Hi!
Thank you for this bug report. While we are working on a fix as a workaround you can add the `indent` item to your toolbar and use that to go to the the next level in a list inside a table.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
