### ISSUE TITLE
Can't edit or add content using the code plugin - for version 4.6.1

### ISSUE THREAD

**Issue by harunthuo** [tinymce/tinymce#3658]
I'm trying to use the code plugin but it looks as though it is disabled i.e incase of adding new content, its not clickable and incase of an edit, the content does get loaded in the code window but again, can't edit as it is not clickable / is disabled. below is my javascript initialization code for tinymce: 

var editor_config = {
    path_absolute : "{{URL::to('/')}}/",
    selector      : "textarea",
    plugins: [
      "advlist autolink lists link image charmap hr anchor pagebreak",
       "insertdatetime media nonbreaking save table contextmenu directionality",
       "code"
    ],
    menubar: false,
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media code"
    
};
tinymce.init(editor_config);

what could be the issue?

**Comment by fyrkant** [comment]
I [created a fiddle with your config](http://fiddle.tinymce.com/bQfaab) but I am not having any problems opening the code dialog and edition/adding content. Can you reproduce the issue on that fiddle?

Maybe it is some other javascript on your site that is interfering with TinyMCE, or perhaps some CSS?

**Comment by harunthuo** [comment]
hmm.. you're right @fyrkant .. run a fiddle and everything seems fine. so clearly not a tinymce issue. i'll dig deeper and get to the root of the problem. thanks for your input!

**Comment by harunthuo** [comment]
forgot to mention an important point: i'm opening the tinymce inside a boostrap modal. based on this, i found a solution from here:

http://stackoverflow.com/questions/18111582/tinymce-4-links-plugin-modal-in-not-editable

simply, adding this solves the issue:

$(document).on('focusin', function(e) {
    if ($(e.target).closest(".mce-window").length) {
        e.stopImmediatePropagation();
    }
});

**Comment by dmuellerstl** [comment]
Just wanted to leave a note that the fix above http://stackoverflow.com/questions/18111582/tinymce-4-links-plugin-modal-in-not-editable worked for me as well. Could not edit Tiny MCE html source code in bootstrap 3 modal.

**Comment by Firzenizer** [comment]
Thanks @harunthuo this fixed the problem for us too.

**Comment by petrprikryl** [comment]
I have same problem when opening editor in dialog https://stackoverflow.com/a/18209594/1763888

**Comment by Danilo-Guedes** [comment]
If you're encountering issues with TinyMCE-React not allowing source code editing within an MUI Dialog component, the problem likely stems from focus propagation and behavior. To resolve this, you can modify a single prop in the Dialog component:

```
    <Dialog
      open={open}
      onClose={(_, reason) => {
        if (reason === 'backdropClick') return;
        handleClose();
      }}
      aria-labelledby="send-email-modal"
      disableEnforceFocus   //<<<< SET THIS TO TRUE
    >
```

By setting disableEnforceFocus to true, you should be able to edit the source code without any problems.
