### ISSUE TITLE
Umage upload not working

### ISSUE THREAD

**Issue by speller** [tinymce/tinymce#3661]
Using https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=**** version.

Trying to upload images with this code in latest Chrome:

	tinymce.init({
		selector:'#value',
		inline: true,
		document_base_url: 'https://mydomain',
		plugins: 'paste lists anchor link code textcolor image imagetools table autosave autoresize save',
		menubar: 'edit insert view format table tools',
		toolbar: [
			'save | undo redo | paste | bold italic underline | alignleft aligncenter alignright alignfull | ' +
			'forecolor backcolor | formatselect | image link | table | code | restoredraft'
		],
		rel_list: [
			{ title: 'Default', value: 'noopener noreferrer'},
			{ title: 'Nofollow', value: 'nofollow noopener noreferrer'}
		],
		link_context_toolbar: true,
		relative_urls: false,
		image_title: true,
		automatic_uploads: true,
		images_upload_url: 'https://mydomain/file',
		images_upload_credentials: true,
		file_picker_types: 'image',
		file_picker_callback: function(cb, value, meta) {
			var input = document.createElement('input');
			input.setAttribute('type', 'file');
			input.setAttribute('accept', 'image/*');

			input.onchange = function () {
				var file = this.files[0];
				var id = 'blobid' + (new Date()).getTime();
				var blobCache = tinymce.activeEditor.editorUpload.blobCache;
				var blobInfo = blobCache.create(id, file);
				blobCache.add(blobInfo);
				cb(blobInfo.blobUri(), {title: file.name});
			};

			input.click();
		}
	});

When selecting an image I get the following error in the JavaScript console:

```
tinymce.min.js?apiKey=****:17 Uncaught blob and base64 representations of the image are required for BlobInfo to be created
g	@	tinymce.min.js?apiKey=****:17
f	@	tinymce.min.js?apiKey=****:17
input.onchange	@	ru:246

```

I took this code from the docs.

What I do wrong?

**Comment by spocke** [comment]
Yes, the example was wrong and has since been updated.

**Comment by Allan1** [comment]
Just ran into this issue. Here is the link for the updated example: [https://www.tinymce.com/docs/demo/file-picker/](https://www.tinymce.com/docs/demo/file-picker/)

**Comment by lccjavo** [comment]
I'm having the same error in the console in the version 4.6.4-dev

**Comment by ManyouRisms** [comment]
#metoo

**Comment by amaan-gani** [comment]
i m uploading images , but at my website it is not showing
