### ISSUE TITLE
Backspace/Delete not working around links since 4.6.

### ISSUE THREAD

**Issue by deeg** [tinymce/tinymce#3662]
Please see #3632. This is an exact duplicate, please feel free to open that issue back up.

The issue still persists and can be seen on the demo page for tinymce in the chrome browser (at the very least).

[See this comment for steps to reproduce.](https://github.com/tinymce/tinymce/issues/3632#issuecomment-301549589)

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
