### ISSUE TITLE
A way to optimize many many elements added for each editor?

### ISSUE THREAD

**Issue by Luke-SF** [tinymce/tinymce#3663]
**What is the current behavior?**

Go to a page with one inline MCE editor, and you'll see a ton of elements are added for toolbars etc:
`jQuery('.mce-panel *').length` returns over 100 elements.

If you add 7 more editors with identical toolbars, you may now have about 1000 elements in dom, just to do the same functions, on different editors!

This can get to be fairly slow and memory-hogging if you happen to have some page with dozens or hundreds of editor entries... even with the same toolbar that could be reused.

**What is the expected behavior?**
Ideally there should be a way to optimize editors that are essentially the same.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I think all versions are affected?

**Comment by fyrkant** [comment]
I am not sure I understand what you mean. All the elements added to the document are a part of the editor UI, so to decrease the amount of elements would mean to remove parts of the UI. There is no other way to optimize this, as far as I know.

**Comment by Luke-SF** [comment]
Basically there should be a way to have a number of editors with the same toolbars... without forcing the browser to keep N times as many elements in memory as it needs to, for any N number of equivalent editors on the page.
