### ISSUE TITLE
Is there a way to access TinyMCE’s HTML sanitizer?

### ISSUE THREAD

**Issue by LeaVerou** [tinymce/tinymce#3664]
Hi there,

Thank you all for creating a great product!

I’m using TinyMCE to edit a certain area on a page, whose data is loaded via JS.
I know TinyMCE does HTML sanitization, so I was wondering if its sanitization functions are exposed so I can use them in my code, to avoid XSS before the HTML even gets to TinyMCE.
I looked at the API docs, but couldn’t find it.

Thanks in advance!

Related to https://github.com/mavoweb/plugins/issues/7#issuecomment-302282330

**Comment by jayarjo** [comment]
@LeaVerou we do not have any extended documentation on it, but some information can be found under API Reference, here: [tinymce.html.Serializer](https://www.tinymce.com/docs/api/tinymce.html/tinymce.html.serializer/) and here: [tinymce.html.DomParser](https://www.tinymce.com/docs/api/tinymce.html/tinymce.html.domparser/) for example.

**Comment by LeaVerou** [comment]
I had seen those, but I hadn't realized that indeed, it was as simple as the example in the docs:

```js
new tinymce.html.Serializer().serialize(new tinymce.html.DomParser().parse('<p>text</p>'));
```

Lovely!

**Comment by donShakespeare** [comment]
Very excellent piece of code. I use it to initialize TinyMCE inline mode on Textareas.
I append a DIV to each textarea and use the parser to grab the content to the DIV
https://github.com/tinymce/tinymce/issues/3677
