### ISSUE TITLE
Resize handle of editor is hidden

### ISSUE THREAD

**Issue by Stadly** [tinymce/tinymce#3666]
When a TinyMCE instance is not shown when the page is loaded, but appears later, the little text "Powered by TinyMCE" is placed on top of the editor resize handle, making it impossible to resize the editor.

You can see the error in action at this [Codepen](https://codepen.io/Stadly/pen/eWPPXm).

I have tested it in Chrome 57.0.2987.133, using TinyMCE 4.6.1.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
