### ISSUE TITLE
is there any multi select box option in tiny mce popup ?

### ISSUE THREAD

**Issue by sadiqrajani** [tinymce/tinymce#3667]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by fyrkant** [comment]
Please provide more information, what do you mean with multi select box?

**Comment by fyrkant** [comment]
No answerso I'm closing this.
