### ISSUE TITLE
Editor window scrolls to top after dialog box closed

### ISSUE THREAD

**Issue by speller** [tinymce/tinymce#3669]
Example: http://fiddle.tinymce.com/3Qfaab . Scroll editor to bottom, open any dialog (such as Image insert) and close it using Cancel button. Editor window will be scrolled to top after closing.

**Comment by bhol** [comment]
Thanks for adding me @blackcathikari I am having the same issue. I have confirmed it is broken in the Chrome browser on Mac, but one of my developers works on a Linux laptop with Chrome and the  loss of focus and scrolling to the top does not occur for him. It appears it may be certain OS / Chrome combos.

**Comment by speller** [comment]
I have this issue under Windows 7.

**Comment by donShakespeare** [comment]
CDN -latest
Inline Mode
First I thought it was my notorious ExtJS environment, with lods of parents.

Issue persists here. On insert image, link etc. Dialog buttons (ok/cancel)
So I think it might be a focus/blur problem.

**Comment by manishbafna** [comment]
This happens on all dialogs that have a textbox.

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by bhol** [comment]
Is there a new version of tinymce with a patch for this? Which version do we need to be on for this patch as this affected us? Thanks.

**Comment by fyrkant** [comment]
4.6.4 was released earlier today.

**Comment by parisiam** [comment]
FYI, I have the same issue in 5.0 rc2

**Comment by cmoreau** [comment]
Same here with v5.0.7 ... 😞

**Comment by Jitender-Singh-Negi** [comment]
Facing same issue :(

**Comment by operaman2100** [comment]
Same issue 5.1.6

**Comment by theflyingbrush** [comment]
Experience this in Chrome with version 5.10.3 from CDN
