### ISSUE TITLE
List plugin bug / list item markers don't align 

### ISSUE THREAD

**Issue by ayZagen** [tinymce/tinymce#3671]
Bullet or numbered lists content is aligning to the right or center, however list markers staying the same. Editors in general aligning them too.

**Comment by fyrkant** [comment]
It is possible to align the list items with the align buttons, but because it is not possible to select the ul/ol element in the editor you can't align the whole list. You could open the source code editor and manually add a `style="float:right;"`, I guess. Hope that solves it for you, closing this.

**Comment by ayZagen** [comment]
@fyrkant yeah ofc i can do that manually but we are testing tinymce, and if it satisfies our needs we will be using it in our product. So customers will be using it and we can't tell them `open the source code editor and manually add a style="float:right;"`.

**Comment by webketje** [comment]
For anyone still looking for a non-manual answer that at least doesn't mess up the `<LI>` item alignment with text-align:

**Disables alignment of lists/ list-items**
```
// reference to your editor, e.g. in setup config option
editor.on('execCommand', () => {
  const selection = this.editor.selection.getSelectedBlocks(),
        relevantCommands = /^Insert(Uno|O)rderedList|Justify.+$/;
    
    // don't add textAlign style to LI elements, they mess up lay-out
  if (relevantCommands.test(evt.command)) {
    selection
      .filter (element  => element.nodeName === 'LI')
      .forEach(listItem => {
          listItem.style.textAlign = '';
          listItem.removeAttribute('data-mce-style');
      });
  }
});
```

If you want to use floats, you'll have to add something like the following inside the `if` clause:

```
if (/^Justify.+$/.test(evt.command)) {
  selection
    .filter(element => /(U|O)L/.test(element.nodeName))
    .forEach(list => {
      list.style.cssFloat = evt.command.slice(7);  // 'Justify'.length
    });
}
```

**Comment by Shayan89** [comment]
Put below styles to list.css file

 ```
   .mce-content-body ol[align="center"],
    .mce-content-body ol li[align="center"],
    .mce-content-body ul[align="center"],
    .mce-content-body ul li[align="center"] {
        text-align: center;
    }
    .mce-content-body ol[align="left"],
    .mce-content-body ol li[align="left"],
    .mce-content-body ul[align="left"],
    .mce-content-body ul li[align="left"] {
        text-align: left;
    }
    .mce-content-body ol[align="right"],
    .mce-content-body ol li[align="right"],
    .mce-content-body ul[align="right"],
    .mce-content-body ul li[align="right"] {
        text-align: right;
    }
```

And then use it on tinymce.init() function

    ```
tinymce.init({
        selector: '#tinymce-textarea',
        content_css: ['list.css']
    });
```

**Comment by Shayan89** [comment]
Put below styles to list.css file

    ```
.mce-content-body ol[align="center"],
    .mce-content-body ol li[align="center"],
    .mce-content-body ul[align="center"],
    .mce-content-body ul li[align="center"] {
        text-align: center;
    }
    .mce-content-body ol[align="left"],
    .mce-content-body ol li[align="left"],
    .mce-content-body ul[align="left"],
    .mce-content-body ul li[align="left"] {
        text-align: left;
    }
    .mce-content-body ol[align="right"],
    .mce-content-body ol li[align="right"],
    .mce-content-body ul[align="right"],
    .mce-content-body ul li[align="right"] {
        text-align: right;
    }
```

And then use it on tinymce.init() function

    ```
tinymce.init({
        selector: '#tinymce-textarea',
        content_css: ['list.css']
    });
```

**Comment by Shayan89** [comment]
Put below styles to list.css file

    .mce-content-body ol[align="center"],
    .mce-content-body ol li[align="center"],
    .mce-content-body ul[align="center"],
    .mce-content-body ul li[align="center"] {
        text-align: center;
    }
    .mce-content-body ol[align="left"],
    .mce-content-body ol li[align="left"],
    .mce-content-body ul[align="left"],
    .mce-content-body ul li[align="left"] {
        text-align: left;
    }
    .mce-content-body ol[align="right"],
    .mce-content-body ol li[align="right"],
    .mce-content-body ul[align="right"],
    .mce-content-body ul li[align="right"] {
        text-align: right;
    }

And then use it on tinymce.init() function

    tinymce.init({
        selector: '#tinymce-textarea',
        content_css: ['list.css']
    });
