### ISSUE TITLE
Hitting backspace moves cursor position to start

### ISSUE THREAD

**Issue by krishna-babu** [tinymce/tinymce#3678]
Bug

Hitting backspace moves cursor position to start of the section

Introduced from 4.6
1. Goto inlite demo page of tinymce.
2. Hit enter key couple of times
3. Hit backspace twice and observe that the cursor moved to start of the section
4. Error log in console
![image](https://cloud.githubusercontent.com/assets/12712808/26379955/a020bc20-3fd0-11e7-874b-f2821ddbd40b.png)

**What is the expected behavior?**
On backspace the cursor should move to previous line

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Issue from 4.6
Encountered in Chrome

**Comment by fyrkant** [comment]
This has been fixed in 4.6.2 that was released yesterday, the problem with the demo page seems to be that the CDN version hasn't been updated to 4.6.2 yet. You can see that it works here: http://fiddle.tinymce.com/RQfaab
