### ISSUE TITLE
Change Event Not working in Tinymce 3.5.11 when viewing firefox

### ISSUE THREAD

**Issue by ssrgspdkt** [tinymce/tinymce#3680]
Change event working correctly in Chrome browser. But not working in firefox. 
Firefox version is 53.0.2
Please provide solution.

**Comment by alecpl** [comment]
Upgrade. Really.

**Comment by fyrkant** [comment]
Yeah I have to agree with @alecpl - if you can you really should upgrade to the latest version of TinyMCE.

**Comment by lnewson** [comment]
As mentioned above, we no longer support TinyMCE 3 sorry. At this time TinyMCE 5 is our supported version, however we're still fixing major issues identified in the latest version of TinyMCE 4. So it's our recommendation to upgrade to a new version if you're still having issues.
