### ISSUE TITLE
Special character descriptions overflow modal window

### ISSUE THREAD

**Issue by robtree** [tinymce/tinymce#3681]
Description of problem:

Long descriptions of special characters are not fully visible when hovering over boxes in the 'Special character' modal window.

Steps to reproduce:

1. https://www.tinymce.com/docs/demo/full-featured/
2. Open Insert > Special character
3. Mouse over the right-pointing angle bracket character (last on penultimate row)

Expected result:

The following text should be visible on the right of the modal window:

"right-pointing angle bracket"

Actual result:

Some of the text is not visible:

"right-pointing angle bra"

![overflow](https://cloud.githubusercontent.com/assets/3150192/26410066/29366a40-409a-11e7-9e25-bdcf4491c7f4.png)

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
