### ISSUE TITLE
Image with link causes javascript error

### ISSUE THREAD

**Issue by j-t-barrett** [tinymce/tinymce#3682]
**Bug report for version 4.6.2**

**Steps to reproduce**
Using http://fiddle.tinymce.com/ (I used version 4.6.2, though it seems to appear in others)
1. Insert an image into the editor
2. Select only that image and add a link
3. Attempt to click to the right of the image to keep adding content

**Expected**
Cursor will appear to the right of the image and typing will produce content here

**Actual**
- A javascript error is thrown: The given range isn't in document
- The cursor is taken back to the start of the editor

**Additional Notes**
 - Behaviour seems slightly different with different browsers, likely due to the difference in time it takes javascript to act. Though appears at some level in all browsers I've tested (Chrome, FF, IE, Edge)
- The image does not have to be the only thing in the editor for this to appear, it occurs whenever trying to click to begin editing directly after the image. This looks the worst when the image is in a paragraph of it's own

Let me know if you have any questions.

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
