### ISSUE TITLE
BUG: Tinymce on joomla: Menues not working / in top corner

### ISSUE THREAD

**Issue by iotexsystems** [tinymce/tinymce#3684]
*BUG-REPORT*

**What is the current behavior?**
![efwewe](https://cloud.githubusercontent.com/assets/28090494/26421348/0fc43a3e-40c6-11e7-95a7-163ce99951cf.JPG)
Menu not working - not clickable - nothing. Appers in top left corner. Joomla 3.7.2
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Clicking on "Formats" and "Paragraph" is making the menu appear, however it does not appear in the right place and is broken.

**What is the expected behavior?**
Appearing next to the Menu.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Reproduced with Opera 	45.0.2552.812 (PGO)
Newest Chrome
Edge
MCE Version: 4.5.6

**Comment by donShakespeare** [comment]
I have seen this before elsewhere.
What menu is that, custom?

**Comment by iotexsystems** [comment]
@donShakespeare Me too. I´m pretty sure I have seen this before...more then a year ago. Still I´m not getting the point. Deleted every non stock css. 
I resetted every setting to stock. It´s the "out of the box" TinyMCE with default menus etc.
Any idea?

**Comment by donShakespeare** [comment]
Yes. It has nothing to do with invading CSS.
It happens when you have a menu (that still shows) even when corresponding plugin is not set.

The menu becomes useless, and is attached to the wrong corner of the screen.
Once you re-attach appropriate plugin or core setting, then the menu resumes normal behaviour.

But I can't right now remember which plugin/core setting is responsible. I'll have to dig.

**Comment by donShakespeare** [comment]
Post your config, let's catch the rat!

**Comment by donShakespeare** [comment]
Okay. I replicated the issue. But it seems that `4.6.2` has generously covered that issue most excellently

https://www.tinymce.com/docs/changelog/#version462-may232017
>FIXED bug with format preview not working on invalid elements excluded by valid_elements.

In http://fiddle.tinymce.com/ use version 4.6.1 and below
```javascript
<script type="text/javascript">
tinymce.init({
   selector: "textarea",
   valid_elements : 'b'
  //the menu that produces elements (h1-h6) that have been excluded by valid_elements will hang and crash
});
</script>
<textarea name="content"></textarea>
```
Case closed! :)

**Comment by iotexsystems** [comment]
@donShakespeare U are awesome :)

**Comment by Afraithe** [comment]
Yes this was sorted out in the 4.6.2 release, thanks for investigating it @donShakespeare 

Closing ticket.
