### ISSUE TITLE
Bullet List and Number list is not visible without "advlist"

### ISSUE THREAD

**Issue by masihur** [tinymce/tinymce#3686]
Hi,
I included tinymce library from the source  "https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.6.2/tinymce.min.js" then "bullet list and number list" are not visible in the tool-bar.
Once I used "advlist" in the plug-in list then "bullet list and number list" are visible with drop-down options.

While If I included "https://cdn.tinymce.com/4/tinymce.min.js" file then "bullet list and number list" option are visible without using "advlist" plug-in.

Is both files are different?

If both file are different then which file is stable, and need to use on our project.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks
