### ISSUE TITLE
Bug: 4.6.2 Autolink not working properly

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3690]
1. Go to https://www.tinymce.com/ 
2. Copy a linked text "PowerPaste"
3. Insert from clipboard
4. Press space
5. Press backspace

Result:
Link have a get colored background and every new space not terminate link

**Comment by fyrkant** [comment]
Do you mean the inline boundary? You can just press right arrow to "get out of" the link, like this: 
![2017-05-31 16 12 32](https://cloud.githubusercontent.com/assets/8655649/26636134/17128e2a-461c-11e7-9b1d-3360763cae4a.gif)

**Comment by Daijobou** [comment]
My mistake, I have not explain it good enoug. Maybe I must first ask, is this a intended new feature in 4.6.x? Before version 4.6.x the link text stops always after step 5. So as step 6 I insert in version 4.5.5 (and before) as example a "," (comma) and link is stopped. In version 4.6.x not its still a link.

**Comment by fyrkant** [comment]
Yes it is intended behaviour, to move out of the link you press right arrow, the background color is removed and you can write outside of the `a` tag.
