### ISSUE TITLE
Media embed handler threw unknown error

### ISSUE THREAD

**Issue by staffsri** [tinymce/tinymce#3691]
I am using v4.5 versions of TinyMCE
i am uploaded video files into file manage but i am selecting video option to insert video When "Media embed handler threw unknown error" error is occurred 
screeshots below 

![1](https://cloud.githubusercontent.com/assets/28999463/26521097/acf5dcca-42fd-11e7-9e85-59f498d94237.png)
![2](https://cloud.githubusercontent.com/assets/28999463/26521096/acf3de48-42fd-11e7-94f4-9f7bf42bb2f4.png)
![3](https://cloud.githubusercontent.com/assets/28999463/26521098/acf7439e-42fd-11e7-884b-57245b75c208.png)
Please Give Solution for rectifying this Error.please respond as early as possible
Thank Q..

**Comment by fyrkant** [comment]
Hmm, must be some code in your media embed handler that is throwing an exception that gets caught in one of the catch blocks in Dialog.js, like this one: 
https://github.com/tinymce/tinymce/blob/master/src/plugins/media/src/main/js/ui/Dialog.js#L111

So you might have to look through the tiny code and remove the catched to see the errors thrown by the file manager... 😅
