### ISSUE TITLE
Strings missing from the master translation file

### ISSUE THREAD

**Issue by czirkoszoltan** [tinymce/tinymce#3693]
The following strings are missing from the list of strings to be translated:
- "Link list"
- "Class"
- "Template" (in singular)
I wanted to do the Hungarian translation, but the original strings (in English) are also missing. I also checked the German and French translation, for example, and those are also missing the strings. However, they are used in the code:
- "Link list", ./js/tinymce/plugins/link/plugin.js:328
- "Class", various plugins
- "Template", ./js/tinymce/plugins/template/plugin.js:123

**Comment by Laurent3170** [comment]
Let me know when it's solved to be able to add french translations

**Comment by lnewson** [comment]
Hi,

Thanks for reporting these and looking at both the TinyMCE 4 and 5 translations, these are now included. As such I'll go ahead and close this, but please do let us know if you're still experiencing issues and we'll reopen this.

Thanks!
