### ISSUE TITLE
Resize events are never fired

### ISSUE THREAD

**Issue by pribilinskiy** [tinymce/tinymce#3694]
https://www.tinymce.com/docs/api/tinymce.ui/tinymce.ui.resizehandle/

Documentation says that resize handle should fire `ResizeStart`, `Resize` and `ResizeEnd` events. But it doesn't happen.

The `ObjectResizeStart` event on the contrary is triggered successfully

Example:

```
init_instance_callback(editor) {

	const resizehandleEl = $(editor.editorContainer).find('.mce-resizehandle');
	const statusbarEl = $(editor.editorContainer).find('.mce-statusbar');

	resizehandleEl.on('resize', () => console.log('resize fired on resize handle'));
	statusbarEl.on('resize', () => console.log('resize fired on statusbar'));
	editor.on('resize', () => console.log('resize fired on editor'));
)
```

Nothing is logged to console

**Comment by pribilinskiy** [comment]
I've found, by reading the sources (duh), that I can get to a control instance through `controlIdLookup` object under `editor.theme.panel`. So, here's a cumbersome solution to handle events that was triggered directly on a control without propagation.

```
init_instance_callback(editor) {

	const resizehandleId = $(editor.editorContainer).find('.mce-resizehandle').attr('id');
	const resizehandle = editor.theme.panel.controlIdLookup[resizehandleId];

	resizehandle.on('resize', () => console.log('resize fired on resize handle'));
)
```

**Comment by spocke** [comment]
We don't use jquery so use the editor.on function to bind event handlers. More details here: https://www.tinymce.com/docs/advanced/events/#editorevents

**Comment by pribilinskiy** [comment]
@spocke why closed? You don't have to use jquery. This issue is not fixed. `editor.on` doesn't receive the mentioned events

**Comment by pribilinskiy** [comment]
I get it, a fiddle is required, here you go http://fiddle.tinymce.com/gRfaab/3
Please re-open this issue
