### ISSUE TITLE
Autoresize has wrong height at start

### ISSUE THREAD

**Issue by FabriceGaudin** [tinymce/tinymce#3699]
Reporting a bug

**What is the current behavior?**
Following previous issue https://github.com/tinymce/tinymce/issues/1947, I still reproduce this bug, on Firefox or Chrome.
> With plugin "autoresize" the editor starts in wrong dimensions.

> Remove plugin "autoresize" fix this problem, but now the cool feature autoresize is missing. :D

I find it easier to see the "jump" with several lines in Tinymce Editor so I made a new fiddle, but the one from the previous ticket also shows this jump.
*Fiddle:* http://fiddle.tinymce.com/9zeaab/2

**What is the expected behavior?**
The editor should be initialized with correct height at start, to avoid the jump of elements under it (and an annoying useless scrollbar).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This bug is not new to TinyMCE and reported in Chrome, Firefox and Internet Explorer.
I reproduced it on Ubuntu 16.04 but apparently, it's not linked to this OS

**Comment by donShakespeare** [comment]
It is not clear what you mean by jumping.

>The editor should be initialized with correct height at start, to avoid the jump of elements under it (and an annoying useless scrollbar).

Questions for you ...
 ...Is the scrollbar present the whole time or does it flicker off?
 ...What initial height are you expecting?
 ... are you referring to `autoresize_on_init: false`

Upon observing the plugin in question, I saw all sorts of paddings and margins and offsets that the plugin uses to achieve its final goal. This is what I think might be disturbing your flow.

The solution would be to rewrite the plugin (I am sure there might even be better ways to achieve what it does now) or simply take control of the paddings via `content_css`

Here is my test.
Please note how the original textareas have a defined height (TinyMCE will inherit that).
```javascript
<script type="text/javascript">
tinymce.init({
    selector: "#one",
    toolbar: false,
    menubar: false,
    statusbar: false,
    plugins: "code",
    content_style: "body{margin:0!important;padding:0 10px!important;}",
    setup: function(editor) {
        editor.on("dblclick", function() {
            $("#bOne").html( $(editor.getContainer()).height());
			editor.focus()
        });
    }
});
tinymce.init({
    selector: "#two",
    toolbar: false,
    menubar: false,
    statusbar: false,
    plugins: "autoresize code",
    autoresize_min_height: 200,
    //autoresize_max_height: 200, //200 creates a perfect box as if there were no autoresize
    //autoresize_bottom_margin: false,
    autoresize_on_init: false, //does not work as expected.... ?? :(
    autoresize_overflow_padding: 0,
    content_style: "body{margin:0!important;padding:0 10px!important;}",
    setup: function(editor) {
        editor.on("dblclick", function() {
            $("#bTwo").html( $(editor.getContainer()).height());
			editor.focus()
        });
    }
});
</script>
<textarea id=one  style=height:200px><p>1 - dblclick to get height</p><p>2</p><p>3</p><p>4</p><p>5</p><p>6</p><p>7</p></textarea>
<div>height of above editor: <button id=bOne> ...</button></div>
<textarea id=two  style=height:200px><p>1 - dblclick to get height of autresize</p><p>2</p><p>3</p><p>4</p><p>5</p><p>6</p><p>7</p></textarea>
<div><div>height of autoresize editor: <button id=bTwo>...</button></div>
```

If it ends up that `autoresize_on_init: false` is your issue, there is a workaround to that.
I hope I have not completely misunderstood you.

**Comment by FabriceGaudin** [comment]
@donShakespeare Thank you for your response and sorry for the imprecisions
- the unwanted scrollbar isn't present the whole time, just on initialization
- I expect the initial height to be the same height than after autoresize
- I'm not referring to `autoresize_on_init` as I do want my editor to be autoresized. However I'd like he was autoresized before showing with its default height, which is causing the kind of jump I try to describe.

My problem is during one second on init, I can see:
![capture d ecran de 2017-06-01 18-18-16](https://cloud.githubusercontent.com/assets/14922065/26689696/d28895b6-46f6-11e7-8877-1c7dad4cea64.png)
then:
![capture d ecran de 2017-06-01 18-18-35](https://cloud.githubusercontent.com/assets/14922065/26689703/d7e00850-46f6-11e7-9313-f2128405c74c.png)
and finally:
![capture d ecran de 2017-06-01 18-18-55](https://cloud.githubusercontent.com/assets/14922065/26689711/de393d0c-46f6-11e7-8640-8356fa7dabd2.png)

And I was wondering if it was possible to make the auto-resize smoother. At least avoid this first screen shot, which can be really disturbing in the middle of a page.
I can also reproduce this problem with your code above.
The visual bug is quick and you may need to throttle your network to reproduce it.
I hope my problem is understandable with these screen shots, tell me if you need any other details.

**Comment by jcudzich** [comment]
@donShakespeare @FabriceGaudin 

I have the same issue.
Above screenshots exactly show the problem.

**Comment by plejus** [comment]
same here:

![image](https://user-images.githubusercontent.com/16239639/32225587-01bb062c-be46-11e7-9220-d2497fe13f5d.png)

when I click on the editor it resizes properly. Problem only occurs where tinymce is in hidden tab initially

**Comment by Alamei** [comment]
I'm seeing this exact same behavior of autoresize causing the page to jump around during the initialization process. Has anyone come up with a viable workaround to utilize until a real solution becomes available?

**Comment by plejus** [comment]
@Alamei I triggering tinymce:autoresize command on "shown.bs.tab" event (I use bootstrap) with small timeout (for example 300). It is not perfect but its working

**Comment by FabriceGaudin** [comment]
@Alamei I didn't find any workaround. I still have the problem on initialization.

**Comment by fvonellerts** [comment]
In case you are using the foundation tabs, this workaround worked for me:
```
$('[data-tabs]').on('change.zf.tabs', function() {
   $(this).find('.mce-tinymce').trigger('tinymce:autoresize')
})
```
The code for bootstrap should be similar.

**Comment by crismx** [comment]
Hi guys! Here's my workaround on the version 4.8.3.
Somehow on the internet explorer (IE11), the body inside the iframe has min-height set on it.
All I had to do is set it to auto during the initialisation.

`
oninit: function() {
              // workaround for Internet Explorer autoresize bug
               if (config.autoresize_min_height && this.isIE) {
                        $($el.tinymce().iframeElement).contents().find("body").css("min-height", "auto")
               }
}
`

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
