### ISSUE TITLE
Customize Shortcuts in Help Plugin (Feature Request)

### ISSUE THREAD

**Issue by jmanos** [tinymce/tinymce#3703]
Hello,

The list of shortcuts listed by the Help plugin's dialog is currently hard-coded (version 4.6.3).

However, it would be extremely helpful to be able to:
- modify which shortcuts are displayed in the help window (in case certain plugins are not enabled or shortcuts have been added/removed)
- change the displayed text of the shortcuts (e.g., to get rid of the ugly "if [plugin] activated" text)
- have an event triggered when the help dialogue finishes displaying (can this already be done?)

Thank you.

**Comment by Afraithe** [comment]
Good feedback, we will see if we can improve this, take out more info from the plugins and allow for custom URLs.

Why would you want an event when the dialog finish displaying?

**Comment by jmanos** [comment]
The event would be used as a workaround to further edit the dialog if the customization options from TinyMCE are not as robust as needed for a specific project. For example, if someone wants to add an extra tab to the help screen on the fly.

I understand, though, that the event is not entirely necessary.

**Comment by fyrkant** [comment]
This is fixed in the latest release, see this page in the docs: https://www.tinymce.com/docs/plugins/help/#exposingmetadataforthehelpplugin
