### ISSUE TITLE
Resize events are never fired

### ISSUE THREAD

**Issue by pribilinskiy** [tinymce/tinymce#3704]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
[Documentation says](https://www.tinymce.com/docs/api/tinymce.ui/tinymce.ui.resizehandle/
) that resize handle should fire `ResizeStart`, `Resize` and `ResizeEnd` events. But it doesn't happen.

The `ObjectResizeStart` event on the contrary is triggered successfully

**Example**
```
init_instance_callback(editor) {

	const resizehandleEl = $(editor.editorContainer).find('.mce-resizehandle');
	const statusbarEl = $(editor.editorContainer).find('.mce-statusbar');

	resizehandleEl.on('resize', () => console.log('resize fired on resize handle'));
	statusbarEl.on('resize', () => console.log('resize fired on statusbar'));
	editor.on('resize', () => console.log('resize fired on editor'));
)
```

Nothing is logged to the console.

Fiddle: http://fiddle.tinymce.com/gRfaab/3

**What is the expected behavior?**

Event should be propagated to the `editor`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.6.1, Windows 10, Chrome latest
Just discovered

**Comment by spocke** [comment]
Use this:
editor.on('ResizeEditor', function (e) {
console.log(e);
});

If I get this bug report correctly. We haven't documented all events on the site yet.

**Comment by pribilinskiy** [comment]
@spocke thanks though I need `ResizeStart` and `ResizeEnd` events specifically.

Already tried `ResizeStartEditor`, `ResizeEditorStart`, `ResizeBeginEditor`, `ResizeEditorBegin` with no luck.

**Comment by Daijobou** [comment]
@spocke 
How do I know if the event "ResizeEditor" was called by drag "tox-statusbar__resize-handle" (resizer: right corner) and not by code?
