### ISSUE TITLE
a is undefined

### ISSUE THREAD

**Issue by mtm81** [tinymce/tinymce#3707]
Current release on //cloud.tinymce.com/stable/tinymce.min.js
on all previously working sites is now displaying an:
a is undefined error on init()
line: 32:1970

tested across several sites using same setup.  Tested across all range of browsers.
All with same result

**Comment by spocke** [comment]
We are not seeing that issue on our end. Could you send us a tinymce.init that you are using or setup a fiddle.tinymce.com it has the cloud versions. Thanks

**Comment by mtm81** [comment]
ok just done some more testing.It would appear the "stable" version on the cloud is Version: 4.6.2-58.
This is doing the behavious described.
If I download a local copy of the latest js for tinymce and run that instead (it's Version 4.6.3)
It works without issue.
It would appear that the 'current' cloud stable version isnt the same as the current download version and it's the cloud version at issue.

I can see on your main site that you are using the cloud version without issue so I'm not sure why it's not working for my sites and is ok on your main site?  (same domain perhaps?)

**Comment by navalpatel5** [comment]
I am receiving the same error after the new version of cloud tinymce.min.js is released

my tinymce.init is
tinymce.init({selector:'textarea', forced_root_block: 'div'});

The result is same if tinymce.init is
tinymce.init({selector:'textarea'});

**Comment by mtm81** [comment]
[cloudversion.txt](https://github.com/tinymce/tinymce/files/1040798/cloudversion.txt)
[downloadversion.txt](https://github.com/tinymce/tinymce/files/1040797/downloadversion.txt)

**Comment by Kirkhammetz** [comment]
I'm getting the same error with the stable cloud, everything ok with the npm version

**Comment by spocke** [comment]
Ok we managed to figure out whats going on. This happens only on the cloud version and only if there is no plugins configured for the editor. We will address this issue in the cloud version today.

**Comment by fyrkant** [comment]
A new version should be out on the cloud ☁️  now that fixes the problem so I am closing this issue. 

If its still not working for you, leave a comment and we can open it up again.

**Comment by navalpatel5** [comment]
Hey guys,

I am surprised why i am getting this error still on my page. However before writing back to you guys, i tried it on Jsfiddle (https://jsfiddle.net/xtc667xj/) and it appears to be perfectly good with the same code.

This is the stack on crash
TypeError: a is undefined[Learn More]  tinymce.min.js:32:1970
	f https://cloud.tinymce.com/stable/tinymce.min.js:32:1970
	g/< https://cloud.tinymce.com/stable/tinymce.min.js:32:2074
	b/< https://cloud.tinymce.com/stable/tinymce.min.js:32:899
	<anonymous> http://localhost:3000/javascripts/notification.js:12:5
	j https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:27239
	fireWith https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:28057
	ready https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:29889
	J https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:30255

**Comment by mtm81** [comment]
perhaps it's a cache issue?  I had to force a re-download in my local browser to get it get the latest version from the stable url?

**Comment by fyrkant** [comment]
@navalpatel5 Like @mtm81 says it is probably a cache issue, so try to clean you cache and check the file what version you are getting, it should say `Version: 4.6.3-59`.

**Comment by navalpatel5** [comment]
Yeah it seems so, it worked late last night for me after I tried it out from incognito mode... thanks :)
