### ISSUE TITLE
"Open link" in the language packs

### ISSUE THREAD

**Issue by edojdikov** [tinymce/tinymce#3712]
There is no phrase "Open link" in the language packs of plugin "link", when calling the context menu.

Version 4.6.3

**Comment by lnewson** [comment]
This is still an issue unfortunately and while this is the older issue, I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/4444 just because it has more comments and details. We'll try and ensure this is added to transifex in the next update.
