### ISSUE TITLE
strange behaviour with empty span element

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#3721]
*bug*?**

```
<p><span class="glyphicon"></span></p>
<p><span class="fa"></span></p>
```
Why is the 1st empty span elmt left there while the 2nd empty span is removed?
https://codepen.io/manu37/pen/awOgEO (inspect source code).

**Comment by cmb69** [comment]
The first `<span>` has a `ZERO WIDTH SPACE` character as content, while the second `<span>` is actually empty. Empty `<span>`s shouldn't be removed, but this is already tracked by #3175.

**Comment by manu37** [comment]
oh shame on me. You're right, my bad eyes.
