### ISSUE TITLE
Backspace is not working before a noneditable element

### ISSUE THREAD

**Issue by Antontelesh** [tinymce/tinymce#3728]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Currently pressing backspace before a noneditable element does nothing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Demo is here: http://fiddle.tinymce.com/fSfaab

Steps to reproduce:
1. Type anything in an editor, for example "some content here"
2. Click on "Add noneditable" button, it will insert a noneditable element at caret position
3. Press left arrow key twice to move caret before the just inserted noneditable element
4. Press Backspace key to remove the last character that you've typed on step 1.
5. Verify that Backspace does not work

**What is the expected behavior?**

Backspace is expected to work properly

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Edge version. Did not tested on other versions.

**Comment by systemx-xx** [comment]
#3559 Duplicate

**Comment by OlivierJaquemet** [comment]
@spocke :
This bug can be reproduce (using the fiddler above) on version 4.6.7.
However it does not occur when using 4.7.5 or above.

I think it can be closed. Can you confirm this @Antontelesh ?

**Comment by Antontelesh** [comment]
Yes, I completely forgot about this issue opened. I’m closing it as it’s fixed.
