### ISSUE TITLE
Have the disable the editor's shortcuts API?

### ISSUE THREAD

**Issue by MrLiufei** [tinymce/tinymce#3729]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by fyrkant** [comment]
We need more information and maybe a fiddle showing the issue to be able to help.

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
