### ISSUE TITLE
Search Plugin cannot find consecutive spaces

### ISSUE THREAD

**Issue by yecril71pl** [tinymce/tinymce#3731]
**Do you want to request a *feature* or report a *bug*?**
a *bug*
**What is the current behavior?**
Search Plugin cannot find consecutive spaces
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/iSfaab

1.  Enter the following text into the edit area (LATIN LOWERCASE LETTER A, SPACE, SPACE, LATIN LOWERCASE LETTER B):

        a  b
1. Press `[Ctrl[F]]` in the editor
1.  Search for (LATIN LOWERCASE LETTER A, SPACE, SPACE):

        a  

**What is the expected behavior?**
Search Plugin should find the text at the beginning of the document.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE Version: edge
browser: Microsoft Edge 40.15063.0.0
OS Name:	Microsoft Windows 10 Pro
Version:	10.0.15063 Build 15063

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
