### ISSUE TITLE
Regression: Lines overlaps when they have different font-size after commit 73c077b6be41d355ed9ee346710c05fce2e13ec9

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3733]
After commit 73c077b6be41d355ed9ee346710c05fce2e13ec9 lines are overlapping other lines because of the new hardcoded line-height, which also breaks line selection. @spocke I could not find much information why that change was needed in the commit message

steps to repro:
Using the latest version of tinymce (I used the edge in fiddle.tinymce.com), call the setContent api with text having multiple lines, like:
`tinymce.activeEditor.setContent('<div><span style="font-family: \'Calibri\'; font-size: 48pt; font-weight: bold;">Text zone - Calibri, 48pt, bold,</span></div><div><span style="font-family: \'Calibri\'; font-size: 72pt; font-weight: bold;">New Line 72pt</span></div>')`

Below the image with the actual result
![screen shot 2017-06-09 at 3 55 56 pm](https://user-images.githubusercontent.com/2013754/26997163-4370cc5e-4d2c-11e7-8682-0e894adf85b8.png)

going to dev tools, and unmarking the `line-height: 1.2em` makes the text look right.

Additionally, this is reproducible when you type text with 2 lines in the editor and change the second line to some high value, like 72

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by thiagolacerda** [comment]
Thanks for such a fast fix!
