### ISSUE TITLE
bug: visual_table_class with more than one class dont set class at all

### ISSUE THREAD

**Issue by bes-internal** [tinymce/tinymce#3742]
In 4.5.7 set of visual_table_class: 'prod prod--default prod--editor' cause table with this class. In 4.6 branch set more than one style cause table without class at all.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by bes-internal** [comment]
http://fiddle.tinymce.com/ASfaab
Insert new table.
Show code.
All visual_table_class must be in table tag.
Check v4.5.7 vs 4.6.4

**Comment by bes-internal** [comment]
In new versions default border=1 attribute added so visual_table_class does not apply.
NOTABUG. Close
