### ISSUE TITLE
tinyMCE 4 > plugin image / link > image_class_list / link_class_list select wrong height

### ISSUE THREAD

**Issue by seltix5** [tinymce/tinymce#3746]
Hi,

Using the setting "image_class_list" :

`settings.image_class_list = [
    {title: '', value: ''},
    {title: 'Responsive', value: 'img-fluid'}
];`

the select, when starting with the first option (without title) it has a wrong height :

http://i.imgur.com/zeVxBze.jpg

thank you

**Comment by fyrkant** [comment]
Because you have an item with an empty title it makes the select input render weirdly, so just add a title to the first one too, something like `{title: "None", value: ""}` and it should look ok.

**Comment by seltix5** [comment]
hi,
Yes if i write some title it is ok, but as every other input is blank by default it is not great to have some text there just to render correctly.
Plus, this text is not a translation so its better to avoid, no?
thank you.
