### ISSUE TITLE
4.6.4 regression - settings is undefined

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#3747]
I experience a regression with version 4.6.4. I tried with version 4.6.3 and it works fine.

The bug occurs when loading TinyMCE using Ajax with a Ajax success handler that does:
```javascript
tinymce.execCommand('mceAddEditor', false, 'Message');
```
My web developer console prints "TypeError: settings is undefined - tinymce.js:38302:11".

This corresponds to:
https://github.com/tinymce/tinymce/blob/master/src/core/src/main/js/EditorSettings.js#L68

So the regression is _possibly_ introduced by the refactoring in the commit d8892f2c808b62ddceede32ca8a3ac8960dc9ade by @spocke on June 2.

**Comment by fyrkant** [comment]
Can you show some more code or even better reproduce it in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by vanillajonathan** [comment]
Here is a fiddle.
http://fiddle.tinymce.com/aTfaab

**Comment by fyrkant** [comment]
Thank you!

**Comment by vanillajonathan** [comment]
This issue is still open, but trying with version 4.6.5 in the fiddle it seems to now work.
It seems this bug has been fixed. I don't know which commit fixed this bug.

The changelog mentions "fixed bug where some legacy editor initialization logic would throw exceptions about editor settings not being defined." which might be what fixed this.

I am clueless to what "legacy editor initialization logic" refers though, and what the modern equivalent would be.
