### ISSUE TITLE
Issue when set properties for rows table

### ISSUE THREAD

**Issue by hungcrush** [tinymce/tinymce#3756]
I have an issue when set background for rows on table. First I set center for they, then I set background. When done => Style of these rows has lost center style.

Please see gif image:

![apztbhsb5a](https://user-images.githubusercontent.com/8098916/27321031-f92b1088-55c2-11e7-8796-4b2e6da0dde7.gif)

**Comment by tinydylan** [comment]
Hi,

I tested this out on this [demo page](https://www.tiny.cloud/docs/demo/full-featured/) and I cannot reproduce the issue. It looks like this has been corrected.

Thanks!
