### ISSUE TITLE
Chrome: Styles are not carried to new paragraph when initially focusing on empty paragraph

### ISSUE THREAD

**Issue by jerryorr** [tinymce/tinymce#3758]
Given a simple target like this:

```
<textarea style="border: thin solid black">
  <p></p>
</textarea>
```

 1. Click directly where the cursor will end up (bug doesn't occur if you click somewhere in the middle of the editor and the cursor ends up in the beginning) 
 2. Add some styles (like bold or italic)
 3. Type some characters
 4. Hit enter
 5. Type some more characters

The second paragraph will not have the styles selected in the first line.

I've only reproduced this in Chrome thus far.

Sample code: https://codepen.io/anon/pen/zzzvEO

Demo:
![tinymce bug](https://user-images.githubusercontent.com/1598167/27401482-5a9c3756-5691-11e7-87a7-63aa16da6a15.gif)

**Comment by fyrkant** [comment]
Simplified fiddle:
http://fiddle.tinymce.com/0Tfaab

I can reproduce it on all browsers but firefox.

**Comment by Afraithe** [comment]
Can't replicate this any more in chrome.
