### ISSUE TITLE
Unlinking a substring ending in a space does not unlink the space

### ISSUE THREAD

**Issue by mcavalletto** [tinymce/tinymce#3761]
To reproduce, in a TinyMCE editor running 4.6 (in multiple browsers; also seen in 4.3):
- Select a phrase containing several words separated by spaces, and apply a link to it.
- Highlight one or more words within the link, and the space after it, while leaving the words at the end of the link unselected.
- Click the "unlink" button.

Doing this in TinyMCE 4.3 and 4.6 leaves the trailing space character as part of the link, even though it was selected when you clicked the unlink button.

For example, using underscores to represent the start and end of a link, if you had an editor that contained "_two words_", and you selected the word "two " including the trailing space, and clicked the unlink button, you'd end up with "two_ words_" — the word "two" would be unlinked, but the space between the words would remain part part of the link.

I would expect that all of the characters that were selected when I clicked the unlink button would become unlinked.

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
