### ISSUE TITLE
External plugins loaded only in the last instance of tinymce on v 4.6.x

### ISSUE THREAD

**Issue by TomTheRock** [tinymce/tinymce#3764]
If i use several instances of the tinymce editor and use a external plugin (filemanager), only on the last instance the filemanager is loaded, not in the instances before...

The last knowed release ist 4.5.7

Here my testpages also many other have this problem:

Other users:
https://github.com/trippo/ResponsiveFilemanager/issues/357
http://www.responsivefilemanager.com/support.php#comment-3381883831

Testpages:
http://www.des-solutions.de/entwicklung/_scripts/tinymce/tinymce_multiple_instances.html (v 4.6.4) *notworking*
http://www.des-solutions.de/entwicklung/_scripts/tinymce_4.5.7/tinymce_multiple_instances.html *working*
Build a fix from pjayramkumar commented on 20 Jul: (v.4.6.5 newest tinymce)
http://www.des-solutions.de/entwicklung/_scripts/tinymce/tinymce_multiple_instances_fix.html 
(the function which used is used from ResponsiveFilemanager/filemanager/plugin.min.js)

Best regards
Tom

**Comment by perezdans** [comment]
Same problem

**Comment by cultrix** [comment]
Same problem, reverted back to 4.5.7.

**Comment by ShaunWilders** [comment]
Same problem, reverted back to 4.5.7.

**Comment by pjayramkumar** [comment]
Here is custom code that you can solve this issue

Add this line to setting of the tinyMCE init options
```
settings.file_browser_callback = function(fieldName, url, objectType, w) {
               filemanager(fieldName, url, objectType, w);
 };
```
```

function copy from filemanager

function filemanager(id, value, type, win) {
        editor=tinymce.activeEditor;
        // DEFAULT AS FILE
        urltype=2;
        if (type=='image') { urltype=1; }
        if (type=='media') { urltype=3; }
        var title="RESPONSIVE FileManager";
        if (typeof editor.settings.filemanager_title !== "undefined" && editor.settings.filemanager_title) {
            title=editor.settings.filemanager_title;
        }
        var akey="key";
        if (typeof editor.settings.filemanager_access_key !== "undefined" && editor.settings.filemanager_access_key) {
            akey=editor.settings.filemanager_access_key;
        }
        var sort_by="";
        if (typeof editor.settings.filemanager_sort_by !== "undefined" && editor.settings.filemanager_sort_by) {
            sort_by="&sort_by="+editor.settings.filemanager_sort_by;
        }
        var descending="false";
        if (typeof editor.settings.filemanager_descending !== "undefined" && editor.settings.filemanager_descending) {
            descending=editor.settings.filemanager_descending;
        }
        var fldr="";
        if (typeof editor.settings.filemanager_subfolder !== "undefined" && editor.settings.filemanager_subfolder) {
            fldr="&fldr="+editor.settings.filemanager_subfolder;
        }
        var crossdomain="";
        if (typeof editor.settings.filemanager_crossdomain !== "undefined" && editor.settings.filemanager_crossdomain) {
            crossdomain="&crossdomain=1";

            // Add handler for a message from ResponsiveFilemanager
            if(window.addEventListener){
                window.addEventListener('message', filemanager_onMessage, false);
            } else {
                window.attachEvent('onmessage', filemanager_onMessage);
            }
        }

        tinymce.activeEditor.windowManager.open({
            title: title,
            file: editor.settings.external_filemanager_path+'?type='+urltype+'&descending='+descending+sort_by+fldr+crossdomain+'&lang='+editor.settings.language+'&akey='+akey,
            width: 860,  
            height: 570,
            resizable: true,
            maximizable: true,
            inline: 1
            }, {
            setUrl: function (url) {
                var fieldElm = win.document.getElementById(id);
              
                url = editor.convertURL(url);

                var static_url = use_static_urls_in_catalog;

                if(static_url){
                    fieldElm.value = url;
                }else{
                    /* check if this is a local url */
                    var base_host = win.location.protocol + '//' + win.location.host;
                    var fnd = url.indexOf("media/wysiwyg");

                    if(url.indexOf(base_host) == 0 && fnd != -1){
                        fieldElm.value = "{{media url='" + url.substr(fnd + 6) + "'}}";
                    }else{
                        fieldElm.value = url;
                    }
                }
              
                if ("fireEvent" in fieldElm) {
                    fieldElm.fireEvent("onchange")
                } else {
                    var evt = document.createEvent("HTMLEvents");
                    evt.initEvent("change", false, true);
                    fieldElm.dispatchEvent(evt);
                }
```
            }
        });
    }

**Comment by joseMontes87** [comment]
Hello good afternoon
I have the same problem.

Add lines:
`settings.file_browser_callback = function(fieldName, url, objectType, w) {
               filemanager(fieldName, url, objectType, w);
 };`

Now I see the attachment button but it does not work.
I'm in the last version

**Comment by TomTheRock** [comment]
Build a fix from 

> pjayramkumar commented on 20 Jul

: (v.4.6.5 newest tinymce) with ResponsiveFilemanager
http://www.des-solutions.de/entwicklung/_scripts/tinymce/tinymce_multiple_instances_fix.html 
(the function which used is from ResponsiveFilemanager/filemanager/plugin.min.js, i only match the objects given by the function filemanager(field_name, func_value, type, win) )

**This solutions is only a workaround**, because if your external filemanager changes/updates and the call function / plugin.min.js CALL is also updated/extended you have to update your function also... ==>filemanager(field_name, func_value, type, win)

**Comment by pjayramkumar** [comment]
@joseMontes87 
try to check console log and detect the error and let me know

**Comment by lixuss** [comment]
Oh my brain gets serious damage after several hours of this bug, 
but @TomTheRock example works for my responsivefilemanager instance too. Thanks man!

**Comment by joseMontes87** [comment]
Hi good morning

My error persisting

Console error:
`Uncaught ReferenceError: filemanager is not defined
    at file_browser_callback ((index):49)
    at b.c (tinymce.min.js:15)
    at b.e [as fire] (tinymce.min.js:10)
    at b.fire (tinymce.min.js:10)
    at b.<anonymous> (tinymce.min.js:14)
    at b.e [as fire] (tinymce.min.js:10)
    at b.fire (tinymce.min.js:10)
    at HTMLDivElement.b (tinymce.min.js:10)
    at a (tinymce.min.js:2)
    at HTMLDivElement.p (tinymce.min.js:2)`

Call to plugin:

`  		tinymce.init({ 
			selector:'textarea', 
            plugins: [
		            "autolink lists link image charmap preview hr anchor pagebreak",
                    "searchreplace wordcount visualblocks visualchars code fullscreen",
                    "insertdatetime media nonbreaking save table directionality",
                    "template paste textcolor"
            ],
            visualblocks_default_state: true,
            verify_html: false,
            menubar: true,
            menu: {
                file: {title: 'File', items: 'newdocument'},
                edit: {title: 'Edit', items: 'undo redo | cut copy paste pastetext | selectall | searchreplace'},
                insert: {title: 'Insert', items: 'image media responsivefilemanager link | hr charmap insertdatetime | template'},
                view: {title: 'View', items: 'visualchars visualblocks visualaid | fullscreen | code'},
                format: {title: 'Format', items: 'bold italic underline strikethrough superscript subscript | removeformat'},
                table: {title: 'Table', items: 'inserttable tableprops deletetable cell row column'}
            },
            force_br_newlines: false,
            force_p_newlines: false,
            forced_root_block: false,
            extended_valid_elements : "iframe[src|frameborder|style|scrolling|class|width|height|name|align],br",
            toolbar1: "newdocument | undo redo | cut copy paste | searchreplace | visualchars visualblocks | fullscreen | code",
            toolbar2: "formatselect | bold italic | forecolor backcolor | alignleft aligncenter alignright alignjustify | removeformat | bullist numlist | link unlink |",
            toolbar3: "hr | image media responsivefilemanager | template | table preview | outdent indent | sizeselect |  fontsizeselect",
            fontsize_formats: "8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 17pt 18pt 19pt 20pt 21pt 22pt 23pt 24pt 25pt 26pt 27pt 28pt 29pt 30pt 31pt 32pt 33pt 34pt 35pt 36pt",
		    
		    external_filemanager_path:"/filemanager/",
	        
	        filemanager_title:"Probando",
	        
	        external_plugins: { "filemanager" : "filemanager/plugin.min.js"},
	        
			file_browser_callback: function(field_name, func_value, type, win) { 
				filemanager(field_name, func_value, type, win);
			}	
  		});`

**Comment by TomTheRock** [comment]
@joseMontes87:

Where is the code of the "filemanager(field_name, func_value, type, win);"

You need a function which handles the filemanager to open it....and so on

**Comment by joseMontes87** [comment]
@TomTheRock 
I thought that was driving him : filemanager/plugin.min.js

But because in one of the textarea works if I do not have that function?

What should I add?

**Comment by TomTheRock** [comment]
Uncaught ReferenceError: filemanager is not defined at file_browser_callback ((index):49) at b.c 
That means that the function  "filemanager(field_name, func_value, type, win);" does not exists.

Look at my example page you have to create your own function which handles the Filemanager (window open eg.)

Line: 37-80
http://www.des-solutions.de/entwicklung/_scripts/tinymce/tinymce_multiple_instances_fix.html

**Comment by joseMontes87** [comment]
Excellent Thank you, now it works!

**Comment by kevinfilteau** [comment]
The way I found to do it for me is to init the editor only when I click the textarea.

```
$("textarea.wysiwyg").on("click", function () {
    tinyMCE.remove(); // remove all.
    $(this).tinymce(); // activate clicked one.
});
```

**Comment by nyroDev** [comment]
As far as I can see, there is a simpler solution to fix this Responsieve File manager.  
And maybe it's not a tinyMce issue...

If you edit the responsivefilemanager plugin to add the following:
`e.settings.file_browser_callback = t;`
in the function callback at the begeinning
it works for all instanciated editors.

**Comment by TomTheRock** [comment]
Hi nyroDev,

thankyou for your fix, but how you edit the plugin...my changes have no affect:
Orginal-Plugin:
`tinymce.PluginManager.add("responsivefilemanager", function(e) {
		
		e.settings.file_browser_callback = t;
		
    function n(t) {
				
        0 === e.settings.external_filemanager_path.toLowerCase().indexOf(t.origin.toLowerCase()) && "responsivefilemanager" === t.data.sender && (tinymce.activeEditor.insertContent(t.data.html), tinymce.activeEditor.windowManager.close(), window.removeEventListener ? window.removeEventListener("message", n, !1) : window.detachEvent("onmessage", n))
    
		}

    function t() {
				
        var t = window.innerWidth - 20,
            i = window.innerHeight - 40;
        if (t > 1800 && (t = 1800), i > 1200 && (i = 1200), t > 600) {
            var a = (t - 20) % 138;
            t = t - a + 10
        }
        e.focus(!0);
        var s = "RESPONSIVE FileManager";
        "undefined" != typeof e.settings.filemanager_title && e.settings.filemanager_title && (s = e.settings.filemanager_title);
        var r = "key";
        "undefined" != typeof e.settings.filemanager_access_key && e.settings.filemanager_access_key && (r = e.settings.filemanager_access_key);
        var o = "";
        "undefined" != typeof e.settings.filemanager_sort_by && e.settings.filemanager_sort_by && (o = "&sort_by=" + e.settings.filemanager_sort_by);
        var g = "false";
        "undefined" != typeof e.settings.filemanager_descending && e.settings.filemanager_descending && (g = e.settings.filemanager_descending);
        var d = "";
        "undefined" != typeof e.settings.filemanager_subfolder && e.settings.filemanager_subfolder && (d = "&fldr=" + e.settings.filemanager_subfolder);
        var l = "";
        "undefined" != typeof e.settings.filemanager_crossdomain && e.settings.filemanager_crossdomain && (l = "&crossdomain=1", window.addEventListener ? window.addEventListener("message", n, !1) : window.attachEvent("onmessage", n)), win = e.windowManager.open({
            title: s,
            file: e.settings.external_filemanager_path + "dialog.php?type=4&descending=" + g + o + d + l + "&lang=" + e.settings.language + "&akey=" + r,
            width: t,
            height: i,
            inline: 1,
            resizable: !0,
            maximizable: !0
        })
    }
    e.addButton("responsivefilemanager", {
        icon: "browse",
        tooltip: "Insert file",
        shortcut: "Ctrl+E",
        onclick: t
    }), e.addShortcut("Ctrl+E", "", t), e.addMenuItem("responsivefilemanager", {
        icon: "browse",
        text: "Insert file",
        shortcut: "Ctrl+E",
        onclick: t,
        context: "insert"
    })
		
});`

**Comment by Tomicapo** [comment]
Regarding the solutions proposed by pjayramkumar on Jul 20, 2017, I was getting an error: 
**"the variable use_static_urls_in_catalog is not defined"**. 
I set the variable at the previous line to _false_ and it all worked.

I also had to do something a bit sloppy. I changed ResponsiveFilemanager's config.php file setting the thumbs_base_path to one more parent folder '../../../thumbnails/' but left the current_path set to '../../images/'. This looks weird.... but it's working. (My file manager is inside js folder, so it's two levels down). I really don't have more time to understand this for now :(
Hope this helps someone.

**Comment by vanilla-thunder** [comment]
this one is not related to Responsive Filemanager only, i'm using Roxy Fileman and my custom tinymce plugin looks pretty like the suggested / fixed code above.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
