### ISSUE TITLE
Add emoji unicode plugin

### ISSUE THREAD

**Issue by chrispcb** [tinymce/tinymce#3766]
New feature:
Add a emoji **unicode** plugin like onesignal-emoji-picker : https://github.com/OneSignal/emoji-picker

**Comment by Daijobou** [comment]
+1

**Comment by konekoya** [comment]
+1

**Comment by adamsentz** [comment]
+1

**Comment by yusteam** [comment]
+1

**Comment by BZhawaii** [comment]
+1

**Comment by fridzema** [comment]
+1

**Comment by quienti** [comment]
+1

**Comment by voitsekhovskymax** [comment]
+1

**Comment by stefanrother** [comment]
Workaround: use and configure the [Character Map Plugin](https://www.tiny.cloud/docs/plugins/charmap/)

**Comment by androb** [comment]
The new [emoticons plugin](https://www.tiny.cloud/docs/plugins/emoticons/) in Version 5 works this way.
