### ISSUE TITLE
autolink plugin bug in firefox

### ISSUE THREAD

**Issue by AdamFu** [tinymce/tinymce#3767]
Type link like www.1.com than type space，the second link had not change to link.Test in Firefox 51.0.1 Firefox 54.0 and Firefox Developer Edition.

![as 00_00_00-00_00_10](https://user-images.githubusercontent.com/5377868/27505465-0c43fabe-58d3-11e7-9390-b492beed2e94.gif)

test in https://www.tinymce.com/docs/demo/classic/

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
