### ISSUE TITLE
How to add shortcut for subscript and superscript?

### ISSUE THREAD

**Issue by vutaviva** [tinymce/tinymce#3768]
I tried to use tinymce.shortcuts to add shortcut for subscript/superscript.
`editor.shortcuts.add('ctrl+.', '', 'Subscript');`
or
` editor.shortcuts.add('ctrl+.', '', function () {
    editor.execCommand('Subscript', false);
});`

However, they do not work. How to add this shortcuts?

**Comment by fyrkant** [comment]
I think the problem that it doesn't work to make a shortcut with `.` (a period) in it, make a shortcut with some other combination and it should work, see this fiddle for example: http://fiddle.tinymce.com/iUfaab

Closing this issue but if you have any other questions just leave a comment and I can open it up again.
