### ISSUE TITLE
How to Refresh the Angular Js Template 

### ISSUE THREAD

**Issue by staffsri** [tinymce/tinymce#3769]
hai Sir,
please Rectify this problem , i am explained in below link
https://youtu.be/SHMkrC7GBeo
example code : 
 $scope.templates =
         [ { name: 'testquestionsGet.php?id='+$scope.qno+'&exid='+exam+'&pprid='+paper, url: 'testquestionsGet.php?id='+$scope.qno+'&exid='+exam+'&pprid='+paper}
         ];
this code will written because  **testquestionsGet.php** page is included in another page how to reload this  **testquestionsGet.php**  page or if any solution please explain it.
**Thank You**,

**Comment by fyrkant** [comment]
spam?
