### ISSUE TITLE
Tinymce 3.5.7 unable to reinitialize

### ISSUE THREAD

**Issue by mahesfsp** [tinymce/tinymce#3772]
$(document).ready(function(){
			tinymce.editors = [];
			tinymce.EditorManager.editors = [];
			$("#edit-short-description-value_parent").remove(); 
				var editor_id = "edit-short-description-value";
				tinymce.EditorManager.execCommand('mceRemoveControl',true, editor_id);
				window.setTimeout(function(){
				try {
				tinymce.init(Drupal.settings.wysiwyg.configs.tinymce);
				console.log('tinymce', tinymce, 'Drupal.settings.wysiwyg.configs.tinymce', Drupal.settings.wysiwyg.configs.tinymce)
				} catch (e) {
					// TODO: handle exception
					console.log(e, e.stack);
				}
			},50);
			
			window.setTimeout(function(){
				$(".defaultSkin").not(':last').remove();
			},100);
	above code used to reinitialize the tinymce editor, but while applying the colour to the text the tinymce editor was disappeared . Anyone help?

**Comment by lnewson** [comment]
Hi,

Thanks for the report, however I'm sorry we no longer support TinyMCE 3. At this time TinyMCE 5 is our supported version, however we're still fixing major issues identified in the latest version of TinyMCE 4. So it's our recommendation to upgrade to a newer version if you're still having issues, as it's likely been fixed given the age of this issue.

Thanks!
