### ISSUE TITLE
Toggling off Bold, Italic, etc sometimes adds a <br> and forces text to the next line

### ISSUE THREAD

**Issue by jerryorr** [tinymce/tinymce#3773]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
In certain situations, turning off an "emphasis" setting (like Bold) will insert a `<br>` that forces the text to the next line.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

 1. Go to https://codepen.io/anon/pen/vZWWZq
 2. Focus into the editor
 3. Select Bold
 4. Enter some text.
 5. Press Enter to start a new paragraph
 6. Enter some text.
 7. Select Bold

The cursor will go to the next line, and any characters entered will be on the new line.

A couple things I noticed:
 1. The `<strong>` element created by step 4 has `<br data-mce-bogus="1">` at the end of it, which is what's pushing the cursor to the next line
 2. If you call `editor.getContent()`, the returned HTML will not have the `<br data-mce-bogus="1">` element, so the HTML this produces looks different than the editor (the un-bolded text is on the same line as that from step 6).

**What is the expected behavior?**

Toggling off Bold shouldn't trigger a new line.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I used TinyMCE 4.6.4, and I've observed this problem in Firefox, IE11 and Edge. Chrome does _not_ have the problem.

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
