### ISSUE TITLE
Sign up Page for API key - Terms & Conditions link broken

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#3779]
**Do you want to request a *feature* or report a *bug*?**
See title.

**What is the current behavior?**
use cloud version w/o API key: the pop up with link to sign up page arises.
On the sign up page, I have to check " I’ve read and accept the Terms & Conditions ". But the link to Terms & Conditions is broken "Page not found".
not very trustworthy
regards
manu

**Comment by r12s** [comment]
Hi @manu37 thanks for raising this issue. This has been resolved.

Some background: we migrated our webstore to a new server the last weekend and in the process one of the team was too aggressive in cleaning up some pages.

By all means ping me here or via email robert.collings@ephox.com if there's anything else I can help you with regarding this issue. Cheers!
