### ISSUE TITLE
space in emtpy lines

### ISSUE THREAD

**Issue by dimmelsw** [tinymce/tinymce#3780]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
If I load content like this into TinyMCE, TinyMCE is adding an additional space into the empty line.
```
<p>123</p>
<p></p>
<p>456</p>
```

http://fiddle.tinymce.com/STfaab

**What is the expected behavior?**
There should be no space in the empty lines.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Browsers: Firefox, Internet Explorer, Chrome
TinyMCE Version 4.5.4 and edge

**Comment by fyrkant** [comment]
This is not a bug but wanted behaviour, without a space in the empty p tag it wont get any height, check this jsfiddle for demo: https://jsfiddle.net/asha4puj/

**Comment by dimmelsw** [comment]
But if I enter a text with empty lines into TinyMCE, then there is no space.
If I save this text to HTML and reload it into TinyMCE, then there is a space in the empty line.

I expect that, if I enter text, save and reload it, it should by exactly the same.

**Comment by fyrkant** [comment]
> If I save this text to HTML and reload it into TinyMCE, then there is a space in the empty line.

But when you save it again there is no space, right? It is only added in the editor so you have somewhere to insert the cursor.
