### ISSUE TITLE
[Table Plugin] Table with style width in percent

### ISSUE THREAD

**Issue by hungcrush** [tinymce/tinymce#3784]
I have a table with style for each td is
`style="width: 18.3482%;"`
When I drag to change width of td => it calculate width wrong. 

Please check with this table.. Thank you

> &lt;div style="line-height: 1.6em; font-family: 'Malgun Gothic','Meiryo UI',Verdana,Arial,sans-serif; font-size: 13px;"&gt;
&lt;div style="line-height: 1.6em; font-family: 'Malgun Gothic','Meiryo UI',Verdana,Arial,sans-serif; font-size: 13px;"&gt;
&lt;table width="100%" height="500" style="border-color: #d3d3d3 gray; font-size: 9pt; -ms-word-break: break-all;" border="1" cellspacing="0" cellpadding="5" border-color="#000000"&gt;
&lt;tbody&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td align="center" style="text-align: left;" colspan="7"&gt;¾Æ·¡ Ç°¸ñ¿¡ ´ëÇÑ ±¸¸Å¸¦ ¿äÃ»µå¸³´Ï´Ù.&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="16%" align="center"&gt;Ã»±¸ÀÏÀÚ&lt;/td&gt;
&lt;td align="center" colspan="6"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="16%" align="center"&gt;¼ö·ÉÀÏ&lt;/td&gt;
&lt;td align="center" colspan="6"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="16%" align="center"&gt;PROJECT¸í&lt;/td&gt;
&lt;td width="46%" align="center" colspan="3"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;±¸¸ÅÃ³&lt;/td&gt;
&lt;td width="12%" align="center" colspan="2"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" colspan="2"&gt;Ç° ¸í&lt;/td&gt;
&lt;td width="17%" align="center"&gt;±Ô °Ý&lt;/td&gt;
&lt;td width="12%" align="center"&gt;¼ö ·®&lt;/td&gt;
&lt;td width="13%" align="center"&gt;´Ü °¡&lt;/td&gt;
&lt;td width="13%" align="center"&gt;±Ý ¾×&lt;/td&gt;
&lt;td width="12%" align="center"&gt;ºñ °í&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" colspan="2"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="17%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" colspan="2"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="17%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" colspan="2"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="17%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" colspan="2"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="17%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" colspan="2"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="17%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" colspan="2"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="17%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" colspan="2"&gt;ÇÕ °è&lt;/td&gt;
&lt;td width="17%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;0&lt;/td&gt;
&lt;td width="12%" align="center"&gt;
&lt;p&gt;ºÎ°¡¼¼&lt;/p&gt;
&lt;p&gt;Æ÷ÇÔ&amp;nbsp;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="33%" align="center" rowspan="4" colspan="2"&gt;ºÐ·ù&lt;/td&gt;
&lt;td width="17%" align="center"&gt;¿øÀç·á&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;ºñÇ°&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="17%" align="center"&gt;°³¹ßºñ&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;¼Ò¸ðÇ°ºñ&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="17%" align="center"&gt;·»Å»ºñ&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;ÀúÀåÇ°&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="17%" align="center"&gt;¿ÜÁÖ°¡°øºñ&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="13%" align="center"&gt;¼ö¼±ºñ&lt;/td&gt;
&lt;td width="13%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td width="12%" align="center"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="16%" align="center"&gt;±Ù°Å¼­·ù&lt;/td&gt;
&lt;td align="center" colspan="6"&gt;1. Ç°ÀÇ¼­1ºÎ 2. °ßÀú¼­1ºÎ 3. °Å·¡¸í¼¼Ç¥ ºÎ 4. ¼¼±Ý°è»ê¼­ ºÎ&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td width="16%" align="center"&gt;NEGO&lt;br /&gt; ´ë±Ý°áÁ¦&lt;br /&gt; ´ã ´ç ÀÚ&lt;/td&gt;
&lt;td align="center" colspan="6"&gt;Àû Á¤( ) &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;Àç NEGO¿ä¸Á ( &amp;nbsp;)&lt;br /&gt; ´ç»ç°áÁ¦Á¶°Ç ( )&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; º°µµÁ¶°Ç ( &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr bgcolor="#ffffff"&gt;
&lt;td valign="top" colspan="7"&gt;¡Øºñ°í&lt;br /&gt; &lt;br /&gt; &amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
