### ISSUE TITLE
paste plugin broken in inline editors in Chrome/MacOS and Safari/MacOS

### ISSUE THREAD

**Issue by thorn0** [tinymce/tinymce#3785]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

On Chrome/MacOS, when Command-V is pressed, the content is inserted to the end of the document. On Safari this bugs shows itself too, but not that often.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/xUfaab/2

1) Open it in Chrome (better) or Safari on MacOS
2) Have some content to paste in the clipboard
3) Click somewhere in the middle of the content
4) Move the caret one character left or right with arrow keys (this step is optional, but sometimes the bug can't be reproduced without it)
5) Press Command-V
6) See the content get appended to the end of the document

And one more issue that isn't stably reproduced:

1) Open it in Chrome or Safari on MacOS
2) Select some part of the content
3) Make it bold or italics
4) Now while the selection is still there, click somewhere in the middle of this selection. It'll remove the selection and place the caret there.
5) Press Command-V
6) It doesn't happen every time, but the inserted content might **replace** the content that was selected

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

MacOS 10.12, TinyMCE 4.6.4
It worked in 4.6.3.
Broken by this commit: https://github.com/tinymce/tinymce/commit/f37a197e1ca22f4d06b4e8b429884391e6192c96

**Comment by bcrigler** [comment]
Having this issue as well after upgrading to latest... any idea on an ETA for this?  We use inline mode in our web application and this is breaking functionality for many customers.

**Comment by Bacher** [comment]
I have similar problem, but this very very simple reproduce case:
I didn't find github and wrote this in ideas on your site:
https://community.tinymce.com/communityIdeaDetail?id=08761000000QnuUAAS

**Comment by thorn0** [comment]
@bcrigler As a temporary solution, you can disable the `paste` plugin for mac users:
```
if (tinymce.Env.mac) ...
```

**Comment by thorn0** [comment]
@Bacher I think yours is a different issue, namely #3775.

**Comment by Bacher** [comment]
@thorn0 Yes, thank you.

**Comment by bcrigler** [comment]
@thorn0 so removing the paste plugin on mac does not fix the issue... I used the mac environment variable which did work and removes the paste plugin on macs although it does not appear that the paste plugin is the problem here...

<img width="1680" alt="screen shot 2017-07-07 at 1 37 47 pm" src="https://user-images.githubusercontent.com/2781424/27969691-da18b16e-6319-11e7-9ff2-f32a6229947b.png">

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
