### ISSUE TITLE
Updating image size in a table doesn't update cells widths and heights

### ISSUE THREAD

**Issue by ayZagen** [tinymce/tinymce#3788]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Updating image size in a table cell, doesn't update cell widths and heights.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
-create a table with 3 columns
-place an image to the center cell
-resize image by resize handles
-the cells widths and heights are not changing

**What is the expected behavior?**
cells widths and heights should be updated too.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 4.6.4

**Comment by fyrkant** [comment]
Hmm, I'm not sure I understand the problem, the cell height and width seem to update fine for me.  

See [this fiddle](http://fiddle.tinymce.com/9Ufaab), click into the table and resize it with the handles. Is it not working as you would like it to?

**Comment by ayZagen** [comment]
@fyrkant resize the image and after that cell's width is still 156px. In my project I convert html taken from tinymce to pdf by using iText. Because of widths and heights are not updating, image in the cell flows out of the table in the pdf.

**Comment by fyrkant** [comment]
@ayZagen Is this issue still relevant with the latest version of TinyMCE?

**Comment by ayZagen** [comment]
Latest version works as expected.
