### ISSUE TITLE
TinyMCE 4.6.3 + Angular 4 + Edge 14 issue with editor

### ISSUE THREAD

**Issue by gaurav2887** [tinymce/tinymce#3789]
Recently we have upgraded our application to angular4, tinymce plugin is working correctly in IE, FF & Chrome browsers but we see some issues while loading plugin in edge browser.

```
ERROR Error: Uncaught (in promise): Error: TypeError: Object expected
Error: TypeError: Object expected
at callWithDebugContext (http://localhost/vendor.dll.js:19309:9)
referring method in angular/core.es5.js file

```

Currently we are using Angular v4.12 Typescript v2.2.2

Any help is appreciated.

**Comment by fyrkant** [comment]
Are you sure that this has something to do with TinyMCE?

**Comment by fyrkant** [comment]
And what plugin are you using? It might be best to ask the plugin developers for help.

**Comment by gaurav2887** [comment]
@fyrkant  - Our code is working fine when we are commenting this line `<textarea tinymce placeholder="test" [(ngModel)]="answer"></textarea>`  in our project.  We are using native tinymce npm package.

**Comment by eegasudheer** [comment]
@fyrkant ,  Initially i posted issue with zone.js, assuming as the error pointing to zone.js file, but digging little more we figured out the issue something related tinymce.js.

https://github.com/angular/zone.js/issues/829

Please refer below stack
http://tinypic.com/r/1gfzb6/9 

Please check it once.

**Comment by fyrkant** [comment]
But where does the tinymce angular code come from? Is it a plugin or something you have written yourself?

**Comment by eegasudheer** [comment]
@fyrkant , we are initializing the plugin in below way.	

`<textarea tinymce placeholder="test" [(ngModel)]="answer"></textarea>`

    ngAfterViewInit(): any {
		let tinyMceConfigCommon: any = this.tinyMceConfig();
		let tinyMceConfigLocal: any = this.tinyMceConfigEditable();
		tinymce.init(_.merge(tinyMceConfigCommon, tinyMceConfigLocal));        
	}

	tinyMceConfig(): any {
		return {
			mode: "textareas",
			editor_deselector: "mceNoEditor",
			elementpath: true,
			plugins: ['link', 'paste'],
			browser_spellcheck: true,
			skin_url: '/assets/skins/lightgray',
			menubar: false,
			statusbar: false,
			width: 'auto',
			content_style: "p {font-size:16px;}"
		}
	}

	tinyMceConfigEditable(): any {
		return {
			setup: editor => {
				this.editor = editor;
				editor.on("init", ed => {                    
					ed.target.setContent(/*service call fetch content*/);                    
				});                
			},
		}
	}

**Comment by gaurav2887** [comment]
@fyrkant - We are using native tinymce [npm package](https://www.npmjs.com/package/tinymce)

**Comment by oleksiipavlenko** [comment]
same problem when change default font-size and call remove

**Comment by fyrkant** [comment]
For angular we now have an official wrapper: https://github.com/tinymce/tinymce-angular
