### ISSUE TITLE
Paste from Excel with errors

### ISSUE THREAD

**Issue by leandrogs** [tinymce/tinymce#3790]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
Using Paste plugin from TinyMCE break Microsoft sheets.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
- Select and copy a sheet from Microsoft Excel with some empty cells and cells with error.
- Paste into TinyMCE editor
- Sheet is pasted without original formatting and I get some missing cells

![jul-05-2017 15-39-23](https://user-images.githubusercontent.com/1022769/27880042-fc829dfe-6199-11e7-988e-e43e8281abf8.gif)

- Select and copy a sheet from Google Sheets
- Paste into TinyMCE editor
- Sheet is pasted correctly (only without original colors)

![jul-05-2017 15-38-41](https://user-images.githubusercontent.com/1022769/27880033-f70ea746-6199-11e7-9b4d-2b009401f416.gif)

**What is the expected behavior?**
- Paste all cells correctly

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I'm using the full demo from tinyMCE web page with Google Chrome  59.0.3071.115

**Comment by fyrkant** [comment]
For pasting content from Word and Excel files we can offer the premium [PowerPaste plugin ](https://go.tinymce.com/powerpaste/), try it out on that page and see how it works.

**Comment by leandrogs** [comment]
`PowerPaste plugin` works fine... but we expected TinyMCE `Paste plugin` to at least paste without break columns.

**Comment by RainerSchwarze** [comment]
I tested PowerPaste at the TinyMCE homepage and the cell formatting was missing there after pasting from Excel 2013. I looked closer into this regarding the paste plugin and noticed, that in `./src/plugins/paste/main/ts/core/Utils.ts` the function `trimHtml` only keeps the data between the `body` tags. However, in the pasted data the formatting exists in a `style` element before that `body` and thus gets removed.

**Comment by performanceadjusting** [comment]
For Pasting content from word, excel and powerpoint, You can try [PasteitCleaned](https://www.pasteitcleaned.io/) , It's an external TinyMCE plugin that can help you to paste the data from Excel without any error and It’s affordable as compared to other plugins.

**Comment by evawhittle** [comment]
For Pasting content from word, excel and powerpoint, You can try [PasteitCleaned](https://www.pasteitcleaned.io/) , It's an external TinyMCE plugin that can help you to paste the data from Excel without any error and It’s affordable as compared to other plugins.
