### ISSUE TITLE
Background color being applied to a p tag that should not be.

### ISSUE THREAD

**Issue by SimplyCorey** [tinymce/tinymce#3796]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The background color is being applied to a p tag that should not have it applied.

1: Visit http://fiddle.tinymce.com/EUfaab/1
2. Triple click on the area that says triple click to highlight the p tag
3. Change the background color.
4. Notice that the bottom p tag changes it's background color as well.

**What is the expected behavior?**

The bottom p tag should not change the background color.

**Comment by SimplyCorey** [comment]
This seems to only occur when the p tag under the highlighted area has a `font-size` attribute.

**Comment by Silviu-Marian** [comment]
This occurs with with tables too

http://fiddle.tinymce.com/fVfaab/1

Select the first paragraph, change the background color. This happens: 

![image](https://user-images.githubusercontent.com/1747499/28164301-88d42852-67d7-11e7-80a1-0181b377201c.png)

**Comment by SimplyCorey** [comment]
This appears to only affect Chrome.

**Comment by Silviu-Marian** [comment]
@SimplyCorey actually it's reproducible in other browsers too. 

I think it's a deeper issue and Chrome has the triple-click selection showing https://github.com/tinymce/tinymce/issues/3810. In Firefox you can select the first letter of the paragraph, hold down Shift, press the End key, then with Shift still selected press Arrow Right. It will (invisibly) select the paragraph ending. After that, changing the background color will also extend to other parts.

**Comment by SimplyCorey** [comment]
@jayarjo Anything you need from me to confirm or help fix this?

**Comment by SimplyCorey** [comment]
@spocke Anything you need from me to confirm this bug?

**Comment by SimplyCorey** [comment]
Looks like this is fixed in 4.6.6

**Comment by SimplyCorey** [comment]
`    Fixed bug where background color wasn't applied correctly on some partially selected contents.`
