### ISSUE TITLE
React Webpack & Tinymce

### ISSUE THREAD

**Issue by goartur** [tinymce/tinymce#3797]
So, I know I could add a link in head section to use TinyMCE in my react project but I will not, because of web pack in my project.
I'm trying to add new TinyMCE loader but I can't get it running, have no clue what is wrong with it. In the inspector I see all elements of Tiny and also I do not get any errors or warnings(but are not visible, only classes appear). 

![alt text](https://d3higte790sj35.cloudfront.net/images/ex/ux/5d7256b1f46ccabd2f03de41979bc10e.jpeg)

Here is how I done it:
```

plugins: [
new webpack.LoaderOptionsPlugin({
			options: {
				loaders: [
					{
						test: require.resolve('tinymce/tinymce'),
						use: [
							'imports-loader?this=>window',
							'exports-loader?window.tinymce',
						]
					},
					{
						test: /tinymce\/(themes|plugins)\//,
						use: [
							'imports-loader?this=>window'
						]
					},
				],
			}
		})]
```

I got following npm's libs:
```
    "react-tinymce": "^0.5.1",
    "tinymce": "^4.6.4"
    "exports-loader": "^0.6.4",
    "imports-loader": "^0.7.1",
```
The script looks like that:

```
import React from 'react';
import tinymce from 'tinymce/tinymce'
import 'tinymce/themes/modern/theme'

import 'tinymce/plugins/paste/plugin'
import 'tinymce/plugins/link/plugin'
import 'tinymce/plugins/autoresize/plugin'

class Textarea extends React.Component {

	componentDidMount(){
		tinymce.init({
			selector: '.addAnswerArea',
			skin: false,
			plugins: ['paste', 'link', 'autoresize']
		})
	}

	render() {
		return (
			<div className="field">
					<textarea className="addAnswerArea" placeholder="Add a comment..."></textarea>
			</div>
		)
	}

}

export default Textarea;
```

**Comment by fyrkant** [comment]
Have you imported the skin files correctly?

**Comment by goartur** [comment]
@fairbanksg I don't want to use skin so I did 'skin: false', I think this should fix skin problem in this case(?) Or do I really need those skins even If I don't use them?

**Comment by fyrkant** [comment]
Yes the editor will not function without a skin.

**Comment by goartur** [comment]
@fairbanksg Thanks for your answer, now I get it. Are there any tutorials that provide a correct way of implementing TinyMCE and themes with web pack 2?
I have no good solution to import those skins via web pack

**Comment by fyrkant** [comment]
There is not way a to bundle the skin files with webpack if that is what you mean, you simply have to move them somewhere in your project and then set the `skin_url` setting to the correct path. There is the webpack `require.context` that can move the files for you, but I would just move them manually once instead of having the code that moves the files mixed in with your app code. For more info see this page in the docs: https://www.tinymce.com/docs/advanced/usage-with-module-loaders/#gettingtheskin

**Comment by goartur** [comment]
@fyrkant That's pretty sad... Yet Thanks for helping!

**Comment by fyrkant** [comment]
Sad? TinyMCE lazy loads in the skin files to make the page load as fast as possible, if you bundled everything together it would probably slow things down.

**Comment by goartur** [comment]
@fyrkant I think that in the first place style should not be required at all. Just saying. I had many people complaining about it, my conclusion is that many people don't use it because of poor web pack compatibility.I think that there should be check if a theme is actually available, and then, after all, it should be included.

**Comment by fyrkant** [comment]
I'm not sure I understand what you mean with that styles "should not be required", how would the editor work without styles? 

I do not agree that TinyMCE suffers from compatibility problems with webpack, like I said the skin files are separate by design to make the loading faster.
