### ISSUE TITLE
File browse button not opening browse window in IE

### ISSUE THREAD

**Issue by manoj-mass** [tinymce/tinymce#3799]
Hi,
![file_picker](https://user-images.githubusercontent.com/26952806/28006358-90183d8c-656c-11e7-8403-cca12fe6f3c1.PNG)

In IE 11 When you click on the browse button to upload an image  it does not open the browse window,  Happens only in IE.

https://jsfiddle.net/manojdarshana/xnypgzob/10/

Any solution for this ?

**Comment by fyrkant** [comment]
Not a problem with tinymce, you just have to add the input to the body before you click it in ie11, this seems to work: https://jsfiddle.net/849gbLvp/1/

**Comment by manoj-mass** [comment]
Thanks mate.

**Comment by jayarjo** [comment]
@manoj-mass could you share the exact version of your IE11 and os version as well? 'cause it seems to work here on Windows 10:
![ie](https://user-images.githubusercontent.com/150075/28015697-252141e8-6582-11e7-9b06-efbd8b8955f9.JPG)

**Comment by manoj-mass** [comment]
@jayarjo 

OS: windows 7

![ie](https://user-images.githubusercontent.com/26952806/28105673-11a5b798-66fe-11e7-8ee5-4b693147069e.PNG)
