### ISSUE TITLE
Ignoring of extended_valid_elements

### ISSUE THREAD

**Issue by lk-geimfari** [tinymce/tinymce#3801]
**Do you want to request a *feature* or report a *bug*?**

Seem it's a bug.

---

**What is the current behavior?**

TinyMCE filtered `iframe` element, although should not do it, because i use this option in my settings:

```js
extended_valid_elements = "iframe[class|src|frameborder=0|alt|title|width|height|align|name]";
```
How i update settings:
```js
function Plugin(editor, url) {
    this.editor = editor;
    this.editor.settings.extended_valid_elements = "iframe[class|src|frameborder=0|alt|title|width|height|align|name]";
    // logic
}
```
When i use `console.log()` i see that the `extended_valid_elements` is already in object `settings`:
![image](https://user-images.githubusercontent.com/15812620/28009536-78c6543c-6564-11e7-9e01-b5cbcbdb1c95.png)

---

**What is the expected behavior?**
I update rules of valid elements using option `extended_valid_elements` to make it possible to insert an `iframe` which have this structure:
```
<iframe src="https://google.com/maps/embed/v1/place?zoom=10&amp;maptype=roadmap&amp;q=55.7558, 37.6173&amp;key=MYKEY" frameborder="0" width="400" height="300"></iframe>
```
But TinyMCE still filtered `iframe` elements.

---

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Browser: **Chrome 58.0.3029.110 (64-bit)**
OS: **Ubuntu 16.04**
TinyMCE:  **v4.6.4**

**Comment by fyrkant** [comment]
It might not be possible to change this setting after the editor is initialised, try adding the setting in the init settings object and see if it works.

**Comment by lk-geimfari** [comment]
@fyrkant I was already tried it, but it's not working, although `extended_valid_elements` is in `settings` object.

**Comment by lk-geimfari** [comment]
@fyrkant Is there any other way to update the `settings` object?

**Comment by lk-geimfari** [comment]
ping
