### ISSUE TITLE
 Table breaks when deleting a row with merged cells (rowspan)

### ISSUE THREAD

**Issue by touchaqb** [tinymce/tinymce#3803]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Deleting the first row of a table with an entire merged cells column breaks the whole table.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Insert a table 3x3 or greather;
2. merge the cells of an entire column;
![broken-tinymce-table-step2](https://user-images.githubusercontent.com/25030975/28072045-1cbe0b52-6628-11e7-9e8e-e567ed79be66.png)
3. place the cursor in a cell of the first row of the table and then Table->Row->Delete Row.
![broken-tinymce-table](https://user-images.githubusercontent.com/25030975/28072158-8bc4eef8-6628-11e7-9a50-4c1a9a95ace1.png)

**What is the expected behavior?**
Preserve the table structure, properly recalculating the rowspan and mantaining the number of <td> elements even over all the <tr> elements of the table.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.6.4

**Comment by Afraithe** [comment]
This doesn't happen in 4.7.x
