### ISSUE TITLE
Is NotificationManager Accessible ?

### ISSUE THREAD

**Issue by manoj-mass** [tinymce/tinymce#3805]
Came up with an issue which is tinymce notifications are not read out once they appear. There is no way that a blind person could notice those notifications if not read out as Alerts.

Browser: IE 11 and Chrome.
Accessible reader: JAWS

Are they accessible if not are there any fixes for it, we just need to set the role as alert i guess ?

**Comment by fyrkant** [comment]
This is a good feature request, the NotificationManager should probably use some aria live regions to make the screen readers follow what is shown. Thank you!

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
