### ISSUE TITLE
Toggling B/I when cursor at end clears formatting

### ISSUE THREAD

**Issue by liukwrm** [tinymce/tinymce#3806]
Bug:

Here is a fiddle with set content that can be the result of using tinymce.activeeditor.formatter.apply with a custom format. http://fiddle.tinymce.com/TUfaab

1. Put cursor at the end
2. Toggle Italic button

Expected: Italic to toggle away, but both Bold and Font Size remain
Actual: Italic, Bold, and Font Size all revert to tinymce default

**Comment by tinydylan** [comment]
I can replicate this issue in the fiddle URL you provided on the latest TinyMCE (5.2.1)

**Comment by ltrouton** [comment]
A fix was added to TinyMCE 5.3.0 to improve format removal at the end of lines and on empty lines which should resolve the issue you were seeing. Please let us know if you have any further issues.
