### ISSUE TITLE
Font styles (like "bold, "italic",...) are not removed from text inside table cell (IE11)

### ISSUE THREAD

**Issue by Stonsi85** [tinymce/tinymce#3814]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Applied font-styles like "bold" can't be removed from text inside a table cell.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
- put some text into a table cell and mark the text
- apply font-style "bold" to the text (by bold-button)
- click again on the bold-button to remove the font-style
-> font-style bold is not removed from text
**What is the expected behavior?**
- font-style bold should be removed from text

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
version: 4.5.6
browser: Internet Explorer 11
It worked in previous versions (tested with version 3.5.11)

**Comment by jayarjo** [comment]
Cannot repeat it in IE11 on Windows 10 (using this fiddle: http://fiddle.tinymce.com/pdgaab/1)
