### ISSUE TITLE
nonbreaking plugin should insert spaces as a transaction

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#3815]
If the `nonbreaking_force_tab` setting for the nonbreakingspace plugin is enabled, the plugin should insert the spaces as a transaction, so that they can be undo as a single operation. 

Right now they are inserted by repeatedly calling the `mceNonBreaking` command and the user has to use Ctrl+Z multiple times to undo the insertion.

The related code is [here](https://github.com/tinymce/tinymce/blob/master/src/plugins/nonbreaking/src/main/js/Plugin.js#L57).

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
