### ISSUE TITLE
Removing underline also removes other formats in the text

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3817]
TinyMCE removes other format styles that were present previously, after removing the underline format.

Steps to repro:
1. open http://fiddle.tinymce.com/3Vfaab
2. See that there is content there with font-size set to 18pt and underline
3. Hit enter to start another line
4. Press underline button to remove that style from the current line

Expected:
Underline is removed but the font-size remains 18pt
Actual:
Both underline and font-size are removed.

Tested in Chrome 59.0.3071.115 on Mac

**Comment by thiagolacerda** [comment]
@fyrkant I saw that you escalated this bug almost 2 months ago.. any updates?
Thanks a lot!

**Comment by cjdubois10** [comment]
@thiagolacerda I am currently working in a small organization consisting of college students that decided to adopt the TinyMCE project. We came across this bug and found it interesting. We wanted to let you know that we are going to look into this bug and attempt to fix it. We will keep you updated on our progress.

**Comment by thiagolacerda** [comment]
good to hear that @cjdubois10 !
Thanks

**Comment by cjdubois10** [comment]
@thiagolacerda it looks like my team has a fix. We are writing some unit tests to verify the changes that we have made and will be submitting a pull request if all tests are passed.

**Comment by tinydylan** [comment]
It looks like this bug has been fixed, so I'm closing the ticket. Please let us know if the bug still occurs.

**Comment by tinydylan** [comment]
My apologies - this issue is still present. Reopening...

**Comment by ltrouton** [comment]
A fix was added to TinyMCE 5.3.0 to improve format removal at the end of lines and on empty lines which should resolve this issue. Please let us know if you have any further issues.
