### ISSUE TITLE
Code Scan Issue -Insecure Randomness-tinymce.min.js

### ISSUE THREAD

**Issue by monika020627** [tinymce/tinymce#3822]
Hi,

We are using the tinymce plugin Verison 4.1.9 in our application.
Our security team ran the fortify code scan and found issue in tinymce.min.js at line no.2
Its due to the Math.random method use

`function(r,a,s,l,c){var u,d,f,p=0,h="0",m=r&&[],v=[],y=T,b=r||o&&w.find.TAG("*",c),C=W+=null==y?1:Math.random()||.1,x=b.length;…`

Attached is the more detailed information of the issue.

Please let us know if you have a fix available for this issue?

Thanks,
M
[TinyMce-Insecure Randomness.docx](https://github.com/tinymce/tinymce/files/1156569/TinyMce-Insecure.Randomness.docx)

**Comment by fyrkant** [comment]
What is insecure about Math.random()? And is this problem still existing in the latest version of TinyMCE (4.6.4)?

**Comment by monika020627** [comment]
So as per Fortify Code scan It generates the Insecure Randomness issue which is 
Insecure randomness errors occur when a function that can produce predictable values is used as a source of randomness in security-sensitive context

JavaScript's Math.random() function is not a cryptographically-secure random number generator.

Here are some more details on this
https://stackoverflow.com/questions/5651789/is-math-random-cryptographically-secure

I am not sure if the latest version has this issue or not we are using 4.1.9 and that is what I wanted to check if already aware of this issue and knows that the newer version doesn't have this issue.

**Comment by fyrkant** [comment]
We don't really use `Math.random()` in a way so that this will become a problem, no cryptography in TinyMCE.
