### ISSUE TITLE
Word Count error with individual characters' formatting

### ISSUE THREAD

**Issue by akamdar** [tinymce/tinymce#3825]
Description of problem:

Steps to reproduce:

1. Go to a large text box
2. Type in one word (word count recognises 1 word and count it as such) (ex. test)
3. select the bold and type in continuation with the previous word (ex. test**123**) it reduces the word count 0. 
4. Now give space after test123 and type a new word then it will show word count 1 instead of 2. 
Similar behavior is happen with the Italic and Underline.

Expected result: The word count should still be 1 if I select bold / Italic / Underline in continuation of word.

Actual result: The word count is 0 words despite there only being 1 single word. (ex. test**123**_**456**_)

Tinymce Version: 4.5.7
Browser: Chrome / Firefox / Safari
OS: Windows 8.

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
