### ISSUE TITLE
Bug: Different font in tinymce control and email sent

### ISSUE THREAD

**Issue by filipmis** [tinymce/tinymce#3827]
Hi,

I am using tinymce 4.6.1. After typing something in tinymce control without changing font of text (default is '**Verdana**') and after sending that email, the font in sent mail is set to '**Times New Roman**'. Can this be fixed?

If I try to send email, but before sending I select all text in tinymce control and click on 'Verdana' font than font in email is correctly set to 'Verdana'.

With thanks,
Filip

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by filipmis** [comment]
[http://fiddle.tinymce.com/YVfaab](http://fiddle.tinymce.com/YVfaab)

In editor if you type 'h' in the first line and press enter and type 'h' in the second line and select 'h' in the second line and select 'Verdana' font from toolbar the source code (Tools - Source Code) will show:

```
<p>h</p>
<p><span style="font-family: verdana, geneva, sans-serif;">h</span></p>
```

The problem is that the font for the first line is not set and the toolbar shows default one 'Verdana'. In the second line source code correctly shows 'Verdana'. If I send that code as an email the first line is interpreted as 'Times New Roman' font in Microsoft Outlook.

Temporarily I changed content.min.css file and added 'Times New Roman' to the first place in
`font-family:"Times New Roman", Verdana,Arial,Helvetica,sans-serif;`.

I suppose the correct solution is to put the first line into span with style set to default font automatically.

**Comment by spocke** [comment]
Right yeah it will show the computed runtime font so the one that the css provides. Unsure how to solve that for emails though. Possible you would have to wrap non styled text nodes with some default font but that seems like a custom plugin would be needed. We could also potentially add a option to disable the run time font checking and just display an empty select box when you don't have a real style value in a span.

**Comment by filipmis** [comment]
That is possible solution, but if you put every line by default into span with style set to currently selected font than tinymce can be used correctly for getting HTML code used for sending emails.

I know that tinymce is not email editor by default, it is WYSWIYG HTML editor, but if this is done as I have proposed than tinymce can be correctly used for generating HTML source for sending emails.

This can be implemented as a plugin so that all lines are automatically put in span with it's own style with font in case when it is only needed.

**Comment by lostkeys** [comment]
An old issue, but here is a solution. You can use the `forced_root_block_attrs` to force inline styles on paragraphs like this:
```
forced_root_block_attrs: { 'style': 'font-size: 14px; font-family: "Comic Sans MS", Cursive;'}
```

Here is a live example: http://fiddle.tinymce.com/Ohhaab
