### ISSUE TITLE
BUG: B/U/I drops the font-size

### ISSUE THREAD

**Issue by Dominis13** [tinymce/tinymce#3828]
Hi all, sorry if this bug already has been reported, but i couldn't find it.

Steps to reproduce:

1. Run tiny
2. Set any non default font-size, for example 18pt
3. Write any word. for example 'first'
4. Change font-size to any non-default, for example 24pt.
5. Write one more word at the same line, for example 'second'
6. Select both words and turn on B/U/I

**Expected**: get B/U/I words with the same font-sizes
**Real Result**: font-size is dropped to default.
[Fiddle](http://fiddle.tinymce.com/VVfaab) Just select and press B/U/I

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
