### ISSUE TITLE
Basic Local File Picker used in Chrome

### ISSUE THREAD

**Issue by hezhongfeng** [tinymce/tinymce#3829]
Chrome version: `59.0.3071.115(64)`
tinymce version:4.6.4
I open this demo [file-picker](https://www.tinymce.com/docs/demo/file-picker/) with chrome.
step 1: click the image icon to insert.
step2: click loacl file icon to select a image. It takes about 10 seconds to respond after clicking.
But I use firefox do the same thing.Respond immediately.
So I thing there are different about Chrome and firefox?

**Comment by jayarjo** [comment]
There might be some delay _after_ you select the image, for example if it's too huge. But I don't see why it should delay the browse dialog. Doesn't happen here.

**Comment by Afraithe** [comment]
Not enough info.
