### ISSUE TITLE
Link style is applying for the following text

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3830]
Hi,

We have upgraded our tinymce version from 4.4.3 to 4.6.4 and I got the following weird behavior like the line style is taking the link style for the whole line if inserted link for particular text and give space and started continuing entering the text.

Is this a change you made or it is a defect.

**Comment by mdemougin** [comment]
I have the same issue. It's also breaking some custom html insertion using insertHTMLAtCaret.

**Comment by mdemougin** [comment]
You can also see this in their full featured demo page.

**Comment by aziz512** [comment]
@kaviyarasanaspire Sounds like a natural behavior with links. After inserting a link try to press `arrow right` key multiple times until cursor leaves the link area.

**Comment by kaviyarasanaspire** [comment]
Thanks for the info!
