### ISSUE TITLE
Bad performance with many BLOB-images

### ISSUE THREAD

**Issue by Fiona-TU** [tinymce/tinymce#3834]
**Do you want to request a *feature* or report a *bug*?**
bug, sort of

**What is the current behaviour?**

When having many blob-images in the editor, initialization takes a lot of time. But it gets even worst when editing the source code inside the editor.

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
I created this fiddle with around 1600 blob images:
1. http://fiddle.tinymce.com/hWfaab (warning, browser may become unresponsive for a time)
2. Open TinyMCE Source Code Pop-Up, press OK
3. Wait (could take a minute or two)

**What is the expected behaviour?**
Should be more responsive.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
current version, firefox/chrome

**Comment by fyrkant** [comment]
This isn't really a bug with TinyMCE, parsing that much data is just really intensive work and it will take some time. 😅  

Unsure how this can be made faster, but open to suggestions!

**Comment by jayarjo** [comment]
How much is many? Having 1600 images in one post, doesn't seem too realistic. If that's your case, you should really rethink your structure. Also notice that it takes quite some time for the page to load with that many images even without TinyMCE: http://fiddle.tinymce.com/odgaab/1.
