### ISSUE TITLE
Feature: Responsive modal dialog

### ISSUE THREAD

**Issue by jnns** [tinymce/tinymce#3835]
Right now the modal dialog to insert links has fixed width on nearly every child element. This leads to the modal dialog to overflow the viewport on small display devices.

In order to reproduce this, go to the demo on https://www.tinymce.com/ and resize the display in your developer tools to something like 400x370 or similar. You will see that not the whole dialog is visible.

This behaviour is occurring on 4.6.3 but will most probably be present on other versions as well.

**Comment by Afraithe** [comment]
There are other tasks being worked on that will optimize it for smaller mobile type devices, responsive optimizing the entire UI is not a part of it, and it is way more complex than that.
