### ISSUE TITLE
Copying a text will make editor jump to top in IE11

### ISSUE THREAD

**Issue by danny6514** [tinymce/tinymce#3838]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Typing a text at the very bottom of the editor such that the scrollbar appears, selecting the text then press ctrl+c makes the editor jump to the top

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Browse to https://www.tinymce.com
2. Using the provided demo editor, make new lines until the scrollbar appears
3. Type any text and select it
4. Press ctrl+c
5. Note how the editor jumped up

**What is the expected behavior?**
Copying a text should not result in the editor to jump around

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.6.4, Windows 10, IE11.
Did not work on 4.6.2 either.

**Comment by danny6514** [comment]
This issue is still present in the latest version, any updates?

**Comment by RolfBensch** [comment]
still present. Any workarounds?

**Comment by fyrkant** [comment]
This has been fixed and will be a part of the next patch release (probably next week).

**Comment by fyrkant** [comment]
This has been fixed in 4.7.7 released today.

Closing this issue but if you can reproduce it in 4.7.7 leave a comment and I can open it up again.

**Comment by RolfBensch** [comment]
Still present in 4.7.9

**Comment by fyrkant** [comment]
@RolfBensch Have you tried the latest version, is it still present in that?

**Comment by wstransky** [comment]
This bug is still present in 4.9.4.
