### ISSUE TITLE
CMD+V pastes text at the end in inline mode with paste plugin on Chrome/Mac

### ISSUE THREAD

**Issue by GabiAxel** [tinymce/tinymce#3841]
When I set TinyMCE with `inline: true` and add the `paste` plugin, attempting to paste anything using CMD+V on Chrome on Mac causes the cursor to jump to the end of the text and the pasted content is appended there, and not where the cursor was at the time of pressing CMD+V. This can be reproduced in the website full example by changing the textarea to a div (and updating the selector) and adding `inline: true`.

Using the browser's "Paste" menu bar or context menu option does paste it correctly. CMD+V does works fine (pastes where the cursor is) in any of the following conditions:
* Firefox and Safari on Mac
* Chrome on Windows
* inline: false
* without the paste plugin

TinyMCE 4.6.4
Chrome 59.0.3071.115
MacOS 10.12.5

**Comment by lipten** [comment]
`<script src="//cdn.tinymce.com/4.5/tinymce.min.js"></script>`

**Comment by fyrkant** [comment]
Are you able to reproduce this problem on the latest 4.6.5 release?

**Comment by GabiAxel** [comment]
It's fixed in 4.6.5, thanks.
