### ISSUE TITLE
ctrl+z resets applied format to the base style in IE

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3846]
TinyMCE does not respect the previously applied format after ctrl+z in IE11

Steps to repro:

1. open http://fiddle.tinymce.com/9Wfaab
2. place cursor in the end of the line and hit enter to create a new line
3. uncheck underline (you will see that the font-size gets removed, but this is already reported in #3817)
4. type anything and then hit ctrl+z

Expected:
New text should be deleted and previously set formatting should be respected
Actual:
New text is deleted **but style is reset to base TinyMCE style**

Tested in IE11 (probably happens in Edge too)

**Comment by ltrouton** [comment]
Closing this ticket as it appears this issue was actually fixed in v4.7.3 and is not present in the v5. If anyone is still experiencing problems, let us know and we can reopen this ticket.
