### ISSUE TITLE
Font family & font style is changing

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3848]
Hi,

I have recently upgraded our tinymce version from 4.4.3 to 4.6.4 and we saw that the font family and font size is automatically changing while changing the format from paragrapah to Header1 or other Headers.

Can anyone please tell me that this is working as designed or we can stop this by changing any configuration.

**Comment by spocke** [comment]
We did a change to make this closer to how word etc works but it seems that not all users want it to work this way so we might add an option for this behavior.

**Comment by kaviyarasanaspire** [comment]
Thanks for your response!
