### ISSUE TITLE
Backport Edge paste charset bugfix to 4.5

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#3850]
Please, see https://github.com/roundcube/roundcubemail/issues/5885

It looks like the issue has been fixed in 4.6.0 (according to changelog). Could you backport this to 4.5.x as it's still in support? The issue sounds quite important. Also, I couldn't find the specific commit for the fix, could you point me to it (if there was one commit)?

**Comment by alecpl** [comment]
@spocke You announced 4.5 to be still supported. When do you plan a release? Any chance to have this fixed?

**Comment by spocke** [comment]
This one is fixed and released as 4.5.8.
