### ISSUE TITLE
Inline TinyMCE inside a bootstrap modal, dropdown menu items misaligned

### ISSUE THREAD

**Issue by mcgoncalves** [tinymce/tinymce#3851]
Hi, 

I'm using inline TinyMCE inside a bootstrap modal and when opening a drop-down menu item e.g.:"Formats", the items are shown aligned to the top-left corner of the page, instead of appearing where they should.

Any ideas on how to solve this problem?

**Aditional Information**
- TinyMCE - v4.6.4 (last version so far)
- Bootstrap - v 3.3.7 (last version so far)
- [JSFiddle demo](https://jsfiddle.net/marinagon/nez0z0z3/).
- [Stackoverflow question about this problem](https://stackoverflow.com/questions/44806269/bootstrap-modal-with-inline-tinymce-drop-down-menu-items-misaligned)

**Comment by AndyFTP** [comment]
Hi,

It seems to be a problem with `tabindex="-1"` attribute on the modal. If you remove it, it will work.

**Comment by mcgoncalves** [comment]
That solves it, thanks @AndyFTP 👍
