### ISSUE TITLE
images_reuse_filename: true gives conflicting name to pasted image

### ISSUE THREAD

**Issue by donShakespeare** [tinymce/tinymce#3852]
*Bug?* CDN 4.6.4

1. Expected: When you drag-n-drop image from computer to editor, original filename is maintained. Excellent!
2. Expected but tricky: When you paste image from clipboard, a name is given automatically **image** _.png_

I have a logic that adds a unique suffix to the **image** .png in order not to override server material.

But the only way I know to distinguish pasted image from dragged-in images is:
(is there another method?)
```
if(blobInfo.filename() == "image.png"")
```

**Conflict** occurs when I drag-n-drop a file from my PC that is named *image.png*
**Suggestion:** use proprietary name like **mceImage**.png

Any workarounds?

**Comment by spocke** [comment]
They should be unique per session so your upload script should be able to make it unique if you just generate a unique prefix or folder when the editor loads and upload everything into that? Could you describe the problem a bit more in theory we could try to generate guids but then the filenames would be very long.

**Comment by donShakespeare** [comment]
Thanks for the reply.

But TinyMCE does not have a unique or distinguishing name for pasted image at all. 
`blobInfo.filename()` is always `image.png` when `images_reuse_filename` is set to true.

But when `images_reuse_filename` is set to false then the pasted data `blobInfo.filename()` is rightly set to `mceClip0` or `mceClip1` etc according to session and all.

So it is impossible or maybe difficult when reuse_filename is set to true to identify pasted image versus file dragged-in that is named image.png

Maybe I'm not clear. I'll try and make a small video.

**Comment by donShakespeare** [comment]
Maybe when `images_reuse_filename: true` 
TinyMCE will name pasted images `mceClip.png` (instead of image,png)- then the user can make it unique by timestamp (mceClip_2017_23_34.png)

**Comment by jayarjo** [comment]
@donShakespeare changing filename to `mceClip.png` won't help that much - what if you paste more than one image for example? Then all of them will have a name of `mceClip.png` - how helpful that would be? 

We automatically generate unique filename if blob (dragged or pasted) doesn't contain name property. We could simply ignore name property for pasted images I guess - would that solve the problem?

Do you have `automatic_uploads` set to `true`? That should trigger the upload instantly and you will be able to set any name in your server response.

**Comment by donShakespeare** [comment]
@jayarjo thanks for responding.

1. To your first point.
Is it possible to paste more than one image at once?
If not then we'd be fine, since my script adds a suffix immediately before upload.

2. This might be a chrome issue, but my main point is that the extractedname is always image(.png) when pasting an image.
But this only happens when `reuse_filename: true`, when set to false your uniqueId() kicks in.
I had the belief that a freshly pasted picture cannot have name property, I don't know why mine have the name: image.png ... but this only occurs when `reuse_filename: true ` so I'm suspecting a bug.
I have looked in here
https://github.com/tinymce/tinymce/blob/941a1a0df959f8a12aafc88bf065862cf263bf83/src/plugins/paste/src/main/js/core/Clipboard.js

3. Yes I do have automatic uploads and the logic to rename pasted pictures works perfectly but also gets confused when I drag a picture into the editor that is named `image.png`.
The script I wrote pops a dialogue to rename pasted picture before uploading.
Before the awesome ` reuse_filename` came out, I use to check to see if blobInfo.filename() contained mceclip. But now, blobinfo.filename never contains mceclip when `reuse_filename:true`
So I have to check if `blobinfo.filename == 'image.png'`

**Comment by donShakespeare** [comment]
With a little desperation I think I solved this issue for my purposes (I hope it covers all circumstances - hoping)

```javascript
//tiny plugin to separate pasted from dragged images
editor.on('paste', function() {
  editor.settings.pastedImage = true;
});
editor.on('drop', function() {
  editor.settings.pastedImage = false;
});

//tiny script that interrupts the upload process (as per TinyMCE docs recommendation)
//dragged images that are named "image.png" no longer have the conflict
if((blobInfo.filename() == "image.png" && editor.settings.pastedImage) || blobInfo.filename().substr(0,7) == "mceclip" || blobInfo.filename().substr(0,10) == "imagetools" || blobInfo.filename().substr(0,6) == "blobid"){
  tinymce.activeEditor.windowManager.open({
    title: title,
    onSubmit: imageCallback, //send(formData) only after user has supplied custom name for pasted image
    body: [
      {
        html: msg,
        type: "container",
      }, {
        type: "textbox",
        classes: "tw_image_name",
        value: getImageTempName(blobInfo.name(),blobInfo.filename())
    }]
  });
}
else{
  formData.append('file', blobInfo.blob(), blobInfo.filename());
  xhr.send(formData);
}
``` 

Thanks @spocke and @jayarjo

**Comment by manu37** [comment]
Could this naming come from the local machine? In my case pasted images get named "grafik.png" (WinX64german).

**Comment by donShakespeare** [comment]
Yes @manu37, this was my suspicion. And I think Greenshot is the valuable culprit. It prepares all my print_screen images for me. I will return with facts.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
