### ISSUE TITLE
Cut paste is working like a copy paste

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3858]
Hi,

We are using tinymce and we recently upgraded it to the version 4.6.3 and found that cut paste is now working like copy paste. If we cut one word and paste it then both the words are there .

I verified this in the tinymce demo and it is reproducible there as well.

Can you please take a look at it and suggest me any solution for this.

**Comment by fyrkant** [comment]
Can you [create a fiddle](http://fiddle.tinymce.com/) reproducing this? It is unclear what the problem with the cut and copy functionality is, it seems to work for me.

**Comment by jayarjo** [comment]
I believe 4.6.3 had a problem with the Cut operation invoked from menu. @kaviyarasanaspire does it happen for you in 4.6.5?

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
