### ISSUE TITLE
Uncaught RangeError when selector is `#length`

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#3860]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When `selector` references an element with an id of `#length`, TinyMCE fails to initialize and a RangeError occurs:

```
tinymce.js:48140 Uncaught RangeError: Invalid array length
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

See fiddle: http://fiddle.tinymce.com/mXfaab

**What is the expected behavior?**

The target element is editable.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

All

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by fyrkant** [comment]
Ah no sorry this is still not fixed!

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
