### ISSUE TITLE
No translation for the "Link list" and "Class" within link_plugin

### ISSUE THREAD

**Issue by fr00x** [tinymce/tinymce#3861]
Copied from an old archived bug - still an issue, also for the "Class" label when using the "link_class_list" configuration parameter.

Description of problem:

There is no translation for the "Link List" in the Link Dialog. The Link List field appears not always, but only if the link_list property is set. Possibly, that is why it has no translation. I looked into the language files, the translation is really missing.

Steps to reproduce:

    Use the editor in the German language.
    Specify some links for the property "link_list".
    Call the Link Dialog.

Expected result:

The caption of the Link List field should be in German.

Actual result:

The caption of the Link List field is always in English.

All translation files for all languages should be updated!

**Comment by lnewson** [comment]
Hi,

Thanks for reporting these and looking at both the TinyMCE 4 and 5 translations, these are now included. As such I'll go ahead and close this, but please do let us know if you're still experiencing issues and we'll reopen this.

Thanks!
