### ISSUE TITLE
Formatting like color, background color, bold are not retaining on copy paste

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3862]
Hi,

We recently upgraded the tinymce version to 4.6.3 and formatting like color, background color, bold is not retaining in chrome 60 while copy paste the text inside the same instance.

I can replicate the same problem tinymce demo site as well.

Can anyone please take a look at it and let me know whether this is having any configuration.

**Comment by Luke-SF** [comment]
Same here and it's quite annoying. Here is a demo in which it does not work:
https://codepen.io/anon/pen/WEZaNo
That never copy-pastes correctly in Chrome browsers. It is working for Firefox on that particular demo link but usually it doesn't copy formatting in Firefox either actually.

**Comment by spocke** [comment]
Was only able to reproduce this on Chrome and on that it's a known issue. On Firefox it works correctly for me.
