### ISSUE TITLE
Copy paste the disabled button is pasted in next line

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3863]
Hi,

We are having our customized plugin to insert an disabled button inside the editor, while copy paste the disabled button it is pasted in the next line rather than on the same line. 

I tried this with our source code in the tinymce demo site and it is reproducible there as well.

**Comment by spocke** [comment]
What are the steps to reproduce this can we get a fiddle with some example contents and steps to follow thanks.

**Comment by Afraithe** [comment]
Not enough info.
