### ISSUE TITLE
Minified version of TinyMCE throws JavaScript exception

### ISSUE THREAD

**Issue by speller** [tinymce/tinymce#3867]
I use the following init code:

```
tinymce.init({
	selector: '#' + el.attr('id'),
	theme: 'modern',
	plugins: 'paste lists link code textcolor save',
	menubar: 'edit insert view format tools',
	toolbar: [
		'undo redo | paste | bold italic underline | alignleft aligncenter alignright alignfull | ' +
		'forecolor backcolor | formatselect | code | restoredraft | cancel'
	],
	link_context_toolbar: true,
	relative_urls: false
});
```

When I use uncompressed version of TinyMCE `https://cloud.tinymce.com/stable/tinymce.js?apiKey=key` all work good. But when I use minified version `https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=key` I see exception in the browser console:

```
tinymce.min.js?apiKey=key:40 Uncaught TypeError: a is not a constructor
    at tinymce.min.js?apiKey=key:40
    at tinymce.min.js?apiKey=key:40
    at Object.l [as each] (tinymce.min.js?apiKey=key:40)
    at Object.d [as define] (tinymce.min.js?apiKey=key:40)
    at fingerprint2.min.js:1
```

But editor work fine even with this exception. This issue do not affect user experience but is annoying and can cause problems with JS error reporing tools.

**Comment by spocke** [comment]
I can't seem to reproduce this can you specify what browser you are using?
Also if you clear your cache does it still break?

**Comment by Afraithe** [comment]
Not enough info.
