### ISSUE TITLE
Image caption disables image resizing

### ISSUE THREAD

**Issue by jarilehtinen** [tinymce/tinymce#3869]
Enabling image captions (image_caption: true) seems to disable the image "wysiwyg" resizing tool. We got it working once by randomly clicking the image, so the functionality seems to be there(?). So, it would be nice to be able to resize the image by handles when captions are on.

**Comment by jayarjo** [comment]
@jarilehtinen it is not yet decided how or if we will implement this. However consider such approach: http://fiddle.tinymce.com/SXfaab. 

Notice that image tag is wrapped in `div[data-mce-contenteditable="true"]`. 

I cannot guarantee though that this will continue to work in consequent releases.

**Comment by jarilehtinen** [comment]
@jayarjo That approach works nicely if you have margin/padding around the image. If not, you lose the ability to click/select the whole `figure` element (including `figcaption`) and therefore can't align or delete it.

I can see the difficulties implementing that, especially when the image editing menu is displayed.  Otherwise the resize handles could appear when hovering over `img` and clicking the `img` could select the whole `figure`. Although this would differ from the basic img resizing functionality, but just a thought.

**Comment by jayarjo** [comment]
I'm afraid showing resizing handles on hover won't get implemented. But why would you remove padding/margin - do you have custom styles for captioned image?

**Comment by jarilehtinen** [comment]
Yes, I have custom styles so that the editor area and the final published version looks the same. Of course I could add margins/padding to the editor view (and leave them out from the public version), but universal approach here would be great – one that does not depend on margins/padding.

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
