### ISSUE TITLE
Noneditable loses focus/selection on blur

### ISSUE THREAD

**Issue by dsifford** [tinymce/tinymce#3872]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Clicking a noneditable element (to give it focus, and thereby set the editor's selection as the content of that entire noneditable block) and then clicking outside of tinymce causes both the noneditable block to blur focus AND causes the selection and cursor to move to the bottom of the document.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

(reproducible environment made on request)

**What is the expected behavior?**

Before the last update to noneditable, focus may have been lost on blur, but _not_ the selection. I need the editor's selection to remain the content of the noneditable block and also the editor's cursor to remain in the position it was in before blurring.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest, WordPress. Yes, it worked up until the latest changes (3 months ago I assume) of the noneditable plugin.

**Comment by dsifford** [comment]
To those who also may be affected by this:

I'm currently getting around the issue by keeping a cache of both the previous selection and bookmark triggered by the editor's `focusin` and `focusout` events. 

```ts
interface SelectionCache {
    fresh: boolean;
    selection: string;
    bookmark: {
        id: string;
    };
}
```

When `focusout` is triggered, the cache is updated with both a new bookmark and the content of the selection and the `fresh` property is set to true.

When `focusin` is triggered, the `fresh` property is set to false and fresh selections and/or bookmarks are used instead of cache.

Hope that might help anybody out there.

**Comment by spocke** [comment]
Hmm can't seem to reproduce that issue: http://fiddle.tinymce.com/YXfaab need more details here.

**Comment by dsifford** [comment]
Not sure I understand what you're saying.

I noticed that you're a member of the `core-editor` group in the wordpress slack team. Care to chat there about this? Happy to help where I can.
