### ISSUE TITLE
getContent() not return normally HTML contents

### ISSUE THREAD

**Issue by PanJiaChen** [tinymce/tinymce#3875]
when content has  img such as `<img src="xxx">` 
use `getContent()` will return `<img src="xxx" />` 

it is not normally HTML

**Comment by spocke** [comment]
It is correct the / is optional and we provide them by default to make the documents more of xhtml compliant. Even though that spec is pretty much dead it makes it a lot easier to parse with for example an xml parser. The HTML5 spec allows them here: https://www.w3.org/TR/html51/syntax.html#start-tags
