### ISSUE TITLE
Why you do not add photos directly ?

### ISSUE THREAD

**Issue by thuyettiensinh** [tinymce/tinymce#3876]
I think when someone click the image button should give the user selected files in the PC to upload ?
Why you do not add photos directly ?

**Comment by jayarjo** [comment]
We've added an interface for this in 4.6.5.  Check the fiddle: https://codepen.io/tinymce/pen/xLPoeV

**Comment by jayarjo** [comment]
Related: https://github.com/tinymce/tinymce/issues/3477

**Comment by thuyettiensinh** [comment]
ok, thank you !
