### ISSUE TITLE
Paste not at cursor position - always attached to end of document

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#3881]
**Bug report:**
Paste: is not inserted at cursor position.

**current behavior:**
Paste: data is always attached to the end of document.
http://fiddle.tinymce.com/OXfaab/5

**expected behavior:**
Paste: data must be inserted at cursor position.

**Version:**
Master Version from 17.08.2017 
with paste plugin, 
Browser: chrome

Tiny 4.6.5 is ok!

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
