### ISSUE TITLE
Textarea parsing validation unexpected behaviour

### ISSUE THREAD

**Issue by Shinao** [tinymce/tinymce#3890]
I add forms HTML element in Tinymce, I have no problem with inputs, checkboxes, selects etc... But Textareas behave weirdly

Reproduction by using the demo on https://www.tinymce.com/ and adding via source code :
- Adding `<textarea></textarea>` tinymce makes you think it has been added but if you check the source it's not there.
- Adding either `&nbsp;<textarea></textarea>` or `<textarea>&nbsp;</textarea>` works but now you have either a space behind or in your input
- Adding `&zwnj;` instead of the space works but now you have an invisible character that you can't even see in the source code but it's there

I'm hoping the expected behavior is to allow the first method to be properly accepted by the parser validator.

**Comment by spocke** [comment]
Yes, it should treat textareas like images or input elements meaning content so they shouldn't be removed in this case.
