### ISSUE TITLE
**.css was not loaded because its MIME type, "text/html", is not "text/css"

### ISSUE THREAD

**Issue by kherP** [tinymce/tinymce#3891]
**Do you want to request a *feature* or report a *bug*?**
*bug*?

**What is the current behavior?**
skin folder has been copied but
/skin.min.css was not loaded because its MIME type, “text/html”, is not “text/css”.
/content.min.css was not loaded because its MIME type, “text/html”, is not “text/css”.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
skin and content css should be loaded

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.6.5

**Comment by spocke** [comment]
Reconfigure your server with the right mime types for css. This isn't a tinymce issue but a server configuration issue as far as I can tell. Will re-open if it can be reproduced outside your environment.

**Comment by vctormb** [comment]
I'm facing this issue in tiny v5.

**Comment by davidjb** [comment]
@vctormb See https://github.com/tinymce/tinymce-react/issues/53 -- you need to import the CSS separately in React (e.g. so Webpack picks it up) via an import like:

```jsx
import 'tinymce/skins/ui/oxide/content.inline.min.css'
```

and set `init={{ content_css: false }}` to prevent the attempt at loading `content[.min].css`.
