### ISSUE TITLE
Clicking Justify selecting all the text

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3894]
Hi,

While clicking justify toolbar button is selecting all the text in the line, can anyone please take a look at it and let me this is working as designed or is there any configuration there.

Issue is reproducible in the tinymce demo site as well.

**Comment by spocke** [comment]
Seems to be working in the nightly version so this will be fixed once we make a new release.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
