### ISSUE TITLE
How do I go through Settings to replace 'pt' with 'px'

### ISSUE THREAD

**Issue by MrLiufei** [tinymce/tinymce#3897]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
![image](https://user-images.githubusercontent.com/20437980/29913002-467de2e4-8e66-11e7-88cc-2557ea9243ae.png)

**Comment by fyrkant** [comment]
What version of TinyMCE are you using? 

You can change what the fontsizeselect selection input will show by changing the `fontsize_formats` setting, see this page in the docs: https://www.tinymce.com/docs/configure/content-formatting/#fontsize_formats

Then you could add a list of px sizes instead.
