### ISSUE TITLE
CDN is outdated

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#3898]
https://cdn.tinymce.com/4/tinymce.min.js
https://cdn.tinymce.com/4.6/tinymce.min.js

Can you please update the CDN with the latest version of TinyMCE?
The CDN still serves version 4.6.4 released on 2017-06-13.

**Comment by spocke** [comment]
You can register for a cloud key and use the cloud version.

**Comment by vanillajonathan** [comment]
@spocke I do not wish to register an account and use a cloud key.
I just want to use a good old fashioned CDN.

**Comment by MartinKolarik** [comment]
You can also use https://www.jsdelivr.com/package/npm/tinymce

**Comment by jayarjo** [comment]
Simply increment the version in the url. But in general please do register the key, it's free, but helps us collect some useful stats.

**Comment by vanillajonathan** [comment]
@jayarjo I wish I could increment the version in the URL. But that results in a 403 Forbidden.

/4.6.7/tinymce.min.js results in 403 Forbidden.
I can only use /4.6/tinymce.min.js which is 4.6.4.
