### ISSUE TITLE
editor is not allowing merge fields format.

### ISSUE THREAD

**Issue by santhosh0101** [tinymce/tinymce#3899]
Hi all,

I am facing one issue with the editor when I used merge fields in my code. Below is my code 
```
<table>
<thead>
<tr>
<th><strong>Name</strong></th>
<th><strong>Price</strong></th>
</tr>
</thead>
<tbody>
{{#item.products}}
<tr>
<td>{{name}}</td>
<td>{{price}}</td>
</tr>
{{/item.products}}
</tbody>
</table>
```
When I entered above code in tools ---> source code It is converting it as below
```
<p>{{#item.products}}{{/item.products}}</p>
<table>
<thead>
<tr>
<th><strong>Name</strong></th>
<th><strong>Price</strong></th>
</tr>
</thead>
<tbody>
<tr>
<td>{{name}}</td>
<td>{{price}}</td>
</tr>
</tbody>
</table>
```
I am using the latest version of the editor. I checked in https://www.tinymce.com/ also having the same issue. Any solution for this?

**Comment by spocke** [comment]
You can use the protect: [/\{\{[^\}]+\}\}/g] option to convert them to comments while editing. But tinymce is a html editor not a template editor and that format is not officially supported.
