### ISSUE TITLE
Saving a single editor sets dirty flag for all editors

### ISSUE THREAD

**Issue by dannoe** [tinymce/tinymce#3900]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Saving an editor sets the dirty flag on all other editors too.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/NYfaab/2
- Change both editors.
- Both save buttons are enabled. 
- Save one editor and click inside the other editor. The save button is also disabled.

**What is the expected behavior?**
Saving an editor should only set its own dirty flag. Other editors should not be affected.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Windows 7
TinyMCE 4.6.6
Firefox 55.0 (64bit) 
Firefox 65.0b3 (64bit)
Firefox 65.0b6 (64bit)
Internet Explorer 11 (11.0.9600.18762)

**Comment by dannoe** [comment]
I think I found the problem.  [Plugin.js#L36](https://github.com/tinymce/tinymce/blob/16916f030c103a1b20e3cafc9ee7fd2fdc7ce377/src/plugins/save/src/main/js/Plugin.js#L36)
Is it enough if I replace `EditorManager.triggerSave();` with `editor.save();`?

**Comment by spocke** [comment]
Yes, it should be save.
