### ISSUE TITLE
Line  break is missing when we paste the two lines in source code editor

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3911]
Line  break is missing when we paste the two lines in source code editor.

I have tried with the below content, it is working fine if we paste it in the editor directly, but issue persists when we paste the same content into the source editor.

**Content:**

Space1&nbsp;Space2&nbsp;&nbsp;Space3&nbsp;&nbsp;&nbsp;Space4&nbsp;&nbsp;&nbsp;&nbsp;Space5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Space6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Space7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Space8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Test.
Space1 &nbsp; Space2 &nbsp;&nbsp;Space3&nbsp;&nbsp;&nbsp; Space4&nbsp;&nbsp;&nbsp;&nbsp;Test.

**Comment by spocke** [comment]
What browser are you using? What content is being pasted and from what source?

**Comment by Afraithe** [comment]
Not enough info, closing.
