### ISSUE TITLE
Cannot drag images in Chrome having "paste_data_images: true".

### ISSUE THREAD

**Issue by drumsibumsi** [tinymce/tinymce#3916]
This is a bug report.

Having "paste_data_images" disabled, one can drag images inside of TinyMCE instance. By dragging I mean repositioning of images by mouse.

As soon as "paste_data_images" gets enabled, it becomes impossible to reposition (drag) images by mouse.

How to reproduce:
1. Open standard example https://codepen.io/tinymce/pen/epbRwB
2. Ensure you can drag images by mouse.
3. Add "paste_data_images: true," into JavaScript.
4. Note that you can no longer drag images.

TinyMCE 4.6.5 & 4.6.6 tested.
Chrome Version 60.0.3112.113 (Official Build) (64-bit).

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
