### ISSUE TITLE
how to init multiple tinymce in same page?

### ISSUE THREAD

**Issue by xiranst** [tinymce/tinymce#3917]
Tinymce version: 4.0;
Browser: Firefox 55(64 bit)

in the page, the tinymce is inited when page is loading and then the selector editor is called "template-editor", working for me. there have many div called "template-editor".
the this page, i set a popup windows when click a button. in the popup windows, the selector is called "tinymce". the tinymce of popup is displaying at first. if click the button and open the popup again, the tinymce editor is not displaying.

Then, i added tinymce.remove() in the click event function when open popup windows. the tinymce is always displaying each click. But some "template-editor" selector are not working for me now, another "template-editor" are still working.

so, how to do it? i want to use tinymce.get(id).remove replace the tinymce.remove(), but it is not working for me.

**Comment by fyrkant** [comment]
Can you create a [fiddle](http://fiddle.tinymce.com/) reproducing the problem so we can get a better idea of what is wrong?

**Comment by Afraithe** [comment]
Not enough info.
