### ISSUE TITLE
reverse tab navigation on Modal dialogs with Tabs get stuck in loop

### ISSUE THREAD

**Issue by bkirkby** [tinymce/tinymce#3922]
when on a modal dialog with separate tabs (Table Properties), if you reverse-tab (SHIFT-TAB), you will toggle between the last Tab and the first item in the displayed tab.

steps to reproduce:
1. open TableProperties
2. hit SHIFT-TAB to bounce between the "Advanced" Tab header and the "Cols" input field.

i would expect that you would be able to reverse tab navigate through the whole modal dialog

tested on tinymce version 4.6.6 on both Chrome and Safari

**Comment by fyrkant** [comment]
When you have focus on the tab row you can switch between the available tabs with the arrow keys,  but what you want is tab to jump through all focusable things?

**Comment by bkirkby** [comment]
it's more an accessibility thing. think about if you were a sightless user. there are actually two separate issues with accessibility here:

1. as described, if i reverse-tab repeatedly i get stuck in a loop without being able to reverse-tab through the page.

2. if i tab through the "General" tab, it can cycle through just fine. but if i reverse tab, i actually tab onto the "Advanced" tab button instead of the "General" tab button where i just came from. that is very confusing to sight-impaired users.

thanks!

**Comment by hashtagbang** [comment]
@fyrkant - can you comment on if this should be an accessibility bug, we have been flagged on this in an accessibility audit. Would like to understand if you interpret it different?

**Comment by hashtagbang** [comment]
@fyrkant - to answer your question above (I work with @bkirkby), Yes, we do want to be able to tab to jump through all focusable things as defined here https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html

**Comment by lnewson** [comment]
Hi,

I've tested this using TinyMCE 5.2.2 and can confirm this issue has been resolved in TinyMCE 5.  We did an entire overhaul on the UI for TinyMCE 5 with a much larger focus on accessibility. You should now be able to reverse cycle through any focusable elements in the same order as normal cycling. If you can still reproduce this issue in TinyMCE 5, please let us know and we'll investigate.

Thanks!
