### ISSUE TITLE
Shortcuts Ctrl+A and Ctrl+C do not work in IE

### ISSUE THREAD

**Issue by radekdostal** [tinymce/tinymce#3923]
Ctrl+A and Ctrl+C do nothing in IE (tested on Windows 10) since v4.6.4.

**Comment by fyrkant** [comment]
I can't reproduce this, can you create a [fiddle](http://fiddle.tinymce.com/) showing the problem?

**Comment by radekdostal** [comment]
It's amazing. [This fiddle](http://fiddle.tinymce.com/WZfaab) works in IE. But my really application with the same code doesn't. Edge is OK. FF is OK.

**Comment by radekdostal** [comment]
Other my application which uses Bootstrap v3 works fine.

**Comment by radekdostal** [comment]
In the preview window shortcuts work correctly.

**Comment by fyrkant** [comment]
I think it has to have something to do with your code or maybe css around tinymce that causes this problem.

**Comment by radekdostal** [comment]
Ok, thank you.
