### ISSUE TITLE
TypeError: top.tinymce.activeEditor.windowManager.getParams(...).setUrl is not a function

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#3928]
**Do you want to request a *feature* or report a *bug*?**
Report

**What is the current behavior?**
TypeError: top.tinymce.activeEditor.windowManager.getParams(...).setUrl is not a function

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
no js error

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version 4.6.7 tinymce.min.js no CDN all browsers
![2017-09-18_143442](https://user-images.githubusercontent.com/1576475/30542167-87fdd7da-9c7e-11e7-90d7-717a5caa8a6e.jpg)

**Comment by Afraithe** [comment]
This doesn't seem entirely related to TinyMCE, or at least it doesn't have enough info, closing.
