### ISSUE TITLE
Cut: only last letter is clipped (Android)

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#3933]
**Bug:** 
Cut: only last letter is clipped

**current behavior:**
Cut: selected word is copied to clipboard (ok), 
but only last letter of selected word is clipped.

(only buggy with Android systemcontrol for cut, 
shortcuts Ctrl X is OK!)

http://fiddle.tinymce.com/0agaab/1

**expected behavior:**
Cut: selection is copied to clipboard, 
and whole selection is cut out.

**Version:**
Tiny 4.6.7 

with paste plugin,
Chrome on Android (7.0 - 8.0)

**Comment by Georg-Git** [comment]
**Tiny 4.1.10** : last version without this bug.

**Comment by Georg-Git** [comment]
**Tiny 4.1.10** : last version without this bug.

**Comment by archon810** [comment]
Is this fixable before v4 goes EOL please?

**Comment by reactmore** [comment]
Is there a new update regarding this issue? I tried upgrading it to version 5 stable but still getting the same issue,

but in incognito mode this does not happen.

I've tried adding version when calling tinymce.min.js?v=5 but it doesn't change anything

**Comment by Georg-Git** [comment]
EOL of v4 was December 31, 2020.

This Bug was fixed in v5, check fiddle with last v5 version:
[https://fiddle.tiny.cloud/Ofiaab](https://fiddle.tiny.cloud/Ofiaab)

And v6 is also OK.

=> I will close this issue
