### ISSUE TITLE
Rename jquery.tinymce.js in tinymce-dist

### ISSUE THREAD

**Issue by pribilinskiy** [tinymce/tinymce#3934]
In https://github.com/tinymce/tinymce-dist there are:
`jquery.tinymce.js` and 
`tinymce.jquery.js`.

@spocke Are you serious?

That brings some confusion, agree?

![image](https://user-images.githubusercontent.com/3078595/30628568-c7e8a7a0-9ddf-11e7-975b-4c5379e69865.png)

**Comment by spocke** [comment]
Yes, we might remove this in the upcoming 4.7.0 version since we are already having a console message about not using the tinymce.jquery.js version.

**Comment by pribilinskiy** [comment]
Great!

**Comment by tinydylan** [comment]
It looks like this has been fixed - https://github.com/tinymce/tinymce-dist no longer has tinymce.jquery.js or tinymce.jquery.min.js
