### ISSUE TITLE
increase indent button gets disable while bulletining is applyed #2063

### ISSUE THREAD

**Issue by abhinav-nehra** [tinymce/tinymce#3935]
Description of problem:

Steps to reproduce:
1.go to the http://www.tinymce.com/tryit/classic.php
2.type one line
3.press enter.
4.select any bullet.

Expected result: increase indent button should not be get disabled

Actual result: increase indent button is gets disable.

Legacy information imported from TinyMCE bug tracker:

#T7337 posted by snehal1112

Tags: []
Status: Open
Resolution: None
Attached URL: none

**Comment by fyrkant** [comment]
Hmm, what is the point of this? Have you copied an old issue? The link does not even work any more, so if you still have a problem can you create a [fiddle](http://fiddle.tinymce.com/) reproducing it?
