### ISSUE TITLE
TD tags appearing in THEAD instead of TH tags

### ISSUE THREAD

**Issue by GeertGuns** [tinymce/tinymce#3941]
Hi,

I'm using TinyMCE v4.6.5 and i'm having a problem with the generated tables.
I insert a table and set the first row as a header.
But the generated code contains `<td>` tags in the `<thead>` tag instead of `<th>` tags.

The same problem had already been reported and was marked solved for TinyMCE v4.4.0, but I guess it reappeared in a later version.
Original post: https://github.com/tinymce/tinymce/issues/1726
I'm opening a new post because the old one was closed.

Could you please take a look at this?

The generated code is as follows and can also be reproduces on the TinyMCE demo site . 
As you can see, the thead row still contains td tags in stead of th tags.

```
<table class="table">
<thead>
<tr>
<td>test</td>
<td>header</td>
<td>line</td>
<td> </td>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">header cell</th>
<td>body</td>
<td>line1</td>
<td> </td>
</tr>
<tr>
<td> </td>
<td> </td>
<td>line2</td>
<td> </td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
</tr>
</tbody>
<tfoot>
<tr>
<td>test</td>
<td>footer</td>
<td>line</td>
<td> </td>
</tr>
</tfoot>
</table>
```

However setting a cell as a 'header', works as it should.
(ex: `<th scope="row">header cell</th>`)

Kind regards,
Geert

**Comment by noraab** [comment]
This is still present in current TinyMCE 5.0.14.
Is there any plan to fix it sometime?

**Comment by vincenzo-mennella** [comment]
Same problem here. Any plan to fix this? Any suggestions or workarounds?

**Comment by adrian36974** [comment]
Hi, i have a fix for the problem.
Table node is created in Ui function in plugins/table/plugin.min.js, here's the solution:

`function Ui(e, n, t, r, o) {
    void 0 === o && (o = $c);
    var i = un.fromTag("table");
    oe(i, o.styles), V(i, o.attributes);
    var v = un.fromTag("thead");
    _n(i, v);
    var u = un.fromTag("tbody");
    _n(i, u);
    for (var h = [], b = [], a = 0; a < e; a++) {
        for (var l = un.fromTag("tr"), f = 0; f < n; f++) {
            var s = a < t || f < r || a == 0 ? un.fromTag("th") : un.fromTag("td");
            f < r && q(s, "scope", "row"), a < t && q(s, "scope", "col"), _n(s, un.fromTag("br")), o.percentages && re(s, "width", 100 / n + "%"), _n(l, s)
        }
        a == 0 ? h.push(l) : b.push(l);
    }
    return Ee(v, h), Ee(u, b), i
}`
First create a thead elemente and attach to table, in the for of the tr elements, i modify the condition if are the first tr, then create a th element instead of td element, and add other condition after the second for, to push the elements tr elements to h(head array) or b(body array).

And finally in the return add the v element(thead).
