### ISSUE TITLE
Key Commands to Invoke Super and Sub Script Formats

### ISSUE THREAD

**Issue by b3smith13** [tinymce/tinymce#3943]
Just as the title says, it would be amazing if we could add Key Commands to Invoke Super and Sub Script Formats to the TinyMCE editor. I know a lot of people who do data entry via WordPress who this would help immensely day to day.

Thanks!

**Comment by fyrkant** [comment]
You can execute the `subscript` and `superscript` commands to do this.

**Comment by fyrkant** [comment]
See this fiddle for demo: http://fiddle.tinymce.com/Oagaab

**Comment by b3smith13** [comment]
Awesome, many thanks!
