### ISSUE TITLE
Format select changes the font style

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3949]
Hi,
While selection "Heading1" in format select , font family is changing into the unspecified format like it is changed into "aileron" which is not in the font family dropdown list.

Can anyone please provide me the solution.

**Comment by jayarjo** [comment]
Could you please provide a [fiddle](http://fiddle.tinymce.com) demonstrating the problem. And also outline the steps to reproduce?

**Comment by fyrkant** [comment]
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.
