### ISSUE TITLE
Firefox/IE: formats: code: text in next line inserted outside code-tag

### ISSUE THREAD

**Issue by IProbablyFoundABug** [tinymce/tinymce#3950]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using the code format (Formats - Inline - Code), after a pressing enter, newly inserted text in the following line gets inserted outside the `<code>`-tag, but there still remains an empty  `<code>`-tag.

**What is the expected behavior?**
Same behaviour as in Chrome/Opera: text in new line gets inserted inside the `<code>`-tag

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.6.7 (and older), it seems only Firefox and IE10 are affected. Cannot test MS Edge.

**Comment by spocke** [comment]
Use the codesample plugin if you want to have blocks of code. Code is a inline format element so pressing enter inside it won't create a linebreak inside it. Closing this one since it can be resolved by using another plugin.
