### ISSUE TITLE
Double Space in the URL field automatically adds a period

### ISSUE THREAD

**Issue by Schenn** [tinymce/tinymce#3956]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behavior?**
When you are inserting a link into the URL field of the inset link popup, hitting the spacebar twice will automatically add a "." character. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

In the editor, click the insert link button to bring up the modal.
Enter an address in the url field, then hit the spacebar twice.
-- NOTE -- the bug doesn't occur if you wait between entering spaces. This is a "double space" effect.
Notice that TinyMCE automatically "ended the sentence" for a field which doesn't require grammar rules.

**What is the expected behavior?**
The spaces are preserved and no grammar rules are applied to the string which is entered into a URL field.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

All. No.

**Comment by jayarjo** [comment]
I'm not able to reproduce this. Can you record the gif/video of the issue in action?

**Comment by Schenn** [comment]
I'll try to get that to you, but it happens reliably for me on https://www.tinymce.com/

OSX 10, Chrome latest

**Comment by Schenn** [comment]
https://www.dropbox.com/s/uvyr6os5zm35qq1/tinymce%20doublespace%20issue.mov?dl=0

**Comment by fyrkant** [comment]
This is a setting in MacOS, turn if off in System Preferences => Keyboard => Text => Uncheck "Add period with double-space"

**Comment by Schenn** [comment]
Thanks, sorry for wasting your time
