### ISSUE TITLE
[TinyMCE 4.6.7] Italian Language Pack mistake

### ISSUE THREAD

**Issue by Ripper184** [tinymce/tinymce#3962]
There is a mistake inside "it.js" file. 

`"Dimensions": "Dimenzioni",` should be `"Dimensions": "Dimensioni"`.

Can it be fixed ?

**Comment by fyrkant** [comment]
You can visit the [TinyMCE page on Transifex](https://www.transifex.com/projects/p/tinymce/) to add or edit translations.

**Comment by Ripper184** [comment]
Hi,

I tried to Transiflex but after 2 mails (to spocke and Moxiecode), there is neither answer or change.
This pb has been alerted on transiflex 4 years ago and 2 years ago but nothing was done.

So how can it be fixed because I can change it locally, the worst method, but every updates clear my changes ?

**Comment by fyrkant** [comment]
I checked it out on transifex and think I approved the change, so it should be updated soon I think (although it takes a while before the zip downloads on the page is updated).

**Comment by Ripper184** [comment]
Thank you
