### ISSUE TITLE
[Ipad][tinymce version 4.6.6] Issue with updating format of text in Table

### ISSUE THREAD

**Issue by wza87** [tinymce/tinymce#3963]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
a. Add a table with at least 5 columns 
b. In the 1st row, for each cell, highlight the text and select a format e.g. Heading 1
c. Use a different format for the next cell 
d. The cursor jumps to the previous cell and updates the formatting of the text in that previous cell. The previously selected text remains unchanged. 

below is the video link for the issue i encounter:
https://www.dropbox.com/s/6ln6lt422ysasuv/tinymce%20ipad%20table%20issue.MOV?dl=0

**What is the expected behavior?**
The text in currently selected cell should be updated.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce version 4.6.5 and 4.6.6 in iPad mini. It works in Desktop computer (Chrome, IE etc).

**Comment by Georg-Git** [comment]
Same problem also with paste not done at cursor position but in other cell.
And even worse with Tiny 4.7.0.

iPad mini

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by wza87** [comment]
Hi,

We are still able to reproduce this issue in iPad, and also find out the chrome browser.

issue in chrome:
https://www.dropbox.com/s/kdfvsyox1rp7x60/wiris%20formatting%20issue%20in%20Chrome.mp4?dl=0

issue in iPad:
https://www.dropbox.com/s/vtoulptif1y7o04/wiris%20formatting%20issue%20in%20iPad.mp4?dl=0
