### ISSUE TITLE
Tinymce 4.7.0 Table of Contents causing error

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#3966]
Installed fresh download version 4.7.0. Nothing seems to work anymore (no CDN)

TypeError: a.schema is undefined plugin.min.js (line 1, col 1140)
TypeError: c is undefined tinymce.min.js (line 1, col 192976)
TypeError: f is undefined theme.min.js (line 1, col 29426)
TypeError: f is undefined theme.min.js (line 1, col 29426)
2 TypeError: a.getBody(...) is null plugin.min.js (line 1, col 2299)
TypeError: f is undefined theme.min.js (line 1, col 29426)
3 TypeError: a.getBody(...) is null plugin.min.js (line 1, col 2299)

**Comment by spocke** [comment]
Did you update all files also did you clear the browser cache. We did some restructuring internally between themes and the core so if the core is out of date from the theme or plugins you need to update those.

**Comment by cfconsultancy** [comment]
Yup, used ff with cache disabled. All files replaced

**Comment by spocke** [comment]
We are not seeing the same issue anywhere works fine here: http://fiddle.tinymce.com/ for example.

**Comment by spocke** [comment]
What happens if you use the non minified files? Is there some test url that you can setup in case it can't be reproduced on fiddle.tinymce.com also what browser are you using?

**Comment by cfconsultancy** [comment]
I think I found the problem. After removing the toc plugin, everything works.

**Comment by spocke** [comment]
Could you send me the tinymce init plugin order you used?

**Comment by cfconsultancy** [comment]
`                tinymce.init({
                  selector: "textarea.editme",
                  theme: 'modern',
                  //skin: 'lightgray',
                  width: '100%',
                  height: 370,
                  language : '<?php echo substr($language, 0, 2);?>',
                  menubar: false,
                  //toolbar_items_size: 'small',
                  autosave_restore_when_empty: false,
                  save_enablewhendirty: false,
                  content_css : ['<?php echo $site_subdir . $editor_css ?>'],
                  save_onsavecallback: function() { save(); },
                  save_oncancelcallback: function() { <?php echo $cancel_action ?> },
                  image_advtab: false,
                  convert_urls: false,
                  convert_fonts_to_spans : true,
                  paste_remove_styles : true,
                  table_grid: true,
				  branding: false,
				  //image_title: true,
				  //image_caption: true,
                  image_description: true,
                  media_filter_html: false,
                  //allow_script_urls: true,
                  //extended_valid_elements: "a[href|target|onclick|title|rel|class]",
                  end_container_on_empty_block: true,
				  table_default_attributes: {
					class: 'responsivetable'
				  },
				  //images_upload_url: 'class-tinymceupload.php',

                  //forced_root_block:false,
                  //force_br_newlines : true,
                  //force_p_newlines : false,

                  advlist_number_styles: "default,lower-alpha,upper-alpha", //string with some combination of (comma seperated): default,lower-alpha,lower-greek,lower-roman,upper-alpha,upper-roman
                  link_list: './tinymce/plugins/links.php',
                              external_filemanager_path:"./tinymce/filemanager/",
                              filemanager_title:"Filemanager",
                              external_plugins: { "filemanager" : "<?php echo $site_subdir;?>/cms/tinymce/filemanager/plugin.min.js" },
                  rel_list: [
                            {title: 'None', value: ''},
                            {title: 'Lightbox', value: 'plaatjes'},
							{title: 'Rel nofollow', value: 'nofollow'}
                      ],
                      plugins: [
                          "advlist autosave autolink lists link image lists charmap preview hr anchor codemirror toc insertdatetime",
                          "fullscreen nonbreaking wordcount save table contextmenu visualblocks <?php if ($color_editor == 1) {?>textcolor<?php }?>",
                          "paste table responsivefilemanager searchreplace youtube qrcode picasa lorumipsum colorpicker",
                      ],
                  	style_formats: [
                              //{title: 'Image Left', selector : 'img',classes: 'imglinks'},
                              //{title: 'Image Right', selector : 'img',classes: 'imgrechts'},
                              //{title: 'Youtube links', inline : 'span',styles: {'float' : 'left','margin': '5px 10px 10px 0'}},
                              //{title: 'Youtube rechts', inline : 'span',styles: {'float' : 'right','margin': '5px 0 10px 10px'}},
                              //{title: 'Youtube links', inline : 'span',classes: 'youtubelinks'},
                              //{title: 'Youtube rechts', inline : 'span',classes: 'youtuberechts'},
                              {title: 'Table color', selector: 'table', classes: 'tablerow'},
                              {title: 'Table color no border', selector: 'table', classes: 'tablerow1'},
                              {title: 'Table Align Top', selector: 'table', classes: 'tabletop'},
                              {title: 'P text top', selector: 'p', classes: 'ptop'}
                      ],
                      formats:{
                              alignleft : [
                                      {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,span', styles : {textAlign : 'left'}},
                                      {selector : 'img,table', classes : 'imglinks'}
                              ],
                              aligncenter : [
                                      {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,span', styles : {textAlign : 'center'}},
                                      {selector : 'img,table', classes : 'aligncenter'}
                              ],
                              alignright : [
                                      {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,span', styles : {textAlign : 'right'}},
                                      {selector : 'img,table', classes : 'imgrechts'}
                              ],
                              strikethrough : {inline : 'del'}
                      },
					  codemirror: {
						  indentOnInit: true,    // Whether or not to indent code on init.
						  path: 'codemirror-5.2', // Path to CodeMirror distribution
						  config: {               // CodeMirror config object
						     mode: 'htmlmixed',
						     lineNumbers: true,
							 indentUnit: 3,
							 tabSize: 3,
						     foldGutter: true
						  }
					  },
                      toolbar1: "save cancel preview fullscreen | cut copy paste | undo redo | alignleft aligncenter alignright alignjustify bullist numlist | outdent indent",
                      toolbar2: "styleselect formatselect | bold italic blockquote | <?php if ($color_editor == 1) {?>forecolor backcolor |<?php }?> underline strikethrough | image link unlink anchor | hr insertdatetime restoredraft code",
                      toolbar3: "removeformat visualblocks searchreplace | table | toc | charmap | plugins <?php if ($widgeteditor == 1) {?>widgets<?php }?> <?php if ($timetableadmin == 1) {?>timetable<?php }?> youtube picasa qrcode lorumipsum <?php if ($albumadmin == 1) {?>albums<?php }?> tags",
                      setup: function(editor) {
                              editor.addButton('plugins', {
                                  type: 'menubutton',
                                  text: 'Plugin',
                                  menu: [
                                      {text: 'Youtube video small', onclick: function() {editor.insertContent('[youtube]Hier de code[/youtube]');}},
                                      <?php if ($youtubelijst == 1) {?>{text: 'Youtube lijst', onclick: function() {editor.insertContent('[youtubelijst=keywords]Hier de trefwoorden[/youtubelijst]');}},<?php }?>
                                      {text: 'Twitter', onclick: function() {editor.insertContent('[twitter max=3 cache=1]Hier de twitternaam[/twitter]');}},
									  {text: 'Facebook', onclick: function() {editor.insertContent('[facebook]Hier gebruikesnaam[/facebook]');}},
                                      {text: 'Vimeo', onclick: function() {editor.insertContent('[vimeo]Hier de video code[/vimeo]');}},
									  {text: 'FAQ', onclick: function() {editor.insertContent('[faqtitel]Titel tekst[/faqtitel][faqvervolg]Beschrijving FAQ tekst[/faqvervolg]');}},
                                      {text: 'RSSfeed', onclick: function() {editor.insertContent('[rss search=0 cache=1 tl=200 dl=300 aantal=6 output=1]Hier de url![/rss]');}},
									  {text: 'Aanmeldformulier', onclick: function() {editor.insertContent('[MODULE:aanmelden]');}}
                                  ]
                              });
                              editor.addButton('tags', {
                                  type: 'menubutton',
                                  text: 'Tags',
                                  menu: [
                                      {text: 'Twitter', onclick: function() {editor.insertContent('<strong>Tags:</strong> tweets,tweet,twitter');}},
                                      {text: 'Pinterest', onclick: function() {editor.insertContent('<strong>Tags:</strong> pinterest,pinit,pin');}},
									  {text: 'Facebook', onclick: function() {editor.insertContent('<strong>Tags:</strong> facebook,socialmedia,tips');}},
									  {text: 'LinkedIn', onclick: function() {editor.insertContent('<strong>Tags:</strong> LinkedIn,connecties,zakelijk,relationship');}},
									  {text: 'Google', onclick: function() {editor.insertContent('<strong>Tags:</strong> Google,Google+,Zoekmachine');}},
									  {text: 'SEO', onclick: function() {editor.insertContent('<strong>Tags:</strong> SEO,zoekmachineoptimalisatie,marketing');}},
									  {text: 'Website', onclick: function() {editor.insertContent('<strong>Tags:</strong> website,tips,visitekaartje');}}
                                  ]
                              });
                          	  // Widget button
                              editor.addButton('widgets', {
                              text: '',
                              icon: true,
                                  title: 'Widgets',
                                  image: './css/images/cog2.png',
                                  onclick: function() {
                                      // Open window
                                      editor.windowManager.open({
                                          title: 'Widgets',
                                          width: 450,
                                          height: 120,
                                          body: [
                                              {type: 'listbox', name: 'widgets', label: 'widgets', values: [
                                          {'text':'Select','value':''},
                                          	<?php
                                          	//Widgets
                                          	if ($widget = 1) {
                                          		$queryw = "SELECT `title`, `id` FROM `" . $mysql_table_prefix . "widgets` ORDER BY title ASC";
                                          		$resultw = mysqli_query($cms_mysql_connection, $queryw);
                                          		while ($pagew = mysqli_fetch_object($resultw)) {
                                          			echo "{text: '" . str_replace("'", "\\'", $pagew->title) . "', value: '[widget name=" . str_replace("'", "\\'", $pagew->title) . "]" . $pagew->id . "[/widget]'},";
                                          		}
                                          	}
                                          	?>
                                          ]}
                                          ],
                                          onsubmit: function(e) {
                                          // Insert content when the window form is submitted
                                          if(e.data.widgets === false){
                                          return;
                                          }
                                              editor.insertContent(e.data.widgets);
                                          }
                                      });
                                  }
                              });

                              // albums button
                              editor.addButton('albums', {
                                  type: 'menubutton',
                                  text: 'Albums',
                                  menu: [
                                  	<?php
                                  	//albums
                                  	if ($albumadmin = 1) {
										$albumdir = "../images/album/";
										foreach(glob($albumdir.'*', GLOB_ONLYDIR) as $dir) {
										    $dirname = basename($dir);
                                         		echo "{text: '" . str_replace("_", " ", $dirname) . "', onclick: function() {editor.insertContent('[MODULE:gallery:" . $dirname . "]');}},";
										}
									}
                                  	?>
                              ]
                              });

                              // Timetable button
                              editor.addButton('timetable', {
                                  type: 'menubutton',
                                  text: 'Timetable',
                                  menu: [
                                  	<?php
                                  	//Timetable
                                  	if ($timetableadmin = 1) {
                                  		$queryt = 'SELECT * FROM `' . $mysql_table_prefix . 'timetable` ORDER BY `title` ASC';
                                  		$resultt = mysqli_query($cms_mysql_connection, $queryt);
                                  		while ($paget = mysqli_fetch_object($resultt)) {
                                  			echo " {text: '" . str_replace("'", "\\'", $paget->title) . "', onclick: function() {editor.insertContent('[timetable=100%]" . $paget->id . "[/timetable]');}},";
                                  		}
                                  	}
                                  	?>
                              ]
                              });
                          }
                });
                </script>`

**Comment by cfconsultancy** [comment]
Used the non minified version now
js error in plugin toc

`TypeError: editor.schema is undefined`

So it must be here 
`var isValid = tagName ? editor.schema.isValidChild('div', tagName) : false; `
but I don't know how to solve that

**Comment by Afraithe** [comment]
So you only get an error if your using the Table of Contents plugin? If you disable it, everything works fine?

**Comment by cfconsultancy** [comment]
Just add the toc plugin and you will see the error

<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste toc"
    ],
    toolbar: "toc insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>`
`

**Comment by Afraithe** [comment]
Thanks, changed the title to reflect the issue, here is the fiddle, we are looking into it.

http://fiddle.tinymce.com/9bgaab

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
