### ISSUE TITLE
[4.7.0] Menu item Preview not removed as expected

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#3969]
**Bug:** Menu item **Preview** doubled

**current behavior:**
Menu item **Preview**: 
in menu **File** AND in menu **View**. 

**expected behavior:**
Menu item **Preview** only in menu **View**. 

**Version:**
Tiny 4.7.0: Preview doubled
Tiny 4.6.7: OK 

with preview plugin

http://fiddle.tinymce.com/0agaab/2

**Comment by spocke** [comment]
This is by design google docs have duplicated menu items as well this is quite common since it's based on context.

**Comment by Georg-Git** [comment]
I had presumed getting this answer.  ;-)

But however the following behavior is not by design, isn't it?:
http://fiddle.tinymce.com/0agaab/13

**Comment by androb** [comment]
Confirmed, updated the bug description to reflect that problem

**Comment by Georg-Git** [comment]
@androb: Oh - sorry - this is a missunderstanding.
I used this "bug" as a feature to show the preview item only in menu view.
;-)

And another change in the menu of 4.7.0 makes me happy, because I do not have to patch the code plugin anymore to move the item "Source code" from "Tools" to the "View" menu - the new place under "View" is really a improvement for me.

@spocke : 
But placing "Source code" under "View" is not correct based on the context, because the plugin "Source code" is a Source-code **Editor**.
So "Source code" has to be placed under "**Edit**"....

I am joking.

The whole thread under this issue is a joke related to the still open issues.

I do not understand the priorities of the tiny team concerning the open issues.
Tiny claims to be a HMTL Editor.
But there are some Issues attesting Tiny to prevent users from editing the content in a proper way. 
And most of this issues are verified and even flagged as escalated.

The best example is an issue from **November 2016!**.
Since opening of this issue we have seen roundabout 16 new releases - but this issue is still open:
#3352 **_"its not possible to edit the first Letter in a span-block"_**

=> place the menu items whereever You want - 
for me it is more important to edit HTML code in a proper way.

**Comment by Georg-Git** [comment]
4.7.1: OK
