### ISSUE TITLE
Styles dropdown text should be inverted with the new styling

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#3972]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When you hover over a style (e.g. Heading 1) in the styles drop-down, it is black on dark grey and not readable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/tinymce/live/gGRYKN

**What is the expected behavior?**
It should be white text on the dark grey background.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version 4.7

![image](https://user-images.githubusercontent.com/2160304/31151212-477818be-a84b-11e7-849b-1a70d3ddb8ed.png)

**Comment by androb** [comment]
This is even worse in our online demos:

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
