### ISSUE TITLE
Pasting Images allowed with or without paste_data_images: false

### ISSUE THREAD

**Issue by jdlindsey11** [tinymce/tinymce#3975]
*This is presumed to be a bug*

**What is the current behavior?**
When trying to paste an image in, it should not be allowed. However, i am able to paste an image in directly since updating to version 4.7

**Use the following fiddle example and paste an image in:**
http://fiddle.tinymce.com/8bgaab

**What is the expected behavior?**
The image should not be allowed to be pasted in. Per my understanding.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I am using Windows, Chrome and TinyMCE 4.7. This worked around version 4.2 of TinyMCE

**Comment by Afraithe** [comment]
This is the same as #3970

**Comment by spocke** [comment]
Hmm, can't seem to reproduce this. I tested pasting both a image file and image data from ms paint none of those methods inserts an image. Could you expand on how you are pasting images in?

**Comment by jdlindsey11** [comment]
I am copying an image from the web and pasting into the editor

**Comment by spocke** [comment]
Right yeah if it's a image url in html to some other site then it's not blocked data is for base64 images basically.

**Comment by jdlindsey11** [comment]
I will look into the paste_preprocess for that then

**Comment by jayarjo** [comment]
Data part in the settings name - `paste_data_images` , hints to just that. It only blocks data urls. I think this can be closed.
