### ISSUE TITLE
STOP REMOVING TAGS IN HTML

### ISSUE THREAD

**Issue by Tectract** [tinymce/tinymce#3977]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Some HTML tags are removed when switching between "visual" and "text" editors, and upon publishing of pages using TinyMCE editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
You all know what I'm talking about

**What is the expected behavior?**
STOP MESSING WITH MY HTML!!! I NEVER ASKED FOR THIS!!!

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by androb** [comment]
Thanks for writing this @Tectract but we probably need more information if we are going to change the behavior. Also, a lot of the filtering behavior is handled by WordPress itself - not TinyMCE. If you can replicate it on fiddle.tinymce.com, it could be TinyMCE and we can look at it. If not, it is probably WordPress.

There is a whole new editor coming to WordPress that you may want to check out. It is called Gutenberg and I'd be curious for you to try it and see if it meets your needs better (we are on the project.)
https://wordpress.org/plugins/gutenberg/

As there is no actionable content in this report, I am going to close it. But feel free to reopen it if you have more information.

**Comment by Tectract** [comment]
removeformat in tinymce.min.js.

Why are you deciding which of my stuff to remove? Stop that.
