### ISSUE TITLE
[4.7.0] Mobile stylesheet references missing URL

### ISSUE THREAD

**Issue by wmorrell** [tinymce/tinymce#3978]
**Do you want to request a *feature* or report a *bug*?**
Minor bug.

**What is the current behavior?**
The default lightgrey skin references in the skin.mobile.min.css file `url(../icons/tinymce-logo2.svg)`. The file at that path does not exist.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Install tinymce==4.7.0 from npm;
try to use css-loader to package styles;
webpack will emit warning that there is no file found for `../icons/tinymce-logo2.svg`

**What is the expected behavior?**
All necessary assets be included in the package :)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
The mobile stylesheet file appears to be new in 2.7.0.

**Comment by esomkin** [comment]
Bug is also actual in 4.7.1 version.

**Comment by mtparet** [comment]
When compiling in production, webpack fails to compile tinymce because of this error.
