### ISSUE TITLE
Right click pasting plain text is not working

### ISSUE THREAD

**Issue by denissonpaz** [tinymce/tinymce#3979]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Right click pasting a plain text is rasing the error: 

_plugin.min.js:1 Uncaught TypeError: Cannot read property 'innerHTML' of undefined
    at Object.i [as getHtml] (plugin.min.js:1)
    at a (plugin.min.js:1)
    at plugin.min.js:1
    at tinymce.min.js?apiKey=3weyqo4xrgnlbqixqznhhu3bpg0ut61dul9qv448kde8oym9:8_

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Steps to Reproduce:
1. Copy any plain text
2. Right click on the Editor and click on Paste
3. Nothing is gonna happen
4. Open the Developer Tool to see the error

Tested in: Chrome and Safari (Windows 10 and MacOS)
Plugin: Paste

**Comment by spocke** [comment]
I can't seem to reproduce this could you setup a fiddle. I can paste fine when I have the contextmenu disabled or do paste need to be configured into that?

**Comment by denissonpaz** [comment]
I have set the **paste** plugin and the **paste** menu
The text has to be plain. Copy it from notepad, for example, or the browser address input.
I just used the context menu to paste it.

it seems that the paste plugin (https://www.tinymce.com/docs/plugins/paste/) is trying to get the property "innerHTML" from a text that is not a HTML element.

![pasteplaintext](https://user-images.githubusercontent.com/19151186/31278844-9ffce778-aa74-11e7-9ec2-b32d3f815966.png)

**Comment by denissonpaz** [comment]
In order to reproduce it, go to https://codepen.io/tinymce/pen/epbjzO , remove the plugin "**contextmenu**" and try to paste a plain text. I just did it right now and got the same error:
![image](https://user-images.githubusercontent.com/19151186/31279129-de6220cc-aa75-11e7-8115-1e9712a8762f.png)

**Comment by spocke** [comment]
This one has already been fixed in the 4.7.0 release however I think we missed adding that to the changelog. So if you could help us verify it after upgrading to 4.7.0 I can no longer reproduce the issue. Thanks.

**Comment by denissonpaz** [comment]
Thank you spocke, using the version 4.7.0 is working fine. I've been using the stable version. I'm gonna change it. Thanks a lot!
