### ISSUE TITLE
Hyperlink button not always working?

### ISSUE THREAD

**Issue by freitasm** [tinymce/tinymce#3985]
Hi folks

Have anyone noticed a problem on Chrome 61 + Windows 10 where if you click the link button it opens the dialog but once you click OK no hyperlink is actually created? You have to then do the same again for it to work.

Thanks

**Comment by spocke** [comment]
There is a bug in 4.7.0 that has to do with if you select backwards from right to left then the link dialog doesn't add the link could be related to that if not could you help us in reproducing your issue by telling us if you are using inline or a iframe based editor and if there is some special contents that needs to be in the editor if so then setup a fiddle at fiddle.tinymce.com so we can easily reproduce that and fix it. Thanks

**Comment by spocke** [comment]
Possible related ticket: https://github.com/tinymce/tinymce/issues/3973

**Comment by freitasm** [comment]
Hi @spocke 

Thanks for your reply. Yes, I see it now - if I select right to left hyperlink doesn't work, but left to right is ok.

Same problem as #3973 then. Cheers.
