### ISSUE TITLE
Tag defined in custom_elements removed from content

### ISSUE THREAD

**Issue by sea75300** [tinymce/tinymce#3986]
I'm using a custom tag "<readmore>" to define an area whose content can be hidden/ displayed on demand. I realised it in an own plugin and insert the given text into TInyMCE using :

`editor.insertContent('<readmore>' + text + '</readmore>');`

Today I noticed the tag get's removed when the code above is executed.

The tag is defined using `custom_elements: '~readmore'`. 

I tried to replace the line above with `editor.execCommand('mceInsertContent', false, '<readmore>' + text + '</readmore>');` with the same result. I also added the tag to "valid_children" and/or "extended_valid_elements" but it still get's removed.

see http://fiddle.tinymce.com/Lbgaab/1

Error occurs with TinyMCE 4.6.7 and 4.7, v4.6.6 works fine. No error messages occurring.

**Comment by spocke** [comment]
I wasn't able to reproduce this inserting seems to work on all versions and the readmore is still in the source code dialog.

**Comment by spocke** [comment]
What browser is this happening in I did just push the button enter something into the dialog and then inspect source and the readmore element is inserted correctly.

**Comment by sea75300** [comment]
Testet in Firefox 56 x64 on Ubuntu 16.04 x64.

But I just noticed I posted the wrong link above.

http://fiddle.tinymce.com/Lbgaab/

**Comment by sea75300** [comment]
Updates to v4.7.1 and still occurs.

**Comment by Afraithe** [comment]
Your fiddle doesn't have `custom_elements: '~readmore',` ?

**Comment by sea75300** [comment]
Yes, the fiddle was missing the definition. That brought me to the point where I had to look at. The information of the tag was defined as a JS variable in real environment, but lost on the way to tinymce.init function. 

Now it's working.
