### ISSUE TITLE
Feature request: allow addContextToolbar to dynamically generate items

### ISSUE THREAD

**Issue by GabiAxel** [tinymce/tinymce#3987]
I propose allowing the second parameter of addContextToolbar to be a function which receives the clicked element as parameter and returns a string or array representing the items to be included in the toolbar. This would allow showing different toolbar items based on the element attributes or other application state. The first parameter would still determine whether the toolbar should be displayed at all, and the second would allow customizing it when it is displayed.

Currently it's only possible to have a function as the first parameter, so in order to implement a dynamic toolbar, I would have to call addContextToolbar for each possible permutation of the toolbar items, which is less than ideal both in terms of code organization and performance.

**Comment by Afraithe** [comment]
That sounds like a good idea, but really, we might be rebuilding the contextmenu very soon for a few different reasons.

1. It is a plugin... a bit overkill, should be in core.
2. It isn't really very context aware, the contexttual changes are a bit of a hack now and can be done a lot better, and allow for what your suggesting.

**Comment by mrpsiho** [comment]
Hi!

Any news here? :) Is it possible to do in TinyMCE 5?
