### ISSUE TITLE
Error in IE when trying to use CTRL-C 

### ISSUE THREAD

**Issue by internayt** [tinymce/tinymce#3990]
Traced this down and found that when trying to do a CTRL-C in IE, it fails in tinymce.fmt.FontInfo - getSpecifiedFontProp

In this file: https://github.com/tinymce/tinymce/blob/5e1fb7535533344261fe557ee17607f2bb7a25d4/src/ui/src/main/js/fmt/FontInfo.js

line 29 fails when the element is a "comment" because the "style" property doesn't exist.
if (elm.style[propName]) {

I replaced with:
if (elm.style && elm.style[propName]) {

That fixed the problem for me, but I am not sure the best way to submit this fix.

**Comment by jayarjo** [comment]
Which IE? No error for me in IE11. Could you provide a [fiddle](http://fiddle.tinymce.com) with the problematic case? Or list the steps to reproduce the problem?
