### ISSUE TITLE
inline_boundaries_selector does not style for ins and del

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#3991]
Setup this CodePen to demonstrate that del and ins do work with inline boundaries but are not styled when moving the cursor in and out:
https://codepen.io/tinymce/pen/EwLYBM

**Comment by spocke** [comment]
It needs a bit of boiler plate css to be expanded to other elements than ”code” and ”a” elements.
Documented here:
https://www.tinymce.com/docs/configure/content-appearance/#inline_boundaries_selector
https://www.tinymce.com/docs/advanced/boilerplate-content-css/

Since this is a very implementation specific feature we haven’t expanded the default css to other elements.

**Comment by androb** [comment]
Ah, thanks @spocke 

Is there some CSS that is slightly less verbose than:
.mce-content-body a[data-mce-selected], .mce-content-body code[data-mce-selected], .mce-content-body b[data-mce-selected], .mce-content-body strong[data-mce-selected], .mce-content-body i[data-mce-selected], .mce-content-body em[data-mce-selected], .mce-content-body ins[data-mce-selected], .mce-content-body del[data-mce-selected] {background-color:#e5f5fa}

No worries if not, it will work.

**Comment by spocke** [comment]
We can look into this I think we can change this to be data-mce-selected="inline-boundary" then you could just select on that with css .mce-content-body *[data-mce-selected="inline-boundary"].

The problem we have now is that we use only one attribute for fake selection of things like table cells, images, inline boundaries etc etc and it's this single attribute. So just changeing that to .mce-content-body *[data-mce-selected] would mean that the css would clash with other selections.

**Comment by androb** [comment]
No worries. I think this is fine for now. If you use a CSS preprocessor I think it ends up being less verbose.

**Comment by androb** [comment]
No worries I think it is fine for now.
