### ISSUE TITLE
Have a max-width option for images while editing

### ISSUE THREAD

**Issue by avrelaun** [tinymce/tinymce#3996]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When importing an image by pasting the url, the image size isn't adjusted to the editor size inside the iframe, and if the image is bigger it's not fully displayed.
After saving the image, the width is adjusted to the parent element, this is not very WYSIWYG.

**What is the expected behavior?**
Having an option to have the image resized to the editor width while editing (eg. 'auto') or to manually set the max width by setting it (eg. '300px'),

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.7.1 / Firefox 57 / Linux

**Comment by fyrkant** [comment]
You can set the `content_style` setting to something like  `content_style: 'img {max-width: 100%;}'` and the images should resize to fit the editor.

**Comment by avrelaun** [comment]
thanks, it worked

**Comment by jjb** [comment]
This was very helpful, thanks! Most folks will probably also want `height:auto`

```js
content_style: 'img { max-width: 100%; height: auto; }' 
```
