### ISSUE TITLE
Odd behavior when selecting an image inside a link in Internet Explorer

### ISSUE THREAD

**Issue by jtark** [tinymce/tinymce#3998]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
In Internet Explorer, clicking on an image inside of a link a couple of times selects the image, then the link, and then the image. This is problematic when one of our users wants to edit the image, selects it, right-clicks it, and chooses to edit the image from the context menu. The first click selects it, but the right click ends up selecting the link. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Left-click the image inside of the link. The status bar will show that the image is selected.
2. Right-click the image to open the context menu. The selection will change to the parent link.
3. Click the Image context menu item. The dialog will open and the Source field will not be populated, since no image is actually selected.

Further clicks on the image will always select the image, not the link (at least until a different element is selected). See the attached HTML file for testing purposes: [Internet Explorer Bugs.txt](https://github.com/tinymce/tinymce/files/1384001/Internet.Explorer.Bugs.txt)

**What is the expected behavior?**
In step 2, the image should remain selected, causing step 3 to edit the image instead of trying to insert a new one.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This affects TinyMCE versions 4.6.0 and later. It does not affect TinyMCE version 4.5.8. This occurs in Internet Explorer, but not Firefox, Chrome, or Edge.

[Internet Explorer Bugs.txt](https://github.com/tinymce/tinymce/files/1384001/Internet.Explorer.Bugs.txt)

**Comment by jayarjo** [comment]
I guess we could use this fiddle for reference: http://fiddle.tinymce.com/ndgaab?

Wasn't able to reproduce this in IE11 on Windows 10? What is your platform, where you observe the problem? As a sidenote current version of TinyMCE doesn't support IEs prior to version 11.

**Comment by jtark** [comment]
This doesn't appear to be an issue anymore for us. I recall testing the fiddle and being surprised that it worked as expected there, but not in our application. After testing it again with version 4.7.6, I'm unable to reproduce it in our application.
