### ISSUE TITLE
Odd positioning of images when the "display: block;" CSS property is assigned

### ISSUE THREAD

**Issue by jtark** [tinymce/tinymce#3999]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
In Internet Explorer and Firefox, img elements with the "display: block;" CSS property assigned have unusual whitespace next to them. In Firefox, the whitespace is always present; in Internet Explorer, clicking an image with that CSS property a couple of times will cause the whitespace to appear. Clicking a different image with that CSS property a couple of times will move the whitespace.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
I've attached an HTML file demonstrating the issue: [Internet Explorer Bugs.txt](https://github.com/tinymce/tinymce/files/1384022/Internet.Explorer.Bugs.txt)
For Firefox, the whitespace is always present.
For Internet Explorer, the whitespace only appears when interacting with the images.

**What is the expected behavior?**
There should not be any whitespace besides the borders and the margins between the images in the attached HTML file.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This appears to affect TinyMCE version 4.6.0 and later. It does not affect TinyMCE version 4.5.8. Firefox has only been tested on version 4.6.7. Chrome and Edge do not appear to be affected by this bug.
[Internet Explorer Bugs.txt](https://github.com/tinymce/tinymce/files/1384022/Internet.Explorer.Bugs.txt)

**Comment by fyrkant** [comment]
The linked files are just text files with no html in them, can you create a [fiddle](http://fiddle.tinymce.com) instead showing the issue?

**Comment by fyrkant** [comment]
Sorry, checked the file again and it contained html after all.

**Comment by jayarjo** [comment]
Moved the code to the fiddle: http://fiddle.tinymce.com/ndgaab. From what I see it's bogus BR, apparently serving as caret container.
