### ISSUE TITLE
Bug: <customTag> is getting stripped

### ISSUE THREAD

**Issue by karoltarasiuk** [tinymce/tinymce#4004]
As you can observe here: `<customTag>` is getting stripped.

1. Go to https://codepen.io/karoltarasiuk/pen/bomKgx
2. Open console in your Web developer tools
3. Click `Get HTML` button
4. Notice that output HTML doesn't have any of `<customTag>`

I would expect that both top level `<customTag>`, and the one placed within `<td>` would be persisted in the output HTML.

TinyMCE version: 4.5.5

**Comment by spocke** [comment]
The browsers will lowercase any element in html so you should use lowercase and also a dash to be conforming with standards.

Check this fiddle: https://jsfiddle.net/Lfg81ho4/
Specification: https://www.w3.org/TR/custom-elements/#valid-custom-element-name

**Comment by karoltarasiuk** [comment]
Good point and works as you said. Didn't know this part of a spec:/ thanks!
