### ISSUE TITLE
Powerpaste plugin doesn't honoring baseUrl set in tinymce options

### ISSUE THREAD

**Issue by deepaknasa** [tinymce/tinymce#4006]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When i load powerpaste plugin, it is not honoring the baseUrl set in tinymce options object. It is taking the relative path of the page where the editor is loaded whereas the powerpaste plugin is hosted on different location.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1) Load the page with tinymce library
2) Try to set the content programmatically (e.g. in $timeout function in angularjs)
3) Now try to paste some content into the editor
4) Observe the dev tools console window it shows errors related to wordimport.js file not being loaded from the url which is wrong url
e.g. powerpaste is hosted on www.<mydomain>.com/scripts/tinymce/plugins/powerpaste/plugin.js
and wordimport is trying to load from, www.<mydomain>.com/relative/path/to/page/where/editor/is/opened/js/wordimport.js

I have to get around this issue by pasting the correct relative path in powerpaste/plugin.js file

```
g("1z", ["43", "1a", "44", "45"], function(a, b, c, d) {
        var e = d.detect()
          , f = e.deviceType.isiOS() || e.deviceType.isAndroid()
          , g = function(d) {
            var e = c.none();
            a.addScript(**"/Scripts/tinymce/plugins/powerpaste/js/wordimport.js"**, b.identity).get(function(a) {
                a.fold(function(a) {
                    console.error("Unable to load word import: ", a)
                }, function(a) {
                    e = c.some(a)
                })
            });
```

**What is the expected behavior?**
powerpaste plugin should respect the baseUrl set in the tinymce options object

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tinymce major version 4, minor version 7.1, browser is chrome
Never tried with previous version (which is 4.3.1) this is the first time we have to use this plugin

**Comment by fyrkant** [comment]
Hi!
For help with the premium plugins, please submit a technical support request at the the [support page](https://support.ephox.com) to get help as fast as possible.
