### ISSUE TITLE
Manually open/close sidebar

### ISSUE THREAD

**Issue by jnessier** [tinymce/tinymce#4014]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
There are currently no possiblities to manually open/close a sidebar like:
`editor.getSidebar('mysidebar').open();`

I cannot find any solution in the [docs](https://www.tinymce.com/docs/advanced/creating-a-sidebar/#editorsidebarapi) or in the source code of TinyMCE.

**Comment by migliori** [comment]
Hi,

I needed the same feature and found how to achieve this:

`tinyMce.editor.execCommand('togglesidebar', false, 'mysidebar');`

It allows to toggle the sidebar, but you can't pass open/close this way.
Anyway we can test the sidebar state and open/close depending on the current state.

**Comment by Kristiyan96** [comment]
@migliori that only closes the sidebar, it doesn't open it...

**Comment by migliori** [comment]
`tinyMce.editor.execCommand('togglesidebar', true, 'mysidebar');`

This will open the sidebar

https://www.tiny.cloud/docs/api/tinymce.editor.ui/tinymce.editor.ui.registry/#addsidebar

**Comment by Kristiyan96** [comment]
@migliori Thanks for the prompt help! This doesn't seem to work as well :/

I register the plugin as adviced in the documentation:
```
tinymce.PluginManager.add('chemInfo', function (editor, url) {
  editor.ui.registry.addSidebar('chemInfo', {
    tooltip: 'My sidebar',
    icon: 'comment',
    onSetup: function(api) {    },
    onShow: function (api) {   },
    onHide: function (api) {    }
  });
});
```

Which displays the toggle button in the toolbar and it works fine. However, both
`tinymce.activeEditor.execCommand('togglesidebar', false, 'chemInfo');`
and
`tinymce.activeEditor.execCommand('togglesidebar', true, 'chemInfo');`

fails to open the sidebar. Any idea where I mess this up :? Thanks again!

**Comment by lnewson** [comment]
@Kristiyan96 it appears as though there's a bug in the toggle sidebar command, as it requires the sidebar name to be lowercase since that's how TinyMCE registers it internally. So if you change `chemInfo` to `cheminfo` then it'll work. Here's a fiddle to demo: http://fiddle.tinymce.com/yXgaab

**Comment by Kristiyan96** [comment]
@lnewson amazing! Thank you
