### ISSUE TITLE
Bug: c is null / selection is null

### ISSUE THREAD

**Issue by erwinleijten** [tinymce/tinymce#4015]
**Do you want to request a *feature* or report a *bug*?**
- This is a bug report

**What is the current behavior?**
- I'm getting erros in the console of 'c is null'. In development version this becomes 'selection is null'.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
- Just opening the editor in a hidden array should reveal the issue

**What is the expected behavior?**
- The expected behavior is no errors when openening the editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- The browser used is firefox, 
- The OS use is Debian and Mac OSX. 
- This error did not occur in TinyMCE v4.6.6 and 4.6.7, but does occur in 4.7.0 and 4.7.1

**The faulty code is this:**
line 21875:
var readRange = function (win) {
  var selection = win.getSelection();
  var rng = (selection.rangeCount === 0) ? Option.none() : Option.from(selection.getRangeAt(0));
  return rng.map(function (r) {
    return Selection.range(Element.fromDom(r.startContainer), r.startOffset, Element.fromDom(r.endContainer), r.endOffset);
  });
};

**The solution for the code could be:**
var rng = (!selection || selection.rangeCount === 0) ? Option.none() : Option.from(selection.getRangeAt(0));

This appears to be a correct change conforming to http://w3c.github.io/selection-api/#extensions-to-window-interface, paragraph 5.1, as getSelection can be null.

**Comment by Cryde** [comment]
For your information, I have the same error.
- FF 57 
- tinymce 4.7.1

**Comment by rileytaylor** [comment]
I also have this issue in firefox 56 on macOS, with both tinymce 4.7.1 and 4.6.x

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by dbistriceanu** [comment]
It seems it can still happen in the latest version (4.7.2):

```
TypeError: selection is null
...
getRanges
tinymce.js:21268
hasMultipleRanges
tinymce.js:21284
normalize
tinymce.js:29549
normalizeSelection/<
tinymce.js:24101
fold
tinymce.js:267
normalizeSelection
tinymce.js:24097
...
```

I've added a simple check to prevent that in #4078.

**Comment by rzymek01** [comment]
Hey! Are you aware of any existing bug report in FF for that or have you contacted with Firefox team about a bug in their implementation of Selection API?

**Comment by race4space** [comment]
`<div>aaaa</div>`

**Comment by Ardeshir81** [comment]
I still have this issue using react integration. This is the stack trace:
![image](https://user-images.githubusercontent.com/5755214/100781914-ef1a2d00-3420-11eb-883d-992e46e54b67.png)


I am using nightly build with releaseDate: `2020-11-25`

This happens when I'm on the page that my component is used, I route to another page, and come back to this page again.
