### ISSUE TITLE
After Inserting code snippets does not save javaScript and Php to the database as contents of the textarea

### ISSUE THREAD

**Issue by Theodory** [tinymce/tinymce#4016]
Am using Tinymce 4.7.1, I was  able to add codesample plugin for adding code snippets but for Html, Css snippets is working well I was able to  save textarea contents to the database but if contents has Php or Javascript snippets it fails to store to my database.

**Comment by spocke** [comment]
Make sure you encode the contents correctly. Sounds like either entity encoding or sql escape. Closing this since this is more of a implementation issue.
