### ISSUE TITLE
Official React Support

### ISSUE THREAD

**Issue by pruhstal** [tinymce/tinymce#4019]
This is a *feature* request.

**What is the current behavior?**
Currently, the officially supported package to integrate tinymce with React is `react-tinymce`. While this is fine and works, there is a long feedback loop between the developer of the wrapper project.

While this isn't a fault of the developer, it'd be nice to see tinymce officially support React in the future as to not rely on a 3rd party dependency wrapper.

Would this be something that we might see in the future?

**Comment by androb** [comment]
I think it is very worthwhile considering

**Comment by Afraithe** [comment]
It's something we are contemplating. We did look at react-tinymce when React 16 came out, but it seems to work fine still. And if we were to make our own, it would probably work almost exactly the same, and that project has an established name & lots of NPM downloads, so not to keen on splitting the userbase up here just for the sake of it. But we will continue to look into this, there might be other options to address your concerns. Do you have any suggestions for changes to it? What is good/bad with it now?

**Comment by pruhstal** [comment]
@Afraithe Thanks for responding.

Here's some of my thought-vomit:

1. The feedback loop to supporting React 16 was almost a week (to get merged in), and then another week to update the version tag. https://github.com/instructure-react/react-tinymce/pull/83

2. Seems wrong for tinymce from a business perspective to defer to a third party (more specifically for people who upgrade but need it supported with React). 

3. Ability to just require `tinymce` and have it work out of the box without a wrapper package such as `react-tinymce` would be the dream. At the same time, possibly not making it required to inject the minified source in a `<script>` tag to make it globally accessibile (per: https://www.npmjs.com/package/react-tinymce#dependency).

4. Adding support for React SSR (e.g. if `typeof window !== 'undefined` then defer until it's available and then render it).

Again, I think the maintainer of `react-tinymce` did something great, and I'm not knocking him for it, but I think it just makes more sense for tinymce to be more forward supportive of React given that it's got staying power (and this is coming from someone who used tinymce for years in a Backbone app that still works great).

My .02 cents

**Comment by Afraithe** [comment]
Thanks, that is good feedback.

Expect a react component soon, would appreciate you helping out to test it.

**Comment by pruhstal** [comment]
Great news @Afraithe. More than happy to help!

**Comment by fyrkant** [comment]
@pruhstal The official React component is now released, for more info see the repository: 
https://www.github.com/tinymce/tinymce-react.
