### ISSUE TITLE
On blur event doesn't always work

### ISSUE THREAD

**Issue by pero93** [tinymce/tinymce#4020]
Is this a bug or am I doing something wrong?

The blur event doesn't work as I expected. When I write something in the editor and then click outside of it, the blur event activates. But when I click on the empty area (shown in the picture), and then click outside of the editor, the blur event is not triggered, so I have to press the mouse pointer again inside the editor and outside again for it to be triggered.

![capture](https://user-images.githubusercontent.com/17166038/31910583-3c81c4e8-b83e-11e7-81cf-b6bb5a25233d.PNG)

**Comment by spocke** [comment]
Yes, it should fire a blur if you go from the UI to another element not withing the editor. The focus/blur is supposed to be fired only when the editor is blurred by moving foucs outside the iframe or the editor ui.

**Comment by benshabatnoam** [comment]
Have you ever tried to fix this bug? it's open from 2017...

**Comment by pero93** [comment]
No recollection as it was long time ago. Closing as it's not relevant anymore.
