### ISSUE TITLE
dynamically added textarea are not render as TinyMCE

### ISSUE THREAD

**Issue by SivaPrakashK90** [tinymce/tinymce#4021]
in angular4 I'm generating textAreas dynamically on button click after that I'm applying tinymce to the textAreas but tinymce was not applying to some of the textAreas. When I'm debugging the code to identify the issue tinymce is applied to every textArea but at the end of the button click event it was disappearing for some textAreas

my dynamically generated textAreas ids are like txtArea_1, textArea_2.....

I'm using following code to apply the tinymce to the textAreas (i.e. I'm calling the following method in button click event after completing the button click event it is going to "drainMicroTaskQueue" method in zone.js  and then tinymce is disappearing for some textAreas)

InitTinyMCE(): void {
    var txtIdArr = ['txtStem'];
    var i = 0;

    if (this.textArealist != undefined) {
        while (i < this.textArealist) {
            txtIdArr.push('txtAnswers_' + i);
            i++;
        }
        var j = 0;
        while (j < txtIdArr.length) {
            tinymce.EditorManager.execCommand('mceRemoveEditor', false, txtIdArr[j]);
            tinymce.init({
                selector: txtIdArr[j],//'textarea',
                height: 100,
                theme: 'modern',
                menubar: false,
                statusbar: false,

            });
            tinymce.execCommand('mceAddEditor', true, txtIdArr[j]);
            j++;
        }

    }
}
may I know the reason why it happens like that? and tell me how to resolve this issue?

I'm using tinymce.min.js (4.3.10)

**Comment by spocke** [comment]
Don't use mceRemoveEditor/mceAddEditor instead just use:
tinymce.init({
            selector: txtIdArr[j],//'textarea',
            height: 100,
            theme: 'modern',
            menubar: false,
            statusbar: false
        });

and
tinymce.remove(id/selector/editor);

Remember that initialization of tinymce is async so init_instance_callback needs to be used to get a editor reference and knowing that the editor did initialize.

This doesn't seem like a bug but rather an question you can use our community forum for that.
