### ISSUE TITLE
Regression: Extra paragraph tags added after formatting is applied in IE

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#4022]
Steps to repro:
1. open http://fiddle.tinymce.com/Wcgaab/1 in IE
2. Open IE dev tools and check the initial content:
```html
<p><span style="font-weight: bold;" data-mce-style="font-weight: bold;">Test</span></p>
```
3. Hit ctrl+a to select the whole editor content
4. change the font size (e.g. 24pt)
5. check content in dev tools:
```html
<p></p>
<p><span style="font-size: 24pt; font-weight: bold;" data-mce-style="font-size: 24pt; font-weight: bold;">Test</span></p>
<p></p>
```

Expected:
only font size is changed and
Actual:
extra <p> tags are added before and after the span tag

can confirm that this did not happen with tinymce 4.6.4

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
