### ISSUE TITLE
Image Resizing Problem in Internet Explorer

### ISSUE THREAD

**Issue by GeertGuns** [tinymce/tinymce#4024]
Hey,

There's a problem when I try to resize an image with a caption in Internet Explorer.
When I do the exact same thing in Chrome, there is no problem.

Scenario:
Add an image with a caption
Left click on the image to select it.  
At this point Chrome shows resize handles on the image ('img' element). Internet explorer however shows 2 sets of resize handles:  1 on the 'img' element which work as they should and 1 on the 'figure' element (when speaking in terms of HTML)

Problem: When you try to resize the outermost set of handles, the image disappears and the editor's focus is put elsewhere.

Example:
On this image you can see the difference between Chrome and Internet Explorer:
![image](https://user-images.githubusercontent.com/32196403/31988238-b2a423e2-b96e-11e7-8b5d-74102268a456.png)

Is there a way to remove the outermost set of handles?
Could you take a look at this.  

I'm using TinyMCE 4.7.1 by the way.

Kind regards,
Geert

**Comment by trevorjay** [comment]
Doing some testing it looks like this behavior has changed and is fixed in the latest version of 4 and 5. Looking back at the changelog, it looks like this particular issue was fixed in 4.7.3. I'm closing this issue but if anyone is still experiencing problems, please let us know.
