### ISSUE TITLE
dragend event is not fired

### ISSUE THREAD

**Issue by ben-mckernan** [tinymce/tinymce#4026]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The dragend event is not fired when dragging a block (e.g. TOC) and dropping outside of the editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Open http://fiddle.tinymce.com/idgaab
2. Drag the TOC and drop it outside of the editor

**What is the expected behavior?**
The dragend event should have been fired.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
OS: Windows 10
TinyMCE: 4.7.1
Browser: Chrome 62, Firefox 56

**Additional**
Looking at the code here: https://github.com/tinymce/tinymce/blob/master/src/core/src/main/js/DragDropOverrides.js#L227
It seems that `state.dragging` will always be false since it is set to false in the `removeDragState` method which is called on the previous line.

**Comment by MagicMicah** [comment]
Fixed, but I am writing unit tests and making sure I haven't broken anything.

**Comment by MagicMicah** [comment]
I have half a unit test, but I can't figure out how to trigger a drag event .
https://github.com/RubberDuckies2017/tinymce/commit/a8c5ab459fe50f126eef084366a1a4874969e307#diff-3049259a14e496c0f52b7f7443dedd36

**Comment by ben-mckernan** [comment]
Any update on this? Is there something more I can do on the PR to get this into the next release?

**Comment by ben-mckernan** [comment]
This is fixed in 4.7.13
