### ISSUE TITLE
BUG:  TinyMCE any version // Win, Mac // Chrome, Firefox // Microsoft Word // Copy+paste from edited Word document inserts previously removed content also

### ISSUE THREAD

**Issue by Kadigan** [tinymce/tinymce#4027]
When pasting text copied from a Word table, content that was previously deleted is also inserted.

Reproducible on https://www.tinymce.com/

------------------------------------------------------------

**Software configuration**

Happens on Windows: Win7 x64 -- haven't tested on others.
Happens on macOS: Mac OS X 10.6, Mac OS X 10.9, macOS 10.12 -- haven't tested on others.

Happens on Firefox and Chrome under both Windows and macOS - latest versions as of 2017-10-26 on all. Also happened on all previous versions.

Happens on Office 2010 and Office 2011 for Mac -- haven't tested others. Source document is a .doc file.

Happens on TinyMCE on https://www.tinymce.com and on TinyMCE embedded with PrestaShop v1.5 and v1.6.

------------------------------------------------------------

Please see attached screenshots. You will see that the pasted text has extra sentences in Italian (this is from a translation document) which have since been deleted in the document.

**What I expect should happen:** the pasted text should not contain previously deleted content.

**What actually happens:** the pasted text does indeed contain previously deleted content.

**If I paste the text into a plain text editor and _then_ copy&paste into TinyMCE, the issue _does not occur_.** This leads me to believe the issue is somewhere in formatting, but Word wouldn't hide versioning in text formatting, would it?

------------------------------------------------------------

![copy source](https://user-images.githubusercontent.com/16637976/32066895-94b93e12-ba81-11e7-9ce4-234190de5dac.jpg)

------------------------------------------------------------

![tinymce result](https://user-images.githubusercontent.com/16637976/32066896-94ec16fc-ba81-11e7-8c4e-76711de12e65.jpg)

**Comment by spocke** [comment]
Can't really reproduce this when I paste with track changes on in Word the deleted contents is removed when pasting. Need more details here.

**Comment by Kadigan** [comment]
When I am able, I will provide a document that I'm seeing issues with. These are confidential, so I can't just hand them out. I'll see if I can write a document that exhibits this behavior instead.

**Comment by bago** [comment]
Please see #4148: maybe the issue is related on what you do before you paste (e.g: if you select everything using mouse double-click before you paste) ?

**Comment by Kadigan** [comment]
I don't use Ctrl/Cmd+A to select, because I'm copying parts of the document.

I don't use double-click to select, because then the entire text style is duplicated -- something I do not want to happen. My client uses text background color to note changes/updates and it's annoying to have to change this back to default each time I paste. Also, if I use double-click, the shape of the table is also retained, along with a border -- again, something I want to avoid if at all possible.

I do however wish to retain _some style elements_, like lists and bold text. This is why I have not disabled Word integration altogether.

I select the text by finding its end, hold-clicking and then selecting to the beginning (or the other way around -- whichever is faster at the moment).

I leave the text highlighted after performing a copy, and switch to the website employing TinyMCE to paste.

I perform duplication from binary .doc files. I do not know if the issue affects XML .docx files.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
