### ISSUE TITLE
Need means of declaring image as decorative

### ISSUE THREAD

**Issue by terrill** [tinymce/tinymce#4029]
Currently, the **Insert/Edit Image** dialog includes a field in which to enter an "Image Description". The value of this field is added to the image as an `alt` attribute, which is announced by screen readers.  

However, it is sometimes desirable to declare an image as decorative so screen readers will ignore it. There are two ways to do this if the image is added using an `<img>` element: 

1. Add `alt=""` to the image. This is a long-standing method for declaring images as decorative, and all screen readers support it. 
2. Add `role="presentation"` to the image. This is a relatively new method (using ARIA) but is supported by recent versions of all screen readers. 

** Current Functionality of TinyMCE ** 
If the user leaves the "Image Description" field blank, neither `alt=""` nor `role="presentation"` is added to the image. Therefore, screen readers don't know if the image is decorative, so they may announce "image" or "graphic" and in some cases read the file name and/or file path, based on the assumption that some information is better than none in case the information contained in the image is critical. 

** Desired Functionality of TinyMCE ** 
If the user leaves the "Image Description" field blank, add either of the supported attributes.

**Comment by cjdubois10** [comment]
Hey @terrill I think I might have fixed this issue. Let me run some unit tests, and if everything looks good, I will submit a pull request. Just a quick question, do you think that this might be a bug rather then a feature?

**Comment by donShakespeare** [comment]
I wonder that this might belong to a user plugin?
See demo http://fiddle.tinymce.com/Xfgaab

```javascript
tinymce.init({
  selector: "textarea",
  menubar: false,
  height: 1000,
  plugins: "code image",
  toolbar: "code image",
  setup: function(editor) {
    editor.on('Nodechange', function(e) { //find better event
      //editor.$('img:not([alt])').attr("role", "presentation");
      editor.$('img').each(function() {
        if (!$(this).attr('alt')) {
          $(this).attr("role", "presentation").removeAttr('alt');
        } else {
          $(this).removeAttr('role');
        }
      });
    });
  }
});
```

**Comment by lnewson** [comment]
Hi,

This feature was added in TinyMCE 5.2 and can be enabled via the new [`a11y_advanced_options`](https://www.tiny.cloud/docs/plugins/image/#a11y_advanced_options) setting. This will add a `Image is decorative` checkbox to the image dialog, which when checked will add both an empty alt text and the `role="presentation"` attribute. Here's a fiddle to demonstrate: http://fiddle.tinymce.com/7hhaab

Thanks!
