### ISSUE TITLE
TinyMCE auto scrolls to top of page after pasting big content

### ISSUE THREAD

**Issue by josemv92** [tinymce/tinymce#4031]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Whenever you paste big amount of content (let's say a big article) and try to do any other edit, the page gets scrolled to the top.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Here's a demo of the issue using the same Full-featured example from the official page https://plnkr.co/edit/kbHeAoGxXbSwMc3mi6IZ?p=preview, this includes the steps to reproduce it and a resource of dummy text which helps reproducing the issue.

**What is the expected behavior?**
Editing the content after pasting a big section of text should not take the user back to the top of the page, this could annoy users which need to do a lot of editing.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
 - TinyMCE latest 4 version (official CDN).
 - Chrome Version 61.0.3163.100 (Official Build) (64-bit) (I tested on Firefox and it looks like it is working fine).
 - Not really sure if it worked in previous versions of TinyMCE (or the browser), I was able to reproduce the issue in http://archive.tinymce.com/tryit/3_x/full.php and I haven't tested on other 4.x versions apart from the current one provided by the CDN.

**Comment by ralspaugh** [comment]
I'm seeing this issue as well. I tried out a random older version 60 developer build of Chromium (Version 60.0.3102.0) and I don't see this issue there, so it seems to only exist in newer versions of Chrome.

**Comment by fyrkant** [comment]
I am having problems reproducing this, can any one of you maybe record a screen recording or something like that?

**Comment by ralspaugh** [comment]
Here's a screen recording of the plnkr linked above my Mac Chrome Version 62.0.3202.75 (Official Build) (64-bit). Notice how when I press "a" after pasting, it scrolls back to the top of the page.

<iframe src="https://giphy.com/embed/3o6nV0bGeRehsVHqM0" width="480" height="260" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/3o6nV0bGeRehsVHqM0">via GIPHY</a></p>

**Comment by androb** [comment]
I have seen this in WordPress although I just tried it on a clean install with no plugins and Grammarly disabled and couldn't replicate it. It is possible it is an interaction with a plugin or browser extension that was causing it... at least for me.

**Comment by spocke** [comment]
This seems to be a chrome issue the latest versions of chrome works correctly also it seems to be mac os specific and only if the paste or powerpaste plugin isn't enabled. I tested adding the paste plugin to the plunker and I can no longer reproduce it after I did that. So please help us verify that it would get solved with the paste plugin. Without it we are at the mercy of the browsers paste implementation and I'm guessing it does something strange here.

**Comment by ralspaugh** [comment]
Adding the paste plugin fixed it for me. Thanks!

**Comment by josemv92** [comment]
spocke, not really sure if it is Mac specific since the user who reported this issue to us works with Windows 7 and I was able to reproduce it on Ubuntu 16 (sorry, I forgot to add those in the description). But I saw the issue disappeared after adding the "paste" plugin too for TinyMCE 4, so thanks for the help. :slightly_smiling_face: 

Do you have a clue about why this works? I ask because an older version of our application uses TinyMCE 3 which seems to have the same issue but the paste plugin doesn't work there to solve it, we are currently in beta for a newer version (which uses TinyMCE 4) so most of our users are in the old version yet and product won't like to invest time in the old version to be migrated to TinyMCE 4, so we are trying to see if there is something we could add in the code to fix this before telling them to deal with it (or upgrade the browser when the latest version in beta is released if it solves the problem).

If you have any clue, it's more than welcomed. We will like to see if there is a workaround for TMCE3 before flagging it as can't be fixed.

Thanks for the info :)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
