### ISSUE TITLE
blockquote format not working

### ISSUE THREAD

**Issue by rustam87** [tinymce/tinymce#4033]
version 4.4.3

not working   blockquote format option
```
formats: {
     blockquote: {
           selector: 'blockquote', classes : 'some-class', exact : true
     }
},
```
When delete `selector: 'blockquote'` from option, TinyMCe add paragraph with class 'some-class'

**Comment by spocke** [comment]
I think this should be that way it toggles the blockquote on/off with a class:
```
formats: {
	blockquote: {
		block: 'blockquote', wrapper: true, classes : 'some-class', exact : true
	}
}
```
