### ISSUE TITLE
feature request: img onmouseover onmouseout

### ISSUE THREAD

**Issue by Maakum** [tinymce/tinymce#4036]
An easy way to add rollover images to an image.

If i remember correctly, this used to be part of the advimage addon, but has disapeared in the latest versions. It would be great to have it back!

**Comment by spocke** [comment]
We used to have this feature way back but it's not something we are likely to add back since it would involve adding inline scripts and we avoid that now days to filter out xss etc. You can however create your own plugin if this is something you really need.
