### ISSUE TITLE
Navigating VoiceOver to text area of TinyMCE causes screen to jump to the top

### ISSUE THREAD

**Issue by claydiffrient** [tinymce/tinymce#4037]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using VoiceOver in Safari, when you navigate using the screenreader commands past the toolbars the screen will jump to the top of the page.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Demo: http://fiddle.tinymce.com/8dgaab

Steps:

1. Activate VoiceOver screen reader
2. Go to an instance of TinyMCE that is below the fold using the VO + right/left arrow commands
3. Notice that as soon as you hit the actual text area the screen jumps to the top of the page

**What is the expected behavior?**

The screen doesn't jump to the top, but maintains position

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

MacOS with Safari 11, unsure if it worked in previous versions.

**Comment by jaredcrystal** [comment]
Not sure if it's the same root problem, but looks like a number of people have observed similar behavior when focusing an iframe (not just tinymce) while navigating using VoiceOver. See https://discussions.apple.com/thread/7537410

**Comment by jaredcrystal** [comment]
Also, if it's any help debugging, when I observed this bug, the following error was thrown in the console:
`TypeError: null is not an object (evaluating 'editor.getWin().focus')`
which seems to be coming from https://www.tinymce.com/docs/api/tinymce/tinymce.editor/#getwin
and voiceover would read "90 percent loaded".
