### ISSUE TITLE
TypeError: h is undefined tinymce.min.js:13:20947

### ISSUE THREAD

**Issue by opsional** [tinymce/tinymce#4039]
Fire tinyMCE v4.6.3 (2017-05-30) on button click, but console error
`
TypeError: h is undefined[Learn More]  tinymce.min.js:13:20947`

```
var a_id = $( this ).data( 'id );
if ( typeof(tinyMCE) != 'undefined' ) {
	tinyMCE.execCommand( 'mceRemoveEditor', true, 'ac-input-' + a_id );
	tinyMCE.init({
		selector: '#ac-input-' + a_id,
		plugins: 'wordpress textcolor wplink',
		menubar: false,
		statusbar: false,
		toolbar1: 'bold,italic,underline,forecolor,link',
		toolbar2: '',
		toolbar3: '',
		toolbar4: '',
		branding: false,
	});
	
	tinymce.execCommand( 'mceFocus', false, 'ac-input-' + a_id );
}
```

**Comment by fyrkant** [comment]
Can you create a [fiddle](http://fiddle.tinymce.com/) reproducing this in the latest version of TinyMCE?

**Comment by spocke** [comment]
If you want to focus an editor when it's initialized use the auto focus feature or wait for the editor to initialize. TinyMCE is async so it will not be available directly after the tinymce.init call.
