### ISSUE TITLE
Package download with https://

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4042]
Would be nice if e.g. http://download.ephox.com/tinymce/community/tinymce_4.7.1.zip would be accessible with https:// prefix. I'm not sure it was ever working, but now it gives a certificate error.

**Comment by MagicMicah** [comment]
Maybe I am wrong, but this could be a hosting error or something to do with hosting the company site, not with the tinymce project itself.

**Comment by alecpl** [comment]
It looks like https://download.tiny.cloud/tinymce/community/ is the new location that works.
