### ISSUE TITLE
TinyMCE Email editor seems to create extra space with quotes

### ISSUE THREAD

**Issue by nhucdaudaobungdaochan** [tinymce/tinymce#4046]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**
TinyMCE editor, when trying to save "HTML code" changes, would re-format the HTML code into better looking, cascading format.
It would also make the special characters like '„' into its own line, probably not knowing what it is, and then put the <a> tag to the next line.
This behavior might later, during rendering (for preview or actual mail) to introduce extra space in front of the link text.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
See above
**What is the expected behavior?**
Not adding space after the quote.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by spocke** [comment]
Need more info here please provide a fiddle where it can be reproduced could be some encoding problem on the server too needs an isolated test case. Thanks.

**Comment by nhucdaudaobungdaochan** [comment]
Sure, let me ask our developer to release the code and will update you.

**Comment by fyrkant** [comment]
No answer so I'm closing this.
