### ISSUE TITLE
Update lang files

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#4049]
Not really a bug, but is there a way to update the lang files. If I cklick on translate I get an forbidden page.
I am glad to update the lang file as an volunteer (dutch), or can we somehow download the full english version ?

**Comment by fyrkant** [comment]
Hmm, that is weird, I haven't seen the 403 page before when trying to go to the transifex page... I guess you need to create a user and login to be able to go to the page, might be easiest to do by going to this link and clicking `Help Translate "TinyMCE"` in the top right:
https://www.transifex.com/moxiecode/tinymce/

**Comment by cfconsultancy** [comment]
Great, needed to subscribe first, translation is done :-)
