### ISSUE TITLE
Forecolor command event is not working in 4.7.2

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#4056]
Hi,

We have upgraded our tinymce library from 4.4.3 to 4.7.2 recently and facing an issue with "forecolor" command.

Can anyone please suggest us any solution for this.

Ref code:
editor.on('Forecolor', function(args) {
                    console.log("forecolor");
                });

**Comment by spocke** [comment]
I don't think we ever had such a event it doesn't work on 4.4.3 http://fiddle.tinymce.com/1egaab so closing this one since it's not a bug from what I can see.

**Comment by kaviyarasanaspire** [comment]
Hi,

But I too don't know How it works in my poject which is having 4.4.3.

Can you please which command I need to catch if I have to write some customization while executing forecolor event in 4.7.2.

Thanks for your help!

**Comment by kaviyarasanaspire** [comment]
I got the solution by finding the customized code in my project.

Thanks for your help!
