### ISSUE TITLE
Translation of "Cannot convert blob:..... to Blob." message

### ISSUE THREAD

**Issue by nikomiranda** [tinymce/tinymce#4057]
There is a way to translate the message on file Conversions.js using the tinymce_dist?

I'm using version 4.7.1

**Comment by spocke** [comment]
You should never get that message unless something is very wrong and then it's a message for the developer there for it's not translated.

**Comment by nikomiranda** [comment]
There is some content saved that have an image with bad url (I don't know why wasn't converted to base64 on the first place, may be an old version of tinymce), and after upgrading to 4.7.1 if I open that content (its on a textarea) the message appears to the user (I attach an screenshot).

`			<textarea id="body" name="body" class="form-control readOnlyBody">
&lt;p&gt;&lt;span style=&quot;font-size: small;&quot;&gt;TEST &lt;br&gt;&lt;br&gt;&lt;img src=&quot;blob:https://localhost/07de02f2-1e96-4960-9f06-09cd037198f&quot;&gt;&lt;/span&gt;&lt;/p&gt;</textarea>
			</div>`
![test](https://user-images.githubusercontent.com/9426688/32725629-38210838-c8b9-11e7-9b08-f3948b0d3ddb.png)

Is there is a way then to disable the message to the user? Though the message is still useful for the final user to know there was a problem saving the images.

**Comment by spocke** [comment]
Maybe we should instead stick that message into the developer console the image is broken and the user can't do much about that information anyway.

**Comment by nikomiranda** [comment]
Yes I think that would be better.

**Comment by nuxio** [comment]
Is there any progress? :smiley:

**Comment by preimpression** [comment]
Seeing as I ran into the error just now, I'm curious.

**Comment by iacopocarlini** [comment]
Any progress guys?
