### ISSUE TITLE
want to use the charcoal skin, can't figure out how from the docs

### ISSUE THREAD

**Issue by seductiveapps** [tinymce/tinymce#4058]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by seductiveapps** [comment]
I'm upgrading my tinymce from version 3.5.10 to version 4.
I had been using a semi-transparent skin for 3.5, because my website seductiveapps.com is all about transparency features.

For starters, how do i include the charcoal skin?

i'm loading up https://cloud.tinymce.com/stable/tinymce.min.js

Here's my init call : 

		//tinyMCE-4
		//tinyMCE-4
		var path = sa.m.globals.urls.framework + "/lib/tinymce-4/themes/";
		tinymce.init({
		  selector: 'textarea',
		  init_instance_callback : sa.s.c.HTMLeditorInitialized,
		  //height: 500,
		  menubar: false,
		  plugins: [
			'advlist autolink lists link image charmap print preview anchor textcolor',
			'searchreplace visualblocks code fullscreen',
			'insertdatetime media table contextmenu paste code help'
		  ],
		  toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
		  content_css: [
			path+'charcoal/content.min.css',
			'//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
			'//www.tinymce.com/css/codepen.min.css']
		});

the editor shows, but with the default white skin instead of the charcoal skin.

**Comment by seductiveapps** [comment]
i've also verified that the charcoal content.min.css file actually loads correctly

**Comment by donShakespeare** [comment]
`content_css` is for the HTML elements in your editor, the rich text you are going to be inputting there ... how you want Paragraphs to look and DIVs... etc.
https://www.tinymce.com/docs/configure/content-appearance/#content_css

So, the charcoal theme link is quite misplaced in that setting.
You are looking for a setting that will style your Editor UI (not its content)

ENTER `SKIN_URL`
https://www.tinymce.com/docs/configure/editor-appearance/#skin_url

```
tinymce.init({
  selector: 'textarea',
  skin_url: path + 'charcoal' //make sure that path is an absolute url or else TInyMCE will look for the charcoal in its CDN root
...
});
```
Cheers

**Comment by spocke** [comment]
This ticket seems to be more of a general community question rather than a bug/feature request. Please use the community forums at https://community.tinymce.com/ or register for an Enterprise license for commercial support. Thanks.
