### ISSUE TITLE
Duplicate imports in 4.7.2

### ISSUE THREAD

**Issue by Niels-NTG** [tinymce/tinymce#4059]
It seems that in version 4.7.2 the file size of the TinyMCE library has grown significantly. I noticed this when 3 of our web applications suddenly grew exactly 136 kB. When reverting to TinyMCE 4.7.1 our file size shrank by 136 kB. When comparing the source code I noticed how 4.7.2 added some imports to 2 different versions of the same feature. For example: 4.7.2 contains both `ephox.katamari.api.Arr` and `tinymce.core.util.Arr`, while 4.7.1 only contained the latter. Here are some of the other imports I noticed seem to be duplicates or slightly different versions of the same thing:
- `ephox.katamari.api.Fun` and `tinymce.core.util.Fun`
- `ephox.sand.api.Node` and `tinymce.core.html.Node`

I would like to know if my hypothesis makes sense and if it's possible the reduce the file size in future releases.

**Comment by spocke** [comment]
The size increase is likely due to the rewrite of the table plugin. We are looking into a few options to decrease the size in general especially when it comes to code duplication between themes and plugins and the core.
