### ISSUE TITLE
Unable to Insert quotation mark (") from Special Character lightbox

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#4062]
Hi,

Unable to Insert quotation mark (") from Special Character lightbox in the latest tinymce version demo as well.

Can anyone please suggest me the solution.

**Comment by kaviyarasanaspire** [comment]
Hi,

It's reproducible in the below fiddle which uses 4.7.2

http://fiddle.tinymce.com/1egaab

**Comment by fyrkant** [comment]
This was fixed a while back!
