### ISSUE TITLE
Table Cell properties dialog throws error when setting H Align and V Align

### ISSUE THREAD

**Issue by tombro32** [tinymce/tinymce#4063]
Bug on version 4.7.2. I believe this issue is new.

Steps to re-produce:
Insert a table (doesnt matter how many rows or cols).
Right-click a table cell and go to cell properties.
Update H Align to "Left" and V Align to "Bottom".
Hit Ok.

Nothing happens. The following javascript error is thrown:

Uncaught TypeError: Cannot read property '0' of undefined
    at n (tinymce.min.js:8)
    at Object.apply (tinymce.min.js:2)
    at Object.d [as applyVAlign] (tinymce.min.js:71)
    at Array.<anonymous> (tinymce.min.js:71)
    at Object.c [as each] (tinymce.min.js:2)
    at tinymce.min.js:71
    at Object.ignore (tinymce.min.js:12)
    at Object.transact (tinymce.min.js:12)
    at f (tinymce.min.js:71)
    at k.onsubmit (tinymce.min.js:71)

Setting H Align ONLY works just fine.
Also setting V Align ONLY (leave H Align as None) seems to work as well.. although the value doesn't stick.

Tested using latest version of Chrome (62.0.3202.89).
TinyMCE source: http://cdn.tinymce.com/4/tinymce.min.js

**Comment by jamie-beck** [comment]
I am running into the same bug. I am running the same version of TinyMCE and chrome. It is also happening in FireFox 57. I have not tried any other browsers.

**Comment by Afraithe** [comment]
This was fixed in 4.7.3.
