### ISSUE TITLE
[BUG] Linking to Anchor-Tag in Tinymce not work

### ISSUE THREAD

**Issue by xstable** [tinymce/tinymce#4068]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
If you create an anchor-Tag in Tinymce 3.5.10 (and up to 3.5.12) it creates `<a id="myID"></a>`
Because there is no "name"-Attribute in this anchor-Tag, the Link-Popup dosn't show the Dropdown to select the anchors in current Page.

![auswahl_337](https://user-images.githubusercontent.com/1778068/32825246-926edce4-c9e4-11e7-808b-3772ddd8cc65.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Create an Anchor in Tinymce
2. Try to create an Link, which should point to this anchor

**What is the expected behavior?**
Showing the dropdown with anchors in current page

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
3.5.10

**How to fix**
Replace the name-Attribute in _tinymce3/jscripts/tiny_mce/plugins/advlink/js/advlink.js_ with the "id"-Attribute 
```
// LINE 378:
	for (i=0, len=nodes.length; i<len; i++) {
		console.log(ed.dom);
	    if ((id = ed.dom.getAttrib(nodes[i], "id")) != "")
            html += '<option value="' + tinyMCE.settings['article_url_suffix'] + '#' + id + '">' + id + '</option>';
	}
```

https://github.com/tinymce/tinymce/blob/3.5.12/jscripts/tiny_mce/plugins/advlink/js/advlink.js#L378

**Comment by spocke** [comment]
3.x is in maintenance mode and we only fix critical browser regressions I suggest that you upgrade to 4.x.
