### ISSUE TITLE
Is there an option to keep spaces on paste? TinyMCE currently removes almost all whitespace

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#4069]
Currently, up to latest v4.7.2, TinyMCE removes all whitespace (tabs and spaces) during paste . So any text or code formatted with whitespace pasted into the editor always loses it's structure. 

For example:
```
  function(){
    test;	test2;		test3;
  }
```
Becomes:
```
function(){
test; test2; test3;
}
```

I have not found any settings that influence this. 

Trying to create a custom workaround for this problem,

```
editor.on('PastePreProcess', function(e){
  // Prevent TinyMCE from removing spaces/tabs on paste
  e.content = e.content.replace(/ /g, '&nbsp;').replace(/\t/g, '&nbsp;&nbsp;');
});
```

I ran into the issue that whitespace between HTML attributes gets replaced too. So in order for this to work correctly a more complex regex needs to check spaces only outside of the HTML tags themselves, which if even written properly would be very fragile if the input HTML does not have correct syntax (partial copies, typos etc.).

So my question is, to prevent such a messy and unstable workaround, a proper solution would be to tell TinyMCE not to remove the spaces in the first place. Is this possible? If not, will you accept such option as a feature request?

**Comment by spocke** [comment]
Use the codesample plugin it's design to preserve whitespace.

**Comment by spocke** [comment]
Closing this since there is existing alternatives. Whitespace is by default collapsed tiny can't know what the user intention was in that case so the user needs to select a way to paste that as code.

**Comment by alphestdev** [comment]
Unfortunately, codesample plugin lacks usability to be used as an alternative (the biggest problem is that it's not directly editable). But, I see you consider it a good alternative and are not willing to create such an option. Thanks anyway.

**Comment by ShqipognjaLL** [comment]
A little late to the party but hooking into the paste_preprocess you have prettty good control of what comes out of the clipboard.

```
tinymce.init({

paste_preprocess: function(pl, o){
        
        o.content = encodeSpaces(o.content);
}

});
```

**Comment by ShqipognjaLL** [comment]
Instead of regex you could parse through the content and create a dom. 

```
editor.on('PastePreProcess', function(e){
  // Prevent TinyMCE from removing spaces/tabs on paste
  var tempDom = document.createElement("DIV");
       tempDom.innerHTML = e.content;
       //recursively traverse through each child node untill you reach the textnode then encode it.
     //childNode.nodeName == "#text"
        //---base case,     textNode.data = encodeURIComponent(textNode.data);
});
```
