### ISSUE TITLE
table - properties - colorpicker missing - V 4.7.2

### ISSUE THREAD

**Issue by wselen** [tinymce/tinymce#4070]
Bug on version 4.7.2

Insert table - properties - advanced - color : no colorpicker is found
checked on :  https://www.tinymce.com/
                      https://www.tinymce.com/docs/demo/full-featured/

Worked on version : 4.3
But there is also an issue that the color did not showed the previous value.
Possible to solve like below onPostRender :

    {   name: 'tablecolor', type: 'colorbox', label: 'Text color', maxWidth: 100,
        onPostRender: postRenderColorPick(data.tablecolor)
   },

        function postRenderColorPick(val) {
            return function () {
                // set icon color on render
                this.getEl().getElementsByTagName('i')[0].style.background = val;
            };
        }

Tested Chrome :  Version 62.0.3202.94

**Comment by Afraithe** [comment]
The color picker now shows up (4.7.3), unfortunately the color picker button now always shows even if the color picker isn't configured in, will have a ticket on that internally.
