### ISSUE TITLE
New table bug - Default width 100% doesn't change - Bug in the version 4.7.2

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4072]
When a new table is created, the default width is 100%, but when you change the width from the table properties to 500px (for example), it doesn't change. It only works if the width is modified from style input text in the advance tab.

**Comment by jankowskip** [comment]
Hey im using TinyMce version 4.7.11, i do have similar bug
In inline editor when you resize last cell saved table has still width 100%, table plugin should recalculate and update witdh of the table. 

![cell_drag_widht_bug](https://user-images.githubusercontent.com/12384594/45867831-9c468480-bd84-11e8-85d3-38f1fc533cbe.gif)

When i resize table by corner button everything works as expected

![widht_change_correct](https://user-images.githubusercontent.com/12384594/45867886-bda77080-bd84-11e8-93f3-8bcd7641b242.gif)
