### ISSUE TITLE
Table not unselectable

### ISSUE THREAD

**Issue by Taygair** [tinymce/tinymce#4080]
Bug:
1. Create a custom toolbar button that shows a dummy window (with no content). Add the following line in open event:  tinymce.activeEditor.selection.collapse();
2. Add a table with some cells in tinymce
3. Select it
4. Press the button created in 1. so the dummy window will appear
-> The table is not unselected. You can try this with f.e. a selected image or some selected text. Then it works fine, just not on tables.

Expected behaviour: 
Table will be unselected, table button toollist is not shown

Version affected: 4.7.2
Browsers affected: Chrome, Firefox, Safari (up to latest versions)

Additional unwanted  effect: When hiding the tinymce, copying HTML code into textarea of tinymce and then show the tinymce again sets all the tables inside the HTML code selcted (white boxes in corners of tables) but not showing any table button toolbar next to table. Also not deselectable by  tinymce.activeEditor.selection.collapse();

**Comment by fyrkant** [comment]
Can you create a [fiddle](http://fiddle.tinymce.com) reproducing the problem so it is easier for us to look at?

**Comment by Taygair** [comment]
Here is a working sample showing you the problem (copy/paste to Fiddle).
1. Run code below
2. Create manually a table (f.e. 2x2) and keep it selected after it was created
3. Press the custom button 'Button' in the toolbar. 
-> It should collapse (unselect) the table selection but it doesn't. If you insert f.e. an image and select it, or select some typed in text they both will be unselected. Only the table keeps selected. This wouldn't be that ugly if the in-editor table-toolbar wouldn't overlap everything. In my case I show a custom window while the in-editor table-toolbar is on top of that. Thats why I need it to have it unselected.
```
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | dummy",
		setup: function (editor) {
		      // Add button for media insert media file
                editor.addButton('dummy', {
                    type: 'button',
                    icon: false,
					text: 'Button',
                    tooltip: 'Dummy button',
                    onclick : function() {
                        // Hide all possible focused window (else overlapping issues)
                        tinymce.activeEditor.selection.collapse();
						console.log ('everything should be collapsed now');
                    }
                });
	}       
});


</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>
```

The other weird thing is (not possible to show in Fiddle but you may understand now better): 
1. Programmatically copy HTML code **with a table in it* into tinymce (previously created in tinymce)
2. Make tinymce visible (maybe not even necessary)
-> The table is selected by default! If you have more than one table in the HTML code then ALL tables are selected by default. Dunno why that is. You need to click the mouse anywhere else to make it/them unselected.

**Comment by Taygair** [comment]
Infos as desired added, see message above

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
