### ISSUE TITLE
Accessibility: Selected toolbar buttons are not distinguishable from other buttons in HC theme.

### ISSUE THREAD

**Issue by terrimorton** [tinymce/tinymce#4097]
This issue came up during an accessibility audit.

**Summary**: Change system settings to High Contrast (Black, or White). Selected "Bold" button is not distinguishable from the other buttons.

**Test Environment**:

- **OS**: Windows 10 RS2
- **OS version**: build 15063.2
- **Browser**: Microsoft Edge 40.15063.2.0 and Firefox 54.0.1
- **Tiny MCE version**: 4.7.3 (and earlier)

**Prerequisite**:

- Change system setting to High Contrast Black: Go to Settings-> Ease of Access-> High contrast-> High Contrast Black
- Change system setting to High Contrast White: Go to Settings-> Ease of Access-> High contrast-> High Contrast White 

**Repro Steps**:

- Open [https://www.tinymce.com/docs/demo/basic-example/](https://www.tinymce.com/docs/demo/basic-example/) in Edge or Firefox browser.
- Click on MoxieManager (which appears in bold)
- Observe the selected "Bold" button. There is no selected state indicated. The button is is not distinguishable from the other buttons.
- Observation: Issue is observed for all/most of the buttons in the toolbar.
- Observation: Side note - Clicking the bulleted line "Our documentation is a great resource for learning how to configure TinyMCE." does show "Increase indent" in a selected state.

**Expected Result**:
HC Black & White: Selected "Bold" button should be highlighted in HC theme

**Actual Result**:
HC Black & White: Selected "Bold" button is not distinguishable from the other buttons.

**User Impact**: 
Low vision users will not be able to differentiate the selected button from others.

![4097-no theme](https://user-images.githubusercontent.com/4643903/33374983-5b57f89c-d4d6-11e7-9238-4e2ef79b08d7.jpg)
![4097-high contrast white](https://user-images.githubusercontent.com/4643903/33374980-5b3299f8-d4d6-11e7-9bf4-73bae6a8d9e3.jpg)
![4097-high contrast black](https://user-images.githubusercontent.com/4643903/33374982-5b491728-d4d6-11e7-9594-ddf89367fb3f.jpg)
![4097-side note](https://user-images.githubusercontent.com/4643903/33374981-5b3ede84-d4d6-11e7-8e3e-61d704c9478b.jpg)

**Comment by terrimorton** [comment]
This accessibility bug still exists and our website is still failing accessibility audits as a result. Will this be addressed?

**Comment by jimunoz1990** [comment]
Following-up to make sure this isn't forgotten

**Comment by jimunoz1990** [comment]
Workaround for anyone else experiencing this issue:

Override the `tox-tbtn` style to add your own border/outline on hover/focus
```
.tox-tbtn {
  &:focus,
  &:hover {
    border: inset 4px transparent;
    outline: solid 3px transparent;
    z-index: 1;
  }
}
```

**Comment by terrimorton** [comment]
> Workaround for anyone else experiencing this issue:
> 
> Override the `.tox-tbtn` style to add your own border/outline on hover/focus
> 
> ```
> .tox-tbtn {
>   &:focus,
>   &:hover {
>     border: inset 4px transparent;
>     outline: solid 3px transparent;
>     z-index: 1;
>   }
> }
> ```

@jimunoz1990 Thanks for the tip!  We took a similar approach after seeing your reply here. :-)

**Comment by terrimorton** [comment]
I took a look at the behavior on https://www.tiny.cloud/, and I see this issue is now addressed (at least in the cloud version), so closing this ticket.

(We no longer use TinyMCE, just closing the loop here)
