### ISSUE TITLE
Version - 4.7.3 - Table bug - Can't change a cell background or border color from the textbox field

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4099]
Select the cell properties of any cell and in the textbox background color or border color field input the value #fc0000 and then the color preview box at the right will be red, but when you press OK, the cell background or border remains the same.

IMPORTANT: If after inputting the hex value, you press the tab key, the background-color or border value will be added to the style textbox and it will work, but if you don't press the tab key and you click in OK, nothing happens. The same bug happens when you try to change the table border or background color.

https://codepen.io/lrusso85/pen/aVQQgg

**Comment by JoeOwner** [comment]
Any update on this? I'm running into the same issue

**Comment by lrusso** [comment]
The bug was fixed. Thank you very much for that!
