### ISSUE TITLE
Mobile theme not usable

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4115]
Roundcube Webmail is using TinyMCE for HTML email editing. The editor is main element of mail compose page. I'm working on a new responsive theme for Roundcube and I need mobile-friendly HTML editor. So, I took TinyMCE 4.7 and modified our tinymce config. It's completely not usable.

- Adding just `config.mobile = {theme:'mobile'}` does not work in Firefox at all, in Chrome it works. In both I'm testing dektop browser versions in Responsive Design mode. `config.theme='mobile'` works in Firefox.
- When switching to full-screen-mobile-editing mode in Firefox the editor does not work. I have a white page, no UI elements. Means not possible to test in Firefox at all.
- Initially the editor is in non-editable mode, it requires a touch to go to full-screen mode on mobile. I'm not sure I like this. Our editor is the main component of the page and there's 99% chances the user will want to edit the content, it should be enabled by default and not require full-screen nor redundant edit button tapping. The textarea already is almost full page.
- For old version I used `config.toolbar = 'undo redo | insert | styleselect'` and that worked. `Insert` doesn't exist in mobile theme?
- The 'T' letter in styleselect button is not self-explanatory. The old 'Formats' was better. And I'm not using style_formats setting.
- Image button does not display image dialog so I can't use defined file_browser_callback to insert attached images.
- mobile theme size: 230KB, modern theme size: 150KB. Really? So much more code for such simple interface?
- I'm curious if it's possible to overwrite mobile menus. They work/look different that the one my app is using, I'd like to unify. Is there any API I can use for this?

**Comment by Afraithe** [comment]
Thanks for the feedback Alec, we are taking another pass at the mobile support after gathering some feedback. One of the next steps is to try and enable more features in the mobile setting.

As far as the file size, the mobile theme uses a new UI library that we aim to switch and start using in the other themes as well, once that happens, the size will go down again as the old UI will go away.

By the way, testing it on a desktop browser in responsive design mode isn't the same thing as testing it on a mobile phone.

**Comment by alecpl** [comment]
Looks better in TinyMCE 5.

**Comment by Afraithe** [comment]
Thanks Alecpl, we expect to put a lot more effort into mobile to get it solid in V5.
