### ISSUE TITLE
Cannot remove an editor immediately after init

### ISSUE THREAD

**Issue by platan** [tinymce/tinymce#4118]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
an error is thrown
Chrome: Uncaught TypeError: Cannot set property 'onload' of null
Firefox: TypeError: null has no properties
IE 11: Unable to set property 'onload' of undefined or null reference

Stacktrace from Chrome (tinymce 4.7.4):
```
Uncaught TypeError: Cannot set property 'onload' of null
    at Editor.unbindAllNativeEvents (VM11718 tinymce.js:23654)
    at Editor.remove (VM11718 tinymce.js:41413)
    at Object.execCommand (VM11718 tinymce.js:42620)
    at preview.php?type=session:23
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Initialize an editor
2. Remove the editor quite fast after initializing
3. tinymce throws an error
Then we are not able to initialize it again.  

http://fiddle.tinymce.com/yggaab/3

**What is the expected behavior?**
Editor will be removed without throwing an error. After this I can initialize the editor again. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 4.5.x, 4.6.x and 4.7.x. Edge and nightly as well. Newest Chrome, Firefox and IE 11 at MacOS.

**Comment by platan** [comment]
Is is my simple workaround https://github.com/platan/tinymce/tree/remove-editor-after-init (diff https://github.com/platan/tinymce/commit/851978c5011b6a7b342e4c8d95dd93fea3e379e4)

https://jsfiddle.net/2bbj7vqu/6/

**Comment by donShakespeare** [comment]
Interesting!
Are you able to share what you are trying to achieve?

**Comment by platan** [comment]
We have a form which allows to edit some data. By default the form displays a bock of text (preview mode). If you click at this text it switches into edit mode - text is replaced with tinymce editor. When a user click outside editor we have preview mode again. 
When a user click very fast preview mode -> edit mode -> preview mode tinymce is removed before it's fully initialized. Out react app is using https://github.com/instructure-react/react-tinymce to render edtior, but the same problem occur with https://github.com/tinymce/tinymce-react.

**Comment by donShakespeare** [comment]
This is how I'd do it to be smooth and to make it really impossible to break in future.

If the user is always going to enter edit mode when that page loads, then load TinyMCE immediately, or else (if user is not necessarily always going to enter edit mode) then load the page and wait for user to click in order to then load TinyMCE.

Put your code responsible for switching modes into a function (switchModes) and call it for the first time when TinyMCE has finished loading
```javascript
editor.on("init", switchModes);
```

*The switchModes function*
It may not be necessary to *remove* TinyMCE altogether (depends on the details of what you are trying to achieve). It might be resource expensive.
Try `editor.hide()` /  `editor.show()`.

```javascript
if(typeof switchModesFired != "undefined") return;

//your code for on click
<<--react onClick outside editor
if(tinymce.get("idOfEditor")){ //check if exists (or you can check if visible)
  // destroy (or .hide()) it here
  // show preview
}

//your code for on click
<<--react onClick inside preview area
if(!tinymce.get("idOfEditor")){ //check if exists (or you can check if hidden)
   // hide preview
   // re init (or .show()) it here
}

switchModeFired = 1;
```

**Comment by jayarjo** [comment]
@platan, Why not simply wait until TinyMCE finishes initialization (which is async process) and then remove it? Simply wait for the callback and then switch the tabs.

**Comment by fyrkant** [comment]
I think this was fixed some time ago so I al closing this, if you are still having the problem please open up a new issue. I would also like to recommend using our official react wrapper: https://github.com/tinymce/tinymce-react
