### ISSUE TITLE
Bug: Weird menu behaviour in Safari browser / tinymce 4.7.2+

### ISSUE THREAD

**Issue by Taygair** [tinymce/tinymce#4125]
**Type**: Bug

**Behaviour**:
On opening/moving inside the menu structure of tinymce using Safari (on Mac) the area around the opened menu behaves weird. I have seen that in my project and as well on the demo editor at www.tinymce.com

Some attachments had to be taken by my mobile. I was unable to do screenshots (effect was not shown):
<img width="937" alt="project_original" src="https://user-images.githubusercontent.com/21134000/34073552-6c5de4d4-e29c-11e7-9773-0cead128d8df.png">
That way it should look like
<br>
![project_menu](https://user-images.githubusercontent.com/21134000/34073555-73727622-e29c-11e7-9b8e-bcf404c2d452.jpg)
The tinymce menu is opened: All red squares are showing displayed objects that now are put behind the semi-transparent div-layer . The header (blue) is cut diagonal and showing more of the header the more I move right inside the menu (but always diagonal cut header)
<br>
![project_close](https://user-images.githubusercontent.com/21134000/34073559-779e7926-e29c-11e7-9556-ca26f316565b.JPG)
Showing the diagonal cut header (shrinking and growing as on moving in the menu structure). The cut part has been put behind the semi-transparent div-layer
<br>
Effect at www.tinymce.com:
<img width="1440" alt="tinymce_original" src="https://user-images.githubusercontent.com/21134000/34073561-7bdff17c-e29c-11e7-93f7-82d27691f9c2.png">
Showing tinymce at www.tinymce.com as it should
<br>
![tinymce_menu_file](https://user-images.githubusercontent.com/21134000/34073562-7f7f070a-e29c-11e7-9130-7f2c8aeff2a9.JPG)
Clicking/opening the file menu, all other menues and toolbar buttons disappearing
<br>
![tinymce_menu_view](https://user-images.githubusercontent.com/21134000/34073565-82c6e73e-e29c-11e7-96a9-19d9c8168219.JPG)
Moving over to tinymce_menu_view: Eveything left from that menu is shown again. The more i move right inside the menu structure the more is shown on the left side till complete.

In my project and on www.tinymce.com everything is fine again as soon as the menu is closed, all objects around appear as they should.

**Affected version**:
For sure tinymce 4.7.4 and 4.7.2 (both tested). I still have a tinymce version that is working correctly (must be 4.x) but haven't got the changelog of that one, so can't say the exact version.

**Tested**:
Mac, High Sierra 10.13.1
Safari Version 11.0.1 (13604.3.5)

**Comment by wambaloo** [comment]
Hi !

I have the same problem. Did you solve it ? I'm on the latest version 4 of TinyMCE.

This ticket is from 2017, so is there a trick to make it work on Safari browser ?
I cannot see what element does this weird behaviour in Safari element inspector because it disappear.

Thanks in advance !

**Comment by Taygair** [comment]
Hi
Nope and zero support from the tinymce team. My "solution" was to stay on the latest version that doesn't have that problem. I recommend finding another HTML editor (with better support).

**Comment by wambaloo** [comment]
Ok so for information, this problem does not exists anymore on tinyMCE 5. So I upgrade to version 5, it's a low cost migration but it's really efficient.

**Comment by Taygair** [comment]
Tnx for the info. I have created many features around tinymce. I don't know if they will run with 5. Considering the non-existing support of tinymce I tend to switch to another HTML editor provider.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
