### ISSUE TITLE
media embed doesnt update correctly

### ISSUE THREAD

**Issue by ctf0** [tinymce/tinymce#4130]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

changing the media url doesnt update in editor but updates in preview "probably because the embed doesnt work and instead i only see a placeholder img"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

- add a media item to the editor
- press the media button again & try to change the source to something else

**What is the expected behavior?**

- using `media_live_embeds: true,` should show the embed instead i still see a placeholder "the embed only shows up in preview"
- updating the media source should update correctly as it does when editing images

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

tinymce v4.7.4  
chrome v63  
mac os v10.11.6

**Comment by jayarjo** [comment]
Are able to reproduce the problem in this fiddle: http://fiddle.tinymce.com/fhgaab/2?

**Comment by ctf0** [comment]
am using https://www.tinymce.com/docs/configure/file-image-upload/#file_browser_callback, ex.
```js
file_browser_callback(field_name, url, type, win) {
    let field = win.document.getElementById(field_name)

    // open a modal
    $('.modal-toggle').click()

    // listen to file selection event from the modal
    EventHub.listen('file_selected', (path) => {
        if (field) {
            field.value = path
        }
    })
},
```

so the fiddle wont help am afraid

**Comment by ctf0** [comment]
yes, add 
```
https://r3---sn-5hne6nsr.googlevideo.com/videoplayback?ratebypass=yes&source=youtube&dur=152.717&lmt=1512673363784368&key=cms1&ipbits=0&requiressl=yes&gir=yes&signature=84232686355BE86A4F84C1FA7B7A06820A91F76B.07C79CDBFE834692D92BB90FA0C96140B4BB3F3C&id=o-AGaCKAgQ43kr9xMJNbeqU_2TqG3WMl9lQlLqbSkdS_A1&ei=jWNKWtbXM4iT0wXL_r3wBg&itag=18&sparams=clen,dur,ei,expire,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source&mime=video%2Fmp4&pl=22&ip=197.133.18.108&expire=1514846190&clen=9669149&cm2rm=sn-8vq54voxxb-j5ps7s,sn-4g5els7s&fexp=9462444&req_id=9e3bd4a5742aa3ee&redirect_counter=2&cms_redirect=yes&mm=34&mn=sn-5hne6nsr&ms=ltu&mt=1514824473&mv=m
```

as source http://fiddle.tinymce.com/fhgaab/3

**Comment by ctf0** [comment]
@jayarjo any update on this ?
