### ISSUE TITLE
p on enter without class - keep_styles: false

### ISSUE THREAD

**Issue by mozonline** [tinymce/tinymce#4135]
I need to have p on enter without class. 

I supposed, that keep_styles: false should do this. But it doesn't.

Is this a bug or is keep_style not intended to do this. How can I achive a class-less p-tag on enter? 

My current workaround is this:
`        ed.on('keydown',function(e) {
            if(e.keyCode == 13){
                if(ed.dom.hasClass(ed.selection.getNode(), 'Bildunterschrift') || ed.dom.hasClass(ed.selection.getNode(), 'Text') || ed.dom.hasClass(ed.selection.getNode(), 'CityBoard/Unterzeile') || ed.dom.hasClass(ed.selection.getNode(), 'Gallery3 ID')){
                    ed.selection.setContent('<p>&nbsp;</p>');
                    return false;
                } else {
                    return true;
                }
            }
        });`

But this let the cursor jump to the beginning of the preceding paragraph.

**Comment by Katastrophet** [comment]
I am currently having the exact same issue, but with spans.
The documentation states "The keep_styles option will keep the editor’s current text style when a user presses enter/return." Therefore I also tried it with inline-styles, but it seems keep_style=false just has no effect at all. All I found about this issue are old tickets that were closed saying it cannot be reproduced it on TinyMCE4.
This is still an existing and bothersome issue even with TinyMCE5 (5.0.14).
