### ISSUE TITLE
Webpack and angular 4 compatibility

### ISSUE THREAD

**Issue by areeba88** [tinymce/tinymce#4136]
@fyrkant i am using the tinyMCE, run it successfully on separate project with Angular 4,5 generated with angular-cli using the build process of JHipster. with tinyMce 4.7.4 and node 5.3.0 i am providing the accurate path of tinymce styles ,which is, in a folder defined in the asset:"folder" in angular-cli.json but it isn't picking it.  I also follow all the path defined in this documentation [https://www.tinymce.com/](url)
having these errors, 

> 
![img_28122017_151128_0](https://user-images.githubusercontent.com/3445703/34431387-925db85a-ec90-11e7-859c-a5aa11c76ccf.png)

![img_28122017_154343_0](https://user-images.githubusercontent.com/3445703/34431392-9557db12-ec90-11e7-962d-62ad5022474c.png)

i hope you can guide me if i am missing any thing

**Comment by Afraithe** [comment]
Check out the official tinymce-angular wrapper and submit issues there, closing.

**Comment by nphias** [comment]
https://github.com/tinymce/tinymce-angular/issues/119
