### ISSUE TITLE
documentFocusInHandler method in the FocusController leaks memory via the shared parent scope

### ISSUE THREAD

**Issue by ben-mckernan** [tinymce/tinymce#4138]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The documentFocusInHandler method in the FocusController leaks memory via the shared parent scope. The anonymous functions inside the registerEvents method share the same parent scope. Because of this the editor variable is leaked by the documentFocusInHandler method. It is not optimized away since it is used in the other anonymous functions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Run http://fiddle.tinymce.com/mhgaab in Chrome.
2. Open the memory tab in Chrome dev tools.
3. Take a heap snapshot.
4. Type "Editor" into the class filter.
5. See that there are two objects when there should only be one.

**What is the expected behavior?**
A reference to the editor should not be held by the documentFocusInHandler method.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7.4
Chrome 63
Windows 10

**Comment by jayarjo** [comment]
Impressive the way you track these down.

**Comment by ben-mckernan** [comment]
This is fixed by commit 997d944a2a423149d1cbc5f49ec96a6948b2f8e6
