### ISSUE TITLE
Memory leak when removing an editor that has already been removed from the DOM.

### ISSUE THREAD

**Issue by ben-mckernan** [tinymce/tinymce#4139]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The event handlers created by DragHelper are not removed when calling remove on the editor if the editor is no longer in the DOM. Specifically, the destroy method at https://github.com/tinymce/tinymce/blob/master/src/ui/src/main/js/DragHelper.js#L144 will get null returned from the getHandleElm() method an therefore not be able to remove the event listeners.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Run http://fiddle.tinymce.com/phgaab in Chrome.
2. Open the memory tab in Chrome dev tools.
3. Take a heap snapshot.
4. Type "Editor" into the class filter.
5. See that there is one object when there should be none.

**What is the expected behavior?**
The event listeners should be removed regardless of whether the editor is present in the DOM.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7.4
Chrome 63
Windows 10

**Comment by jayarjo** [comment]
Does your fix solve the problem? I can imagine some other hooks that will be left over if you remove editor structures like that. By why would you?

Even more will be left if you for example do not call `remove()` method at all. What does this tell us?

**Comment by ben-mckernan** [comment]
My fix solves the issue for us when I test within our solution. I haven't tested in a TinyMCE only environment but judging from the fiddle I only see the drag helper leaking in this scenario. The reason it is a problem for us is that we run a single page application and the DOM containing the TinyMCE editor is removed before the remove method is called on TinyMCE due to some funky optimization on our part.

So just to be clear we don't remove the editor container like is being done in the fiddle. That was just an easy way to reproduce the issue.

We always call the remove method on TinyMCE. However it should be possible to call the remove method even when TinyMCE is no longer in the DOM and not have it leak memory. At least in my opinion :blush:

Do you need any more information?
