### ISSUE TITLE
Focusing the status bar breaks the keyboard navigation

### ISSUE THREAD

**Issue by ben-mckernan** [tinymce/tinymce#4140]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It is not possible to tab past the editor when branding is enabled.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Open http://fiddle.tinymce.com/qhgaab
2. Focus the first input field
3. Press tab to focus the TinyMCE editor
4. Press tab again to focus the next input field
5. See that the focus ends up in the status bar. Press tab or shift-tab now does nothing as focus is now stuck.

**What is the expected behavior?**
It should be possible to navigate between all the form elements with the keyboard.

**Additional**
This doesn't occur if branding is disabled. However the bug is probably not related to the branding since it is possible to reproduce the trapped focus by clicking on the status bar and then trying to tab.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7.4
Chrome 63
Windows 10

**Comment by ben-mckernan** [comment]
This seems to be fixed by the commit 64261effa7cc468bf30b3ff50bcedc40c2d2f32d

**Comment by fyrkant** [comment]
Yes this has been fixed in the latest release!
