### ISSUE TITLE
Uncaught module [tinymce.core.ui.Api] returned undefined

### ISSUE THREAD

**Issue by kropcik** [tinymce/tinymce#4142]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

It's just simple tinyMCE init script. Its working on local environment, but not working when deployed.
TinyMCE window is not shown and console shows `"Uncaught module [tinymce.core.ui.Api] returned undefined"` error.

```
tinymce.init({
                    selector: '#email_body',
                    height: 200,
                    menubar: false,
                    branding: false,
                    plugins: [
                        'advlist autolink lists link image charmap print preview anchor',
                        'searchreplace visualblocks code fullscreen',
                        'insertdatetime media table contextmenu paste code'
                    ],
                    toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image'
                });
```

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE: ^4.6.5

Browsers:
Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Safari Version 10.0 (12602.1.50.0.10)

**Comment by kropcik** [comment]
Solved it by replaceing:
`require('tinymce')`
to
```
import tinymce from 'tinymce/tinymce';
import 'tinymce/themes/modern/theme';
```

**Comment by stephanebruckert** [comment]
I'm having the same issue but with Ember using `$.tinymce`. Has anyone managed to fix it?

**Comment by fyrkant** [comment]
@stephanebruckert 
Seems like the person above got rid of the error by changing how tinymce was being imported, how are you loading/importing tinymce?

**Comment by stephanebruckert** [comment]
@fyrkant this is how Tinymce is integrated with our Ember app https://gist.github.com/koriroys/dc53d8d7034512a995bc/6f254b373bd88c675cf07abaca9f4dd483e6fca5. Working fine, just not with the latest version of tinymce.

```
  // tinymce
  app.import('bower_components/tinymce/tinymce.min.js', {
    destDir: 'assets/tinymce'
  });
  app.import('bower_components/tinymce/jquery.tinymce.min.js', {
    destDir: 'assets/tinymce'
  });
  app.import('vendor/tinymce/skins/lightgray/skin.css', {
    type: 'vendor',
    outputFile: 'text-editor/tinymce/skins/lightgray/skin.min.css'
  });
  app.import('vendor/tinymce/skins/lightgray/content.css', {
    type: 'vendor',
    outputFile: 'text-editor/tinymce/skins/lightgray/content.min.css'
  });
  app.import('bower_components/tinymce/themes/modern/theme.min.js', {
    type: 'vendor',
    outputFile: '/text-editor/tinymce/themes/modern/theme.min.js',
  });
```

and then in Ember I don't have `require('tinymce')` but I can do:

    component.$('textarea').tinymce(options);

Appreciate your help :pray:
