### ISSUE TITLE
White space after hyperlink being removed when getContent is called

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#4143]
Tested on Chrome 63.0.3239.84 OS X

Steps to repro:
1. Go to http://fiddle.tinymce.com/1hgaab
2. Type a link and hit space, so the autolink plugin transforms the text into a hyperlink
3. See that there is space after the hyperlink
4. Get the content from the editor with editor.getContent() API

Expected:
Trailing white space is present:
```html
<p><a href="http://www.google.com">www.google.com</a> </p>
```

Actual:
White space is trimmed:
```html
<p><a href="http://www.google.com">www.google.com</a></p>
```

**Comment by tinydylan** [comment]
I can reproduce this behaviour on Chrome and Firefox on macOS, using TinyMCE 5.2.1.
