### ISSUE TITLE
Mobile skin breaks file input visibility with Chrome (webpack file-loader)

### ISSUE THREAD

**Issue by plfort** [tinymce/tinymce#4149]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When using the instructions from https://www.tinymce.com/docs/advanced/usage-with-module-loaders/#webpackfile-loader to load the skins, all files in tinymce/skins are included but in skin.mobile.min.css there is this line : 

> input[type="file"]::-webkit-file-upload-button{
display:none
}

This style breaks all file inputs in the page.
Current workaround:
> require.context(
    'file-loader?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/skins',
    true,
    /^((?!(mobile)).)*$/
)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Need webpack

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I am working with 4.7.4

**Comment by frostraver** [comment]
I'm having this issue as well in version 5.0.6

**Comment by zulfarakk** [comment]
Hope you will fix this soon.

**Comment by uapixart** [comment]
Same problem in 5.0.14
