### ISSUE TITLE
TinyMCE "Link" plugin doesn't auto-fill "Text to display" on pure paste event

### ISSUE THREAD

**Issue by biggeleben** [tinymce/tinymce#4156]
Just a little glitch. Edge-case but probably easy to fix.

Steps:
1. Open link popup.
2. Paste URL via mouse, i.e. context-menu. Don't touch any keys.
3. Now, click on "Ok" button.

Current behavior: Technically, you get a link with an empty text node. For the average end-user nothing happens visually.

Expected behavior: The text also gets auto-filled when just using the mouse.

Happens with latest version (also older versions). Checked current sources; the code is just relying on "onkeyup" to call updateText. Guess we need onpaste, too.

**Comment by fyrkant** [comment]
This has been fixed in 4.7.7 released today.

Closing this issue but if you can reproduce it in 4.7.7 leave a comment and I can open it up again.
