### ISSUE TITLE
TinyMCE 4.7.4 does not allow to set styles for table rows

### ISSUE THREAD

**Issue by sashklym** [tinymce/tinymce#4159]
After select border type, styles do not change, and in console we can see:

`plugin.min.js:3 Uncaught TypeError: Cannot read property 'parseStyle' of undefined`

https://jsfiddle.net/sashklym/g5oedffx/

![image](https://user-images.githubusercontent.com/4573740/35114120-595e4f5e-fc8c-11e7-89bc-38a8c4fe1112.png)

**Comment by fyrkant** [comment]
This seems to work on the nightly dev build:

https://jsfiddle.net/g5oedffx/3/

**Comment by fyrkant** [comment]
Closing this as I can't reproduce it in the latest version.
