### ISSUE TITLE
Can TinyMCE support dynamically changing context menu items?

### ISSUE THREAD

**Issue by ktschmincke** [tinymce/tinymce#4160]
To the best of my research skills, TinyMCE does not support a custom dynamic context menu. I want to be able to change the items in my custom menu on the fly, as application state changes. Currently, TinyMCE calculates all the menu items once at initialization, and then never does it again.

Is this something that can be added? It would be a very useful feature as it would give better control over context menu items. I am currently using TinyMCE version 4.7.3.

**Comment by Afraithe** [comment]
Modifying the context menu to actually be context aware is something we would like to get to, currently any context stuff is a bit of hack and special cases, it could definitely both work better internally as well as allow for better customization.

I can't say when we will get to it though, there are other stuff on the list of things todo that have some priority, and even overlap the work.
