### ISSUE TITLE
Tinymce erases the initial slash

### ISSUE THREAD

**Issue by raultrysw** [tinymce/tinymce#4161]
**Do you want to request a *feature* or report a *bug*?**
An issue

**What is the current behavior?**
I created a button in tinymce for uploding images, the server then handles the image sending the final url where the image was stored in in an attribute called filepath, next the tinymce add an img tag in the document, and the image shows as expected, but at the time of sending the image, the image don't shows because the initial slash is erased, so if the images is /photos/aaa.png tinymce chages it to photos/aaa.png

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
Tinymce should no convert any image url

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I am using tinymce from this npm package: https://github.com/j6montoya/vue-tinymce

**Comment by spocke** [comment]
Could be related to relative_urls maybe set that to false.

**Comment by fyrkant** [comment]
No answer on this so I'm closing it.
