### ISSUE TITLE
Allow textcolor plugin to take custom HTML/Angular2 Component

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [tinymce/tinymce#4162]
**Do you want to request a *feature* or report a *bug*?**
- feature

**What is the current behavior?**
- When you click on the textcolor plugin, it opens a pre-determined colorpicker.

**What is the ~expected~ desired behavior?**
- would like to be able to set custom HTML for the colorpicker, specifically being able to inject an angular2 component would help.

**Comment by fyrkant** [comment]
You should be able to use the `color_picker_callback` in the colorpicker plugin to do this:

https://www.tinymce.com/docs/plugins/colorpicker/#color_picker_callback

**Comment by blackbaud-joshlandi** [comment]
That seems to work for the "Custom.." pop out color picker.  But not for the initial color picker that opens up when you click on the textcolor plugin.

![image](https://user-images.githubusercontent.com/12849517/35228199-226c76f4-ff5e-11e7-8cb2-152ab3574da1.png)

**Comment by blackbaud-joshlandi** [comment]
We want to override that initial colorpicker.

**Comment by fyrkant** [comment]
Ah, ok, no that isn't possible and I think you should try to create a custom plugin if you want that functionality.

**Comment by blackbaud-joshlandi** [comment]
I realized it's not possible, that's why I put it in as a feature request.  I'll assume something like this isn't anywhere in tinyMCE's roadmap for a long while.

**Comment by fyrkant** [comment]
I don't see the meaning in adding an option to the textcolor opening a custom thing because that is pretty much all the plugin does. I think it makes more sense just creating a custom colorpicker plugin, using the [current implementation](https://github.com/tinymce/tinymce/tree/master/src/plugins/textcolor/main/ts) as a base.
