### ISSUE TITLE
I need some help with the plugin print

### ISSUE THREAD

**Issue by lukasMacedo06** [tinymce/tinymce#4168]
**Do you want to request a *feature* or report a *bug*?**
I want to request some help, with the print plugin (*bug*, maybe...).

**What is the current behavior?**
I can't change the page setting when I click in print button in tinyMCE.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Just type something in tinyMCE editor, and click in print button, the website title and date will appear.

**What is the expected behavior?**
I want to remove this informations website title and date

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
My current version is 4.7.4.

**Comment by lukasMacedo06** [comment]
Very thanks for the appreciation.
I found it a solution very poor, but it works nice for me.
I get the html inside the tinyMCE plugin and add a rule "@page", to change the document margin.

**Comment by calldeludo** [comment]
i have the same problem... i would need to remove the title and date when the page is printed...
@jayarjo is this feature request abandoned?
@lukasMacedo06 could you share a bit more information? or a example...
Thanks in advance.

**Comment by Tongyaoyu** [comment]
I also want to customize the header and footer when i click pint button，any solutions?
