### ISSUE TITLE
table can not be resized with this HTML code

### ISSUE THREAD

**Issue by hungcrush** [tinymce/tinymce#4169]
this is HTML code. I tested on tinymce.com but I can't resize first column...

[http://tranvinhhung.com/code/table.txt](http://tranvinhhung.com/code/table.txt)

```html
<table style="line-height: 20.8px; font-family: 'Malgun Gothic', '맑은 고딕', 돋움, Dotum, 'Open Sans', Helvetica, verdana, arial, sans-serif; font-size: 9pt; border-top-color: #d3d3d3; border-bottom-color: #d3d3d3;" border="1" width="100%" cellspacing="0" cellpadding="5">
<tbody>
<tr style="height: 64px;">
<td style="width: 17.24%; height: 64px; text-align: center;" valign="top">일일업무 (고객응대, 헬프데스크,버그테스트)</td>
<td style="width: 156.29%; height: 64px;" colspan="3">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 66px; text-align: center;" rowspan="3" valign="top">
<p style="margin: 0px; padding: 0px;">&nbsp;</p>
<p style="margin: 0px; padding: 0px;">&nbsp;</p>
<p style="margin: 0px; padding: 0px;"><span style="line-height: 1.6em; font-size: 9pt;">버그 관련</span></p>
</td>
<td style="width: 52.14%; height: 22px;">* 진행중</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 52.14%; height: 22px;">*신규</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 52.14%; height: 22px;">*처리완료</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">기타업무</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">개선 및 요청사항</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">모바일업무</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
</tbody>
</table>
```

**Comment by hungcrush** [comment]
Please help me...

**Comment by hungcrush** [comment]
`<table style="line-height: 20.8px; font-family: 'Malgun Gothic', '맑은 고딕', 돋움, Dotum, 'Open Sans', Helvetica, verdana, arial, sans-serif; font-size: 9pt; border-top-color: #d3d3d3; border-bottom-color: #d3d3d3;" border="1" width="100%" cellspacing="0" cellpadding="5">
<tbody>
<tr style="height: 64px;">
<td style="width: 17.24%; height: 64px; text-align: center;" valign="top">일일업무 (고객응대, 헬프데스크,버그테스트)</td>
<td style="width: 156.29%; height: 64px;" colspan="3">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 66px; text-align: center;" rowspan="3" valign="top">
<p style="margin: 0px; padding: 0px;">&nbsp;</p>
<p style="margin: 0px; padding: 0px;">&nbsp;</p>
<p style="margin: 0px; padding: 0px;"><span style="line-height: 1.6em; font-size: 9pt;">버그 관련</span></p>
</td>
<td style="width: 52.14%; height: 22px;">* 진행중</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 52.14%; height: 22px;">*신규</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 52.14%; height: 22px;">*처리완료</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">기타업무</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">개선 및 요청사항</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">모바일업무</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
</tbody>
</table>`

**Comment by hungcrush** [comment]
> <table style="line-height: 20.8px; font-family: 'Malgun Gothic', '맑은 고딕', 돋움, Dotum, 'Open Sans', Helvetica, verdana, arial, sans-serif; font-size: 9pt; border-top-color: #d3d3d3; border-bottom-color: #d3d3d3;" border="1" width="100%" cellspacing="0" cellpadding="5">
<tbody>
<tr style="height: 64px;">
<td style="width: 17.24%; height: 64px; text-align: center;" valign="top">일일업무 (고객응대, 헬프데스크,버그테스트)</td>
<td style="width: 156.29%; height: 64px;" colspan="3">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 66px; text-align: center;" rowspan="3" valign="top">
<p style="margin: 0px; padding: 0px;">&nbsp;</p>
<p style="margin: 0px; padding: 0px;">&nbsp;</p>
<p style="margin: 0px; padding: 0px;"><span style="line-height: 1.6em; font-size: 9pt;">버그 관련</span></p>
</td>
<td style="width: 52.14%; height: 22px;">* 진행중</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 52.14%; height: 22px;">*신규</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 52.14%; height: 22px;">*처리완료</td>
<td style="width: 102.76%; height: 22px;">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">기타업무</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">개선 및 요청사항</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
<tr style="height: 22px;">
<td style="width: 17.24%; height: 22px; text-align: center;">모바일업무</td>
<td style="width: 154.9%; height: 22px;" colspan="2">&nbsp;</td>
</tr>
</tbody>
</table>

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
