### ISSUE TITLE
global is not defined (v4.7.5)

### ISSUE THREAD

**Issue by roeycohen** [tinymce/tinymce#4171]
on v4.7.5, using jquery breaks with an error: "global is not defined".

the plugin include this line "...=global || window" which is invalid.

**Comment by YovavGad** [comment]
I confirm the same problem while loading from:
https://cdn.tinymce.com/4/tinymce.min.js
https://cdn.tinymce.com/4/jquery.tinymce.min.js

Also - suggestion:
Stop modifying production version, instead create a new individual version for each release... Ya?

**Comment by fyrkant** [comment]
@YovavGad If you use [TinyMCE Cloud](https://www.tinymce.com/docs/get-started-cloud/) you can specify the exakt minor version you want, like this: http://cloud.tinymce.com/4.7.4/tinymce.min.js

**Comment by YovavGad** [comment]
Oh thank you. fantastic! I wasn't aware.

**Comment by fyrkant** [comment]
The bug is by the way fixed and will be released shortly, so the CDN version should also be working again soon!

**Comment by YovavGad** [comment]
@fyrkant, Now I remember why I didn't use the minor version - it shows a nasty message when used from that URL:

> This domain is not registered with TinyMCE Cloud. 

I liked it more when it was free...

**Comment by solarissmoke** [comment]
@fyrkant the CDN still seems to be serving the broken file. Do you have any update on when this will be fixed?

**Comment by fyrkant** [comment]
This has been fixed in 4.7.6 that was released today so I'm closing this, if you still have a problem just leave a comment and I can open it again.
