### ISSUE TITLE
Un-Bold doesn't work if parent has bold style

### ISSUE THREAD

**Issue by mansooraziz** [tinymce/tinymce#4172]
I think it's a bug. 

Let say we have a block format defined in style_formats which which makes the paragraph bold.
After making the text bold tinymce default 'B' button doesn't work properly. It doesn't recognize if the text is bold or not, and can't un-bold the text.

Example: http://fiddle.tinymce.com/Higaab
(Please not I have used a class p-bold to make the text bold but it doe's the same if I use style='font-weight:bold')
The issue is not only with bold, it's the same with Italic, underline and other defuault formats.

Expected behavior:
- Editor should recognize that the text is bold by checking if the parent is bold
- If parent has bold then on selecting some text and pressing B button should un-bold the text by wrapping the selected text with span tag with font-weight=normal (because that's the only way child element's text can be un-bold when parent is bold)

Version used: 4.7.4

**Comment by Afraithe** [comment]
The correct way would be to use the proper strong tags.
`	style_formats: [	   
		{ title: 'Bold Paragraph', block : 'strong'}		
	],`

**Comment by mansooraziz** [comment]
I have written a custom plugin which creates a custom bold button. It converts the text to bold if it's not bold (even if the bold is applied on any parent class or inline style) and un-bold the text if it's bold. Similarly i wrote plugins for italic and underline as well. I am checking the bold status by using 'document.queryCommandState('bold');'
I think default tinymce button should be doing it as well. it won't slow down the editor by just adding one check i.e. if(document.queryCommandState('bold')){//apply bold format } else {apply un-bold format}

Plugin code:
`(function () {
    var COMMANDS = {
        BOLD: 'cmd_customBold'        
    };

    var FORMATS = {
        BOLD: 'fmt_customBold',
        UNBOLD: 'fmt_customUnBold',        
    };

    // Create the Fake Bullet plugin
    tinymce.create('tinymce.plugins.CustomBold', {
        CustomBold: function (editor, url) {
            editor.on('init', function (e) {
                // get the editor formatter
                var f = editor.formatter;


                f.register(FORMATS.BOLD, {
                    inline: 'span',
                    selector: 'span,p',
                    styles: { fontWeight: 'bold' },
                });

                f.register(FORMATS.UNBOLD, {
                    inline: 'span',
                    selector: 'span,p',
                    styles: { fontWeight: 'normal' },
                });

                editor.addCommand(COMMANDS.BOLD, function () {
                    var formatToApply = currentSelectionIsBold() ? FORMATS.UNBOLD : FORMATS.BOLD;
                    editor.formatter.apply(formatToApply);
                });

                editor.addButton('customBoldBtn', {
                    tooltip: 'Bold',
                    icon: 'bold',
                    cmd: COMMANDS.BOLD,                    
                    onPostRender: function () {
                        var _this = this;   // reference to the button itself
                        editor.on('NodeChange', function (e) {
                            if (currentSelectionIsBold()) {
                                _this.active(true);
                            } else {
                                _this.active(false);
                            }
                        });
                        //override existing mapping for ctrl+b
                        editor.shortcuts.add("meta+b", "Custom BOLD", COMMANDS.BOLD);// "meta" maps to Command on Mac and Ctrl on PC
                    }
                });
            });

        }
    });

    
    // Register plugin using the add method
    tinymce.PluginManager.add('customBold', tinymce.plugins.CustomBold);

    function currentSelectionIsBold() {
        var state = document.queryCommandState('bold');
        return state;
    }
})();`
