### ISSUE TITLE
Allow Plugins To Extend Entity Encoding Functions

### ISSUE THREAD

**Issue by mcavalletto** [tinymce/tinymce#4174]
We are using TinyMCE 4.6.6 and storing results in a MySQL database using the utf8 character set.

Unlike MySQL's utf8mb4 character set, MySQL's utf8 implementation does not support four-byte Unicode characters.

Therefore I want to encode four-byte characters like "👽" into their numeric entity equivalents, like "&amp;#128125;", so I can store them in the database.

However, I don't want to convert other characters like á or 新 to entities, because doing so breaks text searching and plain-text editing — I want "résumé" to still be stored in the database as "résumé".

It was easy to write the necessary encoding function based on the ones I found in tinymce/src/core/main/ts/html/Entities.ts — essentially, I want to use encodeNumeric but matching on a different set of regexes:

```
const attrsCharsAndFourByteRegExp = /[&<>\"\u0060]|[\uD800-\uDBFF][\uDC00-\uDFFF]/g;
const textCharsAndFourByteRegExp = /[<>&]|[\uD800-\uDBFF][\uDC00-\uDFFF]/g;

encodeRawAndFourByte = function (text, attr) {
  return text.replace(attr ? attrsCharsAndFourByteRegExp : textCharsAndFourByteRegExp, function (chr) {
    // Multi byte sequence convert it to a single entity
    if (chr.length > 1) {
      return '&#' + (((chr.charCodeAt(0) - 0xD800) * 0x400) + (chr.charCodeAt(1) - 0xDC00) + 0x10000) + ';';
    }

    return baseEntities[chr] || '&#' + chr.charCodeAt(0) + ';';
  });
};
```

However, I can't figure out how to write a plugin that installs this functions into TinyMCE, either overriding a built-in encoding function or defining an additional encoding function with a new name.

I've tried looking for examples of plugins that define new entity encoding functions or override the built-in ones, but did not find any.

If there is a way of doing this cleanly from a plugin or otherwise applying the change without manually patching the TinyMCE source code, I would love to hear about it!

If not, please consider this a feature request for either allowing such an extension, or for adding a pair of config options that would allow the attrsCharsRegExp and textCharsRegExp expressions to be customized either on a per-instance or global basis.

**Comment by spocke** [comment]
You could do this on the server just set entity_encoding: 'numeric' in tiny then everything above 127 will be encoded into number entities then you can decode the range you want on the server before sticking it into the database field.

We don't have support for adding a custom encoding function right now.
