### ISSUE TITLE
Newest release (4.7.5) doesn't export to webpack

### ISSUE THREAD

**Issue by noahheck** [tinymce/tinymce#4178]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*

**What is the current behavior?**
In versions up to 4.7.4, the `tinymce` object was successfully exported using `module.exports`. In the most recent version, that behavior is gone.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
From the command line, simply run `npm install tinymce --save` or `npm install tinymce@4.7.5 --save`. Then try importing tinymce in a webpack environment e.g. `var tinymce = require("tinymce");`

**What is the expected behavior?**
The same as before.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
We were able to lock the version in our application to 4.7.4 and can continue working, but can't upgrade at this time.

**Comment by ldrick** [comment]
Hi, thats solved with #4165 
Just for the record: I am also waiting for 4.7.6 :+1:

**Comment by fyrkant** [comment]
Can you try installing tinymce nightly like this:

```sh
npm install http://download.ephox.com/tinymce/community/tinymce_nightly.tgz
```

And see if it's working better?

**Comment by ldrick** [comment]
@fyrkant I already gave it a try and it worked for me, I just thought I could answer this issue to motivate @noahheck that's already been fixed :-)

**Comment by fyrkant** [comment]
Oh, sorry yeah that's right I've already talked with you about it! 😅 🙇 

Anyway, 4.7.6 will be release early next week.

**Comment by noahheck** [comment]
Sounds great @fyrkant. We'll keep an eye out for it. Thanks.

**Comment by fyrkant** [comment]
4.7.6 has now been released and should fix this problem.
