### ISSUE TITLE
Bug: Return doesn't work when inline mode is used on a span tag

### ISSUE THREAD

**Issue by fastlinemedia** [tinymce/tinymce#4180]
When I create a new inline editor on a span tag, hitting return doesn't work. You can see that happening in this fiddle... http://fiddle.tinymce.com/ejgaab

Additionally, when I experience this within my app, I get the following error in the console (but not in the fiddle)...

![screenshot 2018-01-25 22 24 03_preview](https://user-images.githubusercontent.com/2453483/35427506-a652cbd6-021e-11e8-9708-66c4480e4de1.png)

Inline editors are being instantiated on user defined content, so switching the span to a div isn't an option for us.

I've tested contenteditable without TinyMCE on a span and return seems to work fine... http://fiddle.tinymce.com/fjgaab

Is it possible to get return working with `<br>` tags in a span element? 

I'm using the latest Chrome on OSX with TinyMCE version 4.6.7.

Thanks!

**Comment by fyrkant** [comment]
`span` is an inline element so that works as expected, although it shouldn't throw errors, can you reproduce it throwing errors in a fiddle? 

If you want to be able to insert newlines you should initialise the editor on a block element, like `div`.

**Comment by ben-mckernan** [comment]
Shift+Enter should insert a `<br />` tag instead but you need to press it twice if the caret is at the end of the content.

Setting `forced_root_block: false` will change this to be on Enter as well as Shift+Enter. But I'm not sure what the other side-effects of this might be. You should read the warnings in the documentation https://www.tinymce.com/docs/configure/content-filtering/#forced_root_block

**Comment by fastlinemedia** [comment]
Thanks! I'll have a look at that.
