### ISSUE TITLE
Init fails with "Operation is insecure"

### ISSUE THREAD

**Issue by apapsch** [tinymce/tinymce#4183]
**Do you want to request a *feature* or report a *bug*?**
This is a bug recently introduced.

**What is the current behavior?**
Tinymce initialization fails with "Operation is insecure" in Firefox.

**Steps to reproduce**

1. Create a page which includes an iframe.
2. Let the iframe load a page which inits tinymce.

The two pages need to be on different domains.

**What is the expected behavior?**
Tinymce should init just fine.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
So far this only happened in Firefox 58.0 on Windows 10. Tinymce used to init just fine last week. I'm using the latest Tinymce URL with no hard coded version.

**Comment by apapsch** [comment]
The version currently served is 4.7.5 (2018-01-22).

**Comment by Afraithe** [comment]
This sounds like issues with crossdomain access, not quite related to tinymce. Are you mixing http/https? CORS etc...

**Comment by apapsch** [comment]
Tinymce script is fetched just fine. This issue is related to tinymce, because the error happens in tinymce initialization code. There must be some reference to window.parent or similar.

**Comment by apapsch** [comment]
I rolled back to 4.7.4, where the error doesn't occur. Still convinced this is not related to tinymce?
