### ISSUE TITLE
Editor is Freezed  when try to append content of 10mb

### ISSUE THREAD

**Issue by manoj-mass** [tinymce/tinymce#4187]
Hi,
Im trying to import a 10mb document into tinymce editor. once that happens the editor get freezed for 5 to 10 mins and seems it is unable to handle the content load. Is this a editor issue ? This happens when you try to copy and past same content to the editor. 

The content size is 10mb, about 1800 pages. Is there any thing we can do to handle larger content ?

Thanks.

**Comment by Afraithe** [comment]
Not ever going to work very well.

**Comment by manoj-mass** [comment]
@Afraithe Some sort of a justification please if possible ? Is this a browser limitation or editor limitation ?

**Comment by Afraithe** [comment]
Both, one does not work without the other.
