### ISSUE TITLE
imagetools: Update image "atomically"

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4189]
**Do you want to request a *feature* or report a *bug*?**

Bug/improvement

**What is the current behavior?**

`Actions.rotate` updates `width` and `height` immediately and then asynchronously updates `src`. The fact that the attributes are not updated all at the same time allows other scripts (triggered by a `MutationObserver`) to see the image in an inconsistent state.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

https://codepen.io/anon/pen/MQYGYY

Check the console to see that the mutation observer allowed me to see the image with inconsistent src and width/height attributes.

**What is the expected behavior?**

src, width and height should be updated all at once, so that a MutationObserver fires only after all attributes have been updated.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Ubuntu 16.04
TinyMCE 4.7.6
Chrome 64.0.3282.119 (Official Build) (64-bit)
Firefox 58.0 (64-bit)

I'm pretty sure other browsers and OSes will exhibit the same issue.

**Comment by donShakespeare** [comment]
We definitely need a core config to allow permanent prevention of image dimensions. LTIC, image tools ignores the `valid_elements` config for image attributes.
So, I use a small inconvenient code to nuke the image dimensions upon change.
So, incase the dimensions are incorrect, I wouldn't notice aught.

**Comment by fyrkant** [comment]
This has been fixed in 4.7.7 released today.

Closing this issue but if you can reproduce it in 4.7.7 leave a comment and I can open it up again.
