### ISSUE TITLE
How do I override the min-height of a tinymce editor?

### ISSUE THREAD

**Issue by sontek** [tinymce/tinymce#4191]
**Do you want to request a *feature* or report a *bug*?**
Both.   I'd like to override min-height, I consider it a bug that you accept "height" but limit it.

**What is the current behavior?**
I set height "25" and I get height "100"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Just try to make the height below 100, you'll see it won't do it.

**What is the expected behavior?**
That it uses the height I pass

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest TinyMCE from npm, Chrome, OSX.

I've seen bug reports from previous versions that say this was a problem. So I think it has been an issue before

**Comment by fyrkant** [comment]
If you want the editor that small maybe it would work better in inline mode, or with the inlite theme? I think it would be very hard to use the normal editor if it was that small.

**Comment by sontek** [comment]
Our use case is they create a list of items that can be styled with HTML, but a lot of times they don't need to style it.     So we basically show a list of small inputs with the text in it with a gear next to it, and then when they click the gear it opens up the fully big text editor with a toolbar in it.

Here is a screenshot:

<img width="264" alt="screenshot 2018-01-31 10 08 46" src="https://user-images.githubusercontent.com/151924/35633427-cc291faa-066e-11e8-8330-db9ac781f6b8.png">

So being able to make the size of TinyMCE work like that is the only thing preventing us from releasing the new version with TinyMCE replacing our current editor

**Comment by sontek** [comment]
I have that UI working with TinyMCE, its just at 100px instead of the smaller size that I would like (50px probably)

**Comment by donShakespeare** [comment]
I use CSS !important to hijack all heights and anything else, if I must use TinyMCE in iframe mode.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by misaki-web** [comment]
[Documentation](https://www.tiny.cloud/docs/tinymce/latest/editor-size-options/#min_height) states:

> If a number is provided, TinyMCE sets the height in pixels. If a string is provided, TinyMCE assumes the value is valid CSS and sets the editor’s height as the string value. This allows for alternate units such as %, em, and vh.

Therefore, we must ensure the height is either of type `number` or a string with an appropriate unit. This means that `min_height: '50'` will not be valid, so the default 100px height will apply, while `min_height: 50` or `min_height: Number('50')` will be valid, and a height of 50px will be applied. We must ensure to convert to `number` when getting the value from elsewhere, if needed.

For example, this won't work:

```js
const height = document.getElementById('editor1').getAttribute('data-height');
console.log(typeof height); // string

tinymce.init({
	selector: "#editor1",
	plugins: "autoresize",
	menubar: false,
	toolbar: false,
	statusbar: false,
	min_height: height,
	max_height: 200,
	width: '50%',
	autoresize_bottom_margin: 0
});
```

However, using `min_height: Number(height)` will work. I created a [demo on TinyMCE Fiddle](https://fiddle.tiny.cloud/YV2hQvYxJu/2).
