### ISSUE TITLE
Version 4.7.6 - Spellchecker - '(No suggestions)' disabled item over the separator

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4194]
I modified the SpellChecker plugin in order to show in the suggestionsMenu a '(No suggestions)' disabled item over the separator instead of only showing a separator when no suggestions. Hope it may help.

https://github.com/lrusso/tinymce-plugin-spellchecker-modified

**Comment by fyrkant** [comment]
Please open up a pull request if you want to contribute code.
