### ISSUE TITLE
Version 4.7.6 - Editor bug - A lot of spaces creates an endless document in a single line when the editor should go to the next line

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4196]
While I was implementing a code in order to use the Tab key in a document, I discovered that if you locate yourself at the beginning of the document and press a lof of times the space key, that line will expand the document width (instead of going to the next line) and the rest of the lines below remains with the 'old' width. Tested in Firefox.

![bug](https://user-images.githubusercontent.com/11498901/35748067-78b2399c-082b-11e8-8ae1-178510751644.png)

https://codepen.io/anon/pen/gvPGqN

**Comment by Afraithe** [comment]
This is because it adds nbsp; when you press multiple spaces like that, there isn't any other way to represent multiple spaces. Not likely we can or will do anything about this issue, so closing it.
