### ISSUE TITLE
On Mac with Chrome, formatted text pasted as image

### ISSUE THREAD

**Issue by ispitzen** [tinymce/tinymce#4197]
Bug report.

Pasting formatted text from word pasted as image. It does not go through the selection of "keep formatting" or "remove formatting".

Open Mac (version El Capitan or above) with MS-Word 2016. 
Copy formatted text from word and paste into TinyMCE (with power-paste extension enabled).
--> the text is copied as an image immediately (skipping the "keep formatting" question).
 
The expected behavior is getting the selection of "keep formatting" or "remove formatting" and data pasted as text.

Additional notes: 
1. Works fine on Windows machines when copying from the windows version of MS-Word into Chrome which is installed also on windows.
2. Observation: the problem **does not** replicate on localhost (when running on dev machines) only once the code is on a separate server and accessed through the browser.

TinyMCE 4.7.6
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Mac OS High Sierra (reproduces on earlier versions as well)
MS-Word 2016 (Mac version)

**Comment by fyrkant** [comment]
Hi!
For help with the premium plugins, please submit a technical support request at the the [support page](https://support.ephox.com) to get help as fast as possible.
