### ISSUE TITLE
Version 4.7.6 - Editor bug - Font names with more than one word has a backslash

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4202]
Font names with more than one word has a backslash in the toolbar. Select the text, change the font to 'Comic Sans MS' and you will see that after that, the font name will be 'comic\ sans...'. Tested in Firefox.

https://codepen.io/anon/pen/VQaYXm

![tinymce_full_featured_-_2018-02-03_16 03 51](https://user-images.githubusercontent.com/11498901/35770545-1a5ec5fa-08fc-11e8-8cbb-9b73d458152c.png)

**Comment by fyrkant** [comment]
This has been fixed in 4.7.7 released today.

Closing this issue but if you can reproduce it in 4.7.7 leave a comment and I can open it up again.
