### ISSUE TITLE
Suggestion code for the core - Tab key

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4203]
Here is a suggestion code for the core of TinyMCE in order to use the Tab key. If the Tab key is pressed and the cursor is outside a table, it will add several spaces. In the other hand, if the cursor is inside a table, it will go to the default event, that it would be to go to the next cell/column/row/etc. The same behaviour as Word, Pages, etc. Hope it may help.

```
editor.on('keydown', function (e)
	{
	if (9==e.keyCode)
		{
		var element=editor.dom.getParent(editor.selection.getNode(),'table');
		if (element==null)
			{
			editor.execCommand('mceInsertContent',false,'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;');
			e.preventDefault();
			return false;
			}
		}
	});
```

**Comment by fyrkant** [comment]
You can get this functionality with the `table` and `nonbreaking` plugins used like this:
http://fiddle.tinymce.com/Cjgaab
