### ISSUE TITLE
Mobile not working on android 4.1.2

### ISSUE THREAD

**Issue by cafidf** [tinymce/tinymce#4206]
The mobile feature does not work on android 4.1.2 with chrome.

The display is ok but when I try to edit by clicking on the book icon, the result is a blank page.
Tested on TinyMCE 4.7.6 with up to date chrome.

**Comment by fyrkant** [comment]
Hi!

I don't think we have stated exactly which version of android the mobile theme will work with, but 4.1.2 is probably too old. Looking at the [usage data](https://developer.android.com/about/dashboards/index.html#Platform) it looks like there are only about 1% of all android devices running that version so I don't think we will invest any time in trying to make it work, although we are always open for contributions if there is someone willing to do it.

**Comment by deep0410** [comment]
https://stackoverflow.com/questions/54579110/is-it-possible-to-disable-the-mobile-ui-features-in-tinymce-5#
