### ISSUE TITLE
"nodechange" event is not raised when selection is changed

### ISSUE THREAD

**Issue by nicklasisraelsson** [tinymce/tinymce#4207]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The nodechange event is not raised every time selection is changed in the editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
These scenarios does not trigger a "nodechange" event when the selection is changed:

- Using ctrl+a to select all text in the editor while the caret is on the first paragraph
- Deselecting a selection by clicking inside the selection 

http://fiddle.tinymce.com/Jjgaab

**What is the expected behavior?**
The above scenarios should raise the "nodechange" event

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
At least 4.7.6. I have not tested on earlier versions.

**Comment by fyrkant** [comment]
A selection change doesn't have to be a node change if the selection changes within the same node, so this isn't a bug but expected behaviour.

**Comment by nicklasisraelsson** [comment]
@fyrkant According to your documentation the nodechange event is supposed to be fired when the selection in the editor changes: https://www.tinymce.com/docs/advanced/events/#nodechange

Is there some other event that can be used to be notified whenever the selection is changed regardless if it's the same node or not?

**Comment by fyrkant** [comment]
There is a `SelectionChange` event you can use instead, like this: 
http://fiddle.tinymce.com/Wjgaab
