### ISSUE TITLE
Issue with fontselector (replace is not a function in theme.js)

### ISSUE THREAD

**Issue by stefanholzapfel** [tinymce/tinymce#4208]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I can't get the fontselect working.

My initial config:
```
        tinymce.init({
            target: this.elementRef.nativeElement,
            skin_url: '../assets/tinymce/skins/lightgray',
            inline: true,
            theme: 'modern',
            menubar: false,
            statusbar: false,
            toolbar_items_size : 'small',
            fixed_toolbar_container: this.attachToolbarToElementWithId,
            toolbar:    'bold italic underline | ' +
                        'forecolor backcolor | ' +
                        'fontselect | ' +
                        'fontsizeselect | ' +
                        'alignleft aligncenter alignright alignjustify | ' +
                        'removeformat',
            font_formats:   'Arial=arial,helvetica,sans-serif; ' +
                            'Courier New=courier new,courier,monospace; ' +
                            'Helvetica=helvetica; ' +
                            'Tahoma=tahoma,geneva,sans-serif;' +
                            'Times New Roman=times new roman,times; ' +
                            'Verdana=verdana,geneva;',
            fontsize_formats: '0.2em 0.5em 1em 1.2em 1.5em 2em',
            plugins: 'paste textcolor colorpicker'
       });
```
I always get
![image](https://user-images.githubusercontent.com/9963536/35860301-d99cfe8e-0b43-11e8-8665-cda51d65887b.png)
when clicking the FontSelector.

The problem seems, that the "encode" function in theme.js is getting an Object instead of a string:
![image](https://user-images.githubusercontent.com/9963536/35860377-1d09a74e-0b44-11e8-83b7-b0542e12b4aa.png)

Anybody else experiencing that problem?

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Google Chrome 64.0.3282.140 on Windows 10
TinyMCE 4.7.6

**Comment by jayarjo** [comment]
Can you reproduce it in this fiddle: http://fiddle.tinymce.com/Rjgaab?

**Comment by stefanholzapfel** [comment]
Seems it was a caching issue, it suddenly works without any changes.

Sorry for your efforts!
