### ISSUE TITLE
The Video tag was replace by img tag when upload the content

### ISSUE THREAD

**Issue by M-Nemo** [tinymce/tinymce#4210]
I try to insert a video in the content such as

```html
<p><video controls="controls" width="300" height="150">
<source src="http://XXXXXXX.mp4" type="video/mp4" /></video></p>
```
but when i upload it ,the tag was replaced by

```html
<p><img class="mce-object mce-object-video" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" width="300" height="150" data-mce-p-controls="controls" data-mce-html="%0A%3Csource%20src%3D%22http%3A/XXXXXX.mp4%22%20type%3D%22video/mp4%22%20/%3E" data-mce-object="video"></p>
```

**Comment by fyrkant** [comment]
That is just a placeholder image in the editor, if you preview the content with the preview plugin you will see the movie. You can test it in this fiddle:

http://fiddle.tinymce.com/Tjgaab

**Comment by phatlamhd** [comment]
Hi @fyrkant the demo cannot play video directly in Editor. I found this example and it can play video directly 
https://www.tiny.cloud/docs-4x/demo/full-featured/

could you update http://fiddle.tinymce.com/Tjgaab to make it works like tiny example ?
Thanks

![image](https://user-images.githubusercontent.com/59215467/101755774-dc31e780-3b07-11eb-8258-479570e6e429.png)

**Comment by phatlamhd** [comment]
@fyrkant I realized that we need include **mediaembed** plugin to make it works, pls ignore my comment
Thanks anyway
