### ISSUE TITLE
Media plugin does not work well with iframes that have height and width set in a style attribute

### ISSUE THREAD

**Issue by brentburg** [tinymce/tinymce#4211]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The media plugin adds `hieght=150` and `width=300` attributes to iframes with explicit height and width set in the style attribute. TinyMCE then moves the style attribute to a containing element in the editor. This has the effect of showing a box in the editor that is the right size, but only showing the the iframe as 300x150.

![screenshot from 2018-02-07 13-54-20](https://user-images.githubusercontent.com/225624/35957070-ca7358ae-0c56-11e8-9114-cb2e73e04eeb.png)
![screenshot from 2018-02-07 13-54-49](https://user-images.githubusercontent.com/225624/35957076-d2d08422-0c56-11e8-810d-a3b0ede13d6c.png)
![screenshot from 2018-02-07 13-55-15](https://user-images.githubusercontent.com/225624/35957078-d634bb10-0c56-11e8-9fa8-828c70012ef3.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

- Go to the TinyMCE homepage (http://tinymce.com).
- In the menu bar select `Tools > Source Code`
- Enter the following: `<p><iframe style="height: 250px; width: 500px;" src="https://tinymce.com"></iframe></p>`
- Click OK
- See the smaller `iframe` inside the box

**What is the expected behavior?**

The media plugins should honor the width and height set in the style attribute and not add the width and height attributes to the iframe (or at least match the values from the style). The iframe preview should fill the entire box in the editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested with TinyMCE versions `4.5.7`, `4.6.7`, and `4.7.6`. Tested with Chrome on Linux, but this does not seem like a browser specific issue.

**Comment by fyrkant** [comment]
This has been fixed in 4.7.7 released today.

Closing this issue but if you can reproduce it in 4.7.7 leave a comment and I can open it up again.
