### ISSUE TITLE
TinyMCE appending user credential info when generating absolute URL, causing contentCSS loading failure

### ISSUE THREAD

**Issue by tamcy** [tinymce/tinymce#4217]
**Do you want to request a *feature* or report a *bug*?**

Looks like a bug to me, but could also be a feature request.

**What is the current behavior?**

*  During init, when there are `contentCSS` items to be loaded, TinyMCE [converts them to an absolute URL](https://github.com/tinymce/tinymce/blob/a4add2940715dd27ef7be8ef42065a8292038787/src/core/main/ts/init/Init.ts#L191) before loading.
* The absolute URL contains the [user info of basic HTTP authentication](https://github.com/tinymce/tinymce/blob/a4add2940715dd27ef7be8ef42065a8292038787/src/core/main/ts/api/util/URI.ts#L93
) if present. 

Take the following config as an example:
```
...
content_css: [
    '/main.css',
    '//fonts.googleapis.com/css?family=Roboto'
],
...
```
Say my website is http://www.example.com. It needs HTTP auth for a particular page. User successfully authenticates with username `foo`  and password `bar`. When I visit another page that loads TinyMCE, the above CSS paths will become:
* http://foo:bar@www.example.com/main.css
* //foo:bar@fonts.googleapis.com/css?family=Roboto

Now there are two problems:
1. Chrome refuses to load both URLs with a `(blocked:origin)` error. The reason seems to be related to this issue: https://www.chromestatus.com/feature/5669008342777856, https://bugs.chromium.org/p/chromium/issues/detail?id=435547.
2. TinyMCE appends the user credential to an external CSS URL ,which seems wrong to me.

CSS loading works again after removing the line that [appends user info to the URL](https://github.com/tinymce/tinymce/blob/a4add2940715dd27ef7be8ef42065a8292038787/src/core/main/ts/api/util/URI.ts#L370).

Of course this not only affects css loading. I'm not sure if there's a use case to append user credentials to the URL of the same domain when requesting asset files. But in case there is one, I'd suggest to allow switching this off via a config value.

Thanks!

**Comment by Afraithe** [comment]
That does indeed not seem optimal, we will look into this, thanks for reporting.

**Comment by spocke** [comment]
Wasn't able to reproduce this since the browser hides any authentication information by default. If I request a page with http://foo:bar@domain/page.html then there is no way for me to even access the foo:bar part as far as I know.

I tested this by setting up a local environment and requesting a page with basic auth with the details passed in like that and it wasn't possible to see that information and it shouldn't be either since that would be insecure.

We need proper steps to follow to reproduce this.

**Comment by tamcy** [comment]
@spocke Thanks for your help. After further investigation, I can now confirm that this has indeed nothing to do with TinyMCE, but a configuration issue - an incorrect URL (with user credentials) was being passed to TinyMCE via the  `document_base_url` option, which is the cause of the problem. I am deeply sorry about that.

**Comment by tamcy** [comment]
That said, there may be a concern when the user credentials in the `document_base_url` are passed to an external domain.

**Comment by spocke** [comment]
I'm closing this one since it's no longer supported by modern browsers and not exposes a.f.a.i.k. Thanks for the report though. It could have been a security issue that we would have needed to fix.
