### ISSUE TITLE
IE11: access is denied

### ISSUE THREAD

**Issue by sangue18** [tinymce/tinymce#4218]
The Demopage (https://www.tinymce.com/docs/demo/full-featured/) [and also a local installation] both throw 'Access is denied' in the JS console with the current build of IE11. Tested on multiple computers with Win10/64 and IE 11.0.50.

Voila the relevant screenshots of the demopage, IE version, JS console...

![kgfhekcagciomeif](https://user-images.githubusercontent.com/36418167/36111101-46b7c388-1025-11e8-8e79-415e3f39765f.png)

![bapbafelbinckakm](https://user-images.githubusercontent.com/36418167/36111104-4bac2d02-1025-11e8-89c8-6896df31724a.png)

![hjhkndlfjobhhilo](https://user-images.githubusercontent.com/36418167/36111107-4e349370-1025-11e8-9bec-01c9777e46a0.png)

![igkmgfogiljapncg](https://user-images.githubusercontent.com/36418167/36111113-524f6e12-1025-11e8-80c4-a6700b575d71.png)

![jhjipbpejippefaa](https://user-images.githubusercontent.com/36418167/36111117-54dac636-1025-11e8-9156-7df7708937ad.png)

**Comment by Afraithe** [comment]
Can't replicate, do you have any changed security settings, seems like the tinymce.min.js file is blocked on your system.

**Comment by sangue18** [comment]
hi & thanks for your reply.
nope, no extra security settings AFAIK. tried turning off avast - didn't help.
I suspect the same, but can't pinpoint the culprit and it seems to be somewhat standard.
tiny works fine in all other browsers. so if there's a block, it has to be IE-specific.
if you let me know what to look for I can debug... registry settings?
i see no other JS issues so far.

**Comment by sangue18** [comment]
Followup:
the ms-error "SCRIPT5" points to 
https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=DE-CH&k=k(VS.WebClient.Help.SCRIPT5)
which suggests, that cross-domain scripts are not allowed. so 
 https://www.tinymce.com/
is not allowed to run scripts from 
 https://cloud.tinymce.com
but honestly, I don't that's the real problem. tried an install with a local apache and got similar behavior/error.

**Comment by sangue18** [comment]
Followup 2:
Was able to find a similar report on git, searching for 'SCRIPT5 and tinyMCE':
    https://github.com/tinymce/tinymce/issues/855
which suggests that IE's setting INTERNET OPTIONS>SECURITY>"Enable protected mode" is the culprit. Tried turning it off... no more problems.
But: IE suggests to activate protected mode over and over again, as soon as it's turned off. so chances are high that this issue might turn up as a enduser-problem. Might also be a setting, IE started using as default...?

**Comment by Afraithe** [comment]
No, with the amount of users we have, if that was the default we should see quite a few reports on it.

Either way, nothing we can do about it, closing this ticket.
