### ISSUE TITLE
Can provide more skin？

### ISSUE THREAD

**Issue by k644606347** [tinymce/tinymce#4222]
**tinymce is excellent, and the use of new technologies is also welcome (Typescript / webpack), thanks 🙏;
But the default skin color is too monotonous, optional skin too little;**

**The ckeditor4.x a lot of good-looking skin, such as this: https://ckeditor.com/cke4/addon/office2013;
I hope tiny skin can become more beautiful;**

**Comment by Afraithe** [comment]
You can visit http://skin.tinymce.com to create your own skin if you wish, there are some predefined skins there as well.
