### ISSUE TITLE
Add repository to tinymce-dist package.json

### ISSUE THREAD

**Issue by Daekard** [tinymce/tinymce#4223]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
No repository metadata is found in the tinymce-dist package.json file

**What is the expected behavior?**
Ideally the package.json file would include the tinymce-dist git repository:
``
 "repository": {
    "type": "git",
    "url": "https://github.com/tinymce/tinymce-dist.git"
  }
``

A small thing, but may help projects using the distribution resources.

**Comment by fyrkant** [comment]
Makes sense, I'll add this for the next release.

**Comment by Daekard** [comment]
Cheers
