### ISSUE TITLE
TinyMCE 4.7.x breaks "Insert link" dialog

### ISSUE THREAD

**Issue by doender** [tinymce/tinymce#4224]
In tinymce 4.7.x the "Insert link" dialog is broken in my app:
![image](https://user-images.githubusercontent.com/4175777/36206808-fa4b10c0-1193-11e8-99c6-811fc1b1904e.png)

This renders fine in in 4.6.7:
![image](https://user-images.githubusercontent.com/4175777/36206833-158dbad6-1194-11e8-9960-633fc52e8197.png)

Any idea what causes this?

**Comment by fyrkant** [comment]
This is probably caused by some css in your implementation, can you create a minimal reproduction in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by ben-mckernan** [comment]
@doender can you confirm whether you have multiple TinyMCE themes loaded as described in #4263?
