### ISSUE TITLE
"content_css" with query string no longer appears in "styleselect" classes submenu.

### ISSUE THREAD

**Issue by connelly-steve** [tinymce/tinymce#4227]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Classes added through "content_css" with a query string are useable in editor content but not are no longer appended to "styleselect".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Write a class in a CSS file.
2. Set this file to be loaded with "content_css".
3. Add "importcss" to the "plugins" string.
4. Set "importcss_append" to true.
5. Set "importcss_groups" to [{ title: "Styles (CSS)" }].
6. Add "styleselect" to the "toolbar" string.
7. Use the previously written class in the editor content.
8. Add a query string to "content_css".
9. Reload the page.

**What is the expected behavior?**
Previously, classes were added to the Styles (CSS) submenu of the Format toolbar button.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I tested 4.7.5 and 4.7.6 with Chrome, Edge and Firefox running on Windows 10. It worked in 4.7.2 and I believe it still worked in 4.7.4. As far as IE is concerned, we use 4.5.8 and it works.

**Edit:** Confirmed. It works in 4.7.4.

**Comment by jayarjo** [comment]
Reproduced it here: http://fiddle.tinymce.com/Ikgaab/1. Try latest version and then 4.5.8 (works in the latter).

**Comment by connelly-steve** [comment]
@jayarjo , thanks for the follow up!

**Comment by effetb** [comment]
Hi, Same problem here, do you have an idea when the fix will be available ?

**Comment by connelly-steve** [comment]
Hi @jayarjo and @effetb ! I read the changelog for 4.7.10 and installed it. I can confirm the bug to be fixed.
