### ISSUE TITLE
Bug: TinyMCE tries to load en_US language when 'language: en_US'

### ISSUE THREAD

**Issue by webketje** [tinymce/tinymce#4228]
**Bug**:  `Failed to load plugin url: https://cloud.tinymce.com/stable/langs/en_US.js`
**Expected behavior**: TinyMCE shouldn't load a language file when en_US is set as language setting. The expected behavior can only be achieved by *not* specifying a language setting.
**Reproduce**: Init a TinyMCE instance with `language: 'en_US'`.

**Comment by Afraithe** [comment]
That is kind of by design if you wanted to override, as you notice, you shouldn't set it if you aren't changing the language.
