### ISSUE TITLE
Bug - Tiny mce doesn't handle quote in font family

### ISSUE THREAD

**Issue by michelle-wong** [tinymce/tinymce#4230]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when copy and paste a text with font family that has quote  e.g. 
`<span style="font-family: &quot;72-Web&quot;; color: rgb(255, 174, 207);" data-mce-style="font-family: '72-Web'; color: #ffaecf;">adsfaasdfasdf</span>`
tiny mce tried to clean the content and return
`'font-family: "color: rgb(255, 174, 207)' `
in the style, causing the font-family and color attribute to become invalid, and thus the copied text shows up without those styles

**What is the expected behavior?**
should handle quote properly

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by fyrkant** [comment]
It has to look like this for it to work: http://fiddle.tinymce.com/7kgaab
