### ISSUE TITLE
How to store source code generated in a db ?

### ISSUE THREAD

**Issue by hjjobs** [tinymce/tinymce#4231]
i have to store the source code in a DB for further use. Example i have to store this 
![image](https://user-images.githubusercontent.com/13882879/36303651-e57a6bdc-1332-11e8-9cf2-ff79736bea5e.png)

in a DB.
How do i store this ?
and where can i find this data ?

**Comment by Afraithe** [comment]
This isn't a support system, this is for tracking issues (bugs) around the product.
