### ISSUE TITLE
 Version 4.7.7 - Editor bug in Firefox only - A lot of spaces creates an endless document in a single line when the editor should go to the next line

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4233]
I tested this example in Chrome and in Firefox, and in Chrome works great and the editor go to the next line while typing, but in Firefox, the editor makes one endless line. I attached a few screenshot of this example in both browsers.

Locate yourself at the beginning of the document and press a lof of times the space key, that line will expand the document width (instead of going to the next line) and the rest of the lines below remains with the 'old' width. Bug verified in Firefox, but not in Chrome.

https://codepen.io/anon/pen/gvPGqN

![parte1](https://user-images.githubusercontent.com/11498901/36404594-54f8eb52-15ca-11e8-846f-0ccdd63b0008.png)

![parte2](https://user-images.githubusercontent.com/11498901/36404598-58a33fa0-15ca-11e8-8768-7d4c544d8a62.PNG)

**Comment by fyrkant** [comment]
Has this changed since #4196?

**Comment by lrusso** [comment]
No, it doesn't. I uploaded the screenshots of both browser in order to show that it was actually a bug.

**Comment by fyrkant** [comment]
Ok, then I'm sorry but I'll just have to repeat what Joakim told you there:

> This is because it adds nbsp; when you press multiple spaces like that, there isn't any other way to represent multiple spaces. Not likely we can or will do anything about this issue, so closing it.

That it looks different in Firefox probably caused by some difference in how the browsers represent nbsp.
