### ISSUE TITLE
Version 4.7.7 - Editor bug in Firefox - When the cursor is placed before a table, a huge cursor scrolls the document to the bottom of the table

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4234]
When the cursor is placed before a table, a huge cursor scrolls the document to the bottom of the table. Tested in Firefox. In the following link, just load the page and you will see the bug, you don't have to do anything.

https://codepen.io/anon/pen/ZrxGPZ

**Comment by spocke** [comment]
We have a fix for this one however the caret before the table is a feature so that you can type before a table similar to chrome. However we fixed so that it doesn't scroll when it renders this caret on FF.

**Comment by lrusso** [comment]
Thank you very much for the fast reply and such a great service!

**Comment by fyrkant** [comment]
This has been fixed in 4.7.8 released today.

Closing this issue but if you can reproduce it in 4.7.8 leave a comment and I can open it up again.

**Comment by lrusso** [comment]
Hello, the bug remains in 4.7.8, tested in Firefox.

**Comment by fyrkant** [comment]
@lrusso I'm having problems reproducing this in 4.7.8 and 4.7.9, seems fixed to me, when I click left of the table it no longer scrolls down: http://fiddle.tinymce.com/mlgaab

**Comment by lrusso** [comment]
In 4.7.8, when you focus the document, and the cursor is before a table, the editor will scroll to the bottom of the table. Tested in Firefox:

http://fiddle.tinymce.com/ylgaab

In 4.7.9 this was fixed, thank you for that!
