### ISSUE TITLE
Table toolbar from inlite theme does not disappear on blur after entering text in cell

### ISSUE THREAD

**Issue by eryi** [tinymce/tinymce#4239]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Table toolbar from inlite theme does not disappear on blur after entering text in cell

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://www.tinymce.com/docs/demo/inlite/
1. Insert a new table -> the table toolbar should be visible
2. Enter any text in any cell 
3. Click anywhere else on the page outside the editor

**What is the expected behavior?**
Table toolbar from inlite theme should disappear on blur after entering text in cell

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested on tinymce.com in Chrome browser

**Comment by fyrkant** [comment]
This has been fixed in 4.7.8 released today.

Closing this issue but if you can reproduce it in 4.7.8 leave a comment and I can open it up again.
