### ISSUE TITLE
"Paste as text" does not work in 4.7.7

### ISSUE THREAD

**Issue by rjpepmeyer** [tinymce/tinymce#4242]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
    
Content is pasted with full formatting, even when "Paste as text" is selected.
    
1. Go to [the fiddle page](http://fiddle.tinymce.com/)
2. Open the "Edit" menu and select "Paste as text"
3. Paste in formatted content
    
**What is the expected behavior?**

The text should be pasted in without any formatting.
    
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
    
This is a new bug for 4.7.7 that did not affect 4.7.6 or earlier. I have tested it on MacOS on the latest versions of Safari, Chrome, and Firefox.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
