### ISSUE TITLE
Change in the toolbar - warning that the domain is not registered

### ISSUE THREAD

**Issue by MiBuena** [tinymce/tinymce#4243]
I would like to report a bug.

I use the Community version. I have an API key. I have downloaded the tinymce js files locally. We are still in development so we work on localhost still.

When I try to change the Editor toolbar - for example remove an icon from the toolbar - I start getting the message that the domain is not registered.

I expect that I should be able to change the toolbar without such false warnings.

This happens only when the file is downloaded. If I reference the cloud directly and put the api key at the end - the message doesn't appear. Still I would like to use my local file.

Please, for your assistance.

**Comment by tinydylan** [comment]
Hi,

Downloading the files from Tiny Cloud is not supported. You'll need to reference the cloud directly.

If you wish to run the open source edition of TinyMCE, I'd suggest downloading it from [here](https://www.tiny.cloud/get-tiny/self-hosted/) or using npm.

Thanks!
