### ISSUE TITLE
Indentation Feature Request

### ISSUE THREAD

**Issue by brucesenger** [tinymce/tinymce#4245]
**Do you want to request a *feature* or report a *bug*?**
FEATURE

**What is the current behavior?**
When Indentation is selected for a block of text, the text indents fine when viewed within Web Browsers however it does not indent within HTML emails. This is due to Indentation currently using Padding in lieu of Margin.

**What is the expected behavior?**
Provide an option to choose indentation method using Margin or Padding.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by fyrkant** [comment]
Hi! Seems like we already have this functionality but never added it to the documentation, so I added it now: https://www.tinymce.com/docs/configure/content-formatting/#indent_use_margin

**Comment by brucesenger** [comment]
Thank you!
