### ISSUE TITLE
Template selector bug after a scroll

### ISSUE THREAD

**Issue by remijean** [tinymce/tinymce#4248]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The top position of the template selector options is incorrect after scrolling the page.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

- Do not scroll the page,
- Click on the selector,
- The position of the options is correct:

![image](https://user-images.githubusercontent.com/4329231/36595952-59e165a4-18a4-11e8-8475-4a6616cf3b7c.png)

- Close the selector,
- Scroll the page,
- Click on the selector,
- The position of the options is incorrect:

![image](https://user-images.githubusercontent.com/4329231/36596035-ab77c5c0-18a4-11e8-85de-1beadd8ade01.png)

**What is the expected behavior?**

TinyMCE version : 4.7.7
OS : Windows 10
Browser : Chrome version 64.0.3282.186 (Build officiel) (64 bits)

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
