### ISSUE TITLE
Readonly = true does not work when the contentedtible is true for an element

### ISSUE THREAD

**Issue by mbaneryd** [tinymce/tinymce#4249]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
When the editor is set to readonly it is still possible to modify elements that has contenteditable=true

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/algaab

**What is the expected behavior?**
Nothing inside the editor should be editable when the editor is read only

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I tested back to 4.4.0 and it is reproducable all the way up to Edge (4.7.7)

**Comment by TheSpyder** [comment]
This was fixed in 4.7.12, sorry the ticket was never closed. The fix caused other issues, however, so a patch may be available soon in 5.x.
