### ISSUE TITLE
TypeError: Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by maiconcosta** [tinymce/tinymce#4257]
When using the setContent function of TinyMCE I get this error: TypeError: Can not read property 'parse' of undefined

Here is my code below:

ngAfterViewInit() {   
  tinymce.init({
    selector: 'textarea',
    plugins: ['link', 'image'],
    language: this.translation.translate('filiais.empresa.idioma-editor'),
    height: 500,     
    setup: editor => {
      this.editor = editor;
      editor.on('keyup', () => {
        const content = editor.getContent();
        this.onEditorKeyup.emit(content);
      })    
    }   
  });   
}

private preencherEmpresa(empresa) {
  this.empresa = new Empresa(
    empresa.empre_codigo, empresa.empre_nome,
    empresa.empre_cnpj, empresa.empre_endereco,
    empresa.empre_termos, empresa.empre_bundle,
    empresa.empre_cdn
  );   
  this.editor.setContent(empresa.empre_termos);
}

**Comment by fyrkant** [comment]
This is happening because you are trying to set the content before the editor has been fully initialized. This will be fixed (in the way that it won't throw an error) in an upcoming release, but I would recommend you to use out official angular wrapper instead where we already check for this: https://github.com/tinymce/tinymce-angular

**Comment by maiconcosta** [comment]
Ok, I tried doing the integration, but I get the following error: Error: Template parse errors: 'editor' is not a known element

**Comment by fyrkant** [comment]
That error sounds like you haven't added the editormodule to your app.

**Comment by maiconcosta** [comment]
Consegui, obrigado!
Agora gostaria de saber só mais uma coisa:
Vi na configuração que o [init] recebe a configuração. Como eu poderia ler as variáveis do component.ts nessa diretiva?
Tentei colocar [init]="configEditor" mas sem sucesso.

**Comment by maiconcosta** [comment]
I got it, thank you!
Now I would like to know one more thing:
I saw in the configuration that [init] receives the configuration. How can I read the component.ts variables in this directive?
I tried putting [init] = "configEditor" but without success.

**Comment by fyrkant** [comment]
If you have a `configEditor` property on you class then you should be able to bind it like that. So with a component file like this:

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  myConfig = {
    inline: true,
    plugins: 'link',
    toolbar: 'link'
  };
}
```

You can have a template like this:

```html
<editor [init]="myConfig"></editor>
```

I'm closing this issue as it really isn't a problem with TinyMCE, if you have any more questions about the tinymce-angular package open up an issue on that repo instead, thank you!

**Comment by maiconcosta** [comment]
I got it here, thank you!

**Comment by AdityaPawar2** [comment]
I am getting same error on setContent. I am able to getContent. Is it still not fixed ?
![image](https://github.com/tinymce/tinymce/assets/106816674/9828ca36-f67c-46c8-8ff7-a10af30a839c)

**Comment by TheSpyder** [comment]
@AdityaPawar2 your error is in a plugin, not the editor. It's looking for an `initParsed` function or property. I can't find a reference to this in our code.

**Comment by AdityaPawar2** [comment]
@TheSpyder Ya this error was solved when I removed 3rd party plugins. Issue seems with 3rd party plugins.
