### ISSUE TITLE
Feature request: Plugin for converting the content to AMP compatible html

### ISSUE THREAD

**Issue by buihoanghai** [tinymce/tinymce#4259]
Currently I see a lot of pages are using [AMP](https://www.ampproject.org/). It will be helpful if we have a plugin for converting to AMP.

**Comment by fyrkant** [comment]
I'm not sure this is something that should be a part of TinyMCE, it is probably easier to convert to and serve AMP from the server side. It is anyway not something we will implement in the foreseeable future.

**Comment by nethherman** [comment]
I've done to convert it into, e.g. <img to <amp-img and it works fine. But when I fetch it from the database and show it in textarea of TinyMCE, it doesn't show the <amp-tag even <img tag
