### ISSUE TITLE
 Cannot read property 'parentNode' of null after selecting bullet/numbered list

### ISSUE THREAD

**Issue by grzeskiba** [tinymce/tinymce#4265]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

An exception is thrown after select/deselect bullet/numbered list:
Uncaught TypeError: Cannot read property 'parentNode' of null

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Create a paragraph with a long text
2. Split the paragraph with 2 blank lines
3. Select text and select/deselect bullet list

**What is the expected behavior?**
The exception is not thrown and the selected text has a list style

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Browser: Chrome Version 64.0.3282.140 (Official Build) (64-bit)
OS: Ubuntu 16.04 LTS
Tinymce Version: 4.7.0

![image](https://user-images.githubusercontent.com/10499947/36961010-dc588984-2062-11e8-9111-277539aabafb.png)
![image](https://user-images.githubusercontent.com/10499947/36961030-f39cb5b6-2062-11e8-98c9-be3b0fecdfb9.png)

**Comment by SimonFc** [comment]
Works as of version 4.7.11. Version 4.9 will include a rewrite of the affected code aswell.
