### ISSUE TITLE
Add a translation for "Preformatted"

### ISSUE THREAD

**Issue by LingSpb** [tinymce/tinymce#4266]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
We use the text "Preformatted" in FormatSelect but we don't have a translation for it yet

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
Add a translation for the text "Preformatted"

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by fyrkant** [comment]
I have now added the `Preformatted` string to the transifex source language so you can add an translation to it in the language that you need here: https://www.transifex.com/projects/p/tinymce/
