### ISSUE TITLE
Version 4.7.9 - Editor bug - Several bugs while scrolling up and down using tables

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4271]
Tested in Firefox.

Bug 1) Position yourself before the first table (a huge cursor will appear). Now press the down key. Now you will see that the 'undo' icon is enabled as if the scrolling down with the down key would be an event or change in the document.

Bug 2) Position yourself before the first table (a huge cursor will appear). Now press the down key. Now, use the mouse to scroll down using the vertical scroll bar and you will see that the cursor is below the first table but the editor didn't scroll down when this happened.

Bug 3) Position yourself before the first table. Now press the down key several times until you reach the end of the document. Now press the up key several times and eventually you will see that the editor doesn't follow the cursor and doesn't respond to the up key.

http://fiddle.tinymce.com/mngaab

**Comment by lnewson** [comment]
I tested this using TinyMCE 4.9.10 and 5.2.2 on Firefox 75.0 and it appears that points 1 & 3 have been fixed somewhere around TinyMCE 4.7.10. However point 2 is still an issue, as the editor isn't scrolling the caret into view.
