### ISSUE TITLE
Autosave plugin - missing autosave_restore_when_empty implementation

### ISSUE THREAD

**Issue by OndrejVasicek** [tinymce/tinymce#4274]
In the autosave plugin there is no implementation of the option `autosave_restore_when_empty`. If I open the plugin code, there are all the options from the docs but not the `autosave_restore_when_empty`.

And the result of course is, that the plugin doesn't work as the docs says.

Checked on version 4.7.7 and 4.7.9.

**Comment by gzzo** [comment]
@fyrkant I have a PR that fixes this issue, how do we get this merged in?

**Comment by vctormb** [comment]
I'm trying to use `autosave_restore_when_empty` too and yep... it does not work. Will it be merged soon?

**Comment by gzzo** [comment]
#4447 was merged. This issue can be closed.

**Comment by OndrejVasicek** [comment]
Yep, it's working now. Thank you.
