### ISSUE TITLE
Version 4.7.9 - Spellchecker bug - The editor selects another word as a misspelled word

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4280]
Tested in Firefox 57. Click in the Spellchecker Icon and you will see that the editor selects another word as a misspelled word. Also, the suggestionsMenu shows two empty suggestions. In latest version of Firefox, in the same fiddle, the editor doesn't underline anything.

![example](https://user-images.githubusercontent.com/11498901/37518819-9705c2fc-28f5-11e8-8a84-ca2b90728048.jpg)

http://fiddle.tinymce.com/5ngaab

**Comment by fyrkant** [comment]
So there's no problem in the latest version of Firefox?

**Comment by lrusso** [comment]
In the latest version of Firefox, no words are underlined in that fiddle. I'm guessing that it should be underlined that last part of the url (aKJlwjXeo).

**Comment by fyrkant** [comment]
The last part of the url is `2a7KJlwjXeo` not `aKJlwjXeo`, that's why it isn't finding it.
