### ISSUE TITLE
Dropdown options in dialogs are not visible when the editor is in a fixed container (e.g. a modal)

### ISSUE THREAD

**Issue by seckin92** [tinymce/tinymce#4281]
We're using TinyMCE in a modal dialog, and we have to use the `ui_container` in order to keep `floatpanel`s in place (see #3592).

TinyMCE appends the "dialogs" (such as "Insert Link")  to `document.body`, disregarding the `ui_container` setting, while the `floatpanel`s like dropdown options are still being appended to the specified `ui_container`. This causes the `floatpanel`s like dropdown options inside TinyMCE dialogs to fall behind the dialog window as seen below.

![image](https://user-images.githubusercontent.com/1876867/37478329-d3d6e5aa-2871-11e8-896c-1449787433de.png)

I've tracked this down to the following line; the dialogs are rendered into `document.body`:
https://github.com/tinymce/tinymce/blob/ec35e25c6e5ba6fc699d65742792b7929e4318fc/src/ui/main/ts/WindowManagerImpl.ts#L79

Here is [a codepen that reproduces this behaviour](https://codepen.io/seckin/pen/LdNEyO)

Also, if we don't use `ui_container`, the dropdown options are positioned incorrectly depending on the scroll position:

At the top of the window (good behaviour):
![image](https://user-images.githubusercontent.com/1876867/37478573-7816851c-2872-11e8-91e0-3b144bb489fa.png)

Scrolled down a bit, and then clicked the target dropdown (incorrectly positioned options):
![image](https://user-images.githubusercontent.com/1876867/37478603-9656d6d0-2872-11e8-97ca-1c214397cb73.png)

Any ideas how to get around this?

**Comment by seckin92** [comment]
This is not ideal, but I'm currently getting around this by polling for the dialog element and moving it into the desired parent. Here is [a codepen demonstrating the solution](https://codepen.io/seckin/pen/zWBVKm).

```ts
setInterval(function moveTinyMceDialogInsideModal() {
  
  function getTinyMceDialog() {
    return document.querySelector('body > [role=dialog].mce-window');  
  }
  
  function getContainer() {
    return document.querySelector('.ms-Dialog-main');
  }
  
  let dialog: Element = getTinyMceDialog();
  if(dialog) {
    let container: Element = getContainer();
    if(container) {
      container.appendChild(dialog);
    }
  }
}, 100);
```

**Comment by ben-mckernan** [comment]
We are also experiencing this behavior. Setting an interval to manually move the float panel is not a viable solution.
