### ISSUE TITLE
Version 4.7.9 - bug - After using webpack, firefox loads and loses.

### ISSUE THREAD

**Issue by gx1727** [tinymce/tinymce#4282]
**Do you want to request a *feature* or report a *bug*?**
After using webpack, firefox loads and loses. Tracking code found
```"tinymce/src/core/main/ts/api/EditorManager.ts", ```line 222
`If (!baseURL && document.currentScript) {`
In firefox, there is a problem with **currentScript**, so it is not possible to get the baseURL normally.

Firefox 58.0.2 (64)

**Comment by fyrkant** [comment]
I need a lot more info to be able to take a look at this - can you create a simple reproduction in a github repo that I can take a look at?
