### ISSUE TITLE
Pasting Table Copy on Table Selection Creates Another Table Inside Table

### ISSUE THREAD

**Issue by kamilersz** [tinymce/tinymce#4283]
I'd like to report a bug

When I tried to paste a matched rows x cells into selection, this creates another table inside the cell.
![image](https://user-images.githubusercontent.com/2652633/37501127-7605732c-28ff-11e8-8994-401babd710d2.png)
![image](https://user-images.githubusercontent.com/2652633/37501145-911b2bac-28ff-11e8-8468-1d54f1a0ceb9.png)

The pasted content should be just replacing the content.
![image](https://user-images.githubusercontent.com/2652633/37501156-a0ea6282-28ff-11e8-91ef-72530260ad3f.png)

This appears in here https://www.tinymce.com/docs/demo/full-featured/

Thank you

**Comment by fyrkant** [comment]
I'm having problems reproducing this, what browser are you using?

**Comment by kamilersz** [comment]
I'm using Chrome version 71.0.3578.98 on Windows 10

Still happens now
