### ISSUE TITLE
4.7.6 Superscript and Subscript can not be reset by using Paragraph

### ISSUE THREAD

**Issue by nicohartto** [tinymce/tinymce#4284]
**Do you want to request a *feature* or report a *bug*?**

Feature clarification on how Superscript and Subscript are intended to work in Formats-dropdown.

**What is the current behavior?**

1. Choose part of text
2. Apply "Superscript" or "Subscript" on that part of text
3. Apply "Paragraph" on that part of text
4. "Superscript"/"Subscript" is still applied and text is not "Paragraph"

**What is the expected behavior?**

I think this could go either way, as it is now. This makes sense that Sup/sub scripts are not reset if user selects the surrounding text to be something else.

Again, it might feel out-of-place since these options do not work similarly to other options in the formatting dropdown (e.g. Headings, Paragraph etc..).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested with 4.7.6. Firefox 59.0 on MacOS X

**Comment by fyrkant** [comment]
Super- and subscript are inline elements, while paragraphs and headings are block elements so they won't work the same way. If you want to clear the paragraph of all inline elements you can use the "Clear formatting" option in the "Format" menu.
