### ISSUE TITLE
Where does tinymce save doc ?

### ISSUE THREAD

**Issue by goodforever** [tinymce/tinymce#4286]
Where does tinymce save doc ?

**Comment by fyrkant** [comment]
Do you mean when using the [save plugin](https://www.tinymce.com/docs/plugins/save/)?

**Comment by goodforever** [comment]
No, I want to know where the doc is saved (fs dir or database ?),when I run tinymce on node.js vm .

**Comment by fyrkant** [comment]
Not sure what you mean with running on a nodejs VM, but you can read about how to save content from the Editor in the documentation: https://www.tinymce.com/docs/get-started/first-steps/
