### ISSUE TITLE
Dropdown menu of a dialog does not follow when dragging the dialog

### ISSUE THREAD

**Issue by seraph17** [tinymce/tinymce#4293]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Dropdown menu of a dialog does not follow when dragging the dialog

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
In the official Full featured demo
1. open the **Insert link** dialog
2. click to show the dropdown
3. drag to move the dialog

**What is the expected behavior?**
Dropdown menu should follow the dialog or be hidden.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7.9
![screen shot 2018-03-23 at 11 55 17](https://user-images.githubusercontent.com/5106157/37825981-174f19da-2e92-11e8-91c1-d94fe73cdd30.png)

**Comment by fyrkant** [comment]
This has been fixed in the newly released 4.7.11 release.
