### ISSUE TITLE
Suspicious code

### ISSUE THREAD

**Issue by PetrToman** [tinymce/tinymce#4294]
1. Install closure-compiler: `npm -g install --save-dev google-closure-compiler-js`
2. Build TinyMCE
3. Pack everything together: `grunt bundle --themes=modern --plugins=advlist,anchor,autolink,autoresize,autosave,bbcode,charmap,code,codesample,colorpicker,contextmenu,directionality,emoticons,help,fullpage,fullscreen,hr,image,imagetools,importcss,insertdatetime,legacyoutput,link,lists,media,nonbreaking,noneditable,pagebreak,paste,preview,print,save,searchreplace,spellchecker,tabfocus,table,template,textcolor,textpattern,toc,visualblocks,visualchars,wordcount`
4. Run `google-closure-compiler-js tinymce.full.js > tinymce.full.min.js`
5. Warnings will be printed:

```tinymce.full.js:1224 (JSC_NEGATING_A_NON_NUMBER_ERROR)
Can't negate non-numeric value: NEW 1224 [length: 10] [source_file: tinymce.full.js]
  var expando = 'sizzle' + -new Date();
                            ^

tinymce.full.js:1288 (JSC_USELESS_CODE)
Suspicious code. The result of the 'getprop' operator is not being used.
    arr[preferredDoc.childNodes.length].nodeType;
    ^

tinymce.full.js:1865 (JSC_USELESS_CODE)
Suspicious code. This code lacks side-effects. Is there a bug?
        if (elem.parentNode) {
        ^

tinymce.full.js:1866 (JSC_USELESS_CODE)
Suspicious code. The result of the 'getprop' operator is not being used.
          elem.parentNode.selectedIndex;
          ^

tinymce.full.js:50733 (JSC_UNREACHABLE_CODE)
unreachable code
      var _a;
      ^
```

**Comment by fyrkant** [comment]
I think that the typescript compiler would tell us if we had useless/unreachable code in the code base, so I'm not sure that this is correct. Any way, as there doesn't seem to be any security problems or anything like that I think I'll close this. But thank you for experimenting!
