### ISSUE TITLE
Error with command InsertUnorderedList/InsertOrderedList when empty lines selected

### ISSUE THREAD

**Issue by rolandliwag** [tinymce/tinymce#4298]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error in console: TypeError: Cannot read property 'parentNode' of null

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Enter one line of text followed by multiple empty lines of text
2. Select all text content
3. Toggle [un]orderedList three times using toolbar or programmatically

**What is the expected behavior?**
Selected text should have ol/ul state toggled.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Seen on TinyMCE 4.7.4. Also reproducible on https://www.tinymce.com/docs/demo/basic-example/

**Comment by fyrkant** [comment]
Duplicate of #4265
