### ISSUE TITLE
AMP-IMG not showing in textarea TinyMCE

### ISSUE THREAD

**Issue by nethherman** [tinymce/tinymce#4308]
I use the latest free TinyMCE Editor. I try to convert `<img` to `<amp-img` and saved into my database and it works fine. But when I fetch it from the database and show it in textarea of TinyMCE, it doesn't show the `<amp-img` tag even `<img` tag
I also post this issue to: https://stackoverflow.com/questions/49567114/html-tag-amp-img-not-showing-after-fetch-from-database-using-tinymce.

Here's the code using `amp-img` tag that must be shown inside textarea of TinyMCE:

`<amp-img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIwAAAAoCAIAAACjL4WRAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyBpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNSBXaW5kb3dzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjAwRDlCMzZBN0VBMjExRTQ4QzkwQkFFQ0VBM0E2MENGIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjAwRDlCMzZCN0VBMjExRTQ4QzkwQkFFQ0VBM0E2MENGIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6MDBEOUIzNjg3RUEyMTFFNDhDOTBCQUVDRUEzQTYwQ0YiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6MDBEOUIzNjk3RUEyMTFFNDhDOTBCQUVDRUEzQTYwQ0YiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz5opNLoAAAIIElEQVR42uxbeUwUVxifYw9gAblBQE4XKygIYlVsRIg2rQYsakpQa+QPq9Gkia3+ZarW2FAPmmgxFTVp1dqm1dCg8SrCUkUqWiwlCFYQBLnkRpZjj5nXb3YosDOzC7uAYjNfyOPNvGOG7/cdv+/tgiOEMFGmthCiCkSQRBFBEkESRQRJFBEkESRRRJBEEUF600RixRrUVEZX30HNj5B+YIxLcFJOxmzFvcOHN2mrpCvzUUMJ6uvAtGqzhiTF7JxxR28iJJ4IiMEkcu77vGyiq1SDW1kouIMX4RtFKOMxWyfBCTU1NW1tba6urkFBQVboqrW1tba2Vi6Xz549WyKRvBKQtL36659TxT9ieo3F0FIaafIZpkdT+tyvqMKTmEZt0Q5UQQbh97ZkzTe4R8jwzfvfU7fSkLrFajulACo3pWT1ESI4lj966tSpnJycZcuWHT161IrNVSrV4cOH3d3dL1y44OLi8irCnT7vCFX0nRUIGRZrh9WqOmopQqzQdfd1l7ZjukEPph/f0Gd/Nh6Ehtxa//PHqKv+jc9JqOMZXfyD9Y+i9UyrUTM+NB6F1hfT//xm6NHU3W+hnRBFANLUn+cE4iGOD7VWyziXExZZMeptF9qDxOQOmExh7sfGEZ8+x2CzVfAj/ACYJrcfXgJ9Uib8JgaQIAPRDSXCW8H7MMul3PtS28EhQZyq8t984tBew7MQgnxnBzHrXdzOxaxFI1A37hbM9DrrBAzNK1QStxt3m8nZHGl76cpcSpU+6IUjfJr51d2A6fq5BhO6ioz+CHeaAbP0OV/SFddHIGQjTT6NuwTCEGqvpgoz6Zq7xs7UZqn6+vr6NBoNQoggCFtbWyAIpmaSJMnkdK1WrVaDYykUCplMNvEgIR4MZFSK5P0DFqZpLe8V5NK1GbhPpAB4oHS/BVhnHfXwJ+NXof8bNwojuOdb0g9PYTK7wUuFGwd18Gbc2d9gFmG4d4TuRJwRIcQtiCt37tzJzc0tLS1tamqiKMrGxsbf3z86OnrNmjUzZszgIwRzLl68ePXq1fLycrgMCQmJjY1dt26do6PjhHoSL7ASM+OsiM/ca49ZuPc8cwuC3sE4IJkI8YRv9BBCLI00RV6YPZz9wHdR3X2LCZBen56eDhpnk42vry+0zc3NFQa5efPm8ePHZ840igqA0MGDB2/fvg19b29vnU73yCB5eXmHDh3y8fGZ+DrJKMSPW3CJfJQJdq5j3YufhMyLieRkXrKysliENmzYkJSUxBLrrq4ucCzg6y0tLcC29+3bN3JJi0GUSuWuXbuCg4MB5sLCQuD0jx8/PnDgwIkTJ8yXUOMDyUweguD45BZdmcfQCsMlMXc1VDmCM5mkhZnmPxZEITRh729CIAOdPXsWOkuXLt25c+fQfYhaqampz549g4BWXFwMviKVGlmMl5fXsWPHPDw82MvExEQnJyfADCaDh8XHx08aSOaCwoD+2h7UWjnyXIAByRoyOoW+hQEcYfv27eAWixYt4o9GRUUBSP39/fxvjqSkpAwhxArAvGDBgqKiohs3brwmkMBIOS+KqP/BMRoQhFWrVnFLApqur6+vqanJz883VRUtXryYfzMsLAxAqq6unsycNIpb4OYpw9g2maICab+kpKSqqgpCHLCG7u5uoNemJkPeguDGvx8QEMCUNu3tkwnSxLgcZT7rIHXrlIKnt7c3LS0NWNxQTJs2bRrw7/nz50PZdPnyZQGCJZUKuhebt4D7TSJIdG0RFI8m/IMc87lZFeqsZcsX4QmNf08dhCCyAR8DIgd8DEoiKIyAEUCycXNjarLs7GxBkNiCV7AWhtbOzm4SQaIenMPdleSc1fzzG6TtFU74fIMaeKn/dafkvX24+ywe++inKq5Tf/0iRAhfj5SVlalUKoIg9uzZk5CQwBltbGwUXAUEvaOjg38K/vTpU2g5hGJcIOFOvjz9duuzPqFufiEQr8By+jsFNnEJEDDPKpU28w9c7sAboIQ/InLwfF0gPX/+HJwJ1B0bG8t3snv37plaCIURp8IdGBgoKCiATkRExISBREyfy4DBqy2ET11NiZMf7uiFXjZz7+sGkG6sHyESQUtfF0gKhQJatVpdUVGxcOHCkTaZkZEBbILt89PM+fPnlyxZApXs0J3MzMy6ujqZTMb3yHF4kmcoEZZAl2VbTREM52muRNR6Kv9r6xmlsz/UxcL1E5f0j1arWh42weo9PT1fvHixd+/ezZs3A04ACcRAKI8ePnwIFA4iG2QgIGy+vsOBBxJYZ2fnjh07tmzZEhkZCaNXrly5du0aDG3bti0kJGTichIplSQe1ve109UFVmUw3eAjl30KTIEuzbJCR7izn2RtBnPozp5EcI5rOVGXc2ql13CfaHy4DinQVG5nWxBnZ2fIRvv37wdFp6enj5y5fv36uLg4gAEml5eXsyDpdDrW/zZu3Hj69GmghcPqJMmtW7du2rRp1L/aMuKA23tIN1+iSrPQ099RdwOTMAZ6Rj+2gTJW4UZGJg9eyhTS5DP0vGT6SQ5qrUQ9zZim1+wmCJ6LufgTPvOIOR8MpUbcJZCMShn8uAGcxs6VCE8yiorhSfTzB1h/F0M1EYX7ROKORsmMmL8B9bRglIYFmIhYy3/2ypUrlUrlyC84xMTEnDx5EvwAiqSenh57e3sIYsuXLw8NDYXR3bt3t7W1ASlnJ4eHh6empsIcAAPcDugf1FXAOwIDA1esWAFeNSa1i//6MvVF/EqXCJIoIkgiSKKIIIkigiSCJIoIkijG8q8AAwAx9X3m5V73jwAAAABJRU5ErkJggg==" alt="" title="" width="140" height="40" layout="responsive"></amp-img>`

**Comment by taraskimdev** [comment]
Yeah! Does anybody can help with some custom plugin or at least let us know if there will be any solution for inserting AMP images into the text area

**Comment by natasak** [comment]
I am also interested in using amp-img instead of img - for a custom plugin.
