### ISSUE TITLE
TinyMCE Link plugin -  Displaying garbage item list when click inside URL input

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#4309]
I am using latest TinyMCE version 4.7.9 with link plugin. When open link model and click inside URL input, it is displaying garbage items (<top>, <bottom>) list like below screenshot. 

![editor screenshot](https://user-images.githubusercontent.com/2102705/38137592-296204aa-3443-11e8-912c-b72346e80378.png)

I have checked same with older TinyMCE versions and this garbage list is started displaying after TinyMCE version 4.4.3. The garbage list was not displaying till TinyMCE version 4.4.3.

**Comment by donShakespeare** [comment]
Is it garbage, or is it trying to be smart and sniff your current page for possible links: `#top` and `#bottom`?

**Comment by fyrkant** [comment]
If you don't want the top and bottom items you can disable them:
https://www.tinymce.com/docs/configure/url-handling/#anchor_bottom
https://www.tinymce.com/docs/configure/url-handling/#anchor_top

**Comment by laeeqwtb** [comment]
yes, it is solve to hide top and bottom items. Thanks!
