### ISSUE TITLE
Can't type spaces in a table cell

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4310]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

I can't type the "space" character into a table cell. The spaces just don't appear in the table cell when I press Space on the keyboard. Other characters can be typed as expected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Go to http://fiddle.tinymce.com/9ogaab.
2. Put the caret in the lower-right table cell.
3. In the contextual toolbar click "Insert column after" - the caret should automatically move to the new column.
4. Start typing letters and spaces.

**What is the expected behavior?**

All typed characters, **including spaces**, should appear in the table cell.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.7.9
Safari 11
Mac High Sierra

I could not reproduce it in Chrome nor Firefox.

**Comment by fyrkant** [comment]
Seems like this is a problem with contenteditable="true" tables in Safari and not in TinyMCE, see this: http://fiddle.tinymce.com/9ogaab/1

You can't expand the non-tinymce table with spaces either. We could fix this by taking over the space button inside of tables or something like that, I guess, but I'm not sure it is worth it? Why would you ever want to insert only spaces into a table cell?

**Comment by gkubisa** [comment]
> Why would you ever want to insert only spaces into a table cell?

Inserting spaces to separate words didn't work for me either.

**Comment by fyrkant** [comment]
Ah, yeah that is true, sorry. That isn't good... :/

**Comment by fyrkant** [comment]
This has been fixed in 4.7.11.
