### ISSUE TITLE
Violation errors in chrome js console with verbose logging

### ISSUE THREAD

**Issue by Sophist-UK** [tinymce/tinymce#4312]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

"Violation" errors shown in Chrome javascvript console log if verbose logging is set.

`tinymce.min.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
n @ tinymce.min.js:2
t.bind @ tinymce.min.js:2
(anonymous) @ tinymce.min.js:3
m @ tinymce.min.js:3
each @ tinymce.min.js:3
on @ tinymce.min.js:3
d @ tinymce.min.js:9
postRender @ tinymce.min.js:9
postRender @ tinymce.min.js:10
(anonymous) @ tinymce.min.js:8
postRender @ tinymce.min.js:14
(anonymous) @ tinymce.min.js:8
(anonymous) @ tinymce.min.js:8
n @ tinymce.min.js:3
each @ tinymce.min.js:8
exec @ tinymce.min.js:8
postRender @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:8
postRender @ tinymce.min.js:14
(anonymous) @ tinymce.min.js:8
(anonymous) @ tinymce.min.js:8
n @ tinymce.min.js:3
each @ tinymce.min.js:8
exec @ tinymce.min.js:8
postRender @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:8
renderBefore @ tinymce.min.js:9
p @ theme.min.js:1
s @ theme.min.js:1
renderUI @ theme.min.js:1
init @ tinymce.min.js:11
(anonymous) @ tinymce.min.js:11
(anonymous) @ tinymce.min.js:4
n @ tinymce.min.js:3
v @ tinymce.min.js:4
(anonymous) @ tinymce.min.js:4
o @ tinymce.min.js:4`

`tinymce.min.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
n @ tinymce.min.js:2
t.bind @ tinymce.min.js:2
(anonymous) @ tinymce.min.js:3
m @ tinymce.min.js:3
each @ tinymce.min.js:3
on @ tinymce.min.js:3
(anonymous) @ tinymce.min.js:9
postRender @ tinymce.min.js:14
(anonymous) @ tinymce.min.js:8
(anonymous) @ tinymce.min.js:8
n @ tinymce.min.js:3
each @ tinymce.min.js:8
exec @ tinymce.min.js:8
postRender @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:8
(anonymous) @ tinymce.min.js:8
n @ tinymce.min.js:3
each @ tinymce.min.js:8
exec @ tinymce.min.js:8
postRender @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:8
renderBefore @ tinymce.min.js:9
p @ theme.min.js:1
s @ theme.min.js:1
renderUI @ theme.min.js:1
init @ tinymce.min.js:11
(anonymous) @ tinymce.min.js:11
(anonymous) @ tinymce.min.js:4
n @ tinymce.min.js:3
v @ tinymce.min.js:4
(anonymous) @ tinymce.min.js:4
o @ tinymce.min.js:4`

`tinymce.min.js:11 [Violation] Avoid using document.write().
initContentBody @ tinymce.min.js:11
init @ tinymce.min.js:11
(anonymous) @ tinymce.min.js:11
(anonymous) @ tinymce.min.js:4
n @ tinymce.min.js:3
v @ tinymce.min.js:4
(anonymous) @ tinymce.min.js:4
o @ tinymce.min.js:4`

`tinymce.min.js:4 [Violation] 'load' handler took 187ms`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Open Chrome developer tools, select Console, set filter level to verbose, load a page which includes TinyMCE.

**What is the expected behavior?**

No errors.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Joomla 3.8.4 - TinyMCE 4.5.8

**Comment by fyrkant** [comment]
I wouldn't call these errors, maybe more like recommendations from chrome to use modern stuff like passive event listeners? Passive event listeners are [not supported by IE11](https://caniuse.com/#feat=passive-event-listener), so it is nothing we will start using in the near future in TinyMCE. Closing this issue as it isn't really an issue.

**Comment by sgtcoder** [comment]
I was actually having scroll blocking until `TinyMCE` loaded fully. When I add `async` to the `tinymce` script, it fixes the issue of the scrollblocking that Chrome is throwing warnings about.

**Comment by philipstratford** [comment]
I'm not sure I'd agree this "isn't really an issue". As [the article linked to in the console warning](https://developers.google.com/web/updates/2016/08/removing-document-write) points out, using `document.write()` can have a significant impact on performance over slow connections. The recommended solution is to use async function calls, which aren't supported in IE11, but with IE11 being [officially retired in May 2022](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/) maybe it's time to revisit this?
