### ISSUE TITLE
How to add watermark

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#4314]
Hi,

We are using the latest tinymce version in our project, I have tried to add watermark to it by using "placeholder" property, but it is not showing. Can anyone let me know how to show watermark in tinymce editor.

**Comment by fyrkant** [comment]
We don't have this functionality right now, but it might be added in the future. There is already [an issue about this](https://github.com/tinymce/tinymce/issues/2623) so I'm closing this one.
