### ISSUE TITLE
Version 4.7.10 - Editor bug - A selection in tables disappears in the moment that the mouse cursor is over a cell border

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4316]
Tested in Firefox. Select the first select and keep going down with the mouse to the bottom-right of the table, every time you pass over a cell border, the selection disappears and you have to keep going with the selection (always keeping the mouse button down) in order to make it happen. If you do it at a normal speed, you will see a blinking. This didn't happened in the previous version of TinyMCE.

http://fiddle.tinymce.com/Vogaab

**Comment by fyrkant** [comment]
From my testing this doesn't seem to be a new issue with 4.7.10 but seems to have been around for a few versions, right?

**Comment by lrusso** [comment]
So sorry for this, my bad.
