### ISSUE TITLE
Version 4.7.10 - Editor bug - Several bugs remains in table and regression

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4318]
In the changelog says 'Fixed a bug with the Table Plugin where the caret would sometimes be lost when keyboard navigating up through a table', but testing this in Firefox, the following three bugs remains:

https://github.com/tinymce/tinymce/issues/4271

Fiddle with 4.7.10: http://fiddle.tinymce.com/dpgaab

And now, when you scroll down and then to the top using the keys, a new line is created over top of the first table. Sometimes after reloading the fiddle, I can't scroll down using the keys. I'm using the latest version of Firefox.

**Comment by spocke** [comment]
The new line above and below is by design. It was hard to see that there is a caret before/after a table so now we insert a new line. The focus issue might be something with the iframe needs a separate report if it's an issue.
