### ISSUE TITLE
Unable to type Japanese character in table in Chrome 65

### ISSUE THREAD

**Issue by jirkahronik** [tinymce/tinymce#4319]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When typing a character using IME (any input method that requires multiple key strokes for a single character, e.g. you want `ó` but end up with two characters `'o`.

**Steps to reproduce:**
* Use Chrome 65
* Any version of TinyMCE
* Create a table with 2 cells in a row
* Enter any text in the first cell
* Type k+i using Japanese IME, "k" + "i" = "き" but instead the cell contains "kい". The first character is inserted into the editor directly.

Fiddle: http://fiddle.tinymce.com/epgaab

Notes:
* I am unable to reproduce this outside of the table
* Only happens when the preceding cell is not empty
* Only happens with the first character in the cell, the following ones are fine

**What is the expected behavior?**
A single character is inserted in the cell

**Comment by fyrkant** [comment]
This seems to be a problem with chrome and contenteditable="true" tables, not TinyMCE. You can see [here](http://fiddle.tinymce.com/epgaab/1) that the issue appears in the contenteditable="true" table also.

**Comment by spocke** [comment]
Attaching the chrome ticket:
https://bugs.chromium.org/p/chromium/issues/detail?id=829224
