### ISSUE TITLE
(No suggestions) in the Spellchecker Plugin

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4320]
I modified the SpellChecker plugin in order to show in the suggestionsMenu a '(No suggestions)' disabled item over the separator instead of only showing a separator when no suggestions. Hope it may help.

https://github.com/tinymce/tinymce-dist/pull/21

![35814614-443502a2-0a75-11e8-8d8b-0f47051b2ca8](https://user-images.githubusercontent.com/11498901/38286627-be593a9a-379c-11e8-99d0-f99130cc451b.png)

**Comment by fyrkant** [comment]
You have to open a PR on the this repository if you want to make a contribution.
