### ISSUE TITLE
Remove and add new editor in partial view in Edge error

### ISSUE THREAD

**Issue by subba45** [tinymce/tinymce#4321]
When I remove an tinymce editor after saving and adding it again it is not working.
I get following error in the console:
SCRIPT5007: Object expected
tinymce.min.js (4.4.1)

I have tinyme 4.4.1 and I only get the error in Windows 10 Edge,
other browsers worked as expected..

**Comment by fyrkant** [comment]
Can you create a [fiddle](http://fiddle.tinymce.com/) reproducing the issue?

**Comment by wonderbugtiny** [comment]
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, we would be happy to reopen this issue.
