### ISSUE TITLE
grunt build described in README results in typescript errors

### ISSUE THREAD

**Issue by harveynr** [tinymce/tinymce#4323]
When trying to follow the instructions in the README, I get to the `grunt` step with no issues, but when running grunt, I get the message:

> Warning: Command failed: node ./node_modules/typescript/bin/tsc
>  Use --force to continue.

I can't tell if these are dependency issues within tinymce, or an issue with tsc, though other installations of tsc on my computer are working without issue.

Here is my full output:

[root@localhost homepage]# node -v
v8.11.1
[root@localhost homepage]# git clone https://github.com/tinymce/tinymce.git
Cloning into 'tinymce'...
remote: Counting objects: 109226, done.
remote: Compressing objects: 100% (282/282), done.
remote: Total 109226 (delta 188), reused 297 (delta 129), pack-reused 108773
Receiving objects: 100% (109226/109226), 37.57 MiB | 12.17 MiB/s, done.
Resolving deltas: 100% (65306/65306), done.

[root@localhost homepage]# cd tinymce/

[root@localhost tinymce]# npm i -g grunt-cli

/usr/bin/grunt -> /usr/lib/node_modules/grunt-cli/bin/grunt
+ grunt-cli@1.2.0
updated 1 package in 0.626s

[root@localhost tinymce]# ls
changelog.txt  package.json  tools                 tsconfig.theme.json
Gruntfile.js   readme.md     tsconfig.json         tslint.json
LICENSE.TXT    src           tsconfig.plugin.json

[root@localhost tinymce]# npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 5.634s
[root@localhost tinymce]# grunt
Running "validateVersion" task

Running "shell:tsc" (shell) task
src/core/main/ts/EditorSettings.ts(166,7): error TS2322: Type 'string[]' is not assignable to type 'string'.
src/core/main/ts/caret/CaretContainerRemove.ts(69,35): error TS2345: Argument of type 'NodeListOf<Node & ChildNode>' is not assignable to parameter of type 'Node[]'.
  Property 'push' is missing in type 'NodeListOf<Node & ChildNode>'.
src/core/main/ts/commands/IndentOutdent.ts(37,71): error TS2345: Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.
  Property 'accessKey' is missing in type 'Element'.
src/core/main/ts/keyboard/MatchKeys.ts(62,1): error TS4082: Default export of the module has or is using private name 'Option'.
src/core/test/ts/atomic/keyboard/MatchKeysTest.ts(58,70): error TS2554: Expected 1 arguments, but got 0.
src/ui/main/ts/FilePicker.ts(149,9): error TS2365: Operator '===' cannot be applied to types 'Option<number>' and 'number'.
Warning: Command failed: node ./node_modules/typescript/bin/tsc
 Use --force to continue.

Aborted due to warnings.

**Comment by fyrkant** [comment]
This should be working now, pull down the latest and try again!

**Comment by harveynr** [comment]
Yes, grunt completed successfully that time, thanks!

**Comment by trusktr** [comment]
Regarding the all-too-common "has or is using private name" error, I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
