### ISSUE TITLE
Link plugin prefix with http:// by default

### ISSUE THREAD

**Issue by Narrenschyff** [tinymce/tinymce#4335]
Using TinyMCE version: 4.7.1

Currently we have the option to prefix any URL assuming they are all external with http://. I have this setting configured:

"link_assume_external_targets: true"

However, I was wondering if the dialog for prefixing could be skipped and prefixing could be done in the background by default. Is it possible to plug in such behavior without modifying the plugin myself or is that something that can be supported e.g having a separate setting?

Thanks,
Yulia

**Comment by JeroenvdV** [comment]
@glennr This would be great, are you planning to submit the PR yourself and if so, do you have a branch of this already?

**Comment by glennr** [comment]
Hi! No immediate plans to make a PR - but I thought at least documenting
the desired API would be a start.

**Comment by rafaeelaudibert** [comment]
Definitely would like to have this implemented

**Comment by TheSpyder** [comment]
This is likely to happen during the 5.x development cycle. I can't promise when, but here's what I'm thinking:

`link_assume_external_targets: false` -> no prompt, `https://` prefix for `www.` links only
`link_assume_external_targets: true` -> current behaviour (retain prompt, maybe?)
`link_assume_external_targets: 'http'` -> no prompt, `http://` prefix
`link_assume_external_targets: 'https'` -> no prompt, `https://` prefix

I'm not entirely sure whether we will change the default behaviour, but I'd like to.
