### ISSUE TITLE
If webcomponents polyfill used, no implicit ClassList.toString casting happens

### ISSUE THREAD

**Issue by 4esnog** [tinymce/tinymce#4339]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
When clicking on "Insert link" button, dialog is not opened and the next error is printed in console:
> TypeError: b.split is not a function

**What is the expected behavior?**
"Insert link" dialog should open.

Issue affects web apps using `webcomponents-sd-se.js` polyfill, opened in browsers without ShadowDOM and Custom Elements v1 implemented.
In my case it is FireFox 60.

This polyfill patches Element.className setter with custom setAttribute implementation, which doesn't perform toString() cast before trying to split classes string. This is the code snippet from polyfill which fails:
```
// b is ClassList, not String
b = b ? b.split(/\s/) : [];
```

**Comment by spocke** [comment]
Closing this ticket since the PR related to it was closed.
