### ISSUE TITLE
core.js:1350 ERROR Error: Uncaught (in promise): TypeError: editors.execCommand is not a function

### ISSUE THREAD

**Issue by vusan** [tinymce/tinymce#4341]
**Hi**

I am using `editors.execCommand` for default font. But it is showing the above error. What may be cause of that error?
Tinymce version 4.5.0

**Comment by spocke** [comment]
Upgrade to the latest version and provide a way for us to reproduce it though fiddle.tinymce.com and we can look into it. Closing this ticket for now. Can re open if the requested details is provided.
