### ISSUE TITLE
'null' is not an object - safari browser issue

### ISSUE THREAD

**Issue by mtilokani** [tinymce/tinymce#4343]
`
[Vue warn]: Error in beforeDestroy hook: "TypeError: 'null' is not an object (evaluating 'rng.startContainer')"
`

I am facing this above error in safari browser. This error occurs when I leave that page through vue router. This is tinymce plugin issue.

After this error text editor looks like following screen shot without styling.

![tinymce](https://user-images.githubusercontent.com/20898692/38791419-332645e4-4165-11e8-951b-daa5fca29c90.png)

Please help me to solve this.

**Comment by Afraithe** [comment]
This should actually be in the vue wrapper project, I can't move tickets, if it still is an issue, please open it in the tinymce-vue project.
