### ISSUE TITLE
Keep running in IE10- or provide a flag to bypass restriction

### ISSUE THREAD

**Issue by sntran** [tinymce/tinymce#4347]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When using TinyMCE v4.6.0+ in IE10, it does not load and throws an Error in Console: "TinyMCE does not support the browser you are using".

**What is the expected behavior?**

It should throws the same Error in Console, but will attempt to load as normal. Understandingly, the TinyMCE team does not want to support IE10 and below. However, by throwing the Error, nobody can put the responsibility on TinyMCE, but rather, whoever decides to use it on IE10- will need to fill and fix issues in that browser themselves.

Alternatively, provide an option for the developer to bypass that Error.

In my company, we need to support at least IE9 and IE10. I have tested (at least up to version 4.7.4) that TinyMCE can run in IE9 (with `matchMedia` polyfill) and IE10 after removing that condition in TinyMCE source. We would rather handle the polyfill part than not being able to use TinyMCE at all.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE v4.6.0+ in IE10.

**Comment by spocke** [comment]
We still support the 4.5.0 branch with critical fixes. You can use that if you want legacy support.

**Comment by sntran** [comment]
My apology. I probably didn't explain myself clear enough. I don't need TinyMCE's support for legacy browsers. I just want an option that can be passed to `tinymce.init` that can let me run newer version of TinyMCE on those browsers. 

If TinyMCE does not work in those browsers, it's fine. But I want to handle the browser incompatibility issues myself. At the moment, TinyMCE won't run at all.

In another word, I want an option to bypass the following block:

https://github.com/tinymce/tinymce/blob/cf05d84ca4d62ff730d7c34b784f0d35419e9b03/src/core/main/ts/api/EditorManager.ts#L366-L372
