### ISSUE TITLE
Localization - Is it possible to restrict editor redraw on language change?

### ISSUE THREAD

**Issue by Shanthi-Kumar** [tinymce/tinymce#4352]
We're supporting localization for Japanese and English in our app and with the help of angular we're able to change the language of the document but to do the same I'd to reload the tinymce editor to change the lang. In doing so I'm losing the content edited, font modification and facing few performance issues on loading entire content.

Is there any way to just change the lang instead loading entire editor. Please help

**Comment by spocke** [comment]
There is currently no way to refresh the ui once it's rendered. Usually a setting of language is a global thing you configure in your app so there have not been a lot of demand for such a feature.
