### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by webdevnerdstuff** [tinymce/tinymce#4354]
On the TinyMCE page, it would be helpful if a plugin was a Premium plugin, that it stated this on the documentation page. I just spent a bunch of time searching for why powerpaste wasn't working/js files not included, as well as looking through the repo branches/tags. This could have been easily avoided with a single line of copy saying that it's a premium plugin with a link for more information if they want to purchase a premium version. Thank you.

Ex. Powerpast is a premium plugin. Click here for more information.

**Comment by Afraithe** [comment]
Thanks for the feedback, we continue to update the docs on a regular basis, we will try and work in some clearer message around this.
