### ISSUE TITLE
table plugin add unnecessary height and width

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#4357]
With create a table its add width to every TD

```
<tr>
<td style="width: 20%;">&nbsp;</td>
<td style="width: 20%;">&nbsp;</td>
</tr>
<tr>
<td style="width: 20%;">&nbsp;</td>
<td style="width: 20%;">&nbsp;</td>
</tr>
```
But to set the width in every TD for every TR is not necessary and have no benefits. A cell can't get different widths in a column. So I would like only in the first TR get the width in TD. When delete the first row, the second row (new first) must inherit the width from deleted one.

The same happen with height in table. After resize a single row, its add it for all TR and TD a height.

```
<tr style="height: 25px;">
<td style="width: 20%; height: 25px;">&nbsp;</td>
<td style="width: 20%; height: 25px;">&nbsp;</td>
</tr>
<tr style="height: 18px;">
<td style="width: 20%; height: 18px;">&nbsp;</td>
<td style="width: 20%; height: 18px;">&nbsp;</td>
</tr>
```

Why tinymce add height to every TR and TD? Why not only TR? Again, a row can't have different heights in a single row. And why its add height to all TR/TD and not only the single resized one? This _feature_ make extensive tables very big in size. 

Is here maybe a function that make the html better?

**Comment by jordanade** [comment]
And why can't we, even with `table_resize_bars` set to false, prevent table resizing in the first place! I want a nice clean table with NO inline styles!

**Comment by Daijobou** [comment]
This issue still exists in current tinymce 5. :(

**Comment by odraencoded** [comment]
You can prevent inserting widths when the table is created with:

    table_default_attributes: {},
    table_default_styles: {}

But TinyMCE will still add inline widths if you click the insert column before/after buttons. Inserting a row doesn't add widths. I guess you'll need to manually edit the HTML to add rows or to remove the widths.

The table plugin could use an option to disable adding inline widths/heights altogether. I guess it makes sense for some users, but personally I find inline attributes unmanageable.

**Comment by lostkeys** [comment]
Use the [invalid_styles option](https://www.tiny.cloud/docs/configure/content-filtering/#invalid_styles) to remove width and height from table cells upon serialization (and all other unwanted inline styles too). It's also recommended to [disable resizing](https://www.tiny.cloud/docs/plugins/table/#table_resize_bars) of the table in the UI because it now doesn't save changes.

[Here is a quick demo](http://fiddle.tinymce.com/Mmhaab/1)

**Comment by lnewson** [comment]
Also worth noting in TinyMCE 5.4 we're adding better support for tables that have no set widths.
