### ISSUE TITLE
`.mce-offscreen-selection` element is not removed when TinyMCE is removed

### ISSUE THREAD

**Issue by josh18** [tinymce/tinymce#4363]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The `.mce-offscreen-selection` is not removed when TinyMCE is removed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Mqgaab/1
1. Click the noneditable element
2. Hover over the _Remove TinyMCE_ button

noneditable element is duplicated at the bottom of the page. Note that I think it only happens when you are using `inline: true`

**What is the expected behavior?**
noneditable element is removed when TinyMCE is removed

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All browsers / OS? Testing on TinyMCE v4.7.11 but it has been happening for awhile I think.

**Example**
![tinymce-noneditable](https://user-images.githubusercontent.com/5900962/39335617-dcd5a738-4a07-11e8-95af-9421328eb7c5.gif)

**Comment by SimonFc** [comment]
This bug has now been fixed in the latest version. (4.8.0)
