### ISSUE TITLE
Override the built-in formats for a specific selector only

### ISSUE THREAD

**Issue by mikey213** [tinymce/tinymce#4369]
In TinyMCE 4, is there a way to override a [built-in format](https://www.tinymce.com/docs/configure/content-formatting/#builtinformats) for a particular selector _**without**_ affecting the other selectors with the same format?

To be more specific, I would like to change the behavior of the alignment buttons for the `img` tag. Particularly, I would like to simply add a class (e.g. `.left`, `.center`, or `.right`) on the selected image depending on which alignment button is clicked. For any other tag, I would like to keep the default behavior as-is (e.g. `p` tag would continue using `text-align` style). 

When I tried:
```
tinyMCE.init({
    ...
    formats : {
        alignleft : { selector : 'img', classes : 'left' },
        aligncenter : { selector : 'img', classes : 'center' },
        alignright : { selector : 'img', classes : 'right' }
    }
});

```

It does the necessary alignment behavior for the `img` tag -- but at the same time removes the default behavior of the other tags e.g. `p` tag can no longer change alignment.

Is it possible to achieve this desired behavior? Thanks.

**Comment by spocke** [comment]
You can have an array of items with selectors. This way you can apply different formats for different selectors. I guess we should add that to the docs.
