### ISSUE TITLE
HTML entity encoding affecting attribute values

### ISSUE THREAD

**Issue by jinglesthula** [tinymce/tinymce#4370]
There appears to be a bug with the formatting the editor applies to content.

When I include a link in some text in the editor that includes a querystring, then view the source code, I can see that it's converted any & characters in the href to &amp;, which breaks the links.

`<a href="/foo?one=1&two=2">A link</a>`

becomes

`<a href="/foo?one=1&amp;two=2">A link</a>`

and if I change it back to just `&` in the source, click Ok on the view source dialog, then immediately view source again, it's already worked its charms and encoded the `&` once again.

What I would expect is that any tag attribute value should be ignored by any formatting. Encoding `&` characters in text nodes makes sense.  Applying the same encoding within tags themselves is unexpected and breaks things (see comments on this related SO question I posted: https://stackoverflow.com/questions/50069810/tinymce-converting-ampersand-in-querystring-to-html-entity).

This happens as far back as 4.0.12 and can be easily reproduced on the editor instance shown near the top of [https://www.tinymce.com/](https://www.tinymce.com/).  Just View > Source code and add a traditional querystring with more than one key-value pair to any of the links, click Ok, then view source again to see the magic.

While I describe the easiest way to see the problem, I believe our users also reported the same behavior when pasting HTML in to the WYSIWYG UI, so the same formatting is applied in that case.

**Comment by jinglesthula** [comment]
Based on further comments and an answer on the SO question mentioned above, I'm closing this issue.

**Comment by clarumedia** [comment]
> As a side note, I do not know whether TinyMCE tries to apply URL encoding to `href` or `src` attribute values if it detects characters needing it. Overall, I would expect that burden is on the user to provide well-formed URLs or other proper attribute values, and that what's between the quotes in any attribute on any tag is considered a black box the editor doesn't ever touch.
> 
> Does this sound right? I may be overlooking some intended behavior of the editor that does intentionally modify attribute values.

In the case of the use of PHP short echo tags the mangling of the URL in an href attribute breaks the source HTML/PHP and, if PHP short open tags are protected by TinyMCE, the mce:protected comment is also mangled.

After a long process of stepping through the TinyMCE source, it looks like the href attribute on an element parsed using [DOMParser.parseFromString](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString) is escaped. Hence the issue. BTW: the result from getAttribute is not escaped......

Before anybody starts giving a lecture on how PHP short open tags are evil, this is being used in a very special and specific context with due care for security.
