### ISSUE TITLE
Did you change the way to specify multiple classes in the link plugin?

### ISSUE THREAD

**Issue by chimame** [tinymce/tinymce#4371]
### Question contents
Was it changed to how to specify multiple classes in link_class_list used by the link plugin?

### Problems and suggestions
`value` of` link_class_list` corresponds to class, but if you specify multiple classes, you should specify it as a space delimiter,
Currently it does not work like that, style does not fit in the link insertion dialog.

```javascript
tinymce.init({
    plugins: "link",
    link_class_list: [
        {title: 'nothing', value: ''},
        {title: 'dog', value: 'btn singleBtn'}, //Do not work
        {title: 'cat', value: 'cvBtn'}
    ]
});
```

![image](https://user-images.githubusercontent.com/7520815/39505615-7f601f92-4e0e-11e8-83b2-0c7eded469bb.png)

### Countermeasure
The problematic code is probably [this](https://github.com/tinymce/tinymce/blob/master/src/plugins/link/main/ts/ui/Dialog.ts#L261) .
It is supposed to be passed unconditionally in a single array, but should this be passed on splits in space?

```javascript
return editor.formatter.getCssText({ inline: 'a', classes: item.value.split(' ') });
```

![image](https://user-images.githubusercontent.com/7520815/39505627-94e2c194-4e0e-11e8-873f-61a4647fa885.png)

### versions
I changed TinyMCE version as follows.
4.5.7 to 4.6.2

**Comment by fyrkant** [comment]
Are you having this issue in the latest, 4.7.12 version, of TinyMCE as well?

**Comment by chimame** [comment]
@fyrkant Thank you for your reply.

If it is the latest 4.7.12 it was not a problem.
