### ISSUE TITLE
Merge Cell failing on IE11

### ISSUE THREAD

**Issue by JoeOwner** [tinymce/tinymce#4386]
***bug***

Currently: 
- Using IE11, if I add a table with any content above the table, I am unable to merge cells in the table. 
- If a table is the first thing on the page, the issue resolves with all tables and I can merge cells correctly 

This behavior can be repeated at tinymce.com on the provided WYSIWYG editor. 
**Steps to reproduce:**

1. navigate to www.tinymce.com
2. under the tinyMCE logo in the WYSIWYG editor add a table
3. select the cells you would like to merge
4. got to menu option: Table -> Cell -> Merge Cells
**Expected result:**
cells merge
**Actual result:**
cells remain individual cells

**Fix(?)**
1. add another table above the TinyMCE Logo
2. select the cells you would like to merge
3. got to menu option: Table -> Cell -> Merge Cells
Result:
cells merge

1. return to the first table you created below the logo
2. select the cells you would like to merge
3. got to menu option: Table -> Cell -> Merge Cells
**Result:**
cells merge

OS: Windows 10 
Browser: IE 11.1029 
tinyMCE: 4.7.12

**Comment by TheSpyder** [comment]
Internal records show it was fixed, but not linked to this issue. Whether we did or not, IE11 is not supported by the current editor versions.
