### ISSUE TITLE
Modern theme runs immediately

### ISSUE THREAD

**Issue by Luke-SF** [tinymce/tinymce#4387]
**Do you want to request a *feature* or report a *bug*?**
Bug in recent versions of TinyMCE.

**What is the current behavior?**

The modern theme theme.js in latest TinyMCE has immediately executing Javascript `var modern = (function(){ ... }())`, while previous versions had `tinymce.ThemeManager.add('nameoftheme', function... )` where the js theme code would not immediately run.

**What is the expected behavior?**

Ideally this should use the ThemeManager.add instead of immediately running the theme code. If I include some other js themes in the page and set it to use that theme, it conflicts, and the only way to resolve it to make sure that modern js is not included in the page at all.

**Comment by fyrkant** [comment]
The theme is still loaded the same, using the ThemeManager.add method, so there shouldn't be any change in how it works. Closing this, can open it up again if you can provide a reproduction of two themes conflicting.
