### ISSUE TITLE
Can not use Table with Edge Browser (window insider)

### ISSUE THREAD

**Issue by hungcrush** [tinymce/tinymce#4388]
Hi there, 
(Sorry, my English skill is not good)

I'm using Window Preview version (Insider) And Edge version 42.17666.1000.0
Now I can't use Table on my Browser (Edge) 
I dont know next release windows version, it will be fixed or not!

![screenshot_31](https://user-images.githubusercontent.com/8098916/39910381-4601cdee-5521-11e8-9c87-8038ed30088b.png)

**Comment by spocke** [comment]
We know of an issue where it's not possible to select tables. What is happening on your machine? Can you create tables is it other operations after that that fail?

**Comment by mpsn** [comment]
Edge 42.17134.1.0: When you try to enter a table by clicking on a cell, the cursor is placed at the bottom of the editing area. Inserting a new table works but again, you cannot enter it.

**Comment by hungcrush** [comment]
@spocke It's fixed when I updated 4.7.13

I think "FIXED a bug where Edge 17 wouldn't be able to select images or tables." => FIX it.

**Comment by Afraithe** [comment]
Fixed in latest.
