### ISSUE TITLE
Classic demo is not working

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4389]
https://www.tinymce.com/docs/demo/classic/

There's js error in theme.min.js.

**Comment by fyrkant** [comment]
It seems to work for me, is it in a particular browser where it's broken?

**Comment by alecpl** [comment]
Indeed works in Chrome, but not in Firefox 59.0.2.

TypeError: n is undefined in theme.min.js:1:101983

**Comment by spocke** [comment]
We have a fix in the pipeline for this already. So it will be resolved as soon as we update the cloud.

**Comment by patriciavandermeer** [comment]
Is there a timeline for the update for this?  It's causing some issues for our users.  Will this fix be included in the enterprise version right away?  It's often behind the regular version.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
