### ISSUE TITLE
Suggestion: codebase overview for the new contributors

### ISSUE THREAD

**Issue by alexpyzhianov** [tinymce/tinymce#4390]
It's hard to start contributing to the project. The only way to get to know the codebase is discovering everything by yourself. It takes a lot of time for a casual contributor. I've already spent several hours figuring out how to improve the behavior in #4383 

I think we should create an overview guide for the new developers outlining project structure, different parts of the system, how they fit together and other relevant information. This will greatly help the project by bringing more people in and making their lives easier.

**Comment by Afraithe** [comment]
You are absolutely correct, it would be great to have some overview guide for developers wanting to contribute to the project. TinyMCE has undergone a great deal of changes under the hood the last year or so, it would have been difficult to keep that type of info up to date, but now that it is getting in a more stable state it might be a good idea to start working on that in more detail.

Would probably make it a separate github project that ppl can contribute to. Any ideas on how it could be constructed, examples etc, would be great.

**Comment by alexpyzhianov** [comment]
I think we can learn from [Automattic/wp-calypso](https://github.com/Automattic/wp-calypso), it's so well-documented it almost makes you sick.

1. The project has extensive [documentation](https://github.com/Automattic/wp-calypso/tree/master/docs) for developers covering topics like git workflow and PR review process
2. And what I like the most, READMEs for almost every individual component located in this component's folder. Like [this one](https://github.com/Automattic/wp-calypso/tree/master/client/boot)

**Comment by alexpyzhianov** [comment]
1. A good start would be to add READMEs into each folder inside `core/ts`
![image](https://user-images.githubusercontent.com/7609100/40036168-72afd62a-580e-11e8-92fd-e9bad0a47081.png)
2. Then it would be easier to write a generic article outlining philosophy and architecture of the app
3. It would also be good to have a dictionary with common terms and abstractions like *formatter*, *inline boundary*, *zwsp*
