### ISSUE TITLE
media_url_resolver not reverting back to previous node

### ISSUE THREAD

**Issue by dcasarez14** [tinymce/tinymce#4391]
Bug

TinyMCE editor stays on current node after media embed (e.g. stays on div with class references) and adding more content / pressing enter to add text. Should revert back to `<p>` after embed like normal media embed.

```
media_url_resolver: function(data, resolve) {
      var embedHtml = '<div class="embed-responsive embed-responsive-16by9"><iframe src="' + data.url + '"></iframe></div>';
      resolve({
        html: embedHtml
      });
}
```

**Comment by fyrkant** [comment]
Maybe you can set `contenteditable="false"` on the div to prevent adding content into it?

**Comment by dcasarez14** [comment]
Thanks for the suggestion but I am still having the same issue. The div tag keeps getting repeated on the DOM if I press enter for a new line. I solved the issue by not using the media_url_resolver and instead wrapping the iframe with the div tag in jQuery as a temp fix.

 $('iframe').wrap('...');
