### ISSUE TITLE
Word count incorrect when pasting text into a table

### ISSUE THREAD

**Issue by JoeOwner** [tinymce/tinymce#4392]
***bug***
Currently:

**Using IE11 with Wordcount plugin**

Paste text into a table cell WITHOUT white space after the last character causes the word count to ignore the first word in the next cell.

adding a space to the end of the pasted content triggers the word count to treat the last word of the first cell and the first word of the next cell as 2 separate words. (fixes the issue)

This behavior can be repeated at tinymce.com on the provided WYSIWYG editor.
**Steps to reproduce:**

1. navigate to www.tinymce.com
2. add a table to the WYSIWYG editor
3. copy text, being careful to not copy any trailing whitespace
4. pages text into a cell in your newly created table
5. put focus of the next cell in the row and paste more text

**Expected result:**
Word count correctly reflects the number of words in the table
**Actual result:**
Word count is off by one (unless you repeat the step in the next cell in the row. Then your count is off by 2)
**Note:**
The word count is not wrong if the "next cell" is on a different row.

**Fix:**
Place white space at the end of the pasted text. 

**Demo:**
http://fiddle.tinymce.com/jsgaab
This problem seems to be a bit worse now that I've creating a demo. It seems that white space entered into the table markup to try and prevent the bug, gets stripped out. If you put the space at the end of the text the word count updates.

OS: Windows 10
Browser: IE 11.1029
tinyMCE: 4.7.12

**Comment by fyrkant** [comment]
This was fixed in 4.8.3.
