### ISSUE TITLE
mceInsertRawHTML is broken since 4.7.10

### ISSUE THREAD

**Issue by mwilliamson** [tinymce/tinymce#4401]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`editor.execCommand('mceInsertRawHTML', false, text);` does nothing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/3sgaab

**What is the expected behavior?**

`editor.execCommand('mceInsertRawHTML', false, html);` inserts the specified HTML.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

This seems to be broken since 4.7.10. I've tried it in Firefox, and had reports of the issue in Chrome.

I think this change is the issue: https://github.com/tinymce/tinymce/commit/94c6a98fd31e4279ec9f7a4bdc34184c4fa02504#diff-ad701515834368d8523e5034df87394eR451

Specifically, `content` is assigned before `setSelection` is called, whereas it seems to me that `content`  should be assigned after `setSelection`.

**Comment by epiphanatic** [comment]
We had the same issue. Any updates on this?

**Comment by jekuer** [comment]
Any updates on this?
Commit is still not accepted

**Comment by TheSpyder** [comment]
Should be fixed with #4625
