### ISSUE TITLE
Tinymce seems not to be working on ipv6 hosts

### ISSUE THREAD

**Issue by tkanafa** [tinymce/tinymce#4409]
**Bug report**
**What is the current behavior?**
Tinymce set up on IPv6 address does not work eg. **::1** (my localhost).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. mkdir tinymcetest
2. cd tinymcetest
3. npm install tinymce
4. cd node_modules/tinymce/
5. create file test.html with content:
[test.txt](https://github.com/tinymce/tinymce/files/2034993/test.txt)

6. npm install http-server -g
7. http-server -p 9999 -a ::1
8. in browser go to address (which should be your localhost):
http://[::1]:9999/test.html

observe that tinymce is not working.

Outcome:
script with invalid url is inserted into the head of the page
<script id="mce_0" type="text/javascript" src="http://[:1]:9999/themes/modern/theme.js"></script>
which is not proper address (missing one colon) instead of 
<script id="mce_0" type="text/javascript" src="http://[::1]:9999/themes/modern/theme.js"></script> 

Investigation led somewhere near:
`var URI = function (url, settings) {
    var self = this;
    var baseUri, baseUrl;
    url = trim$4(url);
    settings = self.settings = settings || {};
    baseUri = settings.base_uri;
    if (/^([\w\-]+):([^\/]{2})/i.test(url) || /^\s*#/.test(url)) {
      self.source = url;
      return;
    }
    var isProtocolRelative = url.indexOf('//') === 0;
    if (url.indexOf('/') === 0 && !isProtocolRelative) {
      url = (baseUri ? baseUri.protocol || 'http' : 'http') + '://mce_host' + url;
    }
    if (!/^[\w\-]*:?\/\//.test(url)) {
      baseUrl = settings.base_uri ? settings.base_uri.path : new URI(document.location.href).directory;
      if (settings.base_uri.protocol == '') {
        url = '//mce_host' + self.toAbsPath(baseUrl, url);
      } else {
        url = /([^#?]*)([#?]?.*)/.exec(url);
        url = (baseUri && baseUri.protocol || 'http') + '://mce_host' + self.toAbsPath(baseUrl, url[1]) + url[2];
      }
    }
    url = url.replace(/@@/g, '(mce_at)');
    url = /^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@\/]*):?([^:@\/]*))?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(url);
    each$20(queryParts, function (v, i) {
      var part = url[i];
      if (part) {
        part = part.replace(/\(mce_at\)/g, '@@');
      }
      self[v] = part;
    });
    if (baseUri) {
      if (!self.protocol) {
        self.protocol = baseUri.protocol;
      }
      if (!self.userInfo) {
        self.userInfo = baseUri.userInfo;
      }
      if (!self.port && self.host === 'mce_host') {
        self.port = baseUri.port;
      }
      if (!self.host || self.host === 'mce_host') {
        self.host = baseUri.host;
      }
      self.source = '';
    }
    if (isProtocolRelative) {
      self.protocol = '';
    }
  };`
there is big regex that parses url and it seems to work incorrect for ipv6 address:
![image](https://user-images.githubusercontent.com/17376820/40481059-7bd8b930-5f50-11e8-9ecc-07d0869c68fa.png)

**What is the expected behavior?**
Tinymce properly works

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested with:
- macos sierra
-  tinymce 4.7.13
- chrome 66
- firefox 60

**Comment by tkanafa** [comment]
additional output of parsing function for some real long ipv6 address
![image](https://user-images.githubusercontent.com/17376820/40482043-a8632afa-5f53-11e8-80ac-c8250bd98c71.png)

**Comment by tkanafa** [comment]
I think as a workaround https://www.tinymce.com/docs/configure/url-handling/#convert_urls could be set to false to prevent tinymce from toying with urls.

**Comment by dev7355608** [comment]
This small change enables IPv6 support.

```diff
- var urlMatch = /^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@\/]*):?([^:@\/]*))?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(url);
+ var urlMatch = /^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@\/]*):?([^:@\/]*))?@)?(\[[^\]]*\]|[^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(url);
```

Before:
```javascript
new tinymce.util.URI("http://admin:supersecret@[3c62:5655:8695:0f39:b065:1654:2d23:9f34]:9999/bar/index.html#foo")

==>

{
  "source": "http://admin:supersecret@[3c62:5655:8695:0f39:b065:1654:2d23:9f34]:9999",
  "protocol": "http",
  "authority": "admin:supersecret@[3c62:5655",
  "userInfo": "admin:supersecret",
  "user": "admin",
  "password": "supersecret",
  "host": "[3c62",
  "port": "5655",
  "relative": ":8695:0f39:b065:1654:2d23:9f34]:9999",
  "path": ":8695:0f39:b065:1654:2d23:9f34]:9999",
  "file": ":8695:0f39:b065:1654:2d23:9f34]:9999"
}
```

After:
```javascript
new tinymce.util.URI("http://admin:supersecret@[3c62:5655:8695:0f39:b065:1654:2d23:9f34]:9999/bar/index.html#foo")

==>

{
  "source": "http://admin:supersecret@[3c62:5655:8695:0f39:b065:1654:2d23:9f34]:9999/bar/index.html#foo",
  "protocol": "http",
  "authority": "admin:supersecret@[3c62:5655:8695:0f39:b065:1654:2d23:9f34]:9999",
  "userInfo": "admin:supersecret",
  "user": "admin",
  "password": "supersecret",
  "host": "[3c62:5655:8695:0f39:b065:1654:2d23:9f34]",
  "port": "9999",
  "relative": "/bar/index.html#foo",
  "path": "/bar/index.html",
  "directory": "/bar/",
  "file": "index.html",
  "anchor": "foo"
}
```

**Comment by lnewson** [comment]
TinyMCE 5.7 will now be able to parse ipv6 URIs thanks to a solution provided by @dev7355608.
