### ISSUE TITLE
Bug: Tinymce editor body does not display the content in modal popup in mozilla firefox

### ISSUE THREAD

**Issue by Pankaj611** [tinymce/tinymce#4411]
We have two editors.
- One is for inline editing, which admin user can perform directly on the page.
- Second is for editing the details of container in modal popup with content.

While opening the popup on link button click, first i check that whether any active editor is already activated or not, if any active editor is present then I display the warning message that "By continue this operation you will lost your changes", if user clicks "Yes" in confirmation then I remove the active editor and opens the popup window.

**Javascript code:**
`tinymce.remove();`

On opening the modal popup, I bind HTML content in the TextArea present in the PopUp and pass that TextArea Object as "selector" to tinymce and initialize it.

**HTML for Text Area**
`<asp:TextBox ID="txtEditorContent" runat="server" AutoPostBack="false" CssClass="editor-content" TextMode="MultiLine" />`

**Javascript code:**   

> $(function () {
>        tinymce.remove();
>         // initialize the tinyMCE Editor
>         tinymce.init({
>             selector: '.editor-content',
>             menubar: false,
>             branding: true,
>             height: 350,
>             code_dialog_height: 200,
>             setup: function (editor) {
>                 editor.addButton('image_catelog', {
>                     image: '/img/icons/ImageUpload.png',
>                     tooltip: "Upload Image",
>                     onclick: function () {
>                         jWDOpenImageCatalog();
>                     }
>                 });
>                 editor.addButton('set_link', {
>                     image: '/img/icons/Link.png',
>                     tooltip: "Set link",
>                     onclick: function () {
>                         jWDCreateLinkForInlineEditor(g_slaveKey, g_isLive, g_cultureId);
>                     }
>                 });
>             },
>             plugins: ['advlist autolink lists charmap print preview anchor textcolor code', 'searchreplace visualblocks code fullscreen', 'insertdatetime table contextmenu paste code help wordcount'],
>             toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | table | code | image_catelog | set_link ',
>         });

**Current Behavior:** HTML content is not displayed in editor.
**Expected Behavior:** HTML content is should be displayed in editor.

![issueforeditor](https://user-images.githubusercontent.com/39612319/40531143-058412ce-6019-11e8-8faa-103cc71a4389.png)

**Note:** This issue is only generated in the firefox, same code works fine in Chrome

tinymce version: 4.7.11

**Comment by Afraithe** [comment]
Need a way to replicate this in order to look at it.

**Comment by MinosIE** [comment]
Has it been solved？
I may have the same problem. 
There is nothing in tag body.
Below is the screenshot.
![image](https://user-images.githubusercontent.com/7985586/47254133-3129c400-d490-11e8-8827-15283a7d6586.png)

**Comment by IstvanMs** [comment]
I may have the same issue. I was able to reproduce it by moving the form from a parent div to an other parent div.
http://fiddle.tinymce.com/q3gaab

**Comment by sukheja-varun** [comment]
I am facing the same issue

**Comment by rhanzak** [comment]
Having the same issue.

**Comment by forcequit** [comment]
We are having this issue, anyone fixed this?

**Comment by rhanzak** [comment]
Not sure if this will help anyone else but it resolved my issue. 

I had to put my init function inside `$(document).ready()` so when my modal was initialized, the editor would render properly.

**Comment by apocalipsys** [comment]
anybody knows what the solution is? i have the same problem even in chrome and firefox

**Comment by DiamondDmitriy** [comment]
# @setTimeout необходим для корректной инициализации в firefox'e // for firefox init
        $js[] = "setTimeout(()=>{
            tinymce.remove('#$id');
            tinymce.init($options);
        }, 500);";

**Comment by kkYFL** [comment]
在Modal弹框的时候，第二次无法正常使用，基于我的问题找到了一个合适的方法，每次组件初始化componentDidMount的时候，给Editor一个唯一的key;遇到同类问题的可以试试；
find one solution:when componentDidMount give a unique key for your editor, I solve my issue by that,you can have a try.

**Comment by sandstone991** [comment]
> 在Modal弹框的时候，第二次无法正常使用，基于我的问题找到了一个合适的方法，每次组件初始化componentDidMount的时候，给Editor一个唯一的key;遇到同类问题的可以试试； find one solution:when componentDidMount give a unique key for your editor, I solve my issue by that,you can have a try.

Can you illustrate more please on this.
