### ISSUE TITLE
After submit https?:// removed?

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#4413]
I have in editor a iframe (embed youtube) and after submit the formular, the url in iframe is shortened from

https://www.youtube.com/embed/...
to
//www.youtube.com/embed/...

I can't see this as default setting for a external url in the docs https://www.tinymce.com/docs/configure/url-handling/

I think that should not shortened as default. // is http and not https. Tested in Opera.

**Comment by Afraithe** [comment]
// defaults to whatever the current page is that your in, so if your on HTTPS, it should be https.

You can maybe control this via some url handling options:
https://www.tinymce.com/docs/configure/url-handling/
