### ISSUE TITLE
paste_data_images not working as expected?

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#4415]
In doc https://www.tinymce.com/docs/plugins/paste/#paste_data_images
> This option specifies whether data:url images (inline images) should be removed or not from the pasted contents.

But thats not working as expected
http://fiddle.tinymce.com/ltgaab

What I expected:

`<img width="16" height="16" alt="star" src="data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7" />`

What I get:

`<img src="blob:http://fiddle.tinymce.com/6e831ad8-0c77-4a46-9195-af5a72b7901b" alt="star" width="16" height="16" />`

**Comment by spocke** [comment]
This is by design everything base64 gets converted into blobs while it's inside the editor. The getContent will return the base64 images or uploadImages can be used to upload them and get proper urls instead. It's  documented here https://www.tinymce.com/docs/advanced/handle-async-image-uploads/

**Comment by spocke** [comment]
Also the code editor shows the blobs instead of the base64 since it would be a terrible experience to have huge base64 chunks while editing the source.
