### ISSUE TITLE
tinymce.ui.Control not working

### ISSUE THREAD

**Issue by bdanzer** [tinymce/tinymce#4418]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
. When I debug the tinymce.ui I get only factory functions and nothing else.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
In wordpress if you add a mce_external_plugin and pass tinymce tinymce.ui.Control is undefined. I am not sure if this is a wordpress specific issue.
**What is the expected behavior?**
Should allow Control.extend but cannot since it's undefined
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Safari, Chrome, Firefox

**Comment by GlennMartin1** [comment]
Does this WordPress patch fix it for you?

https://core.trac.wordpress.org/ticket/44134#comment:17

Slated for WP 4.9.7.

**Comment by Afraithe** [comment]
Need a way to replicate this outside of WP in order to look at it.
