### ISSUE TITLE
HTML tags are removed, valid_elements setting is ignored

### ISSUE THREAD

**Issue by sanjaykhandkar** [tinymce/tinymce#4420]
***bug***

**When I add the HTML into TinyMCE, the button tag is removed **
Input HTML
> <div style="margin-top: 15px;">
    <div class="dropdown ">
        <button style="width: 265px;" aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" class="btn btn-primary btn-icon-right" type="button">
            <div class="row">
                <div class="col-md-10"><span class="selected-item">Item 1</span></div>
                <div class="col-md-1"><em class="fa fa-chevron-down">Item 2</em></div>
            </div>
        </button>
        <ul class="dropdown-menu arrow-dropdown" role="menu">
            <li><a target="_blank" href="ref1" style="line-height: 1;">Link 1</a></li>
            <li><a target="_blank" href="ref2">Link 2</a></li>
        </ul>
    </div>
</div>

After closing HTML editor 

> <div style="margin-top: 15px;">
    <div class="dropdown ">        
       <div class="row">
            <div class="col-md-10"><span class="selected-item">Item 1</span></div>
            <div class="col-md-1"><em class="fa fa-chevron-down">Item 2</em></div>
       </div>
       <ul class="dropdown-menu arrow-dropdown" role="menu">
            <li><a target="_blank" href="ref1" style="line-height: 1;">Link 1</a></li>
            <li><a target="_blank" href="ref2">Link 2</a></li>
       </ul>
    </div>
</div>

Note the button tag disappears. 

I tried a variety of settings - see the list below: 

`valid_elements : '*[*]',\
`
`
valid_elements : '+*[*]',
`
`valid_children : '*[*]',
`
`valid_children : '+*[*]',
`
`extended_valid_elements: '*[*]',
`
`extended_valid_elements: '+*[*]',`

[**Click here for fiddle**](http://fiddle.tinymce.com/2tgaab/2)

**TinyMCE should NOT remove ANY html tags if valid_elements setting is specified with a wildcard**

**Affects version 4.7.11, using Google Chrome. This worked fine in 3.9.3.**

**Comment by sanjaykhandkar** [comment]
There is a closing tag for the button on line 7. Yes this is not exactly a standard HTML - the point is - if TinyMCE removes an element without giving any option to keep it (even after specifying valid_elements setting), we are unable to trust it to be used in a production environment. We had existing legacy HTML which has elements similar to the example above and we cannot be sure what will be removed. Especially if an earlier version of Tiny MCE was allowing it to be kept.

**Comment by Afraithe** [comment]
Your HTML is invalid, DIV is not a valid element inside BUTTON according to the HTML5 specification.

If you want to enable this anyway (not recommended, no guarantee how browsers will render this)
	valid_children: '+button[div]',`

And your example should work.
