### ISSUE TITLE
In firefox, TinyMCE inline toolbar in iframe is not hidden by focusing out when click out of iframe.

### ISSUE THREAD

**Issue by alex-kowalski** [tinymce/tinymce#4422]
Hello, I like TinyMCE.
I am using TinyMCE 4.7.2. It is inline mode and it is put iframe inside.
Now I am faced one issue under certain condition.

Details are below:

And TinyMCE text element is in iframe like this.

```
...
<body>
...
<div id="outer_div">
...
<iframe id="iframe1">
...
<div class="elText element-editable mce-content-body mce-edit-focus" contenteditable="true" id="mce_0" style="position: relative;" spellcheck="false">
<p>Input your text in this area</p>
</div>
....
</iframe>
...
</div>
...
</body>
....
```

I know that normally TinyMCE toolbar is hidden when TinyMCE editor is focused out by clicking out of editor.

But when click out of editor and inside iframe, TinyMCE toolbar is hidden exactly.
But when click out of iframe, TinyMCE toolbar is not hidden in firefox, and still visible.

In Chrome, it is hidden even though by clicking out of iframe.
This is happened in firefox, in iframe.

I hope this issue solved urgently.

Thanks

**Comment by Afraithe** [comment]
Not supported, sorry.

**Comment by alex-kowalski** [comment]
Action is different for browser.
This is not issue?
It can't be fixed?
