### ISSUE TITLE
Invalid position of .mce-colorbutton .mce-preview

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4423]
Goto https://www.tinymce.com/ and see that with some screen sizes that element (a color bar below the text-color and background-color buttons) is not positioned correctly. It can be fixed by:
```
.mce-colorbutton .mce-preview {
  left: unset;
  margin-left: auto;
}
```

**Comment by Afraithe** [comment]
I am not sure what you mean here alecpl, can you provide a screenshot?

**Comment by alecpl** [comment]
![tiny](https://user-images.githubusercontent.com/546788/41638398-6d69e81a-7459-11e8-82df-90bc083ca6ee.png)
I see this in Firefox and Chrome. Resize the browser window (width) slowly to see the effect if it's not initially visible.

**Comment by alecpl** [comment]
Not an issue in TinyMCE 5.
