### ISSUE TITLE
Rename lightgrey skin to clearwhite

### ISSUE THREAD

**Issue by shoulders** [tinymce/tinymce#4426]
**Do you want to request a *feature* or report a *bug*?**
Bug/Feature request - Not sure how you guys would class this.

**What is the current behavior?**
When using the default skin 'lightgrey' there is no grey it is instead almost all white. This made me think there was a fault with my configuration.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
This seems to be normal behaviour.

**What is the expected behavior?**
Either put the skin back to being grey or rename the theme to something like 'clearwhite'

Having both themes would be better as the white theme is very hard to use and this would give choice to end users who prefer the old version. I am aware of the skin builder that is available.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
 v4.6.7+

ref: #3982 

thanks

**Comment by Afraithe** [comment]
Yeah there will be a new skin coming with a different name, not to self: Don't name skins with a color indication, should be random name!

**Comment by lnewson** [comment]
Hi,

TinyMCE 4 is now in maintenance mode so we won't be renaming the skin. However, TInyMCE 5 which was released early last year now uses a new skin named `oxide` which should prevent any such confusion. I'll go ahead and close this given we don't plan to rename the skin in TinyMCE 4 as it'd break existing installations.

Thanks!
