### ISSUE TITLE
Request to document ui_container option

### ISSUE THREAD

**Issue by jaredcrystal** [tinymce/tinymce#4427]
This is a request to add official documentation for the `ui_container` option which was added by commit https://github.com/tinymce/tinymce/commit/7fd61eeac61e9a88dfe8ed3c4c0398b5ee0328e2 and released in version 4.4.2.

This is a very useful option, and I was only able to discover it by searching through other issues. I'm sure many other people would also benefit from knowing about, and being able to use this feature.

**Comment by lostkeys** [comment]
Hey! We're going through old feature requests and I notice that this feature is for TinyMCE 4 which is now discontinued. If the feature is missing for TinyMCE 5, please resubmit a new feature request. Thanks.
