### ISSUE TITLE
A way to apply some classes to form elements/dialogs

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4429]
Creating a skin is a big task. Instead, I'd like to just apply some classes to popup windows or form elements in them.

Is there a way to bind to some event on when a dialog window is created/displayed?

**Comment by Afraithe** [comment]
Not really, but if creating a skin is a big task, can't you just override the css classes already there?

**Comment by Afraithe** [comment]
We spent a lot of time last year to modernise the codebase of TinyMCE, restructure a lot of things, switching to Typescript, sorting out build tools (to modern solutions) as well as fiddling with out testing platform.

What we didn't get to is the UI framework, altho we did do some re-structuring of the UI, moved all the components out of the core and into the theme, we didn't really touch the UI framework itself. The old UI framework currently in use still uses a sort of flexbox polyfill, this isn't really needed any more with the browser support for flexbox, so we can get rid of a lot of the on-the-fly calculations and just run with modern HTML/CSS.

That is what we are currently working on, this should normalize a lot of the dialogs, improve accessibility, keyboard navigation, responsiveness and a refresh to the general API for creating buttons, dialogs etc. 

A new skin is also in the works as a part of this of course, should make it easier to customize the look & feel (you can do more via just CSS).

We really appreciate the feedback and issues you are bringing up alecpl, thank you very much.

**Comment by alecpl** [comment]
@Afraithe @spocke Good work on v5. I still miss some events. One for when the dialog opens and maybe another one for when the menu opens. Any chance to have them in v5?

**Comment by TheSpyder** [comment]
TinyMCE has been more than two people for quite a while 😉 

The skin in v5 is designed for flexibility, the project (oxide) includes extensive live demos and should be quite easy to adjust. We recently published some documentation that should help:
https://www.tiny.cloud/docs/advanced/creating-a-skin/

Does this remove your need for events? I can see it perhaps being useful to have one when a dialog is opened, but on menu open would be quite unusual.

**Comment by alecpl** [comment]
I would still need some events. I generally don't need the full skin. I can use the default and change a few elements only. And not everything can be done via css file, I sometimes need to add/remove some classes on dialog/menu open. So, it would be nice to have these events.

One use-case is converting select elements to some pretty widgets used in my project, for this I have to assign some classes, but also js events to the select element.

With menus my use-case was to add "Close" element to the menu (e.g. font selection menu) and overlay background element on mobile/touch device, but I'm not sure I'll use this with v5.

ps. yes, I know there's more of you now, I just could get only spocke from the top of my head. That hopefully will change.

**Comment by TheSpyder** [comment]
Ah, interesting.

There is an undocumented event already - in both v4 and v5 - that you can use to know when a dialog opens. I'm not sure whether this is a fully supported event but if you don't need to adjust the menus anymore it might solve your need for now 🙂 
https://github.com/tinymce/tinymce/blob/master/src/core/main/ts/api/WindowManager.ts#L65

**Comment by andr3i4o** [comment]
Hi, tried to find some info and I found this issue. Could you please tell are there any events for data changed in the Dialog on a Dialog.Components level. What I would like to achieve is to have two select boxes that have master-slave behavior. For now I just found a solution to recreate the Dialog in onChange event of the Dialog itself, but that's kind of tricky when I would need to have more than 1 master-slave elements. Is it possible, cannot find any documentation for selectbox component. Thanks!
