### ISSUE TITLE
How to add custom plugins in tinymce mobile

### ISSUE THREAD

**Issue by k644606347** [tinymce/tinymce#4435]
I wrote a custom plugin, but it is not loaded in tinymce mobile mode
https://codepen.io/k644606347/pen/WyRxoW

**Comment by Afraithe** [comment]
Can't right now, the plugin list is white listed in order to ensure the plugin works with mobile.

We aim to open this up at some point so custom buttons etc will work.

**Comment by k644606347** [comment]
@Afraithe is there any breakthrough in this issue? :)

**Comment by lnewson** [comment]
Hi,

TinyMCE 5.1.0 was released late last year which now has the ability to use custom plugins on mobile devices. More details can be found in the [5.1 release notes](https://www.tiny.cloud/docs/release-notes/release-notes51/#mobile).
