### ISSUE TITLE
Removing row height in "row properties" doesn't update

### ISSUE THREAD

**Issue by Cordemans** [tinymce/tinymce#4438]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Selecting a table row and removing its height via: Table-> Row -> Row properties does not update its height.

[fiddle.tinymce.com](http://fiddle.tinymce.com/Mtgaab)

To reproduce select the cell and go to Table -> Row -> Row properties dialog. Remove the height of 50px en click "OK". Notice that the height won't change.

**What is the expected behavior?**
style="height:50px" should be removed from the `<tr>`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.7.13 (4.7.x)
It did work till version 4.6.7

**Comment by alecpl** [comment]
Confirmed. When clearing the Height input the Style input in Advanced tab should be updated, but isn't. However, even if I clear both inputs the height will not be reset.

**Comment by spocke** [comment]
The style and drop downs goes into a weird race condition where one will overwrite the other. We might remove the style input field and maybe add some form of plugin that allows you to edit styles of selected elements or something. I think code changes like that should be done in code view now in the row dialog but this is yet to be determined.

We are however working on a fix for this particular issue.

**Comment by SimonFc** [comment]
This bug has now been fixed in the latest version. Closing this issue but if you can reproduce it in 4.8.0 leave a comment and I'll open it up again.
