### ISSUE TITLE
Image Tools Plugin for Mobile

### ISSUE THREAD

**Issue by lcarvalho02** [tinymce/tinymce#4440]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Currently, Image tools plugin is provided for Desktop apps.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
It would be great if image tools plugin is supported in mobile apps. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by Afraithe** [comment]
Editing images on a phone with a decent UI (non native) is tricky, we might get to fiddling with this in the future.

There is a good usecase of ppl uploading files with a mobile phone and needing to resize them due to large size.
