### ISSUE TITLE
Building Tiny Aborted: Errors in @ephox/alloy

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4441]
**Bug:**
Building TinyMCE is aborted with errors in ephox/alloy

**Behavior:**
call git clone https://github.com/tinymce/tinymce.git
call npm install
call grunt:	
```
Running "shell:tsc" (shell) task
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/behaviour/Behaviour.d.ts(13,19): error TS2503: Cannot find namespace 'DslType'.
... and so on
Command failed: node ./node_modules/typescript/bin/tsc

```
**Versions:**
package.json of current master:

```
  "dependencies": {
    "@ephox/alloy": "2.0.6",
```

Win10
npm 6.10
grunt 1.2.0

TinyMCE versions: 
- master with latest commit from 07.06.2018 => building aborted
- tiny 4.7.x => building aborted
- tiny 4.6.7 => building OK

**Comment by tups** [comment]
I have the same problem : 
`Running "validateVersion" task

Running "shell:tsc" (shell) task
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/behaviour/Behaviour.d.ts(13,19): e
rror TS2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/behaviour/Behaviour.d.ts(16,14): e
rror TS2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/behaviour/Behaviour.d.ts(28,13): e
rror TS2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/component/SketchBehaviours.d.ts(4,
69): error TS2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/ui/Sketcher.d.ts(16,25): error TS2
503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/ui/Sketcher.d.ts(17,23): error TS2
503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/ui/Sketcher.d.ts(24,25): error TS2
503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/ui/Sketcher.d.ts(25,23): error TS2
503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(2,34): error TS2503:
Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(3,34): error TS2503:
Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(4,40): error TS2503:
Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(5,43): error TS2503:
Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(6,46): error TS2503:
Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(7,54): error TS2503:
Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(8,52): error TS2503:
Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(9,60): error TS2503:
Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(10,50): error TS2503:
 Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(11,40): error TS2503:
 Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/data/Fields.d.ts(12,42): error TS2503:
 Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/parts/AlloyParts.d.ts(22,48): error TS
2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/parts/AlloyParts.d.ts(24,59): error TS
2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/parts/AlloyParts.d.ts(26,73): error TS
2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/parts/AlloyParts.d.ts(31,20): error TS
2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/parts/AlloyParts.d.ts(43,54): error TS
2503: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/parts/PartType.d.ts(8,7): error TS2503
: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/parts/PartType.d.ts(15,19): error TS25
03: Cannot find namespace 'DslType'.
node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/spec/SpecSchema.d.ts(20,84): error TS2
503: Cannot find namespace 'DslType'.
`

**Comment by Afraithe** [comment]
Try clearing everything and rebuilding.

**Comment by Afraithe** [comment]
For now, if you got issues with this, just delete the node_modules/@ephox/alloy/node_modules folder and it should build fine.

**Comment by Georg-Git** [comment]
Ok - I am back in game:
Full deinstallation of node, deleting of its directories and all cache files. 
After installing node again,

=> Building tinyMCE successful.

By the way - you are aware of the warnings?

call npm install:
```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed.
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents)
```

**Comment by Afraithe** [comment]
We are aware of some warning, the original issue here is fixed and out. Thanks for reporting.
