### ISSUE TITLE
Inconsistent structure of forms

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4442]
Sorry if this will sound like a rant, but recently I tried to apply some styles to TinyMCE forms (in the default skin) adding reflow for mobile and I found it a real pain. Here's the list of issues:
1. Use of .mce-form inside of a .mce-form element. I know it's not the same as `<form>`, but there should be no nesting.
2. Missing .mce-form e.g. on Embed tab content in Insert/Edit media dialog.
3. Absolute positioning of form elements, really? `box-sizing:content-box` probably required for positioning?

It would be nice if at least 1. and 2. are fixed so the structure is consistent (and simpler).

**Comment by Afraithe** [comment]
This is a good point, some forms seem to have gotten out of control.

We are working on some heavy UI updates that should take care of this.

**Comment by alecpl** [comment]
Not an issue in TinyMCE 5.
