### ISSUE TITLE
TinyMce 4.7.12 not working in IE11 with a simple html page

### ISSUE THREAD

**Issue by pnyamy** [tinymce/tinymce#4445]
**Do you want to request a feature or report a bug?**

Possible bug.

**What is the current behavior?**
this is the code html of my page 👍 
<html>
 <head>
  <title>My test page</title>
  <script type="text/javascript" src="js/internal/tiny_mce/tiny_mce.min.js"></script>
  <script type="text/javascript">tinymce.init({ selector:'textarea' });
	tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
	});
</script>
 </head>
 <body>
     <textarea name="content">
	test</textarea>
 </body>
</html>
-----------------------------
this simple html page is not working on IE11 but working in chrome, Firefox.
when I change the src to **src="https://cloud.tinymce.com/stable/tinymce.min.js** it is working.
I have even downloaded the tinymce.min.js in the cloud and replace it with my copie in local but it still not working

**What is the expected behavior?**
the expected behevior is that it should work on IE11 as it works on Chrome and Firefox
My version of tinyMce is 4.7.12
My version of IE if 11.492.16299.0

**Comment by Afraithe** [comment]
This was fixed in .13 release.

https://www.tinymce.com/docs/changelog/
