### ISSUE TITLE
Image resize not working on edge version 17 ( works on older versions )

### ISSUE THREAD

**Issue by jamesdavieswales** [tinymce/tinymce#4446]
Current issue when using tinymce on edge version 17. 

When a image is uploaded and you attempt to resize , it automatically deselects and you are unable to get resize options. The toolbar highlight on the image icon goes on and off as if it has been clicked. You can see the resize boundaries quickly before this deselect clicks in.

Gif showing issue below : 

![issuegif](https://user-images.githubusercontent.com/16612198/41477207-8717da66-70bb-11e8-9a0c-e5f65e1857e4.gif)

**Comment by Afraithe** [comment]
This was fixed in .13

https://www.tinymce.com/docs/changelog/
