### ISSUE TITLE
[I18N] Missing translation for 'Div' and 'Pre' at least for japanese

### ISSUE THREAD

**Issue by solygen** [tinymce/tinymce#4448]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Missing translation at least for japanese 

a) "Div"
b) "Pre"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Please take a look at the content of current js.js

"Div": "Div",
"Pre": "Pre",

**What is the expected behavior?**

"Div": "[some japanese translation]",
"Pre": "[some japanese translation]",

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

https://tinymce-services.azurewebsites.net/1/i18n/download?langs=ja

**Comment by Afraithe** [comment]
They are technically tags, not sure they should really be translated?

Either way, this can be done on Transifex tinymce project by contributors.

**Comment by solygen** [comment]
Added a potential translation suggestions at https://www.transifex.com/moxiecode/tinymce/translate/#ja/core/13657877

@Afraithe: you are definitely right but imho we should handle all entries for tags similar. Please take a look at the other two entries in toolbars Formats > Block. <p> is labeled as Paragraph and Paragraph and Blockquote are translated.

**Comment by lnewson** [comment]
Hi,

Thanks for reporting this and looking at both the TinyMCE 4 and 5 translations, the missing strings are now included in transifex and in the language packs. As such I'll go ahead and close this, but please do let us know if you're still experiencing issues and we'll reopen this.

Thanks!

**Comment by lnewson** [comment]
Oops sorry, I just realized this was referring to the fact that they aren't translated in transifex. As @Afraithe mentioned though, translations are handled via the community so it's up to the relevant community members to decide if this should be translated.
