### ISSUE TITLE
Cannot justify content

### ISSUE THREAD

**Issue by Sidney-Dev** [tinymce/tinymce#4449]
Am using tinymce and everytime I click on one of the buttons aiming to justify the content (left, right, center) nothing happens and I see the following error in the console:

`Uncaught TypeError: Cannot read property 'toLowerCase' of undefined`

Is there a fix for this issue?

**Comment by Afraithe** [comment]
Create a fiddle to replicate.

http://fiddle.tinymce.com/

**Comment by value32** [comment]
i have this issue too but only on my local machine osx high sierra chrome 67.0.3396.99. when i try to reproduce this with pc and mac chrome 67 via browserstack it works. weird.

**Comment by johnunclesam** [comment]
@Afraithe I opened you link and just writed some words, you can see here:

![image](https://user-images.githubusercontent.com/21275217/42469308-9c15f556-83b7-11e8-8914-fe86b587366d.png)

**Comment by johnunclesam** [comment]
https://tinymce.github.io/tinymce-react/ same here!

**Comment by Flashspeed** [comment]
This issue exists in Google Chrome as of Version 67.0.3396.99
It does not exist on Firefox as of Version 61.0.1

**Comment by MarouaneZizah** [comment]
Same problem, the bug appears to happen only on google chrome, when I switch to firefox it works fine.

**Comment by Ewarse** [comment]
I think i found the cause of the problem: this extension: https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche. Ran into this problem yesterday after installing this extension, had no problem with the align buttons before. and the tinymce sample site also crashes when this extension is installed.
Hope this helps!
D
