### ISSUE TITLE
Shift+Enter Bug

### ISSUE THREAD

**Issue by nikolay-simeonov-86** [tinymce/tinymce#4452]
I want to report a bug.

When I press Enter it creates a new <p> and when I press Shift+Enter it creates double <br />.

![tinymce bug](https://user-images.githubusercontent.com/34009727/41760426-1398936e-75fc-11e8-8d9e-210e57c00c69.jpg)

I think it should create a single <br /> after pressing Shift+Enter.

This is done live on your website.

**Comment by SimonFc** [comment]
Hi,
Seems like this is the desired behavior. The second br is needed for positional purposes and is removed when you write.

**Comment by nikolay-simeonov-86** [comment]
Hello
Thank you for your response. I understand that this is desired behavior and explained it to my colleagues.
