### ISSUE TITLE
Inlite theme can not get toolbar node reference

### ISSUE THREAD

**Issue by MennaLu** [tinymce/tinymce#4457]
*bug*

I want to get panel information then to get toolbar reference by "tinyMCE.activeEditor.theme". But it does not return panel in inlite theme.

**Comment by SimonFc** [comment]
Hi,
This is the expected behavior. "theme.panel" refers to the main UI panel for the editor and with Inlite theme this isn't defined.

**Comment by jaschaio** [comment]
@SimonFc so how do you get a toolbar reference in inline mode without using `fixed_toolbar_position`?
