### ISSUE TITLE
Tinymce issues with PastBin file

### ISSUE THREAD

**Issue by srirampearson** [tinymce/tinymce#4461]
Hi Team,
 
Recently we upgraded the tinymce to the latest version 4.7.13. This issue is working fine in earlier tinymce version.

In IE 11 browser, we are currently facing an issue while pasting plain text using the tinymce paste plugin. When a copied text is pasted via tinymce plugin, the text got pasted indefinitely.

We tried to debug further and found that in the below plugin:
/src/plugins/paste/main/ts/core/PasteBin.ts -> line number 26 -> 'paste keyup'

--------------------------------------------------------------------------------------
The above fix is done based on the below commit:
commit 5edae84a : TINY-1612: fixed issue with pasting invalid blocks into other blocks
--------------------------------------------------------------------------------------

When I remove the paste from the above, this issue is getting fixed. 

My doubt is whether is it the right fix for this issue? If not, can you please let me know any other better option to address this issue.

Regards,
Sriram Ravi

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
