### ISSUE TITLE
Disable toolbar buttons and use them in another place 

### ISSUE THREAD

**Issue by fccoelho7** [tinymce/tinymce#4463]
Hello guys, I've got a question.

In my current project, we decoupled the text edition buttons from the sidebar (as in the example below). Using Tiny, has any way to do something like that? I don't want to style the current sidebar, I just want to use its buttons in another place, following my own styles. I got it using DraftJS (it's a React project), but following our current scenarios, Draft is very limited and requires a lot of configuration.

![image](https://user-images.githubusercontent.com/4829072/41911751-e66913a2-7923-11e8-92fc-a4a0c0c86fa2.png)

Thank you a lot!

**Comment by SimonFc** [comment]
Hey,

Maybe you're looking for something like this?
https://www.tinymce.com/docs/configure/editor-appearance/#fixed_toolbar_container
