### ISSUE TITLE
can't find theme.js

### ISSUE THREAD

**Issue by printjs** [tinymce/tinymce#4467]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/17404628/42021856-51a463b2-7aee-11e8-92bb-6bca7c46949b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
![image](https://user-images.githubusercontent.com/17404628/42021866-5a96f55c-7aee-11e8-95d6-3f13a80a4794.png)

**What is the expected behavior?**
tinymce can find plugin and theme under typescript
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

err occur in the electron app

**Comment by printjs** [comment]
I found that your project is loaded via baseURL. Why isn't require(theme/xxx.js), but loading via http request?

**Comment by SimonFc** [comment]
Hi,
Are you using a module loader? If so you should be able to simply write `require('tinymce/themes/modern/theme');` Or the same with import since you're writing in Typescript.
You can refer to https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/
