### ISSUE TITLE
After DnD image to editor, change is not saved in undo level

### ISSUE THREAD

**Issue by seraph17** [tinymce/tinymce#4468]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
While replace image src with remote location after DnD, TinyMCE will add attribute "data-mce-src" to image as well. However the attribute is not included in UndoLevel.
Which means the content is not consistent with UndoLevel.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Tugaab
1. DnD an image into TinyMCE editor
2. Check the console
![image](https://user-images.githubusercontent.com/5106157/42022738-5652929c-7abe-11e8-80fa-56199b2f5638.png)

We can see that a new undo level could be created manually. Because previous undolevel doesn't include the "data-mce-src". It does not make sence to have two undolevels for one single DnD operation.

**What is the expected behavior?**
After replacing the image src, undo level should be consistent with content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7.13. Chrome 67

**Comment by SimonFc** [comment]
Hey,
The "data-mce-src"-attribute will be stripped away when you run getContent() anyway so I don't think there needs to be an undo level that includes this. Is there any reason why you would need to have this included in the undo levels?
