### ISSUE TITLE
Inline mode does not work properly on custom elements

### ISSUE THREAD

**Issue by skerit** [tinymce/tinymce#4469]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
When creating an inline tinymce instance on a custom element (like `<my-custom-element>test</my-custom-element>`) most of the functionality won't work properly (like the bold, italic, ... buttons, or inserting hyperlinks)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

* Register a new custom-element like `my-custom-element` (or don't, because it doesn't change anything)
* Use it in your html, like: `<my-custom-element>test</my-custom-element>`
* Apply tinymce on it, enabling inline mode
* See that the buttons don't work

There's a fiddle here:
http://fiddle.tinymce.com/Wugaab

I also read that tinymce needs block elements to work properly, so I added a `style="display:block"` to my custom element instance, but even that didn't help

**What is the expected behavior?**
It should just treat it like any other element

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I tested version 4.7.13, 4.6 & 4.5 in Firefox & Chrome, but it never worked.

**Comment by SimonFc** [comment]
Hi Skerit,
Add `custom_elements: 'my-custom-element'` to your config and it should work.
You can read about it here: https://www.tiny.cloud/docs/configure/content-filtering/#custom_elements
