### ISSUE TITLE
Border Style is missing on advance tab of table properties.

### ISSUE THREAD

**Issue by darknickz08** [tinymce/tinymce#4470]
I have posted an issue on stockflow. 
Heres the link : [tinymce-missing-border-style-on-table](https://stackoverflow.com/questions/51074083/tinymce-missing-border-style-on-table)

this is my current setup of my tinymce :

`tinymce.init({`
       `selector: '.default-editor',`
      `height: 80,`
    `menubar: true,`
    `plugins: 'print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link codesample table charmap hr toc insertdatetime advlist lists textcolor wordcount imagetools  contextmenu colorpicker textpattern',`
    `toolbar1: 'formatselect | forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',`
`});`

The weird thing is, the border style on the advanced tab is missing. I just dunno what is missing on my defined plugin to show the dropdown with border style such as Dotted, Solid, etc.

**Comment by SimonFc** [comment]
Hi,
Closing this since the issue has been fixed in newer versions of tiny.
