### ISSUE TITLE
SetContent event fires twice when paste some text into the editor

### ISSUE THREAD

**Issue by seraph17** [tinymce/tinymce#4471]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
"SetContent" event fires twice when paste some text into the editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Copy and paste text, 'SetContent' event will trigger twice.
2. Paste to a blank line, the event will only trigger once.
http://fiddle.tinymce.com/bvgaab

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Chrome 67, TinyMCE 4.7.13

**Comment by fyrkant** [comment]
I don't see the problem with the event being fired twice, has this caused any problems for you?
