### ISSUE TITLE
[IE 11] [Firefox] User is unable to move the cursor outside of the table from last cell once entered text

### ISSUE THREAD

**Issue by srirampearson** [tinymce/tinymce#4475]
Hi Team,

We recently upgrade tinymce to 4.7.13.

We are currently facing below issue in IE 11 and Firefox.  Details given below:

In Tinymce editor, Insert a new table and fill all the cells. Try to move the cursor from last cell to outside of the table using keyboard arrows.
User should be able to move the cursor outside of the table using keyboard.

User is unable to move the cursor outside of the table from last cell once entered text.

You can reproduce this in the demo site.

Regards,
Sriram

**Comment by fyrkant** [comment]
I believe this was fixed in 4.8.3.
