### ISSUE TITLE
Force protocol on recognized media types

### ISSUE THREAD

**Issue by ssddanbrown** [tinymce/tinymce#4479]
This is an update request for the media plugin to work-around an edge-case issue.

**Current Behaviour**

When inserting recognised media content, such as youtube links, TinyMCE will re-write the link to be better suited for embedding but the resulting iframe urls will be protocol relative. This behaviour appears to be defined here:
https://github.com/tinymce/tinymce/blob/master/src/plugins/media/main/ts/core/UrlPatterns.ts#L22

**The Issue this Causes**

In my use-case, Users have the ability to export content, created via TinyMCE, to HTML files. For most people, when directly opened, this will be served via `file://` instead of `https(s)://`. This causes such media embeds to break as the browser tries to find the media locally since the links are protocol relative.

**Expected behavior**

I'd expect the protocol to be set directly on TinyMCE generate media url's for known services, defaulting to HTTPS for all services that support it (Which I believe is all currently defined). 
With HTTPS becoming much more prevalent and also becoming faster over the last few years I don't see much reason to support HTTP for such embeds.
[Paul Irish has some good information on protocol-relative URL's](https://www.paulirish.com/2010/the-protocol-relative-url/).

I'd be happy to create a pull request to cover this, Just want to ensure you'd be happy with this change in behaviour before I went ahead. 

Related to #3889.

**Comment by lnewson** [comment]
Hi,

This was actually implemented in TinyMCE 5.2.0, which was released last month. The media plugin will now default to using https unless otherwise specified in the URL provided. If you encounter any other issues, please let us know.

Thanks!
