### ISSUE TITLE
Browser hangs with remove a specific image

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#4480]
Go to www.tinymce.com and replace source code in editor with this

`<div class="center"><img class="center" src="http://fiddle.tinymce.com/images/spellchecker-pro-2018-04-12.png" alt="" width="347" height="400"><br><br><br><br><br><br><img class="pright" src="http://fiddle.tinymce.com/images/spellchecker-pro-2018-04-12.png" alt="" width="600" height="505"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>Soon<br><br>Here a small preview for my WIP profile description<br><br><img src="http://fiddle.tinymce.com/images/spellchecker-pro-2018-04-12.png" alt="jpg" width="712" height="400"><img src="http://fiddle.tinymce.com/images/spellchecker-pro-2018-04-12.png" alt="5rbty9h93w5vdy4zg.jpg" width="283" height="400"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><img src="http://fiddle.tinymce.com/images/spellchecker-pro-2018-04-12.png" alt="" width="354" height="257"><br></div>`

scroll down to one before last image and select image and click "delete" key. Browser hangs in chrome and firefox. Tested in jsfiddle.tinymce.com too.

**Comment by alecpl** [comment]
Works for me in Firefox 60.0.2 (64-bit) on Linux.

**Comment by fyrkant** [comment]
Doesn't hang for me but does seem to take a while before the image is deleted, might have something to do with the same image being several time in the same document? Doesn't happen is they are all different images for me: http://fiddle.tinymce.com/8vgaab

**Comment by Daijobou** [comment]
The original issue are all different images, but not extern accessable, so I replace it. Here the original  try http://fiddle.tinymce.com/8vgaab/1 to remove https://i.imgur.com/IyecCNs.jpg in firefox I get many times a firefox error to wait or stop tab. I hope this helps.
