### ISSUE TITLE
Codesample : missing features

### ISSUE THREAD

**Issue by bazooka07** [tinymce/tinymce#4481]
The library from prism.js is outdated.
Please add the version of prismjs you wrap. Today the library from prismjs.com starts with :
```
/* PrismJS 1.15.0
https://prismjs.com/download.html#themes=prism-dark&languages=markup+css+clike+javascript+c+csharp+cpp+ruby+markup-templating+java+php+python */
```
Can you add sql as default language ? A lot of php sites are working with MySQL servers and schema.sql of the database is useful.

Prismjs has an useful plugin for getting missing languages : autoloader
"Automatically loads the needed languages to highlight the code blocks"
https://prismjs.com/plugins/autoloader/

An other missing useful plugin is "Copy to clipboardd button"
"Add a button that copies the code block to the clipboard when clicked."
https://prismjs.com/plugins/copy-to-clipboard/

**Comment by lnewson** [comment]
Just as an update to this, in TinyMCE 5.2 we added the ability to use the global PrismJS instance to render the codesamples within the editor. This can be enabled with the [`codesample_global_prismjs` ](https://www.tiny.cloud/docs/plugins/codesample/#codesample_global_prismjs)setting, which then allows custom languages to be used. Here's an example showing Perl and PowerShell being added: http://fiddle.tinymce.com/6bhaab

Plugins however are a much more difficult thing to support, as the JS needs to execute against the inner iframe. That then impacts the ability to edit content, so I'll leave this open so we can consider adding PrismJS plugin support.
