### ISSUE TITLE
Wrong cursor in Edge on image resize

### ISSUE THREAD

**Issue by JasonTheProgrammer** [tinymce/tinymce#4484]
**Bug**

In MS Edge, the mouse cursor when hovering on an image resize anchor is the 'text' style.

![edge](https://user-images.githubusercontent.com/17895269/42543034-3900a858-84ed-11e8-9cb7-b587b9f68320.gif)

**Expected Behaviour**

In Chrome, the cursor changes to the appropriate 'nesw-resize' or 'nwse-resize' cursor.

![chrome](https://user-images.githubusercontent.com/17895269/42543040-47d715b0-84ed-11e8-9527-09ca800966fa.gif)

**Version**

This is easily replicated on the version currently on demonstration at the top of the TinyMCE page. https://www.tiny.cloud/
I've also replicated it in a local dev environment with version 4.7.13.

**Comment by SimonFc** [comment]
Hi Jason,
This is due to a bug with edge so there's nothing we can do about it. Thanks for reporting it though!
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3419602/
