### ISSUE TITLE
tinymce-i18n an official package

### ISSUE THREAD

**Issue by frederikhors** [tinymce/tinymce#4485]
*feature*

This guy created https://github.com/mklkj/tinymce-i18n

Is there a way to make this an official npmjs package?

**Comment by Afraithe** [comment]
Perhaps, but how often do you need all 60+ languages?

Our language download page on our website allows you to select specific languages.

**Comment by frederikhors** [comment]
Yes, @Afraithe. I know. But with a npmjs package I can `import "tinymce-i18n/langs/en_US";` for example and when there is an update I just have the new one.

Simple, not?

**Comment by alecpl** [comment]
That repo is not up-to-date. I'd like to see something like that too or in tinymce-dist? And yes, as a multilingual project that includes tinyMCE we need all languages.

**Comment by frederikhors** [comment]
Nope
