### ISSUE TITLE
Wrong arrow position in RTL directionality

### ISSUE THREAD

**Issue by azarmehri** [tinymce/tinymce#4489]
**Do you want to request a *feature* or report a *bug*?**
 report a bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/10531380/42660997-0d4dd248-8642-11e8-93cf-38db7f801d42.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Unfortunately, fiddle doesn't support Unicode characters (It can be a bug!), however, in [fiddle](http://fiddle.tinymce.com/Ivgaab), please select the second line to see the reported bug.

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/10531380/42662960-d47524f6-8648-11e8-9ac1-c850336ee768.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.8.0

**The cause**
The inline arrow has two classes with not compatible together: "mce-arrow-left" and "mce-arrow-right".

![image](https://user-images.githubusercontent.com/10531380/42663289-383d89fa-864a-11e8-9e1d-98624b8b7641.png)

I removed "**mce-arrow-left**" class from classes with inspect tool in the browser then the inline arrow works properly.

**Comment by azarmehri** [comment]
I solved this bug by changing `panel.classes.toggle('arrow-left', true);` to `panel.classes.toggle('arrow-left', false);` in ["Panel.ts"](https://github.com/tinymce/tinymce/blob/91731d0b1ed5d7e894658abb9c3a1ca686403f3b/src/themes/inlite/main/ts/ui/Panel.ts#L98) file.

**Comment by SimonFc** [comment]
Hi Azarmehri,
We found the same root of the problem and the fix will be made available in a future release. Thanks for reporting the bug.
