### ISSUE TITLE
event.path usage is discouraged

### ISSUE THREAD

**Issue by TakayoshiKochi** [tinymce/tinymce#4490]
`event.path` was introduced in Chrome for Shadow DOM V0 and is available for V1 in Chrome as well, but the usage here doesn't make sense.

https://github.com/tinymce/tinymce/blob/c433e8464819cb890bd69b4c0ff000ede6afe076/src/core/main/ts/api/dom/EventUtils.ts#L81

If there's any specific reason to keep the 'event.path' access there, please use only `event.composedPath()` as it's standard and is more future-proof (once Firefox supports or Edge supports it).

**Comment by SimonFc** [comment]
Hi Kochi,
`event.path` seems to simply serve as a fallback for when ´event.composedPath()´ isn't defined. `event.composedPath()` is given priority in any case so is there a reason for not keeping `event.path`?

**Comment by fyrkant** [comment]
@TakayoshiKochi  Oh ok, so the fix should be to move the composedPath part up before the event.path code?

**Comment by TakayoshiKochi** [comment]
Yeah, it would be that simple, or you can completely remove `event.path` because Blink-based browsers are the only ones that implement `event.path`, but also implement `event.composedPath()` so it makes very little sense you keep code for `event.path` as a fallback.

**Comment by fyrkant** [comment]
This has now been fixed.

**Comment by TanveerAliS** [comment]
`event.path` is not supported by IE or edge. Don't rely on this.

**Comment by 1337GameDev** [comment]
This issue seems to be current in TinyMCE 6. Including TinyMCE in latest chrome will present this warning.

**Comment by Daijobou** [comment]
Version 5.10.3 and 6.x I get in console this warning message for tinymce.js @fyrkant 

> Event.path is deprecated and will be removed. Please use Event.composedPath() instead.
> This change will go into effect with milestone 109.

See https://fiddle.tiny.cloud/ console

**Comment by mikoloism** [comment]
This bug currently not fixed!
