### ISSUE TITLE
Text direction changes automatically to left-to-right after pressing Enter in H1

### ISSUE THREAD

**Issue by ArieLivshin** [tinymce/tinymce#4491]
This is a Bug in TinyMCE 4. 
It happens in all browsers. I just checked it now in Windows 10 Chrome 67 and Firefox 60. 

Problem: 
Text direction changes automatically to left-to-right after pressing Enter in H1

Steps to reproduce:
- change the text direction to Right-To-Left (push the "Align Right" button)
- insert some text and then select it and make it H1 (Header 1)
- press Enter
- type something

you can see that the edit direction for some reason is switched back to Left-To-Right.

Expected behavior:
Text direction should remain Right-To-Left.

**Comment by SimonFc** [comment]
Hi Arie,
This is the expected behavior and how it's intended to work since headings are block elements. Try it out in Google docs for example and you'll see the same behavior.
