### ISSUE TITLE
Another bug with tinymce 4.X

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#4493]
The bug can be seen here: http://fiddle.tinymce.com/lvgaab

After opening the link above click on the right of xxx an leave the cursor blinking. Then press backspace 3 times to erase the 3 x's. Now start typing anything, you will see that the text will lose the red color.

In programs like MS WORD, BR OFFICE and so on, when you do what I said above you dont lose format, if you type something after erasing xxx the text will keep the format.

This is a very annoying bug and the solution to it is another bug! The solution would be to set valid_elements: `*[*],#span[*]` (in the specific case of TinyMCE) so TinyMCE would add a &nbsp; in empty span tags (the "padding" technique) however a bug with the padding (#) regarding span prevents the &nbsp; to be added.

How to solve this?

**Comment by fyrkant** [comment]
I don't think this is a bug but an example that shows the difference between native applications like Office and WYSIWYG HTML editors like TinyMCE. My tip is to not backspace away the content of the span but instead select it and write over it to at the same time remove the old content and add new content with the same styling.

**Comment by batata004** [comment]
@fyrkant will all respect what you telling me to do is a complete nonsense. You are telling me that I should not erase the last letter and instead, select it and write over it??? This looks pretty much like a hack. It's not practical at all.

I cant believe there are developers with this type of mind on TINYMCE project. Anyway, gladly, other people on other thread found this behaviour to be a bug. Link below. I am pretty sure you will try to close that thread too and prevent that good soul to fix the BUG. It's complete NONSENSE WHAT YOU TOLD ME. It not even a "hack", it's a stupid way to fix a BUG.

https://github.com/tinymce/tinymce/issues/4492#issuecomment-405186288
