### ISSUE TITLE
[I18N] Border Style translations are missing for table plugin

### ISSUE THREAD

**Issue by OlivierJaquemet** [tinymce/tinymce#4494]
Some I18N strings of the link plugin are not translated at all.

**To reproduce** : 
- Configure any version of TinyMCE (for example the edge on this day) : 
    - to use any language but the default english version
    - with the table plugin properly configured, 
- Access the editor and insert a table
- Right click on a cell and display cell properties

**BUG** : item "Border style" and its values are not translated
![image](https://user-images.githubusercontent.com/618861/42747017-d6ff15bc-88da-11e8-87f1-adcf0744f6b2.png)

**Expected** : item and value should be translated in the current language selected

**Explanation** : 
[Some strings](https://github.com/tinymce/tinymce/blob/6cb22eb2f21c4593b643d079862ff2380490ab72/src/plugins/table/main/ts/ui/Helpers.ts#L151)  of the table plugin are NOT in the I18N resource provided :
https://www.transifex.com/moxiecode/tinymce/plugin-table/

**Comment by OlivierJaquemet** [comment]
Related issues with same cause :
#3893 #4444

**Comment by SimonFc** [comment]
I'm closing this issue since it's limited to Tiny 4. In Tiny 5 everything related to the Table and Link plugins seem to be translated

**Comment by OlivierJaquemet** [comment]
@SimonFc This is unfortunate as version 4 is still widely used as far as I know. But this is your product, I won't argue for this moderate issue.

**Comment by SimonFc** [comment]
I should have mentioned that Tiny 4 will only receive fixes for critical issues. It's appreciated that you did report this though even if we didn't have time to fix it.
