### ISSUE TITLE
Issue with Insert File

### ISSUE THREAD

**Issue by patrickvn1** [tinymce/tinymce#4497]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Whereas you used to be able to highlight text, then click insert file, and have it create a hyperlink to the file with that text, now that doesn't work. Doing that doesn't result in a hyperlink or an inserted file. Inserting an image in this way results in the text being replaced by the image.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Enter some text into the text box. 
2. Highlight the text by clicking, dragging, and releasing your mouse.
3. Select insert file
4. Click a document like a PDF or Word doc.
5. see that it doesn't insert the file as a hyperlink. nothing happens

**What is the expected behavior?**
You should be able to highlight text, then click insert file, and have it create a hyperlink to the file with that text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It's TinyMCE 4.2.7 in all browsers on Windows 10 for sure.

**Comment by Rishats** [comment]
Very important bug!

**Comment by fyrkant** [comment]
So is this an issue with the image plugin? Or the media plugin? Not sure I'm understanding the problem, can you create a fiddle showing a clear reproduction? The link plugin will do what you are talking about, if you click the link button while text is selected the selected text will be set as the link's text to display.
