### ISSUE TITLE
Image not linking in V  4.1.3 

### ISSUE THREAD

**Issue by hamzazafeer** [tinymce/tinymce#4499]
I have Tinymce version 4.1.3.

I upload the image, which is fine, but then i want to add link on image, when i select the image it shows error in console.

> Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.

and when i add the link in popup, the **OK** button is not working, it again give me the above error. 

My Chrome version is 

> 67.0.3396.99 (Official Build) (64-bit)

how can i solve this issue?

**Comment by sitecarp** [comment]
@hamzazafeer It may help to know that the latest version as of this comment is 4.8.0, which seems to working without the issue you describe.

**Comment by hamzazafeer** [comment]
@sitecarp you want to say that, i have to update my tinymce?

**Comment by sitecarp** [comment]
@hamzazafeer Yes, updating to the latest version should fix the problem. You are using an old version.

**Comment by hamzazafeer** [comment]
@sitecarp ok i'll check it.

**Comment by fyrkant** [comment]
Yes I think this is a problem that has been fixed in later versions of TinyMCE, so I'm closing this issue. Leave a comment if you can recreate the issue in 4.8.0.
