### ISSUE TITLE
Download links deliver outdated versions.

### ISSUE THREAD

**Issue by sitecarp** [tinymce/tinymce#4500]
This is an issue with the documentation rather than with the software itself.

The [Build Customizer page](https://www.tiny.cloud/download/custom-builds/) delivers outdated version 4.7.13. 

And the [Advanced Install page](https://www.tiny.cloud/docs/get-started/advanced-install/#step1downloadthejquerypackage) contains a link to download the jQuery version of TinyMCE. However, if you select the _non_-jQuery version radio button in the form, it will deliver version 4.3.12.

**Comment by sitecarp** [comment]
How do I download a custom version of 4.8.0?

**Comment by Afraithe** [comment]
The customizer always lags behind the version a few days or so, but it should give you 4.8 now.

**Comment by sitecarp** [comment]
@Afraithe The Build Customizer does seem to have been updated. Thanks!

However, has the jQuery version be discontinued? The newer Build Customizer doesn't include it as an option, and the [older customizer](http://archive.tinymce.com/download/custom_package.php?_ga=2.70052880.1864230400.1532370929-2007562915.1531341460) still accessible through the [jQuery section of the Advanced Install section](https://www.tiny.cloud/docs/get-started/advanced-install/#step1downloadthejquerypackage) delivers outdated version 4.3.12. That part of this ticket may need to remain open.
