### ISSUE TITLE
Missing option to add CSS classes to links with link editing dialog

### ISSUE THREAD

**Issue by felixgonschorek** [tinymce/tinymce#4501]
**Do you want to request a *feature* or report a *bug*?**

I would like to request a feature that was available in TinyMCE 3.x

**What is the current behavior?**

In TinyMCE 3.x it was possible to select a CSS class for the <a /> tag in the link editor dialog. In the current version (4.8.13) there is no option to select CSS class for links. When adding a style class with the "formats" option, an additional <span /> tag is created around the link and the CSS class is applied to the <span /> tag instead of the <a /> tag

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

It's not a bug, it is a feature that was available in earlier versions. We recently upgraded and it would be very hard to rewrite all our stylesheets to match this new behaviour. If we can contribute in any way please let us know.

**What is the expected behavior?**

We would love to see the behaviour of TinyMCE 3.x: the style classes in then "content_css" configuration option are available in the link editing dialog utilizing an drodown / select element.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I don't think it's browser related and it worked with old versions of tinyMCE prior 4.x

Thanks a lot for looking into this issue.

**Comment by felixgonschorek** [comment]
This is for label: "plugin:link"

**Comment by Afraithe** [comment]
The correct way of doing this in 4.x is to use style_formats or formats toolbar with some custom styles.

**Comment by felixgonschorek** [comment]
Thank you for the fast response!

I see, this option is of course very powerful. The ease of use with shared "content_css" classes in 3.x is lost though, but i think understand the reasoning, with content_css all classes (event those which were not meant to be used on links) were available in the dropdown.

We will adopt to the new way of dealing with this, thanks again.

**Comment by fyrkant** [comment]
Closing this as it seems to be resolved.
