### ISSUE TITLE
Inlined CSS styles do not update if they already exist in the table's style attribute

### ISSUE THREAD

**Issue by alexmaris** [tinymce/tinymce#4509]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Configure any version of TinyMCE (for example the edge on this day) with the table plugin properly configured and the `table_style_by_css` property set to `true`

1. Access the *Table Properties* dialog
2. Set a value of `1` in the *Border* input box
3. Click OK
4. Access the *Table Properties* dialog for the same table
5. Set a value of `2` in the *Border* input box
6. Click OK
The table's inline style retains the initial value of `1` ( `border-width: 1px;`)

**What is the expected behavior?**

Configure any version of TinyMCE (for example the edge on this day) with the table plugin properly configured and the `table_style_by_css` property set to `true`

1. Access the *Table Properties* dialog
2. Set a value of `1` in the *Border* input box
3. Click OK
4. Access the *Table Properties* dialog for the same table
5. Set a value of `2` in the *Border* input box
6. Click OK

The table's inline style has the new value `2` (` border-width: 2px;`)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested on v4.7.0 through v4.8.1 on Mac/Chrome 67.0.3396.99 

**Proposed fix**
The style override happens at:  https://github.com/tinymce/tinymce/blob/9f8cbf3a9589f0e67027e81975b72c37ff680456/src/plugins/table/main/ts/ui/TableDialog.ts#L109

That line should extend the existing styles with the new values via:
`styles = Tools.extend({}, dom.parseStyle(data.style),styles);`

I can write a unit test and submit a PR.

**Comment by lnewson** [comment]
Thanks for the report! This appears to have already been fixed in the latest version of TinyMCE. Are you able to replicate it anymore using TinyMCE 5?

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
