### ISSUE TITLE
Bug - No padding on textbox if I add custom css

### ISSUE THREAD

**Issue by jackttcoms** [tinymce/tinymce#4512]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
No padding is textbox

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Here is a fiddle: http://fiddle.tinymce.com/Jxgaab

And the error is caused when i use this: 
`content_css: '//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',`

**What is the expected behavior?**
To have padding in the textbox.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: 4.7.0 (Note I have also tried it with 4.8.1)
Browsers: All

**Comment by MichaelFromin** [comment]
Your bootstrap CSS expressly sets the body margin to 0 so TinyMCE is doing exactly what you are asking it to do.  If you don't want that behavior you should not pass that particular CSS to the editor or override the bootstrap CSS with additional CSS.
