### ISSUE TITLE
How to stop loading default content.min.css for default theme inside iframe? (feature rqst)

### ISSUE THREAD

**Issue by stopsopa** [tinymce/tinymce#4513]
**Do you want to request a *feature* or report a *bug*?**
Request a feature.

**What is the current behavior?**
There is no option to tell tinymce to NOT load ANY css/styles to iframe

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Reproducing the bug is done in this issue:
https://community.tinymce.com/communityQuestion?id=9066100000097TqAAI
title(How to stop loading default content.min.css for default theme inside iframe?)

**What is the expected behaviour?**
To have option to stop tinymce from loading any default css, in order to don't be forced later to override already existing css rules. Just let user to load his own style (using content_css) and nothing more.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All versions. Just nobody thought about it (IMO).

**Comment by rilwis** [comment]
+1 for this feature.

It's necessary to prevent loading the same CSS file multiple times if we have multiple editors on a same page.

**Comment by TheSpyder** [comment]
You can set `content_css` to false, but that won't remove _everything_.

There is some level of styling required for core features to function (e.g. resize handles, search/replace highlights). The only way we can avoid requesting it is to build some other way to inject those mandatory styles into the content.

Loading the same CSS file multiple times should be cached?

**Comment by stopsopa** [comment]
It seems tinymce team doesn't care anymore ...

**Comment by TheSpyder** [comment]
No, we just forgot to link this ticket to our fix when it was released a year ago. Starting with TinyMCE 6.8.0 all CSS can be easily bundled with the editor, which avoids the request for `content.min.css`.
https://www.tiny.cloud/docs/tinymce/latest/react-pm-bundle/
