### ISSUE TITLE
Under the inlite theme, the cursor exceeds the editing range, and the toolbar does not appear.

### ISSUE THREAD

**Issue by tonyChenHey** [tinymce/tinymce#4517]
The toolbar cannot appear when the text selected in the editing area is beyond the editing area.

**Comment by fyrkant** [comment]
Can you create a reproduction of the issue in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by wonderbugtiny** [comment]
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.
