### ISSUE TITLE
Conflict between invalid_styles and advanced image plugin

### ISSUE THREAD

**Issue by dtra** [tinymce/tinymce#4518]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If an editor has the image plugin set, and invalid_styles: 'margin' (or border as well), when setting horizontal and vertical space, the margin style on an image will disappear. It should maintain the individual styles if it can't use the compounded style.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/lygaab
Insert an image and set the horizontal and vertical spacing, when setting both fields the style field is cleared and will not work.

**What is the expected behavior?**
The styles are still applied to the image.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All browsers and latest tinymce, do not see a working version of tinymce.

**Comment by fyrkant** [comment]
This is more of a feature request than a bug report, if you set margins to be invalid then I think it is working as expected when margins are removed.

**Comment by dtra** [comment]
Hi, fair enough (even though margin and margin-* are different properties), but can I just mention that margin is not included in my paste_word_valid_elements
`paste_word_valid_elements: "b,strong,i,em,u,a[href],br,p"`
but is still coming across when pasting from word, that is why I included it in invalid_elements
