### ISSUE TITLE
Async Image Uploads on Mobile

### ISSUE THREAD

**Issue by kyleboe** [tinymce/tinymce#4520]
### Do you want to request a *feature* or report a *bug*?**
Feature

-------

### What is the current behavior?
Images get put into the editor as blob data.

-------

### If the current behavior is a bug, please provide the steps to reproduce.
Upload an image on mobile with `images_upload_url` set.

-------

### What is the expected behavior?
TinyMCE will send the image data to the url provided and swap out the image with the location in the JSON response.

-------

### Which versions of TinyMCE, and which browser / OS are affected by this issue?
All mobile browsers.

-------

### Did this work in previous versions of TinyMCE?
No.

**Comment by JiaLe1** [comment]
I found a way to ignore the upload failure by using success ("").
success(path)  // path is your server return url use url replace base64
success("")  // use "" replace base64 

```
images_upload_handler: function(blobInfo, success, failure) {
          if (blobInfo.blob().size > _this.maxSize) {
            _this.$message.error('文件过大')
            success('')
            failure('文件过大')
            return null
          }
          if (_this.accept.indexOf(blobInfo.blob().type) >= 0) {
            update()
          } else {
            _this.$message.error('请上传一张图片')
            success('')
            failure('请上传一张图片')
          }
          function update() {
            let file = blobInfo.blob()
            let formData = new FormData()
            formData.append('file', file)
            _this.updateImg(formData)
              .then(res => {
                console.log(res)
                _this.$emit('on-upload-success', { res, success, failure })
              })
              .catch(() => {
                _this.$emit('on-upload-fail')
                failure('上传失败')
              })
          }
        },
```

**Comment by JiaLe1** [comment]
```
onUploadSuccess(params) {
      console.log('params', params)
      if (params.res.code != 0) {
        params.failure('Error:' + params.res.message)
        return
      }
      params.success(params.res.data.path)
    },
```

**Comment by ardyfeb** [comment]
> ```
> onUploadSuccess(params) {
>       console.log('params', params)
>       if (params.res.code != 0) {
>         params.failure('Error:' + params.res.message)
>         return
>       }
>       params.success(params.res.data.path)
>     },
> ```

The failure message not showing on tinymce mobile theme. And if the failure called the image keep attaching as base64 url

I want to verify image on server (php)

Here my code 
```
imageUploadHandler = (blobInfo, success, failure) => {
        const files = blobInfo.blob()
               
        const fd = new FormData()
        fd.append('file', files)
        
        let $this = this;
        
        axios.post(API.file.upload, fd, {
            headers: {
                'Authorization': Cookies.get('token')
            }
        })
        .then(response => {
            success(response.data.data.url)
        })
        .catch(error => {
            failure(error.response.data.message)        
        })

    }
```
The image keep attach though the failure called

**Comment by JiaLe1** [comment]
try
`success("")`

before
`failure(error)`

```
...
.catch(error => {
    success("")
    failure(error)
})
```
