### ISSUE TITLE
Immutable inline entities

### ISSUE THREAD

**Issue by marek-baranowski** [tinymce/tinymce#4535]
Is it possible to insert immutable inline entities? Something like "widgets" in CKEditor: [https://ckeditor.com/docs/ckeditor4/latest/guide/dev_widgets.html](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_widgets.html).

Example usage:
[Latex - MathJax](https://sdk.ckeditor.com/samples/mathjax.html), [Placeholder](https://sdk.ckeditor.com/samples/placeholder.html)

**Comment by Afraithe** [comment]
You should be able to set contentEditable=false on almost any element, and it will be handled like a single non editable element/block. And you can nest with contentEditable=true elements inside another false etc.
