### ISSUE TITLE
Toolbar buttons overlap menus

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4542]
Toolbar buttons have higher z-index that the popup menus.

This can be reproduced if there's not enough place to display the menu below the toolbar.

![tiny_menu_bug](https://user-images.githubusercontent.com/546788/44573796-e76e7700-a787-11e8-8511-b888eb88d7b2.png)

https://codepen.io/tinymce/pen/NGegZK

**Comment by jipexu** [comment]
true !!

yes  if the  z-index (65535)  is to low (with 70000 it's become ok)

`<div id="mceu_203" class="mce-container mce-panel mce-floatpanel mce-menu mce-animate mce-menu-has-icons mce-menu-align" hidefocus="1" tabindex="-1" role="application" aria-labelledby="mceu_203" aria-describedby="mceu_203-none" style="border-width: 1px; z-index: 65535; left: 447.733px; top: 275px; width: 190.15px; display: none;">`

**Comment by alecpl** [comment]
Not a problem in TinyMCE 5. Closing.
