### ISSUE TITLE
Mousepress (focusin) event conflicts with other libraries, eg flatpickr

### ISSUE THREAD

**Issue by NicolasCast** [tinymce/tinymce#4543]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

1. Have both tinymce and flatpickr on a page, 
2. open flatpickr's calendar,
3. click on tinymce's textarea (focus in).

The flatpickr calendar should close. 
It does not.

I did not investigate much, but my best guess is that flatpickr and tinymce both compete for a mousepress / mousedown event, which handlers probably conflict.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

https://jsfiddle.net/wr2xqL09/

**What is the expected behavior?**
flatpickr should close when tinymce is gets focus.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Occurs on Edge, with various versions.
Occurs with firefox, chrome ; and both on mobile and desktop (windows)
I suspect it occurs on any versions/navigator/OS.

**Comment by NicolasCast** [comment]
Potential hack : mount a "focus" event on tinymce, which closes all the flatpickr

```
tinymce.init({
  selector: '#textarea_tinymce'

  // here we go.
  // Assuming that all the input powered with flatpickr have a  "flatpickr-input" class
  init_instance_callback: function (editor) {
      editor.on('focus', function (e) {
        var elementsThatMayHaveFlatpickr = document.getElementsByClassName("flatpickr-input");
        console.log("Number of potential flatpickr object : " + elementsThatMayHaveFlatpickr.length);
        for(i = 0 ; i < elementsThatMayHaveFlatpickr.length ; i ++) {
          fp = elementsThatMayHaveFlatpickr[i]._flatpickr;
          if(fp) {
            console.log("flatpickr detected. Closing.");
            console.log(fp);
            fp.close();
          }
        }
      });
    }
});
```

**Comment by NicolasCast** [comment]
Still, it is a pity that mounting tinymce on a textarea changes the focus-in behaviour for the whole page

**Comment by Afraithe** [comment]
It is cause the editable area is an iframe, the flatp lib checks the focus on the body. If they hooked it to onblur="" on the element, it would work.

Nothing we can fix in TinyMCE.
