### ISSUE TITLE
Toolbar doesn't opens if cursor outside of editor's container (Distraction-free mode)

### ISSUE THREAD

**Issue by petyunchik** [tinymce/tinymce#4546]
There is a bug in distraction-free mode when toolbar is not showing if selection ends outside of editor's DOM element area.

It can be easily reproduced from the main page of https://www.tiny.cloud (Distraction-free). Just start select text and release mouse button outside of editing area.

TinyMCE version is 4.8.2

Tested with Chrome 68 and Firefox 61

![selection](https://user-images.githubusercontent.com/673497/44732421-e9b93400-aaed-11e8-9195-a3262289bb00.gif)

**Comment by lucastsudaka** [comment]
Waiting for fix too. 
Same problem in 5.0.5

**Comment by TheSpyder** [comment]
This seems less about the selection, and more about whether the mouseup event is outside the editor. Same effect but the details of the bug are different.

The events we use to track whether the toolbar should be shown are all in-editor events.
