### ISSUE TITLE
Possible typo... 

### ISSUE THREAD

**Issue by SDemonUA** [tinymce/tinymce#4557]
https://github.com/tinymce/tinymce/blob/ffb37d4ad2c610268569b1ed0c524be9040a6be9/src/core/main/ts/api/Editor.ts#L519

**Comment by lnewson** [comment]
Looks like this got left around when the initialisation logic was moved in 1392dd3ed4ba382638768c8612e6c1a49388b46b, so it probably just needs to be cleaned up.
