### ISSUE TITLE
Cant write in editor in firefox

### ISSUE THREAD

**Issue by kbhutiya** [tinymce/tinymce#4562]
- Bug

- can’t write inside the editor,there is no id=“tinymce” with the body! Body is empty and non editable only inside firefox

- Error in firefox says ‘doc is undefined’ ,it has a variable doc which it is not getting in firefox

- It should be editable and should work same in all browsers !
- tinymce is on version 4.8.3 and browser affected is firefox

**Comment by Afraithe** [comment]
This has to be issues with implementation, it works on our demos and tests.

**Comment by ParaHang** [comment]
occurs to me as well
