### ISSUE TITLE
Editor with 6000 characters is not getting initialized

### ISSUE THREAD

**Issue by CwPiyush** [tinymce/tinymce#4565]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Editor with more than 6000 characters is not getting initialized
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://jsfiddle.net/4o3vuqca/2/
**What is the expected behavior?**
Editor must be inintialized irrespective of character length
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
3.4.8 released on 2012-02-02

**Comment by MichaelFromin** [comment]
TinyMCE 3.x is no longer being developed so this issue would not ever be addressed.  We would recommend moving to the latest TinyMCE version.
