### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by waleedHassan95** [tinymce/tinymce#4567]
I know this error has been discussed a lot but it seems no solution worked for me.

I Tried : Replacing TinyMc folder , reinstalling wordpress , clearing cookies and cache ,deactivating all plugins and using define('CONCATENATE_SCRIPTS', false); in wp-config and i tried different browsers but nothing seems to work
![tinymc](https://user-images.githubusercontent.com/27697404/45702513-4dc19c00-bb72-11e8-9341-f74e680194a8.PNG)

**Comment by Afraithe** [comment]
This seems to be an issue with Wordpress?
