### ISSUE TITLE
mceToggleFormat bug

### ISSUE THREAD

**Issue by Vinz3056** [tinymce/tinymce#4568]
Hi, here is a new bug I found...

If you look [this]( http://fiddle.tinymce.com/p0gaab/5) you can see this one.

If you select one word in a sentence (and just one word, no spaces around), you'll see in Current HTML Content tags are added, but spaces are removed... And I think they should not.

**Comment by androb** [comment]
I can replicate this with the above Fiddle

**Comment by lnewson** [comment]
I had a chat to the team about this and this appears to be a configuration issue, as the wave custom element is marked as a `block` element in the `custom_elements` setting, however the custom format is using it as `inline`. So if you change the configuration to make the custom wave element inline, then `editor.getContent` does return the correct content.

Here's a fiddle with wave defined as an inline element, which you can see that the spacing is correctly preserved there when clicking "Change style": http://fiddle.tinymce.com/o2gaab/1

**Comment by lnewson** [comment]
Closing this one since it's a configuration issue.
