### ISSUE TITLE
Bug - Continuous delete key press across spans

### ISSUE THREAD

**Issue by smg-mbhanushali** [tinymce/tinymce#4572]
If I navigate to the beginning of a div that contains a bolded text and continuous press the delete key, it deletes only to the last letter of the bolded text and stops working past that letter.

If I position the cursor any place after the first letter of a paragraph, the continuous delete key press works just fine.

This can be seen in the the demo https://www.tiny.cloud/docs/demo/basic-example/ 

1. position the cursor at the beginning of a paragraph that contains bolded text (such as "Note that any MoxieManager file a...")
2. continuous press the delete key
3. verify that you can not delete past the last letter of the bolded text (MoxieManager)

This is reproducible in Chrome and IE 11 but not in Firefox. I have only tried it on version 4 of TinyMCE

**Comment by lnewson** [comment]
Thanks for the report! I can replicate this and was actually able to reproducible it in Firefox as well, but it's a little bit harder. One way I found to reproduce it across all browsers is to do the following:

1. Insert some text such as <code>abc &nbsp;def</code>
2. Place the caret in the middle of the two spaces and then select bold.
3. Try to press delete and notice that nothing happens.

**Comment by lnewson** [comment]
This should now be fixed, as of version 4.8.5.
