### ISSUE TITLE
Inserting custom element, attribute gets stripped

### ISSUE THREAD

**Issue by frikinside** [tinymce/tinymce#4573]
I made a tinymce fiddle about this problem: [http://fiddle.tinymce.com/O0gaab](http://fiddle.tinymce.com/O0gaab)

I add a custom element "custom-block" and a custom plugin to insert that element.

```
tinymce.PluginManager.add('custom', function(editor, url) {
editor.addButton('custom', {
text: 'CUSTOM',
onclick: function() {
// Open window
editor.windowManager.open({
title: 'Custom plugin',
body: [
{type: 'textbox', name: 'src', label: 'SRC'},
{type: 'label', name: 'title', text: 'Insert content bellow:'},
{type: 'textbox', name: 'content', multiline: true, style: 'width:500px;height:100px;'}
],
onsubmit: function(e) {
console.log(e.data);
editor.insertContent('<custom-block src="' + e.data.src + '">' + e.data.content + '</custom-block>');
}
});
}
});
});
tinymce.init({
selector: "textarea",
plugins: [
"advlist autolink lists link image charmap print preview anchor",
"searchreplace visualblocks code fullscreen",
"insertdatetime media table contextmenu paste custom"
],
toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | custom",
//valid_elements: "+*[*]", //when using this option trying to allow everything get an error "Cannot read property 'src' of undefined"
extend_valid_elements: "custom-block[src]",
custom_elements: "custom-block"
});
```

The element, get inserted correctly but without the src attribute.

From the documentation I though that extend_valid_elements: "custom-block[src]" would allow src attribute on a "custom-block" but it gets stripped everytime.

I also tried to set valid_elements to everything just in case, but then gets worse because at inserting, I get an error: "Cannot read property 'src' of undefined".

I am making any mistake or what is the problem?

**Comment by MichaelFromin** [comment]
The name of the configuration option is `extended_valid_elements` so you simply named it wrong in your configuration. It should be:

`extended_valid_elements: "custom-block[src]"`

I have updated your fiddle (http://fiddle.tinymce.com/O0gaab/1) and things appear to work.
