### ISSUE TITLE
Highlighting text on TinyMCE visual editor not working iOS 12 Safari (WordPress.com)

### ISSUE THREAD

**Issue by alisterscott** [tinymce/tinymce#4579]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Highlighting text in a TinyMCE visual text box doesn't work as intended on iOS 12 - highlight a word then try to extend selection either side of the word

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Open http://fiddle.tinymce.com/ in mobile iOS 12 touch device
2. Enter a paragraph of text
3. Highlight/Select a single word
4. Try to extend selection either side of word

**What is the expected behavior?**

Can extend selection word by word

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

This is impacting the WordPress.com Calypso project https://github.com/Automattic/wp-calypso/issues/27399

We use the latest version of TinyMCE 4.8.3

**Comment by charlesr1971** [comment]
Yes. I am getting the same behaviour on iOS 12, iPhone 7, & iPad. Please sort this out. It makes mobile editing virtually impossible. I am using the TinyMCE mobile configuration.

**Comment by TeslaMHL** [comment]
Hello, we are getting the same behaviour on the aforementioned devices and it´s a real pain because it makes the editing of text on ios devices virtually impossible.

Could anyone from TinyMCE (@spocke - maybe you could push this to the right person?) please give us a timeline on this bug and how/if/when it will be fixed? 

Thanks alot for your time.

**Comment by charlesr1971** [comment]
Having said that, the mobile version of TinyMCE is great, except for this one MAJOR problem. It's a great shame that such a good mobile text editor is blighted by this problem.

**Comment by maxledoux** [comment]
Is TinyMCE working on this bug? It's a huge issue for our site. Very frustrating for iOS users to not be able to highlight text.  We're looking into alternative editors but would prefer to stay with TinyMCE.

**Comment by androb** [comment]
I'll try and get some attention on this

**Comment by charlesr1971** [comment]
That's great. Because, this is a serious problem for iOS users!

**Comment by maxledoux** [comment]
Thank you. 👍

**Comment by wonderbugtiny** [comment]
Thank you for the report. I was able to replicate the issue and it seems to be a bug in iOS 12.x and above. Selection is broken in contentEditable and not specifically TinyMCE.

We have reported the bug to Apple and are waiting on their response. I have also logged an issue internally for us to work on a fix in the meanwhile.

**Comment by charlesr1971** [comment]
Yes. I agree. I am using an iPhone 8+ with iOS 12.2, and text selection seems to work perfectly now! Superb. 

So, it was an Apple issue, after all, and not a TinyMCE bug!

**Comment by wonderbugtiny** [comment]
Please note that we have verified that the fix is to update to iOS version 12.2. Thank you.
