### ISSUE TITLE
Bug - custom styles from content_style appear on toolbar buttons

### ISSUE THREAD

**Issue by IgorKurkov** [tinymce/tinymce#4580]
Report a *bug* 

**current behavior:** 
![image](https://user-images.githubusercontent.com/29090227/46078107-e3c17c00-c19b-11e8-8319-5184e092a133.png)
predefined styles from 'content_style' with predefined body_id overrided (set as inline) styles for toolbar buttons.

reproduced a minimal demo of the problem: http://fiddle.tinymce.com/d1gaab 

expected behavior: disable reassigning styles expected for body area to toolbar buttons

versions of TinyMCE: latest 4.8.3, 
which browser: Chrome latest 2018/10
OS: mac os high sierra x64

Can anyone help me?

**Comment by androb** [comment]
Not sure I see the problem here? Can you give more of an explanation of the behavior you were expecting?

**Comment by TheSpyder** [comment]
This is a feature; the styles dropdown attempts to render the item in the same style as it will be applied in the document. Perhaps we could expand the background styles to the whole menu item, that might look better.

Is what you're asking for an option to disable this rendering?

**Comment by IgorKurkov** [comment]
Yes, I think it'll be great option for disable rendering of internal styles on toolbar buttons. Maybe it already exist?

**Comment by fyrkant** [comment]
There's a setting for this where you can turn of preview of styles completely or narrow down which styles to preview: https://www.tiny.cloud/docs/configure/editor-appearance/#preview_styles
