### ISSUE TITLE
Build Customizer packages an old release

### ISSUE THREAD

**Issue by schutze** [tinymce/tinymce#4581]
I believe this is a bug.

Go to [Build Customizer](https://www.tiny.cloud/download/custom-builds/).  I unchecked "combine all js files" but I'm not sure that matters.  Click the "Download" button.

The tinymce.min.js file contains // 4.8.0 (2018-06-27) at the top.  The current release at the present time is 4.8.3 (2018-09-13), which addresses a number of bugs.  

I think Build Customizer should always be up-to-date with the latest release but if that is not the intention then the version number it creates should be noted somewhere, like the [Self-hosted Releases](https://www.tiny.cloud/download/self-hosted/) page.

**Comment by TheSpyder** [comment]
Looks like this was updated as part of the new website launch (the customiser link is now at https://www.tiny.cloud/get-tiny/custom-builds/). When I download now it uses 4.8.3
