### ISSUE TITLE
TinyMCE 5 Preview: Regressions

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4590]
https://www.tiny.cloud/docs-preview/demo/full-featured/

1. View > Preview feature is broken.
2. Toolbar icons are not vertically aligned (you can see this when you hover the button).
3. Fullscreen is broken.
4. Menus z-index issues on the test page: Just open the Insert menu.
5. Insert > Date/Time options submenu should not have that left margin/padding.
6. In dialogs select fields have blue outline on focus, but inputs do not.
7. button.tox-tbtn element should have a title attribute, it's not clear what's its purpose.
8. The button above should have tabindex - is not accessible with Tab key navigation.
9. Checkboxes should work with Space key, now it works only with Enter key.
10. Focus on checkboxes and e.g. .tox-button--naked is not consistent (e.g. Insert/Edit image dialog).

**Comment by androb** [comment]
Thanks. Keep them coming! I'll probably parse this out into separate issues so that we can track them.

**Comment by TheSpyder** [comment]
View -> Preview dialog has been fixed in preview 1 build 6.

**Comment by TheSpyder** [comment]
1, 2, 4 and 9 should be fixed as of Preview 3.

**Comment by blackcathikari** [comment]
Update: 5. should be fixed in TinyMCE 5 stable.

That just leaves 10!

**Comment by lostkeys** [comment]
The designer chimes in here. The focus style on the naked buttons are as designed as it's a button, not a form control. I understand the argument though, but we will keep it as designed for now. If you want the focus ring behavior it can be done by [making a custom skin](https://www.tiny.cloud/docs/advanced/creating-a-skin/) and changing the variables for `@button-naked-focus-***`
