### ISSUE TITLE
TinyMCE removed tags wordpress

### ISSUE THREAD

**Issue by vccreative** [tinymce/tinymce#4591]
Hi,

I've a problem with TInyMCE in Wordpress, When i try to add SOURCE CODE , TinyMCE remove auto some tags like span, i ,

Thanks
vCreative

**Comment by androb** [comment]
This occurs due to configuration and code in the WordPress integration of TinyMCE.  It is not a problem in TinyMCE itself. 
You can ask more about the WordPress issues at https://wordpress.org/support/
