### ISSUE TITLE
TinyMCE 5 Preview: A tabpanel cannot contain a panel

### ISSUE THREAD

**Issue by ryandemmer** [tinymce/tinymce#4592]
It appears that the TabPanel component in Tinymce 5 cannot contain a Panel component as an item.

See - https://codepen.io/anon/pen/ReaygL

Clicking the button to open the dialog gives the following error in the browser console:
``` javascript
Failed path: (dialog > body > branch: tabpanel > tabs > [1] > items > [0])
The chosen schema: "panel" did not exist in branches: {
  "alertbanner": [
    {},
    {},
    {},
    {},
    {}
  ],
  "button": [
    {},
    {},
    {},
    {}
  ],
  "checkbox": [
    {},
    {},
    {}
  ],
  "colorinput": [
    {},
    {},
    {}
  ],
  "colorpicker": [
    {},
    {},
    {}
  ],
  "dropzone": [
    {},
    {},
    {},
    {}
  ],
  "grid": [
    {},
    {},
    {}
  ],
  "iframe": [
    {},
    {},
    {},
    {},
    {}
  ],
  "input": [
    {},
    {},
    {}
  ],
  "selectbox": [
    {},
    {},
    {},
    {},
    {}
  ],
  "sizeinput": [
    {},
    {},
    {},
    {}
  ],
  "textarea": [
    {},
    {},
    {},
    {}
  ],
  "urlinput": [
    {},
    {},
    {},
    {}
  ],
  "customeditor": [
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "htmlpanel": [
    {},
    {}
  ],
  "imagetools": [
    {},
    {},
    {},
    {}
  ],
  "collection": [
    {},
    {},
    {},
    {}
  ]
}
```

The same is true if a Panel component is added as an item of a parent Panel component.

**Comment by EkimChau** [comment]
Thanks for reporting the issue ryandemmer, 

Did you intend to use a nested panel to help separate sections for complexed dialogs?

On a different topic, did you find the error message useful?  We hope the failure led you to the conclude that Panel was not supported fast.

will keep you posted :)

**Comment by ryandemmer** [comment]
> Did you intend to use a nested panel to help separate sections for complexed dialogs?

Yes. By adding classes to the panel config, it can be styled, or manipulated via the dom in postrender.

Also, the panel is described as similar to a <div> wrapper, so it stands to reason that it should be nestable.

> A Panel is a basic container, that holds other components, we can compose many components inside a panel. In HTML terms consider a panel a <div> wrapper.

**Comment by ryandemmer** [comment]
> On a different topic, did you find the error message useful? We hope the failure led you to the conclude that Panel was not supported fast.

A little confusing in the wording, but I it was apparent that the panel could not be used inside a tabpanel.
