### ISSUE TITLE
TinyMCE 5 Preview: inlite_selection_toolbar should be selection_toolbar in config

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4594]
**Do you want to request a *feature* or report a *bug*?**
Font color command is showing up in the selection toolbar even though it is not in the config

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/2160304/46488236-f26cec00-c7b6-11e8-8cc4-956a05645d25.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/tinymce/pen/79ec454375d41f576b3a9f687994570b?editors=0010

**What is the expected behavior?**
The toolbar reflects the config

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
V5 dev preview

**Comment by EkimChau** [comment]
Not a bug, in the example codepen, the 'textcolor' plugin was declared in the plugins config and works as expected.

**Comment by androb** [comment]
Yeah, I would think we would want to update this.

Switching to `inline_selection_toolbar` worked for now... but now I can't get quicklink on there.

**Comment by blackcathikari** [comment]
Update: In RC1 build 3 this is now called `quickbars_selection_toolbar` and the documentation has been updated. The default config has also been updated to remove forecolor.
