### ISSUE TITLE
Add custom tooltip option to the Formats button

### ISSUE THREAD

**Issue by steved-inova** [tinymce/tinymce#4596]
*feature request*

There is no tooltip option for the Formats toolbar button to which one can attach custom styles.  The referenced bug report was closed with the status that the tooltip contents would be the same as the button label, but I would like to explain what one might find in that menu via a tooltip.  In my case we have specified relative font sizes and we put those custom styles in the Formats menu, so for us the tooltip would state "Font Size".  Attached is a composite screen capture showing our Formats menu contents and the tooltip for the Font Family button.

Thank you.

![formats menu](https://user-images.githubusercontent.com/2686717/46491256-33c1c380-c7d8-11e8-9b8e-203687c33174.png)

#3064

**Comment by lostkeys** [comment]
Hi @steved-inova. We're reviewing old feature requests and your request seems to be for TinyMCE 4 which is now discontinued.
