### ISSUE TITLE
TinyMCE 5 kills page responsiveness on Chrome

### ISSUE THREAD

**Issue by doganmeh** [tinymce/tinymce#4597]
I added 8 inline editors to my page on Chrome and the page ended up being extremely slow. It would respond to page scrolling after a second if DOM was relatively empty but after about 3 seconds when DOM being busy with SVG graphics. All editors are empty. This was on just Chrome; Edge and Firefox were OK. 

I switched back to version 4.

**Comment by doganmeh** [comment]
and this was well after initialization.

**Comment by EkimChau** [comment]
Thanks for trying the developer preview and providing feedback.  Adding multiple editors should not impact the loading like this, we will look into the issue and keep you posted :)

**Comment by doganmeh** [comment]
Just to clarify: this was not during loading, but afterwards as well. I also had a lot of svg graphics on the page, which would make it a relatively busy DOM. Most other people would or would not notice. I don't know. But, one thing I am sure, there is definitely a performance degradation from version 4 to 5. Should be looked into..

**Comment by EkimChau** [comment]
Hi, i had a quick play adding 10 inline editors, each editor contained a 500kb <svg> embedded. (30,000 line html page) https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/car.svg

There was a slight difference between 10 empty editors vs 10 large sized svg embedded editors.
I didn't notice any scrolling issues after the page rendered.

Are you able to provide more detail on your setup?
 - maybe a zip with your html file with svgs
 - tinymce config

(I wasn't able to create a fiddle to show you my replication case due to file size limits on pens)

**Comment by doganmeh** [comment]
Here is my config:

{
 // selector           : "#mextarea",
 inline                : true,
 // theme              : "silver",
 // theme              : "inlite",
 plugins               : [
   'advlist autolink link image lists charmap print preview hr anchor pagebreak searchreplace ',
   'wordcount visualblocks visualchars fullscreen insertdatetime media nonbreaking',
   'save table directionality emoticons template paste textcolor save'
 ],
 menubar               : "edit view insert format table",
 browser_spellcheck    : true,
 // selection_toolbar : 'bold italic underline | h2 h3 | blockquote quicklink', // inlite theme only
 selection_toolbar     : false,
 contextmenu           : false,
 init_instance_callback: function (editor) {
   editor.on ('blur', function (e) {
     if (editor.isDirty ()) {
       editor.save ()
       editor.settings.save_onsavecallback (editor)
     }
   });
 },
 toolbar               : 'save undo redo | styleselect |' + // formatselect fontselect fontsizeselect
   ' alignleft aligncenter alignright alignjustify | bullist numlist outdent indent |' +
   ' link image | forecolor backcolor',
 // content_css       : '/static/text_area.css', // not needed in inline since page's css used
 style_formats         : [ // todo!: edit tinymce style formats
   {title: 'Bold text', inline: 'b'},
   {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
   {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
   {title: 'Example 1', inline: 'span', classes: 'example1'},
   {title: 'Example 2', inline: 'span', classes: 'example2'},
   {title: 'Table styles'},
   {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
 ]
}

There might be slight modifications I made between the two to make them work, e.g., the silver theme is in version 5 but not 4, etc. Unfortunately, I cannot put my page in public domain. Plus, even if I wanted to do it, it would be very hard since it is dynamically generated and depends on data from the server. I think it would be much easier to generate a test page with a busy dom. I had a lot of svg graphics on my page (not in the editors), the editors were blank.

**Comment by doganmeh** [comment]
Here is my config:

```
{
 // selector           : "#mextarea",
 inline                : true,
 // theme              : "silver",
 // theme              : "inlite",
 plugins               : [
   'advlist autolink link image lists charmap print preview hr anchor pagebreak searchreplace ',
   'wordcount visualblocks visualchars fullscreen insertdatetime media nonbreaking',
   'save table directionality emoticons template paste textcolor save'
 ],
 menubar               : "edit view insert format table",
 browser_spellcheck    : true,
 selection_toolbar     : false,
 contextmenu           : false,
 init_instance_callback: function (editor) {
   editor.on ('blur', function (e) {
     if (editor.isDirty ()) {
       editor.save ()
       editor.settings.save_onsavecallback (editor)
     }
   });
 },
 toolbar               : 'save undo redo | styleselect |' + // formatselect fontselect fontsizeselect
   ' alignleft aligncenter alignright alignjustify | bullist numlist outdent indent |' +
   ' link image | forecolor backcolor',
 style_formats         : [ // todo!: edit tinymce style formats
   {title: 'Bold text', inline: 'b'},
   {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
   {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
   {title: 'Example 1', inline: 'span', classes: 'example1'},
   {title: 'Example 2', inline: 'span', classes: 'example2'},
   {title: 'Table styles'},
   {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
 ]
}
```

There might be slight modifications I made between the two to make them work, e.g., the silver theme is in version 5 but not 4, etc. Unfortunately, I cannot put my page in public domain. Plus, even if I wanted to do it, it would be very hard since it is dynamically generated and depends on data from the server. I think it would be much easier to generate a test page with a busy dom. I had a lot of svg graphics on my page (not in the editors), the editors were blank.

**Comment by doganmeh** [comment]
Indeed, it seems good.
