### ISSUE TITLE
T5 question: Is it possible to use an image URL for a custom toolbar button?

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4604]
According to https://www.tiny.cloud/docs-preview/components/toolbarbuttons/component/basic/

It is only possible to set some sort of ID for an icon that "It displays the icon corresponding to the icon name that has been defined in the icon pack."

This appears difficult when prototyping... and I am not even sure what is in the current icon pack, or how I add to it?

In TinyMCE version 4, you could specify an `image` via a URL.
https://www.tiny.cloud/docs/advanced/creating-a-custom-button/

**Comment by TheSpyder** [comment]
The aim was to only support SVG icons in 5, there's an API to add icons to the pack in `editor.ui.registry` which I don't think is documented yet.

As a temporary workaround, in the dev preview we haven't locked down that icon ID field yet and if the name isn't in the pack we just load it verbatim into the button. So you could specify the ID as a full `img` tag linking to your URL.

This likely won't work by the time we release to stable, but it should be enough to prototype with for now?

**Comment by androb** [comment]
Thanks that worked for now

**Comment by toastbrotch** [comment]
seems not to work anymore with 5RC1? so what is the correct way? "image" does not seem to work also...

**Comment by TheSpyder** [comment]
It's not documented yet, but the `editor.ui.registry.addIcon(name, svgData)` API can be used to register custom icon IDs.

**Comment by EkimChau** [comment]
Api docs for addIcon is up
https://www.tiny.cloud/docs/api/tinymce.editor.ui/tinymce.editor.ui.registry/
