### ISSUE TITLE
T5 Preview: Selection toolbar does not latch/unlatch formatting options such as bold and italic

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4608]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The new selection bar option does not latch the Bold button when in bold content. Similar for italic.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Select some text
2. Selection toolbar appears
3. Apply bold
4. Bold button remains unlatched 

As experienced in:
https://codepen.io/tinymce/pen/79ec454375d41f576b3a9f687994570b

**What is the expected behavior?**
The Bold button should be latched when in bold content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version 5 Preview 1 build 6

**Comment by TheSpyder** [comment]
Clicking on the bold toolbar button, the selection bar bold flickers on and then off. Must be a bug in the event handler.

**Comment by blackcathikari** [comment]
This should be fixed in TinyMCE 5 stable. Please let us know if you find any further problems.
