### ISSUE TITLE
T5 Preview: List buttons are not latched

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4609]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
List buttons do not latch when they are in a list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. place the cursor in text
2. apply list

**What is the expected behavior?**
List button shows that you are in a list.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5 Preview 1 Build 6

**Comment by TheSpyder** [comment]
Does this happen with both list and advlist? We only have advlist enabled on most demos.

**Comment by TheSpyder** [comment]
Fixed in Preview 3
