### ISSUE TITLE
T5 Preview: Inlite toolbar takes precedence over Image Tools toolbar

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4610]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
1. Click on an image
2. Image tools should appear, but instead the selection toolbar appears

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

https://codepen.io/tinymce/pen/79ec454375d41f576b3a9f687994570b?editors=0010

Note that this appears to be a problem when selection toolbar is on as the regular demo seems to work (although the toolbar is not positioned correctly).

**What is the expected behavior?**
Image tools appear

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5 Preview 1 Build 6

**Comment by TheSpyder** [comment]
The inlite toolbar is taking precedence over everything. It should be last, not first.

**Comment by blackcathikari** [comment]
I believe this is fixed in RC1 build 1, from looking at your fiddle @androb. Could you please confirm that?
