### ISSUE TITLE
T5 Preview: Show Blocks doesn't display selected status

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4611]
**Do you want to request a *feature* or report a *bug*?**
Bug (MINOR)

**What is the current behavior?**
When selecting Show Blocks from the menu, blocks are successfully shown but the status is not reflected with a check mark.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/tinymce/pen/79ec454375d41f576b3a9f687994570b?editors=0010

**What is the expected behavior?**
When Show Blocks is active, there should be a check mark in the menu indicating its status

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
T5 Preview 2, Build 1

**Comment by TheSpyder** [comment]
Show invisible characters too.

**Comment by EkimChau** [comment]
This issue has been fixed in the latest developer preview version 5.0.0-preview-4-build.3
