### ISSUE TITLE
TinyMCE 5 Preview: Commands not available in menus and toolbars

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4614]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Some commands are not available in menus, and vice-a-versa.
They should be available in both.

**What is the expected behavior?**
Something that can be placed on the toolbar should be able to be added to the menus.

(I will update this list as I find them)

List of commands not available in menus:
`remove`
`rtl`
`ltr`
`indent`
`outdent`
`numlist`
`bullist`
`blockquote`
`h1`, `h2`, `h2`

List of commands not available on toolbars:
`codeformat`

**Comment by TheSpyder** [comment]
I'm not sure everything that is a menu item can be a toolbar button, we would need extra icons.

Whether we can add menu items is dependent on the complexity; for example the list buttons might be viable as menu items with the `list` plugin, but `advlist` with the split menu could turn into a lot of work.

Ideally yes everything would be available on both, I hope one day to create a single-registration API where items work anywhere but likely not until a later major release. Until then we'll have to make a best effort.
