### ISSUE TITLE
[V5-p2-b.2 ] removed_menuitems

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4615]
**bug**

See preview documentation option "removed_menuitems":
https://www.tiny.cloud/docs-preview/configure/editor-appearance/#removed_menuitems

But this option did not work.
Example:
`removed_menuitems: 'newdocument paste',
`

Result:
https://jsfiddle.net/6m8kzqju/40/

**Comment by blackcathikari** [comment]
I believe this is fixed in RC1 build 3. Please let us know if you find any further problems with it.
