### ISSUE TITLE
Tinymce v5 mobile seems to be broken

### ISSUE THREAD

**Issue by addy419** [tinymce/tinymce#4616]
Everything runs perfectly on desktop, but changing the view or opening the page on a mobile device gives error : 
`Uncaught TypeError: Cannot read property 'targetNode' of undefined
    at Object.renderUI (theme.min.js:1)
    at IC (tinymce.min.js:2)
    at Hx.<anonymous> (tinymce.min.js:2)
    at Array.<anonymous> (tinymce.min.js:2)
    at qt (tinymce.min.js:2)
    at o (tinymce.min.js:2)
    at tinymce.min.js:2
    at HTMLScriptElement.r.onload (tinymce.min.js:2)`.

Steps to Reproduce,
open [basic-example](https://www.tiny.cloud/docs-preview/demo/basic-example/),
change view from chrome console and Refresh OR open on mobile (Editor Disappears).

**Comment by TheSpyder** [comment]
The mobile UI is still under development while we're in developer preview, but it definitely shouldn't be throwing an error. Thanks for the report!

**Comment by TheSpyder** [comment]
The exception has been resolved in Preview 3, but the mobile theme still references the old font-based icons so mobile is basically unusable. Further updates are in progress.
