### ISSUE TITLE
[V5-p2-b.2 ] Custom format

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4617]
**bug**

Option "formats" seems to work.
But sub-option "customformat" is not displayed:

```
formats: {
    customformat: { inline: 'span', styles: { color: '#00ff00', fontSize: '20px' }, attributes: { title: 'My custom format' }, classes: 'example1' },
  }
```

see Your example:
https://www.tiny.cloud/docs-preview/demo/format-custom/

**Comment by TheSpyder** [comment]
This may be a documentation issue. TinyMCE 5 is operating the same way as TinyMCE 4:
https://www.tiny.cloud/docs/demo/format-custom/

Or is there a regression from an earlier release that I'm not aware of?
