### ISSUE TITLE
Toolbar at bottom Tinymce 5

### ISSUE THREAD

**Issue by addy419** [tinymce/tinymce#4618]
**Do you want to request a *feature* or report a *bug*?**
**Feature Request**
It would be convenient if there is a default option to shift the toolbar at the bottom.
Also, is it possible to shift a button to the right (Something like a comment button)?

**Comment by TheSpyder** [comment]
What do you mean by shifting a button to the right? Display on the far right of the toolbar separate to all the other buttons?

**Comment by addy419** [comment]
@TheSpyder Exactly a separate button for a specific purpose, like a submit button

**Comment by JYOTISHRAJ** [comment]
Sir, I have written a word like Facebook write  Something Thing, and here a lot of functions such as the color of the image has been made.

**Comment by androb** [comment]
Being able to emulate something like the Gmail Compose window would be ideal.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which added a new `toolbar_location` setting that can be used to set where the toolbar should be rendered. The valid values are `'top'` (default) or `'bottom'`. Here's a fiddle to show how to use the new setting/feature: http://fiddle.tinymce.com/8bhaab/1.

There is one issue we're aware of with the new feature when opening an inline dialog (eg search and replace) when sticky toolbars is also enabled. We'll include a fix for that in a future release. Please let us know if you have any further issues.

@addy419 also it seems this really contains 2 feature requests, so can I ask you create a new issue for the feature to float a button to the right side of the toolbar?

**Comment by laogui** [comment]
'toolbar_location' not work on mobile mode.
