### ISSUE TITLE
T5 Preview: cannot disable insert toolbar

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4626]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
insert_toolbar:false does nothing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/tinymce/pen/79ec454375d41f576b3a9f687994570b?editors=1010

**What is the expected behavior?**
insert_toolbar:false disables the Insert toolbar (which frankly needs a new design).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
T5P2B2

**Comment by TheSpyder** [comment]
Whether we redesign the toolbar is a topic for another day, and another release ;)

Much like #4594, the config has been renamed in the dev preview. It's currently `inlite_insert_toolbar`. Both will have to be reverted but that's tangential to the feature request.

This was never a documented feature of v4:
https://www.tiny.cloud/docs/configure/editor-appearance/#insert_toolbar

I can see why it works, but this would need to be a documentation change as well (and if we decide not to do it, we need to fix the bug where setting it to false shows an empty toolbar).

**Comment by androb** [comment]
Given how annoying the insert toolbar is right now, we should have a way to turn it off. In fact, IMHO it should be off by default until it has a better design.

An aside, but I would prefer we banish the word "inlite" to the outer edges of the galaxy where it's only use is in Vogon poetry. V5 seems like the right time to do it.

**Comment by TheSpyder** [comment]
I'm not going to argue product direction here :)

We'll consider supporting false as a value, but there will be a documentation cost.

**Comment by wonderbugtiny** [comment]
This feature has now been added in 5.0.3.
