### ISSUE TITLE
Formatting doesn't work if target element is in another document

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#4629]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When the target is an element in another document (e.g. inside an iframe), contentEditable is added and the toolbar renders, but formatting doesn't work. Instead, a new paragraph is inserted above the content.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Instructions are in the fiddle: http://fiddle.tinymce.com/m2gaab

**What is the expected behavior?**

The editor should function normally. I realize this is an edge case (albeit a useful one for inline editing) and that elements in other documents may or may not be supported. If this isnt' supported, I'd like to suggest adding a note [in the docs](https://www.tiny.cloud/docs/configure/integration-and-setup/#target). 🙂 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE edge. Affects at least Chrome, Firefox, and Safari.

**Comment by TheSpyder** [comment]
As far as I know this is not supported.

Why are you trying to do this with inline editing instead of using a non-inline editor which creates an iframe and controls it fully? Is it the dynamic toolbar you're after?

**Comment by claviska** [comment]
The use case is a CMS that renders a full copy of the page in an iframe for editing. In this case, the iframe acts as a sandbox for the inline editor.

Without this ability, TinyMCE has to be injected into the target page and accessed from the parent document. Injection has worked for years, but it would be much cleaner and prevent potential namespace conflicts to manage TinyMCE from the parent document.

**Comment by TheSpyder** [comment]
I understand. I'm not sure we'll get to this, but I understand what you're trying to do.
