### ISSUE TITLE
TinyMCE 5: Background color indicator bug

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4630]
The currently selected font background color indication is wrong. The #color element is always black and the icon background color is blend.

ps. the button/icon to reset color is not clear and at least should have a title.

**Comment by TheSpyder** [comment]
Yes, this was a last minute issue in the developer preview. There's also a new icon for background colour that hasn't made it through to the UI yet.

I will pass your feedback on the reset icon to our design team. Title and other accessibility features will be added before this is released, most likely during the beta stage.
