### ISSUE TITLE
Tinymce React ( Cannot read property 'unbind' of undefined)

### ISSUE THREAD

**Issue by Slasherio** [tinymce/tinymce#4634]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When i want to go to another page crash appears and error at console (see text)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
I can not reproduce it at fiddle because i need 2 or more pages.
I'll describe problem. 
1. I installed ```"@tinymce/tinymce-react": "^2.3.0",```

2.I wrote my own component following the documentation
```js
import React from "react";
import { connect } from "react-redux";

import { Editor } from "@tinymce/tinymce-react";

/**Actions */
import { editorOnChange } from "../../../actions";

class CKEditor extends React.Component {
  handleEditorChange = (content) => {
    const {
      id,
      editorOnChange,
      reducer: { actionType },
    } = this.props;
    editorOnChange(actionType, id, content);
  };

  render() {
    return (
      <Editor
        apiKey="8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0"
        init={{
          plugins:"powerpaste",
          toolbar:
            "formatselect | paste | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat | fontselect | fontsizeselect",
          font_formats:
            "Andale Mono=andale mono,times;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Comic Sans MS=comic sans ms,sans-serif;Courier New=courier new,courier;Helvetica=helvetica;Tahoma=tahoma,arial,helvetica,sans-serif;Terminal=terminal,monaco;Times New Roman=times new roman,times;Trebuchet MS=trebuchet ms,geneva;Verdana=verdana,geneva;Webdings=webdings;Wingdings=wingdings,zapf dingbats;Akzidenz-Grotesk Std=Akzidenz-Grotesk Std",
        }}
        value={this.props.value}
        onEditorChange={this.handleEditorChange}
      />
    );
  }
}

const mapDispatchToProps = {
  editorOnChange,
};

export default connect(
  null,
  mapDispatchToProps,
)(CKEditor);
```

I use this component at least at 3 different pages. When i'm load this component at first, it's all ok, no crashes, but when i  want to change page to another, where editor component is use too, i have a crash and error at console
```
Uncaught TypeError: Cannot read property 'unbind' of undefined
    at Yx.<anonymous> (tinymce.min.js?apiKey=8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0:76)
    at Jg.c.fire (tinymce.min.js?apiKey=8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0:8)
    at Yx.fire (tinymce.min.js?apiKey=8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0:8)
    at rp (tinymce.min.js?apiKey=8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0:8)
    at qx (tinymce.min.js?apiKey=8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0:8)
    at Yx.remove (tinymce.min.js?apiKey=8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0:8)
    at Object.remove (tinymce.min.js?apiKey=8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0:8)
    at Editor.componentWillUnmount (Editor.js:71)
    at callComponentWillUnmountWithTimer (react-dom.development.js:14280)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
```

**It only happens when there is plugins property available. If i remove it, everything works good**

**What is the expected behavior?**
Render a component.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version of Tiny - ```"@tinymce/tinymce-react": "^2.3.0",```
Browser - Google Chrome 
Version of browser - Version 69.0.3497.100 (Official Build) (64-bit)
Did this work in previous versions of TinyMCE? - I have not checked

**Comment by fyrkant** [comment]
No reason to open issues both here and on the wrapper component repo, let's talk about this on the other repo.

**Comment by fyrkant** [comment]
No reason to open issues both here and on the wrapper component repo, let's talk about this on the other repo.

**Comment by fyrkant** [comment]
Let's take this on the other repo.
