### ISSUE TITLE
Link or table popup breaks the page 4.7.x 4.8.x

### ISSUE THREAD

**Issue by marionldev** [tinymce/tinymce#4642]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
with tinymce 4.8.4, 4.7.13 and 4.7.1 
 when I insert a link ou I want to modify a table properties, I have following behaviour
1 - the popup appears with toolbar content instead of expected content
2- buttons of toolbar are somehow shuffled 
3- and my page get disabled by a opacity div id="mce-modal-block".  Nothing is clickable anymore
--> I loose all my data and have to reload page to get out of this
![image](https://user-images.githubusercontent.com/44428882/47416903-059c2780-d777-11e8-9f56-92b45255e0d3.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Tinymce toolbar with 2 lines
inline mode in a div
Link button and table button available
Click the link button to insert a new link

**What is the expected behavior?**
1- the popup appears with expected content clickable

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
reproduced in firefox 62 or Chrome 69
with angularjs 1.6.x
angular-ui-tinymce 0.0.19 
and tinymce 4.7.1 4.7.13, 4.8.3 and 4.8.4

**Comment by fyrkant** [comment]
I am unable to reproduce this, are you sure this is a problem with TinyMCE and not with the angular-ui-tinymce package?

**Comment by fyrkant** [comment]
Please create a fiddle showing this problem in TinyMCE without the angular-ui package.

**Comment by Afraithe** [comment]
Not enough info.
