### ISSUE TITLE
`visualchars_default_state` for setting `visualchars` by default

### ISSUE THREAD

**Issue by mat3e** [tinymce/tinymce#4643]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
There is no chance to set a default value for `visualchars`, while it is possible for `visualblocks` plugin.

**What is the expected behavior?**
It would be useful to have a new configuration property, like `visualblocks_default_state` for `visualblocks` plugin.

**Comment by lnewson** [comment]
The PR for this has been accepted and merged into master.
