### ISSUE TITLE
tinyMCE list and indent together do not work correctly?

### ISSUE THREAD

**Issue by ghoomi** [tinymce/tinymce#4645]
In tinyMCE lists and indent independently work fine but together do not work as per expectation.

Issues:

After applying list (number for example) right indent button became disabled.
If I indent first and apply list (number for example), again buttons became disabled, numbering is applied but it has spacing.
Any work around for this please ?

Please see these images for details:

https://i.stack.imgur.com/qBBy9.png
https://i.stack.imgur.com/goPbd.png

**Comment by fyrkant** [comment]
This is a known issue that is being worked on, we will have a new version of the lists plugin out soon.

**Comment by vecin2** [comment]
Any news on this one?

**Comment by SimonFc** [comment]
@vecin2 You're able to indent a single list item in 4.9.4 as well as in 5.0.9, does that solve your use case? The case with indenting the text within a list item, as shown in the first image ghoomi is linking to, will not be possible to do as there is be no way to differentiate between indenting a list and indenting text with padding.

**Comment by vecin2** [comment]
Ok, looks like we are still using TinyMCE 4.4.3

**Comment by SimonFc** [comment]
Awesome, I'll close this issue since it already has been solved.
