### ISSUE TITLE
TypeError: this.getDoc(...) is undefined[Learn More]  tiny_mce.js:14:26276

### ISSUE THREAD

**Issue by erakashpatel** [tinymce/tinymce#4646]
Hello Every one,

Need some help regrading MCE editor Joomla

When i open my article then edit is not working and given me 
TypeError: this.getDoc(...) is undefined[Learn More]  tiny_mce.js:14:26276 Error

MY Joomla version : 3.7.5
JCE Editor Version :  2.6.33 

Is there any solution for this or need to update my joomla to latest joomla?

Please suggest.

Thanks in advance.

Thanks
akash

**Comment by fyrkant** [comment]
This seems like an issue you should create on the[ Joomla repo](https://github.com/joomla), they can probably help you over there.
