### ISSUE TITLE
Latest version 4.8.4 has /*# sourceMappingURL=skin.min.css.map */

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#4649]
Small bug with version 4.8.4

In skin.min.css at the end there is /*# sourceMappingURL=skin.min.css.map */ and should be removed else the following error occurs
Source map error: request failed with status 404 

Same problem with skin.mobile.min.css /*# sourceMappingURL=skin.mobile.min.css.map */

**Comment by MGatner** [comment]
This is still true as of 5.0.16. Any plans to correct it? Adds unfortunate errors to console and Apache logs, or requires intervention in distribution files.

**Comment by lnewson** [comment]
This was fixed recently in TinyMCE 5.2.1 via https://github.com/tinymce/tinymce/issues/5489, so I'm going to go ahead and close this. Please do let us know if you're still having issues after upgrading and we'll reopen this.
