### ISSUE TITLE
Inline editing: elements are unable to inherit line-height from parents

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#4652]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In inline editing mode, the target element is unable to inherit its line-height from parent elements. This causes the line-height to "jump" when TinyMCE is initialized and results in an inconsistent appearance.

This is caused by [this rule](https://github.com/tinymce/tinymce/blob/master/src/skins/lightgray/main/less/desktop/Content.Inline.less#L8) in `Content.Inline.less`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Fiddle: http://fiddle.tinymce.com/X2gaab/2

**What is the expected behavior?**

The line-height should be consistent before and after TinyMCE is initialized.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest / all

**Comment by fyrkant** [comment]
You can add your own content_style changing this:
http://fiddle.tinymce.com/X2gaab/3
