### ISSUE TITLE
Insert/Edit Image function hardly working on mobile

### ISSUE THREAD

**Issue by bendamschke** [tinymce/tinymce#4656]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Insert/Edit Image's 'Browse for an image' button rarely shows the File Upload dialog to select an image on mobile. 9/10 times nothing will occur.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Add the image plugin to your TinyMCE init script
2. Tap the 'Browse for an image' button 

**What is the expected behavior?**
File Upload dialog to display upon tapping the 'Browse for an image' button

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: TinyMCE 4.8.2
Browser: Firefox, Chrome
OS: Android
Did this work in previous versions of TinyMCE? Not sure.

**Comment by MasterSteelblade** [comment]
Can confirm identical behaviour my side. TinyMCE 5 fixes this in the sense that the mobile interface takes over, but the mobile interface is just completely incompatible with the kind of site I'm building. Tried multiple versions of TinyMCE v4, none worked.

**Comment by akagane99** [comment]
I'm having the same problem. Is there any solution?
