### ISSUE TITLE
Table cells are selected but copy/paste does not work

### ISSUE THREAD

**Issue by hxnam0509** [tinymce/tinymce#4657]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
- Select many cells (highlight cells without highlighting text in those cell)
- Copy (via shortcut or menu)
- Put cursor in somewhere else, paste (via shortcut or menu)

Pasted content is not the content I want to copy

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Here is the demo : https://youtu.be/4VXFIpQnwGQ

**What is the expected behavior?**
Be able to copy/paste table cells

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Discovered since tinymce 4.7.11. Haven't tested older version of tinymce.
MacOS : happens on Chrome and Safari, not on Firefox

**Comment by hxnam0509** [comment]
I reported this bug to a Tiny's staff several months ago, it might be tracked under an internal ticket :
TINY-1789: Copy paste table cells without inner text selection, will copy nothing

**Comment by ashfordneil** [comment]
That internal ticket has been completed, and I'm unable to reproduce this issue now on the latest release of Tiny 5. Please reopen this ticket (or create a new ticket) if you notice similar behaviour again.
