### ISSUE TITLE
Circular dependency warnings on build

### ISSUE THREAD

**Issue by vaandr** [tinymce/tinymce#4659]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Circular dependency: lib\core\main\ts\caret\CaretFinder.js -> lib\core\main\ts\caret\CaretUtils.js -> lib\core\main\ts\caret\FakeCaret.js -> lib\core\main\ts\keyboard\TableNavigation.js -> lib\core\main\ts\caret\CaretFinder.js
Circular dependency: lib\core\main\ts\caret\CaretUtils.js -> lib\core\main\ts\caret\FakeCaret.js -> lib\core\main\ts\keyboard\TableNavigation.js -> lib\core\main\ts\keyboard\CefUtils.js -> lib\core\main\ts\caret\CaretUtils.js
Circular dependency: lib\core\main\ts\caret\CaretUtils.js -> lib\core\main\ts\caret\FakeCaret.js -> lib\core\main\ts\keyboard\TableNavigation.js -> lib\core\main\ts\caret\LineReader.js -> lib\core\main\ts\caret\CaretWalker.js -> lib\core\main\ts\caret\CaretUtils.js
Circular dependency: lib\core\main\ts\caret\CaretFinder.js -> lib\core\main\ts\caret\CaretUtils.js -> lib\core\main\ts\caret\FakeCaret.js -> lib\core\main\ts\keyboard\TableNavigation.js -> lib\core\main\ts\caret\LineReader.js -> lib\core\main\ts\caret\CaretFinder.js
Circular dependency: lib\core\main\ts\caret\CaretUtils.js -> lib\core\main\ts\caret\FakeCaret.js -> lib\core\main\ts\keyboard\TableNavigation.js -> lib\core\main\ts\caret\LineReader.js -> lib\core\main\ts\caret\CaretUtils.js

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

No circular dependencies.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.8.5, 1e0bda2

Kind Regards,
Ves.

**Comment by spocke** [comment]
This is now fixed. Thanks for reporting this issue.
