### ISSUE TITLE
Does the insert confirm has some callback?

### ISSUE THREAD

**Issue by HShao0130** [tinymce/tinymce#4661]
use the 'images_upload_handler' to upload a image, when success and get the response, i need to get the image url that i confirm.

**Comment by spocke** [comment]
Not sure what you mean the image_upload_handler is meant to be an async upload not a manual verification step of images.

**Comment by HShao0130** [comment]
> Not sure what you mean the image_upload_handler is meant to be an async upload not a manual verification step of images.

Maybe I didn’t express it clearly.I just mean this confirm button.
![pic](https://user-images.githubusercontent.com/23205753/48108659-f04af100-e27e-11e8-9a22-31d0b1e83275.png)

**Comment by spocke** [comment]
Right yeah there is no support for getting or confirming that before the dialog gets closed.

**Comment by HShao0130** [comment]
> Right yeah there is no support for getting or confirming that before the dialog gets closed.

ok, thanks a lot
