### ISSUE TITLE
settings.allow_html_data_urls is not passed to SaxParser

### ISSUE THREAD

**Issue by hxnam0509** [tinymce/tinymce#4669]
https://github.com/tinymce/tinymce/blob/c7c016fa875b47ba58121f01062ef55fc0963201/src/core/main/ts/api/html/DomParser.ts#L427

Inside SaxParser (https://github.com/tinymce/tinymce/blob/master/src/core/main/ts/api/html/SaxParser.ts) there is a check for `settings.allow_html_data_urls` and `settings.allow_svg_data_urls`. However those setting are not either passed from DomParser or assigned a default value from inside SaxParser. Their value is always `undefined`.
Not sure if this is implemented on purpose

**Comment by spocke** [comment]
Those options is not documented but it seem that you are correct that they are not passed though correctly.
