### ISSUE TITLE
Style format for inappropriate selector

### ISSUE THREAD

**Issue by DebuggeR94** [tinymce/tinymce#4671]
**Do you want to request a *feature* or report a *bug*?**
Bug (unpredictable behavior)

**What is the current behavior?**
Read 'steps to reproduce'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1) Open this [TinyMCE Fiddle](http://fiddle.tinymce.com/U3gaab)
3) Write some text
4) Set format for paragraph (Card->Text from Formats dropdown)
5) Go to a new line and add Heading
3) Check source code (h* class)

As a result, we have a heading with a format/class not intended for it. We cannot remove it using Formats dropdown, since the 'p' selector is specified for this format.

**What is the expected behavior?**
Remove format from element if he do not match with format selector.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.8.5 and TinyMCE 5-dev, Firefox 63.0.1

**Comment by spocke** [comment]
It will by default copy style and class attributes for blocks on enter this can be disabled using the https://www.tiny.cloud/docs/configure/content-filtering/#keep_styles option.
