### ISSUE TITLE
does't work after pjax reload

### ISSUE THREAD

**Issue by rustamwin** [tinymce/tinymce#4678]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by Afraithe** [comment]
No examples, no info, closing issue.
