### ISSUE TITLE
Error non flat package structure detected

### ISSUE THREAD

**Issue by skyzluo** [tinymce/tinymce#4691]
I just git clone the master branch. I tried to install it by following the installation instruction in readme.md. However, when I typed "grunt", the system prompts: 
Warning: Error non flat package structure detected:
 importer: /var/www/tinymce/tinymce/node_modules/@ephox/alloy/lib/main/ts/ephox/alloy/api/behaviour/Behaviour.js
 importee: @ephox/boulder
 resolved: /var/www/tinymce/tinymce/node_modules/@ephox/alloy/node_modules/@ephox/boulder/lib/main/ts/ephox/boulder/api/Main.js Use --force to continue.

Does tinymce have Circular dependency?

I am running in Ubuntu 18.04

**Comment by TheSpyder** [comment]
That error is not regarding circular dependencies, it's an attempt to avoid accidentally nesting our `@ephox` dependencies which would just add code bloat. There is a `postinstall` script that is intended to remove the offending modules for the moment, did that not run for you?

**Comment by skyzluo** [comment]
Yes. I think the postinstall script is not running for me. Is it in Gruntfile.js? How could I solve this problem? Thanks

**Comment by TheSpyder** [comment]
It's just a standard npm script that should be run when you install the NPM packages, whether through `npm` or `yarn`. I'm not sure why it wouldn't be running 🤔 

You could manually run it, using `npm run postinstall`, but that shouldn't be necessary 🤔
