### ISSUE TITLE
TinyMce figure, figcaption and paragraph

### ISSUE THREAD

**Issue by fwitkowski** [tinymce/tinymce#4693]
I have custom code that adds figure with figcaption in TinyMce (version 4):

```
<figure><img src="IMAGE_SRC" />
<figcaption>CAPTION</figcaption>
</figure>
```
When that figure tag is last element, user is not able to add new paragraph. When editing last line, the user is inside figure » figcaption, and when clicking ENTER key, new line of is added. Instead of that, I want to add new

when clicked enter key.

**Comment by trevorjay** [comment]
Doing some testing it looks like this behaviour was changed/fixed in 4.9.2/5.0.0. You can now escape the figcaption context using the down cursor key. I'm closing this issue. Anyone still experiencing this, please let us know and we'll reopen it.
