### ISSUE TITLE
4.9.1: Spacebar not working properly on android

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#4695]
The bug with spacebar was already reported and fixed with https://github.com/tinymce/tinymce/issues/4685 but its still exists on android for version 4.9.1.

**Comment by miketemby** [comment]
Issue still exists on using Chrome and Safari desktop too using 4.9.1 (from cdn), but appears to be more specific now. 
First line typed has no problems but once I return, adding a break into the string, the second line space characters do not work. It isn't isolated to Android. 

![image](https://user-images.githubusercontent.com/41090032/49974536-f6bf3d80-ff8d-11e8-83e7-d686293fcf58.png)

**Comment by jasonfah** [comment]
4.9.2 also still broken.

http://fiddle.tinymce.com/G6gaab

Steps to replicate: (chrome)

enter the text 'test:' then press ENTER
enter the text 'test' then press ENTER
enter the text 'test' then press SPACEBAR
note that nothing happens...

**Comment by arnaudbey** [comment]
same problem here on Chromium v71.0.3578.98 (spaces are ok on the first 2 lines but not on the third one)

**Comment by Nickproger** [comment]
I tested on different version:
fixed on 4.9.3 and on 5.0.0

**Comment by Daijobou** [comment]
When fixed, so I close this ticket.
