### ISSUE TITLE
Everyone can overwrite fiddles

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#4697]
Here https://www.tiny.cloud/docs-3x/howto/words/ link to http://fiddle.tinymce.com/l1baab
Everyone can edit and save it. That should not be possible. I think the original example is here long time overwritten? "Save" should create a new URL like jsfiddle.net do and not overwrite exists. For testing code is "Run".

After press "Reset" button you only get a blank formular and I found no way to get back the default code example. "Reset" should place the default code example in formular.

**Comment by Afraithe** [comment]
Removed save function, saving was removed on the "formal" examples, just not all of them.

We have some other updates on the fiddle website coming, will try to get so that reset goes to default example.
