### ISSUE TITLE
How to hook up custom filebrowser?

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#4698]
Hi there
How do I hook up our custom filebrowser? It seems to me that in init "file_browser_callback" wont work any more, therefore "file_picker_callback" should do the job.
In v4
```
tinymce.activeEditor.windowManager.open(
{
title: 'Filebrowser',
url : "filebrowser.html",
width : 800,
height : 600,
inline : 1,
...
```
ran perfectly, but in v5 windowManager.open() acts differently. How do I open a windows with external html in v5?
Best regards
manu

**Comment by TheSpyder** [comment]
TinyMCE 5 no longer supports dialogs as HTML pages. The API is much more restricted:
https://www.tiny.cloud/docs-beta/ui-components/dialog/#dialogconfigurationframework
