### ISSUE TITLE
Use tinymce 5.0 beta for development

### ISSUE THREAD

**Issue by ayanbora1994** [tinymce/tinymce#4699]
I can't seem to find a developer package for tinyMCE 5. Is there any right now?

**Comment by TheSpyder** [comment]
We don't have a developer download available, just the minified release, but you can create a development build by following the build instructions after doing a git checkout of the `5.x` branch - these are the same instructions as they were for TinyMCE 4, specifically `grunt dev` will create just the development JS file you need.
https://github.com/tinymce/tinymce/tree/5.x#building-tinymce

Once version 5 is released to stable it will be available in the usual channels and development variants, but we aren't doing that for beta.

**Comment by ayan-bora** [comment]
Hi, is there a way to import it using module loaders in this version? I want something like 
`import tinymce from 'tinymce'` and then use this tinymce instance.
