### ISSUE TITLE
The formatselect dropdown does not have tooltip

### ISSUE THREAD

**Issue by sushan05** [tinymce/tinymce#4700]
Hi There,
The **formatselect** dropdown does not have tooltip; while,  **fontselect** & **fontsizeselect** dropdown do have tooltip.
please check the link - https://codepen.io/sushan/pen/mayNeX

**Comment by tinydylan** [comment]
Hi,

Thanks for reporting this issue. I can reproduce the issue in the codepen you linked to. This issue has been corrected in TinyMCE 5. You can see the behaviour in [this demo page](https://www.tiny.cloud/docs/demo/full-featured/).

Thanks!
