### ISSUE TITLE
Location of LESS skin files in 5.0-beta

### ISSUE THREAD

**Issue by ayanbora1994** [tinymce/tinymce#4707]
In 4.9.x I could easily customize the default desktop skin by changing some less files using the path _skins>lightgray>main>less>desktop_ (eg Icons.less, variables.less), but in 5.0, I am not being able to find the less files that control the behavior of the styles on desktop. I understand that there is no explicit desktop skin in 5.0, so I went to _skins/oxide/main/less/mobile_ but I could only find the mobile styles there. Is there something I am missing here?

**Comment by TheSpyder** [comment]
In TinyMCE 5 we've moved the primary skin into a separate repository, as an NPM dependency, to better allow for skin development disconnected from the editor:
https://github.com/ephox/oxide

For the moment to make a custom skin you would need to use the oxide project. It has demos showing some of the customisation options, but we don't have a nice skin builder tool yet.

We are considering moving to a monorepo style project, however, so in the future it may once again be easy to make minor changes and rebuild in the tinymce project.

**Comment by ayanbora1994** [comment]
Hi! The link you provided does not seem to work. It gives a 404 Error. Could you please send me another link?
