### ISSUE TITLE
Version 5: After inserting column(:) into content, enter no longer works

### ISSUE THREAD

**Issue by hnategh** [tinymce/tinymce#4708]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
After inserting column (:) the new line by enter no longer works. the cursor stocks after char : and in some cases Insert Symbol gets opened. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Type char : then try to enter to make new line.
**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?** Version 5.0.0-beta-1-build.3-9

**Comment by lnewson** [comment]
This should be fixed in the latest release candidate. If you can still reproduce it on in RC1, please let us know and we'll investigate further.

**Comment by hnategh** [comment]
I can confirm that doesn't happen anymore. Thank You!
