### ISSUE TITLE
Toolbar at bottom Tinymce 4

### ISSUE THREAD

**Issue by CarlGalloy** [tinymce/tinymce#4710]
Hi
I have a simple question . i can't find it in Doc
I want my toolbar going to bottom of editor? in TinyMCE 4
I search on google and found this [LINK](https://stackoverflow.com/questions/19346818/tinymce-toolbar-location-at-bottom-of-editor) on stackoverflow, but it's about old version ..not version 4.

**Comment by lostkeys** [comment]
Sorry for the late reply. This is not supported in TinyMCE 4. We are looking at reintroducing it in TinyMCE 5 but we cannot give a definite answer if/when yet.
