### ISSUE TITLE
Version 3.x - Selecting image in Firefox 64 not possible

### ISSUE THREAD

**Issue by barbarareiner** [tinymce/tinymce#4714]
For now I'm stuck with version 3 of tinymce (planning to upgrade directly to 5 when released). Since upgrading Firefox to Firefox 64.0 yesterday, it is not possible to select an image or to resize it anymore. Both the fixes I found for a similar behaviour in Chrome 58 don't work for this new problem.

**Comment by ZiTAL** [comment]
same here

**Comment by mickasan** [comment]
Hello, I'm on this old version of tinyMCE :
https://github.com/tinymce/tinymce/tree/3.x/jscripts/tiny_mce
 and i have the same problem, i cant easily upgrade tinyMCE,
Do you have any solutions ?

**Comment by ZiTAL** [comment]
no, check out: https://bugzilla.mozilla.org/show_bug.cgi?id=1516268

**Comment by lnewson** [comment]
Hi,

I'm sorry but TinyMCE 3.x is no longer a supported version and as such I'm going to close this. Please do let us know if you are experiencing issues when using the latest version of TinyMCE 4 or 5.

Thanks!
