### ISSUE TITLE
TinyMCE 5: Some small issues

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4717]
1. Help > Plugins - strange scrollbars
2. Word count - table misalignment
3. Misaligned "constrain proportions" button in image/media dialog
4. If I switch to Fullscreen mode using the menu it would be good so I can go back with some "Close" button in the toolbar, without going to the menu again. Maybe.
5. In menus the right-arrow icon is too close to the text, e.g. in Format > Format menu.
6. Emoticons dialog "jumps" when I select any tab.

**Comment by lnewson** [comment]
Thanks for the report!

1) We've reworked and made a few fixes to the help plugins tab recently, so is this still an issue? If so, could you elaborate a bit more on what the scrollbar issue is?
2) Seems to be a browser specific bug, if you're referring to the table not stretching to the width of the dialog? Anyways, we've logged an issue with the design team to get this fixed.
3) This is another browser specific bug it would seem, so logged another design issue.
4) There is a toolbar button you can use that's a toggle button, would this work for you? Here's an example: http://fiddle.tinymce.com/X7gaab
5) I can replicate this on all browsers, so will log a design issue for this.
6) What browser and/or configuration are you using, when you see the dialog jump?

**Comment by alecpl** [comment]
Firefox 64.

1. Confirmed fixed.
2. Yes.
3. Now I don't see the element at all. Instead there's horizontal scrollbar in this dialog.
4. My point is that if you have no "fullscreen" toolbar button and you use View > Fullscreen menu, you end up with no quick way to go back, but this is very small issue.
5. In Firefox and Chrome. In Chrome additionally the arrow is misaligned. Especially visible on Format > Formats > Alignment item.
6. Firefox. I see this might be because there's no scrollbar in "All" tab, but it appears in other tabs. In Chrome the scrollbar is always there.

New issues:
7. Loading image never disappears on https://www.tiny.cloud/beta/.
8. Dialogs out of screen. E.g. Help dialog does not scale height on small height screen.
9. Console error: "No representation for toolbarItem: crop" in theme.min.js:1:317600, when clicking an image.

**Comment by toastbrotch** [comment]
9. with rc2 its still there: "representation for toolbarItem: crop tinymce.min.js:4:316872" bug or config problem?

**Comment by lnewson** [comment]
Here's an update on where things should be at with this, as of 5.0.0-rc-2-build.14 (the latest version available on 5-testing):

2. This should be fixed now.
3. Still a known issue, but it is being investigated.
4. This sounds like a feature request as v4 didn't have this either, so could I ask that you log a separate issue for this?
5. This should be fixed I believe.
6. I can replicate this in Firefox, so have logged an issue to look into it.
7. This should be fixed.
8. Still an issue. I believe this maybe an issue with the height calculations for the tab panel, which tries to set the height based on the largest tab.
9. Should be fixed now, as this was a configuration issue in the default imagetools context toolbar settings.

**Comment by alecpl** [comment]
Here's what's left (with some upates):
3. "Constrain proportions" button hidden (out of dialog, horizontal scrollbar) in Firefox.
6. Emoticons dialog "jumps" when I select any tab in Firefox.
8. Some dialogs out of screen. E.g. Help dialog does not scale height on small height screen. Generally a Firefox issue, but there's also some style issue in Chrome.

**Comment by lnewson** [comment]
Okay, as of 5.0.0-rc-2-build.22 (available on 5-dev) I believe point 6 & 8 should now be resolved as well, which should only leave the third point left. @alecpl can you confirm?

**Comment by alecpl** [comment]
I can only test with https://www.tiny.cloud/rc/ at the moment and these aren't fixed there.

**Comment by lnewson** [comment]
No worries, I'll let you know when it's live on that page.

**Comment by lnewson** [comment]
5.0.0-rc-2-build.22 is now live on https://www.tiny.cloud/rc/, so you should be able to test now :)

**Comment by TheSpyder** [comment]
Great! We're tracking the sizeinput issue in #4751 so I'll close this now.

**Comment by blmcc-eph** [comment]
hey @alecpl -- Congratulations! This issue has been selected as one of the three most helpful issues in our TinyMCE 5 Developer Challenge. Please contact me at blake [at] tiny [dot] cloud so we can get you your gift card. And on behalf of everyone at Tiny, thanks for your support of TinyMCE 5.
