### ISSUE TITLE
Issue with "file_picker_callback" & "video_template_callback"

### ISSUE THREAD

**Issue by Cryde** [tinymce/tinymce#4718]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When I upload a video (in "file_picker_callback") and generate a poster from it, I want pass all the paths (video & poster) for "video_template_callback"    
For now only the video path is set in "video_template_callback" ("poster" field in "Advanced" tab is empty in the editor)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://jsfiddle.net/z1myL02e/
I've simulate a call with setTimeout and call the callback from "file_picker_callback" ```cb('video.mp4', {poster: 'poster.png'});``` (line 46)

To reproduce : 
1. click on the media button of the editor
2. submit any file 
3. wait 3 seconds 
4. "source" field should contains "video.mp4"
5. "poster" field in "Advanced" tab is empty

**What is the expected behavior?**
"poster" field in "Advanced" tab should contains "poster.png"

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I have tried with version 4.(7,8,9) of tinymce but it's the same issue

**Comment by Cryde** [comment]
I have test with version 4.4.3 http://fiddle.tinymce.com/Z6gaab and it worked.
Seems a regression to me :thinking:  (version after 4.4.3 didn't worked)

**Comment by Cryde** [comment]
I'm also wondering why can you use the poster image if it is present instead of transparent image ? 
https://github.com/tinymce/tinymce/blob/master/src/plugins/media/main/ts/core/Nodes.ts#L30

**Comment by LiuCao** [comment]
I have the same problem as you.

**Comment by chrispcb** [comment]
Same problem with "width" and "height" values.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue.  The `file_picker_callback` will now currently update the poster, etc... fields when provided. Please let us know if you have any further issues.
