### ISSUE TITLE
Space doesn't work after SHIFT-Enter

### ISSUE THREAD

**Issue by freitasm** [tinymce/tinymce#4728]
This has been reported to myself today:

1) Type something.
2) SHIFT + Enter - type more.
3) SHIFT + Enter - type more, note you can't space at this point.

I can reproduce with Chrome (Windows), reporting was from Chrome (Linux) and Chrome (ChromeOS).

Cheers

**Comment by jasonfah** [comment]
Not just shift + enter. There's a few scenarios that cause it.

See #4685 and #4695

**Comment by YohannBethoule** [comment]
Hello, 

I've got the same problem with tinymce 5. 
I saw in the issues #4685 and #4695 that you planned to deploy a fix on the 4.9 version, was it fixed ? And do you plan to quickly fix it on tinymce 5 too ? 

Thanks 😃

**Comment by Nickproger** [comment]
I tested on different version:
fixed on 4.9.3 and on 5.0.0

**Comment by freitasm** [comment]
That's correct. Deployed Cloud 5.0 yesterday and users reported as fixed.
