### ISSUE TITLE
code plugin shows longer text if a non-editable text is selected

### ISSUE THREAD

**Issue by endredy** [tinymce/tinymce#4731]
Bug report

a bug with noneditable + code plugins: if a non-editable text is selected, it is concatenated to the end of the source code in the code plugin dialog.
Tested with 4.9.2-4.8.2, ff and ch

context: a spec string is converted into non-editable (readonly text)

demo: http://fiddle.tinymce.com/M7gaab

steps to reproduce:
1. click on the non-editable text (it'll be highlighted with blue border)
2. click on code plugin
3. source code contains: (selected text is concatenated to the end of the text)
```html
 <p>bla bla you-know-who bla bla</p>
 <p>you-know-who</p>
```
 instead of
```html
 <p>bla bla you-know-who bla bla</p>
```

A quick fix: if i replace "valid_elements" with "extended_valid_elements" (in init), it works.

**Comment by lnewson** [comment]
This issue was fixed in 4.9.3. I've verified that I'm no longer able to replicate this using the above steps in both 4.9.3 and 5.0.0. Please let us know if you find any further problems!
