### ISSUE TITLE
Issue with uploaded images

### ISSUE THREAD

**Issue by cmoreau** [tinymce/tinymce#4734]
Hey there!

I found an issue when I upload a new image. Indeed, when I upload the image attached, their dimensions are updated without keeping the same scale. Then, I have an image with poor scale and quality...
![screen-shot-2019-01-07-at-15 12 18-0533236001546871062-1796322577](https://user-images.githubusercontent.com/7290431/50776277-dc306980-1298-11e9-8597-69b3bfe28469.png)

Am I the only one who detected this behavior?
I'm using the beta version - Version 5.0.0-preview-5 (TBD)

Thanks,
Cyrille.

**Comment by fyrkant** [comment]
What does this have to do with Tinymce?

**Comment by lnewson** [comment]
Closing due to lack of information. If you can add the details asked for above, then we're more than happy to reopen this issue.
