### ISSUE TITLE
Pagebreak can not be deleted

### ISSUE THREAD

**Issue by thopark** [tinymce/tinymce#4738]
Reporting a *bug*

Current behavior:
When inserting a pagebreak and navigating to the beginning of the next paragraph you can not delete the pagebreak by pressing backspace (twice).

Try here:
https://codepen.io/dsakko/pen/jAxgpO

Expected behavior:
Pressing Backspace at the beginning of the paragraph following the pagebreak removes the pagebreak.

TinyMVE Version 4.9.0
Browser: Chrome 71

**Comment by lnewson** [comment]
This should now be fixed in 5.0.2. Please let us know if you find any further problems!
