### ISSUE TITLE
Specify default classes for elements

### ISSUE THREAD

**Issue by Lufog-git** [tinymce/tinymce#4739]
**Do you want to request a *feature* or report a *bug*?**
question

Is it possible to specify default classes for elements? 
For example:
1) It is necessary that the class "card-text" be added to each paragraph by default.
2) But it must also remain an opportunity not to use this class intentionally.

The parameter extended_valid_elements allows you to solve the first problem, but not the second. Since it enforces the specified classes for all elements.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5

**Comment by fyrkant** [comment]
This is not a support forum, visit our docs or community to get answers like this.
https://community.tiny.cloud/
