### ISSUE TITLE
Shortcut with function keys don't work

### ISSUE THREAD

**Issue by speedyhoon** [tinymce/tinymce#4740]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
Creating a new shortcut with most Function keys don't work. It's generating the wrong charCode/keyCodes for "f4" returning  charCode for "f" instead
editor.shortcuts.add(f4', 'superscript', 'superscript');
However using "ctrl+f10" does work
editor.shortcuts.add('ctrl+f10', 'subscript', 'subscript');

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/N8gaab

**What is the expected behavior?**
Specifying a shortcut sequence should work.

**Which versions of TinyMCE, and which browser / OS are affected by this issue?** All browsers & OS
**Did this work in previous versions of TinyMCE?** No

**Comment by fyrkant** [comment]
Hmm, seems like "translations" from f keys to keycodes are only added for f9-11, see this code: https://github.com/tinymce/tinymce/blob/79fc920232e76cadbe410ae51b9a6cae4a57c8b3/src/core/main/ts/api/Shortcuts.ts#L24-L28

We maybe should add some more f key "translations" but for now you can use the keycode directly instead (http://keycode.info/ is an easy way to find out the keycode, 115 for F4) in your shortcut, like this: http://fiddle.tinymce.com/N8gaab/1

**Comment by lnewson** [comment]
This issue should be fixed in 4.9.3 and 5.0.0. Please let us know if you find any further problems!
