### ISSUE TITLE
fontsize_formats option cannot filter unintended space

### ISSUE THREAD

**Issue by ohjihwan-nbt** [tinymce/tinymce#4741]
**Do you want to request a *feature* or report a *bug*?**
it's not a bug. I think it just an improve function

**What is the current behavior?**
![Image of current behavior](http://fureweb.com/20190109-tinymce-fontsize_formats_matter.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
- I think this can be replaced by above image.

**What is the expected behavior?**
![Image of expected behavior](http://fureweb.com/20190109-tinymce-fontsize_formats_matter-after.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- 4.9.2 / Not related to browser and OS / Yes

**Comment by fyrkant** [comment]
I don't think this is a bug, but a faulty usage.

**Comment by ohjihwan-nbt** [comment]
I know this is a misuse. But I still think that this can help a little more convenient use, and that's why I wrote this issue.
