### ISSUE TITLE
How can i change color of tinymce textarea?

### ISSUE THREAD

**Issue by theaterwinner** [tinymce/tinymce#4745]
hello~! I am huge fan of tinymce!

i have a question while using tinymce.

i use django-tinymce-4-lite in my web and

i wanna know how can i cange color of tinymce text area.

How can i change color of tinymce textarea?

i have my configuration of tinymce in my settings.py

thank you in advance. 

TINYMCE_DEFAULT_CONFIG = {
# 'width': "auto",
# 'height': "500",
# 'selector': "textarea",
# 'theme': "modern",
# 'paste_data_images': True,
# 'plugins': [
# "advlist autolink lists link image charmap print preview hr anchor pagebreak",
# "searchreplace wordcount visualblocks visualchars code fullscreen",
# "insertdatetime media nonbreaking save table contextmenu directionality",
# "emoticons template paste textcolor colorpicker textpattern"
# ],
# 'toolbar1': "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
# 'toolbar2': "print preview media | forecolor backcolor emoticons",
# 'image_advtab': True,

'width': "auto",
'height': "350",
'selector': "textarea",
'theme': "modern",
'paste_data_images': True,
'plugins': [
    "advlist autolink lists link  charmap print preview hr anchor pagebreak",
    "searchreplace wordcount visualblocks visualchars code fullscreen",
    "insertdatetime media nonbreaking save table contextmenu directionality",
    "emoticons template paste textcolor colorpicker textpattern"
],
'toolbar1': "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link ",
'toolbar2': "print preview media | forecolor backcolor emoticons",
'image_advtab': True,
}

**Comment by Afraithe** [comment]
This is not a support forum, visit our docs or community to get answers like this.
https://community.tiny.cloud/
