### ISSUE TITLE
‘tinymce.activeEditor.theme.panel’ is not accessible on the mobile

### ISSUE THREAD

**Issue by charlesr1971** [tinymce/tinymce#4747]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

‘tinymce.activeEditor.theme.panel’ is not accessible on the mobile. 
After trying:

editor.on(‘focus’,...

This object equates to null. 

On desktop browser I can use this object to access individual toolbar items, so that I can enable & disable buttons. 

I would like to be able to access the button control state on the mobile, giving users an equivalent experience. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Use the following code to reproduce this behaviour:

editor.on('focus', (event) => {
const toolbarItems = tinymce.activeEditor.theme && tinymce.activeEditor.theme.panel ? tinymce.activeEditor.theme.panel.find('toolbar *') : null;
console.log(toolbarItems);
})

On a mobile the console will log 'null'

**What is the expected behavior?**

The console should log an object which is an array of all the toolbar buttons

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.9.2

**Comment by charlesr1971** [comment]
By the way guys, the mobile theme is really great, and I have integrated & tested it successfully. It is just this one issue which is causing problems. Thanks...

**Comment by charlesr1971** [comment]
I am using iOS12 [all browsers] & TinyMCE config of:

mobile: {
    theme:'mobile'
}

**Comment by charlesr1971** [comment]
The reason I am using editor.on('focus'... is that the toolbar, on the mobile, is only initialised after the ‘book’ icon is clicked upon.

**Comment by TheSpyder** [comment]
The editor `theme` property is specific to the loaded theme instance, there is no `panel` attribute required.
https://www.tiny.cloud/docs/api/tinymce/tinymce.theme/

The mobile theme does not offer this property (and, incidentally, neither does the new silver theme in TinyMCE 5).

**Comment by charlesr1971** [comment]
OK. I have found that each button [mobile UI], has a class name, specific to its function. I am using querySelector to target this name and then I can hide/show the element, using DOM methods. Thanks...
