### ISSUE TITLE
Is it possible for a format to be 'inline' and 'block' at the same time

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#4750]
I want to create Ms Word-like styles where a style applies either to the whole paragraph (if there is no selection or if more than one paragraphs are selected) or only to the text selection (if some text is selected within the paragraph).

Can I do that in TinyMCE solely relying on the style system or should I use a workaround like splitting the style into two (one for block elements and one for inline) and manually applying the correct one?

**Comment by TheSpyder** [comment]
You'll need to make two styles, sorry. It's quite difficult to determine automatically which is the intended use case, so we don't offer automatic switching between block and inline with a single style entry in the menu.

For example:
* The "no selection" case could either be intended as "apply to my block" or "apply inline to the text I'm about to type". This is a personal user choice, not something we can really offer as a configuration option.
* It's quite easy to have what appears to be an entire paragraph selection but actually there's a space not selected at the end. To the editor it wouldn't appear to be a whole paragraph selection and automatic application would use inline selection.
