### ISSUE TITLE
TinyMCE 5 RC1 Image and Media plugins dialog width on Firefox/Edge

### ISSUE THREAD

**Issue by martyf** [tinymce/tinymce#4751]
Image plugin dialog has a horizontal scrollbar on Edge (Windows) and Firefox (Windows/MacOS).

Dialog appears correctly in Safari and Chrome, with no horizontal scrollbar.

Issue can be replicated on the [RC demo](https://www.tiny.cloud/rc/).

Simply click the "Insert/edit image" button to load the Image dialog.

Windows, Microsoft Edge 42.17134.1.0:
![demo-edge-windows](https://user-images.githubusercontent.com/1491079/51095141-9dedf980-1806-11e9-92f8-d24693c50155.png)

MacOS, Firefox 64.0.2:
![demo-firefox-macos](https://user-images.githubusercontent.com/1491079/51095150-b3632380-1806-11e9-94bb-d743d4ef4053.png)

MacOS, Chrome 71.0.3578.98:
![demo-chrome-macos](https://user-images.githubusercontent.com/1491079/51095156-be1db880-1806-11e9-9df0-d9f7f68a45ea.png)

This behaviour can be replicated on my local area too, running 5.0.0-rc-1-build.3 (TBD).

**Comment by martyf** [comment]
@TheSpyder, I've also just noticed this is on the Media plugin too, in the same browsers. Edge and Firefox have the scrollbar - Chrome is fine.

**Comment by TheSpyder** [comment]
Thanks, we think it's the sizeinput control which is too wide on some browsers.

**Comment by TheSpyder** [comment]
Firefox has necessitated a change to how this control is structured, but we might finally have found a solution just in time for the release!

**Comment by lnewson** [comment]
This issue should have been fixed just before the release of 5.0 GA, as mentioned above. I've tried to replicate it with 5.0.0 and 5.0.1, but it appears to be working as expected now. Thanks again for the report and please let us know if you find any further problems!
