### ISSUE TITLE
Using premium plugins with local install

### ISSUE THREAD

**Issue by chimon2000** [tinymce/tinymce#4752]
I am attempting to use one of the premium plugins Tiny Comments with a version of TInyMCE installed from the command line.

**Do you want to request a *feature* or report a *bug*?**
Question

**What is the current behavior?**
When attempting to use the **tinycomments** plugin, nothing happens.

**What is the expected behavior?**
The **tinycomments** plugin should load just as it does in the CodePen samples.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE: 4.9.2

**Comment by fyrkant** [comment]
For questions about our premium plugins please contact the support here: https://support.tiny.cloud/hc/en-us/requests/new
