### ISSUE TITLE
RangeControl: 'Argument 1 of Node.contains does not implement interface Node.'

### ISSUE THREAD

**Issue by rogerlos** [tinymce/tinymce#4757]
Implementation of `RangeControl` in sidebar:

```javascript
EL(
  RangeControl,
  {
    key       : 'bg-color-alpha',
    label     : "Transparency",
    className : 'mynamespace-color-alpha mynamespace-inspector-range',
    help      : "Transparency of background color",
    value     : mynamespace.props.color.alpha,
    min: 0,
    max: 100,
    onChange  : val => {
      props.color.alpha = val + 0;
      mynamespace.Save( args.fieldKey, args.fieldChange )
    }
  }
)
```
This happens when either clicking the arrows in the control, trying to slide the range, or typing a number in the range box. 

I can console.log the value in both the onChange handler and `args.fieldChange`, which will be `99`.

I'm not sure why TinyMCE is upset by this, but that is where the error seems to be:

```
TypeError: Argument 1 of Node.contains does not implement interface Node.
<            wp-includes/js/tinymce/wp-tinymce.php:2:51784
Sg           wp-includes/js/tinymce/wp-tinymce.php:2:180558
Tg/<         wp-includes/js/tinymce/wp-tinymce.php:2:180629
filter       wp-includes/js/tinymce/wp-tinymce.php:2:1664
Rg           wp-includes/js/tinymce/wp-tinymce.php:2:180993
Pg           wp-includes/js/tinymce/wp-tinymce.php:2:181363
Yx/o<        wp-includes/js/tinymce/wp-tinymce.php:2:335433
throttle/o<  wp-includes/js/tinymce/wp-tinymce.php:2:95246
```
I gather even running `SCRIPT_DEBUG` we will never see unminified versions of tinymce or react in our consoles? The error messages generated by Gutenberg make chasing this stuff essentially impossible.

**Comment by TheSpyder** [comment]
You might have some success using the "break on exception" browser debugging feature and inspecting the function parameters involved in the stack.

Loading TinyMCE unminified depends on the script file used; we ship both `tinymce.min.js` and `tinymce.js` with most available download methods.

**Comment by rogerlos** [comment]
My bad. Closing.
