### ISSUE TITLE
TinyMCE 5.x: Checkbox dialog component expects "boolean" but received "string" (unchecked/checked/true/false)

### ISSUE THREAD

**Issue by Paril** [tinymce/tinymce#4758]
If you add a checkbox component to a dialog, it's supposedly designed to require a boolean value in its initialData, but will not respect the boolean passed to it (true starts with an unchecked checkbox).

If you then try api.getData(), the value then becomes "checked" or "unchecked" as a string, which then causes setData with any values to fail as that doesn't pass boolean validation.

**Comment by TheSpyder** [comment]
Which version are you using? We've only just changed the checkbox code to use booleans instead of strings, it's part of an API review we're doing to clean up before the stable release.

Perhaps something wasn't updated correctly in the currently published build, thanks for letting us know!

**Comment by Paril** [comment]
Latest git commit.

**Comment by Paril** [comment]
Seems good now!
