### ISSUE TITLE
Dialog Component Input: how to set initial value?

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#4765]
Noob question, but in the past, it was a single "value:" attribute. And now?

**Comment by manu37** [comment]
found it: 
```
initialData: {
              inputfieldname: {value}
            }
```

**Comment by abuoop** [comment]
how can i set value dynamic to input ?

**Comment by TheSpyder** [comment]
The return value from `editor.windowManager.open()` is a Dialog Instance API, which has a `setData` method
https://www.tiny.cloud/docs/ui-components/dialog/#dialogdataandstate

**Comment by chrisdyckgeorgian** [comment]
Are there any examples that fill a selectbox or listbox fill with data from an API promise response?

**Comment by ZoltanZen** [comment]
> The return value from `editor.windowManager.open()` is a Dialog Instance API, which has a `setData` method https://www.tiny.cloud/docs/ui-components/dialog/#dialogdataandstate

I need examples too.
I would like to find an answer to my case.
https://stackoverflow.com/questions/78417298/tinymce-plugin-manager-dynamically-initial-selectbox-values

`tinymce.PluginManager.add("ag-grid", function (editor, url) {
  editor.ui.registry.addToggleButton("ag-grid", {
    onAction: () => {
      /* Open window */

      let selectboxCount = 3;

      const panel = editor.windowManager.open({
        title: "Settings",
        body: {
          type: "panel",
          items: [
            {
              type: "input",
              name: "title",
              label: "Title:",
            },
            ...Array.from({ length: selectboxCount }, (_, index) => ({
              type: "selectbox",
              name: `selectbox${index + 1}`,
              label: `Select Box ${index + 1}`,
              items: [
                { text: "Option 1", value: "1" },
                { text: "Option 2", value: "2" },
                { text: "Option 3", value: "3" } /* preselect this option */,
              ],
              value: "3", // this isn't work
            })),
          ],
        },
        buttons: [
          {
            type: "submit",
            text: "Save",
            buttonType: "primary",
          },
        ],
        onChange: function (dialogApi, details) {},
        initialData: {
          title: "something",
          selectbox2: "3", // this is work, but I need dynamically initial values
          ...Array.from({ length: selectboxCount }, (_, index) => ({
            //this isn't work
            [`selectbox${index + 1}`]: "3",
          })),
        },

        onSubmit: (api) => {},
      });
    },
  });
});`
