### ISSUE TITLE
Version 4.9.2 - Regression bug - Copying a text to clipboard deletes every breakline

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4766]
Tested in Firefox. Copy the entire text from the editor and paste it in the textarea below and the text will be pasted in a single line. Copying a text to clipboard deletes every breakline. This bug didn't exists in 4.9.0.

Version 4.9.2: http://fiddle.tinymce.com/z7gaab
Version 4.9.0: http://fiddle.tinymce.com/Z9gaab

**Comment by lnewson** [comment]
This has been fixed in 4.9.4, which was released last month. Sorry we have only just got around to updating this now. Please let us know if you find any further problems!
