### ISSUE TITLE
cannot download single language pack

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#4770]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
https://www.tiny.cloud/get-tiny/language-packages/:
Cannot select checkbox for single download

**Comment by lnewson** [comment]
I'm unable to reproduce this on any supported browser, could you please let us know what browser and OS you're using, plus any other details that we could use to replicate the issue?

**Comment by manu37** [comment]
Yes, strange. Today I cannot reproduce it either, it just works. My fault.
