### ISSUE TITLE
external filemanager

### ISSUE THREAD

**Issue by labby** [tinymce/tinymce#4773]
Tried to include external filemanager (https://www.responsivefilemanager.com) in RC1 but failed, no hint in the docs to use external filemanagers.

Integration works fine in tinymce 4series.
Will it be possible in 5series?

**Comment by fyrkant** [comment]
Please share some code showing how you are including the file manager.

**Comment by labby** [comment]
we just followed the docs on
https://www.responsivefilemanager.com/#documentation-section
referring to tinymce 4 series

**Comment by TheSpyder** [comment]
Looking at the demo:
https://www.responsivefilemanager.com/demo.php

It appears to be using the `file_browser_callback` setting, which was deprecated in v4 and removed in v5. I'll make a note that we might need to contact the author about this.

**Comment by labby** [comment]
> I'll make a note that we might need to contact the author about this.
That would really be fine :-)

**Comment by Draghmar** [comment]
> 
> 
> Looking at the demo:
> https://www.responsivefilemanager.com/demo.php
> 
> It appears to be using the `file_browser_callback` setting, which was deprecated in v4 and removed in v5. I'll make a note that we might need to contact the author about this.

Wow, really? Then why it is still in docs for v5?
https://www.tiny.cloud/docs-beta/configure/file-image-upload/#file_browser_callback

**Comment by TheSpyder** [comment]
v5 is still a release candidate and we have a list of things to clean up, particularly in the documentation. I'll make sure that is added! Thanks for pointing it out!

**Comment by fyrkant** [comment]
And the docs repo is open for PRs if anyone wants to help: https://github.com/tinymce/tinymce-docs

**Comment by TheSpyder** [comment]
I'm working on a PR now actually 😅

**Comment by TheSpyder** [comment]
https://github.com/tinymce/tinymce-docs/pull/903

**Comment by labby** [comment]
> I'll make a note that we might need to contact the author about this.

Is this already done?
Including responsive filemanager is really important for our project.

**Comment by fyrkant** [comment]
You should probably contact the developer of the plugin directly if you are in a hurry to get it working.

**Comment by TheSpyder** [comment]
I have passed the information on for our product manager to action.

If responsive filemanager is a requirement of your project, I recommend sticking to TinyMCE version 4 until the plugin supports version 5. We will be supporting version 4 for quite a while yet.
