### ISSUE TITLE
(5.x) What's the recommended method of changing toolbar icon sizes?

### ISSUE THREAD

**Issue by Paril** [tinymce/tinymce#4777]
In 4.x and below, we had an option to directly change toolbar icon sizes in the settings. This feature is gone, but even without that feature we could fall back to changing font-size on the font used for icons in the CSS 5.x uses inlined SVG though, and when inlined SVG is resized it seems to make the icons very blurry. Is there any recommended method to simply changing the size of toolbar icons? There's a ton of extra whitespace around, but if I try to change width/heights or anything it completely breaks the layout of the toolbar (for instance: ![](https://i.imgur.com/63gjDiR.png))

**Comment by TheSpyder** [comment]
Resizing the SVGs will make them blurry, yes, what you're looking for is to have the SVGs rendered at a different size.

I'm not sure whether changing the skin will be enough, that's probably equivalent to how you made them small already.
https://github.com/ephox/oxide/blob/master/src/less/theme/components/toolbar-button/toolbar-button.less#L22

You may also need a custom icon pack (the SVGs are hard coded with width and height 24px). The default icons are in their own repository:
https://github.com/ephox/oxide-icons-default

The documentation for adding icon packs isn't ready yet, and this isn't fully tested, but in the current RC the API to set the icon pack name is `editor.settings.icons` which is then downloaded as `${editor.editorManager.baseURL}/icons/${Tools.trim(iconPackName)}/icons.js` (where `icons.js` is the output equivalent to `dist/js/Icons.js` generated by the `oxide-icons-default` build process).

If you're willing to give that a try, please let us know if it works for you!

**Comment by Paril** [comment]
I see, okay. What sucks is none of us are vector artists, and we've been relying on the 4.x method of using that icomoon to change the font and just slip the new characters in. The new button sizes in 5.x are wayyyy too big for desktop users (it takes up nearly double the space of the small 4.x buttons), so we're looking for a way to change this easily.

I managed to use additional CSS to change the toolbar background and adjust the button sizes, but we kept the icons to 24x24 for now. It's weird that the **scalable** vector graphics can't be easily scaled (as in, the path vertices multiplied by a scalar) and only seem to be scaled as a whole unit which produces the blurry messes.

Getting all of these into our build process (three new git repos, grunt/gulp, etc) would take a lot more work at this point and I dunno if I want to spend a lot of time getting all of that set up just to change some icons, which is why I was hoping for a quick scale solution.

**Comment by TheSpyder** [comment]
I'm sorry it's difficult right now. I'm not an expert in this either so I may be giving you the wrong advice. The need to use three repos is purely due to the early nature of the code; there is a proper skin customisation tool in the works and adjusting the icon packs is intended to be easy as well, but most of the team is focussed on stabilising the core editor before release.

I'll ask our designer to add his thoughts on this.

**Comment by lostkeys** [comment]
We switched from icon fonts to inlined SVG for a number of reasons. As @TheSpyder wrote, the documentation for this is not in place yet but here is instructions on how to rescale the default icons. I would like to note that the icons will be slightly blurred when scaling them, but that happened with the icon fonts in TinyMCE 4 too.

**To modify the icon size:**

1. Download this repo <https://github.com/ephox/oxide-icons-default> and run `npm install`  and then `gulp`. This will produce a `dist` folder.
2. Open the file `TinymceIcons.js` located in the `dist` folder. This file contains a list of all icons and the svg content.
3. Add this attribute to all SVG icons you would like to resize: ` viewBox="0 0 24 24"`. Note that some icons are larger and smaller than 24px. If you want to resize those, replace the number 24 to match the width and height of that icon. (We strip out the viewbox attribute to save space.)
4. Then replace the width and height values with the size you would like the icons to have.
5. In the top of the file you have this string `tinymce.IconManager.*add*('default', {`. Replace the word `default` with the name of your icon pack. For example `small`.

You have now created a custom icon pack. I would just like to point out that the above steps is not recommended. The proper way is to design icons in the size you want them and put them in the `src/svg` folder.

**Getting the icon pack into TinyMCE 5:**

1. Go to the root directory where your `tinymce.min.js` file is located. Create a folder named 'icons', and inside it, create an another folder with the same name as your icon pack. For example `small`.
2. Copy the `TinymceIcons.js` you edited in the previous section to this folder. Rename it to `Icons.js` (we will fix this a.s.a.p so we don't need to rename files)
3. Locate your TinyMCE init config and add the config `icons: "<name-of-icon-pack>"`. If the name of the icon pack is "small", the config would look like below. If everything is alright, you icons should now be smaller.

```
tinymce.init({
    selector: 'textarea',
    icons: 'small'
});
```

**Set the button size**
The button sizes are independent of the icon sizes. So in your case just making the buttons slightly smaller may be sufficent. To customize the button size (and many other things) you'll make a custom skin. Here is how you do that:

1. Download the skin development project here: https://github.com/ephox/oxide. (were revising the documentation here).

2. Go to `src/less/skins/ui/` and duplicate the `default` folder and rename it to something cool.

3. Open the `skin.less` and add the following variables below the comment:

   ```
   @toolbar-button-width: 20px; // size of your icon
   @toolbar-button-height: 20px; // size of your icon
   ```

4. Build the skin using first `npm install` and then `gulp build`. This will produce a `build` folder. 

5. Go to `build/skins/ui` and copy your custom skin folder. Then go to the `tinymce` folder (where your `tinymce.min.js` file is located) and paste the folder inside the `skins/ui` folder

6. Return to your tinymce init function and add the skin config. If our custom skin were named "small", our init function would now look like this:

```
tinymce.init({
    selector: 'textarea',
    skin: 'small',
    icons: 'small'
});
```

This looks like a lot of steps and we will simplify things in the future. But this is the proper and robust way to customize Tinymce 5. We all know in the back of our head that prowling the HTML for class names and overriding them in your own CSS is kind of dirty and will cause headaches when updating Tiny.

**Comment by nphias** [comment]
@lostkeys your first link on how to modify the icon size is broken

**Comment by lnewson** [comment]
@nphias the oxide and oxide icons repo got merged into our monorepo, so it's now here instead: https://github.com/tinymce/tinymce/tree/master/modules/

We also now have some docs on creating custom [skins](https://www.tiny.cloud/docs/advanced/creating-a-skin/) and [icon packs](https://www.tiny.cloud/docs/advanced/creating-an-icon-pack/).

**Comment by Seoxsc** [comment]
Greetings, modifying the main js like this can do the trick:
<svg width="16" height="16"  viewBox="0 0 24 24">

**Comment by lostkeys** [comment]
Just pointing out that scaling the icons like that would produce blurry icons on standard resolution screens since SVG nodes will end up inbetween pixels.

**Comment by msieurtoph** [comment]
A workaround that avoids modifying the source files

Add theses styles to your global styles : 

```css
.tox .tox-tbtn {
    transform: scale(0.7) !important; /* you can set the scale that you want */
    height: unset !important;
    width: unset !important;
}
```
And if you care about the bottom-border that disappeared : 

```css
.tox .tox-toolbar, .tox .tox-toolbar__overflow, .tox .tox-toolbar__primary {
  /* change the background y-positionning to : bottom 0*/
  background: url("data:image/svg+xml;charset=utf8,%3Csvg height='39px' viewBox='0 0 40 39px' width='40' xmlns='http://www.w3.org/2000/svg'%3E%3Crect x='0' y='38px' width='100' height='1' fill='%23cccccc'/%3E%3C/svg%3E") left 0 bottom 0 #FFF !important;
}
```

It is not perfect because some padding/margin are not reduced but it can really do the trick for basic usages of tinymce.
It worked pretty good for me.
