### ISSUE TITLE
(5.x) height does not match element it replaces

### ISSUE THREAD

**Issue by Paril** [tinymce/tinymce#4778]
![](https://i.imgur.com/L8F3bGJ.png)

TinyMCE is initialized to replace the editor above, but it's much smaller (232 vs 292) than the element it's replacing.

**Comment by fyrkant** [comment]
I can't seem to reproduce this, can you create a fiddle? http://fiddle.tinymce.com/

**Comment by Paril** [comment]
The issue was on my end. It's because the textarea uses a font that wasn't loaded at creation time, whoops.
