### ISSUE TITLE
What browser/versions are supported by tinymce 5?

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#4779]
What browser/versions are officialy supported by tinymce 5?

**Comment by TheSpyder** [comment]
The same as TinyMCE 4:
https://www.tiny.cloud/docs-beta/general-configuration-guide/system-requirements/

IE11, FireFox ESR, and the stable channel of Firefox, Chrome, Edge, Safari. We will support the prior stable channel version if need arises (but I have to admit it never has).

The mobile platform list is out of date. We only support the current + previous release of iOS, similar to the desktop policy, previous Android releases are supported as long as we can.
