### ISSUE TITLE
forecolor backcolor as menu items?

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#4780]
forecolor backcolor are very nice features, but frankly rather rarely used.
How about to have a menu item for forecolor/backcolor?

**Comment by TheSpyder** [comment]
This is high on our list to do but it didn’t make the cut for version 5. We will likely work on it quite soon.

**Comment by ltrouton** [comment]
Closing this ticket as the feature was introduced in [5.0.5](https://www.tiny.cloud/docs/release-notes/release-notes505/#textcolormenuitems). Thanks for posting!
