### ISSUE TITLE
(5.x) Table right-click menu appears underneath table options

### ISSUE THREAD

**Issue by Paril** [tinymce/tinymce#4782]
![](https://i.imgur.com/QgHBXyj.png)

**Comment by TheSpyder** [comment]
This one has been around for a while, but it's finally scheduled to be fixed in the current sprint :)

**Comment by martyf** [comment]
This also applies to the menu for an image too - but no doubt the one fix will clean them both up.
![image](https://user-images.githubusercontent.com/1491079/51578876-2b220400-1f13-11e9-85d4-2db9289d49b8.png)

**Comment by blackcathikari** [comment]
This should be fixed in TinyMCE 5 stable. Please let us know if you find any further problems!
