### ISSUE TITLE
TinyMCE 5: Complex/advanced layouts for Plugins without using iframes (like in v4)

### ISSUE THREAD

**Issue by martyf** [tinymce/tinymce#4783]
Plugins such as Drive and Emoticons are utilise dynamic data, and display it in a unique way - which is exactly what I'm trying to do.

I'm working on building a Plugin for v5 that in the v4 world would have been done with an iframe. But just trying to figure out the best way to try to achieve this. 

**Use case example:** the server returns a list of system-managed documents - and I want to be able to give users the ability to select one of the files (for inserting in to the editor) - but also have a "preview" button so they can access the document too. 

Looking at the rendered dialog for Emoticons, for example, shows the emoticons are presented in a "collection". 

I've been able to have my Plugin populate a Collection, but basically they're just small icons just like the emoticons usage, and looking at the source ts, there doesn't appear to be a way to override layout or style - and so it's a collection of very basic buttons only.

What sort of approach is recommended by the Tiny team to create slightly more advanced layouts using the new v5 UI components, now that iframe content has been removed?

**Comment by martyf** [comment]
This issue is the biggest stumbling block for writing new plugins using the UI Components - the included components are on the basic side.

While trying to re-write another of my plugins, which in v4 gives the user a list of articles in the site (including URL and name). This list is scrollable (with a fixed sticky header) and can also be "queried" with a search box.

Using something like "HtmlPanel", I can achieve the table layout, and can style it as needed. 

But... there doesn't appear to be a neat way to bring interactivity (such as a "click" on a row to select that item) to this sort of layout without basically adding specific calls to the table markup, such as a jQuery onClick call - which feels rather hacky.

Anything that requires basic form controls - piece of cake, and easy to achieve a consistent result. But anything beyond the basics feels lost at the moment.

Think of the "symbol" or "emoticons" core plugins - but with more control over listing. Being able to build UIs like TinyDrive would be awesome! Grids, headers, flexibility of item presentation, and options and interactivity - this level of UI development is really needed to give developers the freedom to really build upon the solid platform of 5.

The two use cases are:
- internal document browser (Tiny Drive is not an option given the files are not hosted with the system itself, and MoxieManager is prohibitively expensive for the use case)
- internal article/link browser

These are more dynamic than just simple form controls.

I've been able to rewrite all of my other plugins in to v5 UI Component code - that's seven in total - but these last two are feeling stuck.

Are there plans in the works to extend upon the new UI Components to allow more advanced plugins (such as a layout like TinyDrive)? 

Are there recommendations on how to approach adding interactivity to those custom layouts (such as those within the HtmlPanel), even if this is an interim solution?

**Comment by TheSpyder** [comment]
Reference to an earlier issue with a similar question:
https://github.com/tinymce/tinymce/issues/4588

Tiny Drive doesn't use the TinyMCE UI, it's based on the same UI framework ([alloy](https://github.com/ephox/alloy#readme)) but bundles that directly in order to look the same whether running with version 4 or 5 of the editor. Unfortunately there's no way to recreate Tiny Drive with the dialog API as it will ship in v5; HtmlPanel was designed for display only, not interactivity.

I wonder if an adjustable size for collection items would help. It wouldn't give you a preview _button_, but it would give you the larger grid to work with.

We won't have a good answer for your needs at launch, I'm afraid. We moved in a very deliberate direction to replace the kitchen sink approach of v4 with a simple API over what is a very powerful but also very complex framework that isn't well documented. How we address the more advanced dialog requirements is yet to be determined, I can only promise that we are very much aware of our need to do so post release.

**Comment by martyf** [comment]
That makes sense, thanks for the update.

A collection of items that has more customisation (maybe even able to drop in some HTML, such as an img src for a preview of an image, or image icon of a PDF document, etc) could create incredible flexibility.

As a single column, it could then be 100% width and serve a purpose of the "scrolling table". If it were injectable with HTML, could then emulate two columns.

As a grid, greater flexibility on size and layout could really open up the possibilities for a file/document browser.

If sticking with how the collection is used currently, this is probably one more advanced feature, but the ability to select an item in the collection but not necessarily insert it yet - i.e. if you click an emoticon, it's inserted immediately. That could be handy if there are multiple fields for the user - selecting the item "selects" it, but the user still needs to trigger the dialog's button to perform the insert.

I'm happy to be involved with any queries, surveys, ideas, testing, whatever I can to help. The approach you've taken with 5 is so clean - and makes development simple - and keeping in line within those boundaries makes total sense.

**Comment by martyf** [comment]
Top stuff - just on the collection and columns - if there is only one column, then it just makes a new row for each button but only as wide as the largest in the list. This could be overcome by being able to add a class to the collection itself - which also could have benefits for more advanced layouts and styling/sizing of them.

I noticed "auto" or a number in the source code too, however, that then breaks the text from appearing. I'll create another issue for that one though to keep this on topic.

And duh, sorry, silly me, even in my test of using Collection, I can select and not insert. Must be the heat cooking the brain down here. I'm going to run with that.

**Comment by TheSpyder** [comment]
hmm we can definitely prioritise bugs to make the collection component work as designed, rather than just as we used it. And yes, one column layout would be among the improvements with a size option.

> Must be the heat cooking the brain down here. I'm going to run with that.
Stay safe down there!

**Comment by martyf** [comment]
> > Must be the heat cooking the brain down here. I'm going to run with that.

> Stay safe down there!

Hot in Vic today... but hotter in my home town of Adelaide. Days like this I'm glad I moved 😉
