### ISSUE TITLE
TinyMCE 5: TAB in menu jumps to next group instead of next button

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4795]
In v4 TAB key moves focus to the next button in toolbar, in v5 it jumps to the first button of the next toolbar group. While I see it's possible to jump with Left/Right Arrow keys, I'm not sure this is intended behavior.

**Comment by TheSpyder** [comment]
This is intended, at the accessibility level each toolbar section is given `role=toolbar` and as far as I know tab is the recommended method to move between elements of that type.
