### ISSUE TITLE
set default style in Element

### ISSUE THREAD

**Issue by zpqsunny** [tinymce/tinymce#4798]
**Do you want to request a *feature* or report a *bug*?**
question
**What is the current behavior?**
in **tinymce 4.9.2** how to set default style in Element
for example 
when i upload a image
default html is `<img src="/upload/xxx.jpeg" alt="" width="372" height="247">`.
but i want to get `<img src="/upload/xxx.jpeg" alt="" width="372" height="247" style="max-width=100%;height=auto">`
I found a way is set `style_formats` option; but not very friendly to the user; user need click
Can anyone tell me a better way?

**Comment by lostkeys** [comment]
There is a config option called [extend valid elements](https://www.tiny.cloud/docs-beta/configure/content-filtering/#extended_valid_elements) where you can force attributes with values. However it doesn't apply the styles in the editor until you save and reload the content or view the source code. Here is a [demo fiddle](http://fiddle.tinymce.com/KAgaab/1). But I agree, there should be a way to set default classes and styles and have them show up in the editor content.

**Comment by zpqsunny** [comment]
@lostkeys thanks.

**Comment by lostkeys** [comment]
So after a bit more research, this is how you would do this. Lets use your image example as a use case. In your [content_css](https://www.tiny.cloud/docs-beta/configure/content-appearance/#content_css) you define the default styles, in this case `img { max-width: 100%; height: auto;}` and then you use style formats for any alternatives.
