### ISSUE TITLE
editor.windowManager.open URL not working

### ISSUE THREAD

**Issue by sbillard** [tinymce/tinymce#4801]
BUG (or unclear documentation.)

the following code from a mce version 4 plugin will open a window and fill the content from a link to some PHP code.
`function _onAction(editor, url) {
		// Open window with a specific url
		editor.windowManager.open({
			title: 'netPhotoGraphics:obj',
			width: 800,
			height: 600,
			buttons: [],
			url: url + '/pasteobj.php'
		});
	}`
This code was modeled from examples in the mce4 documentation https://www.tiny.cloud/docs/api/tinymce/tinymce.windowmanager/

This code throws errors on mce5 because the "body" element is absent. I have modified the code to:
`	function _onAction(editor, url) {
		editor.windowManager.open({
			title: 'netPhotoGraphics:obj',
			body: {
				type: 'panel',
				items: [],
			},
			width: 800,
			height: 600,
			buttons: [],
			url: url + '/pasteobj.php'
		});
	}`

and the window will open. But the PHP page content is not present. 

Note: if I add the "body" element to the mce4 version it no longer works on mce4.

**Comment by martyf** [comment]
TinyMCE 5 no longer allows this. The Tiny team are aware of this but there is no solution as yet.

See #4756 and #4786

**Comment by TheSpyder** [comment]
Beat me to it :)

4786 is the one we're leaving open to track requests and determine if or when we add this to v5.

**Comment by mutekellim** [comment]
Look #4786 :) last comment
