### ISSUE TITLE
tinymce5: do we see the toolbar_items_size property somewhen?

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#4802]
tinymce5: do we see the `toolbar_items_size` property somewhen?

**Comment by TheSpyder** [comment]
It's not planned at this stage (I can't even find it in the documentation, although I can see what it did in the code).

Our designer wrote up his thoughts on how to customise the icon size in https://github.com/tinymce/tinymce/issues/4777#issuecomment-456801998 - we have tools in the works to make this easier, but for now it's a bit of a hassle. Follow that thread for updates.
