### ISSUE TITLE
Shift+enter bug

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#4803]
I want to report a bug.

I type some word then I press shift + enter type other word then select second word and use bold format then I press shift+enter again and remove bold format. After these steps i got 4 lines, but expect 3 lines

I expect 3 lines, but got 4

Last version of tinyMCE

**Comment by alecpl** [comment]
Issue confirmed also with TinyMCE 5 demo using Chrome. No issue in Firefox.
