### ISSUE TITLE
Mixed "formats" config option with "selector" overrides

### ISSUE THREAD

**Issue by Paril** [tinymce/tinymce#4804]
This is a bit hard to explain, but I want to prevent people from formatting on certain pieces that won't retain formatting (in my test sample, my conversion process does not retain formatting inside of `<blockquote>` elements, so I want to "turn off" bold, italic, etc while you're inside those elements).

"formats" override with "selector" seems to be what I would want, but it produces odd results. See fiddle here:

http://fiddle.tinymce.com/RAgaab

If you attempt to select the whole text and bold it, it works (it shouldn't, due to selector), but then unbolding it does not function. You can unbold certain pieces of it, however. If you remove the "formats" option from that list, you can see that now you can unbold the selection as you'd expect.

How would I go about doing the above without editing all of the plugins/builtin code behaviors?

**Comment by lnewson** [comment]
Your format option isn't valid, as formats should be an inline, selector or block format and can't be mixed. So what's happening is that inline is taking precedence here and it's just behaving like the normal bold format. So I guess this would be a request to support mixed formats, or to be able to exclude certain elements for formats?

Note: This also happens on 4.x, so it's not something that's changed in 5.0.
