### ISSUE TITLE
TinyMCE 5: Loading overlay does not disappear on iOS

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4807]
If I go to https://www.tiny.cloud/rc/ with my iPhone (iOS 12.0.1, default Safari browser) the loading icon never disappears. I can click the book icon and make the editor working, but still see the loading icon (layer).

**Comment by TheSpyder** [comment]
Sounds like an iframe background issue. The front page has a loading icon always behind the editor, so if the iframe is transparent it shows through.

**Comment by lnewson** [comment]
This should now be fixed in 5.0.2, although the website has had some updates and no longer shows the loading icon anyways.
