### ISSUE TITLE
Drag to resize not working correctly

### ISSUE THREAD

**Issue by mattcoz** [tinymce/tinymce#4809]
Using TinyMCE 5 RC2, dragging the corner to resize the editor doesn't work correctly. If I drag quickly it seems to be ok, but if I drag slowly or drag horizontally the editor will shrink. So there must be a miscalculation in the drag event. I noticed that if I remove the border from the element, or change box-sizing to content-box, the problem goes away.

**Comment by lnewson** [comment]
I can replicate this and what I think is happening is the resizing logic is using scrollHeight which doesn't take into account borders. As such, every time the drag event occurs its losing 2px, which is why removing the border or setting box-sizing to content-box works.

**Comment by blackcathikari** [comment]
This should be fixed in TinyMCE 5.0. Please let us know if you find any further problems!
