### ISSUE TITLE
Firefox: Styles applied to full paragraph are getting applied only partially

### ISSUE THREAD

**Issue by avcs06** [tinymce/tinymce#4810]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In firefox, styles applied to full paragraph are getting applied only partially for a specific case

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Create a fresh paragraph, and generate following html structure
`<p><style> some text <style> some text </style> some text </style><br></p>`
2. Select the full paragraph using triple click
3. Apply some new style or link
4. Style is applied only to the first text node

**What is the expected behavior?**
Style should be applied to full paragraph

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: **4.7.13**
Browser: **Firefox**
OS: **Ubuntu**

**Comment by metricjs** [comment]
Hey @avcs06. As I mentioned in the associated PR, we are closing this issue as we can no longer reproduce the bug as of TinyMCE 5.2.
