### ISSUE TITLE
Version 4.9.3 & 5.0 - Table bug - Adding a column in a table that has cells without width values, resizes the table width to 0

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4812]
Tested in Firefox. Adding a column in a table that has cells without width values, resizes the table width to 0.

Fiddle 4.9.3: http://fiddle.tinymce.com/uBgaab

**Comment by lnewson** [comment]
I can replicate the issue on Firefox, however it doesn't happen on Chrome or Safari. I'll log a ticket internally so this can be investigated.

**Comment by wonderbugtiny** [comment]
Please note that this has been fixed in 5.0.8. Let us know if you have any further issues. Thank you!
