### ISSUE TITLE
[Feature request] Inline editor placeholder

### ISSUE THREAD

**Issue by jaesung2061** [tinymce/tinymce#4813]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** No way to add a placeholder by default

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?** For there to be a way to add a placeholder

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?** N/A

I wanted to ask... Why is this not a default feature since like, 5 years ago?

**Comment by lnewson** [comment]
@jashua212 can you please clarify mean by placeholder here? Do you mean placeholders for input elements in dialogs, etc...? If so, you've been able to set those for quite some time. Here's some examples:
- v4: http://fiddle.tinymce.com/PBgaab
- v5: http://fiddle.tinymce.com/QBgaab

**Comment by jaesung2061** [comment]
I mean in the main editor. I'm running an inline version and so it's not obvious where the text area is and I need to add a placeholder to give them a hint.

Also, this might not be 100% related but the vue tinymce package loads the main tinymce package dynamically. Because of this I can't create plugins because the global tinymce object doesn't exist until some time after the script execution.

**Comment by blackcathikari** [comment]
@jaesung2061 I've forwarded this request to our design team. We'll let you know when there's an update.

**Comment by adesege** [comment]
Any update on this? @blackcathikari

**Comment by TheSpyder** [comment]
We think we've decided to go with a "hide on focus" style placeholder, but we haven't scheduled the work to implement it yet.

**Comment by adesege** [comment]
Thanks for the response @TheSpyder. Perhaps, can I get a code snippet on how to achieve this or a reference to the documentation on what method to use? I'm currently setting a default on initial page load and this isn't a good UX.

**Comment by TheSpyder** [comment]
The idea will be to have a default with a specific style, so it's greyed out like input placeholders, and when the editor receives focus it will be removed. With perhaps logic to restore it if the editor loses focus and has no content.

**Comment by jordanade** [comment]
Official support for inline-editor placeholders would be fantastic and highly relevant to my use case. Right now I'm using a hack that often breaks in different CSS contexts. Hope this gets prioritized. Thanks!

**Comment by petko** [comment]
That would be fantastic not only for the inplace editor, but for the classic one too.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which added a new `placeholder` setting that can be used to show placeholder content when the editor is empty. It will also fallback to using the `placeholder` attribute where the target element can use a placeholder attribute (eg textareas). Here's a fiddle to show how to use the new setting/feature: http://fiddle.tinymce.com/7bhaab. Please let us know if you have any further issues.

**Comment by petko** [comment]
Excellent news! It would be helpful to add an option for the prompt text to disappear whenever the editor has the focus, as this is the preferred way for some users.
