### ISSUE TITLE
Build Customizer Out of Date (using 4.9.2 instead of 5.0.0)

### ISSUE THREAD

**Issue by Jojoshua** [tinymce/tinymce#4815]
Getting 4.9.2 instead of 5.0

**Comment by Afraithe** [comment]
Build customizer will not work with 5 for a while, there are some changes in 5 that wasn't compatible with the way that is built. We will address this when there is time for it.

**Comment by Jojoshua** [comment]
I noticed the build customizer was titled for v4. Any idea when this will be compatible for v5?

**Comment by metricjs** [comment]
Hi @jojoshua, the build customizer was originally created to allow integrators to better control the bundle size of TinyMCE. We have since implemented other improvements in this area, so Tiny has decided not to update the build customizer for TinyMCE 5. As such, I will be closing this ticket.
