### ISSUE TITLE
Deleted Tracking Issue in Mozilla firefox 65.0 version in Ice plugin

### ISSUE THREAD

**Issue by jeeva1989** [tinymce/tinymce#4816]
Deleted Tracking Issue in Mozilla firefox 65.0 version in Ice plugin

**Comment by blackcathikari** [comment]
@jeeva1989 Could you please clarify what you mean?

**Comment by wonderbugtiny** [comment]
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.
