### ISSUE TITLE
TinyMCE 4.9.1: Editing a video prepends it to all the content in IE

### ISSUE THREAD

**Issue by rickCapica** [tinymce/tinymce#4817]
I am having an issue when resizing a video in IE. Click and drag resizing works fine but when I select the video, click the media button in the toolbar and click OK, the video moves from its original location to the beginning of the editor.

I am currently using version 4.9.1 and have tried 4.9.3 but that doesn't fix it either.

Internet Explorer version I am using is 11.523.17134.0

**Comment by rickCapica** [comment]
Oops!

**Comment by lnewson** [comment]
Thanks for the report! I can reproduce this with video's that doesn't use an iframe on IE11 in 4.x and 5.x. I think it might be related to the fact that IE loses it's selection in iframes when you select something in the parent, but I'm not 100% sure so I'll log a ticket for us to investigate.

**Comment by TheSpyder** [comment]
TinyMCE 6 doesn't support IE, so we're not going to be fixing this. Sorry.
