### ISSUE TITLE
BUG: Link list sub-menus in ver. 5

### ISSUE THREAD

**Issue by adaniello** [tinymce/tinymce#4822]
Since TinyMCE 4.0.27 it is possible to have sub-menus within the link list. 

From TinyMCE 5.0 sub-menus aren't visible.

All OS and browsers are affected.

Try http://fiddle.tinymce.com/wleaab/102 (from originale fiddle as suggested in documentation at https://www.tiny.cloud/docs/plugins/link/) or http://fiddle.tinymce.com/WBgaab (sample with same configuration suggested in documentation).

**Comment by emergence75** [comment]
is there any update on this issue ?

**Comment by acurtiss** [comment]
We use the nested link list feature quite heavily, and won't be able to upgrade to TinyMCE 5 until or unless the functionality is restored. If someone can give us a sense of whether this issue is a priority, that would be helpful and appreciated.

**Comment by misterHippo** [comment]
+1

Was looking forward to experiencing all the TinyMCE-5-iness on a new project, but this will prevent me from using it. :(

Is there some interim code we can apply?

**Comment by misterHippo** [comment]
[Oh, just found this](https://community.tiny.cloud/communityQuestion?id=9064N000000EUKbQAO#comment-id-9074N000000ADQhQAO)

> The nested sub-menus are not supported in TinyMCE 5.  That example is not in the TinyMCE 5 documentation since that approach is no longer supported.

That's very sad.

**Comment by TheSpyder** [comment]
Despite how that reads it's not that we'll _never_ support it, otherwise we'd close this bug. Just that it's not supported currently.

**Comment by misterHippo** [comment]
Well, that's good to hear. (Would be good to see that noted on the page I linked above. IMHO of course.)

Do you have a timeline for the re-inclusion of it? Or indeed, replacement code that _probably_ works we can test with?

**Comment by TheSpyder** [comment]
We don't, sorry. One level of submenu we could perhaps do without _too_ much hassle, but v4 actually supports arbitrary levels of nesting.

http://fiddle.tinymce.com/WBgaab/1

The v5 UI library wasn't designed with that in mind. We didn't discover this until it was too late to change it, and the level of requests to restore submenus has been fairly low in comparison to other issues so it hasn't bubbled up the priority list yet.

**Comment by misterHippo** [comment]
Oh, so it's not the link plugin, it's the UI library. Gotcha.

Well, for now I might be able to get away by implying depth and hierarchy with indenting...

**Comment by fr00x** [comment]
We're also needing this feature back.

**Comment by adaniello** [comment]
This issue was submitted almost a year ago, but nothing.
@TheSpyder Maybe it's time to do some updates for v5 UI, are you agree?

**Comment by misterHippo** [comment]
In case it's relevant, this feature was one of the major reasons I left CKEditor behind. The current project I can make do (*code for, not replace the entire HTML editor), but who knows about the next one.

Hoping to hear something positive soon.

**Comment by TheSpyder** [comment]
@adaniello I have moved on to focus on a new major feature, I just sent a reminder to the team working on the core editor to make sure this hasn't been forgotten

**Comment by futureweb** [comment]
well, the lack of nested sub-menues in the link_list just brought me some major hassle ... updated Tiny on our Projects from 4 to 5 ... all working fine, except our whole Link Lists are broken ... really a pity it's not supported yet ... guess I have to go back to 4 again ... lot's of time wasted ... :-(

**Comment by mathi1993** [comment]
I also need this feature.
Any update on this issue?

**Comment by misterHippo** [comment]
>  I just sent a reminder to the team working on the core editor to make sure this hasn't been forgotten

@mathi1993 - I think maybe that's the update?

@TheSpyder - Any chance you can request a core editor team member come and join this thread?

Thanks :)

**Comment by lnewson** [comment]
@misterHippo most of the core editor team watches GitHub as we can, so we have seen this. However the scheduling is really up to our PM team. Based on discussions after @TheSpyder brought this up with the team, we are hoping to prioritize this, but it likely will be at least 5.3.0 before we're able to bring this or a similar functionality back sorry.

**Comment by misterHippo** [comment]
* Waves * Hello Core Ed team! :)

Ah, the good ol' project management team. Righto. Well, as long as it's on the roadmap, I'm happy.

What are we at now? 5.1.5? Do you have a broad time frame for 5.3 delivery?

Thanks for jumping in on this @lnewson - appreciate it. :)

**Comment by lnewson** [comment]
I'll check with the team to see if we have anything more concrete. However, we're just about to code freeze for 5.2.0, so it'll like be a couple of months unfortunately.

**Comment by misterHippo** [comment]
That's better than some of the other projects I've been the end user for. So I'm happy with life signs, listening and progress (planned or actual). :)

Thanks mate.

**Comment by shanereichart** [comment]
I didn't see a proper way to upvote this issue, so I'll just mention that this also prohibits us from upgrading to v5.

**Comment by dejongensvanboven** [comment]
Just upgraded to version 5.4 only to find out that this is an issue in TinyMCE 5. No sub menu's means no deal, sadly. Back to version 4... Any chance this will be picked up?

**Comment by lnewson** [comment]
Sorry we've not given an update in a while, but I just wanted to let you know we've just included this as part of our current sprint. That means if all goes well, it should hopefully get included in TinyMCE 5.5. We'll be sure to link the relevant PR to this issue when one is logged.

**Comment by shanereichart** [comment]
Thanks, @lnewson ! That's great news!

**Comment by lnewson** [comment]
This missing functionality has been implemented in TinyMCE 5.5.0, which was released to the community earlier today. Thanks again for reporting this and please let us know if you have any further issues.
