### ISSUE TITLE
Autolink plugin appends insecure hypertext transfer protocol

### ISSUE THREAD

**Issue by bpchasse** [tinymce/tinymce#4824]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Autolink plugin auto-appends insecure http protocol handler to links.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
paste in the following link: www.fiddle.tinymce.com - hit enter - inspect and notice the appended "http://" protocol.
**What is the expected behavior?**
"https://" (secure) protocol is appended by default, if no protocol is specified and link starts with "www."
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
v5 , all browsers, all OSs.

**Comment by lnewson** [comment]
Since this is very similar to https://github.com/tinymce/tinymce/issues/4825 i'm going to collapse them into the one issue to make it easier to track. The other ticket has all the details, etc... so I'll close this one as a duplicate.
