### ISSUE TITLE
TinyMCE 4.9.3: Link list still content displays offscreen when window is small

### ISSUE THREAD

**Issue by cdaveb** [tinymce/tinymce#4827]
I'm not sure what the appropriate protocol is for reporting that an issue still exists when it has been closed already. I added a comment to the initial report at #4624 , but in case closed issues are not reviewed I thought I should also add it as a new issue.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When in a small window, the link_list feature when using long or nested nested menus does not correctly adjust the position of the menus to the edge of the browser window, so menu content flows outside the window and is not usable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

I've created an example here of the behavior:
https://codepen.io/cdaveb/pen/YJERby

To reproduce it, bring up the link window by selecting text and using the link option. Then scroll towards the bottom of the page. Open the link list and navigate the menus. You'll note that some of the menus appear cutoff by the edge of the page. This can be worked around if the window is large enough, but that's not an option for all users. Below is a screenshot of the behavior in question:

This is a screenshot of what I'm seeing:
 ![tinymce_scrollsoffscreen](https://user-images.githubusercontent.com/6133808/52749652-b0428b00-2f9e-11e9-8707-7b98debf1f79.png)

**What is the expected behavior?**

The expected behavior is for the menus to be displayed in a position that the entire menu can be seen or scrolled to, even when at the bottom of the screen or when the window is small.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I can reproduce the issue reliably with a small browser window in TinyMCE 4.9.3, 4.9.2 and 4.9.1  in Chrome and Firefox on the Mac .

**Comment by TheSpyder** [comment]
When you comment on a case, even a closed one, it notifies all participants (and anyone watching the project). You don't need to open a new ticket, I'll let @lnewson know he needs to take another look.

**Comment by lnewson** [comment]
After looking at this more, this is actually a different issue to #4624 because the other was related to the scroll position and it not taking into account the bottom of the page when trying to position. This one however is about how listbox components are rendered on really small screens, where there isn't enough room to render the menu.

As such, I'm going to reopen this so that it can be investigated further. One possible solution maybe to make the menu scroll when there's not enough room to render it fully, but we'd have to look into that.
