### ISSUE TITLE
Upload image format error caused crash, must refresh the page to continue to use

### ISSUE THREAD

**Issue by TY-LIU** [tinymce/tinymce#4828]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Upload image format error caused crash, must refresh the page to continue to use.
Select any non-image file to upload, you can find this error.
`Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.`

https://codepen.io/ty-liu/pen/MLqQLB

**What is the expected behavior?**
Getting the file stream in the images_upload_handler hook, I judge the file type myself

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 5.0.0 / chrome 71.0.3578.98 / win 10

**Comment by JamesToohey** [comment]
Hi @TY-LIU, apologies for the delay in responding to this.

In a recent release, the `input` was given the `accept="image/*"` attribute, so only images can be selected in the file dialog. That means this error is no longer possible, so I'll close this issue.
