### ISSUE TITLE
BUG: Missing template's description in v. 5

### ISSUE THREAD

**Issue by adaniello** [tinymce/tinymce#4829]
Template plugin (https://www.tiny.cloud/docs/plugins/template/) allows also a "description" info. Now, by v. 5.x this info is defined in plugin but not shown in modal window.

Check demo at http://fiddle.tinymce.com/eCgaab

Thanks

**Comment by lnewson** [comment]
Thanks for letting us know we missed that in v5! The issue should now be fixed in 5.0.2. Please let us know if you find any further problems!
