### ISSUE TITLE
Question: Change spellchecker_language on the fly

### ISSUE THREAD

**Issue by dezertdezine** [tinymce/tinymce#4830]
TinyMCE version 4.9.2

I'm doing this to grab content in different languages on the fly
```javascript
            $.ajax({
                type: 'GET',
                url: admin_url + '/pages_process.php',
                data: {
                    id: id,
                    page_type: page_type,
                    lang: lang
                },
                success: function (data) {
                    var html = data;
                    tinymce.get('content').setContent(html);
                }
            });
```			
			
Is it possible to set the spellchecker_language in a similar way to
```javascript
tinymce.get('content').setContent(html);
```
...something like
```javascript
tinymce.get('spellchecker_language').setSpellcheckerLanguage(lang);
```
?

**Comment by alecpl** [comment]
In older versions I was using `editor.settings.spellchecker_language = lang`, but it looks it might not work anymore. So, I also would like to know the answer.

**Comment by alecpl** [comment]
BTW, once upon a time there was setLanguage() method. https://github.com/tinymce/tinymce/commit/4556feeca525d2d969d275f86bcd8e3edf9580ee. So, until there's a way to do this, it is a feature request.
