### ISSUE TITLE
Case sensitive attributes support in v5

### ISSUE THREAD

**Issue by dmitry-kostin** [tinymce/tinymce#4833]
There is no ability to use case sensitive attributes.
Tiny transforms all attrs to lower case
I personally need support for angular attributes markup
eg `<p *ngIf="visible"></p>`
but event if to set config to:
`valid_elements: '*[*]'`
i got
`<p ngif="visible"></p>`

Is here any workaround for this?

**Comment by spocke** [comment]
HTML and the DOM doesn't support that. Created a fiddle that shows that it will always be lowercase: https://jsfiddle.net/dornqevk/

Closing this ticket since it's not something we can support.
