### ISSUE TITLE
With branding/elementpath both false, the resize handle displays on the left

### ISSUE THREAD

**Issue by jdufresne** [tinymce/tinymce#4834]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When TinyMCE is initialized with both `branding: false` and `elementpath: false`, the resize handle of the status bar displays on the left instead of the usual right.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Run: <http://fiddle.tinymce.com/mCgaab>

Notice the resize handle is on the left.

**What is the expected behavior?**

The resize handle should display on the right of the status bar as it normally does.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE: 5.0 (edge)
Browser: Firefox 65.0 
OS: Linux Fedora 28

This works in TinyMCE 4.9.3: <http://fiddle.tinymce.com/nCgaab>

**Comment by lnewson** [comment]
This should now be fixed in 5.0.2. Please let us know if you find any further problems!

**Comment by jdufresne** [comment]
It works. Thanks!
