### ISSUE TITLE
Typed spaces get stripped from the back when an image is present inline

### ISSUE THREAD

**Issue by Thorazine** [tinymce/tinymce#4836]
**bug**
Typed spaces get stripped from the back when an image is present inline

**[Fiddle](http://fiddle.tinymce.com/pCgaab/1)**

**Reproduce**
Type text with spaces after "magna aliqua.". Spaces will not be visible

**What is the expected behavior?**
Spaces should be visible and not be stripped

Tiny 5.0.0

**Comment by lnewson** [comment]
This issue should now be fixed in 5.0.1 and the fix has also been backported to the 4.x branch, so that it'll be included in the next 4.x release. Please let us know if you find any further problems!
