### ISSUE TITLE
Image linking bug in v5

### ISSUE THREAD

**Issue by sleewoo** [tinymce/tinymce#4838]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behavior?**
Image replaced with `undefined` when editing link

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Link some image.
Now try to edit the image link.

https://www.tiny.cloud/docs/demo/full-featured/

[Video](https://www.amazon.com/clouddrive/share/slBq6Bv7X5KtC62r8cWb6wU5BQaWR2cVuIGL08tOQw/Qf2bocAzQAaIAGBvFis1kA?_encoding=UTF8&*Version*=1&*entries*=0&mgh=1)

**What is the expected behavior?**

Link to be updated without wiping image

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Specific for v5 only.
Work well on v4.

**Comment by blackcathikari** [comment]
Thank you for reporting this! I'll log this and we'll look into it.

**Comment by blackcathikari** [comment]
This should be fixed in the next nightly and community releases. Please let us know if you find any further problems!
