### ISSUE TITLE
[5.0.0] media_url_resolver with media_poster:false fails

### ISSUE THREAD

**Issue by Thorazine** [tinymce/tinymce#4840]
**Bug**

**What is the current behavior?**
any value in the media_url_resolver fails when media_poster is set to false

**[http://fiddle.tinymce.com/0Cgaab/1](http://fiddle.tinymce.com/0Cgaab/1)**

**What is the expected behavior?**
Getting back an object with the url

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0.0

Edit: It also fails with media_alt_source: false

**Comment by lnewson** [comment]
This issue should now be fixed in 5.0.1. Please let us know if you find any further problems!
