### ISSUE TITLE
TinyMCE 5: Color input issues

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4842]
The color input used e.g. for table border and background color has some issues:

1. Left-border is not blue when the color swatch element is focused.
2. I think it is not the best usability when the color swatch is white if the color is unset. I'd expect some chequer-board-like background like here https://labs.abeautifulsite.net/jquery-minicolors/.

**Comment by lostkeys** [comment]
The color input field has been redesigned to address both issues and will be part of an upcoming release.

![image](https://user-images.githubusercontent.com/3122929/67272830-90fce580-f4bd-11e9-8598-bbaa25b5e629.png)

**Comment by alecpl** [comment]
I don't see it in 5.1.1, so what upcoming release are you referring to?

**Comment by lostkeys** [comment]
Honestly, it's not up to me to say exactly which release it will ship with, but it's merged, I can say that at least.

**Comment by lostkeys** [comment]
I've been told it will ship with TinyMCE 5.2 before Christmas.

**Comment by alecpl** [comment]
Thanks.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which includes the fix for this issue. Please let us know if you have any further issues.
