### ISSUE TITLE
TinyMCE 5: Remove button outline in Firefox

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4843]
In Firefox menu buttons have dotted outline when focused. The outline is redundant should be removed.

Something like this should fix it:
```
button::-moz-focus-inner {
    border: 0;
}
```

**Comment by lostkeys** [comment]
This is now fixed and will be shipped in a coming release.

**Comment by lnewson** [comment]
We've just shipped 5.0.2 which includes the fix for this. Please let us know if you find any further problems!
