### ISSUE TITLE
Getting Error on Integrating Tinymce in ionic v4

### ISSUE THREAD

**Issue by jawad-aziz-farhad** [tinymce/tinymce#4849]
After installation with this command 
**npm install --save tinymce angular2-tinymce** 
in my **ionic v4** project, there is no skins with these names at the mentioned paths as its mentioned in the repo Usage, so I downloaded the files and copy the files from downloaded version to the assets folder,
when I run the project with 
**ionic serve --lab** , 
it gives me the error

**ERROR in ./node_modules/angular2-tinymce/fesm5/angular2-tinymce.js
[ng] Module not found: Error: Can't resolve 'tinymce/themes/modern/theme' in '/MY PROJECT_PATH/node_modules/angular2-tinymce/fesm5'**

**Comment by lnewson** [comment]
Thanks for the report, however this isn't the right project for reporting this issue, as it's related to the `angular2-tinymce` wrapper around TinyMCE which is maintained by someone else: https://github.com/Ledzz/angular2-tinymce (it also looks like it only supports v4)

As such, can I ask that you please log the issue with that project and they should be able to help you out. Either that, or you could look at using the Angular project we maintain https://www.tiny.cloud/docs/integrations/angular2/.

**Comment by jawad-aziz-farhad** [comment]
Thanks @lnewson.
