### ISSUE TITLE
IOS no scroll down and text container outside V5 IPAD

### ISSUE THREAD

**Issue by samuel9554** [tinymce/tinymce#4850]
On Ipad 5gen using both Safari and Firefox.

1- I don't find anyway to scroll down the text.
2- The text container is going outside the box.

Here's a link to a video [https://drive.google.com/file/d/1OVNv-4rtfwF6dPlrzQumDOWqGEQPU2SO/view?usp=sharing](https://drive.google.com/file/d/1OVNv-4rtfwF6dPlrzQumDOWqGEQPU2SO/view?usp=sharing)

**Comment by lnewson** [comment]
Thanks for the report! I can confirm this is a known issue which is currently being tracked by https://github.com/tinymce/tinymce/issues/4846 so I'm going to close this, as we're using that as a tracker atm.
