### ISSUE TITLE
TinyMCE 5 Dialog API .setData() to accept numbers

### ISSUE THREAD

**Issue by WarwickGoatee** [tinymce/tinymce#4852]
**Do you want to request a *feature* or report a *bug*?**
Kind of a feature request. Removal of a feature I guess...

**What is the current behavior?**
If you pass a number to the dialog api .setData method, it complains that it's not a string (error says "Expected type: string but got: number")

**What is the desired behavior?**
It's easy enough to work round of course, but I can't see as there's any advantage to forcing people to submit `"" + numberVariable` instead of just `numberVariable`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.0.1

**Comment by TheSpyder** [comment]
Can you tell us more about the dialog you are opening? The data types `setData` requires are set by the components that are on the dialog.

Although we haven't published them yet there are extensive TypeScript types driving this UI. Strings are required for most DOM values, so even though browsers _accept_ other values and coerce them we have stuck to string for now.

**Comment by WarwickGoatee** [comment]
It's a dialog with an input box for entering numbers into. I've set it up to auto-populate a few fields when the relevant element is selected by looking at DOM info that returns number values rather than strings.
Another response, if you didn't want to parse both numbers and strings in the same type of component might be to offer a specific number input component...
