### ISSUE TITLE
Cannot set dialog width or size

### ISSUE THREAD

**Issue by authcode** [tinymce/tinymce#4854]
I'm using the TinyMCE 5.0.1 Dialog UI component in a custom plugin. The docs don't really mention how to set the dialog dimensions but from looking at the source code I've seen references to "width" and "size" properties; the former taking an integer and the latter a string such as "normal".

However, I've set both of these properties with various values and neither seem to have an effect on the dialog size. It looks like the default size is hard coded as 480px max-width in the editor stylesheet and the dialog config can't currently be used to override this. Or am I missing something?

For example, setting Dialog width in this way does nothing:
```javascript
editor.windowManager.open({
  title: 'Test',
  width: 800,
  body: {
    type: 'panel',
    items: []
  },
  buttons: []
});
```

**Comment by TheSpyder** [comment]
The docs so far are mostly a summary, sorry, we are aware that detailed API style documentation for the dialog configuration options is needed. It is something we are working on (the first phase, docs for `editor.ui.registry`, should go live soon).

Width won't do anything there; `size: 'large'` is what you need. There are three size classes, here is where that happens in the code:
https://github.com/ephox/bridge/blob/master/src/main/ts/ephox/bridge/components/dialog/Dialog.ts#L53

The other thing we're working on is publishing our own TypeScript types which will would have given you a compile error 🙂

**Comment by elshobokshy** [comment]
@TheSpyder what if we want a custom width and height? Why did you only make 3 fixed values? How to change the width and height then? :/

**Comment by TheSpyder** [comment]
@elshobokshy support for custom dialog sizes was removed in 5.x, there are indeed only three predefined size classes.
https://www.tiny.cloud/docs/migration-from-4x/#customdialogs

This was done for overall consistency, custom features fit much better within the TinyMCE UI, and also allows us to add features like responsive dialogs on mobile (which I believe happened with the 5.1 release).

**Comment by elshobokshy** [comment]
@TheSpyder some people, such as me, don't care about the plugin being responsive as they're using it in an admin panel only used on computers by our clients. I had to use custom CSS sadly. Thank you anyway.

**Comment by TheSpyder** [comment]
Yeah, I get it, but this is the decision we made and instead we offer a fully customisable theme (hopefully we'll release our theme builder soon which will make customising much easier).

**Comment by lofcz** [comment]
I don't agree with the solution by TinyMCE team in this case. Limiting developers liberty is generally frowned upon. 

In order to set a custom size of your dialog:

```js
editor.ui.registry.addButton { // or addMenuItem
    onAction: function() {
        setTimeout(function () {
            $(".tox-dialog__body-content").css("height", "400px"); // or width
        });
    }
}
```

As of version 1ac52053224165998fe49b7d5d2d6236fa7f94ab (5.2 / 5.3 dev)

**Comment by PululuK** [comment]
You can use `minWidth` and `maxHeight`

```js
editor.windowManager.open({
  title: 'Test',
  body: {
    type: 'panel',
    multiline: true,
    minWidth: 1200,
    maxHeight: 600,
    items: []
  },
  buttons: []
});
```
