### ISSUE TITLE
Powerpaste copy from editor then paste to editor bug

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#4855]
Report bug

I copy and text from editor, then paste to the same editor and get text with '\n\n' in the end.

Steps to reproduce the bug
1.Type some text (for example 'Hello world').
2.Copy that text by ctrl+v or context menu or any other way you can copy text.
3.Paste text near.

demo here: https://www.tiny.cloud/docs/demo/full-featured/#

Expected behaviour: 
If i copy text Hello world, I want to get 'Hello world' in event.content, but getting 'Hello world\n\n';

TinyMCE 4.9 TinyMCE 5.x Chrome version 72.0.3626.119

**Comment by lnewson** [comment]
Powerpaste is a premium plugin and as such isn't something supported via GitHub. If you have an issue with a premium product, can you please log a support ticket were our support team will be able to help in better detail: https://www.tiny.cloud/docs/enterprise/support/

**Comment by varaprasad7007** [comment]
Well it's because when you give space or taken extra space then those \n and \nsb will come. it can be eliminate with merge option
