### ISSUE TITLE
Can we have an NPM package for the source files?

### ISSUE THREAD

**Issue by Shepard** [tinymce/tinymce#4857]
At the moment when running `npm install tinymce` you get the code from the tinymce-dist project here on Github. This only contains the pre-bundled distribution files.

It would be nice if we could install an NPM package pointing to this source project instead.
The main advantage would be (I hope) that when importing it as ECMAScript modules we can apply strategies like tree shaking to get the file size of tiny down (which imo is sorely needed for this code monster).
Another advantage would be source map generation so tiny code can be easily debugged on a website including it.

Thoughts?

**Comment by fyrkant** [comment]
You won't be able to tree shake anything away, we already use rollup in the build step to create as small files as possible.

**Comment by TheSpyder** [comment]
I don't think we can reasonably publish this to NPM. We already have a [developer zip available to download](https://www.tiny.cloud/get-tiny/self-hosted/) which is what this package would contain, and if you look at it a problem quickly becomes apparent; there isn't a single source file you can import to get the entire bundle. We have separate bundles for the core, theme, and each plugin.

We are aware that v5 is quite a bit larger than v4 (although it does gzip very well so it's not as bad as it looks on the filesystem). As @fyrkant said we already use rollup's tree shaking mode, and finding ways to reduce the code size increase we took on board with this release is absolutely a long term technical debt goal.

Turning on source maps in the existing distribution should be easy. I'm happy to prioritise that for you.

**Comment by Shepard** [comment]
Thank you for your consideration. I realise now that tree shaking is an entirely static analysis. See, I thought maybe there could be some way to get rid of code that is not actually in use in the way you integrate TinyMCE, e.g. by how you initialise the editor. But that can't be solved with static analysis because it's dynamic. And you basically already provide a solution for that in the form of plugins.

But yeah, turning source maps on in the distribution build would be great. :-)

**Comment by Afraithe** [comment]
Thank you Shepard for the feedback, closing this now.
