### ISSUE TITLE
上传图片后，不想图片自动加宽和高，应该怎么配置？

### ISSUE THREAD

**Issue by hulang** [tinymce/tinymce#4859]
英语基本是菜，只能中文发了。。
![qq 20190302111736](https://user-images.githubusercontent.com/4961831/53676427-13d9f180-3cdd-11e9-918a-9c00dd35ab76.png)
> 不想图片自动加宽和高。。下面是我的配置
`<form action="post.php" method="post">
    <textarea name="info" id="info" style="width:98%;height:400px;"></textarea>
    <input type="submit" value="提交">
</form>
<script type="text/javascript">
$(function() {
    tinymce.init({
        language: 'zh_CN',
        selector: '#info',
        plugins: 'print preview searchreplace autolink directionality code visualblocks visualchars fullscreen image link media codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools  contextmenu colorpicker textpattern help',
        // menubar
        menubar: 'file edit insert view format table tools help',
        // numlist bullist outdent indent
        toolbar: 'undo redo | formatselect | fontselect | bold italic strikethrough forecolor backcolor | link image | alignleft aligncenter alignright alignjustify | removeformat codesample code | fullscreen',
        images_upload_url: 'upload.php',
        paste_data_images: true,
        images_upload_credentials: true,
        // 自动把内容同步到文本框
        init_instance_callback: function (editor) {
            editor.on('Change', function (e) {
                tinymce.triggerSave();
            });
            editor.on('blur', function (e) {
                tinymce.triggerSave();
            });
        }
    });
});
</script>`

**Comment by lnewson** [comment]
Thanks for the report, but unfortunately we can only provide help for tickets logged in English. As such I'm going to close this, but please feel free to re-log your issue if you're able to find someone to translate.
