### ISSUE TITLE
How to add your own code between the toolbar and the content？

### ISSUE THREAD

**Issue by kwdiwt** [tinymce/tinymce#4860]
![image](https://user-images.githubusercontent.com/7121840/53689850-f323a180-3d99-11e9-94b2-b4b9419b293d.png)

**Comment by lnewson** [comment]
I'm not quite sure what you mean by "code", but it seems as though you want to manipulate the dom and add your own element after the toolbar, but before the editor content? While your results may vary from doing that, as it's not supported, you should be able to do any dom manipulation by adding your logic to the `init_instance_callback` setting: https://www.tiny.cloud/docs/configure/integration-and-setup/#init_instance_callback (or alternatively by binding to the `init` event via editor.on('init', ...))
