### ISSUE TITLE
TinyMCE 5: Styleselect button issue in mobile toolbar

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4863]
I'm using Chrome on desktop in mobile mode.

I see some buttons do not use svg (yet?), but font-icons. Styleselect is one of them. Problem is that this button has active state (`.tinymce-mobile-toolbar-button-selected`). In this state the icon is invisible. It's because the color used for `background` and `color` style are not distinguishable.

**Comment by lnewson** [comment]
I can replicate this and it seems to be a v5 specific issue so I'm not sure what was changed there. I'll log a task to investigate.

**Comment by TheSpyder** [comment]
The mobile theme is not used by default in version 5.1 and has been deprecated. This doesn’t impact the silver theme on mobile.
