### ISSUE TITLE
TinyMCE 5: Input's of type "input"

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4866]
I see that input elements in TinyMCE dialogs have type attribute set to "input" instead of "text". That's not a valid value.

**Comment by lnewson** [comment]
Oh wow, that's embarrassing. Thanks for picking that up, I'll get it fixed up today, so it can get included in the next release.

**Comment by lnewson** [comment]
This should now be fixed in 5.0.2. Please let us know if you find any further problems!
