### ISSUE TITLE
TinyMCE 5: Issue with re-styling form elements

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4867]
I wanted to re-style some elements using javascript. I'd like to replace `.tox-textfield` with Bootstrap's `.form-control`. And I see that's not that easy, because kind of "reset styles" in TinyMCE cause every element in TinyMCE UI ending up with many unwanted styles (with high prio). These styles come from `.tox :not(svg)` rule(s).

Is it really needed? I see not much difference in the UI if I get rid of all these styles.

**Comment by lnewson** [comment]
If you're restyling the UI to that degree you really should be using a custom skin. The reset styles in the default skin (oxide) specifically exist, to make sure no styles from parent elements seep in, which can then cause the skins to look different depending on where the editor is used.
