### ISSUE TITLE
TinyMCE 5: DIfferent vertical spacing in tabbed and non-tabbed dialogs

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4868]
Check Link dialog and Image dialog. The link dialog uses much more spacing between form elements.

Probably `.tox .tox-form__group` should use consistent `margin-top: 8px;` everywhere. The tabbed forms are too condensed, imo.

**Comment by lnewson** [comment]
This looks like it's probably a bug, as the rule that's adding the spacing is `.tox .tox-dialog__body-content>*` which wouldn't work in the tab panels. I'll pass it on to our design team to review.

**Comment by alecpl** [comment]
I see in 5.0.3 the spacing is the same everywhere. However, I think current 4px is too small value. It looks better with 8px.

**Comment by lostkeys** [comment]
If you want a larger spacing you can [create a custom skin](https://www.tiny.cloud/docs/advanced/creating-a-skin/) and use the variable `@form-group-vertical-spacing` to make the spacing larger.

**Comment by alecpl** [comment]
Fair enough, I hope you considered bigger spacing as 8px was used in some places before. Now, you use 4px everywhere. Imo, too small.

**Comment by lostkeys** [comment]
Yes, it's a matter of taste, and as we know taste differs wildly, we have built extensive skinning capabilities into Oxide so developers can style it into their liking. Here is an example of what you can do with the toolbar: 
![Screenshot 2019-06-10 at 11 33 50](https://user-images.githubusercontent.com/3122929/59186855-3ef19e00-8b74-11e9-89b3-6667d2be2abd.png)
