### ISSUE TITLE
TinyMCE 5: plugin files "404 not found"

### ISSUE THREAD

**Issue by jzabate** [tinymce/tinymce#4870]
Error

404 not found

Per google dev tool, plugin.js for almost all tinymce plugin and theme.js for the theme are not found.

version 5

**Comment by lnewson** [comment]
Can you please provide an example, or way to replicate? as if you're getting 404's then it's likely a configuration or setup issue.

**Comment by jzabate** [comment]
I just updated my zendframework 2 application that are using tinymce 4.7.2 community edition to version 5. And somehow and error occurred that almost all the tinymce plugin failed to initialized and it requires plugin.js and the only files under the specific plugin folder is only the minified version.

I already solve this issue by downloading the tinymce dev package where plugin.js and plugin.min.js is found.

**Comment by TheSpyder** [comment]
Did you previously use the dev package, or is there a distribution that included the developer files with v4 and no longer does with v5?

**Comment by jzabate** [comment]
I use the "Download TinyMCE Community" for v4 and now the v5 and when the issue occur I've download the dev package and there I found out the uncompressed version of the plugin's js and added it through.

**Comment by TheSpyder** [comment]
OK. Yes for future reference the unminified `.js` files are not shipped in the "TinyMCE community" production download, only the `.min.js` files. You need the dev package if you want unminified files.
