### ISSUE TITLE
content inside an iframe - position wrong

### ISSUE THREAD

**Issue by Marcel-a** [tinymce/tinymce#4871]
Problem:
I want to use TinyMCE to inline-edit a website, which is inside an iframe. TinyMCE is called outside of the iframe.
The toolbar position seems to be calculated relative to the document inside the iframe. But is positioned relative to the document outside the iframe. So the toolbar appears on the wrong position and is not affected by scrolling inside the iframe.

![image](https://user-images.githubusercontent.com/38622815/53733213-9ea72180-3e80-11e9-8f22-2e7ff84884d8.png)

Demo: http://fiddle.tinymce.com/wDgaab

**Comment by Vmadmax** [comment]
Same issue here. 
And the editor isn't working normal. On inserting any style, for example bold, the editor is adding a new line above the content.

![video](https://user-images.githubusercontent.com/1713226/55159788-1f94c880-5162-11e9-93ef-9e979cd75b4b.gif)

**Comment by juneapp** [comment]
Same issue in my project. It it possible to add a window/document configuration for the toolbar?
