### ISSUE TITLE
Modern theme is not installed by latest tinymce npm package

### ISSUE THREAD

**Issue by bhaidar** [tinymce/tinymce#4872]
*Bug*

**What is the current behavior?**
When I install the latest `tinymce` package using `yarn add tinymce` command, the theme folder has only mobile and silver themes. Modern theme is not installed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
In an angular-cli project, run `yarn add tinymce`.

**What is the expected behavior?**
To find modern theme inside node_modules/tinymce/themes folder

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I switched back to tinymce = '4.7.4`

The tinymce 5.x.x is failing to install modern theme.

**Comment by lnewson** [comment]
This is expected, as the latest version is 5.x which contains a completely different UI system, etc... with a new theme called "Silver". The migration guide has a lot more details on the breaking changes between 4.x and 5.x: https://www.tiny.cloud/docs/migration-from-4x/

If you need the modern theme, then you shouldn't be installing the latest version and should install 4.x from npm.
