### ISSUE TITLE
Feature having more then one column in dropdown 

### ISSUE THREAD

**Issue by deep0410** [tinymce/tinymce#4873]
**Feature**

currrent behaviour: one straight lines in addMenuButton

**What is the expected behavior?**
Being able to pass 2D array to callback(items) for addMenuButton. That will have columns of options instead of sub menu options.

**Comment by lostkeys** [comment]
@deep0410 I know this was some time ago, but we're revisiting older feature requests and in order to be able to judge the benefit of your feature request I'd like to know some more about the problem you would solve with your suggestion. Thanks.

**Comment by yacodes** [comment]
We are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
