### ISSUE TITLE
After uploading pictures, I don't want to automatically get the values in the wide and high text boxes. 

### ISSUE THREAD

**Issue by hulang** [tinymce/tinymce#4874]
5.0.1
After uploading pictures, I don't want to automatically get the values in the wide and high text boxes. Just leave the wide and high text boxes empty. How should I configure them?
![qq 20190305150534](https://user-images.githubusercontent.com/4961831/53786934-26ac2a80-3f58-11e9-87ab-81eec406132f.png)
As shown above, I want the values of wide and high text boxes to be empty.

**Comment by hulang** [comment]
I send English through translation software, there may be errors, that is, after uploading pictures, the value of the wide and high text box is empty, how should I configure it?

**Comment by lnewson** [comment]
Thanks for logging a new issue in English, it's appreciated. To answer your question, unfortunately there is no way to show the width/height field and not have it populate the image dimensions when selecting an image.

The best thing I can suggest, which may not be what you want, is to disable the image dimension fields by setting `image_dimensions: false` in your init settings.

**Comment by hulang** [comment]
@lnewson Thank you. That's exactly what I want.

**Comment by hulang** [comment]
@lnewson https://www.tiny.cloud/get-tiny/language-packages/
Chinese (China) | zh_CN | 98%
Hope to be 100% as soon as possible, just a few.

**Comment by lnewson** [comment]
@hulang the translations are actually community sourced, so if you're able to we'd certainly welcome and appreciate any contributions.

To submit a translation, you need to first create transifex account and then go to https://www.transifex.com/tiny/tinymce/. On that page, you should see a "Join team" button in the top right, which if you click it, you should be able to select Chinese from the language list and then click "Join". Once you're part of a language team, then you should be able to add translations for that language.
