### ISSUE TITLE
Selection bug

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#4875]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If i type one part of word as default format and other part with bold, when i start to select editor will select full word
![screencast-www tiny cloud-2019 03 05-10-44-02](https://user-images.githubusercontent.com/33262949/53788808-db802080-3f33-11e9-987c-6fe39ad1e959.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://www.tiny.cloud/docs/demo/full-featured/

**What is the expected behavior?**
Editor must not change my selection

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.* 5.*

**Comment by lnewson** [comment]
I can replicate this using Firefox, IE or Edge, however I'm unable to replicate this in Chrome and Safari. I'll log a task for us to investigate what's causing the different behaviour.

**Comment by versusvirus** [comment]
> I can replicate this using Firefox, IE or Edge, however I'm unable to replicate this in Chrome and Safari. I'll log a task for us to investigate what's causing the different behaviour.

I replicate it in any browser even in Chrome 72 version
