### ISSUE TITLE
TinyMCE 5.0.1 *feature* dialog/ input element with id/name attributs

### ISSUE THREAD

**Issue by stastka** [tinymce/tinymce#4880]
I try to migrate my own plugin to new TinyMCE 5.x.  Following Problem i have:
 * i would like add dynamicly class to parent div (dialog). i make with jquery a hack:
on open/close
`$("div.tox").addClass("dialog-xxl");`
`$("div.tox").removeClass("dialog-xxl");`
* i would like have a name attribut for input to fill up from seperate page. Sample. I have a iframe with logical code in c#. How i can update parent input-form? the generated code from tinyMCE missing name-attribut and id is random.
`{
type: 'htmlpanel',
html: '<iframe width="100%" src="'+url+'/test.aspx' + '?&amp;key=' + new Date().getTime() + '" frameborder="0"></iframe>',
},`

**Comment by lnewson** [comment]
There's already issues for both of these, so I'm going to close this as a duplicate:
- Classes: https://github.com/tinymce/tinymce/issues/4761
- URL Dialog support: https://github.com/tinymce/tinymce/issues/4786

Note: For the last point, I wasn't 100% sure what you meant for that, but if you wanted to update a field in the dialog instead, then you need to use the dialog `api.setData()` function, as in v5 you don't update values directly via elements.

**Comment by TheSpyder** [comment]
Note that regarding point 1 if you just want to make the dialog bigger, you can set `size: 'large'` on the dialog config which I think still isn't documented.
