### ISSUE TITLE
Custom UI button: Button Image is not shown

### ISSUE THREAD

**Issue by it4need** [tinymce/tinymce#4882]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Currently, if I add an image link (relative or absolute) to a custom UI button, no image is shown.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/6Dgaab - Add a call to editor.ui.registry.addButton with image property. 

**What is the expected behavior?**
The image should be visible.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Previous version: don't know
All browsers

**Comment by lnewson** [comment]
As per the docs https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/#basicbutton image isn't a valid field for adding a button in v5, you need to use an icon. So when adding a custom button you then need to specify the `icon` field and use a name of a registered icon. You can register an icon via the `editor.ui.registry.addIcon(name, svgData)` function.

This previous asked question maybe useful to you as well: https://github.com/tinymce/tinymce/issues/4604
