### ISSUE TITLE
[5.x] Can not select emoticons or special characters on iOS or Android

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4883]
**bug**
Can not select emoticons or special characters on iOS or Android

Window for selection of emoticons or characters is displayed, but while touching for selection nothing happened.
Nevertheless when touch on close button the selection window is closed as expected.

With full featured demo.
iPad and Android Smartphones.

**Comment by lnewson** [comment]
Verified that on tablets clicking on the collection items doesn't work. I suspect this isn't binding a tap event and therefore not triggering the onAction callback.

**Comment by wonderbugtiny** [comment]
This should now be fixed in 5.0.3. Please let us know if you find any further problems!
