### ISSUE TITLE
Is there a plan to support the use of Silver theme on mobile?

### ISSUE THREAD

**Issue by ani2life** [tinymce/tinymce#4884]
I was used to create TinyMCE 4 plugin. And I re-created the plugin for TinyMCE 5.
I have to provide the same environment to my customers on desktop and mobile.
However, the silver theme does not work properly on mobile. So I have to downgrade to TinyMCE 4.

Is there a plan to support the use of Silver theme on mobile?
If you do not have a plan, I will have to change to another WYSIWYG editor in the future.

**Comment by lnewson** [comment]
@ani2life could you prove a bit more detail, when you say "does not work properly"? As the default theme (modern) in TinyMCE 4 doesn't support mobile either and you instead need to use the mobile theme if you wanted something that worked on mobile, which should be the same as v5 except that in v5 the mobile theme is enabled by default for mobile devices.

To actually answer your original question though, yes we do plan on improving mobile support in v5, but unfortunately we don't have a schedule for that at this stage.

**Comment by ani2life** [comment]
@lnewson On mobile, the modern theme of TinyMCE 4 has a longer editing area as the text gets longer. However, the silver theme of TinyMCE 5 is fixed in height and can not be edited if the text becomes longer.

**Comment by TheSpyder** [comment]
For the record, in TinyMCE 5.1 we are aiming to adjust the Silver theme such that it is responsive for mobile use and deprecate the mobile theme for use on older devices only.
