### ISSUE TITLE
Trying to load theme when skin: false

### ISSUE THREAD

**Issue by sam-s4s** [tinymce/tinymce#4886]
**Bug**

**Current behaviour:**
When specifying `skin: false` in the config object, it should not try to load any skins or themes. As I'm running tinymce locally, it will never find the theme files.

**What is the expected behavior?**
It should not try to load any themes.

This seemed to work when it was in cloud mode (but took 5-10 seconds to load, way too long). I am now including tinymce directly in my angular.json file, as follows:
```
"scripts": [
    "node_modules/tinymce/tinymce.min.js"
]
```

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
"tinymce": "4.8.5",
"@tinymce/tinymce-angular": "2.3.1",

**Comment by lnewson** [comment]
You've got this a bit backwards as need to set `theme: false` if you don't want it to load the theme or skin, not the other way around.

**Comment by lnewson** [comment]
I'd also be curious to know what exactly you are trying to do, such that you'd want both the theme and skin disabled? I could understand the skin, but the theme is a bit odd. Are you trying to load the themes locally instead or import them via TypeScript (similar to https://github.com/tinymce/tinymce/issues/4826)?

If so, then you should just need to add the import/script tag before the TinyMCE init call so that the theme is registered with TinyMCE and it won't try to load the theme from an external js file.

**Comment by sam-s4s** [comment]
Thank you @lnewson , you have shown me that my issue is incorrect :)
I think I am unsure what I require.

I just want the bare minimum for tinymce to function locally (no cloud functionality, as it is running inside an intranet).

So I've set:
```
content_css: '/app/assets/tinymce-content.min.css'
```
of which I am exporting to my assets folder.

And now I'm not sure how to make the editor function without having to download any fancy skins or themes (but I understand I may need to specify a theme, if one is not included with tinymce by default?)

Ideally I'd just have the tinymce script file, and a small css file - but that does not appear to be the case anymore?

**Comment by lnewson** [comment]
The `silver` theme is the default theme included as part of TinyMCE, however it is a separate JS file. You can generate a single JS bundle if needed, by downloading the source and following the steps in the README: https://github.com/tinymce/tinymce/blob/master/readme.md#bundle-themes-and-plugins-into-a-single-file (Note: There is currently an issue with the emoticons plugin when bundling to a single file, if you need that: https://github.com/tinymce/tinymce/issues/4847)

However if you don't need it bundled to a single file, then you should be able to get the minimum (no plugins, etc...) working via something like the following (assuming you've installed the tinymce package from npm). That'll load the core editor, default theme and skin locally, without trying to use any resources from the cloud.

```
<!DOCTYPE html>
<html>
<head>
<title>TinyMCE Minimal Example</title>
<link rel="stylesheet" href="./node_modules/tinymce/skins/ui/oxide/skin.min.css" />
<script src="./node_modules/tinymce/tinymce.min.js"></script>
<script src="./node_modules/tinymce/themes/silver/theme.min.js"></script>
</head>
<body>
<textarea></textarea>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    skin: false,
    content_css: '/app/assets/tinymce-content.min.css'
    // Use the following instead if you want to include the default content css
    // content_css: ['./node_modules/tinymce/skins/ui/oxide/content.min.css']
});
</script>
</body>
</html>
```

Note: I should add that really the tinymce.min.js file should be the only thing needed and you could remove the `skin: false` setting. As TinyMCE will try to load the theme, skin, etc... relative to the tinymce script. I only used the above, to show what files it would normally load itself. You can also disable the toolbar/menubar by setting them to false in the init.

Hopefully that helps clear things up and gives you what you need.

**Comment by sam-s4s** [comment]
Sorry Lee I'm still a bit confused...
I'm getting a 404 for https://localhost:5001/app/themes/modern/theme.js
Which of course doesn't exist. I'm running a packaged (webpack) environment (angular 7).
My output directory has only bundled js files, of which "scripts.js" includes "node_modules/tinymce/tinymce.min.js", as is specified in my angular.json file (I don't know if you're familiar with angular or not? But that probably complicates the issue haha)

**Comment by lnewson** [comment]
@sam-s4s which Angular project are you using and which TinyMCE version are you wanting to use? Just asking as the modern theme is from v4, while the example I gave above was for the latest version (v5). If you can provide those details, I should be able to create a better/more applicable example for you.

To answer your last question though, you basically need to make sure the theme and plugins you're trying to use has been loaded (either as part of a bundle or separately) before `tinymce.init` is being called. As otherwise it'll only try to load remotely, if the theme/plugin, etc... hasn't already been registered.

**Comment by sam-s4s** [comment]
Oh right, there's a new version, I'll grab that so we're on the same page.
I'm using Angular 7, and the official tinymce/tinymce-angular component.

Quick question... is there a relation to the skin and the theme?
`"node_modules/tinymce/skins/lightgray/skin.min.css"`
`"node_modules/tinymce/themes/silver/theme.min.js"`

**Comment by lnewson** [comment]
Yes there is, `lightgray` is the skin that supported the v4 modern theme and `oxide` is the new skin for the silver theme.

**Comment by sam-s4s** [comment]
Oh dear, my plugins have all broken :')
I'll have to pull those scripts in too I think lol
Is that the thing to do? All of these little scripts that it tries to pull in after loading... I just include them in my build one by one, and then it won't try to load them?

**Comment by sam-s4s** [comment]
Ok thanks to your help I got it working :D Excellent!

I'll put my stuff here so that anyone else in the same situation can get theirs working too...

package.json
```
"@tinymce/tinymce-angular": "3.0.0",
"tinymce": "5.0.2"
```

angular.json
```
"styles": [
    "app/index.scss",
    "node_modules/tinymce/skins/ui/oxide/skin.min.css"
],
"scripts": [
    "node_modules/tinymce/tinymce.min.js",
    "node_modules/tinymce/themes/silver/theme.min.js",
    "node_modules/tinymce/plugins/advlist/plugin.js",
    "node_modules/tinymce/plugins/code/plugin.js",
    "node_modules/tinymce/plugins/image/plugin.js",
    "node_modules/tinymce/plugins/link/plugin.js",
    "node_modules/tinymce/plugins/lists/plugin.js",
    "node_modules/tinymce/plugins/searchreplace/plugin.js",
    "node_modules/tinymce/plugins/wordcount/plugin.js",
    "node_modules/tinymce/plugins/paste/plugin.js",
    "node_modules/tinymce/plugins/table/plugin.js",
    "node_modules/tinymce/plugins/autoresize/plugin.js"
]
```

config:
```
skin: false,
content_css: '/app/assets/tinymce-content.min.css'
```

**Comment by lnewson** [comment]
Awesome, glad to hear you got it working! Also thanks for including you final configuration. I'll see what I can do about getting something better documented.

**Comment by sharansp** [comment]
> Ok thanks to your help I got it working :D Excellent!
> 
> I'll put my stuff here so that anyone else in the same situation can get theirs working too...
> 
> package.json
> 
> ```
> "@tinymce/tinymce-angular": "3.0.0",
> "tinymce": "5.0.2"
> ```
> 
> angular.json
> 
> ```
> "styles": [
>     "app/index.scss",
>     "node_modules/tinymce/skins/ui/oxide/skin.min.css"
> ],
> "scripts": [
>     "node_modules/tinymce/tinymce.min.js",
>     "node_modules/tinymce/themes/silver/theme.min.js",
>     "node_modules/tinymce/plugins/advlist/plugin.js",
>     "node_modules/tinymce/plugins/code/plugin.js",
>     "node_modules/tinymce/plugins/image/plugin.js",
>     "node_modules/tinymce/plugins/link/plugin.js",
>     "node_modules/tinymce/plugins/lists/plugin.js",
>     "node_modules/tinymce/plugins/searchreplace/plugin.js",
>     "node_modules/tinymce/plugins/wordcount/plugin.js",
>     "node_modules/tinymce/plugins/paste/plugin.js",
>     "node_modules/tinymce/plugins/table/plugin.js",
>     "node_modules/tinymce/plugins/autoresize/plugin.js"
> ]
> ```
> 
> config:
> 
> ```
> skin: false,
> content_css: '/app/assets/tinymce-content.min.css'
> ```
> 
> (you have to copy `node_modules\tinymce\skins\content\default\content.min.css` to your assets directory as part of your build process)

Thanks It worked :-)

**Comment by TheSpyder** [comment]
Extensively.
https://www.tiny.cloud/docs/tinymce/6/introduction-to-bundling-tinymce/
