### ISSUE TITLE
Font size select does not work correctly in jquery ui modal

### ISSUE THREAD

**Issue by csharperperson** [tinymce/tinymce#4889]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Fontsizeselect does not work correctly in jquery ui modal. You can select a font size, then type in that specified font size. However, if you highlight existing text and try to change the font size, it jumps to the first line and uses the font size there.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via fiddle.tinymce.com or similar.
[Demo](http://fiddle.tinymce.com/FDgaab/1)

What is the expected behavior?
Expected behavior should be the same as when the fontsizeselect is not in the modal

Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?
Tested this in all 5.x versions of TinyMCE on Chrome and IE 11. It works on Chrome, but not IE 11 on versoin 5.x

**Comment by lnewson** [comment]
@csharperperson like in https://github.com/tinymce/tinymce/issues/4878 this seems to just be an issue where we've unfortunately missed adding the new class selector to the docs, as adding that seems to fix this issue as well: http://fiddle.tinymce.com/FDgaab/2

**Comment by lnewson** [comment]
I'm going to close this, as it appears to be working after adding the additional selector and we've also merged a change to the docs for the next docs release: https://github.com/tinymce/tinymce-docs/pull/982

If it's still not working for you after making that change, let us know and we'll reopen and investigate further.
