### ISSUE TITLE
TinyMCE 5: Insert custom button on Insert/Edit Link dialog and add a custom css selector for insert/edit toolbar button.

### ISSUE THREAD

**Issue by jzabate** [tinymce/tinymce#4890]
feature/guide/question

I'm trying to modify the contents of the Insert/Edit Link dialog box when clicking on insert/edit link toolbar button.

I want to accomplish of inserting a custom button beside browse url in button.

I'm using TinyMCE v5

**Comment by alecpl** [comment]
Looks like another case for use of undocumented `OpenWindow` event.

**Comment by jzabate** [comment]
I tried to check the link plugin documentation but haven't found any solution to this problem.
https://www.tiny.cloud/docs/plugins/link/

**Comment by wonderbugtiny** [comment]
@jzabate We do not currently have settings to insert custom ui components into dialogs. You could extend the code and add the features/ui components that you wish to include inside the dialogs.

Alternatively, if you have a specific button/functionality that you would like as a feature within the Insert/Edit Link dialog, you can make a feature request for that and we could consider adding it officially. Please let us know if you have any further concerns.

> add a custom css selector for insert/edit toolbar button
With respect to this part of the question, could you please explain further on what exactly is your requirement. Thank you.

**Comment by jzabate** [comment]
I already solve the second part. The first part is what I needed to accomplish. I'll try what I can do and check around.

**Comment by joachimdoerr** [comment]
Hello @wonderbugtiny there a an in the future an extension for ui elements is planned?

**Comment by wonderbugtiny** [comment]
@joachimdoerr We plan to include support for custom UI components in the future. Please let us know what are the specific use cases you would like to utilize this feature for. This will help us decide on the design and implementation of relevant APIs. Thank you.

**Comment by joachimdoerr** [comment]
@wonderbugtiny i need a second custom button like the URL button. I have 2 CMS link types, one for internal links and one for media links.

**Comment by alexwenz** [comment]
+1 for the "second custom button like the URL button"

**Comment by jzabate** [comment]
+1 also on the "second custom button like the URL button".

For my part, I want a secondary button beside the URL button for related links: pop ups modal of site's tree view of the page links.
