### ISSUE TITLE
Insert link  also insert '/'

### ISSUE THREAD

**Issue by plainnany** [tinymce/tinymce#4891]
TinyMcE: 5.0.1

when I insert link, I find before link added path '/'

insert link
![image](https://user-images.githubusercontent.com/27320655/54250378-8456fd00-457e-11e9-8b11-a1a79034f08f.png)
when I edit this link again or preview source code, I find url  added '/'
![image](https://user-images.githubusercontent.com/27320655/54250444-c2542100-457e-11e9-9650-636b42e6dcc2.png)

I want the link save as my edit content, so how?

**Comment by lnewson** [comment]
@plainnany can you please include a fiddle to reproduce this, as I'm unable to using the default configuration: http://fiddle.tinymce.com/NDgaab

**Comment by plainnany** [comment]
@lnewson because I set `relative_urls: false`, I will close this issue, sorry

**Comment by lnewson** [comment]
Ahh, yeah that'd do it since it'll try and convert all links, etc... to absolute urls.
