### ISSUE TITLE
preview_style setting is not working

### ISSUE THREAD

**Issue by ivanrakovic** [tinymce/tinymce#4893]
Setting preview_style to false in tinymce.init doesn't change the display of previewing the styles listed in the menu.
I've tried this functionality on official code pen example from the website.

**Comment by lnewson** [comment]
@ivanrakovic this appears to be working fine for me, here's a fiddle with an example: http://fiddle.tinymce.com/XDgaab One thing to double check, based on you comment, is to make sure you're using `preview_styles` (note the 's' at the end) and not `preview_style` which isn't a valid setting: https://www.tiny.cloud/docs/configure/editor-appearance/#preview_styles

If that still isn't working, then can you please include an example showing how to replicate the issue and any additional details such as what browser you can replicate with?

**Comment by ivanrakovic** [comment]
Thanks, looks it was a typo error. 
I will close the issue.
