### ISSUE TITLE
TinyMCE 4: Formatter.apply and remove doesn't work at the start or end of a tag.

### ISSUE THREAD

**Issue by Hazzard13** [tinymce/tinymce#4896]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Using Formatter.apply or remove at the start or end of a tag does nothing:
![Demonstration](https://user-images.githubusercontent.com/7453558/54452620-56b3b480-4734-11e9-9c69-98aba2cdfa21.gif)

The guide in the bottom right shows the correct tag, indicating the plugin should work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Here's a basic [fiddle](http://fiddle.tinymce.com/nEgaab). To see the issue at play, simply click in the middle of the string, and test that Adding and Removing animations work. Then try the beginning or end of the string, and see that they don't. The same issue occurs with list items, and any other tag I've tested.

**What is the expected behavior?**
Formatter.apply should apply to the current tag as represented in the bottom right, no matter where the cursor is positioned in that tag.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This issue is in the current latest Tinymce 4: 4.9.3. I don't know about other versions.

**Comment by wonderbugtiny** [comment]
This is intended, the formats are only appied to the current selection or when the cursor position is at the middle of the text node and not at the starting or end. This is the same behaviour in ms word and other common text editors as well. Please let us know why you feel the above should work as per your description.

**Comment by Hazzard13** [comment]
> Please let us know why you feel the above should work as per your description.

I think the primary reason this feels like a bug is this indicator:
![Screen Shot 2019-03-18 at 9 06 16 AM](https://user-images.githubusercontent.com/7453558/54528911-213ddf80-495d-11e9-8638-fbf49120f95d.png)

The editor clearly indicates that I have this tag selected, so when I try to use a plugin to affect that tag, it's rather jarring when nothing occurs. We received this as a bug report from a client, and not a single member of our team assumed this was an intentional design choice, likely due to the clear indication that the tag was selected. Especially since I can even use it to select a higher tag, and with this implementation, I still cannot affect this element:

![Recording](https://user-images.githubusercontent.com/7453558/54529590-0ff5d280-495f-11e9-888b-59d39f379fb8.gif)

I think your explanation makes sense for a word document with a hidden underlying structure, but tinymce is an HTML editor, and (for good reason) exposes some of that underlying structure to its users, making this implementation feel broken.

**Comment by wonderbugtiny** [comment]
Thank you for explaining your expectation in detail. When you are using selector formats instead of block formats, you can use the `block_expand` setting to achieve what you want to do here. `block_expand` is a content formatting setting which when set to true will include the matching block while selection starts at the beginning of a matching block.

Please find below the link where, the setting is documented and here is a [fiddle](http://fiddle.tinymce.com/nEgaab/2) to demonstrate the same.
https://www.tiny.cloud/docs/configure/content-formatting/#block_expand
Please let us know if this solves the issue for you.

**Comment by Hazzard13** [comment]
That's perfect. I've implemented this, and it behaves exactly as I suspected. I might still assert that this should be default, but I'm more than happy to simply apply this setting to my formats in the meantime.

Thanks so much.
