### ISSUE TITLE
how to set inline code in toolbar

### ISSUE THREAD

**Issue by plainnany** [tinymce/tinymce#4898]
tiny version : 5.0.1

 I want to set inline code in toolbar, just as same as menubar -> format -> code, and I set `menubar: false` because I don't want to display menubar, what I can do?

![image](https://user-images.githubusercontent.com/27320655/54520247-3dfd0600-49a3-11e9-801a-7667aeeb1f51.png)

**Comment by wonderbugtiny** [comment]
We currently do not have a default toolbar button for the 'format as code' option. Please note that you can register a custom toolbar button for it by following the steps in the documentation at: https://www.tiny.cloud/docs/ui-components/toolbarbuttons/#howtocreatecustomtoolbarbuttons. 

Also, here is a [fiddle](http://fiddle.tinymce.com/qEgaab/3) that shows an example of how to register a custom toolbar button. Please let us know if this was helpful for you.

**Comment by plainnany** [comment]
@wonderbugtiny the fiddle example is exactly what I want, thanks a lot. I will close this issue.
