### ISSUE TITLE
Inserting anchor in empty paragraph not working

### ISSUE THREAD

**Issue by WarwickGoatee** [tinymce/tinymce#4900]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you add an anchor in a blank paragraph it deletes the paragraph and doesn't put an anchor anywhere.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Create a new line by pressing enter. Without adding anything to the line, try to insert an anchor.

**What is the expected behavior?**
Ideally it'd create the anchor in the blank paragraph, showing its presence with the anchor icon as it does in paragraphs with content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.0.2 - replicated in the full featured example on your site.

**Comment by wonderbugtiny** [comment]
Thanks for the report! I can verify this on TinyMCE 5.0.2. I have escalated it internally and we will let you know when we have a fix.

**Comment by WarwickGoatee** [comment]
Awesome, thanks!

**Comment by ltrouton** [comment]
@WarwickGoatee 5.2.2 was released today which includes a fix for this. If you are still experiencing issues, please let us know and we'll re-open this issue.
