### ISSUE TITLE
Can not merge cells vertically

### ISSUE THREAD

**Issue by hxnam0509** [tinymce/tinymce#4901]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Can not merge cells in the same column

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
It is happening on tinymce demo site https://www.tiny.cloud/docs/demo/basic-example/

**What is the expected behavior?**
Be able to merge cells within a column

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- tinyMCE@5.0.2
- Browser: Chrome, MacOS
- It used to work in tinyMCE@4.9.1

![Screen Shot 2019-03-20 at 10 55 07 am](https://user-images.githubusercontent.com/7521193/54649656-35214700-4aff-11e9-8767-d1309b4d212c.png)
![Screen Shot 2019-03-20 at 11 01 36 am](https://user-images.githubusercontent.com/7521193/54649750-93e6c080-4aff-11e9-926b-182254db9a78.png)

**Comment by wonderbugtiny** [comment]
This is intended, The first row of the table in your example is comprised of table header cells that cannot be merged with table body cells. That wouldn't be valid html as you can only merge cells of the same type. I have logged an improvement internally to format the row with header cells differently from the body cells in our website demos. Please let me know if this answers your concerns.

**Comment by hxnam0509** [comment]
I see, thanks
