### ISSUE TITLE
[5.0.3] Wrong cursor position after insert on touch devices

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4902]
**bug:** Wrong cursor position after insert a item on touch devices

After selection of a item to insert (e.g. emoticon, special character or date/time) the item is inserted at cursor position as expected.
But the new cursor position is not behind the inserted item.
Instead the new cursor position depends on the position where the last touch event had been fired by selecting the item.

http://fiddle.tinymce.com/oCgaab/27#

- Tiny 5.0.3
- On iPad or Android devices
Even in Chrome debugger, when a touch device is selected for simulation

**Comment by wonderbugtiny** [comment]
Thank you for the report! I can confirm that this is a bug in Android. I have logged an issue internally to fix it. 
Also, please refer to our [note](https://github.com/tinymce/tinymce/issues/4884#issuecomment-470764623) on support for Silver theme on mobile.

**Comment by Georg-Git** [comment]
I do not know which version solved this bug - but with 5.0.6 I can not reproduce this bug anymore.
👍
