### ISSUE TITLE
Selects in dialogs do not accept translations

### ISSUE THREAD

**Issue by dioobr** [tinymce/tinymce#4904]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Selects fields in dialogs do not accept translation.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
Select values translated

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.0.3 / macOS 10.14.3 / Safari 12.0.3

![Screen Shot 2019-03-21 at 03 56 56](https://user-images.githubusercontent.com/16680429/54737178-811acd00-4b8d-11e9-8dcb-3bc953eb99a7.png)
![Screen Shot 2019-03-21 at 03 52 26](https://user-images.githubusercontent.com/16680429/54737179-81b36380-4b8d-11e9-81af-844fc7feeb8e.png)

**Comment by alecpl** [comment]
I confirm this issue.

**Comment by lnewson** [comment]
Thanks for the report! I can confirm that the strings in select box items aren't being passed through for translation. I've logged an internal issue for us to look into this.

**Comment by lnewson** [comment]
This has been fixed in 5.0.4, which has just been released. Please let us know if you find any further problems!
