### ISSUE TITLE
SVG bugs

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4909]
SVG support is maybe new in TinyMCE 5, I'm not sure. Anyway, I see some issues:

1. I can drop an svg image to the editor and select it or resize, but image tools (Edit image dialog) do not work at all. There's an error: "InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable".

2. Dropping an image into editor works in Firefox but not in Chrome.

3. Dropped svg image takes the whole editor width instead using ViewBox sizes defined in the image.

**Comment by SimonFc** [comment]
Hi @alecpl 
Unfortunately we don't support the use of SVGs at all so I'll be closing this issue.

**Comment by Afraithe** [comment]
Sidenote, SVGs are a huge security risk and we cant really see us supporting that. However, we should perhaps prevent the use more proper and actually warn about the dangers in the editor even.

**Comment by alecpl** [comment]
Yeah, some warning would be nice. You could probably also prevent from dropping/pasting svg into the editor.
