### ISSUE TITLE
How do I get up-to-date localization?

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4912]
I see that localization downloads are not up to date. E.g. Polish lang has been updated on 2019-02-14 according to Transifex, but the download is not up-to-date. The one from https://www.tiny.cloud/docs-4x/language/tinymce4x_languages.zip is from 2019-01-24. Hard to guess what date it is from for the standard "single language button" download.

So, please update languages more often. Or provide them via tinymce-dist repo and update on a release date.

Related tickets: #4485, #3616.

Oh, and btw, this is maybe a reason why there's quite a few "not localized label" tickets here.

**Comment by alecpl** [comment]
And maybe you could share a script to convert .po files from transifex to .js files. So, maybe I could do it by my own. Anyway, that looks like a common request so would be good to be addressed by you.

**Comment by wonderbugtiny** [comment]
Please note that the zip file linked in your description is for Tinymce 4 only. Translations on Transifex now target Tinymce 5 and can be downloaded [here](https://www.tiny.cloud/get-tiny/language-packages/)

**Comment by alecpl** [comment]
I know, I'm also using https://www.tiny.cloud/tinymce-services-azure/1/i18n/download?langs=pl and this gives my old file with 260 lines. According to Transifex it should have 368 strings.

BTW, there's two redirects that does not make sense:
```
$ wget https://www.tiny.cloud/tinymce-services-azure/1/i18n/download?langs=pl
--2019-03-27 15:08:24--  https://www.tiny.cloud/tinymce-services-azure/1/i18n/download?langs=pl
Resolving www.tiny.cloud (www.tiny.cloud)... 99.84.151.17, 99.84.151.128, 99.84.151.71, ...
Connecting to www.tiny.cloud (www.tiny.cloud)|99.84.151.17|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.tiny.cloud/tinymce-services-azure/1/i18n/download/?langs=pl [following]
--2019-03-27 15:08:25--  http://www.tiny.cloud/tinymce-services-azure/1/i18n/download/?langs=pl
Connecting to www.tiny.cloud (www.tiny.cloud)|99.84.151.17|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.tiny.cloud/tinymce-services-azure/1/i18n/download/?langs=pl [following]
--2019-03-27 15:08:25--  https://www.tiny.cloud/tinymce-services-azure/1/i18n/download/?langs=pl
Connecting to www.tiny.cloud (www.tiny.cloud)|99.84.151.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
```

**Comment by Afraithe** [comment]
Looking into it alecpl.

**Comment by Afraithe** [comment]
Seems to be a caching issue, we have an update coming out soon.

In the mean time, if you add some garbage to the end of the URL you bust the caching.
https://www.tiny.cloud/tinymce-services-azure/1/i18n/download?langs=pl&cache=nomore

**Comment by Afraithe** [comment]
This was fixed a while ago, we are also in the process of adding professional translation packages.
