### ISSUE TITLE
default_link_target not respected

### ISSUE THREAD

**Issue by doender** [tinymce/tinymce#4913]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Although the `default_link_target` is set to `_blank` and this option ('new window') is selected when creating a link, the target attribute is *not* set to `_blank`.
Here is a reproduction of the issue: http://fiddle.tinymce.com/LEgaab

**What is the expected behavior?**
default_target_link is respected.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
AFAIK it worked in previous versions 4.x

**Comment by jhaines** [comment]
Thanks for reporting this.  I've replicated the issue on TinyMCE 5.0.2 and have logged an internal issue accordingly.  We'll let you know when it's been fixed.

**Comment by Georg-Git** [comment]
When fixing this issue - what about security improvement:
when
target="_blank" then also:
rel="noopener" at least - and perhaps also
rel="noreferrer"

See [Google description of security issue and recommendation](https://developers.google.com/web/tools/lighthouse/audits/noopener)

**Comment by lnewson** [comment]
This has been fixed in 5.0.4, which has just been released. Please let us know if you find any further problems!

@Georg-Git as for the rel settings, `rel="noopener"` should already be getting set unless someone has set `allow_unsafe_link_target` to `false`. I just tested it now and it seemed to be working when creating a new link with `_blank` set at the target, but if it's not working for you, can I ask that you please log a separate issue for that?

**Comment by ultimagecko** [comment]
This issue does not seem to be resolved in 5.0.6. default_link_target is not always applied.

Links generated by autolink do not apply the default target attribute (they don't seem to apply any attributes).

There's a supposed fix for this in the Version 4.5.1 (2016-12-07) changelog: "Fixed so the default_link_target gets applied to links created by the autolink plugin." Maybe it has persisted through that.

**Comment by eschiebel** [comment]
In my application I set 
```
target_list: false,
default_link_target: '_blank'

```
and the generated anchor never has a target attribute .
