### ISSUE TITLE
TinyMCE 5: Popup toolbars mispositioned and misrendered when near edge of editor (distraction-free)

### ISSUE THREAD

**Issue by jordanade** [tinymce/tinymce#4915]
Even shows up on TinyMCE's own demo:
https://www.tiny.cloud/docs/demo/editor-dfree/

<img width="662" alt="Screen Shot 2019-03-26 at 6 41 44 PM" src="https://user-images.githubusercontent.com/2799445/55038340-daa05300-4ff6-11e9-8435-50bcef24cd51.png">

**Comment by jordanade** [comment]
Moving the line of text down one space improves the situation, but you can see the layout of the toolbar is still munged:
<img width="478" alt="Screen Shot 2019-03-30 at 7 10 19 PM" src="https://user-images.githubusercontent.com/2799445/55282679-93c89b00-531f-11e9-95c8-1b1e6b5b7f4a.png">

Moving the line of text down two spaces finally allows it to render correctly:
<img width="472" alt="Screen Shot 2019-03-30 at 7 10 29 PM" src="https://user-images.githubusercontent.com/2799445/55282682-a4791100-531f-11e9-9be9-8772536f4121.png">

**Comment by jordanade** [comment]
Any response from the developers on this one?

**Comment by fbrbovic** [comment]
I am seeing this same issue, and it's really annoying,  any updates on this ?

**Comment by fbrbovic** [comment]
So decided to investigate it and the culprit is `max-height` being set to `0` on `.tox-pop`.  I have a CSS workaround but still, this should be fixed properly.
```
  .tox .tox-pop {
      max-height: unset !important;
  }
```

**Comment by jordanade** [comment]
@fbrbovic genius. Thanks so much

**Comment by TheSpyder** [comment]
This one slipped through the cracks, sorry. The editor is keeping context toolbars within the content bounds; this was a fix designed to prevent them overlapping the toolbar.

We are aware that removing the max-height is a fine fix for the issue when there is no toolbar or menubar, but we have scheduled a larger block of work to ensure we do not regress the toolbar overlap issue.

**Comment by jordanade** [comment]
Appears to be fixed in 5.0.12

**Comment by TheSpyder** [comment]
Sorry, yes, we forgot to update this ticket when the release went out :)
