### ISSUE TITLE
Not able to play video (mp4 extension)

### ISSUE THREAD

**Issue by sosharma1403** [tinymce/tinymce#4916]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?**
Go to code popup and insert a mp4 video. Instead of dummy poster, user should be able to play the video.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/3Wfaab/2

**What is the expected behavior?**
User should be able to play the video.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All

**Comment by jhaines** [comment]
Hi.  This is expected behaviour for the media plugin.

If you would prefer to preview video inside the editor while still editing, please try the premium plugin here: https://www.tiny.cloud/docs/plugins/mediaembed/
