### ISSUE TITLE
iOS - Soft keyboard not closing when click outside or TinyMCE editor submitted

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#4917]
We are using **TinyMCE editor version 4.7.9**. There are an issue running with the iOS (10, 11, 12.X) devices, the soft keyboard is not closing when clicking outside the TinyMCE editor or after submitting TinyMCE editor.

I have checked issue in latest TinyMCE version 5.0.3  on below TinyMCE fiddle and find issue occurring iOS (10, 11, 12.X) devices. 

**Steps to reproduce:**

1. Load TinyMCE editor and click inside editor and soft keyboard displayed.
2. Write some text in editor.
3. Submit editor to save text.  
4. The Soft keyboard is not closing.

Or 

1. Load TinyMCE editor and click inside editor and soft keyboard displayed.
2. Click outside TinyMCE editor, the soft keyboard not closing.

I have replicated issue on TinyMCE Fiddle URL with TinyMCE version 5.0.3. You can check this with exact issue.

http://fiddle.tinymce.com/REgaab

**Comment by lostkeys** [comment]
Sorry for the late reply, I tested you fiddle on both iOS 12 and 13 and was not able to reproduce it. However both TinyMCE 4.7.9 and 5.0.3 is very outdated. In TinyMCE 5.1 we completely removed the old TinyMCE mobile theme in favor of making the default theme responsive and mobile friendly. So my first recommendation is to upgrade TinyMCE and if your issue persists, please reopen this issue.

**Comment by tyagonunes** [comment]
I have the same problem. @laeeqwtb  Did you find any solutions?
I'm using Tiny Editor with Cordova. IOS Keyboard doesn't close when focus out.

**Comment by MeiMeiYunShang** [comment]
I have the same problem.
After Tinymce actived, IOS(12) keyboard will display when focus out  
@laeeqwtb @tyagonunes  Did you find any solutions?
