### ISSUE TITLE
TinyMCE 5: Incorrect input padding

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4918]
![tiny_input](https://user-images.githubusercontent.com/546788/55219375-0f81f500-5205-11e9-8707-bcc4cd06e57f.png)

Padding-right on some inputs is incorrect. I understand it is added for some status icons, but when the icon is not visible it should be reset to default. Otherwise the text is truncated too early and looks like a bug.

**Comment by lnewson** [comment]
This should have been fixed in 5.0.4, which has just been released. Please let us know if you find any further problems!
