### ISSUE TITLE
TinyMCE 5: checkbox focus issue

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4920]
Steps:
1. Goto https://www.tiny.cloud
2. Open Search and replace dialog
3. Click on "Match case" checkbox (or label) and click again.

Result: 
On the second (and any later) click on the checkbox first field in the dialog is focused for a moment, then focus goes back to the checkbox.

Expected:
Focus stays on the checkbox. No "focus wandering" effect.

Tested with Chrome and Firefox.

**Comment by alecpl** [comment]
If I click anywhere in the dialog (but not on an input nor label nor button) first input will be focused. That is probably related with the issue above. I don't like this, but I guess it might be by design.

**Comment by wonderbugtiny** [comment]
Thanks for the report! I have created an issue internally to look into this. We will update you when a fix is available.

**Comment by wonderbugtiny** [comment]
Please note that this issue is not applicable anymore as the redesigned `Find and Replace` inline dialog with no checkboxes was released in version 5.0.12.  Thank you!
