### ISSUE TITLE
Elements listed in extended_valid_elements cannot be selected with ce=false

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#4921]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Certain elements cannot be selected when `contenteditable="false"`. For example, when using `extended_valid_elements="i[class]"`, the `<i>` will not be selected by clicking:

```html
<i class="anything" contenteditable="false">some text</i>
```

This is demonstrated more clearly in the fiddle. I suspect this may have something to do with the schema being used, as it only seems to affect elements that aren't allowed in the default schema.

However, if an element is listed in `valid_elements` or `extended_valid_elements` it should be treated like any other valid element.

A fix for this bug will let implement a clean solution for the icon font problem (e.g. the holy grail of the icon-font-disappearing-in-TinyMCE issue) which I will gladly share. 🏆

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/YEgaab/2

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest, all tested.

**Comment by lnewson** [comment]
I haven't looked into this properly, but one issue I immediately can see is that your `extended_valid_elements` setting will cause issues with what you are trying to do, as you aren't allowing it to have a `contenteditable` attribute. If you change that setting to `extended_valid_elements: 'i[class,contenteditable]'` then it seems to behave the same as the other element in your fiddle.

**Comment by claviska** [comment]
You are absolutely right. I must have assumed the `contenteditable` attribute was special, because that makes perfect sense in hindsight.

Thanks! 🙌

I'm going to work on an icon font plugin shortly and will post a link back.

**Comment by claviska** [comment]
And here's the icon font plugin, as promised: https://github.com/claviska/tinymce-iconfonts
