### ISSUE TITLE
Circular check boxes - design improvement

### ISSUE THREAD

**Issue by WarwickGoatee** [tinymce/tinymce#4924]
**Do you want to request a *feature* or report a *bug*?**
It's not really either - just wanted to log a suggested design improvement

**What is the current behavior?**
Check boxes are rendered as circles in the default skin.

**What is the expected behavior?**
Pretty much everywhere else a checkbox is box shaped, so this isn't ideal from a UX perspective. People may expect them to act like radio buttons.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0.3, in any browser presumably.

**Comment by lostkeys** [comment]
Yeah, you are right. And it's just a matter of time until we need radio inputs. This will be addressed in an upcoming release.

**Comment by WarwickGoatee** [comment]
Thanks!

**Comment by wonderbugtiny** [comment]
This has been fixed in 5.0.4. Please let us know if you find any further problems!
