### ISSUE TITLE
Multiple toolbars always merge into one toolbar

### ISSUE THREAD

**Issue by zortext** [tinymce/tinymce#4928]
Passing an array of toolbar buttons does not make multiple separate toolbars as documented

https://www.tiny.cloud/docs/configure/editor-appearance/#usingmultipletoolbars

Reproduced demo: https://codepen.io/zortext/pen/VNKovN

Version 5.0.3

**Comment by lnewson** [comment]
Thanks for the report! This was actually an intentional however we are looking at bringing the original functionality back.

Anyways this issue has already been logged via https://github.com/tinymce/tinymce/issues/4819, as such I'm going to close this as a duplicate.

**Comment by zortext** [comment]
Here is a hacky solution 
https://github.com/tinymce/tinymce/issues/4819#issuecomment-481197078
