### ISSUE TITLE
BUG: Tinymce doesn't load plugins that are .min.js when using asp.net mvc bundle optimization

### ISSUE THREAD

**Issue by Cobra86** [tinymce/tinymce#4932]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
tinymce using the plugin files without the min.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
**Bundle Class:**
var tinymce = New ScriptBundle("/Content/Scripts/tinymce/tinymce-bundle.js").Include("/Content/Scripts/tinymce/tinymce.min.js")
bundles.Add(tinymce);

**Page:**
@section JavaScript
@Scripts.Render("~/Content/Scripts/tinymce/tinymce-bundle.js");
<script>
$(document).ready(function () {
testPage.pageInit();
});
</script>
End Section

**Tinymce Init:**
tinymce.init({
selector: '#TestID',
toolbar: true,
menubar: false,
browser_spellcheck: true,
height: 400,
paste_retain_style_properties: "all",
paste_word_valid_elements: "b,strong,i,em,h1,h2,u,p,ol,ul,li,a[href],span, color, font-size, font-color, font-family, mark",
plugins: [
'advlist autolink lists link image charmap print preview anchor textcolor',
'searchreplace visualblocks code fullscreen',
'insertdatetime media table paste code help wordcount'
],
toolbar: 'formatselect | bold italic strikethrough forecolor backcolor permanentpen formatpainter | link image pageembed | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat | code | help',
});
**What is the expected behavior?**
use the plugin.min.js instead of plugin.js
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
 Tinymce 5.0.3 (2019-03-19)

**Comment by lnewson** [comment]
TinyMCE determines whether to load `.min.js` or just `.js` files based on which TinyMCE script is being loaded (minified or unminfied). So if you want to load `plugin.min.js` instead of `plugin.js` then you should name your bundle file `tinymce-bundle.min.js`.

Alternatively you can also set the `suffix` to `.min` before calling `tinymce.init`, eg:
```
tinymce.suffix = '.min';
tinymce.init({
  ...
});
```

**Comment by lnewson** [comment]
I should also add you might also need to set the `baseURL` before calling init if your plugins are being served from an alternative path (eg something other than `/Content/Scripts/tinymce/plugins/`).

**Comment by Cobra86** [comment]
@lnewson I just changed the bundle name to tinymce-bundle.min.js and it works ! thank you for your help :)

**Comment by lnewson** [comment]
Glad to hear you got it working :)
