### ISSUE TITLE
Editor selects nonEditable div while pasting content into child editable div

### ISSUE THREAD

**Issue by kralicek-m** [tinymce/tinymce#4933]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
There is problem with pasting while using noneditable plugin. When you have mceNonEditable div with mceEditable div inside and you paste any content inside editable div, editor loses cursor position and unfortunately selects nonEditable div.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/davidemoro/pen/EVBmYy
**What is the expected behavior?**
Cursor should be just at the end of pasted content.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.9

**Comment by lnewson** [comment]
Apologies for the late update here, but this was fixed back in TinyMCE 5.10.0. Please let us know if you continue to experience any issues in 5.10.0 or above.
