### ISSUE TITLE
List item's content purged after init

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#4934]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When initializing TinyMCE on a list item `<li>`, the editor is initialized but the content is immediately purged.

No errors appear in the console.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Fiddle: http://fiddle.tinymce.com/GFgaab

**What is the expected behavior?**

The editor should be initialized and the existing content should not be purged.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- TinyMCE edge
- Chrome, Firefox, Safari

**Comment by bkirby989** [comment]
Ran into this today. Any update on a fix? Do we know which version this was introduced in?

**Comment by claviska** [comment]
I workaround this by:

- wrapping the list item's content in a `div`
- initializing the editor on the `div` instead of the `li`
- on save, set `li.innerHTML` to the editor's content

🤷‍♂

**Comment by TheSpyder** [comment]
A fix will be merged to master soon, if it passes QA it will be available in the 5.0.9 release.

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.0.10, which has just been released to the community. Please let us know if you have any further issues.
