### ISSUE TITLE
table_responsive_width doesn't enforce percentage units

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#4935]
**Do you want to request a *feature* or report a *bug*?**

Bug 🐞 

**What is the current behavior?**

When using the table plugin and setting `table_responsive_width` to `true`, percentage units should be used when resizing tables. Instead, pixels units are used.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Fiddle: http://fiddle.tinymce.com/IFgaab

**What is the expected behavior?**

The table should be resized using percentage units, per the [documentation](https://www.tiny.cloud/docs/plugins/table/#table_responsive_width):

> This option enables you to force pixels or percentage sizes for tables. **Setting this to true will force resizing by percentages** and setting this to false will force pixel resizing. The default is to automatically detect what the table size is and just use that unit for resizing. 

I have noticed that adding `style="width: 100%"` to the table triggers the correct behavior, so it seems like it's incorrectly using auto-detect when `table_responsive_width` is `true`.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- TinyMCE egde
- Chrome, Firefox, Safari

**Comment by SimonFc** [comment]
@claviska  A fix for this will be out in 5.0.10, thanks for reporting the issue!

**Comment by lnewson** [comment]
Just wanted to let you know that TinyMCE 5.0.10 has now been released to the community.
