### ISSUE TITLE
Some strings don't get translated for link plugin

### ISSUE THREAD

**Issue by nodejh** [tinymce/tinymce#4938]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/10287125/56106236-c2c34b80-5f72-11e9-9f0d-6da2bc47fcb9.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

I set language to `zh_CN` and use Chinese language package in  [https://www.tiny.cloud/get-tiny/language-packages/](https://www.tiny.cloud/get-tiny/language-packages/). 

`Current window` `None` `New window` are translated in language package file, but it don't work.

![image](https://user-images.githubusercontent.com/10287125/56106501-010d3a80-5f74-11e9-8b4b-cb7d1c497493.png)

**What is the expected behavior?**

`Current window` `None` `New window` should be translated.

**Comment by lnewson** [comment]
Thanks for the report! This is a known issue and is being tracked via https://github.com/tinymce/tinymce/issues/4904. We have a fix in the works and it should be fixed in the next TinyMCE 5.x release.
