### ISSUE TITLE
Hyperlinks changes do not apply if URL and text to display are the same

### ISSUE THREAD

**Issue by MariaAtScoro** [tinymce/tinymce#4939]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When url and text to display in hyperlink are different, it is not possible to make them back the same.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Screen record provided: https://www.loom.com/share/78fe8e62080d409c89beccde66726647

**What is the expected behavior?**
It should be possible to change the "URL" value to the same as a "text to display" value 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Issue exists in the tinymce fiddle.

**Comment by lnewson** [comment]
TinyMCE 5.4.2 was released earlier today to the community, which includes a fix for this issue. Please let us know if you continue to experience any further issues.
