### ISSUE TITLE
TinyMCE 4: Editor does not render after clean npm install

### ISSUE THREAD

**Issue by abodnar** [tinymce/tinymce#4942]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

After running a clean npm install, the TinyMCE editor does not display and when viewing the source code of the page, the tinymce element displays instead of the correct html.

`<tinymce name="body" id="body" init-value="" placeholder="Create your content here."></tinymce>`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Attached are the lock files for the previous node modules versions and the current node modules that were installed. TinyMCE was not updated as we use a private repo for it and it contains the premium/enterprise modules. If you want to run npm install with the lock file, I can provide access to the repo.

[new-lock.txt](https://github.com/tinymce/tinymce/files/3086784/new-lock.txt)
[old-lock.txt](https://github.com/tinymce/tinymce/files/3086785/old-lock.txt)

**What is the expected behavior?**

The TinyMCE editor displays correctly.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.8.5-113

**Comment by lnewson** [comment]
Hi,

I attempted to replicate this with TinyMCE 4.9.10 from the 4.x branch, however it all appeared to be working as expected. Additionally, we're only providing critical fixes for TinyMCE 4.9.x currently, so I'm going to close this. If you're still able to reproduce the issue in the latest develop, master or 4.x branches then please let us know and we'll reopen this issue.

Thanks!
