### ISSUE TITLE
Formatting(alignment, coloring, styles) is not applied to bullets and numbers in ordered and unordered lists

### ISSUE THREAD

**Issue by KateMaruk** [tinymce/tinymce#4945]
**Environment:**  
_Browsers:_ Chrome, Internet Explorer, Edge, Safari
_OS:_ Windows 10, MacOS
_TinyMCE editor:_  v.4.8.3

**Steps to reproduce:**
1. Create ordered / unordered list
2. Make settings for list:
   - select any color
   - set center alignment
   - apply bold and italic styles

**Actual result:**
All formatting (styles, alignment, color) is applied only to list text: 
http://img.mtrc.in/c3534eb4e049

**Expected result:**
 Formatting should also be applied to bullets and numbers in lists.

**Comment by SimonFc** [comment]
This is working as intended. Lists/items are block-level elements and so alignment wouldn't affect them. Same with styles such as color and bold. The numbers would have to be styled with list-style and similar(which the advanced lists plugin does) but only works to some extent.

The way Google Docs achieve this is by not using ol, ul etc. lists at all but constructing their lists out of spans and applying styles to them.
