### ISSUE TITLE
Numlist and Bullist not working in mobile view (TinyMce 5)

### ISSUE THREAD

**Issue by anoukinsyde** [tinymce/tinymce#4951]
Bullist and Numlist don't show on mobile after following the steps in the documentation. 

Steps to reproduce:
- I made an example here: https://codepen.io/anon/pen/yrjpNY
- If you view this in Chrome with the mobile view on and click the text area, you can see that the bullist and the numlist buttons are not there, even though they are included in the plugins and they should be supported according to: https://www.tiny.cloud/docs/mobile/

Tested in TinyMce 5.0.2. and 5.0.3., both don't show the list options.

**Comment by lnewson** [comment]
@anoukinsyde are you still able to reproduce this issue? As I just tested using the latest version available on cloud (5.0.4) and it appears to be working correctly:
<img width="276" alt="Screen Shot 2019-05-19 at 12 56 14 pm" src="https://user-images.githubusercontent.com/1575550/57977149-a31db800-7a35-11e9-9f5a-d9f2d96fbf16.png">

**Comment by anoukinsyde** [comment]
@lnewson I just updated TinyMce in my project, and now it indeed works. Don't know if you guys fixed it on purpose, but thanks anyway 😃
