### ISSUE TITLE
tinymce is blocked on Firefox Nightly because of the FF Fingerprinting blocker feature

### ISSUE THREAD

**Issue by staabm** [tinymce/tinymce#4953]
> tinymce.com is blocked by Disconnect:
https://github.com/disconnectme/disconnect-tracking-protection/blob/master/descriptions.md#TinyCloud
>
> any site which embeds TinyMCE HTML editor will have that functionality broken.
>
> Here's a test page which demonstrates the problem:
https://fmarier.github.io/brave-testing/tinymce.html
>
> see https://bugzilla.mozilla.org/show_bug.cgi?id=1544159

would be great if one of the developers here could get in contact with Mozilla within this bug ticket.

see https://github.com/disconnectme/disconnect-tracking-protection/blob/master/descriptions.md#TinyCloud for the reasoning behind TinyCloud beeing identified as 'fingerprinter'

**Comment by Afraithe** [comment]
We are looking to remove this very soon as we are aware of this issue.

Thank you for getting in touch.

**Comment by TheSpyder** [comment]
We've removed the fingerprintjs code, have followed up in the mozilla bug report and will contact disconnectme directly if we need to.
