### ISSUE TITLE
TinyMCE 5: Small jumping effect in Special character dialog (Firefox)

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4955]
Using Firefox:
1. Open Special character selection dialog (focus is on "All" tab)
2. Press KeyDown key to goto Currency tab. See some elements jump (a pixel or two).

**Comment by TheSpyder** [comment]
I can't reproduce this on Firefox for Mac. Are you still seeing this in the latest release?

**Comment by alecpl** [comment]
It looks fixed, indeed.
