### ISSUE TITLE
TinyMCE 5: Navigation items (tabs) have no focus style

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4956]
The navigation (tabs) used in Emoticons or Special character dialog have no focus style. So, when you jump from input/button to nav-item you loose the visual selection. Not a big issue, as the element responds to keyboard, but the currently focused tab name is not visually distinguishable. Buttons and inputs in a dialog have focus style.

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.0.16, as the currently focused tab now gets a blueish background color applied. Please let us know if you have any further issues.
