### ISSUE TITLE
Add custom checkbox in existing image plugin tinymce 5

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#4968]
![2019-04-28_143508](https://user-images.githubusercontent.com/1576475/56864523-b5bb4900-69c3-11e9-9427-9e0a432fcb43.jpg)
Question

How to make a custom checkbox in existing image plugin tinymce 5 ?
In tinymce 4 I adjusted the plugin.js, but is there a better way in version 5 ?
Also an onaction with the OKE button.

**Comment by TheSpyder** [comment]
There isn't a way to extend the built-in dialogs in TinyMCE 5, no. You'll need to continue patching the plugin (or perhaps fork the plugin) to achieve this.

Dialog definitions are much more configuration-based now, the checkbox documentation is here:
https://www.tiny.cloud/docs/ui-components/dialogcomponents/#checkbox
