### ISSUE TITLE
Add native fullscreen support

### ISSUE THREAD

**Issue by netcitylife** [tinymce/tinymce#4969]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When tinymce container element gets into native browser fullscreen mode, menus do not appear when trying to open them.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Menus do not appear because they are appended not to tinymce root container, but to body. So they are simply not visible when root container is in fullscreen mode. I wrote a simplified fullscreen native plugin, demonstrating that:
```javascript
tinymce.PluginManager.add('nativefullscreen', function (editor) {
  
  editor.ui.registry.addButton('nativefullscreen', {
    icon: 'fullscreen',
    tooltip: 'Fullscreen',
    onAction: () => {
      const container = editor.getContainer();
      const requestFullscreen = container.requestFullscreen || container.mozRequestFullScreen;

      requestFullscreen.call(container);
    }
  });
});
```

**What is the expected behavior?**
Menus correctly appear in native fullscreen mode.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TineMCE 4/5, all browsers.

**Comment by TheSpyder** [comment]
In TinyMCE 5 this actually isn't difficult to work around because all external UI is contained within a single auxiliary element.

I'm not saying we will do this immediately, but for demonstration purposes add this to your `onAction` function and the menus should appear:

```
const aux = document.getElementsByClassName('tox-tinymce-aux')[0];
container.appendChild(aux);
```
