### ISSUE TITLE
TinyMCE5 editor problem on IPAD

### ISSUE THREAD

**Issue by itajackass** [tinymce/tinymce#4971]
I've a big problem using tinymce5 on IPAD.

For longer textarea, If I set `max_height: 500` i don't see the scroller on IOS. (it works ok on PC and android)

So i tried to remove `max_height `and enable:
```
mobile: {
		theme: 'mobile'
}
```
but in this case if I click on book icon, a blank white page appears (always on IOS.... on android is all ok!)
To workaround this I need, after I click the book icon and blank page is showed, rotate tablet to change its orientation...in this case the editor appear!

Any fix or simple workaround? I need or use standard theme (no mobile) with scroller also in IOS, or use the mobile theme but fix the blank page IOS!

**Comment by itajackass** [comment]
UPDATE: after some test, i've found that blank page is caused by a sidebar (it appear and disappear by jquery click on an "hamburger" button inside page header) that has a `position:fixed` css.
if I remove position:fixed to my sidebar, editor on IOS appear correctly. But my sidebar get broken.

**Comment by lostkeys** [comment]
Just wanted to let you know that TinyMCE 5.1 is out since a couple of weeks and we have removed the old mobile theme in favor for making the default theme mobile friendly. So please try it out and reopen this issue if the problem persists.
