### ISSUE TITLE
Failed to load plugin url: https://cloud.tinymce.com/5/icons/material/icons.js

### ISSUE THREAD

**Issue by anands9288907423** [tinymce/tinymce#4972]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
overlay showing on screen with danger symbol  "Failed to load plugin url: https://cloud.tinymce.com/5/icons/material/icons.js"
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://wow-share.ml/tiny.html
**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by TheSpyder** [comment]
Your example page isn't showing the error right now. Have you changed anything since you logged this?

**Comment by anands9288907423** [comment]
I'm just removed something like this.
 i don't remember exact code
tinymce.init({
   theme: "material",
   });
now everything looks fine
