### ISSUE TITLE
IE11 infinite loop pasting from MS Word

### ISSUE THREAD

**Issue by lRawd** [tinymce/tinymce#4974]
https://github.com/tinymce/tinymce/blob/43712beb09f7e6fa4bfdbdee402f4d816015ea33/src/plugins/paste/main/ts/core/Clipboard.ts#L389

When pasting (CTRL + V) various content from MS Word into IE11, I get stuck in an infinite loop here. `editor.getDoc().execCommand('Paste', false, null)` seems to invoke `editor.on('paste', function (e: EditorEvent<ClipboardEvent & { ieFake: boolean }>)` and the function is recursively called forever.

I have to kill my Word process and then I get a whole bunch of %MCEPASTEBIN% entries in TinyMCE. If I have MS Word closed when I do the paste, the loop does not occur. If I right click with the mouse and select paste, the loop does not occur.

Using the debuger is see that `isKeyBoardPaste = false` when I use CTRL+V. If i modify it to be true, the loop does not occur.

**Comment by lRawd** [comment]
Further testing, pasting with CTRL+V on http://fiddle.tinymce.com/

version 4.0.28 - works
version 4.1.6 - I get a message saying I need to use CTRL-V to paste
version 4.7.9 - Infinite loop

**Comment by lRawd** [comment]
[ie loop errors.docx](https://github.com/tinymce/tinymce/files/3139649/ie.loop.errors.docx)

Here is a copy of the document that is causing the issue. Copy the entire contents of the doc and paste into tinymce with CTRL+V while Word is still running. Windows 10 IE 11.1087.16299.0CO

**Comment by warwickbs** [comment]
Hi,
I've experienced exactly the same issue and I posted it a few weeks ago but have only heard from one other user who has also had the problem.  Hopefully you'll get a response.  I tried in V5 and has the same issue.

**Comment by lRawd** [comment]
This appears to be a duplicate of #4905

**Comment by pmcquay** [comment]
We are having trouble with our users encountering problems pasting from word into tiny v5, and have not been able to repro the problem, what version of word are you using for this?

**Comment by lRawd** [comment]
@pmcquay I have only tried this with Word 2016 and it doesn't occur with all documents. Not sure exactly what content in the document causes it but it happens every time for me in IE with the document I attached earlier.

**Comment by warwickbs** [comment]
When i broke it i copied only a small paragraph from word, into word 2016.
I did examine the contents of the clipboard contents, and there was a huge amount of Word markup in there so i assume that’s what’s causing (caused?) the issue.
