### ISSUE TITLE
Set checkbox to true tinymce 5

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#4975]
Looks like checked: true isn't working in tinymce 5.04

`      var imageThumb = {
        type: 'label',
        label: 'Thumb',
        items: [{
            type: 'checkbox',
            name: 'thumb',
            label: 'thumb',
	    checked: true
          }]
      };`

expected that the checkbox is enabled by default

**Comment by lnewson** [comment]
@cfconsultancy `checked` isn't a valid value for the checkbox component, as you can see here: https://www.tiny.cloud/docs/ui-components/dialogcomponents/#checkbox In TinyMCE 5, the way you set the initial value is via the `initialData` setting in the dialog spec, as demo'd by the `isdog` checkbox here: https://www.tiny.cloud/docs/ui-components/dialog/#dialogcomposition

Here's a fiddle to demo: http://fiddle.tinymce.com/zHgaab
