### ISSUE TITLE
Buttons disappear from the panel with silver template on mobile device

### ISSUE THREAD

**Issue by zau4man** [tinymce/tinymce#4978]
Bug

Version: 5.0.4 (2019-04-23)

My config

`var tinymce_options = {"plugins":"autoresize quickbars media image link code","toolbar":"code bold italic underline | alignleft aligncenter alignright | blockquote | link media image ","min_height":350,"max_height":700,"browser_spellcheck":true,"menubar":false,"statusbar":false,"relative_urls":false,"paste_data_images":true,"image_caption":true,"toolbar_drawer":false,"spoiler_caption":"\u0421\u043f\u043e\u0439\u043b\u0435\u0440","toc_header":"div","resize":"both","theme":"silver","mobile":{"theme":"silver"},"smiles_url":"\/typograph\/get_smiles","paste_as_text":true,"file_picker_types":"file media","file_upload":{"url":"\/files\/upload_with_wysiwyg\/inline_upload_file"},"allow_mime_types":{"3":null,"4":null,"5":null,"6":["image\/gif","image\/jpeg","image\/png"]},"skin":"oxide","images_preset":"big","quickbars_selection_toolbar":"bold italic underline | quicklink h2 h3 blockquote","quickbars_insert_toolbar":"quickimage","forced_root_block":"p","block_formats":"\u041f\u0430\u0440\u0430\u0433\u0440\u0430\u0444=p; \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 2=h2; \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 3=h3;","image_title":true,"image_description":true,"image_dimensions":true,"image_advtab":true,"language":"ru","images_upload_url":"\/images\/upload","image_list":"\/files\/files_list"};`

When a silver template is specified in the configuration instead of a mobile template, buttons disappear from the panel.

So the editor panel looks like on a computer

![tiny_pc](https://user-images.githubusercontent.com/13526431/57136222-9195a880-6dc5-11e9-8d58-789193370ebc.png)

And so the editor panel looks like on a mobile device

![tiny_mobile](https://user-images.githubusercontent.com/13526431/57136252-ab36f000-6dc5-11e9-82f2-055e8fb72b0d.png)

In addition, the plug-in quickbars does not work. Due to issue https://github.com/tinymce/tinymce/issues/4848 managed to display the image insert button.

![tiny_mobile_h](https://user-images.githubusercontent.com/13526431/57136347-fc46e400-6dc5-11e9-9280-7cf3ecc6a34a.png)

How to be? The mobile template does not suit: it forces you to make an extra click, turns on the whole screen, disorienting the user.

Sorry for my english.

**Comment by pmcquay** [comment]
Hi, this is because the plugins that are missing are disabled on mobile regardless of the theme, there is currently no way to fix this.

This is the only documentation of this that I could find: https://www.tiny.cloud/docs/mobile/#configuringtheplugins

**Comment by lnewson** [comment]
As @pmcquay said, mobile currently only supports a small subset of plugins (see https://www.tiny.cloud/docs/mobile/#configuringtheplugins) and as such any other plugins are disabled. We currently have https://github.com/tinymce/tinymce/issues/4848 open to look at changing that behaviour to work based on the theme, instead of the platform.
