### ISSUE TITLE
how to call print in inline mode

### ISSUE THREAD

**Issue by JackyW83** [tinymce/tinymce#4980]
In inline mode, is there a way call print plugin to print document?

Thanks for helping me

**Comment by TheSpyder** [comment]
There's no easy way to make this work, unfortunately. We rely on the browser to print and for inline mode that means the whole window prints.

Due to the way inline mode inherits styles from the page we would need to somehow combine the print and preview plugins, using the preview frame to print.

**Comment by matsn0w** [comment]
+1
