### ISSUE TITLE
editor.windowManager.openUrl is not in the documentation

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#4981]
`editor.windowManager.openUrl` is not mentioned in the documentation.

https://www.tiny.cloud/docs/api/tinymce/tinymce.windowmanager/

**Comment by lnewson** [comment]
The documentation is based off the enterprise version of TinyMCE which is currently still on 5.0.3. Once 5.0.4 is released to enterprise, then the docs will also be updated. That should be happening sometime this week I believe.

**Comment by vanillajonathan** [comment]
I hope to see the documentation also include callbacks from the opened URL back to TinyMCE.
