### ISSUE TITLE
Cannot toggle formats when instantiating TinyMCE from a parent document

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#4983]
**Do you want to request a *feature* or report a *bug*?**

Bug 🐞

**What is the current behavior?**

When TinyMCE is instantiated from a parent document, you cannot toggle custom [content formats](https://www.tiny.cloud/docs/configure/content-formatting/) if the custom format is configured as an array.

The following bug appears in Chrome:

![image](https://user-images.githubusercontent.com/55639/57249633-75874680-7013-11e9-9808-d1269c814c82.png)

I suspect it has something to do with the changes in [this commit](https://github.com/tinymce/tinymce/commit/b0d27d274d5e4e5d2786f985813f0a0ca43c9f07#diff-4ff98180580588cac0e9a0c0512115ed), but I'm not familiar enough with 5.x's code base to be sure.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

- Minimal test case demonstrating the bug in TinyMCE 5: https://jsfiddle.net/65710fL8/2/
- The same test case demonstrating it _working_ in TinyMCE 4: https://jsfiddle.net/wrhn2dmb/1/

**Note:** Due to the one-file nature of fiddles, this demo injects the `iframe` and `script` with JavaScript. You will see the same behavior using two separate, simpler files (must be run from a web server):

`index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Tiny 5 Bug</title>
</head>
<body>

  <iframe id="editor-frame" src="frame.html" style="width: 100%; height: 400px;"></iframe>

  <script>
    const iframe = document.getElementById('editor-frame');

    // Wait for the iframe to load
    iframe.addEventListener('load', () => {

      // Then instantiate the editor on the iframe using the iframe's TinyMCE object
      const tinymce = iframe.contentWindow.tinymce;
      tinymce.init({
        selector: '.edit',
        inline: true,
        menubar: false,
        toolbar: 'bold',

        // From the docs: https://www.tiny.cloud/docs/configure/content-formatting/
        formats: {
          bold: [
            { inline: 'strong', remove: 'all' },
            { inline: 'span', styles: { fontWeight: 'bold' } },
            { inline: 'b', remove: 'all' }
          ]
        }         
      })
    });
  </script>
</body>
</html>
```

`frame.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body style="padding: 4rem 2rem;">
  <div class="edit">
    <h1>Lorem Ipsum Dolor</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi voluptatum vitae dolorem fugiat, velit maxime est consequuntur repudiandae amet voluptas quo quod ipsum, saepe rerum tempore itaque nobis placeat reprehenderit.</p>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/tinymce@5.0.4/tinymce.js"></script>
</body>
</html>
```

**What is the expected behavior?**

Formats should be applied or removed when toggled.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- Chrome / Firefox / Safari
- Bug appears in TinyMCE 5.0.0 – 5.0.4
- Bug was not present in 4.9.4

**Comment by TheSpyder** [comment]
Using TinyMCE in a different document to the script tag is a difficult scenario to support and I wasn't even aware it worked previously.

I suspect it's the different Array prototypes somehow tripping up our configuration logic. If you print out `ed.formatter.get('bold')` in both editors, the broken case returns an array containing an array where with v4 (and v5 when the script and the tinymce object are in the same window) it's just a straight array as intended.

That causes [this logic](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts#L116) in ApplyFormat to set the wrap element name to `undefined` and things go badly from there.

**Comment by TheSpyder** [comment]
@lnewson found it:
https://github.com/tinymce/tinymce/commit/5d54524ccf8#diff-e5d8630c0ee38c3cf8050d96987767fdR32

We've started using `Type.isArray` more frequently, so we'll have to fix that code rather than simply revert the single change that triggered this issue.

**Comment by claviska** [comment]
> Using TinyMCE in a different document to the script tag is a difficult scenario to support and I wasn't even aware it worked previously.

I realize this seems like an edge case, but controlling the editor from a parent frame makes a lot of sense in terms of inline editing. Without it, there's really no good way to sandbox the editor from the controlling app. I've been using it quite successfully this way since TinyMCE 3. 😄

Thanks for locating the issue, btw. It seems like `register()` should accept an array _or_ an object here. The previous code worked because it was using `format.length` which is true for arrays and objects. Am I mistaken on this?

**Comment by TheSpyder** [comment]
> I realize this seems like an edge case, but controlling the editor from a parent frame makes a lot of sense in terms of inline editing. Without it, there's really no good way to sandbox the editor from the controlling app. I've been using it quite successfully this way since TinyMCE 3. 😄

Well TIL 😂

If you want to standbox from the controlling app, why don't you use normal mode? Inline mode is more or less designed to integrate tightly into pages, normal mode is the sandboxed one. We could perhaps have a longer conversation after this is fixed 🤔

> The previous code worked because it was using `format.length` which is true for arrays and objects. Am I mistaken on this?

No, an object doesn't have a length unless you give it one.

```
> ({inline: 'strong', remove: 'all'}).length
undefined
```

**Comment by TheSpyder** [comment]
There should be a nightly build (the "edge" option on fiddle.tinymce.com) soon, and if there are no issues it will be released with TinyMCE 5.0.10

**Comment by claviska** [comment]
Thanks! 🙌

> If you want to standbox from the controlling app, why don't you use normal mode? Inline mode is more or less designed to integrate tightly into pages, normal mode is the sandboxed one. We could perhaps have a longer conversation after this is fixed 🤔

Again, I'll admit I'm not your standard user, but I'll elaborate a bit for those interested.

In my implementations, the content being edited is an entire webpage with arbitrary editable elements. The controlling app has its own sidebar chrome (left), so the webpage is rendered separately in an iframe (right). The app also uses its own editing UI for consistency:

<img width="1338" alt="Screen Shot 2019-06-26 at 10 23 40 AM" src="https://user-images.githubusercontent.com/55639/60188353-21bc0100-97fd-11e9-860c-ea0767dddf32.png">

I can't reliably sandbox the webpage's scripts and styles from the app because I don't control the webpage. These are user websites with various scripts and styles, so merging them into a SPA would create all sorts of problems.

To solve this, the app renders a copy of the webpage in the iframe, injects TinyMCE, and controls it from the parent document.

I've successfully done this with two projects if you'd like to take a look.

- [Surreal CMS](https://www.surrealcms.com/)
- [Postleaf](https://www.postleaf.org/)

Both have demos. Surreal you need to signup first, Postleaf has a public demo.

> No, an object doesn't have a length unless you give it one.

You're right...I think I was confusing it with `Object.keys()` 🤦🏻‍♂️

**Comment by TheSpyder** [comment]
Oh very cool! We experimented with something similar in a research project earlier this year.

Would you be open to a conversation with someone from our design team about your experience with TinyMCE and what we could do better for you?

**Comment by claviska** [comment]
Absolutely. I’ve talked to @androb a bit in the past so he knows at least some of my thoughts. I’m more than happy to have a more detailed chat with the design team.

**Comment by lnewson** [comment]
@claviska just wanted to let you know that TinyMCE 5.0.10 has now been released to the community. Please let us know if you have any further issues.

**Comment by claviska** [comment]
Works great! Thanks for the fix 🙌
