### ISSUE TITLE
TinyMCE does not preserve whitespace on paste

### ISSUE THREAD

**Issue by Parent5446** [tinymce/tinymce#4984]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If you copy text with leading spaces, trailing spaces, or multiple consecutive spaces from a source that isn't wrapped in a \<pre> into the editor, it strips out the spacing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Steps to Reproduce:
1. Go to https://codemirror.net/
2. Copy the contents from the code editor (below the "This is CodeMirror" heading)
3. Paste into TinyMCE (works with any editor, including the "Basic example" on the dev site).

Result:
It pastes into the text editor as:

```text
<!-- Create a simple CodeMirror instance -->
<link rel="stylesheet" href="lib/codemirror.css">
<script src="lib/codemirror.js"></script>
<script>
var editor = CodeMirror.fromTextArea(myTextarea, {
lineNumbers: true
});
</script>
```

Note this occurs even if white-space: pre-wrap is set as a style on the editor. The spaces are removed entirely. I believe this is occurring in DomParser.ts, which is removing extra whitespace for some reason.

This is the HTML that is taken from the clipboard, as captured from the BeforeSetContent hook:

```
"&lt;!-- Create a simple CodeMirror instance --&gt;<br>&lt;link rel="stylesheet" href="lib/codemirror.css"&gt;<br>&lt;script src="lib/codemirror.js"&gt;&lt;/script&gt;<br>&lt;script&gt;<br>  var editor = CodeMirror.fromTextArea(myTextarea, {<br>    lineNumbers: true<br>  });<br>&lt;/script&gt;"
```

**What is the expected behavior?**

The spacing should be preserved, and it should paste into the editor as:

```text
<!-- Create a simple CodeMirror instance -->
<link rel="stylesheet" href="lib/codemirror.css">
<script src="lib/codemirror.js"></script>
<script>
  var editor = CodeMirror.fromTextArea(myTextarea, {
    lineNumbers: true
  });
</script>
```

Note that this behavior does occur if you paste from a website that actually wraps the content in a \<pre> tag, rather than applying white-space:pre-wrap via a CSS style (such as in StackOverflow).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

v5.0.4 in Chrome Linux
I don't know if this worked in previous versions

**Comment by Parent5446** [comment]
Workaround:

If you set `root_name: 'pre'` in the editor config, the parser thinks it's always in a whitespace-preserving situation.

This setting does not appear in documentation, so I'm not sure what other purposes it serves. But it does not appear to have broken anything else in the editor yet.

**Comment by TheSpyder** [comment]
Interesting. Disabling the paste plugin does fix this, so it's absolutely a bug (probably in our plain text paste routines).

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.0.10, which has just been released to the community. Please let us know if you have any further issues.

**Comment by Parent5446** [comment]
Just noting for my future reference, this was fixed in 4a38064c9b487e623c51ea8f55ad42807d5bfaed.

**Comment by samkcdev** [comment]
I don't see Tinymce preserving whitespace when content is pasted even in their fully featured Demo.

For example if I copy, content like the below one and paste in tinymce demo

![image](https://user-images.githubusercontent.com/13085849/113895625-c64adf80-97e6-11eb-8b00-66586dbcf6ed.png)

It comes in **one single line**. Not sure what was fixed here.

![image](https://user-images.githubusercontent.com/13085849/113895323-7f5cea00-97e6-11eb-8f9d-e6fe83ee39f9.png)

**Comment by TheSpyder** [comment]
Where are you pasting from, and which browser are you pasting into? That example works for me pasting plain text.

![Screen Shot 2021-04-12 at 10 59 39 am](https://user-images.githubusercontent.com/298292/114327905-550c8300-9b7e-11eb-9001-094300ad2e06.png)

**Comment by samkcdev** [comment]
@TheSpyder 
I copied from
 https://codepen.io/modernwebdesigner/pen/rNjqLQg
from the output which which is generated here because that is how I am getting data from backend
I tried this in both Firefox and Chrome

**Comment by TheSpyder** [comment]
This is because our full featured demo uses PowerPaste, which [defaults to clean import for HTML content](https://www.tiny.cloud/docs/plugins/premium/powerpaste/#powerpaste_html_import). This strips the `white-space:pre-wrap` from the pasted data.
