### ISSUE TITLE
tinymce does not show up in mobile browser

### ISSUE THREAD

**Issue by bhasinnaik** [tinymce/tinymce#4985]
Hi,

I am using tinymce in my website. Unfortunately the editor does not show up in my safari browser. i am using ios12.2 with iphone 6s.

Please help here.

Thanks & Regards

**Comment by holuborhee** [comment]
@bhasinnaik I think you should visit the www.tiny.cloud on the specific device and browser.

**Comment by ltrouton** [comment]
Closing this due to lack of additional information. Please reopen this issue if it still persists.
