### ISSUE TITLE
Is there a way to access dialog popup to change input state?

### ISSUE THREAD

**Issue by Draghmar** [tinymce/tinymce#4988]
I'm playing with new `editor.windowManager.openUrl` feature in 5.0.5 and it works quite well. I've manage to make it work in a way I'd like it to...so as a next step I wanted to try and change the input state of the _Insert/Edit Image_ plugin. There's a setting to enable caption but the _checkbox_ itself isn't checked by default. I thought I would set it to _checked_ on dialog open (with help of `file_picker_callback`) or after inserting path with `onMessage` event. But I don't know how to reference Dialog itself...I can't find any info about that. Is it even possible?

**Comment by TheSpyder** [comment]
We removed the API to access the currently open dialog in v5, although it is technically available via the undocumented `OpenWindow` event.

File picker callback does let you set additional fields via the meta object, as documented here:
https://www.tiny.cloud/docs/configure/file-image-upload/#file_picker_callback

however I just tried it and `caption` isn't picked up by the meta-handling code in v5. I'm working on a fix.

**Comment by Draghmar** [comment]
> however I just tried it and `caption` isn't picked up by the meta-handling code in v5. I'm working on a fix.
Oh, so that's why I couldn't do anything with it when I was testing. Thanks! I'll wait for the fix and then try full and final experience with new version :)
