### ISSUE TITLE
Nested link_list not available anymore in TinyMCE 5

### ISSUE THREAD

**Issue by mrk-j** [tinymce/tinymce#4989]
Since TinyMCE 4.0.27 it was possible to have submenu's within the `link_list` as [documented](https://www.tiny.cloud/docs-4x/plugins/link/#link_list). This options seems to have disappeared since version 5. This change doesn't seem to be documented anywhere.

Is this feature on the roadmap for upcoming releases or is this deprecated?

**Comment by lnewson** [comment]
It's something that's on the roadmap, but hasn't been scheduled to be implemented in v5 yet sorry. We're currently tracking this over at https://github.com/tinymce/tinymce/issues/4822, so I'm going to close this as a duplicate.
