### ISSUE TITLE
Images are not selected on right click in Chrome

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#4992]
If you right click on an image in TinyMCE 5.x on Chrome, the context menu is shown, but the image is not selected. This is caused by the fact that the event `click` is used instead of `mousedown` in `\src\core\main\ts\util\Quirks.ts`. `click` events are only fired when the left mouse button is clicked, where `mousedown` works in all cases.

So instead of:
``` 
const selectControlElements = function () {
    editor.on('click', function (e) {
```

it should be:
```
const selectControlElements = function () {
    editor.on('mousedown', function (e) {
```

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.0.8, which has just been released. Please let us know if you have any further issues.
