### ISSUE TITLE
TinyMCE 4 or 5 contenteditable: replace text selection with custom content is possible even if disabled 

### ISSUE THREAD

**Issue by bahamut657** [tinymce/tinymce#4993]
This is a Bug Report

Setting "contenteditable" to false using  
`editor.getBody().setAttribute('contenteditable', false);` is still possible to write inside te editor selecting a work and pressing a letter key.
This action update the editor content but don't trigger the change event.

Step to reproduce the problem:
http://fiddle.tinymce.com/15eaab/1
1) Copy some text in clipboard
2) Select a word inside the editor with double click
3a) Paste content in the selection => The selected content is replaced by the pasted one
3b) It is possible to write one letter every time I perform a selection

I'm expecting that contenteditable = false will prevent ALL input event and prevent any modification to the content

TinyMCE version 4.9.4, but also the 5.0.5 version is affected
Browser: Chromium 74

**Comment by TheSpyder** [comment]
The supported method to disable editing is to make the editor readonly via `editor.setMode('readonly')` (or, in the latest 5.x releases, `editor.mode.set('readonly')`)

There is an issue with the later 4.x releases that causes the entire content to be unselectable in readonly mode, we have just fixed that in 5.0.6.
