### ISSUE TITLE
Error: You must use Yarn to install, not NPM

### ISSUE THREAD

**Issue by nodejh** [tinymce/tinymce#4994]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

➜  tinymce git:(master) npm i

> @ephox/bedrock@4.2.10 preinstall /Users/jh/inbox/test/dev-tinymce/tinymce/node_modules/@ephox/bedrock
> node -e "if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('You must use Yarn to install, not NPM')"

[eval]:1
if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('You must use Yarn to install, not NPM')
                                                    ^

Error: You must use Yarn to install, not NPM
    at [eval]:1:59
    at Script.runInThisContext (vm.js:123:20)
    at Object.runInThisContext (vm.js:313:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at evalScript (internal/process/execution.js:77:25)
    at internal/main/eval_string.js:23:3
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ephox/bedrock@4.2.10 preinstall: `node -e "if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('You must use Yarn to install, not NPM')"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ephox/bedrock@4.2.10 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jh/.npm/_logs/2019-05-13T06_10_03_656Z-debug.log

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

Install packages without errors.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- tinymce/tinymce master
- macOS
- npm 6.9.0,  node v12.2.0

**Comment by lnewson** [comment]
As noted by @TheSpyder in https://github.com/ephox/bedrock/issues/1 this is expected as we are migrating to yarn, as it has a number of features not available to npm that we'll need for upcoming changes.
