### ISSUE TITLE
Tiny removes spaces inside the editor content when changing certain formats

### ISSUE THREAD

**Issue by lukasbash** [tinymce/tinymce#4995]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Tiny removes spaces inside the editor content when changing certain formats.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Using the full featured demo: https://www.tiny.cloud/docs/demo/full-featured/
1. Write two words with a space in between.
2. Select first word, apply bold format
3. Select second word, apply underline, italic and bold
4. While the second word is still selected, unapply underline, italic and bold
-> space in between the two words is gone
![evidence](https://user-images.githubusercontent.com/15958032/57676330-8e4fb780-7624-11e9-906f-811012c7a3a2.gif)

**What is the expected behavior?**
Tiny must not alter the content of the editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I am using Google Chrome Version 74.0.3729.131 (Official Build) (64-bit) on Arch Linux 5.0.13.
I did not test it in other versions.

**Comment by lnewson** [comment]
Interesting... it only seems to happen if you apply the formats in a specific order. As I tested some other combinations and they do preserve the space. As an example these keep the space:
- bold -> italic -> strike-through -> strike-through -> italic -> bold
- bold -> italic -> strike-through -> bold -> italic -> strike-through
- bold -> strike-through -> italic -> italic -> strike-through -> bold

While the following the space was lost:
- strike-through -> italic -> bold -> bold -> italic -> strike-through
- strike-through -> italic -> bold -> strike-through -> italic -> bold
- italic -> strike-through -> bold -> italic -> strike-through -> bold

So the key point seems to be when the first style applied isn't bold (or the same as the sibling), then this issue occurs.
