### ISSUE TITLE
Unable to remove format on inline editor

### ISSUE THREAD

**Issue by lukasbash** [tinymce/tinymce#4996]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When using multiple formats, tiny cannot remove some applied formats anymore.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Use the codepen example here (or any other inline editor) and make sure you have multiple formats enabled. In my case strikethrough, underline, italic and bold.
https://codepen.io/anon/pen/QRGdaM?&editable=true
![reproduction_tinyFormatRemoval](https://user-images.githubusercontent.com/15958032/57677859-200cf400-7628-11e9-8f88-cdecb69bf719.gif)

**What is the expected behavior?**
Tiny should be able to remove any format in any given combination.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I am using Google Chrome Version 74.0.3729.131 (Official Build) (64-bit) on Arch Linux 5.0.13.
I did not test it in other versions.

**Comment by lostkeys** [comment]
Sorry for the late reply. I was not able to reproduce your bug with the codepen you provided. You are using the cloud hosted version of TinyMCE so I don't know which version you had problem with so we can't investigate further. 

Can you please check if the problem persists and in that case, reopen this issue and let us know which version you are using (to do that, enable the help plugin, put a help button in the toolbar and check the version tab in the dialog that appears when pressing the help button).
