### ISSUE TITLE
"Remove color" and "Custom color" not translated

### ISSUE THREAD

**Issue by Bene98** [tinymce/tinymce#4997]
The Buttons "Remove Color" and "Custom Color" are not translated (in my case to german), even though the translated text exits in the language package. I use tinymce5 on Chrome.

**Comment by EkimChau** [comment]
we have now listed 2 new items for our next round of translations, thanks for reporting Bene98

**Comment by lnewson** [comment]
@Bene98 what version of TinyMCE are you using? As there was an issue pre 5.0.4 where the text in the color swatch wasn't being passed through for translation, however that was fix in 5.0.4.

Are you still able to reproduce the issue with this fiddle? http://fiddle.tinymce.com/hIgaab

**Comment by Bene98** [comment]
@lnewson it works with version 5.0.4, thanks!
