### ISSUE TITLE
Autocompleter plugin not trigger when select value from input tool

### ISSUE THREAD

**Issue by nodejh** [tinymce/tinymce#4999]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I select value from input tool, such , autocompleter plugin not work.

- use `space` to choose word `china`.

![tinymceautocomplete](https://user-images.githubusercontent.com/10287125/57698349-0ac7b200-7688-11e9-9281-432e390cac5e.gif)

- select word by mouse

![tinymceautocomplete2](https://user-images.githubusercontent.com/10287125/57699161-cccb8d80-7689-11e9-9aa0-549a4150af2f.gif)

Input sources:

![image](https://user-images.githubusercontent.com/10287125/57699264-f2f12d80-7689-11e9-96eb-cd9268ac44a6.png)

- *Pinyin - Simplified*  not work
- *ABC*  work fine

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

This is the demo: https://github.com/nodejh/tinymce/tree/tinymce/autocompleter_demo.

My plugin source code directory is `src/plugins/mention`.

```js
editor.ui.registry.addAutocompleter('mention', {
  // ...
  matches: (rng, text, pattern) => {
      console.log('rng, text, pattern', rng, text, pattern);
      return text.indexOf(Settings.getMentionCh(editor)) === 0;
    },
});
```

```
$ git clone https://github.com/nodejh/tinymce --branch tinymce/autocompleter_demo autocompleter_demo
$ cd autocompleter_demo
$ yarn
$ grunt
$ grunt start
```

Then open browser and go to `http://localhost:3000/src/plugins/mention/demo/html/demo.html`

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 5.0.5

**Comment by TheSpyder** [comment]
Ah. TinyMCE's core keyboard code blocks normal events during composition input and the autocompleter relies solely on these to show the menu.

It looks like a simple fix.
