### ISSUE TITLE
TinyMCE is blocked in FF Private Window

### ISSUE THREAD

**Issue by jnnlcnjs** [tinymce/tinymce#5000]
TinyMCE is blocked in FF Private Window by it's Content Blocking feature because TinyMCE has a tracker. Is there anyway to automatically remove the blocking feature? Thank you.

**Comment by lnewson** [comment]
We've actually already removed the tracker and the block has been removed in the disconnect.me repo here: https://github.com/disconnectme/disconnect-tracking-protection/commit/156e9c67582134e1511209c1cc7dea5710eab4a5 However it seems that this hasn't yet been rolled out. We've reached out to see when this might get rolled out, but haven't heard back yet.

So until that happens, unfortunately the only way I know to work around that is to disable the content blocking in Firefox (though that's not a great option).

**Comment by lnewson** [comment]
This should now be fixed: https://github.com/mozilla-services/shavar-prod-lists/pull/65
