### ISSUE TITLE
The pre tag disappears when the list is applied.

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5001]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When i apply list on pre tags, they will be disappeared, so after remove list all pre indents won't be restored 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Paste/use preformatted text(tag "pre")
2. Apply list
**What is the expected behavior?**
Pre tag won't remove after applying list
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.0+ Any browser

**Comment by ltrouton** [comment]
Hi @versusvirus. Thanks for posting! The behaviour that you are experiencing is currently the intended functionality of TinyMCE. The pre tags only support inline styling tags (bold, italic, etc.) and any other tags will replace the pre tags. If you could provide some information as to why you would like to have lists inside a pre tag, we may be able to provide more assistance.

**Comment by ltrouton** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
