### ISSUE TITLE
Paste plugin eliminates line spacing for bulleted lists from Google Docs

### ISSUE THREAD

**Issue by Parent5446** [tinymce/tinymce#5006]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When pasting from Google Docs, the default paste filters strip `<p>` tags that are children of `<li>` tags. Frequently, these `<p>` tags have line-height styling if the doc in question has anything but single line-spacing (e.g., 1.15 spacing). Since the tag is stripped, this results in the line spacing being lost

https://github.com/tinymce/tinymce/blob/43712beb09f7e6fa4bfdbdee402f4d816015ea33/src/plugins/paste/main/ts/core/WordFilter.ts#L367

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Create a Google Doc with a bulleted list.
2. Set Format -> Line Spacing -> 1.15 for the entire document.
3. Copy and paste into TinyMCE with default settings and the paste plugin.

**What is the expected behavior?**

The line spacing should be preserved. I'm not sure why the `<p>` tags are being removed in the first place.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

v5.0.4 in Chrome

**Comment by TheSpyder** [comment]
Your issue is not formatted correctly, please highlight the HTML tags in your description and use the "insert code" toolbar button to ensure they show up like `<p>`

**Comment by Parent5446** [comment]
Sorry about that. Done.

**Comment by TheSpyder** [comment]
Ah, I see what you mean now.
