### ISSUE TITLE
Building Tiny not possible

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#5008]
**bug: building tiny not possible**

Description of building tiny based on npm.
But parts of current master code based on Yarn.

-> description for building tiny is wrong.

p.s. I am aware of https://github.com/tinymce/tinymce/issues/4994
Why is it closed? 
-> building tiny is not possible right now.

**Comment by TheSpyder** [comment]
Sorry about this. The change to use yarn on master has taken longer than we expected. It's quite a big project. The push to break npm compatibility in one of the dependencies perhaps happened too early.

The readme should read `yarn install`, not `npm install`. Other than that, as master is today everything else in the readme should work.

**Comment by Georg-Git** [comment]
This is my new script for building TinyMCE with yarn:

```
$ git clone https://github.com/tinymce/tinymce.git
$ cd tinymce/
$ yarn global add yarn
$ yarn global add uglify-js
$ yarn global add grunt-cli
$ yarn install
$ grunt bundle --themes=silver --plugins=table,paste
```

**Comment by TheSpyder** [comment]
If you prefix the last line with yarn:

`yarn grunt bundle --themes=silver --plugins=table,paste`

You should be able to skip the `yarn global add` lines :)

**Comment by Georg-Git** [comment]
Why did You close this issue?

Neither the description on GIT startpage:
https://github.com/tinymce/tinymce
nor the description in the readme file:
https://github.com/tinymce/tinymce/blob/master/readme.md
is correct - and as result building TinyMCE is not possible.

So - with regard to Your last comment the correct building description should be:

```
$ git clone https://github.com/tinymce/tinymce.git
$ cd tinymce/
$ yarn global add uglify-js
$ yarn global add grunt-cli
$ yarn install
$ yarn grunt bundle --themes=silver --plugins=table,paste
```

Why did You not update the descriptions (readme etc.)?

**Comment by Georg-Git** [comment]
Still not correct - next try:

```
$ git clone https://github.com/tinymce/tinymce.git
$ cd tinymce/
$ yarn add uglify-js
$ yarn add grunt-cli
$ yarn install
$ yarn grunt bundle --themes=silver --plugins=table,paste
```

It would be easier when You provide a correct update of the description .....

**Comment by TheSpyder** [comment]
Sorry, I thought your message indicated you had it working. The readme will be updated once our big change is merged, which I hope will be later this week, I didn't see much point in doing it twice.

The only thing I can think might be missing from your script is not related to yarn, it's that `bundle` doesn't build the editor. `prod` does that. I just confirmed this works:
```
$ git clone https://github.com/tinymce/tinymce.git
$ cd tinymce/
$ yarn install
$ yarn grunt prod bundle --themes=silver --plugins=table,paste
```

**Comment by Georg-Git** [comment]
Thanks for Your script version.
But right now the old script in the readme file is describing building the master version of tiny, isn't it?

`$ yarn grunt bundle` => building last master version of tiny
`$ yarn grunt prod bundle` => building last official release of tiny

Correct?

**Comment by petko** [comment]
Still no build instructions?

**Comment by tinydylan** [comment]
Build instructions can be found here: https://github.com/tinymce/tinymce/blob/master/CONTRIBUTING.md
