### ISSUE TITLE
TinyMCE 5: OpenWindow event not used for Yes/No dialog

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5010]
The event is not executed when displaying the dialog mentioned in #5009.

**Comment by TheSpyder** [comment]
We stopped firing this event for alert/confirm dialogs because the event includes a copy of the dialog API, and the API is different for these two dialogs compared to every other dialog.

We would need to find a way to normalise this before we can resume firing the event.

**Comment by alecpl** [comment]
FYI, As I re-style dialog buttons, lack of an event here leads to a visual issue. A workaround with css could be possible, but not that nice.

**Comment by TheSpyder** [comment]
I know we've covered this before, but the design of the TinyMCE 5 theme was that if you want to re-style to that level you can build a replacement skin. The skin builder isn't ready so this is quite difficult right now.

OpenWindow was a core event left in purely for backwards compatibility in case anyone relied on it.
