### ISSUE TITLE
TinyMCE 5: Please, fix obvious UI bugs with more prio

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5011]
Don't get me wrong. I appreciate it's open source and I understand your customers' issues have priority. I am grateful for the work done on TinyMCE 5 so far. And maybe the way I setup Tiny for Roundcube is not what everyone else does. That being said, it's still not ready for inclusion in a serious application (considering its users), that I consider Roundcube Webmail is.

I created [many tickets](https://github.com/tinymce/tinymce/issues/created_by/alecpl) (most of them about bugs in the new UI), many of them already fixed, but I noticed that the progress slowed down. E.g. I see tickets were stopped being tagged about two months ago.

I consider myself an important part of your community. I joined TinyMCE developer challenge and responded to some research pool (yes, I was rewarded for that) so I feel I can ask for your attention and hope it will not be considered an ungrateful rant.

Please, check list of my tickets and read my [blog post](https://kolabian.wordpress.com/2019/05/23/tinymce-5/). If you're interested I will provide prioritized list of tickets.

**Comment by Afraithe** [comment]
Hey Alec, we had a client deadline recently that took up a lot of our time, the next big thing after that (starting this week I believe) is looking deeply into mobile it will take time though, there are a lot of moving parts. And "mobile" is a floating term, the interface on a mobile phone may be one thing, but if your on an ipad, your experience is more similar to desktop etc, so we are trying to find our path through this using our experience, testing and experimenting.

And you are right, you are an important part of the community, and we appreciate all the hard work you do submitting good bug reports, we should have some more time to look into these in the next few months.

A list of the prioritized ones to get you over to T5 would be great, I do not think your situation is unique, if your having these issues, chances are others are as well. And we definitely want ppl to move over to T5 as soon as they are comfortable (sooner the better).

**Comment by alecpl** [comment]
Most pressing bugs: #5010, #5003, #4865, #4863, #4862, #4920.
And a feature that would make my life easier: #4869.

**Comment by TheSpyder** [comment]
Sorry for the current situation. We are starting to return to what we had going after the 5.0 release, which was 20% of the team assigned to support and github. We have also flagged that we need to have a burst where most of the team chips in to get our issue list back under control.

**Comment by alecpl** [comment]
The ticket purpose is to get your attention. I got it. Besides, I decided to give up on the mobile mode, as it was suggested it's deprecated. So, not all mentioned bugs are important to me anymore.

That being said, I'm not happy with the state of my other tickets, but I understand you have your own priorities.

**Comment by TheSpyder** [comment]
The mobile theme was created at a time when mobile browsers didn’t offer wide support for features needed to make a quality editor experience. Enough of them now do that we were able to optimise the silver theme for mobile rather than continue to update the (very limited) mobile theme. Thus it has been deprecated.
