### ISSUE TITLE
TinyMCE 5: Margin inconsistency in Find and Replace dialog

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5012]
In Find and Replace dialog the last row of the form (the one with checkboxes) has no bottom margin. I think for consistency with other forms/dialogs that `.tox-form__grid` element should have `.tox-form__group` class added or the margin should be added in an other way.

Or the last row of the form in other places should have no margin-bottom.

**Comment by lostkeys** [comment]
Thanks! Appreciate your help finding all these small inconsistencies! We're about to revisit this dialog completely so I'm gonna close this ticket as this will not be an issue soon.
