### ISSUE TITLE
TinyMCE 5: Focus trapped in IE11

### ISSUE THREAD

**Issue by jburghardt** [tinymce/tinymce#5013]
**Do you want to request a *feature* or report a *bug*?**
 bug

**What is the current behavior?**

In IE11, the focus is trapped in the Menu.
The Menu should not be in the Tab order, due to tabindex -1

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Open https://www.tiny.cloud/docs/demo/full-featured/ in IE11
and tab trough the page

**What is the expected behavior?**

Tab from outside will focus the Editor edit area, the menu is only focusable trough hotkey.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

5.0.6

**Comment by Tjerk-Haaye-Henricus** [comment]
Hey w👋 

The reason is.. IE11 makes each svg tabbable with the `focusable` attribute. To solve this issue you guys have to add the attribute `focusable="false"` to the svgicons.

With Love from Tjerk ❤️
