### ISSUE TITLE
Remove duplicate span if spans contenteditable is set to false

### ISSUE THREAD

**Issue by YilmazErtugrul** [tinymce/tinymce#5014]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
I want to use the tinymce editor in a iPad app. In the editor im generating span's. For example a span looks like: <span id="1" contenteditable="false" ...>Text...</span>. If i click in the span the editor shows the identical span at the end of the content. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/HIgaab/1 (Use fiddle on iPad)

**What is the expected behavior?**
The expected behavior is: don't show the duplicate span

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce version: 5.0.4
browser: safari, but same behavior in the app (wkwebview)
theme: 'mobile' as u can see in the fiddle
device: iPad Air
softwareversion: 12.2

I tried several variants to detect the failure and it seems that the contenteditable property of the span does the bug. If contenteditable is set to true, there is no duplicate, if its set to false there is a duplicate.

Before click on span:
![Bildschirmfoto 2019-05-24 um 16 27 45](https://user-images.githubusercontent.com/39571120/58343048-634e3a80-7e52-11e9-8225-57222852a5f6.png)

After click on span:
![Bildschirmfoto 2019-05-24 um 16 27 54](https://user-images.githubusercontent.com/39571120/58343100-84af2680-7e52-11e9-93fc-8ef15934a005.png)

**Comment by YilmazErtugrul** [comment]
Any updates on this issue?

Best regards.

**Comment by ltrouton** [comment]
As of TinyMCE 5.1, the old mobile theme used in the fiddle is now deprecated and as such we'll only be making critical fixes for it. Have you tried using mobile on 5.1 and setting the mobile theme to silver? It should resolve this issue.
