### ISSUE TITLE
Add disabled attribute to checkboxes on dialog component

### ISSUE THREAD

**Issue by AnnaYuS** [tinymce/tinymce#5017]
Is there a way to add disabled attribute to checkboxes in a dialog component?
At the moment in Tinymce 5 you can have this configuration:
`{
  type: 'checkbox',
  name: 'checkbox-1',
  label: 'Checkbox Label'
}`

But in Tinymce 4 I could add `disabled: true` to the configuration and the checkbox would render as disabled.
Is there a new way to do it in Tinymce 5?

**Comment by TheSpyder** [comment]
It seems we overlooked this setting for checkboxes in the v5 UI. My apologies, I'll log a task to add it.

**Comment by lnewson** [comment]
Sorry for the late update on this, but this issue was fixed in TinyMCE 5.0.12. Please let us know if you have any further issues.
