### ISSUE TITLE
Link_List with only a single item is not updating the URL field in the Link dialog box

### ISSUE THREAD

**Issue by adrianlynch** [tinymce/tinymce#5024]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If the `link_list` value has only 1 item, you can select it from the Link List menu when editing/inserting a link, but the URL field is not updated and the choice is therefore not saved.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Demonstration here: http://fiddle.tinymce.com/gJgaab

Type in some text, select it and click the Insert/Edit link. Select the item from the Link List menu.

**What is the expected behavior?**

Ideally the Link List menu should have a default choice of 'Select...' with no value of nothing is set. Then when choosing the link from the menu the URL field should update with the selected choice.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE Cloud
MacOS Chrome Version 74.0.3729.169

**Comment by alecpl** [comment]
Confirmed with Firefox. The Link list select should have an empty ("unselected") item in any case. Then selecting any other link will work.

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.0.8, which has just been released to the community. Please let us know if you find any further issues.
