### ISSUE TITLE
tinymce module gives error during angular app compilation

### ISSUE THREAD

**Issue by iDoctorSolutions** [tinymce/tinymce#5025]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
 92% additional asset processing scripts-webpack-pluginx ?wdm?: Error: ENOENT: n
o such file or directory, open 'D:\github.com checkouts\xxxxx\node_modules\tin
ymce\themes\modern\theme.min.js'
    at Object.openSync (fs.js:438:3)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Not sure how to make the codebase into a minimal one to demonstrate the issue. I can't seem to find the relevant match for themes\modern.

**What is the expected behavior?**
I should not get this error.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
In package.lock.json i see tinymce 5.0.6

**Comment by TheSpyder** [comment]
TinyMCE 5 uses a new theme called silver, modern is specific to TinyMCE 4. If you are intending to upgrade to 5 you'll need to adjust the scripts to import silver instead, if you aren't then simply switch back to TinyMCE 4.
