### ISSUE TITLE
Promise needs a featurefill import since IE 11 doesn't have native support.

### ISSUE THREAD

**Issue by nodejh** [tinymce/tinymce#5027]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```sh
$ git clone https://github.com/tinymce/tinymce
$ yarn
$ grunt
Running "shell:tsc" (shell) task

Running "tslint:files" (tslint) task
>> ERROR: src/core/main/ts/api/util/Promise.ts:132:12 - Promise needs a featurefill import since IE 11 doesn't have native support.
>> ERROR: src/core/main/ts/api/util/Promise.ts:140:12 - Promise needs a featurefill import since IE 11 doesn't have native support.
>> ERROR: src/core/main/ts/api/util/Promise.ts:171:12 - Promise needs a featurefill import since IE 11 doesn't have native support.
>> ERROR: src/core/main/ts/api/util/Promise.ts:177:12 - Promise needs a featurefill import since IE 11 doesn't have native support.
>> ERROR: src/core/main/ts/api/util/Promise.ts:183:12 - Promise needs a featurefill import since IE 11 doesn't have native support.
>> ERROR: src/themes/silver/demo/ts/components/DialogComponentsDemo.ts:298:21 - Promise needs a featurefill import since IE 11 doesn't have native support.
>> 6 errors and 0 warnings in 1516 files
Warning: Task "tslint:files" failed. Use --force to continue.

Aborted due to warnings.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by brianlanger** [comment]
Having the same issue. Any workaround for this?

**Comment by TheSpyder** [comment]
Sorry. An update was pushed to our TSLint rules before the TinyMCE master branch was ready to be published (we're about to make a major change that restructures our open source projects into a monorepo).

For now, if you downgrade `@ephox/tslint-rules` to version `1.0.9` the build will work again. We will consider reverting the rules package until next week if this becomes a major problem.

**Comment by brianlanger** [comment]
Sorry for my late reply @TheSpyder, that did the trick, now everything builds perfectly.
Thanks!

**Comment by pkrstic** [comment]
Tried to build today still issue

**Comment by TheSpyder** [comment]
Correct, we haven't pushed the monorepo to github yet. We're still poking it to make sure everything works, it will be up either today or tomorrow.

**Comment by TheSpyder** [comment]
This should now be fixed.
