### ISSUE TITLE
How to use tinymce 5 with module loaders

### ISSUE THREAD

**Issue by mmarton** [tinymce/tinymce#5031]
Hi!

The docs at https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/
references skins and themes directories. They where part of the package in v4, so I assume the docs wasn't updated for v5.

**Do you want to request a *feature* or report a *bug*?**
outdated docs
**What is the current behavior?**
nothing
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

- yarn add tinymce
- try to import and build
 ```
These dependencies were not found:

* tinymce in ./assets/js/form/tinymce-type.js
* tinymce/plugins/link in ./assets/js/form/tinymce-type.js
* tinymce/plugins/paste in ./assets/js/form/tinymce-type.js
* tinymce/themes/modern/theme in ./assets/js/form/tinymce-type.js
```

**What is the expected behavior?**
works fine
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 5.0.6, webpack 4.4.32

**Comment by SimonFc** [comment]
Hi! Funny coincidence, I updated the Docs for that literally minutes ago. The new path for the default(silver) theme is of course `tinymce/themes/silver`. The skin directory is the same.

The changes should out sometime in the near future!
