### ISSUE TITLE
save button mobile version tinymce 5 

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#5032]
**Do you want to request a *feature* or report a *bug*?**

Set save button mobile version tinymce 5

**What is the current behavior?**

save button mobile version tinymce 5 is missing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment]
Thanks for the report, however that's currently expected as mobile only supports a select list of plugins: https://www.tiny.cloud/docs/mobile/#configuringtheplugins As such any plugin that's not supported is then disabled (see https://github.com/tinymce/tinymce/issues/4848 for more information which is a similar issue).

Just as a heads up we're planning to be doing a lot of work with mobile later this year which should hopefully allow us to support a much larger set, if not all plugins.
