### ISSUE TITLE
TinyMCE 5: can't use space at the end of line in ordered lists

### ISSUE THREAD

**Issue by elhuscoro** [tinymce/tinymce#5034]
I would like to report a bug.

**Current**
Currently, when creating ordered lists with nested lists, the user can't modify and existing line properly. When starting to add text to the end of the line that is the parent of a nested ordered list, adding a space has no effect and the written text is concatenated.

**Reproducing the bug**
You can reproduce the bug in the following demo: https://codepen.io/anon/pen/VOOxGw
Try to start **typing** text (e.g. 'Lorem ipsum dolor etc.') at the end of the 3rd line or at the end of lines 3.2, 3.2.1, 3.2.1.1. The text gets concatenated to 'Loremipsumdoloretc.'.

**Expected behavior**
When adding new text to the end of the line, the spaces should stay in place so that the input isn't concatenated together. Just like how it works in FireFox.

**Versions afffected**
5.0.3+, MacOS/Windows, **Chrome** browser Version 74.0.3729.169 (Official Build) (64-bit).

**Comment by joshuakent** [comment]
I'm having this same issue in 5.0.6

**Comment by Jimmy-Bowden** [comment]
I'm also having this issue on 5.0.6 and 4.9.3

**Comment by blackcathikari** [comment]
Thanks for the report! This is a known issue that we have already logged internally. We don't have a schedule for releasing a fix yet, but we'll keep this ticket updated with progress.

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.0.8, which has just been released to the community. Please let us know if you find any further issues.
