### ISSUE TITLE
incorrect font selected in fonts dropdown using legacyoutput plugin

### ISSUE THREAD

**Issue by joaopgg** [tinymce/tinymce#5038]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Using legacyoutput plugin, when we select a word and change the font size, the fontsizes dropdown has the incorrect value selected

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/9Lfaab/7

**What is the expected behavior?**
The fontsizes dropdown -> selected value should be the one selected in the dropdown options

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
In all the v5 releases

**Comment by lnewson** [comment]
Thanks for the report! This is a known issue and is something that has actually already been fixed in master and is currently scheduled to be included in TinyMCE 5.0.8.

**Comment by joaopgg** [comment]
Thanks for the quick reply. 
Yes, I tested using tinymce5-cloud-dev and the problem is fixed.
One more question: When do you guys expect to release the 5.0.8 version?

**Comment by lnewson** [comment]
TinyMCE 5.0.8 has just been released, so you should just be able to update directly now.

**Comment by joaopgg** [comment]
Thanks guys.
