### ISSUE TITLE
*feature* toolbar_drawer: 'sliding' call inside plugin

### ISSUE THREAD

**Issue by stastka** [tinymce/tinymce#5041]
*feature* 

I try to access "sliding" feature from toolbar_drawer. 
It's possible inside plugin to call "More..." button? (=> "tox-toolbar__overflow--open") to show hidden button. 

TinyMCE 5.0.7, WIndows 10, Chrome/FF Latest

**Comment by lnewson** [comment]
You could theoretically manually send a click event to the button which should trigger it, but there isn't any supported API/way to toggle the toolbar drawer atm. I'll mark this as a feature request so the team can evaluate it further.

**Comment by brittanytang** [comment]
The "More..." button  has no element id or a specific class that would identify it via CSS selector.  Other than using the aria-label or title, which would cause issues when switching languages, is there another way to get the button in order to send the click event?
