### ISSUE TITLE
Table removing

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5043]
**What is the current behavior? Describe the bug**
Table doesn't remove when press backspace in the end of table or delete in the start of the table
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1.Insert table
2.Put cursor to end or start of table
3.Try to remove it by backspace/delete
**What is the expected behavior?**
Table removes
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0+

**Comment by lnewson** [comment]
Thanks for the report, however this is working as expected and works the same was as both Word and Google Docs, so it's designed that way to keep the editing experience consistent.

**Comment by TimMTech** [comment]
How does that even answer the question?  Is there a solution?
