### ISSUE TITLE
TypeError: r.parser is undefined

### ISSUE THREAD

**Issue by jonathonklem** [tinymce/tinymce#5044]
With the latest firefox update, once tinymce is initiated, the content becomes invisible.  

If I try to setContent, I get the following: 

`TypeError: r.parser is undefined`

My textarea:
`<textarea id="DESCRIPTION" name="DESCRIPTION" class="textarea" style="display: none;" aria-hidden="true">&lt;p&gt;Homepage&lt;/p&gt;</textarea>`

My init code:
```
tinyMCE.init({
                theme : "advanced",
                mode: "exact",
                elements : "DESCRIPTION",
                //plugins : "paste",
                theme_advanced_toolbar_location : "top",
                theme_advanced_buttons1 : "bold,italic,underline,strikethrough,separator,"
                + "justifyleft,justifycenter,justifyright,justifyfull,formatselect,"
                + "bullist,numlist,outdent,indent",
                theme_advanced_buttons2 : "pasteword,separator,link,unlink,anchor,image,separator,"
                +"undo,redo,cleanup,code,separator,sub,sup,charmap,forecolor,backcolor",
                theme_advanced_buttons3 : "",
                setup : function(ed) {
                        var span = document.getElementById('wc-' + ed.id);
                        if(span)
                        {
                                var charlimit = span.innerHTML;
                                ed.onKeyDown.add(function(ed, e) {
                                        charcount = charlimit - $(ed.getBody()).text().length;
                                        span.innerHTML = charcount;
                                        if ( charcount <= 0 && !(e.keyCode == 8 || e.keyCode == 46  || e.keyCode == 37 || e.keyCode == 38 || e.keyCode == 39 || e.keyCode == 40) ){
                                                e.preventDefault();
                                                e.stopPropagation();
                                                return false;
                                        }
                                });
                        }
            } 
        });
```

If I call the following, I get the error:
`tinyMCE.get('DESCRIPTION').setContent('test');`

Firefox version is 67.0.2 (64-bit) on Mac OSX

**Comment by lnewson** [comment]
@jonathonklem what version of TinyMCE are you using? and can you please provide a fiddle showing how to replicate the issue?

Given that you have `theme: 'advanced'` in your configuration though, among other things, I'm guessing you're using TinyMCE 3.x, which isn't supported anymore unfortunately. I tried to replicate using a similar [fiddle](http://fiddle.tinymce.com/NKgaab) on 4.x and 5.x, but it worked as expected using the same version of Firefox on Mac OSX locally.

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
