### ISSUE TITLE
forced_root_block: div with block formats

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5046]
**What is the current behavior? Describe the bug**
TinyMCE convert few div blocks into div + div>div*quantity blocks^ + div, when user applies block formats, with paragraphs that won't be repeated
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1.Set forced_root_block: 'div'
2.Type few lines(with line breaks by enter)
3.Ctrl+a
4.Apply any block format(for example blockquote)
**What is the expected behavior?**
Applying formats saves original html and don't convert it
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0

**Comment by wonderbugtiny** [comment]
@versusvirus I would like to get more clarity on what you expect the behaviour to be. Please apply the `blockquote` to the below HTML snippet and provide us with a snippet of what the expected output should look like. Thank you!

```
<div>Welcome</div>
<div>to</div>
<div>TinyMCE</div>
<div>Demo</div>
```

**Comment by versusvirus** [comment]
> @versusvirus I would like to get more clarity on what you expect the behaviour to be. Please apply the `blockquote` to the below HTML snippet and provide us with a snippet of what the expected output should look like. Thank you!
> 
> ```
> <div>Welcome</div>
> <div>to</div>
> <div>TinyMCE</div>
> <div>Demo</div>
> ```

If i use blockquote to that HTML i expect 
<blockquote>
  <div>Welcome</div>
  <div>to</div>
  <div>TinyMCE</div>
  <div>Demo</div>
</blockquote>

**Comment by wonderbugtiny** [comment]
@versusvirus Thank you for providing the additional information. The behaviour you are expecting is how TinyMCE currently behaves. You can check it out in the fiddle here: http://fiddle.tinymce.com/2Ogaab
Please help us understand the issue by clarifying what you are seeing that is unexpected.

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
