### ISSUE TITLE
Problem to add a custom formats select

### ISSUE THREAD

**Issue by uselessdev** [tinymce/tinymce#5047]
**What is the current behavior? Describe the bug**
I following [this docs](https://www.tiny.cloud/docs/demo/format-custom/) to add custom formats, this works fine *if* I omit the `toolbar` property in `init`.

**What is the expected behavior?**
Would be nice if was possible to setting up custom format in that way and still use toolbar.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- TinyMCE v5
- Chrome
- macOS Mojave
- idk

**Comment by lnewson** [comment]
@uselessdev can you please provide a fiddle, or more details on what's not working? because as you can see in the demo in the linked docs, custom formats do work with the toolbar enabled.

**Comment by uselessdev** [comment]
Hi @lnewson 

I made a mistake when I trying to add custom formats in `init`, I use this:

```js
.init({
  // ...
  toolbar: 'undo redo | formatselect '
})
```

then [here](http://fiddle.tinymce.com/) I just realize the `styleselect` and using this instead `formatselect` its just works, but I don't know why 😭 

Well, I'll close this issue, thank you for the reply 😊
