### ISSUE TITLE
Version 5.0.8 - ContextMenu Plugin Bug - Always at X:0 and Y:0

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#5049]
Press right click on the document and the ContextMenu will be always at X:0 and Y:0. Tested in the latest version of Firefox.

http://fiddle.tinymce.com/WKgaab

![screenshot](https://user-images.githubusercontent.com/11498901/59958657-8fc09b00-9480-11e9-8663-25a1d83bdb40.png)

**Comment by lnewson** [comment]
I can confirm this behaviour and it appears to be caused by setting `forced_root_block` to false. As the target for the right click ends up becoming the body element and therefore it thinks it's a keyboard contextmenu event and tries to open relative to the body element.

**Comment by lnewson** [comment]
Just as an example, if you wrap the content in a div then it works correctly: http://fiddle.tinymce.com/WKgaab/1

**Comment by lnewson** [comment]
Hi @lrusso,

I was looking at this again today and I realised we actually fixed this issue in TinyMCE 5.1.6 when fixing a related issue. As such I'll go ahead and close this, but please do let us know if you're still experiencing issues.

Thanks!
