### ISSUE TITLE
Spellchecker Plugin Left Click Feature Request

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#5051]
In the SpellChecker Plugin, I was wondering if it would be possible to consider a feature/option that would allow to do a left click in a word in order to show the suggestions menu. That is how it worked in 4.9.4 and it was useful when the ContextMenu was disabled. In 5.0.8, if there is no ContextMenu, there are no suggestions.

**Comment by alecpl** [comment]
See #5003.

**Comment by lnewson** [comment]
As @alecpl said this was intentional since it's very uncommon to have left click open a context menu.

I'll mark this as a feature request still though, so our Product Management teams can decide if we do want to look at supporting this or not.

**Comment by lrusso** [comment]
Thank you both for the reply. The reason of this request is that in a mobile device, when using TinyMCE, the ContextMenu must be disabled in order to use the default/system context menu that allows the mobile user to copy the document to the clipboard. Otherwise there is no way to extract/copy the TinyMCE document in a mobile device. The Standard copy function says that the browser doesn't allow copy/paste and that the user must use CTRL+X/CTRL+C/CTRL+V which are not available in a mobile device with a standard configuration.

A ContextMenu plugin disabled with the SpellChecker plugin with a left click optional feature, allows a mobile user to cut/copy/paste and also to spellcheck the document.

Hope it may helps!

**Comment by TheSpyder** [comment]
If you're on mobile, set browser_spellcheck` to true and use the device dictionary. It may become the mobile default in future. We don't test or optimise the spell checker on mobile because all mobile devices include a built in spell checker.

**Comment by alecpl** [comment]
Please, note that some systems that integrate HTML editor provide spellchecking dictionary with possibility to add words/exceptions to it. If I use browser spellcheck I have no access to this dictionary. The point for a dictionary is to have the same experience on all devices I use.
