### ISSUE TITLE
Toolbar Group Labels

### ISSUE THREAD

**Issue by claydiffrient** [tinymce/tinymce#5052]
**Is your feature request related to a problem? Please describe.**
It's tedious for users of screen readers to have to drill into each of the toolbar groups to determine which buttons that are contained within.

**Describe the solution you'd like**
I'd like the ability to set a label for a group of toolbar buttons.  I'm not sure what the API to do that would look like.  Perhaps
```
toolbar: [
        'fontsizeselect formatselect | bold italic underline forecolor backcolor superscript ' +
        'subscript | align bullist outdent indent directionality'
]
toolbar_labels: [ ' font styles |  font formatting | alignment and positioning']
```
Then an `aria-label` could be added to each of the `role="toolbar"` to give additional context.

**Describe alternatives you've considered**
None.

**Comment by lnewson** [comment]
This is actually already possible in TinyMCE 5, it's just that the docs haven't been published yet, though they should be live next week hopefully. Here's the PR for the `toolbar` format to use if you need headings: https://github.com/tinymce/tinymce-docs/pull/1074/files
