### ISSUE TITLE
Comments cannot be closed and deleted

### ISSUE THREAD

**Issue by yjqxq** [tinymce/tinymce#5053]
Comments cannot be closed and deleted
I uploaded the video to the Google Drive.
[https://drive.google.com/file/d/170Pb3Aar-a4ejbgcGlx0AOj4jdvxuPTV/view?usp=drivesdk
](url)

**Comment by TheSpyder** [comment]
I'm not sure what you're expecting.

* clear clears the input textarea (the "say something" box). The toolbar button is "add comment", to hide the sidebar use the view menu (show comments is the toggle option). I agree this is not great UX, but it's working as intended right now.
* in the video you cancel the delete prompt (the non-destructive action is in blue, the destructive one is grey).

If you are a premium customer having issues with our comments plugin please [log a support case](http://support.tiny.cloud).
