### ISSUE TITLE
Media plugin: add support for embedding Twitch

### ISSUE THREAD

**Issue by danaki** [tinymce/tinymce#5054]
Don't know what to add, it described in the subject. I've checked the source code and it would be trivial. Need PR?

Instructions https://dev.twitch.tv/docs/embed/video-and-clips/

**Comment by blackcathikari** [comment]
I've marked this as a feature request, but it is not a high priority task for us right now. Feel free to make a PR if you would like to.

As another option, our Enhanced Media Embed plugin already supports Twitch.
