### ISSUE TITLE
Translations are not reflected in "Special characters" modal

### ISSUE THREAD

**Issue by ginlime** [tinymce/tinymce#5055]
**What is the current behavior? Describe the bug**
Translations are not reflected in Special characters' "title" property.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Apply some language file to TinyMCE.
2. Show "Special characters" modal.
3. Place mouse cursor to any special character.
4. Tooltip will be display. And its texts are still written in English.

**What is the expected behavior?**
The texts of tooltip of special character are written in applied language.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

5.0.9

**Comment by wonderbugtiny** [comment]
Please note that this has been fixed in 5.0.11. Let us know if you have any further issues. Thank you!
