### ISSUE TITLE
How to make "tinymce textarea" appear on the page instead of through the button

### ISSUE THREAD

**Issue by tak40548798** [tinymce/tinymce#5057]
How to make "tinymce textarea" appear on the page instead of through the button

as follows:
![tinymce](https://user-images.githubusercontent.com/35030964/60426585-84f7ca00-9c27-11e9-9767-b4aa3579a6c2.jpg)

So I changed another CDN

```
<script src="https://cloud.tinymce.com/dev/tinymce.min.js"></script>
<script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=?"></script>
```

The result is like this
![mobile](https://user-images.githubusercontent.com/35030964/60426874-2252fe00-9c28-11e9-8de4-821d71383ae5.png)

But it will pop up "This domain is not registered with TinyMCE Cloud. Start a free trial to discover our premium cloud services and pro support."

I am sure I have input api-key
Which CDN should I use?

**Comment by TheSpyder** [comment]
Your first screenshot is showing the mobile theme which we enable by default on mobile devices in TinyMCE 5. We are aiming to have a new mobile experience in version 5.1 which does not rely on the "tap to edit" experience.

Your second screenshot is TinyMCE 4, which doesn't have this behaviour. If you're using an API key the error indicates you haven't registered the domain you're using with your account.
