### ISSUE TITLE
Website shows version 5.0.10 as old

### ISSUE THREAD

**Issue by Gappa** [tinymce/tinymce#5065]
This URL displays 5.0.9 as the newest version and 5.0.10 is in the table below with other older ones:

- https://www.tiny.cloud/get-tiny/self-hosted/

However, changelog is not affected and shows 5.0.10 at the top:

- https://www.tiny.cloud/docs/changelog/

There is most probably an error when comparing version numbers to decide which version is the latest.

**Comment by lnewson** [comment]
Thanks for letting us know! We've passed the issue onto our website team to get the issue fixed.

**Comment by lnewson** [comment]
This issue has been now been fixed, so that 5.0.10 is showing as the latest version.
