### ISSUE TITLE
image_class_list not respected when drag&drop

### ISSUE THREAD

**Issue by tomaszmadeyski** [tinymce/tinymce#5069]
Let's say we have `image_class_list` defined as follows:

```
 image_class_list: [
    { title: 'First default class', value: 'first-default-class' },
    { title: 'Second class', value: 'second-name' }
  ],
```

When inserting new image using icon from toolbar an image which is inserted has first class from the list (`first-default-class`) assigned.

However, when doing drag & drop, inserted image has no class at all, which IMO is a bug:
I define set of classes and I expect first of these to be default class assigned to every image by default, no matter if I insert this image using TInyMCE button from toolbar or drag & drop.

** Steps to reproduce **

1. Go to [this fiddle](https://codepen.io/anon/pen/bPjqGr?&editable=true)
2. Try to insert image by clicking TinyMCE button in toolbar
3. Preview html source code by using TinyMCE "code" button
4. Observe that inserted image has `first-default-class` assigned => GOOD!
5. Drag & drop any image to TinyMCE
6. Preview html source code by using TinyMCE "code" button
7. Observe that inserted image has no class at all => NOT GOOD!

![draganddrop](https://user-images.githubusercontent.com/1555694/60670126-312bf180-9e70-11e9-8c3c-4b67486a3aab.gif)

**Comment by TheSpyder** [comment]
Image drag & drop is not handled by the image plugin, it's part of the paste code. If you remove `powerpaste` from the plugin list in your demo image drag & drop doesn't work at all.

This is a bug in a premium plugin; if you are a premium customer please [log a support case](https://support.tiny.cloud/hc/en-us) so we can properly prioritise it.
