### ISSUE TITLE
Unselected dropdown prevents typing (keyboard input)

### ISSUE THREAD

**Issue by DocBrown101** [tinymce/tinymce#5070]
**What is the current behavior? Describe the bug**
Nothing can be entered with the keyboard.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Open this link in Microsoft Edge: https://www.tiny.cloud/docs/demo/full-featured/
Simply open a dropdown with the mouse. Now close the dropdown without selecting anything. Best is to click 1x in the text field of Tiny.
Now nothing can be entered with the keyboard.

**What is the expected behavior?**
Keyboard inputs

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Appears only in Microsoft Edge!
Edge version 44.18362.1.0
TinyMCE version 5.0.11

**Comment by ltrouton** [comment]
Hi @Paradoxon101. Thanks for the report! I can confirm that this is a bug and have created an issue internally for us to investigate it. We will let you know when we have an update.

**Comment by ltrouton** [comment]
It appears that this issue was indirectly fixed by a change made in v5.1.3. Can you confirm that the issue can no longer be reproduced in the latest version of TinyMCE?

**Comment by trevorjay** [comment]
I can confirm this seems to have been fixed in 5.1.3 and is no longer reproducible in either the latest 4 or 5 release (Edge and IE11). Anyone still experiencing this problem should let us know.
