### ISSUE TITLE
Change default language for spellchecker list

### ISSUE THREAD

**Issue by srimoyeesen** [tinymce/tinymce#5072]
Earlier in the 3.x version , Adding a '+' before a language made it the default selected language in the list. Unable to do the same in version 5. In this, the default is always selected to English inspite of modifying the list.

**Comment by ltrouton** [comment]
Hi @srimoyeesen. Thanks for posting! In Tiny 5, the default spellchecker language can be changed using the config setting, `spellchecker_language: 'en'`. Here is the relevant documentation for spellchecker: https://www.tiny.cloud/docs/plugins/spellchecker/#spellchecker_language

The list of supported languages and their associated codes can be seen [here](https://www.tiny.cloud/docs/configure/localization/#language)

Please let us know if this is what you were looking for.

**Comment by srimoyeesen** [comment]
Thanks a lot, it solved my query
