### ISSUE TITLE
Uploading local image to tinymce and show up

### ISSUE THREAD

**Issue by ecjoin** [tinymce/tinymce#5073]
I'm using Wordpress to build my website.
I'm using WP Job manager plugin
and I want my website user can upload image via job submission page.
I'd try to work with the wp-includes/class-wp-editor.php
and I've add the upload.php(image upload handler)
And I've add the upload tab at image dialog successfully
However it keeps showing"HTML Error 404"
The upload function doesn't work.
Afterwards I change to the file picker instead,
the image appears inside the editor but it disappears after submit.
There is nothing UPLOADED to my server.

Can anybody help on this?
Nomatter image upload nor file picker....Thanks a lot.

**Comment by wonderbugtiny** [comment]
Hi @ecjoin, If you could provide us with your `tinymce.init()` config we will have a look at your image upload handler setup. However, we would not be able to help you with server-side configuration. If you have any questions regarding the Wordpress TinyMCE plugins, we recommend reaching out to WordPress support: https://wordpress.org/support/plugin/tinymce-advanced/

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
