### ISSUE TITLE
Menu Item "Special charater..." is not translated into German

### ISSUE THREAD

**Issue by krichter722** [tinymce/tinymce#5074]
**What is the current behavior? Describe the bug**
The menu item text "Special characters" is not translated into "Sonderzeichen" when using the German language pack.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Add up-to-date translation file for German from https://www.tiny.cloud/get-tiny/language-packages/ and open the menu "Insert"/"Einfügen".

**What is the expected behavior?**
The menu item text "Special characters" should be "Sonderzeichen" which is also used in the title of the opening dialog (fixed in #5055).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I checked Firefox 67.0.4 and Chorme 75.0.3770.90 on Ubuntu 19.04. It worked fine in 4.x.

**Comment by wonderbugtiny** [comment]
Hello @krichter722, thanks for the report! "Special character..." is a known missing string and we have logged a task internally to get it added to Transifex. We will update you when a fix is available

With that being said, there is also an option of adding the strings to the translation file by yourself, as demonstrated in the fiddle here: http://fiddle.tinymce.com/wMgaab

**Comment by krichter722** [comment]
Thanks for your reply @wonderbugtiny . The workaround is useful. How hard would it be to get the translation mapping (is already correctly translated in the dialog title) into tinymce? Do you have a link to instructions. Then I could open a PR.

**Comment by krichter722** [comment]
Unfortunately, the workaround overwrites the translation for `de` causing everything to be in English except for "Sonderzeichen...". If you tell me how to fix the translation, I'll see if I can provide a PR.

**Comment by wonderbugtiny** [comment]
@krichter722 Sorry, I should've clarified more in my response that the fiddle shows an example of how to add the string to your translation file. Please add the string and its translation to your `de.js` file. Here is the link with more information on language localization:
https://www.tiny.cloud/docs/advanced/creating-a-plugin/#languagelocalization

We are going to be adding the missing strings to Transifex ourselves. I am afraid, creating a PR isn't an option as it's not part of TinyMCE. We will update you once the translations are available. Thank you!

**Comment by krichter722** [comment]
Please add

```
"Special character...": "Sonderzeichen...",
```

next to

```
"Special characters...": "Sonderzeichen...",
```

(note the singular and plural).

I assume that plural is used in the dialog title, otherwise I don't see a reason why the translation should work there.

**Comment by wonderbugtiny** [comment]
@krichter722 The `character` string is singular in the dialog title as well. The difference is that the menu item has an ellipsis(`...`) at the end of the string. We will keep you posted!

**Comment by lnewson** [comment]
Hi,

I just checked the latest German language packs and ie now includes the correct source string (without the s):
```
"Special character...": "Sonderzeichen...",
```
I'm not sure when this was resolved, but I suspect it might have been when the TinyMCE 5.1 translations were pushed into transifex. Anyways, since this issue has been resolved I'm going to go ahead and close this. If you have any further issues, please let us know.
