### ISSUE TITLE
Version 5.0.11 - Table bug - The second table cannot merge any cells

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#5078]
The second table cannot merge any cells. After selecting the merge option with a few cells in the second table, nothing happens and then the first table is automatically selected. Tested in the latest version of Firefox.

http://fiddle.tinymce.com/LMgaab

**Comment by wonderbugtiny** [comment]
Hello @lrusso, thanks for the report! I was able to replicate the behaviour in Firefox 67.0.4 and have logged a ticket internally for us to work on the issue. We will update you when a fix is available.

**Comment by LinZhouWebDev** [comment]
Possibly the same behaviour as #4914 due to how Firefox handle cell selection?

**Comment by blackcathikari** [comment]
A quick note from checking this: I used @lrusso's fiddle linked above, and was able to reproduce this in 5.0.11 on MacOS Firefox, though I can't seem to find the Firefox version on this machine apart from it being a potentially old version of Quantum. I can't reproduce it using a table with empty cells on 5.0.13, but when the cells contain content you still can't merge them.

I agree that this is probably related to #4914
