### ISSUE TITLE
Version 5.0.11 - Spellchecker bug and bugfix - Deleting selected word when forced_root_block = false 

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#5080]
Click in the spellchecker icon and click in the 'esample' word in the document and then select the suggestion 'example' from the SuggestionMenu. When **forced_root_block = false** the spellchecker will delete the word that is selected from the SuggestionsMenu ONLY when that word is at the beginning of a paragraph/section/breakline.

http://fiddle.tinymce.com/dNgaab

The way I found out to fix this, in my server where I use TinyMCE 4.9.4, is by swapping the following lines 701 and 702 from:

```
editor.insertContent(editor.dom.encode(suggestion));
editor.dom.remove(spans);
```

to:

```
editor.dom.remove(spans);
editor.insertContent(editor.dom.encode(suggestion));
```

Source file:

https://github.com/tinymce/tinymce-dist/blob/master/plugins/spellchecker/plugin.js

Hope it may help!

**Comment by ltrouton** [comment]
Hi @lrusso. I couldn’t replicate the issue. It would be helpful if you could please provide a video of the issue as well list your OS, browser and version of Tiny you are using (you have noted 5.0.11 in the title but 4.9.4 in the body). Thanks!

**Comment by ltrouton** [comment]
I can confirm that this is a bug after testing on Firefox. I have created an issue internally for us to investigate it. We will let you know when we have an update.

**Comment by lrusso** [comment]
Sorry, I forgot to mention that this bug was tested in the latest version of Firefox and that this bug is present in TinyMCE 4.9.4 and TinyMCE 5.0.11.
