### ISSUE TITLE
Copying and pasting HTML does not work correctly.

### ISSUE THREAD

**Issue by DocBrown101** [tinymce/tinymce#5081]
**What is the current behavior? Describe the bug**
Fonts can be lost when copied and many useless CSS formatting that does not exist in the original HTML is inserted.

**Minimal demo of the problem:**
Open the demo in microsoft edge.
http://fiddle.tinymce.com/jNgaab/2
Copy the three lines from above into the TinyMCE below.
Open the Source Code View of TinyMCE.
The font of the 1st line no longer exists.
Many useless CSS formatting now present.

**What is the expected behavior?**
The HTML code will be adopted without changes and displayed in TinyMCE.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Appears only in Microsoft Edge!
Edge version 44.18362.1.0
TinyMCE version 5.0.11

Only detected in version 5.

**Comment by PDFCoder** [comment]
The problem also appears in version 4.9.5

**Comment by EkimChau** [comment]
Hi DocBrown101, this is a won't fix issue related to legacy Edge, the new chromium based edge should not have this issue, we would recommend using Chromium edge
