### ISSUE TITLE
Problem with Insert Date/Time Plugin

### ISSUE THREAD

**Issue by mila-mila** [tinymce/tinymce#5084]
I have noticed a problem with toolbar items localization.
When displaying current date/time in french language, drop-down items are shown in raw html codes, like:
instead of showing letter 'û', in the menu there is '&‌ucirc;'. Month of august in french is shown as "Ao&‌ucirc;t" instead of "Août".
When date is inserted in editor area, it appears correctly, only toolbar has the problem.

This is the first time I am submitting an issue, so I hope this is the correct procedure.

I have made a simple solution by adding a line of code to plugin.  Is it possible to include this or similar solution to the plugin. I am using it in a .NET project version of plugin 4.5.0.

By the end of function function getDateTime(fmt, date) {
I add a line that encodes the text like this:
```
fmt = $('<div/>').html(fmt).text();
        return fmt;
    }
```
or in minified version like this:
`a = $('<div/>').html(a).text();`

This is how it looks before the fix:
![bug](https://user-images.githubusercontent.com/6826741/43651395-8545855a-9742-11e8-8507-e854dc871675.png)
This is how it looks after the fix:
![fix](https://user-images.githubusercontent.com/6826741/43651399-878ad50e-9742-11e8-9fb9-dc353c8decab.png)

**Comment by TheSpyder** [comment]
This is a result of forcing menu item text to be in plain text. Which language pack are you using? I don't think the month and day names are actually translated in our language packs (oops).

**Comment by lnewson** [comment]
Closing this due to lack of additional information and the fact that this seems related to an incorrect translation instead. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
