### ISSUE TITLE
Problem with page reference/configuration/Configuration3x@cleanup.md

### ISSUE THREAD

**Issue by karelcech** [tinymce/tinymce#5085]
Hi, the cleanup set to false really disables some html modification, but for example

        <td style="width: {if $fields.hide_discount_on_pdf_c}175{else}137{/if}px;" class={if $idx is div by 2}"normalProductRow"{else}"coloredProductRow"{/if}>{$product.description}</td>

is still transformed to

<td style="width: {if $fields.hide_discount_on_pdf_c}175{else}137{/if}px;" class="{if" idx="" is="" div="" by="" 2="" normalproductrow="" else="" coloredproductrow="" if="">{$product.description}</td>

> *affected page: https://www.tinymce.com/docs-3x//reference/configuration/Configuration3x@cleanup/*

**Comment by MichaelFromin** [comment]
TinyMCE 3 is no longer actively maintained so this issue will not be addressed.
