### ISSUE TITLE
Referer in request header not send in image preview

### ISSUE THREAD

**Issue by meta-manish-sharma** [tinymce/tinymce#5087]
Hi,

I used TinyMCE for image upload. After uploading an image on amazon when I preview it.
The referer in the request header of my site is not sending with getting image request.

Please review the request headers

Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Connection:keep-alive
Host:meta-placement-new.s3.amazonaws.com
If-Modified-Since:Thu, 25 May 2017 06:30:04 GMT
If-None-Match:"2adc92f80d75421bdc9184fa6cf7b7f7"
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by wonderbugtiny** [comment]
@meta-manish-sharma I would like to get more clarity on the issue you are experiencing. Does this issue still exist? And if it does, could you please provide us with the steps to replicate and/or a video demonstrating the behaviour. Also, please let us know the TinyMCE version and browser you are using. Thank you!

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
