### ISSUE TITLE
Bug with firefox in bootstrap modal (inline mode)

### ISSUE THREAD

**Issue by cyrilus** [tinymce/tinymce#5094]
When using firefox (test with 60.8.0esr and 68.0.1 on linux)
with tinymce last version (inline) in a modal when the modal is so long that it require a scrollbar
then the toolbar or menu just disappear when we try to click on it

here is a fiddle to reproduce it
http://fiddle.tinymce.com/ANgaab/29

It work with chrome

**Comment by lnewson** [comment]
@cyrilus this appears to be because on Firefox the modal is grabbing focus, which isn't happening on Chrome. As such if you add the editor to the focusin selector, then that appears to fix the issue: http://fiddle.tinymce.com/ANgaab/30

**Comment by cyrilus** [comment]
Thanks a lot that the solution
