### ISSUE TITLE
Noneditable element is editable when selection.setContent is applied

### ISSUE THREAD

**Issue by vctormb** [tinymce/tinymce#5095]
**What is the current behavior?**
I'm using the `noneditable` plugin to not be able to edit elements with a specific class.  
If I use `setContent` to append a new element with a noneditable class it doesn't work. The `noneditable` content only works if I set it through `initialValue` prop.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
https://codesandbox.io/s/tinymcereact-di17r

**What is the expected behavior?**
To not be able to edit the content when I use `setContent` to append an element with a noneditable class.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**  

**I'm using:**  
- `@tinymce/tinymce-react: 3.1.1`  
- `tinymce: 5.0.7`

**Comment by SimonFc** [comment]
Actually it's confusing to have it at tinymce-react, transfering to tinymce:)
