### ISSUE TITLE
yarn install fails - http://nexus:8081 not available

### ISSUE THREAD

**Issue by warrenbuckley** [tinymce/tinymce#5099]
**What is the current behaviour? Describe the bug**
I have cloned the repository and followed the readme to do `yarn install` but this fails due to a package not being able to be cloned/fetched due to a local URL

>error An unexpected error occurred: "http://nexus:8081/repository/npm-group/@ephox/wrap-promise-polyfill/-/wrap-promise-polyfill-2.2.0.tgz: getaddrinfo ENOTFOUND nexus nexus:8081".

**Comment by zhixinpeng** [comment]
I also encountered this situation, I thought it was my network problem

**Comment by lnewson** [comment]
Sorry about this, we missed that a recent update to our katamari project used an internal dependency. We published the dependency last week after https://github.com/tinymce/tinymce/issues/5093 was logged but missed updating the yarn.lock file. As such, we've just pushed a fix to master, so you shouldn't encounter this issue anymore when running yarn install.
