### ISSUE TITLE
Uncaught Error: Could not find more button element

### ISSUE THREAD

**Issue by IamFonky** [tinymce/tinymce#5100]
**What is the current behavior?**
The editor throws an error after using a custom button and closing the toolbar.
It seem to be related with custom buttons and floating toolbar.

**Error reproduction steps

1. Go to  [this demo](https://codesandbox.io/s/unruffled-bhaskara-qkcwp)
2. Click on the text to make the toolbar appear (the green zone)
3. Click on the [...] button to expand the toolbar
4. Click on the [test] button to apply test class
5. Click on the outside of the editor (the white zone)

1. (Optionnal) Click on the top button
2. Try again without floating toolbar and it should be no error.

**What is the expected behavior?**

Close the editor without error and allows to reuse it by clicking again on the text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
@tinymce/tinymce-react : 3.2.0
Browser : Firefox + Chrome (last version)

**Comment by lnewson** [comment]
I was able to reproduce this issue outside of the react wrapper (http://fiddle.tinymce.com/ZNgaab), so I've moved this over to the core TinyMCE project.

**Comment by juliorosseti** [comment]
I had the same problem, but not with React. TinyMCE V5.0.13

**Comment by sontek** [comment]
Having this issue as well

**Comment by glenfordwilliams** [comment]
having this issue now as well

**Comment by sebastienheyd** [comment]
This also happens when you click on the [...] button and you resize the window to make appear all buttons.

**Comment by ntnyq** [comment]
Having this issue with `tinymce 5.1.3` and `@tinymce/tinymce-vue 3.0.1 `

**Comment by lnewson** [comment]
Just to give an update on this, we're aware of the issue and unfortunately it's not a simple fix. We're currently working on a fix though and it should hopefully be included in TinyMCE 5.2.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue. You should no longer get the `Uncaught Error: Could not find more button element` exception when using the floating toolbar drawer. Please let us know if you have any further issues.
