### ISSUE TITLE
Image Upload Progress Notification Closed Immediately 

### ISSUE THREAD

**Issue by Daekard** [tinymce/tinymce#5101]
**What is the current behavior? Describe the bug**
On uploading an image via drag and drop a notification is opened displaying a progress bar indicating the overall upload progress. This notification is then immediately closed before the upload is complete.

**Steps to reproduce**

1. Configure `images_upload_url` option with appropriate URL
2. Upload an image via drag and drop
3. Note the progress notification is only briefly visible or not visible at all

At present, it appears that the progress notification is opened with a configured timeout of `-1`. In previous versions the timeout when opening a notification value was ignored if not `> 0`. As this is no longer occurring the notification is closed at the minimum timeout threshold.

**What is the expected behavior?**
The progress notification should remain open and updated until either the success or failure callbacks are invoked.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Affects version 5.0.12.
Worked in version 4.8.5.

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.0.14, which has just been released to the community. Please let us know if you have any further issues.
