### ISSUE TITLE
Rendering custom web component in Sidebar freezes sidebar in transition

### ISSUE THREAD

**Issue by DerangedMind** [tinymce/tinymce#5102]
**What is the current behavior? Describe the bug**
When including a custom web component to the innerHTML of a toggleable sidebar, the sidebar gets stuck in transition and the `style="width: 0"` is never removed. 

This can be seen by classes still being applied to the `.tox-sidebar__slider` element: `tox-sidebar__slider tox-sidebar--sliding-growing tox-sidebar--sliding-open`.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Create a custom component:

```typescript
import { LitElement, TemplateResult, html } from 'lit-element';

export abstract class TestComponent extends LitElement {
    protected render(): TemplateResult {
        return html`
            <article>
                This is a custom test component.
            </article>
        `;
    }
}

customElements.define('test-component', TestComponent);
```

2. Create a sidebar plugin:

```typescript
tinymce.PluginManager.add('metadatasidebar', function(editor): void {
            editor.ui.registry.addSidebar('metadatasidebar', {
                tooltip: 'Metadata',
                icon: 'comment',
                onSetup: function(api): void {
                    console.log('Render panel', api.element());
                },
                onShow: function(api): void {
                    console.log('Show panel', api.element());
                    api.element().innerHTML = `<test-component></test-component>`;
                },
                onHide: function(api): void {
                    console.log('Hide panel', api.element());
                },
            });
        });
```

3. Add the plugin to the plugin and toolbar fields of the `tinymce.init()` method.
4. Toggle the sidebar.
5. The sidebar will not toggle open. There is a style property that sets the width to 0. 
6. Removing this from the `<div role="complementary"/>` and `<div class="tox-sidebar__slider"/>` elements will restore the sidebar. 

**What is the expected behavior?**

The sidebar should toggle open, remove the style that sets width to 0, and set the class to `tox-sidebar__slider tox-sidebar--sliding-open`.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE v5.0.9 - I have not worked with any other versions.
Chrome 74 on macOS High Sierra

**Comment by DerangedMind** [comment]
I did find a workaround to move the application of `innerHTML` to `onSetup` instead. Is this the intended location to set the innerHTML and the documentation simply hasn't been updated? Is there a downside to updating the innerHTML in the onSetup?

**Comment by blackcathikari** [comment]
Hi @DerangedMind, I had a go at replicating this but couldn't see the behaviour you're reporting, on either Linux or macOS Mojave Chrome. Could you have a look at my fiddle and advise us if you can see what I've done differently? http://fiddle.tinymce.com/FOgaab

From your first snippet, it looks like you're using some kind of JS framework? In that case, it could possibly be an environmental problem.

Regarding the docs, from memory you can update innerHTML in onSetup or onShow, it just depends on your use case. If you don't need the content to update when the sidebar opens, it could be better to use onSetup since it is only run when the editor is initialised. I don't have any evidence for this but theoretically I think that if you're doing anything performance-heavy, using onShow could potentially cause problems such as race conditions. Which is what I suspect might be happening in your case, though again, that's a pure guess. Hopefully we can find a replication case and find out for sure.

**Comment by DerangedMind** [comment]
@blackcathikari Hey, sorry for the late response. I tested this out using a vanilla custom component (without LitElement) and wasn't able to reproduce: http://fiddle.tinymce.com/8Qgaab

Main difference here is that in my first example in OP, I am using LitElement, so I feel like the issue may have to do with LitElement and not TinyMCE. We moved away from using a sidebar, so I'm not able to further test this, but using `onSetup` felt like a good alternative to get things working.

Thanks for looking into this! I will close this issue, if that's okay with you.

**Comment by blackcathikari** [comment]
Thank you for looking into this again, it's much appreciated!

**Comment by Ebian00** [comment]
> 
> 
> @blackcathikari Hey, sorry for the late response. I tested this out using a vanilla custom component (without LitElement) and wasn't able to reproduce: http://fiddle.tinymce.com/8Qgaab
> 
> Main difference here is that in my first example in OP, I am using LitElement, so I feel like the issue may have to do with LitElement and not TinyMCE. We moved away from using a sidebar, so I'm not able to further test this, but using `onSetup` felt like a good alternative to get things working.
> 
> Thanks for looking into this! I will close this issue, if that's okay with you.

I have a questions regarding the insert of custom HTMLElements with a button. I want to do exactly what you have done but with  a normal button and not the sidebar. I have tried different ways but non of the works. The scenario is to make tinymce able to create a div which is drop-able and on drop it will get id of the Object and will call in from database and insert it in the div that has been created with the button onclick. Anyway it does not work, I have tried different ways but none has worked. Any solutions?
