### ISSUE TITLE
Media poster not updated on change

### ISSUE THREAD

**Issue by eweso** [tinymce/tinymce#5107]
**What is the current behavior? Describe the bug**
When setting or changing the media poster after setting the video source, then the embedded html will not be updated and therefore the poster is missing. There is no change listener on the poster input.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Don't need a fiddle. Try with the full featured example:
https://www.tiny.cloud/docs/demo/full-featured/

**What is the expected behavior?**
When the poster value changed, the html code for the embedded video should be updated, too.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0.13
Win 1903 / MacOS 10.14.6 (both)

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.0.16, which has just been released to the community. Please let us know if you have any further issues.

**Comment by eweso** [comment]
@lnewson Unfortunately it's the same behavior as in version 5.0.13. When I change the poster URL, then the embedded HTML does not change. It only changes when I update the media source URL.

**Comment by lnewson** [comment]
@eweso where did you check? Just asking as our website shows the enterprise version, so it's not running 5.0.16 yet.

**Comment by eweso** [comment]
@lnewson Please excuse my late reply! I did not realized that you had answered. In the meantime I have written a custom video plugin to meet all my personal requirements. But I have tested the current version of tinymce 5.1.4 and the issue seems to be solved. Thank you!

**Comment by lnewson** [comment]
Awesome! Thanks for letting us know and I'm glad to hear it's working as expected now.
