### ISSUE TITLE
onchange not working for colorinput

### ISSUE THREAD

**Issue by Dinesh28** [tinymce/tinymce#5108]
**What is the current behavior? Describe the bug**
Created a custom dialog with type  'panel' and used some components like input, colorinput. Want to do something on changing the input and color

**What is the expected behavior?**
onChange event working fine for input type similarly it should work for colorinput I think 
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Worked in Chrome latest version
OS Windows 10

**Comment by ltrouton** [comment]
A fix for this issue has been released in 5.0.15. Please let us know if you have any other issues.
