### ISSUE TITLE
How to upload images with angular and firebase

### ISSUE THREAD

**Issue by LuisSarmientoM** [tinymce/tinymce#5111]
### I want to implement the upload of images to firebase and then show them in tinyemce

- in my component i have this:
![image](https://user-images.githubusercontent.com/42702720/62901694-137d6200-bd23-11e9-877e-454e4330a046.png)

- in images_upload_handler I save the image in the storage using the service like this:
![image](https://user-images.githubusercontent.com/42702720/62901909-9acad580-bd23-11e9-81b4-12e7c16b2398.png)

With this, the images are correctly saved in the storage but are not shown in the editor.

**Any recommendations or guides to help me?**

**Comment by LuisSarmientoM** [comment]
**Sorry if there's already a issue with this, but I couldn't find it.**

**Comment by lnewson** [comment]
@LuisSarmientoM you're not calling the `success` callback in the image upload handler, so TinyMCE doesn't know the image has been uploaded, nor where it's been upload to. So you'll need to return the image url from your upload function and then call success.

Here's a rough example of what it'd need to look like, assuming your upload function returns a promise:

```
images_upload_handler: (blobInfo, success, failure) => {
    this.nts.guargarNotica(blobInfo.blob()).then((imageUrl) => {
        success(imageUrl);
    });
}
```

**Comment by LuisSarmientoM** [comment]
@lnewson Hi, This solution worked for me, I just had to return the function that brings the url from firebase and call the function then. Like this:
![image](https://user-images.githubusercontent.com/42702720/63021189-a8887400-be65-11e9-98a2-35878796bad3.png)
