### ISSUE TITLE
Toolbar icons are not showing

### ISSUE THREAD

**Issue by ahsanjamilarkhitech** [tinymce/tinymce#5115]
**What is the current behavior? Describe the bug**
Icons of toolbar are missing
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
Toolbar icons must show
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.7.3.. 
![Screen Shot 2019-08-16 at 4 31 27 PM](https://user-images.githubusercontent.com/46220397/63164921-5a30cc00-c043-11e9-98d6-12ad9a1ef329.png)

**Comment by lnewson** [comment]
@ahsanjamilarkhitech can you please provide a fiddle or a way to replicate the issue? Additionally in TinyMCE 4 fonts are used for the icons so it'd be good to check your network tab and make sure nothing has failed to load (specifically /skins/lightgray/fonts/tinymce.woff or similar).

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
