### ISSUE TITLE
TinyMCE doesn't cleanup after itself properly after remove()-ing the instance

### ISSUE THREAD

**Issue by sztanpet** [tinymce/tinymce#5117]
**What is the current behavior? Describe the bug**

when using inline mode, tinymce modifies the element given by the selector in subtle ways, and after destroying the instance, it doesn't remove said modifications

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/VOgaab

instead of logging `<div id="test">just an inline-editable thing</div>` to the console, it logs `<div id="test" aria-hidden="true" style="">just an inline-editable thing</div>`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE: 5.0.13
Chrome: Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by lnewson** [comment]
I can replicate the issue, however I will note that the issue appears regardless of the mode, as can be seen in the provided fiddle as it's using iframe mode (just to clarify since the original report said inline mode).

**Comment by ProFire** [comment]
I'm also facing this issue in TinyMCE 5.1.5

http://fiddle.tinymce.com/bahaab

Before .init()
<div class="content">content</div>

after .remove()
<div class="content" id="mce_0">content</div>

Sometimes, I get other attributes too, like spellcheck="false"
