### ISSUE TITLE
有些字母在设置下划线时出现bug

### ISSUE THREAD

**Issue by WQXHRen** [tinymce/tinymce#5119]
![Snipaste_2019-08-18_17-58-43](https://user-images.githubusercontent.com/54020056/63223016-ebd64000-c1e1-11e9-942d-5994b2a540c5.png)

**Comment by lnewson** [comment]
@WQXHRen I'm sorry but we can only accept issues reported in English. As such I'm going to close this, but please feel free to log a new issue in English.
