### ISSUE TITLE
Download 5.0.14 is missing

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#5122]
Download 5.0.14 is missing on https://www.tiny.cloud/get-tiny/self-hosted/

**Comment by lnewson** [comment]
Thanks for the report, we'll forward it to our website team to investigate what's going on.

**Comment by lnewson** [comment]
In the meantime, if you need the download it is available here:
- Prod: http://download.tiny.cloud/tinymce/community/tinymce_5.0.14.zip
- Dev: http://download.tiny.cloud/tinymce/community/tinymce_5.0.14_dev.zip

**Comment by lnewson** [comment]
The page has been rebuilt and now correctly shows 5.0.14 as the latest version.
