### ISSUE TITLE
How can I enter HTML as **Text** without it getting interpreted?

### ISSUE THREAD

**Issue by M-Reimer** [tinymce/tinymce#5125]
**What is the current behavior? Describe the bug**

I have a page where I use TinyMCE for editing.
If I enter HTML tags as text (for example to describe something about HTML coding) and submit this, then it isn't properly encoded. After loading that page in TinyMCE again, the HTML tags are "active".

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Enter HTML in the "normal editor mode" of TinyMCE. Submit this via a form to the server. If delivered back to the client into TinyMCE, then all the HTML tags are "active" in TinyMCE.

Either I'm doing it wrong or TinyMCE in general is not able to have HTML tags **uninterpreted** as text. I wasn't able to do it but I would be happy if someone tells me how to do it.

**What is the expected behavior?**

If I have &amp;lt;br&amp;gt; in my source HTML, then TinyMCE shouldn't interpret this as HTML but just show it as text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest final but I also had this problem with 4.x

**Comment by M-Reimer** [comment]
Found the solution.

It is important that, when loaded from the server and delivered to the client, that a replacement like this takes place before placing into the textarea:
``
$content =~ s/&/&amp;/g;
$content =~ s/</&lt;/g;
$content =~ s/>/&gt;/g;
``

**Comment by TheSpyder** [comment]
> Found the solution.
> 
> It is important that, when loaded from the server and delivered to the client, that a replacement like this takes place before placing into the textarea:
> 
> ```
> $content =~ s/&/&amp;/g;
> $content =~ s/</&lt;/g;
> $content =~ s/>/&gt;/g;
> ```

Server-side languages should have a "HTML encode" function to do this, for this very reason :)

Browsers are very permissive about tags in textareas but per the standard textarea contents should _always_ be HTML encoded. TinyMCE doesn't have any say in this; if you don't HTML encode the textarea then the browser returns those values unencoded from the `textarea.value` property and the result can be invalid HTML.
