### ISSUE TITLE
Add feature prevent alt text from being generated by the file name.

### ISSUE THREAD

**Issue by Nhawdge** [tinymce/tinymce#5129]
**Is your feature request related to a problem? Please describe.**
Yes. I would like to make it so alt text isn't the file name.

**Describe the solution you'd like**
When images are dragged into the editor, the file name isn't used. Empty alt text would be fine, or a prompt of some sort to ask for alt text.

**Describe alternatives you've considered**
We use an override in our server to remove alt tags that match the file name.

**Comment by wonderbugtiny** [comment]
Hi @Nhawdge, I would like to get more clarity on the behaviour you are experiencing. If possible, please provide us your TinyMCE `init({ })` configuration and/or a video of when the `alt` text is being added to the image. Thank you!

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
