### ISSUE TITLE
w2ui "like" panels for menus, tool bars, status bars and sidebars 

### ISSUE THREAD

**Issue by garymazz** [tinymce/tinymce#5132]
**Is your feature request related to a problem? Please describe.**
1) I cannot locate locate tool bars and custom information at the bottom of tox-editor-container
2) Have currently unsupported left and right sidebars 
3) Have currently unsupported page Footers and Headers

**Describe the solution you'd like**
I think a w2ui like panel would create the infrastructure to support these features. See: http://w2ui.com/web/demo/layout

**Describe alternatives you've considered**
Modifying Silver Theme

**Comment by lostkeys** [comment]
Thanks for your feature requests! Some questions:

1. We have got that feedback before so I'll note a +1 for toolbars below the content area.
2. You talking about the content within the editor, or the editor itself?
3. Do you envision word processor document header and footers or something more flexible?

**Comment by blackcathikari** [comment]
@garymazz Please clearly explain what you are requesting in terms of:
- What do you want the **editable area** to do?
- What do you want the **UI wrapping the editor** to do?
- What do you want the **page around the editor** to do?

HTML snippets and/or graphic mockups would be much appreciated as well. 

Are you wanting to have a w2ui-like layout _within the editor_? Or are you trying to use the editor on each segment of a w2ui-like layout?

I am concerned that you are attempting to use TinyMCE as a **page builder**, which it is not. Some of our customers have successfully used it within page builder apps, but that is by integrating it to do the content editing part of the application, and controlling page layout separately. If you wish to control content layout in your app in terms of page sections like headings, sidebars, etc. that needs to be done _outside_ of TinyMCE. Here is a basic demo of how TinyMCE should be used in such situations: [link](http://fiddle.tinymce.com/HPgaab)

If you mean something else, please give a clear explanation and use case of exactly what you are requesting.

**Comment by blackcathikari** [comment]
Thank you for those details. I'm a little bit clearer on what you mean about the layout now, but I'm afraid I'm still not sure what you are actually requesting. I can think of too many things you might mean, and I'm not sure which is correct.

Would it be possible for you to create a mockup of a webpage containing the editor in the way you want, even if it's just a sketch? For us to consider taking this on board as a feature request, we need to be very clear on what the scope and requirements are, and I feel that a mockup may be our best way of understanding your use case.

**Comment by garymazz** [comment]
"_but I'm afraid I'm still not sure what you are actually requesting._ "

I'm requesting that TinyMCE support theme layout capabilities akin to w2ui panels. Using this layout mechanism, areas for controls, status bars, tool bars, sidebars, content areas can be arbitrarily defined and placed. This would ease developing more sophisticated capabilities and moving between desktop and mobile versions of the editor.

I'm reluctant to provide a mockup because I believe it will be interpreted as a static configuration which is not what I mean.

I would have not placed this request if there was better documentation for the TinyMCE theme mechanism. The time spent discussing the feature, I would have written it myself and placed it back into the project if I didn't have to reverse-engineer current theme code.

**Comment by blackcathikari** [comment]
Just to reiterate for future reference: you mean the ability to rearrange the editor UI within a layout framework, and possibly adding more customisable panels and customisation options like the sidebar and fixed_toolbar_container setting that are currently available. Not adding more editable sections within the editor, which is the other option I thought you might have meant (e.g. for text columns, footnotes, etc.). This has been recorded as a feature request, but we do not have any timeframe or schedule for this kind of work.

**Comment by garymazz** [comment]
@blackcathikari Thanks for the update. 

Adding sections and other features to documents as page sizes (eg A4) footnotes, headers, footers seem simple to implement as plugins if the layout capability to support them were available. 

The theme mechanism is a bit more complicated than plugin, that is without documentation. Obviously, a layout plugin will eventually result in rewriting a few thousand lines theme code, effectively a redesign, is a silly idea and will likely break backward compatibility.  

I normally don't ask for new features unless there is a good reason. Searching the internet and consolidating requests about how to layout different controls and bars, it seem a panels based layout capability would significantly improve the TinyMCE product.   

cheers
