### ISSUE TITLE
Image upload dialog UI blocking or upload progress loader.

### ISSUE THREAD

**Issue by nishanbajracharya** [tinymce/tinymce#5133]
I'm trying to upload an image from local to a server and in the meantime show a loading overlay over the image upload dialog. I did not find anything in the docs for the `file_picker_callback` method about adding such an overlay. I checked the docs for the dialog API and found a method called `block` which is supposed to do what I want to achieve but I cannot find a way to access this.

Is there a way to get the instance of the upload dialog or a feature in the callback functions that allow me to show a loading overlay in the dialog to indicate that the upload is currently in progress?

I am currently using `tinymce-react` and the `image` plugin to open the `Insert/Edit Image` dialog.

My init config:
```js
{
  height: '400px',
  toolbar:
    'bold italic underline | fontsizeselect forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist indent outdent | link image media',
  plugins: 'textcolor link lists image media',
  menubar: false,
  contextmenu: false,
  /* enables adding custom url conversion logic */
  urlconverter_callback: url => {
    if (url.substring(0, 2) === '//') {
      url = 'https:' + url;
    }

    return url;
  },
  image_title: true,
  /* enable automatic uploads of images represented by blob or data URIs*/
  automatic_uploads: true,
  images_upload_credentials: true,
  // add file picker
  file_picker_types: 'image',
  file_picker_callback: function(cb, value, meta) {
    var input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');
    input.onchange = function() {
      var file = this.files[0];

      // Start Loading UI
      // Upload file to server code here
      uploadToServer(file).then(response => {
        if (response.ok) {
          cb(response.data.path, { title: response.data.file_name });
        } else {
          alert(
            'Failed to upload document. Please check you file type and file size.'
          );
        }
        // Stop Loading UI
      });
    };
    input.click();
  }
};
```

**Comment by sudhakarselva** [comment]
Yeah,looking exact samething

**Comment by sudhakarselva** [comment]
while uploading its through upload tab its there but here nope

**Comment by natehitze** [comment]
I struggled with this for a while but ended up with a good-enough solution for my simple implementation. Hope this helps someone else. The editor emits an event when a window (e.g. dialog) opens and closes. I just keep track of the most recently opened window and then when the `file_picker_callback` is called I call `.block()` on that window.

I'm sure there's some kind of corner case I'm missing that will cause this to break but I'm not too worried about it. If you are worried about it there are a couple ways you could eliminate some doubt. The OpenWindow event includes the dialog being opened with its properties. You could infer what kind of dialog is open based on the properties and then only track the insert file or image dialog. You could also write a simple dialog tracker by keeping track of all dialogs opened/closed and then deciding which dialog(s) in the stack should be blocked. [Window Manager](https://github.com/tinymce/tinymce/blob/49cb074fcf41c7ed5ad22f37048350f4d7fd43bd/modules/tinymce/src/core/main/ts/api/WindowManager.ts) keeps track of the dialogs already but I couldn't find a place where that was exposed.

Some trimmed down example code:
In the editor `init` options I have
```js
setup: function(editor) {
    editor.on('OpenWindow', function(eventDetails) {
        document.tinymceEditor.topLevelWindow = eventDetails.dialog; // document.tinymceEditor is where I keep track of my editor instance. You can probably accomplish this without using that
    });
}
```

And then in my `file_picker_callback` I have the following around my `doUpload` promise:
```js
document.tinymceEditor.topLevelWindow.block('Uploading file...');
// ... blobcache/file stuff here
doUpload(blob, function() {
    // Success
    // callback call and input cleanup here
    document.tinymceEditor.topLevelWindow.unblock();
}, function() {
    // Failure
    document.tinymceEditor.topLevelWindow.unblock();
})
```

**Comment by FeHuynhVI** [comment]
<Editor
          id={id}
          apiKey={import.meta.env.REACT_APP_TINY_API_KEY}
          onEditorChange={onChange}
          disabled={disabled}
          value={value}
          init={{
            placeholder: placeholder || "",
            skin: "material-classic",
            content_css: contentUiCss + "?" + new Date().getTime(),
            autoresize_bottom_margin: 5,
            resize: true,
            height: 160,
            max_height: 600,
            plugins: "code image link lists preview autoresize",
            toolbar:
              "undo redo | styles | bold italic underline forecolor backcolor | link image code | align | bullist numlist | preview",
            menubar: false,
            image_title: true,
            setup: function(editor) {
              editor.on('OpenWindow', function(eventDetails) {
                  document.tinymceEditor.topLevelWindow = eventDetails.dialog; // document.tinymceEditor is where I keep track of my editor instance. You can probably accomplish this without using that
              });
            } ,
            file_picker_callback: (cb, value, meta) => {
              const input = document.createElement("input");
              input.setAttribute("type", "file");
              input.setAttribute("accept", "image/*");
              input.onchange = function (e: any) {
                const files = e.target.files;
                
                if (!files?.[0]) {
                  return; // No file selected, exit early
                }
                try {
          
                  const promise = Promise.all(
                    [uploadFile(files?.[0])]
                  )

                  promise.then((res: any) => {
                    setTimeout(async () => {
                      const result = await downloadFileOneDriveService(res[0]);
                      if (result.code === 200) {
                        if (!result.isFile) {
                          if (result.data.fileType != null && result.data.fileType.includes("image")) {
                            cb(result.data.link)
                          }
                        } else {
                          toast.error("GET URL ERROR");
                        }
                      }

                    }, 5000)
                  })
                } catch { 
                }
              };
              input.click();
            },
          }}
        />
      </BlockElement> fix error  Property 'tinymceEditor' does not exist on type 'Document'.ts(2339)
