### ISSUE TITLE
Stop resetting inline style on backspace

### ISSUE THREAD

**Issue by jainh913** [tinymce/tinymce#5139]
I just want to carry forward inline style until and unless I change it manualy.

Suppose there is one paragraph with inline style ARIAL BLACK. Now I press enter twice and then I press back-space. In our current scenario on backspace style resetting automatically.

But my requirement is to stop resetting inline style until and unless I change manually.

**Comment by ltrouton** [comment]
Thanks for the report! I have logged a ticket internally for us to improve this functionality. We will update you once a fix is available

**Comment by jainh913** [comment]
Thanks

**Comment by samkcdev** [comment]
Hi
Is this issue fixed? Is there a solution for this.

**Comment by griffind** [comment]
@samkcdev Not fixed in any versions from what I can tell. Using [http://fiddle.tinymce.com/4zeaab?_ga=2.107413381.643836943.1594651107-1692514120.1594651107](url) it seems this bug was introduced in 4.6. Strangely, I have seen multiple tickets in regard to this issue and they are say that they have been fixed or have been closed.

I am going to attempt to manipulate the dom in a keyup hook, but I would prefer not to have to do that.

**Comment by TheSpyder** [comment]
This should be fixed by #8408, which was just released in TinyMCE 6.4

**Comment by piyushpaliwal** [comment]
This doesn't seem to be fixed, unless I am missing something. backspacing still removes the applied formatting. https://fiddle.tiny.cloud/fHy7I79ehP/0
Tried both 6.4 and 7 version

**Comment by TheSpyder** [comment]
@piyushpaliwal the fix assumes there is content; the bug we fixed was pressing enter twice at the end of a line of content.

When the format is changed in an empty paragraph and nothing is typed, that formatting winds up applying to a temporary cursor element that is later cleaned up. Notice in your example if you press enter twice it also resets back to the default; this doesn't happen if the first line has content.

If you want to set a default content style, try using [content CSS](https://www.tiny.cloud/docs/tinymce/latest/add-css-options/) to apply the style to `body` or `p` tags.

**Comment by piyushpaliwal** [comment]
Understood, so the scenario that I mentioned, does it count as a bug?

What's happening basically is that I am setting a certain style, font family in this case, and I expect whatever user types show up with that font both on editor and as inline style. Things work well if I start typing; but if I hit backspace without entering anything; the styles reset.

Do you have any recommendations to handle this if we don't consider this as a bug?

**Comment by TheSpyder** [comment]
Feel free to log a new issue, it's a different underlying problem to the one we addressed in this ticket.

If adjusting the defaults through CSS isn't an option, you might have better luck setting styles or a class on the paragraph?
