### ISSUE TITLE
issue with noneditable content in tinymce(v5)

### ISSUE THREAD

**Issue by rahuldeshmukh81** [tinymce/tinymce#5140]
I am using tinymce version 5.

If the content has non-editable content and if I drop an image or anything before noneditable content all the non-editable content gets removed.

Please help to resolve this issue

For Tinymcev5

**Comment by OmdaMukhtar** [comment]
your question is not clear enough , where is your code , please explain more..

**Comment by wonderbugtiny** [comment]
@rahuldeshmukh81 I was unable to reproduce the issue using Chrome or Firefox with TinyMCE 5.0.15. Please provide a fiddle and/or a video to help us understand the behaviour you are experiencing. Thank you!

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.
