### ISSUE TITLE
tinymce v5 , post form to save content ,but there is a new line (<br>) when set the content to textarea

### ISSUE THREAD

**Issue by spring-zs** [tinymce/tinymce#5141]
1.  I save the content to database, and I input "hello world!!!!!!!!!!!!!!" . 
I post the form to save the conent, and the content saved is below.
``` html
<html>
<head>
</head>
<body>
<p>hello world!!!!!!!!!!!!!!</p>
</body>
</html>
```

2. I want to edit this ,so I use jquery post to get the 

``` html
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <title>test edit</title>
</head>
<body>
 
<form id="form" method="post" action="/tinymce-eiditor/content">

    <textarea id="mytextarea" name="mytextarea"></textarea>
    <input type="button" value="submit"  onclick="submitForm();"/>
</form>

<script src="/js/jquery.min.js"></script>
<script src="/js/popper.min.js"></script>
<script src="/plugins/tinymce5/tinymce.js" ></script>
<script>
    (function() {
        tinymce.init({
            selector: '#mytextarea',
            // inline: true,
            toolbar_drawer: 'sliding',
        });


        $.post("/tinymce-eiditor/read",function(data,status){
           $("#mytextarea").val(data.html);
        });
    })();
</script> 
```
3. But, there is `<br>` when the content diplay in the edit area.
Like the images below，the first image is the content I want to save .  the sencond is the content that I set to the edit area,and there is a new line.

![image](https://user-images.githubusercontent.com/53106692/64028128-aa944780-cb74-11e9-9349-a8f772790b02.png)

![image](https://user-images.githubusercontent.com/53106692/64028445-445bf480-cb75-11e9-8213-bf58e6f87871.png)
## So, am I wrong??? or it is a bug?
Thanks in advance.

**Comment by ltrouton** [comment]
Hi @spring-zs. A suggestion would be to use the native TinyMCE [setContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#setcontent) and [getContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#getcontent) methods where possible as these do content parsing. This may resolve the behaviour you are seeing but If it doesn’t, please let us know.

**Comment by spring-zs** [comment]
> Hi @spring-zs. A suggestion would be to use the native TinyMCE [setContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#setcontent) and [getContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#getcontent) methods where possible as these do content parsing. This may resolve the behaviour you are seeing but If it doesn’t, please let us know.

yes，I use setContent and getContent，but it's the same as before.

**Comment by ltrouton** [comment]
This is a difficult issue to test and verify since there is an external server and database involved. Can you please provide a [fiddle](http://fiddle.tinymce.com/baaaab) to show how to reproduce the issue, as that'd help us investigate further.

**Comment by spring-zs** [comment]
> This is a difficult issue to test and verify since there is an external server and database involved. Can you please provide a [fiddle](http://fiddle.tinymce.com/baaaab) to show how to reproduce the issue, as that'd help us investigate further.

There is not an external database involved. you can save the content to a variant. And  ajax get this content  to set to tinemce.

In fact,  maybe it is the html tag to cause that problem. 
using "var content = tinymce.get('mytextarea').getContent()"  , you will  find the value of "content" is 
`<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>hello world!</p>
</body>
</html>`
(the content you input is "hello world!")
the image below is the output of script code :console.log(content) .
 
![Snipaste_2019-09-13_22-01-27](https://user-images.githubusercontent.com/53106692/64868535-1ea11600-d672-11e9-8837-d0a24b4393ac.png)
（chrome browser）

so，if you use setContent method to init the content of tinymce, you will see the issue.

**Comment by ltrouton** [comment]
Thanks for the additional information. When you are calling `getContent`, do you have the fullpage plugin included in your editor config? With it included, you should see the following from `getContent`:

```
"<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>Hello World</p>
</body>
</html>"
```

With fullpage not included, you should see the following from `getContent`:
`"<p>Hello World</p>"`

I can only reproduce the extra breaking space issue when the fullpage plugin is not included in the editor config when calling `setContent`. See fiddle [here](http://fiddle.tinymce.com/DQgaab). From your first post, it appears that you may not have the fullpage plugin included. Just to note, the extra breaking space is likely due to the fact that the elements (doctype, head, etc...) are treated as invalid elements when the fullpage plugin is not included. As a result, they are stripped out and a non breaking space remains.

Let us know if this was helpful. If you are still having issues, please update the attached fiddle and fork it. You can copy the new fiddle URL and I can access it.

**Comment by spring-zs** [comment]
> Thanks for the additional information. When you are calling `getContent`, do you have the fullpage plugin included in your editor config? With it included, you should see the following from `getContent`:
> 
> ```
> "<!DOCTYPE html>
> <html>
> <head>
> </head>
> <body>
> <p>Hello World</p>
> </body>
> </html>"
> ```
> 
> With fullpage not included, you should see the following from `getContent`:
> `"<p>Hello World</p>"`
> 
> I can only reproduce the extra breaking space issue when the fullpage plugin is not included in the editor config when calling `setContent`. See fiddle [here](http://fiddle.tinymce.com/DQgaab). From your first post, it appears that you may not have the fullpage plugin included. Just to note, the extra breaking space is likely due to the fact that the elements (doctype, head, etc...) are treated as invalid elements when the fullpage plugin is not included. As a result, they are stripped out and a non breaking space remains.
> 
> Let us know if this was helpful. If you are still having issues, please update the attached fiddle and fork it. You can copy the new fiddle URL and I can access it.

Yes, that it is. it is the fullpage plugin which cause the issue.   Thank you very much.
