### ISSUE TITLE
Preview plugin prepend and append custom content.

### ISSUE THREAD

**Issue by MoazAlkharfan** [tinymce/tinymce#5145]
I would like to append and prepend html to the preview so it would display the content in the context of the page I'm using the content at.

For example:
Prepending a nav bar and appending a footer.
Or using the preview content inside a custom page structure.

Thoughts?

**Comment by lnewson** [comment]
@MoazAlkharfan, unfortunately, we don't currently have a way to append or prepend html when previewing so I'm going to mark this as a feature request.

In the interim, some things that might work for you are:
- inline mode - this may or may not work but it'd allow you to edit the content directly in your site which wouldn't require the preview plugin
- hook into the `GetContent` event and append/prepend your nav/footer. Here's a basic demo: http://fiddle.tinymce.com/aQgaab/1 Note however that you'd then need to filter this out when saving content.

**Comment by lostkeys** [comment]
Hi @MoazAlkharfan, we're looking through older feature requests and i'd just wanted to check with you if this feature request is still relevant or if you were able to solve your use-case with the answer you got from @lnewson?
