### ISSUE TITLE
@types/tinymce out of date, update to version 5

### ISSUE THREAD

**Issue by jpike88** [tinymce/tinymce#5146]
properties like ```mobile``` are missing from the Settings object. please update the types to reflect it. considering that tinymce appears to be written in TS, shouldn't types be integrated into it directly?

**Comment by lnewson** [comment]
Those types unfortunately aren't maintained by us and are maintained by the DefinitelyTyped project: https://github.com/DefinitelyTyped/DefinitelyTyped so to get them fixed you'd need to log a issue against that project.

In saying that we do want to publish the types from TinyMCE ourselves, however there are some complications we'd need to solve first. We are currently tracking that here: https://github.com/tinymce/tinymce/issues/3427
