### ISSUE TITLE
TinyMCe Wordpress Adding <Picture> Tags

### ISSUE THREAD

**Issue by paul133** [tinymce/tinymce#5150]
Use <picture> with source and imag tags in wordpress for responsive images.  After switching from text to visual edit  and back  open and closed picture tags are inserted between each source tag

**Please provide the steps to reproduce and if possible a minimal demo of the problem via  
Put this code into wordpress post:
NOTE:  WONT LET ME SHOW CODE  FFS IS THIS FOR REAL!
AM EDITING CODE  REPLACE < WITH  *
*picture>
*source srcset="1050.jpg" media="(min-width: 1024px)" />
*source srcset="640.jpg" media="(max-width: 1023px) and (min-width: 640px)" />
*source media="(max-width: 639px)" />
*img class="respimg" src="1050.jpg" />
*/picture>

SWITCH TEXT TO VISUAL EDITOR AND BACK AND CODE CHANGED TO 

*picture> *source srcset="1050.jpg" media="(min-width: 1024px)" />
*/picture>
*picture>*source srcset="640.jpg" media="(max-width: 1023px) and (min-width: 640px)" />*/picture>
*picture>*source media="(max-width: 639px)" />*/picture>
*picture>*img class="respimg" src="1050.jpg" />*/picture>

**What is the expected behavior?**
Code should not change

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

WORDPRESS  5.2.2–en_GB,           FIREFOX Quantum 68.0.2 (64-bit)   -  WIN 10

**Comment by lnewson** [comment]
We don't maintain the wordpress integration, so I'm afraid we can't provide any assistance here, unless you're able to reproduce with TinyMCE outside wordpress. As such I'd suggest logging an issue against wordpress, or if you can reproduce outside of wordpress then can you provide a [fiddle](http://fiddle.tinymce.com/) showing how to reproduce.

**Comment by paul133** [comment]
Thanks.
Yes.  the problem did not occur on the http://fiddle.tinymce.com/ you supplied.
So I guess it must be some wordpress issue... Very frustrating.
