### ISSUE TITLE
[5.0.15] Hitting backspace throws an exception if "forced_root_block = false"

### ISSUE THREAD

**Issue by pf56** [tinymce/tinymce#5151]
**What is the current behavior? Describe the bug**

I'm currently in the process of upgrading our TinyMCE from version 4.5.2 to 5.0.15.
One of the problems I've hit is that simply pressing backspace inside the editor throws a javascript exception. I've narrowed it down to being related to "forced_root_block" being set to false.

```
tinymce.js:3605 Uncaught Error: Node cannot be null or undefined
    at Object.fromDom (tinymce.js:3605)
    at backspaceDelete$8 (tinymce.js:22491)
    at Object.action (tinymce.js:21442)
    at tinymce.js:21447
    at find (tinymce.js:298)
    at Object.execute (tinymce.js:21446)
    at executeKeydownOverride$1 (tinymce.js:22502)
    at Editor.<anonymous> (tinymce.js:22590)
    at EventDispatcher.fire (tinymce.js:26019)
    at Editor.fire (tinymce.js:26125)
```

**Steps to reproduce**

http://fiddle.tinymce.com/hQgaab

Simply hit backspace and watch the browsers console.

**What is the expected behavior?**

No exception being thrown.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

The problem seems to be related only to v5.x. Previous versions (4.x) seem to be working fine.
Tried Firefox 71 (Nightly), Chrome 76 and Edge 78 on Windows. All of them are affected.

**Comment by ltrouton** [comment]
Thanks for the report! I have noted the issue internally for us to investigate. We will let you know when we have an update.

**Comment by sontek** [comment]
What is the plan for this?  We are hitting this issue as well

**Comment by sontek** [comment]
This worked fine in v4, we upgraded recently and now no one can delete text in our editors.  We have to backout the upgrade (which was a massive amount of work to rewrite all our plugins)

**Comment by lnewson** [comment]
We've fixed this issue internally and the fix will be in the upcoming 5.1 release.

**Comment by lnewson** [comment]
TinyMCE 5.1.0 has just been released to the community, which contains a fix for this issue. Please let us know if you have any further issues.

**Comment by awansoekamto** [comment]
Is it in production yet?

**Comment by lnewson** [comment]
@awansoekamto I'm not sure what you mean by in production. The community version is something that you need to deploy yourself.

**Comment by awansoekamto** [comment]
I use CDN as follow:
https://cloud.tinymce.com/5/tinymce.min.js?apiKey=blablabla.

It's not in CDN yet?
Thanks.

**Comment by lnewson** [comment]
@awansoekamto no, that's TinyMCE cloud, which uses the enterprise version of TinyMCE, not the community version. I don't yet have a timeframe for when it'll be released to the 5 stable channel on cloud sorry.

Alternatively, you could use the `5-testing` cloud channel instead of the stable channel (eg: https://cloud.tinymce.com/5-testing/tinymce.min.js?apiKey=blablabla), which will serve TinyMCE 5.1. However, I will note that like community it may not be stable.

**Comment by awansoekamto** [comment]
Alright then. I'll give them a call. Thanks!
