### ISSUE TITLE
Yarn build throws error for about a week now

### ISSUE THREAD

**Issue by lofcz** [tinymce/tinymce#5153]
I've built a habit of compiling TinyMCE each few days to get hands on latest features being developed. For about a week now `yarn build` fails with several errors of this type:

`../mcagar/src/main/ts/ephox/mcagar/api/TinyApis.ts(127,25): error TS2345: Argument of type '() => string' is not assignable to parameter of type 'string'.`

Clearly this is a data type error `() => string` assigning to `string`.

Therefore my question is, is this an error on your side or some new typescript feature I haven't heard of yet?

**Comment by lnewson** [comment]
Hmm, I don't get that locally after doing a clean clone and compile. To be honest it sounds as though it might be a caching issue, as there was a change made recently in `agar` that allows labels to be of type `() => string` or `string` (basically lazy evaluated labels). So given you're getting that error, it sounds as though agar hasn't recompiled, in which case I'd suggest trying one of the following:
- Run git clean (eg `git clean -fdx modules/`) followed by `yarn dev`
- Reclone the git repo and run `yarn` followed by `yarn dev` (basically setup from scratch)

If you're still having issues after trying the above, then could you please provide the output of `yarn list` so we can see what versions you have installed?

**Comment by aloksomani** [comment]
I pulled and built from master as of last Friday (5.0.15) and did not have any problems with my build.

Make sure you do a ```yarn install``` whenever you pull newer code. _If_ the issue is related to node modules being out of date and not updating for some reason, you could also delete your ```node_modules``` directory and then run ```yarn install``` to make sure you have the right versions, as a sanity check.

**Comment by lofcz** [comment]
Thanks both @lnewson and @aloksomani `yarn install` resolved my issue. **Closing.**
