### ISSUE TITLE
Add Keyboard Shortcut to go from Toolbar to Editor

### ISSUE THREAD

**Issue by aloksomani** [tinymce/tinymce#5161]
**Is your feature request related to a problem? Please describe.**
In the vein of trying to improve accessibility -- which encompasses keyboard navigation -- I was attempting to create a keyboard shortcut to allow the user to jump from the Toolbar to the Editor. For whatever reason, I could not get the keyboard shortcut to trigger when focus was within the toolbar, nor was I receiving any events when trying it with just jQuery. The keyboard shortcuts work fine when focus is within the editor, but it seems like events might not be propagating when anything happens in the toolbar.

If it makes a difference, I'm using a fixed toolbar container.

**Describe the solution you'd like**
A few different ways to go about this:

- Add your own keyboard shortcut for this and we can use that (like 'alt+f10' for going from the editor to the toolbar)
- Make the 'alt+f10' shortcut a toggle that toggles focus back and forth between the editor and the toolbar
- Ensure that keyboard shortcuts work when focus is placed within the toolbar
- Allow events that occur in the toolbar to propagate (least desirable; potential can of worms for you guys)

**Describe alternatives you've considered**
I don't know of any viable alternative solutions for this at the moment. For the time being, I'm forgoing adding the keyboard shortcut and relying on the user having to take action on one of the toolbar items to get back to the editor (via keyboard at least).

**Comment by alecpl** [comment]
This issue should get more attention. And this is a bug not feature request. Another option would be that on Tab key focus does not jump directly from toolbar to statusbar, but instead it jumps to editor body and then to statusbar if needed.
