### ISSUE TITLE
Is it possible to set upload image's style with the callback function in tinymce 5?

### ISSUE THREAD

**Issue by 016** [tinymce/tinymce#5162]
Hey, I was user of Tinymce 4.x it's realllllly good, well done guys. Right now I am trying use Tinymce 5.x in my project, I found the " callback function in file_picker_callback" is not working like 4.x, so some one pls help.

[code]
file_picker_callback: function(callback, value, meta) {
...
    if (meta.filetype == 'image') {
.......
       callback(response.data.location, {alt: 'alt text', style: 'display: block; margin-left: auto; margin-right: auto; max-width: 100%; height: auto;'});
[/code]

the problem is simple, add uploaded pic back to editor and set alt + style(center the pic)

right now only the "alt" attribute is working in my test, I was thinking the second param in callback should compare with all html attributes for img tag

some one plz help. thx again.

**Comment by ltrouton** [comment]
Thanks for the report. I can confirm that this is a bug and have created an issue internally for us to investigate it. We will let you know when we have an update.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue.  The `file_picker_callback` will now correctly update the style, etc... fields when provided. Please let us know if you have any further issues.
