### ISSUE TITLE
Toolbar not constructed until TinyMCE gets focused in inline mode

### ISSUE THREAD

**Issue by PagnoDunadan** [tinymce/tinymce#5165]
**Is your feature request related to a problem? Please describe.**
I have a field in a form that is edited with TinyMCE to give a WYSIWYG feel. I also have a wrapper around TinyMCE to provide some functionality on events and for that to work I have to use TinyMCE in inline mode because full mode with iframe doesn't propagate events.

I need the toolbar to appear at all times, just as if TinyMCE was in full mode. Having Fixed Toolbar Container and setting `display: flex !important` stops toolbar from hiding when TinyMCE is blurred. But, the problem is that toolbar isn't constructed at all until TinyMCE gets focused for the first time and when constructed pushes text down.

**Describe the solution you'd like**
A way to always show toolbar in fixed container in inline mode, or just a function to call to construct toolbar without TinyMCE getting focused.

**Describe alternatives you've considered**
Focusing TinyMCE programmatically scrolls the page to the editor instance.

Styling Fixed Toolbar Container to have the same height and color just like toolbar and then showing toolbar only when editor is focused unfortunately doesn't look ok.

**Comment by lostkeys** [comment]
Just wanted to circle back and mention that TinyMCE does now support showing the toolbar at all times in inline mode via the [toolbar persist option](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_persist)

**Comment by PagnoDunadan** [comment]
Works great. Thank you
