### ISSUE TITLE
Initialization selector does not allow "[", "]", "

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5166]
**What is the current behavior? Describe the bug**
For TinyMCE 5.0, the initialization selector does not support DOM element ids with "[", "]", or ".".  When ids with these characters are used, the selector fails to locate the textarea and consequently, causes TinyMCE editor to fail to render.

i.e. 
    tinymce.init({
     selector: '["leftMatchList.answer[0].textForm.text"]'
    });

**What is the expected behavior?**
Textareas with ids that have these characters can be rendered as TinyMCE editors.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5 using Chrome.  Our application is currently running TinyMCE 3.5, and it appears ids with the above characters was supported in version 3.5.

I have verified that changing tinymce.js line 1577 from
```
}, rinputs = /^(?:input|select|textarea|button)$/i, rheader = /^h\d$/i, rnative = /^[^{]+\{\s*\[native \w/, rquickExpr = /^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/, rsibling = /[+~]/, rescape = /'|\\/g, runescape = new RegExp('\\\\([\\da-f]{1,6}' + whitespace + '?|(' + whitespace + ')|.)', 'ig'), funescape = function (_, escaped, escapedWhitespace) {
```
to

```
}, rinputs = /^(?:input|select|textarea|button)$/i, rheader = /^h\d$/i, rnative = /^[^{]+\{\s*\[native \w/, rquickExpr = /^(?:#([\w-\.\[\]]+)|(\w+)|\.([\w-]+))$/, rsibling = /[+~]/, rescape = /'|\\/g, runescape = new RegExp('\\\\([\\da-f]{1,6}' + whitespace + '?|(' + whitespace + ')|.)', 'ig'), funescape = function (_, escaped, escapedWhitespace) {
```
will correct the issue.  But ideally, we'd like to avoid making customized changes so that we can upgrade to newer versions of TinyMCE more easily in the future.  So, it would be helpful if TinyMCE 5.0 can support ids with these characters.

Thanks in advance for your help.

**Comment by lnewson** [comment]
@brittanytang can you please clarify the selector, as it looks like it's missing content. I'm wondering if it should be `selector: '["' + leftMatchList.answer[0].textForm.text + '"]'` as TinyMCE should allow anything that's a valid CSS selector as per the [docs](https://www.tiny.cloud/docs/configure/integration-and-setup/#selector). I also gave it a quick test with our [fiddle](http://fiddle.tinymce.com/) and have verified that using `selector: "[name=content]"` or `selector: '[name="content"]'` works as expected.

It'd also be useful to us if you can create a fiddle so we're able to easily replicate the issue.

**Comment by brittanytang** [comment]
@lnewson  Here's an example of the issue. Thanks.

```
<!DOCTYPE html>
<html>
<head>
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  <script>
  tinymce.init({
    selector: 'textarea#leftMatchList.answer[0].textForm.text'
  });
  </script>
</head>
<body>
 <textarea id="leftMatchList.answer[0].textForm.text" name="leftMatchList.answer[0].textForm.text" title="Question 1" rows="8">hello</textarea>
</body>
</html>

```

**Comment by lnewson** [comment]
@brittanytang in that case you'd either need to do what I did above with an attribute selector or escape the reserved characters like in this fiddle: http://fiddle.tinymce.com/QQgaab

We can't adjust the parser/regex like you suggested, as that would break other lookups so the selector being used must remain a valid CSS selector. So this can be done in your example by using a backslash `\` to escape the dots and square brackets, which is valid as per the [CSS spec](http://www.w3.org/TR/CSS2/syndata.html#value-def-identifier).
