### ISSUE TITLE
Tabbing issues

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5171]
**What is the current behavior? Describe the bug**
For accessibility, we need to be able to tab to the toolbar of the TinyMCE, then tab to the text area, and then tab out of the TinyMCE.  Neither of the 2 tabfocus_elements values indicated here, https://www.tiny.cloud/docs/plugins/tabfocus/, appears to support this workflow.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via http://fiddle.tinymce.com/vRgaab

I also tried the second option of tabfocus_elements: "somebutton", where I added an id for the first button in the toolbar as these buttons don't appear to have ids, but this just resulted in an infinite loops, i.e. tabbing from textarea-> 1st button in the toolbar -> 2nd button -> ... -> last button in the toolbar -> textarea -> first button in the toolbar ->...

**What is the expected behavior?**
When the user tab into the TinyMce, it would set focus on the first button in the toolbar.  At this point, the user can either Tab again, which would set focus on the text area, or use the arrow buttons to navigate through the buttons in the toolbar.  Hitting Tab while in the text area would move out of the TinyMce and onto the next DOM element.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I tested using TinyMce 5, MacOSX, Chrome.

**Comment by spocke** [comment]
Tinymce has full support for wai-aria so you can move between the editor and the toolbar using keyboard shortcuts documented here: https://www.tiny.cloud/docs/advanced/accessibility/ the tab focus plugin should allow you to tab between the editor iframe and any element you specify also it should by default be tabable if the page has tabindexes setup.

**Comment by brittanytang** [comment]
Great, thank you.
