### ISSUE TITLE
referencing local image over path

### ISSUE THREAD

**Issue by serkandemirel0420** [tinymce/tinymce#5172]
I have a client app that i need to reeference an image tag to a local path(its png), is it really not possible?

**Comment by lnewson** [comment]
Can you please include more details and preferably a [fiddle](http://fiddle.tinymce.com/) showing the issue you're having? As TinyMCE should be able to work with relative paths/URLs.

Note: These docs may also be useful to you: https://www.tiny.cloud/docs/configure/url-handling

**Comment by lnewson** [comment]
Closing this as the information requested above hasn't been provided, so we can't investigate any further. We'll be happy to reopen this if you're still having issues and can provide the requested information.
