### ISSUE TITLE
How to minify tinymce src file

### ISSUE THREAD

**Issue by srimoyeesen** [tinymce/tinymce#5180]
I have been using tinymce v5 for my application and had to make a few changes for it to work according to our custom requirements. I need help in now minifying the file. As seen from tinymce docs itself , uglify is not a good option for the same. Can anyone please suggest a good minifying tool for the same.

**Comment by lnewson** [comment]
I'm not sure where you saw in our docs that uglify isn't a good fit, as I couldn't find anything looking quickly, but we currently use UglifyJS to do the minification for our distribution. If you're still using our build process, then you should end up with both the minified and unminified versions when running `yarn build`.

You can see where we're using UglifyJS here: https://github.com/tinymce/tinymce/blob/master/modules/tinymce/Gruntfile.js#L140
