### ISSUE TITLE
`br` elements not added to empty table cells valid elements configuration specified

### ISSUE THREAD

**Issue by Daekard** [tinymce/tinymce#5184]
**What is the current behavior? Describe the bug**

When a table is set as the content of the editor it is expected that `br` elements will be added to empty cells. However, when the `valid_elements` configuration is specified and includes the `br` element, the cells are empty.

Note that is occurs when the table is specified as the content of the editor (e.g. the HTML is specified in the text area), not when inserting the table via TinyMCE

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

A codepen example is [provided](https://codepen.io/Daekard/pen/xxKBeaZ)

1. Create a text area that include the HTML for a valid table.
2. Target the text area with TinyMCE and include the tables plugin
3. Observe that the cells of the table include the `br` elements as expected
4. Specify the `valid_elements` configuration as follows: `valid_elements:'br,table[style|border],tr[style],th[style],thead[style],td[style],tfoot[style]'`
6. Observe that the cells of the table DO NOT include the `br` elements

**What is the expected behavior?**

When the `valid_elements` configuration is specified, and includes the `br` element, empty `td` elements in editor tables should contain `br` elements. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 5.0.15
Firefox 69.0.1

**Comment by ltrouton** [comment]
Under the hood, TinyMCE converts `br` elements to `&nbsp;` for tables. You can verify this by including the `code` plugin, adding a table and opening the source code dialog. Understandably, this is not clear.

A simple solution is to add the `#` to `th` and `td` which will populate empty elements with `&nbsp;`. 
For example, 
`valid_elements: br,table[style|border],tr[style],#th[style],thead[style],#td[style],tfoot[style]`

Let us know if this was helpful.

**Comment by Daekard** [comment]
Thank you. The solution you provided works perfectly. Much appreciated. 
Since this is working as intended I can close the issue.
