### ISSUE TITLE
Inline mode - highlighting disappears 

### ISSUE THREAD

**Issue by mp5er** [tinymce/tinymce#5186]
If some text is marked in Tinymce (inline mode) and the forecolor button is clicked, the marked text is no longer highlighted.

Reproducible on https://www.tiny.cloud/docs/demo/inline/

Tinymce Version: 5.0.16
Browser: Chrome  77.0.3865.90

**Comment by ltrouton** [comment]
We are aware of this issue and have it internally logged. We will let you know when we have an update.

**Comment by lnewson** [comment]
Sorry for missing this, but this issue was fixed in TinyMCE 5.1.0 which was released about a month ago. Please let us know if you have any further issues.
