### ISSUE TITLE
Accessibility Checker not working with Chinese language pack

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5187]
**What is the current behavior? Describe the bug**
The Accessibility Checker premium plugin displays English when the TinyMCE is configured for the 'zh_CN' language pack.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Configure TinyMCE to display using 'zh_CN' and click the 'Accessibility Checker' toolbar button.  A dialog appears with the text "No accessibility issues detected.".

**What is the expected behavior?**
Text should be in Chinese.

**Obervations**
* TinyMCE requested "/plugins/a11ychecker/langs/**zh.js**"and was downloaded successfully.  I had expected it to request **zh_CN.js** instead.
* PowerPaste, another premium plugin, displayed correctly in Chinese.  It used "/plugins/powerpaste/langs/**zh_CN.js**".

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5

![accessiblecheck_china](https://user-images.githubusercontent.com/54727261/65736254-3ffcfb80-e08f-11e9-9e8b-e5fb161bf90b.png)

**Comment by lnewson** [comment]
Accessibility Checker is a premium product, so we can't offer support via GitHub sorry. For all premium products/support can you please contact our support team via https://support.tiny.cloud/hc/en-us/requests/new
