### ISSUE TITLE
Make caret container tag configurable

### ISSUE THREAD

**Issue by ZhangLiangliang** [tinymce/tinymce#5188]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/10874722/65743237-4be7cc80-e126-11e9-9820-118ee4d18d62.png)
In a situation that 'div' is more preferrable than 'p', the hard coded 'p' tag caret results in 'p' tag continuously generated upon typing.

**Describe the solution you'd like**
Since we already have 'forced_root_block' in tinymce settings, we can provide one more option 'forced_caret_block' which default value can still be 'p'

**Describe alternatives you've considered**

**Comment by spocke** [comment]
I think this should just use the forced_root_block setting instead of this hard coded paragraph.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue. Please let us know if you have any further issues.
