### ISSUE TITLE
image uploaded but can't be displayed

### ISSUE THREAD

**Issue by ovezjin** [tinymce/tinymce#5190]
Hello, I'm in trouble with  upload image

My image has been uploaded successfully，but can't be displayed, Display page and edit page are not the same. and  i had return the abs path for image. but in the editor, it change to relative path.

this my setting:
```
tinymce.init({
    selector: 'textarea',
    height:500,
    image_advtab: true,
    automatic_uploads: true,
    paste_data_images: true,
    images_upload_url: '/admin/upload',
    plugins: [
        'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
        'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
        'save table directionality emoticons template paste imagetools'
    ],
    toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullscreen | forecolor backcolor emoticons'
});
```
this is my return: {location: "http://127.0.0.1:5000/admin/uploads/post10.png"}

TinyMCE version:5.0.16
browser: google chrome
OS: windows & linux

**Comment by lnewson** [comment]
Hmm, your server response and configuration looks okay, so can you please include a screenshot or video of the issue, as I'm not entirely sure what you mean by "can't be displayed".

Also if you want to keep absolute URL's you need to configure TinyMCE to do that, as by default it'll convert all urls on the same domain to relative urls: https://www.tiny.cloud/docs/configure/url-handling/
