### ISSUE TITLE
strips A tag

### ISSUE THREAD

**Issue by tyeth** [tinymce/tinymce#5192]
First A tag gets stripped

http://fiddle.tinymce.com/LRgaab

**Comment by lnewson** [comment]
TinyMCE by default doesn't support block-based anchors (see https://github.com/tinymce/tinymce/issues/2991#issuecomment-225495895). If you want to use block based anchors, then you'd have to use `valid_children` to add the elements you want inside the anchor element. Here's a fiddle to demo how to do that: http://fiddle.tinymce.com/LRgaab/1 I should add that certain things may not work as expected, for example editing links via the link plugin.
