### ISSUE TITLE
Editor scrolls when making new paragraph in large block of text

### ISSUE THREAD

**Issue by Parent5446** [tinymce/tinymce#5194]
**What is the current behavior? Describe the bug**

This bug occurs when working with a block of text so large that it expands past the height of the editor, i.e., a single paragraph with enough text such that the user can scroll and the paragraph will extend both above and beyond the user's field of view. With such a block of text, if the user scrolls mid-way through and presses Enter to create a new paragraph, the editor randomly scrolls downward, causing the user's cursor to either move to the top of the editor, or in some cases move off-screen entirely. This results in confusion as the user loses sight of where they were.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Navigate to http://fiddle.tinymce.com/QRgaab
2. Scroll mid-way through the editor's contents.
3. Place the cursor in a random spot and press Enter.

The issue is even more pronounced when using the [Basic Example demo](https://www.tiny.cloud/docs/demo/basic-example/) on TinyMCE's website. (Just copy and paste the editor contents from the Fiddle and repeat the same steps.)

**What is the expected behavior?**

The editor shouldn't scroll, and the user's cursor should remain visible on the screen in a relatively similar location to where it was before.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

v5.0.15 Chrome Linux

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue. The editor should no longer scroll the content to the top/bottom when it's already in view. Please let us know if you have any further issues.
