### ISSUE TITLE
TinyMCE font change automatically

### ISSUE THREAD

**Issue by JordanWorks** [tinymce/tinymce#5196]
**What is the current behavior? Describe the bug**

When using the plugin TinyMCE, the font change automatically when I jump lines or deletes them.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

- I put the font in Calibri with a size. (14px) 
- I write two sentences.
- I'm skipping two or three lines.
- I delete a line: the font resets to Times New Roman (16px)

Here a video of my problem : https://screencast-o-matic.com/watch/cq6eXZu2rw

**What is the expected behavior?**

I would like the selected font to remain the same, whether I jump lines or delete them.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

All browsers are concerned. I'm using TinyMCE 4.7.13.

**Comment by ltrouton** [comment]
Thanks for posting. Closing this ticket as it is a duplicate. Please refer to #5139 for future updates.
