### ISSUE TITLE
table plugin: New line/paragraph after table

### ISSUE THREAD

**Issue by arkhamvm** [tinymce/tinymce#5198]
**Is your feature request related to a problem? Please describe.**
After inserting a table, many casual users don't know how to continue typing text after a table. 

**Describe the solution you'd like**
Option for table plugin for auto-inserting new line/paragraph after a table.

**Describe alternatives you've considered**

**Comment by ltrouton** [comment]
Please note that I have marked this as a feature request and we will look into improving this behaviour. However, the implementation likely wouldn’t involve auto-inserting a new line/paragraph after the table as it won’t be a desired behaviour for all users. We will let you know when we have an update.
