### ISSUE TITLE
Pasting bullets from google docs over existing bullets only pastes highest level

### ISSUE THREAD

**Issue by ryoullar** [tinymce/tinymce#5199]
Set up a bulletted list in a Google Doc. Give each top level bullet some nested sub bullets.

If you paste this into a blank editor, they paste correctly. If you then highlight all (ctrl+a or with the mouse), and paste again, only the highest level bullets appear. The nested sub bullets are lost.

I have been able to reproduce this in fiddle.tinymce.com

**Comment by ltrouton** [comment]
Whilst TinyMCE tries to do its best with pasted content from the likes of Google Docs and Word Online, it makes no guarantees that content from those sources is fully compatible with TinyMCE. In fact, Google Docs often uses invalid HTML. If you require improved paste handling the premium plugin, PowerPaste can be used. However, it should be noted that PowerPaste doesn't explicitly support Google Docs, but does do some basic list handling, regardless of the source. Let us know if you have any additional questions. Closing this ticket as a won't fix.
