### ISSUE TITLE
Uncaught Error: Could not find expected socket element

### ISSUE THREAD

**Issue by Dalsen-Chung** [tinymce/tinymce#5201]
I encountered a programming error like this:

`theme.min.js:9 Uncaught Error: Could not find expected socket element`
`at Object.getOrDie (theme.min.js:9)`
`at Object.render (theme.min.js:9)`
`at Object.renderUI (theme.min.js:9)`
`at tinymce.min.js:9`
`at tinymce.min.js:9`
`at Bz (tinymce.min.js:9)`
`at TN. (tinymce.min.js:9)`
`at Array. (tinymce.min.js:9)`
`at Mn (tinymce.min.js:9)`
`at i (tinymce.min.js:9)`

**Comment by Dalsen-Chung** [comment]
theme.min.js:9 Uncaught Error: Could not find expected socket element
    at Object.getOrDie (theme.min.js:9)
    at Object.render (theme.min.js:9)
    at Object.renderUI (theme.min.js:9)
    at tinymce.min.js:9
    at tinymce.min.js:9
    at Bz (tinymce.min.js:9)
    at TN.<anonymous> (tinymce.min.js:9)
    at Array.<anonymous> (tinymce.min.js:9)
    at Mn (tinymce.min.js:9)
    at i (tinymce.min.js:9)

**Comment by lnewson** [comment]
This is not enough information to go on, please include the details requested in the issue template. At minimum we require a way to reproduce the issue and browser details about where the issue occurs.

**Comment by Dalsen-Chung** [comment]
Here is my code
```
<textarea id="myEditor"></textarea>
<script type="text/javascript" src='${basePath}/tinymce/tinymce.min.js' referrerpolicy="origin"></script>
<script>
	tinymce.init({
		selector:'#myEditor',
	});
</script>
```
Browser display error When I visit the page.
In addition, pages are rendered using JSP.
```
theme.min.js:9 Uncaught Error: Could not find expected socket element
    at Object.getOrDie (theme.min.js:9)
    at Object.render (theme.min.js:9)
    at Object.renderUI (theme.min.js:9)
    at tinymce.min.js:9
    at tinymce.min.js:9
    at Bz (tinymce.min.js:9)
    at TN.<anonymous> (tinymce.min.js:9)
    at Array.<anonymous> (tinymce.min.js:9)
    at Mn (tinymce.min.js:9)
    at i (tinymce.min.js:9)
```

**Comment by Dalsen-Chung** [comment]
> This is not enough information to go on, please include the details requested in the issue template. At minimum we require a way to reproduce the issue and browser details about where the issue occurs.

**Comment by lnewson** [comment]
@Dalsen-Chung that doesn't show us how to reproduce the issue, so we still can't provide much help sorry. Based on the error, my best guess is that something else outside TinyMCE is deleting elements that TinyMCE creates, as the error is complaining that it can't find the editor content area/iframe element.

**Comment by Dalsen-Chung** [comment]
@lnewson Thank you, brother. I'm still working on it, Maybe I need to introduce the TinyMCE in a different way.
