### ISSUE TITLE
Failed image upload still showing in editor

### ISSUE THREAD

**Issue by ouraios** [tinymce/tinymce#5205]
**What is the current behavior? Describe the bug**
When i drag & drop an image and check for its size before start to uploading it, if the failure upload callback is called, the image still stay in editor and is not removed.

You can use this image to test the behavior on the fiddle : https://ps.w.org/tinymce-advanced/assets/screenshot-1.png?rev=2011513 

**Fiddle : http://fiddle.tinymce.com/5Sgaab**

**What is the expected behavior?**

Image is removed on upload failure callback

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE Version : tinymce5-cloud-stable
Browser : Chrome 77

**Comment by lnewson** [comment]
@ouraios sorry for the delay in answering here, but it looks like you are trying to implement an image upload limit?

If so the image upload handler is probably not a good solution for that and probably needs to be done via a content filter or proper support as per https://github.com/tinymce/tinymce/issues/4897. The reason being the image upload function is just meant to take images displayed within the editor and then save them via a backend service, however the images will already be added/displayed in the editor by the time the upload handler gets called, so having them disappear on a failure wouldn't be a good user experience.

**Comment by ouraios** [comment]
Hello @lnewson the problem is it wont work if the server refused the uploaded image too, the image will still appear in the textarea of tinymce and that's not really possible.

For me the thing missing is letting the drag&drop feature to not integrate the image in the textarea on drap&drop if the upload callback refuse the image for whatever reason.

**Comment by deepdsavani** [comment]
I faced a similar issue. @ouraios. Calling the success with empty string removed the image from the editor. I don't know whether this was expected or not but it worked for me to remove the image from the editor due to backend failure.

**Comment by ouraios** [comment]
Yes @deepdsavani but its very bad fo force the user to manually delete the image, it can let him believe that the image was uploaded successfully if the image is still in the editor. From a UX pov its really bad.

**Comment by deepdsavani** [comment]
If you call success with an empty string on the backend failure, it will automatically delete the image from the editor. User doesn't need to delete the image explicitly. 

successful upload then
-> success( ImageUrl)
upload failed then
-> success('')

This will automatically remove the image from the editor when we call success('').

**Comment by ouraios** [comment]
Oh my bad i understood it wrong, thanks for explaining in depth, that's good to know thanks a lot !!!  
But calling success with empty string to delete it doesnt make sense at all ... but i'll use this for the time being until theres a fix for it !

**Comment by ouraios** [comment]
@deepdsavani I tried your solution but it's not working well neither ... :/
i tried to add the success callback like that : 

```js
if( valid_extensions.indexOf(ext) == -1){
    failure("Invalid extension");
    success('');
    return;
}
if(blobInfoDetail.size && blobInfoDetail.size > 100000){
    failure('Max accepted image size is 100ko');
    success('');
    return;
}
```

Result : The image still stay in the editor.

And like that : 
```js
if( valid_extensions.indexOf(ext) == -1){
    success('');
    return;
}
if(blobInfoDetail.size && blobInfoDetail.size > 100000){
    success('');
    return;
}
```
There's still an image trying to be resolved by tinymce : 
![image](https://user-images.githubusercontent.com/9526860/83431863-51757f00-a438-11ea-8ca2-59ce2e98653a.png)

Plus i lose the warning message about not being able to upload, so definitly not a good solution in my opinion :/

**Comment by lnewson** [comment]
Just as an update to this, we've had this requested elsewhere as well. As such we're going to look into the ability to use a flag in the failure callback to have the editor remove the image. We don't have a timeframe when the feature will be implemented though.

**Comment by ouraios** [comment]
That's great news ! Cant wait to see this option to be available !

**Comment by livthomas** [comment]
I was dealing with the same issue and I found a simple workaround:
```
tinymce.activeEditor.undoManager.undo();
```

**Comment by guomsh** [comment]
TiniyMCE5 you can set UploadFailureOptions to remove the image，like failure("error!", {remove:true});

**Comment by lnewson** [comment]
I missed updating this when it was released sorry all, but yes this feature was added in TinyMCE 5.5.0. As @guomsh mentioned above you can now pass an object to the `failure` callback to tell TinyMCE to remove the image. See [images_upload_handler docs](https://www.tiny.cloud/docs/general-configuration-guide/upload-images/#images_upload_handler) and [TinyMCE 5.5 release notes](https://www.tiny.cloud/docs/release-notes/release-notes55/#minorchangesfortinymce55) for more details.
