### ISSUE TITLE
Loss of font information in empty blocks

### ISSUE THREAD

**Issue by Parent5446** [tinymce/tinymce#5208]
**What is the current behavior? Describe the bug**

TinyMCE has a number of issues preserving the styling of blank lines, i.e., blocks with no content in them. This can be observed when creating and deleting newlines in various patterns, and also when copying and pasting. I believe the root cause is that TinyMCE uses a <span> within the <p> to apply most styles, but if there's no content, it removes the <span>.

This is frustrating for a lot of our users, because they end up having to re-apply their fonts many times whenever they have a blank line, or else delete the blank line and re-create it.

Note that this was previously a bug in v4.2.5 (see #3471), but has now re-appeared in v5.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/9Sgaab

1. Place the cursor at the end of Line 3
2. Press Enter twice, creating two new lines. Cursor should be on the second new line.
3. Press Backspace once to get back to the first new line.
4. Observe that the font is now "System Font".

Another method of reproduction:

1. Place the cursor at the end of Line 3.
2. Press Enter once, creating a new line.
3. Change the font in the toolbar to anything else, e.g., Helvetica.
4. Click somewhere to put the cursor on a different line, e.g., clicking on Line 2.
5. Click back onto the empty line to move the cursor back.
6. Observe that the font is now "System Font".

**What is the expected behavior?**

The editor should remember the font that was applied to an empty block, so if the user goes back to typing in that block, it preserves the font that was selected.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

tinymce5-cloud-stable with Chrome

**Comment by ltrouton** [comment]
We are aware of this issue and we are currently investigating improvements that can be made in this area. Please refer to #5139 for future updates. Thanks for the detailed post!
