### ISSUE TITLE
Readonly on mobile does not block

### ISSUE THREAD

**Issue by jul6art** [tinymce/tinymce#5209]
If the tinymce is readonly but display on mobile, readonly has no effect

It should be blocked like on desktop.

I'm using version 5.0.8

**Comment by ltrouton** [comment]
As of TinyMCE 5.1 the old mobile theme mentioned here is now deprecated and as such we'll only be making critical fixes for it. Have you tried using mobile on 5.1, as it should provide a better experience and will also respect the `readonly` setting.

**Comment by lnewson** [comment]
Closing this since this isn't a critical legacy mobile theme issue and we haven’t heard back if 5.1 worked for you. If 5.1 doesn't work please either comment on this and we'll reopen the issue or log a new issue.
