### ISSUE TITLE
Clicking on More... button tiny 5.1.0 highlights the next icon on the next toolbar

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#5212]
Clicking on More... button tiny 5.1.0 highlights the next icon on the next toolbar

See video

https://screencast-o-matic.com/watch/cq6qQLugU1

**Comment by lnewson** [comment]
This is expected, as opening the toolbar drawer will focus the first item in the list for accessibility purposes, similar to how it does when opening a menu.
