### ISSUE TITLE
Image dropped when copy/pasting docx file into IE 11.

### ISSUE THREAD

**Issue by ablakeharris** [tinymce/tinymce#5213]
**What is the current behavior? Describe the bug**
When copy/pasting the attached document into TinyMCE in Chrome the image is pasted, but the image is lost when pasting into Internet Explorer 11.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Copy and paste attached document into fiddle in IE 11.
[Hello.docx](https://github.com/tinymce/tinymce/files/3751798/Hello.docx)

**What is the expected behavior?**

Image is present along with text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Only IE 11 seems to be affected.  This is occurring in the newest version, and doesn't appear to work in older versions either.

**Comment by charlest1506** [comment]
I have the same issue.

**Comment by charlest1506** [comment]
Opinions anyone?  What is the likelihood this issue will be fixed given that it is IE only?

**Comment by lnewson** [comment]
Unfortunately this is something that cannot be fixed from the TinyMCE side of things, as Microsoft removed the ability to get the image data from the clipboard on IE 11 earlier this year: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20768499/ and https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20993641/

We've logged a ticket with the Microsoft team, but it's still in their hands at this stage, so we can only wait for them to investigate/resolve the issue.

**Comment by lnewson** [comment]
I should mention as a workaround, if you select only the image and then copy/paste that from the word document then it should work (as the image is the only content on the clipboard), but if selecting it with any additional content then the image is no longer available on the clipboard.
