### ISSUE TITLE
paste image issus

### ISSUE THREAD

**Issue by Paradox-Lee** [tinymce/tinymce#5216]
Hello!
When I paste a single picture into the editor,everything is ok.
But when i paste a large block texts and pictures into the editor(copy from word),each of picture can not show.I use the powerpaste plugin.

like this:
![7e532bacf42c479f6a9fa469d6c5a7f](https://user-images.githubusercontent.com/6771426/67538974-5b513a00-f713-11e9-8a77-545afd3d07b0.png)

that's my code:
![image](https://user-images.githubusercontent.com/6771426/67539059-95bad700-f713-11e9-9407-8afc338e4459.png)

think you

**Comment by lnewson** [comment]
PowerPaste is a premium product, so we can't offer support via GitHub sorry. For all premium products/support can you please contact our support team via https://support.tiny.cloud/hc/en-us/requests/new

**Comment by yesw6a** [comment]
@Paradox-Lee Did you solved the problem?
