### ISSUE TITLE
Add paragraph to the quickbars_selection_toolbar tiny 5.1

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#5218]
Add paragraph to the quickbars_selection_toolbar tiny 5.1

Really missing the paragraph so if you click on a H1 and then you can change it to paragraph.

quickbars_selection_toolbar: 'bold italic | link paragraph h1 h2 h3 blockquote', doesn't work

See image
![2019-10-27_102410](https://user-images.githubusercontent.com/1576475/67632517-84ed9b00-f8a4-11e9-81ec-226be592d26b.jpg)

**Comment by lostkeys** [comment]
You can get that behavior using the API and a custom button. However, the default behavior of the h1, h2 buttons is that they are toggle buttons and toggling off the h1 for example, implies returning it to a paragraph.

Applying the same logic to a paragraph button would have one toolbar button be lit up all the time.
I made an example so you can see it by yourself: http://fiddle.tinymce.com/lUgaab
You can convert the paragraph button to be a "stateless" button like this http://fiddle.tinymce.com/mUgaab but then it doesn't behave consistently with the heading buttons (which might be fine). 

I'm closing this issue, but feel free to reopen it if this didn't solve your problem.

**Comment by lnewson** [comment]
It's also worth noting that you can use the `formatselect` dropdown toolbar button in the quickbars: http://fiddle.tinymce.com/lUgaab/1

**Comment by cfconsultancy** [comment]
Great solutions. Thanks
