### ISSUE TITLE
Failed to load emoticons: Script at URL "..." failed to load

### ISSUE THREAD

**Issue by Hillcow** [tinymce/tinymce#5219]
I use ES2015 to load modules [like described in the docs](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/). Everything works as expected, however the emoticons plugin does not load. I get the following error:

> Failed to load emoticons: Script at URL "..." failed to load

Not sure why this is, but I know I'm not the only one. [This guy right here](https://blog.csdn.net/u010007013/article/details/102562721) just recently had the same problem and found a workaround (just use Google Translate). But the workaround includes taking the emojis.js to a public dictionary, which is obviously not a solution.

**Comment by lnewson** [comment]
When using a module loader, you'll need to make sure you include any additional resource files in your imports list. So for the emoticons plugin, you'd need to do something like this:

```
// Import TinyMCE
import tinymce from 'tinymce/tinymce';

// A theme is also required
import 'tinymce/themes/silver';

// Any plugins you want to use has to be imported
import 'tinymce/plugins/emoticons';
import 'tinymce/plugins/emoticons/js/emojis';

...

// Initialize the app
tinymce.init({
  selector: '#tiny',
  plugins: ['emoticons']
});
```

**Comment by Hillcow** [comment]
Sorry for not being more specific, but what you just described is exactly what I am doing and that is working for all plugins except the emoticon one.

**Comment by lnewson** [comment]
@Hillcow can you please provide a codesandbox, or something similar to replicate the issue then? As I tested the above did work before posting.

**Comment by Hillcow** [comment]
I run the latest version of Laravel and use Vue.js. I found out that it actually works if I import both of these:

> import 'tinymce/plugins/emoticons/js/emojis.min';
import 'tinymce/plugins/emoticons';
