### ISSUE TITLE
Allow string as trigger in Autocompleter

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#5220]
I am trying to create autocomplete plugin for a wiki-style linking. However, it turns out that only a single characters are supported as triggers. I want to use the string `[[`, which is a common trigger for this functionality (even Wikipedia uses [[ to start a link), but it turns out that only a single character is supported in TinyMCE.

I've tried working around that by expecting the first character in the pattern to contain the extra `[` character, but it is ignored. For example typing `[[x` does not return `[x` in the pattern variable.

So, could you add multi-character auto-completion trigger support or do you have an idea how can I workaround that limitation?

**Comment by petko** [comment]
A possible workaround is using the `matches` configuration option, where to check directly if the text starts with `[[` instead with a single `[`, however it seems that there is a bug, because if you type `[[x` the text is set as `[[x`, but if you delete the x and type it again, the second time `text` contains only `[x`.

**Comment by nobodyme** [comment]
Yes, I was looking if this is available as well. It would be great!

**Comment by lostkeys** [comment]
Hi, Just wanted to let everyone know that [TinyMCE 6.2](https://www.tiny.cloud/docs/tinymce/6/6.2-release-notes/#the-autocompleter-now-supports-a-multiple-character-trigger-using-the-new-trigger-configuration) added support for using multiple characters to trigger an autocompleter.

**Comment by vpyshnenko** [comment]
Use the `trigger `configuration [option](https://www.tiny.cloud/docs/tinymce/6/autocompleter/#options).
