### ISSUE TITLE
tinymce 5 not creating first <br /> tag

### ISSUE THREAD

**Issue by joshuatantonflynn** [tinymce/tinymce#5225]
So we recently updated to tinymce 5. So far it's broken a few of our things but we've managed to get things working close enough to how they were with 4.

I am having trouble with on issue however. All our editors used to have the following properties set

invalid_elements: "div",
force_br_newlines: false,
force_p_newlines: false,
forced_root_block: '',

This was necessary so our users would have their printed content look the same as what it looks like in the editor. (using html to pdf libraries would put too large spaces if using p_newlines).

With tinymce 4 this would work perfectly. only <br /> tags would be added for new lines, no uneeded <p> or <div> tags would clutter the editor making things look ugly once printed.

but once upgraded to 5 I noticed when pressing enter on the first line in an editor, instead of creating the <br /> tag it would do nothing. By removing the invalid_elements: "div" property I saw it wasn't doing nothing, but it was creating a div block below the first line after pressing enter. Everything within this div block would then work as before. But with the invalid element property set that block was being removed. This ended up causing a bunch of problems with some of our other features which relied on there being a <br /> tag there.

now I've tried all kinds of things, including changing the above properties to just forced_root_block: false, but currently I can't find a way to replace that div block with a <br />, I can always change the content when a <div> block is added, but then I have to deal with resetting the cursor position, which comes with a whole other set of problems.

Does anyone know why this is happening with tinymce 5 and not 4? Is there anything I can do about this?

All this is with angularJS using the following url: "https://cdn.tiny.cloud/1/<our_api_key>/tinymce/5/tinymce.min.js"
I can recreate this by using the above properties, using the above properties but switch force_br_newlines to true, using only forced_root_block: false. Then click on the first line of an empty editor, type some text and press enter, type some more text. If you have invalid_elements: "div" set then hit code you will see no characters between the newline. If you don't have this property you will see a div was created below the first line. While under tiny 4 it was two lines separated by a <br /> tag in the body tag.

Thanks,

**Comment by joshuatantonflynn** [comment]
After experimenting with a basic example on codepen I have found that it is actually one of my plugins doing this.

For some reason using the textpattern plugin produced this error. I now have removed that plugin and remove the invalid element and kept forced_root_block: false. This produces what I need.

This plugin did not do this in tinymce 4. Is this a bug? a change in the plugin (don't see it in the documentation). It would be good if we could use this plugin and not have this happen.

**Comment by Afraithe** [comment]
Those configs essentially kill most of the functionality of the editor.

I would recommend removing all those 4 configs and solve it by either:
1) Use CSS to control the space around P paragraphs
2) Replace </p> with <br /> and <p> with nothing just when exporting to PDF.

**Comment by lnewson** [comment]
As @Afraithe said using that config kills a lot of functionality in the editor, so we'd suggest to avoid it wherever possible. As a side note however, the text pattern issue sounds like a bug we fixed recently in the text pattern plugin for 5.1 (which isn't live on tiny.cloud just yet). The issue was that it was throwing the following exception when using `forced_root_block: false`:

```
Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at plugin.min.js:9
    at Object.r (plugin.min.js:9)
    at St (plugin.min.js:9)
    at Dt (plugin.min.js:9)
    at It (plugin.min.js:9)
    at e.<anonymous> (plugin.min.js:9)
    at e.fire (tinymce.min.js:9)
    at e.fire (tinymce.min.js:9)
    at Xz (tinymce.min.js:9)
    at Object.t (tinymce.min.js:9)
```
