### ISSUE TITLE
TinyMCE crashes when toolbar is scrollable (also.. not sure why its scrollable?)

### ISSUE THREAD

**Issue by sontek** [tinymce/tinymce#5226]
**What is the current behavior? Describe the bug**
For some reason, a set of my customers are getting a scrolled view of the toolbar which crashes their page when they use it.

Its crashing here in silver/theme.js

```
    var owner = function (element) {
      return Element.fromDom(element.dom().ownerDocument);
    };
```

My customers that are experiencing the crash see this:

![image (16)](https://user-images.githubusercontent.com/151924/68049368-1439ea80-fcb9-11e9-9b57-e0ba396e9a77.png)

People who don't get the crash are seeing this:
<img width="363" alt="Screen Shot 2019-11-01 at 3 05 57 PM" src="https://user-images.githubusercontent.com/151924/68049465-595e1c80-fcb9-11e9-9ee0-34b21626967a.png">

I don't expect it to ever scroll, I would prefer it always wrap and I don't understand why its scrolling for them.

**What is the expected behavior?**
I have two expected behaviors:

- Toolbar should wrap the icons not scroll them
- If the toolbar does scroll, it shouldn't crash

I'm using `toolbar_drawer: false`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE v5.1.1
TinyMCE-React v3.3.2

**Comment by lostkeys** [comment]
Just a quick questions to clarify the use-case (and no, the editor should not crash, that's a bug somewhere)

* What OS and browser are the users that experience the crash using?

The scrollable toolbar was introduced to give more space to the content on narrow mobile screens as having five rows of toolbars as shown in your image  isn't an ideal user experience either. But the horizontal scrollbar below the toolbar looks awful indeed and something we need to look at.

**Comment by lnewson** [comment]
It'd also be useful if you could provide a full stack trace so we can see where it's failing, as the code given above is a rather generic function used in many, many places.

**Comment by sontek** [comment]
Both users that are having the crash are on Windows 10 and are in Chrome.  They've reproduced it on Firefox as well though.

Its weird that some of our users are experiencing the scrollbars and others aren't.  Why would it not be consistent?   I don't think we'd ever want the scrollbar, so I guess we'll have to switch to `toolbar<n>`?   I know stacking doesn't look great but hiding functionality will confuse our users.   They aren't technical users so they need all the functionality visible at once.

This is the callstack:
<img width="1093" alt="Screenshot 2019-11-04 10 28 15" src="https://user-images.githubusercontent.com/151924/68128446-22bd1780-feee-11e9-8075-ca2a35168c17.png">

**Comment by lnewson** [comment]
@sontek thanks for the details! Do you happen to know if any of your users are using touch devices (eg a surface)? As TinyMCE will currently treat any touch device as a mobile device (we probably need to look at tweaking that). That would explain why some of your users are getting a scroll bar and others aren't.

The exception also at a glance looks like it's in the mobile code, but I'll have to look into that more.

**Comment by sontek** [comment]
Yes, both customers who have reported this so far have standardized on Microsoft Surfaces as the primary work station for their employees.  So I believe majority (if not all) bug reports came from surfaces.

**Comment by sontek** [comment]
Is there a way for me to say `work the same way everywhere`?  Our system is already optimized for mobile users and we've tested our configurations of the editor on mobile and it works great.   We've had a lot of users complain about the new fullscreen mobile stuff recently as well and its on our list to figure out how to get back the old functionality that worked well already

**Comment by lnewson** [comment]
@sontek could you clarify how it crashes their page? We unfortunately don't support, nor have access to a surface but we'd still like to fix the issue if it's making it completely unusable. We did manage to reproduce the exception you were seeing, but it didn't appear to be "crashing" the editor.

As for getting it back, we're going to look at improving the scrolling toolbar so it won't apply to desktop devices, though a touch device still needs considerably different handling to a more accurate pointing device such as mouse (eg you can't hover on a touch device). For now, as a temporary workaround, you should be able to override the toolbar CSS to get it to wrap like so:
```
<style>
.tox.tox-platform-touch .tox-editor-container .tox-toolbar, .tox.tox-tinymce-aux.tox-platform-touch .tox-toolbar {
    flex-wrap: wrap !important;
}
</style>
```

**Comment by sontek** [comment]
@lnewson It throws that exception I showed above.   The problem is we can't just allow unhandled exceptions to be thrown and let the user move on because they could be in a really bad state.   So we catch all exceptions and present an error to the user that tells them an unhandled exception happened and to try refreshing their page.

If tinymce throws an exception, we are going to treat it as a bad thing and present that to the user.   We can't tell the difference between "throws an exception but stays in a good state" and "horrible things happened"

**Comment by sontek** [comment]
@lnewson Can you let us as consumers decide the behavior rather than doing introspection into the device and forcing an experience onto our users?    Currently we have a significant amount of Surface users and a small number of mobile users (our mobile usage is only at 8%).   So we have a lot of angry customers because of this and flipping it back to how it used to be would make majority of our customers happy.

Even the 8% users on mobile usually aren't editing their content there, because its clearly easier to use a keyboard than a mobile device when editing lots of content.   Our mobile users pretty much only edit on mobile for quick fixes and typos during emergencies where they can't get to their surface quickly

**Comment by sontek** [comment]
Especially currently how the mobile code path seems to be significantly less tested than the desktop version.  I'd rather present our users a suboptimal desktop experience on mobile than an optimized for mobile exception throwing experience.

**Comment by sontek** [comment]
Also, PLEASE recognize *mobile* vs *touch*.   My surface users are having a very bad experience with these updates.

**Comment by lnewson** [comment]
@sontek we aren't forcing you to upgrade so you could still be using 5.0.x instead of 5.1 if it's causing you issues. Additionally, it was your decision to completely reload the page on any exceptions, which isn't a great idea as any browser plugin, etc... could end up throwing an exception which is outside your control.

In saying all that, we do value your feedback and are making adjustments to improve this in 5.1.2. We've already fixed the original exception, added a way to disable the scrolling toolbar via a configuration and made it so that touch desktop devices won't use the mobile overrides block. I don't have a date for 5.1.2 but it'll likely be early next week.

**Comment by sontek** [comment]
Any update on when a fix for this would be coming out?

**Comment by lnewson** [comment]
Sorry, it was held up due to a few more issues found by QA, it should be getting released tomorrow now instead.

**Comment by sontek** [comment]
@lnewson Great, thanks for the update.  This has been a long month of angry customers for us waiting for the fix

**Comment by lnewson** [comment]
TinyMCE 5.1.2 has just been released to the community with the fixes for the 2 issues mentioned here. Again we're sorry you ran into these issues. 

Note that community releases only undergo basic QA testing before release. Our Enterprise product contains a version of TinyMCE that has been fully tested and patched. If you would like to use a version of TinyMCE that has been formally tested, we recommend using:
- A community version that matches the current enterprise version, or
- Upgrade to an enterprise package.

Please let us know if you encounter any additional issues.

**Comment by sontek** [comment]
@lnewson Did you also fix the mobile bug?    My primary issue was that my non-mobile users were crashing because of the mobile code path was being hit, but my mobile users were also hitting the issue.  Just there aren't as many of them.   I want all my users to not hit the bug =)

**Comment by lnewson** [comment]
As I said above we fixed the issues raised here, that included the exception being thrown and desktop touch devices being treated as a mobile device and using the mobile config overrides. We also made it so that the mobile scrolling toolbar can be disabled by setting `toolbar_drawer: false` in the mobile configuration.
