### ISSUE TITLE
Icon background colour on menus

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5234]
I have an issue with the way the menus are rendering:

![Table1](https://user-images.githubusercontent.com/7985331/68121444-ae8b6f80-feff-11e9-876f-5ebb9f63499e.png)

It is the background colour of the toolbar icons on the menu. We have two scenarios:

Scenario 1
Hovering over a menu item without a icon:

![Table2](https://user-images.githubusercontent.com/7985331/68121527-e98da300-feff-11e9-8ee0-b733ebd9dc70.png)

As you can see, there is a ugly white rectangle.

Scenario 2
Hovering over fly-out menu:

![Table3](https://user-images.githubusercontent.com/7985331/68121614-180b7e00-ff00-11e9-8d44-55256fd53ef8.png)

It seems the background colour for fly-out is `#0073aa` but I can't work out the custom CSS to change the icon background. It needs to be white if there is no icon and that blue colour if it is a fly-out.

Using 4.9.4

Forums:

https://www.publictalksoftware.co.uk/support-forums/

**Comment by ajtruckle** [comment]
This seems OK:

`.mce-menu-item-normal {
	background: none !important;
}

.mce-menu-item-normal:hover {
	background: #aaa !important;
}

.mce-menu-item-normal .mce-ico {
	background: none !important;
}`

Could you confirm?

**Comment by lostkeys** [comment]
Unfortunately customizing the CSS of TinyMCE 4.x using overrides is very much a trial-and-error type of work and not something we have resources to help out with. I hope you understand. If you made it work, then it probably works. Make sure to test in a couple of different browsers.
