### ISSUE TITLE
bbPress support

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5235]
When I try the v4 full demo of the code sample plugin and past in XML content it is displayed fine in the editor.

But when I insert XML content in my editor that is inside bbPress it strips all the tags and I am left with just the text.

**Comment by lostkeys** [comment]
I'm sorry to disappoint you but we have no possibility to test this. You have to rule out it being an issue with either Wordpress, bbPress or the Advanced TinyMCE plugin. TinyMCE can be implemented in so many ways, and it might be that the creators of BBpress does want the xml tags to be stripped (stripping out content is a feature of TinyMCE). I suggest you try the bbPress forum for this issue. Once again, sorry I could not be of any help.
