### ISSUE TITLE
Insert Image Plugin - Support Lightbox?

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5237]
TinyMCE 4.9.4 on WordPress

Could the image plugin be extended to let us insert the image with lightbox support so they can click on it to view normal size?

**Comment by lostkeys** [comment]
That functionality would be up to the website containing the editor to implement. I have personally had [success with this one](https://lokeshdhakar.com/projects/lightbox2/) and as far as I remember, it could generate it's ligthbox without any special markup around the images.

**Comment by lnewson** [comment]
It's also worth noting that you can provide a custom [`image_class_list`](https://www.tiny.cloud/docs/plugins/image/#image_class_list) configuration with any classes you may need to implement the lightbox.

**Comment by ajtruckle** [comment]
I am confused @lnewson . When we insert an image at the moment it is inserted as a `img` type element. My website already has the **Foobox Image Lightbox** installed.

@lostkeys look at your link even it specifically states example code:

`<a href="images/image-1.jpg" data-lightbox="image-1" data-title="My caption">Image #1</a>`

So I don't really understand how I am supposed to go from a `img` to a `a` with TinyMCE.

**Comment by lostkeys** [comment]
I might have been mistaken on exactly what markup is needed. Sorry, there is no way to wrap an image with arbitrary html upon insert. It's considered part of the host app to do that kind of UI-centric features. You could have someone help you do some jQuery magic to wrap all images in a forum post in an `<a>` tag and then initialize the Lightbox.
