### ISSUE TITLE
How to add ui components to sidebar?

### ISSUE THREAD

**Issue by migliori** [tinymce/tinymce#5238]
Hi,

I want to add UI components (like dialog components) in the sidebar like buttons, dropdowns, ... but didn't find any way to do it.

I know it's possible because the Comments 2.0 plugin uses textarea & buttons: https://www.tiny.cloud/docs/demo/comments-2/

So please how can I do this?

Thanks for your answer

**Comment by TheSpyder** [comment]
The comments plugin doesn't use TinyMCE widgets, it ships a custom copy of the UI library (that's why the plugin is fairly large).

This is something we hope to address in the future but it's not on our roadmap right now.

**Comment by migliori** [comment]
Thanks for your answer. It would be a useful feature to allow all the dialog components to be used inside a sidebar.
For now I'll use context menus with a custom toolbar.
