### ISSUE TITLE
Feature Request for 'ui_container'

### ISSUE THREAD

**Issue by milap1296** [tinymce/tinymce#5241]
**Is your feature request related to a problem? Please describe.**
So I need to render the tinymce editor(v5.0.14) within an overlay component, while doing so I faced issues within the popovers/overlays rendered within tinymce eg:- paragraph, textcolor, etc.
The issue over here is that tinymce's overlay components are not being rendered within the context of parent overlay.

**Describe the solution you'd like**
 I found a fix regarding the same in `v4.4.2`. This version uses an option named **ui_container** which is passed as a setting to tinymce such as
```
tinymce.init({
		selector: 'textarea',
		width: 600,
		height: 150,
		ui_container: '.content',
		plugins: 'code link',
		toolbar: 'code link'
	})
```
[4.4.2 Fix link
](https://github.com/tinymce/tinymce/commit/7fd61eeac61e9a88dfe8ed3c4c0398b5ee0328e2)
Can anyone please help me if this is supported in `v5.0.14`, if not is there any alternative to achieve the same?

As you can see the tinymce's overlay is seen behind the component rendering tinymce editor
<img width="237" alt="Covered overlay" src="https://user-images.githubusercontent.com/19545730/68219828-a9681680-000c-11ea-9232-7e525bc5db48.png">

<img width="622" alt="Tinymce Popover Issue" src="https://user-images.githubusercontent.com/19545730/68219842-af5df780-000c-11ea-84a5-20a046a76cd0.png">

**Comment by milap1296** [comment]
@lostkeys @lnewson can you please help me with this ?

**Comment by lostkeys** [comment]
It looks like a z-index issue. Those are tricky to protect oneself against, there is always a higher number. Can you play around with the z-index of the menu item using the browser inspector? Or do you have the site/app publicly available somewhere?

**Comment by milap1296** [comment]
@lostkeys I already tried with the z-index but as I said the tinymce's popover/overlay is not opening within the parent overlay so it shouldn't matter whatever z-index I give to it.

It can be clear from the screenshot attached.
<img width="1600" alt="Overlay TinyMCE" src="https://user-images.githubusercontent.com/19545730/68332152-42298f80-00fc-11ea-9ef2-aebdb2dc3d12.png">

**Comment by lnewson** [comment]
@milap1296 that looks more like a z-index issue as you modal dialog appears to have a higher z-index than the `.tox-tinymce-aux` element. If you can provide a basic fiddle, we can assist in helping to get it working.

The `ui_container` also really doesn't make sense and makes more bugs than it fixes, since positioning, z-index rules, etc... all are affected by parent contexts, which you often can't escape out of which is why it was removed in v5.

**Comment by milap1296** [comment]
@lnewson I tried replicating the same with the new version.
Meanwhile I got to know that `tinymce-react` exists to support compatibility with react. I was using `react-tinymce` to render the tinymce but seems like react-tinymce is not supporting the `v5.0.14`. Should I use `@tinymce/tinymce-react` instead... What do you guys suggest?

Working [Code sandbox](https://codesandbox.io/s/react-bootstrap-modal-enclt) for reference.

**Comment by lostkeys** [comment]
Well, [react-tinymce](https://github.com/instructure-react/react-tinymce) is not maintained by us at Tiny, so any questions and support around that integration has to go to that project. As which one to use, we're heavily biased of course, so the boring answer is that it's up to you and the solution you want to achieve.

I don't know if your code sandbox was to illustrate the problem you are experiencing, but I tested it on Safari and Chrome and it works as expected
![image](https://user-images.githubusercontent.com/3122929/68574509-5954de00-046a-11ea-8e2e-65b952fb6481.png)

**Comment by milap1296** [comment]
@lnewson @lostkeys increasing the z-index value solves the issue for me too. But I think there might be an issue when another popover/overlay is opened by tinymce within tinymce's popover.
Is there is any possible scenarios like such ?
