### ISSUE TITLE
Inserting Tables - Number rows and columns

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5242]
When inserting a table the little grid is limited for the number of rows you can choose. I would like ability to either:

1. Specify the number of rows I want in the grid.
2. Ability to insert x rows into the grid rather than just one at a time.

Using 4.6.4

Andrew

**Comment by lostkeys** [comment]
You can set the [table_grid](https://www.tiny.cloud/docs/plugins/table/#table_grid) option to false that replaces the grid with a dialog where the number of rows and columns can be specified. [See a demo here](http://fiddle.tinymce.com/EUgaab)

**Comment by ajtruckle** [comment]
Thanks for that. It does work but then all the settings in that window need to be set.

I like the drag approach because when I click the table is where with borders taking full width. The other way it doesn't look like that unless I learn the settings. So wheeras i was only looking for two extra edit boxes to specify the row / col count I have to set many more to make it look visually nice.

So I have reverted to the other approach as it was before until this could be done another way.

________________________________

**Comment by lostkeys** [comment]
The visual appearance of the table is defined in either an external stylesheet and loaded using the `content_css` option or directly in the init config using the `content_style` option. [I made an example](http://fiddle.tinymce.com/EUgaab/1) with the latter that sets the width of the table to 100%

**Comment by ajtruckle** [comment]
Thanks. Good to know.

I think overall I will leave it as is. Nicer for user. It is only me who wanted more rows really added to existing table.

So we leave it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lostkeys** [comment]
Alright, I’ll log a feature request for future improvements to the table plugin. As a heads up, any new features like this will end up in version 5 of TinyMCE.

**Comment by ajtruckle** [comment]
I am on 4.9.4 because that is what Wordpress is using at the mo. When they migrate then I will. Prefer to match their official version.

Thanks for adding to the list. 😀

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
