### ISSUE TITLE
Using right-to-left languages

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5246]
I am using version 4.9.4 and have the **Directional** plugin installed:

https://www.tiny.cloud/docs/plugins/directionality/

When I am in the editor the text shows right aligned (even though my text alignment is still left). When I submit my topic or reply the text (whilst still in the right-to-left direction) is now left aligned on the display.

To get the display to display correctly I have to:

- Use right-to-left direction

- Use text align right

I understand that my topic is a mixture of English and Arabic but i thought wherever the plugin content is enabled that it would sort it out.

**Comment by TheSpyder** [comment]
The plugin doesn't do anything automatically, it just provides buttons to set the direction on paragraphs. Note that the `dir` attribute is different to text alignment, although content set to `dir=rtl` is right aligned by default.

If your text is showing right aligned by default, that suggests your editor is configured with `dir=rtl` set on the content body. Content body attributes are not included in saved content (with one exception that doesn't apply here). The likely reason for text rendering left aligned after saving is that the page where saved content is displayed does not have `dir=rtl` set on the surrounding element.

The displayed content area must match the editor configuration content settings for true WYSIWYG.
