### ISSUE TITLE
Directional plugin buttons

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5248]
Why is it that the LTR and RTL buttons are the same with a left pointing arrow on the toolbar?

**Comment by lnewson** [comment]
They aren't the same? One has a right arrow and the other has a left arrow (here's v4):

![759F5E2A-4B15-47D5-8578-83B303C5D6F1](https://user-images.githubusercontent.com/1575550/68577714-5c78ba00-04bc-11ea-87c9-cdd95fb948e0.jpeg)


http://fiddle.tinymce.com/NUgaab

**Comment by ajtruckle** [comment]
I don;t get it. I am using the TinyMCA Advanced Plugin for WordPress. In the plugin "Tiny MCE" settings area where you drag n drop the buttons are the bar they are indeed two different buttons:

![Toolbar1](https://user-images.githubusercontent.com/7985331/68578093-3d047180-0469-11ea-944e-b50a46fe34d1.png)

But on the actual toolbar in the bbPress editor they are not:

![Toolbar2](https://user-images.githubusercontent.com/7985331/68578134-586f7c80-0469-11ea-9bef-f42ebb1fbad6.png)

How do I fix this?

**Comment by lnewson** [comment]
We don't maintain that plugin so we can't provide much help sorry. However TinyMCE uses fonts for icons so it's possible that a custom font is being used in your second screenshot and that's causing the Left-to-right button to be inversed.

**Comment by ajtruckle** [comment]
Hhm. It seemed it was using dashicons so I added this custom CSS:

```
i.mce-i-ltr::before {
	font: normal 20px/1 dashicons !important;
	content:"\f10c" !important;
}

i.mce-i-rtl::before {
	font: normal 20px/1 dashicons !important;
	content:"\f320" !important;
}
```

**Comment by ajtruckle** [comment]
It does indeed seem to be the font. If I try to use `Tinymce' as in your code I end up with squares. It is as if the font is not supported inside bbPress and thus uses dashicon font.

Not to worry. Atleast I have a workaround for now.
