### ISSUE TITLE
Mobile UI events (when book is clicked)

### ISSUE THREAD

**Issue by crinitic** [tinymce/tinymce#5250]
**Is your feature request related to a problem? Please describe.**
When I click on the "book" to open the editor in mobile view, some of the parents CSS styles are overwritten and make the mobile view invisible. Is there an event I can listen to, i.e. onMobileEditorOpened so I can make my parent elements visible?

**Describe the solution you'd like**
Have some events in "options" to react after the mobile editor went full screen.

**Describe alternatives you've considered**
Removing the editor in mobile view.

**Comment by lnewson** [comment]
You should be able to use the `focus` and `blur` events to be able to detect when the legacy mobile theme is activated/deactivated. Note however that the legacy mobile theme is meant to be fullscreen and take over the entire page, so attempting to mess with any of its overrides would be unsupported.

If you don't want something that takes over the entire page, then I'd suggest upgrading to TinyMCE 5.1 which introduces mobile support for our silver theme, so you don't have to click the book icon and it won't be fullscreen unless you manually enable it.

**Comment by crinitic** [comment]
Migration to 5.1 solved the problem, thank you
