### ISSUE TITLE
Focus button (in wordpress)

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5253]
I had asked this here:

https://stackoverflow.com/questions/58645493/marking-the-clicked-button-as-active

But I can't get any of the answers to work in my situation:

```
<div class="wp-editor-tabs"><button type="button" id="bbp_topic_content-tmce" class="wp-switch-editor switch-tmce" data-wp-editor-id="bbp_topic_content">Visual</button>
<button type="button" id="bbp_topic_content-html" class="wp-switch-editor switch-html" data-wp-editor-id="bbp_topic_content">Text</button>
</div>
```

My TinyMCE toolbar has a Visual and Text tab. But the editor with focus is not made clear on thetab itself. Does that make sense?

**Comment by lostkeys** [comment]
You seem to have got some good answers there, what is it more specifically that doesn't work? Can you provide a screenshot?

**Comment by ajtruckle** [comment]
The problem I am having is that I don't understand how I can implement those suggestions given the environment I am actually working in:

WordPress -> bbPress

It is not as simple as just replicating a fiddle on home specific HTMl / PHP files.

**Comment by metricjs** [comment]
Unfortunately we do not maintain any Wordpress integrations, so we are not able to help with any issues specific to an integration. So I'm going to close this ticket as it has been open for a while. If you have any other questions we might be able to help with, please feel free to make another ticket. Hopefully you were able to figure this out though!
