### ISSUE TITLE
Custom toolbar button icon with svg <rect> elements renders badly

### ISSUE THREAD

**Issue by njenia** [tinymce/tinymce#5254]
**What is the current behavior? Describe the bug**
When I use a custom SVG icon for a button that contains `<rect>` elements, specifying `width` and `height` attributes on the `<rect>`, they don't have affect on the element, resulting in a wrong icon.
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Create a custom icon pack and link your tinymce to it (`icons_url: '.../icons.js'` in the `init` block).
2. Add some SVG icon to the pack, that contains a `<rect>` element with width and height > 0. For simplicity, override any of the existing icons, like `bold`.
3. Notice the difference between the real SVG and the how it looks inside the toolbar as a tinymce toolbar icon.
**What is the expected behavior?**
It should look the same
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All.

**I found the root cause.**  The `reset.less` file of the oxide skin has these lines:
```
  *:not(svg) {
    ...
    height: auto;
    width: auto;
    ....
  }
```

This makes any element under tinymce, except for `SVG` to have `width` and `height` of `auto`, which makes `<rect>` elements that have specific width and height to have it overriden by `auto` and so they are invisible. A quick fix would be to simply add `:not(rect)` to the selector of this rule. There might be other elements that have width and height.

Original `reset.less` would make:
<img width="212" alt="Screen Shot 2019-11-14 at 11 42 53" src="https://user-images.githubusercontent.com/1434858/68845366-f6ff1600-06d3-11ea-8832-b2d75c97ebbd.png">
Modified like I suggested (with the `:not(rect)` rule) would make:
<img width="208" alt="Screen Shot 2019-11-14 at 11 42 39" src="https://user-images.githubusercontent.com/1434858/68845400-041c0500-06d4-11ea-9bd7-a3663774528f.png">
(the one visible line on the top image is actually a polygon which isn't affected by the width and height: `auto`)

**Comment by lostkeys** [comment]
Thank for finding this!

**Comment by lostkeys** [comment]
This has been fixed and will be shipped in an upcoming release.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue. Please let us know if you have any further issues.
