### ISSUE TITLE
Tinymce5 init slow in IE

### ISSUE THREAD

**Issue by cblstc** [tinymce/tinymce#5255]
**What is the current behavior? Describe the bug**
I use Tinymce5  in a Vue project. And I regist a event after the editor init success. I console some log and find that ie11 is slow to output the log. More than 3s. But google just less than 1s. What I want to do is to do sth after the editor init.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. regist a event after finishing init
```js
setup: (editor) => {
  this.editor = editor
  editor.on('init', (e) => {
    this.$emit('init-success')
  })
}
```
2. do sth after finishing init
```js
handleInitSuccess () {
  // do sth like console...
  console.log('init success')
}
```

**What is the expected behavior?**
ie finish init slow, more than 3s.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMce 5.1.1
browser IE11.418.18362
os win10

**Comment by lincolndennis** [comment]
@cblstc - How are you integrating TinyMCE into Vue? Are you using our Official Vue component? 
https://github.com/tinymce/tinymce-vue

**Comment by cblstc** [comment]
* MyEditor.vue
```html
<Editor id="tinymce" v-model="editorContent" :init="editorProps"></Editor>
```
```js
import tinymce from 'tinymce/tinymce'
import 'tinymce/themes/silver/theme'
import Editor from '@tinymce/tinymce-vue'
// this is the plugin I defined
import '../../../../public/lib/tinymce/plugins/imageSelector/plugin'

// some init data
data () {
	editorContent: '',
	editorProps: {
		language_url: '/lib/tinymce/zh_CN.js',  // %projectPath%/public/lib/tinymce/zh_CN.js
		skin_url: '/lib/tinymce/skins/ui/oxide',// %projectPath%/public/lib/tinymce/skins/ui/oxide
		setup: (editor) => {
			editor.on('init', (e) => {
				this.$emit('init-success')
			})
		}
	  }
	}
}
```
* imageSelector/plugin.js
```
tinymce.PluginManager.add('imageSelector', function (editor) {
  editor.ui.registry.addButton('imageSelector', {
    icon: 'image',
    tooltip: 'insert image',
    onAction: function () {
		// do sth
    }
  })
})
```

* The component using the MyEditor.vue
```js
handleInitSuccess () {
	// I use a loading component, and after init success, I close loading.
	// And I count that IE finished loading more than 3s.
	this.loading.close()
}, 
``` 

Notice that IE11 has a warning message:
```
SEC7113：CSS was ignored due to mime type mismatch
content.css
```

**Comment by cblstc** [comment]
I has solved the problem. I found some clue in the `getContentCssUrls` function, it concated a default skin url, and the baseURL is wrong to locate the default skin.
```js
   var getContentCssUrls = function (editor) {
      var contentCss = Settings.getContentCss(editor);
      var skinUrl = editor.editorManager.baseURL + '/skins/content';
      var suffix = editor.editorManager.suffix;
      var contentCssFile = 'content' + suffix + '.css';
      ...
   }
```
the `editor.contentCSS` is a array with two skin url, a default one and a customized one. Since we cannot locate the default one, the `loadAll` function executed the failure callback. I guess the loadAll function is time-consuming when it couldn't locate the url.
```js
      getStyleSheetLoader(editor).loadAll(editor.contentCSS, function (_) {
        initEditor(editor);
      }, function (urls) {
        initEditor(editor);
      });
```
so I changed the baseUrl and solved the problem.
```js
window.tinymce.baseURL='xxx'
```
