### ISSUE TITLE
More "toolbar_drawer" settings

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5259]
https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_drawer

Currently, the button only appears when the toolbar no longer fits into the editor. Thats a great feature! I would like to be able to insert a "more"(as example) in "toolbar" and the button [...] will be displayed from there and the following buttons will no longer appear. As an additional display option.

Setting:
toolbar: 'undo redo | **more** bold italic | link image'
Result:
![image](https://user-images.githubusercontent.com/260343/68974013-af54b900-07bd-11ea-834a-d8cb4fc6c92b.png)

**Comment by lnewson** [comment]
We actually have something similar to this planned for TinyMCE 5.2, however it'll more be along the lines of a set grouped items that can be expanded using a button, so a "more" like button can be used multiple times for the different groups as defined in the configuration. Here's a brief example of how the config might look:

```
tinymce.init({
  ...,
  toolbar_groups: {
    mygroup: {
      icon: 'more-drawer',
      tooltip: 'My group of buttons',
      items: 'bold italic | link image'
    } 
  },
  toolbar: 'undo redo | mygroup',
  toolbar_mode: 'sliding_groups'
});
```

I can't share too much more at the moment, but do you think that would work for what you want to do here?

**Comment by Daijobou** [comment]
Here one more request.
The "status" of "more"-button should be saved. At least if you use it as second or more toolbars.

**Comment by lostkeys** [comment]
I just want to circle back that we introduced the [toolbar groups option](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_groups) to configure your own "more drawers" back in TinyMCE 5.2. As for the more button status, we have plans... stay tuned.
