### ISSUE TITLE
Media link context menu missing way to edit Media options 

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5260]
**What is the current behavior? Describe the bug**
The context menu that shows when you right mouse click an inserted media link, such as an mp4, has no option to open the 'Edit Media' Dialog to allow for editing media properties.  Instead, only the Link option is displayed.  

This is different from the context menu for embedded image files, which shows the options for editing "Image" and "Link".  

How do users edit the properties of an embedded media?

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. http://fiddle.tinymce.com/zVgaab/2
2. Click 'Media' toolbar button.  Opens the 'Insert/Edit Media' dialog.  Specify a 'source' of https://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_480_1_5MG.mp4 and click 'Save'.
3. Observe the context menu for the media has no 'Media' menu option to open the 'Edit Media' Dialog, only the option for edit "Link" is available.

**What is the expected behavior?**
Context menu for embedded media files should show options for edit "Media" and edit "Link" similar to that of embedded image files, which displays options for editing 'Image' and 'Link'.    

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMce 5.

**Comment by lnewson** [comment]
You can edit media by using the "Insert" -> "Media" menu item or using the equivalent toolbar button when a media element is selected, however you are right there's no built in context menu for this. One can be added relatively easy though, here's an example of how: http://fiddle.tinymce.com/0Vgaab
