### ISSUE TITLE
Statusbar in forced_root_block not refresh correclty

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5261]
v5.1.1 See http://fiddle.tinymce.com/1Vgaab/1

Click on "BOLD" and then on "TEXT, look statusbar, its show still "STRONG".
Same with click on "LINK" and then on "TEXT, statusbar show still "A".

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue. Please let us know if you have any further issues.
