### ISSUE TITLE
toolbar_drawer select first button

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5262]
v5.1.1 see http://fiddle.tinymce.com/1Vgaab/2

Click on "..."-button and the first button in second toolbar is always selected.

UPDATE:
Selection not disappear after shrink toolbar. You have to click somewhere first.

**Comment by lnewson** [comment]
It is expected behaviour that the first item gets focus and is required for accessibility purposes. The same thing also applies to menus, as when opening a menu will also focus the first item.
