### ISSUE TITLE
Autolink: Bugs with comma at the end of the URL

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5263]
There are multiple issues with that character. Steps:

1. Goto the editor on https://www.tiny.cloud/,
2. Clear the content,
3. Write: "www.test.com, " (no quotes, comma and space at the end). Note that at the moment link element includes the comma, which might in itself be another issue/unexpected behavior.
4. Press backspace twice, to delete the space and comma.

Result: Invalid URL in the resulting HTML:
`<p><a href="http://www.test.com," aria-invalid="true">www.test.com</a></p>`
BTW: what that `aria-invalid` is for?
Expected: URL does not contain comma and the end.

5. Continue by adding comma, space and any text after that.

Result: The whole line becomes a link until you press Enter. Note that `href=www.test.com,` still.
Expected: Link contains only "www.test.com" (or "www.test.com,").

Tested with Chrome and Firefox.

**Comment by lnewson** [comment]
The fact the comma is included in the auto generated link is a bug, thanks for catching that! As for point 5, if you press backspace you're then editing the text content of the link so it's expected that adding any additional text will continue to edit the link text content (you'll see the link gets a blue background to show the selection is inside the link). You can press the right key to escape out of the link and continue typing regularly.

Also `aria-invalid` is part of the link checker Premium plugin as it's required for accessibility to mark links as invalid for screen readers.

**Comment by lnewson** [comment]
I should add if you don't want the behaviour where the selection would stay inside the anchor, then you can turn it off or tune it to your liking by adjusting the inline boundaries settings: https://www.tiny.cloud/docs/configure/content-appearance/#inline_boundaries
