### ISSUE TITLE
Open Link context menu action always opens in new window

### ISSUE THREAD

**Issue by tilmans** [tinymce/tinymce#5266]
**What is the current behavior? Describe the bug**
Context menu option to open links ignores setting to open in current window

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

* Add a link with the option to open in Current Window
* Right click link to open TinyMCE context menu
* Click on Open Link menu option
-> Opens in new tab

**What is the expected behavior?**
Should open in same window (not use target=_blank

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.1.1 -> the code is in the link plugin in core/OpenUrl.ts, open function where it creates a link with target=_blank, ignoring the option to open in same window.

**Comment by androb** [comment]
I believe this is working as intended. 

When editing content in TinyMCE, opening the link in the same browser window could content not to be saved. Most editors only offer the option to open links in a new window. I tested Google Docs and Notion, and they do it this way too.

The underlying HTML attributes in the content are updated to include the correct target.
