### ISSUE TITLE
Open a dialog moved page content to right

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5267]
See this GIF (taken from https://www.tiny.cloud ) v5.1.1
![editor2](https://user-images.githubusercontent.com/260343/69102279-eaf6b980-0a2f-11ea-9dbd-f0d94e2cc591.gif)
When open a dialog the page content is moved to right a few pixels. That's a strange behavior. When this is a _feature_, how I can disable it?

**Comment by lnewson** [comment]
This is just because the browser scrollbar is hidden when a modal is opened since the page shouldn't be able to scroll with a modal open.

**Comment by Daijobou** [comment]
Why are you removing the scrollbar?

**Comment by lostkeys** [comment]
Hm, to be fair, that would drive me nuts. Content should not move around on screen. But I’m on a mac that got rid of the scrollbars way back so I rarely experience these issues. I’ll have a look, but can you confirm you are using windows?

**Comment by Daijobou** [comment]
I use Windows 10. ;)

Reason is overflow:hidden in `body.tox-dialog__disable-scroll`.
I use modal windows with modal(overlay) too, but without hide scrollbars and without position:fixed for dialog and dialog is with his header moveable like desktop apps.

**Comment by namnguyen6595** [comment]
So, how to fix this problem?

**Comment by vasilgvalchev** [comment]
try to add this in your main css fail, this class was added to the body when the dialog is opened and it cause the jump, in my case its mode the dropdown inputs also, its very wired.

body.tox-dialog__disable-scroll {
  overflow: visible !important;
}
