### ISSUE TITLE
TinyMCE not working after form submission in rails

### ISSUE THREAD

**Issue by ruthvikg** [tinymce/tinymce#5268]
I have a form in rails.In that i have a tinymce text_area which is working correctly on page reload.But when i make changes in the form and submit it ,after the turbolink:load,tinymce is not working.

Expected to work normally
tinymce gem -5.1.1
browzer-Chrome latest
os-ubuntu

**Comment by lnewson** [comment]
@ruthvikg can you please provide a replication case, as the details you've provided really aren't enough for us to be able to help here.

**Comment by ruthvikg** [comment]
Here is my rails form:

`<div class="mb-4 firstresponsedata" data-controller="tinymce--tinymce">
    <p><%= form.label :content %></p>
    <div>
    	  <%= form.text_area :content, class:" tinymce appearance-none border border-gray-400 rounded w-full py-2 px-4 text-gray-700 leading-tight bg-white focus:outline-none focus:border-primary", placeholder: "Content*", required: true, data: { editor: 'tinymce' } %>
         <input type="submit" name="submit"/>
    </div>
</div> `

Here is my tinyMce controller:

`$(document).ready(function() {

            let my_toolbar = "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | 
            outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | image media 
             link | fullscreen code |"
            if (tinyMCE) {
                tinyMCE.remove();
            } else {
                tinymce.EditorManager.execCommand('mceAddControl', true, editor_id);
            }
            tinymce.init({
                theme: 'silver',
                skin: false,
                content_style: contentStyle.toString(),
                selector: '.tinymce',
                plugins: ['table', 'lists', 'image', 'media', 'advlist', 'link', 'code', 'imagetools', 'fullscreen', advcode'],
                toolbar: my_toolbar,
`

When the above form is first loaded the tinymce works perfectly fine.But,after the form submission and when the form page reloads the tinymce doesn't work.
The buttons and the menu bar is getting disabled. 
![Screenshot from 2019-11-20 10-25-36](https://user-images.githubusercontent.com/55078141/69210431-c2320980-0b80-11ea-8616-764fdd561e76.png)
