### ISSUE TITLE
Not able to provide a custom URL in language_url

### ISSUE THREAD

**Issue by vctormb** [tinymce/tinymce#5270]
**What is the current behavior? Describe the bug**
When configuring the editor in the init object, there's a property called `language_url`.  
I'm trying to put my custom URL, but it still gets the localhost URL.  
```
// my current configuration
{
  document_base_url: 'https://example.com/assets/',
  language_url: `langs/pt_BR.js`,
  language: 'pt_BR',
}
```
When the editor requests the language file, it tries to get from localhost URL.
![image](https://user-images.githubusercontent.com/13953703/69154520-ea593400-0abe-11ea-9b4e-637d8097cd3f.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
```
tinymce.init({
  document_base_url: 'https://example.com/assets/',
  language_url: `langs/pt_BR.js`,
  language: 'pt_BR',
});
```

**What is the expected behavior?**  
To provide a custom URL to `language_url`.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
`"tinymce": "5.0.14"`
`"@tinymce/tinymce-react": "3.3.2",`

I never tried this in previous versions.

**Comment by lnewson** [comment]
[`document_base_url`](https://www.tiny.cloud/docs/configure/url-handling/#document_base_url) is for resolving urls used in editor content, it is not used for resolving TinyMCE assets. To set the base url for TinyMCE assets you'd need to set the TinyMCE [`base_url`](https://www.tiny.cloud/docs/configure/integration-and-setup/#base_url). In saying that however as per the [`language_url`](https://www.tiny.cloud/docs/configure/localization/#language_url) docs if you're using this setting you should use an absolute path, so in your case I believe it should be `language_url: 'https://example.com/assets/langs/pt_BR.js'`.

**Comment by vctormb** [comment]
> [`document_base_url`](https://www.tiny.cloud/docs/configure/url-handling/#document_base_url) is for resolving urls used in editor content, it is not used for resolving TinyMCE assets. To set the base url for TinyMCE assets you'd need to set the TinyMCE [`base_url`](https://www.tiny.cloud/docs/configure/integration-and-setup/#base_url). In saying that however as per the [`language_url`](https://www.tiny.cloud/docs/configure/localization/#language_url) docs if you're using this setting you should use an absolute path, so in your case I believe it should be `language_url: 'https://example.com/assets/langs/pt_BR.js'`.

I've tried to use the `language_url` with an absolute path, but it still searches for the localhost url.

![image](https://user-images.githubusercontent.com/13953703/69239811-d1618900-0b79-11ea-9869-456619b6d55c.png)
![image](https://user-images.githubusercontent.com/13953703/69239835-e3dbc280-0b79-11ea-936f-f8be55368a91.png)
