### ISSUE TITLE
Firefox 70.0.1: touch screen triggers mobile mode

### ISSUE THREAD

**Issue by Drzwioddomu** [tinymce/tinymce#5272]
**What is the current behavior? Describe the bug**
Running the editor under Firefox on a touch screen laptop (Asus VivoBook) triggers the mobile view of the editor. It runs ok in Chrome. 

**What is the expected behavior?**
Running the editor in desktop view, unless tablet mode is enabled. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Windows 10 Home Version 10.0.18362 Build 18362
TinyMCE 5.1.1

**Comment by lnewson** [comment]
This was fixed in yesterdays 5.1.2 release, so please try upgrading to see if that resolves your issue. If it doesn't let us know and we'll reopen this issue.
