### ISSUE TITLE
Table Caption Disappears On Partial Cut

### ISSUE THREAD

**Issue by iggybotes** [tinymce/tinymce#5273]
**Repro Steps:**
1. Create a table.
2. Add a caption to the table with some text ("My Caption")
3. Select/ highlight part of the text ("My C")
4. Right click mouse and select cut or use Ctrl + X to cut text.

**Expected outcome:**
      - Only selected text is cut.
**Actual outcome:**
      - All text is cut and disappears. When pasting, only the text that was selected/highlighted is pasted (saved on the clipboard).

I am not sure about previous versions but this bug is occuring in v5.

**Comment by lostkeys** [comment]
Did some research and this broke/change in 4.7.1. Before that, selecting and cutting parts of the table caption only cut the selection, not the whole caption.

Test: http://fiddle.tinymce.com/TVgaab
