### ISSUE TITLE
Text starts from second line after apply + remove format in IE

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5276]
**What is the current behavior? Describe the bug**
Text starts from second line after apply + remove format in IE
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1.http://fiddle.tinymce.com/
2.apply then remove bold format
3.type
**What is the expected behavior?**
text starts from first line
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0+

**Comment by lnewson** [comment]
I could reproduce this and it looks like the selection is ending up in the wrong place, as it's at the end of the paragraph (eg after the bogus br) instead of at the start of the paragraph. That then causes the text to appear on the next line since content is inserted after the bogus br.
