### ISSUE TITLE
images_upload_handler get width and height

### ISSUE THREAD

**Issue by Lingouzi** [tinymce/tinymce#5277]
How do I set the resulting height and width to the img tag?
```js
images_upload_handler: (blobInfo, success, failure) => {
                    const formData = new FormData()
                    formData.append('file', blobInfo.blob())
                    uploadImg(formData)
                        .then(res => {
                            console.log('result:', res)
                            if (res.code === 200) {
                                const file = res.data
                                const width = file.width
                                const height = file.height
                                success(file.url)
                                return
                            }
                            failure('upload fail')
                        })
                        .catch(() => {
                            failure('upload fail')
                        })
                },
```
When I drag or paste the screenshot, it will be uploaded automatically, but there is no height and width in the `img` tag.
![image](https://user-images.githubusercontent.com/12908403/69417988-bc8d1d00-0d54-11ea-944e-c341263d43ff.png)
This will be width and height, but I hope that I can also drag or paste.

and
I want the uploaded image to automatically add a note `image_caption: true`
![image](https://user-images.githubusercontent.com/12908403/69418205-2dccd000-0d55-11ea-9801-5c5ebcb7efe9.png)

I have to click to appear, how do I set it up automatically?

**Comment by wyx2014** [comment]
u
need
do
it
by
ur
self
