### ISSUE TITLE
Focus rectangle for current row in the "table"

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5278]
Using 4.9.6 in WordPress 5.3 (bbPress 2.6.1)

Is it possible that when in the editor we can have some kind of focus rectangle around the active row? At the moment it is sometimes hard to keep track of which row I am on. I guess ideally it would have a focus rectangle around the cell itself and then a light background for the row / column of the cell.

Can this be done?

**Comment by lostkeys** [comment]
I've looked through the code and unfortunately there is no attributes on a focused cell or row to use as a CSS target for something like this, sorry. We will consider adding it to TinyMCE 5 when a table plugin update comes due.
