### ISSUE TITLE
Have a max-width/height option for images while editing

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5283]
Here was a two years old closed request https://github.com/tinymce/tinymce/issues/3996 but the answer was not was I expected.

> You can set the content_style setting to something like content_style: 'img {max-width: 100%;}' and the images should resize to fit the editor.

If you set the width to max 100%, this does not change the height. Thus the graphic is wrongly represented. You can set the height to "auto", but this has only one effect on the editor. I want it to the editor and the saved content. I also want the image to have static dimension values and not maximum and "auto". For mobile max values and auto is fine.

Therefore I would like an option for "image_max_width" possibly even "image_max_height". Depending on what is exceeded first, the dimensions are automatically adjusted in the dialog. Because my website have a fixed width.

Example image_max_width=400
If a graphic is entered with 800x1200px, then the width should be 400px and the height automatically set to 600px. So that the graphic is not distorted.

Source: https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts#L382

in plugins/image/plugin.js I changed
```
            var result = data.map(function (dimensions) {
              return {
                width: String(dimensions.width),
                height: String(dimensions.height)
              };
            });

```
to
```
            var result = data.map(function (dimensions) {
              var max_width = editor.getParam('image_max_width', 0, 'number'),
              max_height = editor.getParam('image_max_height', 0, 'number');
              if (max_width>0 && dimensions.width>max_width)
              {
                dimensions.height = parseInt(dimensions.height / (dimensions.width / max_width));
                dimensions.width = parseInt(max_width);
              }
              if (max_height>0 && dimensions.height>max_height)
              {
                dimensions.width = parseInt(dimensions.width / (dimensions.height / max_height));
                dimensions.height = parseInt(max_height);
              }
              return {
                width: String(dimensions.width),
                height: String(dimensions.height)
              };
            });

```
So I can set config-settings
image_max_width: 600,
or/and
image_max_height: 500,

**Comment by lostkeys** [comment]
Thanks for your suggestion. The behavior you are suggesting is normally handled via CSS so we don't have any plans at this time to reimplement max-width/max-height for the HTML attributes. It should be possible for you to accomplish what you need in post processing, either via javascript before submit or server-side. I have noted your feature request.
