### ISSUE TITLE
Autoresize remember size of editor

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5284]
Feature-Request for https://www.tiny.cloud/docs/plugins/autoresize/

It would be nice a new setting like "autoresize_remember_height_on_init" as boolean. So every user can change size of editor individually. Remembered size should be between min_height and max_height and restored by editor init.

Is here maybe a example to do this? Like https://community.tiny.cloud/communityQuestion?id=90661000000ESYWAA4

Where I can find ResizeEditor-Event (editor events at all) in documentation? Is there a setHeight Methode for editor?

**Comment by lnewson** [comment]
This isn't something that makes sense to include within TinyMCE as the editor height will vary depending on both the content being loaded and on which page the editor is being loaded, as it could be loaded for different things (eg blog posts, wiki's, etc...). As such it's really something that should be set up in the integration layer and saved for the user's settings, or something similar and then set when calling `tinymce.init`.

You can track the current width/height from either listening to the `ResizeEditor` event or just getting the height when the page is closed, saved, or similar actions. From there you can do something similar to the linked community forum post to use `editor.getContainer().clientHeight` to get the height/width and store that either in local storage or in some user data store. You can then use that in the init configuration when loading the page.
