### ISSUE TITLE
Multiple inline editors retain the selected toolbar options of previous class when new class is clicked. 

### ISSUE THREAD

**Issue by reshma-epsilon** [tinymce/tinymce#5286]
When editor mode is inline and when we have many classes, the selected toolbar option is highlighted even when editing on new class for the first time.

See https://www.tiny.cloud/docs/general-configuration-guide/multiple-editors/

The toolbar options should not remain highlighting its previously selected options when new class is edited.

This issue is in TinyMCE v5

**Comment by lnewson** [comment]
This appears to be a duplicate of https://github.com/tinymce/tinymce/issues/5244
