### ISSUE TITLE
Text floated as if the editor is seeing the image from the previous editor instance on the page.

### ISSUE THREAD

**Issue by brothersun** [tinymce/tinymce#5287]
![TinyMCE_BUG](https://user-images.githubusercontent.com/18388454/69587643-f6e7fb80-0f9a-11ea-942f-5d5bf8001974.PNG)

In the attached graphic, you can see that the editor is floating text to the right as if the editor is seeing the image from the previous editor instance on the page!  Note that due to the masonry flow of DIVs on the page, the previous instance of the editor is the one to the left with the actual image.

This improper floating of text does not occur in any other editor instance on the page, including instances preceded by an instance with an image. So, it does not appear to be repeatable.

Using TinyMCE Version: 5.0.0-1 (2019-02-04) on Window 10. This occurs in Chrome 78.0.3904.97 but not in Firefox 69.0.1 (64-bit)

**Comment by lostkeys** [comment]
Strange... In order for us to better debug this issue and rule out any issues with the content's css, we would need you to try to replicate the issue in a [TinyMCE Fiddle](http://fiddle.tinymce.com/) or otherwise give us access to a working example. Thx.

**Comment by brothersun** [comment]
The fact that it does not occur in Firefox implies that it's not a CSS issue. My guess is that since there is no image in the affected editor instance, the image info from the previous editor instance is still present in some internal memory address that the next editor uses. I tested this theory by adding an image of a different size to the affected DIV and as you can see,, the editor adjusted the floating text to correctly conform to the new image. Interestingly, when I then deleted that new image, the editor went back to floating the text as shown in my original post! Note: When I log out of admin mode on the website, the editors go away and the text appears correctly, So, it's not a serious problem for me, to where I would want to devote more time to helping to debug it. But, thanks.
![TinyMCE_BUG2](https://user-images.githubusercontent.com/18388454/69693744-532a4880-108b-11ea-9f75-35900c08f3bf.PNG)

**Comment by lostkeys** [comment]
We have never seen the issue ourselves, could be a css rendering bug in Chrome. We will keep our eyes open.
