### ISSUE TITLE
Tinymce 5 Quickbars toolbar won't appear, or has incorrect positioning

### ISSUE THREAD

**Issue by JayAdra** [tinymce/tinymce#5288]
**Bug Report**

**Using:**
Tinymce 5.0.14
Quickbars plugin (distraction-free editing)

**Expected behaviour:**
When selecting some text, the context toolbar should be appearing above the selection consistently.

**Actual behaviour:**
If you click-and-drag to select text, ending with your cursor outside of the editor before releasing the mouse, the toolbar won't appear at all.

![image](https://user-images.githubusercontent.com/2704964/69600455-683bb300-105c-11ea-845b-8fb9fe6744b6.png)

Additionally, sometimes when selecting text (often across multiple paragraphs), the toolbar will appear overlapping some of the selection, as if the positioning calculation is off, or hasn't updated.

![image](https://user-images.githubusercontent.com/2704964/69600450-62de6880-105c-11ea-83ef-3b8560a896a3.png)

Initially found issue in my own app, using v5.0.14 in Chrome 78.0.3904.108, but can also be seen on the tinymce demo page: https://www.tiny.cloud/docs/demo/editor-dfree/

Screen Recording of the bugs:
[Toolbar Bugs Screen Recording.zip](https://github.com/tinymce/tinymce/files/3890088/Toolbar.Bugs.Screen.Recording.zip)

This makes this mode essentially unusable for my app, as my editors are quite "invisible" to the user and they would often be dragging their mouse outside of its bounds etc.

**Comment by lostkeys** [comment]
I can replicate both issues in this [TinyMCE fiddle](http://fiddle.tinymce.com/kWgaab/1)

The context toolbar getting stuck in the middle of the content is a bit more prevalent in Chrome than in Safari. The stuck toolbar seems to be because the mouse is fast enough to trigger interactions in the toolbar thus stoping it from moving.

I can [replicate both issues in TinyMCE 4](http://fiddle.tinymce.com/kWgaab/2) as well, but it's very difficult to get the context toolbar to stick the same way it does in v5.

**Comment by JayAdra** [comment]
Appreciate the speedy response. Interesting that it's in v4 too. I'm surprised it hasn't come up before now.

Any rough ideas when this one will get looked at? Waiting on this fix for a project before it can launch.

**Comment by TheSpyder** [comment]
The issue with the bar not appearing would require us to listen to mouse events outside of the editor area, which sounds complicated as we'd need to be very careful about edge cases.

The issue with the bar appearing too soon should be a much more simple fix - the bar seems to be listening for node change events which only makes sense during keyboard selection. While the mouse is held down it should wait for mouse up before appearing.

**Comment by JayAdra** [comment]
I may be able to work around the first issue with the mouse up occurring outside of the editor, so even just getting the second issue fixed would be great for me.
