### ISSUE TITLE
forecolor configuration color_cols does not update the color picker grid

### ISSUE THREAD

**Issue by cecilialam** [tinymce/tinymce#5290]
According to the [documentation](https://www.tiny.cloud/docs/configure/content-appearance/#color_cols), I can customize the color picker grid columns by adding color_cols in the init.

```color_cols: "8"```

I'm on v5.1.1. I can reproduction the issue on the Test site: http://fiddle.tinymce.com/baaaab

Expected:
* color picker grid has 8 columns when pops open

Observed:
* color picker grid has 5 columns (default value)

**Comment by lnewson** [comment]
Sorry, in 5.0 this setting got changed to require a number instead of a string but it seems that the docs haven't been updated. So if you use `color_cols: 8` it should work as you'd expect. I've also logged an internal issue for us to update the docs.
