### ISSUE TITLE
Ability to show actual size images

### ISSUE THREAD

**Issue by ryamaguchi0220** [tinymce/tinymce#5293]
**Is your feature request related to a problem? Please describe.**

In my use case,  I insert images specifying smaller width and height than their actual size. However, occasionally I'd like to see the inserted images at their actual size instead of the minimized size to see details.

**Describe the solution you'd like**

It would be nice to show the actual size image when clicking one of inserted images.

Thanks!

**Comment by lostkeys** [comment]
You can do that via some clever css. [Here is an example](http://fiddle.tinymce.com/wWgaab#) to get you started. Please feel free to reopen this issue if you have additional questions for this. Cheers!

**Comment by ryamaguchi0220** [comment]
@lostkeys 

Thank you for your suggestion and sorry for lack of my explanation.
I'd like to do that in the generated html not the editor and imagine a more rich UI.

I think It would be good to overlay images on top of the current page with some abilities（[example](https://jsfiddle.net/drv59n3o/)）
* Ability to switch images
* Ability to zoom in/out an image

What do you think about it?
