### ISSUE TITLE
Changing link through quickbar doesn't fire events

### ISSUE THREAD

**Issue by mpskovvang** [tinymce/tinymce#5294]
**What is the current behavior? Describe the bug**
When changing the link href through the quickbar no event (change, input, dirty etc.) is fired.

Other quickbar actions like unlink, bold does fire events.

However, changing the link href from the link dialog does fire events.

**What is the expected behavior?**
I would expect an event being fired. In a Vue project, I watch content changes and analyze the content like word density, links etc.

By looking in the source code the reason might be the link dialog forces the changes in a undo transact while the quickbar doesn't.

https://github.com/tinymce/tinymce/blob/d16a86d9ec2e4fb1f6a5b352bbf6d659da785cc4/modules/tinymce/src/plugins/quickbars/main/ts/selection/Actions.ts#L23-L27

https://github.com/tinymce/tinymce/blob/d16a86d9ec2e4fb1f6a5b352bbf6d659da785cc4/modules/tinymce/src/plugins/link/main/ts/core/Utils.ts#L137-L161

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Using TinyMCE 5.1.2 with Chrome 78.0.3904.108.

**Comment by lnewson** [comment]
This has now been fixed in TinyMCE 5.4.0, which was released at the start of the month. Thanks for reporting this issue and please do let us know if you find any additional issues.
