### ISSUE TITLE
Issue with non-editable content selection 

### ISSUE THREAD

**Issue by nishtha18mittal** [tinymce/tinymce#5295]
I have a non-editable content let - `<var id="xxx" title="xx" class="xx mceNonEditable" data-title="xx" contenteditable="false"><label class="xx" style="xx" data-mce-style="xx"> content </label>test content1 <label class="xx" style="xx" data-mce-style="xx"> content </label></var><var id="xxx" title="xx" class="xx mceNonEditable" data-title="xx" contenteditable="false"><label class="xx" style="xx" data-mce-style="xx"> content </label> test content2 <label class="xx" style="xx" data-mce-style="xx"> content </label></var>`.

I am not able to select the two non-editable content at the same time through mouse.

The another issue which i am facing is when i select the one non-editable content with var tag at the end of the editor and fires the editor.selection.getContent() command then the editor gives me 
The content   - 
`<label class="xx" style="xx" data-mce-style="xx"> content </label> test content2 <label class="xx" style="xx" data-mce-style="xx"> content </label>`

 Instead of giving -
`<var id="xxx" title="xx" class="xx mceNonEditable" data-title="xx" contenteditable="false"><label class="xx" style="xx" data-mce-style="xx"> content </label> test content2 <label class="xx" style="xx" data-mce-style="xx"> content </label></var>`

**Comment by lostkeys** [comment]
That was a lot of x:es. In order to replicate the first issue, can you [make a TinyMCE fiddle](http://fiddle.tinymce.com) for us to better debug the issue?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
