### ISSUE TITLE
In editor on image move it will disappearing

### ISSUE THREAD

**Issue by parthfaladuks** [tinymce/tinymce#5296]
**What is the current behavior? Describe the bug**
Hello, after uploading image and moving image to left to right or right to left side than sometimes it will disappearing so may i know how to prevent this issue ?

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/6Wgaab/1

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
i am using **5.0.16** TinyMCE version.

**Comment by lostkeys** [comment]
You mean moving as in using the align left/right buttons? What browser and OS are you using? I could not replicate it on MacOS Safari. Can you perhaps make a screen recording and upload too?

**Comment by bes-internal** [comment]
Chrome 79
If image drag and drop (mouse) it will disappearing if image larger than editor screen

**Comment by lnewson** [comment]
Closing due to a lack of additional information. If you can provide the information requested above (ie a video or replication case) then we'll be happy to reopen this issue.

**Comment by bes-internal** [comment]
https://youtu.be/JVESVSbJfsk
