### ISSUE TITLE
Invalid css values in skin.css

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5297]
There are few css errors and warnings in skin.min.css for tinymce 5

https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Ffiddle.tinymce.com%2Ftinymce%2F5.1.2%2Fskins%2Fui%2Foxide%2Fskin.min.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by lostkeys** [comment]
Ouch, definitely need to look over those errors. Thx for calling us out on it.

**Comment by lostkeys** [comment]
This has been fixed and will be released with an upcoming version
