### ISSUE TITLE
Question: Position "Insert/edit image" modal inside iframe

### ISSUE THREAD

**Issue by CViniciusSDias** [tinymce/tinymce#5298]
I need to change the position of the "Insert/edit image" modal from a TinyMCE instance that runs inside an iframe. Is there any callback executed when this modal is shown so I can change its position?

**Comment by lnewson** [comment]
The only available event you'd be able to use is the `OpenWindow` event, however it's fired for all dialogs so there's no way to differentiate between them and apply some logic specifically for the link dialog.
