### ISSUE TITLE
Default Squared Bullets with more padding-left ?

### ISSUE THREAD

**Issue by danypt77** [tinymce/tinymce#5299]
Is there a way to put **more margin-left to the default bullets** ?

I have **custom bullets**, and **they have more padding-left** than the default ones.

my code:

```
style_formats: [
     {title : 'Bullet Wrong', selector : 'li', styles : {background: "url('/img/layout/icons/wrong.png') no-repeat left 2px", height:'18px', padding:'0 0 0 25px' }}
```

Thank you very much

**Comment by lostkeys** [comment]
You can use the [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) option to tweak the default content styles. [Here is an example](http://fiddle.tinymce.com/CWgaab)

Please feel free to reopen this ticket if you have additional questions
