### ISSUE TITLE
Problem with page configure/file-image-upload.md

### ISSUE THREAD

**Issue by LDdesign** [tinymce/tinymce#5300]
i'm having troubles with a custom file picker. 
Everythings seems to be working finde, except, i can't get a poster and alternative source into the medie dialog. The documentation says:

tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  file_picker_callback: function(callback, value, meta) {
    // Provide file and text for the link dialog
    if (meta.filetype == 'file') {
      callback('mypage.html', {text: 'My text'});
    }

    // Provide image and alt text for the image dialog
    if (meta.filetype == 'image') {
      callback('myimage.jpg', {alt: 'My alt text'});
    }

    // Provide alternative source and posted for the media dialog
    if (meta.filetype == 'media') {
      callback('movie.mp4', {source2: 'alt.ogg', poster: 'image.jpg'});
    }
  }
});

This works for alt, text but not for source2 and poster.
And hints?

> *affected page: https://www.tinymce.com/docs/configure/file-image-upload/*

**Comment by lostkeys** [comment]
Sorry, I accidentally deleted a comment from @LiuCao. It basically said "I have the same problem as you".

**Comment by lostkeys** [comment]
What version of TinyMCE do you use?

**Comment by lnewson** [comment]
It's also worth noting that we're aware that there's currently an issue where you can't set the alternative source or poster for a media file from a file picker callback. We've already implemented a fix, which should go out in TinyMCE 5.2 I believe. I'll link this issue to our internal tracker and we'll let you know when the fix has been published.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue.  The `file_picker_callback` will now currently update the poster, etc... fields when provided. Please let us know if you have any further issues.
