### ISSUE TITLE
cursor goes inside the element if add css to the last content in tinymce

### ISSUE THREAD

**Issue by nishtha18mittal** [tinymce/tinymce#5301]
I have a content let "This is for testing purpose" the purpose which is the end content in tinymce has some html tag with the css property background-color.
The issue is whenever i try to type some thing or try to add some new content in tinymce,it goes inside the html tag of the last content('purpose').However I want the newly added content should place outside the tag of the last content. Is there any way to do this.

Below is the TinyMCE fiddle for it, when we are going to add some new content, it goes inside the var tag,I want the newly added content goes outside of the var tag.

http://fiddle.tinymce.com/

**Comment by lnewson** [comment]
@nishtha18mittal I think you may have included the wrong link, as that's just the generic fiddle which doesn't have any example/reproduction case. Can you please double check?

To get things started though, I think what you might be talking about is our [inline boundaries](https://www.tiny.cloud/docs/configure/content-appearance/#inline_boundaries_selector) functionality. which will allow you to place the cursor inside or outside of an element if you add the elements required, eg `inline_boundaries_selector: 'a[href],code,var'`.

**Comment by lnewson** [comment]
Closing this as the information requested above hasn't been provided, so we can't investigate any further. We'll be happy to reopen this if you're still having issues and can provide the requested information.
