### ISSUE TITLE
Reporting a security issue

### ISSUE THREAD

**Issue by securityMB** [tinymce/tinymce#5304]
Hello; is there some security contact where I can report a security issue in TinyMCE (namely: XSS) privately?

**Comment by lnewson** [comment]
Hi @securityMB, you should be able to get in contact with someone by emailing infosec@tiny.cloud. 

Here's the exert from https://about.tiny.cloud/legal/website-terms/ for full details: 
> Tiny values the work of security researchers in improving the security of technology products worldwide. We welcome researchers who wish to responsibly disclose vulnerabilities in our products or systems. Note that we do not offer any “bug bounty” program or any form of payment for disclosed vulnerabilities. If you would like to report a vulnerability, please email infosec@tiny.cloud.
