### ISSUE TITLE
Code Sample plugin localization

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5308]
**What is the current behavior? Describe the bug**
Code Sample plugin is missing a translation for the phrase "Code view".  Please see attached screen shot.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
![codeview](https://user-images.githubusercontent.com/54727261/70484718-8adcbb80-1aa1-11ea-9258-9187db655f46.png)

TinyMCE 5

**Comment by lnewson** [comment]
This is being sent through for translation and is included in transifex, it's just that the translation hasn't been approved in Transifex so it's not available in the community language packs at this stage. Here's an example of what it looks like when I manually added in the translation:

![Selection_151](https://user-images.githubusercontent.com/1575550/70485117-c4610580-1b39-11ea-8bcd-3532717e00b0.png)

**Comment by plainnany** [comment]
@lnewson In the example above, how to add the translation manually?

**Comment by lnewson** [comment]
@plainnany for the above I just added the translation manually to the language pack JS file.

Alternatively you could do something like this after the editor has initialized:
```
tinymce.init({
  ...,
  init_instance_callback: function() {
    tinymce.i18n.add('ja', { 'Code view': 'my translation' });
  }
})
```
Note: It needs to be after init, otherwise TinyMCE won't load the language pack.
