### ISSUE TITLE
Code Sample Plugin - config to support not filtering out code sample HTML 

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5309]
**What is the current behavior? Describe the bug**
We integrated with the "Code Sample" plugin and found that markup added by the plugin to style code snippets is stripped off in the copy used for persistence.  This is because when the text is copied from TinyMce editor to HTML text area, the "Code Sample" HTML markup is removed.  As a result, we need to call prism.js to add back the markup when loading each page for display, which unfortunately adds overhead that impacts performance, especially when new data is added dynamically to the page via AJAX after the page is already loaded, e.g. new replies in a discussion board

This is a request to see whether the plugin's call to remove the "Code Sample" markup can be made optional or configurable, which would be very helpful for our use case as we can then save the data with the markup, which eliminates the need to call the Javascript on each page load or message rendering.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment]
TinyMCE isn't filtering out any markup used for codesample, as all the codesample plugin does is add the content wrapped in a pre and code element (eg: `<pre class="language-markup"><code>content</code></pre>`) and then it provides an embedded version of PrismJS to make it render inside the editor. If you want the content to be styled outside the editor, then you'll need to add PrismJS or a similar syntax highighting library to your site as mentioned in the docs: https://www.tiny.cloud/docs/plugins/codesample/#usingprismjsonyourwebpage as adding external JavaScript to the page is outside of scope of what TinyMCE is able to handle.

**Comment by brittanytang** [comment]
Yes, we're trying to see whether there's a way to keep the styling outside the editor without having to call Prism.JS and incur the performance overhead.  

The code that I was referring to is in codesample's plugin.js, starting at line 1026:

`var setup = function (editor) {
    var $ = editor.$;
    editor.on('PreProcess', function (e) {
      $('pre[contenteditable=false]', e.node).filter(Utils.trimArg(Utils.isCodeSample)).each(function (idx, elm) {
        var $elm = $(elm), code = elm.textContent;
        $elm.attr('class', $.trim($elm.attr('class')));
        $elm.removeAttr('contentEditable');
        $elm.empty().append($('<code></code>').each(function () {
          this.textContent = code;
        }));
      });
    });
    });

I found that commenting out this code preserves the <span> added by the plugin, without having to call prism.js.  So, we're hoping that there's a way to make calling this configurable.

**Comment by lnewson** [comment]
That only removes the `contenteditable` attribute and makes sure it's wrapped in a `<code>` block when getting the content from the editor. The plugin never adds anything itself outside of what I mentioned, as PrismJS is what does all the styling of the content inside the pre element.

**Comment by lnewson** [comment]
I also add that even if you do manage to get the content from the editor, with the PrismJS markup included, then it still won't render on your site without the required PrismJS CSS.
