### ISSUE TITLE
Safari and WKWebview scrolling issues on iPhone running iOS13

### ISSUE THREAD

**Issue by chris-tradify** [tinymce/tinymce#5312]
**What is the current behavior? Describe the bug**
When the mobile theme is used, and the editor takes up the whole viewport, for long text that requires scrolling, it takes several attempts to scroll to get to the bottom, and from the bottom to the top. This occurs both when tinymce is shown in a WKWebview in app, and when it is displayed in Safari

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Display [this](https://github.com/tinymce/tinymce/files/3948050/test.html.zip) in Safari or a WKWebview on an iPhone running iOS 13
2. Fill in with a long amount of text (enough to cause a scroll)
3. Attempt to scroll from the top to the bottom (or vis versa)
4. Observe that you can't scroll all the way on the first scroll

**What is the expected behavior?**
You should be able to scroll smoothly through all the text

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Observed with TinyMCE version 5.0.11 and 5.1.3 in iOS 13 on iPhone

**Comment by lostkeys** [comment]
Yeah, unfortunately the way Safari handles the viewport is very problematic for us. We never got the old mobile theme to work right. In TinyMCE 5.1 we introduced better mobile support using the default silver theme, and I suggest you try that

Try updating your config to this:
```
tinymce.init({
    selector: '#mytextarea',
    mobile: {
        plugins: 'fullscreen',
        toolbar: 'undo bold italic underline fontsizeselect fullscreen'
    },
});
```

**Comment by TheSpyder** [comment]
The mobile theme has been deprecated in 5.1 and will be removed in a future release.
https://www.tiny.cloud/docs/release-notes/release-notes51/#mobiledevicesnowusethesilvertheme

The mobile theme is now considered legacy, it is never enabled by default and we did not update it for iOS 13 (all efforts went into making the silver theme mobile responsive).
