### ISSUE TITLE
Toolbar and menu buttons unresponsive in current cloud release

### ISSUE THREAD

**Issue by nikrolls** [tinymce/tinymce#5313]
**What is the current behavior? Describe the bug**

In the current cloud version (5.1.3), the toolbar and menu buttons are unresponsive.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Navigate to any demo on the tiny.cloud site and try to use the toolbar and menu.
https://www.tiny.cloud/docs/quick-start/

**What is the expected behavior?**

Buttons should do something (eg bold), dropdowns should open, menus should open, but they don't. This also affects other sites using the latest cloud version.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest cloud version (5.1.3)

**Comment by lostkeys** [comment]
The demos works fine for me. Can you try again? We did a new release last night, and you might have hit some weird caching issue.

**Comment by nikrolls** [comment]
Hi, I've done some more digging and it seems like it's to do with devices that report touch as their primary input source (eg Microsoft Surface devices, many hybrids, and I've also confirmed on an Android phone with a mouse attached). When the editor initialises on a device with touch as the primary input, the mouse handlers don't seem to be hooked up. Interestingly this only started affecting us yesterday, but seems to have affected others earlier.

Now that I know the exact scenario, it seems that this issue is already tracked in https://github.com/tinymce/tinymce/issues/5310. Therefore my issue is a duplicate.
