### ISSUE TITLE
 option in tinymce editor to select multiple phrases that aren’t continuous

### ISSUE THREAD

**Issue by itsmedeepakupadhya** [tinymce/tinymce#5314]
sometimes we need to apply text color changes to multiple phrases that aren’t continuous. Instead of having to select all of these, select text color and repeat for each segment, it would be less clicks if it wasn’t necessary to select the text color each time (since it would apply across all selections at once). Word allows this [ If we hold CTRL key we can achieve this in WORD].

is there any option in tinymce editor to select multiple phrases that aren’t continuous.

**Comment by lostkeys** [comment]
No unfortunately TinyMCE doesn't support multiple simultaneous text selections. We don't have it on any short-term roadmap at the moment but I'll log a feature request for you.

**Comment by lnewson** [comment]
It's also worth mentioning that TinyMCE relies on the browsers selection API to do any form of selection and at the time of writing Firefox is the only browser that supports multiple selection ranges. Other browsers haven't made a move in this space and there's no indication they plan to support it in the immediate future.

Here's some additional details from our blog: https://www.tiny.cloud/blog/a-quick-guide-to-browser-selection-models/
