### ISSUE TITLE
[question] Single character selection

### ISSUE THREAD

**Issue by johnjacobkenny** [tinymce/tinymce#5316]
I am able to perform processing on backspace (or delete key) in the case of a _selection_. I want to do the same for the case of _single character_. 

I looked at the docs and couldn't find a solution for it. Is there any way to get a selection for a single character? Or is there any other way I should be looking at this problem? Thanks!

**Comment by metricjs** [comment]
Hi, could you please explain your use case? Exactly what steps do you want to be able to do, and what outcome do you expect? There are many ways to do and interact with selections, so we need more information to understand how to help you.

**Comment by johnjacobkenny** [comment]
I want to store the information of which user deleted that text.

**Comment by metricjs** [comment]
You said `I am able to perform processing on backspace (or delete key) in the case of a selection.` - could you please make a demo of how you are doing this using http://fiddle.tinymce.com/? We might be able to then modify it for the single character case.

**Comment by johnjacobkenny** [comment]
Thanks for the quick response, here is a sample fiddle showing the basic functionality. http://fiddle.tinymce.com/1Xgaab/2

**Comment by johnjacobkenny** [comment]
I think that the annotator api (https://www.tiny.cloud/docs/api/tinymce/tinymce.annotator/) could be leveraged to accomplish my goal, but the problem is that it works _only with a selection context_.

My requirement is that whenever a user modifies the text content, I want to markup that content with the user details.

**Comment by metricjs** [comment]
Ah, so you're trying to implement track changes functionality? That is an extremely difficult problem to solve. In case this might be a viable solution for you, one of our technology partners - LoopIndex - has a track changes plugin for TinyMCE - [https://www.loopindex.com/flite/demo/tmce/](https://www.loopindex.com/flite/demo/tmce/). 

If I remember correctly, the Annotator API is used for the Comments plugin and isn't likely to help you in this case. 

I had a go at making something based on your fiddle: http://fiddle.tinymce.com/1Xgaab/4 . It does add the marker for single characters, but it is very basic and there are many ways it will break. It really only works if your cursor is in paragraphs of text to be honest. I also found that if I select content, press backspace then type the new content appears in the del element, which I imagine is also not desirable.

Unfortunately, we can't think of anything that would solve this without a lot of dev work. You need to be able to either intercept and override deletions, or be able to DOM walk, both of which are beyond TinyMCE's current API.

**Comment by johnjacobkenny** [comment]
Thanks for the sample code, it solves the problem I was looking into. I'll take a look at LoopIndex and see if it works out for us.

Thank you very much for helping out with this. 😃
