### ISSUE TITLE
Adding column not making the table resize to make it same size as other columns

### ISSUE THREAD

**Issue by elshobokshy** [tinymce/tinymce#5317]
I'm using the latest version of Tinymce. When I try to "Add a column before/after", each added column gets added inside the column I'm adding into, and doesn't add to the overall table, thus not resisizing the whole table but only the column where it's in.

![chrome-capture](https://user-images.githubusercontent.com/14349626/70720976-20bc5480-1cf5-11ea-80ea-67af57fbb2cc.gif)

Any idea how to make the add columns add to the overall table, and resize the whole table depending on that newly added column ? As if it's doing a table-layout fixed automatically? 

Another way to explain what I'm looking for is : when we click on add column, the width of the new column added should be proportional to the number of columns we have. Say we have 9 columns width a width of 100%. The new added column should be equal to 10%, without taking into consideration any manual resize of other columns.

**Comment by lincolndennis** [comment]
Just to confirm, from an HTML structure perspective, the columns are being added to the correct/overall table, in the correct place, with the correct relationship to other columns.
As an example:

```
<table style="border-collapse: collapse; width: 100%;" border="1">
<tbody>
<tr>
<td style="width: 12.5%;">&nbsp;</td>
<td style="width: 12.5%;">&nbsp;</td>
<td style="width: 25%;">&nbsp;</td>
<td style="width: 50%;">&nbsp;</td>
</tr>
<tr>
<td style="width: 12.5%;">&nbsp;</td>
<td style="width: 12.5%;">&nbsp;</td>
<td style="width: 25%;">&nbsp;</td>
<td style="width: 50%;">&nbsp;</td>
</tr>
</tbody>
</table>
```

But I can confirm the behavior of the new columns not proportionately redistributing spacing from a styling perspective.

**Comment by elshobokshy** [comment]
@lincolndennis is there something I can do about it? Or is it a bug?

**Comment by lostkeys** [comment]
No, there is no workaround at the moment. We are looking at improving the tables plugin but I don't have any date for you yet, sorry.

**Comment by abhijeetj100** [comment]
Hey,
Anything new regarding this?
I am facing a similar issue.

Thanks

**Comment by lostkeys** [comment]
Sorry, we have no news to share for this.
