### ISSUE TITLE
Unresposive buttons on Chrome 79

### ISSUE THREAD

**Issue by freitasm** [tinymce/tinymce#5319]
Hi folks

Using Tiny cloud and buttons (hyperlink, etc) seem to be unresposive - select a text, click the button, nothing comes up. 

Someone reported this yesterday in our forums and today I can reproduce it.

Anyone else seeing this?

**Comment by lnewson** [comment]
I'm guessing you're using a "hybrid" device such as a Surface book? If so this is likely a duplicate of https://github.com/tinymce/tinymce/issues/5310

**Comment by freitasm** [comment]
Thank you... It seems that way - I am checking with our user about his setup but yes, it is not working on my Surface now but yesterday when I tested I was using my desktop.

Closing this now. Cheers.
