### ISSUE TITLE
Images in editor don't dragged when using selenium Webdriver

### ISSUE THREAD

**Issue by fredknyazev** [tinymce/tinymce#5320]
Drag'n drop works in other editors, but here it freezes at the stage of 'move_by_offset' after "click_and_hold"

Example:
actions = ActionChains(wdriver)
actions.move_to_element_with_offset(tinymce, 128, 150).click_and_hold().perform()
actions.reset_actions()
actions.move_by_offset(100, 0).perform() <--- Stops here
actions.reset_actions()
actions.release().perform()
actions.reset_actions()

**Comment by lnewson** [comment]
I'm sorry but this doesn't appear to be a TinyMCE issue as it works fine when dragging and dropping with user actions. That likely means it's an issue with your setup or code. If you can provide a small sample repo of the problem we can take a look and try to make some suggestions, but honestly this is getting outside the scope of what we can support.

**Comment by lnewson** [comment]
Closing due to a lack of additional information. If you can provide the information requested above then we'll be happy to reopen this issue.
