### ISSUE TITLE
Allow max/min height to accept valid css values

### ISSUE THREAD

**Issue by edewaal97** [tinymce/tinymce#5322]
Interesting that height and width values can be a number and any valid css, but the max_height and min_height can only be a number. I would like to have these values also accept css attributes, like 80vh.

**Comment by lostkeys** [comment]
This would apply to all autoresize plugin properties as well, like `autoresize_bottom_margin`,  `autoresize_min_height`, `autoresize_max_height`, `autoresize_overflow_padding`
