### ISSUE TITLE
Modal dialog without transparency on mobile devices

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#5323]
**Bug:** Modal dialog without transparency on mobile devices

**Expected behavior:**
Like on standard devices when a modal dialog pop up the background should be visible (opacity<1)

Buggy since 5.1.x, but only on mobile devices

Standard device is OK:
![image](https://user-images.githubusercontent.com/1309628/71255935-ab253980-232f-11ea-926c-356ddadac0f8.png)

Mobile device is buggy:
![image](https://user-images.githubusercontent.com/1309628/71256014-de67c880-232f-11ea-99b8-bad7abd566a1.png)

To reproduce in fiddle use Browser Debugger:
- activate a mobile device
- press button "init tiny ..."
http://fiddle.tinymce.com/FCgaab/14

**Comment by lostkeys** [comment]
Unfortunately the way Safari on iOS handles the viewport is a PITA. The implementation we went with has the dialog docked at the top of the HTML document and restores the scroll position upon closing it. Having the modal be opaque is a way to hide that.

You can change this behavior by [creating a custom skin](https://www.tiny.cloud/docs/advanced/creating-a-skin/) and use the `@dialog-backdrop-background-color-opaque` variable to set the color value you like.
