### ISSUE TITLE
Can't move cursor before or after <section>

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#5324]
**What is the current behavior? Describe the bug**

When a `<section>` is the first or last element in the editor, or when it's adjacent to another `<section>` element, it's not possible to move the cursor before or after the section. The cursor remains in the section regardless of where you click or which arrow keys you press. As a result, it's not possible to insert new content before or after.

This may affect other block-level HTML5 elements as well.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/ZXgaab

**What is the expected behavior?**

The user should be able to move the cursor before and after a <section> in order to create new content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

* TinyMCE 4.0 through 5.1.5
* Chrome, Firefox, Safari

**Comment by lostkeys** [comment]
Yeah, this is a use case that TinyMCE unfortunately does not handle very well. We have an interest in improving this but I don't have any details for you at this time.
