### ISSUE TITLE
Issue with Overlays/Popover

### ISSUE THREAD

**Issue by milap1296** [tinymce/tinymce#5326]
**What is the current behavior? Describe the bug**
If I have enabled both the spellchecker and quickbars plugins and I right click on the misspelled word, it shows me both suggestions & quickbar actions.

**Steps to reproduce**
[Codepen link](https://codepen.io/milap1296/pen/KKKjggb) 
Apply the spellchecker plugin and then right click the misspelled word, it will show both the suggestions & quickbar actions.

**What is the expected behavior?**
Should show only the suggestions box. Please let me know if this behaviour is expected or there is a way out to control such scenario.
 
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce (5.0.14)

**Comment by lostkeys** [comment]
It is expected, but I agree, it's not very elegant. We have an interest at improving this but I don't have any additional details for you at this time.
