### ISSUE TITLE
Page scrolls when typing in editor that is in a position: sticky element

### ISSUE THREAD

**Issue by noyearzero** [tinymce/tinymce#5327]
**What is the current behavior? Describe the bug**
In the very specific case of using a Chromium based browser, rendering tinymce inside an element that is position: sticky - then on some key presses (including arrow keys) the main scroll element will randomly scroll or jump in a certain direction.  

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/mYgaab/11

**What is the expected behavior?**
No jumping/scrolling

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce version 5.0.14 - I think this may have been an issue in the 4 branch as well.

**Comment by noyearzero** [comment]
I will note that a similar behavior happens when typing in textarea in position: sticky elements that are not tinymce on chromium browsers (I believe I submitted a bug request to chrome years ago, but haven't seen it fixed).  However I did set it it up so I could enable/disable tinymce and the issue will go away when tinymce is disabled and come back when it's enabled.

**Comment by lostkeys** [comment]
I can verify the issue on Chrome (MacOS). The text outside of the editor scrolls to the bottom for me when using the arrow keys after typing some characters in the middle of a sentence.

**Comment by lostkeys** [comment]
Just a quick update, we believe the issue might be that chrome picks up some focus events happening in TinyMCE and scrolls the document to the bottom to bring it into the viewport, ignoring that it's already visible. [See example here](http://fiddle.tinymce.com/IZgaab). But we are not sure. We have had similar issues before and it's not easy to fix head on.

**Comment by noyearzero** [comment]
Yeah, I think the ultimate issue is in Chrome also.  It's weird how it only happens sometimes and I can consistently fix it by disabling TinyMCE in this case.  However, I can create a similar issue without TinyMCE in other situations.  I believe I did post a bug to Chrome about it a long time ago, but never heard anything about it.
