### ISSUE TITLE
Error when destroying the editor on blur

### ISSUE THREAD

**Issue by rart** [tinymce/tinymce#5330]
#2121 is still an issue on the latest (v5).

**Please provide the steps to reproduce**

http://fiddle.tinymce.com/2Ygaab

1. Initialize an editor (unsure if selector vs target makes a difference).
2. Add blue handler to destroy editor onBlur
3. Destroy editor on blur
4. Notice console errors

```html
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
tinymce.init({
  target: myElementRef,
  plugins: ['quickbars'],
  toolbar: false,
  menubar: false,
  inline: true,
  suffix: '.min',
  setup(editor) {
    editor.on('init', function (e) {
      editor.focus();
      editor.selection.select(editor.getBody(), true);
      editor.selection.collapse(false);
    });
    editor.on('blur', function (e) {
      editor.destroy(false); // same result calling remove or destroy(false) or destroy without params
    });
  }
});
</script>
```

Throws error on the console:
```
tinymce.min.js:9 Uncaught TypeError: Cannot read property 'childNodes' of null
    at dg (tinymce.min.js:9)
    at gg (tinymce.min.js:9)
    at tinymce.min.js:9
    at Object.add (tinymce.min.js:9)
    at EE.i (tinymce.min.js:9)
    at Gz.fire (tinymce.min.js:9)
    at EE.fire (tinymce.min.js:9)
    at tinymce.min.js:9
    at tinymce.min.js:9
```

<img width="615" alt="image" src="https://user-images.githubusercontent.com/3928341/71717293-f05d6700-2e17-11ea-8086-0383dbfc3fd5.png">

Adding a timeout seems to workaround the issue.
```js
    editor.on('blur', function (e) {
      setTimeout(() => editor.destroy(false));
    });
```

**What is the expected behavior?**

No errors occur when destroying the editor on blur or otherwise. Regardless of the internal lifecycle - i.e. the destroy/remove methods should be smart enough to differ the task until ready to destroy.

**Alternatively**

Provide a API for consumers to do this reliably.

**Comment by lnewson** [comment]
This is because you're killing the editor inside it's own event handling, which has other things hooked up to the `blur` event which causes the exception you're seeing. As such you'll need to make sure you do one of the following:
1. Ensure your callback is the last blur handler (eg move it inside the `editor.on('init', ...)` callback)
2. Stop propagation so other blur event handlers aren't executed (eg via `e.stopImmediatePropagation()`
3. Use a timeout to delay the destroy (as you mentioned).

**Comment by rart** [comment]
This is good as it provides 1. some context around what's going on 2. steps to work around it. 👍 

Doesn't look like you guys agree - given the issue getting closed immediately - but I do think it'd be nice if the destroy/remove was somehow smarter.

Thanks. 🙂

**Comment by lnewson** [comment]
I'll log a task to investigate if we can make it smarter, but we can't just add a delay to the destroy as some users may require it to be removed immediately. It's possible we can possibly add some logic to stop any other event handlers processing if the editor is destroyed in the middle of handling an event (basically the same as manually calling `stopImmediatePropagation()`.
