### ISSUE TITLE
How can i find out which character gets deleted on backspace (before it actually gets deleted)?

### ISSUE THREAD

**Issue by supidea** [tinymce/tinymce#5332]
How can i find out which character gets deleted on backspace (before it actually gets deleted)?

**Comment by SimonFc** [comment]
Something like [this](http://fiddle.tinymce.com/KYgaab)? You can see how TinyMCE overrides the backspace key at [DeleteBackspaceKeys.ts](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/ts/keyboard/DeleteBackspaceKeys.ts), might can be useful.

I'll close this as this isn't an bug/feature request etc. but let me know if you were looking for something else!
