### ISSUE TITLE
Tiny Drive Not Working

### ISSUE THREAD

**Issue by hapo-tinhlt** [tinymce/tinymce#5333]
I followed the document to create standalone drive. after the configuration was done , i click on browse file, the resulting was broke. 
https://www.tiny.cloud/docs/tinydrive/tinydrive-api/standalone/
![image](https://user-images.githubusercontent.com/49738294/71834481-e9697980-30e1-11ea-82a8-24d5c7118270.png)

**Comment by lnewson** [comment]
TinyDrive is a premium product and this GitHub project is for the open source version of TinyMCE, so I'm afraid we can't help via GitHub. If you're having issues with TinyDrive, please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
