### ISSUE TITLE
Issue with "Text to display" input field in Insert/Edit Link dialog of Link plugin .

### ISSUE THREAD

**Issue by nishtha18mittal** [tinymce/tinymce#5335]
1- There is a content "This text is for link testing purpose" i put a link on "for" content the Insert link dialog is shown like :-
![image](https://user-images.githubusercontent.com/54704714/71978732-159c0c00-3242-11ea-9192-0ed39e6caf51.png)

2- Then in the same content i have select "for link " and click on the link plugin then the Insert link dialog :- 

![image](https://user-images.githubusercontent.com/54704714/71978354-21d39980-3241-11ea-8fd6-fa3dca7da3a3.png)

The issue is "Text to display" input field is not displayed on partial link text content

**Comment by lostkeys** [comment]
That is expected because you can't create nested links, so TinyMCE can't really resolve what to put into the field (technically it's possible but there have always been more important things to do). You are still able to create a new link on that second screen that will remove the old one.
