### ISSUE TITLE
Right-click does not work on touch devices

### ISSUE THREAD

**Issue by palczewski** [tinymce/tinymce#5337]
This is related to issue #5310, @lnewson asked me to create a new ticket for this.

**What is the current behavior? Describe the bug**
Right-clicking on an image or link in the content body does not work on touch devices.  It shows the browser context menu instead of the TinyMCE menu.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Happens with TinyMCE 5.1.5

**What is the expected behavior?**
Right-click menu should allow for changing the link or image.

**Comment by lnewson** [comment]
Thanks for logging this @palczewski I've logged an internal issue for this and we'll aim to get it fixed in 5.1.6. I don't have a timeframe on that atm, as we have another important fix we need to include for 5.1.6.

**Comment by EkimChau** [comment]
Hi palczewski,

This issue has now been resolved by TinyMCE 5.1.6 available to community and enterprise users.

best regards,

EkimChau
