### ISSUE TITLE
Caret with contenteditable false float elements

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5338]
**What is the current behavior? Describe the bug**
Caret doesn't display with contenteditable false float elements because they have no height
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1.Set content to p[contenteditable="false"]>img
2.Click on img
3.Press arrow right or arrow left key
4.Caret doesn't display
**What is the expected behavior?**
Caret display correctly
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0

**Comment by lostkeys** [comment]
I'm unsure what you mean. You have provided a CSS ruleset with no declarations and that does nothing. But if you mean `<p contenteditable="false">Text&nbsp;<img src="..." alt="" />&nbsp;text</p>` then no, the paragraph will be treated as a non selectable block. [See example here](http://fiddle.tinymce.com/GZgaab).

**Comment by lnewson** [comment]
Closing this due to a lack of additional information. If you can provide the information requested above, then we'll be happy to reopen this issue.
