### ISSUE TITLE
TinyMce init function breaks the Page when when 300+ editors are initialized.

### ISSUE THREAD

**Issue by sunder6218** [tinymce/tinymce#5342]
Hey everyone,

i have a form that loads the number of fields dynamically, and in one form it has over 500 textareas to fill, when i use 'selector' as 'textarea', my page gets stuck and the JS breaks and the page becomes unresponsive. i tried lazy loading but it still has to load 300 editors, is there any feature to load them asynchronously? or is there any better way to  do this?

here is my config.

`tinymce.init({
            selector: "textarea",
            branding: false,
            statusbar: false,
            menubar:false,
            toolbar: false,
            cleanup : true,
            table_tab_navigation: false,
            table_grid: false,      
            browser_spellcheck: true   });`

**Comment by Afraithe** [comment]
My first question would be why? Why do you load 300+ textareas?

**Comment by sunder6218** [comment]
> My first question would be why? Why do you load 300+ textareas?

well we have large forms in our system and that is a requirement, and even field is a textarea which is bound with tinyMce. and we want the text to be formatted and have the capacity to show bold , italic and even underlined text, so we opted for tinyMce, it works great for small forms, no complains there but when the instance of the tinyMce in the form size go higher, it takes significantly longer to load and inb some cases completely breaks the JS. my question is, is there a way to just load the tinyMce library once and then attach the intance to the textarea rather than loading the library for every textarea?

**Comment by DNWEIJ** [comment]
not sure what your use case is, but if you need to edit 300+ fields maybe you should change your way of working in just showing in read mode. Then onclick  on the text, attach editor and you have the editable tinymce text. Then have a event/click/save button to save the text to the backend and make the text readonly again.
