### ISSUE TITLE
TinyMCE editor is not initiating in IE 11 but works fine in chrome 

### ISSUE THREAD

**Issue by bharekarsanjay** [tinymce/tinymce#5346]
TiniMCE editor is not initiating in IE 11 but works fine in chrome 

Getting error : Unable to get property 'getItem' of undefined or null reference

**Comment by SimonFc** [comment]
Hi,
You need to provide more information for us to be able to act upon it. Is it possible for you to replicate the issue via [fiddle.tinymce.com](http://fiddle.tinymce.com/)? Thanks!

**Comment by lnewson** [comment]
Closing this as the information requested above hasn't been provided, so we can't investigate any further. We'll be happy to reopen this if you're still having issues and can provide the requested information.
