### ISSUE TITLE
Allowing to upload a dangerous file type or file type restriction.

### ISSUE THREAD

**Issue by chanpu9** [tinymce/tinymce#5348]
Please contact me in a private message to tell you more about detail of the vulnerability that i found.

**Comment by lnewson** [comment]
@chanpu9 would you please be able to contact infosec@tiny.cloud, as that'll contact our team who handle security issues? 

From https://about.tiny.cloud/legal/website-terms/:
> Tiny values the work of security researchers in improving the security of technology products worldwide. We welcome researchers who wish to responsibly disclose vulnerabilities in our products or systems. Note that we do not offer any “bug bounty” program or any form of payment for disclosed vulnerabilities. If you would like to report a vulnerability, please email infosec@tiny.cloud.

Note: It's not currently very easy to find these details sorry, but we're going to be adding them to the docs to make it easier to find shortly.

**Comment by chanpu9** [comment]
Ok
