### ISSUE TITLE
Chrome Upcoming cookie Update.

### ISSUE THREAD

**Issue by manoj-mass** [tinymce/tinymce#5350]
This is related to following warning attached in image. 

Google Chrome release has the potential to cause a significant impact on applications that utilize cookies for cross-site resources. This release is in response to make cookies secure by default within Chrome and is in alignment with other browser vendors' efforts for Safari, Edge, and Firefox.  

Noticed tinymce is also using cookies and third party cookies may effect existing sites if not take actions.

Is there an impact for existing applications using tinymce by this future release of google ?

[https://www.chromestatus.com/feature/5088147346030592](https://www.chromestatus.com/feature/5088147346030592)

<img width="1425" alt="Screen Shot 2020-01-16 at 4 16 12 PM" src="https://user-images.githubusercontent.com/26952806/72518602-b9f20400-387b-11ea-9588-10e5ce02a18a.png">

**Comment by lnewson** [comment]
@manoj-mass that's not TinyMCE itself, but instead the tiny.cloud website/service. This change doesn't impact TinyMCE, as TinyMCE itself doesn't create any cookies, so it's more of an issue with website integrations or server-side components if they are using cookies.

Either way I'll pass this onto our website/cloud teams to make sure the website/service aren't impacted, though I believe they've already done an audit and already fixed any potential issues.
