### ISSUE TITLE
Incorrect color in IE

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5354]
**What is the current behavior? Describe the bug**
If put color "#ef463a" into the color_map option and select it selection will be transparent and text color will be blue
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1.Set color #ef463a into the color_map
2.Select some text
3.Choose that color
**What is the expected behavior?**
Selection has correct color and text has correct color too
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0+ IE

**Comment by lnewson** [comment]
@versusvirus have you tried this using TinyMCE 5.1, as there was an issue with this got fixed in 5.1.0. I also tried to replicate this with the latest version and I wasn't able to replicate, so if you are using 5.1 can you please provide a video/gif on how to replicate?

**Comment by lnewson** [comment]
Closing this as the information requested above hasn't been provided, so we can't investigate any further. We'll be happy to reopen this if you're still having issues and can provide the requested information.
