### ISSUE TITLE
Readonly property not always working

### ISSUE THREAD

**Issue by DarkMikey** [tinymce/tinymce#5356]
**What is the current behavior? Describe the bug**
I really don't know what's going on here. 

1. Load tinymce with readonly config and display some toolbar tools (otherwise the problem won't be visible)
2. Sometimes, but only sometimes the buttons are disabled, sometimes not. To reproduce this you have to click the run button in the tinymce fiddle or reload the page. In the fiddle i get this bug about half of the times I load the page, in my project it's about 90% of the time. If you have e.g. bullet points in the toolbar you can also format text, which should definitely not happen.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/KZgaab

**What is the expected behavior?**
All toolbar options should be disabled

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
all 5.x versions are affected - works in 4.x though
tested in Chrome, Brave, Firefox 

Maybe refers to https://github.com/tinymce/tinymce/issues/3787

![TinyMCE-Fiddle-Brave-2020-01-20-13-56-31](https://user-images.githubusercontent.com/31889204/72728115-e617c880-3b8c-11ea-9f59-c5eb6bc623eb.gif)

**Comment by SimonFc** [comment]
Looks like it's related to the issue you linked to. Internally TinyMCE will set the mode on readonly via the init event when you set the readonly setting to true as you have done.
