### ISSUE TITLE
Fastest way to check for content

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#5357]
What is the fastest way to check if the editor has any content? `getContent() !== ''` is slow when the editor has a lots of content, so this is not a solution..

Empty editor contains a bogus `<br>` tag, so probably the fastest way would be:
```
let hasContent = editor.getBody().childNodes.length() > 1 || editor.getContent() !== ''
```

Is that correct?

**Comment by lnewson** [comment]
@petko there's the [`DOMUtils.isEmpty()`](https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.domutils/#isempty) API that should be able to be used for this and should be a lot quicker than `getContent` since you don't have to serialize and filter all the nodes. Here's an example:
```
let hasContent = !editor.dom.isEmpty(editor.getBody());
```

**Comment by petko** [comment]
Thank you!
