### ISSUE TITLE
Anchor rel attribute is not updated properly

### ISSUE THREAD

**Issue by felixmosh** [tinymce/tinymce#5359]
**What is the current behavior? Describe the bug**
When changing `rel` & link target, it not changes the `rel` properly.

**Steps to reproduce
Given this config: [http://fiddle.tinymce.com/XZgaab](http://fiddle.tinymce.com/XZgaab) 
There are several use-cases that i've noticed that are not working.

Use-case 1:
1. Create a link with `target: currentWindow` & `rel: No Follow`
2. Make sure that the link has only `rel="nofollow"`
3. Update the link's `target` to `newWindow`
4. Check link's attributes, `rel` remains only with `nofollow` (it should add **`noopener`** as well since https://github.com/tinymce/tinymce/issues/3177)

Use-case 2:
1. Same steps as use-case 1
2. Open the link update modal, Rel dropdown will point on `None` (it should be on `nofollow`)

Use-case 3:
1. Create a link with `target: newWindow`
2. The link that was created doesn't have `rel="noopner"` it should have since https://github.com/tinymce/tinymce/issues/3177

tinymce 5.1.5 on chrome

**Comment by lnewson** [comment]
I'm unable to replicate any of the issues mentioned here using Firefox, Chrome or Safari, as when testing `noopener` is always added as long as `New window` is selected as the target. @felixmosh can you please provide some details about your OS and if possible a video/gif, as the steps provided don't appear to replicate the issue.

Here's a quick gif showing case 3 working on Chrome:
![GH-5359](https://user-images.githubusercontent.com/1575550/72940369-843ca600-3dba-11ea-871b-71f4e2116aab.gif)

**Comment by felixmosh** [comment]
Weird thing, I've checked the dom node in dev tools, there it reproduces, but when I click on `show source` it works fine
