### ISSUE TITLE
Tab/Shift+Tab issue with lists

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#5362]
Tab/Shift+Tab indentation in list is a very handy feature. However, there is a case where it does not work as expected.

If you have an empty list item, pressing Tab does not indent the list item, as it does if it is before a line of text, but only inserts a tab character.

It should indent the list item even if it is empty.

**Comment by SimonFc** [comment]
It does? http://fiddle.tinymce.com/Xahaab (Note - you need the [lists](https://www.tiny.cloud/docs/plugins/lists/) plugin for this feature)

1. Place the cursor in the empty list item
2. Press tab once
3. Result: list item is indented

**Comment by petko** [comment]
Actually, it does. It was another thing in my code that was preventing it. Sorry for this one!
