### ISSUE TITLE
Editor doesn't show single breaking spaces in paragraph when preceded by a table with style float: left

### ISSUE THREAD

**Issue by PMartins-EDR** [tinymce/tinymce#5363]
See http://fiddle.tinymce.com/eahaab
A table with style float left is followed by a few paragraph tags with a single breaking space inside. These spaces do not appear in the editor. When the same html is viewed in a browser, the spaces do appear so it's inconsistent with what the editor is showing. Once the single breaking space is replaced with two breaking spaces it appears correctly.

**Comment by SimonFc** [comment]
I've simplified your fiddle quite a bit: http://fiddle.tinymce.com/eahaab/1
Do you expect to have `<p>&nbsp;</p><p>&nbsp;</p>` in the editor in the first example? This is actually intended to work like this as we regard `<p>&nbsp;</p>` as something empty

**Comment by PMartins-EDR** [comment]
@SimonFc Correct, we had cases where `<p>&nbsp;</p></p>&nbsp;</p>` was present when they were trying to put a space after a table, ie the html wasn't manually manipulated.
