### ISSUE TITLE
Autocompleter not trigger on mobile chrome

### ISSUE THREAD

**Issue by HFUBlackRabbit** [tinymce/tinymce#5365]
Hi there. Autocompleter not trigger on mobile devices. 
fix it plz.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinyMCE 5.1.5, Android 6, Chrome 79.0.3945.136

P.s. sry for my poor english? i tryed describe problem.

**Comment by lnewson** [comment]
This is a known issue mentioned in our [release notes](https://www.tiny.cloud/docs/release-notes/release-notes51/#autocompleterandkeypresseventissuesonandroid) and it's related to how Android input is done. It's virtual keyboard implementation inputs content in a somewhat weird and unusual way, that adds all input via an input method editor (IME) and doesn't complete the composition until a space (or similar) is entered (meaning the word is already completed). That's not something that is easy to work with while typing without cancelling the composition, so we plan on doing more investigation to see if there's a way we can get it to work, however we don't have a timeline for that at this stage.

**Comment by HFUBlackRabbit** [comment]
Oh. Sry, i dont read release notes so far. Any way try for response.

**Comment by mariojsnunes** [comment]
Hi, why is this closed if the issue is not fixed?
