### ISSUE TITLE
No way of having both tapping and clicking on a touch device?

### ISSUE THREAD

**Issue by mrcferri** [tinymce/tinymce#5367]
I'm using vers. 5.1.3 with Chrome on a tablet. Menus and toolbar buttons work perfectly when tapping, but they cannot be clicked on when using a mouse.

Is this the expected behavior? I'm not sure this is what is expected by an average user. I don't know  whether I'm an average user or not, but certainly I thought that something wasn't working right.

With same device, same browser, but vers. 5.0.11, menus and buttons work as they should, at least according to me: they respond to tapping and clicking.

Is it a bug or an improvement?

Thanks,

marco

**Comment by lnewson** [comment]
@mrcferri this was fixed in 5.1.5, with one exception being the context menu right click not working which has been fixed in 5.1.6.
