### ISSUE TITLE
Need (4.9.8) version in CustomBuild from website

### ISSUE THREAD

**Issue by Dineshkanin** [tinymce/tinymce#5373]
Hi, 

I'm trying to download the Customized tinyMCE build from "https://www.tiny.cloud/get-tiny/custom-builds/" but it 4.9.2 version which is a year old. Can you pls update it.

**Comment by lnewson** [comment]
Thanks for letting us know! We've updated the version of TinyMCE used, so that it's now using 4.9.8.
