### ISSUE TITLE
Enter creates an empty <p> 

### ISSUE THREAD

**Issue by JugheadStudio** [tinymce/tinymce#5374]
**What is the current behavior? Describe the bug**
I am getting this bug where when i press enter, then the editor creates `<p class="selected"><br data-mce-bogus="1"></p>`

But when i start typing the text still stays in the previous `<p>` tag

so it creates multiple "empty" `<p>` tags and i am stuck in the previous `<p>` tag

Ive also notices that each `<p>` tag has a class of `selected` untill you click somewhere else

**Please provide the steps to reproduce **
Init tinyMCE with `inline: true` then type inside a `<p>` tag

**What is the expected behavior?**
When enter is pressed, it should create a new `<p>` tag (which works),
then when I type it should type inside the new `<p>` tag

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
`"tinymce": "^5.1.6"`
Chrome/electron

P.s. when the inline is set to false, then it works perfectly but then i cant add stuff dynamically die to it being an iframe.

**Comment by ltrouton** [comment]
Just wanted to check that you are using TinyMCE within an electron app? If so, are you able to reproduce the issue when not using electron, for example, in a [fiddle](http://fiddle.tinymce.com/)?

Also, you make a note about not being able to add content dynamically to an iframe editor. Have you tried using the tinymce.dom [api](https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.selection/#setcontent)?

**Comment by Remy-Limelight** [comment]
Good day, 

Thanks for the respond, I am using it inside an electron app

i tried to replicate it in the fiddle, but it works there, I'm thinking its because it is also in an iframe

Here is a link to the [fiddle](http://fiddle.tinymce.com/Fahaab)

Here is my init code

`tinymce.init({
        selector: '#mailerBuild',
        plugins: 'quickbars link table code lists',
        menubar: false,
        toolbar: true,
        inline: true,
        resize: false,
        table_resize_bars: false,
        quickbars_selection_toolbar: 'bold italic link unlink removeformat',
        toolbar: 'undo redo | fontselect fontsizeselect | bold italic link unlink removeformat code | alignleft aligncenter alignright alignjustify bullist numlist | table',
        font_formats: "Arial=arial,helvetica,sans-serif; Courier New=courier new,courier,monospace; Calibri=Calibri, sans-serif; Roboto='Roboto', sans-serif;",
        fontsize_formats: '11px 12px 14px 16px 18px 24px 36px 48px'
    });`

**Comment by ltrouton** [comment]
Thanks for that. The config you have provided looks fine. Since the issue cannot be reproduced in a fiddle, it looks like it may be an issue with electronjs itself or how TinyMCE has been set up in electron. This is something we can't really provide support for.

You should be able to use the TinyMCE API to dynamically set the content of an iframe editor. For example, using these methods: [insertContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#insertcontent), [setContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#setcontent). Would that solve your problem instead?
