### ISSUE TITLE
Toolbar_drawer coming up even if space is available in the toolbar.

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#5375]
**Toolbar_drawer showing up even if there is space available in the editor toolbar.**

**This happens when we are loading tinymce inside an iframe.**

**It should utillize the space to show the tools.**

**The version which i am presently using is 5.0.16.**
 This is the unexpected behavior.
![image](https://user-images.githubusercontent.com/12448024/73529138-2b18e600-443c-11ea-9b2d-dd7534d96ff8.png)

This is the expected behaviour.
![image](https://user-images.githubusercontent.com/12448024/73529382-9e225c80-443c-11ea-93a3-e0350474a586.png)

**Comment by lostkeys** [comment]
Yes, this should not happen. Is it possible for you to update TinyMCE to a newer version and see if the problem persist?

**Comment by SIMRAN88** [comment]
Still happening in the new version. (5.1.6)

**Comment by lostkeys** [comment]
Can you somehow share your HTML and CSS related to this? It might be something tripping up the JavaScript that is checking the width of the editor. We are running TinyMCE in iframe a all the time without issues so it should work.

**Comment by glenfordwilliams** [comment]
i'm having a similar issue but i'm using an external toolbar 
`
"tinymce": "^5.1.6",
"@tinymce/tinymce-react": "^3.4",
`

![image](https://user-images.githubusercontent.com/1114368/73929966-c29a9080-48a3-11ea-974e-bed9ea54e531.png)

**Comment by lostkeys** [comment]
@glenfordwilliams By external toolbar, do you mean you are using `inline: true`? Note that the inline toolbar is as wide as the target element. Also it is _toolbar groups_ that gets pushed into the toolbar drawer (the pipe `|` characters separating toolbar buttons), so if you have a large amount of icons in one group, the whole group will get pushed to the toolbar drawer.

**Comment by Harrison-Lara** [comment]
We are having the same issue. Have tested with tinymce 5.1.6 and tinymce-react 3.4 Only rendering the "More" icon. We are using the toolbar inline.

**Comment by SimonFc** [comment]
@SIMRAN88 You say that the issue appears when you're loading TinyMCE inside an iframe? See if you (or anyone else here) can fork and modify this [codepen](https://codepen.io/SimonFc/pen/YzXzovX?editors=1010) in order to illustrate the issue. As of now we're unable to replicate it.

Thanks!

**Comment by chdeshpc** [comment]
@here, Does anyone have any solution to this problem? I tried removing the | (pipe) and I could see the buttons. But tox-toolbar-container class's width is very small. Hence, all the buttons are getting wrapped.

**Comment by lostkeys** [comment]
@chdeshpc, can you share your toolbar config?

**Comment by chdeshpc** [comment]
const config = {
  dateFormat: ['%H:%M:%S', '%Y-%m-%d', '%I:%M:%S %p', '%D'],
  fontSize: '11px 12px 14px 16px 18px 24px 36px 48px',
  toolbarStyles: '.tox-tinymce { right: 64px; width: 2000px; min-width: 1900px; }',
  contentStyle: './oxide/content.min.css',
  plugins: 'lists insertdatetime table searchreplace charmap code advlist link',
  height: 375,
  width: 700,
  min_wdith: 1900,
  inline: true,
  event_root: '#root',
  toolbar_drawer: 'floating',
  toolbar_sticky: true,
  toolbar:
    'undo redo | bold italic underline | fontselect fontsizeselect | forecolor backcolor | ' +
    'alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | superscript subscript' +
    '| link insertdatetime searchreplace charmap code',
  fontFamily:
    'Andale Mono=andale mono,times;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;' +
    'Book Antiqua=book antiqua,palatino;Comic Sans MS=comic sans ms,sans-serif; Courier New=courier new,courier;' +
    'Georgia=georgia, palatino; Helvetica=helvetica; Impact=impact, chicago; Open Sans= Open Sans;' +
    'Sans- Serif=sans-serif; Symbol = symbol; Tahoma = tahoma, arial, helvetica, sans - serif;' +
    'Terminal = terminal, monaco;Times New Roman = times new roman, times; Trebuchet MS = trebuchet ms,' +
    'geneva; Verdana = verdana, geneva;Webdings = webdings; Wingdings = wingdings, zapf dingbats'
};

**Comment by lostkeys** [comment]
@chdeshpc Hm, nothing out of the ordinary there. The toolbar "wraps" where the pipe characters are, so it moves the whole group down to the toolbar drawer. Do you experience the same issue as @SIMRAN88 where there is enough space to show icons but it still wraps? Can you perhaps post a screenshot? Btw you have a typo in the `min-width` option.

**Comment by chdeshpc** [comment]
![screenshot](https://user-images.githubusercontent.com/27822182/74020750-3c27a100-49c0-11ea-8f2d-ab25caa3aeec.png)
 This is what is happening when I remove groups pipe.

**Comment by chdeshpc** [comment]
![screenshot1](https://user-images.githubusercontent.com/27822182/74020892-8446c380-49c0-11ea-90ac-c7bb6bdbd3e6.png)
This is what happens by default.

**Comment by chdeshpc** [comment]
There is space. When I inspect and add this - <div class="tox-editor-container" style=" min-width: 1000px;"> it shows there is space but still the toolbar_drawer comes up.

**Comment by lostkeys** [comment]
@chdeshpc You seem to have a heavily customized skin. Can you perhaps try with the default skin to rule out any errors in your customization?

**Comment by chdeshpc** [comment]
We also have another version which does not have a custom theme. ANd it is working fine there. But I need some info as to where can I make any changes to get working within our theme. Because that is the releasable part. Non-theme is of no use for us.

**Comment by lostkeys** [comment]
@chdeshpc If it works fine with the default skin, it's likely an issue with the custom skin. Have you made it using the [officially supported way to create skins](https://www.tiny.cloud/docs/advanced/creating-a-skin/)?

**Comment by chdeshpc** [comment]
No. We used the default skin provided by tinymce-react. But when it was merger with our actual product's theme, it is creating some conflicts.

**Comment by lostkeys** [comment]
@chdeshpc, Ok it's really really hard for us to support that as we have no control of what's going on. It can be anything really. By the look of your screenshots, it's not the same issue the original poster describes, It's almost looks like your css hasn't loaded at all. Is your editor public? If not, there is not much we can do other than recommend you to recreate your product's look via the official "style-api".

**Comment by chdeshpc** [comment]
Can you provide some way I can manipulate the css classes? Is there any way? I know it is difficult. But even we are finding it very hard.

**Comment by lostkeys** [comment]
No we have no plans to support adding/modifying classes or overriding the css other than the means provided in the [documentation](https://www.tiny.cloud/docs/advanced/creating-a-skin/) as we would not be able to handle the support load that would come from that.

**Comment by SIMRAN88** [comment]
Hi There, Sorry for the late reply. I found the issue but I am not sure if that is the problem. On the time of loading the size of text-area is small , so at the time tinymce renders it takes up that size and no toolbar shows up expect the toolbar_drawer.I have also noticed that this is happening at the very first time if I launch and also in the Incognito mode. Once tinymce gets cached the toolbar comes properly. We are fixing this problem. Thanks

**Comment by SIMRAN88** [comment]
Hi There @lostkeys . Facing issues with the toolbar_drawer everytime I open the tinymce in my application it comes like this . Using tinymce version 5.2.1. 
![image](https://user-images.githubusercontent.com/12448024/85364868-bb69db80-b541-11ea-8fc5-789fc1e45608.png)
![image](https://user-images.githubusercontent.com/12448024/85364895-cd4b7e80-b541-11ea-9951-971418761303.png)
This is creating lot of issues in all the browsers. Once the tinymce width is altered it takes the exact space. On first time load this is happening always. Tried a lot but not able to get the root cause why this is happening. Please help regarding this.

**Comment by lostkeys** [comment]
Can you try to [replicate the same behavior in a fiddle](http://fiddle.tinymce.com), recreating the html and css around the editor causing this issue? Also check if the body has `display:flex`. That has issues.
