### ISSUE TITLE
Disable inserting an image that was not uploaded via img-upload-tab

### ISSUE THREAD

**Issue by lofcz** [tinymce/tinymce#5376]
**Is your feature request related to a problem? Please describe.**
It would be great to have an option to force images inserted into the editor to be uploaded via the upload tab. Why is this useful? Redactors are commonly used to uploading their images to some 3rd party sites and then pasting the direct link provided by that site. Any serious website probably want to disable this - once the original image hoster goes down, images are dead on your page too. 
**Describe the solution you'd like**
`images_force_upload` option to be added, of a bool type. You should be able to check whether an image's URL is from the local site, as it either: 
- is in format `/[Something/]imgName.suffix`, or
- is in format `[www].[http/https].[window.location.host][:port]/sameAsAbove`

**Describe alternatives you've considered**
Checking article after it is saved, regexing for src tag in images and if it contains url to 3rd party website, prompting an error. This is not that great tho, I'd very much like to directly force uploading.

**Comment by lofcz** [comment]
bump

**Comment by lofcz** [comment]
@lnewson @lostkeys could you folks please take this into consideration?

**Comment by lnewson** [comment]
@lofcz I've labelled it as a feature request so our PM team can evaluate this, but I'm afraid we can't give any time frame for when it might be investigated/implemented sorry.

**Comment by lofcz** [comment]
@lnewson guess I'm better off to create a simple image upload plugin implementing just the features I need. Thanks for the great API which makes this possible.
