### ISSUE TITLE
TinyMce does not display content on re-rendering

### ISSUE THREAD

**Issue by sukheja-varun** [tinymce/tinymce#5377]
Using TinyMce with Angular8
I am having multiple tinymce on a single page and we have the option to shuffle their position by moving them up/down. But when dom re-renders the tinyMce on dom it does not display the content but it displays the number of words.

Here is a fiddle replicating the issue
http://fiddle.tinymce.com/q3gaab

**Comment by SimonFc** [comment]
Whenever an iframe is moved within the DOM it re-renders (you wont have this issue in inline mode). As of now it's up to the user of TinyMCE to re-initialize TinyMCE whenever necessary.

A great summary of the issue is provided [here](https://stackoverflow.com/a/39895407)
