### ISSUE TITLE
Working without inline-styles / style-tags?

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5378]
Only a suggestion not really a wish, instead of use inline-style or style-tags, you can insert (or remove) it directly in CSSStyleSheet with https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule

**Comment by lnewson** [comment]
Thanks for the suggestion, however this wouldn't work when you try and get content out of the editor. That's the primary purpose of inline styles, as it makes the content portable and can then easily be embedded in sites.

Another issue with this, is it wouldn't be possible to style just a single word without putting in spans with dynamic classes (or similar), so it wouldn't end up much better off (with the exception it'd be easier to override styles). Also worth noting this suggestion still requires a `<style>` tag to exist to be able to insert the rules into, so it wouldn't avoid what you mentioned anyways.
