### ISSUE TITLE
Add loading="lazy" as an option in the image plugin

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#5379]
In Chrome 76 (Edge,Opera), you can use the loading attribute to completely defer the loading of offscreen images and iframes that can be reached by scrolling:

loading="lazy"

3 options

auto: Default lazy-loading behavior of the browser, which is the same as not including the attribute.
lazy: Defer loading of the resource until it reaches a calculated distance from the viewport.
eager: Load the resource immediately, regardless of where it's located on the page.

It would be nice if this can be added to the image plugin

**Comment by petko** [comment]
+1. This will make loading of large documents with many images much faster hopefully.

**Comment by shawnngtq** [comment]
👍 I think it will be useful. For now, I am storing that inside my html directly.

**Comment by eartahhj** [comment]
Well, yes, but you need to specify the attributes. If you want to add loading="lazy" you can set the extended_valid_elements like this:
`"extended_valid_elements":"img[loading=lazy]"`

In my example I added more attributes with their default, but you can go with whatever attributes suit your needs.

The result in TinyMCE is that from now on, by default, when you add an image it will have a the attribute "loading" set to "lazy".

To achieve the same on old images, you might probably do it faster on the database, otherwise you can do it manually on every image (remove the image in tinymce and add it again, for example by going with Cut and Paste or something like that).

If it does not work, check on your Tinymce configuration javascript code that you have not disabled some attributes.

**Comment by Sammah071** [comment]
@eartahhj  Thank you so much for a quick response to my issue. 
That's awesome for having it built-in with this lazy method and not having a third-party js.
I tested it with the Chrome Dev tool. It says 'Other' on the initiator column. Is that mean it's working?



> Well, yes, but you need to specify the attributes. If you want to add loading="lazy" you can set the extended_valid_elements like this: `"extended_valid_elements":"img[loading=lazy]"`
> 
> In my example I added more attributes with their default, but you can go with whatever attributes suit your needs.
> 
> The result in TinyMCE is that from now on, by default, when you add an image it will have a the attribute "loading" set to "lazy".
> 
> To achieve the same on old images, you might probably do it faster on the database, otherwise you can do it manually on every image (remove the image in tinymce and add it again, for example by going with Cut and Paste or something like that).
> 
> If it does not work, check on your Tinymce configuration javascript code that you have not disabled some attributes.

**Comment by eartahhj** [comment]
To see if it works, you should check if in the front-end (public website that all users can see) the IMG tag in the HTML has the loading="lazy" attribute.

**Comment by Sammah071** [comment]
I saw the image on the front-end and the source code. 
<img class="img-fluid" src="../../../images/background.jpg" alt="" width="3456" height="5184" loading="lazy" />

 Is this right?
Unlike the third-party tool, Tiny didn't use the data-src or data-original part.
 
> To see if it works, you should check if in the front-end (public website that all users can see) the IMG tag in the HTML has the loading="lazy" attribute.

**Comment by eartahhj** [comment]
The loading="lazy" is present, it seems correct to me.
I don't know what third party tool you are talking about, but if you need to add a default data-src attribute, you can add it in the previous javascript code:
`"extended_valid_elements":"img[loading=lazy|data-src=your-default]"`

or something like that

**Comment by Sammah071** [comment]
No, this removed the src attribute from the image tag which ends up with something like this:

< img loading="lazy" data-src="your-default" />
Do you have any other ideas?

**Comment by eartahhj** [comment]
Inside "extended_valid_elements" you should add all the attributes you want the user to be able to insert inside TinyMCE.
The example is the same I used in my original comment:
`"extended_valid_elements":"img[class=image|src|alt=|title|width=|height=|loading=lazy]"`
This will give you the following img tag by default
`<img class="image" alt="" width="" height="" />`
and you will be able to add the SRC and TITLE attributes also.
Please read the documentation: https://www.tiny.cloud/docs/configure/content-filtering/#extended_valid_elements
> When adding a new attribute by specifying an existing element rule (e.g. img), the entire rule for that element is over-ridden so be sure to include all valid attributes not just the one you wish to add. See [valid_elements](https://www.tiny.cloud/docs/configure/content-filtering/#valid_elements) for default rules.

I think this is not the right place where to discuss this, anyway it's kinda easy to do, if you read the docs and try it out a little bit.

**Comment by Sammah071** [comment]
@eartahhj Thanks. I will try this out tomorrow.
