### ISSUE TITLE
Background color added and border radius removed from button when text font size is increased greater than default.

### ISSUE THREAD

**Issue by DGWIII** [tinymce/tinymce#5383]
**What is the current behavior? Describe the bug**
Background color added and border radius removed from button when text font size is increased greater than default.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Steps to Reproduce:

1. enter source code view
2. add a button element with some text:
`<button>text</button>`
3. add inline styling to increase font-size > 10pt to text:
`<button><span style="font-size: 12pt;">text</span></button>`
4. notice button

Result:
Border radius is removed and background color is changed.

Desired Result:
No additional styling is added

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Present in version 5

**Comment by lostkeys** [comment]
This is not an issue with TinyMCE. The browser removes much of the default styling as soon as you declare your own. [See this CSS-Tricks blogpost for more details](https://css-tricks.com/overriding-default-button-styles/).
