### ISSUE TITLE
start-attribute on <ol> is duplicated into sub <ol> after increasing indenting

### ISSUE THREAD

**Issue by ppdeblieck** [tinymce/tinymce#5387]
See: http://fiddle.tinymce.com/Wahaab

When a list-item in an ordered list with a start attrubute is indented the start-attribute is copied into the newly created sub list resulting in a sub-list starting with a high number.

Html inside editor:
```
<ol start="5">
    <li>Item A</li>
    <li>Item B</li>
    <li>Item C</li>
    <li>Item D</li>
    <li>Item E</li>
</ol>
```
Result when pressing "Increase indent" on Item B:
```
<ol start="5">
    <li>Item A
        <ol start="5">
            <li>Item B</li>
        </ol>
    </li>
    <li>Item B</li>
    <li>Item C</li>
</ol>
```
The expected result is that the new sub-list doesn't have a start attribute:
```
<ol start="5">
    <li>Item A
        <ol>
            <li>Item B</li>
        </ol>
    </li>
    <li>Item B</li>
    <li>Item C</li>
</ol>
```
This issue is present in every version of TinyMCE.

**Comment by lostkeys** [comment]
We don't really support start items on lists yet so this isn't something we have taken care of (yet). I'll log this as a feature request.
