### ISSUE TITLE
insertContent removes complete table consisting of one cell

### ISSUE THREAD

**Issue by ppdeblieck** [tinymce/tinymce#5388]
See: http://fiddle.tinymce.com/Yahaab/1

When there is a table containing one cell and you execute editor.insertContent() on all the td contents the whole table is removed.

The example uses a very skeleton toolbar button from the example https://www.tiny.cloud/docs/ui-components/toolbarbuttons/

This behaviour is the same when selecting all the text in a strong-tag. Expected behaviour is that the inserted text is in the strong tag. The result however shows the whole <strong> tag is removed.

This issue is present in every version of TinyMCE.

**Comment by ltrouton** [comment]
I would like to know more about your intended use case for choosing `insertContent()` to help me investigate further. In the mean time, have you tried using `editor.selection.setContent('New content')` instead? It appears to resolve the issues you have noted.

**Comment by ppdeblieck** [comment]
We use this case in an own plugin that adds a tooltip (span with title-attribute) to any selection of text.
When you select text that is italic or bold you want the selected text to remain bold/italic after adding the tooltip.

The usage was:
```
editor.insertContent(editor.dom.createHTML('span', {
    'class': 'content-footnote',
    'title': dataTitle
}, editor.dom.decode(selectedText)));
```

Based on your suggestion I just altered it to
```
editor.selection.setContent(editor.dom.createHTML('span', {
    'class': 'content-footnote',
    'title': dataTitle
}, editor.dom.decode(selectedText)));
```
Now it does exactly what we intent to do.

Thanks!

**Comment by lnewson** [comment]
I'm going to close this as it sounds like this has been resolved but if it hasn't then let us know and we'll reopen this issue. I'd also reiterate what @ltrouton said in though, that `editor.selection.setContent()` is the API that should be used for this use case.
