### ISSUE TITLE
Table Plugin: problem when calculating width of merged cells

### ISSUE THREAD

**Issue by vincenzo-mennella** [tinymce/tinymce#5389]
**What is the current behavior? Describe the bug**
When you create a table (let's say a 4x2 one) every cell gets a width of 25% (that's right!).
Don't touch anything and merge two cells: the cell with attribute `colspan=2` should get a width of 50%, but this does not happen (it stays at 25% width and this is wrong). 
After this, if you drag a column in order to make it bigger/smaller, the width gets re-calculated right.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Create a 4x2 table and don't touch the width of the columns (let them stay at 25% each)
2. Merge two cells

**What is the expected behavior?**
The merged cell should get a 50% width (25+25)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest version (you can check it on your [online demo](https://www.tiny.cloud/docs/demo/full-featured/))

Thank you!

**Comment by vincenzo-mennella** [comment]
Still present in 5.2. Do you have any news about this issue?

**Comment by danoaky-tiny** [comment]
This is now fixed, Tested on 6.8
