### ISSUE TITLE
Not working inline edit within table.  

### ISSUE THREAD

**Issue by jigneshInd** [tinymce/tinymce#5390]
**What is the current behavior? Describe the bug**
When using inline edit with div or heading elements, its wors perfectly but when we use that heading or div elements withing table elements, it's not working. 

**What is the expected behavior?**
Elements inside table > td elements should be able to do inline edit.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE version : 4.5.7

**Comment by lnewson** [comment]
TinyMCE 4.5.x is no longer a supported version. Please try with the latest version and if you can reproduce using 4.9.x or 5.1.x then please let us know and we'll re-open this issue.
