### ISSUE TITLE
Closebutton: false does not work

### ISSUE THREAD

**Issue by xunni1000** [tinymce/tinymce#5391]
Closebutton: false does not work

tinymce version  5.1.6

html

`<textarea id="tinydemo" >abc</textarea>`

js
```
<script>
tinymce.init({
	selector: '#tinydemo',
	theme: 'silver',
	plugins:['bbcode ,code'],
	//toolbar:false,
	toolbar: 'undo redo | bold italic underline | code',
	menubar:false,

	elementpath: false,
	resize: false,
	statusbar: false,
	entity_encoding : "raw", 
	remove_linebreaks : false, 
	forced_root_block: false, 
	force_br_newlines: true, 
	invalid_elements : "p, div, span", 
	force_p_newlines: false,   
	init_instance_callback : function(editor){
		editor.notificationManager.open({
			text: 'test test.',
			type: 'warning',
			//timeout: 5000,
			closeButton: false,
		});
	}
});

</script>
```

**Comment by lnewson** [comment]
Thanks for letting us know about this! It looks like something that was missed in the 4.x -> 5.x UI conversion, but I'll double check with the team to see if it was intention or just something that was missed.

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue. Please let us know if you have any further issues.
