### ISSUE TITLE
Is there anyway to apply toolbar event apply only to the root node of the selection

### ISSUE THREAD

**Issue by fs-td-eitaro-ueda** [tinymce/tinymce#5392]
**Is your feature request related to a problem? Please describe.**

Hi, I am using tinymce-rails (4.6.7). I know this is not really appropriate to write it here, but I thought the thing I want might be possible in tinymce in general.
I posted pretty much the same thing [here](https://github.com/spohlenz/tinymce-rails/issues/267).

I was wondering if the tinymce toolbar to only act on the root node of the selected element (highlighted by cursor).

Original selected elements:

```html
<div>
    <table>
        <tbody>
            <tr>
                <td>
                    <div>some text here</div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

Tinymce by default when used "bold" button on the toolbar:

```html
<div>
    <table>
        <tbody>
            <tr>
                <td>
                    <strong>
                        <div>some text here</div>
                    </strong>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

**Describe the solution you'd like**

Instead, I want it to be like below where the style is applied to the top element:

```html
<div font-weight="bold">
    <table>
        <tbody>
            <tr>
                <td>
                    <div>some text here</div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

Please let me know if anyone knows a solution to this.

**Describe alternatives you've considered**

Nothing, for now.

**Comment by lnewson** [comment]
I was able to update the formats in a way to achieve this, however it's really not the intended purpose  as it's meant to apply formats to the current selection or block. So something like this really goes against the design/intention and prevents users making just a small part of the content bold, etc.... However, with that disclaimer out the way if you do want to go ahead with that here's a potential solution: http://fiddle.tinymce.com/8hhaab

The best suggestion I can come up outside of that, if it doesn't meet your needs, with would be to hook into the `BeforeExecCommand` event and implement your own variant of the formatter. So something like this: http://fiddle.tinymce.com/9hhaab This however doesn't allow the formatter to know that an element is bold and as such won't show the bold toolbar button as active.
