### ISSUE TITLE
Can't change between fonts where first specified font in font-family is duplicated

### ISSUE THREAD

**Issue by jsteele883** [tinymce/tinymce#5393]
**What is the current behavior? Describe the bug**

In `font_formats` I set `Chinese Arial=Arial,宋体,SimSun,华文仿宋,STFangsong,sans-serif;Korean Arial=Arial,돋움,Dotum,굴림,Gulim,sans-serif;` When I change the text I can't change between these two options in the tinyMCE UI. It stays at Chinese Arial. This is seems to be the case for any font-family when the first specified font is duplicated.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/gbhaab/1

**What is the expected behavior?**

Selected font should change and show correctly in the editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Seen in TinyMCE 4 and 5 across all browsers.

**Comment by lnewson** [comment]
This is expected, as in most cases they are going to be identical as `Arial` is the font that will be used by the browser. I'd suggest making it a fallback much latter in the font list which will get this working as expected. eg: `Chinese Arial=宋体,SimSun,华文仿宋,STFangsong,Arial,sans-serif;Korean Arial=돋움,Dotum,굴림,Gulim,Arial,sans-serif;`
