### ISSUE TITLE
tinyMCE and CSS popup

### ISSUE THREAD

**Issue by Apskaita5** [tinymce/tinymce#5394]
I use tinyMCE v. 5.1.2 and pure CSS popup (https://codepen.io/imprakash/pen/GgNMXO) for field help information (display info sign next to the field label that triggers the popup). When the popup is shown it is (partly) covered by the tinyMCE control. Setting z index wouldn't help.
How to make the popup to be displayed over tinyMCE control?

OS: win7 pro sp1
Browser: Opera v. 66.0.3515.72

Example (razor pages):

`<div class="form-group">
                <label asp-for="Template.ClaimTemplateBody" class="control-label"></label>
                <a class="button" href="#ClaimTemplateBody_Help"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></a>
                <div id="ClaimTemplateBody_Help" class="overlay">
                    <div class="popup">
                        <a class="close" href="#">&times;</a>
                        <div class="content help-block">
                            Use the following placeholders:<br />
                            @(Models.Constants.PlaceHolder_CourtName) - court name;<br />
                            @(Models.Constants.PlaceHolder_HouseName) - court house name;<br />
                            @(Models.Constants.PlaceHolder_InterestRate) - applicable interest rate.
                        </div>
                    </div>
                </div>
                <textarea asp-for="Template.ClaimTemplateBody" class="form-control" aria-describedby="ClaimTemplateBody_Help"></textarea>
                <span asp-validation-for="Template.ClaimTemplateBody" class="text-danger"></span>
            </div>`

**Comment by lnewson** [comment]
The codepen you've provided doesn't use TinyMCE, so we can't really help much without a way to replicate the issue. However using a z-index higher than 2000 should resolve your issues, as TinyMCE currently uses a z-index in the 1000-2000 range. If that doesn't work, then please provide a way to replicate the issue.

**Comment by Apskaita5** [comment]
Thank you.  z-index 3000 worked fine. Just needed to add it to both overlay and popup classes.
