### ISSUE TITLE
Can't build tinymce 4.x because of non flat package

### ISSUE THREAD

**Issue by NeOMakinG** [tinymce/tinymce#5397]
**What is the current behavior? Describe the bug**
![image](https://user-images.githubusercontent.com/14963751/74358673-26501c80-4dc2-11ea-9224-01feb2d2bb2d.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Clone the repo, checkout 4.x branch, npm install and run "grunt"

**What is the expected behavior?**

Building tinymce as the README says

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Current fix found :**

modifying postinstall script to 

`rimraf node_modules/@ephox/alloy/node_modules && rimraf node_modules/@ephox/sugar/node_modules && rimraf node_modules/@ephox/sand/node_modules`

**Comment by lnewson** [comment]
I checked with a clean install and this doesn't occur, nor is it happening with our nightly builds. As such it's likely a bad install, or items left over from a previous install on your system, so try cleaning your node_modules and see if the issue persists. Also make sure you're using `yarn` to install/build as that's all we currently support.

If you're still having issues after that, let us know and we'll reopen this. I'd also be helpful if you can include details on how to reproduce the issue.
