### ISSUE TITLE
Issue with "language" and more as one tinymce on page

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5402]
Maybe thats have impacts on other settings, so I'm reporting it. See http://fiddle.tinymce.com/4bhaab

Here I use two editors. You can see both in language "english", but the first is initialized in "german". The second tinymce.init() overwrites the language of the first editor.

Comment out second tinymce.init() and you will see first editor in german. See http://fiddle.tinymce.com/5bhaab

**Comment by wonderbugtiny** [comment]
Hi @Daijobou, we currently do not support initialising multiple instances of TinyMCE in different languages. The language property of the last editor that is loaded will be set as the language for all TinyMCE instances on the page. Please let us know what your use case is for having multiple editors with different languages on the same page, as usually the UI is only in one language. Thank you!
