### ISSUE TITLE
Empty address field on link edit on image

### ISSUE THREAD

**Issue by bes-internal** [tinymce/tinymce#5403]
Can't empty address field on link edit if link placed on image. But all works if link on text.

timymce Version 5.1.6, 5.2.0

delete link from image:
http://fiddle.tinymce.com/Bbhaab

**Comment by ionescho** [comment]
any progress on this? Am also having issues raised exactly with this

**Comment by lnewson** [comment]
TinyMCE 5.4.2 has just been released to the community, which includes a fix for this issue. Please let us know if you continue to experience any further issues.
