### ISSUE TITLE
alert popup closes underlying window on 'keydown' ok button of alert

### ISSUE THREAD

**Issue by DNWEIJ** [tinymce/tinymce#5405]
using https://www.tiny.cloud/docs/demo/full-featured/  (latest version of tinyMCE5 I gues)

Open the search and replace dialog.  (Edit -> `find and replace...`)
Type search text: asdasdasdadasd
This will result in a popup: `could not find the specified string`  and an `ok` button

The error/problem:
Press down the ok button with the mouse button and hold (DO NOT RELEASE). 
problem/bug -> The underlying 'find and search' window is removed.
move the cursor away from the alert box. Release the mouse button. 
 
Problem/bug:
The actual window  is removed on keydown of the alert box. This doesn't make sense, I would expect that the alert button would be removed on click and the window would still be there, to continue searching.

**Comment by lnewson** [comment]
Thanks @DNWEIJ For the report! I can confirm this is a known issue we're aware of and have been tracking internally, however we don't currently have a timeframe for when it'll be scheduled. We'll let you know when more information is available.

**Comment by lnewson** [comment]
Hi, 

This has been fixed in TinyMCE 5.2.1 which was released at the end of March. Sorry we missed updating this when it was released. If you continue to experience any issues please let us know.

Thanks!
