### ISSUE TITLE
Summary / Details element support

### ISSUE THREAD

**Issue by crazytonyi** [tinymce/tinymce#5410]
It doesn't look like tinymce has any plugins or core controls for adding a `<details>` element (allowing easy to expand/collapse content). It isn't fully supported in some browsers, but it is mostly implemented in latest versions of most browsers:

https://caniuse.com/#feat=details
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by ericmorand** [comment]
It's even worse than that: provide a custom template with a <details> tag and you'll face this thing:

https://github.com/tinymce/tinymce/blob/59748a11303fb7cf00fdb8c9392dcb082ee9d965/modules/tinymce/src/core/main/ts/selection/DetailsElement.ts

For some reason, it is not possible to open/close a details element when in the editor. Why is beyond me.

**Comment by narduin** [comment]
Now that it has 97% support it would be even more relevant to add this natively!

**Comment by WongJuk** [comment]
> 更糟糕的是：提供带有**详细信息**标签的自定义模板，您将面临这样的事情：
> 
> https://github.com/tinymce/tinymce/blob/59748a11303fb7cf00fdb8c9392dcb082ee9d965/modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
> 
> 出于某种原因，在编辑器中无法打开/关闭详细信息元素。为什么超越我。

This may require clicking to edit？

**Comment by narduin** [comment]
This could still be a great addition.

**Comment by lostkeys** [comment]
Hi all, 
Summary/Details was implemented last year as the [accordion plugin](https://www.tiny.cloud/docs/tinymce/latest/accordion/)

— Fredrik, Product Manager
