### ISSUE TITLE
Support setting of default text highlight color

### ISSUE THREAD

**Issue by krishna-babu** [tinymce/tinymce#5411]
**Is your feature request related to a problem? Please describe.**
Current default highlight color is black. When used the content becomes invisible as default text color would normally be black.

Currently there is no setting or api available to modify it. 

**Describe the solution you'd like**
Default highlight color should be light yellow
![image](https://user-images.githubusercontent.com/12712808/74889270-4b4e0d80-5335-11ea-8302-365879dad53f.png)

**Describe alternatives you've considered**

**Comment by lostkeys** [comment]
Hi! You're using a custom color palette, and you can define the order yourself. Just put the yellow color at the top in your config. Please feel free to repoen this ticket if I misunderstood you or if you have additional questions.

**Comment by krishna-babu** [comment]
Hi - Adding color to the top of list doesn't actually set it as default. It's currently showing it at the top of palette. Also it affects forecolor palette

Codepen [link](https://codepen.io/Krish13/pen/GRJmLPE) for your reference.

Video describing the behavior:
[TinyMCE Default Highlight Color.zip](https://github.com/tinymce/tinymce/files/4269295/TinyMCE.Default.Highlight.Color.zip)

What I'm looking for is a default backcolor option, when provided in the config its going to be single step for users to highlight text.

Let me know if I'm missing any detail here.

Thanks
Krishna

**Comment by krishna-babu** [comment]
@lostkeys - Any update on this?

Thanks
Krishna

**Comment by lostkeys** [comment]
Ah, I see what you mean. I agree it should be possible. I'll log a feature request but I don't have any dates for when this can be implemented.

**Comment by samarai-jk** [comment]
Any update here? Thanks!

**Comment by samarai-jk** [comment]
I've added a PR #7736 that would change the default color to yellow-ish but it needs to be reviewed by authorized users

**Comment by Apezdr** [comment]
Did we figure out the command to do this? I see samarai went MIA.

**Comment by samarai-jk** [comment]
Sorry guys, I wasn't able to create the PR as there was something wrong with my Github account and then we moved away from TinyMce as we ended up needing a more low-level editor. Anyways, the change is really trivial, see [here](https://github.com/tinymce/tinymce/pull/7736/files)

**Comment by TheSpyder** [comment]
That's ok. When you didn't follow up we decided to create a more complete implementation in TinyMCE 6.3. We have options for the default foreground and background color:
https://www.tiny.cloud/docs/tinymce/6/6.3-release-notes/#new-color_default_foreground-and-color_default_background-options-to-set-the-initial-default-color-for-the-forecolor-and-backcolor-toolbar-buttons-and-menu-items

We also added configuration to change which colors are in the picker:
https://www.tiny.cloud/docs/tinymce/6/6.3-release-notes/#new-color_map_foreground-and-color_map_background-options-store-custom-colors-selected-using-the-text-color-and-background-color-menus

**Comment by zannix** [comment]
There's one more issue now, when you're using default background color for example, but a different internationalization (language pack), the color is translated fine, but "Background color" is hardcoded
