### ISSUE TITLE
File picker at quickimage button of quickbars plugin does not filter for images

### ISSUE THREAD

**Issue by tim-boerner** [tinymce/tinymce#5415]
**What is the current behavior? Describe the bug**
The button quickimage, provieded by the quickbars plugin, opens the file select. In there the user can pick any file, also non images files.

**steps to reproduce**
HTML:
`<textarea id="default">Hello, World!</textarea>`
JS:
`tinymce.init({
  selector: 'textarea#default',
  plugins : 'quickbars image',
  quickbars_insert_toolbar: 'quickimage',
});`

**What is the expected behavior?**
The user should only be able to select image files at the quickimage button

**Which versions of TinyMCE, and which browser / OS are affected by this issue?**
TinyMCE 5.2.0
Chrome 79.0.3945.130

**Comment by lnewson** [comment]
Thanks for the report @tim-boerner! I can confirm this is a bug, so I've logged an internal task for us to get this fixed.
