### ISSUE TITLE
Firefox issue with selection being null

### ISSUE THREAD

**Issue by Andy-QT** [tinymce/tinymce#5416]
**Firefox 72.0.2 shows JS error**

![image](https://user-images.githubusercontent.com/2870154/74943985-90d20f80-53f5-11ea-9ae0-6c2de80f9139.png)

A previous fix can be found here: 
https://github.com/tinymce/tinymce/commit/7b10860a76a07db43ad0677bee4b2db64dbddef0 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Problem
-----------
Browser : Firefox 72.0.2
TinyMCE 5.0.2

Working
-----------
Browser : Firefox 72.0.2
TinyMCE 5.1.6

**Comment by lnewson** [comment]
@Andy-QT can you please include a way to replicate the issue? as I tested using Firefox 73.0.1, as I'd already upgraded, and can't reproduce the issue.

The stack trace also really doesn't make a whole lot of sense, as the exception is different to the commit you mentioned as it's not the native selection that's undefined and instead is the actual editor selection object that's undefined. However that shouldn't be possible without some sort of outside interference. One possibility is that the editor is being removed before it's finished initialising, as removing the editor will do `editor.selection = null;`. However if that's the case, then I'd be curious as to the use case for immediately starting to initialise the editor and then destroying it before it's finished.

**Comment by Andy-QT** [comment]
Thank you for the explanation, 

The error was to rerender the DOM element for the editor instance a second time before the first initialise was finished.
