### ISSUE TITLE
French language pack

### ISSUE THREAD

**Issue by LittleBigFox** [tinymce/tinymce#5429]
**Is your feature request related to a problem? Please describe.**
The french language pack in Localization is called "fr-FR".

**Describe the solution you'd like**
This language pack should be "fr", according ietf BCP-47, web standards, and others packs of tinymce.
https://www.ietf.org/rfc/bcp/bcp47.txt

**Describe alternatives you've considered**
There none, it's not a bug, just a standard.

**Comment by claudep** [comment]
I strongly support this request. French users from different countries (Switzerland (fr-CH), Belgium (fr-BE), Canada (fr-CA), etc.) might miss French translations because of this.

**Comment by c4ntin** [comment]
The bug still present or evolve... If you define "fr_FR" ou "fr", tinymce try to retrieve "https://cdn.tiny.cloud/1/xxxxxxxx/tinymce/5.6.2-104/langs/fr.js" but only the file existe fr_FR.js exists.
