### ISSUE TITLE
Table picker is broken when zoom out

### ISSUE THREAD

**Issue by zzs1020** [tinymce/tinymce#5430]
**What is the current behavior? Describe the bug**
Open table picker plugin and try to create a table, you'll see the picker is not functioning.
![image](https://user-images.githubusercontent.com/23032993/75289048-77f99d80-57eb-11ea-8b90-6023cd76830d.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Only happens on **Firefox**, (I tested on version 51 and 72), zoom out to 90% or lower. then go to https://www.tiny.cloud/docs/demo/full-featured/ click table and then starting pick table
![image](https://user-images.githubusercontent.com/23032993/75289470-65339880-57ec-11ea-9f16-5d36a0c931a1.png)

**What is the expected behavior?**
Should not broken.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested on 5.1.0 and current cloud version on your website.

**Comment by SimonFc** [comment]
I think it's this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=417278 http://fiddle.tinymce.com/3chaab/1
Perhaps it could be possible for us to work around this issue.
