### ISSUE TITLE
PHP Laravel

### ISSUE THREAD

**Issue by patil-stack** [tinymce/tinymce#5431]
Please give support on Laravel Framework

**Comment by lostkeys** [comment]
What do you mean by support? I've used TinyMCE myself in several Laravel projects

**Comment by patil-stack** [comment]
I implemented in my Larvael Project.
but there is issue i found, if i copy table from another excel sheet
including cell colors, border styles etc, then paste it into editor then it
not paste proper table colors and styles.

*Regards*





Vikram Patil- CRM developer



[image: Enjay-New-Logo-Full.png]

Phone: +919552812109| Email: vikram.p@enjayworld.com | WhatsApp: +91
9552812109

 [image:
https://www.linkedin.com/in/dhaval-patel-8ba9504a?trk=nav_responsive_tab_profile]
<https://in.linkedin.com/company/enjay-it-solutions-ltd->
<https://www.youtube.com/user/enjaynetwork>

**Comment by lostkeys** [comment]
Ok. That is not an issue with Laravel though. To be able to paste form (the desktop version) of Excel and retain formatting you need to have the [Powerpaste premium plugin](https://apps.tiny.cloud/products/powerpaste/). Please feel free to reopen this issue if you have additional questions.
