### ISSUE TITLE
Bullets still getting added in read only mode.

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#5438]
**In the read mode for tinyMCE the bullets are disabled but if you click them it adds the bullet**

**http://fiddle.tinymce.com/ 
Just add the config  readonly:1**

**The bullets should not be enabled for adding as all the buttons are disabled**

![tinymce_fiddle_readOnly](https://user-images.githubusercontent.com/12448024/75416725-20774100-5955-11ea-8e5d-996e1ba288c5.PNG)

**Comment by lostkeys** [comment]
No that should not happen. Thanks for reporting this!

**Comment by lnewson** [comment]
This has been fixed in TinyMCE 5.3.0, which was released to the community earlier today. Thanks again for reporting this and please let us know if you have any further issues.
