### ISSUE TITLE
Table Plugin: problem when calculating width of cells after editing inside the "Cell Properties" popup

### ISSUE THREAD

**Issue by vincenzo-mennella** [tinymce/tinymce#5439]
**What is the current behavior? Describe the bug**
When you edit a cell's width using the field inside the "Cell Properties" popup, the width gets applied only to the edited td and not to the others td inside the other rows.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Create a 4x2 table and don't touch the width of the columns (let them stay at 25% each)
2. Go to the "cell's properties" popup and set a cell width.
3. Save

**What is the expected behavior?**
The new width should be applied to all the cells in the same column, otherwise you'll have a column with cells of different width. The problem does not happen whe you resize columns by dragging the cells (without using the "cell properties" popup).
 
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest version 5.2  (you can check it on your [online demo](https://www.tiny.cloud/docs/demo/full-featured/))

I don't know if it could be related to #5389

**Comment by lostkeys** [comment]
That is intended in the current implementation as you're specifically editing that particular cell. To change all cells in the column, you need to select all cells in the column. But you're right, there is rarely any usecase for a single cell to be wider than all the others. We're looking at improving the table plugin but I don't have any dates for you yet.

**Comment by vincenzo-mennella** [comment]
Hi @lostkeys and thank you for your reply! 
If you have any workaround or suggestion to solve this behaviour (while waiting for you to improve the plugin) I'd be very happy to get them from you since they could solve lots of problems into my implementation of the plugin!

Thank you!

**Comment by vincenzo-mennella** [comment]
Hello! Any news about this?

**Comment by lostkeys** [comment]
Hi @vincenzo-mennella and sorry for the late reply. Can you provide some more details into the problems you are facing? Since we consider the current behavior to be correct, ie the cell dialog affects only the cell and not the column, any arguments why you think the current approach is wrong would help a lot.

**Comment by vincenzo-mennella** [comment]
Hi @lostkeys!
I can confirm that the problem I described in my first comment is still there and you can replicate it using your online demo and following the steps I provided.

I don't think the current behavior is correct. As you can see the whole column _visually_ changes it's width after you cange the width of single cell (taking the the higher width value from the column's cells), so it would be correct to update the `width` attribute of the other cells accordingly.

Even if all the modern browsers can adapt the column to match the width of the higher-width cell, I don't think that having an HTML like this is correct (also note that the sum of the widths in the first row exceeds 100%)

```html
<table style="border-collapse: collapse; width: 100%;" border="1">
    <tbody>
        <tr>
            <td style="width: 50.0329%;" data-mce-style="width: 50.0329%;"><br></td>
            <td style="width: 23.0329%;"><br></td>
            <td style="width: 23.0329%;"><br></td>
            <td style="width: 23.1707%;"><br></td>
        </tr>
        <tr>
            <td style="width: 23.0329%;"><br></td>
            <td style="width: 23.0329%;"><br></td>
            <td style="width: 23.0329%;"><br></td>
            <td style="width: 23.1707%;"><br data-mce-bogus="1"></td>
        </tr>
    </tbody>
</table>
```

In my case I have to parse the tables'HTML and check that attribute in order to create from scratch a custom table in a PDF (row-by-row) and, having a different width for every `td`, means that every row has a different cells widths. 

Let me know if you need further information!

Thank you!

**Comment by lostkeys** [comment]
@vincenzo-mennella Sorry I see what you mean now. Yeah, that HTML looks really ugly. We'll try to address this in a future update.

**Comment by vincenzo-mennella** [comment]
Thank you!
