### ISSUE TITLE
Uunnecessary scroll occured after pasting emoji from toolbar 

### ISSUE THREAD

**Issue by Gfirey** [tinymce/tinymce#5443]
**What is the current behavior? Describe the bug**
After pasting emoji from toolbar inside huge textblock unnecessary scroll occured

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://www.tiny.cloud/docs/demo/full-featured/
1. paste a lot of text
2. place cursor in middle of view
3. select emoji from toolbar
4. scroll to bottom of view occured after emoji placed

**What is the expected behavior?**
emoji placed in middle of view without scroll

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.1.6+, chrome 80, win10
my plugins: powerpaste, lists, codesample, noneditable, media

**Comment by SimonFc** [comment]
What do you mean by "pasting emoji from toolbar" and "select emoji from toolbar"? I'm guessing that you're using the emoticons plugin but forgot to include it in your "my plugins" list?

**Comment by Gfirey** [comment]
> What do you mean by "pasting emoji from toolbar" and "select emoji from toolbar"? I'm guessing that you're using the emoticons plugin but forgot to mention it in your "my plugins" list?

You're right, i mean this button
![image](https://user-images.githubusercontent.com/3421670/75562278-5d2c6080-5a59-11ea-81da-b2fc8a3cec67.png)

With some research i think problems starts here:
![image](https://user-images.githubusercontent.com/3421670/75562324-72a18a80-5a59-11ea-8204-5896a5a9132b.png)

**Comment by lnewson** [comment]
@Gfirey can you reproduce this in TinyMCE 5.2.0? As there was a scroll into view issue very similar to this that we fixed.

**Comment by lnewson** [comment]
I was still able to reproduce this in 5.2.0 using http://fiddle.tinymce.com/Pchaab/1, so I'll log an internal task for us to investigate more.

**Comment by TheSpyder** [comment]
Looks this is fixed in TinyMCE 6, I can no longer reproduce it
