### ISSUE TITLE
'Link' Plugin: Unable to unlink by single word

### ISSUE THREAD

**Issue by caoshaoyu** [tinymce/tinymce#5446]
Hello, Many thanks to your hard work!

There's a problem with 'Link' Plugin:
It is unable to unlink by single word.

Sometimes I wish to add number follow the word being linked, such as ABC to ABC3, but only wish ABC to be linked. The 3 will be linked automaticlly, and there's no way unlink it separately.

Really appreciate your help.
Best regards

**Comment by lostkeys** [comment]
I'm able to put the selector just after the linked ABC and add a number without the number becoming part of the link. If you want to remove some characters from a link, the easiest way is to use the link dialog and edit the "text to display" field. I hope this solves your issue. If I misunderstood something, please feel free to reply and reopen this issue.

**Comment by lnewson** [comment]
It's also worth noting you can use the `unlink` toolbar button to remove part of a link. So in this case, you can highlight "3" and press the unlink button to remove the link. However as @lostkeys mentioned, pressing the left/right arrow keys will allow you to either type inside or outside the anchor element.
