### ISSUE TITLE
set image selection

### ISSUE THREAD

**Issue by jazzwsr** [tinymce/tinymce#5450]
behavior: 
can't set img selection style

steps: 
Ctrl+A or Cmd+A can't set img selection style

![image](https://user-images.githubusercontent.com/8381304/75671908-98799a00-5cba-11ea-8ff7-989bb2a841a2.png)

expected behavior:
want to be able to set the image selection style

versions:
V5.1.3

**Comment by lnewson** [comment]
This is native browser behaviour and it's not something we can do to fix, with the exception of implementing a fake selection model and manually doing selection ourselves. As such I'll mark this as a feature request for consideration, but this would potentially be a massive task and as such is not something we currently have planned to implement sorry.
