### ISSUE TITLE
There is no fallback behavior when DOM storage API is not available

### ISSUE THREAD

**Issue by Schnodderbalken** [tinymce/tinymce#5468]
**What is the current behavior? Describe the bug**

When embedding Tinymce in an Android-App webview that has not called `setDomStorageEnabled(true)` and thus not enabled the DOM storage a.k.a web storage (implemented as localStorage and sessionStorage) the editor does not load and neither tells the user what happened nor provides a workaround.

The console logs:
`Uncaught TypeError: Cannot read property 'getItem' of null", source: tinymce/tinymce/themes/silver/theme.min.js (9)`
and
`Uncaught TypeError: Cannot read property 'getRng' of undefined", source: tinymce/tinymce/tinymce.min.js?v=1582119202 (9)`

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

I am unable to reproduce this in a desktop environment or a usual mobile browser. I couldn't find out how to disable the web storage there.

**What is the expected behavior?**
Either inform the user about the fact that there was in issue or even better provide a fallback if the above mentioned API is unavailable.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I tested it on an Android smartphone with Android 9. TinyMCE version is 5.1.5.

It seems like this issue has come up in 2015 already: https://github.com/tinymce/tinymce/issues/919 however it might has become relevant again.

**Comment by spocke** [comment]
Right I guess we need to improve this check https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/api/util/LocalStorage.ts so localStorage is null wen disabled.
