### ISSUE TITLE
'context aware' Context menu is only shown when no contextmenu defined

### ISSUE THREAD

**Issue by DNWEIJ** [tinymce/tinymce#5469]
### Reproduce
open codepen from the documentation: 
`https://www.tiny.cloud/docs/demo/image-tools/#`
Open in codepen itself, we want to change a bit later.

Right click on image: a true 'contextaware' contextmenu is shown:  `link | image... |  edit image`
When i select text text, i will not see the image but i will see the link since that is context aware for text and the image options are contextaware for image only.
So far so good :-) 

Then:
add `contextmenu: 'bold' `   in the codepen. So the result will be: 
```
  ...<other code part>...
content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tiny.cloud/css/codepen.min.css'
  ],
  contextmenu: 'bold'
});
```

### Problem: 
When i rightclick on the image, i `ONLY`  see the Bold context menu. As a minimum i would expect to see the `contextmenu` be extended with bold: 
  `Bold | link | image... |  edit image`  OR   `link | image... |  edit image | Bold`

But instead i only see bold. 

This means that 'context aware' contextmenu (show image contextmenu when image is selected or show link contextmenu when href is selected) doesn't work as soon as a contextmenu has been defined explicitly. 

I would say that this renders the 'context aware' contextmenu useless, given the fact that once you want to work with a context menu, you probably want to have a defined one as well as being the default  in general.

Is it possible to add the 'contextaware' contextmenu to the defined contextmenu, once a specific context element has been seleceted? In this case: Selecting the image would show the image contextmenus and the general defined contextmenu elements. 

Regards, 
Daniël

**Comment by lnewson** [comment]
I think you've misunderstood how the `contextmenu` setting works. It overrides the default items, so as to allow for complete customization. That does come at a cost of having to redefine what parts of the default you want to use. As such, if you wanted bold and link for example, you should define `contextmenu: 'bold link'`.

The default context menu is: `link linkchecker image imagetools table spellchecker`
