### ISSUE TITLE
Tiny@4 EditorManager setup method falling over on null script src

### ISSUE THREAD

**Issue by bmatto** [tinymce/tinymce#5475]
When the `EditorManager` runs the `setup` method it pulls all the `script` tags on that page and tests against a `substr` of the `src` attribute. In some cases that `src` can be null - perhaps some other script on the page has manipulated a tag as such - and so the `subtr` call fails https://github.com/tinymce/tinymce/blob/4.9.8/src/core/main/ts/api/EditorManager.ts#L205.  This has been fixed in Tiny@5, however the issue persists in Tiny@4

**Comment by bmatto** [comment]
🙇

**Comment by bmatto** [comment]
Just so I am clear - I can expect this in 4.9.9 ?

**Comment by lnewson** [comment]
@bmatto yes, that's correct. I don't have a definite date for the 4.9.9 release at this stage, but it should be within roughly the next two weeks. If you're desperate you should be able to create a build from the `4.x` branch.
