### ISSUE TITLE
Clear highlights when the selection doesn't have highlighted text cause an error

### ISSUE THREAD

**Issue by godhandkiller** [tinymce/tinymce#5488]
When I use the backcolor plugin, I highlight the text, when I try to clear the highlight and I grab text that is not highlighted, and error appears on console and the highlight is not clear. This problem usually happens when you select the last part of the highlighted text with some text that is not part of the highlight.

This is how the text is selected when I want to clear the highlight.
![Screen Shot 2020-03-09 at 11 41 25](https://user-images.githubusercontent.com/18409311/76241988-825c6400-61fb-11ea-8cf5-abbdfe989f72.png)

This is the error I get on Chrome
![Screen Shot 2020-03-09 at 11 41 42](https://user-images.githubusercontent.com/18409311/76242007-89837200-61fb-11ea-89f3-02906a3145f8.png)

This is the error I get on Firefox
![Screen Shot 2020-03-09 at 11 42 04](https://user-images.githubusercontent.com/18409311/76242016-8e482600-61fb-11ea-9a51-e7c18916feca.png)

I'm using tiny 5.2 version. I try this on Firefox 72.0.2 (64-bit) & Chrome 80.0.3987.132 (Official Build) (64-bit)

**Comment by lnewson** [comment]
I was able to replicate the issue. At a glance it looks to be an issue in how the `RangeWalk` module works at a glance as it's trying to get a start node that's `undefined`.

**Comment by godhandkiller** [comment]
@lnewson I'm glad you were able to recreate it, hope a fix comes out soon

**Comment by lnewson** [comment]
This was fixed in TinyMCE 5.2.1 which was released to the community late last month. I'm really sorry that this slipped through the cracks and we didn't update that this had been released. If you have any further issues, please do let us know.

Thanks!
