### ISSUE TITLE
missing some files

### ISSUE THREAD

**Issue by Theolodewijk** [tinymce/tinymce#5489]
DevTools failed to parse SourceMap: https://domain.nl/TinyMCE/latest/skins/ui/oxide/skin.min.css.map
DevTools failed to parse SourceMap: https://domain.nl/TinyMCE/latest/skins/ui/oxide/content.min.css.map
DevTools failed to parse SourceMap: https://domain.nl/TinyMCE/latest/skins/content/default/content.min.css.map

used composer for installation in te public html

**Comment by lnewson** [comment]
I can confirm that these files are missing, however they aren't supposed to be included as it's a production style bundle. Instead the references to the sourcemaps should be getting stripped out when we're creating the bundle. I've created an internal task to fix that up.

**Comment by Theolodewijk** [comment]
@lnewson still missing files

**Comment by lnewson** [comment]
@Theolodewijk 5.2.1 hasn't been released yet, so that's expected. We've just merged the fix for this issue.

**Comment by Theolodewijk** [comment]
when is the release?

**Comment by lnewson** [comment]
@Theolodewijk 5.2.1 was released today, so that should fix the issue for you. If you are still experiencing issues, please let us know and we'll re-open this issue.

**Comment by Theolodewijk** [comment]
Thanks @lnewson tested and works fine now :)
