### ISSUE TITLE
Clear placeholder text on focus

### ISSUE THREAD

**Issue by n1ckster** [tinymce/tinymce#5492]
Hi,

I am using the latest version  of TinyMCE and need to know how to clear the placeholder text on focus. At the moment it only clears the placeholder text on keypress. Can you please give me an example of a function that clears the placeholder text on focus?

Thanks

Nick

**Comment by lostkeys** [comment]
We deciderat to mirror the placeholder behavior of the major browsers, and they hide the placeholder when a user starts to type. That gives users the most time to see what the field is about when the placeholder acts as a label because short attention span, you know 🤷‍♂️

**Comment by tmigacz** [comment]
For anyone who comes across this, adding this css will remove the placeholder on focus:

:host ::ng-deep .mce-content-body[data-mce-placeholder].mce-edit-focus::before {
    content: '';
}
