### ISSUE TITLE
Email validation now matches any URL containing an @ sign.

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5495]
**Is your feature request related to a problem? Please describe.**
We use tokens or template variables, e.g. @X@course.id@X@ in the editor to allow dynamic rendering (see http://docs.blackboard.com/learn/B2s/Dynamic%20Rendering%20with%20Template%20Variables.html). 

This was supported by TinyMCE 3.5, but after upgrading to TinyMCE 5, these tokens are mistakenly interpreted as email addresses, where a dialog comes up with the prompt "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?"

Is this a known issue that will be addressed in a future release?  Any suggestions?

**Comment by bdjnk** [comment]
You'll need to disable the `autolink` plugin. It uses [a very permissive regular expression](https://github.com/tinymce/tinymce/blob/5.2.0/modules/polaris/src/main/ts/ephox/polaris/api/Regexes.ts) and is entirely non-configurable.

To restore auto-linking, you could pre-enrich the text with [a decent and flexible auto-linker](https://www.npmjs.com/package/autolinker).

**Comment by lostkeys** [comment]
I can verify that removing autolink is the right solution in this case. Interestingly I don't know we show a dialog asking to insert a `mailto:` prefix. In all my testing, the mailto gets added automatically.

Please feel free to reopen this issue if this doesn't help or you have further questions.

**Comment by lostkeys** [comment]
Sorry, I was a bit trigger happy closing the ticket. The autolink regex is too permissive so we will review and improve it.
