### ISSUE TITLE
allow toolbar be visible on blur in inline mode ?

### ISSUE THREAD

**Issue by RainedX** [tinymce/tinymce#5505]
Hi,
I am using the latest version of TinyMCE , when i use inline mode, i want toolbar don't disappear on blur, how do I configure it ？

Thanks

Nick

**Comment by lostkeys** [comment]
Hi Nick! There is no supported way to make the inline toolbar persistent but we're looking at it. That's all I can say at the moment.

**Comment by RainedX** [comment]
thanks, i got it, i wish good!

**Comment by lostkeys** [comment]
Hey, Just wanted to let you know that this feature named [toolbar_persist](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_persist) was shipped in TinyMCE 5.5 a while ago.
