### ISSUE TITLE
&lt;test&gt; get stripped in v4.9.8

### ISSUE THREAD

**Issue by intenscia** [tinymce/tinymce#5522]
If you have a textarea with content between encoded HTML tags, it gets stripped.

&lt;test&gt;

This happens in the latest v4 version. If you setContent it doesn't get stripped, or type it in.

I am running the latest version of Chrome.

**Comment by spocke** [comment]
Make sure you entity encode the html within the textarea. So that all < > etc gets encoded into &lt; and &gt; so if you want the text <text> to be presented as text it should be encoded &amp;lt;text&amp;gt; this is how the browser dom works so nothing we can really work around a textarea should contain  entity encoded text for the html to load into the editor.

**Comment by intenscia** [comment]
To confirm I do entity encode. If you test the above in a tinymce activated textarea, the encoded tags will be stripped. i.e.

`<textarea>&lt;p&gt;hello world&lt;/p&gt;</textarea>`

will be displayed as

`<textarea>hello world</textarea>`

**Comment by lostkeys** [comment]
Can you create a fiddle here for us: http://fiddle.tinymce.com/. I'm unable to replicate the issue. I get `<p>Hello world</p>` in TinyMCE...

**Comment by lnewson** [comment]
If it helps here's an example fiddle, showing how it should be escaped, using the original text mentioned: http://fiddle.tinymce.com/Tehaab

**Comment by intenscia** [comment]
In that fiddle the & is also encoded to &amp; which is invalid right?

This works: `<textarea name="content">&amp;lt;test&amp;gt;</textarea>`

This doesn't: `<textarea name="content">&lt;test&gt;</textarea>`

Isn't the 2nd option the right one? Because if I type `<hello>` into tinymce it'll post that to the server as `&lt;test&gt;` which if I then show again in tinymce will disappear?

**Comment by spocke** [comment]
There are two levels of decoding here first the browser will decode the entities inside the text area so the value of `<textarea name="content">&amp;lt;test&amp;gt;</textarea>` becomes `&lt;test&gt;` then tinymce parses the html within the textarea into a text node by decoding once more into `<test>` so when you save the data tinymce will encode it to the second value then when you put the data into the textarea you should encode it.
