### ISSUE TITLE
upgrade tinymce from 4 to 5

### ISSUE THREAD

**Issue by magdalenaromala** [tinymce/tinymce#5524]
I version 5 
tinymce.resolve('tinymce.ui.Factory')
is undefined. 
In version 4 it worked. What can I do to fix it?

**Comment by lostkeys** [comment]
The UI APIs have been removed from TinyMCE 5, see https://www.tiny.cloud/docs/migration-from-4x/#editorchangestoapimethods

The fixes depends what you want to achieve. Let us know and we'll try to help you out.

**Comment by lnewson** [comment]
Closing this since there hasn't been an update in a month. If you're still having issue upgrading, please feel free to reply and we'll reopen this and try to help.
