### ISSUE TITLE
TinyMCE inside of a HTML5 <dialog> causes menus to show behind the dialog

### ISSUE THREAD

**Issue by GresiRoost** [tinymce/tinymce#5525]
**What is the current behavior? Describe the bug**
TinyMCE menu's are added to the DOM outside of the context of the editor element - this causes TinyMCE instances inside of the new HTML5 dialog element to have menus appearing behind the dialog. The new HTML5 dialog is drawn on a layer above everything else and cannot be "fixed" using z-index.

**Steps to reproduce**
Try this out in Chrome:
http://fiddle.tinymce.com/Xdhaab

**What is the expected behavior?**
The menus show up as normal even inside of the dialog. I suggest moving the menu items to a DOM element closer to the tinyMCE editor element instead of at the end of the body element - or possibly just make a workaround that does this only if inside a dialog element.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest cloud version of tinymce (as seen in the fiddle)
Tested in Chrome. HTML5 modal dialogs doesn't seem to be fully implemented in Firefox yet.
Working in previous versions? Unknown

**Comment by duclad** [comment]
I have the same issue...is there a way to tell where the menu items where should be generated?

**Comment by lostkeys** [comment]
Sorry, not at the moment.

**Comment by chadcallahan** [comment]
Shouldn't this be labeled/prioritized as a bug rather than a feature?

**Comment by aeallord** [comment]
I concur with chadcallahan, this should be prioritized as a bug and not a feature. Not good when implementing in a new website design and you can't access or see the menu because it is behind the dailog.

**Comment by lmanriq** [comment]
Has anyone had any progress on this? I'm having the same issue.

**Comment by AdminHcat** [comment]
I tried to use z-index, but it still didn't help

**Comment by lostkeys** [comment]
> Shouldn't this be labeled/prioritized as a bug rather than a feature?

TinyMCE was designed this way because we also have use-cases where menu items need to be positioned above all other UI elements. So from that perspective it is not a mistake and therefore not a bug. Still we are fully aware about the problems this lead to and we are actively investigating solutions, but we cannot promise anything at the moment.

**Comment by brainfoolong** [comment]
For all that still have this issue (as i have), here is a quick "hack" to move the tinymce helper element into the dialog, which is responsible for displaying menu items.  This move the helper in the context and rendering hierarchy of the `<dialog>`.

Done with TinyMCE v6.4. Maybe work in older versions as well.

This hack does come with other issues, like tooltips are behind menu popups now. But hey, better then a completely unusable editor in `<dialog>`.

```js
tinymce.init({
...
    init_instance_callback: function (editor) {
      // move last aux helper to dialog, if field is in a dialog
      const dialogContainer = editor.editorContainer.closest('dialog')
      if (dialogContainer) {
        const auxElements = document.querySelectorAll('body > .tox-tinymce-aux')
        if (auxElements.length) dialogContainer.append(auxElements[auxElements.length - 1])
      }
    }    
...
})
```

**Comment by TheSpyder** [comment]
For an easier version of that try `ui_mode: split`. This is a new feature in 6.4 that moves popups (such as menus) into a separate helper element that is a sibling of the editor. I'm not sure why the tooltips are appearing behind the dialog, we use standard `title` attributes so those are _browser_ tooltips.

Alternatively try the [Web Component](https://www.tiny.cloud/docs/tinymce/6/webcomponent-pm/) integration; web components by their nature force the helper element to remain inside the component.

At the end of the day our UI was designed long before the `dialog` element became standard and so it's using now-outdated techniques to display the interface.

**Comment by brainfoolong** [comment]
@TheSpyder Awesome. The option `ui_mode: 'split'` works like a charm without the need of the hack. About tooltips, nevermind, it was an issue with my implementation. I convert every `title` attribute automatically to a custom made tooltip, which in fact is the problem. So, tooltips are fine also with TinyMce only.

**Comment by TheSpyder** [comment]
Excellent, I'll close this then.

**Comment by ianterrell** [comment]
@TheSpyder I don't think that `ui_mode: 'split'` fully solves this issue. Additional panels remain behind the `dialog`.

Here's a new fiddle against 6.7.2: https://fiddle.tiny.cloud/PYjo9UwVZA/1

Without `ui_mode: 'split'`, the menus render behind the `dialog`:

<img width="678" alt="Screenshot 2023-11-10 at 11 23 30 AM" src="https://github.com/tinymce/tinymce/assets/54963/4a2da8f9-bb67-4920-81e6-c1b39ac080cf">

Adding `ui_mode: 'split'`, the menus render appropriately (or mostly appropriately, depending on one's point of view):

<img width="686" alt="Screenshot 2023-11-10 at 11 24 23 AM" src="https://github.com/tinymce/tinymce/assets/54963/cdd2ae54-64dd-46fa-9aa7-8d1186ce9d22">

However, additional panels still render behind — here is attempting to insert a link:

<img width="948" alt="Screenshot 2023-11-10 at 11 26 00 AM" src="https://github.com/tinymce/tinymce/assets/54963/fc64735b-b69b-404f-a769-7dd4ee4c2560">

---

I believe one of the main use cases for `dialog` elements is for modal forms, as it has tight integration with the `<form>` element including `method="dialog"`. From the spec, emphasis mine:

> The dialog element represents a transitory part of an application, in the form of a small window ("dialog box"), which the user interacts with to [_**perform a task or gather information.**_](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element)

I know it's likely to be a large lift that must be done over time, but I think that this should ticket should be reopened and TinyMCE should strive to work well within `dialog` elements.

**Comment by SolidGlenn** [comment]
Any progress on this?

**Comment by Webreaper** [comment]
Just hit this - looks like 4 years later it's not fixed. Anyone got any suggestions?
