### ISSUE TITLE
Mobile: textcolor gets stuck, can't exit control or select black text

### ISSUE THREAD

**Issue by rlf1358** [tinymce/tinymce#5533]
![tinymce editor mobile ui](https://user-images.githubusercontent.com/19580514/77433399-528d8e80-6dad-11ea-82c7-bdb235bd27e7.png)

- Cannot select black text after selecting any other color on the slider (slider doesn't move all the way back). Doesn't seem to matter if dragging the knob or just tapping on black.

- Cannot return to other editor features (or exit the editor), because the color slider overlays them and never goes away, even when tapping on the blank area. Maybe adding a close button to the slider bar would help and be more intuitive way to get back to the other controls.

Tested on Android Chrome: 80.0.3987.149, Operating System: Android 10; Pixel 2 Build QQ2A.200305.002

Sample tinymce config:
```
{
    theme: 'silver',    
    skin: false,    
    mobile: {
        theme: 'mobile',
        plugins: ['paste', 'link', 'autoresize', 'autolink', 'lists'],
        toolbar: "formatselect | bold italic underline | forecolor backcolor | link unlink | bullist numlist | removeformat"
    },
    content_style: 'body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";}',
    selector: '[data-trigger="texteditor"]',
    plugins: ['paste', 'link', 'autoresize', 'autolink', 'spellchecker', 'lists', 'textcolor'],
    block_formats: 'Paragraph=p; Header 1=h1; Header 2=h2; Header 3=h3',
    default_link_target: "_blank",
    min_height: 300,
    toolbar: "formatselect | bold italic underline | forecolor backcolor | link unlink | bullist numlist | 
removeformat",
    menubar: false
}
```

**Comment by lincolndennis** [comment]
Can you confirm exactly which version of TinyMCE you are testing with?

**Comment by lnewson** [comment]
It's also worth noting that you appear to be using the legacy mobile theme? That theme has been deprecated now, so we'd suggest upgrading to 5.1.0 or higher and using the silver theme since it's now the recommended/supported mobile theme.

**Comment by rlf1358** [comment]
Thanks for the reply. I'm using tinyMCE v5.2.0, but @lnewson is correct that this seems to be related to the legacy mobile theme. I must have overlooked that it was deprecated. I'll be switching to the silver theme, which by the looks of it will have none of these problems (thanks to the horizontal scrolling toolbar and popout color picker).

**Comment by tinydylan** [comment]
We'll be closing this issue for now. If you encounter any issues like this with the silver theme, please let us know.
