### ISSUE TITLE
tinymce editor is invisible on IE11 only?

### ISSUE THREAD

**Issue by andrew-bibby** [tinymce/tinymce#5537]
**What is the current behavior? Describe the bug**
Using a self hosted version of tinymce 5.1.6 and also rolled back to 4.9.9 - the editor displays and works fine on all browsers except IE11. The code is put into them DOM and is visible in the dev tools however it is an empty white space. It is simply not styled. As it works fine on all other browsers, I am pretty sure I have loaded all assets correctly. The dev tools show no console errors at all, so difficult to debug. Has anyone seen this issue or know a solution? As far as I am aware it should work in IE11. I have search extensively for a solution but no luck.

**What is the expected behavior?**

Expected to work on IE11 but styling / functionality invisible.

It works on chrome, firefox and edge.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

This is on IE11 version 11.0.9699.18015

**Comment by lostkeys** [comment]
Yes, TinyMCE 4 and 5 should work fine on Internet Explorer 11. It's very difficult for us to help out with debugging with the information we have here. I can only suggest trying to isolate the problem. 

1. Verify that a vanilla TinyMCE instance works on your particular browser by browsing to http://fiddle.tinymce.com and select the appropriate version in the sidebar.
2. Create a singe HTML file containing just the default editor

**Comment by andrew-bibby** [comment]
Thanks. I will look at that now.

**Comment by andrew-bibby** [comment]
@lostkeys thanks for your help. I checked the fiddle and it did display as expecting so it was my setup. I made use of the skin_url param and it now works. Not sure why it worked on chrome etc without that, but it has resolved the issue. 

Thanks.

**Comment by lostkeys** [comment]
Good it all worked out!
