### ISSUE TITLE
上传图片后的路径问题

### ISSUE THREAD

**Issue by hulang** [tinymce/tinymce#5546]
比如我上传完图片后，返回到图片框中是：
/static/upload/image/20200331/f416056b04afa6642d245ff302591e5f.jpg
但是我点击切换到源代码按钮，里面的路径：
../../../static/upload/image/20200331/f416056b04afa6642d245ff302591e5f.jpg
怎么样配置不要更改路径
我要：/static/upload/image/20200331/f416056b04afa6642d245ff302591e5f.jpg

**Comment by lostkeys** [comment]
Sorry we can only accept issues in English 😔.

**Comment by hulang** [comment]
已解决：convert_urls: false

**Comment by spocke** [comment]
Skönt att det löste sig.
