### ISSUE TITLE
Problem with page integrations/bootstrap.md

### ISSUE THREAD

**Issue by mmerbes** [tinymce/tinymce#5553]
TinyMCE does not initialize in bootstrap modals. The Documentation on this page does not fix the issue and the linked [jsfiddle does not work either](http://fiddle.tinymce.com/gRgaab).

> *affected page: https://www.tiny.cloud/docs/integrations/bootstrap/*

**Comment by lnewson** [comment]
@mmerbes can you please include more information, such as OS, browser, console logs or steps to reproduce the issue? I tested the docs and linked fiddle and they all work fine on my end using our supported browsers.

**Comment by lostkeys** [comment]
Closing this issue due to lack of response. @mmerbes feel free to reopen this ticket and provide additional details.
