### ISSUE TITLE
tinymce latest version

### ISSUE THREAD

**Issue by raselcse13** [tinymce/tinymce#5560]
need to added row marge column marge also added a paragraph content first line decreased  or increased feature

**Comment by lnewson** [comment]
This isn't clear, what is your issue sorry? Can you include a [fiddle](http://fiddle.tinymce.com) or something similar to show us your issue?

**Comment by lostkeys** [comment]
Closing this issue due to lack of response. @raselcse13 feel free to repoen this issue if you have more details to add so we can help you out better.
