### ISSUE TITLE
Clear placeholder on paste

### ISSUE THREAD

**Issue by smclaughry** [tinymce/tinymce#5561]
**What is the current behavior? Describe the bug**
Pasting into the editor does not clear the placeholder

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Configure an editor with placeholder, paste some text, notice that placeholder text is still displayed with pasted content overlaid on it.

**What is the expected behavior?**
Text is displayed, placeholder is not displayed

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Placeholder is a new feature from 5.2, so this is a new problem.

**Comment by smclaughry** [comment]
https://github.com/tinymce/tinymce/pull/5562

**Comment by lnewson** [comment]
As noted on the linked PR, this appears to only be an issue when relying on the native browser paste behaviour. If the `paste` or premium `powerpaste` plugin is used then it works as expected.

Either way, this is still unexpected so I've logged an internal task to fix this and we believe we have a solution for this edge case so I'll try and get that up shortly.

**Comment by lnewson** [comment]
If it helps, here's a temporary workaround until we can fix the issue: http://fiddle.tinymce.com/ofhaab/3
