### ISSUE TITLE
add funtion to Custom formats

### ISSUE THREAD

**Issue by wideweide** [tinymce/tinymce#5564]
**Is your feature request related to a problem? Please describe.**
some complex format can not be done with Custom formats,such as 
```
<p>left</p>
<p>right</p>
```

-->

```
<div class='left_right'>
  <span>left</span>
  <span>right<span>
</div>
```
use class 'left_right',imply style:

```
---------------------------------------------------------------------------------------
  left                                                                                                          right
---------------------------------------------------------------------------------------
```
**Describe the solution you'd like**
add funtion to Custom formats,then use editor.selection.setContent(newText) to imply this
I read the document,but it seems can add funtion to custom format

**Describe alternatives you've considered**
or how can I imply a button/menu just move custom formats to my own custom button/menu?

**Comment by lostkeys** [comment]
I’m not sure I follow. Can you please state the HTML and CSS that you expect in the end?

**Comment by wideweide** [comment]
just like this:

```
<div class="AuthorTime">
	<p class="LeftWidth">left</p>
	<p class="RightWidth">right</p>
</div>

.AuthorTime{
  width: 95%;
  border-top: 1px solid #000000;
  margin:20px auto;
  border-bottom:2px solid rgb(128, 128, 128);
}

.RightWidth{
  text-align: right;
  display: inline-block;
  float: right;
  width: 36%;
  padding-top: 20px;
  padding-bottom: 20px;
  margin-right: 20px;
}
.LeftWidth{
  text-align: left;
  display: inline-block;
  width: 48%;
  padding-top: 20px;
  padding-bottom:  20px;
  margin-left:20px;
}
```

**Comment by lostkeys** [comment]
What you're asking is too complex for formats. But it's easy to do with the [templates plugin](https://www.tiny.cloud/docs/plugins/template/). If you don't want the dialog you could just roll your own [custom button](https://www.tiny.cloud/docs/ui-components/toolbarbuttons/) that injects a [snipet of HTML](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#insertcontent).
