### ISSUE TITLE
No tools are visible when clicking on them in the panel

### ISSUE THREAD

**Issue by dastanaron** [tinymce/tinymce#5565]
**What is the current behavior? Describe the bug**

I made a video:
https://youtu.be/ht3OfDdqlOM

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

See in the video https://youtu.be/ht3OfDdqlOM

**What is the expected behavior?**

When you click on the button, the tool will open as at the beginning of the video

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Dependency in package.json:
"@tinymce/tinymce-vue": "^3.2.0"
LockVersion: 3.2.0
Browser:
google chrome 80.0.3987.163
firefox 74.0

**Comment by dastanaron** [comment]
My component code. Instead of stars, my api key
```vue
<template>
    <editor
        :name="name"
        :aria-placeholder="placeholder"
        v-model="model"
        @input="input"
        api-key="***"
        :init="init"
    >
    </editor>
</template>
<script>
    import Editor from '@tinymce/tinymce-vue'
    export default {
        name: 'mce-editor',
        props: {
            value: {
                type: String,
                default: '',
            },
            name: {
                type: String,
                default: 'text',
            },
            placeholder: {
                type: String,
                default: '',
            }
        },
        data: () => ({
            model: '',
        }),
        computed: {
          init() {
              return  {
                  language: this.$i18n.locale,
                  icons: 'material',
                  height: 500,
                  //menubar: false,
                  plugins: [
                      'advlist autolink lists link image charmap',
                      'searchreplace visualblocks code fullscreen',
                      'print preview anchor insertdatetime media',
                      'paste code help wordcount table'
                  ],
                  toolbar:
                      'undo redo | formatselect | bold italic underline | \
                      alignleft aligncenter alignright | \
                      forecolor backcolor table | \
                      bullist numlist outdent indent | help'
              }
          }
        },
        methods: {
            input(text) {
                this.$emit('input', text);
            },
        },
        watch: {
            value(newValue, oldValue) {
                this.model = newValue;
            }
        },
        mounted() {
            this.model = this.value;
        },
        components: {
            editor: Editor
        }
    }
</script>
```

**Comment by lostkeys** [comment]
TinyMCE puts menus in a `<div>` at the bottom of the body, just above the closing `</body>` tag, can you check that the menus are loaded in the DOM. If so, this might be a z-index issue.

**Comment by dastanaron** [comment]
> TinyMCE puts menus in a `<div>` at the bottom of the body, just above the closing `</body>` tag, can you check that the menus are loaded in the DOM. If so, this might be a z-index issue.

![image](https://user-images.githubusercontent.com/25330618/78865863-14e46300-7a47-11ea-94a4-2df0fe4ebb8e.png)

Yes menu in the body dom element, but z-index not working 
![image](https://user-images.githubusercontent.com/25330618/78866155-8b816080-7a47-11ea-998c-6fc7a8ea4a98.png)
In addition, the stylesheet is located on cdn.tiny.cloud and I don't corrected them. I can only connect my styles

**Comment by dastanaron** [comment]
I solved the problem by adding lines to my stylesheet 
```css
body .tox.tox-silver-sink.tox-tinymce-aux {
    z-index: 999999;
}
```
But I think you need to consider your styles considering modal windows
