### ISSUE TITLE
I can't find what I'm looking for: advanced/editor-icon-identifiers.md

### ISSUE THREAD

**Issue by rassezgin** [tinymce/tinymce#5566]
It will be useful to add "location marker" icon

**Comment by lostkeys** [comment]
Hi! Just Letting you know that we are not going to add a location marker to the default icon pack until we have a plugin that needs one, so we’re closing this for now to not have open issues lingering. You can [create an icon pack](https://www.tiny.cloud/docs/advanced/creating-an-icon-pack/) yourself and include whatever icons you need as Tyler mentioned above.
