### ISSUE TITLE
I can't find what I'm looking for: plugins/index.md

### ISSUE THREAD

**Issue by TomCasano** [tinymce/tinymce#5567]
Is there  plugin that allows you to input a set of phrases, and have any occurences of those phrases be automatically highlighted both as you type, and when the editor is first initialized with pre-existing content?

**Comment by lnewson** [comment]
You might be able to use the [`textpattern`](https://www.tiny.cloud/docs/plugins/textpattern/) plugin to define a sequence that can be used around said phrases to highlight them. Here's a basic example that allows highlighting a phrase wrapped in `{{` characters, such as `{{phrase}}`: http://fiddle.tinymce.com/Mghaab. However, neither that or the autocompleter @tylerkelly13 mentioned above will allow for it to be highlighted on load.

So to answer your question, no sorry there's no plugin in our list of plugins that will do what you want, however there could be a third party plugin that might provide such functionality. Unfortunately I'm not aware of any such plugin at this time.
