### ISSUE TITLE
I want to put a group of operations in the undo stack. How to do it? 

### ISSUE THREAD

**Issue by ContainsK** [tinymce/tinymce#5571]
Help me, I want to put a group of operations in the undo stack. How to do it?

**Comment by lnewson** [comment]
You should be able to use the [`editor.undoManager.transact(callback)`](https://www.tiny.cloud/docs/api/tinymce/tinymce.undomanager/#transact) API to group multiple changes within the one undo level.

**Comment by ContainsK** [comment]
> You should be able to use the [`editor.undoManager.transact(callback)`](https://www.tiny.cloud/docs/api/tinymce/tinymce.undomanager/#transact) API to group multiple changes within the one undo level.

Thank you ! ~
