### ISSUE TITLE
Pasting links over links in compose messes up link destination

### ISSUE THREAD

**Issue by d-haus** [tinymce/tinymce#5574]
**What is the current behavior? Describe the bug**
Pasting a url over a link messes up the link destination. The text and link targed are no longer in sync. This provides confusion to the user or might even be missused for phishing etc.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Copy a URL, needs to start with http and must be text, without any markup http://www.google.com works for me
2. Paste the URL into tinyMCE
3. Press space (the URL gets "linkified")
4. Copy another URL, needs to start with http and must be text, without any markup I used http://www.youtube.com
5. Select the whole link in tinyMCE inlcuding the space after it (if you dont select the space a different bug appears (Link will include both urls after pasting which is also wrong))
6. Paste the new URL

7. Link destination points to the new url while the text reads the old url

Can be reproduced in http://fiddle.tinymce.com/

**What is the expected behavior?**

Link text and destination are both set to the new url.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
We are using version 4.9.8 . Tested on Chrome / Windows 10 but it seems to be the same in every browser/os

**Comment by lnewson** [comment]
This is expected behaviour, as this is the paste plugins "smart paste" behaviour which will convert URLs to links when pasting over content within the editor. You can disable it using the undocumented `smart_paste: false` configuration.

I'll log a documentation ticket to make sure this gets added to the documentation.
