### ISSUE TITLE
"more" button produces toolbar with height:1px

### ISSUE THREAD

**Issue by janis-piazza** [tinymce/tinymce#5577]
**What is the current behavior? Describe the bug**
Happens if tiny is within block with style="position:absolute;"

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Pfhaab

**What is the expected behavior?**
Additional toolbars should appear normally, the same as when style="position:static;"

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tiny 5.2.1, FF, Chrome, Safari on Mac

**Comment by lnewson** [comment]
Thanks for this report @janis-piazza! TinyMCE 5.2.2 has now been released which includes a fix for this issue. If you are still experiencing issues, please let us know and we'll re-open this issue.
