### ISSUE TITLE
I can't find what I'm looking for: configure/integration-and-setup.md

### ISSUE THREAD

**Issue by Symon67** [tinymce/tinymce#5583]
Hello,
My tinymce editor is not displaying correctly, it comes from one of my div here is the code and the screenshot below.
thank you for helping me

```
<div class="col-middle-wrapper">
  <div id="text-view">
    <span>Votre texte</span>
    <textarea id="texte" name="texte"></textarea>
  </div>
</div>
```

```
<script src='https://cdn.tiny.cloud/1/<API_KEY>/tinymce/5/tinymce.min.js' referrerpolicy="origin"></script>
<script>
var editeur = tinymce.init({
  selector: '#texte',
  plugins: "link lists",
  menubar: false,
  toolbar: "bold italic | alignleft aligncenter alignright | numlist bullist | link | fontsizeselect",
  statusbar: false,
  width:'100%',
  height: 500,
                
});
</script>
```

![Capture d’écran de 2020-04-20 11-56-38](https://user-images.githubusercontent.com/48885193/79739244-33c3de80-82fe-11ea-998d-1eadd19c33fa.png)

**Comment by lnewson** [comment]
I've moved this to the TinyMCE repo, as this isn't related to the documentation. @Symon67 can you please create a [fiddle](http://fiddle.tinymce.com/), as this looks like we'll need to be able to reproduce it to help diagnose the issue.
