### ISSUE TITLE
Media plugin - media_url_resolver - X-Frame-Options issue

### ISSUE THREAD

**Issue by ldecoker** [tinymce/tinymce#5587]
When using media_url_resolver to change the embedHtml, I got X-Frame-Options issue (preview not working in editor and in front page).

`tinymce.init({
	selector: '.tinymce',
	plugins : 'advlist autolink link lists code media',
	toolbar: [
		'undo redo | cut copy paste selectall | styleselect | bold italic underline strikethrough subscript superscript removeformat | alignleft aligncenter alignright alignjustify',
		'link media | code | forecolor backcolor | bullist numlist outdent indent'
	],
	menubar: false,
	statusbar: false,
	media_alt_source: false,
	media_dimensions: false,
	media_poster: false,
	media_url_resolver: function (data, resolve) {
			var embedHtml = '<div class="embed-responsive embed-responsive-16by9"><iframe src="' + data.url +
				'" allowfullscreen="allowfullscreen"></iframe></div>';
			resolve({html: embedHtml});
		}
});`

[https://codepen.io/venizia03/pen/rNOMEzW](url)

** Version **
Version: 5.1.5 (2019-12-19) or 5.2.1 (codepen)

**Comment by lnewson** [comment]
This isn't something that we can fix sorry. It's a server-side security setting for the media content, so it can only be adjusted on the server that hosts the media.

More details can be found on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by lnewson** [comment]
It worth noting that if you're using something like a YouTube video/URL, then the default media resolver will change the URL to use a YouTube embed URL. You can see what's remapped here: https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/plugins/media/main/ts/core/UrlPatterns.ts#L19

**Comment by ldecoker** [comment]
ok that could explain why when I am not using the media_url_resolver option, it's working (it's indeed YouTube URL). I will check that.

Thx!

**Comment by ldecoker** [comment]
Is there a way to use the UrlPatterns inside the media_url_resolver or should I redo all logics?
