### ISSUE TITLE
Question: how to detect unformatted text

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#5590]
What is the correct TinyMce way to check if the selected text has no formatting? We can use `editor.formatter.match` to check if the selected has a particular style (strong, heading, etc), but what about checking for not style at all?

**Comment by lostkeys** [comment]
It depends on what you mean by style and formatting. Styles can come either from an external stylesheet (including the browser's default one) or be set inline on HTML tags using the style attribute. Then you have the HTML semantic tags like h1, strong, em etc. So it really depends on what your'e looking to detect

**Comment by petko** [comment]
I am interested if the text contains only plain text paragraphs (<p>) without any class or style attributes. 

In other words, I want to simulate a Normal style as in word processors like Ms Word.

**Comment by lostkeys** [comment]
Here is an example on how to make a normal style format: http://fiddle.tinymce.com/Hghaab

Other than that, I guess you can get the selection and make a custom function to figure out whether it contains any stylistic attributes.
