### ISSUE TITLE
Escape bug in the silver theme's Collection definition

### ISSUE THREAD

**Issue by kanadaj** [tinymce/tinymce#5603]
**What is the current behavior? Describe the bug**

The default theme's Collection uses the following code to escape double quotes in HTML strings:
```ts
  const escapeAttribute = (ch) => {
    if (ch === '"') { return '&quot;'; }
    return ch;
  };
```
This escape code assumes a single character, and does not seem to work when inputting a full string. This becomes obvious if you try to add HTML based emoticons using the `<img>` tag but would affect any other plugins relying on the collection class. 

Replacing the above code with a regex replace works as intended.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/Lghaab

**What is the expected behavior?**

The value of the data-collection-item-value attribute shouldn't overflow into the content

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Unlikely to have worked before; Chrome, Firefox and Edge (latest stable) are all affected. Affects all versions I've tested from 5.0.8 to tinymce5-cloud-dev

**Comment by lnewson** [comment]
Hi @kanadaj,

Currently, we only support single characters inside collections, so it's not expected this would work. We do have a feature in our backlog to look at supporting more advanced items such as images, however that hasn't been scheduled yet. None the less, this is still a bug as it should be replacing all instances as you mentioned, so I've logged an internal task to fix that. However, given this still something that isn't currently supported I'm going to close this issue.

Thanks!

As a side note, if you replace `"` with `'` in your fiddle then it will work: http://fiddle.tinymce.com/Lghaab/1

**Comment by kanadaj** [comment]
@lnewson Actually it works fine with images with the fix, so why not make it official?
