### ISSUE TITLE
Table plugin bugging

### ISSUE THREAD

**Issue by sandorvasas** [tinymce/tinymce#5606]
TinyMCE 5.2.2
tinymce-react 3.5.0

When trying to insert a table, and the grid appears, I can only select a 1x1 table, the others are greyed out. Not sure if it doesn't recognize pointer events or what. If devtools are open and I go over the grid with 'Inspect Element', then it starts to recognize the cursor. So then if I turn off inspect element and start hovering the mouse above the grid, it works fine.
(Btw even tho it displays 1x1 and I can't select a larger table, if I DO select e.g. a 5x6 table, it will create a 5x6 table, so I reckon just the grid's UI is not updating well)

Other issue which is quite similar is that after inserting a table, selecting it, then clicking anything on the table toolbar does nothing but hide the toolbar.

**Comment by lnewson** [comment]
@sandorvasas can you please include details such as what browser, os and device you're using? (eg Firefox, Mac, Desktop). It'd also be useful if you could record a small video, or provide some way for us to replicate the issue?

**Comment by sandorvasas** [comment]
PC, Ubuntu 16.04 LTS 
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

I'll put together a blank react app and try to replicate it there then share with you.

**Comment by lnewson** [comment]
Thanks for that, and here's another couple of questions that come to mind, that would be helpful to try and diagnose what's going on:
- Was this working in previous versions of TinyMCE?
- Are you able to replicate the issue in a basic [fiddle](http://fiddle.tinymce.com/) or similar? or does it only happen in a react app?

**Comment by sandorvasas** [comment]
Issue was unrelated to TinyMCE. 

The Editor was placed in a React Material-UI Drawer, which had tabindex attributes set. Removing those helped.

**Comment by lnewson** [comment]
Glad to hear you got this resolved. I'd be curious to hear why the tabindexes broke this, as there might be something we can do to prevent that causing issues. Anyways, since you got this resolved I'll go ahead and close this.

**Comment by BowlingX** [comment]
Just in case someone stumbles upon this again. The Main problem in combination with MaterialUI is the `TrapFocus` component. If you add the prop `disableEnforceFocus` it works properly (applies also to the `Drawer`, as it's a `Dialog` internally). See https://material-ui.com/api/modal/

**Comment by dave-lw** [comment]
i have this problem in a bootstrap theme... in a modal popup.  
video:  https://share.vidyard.com/watch/bhAxfjqab3kvBnckoTtY6F
tinyMCE version - Version: 5.6.1 (2020-11-25)

**Comment by Ashish-lad07** [comment]
"@tinymce/tinymce-angular": "^7.0.0",
       "tinymce": "^6.8.0",
Hello same issue i am facing in angular i tried removing tabindex but its not working in my case and in my project we are not using  Angular Material
![cell](https://github.com/tinymce/tinymce/assets/151039638/9abb917c-3cc3-4263-843a-00e83d5670eb)

**Comment by dave-lw** [comment]
we solved it but i cant remember the cause... our other code though, not
tinyMCE
