### ISSUE TITLE
Transparency background color of content box (iframe) less override.. fails with white hardcoded 

### ISSUE THREAD

**Issue by nphias** [tinymce/tinymce#5612]
I would have thought this would be a simple config setting...  but I cant find any
after a long time searching and trying to compile a custom skin

it appears the white background is coded at 
.tox-edit-area__iframe 

the override in the skin.less fails and in content.less too
i found these links.. dont like the jquery hackaround

https://stackoverflow.com/questions/60135463/transparent-editor-background-in-tinymce-5
https://deepindera.blogspot.com/2013/09/tiny-mce-40-how-to-change-background.html

I am using the latest version of tinymce.
any help on this appreciated

**Comment by lostkeys** [comment]
Hi! Use the `@edit-area-iframe-background-color` [when making your skin](https://www.tiny.cloud/docs/advanced/creating-a-skin/) to make the iframe transparent. Also make sure your content.css doesn't include any background color.

Here is an [example from our skin tool](http://skin.tiny.cloud)
<img width="1319" alt="Screen Shot 2020-04-28 at 06 15 38" src="https://user-images.githubusercontent.com/3122929/80446706-db9d6580-8917-11ea-893d-035b7bde447b.png">

Please feel free to reopen this ticket if you have additional questions on the topic.

**Comment by nphias** [comment]
thanks very much @lostkeys ! I am sure that will help a lot of people...
a couple of things to follow up... 
1. i also want to change the text color in the edit area frame..
    i tried @edit-area-iframe-color: white;
    and @edit-area-iframe-text-color: white;
    no joy.
2. is there a reference documentation for these less override options?

**Comment by lnewson** [comment]
@nphias I'll let @lostkeys answer the second point, as he knows a lot more about it than me. 

However, for the first point the default text color of the content inside the iframe isn't controlled via the skin. That is controlled via the content css used, which you should generally point to a CSS file from your site so it'll look the same inside the editor and outside on your site. You can apply that via the `content_css` setting: https://www.tiny.cloud/docs/configure/content-appearance/#content_css

**Comment by lostkeys** [comment]
You can read all about making a skin here: https://www.tiny.cloud/docs/advanced/creating-a-skin/

To add to @lnewson's answer, if you just need to set some quick styles, you could also use the [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) option.
