### ISSUE TITLE
table border

### ISSUE THREAD

**Issue by raselcse13** [tinymce/tinymce#5613]
i think table border not working property  
i think add to all table td th  using full table using border but not working 

like this

https://www.w3schools.com/css/tryit.asp?filename=trycss_table_border

**Comment by raselcse13** [comment]
another  feature need to add table strip table property  and add any color using striping  and any here row select and after striping start .Like if you select 3 number row striping start 3

**Comment by raselcse13** [comment]
add another feature hanging text 
add another feature table indent 
add another feature table nowrap and wrap
add another feature Table Row and Table Column merge options
and another feature multiple table bank row remove option

Remove Blank Row
--




Remove Blank Row
--

**Comment by lostkeys** [comment]
Generally you set your table styles in the content.css. If you want your users to be able to style a table they can use the table, row and cell properties reachable from the right click menu.

**Comment by lostkeys** [comment]
* **Hanging text:** we have some loose plans for a paragraph styling plugin that would achieve that. You can make a custom style format for it today though.
* **Table indent:** You mean indenting the whole table?
* **Table nowrap and wrap:** You mean prevent text wrapping in a table cell?
* **Table row and column merge options:** You can merge table cells in TinyMCE. Please tell me more what you need that the existing feature doesn't accomplice
* **Multiple table bank row remove option:** Not sure what you mean

**Comment by raselcse13** [comment]
this is example multiple  row
<table>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
</tr>
</table>
Multiple table bank row remove option

**Comment by raselcse13** [comment]
You mean indenting the whole table? 
yes

**Comment by raselcse13** [comment]
another feature  table strip need to option table property  user want to add any color using table strip

**Comment by raselcse13** [comment]
another feature if i use whole table border table,th,td full table border option

**Comment by lostkeys** [comment]
**Multiple table blank row remove option**
Isn't this sufficient? Thiw will delete the two rows.
<img width="581" alt="Screen Shot 2020-04-28 at 09 42 03" src="https://user-images.githubusercontent.com/3122929/80461025-f205ea00-8934-11ea-83f4-7c5a74581177.png">

**Comment by lostkeys** [comment]
**You mean indenting the whole table**
Added that to our feature request database. But I cannot promise anything.

**Comment by lostkeys** [comment]
**option table property user want to add any color using table strip**
You mean you want a toolbar button to change the color of a cell in the context toolbar above the table?
<img width="553" alt="Screen Shot 2020-04-28 at 09 43 47" src="https://user-images.githubusercontent.com/3122929/80461239-41e4b100-8935-11ea-9514-eda15dfbca0d.png">

**Comment by lostkeys** [comment]
**whole table border table,th,td full table border option**
I'm not sure I understand what you're trying to do, because I feel it's already supported??

**Comment by raselcse13** [comment]
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 5px solid black;
}
</style>
</head>
<body>

<h2>Add a border to a table:</h2>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
  </tr>
  <tr>
    <td>Peter</td>
    <td>Griffin</td>
  </tr>
  <tr>
    <td>Lois</td>
    <td>Griffin</td>
  </tr>
</table>

</body>
</html>

**Comment by raselcse13** [comment]
![image](https://user-images.githubusercontent.com/24198895/80461707-808b6300-8957-11ea-93f1-26d5137ecf1c.png)

**Comment by raselcse13** [comment]
like this

**Comment by raselcse13** [comment]
but 
![image](https://user-images.githubusercontent.com/24198895/80461846-b6304c00-8957-11ea-8236-5460be3df484.png)
here like 100 multipe line blank  some row have data another row not data how can we handle it i think if we implement a option  select empty row and delete all empty row

**Comment by raselcse13** [comment]
this is example multiple  row
<table>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
</table>
Multiple table bank row remove option
Like this

**Comment by raselcse13** [comment]
You mean you want a toolbar button to change the color of a cell in the context toolbar above the table? yes

**Comment by lostkeys** [comment]
For the tables, do you mean like this? http://fiddle.tinymce.com/bhhaab

**Comment by raselcse13** [comment]
![image](https://user-images.githubusercontent.com/24198895/80489292-6c5c5b80-8981-11ea-982d-651210e563b7.png)
already i can done this

**Comment by raselcse13** [comment]
![image](https://user-images.githubusercontent.com/24198895/80489750-1b009c00-8982-11ea-97f9-dbdf8966e82b.png)

**Comment by lostkeys** [comment]
This is how you would make a zebra striped table format: http://fiddle.tinymce.com/hhhaab. Is this what you are looking for?

**Comment by raselcse13** [comment]
<table class="striped" style="border-collapse: collapse; width: 100%; height: 154px;" border="1">
<tbody>
<tr style="height: 22px;">
<th style="width: 33.333333333333336%; height: 22px; background-color: #7e8c8d;">Name</th>
<th style="width: 33.333333333333336%; height: 22px; background-color: #7e8c8d;">Age</th>
<th style="width: 33.333333333333336%; height: 22px; background-color: #7e8c8d;">Score</th>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">John</td>
<td style="width: 33.333333333333336%; height: 22px;">12</td>
<td style="width: 33.333333333333336%; height: 22px;">123</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Jane</td>
<td style="width: 33.333333333333336%; height: 22px;">14</td>
<td style="width: 33.333333333333336%; height: 22px;">144</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Joan</td>
<td style="width: 33.333333333333336%; height: 22px;">22</td>
<td style="width: 33.333333333333336%; height: 22px;">213</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Johan</td>
<td style="width: 33.333333333333336%; height: 22px;">32</td>
<td style="width: 33.333333333333336%; height: 22px;">123</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Jenny</td>
<td style="width: 33.333333333333336%; height: 22px;">11</td>
<td style="width: 33.333333333333336%; height: 22px;">120</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Jimmy</td>
<td style="width: 33.333333333333336%; height: 22px;">46</td>
<td style="width: 33.333333333333336%; height: 22px;">56</td>
</tr>
</tbody>
</table>
your code i think not working table strip

**Comment by raselcse13** [comment]
<table class="striped" style="border-collapse: collapse; width: 100%; height: 154px;" border="1">
<tbody>
<tr style="height: 22px;">
<th style="width: 33.333333333333336%; height: 22px; background-color: #7e8c8d;">Name</th>
<th style="width: 33.333333333333336%; height: 22px; background-color: #7e8c8d;">Age</th>
<th style="width: 33.333333333333336%; height: 22px; background-color: #7e8c8d;">Score</th>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">John</td>
<td style="width: 33.333333333333336%; height: 22px;">12</td>
<td style="width: 33.333333333333336%; height: 22px;">123</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Jane</td>
<td style="width: 33.333333333333336%; height: 22px;">14</td>
<td style="width: 33.333333333333336%; height: 22px;">144</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Joan</td>
<td style="width: 33.333333333333336%; height: 22px;">22</td>
<td style="width: 33.333333333333336%; height: 22px;">213</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Johan</td>
<td style="width: 33.333333333333336%; height: 22px;">32</td>
<td style="width: 33.333333333333336%; height: 22px;">123</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Jenny</td>
<td style="width: 33.333333333333336%; height: 22px;">11</td>
<td style="width: 33.333333333333336%; height: 22px;">120</td>
</tr>
<tr style="height: 22px;">
<td style="width: 33.333333333333336%; height: 22px;">Jimmy</td>
<td style="width: 33.333333333333336%; height: 22px;">46</td>
<td style="width: 33.333333333333336%; height: 22px;">56</td>
</tr>
</tbody>
</table>

**Comment by lostkeys** [comment]
Unfortunately, it is not possible to set a format that way. What you need is for the format to match on the `<table>` element (in other words, when you have the table selected) but have the styles applied on the `<td>` element. This is not possible to do in TinyMCE and we don't currenly have any plans to implement this feature as it would be super complicated considering copy and paste and figuring out that it's actually the table that is zebra striped, and not the cells. 

I recommend you keep the styles separately in your web service, and when the user downloads the HTML file you run a script that inlines all styles, [something similar to this perhaps](https://github.com/lukehorvat/computed-style-to-inline-style) (I've not tested this script, just pointing you on the right direction)

**Regarding removing empty table rows**, I recommend a similar approach, that you search for empty rows via a script outside of TinyMCE (before loading the content into the editor) that filter out any empty rows. You could also do a custom button for cleaning up tables that runs a custom script that removes empty rows.

**Comment by raselcse13** [comment]
i made this 
![image](https://user-images.githubusercontent.com/24198895/80564269-39f93f80-8a0f-11ea-8cc7-d264b86e8fcf.png)

but i need like this interface how can implement
![image](https://user-images.githubusercontent.com/24198895/80564605-0ff44d00-8a10-11ea-80e2-a792fbc0fb7a.png)

**Comment by lostkeys** [comment]
Sorry, it's not possible to customize the existing dialogs in TinyMCE.

**Comment by raselcse13** [comment]
have any idea

**Comment by lostkeys** [comment]
Sorry it cannot be done. You have to make a custom dialog outside of TinyMCE

**Comment by raselcse13** [comment]
please can share me valid angular supported dialog box

**Comment by raselcse13** [comment]
this error message Expected method shorthand  object-shorthand

![image](https://user-images.githubusercontent.com/24198895/80575731-d6c6d780-8a25-11ea-80b9-10d29f628884.png)

**Comment by lostkeys** [comment]
What error do you get?

**Comment by raselcse13** [comment]
Expected method shorthand object-shorthand

**Comment by raselcse13** [comment]
![image](https://user-images.githubusercontent.com/24198895/80577447-b8161000-8a28-11ea-8b94-4090310e1e18.png)

**Comment by lostkeys** [comment]
`Expected method shorthand object-shorthand` seems to be a linter error rather than a syntax error. You need to rewrite the code do conform with your linter.

**Comment by lostkeys** [comment]
> please can share me valid angular supported dialog box

Sorry, that is outside of the scope of support we're available to give here. I'm simply pointing you towards possible solutions to your problem, in this case making your own UI and using the TinyMCE API's to apply the neccesseary formats that you already have in the styleselect.

**Comment by raselcse13** [comment]
hei 
can i add multiple border style please let me known how can i add multiple border style
![image](https://user-images.githubusercontent.com/24198895/80683327-dc83f200-8ae5-11ea-98c5-81ef1a7bdcc9.png)

**Comment by lostkeys** [comment]
I’m sorry, its not possible to add multiple borders through the table dialog UI. 😕

**Comment by raselcse13** [comment]
I want add dropdown list more border style please help me how can i add 
![image](https://user-images.githubusercontent.com/24198895/80812232-551fa700-8be9-11ea-822d-1aab6385a042.png)

**Comment by lostkeys** [comment]
Sorry you can't add items to that list through any API:s

**Comment by raselcse13** [comment]
(function () {
    'use strict';

    var global = tinymce.util.Tools.resolve('tinymce.PluginManager');

    var open = function (editor) {
      editor.windowManager.open({
        title: 'Indent Table',
        size: 'normal',
        body: {
          type: 'panel',
          items: [{
              name: 'indentSize',
              type: 'input',
              label: 'Indent Size (px): ',
              placeholder: 'Ex: 4'
            }]
        },
        buttons: [
          {
            type: 'cancel',
            name: 'cancel',
            text: 'Cancel'
          },
          {
            type: 'submit',
            name: 'save',
            text: 'Save',
            primary: true
          }
        ],
        onSubmit: function (api) {
          var data = api.getData();
          var table = document.getElementsByTagName("table")[0];
          var indentSize = api.data.indentSize;
          table.style.textIndent = indentSize + "px";
            
          api.close();
        }
      });
    };

    var register = function (editor) { 
      editor.addCommand('mceindentTable', function () {
        open(editor);
      });
    };

    var setContentEditable = function (state) {
      return function (nodes) {
        for (var i = 0; i < nodes.length; i++) {
          nodes[i].attr('contenteditable', state);
        }
      };
    };
    var setup = function (editor) {
      editor.on('PreInit', function () {
        editor.parser.addNodeFilter('a', setContentEditable('false'));
        editor.serializer.addNodeFilter('a', setContentEditable(null));
      });
    };

    var register$1 = function (editor) {
      editor.ui.registry.addToggleButton('indentTable', {
        icon: 'indent',
        tooltip: 'Indent Table',
        onAction: function () {
          return editor.execCommand('mceindentTable');
        },
        onSetup: function (buttonApi) {
          return editor.selection.selectorChangedWithUnbind('a:not([href])', buttonApi.setActive).unbind;
        }
      });
      editor.ui.registry.addMenuItem('indentTable', {
        icon: 'indent',
        text: 'indentTable...',
        onAction: function () {
          return editor.execCommand('mceindentTable');
        }
      });
    };

    function Plugin () {
      global.add('indentTable', function (editor) {
        setup(editor);
        register(editor);
        register$1(editor);
      });
    }

    Plugin();

}());
i made this plugin but not working can you help me fixing issues  
![image](https://user-images.githubusercontent.com/24198895/93557620-47529e80-f99d-11ea-8d4e-df371db3dab1.png)

**Comment by Xiamer** [comment]
> I want add dropdown list more border style please help me how can i add
> ![image](https://user-images.githubusercontent.com/24198895/80812232-551fa700-8be9-11ea-822d-1aab6385a042.png)
> 
> i need add border style buttom border,left border,right border ,top border

how to hidden some table border style ？ dashed、solid is enough for me。 thx

**Comment by lostkeys** [comment]
Hi @Xiamer! There is no way to configure the border style list. However you can create your own custom dialog containing the form elements you need and then use some API commands to style the table.

Here are some links to get you started:
* https://www.tiny.cloud/docs/ui-components/dialog/
* https://www.tiny.cloud/docs/ui-components/dialogcomponents/#panelcomponents
* https://www.tiny.cloud/docs/ui-components/dialogcomponents/#panelcomponents (Look specifically at `mceTableApplyCellStyle`)

**Comment by Xiamer** [comment]
> Hi @Xiamer! There is no way to configure the border style list. However you can create your own custom dialog containing the form elements you need and then use some API commands to style the table.
> 
> Here are some links to get you started:
> 
> * https://www.tiny.cloud/docs/ui-components/dialog/
> * https://www.tiny.cloud/docs/ui-components/dialogcomponents/#panelcomponents
> * https://www.tiny.cloud/docs/ui-components/dialogcomponents/#panelcomponents (Look specifically at `mceTableApplyCellStyle`)

@lostkeys thx,  but i used glbal css to resolve this, this is a ruthless method ！O(∩_∩)O~
```code
.tox-collection__group  div[title="Dotted"] {
    display: none!important;
}
```

**Comment by lostkeys** [comment]
@Xiamer That only fixes removing options from the dropdown though...

**Comment by zjhr** [comment]
Hello @lostkeys , I need your help. `editor.execCommand('mceTableApplyCellStyle', false, {'borderBottomColor': '#fff'});`,I need to set the color of a part of a boder of a cell, but it doesn't take effect. why?

**Comment by lostkeys** [comment]
@zjhr `mceTableApplyCellStyle` only works for border-bottom, border-width and border-style [as stated in the docs]:(https://www.tiny.cloud/docs/plugins/opensource/table/#commands)
>Applies the specified styles to the selected cells. The following styles can be changed with this command: background-color, border-color, border-style, and border-width.

However in the spirit of hacking a solution, [if we peek under the hood and look at the code](https://github.com/tinymce/tinymce/blob/108e669682322ff8aef26c78310db5794775c869/modules/tinymce/src/plugins/table/main/ts/api/Commands.ts#L188), what's actually happening is that `mceTableApplyCellStyle` sets a format. With that knowledge we can make custom formats to create a border-bottom-color feature. Note that the format has to be named `tablecell<style>` where style is the lowercase style name without a hyphen, eg `bordercolor`.

I've put together a demo here: https://fiddle.tiny.cloud/C1haab

Please note that this is undocumented and unsupported and may change without notice in any release

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. This seems to have been resolved a long time ago.

**Comment by mauricioprado00** [comment]
solution in here:
https://github.com/tinymce/tinymce/pull/10160

please vote up so they push the fix:
https://github.com/tinymce/tinymce/discussions/10165
