### ISSUE TITLE
Is there any autocompleter for version 4.5.7

### ISSUE THREAD

**Issue by developeronboard** [tinymce/tinymce#5614]
I am using V4.5.7 is there any autocompleter available for this version?

**Comment by lnewson** [comment]
No sorry, TinyMCE 5.0 was the first version to include the autocomplete feature/API. Also just as a reminder, as I mentioned in your other issue, TinyMCE 4.5 is no longer supported so we won't be able to provide help with any bugs you may find. As such we'd suggest upgrading to TinyMCE 5 if you need the autocomplete feature.
