### ISSUE TITLE
Using TinyMCE API to expand/collapse the toolbar

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5616]
**Is your feature request related to a problem? Please describe.**
For our product, we're using single-row toolbar which utilizes the  [TinyMCE toolbar's overflow button](https://www.tiny.cloud/docs/configure/editor-appearance/#sliding) for toolbar expand and collapse.  

Our requirement stipulates that the page with the TinyMCE needs to open with the toolbar expanded.  Because we didn't find any TinyMCE API to do this, we simulated clicking the overflow button on page-load, followed by setting the focus back to the first field on the data entry page.  However, this doesn't work because expanding the toolbar seems to be executed asynchronously because the focus is only set to the first field temporarily (after the call to click the overflow button), but immediately the focus is reset back to the toolbar.

So, is there a way to do either of the following?
1.  Pass in a config value to TinyME to tell it to render the toolbar expanded or collapsed?
2.  Call the TinyMCE API to open or collapse the toolbar?

I've upgraded to TinyMCE 5.2 and didn't see a way to do either of the above.

Thanks,
Brittany

**Comment by lnewson** [comment]
You're correct there's no way to currently do this sorry and we've actually had this requested before via https://github.com/tinymce/tinymce/issues/5041. This has more details though, so I won't close it and will mark it as a feature request so our PM team can assess it.

**Comment by lostkeys** [comment]
Issue #5259 (in the comments) contains a feature request for remembering the toolbar drawer state. Having this API would make such a feature easy to build.

**Comment by roy2651** [comment]
hey,guys：
is there any methods to collapse the toolbar, something on toolbar_mode floating, for example floating toolbar is blur which collapse the toolbar

**Comment by lostkeys** [comment]
@roy2651 Sorry there is no api:s for you to programatically toggle the floating toolbar.
