### ISSUE TITLE
Table plugin: override width of table cells.

### ISSUE THREAD

**Issue by Simkhotech** [tinymce/tinymce#5620]
Hi. While creating a new table, "width" style is added to every TD cell.

i.e.
```
<tr>
  <td style="width: 20%;">&nbsp;</td>
  <td style="width: 20%;">&nbsp;</td>
</tr>
<tr>
  <td style="width: 20%;">&nbsp;</td>
  <td style="width: 20%;">&nbsp;</td>
</tr>
```

How can i override default behavior?
I need to remove any width from TD or set width to "auto". (table_resize_bars is false, so user can't drag table width)
For tables i can use table_default_styles to override styles, but there is no option to override default style for new created cell.

Maybe there is such option exists or you can introduce it?
p.s. I use 4.7.4

**Comment by lostkeys** [comment]
One way is to use the invalid_styles option. My gut feeling says it wasn't ment to be used this way so there might be unwanted consequences, just sayin that as a disclaimer. But it looks like it gets the job done. See demo here: http://fiddle.tinymce.com/nhhaab

**Comment by Simkhotech** [comment]
@lostkeys 
thanks for a great solution! :)
