### ISSUE TITLE
tinyMce.triggerSave() & editor.save() not working

### ISSUE THREAD

**Issue by Sunilpb91** [tinymce/tinymce#5626]
I had tried to update textarea content  with tinymce editor (v5.2.2) content  

by  tinyMCE.triggerSave() and tinymce.triggerSave() in befor searialize() method  of ajax  but text area is not updates , i had also tried following 
  		  setup: function(editor) {
				editor.on('Change Keyup', function () {
							editor.save();
							//tinyMCE.triggerSave()   <-- also tried
        });
    }

dettailed issue is on 
https://stackoverflow.com/questions/61544953/autosave-content-of-tinymce-editor-on-change-event-with-laravel-7

**Comment by lnewson** [comment]
@Sunilpb91 I tried to reproduce this, however was unable to so it might be something in your setup that's causing the issue instead. As such we'll need a small reproduction case to be able to help further, and details about your browser/OS would also be helpful.

To get you started, here's the working fiddle I used to test based on the information you have provided: http://fiddle.tinymce.com/3hhaab/1

**Comment by Sunilpb91** [comment]
Problem has solved , i had include  app.js file where tinymce.init defined  **two times**  , after remove one file textarea content is updated without editor.save() and tinyMCE.triggerSave() method.
