### ISSUE TITLE
Editor event for toolbar_drawer

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#5639]
We are adding comments in tinymce, and using toolbar_mode :'sliding'.So need to change some positions.

Add an event whenever we open or close the toolbar_drawer.

none of the editor events work like change,click so thinking of binding an event.

**Comment by lostkeys** [comment]
Yep, I like that too. However, I can't give you any dates or anything for when it might be available.

**Comment by SIMRAN88** [comment]
Can you suggest any better solution for this??

**Comment by lostkeys** [comment]
You could listen on the `tox-toolbar__overflow--closed` and `tox-toolbar__overflow--open` classes maybe?

**Comment by SIMRAN88** [comment]
Sure, will try. Thanks
