### ISSUE TITLE
Contextmenu on right click does not display items except "Link"

### ISSUE THREAD

**Issue by MikeDanilov** [tinymce/tinymce#5646]
Currently when you set up `contextmenu` with list of items in configuration there is only one item displayed at the end after right click in editor. 

**Steps to reproduce:** (This is doesn't work in project and even in full feature example)
- Go to full feature example https://www.tiny.cloud/docs/demo/full-featured/
- Check JStab and see that `contextmenu: "link image imagetools table configurepermanentpen",`
- Go back to TinyMCE tab
- Right click on editor

**Actual Result**
Only `Link` item is in context menu.

**Expected behavior**
The link, image...etc items appear in the context menu.

TinyMCE version is 5.2.1.
OS: Windows 10 Pro
Browser: Chrome Version 81.0.4044.129

It works in TinyMCE v4 in full-featured example https://www.tiny.cloud/docs-4x/demo/basic-example/

**Comment by lnewson** [comment]
This is expected behaviour, as TinyMCE 4 had a hardcoded context menu that showed the same thing at all times. TinyMCE 5 however, is a proper contextual menu so the items it'll show depend on where you click.

As an example, click on the table in that demo and you'll see this:
![image](https://user-images.githubusercontent.com/1575550/81408874-5f114f00-9181-11ea-81b5-f89336a6880d.png)

**Comment by MikeDanilov** [comment]
@lnewson What I need is to be able to insert link/image/custom thing in empty text editor or in the middle of the text. Could it be possible? If so could you please provide working example or point me to the documentation that describe how to do that?

Thanks in advance.

**Comment by lnewson** [comment]
@MikeDanilov I think http://fiddle.tinymce.com/cihaab should do what you want? You may need to tweak what menu and contextmenu items you want shown, but that replicates something similar to the v4 context menus.

You can find a list of menu items available by default here: https://www.tiny.cloud/docs/advanced/editor-control-identifiers/#menucontrols

Also these docs about registering custom menu and contextmenu items might be useful to you:
- https://www.tiny.cloud/docs/ui-components/contextmenu/#registeringcontextmenusections
- https://www.tiny.cloud/docs/ui-components/menuitems/

**Comment by MikeDanilov** [comment]
@lnewson Thanks. That helped.
