### ISSUE TITLE
removeformat should remove style also from <style> tags

### ISSUE THREAD

**Issue by NitroBAY** [tinymce/tinymce#5648]
**Is your feature request related to a problem? Please describe.**
My user imports html from word (he already imported hundreds documents). Word defines CSS in tags <style>. He sometimes wants to remove the style of a tag (h1's color for example) he clicks on removeformat : nothing happens.
**Describe the solution you'd like**
Tinymce should search into <style> tags any selector that selects the element which you want to remove format and remove the CSS rule-set if its selector only matches the element we want to reset the format. Or if there are multiples elements selected by the CSS selector (not only one selected node) then find a way to exclude the selected node from the CSS rule (adding a class to node so you can exclude it with pseudo selector `:not` ?)
**Describe alternatives you've considered**
Implementing myself but the project is loooooong overdue so I may have to learn my users to manually edit the HTML so they modify what's inside the style tag.

If it's already implemented I'm sorry I searched for this feature.

**Comment by metricjs** [comment]
TinyMCE is not designed to deal with `style` elements. Styles should be inlined into the content. Depending on how you're "importing" the content into the editor, the Paste or PowerPaste plugins may be helpful. They can both take content with `style` tags and inline the styles, plus clean up the HTML a bit. Their parsing code can either be triggered by pasting in content or via the [API](https://www.tiny.cloud/docs/advanced/editor-command-identifiers/#paste). Here's a [Fiddle example](http://fiddle.tinymce.com/nihaab) of how to use the API.

Does that help?

**Comment by NitroBAY** [comment]
Okay, thank you.
I'm unsure what the problems were but I vividly remember that there were so many problems when copy/paste from microsoft words to tinymce.
So we ended up copying pasting the html files produced by words to tinymce (via code plugin).
I do not need this feature as much as I needed to (because we decided we do not need anymore to customize H1/H2/H3 colors so tinymce is not needed) but this feature may still be needed by other people.

**Comment by metricjs** [comment]
Hi @NitroBAY, I'm going to close this ticket as you mentioned you did not need this feature. However, I have made a note of the use case you mentioned and we will keep it in mind when considering related features for future TinyMCE releases. Thanks for reporting this!
