### ISSUE TITLE
Table styles are not being applied by default when TinyMce is installed via NPM

### ISSUE THREAD

**Issue by methoil** [tinymce/tinymce#5657]
In our project with TinyMce installed via NPM and bundled using webpack, the table styles are not being applied by default. When a table is added, the cells are smaller and black, and when selecting them, you do not get the expected visual feedback. But otherwise they appear to be working:
![image](https://user-images.githubusercontent.com/47762021/81605584-af65f800-939f-11ea-844c-764c236327ae.png)

I am able to fix this when I manually copy the styles from `tinymce/skins/content/default/content.min.css` and `tinymce/skins/ui/oxide/content.min.css` into the `content_style` setting, but this seems like a poor solution. The styles are being loaded in the project as I am importing them in the file where tinyMce is created and I see them in chrome dev tools. TinyMce is however appying the styling for the buttons/editor controls on its own, so I am confused as to what is going on. 

I would think that TinyMce should be able to load the default styles on its own, but it seems like this isn't the case for skins - I think the issue I'm seeing is described here in the docs - https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/#gettingtheskin.

So is this indeed the expected behavior? It seems really odd that some of the styles work on their own, but the skins require you to move the default TinyMce files into a local directory of your project. This is an issue for us because the build we're using doesn't allow us to extend the Web Pack config (which is pretty dumb), so we'd need to manually move the files.

TinyMce 5.2.2, Chrome 81

**Comment by lnewson** [comment]
@methoil this looks like TinyMCE is unable to load both the skin and default content CSS, however it is able to load the skin UI CSS. This is likely an issue with your bundling setup, so we'd need to see a reproduction case to be able to assist further, so could you please create a small repo, codesandbox or similar?

I should mention we do know the docs are making with how to load the content css, so there is https://github.com/tinymce/tinymce-docs/issues/1466 open in the docs repo to improve that. There's also a number of solutions other community members have found, that may help to resolve your issue. From that linked issue, I suspect https://github.com/tinymce/tinymce/issues/2836#issuecomment-544790987 is probably what is needed to solve this issue for you.

Also yes, it is expected as TinyMCE either has to be provided the content css inline, or it needs to load it from an external stylesheet. When using a module loader, most people don't copy the styles as they want to bundle/embed them which is where the above comes in. If you're not aiming to embed them, then you'll likely need to set the [`base_url`](https://www.tiny.cloud/docs/configure/integration-and-setup/#base_url) setting so TinyMCE knows where to load plugins, skins, themes, etc... from.

**Comment by methoil** [comment]
@lnewson Thank you for the info, we did find a way to load these styles via the `skin_url` and `content_css` properties without editing WebPack, though the WebPack solution you linked makes sense. So my reported issue is resolved, but I am still wondering why the TinyMCE setup works like this.

In the second comment you linked, the code is only loading in the same two files I mentioned into the `content_style` property
```
import contentStyle from '!!raw-loader!tinymce/skins/ui/oxide/content.css';
import contentStyle2 from '!!raw-loader!tinymce/skins/content/default/content.css';
```
and not `tinymce/skins/ui/oxide/skin.min.css`, which was working without adding into the config for me as well.   So it looks to me like all the behavior I saw, with only the skin UI CSS working by default, is expected. Why is the skin UI CSS loaded differently from the other two files?

I am not sure if I can make a reproducer as the build I am using is internal and I probably can't post it, but in any case I think my issue is solved, I am more curious about the implementation at this point.

**Comment by lnewson** [comment]
@methoil, it basically comes down to how TinyMCE sandboxes the content you edit. Before I get into that though, I want to clarify with you what the 3 different CSS files are used for:
- `skins/ui/oxide/skin.css` - This file is loaded on the page and has all the styles for TinyMCE's UI elements.
- `skins/ui/oxide/content.css` - This file is loaded within the iframe and contains styles for UI elements rendered within the content (eg the resize handles for tables, images, etc...).
- `skins/content/default/content.css` - This one isn't needed and should realistically be replaced with whatever your websites content CSS is. This file is just the default or template used as a placeholder more than anything. However, this file or the file used from your site is loaded within the iframe and will make the content appear the same as on your site.

So back to the iframe, that's done to make sure nothing seeps through (styles, javascript, etc...) for the content you're editing. Now since it's within an iframe, you cannot just include the CSS to use within the iframe on your page like you can with `skin.css` and it has to be available to load externally or for TinyMCE to inject. So that means either hosting it externally or embedding it using the `content_style` setting.

As for the reproduction case, there's no need for that if you have it working. Anyways, hopefully that's helped to clear up why you can't just include the content styles within the bundle like you can with the UI styles.

**Comment by crustamet** [comment]
I have the same problem, i have this setup if i dont use all _url setup
i recieve error that is trying to load this

assets/libs/tinymce/plugins/print/pluginundefined.js 

instead of assets/libs/tinymce/plugins/print/plugin.min.js 

i had to rename the plugins to that to work properly LOL

	$(function () {
		tinymce.init({
			selector:'#tinymce',
			toolbar_mode: 'sliding',
			plugins: 'print',
			// toolbar_sticky: true,
			min_height: 350,
			base_url: base_url+'/assets/libs/tinymce/',
			theme_url: base_url+'/assets/libs/tinymce/themes/silver/theme.min.js',
			skin_url: base_url+'/assets/libs/tinymce/skins/ui/oxide',
			// plugins_url: base_url+'/assets/libs/tinymce/plugins',
			content_css : base_url+'/assets/libs/tinymce/skins/content/default/content.min.css',
			image_caption: true,
			image_advtab: true,
		});
	});

**Comment by crustamet** [comment]
Yes as it seems the suffix variable was not set, i had to see the cloud settings how the heck is working so i find this varriable in there and put it and now i can remove all _url out.

**Comment by methoil** [comment]
@lnewson Thanks for the explanation, that clears things up. I had noticed that some of TinyMCE was appearing inside of an iFrame, but I wasn't sure why. And I didn't realize that it would be interfering with the loading of the css. Also good to know that the `default/content.css` might be good to replace.

@crustamet That's an odd error, though I only needed to set `theme_url`/`content_css` to get the editor styling working. Though your setup sounds different than mine, seems like you may be pulling from the main tinyMce CDN, in which case I don't think you'd need to set any _url's, which looks like what you wound up doing.

**Comment by lnewson** [comment]
Yeah, we're aware we need to improve our documentation with regards to bundlers or module loaders, as it's missing a number of important things (such as the items mentioned here). It's in our docs team backlog, but they are a bit tied up with other things atm sorry.

Anyways, I'm glad to hear that helped clear things up :+1:
