### ISSUE TITLE
On Bold,Italics,Underline select under toolbar section,char count(wordCount plugin) updated to 1 even when no text present

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#5659]
When editor is empty -> select the Bold from toolbar and check char count, its updated to 1 whereas it should update when user starts typing.

Tinymce 5.2.1.

I want to know if this is an expected behaviour because logically there is no character so it should return zero.

**Comment by lnewson** [comment]
@SIMRAN88 that's definitely not expected behaviour, so thanks for reporting that bug!

It looks like  the wordcount plugin isn't filtering out our internal caret characters when it's calculating the character count. I'll log an internal issue to get that fixed.
