### ISSUE TITLE
Autolink plugin improvement

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#5664]
Autolink is an excellent feature of Tinymce, but it needs an improvement (even as an option only): when the user edits the link, the `href` should be updated with the new text. 

Right now, if you have a auto linked text: `https://site.com` and edit it to `https//site2.com`, the `href` attribute of the link will stay `https://site.com`

**Comment by lostkeys** [comment]
This is expected. The autolink simply adds the url in the displayed text as well. There is no connection between the text displayed and the url once the link has been resolved. And making some sort of smartness that would figure out that when you edited the link text, you also ment to edit the url too will probably cause a lot of headache trying to handle all edge cases.
