### ISSUE TITLE
Remove Bullet lists on clicking remove format button

### ISSUE THREAD

**Issue by samkcdev** [tinymce/tinymce#5668]
Hi Team,
Right now it's not possible to remove bullet points on clicking remove format button.
Is there a workaround for this. I used the following to make it work, it removes the ul and li
but the whole text comes in one line.
```
 formats: {
    removeformat: [
 { selector: 'ul,li', remove: 'all' },
]}
```
Please help me to find a solution for this.

**Comment by lnewson** [comment]
This is expected as lists are not formatting and instead are structured content. Ideally, you probably should look at removing lists by using the `RemoveList` command if you want to remove a list (e.g. `editor.execCommand('RemoveList')`).

However, if you absolutely must use the formatter then you can probably do something like this: http://fiddle.tinymce.com/Qihaab. Just be aware though, as already mentioned the formatter is not designed for this sort of things so your results may vary and I'd suggest using the command instead.

**Comment by samkcdev** [comment]
Thanks! @lnewson will try these out.
