### ISSUE TITLE
For inline mode in "a" element editor remove container

### ISSUE THREAD

**Issue by maksymKyselyov** [tinymce/tinymce#5674]
Editor remove inline mode container after delete all content in `<a></a>` element.

I use React and I have element with "a" tag. Element have anchor:
```<a href={`#menu${tabContainerId}-${index}`} className={`pbi-tab-title-${uuid}`}></a>```

For this element I need inline editor. My code for init editor:
```
<Editor
    init={{
        selector: `.pbi-tab-title-${uuid}`,
        menubar: false,
        inline: true,
        toolbar: 'undo redo | forecolor',
    }}
    initialValue={config.title}
    value={config.title}
    onEditorChange={handleChangeTitle}
/>
```

If write content and then delete it whole editor remove my link which was a container.
Link to fiddle: [http://fiddle.tinymce.com/Xihaab](http://fiddle.tinymce.com/Xihaab)

I use Chrome v. 81.0.4044.129

**Comment by lnewson** [comment]
@maksymKyselyov I'm unable to reproduce the issue the linked fiddle using the same version of Chrome. The anchor remains both when deleting all content and when calling `editor.remove()` so could you please provide further details about what your issue is?

**Comment by maksymKyselyov** [comment]
@lnewson sorry, I try reproduce this bug in fiddle and saw that everything was working fine. but I tried adding `display: block` to the styles of the `a` tag and saw that the element is deleted after deleting all the content
