### ISSUE TITLE
Sometimes dialog doesn't fit in viewport and content doesn't fit in dialog

### ISSUE THREAD

**Issue by halfninja** [tinymce/tinymce#5681]
**What is the current behavior? Describe the bug**

This may only affect HiDPI displays - I'm on Windows 10 with a 1920x1080 display set to 150% scale, which should be transparent to most web pages as they'll get virtual pixels but somehow it makes a large dialog, with enough content that scrolling is required, too big for the screen

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

https://codepen.io/halfninja/pen/mdeaPew

Screenshot with browser at 100%, dialog is clipped off
![image](https://user-images.githubusercontent.com/72052/82364188-d909c980-9a06-11ea-8656-e01efb1fcec2.png)

Screenshot with browser at 90% - dialog fits, but the content still can't be scrolled all the way to the bottom ("LAST WORD" not visible)
![image](https://user-images.githubusercontent.com/72052/82364225-e58e2200-9a06-11ea-9eec-14cedf141ab3.png)

**What is the expected behavior?**

The dialog fits inside the viewport, and the content can be scrolled to in its entirety.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested in Chrome 81 and Firefox 76 on Windows 10. Tried in a Browserstack session where there is no UI scaling and the dialog fits BUT you still can't scroll down to see all the content.

**Comment by lnewson** [comment]
Thanks @halfninja for reporting this and I can confirm this also occurs if the viewport is 650px or less.

**Comment by robertsoniv** [comment]
@lnewson I noticed this behavior too - seems like the only time this bug occurs is when you specify `dialog.size = 'large'`

**Comment by mdgilene** [comment]
+1 experiencing this issue as well. Again only while dialog size is 'large'
