### ISSUE TITLE
TinyMCE trims all the whitespace character automatically, how to turn it off?

### ISSUE THREAD

**Issue by peterzhangsnail** [tinymce/tinymce#5685]
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate TinyMCE into my project which is designed to be a WYSIWYG tool of translating standard specification docs. As we all know, there are some whitespace characters in these docs and if you trim them all away, there may be a huge impact on the layouts and cause a lot of file conflicts when doing a merge. 
Here's a simple [demo](http://fiddle.tinymce.com/jjhaab/1)
**Describe the solution you'd like**
Make the trimming functionality configurable.
**Describe alternatives you've considered**
Is there any chance that we can turn off the trimming using a plugin already exists or writing a new one on our own?

**Comment by lnewson** [comment]
@peterzhangsnail this has nothing to do with TinyMCE and is native HTML and browser behaviour. I've updated your fiddle to remove TinyMCE so that you can see the same happens natively: http://fiddle.tinymce.com/jjhaab/2

**Comment by peterzhangsnail** [comment]
@lnewson I'm saying that after you click the submit button, the `HTML output from post` content in the `Post dump` section has been trimmed.
You can tell the difference from the zip pakage below:
[Desktop.zip](https://github.com/tinymce/tinymce/files/4659882/Desktop.zip)
In this package, the `test.html` is the tinyMCE-free doc and there's a script print its innerHTML to the console. Meanwhile, the `response.html` is the response from dump.php that I copied from chrome, also add a scirpt to it to show the innerHTML of the key element. 
How I copy the response.html:
![copy](https://user-images.githubusercontent.com/20182319/82508682-66007000-9b38-11ea-91f9-7db84a289826.png)
And this is the difference of console output between two files:
![test](https://user-images.githubusercontent.com/20182319/82508782-b4157380-9b38-11ea-8bff-21cf933259c9.png)
![response](https://user-images.githubusercontent.com/20182319/82508791-bb3c8180-9b38-11ea-9f5b-5a3c55e3ec3e.png)

**Comment by peterzhangsnail** [comment]
@lnewson Here's an [update](http://fiddle.tinymce.com/jjhaab/5) of your demo,maybe it is helpful to explain what I mean.

**Comment by lnewson** [comment]
I haven't had a chance to look into this more, so I'll reopen for now. However remember that TinyMCE is a WYSIWYG editor so it's goal is not to preserve HTML input verbatim, it's about keeping the content appearing the same. Since all of that markup is collapsible whitespace, it will not be maintained while editing and we are unlikely to implement such feature.
