### ISSUE TITLE
icon not found

### ISSUE THREAD

**Issue by June0611** [tinymce/tinymce#5687]
**What is the current behavior? Describe the bug**

![image](https://user-images.githubusercontent.com/16040781/82530553-2d7c8880-9b70-11ea-9dca-a83cc8ec8e19.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Nothing changes, just repackage, and then this happens

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

5.2.1

**Comment by lnewson** [comment]
@June0611 can you please include a way to replicate the issue? In TinyMCE 5.2.1 the icons are embedded in core, so it'd be quite surprising to see that issue without manually removing them from the registry.

If you're using TinyMCE 5.3.0, which was only released a couple hours ago, then it now has a the icons in a separate file `icons/default/icons.js` or `icons/default/icons.min.js` you'll need to make sure you copy across when deploying TinyMCE.

**Comment by June0611** [comment]
> @June0611 can you please include a way to replicate the issue? In TinyMCE 5.2.1 the icons are embedded in core, so it'd be quite surprising to see that issue without manually removing them from the registry.
> 
> If you're using TinyMCE 5.3.0, which was only released a couple hours ago, then it now has the icons in a separate file `icons/default/icons.js` or `icons/default/icons.min.js` you'll need to make sure you copy across when deploying TinyMCE.

抱歉,当前引用的版本是5.3.0 ,已经解决了,非常感谢

**Comment by June0611** [comment]
> @June0611 can you please include a way to replicate the issue? In TinyMCE 5.2.1 the icons are embedded in core, so it'd be quite surprising to see that issue without manually removing them from the registry.
> 
> If you're using TinyMCE 5.3.0, which was only released a couple hours ago, then it now has the icons in a separate file `icons/default/icons.js` or `icons/default/icons.min.js` you'll need to make sure you copy across when deploying TinyMCE.

Sorry, the current quoted version is 5.3.0, which has been resolved, thank you very much

**Comment by lugosium** [comment]
Hello @lnewson,

Is there a way or option to activate to get the old behaviour, not load the icons via another request?

Thanks

**Comment by lnewson** [comment]
@lugosium it's a build time thing, so there's no setting. However, you can just manually bundle the icons JS with the TinyMCE JS. eg:
```
cat tinymce.min.js icons/default/icons.min.js > tinymce.full.min.js
```

If you're using a module loader, just be sure to include something like this:

```
import 'tinymce/icons/default`;
```

Note: The above will be added to our docs when 5.3 is released to enterprise.

**Comment by lugosium** [comment]
Working like a charm! Thank you very much.

**Comment by pavel-mailpoet** [comment]
@lnewson when using the version with module loader `import 'tinymce/icons/default`;` I get an error: `Uncaught ReferenceError: tinymce is not defined` How to fix that?

**Comment by arnaudbey** [comment]
@pavel-mailpoet using require('tinymce/icons/default') dit the job for me
