### ISSUE TITLE
right to left direction lists plugin not working properly

### ISSUE THREAD

**Issue by ahmedosama5200** [tinymce/tinymce#5693]
lists don't work properly with right to left direction. There is not indent and also text is not aligned to right.

I use tinymce version 5

**Comment by ltrouton** [comment]
I am unable to reproduce the issue you have noted so If you could note the browser you are using and provide a [fiddle](http://fiddle.tinymce.com/baaaab) that allows the issue to be reproduced, that would be very helpful. Thanks.

**Comment by ahmedosama5200** [comment]
here is a picture
https://ibb.co/wW9VNqL

I used google chrome and took this picture with your demo editor here https://www.tiny.cloud/docs/demo/full-featured/
