### ISSUE TITLE
Code editor not editable

### ISSUE THREAD

**Issue by Sicos1977** [tinymce/tinymce#5698]
**What is the current behavior? Describe the bug**
When I view the HTML code then it looks like it is opened as readonly. I cant select or change anything in the editor

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
That I can edit the html

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest chrome, latest tinymce, never used tinymce before so I dont know if this has worked before.

![image](https://user-images.githubusercontent.com/6692947/82815763-202a0b80-9e9a-11ea-807a-8e1586d182c6.png)

**Comment by Sicos1977** [comment]
This is how I init tinymce from a codebehind file in an asp.net webforms app

```csharp
        #region SetTinyMce
        /// <summary>
        /// Schrijft scriptcode naar de webpagina om tinymce te binden aan de textarea met
        /// het opgegeven <paramref name="ctrl"/> id
        /// </summary>
        /// <param name="ctrl"></param>
        private void SetTinyMce(Control ctrl)
        {
            var id = EditMode ? "editscript" : "texteditor" + ctrl.ClientID;

            ScriptManager.RegisterStartupScript(Page, GetType(), id,
               $"tinymce.remove('#{ctrl.ClientID}'); " +
                "tinymce.init({" +
               $"   selector: '#{ctrl.ClientID}', " +
                "   plugins: 'advlist anchor code codesample colorpicker contextmenu fullscreen hr insertdatetime nonbreaking paste preview searchreplace table', " +
                "   language: 'nl', " +
                "   branding: false, " +
                "   height: '400px', " +
                "   skin: 'email2storage', " +
                "   setup: function(editor) {" +
                "      editor.on('blur', function(e) {" +
               $"         $('#{ctrl.ClientID}').val(editor.getContent());" +
                "      });"+
                "   }" +
                "});", true);
        }
        #endregion
```

**Comment by Sicos1977** [comment]
It seems that I had to add this to my page.

```javascript
// Prevent Bootstrap dialog from blocking focusin
$(document).on('focusin', function(e) {
  if ($(e.target).closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
    e.stopImmediatePropagation();
  }
});

```

**Comment by salmanarshad321** [comment]
> It seems that I had to add this to my page.
> 
> // Prevent Bootstrap dialog from blocking focusin
> $(document).on('focusin', function(e) {
>   if ($(e.target).closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
>     e.stopImmediatePropagation();
>   }
> });

you're a life saver lol
