### ISSUE TITLE
Inline Paste Notification can't be closed in Firefox on OSX

### ISSUE THREAD

**Issue by matzesa** [tinymce/tinymce#5702]
**What is the current behavior? Describe the bug**
In inline mode with Firefox when I click 'Paste' (in menubar) a notification is shown. I can't close this notification because the editor gets closed (an the notification unvisible) when clicking the close button of the notification (when the notification gets the focus).

**Please provide the steps to reproduce and if possible a minimal demo of the problem**
* http://fiddle.tinymce.com/Ljhaab
* Activate editor by clicking the text
* Click 'Edit' in menubar
* Click 'Paste' (-> Notification to use keyboard shortcuts is shown)
* Try to close the notification

**What is the expected behavior?**
Interacting with the notification (closing, marking text) won't close the editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tinymce 5.3.0 in Firefox 76.0.1 on OSX

**Comment by ltrouton** [comment]
Thanks for the report. I can confirm that the notification cannot be closed on OSX, Firefox. I have logged a ticket internally so we can investigate this. We will let you know when we have any updates.

**Comment by lnewson** [comment]
TinyMCE 5.4.2 has just been released to the community, which includes a fix for this issue. Please let us know if you continue to experience any further issues.

**Comment by matzesa** [comment]
Thanks, works fine.
