### ISSUE TITLE
TinyMCE v5.3.1 want to load a modern theme

### ISSUE THREAD

**Issue by arnofly** [tinymce/tinymce#5719]
Same error on Chromium based browsers or Firefox.

![image](https://user-images.githubusercontent.com/45882853/83440733-baafbf00-a445-11ea-8d02-7f1b512206b2.png)

Create an empty JS file on this path seem to fix the bug.

Thx

**Comment by lnewson** [comment]
@arnofly this will almost definitely be an issue with your configuration. I suspect you'll find you have `theme: 'modern'` in your TinyMCE init configuration. If you don't have that, then please provide a way to reproduce the issue, or at the very least could you please provide your TinyMCE configuration.

**Comment by lnewson** [comment]
I should add if you're migrating from TinyMCE 4, which this error suggests you might be, there's our v4 migration guide here: https://www.tiny.cloud/docs/migration-from-4x/.

To fix this specific issue though, I'd suggest just removing the theme from your configuration. Either that or change it to `theme: 'silver'`.

**Comment by arnofly** [comment]
Hi,
You are right, it's was my fault, so sorry ;)

I'm working on a quite big project. The new version of TinyMCE that replace the old one has the same path. TinyMCE v4 was initialized on textarea tags from another file that I had forgotten during my tests yesterday.

So, now we know why all the textarea tags on my project was stylized with "visibility:hidden" and why the moden theme was called.

TinyMCE is great, thank you for your job!
