### ISSUE TITLE
Expose core api to enable better support for plugin authors

### ISSUE THREAD

**Issue by crhistianramirez** [tinymce/tinymce#5720]
**Is your feature request related to a problem? Please describe.**
We'd like to extend the functionality of an existing plugin which depends on code from the core api ie things in 'tinymce/core/api/'.

**Describe the solution you'd like**
It would be useful as a plugin author to also be able to import these core apis so I don't have to re-implement it from scratch. At the moment it only allows me to import icons, plugins, skins and themes.

**Describe alternatives you've considered**
I will work around this by re-implementing functionality separately

**Comment by robertsoniv** [comment]
@crhistianramirez I believe you can do this:
```tsx
import tinymce from "tinymce";

//all core apis are available at their documented path
tinymce.dom.DomQuery('#element_id')
var parser = new tinymce.html.SaxParser({
   ...options
})
```

**Comment by crhistianramirez** [comment]
Oh neat. I guess the only piece that would might be missing is the types but I can live without that
