### ISSUE TITLE
Dialog with input followed by many checkbox controls (enough to trigger scrolling) makes checkboxes below scroll "unclickable"

### ISSUE THREAD

**Issue by robertsoniv** [tinymce/tinymce#5721]
**What is the current behavior? Describe the bug**
Creating a custom `panel` dialog with an `input` control followed by enough `checkbox` controls to trigger scrolling behavior results in the `input` getting focused on any `mousedown` events (including checkbox clicks). This results in the editing user not being able to check any checkbox controls outside of the dialog's initial visible area. The user can still scroll to the bottom of the dialog, but once you press down your mouse, the search input is focused and the dialog is auto-scrolled to the top, resulting in the checkbox change never getting triggered. 

Reason I think this happens on any `mousedown` is if you click and hold on a checkbox control that was _initially visible_, you can see the input at the top gains focus again until `mouseup` event at which point the checkbox gains focus and the change event occurs.

**Please provide the steps to reproduce and if possible a minimal demo of the problem**
[Fiddle Link](http://fiddle.tinymce.com/3khaab/1)
Steps to reproduce:
- Create a custom dialog with 1 input followed by 20+ checkboxes
- Open the custom dialog
- Attempt to click on checkboxes below the dialog's initial visible area

**What is the expected behavior?**
I expect all checkboxes to gain focus / trigger `onChange` when clicked and the scroll position of the dialog to remain constant.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE v5+
Browser: Gogole Chrome Version 83.0.4103.61 (Official Build) (64-bit)
OS: Windows 10 Pro version 1903

**Comment by lostkeys** [comment]
Your fiddle demo uncovered an issue with the CSS in Safari as well... 

<img width="503" alt="Screen Shot 2020-06-02 at 08 55 35" src="https://user-images.githubusercontent.com/3122929/83489660-0c406400-a4af-11ea-93f8-f18196ef7238.png">
