### ISSUE TITLE
Tinymce 5 sets spellcheck attribute to false on main body element

### ISSUE THREAD

**Issue by freeman-g** [tinymce/tinymce#5743]
**What is the current behavior? Describe the bug**

Prior to upgrading to v5, Chrome would show a red underline for misspelled words in the Tinymce editor. After upgrading, this stopped working and I discovered that it was because the spell check attribute is set to false:

```<body id="tinymce" class="mce-content-body " data-id="actionTakenAll" contenteditable="false" spellcheck="false">Test content</body>```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

This is the config I'm using:

```
<script id="tiny-script" src="https://cdn.tiny.cloud/1/apikey/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
```

```
 tinymce.init({
          menubar: false,
          target: this.$el,
          height: '400',
          plugins: 'preview lists tinymcespellchecker powerpaste',
          forced_root_block: '', 
          powerpaste_allow_local_images: true,
          powerpaste_word_import: 'clean',
          powerpaste_html_import: 'clean',
          browser_spellcheck: true,
          spellchecker_dialog: true,
          spellchecker_languages: 'US English=en',
          spellchecker_active: false,
          spellchecker_on_load: true,
          spellchecker_whitelist: this.spellCheckDictionary,
          paste_as_text: false,
          fontsize_formats: '8pt 9pt 10pt 11pt 12pt 14pt 18pt 24pt 36pt',
          convert_fonts_to_spans: false,
          toolbar: 'spellchecker undo redo | bold italic underline strikethrough | fontsizeselect  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | preview image code',
        })
```

**What is the expected behavior?**

I expect the main body element to have spellcheck=true since the config uses browser_spellcheck: true.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE v5, Chrome 83. Yes, this worked prior to upgrading to 4.

For what its worth, I'm working around this issue with the following event, but would prefer not to have to do this.

```
          init_instance_callback: (editor) => {
            // after the v5 upgrade, the HTML 5 spellcheck was set to false
            // preventing chrome's naitve red-underline spell checking. This reenables it.
            let body = editor.$()
            body.context.spellcheck = true
          }
```

**Comment by HAFRMO** [comment]
Hello

After looking through your provided settings it'd seem that you are using PowerSpell (tinymcespellchecker). It's PowerSpell itself that is adding the attribute, possibly because it and the default spellchecker are not designed to be used at the same time.

As Powerspell is a premium plugin I'd suggest you to reach out to our support at https://support.tiny.cloud/hc/en-us to see if they can give you proper assistance with this plugin as the github is for the community editions.
