### ISSUE TITLE
I can't find what I'm looking for: advanced/index.md

### ISSUE THREAD

**Issue by ontoconsult** [tinymce/tinymce#5745]
Hi, 
I have used Namo Web Editor for years until it dropped dead after a Windows 10 update.
What I miss most is that you could draw, inside an image, a rectangle or ellipse and link that to a URL.
I believe that is called an area tag now, but they had it years earlier.
Does TinyMCE support that as well? If not, do you know a competitor who does? To me it is the essential selection criterium.
Regards, Hans (Netherlands)

**Comment by lostkeys** [comment]
No, unfortunately TinyMCE does not contain any functionality to draw and configure image map areas. You'll have to build that feature yourself as a custom plugin.

**Comment by ontoconsult** [comment]
Hi Fredrik,

 

I am not a software geek. What would be the order-of-magnitude cost when someone would write that code?

 

Regards, Hans

**Comment by lostkeys** [comment]
It depends. I first want to point out that TinyMCE is a rich text component for developers to integrate into their software. I have no experience with Namo WebEditor but googeling it, it looks like a website builder which TinyMCE is not, but it can certainly be used by software geeks to build services like Namo WebEditor, but then TinyMCE would be a technology among many others to achieve a complete product.

You could look into services like [Squarespace](https://www.squarespace.com), [Wix](https://www.wix.com) or [Webflow](https://webflow.com) which offers great tools for non-coders to build web sites. Or you could explore an open source technology like [GrapesJS](https://grapesjs.com)

**Comment by ontoconsult** [comment]
Thanks, Fredrik!

Regards, Hans
