### ISSUE TITLE
The execCommand method generates extra <p> at the beginning and end of the article

### ISSUE THREAD

**Issue by Silencer-1984** [tinymce/tinymce#5747]
1. In version 4.92

2. When I use the execCommand editor, which assigns null values, I generate extra <p> at the beginning and the end

3. 
![image](https://user-images.githubusercontent.com/31053595/83986449-73f32500-a96f-11ea-91cf-2b34d62df381.png)

4.   I use  `tinymce.execCommand('mceInsertContent', false, this.html)`

5. 
![image](https://user-images.githubusercontent.com/31053595/83986544-c46a8280-a96f-11ea-97ae-73023328f913.png)

6. This question will generate a lot of unnecessary elements when editing the article. I need the method execCommand to help me locate the cursor. I want to ask why and for what purpose.

This problem occurs after `forced_root_block: false` is set #4728 .So I can't use this method

**Comment by Silencer-1984** [comment]
This is an old project and I can't afford to run the risk of upgrading. I would like to get some help or help convince someone to upgrade.

**Comment by lostkeys** [comment]
I'm not sure I follow what the problem is and what you try to achieve. Can you perhaps try to [replicate the issue with a fiddle](http://fiddle.tinymce.com)

**Comment by lostkeys** [comment]
I actually ran into this issue today myself, and managed to create a fiddle.

Check out this fiddle:
http://fiddle.tinymce.com/Okhaab/3

Adding a custom element inserts an empty paragraph after the element. But a couple of conditions must apply:
1. The template must contain a custom element
2. The `extended_valid_elements` option must be present.
3. The `custom_element` option defines the custom element as a block

If I change any of these, the trailing paragraph stops appearing
