### ISSUE TITLE
the icon of toolbar is missing . it is not found

### ISSUE THREAD

**Issue by kqy520** [tinymce/tinymce#5752]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by kqy520** [comment]
the version is 5.3.1

**Comment by lostkeys** [comment]
Hi! You forgot to add a description. Please add one and reopen the issue, thx.

**Comment by lnewson** [comment]
https://github.com/tinymce/tinymce/issues/5687 might also be useful to you.
