### ISSUE TITLE
Provide a way to specify the default icon pack URL

### ISSUE THREAD

**Issue by clabough** [tinymce/tinymce#5759]
**What is the current behavior? Describe the bug**

tinymce is trying to load the default icons from multiple locations - which may be the issue that others with missing icons are having. #5753 #5687 

My tinymce.js file is in my /css/tinymce/ folder, but it is trying to load the default icons from two locations:
1. /dist/ng/icons/default/icons.js (where my application bundles are in /dist/ng)
2. /css/tinymce/icons/default/icons.js

This is with *icons_url: "/css/tinymce/icons/default/icons.js"* in my init configuration.

Until I copied the tinymce icons folder into my /dist/ng folder, the icons were not showing.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/blhaab

Notice that in this repro that it attempts to load from two locations.

**What is the expected behavior?**

Icons loaded from one location - the one specified in init.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Chrome 83. TinyMCE 5.3.1

**Comment by lnewson** [comment]
@clabough that's expected, as `icons_url` is meant to be used for loading a custom icon pack, not for loading the default icon pack. As such you're now attempting to load the icon pack twice, once for the default and then another as if it was a custom icon pack. We currently don't have a way to specify the specific URL of the default icon pack.

Out of curiosity, if you use the [`base_url`](https://www.tiny.cloud/docs/configure/integration-and-setup/#base_url) setting instead and set that to `/css/tinymce` does that solve your issue? The base URL setting will specify where to load all plugins, icons and themes from by default.

**Comment by lnewson** [comment]
I'm going to mark this as a feature request either way, as we do need a way to specify the default icon pack URL, as there are edge cases where it will be useful (similar to the existing icons_url).

**Comment by ss2020a** [comment]
Could someone provide me a sample icons.js file please.  In the tinymce site I notice that I can use the properety as   

icons_url: 'https://www.example.com/icons/my_icon_pack/icons.js', // load icon pack  ,  

but do not notice any sample file or format of it.

Just a copy/paste of full icons.js with couple of line items would be helpful.

Thanks
