### ISSUE TITLE
Table as root element can be deleted

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#576]
For inline editing, when a table is the root element, it's still possible to delete the entire table by selecting all cells and running `mceTableDeleteCol`.

I've setup a fiddle to demonstrate the behavior in 4.2.7: http://fiddle.tinymce.com/zhfaab/1

To replicate:

1. Select all cells by clicking and dragging
2. Select Table > Column > Delete Column
3. The table is deleted

Does not occur with `mceTableDelete` or `mceTableDeleteRow`.

**Comment by claviska** [comment]
What commit fixed this? I know 4.2.7 addressed the table-as-a-root-element issue, but it's still possible to delete the table by using `mceTableDeleteCol`, either through `execCommand()` or the toolbar option.

I tested with the nightly and am still experiencing this behavior.

**Comment by spocke** [comment]
You are correct. This one wasn't fixed correctly. But I added a check for that now.
https://github.com/tinymce/tinymce/commit/c458873b0766d749053e2e200a1f8d99a8d5172d
