### ISSUE TITLE
removing by id not working correctly

### ISSUE THREAD

**Issue by DNWEIJ** [tinymce/tinymce#5761]
Using version:  5.2.0
**What is the current behavior? Describe the bug**
Removing of editors not working as expected. I am trying to remove specific editors via id. I track a list of ids then o a foreach and remove the editor.
It seems that some are removed and some are still there.
If a make a really simple test, i see the same behaviour. 
This simple test is:

In chrome browser console:
`>tinymce.editors`
gives me: 21 available editors
`(21) [Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, mce_38: Editor, mce_39: Editor, mce_40: Editor, mce_41: Editor, mce_42: Editor, …]`

when i execute the following command i expect to have no editors left anymore.

`> tinymce.editors.forEach(editor => editor.remove())`

requesting the number of available editors from tinymce:
`> tinymce.editors`
the result is:
`(10) [Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, Editor, mce_39: Editor, mce_41: Editor, mce_43: Editor, mce_45: Editor, mce_47: Editor, …]`

There are still 10 editors available.

repeating the:
`tinymce.editors.forEach(editor => editor.remove())`
will remove all editors at the end, so it seems to work  but not as expected.

I have noticed that when i have a breakpoint added on the edit.remove (so within the forEach) and i click 'next' slowly, meaning i actually create a delay having manually intervention, it works; the editor is removed and at the end the list is empty. But clearly, I cannot ask the user to go into debug mode :-). 

tinymce.minorVersion
"2.0"
tinymce.majorVersion
"5"

**What is the expected behavior?**
All editors should have been removed in 1 pass of the foreach

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 5.2.0 chrome

**Comment by trevorjay** [comment]
`forEach` becomes unpredictable when the underlying array is modified (as the call to `remove` does). If I understand your context correctly, you should be able to get the behavior you want by copying the editor array:

```
tinymce.editors.slice().forEach(ed => ed.remove()); 
```

This works for me in Chrome whereas using `forEach` behavior does indeed have issues.

**Comment by lnewson** [comment]
Also worth mentioning that `tinymce.editors` is deprecated and you should be using `tinymce.get()` instead. That will return a new array, instead of the underlying one.

**Comment by DNWEIJ** [comment]
Works!
Thnks!
