### ISSUE TITLE
I can't find what I'm looking for: configure/editor-appearance.md

### ISSUE THREAD

**Issue by GGKCoder** [tinymce/tinymce#5762]
How to disable/enable one button(bold) dynamically in toolbar?

**Comment by lincolndennis** [comment]
Here is a way to programmatically disable the bold toolbar button:
http://fiddle.tinymce.com/4mhaab/2

Docs:
https://www.tiny.cloud/docs/advanced/editor-command-identifiers/#listingcoreandplugineditorcommands
https://www.tiny.cloud/docs/api/tinymce/root_tinymce/#execcommand

Reach out on the Tiny Community forums if you have questions:
https://community.tiny.cloud/

...or if you are a Pro or Enterprise level TinyMCE customer, contact Support here:
https://support.tiny.cloud/hc/en-us
