### ISSUE TITLE
The caret does not moves when the buttons Shift+Enter are pressed after the link

### ISSUE THREAD

**Issue by fredure** [tinymce/tinymce#5781]
**What is the current behavior? Describe the bug**
When I insert a link into the field and when I click buttons Shift+Enter, the caret does not switch to the new line.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Configure the TinyMCE with the "paste" plugin.
2. Insert the link in the field.
3. Press buttons Shift+Enter.

Codepen: https://codepen.io/fredure/pen/pogEzxe

**What is the expected behavior?**
The caret moves to a new line by the first time.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version of TinyMCE - 5.2.0 (2020-03-14).
Browser - all.
OS - all.

This didn't work in previous version.

**Comment by DNWEIJ** [comment]
try to reproduce and it is working.
I went to https://codepen.io/fredure/pen/pogEzxe
paste a link ( you are not specifying one so took https://codepen.io/fredure/pen/pogEzxe) 
and press shift+enter. 
Caret is on the line below. 

I checked to actually use the link option from the menu, but that is not there, so the only thing i could think of was pasting a link and then press shift+Enter; and that is working...

**Comment by fredure** [comment]
Any link will do. If the link is shared like a hyperlink (with underline), then the problem is repeated. Your link is pasted like plain text and the problem did not reproduce.

**Comment by lincolndennis** [comment]
I can confirm this behavior in a standard Tiny Fiddle (http://fiddle.tinymce.com/baaaab): after pasting a link into the editor, the first time pressing shift+enter seems to have no effect. Pressing shift+enter a second time adds a line break.
