### ISSUE TITLE
Can't select all on iPad if first element isn't contenteditable.

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5783]
**What is the current behavior? Describe the bug**
Users can't select all from iPad native context menu if first element of editor isn't edtiable.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Visit http://fiddle.tinymce.com/2lhaab on iPad
2. Try to select all
 
**What is the expected behavior?**
Select all command works correctly

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Last version of TinyMCE, last version of Safari

**Comment by lostkeys** [comment]
I can confirm this being an issue with the desktop safari as well. Select all does not work properly. Typing characters appends them to the end, hitting enter removes all content but leaves two empty paragraphs.
