### ISSUE TITLE
How to integrate Keyman Web with Tiny MCE editor

### ISSUE THREAD

**Issue by ramesh-k** [tinymce/tinymce#5784]
How to integrate Keyman Web with Tiny MCE editor. Keyman supports more than 1000 languages.

https://keyman.com/developer/keymanweb/

https://help.keyman.com/DEVELOPER/ENGINE/WEB/current-version/

**Comment by DNWEIJ** [comment]
What is your requirment? for instance? 
Do you want to have a MCEEditor menu button to activate the keyboard?
Or do you just want to have the keyboard working? I think tinyMCE and keyboard can run next to each other and do not have to know each other. The keyboards fires  keyevents and tinyMCE (when focused on the input part) will just receive them....

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles integrating Keyman, then could you please include more details about what issue you're having and then we'll be happy to reopen this.
