### ISSUE TITLE
Ability to expand the selection to the current word

### ISSUE THREAD

**Issue by RamEsh3508** [tinymce/tinymce#5786]
I have to get a word from current caret position. Ex. 'Hello world!' If I have a cursor anywhere middle on 'Hello'. I have to select the whole word.

**Comment by DNWEIJ** [comment]
does this do the job? https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.selection/

**Comment by lnewson** [comment]
This isn't currently possible via a TinyMCE API. Some browsers do provide an API to do this though: https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify So you'd need to do something like this:
```
editor.selection.getSel().modify('move', 'foward', 'word');
editor.selection.getSel().modify('extend', 'backward', 'word');
```

Either way, I'm going to mark this as a feature request as I've seen it mentioned a few times.
