### ISSUE TITLE
Pagebreak plugin: add option to have only one page break

### ISSUE THREAD

**Issue by odraencoded** [tinymce/tinymce#5787]
Some CMS's only use a single pagebreak, dividing the summary of the article from the rest of the article. The pagebreak plugin could be extended to **set** where that single pagebreak is, rather than adding multiple pagebreaks to the same article.

Currently, if you click the pagebreak button and you already have a pagebreak in the article, it will add a second pagebreak.

An option could be added so that clicking the pagebreak button automatically removes the previous pagebreak before adding a new one, or moves the existing pagebreak to the cursor position instead of adding any one, either way limiting the number of pagebreaks in an article to one.

**Comment by lostkeys** [comment]
Thanks for your suggestion. Can you give some examples on implementations of this so we could investigate further?

Also, this is probably doable in TinyMCE today as you could manipulate the DOM pretty easily though our APIs.

**Comment by odraencoded** [comment]
Yes, I managed to modify pagebreak into a custom plugin to fit my needs. It uses HR instead of P/IMG.

http://fiddle.tinymce.com/Nlhaab

	editor.addCommand('customReadMore', function () {
		if(getLimitToSingle(editor)) {
			var nodes = editor.dom.select('hr.' + getReadMoreClass());
			var i = nodes.length, node;
			while (i--) {
				node = nodes[i];
				node.remove();
			}
		}
		editor.insertContent(getPlaceholderHtml());
	});
