### ISSUE TITLE
is there a way to change the status of custom toolbar button 

### ISSUE THREAD

**Issue by zhoufenfens** [tinymce/tinymce#5795]
**Is your feature request related to a problem? Please describe.**
I wanted to add a custom toolbar button in my editor, it looks like the fontsizeselect plugin, it has the drop down menu, I wanted to detect the current text status (like fontSize or bold ) and changed the text on my custom button , I used the 'editor.ui.registry.addMenuButton' to add my custom button to the toolbar, but I could not find a way to change the button text dynamically base on where the caret located.
**Describe the solution you'd like**
change the text by operate dom node
**Describe alternatives you've considered**

**Comment by lostkeys** [comment]
Sorry, that is currently not possible. We'll notify you here when/if it becomes available.
