### ISSUE TITLE
Bug using GBoard keyboard on ie. Motorola or xiomi mobiles

### ISSUE THREAD

**Issue by TheChris1969** [tinymce/tinymce#5810]
**What is the current behavior? Describe the bug**

When using the GBoard keyboard in Android on a Motorola mobile and on xiomi Mi Note 10 bzw. Mi 6. (not on Samsung hardware), and autocorrect is activated.

Description:
1) Write in editor:
This is a bug.
Here is another bug.

2) Position cursor to begin of first sentence (in front of "This")

3) Write "Test" and hit the space bar on the keyboard

4) you see something like: 
ThisTThis

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

The behavior is documented here: https://bit.ly/3cLpXNk

**What is the expected behavior?**

Words should not be overwritten

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

v5.x of TinyMCE, when using the GBoard keyboard in Android on a Motorola mobile and on xiomi Mi Note 10 bzw. Mi 6. (not on Samsung hardware). Autocorrect has to be activated.

![image](https://user-images.githubusercontent.com/67310035/85372001-776eda80-b531-11ea-83f0-0e85b5ce4a16.png)

![image](https://user-images.githubusercontent.com/67310035/85372024-7fc71580-b531-11ea-86ed-3607557e3a44.png)

**Comment by lostkeys** [comment]
Can you verify this being an issue with the latest version of TinyMCE? Does this also happens when using the default keyboard (not gboard, assuming that being a third party keyboard.)?

**Comment by TheChris1969** [comment]
Hi,
yes, the issue is seen on version 5.3.2 (but also in v 4.x).
Users using the default keyboard did not report the problem, seems only to be seen on Gboard (which is used by really many Android users, according to nearly 6 Million reviews)
Thanks,
Chris
