### ISSUE TITLE
Source Code window doesn't honor text cursor position of main window

### ISSUE THREAD

**Issue by dgmlr** [tinymce/tinymce#5830]
**What is the current behavior? Describe the bug**

Source Code window always opens with text cursor at the last text position ("code" plugin) or first text position ("advcode" plugin), irrespective of where the cursor is in the main window.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Create text in a TinyMCE instance with the "code" or "advcode" plugin.
2. Position the cursor in the middle of the text.
3. Open the Source Code window. Note that the text cursor is not in the same position (it is either at the start or end of the window). 

**What is the expected behaviour?**

I expected the text cursor position to be maintained the same in the Source Code window as in the main window. This would be obviously more useful than the current behaviour, and would be consistent with the behaviour of other similar systems.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I've confirmed this behaviour with TinyMCE 5.3.2 and Chrome 80.0.3987.132.

I've also seen the different, expected behaviour in another version of TinyMCE, the one that is integrated with ServiceNow (at least up until their "New York" release).

**Comment by lincolndennis** [comment]
I have confirmed that this is currently expected (albeit, not identical) behavior in both our `code` and `advcode` plugins. While we do plan to include cursor sync functionality in an upcoming release of `advcode`, we don't have any plans to change the behavior of the `code` plugin at this time.
