### ISSUE TITLE
Place the "Save" and "Fullscreen" buttons in the corners of the article editor.

### ISSUE THREAD

**Issue by korenevskiy** [tinymce/tinymce#5851]
Please read this ISSUE.
https://github.com/joomla/joomla-cms/issues/29949
.
I ask the developers of the plugin for CMS Joomla to make corrections.

**Comment by lostkeys** [comment]
Here is how you configure the toolbars:
https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar

Look here for a technique to right align buttons: https://tinymce.github.io/tinymce-demos/tinymce-basics/right-aligned-toolbar-button.html

Hope that helps!

**Comment by korenevskiy** [comment]
@lostkeys You are welcome. I ask You to understand the problem differently.
I am not saying that I want to solve the problem just for myself. I inform you that such a change should be made initially. Buttons in the corners of the panel should be set by default.
Do I need to collect 100(or 1000 000) votes for Yours?, or will we as developers think and decide that this will really be a great idea for all users?

**Comment by korenevskiy** [comment]
@lostkeys 
I didn't find a TinyMCE repository for Joomla on GitHub.
I know that fixes should only be made in the Joomla extension.

**Comment by lostkeys** [comment]
Sorry, I don’t know who maintains that Joomla integration. You are correct in that the changes has to be made by them.
