### ISSUE TITLE
5.4.0: forced_root_block: '' will always insert <p> after setContent()

### ISSUE THREAD

**Issue by hy-net** [tinymce/tinymce#5852]
Init tinymce with the following options.

	force_br_newlines: true,
	force_p_newlines: false,
	forced_root_block: '',

Everything is working as expected. But once I call

	tinymce.get("textarea").setContent("");    // empty string

The root element < p > will be inserted to whatever I type later.

**Comment by metricjs** [comment]
@hy-net Sorry, we can't figure out how to replicate this. Could we please know:

- Is this a good example of how you've set up the editor? http://fiddle.tinymce.com/Tnhaab
- What browser are you using?
- What operating system are you using?
- What version of TinyMCE are you using?

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please reply with the information requested above and we'll reopen this.
