### ISSUE TITLE
I can't find what I'm looking for: configure/contributing-docs.md

### ISSUE THREAD

**Issue by CarolineFell** [tinymce/tinymce#5858]
Hello! Could you help me with highlighting the syntax not in the editor itself but on the web page where the code entered in editor is published? Is there any opportunity to highlight such bulks of code in text on web page after publishing the article?

**Comment by trevorjay** [comment]
If what you're wanting to do is include code listing in your output document, you might want to look at the [code sample plugin](https://www.tiny.cloud/docs/plugins/codesample/).

**Comment by lnewson** [comment]
Also worth noting, if you are already using the `codesample` plugin, then make sure to include Prism.js or similar on your published page. See [Using Prism.js on your web page](https://www.tiny.cloud/docs/plugins/codesample/#usingprismjsonyourwebpage) for more details.

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then please feel free to reply with more information and we'll reopen this.
