### ISSUE TITLE
Editor Floating Panels Detached on Scrolling Container

### ISSUE THREAD

**Issue by amills17** [tinymce/tinymce#5861]
**What is the current behavior? Describe the bug**
I have an instance of the TinyMCE editor on a scrolling container. 
I am running into an issue where the float panels (dropdowns) are positioned incorrectly when you scroll the panel. 

**Related issue in GitHub:**
https://github.com/tinymce/tinymce/issues/3592

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
There doesn't appear to be any workarounds for this issue in TinyMCE 5.

**Comment by lnewson** [comment]
Yes, this is something we're aware of however it's a new feature and not something that we've had time to schedule yet. This is already being tracked via https://github.com/tinymce/tinymce/issues/5097 so I'm going to close this as a duplicate.
