### ISSUE TITLE
define custom label like h1/h2...

### ISSUE THREAD

**Issue by wideweide** [tinymce/tinymce#5862]
**Is your feature request related to a problem? Please describe.**
I defined a label topic,some code like this:

```
      formats: {
          topic: { block: 'topic' },
        },
        style_formats: [
          { title: 'topic', format: 'topic' },
        ],
```

when I write somethins as topic,press enter,it will be :
```
<topic>line1,press enter</topic>
<topic>new line</topic>    ---- I want : <p>new line</p>

```
**Describe the solution you'd like**
I don't know..   Could I do this?

**Describe alternatives you've considered**

**Comment by metricjs** [comment]
Related to #5214. To copy the question from there: 

The newblock event could be used to update/change the custom element back into a p. Alternatively, can the custom tag always be inline with a p block? That should resolve the issue.

**Comment by wideweide** [comment]
> This isn't currently a feature of TinyMCE. Related to #5214. To copy the question from there:
> 
> The newblock event could be used to update/change the custom element back into a p. Alternatively, can the custom tag always be inline with a p block? That should resolve the issue.
> 
> If not, we could make this a feature request.

Is there some code to show newblock ? 

I try  to set <p><topic>abc..</topic></p>, but the ps diappeared...


I write a keyup event , but seems not smart ...

 ```
   onKeyUp () {
      let selection = this.$refs.tinyEditor.editor.selection
      if (!selection) return
      let node = selection.getNode()

      if (['TOPIC', 'SUBTOPIC'].indexOf(node.nodeName) < 0) {
        node = node.parentElement
        if (['TOPIC', 'SUBTOPIC'].indexOf(node.nodeName) < 0) {
          return
        }
      }

      let str = node.innerText.split('↵').join('').replace(/(^\s*)/g, '')
      console.log('node html: ' + node.outerHTML)
      console.log('node innerText: [' + node.innerText + ']')
      console.log('node innerText-removed: [' + str + ']')
      if (str === '') {
        selection.dom.setOuterHTML(node, '<p>&nbsp;</p>')
      }
    }
```

**Comment by lnewson** [comment]
> Is there some code to show newblock ?

Here you go http://fiddle.tinymce.com/mohaab. You can also find more information about the various events and data included here: https://www.tiny.cloud/docs/advanced/events/

**Comment by wideweide** [comment]
> > Is there some code to show newblock ?
> 
> Here you go http://fiddle.tinymce.com/mohaab. You can also find more information about the various events and data included here: https://www.tiny.cloud/docs/advanced/events/

thanks : new block is better !

but the cursor is moved to the first of the selection, even I use setCursorLocation, some code like that:

```
let node = selection.getNode()
selection.dom.setOuterHTML(node, '<p>ABCDEDFHGDF</p>')
selection.setCursorLocation(node, 3) // other postion as I wish
```

the error info: 
`DOMException: Failed to execute 'setStart' on 'Range': There is no child at offset 3.`

**Comment by metricjs** [comment]
The error you got means that `3` is too high an offset - there aren't that many possible cursor positions in `node`. For example, a `p` element only has offsets `0` and `1` because it's an element that wraps other nodes (including text nodes). 

Do you know if `node` is the `p` element or the text inside it in your example? 

Did you mean to set the cursor to offset `3` within the text? I.e. after the `C`? 

If `node` is the `p` element and you wanted to set the cursor position within the text, you need to pass the text node to `setCursorLocation`, not the parent `p` node. For example: `selection.setCursorLocation(node.firstChild, 3)`

**Comment by wideweide** [comment]
@metricjs I write some code like this,but something wrong,please help to fix..

```
NewBlock () {
      let selection = this.$refs.tinyEditor.editor.selection
      if (!selection) return
      let node = selection.getNode()

      if (['TOPIC', 'SUBTOPIC'].indexOf(node.nodeName) < 0) {
        node = node.parentElement
        if (['TOPIC', 'SUBTOPIC'].indexOf(node.nodeName) < 0) {
          return
        }
      }

      let str = node.innerText.split('↵').join('').replace(/(^\s*)/g, '')
      console.log('node html: ' + node.outerHTML)
      console.log('node innerText: [' + node.innerText + ']')
      console.log('node innerText-removed: [' + str + ']')
      if (str === '') {
        // ------------
        // I can't use node.replace and must has a &nbsp; in p -- but it will add a  real space
        selection.dom.setOuterHTML(node, '<p>&nbsp;</p>') 
        console.log('node html: ' + node.outerHTML)
      }
    }
```
