### ISSUE TITLE
How to deal with the problem that the cursor focus is covered when the mobile terminal pops up the input method?

### ISSUE THREAD

**Issue by q326066766** [tinymce/tinymce#5869]
How to deal with the problem that the cursor focus is covered when the mobile terminal pops up the input method?
请问如何处理移动端弹出输入法时,光标焦点被覆盖的问题?

**Comment by metricjs** [comment]
Could you please send us a photo or video of the problem?

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include the details requested above and then we'll be happy to reopen this.
