### ISSUE TITLE
Back from toolbar to editor with ESC does not work if there are multiple toolbar lines

### ISSUE THREAD

**Issue by rskrzypczynski** [tinymce/tinymce#5876]
If user use only keyboard it is not possible to back to editor with ESC after go to toolbar by ALT + F10.
This problem does not occur if toolbar is configurat as single line.
Problem occurs only if configuration is set on multiple toolbar lines.

Steps to reproduce:

Go to editor
Press ALT + F10
Press ESC
https://fiddle.tiny.cloud/aohaab
Should it be possible to back to editor from toolbar by ESC independent of amount of configured toolbar lines.

Observed in version 5.2.2, chrome browser on win7.

**Comment by hrvojegolcic** [comment]
I can reproduce the same issue on Win 8.1 with newest Chrome and FF. IE didn't try

**Comment by lnewson** [comment]
I can confirm this is a bug. I've logged an internal ticket for us to look into this and get it fixed.
