### ISSUE TITLE
Cannot approve the ionic://localhost domain 

### ISSUE THREAD

**Issue by rbalet** [tinymce/tinymce#5878]
**What is the current behavior? Describe the bug**
I cannot add `ionic://localhost` to the approved domain.
this result in seeing the "domain is not registered" message on IOS smartphone devices

**Steps to reproduce**
*  go to https://www.tiny.cloud/my-account/domains/
*  try to add `ionic://localhost`
*  get `Domain name should be correct`

**What is the expected behavior?**
The domain is added to the list

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
*  @tinymce/tinymce-angular : 3.5.0
*  IOS
*  Don't know

**Comment by lnewson** [comment]
@rbalet we can't assist with website/account issues from GitHub sorry. Could you please contact our support team via https://support.tiny.cloud/hc/en-us/requests/new who should be able to help further.
