### ISSUE TITLE
default font family is not selected in menu bar when i am trying to create table

### ISSUE THREAD

**Issue by Ashokkumar799** [tinymce/tinymce#5882]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment]
@Ashokkumar799 can you please fill in the details requested in the template, as it's not clear how to replicate the issue from the title alone?

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include more details about what issue you're having and then we'll be happy to reopen this.
