### ISSUE TITLE
Include Insert/Edit image in the context menu when the user right-clicks on white space

### ISSUE THREAD

**Issue by jsevern55** [tinymce/tinymce#5886]
**In the past, when the user would right-click on white space, the context menu would display the option to insert/edit an image. This option now only displays when the user right-clicks over an existing image.**

![image](https://user-images.githubusercontent.com/30242533/87323419-9682db80-c4e3-11ea-9cbd-105048c9a5f6.png)
![image](https://user-images.githubusercontent.com/30242533/87323438-9be02600-c4e3-11ea-8f68-e0d87045ce17.png)

If possible, please have the option to make this context menu option appear always.

**Comment by lnewson** [comment]
You can do this today by setting a custom `contextmenu`, as by default the editor will show based on the context you right-click on. See https://github.com/tinymce/tinymce/issues/5646#issuecomment-625836551 for more details on how to make a similar context menu to version 4.

Let me know if that doesn't solve your question and I'll reopen this.
