### ISSUE TITLE
Tinymce throw error while init

### ISSUE THREAD

**Issue by HazySoda** [tinymce/tinymce#5887]
**What is the current behavior? Describe the bug**
While init, tinymce throw an error, 
```
tinymce.min.js:9 Uncaught TypeError: Cannot read property 'scroll' of undefined
    at Vr.bind (tinymce.min.js:9)
    at Proxy.eval (tinymce.min.js:9)
    at Si (tinymce.min.js:9)
    at init.each (tinymce.min.js:9)
    at init.on (tinymce.min.js:9)
    at tE (tinymce.min.js:9)
    at Object.add (tinymce.min.js:9)
    at FS (tinymce.min.js:9)
    at VN.render (tinymce.min.js:9)
    at n (tinymce.min.js:9)
```
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment]
@HazySoda, can you please provide a way to replicate this and include the rest of the template fields, specifically what version of TinyMCE you're using and what browser you can replicate this on.

Worth noting I had a quick look and I can't find the `Proxy.eval` or attempts to access the `scroll` property in the latest develop branch.
