### ISSUE TITLE
Problem with erasing full url link when link has an img inside it

### ISSUE THREAD

**Issue by ionescho** [tinymce/tinymce#5888]
So, if I have an image inside an ```<a href>``` , trying to use the link toolbar button to edit/insert the image link and trying to erase the entire URL doesn't work( as soon as I erase the last character, the entire URL pops back into the input).

You can try it yourself by copy and pasting this code inside a TinyMCE editor:
```
<a href="https://www.popgateway.com/uTsaFD8MlleG5z4MorIRyC9FJ0jUk4FYUHeeItSzb2A2gJ30tFpuaNpjvprK6fLsJIGdHs3ZxWZkEYVZgrsC8g~~///"><img src="http://www.metta.org.uk/travel/images/mist2.jpg" alt="" /></a></p>
```
After that, try to click on the image and hit the edit link toolbar button. Then try to erase the entire url and see that you can't because it simply pops back.

**Comment by dmacleay** [comment]
I'm experiencing the same behavior (along with some other possibly-related effects) when attempting to edit the link URL of a linked image.

Fiddle is here: http://fiddle.tinymce.com/fphaab

Tested with TinyMCE 5.4.1 in macOS Safari 13.1.1

1. Click to select the linked image in the editor
2. Click the link button
3. In the link dialog, place the cursor somewhere in the URL field
4. Delete a single character (e.g. press Delete key once) OR insert a single character
      - The cursor jumps to the end of the URL field
      - The value in the Title field disappears
5. Delete the the URL (either one character at a time, or by selecting and deleting all at once)
      - Upon deleting the last character, the entire original URL reappears

**Comment by lnewson** [comment]
Thanks for the reporting of this! We logged an internal ticket to address and we'll update when a fix is available.

**Comment by lnewson** [comment]
TinyMCE 5.4.2 has just been released to the community, which includes a fix for this issue. Please let us know if you continue to experience any further issues.
