### ISSUE TITLE
TinyMCE doesn't work with new version of Chrome 83....

### ISSUE THREAD

**Issue by kaplaner** [tinymce/tinymce#5889]
TinyMCE doesn't work in my card editor. I am prevented to edit template headings on my card and my app crash several attempts.

When i open card editor and try to set some template headings on my card. If previously nothing exists on that fields, or if I setting them for the first time, or if I erase them and try to set new values, my app crash several attempts. 
Also if I have more then one heading on my card, I am prevented to switch between them.

```
<div class="heading">			
     <div class="copy-body title mce-content-body mce-edit-focus" contenteditable="true" data-classifier="titleHead" data- 
     font-class="sm-font" id="mce_0" style="position: relative;" spellcheck="false"><p></p></div>	
</div>
```

Latest version of Chrome Version 83.0.4103.116 (Official Build) (64-bit) 
TinyMCE Version 4.9.10.
MacOS Catalina version 10.15.3

It worked on previous versions of browser, macOS and TinyMCE.

**Comment by lnewson** [comment]
@kaplaner I'm afraid we'll need more information and likely a replication case to be able to assist here. Have you tried TinyMCE 5 to see if you can reproduce the issue there, as TinyMCE 5 is our supported community version?

It's also worth noting that TinyMCE 4.x is only receiving critical patches for the community version now and will [no longer be supported](https://www.tiny.cloud/blog/tinymce-4-support-window/) at the end of this year.

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include the details requested above and then we'll be happy to reopen this.
