### ISSUE TITLE
template plugin documentation is wrong

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#589]
Description of problem:

the template plugin documentation seems to be a copy from tinymce3.
Some Options are wrong or missed in tinymce4

It would be great if the template plugin can handle this like the docu says

&ltg;div class="mceTmpl">

content

&ltg;/div>

Now all html in template is used so you cannot add styles for example.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6095](http://archive.tinymce.com/develop/bugtracker_view.php?id=6095) posted by [otter71](http://archive.tinymce.com/profile.php?name=otter71)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
