### ISSUE TITLE
How to integrate TinyMCE with GrapeJS

### ISSUE THREAD

**Issue by krishnaeverestengineering** [tinymce/tinymce#5891]

**Comment by krishnaeverestengineering** [comment]
Currently some of the tools are not working.

**Comment by metricjs** [comment]
@krishnaeverestengineering Could you please give us some more information? Are you making an integration or using an existing one? What problems are you seeing? What version of TinyMCE are you using?

**Comment by krishnaeverestengineering** [comment]
I am using TinyMCE 5 and when I replace it with default RTE, some of the functions like Alignments, Formats were not working.

**Comment by metricjs** [comment]
Is there any more information you could give us? For example, in what way are they not working? Is there any errors in the console? Are you able to show us any screenshots of the problem?

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include the details requested above and then we'll be happy to reopen this.
