### ISSUE TITLE
Is there a way to narrow down the fontsize drop down

### ISSUE THREAD

**Issue by abhijeetj100** [tinymce/tinymce#5894]
![image](https://user-images.githubusercontent.com/33035102/87537284-021da200-c6b8-11ea-8416-961fc1c5fe9c.png)

As in the above image, is there a way/workaround through which we can reduce the width taken up by the dropdown? 

I researched a little and found this issue :
https://github.com/tinymce/tinymce/issues/4595

But no workaround has been suggested there.

Thanks
Abhijeet

**Comment by abhijeetj100** [comment]
Thanks @tylerkelly13

**Comment by metricjs** [comment]
Hi @abhijeetj100. 

This is actually something we have been looking into recently which will likely change in a future release. If you would like a more immediate solution, the width of the `fontsizeselect` is specified in the skin CSS. So I believe you may be able to change the skin to get the effect you want. However, changing this CSS rule would also affect the `alignselect`, `fontselect`, `formatselect` and `styleselect` toolbar buttons as well. So this is possible, but we would recommend proceeding with caution. If you don't need an immediate fix, I would recommend waiting for the changes we have planned, though we don't have a schedule for this work yet.

**Comment by abhijeetj100** [comment]
Sure @metricjs .

Thanks 👍

**Comment by lostkeys** [comment]
Currenly TinyMCE wants menus to be as wide as the parent menu button, so it programatically adds a min-width to the menu. [It can be overridden like this](http://fiddle.tinymce.com/grhaab), but that will affect all menus. We generally strongly advice overriding CSS like this and we cannot support it. But on the other hand the worst thing that can happen is that the menus become a bit wider again if we make changes to the HTML or CSS that would make the override not work. So it should be fine.
