### ISSUE TITLE
excel merge row  have wrong format

### ISSUE THREAD

**Issue by hicheer** [tinymce/tinymce#5895]
my excel like this:
![image](https://user-images.githubusercontent.com/18565314/87635365-7ff1b400-c771-11ea-94b6-16c37422c237.png)

in version 4.8.2 have wrong format. I try  this page:  https://www.tiny.cloud/docs/demo/full-featured/  , both Premium Plugins and Non-Premium Plugins have wrong too.

Premium Plugins effect:
![image](https://user-images.githubusercontent.com/18565314/87636233-08248900-c773-11ea-8d17-22a370036c80.png)

Non-Premium Plugins effect:
![image](https://user-images.githubusercontent.com/18565314/87635697-0e663580-c772-11ea-82e9-e88cecc03eb2.png)

**Comment by metricjs** [comment]
Hi @hicheer,

First, have you bought any premium plugins? For example, are you using PowerPaste?

Second, I believe this may be a known issue. To confirm that, could you please attach either:
- The Excel document that is causing this issue.
- The clipboard HTML when you copy the Excel document (e.g. copy the Excel document, open a clipboard viewer program and copy the HTML data, paste it into a file, save the file and send it to us).

It could also be helpful if you could send us the editor HTML after pasting the Excel document into TinyMCE.

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please reply with the information requested above and we'll reopen this.
