### ISSUE TITLE
Fullpage does not reset HTML

### ISSUE THREAD

**Issue by vesnican** [tinymce/tinymce#5896]
**What is the current behavior? Describe the bug**
When fullpage plugin enabled, once you insert HTML containing tags in head or attributes in html or body tags, they are not reset by File->New Document. The only way is manual edit of source code.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
http://fiddle.tinymce.com/Lohaab/3
1) Do File->New Document
2) View source code: tags in head and attributes in html and body tags remained intact.

**What is the expected behavior?**
Initial HTML without tags in head and without attributes should be created after New Document

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce-react 3.6.0 (TinyMCE 5), tested on latest Firefox & Chrome. No idea about previous versions.

**Comment by metricjs** [comment]
Hey @vesnican, just wanted to let you know that we've been discussing this internally. We're a bit unsure which behaviour would be best though. I'll try to get you an update when we have decided.
