### ISSUE TITLE
Remove tinymce 4 instance

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#590]
Description of problem:
I try to init and remove instances on the fly, but I cant figure out if the instances gets cleaned up correctly. I dont get any errors but the RemoveEditor event triggers for each of the removed/destoyed instances.

Docs it says: Destroys the editor instance by removing all events, element references or other resources that could leak memory. This method will be called automatically when the page is unloaded but you can also call it directly if you know what you are doing.

if I understand correctly it should be ed.destroy(false); in my code, missed it in the fiddle but still same result.

Is this correct? Or how do I clean up after me?

Steps to reproduce:
1. click init
2. click remove
3. click init
4. click remove
5. look in console

Expected result:
Just one console out per remove

Actual result:
One console out for each old editors instance
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6096](http://archive.tinymce.com/develop/bugtracker_view.php?id=6096) posted by [magny](http://archive.tinymce.com/profile.php?name=magny)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://fiddle.tinymce.com/fqdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
