### ISSUE TITLE
Callback when a Template is applied

### ISSUE THREAD

**Issue by eugenio-caicedo** [tinymce/tinymce#5901]
I'd like to have a callback when a template is applied with the complete information got from the remote server. Like that:

````
templates: "/dir/templates.php",
templates_create: function(event, template) {  ... }
````
I think it is a good solution to update the interface with other custom parameters or hide options if required.

**Comment by metricjs** [comment]
Hi @eugenio-caicedo, 

Could you please detail a use case for this? For example, what kind of template would you use this for and what would you want the callback to be capable of? The more information you can give us the better we can scope this out.

**Comment by eugenio-caicedo** [comment]
Hi @metricjs, yes, sure. Let me explain better this. Currently, the library manages the template with those fields:

`{ :title, :description, : content, :url }`

But this is a limitation if I need to add some custom fields like _category_ or _notes_. So I think a callback can be helpful in solving this. I can use that callback to print these specific values in the UI. I just need the original values from the server response:
````
templates_create: function(event, template) {  
   var category = template.catetory;
  var description = template.description;
   $("#description").val(description);
   $("#category").val(category);
   //the event is only information about the changes on the UI.
}
````
Another use case can be to enable/disabled some components on the UI, for example, I can add a field like this:

`no_font: true/false `

This parameter in the template indicates that the user cannot change the font in the current template. I can add whatever value I want to templates without altering current functionality.

I am not sure if it is possible to enable or disable features on runtime, but this is another good option to add to the editor.
