### ISSUE TITLE
Is there any plugin for creating Responsive fluid layout design inside editor like table ?

### ISSUE THREAD

**Issue by krishnaeverestengineering** [tinymce/tinymce#5902]

**Comment by metricjs** [comment]
Hi @krishnaeverestengineering, 

Could you please give us more details on what functionality you would like? For example, a description, a HTML snippet or a link to an existing library that does something similar?

**Comment by androb** [comment]
If you are using Bootstrap, there is plugin available:
https://www.tinymce-bootstrap-plugin.com/

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include the details requested above and then we'll be happy to reopen this.
