### ISSUE TITLE
anchor_top, anchor_bottom cannot be removed from type ahead URL list

### ISSUE THREAD

**Issue by dmacleay** [tinymce/tinymce#5904]
Setting anchor_top and anchor_bottom to false does not remove them from the type ahead URL list in the link dialog.

Fiddle: http://fiddle.tinymce.com/gphaab

1. Click the link button
2. In the link dialog, type "t" in the URL field

&lt;top&gt; and &lt;bottom&gt; appear in the type ahead URL list

According to current-version documentation, [they should not appear](https://www.tiny.cloud/docs/configure/url-handling/#anchor_bottom).

Tested with TinyMCE 5.4.1 in macOS Safari 13.1.1

**Comment by metricjs** [comment]
Thanks for reporting this @dmacleay! I've confirmed this is a bug and created an internal ticket for it.

**Comment by lnewson** [comment]
This appears to have been broken in 5.4.0, so adding the regression label as well. If you use 5.3.2 then it does work: http://fiddle.tinymce.com/gphaab/1

**Comment by lnewson** [comment]
TinyMCE 5.4.2 has just been released to the community, which includes a fix for this issue. Please let us know if you continue to experience any further issues.
