### ISSUE TITLE
[bug][5.3.2] The dropdown doesn't  move with Editor when the page is scrolled.

### ISSUE THREAD

**Issue by xr0master** [tinymce/tinymce#5905]
**What is the current behavior? Describe the bug**
The dropdown scrolls apart from the content.
![image](https://user-images.githubusercontent.com/8962340/88015274-81342f80-cb29-11ea-9910-097a8573f30f.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
You can just open the skin generator as example http://skin.tiny.cloud/t5/
Open any dropdown (font for example) and scroll the page. It happens, because the dropdown in the body, but the scroll in a custom container.

**What is the expected behavior?**
The dropdown should move with editor.

**How to fix**
I think, as in other libraries, to give the opportunity to set a parent container for dropdowns.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.3.2
Chrome 83
Have no idea, I'm a new user.

**Comment by metricjs** [comment]
Hi @xr0master, this is something we're aware of however it would be a new feature and it's unfortunately not something that we've had time to schedule yet. This is already being tracked via #5097 so I'm going to close this as a duplicate.
