### ISSUE TITLE
Allow all valid_children possibilities

### ISSUE THREAD

**Issue by BenjaminTournois** [tinymce/tinymce#5906]
**What is the current behavior? Describe the bug**
I need to allow all valid_children possibilities. For exemple, I would like to write in the "source code" view this :

`<h2><div>test</div></h2>`

So I have to add to tinymceOptions : 

`valid_children : "+h2[div]"`

How can I allow everything without enumerate all the combinaisons ? I wish something like `valid_children : "+*[*]"` would work but it doesn't. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

With `valid_children : "+h2[div]"` https://fiddle.tiny.cloud/kphaab it works.
With `valid_children : "+*[*]"` https://fiddle.tiny.cloud/kphaab/ it doesn't work.

**What is the expected behavior?**

Make  `valid_children : "+*[*]"` works for all combinaisons.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Using 5.4.1 version. All OS and browser affected. I don't know if it worked for a previous version of TinyMCE.

**Comment by metricjs** [comment]
Hi @BenjaminTournois, 

What is your use case for this? This would allow for invalid HTML to be added to the editor, which we try to avoid as it can cause unpredictable behaviour for users in both TinyMCE and the browsers themselves. It is usually safer to explicitly specify combinations that you have tested, to ensure everything works correctly.

**Comment by BenjaminTournois** [comment]
Hi @metricjs, thank you for your answer, and I totally agree with you. But in any case I need that TinyMCE doesn't rewrite my html code for any reason. 

To illustrate another use case, I use AngularJS and I created some directives which I use like `<foo>bar</foo>` and this should not be delete or rewrite.

Is there a way to avoid TinyMCE to rewrite my source code ?

**Comment by metricjs** [comment]
Hi @BenjaminTournois, we discussed your request further but we can't find any way to completely turn off HTML validation. I suspect that even if we did, it might have cascading issues with other parts of the editor though. `valid_children`, `extended_valid_elements` and the like are probably your best bet. I do know that for Angular projects, [`custom_elements`](https://www.tiny.cloud/docs/configure/content-filtering/#custom_elements) can be quite helpful too, if you didn't know about that one already.

Is there anything about your use case that can't be solved by the combination of those settings?

**Comment by BenjaminTournois** [comment]
Ok thank you. You are right I can solve any combination but it would have been easier to have a parameter to allow every cases instead of writing case by case.

So is there a way to know if the source code has been modified after the validation of the source code editing ?

**Comment by lostkeys** [comment]
To find out if TinyMCE changed your HTML you can immediately after loading the editor do a diff between what you sent into TinyMCE and the HTML that got rendered inside TinyMCE. The [setContent event](https://www.tiny.cloud/docs/advanced/events/) and the [getContent method](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#getcontent) would be a good start.
Another approach could be to somehow automatically generate a list of custom elements you app is using and feed that into the custom_element option.

Please feel free to reopen this ticket if you didn't manage to get this working.
