### ISSUE TITLE
how fous to the original location use setCursorLocation

### ISSUE THREAD

**Issue by wideweide** [tinymce/tinymce#5907]
**Is your feature request related to a problem? Please describe.**
https://github.com/tinymce/tinymce/issues/5862

**Describe the solution you'd like**
```
if I change <h1>ABCDEDFHGDF</h1> to <p>ABCDEDFHGDF</p> use my method
how fous to the original location use setCursorLocation?

let node = selection.getNode()
selection.dom.setOuterHTML(node, '<p>ABCDEDFHGDF</p>')
selection.setCursorLocation(node, 3) //  how to get original loation
```

**Comment by metricjs** [comment]
Closing as this is a continuation of #5862. Please keep conversation about a bug in the same ticket so we can see the conversation history easily.
