### ISSUE TITLE
Inline editor "tooltip" toolbar width/breakpoint

### ISSUE THREAD

**Issue by TechOverflow** [tinymce/tinymce#5914]
Is there a way to make the tooltip width not adhere to the size of the element that is being edited inside of?
For example in case of an editor `div` that is `100px` wide and only contains two editable words, an inline toolbar is only as wide as the `div`, even smaller if only the second word is selected.

Is it possible to set it to either a larger parent element or the screen size itself?

**Comment by metricjs** [comment]
Hi @TechOverflow, would adding the `width` setting or even the `min_width` setting to your TinyMCE config fix this? I believe they should override the behaviour where the inline toolbar inherits its width from the editor element/its parent/etc.

Refs: 
- https://www.tiny.cloud/docs/configure/editor-appearance/#width
- https://www.tiny.cloud/docs/configure/editor-appearance/#min_width

**Comment by TechOverflow** [comment]
Hi @metricjs. Unfortunately, I have tried both and they do nothing for the inline version.

**Comment by lnewson** [comment]
@TechOverflow the above does work for me to change the toolbar width, so could you please create a [fiddle](https://fiddle.tiny.cloud) to reproduce your issue?

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include the details requested above and then we'll be happy to reopen this.
