### ISSUE TITLE
Reply to a comment not saved after save click button it requires two times click on save button

### ISSUE THREAD

**Issue by virendrasinghpawar** [tinymce/tinymce#5919]
**Reply to a comment not saved after save click button it requires two times click on save button**

in embed mode of tinymce comment whenever user replies to a comment he needs to explicitly hit save button again to save the conversation .Current version tinymce 5.x and if also possible any event in embeded mode which can be triggered so that dev can auto save content of tinymce to the backend .

**Comment by lnewson** [comment]
Tiny Comments is a premium product and this GitHub project is for the open source version of TinyMCE, so I'm afraid we can't help via GitHub. If you're having issues with Tiny Comments, please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
