### ISSUE TITLE
如果需要回显得字符串含有img标签，并且src是base64格式的，img显示图片异常

### ISSUE THREAD

**Issue by namezj** [tinymce/tinymce#5925]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment]
Hi @namezj,

Firstly we can only handle tickets in English, so I'm going to close this sorry. Secondly, if you log a new issue, please ensure to fill out the relevant template content so that we can replicate the issue. Without that, we can't assist sorry.
