### ISSUE TITLE
Revert menu popovers with custom html.

### ISSUE THREAD

**Issue by GamerX-Ar** [tinymce/tinymce#5926]
Hello!

TinyMCE version 4.x has panel button with custom html, like this:

```javascript
editor.addButton("emoji", {
    type: "panelbutton",
    panel: {
        role: "application",
        autohide: !0,
        html: getPopoverHtml(),
        onclick: function(e) {
        }
    }
});
```

It's a very useful feature for some handmade plugins such as Emoji for example. Calling a dialog window for this purpose is less useful. However i don't see the feature in TinyMCE version 5.x. Why was it removed from new versions?

I can do some trick and add the floating panel from js and open/close it on click (onAction...) but I need for current positin of the plugin button on the toolbar:

```javascript
editor.ui.registry.addButton('mycustombutton', {
    tooltip: 'CustomButton',
    icon: 'table',
    onAction: function (api) {
        // Here i want catch the event.target
    }
});
```

I can't query by css selector because the button has neither an identifier nor a class. Now I find the editor interface less flexible and stay use version 4.

**Comment by lostkeys** [comment]
Hi @GamerX-Ar. You are right that TinyMCE 5 doesn't support putting arbitrary HTML inside the dialogs. One big reason is that we don't want third party CSS styles within TinyMCE as changes we do to our CSS might bleed into the third party ui and break it. When operating at our scale, the support load plays a factor when creating (and removing) features.

One idea we have is to isolate third party UI using web components. Would that work for your use-case?

**Comment by GamerX-Ar** [comment]
Hi, @lostkeys. Thanks for your answer. We are not using web components yet. But the idea looks promising. Is it already possible to embed my custom component in the editor for my case?

**Comment by lostkeys** [comment]
I just wanted to circle back and check if your use-case would be solved using what we call an [URL-dialog](https://www.tiny.cloud/docs/ui-components/urldialog/) which basically loads anything you want into the dialog through an iframe?
