### ISSUE TITLE
Release from Version 5.4.1 July 8, 2020 - not working

### ISSUE THREAD

**Issue by bear-wolf** [tinymce/tinymce#5928]
Hi.
I use your product and after the last release, I have a problem with JS

![image](https://user-images.githubusercontent.com/14107341/89039350-93dd0e80-d34a-11ea-9839-33f9eb8b668a.png)
![Screenshot_2](https://user-images.githubusercontent.com/14107341/89039313-7f991180-d34a-11ea-94b8-661ff46d6eb4.png)

**Comment by lnewson** [comment]
@bear-wolf could you please provide a way to reproduce the issue (eg via a [fiddle](https://fiddle.tiny.cloud))?

The exception you're getting it very strange as it's saying the window `Element.prototype` is undefined, which is something we likely can't do anything about. It might be worthwhile making sure you're not using a polyfill or some other library that's messing with the browsers native prototypes.

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include the details requested above and then we'll be happy to reopen this.
