### ISSUE TITLE
When building a bundle of themes, plugins references to js/tinymce is lost

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#593]
Description of problem:

I downloaded the latest release from github and can build and minify with jake properly.

Making a bundle to load tinyMCE faster went well, but I discover that references to skin css files loose the first "js/tinymce" part in the requests.

Steps to reproduce:
1. get the latest build from github
2. make sure you can build with jake
3. make a bundle as "jake minify bundle[themes:modern,plugins:table,paste,visualblocks]
4. use the new tinymce.full.min.js in an easy testpage
5. Used the instructions for building from github and did no changes to the original jakefile.js

Expected result:
That everything would be pulled in properly and working.

Actual result:
it can't load some files like the /js/tinymce/skins/lightgray/skin.min.css file because it reference it without the first "js/tinymce" part in the url. (or the visualblock.css)

example:
when loading it asks for /mytinydir//skins/lightgray/skin.min.css
when it should be /mytinydir/js/tinymce/skins/lightgray/skin.min.css
(this could be circumvented by setting skins_url to: /mytinydir/js/tinymce/skins)

The same is for visualblocks where it asks for:
/mytinydir//plugins/visualblocks/css/visualblocks.css

instead of:
/mytinydir/js/tinymce/plugins/visualblocks/css/visualblocks.css

I can't find a way past that like with the skins_url init parameter.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6461](http://archive.tinymce.com/develop/bugtracker_view.php?id=6461) posted by [DanielMogul](http://archive.tinymce.com/profile.php?name=DanielMogul)_

> _**Tags:** [firefox msie safari chrome opera jake bundle]_
> _**Status:** Closed_
> _**Resolution:** Fixed_
> _**Attached URL:** none_

**Comment by marianbida** [comment]
Bug exists in // 4.4.0 (2016-06-30)

**Comment by nanivijay** [comment]
+1

**Comment by stepbeta** [comment]
still true in // 4.6.6 (2017-08-30)
