### ISSUE TITLE
Trying to link image in basic demo causes everything to be linked

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#594]
Description of problem:

Using Chrome 26 (version options in this tracker need to be updated, BTW!), attempting to link just the image on the top right in the basic demo causes everything in the page to get linked to the target URL.

Steps to reproduce:
1. Select image in the body
2. Click link button
3. Click browse
4. Select a file to link to
5. Submit

Expected result:

Only the image is linked to the file selected

Actual result:

Entire body gets linked - a tag is applied within every block level element on the page.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5806](http://archive.tinymce.com/develop/bugtracker_view.php?id=5806) posted by [seanr](http://archive.tinymce.com/profile.php?name=seanr)_

> _**Tags:** [chrome link]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
