### ISSUE TITLE
Set language  via function

### ISSUE THREAD

**Issue by sinbargit** [tinymce/tinymce#5945]
Any way we can set language via something like a function?  It is hard to add a js in our CDN
Our project is a single Page app

**Comment by sinbargit** [comment]
Maybe a js blob can do this?

**Comment by lnewson** [comment]
@sinbargit can you please add more details about what you are trying to do or what problems your having? To use another language for the UI you should just need to add the [language](https://www.tiny.cloud/docs/configure/localization/#language) setting and then either host the appropriate language pack on a server or include it in your bundled JS.

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the information requested above, then we'll be happy to reopen this.
