### ISSUE TITLE
I can't find what I'm looking for: general-configuration-guide/multiple-editors.md

### ISSUE THREAD

**Issue by ShivSoni5** [tinymce/tinymce#5947]
When I create multiple inline Editor instances then if I perform any editor action on text field like making characters bold or italic then the editor corresponding button will get enabled which is obvious and correct behaviour. But after it when I put my cursor on next text field then still the button in editor **remains enabled**. After inspecting it I found that class "tox-tbtn--enabled" is present there which should not be present.

I am also attaching the image of the issue. Here BOLD button **should not be enabled**. Also, all fields toolbar is attached to a div above all text fields as shown in image

![Screenshot from 2020-08-06 18-00-44](https://user-images.githubusercontent.com/21109688/89532098-e321b400-d80e-11ea-939d-af1b466b7e2e.png)

I have done some more investigation and found that first toolbar creation is perfect but when others get initialised they copy properties like classes and all from the first toolbar. That's why the button gets enabled. I am facing this issue in our product.

I have just shown a demo here. I will really appreciate if I get a solution for it. Thanks in advance.

**Comment by lnewson** [comment]
Hi @ShivSoni5, I can confirm this is a known issue. The cause is that the `editor.selection.getNode()` API isn't constraining itself to just the editor body. So it sees the selection in the first editor is on bold and as such the other toolbars end up showing bold being active as well. I'll add this issue to our internal tracker and we'll let you know when a fix is available.

**Comment by ShivSoni5** [comment]
@lnewson Thanks for confirming.
I'll be waiting for this bug fix, so please do let me know about this.

**Comment by ShivSoni5** [comment]
I have figured out an alternative until the bug fix releases.
What you can do is to check the field only for the first time and find if the cursor is positioned on any styled character(i.e. bold, italic or underline). If yes then keep the enabled class on toolbar else remove it.

I have provided code below for your help.

```
questionsToolbarInitialized: { [questionId: string]: boolean } = {};

QuestionFocused(questionId: string) {
    setTimeout(() => {
      if (!this.questionsToolbarInitialized[questionId]) {
        const isSelectedBold = document.queryCommandState('bold');
        const isSelectedItalic = document.queryCommandState('italic');
        const isSelectedUnderline = document.queryCommandState('underline');


        if (!isSelectedBold) {
          const boldButtons = document.querySelectorAll('[title="Bold"]');
          boldButtons[boldButtons.length - 1].classList.remove('tox-tbtn--enabled');
        }


        if (!isSelectedItalic) {
          const italicButtons = document.querySelectorAll('[title="Italic"]');
          italicButtons[italicButtons.length - 1].classList.remove('tox-tbtn--enabled');
        }


        if (!isSelectedUnderline) {
          const underlineButtons = document.querySelectorAll('[title="Underline"]');
          underlineButtons[underlineButtons.length - 1].classList.remove('tox-tbtn--enabled');
        }

        this.questionsToolbarInitialized[questionId] = true;
      }
    });
  }
```

I have always used the last button because the newly created text editor is always present at the last position of an array.
Now we can use this function whenever the field gets into focus.
