### ISSUE TITLE
Dragging images in Chrome V26 replaces image with image url.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#595]
Description of problem:

Steps to reproduce:
1. move the logo image anywhere within TinyMCE

Expected result: Image displayed in new location

Actual result: TinyMCE Logo link shows up not the image.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5807](http://archive.tinymce.com/develop/bugtracker_view.php?id=5807) posted by [wwken](http://archive.tinymce.com/profile.php?name=wwken)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
