### ISSUE TITLE
bbcode v4.x

### ISSUE THREAD

**Issue by andrtechno** [tinymce/tinymce#5950]
не работает 
underline, strikethrough
нужно подправить replace regexp !

возможно  что-то еще не работает. не проверял!

**Comment by lnewson** [comment]
Hi @andrtechno,

We can only handle tickets in English, so I'm going to close this sorry. I should also note that TinyMCE 4.x is only receiving critical fixes now and will no longer be supported at the end of the year.

**Comment by andrtechno** [comment]
@lnewson google translate will help)
