### ISSUE TITLE
Image dragndrop issue in tinymce on safari browser

### ISSUE THREAD

**Issue by ravipjag** [tinymce/tinymce#5951]
Hi

I am using self hosted tinymce in my angular 8 application of v5.2.2. I have problem in drag drop image in tinymce on safari browser, which is not inserting image in tinymce editor,  any configuration for this is available so it can shown in editor

Thanks,
Ravindra.

**Comment by lnewson** [comment]
Hi @ravipjag, can you please try to replicate this on the latest version of TinyMCE? As there were a number of fixes done with inserting images from Safari in TinyMCE 5.3.

If that doesn't work, then can you please provide more details (are there any console errors, what type is the image, how big is the image, etc...) or a way to replicate the issue?

**Comment by ravipjag** [comment]
Hi Newson,

As we are using self hosted tinymce and site is up so changes in version may affect several places We want solution in this version. So please look into it.

Ravindra

**Comment by MichaelFromin** [comment]
> We want solution in this version. So please look into it.

This issue was fixed in TinyMCE 5.3.  

We do not provide patches/fixes to older versions and this issue is already resolved in the current release of TinyMCE.  To get this working as you wish you will need to update to the latest TinyMCE.
