### ISSUE TITLE
Problem with formatting text

### ISSUE THREAD

**Issue by vbarzilovich** [tinymce/tinymce#5958]
I noticed a problem with formatting text.

This problem can sen, when text contains italics style in bold style, for example:

<p><strong>This is the text <em>line</em> for problem visualization</strong></p

HTML:
`<p><strong>This is the text <em>line</em> for problem visualization</strong></p>`

If you select the word `for` and remove bold style from it, then the editor will remove the space to the left of `for` and the line will look like this (`linefor` without space):

<p><strong>This is the text <em>line</em></strong>for <strong>problem visualization</strong></p>

HTML:
`<p><strong>This is the text <em>line</em></strong>for  <strong>problem visualization</strong></p>`

You can test formatting in a text editor on the site https://www.tiny.cloud/

**Comment by lnewson** [comment]
I can confirm this is a known issue and is currently being tracked here: https://github.com/tinymce/tinymce/issues/4995 We have a PR open at the moment to fix this.
