### ISSUE TITLE
Add/remove spacing formatting tool

### ISSUE THREAD

**Issue by abhijeetj100** [tinymce/tinymce#5959]
Hey guys,

Is there any way to mimic the add/remove space formatting tool similar to the one in MS Word ?
![image](https://user-images.githubusercontent.com/33035102/89630396-f0957780-d8bc-11ea-9d87-f06ae0ebfbb9.png)

Thanks

**Comment by abhijeetj100** [comment]
Thanks @tylerkelly13 
🙂

**Comment by androb** [comment]
@bwilkn I know you've been looking at prioritizing advanced formatting issues such as this.

@abhijeetj100 can you share more information about your use case?

**Comment by abhijeetj100** [comment]
Hey @androb ,
Apologies, for the late reply.
I tried implementing this feature.
But for changing the icon while runtime of the custom buttom, its not getting changed

![image](https://user-images.githubusercontent.com/33035102/90238873-41204e00-de44-11ea-8e91-5f6dc214feb0.png)
I am changing the button icon using this:
`editor.ui.registry.getAll().buttons.spacebeforeparagraphbutton.icon="add-space-before-paragraph";`

but it stays the same.

you can check this out for code:
https://codepen.io/abhijeet100/pen/wvGMbRQ?editors=0010

**Comment by abhijeetj100** [comment]
@tylerkelly13 
Can you please get me some help ?

Thanks

**Comment by lnewson** [comment]
Hi @abhijeetj100,

It's come to our attention that this feature request has also been logged in our commercial support system, so I'm going to close this and ask all future communication go via there, as it'll receive more attention and priority than GitHub feature requests. If that is incorrect and your company didn't log a feature request via our commercial support, then please let us know and we'll reopen this.

Thanks!

P.S. As for your latest question, we'll deal with that in your other open GitHub issue.

**Comment by abhijeetj100** [comment]
@lnewson Sure, np.
Thanks :)
