### ISSUE TITLE
insert date/time: use html5 microformats

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#596]
use html microformats when inserting date/time.

Instead of inserting plain date/time strings wrap those in &ltg;time> tags, see http://html5doctor.com/the-time-element/

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5804](http://archive.tinymce.com/develop/bugtracker_view.php?id=5804) posted by [kills](http://archive.tinymce.com/profile.php?name=kills)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://html5doctor.com/the-time-element/_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. 🐛 

If you still have a problem connected to this, leave a comment and we can open it up again. 

Cheers! 🍺
