### ISSUE TITLE
Need help with adding a custom icon

### ISSUE THREAD

**Issue by abhijeetj100** [tinymce/tinymce#5964]
Hey, I am using the following code to create a custom icon in setup attribute of init():

`  editor.ui.registry.addIcon(
    'lineHeightCustom',
    '<svg version="1.1" width="24px" height="24px" viewBox="0 0 32 32" xml:space="preserve"><g><path style="fill:#010002;" d="M9,29h5.833L9,23h5V9H9l5.833-6H9V0h14v3h-5.833L23,9h-5v14h5l-5.833,6H23v3H9V29z"></path></g></svg>'
  );`
![image](https://user-images.githubusercontent.com/33035102/89882097-f43e3c80-dbe3-11ea-99ab-7daf8c944b5a.png)

and then trying to reference to this icon created in the "icon" attribute when using addMenuButton().
![image](https://user-images.githubusercontent.com/33035102/89882117-fe603b00-dbe3-11ea-8411-26d573e3ed67.png)

But I am getting an icon which looks like a bomb:
![image](https://user-images.githubusercontent.com/33035102/89882075-eee0f200-dbe3-11ea-8e8a-3a793a5e1bfc.png)

Please tell if I am doing anything wrong.

Thanks,
Abhijeet

**Comment by lnewson** [comment]
Hi @abhijeetj100, what version of TinyMCE are you using? As there was a bug when using icon names that contained capital letters (see #5059), but that was fixed in TinyMCE 5.4.0.

If you're using a version less than 5.4.0, the workaround is to use a lowercase name such as `lineheightcustom`.

**Comment by abhijeetj100** [comment]
ah, it seems I am using 5.3.1.
I'll try once with the lowercase name and will update here.

Btw...rest all seems fine right?

**Comment by lnewson** [comment]
Yeah, the rest looks fine, from what I can see in the screenshots. 👍

**Comment by abhijeetj100** [comment]
just ran it again.

Worked perfectly.

Thanks again 👍

**Comment by abhijeetj100** [comment]
I had one more question though.
is there a way to show both icon and text on a menu button?
