### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reset' of undefined when resetting form

### ISSUE THREAD

**Issue by globules-io** [tinymce/tinymce#5965]
Resetting a form into which a textarea is a tinymce instance returns error

     <form id="myform">
           <input type="text" name="title">
           <textarea id="desc_editor" class="texteditor" name="body" placeholder="Type your content here..."></textarea>
     </form>

ie, using jQuery

     $('#myform')[0].reset();

Error trace version 5.2.1

`tinymce.min.js:9 Uncaught TypeError: Cannot read property 'reset' of undefined
    at $E.resetContent (tinymce.min.js:9)
    at $E.<anonymous> (tinymce.min.js:9)
    at uE.fire (tinymce.min.js:9)
    at $E.fire (tinymce.min.js:9)
    at Object.t.formEventDelegate (tinymce.min.js:9)
    at Jr.executeHandlers (tinymce.min.js:9)
    at HTMLFormElement.o (tinymce.min.js:9)`

Error trace version 5.4.1

   `at VN.resetContent (tinymce.min.js:9)
    at VN.<anonymous> (tinymce.min.js:9)
    at dN.fire (tinymce.min.js:9)
    at VN.fire (tinymce.min.js:9)
    at Object.FS.t.formEventDelegate (tinymce.min.js:9)
    at Vr.executeHandlers (tinymce.min.js:9)
    at HTMLFormElement.m (tinymce.min.js:9)`

**Comment by lnewson** [comment]
Hii @globules-io, I tried to reproduce this but I wasn't able to. Here's the fiddle I used, so can you please update it to show how to reproduce this error? https://fiddle.tiny.cloud/oqhaab

Worth noting the exception you're getting indicates that the `editor.undoManager` instance is undefined, which is worrying...

**Comment by globules-io** [comment]
Can't reproduce with the fiddle but can reproduce 100% of the time here.... 
But have too many things across the board to try to make a stripped case.
Up to you to look into this or close.

**Comment by rexebin** [comment]
I am using tinymce/react latest version (5.8 and 3.12.3) `Editor` component and I get this error the first time I load an tiny editor: 

> Uncaught TypeError: Cannot read property 'reset' of undefined
>     at Editor.resetContent (vendor.js:532669)
>     at Editor.<anonymous> (vendor.js:530839)
>     at EventDispatcher.fire (vendor.js:531610)
>     at Editor.fire (vendor.js:531715)
>     at Object.editor.formEventDelegate (vendor.js:530835)
>     at EventUtils.executeHandlers (vendor.js:508942)
>     at HTMLFormElement.defaultNativeHandler (vendor.js:508745)
>     at reset (vendor.js:335983)

1. It happens when the form is reset to populated data when TinyMCE is still showing a blank area, I guess it has not finished loading yet.
2. It only happens once in the app after refreshing the browser, after then, everything is fine.
3. clicking `vendorjs:533669` lead to this line, apparently `this.undoManager` is `undefined`: 
```
 Editor.prototype.resetContent = function (initialContent) {
        if (initialContent === undefined) {
          setContent$2(this, this.startContent, { format: 'raw' });
        } else {
          setContent$2(this, initialContent);
        }
  --> this.undoManager.reset();
        this.setDirty(false);
        this.nodeChanged();
      };

My guess is `undoManager` somewhat was not yet initialized when `reset` is called.

**Comment by rexebin** [comment]
I am happy to confirm that delaying my form `reset` for 100ms - 250ms with `setTimeout`, this error went away, I suppose this allows TinyMce to be fully initialised before the `reset` request.

I can also confirm without the delay, the error happens only once after a manual refreshing the browser.
