### ISSUE TITLE
How to dynamically change text value of menuButton

### ISSUE THREAD

**Issue by abhijeetj100** [tinymce/tinymce#5966]
Hey,

https://codepen.io/abhijeet100/pen/mdPezJq?editors=1011

![image](https://user-images.githubusercontent.com/33035102/89975544-a6791100-dc83-11ea-828f-5b03b5ed794f.png)
For the expected behaviour when selecting a value from the menuButton "Line-Height" should get replaced by the value selected.

You can check out the code using the given link.

I am using an object to store the value to display as text and tooltip, but before that I also tried something like:

`editor.ui.registry.getAll().buttons.lineheighhtbutton.text = config[key].value`

but this also didn't work for me.
Please suggest some workaround if possible or if anything in the code seems wrong.

Thanks,
Abhijeet

**Comment by lnewson** [comment]
Hi @abhijeetj100,

There's no way to currently do this sorry, as the buttons that do allow this (eg `fontselect`) currently use an internal only API. We do want to expose this for others to use, however we haven't yet scheduled the work to do that, so I'm going to label this as a feature request.

Note: If you're a commercial customer I'd recommend logging this feature request via our support channels, as it'll receive more attention/priority than GitHub feature requests.

**Comment by PeiyuanZ** [comment]
same need one api to change text

**Comment by zozoh** [comment]
I have seem case too #6479

**Comment by jRexhmati** [comment]
@lnewson Is there any update on this one?

**Comment by lsycxyj** [comment]
Or is there any way to add listbox into toolbar? It's available in [4.x](https://www.tiny.cloud/docs-4x/demo/custom-toolbar-listbox/).

**Comment by habui-epi** [comment]
Hi, the workaround solution could be:
1. Use special string with tooltip as a indicator for the button
2. onSetup method try to find the button with the indicator (document.querySelector(`button[tooltip="${tooltipPlaceholder}"]`)) and update text as you want.
