### ISSUE TITLE
The current stable version still points to 5.4.1 even though we just had a release this morning

### ISSUE THREAD

**Issue by ionescho** [tinymce/tinymce#5973]
The url for current stable cloud release( https://cdn.tiny.cloud/1/no-api-key/tinymce/5/version.txt ) still says 5.4.1.

Shouldn't it already say 5.4.2? 

tinymce-react depends on whatever version the cloud provides and until it is updated, we cannot access the bug fixes

**Comment by lnewson** [comment]
Hi @ionescho, this is expected as our cloud instance runs the version of TinyMCE shipped to enterprise customers, so it's had more QA, etc... than the open source community version. It'll be updated sometime next week with TinyMCE 5.4.2.
