### ISSUE TITLE
I can't find what I'm looking for: demo/format-html5.md

### ISSUE THREAD

**Issue by fathergorry** [tinymce/tinymce#5974]
Option "wrapper:true" maybe not working. 
For example, section and article tags just being split inside block children: < li>< section>< /section>< /li> < li>< section>< /section>< /li> instead of desired < section>< li></li>< li>< /li>< /section>

**Comment by lostkeys** [comment]
Hi @fathergorry. Having `<section>` wrapping `<li>` isn't valid HTML so TinyMCE cleans it up for you. List items must be wrapped in `<ol>`, `<ul>` or `<menu>`. If you explain better what you try to achieve we might be able to provide a solution.

**Comment by fathergorry** [comment]
Please take a look at the screenshot. 
http://prntscr.com/u2dba2
The whole content was selected by Ctrl+A, than style format was applied with tag:section, wrapper_true, merge_siblings: false or true
The first  < section > was wrapped around h1+ul+h2
The second one was wrapped around the <ul>
There were different editor behaviors so far, from wrapping each < li > to wrapping the whole document in single tag with no particular regularity. 

Expected behavior: no wrap breaks and duplicates except those strictly prohibited in html standard description.

**Comment by ltrouton** [comment]
If you add `block_expand: true` to your registered format, this should resolve the inconsistencies you are seeing. Let us know if this is what you were after.

**Comment by fathergorry** [comment]
@ltrouton thanks, this might help.

**Comment by lostkeys** [comment]
Alright, seems like you're on a path to solving this issue. Feel free to reopen this ticket if @ltrouton's solution didn't work out.
