### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by Cankar001** [tinymce/tinymce#5977]
**What is the current behavior? Describe the bug**
I use KingComposer as a visual editor and if I try to edit a textbox TinyMCE shows the Error: "Tinymce Error!". After inspecting the developer console I noticed the error above appears every time I try to edit the textbox. The callstack leads me to editor.min.js?ver=5.5 and to a js file of kingComposer, but it seems to call tinyMCE code which generates this undefined behaviour error.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
![screen](https://user-images.githubusercontent.com/53074877/90627982-16a40b80-e21d-11ea-972d-246c5fb0dc3d.PNG)
![screen1](https://user-images.githubusercontent.com/53074877/90627984-173ca200-e21d-11ea-98ac-78b8cc43b62e.PNG)

**kc.tools.js:**
![screen2](https://user-images.githubusercontent.com/53074877/90628132-61258800-e21d-11ea-8cb4-84f2612815a3.PNG)

**editor.min.js**
![screen3](https://user-images.githubusercontent.com/53074877/90628602-2ff98780-e21e-11ea-893f-49ec3e1a8850.PNG)

**What is the expected behavior?**
The Textbox should open in KingComposer and I should be able to edit the textbox properties (none of them are showing except for the extra class field at the very bottom and the TinyMCE Error)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It worked in previous versions of TinyMCE, it seems that the error was implemented by the last update of TinyMCE and kingComposer.
**My versions:**
KingComposer: 2.9.5
TinyMCE Advanced: 5.5.0
Wordpress: 5.5
Browser: Google Chrome (Version: 84.0.4147.125)

**Comment by ltrouton** [comment]
Thanks for posting. It looks like this may be an error with how KingComposer is integrating TinyMCE or more specifically, 'TinyMCE Advanced' into their application. As a result, it might better to contact KingComposer directly. Additionally, it is worth noting that 'TinyMCE Advanced' is a third party integration for Wordpress and is not something we can provide support for. 

I am going to close this issue but if there is an issue with TinyMCE core, I am happy to reopen it.
