### ISSUE TITLE
Editor is blank and not editable after mooving it cross the dom

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [tinymce/tinymce#5979]
Hey Folks,

I'm facing an issue which was rised a few times afaik but never been fixed.

Im moving a Tinymce editor cross the dome. If i move it upward the dom everything is right. But if i'm mooving it downward the dom Tinymce seems to disconnect. The editor and it's menu bar are there but the content is blank and the Editor isn't editable.

This Question is equal:
https://stackoverflow.com/questions/20271876/tinymce-4-blank-editor-after-moving-textarea

In tinymce-vue this seems to happen too
https://github.com/tinymce/tinymce-vue/issues/32

Thanks for your Support :)

**Comment by lnewson** [comment]
This is native browser behaviour, as it'll reload the iframe content and lose all data, which TinyMCE can't prevent. As such, you need to shutdown the editor and re-initialize the editor when moving it in the DOM.
