### ISSUE TITLE
Space text disappear when one image is moved around the text

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#598]
Description of problem:

If you have one image between two words, and you move the image to another place, the space between the two words is deleted.

Steps to reproduce:
1. write any text. For ex: "one two"
2. insert one image in middle of the two words. For ex: "one &ltg;img>two"
3. move the image to another place. For ex: "onetwo &ltg;img>"
4. the space in the middle of the two words disappears. 
 "one two &ltg;img>" -> "onetwo &ltg;img>"

Expected result:
the two words be kept separate
"one two &ltg;img>"

Actual result:
the space disappear
"onetwo &ltg;img>"
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5808](http://archive.tinymce.com/develop/bugtracker_view.php?id=5808) posted by [pepet](http://archive.tinymce.com/profile.php?name=pepet)_

> _**Tags:** [safari chrome safari4 safari5 safari6 chrome10 chrome11 chrome12 chrome13 image]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
