### ISSUE TITLE
Hilitecolor / Forecolor custom formats can not produce valid css class 

### ISSUE THREAD

**Issue by jburghardt** [tinymce/tinymce#5989]
**What is the current behavior? Describe the bug**

Forecolor / Hilitecolor use inline styles to set color. We want custom css classes to do this.
But using custom formats to create a css class produces invalid css classes, as the value always returns a '#'

using following will always produce invalid css
`hilitecolor: { inline: 'span', classes: 'hilitecolor-%value' },
forecolor: { inline: 'span', classes: 'forecolor-%value' },`

** steps to reproduce **

http://fiddle.tiny.cloud/qrhaab

**What is the expected behavior?**

We can use custom formats to produce valid css, by removing "#" from the substituted value 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All versions of 5

**Comment by lostkeys** [comment]
Hi @jburghardt I think you might have forgot to save the fiddle because it isn't complete. We'd love to see the full thing to be able to best help you out...

**Comment by lnewson** [comment]
This is expected behaviour, as the color picker provides valid **colors** (eg RGB, hex, etc...). It should not be used in a class name and I'm afraid that will not work.

What are you attempting to do, as we might be able to provide another alternative.

**Comment by jburghardt** [comment]
@lostkeys it seems i can not save content. But you can reproduce it by using the hilitecolor or forecolor function on any text and inspecting the css.

@lnewson We are trying to match colors by class, not by inline style.

**Comment by lostkeys** [comment]
I think I'm on to a solution, but before I dig too deep, can you confirm the use-case in principle is something similar to someone wanting to use [Bootstrap color classes](https://getbootstrap.com/docs/4.5/utilities/colors/#color) rather than inline styles?

**Comment by lostkeys** [comment]
Just to ask, are you dead set on using the forecolor and backcolor buttons? Because if you have a predefined set of colors you want end-users to pick from, you could also set up the [style formats menu](https://www.tiny.cloud/docs/demo/format-custom/) to show the colors, which can be better if the colors have meaning, like "primary", "warning" etc...

**Comment by jburghardt** [comment]
> I think I'm on to a solution, but before I dig too deep, can you confirm the use-case in principle is something similar to someone wanting to use [Bootstrap color classes](https://getbootstrap.com/docs/4.5/utilities/colors/#color) rather than inline styles?

yes, exactly.

> Just to ask, are you dead set on using the forecolor and backcolor buttons? Because if you have a predefined set of colors you want end-users to pick from, you could also set up the [style formats menu](https://www.tiny.cloud/docs/demo/format-custom/) to show the colors, which can be better if the colors have meaning, like "primary", "warning" etc...

We want to use the buttons. the foreolor is really just the color without meaning. 
The hilitecolor, ideally having a different color_map, could have a meaning.

**Comment by jburghardt** [comment]
Looking at the style formats, i think this is the way to go instead of using background-color.

with  the Hilitecolor we actually want to use produce something like "<mark> test </mark>" instead of setting the background color.

**Comment by lostkeys** [comment]
Alright, sounds like your on a path to a solution. Here are more ideas on how to create custom menus and toolbars for choosing colors. Inpect the source code for detailed documentations.
https://tinymce.github.io/tinymce-demos/tinymce-basics/custom-toolbar-button-menu-and-context-toolbar.html
https://tinymce.github.io/tinymce-demos/tinymce-basics/customizing-the-table-toolbar.html
