### ISSUE TITLE
Build instructions are apparently wrong

### ISSUE THREAD

**Issue by sgbeal** [tinymce/tinymce#5990]
**What is the current behavior? Describe the bug**

Following the build instructions: <https://github.com/tinymce/tinymce/blob/master/CONTRIBUTING.md>

```
[pi@pi4b8:~/src/tinymce]$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
[pi@pi4b8:~/src/tinymce]$ yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
[pi@pi4b8:~/src/tinymce]$ yarn --version
0.32+git
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

See above.

**What is the expected behavior?**

Not sure - never built it before.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Current trunk version [24b3854] on Raspberry Pi OS 10. i have no idea if it works in other distros.

**Comment by lnewson** [comment]
Hi @sgbeal, it looks like you're using a very old version of yarn. You'll need at least version 1.0 installed to be able to build. A quick solution might be to run something like this:
```
npm install -g yarn
```

**Comment by sgbeal** [comment]
Indeed. It's whatever yarn is on this brand-spanking-new Debian-based Raspberry Pi OS. The npm install warns about my system having "only" node 10.21, but that's another issue and the install works. After that "yarn" by itself starts doing something...

Linking dependencies... 32860 of them.

Once again, npm earns its nickname of *Dependencies as a Service*!

Thank you!
