### ISSUE TITLE
Integration for asp.net core/ Blazor

### ISSUE THREAD

**Issue by RaoSaifUllah** [tinymce/tinymce#5991]
Please add integration with asp.net core/ Blazor etc. Wating for your kind reploy.

bc180204667@vu.edu.pk

**Comment by tylerkelly13** [comment]
Hi @bc160200080 ,

Our integrations team is currently researching a blazor integration. I've moved the issue to this repository so the team can keep an eye on it.

Cheers
Tyler

**Comment by vetezeTE** [comment]
I created a Blazor component for TinyMCE and have posted it on stackoverflow.

https://stackoverflow.com/a/62091603/1026576

I could make a contribution here if you guys would find that helpful?
