### ISSUE TITLE
TinyMCE Release Support Cycle

### ISSUE THREAD

**Issue by x86demon** [tinymce/tinymce#5997]
Do you have publicly available Release Support Cycle information?
Would be very handy to know when some version will stop receiving updates.

Example:
| Version | Release date | Maintenance ends | Support ends (including security fixes) |
| --- | --- | --- | --- |
| 4.9.x | November 27, 2018 | ??? | ??? |
| 5.4.x | June 30, 2020 | ??? | ??? |

**Comment by EkimChau** [comment]
Hi x86demon,

The information is available here https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/

**Comment by lnewson** [comment]
To clarify the point above, that page details support for our commercial offering. For our open source offering, we only support the latest release of supported major versions (currently 4.9.11 and 5.4.2).

It's also worth noting that TinyMCE 4 support will end for both commercial and open source on December 31, 2020 as noted here: https://www.tiny.cloud/blog/tinymce-4-support-window/
