### ISSUE TITLE
How can I look up the state of a toggle button?

### ISSUE THREAD

**Issue by dgmlr** [tinymce/tinymce#5998]
I have a button where I would like the onAction to have conditional code that depends on the state of another button (i.e., a toggle button).
But is there any way to look up the state of a toggle button? This seems like an obvious feature, but I can't see anything about this in the API doc.

**Comment by lostkeys** [comment]
Normally you manage the state of buttons yourself so in this case you create your own custom variable that holds the state for the other button to use. If you need further help, don't hesitate to reopen this ticket. Cheers!
