### ISSUE TITLE
on changing textcolor,the pointer jumps to start of textarea

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#600]
Description of problem:

Steps to reproduce:
1. Use advanced tinyMCE.
2. Write something in textarea.
3. Click on change textarea button.The text cursor will focus at the beginning

Expected result:On click of textxolor change a new span is created where the text cursor is there

Actual result:New span is created at the beginning of textarea no matter how long text you have written.Even on clicking at the end,it will take the format of the first span format.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5810](http://archive.tinymce.com/develop/bugtracker_view.php?id=5810) posted by [aditya](http://archive.tinymce.com/profile.php?name=aditya)_

> _**Tags:** [msie msie8 msie9 textcolor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
