### ISSUE TITLE
Can't edit media object with setted video_template_callback

### ISSUE THREAD

**Issue by bes-internal** [tinymce/tinymce#6002]
Step to reproduce:
1. http://fiddle.tinymce.com/8rhaab
2. insert media with some text in source - "111"
3. check code
4. select media object and click on media again to edit
5. enter in source "222" and save
6. media object stay untouced

Expect editing media object at least recreate it with new data 

tinymce v5.4.2

**Comment by metricjs** [comment]
Thanks for the report. I can replicate in 5.2.0 - note for the team: before that step 3 would show `undefined` for the src.

To get a better picture of the problem, @bes-internal did you find this issue with any links to actual media? Embedding and editing a Youtube video seems to work correctly for me.

**Comment by bes-internal** [comment]
Did you read the title? `video_template_callback` was set with non-default `<embed>` . When you insert .mp4 or youtube link it is force `<iframe>` as template (behavior is not documented) where `source` change is already working.
