### ISSUE TITLE
Cant insert pdf datauri in media object

### ISSUE THREAD

**Issue by bes-internal** [tinymce/tinymce#6003]
Try to insert this datauri 

`
data:application/pdf;base64,JVBERi0xLjUKJeLjz9MKNSAwIG9iago8PAovRmlsdGVyIC9GbGF0ZURlY29kZQovTGVuZ3RoIDI3Cj4+CnN0cmVhbQp4nDNUMABCXUMQpWdkopCcy1XIFcgFADCwBFQKZW5kc3RyZWFtCmVuZG9iago0IDAgb2JqCjw8Ci9UeXBlIC9QYWdlCi9NZWRpYUJveCBbMCAwIDAuMjQgMC4yNF0KL1Jlc291cmNlcyA8PAo+PgovQ29udGVudHMgNSAwIFIKL0dyb3VwIDw8Ci9UeXBlIC9Hcm91cAovUyAvVHJhbnNwYXJlbmN5Ci9JIHRydWUKL0NTIC9EZXZpY2VSR0IKPj4KL1BhcmVudCAyIDAgUgo+PgplbmRvYmoKMiAwIG9iago8PAovVHlwZSAvUGFnZXMKL0tpZHMgWzQgMCBSXQovQ291bnQgMQo+PgplbmRvYmoKMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIFIKPj4KZW5kb2JqCjMgMCBvYmoKPDwKL0NyZWF0aW9uRGF0ZSAoRDoyMDIwMDkwMjE0MjEzNCswMycwMCkKL1Byb2R1Y2VyICh3d3cuaWxvdmVwZGYuY29tKQovTW9kRGF0ZSAoRDoyMDIwMDkwMjExMjMxM1opCj4+CmVuZG9iago2IDAgb2JqCjw8Ci9TaXplIDcKL1Jvb3QgMSAwIFIKL0luZm8gMyAwIFIKL0lEIFs8Mjc0NkI2NUFCMUQ2N0QxODE0MzM1MEZDQkIxOTQyRDA+IDxEQzRCN0U3Q0QyNjk2NkM1QjRDMzUzM0NCNDYzNzRGMz5dCi9UeXBlIC9YUmVmCi9XIFsxIDIgMl0KL0ZpbHRlciAvRmxhdGVEZWNvZGUKL0luZGV4IFswIDddCi9MZW5ndGggMzUKPj4Kc3RyZWFtCnicY2Bg+P+fkTGMgYGRURZEtAMJhkIQwQ/i/mVgAABeRgSACmVuZHN0cmVhbQplbmRvYmoKc3RhcnR4cmVmCjUwOQolJUVPRgo=
`

to
http://fiddle.tinymce.com/7rhaab

expect embed media template with <source> and src with this datauri

But this datauri is working

`
data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
`

tinymce v5.4.2

**Comment by ashfordneil** [comment]
Hi Vladimir,
At this point in time the media plugin only supports embedding videos or audio into the editor content, and there isn't any other plugin that would let you import PDFs. As such I'm going to label this as a feature request, to go on our product backlog.
