### ISSUE TITLE
Table of Contents issue

### ISSUE THREAD

**Issue by thogan1** [tinymce/tinymce#6004]
**What is the current behavior? Describe the bug**
When creating the table of contents and assigning tags to the headers, the table of contents link will not take you to the designated section.  

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Insert Anchor on header(s)
2. Insert Table of Contents
3. Right click on table of contents header entry and select link
4. Select Anchors field, select entry from Step 1.
5. Entry title for organization.
6. Click save

**What is the expected behavior?**
Selecting the item inside the table of contents should take you to the specific paragraph or area that has been entered as an anchor on the page.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I'm using the demo on the TinyMCE page, using Chrome and the new Chromium Edge Browser.  We were looking to implement and I wanted to demo to make sure it fits the requirements, but it doesn't work.

I've tested on both the demo page as well as the landing page of TinyMCE
https://www.tiny.cloud/docs/demo/full-featured/
https://www.tiny.cloud/

**Comment by lostkeys** [comment]
The table of contents feature creates and manages it's own anchors and links. To follow them within the TinyMCE editor, hold down `cmd` (on Mac) or `alt` on (Windows) while clicking the link. (I'm on a mac so I'm not 100% sure which modifier key is used with Windows).

I hope this answers your question, and if not, please reopen this issue.

**Comment by thogan1** [comment]
Thank you, this works.
