### ISSUE TITLE
Focus get lost after change tinymcespellchecker language

### ISSUE THREAD

**Issue by rskrzypczynski** [tinymce/tinymce#6008]
**What is the current behavior? Describe the bug**

On selection of spellcheck language focus is lost instead of go back to editor or menu.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

At demo  site https://www.tiny.cloud/docs/demo/full-featured/ navigate with keyboard to:

1. Tools
2. Spellcheck Language
3. Choose any option

**What is the expected behavior?**

Focus return to editor or menu.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE v5, all browsers.
This works on previous versions of TinyMCE - focus is back to menu.

**Comment by lnewson** [comment]
Thanks for the report, however SpellChecker Pro is a premium product and this GitHub project is for the open source version of TinyMCE, so I'm afraid we can't assist via GitHub. If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
