### ISSUE TITLE
Problem while trying to open tinymce editor for second time in modal popup in php

### ISSUE THREAD

**Issue by JeniChevli** [tinymce/tinymce#6012]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by metricjs** [comment]
Hi @JeniChevli, please fill out the questions in the ticket template with more information so we can try to replicate this.

**Comment by lnewson** [comment]
Closing this due to lack of additional information. If you can provide the information requested above, then we'll be happy to reopen this.
