### ISSUE TITLE
Infinite parsing of malformed comments

### ISSUE THREAD

**Issue by charsbar** [tinymce/tinymce#6014]
**What is the current behavior? Describe the bug**
TinyMCE 5.20 fixed incorrect parsing of malformed/bogus HTML comments, but the fix has a bug that does not finish parsing malformed comments under some condition.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Visit the TinyMCE home page and click ```view``` and then ```source``` menu. Replace the entire source code with ```<!-- value -->\n<!-- value```, and save. The dialog won't close.

**What is the expected behavior?**
The parse finishes and the dialog closes.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This bug is a regression introduced by TinyMCE 5.20, specifically  https://github.com/tinymce/tinymce/commit/09fbbb58a56819c5276ae41dc2aee1e009244705#diff-892bb2f73be01889d153d703d105c0cfR145.

**Comment by lnewson** [comment]
Sorry this wasn't updated when the fix for this was released, however this was fixed by https://github.com/tinymce/tinymce/pull/6396 which was included in the TinyMCE 5.7 release back in February.
