### ISSUE TITLE
Toolbar buttons clicked when swiping on mobile.

### ISSUE THREAD

**Issue by maciejmackowiak** [tinymce/tinymce#6020]
**What is the current behavior? Describe the bug**
When swiping on mobile starts on toolbar item it gets fired/clicked.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Steps to reproduce:
On mobile device:
1. Go to: https://www.tiny.cloud/docs-4x/demo/basic-example/
2. Swipe down but first touch(touchstart event looks to be the culprit) must happen on any toolbar item.
3. The item gets "clicked"

**What is the expected behavior?**
Do not fire toolbar events while swiping.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tinymce v4
Browser: Firefox, Chrome and probably any other browser

**Comment by lostkeys** [comment]
What mobile phone and browser are you using? I'm unable to replicate this on iOS and my samsung test device.

**Comment by archon810** [comment]
I am seeing the same issue in Chrome 85 stable on Android 11 (as well as 10), Pixel 4 XL.

**Comment by archon810** [comment]
Here's a quick demo: https://i.imgur.com/qw4VBPK.gifv.

**Comment by lostkeys** [comment]
Thanks for the update!

Can you confirm you're using the mobile theme: https://www.tiny.cloud/docs-4x/mobile/

Also, can you confirm this is what you see when you visit the basic example (the gray overlay with the icon in the middle):
![image](https://user-images.githubusercontent.com/3122929/92691820-7a64b480-f343-11ea-8052-77f2257ba0ac.png)

**Comment by archon810** [comment]
I'm going to let @maciejmackowiak reply regarding the mobile theme, but what doesn't make sense to me is we're just using TinyMCE built into WordPress - shouldn't it "just work"? Is this a bug in WP where it's not loading TinyMCE in the mobile-optimized mode?

**Comment by lostkeys** [comment]
@archon810 Wordpress has built their own UI for TinyMCE so you have to direct your questions to them in this case.

**Comment by maciejmackowiak** [comment]
Thanks for your help @lostkeys 
You are right, the issue is related to non-mobile theme, I had different user agent that is why https://www.tiny.cloud/docs-4x/demo/basic-example/ was not working properly for me, sorry for the confiusion.

Here is the correct example without mobile theme:
https://codepen.io/maciejmackowiak/pen/GRZXWpp

So the issue is that the non-mobile theme should not "fire" toolbar events when swiping.

**Comment by lnewson** [comment]
Hi @maciejmackowiak, the "modern" theme in TinyMCE 4 only supports desktops, so it's not really expected to work on mobile.

Additionally, TinyMCE 4 is now only receiving critical bug fixes for the open source version, so I'm going to close this sorry. I'd recommend updating to TinyMCE 5, where the "silver" theme does support mobile/touch devices fully and this issue shouldn't occur. If you can reproduce this in TinyMCE 5, then please do let us know and we'll reopen this issue.

**Comment by archon810** [comment]
WordPress, sadly, has no current plans to update to TinyMCE 5 https://core.trac.wordpress.org/ticket/47218.
