### ISSUE TITLE
Is there a way to import static resources instead of setting a url?

### ISSUE THREAD

**Issue by cloydlau** [tinymce/tinymce#6021]
**Is your feature request related to a problem? Please describe.**
It's very necessary when using tinymce in a library. Otherwise all the static resources like language, theme, css etc. must be copied as assets outside the library once again. But the library users shouldn't bother to do this.

**Describe the solution you'd like**
There should be some options like 'language_file', 'theme_file', 'content_css_file', so that I can bundle them with webpack.

Such as:
```js
import theme from './static/theme.min.js'

{
  theme_file: theme
}
```

**Comment by SimonFc** [comment]
It is possible for you to create a bundle. Read more about [<ins>Usage with module loaders</ins>](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/). This applies to all JS, including language and icon packs. What you do with the CSS found at `tinymce/skins/` depends on your setup.

**Comment by cloydlau** [comment]
> It is possible for you to create a bundle. Read more about [Usage with module loaders](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/). This applies to all JS, including language and icon packs. What you do with the CSS found at `tinymce/skins/` depends on your setup.

That's perfect! Thanks.
