### ISSUE TITLE
There is an error when I insert a link on a picture

### ISSUE THREAD

**Issue by lixpng** [tinymce/tinymce#6026]
**What is the current behavior? Describe the bug**
Cut a screenshot and paste into tinymce, choose the picture and insert link in toolbar, and save.
Then re-edit the link, when delete completely the **URL**, it will recover to the prev url.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/yshaab/3
![image](https://user-images.githubusercontent.com/19266401/92876312-8c764e00-f43c-11ea-979a-e819e60d593c.png)

**What is the expected behavior?**
When delete the **URL** completely, it shouldn't recover to prev url.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
* tinymce: 5.2.2
* borwser: chrome 84.0.4147.125
* OS: macOS Mojave 10.14.4

**Comment by lincolndennis** [comment]
I can confirm this behavior in 5.2.2. However, in our current stable release, 5.4.2, it appears this behavior has changed. In this version, deleting the URL in the manner you describe is allowed and consequently removes the link/anchor tag.

Here is a modified version of your Fiddle using this current version:
https://fiddle.tiny.cloud/yshaab/4

Can you confirm that behavior?

**Comment by lixpng** [comment]
> I can confirm this behavior in 5.2.2. However, in our current stable release, 5.4.2, it appears this behavior has changed. In this version, deleting the URL in the manner you describe is allowed and consequently removes the link/anchor tag.
> 
> Here is a modified version of your Fiddle using this current version:
> https://fiddle.tiny.cloud/yshaab/4
> 
> Can you confirm that behavior?

Yeah, I can confirm that, it has been fixed, thanks for your reply.
