### ISSUE TITLE
remove border 

### ISSUE THREAD

**Issue by saeedegh** [tinymce/tinymce#6032]
hello.
first of all thank you for your great editor.
now i need to remove editor borders. i tried these:
```
{
 statusbar: false,
            content_css : 'textarea{border:none !important;}' ,
            content_style:'textarea{border:none!important;}',
            editor_css : 'textarea{border:none !important;}',
            editor_style:'textarea{border:none !important}'
}
```
but it doesnot work.
should i create a custom them to remove editor border or no need it?
how can i remove tiny mce editor border ?

**Comment by ashfordneil** [comment]
Applying styles to the `textarea` isn't going to work directly. When tiny loads in iframe mode (the default) we hide the element that you specified in your selector, and create a div (containing an iframe) after it in the dom. If all you want to do is remove the border from that div, you might be able to do something using the [CSS child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator) to target that div based on its position relative to content you control in the CSS on your page.

If you're interested, as an alternative we have made a "Borderless" skin that will do this for you. You can check it out here: https://www.tiny.cloud/docs/enterprise/premium-skins-and-icon-packs/borderless-demo/ but it is a premium only skin.

**Comment by lostkeys** [comment]
You can also use our skin tool to do this for free:

1. Go to http://skin.tiny.cloud/t5/
2. In the "Styles" pane, press "Advanced mode"
3. Delete all the LESS variables (the ones starting with `@`)
4. Add `@tinymce-border-width: 0;`. You should now see a borderless editor in the preview pane.
5. Download the skin

[Read more about creating skins here](https://www.tiny.cloud/docs/advanced/creating-a-skin/)
