### ISSUE TITLE
can't upload jfif image

### ISSUE THREAD

**Issue by 675076143** [tinymce/tinymce#6034]
**What is the current behavior? Describe the bug**
upload jfif image shows no response
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
check out the official example:
https://www.tiny.cloud/docs/demo/local-upload/
**What is the expected behavior?**
it should be successful uploaded but not
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
* "tinymce": "5.2.2"
* "@tinymce/tinymce-react": "^3.6.0"
* chrome, edge

**Comment by ashfordneil** [comment]
We currently only support a few image extensions: '.jpg,.jpeg,.png,.gif'
I'll mark adding support for .jfif files as a feature — looks like browsers can read and display them, so it should be possible for us to add them in.

**Comment by eyu0415** [comment]
> We currently only support a few image extensions: '.jpg,.jpeg,.png,.gif'
> I'll mark adding support for .jfif files as a feature — looks like browsers can read and display them, so it should be possible for us to add them in.

Is there planning for support pdf, svg?

**Comment by zhailingzy** [comment]
may I ask for the support of tif/tiff file?

**Comment by lnewson** [comment]
@zhailingzy TIFF is not an image format supported by browsers (Safari being the exception), so we won't be adding support for that sorry. https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types details what are valid web image formats.

**Comment by lnewson** [comment]
I should add though, that in TinyMCE 5.6 we'll be adding a setting to allow integrators to configure what image formats (and only image formats) can be uploaded or used with the smart paste functionality. We'll also be updating the default list to include the more common formats such as `jfif`. As such, you might be able to use that once released, however do note that the images likely won't render or function in other ways as browser don't support the TIFF image format as previously mentioned and still won't be supported or be in the default list.
