### ISSUE TITLE
It is not a good solution to introduce skin automatically. It would be better to provide a solution for developers to introduce skin themselves, especially when using webpack to package files.

### ISSUE THREAD

**Issue by jiankafei** [tinymce/tinymce#6038]
**Is your feature request related to a problem? Please describe.**
It is not a good solution to introduce skin automatically. It would be better to provide a solution for developers to introduce skin themselves, especially when using webpack to package files.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by lostkeys** [comment]
Hi, @jiankafei! Sorry, we need some more details to be able to evaluate your request. Please update the ticket with more specific issues you are running into and we can reopen this ticket
