### ISSUE TITLE
Placeholder cannot have special characters

### ISSUE THREAD

**Issue by ansierras** [tinymce/tinymce#6039]
**Is your feature request related to a problem? Please describe.**
I need to use special charaters in my placeholder text, such as line breaks, bulletpoints, etc. Currently only a normal string is allowed

**Describe the solution you'd like**
Allow the usage of html or utf-8 characters in order to make more engaging placeholders

**Describe alternatives you've considered**
We are using the placeholder plugin to inject html into the placeholder but it is currently a hack and not really best practice

**Comment by lostkeys** [comment]
Thanks for your feature request. While we think about this feature you can have a look at this demo https://tinymce.github.io/tinymce-demos/templates-and-layout/advanced-placeholder.html
