### ISSUE TITLE
Selected arrow no present in Styles menu if style contains background color 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#604]
Description of problem:

If a style contains a background color, the menu_arrow.gif background of its parent &ltg;a> tag will not be present.

Steps to reproduce:
1. Add a style that contains a background color
2. Apply this style to selected text and view the styles dropdown
3. Note the arrow indicating a selected style is not present
4. Remove the background color from the style and repeat steps 1-2
5. Note the arrow is present

Expected result:

The menu_arrow.gif icon should be present to indicate a style is selected.

Actual result:

The menu_arrow.gif icon is not present. The style's background color is over-layed on top of the parent a.

Notes:

A possible workaround could be to add additional padding-left to the following selector:

.defaultSkin .mceNoIcons .mceMenuItemSelected a
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5813](http://archive.tinymce.com/develop/bugtracker_view.php?id=5813) posted by [rgriffith](http://archive.tinymce.com/profile.php?name=rgriffith)_

> _**Tags:** [firefox msie safari chrome opera styles ui theme]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/ecdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
