### ISSUE TITLE
复制图片显示图裂

### ISSUE THREAD

**Issue by mesxie** [tinymce/tinymce#6044]
![image](https://user-images.githubusercontent.com/41989520/93729949-18386900-fbf9-11ea-8b1d-f4bb8ffa5be3.png)
![image](https://user-images.githubusercontent.com/41989520/93729958-1e2e4a00-fbf9-11ea-81fb-87433f976b1f.png)
复制图片到富文本出现图裂的情况并且右键选择图片菜单时出现的窗口中，图片链接是空的，但是富文本内容中有正常创建img标签并且src属性没错

**Comment by ashfordneil** [comment]
Sorry, we can only accept issues in English. Please reopen or open a new issue if you can translate your issue/question into English.
