### ISSUE TITLE
Bullet list starting from previous line if text format applied to previous line (5.4.2)

### ISSUE THREAD

**Issue by punchpudding** [tinymce/tinymce#6047]
**What is the current behavior? Describe the bug**
Creating a new bullet list when the previous line of text includes formatted text moves the previous line of text into the new bullet list.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. initialize tinymce with force_p_newlines : false
2. select a font style applied (e.g. bold, italic)
3. type some text
4. press enter
5. press the bullet list button
6. the bullet list will "pull down" text from the previous line into the new bullet list

If you type formatted text and then unformatted text in the first line, only the unformatted text is pulled down.

**What is the expected behavior?**
A new bullet list should be created without affecting the previous lines of text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.4.2
Chrome
This feature worked in TinyMCE 4.X

**Comment by HAFRMO** [comment]
The `force_p_newlines` setting is deprecated, try `forced_root_block` instead if possible (https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block) and please give more info e.g. steps that work vs don’t, and examples of the editor html in both cases?

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
