### ISSUE TITLE
Editor shows message to activate

### ISSUE THREAD

**Issue by joseluizjlcj** [tinymce/tinymce#6057]
Hello, I put my TinyMce in my project and now it shows a message asking to activate the product.

How do I maintain it with the FREE version?

I am using this package "@tinymce/tinymce-react" in my application with ReactJS.

**Comment by ltrouton** [comment]
Hi @joseluizjlcj. Have you set up an API key yet? If not, this post might help you get started https://www.tiny.cloud/blog/how-to-get-tinymce-cloud-up-in-less-than-5-minutes/. We also have integration docs for React which can seen [here](https://www.tiny.cloud/docs/integrations/react/). 

Let us know if this is what you were after.
