### ISSUE TITLE
Problem with pasting links into editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#606]
Description of problem:

When i paste link (copied from my chrome address bar) into editor and go to new line with Shift+Enter, first letter of new line becomes part of previous link.

Tested in Win 7 + Chrome 26. No error in Firefox. Can't test other browsers.

Steps to reproduce:
1. Open editor.
2. Copy link from browser's address bar
3. Paste a link to editor
4. (important) Place cursor to other position, then place it to end of link (for example use Home and End key)
5. press Shift+Enter and begin typing text

Expected result:
Link will be only on first line

Actual result:
First letter of the next line becomes a link

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5815](http://archive.tinymce.com/develop/bugtracker_view.php?id=5815) posted by [smilingcheater](http://archive.tinymce.com/profile.php?name=smilingcheater)_
> 
> _**Tags:** [chrome links]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/index.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by theplz007** [comment]
I still have this problem in 4.4.3
It happens when you paste the link and **directly** afterwards press enter.
Then, the first character of the new line is a part of the link.

**Comment by blackcathikari** [comment]
@theplz007 Sorry, I'm still having trouble replicating this problem. Could you please check if it happens on [](http://fiddle.tinymce.com/)? Also, what OS and browser are you using? I tested on Win 7 Chrome 53, since Chrome was mentioned in the original post.

**Comment by donShakespeare** [comment]
Tested on http://fiddle.tinymce.com/ 
With latest builds of browsers

Firefox, on linebreak, continues the link for each linebreak.
Chrome, on linebreak, continues the link for only first letter, for only first linebreak.

In each, in view source, `br` is added as expected within the link tag.

In each, when the link is edited, the `br` within link is completely stripped.

**Comment by blackcathikari** [comment]
Thanks @donShakespeare, we've replicated it now. I'll reopen this ticket.

**Comment by fyrkant** [comment]
I think the inline boundaries added to the editor in 4.6 should have solved this problem (it is now easy to choose to write inside link or not) so I am closing this issue. Please leave a comment if you disagree and I can open it again.
