### ISSUE TITLE
inline editor for iframe elements does't format their content

### ISSUE THREAD

**Issue by VitaliyOnRule** [tinymce/tinymce#6062]
When we init editor in inline mode but for elements which belong to iframe - it renders toolbar after click and we are do able to edit text
 but formatting text (alignment, bold, italic, e.t.c) are not working

demo:
https://jsfiddle.net/vitaldo/4tujLxzy/6/

We are expecting that it will work for iframe elements as well - either by default or by specifying some properties during initialization
TinyMCE - 5.4.2

For for TinyMCE4 it could be partially fixed by specifying such properties for "init" config object
"content_window"
"content_document"
 and even in this case alignment is not working

**Comment by lostkeys** [comment]
@VitaliyOnRule While we wait for more technically knowledgeable people to answer, can you elaborate more on the use case, what you want to achieve with such an implementation ☺️. Thx!

**Comment by VitaliyOnRule** [comment]
@lostkeys We are creating an email editor and email itself should be rendered inside iframe. And also we need integration with grapes.js - emails there also are rendered inside iframe

**Comment by lostkeys** [comment]
So we discussed this internally and unfortunately we have no plans to adress this issue. The options for content_window and contend_document were added a long time ago but never worked alright and caused memory leaks and weren't carried over to TinyMCE 5. What is keeping you from just running TinyMCE in inline mode inside the iframe?

**Comment by VitaliyOnRule** [comment]
In the first case - I have tough interaction between app and iframe and I need to handle changes outside iframe
In the second case - iframe is generated by library(grapesjs) and the only one way to replace default editor with tinymce is via library api which happens on the main window.
