### ISSUE TITLE
automatically add namespace on tags

### ISSUE THREAD

**Issue by arnaudbey** [tinymce/tinymce#6063]
Hi there,
I'd like to know if there's a way to add namespace on tags. I'm working on a project, allowing ppl to insert TEI-XML tag like "title" for example, which obviously collides with HTML one and causes some problems.
i found out an old "custom_tag_ns_prefix" option on a forum, but there's no trace of it in documentation, nor anything related to it

Thanks again for your time & great work ! 
Arnaud

**Comment by lostkeys** [comment]
Hi @arnaudbey! Can you elaborate into more details what you want to achieve. TinyMCE is very configurable and has plenty of options related to custom tags and formatting but without knowing exactly what you want it's hard to point you in the right direction.

**Comment by arnaudbey** [comment]
Hi @lostkeys 
We're developping an XML editor around tinyMCE basis. [Here](https://gitlab.com/litt-arts-num/tact/-/blob/master/application/modules/tei-editor.js) is kind of a draft of the module. (Sorry for your eyes, code is not that pretty).

We're using `dom.create()` method to create tag who will be inserted in the editor (through the `range.insertNode()` method). The problem is that, tags we insert can collide with HTML ones; For exemple `<title>`, who has another meaning and use in XML-TEI, is interpreted in tinyMCE as the HTML `<head> child`. 

That's why I'm looking for a way to namespace element I insert. (i.e. `<mynamespace:title>`) to make them handled differently by TinyMCE.

Would this be possible?

**Comment by lostkeys** [comment]
The problem isn't really with TinyMCE, as the title tag shows up with the config options you're using (and you could [style it using formats](https://www.tiny.cloud/docs/configure/content-formatting/#formats). The problem you're facing is that TinyMCE renders through a web browser, and there is little we can do to trick Chrome and Firefox into believing that tags like `<head>`, `<meta>` or `<body>` mean something else.
The proper way to ["namespace" custom elements](https://html.spec.whatwg.org/#valid-custom-element-name) is to use a dash, like this `<mynamespace-title>`.

**Comment by arnaudbey** [comment]
Indeed, I thought about custom elements, but I secretly hoped there was another magic solution :D 
Anyway, thanks for your answer !
