### ISSUE TITLE
i made a plugin table of indent i found some issue any one help me fix this issues

### ISSUE THREAD

**Issue by raselcse13** [tinymce/tinymce#6065]
(function () {
    'use strict';

    var global = tinymce.util.Tools.resolve('tinymce.PluginManager');

    var open = function (editor) {
      editor.windowManager.open({
        title: 'Indent Table',
        size: 'normal',
        body: {
          type: 'panel',
          items: [{
              name: 'indentSize',
              type: 'input',
              label: 'Indent Size (px): ',
              placeholder: 'Exmple: 4'
            }]
        },
        buttons: [
          {
            type: 'cancel',
            name: 'cancel',
            text: 'Cancel'
          },
          {
            type: 'submit',
            name: 'save',
            text: 'Save',
            primary: true

          }
        ],
        onSubmit: function (api) {
          var data = api.getData();
          var table = document.getElementsByTagName("table")[0];
          var indentSize = data.indentSize;
          table.style.textIndent = indentSize + "px";  
          api.close();
        }
      });
    };

    var register = function (editor) { 
      editor.addCommand('mceindentTable', function () {
        open(editor);
      });
    };

    var setContentEditable = function (state) {
      return function (nodes) {
        for (var i = 0; i < nodes.length; i++) {
          nodes[i].attr('contenteditable', state);
        }
      };
    };
    var setup = function (editor) {
      editor.on('PreInit', function () {
        editor.parser.addNodeFilter('a', setContentEditable('false'));
        editor.serializer.addNodeFilter('a', setContentEditable(null));
      });
    };

    var register$1 = function (editor) {
      editor.ui.registry.addToggleButton('indentTable', {
        icon: 'indent',
        tooltip: 'Indent Table',
        onAction: function () {
          return editor.execCommand('mceindentTable');
        },
        onSetup: function (buttonApi) {
          return editor.selection.selectorChangedWithUnbind('a:not([href])', buttonApi.setActive).unbind;
        }
      });
      editor.ui.registry.addMenuItem('indentTable', {
        icon: 'indent',
        text: 'indentTable...',
        onAction: function () {
          return editor.execCommand('mceindentTable');
        }
      });
    };

    function Plugin () {
      global.add('indentTable', function (editor) {
        setup(editor);
        register(editor);
        register$1(editor);
      });
    }

    Plugin();

}());

![image](https://user-images.githubusercontent.com/24198895/94520037-68dd4100-024d-11eb-87e8-b8cbabffde12.png)

**Comment by lostkeys** [comment]
Hi @raselcse13! [Look at this fiddle](http://fiddle.tinymce.com/Tthaab), especially row 44, 45, 46. Please feel free to reopen this issue if you need more help.
