### ISSUE TITLE
I can't find what I'm looking for: plugins/charmap.md

### ISSUE THREAD

**Issue by abartov** [tinymce/tinymce#6069]
I use TinyMCE 5.4.1. 

My users are reported a "failed to initialize plugin: charmap".  I cannot reproduce it.  The docs do not suggest any reason that would cause this plugin to fail.

**Comment by abartov** [comment]
Thank you, @tylerkelly13 tylerkelly13.

I have now figured it out.  It was caused by stale assets in my deployment.  I thought I had ruled that out, so filed this issue, but I was mistaken.

(There is still a potential documentation improvement here:  the _actual_ error preventing initialization here was a call (by an older asset) to editor.addButton instead of to registry.ui.addButton.  This was only visible in the JS console.

Anyway, no further attention needed here, thanks!

**Comment by tylerkelly13** [comment]
Awesome!

Heads-up, if you're upgrading from TinyMCE 4, we have docs that can help, but it sounds like you've sorted most of it out.

Here's the link anyway: https://www.tiny.cloud/docs/migration-from-4x/

Cheers
Tyler
