### ISSUE TITLE
menu printing in 4.0b1 inline demo

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#607]
Description of problem:

Steps to reproduce:
1. in the menu, click on "print"

Expected result:
The page as it currently is should be printed without the tinyMCE menu

Actual result:
The menu is part of the print.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5817](http://archive.tinymce.com/develop/bugtracker_view.php?id=5817) posted by [johanneswilm](http://archive.tinymce.com/profile.php?name=johanneswilm)_

> _**Tags:** [firefox msie safari chrome opera 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
