### ISSUE TITLE
Typescript definition for EditorSettings is wrong

### ISSUE THREAD

**Issue by sunkan** [tinymce/tinymce#6075]
Currently the `EditorSettings.plugins` type is set to only accept `string` and not `string|string[]`

But your code that normalize the plugins setting accepts both as shown: [EditorSettings.ts](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/EditorSettings.ts#L45)

**Comment by lnewson** [comment]
Hi @sunkan, the editor will always normalise the plugins to be a `string` during instantiation, so the types are correct (see https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/EditorSettings.ts#L180). I suspect the type you want is `RawEditorSettings`, as that's the type used for configuring the editor and it does allow `string | string[]`.

**Comment by sunkan** [comment]
Thanks for the response
