### ISSUE TITLE
plugin_preview_max_width option [Updated - Feature Request]

### ISSUE THREAD

**Issue by FilipQL** [tinymce/tinymce#6076]
**UPDATED [FEATURE REQUEST]**

I'm trying to set the "max-width" of the preview dialog. It would still be responsive but it will not take the whole screen (width). 
For example, on desktop (normal/large screens) my articles are no wider than ~650px (I'm using bootstrap 4).
So I would like to have the same "preview"  (with the same width) as articles (as it would better show how article is going to look after submitting). 
Maybe introduce `plugin_preview_max_width` option: when set, the preview dialog will still remain responsive but it cannot be wider than _value_. 

-------------------------------------------------------------------------------------

ORIGINAL COMMENT:

**BUG DESCRIPTION:**

`plugin_preview_width` option is ignored.  For example:

```
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "preview",
    ],
    toolbar: "bold italic | preview",
    plugin_preview_height: 200,
    plugin_preview_width: 200,
});
</script>

<form method="post" action="dump.php">
    <textarea name="content">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</textarea>
</form>
```
As you can see, `plugin_preview_width` is set to `200`, but that's ignored: 

![TinyMCE Fiddle - Mozilla Firefox 2020-10-01 23 24 44](https://user-images.githubusercontent.com/18264428/94865186-72c59680-043d-11eb-862f-4c3bc2beee8f.png)

**DEMO:**

http://fiddle.tinymce.com/nuhaab

**What is the expected behavior?**

Apply `plugin_preview_width`. Also, it would be good to apply this option as `max-width`, not `width` (so that it can be responsive, if I'm not wrong).

**I'm using:**

- TinyMCE 5.4.2
- Browsers: Firefox 81.0 (64-bit); Chrome 85.0.4183.121 (64-bit);
- OS: Windows 7 (64-bit)

**Comment by lnewson** [comment]
Hi @FilipQL, this is expected as that's not a valid setting in TinyMCE 5. You can see all the settings for the preview plugin here: https://www.tiny.cloud/docs/plugins/preview/

Could you elaborate on what you are trying to do? As the dialogs in TinyMCE 5 are responsive, so they cannot be assigned a fixed width/height. So if you can let us know your use case, we might be able to come up with some other suggestions.

**Comment by FilipQL** [comment]
Hi @lnewson,

> this is expected as that's not a valid setting in TinyMCE 5.

Aha, I was probably looking wrong documentation. 

> Could you elaborate on what you are trying to do? As the dialogs in TinyMCE 5 are responsive, so they cannot be assigned a fixed width/height. So if you can let us know your use case, we might be able to come up with some other suggestions.

I'm trying to set the "max-width" of the preview dialog. So, it would still be responsive, but it will not take the whole screen (width). 
For example, on desktop (normal/large screens) my articles are no wider than ~650px (I'm using bootstrap 4).
So I would like to have the same "preview" (as it would better show how article is going to look after submitting). 
Maybe introduce `plugin_preview_max_width` option: when set, the preview dialog will still remain responsive but it cannot be wider than _value_.

**Comment by lnewson** [comment]
Sorry for the delayed reply, but I've marked this as a feature request for our PM team to review.

**Comment by lostkeys** [comment]
The preview dialog reflects the content styles. TinyMCE is a WYSIWYG editor, so the content you're editing sorta is your preview. What the preview window do is hide some visual aids, like dotted borders around borderless tables and anchor markers etc. To solve your particular use-case, simply add the max width to your content style.
Here is a demo: http://fiddle.tinymce.com/nvhaab

However, this surfaced another bug. In TinyMCE content iframe the styles defined in content_styles option are injected last, overriding any existing styles set by the skin or an external content_css. However, in the _Preview dialog_ iframe, the content_styles are loaded first, thus being overridden instead of being the overrider (forgive my English).
