### ISSUE TITLE
Wrap emojis option

### ISSUE THREAD

**Issue by FilipQL** [tinymce/tinymce#6077]
**Problem:**

On my project body (p) text size is 16px (1rem). This is OK for text, however Emojis are too small (1rem/16px Emojis are looking bad). In my case, 1.5rem as font size just for emojis would look good. I would like to be able to control/set Emoji font-size independent of the rest of the text.

**Solution:**

To be able to achieve this, one way would be to put emojis within `<span>` element and have an option to specify class or other attributes of this wrapper (span) tag. This would allow us to specify different font-size of Emojis. 

So, for example we would have option `emoticons_wrapper`: 

```
  emoticons_wrapper: {
    tag: 'span',
    class: 'myEmojiClass',
    style: ''
  }
```
Of course, by default no classes and styles will be applied, but there will be this option available.

**Comment by HAFRMO** [comment]
There is unfortunately not currently any easy method of doing this. Because of this I'm going to label this as a feature request, to go on our product backlog.
