### ISSUE TITLE
Source input on dialog for "Insert/Edit Image": Disable "dropdown" that is shown on paste

### ISSUE THREAD

**Issue by FilipQL** [tinymce/tinymce#6079]
On dialog for "_Inserting/Editing Image_" when you paste image URL, this "dropdown" is shown: 

![TinyMCE](https://user-images.githubusercontent.com/18264428/94968846-ee891700-0501-11eb-888b-6d10fc5d7991.png)

It's annoying because you have to click to remove it; It blocks whatever is below the "source" input (in my case "Cancel" and "Save" buttons as I only have "source" input on image dialog and nothing else, no "width" & "height" inputs, no "alt" input... ).

*DEMO:*

![ezgif-7-6ded02a29bd1](https://user-images.githubusercontent.com/18264428/94969920-d914ec80-0503-11eb-8554-ac7b230da977.gif)

http://fiddle.tinymce.com/ruhaab

*(Possible) Solution:*

Completely disable this (by default) or provide an option to disable. For example, `disable_dropdown_on_paste` or something like that.

**Comment by HAFRMO** [comment]
I believe that this setting ( [typeahead_urls](https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#typeahead_urls) ) is exactly what you are looking for, as it will disable the predictive url field.
