### ISSUE TITLE
Change translation string button tooltip

### ISSUE THREAD

**Issue by jozeflambrecht** [tinymce/tinymce#6081]
For example, I want to change _Blockquote_ to _Citation_ in French.

Being able to overwrite translation strings in `tinymce.init` would be helpful (without creating a localization file).

I created an account on https://www.transifex.com/tiny/tinymce/, joined the team, but cannot make a suggestion to improve the translation.

**Comment by lnewson** [comment]
Hi @jozeflambrecht, this can already be done with the editor. Here is an example: http://fiddle.tinymce.com/yuhaab

The key part of the above, is that you can't add the override until the `PreInit` event has fired, as it will have loaded the language pack by this stage. Another option would be to just manually edit the `fr_FR.js` language pack file to include your new translation.

**Comment by jozeflambrecht** [comment]
thank you for this solution!
