### ISSUE TITLE
Remove (hide) “Embed” tab (section)

### ISSUE THREAD

**Issue by PeraMika** [tinymce/tinymce#6082]
I'm using TinyMCE 5 and Media plugin with the following configuration:

```javascript
tinymce.init({
    selector: "textarea",
    menubar: false,
    plugins: [
        "media",
    ],
    toolbar: "media",
    media_dimensions: false,
    media_alt_source: false,
    media_poster: false,
});
```
We need an option to remove (disable, hide) the "Embed" tab (section): 

![TinyMCE-5-Remove-Embed-On-Media-Dialog](https://user-images.githubusercontent.com/41101578/95128289-85034580-0759-11eb-815a-8d24717e2da5.png)

In the documentation there's no such option:  https://www.tiny.cloud/docs/plugins/media/
So, maybe something like: `(bool) media_embed_tab: false/true`.

I'm using TinyMCE 5.4.2
http://fiddle.tinymce.com/zuhaab

**Comment by lnewson** [comment]
I can confirm there is currently no way to disable this tab in the media plugin, so I'll label this as a feature request.

**Comment by PeraMika** [comment]
@lnewson Is there any (recommended) workaround (until this new feature/option becomes available)?

**Comment by lnewson** [comment]
Unfortunately there is no workaround at the moment. If you really needed it, you'd have to fork the plugin and remove the embed tab, however that likely won't be an easy task.
