### ISSUE TITLE
Mixed content info when embedding images

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#6084]
TinyMCE have a image button in the toolbar that allows the user embed a image.

When a website is served over https but the embedded image is served over http then the page is served as a [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) page. This is undesirable and web browsers usually warn about this, and may even block the loading of resources.

Consider displaying a informative text in the TinyMCE embed modal when TinyMCE is serviced over https and the user attempts to insert a hyperlink to image does not use https.

# Example
![image](https://user-images.githubusercontent.com/10222521/95189283-f2e95480-07cd-11eb-829d-60110f8f852c.png)

**Comment by HAFRMO** [comment]
Hello.
At the moment we can't do this, but I've marked this as a feature request to go into our backlog.
