### ISSUE TITLE
CharMap

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#6087]
Hi Team , I have a question related to charmap customizations. Can we create a config in the charmap plugin where we can customize our own categories along with the symbols. The only thing I could find was char map append and overwrite. Please help on this if this is available.

**Comment by lostkeys** [comment]
Hi @SIMRAN88! You can create your own custom dialog containing your own categories. It's a bit of work to define all characters but that you'd have to do anyway. [See here to set up a dialog](https://www.tiny.cloud/docs/ui-components/dialog/), and then [look here for menus and components](https://www.tiny.cloud/docs/ui-components/dialogcomponents/) inside the dialog, specifically the tab panel and the collection component.

**Comment by SIMRAN88** [comment]
Hey, Thanks @lostkeys  for always coming out and helping with the issues. Will surely try the solution.

**Comment by SIMRAN88** [comment]
Thanks @lostkeys . I was able to create something like this. 
![image](https://user-images.githubusercontent.com/12448024/95456684-540b5680-098d-11eb-8c82-003d503c2bef.png)

**Comment by lostkeys** [comment]
Awesome! What are you going to use it for?

**Comment by SIMRAN88** [comment]
Have some requirement to have musical characters(maybe more) for students in our writing assignment tool.
