### ISSUE TITLE
TinyMCE creates a white layer and crashes the view in mobile layout

### ISSUE THREAD

**Issue by Tiththa** [tinymce/tinymce#6089]
When in mobile layout (Android 8.0 , Chrome 85.0.4183.127) the tinyMCE loads as it is intended, when clicked the editor allows to enter the content (Normal behavior) and suddenly when the keyboard pops up the screen is over-layered by white layer (Blank). The whole page becomes unresponsive and doesn't go back either. The error has progressed to other versions of chrome and android as well.  Desktop versions do not produce the error. 

Using tinyMCE version : 5.0.11

**Comment by lostkeys** [comment]
Hi @Tiththa! Can you please update to the latest version of TinyMCE to see if the issue goes away? TinyMCE 5.0.x is a while ago.

**Comment by Tiththa** [comment]
Thanks, i upgraded to v5.5.x and the issue is gone. Works like a charm @lostkeys

**Comment by Tiththa** [comment]
The issue re-appeared in mobile once again. @lostkeys 

Using Tinymce 5.8.1
Mobile browser Chrome 91.0 on Android 8.0, tested on Android 7 as well

![Screenshot_20210611-221845_Chrome](https://user-images.githubusercontent.com/24600191/121722999-a0ea9280-cb03-11eb-9f2b-67ca7f6fb53b.jpg)

When keyboard closed the issue doesn't exist
![Screenshot_20210611-221901_Chrome](https://user-images.githubusercontent.com/24600191/121723009-a34cec80-cb03-11eb-9a5b-a67201c011d1.jpg)
