### ISSUE TITLE
After the image is inserted, the default setting is pixel. I want to configure the default percentage or pixel value

### ISSUE THREAD

**Issue by yuntian001** [tinymce/tinymce#6092]
After the image is inserted, the default setting is pixel. I want to configure the default percentage or pixel value

**Comment by lincolndennis** [comment]
To clarify, are you saying that you want to be able to configure what unit is used for editing image dimensions in the Insert/Edit image dialog?  Or in the actual markup for the inserted image?

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
