### ISSUE TITLE
Dynamic Image Transformation Via QS Parameters

### ISSUE THREAD

**Issue by jasonhill** [tinymce/tinymce#6094]
We are using Tiny Drive for storing and serving our image files and it is really awesome. We sometimes want to apply transformations to the source images for different parts of the site and have previously used services like imgix to allow for dynamic transformation of source images via querystring parameters, e.g. ?w=100&h=100 to create an image that is resized to 100 x 100 or ?bri=50 to adjust brightness by 50%.

I haven't found any mention of the being supported...is it possible? It would be great if Tiny Drive could support that out of the box rather than having to use an external service.

**Comment by lnewson** [comment]
Hi @jasonhill, as Tiny Drive is a Cloud/Premium offering I'm afraid we can't provide support via GitHub sorry. Could you please log a support ticket and our support team should be able to help from there? https://support.tiny.cloud/hc/en-us/requests/new

**Comment by jasonhill** [comment]
Sure - will do.
