### ISSUE TITLE
List of content is broken

### ISSUE THREAD

**Issue by sgurin** [tinymce/tinymce#6097]
Hi.

In case of formatselect option enabled - list is broken https://prnt.sc/uxvk11

You may take a look on the example
https://codepen.io/JustCoded/pen/rNLVXVx?editable=true%3Dhttps%3A%2F%2Fwww.tiny.cloud%2F

**Comment by lostkeys** [comment]
Yes, this is a known limitation to our lists. As a work-around, TinyMCE has an option to specify what styles are to be reflected in the menu called [preview_styles](https://www.tiny.cloud/docs/configure/editor-appearance/#preview_styles). Here is a [working demo](http://fiddle.tinymce.com/zvhaab)

**Comment by sgurin** [comment]
Thanks, a lot
