### ISSUE TITLE
code_dialog_width: 300  doesn't work

### ISSUE THREAD

**Issue by njali2001** [tinymce/tinymce#6098]
**Documentation/Product Version**
_TinyMCE 4 Documentation_ OR _TinyMCE 5 Documentation_

**Links to Page(s) affected**

**Description of Issue**
I failed to adjust the width of code plugin by using the sample code: code_dialog_width: 300, nothing changed. 

**Suggested Fix**

**Comment by njali2001** [comment]
@tylerkelly13  Thank you!

**Comment by lostkeys** [comment]
Hi @njali2001! You have to fix this by adjusting z-index to have our dialog overlay your sidebar. That said, TinyMCE should have better options to style dialog and dialog positioning using the Style API [outlined here](https://www.tiny.cloud/docs/advanced/creating-a-skin/) such as setting the dialog container offset  so I'll label this as a feature request for internal tracking.

**Comment by njali2001** [comment]
@lostkeys  Thanks for your explanation. I'm afraid I haven't got your point. What should I do now? Using style to fix it by myself or waiting for your new version?

**Comment by lostkeys** [comment]
For now, you should fix your issue by setting a lower z-index on your sidebar than the TinyMCE dialog container to have the dialog appear above.
