### ISSUE TITLE
Uncaught TypeError: Cannot read property 'normalize' of null

### ISSUE THREAD

**Issue by basti96** [tinymce/tinymce#6102]
**What is the current behavior? Describe the bug**
If i press enter after a html select element, TinyMCE fire an error in the console:
`Uncaught TypeError: Cannot read property 'normalize' of null`

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
[Here](https://jsfiddle.net/1zjka8px/8/) is a demo of the problem.
If you press enter after the select element, the error fires in the console.

**What is the expected behavior?**
A newline.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I use TinyMCE 5 and Google Chrome Version 86.0.4240.75 on Windows 10. I don't know if this works in previous versions.

**Comment by lostkeys** [comment]
It's recommended to declare more complex html that isn't "content" like forms as [non-editable](https://www.tiny.cloud/docs/plugins/noneditable/). [Here is a demo](http://fiddle.tinymce.com/1vhaab). Please feel free to reopen this issue if you have further questions on this topic.

**Comment by basti96** [comment]
But the problem in your demo is that i can't change the selected element in the dropdown.
On click the dropdown not opened.

**Comment by lostkeys** [comment]
Generally form elements isn't supported in TinyMCE other than what I described above, which generally makes them basically placeholders. But if you could tell me more about your specific use-case and what you're trying to achieve I might be able to tell you if there is a work-around or not.
