### ISSUE TITLE
Ctrl+S error message on editor

### ISSUE THREAD

**Issue by tnorbs** [tinymce/tinymce#6107]
When I press ctrl + S, an error message appears saying "form element not found". 

I haven't found anything on the documention explaining what this command does, and what this error means.

Any thoughts?

**Comment by lnewson** [comment]
Hi @tnorbs,

That means you either don't have the editor in a HTML form, or if you aren't using a form, then you haven't configured the Save plugin to use a custom callback (see the [save_onsavecallback](https://www.tiny.cloud/docs/plugins/save/#save_onsavecallback) setting). Without either of those setup, TinyMCE doesn't know how to save the content.
