### ISSUE TITLE
IE no cursor available before or after table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#611]
The primary problem I am trying to resolve is when you have two tables one immediately after the other. It is not possible to position the cursor between the tables to insert text separating the tables.

This only occurs in IE, in Chrome it is possible to use the arrow keys to get a cursor between the tables, so you can insert text.

Steps to reproduce:
1. New document or clear editor
2. Hit enter to create an empty paragraph
3. Insert table1, any size
4. Click up to move outside table to empty paragraph
5. Insert table2, any size
6. Now try and move the cursor between the tables to insert some text, not possible in IE, but possible in Chrome

We are using v3.5.6, but have tried 3.5.8 and new 4 beta, and get same problems.

Expected result:
In step 6 you should be able to position a cursor between the tables so you can insert text.

Actual result:
It is not possible to position cursor between the tables

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5820](http://archive.tinymce.com/develop/bugtracker_view.php?id=5820) posted by [pauljevp](http://archive.tinymce.com/profile.php?name=pauljevp)_
> 
> _**Tags:** [msie msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this problem with the latest version of TinyMCE please create a new issue.
