### ISSUE TITLE
Width option for table classes

### ISSUE THREAD

**Issue by LorenzoKorn** [tinymce/tinymce#6119]
**Is your feature request related to a problem? Please describe.**
I am working with tables and I have some different classes that the tables can have. The problem is that different table classes need to have different widths. One needs to have 100% width and others like 60% or 50% or even none. Changing the default width doesn't help this either.

I tried changing it with onChange and onClick events, but couldn't get it working.

Found a solution with CSS, but the problem then is that the table setting modal still shows 100% and this is confusing for the user.

**Describe the solution you'd like**
I would like to see an option to the `table_class_list` object to include an optional `width` property.

e.g.
```javascript
table_class_list = [
    { title: 'class1', value: 'class1' }, // default width
    { title: 'class2', value: 'class2', width: '50%' }, // overrides default to 50% width
    { title: 'class3', value: 'class3', width: '0' } // overrides default to no width
];
```

**Describe alternatives you've considered**
Specific onChange event for the class_list dropdown.

**Comment by lostkeys** [comment]
@LorenzoKorn [Here is an example how to get different table widths](http://fiddle.tinymce.com/Yvhaab) through the class drop down while also clear the width input field from saying 100% all the time.

**Comment by LorenzoKorn** [comment]
@lostkeys aha, so no default width and then apply css to it. Didn't adjust the default... Thanks!
