### ISSUE TITLE
When switching to FullScreen mode, the screen appears to be getting truncated

### ISSUE THREAD

**Issue by SuppSoftAdminZ** [tinymce/tinymce#6122]
Select View --> Full Screen

The screen expands but parts of the screen are truncated

The expected behavior was to see it render like the demo
https://www.tiny.cloud/docs/demo/full-featured/

Using version @tinymce/tinymce-react@3.7.0

Screen shot attached
Before:
![image](https://user-images.githubusercontent.com/34314680/96497815-3950a180-1219-11eb-8c89-bf31412b1925.png)

After:
![image](https://user-images.githubusercontent.com/34314680/96497865-4d949e80-1219-11eb-8730-a8f66083fa80.png)

I'm assuming I need to adjust a z-index on a css class somewhere but not certain where.

**Comment by JamesToohey** [comment]
Hi @SuppSoftAdminZ, I'm not quite sure exactly what the problem you're facing is given those screenshots, and I wasn't able to reproduce any odd cut-off behaviour in our demo. 

Could try to replicate the issue with a [fiddle](http://fiddle.tinymce.com/) for me to take a look?

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
