### ISSUE TITLE
A problem when I add a svg from source code.

### ISSUE THREAD

**Issue by lingluang** [tinymce/tinymce#6125]
It shows well in editor when I add svg code from source, but when I close the source code and reopen it, the code disappeared.

![tinymce_1](https://user-images.githubusercontent.com/21175047/96574387-f4ed0080-1301-11eb-9541-4e5e55a5e294.png)

I found maybe something wrong in 'editor.getContent()'.
![tinymce](https://user-images.githubusercontent.com/21175047/96574923-ad1aa900-1302-11eb-9d52-2ee3c4437833.png)

After doing some tests, I found I can get the code by adding a space ‘&nbsp’ after the svg tag

![tinymce_2](https://user-images.githubusercontent.com/21175047/96575204-0aaef580-1303-11eb-9a65-cc2f5bef3d00.png)

My svg code is `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M24 10h-10v-10h-4v10h-10v4h10v10h4v-10h10z"/></svg>`

**Comment by lingluang** [comment]
@tylerkelly13 Can you give me some help? thx.

**Comment by lingluang** [comment]
![image](https://user-images.githubusercontent.com/21175047/96703618-a7d26280-13c5-11eb-8a0c-2e40e0b6848d.png)

It's ok but I don't why if it need to add 'p[*]' to 'extended_valid_elements'

**Comment by lnewson** [comment]
@lingluang could you please create a [fiddle](https://fiddle.tiny.cloud/) to reproduce the issue? I suspect you may need the [valid_children](https://www.tiny.cloud/docs/configure/content-filtering/#valid_children) setting, but it's hard to say while only seeing images.

**Comment by lingluang** [comment]
@lnewson Hi, thanks for your reply.
The fiddle is as follow:   https://fiddle.tiny.cloud/xwhaab

you can add `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M24 10h-10v-10h-4v10h-10v4h10v10h4v-10h10z"/></svg>` to sourcecode, save it and reopen it, you will find the soucecode is empty like my first pic.

**Comment by lingluang** [comment]
@lnewson And... I can get the sourcecode from https://fiddle.tiny.cloud/ywhaab
which I only add a 'p[*]' to the 'extended_valid_elements'

**Comment by lnewson** [comment]
@lingluang, the problem is that TinyMCE will remove empty elements by default. So we need to tell TinyMCE to keep the SVG element, which can be done by doing something like this: https://fiddle.tiny.cloud/xwhaab/1

I should add that TinyMCE doesn't support using SVG's in the editor, as they are a large security issue, so enabling them could expose yourself to XSS vulnerabilities.
