### ISSUE TITLE
How to keep Adsense code work on Tinymce editor

### ISSUE THREAD

**Issue by sadazs** [tinymce/tinymce#6126]
Help!
When add Adsense code to Tinymce editor it replace code wrong formart, I see a function on tiny_mce.js
How to remove or edit that function to not place adsense code
<script src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<p><ins class="adsbygoogle" style="display:block"></ins></p>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</p>

**Comment by lnewson** [comment]
@sadazs could you please let us know what version of TinyMCE you're using? Based on the filename, I suspect it's TinyMCE 3 which is no longer supported. If you can reproduce it with TinyMCE 5, could you please include some clarification about what you mean when you say the following?
> Tinymce editor it replace code wrong formart

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
