### ISSUE TITLE
I can't find what I'm looking for: index.md

### ISSUE THREAD

**Issue by jimlink2** [tinymce/tinymce#6128]
In the Insert/Edit Media dialog:

Is there some way to customize and/or remove the "General" option?

In a related topic, is there some way to ADD a text link to this dialog, to open a custom "Instructions" page?

**Comment by lnewson** [comment]
Hi @jimlink2,

The dialog is not customizable in the manners you describe. The links on the left of the dialog are tabs to different media embedding options. 

As such if you want to customise the look and feel of the media dialog to that extent, you'd need to fork the plugin and make any required changes.
