### ISSUE TITLE
Replace <img> in <figure> disrupts the layout

### ISSUE THREAD

**Issue by davidearl** [tinymce/tinymce#6134]
**What is the current behavior? Describe the bug**

http://fiddle.tinymce.com/4whaab/2

I have initial content which is a series of blocks (`h3`, `figure`, `h4`, `p`, `div`) inside a pair of `div`'s styled as `display: inline-block`. The figure element contains a placeholder `img` and a `figcaption`.

If I replace the `img `using right click + image in tinymce, the layout hierarchy is completely altered: the figure element is moved outside its enclosing div (apparently by terminating that div before the figure, and adding a new opening div afterwards).

If I use `div` instead of `figure` and `figcaption`, this does not happen.

Both `div` and `figure` are block level elements, so there shouldn't be any difference in behaviour.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

http://fiddle.tinymce.com/4whaab/2

Look at the layout using the code button

Replace the first image with the editor (just change the last number in the url from 200 to 201 for example)

Look at the layout again with the code button and you'll see extra closing and opening `div`s have been inserted. This does not happen if div is used in place of `figure` and `figcaption`.

**What is the expected behavior?**

Just the image should change, not the layout.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested in Chrome 86 with tinymce-cloud-stable in the fiddle (but motivated by it failing in a 5.2.1 self-hosted version)

**Comment by lostkeys** [comment]
Hi @davidearl! Unfortunately the complex HTML that layouts are is one area that TinyMCE doesn't handle very well. The way to tackle this is to have the layout be outside of TinyMCE and then use [Inline mode](https://www.tiny.cloud/docs/general-configuration-guide/use-tinymce-inline/) to edit each block. (Any adding, removing and reordering of blocks is thus outside the scope of TinyMCE.). [Here is a demo showcasing that approach](https://tinymce.github.io/tinymce-demos/email/marketing-email-inline-mode.html). Recently we have [added APIs to get inline mode to mimic the regular editor](https://www.tiny.cloud/docs/release-notes/release-notes55/#newpersistenttoolbaroptionforinlinemode) if that's desired.

**Comment by davidearl** [comment]
Thank you. That may well be a good approach here.

However, I also think you're missing the point: that figure and figcaption behave differently from div used in the same context, even though both are block-level elements. Is it simply that tinymce doesn't admit that those relatively new elements exist?

**Comment by lostkeys** [comment]
Yeah we agree, changing the `img` within a `figure` should not trigger any DOM changes outside of the `figure` element. 

Here is a diff showing better what's going on. The right side is after changing the image.
![image](https://user-images.githubusercontent.com/3122929/97548459-719d7000-19cf-11eb-98b5-825bee0ecc9e.png)
