### ISSUE TITLE
Using the same domain through mobile device shows the Domain not registered message

### ISSUE THREAD

**Issue by savinash47** [tinymce/tinymce#6136]
**What is the current behavior? Describe the bug**
I am using api key and using editor in my website. On browser I don't see the Domain name not registered message but when i try to open my website in mobile browser (Safari) i see the domain not registered message.
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**
It should not show error message in mobile browser (safari)
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Using TinyMCE react.

**Comment by lnewson** [comment]
Hi @savinash47, we can't assist with Tiny Cloud issues from GitHub sorry. If you have an active Tiny Cloud account, could you please contact our support team via https://support.tiny.cloud/hc/en-us/requests/new who should be able to help further.

As a tip, it might be worth checking the domains on mobile are the same as what's being used on desktop.
