### ISSUE TITLE
getting TypeError: u.hasPlugin is not a function in theme.min.js

### ISSUE THREAD

**Issue by scorpanog** [tinymce/tinymce#6138]
**What is the current behavior? Describe the bug**
I can not even load the editor anymore as I am getting this error in console. it is occurring in theme.min.js:2:368191, which is downloaded from the server.
the issues started to occur pretty recently within last week and of course it is affecting my dev and production site.  Before this issue happened editor was working fine and I even created 2 articles using it. Everything was working properly, went to write another article today and could not load the page.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
I event tried the default init() function from from my dashboard and I am still getting the same error. I
**What is the expected behavior?**
It should load and work properly.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Macos 10.15, firefox 81, chrome. tynimce v5.

**Comment by lnewson** [comment]
Hi @scorpanog, It sounds like you're having caching issues, as that would only occur if using an older version of the editor core and a newer theme. Can you try clearing your cache or trying to load the editor in a private/incognito window?

If that works, then make sure to set up a cache-busting strategy for loading your JavaScript resources (either via server-side HTTP headers or client-side via query parameters for example). If that doesn't work, then we'll need a way to reproduce the issues to help further.

**Comment by scorpanog** [comment]
Hi @lnewson,
thanks. Found the reason. It looks like the older core code was left on the server prior to setting it up with cdn resourse and now that code got too old. There was no comment that it was tinymce code, so I did not realized at first, but when you said core is older than the theme, I tried it.

it's all loading now thanks.
Appreciate the quick help.

**Comment by lnewson** [comment]
Awesome, glad to hear you managed to resolve your issue :+1:
