### ISSUE TITLE
How to replace an icon which was initialized via plugin after it was initialized? I can't find it in api/tinymce/tinymce.plugin.html

### ISSUE THREAD

**Issue by ss2020a** [tinymce/tinymce#6141]
I would like to change a button's icon after it was initialized (the initialization happens from the product it is embedded with).

What is the best way to achieve it?

Actually product uses an image(gif not svg) and it was initialized within pluginmanager.add function within init method

I would like to use svg icon by overriding it after initialization (ie remove image: and add icon:).

Please let me know.

Thank you

**Comment by sethurk** [comment]
Thank you tylerkelly13. Appreciate you help..

**Comment by lostkeys** [comment]
Hi @ss2020a! Unfortunately this is not something we support. Can you describe in more detail the usecase you are trying to solve by changing the icon?

**Comment by ss2020a** [comment]
Hi @lostkeys ,  good day and sorry for the delay.  Basically, tinymce5.0.3 is bundled with a cms product which has a custom tinymce plugin.  We would like to change the custom plugin's icon without updating the custom plugin's plugin.js or its svg/img files by placing another .js file which should override the custom plugin's icons.  Is it possible? If so, how? Thanks in advance.

**Comment by ss2020a** [comment]
@lostkeys , thanks for the reply.  The issue is, they have used gif/image in their custom plugin. I would like to override with my custom svg file. Is that possible without touching their custom plugin.js?

**Comment by lostkeys** [comment]
If the third party plugin creator defined their icon using the [ui.Registry.addIcon()](https://www.tiny.cloud/docs/api/tinymce.editor.ui/tinymce.editor.ui.registry/#addicon) you can override that icon in your own config by using the same method and using the same icon identifier. Here is an example: https://fiddle.tiny.cloud/Dyhaab/2
