### ISSUE TITLE
Autocompleter: allow to pass an object as the value

### ISSUE THREAD

**Issue by MissChocoe** [tinymce/tinymce#6152]
**Is your feature request related to a problem? Please describe.**
We are using the auto-complete to create link with other element (not url link but rather a reference). We want to display the element name and keep the element id in an span surrounding the name. So we need two informations when user pick an element: the id and the name.

**Describe the solution you'd like**
Simply allow to pass object as the value so we could pass someting like {name: "My element", id: "123"}

**Describe alternatives you've considered**
We can pass a stringify version of the json or the two values separated by a predefined  caracter.

**Comment by zhoufenfens** [comment]
good advice

**Comment by ashfordneil** [comment]
I've created a ticket to add documentation for this, but we have an optional `meta` field on the autocompleter item interface, and if you provide it it will be passed into your `onAction` function as a fourth argument. Here is an example of how to use it: https://fiddle.tiny.cloud/Mwhaab/4

**Comment by MissChocoe** [comment]
> I've created a ticket to add documentation for this, but we have an optional `meta` field on the autocompleter item interface, and if you provide it it will be passed into your `onAction` function as a fourth argument. Here is an example of how to use it: https://fiddle.tiny.cloud/Mwhaab/4

Thanks for revealing this "secret" feature. :)

**Comment by MissChocoe** [comment]
@ashfordneil Got delayed a bit on using this meta feature. I'm not back on it but when I do pass my object in the meta, I get stackoverflow. My object is a class instance. 

Does TinyMCE tries to run any code with this object that could cause such weird behavior? If I pass a simple dummy object as in the exemple, it works. But mine makes TinyMCE get into a stackoverlflow between after the fetchResults and before the onAction callback.

Since this object is loaded async, I would prefer not to have to make the call again to get it back.

**Comment by sonikasharma1403** [comment]
@lostkeys - this is no longer working as expected
