### ISSUE TITLE
inline editor is not working if editable element is in shadowRoot

### ISSUE THREAD

**Issue by VitaliyOnRule** [tinymce/tinymce#6158]
if element is inside shadowRoot - inline editor for it is working with a lot of bugs

version 5.5 or 5.4.2

https://jsfiddle.net/vitaldo/jsdm7ao9/16/
https://jsfiddle.net/vitaldo/jsdm7ao9/17/

is it possible that it will be fixed in future or it is the same as #6062 ?

**Comment by lnewson** [comment]
Hi @VitaliyOnRule, I'm afraid we don't currently have any plans to support inline mode when rendered in a shadow root. The primary reason is that the browser selection APIs for shadow roots are still experimental, or in flux and aren't in a state that would allow TinyMCE to operate. Some examples of the current issues are:

- Safari doesn't provide a way to get the selection for the shadow root (likely means we can't support Safari).
- Firefox doesn't implement the DocumentOrShadowRoot.getSelection() API, but it will return the shadow root selection for Window.getSelection().

We are keeping an eye on discussions regarding replacing this API with Selection.getComposedRange(), however no browsers implement this API at this time. If it is implemented, we will then investigate inline mode support for ShadowDOM again.

**Comment by VitaliyOnRule** [comment]
@lnewson Thanks a lot for detailed response

**Comment by jogibear9988** [comment]
Bugs:
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1430308
Safari: https://bugs.webkit.org/show_bug.cgi?id=163921
