### ISSUE TITLE
inline editor removes "a" tag if there is one character left

### ISSUE THREAD

**Issue by VitaliyOnRule** [tinymce/tinymce#6169]
After pressing "Backspace" inline editor removes "a" tag if there is one character left

It causes a bad UX (impossible to change text of the link at all)

example: https://jsfiddle.net/vitaldo/cmxjhks4/8/

Expected result: after pressing "Backspace" the last character is removed and "a" tag still exists and selection is still on that tag.

Chrome, tinymce 5.4.2

**Comment by VitaliyOnRule** [comment]
it is a duplicate of #6168

**Comment by ashfordneil** [comment]
This is intended behaviour. We checked with other online WYSIWYG editors and they don't preserve the link either as you don't want hidden links lingering in the HTML. If you want to completely replace the text in the link you can double click inside the link and then type over the range selection.
