### ISSUE TITLE
The quote icon is removed along with the text if the quote is the first in a line in the editor

### ISSUE THREAD

**Issue by fredure** [tinymce/tinymce#6186]
**What is the current behavior? Describe the bug**
The quote icon is removed along with the text if the quote is the first in a line in the editor.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Insert quote into editor;
2. Select the entire text of the quote with the mouse;
3. Press "backspace".

Codepen: https://codepen.io/fredure/pen/vYKaaax

Actual result:
![Nov-05-2020 18-56-49](https://user-images.githubusercontent.com/8024592/98264367-dee56e00-1f98-11eb-82d8-5a49d35d426d.gif)

Expected Result:
![Nov-05-2020 18-57-26](https://user-images.githubusercontent.com/8024592/98264387-e442b880-1f98-11eb-9554-e0e671b10b27.gif)

**What is the expected behavior?**
The text has been deleted, the quote icon remains.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: 5.2.0 (2020-03-14).
Browsers: all.
OS: all.

**Comment by ashfordneil** [comment]
This is intended behaviour, as it's how all our block level elements behave when you select them and hit backspace. As an alternative, if you delete the text by pressing backspace when the cursor is at the end of the text, you will be able to remove the text without deleting the block level element (press backspace one extra time at the end to remove the block itself, if desired).

If you'd like, we can make a feature request to support this behaviour (under a setting) and pass that along to the product team for evaluation.
