### ISSUE TITLE
Applying style to parent element

### ISSUE THREAD

**Issue by peter3** [tinymce/tinymce#6191]
**What is the current behavior? Describe the bug**
I have a requirement to add a class to a p-tag if it has an a-tag child, like this:
```
<p class="read-more-link">
  <a href="#">Link</a>
</p>
```
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Demo here https://fiddle.tiny.cloud/0xhaab/3 with various options I have tested

**What is the expected behavior?**
One of formats #3 to #5 in the demo should provide the required result, but none do

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?** 
Version 4.9.11 (local) and tinymce5-cloud-stable in fiddle
Haven't tried in other version
OS/browser not significant

**Comment by ashfordneil** [comment]
The formatter isn't designed for this type of use-case. Instead, I'd recommend you add a node filter to the DOM parser, as per [these docs](https://www.tiny.cloud/docs/api/tinymce.html/tinymce.html.domparser/#addnodefilter).

If the node filter doesn't work, can you give us more information about your use case so that we can better advise you.

**Comment by peter3** [comment]
Sorry, I have no idea how to use a node filter and the documentation is a bit... lacking on what can be done with it

**Comment by JamesToohey** [comment]
Hi @peter3,

Apologies for the delayed response. The team has taken a look and produced a fiddle that will likely satisfy your use case: 

https://fiddle.tiny.cloud/0xhaab/6

I agree the documentation for node filter could be improved, so I will log an internal ticket to improve that.
