### ISSUE TITLE
ImageTools Workaround For PHP Upload Script Forcing Unique Names?

### ISSUE THREAD

**Issue by WebSpectrum** [tinymce/tinymce#6192]
**Is your feature request related to a problem? Please describe.**
My PHP script handling uploads for TinyMCE has a function to rewrite filenames if the filename already exists. However it's a problem with ImageTools as every edit of an image produces a new image which is not necessary.

**Describe the solution you'd like**
I don't have a solution
**Describe alternatives you've considered**
Possibly using a different PHP upload script for imagetools but not sure how easy it is to implement?

**Comment by ashfordneil** [comment]
Would this setting help? https://www.tiny.cloud/docs/configure/file-image-upload/#images_reuse_filename

If this doesn't help solve your problem, please provide more information about exactly what is going wrong. Note that we can't really provide PHP / backend support, but if you believe there are issues with the requests that we are sending to your backend we can look into that.

**Comment by WebSpectrum** [comment]
Already have this setting:

`images_reuse_filename: true,`

The issue is my upload.php script has a function to check for an existing filename and it will rewrite the filename to prevent overwriting, the issue with imagetools is now every time and edit is made with imagetools it will generate a new file with unique filename. Could probably do with sending imagetools to a different php uploader

**Comment by JamesToohey** [comment]
Hi @WebSpectrum,

It sounds like you're on the right track so I'll close this issue. If not and you feel this is a bug, could you please provide a replication case of your issue?

**Comment by WebSpectrum** [comment]
I think it's probably a feature request, to be able define a different php upload script for imagetools would might be a way round it, I don;t think such a setting exists currently?
