### ISSUE TITLE
after publication, emoticons are not displayed.

### ISSUE THREAD

**Issue by starskg** [tinymce/tinymce#6199]
in the editor emoticons works. and the plugin responds fine too. after completion the emoticons disappeared
sys: laravel
```
{{-- TinyMCE --}}
@if (config('settings.single.wysiwyg_editor') == 'tinymce')
    <script src="{{ asset('assets/plugins/tinymce/tinymce.min.js') }}"></script>
    <?php
    $editorI18n = \Lang::get('tinymce', [], config('app.locale'));
    $editorI18nJson = '';
    if (!empty($editorI18n)) {
        $editorI18nJson = collect($editorI18n)->toJson();
        // Convert UTF-8 HTML to ANSI
        $editorI18nJson = convertUTF8HtmlToAnsi($editorI18nJson);
    }
    ?>
    <script type="text/javascript">
        tinymce.init({
            selector: '#description',
            language: '{{ (!empty($editorI18nJson)) ? config('app.locale') : 'en' }}',
            directionality: '{{ (config('lang.direction') == 'rtl') ? 'rtl' : 'ltr' }}',
            height: 350,
            menubar: false,
            statusbar: false,
            plugins: 'lists  table emoticons',
            toolbar: 'emoticons | undo redo | bold italic underline | forecolor backcolor | link unlink | alignleft aligncenter alignright | outdent indent | fontsizeselect ',
        });
        @if (!empty($editorI18nJson))
            tinymce.addI18n('{{ config('app.locale') }}', <?php echo $editorI18nJson; ?>);
        @endif
    </script>
@endif

```

![Screenshot_1](https://user-images.githubusercontent.com/62965715/98575929-02375280-22e4-11eb-9243-5785d2687600.png)
![Screenshot_2](https://user-images.githubusercontent.com/62965715/98575944-06637000-22e4-11eb-9355-7d5b6d09a77d.png)

**Comment by lincolndennis** [comment]
Can you post the HTML content in the editor vs the HTML content of the rendered page?

**Comment by starskg** [comment]
I do not understand you at all. how to do it

**Comment by starskg** [comment]
did you mean it
![Screenshot_3](https://user-images.githubusercontent.com/62965715/99145387-a0d30300-2698-11eb-8f0a-3712ea90048c.png)

**Comment by JamesToohey** [comment]
Hi @starskg,

Thanks for getting back to us with a screenshot. It looks like something in your system is removing the emoticons, so unfortunately I don’t think there’s much we can do to help.

A quick thought, you may want to check your server and database character set/encoding as this could cause issues with unicode characters.
