### ISSUE TITLE
Source code Editor 

### ISSUE THREAD

**Issue by njali2001** [tinymce/tinymce#6200]
**What is the current behavior? Describe the bug**
I would like to copy paste a piece of source code to TinyMCE via source code editor. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Switch the TinyMCE to source code mode, an editor prompt up. 
2. I copy and paste the source code into it. and Save.
3. Everything looks perfect. 
4. Click the source code button again, and the editor prompt up. but the source code is different with the previous that I submitted. 
5. After saving, the content is messed up. 

Here is the source code I used. you can try it. 

[HTML.txt](https://github.com/tinymce/tinymce/files/5512866/HTML.txt)

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lincolndennis** [comment]
Can you provide some more information regarding this behavior?

For instance, when you say:
>but the source code is different with the previous that I submitted.

How is the code different, what changes have been made?

Similarly,
>After saving, the content is messed up.

The content is messed up in what way? Can you provide screenshots? Do you  mean the content is "messed up" in the editor, or when it is later rendered elsewhere?

**Comment by njali2001** [comment]
Thank you for your reply, Here are the details as attached. 
The source code before (HTML_before.txt) and after (HTML_after.txt), and the screen shoot before (before.png) and after (after.png) 
[HTML_before.txt](https://github.com/tinymce/tinymce/files/5537500/HTML_before.txt)
<img width="565" alt="after" src="https://user-images.githubusercontent.com/8847441/99085554-55383080-2596-11eb-8f9c-f28a850d84fd.png">
<img width="601" alt="before" src="https://user-images.githubusercontent.com/8847441/99085557-55d0c700-2596-11eb-963f-ee8a0d7ae7a9.png">
[HTML_after.txt](https://github.com/tinymce/tinymce/files/5537501/HTML_after.txt)

Please let me know if you anything further.

**Comment by JamesToohey** [comment]
Hi @njali2001, thanks for providing additional information.

Ultimately, TinyMCE is a WYSIWYG editor. The editor will sanitize content that is inserted via the code plugin to ensure it is secure and works correctly in TinyMCE. That means we can not guarantee that inserted HTML will remain exactly as it was. 

We do have the `fullpage` plugin that may help with your use case though. TinyMCE also has a setting to allow condition comments. We recommend trying both. 

Another solution for your use case may be to use inline editors for the parts of the page that you wish to edit using TinyMCE.

Consider:
- [ ] adding `fullpage` plugin (https://www.tiny.cloud/docs/plugins/opensource/fullpage/)
- [ ] enabling `allow_conditional_comments` (https://www.tiny.cloud/docs/configure/content-filtering/#allow_conditional_comments)
- [ ] using inline editors for the parts of the content you wish to edit (https://www.tiny.cloud/docs/demo/inline/)
