### ISSUE TITLE
Clicking on a button in a TinyMCE inline text editor inside a NG-ZORRO modal calls blur() causing the toolbar to disappear so the buttons never work

### ISSUE THREAD

**Issue by ajhernandez95** [tinymce/tinymce#6201]
**What is the current behavior? Describe the bug**
After upgrading to V9 of Angular and NG-ZORRO, when using the inline mode of TinyMCE inside a modal the toolbar just disappears every time a user would click on a button like bold or italics. This works properly out of a modal but inside its broken.

If I set the toolbar_persist property to true the toolbar works as expected but then I can not remove the toolbar on blur as the blur event still fires on button click so I never know when a true blur event is fired off.
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Set up a inline text editor inside a NG-ZORRO V9 modal and attempt to use the toolbar.
**What is the expected behavior?**
Toolbar buttons apply proper actions to selected items or insert where cursor is.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE 5.5.1 / Chrome / Angular 9 / NG-ZORRO 9. 
This feature worked properly in Angular 7 and NG-ZORRO 7

**Comment by thibaultchazal** [comment]
Same problem in a vue dialog box

**Comment by ajhernandez95** [comment]
> Same problem in a vue dialog box

I worry that they are not going to do anything due to V10 being released and most likely taking priority.

**Comment by JamesToohey** [comment]
Hi @ajhernandez95, thanks for reporting this issue.

We are not familiar with NG-ZORRO, is it possible for you to create a reproduction case in an open source repository, or using a sandbox platform such as Codepen or JSFiddle?

**Comment by lnewson** [comment]
Worth noting, that many of these dialog frameworks will block focusing anything outside the dialog. This often causes issues with TinyMCE and you need to tell the framework how to let it access the TinyMCE components. https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog is an example of what's needed for bootstrap, however it varies between frameworks so you may be better asking for help from the NG-ZORRO developers.

**Comment by ajhernandez95** [comment]
> Hi @ajhernandez95, thanks for reporting this issue.
> 
> We are not familiar with NG-ZORRO, is it possible for you to create a reproduction case in an open source repository, or using a sandbox platform such as Codepen or JSFiddle?

Here is a [link](https://github.com/ajhernandez95/tinymce-issue-demo) to a repo holding a demo for you to test on. You can see in the demo that I set up two modals with two different problems. In one modal, it's the default text editor and when you try and highlight text to link the modal and quickbar both break and in the second modal you can see that inline does not work within a modal.

**Comment by JamesToohey** [comment]
Hi @ajhernandez95, thanks so much for the repo!

The team has taken a look and there's two separate things going on here:

1. NG-ZORRO is highjacking focus events which breaks all of TinyMCE's functionality. This is something that you'll need to raise with the NG-ZORRO maintainers.
2. In the second example, you can add the following styles to fix the toolbar being behind the modal:

```
.tox.tox-tinymce-inline, .tox.tox-tinymce-aux {
    z-index: 1001; // at least one more than NG-ZORRO
}
```

Thanks again for putting the time in to build a reproduction case, it's very much appreciated.

**Comment by ajhernandez95** [comment]
> Hi @ajhernandez95, thanks so much for the repo!
> 
> The team has taken a look and there's two separate things going on here:
> 
> 1. NG-ZORRO is highjacking focus events which prevents interacting with the TinyMCE UI. This means that as soon as you try to interact with the TinyMCE UI, NG-ZORRO moves the focus back to its dialog. This is something that you'll need to raise with the NG-ZORRO maintainers.
> 2. In the second example, you can add the following styles to fix the toolbar being behind the modal:
> 
> ```
> .tox.tox-tinymce-inline, .tox.tox-tinymce-aux {
>     z-index: 1001; // at least one more than NG-ZORRO
> }
> ```
> 
> Thanks again for putting the time in to build a reproduction case, it's very much appreciated.

Thank you guys for the assistance. I got with the NG-ZORRO team and they were able to provide me with a solution [here](https://github.com/NG-ZORRO/ng-zorro-antd/issues/6181) and I wanted to share it with you guys in case in the future someone has a similar issue. The issue was [FocusTrapFactory](https://material.angular.io/cdk/a11y/api#FocusTrapFactory) and they show a way to remove that in [this repo](https://github.com/ajhernandez95/tinymce-issue-demo).

**Comment by lostkeys** [comment]
@ajhernandez95 Thanks for sharing this info back to the community!
