### ISSUE TITLE
In 'Distraction-free' mode, 'height and 'min-height' have no effect

### ISSUE THREAD

**Issue by xiaohundun** [tinymce/tinymce#6207]
**What is the current behavior? Describe the bug**
In 'Distraction-free' mode, 'height and 'min-height' have no effect

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
[https://fiddle.tiny.cloud/Oxhaab/1](https://fiddle.tiny.cloud/Oxhaab/1)
[https://codepen.io/xiaohundun/pen/BazGqdv?editable=true%3Dhttps%3A%2F%2Fwww.tiny.cloud%2F](https://codepen.io/xiaohundun/pen/BazGqdv?editable=true%3Dhttps%3A%2F%2Fwww.tiny.cloud%2F
)
**What is the expected behavior?**
In 'Distraction-free' mode, 'height and 'min-height' have effect

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE：5.5.1
OS：MacOS
Browser：Chrome
Did this work in previous versions of TinyMCE？：no

**Comment by lnewson** [comment]
Hi @xiaohundun,

This is expected, as those settings only apply to classic (iframe) editors. Inline editors, which is what distraction-free is, will use whatever CSS/styles you use on the element that TinyMCE takes over and won't try to change the look of the page. So you should instead set the height on the inline element. Here's an example: https://fiddle.tiny.cloud/Oxhaab/3

**Comment by xiaohundun** [comment]
Thanks！！😘
