### ISSUE TITLE
Does quickbars have the option can realize the same effect as toolbar_mode

### ISSUE THREAD

**Issue by StarkShang** [tinymce/tinymce#6214]
I am using quickbars plugin for Distraction-free editing mode, and I want to hide the overflowing toolbar buttons in overflow icon. Is there a option for quickbars can make the same effect?

**Comment by lostkeys** [comment]
Hi @StarkShang! Unfortunately the quickbars context toolbar doesn't have the overflow functionality. I'll add it in our backlog as a feature request but I cannot give you any hints on when and if we fix this at this time.
