### ISSUE TITLE
Table binding problem. I can't spiraling tr tags with ruby codes

### ISSUE THREAD

**Issue by PolisImdat** [tinymce/tinymce#6221]
Hi, I want to show products in privacy contract on e-commerce website. I use ruby codes in editor something like that : 
```
<table>
<thead>
<tr>
<th>Product</th>
<th>Quantitiy</th>
<th>Total</th>
</tr>
</thead>
<tbody>
{% for item in Order.OrderItems -%} //For Loop
<tr>
<td>{{item.ProductName}}</td>
<td>{{item.Quantity}}</td>
<td>{{item.TotalPrice}}</td>
</tr>
{% endfor -%} //End For Loop
</tbody>
<tfoot>
<tr>
<td> </td>
<td><strong>Orrder Total:</strong></td>
<td><strong>{{Order.Total}}</strong></td>
</tr>
</tfoot>
</table>
```
But, codes are changing when I click ok button in source code popup. Ruby codes go up. 
```
 {% for item in Order.OrderItems -%}{% endfor -%}  // Ruby Codes Are Here!!!
<table>
<thead>
<tr>
<th>Product</th>
<th>Quantitiy</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr>
<td>{{item.ProductName}}</td>
<td>{{item.Quantity}}</td>
<td>{{item.TotalPrice}}</td>
</tr>
</tbody>
<tfoot>
<tr style="text-align: right;">
<td style="height: 18px;"> </td>
<td><strong>Orrder Total:</strong></td>
<td><strong>{{Order.Total}}</strong></td>
</tr>
</tfoot>
</table>
```

**Comment by lostkeys** [comment]
Hi @PolisImdat!. Unfortunately I cannot find an easy solution to your use case. There is a [config option called Protect](https://www.tiny.cloud/docs/configure/content-filtering/#protect) which prevents the ruby codes to be moved tothe top of the document. Unfortunately everything is wiped when inserting a row or column. Here is a demo: https://fiddle.tiny.cloud/myhaab/1

TinyMCE is first and foremost an HTML editor. Ruby or PHP isn't HTML and won't be understood by a browser. Simpe use-cases mostly works fine like these "placeholders":`{{Order.Total}}`, but it falls apart when you need to manage advanced things like loops in tables and lists. 

I'll do some more investigating next week but prepare yourself that your use case is outside of the scope of TinyMCE, or that the solution will require some serious effort on your side doing post and preprocessing of control codes.

**Comment by PolisImdat** [comment]
Hi @lostkeys . I changed my html code, table to div and its work fine. Thank you for help.
