### ISSUE TITLE
Table Plugin: When dragging the frame to select some cells, move the mouse to the border line and release the mouse, the cell will be selected in confusion

### ISSUE THREAD

**Issue by xinzikang** [tinymce/tinymce#6222]
**What is the current behavior? Describe the bug**
When dragging the frame to select some cells, move the mouse to the border line and release the mouse, the cell will be selected in confusion

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce: V5.4, chrome

**Comment by lostkeys** [comment]
Hi @xinzikang! I cannot fully understand your problem. Can you perhaps do a video recording of your screen?

**Comment by xinzikang** [comment]
[屏幕录制 2020-11-26 14.36.30.zip](https://github.com/tinymce/tinymce/files/5600917/2020-11-26.14.36.30.zip)

**Comment by lostkeys** [comment]
@xinzikang I see, I've encountered this issue myself but haven't been able to find a fix for it. 

![IMG_803BFE29ADD6-1](https://user-images.githubusercontent.com/3122929/100316707-5e27f980-2fbb-11eb-8a8c-cadcd9d86a50.jpeg)

**Comment by lostkeys** [comment]
(I logged it as a bug because CK4 and CK5 manages to not have these selections show up so it seems to be doable.)

**Comment by xinzikang** [comment]
Here is my way: 

> table/plugin.js
![image](https://user-images.githubusercontent.com/22428947/100330222-a968f900-3009-11eb-9338-efa375be3825.png)
![image](https://user-images.githubusercontent.com/22428947/100330685-3f9d1f00-300a-11eb-9449-0bde652052cd.png)
