### ISSUE TITLE
I coded a character limiter and wanted to share it with you and users

### ISSUE THREAD

**Issue by durangod** [tinymce/tinymce#6225]
**Is your feature request related to a problem? Please describe.**
Not really but there is no out of the box character limiter that i know of

**Describe the solution you'd like**
I coded the solution already, but im sure you can make it better, it works great.

**Describe alternatives you've considered**
Doing without... but i am proud of myself for being able to code this as my js skills are weak.

All you need to place a div after the textarea that has an id of  ??_countdown that the ?? matches your textarea id.  In my case i used  aboutme for my textarea id and  aboutme_countdown  and on the pages with multiple textareas i also gave those divs an id of  ??_countdown

Also be sure you have maxlength attribute on  your textarea as well.

Instructions are on the inside of this file... if you can make the code shorter, go for it... :)
    
[tm_custom_setup_character_counter_limiter.txt](https://github.com/tinymce/tinymce/files/5538656/tm_custom_setup_character_counter_limiter.txt)

I had to correct the instructions, sorry.  They are fixed now.

**Comment by lostkeys** [comment]
@durangod Thanks for your contribution 🤩. I've added it to our internal idea database. [Here is a working example in TinyMCE](https://fiddle.tiny.cloud/Kzhaab) for anyone who want to to see it in action.

**Comment by durangod** [comment]
Thanks... :)  that is nice of you 
 
On Monday, November 30, 2020 at 12:24 AM, Fredrik D <notifications@github.com> wrote:



@durangod Thanks for your contribution 🤩. I've added it to our internal idea database.   Here is a working   example in TinyMCE for anyone who want to to see it in action.

—
You   are receiving this because you were mentioned.
Reply to this email   directly, view   it on GitHub, or unsubscribe.
   [  {  "@context": "http://schema.org",  "@type": "EmailMessage",  "potentialAction": {  "@type": "ViewAction",  "target": "https://github.com/tinymce/tinymce/issues/6225#issuecomment-735576902",  "url": "https://github.com/tinymce/tinymce/issues/6225#issuecomment-735576902",  "name": "View Issue"  },  "description": "View this Issue on GitHub",  "publisher": {  "@type": "Organization",  "name": "GitHub",  "url": "https://github.com"  }  }  ]

**Comment by DNWEIJ** [comment]
Nice one! :-)

Just be aware, there is a small bug on the fidde (link of lostkeys) 
once hitting the limit, the alert popsup. klik ok
then the cursor goes to the beginning of the string.
type a letter, the letter is actually displayed. The error message popups. Press ok, the letter is still there, but 1 letter at the end is removed.....
Seems a bug to me, but other then that, good job! :-)

**Comment by prinsrob** [comment]
Hihi! Thank you for this, it is exactly what I need. Unfortunately, for me this does not work. If you try answering my question, keep in mind that I am new to programming  and might oversee something simple.

When I copy the code,, I do not see the tinymce textbox, I see a normal html textarea. When i remove the whole setup part, I see the tinymce box. 

When I use this for the setup in tinymce.init I see the tinymce textbox (with of course not the counter functionality);

setup: function(ed)
    {
    var id = this.id;  // the id of the html textarea
    }

When I use this for the setup in tinymce.init I see the html textarea, so I guess something goes wrong:

setup: function(ed)
    {
var elem = $(editor.getContainer());
}

Also this does not work, I see the html textarea:

setup: function(ed)
    {
 var limit = parseInt($("#" + (id)).attr("maxlength"));
}

Maybe this can give someone a clue to what I'm doing wrong. I use the cloud version where I have the src with the long personal number, i am not sure if this matters. Hopefully someone can help me solving this issue. Thanks in advance! :-)
