### ISSUE TITLE
Tinymce paste and powerpaste plugin improperly closes <li>

### ISSUE THREAD

**Issue by ss2020a** [tinymce/tinymce#6229]
**Tinymce paste and  powerpaste plugin improperly closes <li> when I copy/paste a piece of ordered list**

When I copy/paste a word content into tinymce, it closes the "LI" though it has a sub-list and create "OL" below the closed parent "LI".

**What is the expected behavior?**

It should create the sub-list as follows:
<li>parent list
<ol>
<li>sub list item</li>
<ol>
</li>

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?** 

TinyMCE 5.0.3 and powerpaste plugin Version: 4.0.0-312

**Comment by ss2020a** [comment]
[tinymce_powerpaste_bug_in_generating_ol.docx](https://github.com/tinymce/tinymce/files/5544358/tinymce_powerpaste_bug_in_generating_ol.docx)
Above the word content I copy pasted.  and it produced html code as stated in my next post

**Comment by ss2020a** [comment]
<p>---start of text ---</p>
<p>&nbsp;</p>
<ol>
<li>Level1 &ndash; 1<sup>st</sup> item</li>
<ol>
<li>Level2 -1<sup>st</sup> item</li>
<li>Level2 &ndash; 2<sup>nd</sup> item</li>
<li><strong>Level2 &ndash; 3<sup>rd</sup> item</strong></li>
<ol>
<li>Level 3</li>
<ol>
<li>Level 4</li>
<ol>
<li><strong>Level5</strong></li>
<ol>
<li>Level 6</li>
<li><strong><em>Level 6</em></strong></li>
<ol>
<li><em>Level 7</em></li>
</ol>
</ol>
</ol>
</ol>
</ol>
<li>Level2 &ndash; 4<sup>th</sup> item</li>
<li>Level2 &ndash; 5<sup>th</sup> item</li>
</ol>
<li>Level1 &ndash; 2<sup>nd</sup> item</li>
</ol>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>---end of text ---</p>

**Comment by ss2020a** [comment]
Please check the level 7, after level6.

<ol>
<li>Level 6**</li>**
<li><strong><em>Level 6</em></strong></li>
<ol>
<li><em>Level 7</em></li>
</ol>

**Comment by metricjs** [comment]
Hi @ss2020a, we can't assist with PowerPaste issues from GitHub sorry. Since you mentioned PowerPaste, I assume you have an active Tiny Cloud account, so please contact our support team via https://support.tiny.cloud/hc/en-us/requests/new who should be able to help further.
