### ISSUE TITLE
Close sub-menu when you click again on a menu title

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#623]
When you click on a menu title, a sub-menu appears. Can this sub-menu disappear when you click again on this sub-menu title ?

Regards

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5833](http://archive.tinymce.com/develop/bugtracker_view.php?id=5833) posted by [lhapaipai](http://archive.tinymce.com/profile.php?name=lhapaipai)_
> 
> _**Tags:** [menu toolbar]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
As far as I know the menu items open on hover now and not on click so I don't think this is relevant any more.
