### ISSUE TITLE
TAB and accessibility in TinyMCE - copy https://github.com/tinymce/tinymce-vue/issues/154

### ISSUE THREAD

**Issue by mesterjagels** [tinymce/tinymce#6230]
When trying to use TAB to jump through the fields in TinyMCE, focus stays on the toolbar. It is not possible to tab through toolbar and into the the textarea. 

**Browser:**
Firefox 83.0b9
Chrome 86.0.4240.193
possibly others

**Steps to reproduce:**

    Click tab into RTE
    Try to use TAB through toolbar, and attempt to tab into the textarea.

**Result:**
Focus stays on the toolbar

**Expected:**
Focus contiue to the textarea

Version: @tinymce/tinymce-vue: 3.2.6 - but it's possible to reproduce the bug in the editor available on your own page https://www.tiny.cloud/ - here you can't even tab the focus through the page into the TinyMCE toolbar

**Comment by lostkeys** [comment]
Hi @mesterjagels! This is not a bug, but how TinyMCE works. See [this page on how to use TinyMCE with a keyboard](https://www.tiny.cloud/docs/advanced/accessibility/#keyboardshortcuts). To get back to the editable area, press `esc`.

**Comment by mesterjagels** [comment]
@lostkeys thanks!
