### ISSUE TITLE
Preserving the custom classes in msword/html content while using paste or powerpaste plugin

### ISSUE THREAD

**Issue by ss2020a** [tinymce/tinymce#6231]
**Is your feature request related to a problem? Please describe.**

We have a requirement to cleanup ms word unwanted tags and proprietary styles/attributes etc at the same time we would like preserve any custom css classes we have added to table and other tags if any.  Paste or powerpaste plugin doesn't have a feature to preserving a list of custom classes (if exist please let me know.)

Version: TinyMCE 5.0.3

**Describe the solution you'd like**

For example, MS word table has <table class="CUSTOM_TBL">  a embedded class attribute.  powerpaste removes the custom class as well. We would like to preserve the same. 

**Describe alternatives you've considered**

Alternative,  creating custom plugin if no out of the box configuration available.

**Comment by ss2020a** [comment]
Actually, powerpaste_word_import:'merge' , option preserves the custom css class within the clipboard object.  But it also preserves numerous unwanted styles in the 'p' elements.  Is there a way, I can get rid of the inline styles but not the css classes with configurations only?

**Comment by lnewson** [comment]
Hi @ss2020a thanks for the request, however PowerPaste is a premium product and this GitHub project is for the open-source version of TinyMCE, so I'm afraid we can't assist via GitHub. Additionally, the community paste plugin has very limited word support, so we don't plan to add any additional word features to it at this stage. If you have a support subscription, then please contact our support team who will be able to help with your feature request: https://support.tiny.cloud/hc/en-us/requests/new
