### ISSUE TITLE
editor.getContent() not respecting custom format settings, returns bookmark element

### ISSUE THREAD

**Issue by DavidSvetlik** [tinymce/tinymce#6235]
If I unterstand correctly, [getContent()](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#getcontent) should return sanitized html content, however, I stumbled upon two bugs:

1. getContent doesn't respect my custom format settings - I had my bold and italic formats set to:

```
bold: { inline: 'b' },  
italic: { inline: 'i' },
```

And it works well in edit area, but getContent returns strong and em elements, respectively.

2. Second, related - when some media are present (eg. YouTube iframe) and editor works with `<span id="mce_marker" data-mce-type="bookmark">﻿</span>` element, this one is also returned by getContent.

Thank you for all your work!

Regards,
David S.

**Comment by wendelcosta** [comment]
Hi @DavidSvetlik  thank you for bringing this to our attention. 

The first issue can be overcome using the following: 
formats: {
	bold: {inline : 'b'},
         italic: {inline : 'i'},
},
schema: 'html5'

Please refer to: https://www.tiny.cloud/docs/configure/content-filtering/#schema

I couldn’t replicate your second issue though. 
Could you please send me a working code sample to that?

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.

**Comment by DavidSvetlik** [comment]
@wendelcosta Thank you, extended_valid_elements works!
