### ISSUE TITLE
Table resizing event

### ISSUE THREAD

**Issue by ElizavetaKoroleva** [tinymce/tinymce#6238]
No event is fired when starting to drag border of a table for resizing.

**Comment by metricjs** [comment]
Hi @ElizavetaKoroleva, could you please give us more details?

1. What event are you expecting?
2. What version of TinyMCE are you using?
3. Which resize handles are you referring to? The square handles at the corners of the table, or the row/column resize bars?

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
