### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ligne13** [tinymce/tinymce#6239]
Hi,

I have node v14.15.1 and yarn v1.22.5.
I have ran `yarn install` => OK.
Then `yarn build` fails when running the shell:tsc task:

```shell
Running "shell:tsc" (shell) task
../katamari/src/main/ts/ephox/katamari/api/Future.ts(1,21): error TS2307: Cannot find module '@ephox/wrap-promise-polyfill' or its corresponding type declarations.
../katamari/src/test/ts/atomic/api/async/FutureResultTest.ts(2,21): error TS2307: Cannot find module '@ephox/wrap-promise-polyfill' or its corresponding type declarations.
../katamari/src/test/ts/atomic/api/async/FutureTest.ts(2,21): error TS2307: Cannot find module '@ephox/wrap-promise-polyfill' or its corresponding type declarations.
../katamari/src/test/ts/atomic/api/async/LazyValueTest.ts(1,21): error TS2307: Cannot find module '@ephox/wrap-promise-polyfill' or its corresponding type declarations.
Warning: Command failed: tsc -b
 Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "tinymce-grunt" exited with 1.
error Command failed with exit code 1.
```

It seems it misses some @ephox modules. These are not in the node_modules/@ephox. But they are not required in  the package.json file.

Any idea ?

thanks

**Comment by lnewson** [comment]
Hi @ligne13,

I'd suggest trying to do a clean checkout/install again, as we have a nightly build that does this and it's building fine. Additionally, that dependency is in the package.json file here: https://github.com/tinymce/tinymce/blob/develop/modules/katamari/package.json#L19, so this suggests something failed to install properly on your system.
