### ISSUE TITLE
Right clicking in cell incorrectly shows non-table context menu on OS X

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#624]
Description of problem:
On OS X with a WebKit-based browser, right clicking an area of a table cell "without content" (such as the area where cell padding is) below/to the right of existing content in the cell will bring up the "normal" context menu (with insert image, etc.), as opposed to the "table" context menu (with table-editing options).

Using this normal context menu to perform an action like inserting an image will (if all cells in the below rows are empty) remove a row from the table if done in a cell in the last column.

The linked fiddle URL has basic instructions/description of how to reproduce it.

This is seen in TinyMCE version 3.5.8 (have seen it in at least one earlier version, 3.5.0.1). This was tested in Chrome 26 on Mac and Linux, as well as Safari 5.1 on Mac and Firefox 20 on Mac. The presumably incorrect context menu appears in Chrome/Safari on Mac but not in Firefox on Mac, nor does it occur in Chrome on Linux, or Chrome on Windows 7.

Steps to reproduce:
1. Using OS X Chrome/Safari, start a TinyMCE fiddle on version 3.5.8
2. Create a table with cell padding (2x2 with ~20px padding works well, showing guidelines is helpful for this)
3. Type a few characters into a cell in the last column (top-right cell)
4. Right click underneath the text in the padding area to open a context menu
5. Note how the context menu acts as if it is not opening within a table (includes options like Insert/Edit Image instead of table editing options)
6. Insert an image with this context menu, and then count the number of rows in the table afterwards. One should be missing.

Expected result:
Either the table context menu shows up at all times when right-clicking anywhere in a table, or any content inserted with the "normal" context menu (opened when right-clicking certain areas of cells) should leave the table intact upon inserting said content.

Actual result:
The normal context menu shows up when right-clicking certain areas of table cells, and inserting content via this menu adversely changes the table.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5834](http://archive.tinymce.com/develop/bugtracker_view.php?id=5834) posted by [ajp15243](http://archive.tinymce.com/profile.php?name=ajp15243)_

> _**Tags:** [safari chrome safari5 osx mac contextmenu webkit chrome safari tables]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/pddaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
