### ISSUE TITLE
Cannot find name 'PromiseConstructor'

### ISSUE THREAD

**Issue by chriscfox** [tinymce/tinymce#6240]
**What is the current behavior? Describe the bug**

Error Build:Cannot find name 'PromiseConstructor'.	SNA	.......\Scripts\tinymce\tinymce.d.ts	2723	

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Upgrade tinyMCE Nuget package from 5.1.5 to 5.5.1

**What is the expected behavior?**

Project should compile and run.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Visual Studio 2019. Previous version (1.5.1) worked.

**Comment by labilbe** [comment]
Same problem here with package <package id="TinyMCE" version="5.6.0" targetFramework="net461" />

**Comment by dinobrasi** [comment]
Same problem. 5.6.0

**Comment by ltrouton** [comment]
As of 5.5.0, a TypeScript declaration file is included in the bundle. If you add `"lib": [ "es2015", "dom" ]` to `compilerOptions` in the tsconfig.json file in your project, this should hopefully resolve the errors when building.

**Comment by chriscfox** [comment]
I created a file \Scripts\tinyMCE\tsconfig.json with the contents:
`{
  "compilerOptions": {
    "lib": [ "es2015", "dom" ]
  },
  "exclude": [
    "**/bin",
    "**/bower_components",
    "**/jspm_packages",
    "**/node_modules",
    "**/obj",
    "**/platforms"
  ]
}`
and after that my project compiled and ran again.
Hope that helps someone else.

**Comment by metricjs** [comment]
Thanks for reporting this @chriscfox, we're going to close this ticket as solved. However we will also look into if we can make Nuget installation easier.
