### ISSUE TITLE
In the table: quickbars_selection_toolbar and table_toolbar attributes conflict

### ISSUE THREAD

**Issue by flycj** [tinymce/tinymce#6245]
**What is the current behavior? Describe the bug**
![屏幕录制2020-11-18 下午2 49 23](https://user-images.githubusercontent.com/5103045/99496391-257e9380-29af-11eb-9161-d184ca993cfc.gif)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Sorry, I don’t have a reproduce project at the moment. 

**What is the expected behavior?**
It is expected that when multiple cells are selected in the table, table_toolbar will be displayed first

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
browser: chrome 86.0.4240.193
device: mac os 10.15.7
TinyMCE: 5.5

**Comment by lostkeys** [comment]
Hi @flycj! It is deliberate that when multiple cells are selected, the quickbars selection toolbar is shown, as many users want to be able to format content in multiple cells simultaneously. Currenly we have no plans to change that but I can log a feature request, in that case I need a bit more details on why you want the behaviour you ask for.

That said, there exists [APIs for creating your own context toolbar](https://fiddle.tiny.cloud/Syhaab), you might be able to piece something together that would work the way you want.

**Comment by flycj** [comment]
> Hi @flycj! It is deliberate that when multiple cells are selected, the quickbars selection toolbar is shown, as many users want to be able to format content in multiple cells simultaneously. Currenly we have no plans to change that but I can log a feature request, in that case I need a bit more details on why you want the behaviour you ask for.
> 
> That said, there exists [APIs for creating your own context toolbar](https://fiddle.tiny.cloud/Syhaab), you might be able to piece something together that would work the way you want.

Sorry, I may not describe it clearly, this is my use case. https://fiddle.tiny.cloud/Syhaab/8. and i purpose is also to make it more convenient for users. 
When I want to merge the two selected cells, the quickbars selection toolbar is shown, which prevents me from merging the cells nearby. So, in this case, I don’t know how to set the two cells that the user selects nearby. Can you help me?
