### ISSUE TITLE
The stretch frame of the picture disappears. It seems that there is something wrong with the positioning

### ISSUE THREAD

**Issue by 3812651** [tinymce/tinymce#6246]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lostkeys** [comment]
You need to provide more details for us to help. Please update the ticket and we can reopen it. Thx.
