### ISSUE TITLE
In the table: quickbars_selection_toolbar and table_toolbar attributes conflict

### ISSUE THREAD

**Issue by flycj** [tinymce/tinymce#6249]
**What is the current behavior? Describe the bug**
When I want to merge the two selected cells, the quickbars selection toolbar is shown, which prevents me from merging the cells nearby. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud] https://fiddle.tiny.cloud/Syhaab/8.

**What is the expected behavior?**
It is expected that when multiple cells are selected in the table, table_toolbar will be displayed first

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

browser: chrome 86.0.4240.193
device: mac os 10.15.7
TinyMCE: 5.5

[https://github.com/tinymce/tinymce/issues/6245](url)
@lostkeys 

in this case, I don’t know how to set the two cells that the user selects nearby. Can you help me?

**Comment by lostkeys** [comment]
I'm not sure I follow. TinyMCE intelligently merges the toolbars so you have the cell merge buttons while also having the quick selection buttons. Is the below image what you see as well?

<img width="766" alt="image" src="https://user-images.githubusercontent.com/3122929/99637746-940e3080-2a45-11eb-94a1-f81463c78bac.png">

**Comment by flycj** [comment]
I have implemented this method before, but one problem with this is that when the content selected by the user is not in the table, the quickbars selection toolbar will also appear on the table operation, which will make the user feel strange. So I don’t think this is a Elegant approach.
Thank you for responding to this question in your busy schedule, looking forward to tinymce getting better and better

**Comment by lostkeys** [comment]
Can you clarify this perhaps with a screenshot or a screen recording
> content selected by the user is not in the table, the quickbars selection toolbar will also appear on the table operation

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.

**Comment by NicolasDerumigny** [comment]
Sorry to reopen the issue, but I have the same problem. I am using TinyMCE on Joomla! 4 and the merge of the toolbars does not happen. Either the table toolbar is displayed, or the selection one, but never both at the same time.
