### ISSUE TITLE
Use standard CSS properties for table borders, padding and alignment

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#625]
Description of problem:

When adjusting table/table row or table cell properties through the various table menus within TinyMCE, certain options output deprecated HTML attributes instead of standard CSS.

Steps to reproduce:
1. In the editor, insert a table.
2. Customize the table's "border" property by setting it to "1"
3. Customize the table's "cell padding" property by setting it to "5"
4. In a table cell, customize the cell's "alignment" and "vertical alignment" (vertical alignment doesn't seem to be present in TinyMCE 4)
5. Look at the HTML that is output

Expected result:
&ltg;table style="border:1px solid black;padding:5px">
  &ltg;tr>
    &ltg;td style="text-align:left;vertical-align:top;">&ltg;/td>
  &ltg;/tr>
&ltg;/table>

Actual result:
&ltg;table border="1" cellpadding="5">
  &ltg;tr>
    &ltg;td align="left" valign="top">&ltg;/td>
  &ltg;/tr>
&ltg;/table>

The "align", "valign", "cellpadding", "cellspacing" and "border" attributes are all deprecated and no longer part of the HTML specification. Proper markup would be to use the CSS equivalents in an inline "style" attribute.

The reason this is very problematic is for anyone using a reset stylesheet: browsers will always choose the reset's style rule over the deprecated attributes. If inline CSS were present instead, the inline CSS would take precedence.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5835](http://archive.tinymce.com/develop/bugtracker_view.php?id=5835) posted by [dlockhart](http://archive.tinymce.com/profile.php?name=dlockhart)_

> _**Tags:** [firefox msie safari chrome opera 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by chrislrobert** [comment]
We've confirmed that this issue remains in both 4.4.0 and 4.4.1 -- not at all sure why it was closed. In particular, the obsolete HTML tags are still being used for cellpadding and cellspacing, which makes it difficult-to-impossible to properly display TinyMCE-generated HTML in many settings.

Any change you'd re-open and fix?

We might even try to develop a fix, but we're not at all sure about your system of plug-ins, etc. It would take us a while to develop a safe fix...

Thanks!

**Comment by piercy** [comment]
still a problem in 2017.

**Comment by piercy** [comment]
@blackcathikari i actually opened a new ticket #3619  for this as i wasnt sure my comment would be seen.  I include reproduction steps in it.  Hopefully that gives enough information?

Version wise we are using version 4.3.12  but i give an example reproducing it on the tinymce demo site using chrome.

Thanks

**Comment by blackcathikari** [comment]
Thanks for that @piercy, that does make it easier. Can definitely replicate it now, so I'll add a note to that effect to the new ticket. Personally I'm wondering if this is a regression or some weird interaction between plugins, but I'll leave that to the devs to sort out.

**Comment by piercy** [comment]
@blackcathikari is there anyway to see if theres been any movement on this issue? Obviously this issue is closed on github, but presumably its still open somewhere in the tinymce world. I only ask as im being chased for it by our customers and staff so i need to at least try keep on top of it a little.

Thanks,

**Comment by blackcathikari** [comment]
@piercy I've forwarded this to the devs and asked for an update, hopefully someone will get back to you soon. :)
