### ISSUE TITLE
Drag and drop contenteditable = false on chrome produce duplicate element

### ISSUE THREAD

**Issue by xsenechal** [tinymce/tinymce#6252]
**What is the current behavior? Describe the bug**
When I drag an element inside tiny and use event.dataTransfer.setData('text/html', '...'); to include a custom HTML element with contenteditable="false", It works as expected in Firefox BUT not in Chrome

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
![tiny-mce-bug-drag-and-drop-non-editable](https://user-images.githubusercontent.com/1405104/99668672-55d93700-2a6e-11eb-8b21-ea368c81106d.gif)
https://codepen.io/xsenechal/pen/LYZoxoj?editors=1010

**What is the expected behavior?**
We should have only the non-editable element inserted in Tiny, like in Firefox.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Chrome latest version
tiny v4 and v5

Thanks !

**Comment by JamesToohey** [comment]
Hi @xsenechal, we’ve done some investigation and this appears to be a bug in Chrome :(

You can replicate this with dragging into a plain content editable div: https://fiddle.tiny.cloud/k0haab/2

**Comment by JamesToohey** [comment]
@xsenechal a quick note - one of our engineers came up with this workaround that may work for you:

https://fiddle.tiny.cloud/k0haab/3

**Comment by xsenechal** [comment]
> @xsenechal a quick note - one of our engineers came up with this workaround that may work for you:
> 
> https://fiddle.tiny.cloud/k0haab/3

Thanks a lot for your answer. 
We added the paste plugin. and it appeared to work smoothly. 
However, after some time, the issue came again :(  on a particular case: after having dragged an item inside the editor
![chrome-drag-and-drop-tiny-paste-ko](https://user-images.githubusercontent.com/1405104/111785962-8c5c7c80-88bd-11eb-870f-c2f38e85ae8b.gif)
I ended up "rewriting" the drop:
```js
 editor.on('drop', (e) => {
  if(e.dataTransfer) {
    const html = e.dataTransfer.getData('text/html');
    let content = html.replace(/<meta.*?>/,'');
    editor.selection.placeCaretAt(e.clientX, e.clientY);
    editor.insertContent(content)
    e.preventDefault();
  }
});
```
https://fiddle.tiny.cloud/Y7haab/1
That could help others
