### ISSUE TITLE
There is a problem with the value calculated by the left attribute of the MCE resizehandle class, so that the stretched box of the image disappears

### ISSUE THREAD

**Issue by 3812651** [tinymce/tinymce#6253]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lostkeys** [comment]
You need to provide a more detailed description for us to be able to help you. Please submit a complete bug report or feature request.
