### ISSUE TITLE
Inline TinyMCE - width of the custom toolbar changed between 5.5.1 and 5.6.0

### ISSUE THREAD

**Issue by naro** [tinymce/tinymce#6256]
When migrated from TinyMCE 5.2.2 to 5.6.0 the custom inline toolbar element is displayed differently

The issue is clearly visible on https://fiddle.tiny.cloud/lzhaab/1  - try to run with 5.5.1 and 5.6.0 and check the size of the toolbar.

I expect the toolbar size to be the same as in 5.5.1

Browser: Chrome 87

**Comment by lnewson** [comment]
Hi @naro, sorry about this! It appears one of our fixes for another issue caused this. We released TinyMCE 5.6.1 to the community yesterday which will resolve this issue. If you have any further issues with this, please let us know.
