### ISSUE TITLE
I have a live app with my assigned key, but I am being directed to get the key again. 

### ISSUE THREAD

**Issue by JuiceDev20** [tinymce/tinymce#6257]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by metricjs** [comment]
Hi @JuiceDev20, we can't assist with Tiny Cloud issues from GitHub sorry. If you have an active Tiny Cloud account, could you please contact our support team via https://support.tiny.cloud/hc/en-us/requests/new who should be able to help further.
