### ISSUE TITLE
hope add a dialoginstanceApi argument for callback file_picker_callback

### ISSUE THREAD

**Issue by imic07** [tinymce/tinymce#6262]
**Is your feature request related to a problem? Please describe.**
now i cant use dialogInstanceApi.block() for spin

**Describe the solution you'd like**
```
 file_picker_callback: function (callback, value, meta, instanceApi) {
      // then wen can use spin
       instanceApi.block('Uploading');
       instanceApi.unBlock('Uploading');
 }
```

**Describe alternatives you've considered**
```
 file_picker_callback: function (callback, value, meta) {
      // then wen can use spin
       tinymce.activeEditor.setProgressState(true)
       tinymce.activeEditor.setProgressState(false)
 }
```

**Comment by JamesToohey** [comment]
Hi @imic07, thanks for this feature request. There are instances where this callback is triggered where there is no Dialog open, so the solution here will be slightly more complex.

However, I have passed this along to the product team for evaluation.

**Comment by doMynation** [comment]
Is there, by chance, a workaround to access to current dialog instance from that callback? I'd also need access the dialog API corresponding to the dialog being shown at the moment of selection of a file.

I've tried `this.windowManager.getWindows()[0]` but that instance doesn't seem to expose a `block()` nor `setProgressState()` method.

Thanks

**Comment by huyanyawei** [comment]
@JamesToohey
