### ISSUE TITLE
Copy Paste of Whatsapp Image is not working.

### ISSUE THREAD

**Issue by Sakthi002** [tinymce/tinymce#6266]
**Current Behaviour**
When i try to paste whatsapp image i am getting this error.
![image](https://user-images.githubusercontent.com/35330401/99941113-787f8e80-2d93-11eb-9e10-f13c751c27f9.png)

**Expecting behaviour**
Like gmail. Copy paste of Whatsapp Image.

**Comment by lostkeys** [comment]
You need to set up a backend on a server to store the images. [Have a look here](https://www.tiny.cloud/docs/configure/file-image-upload/). Please feel free to get back to us with more specific questions as you go.
