### ISSUE TITLE
Preview Popup not showing maths formulas

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#6271]
We are using MathType for inserting maths formulas. It is working properly but when clicking the preview button in the toolbar, it displays as simple text. 
Adding screenshots for references.
![image](https://user-images.githubusercontent.com/12448024/100104279-fd4dd380-2e8b-11eb-8763-d14459f39b6e.png)
![image](https://user-images.githubusercontent.com/12448024/100104312-06d73b80-2e8c-11eb-999d-cfbe45eaaafc.png)

**Comment by metricjs** [comment]
Hi @SIMRAN88. Tiny does not maintain Mathtype ([Wiris](http://www.wiris.com/mathtype) does) so unfortunately I'm not sure we'll be able to help. You may have more luck contacting their support team. However, in case it's something we can look into: 

1. Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
2. What is the HTML in the editor after inserting a formula? Are you able to make a replication case on our [Fiddle](https://fiddle.tiny.cloud/)?

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
