### ISSUE TITLE
Resizing issue in Tinymce 4.x

### ISSUE THREAD

**Issue by seraph17** [tinymce/tinymce#6272]
**What is the current behavior? Describe the bug**
When enabling 125% scaling, either in Windows display setting or by zoom in Chrome browser. Adjusting the width of the TinyMCE editor back and forth makes the content in the editor go outside the bounding box of the editor.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
http://jsfiddle.net/uys207go/
![image](https://user-images.githubusercontent.com/5106157/100111364-4f7ffc00-2e6e-11eb-8da9-28d4ee3fa75a.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It happens on Tinymce 4.x version, tested in Chrome 87, Windows10.

**Comment by lostkeys** [comment]
Hi! Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. If the issue still exists after upgrading to TinyMCE 5, please let us know and we'll reopen this issue.

Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
