### ISSUE TITLE
table merge cell 

### ISSUE THREAD

**Issue by raselcse13** [tinymce/tinymce#6278]
If i couple of row merge but got result 
![image](https://user-images.githubusercontent.com/24198895/100306405-81f43b00-2fcd-11eb-98f4-44009153c144.png)
![image](https://user-images.githubusercontent.com/24198895/100306428-8b7da300-2fcd-11eb-8f15-2ad022719f83.png)
![image](https://user-images.githubusercontent.com/24198895/100306438-959fa180-2fcd-11eb-81a5-d0a58c6f7526.png)
but i want get this like result
![image](https://user-images.githubusercontent.com/24198895/100306481-ba941480-2fcd-11eb-9501-4a5197ab0339.png)
 please help me how can i get this

**Comment by lostkeys** [comment]
Sorry it's not possible to configure or remove the line breaks that are inserted. A really advanced technique is to listen to the the table changes and replacing any <br> with a space manually.
