### ISSUE TITLE
Paste list from Word results in double numbers (chrome/safari)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#628]
Description of problem:
When pasting a list from MS Word into the editor you will get double numbers. F.e. :
1.	1. Dit is test 2
2.	2. Test 2
3.	3. Test
4.	4. Gedaan

Steps to reproduce:
1. Create a list in MS word
2. Copy the list
3. Open tinyMCE in chrome or safari
4. Paste the list

Expected result:
1.	Dit is test 2
2.	Test 2
3.	Test
4.	Gedaan

Actual result:
1.	1. Dit is test 2
2.	2. Test 2
3.	3. Test
4.	4. Gedaan
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5839](http://archive.tinymce.com/develop/bugtracker_view.php?id=5839) posted by [TjorvenB](http://archive.tinymce.com/profile.php?name=TjorvenB)_

> _**Tags:** [safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
