### ISSUE TITLE
Facing problem in Double click selection

### ISSUE THREAD

**Issue by srstechsolution** [tinymce/tinymce#6281]
**What is the current behavior? Describe the bug**
When we select Text and apply Uppercase. Its working fine.
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Create any Quote / Table
2. Write some text in block elements (Quote / Table).
3. Try to select text with double click.
4. Now apply uppercase. 
5. Text would be formatted successfully in Uppercase but text would be goes out the block elements (Quote / Table). 
**What is the expected behavior?**
Text would not be goes out from the block elements
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

We are using tinymce 4.7.4 and Google Crome browser Version 86.0.4240.198 (Official Build) (64-bit)

**Comment by lostkeys** [comment]
Hi. As the official support window for TinyMCE 4 is ending on December 31, 2020, we reccommend you have a look at TinyMCE 5 and see if the issue still persists (I could not replicate it myself) If that's the case, let me know and I'll reopen this ticket.

Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
