### ISSUE TITLE
Internet Explorer 11:  Rendering issue with Modal dialog when tinyMCE is rendered inside an iframe and editor displays a scrollbar

### ISSUE THREAD

**Issue by Pobaxi** [tinymce/tinymce#6282]
**What is the current behavior? Describe the bug**
This happens only with Internet Explorer 11.
Chrome, Firefox and Edge Chromium do not have this issue.
When tinyMCE is used from inside an iframe and the there is enough text rendered for the text area to require a scrollbar, modal dialogs are rendered incorrectly.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Use tinyMCE inside an iFrame.
TinyMCE has a height set.
Paste enough text into the text editor until a scrollbar appears
Open a Modal Dialog (link or anchor)

FiddleDemo here:
https://fiddle.tiny.cloud/Bzhaab

**What is the expected behavior?**
Modal dialogs are rendered correctly

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE Version: 5.6.1 
Browser: Internet Explorer 11
OS: Windows 10 Pro 1909

**Attachments**
Screenshot of a local repo
Zipfile containing the repo using selfhosted tinyMCE 5.6.1

![repo](https://user-images.githubusercontent.com/7623672/100378392-4d0ad700-3013-11eb-8248-9ac4b5585ea2.png)
[Repro.zip](https://github.com/tinymce/tinymce/files/5604345/Repro.zip)

**Comment by JamesToohey** [comment]
Hi @Pobaxi, unfortunately this is a rendering issue in IE11 which we are unable to work around with TinyMCE. Sorry about that :(

**Comment by Pobaxi** [comment]
@JamesToohey 
Hmm; ok.
Bit unfortunate, previous versions didn't have that problem. We used 4.4.3 before. Can you elaborate why you decided not to treat like a regression, so I can give a management summary to my PO?
Thank you.
