### ISSUE TITLE
isDirty() is not reliable

### ISSUE THREAD

**Issue by mriot** [tinymce/tinymce#6285]
**What is the current behavior? Describe the bug**
Some actions under certain circumstances are not registered properly and don't flip the dirty flag.

**Showcase**
I have made a gif for you to see.
![tinymce isdirty bug](https://user-images.githubusercontent.com/24588573/100524371-e4a92a80-31b7-11eb-88d6-58150f62be12.gif)

**What happens in the gif:** 

1. Pressing the backspace key (which fires **only** the onKeyUp event)
2. Pressing the 0 (zero) key on the keyboard (which now fires the onDirty event)
3. An autosave (automatically fired when the editor is dirty) kicks in and calls editor.save() (which internally resets the isDirty flag to false)
4. Pressing backspace again to remove the last 0 from 2020
4.1 As you can see, again only onKeyUp is being fired
5. Pressing backspace once more results in triggering onDirty event.

**What is the expected behavior?**
The dirty flag should respect all actions that change/modify the content.

**Specs**
- TinyMCE: 5.5.1
- TinyMCE-React: 3.8.1
- Chrome 87
- MacOS Catalina (10.15.7)

**Comment by JamesToohey** [comment]
Hi @mriot,

I have spent a bit of time trying to replicate this issue with no luck. It's possible it's something different with your TinyMCE configuration, could you set up a [fiddle](http://fiddle.tinymce.com/) with a reproduction case?

Thanks!

**Comment by mriot** [comment]
Hi @JamesToohey,

I tried to set up a fiddle but without luck.
The only thing I did basically was to add the react-tiny-mce-editor to my app.
Standard configuration stuff, nothing unusual.

Also I can't really predict _when_ it will happen. However, I noticed a lot of failures with chars like "?" and "!".
It also only happens, when you delete and insert the **same** character. If you add or remove one more, it will work like a charm. Or when you click with your mouse into the text area.

It feels like the "isNotDirty" property update is stalling.

As a workaround for my use-case I have added a length check that compares the length of the prev content with the current content. That covers like 99% of all cases where isDirty() fails.

**Comment by JamesToohey** [comment]
Hi @mriot,

It sounds like there might be an TinyMCE state vs. React state sync issue here. 

May I suggest using our official [React integration](https://github.com/tinymce/tinymce-react) instead of `react-tinymce-editor` and see if that resolves your issue?

**Comment by SreekuttanPS** [comment]
> Hi @mriot,
> 
> It sounds like there might be an TinyMCE state vs. React state sync issue here.
> 
> May I suggest using our official [React integration](https://github.com/tinymce/tinymce-react) instead of `react-tinymce-editor` and see if that resolves your issue?

Hi @JamesToohey,
I'm using official React Integration of TinyMCE, but the isDirty() is misbehaving. For me it's not working on the first state update, then it's working properly. It returns false for the first input, I don't know if I'm making any mistakes here as I'm new to React and TinyMCE.

```
        onEditorChange={(newValue, editor) => {
          editorChange(newValue, editor?.isDirty());
        }}
```
        
        - This is my onEditorChange, and below I have provided my function editorChange()
      
       ```
const onEditorChange = (newValue: string, isDirty: boolean) => {
           console.log('isDirty: ', isDirty);
           setValue(name, newValue, { shouldDirty: isDirty });
       };
```

       -So when I console the dirty field, its showing false for the first time, then shows correct value, Is there any solution?

**Comment by JamesToohey** [comment]
Hi @SreekuttanPS, unfortunately I no longer work on TinyMCE, you can probably reach out to the [tinymce-react](https://github.com/tinymce/tinymce-react/issues) team for help on this
