### ISSUE TITLE
 video_template_callback 参数使用，插入视频过程中地址有改变，再次编辑的时候会有不同步的问题bug

### ISSUE THREAD

**Issue by 1119879311** [tinymce/tinymce#6287]
**
问题就是 使用 video_template_callback 参数指定视频模板回调，视频地址的不能同步更新再次编辑的视频地址
描述：
1. 插入视频，通过粘贴视频地址在输入框中，然后修改再次粘贴新的视频地址再输入框中，然后保存，编辑器中显示视频了
2. 重新编辑 视频，然后发现输入框中的视频地址值是第一次粘贴的地址，而不是最新的，
3. 通过调试 plugin/media/plugin.js ，**
**
bug 复现如下图所示：

![屏幕截图 2020-11-29 183359](https://user-images.githubusercontent.com/26242205/100540212-e980e380-3276-11eb-81a7-7b89f1eaca3e.png)

![屏幕截图 2020-11-29 183640](https://user-images.githubusercontent.com/26242205/100540231-fef60d80-3276-11eb-8019-8516265548af.png)

![屏幕截图 2020-11-29 183457](https://user-images.githubusercontent.com/26242205/100540236-05848500-3277-11eb-9deb-4da69796dec9.png)

![屏幕截图 2020-11-29 183938](https://user-images.githubusercontent.com/26242205/100540243-103f1a00-3277-11eb-8ba2-ebd628fc1c73.png)

![屏幕截图 2020-11-29 183831](https://user-images.githubusercontent.com/26242205/100540247-19c88200-3277-11eb-9b2c-e72664c8f8c4.png)

``

**Comment by lostkeys** [comment]
I'm sorry we can only accept issues written in English 😞.

**Comment by sws797** [comment]
你好，我在插入视频后，`video`中的`source`标签会被转义成字符串，导致无法加载视频。请问你遇到过这个问题吗？
