### ISSUE TITLE
Table column widths calculated incorrectly when a td class applies horizontal padding

### ISSUE THREAD

**Issue by jeromegwilson** [tinymce/tinymce#6288]
### Background
We're using **TinyMCE v5.6.1** with **@tinymce/tinymce-react v3.8.0** to implement rich text editing on a site that uses the UK goverment design system: https://design-system.service.gov.uk/

One aspect of the design system is that it requires almost all HTML elements to implement specific classes. For example, all TDs must have class="govuk-table__cell". This has meant that we've had to write code to watch for relevant content node insertions or modifications and "forcibly" ensure that classes are set according to the GDS specifications. Generally speaking this approach works well.

See our (not standalone) implementation here: https://gist.github.com/jeromegwilson/29c52a34d5fb3f641042c568b9e3dd58

We've also implemented our own word count, rather than using the plugin, as we need to be able to count words server-side as well, but that's another story.

### The Problem
When table cells are given a class that implements horizontal padding TinyMCE calculates column widths such that the last column is squashed up very small. 

`editor.dom.setAttrib(editor.dom.select('td'), 'class', 'govuk-table__cell');`

```
.govuk-table__cell {
    padding: 10px 20px 10px 0;
    border-bottom: 1px solid #b1b4b6;
    text-align: left;
    vertical-align: top;
}
```

![image](https://user-images.githubusercontent.com/700334/100627179-97939880-331e-11eb-8fe0-f6f2d783cf5d.png)

### Workaround
We can mitigate this by overriding the padding on the table cell:
`content_style: 'td.govuk-table__cell { padding-left: 0; padding-right: 0 }'`

This results in correct column widths being calculated by TinyMCE at the expense of some difference between the table as rendered and how it looks in the editor.

### Testing
This has been tested in the latest versions of Chrome and Firefox.

**Comment by lostkeys** [comment]
Hi @jeromegwilson! I'm sorry but I'm not able to replicate your issue. Can you [recreate it in a TinyMCE fiddle](https://fiddle.tiny.cloud/) for me?

**Comment by lostkeys** [comment]
Meanwhile, here is a "TinyMCE native" example setting classes on `<td>`: https://fiddle.tiny.cloud/Xvhaab

**Comment by jeromegwilson** [comment]
Big thanks for your quick response Fredrik! 😄 We found today that delaying setting the class on a TD until the next tick (after the triggering event) resolves the issue, presumably because the class is then applied after the column width calculation has happened.

`setTimeout(() => editor.dom.setAttrib(editor.dom.select('td'), 'class', 'govuk-table__cell'), 0);`

I'll take some time as soon as possible to create a stand-alone JsFiddle that demonstrates the issue (or possibly demonstrates that it's been user-error all along 😁).
