### ISSUE TITLE
I can't find what I'm looking for: ui-components/dialogcomponents.md

### ISSUE THREAD

**Issue by Zmira134** [tinymce/tinymce#6289]
I was looking for: How to show an alert component (alert banner) in reaction to invalid input..
The alert banner text is different and set according to the invalid input

Thanks

**Comment by lostkeys** [comment]
Hi @Zmira134! Take a look at the [redial section of the dialog configuration docs](https://www.tiny.cloud/docs/ui-components/dialog/#redial) and perhaps the `onChange` function described in the [dialog configuration options](https://www.tiny.cloud/docs/ui-components/dialog/#configurationoptions).
