### ISSUE TITLE
Color picker ignores currently selected color

### ISSUE THREAD

**Issue by owagner24** [tinymce/tinymce#6293]
When you have a colored text focused, and want to adjust the color via the Custom Color Picker, the currently selected color is not selected. Instead always white is selected. It seems that the Color Picker modal always starts with white. This behavior differs from TinyMCE 4. Same when selected a color in the custom color picker, close it and reopen it.

In my eyes this is a bug, cause it differs from v4 and is helpful for the user if he only wants to adjust the color a little bit.

Steps to reproduce:

- Go to tinymce.cloud, scroll to the example editor
- Selected a word and click on the text color dropdown, select Custom Color
- Set the custom color to #ff0000 and click save
- Open the Custom Color Picker again via the text color dropdown

Observed:

- The color in the custom color picker is now white

Expected

- The custom color picker shows the currently selected text color, which is #FF0000

**Comment by lostkeys** [comment]
Thanks for your input! I'll flag it as a feature request.

**Comment by drose030** [comment]
Isnt this a bug since it used to work with v4?
Would be great to get this fixed since currently its impossible to find out the exact used color.

**Comment by SteveX** [comment]
I too would like to see this feature added / bug fixed.
