### ISSUE TITLE
width inline mode,the toolbar how to in a praticualcontainer?

### ISSUE THREAD

**Issue by qianyan123** [tinymce/tinymce#6295]
How can I create the editor toolbar in a praticual container instead of the body?
in order to scroll with the container

**Comment by lostkeys** [comment]
What (I think) you are looking for are the following config options
1. [Use Inline mode](https://www.tiny.cloud/docs/configure/editor-appearance/#inline)
2. Put the toolbar wherever you want it using the [fixed toolbar container option](https://www.tiny.cloud/docs/configure/editor-appearance/#fixed_toolbar_container)
3. Make the toolbar always visible by enabling [persistent toolbar](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_persist)

Let me know if I guessed right, if not please get back here and I'll reopen the ticket.
