### ISSUE TITLE
Uncaught TypeError: Cannot call method 'toAbsolute' of undefined 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#630]
Description of problem:
TinyMCE v 4.0b2 - when i include tiny_mce_popup.js to elFinder i get this error:
Uncaught TypeError: Cannot call method 'toAbsolute' of undefined  on line 45 in tiny_mce_popup.js
Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5841](http://archive.tinymce.com/develop/bugtracker_view.php?id=5841) posted by [Saja](http://archive.tinymce.com/profile.php?name=Saja)_
> 
> _**Tags:** [chrome chrome13]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. 🐛 

If you still have a problem connected to this, leave a comment and we can open it up again. 

Cheers! 🍺
