### ISSUE TITLE
I can't find what I'm looking for: api/tinymce/tinymce.notificationmanager.html - How to configure the css for the notification container

### ISSUE THREAD

**Issue by max-carroll** [tinymce/tinymce#6301]
Hi There, 

This is for tinyMCE v5

I am trying to configure the appearance of the notification manager to be full width, so I need to override the default styles.

It seems that styles are set by the style attribute on the tox notifications-container at the moment

```
<div
  class="tox-notifications-container"
  style="
    position: absolute;
    left: 549px;
    top: -805px;
    overflow: hidden auto;
    max-height: 805px;
  "
>
  <div
    role="alert"
    tabindex="-1"
    class="tox-notification tox-notification--in tox-notification--info"
  >
    <div class="tox-notification__icon">
      <svg width="24" height="24">
        <path
          d="M12 4a7.8 7.8 0 015.7 2.3A8 8 0 1112 4zm-1 3v2h2V7h-2zm3 10v-1h-1v-5h-3v1h1v4h-1v1h4z"
          fill-rule="evenodd"
        ></path>
      </svg>
    </div>
    <div class="tox-notification__body"><p>hello</p></div>
    <button
      type="button"
      tabindex="-1"
      class="tox-notification__dismiss tox-button tox-button--naked tox-button--icon"
    >
      <div aria-label="Close" class="tox-icon">
        <svg width="24" height="24">
          <path
            d="M17.3 8.2L13.4 12l3.9 3.8a1 1 0 01-1.5 1.5L12 13.4l-3.8 3.9a1 1 0 01-1.5-1.5l3.9-3.8-3.9-3.8a1 1 0 011.5-1.5l3.8 3.9 3.8-3.9a1 1 0 011.5 1.5z"
            fill-rule="evenodd"
          ></path>
        </svg>
      </div>
    </button>
  </div>
</div>

```
According to the docs https://www.tiny.cloud/docs/api/tinymce/tinymce.notificationmanager/, there are 3 methods for the notificationManager, `close() getNotifications() and open()` so how do I configure this class?

In [version 4 of the docs](https://www.tiny.cloud/docs-4x/api/tinymce.ui/tinymce.ui.notification/) there looks like there's some api where you can configure these, but how do I do that? there's no examples and I can't find anything by googling on the web unfortunately?

The problem I'm trying to solve here is to make the notification full width

**Comment by JamesToohey** [comment]
Hi @max-carroll, unfortunately overriding internal TinyMCE styles for our default skins is unsupported. If you wish to customize the appearance of TinyMCE, you can [create a skin](https://www.tiny.cloud/docs/advanced/creating-a-skin/).
