### ISSUE TITLE
How to insert <br> instead of <p> tag when Enter key pressing

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [tinymce/tinymce#6304]
Hi Team

How to config to insert `<br>` tag instead of  `<p>` tag when **Enter key** pressing.

**Comment by lostkeys** [comment]
Hi @Rajesh-Thiyagarajan! Use `forced_root_block: false` to generate `<br>` instead of `<p>`. [Read more about it here](https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block)

**Comment by codingyourlife** [comment]
but it still can produce p tags if you press shift+enter. how can I prevent this then?

**Comment by lostkeys** [comment]
I don't think there are any config options to disable that behavior.

**Comment by entegresoft-special** [comment]
asd
asd
asd
asf
