### ISSUE TITLE
Table resize handles shown when table_resize_bars set to false

### ISSUE THREAD

**Issue by dglaan** [tinymce/tinymce#6305]
**What is the current behavior? Describe the bug**
When table_resize_bars is set to false, initially the resize handles are not shown (as expected). 
After inserting a row or column, the resize handles are being shown, though.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
http://fiddle.tiny.cloud/d0haab
Insert a row or column. Hovering over the table cell borders shows a resize cursor.

**What is the expected behavior?**
When inserting a row or column, or altering the table in any way, should not activate the resize handles to being shown.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested in TinyMCE 5.5.1 in Chrome (87), Firefox (83), Edge (chromium, 87) on Windows 10

**Comment by JamesToohey** [comment]
Hi @dglaan, thanks for reporting this bug!

I've logged a ticket internally to fix this, we will let you know when we have a solution.

**Comment by nealchen-cn** [comment]
Hi Team, May I ask the status of the ticket, I encounter the same issue in Tinymce 6

**Comment by nealchen-cn** [comment]
I found a workaround is to overwrite the default CSS, it can work

**Comment by danoaky-tiny** [comment]
This has been fixed, tested on 6.8
