### ISSUE TITLE
editor.ui.registry.addButton

### ISSUE THREAD

**Issue by kiff86** [tinymce/tinymce#6306]
to add custom toolbar button I use pluginmanager, but button create with "tox-tbtn tox-tbtn--select" class. Why is this possible?
https://prnt.sc/vv47p9 - this is a pic of button view

code:
```
tinymce.PluginManager.add('customButton', function(editor, url) {
// my code
editor.ui.registry.addButton('imageManager', {
        text: '',
        icon: 'image',
        tooltip: 'customButton',
        onAction: function (){
            // my code
        }
    });
}
```

use //cdn.tiny.cloud/1/api-key/tinymce/5/tinymce.min.js

**Comment by JamesToohey** [comment]
Hi @kiff86, this is because you’ve included an empty string for `text` - try removing `text` entirely from your button config.

```
editor.ui.registry.addButton('imageManager', {
  icon: 'image',
  tooltip: 'customButton',
  onAction: function (){
    // my code
  }
});
```

**Comment by kiff86** [comment]
Hi @JamesToohey! Thanks for answer! Your advice helped.
