### ISSUE TITLE
Tabbing between table cells indents list when it should not.

### ISSUE THREAD

**Issue by iggybotes** [tinymce/tinymce#6307]
Repro Steps:

- Create a table that has a bulletpoint/ list in one of the cells (any cell except the first one).
- Click into a table cell that is before (to the left or above) the cell with the list in it.
- Click TAB till you reach the cell with the list in it.

Expected Behaviour:

- Cursor is positioned at the end of the cell's content.

Actual Behaviour:

- The list in the cell has been indented

Affects Version: TinyMCE 5.2
Affects Browser: Chrome
![chrome-capture](https://user-images.githubusercontent.com/22213473/101091661-569ccc00-361d-11eb-9d63-5b5c1a8efaf0.gif)

**Comment by JamesToohey** [comment]
Hi @iggybotes, I see you're in discussion with our professional support team so I will close this issue to keep the discussion in one location.
