### ISSUE TITLE
Odd auto injected html

### ISSUE THREAD

**Issue by Tejendi** [tinymce/tinymce#6310]
Hey,

We have are using tinyMCE, via Umbraco version 7.7.2.
We have recently started experincing some odd behacviour where some html appears in the tinyMCE RTE.

The html that appears are as following:
```
<div id="mailtovinduepopupToModalMail" style="z-index: 1;">
<div id="mailtovinduemailModalPopupTo">
<div id="mailtovinduecloseMailModal"><a id="mailtovinduecreateAppOpenEmailButtonNew"></a><button>Copy</button></div>
</div>
</div>
<div id="mailtovinduepopupToModalMail" style="z-index: 1;"></div>
<div><img alt="" /></div>
```
Here is how it looks rendered
![2020-12-04 14_37_02-Værd at vide - fsb dk](https://user-images.githubusercontent.com/3592726/101171719-75608a00-3640-11eb-9e1d-a40f8f9ffa26.png)

Any suggesting if this is because of some setting in tinyMCE or perhaps a browser addon?

**Comment by lostkeys** [comment]
Hi @Tejendi! We need some more details to be able to say why the link looks like that, but take a look into what css styles are loaded into the editor. Links in TinyMCE does not look like that by default, they look like regular blue links so this is not a setting we provide. Also just to have it said, we aren't responsible for the Umbraco integration so you might be able to get better help in a Umbraco oriented forum.
