### ISSUE TITLE
TinyMCE skins style not loaded

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6311]
@tinymce
I have using  tiny product. I click editor not open the toolbar. press 'F12' found some errors.
How to fix this,
If I include any path or We need add any editor config?.
Kindly request please give me solution or any way to solve this issue.

![Skin error](https://user-images.githubusercontent.com/21060460/96411760-a0188f80-1206-11eb-8ef8-31bd35b64ec9.png)
![editor](https://user-images.githubusercontent.com/21060460/96411775-a60e7080-1206-11eb-9ac4-5deed2ccb6bb.png)
![Folder](https://user-images.githubusercontent.com/21060460/96411782-a73f9d80-1206-11eb-88b1-828d7559d5c8.png)

Thanks. :)

**Comment by lostkeys** [comment]
Hi @Valgeria. It should just work if you're using the default skin. No special config options are needed. So you need to make sure css exists and are served on the missing paths. You can also define your own path using the [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_css) option. Hope this helps in your troubleshooting. If not, get back to us and we'll try to help.

**Comment by SXLaaa** [comment]
Can you send me the whole folder code？
