### ISSUE TITLE
Return url or base64 after uploading the picture

### ISSUE THREAD

**Issue by munitioner** [tinymce/tinymce#6314]
After I upload a picture in tinymce, sometimes it directly returns the url but sometimes it returns to the base, but my background processing program keeps returning the url. I want to know if this is related to tinymce?

**Comment by lnewson** [comment]
Hi @munitioner, TinyMCE will store non-remote images as Blobs or base64 images while editing. It will then try to upload images at various intervals if automatic uploads is enabled, or alternatively when calling `editor.uploadImages()`. When this happens it should always replace the Blob or base64 URI with the URL returned by your upload callback.

If this isn't happening, then can you please provide a way to replicate the issue or provide more details about exactly what's happening?

It's also worth mentioning that you may end up with base64 URLs if you aren't ensuring that images are uploaded before saving, as per: https://www.tiny.cloud/docs/general-configuration-guide/upload-images/.

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
