### ISSUE TITLE
Incorrect translation in sv_SE

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#6315]
"Paragraph" is translated as "Avsnitt", the proper translation is "Paragraf".

**Comment by lostkeys** [comment]
What an embarrassing mistake considering TinyMCE's Swedish origin.

**Comment by JamesToohey** [comment]
Hi @vanillajonathan, thanks for reporting this. Our community translations are contributed to by open-source community members [here](https://www.transifex.com/tiny/tinymce/). We have updated this (it may take some time to propagate), and if you'd ever like to contribute in the future you're more than welcome!
