### ISSUE TITLE
I got a strange html tags and text in the editor: 'What do you want to do ? New mailCopy...' etc

### ISSUE THREAD

**Issue by jeanboum** [tinymce/tinymce#6316]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by JamesToohey** [comment]
Hi @jeanboum, could you expand on your issue so we can better understand how to help? Could you please create a reproduction case in a TinyMCE Fiddle, an open source repository, or using a sandbox platform such as Codepen or JSFiddle?

**Comment by mgagliol** [comment]
Some of my students had a similar issue with moodle feedback fields, and it was related to a chrome or firefox extension called fenetre mailto, try deactivating/uninstalling it:
https://chrome.google.com/webstore/detail/fenetre-mailto/gepijnnkhnilemhhacebnhcndgogkamc

**Comment by metricjs** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate. Also, thanks for adding your workaround @mgagliol!
