### ISSUE TITLE
Lowerscore on tag name bug

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#632]
Description of problem:
TinyMCE seems to break when you use a custom tag that contains a lowerscore.
E.g. The syntax should look like
&ltg;custom_tag>My contents&ltg;/custom_tag>

When TinyMCE renders the underlying HTML, it displays something like this:
&ltg;custom_tag>My contents

Instead of just showing the text within the tag.

Steps to reproduce:
1. Visit TinyMCE home where there is a live editor:
http://www.tinymce.com/index.php
2. Edit the source code and paste this tag &ltg;custom_tag>My contents&ltg;/custom_tag>
3. Click the GO button and see how TinyMCE renders the HTML.
4. This only happens when there is a lowerscore in the tagname, it does not happen in any other situation, e.g. you can use mid-scores or other special characters, but the lowerscore seems the culprit.

Expected result:
It should display :
My contents

Actual result:
It displays:
&ltg;custom_tag>My contents

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5843](http://archive.tinymce.com/develop/bugtracker_view.php?id=5843) posted by [TheAgux](http://archive.tinymce.com/profile.php?name=TheAgux)_

> _**Tags:** [chrome custom tags]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
