### ISSUE TITLE
image with z-index:-1 in HTML not displayed in tinyMCE version5

### ISSUE THREAD

**Issue by chann7h** [tinymce/tinymce#6320]
**What is the current behavior? Describe the bug**

HTML containing <img> tag with z-index:-1 is not display. where as same HTML is displayed properly in chrome and edge browsers.
html e.g.

```
<p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt">
<span style="height:0pt; display:block; position:absolute; z-index:-1"><img src="HeartPicture.001.png" width="606" height="795" alt="" style="margin-top:-615.35pt; -aw-left-pos:0.3pt; -aw-rel-hpos:margin; -aw-rel-vpos:margin; -aw-top-pos:0pt; -aw-wrap-type:none; position:absolute"></span>
</p>
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

take any HTML having above content, load this html to tinyMCE

**What is the expected behavior?**
same as chrome browser, loads the background image

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

windows 10 with tinymce_v5_5_1

**Comment by JamesToohey** [comment]
Hi @chann7h, you have a significant negative margin in your inline style (`margin-top:-615.35pt;`) and that's what's causing the image to not appear, as it's rendering offscreen. If I remove this the image is visible, so this appears to be an issue with your styles and not TinyMCE, so I will close this issue.
