### ISSUE TITLE
Focus reverting to editor instead of first dialog element when shortcut to open a dialog is pressed

### ISSUE THREAD

**Issue by AmritGurung** [tinymce/tinymce#6326]
Bug: When you are on a editor and hit a shortcut key to open a dialog (e.g. `ctrl+f`, `ctrl+k`), the focus briefly appears on the first element of the dialog but reverts back to the cursor position on the editor. This only happens with dialogs opened with a shortcut key. Clicking the icon to open a dialog sets the focus on the first element properly.

Expected: When you press a shortcut key, a dialog opens with the focus set on the first element of the dialog. (e.g. You press `ctrl+f` and the find and replace dialog opens with focus on 'find' input field.)

TinyMCE version: 5.6.2 (bug present on older versions as well, as far as v4.8.5)
Browser tested: Chrome and Firefox (both latest stable releases)

Meta: So we've narrowed the issue down to the 'Visual Characters plugin'. Everything seems to work as expected until you set the `visualchars_default_state` option to `true` or execute the `mceVisualChars` command on initialization. Either of the change triggers the aforementioned issue.

**Comment by lnewson** [comment]
Hi @AmritGurung,

I attempted to replicate this using the default editor using both Chrome and Firefox and was unable to. After much more digging and given the hint about visual chars, I was able to replicate the issue under the following circumstances:
- Must be using either Inline mode or IE 11 (ie: not reproducible using the default iframe mode)
- Must have the visual chars plugin enabled and active
- Must not be using `forced_root_block: false`

Could you please confirm that you're only experiencing this with the above conditions? If so I'll log an internal task for us to investigate the Visual Characters plugin incorrectly stealing focus. If not, then can you please include a [fiddle](https://fiddle.tiny.cloud) or a video showing how to replicate the issue?

**Comment by AmritGurung** [comment]
Hello @lnewson,
Here is [the fiddle that replicates the aforementioned issue.](https://fiddle.tiny.cloud/y1haab)

Yes, we are using the inline mode and have the visual chars plugin enabled and active. We are not using the `forced_root_block` option, so I guess that defaults it to `false`. We can verify that setting `forced_root_block` option to `true` does not cause the aforementioned issue.

**Comment by shanereichart** [comment]
This affects me too.

**Comment by shanereichart** [comment]
### What causes the bug:
When`visualchars_default_state` is set to `true`, the visualchars plugin binds a global `keydown` event listener to ensure invisible characters (like non-breaking spaces) stay visible as you edit. Whenever any key is pressed, the plugin calls a debounced function scheduled for 300ms to rewrite the DOM to replace invisible characters with gray <span> tags. At the end of that DOM rewrite, the plugin deliberately calls `editor.selection.moveToBookmark(e)`. This action forcibly returns browser focus to the cursor/selection inside the editor.

However, the "Ctrl + K" keyboard command to open the "Insert/Edit Link" dialog also triggers the _keydown_ event, so 
300 milliseconds after the modal opens, the debounced function fires, reorganizes the DOM, and yanks the focus forcibly back to the editing container, stealing it right out of the modal.

### Monkey patch:
```
//if the cursor isn't in the editor when the debounced function fires, prevent returning the cursor to the editor
setup: function(editor) {
	editor.on('init', function() {
		var orig = editor.selection.moveToBookmark;
		editor.selection.moveToBookmark = function() {
			var el = document.activeElement;
			var res = orig.apply(this, arguments);
			if (el && el.closest('.tox-dialog')) el.focus();
			return res;
		};
	});
},
```
