### ISSUE TITLE
Icons not shown when applied to parent of nested sub-menu in style_formats

### ISSUE THREAD

**Issue by shanereichart** [tinymce/tinymce#6329]
In version 4.x, an icon applied to parent of nested sub-menu in style_formats would display as expected as such:

![image](https://user-images.githubusercontent.com/16807422/101858753-41053600-3b38-11eb-8386-745a7038e54e.png)

However in version 5.x, this icon is _not_ displayed as such:

![image](https://user-images.githubusercontent.com/16807422/101858912-95a8b100-3b38-11eb-8394-5dbec2bf5edb.png)

If it's unclear from the screenshots, this is an example of the type of nesting to which I'm referring:

```
style_formats: [
	{
		title: 'Visibility',
		items: [
			{
				title: 'Protected',
				icon: 'protected',
				inline: 'span',
				classes: 'protected'
			},
			{
				title: 'Custom',
				icon: 'custom', //This icon no longer works in TinyMCE 5.x.
				items: [
					{
						title: 'Team 1',
						inline: 'span',
						classes: 'custom-team1'
					},
					{
						title: 'Team 2',
						inline: 'span',
						classes: 'custom-team2'
					}
				]
			}
		]
	}
]
```

**Comment by lostkeys** [comment]
Thanks for finding this regression! We'll let you know here when there is a fix for this issue.
