### ISSUE TITLE
Spoiler tag, not just text color == background color

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#633]
Hello.

I am looking for a spoiler plugin, and i am not really good at JS yet, and it'd be a great feature so i thought maybe you could include it as a feature? :)

I'd like a spoiler like the one there is on the page i submitted ^^

You can go to the link and press "Vis..."

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5844](http://archive.tinymce.com/develop/bugtracker_view.php?id=5844) posted by [JapSeyz](http://archive.tinymce.com/profile.php?name=JapSeyz)_
> 
> _**Tags:** [spoiler]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://japseyz.dk/Test%20-%20Copy/?p=1337_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. 🐛 

If you still have a problem connected to this, leave a comment and we can open it up again. 

Cheers! 🍺
