### ISSUE TITLE
Lists of buttons instead of dropdown on template plugin

### ISSUE THREAD

**Issue by jzabate** [tinymce/tinymce#6330]
**Is your feature request related to a problem? Please describe.**
I would like to use buttons instead of dropdown on the template plugin dialog component.

**Describe the solution you'd like**
I duplicated the template plugin and trying to change the selectbox component into buttons.

**Describe alternatives you've considered**
Create a custom plugin from scratch

Is this doable? Where in the part of the template plugin.js needed to be changed as there is no comments per block of codes. Any suggestions for more doable solution?

**Comment by lostkeys** [comment]
Sorry, changing the dropdown to buttons is not possible with the default dialog. You can create your own template dialog with custom preview and insert the templates using the API's, more specifically [mceInsertTemplate](https://www.tiny.cloud/docs/plugins/opensource/template/#commands).
