### ISSUE TITLE
Add "enable" option for "browser_spellcheck" init property

### ISSUE THREAD

**Issue by BlindWanderer** [tinymce/tinymce#6334]
Browser spellchecking is pretty good these days and it would be nice if it could be forceably enabled.

Suggestion: add "enable" option (or similar) for the browser_spellcheck init option.

Here is the code in question in [InitContentBody.ts](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/init/InitContentBody.ts#L308)
```
  if (!settings.browser_spellcheck && !settings.gecko_spellcheck) {
    doc.body.spellcheck = false; // Gecko
    DOM.setAttrib(body, 'spellcheck', 'false');
  }
```

I'm just guessing at the typescript but I think it could be replaced with something like:
```
  if (settings.browser_spellcheck === 'enable') {
    doc.body.spellcheck = true; // Gecko
    DOM.setAttrib(body, 'spellcheck', 'true');
  }
  else if (!settings.browser_spellcheck && !settings.gecko_spellcheck) {
    doc.body.spellcheck = false; // Gecko
    DOM.setAttrib(body, 'spellcheck', 'false');
  }
```

**Comment by lnewson** [comment]
Hi @BlindWanderer, this is already possible. You just need to set the `browser_spellcheck` setting to `true`, as browsers will spellcheck content by default. An example can be found in our documentation: https://www.tiny.cloud/docs/configure/spelling/#browser_spellcheck
