### ISSUE TITLE
Duplicate number/letter, incorrect total value calculation

### ISSUE THREAD

**Issue by nanliu666** [tinymce/tinymce#6339]
![image](https://user-images.githubusercontent.com/30199403/102046865-2de3b600-3e17-11eb-9253-ed5cb38552d8.png)

![image](https://user-images.githubusercontent.com/30199403/102046911-448a0d00-3e17-11eb-920d-a8b26a9ecb5a.png)
![image](https://user-images.githubusercontent.com/30199403/102046926-4eac0b80-3e17-11eb-8625-ae0a4dfbe66d.png)

**Comment by lostkeys** [comment]
Hi! TinyMCE count words, not letters. I assume each character in that foreign language is counted as a word by that language.
