### ISSUE TITLE
No icon for selectall 4.x

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#634]
Description of problem: It's possible to add a selectall button to the toolbar, but it's blank.

Steps to reproduce:
1. Load default example into fiddle
2. Add selectall to plugins and toolbar in init
3. Click Run
4.
5.

Expected result:
A new button on the toolbar with an applicable icon

Actual result:
A new button on the toolbar with no icon

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5845](http://archive.tinymce.com/develop/bugtracker_view.php?id=5845) posted by [toxalot](http://archive.tinymce.com/profile.php?name=toxalot)_
> 
> _**Tags:** [4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/_

**Comment by ignaciogros** [comment]
Me too. 4.3.12. Thanks!

**Comment by kasparsj** [comment]
Tried with 4.7.4 - no icon.

**Comment by okainov** [comment]
Any update on it? The issue is still there with the latest version

**Comment by TimGallion** [comment]
I have the same problem with TinyMCE Version 4.8.3.
Is it solved with Version 5?

**Comment by alecpl** [comment]
I can confirm that It is fixed in TinyMCE 5.
