### ISSUE TITLE
ChromeOS not listed in the Editor UI keyboard navigation

### ISSUE THREAD

**Issue by jimunoz1990** [tinymce/tinymce#6343]
**Summary:** Chrome OS is **not** listed in the editor UI keyboard navigation.

**Expected behavior:** Chrome OS **is** listed in the editor UI keyboard navigation.

**OS affected**:
- Chrome OS

![Screenshot 2020-12-14 at 1 25 09 PM - Display 2](https://user-images.githubusercontent.com/2072649/102125840-e0177f80-3e0f-11eb-9b17-3c7a7f1a0ded.png)

**Comment by metricjs** [comment]
Hey @jimunoz1990. As mentioned in your linked PR, we do not consider this a bug. The browsers named in the Help dialog text are intended as examples, not an exhaustive list. If it was, we would also list GNU/Linux. In addition, we don't support ChromeOS per the [Supported Versions and Platforms documentation](https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/#supportedwebbrowsers) so it doesn't make sense for us to list it in the Help dialog. As such, I will also be closing this ticket.
