### ISSUE TITLE
Paste from outlook is not working

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [tinymce/tinymce#6346]
Hi Team
I am pasting a table from outlook to tinymce with premium plugins.
![image](https://user-images.githubusercontent.com/67726510/102175824-2bf91180-3e6e-11eb-9109-bf21b974efcf.png)

**Actual Result**
![image](https://user-images.githubusercontent.com/67726510/102175376-729a3c00-3e6d-11eb-97c8-e9fb46713794.png)

**Actual Result in Preview**
![image](https://user-images.githubusercontent.com/67726510/102175737-0c61e900-3e6e-11eb-98c3-e939ce4b6c7e.png)

**Note : ** Our old version we are using ckeditor. Now we planned to migrate with tinymce
**Expected Result coming in ckeditor**
![image](https://user-images.githubusercontent.com/67726510/102175869-3f0be180-3e6e-11eb-96c0-adcef7cc1f99.png)

**Expected Result in Preview**
![image](https://user-images.githubusercontent.com/67726510/102176014-88f4c780-3e6e-11eb-88c6-19542b6b7103.png)

**Comment by metricjs** [comment]
Hi @Rajesh-Thiyagarajan, from your screenshot of the Full Featured demo I assume you are using PowerPaste? If so, PowerPaste a premium product, so I'm afraid we can't assist via GitHub.  If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
