### ISSUE TITLE
[firefox] [Tinymce v4] nonEditable content in tables is buggy

### ISSUE THREAD

**Issue by mostafa-sakhiri** [tinymce/tinymce#6347]
Hello Tinymce team !

**Bug desription**

In our platform, we need to have some nonEditable content in tables. In firefox, when adding these nonEditable elements to a cell of a table, we can't move the cursor to the other cells of the same column using the mouse (it works using the keyboard).
The same issue exists in chrome but it's on the cells of the same line and cannot reproduce systematically like firefox.

I was able to reproduce easily the issue on the v4 demo but not on the v5. It will take us some time to upgrade from v4 to v5. So, we hope that you guys can fix that on v4 also.

**How to reproduce**
1. [Open tinymce demo page using firefox](https://www.tiny.cloud/docs-4x/demo/full-featured/)
2. Add a table with at least two rows
3. If you add a non editable content to one of the cells : you cannot have the cursor on the other cells of the same column using the mouse, if these cells are empty.
(How our non editable elements look like when rendered : `<span class="mceNonEditable" data-mce-contenteditable="false" data-mce-fragment="1" contenteditable="false">someTextContent</span>`)

**Expected behavior**
When adding a non editable content to a cell : I can move to the other cells of the same column and same row using the mouse even if they are empty.

**Comment by lostkeys** [comment]
Hi @mostafa-sakhiri. Sorry to disappoint you but we're ending support for TinyMCE 4 at the end of 2020, which is very soon. So now is the time to pay that technical debt and [upgrade to TinyMCE 5](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/). Don't hesitate to reach out if you face any issues upgrading.

**Comment by mostafa-sakhiri** [comment]
Got it. Thank you @lostkeys :pray:
