### ISSUE TITLE
contextmenu does not support image 

### ISSUE THREAD

**Issue by jbriner-pearson** [tinymce/tinymce#6349]
**What is the current behavior? Adding image to the contextmenu fails to show image**
Note: I have also seen problems with table imagetools. However, for simplicity, let's focus on image.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://codepen.io/jackbriner/details/eYdvXNB (I just added contextmenu from your basic example with bold and image).

**What is the expected behavior?**
I would have expected to see image and bold on the context menu. However, it only displays bold.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.6.2.  We had no problems with 4.9.1.

**Comment by metricjs** [comment]
Hi @jbriner-pearson. Context menu sections are often contextual - so the sections only appear when the selected content is of the right type. The default `image` context menu item only appears when you right-click on an image. This works as expected in your codepen. If you want the `image` context menu section to always appear, you could wrap it in a new context menu section like this:

```
tinymce.init({
  selector: 'textarea#basic-example',
  height: 500,
  menubar: false,
  plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table paste code help wordcount'
  ],
  contextmenu: 'quickimage bold',
  toolbar: 'undo redo | formatselect | ' +
  'bold italic backcolor | alignleft aligncenter ' +
  'alignright alignjustify | bullist numlist outdent indent | ' +
  'removeformat | help',
  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
  setup: function(editor) {
    editor.ui.registry.addContextMenu('quickimage', {
      update: function(element) {
        return ['image'];
      }
    });
  }
});
```

**Comment by lostkeys** [comment]
I believe @metricjs has provided an answer to your question so I'm going to close this issue. If you still have questions, please feel free to reopen this issue or create a new one.
