### ISSUE TITLE
Inline Tables and NonEditable Content - Table Cell Focus

### ISSUE THREAD

**Issue by HDorterPropel** [tinymce/tinymce#6350]
Hey Legends,

Loving the editor. Keep up the great work. Just a small bug I've come across when mixing some features together.

**Behaviour:** When clicking certain empty cells in inline tables that both contain NonEditable content, it doesn't bring focus to the cell you've clicked on.

**Example:** https://codesandbox.io/s/tinymce-and-react-table-cell-focus-bug-ng02y?file=/index.js

**Context:** I'm making a document template which populates the preset template fields from an API call.
A single table with 4 columns can't be used as the data can contain multiple lines and each side should not effect eachother's row height.
 
**Expected Behaviour:** Cell you're clicking on should gain focus. (Working in Firefox 84.0)

**Versions:**
MacOS
Chrome - 87.0.4280.88
Safari - 14.0

**Working perfect: Firefox - 84.0**

TinyMCE version: 5.6.2

 Cheers!

**Comment by lnewson** [comment]
Hi @HDorterPropel, thanks for the report! I can confirm this is an existing known issue which hasn't yet been scheduled to be fixed. I'll link this issue to our internal tracker and we'll make sure to notify you when a fix is available.

**Comment by HDorterPropel** [comment]
@lnewson Thanks mate! Appreciate the effort
