### ISSUE TITLE
change table width not work when defined a style in table

### ISSUE THREAD

**Issue by imic07** [tinymce/tinymce#6355]
**What is the current behavior? Describe the bug**
can't change table width

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

When Table has style='width:xxx', we can't change table width. I found tinymce change table.width nor table.style.width  
This is source html code:
```
<p style="text-indent: 24.0pt; line-height: 20.0pt;">
	<span style="font-family: 宋体;">
		<span style="font-size: 12.0pt;">
			<strong>xxxx</strong>：</span>
	</span>
</p>
<table style="border-collapse: collapse; width: 100%;" border="0" width="50%" cellspacing="0" cellpadding="0">
	<tbody>
		<tr style="height: 34px;">
			<td style="width: 168px; border: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt; height: 34px;">
				<p style="text-align: center; line-height: 20.0pt;">xxx</p>
			</td>
			<td style="width: 435px; border: solid windowtext 1.0pt; border-left: none; padding: 0cm 5.4pt 0cm 5.4pt; height: 34px;">
				<p style="line-height: 20.0pt;">
					<span style="font-family: 宋体;">
						<span style="font-size: 12.0pt;">zzzzz</span>
					</span>
				</p>
			</td>
		</tr>
		<tr style="height: 38px;">
			<td style="width: 168px; border: solid windowtext 1.0pt; border-top: none; padding: 0cm 5.4pt 0cm 5.4pt; height: 38px;">
				<p style="text-align: center; line-height: 20.0pt;">xxx</p>
			</td>
			<td style="width: 435px; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt; height: 38px;">xxx</td>
		</tr>
	</tbody>
</table>
<p style="text-align: center; line-height: 30.0pt;">&nbsp;</p>
```

**What is the expected behavior?**
can change table size

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 5.6.1/deepin20/chrome latest

**Comment by lostkeys** [comment]
Sorry, I can't recreate your problem. Can you please replicate the issue in a [TinyMCE Fiddle](https://fiddle.tiny.cloud/) and then reopen this ticket? Would be much appreciated. Cheers.

**Comment by imic07** [comment]
I use source html code in TinyMCE Fiddle, 
1. click table properties, change general.width to 20% and save
![image](https://user-images.githubusercontent.com/16321067/102855829-4fb8ea80-4460-11eb-9f32-0dab4600b928.png)

2. 
![image](https://user-images.githubusercontent.com/16321067/102855860-62332400-4460-11eb-9c1c-640c9614900b.png)

3. check source html code. found table.style.width work, not table.width work.
![image](https://user-images.githubusercontent.com/16321067/102855973-a9b9b000-4460-11eb-9092-9b1db6441f64.png)

**Comment by imic07** [comment]
@lostkeys this is operation video:
https://user-images.githubusercontent.com/16321067/102857813-12565c00-4464-11eb-8dd9-b140aaf3f7ef.mp4
