### ISSUE TITLE
A custom format container is not deleted if there was a paragraph with text in it, and when deleted, text outside the container and all text inside the container are selected

### ISSUE THREAD

**Issue by fredure** [tinymce/tinymce#6356]
**What is the current behavior? Describe the bug**
A custom format container is not deleted if there was a paragraph with text in it, and when deleted, text outside the container and all text inside the container are selected

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Add a paragraph with text to a custom format container;
2. Select text under a custom format container and all text inside the container;
3. Press "backspace".

Codepen: https://codepen.io/fredure/pen/abmWxgg

Gif:

![2020-12-17 20-01-25](https://user-images.githubusercontent.com/8024592/102518729-b3c76180-40a2-11eb-9b52-bb15361507b3.gif)

**What is the expected behavior?**
The text was removed along with the custom format container. With current behavior, only the inner paragraph is deleted

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: 5.2.0 (2020-03-14).
Browsers: all.
OS: all.

**Comment by lostkeys** [comment]
This is more a behavioral issue than a bug. We have requests to not delete the wrapper as well. That said, a regular blockquote wrapper is deleted when doing the same operations as you describe above, so I'll tag this as a question and more knowledgeable persons might chime in.

**Comment by metricjs** [comment]
The development team discussed this and we agree @lostkeys. We have also had requests to do the opposite, so we are going to mark this as a feature request for the ability to customise this behaviour.
