### ISSUE TITLE
API for updating icon of menu button

### ISSUE THREAD

**Issue by dakur** [tinymce/tinymce#6359]
Hi!

**Is your feature request related to a problem? Please describe.**

I want let user to choose vertical alignment for table cell and update the button's icon based on currently set alignment. In tinymce v4, I was able to update button's icon using `onPostRender: (e) => listenOnNodeChangeAndUpdateUsing(e.target.state.set('icon', '...'))`. With v5 API I can not think of a way how to achieve that.

![image](https://user-images.githubusercontent.com/9862581/102685836-93eb8700-41e3-11eb-9c9a-228ef59e3486.png)

**Describe the solution you'd like**

`onAction()` method can pass `api` parameter with `updateIcon()` method or icon can obtained using callback on every node change.

Solution using `updateIcon()`:

```js
const options = [
	{value: VerticalAlignPositions.TOP, icon: 'vertical-align-top', text: 'Top'},
	{value: VerticalAlignPositions.MIDDLE, icon: 'vertical-align-middle', text: 'Middle'},
	{value: VerticalAlignPositions.BOTTOM, icon: 'vertical-align-bottom', text: 'Bottom'}
];

editor.ui.registry.addMenuButton('verticalalign', {
	icon: 'vertical-alignment-top',
	fetch: (callback) => {
		const currentVerticalAlignment = getVerticalAlignmentOfFocusedCell(editor);
		callback(options.map((option) => ({
			type: 'togglemenuitem',
			text: option.text,
			active: option.value === currentVerticalAlignment,
			onAction: (api) => {
				setVerticalAlignmentToFocusedCell(editor, option.value),
				api.updateIcon('vertical-alignment-' + option.value);
			}
		})));
	},
});
```

Solution using callback:

```js
const options = [
	{value: VerticalAlignPositions.TOP, icon: 'vertical-align-top', text: 'Top'},
	{value: VerticalAlignPositions.MIDDLE, icon: 'vertical-align-middle', text: 'Middle'},
	{value: VerticalAlignPositions.BOTTOM, icon: 'vertical-align-bottom', text: 'Bottom'}
];

let currentIcon = 'vertical-align-top'; // default value
editor.ui.registry.addMenuButton('verticalalign', {
	icon: () => currentIcon,
	fetch: (callback) => {
		const currentVerticalAlignment = getVerticalAlignmentOfFocusedCell(editor);
		callback(options.map((option) => ({
			type: 'togglemenuitem',
			text: option.text,
			active: option.value === currentVerticalAlignment,
			onAction: () => {
				setVerticalAlignmentToFocusedCell(editor, option.value),
				if (option.value === currentVerticalAlignment) currentIcon = 'vertical-alignment-' + option.value;
			}
		})));
	},
});
```

**Comment by lostkeys** [comment]
I suggest that a property is added on the menu-button that when true, replaces the **menu-button**'s icon with the **menu-item** icon when selected. The [align toolbar button already have this behavior](https://fiddle.tiny.cloud/01haab) so the logic is in there somewhere.

**Comment by dakur** [comment]
That might work in my case, but it does not seem to be fully flexible as it does not take different use-cases into account (at least from what I can see). What if I have nested menu items there like in this [official example](https://www.tiny.cloud/docs/demo/custom-toolbar-menu-button)? When clicked `My button > Menu item 2 > Sub menu item 1` one would want the `Menu item 2` icon to be set, but another one the `Sub menu item 1` icon be set.

Also, it is interaction driven, not state driven. The state of the "main" button would be – in my use-case – taken from what user did, not from what the state of the table cell in DOM is, which is not reliable. That's actually why I thought of callback or API using custom state instead. In such case, I would go e.g. with `icon: () => deriveIconFromDom()`, someone else with `icon: () => someLocalVariable` or just `icon: 'some-icon'` – flexible enough in my opinion.

What do you think?

**Comment by dakur** [comment]
By the way, how is it achieved in the example? Is it [this `addNestedMenuItem('align')`](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/themes/silver/main/ts/ui/core/complex/AlignSelect.ts#L68)? I did not know that menu items are applicable to toolbars.

**Comment by dakur** [comment]
> By the way, how is it achieved in the example?

As far as I understood, it relies on some internal stuff which is not available in built code. There is this `updateSelectMenuIcon()` which would be nice to use. 🙂

**Comment by lostkeys** [comment]
This is a bit too technical for me. Maybe @lnewson or @metricjs can chime in.

**Comment by dakur** [comment]
@lostkeys @lnewson @metricjs Guys, are there any updates on this? At least some opinions or suggestions?

**Comment by Anu3ev** [comment]
up

**Comment by TheSpyder** [comment]
We've nearly finished this, see #8353. It's about ready to merge so should make it into the 6.4 release.

There's already an api parameter to `onAction`, we added it to `fetch` as well where appropriate.

**Comment by TheSpyder** [comment]
Correct, it's also something we struggle with internally but we are starting to look at ways to make it easier.

It's not ideal, but you could try this:
* Check out TinyMCE to the branch
* run `yarn build`
* take the `js/tinymce` folder and overwrite the contents of `node_modules/tinymce`

**Comment by dakur** [comment]
Ok, there were some problems with types, but I've handled that.\*

Now, to the core. It kind of works but when I click the menu item, correct icon is rendered for few miliseconds but then it's replaced with the default one again (`'vertical-align-top'`). I've digged into it and the cause is `editor.nodeChanged()` call in the `setVerticalAlignmentToFocusedCell()` which causes some rerender of toolbar icon.

As far as I understand concept of tinymce, that dispatcher should be there, shouldn't it? I'm changing DOM so all listeners should have a chance to react to changes.

So is it bug in `api.setIcon()` implementation? Or am I missing something?

Thank you.

Simplified code:

```ts
editor.ui.registry.addMenuButton('verticalalign', {
	icon: 'vertical-align-top',
	fetch: (callback, _, api) => {
		const currentVerticalAlignment = getVerticalAlignmentOfFocusedCell(editor);

		const update = (value: string, icon: string) => {
			setVerticalAlignmentToFocusedCell(editor, value); // update content
			api.setIcon(icon); // update editor UI
			editor.focus();
		};

		callback([
			{
				type: 'togglemenuitem',
				text: 'Top',
				icon: 'vertical-align-top',
				active: currentVerticalAlignment === 'top',
				onAction: () => update('top', 'vertical-align-top'),
			},
			{
				type: 'togglemenuitem',
				text: 'Middle',
				icon: 'vertical-align-middle',
				active: currentVerticalAlignment === 'middle',
				onAction: () => update('middle', 'vertical-align-middle'),
			},
			{
				type: 'togglemenuitem',
				text: 'Bottom',
				icon: 'vertical-align-bottom',
				active: currentVerticalAlignment === 'bottom',
				onAction: () => update('bottom', 'vertical-align-bottom'),
			},
		]);
	},
});

const setVerticalAlignmentToFocusedCell = (editor: Editor, value: string) => {
	const focusedCell = getFocusedTableCell(editor);
	editor.dom.setStyle(focusedCell, 'vertical-align', value); // update style
	editor.nodeChanged(); // fire listeners
};
```

----

\* I had to preserve `package.json` from tinymce installed in usual way and I had to change all plugin and theme imports from `import 'tinymce/plugins/searchreplace'` to `tinymce/plugins/searchreplace/plugin`

**Comment by TheSpyder** [comment]
Oh wow, I didn't realise it would be so challenging to use a dev build. Thanks for putting that effort in!

It could be a bug, yes. I'll ask the developer who worked on it to take a look.

**Comment by TheSpyder** [comment]
I can't reproduce it using your sample code on fiddle - I had to make some adjustments due to the lack of icon and `getFocusedTableCell` method:
https://fiddle.tiny.cloud/Iyiaab

Can you please adjust it to reproduce what you're seeing?

**Comment by dakur** [comment]
@TheSpyder Sorry for delay, I was unable to reproduce it for a longer time but now I found out it's about where you place the button. If it's inside of main toolbar, it works. But when you place it into the floating toolbar of table, it starts behaving like I describe above.

Just add `table_toolbar: 'verticalalign'` to the tinymce config object a re-run the fiddle.

**Comment by TheSpyder** [comment]
That's because context toolbars are recreated in response to the `nodechange` event, which your code triggers. The fix is to make sure the `onSetup` function sets the icon to the correct state (I also added a `nodechange` listener so the toolbar button updates as the cursor moves around).
https://fiddle.tiny.cloud/Iyiaab/3

**Comment by dakur** [comment]
Thanks for the explanation of the recreating, it makes sense definitely. 

Now it works as expected. Also calling `api.setIcon(icon)` in items's `onAction()` as well as setting `active` is not needed anymore as both are handled in the `onSetup` callback.

Thank you very much!
