### ISSUE TITLE
addChoiceButton() for toolbar buttons

### ISSUE THREAD

**Issue by dakur** [tinymce/tinymce#6362]
**Is your feature request related to a problem? Please describe.**

I want let user to choose vertical alignment for table cell, but I'm not sure what is the best way to achieve that.

![image](https://user-images.githubusercontent.com/9862581/102785685-a5c55980-439e-11eb-8853-fe37c43f4f69.png)

**Describe the solution you'd like**

I believe there should be something like `addChoiceButton()` which allows me to define such enum feature with proper state handling without the need of main button. It's almost identical to `addSplitButton()` with the difference that there is no main button. So it is split button in how it works, but menu button in how it looks and interacts. It improves UX in this case (see explained below).

**Describe alternatives you've considered**

With `addMenuButton()`, there is the `togglemenuitem`, which works as intended but semantically it does not make sense, because it is not that each of the option could be on or off, but only one of them could be selected. If I write code below, it technically works but it does not make sense:

```js
editor.ui.registry.addMenuButton('vertical-align', {
	fetch: (callback) => callback([
		{
			type: 'togglemenuitem',
			text: 'top',
			active: true,
		},
		{
			type: 'togglemenuitem',
			text: 'middle',
			active: true,
		},
		{
			type: 'togglemenuitem',
			text: 'bottom',
			active: false,
		},
	]),
});
```

So `addSplitButton()` makes more sense which handles the items in enum way. But it is tied to the functionality of the main button which I have problem with. I *could* use it in theory and it works as alignment could or couldn't be applied (so it is or is not active), but from UX point of view, it does not make sense to prefer top (or any other) alignment over others as all are equally used. Instead, I want user to instantly choose from all of the options, not to make him search the dropdown icon after unsuccessful clicking on the main button's icon. It is similar to [this example](https://fiddle.tiny.cloud/01haab) with text alignment from related issue #6359.

The toolbar button would be then active if any of the options is active, otherwise not.

But maybe I just can not see proper solution, let me know. 🙂

**Comment by lostkeys** [comment]
Thanks for your feedback! I've labeled it as a feature request. A button for vertical alignment is part of an upcoming major update to tables scheduled for 2021, but I have no further details at this time.

**Comment by TheSpyder** [comment]
We added menu toolbar buttons in TinyMCE 6.2, does that cover what you need?
https://www.tiny.cloud/docs/tinymce/6/custom-menu-toolbar-button/

**Comment by dakur** [comment]
@TheSpyder Thanks for the response. I guess you meant *searchable* menu button, didn't you? No, that doesn't help in any way, sorry. 

This issue is rather about having to imitate "enum" button with three single menu items than about users can not find items.
