### ISSUE TITLE
What is this fancymenuitem?

### ISSUE THREAD

**Issue by dakur** [tinymce/tinymce#6363]
Sorry for a question here, but I guess no one would answer me on stackoverflow as it looks rather like an internal accidentally exposed to public. When I worked with menu buttons, I've noticed Typescripts auto-suggests me `fancymenuitem` for `type` in menu items. But it is not mentioned in the docs. What is it useful for?

Thank you.

![image](https://user-images.githubusercontent.com/9862581/102796051-f42e2480-43ad-11eb-8a0f-f9b8ca4ab587.png)

**Comment by lostkeys** [comment]
`fancymenuitem` are our internal name for more complex menuitems, currently we have two: the color swatch picker and the insert table grid. They are currenly undocumented and "private" thus can change without notice in any release. Here is an example of how to use the color swatch picker menuitem: https://fiddle.tiny.cloud/D1haab

**Comment by dakur** [comment]
Thank you for your answer and detailed example!
