### ISSUE TITLE
Inserting rich text into an image requires a callback method.图片插入富文本需要一个回调方法

### ISSUE THREAD

**Issue by taozuidesongshu** [tinymce/tinymce#6369]
**Is your feature request related to a problem? Please describe.**
希望在图片插入富文本时增加一个回调方法，方便开发者把第三方链接转换为自己的图库链接
We want to add a callback method when the image is inserted into rich text, so that developers can convert the link to their gallery address
![image](https://user-images.githubusercontent.com/37061056/102972946-e35cea80-4536-11eb-86d1-b303a55c58de.png)

**Comment by lnewson** [comment]
Hi @taozuidesongshu, could you please clarify the workflow you're attempting to use here a little more? As an example:
- Do you mean when an image is inserted via the image dialog, or when for example pasting an image?
- What do you mean by a "gallery address"?

I should also add that you might be able to solve this using the [urlconverter_callback](https://www.tiny.cloud/docs/configure/url-handling/#urlconverter_callback) setting, as it will allow converting a URL to some other URL when content is inserted into the editor.

Lastly, I also want to mention that in the screenshot I can see you're using TinyMCE 4. TinyMCE 4 is no longer a supported version of TinyMCE: https://www.tiny.cloud/blog/tinymce-4-support-window/

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.

**Comment by taozuidesongshu** [comment]
工作流程：用户通过图像对话框插入任意图片链接并点击确定>web回调方法将链接传递到服务端>服务端校验图片是否合格>上传至私有的图库并返回图库链接>web回调方法接收图库链接插入到文本域内

Work flow: The user inserts any picture link through the image dialog box and clicks OK>web callback method to pass the link to the server>server verifies whether the picture is qualified>upload to a private gallery and return to the gallery link>web callback method to receive the gallery link Insert into the text field
