### ISSUE TITLE
Paste from MSWord drops content from table cells

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#637]
Description of problem:

When copying tables from MS Word, some of the content is dropped.  In particular, table cells with a &ltg;p> element with class="MsoNormal" with content that includes a period character ('.').  All of those appear to be necessary to reproduce the problem.

Steps to reproduce:
1. Visit this fiddle:  http://fiddle.tinymce.com/Qddaab
2. Copy the first table.
3. Paste into the editor (stock editor, no changes).

Expected result:

Table matches the content copied, including the "x."

Actual result:

The content -- the "x." -- is dropped.

If you do the same thing with the second table (the one with just "x", no period), then the paste works as expected.  It appears to be something special with the period?

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5848](http://archive.tinymce.com/develop/bugtracker_view.php?id=5848) posted by [codyebberson](http://archive.tinymce.com/profile.php?name=codyebberson)_

> _**Tags:** [firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
