### ISSUE TITLE
Copy table from Excel, the data in cell will be align left, should remain unchanged

### ISSUE THREAD

**Issue by MelodyHJ** [tinymce/tinymce#6373]
in Excel: 

![image](https://user-images.githubusercontent.com/76765896/103332888-cda37400-4aa6-11eb-81eb-93aed7bc254a.png)

Copy in tinymce

![image](https://user-images.githubusercontent.com/76765896/103332948-fb88b880-4aa6-11eb-966b-25f0ac9d9d1f.png)

**Comment by lnewson** [comment]
As noted in #6374, Excel is not supported by the community Paste plugin so again I'm going to close this sorry, as this isn't something we plan to support for the community Paste plugin. Again though, you can possibly get it to work by tweaking the settings as mentioned in the previous issue.
