### ISSUE TITLE
Copy table from excel, the frame will be lost

### ISSUE THREAD

**Issue by MelodyHJ** [tinymce/tinymce#6374]

**Comment by lnewson** [comment]
Hi @MelodyHJ , I'm afraid Excel is not supported by the community paste plugin, so I'm going to close this.

I should add, it's also possible it might be falling through to the legacy/deprecated Word handling logic, so might be able to get something to work by tweaking the [paste_retain_style_properties](https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_retain_style_properties) or [paste_word_valid_elements](https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_enable_default_filters) settings to allow what you want. You could also try disabling the word filter by setting [paste_enable_default_filters: false](https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_enable_default_filters).

Note: If you're looking for something that supports Word/Excel paste, then I'd suggest looking into our Premium PowerPaste plugin.
