### ISSUE TITLE
Branding/Attribution in Inline mode?

### ISSUE THREAD

**Issue by mirkootter** [tinymce/tinymce#6376]
**What is the current behavior? Describe the bug**
```branding: true``` has no effect in Inline mode.
Since branding is mandatory, this bug makes TinyMCE much harder to use.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Use any of the Inline samples.

**What is the expected behavior?**
For example, the branding could be shown above the toolbar instead of the statusbar which does not exist in inline mode.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.6.2, all browsers

**Comment by lostkeys** [comment]
Hi @mirkootter! As designer, I've explored that and it becomes too intrusive. The different versions of inline mode allows so many different stylistic implementations that it's more or less impossible to have a attribution that is both elegant but visible. Therefore we decided to leave it up to you as a developer to implement the attribution in a way that makes sense in your specific use-case [as outlined in the docs](https://about.tiny.cloud/legal/attribution-requirements/#includingattributionwithtinymce).
