### ISSUE TITLE
Frameworks for TinyMCE

### ISSUE THREAD

**Issue by mordy-python** [tinymce/tinymce#6380]
Please add support for flask

**Comment by tiny-james** [comment]
TinyMCE will work fine with flask as it is currently. You just need to load the tinymce script and use a small piece of Javascript to load the editor as you would on a normal HTML page.

If you want to avoid Javascript I suggest you use the web-component integration, just load the script to one of your top level templates.
[https://github.com/tinymce/tinymce-webcomponent](https://github.com/tinymce/tinymce-webcomponent)

That way you can avoid Javascript for most simple cases and it'll just be like any other html tag.
