### ISSUE TITLE
Cursor doesn't go past inline boundary element

### ISSUE THREAD

**Issue by krichter722** [tinymce/tinymce#6387]
**What is the current behavior? Describe the bug**
After configuring

```
formats: {
    noteInfo: {block: 'div', classes: 'note', attributes: {"style": "background-color: green;"}, wrapper: true},
},
style_formats: [
    {
        title: 'Notes', items: [
            {title: 'Info', format: 'noteInfo'}
        ]
    },
],
inline_boundaries_selector: 'a[href],code,div.note',
```

for `tinymce.init` and formatting a paragraph as `Info` the style changes are applied correctly, however I'm not able to navigate before or after the formatted div.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
A demo of the setup can be found at https://fiddle.tiny.cloud/P1haab/1. Type a character and format the line as Notes -> Info. Then try to navigate before or after the green box with the keyboard arrows and to insert text. If you hold down the arrow key, you eventually get out of the box and you might be able to insert a character. This should work without holding down the keys forcefully though.

**What is the expected behavior?**
One should be able to move the cursor past and before the formatted div similar to tables and be able to insert text there.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
The issue occurs with Firefox 84.0 and Chrome 87.0.4280.88 on Ubuntu 20.10 with TinyMCE 5.6.2. I didn't test this before or with other versions.

**Comment by ashfordneil** [comment]
Hi @krichter722,
I think what's happening here is there's some confusion between inline and block level elements. Inline boundaries, what you're controlling with that `inline_boundaries_selector`, are only supported for inline elements. By default, divs are block level elements and aren't compatible with the setting.

Would you be able to create your `noteInfo` format using a span, or other inline element? That way you’d be able to use the inline boundaries. If not, we can forward your use-case to Product Management to consider as a feature for a future release of TinyMCE.

**Comment by krichter722** [comment]
@ashfordneil Thanks for the explanation the aspect of inline vs. block elements is very enlightening. I didn't see it because of the way one can navigate around tables. They might be created with a plugin and the cursor control is implemented specially for them. For my concrete use case I need a block element.

I'd appreciate if any sort of control for the cursor around block elements like it's already implemented for inline elements and the forwarding of such a feature to product management.

**Comment by ashfordneil** [comment]
I have added this to the queue of things for PMs to look at.
