### ISSUE TITLE
No icon for button 'insertlayer'

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#639]
Description of problem:
The icon of the button 'insertlayer' isn't visible with TinyMCE 4.0b2.
Also the label of the button doesn't seem to work correctly.
See attached screenshot.

Steps to reproduce:
1. plugins: layer
2. toolbar: insertlayer

Expected result:
Expected to see a button in the toolbar

Actual result:
No visible button just an empty space on the toolbar. When clicking this empty space or button it inserts this code: 

&ltg;div class="mceItemVisualAid mceItemLayer" style="position: absolute; left: 8px; top: 20px; width: 100px; height: 100px;">{#layer.content}&ltg;/div>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5850](http://archive.tinymce.com/develop/bugtracker_view.php?id=5850) posted by [McDonald](http://archive.tinymce.com/profile.php?name=McDonald)_
> 
> _**Tags:** [firefox 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
The layer plugin has been removed.
