### ISSUE TITLE
The fork of Sizzle lacks fixes from the upstream

### ISSUE THREAD

**Issue by thorn0** [tinymce/tinymce#6390]
**What is the current behavior? Describe the bug**

Memory leaks in Sizzle fixed by https://github.com/jquery/sizzle/pull/300 aren't fixed in TinyMCE.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

No reproduce steps, sorry. Just noticed a memory leak in my unit tests.

**What is the expected behavior?**

No leak.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.x, 5.x

**Comment by ashfordneil** [comment]
Hi @thorn0,

Thanks for reporting this. We've created a ticket internally, and we'll let you know when a PR is available.

**Comment by thorn0** [comment]
Is there any chance this gets backported to 4.x?

**Comment by lnewson** [comment]
I'm sorry to say that TinyMCE 4.x is no longer supported, so we won't be releasing any more fixes for TinyMCE 4. More information can be found here: https://www.tiny.cloud/blog/tinymce-4-support-window/
