### ISSUE TITLE
Autocomplete input in a dialog

### ISSUE THREAD

**Issue by Jako** [tinymce/tinymce#6393]
I like to extend the link plugin for a CMS. I like to add an autocomplete input fetching asynchronous data (CMS documents and link values) in the link dialog. After selecting the document I have to fill the the URL field with link value. Is this somehow possible?

**Comment by ashfordneil** [comment]
It looks like the setting you want is [link_list](https://www.tiny.cloud/docs/plugins/opensource/link/#link_list). Pay particular attention to the [asynchronous data](https://www.tiny.cloud/docs/plugins/opensource/link/#exampleofacustomasynchronouscallbackfunction) section of the docs, as I think that'll help you solve your particular use case.

By using different values for the `title` and `value` of the links you provide here, you can show users a friendly name of the document and then have the URL field be filled with the link value you need.

**Comment by Jako** [comment]
It seems that the listbox does not provide any paging or filtering for the list. Is this somehow possible?

Would it be possible to add something the single 'Single select input' demo on https://joshuajohnson.co.uk/Choices/ to the link list field?
