### ISSUE TITLE
add max indentation option

### ISSUE THREAD

**Issue by survtur** [tinymce/tinymce#6398]
I was looking for simple way to limit max indentation. I did it in a local copy of code, by adding simple `if` structure with harcdoded value. It's ugly but it works.
 
It would be nice to have parameter called `maxIndentation`. And the indent button should become grey if adding mode indent is not possible. 

```json
{
  "indentation": 30,
  "maxIndentation": 100,
  "indentationUnits": "px",
}
```

Also, I think we should use `indentationUnits` parameters to be sure that limit and current value of indentation use same units.

**Comment by metricjs** [comment]
Hi @survtur, this is an interesting idea. We're going to mark this as a feature request for settings to control indentation amount and max indentation and, as you highlighted, some way of specifying/handling the relevant units.
