### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TanyaRosana** [tinymce/tinymce#6399]
what  shall I do with the  zip abouut private.jwk.json,  private.pkcs1.pem
 I download  library.. I have to put into the pryect ?????? 
 I am from South America

**Comment by metricjs** [comment]
Hi, thanks for the report, however we believe your issue is with a premium product. For example, TinyDrive. If so, I'm afraid we can't assist via GitHub. Please contact our support team who may be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
