### ISSUE TITLE
merge table 

### ISSUE THREAD

**Issue by eiji-th** [tinymce/tinymce#6405]
Uncaught Error: The component must be in a context to send: triggerEvent
div title="合并单元格" role="menuitem" aria-haspopup="false" tabindex="-1" class="tox-menu-nav__js tox-collection__item tox-collection__item--active tox-collection__item--state-disabled" aria-disabled="true" is not in context

**Comment by lostkeys** [comment]
Hi @eiji-th. We need some more info to be able to help you out. [Can you please recreate the issue in a TinyMCE Fiddle](https://fiddle.tiny.cloud) so we can rule out it being an issue with your own code. Thanks

**Comment by lnewson** [comment]
It's also possible this may be a duplicate of https://github.com/tinymce/tinymce/issues/6397

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
