### ISSUE TITLE
Float Style not permitted on images

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#641]
Description of problem:

Steps to reproduce:
1.Added styles which specifically have float 
2.TinyMCE completely ignores float, while adding others
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5852](http://archive.tinymce.com/develop/bugtracker_view.php?id=5852) posted by [Meleo](http://archive.tinymce.com/profile.php?name=Meleo)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
