### ISSUE TITLE
Copying table loses table width

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#6423]
1. Create a 2x2 table in the TinyMce demo
2. **Select table with the mouse**
3. Copy
4. Paste
5. The resulting table will be shrunk in contrast to the original table. 
The resulting table does not include width=100% where the original table has it

**Comment by metricjs** [comment]
Hi @petko, thanks for reporting this. A fix for this is coming out in TinyMCE 5.7, and is currently available on the `5-dev` Cloud channel if you would like to test it.
