### ISSUE TITLE
"Paste as text" should perform an action, not toggle mode

### ISSUE THREAD

**Issue by dakur** [tinymce/tinymce#6432]
When you click `Paste as text`, nothing happens in editor. Instead, plain paste mode is enabled silently. I think that's very counterintuitive. If you look at desktop applications, all use it as action maker, not mode toggler – e.g. Word, Thunderbird, Writer... On mac, plain text is default and rich paste has [its shortcut](https://support.apple.com/en-us/HT209651).

I think it should copy this way – perform an action instead of toggling mode.

**Comment by metricjs** [comment]
Hi @dakur, changing this functionality would be a breaking change so we couldn't do that until at least TinyMCE 6.0. Triggering a paste from a menu item is also complicated due to browser clipboard restrictions. However, we will consider relabelling this button to clarify that it toggles the paste mode.

**Comment by dakur** [comment]
Yeah, now I see it behaves differently on Windows and macOS. On Windows, cut/copy/paste is actually useless as it does not work with old clipboard API and the new one is probably not well supported yet and has its gotchas. On macOS, the buttons work well.

What I did not know is also that this toggler works not only for buttons, but also for keyboard shortcuts. So if you toggle plain text on and `Ctrl`+`V` rich text, it inserts it as plain text. 👍

That brings new dimension to the question how to handle rich vs plain pasting. Maybe the title should be updated?

**Comment by metricjs** [comment]
Yes, our plan is to change the menu item's label/title. We are thinking `Toggle plain text paste` or `Toggle text paste mode` or similar. Unfortunately, the string needs to be short and describing this functionality in a few words is difficult.
