### ISSUE TITLE
How to programatically trigger Enter key in editor in v5?

### ISSUE THREAD

**Issue by dakur** [tinymce/tinymce#6433]
Hi,

I was able to programtically insert Enter in v4 like this:

```js
editor.fire('keydown', {keyCode: 13});
```

This *works* as well in v5, but Typescript throws:

![image](https://user-images.githubusercontent.com/9862581/104593091-75a46a00-566f-11eb-86d4-dd75505acf77.png)

What is the correct way to trigger Enter key in v5? Should I list all ~40 properties? Wouldn't `@ts-ignore` cause some errors on listeners of this event?

I've consulted docs, but it just refers to MDN which provides examples on listening of `keydown`, not dispatching. I don't know if it is rather issue of tinymce or event dispatching generally.

Thank you.

**Comment by jkuchar** [comment]
Just create DOM event and pass it to fire method. Are is there any shortcut? 

```ts
			const enterPressedEvent = new KeyboardEvent('keydown', {
				bubbles: true,
				cancelable: true,
				key: 'Enter',
				code: 'Enter',
				// keyCode: 13, // deprecated
				// charCode: // deprecated
				// which // deprecated
				location: 0, // https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/location
				ctrlKey: false,
				shiftKey: false,
				altKey: false,
				metaKey: false,
				repeat: false,
				isComposing: false,

			});
			editor.fire('keydown', enterPressedEvent);
```

**Comment by dakur** [comment]
Huh. Ok, let's make one. 🙂 Thanks.

```js
const createEnterKeydownEvent = () => new KeyboardEvent('keydown', {
	bubbles: true,
	cancelable: true,
	key: 'Enter',
	code: 'Enter',
	// keyCode: 13, // deprecated
	// charCode: // deprecated
	// which // deprecated
	location: 0, // https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/location
	ctrlKey: false,
	shiftKey: false,
	altKey: false,
	metaKey: false,
	repeat: false,
	isComposing: false,
});
```

**Comment by dakur** [comment]
The `new KeyboardEvent()` stopped to work suddenly, it throws an error now:

![image](https://user-images.githubusercontent.com/9862581/110089556-8da68900-7d96-11eb-91ef-baf415992ed1.png)

which is further described here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only

It is failing on [this line](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/api/util/EventDispatcher.ts#L147) as there is an attempt to re-set event's `type` property which is not possible. I don't know if something changed in browser-land as the code is there for a long time and it worked before.

I'm also confused what is the correct way anyway. `editor.fire('keydown', {keyCode: 13})` works but TS cries loud, otherwise `editor.fire('keydown', new KeyboardEvent(...))` is correct according to TS, but does not work. Documentation is not much helpful in here: https://www.tiny.cloud/docs/api/tinymce.util/tinymce.util.eventdispatcher/#fire

Any ideas?

**Comment by jkuchar** [comment]
Event must be broken in some way, as Naja [uses this way of event creation](https://github.com/jiripudil/Naja/blob/75a53367085ad0c014454bd8d15b621396d8fa72/tests/Naja.ext.AbortExtension.js#L12) without any troubles.

**Comment by jkuchar** [comment]
Where exactly code fails? Could you please narrow down the context?

**Comment by dakur** [comment]
Well yeah, but naja does not alter the event object itself as linked above (https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/api/util/EventDispatcher.ts#L147).

**Comment by dakur** [comment]
I've made a fiddle which demonstrates it: https://fiddle.tiny.cloud/H6haab

**Comment by dav-sap** [comment]
@dakur did u find any solution to this? `editor.fire('keydown', {keyCode: 13})` these kind of events dont work for me as well.

**Comment by dakur** [comment]
@dav-sap I've sticked with `editor.fire('keydown', {keyCode: 13})` and that works. In your case I suspect rather something different. Have you tried to `console.log('something')` before the `editor.fire()` to see if it actually make its way to there? Or try to debug with debugger in devtools.

**Comment by dav-sap** [comment]
I can see now that `{keyCode: 13}` but no other keyCode works. I try to add text like any char with a click event and its not working.
What Im trying to do in general is just open an AutoComplete list by the char it registers to.

**Comment by dakur** [comment]
🤷‍♂️ Sorry, I can not tell anything useful as I don't have any experience with autocompleter in tinymce nor anyone still answered the proper usage of key event handling in tinymce.

**Comment by dav-sap** [comment]
thanks anyway :) @dakur
