### ISSUE TITLE
Table related

### ISSUE THREAD

**Issue by srstechsolution** [tinymce/tinymce#6435]
**What is the current behavior? Describe the bug**

Merge and split functionality is not working. If cells generate `<br>` tag on enter key.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. When we create table with Some rows and columns then It creates but all cells contains `<br>` Tag.
2. After creating table, When we write write something in any cell and press "Enter" key in cell then Its create another `<br>` tag.
3. After that, Apply merge and split operation. Split will not work properly because of `<br>`. 

**What is the expected behavior?**
Merge and Split should be work.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE - 4.7.4 , Google Crome - 87.0.4280.141

**Comment by MichaelFromin** [comment]
As of 31-Dec-2020 TinyMCE 4.x is no longer a supported release of TinyMCE so we will no longer be providing fixes for the 4.x version.  We would recommend updating to the latest release (currently 5.6).  If the issue persists please update this ticket with the appropriate information to replicate the issue.

**Comment by srstechsolution** [comment]
I have also checked in Tinymce 5. this bug also exist in tinymce 5.

**Comment by lnewson** [comment]
@srstechsolution I tested this before closing and I was unable to reproduce it using TinyMCE 5.6.2 with the default settings. So could you please provide a [Fiddle](https://fiddle.tiny.cloud/) or video showing how to reproduce this?

**Comment by srstechsolution** [comment]
Hi @lnewson I have test on Fiddle. I have faced the same issue.

https://fiddle.tiny.cloud/

I am sending u HTML.

<table style="border-collapse: collapse; width: 100%;" border="1">
<tbody>
<tr>
<td style="width: 24.9249%;">
<p>Hello</p>
<p>Cell1</p>
cell2<br />
<p>Cell3</p>
<p>test</p>
</td>
<td style="width: 25.025%;">
<p>&nbsp;</p>
</td>
<td style="width: 24.9249%;">
<p>&nbsp;</p>
</td>
<td style="width: 23.6754%;">&nbsp;</td>
</tr>
<tr>
<td style="width: 24.9249%;">&nbsp;</td>
<td style="width: 25.025%;">&nbsp;</td>
<td style="width: 24.9249%;">&nbsp;</td>
<td style="width: 23.6754%;">&nbsp;</td>
</tr>
</tbody>
</table>

**Comment by srstechsolution** [comment]
Hi @lnewson, Have you got a chance to have a look this Bug ?

**Comment by ashfordneil** [comment]
Hi @srstechsolution

I’ve copied your HTML into this fiddle: https://fiddle.tiny.cloud/D2haab
But we still can’t reproduce it. Can you please add the settings you’re using to reproduce it, hit the save button, and then give us the updated URL to test with?

As an extra thing, if you’ve got time, it might be helpful for you to send us a screen recording of you reproducing the bug?
