### ISSUE TITLE
Freature request: Semitransparent grid overlay for content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#644]
Hi

I use Wordpress and Wordpress uses Tinymce for their content creation layout.

The content creation in Wordpress really needs a good overhaul. Making it easier for people to add content to a page or post. It is somewhat primitive in how it works today. I would like to see a more intuitive way of adding content.

So one of my thoughts is a semitransparent overlay so one can easily add content to a cell or cells (kinda like a table to where one can manipulate a cell or a row etc). By doing so it would make it easy to split the page/post into columns.

This way one could select multiple cells and for instance add a background color or image, curve the corners and then just add text or other content to these cells.

Go down a few rows and add some content to a row which could be made up of 4-5 cells depending on what is selected in the grid properties.

Having a semitransparent grid layout creation would make it a lot easier in adding content. 

Could you guys add this in?
Then it will hopefully also drip down to the Tinymce that WP uses as well.

Thanks..:)

Paal Joachim Romdahl
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5855](http://archive.tinymce.com/develop/bugtracker_view.php?id=5855) posted by [paaljoachim](http://archive.tinymce.com/profile.php?name=paaljoachim)_

> _**Tags:** [firefox msie safari chrome opera wordpress]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
