### ISSUE TITLE
Autocomplete jumbled

### ISSUE THREAD

**Issue by philiprbrenan** [tinymce/tinymce#6444]
The possibilities I am returning for autocomplete to display are getting jumbled up: 

![image](https://user-images.githubusercontent.com/7548378/104857386-36487880-5910-11eb-82a3-dd897fd0ffe3.png)

Please tell me how to unjumble them?

**Comment by lostkeys** [comment]
@philiprbrenan That doesn't look good. Can you try to replicate it in a [TinyMCE fiddle](https://fiddle.tiny.cloud) to try to isolate the problem to either TinyMCE or your specific implementation. Thanks.

**Comment by lostkeys** [comment]
It might be that you are returning a row of icon buttons rather than a menu. [Have a look at the columns property here](https://www.tiny.cloud/docs/ui-components/autocompleter/#configurationoptions) and see if that helps.

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
