### ISSUE TITLE
Approved Domains - You have a critical bug in the system!

### ISSUE THREAD

**Issue by hjvf07** [tinymce/tinymce#6449]
Approved Domains - You have a critical bug in the system!
http://prntscr.com/x8q9iq  - When adding my domain, the system does not save it.
In this regard, I get a message that the editor is not active for my domain.

**Comment by irooskovtiny** [comment]
Hi, Isaac here, Product Manager for DX and Cloud at Tiny. 
Can you please try adding the domain without the trailing slash " / "
We are currently working on a fix to this, however this should get you up and running in the meantime. 

Please let me know if the issue persists.

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
