### ISSUE TITLE
Reflected DOM XSS Vulnerability in the TinyMCE Insert/Edit Image window

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#645]
Description of problem:
A reflected DOM XSS vulnerability exists in the TinyMCE Insert/Edit Image window

Steps to reproduce:
1) Open the Insert/Edit Image window
2) Click on the "General" tab
3) Copy and paste the following into the "Image URL" field: ">&ltg;img src=x onerror=prompt(1);>
5) Press tab to change focus to another field (the Javascript prompt should fire at this time)

Expected result:
No popup / no javascript execution

Actual result:
A popup / javascript execution
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5856](http://archive.tinymce.com/develop/bugtracker_view.php?id=5856) posted by [grosser](http://archive.tinymce.com/profile.php?name=grosser)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
