### ISSUE TITLE
Tinymce 5.6.2 Append button labels to toolbar buttons

### ISSUE THREAD

**Issue by tushar721991** [tinymce/tinymce#6453]
I am using Tinymce 5.6.2, here in toolbar we have buttons for certain actions(cut, copy paste, bold etc.). My question is that I want to add button labels(as few people may not understand the button action from its icon). How can we do it.

In tinymce 4.x we had different classes for each button for ex mce-i-undo mce-i-redo mce-i-cut mce-i-copy etc and I was able to append button labels using these class names.

But now in tinymce 5.6.2 there is no such distinction between the buttons. Any Idea how I can manage to label these toolbar buttons?

I have also added following question on stackoverflow
https://stackoverflow.com/questions/65822209/tinymce-5-6-2-append-button-names-to-toolbar-buttons

**Comment by lostkeys** [comment]
You can create custom buttons using the APIs on which you can add text labels. [Here you can read more about custom toolbar buttons](https://www.tiny.cloud/docs/ui-components/toolbarbuttons/) and then [use commands to create the action](https://www.tiny.cloud/docs/advanced/editor-command-identifiers/).

**Comment by tushar721991** [comment]
I have added the custom undo redo buttons, how can I activate/deactivate them based on undo/redo available or not?

**Comment by lnewson** [comment]
An alternative option that might work for you is to add text to the default toolbar buttons, such as: https://fiddle.tiny.cloud/X2haab

I should note however that we don’t really recommend overriding default buttons, but that would be the simplest way to achieve this. Without that, you'd need to replicate the same logic in the default buttons. For Undo/Redo, that can be found here: https://github.com/tinymce/tinymce/blob/bb82d194a8163dbcdf6b5fd3ea03a55152b8835b/modules/tinymce/src/themes/silver/main/ts/ui/core/UndoRedo.ts#L11

**Comment by tushar721991** [comment]
Is there a way I can migrate modern theme from 4.x version into 5.6.2 version of tinymce?

**Comment by lostkeys** [comment]
Sorry, we don't have a TinyMCE 4.x skin for TinyMCE 5.x. You can create your own skins using our [skin tool](http://skin.tiny.cloud/t5/) or manually like [described here](https://www.tiny.cloud/docs/advanced/creating-a-skin/)

**Comment by tushar721991** [comment]
How can we add custom icons to default toolbar buttons like (copy, paste, undo, redo buttons).

**Comment by lostkeys** [comment]
@tushar721991 Check out [creating an icon pack](https://www.tiny.cloud/docs/advanced/creating-an-icon-pack/) in our docs.

**Comment by tushar721991** [comment]
Where can we get the svg's for tinymce 4.x icons we want to add a custom icon pack to tineymce5

**Comment by tushar721991** [comment]
Is it possible to add gradient to toolbar background in tinymce 5.6.2? we were able to do so in tinymce 4.1.10 but we dont see a way to do so in the skin tool provided by tinymce

**Comment by lostkeys** [comment]
@tushar721991 [Download the latest TinyMCE v4 release from Github](https://github.com/tinymce/tinymce/releases/tag/4.9.11) and look for a webfont file therein. From there you should be able to extract the icons you need.

There is an advanced mode in the skin tool where you can manipulate anyone of the hundreds of LESSCSS variables available in the oxide skin. There exists a `@toolbar-background` for which you can set a linear gradient.

**Comment by tushar721991** [comment]
I copied the following icon  from tineymce 4
<glyph unicode="&#xe00f;" glyph-name="undo" d="M761.862-64c113.726 206.032 132.888 520.306-313.862 509.824v-253.824l-384 384 384 384v-248.372c534.962 13.942 594.57-472.214 313.862-775.628z" />

and tried to add it into tinymce5 like following
editor.ui.registry.addIcon('undo', '<svg width="24" height="24"><path d="M6.4 8H12c3.7 0 6.2 2 6.8 5.1.6 2.7-.4 5.6-2.3 6.8a1 1 0 01-1-1.8c1.1-.6 1.8-2.7 1.4-4.6-.5-2.1-2.1-3.5-4.9-3.5H6.4l3.3 3.3a1 1 0 11-1.4 1.4l-5-5a1 1 0 010-1.4l5-5a1 1 0 011.4 1.4L6.4 8z" fill-rule="nonzero"/></svg>' );

but it does not display the icon, its showing blank icon, not sure why?

**Comment by lostkeys** [comment]
Have you tested that the SVG data works outside of TinyMCE to make sure it's a valid SVG file?
