### ISSUE TITLE
Cursor position jump to the start of the editor when dealing with content non-editable elements

### ISSUE THREAD

**Issue by krishna-babu** [tinymce/tinymce#6456]
**What is the current behavior? Describe the bug**
Cursor always jumps to the top of the editor when clicked left or right of the editor body (when padding applied)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Have left & right padding set for the editor
2. Place a container which is made up with non-editable elements
![image](https://user-images.githubusercontent.com/12712808/105456863-c0f3e500-5c3a-11eb-934c-f5a3e86306bc.png)
3. Place cursor inside the editable region of container
4. Click left or right of container
5. Notice that the scroll position is lost and editor is scrolled all the way to top.

**What is the expected behavior?**
Scroll position retained, cursor is placed next to container

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?
Observed in 4 & 5 major versions, even in latest using Chrome or Edge
![scroll issue](https://user-images.githubusercontent.com/12712808/105457105-20ea8b80-5c3b-11eb-82f0-c801eaa9ab81.gif)

**Comment by JamesToohey** [comment]
Hi @krishna-babu, thanks for the detailed bug report.

From your attached video, this does indeed look like a bug in TinyMCE, but I haven't been able to easily replicate this. Could you provide a replication case with https://fiddle.tiny.cloud/ so I can confirm what's actually happening?

**Comment by krishna-babu** [comment]
Hi James, Here is the fiddle [https://fiddle.tiny.cloud/H4haab/9](url), also GIF to repro. (Click in and out of editable section)

![scroll issue fiddle](https://user-images.githubusercontent.com/12712808/107589524-1167be00-6bbb-11eb-9b5a-bc946bbd5cde.gif)


If it helps, I noticed the problem on "mousedown" event with condition "if (!hasBetterMouseTarget(targetElm, fakeCaretInfo.node)) "

**Comment by krishna-babu** [comment]
Hi @JamesToohey, I just noticed that clicking on fiddle link in previous note is not working. Use this [link](https://fiddle.tiny.cloud/H4haab/9) and let me know if you need more details.

**Comment by ltrouton** [comment]
Hi, thanks for the additional information.

I can confirm that the editor incorrectly scrolls when clicking in and out of the editable section

 I've logged an internal task for us to investigate this issue and we'll update you when a fix is available.
