### ISSUE TITLE
Appending a new line before <picture> tag causes splitting <picture> tag in a few ones 

### ISSUE THREAD

**Issue by andrei-shabanski** [tinymce/tinymce#6457]
**What is the current behavior? Describe the bug**

If you wrap an image in \<picture\> tag like this

```html
<p>
    <picture>
        <source srcset="..." />
        <source srcset="..." />
        <img src="..." />
    </picture>
</p>
```

and try to append a new line before the image, \<picture\> tag will split up. Source Code shows something similar to:

```html
<p>
    <picture>
        <source srcset="..." />
        <source srcset="..." />
    </picture>
</p>
<p>
    <picture>
        <img src="..." />
    </picture>
</p>
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Full example https://fiddle.tiny.cloud/d3haab

1. Insert an image
2. Open Souce code and wrap the image in \<picture\> tag with a few \<source\> alternatives.
3. Place a cursor before the image.
4. Click Enter to move the image to the next line.

**What is the expected behavior?**

A new empty line will appear before an image. \<picture\> and its children tags will be kept.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Chrome 87, Firefox 84

TinyMCE 5.6.2

**Comment by JamesToohey** [comment]
Hi @andrei-shabanski, thank you for creating this issue and my apologies for the delay in responding. 

Currently TinyMCE does not support editing `picture` elements, so cases like this are not accounted for in either the core editor or the `image` plugin.

I've flagged this as a feature request to be looked at by our PM team.
