### ISSUE TITLE
Can't upload images with uppercase extensions using image plugin

### ISSUE THREAD

**Issue by lwd8cmd** [tinymce/tinymce#6459]
**Current behavior**
Can't upload files with uppercase extension (.JPG, .PNG) using image plugin. Image modal doesn't respond if file with uppecase extension is either dragged or selected in Image modal -> Upload tab.

Image plugin validates file type using extension (`images_file_types` setting was added #TINY-6224). By default only files ending with `jpeg,jpg,jpe,jfi,jif,jfif,png,gif,bmp,webp` (https://www.tiny.cloud/docs/configure/file-image-upload/#images_file_types) are allowed. Comparison is case-sensitive, presence of `jpg` in `images_file_types` does not white-list `.JPG` files.

**Steps to reproduce**
Try to upload file with .JPG extension on tinyMCE instance using image plugin with upload tab.
```
plugins: "image",
toolbar: "image",
images_upload_url: 'http://example.com/',
```

https://codepen.io/lwd8cmd/pen/wvzbGaj

**What is the expected behavior?**
Images with uppercase extensions (.JPG, ...) should be uploaded and displayed in TinyMCE edit area.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? **
Tested with TinyMCE 5.6.0.

**Possible solution**
Transform file extension to lowercase when retrieving image's MIME type in https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/paste/main/ts/core/Utils.ts#L150
```
+ ext = ext.toLowerCase();
```

**Comment by JamesToohey** [comment]
Hi @lwd8cmd, thank you for reporting this (and for the very highly detailed bug report!). I've logged this internally, we'll let you know when a fix is in place.
