### ISSUE TITLE
<p> font css not being picked up in editor body

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#646]
Description of problem:  In the body, the Heading styles work with my css, but the paragraph &ltg;p> style is using some type of default instead of my css font/font-size.  See attached screenprint.

Steps to reproduce:
I've put the correct p font into my local.css into the following css classes, and none of them is picking up the correct font.
1.  p and body
2.  .mceContentBody p
3.  .defaultSkin .mce_p span.mceText,
.defaultSkin .mceMenu span.mceText, .defaultSkin .mceMenu .mcePreview,
.defaultSkin .mceNoIcons a .mceText -- picked up from your ui.css file

Expected result:  Picking up the correct font.

Actual result:  Some type of default font.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5857](http://archive.tinymce.com/develop/bugtracker_view.php?id=5857) posted by [joyseeker](http://archive.tinymce.com/profile.php?name=joyseeker)_
> 
> _**Tags:** [firefox msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://example1.masterthewebdesign.com/content/bitten-purple-pansy-example-article_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
