### ISSUE TITLE
How to add modern theme from 4.1.10 version into 5.6.2 version

### ISSUE THREAD

**Issue by tushar721991** [tinymce/tinymce#6460]
We are migrating from 4.1.10 to 5.6.2 version
We want to use "modern" theme in 5.6.2(as we don't want to change our UI)
How can we achieve it?

**Comment by lostkeys** [comment]
Sorry, we don't have a TinyMCE 4.x skin for TinyMCE 5.x. You can create your own skins using our [skin tool](http://skin.tiny.cloud/t5/) or manually like [described here](https://www.tiny.cloud/docs/advanced/creating-a-skin/)

**Comment by tushar721991** [comment]
Is there any onresize callback for tineymce editor?
for me ".tox-sidebar-wrap " height is proper after resize but height of ".tox-edit-area" reduces after resize action.

**Comment by lostkeys** [comment]
Try the `resizeEditor` event [documented here](https://www.tiny.cloud/docs/advanced/events/#editorcoreevents)

**Comment by tushar721991** [comment]
How do we provide Id's to toolbar buttons(cut, copy , paste, Italic, bold etc) so that we can locate and click these buttons in automation?

**Comment by lostkeys** [comment]
@tushar721991 Sorry you can't provide ID's. The way to programatically trigger those actions is by [using commands](https://www.tiny.cloud/docs/advanced/editor-command-identifiers/).

**Comment by tushar721991** [comment]
when I do tinyMCE.activeEditor.getContent();
with following data
Test this
One
Two

I get following response 
"<p>Test this</p>
<p>One</p>
<p>Two</p>"

How can I get clean data?

**Comment by lostkeys** [comment]
@tushar721991 That looks very weird 🤨. I need you to try to replicate it in a [TinyMCE fiddle](https://fiddle.tiny.cloud) in order to isolate the problem to either TinyMCE or your implementation.

**Comment by tushar721991** [comment]
Please use following code 

`<script type="text/javascript">
tinymce.init({
    selector: "textarea",
	forced_root_block : '',
	force_br_newlines: false,
	force_p_newlines: true,
	convert_newlines_to_brs: false,

    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    setup: function (ed) {
      ed.on('undo',function (e) {
        console.log("undoData :: "+ed.getContent());
      });
      ed.on('redo',function (e) {
		console.log("redoData :: "+tinyMCE.activeEditor.getContent());
		
      });

	}



});

</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>`

**Comment by tushar721991** [comment]
How do we provide custom names to ok cancel buttons in editor.windowManager.confirm dialog?
