### ISSUE TITLE
Save button stays disabled when it is hidden in a collapsed toolbar

### ISSUE THREAD

**Issue by rutsch** [tinymce/tinymce#6469]
The toolbar collapses when there are more items then it can fit. If the Save button is in the collapsed panel, it doesn't lose it's disabled state when content changes are made. 

Issue also occurs on the TinyMCE website, in the full featured example:
https://www.tiny.cloud/docs/demo/full-featured/#fullfeaturednon-premiumplugins

**What is the expected behavior?**
I would expect the button to be active when I first make changes and then open the collapsed toolbar.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.6.2

**Comment by JamesToohey** [comment]
Hi @rutsch, thank you for reporting this bug. I have added it to our internal backlog, we will let you know when a fix is in place.

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.9.0, which was released at the end of August. If you are still have issues or find any other issues, please let us know.
