### ISSUE TITLE
URL in editor doesn't open on ctrl + click

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#647]
Description of problem:

Steps to reproduce:
1. Open the fiddle
2. Ctrl+click the link

Expected result:
Link opens in a new tab/window.

Actual result:
No link opens.

Try the same in Firefox to get the expected result.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5861](http://archive.tinymce.com/develop/bugtracker_view.php?id=5861) posted by [asm89](http://archive.tinymce.com/profile.php?name=asm89)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/tfdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
