### ISSUE TITLE
What is the license for language packages?

### ISSUE THREAD

**Issue by DemianWright** [tinymce/tinymce#6470]
TinyMCE itself is licensed under [LGPL-2.1](https://github.com/tinymce/tinymce/blob/develop/LICENSE.TXT) but what about the language packages: https://www.tiny.cloud/get-tiny/language-packages/

The page itself does not mention a license and neither does the Transifex page: https://www.transifex.com/tiny/tinymce/

Are the language packages also licensed under LGPL-2.1?

**Comment by lnewson** [comment]
Hi @DemianWright, I'm afraid I don't know the answer to this either, so I'm going to have to ask our product/legal team about this. Thank you for bring this to our attention and we'll let you know when we have more information.

**Comment by DemianWright** [comment]
The reason I am asking is because I am working on a translation add-on for software that uses TinyMCE and I would like to integrate the TinyMCE translation for my language into that add-on so the software displays TinyMCE in the correct language. I am planning on releasing my add-on under the MIT license which, as far as I understand, is compatible with LGPL-2.1.

**Comment by DemianWright** [comment]
@lnewson any updates on this question?

**Comment by jenhae** [comment]
@lnewson do you have any news from your product/legal team?

**Comment by DemianWright** [comment]
@lnewson Any progress on this?
