### ISSUE TITLE
tiny editor can't windows chrome browser paste image

### ISSUE THREAD

**Issue by 1161740194** [tinymce/tinymce#6471]
tiny editor can't windows chrome browser paste image ， but it can mac  chrome browser paste image , can you help me , thanks

**Comment by JamesToohey** [comment]
Hi @1161740194, thanks for reporting this. Is it possible for you to create a reproduction case in a [TinyMCE Fiddle](https://fiddle.tiny.cloud/), an open source repository, or using a sandbox platform such as Codepen or JSFiddle?

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
