### ISSUE TITLE
Default table with header 

### ISSUE THREAD

**Issue by bibos** [tinymce/tinymce#6472]
Hi everyone,

Is there a way to create tables with already a TH (or thead/td) by default?

Thanks,

Bruno

**Comment by lostkeys** [comment]
Hi @bibos! 

Yes, check out `insertTable` in the [Table API](https://www.tiny.cloud/docs/plugins/opensource/table/#api). Here is a [demo showing it in action](https://tinymce.github.io/tinymce-demos/tables/customizing-the-table-toolbar.html)

**Comment by bibos** [comment]
Perfect, thanks!

This part of code was sufficient for me:

`setup: (editor) => {
			
                editor.ui.registry.addMenuButton('inserttable', {
                    icon: 'table',
                    tooltip: 'Insert table',
                    fetch: function(callback) {
                        callback([
                            {
                                type: 'fancymenuitem',
                                fancytype: 'inserttable',
                                onAction: function(data) {
                                    // https://www.tiny.cloud/docs/plugins/table/#commands
                                    editor.execCommand('mceInsertTable', false, { rows: data.numRows, columns: data.numColumns, options: { headerRows: 1 } });
                                }
                            }
                        ]);
                    }
                });

                
            },`

Plus adding "inserttabble" in the toolbar of course.

**Comment by MrTango** [comment]
Sorry for posting on an old issue, but this is only working when i add an extra button, not for the existing entry in the menu.
The button does it right, but when i go over the tables menu where there is also 'inserttable' defined, it ignores this settings.
Any idea how to address that?

**Comment by soritaheng** [comment]
@bibos @MrTango Thank you for raising this issue. This is supported in [TinyMCE 8.4](https://www.tiny.cloud/docs/tinymce/latest/8.4.0-release-notes/#new-table_default_header_rows-and-table_default_header_cols-options-to-set-the-default-header-size-for-new-tables) via the `table_default_header_rows` and `table_default_header_cols` options, which configure the default number of header rows and columns for inserted tables.
