### ISSUE TITLE
Browse file on click?

### ISSUE THREAD

**Issue by bibos** [tinymce/tinymce#6475]
Ok I need help again...

I'm "just" trying to open the "browse/file" explorer on a click inside the editor...
Just trigger the same thing that we got with the "quickimage" button?

```
setup : function(editor) {
			editor.on("click", function() {
				
>> and what do I do here ???

			});
		},
```

Thanks for your help!

**Comment by JamesToohey** [comment]
Hi @bibos, in order to replicate the `quickimage` functionality on any click within TinyMCE, you would need to implement something very similar to this:

https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/quickbars/main/ts/insert/Picker.ts#L13

**Comment by bibos** [comment]
I thought it could be simpler than this...

**Comment by bibos** [comment]
But thanks ;)

**Comment by bibos** [comment]
I have another issue.
I can launch a new action, but actually it is launched twice!

Here is my the code :

`		setup : function(editor) {
			editor.on("click", function() {
				// action here
			});
		},`
