### ISSUE TITLE
Some types in tinymce.d.ts are not exported

### ISSUE THREAD

**Issue by apokryfos** [tinymce/tinymce#6478]
**Is your feature request related to a problem? Please describe.**

I was trying to write some code that creates a menu button in TypeScript. This code was in a module, and my intention was to create an array of type:

```
const menuArray: MenuButtonItemTypes[] = [ ... ];
```
This was the type that the success callback of addMenuButton.fetch is meant to accept.  However I was unable to do this because the type is not actually exported from the d.ts file

**Describe the solution you'd like**

Most (if not all) types in the declaration should be exported unless there's a good reason not to export something (or unless I'm missing something obvious in how to do this). 

**Describe alternatives you've considered**

Here's what I have tried:

```
fetch: (success) => {
    const menuArray: Parameters<typeof success>[0] = [ ... ];
   success(menuArray);
}
```

this does work but makes for very messy code in my opinion.

**Comment by lnewson** [comment]
Hi @apokryfos, you'll find those types under the `Ui` module/namespace. I will note you're right we are missing the `MenuButtonItemTypes` type specifically, but it is just an alias for `NestedMenuContents`. As such you could use that instead for now. Here's a basic example:
```
import { Ui } from 'tinymce';

const menyArray: Ui.Menu.NestedMenuItemContents[] = [ ... ];
```

**Comment by apokryfos** [comment]
Thanks for your response. I must have missed that export.
