### ISSUE TITLE
How to change the toolbar item text in runtime?

### ISSUE THREAD

**Issue by zozoh** [tinymce/tinymce#6479]
# Is your feature request related to a problem? Please describe.

> `TinyMCE 5.6.2`

In toolbar configuration: 

```js
tinymce.init({
  toolbar : "formatselect"
})
```

There will present a drop list in toolbar:

```
[Paragraph]
-----------------
  +---------------+
  | Paragraph   V |
  | Heading 1     |
  | Heading 2     |
  | Heading 3     |
  | Heading 4     |
  | Heading 5     |
  | Heading 6     |
  | Preformatted  |
  +---------------+
```

When I focus into a `<h1>`, it will change to

```
[Heading 1]   <-- It will auto upgrade
-----------------
  +---------------+
  | Paragraph     |
  | Heading 1   V |
  | Heading 2     |
  | Heading 3     |
  | Heading 4     |
  | Heading 5     |
  | Heading 6     |
  | Preformatted  |
  +---------------+
```

I try to make a customized toolbar button to simulate the behavior of `formatselect`.

```js
// Heading data
let headingItems = [{
  title: "Heading 1",
  selector: "h1",
  command: ['FormatBlock', false, 'h1']
}, {
  title: "Heading 2",
  selector: "h2",
  command: ['FormatBlock', false, 'h2']
}, {
  title: "Heading 3",
  selector: "h3",
  command: ['FormatBlock', false, 'h3']
}]
// Init the editor
tinymce.init({
  toolbar : "myselect",
  setup : (editor)=>{
    editor.ui.registry.addMenuButton("myselect", {
      text: "Paragraph",
      fetch(callback) {
        let items = []
        for(let hi of headingItems) {
          let {title, selector, command} = hi || {} 
          items.push({
            type : 'togglemenuitem',
            text : title,
            onAction() {
              editor.execCommand(...command)
            },
            onSetup(menuItem) {
              let el = editor.selection.getNode()
              let on = tinymce.DOM.is(el, selector)
              menuItem.setActive(on)
              return function(){}
            }
          })
        }
        callback(items)
      },
      onSetup(menuBtn) {
        const callback = function({element}={}) {
          // TODO: 
          // If current element is <h1>,
          // How should I update the menu button
          // change the display text to `Heading 1` ?
        }
        editor.on('NodeChange', callback);
        return function(){
          editor.off('NodeChange', callback);
        }
      }
    })
  }
})
```

I can handle the `NodeChangeEvent`, but in the event handler, I can not find 
the way to change the menu button text.

# Describe the solution you'd like

Extend the api for toolbar item,
expose a way to update any toolbar button aspect (icon/text) in runtime.

# Describe alternatives you've considered

I will use some special HTML tag (class and attribute) to define
a dynamic placeholder, and replace them by some resource outside of document
in runtime.

It can help me to provide friendly UE to my customer to create those `placeholder`
in editor. 

Thanks ^_^

**Comment by lnewson** [comment]
Hi @zozoh, as you've surmised this isn't currently possible, as those "bespoke" buttons are currently using an internal API that's not appropriate to publicly expose. We are already tracking the feature request to expose an API to allow similar behaviour to how those toolbar buttons work via https://github.com/tinymce/tinymce/issues/5966. As such, I'm going to close this as a duplicate.

**Comment by zozoh** [comment]
@lnewson  Thanks, I will going to watch the #5966
