### ISSUE TITLE
Link plugin data-mce-href and href not synchronized when no text is selected

### ISSUE THREAD

**Issue by MiQ42** [tinymce/tinymce#6480]
**What is the current behavior? Describe the bug**
If you select a word and then create a link, this element is created:
`<p><a data-mce-href="../../../test" **href="../../../test"**>linktext</a></p>`
If no word is selected and you enter the text to be displayed in the link editor, this will create this element:
`<p><a data-mce-href="../../../test" **href="/test"**>linktext</a></p>`
So if you want to open the second link now, you will have the wrong target.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
create link without prior selecting text on [https://www.tiny.cloud/docs/demo/full-featured/](https://www.tiny.cloud/docs/demo/full-featured/)

**What is the expected behavior?**
data-mce-href and href should be in sync

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5 in Chrome
tested today on [https://www.tiny.cloud/docs/demo/full-featured/](https://www.tiny.cloud/docs/demo/full-featured/)

**Comment by HAFRMO** [comment]
Hello.
Could you include a more detailed instruction for how to get to this state? I tried to replicate what you experienced with the steps most obvious to me that fit what you described, but I get the expected links, so I suspect I'm missing some crucial step of reproduction. Thank you.

**Comment by MiQ42** [comment]
https://user-images.githubusercontent.com/59486390/107393563-3a287e80-6afb-11eb-822b-1f084b438166.mov
