### ISSUE TITLE
Insert/Edit Link does not work when opened on top of a Modal/Popup

### ISSUE THREAD

**Issue by RakeshKB** [tinymce/tinymce#6481]
There is a Modal/Popup which is currently opened with TinyMCE editor in it. Inside the editor when the link icon is clicked, another popup opens up with 'Insert/Edit Link'. This popup is not focusable or editable
<img width="912" alt="Screenshot 2021-01-31 at 8 17 06 PM" src="https://user-images.githubusercontent.com/5022780/106387779-56dcfc00-6401-11eb-9f5c-ee379eb9343c.png">

**Comment by lnewson** [comment]
Hi @RakeshKB, from your screenshot I can see you're rendering TinyMCE in a dialog, however I can't tell what dialog framework it is. Anyways, this is most likely not an issue with TinyMCE and will be the dialog framework blocking focus shifting to other dialogs, so I'd suggest reaching out to whoever maintains that dialog framework. You'll need to find out how to prevent that dialog focus trap from happening.

We do document this case for [jQuery UI](https://www.tiny.cloud/docs/integrations/jquery/#tinymceinajqueryuidialog) and [Bootstrap](https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog), so you'll likely need to do something similar.

**Comment by RakeshKB** [comment]
Hi @lnewson , thanks for the response. Yes, TinyMCE is rendered on top of a modal/dialog. Sure, will try and prevent the modal/dialog focus trap from happening.
Many thanks.

**Comment by edugarcam** [comment]
This also happens to me but only in Firefox with small screens (or with a lot of zoom) when scroll appear.
