### ISSUE TITLE
Incorrect word count for Devanagari characters (Hindi)

### ISSUE THREAD

**Issue by preeteshjain** [tinymce/tinymce#6483]
**What is the current behavior? Describe the bug**
The wordcount plugin drastically underestimates the number of words in Devanagari characters (languages like Hindi). For example, this text is 33 words, but plugin shows only 6 words.

```
सभी मनुष्यों को गौरव और अधिकारों के मामले में जन्मजात स्वतन्त्रता और समानता प्राप्त है। उन्हें बुद्धि और अन्तरात्मा की देन प्राप्त है और परस्पर उन्हें भाईचारे के भाव से बर्ताव करना चाहिये।
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/K3haab (enter the text I mentioned above and check word count)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All versions are affected in any browser/OS.

**Comment by HAFRMO** [comment]
Hello.
This appears to be similar to a different issue which we have escalated ( [Wordcount](https://github.com/tinymce/tinymce/issues/6464) ) and will be looking at in the future.
We'll keep you updated to the result of that investigation, and see if that solves it.

**Comment by preeteshjain** [comment]
Yeah I've seen that issue.

I'd like to add a tip. There's a library called [Countable.js](/RadLikeWhoa/Countable) that works well with any language. Maybe you guys can look into that for a possible fix?

**Comment by tcavusoglu-stibodx** [comment]
Version 5 is counting even less words as version 4, it seems.
[bengali.txt](https://github.com/tinymce/tinymce/files/6787189/bengali.txt)
MS Word: 66, Tiny v4: 45, Tiny v5: 14

**Comment by preeteshjain** [comment]
This issue seems to not exist in the latest version. So closing this.
<img width="1428" alt="image" src="https://github.com/tinymce/tinymce/assets/6207830/da98b219-b321-4d2d-a94e-9f4ae9b84d7c">
