### ISSUE TITLE
The applied formatting is lost when the carriage leaves

### ISSUE THREAD

**Issue by lemm17** [tinymce/tinymce#6484]
How do I repeat it?
1. Enter the text with a space at the end;
2. Select the bold/italic/underlined/strikethrough style;
3. Click on the text on the left;
4. Click on the place where the formatting was applied.
Result: the selected formatting is lost.
Expected result: the selected formatting remains.

**Comment by JamesToohey** [comment]
Hi @lemm17, thank you for reaching out. TinyMCE’s behaviour you are describing is expected - if you apply formatting without typing anything and move the cursor away, that formatting will not persist. This is also how most other text editors behave. As such, we currently have no plans to support the requested functionality, so I’m closing this issue.
