### ISSUE TITLE
Stackoverflow when "meta" element in autocompleter has a cycle

### ISSUE THREAD

**Issue by MissChocoe** [tinymce/tinymce#6491]
**What is the current behavior? Describe the bug**
In autocompleteter fetch method, it is possible to add a "meta" field that is then return as the fourth parameter in onAction.
If this meta has a cycle, then you get a stackoverlflow when a "merge" operation is done to create the menu.
In my case the cycle is caused by a Child that knows its Parent.
To be sure this was the actual issue, I removed the parent field and everything worked. It also work on other kind of element without cycle that I use.

**What is the expected behavior?**
That meta field should probably be ignored by the merge to avoid such error. As a workaround, I just keep the id of thy element and fetch it back from my model but I would be simpler to just pass the element.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE v5.6
Don't know about previous version.

**Comment by vpyshnenko** [comment]
Hi @MissChocoe, thanks for reporting this. If possible, please provide a minimal code example of the problem via [fiddle.tiny.cloud](http://fiddle.tiny.cloud/) or similar.

**Comment by MissChocoe** [comment]
I tried to reproduce it in a simple example but it didn't work. 

I've encountered that problem with 2 different models structure. Tracing the infinite loop this is the only logic thing I could figure out. Removing the 'parent' relation did prevent the issue (this wans't my final solution; I just kept the reference and fetch the actual element back). 

The actual lines are cryptic since the code is compile but here's the piece of codes that are being called in loop:

```
// 1
var isType = function (type) {
      return function (value) { // here it stops and call it off!
        return typeOf(value) === type;
      };
    };
// 2
var deep = function (old, nu) {
      var bothObjects = isObject(old) && isObject(nu); // on isObject(nu)
      return bothObjects ? deepMerge(old, nu) : nu;
    };

// 3
var baseMerge = function (merger) {
      return function () {
        var objects = new Array(arguments.length);
        for (var i = 0; i < objects.length; i++) {
          objects[i] = arguments[i];
        }
        if (objects.length === 0) {
          throw new Error('Can\'t merge zero objects');
        }
        var ret = {};
        for (var j = 0; j < objects.length; j++) {
          var curObject = objects[j];
          for (var key in curObject) {
            if (hasOwnProperty$1.call(curObject, key)) { // Sometimes it stops here too
              ret[key] = merger(ret[key], curObject[key]); // This line
            }
          }
        }
        return ret;
      };
    };
// 4
    var deep = function (old, nu) {
      var bothObjects = isObject(old) && isObject(nu);
      return bothObjects ? deepMerge(old, nu) : nu; // deepMerge
    };

// Back to 3
// Back to 4
// ...
```

I'm not quite sure what it might be. Maybe there's an attribute name that is what is searched by the introspection.

Here's my attempt in case it helps:
http://fiddle.tiny.cloud/M4haab/2

**Comment by vpyshnenko** [comment]
Hi @MissChocoe, thank you for provided details. I've looked into autocompleter code for the way it merges menu items. Basically, this is done through the flattening of match results: https://github.com/tinymce/tinymce/blob/dd96c166307dfc724d226b8f60d33f3335ec4bd8/modules/tinymce/src/themes/silver/main/ts/Autocompleter.ts#L82 I haven't found any use of deepMerge in Autocompleter code. If it possible, please look upper in stack trace to figure out what code is responsible for the first call of deepMerge function.

**Comment by MissChocoe** [comment]
I worked around the infinite loop but there's definitely code that introspect the "meta" element that I give to the auto-completer. The element I put there now has proxy that logs warning when its properties are directy access and it logs a lot when the element is given to the auto completer.

I've created a new version of the Fiddle that has a basic proxy too so you can see attempt to call .field.

http://fiddle.tiny.cloud/M4haab/5

With an uncompiled version of tinyMCe it should be easier to debug!
