### ISSUE TITLE
How to make tinymce responsive

### ISSUE THREAD

**Issue by najararifahmad** [tinymce/tinymce#6500]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by JamesToohey** [comment]
Closing this issue due to lack of information. Please create a new issue with more information, using the template provided.
