### ISSUE TITLE
I can't find what I'm looking for: migration-from-4x.md

### ISSUE THREAD

**Issue by kerusan** [tinymce/tinymce#6501]
Before I used `editor.theme.resizeTo(w,h)` to be able to dynamically resize the editor. It doesn't seems to be there anymore.
I have done a framework for adding tinyMCE in Cappuccino and when cappuccino wants to layout its subviews this function was used.
What to do now?

**Comment by ltrouton** [comment]
Hi, thanks for posting.

To be able to dynamically resize the editor, the recommended approach is to set the editor configuration to use `width: '100%'` and `height: '100%'`. The editor target element can then be wrapped in a container e.g. `div` and the height and width can be set on the container. TinyMCE will dynamically resize to fit its container element.

Here is a Fiddle demonstrating this approach: https://fiddle.tiny.cloud/k5haab. 

We do have an internal ticket logged to look into documenting this. Let us know if this is helpful.

**Comment by kerusan** [comment]
Hi 

Thanx,  it solved my issue.

But please document this.

Kind regards
--kjell
