### ISSUE TITLE
Inline mode: selection toolbar doesn't show up when cursor is outside inline editor on dragend

### ISSUE THREAD

**Issue by jordanade** [tinymce/tinymce#6508]
I have a UI issue with TinyMCE's inline mode and the quickbars_selection_toolbar. My users are dragging to select text and ending the drag operation with the cursor positioned outside of the editor area. This causes the selection toolbar to not show up and my users are frustrated.

Can we change this behavior so that the quickbars_selection_toolbar still shows up on a selection event where the cursor is outside the editor upon dragend?

**Comment by ltrouton** [comment]
Hi, thanks for reporting this. I am going to mark this as a feature request so that our product managers can have a look at this.

**Comment by bshoemate** [comment]
Can we reopen this or at least post a work arround. We have the same issue.
