### ISSUE TITLE
The custom block div format is inserted inside itself

### ISSUE THREAD

**Issue by lemm17** [tinymce/tinymce#6512]
How do I repeat it?
1. Add a custom dv format to the configuration;
2. Write the text in this format;
3. ctrl + A, ctrl + C, put the cursor at the end of the text (right arrow);
4. ctrl + V several times.

Fixed result: the block is inserted inside itself.
Expected result: blocks are inserted parallel to each other, like h1, h2, pre and so on

DIV Style configuration
![image](https://user-images.githubusercontent.com/48180890/107214563-df742180-6a2b-11eb-9e17-8c5e1c5beb44.png)

The configuration as in the paragraph block does not help
![image](https://user-images.githubusercontent.com/48180890/107214646-003c7700-6a2c-11eb-8b49-1b96ff36b9ab.png)

**Comment by ltrouton** [comment]
Hi, thanks for posting. This behaviour is not something that can be controlled by the formatter and It also cannot be configured with editor settings. As a result, for the steps you have given, a new line will have to be entered before pasting the new `div`. 

If you have any other issues, let us know.
