### ISSUE TITLE
Numbered list is changed to bullets list while its coped

### ISSUE THREAD

**Issue by 1MrSmith** [tinymce/tinymce#6515]
I try to copy numbered and bullet list from Microsoft Word
1.	Test 1
2.	Test 2
3.	Test 3
4.	Test 4

1.)	Test 1
    a.)	33ewdfwfsfa
    b.)	34242342
    c.)	243
2.)	Test 2
3.)	Test 3
4.)	Test 4

1)	Test 1
2)	Test 2
3)	Test 3
4)	Test 4 

•	Test 1
•	Test 2
•	Test 3
•	Test 4

Numbered list copied correctly in Internet Explorer 11 but in Chrome and other browsers copied not correctly 

![image](https://user-images.githubusercontent.com/48734090/107342305-194b3380-6ad1-11eb-8505-a61cabb40ba4.png)

![image](https://user-images.githubusercontent.com/48734090/107342242-033d7300-6ad1-11eb-9d8a-b44b4bcad41e.png)

Expected result:
Numbered list is copied as numbered list

Actual result:
Numbered list is copied as bullet list

**Comment by ltrouton** [comment]
Hi, thanks for posting. I unable to reproduce the issue you have noted when pasting numbered and bullet lists from Microsoft Word into Chrome. 

It is worth noting that the `Paste` plugin used in the basic-example demo has limited support for pasting from Microsoft Word. Rather, the [Powerpaste](https://www.tiny.cloud/docs/plugins/premium/powerpaste/) plugin is the recommended plugin to use if pasting from Microsoft Word as it has greater support and receives continual updates for handling content from Word.

If you have any other issues let us know.

**Comment by laggage** [comment]
I found that the ordered list whose order ends with a close bracket `)` in the ms-word will be converted to unordered list after pasted to the tinymce

<img width="551" alt="image" src="https://user-images.githubusercontent.com/38829279/213346431-8255f4a1-467d-4768-b638-35ee50b326d7.png">

After paste:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/38829279/213346613-e09aeef1-152f-4e1f-9af8-d963447c5188.png">
