### ISSUE TITLE
Buttons in dialog not working.

### ISSUE THREAD

**Issue by swissniggi** [tinymce/tinymce#6516]
Setting:
tinymce 5.6.2, self-hosted
jquery 3.5.0

Furthermore:
Java 11
SpringFramework

The project is compiled by gradle

I am using tinymce in a project and I am having problems with dialogs. I use the following code to open a dialog with two buttons:

```javascript
/**
 * Creates the dialog window to edit the Title
 */
function createTitleChangeDialog() {
  var useSpecificLength = maxTitleLength > 0 && maxTitleLength < 60;
  editor.windowManager.open({
    title: "pvb.titleEditor.window_title",
    width: 680,
    height: 100,
    layout: "flex",
    direction: "column",
    align: useSpecificLength ? "start" : "stretch",
    padding: 15,
    spacing: 10,

    body: {
      type: "panel",
      items: [
        {
          type: "listbox",
          name: "titleSelector",
          label: "pvb.titleEditor.select.title",
          value: currentSelectionMode,
          onselect: function () {
            currentSelectionMode = this.value();
          },
          items: [
            {
              text: "pvb.titleEditor.select.all",
              value: "all",
              tooltip: "pvb.titleEditor.select.all.tooltip",
            },
            {
              text: "pvb.titleEditor.select.page",
              value: "page",
              tooltip: "pvb.titleEditor.select.page.tooltip",
              disabled: pageDisabled,
            },
            {
              text: "pvb.titleEditor.select.notfirst",
              value: "notfirst",
              tooltip: "pvb.titleEditor.select.notfirst.tooltip",
            },
          ],
        },
        {
          type: "textarea",
          label: "pvb.titleEditor.label.title",
          name: "title",
          multiline: false,
          value: originalTitle,
          size: useSpecificLength ? Math.max(maxTitleLength, 15) : undefined,
          maxLength: maxTitleLength > 0 ? maxTitleLength : undefined,
        },
      ],
    },
    buttons: [
      // A list of footer buttons
      {
        type: "submit",
        primary: true,
        text: "OK",
      },
      {
        type: "cancel",
        text: "Abbrechen",
      },
    ],

    onSubmit: function (e) {
      var newTitle = e.data.title;

      var validationError = titleEditor.validate(
        newTitle,
        minTitleLength,
        maxTitleLength
      );

      if (validationError) {
        editor.windowManager.alert({ text: validationError });
        return false;
      }

      updateTitles(newTitle);
    },

    onAction: function (dialogApi, details) {
      editor.windowManager.alert("Test" + details);
    },
  });
}

createTitleChangeDialog();

```

The dialog opens without problems but when I klick on either button nothing happens. However I don't get any error messages either. What could cause such a behavior? Closing the dialog by click on the "X"-Button works fine.

**Comment by lnewson** [comment]
Hi @swissniggi,

Without a working [fiddle](https://fiddle.tiny.cloud/) or working replication case I'm afraid we'll be limited in how we can help. If you could provide that, it'd help a lot to try and diagnose what's going on.

Having said that though, from your example, I'm assuming you're upgrading from TinyMCE 4 given the dialog data? Unfortunately, a lot changed in dialogs so a number of properties or callbacks in your data is invalid. I'd suggest reading through the [migration guide](https://www.tiny.cloud/docs/migration-from-4x/) and [dialog documentation](https://www.tiny.cloud/docs/ui-components/dialog/) to make sure everything is valid.

Some basic points where the dialog spec is invalid, are things like `width`, `height`, `layout`, `direction`, etc... as they are no longer valid and will not work (though that shouldn't cause failures). Another issue is that your `onSubmit` callback will be throwing an exception, as the argument passed is the dialog API and `data` is not a valid property. That will likely need to be something like:
```
onSubmit: function (dialogApi) {
  var data = dialogApi.getData();
  var newTitle = data.title;

  ...
}
```

**Comment by swissniggi** [comment]
Hi @lnewson,
you are right, I am upgrading from TinyMCE 4. I have now made sure that everything is valid but the problem remains. I even replaced my code with an example code from the documentation (https://www.tiny.cloud/docs/ui-components/dialog/#configurationoptions see "basic exapmle"). No success. This makes me believe that the problem lies somwhere completely else, however I have no idea where.

**Comment by lnewson** [comment]
Hi @swissniggi, firstly sorry for the delayed response. I'm afraid without a way to reproduce this or without any error messages, we can't provide much help here. As such, could you please provide a way to reproduce the issue either in fiddle, or with a simple Java application?

**Comment by swissniggi** [comment]
Sorry to say that, but Tinymce 5.x.x is the worst version of tinymce there is. Absolutely unuseable.

**Comment by lostkeys** [comment]
@swissniggi Sorry you feel that way, but there is not much we can do to help without a repeatable test case.
