### ISSUE TITLE
how to use icons of 4.1.10 version in 5.6.2 version of tinymce

### ISSUE THREAD

**Issue by pratham1107** [tinymce/tinymce#6520]
I want to use icons like cut,copy,paste,bold etc etc of 4.1.10 in 5.6.2 version in tinymce.
I tried copying svg file from 4.1.10 to 5.6.2 but it did not work.
Requesting you to please help regarding the same.
Also.
Is there anyway to resize the icons from 5.6.2?
Can we use old toolbar of version 4.1.10 in 5.6.2?

**Comment by lostkeys** [comment]
Hi @pratham1107. Sorry you can't use the TinyMCE v4 icons with v5. You can make your own icon pack by [extracting the v4 icons from the latest v4 release](https://github.com/tinymce/tinymce/releases/tag/4.9.11) and create a [custom icon pack as outlined here](https://www.tiny.cloud/docs/advanced/creating-an-icon-pack/)

And no we don't have a skin for v5 that looks like v4. You can replicate it yourself using our [skin tool](http://skin.tiny.cloud/t5/) or [manually as described here](https://www.tiny.cloud/docs/advanced/creating-a-skin/)

**Comment by pratham1107** [comment]
how can we create custom icon pack using tinymce 4.1.10 icons?

**Comment by lostkeys** [comment]
Begin by reading the documentation on how to create a icon pack to familiarize yourself with the process. Then you go download the latest v4 release and locate the v4 icons in there. You should look for a webfont file. Then you need to extract the icons from the webfont somehow and build the v5 icon pack as described in the docs.

**Comment by pratham1107** [comment]
How to tab between different buttons in toolbar in 5.6.2.
Currently, focus is shifting between first button of each toolbar group. We tried using tabfocus plugin as well but it did not work.
Could you please share any fiddle or any example?
Thanks!

**Comment by lostkeys** [comment]
@pratham1107 Use the arrow keys to navigate within a toolbar group. You can [read all about keyboard navigation here](https://www.tiny.cloud/docs/advanced/accessibility/).
