### ISSUE TITLE
Using TINYMCE with html PURIFIER in code some elements doesnt save like blocks (H1, H2, H3) instead it back them to <p> after saving, how to solve this ?!

### ISSUE THREAD

**Issue by SarajevoNo1** [tinymce/tinymce#6521]
Using TINYMCE with html PURIFIER in code some elements doesnt save like blocks (H1, H2, H3) instead it back them to <p> after saving, how to solve this ?!

THANKS!

**Comment by lnewson** [comment]
@SarajevoNo1 I'm afraid you'll need to log an issue with HTML purifier (or whatever library you're using) for that issue, as once the content leaves the editor we have no control over it and can't provide much assistance.
