### ISSUE TITLE
Wrong Polish translation for tables alignment

### ISSUE THREAD

**Issue by darth0s** [tinymce/tinymce#6523]
**What is the current behavior? Describe the bug**
When user adds Table and would like to format Cell alignment (Horizontal and Vertical) input labels are shifted (Horizontal and Vertical aligment labels swapped). This is clearly wrongly translated in pl.js as H = Horizontal = Poziom(y) so it should be _w poziomie_ .
![image](https://user-images.githubusercontent.com/17128331/107583550-5dd2ee00-6bfb-11eb-88d8-98e03916ccc5.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
In editor with selected Polish as default language:
1. add table
2. right click on table and select Cell > Cell Properties (Komórka > Właściwości Komórki)
3. Notice that Wyrównanie w Pionie has only _lewo_, _środek_ and _prawo_ options which are _left_, _center_ and _right_ accordingly.

![image](https://user-images.githubusercontent.com/17128331/107583234-ebfaa480-6bfa-11eb-8a9f-419e1323014d.png)

**What is the expected behavior?**
Expected behavior is that first alignment inputs labels are swapped.
 Current _Wyrównanie w pionie_ -> _Wyrównanie w poziomie_ 
 Current _Wyrównanie w poziomie_ -> _Wyrównanie w pionie_  

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Browser: Version 88.0.4324.150 (Official Build) (64-bit)
TinyMCE: Community Version 5.6.1 (2020-11-25)

**Comment by ltrouton** [comment]
Hi, thanks for reporting this. Our community translations are contributed to by open-source community members here. We have updated this (it may take some time to propagate), and if you'd ever like to contribute in the future you're more than welcome!
