### ISSUE TITLE
How to lift ContextMenu popup to <body>

### ISSUE THREAD

**Issue by TheoDt** [tinymce/tinymce#6524]
Hi,
I am using tinyMCE in React and its contained within a parent . Whenever I right-click on a table cell, the popup gets cut off by parent container.

![image](https://user-images.githubusercontent.com/34257451/107601065-8fca6b80-6c60-11eb-96e6-231e31892148.png)

I tried setting to class .tox.tox-silver-sink.tox-tinymce-aux{ z-index: 9999;}  but it doesn't work
Is there any built-in option to lift it to 'body'? or custom css override I can do to make the popup appear on top?

**Comment by ltrouton** [comment]
Hi @TheoDt, I believe you are in discussion with our professional support team on Zendesk so I will close this issue to keep the discussion in one location. If this is not the case, let us know and we will happily reopen this issue.
