### ISSUE TITLE
Why TinyMCE change type attribute to like 「type="mce-text/javascript"」 ?

### ISSUE THREAD

**Issue by toshi-toma** [tinymce/tinymce#6530]
**What is the current behavior? Describe the bug**

TinyMCE change type attribute to like 「type="mce-text/javascript"」, 「type="mce-no/type"」.

e.g.

For example, if I set the following content.

```js
<html>
	<head>
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>
<body>
</body>
</html>
```

tinymce has the following iframe

```html
<body
  id="tinymce"
  class="mce-content-body"
  data-id="mytextarea"
  contenteditable="true"
  spellcheck="false"
>
  <p><br /></p>
  <p>
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      type="mce-no/type"
      data-mce-src="https://code.jquery.com/jquery-3.5.1.min.js"
    ></script>
  </p>
  <h1>sample</h1>
</body>
```

This will prevent the JavaScript file from being loaded in the iframe.

Why TinyMCE change type attribute? 
Is there a workaround?

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

TBW

**What is the expected behavior?**

The JavaScript file will be loaded successfully.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I'm using TinyMCE v5 from CDN. (https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js)

**Comment by ltrouton** [comment]
Hi, thanks for posting. 

TinyMCE intentionally prevents the execution of scripts within the content for security purposes. This is not something that can be configured/changed. 

We would like to get some more information as to why you are trying to execute a script in the content?

**Comment by toshi-toma** [comment]
@ltrouton 

Thank you for answering!

### why you are trying to execute a script in the content?

I'm using [Full Page Plugin](https://www.tiny.cloud/docs-4x/plugins/fullpage/) that editing HTML Content.
My purpose is to edit web page with TinyMCE.

some web page run javascript file that control css class.

### Simple Example

```html
<html lang="en">
  <head>
    <style>
      .display-none {
        display: none;
      }
    </style>
    <script>
      function showContent() {
        document.getElementById("content").classList.remove("display-none");
      }
    </script>
  </head>
  <body>
    <div id="content" class="display-none">
      <p>some content</p>
    </div>
    <button onclick="showContent()">show content</button>
  </body>
</html>
```

By default set `display: none` with css. Then remove css class by javascript code.

### Problem

TinyMCE disabled script tag, so the content(<p>tag) cannot be seen and edit. 

Is there any workaround?

**Comment by KirillPenkin** [comment]
@itrouton
Thank you for for answering.
I have the same request too.
I want to have controls inside a text editor, so I need a way to receive some data from the textarea content.
```
const richTextContent = `

    <select id="dropdowninput" class="ice-cream" name="ice-cream" onchange="console.log('change dropdown')">
        <option value="">Select One …</option>
        <option value="chocolate">Chocolate</option>
        <option value="sardine">Sardine</option>
        <option value="vanilla">Vanilla</option>
    </select> <br/>

    <input id="textinput" type="text" onchange="console.log('change input')" onkeyup="(e) => {console.log(e)}" />

    <script type="text/javascript" language="JavaScript">

        document.getElementById('textinput').onkeyup = (e) => {
            const value = e.target.value;
            console.log(value);
            saveValueToLocalStorage('textinput', value);
        };

        document.getElementById('dropdowninput').onchange = (e) => {
            const value = e.target.value;
            console.log(e.target.value);
            saveValueToLocalStorage('dropdowninput', value);
        };

    </script>
`

export const TextBoxPageStory = () => {

    const [content, setContent ] = useState(richTextContent);

    const answerOptions = <>
        <RichTextEditor
            content={content}
            isPreview={false}
            language={SystemLanguage.EN}
            onChange={setContent}
            imageUploadHandler={doNothing}
        />

        <button onClick={() => console.log(content)}>Bbbb</button>
    </>

    return page(mapRadioButtonOptions(false, answerOptions), answerConfig, QuestionType.TEXT_BOX);
}
```

My scripts ```type``` gets changed to ```mce-text/javascript``` that prevents it from executing. 

Is there a way to assign event handlers to inner elements? I'm ok with them being executed in a safe environment. There's a local storage that can provide me with a way to exchange data.
