### ISSUE TITLE
Undo didn't works with iframe parent

### ISSUE THREAD

**Issue by rogerpec** [tinymce/tinymce#6533]
Editing a text inside a parent or parents of an iframe makes undo command not working like expected, instead the undo only refresh the iframe with forward/backward browser command.

[Here is a fiddle](https://jsfiddle.net/fwsbpgra/1/) showing the issue. Try to edit and undo, You will se an iframe refresh and not really undo.

I tested on Firefox and Edge last versions.

If this is not a bug please clarify me, thank you.

**Comment by ltrouton** [comment]
Hi, thanks for posting. 

When using your provided JSFiddle on Firefox and Edge, I am able to edit the text and undo the changes using Ctrl+Z or the toolbar button. The iframe (video) does refresh but this is expected.

I would like to get some clarification on what `forward/backward browser command` is referring to as I am little unsure. If you could provide any more details that may allow us to reproduce the issue, that would be helpful.

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
