### ISSUE TITLE
I can't find what I'm looking for: integrations/bootstrap.md

### ISSUE THREAD

**Issue by ucimo** [tinymce/tinymce#6536]
I need Vanila JS, React or Angular implementation for [event propagation ](https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog), basically anything that's not JQuery
![image](https://user-images.githubusercontent.com/38113520/107878853-97467a80-6ed5-11eb-8fa5-a126bb6b76b2.png)

**Comment by tiny-james** [comment]
Here's a direct conversion to Javascript. The caveat is that it doesn't support Internet Explorer (due to using closest). There is a pollyfill on MDN if you need that ( https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#polyfill )

```js
document.addEventListener('focusin', function(e) {
  if (e.target.closest(".tox-tinymce, .tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
    event.stopImmediatePropagation();
  }
});
```
