### ISSUE TITLE
Version5 preivew function problem

### ISSUE THREAD

**Issue by constantinedev** [tinymce/tinymce#6538]
I have try to use the dev version of V5<br>
eveny I can fix the other post and get problem<br>
but the last things is I don't know how to make the preview button in the following picture<br>
![image](https://user-images.githubusercontent.com/1324252/108071334-91e95b80-70a0-11eb-97f5-212db501d000.png)
<br>
Should it be in the plugin configure or I need to do somthing in my javascript of index.html?<br>
I can't found any issus in web support....<br>
or this is the bug with the new version browser?<br>
share me some idea...

**Comment by constantinedev** [comment]
I have to know what's happen on it
if you need to take the preview in HTML code style
don't use the [bbcode] plugin

**Comment by ltrouton** [comment]
Hi, thanks for reporting this! 

I can confirm that the Preview plugin dialog is incorrectly rendering BBCode content. This is a bug so I've logged an internal task for us to investigate and fix this issue.

**Comment by TheSpyder** [comment]
Sorry that we didn't get to this before TinyMCE 5 dropped out of support. The bbcode plugin was removed in TinyMCE 6.
