### ISSUE TITLE
Tags are overlapping (going inside another tags) in Tinymce

### ISSUE THREAD

**Issue by sunil20000** [tinymce/tinymce#6544]
**What is the current behavior? Describe the bug**
We have two custom buttons and when you click on them they add some HTML (for example span tags). So to reproduce the issue, first click on Button1 this will insert below HTML into editor window:

`<p><span class="container1"><span class="icon1">1</span>[[Test One]]</span></p>`

![TinymceIssue1](https://user-images.githubusercontent.com/79204196/108236568-0f7a9d80-716d-11eb-9aaa-7f4be8e2e4e0.PNG)

Now press Home button from keyboard or use arrow keys and go to left most of the editor window i.e. just before newly added content. See highlighted cursor position in below image:

![TinymceIssue2](https://user-images.githubusercontent.com/79204196/108236609-1bfef600-716d-11eb-9864-f5a8345946a1.PNG)

Now click on Button2 and that will insert another HTML. Technically it should insert new HTML before Button1 content because we have shifted our cursor to beginning of editor window and before Button1 content but when you see code of editor window, you find second set of HTML elements got inserted into Button1's HTML. See below image:

![TinymceIssue3](https://user-images.githubusercontent.com/79204196/108236663-291be500-716d-11eb-9f86-4f82119fb401.PNG)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/f5haab/3

**What is the expected behavior?**
If cursor position is out side of any element then newly added elements should be outside (not added inside other elements). In my example the final code should be (not much worried about <p> tags added by editor). As I moved my cursor to beginning of editor window and then clicked Button2 so first Button2's HTML and then Button1's HTML:
`<p><span class="container2"><span class="icon2">2</span> Test Two</span></p><p><span class="container1"><span class="icon1">1</span>[[Test One]]</span></p>` 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tinymce version: 5.6.2
Happening in all the browsers
Not sure it was working in old versions

**Comment by lostkeys** [comment]
Hi @sunil20000. This behavior is expected as many people uses spans for different types of formats such as colors, case, font-sizes etc and want to be able to write in that same format the beginning and end of a word.
However your example suggests you can use the [noneditable plugin](https://fiddle.tiny.cloud/55haab/1) to protect your tag. I've added an example in your fiddle: https://fiddle.tiny.cloud/55haab/1.

**Comment by sunil20000** [comment]
Thanks for the response. 

Actually in my case instead of <span> we are having custom element say <customtag> and it has nested <div> and <span> tags. See below code:

`  <customtag>`
`  <div class="ui mceNonEditable">`
`  <div class="heading">`
`  <div class="editor-icon"><br /></div>`
`  <h5>Custom Tags</h5>`
`  </div>`
`  <div class="mceEditable"></div>`
`  </div>`
`  </customtag >`

But when I add class to this custom tag then it is throwing JS error. 
`<customtag class = "mceNonEditable" >`

> tinymce.min.js:9 Uncaught TypeError: Cannot read property 'class' of undefined
    at B (tinymce.min.js:9)
    at tinymce.min.js:9
    at String.replace (<anonymous>)
    at n (tinymce.min.js:9)
    at Object.parse (tinymce.min.js:9)
    at Object.parse (tinymce.min.js:9)
    at ah (tinymce.min.js:9)
    at Object.insertContent (tinymce.min.js:9)
    at GN (tinymce.min.js:9)
    at mceInsertContent (tinymce.min.js:9)

**Comment by sunil20000** [comment]
If I directly add "class" to my <customtag> then getting JS error but when I try the same using "extended_valid_elements" then it's working fine. See below code:

`extended_valid_elements: 'customtag[class=mceNonEditable]',`

Is it the right way of doing this?

**Comment by lostkeys** [comment]
I cannot replicate the javascript error, but in general you are correct, you should let TinyMCE know about your custom tags. Primarily that is done throught the [custom_elements option](https://www.tiny.cloud/docs/configure/content-filtering/#custom_elements).

**Comment by sunil20000** [comment]
Thank you so much for all the help.
