### ISSUE TITLE
Mobile device: Caret is positioned to adjacent table cell, when adjacent table cell contains node with attribute contenteditable="false"

### ISSUE THREAD

**Issue by GouTong-dandan** [tinymce/tinymce#6547]
**What is the current behavior? Describe the bug**
Using a mobile device, create a table with multiple columns first. 
![tableConfig](https://user-images.githubusercontent.com/79293925/108457205-16a8c500-72ad-11eb-9450-fd4a14bb8d70.png)

Input some text, and followed by inputting a node: `<span contenteditable="false">anything</span>` by a customized plugin for tinymce. In addition, make the span to be the last part of this table cell's first line. Then continue to input some text, they will appear at the second line of this cell. 
![cellContent](https://user-images.githubusercontent.com/79293925/108457275-40fa8280-72ad-11eb-9f48-df113e119234.png)
![tableHtml](https://user-images.githubusercontent.com/79293925/108457284-4657cd00-72ad-11eb-94b4-34d5476bd81a.png)

Clicking on the upper half of the next table cell, the caret goes to the previous cell, and it is located after the not contenteditable span. However, caret locates correctly when the first table cell contains only editable content.

https://user-images.githubusercontent.com/79293925/108457322-62f40500-72ad-11eb-9124-3fadd46e28a6.mp4

**What is the expected behavior?**
Caret is supposed to be located at the cell where the user clicks.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version of tinymce: 5.3.2
Browser: Chrome
Replicable to android table/phone and ipad.

**Comment by lnewson** [comment]
Hi @GouTong-dandan, thanks for the detailed report! I can confirm this is a known issue and is actually reproducible on desktop devices as well. This issue is currently being tracked via #6350, so I'm going to close this as a duplicate so we're tracking it in a single location.
