### ISSUE TITLE
The table is inserted inside the format block

### ISSUE THREAD

**Issue by lemm17** [tinymce/tinymce#6548]
How do I repeat this?

Add a custom div format to the configuration;
Switch the text in this format;
Insert the table;
Fixed result: The table is inserted inside the format block.
Expected result: Just like with the standard format (paragraph) - the format block is replaced with a table

**Comment by ltrouton** [comment]
Hi, thanks for posting. 

Is it possible for you to create a reproduction case in a [TinyMCE Fiddle](https://fiddle.tiny.cloud/baaaab) or using a sandbox platform such as Codepen or JSFiddle? This will help us in reproducing and assessing the issue,

**Comment by JamesToohey** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
