### ISSUE TITLE
LineHeight ExecCommand event is trigger AFTER change event

### ISSUE THREAD

**Issue by nyroDev** [tinymce/tinymce#6549]
**When using the lineheight formatter, event orders is wrong**

In every execCommand I tested, the regular events chain is:

1. BeforeExecCommand
2. ExecCommand
3. change

When using the lineheight format the events chain is:

1. BeforeExecCommand
2. change
3. ExecCommand

Here is a very simple fiddle to illustrate it, you should open your console to see the event log
https://fiddle.tiny.cloud/75haab

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Current stable version, 5.x

I expect to see the lineheight in the same events chain than any other formats.

In my case, it currenly cause bug because I have to do some clean up on execCommand before the change do something else to trigger a local saving.

**Comment by ltrouton** [comment]
Hi, thanks for reporting this! 

I've logged an internal task for us to fix this issue and we'll update you when a fix is available.
