### ISSUE TITLE
Bootstrap 5 integration problem

### ISSUE THREAD

**Issue by musicman3** [tinymce/tinymce#6551]
Hello. I am unable to integrate tiny with bootstrap 5 in a modal window. No focus for Link insertion, picture insertion, etc.

Here's an example:
http://fiddle.tiny.cloud/gRgaab/187

**Comment by lnewson** [comment]
Hi @musicman3, this is a duplicate of https://github.com/tinymce/tinymce/issues/6391, so I'm going to close this.

As noted in that issue, Bootstrap 5 is still only in beta so our [docs](https://www.tiny.cloud/docs/integrations/bootstrap/) only detail how to handle the stable version of bootstrap. Anyways, see that issue for the solution to make it work on Bootstrap 5.

**Comment by musicman3** [comment]
Here is a solution without jquery for bootstrap 5:

`    document.addEventListener('focusin', function (e) {
        if (e.target.closest('.tox-tinymce-aux, .moxman-window, .tam-assetmanager-root') !== null) {
            e.stopImmediatePropagation();
        }
    });`

**Comment by lnewson** [comment]
Worth noting the above won't work on Internet Explorer, as `Element.closest` doesn't exist. You could polyfill that if needed, eg: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#polyfill

**Comment by musicman3** [comment]
IE support has ended. Therefore, it is no longer relevant. You can safely use my solution.
