### ISSUE TITLE
Activate or block: "save button"

### ISSUE THREAD

**Issue by engineer77721** [tinymce/tinymce#6555]
https://www.tiny.cloud/docs/plugins/opensource/save/

How to pass true or false from the save_onsavecallback function: function () {console.log ('Saved'); } in parameter: save_enablewhendirty: ****?

**Comment by JamesToohey** [comment]
Hi @engineer77721, thanks for your detailed request.

Currently, TinyMCE's concept of "saved" is when the data is persisted to the original target element. Our advice would be to block any form of editing while you are performing your save, either by:

- Using the [`setProgressState` API](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#setprogressstate)
- [Setting TinyMCE to `readonly` mode](https://www.tiny.cloud/docs/api/tinymce/tinymce.editormode/#set)
