### ISSUE TITLE
Fullscreen plugin uses wrong target element

### ISSUE THREAD

**Issue by mistic100** [tinymce/tinymce#6556]
**What is the current behavior? Describe the bug**

When using `fullscreen_native` the whole document body is put in fullscreen, not only the editor element.

I think this is because of this line
https://github.com/tinymce/tinymce/blob/eb618dd55824ba63c4d30982ebf58dc554f57c06/modules/tinymce/src/plugins/fullscreen/main/ts/core/NativeFullscreen.ts#L12
`editor.getElement()` (textarea) should be `editor.getContainer()` (application element)

---

The problem is clearly visible when using specific page layout with z-index (note: I cannot change this layout)
https://jsfiddle.net/mistic100/s9pfr15d/5/
The grey header should not be visible in fullscreen.

When manually triggering the fullscreen from the console by targeting only the "application" container it works as expected.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All browsers. TinyMCE 5.6

**Comment by mistic100** [comment]
Current workaround:

```ts
function requestFullscreen(elt) {
    // @ts-ignore
    (elt.requestFullscreen || elt.mozRequestFullScreen || elt.webkitRequestFullscreen || elt.msRequestFullscreen).call(elt);
}

function exitFullscreen() {
    // @ts-ignore
    (document.exitFullscreen || document.mozCancelFullScreen || document.webkitExitFullscreen || document.msExitFullscreen).call(document);
}

    fullscreenEnabled$ = new BehaviorSubject<boolean>(false);

    editorConfig = {
        toolbar          : 'custFullscreen',

        setup: (editor) => {
            editor.ui.registry.addButton('custFullscreen', {
                icon    : 'fullscreen',
                onAction: () => {
                    const editorElement = editor.getContainer();
                    if (this.fullscreenEnabled$.value) {
                        exitFullscreen();
                        this.fullscreenEnabled$.next(true);
                    } else {
                        requestFullscreen(editorElement);
                        this.fullscreenEnabled$.next(false);
                    }
                },
                onSetup: (button) => {
                    this.fullscreenEnabled$
                        .subscribe(enabled => button.setActive(enabled));
                }
            });
        }
    };
```

**Comment by ashfordneil** [comment]
Hi @mistic100,
Thanks for all the details in this report, it's made it a lot easier to track down for us!

> When using fullscreen_native the whole document body is put in fullscreen, not only the editor element.

So this behaviour is actually intended for the full-screen plugin. While we could full-screen the editor element itself, that would prevent us from letting certain floating elements (like dialogs) be usable in full-screen mode, as they are not children of the editor container.

The solution to making the full-screen editor appear above that grey bar is going to be raising its z-index, but there are ways you can do that without changing the layout of your site. Essentially, what you're going to want to do is raise the z-index of `#page` _when the editor is in full-screen mode_. I'd recommend going about that in one of two ways:

1. Using JavaScript, listen for the `FullscreenStateChanged` event and alter the z-index of the element in response to that element. For information on the `FullscreenStateChanged` event see [Events Available for TinyMCE](https://www.tiny.cloud/docs/advanced/events/#fullscreenevents).
2. Using css, add a rule that raises the z-index when the `#page` element is inside an element with the `.tox-fullscreen` class. TinyMCE will ensure that this class is applied to the parent document body when in full-screen mode, and that is is removed when full-screen mode is exited. Adding the following CSS to your fiddle fixed the issue on our end:

```css
.tox-fullscreen #page {
    z-index: 40;
}
```

**Comment by mistic100** [comment]
Why is is intended ? What is the point ?
When you put a video in fullscreen on YouTube not the whole screen is put in fullscreen only the video player.

Actually it is the same for **any** website/solution I ever encounter, tinymce is the only I ever encountered why this buggy behaviour.

I cannot use your solution, it is to much intrusive so I will keep my button.

Shame that your consider a bug is intended, because yes, considering what "getFullscreenRoot" does (fallback to body because the provided element is incorrect) is is clearly a bug.

**Comment by mistic100** [comment]
>  that would prevent us from letting certain floating elements (like dialogs) be usable in full-screen mode, as they are not children of the editor container.

Perhaps you should not bleed out of the container that was assigned to the editor and put the modals and dropdown at the bottom of the `role=application` element. In order to not break the interagtion in large applications.
