### ISSUE TITLE
add fixed_toolbar_container_element setting which accepts an HTMLElement instead of a CSS3 selector string

### ISSUE THREAD

**Issue by pvrobays** [tinymce/tinymce#6559]
**Is your feature request related to a problem? Please describe.**
For an inline editor, you can currently only pass the `fixed_toolbar_container` CSS3 selector string to fix the toolbar to a certain div. However, when working with React Portals on different window (actually different body) instances, it might occur that the CSS3 selector fails to find the element on its current body.
Also, lately it's more common to pass HTMLElements instances around instead of selector strings.

**Describe the solution you'd like**
add the setting `fixed_toolbar_container_element` which accepts an HTMLElement instance in which the toolbar should be rendered. This should have a higher priority than `fixed_toolbar_container`.

**Describe alternatives you've considered**
/

**Comment by metricjs** [comment]
Hi @pvrobays, thanks for raising this. The team discussed this feature request the other day and we have some concerns about the ramifications of doing this in your environment, but we also wanted to clarify our understanding of how your app or website works. 

TinyMCE doesn't support rendering the UI in a different window to where TinyMCE is loaded. So our main concern is that by putting the toolbar container in a different body (of a different window?) to the rest of the editor, that a lot of TinyMCE's functionality that references the body or window, or rely on things being in the same body or window, would break. For example, the positioning of various TinyMCE UI elements.

To better understand your use case, and whether our concerns are valid, we wondered:

1. What DOM structure are you using in your use case exactly? E.g. what elements are you wanting to put the toolbar container and the rest of the editor in and how do they relate? We assumed that you might be working with iframes or even ShadowDOM?
2. Assuming you have tested your suggestion in your app, did you notice any issues with TinyMCE functionality or UI?

**Comment by pvrobays** [comment]
Hi @metricjs, thanks for considering this feature.

Let me start by ignoring our current use case, as this is a special one. In typed coding languages, I find it more useful to pass around references to DOM objects instead of string (css)selectors. That way you won't have typos in the selector which make your app crash at runtime. So I do believe that, apart from my use case, this setting has its value within TinyMCE.

OK, to answer your first question. Our use case is a multi-monitor web application via electron. This means we'll have electron open a window for each of your monitors of your multi-monitor setup. Each window registers its 'js window' instance to one main 'js window' instance. This way the 'main' window has a references to all other window instances.
The main window will render the UI of all the registered windows. FYI: this is done via React portals.

So what does that mean for TinyMCE?
If we render an inline editor on the main window instance, there's no problem. The TinyMCE instance of the main window is used to create it, the fixed_toolbar_container ID is found as this lives on the current window.
If we render an inline editor on another window which isn't the main window, it's another story. This time again the main window will create an inline editor for the other window, so the TinyMCE instance of the main window is used to create it, but the fixed_toolbar_container ID cannot find the passed ID as that ID lives in the DOM of the other window.

To answer your 2nd question: No, we haven't had any major issues with TinyMCE functionality. I guess that is because all the editors are still being created on the same window instance. They're just rendered on another one.
The only major issue we had so far was with deferred loading of TinyMCE. If this load was triggered on a window other than the main window, TinyMCE would attach itself to that (wrong) window. The main window would see that TinyMCE was loaded, but isn't able to find a window.TinyMCE instance.

If you need more information, or I wasn't clear about something, please don't hesitate to ask.
