### ISSUE TITLE
How to remove the help plugin keyboard shortcut?

### ISSUE THREAD

**Issue by ghazpar** [tinymce/tinymce#6561]
**What is the current behavior? Describe the bug**
The `editor.shortcuts.remove` methods returns false when I try to remove the 'alt+0' or 'alt-48' key combinations. Why can't I remove the shortcut for the help plugin?

I need to disable this shortcut, because it conflicts with the ] key on a French-Canadian Mac keyboard layout.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://fiddle.tiny.cloud/a6haab

**What is the expected behavior?**
That the keyboard shortcut for the help plugin be removed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest Version 5 on all browsers.

**Comment by JamesToohey** [comment]
Hi @ghazpar, it looks like you're trying to remove the shortcuts before the TinyMCE has initialized. 

You can use [`init_instance_callback`](https://www.tiny.cloud/docs/configure/integration-and-setup/#init_instance_callback) to perform operations after TinyMCE has initialized.

You could also listen to the `init` event inside your `setup` function, similar to [this example](https://www.tiny.cloud/docs/advanced/events/#handlingeditorevents).

I've updated your fiddle: https://fiddle.tiny.cloud/a6haab/2

**Comment by MissChocoe** [comment]
I tried to remove the bold/underline/italic shortcuts but it doesn't seem to work.

**Comment by lnewson** [comment]
@MissChocoe in the above, that's still working as it's falling back to native browser contenteditable behaviour after you've disabled TinyMCE handling the keyboard events. So to prevent that happening, you need to block the keyboard events or similar instead. The easiest way to do that is probably going to be to add a new shortcut that does nothing. Here's an example: https://fiddle.tiny.cloud/a6haab/4

**Comment by mrelarsen** [comment]
I have trouble removing or replacing the shortcut for the headlines. Any ideas why?
https://fiddle.tiny.cloud/a6haab/9

**Comment by TheSpyder** [comment]
The help dialog list is not dynamic, sorry.
https://github.com/tinymce/tinymce/blob/236891ffcdf2fd1b698d020e67c31838fb110019/modules/tinymce/src/plugins/help/main/ts/data/KeyboardShortcuts.ts#L3-L29
