### ISSUE TITLE
I can't find what I'm looking for: configure/localization.md

### ISSUE THREAD

**Issue by siavashvj** [tinymce/tinymce#6566]
Trying to get this on a Weblow page, which works great. But since Webflow doesnt allow hosting of .js files I cannot upload language pack.

Tried using  

`language_url : 'external-https-adress-for-hosted-languag-pack-file'
`
which does not work. Stops the plugin to load all together. 

Any clues or workarounds?

**Comment by ashfordneil** [comment]
Hi, I see you're in discussion with our professional support team so I will close this issue to keep the discussion in one location.
