### ISSUE TITLE
Quick Insert Toolbar & forced_root_block

### ISSUE THREAD

**Issue by bibos** [tinymce/tinymce#6574]
Hi everybody,

It seems that the **Quick Insert Toolbar** is not working correctly when using **force_br_newlines**...

You can see that here: https://codepen.io/bibos/pen/VwmxrVm 
(comment the "force_br" section and it will work again)

Regards,

Bruno

**Comment by lnewson** [comment]
Hi @bibos,

This is largely expected as the `force_br_newlines` and `force_p_newlines` has been deprecated for years now and is no longer supported (you'll note they aren't in the documentation). `forced_root_block` is the setting that largely replaces it.

That being said I can see you do have `forced_root_block` configured and it's not showing on new lines so it is still a bug. I'll log an internal issue and we'll update you when a fix is available.

**Comment by bibos** [comment]
Oh ok...
Thanks!
