### ISSUE TITLE
problem with failure callback

### ISSUE THREAD

**Issue by olyakolesnichenko** [tinymce/tinymce#6579]
I am trying to implement file upload using `images_upload_handler`. I faced an issue with handling errors when upload fails. I can't customize a title in the error dialog despite calling `failure("my_string_message")`. Calling failure("my_string_message")` shows a dialog with `[object Object]` in the title.

**What is the current behavior?**
Dialog with title `[object Object]`appears when file upload fails.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
https://codepen.io/olyakolesnichenko/pen/QWGrRgE

**What is the expected behavior?**
A title from failure callback is expected

**Comment by ashfordneil** [comment]
Thanks @olyakolesnichenko,

We've reproduced this on our end, and noted that it's a regression caused by some of the 5.7.0 work. We'll try to fix it for our next release (5.7.1). In the mean time, you can avoid this bug by downgrading to 5.6.2 until the fix is available.

**Comment by lnewson** [comment]
TinyMCE 5.7.1 was released to the community Wednesday last week (17th of March). If you're still having issues after upgrading please let us know.

Note: If you're using Tiny Cloud, it's scheduled to be updated later this week, pending enterprise QA checks.
