### ISSUE TITLE
【Link plugin & Vue Router】When adding a link, the current URL is deleted, which makes it impossible to distinguish it from the anchor when clicking jump

### ISSUE THREAD

**Issue by sws797** [tinymce/tinymce#6586]
Editing the link
![Editing the link](https://file.learnerhub.net/ck-images-1614857545106/image.png)

After saving
![Editing the link](https://file.learnerhub.net/ck-images-1614857213765/image.png)

When clicking
![click error](https://file.learnerhub.net/ck-images-1614857433723/image.png)

Link plugin.js
![code](https://file.learnerhub.net/ck-images-1614857630915/image.png)

How to save the full link when I save it instead of clipping it

Thank you

**Comment by lostkeys** [comment]
Hi @sws797! Have a look at [this page in our documentation about URL conversion](https://www.tiny.cloud/docs/demo/url-conversion/#absoluteurlsonlinksandimages) and see if that solves your problem.

**Comment by sws797** [comment]
@lostkeys Thank you! That works！
