### ISSUE TITLE
Editor scroll with inline mode and limited height

### ISSUE THREAD

**Issue by ElizavetaKoroleva** [tinymce/tinymce#6587]
If editor is in inline mode and has limited height than container doesn't scroll to cursor position after content paste.

Steps to reproduce:
1. Set inline editing mode
2. Set the height of the editor
3. Copy and paste text

Expected behavior: container scrolls to cursor position
https://user-images.githubusercontent.com/43936760/109975367-a1f17400-7d0b-11eb-9880-e9e6650881a9.mp4

**Comment by lostkeys** [comment]
Hi @ElizavetaKoroleva! Unfortunately I do not fully understand your report. Can you produce a [TinyMCE fiddle](https://fiddle.tiny.cloud) for us for which we can replicate the issue ourselves.

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
