### ISSUE TITLE
Allowing Angular template tag within elements

### ISSUE THREAD

**Issue by BenRacicot** [tinymce/tinymce#6590]
I have read through the docs and several popular Stackoverflow pages on allowing custom attributes within HTML elements. However, I cannot get TinyMCE to stop stripping out Angular template tags. 

Here is my Stackoverflow question: [stackoverflow.com/q/66265964/1440240](https://stackoverflow.com/q/66265964/1440240)

I need: `<aside #tagname></aside>`

Adding this to the config still strips out any `#....`
`extended_valid_elements : 'aside[#]'`

Adding all reformats it to an attribute with `=""`.
`extended_valid_elements : 'aside[*]'`

Either this is not possible or I am doing it incorrectly and cannot understand how to make template tags allowed.
(thanks for your help)

**What is the expected behavior?**
Adding a template tag to HTML within the editor outputs the HTML exactly as it was saved.

**Which versions of TinyMCE/TinyMCE-Angular: 4.2.1

**Comment by lostkeys** [comment]
Hi @BenRacicot! TinyMCE is at it's core a HTML editor, and such is built to only output vanilla HTML. We had a similar question not long ago about injecting ruby control markup (see #6221). You always have the option to process the HTML outside of the editor. For example, you can use `<aside reference="foobar"></aside>` in TinyMCE and have some regex convert turn it into `<aside #foobar></aside>` for use in angular. 

I'll flag this as a feature request. Anyone seeing this and want us to build a feature to insert component placeholders and template control markup, please give a thumbs up here so we can gauge appetite for such a feature.

**Comment by BenRacicot** [comment]
Great idea @lostkeys and thanks for replying.

Yes, this should be a feature request because without this allowance it does kind of void any template/DOM manipulation via the angular framework's main tools such as `ViewChild`. Engineers wont know this is not available until they're up against it.

The regex concept may be work a work around. Thanks for that.
