### ISSUE TITLE
Untranslated strings in the link plugin interface

### ISSUE THREAD

**Issue by DemianWright** [tinymce/tinymce#6592]
**What is the current behavior? Describe the bug**
The following strings are translated in the Finnish language package but they do not appear in Finnish in the interface:
1. "Link..."
1. "Open link in..."

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Select text, right click, context menu has "Link...". Click the context menu item, the dialog has "Open link in...".

**What is the expected behavior?**
The English UI strings should be translated according to the installed language package.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE: 5.6.2
Browser: Chrome 88.0

**Comment by lnewson** [comment]
Thanks for also reporting this issue. This appears to be the same cause as #6593, as these are passed for translation and are just missing in Transifex. As such I'm going to also label this as needing the translations added in Transifex.
