### ISSUE TITLE
Untranslated strings in the table plugin interface

### ISSUE THREAD

**Issue by DemianWright** [tinymce/tinymce#6593]
**What is the current behavior? Describe the bug**
The following string is translated in the Finnish language package but they do not appear in Finnish in the interface:
1. "Select..."

Additionally none of the table border style names are translated.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Create a table, go to table properties, select the **Advanced** tab. It is the first option in the **Border style** drop-down menu. This is the same menu that contains the untranslated border styles.

**What is the expected behavior?**
The English UI strings should be translated according to the installed language package.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE: 5.6.2
Browser: Chrome 88.0

**Comment by lnewson** [comment]
Hi @DemianWright, thanks for the report. Looking at the code, this is passed for translation so it appears we're just missing the translations in [Transifex](https://www.transifex.com/tiny/tinymce/). You can see this is working with our enterprise translations via Tiny Cloud: https://fiddle.tiny.cloud/W6haab

As such, I'm going to label this as needing updating in Transifex for the community translations.
