### ISSUE TITLE
Cursor jumps by one character when erasing between lines

### ISSUE THREAD

**Issue by thecodrr** [tinymce/tinymce#6595]
**What is the current behavior? Describe the bug**
If there are two lines and you try to backspace so it all fits on one line, it jumps to the next character (See video below).

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://fiddle.tiny.cloud/L6haab

**What is the expected behavior?**
The cursor should not jump.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE Version: 5.7.0
OS: Android
Browser: Brave Browser Android

https://user-images.githubusercontent.com/7473959/110202743-8497e380-7e8c-11eb-8ac6-0f7d075a559f.mp4

**Comment by thecodrr** [comment]
I am able to reproduce this in every browser on Android including Google Chrome, Microsoft Edge, and even Android WebView. Please follow the reproduction steps I gave in the issue (or follow the video):

1. Open the tinymce editor
2. Write 2 lines
3. Tap in the very beginning of the second line
4. Press backspace (the second line should move after the first)
5. Notice how the cursor is one character ahead.

**Comment by lnewson** [comment]
That was what was tried, however we were unable to reproduce the issue. Either way, I'm going to reopen this so we can investigate further.

**Comment by ammarahm-ed** [comment]
+1

**Comment by Botinok666** [comment]
This is still not fixed. Easily reproducible on Android WebView (or Chrome) with exactly the same steps as were mentioned by @thecodrr
