### ISSUE TITLE
Code plugin stripping anchor tags when they wrap other tags

### ISSUE THREAD

**Issue by kevin-v96** [tinymce/tinymce#6596]
**What is the current behavior? Describe the bug**
The code plugin is not handling links that wrap div/table tags. e.g.:

`<a><div>some text</div></a>`
this won't work as when you save the `<a>` tags will be removed

but something like
`<a>some text</a>`
or
`<a><img /></a>`
works

**Steps to reproduce**
Add code to the code plugin that has links with `<a>` tags wrapping either `<div>` or `<table>` tags

**What is the expected behavior?**
Should not strip the` <a>` tags and keep them as links

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce (5.7.0), no.

**Comment by ashfordneil** [comment]
Hi @kevin-v96,

It's an old comment, but spocke explains this really well here: https://github.com/tinymce/tinymce/issues/2991#issuecomment-225495895. We don't support, or have plans to support, anchors with block level elements (like divs) in them. As a result, the TinyMCE schema doesn't mark `div` as a "valid child" of `a` by default. This is what causes the code plugin behaviour you're seeing: the editor parser / serialiser will strip them out.
