### ISSUE TITLE
[Safari] Deleting an input element from Tinymce Editor would result in newly inserted text to inherit style of the input element.

### ISSUE THREAD

**Issue by MelMelsy** [tinymce/tinymce#6597]
Hi, 

I'm currently facing an issue after deleting an input element that was inserted into the Tinymce editor through a custom plugin where newly created text would inherit the format/style of the input element instead of the default format/style of the other texts in the editor. This only happens on Safari.

**You may refer to the sandbox app for reference**:
https://codesandbox.io/s/tinymcevue-jgf4l

To replicate the issue:
1. On a Safari browser, open the sandbox app.
2. Type in some text into the Tinymce editor (e.g abc).
3. Insert a space at the end of the text.
4. Click on the custom plugin found at the end of the plugin toolbar (refer to video or screenshot below) which uses the editor.insertContent() function to insert an input element into the editor. 
5. Backspace once to delete the input element that was just inserted.
6. Type in some text into the editor (e.g abc2).

**Expected behavior**: The format/style of the newly entered text would be similar to the text entered in step 2.
**Actual behavior**: The newly entered text inherits the format/styling of the input element that was inserted into the content via the custom plugin.

**You may also refer to this video or the screenshots found at the end of this post**:
https://user-images.githubusercontent.com/28200679/109978469-e1828500-7d38-11eb-9aa5-74d605170a26.mov

**Dependencies used in sandbox app**:
@tinymce/tinymce-vue version 3.2.2
vue version 2.6.11

This behavior is also replicable on the official Tinymce website through the following steps: 
https://www.tiny.cloud/blog/text-entry-input-fields-html-form-design/

1. On a Safari browser, open the website and scroll to the Advanced Tinymce editor.
2. Type in some text (e.g "abc"). 
3. Click on the source code plugin.
4. Enter `<div><input style="color: red;" readonly="readonly" type="text" value="text" /></div>`.
5. Click Save.
6. Backspace once to delete the input element.
7. Type in some text (e.g "abc2").

**Expected behavior**: The format/style of the newly entered text would be similar to the text entered in step 2, which is the default format/style.
**Actual behavior**: The newly entered text inherits the format/styling of the input element that was inserted into the content via the custom plugin.

You may refer to this video:
https://user-images.githubusercontent.com/28200679/109980253-a7b27e00-7d3a-11eb-8189-3670e4e11692.mov

Thanks.

Screenshot 1: Insert an input element using the custom plugin.
![image](https://user-images.githubusercontent.com/28200679/109978767-2dcdc500-7d39-11eb-8f9d-aa8741cfe572.png)

Screenshot 2: Newly typed text inherits the format/style of the deleted input element.
![image](https://user-images.githubusercontent.com/28200679/109980418-da5c7680-7d3a-11eb-8989-bd02f5b5400a.png)

**Comment by JamesToohey** [comment]
Hi @MelMelsy,

It's worth mentioning that TinyMCE is not a form builder, using these sorts of elements is not really supported.

However, this appears to be a bug in WebKit which we have added a note to: https://bugs.webkit.org/show_bug.cgi?id=94014 

We’re going to close this issue, please subscribe to the linked WebKit bug for updates.
