### ISSUE TITLE
Override shortcuts - shortcut key to focus on toolbar

### ISSUE THREAD

**Issue by pratham1107** [tinymce/tinymce#6603]
I want to use ctrl+M key as shortcut key to focus on tinymce toolbar.
It's not working in tinymce 5 version.

P.S. I have tinymce 4 version where I can use ctrl+m key to focus on tinymce toolbar. (Is this default one because I did not find in document that this key combination is default one to focus on toolbar)

**Comment by SimonFc** [comment]
Hi @pratham1107. If I understand this correctly you're looking for a way to override existing shortcuts, specifically the current Alt/Option+F10 shortcut to focus the toolbar. This is currently not possible so I'm marking this as a feature request.

**Comment by pratham1107** [comment]
Thank you for reply.
I tried using alt/option+ F10, it's focusing on toolbar however it's not focusing on last used button on toolbar.
(e.g. there are three button cut, copy, paste. then by alt/option +f10 and then using tab I entered on copy button so next time when I do alt/option + f10 it should focus on copy. but it's not happening in current behaviour)
