### ISSUE TITLE
Center image not working for outlook mails

### ISSUE THREAD

**Issue by elyamaniadil** [tinymce/tinymce#6604]
After inserting an image on tiny editor, i put the cursor on the image (click on the image) then use the button to center it.
In the code view it produces this <img style="display: block; margin-left: auto; margin-right: auto;"  wich is not working on outlook. 
But when we put the cursor next to the image it produces <p style="text-align: center;"  wich is better since it works everywhere.

It there any correction planned for this ?

Thank you

**Comment by JamesToohey** [comment]
Hi @elyamaniadil,

Apologies for the delay in getting back to you on this.

TinyMCE's output is designed to be compatible with HTML 4/5 and the equivalent CSS standards.

Occasionally other applications do not display the content correctly (which is likely what's happening with Outlook), in which case you can modify the [content formatting](https://www.tiny.cloud/docs/configure/content-formatting/) to try to get it to work. 

Here is the default formatting for reference: https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/fmt/DefaultFormats.ts

**Comment by JamesToohey** [comment]
A quick thought: if you don't want the styles applied to images, try removing the image default formats as a first step
