### ISSUE TITLE
RTL icons are not flipped in mobile full screen version

### ISSUE THREAD

**Issue by shostkevych** [tinymce/tinymce#6609]
When using configuration with **directionality** property set to **rtl** and **language** property set to **ar**, desktop version flips icons respectively to right-to-left rules, but at the same time, mobile full screen version does not.  As an example list style icons.

Flipping icons should both work same on desktop and mobile.

TinyMCE 5.7.0 / Chrome Version 88.0.4324.192 / OS X BigSur

Attaching corresponding screenshots.

Desktop version OK

![Screenshot 2021-03-10 at 14 26 27](https://user-images.githubusercontent.com/48904766/110629974-7bb95180-81ad-11eb-8b0e-73494a21c61e.png)

Mobile version ISSUE

![Screenshot 2021-03-10 at 14 26 50](https://user-images.githubusercontent.com/48904766/110630029-8a076d80-81ad-11eb-9cb4-c322faf81a71.png)

**Comment by lostkeys** [comment]
Hi @shostkevych! You seem to be using the old deprecated mobile UI. [Have a look in the documentation on how properly set it up.](https://www.tiny.cloud/docs/mobile/)
