### ISSUE TITLE
tinymce-vue: another inline editor's bold and italic is pre-selected when first inline editor selects bold and italic

### ISSUE THREAD

**Issue by GouTong-dandan** [tinymce/tinymce#6615]
**What is the current behavior? Describe the bug**
When there are multiple **inline** tinymce editors on the page, I clicked the first editor, selected bold, italic and then input some text. After that, I clicked another editor, when the toolbar shows, the bold, italic is selected. However, the text is not bold and italic if I input some text in this editor. Can refer to the codesanbox: https://codesandbox.io/s/modest-dawn-t59sf

**What is the expected behavior?**
When another editor initialized, nothing from the toolbar is pre-selected.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
@tinymce/tinymce-vue: 3.2.8

**Comment by lnewson** [comment]
Hi @GouTong-dandan, thanks for the report! I can confirm this is a known issue and is currently being tracked via #5947, so I'm going to close this as a duplicate.
