### ISSUE TITLE
want to upload images either upload or powerpaste to server using vuejs

### ISSUE THREAD

**Issue by salipalliswathi** [tinymce/tinymce#6624]
i am currently using tinymce (open source) , i want to upload images to our server and get path of it in image src (Vuejs) . image can be uploaded in anyways drag and drop, power paste, or normal upload from local.

thank you in advance.

**Comment by HAFRMO** [comment]
Hello. From what I can tell of this issue, it seems that using https://www.tiny.cloud/docs/general-configuration-guide/upload-images/#images_upload_handler would potentially cover many of the situations you have?
