### ISSUE TITLE
How to disable table properties 'Height' and 'Alignment'

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6627]
Hi,

I am using tinyMCE. I need to disable the following properties.
Table-Row-Properties: "Footer-Type" and "height".
Table-Cell-Properties: "Height" , "Celltype" and  "Scope"
Table-Properties: "Height" and "Alignment"

![image](https://user-images.githubusercontent.com/21060460/111151055-f1119180-85b4-11eb-88da-7dacefac07b3.png)

Please suggest to me is there any option available.

Thanks.

**Comment by HAFRMO** [comment]
At this moment there does not seem to be any way to disable specific parts of the dialog as you request here. It should be possible to create your own dialogs instead and use them instead, with exactly the settings you'd prefer.
If you'd like I could also mark this as a feature request, if you'd like to request this sort of fine-grain control.

**Comment by Valgeria** [comment]
@HAFRMO ,
Could you please give sample snippet for   'create your own dialogs instead '. 

Thanks.

**Comment by HAFRMO** [comment]
You can create a dialog with the dialog api ( https://www.tiny.cloud/docs/ui-components/dialog/ ), as well as a button ( https://www.tiny.cloud/docs/ui-components/toolbarbuttons/#howtocreatecustomtoolbarbuttons ) to open the dialog with.

You will unfortunately not be able to override the command, but the button and dialog should allow you to create the dialog that suits your need and present it to your users.

You may also wish to look at the `CellDialog.ts`, `RowDialog.ts`, and `TableDialog.ts` for the current implementation of these dialogs, it should give you an idea of how to implement yours.

**Comment by mikkorantalainen** [comment]
And if you only want to remove the two inputs from "cell cell properties" dialog, you'll have to reimplement the whole `table` plugin because you have to adjust the whole chain from the start to allow your custom dialog to be opened instead of the default implementation when you select "cell properties" in quickbar or menu or context menu, right?
