### ISSUE TITLE
[Japanese] TinyMCE get data loss when using Japanese input method.

### ISSUE THREAD

**Issue by XingGao-PKI** [tinymce/tinymce#6630]
**What is the current behavior? Describe the bug**
Content after my current input cursor get lost when I use space bar to select suggestion words while inputing with Japanese. 

Steps to reproduce bug:
  1. open https://fiddle.tiny.cloud/,
  2. paste these content into the editor 

③ｻﾝﾌﾟﾙ5と6の比較
ｺｱ層が

・断面観察 SEM 必要に応じてAFM
3. change your input method to Japanese. E.g, on Mac
![image](https://user-images.githubusercontent.com/28696796/111245050-f5828c80-863e-11eb-82b6-a7d9c2215241.png)

4. move cursor to the second line end, and start input `tesuto` on keyboard. Some suggestion Japanese words came out. Use `space bar` to select between different suggestion words.

Bug: the last line of the content start to be deleted word by word.
Videos of current bug:
![tinyMCEbug](https://user-images.githubusercontent.com/28696796/111247773-95421980-8643-11eb-9528-0fbb3bf98eef.gif)

**What is the expected behavior?**
Expected behavior 
![Expected](https://user-images.githubusercontent.com/28696796/111247804-a0954500-8643-11eb-92cb-27980f7cfda9.gif)
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE version: 5.3.1, also on latest https://fiddle.tiny.cloud
Google Chrome Version : 89.0.4389.82（Official Build) (64-bit)
OS: MacOS Big Sur  11.2.1 / Microsoft Windows 10 Enterprise 64-bit (1909) en locale

**Comment by HAFRMO** [comment]
Thank you for this detailed issue description. We've verified it on our end to be as you described and logged an internal issue for development. We do not have a date for when a fix may be provided, but we will try to notify you here when it happens.

**Comment by XingGao-PKI** [comment]
Any plan to fix this rencently ?

**Comment by XingGao-PKI** [comment]
tested on latest tinymce 5.10.5, this is no longer an issue.
