### ISSUE TITLE
How to disable only table resize option not column resize option

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6632]
Hi,

I am using TinyMCE. Is there any option to disable only table resize option **not** **column resize option**.

If any option is existing please suggest to me.

Thanks.

**Comment by lostkeys** [comment]
Hi @Valgeria! Sorry, there exists no option to disable just resizing the table but still be able to resize columns and rows. I'll flag this as a feature request but I cannot tell when or if this feature will be implemented.

**Comment by speehive-admin** [comment]
**object_resizing**
https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#object_resizing
This options allows you to turn on/off the resizing handles on images, tables or media objects. This option is enabled by default and allows you to resize table and images. You can also specify a CSS3 selector of what you want to enable resizing on.

**Comment by kishoresahas** [comment]
**object_resizing**
https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#object_resizing
This options allows you to turn on/off the resizing handles on images, tables or media objects. This option is enabled by default and allows you to resize table and images. You can also specify a CSS3 selector of what you want to enable resizing on.
