### ISSUE TITLE
[Wiris Integration] [Safari]Chem equation: behaves differently from Math, editor is inactive after chem equation is inserted into editor

### ISSUE THREAD

**Issue by GouTong-dandan** [tinymce/tinymce#6637]
**What is the current behavior? Describe the bug**
The user tries to add chemical expression in the inline Richtext editor. After it is added, the caret does not appear after the added expression, and the editor becomes inactive. The user needs to click in the editor again to continue inputting. However, if the user adds math expression, the caret appears after the added expression, and the editor keeps active. The user is able to continue typing without additional clicks.
Currently, the issue is only found in Safari, Wiris works fine in Chrome.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Can refer to the codesanbox here: https://codesandbox.io/s/modest-dawn-t59sf

https://user-images.githubusercontent.com/79293925/111447941-e6880100-8748-11eb-8be1-3ea8803de89f.mov

**What is the expected behavior?**
Chem formula works the same way that the math equation works: Caret appears after the added expression, and the editor keeps active.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version of tinymce: 5.3.2
Version of Wiris: 7.24.6
Browser: Safari
Replicable to MacOs and IOS.

**Comment by lnewson** [comment]
Hi @GouTong-dandan, the MathType plugin is not something that's developed by us, so I'm afraid we can't provide any support for it. This plugin is instead developed by WIRIS, as such I would recommend reaching out to their support at http://www.wiris.com/en/contact if you're having issues.
