### ISSUE TITLE
valid_classes doesn't work

### ISSUE THREAD

**Issue by lovelike123** [tinymce/tinymce#6641]
valid_classes doesn't work

**Comment by HAFRMO** [comment]
Could you describe how it does not work, what you you were expecting and what you are actually getting, and a way to replicate the issue?

**Comment by lovelike123** [comment]
tinymce.init({
    selector: '#textarea1',
    valid_classes: {
        'p': 'class1', 
        'a': 'class2', 
    }
});
This is an official example. There is no class added to a tag and P tag. I want to add the specified class to a tag and P tag

**Comment by lovelike123** [comment]
tinymce.init({
    selector: '#textarea1',
    valid_classes: {
        'p': 'class1', 
        'a': 'class2', 
    }
});
This is an official example. There is no class added to a tag and P tag. I want to add the specified class to a tag and P tag

**Comment by lovelike123** [comment]
tinymce.init({
    selector: '#textarea1',
    valid_classes: {
        'p': 'class1', 
        'a': 'class2', 
    }
});
This is an official example. There is no class added to a tag and P tag. I want to add the specified class to a tag and P tag

**Comment by lovelike123** [comment]
@HAFRMO 
tinymce.init({
selector: '#textarea1',
valid_classes: {
'p': 'class1',
'a': 'class2',
}
});
This is an official example.Version 5.0.12 .There is no class added to A tag and P tag. I want to add the specified class to A tag and P tag

**Comment by lovelike123** [comment]
@HAFRMO 
I use vue written

**Comment by HAFRMO** [comment]
The use of vue should not have any bearing on this particular issue, thankfully, since you can make the settings and hopefully make whatever listeners you need.

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
