### ISSUE TITLE
While run the tinyMCE in browser in console its shown error

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6642]
Hi,
I am using tinyMCE. I have added all 'Skin.min.css and Content.inline.min.css' to my css file. Then Irun the tinyMCE editor, It's shown the below error in console.

**Error:**
_Refused to apply style from 'http://localhost/TinyMCERTX/skins/ui/oxide/skin.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Page.ashx?ID=1:1 Refused to apply style from 'http://localhost/TinyMCERTX/skins/ui/oxide/content.inline.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled._

![image](https://user-images.githubusercontent.com/21060460/111573815-3ad6c380-87d1-11eb-8c10-63f976e7f01d.png)

![image](https://user-images.githubusercontent.com/21060460/111581717-c5beba80-87df-11eb-8b2d-e799a8c41c68.png)

please help me how resolve this.

Thanks.

**Comment by HAFRMO** [comment]
Hello.
Can you verify that the issue at hand is not because the file can't be loaded for one reason or another? I made a swift test where the css file linked did not exist, and it resulted in this error ( And if it existed, everything worked well ).

**Comment by lnewson** [comment]
To add to what @HAFRMO has said, the console error indicates that either the file is missing/can't be loaded or that it's being loaded with the wrong mime type. As such, this likely isn't an issue with TinyMCE and instead is an issue with how you're serving the TinyMCE assets, so we're limited in the amount of help we can provide. As such, be sure to check that you've included th files in the relevant location for your server-side setup and that it's appropriately configured.

**Comment by Valgeria** [comment]
Thanks for your suggestion. the file path is not valid.
