### ISSUE TITLE
How to set only first row as header row while clicking custom command 'mceTableRowType'?

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6646]
Hi,
I am using tinyMCE.
How to set only first row as header row while clicking custom command? 
Even the selection in any where of the table.

Thanks.

**Comment by HAFRMO** [comment]
Hello. I'm not quite clear on what your problem is, nor what you are trying to do. Could you give a couple more details, such as what the expected outcome is, what the actual outcome is, and what the custom command you are trying to do is?
