### ISSUE TITLE
Icons in the 'stlye_formats' fail to load without any errors/logs.

### ISSUE THREAD

**Issue by karanvalecha** [tinymce/tinymce#6649]
**What is the current behavior? Describe the bug**

Using a CDN path e.g. CloudFront as the `baseURL` will not load any Icons under the style_formats. The same icons do work on the toolbar, but not inside the style_formats component.

For example:

Style Formats Icons do not load with ->  tinymce.baseURL = 'https://subdomain.cloudfront.net/assets/tinymce'

Style Formats Icons DO load with ->  tinymce.baseURL = 'https://www.myserver.net/assets/tinymce'

Inspecting the Network tab will show all requests as successful & obviously the files rendered are exactly the same.

-----

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://fiddle.tiny.cloud/O7haab/5

I have provided both the CloudFront URL the actual server URL that CloudFront loads assets from.

**What is the expected behavior?**

If there are any errors in loading the Icons in the Style Formats component, there must be error logs.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Version >= 5.3

**Comment by lnewson** [comment]
Hi @karanvalecha,

Thanks for the report! Unfortunately I'm unable to reproduce the issue you've mentioned using the provided replication case, as the icons are loading fine using the CloudFront URL provided (see screenshots below).

Are you able to provide any screenshots of the console/network tab or similar instead to try and diagnose why it's not working for you? Also have you tried loading via an incognito/private window, just to ensure no browser extensions are causing issues? Another thing to check would be to make sure the icons.js file is returning the correct data (eg `application/javascript` mime type and js containing `tinymce.IconManager.add("default",{icons:{...}})`).

It's also worth noting that the icons are shared between menu/toolbar (eg they both are pulled from the same source), so this statement indicates something else is going on
> The same icons do work on the toolbar, but not inside the menu item component.

Fiddle:
![image](https://user-images.githubusercontent.com/1575550/111813319-c4e37100-8924-11eb-8572-f45a6b641817.png)
Network:
![image](https://user-images.githubusercontent.com/1575550/111814100-cc574a00-8925-11eb-80de-5ade0d6c2738.png)

**Comment by karanvalecha** [comment]
Hi @leemhenson thanks for looking into this.

I just realized that the menu item I am mentioning here would mean the one that comes from `style_formats` section

Sorry, I should have included a screenshot - here's one

![image](https://user-images.githubusercontent.com/10561168/111815589-dd8e5f80-8901-11eb-8ac3-6fac7ad97ee9.png)



Could you please verify this once?

**Comment by lnewson** [comment]
Also here's another screenshot showing the style formats menu is rendering the icons correctly as well:
![image](https://user-images.githubusercontent.com/1575550/111815699-b5b1f280-8927-11eb-9394-683a846acf65.png)

**Comment by lnewson** [comment]
Given that screenshot, here are some other things that might be useful to debug what's happening are:
- What browser/OS are you using?
- Are you able to provide a screenshot or the raw HTML of the DOM for that menu? (the `tox-collection__item-icon` div is what I'm most curious about)

**Comment by karanvalecha** [comment]
> Given that screenshot, here are some other things that might be useful to debug what's happening are:
> 
> * What browser/OS are you using?
> * Are you able to provide a screenshot or the raw HTML of the DOM for that menu? (the `tox-collection__item-icon` div is what I'm most curious about)

@lnewson I am not able to see icons on any of the browsers yet.

The screenshot is from Google Chrome on macOS Big Sur (same results on Safari)
```
Version 89.0.4389.82 (Official Build) (x86_64)
```

----

Here's the raw HTML (beautified for readability)

```html
<div class="tox-collection__group">
	<div title="Bold" role="menuitemcheckbox" aria-haspopup="false" tabindex="-1" class="tox-menu-nav__js tox-collection__item" aria-checked="false">
		<div class="tox-collection__item-icon tox-collection__item-checkmark">
			<svg width="24" height="24">
				<path d="M18.2 5.4a1 1 0 011.6 1.2l-8 12a1 1 0 01-1.5.1l-5-5a1 1 0 111.4-1.4l4.1 4.1 7.4-11z" fill-rule="nonzero"></path>
			</svg>
		</div>
		<div class="tox-collection__item-label"><strong style="font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-weight: bold; font-style: normal; text-decoration: none solid rgb(0, 0, 0); text-transform: none; background-color: rgba(0, 0, 0, 0); padding: 0px 2px; border: 0px none rgb(0, 0, 0); border-radius: 0px; outline: rgb(0, 0, 0) none 0px; text-shadow: none;">Bold</strong></div>
	</div>
	<div title="Italic" role="menuitemcheckbox" aria-haspopup="false" tabindex="-1" class="tox-menu-nav__js tox-collection__item" aria-checked="false">
		<div class="tox-collection__item-icon tox-collection__item-checkmark">
			<svg width="24" height="24">
				<path d="M18.2 5.4a1 1 0 011.6 1.2l-8 12a1 1 0 01-1.5.1l-5-5a1 1 0 111.4-1.4l4.1 4.1 7.4-11z" fill-rule="nonzero"></path>
			</svg>
		</div>
		<div class="tox-collection__item-label"><em style="font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-weight: 400; font-style: italic; text-decoration: none solid rgb(0, 0, 0); text-transform: none; background-color: rgba(0, 0, 0, 0); padding: 0px 2px; border: 0px none rgb(0, 0, 0); border-radius: 0px; outline: rgb(0, 0, 0) none 0px; text-shadow: none;">Italic</em></div>
	</div>
	<div title="Underline" role="menuitemcheckbox" aria-haspopup="false" tabindex="-1" class="tox-menu-nav__js tox-collection__item" aria-checked="false">
		<div class="tox-collection__item-icon tox-collection__item-checkmark">
			<svg width="24" height="24">
				<path d="M18.2 5.4a1 1 0 011.6 1.2l-8 12a1 1 0 01-1.5.1l-5-5a1 1 0 111.4-1.4l4.1 4.1 7.4-11z" fill-rule="nonzero"></path>
			</svg>
		</div>
		<div class="tox-collection__item-label"><span style="font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-weight: 400; font-style: normal; text-decoration: underline solid rgb(0, 0, 0); text-transform: none; background-color: rgba(0, 0, 0, 0); padding: 0px 2px; border: 0px none rgb(0, 0, 0); border-radius: 0px; outline: rgb(0, 0, 0) none 0px; text-shadow: none;">Underline</span></div>
	</div>
	<div title="Strikethrough" role="menuitemcheckbox" aria-haspopup="false" tabindex="-1" class="tox-menu-nav__js tox-collection__item" aria-checked="false">
		<div class="tox-collection__item-icon tox-collection__item-checkmark">
			<svg width="24" height="24">
				<path d="M18.2 5.4a1 1 0 011.6 1.2l-8 12a1 1 0 01-1.5.1l-5-5a1 1 0 111.4-1.4l4.1 4.1 7.4-11z" fill-rule="nonzero"></path>
			</svg>
		</div>
		<div class="tox-collection__item-label"><span style="font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-weight: 400; font-style: normal; text-decoration: line-through solid rgb(0, 0, 0); text-transform: none; background-color: rgba(0, 0, 0, 0); padding: 0px 2px; border: 0px none rgb(0, 0, 0); border-radius: 0px; outline: rgb(0, 0, 0) none 0px; text-shadow: none;">Strikethrough</span></div>
	</div>
	<div title="Superscript" role="menuitemcheckbox" aria-haspopup="false" tabindex="-1" class="tox-menu-nav__js tox-collection__item" aria-checked="false">
		<div class="tox-collection__item-icon tox-collection__item-checkmark">
			<svg width="24" height="24">
				<path d="M18.2 5.4a1 1 0 011.6 1.2l-8 12a1 1 0 01-1.5.1l-5-5a1 1 0 111.4-1.4l4.1 4.1 7.4-11z" fill-rule="nonzero"></path>
			</svg>
		</div>
		<div class="tox-collection__item-label"><sup style="font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13.3333px; font-weight: 400; font-style: normal; text-decoration: none solid rgb(0, 0, 0); text-transform: none; background-color: rgba(0, 0, 0, 0); padding: 0px 2px; border: 0px none rgb(0, 0, 0); border-radius: 0px; outline: rgb(0, 0, 0) none 0px; text-shadow: none;">Superscript</sup></div>
	</div>
	<div title="Subscript" role="menuitemcheckbox" aria-haspopup="false" tabindex="-1" class="tox-menu-nav__js tox-collection__item tox-collection__item--active" aria-checked="false">
		<div class="tox-collection__item-icon tox-collection__item-checkmark">
			<svg width="24" height="24">
				<path d="M18.2 5.4a1 1 0 011.6 1.2l-8 12a1 1 0 01-1.5.1l-5-5a1 1 0 111.4-1.4l4.1 4.1 7.4-11z" fill-rule="nonzero"></path>
			</svg>
		</div>
		<div class="tox-collection__item-label"><sub style="font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13.3333px; font-weight: 400; font-style: normal; text-decoration: none solid rgb(0, 0, 0); text-transform: none; background-color: rgba(0, 0, 0, 0); padding: 0px 2px; border: 0px none rgb(0, 0, 0); border-radius: 0px; outline: rgb(0, 0, 0) none 0px; text-shadow: none;">Subscript</sub></div>
	</div>
	<div title="Code" role="menuitemcheckbox" aria-haspopup="false" tabindex="-1" class="tox-menu-nav__js tox-collection__item" aria-checked="false">
		<div class="tox-collection__item-icon tox-collection__item-checkmark">
			<svg width="24" height="24">
				<path d="M18.2 5.4a1 1 0 011.6 1.2l-8 12a1 1 0 01-1.5.1l-5-5a1 1 0 111.4-1.4l4.1 4.1 7.4-11z" fill-rule="nonzero"></path>
			</svg>
		</div>
		<div class="tox-collection__item-label"><code style="font-family: monospace; font-size: 13px; font-weight: 400; font-style: normal; text-decoration: none solid rgb(0, 0, 0); text-transform: none; background-color: rgb(232, 232, 232); padding: 0px 2px; border: 0px none rgb(0, 0, 0); border-radius: 3px; outline: rgb(0, 0, 0) none 0px; text-shadow: none;">Code</code></div>
	</div>
</div>
```

AFAIK: since V5.3, the icons must come on the right side of the item name. On the contrary, here the empty space on the left side is actually the placeholder checkmark icon. This shall not be the case, right? please refer:

![image](https://user-images.githubusercontent.com/10561168/111820591-b20e7380-8907-11eb-9c2e-d99f3166d320.png)

**Comment by karanvalecha** [comment]
Hi @lnewson are you able to reproduce the above? I am here not able to figure out the reasoning yet.

**Comment by lnewson** [comment]
Sorry, @karanvalecha I've been tied up with other things the past couple of days and haven't had a chance to look. So from the HTML dump you provided, that indicates that the icons aren't ever being rendered and the checkmark div is in the incorrect location.

That points to a potential caching issue with the theme that's being loaded, as it appears to be using an older version of the theme to render the UI which in turn is preventing the icons being rendered. Can you try this fiddle and see if it works? https://fiddle.tiny.cloud/O7haab/8 That uses the [cache_suffix](https://www.tiny.cloud/docs/configure/integration-and-setup/#cache_suffix) setting to try an ensure a fresh version of all the TinyMCE assets are loaded.

**Comment by karanvalecha** [comment]
@leemhenson thank you so much for looking into this.

I dug into the theme.js cache thing & it was loading theme.js from V5.2.

My understanding was that if it must be the scripts failing somewhere. Didn't notice that it's theme.js managing the placement of icons & it's not necessarily supposed to be throwing errors.

Thank you for the help, I'll close this issue 👍

**Comment by leemhenson** [comment]
Please, I have nothing to do with this issue. 😂  I suggest you thank @lnewson instead!

**Comment by karanvalecha** [comment]
> Please, I have nothing to do with this issue. 😂 I suggest you thank @lnewson instead!

@leemhenson You must have seen this a lot here 😂

**Comment by jordanade** [comment]
To fix this, vote for https://github.com/tinymce/tinymce/issues/9403
