### ISSUE TITLE
When images_upload_handler calls failure() with a string, the dialog displays [object object] instead of the error string

### ISSUE THREAD

**Issue by rogerjaffe** [tinymce/tinymce#6651]
I'm trying to prohibit uploading files larger than a certain size.  When uploading an image, if the size is too big I call `failure()` with a string and the optional `{remove: false}` object.   The dialog displays [object object].  

I was using Version 5.1.1, then upgraded to V5.7.1 but the error continues.

This is my configuration object.  Note that the call to failure() displays [object object] instead of the string

```
  // TinyMCE editor configuration object
  const editorConfig = {
    height: 450,
    menubar: false,
    plugins: [
      'advlist autolink lists link image charmap print preview anchor',
      'searchreplace visualblocks code fullscreen',
      'insertdatetime media table paste code help wordcount'
    ],
    toolbar:
      `bold italic underline forecolor backcolor link image | undo redo | fontselect fontsizeselect formatselect | 
      alignleft aligncenter alignright alignjustify | 
      bullist numlist outdent indent | removeformat | table | help`,

    file_picker_types: 'file image'/*image media*/,
    images_upload_handler: (blobInfo, success, failure, progress) => {
      let blob = blobInfo.blob();
      if (blob.size > MAX_UPLOAD_SIZE) {
        failure('File too large. Max size = '+MAX_UPLOAD_SIZE, { remove: true });
      } else {
        upload(blob, (err, url) => {
          if (err) {
            failure(url);
          } else {
            success(url);
          }
        })
      };
    },
}
```

See the fiddle at `http://fiddle.tiny.cloud/a8haab`

**Comment by lnewson** [comment]
Hi @rogerjaffe, thanks for the report! This issue has already been reported via https://github.com/tinymce/tinymce/issues/6579 so I'm going to close this as a duplicate.

I should note the fiddle you've linked is using TinyMCE 5.7.0, not 5.7.1. If you use 5.7.1 then it'll work, eg: http://fiddle.tiny.cloud/a8haab/1. We'll be updating the cloud version to 5.7.1 later this week, assuming there are no issues found with our enterprise QA checks.

**Comment by rogerjaffe** [comment]
Good evening and thank you so much for the quick response!  I've made the
changes in my code and it works like a charm!

Thanks again.
RJ
