### ISSUE TITLE
Unselect the Numbered List to content then text is placed between <p> tag due to this each line had space

### ISSUE THREAD

**Issue by kumarmamidi** [tinymce/tinymce#6655]
Issue: UnSelect Numbered List then each line is placed between `<p>` tag.

expected : Should be normal as in previous status.

Step1 : Enter following content in TinyMCE editor (text is placed with in div tag)
```
<div>Line1</div>
<div>Line2</div>
<div>Line3</div>
```

Step2: Select Number list option it will convert as in below
```
<ol style="list-style-position: inside;">
<li>Line1</li>
<li>Line2</li>
<li>Line3</li>
</ol>
```

Step3: unselect Number list option it will convert as in below (text placed with in p tag)
```
<p>Line1</p>
<p>Line2</p>
<p>Line3</p>
```

Excepted behavior as in step1

Kindly let me how i can achieve it ?

**Comment by JamesToohey** [comment]
Hi @kumarmamidi,

This is intended behaviour, when you convert the content to a list and then back it will return to using the root block (default `<p>`).

You can change the root block element by using the [`forced_root_block` setting](https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block), however this is not advised as it may cause unintended side effects elsewhere and impair the functionality of TinyMCE.
