### ISSUE TITLE
Error in writing

### ISSUE THREAD

**Issue by kikors** [tinymce/tinymce#6659]
When i am writing in my tiny the cursor goes to the first caracter, in the attached image i wrote "Hello this is a test"
![tiny](https://user-images.githubusercontent.com/7375864/112437107-e094b000-8d46-11eb-8154-ee5503c51968.png)

**Comment by FelipeQueiroz** [comment]
Hi! I got the same problem and i got two libs for tinymce text editor:
"@tinymce/tinymce-react": "^3.6.1",
"tinymce": "^5.5.1",

The fix for me is to outdate @tinymce/tinymce-react to 3.5.0 and work well!
I hope it helps you, seeya!

**Comment by kikors** [comment]
Solved!! update to 3.12.0 version

Thank you very much
