### ISSUE TITLE
Quicklink default target

### ISSUE THREAD

**Issue by tsamu** [tinymce/tinymce#6660]
If you set default_link_target, quick link does not work as expected.

```
editor.ui.registry.addContextForm('quicklink', {
...
    onAction: (formApi) => {
...
        target: Optional.from(getDefaultLinkTarget(editor))
```

**Comment by JamesToohey** [comment]
Hi, thanks for reporting this. Is it possible for you to create a reproduction case in a [TinyMCE Fiddle](https://fiddle.tiny.cloud/)?

**Comment by tsamu** [comment]
https://fiddle.tiny.cloud/O8haab/7

If you use the quicklink feature, href target is missing.
