### ISSUE TITLE
Ordered list is not rendering in Editor while copying 

### ISSUE THREAD

**Issue by mish1102** [tinymce/tinymce#6663]
When I copy the ordered list from PPT and paste it to the editor, the ordered list is not identified, it is identified as a p tag. 
But if the same thing I tried with unordered, it is working fine. 

Do we have any output on the same?

**Comment by JamesToohey** [comment]
Hi @mish1102,

Pasting content from PPT is not officially supported by TinyMCE. Our [paste plugin](https://www.tiny.cloud/docs/plugins/opensource/paste/) only supports Word. Generally MS Office applications will represent ordered lists as paragraphs, which is why you're seeing this.

**Comment by mish1102** [comment]
> Hi @mish1102,
> 
> Pasting content from PPT is not officially supported by TinyMCE. Our [paste plugin](https://www.tiny.cloud/docs/plugins/opensource/paste/) only supports Word. Generally MS Office applications will represent ordered lists as paragraphs, which is why you're seeing this.

Hey @JamesToohey Thanks for the update. Truly appreciate it. 
An add on to it, I had worked on pasting content from PPTx to Tinymce to officially supports List, and paragraphs. 
I will be looking forward if I can contribute to add my effort in the same. 
Thanks!
