### ISSUE TITLE
Prevent formatting and strip html from a contenteditable

### ISSUE THREAD

**Issue by ben-rogerson** [tinymce/tinymce#6667]
Hey there

We’re developing a plugin for use in a large note-taking app.
The plugin adds a contenteditable div within a non-contenteditable div, like this:

```html
<div contentEditable="false">
  <div contentEditable="true">
   Plain text only
  </div>
</div>
```

Here’s the behaviour we’re seeking in the inner div:

- It can’t contain HTML nor allow any formatting - only plain text
  How can we prevent and strip formatting in this div if it happens to be pasted in from another source?
  
- When the selection is within this div, we need to disable all the toolbar icons
  We can disable all toolbar icons at once with `editor.ui.disable();` but the keyboard shortcuts are still active.
  Can we disable all keyboard shortcuts temporarily with a similar command? Or is there a better way to achieve this?

Thanks ahead

**Comment by lostkeys** [comment]
Hi @ben-rogerson! I'm going to be honest and tell you that TinyMCE does not handle any of these things very well.
1. There aren't any options to restrict the content put into the content-editable div. There are ways to configure TinyMCE to filter out any unwanted tags upon submit, but it will show up for users while inside TinyMCE. Making matters worse, the editable div is deletable, so if you are making some sort of widget, keep in mind that it's easy for the end user to break the widget by hitting backspace one time too many. It's usually undoable but not all users know that.
2. I'll have to have an engineer get back to you on this issue.

We are actively looking at improving the noneditable features and if you are up for it I'd love to hear more about your particular use-case to gather as much insights as possible. If you accept I can reach out to you via the email in your Github bio.

**Comment by ben-rogerson** [comment]
Thanks for the honest response Fredrik - feel free to contact me via email to followup 👍

**Comment by JamesToohey** [comment]
Hi @ben-rogerson,

There is currently no way to disable all editor shortcuts with a single command. If you wish to disable a shortcut, you can override it with a no-op like this:

```javascript
// Disable "Bold" shortcut
editor.addShortcut('meta+b', function () {});
```

**Comment by ben-rogerson** [comment]
@JamesToohey Thanks for the info. I found that adding a no-op for every shortcut didn't suit us so I looked for an alternative solution.

I've found that a keydown event listener can be added on the `<div contentEditable="false">` which allows me to refuse the key shortcuts:

```js
keydown: (event) => {
	const metaKeyAllowList = ['ArrowLeft', 'ArrowRight']
    if (event.metaKey && !metaKeyAllowList.includes(event.key))
        return false; // Avoid command key shortcuts
},
```

No issues with this implementation - yet :)
