### ISSUE TITLE
Spellcheck does not work when text is added programatically 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#667]
Description of problem: When text is added programmatically in tinymce the previous text added in the editor which was showing spellcheck error before does not shows any error after adding text programmatically. This happens in chrome in Windows,Ubuntu and MAc OS. while in firefox the text whenever added shows error for previous added text also. 

Steps to reproduce:
1.Add some text in the tinymce editor which shows errors.
2.Add some text programmatically.
3.Now the text which was added and was showing spellcheck errors after adding text programmatically now donot shows any error.

Expected result:The the whole text in the tinymce editor should show errorline even some text added programatically.

Actual result:The tinymce spellcheck does not shows any error.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5880](http://archive.tinymce.com/develop/bugtracker_view.php?id=5880) posted by [udita](http://archive.tinymce.com/profile.php?name=udita)_

> _**Tags:** [chrome chrome10 chrome11 chrome12 chrome13]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/9gdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
