### ISSUE TITLE
【media plugin】 video template encode the "source" tag, causing the video tag to fail

### ISSUE THREAD

**Issue by sws797** [tinymce/tinymce#6673]
![image](https://user-images.githubusercontent.com/33458935/112709848-a4ed1800-8ef7-11eb-8f55-59c37ecd0dba.png)

MP4 example link `https://file.learnerhub.net/tinymce-media-1616723684073/华为录制5s.mp4`

embed example
```
<video width="476" height="238" controls="controls">
    <source src="https://file.learnerhub.net/tinymce-media-1616723684073/华为录制5s.mp4" type="video/mp4">
</video>
```

I failed to add video. Is this a bug?

tinymce 5.7

you can try it on your website https://www.tiny.cloud/docs/demo/full-featured/

**Comment by JamesToohey** [comment]
Hi @sws797, thanks for the report. It appears you're using Enhanced Media Embed which is a premium product, so I'm afraid we can't assist via GitHub. If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new

**Comment by JamesToohey** [comment]
If you are able to replicate this with the open source Media plugin, could you please provide a replication case using http://fiddle.tinymce.com/

**Comment by sws797** [comment]
@JamesToohey https://fiddle.tiny.cloud/W8haab/1 The source tag in the video tag is encode, which makes the web page unable to recognize normally

**Comment by JamesToohey** [comment]
Hi @sws797,

Thank you for your replication case and my apologies for not understanding earlier. I have raised a ticket in internally for this bug.

Thanks again!

**Comment by Binpeng-W** [comment]
> @JamesToohey https://fiddle.tiny.cloud/W8haab/1 The source tag in the video tag is encode, which makes the web page unable to recognize normally


> @JamesToohey https://fiddle.tiny.cloud/W8haab/1 The source tag in the video tag is encode, which makes the web page unable to recognize normally

兄弟，5.8了，还没解决

**Comment by Binpeng-W** [comment]
@sws797 ，你好，5.8了，这问题还没解决，你是怎么回显的

**Comment by sws797** [comment]
@Binpeng-W 搁置了，木有处理

**Comment by Binpeng-W** [comment]
> @Binpeng-W 搁置了，木有处理

我找了个办法，‘media_url_resolver’，但是不能改宽高，要想改宽高只能改code

**Comment by sws797** [comment]
> > @Binpeng-W 搁置了，木有处理
> 
> 我找了个办法，‘media_url_resolver’，但是不能改宽高，要想改宽高只能改code

谢谢，回头试一下。现在根本就没搞这些了
