### ISSUE TITLE
Copy and paste functions aren't blocked when 'Full screen pop-up with some Javascript security' is used in Moodle quiz

### ISSUE THREAD

**Issue by phil-r-openlms** [tinymce/tinymce#6676]
**What is the current behavior? Describe the bug**
When enabling the 'Full screen pop-up with some Javascript security' setting in a Moodle quiz (essay question), users are still able to copy and paste into the editor window.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Enrol a test student in a Moodle course
2. Access the student's profile and then 'Preferences'. Ensure their editor preference is set to 'TinyMCE'
2. Create a quiz activity in the course, scroll down to 'Extra restrictions on attempts' and set Browser Security to 'Full screen pop-up with some Javascript security'
2. Save and display
3. Click Edit quiz and add a new Essay type question (just fill out required fields with anything)
4. Log in as the test student and access the quiz, it will open in a new window
5. Copy some text from somewhere external to Moodle e.g. web page, notepad, then attempt to paste it into the TinyMCE editor box in the quiz window - Note the text can be pasted and no error message appears telling the student they cannot perform the action.

**What is the expected behavior?**
TinyMCE prevents any copy or paste actions and presents the user with a message informing them of this.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
OS: Windows 10
Browser: Google Chrome Version 89.0.4389.90
TinyMCE version: Replicated in both 2020110900 and 2020061500

**Misc notes**
Unsure if it was previously working or not. When using the Atto editor or Plain text with the browser security setting enabled, both prevent copy and paste actions, presenting a user with a dialogue box 'That functionality is currently disabled'

Seeing as this only appears to affect TinyMCE I thought reporting it here would be appropriate. However if you feel this is more tied to the Moodle quiz module please advise and I can report it in the Moodle Tracker instead.

**Comment by JamesToohey** [comment]
Hi @phil-r-openlms,

Thanks for the detailed report. Unfortunately this kind of thing is based on how TinyMCE is configured by the app that integrates it, in this case Moodle. Your report is better directed to them for now.
