### ISSUE TITLE
How to set toolbar width as editor width in Inline mode?

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6677]
Hi,
I am using TinyMCE as **inline editor** . I need to show the toolbar width equal to editor width. See the below images
**Existing:** **Inline editor**
![image](https://user-images.githubusercontent.com/21060460/112792300-d34a2f00-9080-11eb-9b89-8318625d7535.png)

**New: I want like as classic mode**
![image](https://user-images.githubusercontent.com/21060460/112792790-ba8e4900-9081-11eb-8e4c-d86243baffb1.png)

Code: https://codepen.io/venkat5299/pen/GRjpLpa

Is there any option to achieve this. Please suggest me.

Thanks.

**Comment by lostkeys** [comment]
Hi @Valgeria! You can use the [fixed toolbar container option](https://www.tiny.cloud/docs/configure/editor-appearance/#fixed_toolbar_container) to put the toolbar into a container div that you style to be the width of the editable space. Hope that answers your question.

**Comment by Valgeria** [comment]
@lostkeys ,
Thanks for your suggestion.

But the toolbar shown always in the bottom. I need to show always top.
![image](https://user-images.githubusercontent.com/21060460/112801620-c03e5b80-908e-11eb-9612-5c1b38363aad.png)

how to fix this.
Thanks.

**Comment by lostkeys** [comment]
You define the container element yourself so it can be anywhere on the screen. [Have a look at this demo for some inspiration](https://tinymce.github.io/tinymce-demos/email/marketing-email-inline-mode-fixed-toolbar.html)
