### ISSUE TITLE
TinyMCE Editor - Unable to get focus in Mobile iPAD Safari

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#668]
Description of problem:
when we type some content in the editor, then clicks on outside of the editor. When we click on the editor again by putting the cursor in the end of the content and then start typing, the typing is not working. Essentially, the focus on the control is not working in this scenario. 

Steps to reproduce:
1.Type content in the editor
2.Click anywhere outside editor
3. Again click on the editor again by putting the cursor in the end of the content
4.Typing is not working

Expected result: We can able to type text

Actual result: Unable to type any text

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5881](http://archive.tinymce.com/develop/bugtracker_view.php?id=5881) posted by [Priyabrata Sahu](http://archive.tinymce.com/profile.php?name=Priyabrata Sahu)_

> _**Tags:** [safari safari5]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
