### ISSUE TITLE
Losing all event bindings in custom plugins after undoing deleted texts.

### ISSUE THREAD

**Issue by shikeiyan** [tinymce/tinymce#6680]
You may refer to the sandbox app that I have created:
https://49gdd.csb.app/

**Steps to replicate the issue:**

1. Click on the custom plugin icon on the last to insert youtube
2. Click on "Insert" button under youtube 
    :  emit event can be seen in console log
    :  new div with text paragraph is inserted
3. Delete one of the new inserted text paragraph or some texts using (backspace or delete)
4. Click undo on the toolbar
5. Click on the button under youtube again 

**Current Behaviour:**
Losing event binding on the button.
Emit event is not populated in console log.
New div paragraph is not being inserted.

**Expected Behaviour:**
Event bindings are retained.

You can also refer to this video:

https://user-images.githubusercontent.com/34058332/112929903-ef66d280-914b-11eb-9925-b4adf5a14fcf.mp4

**Current version used:**

@tinymce/tinymce-vue version 3.2.8
vue version 2.6.11

Thanks.

**Comment by JamesToohey** [comment]
Hi @shikeiyan,

Thanks for reporting this. Your sandbox app has a lot of custom logic that appears to be interfering with the way TinyMCE operates. Could you please produce a minimal reproduction case of this issue using https://fiddle.tiny.cloud/?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
