### ISSUE TITLE
Form builder

### ISSUE THREAD

**Issue by anonimo82** [tinymce/tinymce#6685]
**Is your feature request related to a problem? Please describe.**
No, it's not

**Describe the solution you'd like**
I'd like to build an HTML form visually, like you can do in BlueGriffon/Kompozer

**Describe alternatives you've considered**
None yet

**Comment by anonimo82** [comment]
@lostkeys what info do you need?
I could try updating

**Comment by lostkeys** [comment]
TinyMCE does not support building forms unfortunately. It might possible to do this if you do not expect to be able to edit the form inside TinyMCE (it's not possible) and are willing to do some post processing on the output and use web components. Basically it involves using web components as placeholders for the form fields inside TinyMCE and then render them as actual forms in your front end. [You can see a web component demo here](https://tinymce.github.io/tinymce-demos/tokens/web-component-token.html)

**Comment by anonimo82** [comment]
Well, I'd just need the "visual" portion of forms, so buttons/labels/inputs/etc, I'd obviously code interaction in JavaScript or PHP myself, separately

**Comment by lostkeys** [comment]
If you just need the visual part, have a look at the non-editable plugin that makes all HTML form components like images, selects, radio buttons "static" and then you can [use concepts from this demo](https://tinymce.github.io/tinymce-demos/tinymce-basics/badges.html) to manipulate the attributes you need on each form component (look at the page source code for detailed documentation.

**Comment by anonimo82** [comment]
I can't get how is that page related to controls like buttons, checkboxes and the like

**Comment by lostkeys** [comment]
I put together a very rudimentary example using the noneditable plugin to make form components non-intractable inside TinyMCE. To insert form components you can use something like the template plugin to inject form components.
To make the form controls usable you will need to have some means to edit attributes like name, id or similar. That is where the demo I mentioned earlier comes in. Using the same concepts as badges, you can create a custom dialog to allow end users to configure the attributes. The demo showcases the design patterns for creating a custom dialog, populating existing data from the selected element and how to update the selected element when pressing OK.
