### ISSUE TITLE
getContent({format: "text"}) does not work properly (4.0b2/b3)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#669]
Description of problem:
getContent({format: "text"}) does replace linebreaks (br tags) with whitespaces. This behaviour occurs in Firefox v20 (maybe other versions) but not in IE 9. Note: The Enter key produces br tags instead of p tags by config.

Steps to reproduce:
1. Go to the fiddle
2. Enter some lines of text and be sure to put some line breaks in there
3. Click Alert Content

Expected result:
The content of the Editor in plaintext but with linebreaks. Example:
abc

efg

Actual result:
The content of the Editor in plaintext without linebreaks. Example:
abc efg

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5883](http://archive.tinymce.com/develop/bugtracker_view.php?id=5883) posted by [Dethrall](http://archive.tinymce.com/profile.php?name=Dethrall)_

> _**Tags:** [firefox firefox8]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Ggdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
