### ISSUE TITLE
How can I upload  image multiply

### ISSUE THREAD

**Issue by AmyShieh** [tinymce/tinymce#6693]
**Is your feature request related to a problem? Please describe.**

 **Describe the solution you'd like**
I want to upload image multiply

 **Describe alternatives you've considered**
I can drag or copy multiple images into the richtext and it can be auto uploaded

**Comment by JamesToohey** [comment]
Hi @AmyShieh,

Could you clarify whether you mean dragging the images directly into the TinyMCE text content or using the upload image dialog? I tried dragging multiple images directly into TinyMCE [(on this page)](https://www.tiny.cloud/docs/demo/full-featured/) and that worked.
