### ISSUE TITLE
Add copy button in block of codesample

### ISSUE THREAD

**Issue by mr-nazari** [tinymce/tinymce#6698]
Hi. I want to add a Copy button to codesample

[like this](https://uupload.ir/files/1dwx_screenshot_(1382)_li.jpg)

How to create it?

**Comment by lnewson** [comment]
Hi @mr-nazari can you clarify if you mean while editing or once the content is published outside the editor?

If it's outside the editor, as you'll need Prism.js to render the code samples (see the [docs](https://www.tiny.cloud/docs/plugins/opensource/codesample/#usingprismjsonyourwebpage)), I'd suggest enabling this Prism.js plugin: https://prismjs.com/plugins/copy-to-clipboard/

It's it's while editing, that's not currently possible and would need to be a feature request.

**Comment by mr-nazari** [comment]
Thankful . [It](https://prismjs.com/plugins/copy-to-clipboard/) worked

**Comment by Sebuahhobi** [comment]
@mr-nazari can you give me code? But, i'm was try not work
