### ISSUE TITLE
TinyMce exception for one specific scenario

### ISSUE THREAD

**Issue by KhurramShehzadd** [tinymce/tinymce#6699]
Hi, 

I'm using tinymce 4.4.3, everything seems to work fine. But there is one scenario when tinymce behaved weird and throw exception for no reason. 

Steps to reproduce:
1. Creating a normal document.
![image](https://user-images.githubusercontent.com/23308945/113506320-32aeb000-9555-11eb-8f8f-4f409d1935a9.png)

2. Changing the font without selecting any text. 
![image](https://user-images.githubusercontent.com/23308945/113506359-79040f00-9555-11eb-91f6-1a6da34843da.png)

3. After changing the font, it adds a span somewhere as shown in image below.
![image](https://user-images.githubusercontent.com/23308945/113506380-9e911880-9555-11eb-8d61-9b75f9a50115.png)

4. Now, when any post-back happens on page, we are saving tinymce tinyMCE.triggerSave(); and then removing it before inilizing a new one. tinymce.remove();

5. It gives the following exception: 
Uncaught TypeError: Cannot read property 'createRange' of undefined
    at u.getRng (tinymce.min.js:6)
    at u.getStart (tinymce.min.js:6)
    at le (tinymce.min.js:7)
    at B.<anonymous> (tinymce.min.js:7)
    at t.i [as fire] (tinymce.min.js:8)
    at B.fire (tinymce.min.js:8)
    at B.getContent (tinymce.min.js:11)
    at B.save (tinymce.min.js:11)
    at B.remove (tinymce.min.js:11)
    at Object.remove (tinymce.min.js:12)

**_Note: It is happening only during these steps, if I select the text and then change font. Everything works normal as expected._**

**Comment by lnewson** [comment]
Hi @KhurramShehzadd, I'm afraid TinyMCE 4.4 has not been supported for many years now and we stopped supporting TinyMCE 4 entirely at the end of last year: https://www.tiny.cloud/blog/tinymce-4-support-window/

As such I'd suggest upgrading to TinyMCE 5, as I was unable to reproduce the issue there. If you can still reproduce it using the latest version of TinyMCE though please let us know and we'll be happy to reopen and investigate further.
