### ISSUE TITLE
Keyboard shortcuts to create lists

### ISSUE THREAD

**Issue by Philipp91** [tinymce/tinymce#6700]
**Describe the feature you'd like**

* Ctrl+Shift+7 => Create numbered list
* Ctrl+Shift+8 => Create bullet list
* Ctrl+Shift+9 => Create checkbox list

These shortcuts match Google Docs. They would be more intuitive to remember too if the numbered-list icon were ordered before the bullet-list icon in in the toolbar.

**Comment by lnewson** [comment]
Hi @Philipp91, thanks for the submission. I've marked this as a feature request for our Product Team to review.

With regards to the toolbar, you're free to change that to whatever suits your preference by providing a custom [toolbar](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar) configuration.
