### ISSUE TITLE
href links are not working properly with same domain

### ISSUE THREAD

**Issue by pradeepaitha11** [tinymce/tinymce#6702]
**What is the current behavior? Describe the bug**
The href links are getting removed and are getting replaced with '..'. The issue is specifically happening when hosting the code in a domain and pointing the href link to a url within the same domain. Hence it is not being reproduced in fiddle.

Before saving the link:
![image](https://user-images.githubusercontent.com/50624905/113592263-c7fb8400-95e9-11eb-9375-659b010c6539.png)

After saving the link and opening the source code again:
![image](https://user-images.githubusercontent.com/50624905/113592298-d21d8280-95e9-11eb-9ec6-c91c8b03ae15.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://codepen.io/pradeepaitha11/pen/LYxLgzv (Works fine in pen but doesn't work fine when hosted in a domain. Attaching screenshots for the same).

**What is the expected behavior?**
The links should not get replaced.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version 5.

**Comment by lnewson** [comment]
Hi @pradeepaitha11, this is expected behaviour using the default settings. You can change that behaviour though by adjusting the default settings, which are documented here: https://www.tiny.cloud/docs/configure/url-handling/. In your case I believe you'd want to add the following settings, if you want the URL to be absolute:
```
relative_urls: false,
remove_script_host : false,
```

**Comment by pradeepaitha11** [comment]
Thank you so much @lnewson. The above additional configuration helped me solved my problem.
