### ISSUE TITLE
forced_root_block does not work with list plugin

### ISSUE THREAD

**Issue by etanter** [tinymce/tinymce#6705]
Hi,

Even if I set `forced_root_block` to false, there is still some `<p>...</p>` wrapping happening around bullet/numbered lists.

The documentation does not mention if there's something special to do in that case.

Thanks

**Comment by SimonFc** [comment]
Hi @etanter, can you create a demo at https://fiddle.tiny.cloud/ with the exact configuration + content required to replicate this issue and describe the steps you take. For example:

1. Position cursor at...
2. Press enter...
3. etc.

Thanks

**Comment by etanter** [comment]
@SimonFc Sorry, after some more investigation I figured out that the observed behavior is as expected. There was some sneaky css interfering... :-/
