### ISSUE TITLE
How to add event listener to new HTML element

### ISSUE THREAD

**Issue by kiliandr** [tinymce/tinymce#6706]
I am working on a plugin that makes it able to add system code like this to the editor:

`[quiz]id=1[/quiz]`

This code will be replaced on server side.

The editor should (in WYSIWYG mode) hide this code and replace it with a `<div class="quiz">ID 1</div>` (a red box).

If the user clicks on that box an dialog should open where he can change the ID of the quiz.

when saving the editor should give back the [quiz]-code (not the html representation). But if i have to replace it on the server this would be okay anyway...

What i am still failing at:

- i could not find out how to add an event listener to a new HTML element.
- i ask myself if there is a better way of making html-elements interactive because it seems to be a quite common thing... (maybe there are allready watch functions etc)

i tried this:

let el = tinymce.activeEditor.dom.create('div', {'class': 'quiz'}, "ID: 1");
tinymce.activeEditor.selection.setNode(el);
				
el.on("click", function() {
console.log("click!!");
});

and it adds the `<div>`-element, but no event listener.

I would appreciate any help and suggestions.
Maybe a simple plugin example would also help. I am searching for several days now but with no success...

**Comment by SimonFc** [comment]
Hello,

Regarding adding event listeners to elements in the content area - I recommend that you do avoid this as elements can be deleted and created for a number of reasons by TinyMCE and its plugins. Listen to the editor click event instead and filter on elements which have the "quiz"-class. https://www.tiny.cloud/docs/advanced/events/#handlingeditorevents

Regarding & - having ampersands encoded as &amp;amp; is according to the spec for HTML entities so TinyMCE is working as expected here. Some entity encoding can be disabled with the [entity_encoding](https://www.tiny.cloud/docs/configure/content-filtering/#entity_encoding) option but not for ampersands.

Regarding the content being wrapped in paragraphs - maybe you're looking for the [forced_root_block](https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block) option?

Also, if you haven't already done so I recommend you to take a look at the Noneditable plugin as well. See https://www.tiny.cloud/docs/plugins/opensource/noneditable/

**Comment by kiliandr** [comment]
Thank you SimonFc!
ok, i guess this is too much work for this little thing... i think i will train the users to user the codes instead.
