### ISSUE TITLE
No information on using own emoji images along with custom emoticons database

### ISSUE THREAD

**Issue by roenfeldt** [tinymce/tinymce#6712]
**Documentation/Product Version**
_TinyMCE 5 Documentation_

**Related page URL (if applicable)**
https://www.tiny.cloud/docs/plugins/opensource/emoticons/

**I would like to know...**
I don't need the whole (default) list of emoticons, but rather a specific set which I already configured, as per https://www.tiny.cloud/docs/plugins/opensource/emoticons/#emoticons_database. Which is working well.

```javascript
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'emoticons',
  toolbar: 'emoticons',
  emoticons_database_url: 'https://example.com/emojis.js'
});
```

```javascript
// emojis.js Database
tinymce.Resource.add('tinymce.plugins.emoticons', {
  /* REJSER OG STEDER */
  "Anker": {
    keywords: ['anker', 'båd', 'skib', 'skipper', 'kaptajn'],
    char: '⚓',
    category: 'travel and places'
  },
  "Bjerg": {
    keywords: ['bjerg'],
    char: '⛰️',
    category: 'travel and places'
  },
  "Solopgang": {
    keywords: ['sol', 'solopgang'],
    char: '🌅️',
    category: 'travel and places'
  },
  "Regnbue": {
    keywords: ['regnbue', 'farver'],
    char: '🌈',
    category: 'travel and places'
  },
  
  /* OBJEKTER */
  "&Aelig;delsten": {
    keywords: ['ædelsten', 'diamant', 'juvel', 'perle'],
    char: '💎',
    category: 'objects'
  },
};
```

The problem arises when I'm specifying the `emoticons_images_url` value, as per https://www.tiny.cloud/docs/plugins/opensource/emoticons/#emoticons_images_url, which contains the path to the folder where my self-hosted, custom emoji images reside. I made sure to keep the images file naming convention exactly as the default Twemoji ones.

However, my custom images won't show up, unless I remove the `emoticons_database_url` parameter along with its value, and add the `emoticons_database: 'emojiimages'`. In which case, **all** the default emojis are showing up, which is against my needs of using only a specific, limited set of emojis, along with their localized names + keywords.

To sum it all up, what's the proper way of using a specific set of emojis, while having each of them make use of a custom, self-hosted .PNG image?

Thank you.

**Comment by roenfeldt** [comment]
@tylerkelly13 thank you, much appreciated!

**Comment by SimonFc** [comment]
Hi @roenfeldt, just to clarify - you are not trying to use the custom `tinymce.plugins.emoticons` database that you have pasted as a code snippet (you just described this as something which is working) but you have a second database that is using images, similar to the emojiimages database. What does your `emoticons_images_url` setting look like? I found that the url concatenation logic in the emoticons plugin perhaps isn't that smart as it requires a slash at the end.

In case I misunderstood your issue and you have not yet created a custom database that is using images and you would like to have something as a refererence, the emojiimages database looks like this:
```
// Source: npm package: emojilib
// Images provided by twemoji: https://github.com/twitter/twemoji
window.tinymce.Resource.add('tinymce.plugins.emoticons', {
  "100": {
    "keywords": [
      "score",
      "perfect",
      "numbers",
      "century",
      "exam",
      "quiz",
      "test",
      "pass",
      "hundred"
    ],
    "char": "<img data-emoticon=\"true\" style=\"width:1em;height:1em;margin:0 .05em 0 .1em;vertical-align:-.1em\" draggable=\"false\" alt=\"💯\" src=\"1f4af.png\"/>",
    "fitzpatrick_scale": false,
    "category": "symbols"
  },
  // plus a lot more....
});
```

**Comment by roenfeldt** [comment]
Hi @SimonFc, I apologize for the lack of clarity of my use case scenario. I'll try to be as specific as possible. 

FYI: 

- I'm using a local development environment serving the "website" locally at `http://mdplm.test`
- my local emoji .PNG images are all located at `http://mdplm.test/mh-emoji/` - yes, I made sure to include the slash character at the end of the URI
- all of the above-mentioned .PNG emoji images are being properly loaded into the emoji list modal upon clicking the smiley button in the Tiny toolbar. All good ***so far***.
- HOWEVER: I don't need ***all*** those emojis, as a matter of fact, I only need a specific, limited "subset" of them. And therefore, I'm specifying the `emoticons_database_url` argument, whose value is `http://mdplm.test/js/emojis.js`, in other words, specifying my custom database. See the code of my custom database below (second code block). I'm hoping I'm making more sense this time :)

```
<!-- MAIN DOC -->
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.tiny.cloud/1/my-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body>
  <textarea>
    Welcome to TinyMCE!
  </textarea>
  <script>
    tinymce.init({
      selector: 'textarea',
      plugins: 'emoticons',
      toolbar: 'emoticons',
      	
      /*emoticons_database_url: 'http://mdplm.test/js/emojis.js',*/ /* <<< images NOT loaded if uncommenting this line */
      
      emoticons_database: 'emojiimages',
      emoticons_images_url: 'http://mdplm.test/mh-emoji/',
    });
  </script>
</body>
</html>
```

```javascript
// EMOJI IMAGES DATABASE
tinymce.Resource.add('tinymce.plugins.emoticons', {
  /* REJSER OG STEDER */
  "Anker": {
    keywords: ['anker', 'båd', 'skib', 'skipper', 'kaptajn'],
    char: '⚓',
    category: 'travel and places'
  },
  "Bjerg": {
    keywords: ['bjerg'],
    char: '⛰️',
    category: 'travel and places'
  },
  "Solopgang": {
    keywords: ['sol', 'solopgang'],
    char: '🌅️',
    category: 'travel and places'
  },
  "Regnbue": {
    keywords: ['regnbue', 'farver'],
    char: '🌈',
    category: 'travel and places'
  },
  
  /* OBJEKTER */
  "&Aelig;delsten": {
    keywords: ['ædelsten', 'diamant', 'juvel', 'perle'],
    char: '💎',
    category: 'objects'
  },
};
```

**Comment by SimonFc** [comment]
No worries, and thanks for the extra information. It seems like the documentation is lacking when it comes to using images as you have stated earlier. https://www.tiny.cloud/docs/plugins/opensource/emoticons/#emoticons_database_url describes loading a custom database, but I can't find any information on the required structure when using images. What if you use img tags instead of unicode characters as in the code snippet I posted above? (updated with a comment) The custom database you have given as an example is only using unicode characters, so is this perhaps why "they're not **_images_** anymore".

And then use the following init config:
```
tinymce.init({
  selector: 'textarea',
  plugins: 'emoticons',
  toolbar: 'emoticons',  
  emoticons_database_url: 'http://mdplm.test/js/emojis.js',
  emoticons_images_url: 'http://mdplm.test/mh-emoji/',
});
```

**Comment by roenfeldt** [comment]
@SimonFc your suggestion works! Thank you so much for helping me out. I am grateful for your help :)

For reference, what I ended up doing, was simply using img tags within the custom database (and using CSS classes, instead of inline style), for instance:

```javascript
window.tinymce.Resource.add('tinymce.plugins.emoticons', {
  "Anker": {
    keywords: ['anker', 'båd', 'skib', 'skipper', 'kaptajn'],
    char: '<img data-emoticon="true" class="mdplm-emoji" draggable="false" alt="\u2693" src="26f0.png"/>',
    category: 'travel and places'
  }
});
```

```css
img.mdplm-emoji {
  width: 1em !important;
  height: 1em !important;
  margin: 0 .05em 0 .1em !important;
  display: inline !important;
  vertical-align: .1em !important;
}
```
