### ISSUE TITLE
I added my Domain in Tinymce but still Getting Invalid API key.

### ISSUE THREAD

**Issue by kiran290** [tinymce/tinymce#6713]
I Just added my Domain in the Tinymce Domain List but Getting an Invalid API key. please support to Close the Issue.

![Issue](https://user-images.githubusercontent.com/59478011/113812694-27919500-978c-11eb-82bc-91a391734a13.PNG)

**Comment by SimonFc** [comment]
Hi, take a look at this blog post and see if you are able to resolve the issue with the information provided there: https://www.tiny.cloud/blog/this-domain-is-not-registered-with-tiny-cloud/
If not, please provide more information on your specific use case. Thanks.
