### ISSUE TITLE
Cannot save entered Font colors - the Save button does not respond

### ISSUE THREAD

**Issue by douglerner** [tinymce/tinymce#6719]
**What is the current behavior? Describe the bug**

Update: It was working in other browsers. It was working in an Incognito window in Chrome. Clearing the cache didn't work. Relaunching Chrome didn't work. So I tried clearing the cookies and site data just for one site experiencing the problem. That worked!

Something got "stuck" from some old cookies or old site data. What happened remains a mystery though so I'll report it anyway because it might be a tinyMCE bug. If somebody wants to close this report they can.

The problem was not being able to save colors set with the color picker in tinyMCE. Clicking the Save button just doesn't do anything but an error is generated in the JavaScript console.  Maybe a new bug rolled out?

Please see the video capture for an example. https://photos.app.goo.gl/EB2P45tQhS3rE3PL9

The error is this:

theme.min.js:4 Uncaught TypeError: r.unshift is not a function
    at Object.add (theme.min.js:4)
    at jb (theme.min.js:4)
    at theme.min.js:4
    at Object.each (theme.min.js:4)
    at theme.min.js:4
    at Object.r [as onSubmit] (theme.min.js:4)
    at theme.min.js:4
    at theme.min.js:4
    at theme.min.js:4
    at Object.each (theme.min.js:4)

theme.min.js is at cloud.tiny.com.

Does anybody know what the cause is and what a fix might be? Thanks.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Select text. Use the text color toolbar (or the text color in the menu Format dropdown). Manually enter a color (e.g. a hex color). Try to click save.

**What is the expected behavior?**

That the color you entered gets saved. But the save button does not respond and the JavaScript console reports an error. This just started happening at both my sites where it was working fine before.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

The latest cloud version (5.7?). It seemed to have been working and suddenly stopped over a couple of days. All browsers.

**Comment by douglerner** [comment]
The problem appears to have to do with some change I made to tinymceInit(). Not sure what, but I have documented this at [https://stackoverflow.com/questions/66994924/unable-to-save-colors-changed-with-the-color-picker-in-tinymce](url) if anybody would like to maybe glance at it and help? Thanks.

**Comment by douglerner** [comment]
This does appear to be a bug. Depending on the options, or order of the options loaded, the Save in font color causes a JavaScript error in theme.min.js which is at cloud.tiny.com. I've described the error in more detail in my stackoverflow post above if anybody can take a look at it. Thanks.

**Comment by SimonFc** [comment]
Hi @douglerner,
I was able to replicate the aforementioned error by setting the value of the color [cache](https://github.com/tinymce/tinymce/blob/84ce865eacab7d6dc26d4fae33f3f551ee32afb1/modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorCache.ts#L14) to a string, although I can't see how this would be possible to do with just the UI (i.e. without manipulating localstorage directly). If you are able to replicate this issue again it would be great to know the value of `localStorage.getItem('tinymce-custom-colors')`, and of course the steps taken before arriving at this value.

An upcoming [release](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/CHANGELOG.md#fixed) will contain a fix to the color picker dialog which will prevent users from saving invalid hex values. If the cache somehow was invalid due to an invalid value having been saved earlier, this will hopefully prevent it from happening again.

Are you able to check the specific version in use? You can do this by logging `tinyMCE.minorVersion` to the console. And are you perhaps using the dev-channel? Thanks.

**Comment by douglerner** [comment]
Hi @SimonFc,

Thanks for your reply. I'm glad you were able to replicate the error. It is happening yet again this morning at my site even though I cleared the cookies and site data. I have not cleared them again this morning.

The steps taken just now were (1) open the editor, (2) enter some text, (3) select part of the text, (4) open the text color setting, (5) go into the manual settings panel, (6) double click on the existing hex value there, (7) enter a different hex value (in this case ff2233), and (8) click save.

The JavaScript Console in Chrome on my Mac shows this:

theme.min.js:4 Uncaught TypeError: r.unshift is not a function
    at Object.add (theme.min.js:4)
    at jb (theme.min.js:4)
    at theme.min.js:4
    at Object.each (theme.min.js:4)
    at theme.min.js:4
    at Object.r [as onSubmit] (theme.min.js:4)
    at theme.min.js:4
    at theme.min.js:4
    at theme.min.js:4
    at Object.each (theme.min.js:4)

That's all the console shows.

In the Chrome developer's panel it shows the value of `localstorage.getItem('tinymce-custom-colors')` as this:

"[\"#ff3333\", \"#ff3322\", \"#ff2200\", \"#120ed2\", \"#ff2233\"]"

That is the entire contact of localstorage showing right now.

As far as the version goes, if I just type `tinyMCE.minorVersion` into the console under the above error message it replies with:

"7.1"

Is that what you needed? I'm not familiar with dev-channel. Is that whether to use the current stable version or not? If so, I believe I chose the current stable version, but don't remember for sure.

Thank you. I am relieved to be in contact with a human!

**Comment by douglerner** [comment]
Hi again, @SimonFc,

A short followup. I again cleared the cookies-and-storage for the site and repeated the test above. This time it worked, as expected. I checked `localstorage.getItem('tinymce-custom-colors')` again and this time it is showing just this:

["#ff3322"]
0: "#ff3322"

I guess previous list was accumulated from other tests?

And this time there is that "0:" line, but that didn't show up before.

No errors are occurring at the moment, since clearing the data again.

Thanks.
