### ISSUE TITLE
IE 8 crash when enable "forced_root_block : false"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#672]
Description of problem:
the symptom is that when i enable "forced_root_block : false"
I type the follow text in IE8,it will crash with no error prompt out. I have no choice to kill the process.
{
aaa@aaa     //still work fine
aaa aaa aaa aaa@aaa  //press enter and crash with no error prompt
}

it looks tinymce has problem on handle &ltg;p> and mailto tag in same time
But it works in IE9 or I remove this "forced_root_block : false"

here's is my config:
$().ready(function() {
		$('textarea.risReportEditor').tinymce({
			// Location of TinyMCE script
			script_url : 'jquery/tiny_mce/tiny_mce.js',

			oninit : "postTinyMCEInit",

			force_br_newlines : true,
			force_p_newlines : false,
			forced_root_block : false,
			//convert_newlines_to_brs : true,
			gecko_spellcheck : false,

			table_default_border : 1,

			// General options
			invalid_elements : "a",
			encoding : "xml",		
			theme : "advanced",

Expected result:
ie not crashed
Actual result:
i have no choice to kill it
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5886](http://archive.tinymce.com/develop/bugtracker_view.php?id=5886) posted by [rangeke](http://archive.tinymce.com/profile.php?name=rangeke)_

> _**Tags:** [msie msie8]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
