### ISSUE TITLE
When Click table tool button only  insert option show

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6720]
Hi,
I am using TinyMCE editor. When I click the table icon and insert table option should shown.
**Existing:**
![image](https://user-images.githubusercontent.com/21060460/114027849-72e39a80-9895-11eb-951e-0bac76cc75ac.png)

**I need:**
![image](https://user-images.githubusercontent.com/21060460/114027660-3c0d8480-9895-11eb-8b54-aef08fec5081.png)

If there is any option, please suggest me.

Code: https://codepen.io/venkat5299/pen/GRjpLpa

Thanks

**Comment by SimonFc** [comment]
Hi, there's currently no toolbar button that provides this functionality, only a menu item by the name `inserttable`.
https://www.tiny.cloud/docs/plugins/opensource/table/#toolbarbuttons
https://www.tiny.cloud/docs/plugins/opensource/table/#menuitems

As can be seen in the reply of a similar issue, we do provide the APIs necessary for implementing this though. See https://github.com/tinymce/tinymce/issues/5360#issuecomment-678083829

If you are looking for a pre-defined button I can leave this open as a feature request.

**Comment by Valgeria** [comment]
@SimonFc ,

`If you are looking for a pre-defined button I can leave this open as a feature request.` no thanks.

Thanks for the reference..
