### ISSUE TITLE
Selection API returns empty string when a floated image is present as the last element

### ISSUE THREAD

**Issue by radiantshaw** [tinymce/tinymce#6723]
**What is the current behavior? Describe the bug**

- Visit [TinyMCE Fiddle](https://fiddle.tiny.cloud/59haab) on **Safari**
- Add the following contents through the "Source code" panel
   ```
   <p>Some text to select</p>
   <div class="float_left"><img src="https://images.unsplash.com/photo-1525225120432-e32a514cb0ae?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&amp;ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=1050&amp;q=80" /></div>
   ```
- Open DevTools console and select the TinyMCE frame
- Select some text from the editor
- Execute the following:
   ```js
   tinyMCE.activeEditor.selection.getContent({ format: "text" })
   ```

**What is the expected behavior?**

The executed code should return the selected text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- TinyMCE: Version 5.3.2
- Browser: Safari Version 13.1.2 (13609.3.5.1.5)
- OS: macOS High Sierra Version 10.13.6

**Additional notes**

Removing the `float_left` class from the `<div>` works. This only happens for the CSS property `float`. However, if the CSS is added inline to the `<div>` element, then it works. Another thing is that when the image's width is small, then it behaves correctly. Try setting the width of the image using `style="width: 240px"` and see it working correctly.

On top of the above, this only happens when the image is at the very last (the container `<div>` doesn't matter). Also, it happens only in Safari.

**Comment by prayeshshah** [comment]
@radiantshaw 
I was able to reproduce the issue which you mentioned by updating your fiddle
https://fiddle.tiny.cloud/59haab/4

And as you rightly mentioned, this is only happening on Safari
