### ISSUE TITLE
Plugin development: custom CSS files

### ISSUE THREAD

**Issue by smfukaya** [tinymce/tinymce#6729]
Hi

I was wondering if you could shed some light on how to load external CSS files for a custom plugin for TinyMCE v4.9.11. I'm not referring to styles for the editor contents, but the plugin itself (dialogs, icon, including external javascript libraries CSS files etc.)

I'm using [Yeoman Generator](https://www.tiny.cloud/docs-4x/advanced/yeoman-generator/), but I having trouble to figure out how to load and import CSS files. Hope you can help me.

Best!

**Comment by lnewson** [comment]
Hi @smfukaya,

Firstly, I have to mention that TinyMCE 4 is no longer a supported/developed version of TinyMCE as of the end of last year, see: https://www.tiny.cloud/blog/tinymce-4-support-window/

With that said though, the answer will depend on if you need the CSS loaded for the content or the UI. Just for others that read this I'm going to cover both cases. If it's the content (which you've said it's not), the recommended way to do that is to use the `editor.dom.loadCSS(url)` API in your plugin init code, where URL is path to the CSS that needs to be loaded. If it's the UI, I'm afraid we don't support changing the UI CSS and that is done via skins that apply globally instead to keep a consistent look and feel of the editor.

If you need to load additional JS files though, you can do that using the [`tinymce.ScriptLoader`](https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.scriptloader/) instance to load additional scripts.

**Comment by smfukaya** [comment]
Hi @lnewson,
Thank you very much for your assistance. My doubt was related to the second scenario you described: UI. While I do understand that the look and feel of the editor and its native components should be kept coherent, there are some third party libraries for enhanced components or behavior (like https://github.com/haltu/muuri) that requires some elements to have some classes be defined (an inline style for each element you increase considerably the code and make the maintenance worse) in order to work.
I'm not a 100% sure (it could make debugging a nightmare if one is not aware), but it seems to me that it would be great to inject dynamically these to the webpage hosting TinyMCE if it is using my plugin and my plugin uses it, instead of adding it statically to a skin. Please, let me know if this makes sense.

Best!
