### ISSUE TITLE
I can't find what I'm looking for: demo/inline.md

### ISSUE THREAD

**Issue by bharat55** [tinymce/tinymce#6732]
Can we open the inline editor at fixed position in dom

**Comment by lnewson** [comment]
Hi @bharat55, have you tried the [`fixed_toolbar_container`](https://www.tiny.cloud/docs/configure/editor-appearance/#fixed_toolbar_container) setting? That'll control where the editor toolbar will be rendered in the DOM.

**Comment by bharat55** [comment]
> Hi @bharat55, have you tried the [`fixed_toolbar_container`](https://www.tiny.cloud/docs/configure/editor-appearance/#fixed_toolbar_container) setting? That'll control where the editor toolbar will be rendered in the DOM for inline mode.

**Comment by bharat55** [comment]
Hi @tylerkelly13 , fixed_toolbar_cantainer setting worked, thanks for your help
