### ISSUE TITLE
Opening Autocompleter dynamically from toolbar

### ISSUE THREAD

**Issue by dav-sap** [tinymce/tinymce#6734]
**Is your feature request related to a problem? Please describe.**
I want to provide the option to open the Autocompleter list dynamically from toolbar,
I tried firing many different types of events into the editor but nothing is working.

here is the Fiddler example of what im trying to achieve. in tinymce4 it was possible
https://fiddle.tiny.cloud/M9haab/2

**Comment by lostkeys** [comment]
Hi @dav-sap! To better help us understand the value this would bring to you and other developers and prioritize any efforts on our end, can you elaborate on the use case you're trying to solve?

**Comment by dav-sap** [comment]
yes.
Use case is simple.
We give the option to users to add data to the editor from a list. However its not intuitive for users to understand that if they type some char "$" / "%" etc, the list will pop up. Its much more helpful to have a toolbar option that will pop up that list of data for you.
Instead of writing a whole plugin that shows the same list, with an option to filter some of its data when typing. we just type the char for you and list opens up and you have the exact same behaviour. 

I do believe there is a way to achieve this today as well, I just could not figure it out. in Tinymce 4 after firing some event it worked. However in tinymce 5 any event i try to fire that is not "Enter" key does not work (or does not type in the editor). (see this open issue https://github.com/tinymce/tinymce/issues/6433)

**Comment by lostkeys** [comment]
Thanks for providing more details. However, I'm not convinced that it's the right way to solve this issue. I've observed two more common patterns for this use-case:
1. A regular toolbar menu button with search/filter functionality
1. Have a help text shown on an empty line as shown in the image below
<img width="332" alt="image" src="https://user-images.githubusercontent.com/3122929/116042770-18a55080-a66f-11eb-8b5b-b7182e544d77.png">
Would any of these solve your issue?

**Comment by lucaspontarolo** [comment]
@dav-sap did you find any way to solve this? Im have the same issue here.

**Comment by lucaspontarolo** [comment]
Hi @dav-sap! Try using **keypress** instead of **keydown** 
This works for me
 
Ex: editor.fire('keypress', { keyCode: '52' });

**Comment by dav-sap** [comment]
@lucaspontarolo it worked for me. 
Thanks.
@lostkeys I understand what you are saying however.
1. is duplicate of code, to do a different thing in the toolbar as well.
2. help text is good, but once you have some text in the editor it wont show.

Anyway you can close the issue, @lucaspontarolo solution works, I still think we should have something like this built in.
