### ISSUE TITLE
fullscreen plugin can't fullscreen in framework:  iview 's tab  

### ISSUE THREAD

**Issue by MIKOTO123** [tinymce/tinymce#6735]
**What is the current behavior? Describe the bug**
fullscreen plugin can't fullscreen in framework:  viewui's tab  
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
`      <Tabs size="small">
            <TabPane label="标签一">
                <editor
                    v-model="myValue"
                    :init="init"
                ></editor>
            </TabPane>
            <TabPane label="标签二">标签二的内容</TabPane>
            <TabPane label="标签三">标签三的内容</TabPane>
        </Tabs>
`
**What is the expected behavior?**
normal fullscreen  
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE@5.7.1   view-design/viewui (https://github.com/view-design/ViewUI) @4.4.0

**Comment by MIKOTO123** [comment]
after click fullscreen:
![image](https://user-images.githubusercontent.com/19549093/114545061-149c2a80-9c8e-11eb-9441-3d115e0236c5.png)

**Comment by lostkeys** [comment]
Hello @MIKOTO123. We do not actively support the ViewUI framework, and it's likely some CSS within that framework that is causing issues with the TinyMCE fullscreen mode. In order to help you out you need to provide us with a test case that you made available online that we can inspect and possibly provide you with some tips. I've also marked this as a feature request.

**Comment by MIKOTO123** [comment]
> Hello @MIKOTO123. We do not actively support the ViewUI framework, and it's likely some CSS within that framework that is causing issues with the TinyMCE fullscreen mode. In order to help you out you need to provide us with a test case that you made available online that we can inspect and possibly provide you with some tips. I've also marked this as a feature request.

![image](https://user-images.githubusercontent.com/19549093/114549100-2e8c3c00-9c93-11eb-800f-d1cf95c4df6e.png)
I find this. And I tested style `transform`  can   transform the tinymce's fullscreen `position:fixed` . My English is not good. can your understand

**Comment by lostkeys** [comment]
No, sorry, it's really hard to know what's going on without an actual browser demo to inspect and test on.
