### ISSUE TITLE
Not able to add tracking links

### ISSUE THREAD

**Issue by SimonAl3** [tinymce/tinymce#6738]
I am trying to add tracking links starting <style data-ignore-inlining> before </body>
When I click "ok" the tracking code is being removed  

**Example of Code** 
```
<style data-ignore-inlining>@media (prefers-color-scheme: dark) { #_t::before {content:url('https://oo88tfws.emltrk.com/v2/oo88tfws?rd&i=subjectId');}} @media (prefers-color-scheme: light) { #_t::before {content:url('https://oo88tfws.emltrk.com/v2/oo88tfws?rl&i=subjectId');}} @media print{ #_t {background-image:url('https://oo88tfws.emltrk.com/v2/oo88tfws?p&i=subjectId');}} div.OutlookMessageHeader {background-image:url('https://oo88tfws.emltrk.com/v2/oo88tfws?f&i=subjectId')} table.moz-email-headers-table {background-image:url('https://oo88tfws.emltrk.com/v2/oo88tfws?f&i=subjectId')} blockquote #_t {background-image:url('https://oo88tfws.emltrk.com/v2/oo88tfws?f&i=subjectId')} #MailContainerBody #_t {background-image:url('https://oo88tfws.emltrk.com/v2/oo88tfws?f&i=subjectId')}</style><div id="_t"></div>
<img src="https://oo88tfws.emltrk.com/v2/oo88tfws?i=subjectId" width="1" height="1" border="0" alt="" />
```

**This is what's saved**
```
<div id="_t">&nbsp;</div>
<p><img src="https://oo88tfws.emltrk.com/v2/oo88tfws?i=subjectId" alt="" width="1" height="1" border="0" /></p>
```
Can you give me any advice on how to keep the tracking code at the bottom of the code

**Comment by HAFRMO** [comment]
Hello @SimonAl3 
At this moment TinyMCE does not support the `data-ignore-inlining` attribute. However, you can use the `valid_children` configuration ( https://www.tiny.cloud/docs/configure/content-filtering/#valid_children ) and `extended_valid_elements` configuration ( https://www.tiny.cloud/docs/configure/content-filtering/#extended_valid_elements ) to build the behavior you need.
