### ISSUE TITLE
If I  focused one editor the other editor toolbar (**...**) this option is not expand in resize mode

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6740]
Hi,
I am using TinyMCE. If I  focused one editor the other editor toolbar (**...**) this option is not expand in resize mode.
![image](https://user-images.githubusercontent.com/21060460/114870232-88b50a80-9e15-11eb-8c73-1704819708bc.png)
If there is any option. Please suggest us.
Code: https://fiddle.tiny.cloud/Mqhaab/4
Thanks

**Comment by HAFRMO** [comment]
Hello. I'm not quite sure what the problem you refer to is. I tried the code provided and everything appears to work correctly. Could you perhaps provide further details, or possibly a recording of the issue being demonstrated?
