### ISSUE TITLE
lists_indent_on_tab="false" configuration is not working for numbered lists

### ISSUE THREAD

**Issue by ramchaitanyap** [tinymce/tinymce#6741]
As per doc https://www.tiny.cloud/docs-4x/plugins/lists, we are using lists_indent_on_tab="false" configuration on numbered lists for version 4.3

Steps:
-Use https://fiddle.tiny.cloud/R9haab
-Give numbered list like
1.a
2.b
-Press tab

Actual: See that focus is still in numbered list
Expected: Focus should go to button sample

**Comment by MichaelFromin** [comment]
TinyMCE 4.x is no longer a developed/supported version of TinyMCE.  Testing thin is TinyMCE 5 (the supported release) the editor does not have this issue.

**Comment by ghost** [comment]
We are currently using TinyMCE version 7.9.1 (2025-05-29) and seeing the same behavior: 
`list_indent_on_tab: false`  has no effect at all.
The (bad) behavior is identical inside and outside of tables.
We have to turn it off, so that the tab navigation in tables works like for normal elements.
