### ISSUE TITLE
add custom classes in table properties ( Like striped table, no border, only bottom border ) in it.

### ISSUE THREAD

**Issue by hafizjavaid** [tinymce/tinymce#6745]
Hi, I'm using the free version of TinyMCE and I want to add new class properties to the table. I tried according to the documentation and even these are adding in table properties but these are not working. Let me show what I mean
I want to have strippe
![uR85t](https://user-images.githubusercontent.com/49143414/115143498-22bcc300-a061-11eb-944d-33e95d05192a.png)

Here you can these are adding but not working when I try to apply them. 
Thanks!!!

**Comment by lostkeys** [comment]
Hi @hafizjavaid. I'm sorry, you need to explain more what steps you have done, preferably by replicating your issue in a [TinyMCE Fiddle](https://fiddle.tiny.cloud).

**Comment by hafizjavaid** [comment]
Hi @lostkeys, I'm using TinyMCE with vuejs. Like the code, I did in the init function adding classes. So when I try to style them using CSS. It's working on preview ( When we click on the eye icon ). But these classes are not applying to live preview.
[Code](https://fiddle.tiny.cloud/)

**Comment by lostkeys** [comment]
I'm not sure I understand, but in general you need to check the following:
1. Configure TinyMCE with the classes you want end-users to pick from using class list options, for example [table_row_class_list](https://www.tiny.cloud/docs/plugins/opensource/table/#table_class_list)
2. Make sure you have the classes defined in your content's css, for example by using [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_css). This will make the styles show up inside the editor
3. To have the styles show up outside of the editor, if you are using TinyMCE in a blog or CMS, you also need the same classes defined in your front-end's CSS.

**Comment by hafizjavaid** [comment]
Hi @lostkeys, I understand I'll try this content_css property. Hope so it will work.
