### ISSUE TITLE
How do I change a skin dynamically?

### ISSUE THREAD

**Issue by joaowall88** [tinymce/tinymce#6748]
How do I change the skin of tinyMCE dynamically when changing the theme of my app?

Currently the solution I found was to destroy tinyMCE and init it again.

I would like to know if there is any better way to do this.

**Comment by lostkeys** [comment]
@agcardume It depends on what you want to do. Please elaborate on what you want to achieve and we can see if we can point you in the right direction...

**Comment by lostkeys** [comment]
Hi @BlueManCZ! Not with the existing skins, but you can create a new custom skin and combine the light and dark ones into one and use mediaquery to switch between light and dark. We don't do that by default because it's not something everyone would like to do.
