### ISSUE TITLE
BUG with the display of Text and background color pickers

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#675]
Description of problem:

Steps to reproduce:
1.Add Text in the text area
2.Now click the text color button
3.Select Text color
4.Now while the TextColor picker is open click background color button
5.Both the color pickers are displayed...
6.Also when we click in the text area both the color pickers must be hidden.

Expected result:when clicked else where the color picker must be hidden

Actual result:the color pickers are both displayed at the same time
I have attached the image of what i got to see. Observed this in IE8 and Firefox.. OS: windows 7(64-bit)
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5889](http://archive.tinymce.com/develop/bugtracker_view.php?id=5889) posted by [Sreedevi](http://archive.tinymce.com/profile.php?name=Sreedevi)_

> _**Tags:** [firefox msie msie8 color pickers 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
