### ISSUE TITLE
toolbar：The same width版本:vue3/tinymce^5.7.1 配置:{inline: true} 内联模式:工具栏(toolbar)宽度不能随父元素宽度。

### ISSUE THREAD

**Issue by delete-rain** [tinymce/tinymce#6752]
**What is the current behavior? Describe the bug**
内联模式{inline: true}，工具栏(toolbar)宽度不能跟随父元素宽度。
tinymce.init(init)初始化无效

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
sry

**What is the expected behavior?**
   hope： The same width

   now:
▕￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣▏
▕ toolbar, toolbar, toolbar....                                                    ▏
▕_________________________________________________▏

▕￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣▏
▕ father div ..... content.......edit    ▏
▕____________________________▏

   hope:
▕￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣▏
▕ toolbar, toolbar, toolbar....           ▏
▕____________________________▏

▕￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣▏
▕ father div ..... content.......edit    ▏
▕____________________________▏

  PS:understand？
       I have given my full play。
       I'm sorry, my English teacher。
       I like English ... I'm sure...  very much  ...but ,,,you konw.........
       Please help me。    Please！

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
版本:vue3/tinymce^5.7.1 配置:{inline: true}

**Comment by techtangents** [comment]
Does this help?

https://fiddle.tiny.cloud/zAhaab

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
