### ISSUE TITLE
Document TinyMCE 4 spellchecker plugin request/response API

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#676]
Description of problem:
There is no ay documentation about new spellchecker APU (request/response structure)

Steps to reproduce:
1. Enable spellchecker plugin
2. define spellchecker-rpc_url
3. try to perform spellcheck

Expected result:
==> old implementations will fail, since request structure is changed

Actual result:
Documentation about request/response should be available

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5890](http://archive.tinymce.com/develop/bugtracker_view.php?id=5890) posted by [Andreaz](http://archive.tinymce.com/profile.php?name=Andreaz)_
> 
> _**Tags:** [spellchecker 4x documentation]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
There are spellchecker docs here: https://www.tinymce.com/docs/plugins/spellchecker/
