### ISSUE TITLE
Wordpress load TinyMCE error script

### ISSUE THREAD

**Issue by phongdatgl** [tinymce/tinymce#6760]
**Is your feature request related to a problem? Please describe.**
I use Wordpress, in Post edit page, i can not load js from CDN TinyMCE. Bug below:

`tinymce.min.js?ver=4960-20190918:2 GET https://cdn.tinymce.com/4/plugins/table/plugin.min.js?wp-mce-4960-20190918 net::ERR_ABORTED 403`

I found tinymce.min.js in here: wp-includes/js/tinymce/tinymce.min.js

**Comment by MichaelFromin** [comment]
You are trying to use a CDN that was decommissioned.  We have a few articles from the past 6 months outlining what happened and how to address:

https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
https://www.tiny.cloud/blog/announcement-decommissioning-cdn-tinymce-com
https://www.tiny.cloud/blog/tinymce-cdn-reminder

You will need to modify whatever plugin or capability is pointing to the decommissioned CDN to a new location to pull TinyMCE.  Alternatives are referenced in those articles.
