### ISSUE TITLE
Inject your own window and document instance into the editor

### ISSUE THREAD

**Issue by pvrobays** [tinymce/tinymce#6765]
This is a follow-up feature of #6559, for a very specific scenario.

**Is your feature request related to a problem? Please describe.**
Yes. Let me first define our use case. It is a multi-monitor web application via electron. This means we'll have electron open a window for each of your monitors of your multi-monitor setup. Each window registers its 'js window' instance to one main 'js window' instance. This way the 'main' window has a references to all other window instances. The main window will render the UI of all the registered windows.

When we create a tinymce editor on a non-main window, some features (like formatting) won't work.
This is because when an (inline-)editor is created, its window reference will be set to the window that creates it. This instance will be passed to the selection instance of the editor. Once formatting commands are triggered, tinymce will use the `window.getSelection()` to get the selected nodes. In our use case this of course get the selection of the wrong window.

**Describe the solution you'd like**
Add 2 new settings:
- customWindow
- customDocument

These should replace the editor's `contentWindow` and `contentDocument`.

Btw @metricjs: As you predicted, there are some functionality issues with the way we use tinymce :)
The above solution solves them though.

**Describe alternatives you've considered**
Inject different window/document instances after the editor has been created. This is however a bit cumbersome as after the creation of the editor, the window dependency has already been referenced in multiple places.

**Comment by lnewson** [comment]
Hi @pvrobays,

Thanks for the Feature Request and PR, however we've decided to decline this request. As we mentioned last time, handling cross-frame logic can get very tricky, especially when rendering UI components. It's also a large overhead to try to maintain and continually test against it.

As such, after discussing this internally, at this stage we have no plans to support rendering or editing an element that is in another window/frame. We'd instead suggest loading TinyMCE in the frame where you need to edit the content if that behaviour is needed.
