### ISSUE TITLE
Newline after the table cannot be removed when pressing backspace.

### ISSUE THREAD

**Issue by KhurramShehzadd** [tinymce/tinymce#6769]
When we insert a table in tinymce editor, and try to add some text after the table. Now, if we want to remove the text after table it will be removed using backspace, but empty line after table is still there. We are facing this issue with v5.7.1 and it was working fine in version 4. 

Expected:  
The empty line after the table should be removed when pressing backspace key. 

TinyMCE Version: 5.7.1, Browser: Google Chrome v90.0.4430.93, Windows 10

**Comment by HAFRMO** [comment]
Hello. I attempted to replicate the issue, but I am getting the same behavior in both 4 and 5, though you said it works in 4, so I would like to clarify the details with you. The issue is that there is a newline after the table after you attempt to delete what was added afterwards?

**Comment by KhurramShehzadd** [comment]
Hi, 

The empty line after the table is the problem. To produce this, you can use my steps to replicate this issue. 

Try to add some text after the table. 
Now, if we want to remove the text after table it will be removed using backspace, but empty line after table is still there.
That empty line cannot be removed using backspace. 

The additional line shouldn't be there, as user don't want it and want to remove but it's not working.
Hope that helps, let me know if you need additional information.

**Comment by KhurramShehzadd** [comment]
Hi @HAFRMO, 

I'm still seeing a label 'needs: more info'. Please refer to my comment above and let me know if you still needs any information.

**Comment by MattMadness** [comment]
I am also having this same issue with version 6. 

![20220828_144122](https://user-images.githubusercontent.com/55710660/187292287-52ad8def-6274-4dd7-a374-c709bbde38ae.jpg)

Will follow up with HTML that demonstrates the issue.
