### ISSUE TITLE
position of cursor after click on save button

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#678]
I don't understand, whay is cursor position after click on save button on start of line.

I will write  plugin for autosave, but if I use trigger on mceSave event -> cursor is on start of line.

Please help
--
Sorry for my bad english
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5892](http://archive.tinymce.com/develop/bugtracker_view.php?id=5892) posted by [houba](http://archive.tinymce.com/profile.php?name=houba)_

> _**Tags:** [firefox msie safari chrome opera save inline editting tinymce_40b3_jquery]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
