### ISSUE TITLE
stylesheet is undefined in loader so inline blows up

### ISSUE THREAD

**Issue by solomon23** [tinymce/tinymce#6785]
**What is the current behavior? Describe the bug**

https://github.com/tinymce/tinymce/blob/9b6047b0c668e9404fbc92f8d649e73dacc4b054/modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts#L125

i'm trying to set this up with angular 

```
<editor
    [inline]="true"
    [init]="{ menubar: false}"
  ></editor>
```

sometimes it works and stylesheets will be a full array but often it's undefined and then it throws a script error

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by seawave23** [comment]
Any news here? We have the same problem.

**Comment by TheSpyder** [comment]
We're working on a migration to strict mode TypeScript (#7925, #7927) so hopefully that helps. Although it isn't marked as nullable in the [spec](https://developer.mozilla.org/en-US/docs/Web/API/Document/styleSheets).

Given that the code should only run in a `link` tag onload event, I'm surprised it can ever be undefined.

**Comment by lnewson** [comment]
For anyone running into this issue, can you please include a replication case and information on what browsers you're using? As mentioned above this shouldn't be nullable.

**Comment by seawave23** [comment]
I was trying to create a replication, but there's an issue an stackblitz that scripts can't be downloaded, like the tinymce.min.js. So no way there unfortunately.

But maybe the environment information helps a bit:
We have an Angular 14.0.3 application, using Tinymce editor with tinymce/tinymce-angular package in version 6.0.1 and tinymce 6.0.3. Setup is exactly as described here: https://www.tiny.cloud/docs/integrations/angular/, and we wrapped the editor into a custom component, that we don't have to pass the config on every place of usage.

Is there any idea of what we could try to fix that behaviour? The stylesheets property seems to be loaded from document, which can be of type Document | ShadowRoot. Are the stylesheets somewhere rewritten/adapted inside of tinymce, or might it have to do with the way how Angular loads stylesheets?

**Comment by seawave23** [comment]
Any more ideas? What we found so far is an inconsistency between proposed tinymce solutions here: [tiny-cloud](https://www.tiny.cloud/docs/tinymce/6/angular-pm/) and here: [npm/tinymce-angular](https://www.npmjs.com/package/@tinymce/tinymce-angular)  - the one says that tinymce with tinymce-angular should be version 6.0.0, the other 5.0.0. Could it be that with 5.0.0, it works?
