### ISSUE TITLE
when valid_elements and valid_classes enabled,media video lost width and height

### ISSUE THREAD

**Issue by gebaiwan** [tinymce/tinymce#6809]
**What is the current behavior? Describe the bug**
when valid_elements and valid_classes enabled,plugins media video lost width and height attrs
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
```javascript
plugins:['media'],
toolbar:'media',
valid_elements : 'a[href|title|target|rel],blockquote,br,code,div[class|style],figure[class],figcaption,h3[class],h4[class],h5[class],img[class|style|width|height|alt|src],li[class],ol,p[class|style],pre,source[src|type],strong[class],span[class|style],table[class|style],tr[style],th[style],td[style],ul[style],video[controls=controls|width|height|style|src|type|poster|preload]',
valid_classes: 'attachment blockquote code dirty-word font-bold forecolor h-title hilitecolor image language-php language-markup language-javascript language-css language-python language-java language-c language-csharp language-cpp pre sub sup table table-sm table-bordered tag text-left text-center text-right text-justify text-italic text-underline text-across',
```
**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
v:Self-hosted / Community 5.8.0
browser:chrome
OS:windows10

fiddle.tiny.cloud screen shot:
![Snipaste_2021-05-10_16-20-43](https://user-images.githubusercontent.com/34265145/117628643-f69de900-b1ab-11eb-8e8d-3a04a2eb5d26.jpg)

**Comment by Cordemans** [comment]
same problem here with iframes. using it with valid_classes will strip the width and height attributes.
