### ISSUE TITLE
Add/Delete Image upload from editor

### ISSUE THREAD

**Issue by abdulmalik-DA** [tinymce/tinymce#6810]
I am using **images_upload_handler** to upload an image to the server, which return json response containing **primary key** and **location** of the image. So if I somehow persist **primary key** to the html content we can delete the image from server by comparing old version of the content.

Possible Solution:
 if **images_upload_handler** along with these arguments( blobInfo, success, failure, progress ), also pass nodeReference to that **img** node, then we can set our attributes to it and delete according to it.

References
https://www.tiny.cloud/docs/general-configuration-guide/upload-images/#imageuploaderrequirements
https://stackoverflow.com/questions/66422288/in-tinymce-how-do-you-deal-with-images-uploaded-to-the-server-and-then-deleted-i

**Comment by gebaiwan** [comment]
我可以给你点思路，抱歉，英文比较差，所以中文写了。
单纯编辑器来实现这一点我觉得几乎是不可能的，这是一个联动的过程。
1、数据库中设计一个图片表
2、上传图片成功后，从后端传过来的图片地址URL可以附带数据库键（加密主键或UUID之类的），如 x.jpg?=abcd_key 或者 getimg/abcd_key
3、内容保存之前，后端分析内容后提取图片主键
4、建立内容和图片之间的关联表，同时更新图片被关联的总数
5、清理被关联总和为0的图片（立即或事件触发或定时）

**Comment by abdulmalik-DA** [comment]
Backend cannot analyze the content without primary key associated to the url, e.g. 
`<img src="http://yourserver.com/uploaded_file.jpg" data-id="2" />`
 Now backend can easily match with database and compare with the old content to delete what is not required. But to add data-id it would require node that trigger **images_upload_handler**. Like **paste_postprocess** in **paste** plugin.

**Comment by lostkeys** [comment]
I'm removing the feature label so that our engineers don't think this feature has been handled already.
