### ISSUE TITLE
There is no way to add an accessible name on the tinyMCE Textarea or the body tag with the contenteditable="true" attribute on it

### ISSUE THREAD

**Issue by Sparkles08** [tinymce/tinymce#6839]
The iFrame that contains the contenteditable="true" attribute on the body tag doesn’t have an accessible name, and there is no way to add an accessible name. A placeholder text is not an accessible name. 

I am seeing that tinyMCE code adds the style "display:none" and aria-hidden=true to the textarea, therefore there is no way to add or give an accessible name to the tinyMCE textarea (or body tag that has the contenteditable=true property) on it. How about having the textarea have a style of "visuallyHidden" so it will still be in the DOM, and remove the aria-hidden="true", then an aria-label or a visually hidden label could be associated to the textarea and therefore screen readers would be able to pick up the accessible name of the textarea.

And on the iFrame, body tag, add a role="textarea", tabindex="0", aria-label="writing area".

**Describe alternatives you've considered**
I've tried the above but the style "display:none" and aria-hidden="true" removes the textarea from the DOM, therefore trying to associate a label to the textarea doesn't work. And you can't associate a proper label to a body tag because a body tag is not a form item.

**Comment by lostkeys** [comment]
I'm removing the feature label so that our engineers don't think this feature has been handled already.

**Comment by brichwin** [comment]
I've been labeling the TinyMCE editor using a callback in the tinymce.init call:

```js
tinymce.init({
  // other config items,
  init_instance_callback: function(editor) {
    editor.getContainer().setAttribute('aria-label', 'This is editor one.')     // NVDA reads this label
    editor.getBody().setAttribute('aria-label', 'Edit me here');   // JAWS and VoiceOver read this label
  }
});
```

JAWS and VoiceOver see the label applied to the body element in the iframe. The document body is found by calling ``editor.getBody()``. For example, in the JAWS "Select a Form Field" dialog, the label on the body element will appear after the toolbar buttons.

Unfortunately, NVDA will not list controls inside the div[role="application"] that is the editor's container. When reading down  a page with NVDA, the tinyMCE editor shows up as "application clickable" by default. It's speaking that when it hits the container div that has the role="application" on it. Putting an aria-label on that div will make NVDA speak "application clickable <aria-label text>". The div[role=application] can be found with ``editor.getContainer()``. However this label will not show up in any of NVDA's finding aids. 

Thus, to make it easy to find the editor in NVDA, it's best to also wrap it in a landmark with an appropriate label. Do this along with the above aria-labels. A region landmark with an aria-label seems best (See: https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/region.html). To wrap the editor in a landmark, do something like this:
```xml
<body>
  <h1>Question 1</h1>
  <p>Write a short essay about your summer vacation.</p>
  <div role="region" aria-label="Response for Question 1">
    <form method="post">
      <textarea id="mytextarea">Hello, World!</textarea>
    </form>
  </div>
</body>
```

The landmark can be navigated too with screen-reader hotkeys and discovered in a list of landmarks (also known as regions). It seems to be the only way to have a NVDA reader locate it. It is also useful for users of any of the other modern screen-reading programs.

Hope this helps!

**Comment by brichwin** [comment]
And, oh... you don't want to expose the original textarea or screen-reading software will let users edit it. It's totally correct that tinyMCE adds the style "display:none" and aria-hidden=true to the original textarea. You want the user to navigate to the editable DOM content inside the iframe not the original textarea.
