### ISSUE TITLE
Can't select "heading x" when a p block contains br tag in V3.5.8

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#684]
Description of problem:

 Within a p block like following
&ltg;p>
line1&ltg;br />
line2&ltg;br />
line3&ltg;br />
&ltg;/p>

when select line1 (or other line) and select drop menu, for example "Heading 1",
the block not be taged by h1, just only delete a br tag that gives the result as following.

&ltg;p>
line1line2&ltg;br>
line3&ltg;br>
&ltg;/p>

 By the way, this occurs after 3.5.7, before that the result is like following(also v4.0).
 
&ltg;h1>
line1&ltg;br />
line2&ltg;br />
line3&ltg;br />
&ltg;/h1>

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5898](http://archive.tinymce.com/develop/bugtracker_view.php?id=5898) posted by [wce01](http://archive.tinymce.com/profile.php?name=wce01)_

> _**Tags:** [msie msie7 msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
