### ISSUE TITLE
Issue with table borders when trying to export PDF

### ISSUE THREAD

**Issue by HikeGrig** [tinymce/tinymce#6858]
**Issues with table borders when trying to export PDF**

I want to generate pdf file which contains tables via export plugin, but there are issue related table vertical borders
Here is example [codesandbox.io](https://codepen.io/HikeGrig/pen/eYvgPrW).

**Comment by lnewson** [comment]
Hi, thanks for the report. Export is a premium product, so I'm afraid we can't assist via GitHub. If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new

I will note however, that we are already aware of some issues with Export 1.0.0 and there's a fix coming soon.
