### ISSUE TITLE
please helppppppp.using explorer copy past  to the editor it crashed sometimes.i am pasting images or tables from the web or from office and explorer crash.please help

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#687]
Description of problem:

Steps to reproduce:
1.
2.
3.
4.
5.

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5901](http://archive.tinymce.com/develop/bugtracker_view.php?id=5901) posted by [alon0000](http://archive.tinymce.com/profile.php?name=alon0000)_

> _**Tags:** [msie msie8 msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
