### ISSUE TITLE
Inline Edition of elements in iFrame doesn't work

### ISSUE THREAD

**Issue by kronsilds** [tinymce/tinymce#6870]
**What is the current behavior? Describe the bug**
The TinyMCE Editor, initialized on a element placed into an iFrame, can't apply correctly any formatting to any selected text and keeps inserting on each formatting action a P tag at the beginning of the element with a span in it like so:
`<p><span id="_mce_caret" data-mce-bogus="1" data-mce-type="format-caret"><strong>?</strong></span></p>`

Here's the fiddle to reproduce the problem:
[https://fiddle.tiny.cloud/tEhaab/2](https://fiddle.tiny.cloud/tEhaab/2)

**What is the expected behavior?**
The Editor should apply the formatting to the selected text

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested with last version of TinyMCE on chrome 90 / windows 10

**Comment by krishnaeverestengineering** [comment]
I am also having similar issue. Badly need solution to upgrade from version 4 to 5. I am using tinymce inside iframe element. So it is another document element using tinymce. But I faced issue with <DOCTYPE>. Is somebody out there to help with it?

**Comment by Cordemans** [comment]
I'm also experiencing the same issue with an inline tinymce editor inside an iframe.
Backspace does not work. Return key adds paragraphs to the top. None of the buttons work.

**Comment by krishnaeverestengineering** [comment]
> I'm also experiencing the same issue with an inline tinymce editor inside an iframe.
> Backspace does not work. Return key adds paragraphs to the top. None of the buttons work.

Hey, latest grapes version should fix this. Now we can add Iframe doctype so that tinymce should work

**Comment by Cordemans** [comment]
Unfortunately it does not work for me. 

For example try selecting text and making it bold. Or pressing enter or backspace.
[https://fiddle.tiny.cloud/tEhaab/4](https://fiddle.tiny.cloud/tEhaab/4)

**Comment by omanizer** [comment]
I've also run into this.  If I load tinymce within the iframe and instantiate then it works fine but I cannot target elements in the iframe DOM from the parent frame and have it work.  It *almost* works.

Here's another example (if it helps):
https://codepen.io/ohmance/pen/dyWrrrZ

**Comment by omanizer** [comment]
I just gave this a shot and it worked and should accomplish what I need (in case it helps anyone else).  My primary need is the ability to initialize and access the instance from the parent frame toward a DOM element in the child iframe.  It does involve adding the tinymce script to the child frame, which unfortunately requires an internet connection to access and won't be bundled into my webpack generated code, but it's likely possible to use a loader and pass all of that into the srcdoc instead of using a script[src] method.

https://codepen.io/ohmance/pen/OJmqGje
