### ISSUE TITLE
Add a placeholder for urlinput

### ISSUE THREAD

**Issue by hugsbrugs** [tinymce/tinymce#6878]
I would like to be able to add a placeholder on urlinput fields to give user more informations on expected data.
This option is available for input and textarea fields but not for urlinput ! 
Is there any reason for that ?

I have tried to add it without success : 

```
interface UrlInputSpec extends FormComponentWithLabelSpec {
    type: 'urlinput';
    placeholder?: string;
    filetype?: 'image' | 'media' | 'file';
    disabled?: boolean;
}
```

**Comment by EkimChau** [comment]
Hi hugsbrugs, 

TinyMCE will accept this feature request.  Currently we have no time frames on when this will become available and will be prioritised with our backlog of requests.

Thanks for posting :)
