### ISSUE TITLE
Uncaught TypeError when adding / editing image

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#688]
When using the newest version of the Moxiemanager plugin with TinyMCE 4.0b3, a javascript error shows when opening the Moxiemanager dialog.

Uncaught TypeError: Object function (el, nocash, doc){
			if (el && el.$family && el.uid) return el;
			var type = typeOf(el);
			return (types[type]) ? types[type](el, nocash, doc || document) : null;
		} has no method 'indexOf' tinymce.min.js:9
(anonymous function) tinymce.min.js:9
e.extend.fire tinymce.min.js:7
e tinymce.min.js:7
i tinymce.min.js:2
m tinymce.min.js:2

Steps to reproduce:
1. Set up TinyMCE with Moxiemanager plugin
2. Click the insert/edit image icon
3. Click browse

Expected result:
Dialog opens, no javascript error

Actual result:
Dialog opens, but with a javascript error.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5902](http://archive.tinymce.com/develop/bugtracker_view.php?id=5902) posted by [MCActive](http://archive.tinymce.com/profile.php?name=MCActive)_

> _**Tags:** [firefox msie safari chrome opera typeerror moxiemanager javascript]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
