### ISSUE TITLE
'urlconverter_callback' and 'paste_postprocess' do not support asynchronous actions

### ISSUE THREAD

**Issue by cloydlau** [tinymce/tinymce#6882]
**Is your feature request related to a problem? Please describe.**

Hello, I found that `urlconverter_callback` and `paste_postprocess` option do not support asynchronous actions.

Error occurred when adding `async` keyword to `urlconverter_callback`:
```
tinymce.js?4651:3881 Uncaught (in promise) TypeError: text.replace is not a function
    at encodeRaw (tinymce.js?4651:3881)
```

`paste_postprocess` accepts `async` keyword but making asynchronous changes to dom is invalid.

```
paste_postprocess: async (pluginApi, data)=> {
  // invalid, data.node stay unchanged
  const res = await fetch('')
  const additionalNode = document.createElement('div')
  additionalNode.innerHTML = '<p>This will go before the pasted content.</p>'
  data.node.insertBefore(additionalNode, data.node.firstElementChild)
},
```

**Describe the solution you'd like**

Supporting `async` keyword or providing callback function.

**Comment by lostkeys** [comment]
I'm removing the feature label so that our engineers don't think this feature has been managed already.
