### ISSUE TITLE
Table size to fit the width of the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#689]
When adding a table, it is sized to the minimum in the editor. I first have to re-size it before I can do anything with it. This isn't convenient. 

I would expect the table to be sized to fit the width of the editor.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5903](http://archive.tinymce.com/develop/bugtracker_view.php?id=5903) posted by [mxpkr](http://archive.tinymce.com/profile.php?name=mxpkr)_
> 
> _**Tags:** [firefox msie safari chrome opera table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
