### ISSUE TITLE
heading change

### ISSUE THREAD

**Issue by gb-lilin** [tinymce/tinymce#6898]
**What is the current behavior? Describe the bug**
![image](https://user-images.githubusercontent.com/51564295/120638251-7a44b000-c4a2-11eb-8eb5-12a49e4c8dd3.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

![image](https://user-images.githubusercontent.com/51564295/120638477-bed04b80-c4a2-11eb-890f-7f75d789246c.png)
what i write didn't work
**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/51564295/120638217-6ef18480-c4a2-11eb-94eb-02ef38f61fb7.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**![image](https://user-images.githubusercontent.com/51564295/120638390-a19b7d00-c4a2-11eb-8a83-7a3482a96be9.png)

**Comment by gb-lilin** [comment]
I don't konw why didn't work ,Looking forward to your reply

**Comment by lostkeys** [comment]
Hi @gb-lilin. The menu reflects the CSS you have associated with the elements so you should first check what styles you are applying to the H1-H6.

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
