### ISSUE TITLE
crash chrome/explorer with html entity without space after

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#690]
Description of problem:

Steps to reproduce:
1.in the initial configuration it works
2.delete the last space in the string 'E &lt; A.' ('E &lt;A.')
3.run

Expected result:
show tinymce

Actual result:
crash browser
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5904](http://archive.tinymce.com/develop/bugtracker_view.php?id=5904) posted by [2000000](http://archive.tinymce.com/profile.php?name=2000000)_

> _**Tags:** [msie chrome msie7 msie8 msie9 msie10 chrome10 chrome11 chrome12 chrome13 crash html entity space]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/mhdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
