### ISSUE TITLE
IE10 lost selected on custom buttons

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#691]
Description of problem:

IE 10

Steps to reproduce:
1. Select word
2. Click on "B" button

Expected result: word is bold and selected

Actual result: cursor moved to start

Click on "button", "input", "a[href]" works as expected. "Label", "span" and other - lost focus

Workaround - getBookmark on mousedown, and restoreBookmark before operation
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5905](http://archive.tinymce.com/develop/bugtracker_view.php?id=5905) posted by [neex](http://archive.tinymce.com/profile.php?name=neex)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/nhdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
