### ISSUE TITLE
Table toolbar is covering text inside

### ISSUE THREAD

**Issue by mateuszwitkowski** [tinymce/tinymce#6919]
**What is the current behavior? Describe the bug**
1. Insert a table with two columns and a few rows.
2. Make table narrow (~250px).
3. Focus on the first row.
4. Typed text is covered by a table toolbar (especially in the second column).

**What is the expected behavior?**
Toolbar should be positioned below the focused row so the content is visible.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Chrome/FF/Safari
5.8.1

**Comment by lostkeys** [comment]
Hi @mateuszwitkowski! We have an upcoming fix for this issue planned for an upcoming release.

**Comment by lostkeys** [comment]
Hey @mateuszwitkowski, the issue with the table context toolbar was fixed with TinyMCE 5.9 released yesterday.
