### ISSUE TITLE
Auto unselecting toolbar group buttons

### ISSUE THREAD

**Issue by DamianOczkowski** [tinymce/tinymce#6922]
Hello everyone, 
I found a problem with the toolbar in tinymce-angular editor. When I select all options in toolbar group:

![2021-06-07_21h20_14](https://user-images.githubusercontent.com/46203478/121076099-49cc8100-c7d6-11eb-8c94-10bb85910d7b.png)
 
And the next, when I try unselect for example "bold" or other options in group, all options in group becomes unselected:

![2021-06-07_21h24_16](https://user-images.githubusercontent.com/46203478/121076486-c65f5f80-c7d6-11eb-9eb1-a2941898c75c.png)

It seems obvious, that the option that user currently unselect, should be unselected

error occurs on: 
Chrome: 90.0.4430.212
Firefox: 89.0 
Opera: 76.0.4017.177

env. params:

tinymce-angular: 4.2.4
angular/core: 11.2.6,

**Comment by 779102260** [comment]
anybody fixed it ?
