### ISSUE TITLE
[MCE4] Text from Word disappears

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#693]
Description of problem:

Line with text from a Word file disappears. When pasting in to notepad and than copying it does work..

Steps to reproduce:
1. Copy (ctrl + v) text from Word File
2. Paste Text in TinyMCE (ctrl + v)

Expected result:

Text as in Word file in TinyMCE editor

Actual result:

Line with P.S. does not show up..
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5907](http://archive.tinymce.com/develop/bugtracker_view.php?id=5907) posted by [MCActive](http://archive.tinymce.com/profile.php?name=MCActive)_

> _**Tags:** [firefox msie safari chrome opera 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
