### ISSUE TITLE
Bullet points and numbered lists can’t be realigned

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#6938]
**What is the current behavior? Describe the bug**
Bullet points and numbered lists can’t be aligned using alignment buttons. They stay left aligned for LTR and right aligned for RTL.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Add a list using the bullet/numbered list button
2. Click the alignment buttons to change the position of the lists

Expected result: Text and list indicator are aligned accordingly
Actual result: Only text is aligned, indicators stays at the left for LTR and at the right for RTL

**What is the expected behavior?**
Text and list indicator are aligned accordingly

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.3.2

**Comment by anders-kaffia** [comment]
As far as I know this is expected browser behavior. I've created a CSS workaround for this. Here is a CodePen: [Centered list styling](https://codepen.io/anders-kaffia/pen/XWRoVRY)
