### ISSUE TITLE
Text formattting is not working for "editor.selection.getContent()".

### ISSUE THREAD

**Issue by sadashivm** [tinymce/tinymce#6954]
Hello Team,
The applied background style is not applying to the parent HTML tag, in the below example I've applied background color to the entire line when I console that line, it is printed only the text.

![image](https://user-images.githubusercontent.com/10355473/122706121-d1090280-d274-11eb-85f7-3dfc97b7d2c1.png)

And the console is,
![image](https://user-images.githubusercontent.com/10355473/122706137-df571e80-d274-11eb-9798-0ba4f2ec1874.png)

When I checked the source code, the background style is present,
![image](https://user-images.githubusercontent.com/10355473/122706245-1decd900-d275-11eb-8643-d99dae1a6768.png)

However, If I applied background color to some of the text then it is working like,
![image](https://user-images.githubusercontent.com/10355473/122706442-95226d00-d275-11eb-88cd-88170228c4b8.png)

And the console is,
![image](https://user-images.githubusercontent.com/10355473/122706525-c69b3880-d275-11eb-8f11-2b0ba892268f.png)

Could you please tell me the solution?

**Comment by JamesToohey** [comment]
Hi, thanks for reporting this, I tried to replicate this with no luck. It's possible it's something different or unique with your TinyMCE configuration or how you are retrieving the content.

Could you please create a reproduction case in a [TinyMCE Fiddle](http://fiddle.tinymce.com/)?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
