### ISSUE TITLE
How to pass parameters to plugins OR openUrl() in fullscreen?

### ISSUE THREAD

**Issue by YvesR** [tinymce/tinymce#6956]
**Is your feature request related to a problem? Please describe.**
There is a `codemirror` plugin for tinymce. It works fine with version 4 and 5.

However in version 5 it shows an error
https://gitlab.com/tinymce-plugins/tinymce-codemirror/blob/master/plugins/codemirror/plugin.js#L90
that should pass configuration to the target souce.html.
I tried to find a solution here but did not manage to make it work.

As the current plugin is not updated since a year or more id like to modify myself, but what is the best approach here?
The dialog should be in *fullscreen*. In the past the codemirror plugin handled this, but it should also work remove the functionality there and auto resize dialog to fullscreen.

Any idea or help here? Thanks in advance.

**Comment by EkimChau** [comment]
Hi YvesR, 

We have considered full screen mode for TinyMCE's code editor however being a rich text editor and not a source code editor we have decided not to proceed with full screen support for now.  Currently our dialogs do not support fullscreen mode.

Can you tell us a bit more about your use case that requires fullscreen source code editing and how your users depend on the Source Code plugin please list (eg. make light corrections, implement something unsupported)

Additionally about your users, are they generally more technically inclined and prefer to be in control of the source code? 

Your feedback will help shape our roadmap for the source code plugin

regards

TinyMCE product team

**Comment by YvesR** [comment]
Hello,
the use case was/is to create the same environment while migrating to newest version. I was checking any plugin that is not available by default.

The `codemirror` plugin is used to show `html-source` with syntax highlighting and it does the job pretty well. However the source was opened in full screen mode. 
Many of our users (the more professional ones) use to view html source code do edit for something special or view created results.

Now I just set it to max window with minus some padding, so from my perspective I am fine with the current situation.

Thanks and bye Yves
