### ISSUE TITLE
MS Pinyin (Chinese) Issue with tinyMCE editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#696]
Description of problem:

I have a XUL application with a page which contains an html editor. I'm using the tinyMCE editor in my XUL application. This application need to support Chinese language.

My client uses the MS Pinyin (http://www.pinyinjoe.com/windows-7/win7-chinese-intro.htm) to input the data in the editor. When I start typing in the editor, the Pinyin window will be poped up automatically so that I can choose words from it. But, this has a problem if you follow the below steps:

1. Keep on typing the Chinese text without pressing the ENTER key. As you type-in, the Pinyin will be shown underneath the line where you are typing now
2. But, when the cursor comes to the second line, the Pinyin popup will be shown exactly on top of the second line where we are typing now which will hide the second line

I thought that this is a XUL-specific case. But, now I have some strong reasons to believe that that this is a tinyMCE issue:

1. When MCE is used in IE, the Pinyin dialog will always be displaying under the current cursor position and moves as we type-in. In FF, this will be displayed below the line but starting at the left most position and it doesn't move as we type-in.

2. In FF, if the above test is done in a textarea, it works fine!

Therefore, I think this is an issue in tinyMCE editor while used in FF. Since XUL is a mozilla plug-in, this issue occurs there too.

PFA file to demo the issue

Steps to reproduce:
1. Please see the above explanation
2.
3.
4.
5.

Expected result: Please see the above explanation

Actual result: Please see the above explanation
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5909](http://archive.tinymce.com/develop/bugtracker_view.php?id=5909) posted by [danielsds](http://archive.tinymce.com/profile.php?name=danielsds)_

> _**Tags:** [firefox pinyin chinese]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
