### ISSUE TITLE
Table css style input field missing | 5.7.1

### ISSUE THREAD

**Issue by Borsti26** [tinymce/tinymce#6962]
In Version 5 the css style input field for the table / row /cell in the Advanced tab is missing.

Version 4:
![image](https://user-images.githubusercontent.com/2920507/123048856-27a24800-d3ff-11eb-9654-34f065ecb8ee.png)

Version 5:
![image](https://user-images.githubusercontent.com/2920507/123048995-53253280-d3ff-11eb-898f-b5f7b381be69.png)

I was thinking this feature where removed but in the Version 5 documentation it is still written:
https://www.tiny.cloud/docs/plugins/opensource/table/#table_advtab

> This option makes it possible to disable the advanced tab in the table cell dialog box. The advanced tab allows a user to input **_style_**, border color and background color values.

Same as in Version 4.

**Comment by lnewson** [comment]
Hi @Borsti26, this is expected as that feature was removed in TinyMCE 5 as noted in the migration guide here: https://www.tiny.cloud/docs/migration-from-4x/#tableplugin

**Comment by Borsti26** [comment]
Ok, sorry i missed that.
Thanks.
