### ISSUE TITLE
Allow commenting in readonly mode

### ISSUE THREAD

**Issue by Noraiz** [tinymce/tinymce#6975]
while disabling editor or making it readonly. can not add/read comments from the editor. 
Is there anyway to achieve it with existing functionality?

**Comment by sws797** [comment]
[CKEditor: Comments-only mode](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-only-mode.html#enabling-comments-only-mode)

**Comment by ecconomix** [comment]
@Noraiz you can do it by setting tinymce body `'contenteditable' attribute to false`

```
<TinymceEditor
        onInit={(_, editor) => {
            editor.getBody().setAttribute('contenteditable', 'false')
         }}
         ...
</TinymceEditor >
  ```
