### ISSUE TITLE
tinymce 4 instance not removed with ie10

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#699]
Description of problem:

I am using the jquery plugin for tinymce. I initialize the tinymce instance via jQuery('#myid').tinymce({...}); On my page, the element with the tinymce inside is replaced via javascript that is loaded from the server. Therefore i want to remove the instance of tinymce before the request with jQuery('#myid:tinymce').tinymce().remove(); 

For Chrome and Firefox this method works like a charm. But under IE 10 the instance seems not to be removed entirely, but the remove-Methods does something with the instance.

Steps to reproduce:
1. initialize tinymce via jQuery('#myid').tinymce({...});
2. insert onclick-handler for a button like this:
var test = jQuery('#myid:tinymce').tinymce();
jQuery('#myid:tinymce').tinymce().remove();
var test2 = jQuery('#myid:tinymce').tinymce();
console.log(test);
console.log(test2);
console.log(test == test2);
1. open console
2. click on button

Expected result:

Console output like this
[Object object]
[]
false

Actual result:

On IE10 Developer Tools Console:

[Object object]
[Object object]
false

On Firefox Firebug console:

[textarea#myid]
[]
false

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5912](http://archive.tinymce.com/develop/bugtracker_view.php?id=5912) posted by [jaschil](http://archive.tinymce.com/profile.php?name=jaschil)_
> 
> _**Tags:** [msie msie10 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. 🐛 

If you still have a problem connected to this, leave a comment and we can open it up again. 

Cheers! 🍺
