### ISSUE TITLE
Multiple editors How do I use wordcount

### ISSUE THREAD

**Issue by zq0904** [tinymce/tinymce#6992]
**Is your feature request related to a problem? Please describe.**

When a Web page has multiple editors using the WordCount API,
Always get the last loaded Editor

**Describe the solution you'd like**

wordcount.body.getCharacterCountWithoutSpaces()API, such as whether you can specify the editor id to guarantee

**Describe alternatives you've considered**

**Comment by EkimChau** [comment]
Hi 

When you use tinymce.activeEditor.plugins.wordcount, it will return your active editor

using the tinymce.editors command will return an array of editors, which you can then loop through each editor and call wordcount.

eg: 
tinymce.editors[0].plugins.wordcount
tinymce.editors[1].plugins.wordcount

**Comment by zq0904** [comment]
Thank you for your efforts

**Comment by zq0904** [comment]
> 你好
> 
> 当您使用 tinymce.activeEditor.plugins.wordcount 时，它将返回您的活动编辑器
> 
> 使用 tinymce.editors 命令将返回一个编辑器数组，然后您可以遍历每个编辑器并调用 wordcount。
> 
> 例如：
> tinymce.editors[0].plugins.wordcount
> tinymce.editors[1].plugins.wordcount

Thank you for your answer
I have the following questions
When I use the link plugin, I want to verify the link format entered by the user before clicking OK. There is no relevant callback when I look up the document. Is there a good way to do this?
