### ISSUE TITLE
<svg viewBox="..."></svg> removing attribute

### ISSUE THREAD

**Issue by office-easy** [tinymce/tinymce#6997]
Hi there,

We are currently using tiny mce shipped with Magento 2.4, TinyMCE is at version 4.9.10.

I'm trying to allow svg in the wysiwyg with the following code :

`                'extended_valid_elements': 'svg[viewBox]',
`

The main issue is that "view**B**ox"  will be deleted when TinyMCE makes its verifications.

Why such a limit on upper case ?

There is a developer adding its own custom attributes, he knows what he is doing.
Why the heck would you remove the attribute he actually specified as valid and it is actually valid.

Any workaround ?

How to download the 4.9.10 not minified ?

Thank you in advance

**Comment by GuillaumeBrook** [comment]
Actually you could do :

extended_valid_elements: 'svg[class|viewBox=0 0 16 9]'
