### ISSUE TITLE
the jsonData for table plugin

### ISSUE THREAD

**Issue by kongxuhui** [tinymce/tinymce#7000]
Hello ，I am using tinymce a table plugin，I would like to table space inside the content into json data format is there。But now I can only getcontemt and getcontent({format:’text
’}). Is there a way to get the json data structure of such a table, or can you tag key and get the data in a format like key: value. I look forward to your reply. Thank you.
![6161242E-9181-4B76-82AF-701284B67368](https://user-images.githubusercontent.com/29567129/124847877-5bb86400-dfce-11eb-88a4-2dd6234b6da6.jpeg)

**Comment by EkimChau** [comment]
Hi @kongxuhui,

Have you tried:
tinymce.activeEditor.getContent({ format: 'tree' });

Let us know if that helps your usecase.
