### ISSUE TITLE
InsertContent does not work as expected when using innerHTML (version 4)

### ISSUE THREAD

**Issue by Zinyon** [tinymce/tinymce#7006]
**What is the current behavior? Describe the bug**
InsertContent does not work as expected when using innerHTML 
(especially with <a> tag)
* ``<a>`` Element should wrap html but it sets in last child position of wrapElement

It works fine in version 5 stable, but not in version 4 stable.
Is there any issue about this behavior in version 4?

i have other question, what is the difference of ``editor.insertContent`` vs ``editor.selelection.setContent`` ? 
I'm sorry for no demo in this question but it creates different dom in some cases.(similar with demo i created)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/QHhaab

**What is the expected behavior?**
#### AS-IS
![image](https://user-images.githubusercontent.com/26531678/125056671-6ca6c980-e0e3-11eb-8261-c13313ad0e09.png)

#### TO-BE
a tag should wrap innerHTML of figure element like this
![image](https://user-images.githubusercontent.com/26531678/125056574-54cf4580-e0e3-11eb-81ca-98962da18807.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
* TinyMCE version : version 4 stable 
* browser: chrome
* OS : MAC

**Comment by MichaelFromin** [comment]
TinyMCE 4 is no longer a supported version of TinyMCE and is no longer getting code updates.  In your testing does this issue still happen in TinyMCE 5?
