### ISSUE TITLE
Misplaced dropdown menus on menubar

### ISSUE THREAD

**Issue by mykhie** [tinymce/tinymce#7011]
The drop down menus are misplaced , has anybody faced this issue? Anybody with a solution

![issue with tiny emce](https://user-images.githubusercontent.com/7732556/125570151-79a6dfb1-032c-4049-9b87-ac1beedac407.PNG)

**Comment by warethis-dev** [comment]
This is driving me insane! I've tried everything i can think of but can't find a fix, DOES ANYONE HAVE A SOLUTION?

**Comment by TheSpyder** [comment]
We are working on this at the moment. Apologies, there have been a number of similar requests over the years and while we tried to combine them we missed this one.

Our combined tracking ticket is #5097 and I've noted there how to follow our progress.
