### ISSUE TITLE
Inline editor with fixed height. Scroll stay on top when enter is pressing

### ISSUE THREAD

**Issue by sergeji4** [tinymce/tinymce#7013]
**What is the current behavior? Describe the bug**
Scroll stay on top when enter is pressing.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://fiddle.tiny.cloud/mIhaab

1. tinymce in inline mode 
2. Container with fixed height, overflow: auto.
3. click on the editor area
4. hold enter btn few seconds
5. caret is missing, scroll stay on top of the element

**What is the expected behavior?**
scroll moves to bottom, caret is visible

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: tinymce-5-cloud-stable
OS: Windows 10
Browser:  Google Chrome Version 91.0.4472.124 (Official Build) (64-bit)
On versions before 5.0.7(incusive) works as expected

**Comment by JarvisArt** [comment]
+1
