### ISSUE TITLE
Style merge conflicts if the style has properties set via css variables

### ISSUE THREAD

**Issue by lemm17** [tinymce/tinymce#7021]
**Describe**
Style merge conflicts if the style has properties set via css variables. Because of this, it is impossible to apply other formats. The styles of css variables are placed in the style attribute, which prevents the styles from being applied

**Steps**
1. Go to https://fiddle.tiny.cloud/5Ihaab/2;
2. Place the cursor at the end of "custom-format" and press Enter, dividing the text into 2 lines;
3. For the first line, use the format " Red";
4. For the second line, use the format " Header 1 "(Format - > Blocks -> Header 1);
5. Place the cursor at the beginning of the 2 lines and click backspace, merging the 2 formats;
6. BUG ->The text of the second line is wrapped in span with inline styles
7. 
**What is the expected behavior?**
Inline styles of css variables are not set in the style attribute.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.8.2

**Example mp4**
https://user-images.githubusercontent.com/48180890/126123123-1f507cf0-46ba-487d-a806-b549d5485e8e.mp4

**Comment by burnes** [comment]
+1 having a similar issue with
```
<span class="some-class">One</span> <span class="some-class">Two</span>
```

When selecting both spans and entering new text, the span has no more the class `some-class` but a style tag with the styles of some-class.

**Comment by burnes** [comment]
Added a fiddle: https://fiddle.tiny.cloud/XUhaab/1

**Comment by burnes** [comment]
Hmm, I can see that the styles are merged, but why is this done and not the classes itself?
https://github.com/tinymce/tinymce/blob/b7fe330dc13ab684707d83335d4bbff7293c2b3a/modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts#L302
