### ISSUE TITLE
Full screen scrolls to the top of the page

### ISSUE THREAD

**Issue by BeautifulZhao** [tinymce/tinymce#7026]
**What is the current behavior? Describe the bug**
Full screen scrolls to the top of the page
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. The tinymce is at the bottom of the page, and the page has a scroll bar.
2. fullscreen
3. quit fullscreen. At the top of the page
**What is the expected behavior?**
back to pre position
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by sandervercampt** [comment]
Is there any news on this issue? I have the same problem...
