### ISSUE TITLE
Export pdf

### ISSUE THREAD

**Issue by Shisyr** [tinymce/tinymce#7030]
Premium export as pdf does not work correctly. Images that contains on editor does not display in pdf. Moreover, during exporting as pdf, there is error 400 with message "image_too_large" in request of imageproxy.tiny.cloud. Could you please help me to fix this problem? Thank you in advance.

**Comment by Shisyr** [comment]
<img width="669" alt="Screen Shot 2021-07-21 at 15 13 05" src="https://user-images.githubusercontent.com/22312494/126483294-0d3268a3-38f7-42f0-a6a1-4cf0c5ddf0f1.png">

**Comment by MichaelFromin** [comment]
Please direct questions on our premium features to our support site (https://support.tiny.cloud).  You appear to have already done so for this issue so I am going to close this GitHub issue.
