### ISSUE TITLE
Selected (custom) class formats 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#704]
When you add your own custom class formats for example like so:
# 

style_formats: [
   {title: 'Vraagbaak', items: [
      {title: 'container', selector : 'ul', classes : 'vragen'},
      {title: 'vraag', selector : 'li', classes : 'vraag'},
      {title: 'antwoord', selector : 'li', classes : 'antwoord'},
   ]}
# ],

There is no way for the user to see whether this class is selected or not. Would be great to either add class names to the bottom bar, but especially to have a way to see the selected classes in the top menu (same with the standard H1 and so on). This was the case in the old verstion of tinyMCE. I added a screenshot where in both H1 is selected.

Johan 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5921](http://archive.tinymce.com/develop/bugtracker_view.php?id=5921) posted by [johankrijt](http://archive.tinymce.com/profile.php?name=johankrijt)_
> 
> _**Tags:** [format]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
