### ISSUE TITLE
Powerpaste plugin allow to copy paste in disable mode

### ISSUE THREAD

**Issue by SerhiyP** [tinymce/tinymce#7041]
**Powerpaste plugin allows copy-pasting by hockeys  in disable mode**

**https://codepen.io/sergej-popad-k/pen/NWjaLez**

**In disable mode copy-paste functionality shouldn't work**

**reproduced on chrome and safari**

![tinyMce](https://user-images.githubusercontent.com/16022230/126658904-a9cdb2ba-29ca-4838-9e2d-d8b6aed511a2.gif)

**Comment by lnewson** [comment]
Hi, thanks for the report. PowerPaste is a premium product, so I'm afraid we can't assist via GitHub. If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new

**Comment by rianazara** [comment]
> Thanks for the great bug report! Very clear, concise and easy to replicate.
> 
> I have confirmed this bug in plain TinyMCE so I will transfer this to the tinymce repository. I will also raise this directly with the team.

@tiny-james - I'd like to know in which version of powerpaste was this issue resolved?

**Comment by rianazara** [comment]
I noticed that this issue is not reproducible anymore with the latest powerpaste plugin but is reproducible in Version: 5.5.1-491
