### ISSUE TITLE
Cannot force use inline style instead of width attribute when resize image

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#706]
Description of problem:
When i insert image and edit width or height, the tinymce use width height attribute instead of inline style width, height.
It is very bad with responsive design.
Tinymce should has an option to "force use" inline style instead of width, height attribute.

Steps to reproduce:
1. click insert image button
2. paste image url
3. specify dimension eg. 200
4. view source from tools menu > source code
5. img element has width attribute instead of inline style

Expected result:
style="width: 200px;" in img element.

Actual result:
width="200"

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5918](http://archive.tinymce.com/develop/bugtracker_view.php?id=5918) posted by [vee](http://archive.tinymce.com/profile.php?name=vee)_
> 
> _**Tags:** [firefox msie safari chrome opera 4x]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://fiddle.tinymce.com/Ghdaab_

**Comment by NitroBAY** [comment]
+1 very important.
