### ISSUE TITLE
Issue with paste plugin on copy content from PDF and pasting in tinyMCE

### ISSUE THREAD

**Issue by bshridhar** [tinymce/tinymce#7068]
I am facing issues to retain the formatting of the content copied from **PDF** document. Even the basic formatting such as bold text of the content is not retained when the content is copied from the PDF. 

### **Steps to reproduce:**
1. copy content from **PDF** 
2. Consider the content which has basic formatting such as either bold/italic text.
3. Paste in tinyMCE editor
4. Notice only the text along with line breaks(&#60;br /&#62;) is copied from source.
5. Notice only text content with line breaks(&#60;br /&#62;) is there in a &#60;p&#62; tag on inspect elements.
Please note that I am running on default configurations for tinyMCE. 

### **Expected:**
To retain basic format as the following. 
- Bold Text
- Italic Text
- Underline Text
- Strikethrough
- Superscript
- Subscript
- Code text
- Headings 1-6
- Left aligned text
- Right aligned text
- Center aligned text
- Justified text
- Paragraph
- Blockquote
- Div
- Pre
- Line breaks

### **Affected Versions**
I verified the issue in tinyMCE 4 and 5. 

Please look into the issue. 
Please let me know whether this requires to be fixed. 

Cheers,
Shridhar

**Comment by bshridhar** [comment]
Hi,
Is there any update on this issue. 

Thanks,
Shridhar

**Comment by dbussman** [comment]
This also happens when copying text from other sources (not just PDF)

**Comment by ManishNayakIN** [comment]
This issue still exists and need some solution, it will be good if someone can reopen this issue.
