### ISSUE TITLE
Issue with tinymce and sortable/vue-draggable.

### ISSUE THREAD

**Issue by eytan012** [tinymce/tinymce#7070]
hello, I'm using TinyMCE 3.2 with vuejs and vue-draggable and I'm having an issue. 
while dragging each editor, the value inside disappears. it's not deleted it's still stored in my data. 

looked at this issue: https://github.com/tinymce/tinymce/issues/3882
and several SO issues didn't solve it. 

hope someone could help :)

**Comment by YangLG-7** [comment]
I have the same problem，in latest version!!!!
Did you solve it?

**Comment by YangLG-7** [comment]
@eytan012

**Comment by eytan012** [comment]
Hey, I didn’t solve it.

**Comment by ahamed-kashif** [comment]
I am aving the same problem. dont know what to.. anyone please help me out.. any alternate suggestion also appreciated.

**Comment by ahamed-kashif** [comment]
@eytan012 did u find anything alternate solution?

**Comment by AvionCode** [comment]
To anyone facing the same issue,

Create a componentKey variable:
`data() {
            return {
                componentKey: 0
}
        },`

Add it as a key to the editor component:
`<editor :key="componentKey" .../>`

Attach a listener to the draggable component and update the component key on dragEnd:
`<draggable @end="onEnd">...</draggable>`
`methods:{
onEnd() {
                this.componentKey += 1;
            }
}`

More on forced re-rendering:
https://michaelnthiessen.com/force-re-render/

**Comment by bjornstenfeldt** [comment]
Based on what AvionCode wrote, I tried to simply add an unique key and that seemed to be enough to fix the issue.

Something like this:
```
<li v-for="(file, i) in files" ... class="draggable-item">
  <editor :key="'description' + i" .../>
</li>
```
