### ISSUE TITLE
After uploading the picture, I can't set the picture size arbitrarily

### ISSUE THREAD

**Issue by lovelike123** [tinymce/tinymce#7080]
I use Vue 。After uploading the picture, I can't set the picture size arbitrarily

I want to be able to zoom freely

The version I use is 5.0.12

**Comment by lovelike123** [comment]
object_resizing:true。 This parameter does not work

**Comment by Guolinlinaaa** [comment]
请问你的这个问题解决了？ 我的项目是vue3  然后也是图片上传之后就不能编译大小了，object_resizing:true。我也配置过了然后版本我也换过几个就是不能够正常的使用。 如果你的已经解决了 可以帮我看一下？

**Comment by lovelike123** [comment]
@Guolinlinaaa It hasn't been solved yet

**Comment by lovelike123** [comment]
@Tyler Kelly 
object_resizing:true。 This parameter does not work。
Please tell me how to solve this problem

**Comment by izachwei** [comment]
可以参考这篇文章
https://blog.csdn.net/VsXiXi/article/details/145574632?spm=1001.2014.3001.5501

**Comment by izachwei** [comment]
You can try to refer to this article to solve the problem
https://blog.csdn.net/VsXiXi/article/details/145574632?spm=1001.2014.3001.5501
