### ISSUE TITLE
how do I make line-end characters visible using visualchars

### ISSUE THREAD

**Issue by jasperf** [tinymce/tinymce#7087]
Would like to see whether `<br>` or `<p>`s can be displayed with symbols like the symbol used for the button. This so we can show when a hard or soft enter has been pressed and whether a break has been added or a new paragraph.
> *affected page: https://www.tiny.cloud/docs/plugins/opensource/visualchars/*

**Comment by tylerkelly13** [comment]
Note to developers:
Could someone easily work around this limitation using CSS?

**Comment by jasperf** [comment]
Yes, perhaps with a CSS rule for `p:empty` or `br` and using the CSS Content property https://developer.mozilla.org/en-US/docs/Web/CSS/content to show a symbol when visualchars is active. Just a thought.

**Comment by elenastoyanovaa** [comment]
Hello,

Is there any updates on this?
