### ISSUE TITLE
Clicking undo button in New Document takes you to Old Document

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#711]
Description of problem: Clicking undo button  in New Document takes you to Old Document

Steps to reproduce:
1.Open http://www.tinymce.com
2. Click on File->New Document
3.Click on Undo icon
4.You can see the old document with text contained 
5.

Expected result: It should not go to old document and stay in same as nothing to undo.

Actual result: It goes back to old document.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5924](http://archive.tinymce.com/develop/bugtracker_view.php?id=5924) posted by [Srikanta.Sahoo](http://archive.tinymce.com/profile.php?name=Srikanta.Sahoo)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
