### ISSUE TITLE
imagetools 图片编辑

### ISSUE THREAD

**Issue by Guolinlinaaa** [tinymce/tinymce#7111]
`<template>
	<div>
		<editor id="Editor" v-model="state.content" :init="init" />
	</div>
</template>`
`<script>

	import Editor from "@tinymce/tinymce-vue";
	import tinymce from "tinymce/tinymce";
	import 'tinymce/themes/silver/theme'; // 引用主题文件
	import "tinymce/icons/default"; // 引用图标文件
	import "tinymce/plugins/image";
	import "tinymce/plugins/imagetools";
	import "tinymce/plugins/link";
	import "tinymce/plugins/code";
	import "tinymce/plugins/table";
	import "tinymce/plugins/paste";
	import "tinymce/plugins/print";
	import "tinymce/plugins/preview";
	import "tinymce/plugins/searchreplace";
	import "tinymce/plugins/autolink";
	import "tinymce/plugins/directionality";
	import "tinymce/plugins/visualblocks";
	import "tinymce/plugins/visualchars";
	import "tinymce/plugins/fullscreen";
	import "tinymce/plugins/media";
	import "tinymce/plugins/template";
	import "tinymce/plugins/codesample";
	import "tinymce/plugins/charmap";
	import "tinymce/plugins/hr";
	import "tinymce/plugins/pagebreak";
	import "tinymce/plugins/nonbreaking";
	import "tinymce/plugins/anchor";
	import "tinymce/plugins/insertdatetime";
	import "tinymce/plugins/advlist";
	import "tinymce/plugins/lists";
	import "tinymce/plugins/wordcount";
	import "tinymce/plugins/textpattern";
	// import "tinymce/plugins/emoticons";
	import "tinymce/plugins/autosave";
	import "tinymce/plugins/autoresize";

	const init = {
		selector: '#Editor',
		language_url: require("../../static/langs/zh_CN.js"), // 中文语言包路径
		language: "zh_CN",
		skin_url: require("../../static/skins/ui/oxide/skin.css"), // 编辑器皮肤样式
		menubar: false, // 隐藏菜单栏
		height: 520,
		toolbar_mode: "none",
		// placeholder: '请输入会刊内容',
		plugins: 'image code imagetools link  table paste print preview searchreplace autolink directionality visualblocks visualchars fullscreen media template codesample charmap hr pagebreak nonbreaking anchor insertdatetime advlist lists wordcount textpattern  autosave', // 插件需要import进来
		toolbar: 'code | undo redo | link image | restoredraft | cut copy paste pastetext | forecolor backcolor bold italic underline strikethrough link anchor | alignleft aligncenter alignright alignjustify outdent indent | styleselect formatselect fontselect fontsizeselect | bullist numlist | blockquote subscript superscript removeformat | table image media charmap emoticons hr pagebreak insertdatetime print preview | fullscreen | lineheight',
		content_style: "p {margin: 5px 0; font-size: 14px}",
		fontsize_formats: "12px 14px 16px 18px 24px 36px 48px 56px 72px",
		font_formats: "微软雅黑=Microsoft YaHei,Helvetica Neue,PingFang SC,sans-serif;苹果苹方=PingFang SC,Microsoft YaHei,sans-serif;宋体=simsun,serif;仿宋体=FangSong,serif;黑体=SimHei,sans-serif;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;",
		branding: false,
		elementpath: false,
		resize: true, // 禁止改变大小
		// object_resizing: true,
		object_resizing: 'img',
		image_title: true,
		automatic_uploads: true,
		// image_dimensions: false,
		statusbar: false, // 隐藏底部状态栏
		// imagetools_cors_hosts: [''],
		// imagetools_proxy: '',
		image_class_list: [{
			title: '默认样式',
			value: 'rich-img'
		}],
		image_dimensions: true, // 保存图片的时候可以设置大小
		paste_as_text: true,
		forced_root_block: 'p',
		forced_root_block_attrs: {
			'class': 'content'
		},
		autosave_ask_before_unload: false,
		toolbar_mode: 'wrap',
		file_picker_types: 'image',
		// file_picker_callback: function(data){
		// 	console.log('go',data);
		// }, // 图片上传之后的回调
		images_upload_handler: function(blobInfo, succFun, failFun) {
			var xhr, formData;
			//转化为易于理解的file对象
			var file = blobInfo.blob();
			xhr = new XMLHttpRequest();
			xhr.withCredentials = false;
			xhr.open('POST', '/api/proceeding/uploadImage');
			xhr.onload = function(res) {
				console.log(res);
				if (xhr.status != 200) {
					failFun('HTTP Error: ' + xhr.status);
					return;
				}
				var data = JSON.parse(xhr.responseText);
				console.log(data, '8888888888800');
				if (!data || data.data.code === 0) {
					failFun(data.data.msg);
					return;
				}
				succFun(data.data.src);
			};
			formData = new FormData();
			formData.append('file', file, file.name);
			xhr.send(formData);
		},
		setup: function(editor) {
			console.log(editor, '22222222222222222');
			editor.on('change', function() {
				editor.save();
			});
		}
	}

	import {
		defineComponent,
		ref, // 赋值一个值
		reactive, // 生成响应式的数据
		toRefs,
		toRaw,
		onBeforeMount,
		onMounted,
		computed,
		onActivated,
		watch,
	} from 'vue'; // 钩子函数在这里面注册

	export default defineComponent({
		name: 'Editors',
		components: {
			'editor': Editor,
		},
		props: {
			content: {
				type: String,
				default: ''
			}
		},
		setup(props, {
			attrs,
			slots,
			emit
		}) {
			const state = reactive({
				content: props.content,
			})
			onMounted(() => {
				tinymce.init({});
				console.log(props.content, '组件');
				// state.content = props.content;
			});
			watch(() => state.content, (newValue, old) => {
				emit("content", {
					data: newValue
				});
			});

			const contentVlue = (value) => {
				console.log(value);
			}
			return {
				init,
				state,
				contentVlue,
			}
		}
	})
</script>`

这是我项目的配置的组件 不知道为什么我在项目中配置了imagetools 这个插件但是不生效， 问过好多人，也把我自己的配置给过别人， 人家用我的配置时 是能够正常的对图片进行放大和缩小的操作，而我的就不行， 改过好多地方 我也重新下载过node包,版本也换过几个也是不行，我真是心累了。 希望您能帮我看看。 （上面是我组件里面的全部配置 我的项目是vue3版本的项目。） 先谢谢大家了。

**Comment by xrjj** [comment]
请问这个问题解决了吗，我也遇到了，求赐教

**Comment by TheSpyder** [comment]
We only provide support in English, sorry. Although I think I get the gist of it from google translate.

I'm not sure what the original issue was but `imagetools` was removed in version 6, it's now a [premium plugin](https://www.tiny.cloud/tinymce/features/enhanced-image-editing/).
