### ISSUE TITLE
Autoresize plugin causes editor to jump to top

### ISSUE THREAD

**Issue by laneme** [tinymce/tinymce#7131]
The demos I set up used CRA and Next starters. But feel free to reproduce it the same way in their official [codepen example](https://codepen.io/pen/?&prefill_data_id=6927c5f6-a2b3-4720-96aa-702c5dc7ae9b)

### Steps to reproduce
-  `git clone https://github.com/laneme/tainy`
-  If you want to use cra instead of next, `git checkout with-cra`
-  `yarn`
-  `yarn dev` or `yarn start` (depending on which branch you're using)
-  Replace the api key and/or text if you need to, and visit `localhost:3000`
-  Go around the bottom and edit/del a block or two. Then press `Ctrl+Z`. The editor should jump to top.

At first I thought it is a react/next specific issue. Maybe due to some weird re-renders. I spent quite some time to figure out it was a core autoresize issue. 

If you inspect the index.tsx file, you'll see there's no other plugins used, nothing that could cause re-renders, and no handlers attached. In fact this happens in the official codepen example too. 

I have a readme file attached to both `main` and `with-cra` branch. Check them out [here](https://github.com/laneme/tainy).

### Browsers (ubuntu 21.04)

-  Firefox 92
-  Chromium 91

They're current latest versions of ubuntu.

**Comment by joyously** [comment]
Is this similar to #6250 ?

**Comment by laneme** [comment]
Yes it is @joyously

**Comment by metricjs** [comment]
Hi all, thanks for reporting this! This appears to be the same issue as #6714 and we are already tracking that issue internally, so I'm going to close this ticket as a duplicate. Keep an eye on #6714 to be alerted when this is fixed.
