### ISSUE TITLE
Highlighting text in editor on mobile

### ISSUE THREAD

**Issue by ashakir96** [tinymce/tinymce#7147]
**What is the current behavior? Describe the bug**

- When copying a few lines in the text and dragging down to select more, the blue highlight jumps outside of the text area.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Steps:
1. On mobile, go to https://www.tiny.cloud/docs/demo/full-featured/
2. try to double tap and highlight a couple of lines and drag/scroll downwards
3. Notice that the blue highlight (selector) is visible outsid eof the text area.

**What is the expected behavior?**

The highlight should remain within the composer (something like an overflow scroll)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment]
This is an iOS rendering bug and isn't something TinyMCE is able to fix sorry. It appears to have already been reported here: https://bugs.webkit.org/show_bug.cgi?id=190655
