### ISSUE TITLE
Image insert problem

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#715]
Description of problem: Images not loading in message after inserting them via image insert button in all versions of Google Chrome.

Steps to reproduce:
1. Launch Chrome (any version)
2. Copy the direct URL of an image. IMPORTANT: DO NOT preload the image into the browser so that it is not cached. This problem only occurs when the image is not cached by the browser.
3. Now Click insert image and paste the direct link of the image and click Insert.
4. The image will not appear in the message box or partially load. If you switch to full screen mode, the image starts loading then.
5. This problem is only with chrome and not with any other browsers. Only with version 3.x

Expected result: Image should start loading into the message box immediately after adding it.

Actual result: Image does not load at all in the message box after adding it.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5930](http://archive.tinymce.com/develop/bugtracker_view.php?id=5930) posted by [nilanko](http://archive.tinymce.com/profile.php?name=nilanko)_

> _**Tags:** [chrome chrome10 chrome11 chrome12 chrome13 image no not appearing]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://mysevenforums.com/viewtopic.php?f=2&t=2_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
