### ISSUE TITLE
Apply correct tox-collection__item--active class to parent menu depending on nested menu selected

### ISSUE THREAD

**Issue by AntonioLok** [tinymce/tinymce#7154]
Hello,

I have a dropdown menu that I added by passing a list of menus to `style_formats`.

This dropdown menu is composed of  2 parent menu items: Headers and Paragraphs. 

Within the Headers, I have some other nested menus. Same case for Paragraphs. I am currently applying some css style to `.tox-collection__item--active`. The problem is it always get applied to the first parent menu item, in this case it would be Headers. If I select a sub option in the second parent menu (Paragraphs) and I close the dropdown and re-open it, I should expect the active class to be applied to the Paragraphs menu, not the first one (Headers). 

Is there any solution for this? Thanks in advance!

In this screenshot attached, I selected a menu within Paragraphs and closed and re-opened the dropdown menu, but the active class is applied to the first menu item (Headers) instead of Paragraphs.

<img width="548" alt="Screen Shot 2021-08-05 at 3 21 33 PM" src="https://user-images.githubusercontent.com/14690224/128408752-4aa9351c-9d10-4ff4-8e57-1f2dcd3812b4.png">

**Comment by dhavalwd** [comment]
Here is the [codepen](https://codepen.io/cooldhavs/pen/qBjxoWY) that shows this issue. Here, `Blocks` should have been shown active instead active class always goes to the first item in the menu (i.e. `Headings`).

**Comment by meetmedana** [comment]
I've got same issue with @AntonioLok. Is there any update for it?
