### ISSUE TITLE
Persist the toolbar_mode open/hidden on the device

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#7168]
**Is your feature request related to a problem? Please describe.**

Currently, the `toolbar_mode: sliding` displays the hidden buttons that don't fit into the screen.

**Describe the solution you'd like**

It would be nice to keep the open/hidden status on the device.

For example, I may want to open it, refresh the page, and keep it open, instead of having to click it again.

**Comment by MichaelFromin** [comment]
We have a command (`ToggleToolbarDrawer`) you can use to both track the current state of the drawer and change its state:

How to determine the current state:
`tinyMCE.activeEditor.queryCommandState('ToggleToolbarDrawer')`

How to change the state:
`tinyMCE.activeEditor.execCommand('ToggleToolbarDrawer')`

You would have to track the current state and re-establish that once the editor is reloaded.
