### ISSUE TITLE
Paste Bullet List from Word adds extra spaces

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#717]
Description of problem:
When you paste a (bullet) list form WORD into the editor you get additional spaces after 4 words. (Version 3.5.8 and 4.03b). It only has a bug in MSIE, Chrome is acting as expected.

Steps to reproduce:
1. Make a bullet list in WORD. Sentences must be at least 8 words
- New user interface API some extra text
- New modern skin! some extra text
2. Copy & Paste it in the editor (All versions)
3. The editor adds the spaces 

Expected result:
- New user interface API some extra text
- New modern skin! some extra text

Actual result:
- New user interface API (EXTRA SPACES)     some extra text
- New modern skin! some  (EXTRA SPACES)             extra text
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5933](http://archive.tinymce.com/develop/bugtracker_view.php?id=5933) posted by [etinuz](http://archive.tinymce.com/profile.php?name=etinuz)_

> _**Tags:** [msie list paste word]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
