### ISSUE TITLE
Upload all Types of File via drag and drop functionality

### ISSUE THREAD

**Issue by mayrhofer-simon** [tinymce/tinymce#7178]
Upload all kinds of files would be nice, so i don't have to solve it via a botch

Provide upload functionality to the editor via drag and drop of all kinds of files (e.g. json, txt, docx) with a preview, just like in Rich Text Editor used in Jira, where you have the possibility to upload all kinds of files via drag and drop on the editor.

I tried to understand the code from the selfhosted version to extend the functionality but i have not seen through how the problem was solved.

**Comment by OlivierJaquemet** [comment]
@mayrhofer-simon I wanted to provide the same feature. 
But apparently, TinyMCE voluntarily only supports image (*).
You closed your issue without further comment, did you find a solution for your need ?


(*)
- https://github.com/tinymce/tinymce/issues/6034#issuecomment-722615955
- https://github.com/tinymce/tinymce/blob/0325f25d77df58040e6da4af890999b6f20a963a/modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts#L27

**Comment by mayrhofer-simon** [comment]
Hello, i implemented it by my my own. I overrided the default methods and made my own logic

**Comment by OlivierJaquemet** [comment]
Would you consider sharing your code ? or maybe some pointers on how you did it ?

**Comment by mayrhofer-simon** [comment]
You prevent ondrop default and then upload the files asynchroniously when draggin inside the Editor

**Comment by OlivierJaquemet** [comment]
Thanks.
