### ISSUE TITLE
Iframe resize invalidates size change through "Insert/Edit Media" configuration modal

### ISSUE THREAD

**Issue by elias-telescope** [tinymce/tinymce#7185]
**Description**

By using the "Insert/Edit Media" button the user can add embedded media like a YouTube video. Once added, the user can resize the video in two different ways. 

1. By clicking the "Insert/Edit Media" button again, and use the Width and Height numeric inputs to change the size of the iframe.
2. By dragging the corner of the iframe to resize it. 

The issue is, once the user has used the second approach, the first one won't work anymore. 

**Steps to reproduce**

1. Click on the "Insert/Edit Media" button. 
2. Paste a YouTube URL on the source input. Do not modify the size of it. Press Save.
3. Click on the "Insert/Edit Media" button again and edit the size of it. Press Save. Check the size does change. 
4. Close the "Insert/Edit Media" modal and this time, resize the video by dragging one of the corners.
5. Check the video does get resized.
6. Click on the "Insert/Edit Media" button once more and try to update the size of it. 
7. Check this time the YouTube video DOES NOT get resized.

**What is the expected behavior?**

Users should always be able to follow any of the approaches explained in the description section, to resize an embedded media.

**Which versions of TinyMCE, and which browser / OS are affected by this issue?**

Currently using "@tinymce/tinymce-angular": "3.5.0". The issue is happening in all browsers.

**Comment by Anu3ev** [comment]
Hi!

I join to this topic and also would like to add one moment.

By clicking "Insert/Edit Media," we can use numbers to change the sizes of an iframe, and this works well, but when we want to change sizes by using values in percent, we get a very strange picture.

![image](https://user-images.githubusercontent.com/46539713/217790846-c106253b-dd62-4d5d-8b3b-a87eb9cadedf.png)
![image](https://user-images.githubusercontent.com/46539713/217790913-c82e2fd2-fac5-441a-8869-1526a80cd977.png)
