### ISSUE TITLE
All formats disabled when disabling one at end of node

### ISSUE THREAD

**Issue by tamila-ambeon** [tinymce/tinymce#7186]
**Description of problem:**
Applied formats are disabled, when disabling one by clicking its button, when cursor is at end of content. Sometimes disable one, sometimes all.

**Steps to reproduce:**

- Open an editor with custom formats such as https://www.tiny.cloud/docs/demo/full-featured/
- Type some text (ex. "Hello world")
- Apply Bold, Italic, Underline, Strikethrough formatting
- Move cursor to end of content (either with arrow keys or mouse)
- See that all formatting buttons are active and enabled.
- Disable any formatting button
- See that some other has also been disabled (sometimes one of them, sometimes all at once.

**Expected result**: Only the format which was toggled should be disabled. The other(s) should remain enabled so that continued typing with those formats is possible without reapplying them.

**Actual result**: Sometimes it works as expected, but mostly it doesn't, One or all applied formats are disabled, so that continued typing has no formatting applied. Formats must be reapplied for continued typing.

Self-hosted version 5.8.1 has this bug too.
![2021-09-10](https://user-images.githubusercontent.com/28840260/132764722-f77bf625-54d4-48a9-b516-ddbc6077061d.gif)

Version: 5.8.1, Chrome and Safari affected by this issue

**Comment by kamilluc** [comment]
Any chance for a fix?

Issue is still present in v6:
https://www.tiny.cloud/docs/tinymce/6/

Steps to reproduce:
1) Remove all content
2) Select "B" and "I"  ("B" and "I" enabled)
3) Select B again, ("B" and "I" disabled, but only "B" should)
