### ISSUE TITLE
TinyMce v4.0b3 conflict with my peosonally javascript Method

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#719]
Description of problem:
## Hi I found a bug from my personally SpringMvc3-test-project using TinyMce v4.3 for my Html-Editter,it happpend when I use it in a html file which exist a javascript methods like this:

Object.prototype.equals = function(obj){
         if(this == obj){
         return true;
     }
         if(typeof(obj)=="undefined"||obj==null||typeof(obj)!="object"){
         return false;
     }
     var length = 0;
     var length1=0;

```
 for(var ele in this) {
      length++;
 }
 for(var ele in obj) {
     length1++;
 }
 if(length!=length1){
      return false;
 }

  if(obj.constructor==this.constructor){
      for(var ele in this){
          if(typeof(this[ele])=="object") {
              if(!this[ele].equals(obj[ele])){
                  return false;
              }
          }else if(typeof(this[ele])=="function"){
              if(!this[ele].toString().equals(obj[ele].toString())){
                  return false;
              }
          }else if(this[ele]!=obj[ele]){
                return false;
          }
     }
         return true;
     }
 return false;
```
## };

maybe there is some conflict with each other.
Expected result:

Actual result:
## finally I used FireFox FireBug found some information like this:

```
 TypeError: C[_] is undefined
                                                 tinymce.min.js (row  4)
```

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5935](http://archive.tinymce.com/develop/bugtracker_view.php?id=5935) posted by [ad_oamaker](http://archive.tinymce.com/profile.php?name=ad_oamaker)_
> 
> _**Tags:** [firefox msie safari chrome opera javascript conflict]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
