### ISSUE TITLE
Fullscreen plugin does not work when TinyMCE instance set to readonly

### ISSUE THREAD

**Issue by Dave-REBL** [tinymce/tinymce#7208]
**Issue description:**

- TinyMCE instance is initialized to readonly with fullscreen plugin as follows:
  `tinymce.init({
       selector: 'textarea#lh',
       plugins: 'fullscreen',
       toolbar: false,
       menubar: false,
       statusbar: false,
       readonly: true,
       content_style: "body { line-height: 1; font-size: 10pt; font-family: Consolas; }",
       forced_root_block : false,
       height: "100%",
       width:"100%"});`

- Attempting to set the TinyMCE editor to fullscreen mode with (Ctrl+Shift+F) does not have any effect.

**Requested Behavior:**
Would like to have the option of presenting the user with a full screen display of read-only information.

**Browser / Version Info:**
Tested in Chrome 93.0.4577.82 on Microsoft Windows 10  Version 21H1 on the latest version of TinyMCE v5. Seems to be an issue on older versions of TinyMCE as well.

**Comment by lorenzo-pomili** [comment]
Hi @Dave-REBL 

I was not able at reproducing the issue, could you please provide a [fiddle] (https://fiddle.tiny.cloud/) with an example?

Thanks

**Comment by lorenzo-pomili** [comment]
Hello @Dave-REBL, I figured out how to replicate it, at the moment is an expected behaviour. There have been similar requests to allow this type of thing before though, so I'm going to label it as a feature request.

**Comment by GlodenBoy** [comment]
> Hello @Dave-REBL, I figured out how to replicate it, at the moment is an expected behaviour. There have been similar requests to allow this type of thing before though, so I'm going to label it as a feature request.

Is it possible to provide a way to preview in full screen when read-only?
