### ISSUE TITLE
Wrong cursor position on table insert

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#721]
Just after a table is inserted cursor is positioned in the last row/cell of the table. Would be better to place it in the first cell. Tested with Firefox.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5937](http://archive.tinymce.com/develop/bugtracker_view.php?id=5937) posted by [alec](http://archive.tinymce.com/profile.php?name=alec)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
