### ISSUE TITLE
Add Authorization Header when downloading images

### ISSUE THREAD

**Issue by FireSon** [tinymce/tinymce#7217]
Hi would it be possible to add an authorization header to the download request when the images are downloaded? 
I am aware that it is possible when an images_upload_handler is used. 

```
tinymce.util.XHR.on('beforeSend', function(e) {
     e.xhr.setRequestHeader('X-Requested-With', 'Something');
});

```
But new images are uploaded to a secure API and therefore the same authorization header is necessary when the images are downloaded...

**Comment by rehack** [comment]
```
tinymce.util.XHR.on('beforeSend', function(e) {
     e.xhr.setRequestHeader('X-Requested-With', 'Something');
});
```
The beforeSend event is not fired when uploading to the `images_upload_url` configured address
