### ISSUE TITLE
Group Toolbar button not rendered on mobile device

### ISSUE THREAD

**Issue by tgochenour** [tinymce/tinymce#7238]
Receiving the console warning: 
**theme.min.js:9 Ignoring the 'selectdropdown' toolbar button. Group toolbar buttons are only supported when using floating toolbar mode and cannot be nested.**

The application is running in Chrome on an Android phone.  The same application running in Chrome on a PC does produce the expected result.

My spec:
```
var spec = {
	selector: '#' + arr[i].id
	,toolbar_mode:'floating'
	,plugins: [ 'lists' ]
	,menubar: false
	,browser_spellcheck: true
	,contextmenu: false
	,inline:true
	,toolbar: [
		'bold italic underline | forecolor backcolor | removeformat selectdropdown',
		'undo redo | selectall | alignleft aligncenter alignright | numlist bullist'
	]
	,toolbar_groups: {
		selectdropdown: {
			icon: 'more-drawer',
			tooltip: 'Format',
			items: 'fontsizeselect formatselect'
		}
	}
	,block_formats: 'Normal=p; Header=h3;'
};
```

The image on the phone:
![image](https://user-images.githubusercontent.com/39278603/135096408-9f949261-24f3-4fba-beb0-6dd6fd088dd7.png)

The image on the PC:
![image](https://user-images.githubusercontent.com/39278603/135097862-be998ce0-56d7-4d3f-97b8-425f83b29bf8.png)

**Comment by WilliamAdolph** [comment]
have you solve this problem?i also got this problem

**Comment by joshclancy** [comment]
I am also having this problem! Any work arounds yet?

**Comment by mateusfmello** [comment]
@lostkeys can you help us?

**Comment by mateusfmello** [comment]
@lostkeys **you are an angel**, it worked perfectly, thank you very much.

I didn't find this information in the documentation, I don't know if I looked wrong or if it doesn't exist. 

@tgochenour @WilliamAdolph @joshclancy This solution worked for me, try it too.

**Comment by joshclancy** [comment]
Hell yeah! that worked. I was setting toolbar_mode to float specifically within the mobile environment but not like that.  Thanks @lostkeys
