### ISSUE TITLE
[3.5.8] table plugin copies too much content when inserting row

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#724]
Description of problem:
when inserting row below a row with &ltg;a> tag inside, new row gets &ltg;a> inserted with all the attributes.
The problem seems to be in code of editor_plugin_src.js in lines 151-173 described as 'Clone formats'. When I comment out these lines in my editor only attributes like style in &ltg;td> are copied.

Steps to reproduce:
1. launch 3.x demo
2. create a table 2x2
3. insert a link to the first row/cell of the table
4. insert row below
5. try input sth in the cell below &ltg;a> cell in row above

Expected result:
&ltg;tr>&ltg;td> is copied without content like &ltg;a> tags etc
example:
&ltg;table border="0">
&ltg;tbody>
&ltg;tr>
&ltg;td>&ltg;a href="http://yahoo.com">aaaaaaaaaaaaaa&ltg;/a>&ltg;/td>
&ltg;td>&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td>aaaaaaaaaa bbbb&ltg;/td>
&ltg;td>&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td>&nbsp;&ltg;/td>
&ltg;td>&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>

Actual result:
&ltg;tr>&ltg;td> is copied, but when you start input text, then other tags are included, example:
&ltg;table border="0">
&ltg;tbody>
&ltg;tr>
&ltg;td>&ltg;a href="http://yahoo.com">aaaaaaaaaaaaaa&ltg;/a>&ltg;/td>
&ltg;td>&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td>&ltg;a href="http://yahoo.com">aaaaaaaaaa bbbb&ltg;/a>&ltg;/td>
&ltg;td>&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td>&nbsp;&ltg;/td>
&ltg;td>&nbsp;&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>

http://scr.hu/0ruy/8ketp

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5940](http://archive.tinymce.com/develop/bugtracker_view.php?id=5940) posted by [valor](http://archive.tinymce.com/profile.php?name=valor)_

> _**Tags:** [firefox table plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/3_x/full.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
