### ISSUE TITLE
custom build with tinymce with grunt still working?

### ISSUE THREAD

**Issue by jcyl29** [tinymce/tinymce#7240]
**What is the current behavior? Describe the bug**

I wish to upgrade tinymce from 5.0.8 to 5.9.2
With version 5.08, I followed along the instructions in
https://github.com/tinymce/tinymce/tree/master/modules/tinymce
to create a custom build of tinymce.

However, when I tried to repeat the same steps for 5.9.2, I am getting all sorts of errors.  Is this still a supported method of building tinymce?

Here is what I did:
* clone this repo
* cd to `tinymce/modules/tinymce`
* run `yarn install`

Then I ran this commands:
```
jlui@COMPUTER_NAME:~/Downloads/tiny_repo/tinymce/modules/tinymce (develop)$ yarn --version
3.0.2
jlui@COMPUTER_NAME:~/Downloads/tiny_repo/tinymce/modules/tinymce (develop)$ yarn grunt
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "shell:tsc" (shell) task
src/core/test/ts/browser/init/InitEditorIconTest.ts(5,43): error TS2307: Cannot find module '@tinymce/oxide-icons-default' or its corresponding type declarations.
src/themes/silver/test/ts/browser/icons/IconsTest.ts(5,39): error TS2307: Cannot find module '@tinymce/oxide-icons-default' or its corresponding type declarations.
Warning: Command failed: tsc -b
 Use --force to continue.

Aborted due to warnings.
```

Also tried:
```
jlui@COMPUTER_NAME:~/Downloads/tiny_repo/tinymce/modules/tinymce (develop)$ yarn grunt bundle --themes=silver --plugins=paste,lists,help
Running "bundle:minified" (bundle) task
Fatal error: Could not find file: js/tinymce/themes/silver/theme.min.js
```

**Comment by lnewson** [comment]
Hi @jcyl29,

The problem here is that you've missed a step in the monorepo setup that would be required to make this work. You'll need to run at least `yarn dev` (or possibly even the full `yarn build`) from the root of the monorepo first to setup the various packages TinyMCE depends on. These steps and more information is noted in the contributing guide: https://github.com/tinymce/tinymce/blob/develop/CONTRIBUTING.md

**Comment by jcyl29** [comment]
Hi @lnewson you're totally right, i read the wrong set of the directions.  I started over with the link you have, and was able to repeat my previous steps.  I just had to change the bundle command slightly:
```
yarn tinymce-grunt bundle --themes=silver --plugins=paste,lists,help
```

Thanks for response!
