### ISSUE TITLE
Font size changes to default when deleting empty line when having multiple ones.

### ISSUE THREAD

**Issue by jjatczakgsd** [tinymce/tinymce#7246]
If I have multiple empty lines in my text editor and font size set to different height than default, line height changes from one set to the default one after deleting one of empty lines using backspace or delete keyboard button as could be seen in images below.

Before line deletion:
![image](https://user-images.githubusercontent.com/91679871/135474356-b0f73657-b8c3-4668-acb2-a246f73501ff.png)
After line deletion:
![image](https://user-images.githubusercontent.com/91679871/135474534-80a67f38-b8a6-4ea4-8627-db7ab2318333.png)

**Comment by zileeva** [comment]
Hello! Is there a plan to fix this issue?
