### ISSUE TITLE
After pasting html ordered list, left margin is not applied properly

### ISSUE THREAD

**Issue by jjatczakgsd** [tinymce/tinymce#7248]
If I paste a snippet seen below which is an html code for ordered list, left margin won't apply as it is supposed to, bringing the result of digit '1' being invisible in the number '10'.

```
  <p>&nbsp;</p>
   <ol>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">dsf</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">sdfs</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">dsfa</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">dsf</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">dsf</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">dsf</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">fsdf</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">fsd</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">fsdf</li>
   <li style="font: 36pt/normal Arial; font-size-adjust: none; font-stretch: normal;">sdfd</li>
  </ol>
```

![image](https://user-images.githubusercontent.com/91679871/135475713-f4db7e75-469c-45c2-adae-65d0f881c5de.png)

**Comment by joyously** [comment]
The HTML is not responsible for the styling, and the styles you have do not handle it.
I suggest you use a smaller font.

**Comment by jjatczakgsd** [comment]
I am not sure that using smaller font could be regarded as an acceptable answer. The editor needs to behave correctly independently from the font-size (which is not exceptionally big here, really). There clearly needs to be made a change in tinymce's behaviour. If I want the default font-size to be 36pt, it doesn't matter if I use inline style or no - the problem stays the same. Moreover, it is tinymce's default behaviour to use inline styles.

**Comment by joyously** [comment]
Are you saying that the example is what the editor generates or what you pasted into the editor?
It is a known "feature" of a HTML `<ol>` that you have to make room for larger numbers, especially if you use a larger font size (which 36pt is). 

It seems to me that the styling beyond the basics is not really the concern of the editor. The editor simply applies what the user commands. The user needs to add styling if there is something that doesn't look right. (There's no way for the editor to know that the number is not visible.)
The default of `list-style-position: outside` needs padding needs to go on the `<ol>` but in most fonts at standard sizes, the default amount will show 3 digits. If you use `inside`, then it doesn't overflow. If you put a floated element next to a list, you will have a different problem. The `outside` markers can be covered by the floated element.
Styling is for humans, not programs.

**Comment by lorenzo-pomili** [comment]
Hello @jjatczakgsd, like @joyously said previously this issue is caused by the content inserted into the editor, so it is correct that it is rendered this way.

Here is a comparison between what happens in raw HTML and what happens if you put the same HTML in the editor just to show it's not a TinyMCE related issue: https://fiddle.tiny.cloud/sdiaab
