### ISSUE TITLE
Autocomplete context menu doesn't work after changing editor styles (i.e. turning bold/italic/etc off or on)

### ISSUE THREAD

**Issue by timsquires** [tinymce/tinymce#7258]
**What is the current behavior? Describe the bug**
Autocomplete does not get triggered by the trigger character after toggling font styles on or off unless some other text is typed before the trigger character. Note that the most reproducible way to see this appears to be by toggling the styles with keyboard shortcuts.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/5Ohaab

Click in the editor, press `Ctrl+B` to turn Bold on, then type `:a` and no autocomplete context menu shows up. Then type a space and type `:a` again and the autocomplete context menu will now work.

**What is the expected behavior?**
Typing the autocomplete character should trigger the context menu

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I haven't tested other versions but it's happening on at least 5.8.2 and 5.9.2

**Comment by timsquires** [comment]
On the first attempt, note there is not a space after the closing strong tag in front of the colon
`
<p><strong><strong>:a</p>
`
Then the second attempt looks something like:
`
<p><strong><strong>:a :a</p>
`
so it seems like it might be related to the single character autocomplete trigger if

**Comment by Mintenker** [comment]
I can confirm this happens to me too.

```
"tinymce": "^5.10.2",
"typescript": "^4.5.5"
 "@angular/core": "^13.2.1",
 ```
