### ISSUE TITLE
Initialize fullscreen plugin in fullscreen mode

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#728]
Hello,

I would like to be able to initialize the fullscreen plugin in fullscreen mode, either through an option or some command line "setFullscreenState". I have looked at the code of the plugin and I think it is not possible at the moment. I'm using tinymce 4.0b3.

Best regards,

Werner.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5944](http://archive.tinymce.com/develop/bugtracker_view.php?id=5944) posted by [wdonne](http://archive.tinymce.com/profile.php?name=wdonne)_
> 
> _**Tags:** [fullscreen initialization]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
