### ISSUE TITLE
forced_root_block deprecation

### ISSUE THREAD

**Issue by vjsingh** [tinymce/tinymce#7297]
Apologies if this is not the right place to ask this.

I found this in the [docs](https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block): `Important: Setting forced_root_block to false or an empty string has been deprecated in TinyMCE 5.10. For TinyMCE 6.0, this option will only accept valid block elements.`

I want to prevent `<p>` tags from being generated on enter, and instead create `<br>`s. This used to be possible by setting `forced_root_block` to false.

Will there be any way to do this in TinyMCE 6?

See:
https://github.com/tinymce/tinymce/issues/6304
https://github.com/tinymce/tinymce/issues/2634

**Comment by EkimChau** [comment]
Hi Georgevanvelzen,

I see your use case is around emails, and that outlook strips out html and just leaves plain text.  I am familiar with this issue dealing with old email clients a long time ago, but not so much recently so i'll need to get more context on whats happening.  Just some follow up questions to help me understand. 

- Are you able to provide a code snippet of what the html formatting looks like before and after outlook strips?
- What percentage of your users experience this problem? Does it happen to all of your users or just some?
- Does it happen if you follow a strict HTML schema and use a HTML mime type?
- Does outlook strip out the BR tags and replace with newline or carriage returns?
- For others on the thread, is this the primary reason to use forced_root_block, is to solve problems with email formatting?

I'd like to fully understand the context and the conditions this occurs before we start looking for solutions

**Comment by Daijobou** [comment]
> I'd like to explore and discuss your use case for using BR tags instead of paragraphs.

I honestly don't understand this question. **TinyMCE replaces textarea and textarea does not use paragraphs**. 
Text is written much more often without paragraphs. Pragraphs are needed in scientific texts or in news and blogs.

In comment system or forum posts or or or ... paragraphs are complete nonsense. Most users make a line break after each sentence. This is not what paragraphs are for. We don't want paragraphs. If we need them, we press Shift+Enter.

There are also situations where you edit a part of a paragraph and it should NOT contain any other paragraphs because it is already contained in a paragraph. In this cases is Shift+Enter blocked.

If you currently create a table and press Enter in a field, the editor itself makes paragraphs in there. This is so absurd. I would rather like to hear an explanation of how this is supposed to be useful. Because I don't understand it.

**Comment by vjsingh** [comment]
> I'd like to explore and discuss your use case for using BR tags instead of paragraphs.

We use the TinyMCE editor to allow users to edit the description of a calendar invite. `<p>` tags in calendar invites get translated into two line breaks (one blank line) instead of one, which results in lots of extra vertical space and is unusable for our users.

See this example screenshot, which would be generated by this text:

```
Hi John,
We're looking forward to speaking with you on Saturday, October 9 at 9:00 AM - 9:30 AM (EDT).
Feel free to reach out to us if you have any questions.
Thank you,
```

<img width="445" alt="Screen Shot 2021-10-15 at 10 54 15 AM" src="https://user-images.githubusercontent.com/318312/137508075-f2be6a06-7370-4b39-bcce-81c2e5ac1e03.png">

**Comment by EkimChau** [comment]
Hi, based on the feedback so far, TinyMCE has a getContent api that returns only text and \n newlines.  This takes a post processing approach to the situation, where you create rich HTML in the editor and upon exporting the content, you cleanup the content to suit the publishing needs, aka email calendar or outlook.

Have a try of `tinymce.activeEditor.getContent({ format: 'text' })` on https://fiddle.tiny.cloud/ and see if this approach could work for your use case, you will need to filter out any unwanted double \n\n characters as paragraphs generally resolve to double new lines

**Comment by russpowers** [comment]
Paragraph formatting was confusing for our users writing emails in TinyMCE, they want line breaks to work like the Gmail editor. And I've found that `<br />` tags tends to cause the least problems when sending emails. If TinyMCE removes `forced_root_block` we would be forced to stick with version 5 I guess.
