### ISSUE TITLE
Removing specific text style affects command state of the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#730]
Description of problem: I was typing text that was both Bold and Italic, and after removing the Bold style the editor command state no longer thought it was Italic, even though as I continued typing the text was still Italic.

Reproduces on TinyMCE demo

Steps to reproduce:
1. Turn on Bold
2. Type text
3. Turn on Italic
4. Type text
5. Type a space
6. Turn off Bold
-- Toolbar state of Italic also "turns off"
7. Continue typing
-- Text is still Italic, but editor.queryCommandState('italic') returns false

Expected result: editor.queryCommandState('italic') would return true since I never turned off that style

Actual result: editor.queryCommandState('italic') returns false, however, newly entered text is still italic.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5946](http://archive.tinymce.com/develop/bugtracker_view.php?id=5946) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_

> _**Tags:** [firefox safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
