### ISSUE TITLE
Autofocus and autoscrolling cannot be disabled (revisited)

### ISSUE THREAD

**Issue by NickVolt77** [tinymce/tinymce#7306]
**What is the current behavior? Describe the bug**
Editor steals focus and scrolls page to top of editbox.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Code for fiddle (I can't get working fiddle link with my code)

```
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
$('body').on('click','#add',function(){
var insx='text to insert';
tinymce.activeEditor.execCommand('mceInsertContent', false, insx,{skip_focus:true});
});
</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
	<div style="height:500px">space</div>
	<input type="button" id="add">
</form>
```

Pressing button should add text to editor without scrolling page. But it scrolls page to editor. 

**What is the expected behavior?**
Window should not be scrolled.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
New 5,x from fiddle, Opera on Linux.

**Comment by NickVolt77** [comment]
I don't want to be rude, but shouldn't I get any answer od confirmation of a bug? This bug is unfixable by me and it slows down my team at work - they must scroll page after every photo add action. We use photos list outside editor and dedicated buttons to add them to text.

**Comment by NickVolt77** [comment]
@EkimChau Is there any chance to fix this bug or I need to find another editor?

**Comment by NickVolt77** [comment]
@landtastic Sorry for calling, but noone seems to be interested in fixing this bug. Can you reproduce it?

**Comment by joernlenoch** [comment]
Might be slightly off-topic, but I might help someone coming here:

I just encountered this issue when loading multple tinymce instances on page load with the angular bindings. Had no issues with firefox, but with chrome the screen jumped erratically.

I "solved" this for me by replacing `focus` in the configuration setup method.

```
setup: (editor: any) => {
      editor._focus = editor.focus;
      editor.focus = () => {};
}
```
