### ISSUE TITLE
'height' not respected using iPad

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#731]
Description of problem:
On iPad, if the content of the textarea is to long, instead of being scroll-able, it just creates a TinyMCE textarea with more height.

Steps to reproduce:
1. Init TinyMCE with 'height: XXX'
2. Wrap div with 'overflow: scroll' around the textarea.
2. Open with iPad

Expected result:
It should be XXX high and scroll-able.

Actual result:
The textarea does not scroll, instead the outer div scrolls.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5947](http://archive.tinymce.com/develop/bugtracker_view.php?id=5947) posted by [Devils Child](http://archive.tinymce.com/profile.php?name=Devils Child)_

> _**Tags:** [ipad]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
