### ISSUE TITLE
Open autocompleter in the middle of a word

### ISSUE THREAD

**Issue by dav-sap** [tinymce/tinymce#7310]
Today my auto completer opens up a new line or after a space. However I have use cases where users will want to open the autocompleter attached to a different word, today it doesn't work.
Is there an option to do it that Im missing? I can also create a listener and trigger it on my own if possible.
Thanks.

**Comment by lorenzo-pomili** [comment]
Hello @dav-sap 

I have not been clear on how to reproduce the issue, could you please provide a [fiddle](https://fiddle.tiny.cloud/) and a list of steps to reproduce it?

Thanks
