### ISSUE TITLE
setActive is not working on ToggleButton on Quickbars Selection Toolbar

### ISSUE THREAD

**Issue by krishnaeverestengineering** [tinymce/tinymce#7321]
I am trying to toggle the custom button state, but somehow it's not highlighting the button through CSS class on quickbars_selection_toolbar. But is working on regular toolbar. Is there anything I am missing? Defaults buttons like h2, b are working fine. But custom toggle buttons are not working.

<img width="354" alt="Screenshot 2021-10-22 at 5 20 34 PM" src="https://user-images.githubusercontent.com/55732888/138449056-50a2b121-b27b-4dc6-b2ea-031565007827.png">
.

**Comment by jdus** [comment]
I can confirm that. It's not working for me either on Tiny 5.10.0.

**Comment by lnewson** [comment]
Can you please provide a replication case? This issue normally occurs because the toolbar buttons are not setting the initial state correctly, for example in the `onSetup` function.

**Comment by krishnaeverestengineering** [comment]
> Can you please provide a replication case? This issue normally occurs because the toolbar buttons are not setting the initial state correctly, for example in the `onSetup` function.

This issue happens on distraction editor mode and create custom quick selection toolbar button. The button api is gonna not work even on onSetup.

**Comment by lnewson** [comment]
That is not a reproduction case, please provide a working example of the issue occurring because as you noted this works fine with the default buttons. That means it's something in your custom code that likely isn't being done correctly.

**Comment by krishnaeverestengineering** [comment]
> That is not a reproduction case, please provide a working example of the issue occurring because as you noted this works fine with the default buttons. That means it's something in your custom code that likely isn't being done correctly.

https://codepen.io/krishnaeverestengineering/pen/jOLGpwN

Here is an reproduction case

**Comment by lnewson** [comment]
That confirms what I had suspected. You're not setting up the initial state of the button correctly, which means it won't show as toggled until some other action occurs. I've forked your codepen to fix the issues and you'll see it now works: https://codepen.io/lnewso/pen/RwZLBEq

To add more details about what's happening, the `formatter.formatChanged()` API being used will only fire when the format changes. Since the button isn't rendered/setup until the context toolbar is opened it won't register the format changed function until after the selection is already set. As such, you need to ensure you always set the initial state via the `onSetup` function. Now the reason this works in the toolbar is it's rendered before the editor initializes, so therefore it does get the format changed callbacks as you change the selection within the editor.

**Comment by krishnaeverestengineering** [comment]
> That confirms what I had suspected. You're not setting up the initial state of the button correctly, which means it won't show as toggled until some other action occurs. I've forked your codepen to fix the issues and you'll see it now works: https://codepen.io/lnewso/pen/RwZLBEq
> 
> To add more details about what's happening, the `formatter.formatChanged()` API being used will only fire when the format changes. Since the button isn't rendered/setup until the context toolbar is opened it won't register the format changed function until after the selection is already set and therefore the callback won't fire. As such, you need to ensure you always set the initial state via the `onSetup` function. Now the reason this works in the toolbar is it's rendered before the editor initializes, so therefore it does get the format changed callbacks as you change the selection within the editor.

It's working. Thanks @lnewson

**Comment by jdus** [comment]
> That confirms what I had suspected. You're not setting up the initial state of the button correctly, which means it won't show as toggled until some other action occurs. I've forked your codepen to fix the issues and you'll see it now works: https://codepen.io/lnewso/pen/RwZLBEq
> 
> To add more details about what's happening, the `formatter.formatChanged()` API being used will only fire when the format changes. Since the button isn't rendered/setup until the context toolbar is opened it won't register the format changed function until after the selection is already set and therefore the callback won't fire. As such, you need to ensure you always set the initial state via the `onSetup` function. Now the reason this works in the toolbar is it's rendered before the editor initializes, so therefore it does get the format changed callbacks as you change the selection within the editor.

Thanks for the explanation @krishnaeverestengineering. I have been reading the documentation and was following the example in https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/#togglebutton. Maybe setting the initial state explicitly, should be added to the documentation.

**Comment by krishnaeverestengineering** [comment]
> > That confirms what I had suspected. You're not setting up the initial state of the button correctly, which means it won't show as toggled until some other action occurs. I've forked your codepen to fix the issues and you'll see it now works: https://codepen.io/lnewso/pen/RwZLBEq
> > To add more details about what's happening, the `formatter.formatChanged()` API being used will only fire when the format changes. Since the button isn't rendered/setup until the context toolbar is opened it won't register the format changed function until after the selection is already set and therefore the callback won't fire. As such, you need to ensure you always set the initial state via the `onSetup` function. Now the reason this works in the toolbar is it's rendered before the editor initializes, so therefore it does get the format changed callbacks as you change the selection within the editor.
> 
> Thanks for the explanation @krishnaeverestengineering. I have been reading the documentation and was following the example in https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/#togglebutton. Maybe setting the initial state explicitly, should be added to the documentation.

Yeah @jdus , it would be great to add to the documentation. If possible please add the bit of explaination as well for understanding.
