### ISSUE TITLE
Using backspace to delete empty <p> nodes doesn't insert cursor into previous <span> correctly

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#733]
Description of problem: If I apply styling to some text, enter some newlines, then delete the empty lines, the toolbar (and queryCommandValue) return unexpected results

Reproduced on TinyMCE's demo

Steps to reproduce:
1. Apply some formatting (bold, italic)
2. Press Enter for a new line
3. Press Enter again
4. Press Backspace twice to delete the empty lines
-- Notice that the toolbar things the bold/italic styling is still applied
5. Begin typing

Expected result: My new text would be bold/italic

Actual result: The new text has no formatting

Looking at the content of the editor, the new text was entered outside of the styled &ltg;span>, ex: 
&ltg;p>
  &ltg;strong style="font-style: italic;">Some styled text&ltg;/strong>&nbsp;No longer styled
&ltg;/p>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5949](http://archive.tinymce.com/develop/bugtracker_view.php?id=5949) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_

> _**Tags:** [safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
