### ISSUE TITLE
drop event obj on editor is missing targetClone property in version 5, it is there on v4

### ISSUE THREAD

**Issue by shmdhussain** [tinymce/tinymce#7333]
**What is the current behavior?**

in version 4.x , when I drag and drop any dom element inside the editor, the drop event handler passes event object for ex : 

```editor.on("drop", function(eventObj){})```

the eventObj contains the targetClone property which is the clone of the currently dragged element.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

in version5.x , when I drag and drop any dom element inside the editor, the drop event handler passes event object for ex : 

```editor.on("drop", function(eventObj){})```

the eventObj **does not contain the targetClone** property which is the clone of the currently dragged element. 

We are relying on the targetClone property to determine which element is dragged.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

yes It is working in 4.x, but not in 5.x, we are trying to migrate from v4 to v5.

see the screenshots which i took by putting the breakpoint in firing of the drop event in version 4 and 5, you can see targetClone property is missing from v5

**version 4**
<img width="1789" alt="tinymce_v4_drop_event_targetClone_there" src="https://user-images.githubusercontent.com/4039657/138817807-b544e9cb-187f-445b-8975-0ef9f9529e96.png">

**version 5**
<img width="1792" alt="tinymce_v5_drop_event_targetClone_missing" src="https://user-images.githubusercontent.com/4039657/138817861-f312a98f-a3f5-4327-9f48-24f1f0789515.png">
<img width="1791" alt="tinymce_v5_drop_event_targetClone_missing_in tinymce_v5" src="https://user-images.githubusercontent.com/4039657/138817885-e95d7469-fa1c-42cc-89b1-5e0699ada497.png">

**Comment by lorenzo-pomili** [comment]
Hello @shmdhussain, it seems that this feature was never been officially supported, and was removed as it's not a native property on the [drop event](https://developer.mozilla.org/en-US/docs/Web/API/Document/drop_event).

We do however believe there is a bug whereby other drop event information is not being passed which might prevent you being able to do what you want (for example the `dataTransfer` property). If we fixed that, would that solve your use case? If not could you please provide some more information about what you are trying to do or what you need the old `targetClone` property for?

**Comment by shmdhussain** [comment]
@lorenzo-pomili thanks for getting back.

I will explain the scenario in the paper, see the below screenshot
![IMG_20220526_090358](https://user-images.githubusercontent.com/4039657/170419780-8041114b-5ae1-4ba6-8dd1-ecbcccb85b0a.jpg)

**Comment by TheSpyder** [comment]
This happened in #5936:
https://github.com/tinymce/tinymce/pull/5936/files#diff-14731f22f9be8d6212d23fc075a1da6b3a89f9865d9b975f7f966a345941af79L212

Previously these events did not have a type, now they are type `DragEvent` and so we can't include extra properties in them.

**Comment by shmdhussain** [comment]
Is there any workaround. So that I could solve my mentioned issue.

The dragged Dom element is having the type attribute which mentions whether it's video or article.
