### ISSUE TITLE
Different behavior when pasting text-only content

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#734]
Description of problem: Pasting text-only content (in this case from Notepad on Windows 7) with line breaks is not formatted consistently across browsers.

Steps to reproduce:
1. Copy the text below from Notepad on Windows using Ctrl + C
directory
contact
feedback
2. Paste the content using Ctrl + V in the TinyMCE Fiddle using Firefox 21.0
3. Paste the content using Ctrl + V in the TinyMCE Fiddle using Safari 5.1.7

Expected result: Content should be wrapped in a &ltg;p> tag in both browsers

Actual result: Content is wrapped in a &ltg;p> tag in Firefox but in a &ltg;div> tag in Safari

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5950](http://archive.tinymce.com/develop/bugtracker_view.php?id=5950) posted by [asiral](http://archive.tinymce.com/profile.php?name=asiral)_

> _**Tags:** [firefox safari safari5]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
