### ISSUE TITLE
Pasting plain text loses line breaks

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#735]
Description of problem: Pasting plain text appears to eat single &ltg;br> line breaks. I was pasting text from Notepad into IE and my single line breaks were all removed

Steps to reproduce:
1. Prepare some text in Notepad with line breaks
2. Copy all text
3. Paste text

Expected result: Text would be pasted with line breaks

Actual result: Single line breaks are removed

There appears to be an issue in the paste plugin, _preProcess() function that is intentionally removing these breaks: 
// IE9 also adds an extra BR element for each soft-linefeed and it also adds a BR for each word wrap break
process([
  [/&ltg;br>&ltg;br>/g, '&ltg;BR>&ltg;BR>'], // Replace multiple BR elements with uppercase BR to keep them intact
  [/&ltg;br>/g, ' '], // Replace single br elements with space since they are word wrap BR:s
  [/&ltg;BR>&ltg;BR>/g, '&ltg;br>'] // Replace back the double brs but into a single BR
]);

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5951](http://archive.tinymce.com/develop/bugtracker_view.php?id=5951) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_

> _**Tags:** [msie msie9 msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
