### ISSUE TITLE
table td border style merging: missing 'px'

### ISSUE THREAD

**Issue by syedadil010** [tinymce/tinymce#7359]
When the setContent() is used for HTML content, the border styles in td tag are merged and the resulting border style has a missing 'px' unit.
example: 
The following td tag
`<td
                      cname="TableCell"
                      width="100"
                      colspan="1"
                      style="
                        border-width: 1 1 1 1;
                        border-color: #000000;
                        border-style: solid;
                        mso-element: para-border-div;
                        font-family: tahoma;
                        font-size: 11;
                      "
                    >`

is processed to:
`<td
                style="mso-element: para-border-div; font-family: tahoma; font-size: 11; border: 1 solid #000000"
                colspan="1"
                width="100"
              >`
The border styles like border-width, border-color, border-style are processed and combined to just “border: 1 solid #000000 “ style. The issue is that the style should be “border: 1px solid #000000 “ to be recognized by Chrome.

I am using TinyMCE 5, Chrome on windows.

Any suggestions or solutions are welcomed.
Thank you in advance!

**Comment by TheSpyder** [comment]
Your input style `border-width: 1 1 1 1` is shorthand for `border-width: 1`, not `border-width: 1px`. This seems to be behaving correctly?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
