### ISSUE TITLE
AutoResize plugin iframe height is not being calculated correctly

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#736]
Description of problem: The &ltg;body> element has padding and margins, but when the parent iframe is resized, it is not taking these items into consideration. Since the body is the wrong size, there is a way to scroll some of the contents out of the iframe.

Steps to reproduce:
1. Use auto resize plugin
2. Inspect elements

See attached image

Expected result: &ltg;body> would fill up the iframe perfectly

Actual result: &ltg;body> overflows the iframe because the margin isn't used in the iframe height calculation.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5952](http://archive.tinymce.com/develop/bugtracker_view.php?id=5952) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_

> _**Tags:** [3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
