### ISSUE TITLE
image-tools html structure inconsistency between edit and view mode

### ISSUE THREAD

**Issue by nct124** [tinymce/tinymce#7361]
inconsistency  can be found on https://demo.wiris.com/integrations/tinymce/
in view mode the img is wrapped with a span tag
in edit mode the img is not wrapped with a span tag

possible to standardize it to be wrapped with a span tag? and give us the option to customize the classes on the span itself.

**Comment by lorenzo-pomili** [comment]
Hello @nct124, the MathType plugin is not developed by Tiny but by WIRIS, so I'm afraid Tiny can't provide any support for it. If you want you could try to contact them at their support at http://www.wiris.com/en/contact
