### ISSUE TITLE
Transifex subscription has expired

### ISSUE THREAD

**Issue by horus68** [tinymce/tinymce#7363]
**What is the current behavior? Describe the bug**
Transifex subscription has expired. 
The English language file its updated?
The translations are still used by the project?

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Go to Transifex https://www.transifex.com/projects/p/tinymce/

`This organization's subscription has expired. To keep using Transifex, please have an organization administrator subscribe to a plan again.
`
![tiny_transifex](https://user-images.githubusercontent.com/3055443/140486973-b9839d80-f921-4479-a7c7-45d919c4250f.png)

**What is the expected behavior?**
No subscription alert.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Collaborative translation

**Comment by Afraithe** [comment]
We are looking into this, Transifex is trying to get us to their current plans, we have been on legacy plans for ages, but something has gone wrong. TinyMCE should be on their free Open Source plan, but we do have other projects that are commercial.

**Comment by horus68** [comment]
Hope they find a solution to keep the Open Source plan maybe on software relevance.
Else you can try Crowdin, way better for us translators. 
They also have an Opens Source plan.

**Comment by Afraithe** [comment]
They recently changed their wording on the Open Source plan, and we have been on a legacy plan for a long long time, now they want to move us up and costs will potentially increase 10x. So yeah, we might be looking at an alternative, I am not a fan of Transifex myself, I think the interface is bloated, slow and hard to manage.

**Comment by Afraithe** [comment]
We have moved to Crowdin for translations.
