### ISSUE TITLE
bug in table plugin when creating multiple table heads ie.converting multiple rows to table heads .

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#738]
Description of problem:
bug in table plugin when creating multiple table heads ie.converting multiple rows to table heads .

Steps to reproduce:
1. create a table 
2. select multiple rows of the table i.e first two rows.
3. go to table row properties and select header
4. click on update button

you will notice that the first row selected is swapped with the other selected row .

Expected result: the rows must become header in the same order in which they were present before updating to header.

Actual result: the first row selected is swapped with the other selected row . and are not appearing in the order as they were present before updating to header.

Please find the attached document row.js for the solution .i have created list and putting the dom objects of the rows after first tbody.

Please suggest me if i have done something wrong.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5954](http://archive.tinymce.com/develop/bugtracker_view.php?id=5954) posted by [sahilmehra03](http://archive.tinymce.com/profile.php?name=sahilmehra03)_

> _**Tags:** [firefox msie safari chrome opera 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
