### ISSUE TITLE
Problem with page demo/valid-elements.md

### ISSUE THREAD

**Issue by GermanJablo** [tinymce/tinymce#7381]
Hi, I can't get valid and invalid HTML tag content filters to work. I also tried using the ones from the paste plugin like paste_word_valid_elements but the content is still pasted with excluded tags.

I thought that I was typing something wrong, but now I am inclined to think that it is a bug since the same thing happens in the demo of the documentation. For example, you declare bold text invalid, but it is perfectly usable.

> *affected page: https://www.tiny.cloud/docs/demo/valid-elements/*

```
    selector: `#${(target as HTMLDivElement).id}`,
    plugins: "paste",
    inline: true, // does not work in mobile
    forced_root_block: true,
    force_br_newlines: false,
    force_p_newlines: false,
    invalid_elements : 'strong,em',
    paste_merge_formats: true,
    paste_preprocess: (plugin: any, args: any) => {
      console.log("que trae",args.content);
      console.log(">>>>>>>>", args.content.split('</p>'));
    },
    paste_word_valid_elements: 'b,strong,i,em,h1,h2',

  }
```

The version I use is 5.8.2

**Comment by german-jablo** [comment]
Ok @tylerkelly13, thank you!

**Comment by german-jablo** [comment]
Hello, any updates on this? Is it just me who can't filter any HTML tags? From what I see from the demo in the documentation it seems not.
