### ISSUE TITLE
Cannot delete <hr> in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#739]
Description of problem: I cannot always delete horizontal rulers when using IE

Can reproduce using 4.x demo

Steps to reproduce:
1. Select all text in an editor with Ctrl + A
2. Press the Backspace key
3. Press the Delete key
4. Insert 2x horizontal rulers
5. Try to backspace to delete all &ltg;hr> 

Expected result: All &ltg;hr> would get deleted

Actual result: The first &ltg;hr> is not deleted. It actually looks like my cursor is somehow placed _inside_ the &ltg;hr> ???

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5955](http://archive.tinymce.com/develop/bugtracker_view.php?id=5955) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_
> 
> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age.

If you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
