### ISSUE TITLE
Only enable text pattern at beginning of paragraph

### ISSUE THREAD

**Issue by xingming2020** [tinymce/tinymce#7408]
I want to add some markdown grammar to the editor and I hope I can get a h1 element when I hit spacebar after a '#'.  

I read the document of [text pattern](https://www.tiny.cloud/docs/plugins/opensource/textpattern/) and I found the inline mode is what I expected.

`textpattern_patterns: [{ start: '#', end: '', format: 'h1' }]`

I can get an h1 element now when I enter the spacebar after a '#'. However, there is a problem that I will turn a whole paragraph into an h1 element when I enter '#+spacebar' in a paragraph. What I expect is the pattern is only enabled at the beginning of a paragraph. So I was wondering if it is possible to add an option such as:

`textpattern_patterns: [{ start: '#', end: '', format: 'h1', global: false }]`

After set the 'global' to false, the pattern only works at the beginning of a paragraph.

**Comment by teeej** [comment]
I second this request.

**Comment by autumninflab** [comment]
I second this request.
