### ISSUE TITLE
Unable to center text within a table cell when table is centered

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#741]
Description of problem:
When a table is centered we are unable to center the content of a cell.

Steps to reproduce:
1. Create a new table with 2 rows and 1 column
2. Type short text on first row
3. Type long text on second row
4. Center the table
5. Try to center the text in first row

Or just use the following html
&ltg;table style="margin-left: auto; margin-right: auto;">
&ltg;tbody>
&ltg;tr>
&ltg;td>This should be in the middle&ltg;/td>
&ltg;/tr>
&ltg;tr>
&ltg;td>A very long sentence so that the previous row can be centered within a cell&ltg;/td>
&ltg;/tr>
&ltg;/tbody>
&ltg;/table>

Expected result:
The text in the row should be centered

Actual result:
The text in the row is not centered.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5957](http://archive.tinymce.com/develop/bugtracker_view.php?id=5957) posted by [ahogue](http://archive.tinymce.com/profile.php?name=ahogue)_

> _**Tags:** [firefox msie safari chrome opera table center cell unable to]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Lkdaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
