### ISSUE TITLE
Tinymce 5.10.2 set figure element with custom formats like left or right won't work

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#7412]
I have set custom formats for example:

```
   alignleft: [
       {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,span,article', styles: {textAlign: 'left'}},
       {selector: 'img,table,figure', classes: 'imglinks'}
   ],
```
In tinymce 5.10.2 you cannot center or set left or right to a figure element

See code example here [https://codepen.io/cfconsultancy/pen/rNzggme](https://codepen.io/cfconsultancy/pen/rNzggme)

**Comment by cfconsultancy** [comment]
Solved it by setting the following

```
   alignleft: [
       {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,span,article', styles: {textAlign: 'left'}},
       {selector: 'img,table', classes: 'imglinks'},
       {selector: 'figure', collapsed: false, classes: 'imglinks', ceFalseOverride: true }
   ],
```

**Comment by pmacswebteam** [comment]
Hi @cfconsultancy, 
We are also trying to set up a style on figures. The trouble we are running into is that our figcaptions are being saved with `content-editable="true"`. Did you have the same issue? If so how did you solve it?
