### ISSUE TITLE
Cursor in IE doesn't show up in right spot when clicking

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#742]
Description of problem:

Multiple lines (&ltg;p>content&ltg;/p>) cause the cursor to end up in the wrong spot when clicking in IE8/9 beyond the p tag. 

Steps to reproduce:
1. Use IE8/9 (you self-loathing weirdo!)
2. Add multiple lines to the window by typing and hitting enter, enough to scroll the editor
3. Attempt to click

Expected result:

Cursor shows up where user clicks

Actual result:

Cursor shows up a line or two above where user clicks
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5958](http://archive.tinymce.com/develop/bugtracker_view.php?id=5958) posted by [maggiomj](http://archive.tinymce.com/profile.php?name=maggiomj)_

> _**Tags:** [msie msie8 msie9 ie ie8 cursor caret 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
