### ISSUE TITLE
Can't remove images with back or delete keys if floating left or right (Firefox 91+ specific)

### ISSUE THREAD

**Issue by e-gaulue** [tinymce/tinymce#7424]
**What is the current behavior? Describe the bug**
If I select an image in the tinyMCE editor and this image is floating left or right, then I can't delete the image by just pressing back or delete keys.

**What is the expected behavior?**
Image should disappear (be removed).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE is v4.9.11, and we didn't have this trouble with Firefox previous version.

Could anyone confirm and tell if it's Mozilla specific?

**Comment by zonnedauw** [comment]
Yes, I discovered this issue a while ago and would like to see this addressed :o)

**Comment by e-gaulue** [comment]
Hi,

Just to inform you about this bug report on Thunderbird 91: https://bugzilla.mozilla.org/show_bug.cgi?id=1742881

Was posted five days ago and still unconfirmed. I worry those two behaviours are linked (through gecko) and Mozilla will take a long time before focusing on it.

Regards,
