### ISSUE TITLE
Dragging links from outside the editor to inside does not work in Chromium

### ISSUE THREAD

**Issue by ariselseng** [tinymce/tinymce#7428]
**What is the current behavior? Describe the bug**
I cannot drag and drop links/elements from outside tiny to inside tinymce editor. This is only a problem in latest Chromium and not Firefox.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/yRhaab
Try to drag the "test link" down into the editor. It does not work in Chromium Version 96.0.4664.45 (Official Build).

**What is the expected behavior?**
The link should be created in the editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This worked in at least 4.6.1 and also works in latest cloud version in Firefox, but not Chromium or Google Chrome

**Comment by landtastic** [comment]
Hello,
I wasn't able to reproduce this on Chrome Version 96.0.4664.110 or Chromium Version 98.0.4753.0 on Mac OS. The link dragged into the editor as expected. What OS are you using?

**Comment by ariselseng** [comment]
I am on Manjaro Linux with Plasma.
My colleagues reproduced this on windows 10 as well. Let me see if latest chrome has fixed the issue.

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
