### ISSUE TITLE
Empty line ignored by HTML Parser for <i> tags when calling editor.getContent()

### ISSUE THREAD

**Issue by jcflow** [tinymce/tinymce#7441]
### **Current Behavior**
Editor doesn't recognize an empty line when using text with `<i>` tags when calling `editor.getContent()` (uses HTML Parser)

### **Steps to reproduce**
1. Add two lines of text(using line break) to editor.
2. Style the complete first line using `<i>` tag.
3. Position the caret at the end of the first line.
4. Add a line break(pressing enter). Leaving three lines of content leaving the middle one empty.
5. Notice that `editor.getContent()` returns a content that its middle line is `<p><i></i></p>` but it should be `<p><i>&nbsp;</i></p>` according to other other text styling tags like `<em>`. It can be confirmed that  this following these instructions using `<em>` instead if `<i>` text styling, in this case the result will be `<p><em>&nbsp;</em></p>`.
6. It also can be confirmed using `editor.getContent({format: 'raw'})`, this will return `<p><i><br data-mce-bogus=\"1\"></i></p>` and `<p><em><br data-mce-bogus=\"1\"></em></p>` for `<i>` and `<em>` styling respectively. So `<br>` is added on both cases, but not considered as `&nbsp;` for `<i>` when calling `editor.getContent()`.

### **Expected behavior**
After doing a line break after a `<i>` styled text, editor should recognize the empty line and should be returned as `<p><i>&nbsp;</i></p>` calling `editor.getContent()`

**Affected version:** TinyMCE ^5
**Affected browsers:** Firefox, Chrome

**Comment by hamza0867** [comment]
Hi @jcflow ,

We were not able to reproduce the error you mention in this ticket, can you please provide a replication case, such as on [fiddle](https://fiddle.tiny.cloud/) ?

Thank you
