### ISSUE TITLE
[6.0.0-alpha.20211210] default_link_target config is ignored

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#7460]
default_link_target:'_blank',
is ignored.

[https://fiddle.tiny.cloud/YRhaab/3](https://fiddle.tiny.cloud/YRhaab/3)

![image](https://user-images.githubusercontent.com/1309628/145603473-f3e6b32e-af3d-4cd6-bb29-8fc3ff09d7c4.png)

Browser: Chrome and Firefox
Tinymce Inline Mode [6.0.0-alpha.20211210]

Tiny <6.0.0 does not show this behavior

**Comment by lnewson** [comment]
Hi @Georg-Git,

This is expected as this option has been renamed to `link_default_target` as it was inconsistently named and we're trying to clean a lot of that up in 6.0. I've updated your fiddle to show it works with the new name: https://fiddle.tiny.cloud/YRhaab/4. It's worth noting a few other options for the link plugin have been renamed as well. See https://github.com/tinymce/tinymce-docs/pull/2185/files and https://github.com/tinymce/tinymce/blob/devleop/modules/tinymce/CHANGELOG.md#changed for the full list or more details.

I should also mention we're still looking at options on how migration from 5.x to 6.x can be made easier.
