### ISSUE TITLE
The editor.selection.getContent({ format: 'html' }) function returns list type <ul> instead of <ol> for the selected numbered list

### ISSUE THREAD

**Issue by jacifkusto** [tinymce/tinymce#7461]
**Current Behavior**
The function `editor.selection.getContent({ format: 'html' })` returns list type `<ul>` instead of `<ol>` for the selected numbered list.

**Steps to reproduce**
1. Add two lines of text to editor.
2. Select the added lines.
3. Create the numbered list clicking the "Numbered List" on the toolbar.
4. Call the `editor.selection.getContent({ format: 'html' })` function. 
5. Notice that `editor.selection.getContent()` returns a content that is wrapped with `<ul>` tag instrad of `<ol>` tag.
6. Notice that if selection contains any other content the result is correct. It is also correct when calling `editor.getContent()` function.

**Expected behavior**
The result of calling  `editor.selection.getContent({ format: 'html' })` function should be correct for the selected numbered list wrapped with `<ol>` tag instread of `<ul>` tag.

**Affected version:** TinyMCE ^5

**Comment by hamza0867** [comment]
Hello @jacifkusto 

I was not able to reproduce the bug. Can you please provide a [fiddle]( https://fiddle.tiny.cloud ) that reproduces the bug ?

Thank you

**Comment by hamza0867** [comment]
Hi @jacifkusto 

I was able to replicate the issue. Thank you for reporting this bug
