### ISSUE TITLE
Adding compiled version to repository/maintaining a repository with compiled version

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#747]
I would like a release version of TinyMCE 4 maintained in a Github repository for easier automation for pulling with Bower (https://github.com/bower/bower ).  In particular, I would like to update a plugin for using TinyMCE 4 with AngularJS (http://angularjs.org ), and the ability to pull a distribution version of the plugin through Bower would make it extremely convenient for developers using the plugin.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5964](http://archive.tinymce.com/develop/bugtracker_view.php?id=5964) posted by [Bahamut](http://archive.tinymce.com/profile.php?name=Bahamut)_
> 
> _**Tags:** [bower]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
