### ISSUE TITLE
add new Font Family in admin panel wysiwyg editor 

### ISSUE THREAD

**Issue by subineseller** [tinymce/tinymce#7481]
We are using Magento 2.3.3 and TinyMCE 3.

I need to add some new fonts to wysiwyg editor.

**Comment by landtastic** [comment]
Hi, unfortunately TinyMCE 3.x is no longer supported (see https://www.tiny.cloud/blog/tinymce-4-support-window/). TinyMCE 5 is our supported community version, I'd suggest upgrading and following the instructions for adding a custom font family here: https://www.tiny.cloud/blog/tinymce-custom-font-family/
