### ISSUE TITLE
[4.x] Menubar height

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#750]
I know, maybe you considered this when designing a new look, but please re-consider making menubar a little bit smaller. Currently it's 34px line for toolbar. I'd propose 20px. Or make css so simple that it would be possible to change the height with one line of css code.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5966](http://archive.tinymce.com/develop/bugtracker_view.php?id=5966) posted by [alec](http://archive.tinymce.com/profile.php?name=alec)_
> 
> _**Tags:** [4x]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
