### ISSUE TITLE
Can TinyMCE use `images_upload_url` with third-party image URLs?

### ISSUE THREAD

**Issue by grahamcracker** [tinymce/tinymce#7502]
Hello,

As documented, TinyMCE allows uploading images automatically — one defines a remote URL (`images_upload_url`) which is expected to upload the image and return the `location` for TinyMCE to use in markup.

However, when pasting or inserting an image from a third party URL — for example, `https://somecdn.com/image.png` — TinyMCE will simply embed the image with the third party source, instead of sending the URL to `images_upload_url` to be uploaded.

I've scoured through the docs [here](https://www.tiny.cloud/docs/configure/file-image-upload/) and haven't found any way to configure TinyMCE to do this. Which method can I override to upload images from URLs as well as local image uploads?

This seems like a pretty common use case to have in docs. It's expected many users will paste images from emails, websites and other sources and not realize that the image references will disappear at some point if not uploaded.

**Comment by Gagydzer** [comment]
up

**Comment by Bulala-liu** [comment]
any progress?

**Comment by Gagydzer** [comment]
Have anyone found any solution for this problem?

**Comment by pigfan** [comment]
I provide a way that how i handle this problem, and the code is as follows
```
options = {
  ...,
  paste_preprocess: (editor, args) => {
    if (/^https?\:\/\/.+(png|jpg)$/.test(args.content)) {
      args.content = uploadByThirdPartyUrl(args.content);
    }
  }
}

```
The [`paste_preprocess`](https://www.tiny.cloud/docs/tinymce/6/copy-and-paste/#paste_preprocess) allow us modify the pasted content before it gets inserted into the editor.
I judge if the pasted content is a third party URL; if true,  i will send it to the server and get a new URL to replace the original URL.

I don't know if my answer will help you, if not or has a better way, please let me know. Thanks :)

**Comment by Bulala-liu** [comment]
> I provide a way that how i handle this problem, and the code is as follows
> 
> ```
> options = {
>   ...,
>   paste_preprocess: (editor, args) => {
>     if (/^https?\:\/\/.+(png|jpg)$/.test(args.content)) {
>       args.content = uploadByThirdPartyUrl(args.content);
>     }
>   }
> }
> ```
> 
> The [`paste_preprocess`](https://www.tiny.cloud/docs/tinymce/6/copy-and-paste/#paste_preprocess) allow us modify the pasted content before it gets inserted into the editor. I judge if the pasted content is a third party URL; if true, i will send it to the server and get a new URL to replace the original URL.
> 
> I don't know if my answer will help you, if not or has a better way, please let me know. Thanks :)

args.content will not work asynchronously. 
I expect the replacement is asynchronous. For example, inserting  
loading placeholder into the target image position and replace it after the server returns the image url.

**Comment by pigfan** [comment]
@Bulala-liu 
```
      paste_preprocess: (editor, args) => {
        if (/^https?\:\/\/.+\.(jpg|png)$/.test(args.content)) {        
          upload(args.content).then(new_url => {
            const image = document.createElement('img')
            image.src = new_url
            const targetEl = editor.getDoc().querySelector(`#placeholder`)
            targetEl.parentElement.replaceChild(image,targetEl)
          })
          args.content = `<span id="placeholder">loading</span>`
        }
      }
```
like this?

**Comment by pigfan** [comment]
> > I provide a way that how i handle this problem, and the code is as follows
> > ```
> > options = {
> >   ...,
> >   paste_preprocess: (editor, args) => {
> >     if (/^https?\:\/\/.+(png|jpg)$/.test(args.content)) {
> >       args.content = uploadByThirdPartyUrl(args.content);
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The [`paste_preprocess`](https://www.tiny.cloud/docs/tinymce/6/copy-and-paste/#paste_preprocess) allow us modify the pasted content before it gets inserted into the editor. I judge if the pasted content is a third party URL; if true, i will send it to the server and get a new URL to replace the original URL.
> > I don't know if my answer will help you, if not or has a better way, please let me know. Thanks :)
> 
> for `paste_preprocess ` args.content will not work asynchronously, and unexpectedly, there is no way to prevent default paste...
> 
> I expect the replacement is asynchronous. For example, inserting loading placeholder into the target image position and replace it after the server returns the image url.

```
      paste_preprocess: (editor, args) => {
        if (/^https?\:\/\/.+\.(jpg|png)$/.test(args.content)) {        
          uploadByThirdPartyUrl(args.content).then(new_url => {
            const image = document.createElement('img')
            image.src = new_url
            const targetEl = editor.getDoc().querySelector('#placeholder')
            targetEl.parentElement.replaceChild(image,targetEl)
          })
          args.content = `<span id="placeholder">loading</span>`
        }
      }
```
like this ?
