### ISSUE TITLE
col element with span attribute

### ISSUE THREAD

**Issue by jbreure** [tinymce/tinymce#7507]
Hi,

I run into an issue when adding a column in a table has a colgroup containing col elements with span attribute. Here is an example: my table has four columns and this is the colgroup element:
`<colgroup><col span="2" /><col span="2" /></colgroup>`

When inserting a column before the last column, the table has 5 columns but this is the colgroup element:
`<colgroup><col style="width: 19.9892%;" span="2" /><col style="width: 24.973%;" /><col style="width: 24.973%;" /></colgroup>`
The number of col elements does not match the number of columns in the table which generates an error when the content is validated upon saving.

Thanks for providing a workaround or fixing it,

JB Reure

**Comment by linilini** [comment]
valid_children: '-table[colgroup],-colgroup[col]'

**Comment by jbreure** [comment]
While it would be better to delete the `colgroup` element as it would result in valid content, we use the `col` elements to store metadata against the columns (width, alignment, role) so ideally it should be retained.

Any chance to keep the `span` attribute on the `col` elements? so insert column before would result in a new `col` element inserted before the existing one, even if it has a `span` attribute. It may not be what the user wants but it's a possible outcome and it's valid content.
