### ISSUE TITLE
Document preview makes document dirty

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#751]
Description of problem:

When you preview a document using the preview plugin, it is marked as dirty, even when no changes were made.

Steps to reproduce:
1. Open a document
2. Do preview
3. Perform an action that depends on the dirty state or that shows this state in the debugger

Expected result:

The document should be dirty.

Actual result:

The document is dirty.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5967](http://archive.tinymce.com/develop/bugtracker_view.php?id=5967) posted by [wdonne](http://archive.tinymce.com/profile.php?name=wdonne)_

> _**Tags:** [firefox msie safari chrome opera preview dirty 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
