### ISSUE TITLE
Create custom button in toolbar to increase/decrease font size by one

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#752]
Quote: I would like to know how could someone create a custom button in toolbar, in order to increase or decrease editor's selected text font size , by one. The default "fontsizeselect" toolbar button makes you select from a dropdownlist. I want just to increase or decrease font size by one, like many applications do (e.g outlook). I use the modern theme.

Source: http://www.tinymce.com/forum/viewtopic.php?id=31226

Set font-size is complete missing in version 4?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5970](http://archive.tinymce.com/develop/bugtracker_view.php?id=5970) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** [4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
