### ISSUE TITLE
Different context menu depending on where in the editable area the user right click

### ISSUE THREAD

**Issue by jeme** [tinymce/tinymce#7529]
**What is the current behavior? Describe the bug**

Given a empty editor, or an editor that only has one line.

 a ) If I click at the top line of the editable area, I get the following browser context menu:
![image](https://user-images.githubusercontent.com/1609615/150133570-90cea24b-1193-4048-a4ed-ae6d8a57cfb5.png)

 b ) if I click anywhere below any lines/actual text context, yet still inside the editable area (the image pritty much shows where the click happened, approx at the top-left corner of the context menu), I get the following browser context menu instead:
![image](https://user-images.githubusercontent.com/1609615/150133624-f907d5d2-d5eb-473b-a3c5-c4d60090d86b.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

This is pretty much just the default setup given in the fiddle.tiny.cloud, except we have set the contextmenu option to false.
To make the issue more visible we could also set the height of the editor. But seeing as the standard height is enough I have not done that.

https://fiddle.tiny.cloud/aUhaab/1

**What is the expected behavior?**

That it always present the context menu of A when one right click inside the editable area.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Locally: TinyMCE 5.10.2, Windows 10, Chrome 97.0.4692.71 (also tested locally with Edge 97.0.1072.62)

**Furter information**

The cause seems to be that the height of the HTML and BODY inside of the editable area are only filing what fits the content rather than the editable area. 

It can be improved a great deal by setting the html elements height to 100% and then the body to calc(100% - 2rem) (the margin for the body element. Yet it leaves the area of the margin where the behavior persists. If it can be improved further I don't know, but I think the core solution should do better than what it is now.

Obviously the body height depends on the theme I guess, as if the theme changes the body margin, then the height should also be changed to match, but the default theme seems to use 1rem as margin, so the above values should work for that.

(Done in a debugger)

However, this seems to break the Autosize plugin. setting min-height to the above does not seem to work either. Setting min-height to a fixed value seems to work though. ~~So my guess is that the solution is to somehow set the height via javascript to the above value until there is overflow. Not sure how that might be possible.~~ So perhaps setting the min-height to the configured editor size or if the editor can be resized by dragging then update the internal min-height based on what it's resized to. Perhaps there are some other clever way to just figure out the height from the bounds.

**Comment by jeme** [comment]
This sill seems to be an issue in newest release.

**Comment by propertyhive** [comment]
The solution from @rstencel  worked for me. I found using 'min-height' instead of just 'height' on the html worked better, especially when a few lines had been entered into wysiwyg already and a scrollbar had appeared.

**Comment by jeme** [comment]
Due to TinyMCE swittching to GPL or Commercial (ref: https://github.com/tinymce/tinymce/issues/9453#issuecomment-2327646149) this issue is no longer relevant to me.
