### ISSUE TITLE
Spellchecker tries to access URL "undefined"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#753]
Description of problem:

Opening the spellchecker produces the error message "GENERAL". The error log shows that it tries to access a URL ending with "undefined".

Steps to reproduce:
1. Open a document
2. Select Tools->Spellchecker

Expected result:

Start checking.

Actual result:

"GENERAL" error message.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5968](http://archive.tinymce.com/develop/bugtracker_view.php?id=5968) posted by [wdonne](http://archive.tinymce.com/profile.php?name=wdonne)_

> _**Tags:** [firefox msie safari chrome opera spellchecker 4x 404]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
