### ISSUE TITLE
Move "bullist numlist outdent indent" to menubar

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#758]
I think "bullist numlist outdent indent" is very rarely needed and take too much space. I think the menubar is a better place for it.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5971](http://archive.tinymce.com/develop/bugtracker_view.php?id=5971) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** [4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This does not seem relevant for the latest version of TinyMCE.
