### ISSUE TITLE
Resizing table using resizer bars triggers blur

### ISSUE THREAD

**Issue by Evertvdw** [tinymce/tinymce#7605]
**What is the current behavior? Describe the bug**
Basically a recreate of [#4342. ](https://github.com/tinymce/tinymce/issues/4342). This issue still occurs in the latest v5 version, causing some issue for me. In short:

Resizing the table using the resizing bars (column lines/row lines) will cause the editor to blur. When resizing the whole table using the edge drag handles it does not do this and this is the correct behavior in my opinion.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/FVhaab

**What is the expected behavior?**
It should not cause blur when resizing using the resizing bars.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Previous correct version (based on previous issue) is 4.6.7, probably broken since then.

**Comment by 2sagarraut2** [comment]
I am facing a similar kind of issue, not able to resize or change width of the tables. Table properties are non editable. 
![Screenshot from 2022-02-15 10-18-34](https://user-images.githubusercontent.com/36417693/153994579-30e8ffdc-f9f0-4127-8ca7-a45e7967f7e2.png)
![Screenshot from 2022-02-15 10-21-46](https://user-images.githubusercontent.com/36417693/153994870-db4a318a-112d-4cf8-9d7a-3d046c579187.png)


whenever I click on table properties, menu is not opening
