### ISSUE TITLE
Pagebreak separator makes no difference to result

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#762]
Description of problem:

Steps to reproduce:
1. Init TinyMCE with pagebreak plugin and pagebreak_separator set to &ltg;!--break-->
2. Insert a pagebreak 

Expected result: HTML should insert &ltg;!--break--> where the pagebreak was inserted.

Actual result: HTML for pagebreak is still the default &ltg;!-- pagebreak -->

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5980](http://archive.tinymce.com/develop/bugtracker_view.php?id=5980) posted by [Nyorai](http://archive.tinymce.com/profile.php?name=Nyorai)_

> _**Tags:** [firefox msie safari chrome opera 40b3 pagebreak]_
> _**Status:** Open_
> _**Resolution:** Remind_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
