### ISSUE TITLE
Placeholder does not disappear when tapping the quick type for iOS keyboard

### ISSUE THREAD

**Issue by garyZlot** [tinymce/tinymce#7642]
**What is the current behavior? Describe the bug**
Placeholder does not disappear when tapping the quick type for the iOS keyboard

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
![591645173691_ pic](https://user-images.githubusercontent.com/4505169/154648234-596e386b-e8fe-46ca-9aa1-c39b56a8d2f9.jpg)

**What is the expected behavior?**
Placeholder disappear when tapping the quick type for the iOS keyboard

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Current version,   Chrome and Maxthon browser,  should be all browsers.   iOS 15.3.1. Previous versions have the same issue.

**Comment by 15666795711** [comment]
遇到了同样的问题，有解决方案吗
