### ISSUE TITLE
Reset background-color

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#766]
Set Background-color can not be reset to default value "transparent" only with "clear formatting". I dont think everyone understand this way. ;)
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5985](http://archive.tinymce.com/develop/bugtracker_view.php?id=5985) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [firefox msie safari chrome opera 4x]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
