### ISSUE TITLE
There is a problem with the positioning of the sub menu bar under the menu bar

### ISSUE THREAD

**Issue by SheenaghF** [tinymce/tinymce#7668]
**What is the current behavior? Describe the bug**
When the scroll bar appears on the page, there is a problem with the positioning of the secondary menu, which will not be adsorbed on the menu bar, but appear at the bottom of the page

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Abnormal
![image](https://user-images.githubusercontent.com/33509031/156288442-d5417b5f-70bc-40b5-962e-8fb24d30df3b.png)
natural
![image](https://user-images.githubusercontent.com/33509031/156288468-eaa56d5d-252a-4f80-9988-af1755b86fee.png)

**What is the expected behavior?**
I hope it can be adsorbed on the menu bar

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.10.3

**Comment by pablo-guelu** [comment]
I'm having the same issue

**Comment by TheSpyder** [comment]
yes see issue 3592 (or 5097)
