### ISSUE TITLE
target_list not respected

### ISSUE THREAD

**Issue by lublak** [tinymce/tinymce#7672]
**What is the current behavior? Describe the bug**

Currently i can't set target_list.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://fiddle.tiny.cloud/kYhaab

**What is the expected behavior?**

Hide or change the target_list.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

issue: 6.0.0

5.10.3 works fine

**Comment by TheSpyder** [comment]
It's been renamed `link_target_list`
https://github.com/tinymce/tinymce/blob/e52ad71b24d7498298845e488f5e483ab3f1c08a/modules/tinymce/CHANGELOG.md#L95

Sorry we don't have the migration guide ready yet.

**Comment by lublak** [comment]
@TheSpyder my fault.
Thanks for the answer :)

**Comment by Simbiat** [comment]
Probably needs to be updated in https://www.tiny.cloud/docs/plugins/opensource/link/#target_list

**Comment by lnewson** [comment]
@Simbiat that's the TinyMCE 5 documentation as shown in the top left, so that is correct. For TinyMCE 6 see the appropriate docs: https://www.tiny.cloud/docs/tinymce/6/link/#link_target_list

**Comment by Simbiat** [comment]
lol, it was so subtle, that I thought it was a decorative header 😅
