### ISSUE TITLE
Add ability to prevent text in expanding below bottom of edit  window

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#769]
This follows on from Bug #5978.

Basically - whilst you can set the original starting width and height of the tinyMCE edit area - there is no way of fixing the height.  

As the user types a scroll bar appears on the right hand side and text can be entered below the bottom of the editable area.

It would be useful to add a plugin (or option) to fix the maximum height of the area being typed.

I have tried:
$('textarea.storeForm').tinymce({
// General options
theme : "modern",
body_class: "fixedSizeEditor",
content_css : "/themes/icephorm/css/tinyMcefixedSize.css",
.....

the css file has just:

.fixedSizeEditor {
font-weight:bold;
height:185px !important;
max-height:185px !important;
}

This removes the scroll bars, but text can still be entered into the box below the 185px height - you can use cursor keys to scroll up and down.

It would be a useful feature to be able to limit the editable area to the viewable area.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T5987](http://archive.tinymce.com/develop/bugtracker_view.php?id=5987) posted by [rwap](http://archive.tinymce.com/profile.php?name=rwap)_
> 
> _**Tags:** [resizing fixed size]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
