### ISSUE TITLE
Link to `Full featured demo of TinyMCE` on README leads to 404 page

### ISSUE THREAD

**Issue by TildaDares** [tinymce/tinymce#7697]
The link to the `Full featured demo of TinyMCE` leads to a 404 page. I think the link should lead to https://www.tiny.cloud/docs/demo/full-featured/

**Comment by lnewson** [comment]
Hi @TildaDares, as was noted in the other issue you linked the TinyMCE 6 documentation was delayed and as such any TinyMCE 6 links in the README will be broken until that is released.

To repeat what was said there, in the meantime the 5.x readme still points to the old links:
[https://github.com/tinymce/tinymce/tree/release/5.10](https://github.com/tinymce/tinymce/tree/release/5.10)
