### ISSUE TITLE
The border table does not appear the same setting.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#771]
Description of problem:

Steps to reproduce:
1. Create any table, for example, 5x5.
2. After right click and setup border the table
3. The border does not appear.

Expected result: the border appear.

Actual result: the border does not appear, even setup border.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5988](http://archive.tinymce.com/develop/bugtracker_view.php?id=5988) posted by [liszkievich](http://archive.tinymce.com/profile.php?name=liszkievich)_

> _**Tags:** [firefox msie safari chrome opera 4x]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://www.tinymce.com/tryit/full.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
