### ISSUE TITLE
file_picker_callback provides progress callback function

### ISSUE THREAD

**Issue by OneSeven** [tinymce/tinymce#7711]
**Is your feature request related to a problem? Please describe.**

Provides a progress callback function just like images_upload_handler, uploading file or media through file_picker_callback requires progress prompt

**Describe the solution you'd like**
file_picker_callback provides progress callback function
**Describe alternatives you've considered**
file_picker_callback provides progress callback function

**Comment by gbirhanu** [comment]
I am looking for this feature also.
