### ISSUE TITLE
Avoid filter <img>

### ISSUE THREAD

**Issue by icaparros-at-wiris** [tinymce/tinymce#7716]
**What is the current behavior? Describe the bug**

With the new version of TinyMCE 6.0.0 the option `images_dataimg_filter` was removed. Is there some alternative to avoid filtering images.

![image](https://user-images.githubusercontent.com/91468181/159725759-8039b172-6e14-4d15-992a-38fd038b3895.png)

**What is the expected behavior?**
Render the image

![image](https://user-images.githubusercontent.com/91468181/159726318-4d01fa0a-e4e5-4381-bdcb-cdf2a388aac3.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- 6.0.0
- Linux
- Chrome

**Comment by Don-Cryptus** [comment]
would like to know aswell

**Comment by metricjs** [comment]
Hey @icaparros-at-wiris, could you please give us some more information about your use case? We may be able to offer another way of doing this, but it depends on what exactly you are trying to achieve. Are you wanting to preprocess images on insertion, content get, etc.? Or is it something else?

**Comment by icaparros-at-wiris** [comment]
Hey @metricjs,

We would like to avoid the image filtering through blob, as the `images_dataimg_filter` achieved, so that our image src remains intact with the information we fill it with. 

Our plugin can insert formulas as image and edit a previous image formula. Also filter all mathml inside the editor to render them as an Image using the `onBeforeSetContent` event. You can check our demo using Tinymce 5 [here](https://demo.wiris.com/integrations/tinymce/).

Thank you for your response, If you need more information I will be attentive to your answer.

**Comment by Don-Cryptus** [comment]
Hey @metricjs,

it would nice to be able to disable default blob conversion, like it was posible with ``images_dataimg_filter`` as it stated [here](https://www.tiny.cloud/docs/configure/file-image-upload/#images_dataimg_filter)

> Note: The images_dataimg_filter option can also be used to specify a filter predicate function for disabling the logic that converts base64 images into blobs while within the editor. Tiny discourages using images_dataimg_filter for this purpose.

**Comment by icaparros-at-wiris** [comment]
Hi @metricjs, any news?

**Comment by icaparros-at-wiris** [comment]
Fixed with Tinymce 6.1.0.

**Comment by Valgeria** [comment]
@icaparros-at-wiris 

Please share the Is there is alternative to avoid filtering images. You have mentioned fixed with 6.1.0. Please share with solution
