### ISSUE TITLE
Missing some core toolbar items

### ISSUE THREAD

**Issue by imansa** [tinymce/tinymce#7727]
**What is the current behavior? Describe the bug**
according to [online full featured samples](https://www.tiny.cloud/docs/tinymce/6/os-full-featured/), when following toolbars added to *toolbar* config, there is not any added tool for them in result.
- fontselect
- fontsizeselect
- formatselect

returned value from executing `tinyMCE.activeEditor.ui.registry.getAll().buttons` command in console is not contain any of above toolbars. this toolbars are from the core toolbar buttons.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
this is tested [here](https://fiddle.tiny.cloud/BZhaab) too with 6.0.0 and 6.0.1 versions

**What is the expected behavior?**
in older version there was three select input for this toolbars to choose font size, font family and sample formats. this features was in core plugins and according to [Beta version of docs](https://www.tiny.cloud/docs/tinymce/6/available-toolbar-buttons/) this buttons are available yet.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
in 6.* version this problem is exists. i am using Firefox 98.0 and Google chrome 99.0 in Fedora 35 Linux

**Comment by lostkeys** [comment]
Hi @imansa. We haven't released the final documentation yet which will happen with the TinyMCE 6.0 Enterprise release about to happen soon, fingers crosses, but the buttons are still there. From the [changelog](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/CHANGELOG.md):

- Renamed the `font_formats` option to `font_family_formats`
- Renamed the `fontselect` toolbar button and `fontformats` menu item to `fontfamily`
- Renamed the `fontsize_formats` option to `font_size_formats`
- Renamed the `fontsizeselect` toolbar button and `fontsizes` menu item to `fontsize`
- Renamed the `formatselect` toolbar button and `blockformats` menu item to `blocks`
- Renamed the `styleselect` toolbar button and `formats` menu item to `styles`
- Renamed the `lineheight_formats` option to `line_height_formats`

**Comment by imansa** [comment]
thanks a lot @lostkeys

**Comment by mateusfmello** [comment]
@lostkeys can you help us?

**Comment by dingetje** [comment]
Thanks for this, I only wished I've found it sooner.

**Comment by meco999** [comment]
@imansa Can I ask you the version of the problem you had at that time? I am also encountering this problem now😢
