### ISSUE TITLE
[Question] How to avoid uploading draft files?

### ISSUE THREAD

**Issue by ttc0419** [tinymce/tinymce#7730]
If you enable automatic_uploads, the files will be uploaded to server once they added to the editor.  However, if the form was not submitted by the user, the files will still be stored on the disk.  Is there any way to avoid this?

**Comment by Afraithe** [comment]
Well there are various ways you could set this up (delete temp files etc). But easiest might be to disable automatic uploads and instead trigger editor.uploadImages(); when you save your document, and only images that are currently in the content will be uploaded.

**Comment by Galaxy0419** [comment]
@Afraithe Thanks for the suggestion, however, if I disable automatic uploads, the images will be encoded as base64.  This can easily exceed row limit of some databases.  Is there a way to disable this behavior?

**Comment by Afraithe** [comment]
They should only be base64 until you run editor.uploadImages() and they should be converted (to a image file link) if you have everything setup to upload like you did before you disabled automatic uploads.

**Comment by Galaxy0419** [comment]
@Afraithe I'm still a bit of confused, is there any example code and document for that?
