### ISSUE TITLE
No possibility to clear the selected cells background using the "Cell Properties" dialog

### ISSUE THREAD

**Issue by jacifkusto** [tinymce/tinymce#7731]
**Current Behavior**
No possibility to clear the selected cells background using the "Cell Properties" dialog.

**Steps to reproduce**
1. Insert a table 3x3.
2. Select 2 or more cells.
3. Right click -> Cell -> Cell Properties.
4. Go to the Advanced Tab.
5. Select any color (orange for example) for the Background Color and click Save.
6. The selected cells background is filled now.
7.  Select these cells again.
8. Right click -> Cell -> Cell Properties.
9. Go to the Advanced Tab.
10. Select "Remove color" for the Background color and click Save.
11. Notice that the selected cells background is still filled.

**Expected behavior**
The background color of the selected cells should be removed after selecting "Remove color" in the "Cell Properties" dialog and click Save.
The issue is not reproduced for the only selected cell.

**Affected version:** TinyMCE ^5

**Comment by TheSpyder** [comment]
There's a similar problem with removing cell heights that we're about to look at. I'll make a note to check whether it's a general problem with the cell properties dialog, in which case this will be fixed at the same time.

**Comment by lnewson** [comment]
This has been fixed in TinyMCE 6.0.3 which has now been released to the community.
