### ISSUE TITLE
TinyMCE 6 missing plugins

### ISSUE THREAD

**Issue by dmitrue** [tinymce/tinymce#7732]
Hi there,

Rails 7 + esbuild app, I get an error after upgrading to tinyMCE 6 that `print` and `paste` plugins are missing. 

`import tinymce from 'tinymce'`
`import 'tinymce/themes/silver/theme'`
`import 'tinymce/icons/default/icons'`
`import 'tinymce/plugins/autoresize'`
`import 'tinymce/plugins/autolink'`
`import 'tinymce/plugins/print'`
`import 'tinymce/plugins/preview'`
`import 'tinymce/plugins/anchor'`
`import 'tinymce/plugins/paste'`
`import 'tinymce/plugins/wordcount'`
...

**Comment by lnewson** [comment]
HI @dmitrue,

This is expected as both of those plugins have now been merged into the TinyMCE Core as of 6.0.0. From the [changelog](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/CHANGELOG.md):

> - Moved the `paste` plugin's functionality to TinyMCE core #TINY-8310
> - Moved the `print` plugin's functionality to TinyMCE core #TINY-8314

As such you can now exclude these from your above import list and it should still work largely the same. One thing to note however is that the paste Word cleaning logic was removed in TinyMCE 6:

> - Removed support for Microsoft Word from the opensource paste functionality #TINY-7493

**Comment by lnewson** [comment]
Oh, one other thing I should add is that if you are using a bundler then there is one other file you'll need to include alongside the theme and icons:
```
import 'tinymce/models/dom/model'
```

This will be included in the TinyMCE 6 documentation we're hoping to release soon.

**Comment by dmitrue** [comment]
@lnewson Thank you for your reply! But what about other plugins, after removing `paste` and `print` import statements I'm now getting `Failed to load plugin: autoresize autolink lists from url plugins/autoresize autolink lists/plugin.js`

**Comment by dmitrue** [comment]
Thank you, really appreciate that!

**Comment by lnewson** [comment]
@miedzikd it was also merged into the core editor. The migration guide is now available and the section about removed plugins is here: https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#removed-plugins
