### ISSUE TITLE
Cannot load protected images with Firefox

### ISSUE THREAD

**Issue by francoisfreitag** [tinymce/tinymce#7746]
**What is the current behavior? Describe the bug**

I’m using the [image plugin](https://www.tiny.cloud/docs/tinymce/6/image/) to upload images to my servers. The images are only accessible to users who uploaded them: the web server checks the session cookie from the request.

Starting with TinyMCE 6, Firefox users cannot see images they have uploaded. I believe the cause to be https://bugzilla.mozilla.org/show_bug.cgi?id=1741489.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

STR:
1. Download [project.tar.gz](https://github.com/tinymce/tinymce/files/8473838/project.tar.gz)
2. `mkdir project && tar -xf project.tar.gz -C project`
3. `cd project`
4. `php -S localhost:3001`
5. With Firefox, visit http://localhost:3001/index.php
6. Notice image does not load

![image](https://user-images.githubusercontent.com/2758243/162987452-5b9621ce-5797-4eb3-873b-00cd2870b90c.png)

**What is the expected behavior?**

The image loads.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Failure reproduced with Firefox 99.0, 100.0b4. Success obtained with Chromium 100.0.4896.75.
My OS is ArchLinux.
Version 5.10 of TinyMCE is not affected by this issue.

---

I understand the issue is caused by Firefox, but I’m probably not the only TinyMCE user affected by this behavior. I figured a GitHub issue would raise awareness and may help identifying workarounds.

**Comment by ssddanbrown** [comment]
I can confirm this behaviour. This appears to be trigged by the use of the `srcdoc` attribute, for which it seems Firefox treats as a third party separate origin when it comes to cookies, so non-`None` samesite cookies will not be included in any outbound requests, including for images.

I could not see any way to work-around the [usage of srcdoc](https://github.com/tinymce/tinymce/blob/ad69ad9f749775e7ed961cc9710755de4b7f12fe/modules/tinymce/src/core/main/ts/init/InitContentBody.ts#L486) via official methods/API/options. For now I am making the following modification to the minified JS source to work around it (Not fully tested):

```javascript
// Find:
t.srcdoc=e.iframeHTML
// Replace:
t.contentDocument.open();t.contentDocument.write(e.iframeHTML);t.contentDocument.close();
```

**Comment by lnewson** [comment]
Hi,

Thanks for this detailed report and we can confirm this behaviour as well. We've logged a task internally to look at swapping how the iframe content is loaded back to the older `iframe.contentDocument.write()` browser APIs for Firefox specifically until the linked Firefox bug is fixed.

**Comment by francoisfreitag** [comment]
I confirm it fixes the issue in my project, thanks a lot for the fix! :grin:
