### ISSUE TITLE
Filter or Remove Emoticons

### ISSUE THREAD

**Issue by SHRIVES23** [tinymce/tinymce#7755]
I can see the option to add emoticons, is there a way to remove certain ones? For example, we can't show the middle finger emoticon on our site, so I need to remove it.

**Comment by lnewson** [comment]
Hi @SHRIVES23,

The only way to do this currently would be to copy the [default emoji database](https://github.com/tinymce/tinymce-dist/blob/master/plugins/emoticons/js/emojis.js) and then tweak it to provide your own version using the `emoticons_database` and `emoticons_database_url` options. As such I'm going to label this as a feature request for our product team to consider to have something similar to the `emoticons_append` option, except for removing default emoji.
