### ISSUE TITLE
How to add checkbox in to the toolbar menu

### ISSUE THREAD

**Issue by shankar5147** [tinymce/tinymce#7759]
I am using  tinymce5 version. plz help to add custom checkbox in toolbar list
![checkbox-tiny](https://user-images.githubusercontent.com/43570538/163992771-3466fee5-1e70-43f7-a5fa-b15661ee855e.png)

**Comment by mrinasugosh** [comment]
I would recommend looking at this, the support is for 4 onwards for this ui checkbox
https://www.tiny.cloud/docs-4x/api/tinymce.ui/tinymce.ui.checkbox/
