### ISSUE TITLE
Media changing source bug

### ISSUE THREAD

**Issue by BarneyCoding** [tinymce/tinymce#7772]
In version 6.0, after uploading a youtube video to a media input, if I tried to change the video source of the media input to another youtube video, it just wont work..it used to work just fine in version 5.0

**Comment by TheSpyder** [comment]
Good catch! We've logged this as a bug internally.

**Comment by BarneyCoding** [comment]
Hi, so the bug is fixed, right? It will be available in the next release? Cos now I still facing the same bug in my project..sorry I am new to this TinyMCE..hahaha

**Comment by lnewson** [comment]
Yes, this will be available in the 6.0.2 release which should be made available within the next couple of days. If you're using Tiny Cloud, then that will be about 1 week behind the community release.

**Comment by BarneyCoding** [comment]
alright...thank you very much =)

**Comment by lnewson** [comment]
TinyMCE 6.0.2 has now been released to NPM and other community downloads. Thanks again for letting us know of this issue!
