### ISSUE TITLE
RTC plugin with self hosted editor

### ISSUE THREAD

**Issue by BickelLukas** [tinymce/tinymce#7774]
**What is the current behavior? Describe the bug**
I am bunding/self hosting the editor. 
When I want to add the rtc plugin it tries to load the plugin from localhost and I get the follwing error:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/16354178/164487227-4cbd3308-e6e9-4eb5-8a66-5f3e83fb4274.png">

I cannot bundle the rtc plugin with the app since it not available in the npm package. 

I tried manually downloading the plugin.min.js which gets downloaded when I don't bundle the editor but this gives me the following error:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/16354178/164487085-5b9df269-8665-4458-b94b-2211529e407f.png">

**What is the expected behavior?**
I want to be able to use RTC with a self hosted instance of the editor. The plugin can either be downloaded from the cdn or be added to the npm package.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE Version: 6.0.1 (i have not used older versions)
Browser: Google Chrome 100.0.4096.127

**Comment by lnewson** [comment]
Hi, thanks for the report. Real-time collaboration is a premium product, so I'm afraid we can't assist via GitHub. If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new

That said, I can confirm that the RTC plugin cannot currently be used for self-hosted deployments and only works when used with Tiny Cloud. I believe there are plans to make it available for self-hosted but there isn't a scheduled date for that yet to my knowledge.

**Comment by BickelLukas** [comment]
Hi, I do not have a support subscription (yet) because we are still evaluation tinymce for our project. 

But I just wanted to explain the use case here as it might aid you in the design of the feature.
We need the core editor to work while offline (in a PWA or capacitor app). Therefore we need to bundle the scripts with our application and can not load them from the CDN. 
Since the RTC functionality only works while online, its OK for that script to be loaded from the CDN but it needs to "gracefully" fail when offline.

If you have any questions, don't hesitate to ask

**Comment by mryellow** [comment]
I'm having this come up on a non-premium self-hosted integration.

It does not appear in local dev, then comes up once on server.
