### ISSUE TITLE
Same Paste Is Not Working In TinyMCE

### ISSUE THREAD

**Issue by akashhdeep** [tinymce/tinymce#7788]
**Whenever I'm trying to paste the same text in TinyMCE it's showing a validation error **This field is required** **

![image](https://user-images.githubusercontent.com/91879324/165448673-8df215b9-b66a-4532-9e7d-436bf81d8df9.png)

**Comment by akashhdeep** [comment]
@ttcremers @leemhenson @simeng @threebytesfull Please Help me through this issue

**Comment by metricjs** [comment]
Hi @akashhdeep, the error you are seeing is part of the app that integrates TinyMCE, not TinyMCE itself. If you are not the maintainer of that app, please contact them for support. If you are, please give us more information about your integration and how that error is triggered, and we may be able to assist.

**Comment by akashhdeep** [comment]
Hi @metricjs Thanks for your fast reply.

I'm trying to update something by pasting the text in TinyMCE, It's updating for the first time but when I'm trying to paste that same text content for the second time and trying to update it's showing the validation error of **This field is required**

This is the error
![image](https://user-images.githubusercontent.com/91879324/165452640-61834c17-2159-4608-ba71-193563c9d671.png)

Code snip
![image](https://user-images.githubusercontent.com/91879324/165452531-8358a756-99a0-48d1-bbc1-3341c7e403c9.png)

**Comment by akashhdeep** [comment]
@metricjs Any Updates regarding the issue?
