### ISSUE TITLE
Azure web firewall is blocking TinyMCE editor Content

### ISSUE THREAD

**Issue by itsmehaboob** [tinymce/tinymce#7789]
When copying and pasting content from one TinyMCE editor to another I can see the format is changed in the source and sometimes new scripts adding in between the lines like <![if !supportLists]>. Azure Firewall is blocking the content from TinyMCE if we copy and paste the content how can I copy the exact content from the editor?

using tinymce js Version: 1.12.0-18

**Comment by gagaltotal** [comment]
because tinymce your version vlunerability xss
upgrade in latest version, example : Upgrade tinymce to version 5.10.7, 6.3.1 or higher.
referensi XSS tinymce : https://security.snyk.io/vuln/SNYK-JS-TINYMCE-3166281
