### ISSUE TITLE
Can't remove a table in RTC

### ISSUE THREAD

**Issue by dynafer** [tinymce/tinymce#7799]
**What is the current behavior? Describe the bug**
After pasting a table from word or excel by using powerpaste plugin in RTC, can't remove the table.

**Comment by lnewson** [comment]
Hi, RTC is a premium product so I'm afraid we can't assist via GitHub. If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new

Having said that though, RTC does not currently support tables as per https://www.tiny.cloud/docs/rtc/rtc-supported-functionality/#tinymcefeaturespluginssupportwhenusingrtc
