### ISSUE TITLE
"A" Tag without "Title" Attribute

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#780]
Description of problem:

Steps to reproduce:
1. when I create a link, there is no "Title" attribute

Expected result:

Actual result:
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T5999](http://archive.tinymce.com/develop/bugtracker_view.php?id=5999) posted by [klauxer](http://archive.tinymce.com/profile.php?name=klauxer)_

> _**Tags:** [firefox msie safari chrome opera links 4x]_
> _**Status:** Verified_
> _**Resolution:** Remind_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
