### ISSUE TITLE
name attribute is removed from img tag when calling getContent()

### ISSUE THREAD

**Issue by anormal81** [tinymce/tinymce#7812]
We updated from version 5.6.1 to 5.10.2 and also checked in 5.10.4.

I inserted an image tag with data URI and a name attribute. E.g. `<img src="data:image/png;base64,iVBOR...... name="myfilename.png>`

Calling `getContent({ format: 'html' })` returns the HTML including the image tag. But the name attribute is removed. 
Calling `getContent({ format: 'raw' })` returns the raw content. the name attribute still exists here.
No difference when defining in valid_elements or extended_valid_elements.

Expected: name attribute should still be in the output.

Worked in 5.6.1.

**Comment by anormal81** [comment]
Needs to be fixed!

**Comment by anormal81** [comment]
Ups, wrong button pressed. Not closed for now.

**Comment by reitanAndreas** [comment]
Needs to be fixed

**Comment by spocke** [comment]
The `name` attribute is deprecated on images so no longer valid HTML. It's recommended to use `id` instead.
If you still need the name attribute you should be able to configure it in using the `extended_valid_elements` option.
