### ISSUE TITLE
Dialog is not rendered in a root which causes stacking context problems.

### ISSUE THREAD

**Issue by liesahead** [tinymce/tinymce#7814]
**What is the current behavior? Describe the bug**
Source dialog is rendered right after the toolbar. So both depend on `fixed_toolbar_container` setting.
![image](https://user-images.githubusercontent.com/32300784/167632875-ee03fa2c-3a05-48fe-bc85-378a3cb041e7.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Create some element with position relative + some positive `z-index`
2. Render editor after that element
3. Open source dialog

**What is the expected behavior?**
It would be better to render it directly to the `body` (`documentElement`) html element. Or at least add some config setting which would accept the element/selector where to render the dialogs.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Npm packages:
* "@tinymce/tinymce-angular": "^6.0.1",
* "tinymce": "^6.0.2",

Browser:
* Google chrome version 100.0.4896.127 (Official Build) (64-bit)

OS:
* Windows 11

**Comment by liesahead** [comment]
This happens when `fixed_toolbar_container` is set. When it's not set the toolbar is positioned into body so are dialogs. Why are dialogs tied to the toolbar?

**Comment by liesahead** [comment]
This also causes problems with menu.

![image](https://user-images.githubusercontent.com/32300784/180755241-c637a8d4-b9ed-4908-802d-fb902ebab0d3.png)

**Comment by TheSpyder** [comment]
We're actually looking at an adjustment to separate the dialogs into their own root element for other reasons. I'm not sure if this plan will fit into the next release scope but it sounds like it would resolve that issue.

The menus look like a different issue - we need those tied to the toolbar so they scroll together. However they should be positioning themselves so they're not squished up against the edge of the view like that.

**Comment by liesahead** [comment]
But is it going to be present in v5? As we cannot migrate to v6 due to missing `forced_root_block` setting.

**Comment by liesahead** [comment]
@TheSpyder , up

**Comment by liesahead** [comment]
@TheSpyder , ping

**Comment by liesahead** [comment]
Is this going to be fixed in v6?

**Comment by TheSpyder** [comment]
My apologies, the change is nearly complete, I forgot to link this to the tracking ticket where we collected all the similar reports - #5097

Further updates are in that issue. And no, sorry, this will not be changed in v5.
