### ISSUE TITLE
TinyMCE in Twitter Bootstrap modal: can't insert/edit links

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#782]
We use TinyMCE in a Twitter Bootstrap modal box. In TinyMCE 4 however, we can't insert/edit links. I've supplied a clean as possible example, a default bootstrap Modal w/ default tinyMCE on the latest versions of Twitter Bootstrap (2.3.2) and TinyMCE (4.0 stable) via CDN's. 

Steps to reproduce:
1. See the JSfiddle example above
2. Open the Bootstrap Modal via the [Launch TinyMCE in bootstrap modal] button
3. Put your cursor in a link in the text, click the highlighted [insert/edit link] icon
4. Try to change the Url input element.
4a. Chrome, Safari and Firefox can't even focus the input element to edit the text
4b. IE 9/10 can focus the input element, but does not save the edited text when clicking the [Ok] button.

The same thing pretty much happens when adding a new link on a random text.

Tested in Chrome 27, FireFox 21, Safari6, IE 9/10

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6001](http://archive.tinymce.com/develop/bugtracker_view.php?id=6001) posted by [Neejoh](http://archive.tinymce.com/profile.php?name=Neejoh)_
> 
> _**Tags:** [firefox msie safari chrome link 4x]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/Neejoh/e99xf/7/_

**Comment by icamys** [comment]
@TinyMCE-User Thanks for the link. Works for me. Having bootstrap TinyMCE v4.3.11 and Bootstrap v3.3.5.

**Comment by 1eddy87** [comment]
Are you guys going to be fixing this issue?

**Comment by larrylin17** [comment]
@TinyMCE-User It works to me. Thank you!

**Comment by championchap** [comment]
Still seeing this issue with Bootstrap 4.0.0 and TinyMCE 5.0.3

**Comment by RoyVoetman** [comment]
The previous answer doesn't seem to work with Bootstrap v4 and TinyMCE v5. This is the modified solution should work:

` $(document).on('focusin', function(e) {
        if ($(e.target).closest(".tox-textfield").length)
            e.stopImmediatePropagation();
  });`

**Comment by Kasheftin** [comment]
I use the different modal dialog (vuetify instead of bootstrap) and none of the above works for me.

**Comment by Kasheftin** [comment]
Vuetify widely uses stopPropagation. I was able to make it work with tinymce in popup by changing `jquery on` with addEventListener + useCapture (working with tinymce 5.0.11 and vuetify 1.5.14):
````
mounted () {
  document.addEventListener('focusin', this.focusinTox, true)
},
beforeDestroy () {
  document.removeEventListener('focusin', this.focusinTox, true)
},
methods: {
  ...
  focusinTox (event) {
      if ($(event.target).closest('.tox-dialog').length) {
        event.stopImmediatePropagation()
      }
  }
}
````

**Comment by lnewson** [comment]
Sorry for not updating this sooner, however this is unfortunately a limitation of bootstrap dialogs as it's blocking TinyMCE from getting focus. As such we've documented this limitation and documented the workaround here:
- TinyMCE 4: https://www.tiny.cloud/docs-4x/integrations/bootstrap/#usingtinymceinabootstrapdialog
- TinyMCE 5: https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog

**Comment by khabibulinalina** [comment]
@lnewson how i can fix this problem in angular 8?

**Comment by lnewson** [comment]
I'd suggest reaching out to the various library you're using and asking for help there, as we can't provide details for every framework sorry. The general problem is that they are blocking focus switching to other modals that are opened.

**Comment by Sperovita** [comment]
I'm using Bootstrap 4 and Tinymce 5 and the focusin event listener wasn't working. The event is running on focusin, but stopImmediatePropagation wasn't doing anything for me. Since the issue is that the tinymce dialog is outside the modal I just pulled it into the modal and it works fine for me. It's in a single reusable modal in vue, so might not work where you have multiple modals, unless you have it pulling the tox dialog into the modal on open. I just put the move in the promise returned from `tinymce.init()`.

```javascript
tinymce.init({ ... }).then(editor => {
    const tinyAuxEl = document.querySelector('.tox-tinymce-aux');
    const modalBodyEl = this.$refs.modalBody; // if using something else just grab your modal body element here
    modalBodyEl.appendChild(tinyAuxEl);
})
```

Not too sure what else that tox-tinymce-aux classed element is used for, or if there may be multiple, but this works for my use case.

**Comment by jyotisingh144** [comment]
For bootstrap 5 and Tinymce v4.7.9

Try

 document.addEventListener('focusin', function(e) {
    if (e.target.closest(".mce-window") !== null) {
    e.stopImmediatePropagation();
    }
  });
It works for me

**Comment by rahimnagori** [comment]
> e.stopImmediatePropagation();

This works for me. Thanks.
