### ISSUE TITLE
Bad translation about image_caption

### ISSUE THREAD

**Issue by eanon** [tinymce/tinymce#7827]
Hello, Don't know if this is the right place for this localization related issue (don't hesitate to tell me), but well...

**What is the current behavior? Describe the bug**
Installing the French pack, when I enable "image_caption: true" for the image plugin, it adds a checkbox called (in French) "Afficher le sous-titrage". This translation is wrong: a "sous-titrage" in French means "subtitle" not "caption". This translation should be replaced with the word "légende". So, for example: "Afficher une légende".

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Install the French pack and enable image_caption.

**What is the expected behavior?**
"Afficher une légende" instead of "Afficher le sous-titrage".

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Self-hosted TinyMCE 6.0.2.

**Comment by lnewson** [comment]
Hi @eanon, those translations are community provided and done via CrowdIn: https://crowdin.com/project/tinymce. Feel free to contribute this fix yourself via https://crowdin.com/translate/tinymce/40/en-fr?filter=basic&value=0#q=Caption otherwise we can make the change for you.

**Comment by eanon** [comment]
OK @lnewson, done, I submitted my suggestion on CrowdIn.

**Comment by lnewson** [comment]
Thanks @eanon! The change should already be available via the language pack downloads: https://www.tiny.cloud/get-tiny/language-packages/
