### ISSUE TITLE
Uncaught (in promise) ... QN.convertURL ... images_upload_handler

### ISSUE THREAD

**Issue by Deewde** [tinymce/tinymce#7839]
Hi,

I've successfully uploaded content together with **base64** inline image data in _v5_, but now with this forced move to Promises everything broke. I finally decided to put in the time to migrate to _v6_ and now I'm left with a pesky error.

My flow is the following:

1. user injects an inline image in the content
2. `automatic_uploads` is set to false, so nothing happens immediately
3. when the user's done editing, he hits a Save button on the page and that triggers `tinymce.activeEditor.uploadImages();`
4. that triggers the new images_upload_handler (error appears at this point) which finds the image on the page and sets its src to the inline base64 and the posting continues
5. everything works the way I need it to, except for that error. No functionality is affected, but the error is annoying

I realize the docs state that the `resolve()` should be called with the location of the image (which in my case doesn't exist because I don't want to do an actual separate upload on the server) but this doesn't affect the error in any way. I've tried relative URLs, absolute URLs of actual images on the internet, other domains, same domain as the editor, no kind of passed variable type satisfies the nasty code that generates this fault.

Some assistance would be much appreciated.

> images_upload_handler: (blobInfo, progress) => new Promise((resolve, reject) => {
>  resolve(blobInfo);
> }).then(function(blobInfo) {
>  ...
> }).catch((error) => {});

> tinymce.min.js:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
> at QN.convertURL (tinymce.min.js:9:380671)
> at tinymce.min.js:9:230136
> at tinymce.min.js:9:230274
> at H (tinymce.min.js:9:3236)
> at tinymce.min.js:9:230008
> at tinymce.min.js:9:229445

**Comment by TheSpyder** [comment]
It's hard to know without the full code. Depending on the implementation of your `.then(function(blobInfo) {` function you might actually be resolving with `undefined`, not the string you intended to. Note that `resolve` is provided as a part of the construction of `new Promise()`, not by TinyMCE itself. This piece of code is perhaps not doing what you think it is:

```
new Promise((resolve, reject) => {
  resolve(blobInfo);
})
```

How did you deal with this in v5? Were you just never calling the success function?

Have you tried resolving with the base64 data rather than updating the `src` attribute yourself?

TinyMCE does not validate that the resolved value is a string, so if you return a promise resolved to anything other than a string it will fail. Perhaps it could fail in a nicer way, but it will always fail.

**Comment by Deewde** [comment]
You're correct, I was resolving without a return. So now I'm left with these less than ideal situations:
- no return and I get the original error; everything works fine
- return an empty string; visually is fine in the editor, no error but no src is present in the POST-ed image in the content
- return the base64 data; visually is not fine, I just see the label where the image should be, I get an invalid URL error in the console, but the data gets correctly POST-ed

> How did you deal with this in v5? Were you just never calling the success function?

That's correct

**Comment by Deewde** [comment]
So is there any way in which I can accomplish what I need, which is uploading the content together with images with base64 data urls while keeping the rendering fine in the editor?

If there is not, do you foresee any problems with no return value and the original Promise error?

**Comment by TheSpyder** [comment]
_something_ needs to be returned, or this code will fail trying to call `then()` on it:
https://github.com/tinymce/tinymce/blob/731754d6019938fd74d4d8c233423d3fcdb1148c/modules/tinymce/src/core/main/ts/file/Uploader.ts#L164-L166

In theory returning a promise that never resolves is the equivalent to never calling success in v5, but that would result in a memory leak. This might be acceptable if the page is closed shortly afterwards but that's up to you.

The best way to accomplish this is not using the upload handler to manage the base64 data. A filter to replace the `src` attributes during the `getContent()` process would be much more reliable. Which brings me to my suggestion...

I'm a little confused why you're doing this manually; by default tinymce replaces blob image URLs with the base64 data during the `getContent()` process. Here's an example with very basic configuration (the default config we use on our fiddle website) showing the editor content when the button is clicked.
https://fiddle.tiny.cloud/Sdiaab

Drag and drop into the editor wasn't a core feature until v6, so it's a little harder to show in v5, but the behaviour to return base64 images has been around for quite a long time.
