### ISSUE TITLE
'visualaid' toolbar option does not have an icon

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#784]
Description of problem:

Steps to reproduce:
1. add visualaid to a toolbar
2. observe button on the toolbar

Expected result: Button with an icon on it

Actual result: Button without an icon

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6003](http://archive.tinymce.com/develop/bugtracker_view.php?id=6003) posted by [drewmccauley90](http://archive.tinymce.com/profile.php?name=drewmccauley90)_
> 
> _**Tags:** [firefox msie safari chrome opera visualaid toolbar 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Bldaab_

**Comment by cgoess** [comment]
I have the same problem. Is there a solution available to the on/off state issue?

**Comment by HaraldWalker** [comment]
```
.mce-i-visualaid::before {
    content: "\e01b";
    }
```
restores the old behavior of showing the table icon

**Comment by tinydylan** [comment]
I couldn't track down a "visualaid" toolbar button. Perhaps it's an old button name.

I'd suggest the visualchars and visualblocks plugins/buttons. See http://fiddle.tinymce.com/Bldaab/2
