### ISSUE TITLE
Code Plugin - button onclick code not updating content

### ISSUE THREAD

**Issue by Paytah232** [tinymce/tinymce#7844]
I have the tinymce editor working on my site, and except for this bug I've found, it works perfectly. I'm not sure if it's a known issue, but I don't seem to be able to update the source code content of the tinymce dialog. I have the 'code' plugin active and my source code is as below:
`<button class="btn-xs btn-success">Click me to see a GIF of the process</button><img id="integration_gif" class="hideme" style="width: 100%; height: 100%;" src="../uploads/system/images/integration.gif">`

I need to add an onclick functionality here in the button as follows:
`<button class="btn-xs btn-success" onclick="toggle('integration_gif');">Click me to see a GIF of the process</button><img id="integration_gif" class="hideme" style="width: 100%; height: 100%;" src="../uploads/system/images/integration.gif">`

For whatever reason, when I add the onclick event in the button tag (or anywhere else for that matter), it reverts when I click save. However, if I update the information inside the class of the button, that does work.

Any able to shed any light on this problem for me? Thanks!

**Comment by TheSpyder** [comment]
This is a security feature. By default TinyMCE blocks script attributes from being added to content elements.
https://www.tiny.cloud/docs/tinymce/6/security/#scripts-and-xss-vulnerabilities

More information, and details on how to configure specific `onclick` attributes to be allowed, is contained in our `schema` documentation:
https://www.tiny.cloud/docs/tinymce/6/content-filtering/#schema

**Comment by Paytah232** [comment]
@TheSpyder Thanks for the super fast response. I had a feeling this could be why. 

I had a quick look through the documentation, but I'm having trouble understanding how I can allow the onclick type to buttons; could you help?

**Comment by Paytah232** [comment]
I added extended_valid_elements: 'button[onclick]' to my constructor, but now now button does not accept classes etc.

**Comment by TheSpyder** [comment]
You caught me at a good time 🙂 

The extended valid elements configuration replaces an element in the schema entirely. You need to specify _all_ valid attributes you plan to use, not just the new one you want to add.

**Comment by Paytah232** [comment]
Ah perfect! Looks like (assuming the schema allows all button elements), that this will do the trick:
`extended_valid_elements: 'button[*|onclick]'`.

Otherwise, is there another way I can find what the schema defaults are, for example, for the button type?

**Comment by TheSpyder** [comment]
The schema is too big to keep a copy of it in the documentation - you'll have to look at the code:
https://github.com/tinymce/tinymce/blob/731754d6019938fd74d4d8c233423d3fcdb1148c/modules/tinymce/src/core/main/ts/api/html/Schema.ts#L263-L264

I don't think we do any validation on attribute values, only whether attributes are allowed.

**Comment by Paytah232** [comment]
Fantastic. Well this solved my issue. Thanks so much for your help and a great tool!
