### ISSUE TITLE
TinyMCE removing html tags on init

### ISSUE THREAD

**Issue by pomyslografia** [tinymce/tinymce#7846]
Hi, I try to paste html code. I use tinymce code plugin. After save it's ok.
The source code: `<p><code>&lt;html&gt;&lt;body&gt;test&lt;/body&gt;&lt;/html&gt;</code></p>`
Displayed on page: `<html><body>test</body></html>`

When I edit it again, after opening all html code is missing: `<p><code>test</code></p>`

Im using 4.5 version.
Please help.

**Comment by vanillajonathan** [comment]
TinyMCE 4.5 is very old! Please use version 5 or even better version 6.
Check out the [element_format](https://www.tiny.cloud/docs/tinymce/6/content-filtering/#element_format) option.
