### ISSUE TITLE
First set the text size to 8pt, then set it to heading 2, but the text is still displayed as 8px instead of the heading 2 format size

### ISSUE THREAD

**Issue by xingxingnuan** [tinymce/tinymce#7856]
"tinymce": "^6.0.2",

1. set the text size to 8pt
2.  set it to heading 

which is different from the expected structure

**Comment by TheSpyder** [comment]
This is expected, because changing the block tag (from paragraph to heading) does not override inline styles (setting the text size). Outside of the inline style the text size will show as the normal heading value.

**Comment by xingxingnuan** [comment]
However, in this case, it cannot be reset to the font size of the title. The effect is different from that of the normal operation of word documents. Is it necessary to rewrite this logic to achieve this effect
