### ISSUE TITLE
The style of codesample is inconsistent when the editor is in preview and editing status

### ISSUE THREAD

**Issue by xingxingnuan** [tinymce/tinymce#7858]
1. editor 
![image](https://user-images.githubusercontent.com/87689910/170907111-fbf7c875-2299-484a-8854-e9d1682dcd70.png)
2. preview
![image](https://user-images.githubusercontent.com/87689910/170907238-14be8790-c067-44df-89d0-0ab0359fe45a.png)

How to make consistent highlighting styles?

**Comment by czh1998yr** [comment]
I have encountered the same problem as you. Have you found a solution

**Comment by xingxingnuan** [comment]
No solution found
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sun, Aug 7, 2022 05:42 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [tinymce/tinymce] The style of codesample is inconsistent when the editor is in preview and editing status (Issue #7858)

&nbsp;




I have encountered the same problem as you. Have you found a solution
