### ISSUE TITLE
autoresize

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#786]
At the beginning autoresize plugin doesn't work when text is loaded with the control.

Description of problem:

Steps to reproduce:
1. Set multiline text in textarea.
2. Set tinyMce as autoresize.
3. Open it in browser (not FF).

Expected result:
Text field autoresized at the beginning.

Actual result:
Text field collapsed at the beginning. User has to set focus on the textarea and press a key to expand the control.

Tested on IE v7,v8,v9,v10 Chrome v27 and FF v21. (on FF v21 works fine)
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6005](http://archive.tinymce.com/develop/bugtracker_view.php?id=6005) posted by [ivmce](http://archive.tinymce.com/profile.php?name=ivmce)_

> _**Tags:** [msie chrome msie7 msie8 msie9 msie10 autoresize ie 4x chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Nldaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
