### ISSUE TITLE
Ellipsis added at the end of option labels resulting in translations (by tinymce-i18n) not working for them.

### ISSUE THREAD

**Issue by maciejSas** [tinymce/tinymce#7866]
**What is the current behavior? Describe the bug**
![image](https://user-images.githubusercontent.com/78368247/171638902-8479585c-c30f-4faa-9ba9-759016050f9a.png)
![image](https://user-images.githubusercontent.com/78368247/171638996-75a6d422-bc68-4619-8446-0bd73175d655.png)
All options are translated, but dropdown options with ellipsis added to them are not translated. 

Im using this language pack https://cdn.jsdelivr.net/webjars/org.webjars.npm/tinymce-i18n/22.2.11/langs/es.js

Translations for those labels exist in file above.

Using tinymce 5.0.7 as an artifact from org.webjars.bowergithub.tinymce

**Comment by TheSpyder** [comment]
The `tinymce-i18n` project is not run by us. Please direct your question to their issue tracker:
https://github.com/mklkj/tinymce-i18n
