### ISSUE TITLE
Pop-up windows get resize in TinyMCE, after first window is opened and closed

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#787]
Description of problem:

Hello,

I am using TinyMCE 3.4.8 editor for my drupal project. Whenever I am adding image, anchor tag, video from TinyMCE editor, browser is resizing to small size.

Steps to reproduce:
1. Open the editor, click on image/ anchor/ video button. For the first time browser is coming correct only.
2. Close and open it again. Browser got resized.

Expected result:
Browser should not get resize. 
Actual result:
Browser is resizing.

This is happening in chrome browser only. Currently I am using 27.0.1453.110 m.

Can you help me out.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6006](http://archive.tinymce.com/develop/bugtracker_view.php?id=6006) posted by [Rajendar](http://archive.tinymce.com/profile.php?name=Rajendar)_

> _**Tags:** [chrome browser resizing chrome 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
