### ISSUE TITLE
小屏幕上table表格线粗细不一

### ISSUE THREAD

**Issue by liucan25011** [tinymce/tinymce#7871]
在大的屏幕上tr线的粗细正常为1px，在小屏幕上线的粗线会发现变化，会出现有的粗有的细的情况，是什么原因？

**Comment by vanillajonathan** [comment]
Please write in English.

> On a large screen, the thickness of the tr line is normally 1px. On a small screen, the thick line on the line will change, some thick and some thin. What is the reason?

https://translate.google.com/?sl=zh-CN&tl=en&op=translate
