### ISSUE TITLE
Menu's lists not displayed. Bootstrap 5.2 conflict ?

### ISSUE THREAD

**Issue by webmasterCerf** [tinymce/tinymce#7879]
**What is the current behavior? Describe the bug**
Menu's lists are not displayed
![Capture d’écran de 2022-06-08 12-00-56](https://user-images.githubusercontent.com/78088592/172591569-e03d6962-3e39-4f1e-8172-1c87b0d1c87d.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 6 / firefox and chrome / any

**Comment by TheSpyder** [comment]
Is this new in TinyMCE 6? It doesn't happen in version 5?

A replication case on codepen would help a lot.

**Comment by webmasterCerf** [comment]
My bad ! There was a pollution of the root css which mention :  * { overflow-x: hidden } sorry !

**Comment by TheSpyder** [comment]
No problem. Glad it wasn't a bug :)
