### ISSUE TITLE
error while saving, when editor id is numeric

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#789]
tested on 3.5.8

Description of problem:
- content of the editor is not saved, when id only contains of numerics.
- after changing the id to contain a char like "a123" everything works like a charm.

I will try to further reduce the example, if required.

Steps to reproduce:
1. open the linked fiddle
2. enter some text into tinymce
3. click the floppy-symbol to save

Expected result:
content posted and saved

Actual result:
js-error

TypeError: l is undefined

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6008](http://archive.tinymce.com/develop/bugtracker_view.php?id=6008) posted by [kills](http://archive.tinymce.com/profile.php?name=kills)_
> 
> _**Tags:** [firefox]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://jsfiddle.net/mstaab/hV3yp/_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
