### ISSUE TITLE
Undo pasted text not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#791]
Description of problem:
It is not possible to undo pasted text after clearing all undo levels using the UndoManager.clear().

Steps to reproduce:
1. Open fiddle link
2. Press 'Reset History' Button
3. Copy some external text to the clipboard
4. Paste this external text in the TinyMCE editor
5. Try to Undo this pasted text

Expected result:
The undo button is enabled and the pasted text can be undone

Actual result:
The undo button is disabled and it is not possible to undo the pasted text.

Update: This is a bug with the 'paste' plugin. When I remove the plugin from the fiddle example it allows me to paste after clearing the undo history.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6010](http://archive.tinymce.com/develop/bugtracker_view.php?id=6010) posted by [TAS](http://archive.tinymce.com/profile.php?name=TAS)_
> 
> _**Tags:** [chrome 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Xldaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by igumcheg** [comment]
The message above is incorrect, this bug still persists and reproducible in 4.4.0 and 4.4.3

**Comment by blackcathikari** [comment]
Apologies, @igumcheg, you're right. I'll re-open this.
Note for our reference: I reproduced on v.edge using http://fiddle.tinymce.com/zAfaab

**Comment by tom-haines** [comment]
+1 - any update on this?

**Comment by spocke** [comment]
There is a new undoManager.reset() that adds the current state as the initial undo level. This could have been worked around in the past as well with a undoManager.add() after the clear. Closing this since I can no longer reproduce it if I change the code to reset.

**Comment by akshymalvia** [comment]
I'm having the same issue, after pasting text into the editor, undo was not working, but after preventing default behaviour of browser native paste event on the editor instance, it started to work properly.

```
tinymce.on('paste', (e) => {
  e.preventDefault()
})
```

**Comment by metricjs** [comment]
@akshymalvia Interesting. What version of TinyMCE are you using?

**Comment by akshymalvia** [comment]
@metricjs I'm using 5.7.0
