### ISSUE TITLE
Editor is not display if embedded in JSP page

### ISSUE THREAD

**Issue by truezjz** [tinymce/tinymce#7915]
Editor is not display if embedded in JSP page;
try Ver 6.0 , ver 5.10

tried Ver4.9, it works as expected, using the same code.

**Comment by lnewson** [comment]
Hi,

Can you please provide more information? Is there any console errors and if not can you provide a reproduction case or similar?

At a guess, you're probably using quirks mode and that's normally caused by the missing `<!DOCTYPE html>` declaration at the top of the HTML page.

**Comment by truezjz** [comment]
Thanks for your response, yes, you are right, I was still using <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> in the header

After change it to <!DOCTYPE html>  ver 5 works.
