### ISSUE TITLE
image_upload_handler should take 4 arguments, but only 2 defined by UploadHanlder

### ISSUE THREAD

**Issue by stomvi** [tinymce/tinymce#7916]
**What is the current behavior? Describe the bug**
When using with typescript, `image_upload_handler` should take 4 arguments, but only 2 are defined in `UploadHandler` in `tinymce.d.ts`.

```ts
declare type UploadHandler = (blobInfo: BlobInfo, progress: ProgressFn) => Promise<string>;
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
none

**What is the expected behavior?**
`UploadHandler` should accept 4 arguments as described here: [https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler](https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
`tinymce v6.0.3`

**Comment by lnewson** [comment]
Hi,

As per the sidebar in the top left, the https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler documentation is for TinyMCE 5. The documentation for TinyMCE 6 is here: https://www.tiny.cloud/docs/tinymce/6/upload-images/#images_upload_handler. Additionally, as noted in the [migration guide](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#images_upload_handler) the `success` and `failure` callback parameters have been removed and the function now needs to return a Promise, so this is correct.
