### ISSUE TITLE
Template plugin replace content

### ISSUE THREAD

**Issue by tom-villanueva** [tinymce/tinymce#7920]
**Is your feature request related to a problem? Please describe.**
The current behaviour when you place a template is that it's pasted above the content, and does not replace the current content in the editor.

**Describe the solution you'd like**
I'd like to add the possibility to change that behaviour through an option in the init method. 
Something like: 
`template_replace_content: true`

**Describe alternatives you've considered**
Replace content being the default behaviour.

**Comment by zhaokaide** [comment]
I hope to prefabricate some templates. When I select text, click Template Plug in to format text according to my prefabricated template
