### ISSUE TITLE
RTL and LTR buttons and command not working

### ISSUE THREAD

**Issue by TomLorenzi** [tinymce/tinymce#7921]
**What is the current behavior? Describe the bug**
After adding directionnality plugins and `ltr rtl` in my toolbar i can click on that buttons and nothing would change.  
That would be the same for executing `myEditor.execCommand('mceDirectionRTL')`, it won't do anything

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
I can reproduce this everytime and that's litrally the only code i added.
It worked one time using commands randomly but never worked anymore...

It seems to work when I init my tinyMce as 'RTL' but not 'LTR' in some cases

**What is the expected behavior?**
Change text direction

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
v5, not workig with lastest v5 version as same as `5.8.2`

**Comment by TomLorenzi** [comment]
Actually found a workaround doing `myEditor.getBody().dir = 'rtl'`

**Comment by TomLorenzi** [comment]
Still want to keep this issue, using strange workaround is not ideal

**Comment by lostkeys** [comment]
Hi @TomLorenzi. Sorry, I cannot replicate your issue. [It works fine when I test it](https://fiddle.tiny.cloud/2xEEGUWrmf/1). If you are having issues, please investigate and provide a replication demo. Thanks.

— Fredrik, Product Manager
