### ISSUE TITLE
Bootstrap Modal with Scrollbars - TinyMCE Menu and Toolbar Get Detached when scrolling

### ISSUE THREAD

**Issue by mhast** [tinymce/tinymce#7922]
I have a tinymce editor inside of a Bootstrap Modal. Either the modal has a scrollbar or the page has a scrollbar, so that the modal moves when the scrollbar is used. In both of those cases, I select a menu item e.g. Format, then move the mouse outside of the Format menu and start scrolling, the contents of the menu item stays fixed inside of the modal (see picture). The same is true for the toolbar. When I press the ellipsis on the toolbar and then scroll, the toolbar is fixed.

This fiddle example is taken from the Boostrap integration page.
https://www.tiny.cloud/docs/integrations/bootstrap/
http://fiddle.tiny.cloud/TPhaab?_ga=2.141185906.1395781475.1655844545-2042033185.1654898730

The expected behavior is that the content of the menu and toolbar moves up or down with the scroll direction.

Fiddle uses TinyMCE 5, but version 6 has the same behavior.

<img width="556" alt="Screen Shot 2022-06-21 at 3 07 40 PM" src="https://user-images.githubusercontent.com/862037/174906255-feee5c39-d7a0-4f85-b33b-35206968dc37.png">
*

**Comment by TheSpyder** [comment]
This is a known issue that we're tracking in #5097. I'll post a status update there, because we're about to start looking at it.
