### ISSUE TITLE
Backspace is not working when inline editor is in an iframe

### ISSUE THREAD

**Issue by Sylphide** [tinymce/tinymce#7924]
Hello,

**What is the current behavior?**
Backspace key does not erase content when inline editor is set in an iframe

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

I set up the inline editor inside an iframe (using react-frame-component) and when clicking inside the editor, the backspace key does not work. I can't erase content. Otherwise the editor seems to work fine. I tried understanding what is happening directly inside tinymce code and it seems like the caret is not correctly positionned. 

https://github.com/tinymce/tinymce/blob/e242dd9b55201c9084d2c7c9c7b03489bcf308ec/modules/tinymce/src/core/main/ts/delete/Outdent.ts#L15

`BlockBoundary.isAtStartOfBlock(SugarElement.fromDom(block), pos)` is always true even after typing some characters

Not sure if I should have posted this issue in tinymce repo or here since I used the react integration. Let me know if I should copy this in tinymce repository instead.

Here is my editor component
```
<Editor
        init={{
          menubar: false,
          statusbar: false,
          plugins: ['autolink', 'lists', 'link'],
          toolbar: 'bold italic bullist link',
        }}
        initialValue="<p>Hello world!</p>"
        inline
      />
```

The iframe is just as simple as
````
import Frame from 'react-frame-component';

....

return (
<Frame>
      {children}
</Frame>
);
````

**What is the expected behavior?**

Backspace key should erase content in editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

Tested on "@tinymce/tinymce-react": "^3.13.1" in chrome 98.0.4758.82

Thanks

Edit:

If Editor uses IFrame window instead of global window it works fine

**Comment by JohannesKonczak** [comment]
I'm having the same problem and sadly there is no workaround for me.

What is the status on this issue?
