### ISSUE TITLE
[4.0] Remove last table sets content to null

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#793]
Description of problem: Removing tailing table will set the editor content to "" (empty)

Steps to reproduce:
1. Go to Fiddle / Tinymce.com (try it)
2. Add some content
3. Add tailing table
4. Place cursor after the table
5. Hit backspace

Expected result: Table removed

Actual result: Everything is gone
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6012](http://archive.tinymce.com/develop/bugtracker_view.php?id=6012) posted by [michaelkiwi](http://archive.tinymce.com/profile.php?name=michaelkiwi)_

> _**Tags:** [chrome chrome10 chrome11 chrome12 chrome13 4x]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://fiddle.tinymce.com/Zldaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
