### ISSUE TITLE
images_upload_handler 自定义上传图片失败

### ISSUE THREAD

**Issue by wwq146213** [tinymce/tinymce#7935]
![image](https://user-images.githubusercontent.com/93062479/176123828-15a7151d-84ca-48e9-aa26-add7e86b9b89.png)
上传之后获取不到图片信息

**Comment by wwq146213** [comment]
z有人吗

**Comment by dengshicheng1996** [comment]
> ![image](https://user-images.githubusercontent.com/93062479/176123828-15a7151d-84ca-48e9-aa26-add7e86b9b89.png) 上传之后获取不到图片信息

用images_upload_handler函数

**Comment by icetee** [comment]
I have the same issue. I see the demo code [here](https://github.com/tinymce/tinymce/blob/124bb72f8d5ac9daa21a5b2bb9e866a47c06e6b9/modules/tinymce/src/plugins/image/demo/ts/demo/Demo.ts), and not work.

If I no call `_progress` function, not happened.

If I call `_progress(100);` I get error message
```js
images_upload_handler: (blobInfo, _progress) => new Promise(success => {
    setTimeout(() => {
      success('https://www.google.com/logos/google.jpg');
      _progress(100);
    }, 1000);
}),
```

```
Error: Errors: 
Failed path: (data > src > value)
Expected type: string but got: number

Input object: {
  "src": {
    "value": 100,
    "meta": {}
  },
  "alt": "",
  "dimensions": {
    "width": "",
    "height": ""
  },
  "fileinput": [
    {}
  ]
}
```

But. If add `_progress` function the link, resolve this issue.

```js
images_upload_handler: (blobInfo, _progress) => new Promise(success => {
  setTimeout(() => {
    _progress('https://www.google.com/logos/google.jpg')
    success()
  }, 1000);
}),
```
![image](https://user-images.githubusercontent.com/1855340/198735372-bbf85256-628f-4fc2-9298-48293f9a82b1.png)

My solution is that I upgraded to v6. Unfortunately I was v5.

**Comment by nnmax** [comment]
I have a same issue.

**Comment by toyRan** [comment]
This code can work normally.
 images_upload_handler: function(blobInfo) {
          const formData = new FormData()
          formData.append('image', blobInfo.blob(), blobInfo.filename())

          return fetch('http://mysite.com/api/upload', {
            method: 'POST',
            body: formData,
            headers: { Authorization: 'Bearer ' + window.sessionStorage.getItem('token') }
          })
            .then(response => {
              if (!response.ok) {
                throw new Error('Network response was not ok')
              }
              return response.json()
            })
            .then(data => {
              if (data && data.data && data.data.location) {
                return data.data.location
              } else {
                throw new Error('Unable to upload image')
              }
            })
            .catch(error => {
              console.error(error)
              throw new Error('Image upload failed: ' + error.message)
            })
        }

**Comment by mariojgt** [comment]
Yes this code 

> This code can work normally.
> 
> ```
>  images_upload_handler: function(blobInfo) {
>           const formData = new FormData()
>           formData.append('image', blobInfo.blob(), blobInfo.filename())
> 
>           return fetch('http://mysite.com/api/upload', {
>             method: 'POST',
>             body: formData,
>             headers: { Authorization: 'Bearer ' + window.sessionStorage.getItem('token') }
>           })
>             .then(response => {
>               if (!response.ok) {
>                 throw new Error('Network response was not ok')
>               }
>               return response.json()
>             })
>             .then(data => {
>               if (data && data.data && data.data.location) {
>                 return data.data.location
>               } else {
>                 throw new Error('Unable to upload image')
>               }
>             })
>             .catch(error => {
>               console.error(error)
>               throw new Error('Image upload failed: ' + error.message)
>             })
>         }
> ```

thank you is working.

**Comment by TheSpyder** [comment]
Correct, TinyMCE 6 changed the `images_upload_handler` config to use promises, rather than `success` and `failure` callbacks.

https://www.tiny.cloud/docs/tinymce/6/upload-images/#images_upload_handler

**Comment by pjuhen** [comment]
Hi, 

I have the same issue with TinyMCE v7 :

Here is my code, that is very close to the example :

_const image_upload_handler = (blobInfo, progress) => new Promise((resolve, reject) => {
  function getCookie(cname) {
        let name = cname + "=";
        let decodedCookie = decodeURIComponent(document.cookie);
        let ca = decodedCookie.split(';');
        for(let i = 0; i <ca.length; i++) {
            let c = ca[i];
            while (c.charAt(0) == ' ') {
            c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
            }
        }
        return "";
    }

  const xhr = new XMLHttpRequest();
  xhr.withCredentials = true;
  xhr.open('POST', '/upload');
  xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));


  xhr.upload.onprogress = (e) => {
    progress(e.loaded / e.total * 100);
  };


  xhr.onload = () => {
    if (xhr.status === 403) {
      reject({ message: 'HTTP Error: ' + xhr.status, remove: true });
      return;
    }

    if (xhr.status < 200 || xhr.status >= 300) {
      reject('HTTP Error: ' + xhr.status);
      return;
    }

    const json = JSON.parse(xhr.responseText);
    console.log(json);

    if (!json || typeof json.location != 'string') {
      reject('Invalid JSON: ' + xhr.responseText);
      return;
    }

    progress(100);
    resolve(json.location);
  };

  xhr.onerror = () => {
    reject('Image upload failed due to a XHR Transport error. Code: ' + xhr.status);
  };

  const formData = new FormData();
  formData.append('file_field', blobInfo.blob(), blobInfo.filename());

  xhr.send(formData);
});_

I have no error in executing this code, image is uploaded, location is right (console.log()).

The error seems to happen after  the execution of the code.

The value 100 ( instead of file location) seems to be linked to the progress event.

What am I doing wrong ?

Regards,
