### ISSUE TITLE
[Tiny 6.1.0] "only in private projects"

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#7941]
Security warning while building:  **"warning Workspaces can only be enabled in private projects"**

It is the first time I am seeing this warning while building tinymce.

Tiny Master => ~6.1.0
Windows Yarn 1.22.19

The package.json file of Tiny begins with:
```
{
  "name": "root",
  "private": true,
  "workspaces": [
    "modules/*"
  ],
...
```

So what?
The required declaration of private: true is done. 
What is the reason for this security warning?

**Comment by TheSpyder** [comment]
Huh. It doesn't block the build, and we have had so many warnings about out of date packages over time, that I don't think any of us had noticed. I'll look into it, thanks for logging this!

**Comment by TheSpyder** [comment]
It's a yarn bug:
https://github.com/yarnpkg/yarn/issues/8580

I used `grep` to search the codebase and the problem is we upgraded `webdriverio` in this release, which depends on a version of `keyv` that published a `package.json` including workspaces.

They have fixed it (jaredwray/keyv#347) so we'll see whether an upgrade of wdio is available or if we need to add a resolution override.

**Comment by TheSpyder** [comment]
A simple upgrade of _our_ transitive dependencies upgraded `keyv` and fixed the problem!

**Comment by TheSpyder** [comment]
Merged

**Comment by Georg-Git** [comment]
Yes - workspace warning is gone.

By the way: 
I've been noticing for a while 3 remarkable warnings.
And the first one makes me nervous:

```
warning Pattern ["grunt-cli@^1.4.3"] is trying to unpack in the same destination 
..Local\\Yarn\\Cache\\v6\\npm-grunt-cli-1.4.3-22c9f1a3d2780bf9b0d206e832e40f8f499175ff-integrity\\node_modules\\grunt-cli
as pattern ["grunt-cli@~1.4.3"]. 
This could result in non-deterministic behavior, skipping.
```


```
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4"
has unmet peer dependency "@octokit/core@>=3"
```

```
warning " > stylelint-order@5.0.0" 
has incorrect peer dependency "stylelint@^14.0.0"
```

**Comment by TheSpyder** [comment]
yes, we need to figure out what to do with the out of date lerna and stylelint. Neither are causing us issues, as far as we can tell, it's just a matter of checking for breaking changes in the new major version.

**Comment by Georg-Git** [comment]
Ok - and I solved the grunt-cli warning.

In my build script I had added:
`yarn add grunt-cli`

But there was no need for this line anymore.
=> Everthing fine
