### ISSUE TITLE
mentions plugin: It shows only 10 users at a time. It should have a way to config number of users.

### ISSUE THREAD

**Issue by Ruchitakheni** [tinymce/tinymce#7944]
Currently, after @ type it shows list of users in which only 10 users are being shown.

**Repro**
- Enable mentions plugin and provide required config
- In editor, type @a which will open users list menu
- Observe in menu only 10 users are being shown

**expected behavior**
 It should show all the matching users or should provide a way to config number of users

**Comment by TheSpyder** [comment]
Mentions is a premium plugin so I'm afraid we can't assist via GitHub. If you have a support subscription, please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
