### ISSUE TITLE
paste from word doesn't retain text background color

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#795]
Description of problem: Bakground color of text copied from Word is not pasted with the text in the final document.

Steps to reproduce:
1. Create text in Word, set background color to yellow ("Text highlight color")
2. Copy text from Word.
3. Click "Paste from Word" command in TinyMCE
4. Paste text (ctrl-v). Note that the highlighting (background) color appears (see attached screenshot).
5. Click Insert button. Note that the highlighting (background) color DOES NOT APPEAR

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6014](http://archive.tinymce.com/develop/bugtracker_view.php?id=6014) posted by [fuhrmanator](http://archive.tinymce.com/profile.php?name=fuhrmanator)_

> _**Tags:** [msie chrome msie10 chrome13]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
