### ISSUE TITLE
A white screen appears when the editor loads slowly, hoping to display the loading effect

### ISSUE THREAD

**Issue by xingxingnuan** [tinymce/tinymce#7962]
When traversing and initializing 10 tinymces in react, the loading display screen will be blank. Can you increase the effect in loading
<img width="817" alt="企业微信截图_16571972835349" src="https://user-images.githubusercontent.com/87689910/177804935-40e186cb-dccc-42e6-92d0-64ded3a872ce.png">
It took a while to show
<img width="826" alt="企业微信截图_16571973256220" src="https://user-images.githubusercontent.com/87689910/177805076-b25b2b8e-55a9-4f1d-9d3e-c9847cf5409b.png">

**Comment by smalos** [comment]
Why would you want to load 100 tinymce instances?
Reconsider your design.
