### ISSUE TITLE
Copying and pasting from bulleted list increase the indent

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#797]
Description of problem:Pasting from Bullet list increase the indent and change the bullet style

Steps to reproduce:
1.Click the bullet list and type 'Test'
2.Copy the 'Test' and paste without clicking out
3.You can see that rather than pasting below, it paste as increased indent which change the bullet style

Expected result: It should paste below bullet list rather than increasing indent 

Actual result: 

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6016](http://archive.tinymce.com/develop/bugtracker_view.php?id=6016) posted by [Srikanta.Sahoo](http://archive.tinymce.com/profile.php?name=Srikanta.Sahoo)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/pmdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
