### ISSUE TITLE
Selecting checkboxes in the menu, will also select list

### ISSUE THREAD

**Issue by michgerts** [tinymce/tinymce#7978]
**What is the current behavior? Describe the bug**
Selecting checkboxes in the menu, will also select list

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Click checkbox in the menu
![image](https://user-images.githubusercontent.com/10831534/178948731-f297866f-5be1-4478-a1de-840a051b8a20.png)

**What is the expected behavior?**
The docs of tiny say the list and checklist plugins need to be enabled together, so I suspect it's some internal tiny plumbing.  

It would be more clever to have checks as a sub-option of list in that case.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Chrome, tinymce-angular 6.0.3-5

**Comment by TheSpyder** [comment]
Checklist is a premium plugin so I'm afraid we can't assist via GitHub. If you have a support subscription, please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
