### ISSUE TITLE
editor.queryCommandValue doesn't return expected result after calling execCommand

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#799]
Description of problem: After applying a style, calling queryCommandValue for the changed style doesn't always update as expected

Reproduced on 4.x demo

Steps to reproduce:
1. Enter some text, I'll use the sentence "Hello there TinyMCE"
2. Select "there"
3. From the console, type tinymce.activeEditor.execCommand('fontsize', false, '18pt')
4. From the console, type tinymce.activeEditor.queryCommandValue('fontsize')

Expected result: Returned value would be '18pt'

Actual result: Returned value is 0, or the default font size.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6017](http://archive.tinymce.com/develop/bugtracker_view.php?id=6017) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
