### ISSUE TITLE
Nested editor in modal window - most of buttons don't work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#801]
I know that creating a new instance of the editor inside a mce modal window (from a previous editor) might seem curious. I just want to report this here, if there's no fix, never mind.

So the bug is simple. Everything is working, except most of the buttons actions. The indent/oudent will work but the most basic one (bold/italic/underline, etc.) will not. For example, after having selected some text inside the editor, a click on the bold button, will try to modify the range but nothing will change. But the shortcuts are working (ctrl+b).

If the textarea is appended to the page body (so outside from the modal window), then the editor is loaded, everything will work.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6018](http://archive.tinymce.com/develop/bugtracker_view.php?id=6018) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_

> _**Tags:** [mce4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
