### ISSUE TITLE
Customization of ContextMenu by using React - Override

### ISSUE THREAD

**Issue by ZeroWhisper** [tinymce/tinymce#8016]
# Related issue

We are using TinyMCE 6.0.3 and trying to create a very own Context Menu

We didn't find examples of how to do this or documentation about it. 
We found how add 'plugins' and set already existent fields to create a new option within ContextMenu

# The solution we would like
The best solution should be using React Components and add it as a Option 
- OR -  
Create a React Component and override Entire Context Menu 

# Other alternatives
* Pure HTML and JS. 
* CSS Override
* More and more option to CSS Override, Icon (svg) preffix or suffix Options

**Comment by jacksonpradolima** [comment]
Any input here?
