### ISSUE TITLE
When caret is on the left of a non editable container, image are inserted with data-mce-bogus="all".

### ISSUE THREAD

**Issue by icaparros-at-wiris** [tinymce/tinymce#8032]
**What is the current behavior? Describe the bug**

1. I create any container element with the attribute `contenteditable="false"`.
2. With the caret on the left of the container element I insert an image.
3. TinyMCE set the image inside an element `<p>` with the attribute `data-mce-bogus="all"`.

The Image is not correctly displayed until I reclick the editor.
All elements with the attribute `data-mce-bogus="all"` are ignored on the function `getContent()`.

**What is the expected behavior?**

The `<p>` element doesn't have the `data-mce-bogus="all"` attribute. The image HTML is part of the `getContent()` output.

**Comment by moneydance** [comment]
Also able to recreate this

**Comment by jeremysykesQ4** [comment]
Experiencing a similar issue where I have a span that has `contenteditable="false"` set.
If I place the cursor right of the element and key left once, a `data-mce-bogus="all"` renders on the screen.
If I key left once more it disappears, it appears to render when I have the `contenteditable="false"` selected.
