### ISSUE TITLE
Content filtering not removing data attributes from pasted content

### ISSUE THREAD

**Issue by christian-fries** [tinymce/tinymce#8046]
**What is the current behavior? Describe the bug**
Currently, the content filtering mechanism does not remove data attributes from pasted content, even though they're not part of the `valid_elements` configuration.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
See this code pen: https://codepen.io/christianfries/pen/jOzpPGd

**What is the expected behavior?**
The data attributes should be removed from the content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
* TinyMCE 5.10.5
* Firefox 103.0.1 on Windows 10
* Firefox 103.0.1 on macOS 12.5
* Chrome 104.0.5112.79 on macOS 12.5 (Copy the text in Firefox and paste it in Chrome. When the text is copied in Chrome, a different output is generated)

**Comment by jordanade** [comment]
Bizarre that this is not supported
