### ISSUE TITLE
Make windows responsive

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#805]
Make the windows responsive, the windows now seems to be opened with a strikt width.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6024](http://archive.tinymce.com/develop/bugtracker_view.php?id=6024) posted by [otter71](http://archive.tinymce.com/profile.php?name=otter71)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
