### ISSUE TITLE
Pressing escape in a Modal dialogue when an input element is selected causes focus loss

### ISSUE THREAD

**Issue by andrewnicols** [tinymce/tinymce#8051]
**What is the current behavior? Describe the bug**
When a modal is open and focus is on an input element (for example the Link modal is open and the "URL" field is selected, pressing the Escape key causes a focus change to the document body with no easy way to get back to the modal.
Using the tab key then allows the user to tab through all elements on the document, which 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://fiddle.tiny.cloud/Ajiaab
* Open the Link editor
* Press Escape
* Press Shift+Tab (willjump 

**What is the expected behavior?**
When pressing escape the Modal should close.
It should also not be possible to escape the focus from the modal

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest 6.1

**Comment by TheSpyder** [comment]
It's quite normal for users to tab between elements in the document, we only override that when the cursor is in a list or a table.

In our testing escape does close the modal and return focus to the document, and focus cannot escape from the modal (at least not by using tab and shift+tab). Can you please provide more details?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
