### ISSUE TITLE
TinyMCE 6 doesn't support to set style of tab title in tabpanel dialog 

### ISSUE THREAD

**Issue by lacinello** [tinymce/tinymce#8054]
**What is the current behavior? Describe the bug**
Style of tab title in tabpanel dialog doesn't work in TinyMCE 6. It works in TinyMCE 5. 
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/Ljiaab/1
Switch between tinymce6-stable and tinymce5-stable to see differences.
**What is the expected behavior?**
Style of tab title should be customizable to distinguish between tabs in structure based on topic.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 6 cloud stable
Google Chrome Version 104.0.5112.81

**Comment by TheSpyder** [comment]
I'm sorry, this was never an intended capability of dialog fields defined as text properties. We couldn't correct it until TinyMCE 6 as it was a breaking change. From the 6.0 release notes:
https://www.tiny.cloud/docs/tinymce/6/changelog/#fixed-7

> Dialog labels and other text-based UI properties did not escape HTML markup.
