### ISSUE TITLE
Specify initial color for backcolor button

### ISSUE THREAD

**Issue by thommelutten** [tinymce/tinymce#8055]
With TinyMce version 6.0 it is not possible to specify initial default value for backcolor button. It is set to black, and I would like to be able to specify it to another color on initialization. I've scoured the 6.0 documentation and can't find any information regarding how to specify initial value.

Specifying a color first in the color_map on tinymce.init does not work either, despite that it looks like the first color is picked.

Setting execCommand("hilitecolor"..) is not an option either, as I want the backcolor button to contain the default color to use when I click on it, and not have it enabled at per default.

**Comment by smalos** [comment]
Was it possible in previous versions and how?

**Comment by thommelutten** [comment]
I don't know. I have just recently picked it up, so I am unaware of whether it was present in prior versions. Hence why I labeled it as a feature request.

However I haven't been able to find it in documentation regarding version 5.0 or 4.0. I'm just using 6.0 so wanted to specify that version to help a bit.
