### ISSUE TITLE
Medium vulnerability  - jquery.tinymce-5.9.0.min.js

### ISSUE THREAD

**Issue by KhushbooNigam** [tinymce/tinymce#8056]
A cross-site scripting (XSS) vulnerability was discovered in the URL processing logic of the image and link plugins. The vulnerability allowed arbitrary JavaScript execution when updating an image or link using a specially crafted URL. This issue only impacted users while editing and the dangerous URLs were stripped in any content extracted from the editor. This impacts all users who are using TinyMCE 5.9.2 or lower.

Here the TinyMCE version used is 5.10 and it still shows the above descripted error  in pipeline with Medium vulnerability in White source Bolt Build report highlighting **jquery.tinymce-5.9.0.min.js** in 5.10 RTE SDK version.

We also tried to disable links and images in plugins by keeping allow_script_urls: false but no luck. 

Any help is much appreciated.
Thank you in advance for support.

**Comment by TheSpyder** [comment]
Are you referring to this report?
https://github.com/tinymce/tinymce/security/advisories/GHSA-r8hm-w5f7-wj39

Are you sure it's the 5.10 zip that includes the jQuery 5.9 file? Where are you downloading that build of 5.10 from?

**Comment by KhushbooNigam** [comment]
Hi Team,

I would like to confirm we have managed to produce no vulnerability on TinyMCE version 5.10. Under the guidance of  TinyMCE team we performed this activity and it results to be a false positive scan from Mend which is already reported from us.

We can now close this issue.

Thank you all for quick support and guidance.

Best regards,
