### ISSUE TITLE
Change ok und cancel buttons

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#806]
add a configuration where the position of ok and cancel can be changed.
I need first cancel and the ok

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6025](http://archive.tinymce.com/develop/bugtracker_view.php?id=6025) posted by [otter71](http://archive.tinymce.com/profile.php?name=otter71)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
