### ISSUE TITLE
Failed to construct HTMLElement

### ISSUE THREAD

**Issue by parthfaladuks** [tinymce/tinymce#8065]
I have created custom plugin for conditional block set in tinymce in that i am extending `HTMLElement` as follows in es6

`class ConditionalBlock extends win.HTMLElement`

but getting error as follows

Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

so can you please help me how to extend HTMLElement with es6

tinymce version is 5.0.16

**Comment by hueter** [comment]
This is an old issue but, I also had this issue from copying the [Conditional Blocks](https://tinymce.github.io/tinymce-demos/cool-demos/conditional-blocks.html) example from the [Cool TinyMCE Demos](https://github.com/tinymce/tinymce-demos/blob/master/cool-demos/conditional-blocks.html) repo.

I realized that my bundler (Webpack + SWC) was transpiling to ES5, but [web components only work in ES6+](https://stackoverflow.com/questions/39037489/extending-htmlelement-constructor-fails-when-webpack-was-used)

I updated my compilation target to ES6+ and the errors went away.
