### ISSUE TITLE
Constrain proportions is not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#807]
Description of problem: "Constrain proportions" is not working

Steps to reproduce:
1. Load image in image dialog
2. Write image with and height
3.
4.
5.

Expected result: Expected the height to be calculated automaticly when writing the with...

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6026](http://archive.tinymce.com/develop/bugtracker_view.php?id=6026) posted by [thorskaar](http://archive.tinymce.com/profile.php?name=thorskaar)_

> _**Tags:** [firefox msie safari chrome opera 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
