### ISSUE TITLE
编辑器打开的页面支持复制

### ISSUE THREAD

**Issue by xiaomonvguoguo** [tinymce/tinymce#8077]
现在生成的页面在浏览器和app里面用户复制不了

**Comment by zhaokaide** [comment]
从其他页面复制到编辑器吗？可以尝试开启paste插件

**Comment by yacodes** [comment]
Hi @xiaomonvguoguo and @zhaokaide. Sorry, we can only accept issues in English. Please reopen or open a new issue if you can translate your issue/question into English.
