### ISSUE TITLE
Column width properties

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#808]
It would be nice if we could set the column width, like the row height.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6027](http://archive.tinymce.com/develop/bugtracker_view.php?id=6027) posted by [kooistrag](http://archive.tinymce.com/profile.php?name=kooistrag)_
> 
> _**Tags:** [column width edit properties]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
