### ISSUE TITLE
Emoji in URL breaks Enhanced Media Embed support

### ISSUE THREAD

**Issue by iluis-ud** [tinymce/tinymce#8091]
**What is the current behavior? Describe the bug**

When pasting a link to a video-sharing site with an emoji in the URL, the Enhanced Media Embed plugin cuts off at the emoji, resulting in a broken embed.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Paste https://odysee.com/@skyrift:2/minecraft-timelapse-volcano:2 into the HTML editor.
2. It should turn into a working embed, because there is no emoji in the video's link. (Note that for this particular video, the resulting embed would be in portrait, with an initial image in letterboxed widescreen.)
3. Paste https://odysee.com/@skyrift:2/minecraft-timelapse-%F0%9F%8F%B0-medieval-castle:1 into the HTML editor.
4. The entire URL disappears, yet the plug-in only shows generic embed text from the Odysee website.

**What is the expected behavior?**

4- It should result in a working embed you can tap to watch the vid, with the aspect ratio being a box (as the video is) and the thumbnail being letterboxed widescreen.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested in [TinyMCE v4 demo](https://www.tiny.cloud/docs-4x/demo/full-featured/) and [TinyMCE v6 fully-featured demo](https://www.tiny.cloud/docs/tinymce/6/full-featured-premium-demo/).

**Comment by lnewson** [comment]
Hi, thanks for the report. Enhanced Media Embed is a premium product, so I'm afraid we can't assist via GitHub. If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new

As a side note, it's also worth mentioning that TinyMCE 4 is no longer a supported version of TinyMCE.
