### ISSUE TITLE
Enable editor on edit eara focus

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#811]
There have been several bugs/problems/questions reported and a few features requested regarding fixes to enable activation of the editor most solutions for which involve hacks to the editor code instance.

Enable a default capability switch that can be turned on via config setting which allows activation of editor in one editable area on change in focus into and out of that area. This should be done by design rather than via enabling hacks within various area of editor code.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6030](http://archive.tinymce.com/develop/bugtracker_view.php?id=6030) posted by [RLM](http://archive.tinymce.com/profile.php?name=RLM)_
> 
> _**Tags:** [editor focus blur]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
