### ISSUE TITLE
[6.2.0] Building:  113 warnings  "Direct access to options is forbidden"

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#8112]
**Building reported: 113 problems (0 errors, 113 warnings)**
"warning  Direct access to options is forbidden"

Fresh Building with Tiny Master Code [6.2.0].

One example of the warnings:

`\tinymce\modules\tinymce\src\core\main\ts\api\Options.ts`
`warning  Direct access to options is forbidden outside api/Options.ts  @tinymce/no-direct-editor-options
`

**Comment by spocke** [comment]
Was unable to not reproduce this. You could try to do a `git clean -dfx && git pull origin master && yarn && yarn build` so make sure that you have the latest version of everything and that no build artifacts is interfering with the normal build operation.

**Comment by spocke** [comment]
Just tested the build on windows and it produces the linting warning that you describe.

**Comment by spocke** [comment]
It's because we have not bumped our internal eslint plugin to the latest 2.2.2 version for the tinymce repo that resolves this.
https://github.com/tinymce/eslint-plugin/blob/main/CHANGELOG.md#221---2022-08-30

**Comment by Georg-Git** [comment]
In former times I was used to recompile my project with a new version of tinymce once per month - and now such a long dry spell 🤣

[6.3.0] No warnings while building.
