### ISSUE TITLE
inlinepopups plugin - missing translation

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#812]
Description of problem:
Missing translation in the plugin.
For example in line 187 in plugins/inlinepopups/editor_plugin_src.js
there should be:

DOM.add(id + '_wrapper', 'a', {'class' : 'mceButton mceCancel', href : 'javascript:;', onmousedown : 'return false;'}, ed.getLang('cancel'));

instead of:
DOM.add(id + '_wrapper', 'a', {'class' : 'mceButton mceCancel', href : 'javascript:;', onmousedown : 'return false;'}, 'Cancel');

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6031](http://archive.tinymce.com/develop/bugtracker_view.php?id=6031) posted by [valor](http://archive.tinymce.com/profile.php?name=valor)_

> _**Tags:** [firefox msie safari chrome opera inlinepopups 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
