### ISSUE TITLE
Cannot auto hide "more" drop down menu

### ISSUE THREAD

**Issue by byuilazenbyt** [tinymce/tinymce#8123]
**What is the current behavior? Describe the bug**
When the screen or container for the Editor is too small, the more button appears, and you can click on it and the hidden items show up. However, on "blur" this menu remains open instead of closing.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
See above

**What is the expected behavior?**
on blur behavior the "more" drop down menu should be hidden.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TInyMCE 6

**Comment by lostkeys** [comment]
Hi @byuilazenbyt. Have a look if you can achieve this using our APIs. There are a command to toggle the moredrawer called [ToggleToolbarDrawer](https://www.tiny.cloud/docs/tinymce/6/editor-command-identifiers/) which you perhaps can use with the [blur event](https://www.tiny.cloud/docs/tinymce/6/events/). 

If not, then I recommend you to go to our [roadmap website and submit a feature idea](https://www.tiny.cloud/roadmap/). If you decide to do that, please make sure to tell us why you need this feature, what you are trying to solve and the impact of having and not having it. A well formulated problem helps us prioritize among features and improvements. Thanks!

**Comment by ericbf** [comment]
This isn’t really a feature request, imo, definitely a bug.

![menu-does-not-close](https://github.com/tinymce/tinymce/assets/2483476/cb7ddc6b-985d-4233-a0d0-0dd1431684ea)
