### ISSUE TITLE
Scroll position jumping on context menu shortcut key press if scroll bar is visible

### ISSUE THREAD

**Issue by a-legotin** [tinymce/tinymce#8124]
When editing content and scroll bar is visible scroll position jumping when pressing context menu shortcut ![](https://iili.io/PvGqg9.png) using keyboard.

Reproducible with [sample from docs](https://www.tiny.cloud/docs/ui-components/contextmenu/#interactiveexample). I also create demo [fiddle](https://fiddle.tiny.cloud/Nmiaab).

**Repro steps**
1. Make sure editor have some content and vertical scrollbar is visible.
2. Scroll to top in the editor and put cursor in the first line of the content.
3. Press context menu key on the keyboard.
4. Content now scrolls a bit and no context menu is shown

![](https://iili.io/PvMKhv.gif)

**Expected behavior**
No scroll jumping and context menu visible when pressing context menu key.

**Environment**
Windows 11
TinyMCE v5 & v6
Reproduced in Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)

Works fine in Firefox 104.0.2 (64-bit)

**Comment by Ampatte2** [comment]
Similiar thing here with the scrolling when enter is hit at the bottom of the editor. It causes the entire page to jump up along with the RTE.

![Similiar](https://user-images.githubusercontent.com/29719870/236460433-bb7abe81-038c-4f69-900b-06ab6e801ce2.gif)

**Comment by TheSpyder** [comment]
@Ampatte2 That is a new issue, we think it might be a regression in 6.4.2. Can you log a new issue for it please? A fiddle replication case may also be able to confirm it doesn't happen in 6.4.1.

**Comment by Clouds101** [comment]
@TheSpyder 

this issue with 6.4.2.
It was fine in 6.4.1.
I've reverted back to 6.4.1 because it happens every time I hit enter, and it's very annoying.

![36_18](https://github.com/tinymce/tinymce/assets/21264714/31c49214-daa2-4297-928f-bcdb6747f890)

**Comment by TheSpyder** [comment]
Yes, we have an internal tracking ticket for it. But it's not related to the original reported issue in this ticket so I haven't linked them.

**Comment by TheSpyder** [comment]
PR #8821 should address that (which I believe is unrelated to the original report here)
