### ISSUE TITLE
[Bug] copy paste unexpected behaviour from google docs

### ISSUE THREAD

**Issue by ggowtham67** [tinymce/tinymce#8134]
**What is the current behavior? Describe the bug**

Rich text formatting is lost when copy pasting content from Google doc with mixed content such as Regular, Italic, Bold

Sample doc: https://docs.google.com/document/d/19BwcxAJVBPzdM1BE0JzWOMECi9mZbh8Ufnfxjzhraw0/edit?usp=sharing

Steps to reproduce
- Copy the paragraph in the shared doc
- Paste the content into the editor

**What is the expected behavior?**
To retain formatting

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: v6.1.2 open source
Browser: Brave 1.43.89 Chromium: 105.0.5195.102
OS: Test on MacOS Monterey 12.4

Might be related to https://github.com/tinymce/tinymce/issues/2112

**Comment by lostkeys** [comment]
Hi @ggowtham67. What you are asking for is achieved using our premium [PowerPaste](https://www.tiny.cloud/tinymce/features/powerpaste/) plugin.
