### ISSUE TITLE
When image is linked, the cursor is inconsistent depending whether it has a caption or not

### ISSUE THREAD

**Issue by ajssd** [tinymce/tinymce#8136]
**What is the current behavior? Describe the bug**

The cursor for a linked image without a caption is "text"
The cursor for a linked image with a caption is "pointer"

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

- Insert an image
- Select the image and add a link
- Observe the cursor when mousing over the image (it is "text")
- Edit the image; click on "Show Caption"
- Re-apply the link (this seems like its own bug -- the link is lost when adding the caption)
- Observe the cursor when mousing over the image (it is "pointer")

**What is the expected behavior?**

The pointer image is incorrect, because clicking the image doesn't actually navigate to the linked URL.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

6.0, macOS

**Comment by ajssd** [comment]
https://user-images.githubusercontent.com/10245941/190692667-799369db-a8a5-46fe-9f2d-3d4eb9636601.mov

**Comment by vpyshnenko** [comment]
The issue is reproduced on Chrome/MacOS in this [Fiddle](https://fiddle.tiny.cloud/Fuiaab)

**Comment by ajssd** [comment]
> The issue is reproduced on Chrome/MacOS in this [Fiddle](https://fiddle.tiny.cloud/Fuiaab)

Looks good, the test case is therefore to add a Link to the captioned image.  The cursor will be pointer (which is incorrect).
