### ISSUE TITLE
Formatting non-editable elements

### ISSUE THREAD

**Issue by pavkriz** [tinymce/tinymce#8140]
Formatting non-editable elements via `format_noneditable_selector` option sometimes works and sometimes not, when there is a non-editable element as the first elements in the document.

Steps to reproduce
https://codepen.io/pavkriz/pen/GRdmPrQ

1. CTRL-A
2. CTRL-B works (enables Bold)
3. CTRL-B does not work (does not disable Bold)

Expected the toggle to work on and off.

TinyMCE 6.2.0 (6-testing), Chrome version 105.0.5195.125 (Official Build) (64-bit), Linux Mint 21 is based on Ubuntu 22.04.
Paying customer here ;-)

**Comment by vpyshnenko** [comment]
Reproduced on Chrome/MacOs in the [Fiddle](https://fiddle.tiny.cloud/yuiaab)
