### ISSUE TITLE
Right-clicking an image does not always select the image, leading to incorrect values in Image dialog

### ISSUE THREAD

**Issue by ajssd** [tinymce/tinymce#8143]
**What is the current behavior? Describe the bug**

Right-clicking an image does not always select the image, leading to incorrect values in Image dialog.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. go to https://www.tiny.cloud/docs/demo/full-featured/
2. View Source, and enter the following code, then Save:
`<p>two images<img title="Tiny Logo" src="../../images/logos/android-chrome-256x256.png" alt="TinyMCE Logo" width="128" height="128" />some text<img title="Tiny Logo" src="../../images/logos/android-chrome-256x256.png" alt="TinyMCE Logo" width="128" height="128" />more text</p>
`
3. Try right-clicking the images in TinyMCE -- especially (it seems) on the left-hand side of the images
4. You'll find that the text is sometimes selected as well.  In such cases, choosing Image from the context menu leads to unexpected results, as the image isn't really selected.

**What is the expected behavior?**

Right-clicking an image should select only the image, nothing else.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 6.1.2.  macOS, Safari (latest)

**Comment by ajssd** [comment]
Here is a video demo:

https://user-images.githubusercontent.com/10245941/191360545-4dbcaf57-e807-4bd9-b66e-2d009c8c22f5.mov

**Comment by vpyshnenko** [comment]
Reproduced with version 6.3.1 on MacOS/Safari  in this[ Fiddle](https://fiddle.tiny.cloud/xuiaab/1)
