### ISSUE TITLE
Is there have a Non editable mode?

### ISSUE THREAD

**Issue by PccCodesix** [tinymce/tinymce#8144]
some times have a scene。No characters can be entered, Only the style can be changed。
maybe editor have a Non editable mode?

**Comment by lostkeys** [comment]
Hi @PccCodesix! This is unfortunately not supported in TinyMCE. I recommend you to go to our [roadmap website and submit a feature idea](https://www.tiny.cloud/roadmap/). If you decide to do that, please make sure to tell us what problem you are trying to solve using this feature, the impact of having and not having it, and perhaps even if you are willing to become a paying customer to get it. A well formulated problem helps us prioritize among features and improvements. Thanks!
