### ISSUE TITLE
Table_Grid: true is not working for touch laptop.

### ISSUE THREAD

**Issue by KhurramShehzadd** [tinymce/tinymce#8154]
**What is the current behavior? Describe the bug**
When I'm using configuration table_grid and testing on touch laptop it is not showing table grid to insert the table.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
set the table_grid to true in configuration and test on touch laptop.

**What is the expected behavior?**
When we are forcing it to use table_grid, it should show table grid to insert the table.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All versions.

**Comment by Mrjiangqianli** [comment]
ggg
