### ISSUE TITLE
If you are using the editor command-left arrow, it performs a browser "Back" navigation rather than taking the cursor to the start of the line (TinyMCE 4, Firefox)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#816]
Description of problem:

If you are using the editor command-left arrow, it performs a browser "Back" navigation rather than taking the cursor to the start of the line.

The result is that you may have been working for 10 minutes, and you lose all your work in an instant.

Pressing the same key combination in Chrome just moves your cursor to the start of the current line.

Steps to reproduce:
1. Go to any webpage in Firefox on the Mac, e.g. google.com
2. Enter http://fiddle.tinymce.com/lldaab/2 into your URL bar and go there (i.e. so you have some browser history)
3. Place your cursor at the end of the line
4. Press Cmd+Left-Arrow

Expected result:
The cursor jumps to the start of the line

Actual result:
The browser navigates to the previous page
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6035](http://archive.tinymce.com/develop/bugtracker_view.php?id=6035) posted by [Chris Turnbull](http://archive.tinymce.com/profile.php?name=Chris Turnbull)_

> _**Tags:** [firefox mac osx]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/lldaab/2_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
