### ISSUE TITLE
Weird interaction between Sapling (Grammar Checker) and TinyMCE when pasting URL.

### ISSUE THREAD

**Issue by james-huang** [tinymce/tinymce#8160]
**What is the current behavior? Describe the bug**
Pasting a URL when text is selected applies a link to the selected text, but the text reverts to a previous form/version.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Repro steps:

1. Copy URL into the clipboard
2. Make text edits in TinyMCE using Sapling
3. Select the text that was edited
4. Paste URL

Higher Resolution (10MB):
https://www.dropbox.com/s/o8lnkadzs7mjann/TINYMCE_sapling_bug.mov?dl=0

Lower Resolution (3MB):
https://user-images.githubusercontent.com/990325/193103363-5548177a-6541-4291-8f94-85cb39442eaf.mov

**What is the expected behavior?**

The text does not revert to the previous form/version.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested on the version on the TinyMCE homepage. Unclear if this worked in previous versions of TinyMCE.

I'm not sure if this is a case of TinyMCE using the wrong DOM state while handling a URL being pasted when text is selected, or something else. If there is a workaround where Sapling can emit a specific JavaScript event to "lock" in edit changes before the paste event, please let me know!

**Comment by chadbaudoin** [comment]
@james-huang Can you post the code you use to integrate with Sapling?

**Comment by james-huang** [comment]
Hi Chad, 

Thanks for responding.
We update rich text editors in a couple different ways, one of which is sending a `beforeinput` `InputEvent`. 
I believe TinyMCE handles direct DOM manipulation. 

Here's a code based repro: 

```
let replacementText = 'HELLOWORLD';
let startContainer = document.getElementById('tinymce');
while (startContainer.nodeType !== 3) {
  startContainer = startContainer.firstChild;
}
startContainer.replaceData(0, 1, replacementText);
```

# Works

- Navigate to tiny.cloud, make an edit using JavaScript in the iframe context
- Modify text using keyboard (add new line somewhere)
- Copy a URL to clipboard
- Select "HELLOWORLD" text, paste
- We see a link inserted into the text

# Does not Work

- Navigate to tiny.cloud, make an edit using JavaScript in the iframe context
- Modify text using keyboard (add new line somewhere)
- Copy a URL to clipboard
- Select "HELLOWORLD" text, paste
- We see a link inserted into the text, but the text is reverted. 

Theres probably some recommended way to "lock" in edit changes that Sapling is missing for TinyMCE.
