### ISSUE TITLE
Can't change font in bullet lists' numbering (<li>)

### ISSUE THREAD

**Issue by szatanica2020** [tinymce/tinymce#8168]
I'm using Tiny editor as a feature in a bigger online platform. I do have several issues with it. Here is one.

Editor has a default font that I want to change. And while I can select a text and choose a font from top menu, a bullet list numbers a lot of times (I can't figure out when, because it doesn't happen always) don't change, but keep the other font, which causes the document to lack uniformity. Also, there is no way to change the pagination's font. It stays fixed.

I do use HTML to change the fonts in bullets manually, but it's tedious and honestly I wouldn't want an editor that in order to work requires an external HTML editor (because Tiny's html editing capabilities are basically none, no offence:) Makes no sense. 

Does anyone notice the same issues? It there a way to fix this? Or maybe a temporary workaround?

Check out the screenshot - I'm using Helvetica as my main font. Red markings show the other, default font. 

![Zrzut ekranu 2022-10-4 o 17 49 16](https://user-images.githubusercontent.com/62773449/193869553-c74fbe90-5525-438c-9985-34c1a69b7736.png)

Interestingly, the same thing happens to the size of the numbers. I can't change them back to another size, even if I change the size of the font of the text in a bullet.:

![Zrzut ekranu 2022-10-4 o 18 11 55](https://user-images.githubusercontent.com/62773449/193870906-ddbaa0d9-1da6-47c5-9bc6-e694eb7d9786.png)

**Comment by TheSpyder** [comment]
We just released a fix for this in TinyMCE 6.2:
https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/CHANGELOG.md?plain=1#L33

If you select all text in a list item then font family and size changes will apply to the list bullets/numbers.
