### ISSUE TITLE
Selecting Underline, Italic also getting selected in formatting option section

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#817]
Description of problem:
If we select Underline(U) from formatting option, Italic also getting select.
Vesion Details:
majorVersion:"3",
minorVersion:"5.0.1",
releaseDate:"2012-05-10"

Steps to reproduce the issue:-

1. Open the Tiny MCE editor page.
2. Without adding any text in the textarea, click on Underline(U) from format option.

Please check the attached screen shot for the better understanding.

Expected result: Only underline get select in Tiny MCE formatting option.

Actual result: Both underline and italic are getting selected in format option.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6036](http://archive.tinymce.com/develop/bugtracker_view.php?id=6036) posted by [Bold_Rose](http://archive.tinymce.com/profile.php?name=Bold_Rose)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
