### ISSUE TITLE
Possible bug with mceNonEditable span that causes a new line without corresponding code

### ISSUE THREAD

**Issue by mtbutah** [tinymce/tinymce#8170]
What is the current behavior:
If one has an editor with a div section with some text followed by a mceNonEditable span, and then puts the cursor on the line with the div text and presses the arrow down key, a new line is inserted before the span line. When you look at the source code, there is nothing there that represents the new line that got inserted.

Here is a demo that shows the issue:
https://fiddle.tiny.cloud/0oiaab/1

I see this on Chrome, Firefox and Edge with TinyMce version 6

Expected behavior:
If a new line gets inserted by moving the cursor down with the arrow down key, I would expect the new line to have a div section representing the new line.

**Comment by TheSpyder** [comment]
This is because the noneditable span is set to `display: block`. A temporary gap is introduced in order for there to be a cursor position before it. If you type, you'll notice that the text does appear in the source code; but if nothing is typed before save the temporary gap is removed.
