### ISSUE TITLE
media_url_resolver give wrong iframe after width / height changed

### ISSUE THREAD

**Issue by caoshaoyu** [tinymce/tinymce#8172]
**Media** plugin on TinyMCE 6.2.0
I set a **media_url_resolver** to handle Bilibili videos.

`(data, call) {
    var bilibili = data.url.match(/https:\/\/www\.bilibili\.com\/video\/(.*?)\//);
    if (bilibili) {
        call({ html: '<p><iframe src="//player.bilibili.com/player.html?bvid=' + bilibili[1] + '" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" width="640" height="480"></iframe></p>' });
    } else {
        call({ html: '' });
    }
}`

It works fine when I insert a URL, such as:
https://www.bilibili.com/video/12345

The HTML code converted to:
`<p><iframe src="//player.bilibili.com/player.html?bvid=12345" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" width="640" height="480"></iframe></p>`

However, when I changed width / height on "Insert Media" window, the code will change back to:
`<p><iframe src="https://www.bilibili.com/video/12345" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" width="640" height="480"></iframe></p>`

The **iframe src** changes to the origin **data.url** value.
Seems the formatter after width / height changes didn't follow media_url_resolver configure.

It happens on Microsoft Edge 106.0.1370.34 via Windows 11.
Please help check, thank you very much!

**Comment by axww** [comment]
Same issue here:
https://github.com/tinymce/tinymce/issues/9798
I've solved this problem by change 1 file:
https://github.com/tinymce/tinymce/pull/9824/files
