### ISSUE TITLE
How to programatically trigger autocompleter?

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#8174]
Hi, is there a way to programatically trigger autocompleter? I want to show it without typing the trigger text..

**Comment by lostkeys** [comment]
Hi @petko. This is unfortunately not supported in TinyMCE. I recommend you to go to our [roadmap website and submit a feature idea](https://www.tiny.cloud/roadmap/). If you decide to do that, please tell us what problem you are trying to solve using this feature and the impact of having and not having it. A well formulated problem helps us prioritize among features and improvements. Thanks!
