### ISSUE TITLE
6.2.0 no mobile UI on ios12.5.6 ?

### ISSUE THREAD

**Issue by jipexu** [tinymce/tinymce#8177]
Hi
no ui for the editor("mobile version") with iphone5S  IOS12.5.6

even here ? :  go https://fiddle.tiny.cloud/ 

i got 
[Error] Unhandled Promise Rejection: TypeError: undefined is not a function (near '...Promise.allSettled...')
	r (tinymce.min.js:4:61592)
	(fonction anonyme) (tinymce.min.js:4:61820)
	promiseReactionJob
Unhandled Promise Rejection: TypeError: undefined is not a function (near '...Promise.allSettled...')

**What is the expected behavior?**
to have tiny ui on mobile ...
**6.2.0 - IOS12.5.6**

Thanks for you advice ?

**Comment by TheSpyder** [comment]
TinyMCE 6 requires iOS 14. Sorry.
https://www.tiny.cloud/docs/tinymce/6/support/#supported-mobile-platforms

We do still support TinyMCE 5, which will work on iOS 12.

**Comment by jipexu** [comment]
Thank you.
