### ISSUE TITLE
Paste plugin in Chrome 16 going to recursion

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#818]
Description of problem:
In "Chrome 16.0.912.75 m" when you have on page some &ltg;input type="text"> which focus by script when DOM loaded and after load try to paste some content into editor - paste plugin going into recursion. Console throw next:
Uncaught RangeError: Maximum call stack size exceeded.

Steps to reproduce:
1. Open fiddle : http://fiddle.tinymce.com/tndaab/4 in "Chrome 16.0.912.75 m"
2. Try to paste content

Expected result:
Pasted content into editor

Actual result:
Alert with message: "Please use Ctrl+V/Cmd+V keyboard shortcuts to paste contents", no content pasted and error in console.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6037](http://archive.tinymce.com/develop/bugtracker_view.php?id=6037) posted by [DBuTbKa](http://archive.tinymce.com/profile.php?name=DBuTbKa)_

> _**Tags:** [chrome paste chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/tndaab/4_

**Comment by Luke-SF** [comment]
This is still happening in Chrome 47, and I don't think it's related to paste-plugin. Remove "paste" from plugins line and run http://fiddle.tinymce.com/tndaab/4, type in MCE, and click into the lower input-element and back to MCE. It gives two "Uncaught RangeError: Maximum call stack size exceeded." errors.

**Comment by spocke** [comment]
That fiddle used tinymce 4.0 I upgraded it to edge and now it doesn't produce that error. So can this be reproduced on the latest 4.3.2 version?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
