### ISSUE TITLE
underline changes from span to u-tag

### ISSUE THREAD

**Issue by thopark** [tinymce/tinymce#8201]
**What is the current behavior? Describe the bug**
Text formatted as underline is wrapped in p-tag.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Open http://fiddle.tiny.cloud/
Enter some text in multiple paragraphs.
Select all text and apply underline-formatting (via toolbar).
Text in Paragraphs is correctly wrapped in span[text-decoration:underline].
Select one paragraph and delete it.
Enter some text at the current cursor position .
Text is wrapped in u-tag

**What is the expected behavior?**
When entering the new text it should be wrapped in span[text-decoration:underline]

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Checked with:
TinyMCE 5.10.5
TinyMCE 6.2.0
Browser: Chrome on Windows 10 / 11

**Comment by lostkeys** [comment]
Hi @thopark, your reproduction and expected behaviour yields the same result, the text is underlined. Can you clarify?

**Comment by thopark** [comment]
@lostkeys 
In this case the result is the same, but it's semantically different. That could cause problems when you define a different style for the u-tag.

What's worse is:
We defined our own format "redunderline" with folling css:
.redunderline {text-decoration: underline; text-decoration-color: rgb(255, 0, 0);}

When we apply this format for all text and follow the steps from above we also get a u-tag where we would expect a <span class="redunderline">...</span>

And now the result is different, because the underline ist not red.

**Comment by lostkeys** [comment]
Oh, I see!

So to summarize for people after me looking at this. When making paragraphs underlined, the styles is applied inline, and we get this output
```
<p><span style="text-decoration: underline;">Test</span></p>
<p><span style="text-decoration: underline;">test</span></p>
<p><span style="text-decoration: underline;">test</span></p>
```
But after deleting the middle line of text and typing something new, the text is suddenly wrapped in a `u` element like this
```
<p><span style="text-decoration: underline;">Test</span></p>
<p><u>new text</u></p>
<p><span style="text-decoration: underline;">test</span></p>
```
I'm pretty sure this is not intentional but I leave it to one of our engineers to chime in on that.
