### ISSUE TITLE
Auto converting blob url in base64

### ISSUE THREAD

**Issue by testbuddy** [tinymce/tinymce#8202]
**What is the current behavior? Describe the bug**

It automatically converts the blob url to base64 after inserting an image.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

If I'm not mistaken, this happens because the GetContent Event in EditorUpload.

https://github.com/tinymce/tinymce/blob/65cd2e3c93b25c1d74d8a6ae0d02d01fd64a6d73/modules/tinymce/src/core/main/ts/api/EditorUpload.ts#L251-L257

**What is the expected behavior?**

It should not convert the URL before submitting.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Current Version

**Comment by TheSpyder** [comment]
Our assumption is that blob URLs are not useful outside of the page they are created on, so we convert them to base64 to ensure the HTML we produced is valid everywhere. The code you posted contains the clue for how to get the raw HTML:
`editor.getContent({ format: 'raw' })`

**Comment by testbuddy** [comment]
Thank you for your quick support! Okay, good to know :) I will try to play with the "format: 'raw'".
