### ISSUE TITLE
Copying emoji  from Twitter

### ISSUE THREAD

**Issue by yousef-alsalem** [tinymce/tinymce#8209]
Hi,
I've downloaded the latest version and it looks very nice and easy to customize. 
However, I have issue with coping text from Twitter with emoji. When I paste it to the editor,  the emoji gets very big and fill the screen!!. This behavior doesn't occur when using any of the examples in Tinymce home page or its documentation.

I use the quick start tutorial but hosting locally: https://www.tiny.cloud/docs/quick-start/
If I referenced the cloud version instead of my local one, then this issue get solved, so maybe there is a special plugin in the cloud version.

You can try using this tweet: 
https://twitter.com/tiptap_editor/status/1446085632195977218?s=20&t=QLvlIKvXvo6V_yaSnARuFg

![image](https://user-images.githubusercontent.com/15380630/197350361-345f83d3-2528-4ca5-8191-0d712e093819.png)

**Comment by zhaokaide** [comment]
you can try to set paste_preprocess in setting before init tinymce, and resize the dom of emoji
