### ISSUE TITLE
Double New Lines

### ISSUE THREAD

**Issue by vishwajit76** [tinymce/tinymce#8213]
When I convert editor content to text format, It takes double lines instead of a single line.

`editor.getContent({
                  format: "text",
 })`

EditorValue
```
<p>Line 1</p>
<p>Line 2</p>
```

Is converted into
```
Line 1

Line 2
```

It Must Be

```
Line 1
Line 2
```

Note: One Extra Line was added Between "Line 1" & "Line 2".

![image](https://user-images.githubusercontent.com/25575802/184475729-6ae2c511-4e6d-4469-9b00-880a58ec1ccd.png)

**Comment by TheSpyder** [comment]
@jaspritt-hora is correct. To get a single line in text format use a `<br>` tag, we always output two lines between block tags.
