### ISSUE TITLE
Paste event is not getting triggered

### ISSUE THREAD

**Issue by azharnh** [tinymce/tinymce#8219]
Hello Team,
I'm working on a SAP UI5 app and there I'm using Rich Text Editor which uses TinyMCE.
We have a requirement whenever user copies an image into the editor we need to upload it to our backend server, so to do this I've attached a "paste" event and "drop" event but some how paste event doesn't get triggered whenever I'm pasting any image although the drop event triggers if I drag & drop image.

Sample Code: 

 oEvent.getSource().getNativeApi().on("paste", function() {
     alert("Paste");
    }.bind(this));
    oEvent.getSource().getNativeApi().on("drop", function() {
     alert("Drop");
    }.bind(this));

SAP UI5 Rich Text Editor uses TinyMCE 5.10.2 version, I've tried above mentioned issue in chrome with widows OS

Regards,
Azhar

**Comment by zhaokaide** [comment]
try editor api like this:
 editor.on('paste', function())

**Comment by azharnh** [comment]
> try editor api like this: editor.on('paste', function())

oEvent.getSource().getNativeApi().on("paste", function() {
    alert("Paste");
}.bind(this));
that is same thing I've tried but not working.

**Comment by zhaokaide** [comment]
> > try editor api like this: editor.on('paste', function())
> 
> oEvent.getSource().getNativeApi().on("paste", function() { alert("Paste"); }.bind(this)); that is same thing I've tried but not working.

you need to put it in function editorSetUp
