### ISSUE TITLE
how to hide embed in media dialog

### ISSUE THREAD

**Issue by QMangoJ** [tinymce/tinymce#8225]
i use tinymce-react v5.x 
import { Editor as EditorComponent } from '@tinymce/tinymce-react';

how to hide embed in media dialog

<img width="544" alt="Screen Shot 2022-10-27 at 7 16 01 PM" src="https://user-images.githubusercontent.com/35953248/198270354-49caab68-be3c-4ac7-9eb5-2c6a959285a4.png">
his work in previous versions of TinyMCE?**

**Comment by QMangoJ** [comment]
please 😭

**Comment by TheSpyder** [comment]
Sorry, this plugin does not offer an option to hide the embed tab:
https://github.com/tinymce/tinymce/blob/9c486f7c951e55ae34bb548efe897eec705ac04d/modules/tinymce/src/plugins/media/main/ts/ui/Dialog.ts#L242-L245

You could submit a PR adding an option for this, which would require tests and documentation, or now that TinyMCE is MIT licensed you are free to fork the plugin and just remove `embedTab` from that code.

**Comment by lostkeys** [comment]
Hi @QMangoJ! As my colleague above said, this is unfortunately not supported in TinyMCE. In addition to what @TheSpyder said, I can suggest you to go to our [roadmap website and submit a feature idea](https://www.tiny.cloud/roadmap/). If you decide to do that, please make sure to tell us what problem you are trying to solve using this feature, the impact of having and not having it. A well formulated problem helps us prioritize among features and improvements. Thanks!
