### ISSUE TITLE
Persist the Comments conversation on page refresh. 

### ISSUE THREAD

**Issue by pooja-chawla-kindlebit** [tinymce/tinymce#8229]
Hello All, 

I am using comments plugin of tinymac editor. I want to persist comment conversation on browser if there is any open conversation page refresh .

If anyone can suggest how can Persist a already created Comments conversation on page refresh. 

Before page refresh - https://ibb.co/NK4sPR1
After page refresh -  https://ibb.co/mHWvnQ4

**Comment by TheSpyder** [comment]
Comments is a premium plugin so I'm afraid we can't assist via GitHub. If you have a support subscription, please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
