### ISSUE TITLE
Quickbars and quickbars_insert_toolbar

### ISSUE THREAD

**Issue by rvwilliams88** [tinymce/tinymce#8233]
[rvwilliams88](https://github.com/rvwilliams88)
[yesterday](https://github.com/tinymce/tinymce/discussions/8231#discussion-4524287)
I'm on version 6 and I'm trying out the code in the article about emulating Medium (https://www.tiny.cloud/blog/medium-editor/). This uses quickbars in the main textarea. The first time I click in this textarea the quickbars_insert_toolbar shows up OK. If I leave the textarea (for example to edit the title), when I return to the main textarea the quickbars_insert_toolbar doesn't appear. The quickbars_selection_toolbar does still work. Is this what is supposed to happen or is this a bug?

**Comment by lostkeys** [comment]
Hi @rvwilliams88! The quick insert toolbar only shows up on empty lines. It is a bit unclear by your description exactly what is happening so it would be helpful if you can make a screen recording or replicate the issue in a [TinyMCE fiddle](https://fiddle.tiny.cloud). Thanks.

**Comment by rvwilliams88** [comment]
Hi Fredrik

Thanks for the reply.  I was trying an example with tinymce-angular so not easy to put in a fiddle.  However I didn't understand that the quickbars_insert_toolbar only works on blank lines as the situation I was talking about was one where a line is started, the cursor is taken off the line to do something else and then brought back to continue the same line.  I can confirm that the toolbar does appear when the insert point is on a blank line.

Regards

Richard.

****************************************************
Richard Williams
email: ***@***.******@***.***>
mobile: 07981 734697
****************************************************

**Comment by rvwilliams88** [comment]
Hi Fredrik

Thanks for the reply.  I was trying an example with tinymce-angular so not easy to put in a fiddle.  However I didn’t understand that the quickbars_insert_toolbar only works on blank lines as the situation I was talking about was one where a line is started, the cursor is taken off the line to do something else and then brought back to continue the same line.  I can confirm that the toolbar does appear when the insert point is on a blank line.

Regards

Richard.

****************************************************
Richard Williams
email: ***@***.******@***.***>
mobile: 07981 734697
****************************************************
