### ISSUE TITLE
Can I insert a react component to editor

### ISSUE THREAD

**Issue by nwa2018** [tinymce/tinymce#8239]
Can I insert a react component to editor? 

I need to custom an toolbar and after user click it, I need to insert a react component to editor, can I implement it?

**Comment by lostkeys** [comment]
Hi @nwa2018. Inserting react components is not officially supported. But it depends on what you want to achieve. TinyMCE can be configured to accept custom elements, so you can insert a static "placeholder" with the markup of your react component. We are always interested to hear more about these types of advanced use-cases so feel free to tell us a bit more about your end-game and what you want to achieve.
— Fredrik Danielsson, Product Manager
