### ISSUE TITLE
启用粘贴图片功能后，无法删除条件不满足的图片，或者remove:true删除后，会出现多次弹窗

### ISSUE THREAD

**Issue by loto123** [tinymce/tinymce#8245]
images_upload_handler: async (blobInfo, success, failFun)=> {
              var file = blobInfo.blob();
              console.log(file, 'file___')
              const isLt2M = file?.size / 1024 / 1024 < 2;
              if (!isLt2M) {
                message.warning('图片上传超过2M，请重新选择上传');
                failFun('图片上传超过2M',{remove:true})
              }
}

tinymce版本：5.7.1

**Comment by lostkeys** [comment]
Hi @loto123, sorry this is too hard to understand. Please resubmit your issue with a more complete description in English and a reproduction case using a [TinyMCE fiddle](https://fiddle.tiny.cloud)

**Comment by loto123** [comment]
该邮件由 QQ邮件列表 推送。
如果您不想继续收到该邮件，可点此 退订
