### ISSUE TITLE
Change table properties

### ISSUE THREAD

**Issue by yingying96** [tinymce/tinymce#8259]
Currently we are only able to change selected properties of a table.
May i know how do we configure it to allow users to edit all properties of a table?
For example, i can change the border colors (to e.g. yellow) but i cannot edit the height and width of the cell.

![image](https://user-images.githubusercontent.com/19566726/201512557-e3529a09-848f-48eb-a7eb-82586a2c3e28.png)

**Comment by lostkeys** [comment]
Hi @yingying96. What happens if you type numbers into width and height?

**Comment by yingying96** [comment]
Can't change it. It seems to be only read-only.

**Comment by lostkeys** [comment]
Hm. I need a replication case. Can you replicate the issue in a [TinyMCE fiddle](https://fiddle.tiny.cloud)? If not, you have to investigate where the issue are in more detail. Thanks.
