### ISSUE TITLE
Tinymce - validate cell width in cell properties or is it possible to set min width for any column?

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#8261]
Hi Tiny,

We need to validate the cell width less than 10px need to show error message.
Is there any option please let us know.

Also, is it possible to set min width for column.

Thanks

**Comment by lostkeys** [comment]
Hi @Valgeria. We don't have that option out of the box, but you could probably piece together this using the various TinyMCE APIs. There exist an [event](https://www.tiny.cloud/docs/tinymce/6/events/#editor-core-events) for `TableModified` and here is a description on how you can fire a [custom notification](https://www.tiny.cloud/docs/tinymce/6/creating-custom-notifications/). Have a look at the various [demos here](https://tinymce.github.io/tinymce-demos/index.html), especially those ones tagged "master" which will give you pointers on how to use the various APIs.

The min width you can set using the [content_css option](https://www.tiny.cloud/docs/tinymce/6/add-css-options/)

Hope this helps you on your way!
