### ISSUE TITLE
Image upload is giving a pop up error "Cannot read properties of undefined (reading 'then')"

### ISSUE THREAD

**Issue by akshit-arora-ee** [tinymce/tinymce#8262]
**What is the current behavior? Describe the bug**
When the image is selected to be uploaded, a pop up appears that says: Cannot read properties of undefined (reading 'then')
Screenshot: https://prnt.sc/wyrSHjbjCEQD

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Try uploading an image in the fiddle.
http://fiddle.tiny.cloud/Qriaab

**What is the expected behavior?**
Image to be uploaded should be converted into base64 encoded image, as per the handler code. Tried by uploading the image and creating the upload link. Getting same error.

**Which versions of TinyMCE, and which browser / OS are affected by this issue?**
TinyMCE v6,
Browser: Google Chrome: Version 107.0.5304.87 (Official Build) (64-bit)

**Did this work in previous versions of TinyMCE?**
Checked on TinyMCE fiddle, this works on TinyMCE v5

**Comment by spoirier27** [comment]
@akshit-arora-ee 

I encountered the same error upgrading from v5->6. I noticed in the [migration guide](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#images_upload_handler) the _images_upload_handler_ function had changed. "Previously the images_upload_handler option passed success or failure callbacks to report the status of an image upload. In TinyMCE 6, images_upload_handler reports upload results by returning a Promise." 

Follow [the example here](https://www.tiny.cloud/docs/tinymce/6/upload-images/#images_upload_handler) to update your _images_upload_handler_ function.

**Comment by TheSpyder** [comment]
You're right, this was incorrectly classified as a bug. Thank you for the pointer.

**Comment by THE-KONDRAT** [comment]
I have the same problem. 
my `images_upload_handler `:
```js
images_upload_handler: function (blobInfo, success, failure) {
	let imgData = "data:" + blobInfo.blob().type + ";base64," + blobInfo.base64();
	success(imgData);
}
```
Or maybe i'm doing something wrong?

**Comment by spocke** [comment]
You need to return a promise in v6 see the docs here. https://www.tiny.cloud/docs/tinymce/6/file-image-upload/#images_upload_handler

**Comment by THE-KONDRAT** [comment]
Ok. now my `images_upload_handler` looks like this and works fine.

```js
images_upload_handler: (blobInfo, progress) => new Promise((resolve, reject) => {
	try{
		let imgData = "data:" + blobInfo.blob().type + ";base64," + blobInfo.base64();
		resolve(imgData);
	}
	catch (e){
		reject(e.message);
	}
}),
```
