### ISSUE TITLE
How to disable autolink function

### ISSUE THREAD

**Issue by joohnsow44** [tinymce/tinymce#8266]
hi i want to disable autolink function how i can do this?

**Comment by lostkeys** [comment]
Hi @joohnsow44. You remove it from the [plugin config option](https://www.tiny.cloud/docs/tinymce/6/autolink/). Or were you thinking about something else?

**Comment by joohnsow44** [comment]
actually i want to disable autolink function in wordpress editor . can you tell me how to do this

**Comment by lostkeys** [comment]
Hi again. Sorry this issue tracker is for the stand-alone TinyMCE editor. We can't answer how Wordpress work, so I'll recommend go asking on their forums.
