### ISSUE TITLE
Documentation: option "branding": incorrect clause about "required" product attribution

### ISSUE THREAD

**Issue by mikkorantalainen** [tinymce/tinymce#8268]
**What is the current behavior? Describe the bug**

The documentation at https://www.tiny.cloud/docs/configure/editor-appearance/#branding says following:
> Important: Product attribution is required for free and open source users. For information on TinyMCE attribution requirements, see: Logo & attribution requirements.

The current license for open source variant of TinyMCE is MIT which definitely doesn't require any branding or endorcement. The documentation should be fixed to match the current license.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Read the current documentation at https://www.tiny.cloud/docs/configure/editor-appearance/#branding

**What is the expected behavior?**

The documentation should say something like

> Notice that while the MIT license doesn't require endorcing or advertising TinyMCE, we would prefer you to keep the branding enabled if at all possible. This would help to increase the user base of the TinyMCE which will make it easier to get more resources for future development.

instead of claiming fictional requirements.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

The TinyMCE source code license was changed before release of version 6.0 but the documentation was never fixed.

**Comment by androb** [comment]
Fair point. The LGPL had more robust attribution clauses, and MIT didn't.

Regardless, there should be a solid encouragement to leave the branding in place to help promote the project.

**Comment by lnewson** [comment]
One other important thing to note here is those are the TinyMCE 5 docs which is LGPL licensed as noted above. The TinyMCE 6 docs have been updated to reflect it is not required but would be appreciated when using the MIT licensed code: https://www.tiny.cloud/docs/tinymce/6/statusbar-configuration-options/#branding

**Comment by brian-forte** [comment]
Mikko,

The [currently supported versions of TinyMCE 5][1] (versions 5.10.6 and 5.9) are [licensed][2] under the [LGPL, version 2.1][3]. And the LGPL has an attribution requirement:

> Give prominent notice with each copy of the Combined Work that the
> Library is used in it and that the Library and its use are covered
> by this License.

And the documentation for TinyMCE 5 [reflects this][4].

TinyMCE 6.x, however, is [licensed][5] under the [MIT License][6] which, as you note, does not have an attribution requirement.

And the TinyMCE 6 documentation [reflects this][7] as well.

> The TinyMCE source code license was changed before release of
> version 6.0

The [commit][8] that introduced the license change was made on 2022-02-23. And that is before the public release of TinyMCE on 2022-03-03.

But this commit was made to the TinyMCE 6 codebase. The TinyMCE version 5 codebase was never re-licensed, and TinyMCE version 5 continues to be LGPL licensed.

> but the documentation was never fixed.

The documentation regarding attribution for TinyMCE 5.x and the documentation regarding attribution for TinyMCE 6.x reflect the attribution requirements of each codebase, given the different license each codebase is released under.


[1]: <https://tiny.cloud/docs/enterprise/system-requirements/#supportedtinymceversions>

[2]: <https://github.com/tinymce/tinymce/blob/release/5.10/LICENSE.TXT>

[3]: <https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html>

[4]: <https://tiny.cloud/docs/configure/editor-appearance/#branding>

[5]: <https://github.com/tinymce/tinymce/blob/develop/LICENSE.TXT>

[6]: <https://mit-license.org/>

[7]: <https://tiny.cloud/docs/tinymce/6/statusbar-configuration-options/#branding>

[8]: <https://github.com/tinymce/tinymce/pull/7647>
