### ISSUE TITLE
when edit <section> tag, enter fall short of expectations

### ISSUE THREAD

**Issue by haogit1024** [tinymce/tinymce#8269]
**What is the current behavior? Describe the bug**
when edit section tag, enter generate source code fall short of expectations
example
source code :
```html
<section>aaaaaaaaaaaaaaaaaaa</section>
```
after Enter
```html
<section>aaaaaaa</section>
<section></section>
<section></section>
<section></section>
<section>aaaaaaaa</section>
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**
i think expectation is:
```html
<section>aaaaaaa</section>
<section>&nbsp;</section>
<section>&nbsp;</section>
<section>&nbsp;</section>
<section>aaaaaaaa</section>
```

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
2022-11-15 repetition on https://www.tiny.cloud/tinymce/features/
Browser：chrome on mac(apple silicon)

**Comment by LucaDRit** [comment]
did you manage to solve that problem? i have the exact same one. I found about keep_styles: false but it doesn't help
