### ISSUE TITLE
2 times adding Horizontal Rule in IE gives script error

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#827]
Description of problem:

Steps to reproduce:
1. Have a TinyMCE editor (classic) having the Horizontal Ruler button in toolbar
2. Click on new Horizontal Ruler button and click next to TinyMCE editor (blur)
3. Again click on Horizontal Ruler button again

Expected result:
Again a horitzonal Ruler should be added 

Actual result:
Script error will come: Unexpected call to method or property access. 

return u&&r&&r.setStart&&o.selection.createRange().item&&(i=o.selection.createRange().item(0),r=o.createRange(),r.setStartBefore(i),r.setEndAfter(i)),r||(r=o.createRange?o.createRange():o.body.createTextRange()),r.setStart&&9===r.startContainer.nodeType&&r.collapsed&&(i=t.dom.getRoot(),r.setStart(i,0),r.setEnd(i,0)),t.selectedRange&&t.explicitRange&&(0===r.compareBoundaryPoints(r.START_TO_START,t.selectedRange)&&0===r.compareBoundaryPoints(r.END_TO_END,t.selectedRange)?r=t.explicitRange:
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6045](http://archive.tinymce.com/develop/bugtracker_view.php?id=6045) posted by [abaan](http://archive.tinymce.com/profile.php?name=abaan)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
