### ISSUE TITLE
Manage table tooltip menu

### ISSUE THREAD

**Issue by yingying96** [tinymce/tinymce#8274]
May i know if there is a way to manage the table tooltip menu? E.g. edit or hide it

![image](https://user-images.githubusercontent.com/19566726/202332636-5c18b1a2-a298-49ab-985f-7151a212a083.png)

**Comment by lostkeys** [comment]
@yingying96 Have a look at the [table toolbar config option](https://www.tiny.cloud/docs/tinymce/6/table/#table_toolbar). Further down the page you see a list of all available table related toolbar buttons you can use. Hope this answers your question.
