### ISSUE TITLE
Remove bottom toolbar

### ISSUE THREAD

**Issue by NrmlPtl** [tinymce/tinymce#8275]
![image](https://user-images.githubusercontent.com/26079157/202445740-b3c5d895-f4b2-41a0-a18f-a233b1acaa22.png)

How to change the radius of the editor?
How to remove the bottom toolbar?
How to add custom editor theme/skin?

Can someone please answer these questions?

**Comment by lostkeys** [comment]
Hi @NrmlPtl!
To change the visual appearance of the editor, including the border radius but also colors, see the docs for [create a skin](https://www.tiny.cloud/docs/tinymce/6/creating-a-skin/)

See the [documentation for the statusbar](https://www.tiny.cloud/docs/tinymce/6/statusbar-configuration-options/#statusbar) on how to remove it.

Hope this helps!

**Comment by NrmlPtl** [comment]
Hi @lostkeys ,
![image](https://user-images.githubusercontent.com/26079157/203355456-916d14b0-ba4e-480c-a47a-d02cd825cabe.png)
.less file is not present. How can I edit the skin?

I am using `"@tinymce/tinymce-react": "^4.2.0"`.
