### ISSUE TITLE
how to remove default styles for ul,li tags?

### ISSUE THREAD

**Issue by bartplay2499** [tinymce/tinymce#8277]
for p it works like this:
```
formats: {
    p: {
        block: 'p',
            styles: {
            'margin': '0px'
        }
    },
},
```

**Comment by lostkeys** [comment]
Hi @bartplay2499!
If you're asking how to customize the css of the editor content, have a look at the [content_css](https://www.tiny.cloud/docs/tinymce/6/add-css-options/#content_css) option. If this is not what you're asking about, please open a new ticket and describe the issue in more detail. Thanks.
