### ISSUE TITLE
when table style is table-layout:fixed, adjusting one column width will cause the ohters column's width follow to change

### ISSUE THREAD

**Issue by qinpeifeng** [tinymce/tinymce#8281]
when the table style is table-layout: fixed, drag one column to change width, it will cause each column to change;
the reason is caused by CSS table-layout: fixed；

the html code like that:
`<table style="width: 600px; table-layout: fixed;"class="mce-item-table"><colgroup><col style="width: 300px;"data-mce-style="width: 300px;"><col style="width: 300px;"data-mce-style="width: 300px;"></colgroup><tbody><tr><td style="border:1px solid #000">1111</td><td style="border:1px solid #000">2222</td></tr></tbody></table>`

expected behavior:
when drag to change column's width,  other columns width won't be change. 

 versions of TinyMCE 5.10.3

My solution is:
change the tinymce source code.
`modules\snooker\src\main\ts\ephox\snooker\resize\Adjustments.ts`

in the adjustWidth function, before  resizing.resizeTable method invoke,like this:

`  //when table的table-layout == 'fixed' `
`  //1.when table width > all columns width, other columns will divide the remaining width equally `
`  //2.when table width < all columns width, the table width will behavior as all columns width `
`  if(table.dom.style.tableLayout=='fixed' && clampedStep>0) clampedStep = 0; `
`  resizing.resizeTable(tableSize.adjustTableWidth, clampedStep, isLastColumn);`

**Comment by yacodes** [comment]
Hi @qinpeifeng, thanks for reporting this. Is it possible for you to create a reproduction case in a TinyMCE [Fiddle](http://fiddle.tinymce.com/)?

**Comment by yacodes** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
