### ISSUE TITLE
TinyMCE - Jenkins build issue

### ISSUE THREAD

**Issue by aman-ebs** [tinymce/tinymce#8282]
Hello there,
We have implemented TinyMCE free version in our application, and it works fine in our local environment. But, when we are trying to push code, jenkins build is getting failed. I'm attaching screenshot with this support request. Kindly advise.
Thank you!!

<img width="854" alt="image" src="https://user-images.githubusercontent.com/103945892/202678573-63f1d83d-4927-4d92-afcc-81bfae0b4b2b.png">

**Comment by Afraithe** [comment]
This seems to be an issue with your build environment, not sure how this relates to TinyMCE?
