### ISSUE TITLE
Table toolbar button is not highlighted

### ISSUE THREAD

**Issue by zhaokaide** [tinymce/tinymce#8284]
**What is the current behavior? Describe the bug**
advlist plugin cant highlight
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1、use plugin advlist to insert an item into the editor content
2、select the item

**What is the expected behavior?**
the advlist icon in toolbar is highlight
![image](https://user-images.githubusercontent.com/116812155/203076324-7fc1a5ad-d238-4ee7-92b2-54d257167919.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by zhaokaide** [comment]
following is the amend code:
![image](https://user-images.githubusercontent.com/116812155/203076607-ffdc0369-c5e2-4d38-8bec-3ff61b63c946.png)

**Comment by lostkeys** [comment]
Hi @zhaokaide. What you have highlighted is the insert table button. The advlist plugin enables you to style list items and do not really have it's own button. Can you please clarify the issue, perhaps a screen recording?

**Comment by zhaokaide** [comment]
> 



> Hi @zhaokaide. What you have highlighted is the insert table button. The advlist plugin enables you to style list items and do not really have it's own button. Can you please clarify the issue, perhaps a screen recording?

**Comment by zhaokaide** [comment]
> Hi @zhaokaide. What you have highlighted is the insert table button. The advlist plugin enables you to style list items and do not really have it's own button. Can you please clarify the issue, perhaps a screen recording?

but when you insert a table in the editor, and you select the table , you will find that the table icon in toolbar is highlight

**Comment by lostkeys** [comment]
@zhaokaide, I'm sorry but It is still unclear what you ask. The list button is highlighted when you have a list selected.

![list](https://user-images.githubusercontent.com/3122929/203966457-ce03fd9a-3b57-4747-87f8-3ee65aa63528.png)

**Comment by zhaokaide** [comment]
> @zhaokaide, I'm sorry but It is still unclear what you ask. The list button is highlighted when you have a list selected.
> 
> ![list](https://user-images.githubusercontent.com/3122929/203966457-ce03fd9a-3b57-4747-87f8-3ee65aa63528.png)

![image](https://user-images.githubusercontent.com/116812155/204066942-e51279a8-9a9b-4112-b973-789fc0257445.png)

i‘m sorry , it's table plugin not advlist plugin, when you insert a table and select it, you  will find that the table plugin is not highlighted

**Comment by yacodes** [comment]
@zhaokaide If I understood correctly, you're asking to highlight the table button when the cursor is within a table. Similar to format and list tools. We'll look into it and will let you know when a fix is available.
