### ISSUE TITLE
Fetch skin from local

### ISSUE THREAD

**Issue by 29np** [tinymce/tinymce#8289]
http://localhost:3000/path/tinymce/skins/ui/mytheme/content.min.css
Error - Refused to apply style from 'http://localhost:3000/path/tinymce/skins/ui/mytheme/skin.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

` "@tinymce/tinymce-react": "^4.2.0"`

```
<Editor
        skin_url: "/path/tinymce/skins/ui/mytheme"
/>
```

I want to load custom theme from localhost. Can someone please tell me how to do that?

**Comment by LucaDRit** [comment]
did you manage to solve it? i'm having the same problem with a plugin and the docs don't have a section about it
