### ISSUE TITLE
Uncaught Error: tinymce should have been loaded into global scope

### ISSUE THREAD

**Issue by zhifou** [tinymce/tinymce#8297]
online question Uncaught Error: tinymce should have been loaded into global scope
but local dev normal
why？I  have used qiankun.

import React from 'react';
import axios from 'axios';
import { Editor } from '@tinymce/tinymce-react';
// 必须引入
// eslint-disable-next-line no-unused-vars
import tinymce from 'tinymce';

// TinyMCE wants to be in global scope, even if loaded from npm module
window.tinymce = tinymce;

// Theme
import 'tinymce/themes/silver';
// Toolbar icons
import 'tinymce/icons/default';
// Editor styles
// import 'tinymce/skins/ui/oxide/skin.min.css';
import 'tinymce/models/dom';
// importing the plugin js.
import 'tinymce/plugins/advlist';
import 'tinymce/plugins/link';
import 'tinymce/plugins/image';
import 'tinymce/plugins/lists';
// import 'tinymce/plugins/hr';
import 'tinymce/plugins/fullscreen';
import 'tinymce/plugins/table';
// import 'tinymce/plugins/paste';
// import 'tinymce/plugins/autolink';
// import 'tinymce/plugins/charmap';
// import 'tinymce/plugins/anchor';
// import 'tinymce/plugins/searchreplace';
// import 'tinymce/plugins/wordcount';
// import 'tinymce/plugins/code';
// import 'tinymce/plugins/insertdatetime';
// import 'tinymce/plugins/media';
// import 'tinymce/plugins/nonbreaking';
// import 'tinymce/plugins/template';
// import 'tinymce/plugins/help';

**Comment by yacodes** [comment]
Closing this issue due to lack of information. Please create a new issue with more information, using the template provided.

**Comment by hlongc** [comment]
@zhifou 这个问题解决了吗
