### ISSUE TITLE
On page Scroll, close any open dropdown

### ISSUE THREAD

**Issue by sonikasharma1403** [tinymce/tinymce#8316]
**What is the current behavior? Describe the bug**
Say for instance we have a dropdown open, like font select and we have a hug page outside, ideally on scroll of outside page, the dropdown should close 
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://codepen.io/sonika11/pen/WNyaeNr
**What is the expected behavior?**
API support to close the dropdown on main page scroll

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
v6.3

**Comment by lostkeys** [comment]
Hi @sonikasharma1403, yep this is currently how TinyMCE works. To help us prioritize any change to TinyMCE, can you provide some additional context why this is problematic in your use-case and how important it is to have it be addressed. Thanks!

**Comment by sonikasharma1403** [comment]
we have a fixed header, and the dropdown looks weird behind the header. Hence, we need a config to close any popups that are open while scrolling

**Comment by sonikasharma1403** [comment]
@lostkeys - is there any way to toggle dropdown via `execCommand`

**Comment by lostkeys** [comment]
Hi again! Sorry it seems we do not have any API to programatically close the menus. I have added a feature request for this but I cannot say when or even if we have the chance to visit this. You can always fork TinyMCE and try to fix it yourself.
