### ISSUE TITLE
toolbar mode not working when we specify toolbar as an array of strings

### ISSUE THREAD

**Issue by sonikasharma1403** [tinymce/tinymce#8318]
**What is the current behavior? Describe the bug**
toolbar mode not working when we specify toolbar as an array of strings, but works when toolbar config is a string

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://codepen.io/sonika11/pen/yLERBVX

**What is the expected behavior?**
toolbar mode should work irrespective of how we send toolbar input

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
v6.3

**Comment by lostkeys** [comment]
Hi @sonikasharma1403. What you describe is a feature and [the way you define multiple toolbars](https://www.tiny.cloud/docs/tinymce/6/toolbar-configuration-options/#using-multiple-toolbars). The toolbar mode only kicks in when you have more toolbar buttons than fits on a row.

**Comment by sonikasharma1403** [comment]
@lostkeys 
toolbar_mode should work irrespective of how we pass the toolbar, but that's not happening here.
tried: `toolbar` as string - works
`toolbar` as array of string - does not work
`toolbar(n)` approach like you mentioned - does not work

**Comment by lostkeys** [comment]
Sorry toolbar mode is not supposed to work with multiple toolbars, it is used to handle overflowing buttons on a toolbar. Please feel free to describe in more detail what you want to achieve and I can place a feature request.
