### ISSUE TITLE
toolbar_mode does not work when we pass toolbar as an array of string

### ISSUE THREAD

**Issue by sonikasharma1403** [tinymce/tinymce#8319]
**What is the current behavior? Describe the bug**
toolbar_mode does not work when we pass toolbar as an array of string. It works iff we pass a string

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://codepen.io/sonika11/pen/RwJebKz

**What is the expected behavior?**
toolbar_mode should work irrespective of how we pass the toolbar config

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
v6.3

**Comment by lostkeys** [comment]
Sorry, it's still the same answer as in #8318. Closing as duplicate.
