### ISSUE TITLE
TinyMCE removing whole script tag and contents even after allowing all the contents

### ISSUE THREAD

**Issue by mathewm3** [tinymce/tinymce#8321]
**What is the current behavior? Describe the bug**
I have enabled the setting - **verify_html : false** (all settings to allow script contents), to accept all the contents entered in TinyMCE. But the whole script including the script tag is removed.

This happens when the script tag contains fields which satisfies the regex **/<[/\w]/g**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
link - https://fiddle.tiny.cloud/Ytiaab/1

source code attached - [fnWithLessThan.txt](https://github.com/tinymce/tinymce/files/10142165/fnWithLessThan.txt)

if you remove the contents in the method - setUrlLink(), it will work fine.

**What is the expected behavior?**
All the contents should be retained as it is.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE version 6.1.2 (2022-07-29)
Browser - Chrome

**Comment by mathewm3** [comment]
[fnWithLessThan.txt](https://github.com/tinymce/tinymce/files/10142165/fnWithLessThan.txt)

**Comment by mathewm3** [comment]
Following code in **_sanitizeElements** is the culprit. 

```
if (currentNode.hasChildNodes() && !_isNode(currentNode.firstElementChild) && (!_isNode(currentNode.content) || !_isNode(currentNode.content.firstElementChild)) && regExpTest(/<[/\w]/g, currentNode.innerHTML) && regExpTest(/<[/\w]/g, currentNode.textContent)) {
          _forceRemove(currentNode);
          return true;
        }
```

It think lot of elements are removed without checking any configuration/setting which leads to unexpected behaviour.

**Comment by Titan21** [comment]
I've also run into this issue, trying to migrate from another editor to TinyMCE (v6.2.0).

We have a script, similar to the following:

```
<script>
   var message = "First Line<p>Second Line";
   // Code here to popup message in modal overlay
</script>
```

I've tried all combinations of `extended_valid_elements`, `valid_children`, `verify_html` and everything else I could think of.

As long as I've got any tags inside the script's message, the entire script block is stripped out.

Would be great to see this fixed.

**Comment by Titan21** [comment]
For anyone stumbling upon this,
We've found setting
```
tinymce.init({
	selector: '#tiny',
        extended_valid_elements: 'script[*]',
        protect: [/<script.*>[\s\S]*?<\/script>/g];
});
```
can be a work-around

**Comment by empiricompany** [comment]
If you have difficulty dealing with the insertion of empty <p> tags after the scripts, I have used this:
```
protect: [
    /([\s\S]\*?)<script([\s\S]*?)>([\s\S]*?)<\/script>([\s\S]\*?)/ig,
    /([\s\S]\*?)<style([\s\S]*?)>([\s\S]*?)<\/style>([\s\S]*?)/ig
],
```
