### ISSUE TITLE
Tinymce V6 - Topmost Menu Item Click Still Closes Tinymce In Safari

### ISSUE THREAD

**Issue by nickjgentile** [tinymce/tinymce#8322]
**What is the current behavior? Describe the bug**
In Safari, if you have the following initialization settings: `inline: true` with a `fixed_toolbar_container` set, when you click the top-row of the menu items in the toolbar, the toolbar disappears.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://jsfiddle.net/Nickjgentile/rL3cato8/2/

(I forked this fiddle from https://jsfiddle.net/j70u4ohs/2/ which is the same issue just in version 5 of tinyMCE, whereas I want to highlight that this is still and issue and version 6 was released with this bug).

**Reproduction Steps:**

- click one of the top-most items in the Tinymce toolbar in Safari (any version of Safari seems to do it).
- **Expectation**: Opens menu items for selected menu button.
- **Result**: Closes the toolbar entirely.

Note: If you FIRST click a menu item from the bottom row of the toolbar, THEN click a menu item from the top row of the toolbar, it works fine. However thats not an acceptable workaround for us to communicate to clients. 

Also, this bug ONLY happens with you have BOTH inline: true AND a fixed_toolbar_container -- remove either one and it works as expected - however we use both of these options and the major browsers should support tinymce-supported init options.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Any version of Safari, it seems like this was an issue with Tinymcev5 and continues to be an issue in Tinymcev6 (my fiddle is specifically using 6.3.0 (https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.3.0/tinymce.min.js)

**Comment by nickjgentile** [comment]
To expand a little -- I guess as I look into this more it is the `menubar` (i was previously referring to this as the 'top row') items that, when clicked first, make the toolbar disappear.

**Comment by nickjgentile** [comment]
This is reproducible in your test suite's fixed_toolbar_container_demo.html test file, if you just open it in Safari.

**Comment by lukasasorensen** [comment]
Anything being done about this? I am currently having the same issue. Wanting to upgrade to v6 but I can't have it not working in Safari... :(
