### ISSUE TITLE
Can't add link to an image

### ISSUE THREAD

**Issue by webIMT** [tinymce/tinymce#8334]
If an image is in p tag like this code :
```
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><img style="display: block; margin-left: auto; margin-right: auto;" src="../images/image.jpg" alt=""></p>
<p>&nbsp;</p>

```
To reproduce the bug : If I want to add a link to the image by using the link button 

1) I select the image
2) I add the URL in the modal window and press Save button, 

Bug : no a tag (link tag) is added. 
But if I use right click and contextual menu, the a tag is added...

TinyMCE 6.3.1 
Firefox 107.0.1 but same bug with all browsers.

**Comment by vpyshnenko** [comment]
Hi, webIMT. It would be helpful if you provide the example for reproducing the issue in the [Fiddle](https://fiddle.tiny.cloud/baaaab)

**Comment by webIMT** [comment]
https://fiddle.tiny.cloud/0uiaab/3 but I'm not sure it's saved

**Comment by vpyshnenko** [comment]
You need to click `Fork` button to get a new reference to your Fiddle and then if you want to update click `Save`.

**Comment by webIMT** [comment]
I've added the HTML code below but when I click on Save, nothing is saved...
```
<p>&nbsp;</p>
<p><img style="display: block; margin-left: auto; margin-right: auto;" src="https://www.imt.fr/wp-content/uploads/2022/02/logo-imt-rp.png" alt="" width="240" height="100"></p>
<p>&nbsp;</p>
```

**Comment by vpyshnenko** [comment]
Reproduced in this [Fiddle](https://fiddle.tiny.cloud/Duiaab/5) on Firefox/MacOS
