### ISSUE TITLE
when google chrome upgrade to the lastest vesion 108.0.5359.95,  Rich text writing will freeze

### ISSUE THREAD

**Issue by anyue100** [tinymce/tinymce#8335]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by anyue100** [comment]
tinyMCE version is 6.1.0.

**Comment by xiaohuijunjun** [comment]
I have a similar problem with editing Cottonwood when the word count exceeds 5,000 +

**Comment by spocke** [comment]
I think we need more details here could you provide a fiddle where this is happening.
What operating system are you using and exact version of the browser?
What do you mean with writing using normal input method though keyboard or say a IME?
Could you provide us with a fiddle/codepen or similar where this can be reproduced.

I made a fiddle here: https://fiddle.tiny.cloud/4uiaab with 10000 words I wasn't able to reproduce it tested it on:
Windows 10 Chrome Version 108.0.5359.99 (Official Build) (64-bit)
Linux Chrome Version 108.0.5359.94 (Official Build) (64-bit)

I tested it by loading that fiddle and typed text at various locations in the document. Could not find the exact build number `108.0.5359.95` maybe that specific Chrome build has issues. Could you try upgrading to the latest if possible.

**Comment by Freedom-2020** [comment]
I've upgraded to the latest browser 108.0.5359.99 , but it's still stuck.    I tested it here https://www.tiny.cloud/docs/tinymce/6/basic-example/

**Comment by anyue100** [comment]
> I think we need more details here could you provide a fiddle where this is happening. What operating system are you using and exact version of the browser? What do you mean with writing using normal input method though keyboard or say a IME? Could you provide us with a fiddle/codepen or similar where this can be reproduced.
> 
> I made a fiddle here: https://fiddle.tiny.cloud/4uiaab with 10000 words I wasn't able to reproduce it tested it on: Windows 10 Chrome Version 108.0.5359.99 (Official Build) (64-bit) Linux Chrome Version 108.0.5359.94 (Official Build) (64-bit)
> 
> I tested it by loading that fiddle and typed text at various locations in the document tested both 6.3.1 and 6.1.0. Could not find the exact build number `108.0.5359.95` maybe that specific Chrome build has issues. Could you try upgrading to the latest if possible.

-------------------------------------------------
we found issue in window 10, and upgrade to 108.0.5359.99 (Official Build) (64-bit) ,the issue remains.  our text have 16700 words.

**Comment by spocke** [comment]
Could you try running the links in Chromes incognito mode since that would disable chrome extensions just want to verify that there is no conflict with some extension.

**Comment by Freedom-2020** [comment]
Actually, I've tried incognito mode, and the problem still hasn't been solved. I wrote 12000 words in Chinese.

**Comment by ddjtddjt** [comment]
> Could you try running the links in Chromes incognito mode since that would disable chrome extensions just want to verify that there is no conflict with some extension.

I met the same problem in 108.0.5359.99 Chrome. The editor was stuck, even though the browser worked  in Chromes incanognito mode.
I used tinymce 6.1.0 and there was 8000 words I wrote

**Comment by ryanvall** [comment]
@anyue100 @Freedom-2020 @ddjtddjt does your rich text contain custom CSS at all? We recently ran into an issue in our application where some pages (including ones that utilize TinyMCE) froze on chrome v108. Turns out it's a chromium/CSS issue - a specific combination of `column-count`, `display: flex`, and margin-based styles. 

If that sounds applicable, you can follow that bug issue [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1395408).

**Comment by ddjtddjt** [comment]
> @anyue100 @Freedom-2020 @ddjtddjt does your rich text contain custom CSS at all? We recently ran into an issue in our application where some pages (including ones that utilize TinyMCE) froze on chrome v108. Turns out it's a chromium/CSS issue - a specific combination of `column-count`, `display: flex`, and margin-based styles.
> 
> If that sounds applicable, you can follow that bug issue [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1395408).

No.  There's no custom CSS in my rich text. and it's even stuck in the official demo.

**Comment by penpenChen-cn** [comment]
I tried to keep copy and pasting original content in official demo in https://www.tiny.cloud/
Fill hard(1-2 second delay) to input new character when total word comes to 5000+, chrome will totally stuck when reach to 8000+ words.
Environment: window 11 professional, chrome 108.0.5359.99 (Official Build) (64-bit)

**Comment by anyue100** [comment]
@spocke Today, after I upgraded to chrome version to 108.0.5359.125, I found that copying large text was still stuck. When the copying was complete, scrolling up and down or editing improved, but it still didn't return to the smoothness of the beginning.
I hope these are helpful for problem locating.

**Comment by 593377931** [comment]
It seems a bug from Chrome
when set this div element to contenteditable, the browser will be stucked
test in Chrome stable 108.0.5359.125 and Chromium's 110.0.5463.0

works fine in Firefox 108.0, Chromium's 74.0.3684.0 and 106.0.5249.0

test page:
https://output.jsbin.com/fiwujibizi

**Comment by ibin79** [comment]
Looks like a bug in Chrome v108.

In my case, the problem was solved by entering `chrome://accessibility/` in the browser address bar and then unchecking the `Web accessibility`.

![image](https://user-images.githubusercontent.com/6302755/209916015-1f11f73b-2b51-44a8-9eca-839a92bf0eab.png)


---
- https://bugs.chromium.org/p/chromium/issues/detail?id=1396198&q=ContentEditable&can=2
- https://chromium-review.googlesource.com/c/chromium/src/+/4120465
