### ISSUE TITLE
Custom styles via attribute for lists

### ISSUE THREAD

**Issue by bartplay2499** [tinymce/tinymce#8340]
Good afternoon, how do I add a style attribute for any lists, when pasting through the toolbar.
For the paragraph, I specified this during initialization and it works:
`
formats: {
  p: {
      block: 'p',
      styles: {
          'margin': '0px'
      }
  }
}
`
How to do something similar for lists(ul, ol)
Through the insertion of a separate css option is not suitable it is necessary to attribute
![tiny](https://user-images.githubusercontent.com/54477221/207284296-ea127b13-7305-4784-9504-f474f6e291ef.png)

**Comment by lostkeys** [comment]
Hi @bartplay2499! I'm not sure I follow you. Are you asking how to set certain styles on list items?

**Comment by bartplay2499** [comment]
I want to hang styles on ul, ol tags using attributes, not a class with styles. so that it is inserted into the html

**Comment by bartplay2499** [comment]
I want that when inserting lists into the editor, they will automatically put the following in html: style="margin: 0px;". Both when adding from other sources and from the toolbar
