### ISSUE TITLE
Can't write empty tags

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#835]
Hi (sorry for errors but I'm Italian...)!
I shoud write in the HTML code this: "&ltg;td>&ltg;a>ABC &ltg;span>DEF&ltg;/span>&ltg;/a>&ltg;/td>", but tinyMCE automatically removes "&ltg;span>&ltg;/span>" because the tag is empty. In fact, if I write "&ltg;span clas='abc'>DEF&ltg;/span>", the code doesn't change.
In the version 3 there isn't this "problem" (this is not a problem, but for me it is!), so I understood that it's a new feature. So I went on the migration page but I don't see this changing.
Is this a plugin? How can I remove this feature?
Thanks a lot!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6054](http://archive.tinymce.com/develop/bugtracker_view.php?id=6054) posted by [Lucart98](http://archive.tinymce.com/profile.php?name=Lucart98)_
> 
> _**Tags:** [empty tags]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
