### ISSUE TITLE
Undo operation cannot get the expected result

### ISSUE THREAD

**Issue by lizhangyi** [tinymce/tinymce#8351]
**What is the current behavior? Describe the bug**
undo operation can't recover my last operate

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. open the official example: https://www.tiny.cloud/docs/tinymce/6/
2. press enter button after 'Hello, World!' to restart a new line
3. input 'abcd' into editor
4. press backspace button delete 'cd' character
5. press 'undo' button in toolbar
6. 
![image](https://user-images.githubusercontent.com/81246775/208579103-ad9c0871-a207-4d60-88cf-d2cb597a682a.png)

**What is the expected behavior?**
after undo, should editor's content is 'abcd'?

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMce6.1.0 and official page's example
Google Chrome 108.0.5359.99
widnows10

**Comment by Freedom-2020** [comment]
I face the same problem！
