### ISSUE TITLE
Tab-press in table with non-editable-content leads to endless loop

### ISSUE THREAD

**Issue by thopark** [tinymce/tinymce#8355]
I have a table that is contenteditable=false except some td.
Cursor is in one of the editable td.
Pressing tab leads to an endless loop, since tinymce tries to add a new row and then moving to the first cell of that row, which is not possible, so it tries to add a new row, etc.
This loop freezes the browser.

Expected behavior:
loop is detected; no more tries to create a new row; cursor stays in current td

version 5.10.5, browser: chrome on windows

**Comment by lostkeys** [comment]
Hi @thopark. Yeah unfortunately you are a bit outside of the envelope of what the content editable feature was designed for. For reference, I've included a replication case here: https://fiddle.tiny.cloud/0viaab

To help us better understand and prioritize this issue, can you fill us in on the following details. If you don't want to do it publicly, feel free to submit your feedback over at our [roadmap website](https://www.tiny.cloud/roadmap/)

1. Why is the requested feature important for your app/service?
2. What is the consequence of not having the requested feature?
3. How important would you rate the requested feature choosing from nice-to-have, important or critical?

Thanks,
Fredrik – Product Manager

**Comment by thopark** [comment]
use case: prefilled forms, where the user is allowed to only edit certain parts of the form, while other parts are locked.
We implemented a workaround to disable tab-navigation in tables.

1. Why is the requested feature important for your app/service?
Users who prefer keyboard-naviagtion should be able to use the tab-key without the risk of crashing the browser

2. What is the consequence of not having the requested feature?
Users cannot use the tab-key or risk to crash the browser (which is critical and must never happen in our application)

3. How important would you rate the requested feature choosing from nice-to-have, important or critical?
Since we have a workaround this is rated important; without that it would be critical
