### ISSUE TITLE
Paste from context menu not working 

### ISSUE THREAD

**Issue by sadiqueali786** [tinymce/tinymce#8358]
I am trying to paste the content using the context menu paste and it is not working.
![paste not working](https://user-images.githubusercontent.com/60964121/209433820-9afcf077-a450-4532-9b9d-4b84169c6cb6.PNG)

**Comment by yacodes** [comment]
Hi @sadiqueali786, thanks for reporting this. Please, provide your browser type and version.

**Comment by yacodes** [comment]
Closing this issue, as it is being addressed and escalated in https://github.com/tinymce/tinymce/issues/8078.
