### ISSUE TITLE
More options for removeformat

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#836]
Basically a reintroduction of the removeformat_selector setting from version 3.x.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6055](http://archive.tinymce.com/develop/bugtracker_view.php?id=6055) posted by [jezzdk](http://archive.tinymce.com/profile.php?name=jezzdk)_
> 
> _**Tags:** [removeformat]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
