### ISSUE TITLE
"tox tox-silver-sink tox-tinymce-aux" blocks page elements

### ISSUE THREAD

**Issue by Simbiat** [tinymce/tinymce#8363]
**What is the current behavior? Describe the bug**
It looks like TinyMCE spawns an empty div with classes "tox tox-silver-sink tox-tinymce-aux", at some point after load (but not at `init`), which is placed at the top of the page and can block clickable elements under it.
![image](https://user-images.githubusercontent.com/6022665/209829533-a5cc5317-67b5-4043-874d-1020d952f80e.png)
Once it's loaded I can "fix" this by either unchecking `position: relative`, which breaks alignment for all menus, `display: none`, which hides all menus, or by setting `width: 0!important` for the element.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
For some reason I am not able to reproduce this on Fiddle, but maybe it's not the same build as in tinymce-dist, which I download with Composer? I also can't share a live link either, since on production instance editor is not available yet.

**What is the expected behavior?**
No blocking-divs, I guess. Since the width looks to be setup for the element specifically, my guess would be that that particular line of code may need to be removed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
6.3.1, checked in Edge and Chrome. Not sure if this was the behavior

**Comment by Simbiat** [comment]
Found an issue with 0 width: 
![image](https://user-images.githubusercontent.com/6022665/209838018-eb94a81e-c883-43a0-97a2-2f2cda41fc27.png)

**Comment by lostkeys** [comment]
The "sink" is the container for menus and dialogs and it's injected in the dom at the bottom of the HTML document to make sure it's ontop of other UI element. But it should not be active and blocking other content unless you have something open.

Have a look at your CSS and see if you apply any wildcard declarations that might affect the sink.

**Comment by Simbiat** [comment]
Wanted to copy the styles from the element to show that it does not have anything that would put the block at the top, but while doing it, an idea hit me, which I was able to confirm: my `body` has `display: grid`, and since this block is added directly into `body` and does not have `grid-area` it renders this way. If I add a `grid-area` attribute with any random name, it renders (invisibly) at the bottom right at the edge.
Since I can "fix" this through simple CSS, not sure if anything needs to be done here, but perhaps this behavior could be documented somewhere.

**Comment by lostkeys** [comment]
Good it got sorted out. It's a known issue, but not really a bug either. I've logged it in our internal systems for future reference
