### ISSUE TITLE
Very high z-index when resizing editor 

### ISSUE THREAD

**Issue by enesag** [tinymce/tinymce#8365]
**What is the current behavior? Describe the bug**

When I resize the editor, it gets in front of some floating (absolutely positioned) elements.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Lets say you have an element with some z-index (for example 100) in front of the editor (in my case this element was my navbar). when i try to resize the editor, it gets a very high ([2^31 − 1](https://en.wikipedia.org/wiki/2,147,483,647#In_computing) to be precise) z-index value. And moves in front of the element.

Minimal demo: https://codesandbox.io/p/github/enesag/tinymce-zindex/draft/nifty-cannon?file=%2Fsrc%2FApp.js

Just try to resize the editor and pink div disappears

**What is the expected behavior?**

I dont expect z-index changes when i resize the editor pane. Resizing works fine but z-index change causes a bad experience in my opinion. I don't know why this z-index change was necessary but even if its necessary it might be more relevant lower value (like 10, 20, 100, 1000 etc.)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE: 6.3.1
Browser: Up-to-date (108.0.5359.125) Chrome
OS: Windows 11 (22H2)

I dont know if it works differently in previous versions.

**Comment by yacodes** [comment]
Hi, thanks for reporting this. Confirming that this is a reproducible issue in Chrome (not FF however). Quite sure that this behavior is expected because resizing is an active action. We will have a discussion and will come back to you in a while.

**Comment by enesag** [comment]
For others facing the same problem, i've temporarily fixed it by setting a class that has a z-index value with `!important` to the editor component, by using jquery in tinymce editor option called `init_instance_callback`.
