### ISSUE TITLE
[5.x] Paste plugin removes whitespace

### ISSUE THREAD

**Issue by bytestream** [tinymce/tinymce#8368]
**What is the current behavior? Describe the bug**

I use the `paste` plugin to allow copy/paste and drag/drop of images into the editor. However, when the `paste` plugin is used the way plain text clipboard content is processed changes and introduces undesirable behaviour. 

Clipboard content:
```
Test

Test
```

With `paste` plugin (https://fiddle.tiny.cloud/Tviaab), the editor produces:
```html
<p>Test</p>
<p>Test</p>
```

Without `paste` plugin (https://fiddle.tiny.cloud/Tviaab/1), the editor produces:
```html
<p>Test</p>
<p><br></p>
<p>Test</p>
```

**What is the expected behavior?**

I expect the `paste` plugin to match the default editor behaviour:
```html
<p>Test</p>
<p><br></p>
<p>Test</p>
```

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

5.10.7

**Comment by bytestream** [comment]
It's https://github.com/tinymce/tinymce/blob/5.10.7/modules/tinymce/src/plugins/paste/main/ts/core/Newlines.ts#L50 which eats the empty new line.

**Comment by Naiem890** [comment]
Facing the same issue. Is there any solution for this problem?

**Comment by bytestream** [comment]
Yes still an issue.

**Comment by TheSpyder** [comment]
This is an intentional feature. One newline between plain text lines translates to a `br` tag, two translates to a `p` tag.

**Comment by Mohamed3nan** [comment]
this is still a problem with latest version!
