### ISSUE TITLE
Textpattern, Paste, Noneditable, Bbcode, Preview etc plugins are missing in TinyMCE6

### ISSUE THREAD

**Issue by akash07k** [tinymce/tinymce#8378]
**What is the current behavior? Describe the bug**
Unable to find `Textpattern`, `Paste`, `Noneditable`, `Bbcode` etc. plugins in TinyMCE6 selfhostable downloads
Above mentioned very important plugins are missing in TinyMCE6 selfhostable downloads.
However, they are listed on the [Official open source plugins listing page](https://www.tiny.cloud/docs/plugins/opensource/) and it they are not even listed under premium plugins.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Download any release of TinyMCE6 from the [Official Page](https://www.tiny.cloud/get-tiny/self-hosted/)
2. Extract the zip.
3. Navigate inside the `tinymce/js/plugins` directory and look for the `textpattern`, `Paste`, `Noneditable`, `Bbcode` etc. directories.
4. They are no longer there.
**What is the expected behavior?**
The plugins should be there in the downloaded zips, or it should be mentioned if those plugins are removed intentionally.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE6
Yes, the plugins are available in TinyMCE5 downloads

**Comment by TheSpyder** [comment]
It was mentioned that they were removed intentionally, in the release notes:
https://www.tiny.cloud/docs/tinymce/6/6.0-release-notes-core-changes/#removed-or-deprecated-plugins

Some of them were moved into the core, others had been deprecated in v5 and were removed in v6.

**Comment by akash07k** [comment]
@TheSpyder 
So, Since Textpattern plugin is now the part of TinyMCE core, how do we define the textpatterns in our configurations as we previously used to do?
I checked, most of the text patterns are not working by default.
Please help.
> It was mentioned that they were removed intentionally, in the release notes: https://www.tiny.cloud/docs/tinymce/6/6.0-release-notes-core-changes/#removed-or-deprecated-plugins
> 
> Some of them were moved into the core, others had been deprecated in v5 and were removed in v6.

**Comment by akash07k** [comment]
@TheSpyder Any ideas on this?
I am unable to use the textpatterns due to this issue

**Comment by TheSpyder** [comment]
Sorry I didn't respond at the time, I should've linked to the full docs not just the changelog entry.

**Comment by akash07k** [comment]
No problem.
