### ISSUE TITLE
More options for paste plugin

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#838]
It would be nice to have more control over content that gets pasted from a webpage or Word, since that's what many users tend to do.
More specifically, it would be nice to be able to discard empty elements, only allow certain elements and so on.
Also pasting text from a webpage or Word often inserts &ltg;p> elements with only a space in them, which adds a lot of empty space in the editor, so a trim option would also be nice.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6058](http://archive.tinymce.com/develop/bugtracker_view.php?id=6058) posted by [jezzdk](http://archive.tinymce.com/profile.php?name=jezzdk)_
> 
> _**Tags:** [paste paste_as_text paste_from_word]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
