### ISSUE TITLE
Autocompleter not triggering in Chrome on Android

### ISSUE THREAD

**Issue by terraxus94** [tinymce/tinymce#8380]
We ran into an issue where the trigger character doesn't trigger the autocompleter dropdown. The issue is similar to the one reported below
- https://github.com/StevenDevooght/tinyMCE-mention/issues/50

Could it be that this issue is caused by the keypress event being deprecated in Chrome on Android? 

We found that the trigger **works** on Android 7, Chrome 75.0.3770.143 (tested on a Samsung Galaxy A5) and **doesn't work** on Android 13 and Chrome 108.0.5359.128 (Tested on a Samsung Galaxy S21+)
The issue was observed on versions tinymce/tinymce-react": "3.10.2" and tinymce/tinymce-react": "4.2.0"

Expected behaviour 
<img width="361" alt="Screenshot 2023-01-09 at 15 54 24" src="https://user-images.githubusercontent.com/61805273/211338666-2b07fd0b-d83c-46de-8b19-48854c23db57.png">

Current behaviour
![2023-01-09 15 58 38](https://user-images.githubusercontent.com/61805273/211338682-742cdf0e-dfd8-4c72-a65c-5dfd4852e478.jpg)

**Comment by Haskaris** [comment]
We reproduce the same issue, using:
- TinyMCE 5.10.3
- tinymce/tinymce-react 4.2.0

Working on:
- Android 10 - Firefox 111.1.1
- Android 10 - Firefox 112 

Not working on:
- Android 10 - Brave 1.50.114, Chromium 112.0.5615.49
- Android 10 - Chrome 112.0.5615.47
- Android 10 - Edge 24.7.410403314 
- Android 13 - Opera 74.1.3922.71199, Chromium 110

**Comment by kunal-punjrath** [comment]
This is still reproducible with TinyMce 6.5.1 on Chrome on Android 12.
