### ISSUE TITLE
Custom fonts are not working on mac

### ISSUE THREAD

**Issue by khasman** [tinymce/tinymce#8385]
**Problem**
I have added the custom fonts and they working on windows system, but not working on mac 

**This is my code:**

<script src="https://cdn.tiny.cloud/1/rowge2tbueik0mj7u5hywsyce3oewy0p1pwqiuzalru4fhad/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>

        tinymce.init({

            selector: 'textarea',

            height: 300,

            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount | image code',

            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough| fontselect forecolor backcolor| link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',

            font_formats:
                "Agency FB;Algerian;Arial;Arial Black;Arial Narrow;Arial Nova;Arial Nova Cond;Arial Nova Cond Light;Arial Nova Light;Arial Rounded MT Bold;Bahnschrift;Bahnschrift condensed;Bahnschrift light;Bahnschrift light condensed;Bahnschrift light semicondensed;" +
                "Bahnschrift semibold;Bahnschrift semibold condensed;Bahnschrift semicondensed;Bahnschrift semilight;Bahnschrift old face;Bauhaus 93;Bell MT;Berlin Sans FB;Berlin Sans FB Demi Bold;Bernard MT Condensed;blackadder ITC;Bodoni MT;Bodoni MT Black;Bodoni MT Condensed;" +
                "Bold Italic Art;Book Antiqua;Bookman Old Style;Bookshelf Symbol 7;Bradley Hand ITC;Britannic Bold;Calibri;Calibri Light;Californian FB;Calisto MT;Cambria;Cambria Math;Candara;Candara Light;Cascadia Code;Cascadia Code Light;Cascadia Code SemiBold;Cascadia Mono;",

            image_title: true,

            automatic_uploads: true,

            file_picker_types: 'image',

            file_picker_callback: function(cb, value, meta) {
                var input = document.createElement('input');

                input.setAttribute('type', 'file');

                input.setAttribute('accept', 'image/*');

                input.onchange = function() {

                    var file = this.files[0];

                    var reader = new FileReader();

                    reader.onload = function () {

                        var id = 'blobid' + (new Date()).getTime();

                        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;

                        var base64 = reader.result.split(',')[1];

                        var blobInfo = blobCache.create(id, file, base64);

                        blobCache.add(blobInfo);

                        // call the callback and populate the Title field with the file name
                        cb(blobInfo.blobUri(), { title: file.name });

                    };

                    reader.readAsDataURL(file);
                };

                input.click();
            }
        });
    </script>

**TinyMCE v6** is using here

**Comment by lostkeys** [comment]
Hi @khasman! You have a very generic question about fonts. [Have a look at the page source for this webfonts demo](https://tinymce.github.io/tinymce-demos/tinymce-basics/fonts.html) and get back to us if you have any problem.

— Fredrik, Product Manager
