### ISSUE TITLE
The tinymce 4.01 editor disappears from a jQuery UI Tab when entering the tab the second time

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#839]
Description of problem:

The tinymce4.0.1 editor disappears from a jQuery UI Tab when entering the tab the second time, and the tab is loaded dynamically via ajax request. Using timymce 3.x everything is ok!

Steps to reproduce:
1. - create a jQuery UI Tab with 2 or more tabs
2. - load the content of the tab via ajax request, the request returns a textarea and the js code to create a tinymce editor 
4. - navigate through the tabs, when a tab is first loaded the editor appears correctly, but when you revisit a tab the editor is not appearing anymore, and the textarea is hidden 

Expected result:
   the editor should appear after the tab is visited more then one time
Actual result:
   the editor is not appering

-In the attachment i made a simple demo of the problem, index.htm is the main file (only creates the tabs), content1.htm, content2.htm, content3.htm are the files loaded via ajax as a tab content and contains a textarea and js to create the tinymce editor. 
-When index.html is loaded the editor is apperaing correctly, selecting tab2, tab3 is also ok, but when you revisit any of the tabs the editor is not appearing any more (the textarea is also hidden). 
-The same exapmle is working without any problem with tinymce 3.x, it can be tested by uncommenting tinymce3.x and commenting tinymce4 in the index.html file.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6059](http://archive.tinymce.com/develop/bugtracker_view.php?id=6059) posted by [r_imreh](http://archive.tinymce.com/profile.php?name=r_imreh)_
> 
> _**Tags:** [firefox msie safari chrome opera ajax jqueryui tab tinymce401]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
