### ISSUE TITLE
getContent or setContent results in error within walkTree method

### ISSUE THREAD

**Issue by ststrobel** [tinymce/tinymce#8390]
**What is the current behavior? Describe the bug**
whenever I try to either `getContent()` or `setContent()`, I get an error with the following stacktrace:
```
Uncaught (in promise) ReferenceError: i is not defined
    at _loop6 (app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2369:42)
    at walkTree (app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2369:217)
    at Object.parse (app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2369:6971)
    at setContentString (app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2360:381238)
    at app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2360:382105
    at Optional.map (app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2360:4835)
    at setContentInternal (app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2360:382001)
    at Object.setContent (app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2369:30865)
    at setContent$2 (app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2369:38384)
    at app-angular.js?id=9803a4a1453a082b43bd7d5949608f5e:2369:60980
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
I could track the issue down to the `walkTree` method of the DomParser (https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/api/html/DomParser.ts), specifically to the processing of the postprocessors.
The following code snippet creates the error:
```
for (let i = traverseOrder.length - 1; i >= 0; i--) {
        const node = traverseOrder[i];
        each$e(postprocessors, postprocess => postprocess(node));
}
```
Interestingly, it seems that the body of the for-loop is not actually executed... I changed the dist file tinymce.js locally in my node_modules and if I insert a `console.log(i)` inside the loop, nothing gets printed. It seems the error occurs within the definition of the for-loop.
When I change this to the following, it works 🤯:
```
let i = traverseOrder.length - 1;
for (i; i >= 0; i--) {
        const node = traverseOrder[i];
        each$e(postprocessors, postprocess => postprocess(node));
 }
```

**What is the expected behavior?**
The `walkTree` method works as expected, no error occurs when calling `getContent()` or `setContent()`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- tinymce 6.3.1
- Windows/Mac

**Comment by ststrobel** [comment]
the issue was resolved on my end.

*tl&dr;* always use the tinymce.min.js file in your build scripts!

It had to do with my local build setup (webpack/babel). It seems that the syntax of the foor-loop in the was causing the issue: When referencing tinymce.js in our build script, this is what comes out in the minified script:
```
var _loop6=function _loop6(){var node=traverseOrder[i];each$e(postprocessors,function(postprocess){return postprocess(node);});};for(var _i75=traverseOrder.length-1;_i75>=0;_i75--){_loop6();}};
```

However, when bundling the tinymce.min.js script, everything works as expected. Interesting that this for-syntax seems to cause an issue...

**Comment by TheSpyder** [comment]
I can only assume the optimiser, when looking at the full code, assumes `i` is available in scope and shifts the code around accordingly. That's a pretty weird bug!
