### ISSUE TITLE
no warning when cookies disabled was: Ubuntu 11.10 oneiric FF20  does not show tinymce on your TryIt page

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#840]
Possibly this hits other Browsers/OS's too. First I thought it was a special Ubuntu/Firefox bug - but just was my paranoid browser settings :-) .

Anyway - it would be nice to be warned of failing functionality when cookies disabled  or Javascript disabled.

So, should this ticket be moved to 'feature requests'?

Regards, Orson

Description of problem:

Steps to reproduce:
1. have Ubuntu 11.10 started 
2. Prepare Firefox so that cookies are disabled
2. with Firefox goto www.tinymce.com/tryit/basic.php

Expected result: As in Ubuntu Chrome or any other MSWindows browser: show basic tinymce with drop down menues and buttons below

Actual result:
text field shows source code, look at screenshot

Same result with Firefox 'restarted with Add-Ons disabled'

No problems at all with 
Chromium Version 25.0.1364.160 Ubuntu 11.10 (25.0.1364.160-0ubuntu0.11.10.1)

Kind regards,
Orson

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6060](http://archive.tinymce.com/develop/bugtracker_view.php?id=6060) posted by [Orson](http://archive.tinymce.com/profile.php?name=Orson)_
> 
> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
