### ISSUE TITLE
Can't calculate working SRI-Hash as cdn.tiny.cloud delivers seemingly different versions of the .js

### ISSUE THREAD

**Issue by PyroRider** [tinymce/tinymce#8401]
I tried generating the SRI hash for tinymce 6 but all generated values (including the ones by 2 different official sri generators) differ from each other and are all marked as wrong by chrome and firefox. is there an official SRI hash for the versions to be found anywhere?

TinyMCE 6 cloud version (free), happens in Chrome and Firefox

**Comment by TheSpyder** [comment]
Unfortunately we cannot support SRI hashes with TinyMCE cloud. There are two reasons for this:
* New minor and patch release versions are deployed without clients needing to change the URL. This is a benefit of using our cloud hosting, but every update would break existing hashes.
* Our cloud hosting adds extra dynamic scripting to preconfigure the editor based on cloud services the API key has available. This means the version available to download for self-hosting will never match the cloud, and we update it more frequently than the TinyMCE release cycle which exacerbates the first point.
