### ISSUE TITLE
When I use insertContent, tinymce will change my html structure.

### ISSUE THREAD

**Issue by wudi98** [tinymce/tinymce#8418]
When I use insertContent, tinymce will change my html structure.

Steps:
1.You can go to this page and edit it: [https://codesandbox.io/s/peaceful-vaughan-wckdms?file=/src/App.js](https://codesandbox.io/s/peaceful-vaughan-wckdms?file=/src/App.js)
2.Select the second and third rows and click the add comment button.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/47620997/216253836-fd6f9d3d-437a-4bd2-9696-a51588b947b1.png">
3.We can see that the final rendered structure is not the one we inserted.
<img width="660" alt="image" src="https://user-images.githubusercontent.com/47620997/216254156-0fabdc43-10c7-4f9d-b41c-c2bd758e5820.png">

expected behavior：
Insert the processed html as normal.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/47620997/216254230-cc221cb7-343c-4631-bb2f-e8a61e0cd19d.png">
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/47620997/216254460-c98dd5a8-d91c-4d4e-9e12-febb17b79202.png">

I'm using "@tinymce/tinymce-react": "^3.14.0"
MacBook pro

**Comment by lostkeys** [comment]
Hi @wudi98 What you are trying to do is [not valid HTML](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element). A `<ul>` should only contain `<li>` elements so TinyMCE works as expected here. I recommend you add the div inside the list item.

Fredrik Danielsson – Product Manager
