### ISSUE TITLE
MCE4 - Plain text - blockquote in html selection  => extra blank spaces in the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#842]
Html source to select (after parsed):
&ltg;article>
	&ltg;blockquote class="messageText ugc baseHtml">
		&ltg;b>fefezfezf&ltg;/b>&ltg;br>&ltg;i>efezfezfezf&ltg;/i>
	&ltg;/blockquote>
&ltg;/article>

Activate the plain text paste mode

Paste
=> some extra blank spaces (br) are added inside the editor

Tested on Firefox.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6063](http://archive.tinymce.com/develop/bugtracker_view.php?id=6063) posted by [cclaerhout](http://archive.tinymce.com/profile.php?name=cclaerhout)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
