### ISSUE TITLE
TinyMCE's placeholder div for dropdowns is in a different stacking context to the main editor

### ISSUE THREAD

**Issue by angusmglfraser** [tinymce/tinymce#8421]
**What is the current behavior? Describe the bug**

TinyMCE spawns a placeholder div at the end of the body for floating UI elements (mostly dropdown menus). This means that it's competing with every other top-level element for stacking, which means that TinyMCE toolbar won't work with some solutions for managing modals/slideovers/etc. Example: http://fiddle.tiny.cloud/Zxiaab/1

Since the div above the form has a higher z-index than Tiny's placeholder div, it wins over any of TinyMCE's dropdowns (e.g. font selection, font size, extra toolbar items if they overflow, etc)

**What is the expected behavior?**

The div for floating UI elements should be in the same stacking context as the editor. If you manually grab that div and append it to the same stacking context that the editor is in, floating UI elements appear as expected (see example: http://fiddle.tiny.cloud/ayiaab/1). It also means that if you spawn a modal while tiny has a dropdown open, you won't end up with Tiny's UI rendering on top of it if it has a lower z-index than `.tox-tinymce-aux`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I have this issue with TinyMCE 6.3.0, but have confirmed it is still happening in v5. I have this on all browsers and devices I have tested (Firefox and Chrome on Android, Firefox, Chrome, Safari on macOS, Firefox, Chrome, Edge on Windows)

**Comment by angusmglfraser** [comment]
http://fiddle.tiny.cloud/ayiaab/2

I've found a slightly better workaround - moving the placeholder div into `editor.editorContainer`. This makes floating UI elements work in fullscreen mode as well

**Comment by TheSpyder** [comment]
That workaround is along the lines of what we're implementing as an option to solve problems with scrollable containers. This should address modal stacking issues as well. Tracking ticket is #5097.
