### ISSUE TITLE
Errors "Could not find valid *required* value for "link" in" in console while writing url in link dialog

### ISSUE THREAD

**Issue by ShoresOfNowhere** [tinymce/tinymce#8423]
Many errors of the type "Could not find valid *required* value for "link" in" appear while typing link url in link dialog.

This happens in a simple installation with only the link plugin active, in the latest 6.3.1.

**Comment by ShoresOfNowhere** [comment]
I have found that the error happens when the list_link is set to an empty object []

This is none the less a bug, since there might be times when the external url that lists links has no link to propose.

**Comment by 1437552152** [comment]
+1  我也上传的时候遇到这个问题，请问怎么解决啊
