### ISSUE TITLE
6.0+ custom dialog components - text as html string no longer supported (breaking from 5.X)

### ISSUE THREAD

**Issue by lofcz** [tinymce/tinymce#8435]
**What is the current behavior? Describe the bug**

In 5.10.3 it is possible to style pre-defined dialog components with HTML where `text: string` is expected.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Run the following sample plugin:

```js
tinymce.PluginManager.add('bugplugin', function (editor, url) {

var openDialog = function () {
    return editor.windowManager.open({
        title: 'Bug',
        size: 'medium',
        body: {
          type: 'tabpanel',
                tabs: [
                    {
                        name: 'bug',
                        title: 'Bug',
                        items: [
                            {
                                type: 'label',
                                label: '<b>bold label text</b>',
                            }
                        ]
                   }
             ]
        }
});
```

This correctly renders **bold label text** in 5.10.3. In 6.X it displays `<b>bold label text</b>`.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

6.3.1

**Comment by TheSpyder** [comment]
Allowing HTML in the label field was a mistake; the documentation of 5 clearly states it was intended to be text.
https://www.tiny.cloud/docs/ui-components/dialogcomponents/#label

However by the time we realised our mistake fixing it constituted a breaking change, so we had to wait for the next major release.
https://www.tiny.cloud/docs/tinymce/6/6.0-release-notes-core-changes/#dialog-labels-render-correctly

**Comment by lofcz** [comment]
Are you open to re-evaluating whether to add an option to render texts as markup or include `html` fields to components where `text` now is? Being able to use markup was a great help as I could wholly lean onto the built-in components and style them without arbitrary limitations. Without this users would have to reimplement even such basic things as a label.

**Comment by TheSpyder** [comment]
That would be a question for @lostkeys 

The new UI in TinyMCE 5 was designed to be consistent, not adjustable, and to be honest offering the ability to inject raw HTML into the dialog is not really a great way to add extendability.

**Comment by lofcz** [comment]
> The new UI in TinyMCE 5 was designed to be consistent, not adjustable, and to be honest offering the ability to inject raw HTML into the dialog is not really a great way to add extendability.

I guess that makes sense from the perspective of product owners. But consider also your customer's case - having the ability to inject arbitrary HTML into any built-in component enabled us to quickly develop plugins while delegating all the heavy work to the built-in components. We could style labels (new lines, emphasis..), create a custom progress bar for image uploading, and post-upload summary.  We have used this heavily in TinyMCE 5 and now we have to invest in rewriting our extensions in order to migrate to 6.

While @TheSpyder clarified this was a "mistake" on your side in the first place I consider it an amazing feature. Hence, if it already worked and should it be cheap to get it working again (possibly as a new field `html` in components) it would enable our use-case.
