### ISSUE TITLE
Button for toggle menubar visibility

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#844]
The toolbar have all what most users need, so I would like to hide the menubar as default option and with a toolbar button to show it or hide it again.

So tinymce look much better as compact version and a user can reactivate full menubar features.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6062](http://archive.tinymce.com/develop/bugtracker_view.php?id=6062) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** [4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺

**Comment by giangcoi48k** [comment]
`tinyMCE.init({
    selector: '.ckeditor-biinreport-enabled',
    branding: false,
    plugins: 'print preview paste searchreplace autolink directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern',
    toolbar: 'bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist | removeformat | mybutton',
    setup: function (editor) {
        editor.addButton('mybutton', {
            icon: "mce-ico mce-i-preview",
            onclick: function () {
                $(editor.editorContainer).find(".mce-container.mce-menubar.mce-toolbar.mce-first").toggle();
            }
        })
    },
    init_instance_callback: function (editor) {
        $(editor.editorContainer).find(".mce-container.mce-menubar.mce-toolbar.mce-first").toggle();
    }
});`

**Comment by giangcoi48k** [comment]
```
tinyMCE.init({
    selector: '.ckeditor-biinreport-enabled',
    branding: false,
    plugins: 'print preview paste searchreplace autolink directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern',
    toolbar: 'bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist | removeformat | mybutton',
    setup: function (editor) {
        editor.addButton('mybutton', {
            icon: "mce-ico mce-i-preview",
            onclick: function () {
                $(editor.editorContainer).find(".mce-container.mce-menubar.mce-toolbar.mce-first").toggle();
            }
        })
    },
    init_instance_callback: function (editor) {
        $(editor.editorContainer).find(".mce-container.mce-menubar.mce-toolbar.mce-first").toggle();
    }
});
```
