### ISSUE TITLE
Warning message when using an inline text link is in English while language is set to Dutch

### ISSUE THREAD

**Issue by RobD-tech** [tinymce/tinymce#8442]
**What is the current behavior? Describe the bug**
When you have the link plugin installed, the language in the popup message is not correct.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Make sure you have the Dutch version of TinyMCE installed. 
2. Click on the link icon in the toolbar to add or edit a link.
3. Type for instance "/example" in the URL field and click Save. 
4. A warning popup will appear saying: "The URL you entered seems to be an external link. Do you want to add the required https:// prefix?" while the buttons are in Dutch (i.e. "Nee" and "Ja").

**What is the expected behavior?**
I expect the warning message in the popup to be in Dutch just as the button labels are.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE version 5.8.2, using Chrome.

**Comment by RobD-tech** [comment]
@yacodes I can see you've added some labels to my issue, thank you for that. Not sure if you're the right person to ask, but do you know if or when this issue can be picked up any time soon?

**Comment by TheSpyder** [comment]
Sorry for not following up. If you're using community translations, that string seems to have translations available:
https://crowdin.com/translate/tinymce/40/en-nl?filter=basic&value=0#q=the%20url%20you%20entered

If you don't want to download a complete new translation set, you may be able to patch that into your string file yourself. It's a JavaScript object with the english string as the keys and the translated text as the values.

**Comment by RobD-tech** [comment]
Massive thanks for the quick response. We have a self-hosted installation so we'll probably need to either download the newest translation set or manually include the translation in there ourselves.
