### ISSUE TITLE
Space cannot added to the end of the word if there are no space between the image and word

### ISSUE THREAD

**Issue by johnnywys26** [tinymce/tinymce#8446]
Currently there is a bug when the word and image stick together, the if the word and image have a space in between then this bug will not occur.

The attachment video is how we can replicate on tinymce demo page
[screen-recorder-fri-feb-10-2023-11-34-59.webm](https://user-images.githubusercontent.com/108114726/217994872-d70ec948-7993-4a2a-a821-2672444e17ba.webm)

**Comment by yacodes** [comment]
Hi @johnnywys26, thanks for reporting this! Confirming that the bug is present in Chrome (not in FF though).
