### ISSUE TITLE
Selecting image in IE and view source gives script error

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#845]
Description of problem:

Steps to reproduce:
1. Go with IE10 browser to try it on tinymce.com and select basic example
2. Select the tinymce log image in the example
3. From menubar select Tools -> Source code
4. Press OK button on Source Code plugin
5. Script error is coming Invalid Argument: ge(),o.addElement(a),o.select())),n.editorManager.activeEditor!=n&&((t=n.editorManager.activeEdi

Expected result:

Actual result:

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6065](http://archive.tinymce.com/develop/bugtracker_view.php?id=6065) posted by [abaan](http://archive.tinymce.com/profile.php?name=abaan)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
