### ISSUE TITLE
TinyMCE Editor Text area is not visible: Version 4.9.2

### ISSUE THREAD

**Issue by dixitrohit17** [tinymce/tinymce#8453]
During the first time loading the editor, is not displaying the text area though tollbar displayed. On the other hand if editor closed and reopen it start working fine.

Editor code is available in JS file and it initialize on View load.

Observation:
On `createIframe` function at `DOM$3.add(o.iframeContainer,ifr)` , `o.iframeContainer` value contains a lot of HTML on first time load. When this much of HTML is available on the variable it did not displayed the text area. 
HTML: 
```
<div id='mceu_15' class='mce-top-part mce-container mce-stack-layout-item mce-first' hidefocus="1" tabindex= "-1" role="group">
      <div id="mceu_15-body" class="mce-container-body">
             ------ More nested HTML -------
      </div>
 </div>
```

While reopening the editor, `o.iframeContainer` value contains only one `div` 
i.e. `<div id='mceu_15' class='mce-edit-area mce-container mce-panel mce-stack-layout-item mce-last' hidefocus="1" tabindex= "-1" role="group"> </div>`

Ideally editor should be opening on the first time load.

Editor Version: 4.9.2
It is not browser specific issue, already validated on Google Chrome (v 110+) and Microsoft Edge.
Operating system: Windows 10.

Thanks in advance, Kindly help me out on this issue do let me know in case of any other details are required.

**Note:** Code cannot be shared due to policy.

**Comment by TheSpyder** [comment]
We don't support TinyMCE 4 anymore, sorry.
https://www.tiny.cloud/blog/tinymce-4-support-window/

The last version of the TinyMCE 4 code will always be available in the git history, if you'd like to work with it yourself:
https://github.com/tinymce/tinymce/tree/4.x
