### ISSUE TITLE
There is no possibility to move photos within content editing.

### ISSUE THREAD

**Issue by tarzinio** [tinymce/tinymce#8457]
Hi,

There is a problem in firefox. You cannot move the photo to another position. There is no such problem in chrome.

**Browser: Firefox and Chrome (last update)**

https://user-images.githubusercontent.com/29274594/219039289-1314ea29-3858-471f-86c9-dbf8be82fb16.mp4

**Comment by lostkeys** [comment]
I can verify this being an issue using the latest Firefox developer edition on Mac. Notice the cursor inside the image selection on the bottom left.

![firefox_issue](https://user-images.githubusercontent.com/3122929/220667444-49108957-2948-4c6a-ab53-3b143779cc00.gif)

**Comment by tarzinio** [comment]
I found a solution. Browser plugins have been disabled. One of them had an influence (although it's strange). You can close the ticket. :D
