### ISSUE TITLE
Replace Function Produces Invalid Argument Error

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#846]
Description of problem:I am using Tiny MCE version 3.5.7.  I click on the Find/Replace button and enter the search and replace text.  When I click on either Replace or Replace All button in the dialog, I get an error: Invalid Argument from Line 1, Char: 175044 of searchreplace.htm.

Steps to reproduce:
1. See above
2.
3.
4.
5.

Expected result: Text would be replaced in the textarea.

Actual result: Error from searchreplace.htm stating Invalid Argument.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6066](http://archive.tinymce.com/develop/bugtracker_view.php?id=6066) posted by [wheeliea](http://archive.tinymce.com/profile.php?name=wheeliea)_

> _**Tags:** [msie msie9 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
