### ISSUE TITLE
Checkmarks in color select menu

### ISSUE THREAD

**Issue by sadovsf** [tinymce/tinymce#8467]
**What is the current behavior? Describe the bug**
For some reason when i want to change color of either text or text bg menu for selecting that color has check icons on every single color. On official preview this is not visible, at a same time though from debuging it should be as all entries in that menu are generated having "checkmark" icon at: 
https://github.com/tinymce/tinymce/blob/415ae82dbc55c375f039e112b9497f99a369b53d/modules/tinymce/src/themes/silver/main/ts/ui/core/color/Options.ts#L14-L27

Now question is. Is it bug on official example which for some reason does not show this icon or in local usage in which case only solution as this is hard coded icon seems to be not registering given icon in first place and replace whole icons file.

<img width="423" alt="Snímek obrazovky 2023-02-20 v 17 02 21" src="https://user-images.githubusercontent.com/2211533/220153788-81d942e9-3e37-44cd-9e9b-aa182473330b.png">

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Seems simple instantiation is enough. Here are my options:
```ts
{
target:  vTarget, // target is empty div
skin_url:    `/styles/wysiwyg/skin/${vTheme}`,
content_css: `/styles/wysiwyg/content/${vTheme}/content.min.css`,
}
```

And imports:
```ts
import tinymce from "tinymce";
import type { Editor as TinyEditor, RawEditorOptions } from "tinymce";
export { Editor } from "tinymce";

import "tinymce/models/dom";

import "tinymce/icons/default";
import "tinymce/themes/silver";
```

Does not seems like i would be doing something strange in there

**What is the expected behavior?**
I would expect to have checkmark only on icon used for selected text (where cursor is). And based on menu implementation itself it seems there was intention of exactly that but it does not work.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
MacOS Ventura 13.2.1
Firefox 110.0
TinyMCE 6.3.1 (from npm)

**Comment by TheSpyder** [comment]
It's weird, I admit, but the TinyMCE skin is designed to hide every check mark that isn't active:
https://github.com/tinymce/tinymce/blob/415ae82dbc55c375f039e112b9497f99a369b53d/modules/oxide/src/less/theme/components/color-swatch/color-swatch.less#L74-L76

Please check the styles applied to the swatch with your skin and make sure the `display:none` is high enough to apply when appropriate.

**Comment by sadovsf** [comment]
Funny enough, in examples svg is not even inside tox-swatch divs which could not be achieved only by css 😳

For sure css you mentioned is missing from skin generated using http://skin.tiny.cloud/t5/ which i just noticed is for version 5. Maybe change in version 6 then? Any idea when version 6 generator will be available?
