### ISSUE TITLE
Ice Track Changes By Range Not Working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#847]
Description of problem:I am using Tiny MCE version 3.5.7.  I also added the plugin for ICE Track Changes.  When I select text and remove the text, the strike-trough does not display on the deleted text.  However, if I use the Delete key on the keyboard and delete one character at a time, this is working.

Steps to reproduce:
1.See above
2.
3.
4.
5.

Expected result:Track Changes would display a strike-through on the deleted range of character.

Actual result: Selected text remains, but without the strke-through.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6067](http://archive.tinymce.com/develop/bugtracker_view.php?id=6067) posted by [wheeliea](http://archive.tinymce.com/profile.php?name=wheeliea)_
> 
> _**Tags:** [msie msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
