### ISSUE TITLE
 [Accessibility Issue] Keyboard navigation issue with table option

### ISSUE THREAD

**Issue by jhkeswani18** [tinymce/tinymce#8475]
**What is the current behavior? When user is trying to make use of Keyboard to interact with Table option in TinyMCE
1) User is unable to access the table icon popup which appears next to the mouse cursor using keyboard.
2) After we insert table in the edit field, a table options popup appears. The user is unable to navigate to the popup using keyboard.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior? keyboard interaction for table options should work

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE? 6.0

Observation:
After checking with Windows Accessibility tool, we found that UIA property "IsKeyboardFocusable" is set to false for the table tool bar group

**Comment by TheSpyder** [comment]
I'm not sure what you mean in the first point. Whether I click the insert table menu or navigate to it with a mouse, the size of the table to insert can be controlled with the keyboard.

For the second point, It is possible to access context toolbars with the keyboard, but it's not a standard shortcut. Our help dialog explains the keyboard shortcuts available in the editor:

> Context toolbars and menus
> 
> To focus an open context toolbar such as the table context toolbar, press Ctrl + F9 (Windows) or ⌃F9 (MacOS).
