### ISSUE TITLE
Erorr is coming trying to insert a smiley on selected rule

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#848]
Description of problem:

Steps to reproduce:
1. Start Firefox with a page having TinyMCE having the horizontal ruler and the emoticons options in the toolbar. (On the tinymce.com website use the classic example below the try it section.)
2. Click on horizontal rule button. A horizontal line will be inserted.
3. Select the horizontal line
4. Click on the emoticons icon in the toolbar and select an emoticon
5. Now an error will come: 
TypeError: n is undefined

Expected result:

Actual result:
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6068](http://archive.tinymce.com/develop/bugtracker_view.php?id=6068) posted by [abaan](http://archive.tinymce.com/profile.php?name=abaan)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
