### ISSUE TITLE
ceFalse and contentEditable issue, figcaptions are editable from public-facing website. 

### ISSUE THREAD

**Issue by pmacswebteam** [tinymce/tinymce#8486]
Using TinyMCE 5 with MODX, we are having issues getting figcaptions to work properly. In our testing, figcaptions can be edited from our public-facing website(s). ceFalse and contentEditable seem to be the issue(s).

-Removing ceFalseOveride: true from tinymcerte.image_format does not change figcaption.
-Adding figcaption to tinymcerte.image_format settings does nothing.
-Trying to add a custom style for figcaptions also did not solve issue.
-contenteditable only appears in code when we give the image a specific alignment (left, right, or center).
-changing the values in tinymcerte.image_format setting breaks the editor.

Has anyone else using TinyMCE had issues with Images, Figures, and Figcaptions?

Is this something that will be or has been fixed in TinyMCE 6?

**Comment by lostkeys** [comment]
Hi @pmacswebteam. TinyMCE do not output figcaptions with contenteditable enabled. Are you doing some customizations of TinyMCE yourself? If not, you need to check with the MODX team as we cannot debug their TinyMCE integration from here.

**Comment by pmacswebteam** [comment]
Thanks for the quick response @lostkeys!

To clarify, the issue is that we want to apply a class to captioned images, specifically we want to put the class on the `<figure>` element that wraps the image. The only way we found to get a class on the `<figure>` is to use "ceFalseOverride":true in the style definition, like this:

```
{"title":"Left","selector":"img,figure","attributes":{"class":"pull-left"},"ceFalseOverride":true}
```

... and we used `"attributes": {"class":  "pull-left"}` rather than "class": "pull-left" because we want only that class and not "pull-right" for example.

This works when we're editing the content in TinyMCE, but when we view our saved content, the figcaption inside of the figure has the content-editable="true".

Is there a way to apply classes to `<figure>` without messing with "ceFalseOverride" in TinyMCE 5(preferably) or TinyMCE 6? Is there any other information that would help you help us?

**Comment by pmacswebteam** [comment]
We figured out a fix for our problem. Here it is in case someone else has a similar issue.

We found that adding the `image` class which TinyMCE adds to captioned images (figures) to each of our style definitions solved the problem of having contenteditable="true" on the figcaptions. 

So, this

```
{"title":"Left","selector":"img,figure","attributes":{"class":"pull-left"},"ceFalseOverride":true}
```

becomes: 

```
{"title":"Left","selector":"img,figure","attributes":{"class":"pull-left image"},"ceFalseOverride":true}
```
