### ISSUE TITLE
The background color does not change after the font size is changed

### ISSUE THREAD

**Issue by 1249190004** [tinymce/tinymce#8489]
https://user-images.githubusercontent.com/51875117/221456532-6ce6c25d-0060-406d-b391-d81a9cc4e60c.mp4

**Comment by 1249190004** [comment]
When the selected font becomes smaller, the background color of the currently selected font should also be changed

**Comment by HAFRMO** [comment]
To clarify, do you want the background color to be reset to white (transparent) on the section with changed font size, or do you want it to be shrunk vertically, similarly to the size it would have if the entire selection had been changed to the smaller font?

**Comment by 1249190004** [comment]
The background color of the corresponding font shrinks vertically when the font is reduced.

**Comment by 1249190004** [comment]
Of course, I'm not sure if this is a bug or a feature; the background color I got from other libraries like wangEditor changes with the font size.

**Comment by HAFRMO** [comment]
The situation here is that the background does change size ( try giving the tiny text a different color when you resize it ), but the color of the parent element's background is visible as well, which is the 'large' color background that you see. (The nesting is the size 'inside' of the background color )
This is likely an unintended result, though I'm hesitant to call it an outright bug. This would probably be classed as a feature request, so I'll tag it as such.
