### ISSUE TITLE
Poor performance for html with tables

### ISSUE THREAD

**Issue by mmubd** [tinymce/tinymce#8494]
**What is the current behavior? Describe the bug**

I'm upgrading from TinyMCE 4 to TinyMCE 6.
However, rendering performance for v6 is considerably worse than v4.
The input lag is several seconds.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

The behavior can be seen with this input: https://pastebin.com/2bYrKcnW

**What is the expected behavior?**

Seamless editing.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

This affects the latest version on Win10.
It worked in v4 TinyMCE.

**Comment by lostkeys** [comment]
Hi @mmubd! Are you using any of the integrations (eg. Vue, React, Angular)? A "vanilla" instance of [TinyMCE handles your example code fine](https://fiddle.tiny.cloud/c0iaab), but we know there are issues when using the integrations.

**Comment by mmubd** [comment]
Hi @lostkeys I'm using the angular integration @tinymce/tinymce-angular 7.0.0.
However, I've also tested on the editor displayed on your front page which also showed the issue https://www.tiny.cloud/.

I can confirm that "vanilla" TinyMCE handles it better. Still jerky but better.

So what is your recommendation? Rewrite our integration to use "vanilla" or?

**Comment by mmubd** [comment]
Hi @lostkeys 

I've done some more testing of vanilla vs. angular TinyMCE.
Unfortunately the typing performance is poor in both cases.

Is there anything we can do or can you look into this?
