### ISSUE TITLE
Icons  are not clearly visible in multiple places only in High Contrast 'Aquatic' mode.

### ISSUE THREAD

**Issue by cgk1994** [tinymce/tinymce#8496]
The icons present in toolbars are not clearly visible in high contrast 'Aquatic mode'

1. Open tinyMCE editor - https://codepen.io/cgk1994/pen/JjaEZWQ
2. Turn on High Contrast(Aquatic/Desert) using Settings->Accessibility->Contrast Themes->Aquatic/Desert.
3. Observe the icons in tool bar.

![tinyMCE_Icons_HC](https://user-images.githubusercontent.com/126610719/221954671-b9f5604e-02e3-4100-88b4-ccc48a83ee4f.png)
The icons are not clearly visible

tinyMCE - v6.0
Browser - Google Chrome

**Comment by cgk1994** [comment]
@HAFRMO  -- Hey, Do you have any idea about the fix of above mentioned issue? . Any sort of doc related to above will be really helpful.

**Comment by TheSpyder** [comment]
We are aware we need to do better in high contrast mode. The `oxide-dark` skin is probably suitable, but we don't have any way to switch skins when the operating system is in high contrast.
https://fiddle.tiny.cloud/e5iaab
