### ISSUE TITLE
No numbers and click command for the checkboxes using voice access commands. 

### ISSUE THREAD

**Issue by cgk1994** [tinymce/tinymce#8497]
No number is shown using 'Show numbers' voice access command on the checkbox next to 'Show Caption'. Also, no click command to invoke the checkbox next to 'Show Caption'.

1. Open tinyMCE editor - https://codepen.io/cgk1994/pen/JjaEZWQ
2. Go to Settings->Accessibility->Speech->Voice Access(Preview)->turn on toggle button.
3. Insert a table.
4. Go to Table -> Table Properties -> General 
5. Enable voice access and tell "show numbers".

The checkbox present in the General Tab is actionable item and expected to get tagged with numbers so that physically challenged folks can invoke the checkbox by asking voice access to click the number that's been tagged with checkbox

![show numbers_main issue](https://user-images.githubusercontent.com/126610719/221956341-23ec85fb-8683-45d3-ba56-92a46f5ab8b0.png)

tinyMCE - v6.0
Browser - Google chrome

**Comment by cgk1994** [comment]
@HAFRMO -- Hey, I am not sure whether you will be able to provide any insights about this issue, I am just trying my luck here as its important for our project. Is there any way to fix the above mentioned issue or any workarounds that you can suggest for us?

**Comment by cgk1994** [comment]
Will this issue get resolved if in case we subscribe to premium version?

**Comment by TheSpyder** [comment]
Premium users are entitled to priority support, but that doesn't guarantee priority bug fixes. Those are still evaluated against other work we have scheduled.

Having said that we are looking at some accessibility issues at the moment.

I don't see a `speech` section under chrome accessibility settings. Is there an extension you're using for this?

**Comment by cgk1994** [comment]
Hi,
Thanks for the reply.  We are not using any extension to check the Voice Access instead we are using "Speech" section present under Window's Accessibility menu.(Settings --> Accessibility --> Speech --> "Show Numbers" command). Please keep us posted in regards to the fix of the mentioned issue. Again thanks for the support.
