### ISSUE TITLE
Merge cells

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#851]
* Create a table
* Merge 2 cells
* Cell height is now twice, I must clean the height with backspace.

I think this is a bug?
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6071](http://archive.tinymce.com/develop/bugtracker_view.php?id=6071) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [chrome 4x]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by jhaines** [comment]
Cells will now retain one br when merged.

**Comment by raselcse13** [comment]
> * Create a table
> * Merge 2 cells
> * Cell height is now twice, I must clean the height with backspace.
> 
> I think this is a bug?
> 
> > _**Legacy information imported from TinyMCE bug tracker:**_
> > _[#T6071](http://archive.tinymce.com/develop/bugtracker_view.php?id=6071) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> > _**Tags:** [chrome 4x]_
> > _**Status:** Verified_
> > _**Resolution:** Accepted_
> > _**Attached URL:** none_
