### ISSUE TITLE
Tinymce not working in IE 10.0.6

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#855]
//tinymce.cachefly.net/4.0/tinymce.min.js  WAS working in IE 10
but now both the tinymce.com home site [and my test site pagination.net.au/tinytest.htm no longer work in IE 10.0.6
Both work fine in Chrome and FF.

The tinymce.com.au site homepage [in IE10.0.6] the top demo editing box does not show, and the top menu rollovers [Develop/Forum etc] don't work either

Obviously some setting in IE . .  any clues

Cheers, Stephen Davey
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6075](http://archive.tinymce.com/develop/bugtracker_view.php?id=6075) posted by [smd@pagination.com.au](http://archive.tinymce.com/profile.php?name=smd@pagination.com.au)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.pagination.net.au/tinytest.htm_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
