### ISSUE TITLE
id="submit" stripped from <input> element

### ISSUE THREAD

**Issue by malnoxon** [tinymce/tinymce#8552]
**What is the current behavior? Describe the bug**
If you add an id="submit" element to an <input> form on tinymce v5+ it gets automatically stripped out even when other ids can be specified.

Adding id explicitly with `extended_valid_elements: 'input[id]',` has no affect.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
In the default fiddle editor (eg:
```
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist", "anchor", "autolink", "charmap", "code", "fullscreen", 
        "help", "image", "insertdatetime", "link", "lists", "media", 
        "preview", "searchreplace", "table", "visualblocks", 
    ],
    toolbar: "undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>
```

Edit the source code via Tools > Source Code to be 
```
<p><input id="tarstarst" type="text"></p>
<p><input id="submit" type="text"></p>
```

Save it and open the source code back up again. Notice it's changed to 
```
<p><input id="tarstarst" type="text"></p>
<p><input type="text"></p>
```

**What is the expected behavior?**
The id element does not get silently stripped on save. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This behavior did not exist on tinyMCE v4.6.7 but does on tinyMCE v5.10.7

**Comment by TheSpyder** [comment]
This is a security feature we added in TinyMCE 5.9, aiming to prevent an attack known as "DOM Clobbering" where element names conflict with DOM functions and override them. Any time an `id` or `name` attribute matches a DOM method, we remove it.

DomPurify, which we started using in TinyMCE 6, has links to resources about why this is a problem:
https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model#security-goals
