### ISSUE TITLE
underscored text has underscore line in wrong color

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#856]
Description of problem:

Underscored text has underscore line in wrong color (not the same color as text have)

Steps to reproduce:
1.insert "sdf"
2.click B, I, U buttons
3.insert "dfg"
4.choose red text color
5.insert "hjk"

Expected result:
"hjk" part of "sdfdfghjk" word is red bold italic text with red line under it

Actual result:
"hjk" part of "sdfdfghjk" word is red bold italic text with black line under it

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6076](http://archive.tinymce.com/develop/bugtracker_view.php?id=6076) posted by [apsavin](http://archive.tinymce.com/profile.php?name=apsavin)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
