### ISSUE TITLE
After Integrating The TinyMCE into my asp.net Webform I can't access the TextArea It's Too Small & When I drag it to normal Size I can't Paste Anything In It.

### ISSUE THREAD

**Issue by Pandey9800** [tinymce/tinymce#8562]
Not Showing The TextArea Properly When the TextArea will work Properly I'll try to Paste Tables Containing Images From MS Word.

Here's My Previous Version Of TinyMCE  https://freeimage.host/i/1st.HXshYpS
&
Here's junioryauricasa's Version But It's Not Showing The Text Area As Expected  https://freeimage.host/i/2nd.HXshM4j

I Just Want To Use PowerPaste Plugin So That I can Use it for Pasting Tables Containing Images From MS Word To TinyMCE Editor

I'm Using Chrome Browser & Windows OS. I'm Trying to use PowerPaste Plugin Available into This Version Of TinyMCE.

**Comment by TheSpyder** [comment]
PowerPaste is a premium plugin, we do not offer premium support via GitHub. If you have a support subscription, you will be better served by our support team who will be able to assist: [support.tiny.cloud/hc/en-us/requests/new](https://support.tiny.cloud/hc/en-us/requests/new)
