### ISSUE TITLE
Area in which user can type has reduced with the toolbar mode

### ISSUE THREAD

**Issue by sonikasharma1403** [tinymce/tinymce#8564]
**What is the current behavior? Describe the bug**
Assume, that you have multiple toolbar buttons and have enabled the `toolbar_mode` and a fixed height. Now, when someone expands the toolbar, notice that the area in which the user can type has reduced. Also, imagine that you have a responsive system, and at that time, the expanded toolbars, hide behind.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/z2iaab

**What is the expected behavior?**
height should be for the iframe, rather than for the entire TinyMce.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest TinyMCE

**Comment by TheSpyder** [comment]
The height is specified for the editor container, not the content. We will not break that guarantee other than with the `autoresize` plugin which is documented to do so. Perhaps toolbar mode `floating` would suit you better, rather than `sliding`.
