### ISSUE TITLE
Documentation does not include example or demo of the tree component

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#8570]
**What is the current behavior? Describe the bug**
The documentation does not include any example and/or demo of the tree component.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Go to https://www.tiny.cloud/docs/tinymce/6/changelog/
2. Press <kbd>Ctrl</kbd>+<kbd>K</kbd>.
3. Search for tree component

**What is the expected behavior?**
The documentation should include examples and a demo of the tree component.

**Related**
Tree component PR:
- #8445
- #8553

**Comment by lostkeys** [comment]
Hi @vanillajonathan! Here you can find the documentation on the tree component: https://www.tiny.cloud/docs/tinymce/6/dialog-components/#tree

**Comment by vanillajonathan** [comment]
Thanks, it would be great if there was an **interactive demo** of the tree component too, so you could actually understand what it does.
