### ISSUE TITLE
Text to display in links

### ISSUE THREAD

**Issue by mandreou** [tinymce/tinymce#8575]
If i add a link automatically the "Text to display" is autofilled with the link - correct.
However, i can remove the "Text to display" and then the link it is not showing on tinymce, even if the get Contenct raw type has the link in it.
Also if you have like: two links with no "Text to display" the first link it is disappeared completely and the last one keeps the link but still it is not appearing in text.

is there any way to make "Text to display" text to be mandatory? Forbid the user to have it empty

**Comment by TheSpyder** [comment]
We don't have any support for dialog validation, although it is something we're aware would help a lot of features. It's a much wider topic so I'll close this ticket for now - but know that we are thinking about it.
