### ISSUE TITLE
contextmenu missing "table properties"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#858]
Menu have item "table properties", this is missing in contextmenu. I need it, because I set "menubar:false".

Workaround:

contextmenu: 'link image inserttable | tableprops cell row column deletetable',

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6077](http://archive.tinymce.com/develop/bugtracker_view.php?id=6077) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [chrome 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
