### ISSUE TITLE
Self-Hosted Non-Premium v6 integration RTC error

### ISSUE THREAD

**Issue by mryellow** [tinymce/tinymce#8582]
`Uncaught (in promise) Error: Failed to get RTC instance not yet initialized.`

Seems in the process of attempting to vendor-lock with the CDN based implementations you've broken the library itself.

...

```
import tinymce from 'tinymce';

import 'tinymce/icons/default';

import 'tinymce/themes/silver';
import 'tinymce/models/dom';

import 'tinymce/skins/ui/oxide/skin.css';

import 'tinymce/plugins/advlist';
import 'tinymce/plugins/code'; // FIXME: Not picking up changes made in editor view? NOTE: Works again in v5
import 'tinymce/plugins/emoticons';
import 'tinymce/plugins/emoticons/js/emojis';
import 'tinymce/plugins/link';
import 'tinymce/plugins/lists';
import 'tinymce/plugins/table';

import contentUiSkinCss from 'tinymce/skins/ui/oxide/content.css';
import contentCss from 'tinymce/skins/content/default/content.css';
```

```
tinymce.init({
	selector: `#mg-wysiwyg-${this._uid}`,
	height: parseInt(this.height),
	readonly: this.disabled,
	//min_height: this.height,
	placeholder: this.placeholder,

	resize: 'both',

	menubar: false,
	plugins: ['advlist', 'code', 'emoticons', 'link', 'lists', 'table'],
	toolbar: 'undo redo | bold italic forecolor backcolor | bullist numlist checklist table | link emoticons | code',
	model: 'dom', // FIXME: Forcing "dom" because non-existant RTC "Premium plugin" getting in the way

	// Configuration required for local self-install
	skin: false,
	content_css: false,
	content_style: contentUiSkinCss.toString() + '\n' + contentCss.toString(),

	//promotion: false, // Oh yeah we really want adverts!

	// Bound to "change keyup" events as per https://github.com/tinymce/tinymce-vue/blob/b41c2a47eb8d9629eb01a41d6c6c633651f2d078/src/main/ts/Utils.ts#L115-L119
	init_instance_callback: editor => {
		editor.on('change keyup', e => {
			this.data = editor.getContent({ format: this.syntax })
		})
	},
});
```

**Comment by mryellow** [comment]
Same with: `plugins: ['advlist', 'code', 'emoticons', 'link', 'lists', 'table'],`

**Comment by mryellow** [comment]
```
plugins: [],
toolbar: '',
```

Same again.

**Comment by mryellow** [comment]
This appears to be a cynical attempt to drive people into vendor-locking with your CDN.

Your desire to be paid for working on Open Source has cost me a lot of my time.

Was it the intention to waste my time or did you expect me to just hand over a monthly subscription?

**Comment by mryellow** [comment]
`5.10.7` works as it should and does not include these most recent attempts to break the library.

Those choosing not to vendor-lock themselves into unnecessary pointless parasitic CDN subscriptions can use this version and avoid any future _"upgrades"_.

**Comment by TheSpyder** [comment]
If you're just going to go around our tracker posting about vendor lock-in you're the one wasting our time.

If you would like to continue using v6 - which I recommend as support for v5 [ends in a month](https://www.tiny.cloud/blog/tinymce-end-of-support/) - I'm happy to look at what might be causing this error.

**Comment by TheSpyder** [comment]
The intent of this code is that during the init process TinyMCE checks whether the `rtc` plugin is loading, with the aim of allowing RTC to take over parts of editor functionality. If RTC isn't in the plugin list it redirects everything back to the core.

https://github.com/tinymce/tinymce/blob/ece3bf774b9ae20910d073af5351f162c4fb52d5/modules/tinymce/src/core/main/ts/Rtc.ts#L294-L306

This code was added in TinyMCE 5.3 so the source of the exception isn't recent, there's probably just some code trying to use one of those core features during setup instead of waiting for the `PreInit` event.

I am open to collaborating if you'd like to help track down this mistake.

**Comment by mryellow** [comment]
> I am open to collaborating

* The bug is caused by efforts to lock certain features and wouldn't exist otherwise
* The ticket is closed as if the reported bug does not exist as only the commercial version matters
* Given this is a commercial product only one of us is incentivised to contribute
* v5 will work fine for decades to come
* Have other fish to fry, wasted enough time on what should have been a simple install

**Comment by TheSpyder** [comment]
If you're just going to twist my words don't bother replying. This isn't an airport, you don't need to announce your departure.
