### ISSUE TITLE
v6 docs have no search function

### ISSUE THREAD

**Issue by mryellow** [tinymce/tinymce#8583]
Documentation for v6 lacks a search function either in the API docs or the guides.

Seems this may be dependant on `jsdelivr` and displays nothing until it is permitted to load.

**Comment by TheSpyder** [comment]
We use Algolia docsearch for our search box, and jsdelivr to include the scripts rather than rehost them ourselves. It's a commonly used search tool so linking to a public CDN means it's more likely to be cached and speed up the first visit to our docs.
```
    <!-- Algolia docsearch styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" />

    <!-- Algolia docsearch script -->
    <script src="https://cdn.jsdelivr.net/npm/@docsearch/js@3"></script>
```
