### ISSUE TITLE
Incomplete translations and unable to add translations

### ISSUE THREAD

**Issue by sonikasharma1403** [tinymce/tinymce#8584]
**What is the current behavior? Describe the bug**
Looks like apart from English and a couple of more, other languages are completely translated

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
- 

**What is the expected behavior?**
Should have translations. 
Even the [crowdwin](https://crowdin.com/project/tinymce/hi) websites seems to no longer recognize the project 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest tinymce

**Comment by sonikasharma1403** [comment]
Any update on this?

**Comment by TheSpyder** [comment]
We had a problem with the payment system and our account had become suspended. This is now resolved, thank you for the report.
