### ISSUE TITLE
focusout is not working properly in inline mode

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#859]
Description of problem:
it can be reproduced in this site.

Steps to reproduce:
1. inline editor click(then focused)
2. then, show up floatpanel. click toolbar's "Tools"'s right side(empty space)
3. and, click other area.(except editor area)
4. you can see it focusout not working.
5.

Expected result:
editor is focusout, floatpanel closed.

Actual result:
editor has not caret, floatpanel is opened.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6079](http://archive.tinymce.com/develop/bugtracker_view.php?id=6079) posted by [AndrewAhn](http://archive.tinymce.com/profile.php?name=AndrewAhn)_
> 
> _**Tags:** [msie chrome msie10 chrome13]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://www.tinymce.com/tryit/inline.php_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
