### ISSUE TITLE
TtinyMCE 6 doesn't display base64 inline image when html loaded into the editor

### ISSUE THREAD

**Issue by lrossict** [tinymce/tinymce#8590]
HTML text prepared with an inline image and sent with "setContent" to the editor window.

All the HTML gets displayed, except for the image, a blank space is left.

The Html code is set correctly and image is correctly visualized if the same HTML is uploaded in any other HTML viewer (including the VS debugger view).
Albeit useless, as the editor window is used only a reader, the image plugin has been added in the initialization routine.

Same issue mentioned and never solved at https://github.com/tinymce/tinymce/issues/2105

**Comment by lorenzo-pomili** [comment]
it seems to work in this case: https://fiddle.tiny.cloud/c7iaab
could you provide a replication case to reproduce the bug?

**Comment by maverickchangithub** [comment]
Same.

When you first insert a base64 image , it shows fine.
But, if you retrieve the image from a database and want to edit it in the editor, its tag has been escaped and shows a broken image.

**Comment by maverickchangithub** [comment]
turn of automatic uploads
```automatic_uploads: false,```
