### ISSUE TITLE
paste_remove_styles_if_webkit

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#860]
Description of problem:

paste_remove_styles_if_webkit setting is undefined by default. It should have value. According to http://www.tinymce.com/develop/bugtracker_view.php?id=4924 it should be false by default.

The problem: when you pase from MS Office, or other webpage with text-align style attribute, TinyMCE doesn't retain paragraph alignment. Even if you say TinyMCE to retain paragraph align style properties with

paste_retain_style_properties: 'text-align'

They are dropped because paste_remove_styles_if_webkit should be exactly false to retain style.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6232](http://archive.tinymce.com/develop/bugtracker_view.php?id=6232) posted by [kerby](http://archive.tinymce.com/profile.php?name=kerby)_

> _**Tags:** [firefox msie safari chrome opera paste_remove_styles_if_webkit paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
