### ISSUE TITLE
set link is current window,and set target is _self ,but open new window

### ISSUE THREAD

**Issue by wmshero** [tinymce/tinymce#8607]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

clink here to check
[fiddle](https://fiddle.tiny.cloud/F3iaab)

**What is the expected behavior?**
click link when target is _self, open link at current window.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
        "tinymce": "^6.3.2",
       "@tinymce/tinymce-react": "^4.3.0",

**Comment by TheSpyder** [comment]
We implement link clicking within the editor ourselves, and always open a new window to avoid losing the editor session.

https://github.com/tinymce/tinymce/blob/ece3bf774b9ae20910d073af5351f162c4fb52d5/modules/tinymce/src/core/main/ts/mode/Readonly.ts#L148
