### ISSUE TITLE
properties body_class and content_css in the preview of a template

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#861]
In the template window of the template plugin, 

you can't preview your template with the class defined in the property body_class of the tinymce configuration.

you can't preview your template with the stylesheet defined in the property content_css of the tinymce configuration.

thank you !!

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6081](http://archive.tinymce.com/develop/bugtracker_view.php?id=6081) posted by [lhapaipai](http://archive.tinymce.com/profile.php?name=lhapaipai)_
> 
> _**Tags:** [plugin template body_class content_css]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
