### ISSUE TITLE
Global variable collides against other instances of tinymce

### ISSUE THREAD

**Issue by bennbollay** [tinymce/tinymce#8613]
**What is the current behavior? Describe the bug**

Currently, tinymce uses a hardcoded global attached to the `window` object as a single entrypoint for code from several locations, primarily Silver/Icons.tsx (where it's used to register icons), and many calls to Obj.get() to acquire objects under the `tinymce` global itself.

This conflicts with supporting multiple versions of tinymce in the same JavaScript environment and impacts configuration and init parameter isolation between different usage.

**What is the expected behavior?**

Provide an entrypoint or a registrant that is either configurable, to allow for specifying the global name in a coherent fashion during load, or self-contained, such that dependent artifacts are referenced internally rather than falling back to the global.

There are only 167 instances of tinymce.util.Tools.resolve, which is the primary usage of this global, and a vast majority of them are self-references, resolvable by wrapping the object and invoking it within a configuration space, rather than relying on the global namespace.

**Comment by TheSpyder** [comment]
Adjusting the window object isn't as simple as migrating all global references to self-references. TinyMCE is compiled into a number of files and plugins to reduce the size of the initial script load, so most (if not all) of those those 167 references you see are in separate script files:
https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.4.1/plugins/autosave/plugin.js

We don't support loading multiple versions of TinyMCE in the same page. The window object is certainly a big reason for this, but the skin CSS is another major issue that will come up. We regularly make changes to the skin that will not render correctly except on the version the skin shipped with.

We built an entire library to help us write tests that run on multiple versions of TinyMCE, by unloading all relevant resources before attempting to load a different version.
https://github.com/tinymce/miniature/blob/457c30328497fbe78119bffc9712b854cee56640/src/main/ts/loader/Loader.ts
