### ISSUE TITLE
Powerpaste plugin and version 6.0 results in content paste duplication

### ISSUE THREAD

**Issue by neilBitflux** [tinymce/tinymce#8622]
**What is the current behavior? Describe the bug**

Just upgraded from 5 to 6. I am told that the paste is now a core feature. Prior to 6 was a plugin that could be disabled by not adding it to the list of plugins. Now as its a core feature is enabled by deafault. If you install the powerpaste plugin this results in both plugins being enabled and causing the content to be pasted twice.

Remove powerpaste from the list of plugins and it pastes once.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
I am using this in combination with @tinymce-angular 7.0. 
add the powerpaste plugin to tinymce version 6 and use it with @tinymce-angular 7.0.

**What is the expected behavior?**
Content should be pasted once when powerpaste plugin is being used. So we need a way of disabling paste core when in 6.0.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
chrome.
tinymce 6
tinymce-angular 7
this worked fine with tinymce 5 (I assuming because with 5 it was a plugin and not added to the list  so was disabled automaticaly) resulting in 1 pasted when powerPaste plugin was in the list.

**Comment by neilBitflux** [comment]
Didn’t realise you needed to upgrade the plugins separately so Haven’t upgraded the plug-in itself from 5 to 6. When I upgraded tinymce
Does that need doing?
Thanks

Sent from my iPhone

On 11 Apr 2023, at 07:54, Andrew Herron ***@***.***> wrote:

﻿

Something else is going on here. Powerpaste has always been supported on 6.x and doesn't paste twice. We use it in our own demos all the time:
https://www.tiny.cloud/docs/tinymce/6/full-featured-premium-demo/

I wonder if you still have the TinyMCE 5 paste plugin running? That's a scenario we didn't consider.

**Comment by TheSpyder** [comment]
The plugins are bundled with the editor, but if all you did was overwrite the existing `tinymce` folder on your server it may have left v5 plugins behind that we deleted in 6. We didn't ship stub plugins to overwrite things that are no longer needed.

If your configuration then still includes the v5 `paste` plugin it _might_ lead to this situation. Either way, removing `paste` from your config (since it's built-in now) and leaving just `powerpaste` should definitely fix it.

**Comment by neilBitflux** [comment]
I’m using powerpaste plugin 5.6.2-4
In the plug-ins folder. Could this be an old version that didn’t get updated when moving from tinymce 5>6?

Is there a newer version that I can download and install here?

If so where could I get this from.

Sent from my iPhone

On 13 Apr 2023, at 07:51, Andrew Herron ***@***.***> wrote:

﻿

The plugins are bundled with the editor, but if all you did was overwrite the existing tinymce folder on your server it may have left v5 plugins behind that we deleted in 6. We didn't ship stub plugins to overwrite things that are no longer needed.

If your configuration then still includes the v5 paste plugin it might lead to this situation. Either way, removing paste from your config (since it's built-in now) and leaving just powerpaste should definitely fix it.
