### ISSUE TITLE
When newline behavior is changed to <br> in TinyMCE 6, alignment plugin is not working properly

### ISSUE THREAD

**Issue by sha2nktiwade** [tinymce/tinymce#8625]
**What is the current behavior? Describe the bug**

In TinyMCE 6, when the newline behavior is changed from p to br, the alignment plugin is giving incorrect result as the alignment style is applied to the outer p tag rather the individual brs where alignment option was applied.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Change the newline behavior is TinyMCE 6 with this line in config: newline_behavior: 'invert'.
2. Write multiple line text in the editor.
3. When togging and viewing the source code, it looks like below:
    <p>Text1<br>Text2<br>Text3<br>Text4</p>
4. Now try to the alignment of the only the second or third line in the editor.
5. The source code now looks like below:
    <p style="text-align: center;">Text1<br>Text2<br>Text3<br>Text4</p>
6. We can see that the alignment of all the lines are changed even when we wanted to change the alignment of a single line. This happened because even when the newline behavior is changed to <br>, still we are getting one outer <p> tag and all the content is wrapped in that tag.

Expected Result: Only the specific line should have changed the alignment. All the content should be separated by <br> and there should not be any <p> tag here.

Actual result: The alignment option is not working properly in version 6 of TinyMCE.

**What is the expected behavior?**
Expected Result: Only the specific line should have changed the alignment. All the content should be separated by <br> and there should not be any <p> tag here.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
We are using latest version TinyMCE 6. This is reproducable in any browser and is not browser specific. In earlier version of TinyMCE, it was not wraping the content in <p> and hence even after changing the newline behavior it was working properly.

**Comment by sha2nktiwade** [comment]
Initial Source mode:
![image](https://user-images.githubusercontent.com/130130998/230558516-64fd6a55-1a61-4e02-a0fc-6e1256405840.png)

Source mode after changing the alignment:
![image](https://user-images.githubusercontent.com/130130998/230558695-202cf546-cce7-42a7-aff9-54c0479e86d4.png)

**Comment by TheSpyder** [comment]
This was an unfortunate loss with the removal of `forced_root_block: false` in TinyMCE 6. Block operations now only apply to block elements.

I will have a chat to our PM and see if we might consider bringing this back before I close the issue.

**Comment by sha2nktiwade** [comment]
@TheSpyder - Could you please share if there are any updates on this issue.

**Comment by TheSpyder** [comment]
Apologies, I’ve had a lot going on and by the time the conversation ended I forgot it had started here.

The answer is no. There isn’t enough demand to consider bringing back even this small piece of the `false` code. Sorry to disappoint you.
