### ISSUE TITLE
Dragging and dropping an image onto the header menu or status bar will result in an "Dropped file type is not supported" message.

### ISSUE THREAD

**Issue by chaploud** [tinymce/tinymce#8636]
**What is the current behavior? Describe the bug**

Dragging and dropping an image onto the header menu or status bar will result in an "Dropped file type is not supported" message.

![image](https://user-images.githubusercontent.com/19206115/231106826-26e90c7b-7201-4157-ae25-4b220dc40062.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Access "https://www.tiny.cloud/docs/demo/full-featured/."
2. Drag and drop any image onto the TinyMCE's header menu or status bar.
3. "Dropped file type is not supported" message popups.

**What is the expected behavior?**

"Dropped file type is not supported" message does not popup.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- TinyMCE Version >= 6
- WIndows 11
- Google Chrome 111.0.5563.147

**Comment by gvodandan** [comment]
I'm having the same issue 😞

**Comment by gvodandan** [comment]
https://www.tiny.cloud/docs/tinymce/6/
TinyMCE6 has solved this problem
