### ISSUE TITLE
NO mouse over icon in editor mode

### ISSUE THREAD

**Issue by kowaleji** [tinymce/tinymce#8639]
I would really like to know if there is ANY SOLUTION to this problem.

Explanation:
When the cursor is brought over link carrying image or text -- a hand pointer usually comes up.

However in the MCE-edit mode, this pointer is missing, SO one  doesn't know if the link actually exists or NOT.
Only cotrol-click results in the linked page coming up.

So this is not great when you really understand your  WYSIWYG. :(

Ergo -- A BIG THUMBS DOWN for TinyMCE.

Sorry guys, this is something not acceptable to an old timer with 30+ years IT. I keep finding great big flaws in the (sic!) might MSO at regular intervals and manage to crash the program quite regularly.

ADIOS
vicky
+9 9820037787

**Comment by kowaleji** [comment]
vicky +91 9820037787

**Comment by TheSpyder** [comment]
Links in an editor are there to be edited, not viewed. You can ctrl+click (or cmd+click on mac) to specifically view the link, but CSS doesn't let us change the mouse cursor based on holding down a modifier key. We can only ever display the edit cursor.
