### ISSUE TITLE
Keydown event triggered after text changed.

### ISSUE THREAD

**Issue by higty** [tinymce/tinymce#8640]
**What is the current behavior? Describe the bug**
Keydown event fired after text modified.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Reproduct code
https://fiddle.tiny.cloud/L4iaab

Input text to textbox "mytext1"
Move carret between y and t.
Press enter.

```
<p>my</p><p>text1</p>
```
shown as alert.

**What is the expected behavior?**
alert text must be 
```
<p>mytext1</p>`
```

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest chrome version on PC and latest TinyMCE version.

I just want to get 
```
<p>mytext1</p>
```
. So, any workaround is appriciated.

regards.

**Comment by TheSpyder** [comment]
That's because `init_instance_callback` runs after the editor is ready for use - meaning our internal `keydown` handlers are already registered. Handlers are executed in registration order.

If you want to inject your handler before ours, use `setup`:
https://fiddle.tiny.cloud/L4iaab/2

**Comment by higty** [comment]
@TheSpyder 
That works great! Thank you!
