### ISSUE TITLE
Getting a type error during editor init in some cases.

### ISSUE THREAD

**Issue by liesahead** [tinymce/tinymce#8645]
**What is the current behavior? Describe the bug**
Getting such error: `TypeError: Cannot read properties of null (reading 'nodeName')`

![image](https://user-images.githubusercontent.com/32300784/231742964-ca0970e9-36cf-46a0-a057-2bb4b159a37e.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Extremely difficult to reproduce and reason why it happens is not clear. Maybe someone has an idea? Also, maybe the code in the screenshot should be replaced with `editor.getElement()?.nodeName.toLowerCase()`?

**What is the expected behavior?**
No error during editor init.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Never happened previously in `v6.3.1` only after we upgraded to `v6.4.1`.

Angular CLI: 15.2.5
Node: 18.14.0
Package Manager: yarn 3.3.0
OS: win32 x64

Angular: 15.2.6

Package                                     Version
------------------------------------------------------------
@tinymce/tinymce-angular      v7.0.0
tinymce                                     v6.4.1

**Comment by TheSpyder** [comment]
If `editor.getElement()` is returning null there are bigger problems than just that method. Unfortunately without a replication case it's very difficult to know why that might happen; from your description it's probably a race condition.

Do you have a full stack trace of the error?

**Comment by liesahead** [comment]
@TheSpyder , we have reverted to the previous version, but I have a screenshot saved, hope it will help.

![image](https://user-images.githubusercontent.com/32300784/233993811-6cbe8899-96d6-42e2-a348-80bbae0040af.png)

**Comment by TheSpyder** [comment]
Are you removing the editor during the init process? That's one way this might come up. We try to check for that happening in a few places, but that's much earlier in the process than I've seen before.

Removing the target element TinyMCE is replacing could also do this. We made the init process async in 6.4, so code that removes the target element after calling `init()` may have worked in the past and no longer does.
