### ISSUE TITLE
Tinymce 4 tooltip popup responsive issue

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#865]
Description of problem:
The tooltip popup when I click on inser image or video, is not actually responsive. That is why having issue to view on mobile devices. Please fix it asap or let me know how to fix it.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6085](http://archive.tinymce.com/develop/bugtracker_view.php?id=6085) posted by [isaumya](http://archive.tinymce.com/profile.php?name=isaumya)_

> _**Tags:** [firefox msie safari chrome opera tooltip popup responsive v401]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
