### ISSUE TITLE
valid_elements and extended_valid_elements do not work with iframe

### ISSUE THREAD

**Issue by kratosvn** [tinymce/tinymce#8655]
**What is the current behavior? Describe the bug**
Hi guys,
I want to add `onload` attribute to `iframe` with config 
```
valid_elements: '*[*]',
extended_valid_elements:'@[onload]',
valid_children: "+iframe[onload]",
```
But tinymce filter my attribute, what is my config wrong?

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**
keep attribute `onload` for iframe

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
version: `tinymce@^5.0.0`

**Comment by spocke** [comment]
Can't seem to reproduce that here: https://fiddle.tiny.cloud/c8iaab

In general having events like `onload` enabled is generally something we prohibit by default to avoid XSS since these event handlers can include malicious code.

So need more info here on how to reproduce this.

**Comment by kratosvn** [comment]
thank @spocke
