### ISSUE TITLE
TinyMCE Version 6.4.1 | Bullet List Issue - Not working properly

### ISSUE THREAD

**Issue by dixitrohit17** [tinymce/tinymce#8658]
**Migration - TinyMCE Version 4.9.2 to 6.4.1 | Bullet List is not working**

TinyMCE editor is used in MVC 5 Application, bullet list is not applying bullets while applying numbering on multiple line selected simultaneously.  If bullet list apply one by one in line then it work however applying listing on multiple line parallelly, bullet came in only one line rest lines shift down with one extra line.

**Is there any way to correct numbering.**

**Note:** Other lists are also working as motioned above.

**TinyMCE Version -** 6.4.1, 
 **Browser -** Google chrome and MS Edge 
in earlier version bullet list was working fine.

**Comment by dixitrohit17** [comment]
Hello Everyone,
Is there any resolution on this.

**Comment by TheSpyder** [comment]
We need more information about the problem, applying bullets to multiple numbered list items should work (in fact it should apply to them all at the same time regardless of selection).

As the issue template suggested, a replication case on https://fiddle.tiny.cloud/ is ideal and a video might help too.

**Comment by TheSpyder** [comment]
ah, yeah our list code has changed a lot since v4 and isn't picking up that it should apply a single list across multiple div tags. You can see this by trying to apply a list to 2 and 3, it becomes 3 lists.
