### ISSUE TITLE
MCE4: Paste as text retains linebreaks of HTML source

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#866]
Description of problem:

If you switch to Paste As Text mode and paste in some selected text from a HTML document in another tab/window, then formatting is stripped, however if the underlying HTML source in the document was using linebreaks (ie. \n, not &ltg;br>) for source code formatting then these are also pasted in. This leads to an end result of:

So this is me pasting
in some text into 
this document.

...instead of:

So this is me pasting in some text into this document.

I have a sort-of workaround for it by using the DOM - see the attached paste plugin.js - changes are from line 123 to line 138. However this now wrecks linebreaks for plaintext stuff that has been pasted in from Notepad.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6086](http://archive.tinymce.com/develop/bugtracker_view.php?id=6086) posted by [lid2000](http://archive.tinymce.com/profile.php?name=lid2000)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
