### ISSUE TITLE
Use power paste to paste pictures and texts in word, but the pictures are invalid

### ISSUE THREAD

**Issue by LY-Net** [tinymce/tinymce#8660]
**What is the current behavior? Describe the bug**

Use power paste to paste a small amount of text and pictures in word, but a little more text and pictures (including three pictures or more and text) will fail

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Create a new word document with pictures and text, select all + paste, copy to my tinymce project

**What is the expected behavior?**

 keep the picture displayed normally

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
6.1.14

**Comment by LY-Net** [comment]
Can someone fix the problem with the paid component?

**Comment by TheSpyder** [comment]
PowerPaste is a premium plugin, we do not offer premium support via GitHub. If you have a support subscription, you will be better served by our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new

**Comment by pengyanxue** [comment]
请问你解决了没？word中的图文一起复制时候 图片就不支持
