### ISSUE TITLE
Script error is coming while pressing Enter key after clicking on 'Horizontal Rule'button

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#867]
Description of problem:

Steps to reproduce:
1. In IE10 start blank TinyMCE editor, having an option to insert an horizontal rule in the toolbar.
2. Press Horizontal Rule toolbar button. 
3. A horizontal line will be added to the editor. However note that the cursor is not going to the next line.
4. Press enter key now.
5.

Expected result:
Cursor should to to next line.

Actual result:
Script error is coming: Unable to get property 'firstChild' of undefined or null reference 
=e,n=[],r;t=t.firstChild;){if(i.isBlock(t))return;1!

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6087](http://archive.tinymce.com/develop/bugtracker_view.php?id=6087) posted by [abaan](http://archive.tinymce.com/profile.php?name=abaan)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
