### ISSUE TITLE
format_noneditable_selector does not support block like elements, such as div or p,where did I make a mistake?

### ISSUE THREAD

**Issue by lydat** [tinymce/tinymce#8674]
![image](https://user-images.githubusercontent.com/36094163/233643856-d50d2d1e-d652-47b8-b74c-4569281b0141.png)
format_noneditable_selector does not support block like elements, such as div or p,But the document supports p tags

![image](https://user-images.githubusercontent.com/36094163/233644062-03532875-9096-4d75-965d-48f80d26a6fc.png)

**Comment by vpyshnenko** [comment]
Thank you for bringing this issue to our attention. While the behavior you described is expected, we understand that it may not have been clear in our documentation.
To clarify, TinyMCE does not typically allow you to apply inline formatting, such as bold or italic, to block tags. Instead, any inline formatting will be applied to the content inside the block tag. However, if the block tag is non-editable, you cannot modify its content, and applying inline formatting becomes impossible.
On the other hand, you can apply wrappable block formats, like the block-quote format, to non-editable block elements. According to our documentation: "Wrappable formats include block formats that have the `wrapper` parameter set to `true` and inline formats".
Alternatively, you can create new custom formats to meet your specific needs. For example, look at this [Fiddle](https://fiddle.tiny.cloud/K7iaab) demonstrating the custom bold block format.

**Comment by jarangutan** [comment]
As I understand it, if I set `format_noneditable_selector: 'p.special, span, span.special'`, then I can expect `<span contenteditable="false">hello world</span>` to be styled with the toolbar.

However, `<p class="special" contenteditable="false">hello world</p>`  will not work which goes against what the documentation is saying but agrees with your statement that you cannot modify a non-editable blocks contents.

As you stated, one can create a wrapper block that attaches styles to a non-editable block. That ends up looking like so from the output of the fiddle: 

```
<div style="font-weight: bold;">
<p class="special" contenteditable="false" data-mce-cef-wrappable="">No-editable 2</p>
</div>
```

This does apply bold, and if you select the non-editable block then you can also set the line height which ends up looking like:

```
<div style="font-weight: bold; line-height: 1.5;">
<p class="special" contenteditable="false" data-mce-cef-wrappable="">No-editable 2</p>
</div>
```

What you cannot do is select the non-editable block and change the font size which is arguably more important than line height or bold. But, you could manually add `font-size` to the div through the code plugin which will apply the font to everything the div wraps. That option is not a good user experience.

```
<div style="font-weight: bold; line-height: 1.5; font-size: 12pt;">
<p class="special" contenteditable="false" data-mce-cef-wrappable="">No-editable 2</p>
</div>
```

The actual behavior of this option doesn't reflect what folks are expecting and is pretty inconsistent. I think that's what folks want addressed when it comes to these questions as I came to ask the same thing.

---

There's a fun problem you can run into as well with this feature. If you had a noneditable `<div>` wrapping a `<p><span contenteditable="false" data-mce-cef-wrappable>` then you can change the font of the spans in the block but it'll just keep adding more wrapping spans with the font changes. 

So, if you had this:

```
<p>you need text before and after the div to be able select all</p>
<div contenteditable="false">
<p><span contenteditable="false" data-mce-cef-wrappable="true">hello world</span></p>
</div>
<p>and get the noneditable div content. If the div was the only element, then you would not be able to click on it or even select it</p>
```

And proceeded to select all and change the font a few times, then you'll end up with:

```
<p>you need text before and after the div to be able select all</p>
<div contenteditable="false">
<p><span="font-size: 36pt;"><span="font-size: 24pt;"><span="font-size: 8pt;"><span="font-size: 16pt;"><span contenteditable="false" data-mce-cef-wrappable="true">hello world</span></span></span></span></span></p>
</div>
<p>and get the noneditable div content. If the div was the only element, then you would not be able to click on it or even select it</p>
```

Normally, you'll only get 1 wrapping span that is updated, but in this case, you can get multiple.
