### ISSUE TITLE
Inserting child with valid_children in table not working

### ISSUE THREAD

**Issue by timlehmkuhl** [tinymce/tinymce#8675]
Hi, we use TinyMCE in combination with JMustache. Users can insert Mustache variables into the text from TinyMCE to create a template. 
We now have a problem with loops in combination with tables. The loop must start before a `<tr>`  and stop after the `</tr>` so that one iteration equals one row. TinyMCE uses tbody in addition. So the HTML would have to look like this:

```html
<table style="border-collapse: collapse; width: 100%; height: 32px;" border="1">
    <colgroup>
        <col style="width: 24.9891%;">
        <col style="width: 24.9891%;">
    </colgroup>
    <tbody>
    <tr style="height: 16px;">
        <td style="height: 16px;">Name</td>
        <td style="height: 16px;">Birthday</td>
    </tr>
    <p>{{#PERSONS}}</p>
    <tr style="height: 16px;">
        <td style="height: 16px;">
            <p><br>{{NAME}}</p>
        </td>
        <td style="height: 16px;">
            <p>{{BIRTHDAY}}</p>
        </td>
    </tr>
    <p>{{/PERSONS}}</p>
    </tbody>
</table>
```

If we put this in TinyMCE, the variable will detect invalid HTML and the loop start/end will be moved out of tbody. 
According to the documentation, the solution to our problem would be to use `valid_childen`. We enclosed the variables in a `<p>` tag and added `valid_children: "+tbody[p]"` to the TinyMCE configuration.
Unfortunately it does nothing and the paragraph is moved away again.

Here is an example for our TinyMCE configuration:

```javascript
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist", "anchor", "autolink", "charmap", "code", "fullscreen", 
        "help", "image", "insertdatetime", "link", "lists", "media", 
        "preview", "searchreplace", "table", "visualblocks", 
    ],
    toolbar: "undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
	valid_children: "+tbody[p]"
});
</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>
```
I have created an example here where you can try it out: [https://fiddle.tiny.cloud/T5iaab](https://fiddle.tiny.cloud/T5iaab)
The HTML code from above can be inserted via Tools -> Source code.

Also tried `valid_children: "*[*]"` but same problem. 

Have tried it with TinyMCE 6 and 5.

**Comment by kratosvn** [comment]
it same issue here: https://github.com/tinymce/tinymce/issues/8655

**Comment by spocke** [comment]
TinyMCE is a HTML based editor so it follows the HTML standards and parse and render the content using the browsers DOM APIs. Having P tags at those positions in a table is not semantically correct HTML so the browser will normalize the table and move those elements out. You can see that if you just invoke the browsers parser using this code:
```
console.log(new DOMParser().parseFromString(`
<table style="border-collapse: collapse; width: 100%; height: 32px;" border="1">
    <colgroup>
        <col style="width: 24.9891%;">
        <col style="width: 24.9891%;">
    </colgroup>
    <tbody>
    <tr style="height: 16px;">
        <td style="height: 16px;">Name</td>
        <td style="height: 16px;">Birthday</td>
    </tr>
    <p>{{#PERSONS}}</p>
    <tr style="height: 16px;">
        <td style="height: 16px;">
            <p><br>{{NAME}}</p>
        </td>
        <td style="height: 16px;">
            <p>{{BIRTHDAY}}</p>
        </td>
    </tr>
    <p>{{/PERSONS}}</p>
    </tbody>
</table>`,
'text/html'
).body.innerHTML)
```

So there is not much we can do on our side of this. So I'm closing this issue since it's not really a bug but rather how browsers and TinyMCE operates.
