### ISSUE TITLE
Autoresize IE8 IE9 shifts cursor one line down from first line on init

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#868]
Description of problem:

Steps to reproduce:
1.On IE auto-resize plug-in enabled same as of full example http://www.tinymce.com/tryit/3_x/full.php
2. When cursor is at very start of editor and start typing cursor moves a bit down on IE. 
3. To Reproduce just delete all of content in this full example and press backspace at start so that cursor is at very start. Now type any character it moves down a bit.  
4.This movement do not occur if auto-resize is disabled. 
5.

Expected result: Cursor and text typed should not move

Actual result: typed letter moved bit down first time. 

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6088](http://archive.tinymce.com/develop/bugtracker_view.php?id=6088) posted by [chetan.padhye](http://archive.tinymce.com/profile.php?name=chetan.padhye)_

> _**Tags:** [msie msie8 msie9]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
