### ISSUE TITLE
Srcset not used correctly in Tiny 6

### ISSUE THREAD

**Issue by davobutt** [tinymce/tinymce#8688]
With saved documents with images (dropped in to a tiny 5 editor) that look like this
`<img class="WACImage SCXW8307006 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; border: none; vertical-align: baseline; font-family: 'Segoe UI', 'Segoe UI Web', Arial, Verdana, sans-serif; font-size: 12px; background-color: #ffffff; width: auto; height: auto; white-space: pre !important;" src="blob:https://<<private url>>" srcset="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB0AAAAhCAYAAAAlK6DZAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAHYcAAB2HAY/l8WUAAABZSURBVFhH7c0xCsBADAPB+/+nk7BInUv50mhAhXGx5/NcHqbH5sCxyQ0Njca4oaHRGDc0NBrjhoZGY9zQ0GiMGxoajXFDQ6Mxbmj4L3pxmB6bw/TYXFXCOS/E/DpFZwOehwAAAABJRU5ErkJggg== 2x" alt="Shape" />`

Do not load correctly in Tiny 6
The editor complains about the blob url being invalid. In a browser the `srcset` is used ahead of the src fallback.

Replicate by shoving that HTML in to the document.

**Comment by spocke** [comment]
Just want to double check that we get this one right. From what I can see the `srcset` attribute is stripped out when a data uri is being used inside it. I made a simpler replication case here: https://fiddle.tiny.cloud/r9iaab/1 could you verify that this is what we are talking about here if you open the source code editor you notice that the `srcset` attribute is removed from the first image.
The error notification message was removed in 6.4.2 so no longer the case if that is what you are referring to?
