### ISSUE TITLE
Script error is coming for Textcolor and BGcolor buttons

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#869]
Description of problem:

Steps to reproduce:
1. In IE10 open empty tinymce editor having TextColor and Backgroundcolor in toolbar. (On tinymce.com try it the classcial example)
2. Be sure editor content is empty.
3. Select TextColor from the toolbar and select a color
4. Blur the editor by clicking outside the editor
5. Click on the TextColor toolbar button again.

Expected result:
Color popup should be visible again.

Actual result:
Script error: 
Unable to get property 'nodeType' of undefined or null reference
t,y=t.endContainer,b=t.endOffset;if(1==g.nodeType&&g.hasChildNodes()&&(p=g.c
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6089](http://archive.tinymce.com/develop/bugtracker_view.php?id=6089) posted by [abaan](http://archive.tinymce.com/profile.php?name=abaan)_

> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by starquake** [comment]
I just had this error in ie11. I am however unable to reproduce this right now. I'll do some more testing.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
