### ISSUE TITLE
Closing `source code` dialog throws errors in console.

### ISSUE THREAD

**Issue by liesahead** [tinymce/tinymce#8691]
**What is the current behavior? Describe the bug**
![image](https://user-images.githubusercontent.com/32300784/235088587-84fe6445-032b-402c-8027-e7dfce4be0f9.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Open https://www.tiny.cloud/docs/tinymce/6/full-featured-premium-demo/;
2. Open `Source code` dialog;
3. Close it (by `Esc` or `Cancel` button);

**What is the expected behavior?**
No errors in console.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest?

**Comment by TheSpyder** [comment]
I can't reproduce this, and the demo you linked to uses our premium source code dialog. Are you having issues with our premium code dialog or the open source one?

**Comment by liesahead** [comment]
@TheSpyder , lots of errors even in demo as you see in the video. We use open-source version, but the result is the same - same errors.

https://user-images.githubusercontent.com/32300784/235592216-5865dcb1-04eb-4253-ae99-9508a3704c3a.mp4

**Comment by TheSpyder** [comment]
@liesahead That looks like chrome dev tools, but what exact browser and plugins are you using? The dialog does not cause errors for us.

Looking at the stack trace it's all coming from a `content.js` file. We don't have any files by that name on that page, but this is a common name used by chrome extensions. I suggest it's a chrome extension that is throwing the exception.

If you can track down which extension is doing this I suggest contacting them about it, although we may also be able to help track down why TinyMCE is causing the error.

**Comment by liesahead** [comment]
@TheSpyder , thanks for the great reaction. My bad, haven't checked the source of the error and indeed it's an extension. This one.

![image](https://user-images.githubusercontent.com/32300784/235599721-a82252ba-86ef-4bf0-b8e5-2702f596cd47.png)

**Comment by TheSpyder** [comment]
Good to know, thank you!
