### ISSUE TITLE
Problem with parsing lists with items which contains float numbers.

### ISSUE THREAD

**Issue by IgorIzviekov12** [tinymce/tinymce#8695]
TinyMCE parse lists incorrectly when you paste a data from MS Word with items which contains float numbers.

Version of TinyMCE: 5.10.7
Plugins: `["lists", "code", "preview", "fullscreen", "hr", "link", "table", "paste"]`

Initial data
![photo_2023-05-03_10-56-00](https://user-images.githubusercontent.com/117081990/235860769-67d50828-4f85-4c3f-978e-694723eb6465.jpg)

Result
![photo_2023-05-03_10-55-54](https://user-images.githubusercontent.com/117081990/235860665-97dc1a0d-7137-4dc5-97ec-e7bec9a41be1.jpg)

Expected result
![photo_2023-05-03_10-58-31](https://user-images.githubusercontent.com/117081990/235861056-dac25a64-6daa-41d5-963d-a8b89705b2be.jpg)

**Comment by TheSpyder** [comment]
We have closed maintenance on the open source MS Word import from TinyMCE 5. There is an open request for maintainers:
https://github.com/tinymce/tinymce/discussions/7487
