### ISSUE TITLE
How to get image dimensions from textarea in upload handler

### ISSUE THREAD

**Issue by saintroma** [tinymce/tinymce#8718]
It is necessary to get the user-defined dimensions of the image to reduce according to the specified dimensions. The image has an id and displays 0 when using getSize() and getAttribs()

**Comment by spocke** [comment]
You will need to load the image then get the size. Like:

```
const img = new Image();
img.src = 'something';
img.onload = () => {
  console.log(img.naturalWidth, img.naturalHeight);
};
```

Closing this since it's not a bug or feature request more of a general question on how to get the image dimensions in the upload handler.
