### ISSUE TITLE
Copy / Paste / Wordwrap failure

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#872]
Description of problem:

Steps to reproduce:
1. Add "p, pre, pre[wrap] {white-space:normal}" to custom_content.css 
2. Type "a a a a" in editor
3. View source code and verify there are no &nbsp; then close code window
4. Copy all but first a, that would be " a a a"
5. Paste 5 or 6 times.
6. View source code, &nbsp; has been added repeatedly.
7. Firefox succeeds correctly, IE10 failed as shown below.

Expected result:
&ltg;p>a a a a a a a a a a a a a a a a a a a&ltg;/p>

Actual result:
&ltg;p>a a a a&nbsp;a a a&nbsp;a a a&nbsp;a a a&nbsp;a a a&nbsp;a a a&ltg;/p>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6092](http://archive.tinymce.com/develop/bugtracker_view.php?id=6092) posted by [ibacondors](http://archive.tinymce.com/profile.php?name=ibacondors)_
> 
> _**Tags:** [msie msie10]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
