### ISSUE TITLE
Duplicate IDs for tox-icon-text-color__color and tox-icon-highlight-bg-color__color

### ISSUE THREAD

**Issue by stefandobre** [tinymce/tinymce#8720]
The Text Color and Background Color toolbar entries use a static ID for referencing an svg element.

While this is a minor issue that doesn't break functionality, it does produce invalid HTML when having more than 1 TinyMCE instance on 1 page, as IDs should be unique. Our accessibility checker specifically is flagging this.

<img width="508" alt="Screenshot 2023-05-11 at 12 02 54" src="https://github.com/tinymce/tinymce/assets/20504443/c5193401-660b-40bf-9c0f-862340f80298">

These elements should instead either use a class or a data attribute.

See:
https://github.com/tinymce/tinymce/blob/dd4c601aab9f1e5e8b64b98bf929c24dbcc38305/modules/oxide/src/less/theme/components/toolbar-button/toolbar-split-button.less#LL68C12-L68C12
and
https://github.com/tinymce/tinymce/blob/dd4c601aab9f1e5e8b64b98bf929c24dbcc38305/modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts#L121

**Comment by lostkeys** [comment]
Good catch! Will log an issue to fix this in a future release

— Fredrik, Product Manager

**Comment by TheSpyder** [comment]
This was fixed in TinyMCE 6.5, but we forgot to link the PR to this issue. Apologies.
