### ISSUE TITLE
Entire page freezes on copy

### ISSUE THREAD

**Issue by mrAceT** [tinymce/tinymce#8721]
**What is the current behavior? Describe the bug**
All operation is fine, the damnedest thing is, that when a portion of the text is copied (via CTRL-C) the entire page freezes!
(CTRL-X is fine, CTRL-V is fine)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE: 6.4.1 and 6.4.2
OS: Windows 10
Browser: Chrome 112.0.5615.138 and Edge  113.0.1774.35

**Comment by mrAceT** [comment]
I have tried several ways to catch the cause, but am unable to find it.

The odd thing is that when I run the exact same code on a local test server there is no problem!?
Could it be a browser security thing somewhere, somehow? Something with the SSL certificate maybe?

**Comment by spocke** [comment]
Try using incognito mode maybe it's a chrome extension. I can't seem to find that file any where in the chromium source code. Tried googling on that script file and similar error messages like the debug calls there but didn't find anything. Really need more info here and a way to reproduce.
