### ISSUE TITLE
Clear Formatting button incorrectly clearing the First String of characters.

### ISSUE THREAD

**Issue by MicahPuzio** [tinymce/tinymce#8723]
when opening an editor with some previously edited text, pressing the clear formatting button will clear the all font/ styling formats from a string of characters before a space.

open an Editor with the full suite of options available for the user. Create some line of text and make substantial changes to the font/ styling, taking particular care to ensure that the text before the first space has some formatting changes. upon saving the edited text, re-open the editor and press the 'clear formatting' button _BEFORE_ highlighting any text. you should observe the first string of characters before the first space have it's formatting cleared.

What is the expected behavior: I believe if a section of text is not highlighted, pressing the clear format button should not remove the formatting from any text. 

Tinymce-React 4.3.0. run in Google Chrome Version 112.0.5615.121.

https://github.com/tinymce/tinymce/assets/122472090/dfd9a752-5648-42d5-8617-112fd5aaed82

**Comment by TheSpyder** [comment]
This is a side effect of our "word grab" code. If you place the cursor in the middle of a word and use a formatting action it will expand the application of that format to the entire word. Normally if the cursor is at the start of a word the formatting action will not grab the word, but clear formatting does (try putting the cursor at the start of any other word and using it).

What you're seeing is the result of the editor needing to choose a cursor position when the editor loads. Regardless of whether the editor has been focused or not, the DOM doesn't allow us to have no cursor position, so we pick the first valid one in the document.

Thus clear formatting on load will always apply to the first word. Sorry.

**Comment by MicahPuzio** [comment]
Many thanks, this clear things up
