### ISSUE TITLE
Image adjustment box is overflow from edit zone

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#873]
Description of problem:

Steps to reproduce:
1.Click 'Insert image', insert a picture from web;
2.Change its size
3.up and down the vertical scroll, you will see the result as attachment.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6102](http://archive.tinymce.com/develop/bugtracker_view.php?id=6102) posted by [kgm545](http://archive.tinymce.com/profile.php?name=kgm545)_

> _**Tags:** [msie]_
> _**Status:** Verified_
> _**Resolution:** Duplicate_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
