### ISSUE TITLE
Unable to add newlines before and after a custom editable div in TinyMCE 6

### ISSUE THREAD

**Issue by sha2nktiwade** [tinymce/tinymce#8748]
**What is the current behavior? Describe the bug**
We are trying to add a custom div, which should be editable as per use-case. If we add this div as first child in the TinyMCE editor, then we are unable to newlines or any text before or after the div section entered.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
- Since the div we have mentioned is custom code and custom css is applied to this, we wont be able to share the HTML. 
- Please note that the HTML tag however is <div> tag.
- Below is the image how it looks like in the editor.
- 
![image](https://github.com/tinymce/tinymce/assets/130130998/36b96b63-b9f6-40ff-902e-41977a643788)

- We want this div to be editable as we need the capability to add and remove text in this div section.
- Since as per TinyMCE rules, if we want to convert it to widget, we need to make it non-editable. Since this is not an option for us, we wanted to check how how we can leverage this capability.
- Unable to convert it to widget as well keeping the editable quality.

**What is the expected behavior?**
- Regardless if it is a editable or non-editable, we should have the ability to convert it to widget.
- What can be down here so that we would be able to enter text inside it and also enter the lines before and after the div section by taking the cursor there.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- We are using TinyMCE version 6. Issue is present in all Browsers.

**Comment by sha2nktiwade** [comment]
Hi @spocke,

Our use-case is like you described. We will also have a nested structure like, div inside div and every div in itself should be a widget and editable component. 

Is this type of request not supported in TinyMCE 6? If no, is there a way in TinyMCE 6 that div can be configured in such a way that they will be both editable as well as a widget at the same time? Or  is there a way we can press the arrow key and move up or down a div?

User should have the ability to move up and down a lock and still use the block as editable component.

**Comment by sha2nktiwade** [comment]
@spocke - Any updates on this issue?

**Comment by zerefel** [comment]
This is really needed. Currently, DIVs in TinyMCE are second-class citizens. There are a few ways I tried to go about resolving this. I love TinyMCE, but it's like the editor just doesn't want me to achieve my goal and is actively fighting me.

1) I tried to add non-editable paragraphs before and after the DIV, however non-editable doesn't mean non-deletable, which is [another issue in itself](https://github.com/tinymce/tinymce/issues/3697). 
2) I tried to force the default root block to be 'p' so I can at least exit the DIV with enter and it will create a paragraph, however exiting a DIV just creates another DIV and you can't override this. That's another issue in itself, with many issues raised in this repo.

Please, give us a way to do this, I'd settle for hack at this point.
