### ISSUE TITLE
white icon for insertfile/moxiemanager

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#875]
see the attached image.
white icon button for 'insertfile' in chrome and explorer.
and 'E034' icon in Firefox

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6097](http://archive.tinymce.com/develop/bugtracker_view.php?id=6097) posted by [xavier](http://archive.tinymce.com/profile.php?name=xavier)_

> _**Tags:** [msie chrome]_
> _**Status:** Open_
> _**Resolution:** Works For Me_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
