### ISSUE TITLE
Underline and Strikethrough behaving incorrectly with custom font size and color

### ISSUE THREAD

**Issue by dani-ttci** [tinymce/tinymce#8766]
**Adding/Removing underline and strikethrough together is not working properly if combined with custom font size and color**

**Steps to reproduce:**
Try the fiddle [here](https://fiddle.tiny.cloud/V8iaab)
Steps:

1. Type some text
2. Click bold, italic, underline, and strikethrough
3. Add font color red (or any)
4. Update font size to 72px or above
5. Click enter and type new text
6. Remove bold, italic, underline, and strikethrough on the second line text
7. Re-add font and update font color and size to maximum
8. Highlight all text and click bold, italic, underline, and strikethrough on the second line text OR click strikethrough then underline, italic, and bold on the second line text

<img width="1440" alt="Screen Shot 2023-05-29 at 10 42 41 PM" src="https://github.com/tinymce/tinymce/assets/105846684/d73c46ac-d703-49e3-b20a-9316d651c277">

**Expected Results:**
It should properly display font styles

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE v6
Tested on chrome, safari, and firefox browsers

**Comment by bagaskarala** [comment]
same issue with me

- adjust size then apply strikethrough -> bug
- apply strikethorugh then adjust size -> expected

**Comment by TheSpyder** [comment]
As I said in #9060 this is just how HTML works. If you take the HTML contents and render them outside of TinyMCE it will look the same.

Unless it's a behaviour regression in the editor we're not likely to do anything about it.
