### ISSUE TITLE
Do not change the value of ImageSource

### ISSUE THREAD

**Issue by OneSeven** [tinymce/tinymce#8786]
**What is the current behavior? Describe the bug**

In the setting picture box, if the source value starts with "/", it will appear strange. After clicking Save, the address will be changed
I have encountered two situations,
The first one: the "/" at the beginning is deleted
The second: the "/" at the beginning is replaced by "../../../"

![2023-06-04 034753](https://github.com/tinymce/tinymce/assets/17974392/4a8aa9f1-fff4-46cd-9ed9-96522ac5a5bf)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://fiddle.tiny.cloud/Duiaab/5

**What is the expected behavior?**

Regardless of whether you are "kindly" processed by this piece, I just want to save any value I filled in, and don't make any changes!

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
windows 11

**Comment by TheSpyder** [comment]
By default relative URLs are normalised so that they all use the same style of reference. We have extensive documentation on this:
https://www.tiny.cloud/docs/tinymce/6/url-handling/

In this case it sounds like you want `convert_urls: false` which should disable all normalisation.
