### ISSUE TITLE
Can't focus the editor when only floating images

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#881]
Description of problem:

Hello,
there is a bug on IE when you insert a floating image, you can't focus the editor by clicking within.

Steps to reproduce:
1. Open the editor : http://www.tinymce.com/tryit/basic.php
2. Edit the source code and paste this : 

&ltg;p>&ltg;img style="float: left;" title="TinyMCE Logo" src="img/tlogo.png" alt="TinyMCE Logo" width="92" height="80" />&ltg;/p>

3. Try to click anywhere in the editor, you can't focus it !

Expected result:

Focus the editor to be able to add text (or something else)

Actual result:

You can't

Thank you and sorry for my english
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6104](http://archive.tinymce.com/develop/bugtracker_view.php?id=6104) posted by [gnicolas](http://archive.tinymce.com/profile.php?name=gnicolas)_

> _**Tags:** [msie msie7 msie8 msie9 msie10 image float focus]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
