### ISSUE TITLE
Copy from word and paste editor the bullet list formatting is missing? 

### ISSUE THREAD

**Issue by Jayachaa** [tinymce/tinymce#8810]
Tinymce 6 version

I have word document contains some list items like shown below
![image](https://github.com/tinymce/tinymce-docs/assets/58075922/0e646004-367d-4a70-a313-b34f18011217)

After pasting the content in Tinymce editor the formatting is not correct. it's placed as 'paragraph'.

![image](https://github.com/tinymce/tinymce-docs/assets/58075922/249f92e6-bbf5-4070-84cb-1e2c5d81a919)
![image](https://github.com/tinymce/tinymce-docs/assets/58075922/2d9b105c-fd33-4f91-88c0-88864d9822e1)

Expected:
It should keep the formatting: like below
'<UL>
<li>Text 1 </li>
<li>Text 2 </li>
</UL>
Code:

```
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.tiny.cloud/1/XXXXXXXXXXX/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
 
<script type="text/javascript">
  tinymce.init({
    selector: '#myeditablediv',
    inline: true,
	 plugins: 'anchor autolink charmap codesample paste emoticons image link lists media searchreplace table visualblocks wordcount',
      toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat | paste pastetext',
	  paste_word_valid_elements: '-strong/b,-em/i,-u,-span,-p,-ol,-ul,-li,-h1,-h2,-h3,-h4,-h5,-h6,-p/div,-a[href|name],sub,sup,strike,br,del,table[width],tr,td[colspan|rowspan|width],th[colspan|rowspan|width],thead,tfoot,tbody',
	  paste_merge_formats: true
    });
	</script>
</head>

<body>
  <h1>TinyMCE Inline Editing Mode Guide</h1>
  <form method="post">
    <div id="myeditablediv">Click here to edit!</div>
  </form>
</body>
</html>
```

Could please help us to resolve this issue?

**FYI:**
The formatting works in before the **TinyMCE version 6**. (Because the 'Paste' plugin is in that old version)

Thanks

**Comment by TheSpyder** [comment]
Microsoft Word content processing was removed from the open source codebase in TinyMCE 6, sorry. We are now only maintaining our premium [powerpaste](https://www.tiny.cloud/tinymce/features/powerpaste/) plugin for word import, although we are open to promoting a community continuation of the TinyMCE 5 word import logic:
https://github.com/tinymce/tinymce/discussions/7487
