### ISSUE TITLE
formatpainter plugin.js missing

### ISSUE THREAD

**Issue by gspgsp** [tinymce/tinymce#8819]
when i add formatpainter to plugins config, then refresh the page，i get the console error:
Failed to load plugin: formatpainter from url plugins/formatpainter/plugin.js
... 
env: vue2
note: i did't  pay  for Premium feature plugins，but i have a free 14-day Cloud trial.
how to solve this?

**Comment by lostkeys** [comment]
Are you loading TinyMCE from the cloud using the [Vue setup guide](https://www.tiny.cloud/docs/tinymce/6/vue-cloud/)? The trial is only for the cloud version of TinyMCE.

— Fredrik, Product Manager
