### ISSUE TITLE
Headings (h1-h6) resets to Paragraph when adding bullets/numbered list

### ISSUE THREAD

**Issue by dani-ttci** [tinymce/tinymce#8820]
**Applying headings (h1-h6) to a text and making it a numbered or bullets resets the font format to Paragraph.**

This happens to all instances/setup.

Headings should be retained regardless if it's in bullet/numbered list form or not.

Tested on Tinymce v6.
All OS/browsers are affected.

**Comment by TheSpyder** [comment]
This is currently by design.
Unlike other word processing environments, HTML headings (and paragraphs) have significant default margins, so when converting text

**Comment by dani-ttci** [comment]
> This is currently by design.
> 
> Unlike other word processing environments, HTML headings (and paragraphs) have significant default margins, so when converting text to a list we remove the paragraph/heading element around it.

Got it. Thank you!
