### ISSUE TITLE
Format breaks after line break (enter) on menubutton custom mergetags

### ISSUE THREAD

**Issue by AdriVergara** [tinymce/tinymce#8822]
I'm using last version of tinyMCE in an asp.net mvc solution. Using mergetags plugin was not an option for some reasons so i ended up making a custom MenuButton in toolbar, where i set items that insert content to the editor. This is working fine. When i click over any item, it shows what is expected:

![1](https://github.com/tinymce/tinymce/assets/26234592/dc05ede3-6714-45b0-b182-9513a2a2d132)

And i achieved this through javascript like this:

`
//custom mergetags
var tagItems = [];

Array.prototype.forEach.call(llistaCampsPersonalitzats, element => {
    let Name = element.title;
    let Value = element.value;
    let Type = element.type;
    //this is the mergetag html each item inserts
    let htmlTag = `<span id=" + Value + " class="mce-mergetag" contenteditable="false" data-mce-cef-wrappable="true" data-mce-mergetag="1"><span class="mce-mergetag-affix" data-mce-mergetag-affix="">#*#</span> + Name + <span class="mce-mergetag-affix" data-mce-mergetag-affix="">#*#</span></span>`;
    
    tagItems.push({ type: Type, text: Name, onAction: function () { editor.insertContent(htmlTag) } });
});

editor.ui.registry.addMenuButton('customtags', {
    text: 'Camps',
    search: {
        placeholder: 'Search camp...'
    },

    //Custom camps input search
    fetch: (callback, fetchContext) => {
        if (fetchContext.pattern.length > 0) {
            callback(
                tagItems.filter(item => item && item.text && item.text.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu, '').includes(fetchContext.pattern.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu, '')))
             );
         } else {
             callback(tagItems);
         }
    }
});
`

The problem is that when i click over the line on the editor and make a page break with the enter key, the format breaks completely. For example, in this same case where i have (source code):

`<p>#*#Servei_Dia#*# #*#Comunicaci&oacute;#*# #*#Operador#*#</p>`

Let's say i click right before the "Operador" tag and press enter. So this is what happens:

![2](https://github.com/tinymce/tinymce/assets/26234592/2d16f54f-5373-488a-a8c2-335896973caf)

And this is the Source code:

`<h1>#*#Servei_Dia#*# #*#Comunicaci&oacute;#*#</h1>`

So as you can see, the `<p>` tag transforms to `<h1>` and the last custom tag disappeared. Any idea why this is happening and how to solve it? 

Thank you,

**Comment by lostkeys** [comment]
Hi @AdriVergara. The solution is to subscribe to a plan containing merge tags. Mergetags was not trivial to build and naturally we cannot help you recreate a paid feature.

— Fredrik, Product Manager

**Comment by AdriVergara** [comment]
My company is currently talking with you about pricings but that's not the solution anyway. 
I already contacted with you about merge tags, check this:

[https://support.tiny.cloud/hc/en-us/requests/20144](url)

After you told me that that was not possible to do, the only thing i could do to workaraound it is to make it custom.

I'm not asking about the mergetags plugins because i'm not using it, it doesn't provide us what we need. I just need help with the format being destroyed when enter line break.

**Comment by lostkeys** [comment]
I need you to be able to [reproduce the issue in a TinyMCE fiddle](https://fiddle.tiny.cloud/) so we can inspect exactly what code you are using in a reproducible example.

**Comment by AdriVergara** [comment]
There it is:

[](https://fiddle.tiny.cloud/oAiaab)

Thank you,

**Comment by lostkeys** [comment]
Lol, this was a dirty bomb. It turns out we have a feature called [textpattern](tiny.cloud/docs/tinymce/6/content-behavior-options/#text_patterns) that has markdown-like text transformations, like typing stars to get lists, hashes to get headings. So your tags converts the content to a heading. The solution is to turn of or modify the default textpatterns. [Here is a demo](https://fiddle.tiny.cloud/pAiaab).

This should solve the issue.

**Comment by AdriVergara** [comment]
Thank you!!
