### ISSUE TITLE
@jayarjo That patch still doesn't return the original file name. If I upload `image.png`, it gets renamed to something like `blob01.png`. Is there a workaround on this so that the server gets `image.png` as the filename?

### ISSUE THREAD

**Issue by mihailbakirov** [tinymce/tinymce#8826]
Issue still exist, I'm facing the same problem as other people in the thread below - drag'n'drop images get renamed to something like `blob01.png`, is there a way to get the original filename of a dragged and dropped file? `images_reuse_filename` doesn't work.

              @jayarjo That patch still doesn't return the original file name. If I upload `image.png`, it gets renamed to something like `blob01.png`. Is there a workaround on this so that the server gets `image.png` as the filename?

_Originally posted by @alexkasina in https://github.com/tinymce/tinymce/issues/2871#issuecomment-301764633_

**Comment by mihailbakirov** [comment]
I guess that is the same issue as mentioned here https://github.com/tinymce/tinymce/issues/3652
We do also have powerpaste plugin available.

**Comment by carlosmintfan** [comment]
Please reopen
