### ISSUE TITLE
Pressing Enter at Bottom of Content Causes Editor to Jump

### ISSUE THREAD

**Issue by mhast** [tinymce/tinymce#8832]
**What is the current behavior? Describe the bug**
On MacOS, Chrome, Firefox and Safari: using the basic editor example, I scroll to the bottom of the page so that there is a page scrollbar as well as a scrollbar within the editor (see image below). I place the cursor at the bottom of the editor content after "... team.". Then I press enter to add a new paragraph and editor jumps to the bottom of the page.

Editor position before pressing enter:
<img width="400" alt="image" src="https://github.com/tinymce/tinymce/assets/862037/2111bc55-5c9e-4e81-af27-91202c76584c">

Editor position after pressing enter:
<img width="400" alt="image" src="https://github.com/tinymce/tinymce/assets/862037/44e75fae-5374-47a9-b778-93ddb72c9b84">

I am used the basic editor example:
https://www.tiny.cloud/docs/tinymce/6/basic-example/

**What is the expected behavior?**
I did not expect the editor to jump on the page.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 6
MacOS Chrome, Firefox and Safari

It works in Chrome on Windows.
It works using TinyMCE 5 in all browsers on MacOS (again the basic example : https://www.tiny.cloud/docs/demo/basic-example/).

**Comment by TheSpyder** [comment]
We're hoping to fix this in 6.6, PR is already open

**Comment by mmuelder** [comment]
Problem still occurs for us at TinyMCE version 6.6.0 (2023-07-12)
Its even visible on the official website https://www.tiny.cloud/get-tiny/

I scroll down to the editor:
![grafik](https://github.com/tinymce/tinymce/assets/5302657/e51116e7-d349-46ab-9849-ac58aaacd7d7)

Then I press return a couple of times after the last paragraph and the browser scrolls to the top:
![grafik](https://github.com/tinymce/tinymce/assets/5302657/875200fa-eaf2-457a-9861-388a511cc05d)

(Firefox 115.0.2)

**Comment by TheSpyder** [comment]
Apologies, after I wrote that it was bumped to 6.6.1. We should be publishing that within a week.

**Comment by mmuelder** [comment]
Just tried the new 6.6.1 - 2023-08-02 
Problem still exists. Your examples are still 6.6.0 so I cant show it there, but when we downloaded and self hosted it, the scroll position still jumps to the top on pressing return once the end of the editor is reached.

**Comment by TheSpyder** [comment]
Yes, 6.6.1 won't be deployed to our tiny.cloud `6-stable` channel (which our demos use) until the GA release in a couple of days.

Can you please try https://fiddle.tiny.cloud/ with the `6-dev` channel? It looks like the fix was delayed to 6.7 (which is a smaller release, the community version ETA is 3 weeks).

Apologies for promising the wrong thing.

**Comment by mmuelder** [comment]
seems to be fixed on 6-cloud-dev indeed, thx

**Comment by mhast** [comment]
I just tried version 6.6.2 and it is not fixed. I can reproduce it on the demo site as well as on https://fiddle.tiny.cloud/ version 6.6.2. I again enter text into the editor and scroll all the way to the bottom of the page, as well as to the bottom of the editor.

Before pressing enter:

<img width="1093" alt="image" src="https://github.com/tinymce/tinymce/assets/862037/2ee34717-c30b-44b0-b4ba-322304e65569">

After pressing enter:

<img width="1090" alt="image" src="https://github.com/tinymce/tinymce/assets/862037/b9b6b524-9b7d-4e56-9466-5c6299f7ff2b">

After pressing enter the editor jumps and I can no longer see the footer of the editor (cannot see the 'p' on the left nor the 'tiny' marker on the right.

**Comment by TheSpyder** [comment]
I did say above

> It looks like the fix was delayed to 6.7

which is currently `6-dev` on fiddle.

**Comment by shengslogar** [comment]
Can confirm `tinymce@6.7.0` fixes this issue ([repro](https://codepen.io/shengslogar/pen/LYMNodd)). However, `@tinymce/tinymce-vue@5.1.1` with a dependency of `tinymce@6.7.0` (sub-dependencies aren't shown on StackBlitz, but inspecting my local `package-lock.json` indicates this) still has this issue ([repro](https://stackblitz.com/edit/vue-mjzkvj?file=src%2FApp.vue)). Should I open a separate issue in that repo?

**Comment by TheSpyder** [comment]
That vue repro is still running 6.6.2 (to check this, either enable the `help` plugin or look at the `tinymce.minorVersion` property)

**Comment by shengslogar** [comment]
> That vue repro is still running 6.6.2 (to check this, either enable the `help` plugin or look at the `tinymce.majorVersion` and `tinymce.minorVersion` properties)

Indeed! Didn't realize `tinymce-vue` reached for cloud libraries (6.6) but also had a dependency of `tinymce` (6.7), seemingly just for TypeScript types. Thanks for your help!
