### ISSUE TITLE
How to update in real time if there are changes?

### ISSUE THREAD

**Issue by ranwenqi** [tinymce/tinymce#8840]
Develop plugins or I modify the source code of css, how I want to see the effect in real time. At present, I yarn build every time I modify it, which is really slow and troublesome. I hope you can help me solve it. Thank you very much

**Comment by TheSpyder** [comment]
You mean for adjusting tinymce itself? We have `yarn start` to run tinymce in dev mode.

For updates to the LESS source, while we don't recommend doing that for simple skin development, `yarn oxide-build` will compile them to CSS and `yarn tinymce-grunt dev` will publish those changes to where webpack can see them. That's about the best we have right now.
