### ISSUE TITLE
Help Plugin failes to load keyboard internationalization for English language

### ISSUE THREAD

**Issue by tiberiuzuld** [tinymce/tinymce#8844]
**What is the current behavior? Describe the bug**
Help Plugin failes to load keyboard internationalization for English language.

```ts
const pLoadHtmlByLangCode = (baseUrl, langCode) => global$3.load(`tinymce.html-i18n.help-keynav.${ langCode }`, `${ baseUrl }/js/i18n/keynav/${ langCode }.js`);

GET https://<domain>/<path>//plugins/help/js/i18n/keynav/en.js 404 not found
```

Possible issue arrises from
Help text displayed at Help -> Help -> Keyboard Navigation re-written. #DOC-1936
Translations added for Help text displayed at Help > Help > Keyboard Navigation. #TINY-9633

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Was not able to reproduce on the cloud version, seems to be an issue how it tries to laod the en.js file for npm package and @tinymce/tinymce-angular
For other translations we use config.language_url and config.language to configure and load the translation files.
But for the plugin I was not able to find such options to be able to configure or preload these files.

**What is the expected behavior?**
For the translation files for plugins to be configurable to be able to work with bundlers like angular-cli

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE v6.5.1 Chrome 
It worked in TinyMCE v6.4.2

**Comment by TheSpyder** [comment]
Can you please double-check your deployment? The file is definitely there on NPM
https://unpkg.com/tinymce@6.5.1/plugins/help/js/i18n/keynav/en.js

We haven't finalised the docs for this yet, but you can preload this file and then the help plugin will not attempt to download it.

**Comment by larryprice** [comment]
I am also experiencing this same issue with the `@tinymce/tinymce-react` package.

No fiddle repro steps at the moment from me either unfortunately.

**Comment by tiberiuzuld** [comment]
Thanks @TheSpyder ,
Importing manually the languges works
```ts
import 'tinymce/plugins/help/plugin';
import 'tinymce/plugins/help/js/i18n/keynav/en';
import 'tinymce/plugins/help/js/i18n/keynav/de';
import 'tinymce/plugins/help/js/i18n/keynav/fr_FR';
import 'tinymce/plugins/help/js/i18n/keynav/it';
```

**Comment by Good4zb** [comment]
I've found the same issue when loading tinymce via https://cdnjs.cloudflare.com. The issue is the /js/ folder in /help/ doesn't exist therefore the en.js doesn't exist.

* Work around 1 remove the help plugin from your init script
* Work around 2 use an alternative CDN jsdelivr or tiny.cloud

I'm submitting a request to update the cloudflare build script to not exclude /js/ folders for plugins
https://github.com/cdnjs/packages/blob/master/packages/t/tinymce.json

An issue has been logged to update cdnjs at [https://github.com/cdnjs/packages/issues/1597](https://github.com/cdnjs/packages/issues/1597)
