### ISSUE TITLE
Flash content with Tinymce 4?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#886]
Is it posible or will it be in the future to add Flash content with tinyMCE 4 just like we used to do in tinyMCE 3 with media plugin?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6109](http://archive.tinymce.com/develop/bugtracker_view.php?id=6109) posted by [PeR45](http://archive.tinymce.com/profile.php?name=PeR45)_
> 
> _**Tags:** [media]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! 🍺
