### ISSUE TITLE
Text color palette has extra one color

### ISSUE THREAD

**Issue by MustafaEminn** [tinymce/tinymce#8878]
**What is the current behavior? Describe the bug**
I added custom color map.

In text color palette I have an extra one color. ( The extra color is pointed by cursor and has specific title)
![image](https://github.com/tinymce/tinymce/assets/63938499/b9c7bab7-f844-4be5-8952-f8d3e49c609e)

But in background color palette everything is fine.
![image](https://github.com/tinymce/tinymce/assets/63938499/6ed763e3-45e2-4e2e-8cfe-2eedb1fe14a1)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
I don't know how to reproduce it. Just I added color map and this is happening.

**What is the expected behavior?**
Should not has extra color.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE Version: 6.5.1
Browser/OS: Chrome/Windows 10

I just tried on version 6+.

**Comment by IAWAdrianParker** [comment]
The problem seems to be a spurious extra entry which is stored in localStorage.   if you do the following before creating the control, it seems to fix the problem

`    localStorage.removeItem("tinymce-custom-colors-forecolor");
    localStorage.removeItem("tinymce-custom-colors-hilitecolor");`
