### ISSUE TITLE
Rails7 TinyMce 5 compil fails

### ISSUE THREAD

**Issue by aryalsan** [tinymce/tinymce#8887]
I am using rails 7 and Tinymce, everything works perfect in production. I got the following error while trying to compile in production.

```
SassC::SyntaxError: Error: "calc(100vh - 110px)" is not a number for `min'
        on line 1468:15 of stdin, in function `min`
        from line 1468:15 of stdin
>>   max-height: min(650px, calc(100vh - 110px));
```

The respective line was found in 
```
.tox .tox-dialog__body-content {
  box-sizing: border-box;
  display: flex;
  flex: 1;
  flex-direction: column;
  max-height: min(650px, calc(100vh - 110px));
  overflow: auto;
  -webkit-overflow-scrolling: touch;
  padding: 16px 16px;
}
```

**Comment by TheSpyder** [comment]
Sounds like your CSS tool doesn't support the latest standards.
https://developer.mozilla.org/en-US/docs/Web/CSS/calc

**Comment by jamesw** [comment]
> I am using rails 7 and Tinymce, everything works perfect in production. I got the following error while trying to compile in production.
> 
> ```
> SassC::SyntaxError: Error: "calc(100vh - 110px)" is not a number for `min'
>         on line 1468:15 of stdin, in function `min`
>         from line 1468:15 of stdin
> >>   max-height: min(650px, calc(100vh - 110px));
> ```
> 
> The respective line was found in
> 
> ```
> .tox .tox-dialog__body-content {
>   box-sizing: border-box;
>   display: flex;
>   flex: 1;
>   flex-direction: column;
>   max-height: min(650px, calc(100vh - 110px));
>   overflow: auto;
>   -webkit-overflow-scrolling: touch;
>   padding: 16px 16px;
> }
> ```

Did you find a solution to this issue? I am facing the same
