### ISSUE TITLE
Weird size on toolbar when opening in new window

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#890]
Description of problem:

I noticed when submitting my other Bug #6111 a problem that I have seen different times even in 3.x versions but never knew how to reproduce.

Steps to reproduce:
1. Open a new window with ctrl+n or cmd + n
2. paste http://fiddle.tinymce.com/7rdaab/5
3. press run link
4. toolbar gets wrong size.
5. reload window
6. press run again
7. toolbar get correct size

Expected result:
Should get correct size when opening first time in a new browser window

Actual result:
Toolbar looks really big the first time when init in a new browser window

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6112](http://archive.tinymce.com/develop/bugtracker_view.php?id=6112) posted by [magny](http://archive.tinymce.com/profile.php?name=magny)_

> _**Tags:** [firefox chrome 4x]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** http://fiddle.tinymce.com/7rdaab/5_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
