### ISSUE TITLE
Editor losses font size & style in IE after save

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#891]
Description of problem:
Tiny MCE version: 4.0.1.

When I change the font size or font style in tiny mce editor and hit save and view my page, it displays correct font size and style on the form .
When I open editor again the editor doesn't display correct font size or style. IE9 doesn't display styles and size of font as selected and saved before. firefox displays it right.
Steps to reproduce:
1.In editor's text are type any 3 word. 
2.Change font style & size of each one and hit save.
3. Open saved item in editor to edit.
4. editor doesn't display previously saved font size & font style.
5.

Expected result:
firefox test.png
Actual result:
test.png

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6115](http://archive.tinymce.com/develop/bugtracker_view.php?id=6115) posted by [goraj](http://archive.tinymce.com/profile.php?name=goraj)_
> 
> _**Tags:** [msie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
