### ISSUE TITLE
In TinyMCE Editor the bullet list or numbered list is moving towards left and user is not able to see it if the Font size greater than or equal to 36pt

### ISSUE THREAD

**Issue by Mahesh554** [tinymce/tinymce#8918]
**What is the current behavior? Describe the bug**
In TinyMCE Editor the bullet list or numbered list is moving towards left and user is not able to see it if the Font size greater than or equal to 36pt

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Navigate to https://www.tiny.cloud/docs/tinymce/6/classic-demo/
2. Write one to ten numbers (in words) line by line
3. Now select all and add numbered list to them
4. Now select them again and give font size as 36pt
5. Observe that the number ten is half cut and only 0 is visible in UI

![numberlist_issue](https://github.com/tinymce/tinymce/assets/28930402/468aaaa2-3dd2-4e73-a40a-9e68b5141a0c)

**What is the expected behavior?**
List should be aligned properly and should not move towards left even after increase in font size.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 6.4.2 and later (might be there in older versions also, didn't checked.)

**Comment by TheSpyder** [comment]
That's just normal HTML behaviour. If you save the content to a web page it would do the same thing.
https://fiddle.tiny.cloud/1Diaab
