### ISSUE TITLE
Plugin tabfocus does not focus on version 4.0.1 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#892]
Description of problem:

tabfocus_elements: ":prev,:next" not work in modern browser.

function canSelect(el) {
  return ((!canSelectInOldIe(el))) && el.getAttribute("tabindex") != '-1' && canSelectRecursive(el);
}

function canSelectInOldIe(el) {
  return el.tabIndex || el.nodeName == "INPUT" || el.nodeName == "TEXTAREA";
}

canSelectInOldIe: el.tabIndex is a integer > 0 and return always false on modern browser. Regular input with tabIndex="x" are not focusable.

Steps to reproduce:
1. set breakpoint to find function inside tabHandler
2. press tab and see what happens

Expected result:
focus next or prev element with tabIndex

Actual result:
focus next or prev element without tabIndex

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6114](http://archive.tinymce.com/develop/bugtracker_view.php?id=6114) posted by [andrejlnnk](http://archive.tinymce.com/profile.php?name=andrejlnnk)_
> 
> _**Tags:** [firefox msie safari chrome opera tabfocus]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by alecpl** [comment]
Is this still an issue? Can be closed?

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
