### ISSUE TITLE
 Failed to load icons: thin from url

### ISSUE THREAD

**Issue by veeraattili** [tinymce/tinymce#8925]
Team,
We are trying use text-editor while using this we are getting below console error. Please help me resolving this. 
Thanks in advance.

<img width="772" alt="image" src="https://github.com/tinymce/tinymce/assets/140362494/7b9f6216-0447-4332-84fe-f5ebe1ced8d4">

**Comment by TheSpyder** [comment]
Thin icons are a premium feature, we do not offer premium support via GitHub. If you have a support subscription, you will be better served by our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
