### ISSUE TITLE
external_plugin using tiny_mce_wiris returned a error in console "Uncaught TypeError: tinymce.create is not a function"

### ISSUE THREAD

**Issue by jcvjunior** [tinymce/tinymce#8931]
My code exemple

<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.tiny.cloud/1/api_key_hash/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body>
  <textarea>
      Welcome to TinyMCE!
  </textarea>
  <script>
    tinymce.init({
        selector: 'textarea',
        external_plugins : { tiny_mce_wiris : 'https://www.wiris.net/demo/plugins/tiny_mce/plugin.js' },
        plugins:  'advlist autolink lists link image media charmap preview anchor pagebreak searchreplace wordcount visualblocks visualchars code  insertdatetime media nonbreaking save table directionality emoticons tiny_mce_wiris',
        toolbar: [
            'insertfile undo redo | blocks fontfamily fontsize | forecolor backcolor | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent',
            'link image imageupload media emoticons | tiny_mce_wiris_formulaEditor tiny_mce_wiris_formulaEditorChemistry'
        ],
        language: 'pt_BR',
        fontsize_formats: '8pt 10pt 12pt 14pt 18pt 24pt 36pt'
    });
  </script>
</body>
</html>

When I have external_plugins : { tiny_mce_wiris : 'https://www.wiris.net/demo/plugins/tiny_mce/plugin.js' }, and the wiris references in plugins: "tiny_mce_wiris" and in toolbar: "tiny_mce_wiris_formulaEditor tiny_mce_wiris_formulaEditorChemistry", I have the error in the console log.
plugin.js:1 Uncaught TypeError: tinymce.create is not a function
    at plugin.js:1:1046367
    at plugin.js:1:1054259
    at plugin.js:1:1054263

Resource usage references were taken from the documents.
https://www.tiny.cloud/docs/tinymce/6/creating-a-plugin/#example-using-external_plugins
https://docs.wiris.com/mathtype/en/mathtype-integrations/mathtype-for-html-editors/mathtype-for-tinymce.html#external-integration-2972371

**Comment by TheSpyder** [comment]
`tinymce.create()` was removed in TinyMCE 6
https://www.tiny.cloud/docs/api/tinymce/root_tinymce/#create

You could use TinyMCE 5, then the plugin might work, but version 5 won't be receiving further updates and is no longer supported.
