### ISSUE TITLE
Fixed height inline editor not scrilling when hitting enter

### ISSUE THREAD

**Issue by blindspeed90** [tinymce/tinymce#8935]
**What is the current behavior? Describe the bug**
This looks to be the same as https://github.com/tinymce/tinymce/issues/1055 .  When adding a fixed height and overflow, hitting enter adds new P tags, and the scrollbar grows, but the scroll position does not place you where the caret is.  After about 15 of them it updates and scrolls.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Just keep hitting Enter,

**What is the expected behavior?**
It should scroll with each Enter, like it does with non-inline.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
6.5.1
[tinymce6_enterbug.zip](https://github.com/tinymce/tinymce/files/12176774/tinymce6_enterbug.zip)

**Comment by JarvisArt** [comment]
+1 ，I had the same problem.

```tsx
<div
  style={{
    width: 700,
    height: 200,
    overflow: 'auto',
    border: '1px solid #ccc',
    margin: '100px 0 200px 200px',
  }}
>
  <Editor
    apiKey="your_TinyMCE_API_key"
    initialValue="<p>This is the initial content of the editor</p>"
    init={{
      inline: true,
      height: 500,
      menubar: false,
      plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table paste code help wordcount'
      ],
      toolbar: 'bold italic underline forecolor backcolor subscript superscript alignleft aligncenter alignright quickimage kityformula-editor',
    }}
  />
</div>
```

https://github.com/tinymce/tinymce/assets/38420763/f0713369-1265-49eb-9103-b0d34b4ac781
