### ISSUE TITLE
BUG: `mceEditable` image not working as it did on previous versions 5.x

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#8939]
Hi,

This bug only started to happen on version 6.x - it does not happen on all previous versions. If I have a parent element with the class `mceNonEditable`, on previous versions I could edit all elements that have the class `mceEditable` inside, even if it was an image. However, in the 6.x version, if the element that has the class `mceEditable` is an `img` the user cant select it, cant resize (using the blue squares).

You can check the bug at:

https://fiddle.tiny.cloud/PDiaab

Using exacly the same code, but on version 5.x the bug does not happen:

https://fiddle.tiny.cloud/QDiaab

Try to click the image, you will see in the first link nothing happens, on the second link you can select the image and even resize it using the blue squares on the corners.

**Comment by TheSpyder** [comment]
We've been making some changes to the noneditable code in the last few months to improve templates. Using the fiddle version picker, it seems to work on 6.3.2 but appears to be a regression in 6.4.0. Can you confirm?

**Comment by batata004** [comment]
> We've been making some changes to the noneditable code in the last few months to improve templates. Using the fiddle version picker, it seems to work on 6.3.2 but appears to be a regression in 6.4.0. Can you confirm?

You are correct. Until the version 6.3.2 it still works, then on 6.4.0 it gets broken up to the latest stable version.

**Comment by TheSpyder** [comment]
Oh I forgot - yes, `noneditable` is now a core feature:
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#removed-plugins

Note that the configuration options changed as a result of this move.

**Comment by batata004** [comment]
@TheSpyder thank you for your attention. One final question: on versions prior to 6.x I could simply import the `noneditable` plugin and the user could only edit elements with class `mceEditable`. But sometimes, for admin reasons, I would not import the `noneditable` plugin in order for me to be able to change everything in the page (not only the `mceEditable` elements). Now, that the `noneditable` is a core feature, I ask you: how do I disable this plugin without having to remove all `mceEditable` and `mceNonEditable` class from all elements?

**Comment by TheSpyder** [comment]
@batata004 good question. Does changing `noneditable_class` and `editable_class` work?
https://www.tiny.cloud/docs/tinymce/6/content-behavior-options/#noneditable_class
https://www.tiny.cloud/docs/tinymce/6/content-behavior-options/#editable_class

We lost the central documentation page for the feature when the plugin was removed, I've flagged that with our docs team.

**Comment by TheSpyder** [comment]
Excellent! I've logged this with our docs team to bring back some sort of noneditable feature page now that it no longer has a dedicated plugin page, I'll also note somewhere that a central option would be helpful.

**Comment by soritaheng** [comment]
Hi @batata004, thanks for opening the issue. The `allow_noneditable` option is now available in [TinyMCE 8.4](https://www.tiny.cloud/docs/tinymce/latest/8.4.0-release-notes/#the-noneditable-feature-can-now-be-disabled-with-the-new-allow_noneditable-option) to disable the noneditable feature.
