### ISSUE TITLE
Strange behavior in text input with an input method on iPad

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#894]
Environment: iPad, iOS 6, Safari, tinymce 3.5.8 & 4.0.1

Description:
When we type some text with an input method (such as Japanese), delete some characters and type some text, deleted text is automatically inserted.

Steps of reproduce:
With Japanese input method,

1. Type 'AAA'  (Input: 'AAA')
2. Delete 2 characters (Input: 'A')
3. Type 'B' (Input: 'AAAB')

Expected result:
Input text is 'AB'

Actual result:
Input text is 'AAAB'

Screenshot: http://gifzo.net/BRQoYdjDgiS 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6117](http://archive.tinymce.com/develop/bugtracker_view.php?id=6117) posted by [uiureo](http://archive.tinymce.com/profile.php?name=uiureo)_

> _**Tags:** [safari]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
