### ISSUE TITLE
BUG: TinyMCE loses focus when using `select`

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#8940]
This bug is easily reproduceable. Open the link below (it has the minimal code to trigger the bug):

https://fiddle.tiny.cloud/dEiaab/6

Put your mouse cursor (click) anywhere inside the first line (which contains `XXX`). Then press spacebar. You will see the code will replace all the contents of that element with 3 spaces. After that, if you press any other key on your keyboard (like for example the letter `A`) then the letter A will show up.

Now do the same on the second line. You will see that when you try to type the letter `A` it will not work, for some reason the editor loses focus and you need to click again in the element in order to be able to type anything inside it. 

And this bug gets even weirder, do the same in the link below:

https://fiddle.tiny.cloud/dEiaab/7

The **only** difference of this second link to the first is that instead of using 3 spaces I use 3 underscores (you can actually use any other printable char). In this case, the bug goes away.

So the bug only happens in the 1st link when using 3 spaces ("&nbsp") but on the second it does not.

If you need any additional info I am here to help.

**Comment by batata004** [comment]
Is there any other place to report bugs?

**Comment by batata004** [comment]
Where else can I report this?

**Comment by TheSpyder** [comment]
Apologies for the lack of response to this. The only other place is our professional support offering for customers on a paid TinyMCE plan.

**Comment by batata004** [comment]
So, if I buy the USD 80 plan (is there a cheaper one?) I can request your professional support team to fix this bug and have it fixed?

**Comment by TheSpyder** [comment]
I'm not saying we ignore bugs reported by the open source community. I'm also not guaranteeing that a paid subscription will give you a quick turnaround for bug fixes.

I'm just noting that we have a professional support option which includes a dedicated team to respond to customer concerns. The only people who monitor github issues are our developers.
