### ISSUE TITLE
BUG: TinyMCE does not work allow content to overflow

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#8941]
Dear friends,

I cant find a way to make content overflow outside the iframe that TinyMCE creates. Take a look at the simple case below:

https://fiddle.tiny.cloud/dEiaab/11

You can see I configured `body` with `background:transparent` in the `content_style` and the yellow background does not show up inside the TinyMCE. Even worse is the red outline that I configured in the element inside TinyMCE, it does not overflow and gets really strange.

Is there an alternative to make this work?

**Comment by TheSpyder** [comment]
This isn't something we can control, it's just how iframes work. You'd have the same result using a plain iframe tag without TinyMCE involved.

You might be looking for inline mode - note that in this mode you can't use a `textarea`:
https://fiddle.tiny.cloud/dEiaab/13
