### ISSUE TITLE
Can't delete images when the upload fails in `images_upload_handler`

### ISSUE THREAD

**Issue by ardalan-nhd** [tinymce/tinymce#8942]
**What is the current behavior? Describe the bug**
Not a bug actually, but previously on version 5 of tinyMCE, you could remove the image if the upload failed by using `failure("text to be shown", { remove: true })`. But in version 6, since there is no `failure` or `success` callbacks and you need to return a `Promise`, you can't do that.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
when you init tinyMCE and you pass `images_upload_handler` option, there is no way to remove image on failure.
Currently, I fixed this issue by setting `paste_data_images` to `false`. But I want to allow the user to paste images.

**What is the expected behavior?**
Being abled to remove image on upload failure.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version 6

**Comment by TheSpyder** [comment]
Apologies if this wasn't clear [in the docs](https://www.tiny.cloud/docs/tinymce/6/upload-images/#images_upload_handler), but we did a straight swap from `failure` and `success` callbacks to the `resolve` and `reject` statuses of a promise. As such, the same API applies.

Here's one of the tests we have for `remove: true`:
https://github.com/tinymce/tinymce/blob/6a70831a19d8c36dc2d787dab95eb44d139c5d95/modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts#L432-L446

**Comment by ardalan-nhd** [comment]
Oh thanks. I don't know why I didn't see that section in the docs :D
