### ISSUE TITLE
Spellcheck plugin always returns "No misspellings found"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#895]
Description of problem: The spellcheck plugin uses a google service which now appears to be defunct. This causes the plugin to default to the "No misspellings found" result.

Steps to reproduce:
1. Enable the spellchecker plugin for Tiny
2. Enter text with known bad spellings
3. Click the spellcheck button in the toolbar
4. Receive message "No misspellings found"

Expected result: The plugin should be able to identify misspelled words, or it should be possible to force Tiny to allow the browser's spell checking functionality to work when the plugin is disabled.

Actual result: No spell checking functionality

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6118](http://archive.tinymce.com/develop/bugtracker_view.php?id=6118) posted by [tkeyser](http://archive.tinymce.com/profile.php?name=tkeyser)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by nori-h** [comment]
We have taken a look and this issue appears to be a duplicate of #1561

**Comment by nori-h** [comment]
We have taken a look and this issue appears to be a duplicate of #1087
