### ISSUE TITLE
Unable to add `style` tag using the code plugin

### ISSUE THREAD

**Issue by sonikasharma1403** [tinymce/tinymce#8951]
**What is the current behavior? Describe the bug**
If we add a `style` block it gets removed

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
- Enable code plugin
- Use style tag to modify styles.. notice that it gets removed as soon as you click on save

**What is the expected behavior?**
Style tag should be preserved

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- latest

**Comment by TheSpyder** [comment]
If you're adding it inside the body, TinyMCE bans this by default. Use the `valid_children` configuration option to allow it.
https://www.tiny.cloud/docs/tinymce/6/content-filtering/#valid_children
