### ISSUE TITLE
[help] how to save to database in optimal way?

### ISSUE THREAD

**Issue by terlan4** [tinymce/tinymce#8957]
So while multiple clients edit the content, we only send changes through websockets and other clients' editors merge new changes automatically.

But what about saving the content to database? Database service doesn't know how to merge new changes to what is already saved. When we save to database, do we have only these two options:

send only changes to your server and let the server merge it with what is saved in database and save the result to db store.
send entire document on your editor with request to save in db
None of these options sound good bandwidthwise. I would be really happy to hear what are the best practices around saving to db.

Also should we save as blob or which data type? (please suggest both for mongo and mysql)

(frontent-nextjs, backend-either next serverless, express, or fastify)

**Comment by TheSpyder** [comment]
Which product are you referring to? Our premium RTC plugin, or something third party?

Premium support is not offered via github, and aside from that our RTC plugin has been discontinued with the service to be turned off at the end of 2023.

**Comment by terlan4** [comment]
I just want to save my editor content in mongo atlas, supabase, or planetscale database. and my backend will be with express.

**Comment by TheSpyder** [comment]
I meant the client side frameworks. Multiple clients editing content, sending changes through websockets, these aren't features of our open source editor.

Our RTC solution included a [feature to assist with saving content](url), but it doesn't sound like you're referring to our plugin.
