### ISSUE TITLE
Menu Options on par with Buttons

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#896]
Please make all options available from the menu as well as buttons. Right now, there are lots of missing options, like font-size, text colors, bullet list, numbered lists, remove link, Insert file (Moximanager).

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6119](http://archive.tinymce.com/develop/bugtracker_view.php?id=6119) posted by [jasch](http://archive.tinymce.com/profile.php?name=jasch)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
