### ISSUE TITLE
TinyMCE doesn't work in a PWA (progressive web app)

### ISSUE THREAD

**Issue by anilshanbhag** [tinymce/tinymce#8962]
**What is the current behavior? Describe the bug**
I am using TinyMCE in my PWA. When an App is designed as a PWA (uses a service worker), the host page should be able to intercept all requests so users can use it offline. 

Currently, as TinyMCE loads the editor in an iframe with srcDoc, it hits a nasty old Chromium bug [cr#880768](https://bugs.chromium.org/p/chromium/issues/detail?id=880768). Requests for default/content.min.css and oxide/content.min.css  do not go through the service worker. Hence the user is not able to use it offline.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service Worker and srcdoc IFrame Example</title>
</head>
<body>

<div id="editor"></div>
<script src='https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.2.0/tinymce.min.js'></script>
<script>
  // Register the service worker
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw.js').then(function(registration) {
      console.log('Service Worker registered with scope:', registration.scope);
    }).catch(function(error) {
      console.log('Service Worker registration failed:', error);
    });
  }

tinymce.init({selector: '#editor',});
</script>

</body>
```

sw.js
```
self.addEventListener('fetch', event => {
    console.log('Intercepted request for:', event.request.url);

    // Add caching or other logic here if desired...

    event.respondWith(fetch(event.request));
});
```

**What is the expected behavior?**
The host service worker should intercept TinyMCE editor requests. 

With the above example, you will see
```Intercepted request for: https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.2.0/skins/ui/oxide/skin.min.css```

But you will see no logs for https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.2.0/skins/ui/oxide/content.min.css and https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.2.0/skins/content/default/content.min.css

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
6.2.0

**Comment by anilshanbhag** [comment]
The same issue happens with 6.6.1

Replaced the src with ```https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.6.1/tinymce.min.js```. 

The main issue arising from the above bug is that it make it impossible to use TinyMCE within a PWA.

**Comment by TheSpyder** [comment]
There are a couple of ways around this

* use `inline: true` to edit using a plain `contenteditable=true` element, rather than an iframe
* TinyMCE 6.5 added a `init_content_sync: true` option which reverts back to the TinyMCE 5 style of loading content, using `document.write` instead of `srcdoc` (which can trigger a console warning, but may avoid this issue)

**Comment by anilshanbhag** [comment]
Thanks @TheSpyder 
The Chrome implementation is dumb. init_content_sync doesn't work either.
The only way is to use inline: true which doesn't work for my use case.

An alternative implementation of TinyMCE that loads the editor in a shadow root instead of an iframe would work.

**Comment by TheSpyder** [comment]
Yes, shadow root is a direction we are interested in pursuing. We're currently waiting for the browsers to fix some issues with text selection in shadow root elements before we look at it seriously.
