### ISSUE TITLE
Image uploader

### ISSUE THREAD

**Issue by masartbenji** [tinymce/tinymce#8964]
Hello, with my team we use TinyMce for Angular library, we recently upgrade the version of this library.

On previous version, this code worked like expected, the dataUrl is like 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgEBLAEsAAD/....',

`this.updateRichTextEditorInitializer('images_upload_handler', async function(blobInfo, success, failure, progress) {
    const dataUrl = await FileUtils.convertToDataUrl(blobInfo.blob() as Blob);
    success(dataUrl);
});`

Withe the new version we received error message

![image](https://github.com/tinymce/tinymce/assets/32701546/e0f0a193-8cf7-4f15-b509-38006991a684)

The previous version of the library was 5.0.1 and now we want to use 7.0.0

**Comment by TheSpyder** [comment]
TinyMCE 6 changed the `images_upload_handler` config to use promises, rather than `success` and `failure` callbacks. You can just do `async (blobInfo) => await FileUtils.convert...` now, since you're already using promises.

https://www.tiny.cloud/docs/tinymce/6/upload-images/#images_upload_handler
