### ISSUE TITLE
Modfying predefined toolbar button tooltip/icon

### ISSUE THREAD

**Issue by ferlimputra** [tinymce/tinymce#8967]
TinyMCE: 6.0.0

Is there a way to modify/override the tooltip/icon for a pre-defined toolbar button like 'bold', 'italic', etc.?
I tried using editor.ui.registry.getAll().buttons but that only returns the custom buttons and not the predefined buttons.

Thanks.

**Comment by TheSpyder** [comment]
Yes, by registering a new icon for the button:
https://www.tiny.cloud/docs/tinymce/6/apis/tinymce.editor.ui.registry/#addIcon

The built-in icon names match the SVG filename in the repository (so `bold.svg` can be overridden by registering a new `bold` icon):
https://github.com/tinymce/tinymce/tree/develop/modules/oxide-icons-default/src/svg

The best time to do this is probably during `setup`, as you need to apply the change after the icon pack has loaded but before any UI elements are rendered.

For more complete documentation see our tips on creating an icon pack, which also includes a list of icon names:
https://www.tiny.cloud/docs/tinymce/6/creating-an-icon-pack/

**Comment by ferlimputra** [comment]
Thanks! That works perfectly for the icon.

How about the tooltips? Is there a way to override them as well?

**Comment by TheSpyder** [comment]
Possibly, if you load a language pack that changes the string (but keep in mind any duplicate strings will also be changed). There's no way to override the predefined buttons without completely redefining them.
