### ISSUE TITLE
Whatever the position of the cursor in the editor, bullets and list numbering always start at the beginning of the text area

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#898]
Version 3.4.7
Navigaeur IE

Whatever the position of the cursor in the editor, bullets and list numbering always start at the beginning of the text area.  

The bug is not reproducible in other browsers.

In IE, block search performed by TinyMCE to determine the beginning and
the end of the bulleted list does not include the tag "&ltg;br />". only
paragraph tag "&ltg;p>" is taken into account.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6121](http://archive.tinymce.com/develop/bugtracker_view.php?id=6121) posted by [khaled](http://archive.tinymce.com/profile.php?name=khaled)_
> 
> _**Tags:** [bullets and list numbering 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
