### ISSUE TITLE
images_upload_handler undefined issue

### ISSUE THREAD

**Issue by Zack-Heisnberg** [tinymce/tinymce#8991]
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

using the last version 6.6.2

        function image_upload_handler(blobInfo, success ) {
        success('https://picsum.photos/200/300')
        }

        window.tinymce.init({
              selector: 'textarea',
              images_upload_handler: image_upload_handler,
       })
 
 you get this error
 Cannot read properties of undefined , reading then 
 
 chaning to older version work fine ( 5 )
 
**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
6.62
yes

**Comment by TheSpyder** [comment]
See my response in #8964
