### ISSUE TITLE
Click "..." on the toolbar, and the floating box that appears will select the first item by default

### ISSUE THREAD

**Issue by dusting-123** [tinymce/tinymce#8999]
**What is the current behavior? Describe the bug**
When the content of the toolbar is too much to display, it will display '...', click on '...', the floating or sliding toolbar will select the first element by default.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
![image](https://github.com/tinymce/tinymce/assets/70480411/14f45239-899a-464a-b49d-cbd4739abdb3)

**What is the expected behavior?**
The first element is not selected by default

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version 6.4.2

**Comment by TheSpyder** [comment]
This is by design. When the new buttons appear, we want users with a screen reader to know what changed (particularly with the floating toolbar where the keyboard is focus-locked inside the floating area).
