### ISSUE TITLE
Issue with Applying "Almarai" Font to TinyMCE Content

### ISSUE THREAD

**Issue by waseemViwell** [tinymce/tinymce#9006]
**I'm facing an issue while trying to apply the "Almarai" font to the content within the TinyMCE editor in my React application. I've tried multiple approaches, including using the content_style parameter and custom CSS, but the font is not being rendered as expected.**

- Imported "Almarai" font using <link> tag in the <head> of my HTML.
- Configured TinyMCE with the desired fontFamily and either content_style or an external CSS file.
- Verified that the "Almarai" font is being fetched successfully from Google Fonts.
- Ensured there are no conflicting CSS rules in my project.
However, despite these efforts, the font is not applied to the content within the TinyMCE editor.

`editor.getBody().style.direction = "rtl";
    editor.getBody().style.fontFamily = "Almarai";`
    
the following style is being applied on the elemtn
`style attribute {
    direction: rtl;
    font-family: Almarai;
}
 `
 but still the actual look and feel is not as Almrai fonts
 

![image](https://github.com/tinymce/tinymce/assets/130146832/5621977d-1bcc-4036-8c91-b721e178e808)

if i locally installed the Almrai fonst into my machine then its giving the actual look and feel..what the issue?

**Comment by waseemViwell** [comment]
@TheSpyder thanks for your response.......i just added google fonts as content_css now its working fine

**Comment by TheSpyder** [comment]
Glad to hear it!
