### ISSUE TITLE
Paste removes text color, text background colour and underlining

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#901]
Description of problem:

Steps to reproduce:
1. Copy text from Word or from a website.
2. Paste text in Chrome.
3.
4.
5.

Expected result: All formatting should be transferred over.

Actual result: Colors and underlining aren't transferred.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6124](http://archive.tinymce.com/develop/bugtracker_view.php?id=6124) posted by [annan](http://archive.tinymce.com/profile.php?name=annan)_

> _**Tags:** [chrome paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
