### ISSUE TITLE
'@@@@' turns to a mail hyperlink on space/enter

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#902]
Description of problem:  Text automatically turns into a link.

Steps to reproduce:
1. Type a character followed by at least four at signs.
2. Press enter or space.
3.
4.
5.

Expected result: e.g. &ltg;p> a@@@@ &ltg;/p>

Actual result: &ltg;a href="mailto:a@@@@>a@@@@&ltg;/a>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6125](http://archive.tinymce.com/develop/bugtracker_view.php?id=6125) posted by [annan](http://archive.tinymce.com/profile.php?name=annan)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
