### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by roshan123456789** [tinymce/tinymce#9036]
placeholder is visible initially but when i route to other tab and comes to previous tab placeholder disappear but clicking on that particular editor where i added placeholder it shows placeholder.I want placeholder to be visible even if i reload or go from one tab to another.

 <Editor
              key={`subHeader-${editorKey}`}
              value={
                subHeaderFocus ? subHeaderValue : formField?.configs?.subHeader
              }
              id={`subHeader-${formField?.id}`}
              disabled={!isFieldActive}
              onInit={(_evt: any, editor: any) => (editorRef.current = editor)}
              tinymceScriptSrc={
                isWordPress
                  ? CDN_URL + '/tinymce/js/tinymce/tinymce.min.js'
                  : process.env.PUBLIC_URL +
                    '/tinymce/js/tinymce/tinymce.min.js'
              }
              toolbar={[
                'bold italic underline | fontsize | forecolor backcolor | alignleft aligncenter alignright alignfull',
                `outdent indent | customInsertButton ${
                  formField?.subType !== fieldTypes?.heading && !isWelcomeEnable
                    ? '| mydropdown '
                    : ''
                }| fontsizeselect | lineheight`,
              ]}
              onEditorChange={handleSubHeaderUpdate}
              onFocus={() => {
                setSubHeaderFocus(true);
              }}
              onBlur={() => {
                setSubHeaderFocus(false);
              }}
              
              init={{
                menubar: false,
                inline: true,
                plugins: 'paste',
                paste_as_text: true,
                fontsize_formats: ptList,
                lineheight_formats: lineHeightList,
                content_style: `p {
                 margin: 0;
               }`,
                placeholder:t(FormBuilderStrings.SUB_HEADER),
              }}
            />

I am using version 4.1.0

**Comment by roshan123456789** [comment]
I am using version 4.1.0

**Comment by mrinasugosh** [comment]
The issue you're describing where the placeholder disappears when you navigate away and return to the tab sounds like it might be related to a redraw or re-render behavior within TinyMCE and/or the surrounding React environment. I can't tell without more detail on how your code looks in the context of the project.

Things you could try:

1. **Use a State to Hold Placeholder Value:** Ensure that the placeholder value is being managed by the React state, and that it is being re-applied to the TinyMCE editor when the component is re-rendered.
```javascript
const [placeholder, setPlaceholder] = useState(FormBuilderStrings.SUB_HEADER);

// ... other code ...

<Editor
  // ... other props ...
  init={{
    // ... other init properties ...
    placeholder: placeholder,
  }}
/>
```

2. **Re-apply Placeholder on Editor Initialization:** You might want to use the `onInit` event to force the placeholder back into the editor.
```javascript
onInit={(_evt: any, editor: any) => {
  editorRef.current = editor;
  if (!editor.getContent()) {
    editor.getBody().setAttribute('data-placeholder', placeholder);
  }
}}
```
3. **Check for External CSS or JS Impacting Editor:** Ensure there are no external styles or scripts that might be hiding or altering the behavior of the placeholder in the TinyMCE editor.

4. **Check Routing Mechanism:** Depending on how you're handling routing (e.g., with React Router), it's possible that the component containing the TinyMCE editor is being unmounted and then re-mounted. If this is the case, it's crucial to ensure that any necessary state or properties are being correctly re-initialized when returning to the editor tab.

5. **Update TinyMCE Version:** Although you mentioned you are using version 4.1.0, it's worth considering updating to a newer version as this might contain fixes for various bugs and improved behavior for your project overall.

If after trying these suggestions, you're still experiencing issues, it might be worth creating a minimal reproduction case for us to play around with and better understand the problem (maybe on [fiddle](https://jsfiddle.net/)) or reaching out to the TinyMCE community on Discord for further assistance?
[TinyMCE Discord Sever](https://discord.gg/sugTfmjkXD)
