### ISSUE TITLE
Double clicks in empty area of menubar

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#904]
Description of problem:

A double-click in the empty area to the right of the menubar's Tools button ends up selecting (i.e., highlighting) the button's "Tools" text.

Expected result:

Double-clicks in that empty area of the menubar should have no effect on anything in the ui.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6127](http://archive.tinymce.com/develop/bugtracker_view.php?id=6127) posted by [jashua212](http://archive.tinymce.com/profile.php?name=jashua212)_

> _**Tags:** [firefox safari chrome 4x ui]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
