### ISSUE TITLE
Help Dialog, with custom content - height of dialog changes on subsequent opens

### ISSUE THREAD

**Issue by jxmot** [tinymce/tinymce#9045]
**What is the current behavior? Describe the bug**

I have created 2 custom tabs for the tinyMCE help dialog box. The content of one of the tabs is taller than the dialog and will scroll. However if the help dialog is opened again in the same active editor it will change to a taller height. And then if opened again it will return to the expected height.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Here is a fiddle that demonstrates the problem - https://fiddle.tiny.cloud/EPzwTvos1M/5

1) Load the fiddle
2) **Please be sure to arrange the code pane and output pane to be next to each other.** It is the only way this problem becomes visible.
3) Open the help dialog
4) Close the help dialog
5) Open the help dialog again - it is likely to be too tall now.

To get the dialog back to the correct height "run" the fiddle again. In the real-world the behavior alternates between subsequent openings of the help dialog.

**What is the expected behavior?**

The help dialog must be a fixed height. And should not change dynamically. This is correct, and expected - 

![image](https://github.com/tinymce/tinymce/assets/20270843/f0c2cc5e-f9c8-40f8-be7d-67b7bf578ecf)

Above is correct, however this is not - 

![image](https://github.com/tinymce/tinymce/assets/20270843/3adb74f2-471b-4e80-89a3-da2b39a4562b)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I am using 6.7, this occurs in all up-to-date browsers on Win10. It was not checked with any previous versions of TinyMCE

**Comment by jxmot** [comment]
In addition to the the changing dialog height it also appears that its height is somewhat governed by the height of the content. I added a tab that was taller than the others I made and now the dialog is too tall. It seems odd to me that this is not adjustable.

**Comment by TheSpyder** [comment]
That's by design. A dialog that changes height as you move between tabs is poor UX, so we measure all the tabs when the dialog opens and that is the size we use (up to a fixed max-height, which is defined in the skin).
https://github.com/tinymce/tinymce/blob/2434090ce7ebcd8ffabc54d25c753a05d187af60/modules/oxide/src/less/theme/components/dialog/dialog.less#L127
https://github.com/tinymce/tinymce/blob/2434090ce7ebcd8ffabc54d25c753a05d187af60/modules/oxide/src/less/theme/components/dialog/dialog.less#L247

I suspect the issue with your help dialog is the code not waiting for images to load. A race condition like that would explain why sometimes it's smaller than we expect it to be.

**Comment by jxmot** [comment]
@TheSpyder Thank you very much for your reply. 

All of the images I use are inline base64 and less than 8k in size. The problem has been the inconsistent behavior. It would be helpful if there was an init value that could be used for setting the maximum height of the dialogs. Also, the max height you're setting in the skins will be wrong depending on the surrounding HTML. For example, we have a fixed toolbar and occasionally followed by a status bar at the top of the browser window, their z-index is set to place them always "on top" all other elements. Let's say it's a 100px total height for the two.

Then when the jumping sized dialog appears the top of it gets cut off. 

This issue becomes a bigger problem when longer content is added to the help dialog. Then the height is always too much and visually the dialog looks awful. I think there should be an option for the dialogs that over rides the max height calculation.

At this time my solution has been to "watch" the dialog and "fix" its height as its being rendered. This works very well and solves the problem. However, a cleaner approach like an init setting is preferred.
