### ISSUE TITLE
Source code editing view does not use monospace font

### ISSUE THREAD

**Issue by ThiefMaster** [tinymce/tinymce#9056]
**What is the current behavior? Describe the bug**

When editing the raw HTML source in TinyMCE, it uses the default font.

**What is the expected behavior?**

A mono-space font is used, since this is what pretty much everyone expects and wants when it comes to editing HTML (or other source code).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest version (in my app and the demo on your site). No idea about previous versions. There's #629 but maybe it was just closed as 'complete' in a cleanup (since back then github didn't have different close reasons).

**Comment by ThiefMaster** [comment]
Looking at the current CSS it also seems to be pretty hard to work around this issue using custom CSS, since there's absolutely no class indicating what the dialog/textarea are about... `.tox-textarea` is very generic but maybe not too bad (since it targets both source editing and inserting source snippets - not sure if it's used anywhere else where you would not want monotspace)

**Comment by lostkeys** [comment]
Thanks for the feedback. I've added it to our internal feature tracker.
Cheers,

— Fredrik, Product Manager
