### ISSUE TITLE
Adjust font size then apply strikethough will show misaligned strike

### ISSUE THREAD

**Issue by bagaskarala** [tinymce/tinymce#9060]
**What is the current behavior? Describe the bug**
I cant use formatting using font size and striketrough consistenly. Because it behave differently, based on input order. If a adjust size then apply striketrough, somehow the strike line is above the font. But if i do apply strikethrough first, then adjust size, it will be expected result.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/2dcy69HbAC/0

Reproduce steps:
- block some word
- adjust font size
- apply strikethrough

**What is the expected behavior?**
Strikethrough will be center aligned within the text

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- tinymce 6.7.0
- using wrapper @tinymce/tinymce-vue: "^5.1.1"

Proof preview
<img width="347" alt="image" src="https://github.com/tinymce/tinymce/assets/14112952/62031493-f794-4148-a650-64fd8a88374d">

**Comment by TheSpyder** [comment]
This is not unique to TinyMCE; if you remove the editor it's just how browsers render that specific HTML.

https://fiddle.tiny.cloud/2dcy69HbAC/1

**Comment by bagaskarala** [comment]
> This is not unique to TinyMCE; if you remove the editor it's just how browsers render that specific HTML.
> 
> [fiddle.tiny.cloud/2dcy69HbAC/1](https://fiddle.tiny.cloud/2dcy69HbAC/1)

oh i see, but then how to handle this thing on tinymce? if i try merge the style in one span it will be normal, so how to apply this behavior in tinymce?

i want expected result should be this element, either adjust size then strike, or adjust strike then size

```
<span style="font-size: 24pt;text-decoration: line-through;">size then strike</span>
```

**Comment by bagaskarala** [comment]
oke i've found the workaround, by override default format style, from html tag to css style

```formats: {
    // Avoid default html issue
    // Changes the default format to be mergeable in one span element
    underline: {
      inline: 'span',
      styles: { 'text-decoration': 'underline' },
    },
    strikethrough: {
      inline: 'span',
      styles: { 'text-decoration': 'line-through' },
    },
    bold: {
      inline: 'span',
      styles: { 'font-weight': '700' },
    },
    italic: {
      inline: 'span',
      styles: { 'font-style': 'italic' },
    },
  }
```

it works, but i doubt whether this solution is the best approach, cmiiw

**Comment by TheSpyder** [comment]
That is a fair point, we should re-use span tags more often.

**Comment by lin0102** [comment]
@bagaskarala Merging style in one span element will result in the inability to set underline and strikethrough at the same time？

**Comment by lin0102** [comment]
@TheSpyder I think the key reason for this bug is adding a new layer of span for the format instead of how browsers present specific HTML.
