### ISSUE TITLE
Authorization for image requests on tinyMCE

### ISSUE THREAD

**Issue by danHumphreysCPL** [tinymce/tinymce#9067]
I'm using tinyMCE self hosted on a react site, and am uploading images embedded into the text (through the images plugin) to a backend rest API using the images_upload_handler. However when getting the images that I uploaded, I need to provide bearer authorization. Is it possible to add an authorization headers to image GET requests for images embedded inside the text?

**Comment by lobbo232** [comment]
If it was normal html img element, you could store the url in a data attribute and use onload to call a function that handles the request and can add headers to that request.

Is this something that anyone has accomplished with TinyMCE?
@TheSpyder could you offer any insight on this?

**Comment by lobbo232** [comment]
This is still an issue

**Comment by spocke** [comment]
I think this can be handled with cookies even if you use jwt tokens you can store that in a session cookie. That cookie will be sent on every request including image requests if it's a separate domain  then use cors headers.

**Comment by TheSpyder** [comment]
As a WYSIWYG editor we use plain `img` tags for images in the content. These do not provide a JavaScript API to add extra headers to the request. If we create an API to support rendering images with `fetch` requests that do have customisable headers, there would be two problems:

1. The server would need to allow this with CORS headers
2. The image would not work when the content is saved

It's not clear to me why this is a tinymce request. If you need the browser to send authorisation headers, you need them outside of tinymce as well.
