### ISSUE TITLE
Missing 'NewBlock' Event Trigger on 'Enter' in Last List Item: TinyMCE Styling Issue

### ISSUE THREAD

**Issue by martinkukucka** [tinymce/tinymce#9068]
**What is the current behavior? Describe the bug**
The "NewBlock" event doesn't trigger when the user presses "Enter" in the last empty list item, resulting in the loss of styling for a new paragraph block created.
It's peculiar that the "NewBlock" event is triggered when adding list items within the list, even though no new blocks are visible through the "View -> Show Blocks" option. However, when you exit the list by pressing "Enter" in the last empty list item to create a new paragraph, the "NewBlock" event doesn't fire, despite the presence of a visible new block.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
You can test it on the website https://fiddle.tiny.cloud/TV1MGKgNFT/0. 

Inspect (F12) -> Console to view when "NewBlock" event is triggered.

The content consists of an unordered list with proper styling, where the list items are correctly styled. However, when attempting to exit the list by pressing "Enter" in the last empty list item, styling is not preserved for a new paragraph block.
- Press Enter in the last empty list item - styling is lost. 
- Press Enter in the paragraph - a new paragraph is created with the style kept. 

**What is the expected behavior?**
"NewBlock" event is fired and styling is kept even when user presses "Enter" in the last empty list item.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I'm currently using:
- TinyMCE v6.7.0
- Google Chrome
- Windows 10 (64-bit)

I found this behavior even on the previous versions.

**Comment by TheSpyder** [comment]
Logically this is because the new block was already created, `li` elements are block tags just like the parent `ul` element. The enter action just converts the existing list item to a paragraph (the same happens if you decrease indent in the middle of a list). But maybe we should make it easier to detect this conversion.

**Comment by martinkukucka** [comment]
Thanks for your reply. 
It would be beneficial to either trigger a "NewBlock" event during the conversion process or create a new event specifically for this purpose. Alternatively keep styling after `li` to `p` conversion. I need to keep styling throughout the conversion process and I haven't find any workaround for this issue yet.
