### ISSUE TITLE
Setting the focus after init does not work with existing events

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#907]
Description of problem:
Giving an editor the focus after initialization seems not possible with the given events. I tried using onInit and onPostRender, but they are both fired to early to let a focus() call work. A workaround is waiting some time (with setTimeout), but the time needed depends on the speed of the browser/PC.

Steps to reproduce:
1. Click the init link
2. The editor gets the focus after 1000ms

The expectation is that the editor gets the focus right away (because of the first "editor.focus()", but that doesn't happen. Only the second call works after waiting some time. Actually I found no event that sounds right and works for this case. They are all called to early.

Either you could add an additional event that fires after everything is really finished, or you adjust the onPostRender event to get fired after the content of the editor is rendered too (that is what I expected at first).

Btw: Setting the focus during the init event used to work with version 3.5.8.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6142](http://archive.tinymce.com/develop/bugtracker_view.php?id=6142) posted by [Simon Brodtmann](http://archive.tinymce.com/profile.php?name=Simon Brodtmann)_

> _**Tags:** [firefox]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/ntdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by fabsn182** [comment]
What's going on here? Hundreds of closed issues, most of them with easy to reproduce descriptions. Yet all get marked "unable to reproduce". Srsly?

**Comment by jayarjo** [comment]
@fabsn182 can you reproduce this particular issue in the latest TinyMCE release?

**Comment by glevine** [comment]
http://fiddle.tinymce.com/cdgaab/1

That fiddle shows the bug in Firefox and IE. Change the version to 4.6.3 and the bug vanishes. So something in 4.6 fixed it.
