### ISSUE TITLE
Formatting changes does not appear where the cursor is placed

### ISSUE THREAD

**Issue by zyslsufin** [tinymce/tinymce#9072]
**What is the current behavior? Describe the bug**

The text is highlighted (selected) for formatting
Format is selected (e.g. Header 4) 
Highlighted text is not changed to the correct format, instead, a separate paragraph of text is changed to the selected format (Area where the option was selected)

Issue happens when tinymce configuration value inline is set to true.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

CodeSandbox for tinymce 5.10.7: https://codesandbox.io/s/tinymce-vue-forked-5j4zy3?file=/src/App.vue
CodeSandbox for tinymce 6.6.2: https://codesandbox.io/s/tinymce-vue-forked-gsryd6?file=/src/App.vue

**What is the expected behavior?**
The initially highlighted text should have been formatted.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
MacOS version 13.4
Safari version 16.5 (18615.2.9.11.4)
issue occurs on both tinymce 5.10.7/6.6.2

Issue seems to only affect safari.

**Comment by lostkeys** [comment]
I'm sorry but I cannot replicate this issue, formats applies just fine. Can you perhaps record your a screen to show the issue?

**Comment by zyslsufin** [comment]
Please refer to screen recording showing the issue below. Issue is not consistently replicable, and may require a few tries.

https://github.com/tinymce/tinymce/assets/133622472/6c9bd475-3134-4d54-9a61-dcc8ab7e31ae

**Comment by zyslsufin** [comment]
@lostkeys Were you able to replicate the issue with the help of the recording provided?
