### ISSUE TITLE
Firefox specific execCommand no longer needed

### ISSUE THREAD

**Issue by johanneswilm** [tinymce/tinymce#9078]
Hey,
Firefox stopped requiring disabling controls five years ago [1]. So you are now able to remove your last usages of `document.execCommand` for things like "enableInlineTableEditing" or "enableObjectResizing".

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1490641

**Comment by spocke** [comment]
Thanks for pointing that out will see if we can clean that up.
