### ISSUE TITLE
Default value for `table_style_by_css` is not `false`

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#9084]
**What is the current behavior? Describe the bug**
The documentation states the the default value for [`table_style_by_css`](https://www.tiny.cloud/docs/plugins/opensource/table/#table_style_by_css) is `false`.

However, when I test in TinyMCE Fiddle, side-by-side, I see that if I set the `table_style_by_css` to `false` I get a different output in the source than if I omit setting the `table_style_by_css` option.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Create a table and check the output without setting the `table_style_by_css` to anything and the output will be:
```html
<table style="border-collapse: collapse; width: 100%; border-width: 0px;" border="1">
```
Set the `table_style_by_css` option to `false` and the output will be:
```html
<table style="border-collapse: collapse;" border="0" width="100%">
````

https://fiddle.tiny.cloud/olwaiIqA7y/0 (without `table_style_by_css` set)
https://fiddle.tiny.cloud/olwaiIqA7y/1 (with `table_style_by_css` set to `false`)

**What is the expected behavior?**
Not sure, but it the documentation says that the default value is `false` then setting it to `false` ought to behave the same way as not setting it at all.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
6.7.0
I could reproduce with Firefox and Edge.
Yes, this worked fine in version 6.0.3. This unexpected behavior occurs in version 6.1.0 and later.
The changelog for version 6.1.0 mentions:
> Changing table properties with the `table_style_by_css` option set to `false` would sometimes reset the table width.

**Comment by TheSpyder** [comment]
You've linked to the version 5 docs. It was changed to `true` by default in v6:
https://www.tiny.cloud/docs/tinymce/6/table/#table_style_by_css

And this is listed in the release notes, although quite a lot changed so it's a bit buried:
https://www.tiny.cloud/docs/tinymce/6/6.0-release-notes-core-changes/#default-value-changes
