### ISSUE TITLE
Toolbar standard collapsed with fixed_toolbar_container

### ISSUE THREAD

**Issue by kylianleem** [tinymce/tinymce#9103]
**What is the current behavior? Describe the bug**
When im having a inline editor and have the default toolbar set to another div with fixed_toolbar_container. When the toolbar opens in the different div its always standard collapsed(with 3 dots to uncollapse it) but I need it to be standard to uncollapsed. Is there any settings to uncollapse it automatically?

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/jrk9Y3eRlk/1
1. Click on "Click here to open toolbar"
2. The toolbar in the new toolbar div is standard collapsed

**What is the expected behavior?**
Want the toolbar to be standard uncollapsed in the fixed toolbar container.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Im using tinymce version 6 havent seen it work in other version

**Comment by TheSpyder** [comment]
You're probably looking for `toolbar_mode` https://www.tiny.cloud/docs/tinymce/6/toolbar-configuration-options/#toolbar_mode

https://fiddle.tiny.cloud/jrk9Y3eRlk/2

**Comment by kylianleem** [comment]
@TheSpyder this was exactly what I was looking for thanks
