### ISSUE TITLE
how to use `oembed` media tag?

### ISSUE THREAD

**Issue by bang-star** [tinymce/tinymce#9106]
**What is the current behavior? Describe the bug**

I has a free 14-day Cloud trial. 
I try to check `oembed` tag active on `Enhanced Media Embed plugin`.

In shortly, `oembed` tag disappeared. 

No additional cloud settings were made. I would like to connect media links(`oembed tag`) using only tiny-cloud.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

it is test environment link [codepen](https://codepen.io/fuckingbang/pen/jOdEawM).

**What is the expected behavior?**

I would like to create an environment where the `oembed` tag can be used and freely used with the `iframe` tag.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by TheSpyder** [comment]
oembed is not a tag, it's a standard:
https://oembed.com/

If you paste any URL into the editor with the enhanced media embed plugin it will be transformed into a rich link. Try pasting a link to this issue, for example.

**Comment by bang-star** [comment]
@TheSpyder 

I tried many tests by inserting data with the `oembed` tag into the content, but `tiny editor` has logic that deletes the corresponding code.

```
// input content 
<figure class="media media-outer">
  <oembed id="media-inner" url="https://tv.kakao.com/v/438817463"></oembed>
</figure>
<figure class="media">
  <oembed url="https://tv.kakao.com/channel/3861791/cliplink/438900258"></oembed>
</figure>
<figure class="media">
  <oembed url="https://youtube.com/watch?v=6WPUQKBRGLw&amp;ab_channel=한그루"></oembed>
</figure>

// active code
<figure class="media">
</figure>
<figure class="media">
</figure>
<figure class="media">
</figure>
```1
