### ISSUE TITLE
Can't insert a paragraph before a non-editable area at start of document

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#911]
Description of problem:

If insert a non-editable area at the start of the document then try to insert an empty paragraph before it, the empty paragraph gets collapsed even though it is in the DOM. (Only occasionally happens in Opera. I couldn't reproduce this in IE10.)

Steps to reproduce:

1. Goto the TinyMCE non-editable content demo

2. Copy and paste a non-editable area from the text so that it is the first content in the text. Ensure that the text is actually non-editable.

3. Move the cursor to the beginning of the line and press [Enter]

Expected result:

The text should move down and an empty paragraph should be displayed at the start of the text.

Actual result:

The text does initially move down, but then it collapses.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6134](http://archive.tinymce.com/develop/bugtracker_view.php?id=6134) posted by [mstrong](http://archive.tinymce.com/profile.php?name=mstrong)_

> _**Tags:** [firefox safari chrome opera noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/3_x/noneditable_content.php_

**Comment by bszypelow** [comment]
Any chance of fixing this?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
