### ISSUE TITLE
Lite YouTube Embed is not supported

### ISSUE THREAD

**Issue by gavriel-adi** [tinymce/tinymce#9112]
Hi I work with the plugin: Lite YouTube Embed https://github.com/paulirish/lite-youtube-embed
And I'm trying to get to the point where I can integrate the code of the plugin to display videos in a high-quality way as follows (as an HTML tag):
`<lite-youtube videoid="QL7sER7ufPk"></lite-youtube>`
But for some reason every time I put this code into a rich text editor TinyMCE it is not saved well in a database because it is processed by your code and saved like this: `<p>&nbsp;</p>`
, I would like to know if there is a way to make the code of the text editor not touch a specific code that starts with the `<lite-youtube>` tag?

I must point out that the first time the code was saved like this:
`<p><span class="html-tag"><lite-youtube <span class="html-attribute-name">videoid</span>="<span class="html-attribute-value">Kj3RN8GUnm4</span>"></span><span class="html-tag"></lite-youtube></span></p></div>`

And the second time I save this already saved code, it is saved like this:
`<p><span class="html-tag"><lite-youtube>videoid</lite-youtube></span>="<span class="html-attribute-value">Kj3RN8GUnm4</span>"></p>`

Instead the code will be saved like this:
`<lite-youtube videoid="RHoPR24COHU"></lite-youtube>`

I am using the latest version 6.7.0

**Comment by TheSpyder** [comment]
If you use the github editor to mark those tags as code it would be easier to see what you are trying to describe.

Our config does allow defining custom elements, although for your use case they won't be very easy to manipulate in the content. It's designed for elements that contain text or other elements.
https://www.tiny.cloud/docs/tinymce/6/content-filtering/#custom_elements

Adding this to the config will at least allow your example to work without deleting the elements:
```
	custom_elements: "lite-youtube",
	extended_valid_elements: "lite-youtube[videoid]",
```

**Comment by gavriel-adi** [comment]
I already tried it and it saves this code that I put:
`<lite-youtube videoid="Kj3RN8GUnm4"></lite-youtube>`
so:
`<p><span class="html-tag"><lite-youtube <span class="html-attribute-name">videoid</span>="<span class="html-attribute-value">Kj3RN8GUnm4< /span>"></span><span class="html-tag"></lite-youtube></span></p></div>`
Which means it adds and changes the entire structure of the code
