### ISSUE TITLE
How can i control br tag?

### ISSUE THREAD

**Issue by bang-star** [tinymce/tinymce#9114]
** environment
- tiny MCE v5

**What is the current behavior? Describe the bug**

The data was set as follows.
```
const content = `
<blockquote>
   <p>ABCDEF
       <br>  ABCDEF
   </p>
</blockquote>
`;
```

converted html
```
<blockquote>
   <br>
   <p>ABCDEF
       <br>  ABCDEF
   </p>
   <br>
</blockquote>
```

I want to remove additional br tags.

**What is the expected behavior?**

In the official document, it was possible to remove the trailing br tag using `remove_trailing_brs`.

However, I don't know how to remove the br tag created in front.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I try to edit init options.

```
force_br_newlines : false,
forced_root_block: ''
```

but I cant solve it.

**Comment by bang-star** [comment]
@TheSpyder help me.

**Comment by TheSpyder** [comment]
TinyMCE 5 is [no longer supported](https://www.tiny.cloud/blog/tinymce-end-of-support/). Don't ping me just because I respond to a lot of issues.
