### ISSUE TITLE
on selecting a text font colour and font background is not reflecting in the toolbar

### ISSUE THREAD

**Issue by dchandramohanan** [tinymce/tinymce#9119]
<img width="656" alt="Screenshot 2023-10-26 at 8 15 49 PM" src="https://github.com/tinymce/tinymce/assets/149086190/190170a7-e302-4dc6-9033-3dbd5299286f">

In the Text Editor when a text with some styles is selected the style font colour and background colour is not getting reflected in the toolbar . The styles like bold, italic, alignment etc are getting reflected. This issue is available in 6.6.2 version. Please use the below link reproduce the issue. In the attached screen shot even though the selected text is in red with green background in the toolbar it is shown as blue text with black background

https://fiddle.tiny.cloud/kYezcadwkM/2

**Comment by TheSpyder** [comment]
The line under the icon does not update as the cursor moves. It reflects the last colour chosen in the colour picker.

The colour buttons are split buttons; if you click the arrow it shows the picker, if you click the icon it applies the colour shown. This behaviour wouldn't make sense if the colour reflected the cursor context.
