### ISSUE TITLE
jQuery UI dialog under Tinymce dialog 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#912]
Description of problem:
If you use jQuery UI and you add your own plugins (for ex : a file manager) with dialog popup creates with jQuery UI, dialog appears under tinymce dialog.

Steps to reproduce:
1. Add link or Insert image (open tinymce dialog)
2. On filepicker button open a jQuery UI dialog
3. Dialog appaears under overlay and tinymce dialog

z-index used by tinymce is 65535 and more
z-index used by jQuery UI is 100

If on tinymce code replace 0xFFF by 99, it's works. But in fullscreen mode menu on menubars doesn't show !

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6135](http://archive.tinymce.com/develop/bugtracker_view.php?id=6135) posted by [btr](http://archive.tinymce.com/profile.php?name=btr)_

> _**Tags:** [firefox 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
