### ISSUE TITLE
Non-editable area unexpectedly deleted

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#913]
Description of problem:

Steps to reproduce:
1. Go to the TinyMCE Noneditable Content example (URL above)
1. Click on the Html link and paste in the following HTML:

&ltg;p>&ltg;/p>
&ltg;p>&ltg;span id="1" class="mceNonEditable">[non editable]&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span id="2" class="mceNonEditable">[non editable]&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span id="3" class="mceNonEditable">[non editable]&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span id="4" class="mceNonEditable">[non editable]&ltg;/span>&ltg;/p>
1. Move the cursor to the first character in the text and press [Delete]

Expected result:

The empty paragraph is deleted and the first non-editable area moves to the top of the editor.

Actual result:

A new empty paragraph is inserted, the first non-editable area is deleted, and the other non-editable areas are moved up in the editor.

If you view the html after hitting the [Delete] key you will see the following html:

&ltg;p>&nbsp;&ltg;/p>
&ltg;p>&nbsp;&ltg;/p>
&ltg;p>&ltg;span id="2" class="mceNonEditable">[non editable]&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span id="3" class="mceNonEditable">[non editable]&ltg;/span>&ltg;/p>
&ltg;p>&ltg;span id="4" class="mceNonEditable">[non editable]&ltg;/span>&ltg;/p>

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6136](http://archive.tinymce.com/develop/bugtracker_view.php?id=6136) posted by [mstrong](http://archive.tinymce.com/profile.php?name=mstrong)_
> 
> _**Tags:** [firefox msie safari chrome opera noneditable]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/3_x/noneditable_content.php_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
