### ISSUE TITLE
unable to insert image from custom filemanager

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#914]
Description of problem:
Hello, am having the following errors when am trying to insert an image from my custom filemanager, where the image is already uploaded to my server, but not yet added to my content text area:

TypeError: t.baseURI is undefined
http://www.example.com/lib/tinymce4/plugins/compat3x/tiny_mce_popup.js
Line 45

TypeError: this.params is undefined
http://www.example.com/lib/tinymce4/plugins/compat3x/tiny_mce_popup.js
Line 108

Any fix for this?

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6141](http://archive.tinymce.com/develop/bugtracker_view.php?id=6141) posted by [lordrt](http://archive.tinymce.com/profile.php?name=lordrt)_
> 
> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
