### ISSUE TITLE
Switching from Rich Text editor to Raw HTML messes up the formatting

### ISSUE THREAD

**Issue by MaximilianKohler** [tinymce/tinymce#9146]
It's the [TinyMCE 5.10.7](https://www.tiny.cloud/docs/changelog/?utm_campaign=editor_referral&utm_medium=help_dialog&utm_source=tinymce) version integrated into this open-source app: https://demo.listmonk.app/admin/campaigns/2 - click "content" tab.

When switching from "rich text" to "raw html" it messes up the formatting:
Before:
![before](https://github.com/tinymce/tinymce/assets/3606996/a4a86197-32f5-4748-899a-7617a0acfaf5)
After:
![after](https://github.com/tinymce/tinymce/assets/3606996/74e0f495-ef09-4689-a7df-d089f18ed8e1)

The same thing happens when you "indent the raw HTML" with https://htmltidy.net/.

EDIT: I think it might be caused by indenting lines with spaces, and thus might be remedied by using tabs instead? And/or it could be remedied by changing/reducing which HTML tags get put on their own line?

**Comment by MaximilianKohler** [comment]
I do think it's an important thing to fix if possible.

**Comment by TheSpyder** [comment]
TinyMCE 5 is no longer supported, for the record, but the listmonk "raw html" feature is not using TinyMCE at all.

The campaign you posted doesn't work anymore, but looking at the screenshot and the indent feature of htmltidy you're likely using tools that don't properly consider the [HTML whitespace collapsing rules](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace).

Tools that split a `span` tag into multiple lines and indent the contents are quite likely to cause content changes such as the one in your screenshot.
