### ISSUE TITLE
TinyMCE spellchecker failed to load url 

### ISSUE THREAD

**Issue by waseembaig786** [tinymce/tinymce#9149]
I am using TinyMCE 6.1 premium account in my ASP.net core project but I am having an issue in TinyMCE 6.1 spellchecker plugin is not loading when I try to check the spellings are right or wrong they give me an error in console.
Here in my screenshot you can see that:
![image_2023_11_10T07_54_34_539Z](https://github.com/tinymce/tinymce/assets/150443773/0ac3b66b-9f73-4954-a6d8-ab26130f695f)
![image_2023_11_10T07_55_13_414Z](https://github.com/tinymce/tinymce/assets/150443773/ff6e1b58-0010-4bfd-b56c-91e18d12c45c)
Even I give the path of my spellchecker plugin.js file in the **spellchecker_rpc_url** with ~ sign and without ~ sign but it's not working and also you can see the tinymcespellchecker folder in my directory and when I give this path in my initialization code path not found error in console and also add at the end of path **/2/check** added to my given path in **spellchecker_rpc_url**  I don't where it comes from.
![Screenshot_6](https://github.com/tinymce/tinymce/assets/150443773/222ef2b7-cb5a-459b-97a8-9cf8d2906151)
![Screenshot_5](https://github.com/tinymce/tinymce/assets/150443773/afa2ba8e-eacf-471d-917a-b09813acff26)
![Screenshot_3](https://github.com/tinymce/tinymce/assets/150443773/750fe68f-7e34-4475-afaf-e2e1363af23c)
![Screenshot_4](https://github.com/tinymce/tinymce/assets/150443773/4e24272e-0a60-431f-8019-daf08691aec4)

**Comment by TheSpyder** [comment]
We do not offer premium support via GitHub. If you have a support subscription, you will be better served by our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new

**Comment by waseembaig786** [comment]
@TheSpyder I post the ticket on the link you mentioned above.
Here is the link where I posted the ticket:
https://support.tiny.cloud/hc/en-us/requests

**Comment by TheSpyder** [comment]
Yes and you had a response about 3 hours later!
