### ISSUE TITLE
Windows Chrome 119 - super long load times

### ISSUE THREAD

**Issue by jasonwuwrf** [tinymce/tinymce#9151]
**What is the current behavior? Describe the bug**
On Chrome 118 (and Edge 119) Editor takes multiple minutes (~5)  to load into the page.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
When loading a page in Windows Chrome 118 it loads quick and snappy as always.  When on Windows Chrome 119 the problem begins, where the page loading "spins" and the editor will not load for several minutes. It eventually will load, but it takes as long as 5 or 10 minutes sometimes. The browser tab will hand and be unresponsive, which sometimes cause a "wait/no wait" dialog to presented to the user. If you continue to wait it will eventually load.

**What is the expected behavior?**
Quick and snappy editor loading in a couple of seconds, like it did on <v118.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Initially, I was using 5.9.2 and upgraded then to 6.7.2 and both are presenting the problem.

Windows 11
Chrome Version 119.0.6045.124 (Official Build) (64-bit)
Microsoft Edge | 119.0.2151.58 (Official build) (64-bit)

**Comment by jasonwuwrf** [comment]
My initialization of the editor on the page.  

```
tinymce.EditorManager.init({
  selector : ".mceEditor",
  theme: 'silver',
  //plugins: 'code searchreplace link table charmap pagebreak nonbreaking anchor insertdatetime advlist lists wordcount',
  toolbar1: 'code | formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
  image_advtab: true
});
```

**Comment by jasonwuwrf** [comment]
FireFox does not have this problem on Windows.

**Comment by jasonwuwrf** [comment]
No change in performance when call is made:

```
tinymce.EditorManager.init({
  selector : ".mceEditor",
  //theme: 'silver',
  //plugins: 'code searchreplace link table charmap pagebreak nonbreaking anchor insertdatetime advlist lists wordcount',
  //toolbar1: 'code | formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
  //image_advtab: true
});
```

**Comment by TheSpyder** [comment]
I can't reproduce this on https://fiddle.tiny.cloud/ - are you able to replicate it there?

Note that you don't need to use `tinymce.EditorManager.init`, simply `tinymce.init` is enough (they're the same function reference).
