### ISSUE TITLE
Tinymce doesn't work on Firefox and Chrome 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#917]
Tinymce doesn't work on Safari 17 and Google Chrome, while it works on IE10.
My code is:
&ltg;script type="text/javascript" src="../tinymce/js/tinymce/tinymce.min.js">&ltg;/script>
&ltg;script type="text/javascript">
tinymce.init({
	language: "it",
    selector: "textarea",
    theme: "modern",
	force_br_newlines : true,
    force_p_newlines : false,
	forced_root_block : '', 

    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor moxiemanager"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    templates: [
        {title: 'Test template 1', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ]
});
&ltg;/script>
&ltg;!-- /TinyMCE -->

Text area become invisible.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6139](http://archive.tinymce.com/develop/bugtracker_view.php?id=6139) posted by [kageja](http://archive.tinymce.com/profile.php?name=kageja)_

> _**Tags:** [firefox chrome firefox chorme issue]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
