### ISSUE TITLE
<details> HTML Element Selection in Chromium-based browsers

### ISSUE THREAD

**Issue by tamasszitas** [tinymce/tinymce#9175]
**What is the current behavior? Describe the bug**

If you insert a `details` HTML Element in the Source Code Editor view and switch back to the editor, you can only select the `<details>` element but not any elements before or after if you start the selection inside the `<details>` element.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

It is reproducible on the official TinyMCE website with the example editor:
- Open the Source Code view
- Insert a `<details>` Element, e.g. 

< details>
< summary>Click Me< /summary>
< p>This is my content.< /p>
< /details>

Just remove spaces after the opening  `<` tags.

- Start the selection with `Click Me` and move your mouse to the paragraph above.
- Only `Click Me` will be selected.
- If you try to do the selection via Shift + Arrow-Up / Down, the next line above / below `Click Me` will be selected, but the selection does not continue afterward.

**What is the expected behavior?**

Elements should be able to get selected outside the `<details>` element as well. The selection works as expected in Firefox.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- We are using 6.7.2 in our project. I have no information about how the selection worked in previous versions.
- The bug is present in Google Chrome and Microsoft Edge but works perfectly in Firefox.

**Comment by noraab** [comment]
Hi @lostkeys , any update on this or any plan to get this fixed somehow?

**Comment by TheSpyder** [comment]
Are you using the accordion plugin? It adds some extra details-specific handling such as a button to toggle whether the details element is expanded.
https://fiddle.tiny.cloud/iEXZIyIg5r/1

This doesn't fix your selection concerns, but that's a browser bug. Here's what it looks like without any JS at all.
https://codesandbox.io/p/sandbox/frosty-wood-d6n6g3

**Comment by noraab** [comment]
Thanks for your reply @TheSpyder and the clarification, that this is a browser bug. I guess there is no chance that a workaround will be implemented from TinyMCE side?

**Comment by TheSpyder** [comment]
@noraab In my experience attempts to force browsers to apply native selection that they don't support directly is a recipe for weird bugs and unwanted behaviour. Sorry.

You're welcome to try [logging a bug with the Chromium project](https://www.chromium.org/for-testers/bug-reporting-guidelines/).
