### ISSUE TITLE
model.min.js:9  Uncaught TypeError: Cannot read properties of undefined (reading 'add')

### ISSUE THREAD

**Issue by derricka-lau** [tinymce/tinymce#9187]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.

*What is the expected result of the above steps?*

### ❌ Actual result
*What is the actual result of the above steps?*

model.min.js:9  Uncaught TypeError: Cannot read properties of undefined (reading 'add')
    at model.min.js:9:96585
    at model.min.js:9:96617
    
  Error occurs here
  e.add("dom", (e=>({
        table: Rd(e)
    })))

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: …
- OS: …
- First affected version: …
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Try clearing your browser caches. That `add` method should exist if TinyMCE is up to date - although I'm not sure why `model.min.js` even downloads if it's not.

Either way clearing caches is definitely the first thing to try.

**Comment by derricka-lau** [comment]
Thanks! Clearing cache works but it still happens randomly.

**Comment by TheSpyder** [comment]
Hmm. That suggests a potential race condition. If you ever notice a pattern to this issue, please let us know!
