### ISSUE TITLE
Types related to EditorConfig are not exported

### ISSUE THREAD

**Issue by franklbt** [tinymce/tinymce#9191]
**What is the current behavior?**

I have a method implemented in a typescript component file to get the init configuration object used to initialize editor component.

```ts
getInitOption() : Partial<EditorOptions> { 
   return {
        toolbar_sticky: true,
        menubar: false,
        branding: false,
        statusbar: false,
        contextmenu: [],
        toolbar_mode: ToolbarMode.Wrap,
        setup: (editor) => { /* ... */ },
      };
}
```

The problem is that certain types are not accessible from my component.
For example the `ToolbarMode` enum is not usable, and if I replace by its value (`wrap`) it says that types are incompatibles (`Type string is not assignable to type  ToolbarMode `).

Also the `MenuButtonItemTypes` type that i use to configure additional buttons cannot be used.

**What is the expected behavior?**

The types used by EditorConfig are accessible.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**

TinyMCE: 6.6.2
TinyMCE-Angular 7.0.0
Browser / OS : all
Did this work in previous versions ? I don't know

**Comment by danoaky-tiny** [comment]
`EditorOptions['toolbar_mode']` is is a union of the enum `ToolbarMode`'s values. TinyMCE version 6 should reflect this

**Comment by TheSpyder** [comment]
As @danoaky-tiny said it's not difficult to access the enum with modern TypeScript. We've decided not to add a direct export.

This works:
```
import { EditorOptions } from 'tinymce';
type ToolbarMode = EditorOptions['toolbar_mode'];
const mode: ToolbarMode = 'wrap';
```
