### ISSUE TITLE
Tinymce 6.8.0 querySelectorAll is not a valid selector

### ISSUE THREAD

**Issue by xibieni** [tinymce/tinymce#9201]
There is an error in my electron client page.
Failed to execute 'querySelectorAll' on 'Element': 'map:not(svg map), canvas:not(svg canvas).....' is not a valid selector.
It can only work in chrome with version higher than 88.x.
https://developer.mozilla.org/zh-CN/docs/Web/CSS/:not

**Comment by TheSpyder** [comment]
As [noted in our documentation](https://www.tiny.cloud/docs/tinymce/6/support/#supported-web-browsers-table) the oldest version of Chrome we support is extended stable. That is currently [`118.0.5993.129`](https://chromereleases.googleblog.com/2023/11/extended-stable-channel-update-for.html).

Sorry.

**Comment by dertuxmalwieder** [comment]
FYI, this problem **also** occurs when TinyMCE is initialized with `promotion: false`. Seems like it **needs** an image tag somewhere.

**Comment by TheSpyder** [comment]
To add more detail, TinyMCE 6.8 allows `svg` elements to be configured as valid content elements. This required a lot of internal changes for edge cases with SVG enabled.

One of those fixes was to make sure links inside SVG elements were not picked up by our block link code:
https://github.com/tinymce/tinymce/pull/9069

This happens any time content is parsed, the editor configuration has no effect on whether this code is run.

We were not aware that this use of the `:not` selector required Chrome 88, but as that's no longer a supported browser we aren't going to fix it. Why are you still using such an old version of Chrome? Version 88 was released nearly 3 years ago.

**Comment by dertuxmalwieder** [comment]
Nobody in my company uses an old Chrome anymore, so that's not the only reason, it seems. As far as I understand, my colleague uses both Edge and a "new" Chrome, but I'll ask him tomorrow. Anyway, I *could* reproduce (in the newest Windows 10 Edge) that the error goes away if you had `promotion: false` in the editor configuration and you remove that. Not sure why yet.

**Comment by TheSpyder** [comment]
That might be a different error 🤔

**Comment by dertuxmalwieder** [comment]
That's what I meant to say. But the error message is the same, so I thought it'd fit here.

**Comment by dertuxmalwieder** [comment]
Turns out that his Windows, indeed, had an older version of Edge ("86") and did **not** find an update. Please just ignore my report. 🙄
