### ISSUE TITLE
Tinymce 5.10.8 'unsafe-inline' with 'style-src'

### ISSUE THREAD

**Issue by SubrotoWipro** [tinymce/tinymce#9205]
## 📝 Provide detailed reproduction steps (if any)

1. We are using Tinymce 5.10.8 in React code. We have 'unsafe-inline' disabled for 'style-src' in content security policy headers. In the browser when we are editing the text inside the Tinymce editor, the original formatting is lost i.e., font, font-style, color, etc are lost. We noticed that there is an error coming inside the Tinymce.js file. The error is happening in a line where innerHTML is being set. Please find attached a screenshot from ‘Tinymce.js’ file highlighting the line where error is occurring.
![Error screenshot Tinymce](https://github.com/tinymce/tinymce/assets/152352339/3f68de90-5f98-49f8-bf75-45b6bbe79a19)

### ✔️ Expected result
We should be able to edit the text in Tinymce text editor with the original formatting being retained. 

### ❌ Actual result
When we are editing the text inside the Tinymce editor, the original formatting is lost i.e., font, font-style, color, etc are lost. We noticed that there is an error coming inside the Tinymce.js file. 

### ❓ Possible solution
Can you please let us know if there is any way to mitigate this in 5.10.8 version or any upcoming versions will address this issue automatically. 

## 📃 Other details
- Browser: Chrome, Edge
- OS:Windows
- First affected version: 5.10.8 (previous versions may be affected too)
- Worked in version: 5.10.8

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mkzhx** [comment]
@SubrotoWipro `style-src 'self' 'unsafe-inline' *.tinymce.com *.tiny.cloud;` is one of the CSP directives required for TinyMCE to function. We do not support having `unsafe-inline` disabled for `style-src` in content security policy headers. Here are the associated docs for [5.x](https://www.tiny.cloud/docs/advanced/security/#configuringcontentsecuritypolicycspfortinymce) and [6.x](https://www.tiny.cloud/docs/tinymce/6/tinymce-and-csp/#configuring-content-security-policy-csp-for-tinymce). Let me know if you have further questions, thanks.

**Comment by SubrotoWipro** [comment]
@mkzhx, thanks for response. Can you kindly suggest, if Professional/Enterprise edition will support the 'unsafe-inline' disabled for 'style-src'. Thanks.

**Comment by lostkeys** [comment]
Hi @SubrotoWipro. The professional and enterprise versions of TinyMCE are the same as the open source version in this regard.

— Fredrik, Product Manager
