### ISSUE TITLE
event_root option appears to be misconfigured

### ISSUE THREAD

**Issue by helious** [tinymce/tinymce#9218]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.
1. Use `event_root` option
2. See a warning when Editor is initialized saying `event_root` should be an `object`

### ✔️ Expected result
*What is the expected result of the above steps?*
Able to use the `event_root` option without seeing a warning on initialization of the Editor

### ❌ Actual result
*What is the actual result of the above steps?*
We see a warning that `event_root` needs to be configured as an `object` on initialization of the Editor

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*
I believe that we just need to change the configuration of the `event_root` option from `object` to `string` over here:
https://github.com/tinymce/tinymce/blob/454de9339c02b958ad451ac7daa2afd417bf5cb5/modules/tinymce/src/core/main/ts/api/Options.ts#L358-L360

## 📃 Other details
- Browser: Chrome
- OS: MacOS
- First affected version: Since introduced?
- Worked in version: Never?
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Ah yeah the types define it as `string` but it had the wrong processor attached to it. Nice catch!

**Comment by shanmen-tiny** [comment]
Hi @helious, thank you for reporting. The fix will be available in the next release.
