### ISSUE TITLE
the ai assistant  generate code can‘t show properly

### ISSUE THREAD

**Issue by cha80** [tinymce/tinymce#9219]
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by cha80** [comment]
> If you'd like to see this fixed sooner, add a 👍 reaction to this post.

![IMG_2859](https://github.com/tinymce/tinymce/assets/56351661/134a384a-8ac3-4daf-88dd-1b12c1d88f04)
![IMG_2858](https://github.com/tinymce/tinymce/assets/56351661/571ca42d-99d4-4b6a-8625-775e7a49ce4a)

**Comment by cha80** [comment]
it not code block

**Comment by lostkeys** [comment]
Hi @cha80, 
Unfortunately TinyMCE does not support inserting Markdown codeblocks at this time. We'll add this as a feature request to consider for future improvements. 

— Fredrik, Product Manager
