### ISSUE TITLE
The 'Current window' option for links does not work on version 5.10.5 of tinyMCE. Links are not gettting clicked.

### ISSUE THREAD

**Issue by pmestry25** [tinymce/tinymce#9223]
## 📝 Provide detailed reproduction steps (if any)
1. In the toolbar of the rich text editor of tinyMCE, click on the link option
2. In the opened popup, fill the required fields and select 'Current window' option  in the 'Open link in ..' dropdown
3. click on save
4. Now, click on the link...Nothing happens
5. Now CTRL + click on the link...link opens in a new browser tab

### ✔️ Expected result
A link should be clickable and should open in the current browser window when they have the 'Current window' option selected in the hyperlink editor while adding a link.

### ❌ Actual result
After adding a link in tinyMCE editor by selecting a 'Current window' option from the link popup, when we click on it nothing happens. But when we do CTRL + click, the link always opens in a new browser tab.

## 📃 Other details
- Browser: All
- OS: All
- First affected version: 5.10.5

This bug is also reproducible on the latest version of TinyMCE 6.

**Comment by TheSpyder** [comment]
Are you talking about clicking links while the editor is open? We never open those in the current window because that might cause the content you are editing to be lost.

**Comment by pmestry25** [comment]
Yes...as per the option "Current Window" we expect the link to open in the current window.  

If it is a cautious call taken not to open the link in the current window then it would be helpful if you explain the purpose or the expected behavior of the "Current Window" option available in the link popup under 'Open link in ..'.

<img width="476" alt="Screenshot 2023-12-08 at 10 14 45 AM" src="https://github.com/tinymce/tinymce/assets/24245678/99575e3b-45a8-4131-bf95-7dca965f9f80">


There is no documentation available that explains this option's expected behavior very well.

> Are you talking about clicking links while the editor is open? We never open those in the current window because that might cause the content you are editing to be lost.

**Comment by lostkeys** [comment]
Hi @pmestry25, The purpose is to allow control how links are opened when the HTML is published and viewed outside of TinyMCE, like in a CMS. Setting new window adds `target="_blank" ` to the link, and setting current window removes it. Links inside TinyMCE will always open in a new window because of the risk @TheSpyder mentions above.
