### ISSUE TITLE
Missing German translation for redo icon tooltip.

### ISSUE THREAD

**Issue by gabrieldominguezduran** [tinymce/tinymce#9232]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.
1. Place the cursor over the redo icon to display the tooltip.

### ✔️ Expected result
*What is the expected result of the above steps?*
The tooltip should display "Wiederholen" when the application's language is set to German.

### ❌ Actual result
The tooltip displays "Redo".
![image](https://github.com/tinymce/tinymce/assets/25334605/0ca2bad1-f37c-4024-abf6-de090fba17a6)
In the undo icon, the tooltip display correctly:
![image](https://github.com/tinymce/tinymce/assets/25334605/63e54bb9-7d1a-4833-8368-affc98d9d0d7)

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*
Please add the correct German translation for the tooltip.
## 📃 Other details
- Browser: …
- OS: …
- First affected version: V6
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Open source translations are a community effort. Our status page shows german at 100%:
https://www.tiny.cloud/get-tiny/language-packages/

Please try downloading it again.

**Comment by gabrieldominguezduran** [comment]
Thank you for the answer and the link, I'll check them out.
