### ISSUE TITLE
Text doesn't wrap to next line on iOS 6

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#926]
Description of problem:
On iOS 6, text runs past the right side of the editor and causes its width to expand rather than word-wrapping. This continues until you press enter. Note: I am not including any spaces; it's one continuous string. 

Also, after pressing enter, the focus isn't given to the new line until you start typing again.

Steps to reproduce:
1. Type continuous text to the right side of the editor

Expected result:
Text wraps to the next line.

Actual result:
Width of the editor expands into the rest of the page.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6151](http://archive.tinymce.com/develop/bugtracker_view.php?id=6151) posted by [tm258](http://archive.tinymce.com/profile.php?name=tm258)_
> 
> _**Tags:** [safari]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by agupta1989** [comment]
Nope, this issue is still there with v4.x
