### ISSUE TITLE
Custom form elements cannot enter or delete characters

### ISSUE THREAD

**Issue by xuxiaolong123** [tinymce/tinymce#9262]
## 📝 Provide detailed reproduction steps (if any)
When a custom plug-in inserts a form element, the form element cannot enter and delete characters. For example, input and textarea cannot enter characters.

Plugin Script:
```
tinymce.PluginManager.add('form', function(editor, url) {
	editor.ui.registry.addMenuButton('form', {
      text: 'form',
      fetch: (callback) => {
        const items = [
          {
            type: 'menuitem',
            text: 'input',
            onAction: () => {
				editor.insertContent('&nbsp;<input id="aaaaa" type="text" name="aa"/>');
			}
          },{
            type: 'menuitem',
            text: 'textarea',
            onAction: () => {
				editor.insertContent('&nbsp;<textarea id="bbbb" >example</textarea>');
			}
          }
        ];
        callback(items);
      }
    });
  return {
    getMetadata: function () {
      return  {
        name: "form element",
        url: "http://exampleplugindocsurl.com",
      };
    }
  };
});
```

### ✔️ Expected result
The input box can input characters from the keyboard
![image](https://github.com/tinymce/tinymce/assets/59186378/065d2398-7428-498d-8191-9e461316e8f0)

### ❌ Actual result
The keyboard cannot enter any characters into the input box

## 📃 Other details
- Browser: Google Chrome version 119.0.6045.200
- OS: Windows

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @xuxiaolong123 . TinyMCE does not support adding functional form elements inside the editor, so this is not a bug. Please feel free to file a feature request instead, adding additional details what you intend to use this feature for and any requirements for it. Create a new issue and pick the feature request template. Thanks.

**Comment by xuxiaolong123** [comment]
> Hi @xuxiaolong123 . TinyMCE does not support adding functional form elements inside the editor, so this is not a bug. Please feel free to file a feature request instead, adding additional details what you intend to use this feature for and any requirements for it. Create a new issue and pick the feature request template. Thanks.

got it！
