### ISSUE TITLE
HTTP Error:400 alert coming

### ISSUE THREAD

**Issue by shakirayoub123** [tinymce/tinymce#9266]
If i am trying to upload image getting the alert message HTTP Error : 400 
steps to replicate

- clicking on the insert from the description of the tinyMce, then click on the image and then click on upload image its throwing error
![image](https://github.com/tinymce/tinymce/assets/117161359/6a143445-c4f4-4488-af38-69d5812826ed)

I want to to catch the error. To prevent and show that error response  in warning modal.

**Comment by lostkeys** [comment]
Hi @shakirayoub123,
I'm sorry but I have to ask you to resubmit your bug report/feature request using the proper template with a bit more actionable detail.

— Fredrik, Product Manager
