### ISSUE TITLE
Copying and pasting colors from a word document does not work on iPhone/Safari

### ISSUE THREAD

**Issue by athenem** [tinymce/tinymce#9271]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.
1. Create a word document with some text in color
2. On an iPhone/Safari (Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Mobile/15E148 Safari/604.1) copy and paste the colored text into tinymce editor.
3. The colors are lost
4. Works fine on a PC

### ✔️ Expected result
Colors should not be lost

### ❌ Actual result
All text is in black

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Mobile/15E148 Safari/604.1
Broken in 6 for Angular.
Worked in 5 for AngularJs tinymce/5/tinymce.min.js

**Comment by lostkeys** [comment]
Hi @athenem. Can you go [to our clipboard helper tool](https://static.ephox.com/clipboard/clipboardtest.html) and paste what you copied out of Word into the red square and get back here with the result to help us better debug the issue.

**Comment by athenem** [comment]
Hi,

 

Thanks for looking into this.

 

Copying and pasting the content from the attached document works fine using
the clipboard helper tool. 

 

It doesn't work pasting it into
https://www.tiny.cloud/docs/tinymce/6/full-featured-open-source-demo/.

 

Thanks

Athene

**Comment by athenem** [comment]
Attaching example document to copy and paste from 
[tinymceexample.docx](https://github.com/tinymce/tinymce/files/13789974/tinymceexample.docx)

**Comment by lostkeys** [comment]
Thanks for the update. Can you please paste the HTML code the helper tool produces here so we can see what output your "particular flavor" of Word produces.

**Comment by athenem** [comment]
Attaching raw html from https://static.ephox.com/clipboard/clipboardtest.html from PC and IPhone.
[rawHtmlPC.txt](https://github.com/tinymce/tinymce/files/13796337/rawHtmlPC.txt)
[rawHtmlIPhone.txt](https://github.com/tinymce/tinymce/files/13796338/rawHtmlIPhone.txt)

**Comment by athenem** [comment]
Hi Fredrik,

 

I have attached the raw html from both Iphone and PC. Looks like some stuff gets stripped out on Iphone.

 

Thanks

Athene

**Comment by TheSpyder** [comment]
Word import was removed from the open source editor in TinyMCE 6. See https://github.com/tinymce/tinymce/discussions/7487

The steps @lostkeys has asked you to follow related to our premium Powerpaste feature, but you don't seem to be using it. If you're interested I can connect you to our sales team, we do not offer premium support via GitHub. Apologies for the confusion.
