### ISSUE TITLE
This information is not clearly defined and does not explain the meaning of what the P Buttons relate to, or what it is to be used for

### ISSUE THREAD

**Issue by kadirozden001** [tinymce/tinymce#9277]
## 📝 Steps to reproduce:
====================
Select Microsoft Start button
Select Accessibility Tools drop down menu
Select JAWS version 2022
When JAWS opens - select Options, then Basic.
Navigate to drop down menu for Use keyboard layout
Select Laptop.
Select OK
Sign onto Service Now application
Select All Button
Enter Demand in Filter field
Select Create New
Select JAWS key (Caps lock or Insert) + CTRL + B keys to open the JAWS "Select a Button" list.
View P Button fields in the list.
![P Button](https://github.com/tinymce/tinymce/assets/155450933/6730ea4b-a543-4b89-a694-58aea1e214a6)

JAWS 11 Test CriterIa:
1. Use the CTRL + JAWS Key + B to display the list of all the button on the page
2. Confirm that all the buttons on the page are listed in the Buttons List"" box
3. Confirm that there is nothing in the buttons list which is not a button.
4. confirm that the button wording gives a clear indication of the purpose" Confirm the user can list all the buttons on the page in the buttons list box and that their purpose is described accordingly.

WCAG - 3.3.2 Labels or Instructions - Level A
WCAG - 4.1.2 Name, Role, Value - Level A"

**Comment by lostkeys** [comment]
Hi @kadirozden001 

Please resubmit this issue using our bug template with expected and actual results and and the version of TinyMCE you observe this issue on.

— Fredrik, Product Manager
