### ISSUE TITLE
Treeview for link (link_list option)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#928]
With the link_list option a list of links can be passed to the link dialog.

It would be nice to be able to have a tree structure for these links.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6153](http://archive.tinymce.com/develop/bugtracker_view.php?id=6153) posted by [bertvan](http://archive.tinymce.com/profile.php?name=bertvan)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
