### ISSUE TITLE
Sizeinput dialog component does not autocompute height even if constrain proportion is on

### ISSUE THREAD

**Issue by finnar-bin** [tinymce/tinymce#9284]
**What is the current behavior?**
I am creating a custom plugin which uses the `sizeinput` dialog component with an initial value. After editing the width the height does not get automatically computed eventhough constrain proportion settings is on. The only way I could get it to autocompute the height is if I focus on the height field first then go back to the width field and update it.

Here's a snippet of the custom plugin I'm currently making:
```typescript
editor.windowManager.open({
      initialData: {
        dimensions: {
          width: "10",
          height: "5",
        },
      },
      title: "Resize image",
      body: {
        type: "panel",
        items: [
          {
            type: "sizeinput",
            name: "dimensions",
            label: "Constrain proportions",
            enabled: true,
          },
        ],
      },
      buttons: [
        {
          type: "submit",
          text: "Save",
          primary: true,
        },
      ],
    });
``` 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

**What is the expected behavior?**
Height should get autocomputed once the user changes the width field value.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
TinyMCE version 6.7.2

**Comment by danoaky-tiny** [comment]
I can confirm this is an issue. You can replicate it here (tested on 6.8.2) https://fiddle.tiny.cloud/26J5FGyLy2/3

**Comment by theofficialnar** [comment]
One workaround I found was to force un-autofocus  the height input field via `.blur()` once my dialog opens which would force the user to manually click on the input fields which then enables the autocompute when constrain proportions is active.
