### ISSUE TITLE
Empty inline code formatting in new line leave empty formatting on remove

### ISSUE THREAD

**Issue by EmWa94** [tinymce/tinymce#9288]
Hi 👋 

I encountered an inline code formatting bug.

When you choose to write text as inline code formatting:

<img width="888" alt="image" src="https://github.com/tinymce/tinymce-react/assets/46203740/214dbdd1-af7f-449d-9112-3072d8442138">

Then, pressing `Enter` to go to the new line, it still formats text as an inline code, as expected (the same behaviour as, for instance, with bold formatting), but when you want to remove this line and get back to the previous line, there is empty inline code block left. It's impossible to remove. You can't go into this block again with the aim of removing it. 

<img width="887" alt="image" src="https://github.com/tinymce/tinymce-react/assets/46203740/34f93d66-08ef-4373-811c-bda343c3086d">
<img width="892" alt="image" src="https://github.com/tinymce/tinymce-react/assets/46203740/aa10c6f2-7b7a-4c5e-8d09-918a786a981c">

When you go to the new line and type something, it works ok. Clicking `Backspace` removes letter by letter first, then empty formatted code. It just does not work when trying to remove an empty inline code block in a new paragraph.

It's rather `tinymce` bug than `@tinymce/tinymce-react` 🤔 

`tinymce`: `6.8.1`
`@tinymce/tinymce-react`: `4.3.2`

**Comment by danoaky-tiny** [comment]
Ah, just realised you had made an issue in `tinymce` already. It is indeed an issue for core TinyMCE, I'll close this one.
