### ISSUE TITLE
How to disable the tinymce focus from text editor or, how to remove the focus from tinymce text area.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#930]
Description of problem:

Steps to reproduce:
1.remove the text editor focus, 
2.
3.
4.
5.

Expected result: focus should remove or focus should be blur.

Actual result: focus not able to remove or focus not blur in text editor
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6155](http://archive.tinymce.com/develop/bugtracker_view.php?id=6155) posted by [naveen ng](http://archive.tinymce.com/profile.php?name=naveen ng)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
