### ISSUE TITLE
Shortcut to element path is listed in the help whereas it's desactivated

### ISSUE THREAD

**Issue by Naciba** [tinymce/tinymce#9301]
## 📝 Provide detailed reproduction steps (if any)
1.go to : https://fiddle.tiny.cloud/WRDhIjZwrQ/0
2. Go to help or Press Alt+0 for help

### ✔️ Expected result
the shortcut to element path shouldn't be listed in the help when it's desactivated

### ❌ Actual result
the shortcut to element path is listed in the help whereas it's desactivated

### ❓ Possible solution
remove in the help the shortcut related to the element path when it's desactivated

## 📃 Other details
- Browser: …
- OS: …
- First affected version: …
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Duplicate of #9300
