### ISSUE TITLE
select in plugin tinymce v6 not use 

### ISSUE THREAD

**Issue by tieucoctu** [tinymce/tinymce#9304]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.
selector: 'textarea#file-picker',
then
Type 'string' is not assignable to type 'undefined'.

### ✔️ Expected result
*What is the expected result of the above steps?*

### ❌ Actual result
*What is the actual result of the above steps?*

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: …
- OS: …
- First affected version: …
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Sorry, we need much more information to be able to do anything with this. Please submit a new ticket and fill in more details in the template. Thanks.
