### ISSUE TITLE
Tiny MCE Formatting Options

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#931]
Description of problem:
When we type  some text in the editor after selecting the B, I and U option and after typing again deselect the U, I and B option, the text that are not selected for applying styles are getting affected. PFB the steps to replicate:

Steps to reproduce:

  i)Enter text in the notes section&ltg;Ex:qwe>
  ii)Select Bold icon and enter text&ltg;Ex:qwe>
  iii)Select Italic icon and enter text&ltg;Ex:qwe>
  iv)Select Underline icon and enter text&ltg;Ex:qwe>
  v)Now deselect the Italic icon and verify the entered text.
  vi)Now deselect the Bold icon and verify the entered text.

Expected result:
Changes should be reflected only to the selected text.
Actual result:
Changes are reflected to all the text in the editor.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6156](http://archive.tinymce.com/develop/bugtracker_view.php?id=6156) posted by [Bold_Rose](http://archive.tinymce.com/profile.php?name=Bold_Rose)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
