### ISSUE TITLE
Bulleted lists are very buggy

### ISSUE THREAD

**Issue by Ajayguttedardev** [tinymce/tinymce#9311]
When a user uses the wysiwyg editor, they work very hard on their bullets but these bullets eventually get screwed up and it becomes hard to fix them.

If you use the editor you have no double experienced this issue?  Type a series of bullets, then try to reformulate them by adding and subtracting them, change the indenting, use multiple levels, cut and paste items into a different order, and just work your content. After a while you will be unable to format the bullets the way you want them. 

If you need more details please ask Tyler to provide specific recreation steps. The best way to understand the problem is just by using the editor to create and manage bulleted lists for a while. Working with your content in bulleted lists is unusable.
![bullets xFAD6G](https://github.com/tinymce/tinymce/assets/157182845/5acd30aa-68f5-40d8-aee7-868d0239df8f)

**Comment by TheSpyder** [comment]
Enter and backspace are just conveniences for list manipulation. The `Decrease indent` button, mapped to the keyboard shortcut `shift+tab` while the cursor is in a list, is the proper action you seem to be looking for in that gif.

Who is Tyler? We did have an author of our documentation by that name, but he left the company 2 years ago.
