### ISSUE TITLE
Can not get val() of certain elements when jQuery tinymce (v4+) is loaded.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#932]
Description of problem:

When there is an HTML element (eg. form input field) which has an ID that is the same as an existing javascript array prototype method or property, an error occurs when you try to access the jQuery setter/getter functions .text(), .html() or .val() on that element.

The tinymce jQuery plugin modifies jQuery's setters and getters (text, html, val) to add support for getting content from tinymce instances, however the tinymce.get() (tinymce.jquery.js:24987, called by jquery.tinymce.js:246) method is incorrectly returning a false positive for these fields, returning the javascript array method/property with the same name instead of a tinymce editor instance.

Because tinymce.editors is stored as an array, when it goes to return this.editors['sort'](which is not an editor instance), it's finding the sort() method as inherited from the array prototype. This can be solved by using hasOwnProperty() at this point to check that we're not returning inherited methods or properties from the prototype. eg if (this.editors.hasOwnProperty('sort'))

Steps to reproduce:
1. Have the jQuery version of tinymce running on a page. (Not sure if this is the same for the non-jQuery version)
2. Try to access the value of a form input element with the ID attribute of "sort" using jQuery's .val() method. eg. 

&ltg;input type="hidden" id="sort" value="123" />
&ltg;script>
console.log ( $("#sort").val() );
&ltg;/script>

Expected result:

123

Actual result:

Uncaught TypeError: Object function sort() { [native code] } has no method 'getContent' 

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6157](http://archive.tinymce.com/develop/bugtracker_view.php?id=6157) posted by [madwebskills](http://archive.tinymce.com/profile.php?name=madwebskills)_
> 
> _**Tags:** [firefox msie safari chrome opera jquery val html text]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Rtdaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
