### ISSUE TITLE
line height lose in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#933]
When I copy a table with styles, etc with line-height to tinymce, the line-height will be lost. It happen in Chrome but ok in firefox. So I think that's a bug.

I can recur it in your demo editor also.

Chrome: 28.0.1500.72 m

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6158](http://archive.tinymce.com/develop/bugtracker_view.php?id=6158) posted by [suning](http://archive.tinymce.com/profile.php?name=suning)_
> 
> _**Tags:** [chrome chrome style]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
