### ISSUE TITLE
Inlinecss Plugin does not support CSS Variables 

### ISSUE THREAD

**Issue by roymilder** [tinymce/tinymce#9335]
## 📝 Provide detailed reproduction steps (if any)
It looks like the inlinecss plugin does not support css variables. When working with the inlinecss plugin the following error message appears when executing ``` editor.plugins.inlinecss.getContent()```

This is the case when running TinyMCE in inline mode.

```
plugin.min.js:10 Invalid call to CSS.set. Property  --primary-50-color :: Value  undefined :: Element  
```
```
zone.js:1681 Uncaught Error: CSS value must be a string: undefined
```

### ✔️ Expected result
*What is the expected result of the above steps?*
Should output the correct inline css

### ❌ Actual result
*What is the actual result of the above steps?*
Error message (see above)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Inline CSS is a premium feature, we do not offer premium support via GitHub. If you have a support subscription, you will be better served by our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
