### ISSUE TITLE
Looses bold state

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#934]
Description of problem: Chrome 28.      

Steps to reproduce:
1. Click into textarea.
2. Click bold.
3. Type "hello"
4. Click italic
5. Type "world"
6. Click bold.

Expected result: Text you type should change from italic-bold to italic-unbold.

Actual result: All bold formatting is removed from the entire string.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6159](http://archive.tinymce.com/develop/bugtracker_view.php?id=6159) posted by [stevenmc](http://archive.tinymce.com/profile.php?name=stevenmc)_

> _**Tags:** [chrome chrome13]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
