### ISSUE TITLE
object_resizing fails when bundled installation is used

### ISSUE THREAD

**Issue by OneSeven** [tinymce/tinymce#9352]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.

example:  https://stackblitz.com/~/edit/vitejs-vite-9eljq6?file=index.html&terminal=dev

### ✔️ Expected result
object_resizing work

### ❌ Actual result
object_resizing not work

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: chrome 121
- OS: windows11
- First affected version: 6.8.2
- Worked in version:  none

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Your example doesn't include any detail about what is wrong - whoever reviewed this should've asked for more detail, sorry about that.

At a guess #10004 might resolve your issue. It will be released in TinyMCE 7.6.

**Comment by TheSpyder** [comment]
Ah there's no resize _handles_. Thank you for sticking with me, I know language barriers can be difficult.

Yes this is what we resolved in #10004 and the fix should be out shortly.

**Comment by TheSpyder** [comment]
And by "shortly" I mean "today". The release notes talk about React but it applies to all bundling.

https://www.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#fixed-css-bundling-for-skin-ui-content-css
