### ISSUE TITLE
IE: DIVs have to be clicked twice to make active

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#936]
Description of problem:
Where content has two DIVs, each DIV has to be double clicked in order to make it active

Steps to reproduce:
1. Internet Explorer v7-10
2. TinyMCE v4
3. Two DIVs with content

Expected result:
Click div, cursor flashes where clicked

Actual result:
Click div, you get grab handles

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6161](http://archive.tinymce.com/develop/bugtracker_view.php?id=6161) posted by [grahammiles](http://archive.tinymce.com/profile.php?name=grahammiles)_

> _**Tags:** [msie msie7 msie8 msie9 msie10 explorer divs ie]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Ztdaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
