### ISSUE TITLE
Backspace key deletes span tags in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#937]
This bug still exists for backspace and span tags:

http://www.tinymce.com/develop/bugtracker_view.php?id=5641

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6162](http://archive.tinymce.com/develop/bugtracker_view.php?id=6162) posted by [sgentile](http://archive.tinymce.com/profile.php?name=sgentile)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
