### ISSUE TITLE
Multiple tinymce on page cause tinymce.activeEditor undefined

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#938]
Description of problem:
If you have multiple tinymce on same page and your focus is on other page element, open insert image dialog and click on filepicker button, tinymce.activeEditor is undefined.
Close popup and re-open, it's ok.

Steps to reproduce:
1. load your page with multiple tinymce
2. focus other element on page
3. click insert image button
4. click filepicker button
5. on your callback function "file_browser_callback" in config, tinymce.activeEditor is undefined. tinymce.activeEditor.windowManager.windows[0].find('#element') is usefull, for exemple, to get/change input element from own filepicker.

It works if focus editor before open popup or there is 1 editor on page.

Maybe, is there other solution to get open windows ?
is there a event callback when popup is ready ?

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6163](http://archive.tinymce.com/develop/bugtracker_view.php?id=6163) posted by [btr](http://archive.tinymce.com/profile.php?name=btr)_

> _**Tags:** [firefox 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
