### ISSUE TITLE
document.id conflict with MooTools, MoxieManager

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#940]
Description of problem:

Javascript errors occur due to a conflict with the Mootools document.id() function. Although it happens when launching MoxieManager, the error occurs within tinymce.

(The fiddle doesn't seem to include the moxiemanager plugin so I can't include a test case)

Steps to reproduce:
1. include Mootools 1.4.5
   http://ajax.googleapis.com/ajax/libs/mootools/1.4.5/mootools-yui-compressed.js
1. enable moxiemanager plugin
2. click "insert/edit image" toolbar button
3. click moxiemanager "browse" button

Expected result:

Open moxiemanager without error

Actual result:

"TypeError: t.id.indexOf is not a function"

The error occurs due to using the String.indexOf() method on a function, document.id().
Mootools defines document.id() as its dollar function $() to find and extend elements.

//##### File: tinymce.js, Line: 29502 #####
//ORIGINAL: 
  if (elm.id && elm.id.indexOf('-open') != -1) {

//PATCHED: 
  if (elm.id && elm.id.indexOf && elm.id.indexOf('-open') != -1) {

//##### File: tinymce.min.js #####
//ORIGINAL: 
  n.on("click",function(e){for(var t=e.target;t;)t.id&&-1!=t.id.indexOf("-open")&&n.fire("action"),t=t.parentNode}),

//PATCHED: 
  n.on("click",function(e){for(var t=e.target;t;)t.id&&t.id.indexOf&&-1!=t.id.indexOf("-open")&&n.fire("action"),t=t.parentNode}),

//--------------------------------------------------
// EDIT: found another instance in the moxiemanager code

//##### File: moxiemanager/js/moxman.api.min.js #####
//ORIGINAL: 
  i.on("click",function(e){for(var t=e.target;t;)t.id&&-1!=t.id.indexOf("-open")&&i.fire("action"),t=t.parentNode}),

//PATCHED: 
  i.on("click",function(e){for(var t=e.target;t;)t.id&&t.id.indexOf&&-1!=t.id.indexOf("-open")&&i.fire("action"),t=t.parentNode}),

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6169](http://archive.tinymce.com/develop/bugtracker_view.php?id=6169) posted by [Rob J](http://archive.tinymce.com/profile.php?name=Rob J)_
> 
> _**Tags:** [firefox msie safari chrome opera mootools documentid moxiemanager]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
