### ISSUE TITLE
Can TinyMCE cache-bust its own modules?

### ISSUE THREAD

**Issue by jordanade** [tinymce/tinymce#9403]
## 📝 Provide a description of the new feature or improvement
Why should I have to add `cache_suffix: "?v="+tinymce.majorVersion+"."+tinymce.minorVersion` to all my configs to avoid everything breaking, as it did when upgrading from v5 to v6? Can this be handled automatically?

### 🫶 What is the motivation?
Avoid unnecessary cache-related bugs.

### 🔗 What is the consequence of not having this feature?
Horrible bugs when upgrading and forgetting to change `cache_suffix` or use my above solution.

### 🚦 How important would you rate the requested feature or improvement?
Important

---

If you'd like to see this implemented sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
We don't want to assume a cache-busting system we come up with will work for the wide range of web servers, proxies, and integration environment TinyMCE is used in. So no, if you want a dynamic cache suffix that's the way to do it.

For example on Tiny Cloud, our solution is to `307` redirect requests for `tinymce.min.js` to a folder with the version number in it. So no cache suffix is required at all.
