### ISSUE TITLE
Using Blockquote clears editor contents (but not visually!)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#941]
When using the blockquote function in a specific way, the contents of the editor are lost upon submitting. However, this is not visible, so after submitting all contents are lost.

The error appears in 3.5.x, but not in 4.0. I'm not sure whether these two versions are maintained, but an upgrade to 4.0 seems quite radical, so that might not be feasible on the short term. 

Steps to reproduce:
1.Focus the editor
2.Press Enter
3.Click Blockquote
4.Type some words
5.Click Blockquote again
6.Press Enter
7.Type another set of words
8.Click See editor contents

Expected result:
The two lines of text (from steps 4 and 7) are shown in the dump screen.

Actual result:
The submitted text is empty.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6165](http://archive.tinymce.com/develop/bugtracker_view.php?id=6165) posted by [allardnaber](http://archive.tinymce.com/profile.php?name=allardnaber)_

> _**Tags:** [msie msie8 msie9 msie10 3x]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/iudaab_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
