### ISSUE TITLE
Crash in IE10 when deleting a row or column in a table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#942]
Description of problem: IE throws an "unknown exception" when trying to delete a column in a table when the cursor is in the last lower right cell

Steps to reproduce:
1. Goto the 3.x demo
2. Insert a new table (2x2 will do)
3. Place cursor in the cell in the lower right
4. Delete column

Expected result: Column would be deleted

Actual result: Crash!

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6166](http://archive.tinymce.com/develop/bugtracker_view.php?id=6166) posted by [Atletismo343](http://archive.tinymce.com/profile.php?name=Atletismo343)_

> _**Tags:** [msie msie10 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
