### ISSUE TITLE
Error on deselecting italic and bold icons

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#943]
Description of problem:
Deselecting italic and bold icons after intially selecting them and entering resulting in all the entered text getting unbolded and unitalicized.

Steps to reproduce:
  i)Enter text in the notes section&ltg;Ex:qwe>
  ii)Select Bold icon and enter text&ltg;Ex:qwe>
  iii)Select Italic icon and enter text&ltg;Ex:qwe>
  iv)Select Underline icon and enter text&ltg;Ex:qwe>
  v)Now deselect the Italic icon and verify the entered text.
  vi)Now deselect the Bold icon and verify the entered text.

Expected result:
After deselecting bold or italic icon the text to be entered should be affected but not the already entered text which is not selected.

Actual result:
After deselecting italic or bold icon the text already entered  is getting affected without any selection done.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6167](http://archive.tinymce.com/develop/bugtracker_view.php?id=6167) posted by [Bold_Rose](http://archive.tinymce.com/profile.php?name=Bold_Rose)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
