### ISSUE TITLE
Why is the table not highlighted when selecting a table with the mouse

### ISSUE THREAD

**Issue by Himiaomiao** [tinymce/tinymce#9430]
## 📝 Provide a description of the new feature or improvement
*Describe your idea for the new feature or improvement*
Why is the table not highlighted when selecting a table with the mouse
### 🫶 What is the motivation?
*Pitch why this feature or improvement should be implemented.*
Why is the table not highlighted when selecting a table with the mouse
### 🔗 What is the consequence of not having this feature?
*This helps understand the underlying pain-points*
Why is the table not highlighted when selecting a table with the mouse
### 🚦 How important would you rate the requested feature or improvement?
*Choose from nice-to-have, important or critical.*
Why is the table not highlighted when selecting a table with the mouse
---

If you'd like to see this implemented sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @Himiaomiao. When selecting a table, it highlights. I cannot replicate your issue. And you didn't fill in the template correctly. Please submit a proper bug or feature request with more details. Thanks.

— Fredrik, Product Manager
