### ISSUE TITLE
scrolling attribute lost on iframe 

### ISSUE THREAD

**Issue by spoissant** [tinymce/tinymce#9435]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.
1. Given a TinyMCE editor with `code` and `media` plugins enabled
2. Open the "source code" dialog
3. Insert an iframe element with the `scrolling` attribute in the content and click `save`. For example, you can replace the content with the following:
```
<p><iframe class="embedly-embed" style="aspect-ratio: 854 / 480;" title="YouTube embed" src="//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fmw34FQUIu3I%3Ffeature%3Doembed&amp;display_name=YouTube&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dmw34FQUIu3I&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fmw34FQUIu3I%2Fhqdefault.jpg&amp;key=dbe53e8b4d2c414baa1bb5daf229ae72&amp;type=text%2Fhtml&amp;schema=youtube" width="854" height="" frameborder="0" scrolling="no" sandbox=""></iframe></p>
```

### ✔️ Expected result
The resulting iframe in the editor has the same `scrolling` attribute as the original iframe

### ❌ Actual result
The `scrolling` attribute has been stripped from the iframe

### ❓ Possible solution
Add the following at around [line 95](https://github.com/tinymce/tinymce/blob/f1647ea623561365b3ea493fed25b50667c4f33a/modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts#L95) in `modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts` inside `createPreviewNode`
```
scrolling: node.attr('scrolling')
```

**Comment by lostkeys** [comment]
Hi @spoissant. Use [extended valid elements](https://www.tiny.cloud/docs/tinymce/6/content-filtering/#extended_valid_elements) to define what attributes you need on the iframe. Here is an example: https://fiddle.tiny.cloud/LMoKXVj2ka/0

— Fredrik, Product Manager
