### ISSUE TITLE
Entire Word doc not being pasted into TinyMCE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#944]
Description of problem:  Pasting in the attached Word doc does not copy over all the text.  Content disappears in random spurts throughout the page.

Steps to reproduce:
1.  Paste Word doc
2.  Examine TinyMCE content vs. Word doc

Expected result:  One fo the news articles is labeled "Teen Dating Abuse" and has a paragraph describing it (when viewed in Word).  Upon pasting it into TinyMCE, only the title "Teen Dating Abuse" appears and the paragraph describing it goes missing.  I've put lines to indicate starting and ending point for expected result.

=================================
TEEN DATING ABUSE
U.S. News & World Report (July 31) -- More than a third of teen boys and girls say they�ve been physically, emotionally or sexually abused in their dating relationships, according to new, unpublished data from a nationwide survey. Similar numbers of both sexes say they�ve been abusers. Dorothy Espelage, a professor of educational psychology at Illinois, says, �Without measures of fear, severity and injury, we need to be cautious� about interpreting the new nationwide survey results. Espelage worked on the survey and on another study presented Wednesday that show links between middle school bullying and teen dating violence.
=================================

Actual result:  As mentioned above, the Teen Dating Abuse article has a paragraph.  Unfortunately, in TinyMCE, here's the end result for the Teen Dating Abuse article.

=================================
TEEN DATING ABUSE
=================================
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6170](http://archive.tinymce.com/develop/bugtracker_view.php?id=6170) posted by [mgaso](http://archive.tinymce.com/profile.php?name=mgaso)_

> _**Tags:** [firefox msie safari chrome opera word paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
