### ISSUE TITLE
Specific plugin for align images using a specific <DIV>

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#946]
Using the "text align" for linked images, it often produces a bad final result, moreover if the link:hover status in css has a colored background.

It would be great to have a tip on how to create a plugin that can add a &ltg;div class=#"> and &ltg;/div> around images and their link.

Example: the image in editor is &ltg;a href="#"> &ltg;img src="path" /> &ltg;/a>

Then in have 3 buttons in my editor: "Align image left", "Align image right", "Align image center".

By clicking the linked (or not) image and by pressing the "Aling image left" button, it adds a new div - container:

&ltg;div class="img_left"> &ltg;a href="#"> &ltg;img src="path" /> &ltg;/a> &ltg;/div>

(css example: img_left {display:block; float:left; margin:0 10 10 0; padding:5px; border:1px solid #bcbcbc} )

Now, if I want to change the align, by clicking the image and pressing the "Align image right" button, the editor should just switch between classes, from "img_left" to "img_right".

Right now, by using the simple "text align" buttons, it just adds a float class to the &ltg;img>.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6173](http://archive.tinymce.com/develop/bugtracker_view.php?id=6173) posted by [MarkWD](http://archive.tinymce.com/profile.php?name=MarkWD)_
> 
> _**Tags:** [aling images plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
