### ISSUE TITLE
TinyMCE failed to import styles

### ISSUE THREAD

**Issue by HaloElite** [tinymce/tinymce#9468]
I'm using tinymce 6.8.3 via the npm package in a vue3 application. 
When importing `import 'tinymce/themes/silver';`, I get the errors shown in the picture.

[![enter image description here][2]][2]

  [2]: https://i.stack.imgur.com/erNsP.png

### ✔️ Expected result
The styles shoul be imported 

### ❌ Actual result
Problems importing the styles.

**Comment by TheSpyder** [comment]
You need to import more than just the theme - see our bundling documentation for guidelines.
https://www.tiny.cloud/docs/tinymce/latest/introduction-to-bundling-tinymce/

**Comment by HaloElite** [comment]
@TheSpyder That's what I actually did. Looking at [npm/vite](https://www.tiny.cloud/docs/tinymce/latest/vite-es6-npm/)

```
/* Import TinyMCE */
import tinymce from 'tinymce';

/* Default icons are required. After that, import custom icons if applicable */
import 'tinymce/icons/default/icons.min.js';

/* Required TinyMCE components */
import 'tinymce/themes/silver/theme.min.js';
import 'tinymce/models/dom/model.min.js';
import 'tinymce/skins/content/tinymce-5/content';

/* Import a skin (can be a custom skin instead of the default) */
import 'tinymce/skins/ui/oxide/skin.js';
```
It's the exact example from the docs. But importing the theme throws the shown error. Also do these lines:

```
/* content UI CSS is required */
import contentUiSkinCss from 'tinymce/skins/ui/oxide/content.js';

/* The default content CSS can be changed or replaced with appropriate CSS for the editor content. */
import contentCss from 'tinymce/skins/content/default/content.js';
```

`Uncaught (in promise) SyntaxError: The requested module '/vite-dev/@fs/app/node_modules/.vite/deps/tinymce_skins_ui_oxide_content__js.js?v=8feccfe8' does not provide an export named 'default'`

**Comment by HaloElite** [comment]
It seems to be a problem with how the `baseURL` inside `theme.min.js` is resolved in combination with vite. Setting and alias to the `base_url` prop solves the issue but seems kinda hacky to me.

`base_url: '/vite-dev/@fs/app/node_modules/tinymce/'`

**Comment by TheSpyder** [comment]
This changed a bit in 6.8 and maybe the docs need to be updated further. Every `css` file it's trying to download should be available as a JS file, and if you import that into your bundle the editor should not attempt to download the CSS file.

**Comment by HaloElite** [comment]
So that means I have to do what exactly? Import the css files by myself? But shouldn't it be enough to import the skins/themes?
`import 'tinymce/skins/ui/oxide/skin.js';` / `import 'tinymce/themes/silver/theme.min.js';`? Or should I move them out of `node_modules` inside the public folder for example?

**Comment by TheSpyder** [comment]
The JS files are designed register themselves with the `tinymce` object such that editor loads use the data in the JS file instead of trying to download the CSS. Every `.min.css` file we ship should have a corresponding `.js` file.
