### ISSUE TITLE
Page jumps to top when editor resizes

### ISSUE THREAD

**Issue by aneshodza** [tinymce/tinymce#9480]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.
**Sadly I cannot provide an example, as the project is confidential**
1. Adding TinyMCE to a website, where seeing the editor means that you aren't scrolled at top
2. Write a few newlines, so the editor gets resized.

### ✔️ Expected result
The expected result is for the editor to just get bigger

### ❌ Actual result
The editor scrolls to the top of the page

### ❓ Possible solution
I'm guessing there are JS handlers somewhere that cause this

## 📃 Other details
- Browser: Firefox and potentially other browsers too. I'm not sure which browser the customer uses.
- OS: Fedora & Windows
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Which TinyMCE version? This sounds like a bug in one of the 6.x releases but it was fixed.

**Comment by aneshodza** [comment]
I am on version 6.6.1 of TineMCE. Should I just upgrade my version and try again?

**Comment by aneshodza** [comment]
Much thanks!
