### ISSUE TITLE
change format source doesn' work in media plugin 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#949]
Description of problem:
For ex. add a mp3 source and change to webm source, change isn't apply.

Steps to reproduce:
1. open insert video popup
2. add a source (mp3), look embed code, it's &ltg;audio>...
3. now, change source (vid�o like webm or mp4)
4. look embed code, it's &ltg;audio>
5. look your url source, it's your first source, mp3 file
6. and vice & versa

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6176](http://archive.tinymce.com/develop/bugtracker_view.php?id=6176) posted by [btr](http://archive.tinymce.com/profile.php?name=btr)_

> _**Tags:** [4x media]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
