### ISSUE TITLE
<use> tag is always removed

### ISSUE THREAD

**Issue by radekhulan** [tinymce/tinymce#9497]
## 📝 Provide detailed reproduction steps (if any)

Have this HTML code:
`<svg width="19" height="22" viewBox="0 0 19 22"> <use xlink:href="#icon-user"></use></svg>`

I have tried many "hacks",  including:
- valid_elements : `*[*]`
- extended_valid_elements : `*[*]`
- `name="XYZ"` to <use> tag
- add `&nbsp;` as content
- add `class="XYZ"` to <use> tag
- changing xlink:href to xlink-href

but `<use>` will always get removed.

### ✔️ Expected result

Preserve the tag.

### ❌ Actual result

<USE> tag gets deleted

### ❓ Possible solution
Just preserve this tag. Please :-)

## 📃 Other details
- Browser: latest Edge and Chrome 
- OS: Windows
- tinyMCE version: latest (6.8.3)

**Comment by lostkeys** [comment]
Hi @radekhulan. SVGs are filtered out because of the security risk they pose. Read our [security guide](https://www.tiny.cloud/docs/tinymce/6/security/) on the topic and available options.
