### ISSUE TITLE
Menubar items in wrong order

### ISSUE THREAD

**Issue by richardczeiger** [tinymce/tinymce#9499]
It's a small issue but should be looked at.
My code is written like this:
...
```
	menubar: true,
	menu: {
		edit: { title: 'Edit', items: 'undo redo | cut copy paste pastetext | selectall | searchreplace' },
		insert: { title: 'Insert', items: 'link anchor image media inserttable | nonbreaking charmap emoticons hr | mergetags' },
		format: { title: 'Format', items: 'bold italic strikethrough superscript subscript codeformat | removeformat' },
		table: { title: 'Table', items: 'inserttable | cell row column | advtablesort | tableprops deletetable' },
		tools: { title: 'Tools', items: 'spellchecker a11ycheck | visualaid visualchars wordcount code fullscreen' },
		help: { 'title': 'Help', items: 'help' },
	},

```
...
The expectation is that it is displayed in the order written.
However, this is the result - 'Table' and 'Tools' are reversed.

![tinymce-menu-order](https://github.com/tinymce/tinymce/assets/8031303/5030c873-9ca3-41fc-a4ab-73749851eb72)

Any idea how to fix this??
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @richardczeiger. You should use the [menubar option](https://www.tiny.cloud/docs/tinymce/latest/menus-configuration-options/#example-customizing-the-menu-bar) to control the order of the menu itself.

**Comment by richardczeiger** [comment]
SoSorry! I totally didn't realise that. Thanks for taking the time to show me the way   :)
