### ISSUE TITLE
From version 6.8.1 is removed USE tag from SVG tag

### ISSUE THREAD

**Issue by MSTrucker** [tinymce/tinymce#9507]
## 📝 Provide detailed reproduction steps (if any)
extended_valid_elements contain "use[*]"
inserted code `<svg class="fs right"><use xlink:href="/fonts/icons.svg#angle-up"></use></svg>` is filtered to `<svg class="fs right"></svg>`

### ✔️ Expected result
If "extended_valid_elements" contains a "use" tag, it will be preserved in the code.

### ❌ Actual result
Tag "use" is removed.

## 📃 Other details
- Browser: Chrome 123.0.6312.58
- OS: Windows 11
- First affected version: 6.8.1
- Worked in version: 6.7.3

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @MSTrucker. SVGs are filtered out because of the security risk they pose. Read our [security guide](https://www.tiny.cloud/docs/tinymce/6/security/) on the topic and available options.
