### ISSUE TITLE
video_template_callback does not take effect

### ISSUE THREAD

**Issue by NiklasBr** [tinymce/tinymce#9512]
## 📝 Provide detailed reproduction steps (if any)

using the documentation available at https://www.tiny.cloud/docs/tinymce/latest/media/#example-using-video_template_callback I have created this fully distilled small example of the bug:

https://fiddle.tiny.cloud/chAnRwzU7m/0

```html
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "media", "code"
    ],
    toolbar: "media code",
	  video_template_callback: (data) =>
    `<video width="${data.width}" height="${data.height}"${data.poster ? ` poster="${data.poster}"` : ''} controls="controls">\n` +
    `<source src="${data.source}"${data.sourcemime ? ` type="${data.sourcemime}"` : ''} />\n` +
    (data.altsource ? `<source src="${data.altsource}"${data.altsourcemime ? ` type="${data.altsourcemime}"` : ''} />\n` : '') +
    '</video>'
	
});
</script>

<form method="post" action="/dump">
    <textarea name="content"></textarea>
</form>

<!-- example to paste into Media source: https://youtu.be/s1LeJjI2qZ0?si=m8nGJr_CYbtIuS73 -->
```

### ✔️ Expected result
A `<video ...` element according to what is written in `video_template_callback`

I know that linking a youtube video into a `<video>` element is not valid HTML, but the above code is to demonstrate a specific issue where the `video_template_callback` is not even executed.

Even running `video_template_callback: (data) => console.warn("This should run")` does not print anything into the browser console.

### ❌ Actual result
A regular YouTube iframe, the `video_template_callback` appears to never run.

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: Crome, Edge, Safari, Firefox all exhibits the same behaviour.
- OS: Mac OS 14.4 and Windows 11 Pro exhibits the same behaviour
- First affected version: ?
- Worked in version: ?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
That's because we know certain URLs don't work in a video tag and map them to the iframe type.
https://github.com/tinymce/tinymce/blob/ee32d00d4f5a613576862f3756b4d7d0a6da1fdf/modules/tinymce/src/plugins/media/main/ts/core/UrlPatterns.ts#L15-L20

In general, we use the URL file extension to determine which tag to use - with `video` as the default.
https://github.com/tinymce/tinymce/blob/9c486f7c951e55ae34bb548efe897eec705ac04d/modules/tinymce/src/plugins/media/main/ts/core/Mime.ts#L5-L11

**Comment by NiklasBr** [comment]
How do I override those?

**Comment by NiklasBr** [comment]
The Youtube embedded iframe created is incomplete in three ways (lacking permissions, not fully responsive, and can't force the no-cookie domain) and we need to adjust that template.

How do we do that=

Why is the above behaviour not documented? The docs make it seem like the desired behaviour is possible.

**Comment by TheSpyder** [comment]
There is also an [iframe_template_callback](https://www.tiny.cloud/docs/tinymce/latest/media/#iframe_template_callback) option if you'd like to customise the result.

**Comment by NiklasBr** [comment]
Thanks, I will try that.

Given the documentation says 

> "This option allows you to specify a function that will be used to replace TinyMCE’s default media embed logic with your own, custom logic."

How was we to know that it was _not actually_ possible to replace the embed logic with our own?

**Comment by TheSpyder** [comment]
That statement refers to [`media_url_resolver`](https://www.tiny.cloud/docs/tinymce/latest/media/#media_url_resolver), not `video_template_callback`.

**Comment by NiklasBr** [comment]
Sorry, but the sentence "This option allows you to specify the function that will return the HTML embed code of the video media that you are attempting to insert into TinyMCE." does not mention anything either about sometimes not being able to specify the function that will return the HTML embed code of the video media we are attempting to embed.

**Comment by TheSpyder** [comment]
It's a matter of semantics. By "video media" we mean standalone video files. The same way "audio media" means audio files. Youtube and similar video websites use iframes or other dynamic HTML embed approaches.

**Comment by NiklasBr** [comment]
Why not clarify the documentation like that, that's what it's there fore?
