### ISSUE TITLE
V5, paste a image  images_upload_handler failure('XXX') not work

### ISSUE THREAD

**Issue by centuryPark** [tinymce/tinymce#9519]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](fiddle.tiny.cloud) or similar.
1. copy a image what size > 5M
2. paste it, and then images_upload_handler function will limit size < 2M, so, goto failure('image size is to big!', { remove: true })
3. it can remove image, but the message window cannot be displayed 

### ✔️ Expected result
*What is the expected result of the above steps?*
it can remove image, but the message window cannot be displayed 

### ❌ Actual result
*What is the actual result of the above steps?*
remove image, and the message window can be displayed 

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: chrome
- OS: mac os 14.0 (23A344)
- First affected version: tinymce@5.9.1
- Worked in version: …

---
my version  tinymce@5.9.1
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Have you tried it in TinyMCE 6 or 7? We don't support 5 anymore.

**Comment by abhinavakhil** [comment]
Add paste_data_images property and set it to true. It will allow pasting images.

`paste_data_images: true,`
