### ISSUE TITLE
Spellchecker Plugin not properly working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#952]
The spellchecker plugin doesn't seem to work properly. There are several, similar bug reports and not one working example:

http://www.tinymce.com/wiki.php/Plugin:spellchecker (Comments)
http://www.tinymce.com/develop/bugtracker_view.php?id=6061

Could you please add the spellchecker to the full featured TinyMCE demo here on tinymce.com? That would help a lot! For once, we can see it actually works if correctly set up, and secondly, we'll the data structure that is expected as response from the server.

Kind regards and thanks for your hard work,
Simon

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6179](http://archive.tinymce.com/develop/bugtracker_view.php?id=6179) posted by [SimonStone](http://archive.tinymce.com/profile.php?name=SimonStone)_
> 
> _**Tags:** [firefox msie safari chrome opera spellchecker plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
I am closing this issue due to old age, if you still have this issue in the latest version of TinyMCE please [open up a new issue ⭐️](https://github.com/tinymce/tinymce/issues/new).
