### ISSUE TITLE
v7 how to display html source code？

### ISSUE THREAD

**Issue by rfrkk** [tinymce/tinymce#9545]
document : https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#encoding-types

codepen : [https://codepen.io/rfrkk/pen/vYMjWEp](https://codepen.io/rfrkk/pen/vYMjWEp)

What is the actual result : it didn't succeed

**Comment by TheSpyder** [comment]
You're looking for HTML encoding, not entity encoding. Try this:

`&lt;div class="paper"&gt;this is an html source code text&lt;/div&gt;`
