### ISSUE TITLE
how  to add header and footer  when printing?expected reply....

### ISSUE THREAD

**Issue by huanhuanSun** [tinymce/tinymce#9565]
## 📝 Provide a description of the new feature or improvement
*Describe your idea for the new feature or improvement*

### 🫶 What is the motivation?
*Pitch why this feature or improvement should be implemented.*

### 🔗 What is the consequence of not having this feature?
*This helps understand the underlying pain-points*

### 🚦 How important would you rate the requested feature or improvement?
*Choose from nice-to-have, important or critical.*

---

If you'd like to see this implemented sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @huanhuanSun. The concept of page headers and footers does not really exist in HTML. Check out our commercial export to PDF feature where you can include headers and footers and print that PDF. [Learn more at our website](https://www.tiny.cloud/tinymce/features/export-pdf/)
