### ISSUE TITLE
Regular expression parsing problem

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#957]
TinyMCE takes long time (or crashes) when parsing some text of mine. It happens on initialization and if the text is inserted as HTML (I guess it is the same parsing routine that is used and causes the problem).

Im running Windows 7 with Google Chrome Version 28.0.1500.72 m

Steps to reproduce in TinyMCE 3.x (which is where I discovered the problem):
1. Copy the entire text from http://www.aw-media.dk/misc/tinymce_load.txt
2. Go to http://www.tinymce.com/tryit/3_x/full.php
3. Click the HTML button
4. Delete ALL content in the popup
5. Insert the text from your clipboard (that copied in step 1)
6. Press the "update" button in lower left corner

Steps to reproduce in TinyMCE 4:
1. Copy the entire text from http://www.aw-media.dk/misc/tinymce_load.txt
2. Go to http://www.tinymce.com/tryit/full.php
3. Click "Tools" -> "Source code"
4. Delete ALL content in the popup
5. Insert the text from your clipboard (that copied in step 1)
6. Press the "OK" button in lower right corner

Expected result: Ability to proceed working in TinyMCE

Actual result: Freezing (due to javascript running forever)

------------- My own findings (TinyMCE v3.x):

By profiling the javascript in chrome i found that this regular expression is consuming the time: &ltg;(?:(?:!--([\w\W]_?)-->)|(?:![CDATA[([\w\W]_?)]]>)|(?:!DOCTYPE([\w\W]_?)>)|(?:\?([^\s\/&ltg;>]+) ?([\w\W]_?)[?/]>)|(?:\/([^>]+)>)|(?:([^\s\/&ltg;>]+)((?:\s+[^"\'>]+(?:(?:"[^"]_")|(?:\'[^\']_\')|[^>]_))_|\/)>))

It seems to be generated from the file "tiny_mce_src.js" line 2221 - 2228:
            tokenRegExp = new RegExp('&ltg;(?:' +
                '(?:!--([\w\W]_?)-->)|' + // Comment
                '(?:!\[CDATA\[([\w\W]_?)\]\]>)|' + // CDATA
                '(?:!DOCTYPE([\w\W]_?)>)|' + // DOCTYPE
                '(?:\?([^\s\/&ltg;>]+) ?([\w\W]_?)[?/]>)|' + // PI
                '(?:\/([^>]+)>)|' + // End element
                '(?:([^\s\/&ltg;>]+)((?:\s+[^"\'>]+(?:(?:"[^"]_")|(?:\'[^\']_\')|[^>]_))_|\/)>)' + // Start element
            ')', 'g');

The lines above is also included in
- tiny_mce_jquery_src.js
- tiny_mce_prototype_src.js (not sure if this is a Magento file?)
- SaxParser.js
- and maybe other files?
  > _**Legacy information imported from TinyMCE bug tracker:**_
  >
  > _[#T6186](http://archive.tinymce.com/develop/bugtracker_view.php?id=6186) posted by [kaspern](http://archive.tinymce.com/profile.php?name=kaspern)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by gabor-farkas** [comment]
I've also faced a similar problem recently (with the latest 4.4.3). A source like ```<span rel1 rel2 rel3 rel4 rel5 rel6 rel7 rel8 rel9 rel10 rel11 rel12 rel13``` will hang up the browser for quite a long time, stuck in the regexp evaluation.
I've also identified that the problematic part of the regexp is ```[^>]*``` - I'm not sure if this regexp part has a more performant alternative.

**Comment by mboudreau** [comment]
Just hit this issue as well.  This has been a problem for 4 years and nobody can get it fixed?

For me, all I had to do is add an less-than character within a sentence to make it crash, like:

```
Lorem Ipsum
"Neque  (<2 boro) porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tortor justo, fermentum sed pulvinar non, gravida vitae justo. In hac habitasse platea dictumst.
```

I understand that the user pasted a character that probably shouldn't be there in source code, but this wouldn't be an issue in any other source code parsers since they would make sure that the open tag is valid (they can't start with a number) and that it's closed properly before trying to parse the attributes.

Seriously, get your parser fixed, it's long overdue.

**Comment by jayarjo** [comment]
Related: https://github.com/tinymce/tinymce/issues/3300

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
