### ISSUE TITLE
tinyMCE 6.7.0. steals focus from other form fields

### ISSUE THREAD

**Issue by thooyork** [tinymce/tinymce#9582]
Having tinyMCE integrated in a form with other formcontrols like text-inputs.

Setting the focus to the first text-input in the Form I would expect, that this first field has focus.

What happens instead is, that on init of tinyMCe editor - tiny steals the focus from the text-input.

I found out that the code that seems to trigger this behaviour is:

`editor.on("init", () => {
      editor.execCommand("fontSize", false, "12pt");
  });`

if I remove this execCommand Line tinyMCe will not steal focus.

### ✔️ Expected result
Focus should be on the first text-input.

### ❌ Actual result
tinyMCE steals focus from other formcontrols on initialisation

### ❓ Possible solution
No idea, all I know is that it has something todo with execCommand ...

## 📃 Other details
- Browser: all browses (tested in chrome, FF, webkit and edge)
- OS: ubuntu 22.04 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
ah, I understand the problem now.

We usually expect commands to be in response to user action. If all you want to do is change the default font size, there are [better ways](https://www.tiny.cloud/docs/tinymce/latest/add-css-options).

**Comment by lostkeys** [comment]
As @TheSpyder explains above, the commands are to create custom user-initiated actions, and you'd need focus to work as expected for accessibility. So at this time we have no plans to change the current behavior.
— Fredrik, Product Manager
