### ISSUE TITLE
missing text while pasting from word 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#959]
Description of problem:

Steps to reproduce:
1. Go to try it link of tinymce.com 
2. Copy the whole text from the attached file and paste into the Example Column
3. Compare the contents
4. You will find substantial text is missing

Expected result:
       Full text on paste

Actual result:
       Partial text on paste, substantial portion of text is missing.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6188](http://archive.tinymce.com/develop/bugtracker_view.php?id=6188) posted by [sguptaca](http://archive.tinymce.com/profile.php?name=sguptaca)_

> _**Tags:** [firefox msie safari chrome opera]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
