### ISSUE TITLE
Copied Word document highlighted text and table does not show appropriately on iPad OS 17.4.1

### ISSUE THREAD

**Issue by yelyzavetak** [tinymce/tinymce#9593]
## 📝 Provide detailed reproduction steps (if any)
The web app is using the `tinymce@5.10.5` and `@tinymce/tinymce-react@3.12.6` and the issue is specific on iPadOS 17.4.1 any browser. When the user tries to copy from MS Office Word on iPadOS 17.4.1 and paste it into the TinyMCE editor it loses the formatting, especially highlighted text and table styles. The web app uses `paste` and `table` plugins, and the `paste_retain_style_properties` is set to 'all'. I can provide the full component property settings if necessary.

### ✔️ Expected result
The expected result is to keep all formatting and highlight the text in the table's cell, keep table's formatting: 
![Screenshot 2024-04-24 at 08 07 14](https://github.com/tinymce/tinymce/assets/55834183/3500ac81-ff65-4650-aa7d-6d4147028c2f)

### ❌ Actual result
On iPadOS 17.4.1 copy from MS Office Word loses the formatting in the table: 
![Screenshot 2024-04-24 at 08 02 18](https://github.com/tinymce/tinymce/assets/55834183/49249f6d-63d7-4b7c-8994-12a76cf6c5bf)

### ❓ Possible solution
Have you fixed this in the newer version? For example, does the new `powerpaste` plugin work as expected on iPadOS 17.4.1? If so, please let me know what version contains the fix. Could you please provide a quick-fix solution for this issue with the provided TinyMCE versions above?

## 📃 Other details
- Browser: any browser
- OS: iPadOS 17.4.1
- MS Office Word

Thank you!

**Comment by TheSpyder** [comment]
We don't support TinyMCE 5 anymore (although we do have an LTS offering available). The open source word import feature was removed in TinyMCE 6, so any upgrade for you will require powerpaste to keep that functionality.

Unfortunately, last time we checked MS Office for iPad did not provide full rich text data on the clipboard for TinyMCE (or any browser-based editor) to support. You can confirm this by pasting into our [clipboard viewer tool](https://static.ephox.com/clipboard/clipboardtest.html), which shows the raw data we have to work with. You could try our [full-featured demo](https://www.tiny.cloud/docs/tinymce/latest/full-featured-premium-demo/) to get an idea of how PowerPaste differs from the old open source paste code, or feel free to [contact our sales team](https://www.tiny.cloud/contact/) to discuss your options.
