### ISSUE TITLE
在页面滚动时 插入表格的弹出层位置不正确

### ISSUE THREAD

**Issue by 2869783364** [tinymce/tinymce#9595]
vue3  tinymce4.0.7
在页面滚动时 插入表格的弹出层位置不正确
![image](https://github.com/tinymce/tinymce/assets/104182261/2d4fb292-8a46-4912-9c83-0ff0f1bf8c0c)
![image](https://github.com/tinymce/tinymce/assets/104182261/c3f1deff-e025-43a2-a16c-aac7dbddd82d)
![image](https://github.com/tinymce/tinymce/assets/104182261/86b3a26a-109f-4699-af64-448137028d2e)
页面滚动的越多,位置偏离的也越多

**Comment by TheSpyder** [comment]
We only offer support in English, sorry.

Based on a google translation of your query, it's likely we fixed this with the [ui_mode](https://www.tiny.cloud/docs/tinymce/latest/ui-mode-configuration-options/#ui_mode) setting in TinyMCE 6.4
