### ISSUE TITLE
How to stop tinymce parse checking and correcting HTML code automatically when it readed data from databas?

### ISSUE THREAD

**Issue by rfrkk** [tinymce/tinymce#9596]
I made a simple background, only put the tinymce ver 6 editor, input text and html code and save it to the database.

Step1.  i paste this html code for test
`<a class="fl1 page" name="59"><div style="color: gray;">page 59</div></a>`

Step2.  This data is recorded by database. It is correct now.
`<p>&lt;a class="fl1 page" name="59"&gt;&lt;div style="color: gray;"&gt;page 59 &lt;/div&gt;&lt;/a&gt;</p>`

Step3. Then, let tinymce read this data storing by database, but this HTML code is automatically checking and correcting by tinymce after reading.This is not the result I want. 
`<p><a class="fl1 page" name="59"></a></p>`
`<div style="color: gray;"><a class="fl1 page" name="59"></a>page 59</div>`

Step4. This is not the result I want. It will display error in web page.

I hope tinymce ver 6 stop checking and correcting HTML code automatically when it readed data from databas, how can i do?

**Comment by TheSpyder** [comment]
Are you using a textarea to load content into the editor? The value of a textarea must be HTML encoded. Browsers do accept un-encoded HTML tags in textarea elements, but that's not technically valid. Any HTML encoded value will be decoded, just as it is when displayed within any other element.

Any content you load into a textarea must be HTML encoded, which means that if you have HTML encoded values already they will be double-encoded.

Here's your example properly encoded in a textarea.
https://fiddle.tiny.cloud/MA3eSph8NI/0

**Comment by rfrkk** [comment]
> I made a simple background, only put the tinymce ver 6 editor, input text and html code and save it to the database.
> 
> Step1. i paste this html code for test `<a class="fl1 page" name="59"><div style="color: gray;">page 59</div></a>`
> 
> Step2. This data is recorded by database. It is correct now. `<p>&lt;a class="fl1 page" name="59"&gt;&lt;div style="color: gray;"&gt;page 59 &lt;/div&gt;&lt;/a&gt;</p>`
> 
> Step3. Then, let tinymce read this data storing by database, but this HTML code is automatically checking and correcting by tinymce after reading.This is not the result I want. `
> 
> page 59
> `
> 
> Step4. This is not the result I want. It will display error in web page.
> 
> I hope tinymce ver 6 stop checking and correcting HTML code automatically when it readed data from databas, how can i do?



> I made a simple background, only put the tinymce ver 6 editor, input text and html code and save it to the database.
> 
> Step1. i paste this html code for test `<a class="fl1 page" name="59"><div style="color: gray;">page 59</div></a>`
> 
> Step2. This data is recorded by database. It is correct now. `<p>&lt;a class="fl1 page" name="59"&gt;&lt;div style="color: gray;"&gt;page 59 &lt;/div&gt;&lt;/a&gt;</p>`
> 
> Step3. Then, let tinymce read this data storing by database, but this HTML code is automatically checking and correcting by tinymce after reading.This is not the result I want. `<p><a class="fl1 page" name="59"></a></p>` `<div style="color: gray;"><a class="fl1 page" name="59"></a>page 59</div>`
> 
> Step4. This is not the result I want. It will display error in web page.
> 
> I hope tinymce ver 6 stop checking and correcting HTML code automatically when it readed data from databas, how can i do?



> Are you using a textarea to load content into the editor? The value of a textarea must be HTML encoded. Browsers do accept un-encoded HTML tags in textarea elements, but that's not technically valid. Any HTML encoded value will be decoded, just as it is when displayed within any other element.
> 
> Any content you load into a textarea must be HTML encoded, which means that if you have HTML encoded values already they will be double-encoded.
> 
> Here's your example properly encoded in a textarea. https://fiddle.tiny.cloud/MA3eSph8NI/0

My form setting is 
` <div class="form-group">`
  `<label for="title">book content</label>`
  `<textarea id="itscontent"><?= html_entity_decode($data["content"]) ?></textarea>`
  `</div>`

I get more simple example to prove that this is tinymce converted html syntax.

`<a class="fl1 page" name="59">page 59</a>`
this is an html element of "A" with class and name att.

1. save data to database. 
movie : the html code is correctlly all right when checking source code, and its code stores to database.
![錄製_2024_04_29_10_16_06_293](https://github.com/tinymce/tinymce/assets/137764/442ede2b-383d-48d4-8a62-35f6ff06eadd)

2. then read data from database
movie: then read content from database, but in tinymce the html is not correctlly. The original content in database is still correctlly. it becomes `<p><a class="fl1 page" name="59"></a>page 59</p>`, "page 59" was out of A elemt.

![錄製_2024_04_29_10_16_37_217](https://github.com/tinymce/tinymce/assets/137764/4054938d-4d0f-48c9-bfbd-fd6426174a3d)

How can i make tinymce to stop handle it？

**Comment by TheSpyder** [comment]
I repeat, it's not TinyMCE. It's how you load the content into the textarea. You are using what appears to be PHP with `html_entity_decode()` but you want an _encoder_, not a _decoder_, which I believe is PHP `htmlentities()`.

**Comment by rfrkk** [comment]
> I repeat, it's not TinyMCE. It's how you load the content into the textarea. You are using what appears to be PHP with `html_entity_decode()` but you want an _encoder_, not a _decoder_, which I believe is PHP `htmlentities()`.

### Situation 1-1 :
this is the pure textarea 1.

database storing:
`<p>&lt;a class="fl1 page" name="59"&gt;page 59&lt;/a&gt;</p>`

now, it fetches from database and uses php htmlspecialchars()

it is the result:
`<p>&lt;a class="fl1 page" name="59"&gt;page 59&lt;/a&gt;</p>`

### Situation 1-2:
this is the tinymce ver 6

database storing:
`<p>&lt;a class="fl1 page" name="59"&gt;page 59&lt;/a&gt;</p>`

now, it fetches from database and uses php htmlspecialchars()

tinymce editor show the result:
`<p><a class="fl1 page" name="59">page 59</a></p>`

and see tinymce tools -> source code：
`<p>&lt;a class="fl1 page" name="59"&gt;page 59&lt;/a&gt;</p>`

### Situation 2-1 :
this is the pure textarea 2.

database storing:
`<p>&lt;a class="fl1 page" name="59"&gt;page 59&lt;/a&gt;</p>`

now, it fetches from database and uses php html_entity_decode()

it is the result:
`<p><a class="fl1 page" name="59">page 59</a></p>`

**Situation 2-2:**
this is the tinymce ver 6

database storing:
`<p>&lt;a class="fl1 page" name="59"&gt;page 59&lt;/a&gt;</p>`

now, it fetches from database and uses php html_entity_decode()

tinymce editor show the result: (picture)
![Screenshot 2024-04-30 at 06-57-33](https://github.com/tinymce/tinymce/assets/137764/b3fd0f91-6f69-4537-aa52-1438ceae2b76)


and see tinymce tools -> source code：
`<p><a class="fl1 page" name="59"></a>page 59</p>`


In conclusion, my guess is that whether PHP uses htmlspecialchars or html_entity_decode, the html code will be processed by the tinymce editor.

Please look at situations 1-1 and 1-2. tinymce(1-2) will encode/escape the html. The final result of this html is as expected and has no errors.

However, please look at situations 2-1 and 2-2. tinymce(2-2) will encode/escape and modify the html, so the final result of this html is not as expected and has errors.

It can be seen from 1-1 and 2-1 that php and textarea will not modify any html rules, they just do their own work; and tinymce will process the string of html_entity_decode, causing some html to be changed.

The example I gave is very obvious. <p><a class="fl1 page" name="59">page 59</a></p> will be modified by tinymce to <p><a class="fl1 page " name="59"></a>page 59</p>, page 59 is out of A tag by tinymce processing.

I speculate that tinymce automatically corrects HTML, perhaps following the W3C HTML rules. A tags cannot contain block tags, but this is a recommended rule, not mandatory. Almost all rules can be broken after CSS processing. There are countless such cases.

In the future, can tinymce launch a function that stop checking and modifying html. Please give me more advice.
