### ISSUE TITLE
Some of the Button are missing the first time in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#960]
I am using tinymce with JGraph, and I have noticed that with I open up the editor for editing the first time some of the buttons are missing. The buttons reappear when I open the tinymce editor the second time. Attached please see a screenshot.

This is happening only in IE 8 and IE 9. Its working fine in Chrome and Firefox.

Anyone else having the same issue?

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6184](http://archive.tinymce.com/develop/bugtracker_view.php?id=6184) posted by [rishabh50](http://archive.tinymce.com/profile.php?name=rishabh50)_

> _**Tags:** [msie msie8 msie9 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
