### ISSUE TITLE
Adding an iframe tag with tinymce7 includes sandbox

### ISSUE THREAD

**Issue by emaeba** [tinymce/tinymce#9608]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
If you insert an iframe tag like the one below in Tinymce7, sandbox="" will be included in the attribute.
In the case of Tinymce6, it did not fit.
### ✔️ Expected result
*What is the expected result of the above steps?*
Add the following tag to Tinymce7
<iframe title="YouTube video player" src="YotubeURL" width="560" height="315" frameborder="0"></iframe>

### ❌ Actual result
*What is the actual result of the above steps?*
sandbox attribute added
<iframe title="YouTube video player" src="YotubeURL" width="560" height="315" frameborder="0" sandbox=""></iframe>

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: … Chrome
- OS: … Windows
- First affected version: …　　TinyMCE version 7.0.1
- Worked in version: …  TinyMCE version 6.8.2

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
This was a security fix for a CVE. The documentation explains how to turn it off if you aren't concerned about the safety of your iframes.
https://www.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#security-fixes

The default exclusion list does include youtube, so that specific website shouldn't be a problem.

**Comment by martabitbrain** [comment]
> This was a security fix for a CVE. The documentation explains how to turn it off if you aren't concerned about the safety of your iframes. https://www.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#security-fixes
> 
> The default exclusion list does include youtube, so that specific website shouldn't be a problem.

It includes youtube, but it does not include youtube's domain for enhanced privacy mode (If you are on a video -> share -> scroll down and mark the checkbox, see how the domain changes to youtube-nocookie.com). This _might_ be what happened to the OP.

Just added a feature request for it here: https://github.com/tinymce/tinymce/issues/9617 :)
