### ISSUE TITLE
Resizing image in table cell using handlers

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#961]
Description of problem:
You can't resize an image in table cell to make it bigger that the cell. 
IN MSIE 9 and 10 it's possible to make it bigger but you cant shrink it back.
Tested on MSIE 8 WinXP and MSIE 9/10 in Win7.

Steps to reproduce:
1. Insert small image in table cell
2. Make image bigger using handlers
3. Try to make it bigger than the cell

Expected result:
Cell should expand.

Actual result:
Text under cursor is selected and image is as big as the cell.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6187](http://archive.tinymce.com/develop/bugtracker_view.php?id=6187) posted by [kamil.musial](http://archive.tinymce.com/profile.php?name=kamil.musial)_

> _**Tags:** [msie msie8 msie9 msie10 table image resize handlers]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
