### ISSUE TITLE
TinyMCE control icons mising

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#963]
Description of problem:
TinyMCE control icons are missing and few converting to hyperlinks

Steps to reproduce:
1. In our application we use tinymce control to edit the contents.
2. we add reports and edit part of the report
3. when adding more than 30 reports controls are messed up
4. when the reports are reduced to 25 it works fine
5. we also observed that before the control disappears the color changes

Expected result:
Control icons should not be messed up
Actual result:
Controls are missing.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6190](http://archive.tinymce.com/develop/bugtracker_view.php?id=6190) posted by [pasumarthydavid](http://archive.tinymce.com/profile.php?name=pasumarthydavid)_

> _**Tags:** [firefox msie safari chrome opera 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
