### ISSUE TITLE
Help plugin failed to load

### ISSUE THREAD

**Issue by Y-V-H** [tinymce/tinymce#9633]
## 📝 Provide detailed reproduction steps (if any)
Hello everyone,
I encountered an error after migrating from version 6.4.2 to 6.8.3. If I downgrade the version, everything works fine. I checked the release notes for version 6.5.1 but didn't find any useful information that could help me. I hope I didn't overlook anything.
Plugins that I'm using:
`plugins: ['autoresize', 'help', 'autolink', 'lists', 'link', 'image', 'fullscreen', 'media', 'code', 'autoresize'],`
I also use:
`help_tabs: ['shortcuts', 'keyboardnav'],`

### ✔️ Expected result
*A user can trigger the help dialog by clicking the help button or using the Alt+0 shortcut.*

### ❌ Actual result
*When this occurs, nothing happens, and an error appears in the console.*
![image](https://github.com/tinymce/tinymce/assets/11545672/bf6e2b41-16c2-48a3-9995-66a274289f33)

## 📃 Other details
- Browser: Chrome (Version 124.0.6367.155) or FF (125.0.3 (64-bit))
- OS: Ubuntu 22.04.4 LTS or windows 11 
- First affected version: TinyMCE 6.5.1 and late
- Worked in version: TinyMCE 6.4.2 and earlier
- React: "17.0.2"
- Node: v20.10.0
- npm: 10.2.3
- @tinymce/tinymce-react": "5.0.1"
- Vite: "5.0.12",
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
It's this change in 6.5.0:
https://github.com/tinymce/tinymce/blob/df90c6e6b2a3a79665aa297081d62debb2decfef/modules/tinymce/CHANGELOG.md#L304

This release added additional files in the distribution that are missing from your deployment. The files are there in the NPM package.
https://unpkg.com/browse/tinymce@6.5.0/plugins/help/js/i18n/keynav/

**Comment by Y-V-H** [comment]
Hello @TheSpyder 
Firstly, thank you for your response regarding my issue.
I forgot to mention that even after updating to version 6.8.3, I still encounter issues with loading files from `node_modules/tinymce/plugins/help/js/i18n/keynav. `
![image](https://github.com/tinymce/tinymce/assets/11545672/1035128b-5422-4228-9fac-d6d183c4f171)


It seems that the files are present but not loading as expected.

**Comment by TheSpyder** [comment]
Maybe it's a configuration issue with your webserver?
