### ISSUE TITLE
👍 Padding on Tables Elements doesn't work in some cases.

### ISSUE THREAD

**Issue by TopCoder02** [tinymce/tinymce#9640]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. [Tiny.Fiddle](https://fiddle.tiny.cloud/Wm42acSOau/3) - There should be a 10px padding on top, but it's not rendered in the TinyMCE WYSWYG engine
2. [JSFIDDLE](https://jsfiddle.net/jLao5yh2/) - This is how it should render, you can see the padding around it. 

### ✔️ Expected result
*What is the expected result of the above steps?*
It should render with padding on top of the table element, like it does in the browser.

### ❌ Actual result
*What is the actual result of the above steps?*
No padding is shown on top of the table element

## 📃 Other details
- Browser: ALL
- OS: ALL
- First affected version: 5.5 
- Worked in version: 5.4 (didn't really work right in 5.4, but you can see a the change from 5.4 to 5.5

**Comment by TheSpyder** [comment]
Our default styles have `border-collapse` set:
https://github.com/tinymce/tinymce/blob/f34c4bbcde5cad04232b3e4c5429ec52557fcbff/modules/oxide/src/less/skins/ui/default/content.less#L7-L9

You could configure custom styles that restore this to `border-collapse: separate`.
https://www.tiny.cloud/docs/tinymce/latest/add-css-options/

**Comment by TopCoder02** [comment]
Didn't realize this was the issue, thank you. Such an easy fix.
