### ISSUE TITLE
TinyMCE Version 6 Hyperlink Issue - default_link_target not working

### ISSUE THREAD

**Issue by smasud98** [tinymce/tinymce#9643]
I am trying to add a hyperlink which will open in a new window. It isn't working because the `<a>` tag needs the target=_blank attribute to be set. I tried adding the following properties to my editor which I found in the docs:

default_link_target: "_blank",
link_default_target: "_blank",
extended_valid_elements: 'a[href|target=_blank]',
target_list: [
        {title: 'New page', value: '_blank'}
]

I've tried adding various combinations of the above properties individually and together. When I inspect my hyperlink, I only see the rel="noopener" property. According to the docs, I should be seeing the target="_blank" attribute.

Can I please get some help with this? I'm not sure if I am missing something or if this is a bug with TinyMCE.

Thanks

Using: tinymce 6.7.2^, @tinymce/tinymce-angular ^7.0.0, Angular 15

**Comment by TheSpyder** [comment]
The docs for this are here, and it should work without needing to modify the valid elements: https://www.tiny.cloud/docs/tinymce/latest/link/#link_default_target

How are you inserting the link? Can you make a replication case for us?

**Comment by smasud98** [comment]
I tried this too. Same issue. 

To make the link, I just added 'link' to the plugins. To insert, I highlight the text I want to add the hyperlink to and paste the URL into the popup that appears when I insert 'Link' and set it to open in a New Window. 

I tried to replicate the docs by adding only the link_default_target: "_blank" and am still not seeing the target = _blank attribute.

I also noticed someone else had this issue in the past (https://github.com/tinymce/tinymce/issues/4913)  and it was said to have been resolved in version 6.8.2 but I'm still seeing the error after making the switch.

**Comment by TheSpyder** [comment]
If you select `new window` in the link dialog it should work even with no other settings configured, just the `link` plugin. Please build a replication case using https://fiddle.tiny.cloud or a similar tool.

**Comment by smasud98** [comment]
Looks like you were right. I should've investigated this better. What I was doing was saving the HTML generated in the editor and trying to click the link from there. Problem is that I was first running the HTML through DOMPurify which is where the target=_blank is getting filtered out. So TinyMCE seems to be working fine. Sorry about that and thanks for your prompt response.

**Comment by TheSpyder** [comment]
For the record, we ship DOMPurify inside TinyMCE (configured to allow the things specified in the TinyMCE config). So you might not need it if that's the only place you run DOMPurify.
https://www.tiny.cloud/docs/tinymce/latest/security/#sanitizing-html-input-to-protect-against-xss-attacks
