### ISSUE TITLE
Error: Can't resolve 'node_modules/tinymce/plugins/template/plugin.js' after V7 update

### ISSUE THREAD

**Issue by TobiasJu** [tinymce/tinymce#9644]
## 📝 Provide detailed reproduction steps (if any)
1. Set tinymce to Version **7.1.0** from **6.8.3** in the package.json
2. Run `npm i`

### ✔️ Expected result
`nx s` runs normally

### ❌ Actual result

> Error: Can't resolve 'node_modules/tinymce/plugins/template/plugin.js'

## 📃 Other details
- Browser: Chrome
- OS: Windows
- First affected version: 7.0.0
- Worked in version: 6.8.3

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Your browser console logs would've been showing it as deprecated since TinyMCE 6.4. And the logs now should show it's been removed.
https://www.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#accompanying-open-source-plugin-end-of-life-announcement
