### ISSUE TITLE
Repeated header/letterhead and footer

### ISSUE THREAD

**Issue by aayushsapkota9** [tinymce/tinymce#9650]
## 📝 Provide a description of the new feature or improvement
*Describe your idea for the new feature or improvement*
Is there a way to add repeated header on tiny mce? I need a repeated footer and header on every page whilte content beign as noraml
### 🫶 What is the motivation?
*Pitch why this feature or improvement should be implemented.*
It would make tinymce more useful for office tasks

### 🔗 What is the consequence of not having this feature?
*This helps understand the underlying pain-points*

### 🚦 How important would you rate the requested feature or improvement?
*Choose from nice-to-have, important or critical.*
I beleive it is an important feature to have

---

If you'd like to see this implemented sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi. This is a feature we cannot really implement as the concept of pages does not exist in HTML. Calculating the height of a paper and intelligently break more complex HTML elements like tables & images while still retaining a sane HTML that can be used outside of the editor is not feasible. That said, you should check out our [Export to PDF feature](https://www.tiny.cloud/tinymce/features/export-pdf/) which allows for defining footers and headers on the generated PDF document.
