### ISSUE TITLE
multiple files import when we create multiple instances

### ISSUE THREAD

**Issue by DishantWeb** [tinymce/tinymce#9659]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. …
<script type="text/javascript">
tinymce.init({
    selector: "#content",
    plugins: [
        "advlist", "anchor", "autolink", "charmap", "code", "fullscreen",
        "help", "image", "insertdatetime", "link", "lists", "media",
        "preview", "searchreplace", "table", "visualblocks",
    ],
    toolbar: "undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
});
tinymce.init({
    selector: "#content2",
    plugins: [
        "advlist", "anchor", "autolink", "charmap", "code", "fullscreen",
        "help", "image", "insertdatetime", "link", "lists", "media",
        "preview", "searchreplace", "table", "visualblocks",
    ],
    toolbar: "undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
});
tinymce.init({
    selector: "#content3",
    plugins: [
        "advlist", "anchor", "autolink", "charmap", "code", "fullscreen",
        "help", "image", "insertdatetime", "link", "lists", "media",
        "preview", "searchreplace", "table", "visualblocks",
    ],
    toolbar: "undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
});
tinymce.init({
    selector: "#content4",
    plugins: [
        "advlist", "anchor", "autolink", "charmap", "code", "fullscreen",
        "help", "image", "insertdatetime", "link", "lists", "media",
        "preview", "searchreplace", "table", "visualblocks",
    ],
    toolbar: "undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
});
</script>

<form method="post" action="/dump">
    <textarea id="content" name="content"></textarea>
	<textarea id="content2" name="content2"></textarea>
	<textarea id="content3" name="content3"></textarea>
	<textarea id="content4" name="content4"></textarea>
</form>

### ✔️ Expected result
*What is the expected result of the above steps?*
Import only ones in any page

### ❌ Actual result
*What is the actual result of the above steps?*
Import multiple files when page load or multiple instances load
![Screenshot_1](https://github.com/tinymce/tinymce/assets/169239989/70bc3133-c628-41ce-9ede-928aaa3437ce)

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*
Import files on head section or end of body section then second time check if files are import or not if not then import else skip it.

## 📃 Other details
- Browser: …
- OS: …
- First affected version: … 5
- Worked in version: … 7.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Each editor creates an `iframe` to edit, unless you're using inline mode. Each iframe loads the default content CSS (plus any other content CSS files that are configured, such as skins).

Note that you have `disable cache` selected in your dev tools; without that every CSS file after the first will be cached and not send a request to the server.

If you're worried about extra files being downloaded you could always bundle the editor.
