### ISSUE TITLE
Text jumps back in disabled Editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#966]
Description of problem:
Text jumps back on submit in tinymce when editor is disabled.

Steps to reproduce:
1. Paste some text into the editor
2. Disable Editor with tinymce.get(id).hide(); 
3. Replace the Text in the plain textarea
4. Click on submit button

Expected result:
The text from the the plain text area should be posted

Actual result:
The text "jumps" back to the former pasted text is posted.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6193](http://archive.tinymce.com/develop/bugtracker_view.php?id=6193) posted by [bluescreen](http://archive.tinymce.com/profile.php?name=bluescreen)_
> 
> _**Tags:** [chrome paste]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
