### ISSUE TITLE
Initialize right to left attribute issues

### ISSUE THREAD

**Issue by qiangzhe01** [tinymce/tinymce#9661]
Initialize the directionality: rtl attribute, which will be set on the body of the text editor. When submitting editor content, the body element will not be obtained. Therefore, when the content is stored, there is no dir='rtl 'attribute on the element, resulting in the content not being displayed on the interface from right to left

**Comment by TheSpyder** [comment]
TinyMCE is designed to be customised to match the location where content will be rendered. If you don't have `dir=rtl` on the page where you will display the TinyMCE content, don't set the editor content to RTL.

Or, conversely, if you think the editor should be RTL in this way then you are responsible for making sure the rendered content is within an RTL div or page.
