### ISSUE TITLE
Document Margins

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#968]
Please make available the option to modify document margins.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6195](http://archive.tinymce.com/develop/bugtracker_view.php?id=6195) posted by [Milbilly](http://archive.tinymce.com/profile.php?name=Milbilly)_
> 
> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
