### ISSUE TITLE
content_css console and test throw error (using Angular and Jest)

### ISSUE THREAD

**Issue by Charon1502** [tinymce/tinymce#9688]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. Issue occured inside an Angular project with testing framework Jest
2. I am using TinyMCE version 7.1.1 (I just migrated from version 5.10.9 to 7.1.1)
3. I used (and still want to use) the configuration `content_css: false`
4. With this configuration the editor still works fine but my tests fail

I also encountered an issue while using the configuration `content_css: 'default'`
When using this configuration the httpRequest respond with a 404 error because of a mime type exception. The request is made with MIME type `text/html` but `text/css` is required.

For Testing I am using Jest within an angular project. I managed to reproduce the error in the following example:
https://stackblitz.com/edit/stackblitz-starters-ruviqm?file=src%2Ftinymce%2Ftinymce.component.ts

### Important Note
Within the provided example the editor is not rendered. This behaviour leads to the rendering of an empty html. 
I don't know why the editor is not rendered (probably I misconfigured something) but for the issue this makes no difference. In my actual project the editor is rendered but still has the same issue.

### ✔️ Expected result
Tests can be executed successfully with the configuration `content_css: false`
When using `content_css: 'default'` there is no error / failing http request

### ❌ Actual result
Running `yarn test` leads to: 
![image](https://github.com/tinymce/tinymce/assets/22888051/ae453853-f396-486c-a7e7-adb9b67bed59)
(error occures at [tinymce/modules/tinymce/src/core/main/ts/content/TransparentElements.ts:19:27)](https://github.com/tinymce/tinymce/blob/054671e930597a1edf45994132c97b72b163514a/modules/tinymce/src/core/main/ts/content/TransparentElements.ts#L19)

Using the configuration `content_css: 'default'` leads to a http error: 
![image](https://github.com/tinymce/tinymce/assets/22888051/4b7cfa0b-6623-454c-b51f-3763aa833f0f)

### ❓ Possible solution
Desired solution: 
- tests should be successfully executable with the configuration: `content_css: false` 
- and using `content_css: 'default'` should not lead to a http error

Minimal solution:  using `content_css: 'default'` should not lead to an error.

## 📃 Other details
- Browser: tested only using chrome browser
- First affected version: occured at migration from version 5.10.9 to 7.1.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
The error in tests might be JSDom, which doesn't implement `CSS.escape`. We don't support TinyMCE in JSDom.

The skin problem appears to be that you're bundling TinyMCE, which means you need to either
* bundle the styles as well (https://www.tiny.cloud/docs/tinymce/latest/introduction-to-bundling-tinymce/)
* set a [base url](https://www.tiny.cloud/docs/tinymce/latest/editor-important-options/#base_url) for the editor to find the resources it needs

**Comment by Charon1502** [comment]
@TheSpyder thanks for the advice. 
According to the bundling Issue: thanks for the provided links, but I didn't find a solution that worked in my case. Luckily, I found an Issue with a solution for my bundling issue (https://github.com/tinymce/tinymce/issues/9233). There importing `tinymce/skins/content/default/content.js` is mentioned which worked for me. Maybe it would be helpful for others to extend the bundling documentation by this import.
Nevertheless, the fact that TinyMCE doesn't support JSDom is a problem for me, but this seems not to be a TinyMCE issue,
