### ISSUE TITLE
Table borders are not preserved in preview

### ISSUE THREAD

**Issue by enoh-barbu** [tinymce/tinymce#9692]
Access this [link](https://developer.mozilla.org/en-US/docs/Web/API/Web_components#browser_compatibility) 
Copy the Browser compatibility table 
![image](https://github.com/tinymce/tinymce/assets/24221572/8b857362-edbd-471c-97b8-90b408a2ff76)
Paste into editor
Go to View -> Preview

### ✔️ Expected result
The copied table border should be displayed

### ❌ Actual result
![image](https://github.com/tinymce/tinymce/assets/24221572/4e28a8ad-dfaa-4b58-9e16-a07b0e677f3a)
The border of the table is not displayed

## 📃 Other details
- Browser: Chrome
- OS: Windows 11

---

Also, the border style in editor is dashed, not solid as in the source table

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
If you look at the editor it's showing the table with gridlines, implying there is no table border. You can try pasting it into a clipboard viewer ([we have one here](https://static.ephox.com/clipboard/clipboardtest.html)) to check; the browser does not copy the gridlines. Likely they were added by a class, which the browser also does not copy.

It's also browser dependent. Firefox doesn't seem to copy the table correctly at all.
