### ISSUE TITLE
how to Prohibit user input ？Do not set readonly。

### ISSUE THREAD

**Issue by PccCodesix** [tinymce/tinymce#9695]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. …
2. …
3. …

### ✔️ Expected result
*What is the expected result of the above steps?*

### ❌ Actual result
*What is the actual result of the above steps?*

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: …
- OS: …
- First affected version: …
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Sorry we need a bit more details than this. Please resubmit and fill in all the details.

**Comment by PccCodesix** [comment]
Thank you for your reply。
I encountered a special usage scenario。i want Do not allow users to input。but can use the  custom     
 quickbars_selection_toolbar to set underline,forecolor ...
  I set the editor readonly mode. but the  quickbars_selection_toolbar can not use ,I have also tried using the keyup keydown event, but it cannot prevent the user from entering ， Is there any way to achieve it？

**Comment by PccCodesix** [comment]
> Sorry we need a bit more details than this. Please resubmit and fill in all the details.

Thank you for your reply。
I encountered a special usage scenario。i want Do not allow users to input。but can use the custom
quickbars_selection_toolbar to set underline,forecolor ...
I set the editor readonly mode. but the quickbars_selection_toolbar can not use ,I have also tried using the keyup keydown event, but it cannot prevent the user from entering ， Is there any way to achieve it？
