### ISSUE TITLE
Add jump to item keyboard navigation to listBox control

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#970]
Standard browser controls let you jump to an item in a list by pressing the first character. TinyMCE listBox controls currently do not. Adding this capability natively would be a real boon and improve accessibility.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6197](http://archive.tinymce.com/develop/bugtracker_view.php?id=6197) posted by [natepixel](http://archive.tinymce.com/profile.php?name=natepixel)_
> 
> _**Tags:** [listbox keyboard]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
