### ISSUE TITLE
extended_valid_elements no works with script

### ISSUE THREAD

**Issue by JTorresConsulta** [tinymce/tinymce#9714]
Hi,
I am trying to inject script code into the editor text as <script> but Tiny is removed it despite i am following the docs suggestions:

https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#using-extended_valid_elements-to-allow-script-elements

`extended_valid_elements: 'script[src|async|defer|type|charset]'`

Here an example:

https://codepen.io/JTorresConsulta/pen/RwmQLON

If is not a bug.. How is the way to let <script> tags in content?

**Comment by lostkeys** [comment]
Hi @JTorresConsulta. Script tags are filtered out because they pose a serious XSS risk. Please consult the [security guide for available options](https://www.tiny.cloud/docs/tinymce/latest/security/)

**Comment by JTorresConsulta** [comment]
It seems fine for a children's sandbox, but could we adult developers take our own risks without a "daddy" to take care of us .. ? 

Why is it documented as a possibility then?  Delete it from docs for future adult developers that no want to waste their time

**Comment by JTorresConsulta** [comment]
Ok, could I use by my own risk please... ? Thank you
