### ISSUE TITLE
Bug in alignment?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#973]
Go to: http://fiddle.tinymce.com/5vdaab/2

A:
Select a line with "text line." and set aligment to "center" or "right".
Its working, but with a second new empty line.

B:
Select now the line with "more text" and set aligment to "center" or "right".
The text is moved a line up and placed directly after the text in the line before.

Is this a bug?

The title and description (left side) in fiddle is wrong. Sorry. Was a fork ^^

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6199](http://archive.tinymce.com/develop/bugtracker_view.php?id=6199) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_
> 
> _**Tags:** [chrome 4x]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/5vdaab/2_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
