### ISSUE TITLE
TinyMCE objects not cleared from memory after destroy

### ISSUE THREAD

**Issue by sendev1** [tinymce/tinymce#9730]
## 📝 Provide detailed reproduction steps (if any)
We use JQuery in our app. And we initialize tinymce as below

```
TextArea.prototype.render = function (callback) {
var tinymceConfig = {
      selector: 'textarea',
      .
      .
      .
      setup: function (ed) {
                 .
                 .
                 .
      }
}

TextArea.prototype.destroy = function () {
  // Destroys the editor instance by removing all events, element references or other resources that could leak memory
  tinymce.activeEditor.dom.destroy();
  tinyMCE.remove('textarea');
  // Destroys all internal references to the DOM to solve memory leak issues.
  tinyMCE.DOM.destroy();
}

```

### ✔️ Expected result
Should not see any tinymce objects in browser heap memory. The second snapshot was taken after calling the destroy method and still seeing tinymce objects in memory. How to clear all the tinymce objects from memory

![image](https://github.com/tinymce/tinymce/assets/68568448/1860499a-e8d2-4aff-bfeb-0c61c3c9b11f)

### ❌ Actual result
*What is the actual result of the above steps?*
 but even after calling destroy method still seeing tinymce objects in memory

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by sendev1** [comment]
Lots of string objects and objects are still there in memory even after calling destroy method

![image](https://github.com/tinymce/tinymce/assets/68568448/c37e9746-adc4-43d6-8d2d-d2231992a634)


![image](https://github.com/tinymce/tinymce/assets/68568448/d34f84b1-716a-497f-82c2-11bc9cc1271a)

**Comment by TheSpyder** [comment]
There are a lot of methods and references on the TinyMCE global that can't be removed just because there are no editors running.

I believe `(string)` memory usage includes static strings parsed by the browser from JavaScript in the page, not just strings created by the editor. Our icons are shipped in a way that would show up using that measurement:
https://unpkg.com/browse/tinymce@7.2.1/icons/default/icons.js
