### ISSUE TITLE
Error in "theme.min.js" when Format dropdown menu opens

### ISSUE THREAD

**Issue by pork1977** [tinymce/tinymce#9739]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.

So apologies on this first part about recreating... but I can't seem to reliably recreate this issue, but I'm pretty sure there's an issue here. What's happening is that when I click on the Format dropdown menu, the actual menu doesn't drop down but instead throws the following where "toLowerCase() is undefined".

![image](https://github.com/tinymce/tinymce/assets/29090134/eab6c586-a60e-46a1-995f-f60e311ab9d6)

If I go back and load the v6.7.3 script then it works (the Format menu drops down correctly)
If I attempt to load the next release of v6.8.1 then it breaks and it stays broken right up to v7.2 so I'm not too sure what's going on.

I've tried replicating on Fiddle for you guys, but it works. I suspect this _may_ have something to do with my parent DIVS, not entirely sure since I'm guessing Ws(t).toLowerCase() is some HEX value?

I can make it work though... if I remove both "styles" and "blocks" out of the menu options then the Format menu drops down as expected.

So this config will make it work:

```
let menu = {
            file: { title: 'File', items: 'newdocument restoredraft | preview | importword exportpdf exportword | print | deleteallconversations' },
            edit: { title: 'Edit', items: 'undo redo | cut copy paste pastetext | selectall | searchreplace' },
            view: { title: 'View', items: 'code revisionhistory | visualaid visualchars visualblocks | spellchecker | preview fullscreen | showcomments' },
            insert: { title: 'Insert', items: 'image link media addcomment pageembed codesample inserttable | math | charmap emoticons hr | pagebreak nonbreaking anchor tableofcontents | insertdatetime' },
            format: { title: 'Format', items: 'bold italic underline strikethrough superscript subscript codeformat | fontfamily fontsize align lineheight | forecolor backcolor | language | removeformat' },
            tools: { title: 'Tools', items: 'spellchecker spellcheckerlanguage | a11ycheck code wordcount' },
            table: { title: 'Table', items: 'inserttable | cell row column | advtablesort | tableprops deletetable' },
            help: { title: 'Help', items: 'help' }
        };
```

But this will break it (these are the default menu options, where the only difference from the above is that styles and blocks are added to the format menu item values).

```
let menu = {
            file: { title: 'File', items: 'newdocument restoredraft | preview | importword exportpdf exportword | print | deleteallconversations' },
            edit: { title: 'Edit', items: 'undo redo | cut copy paste pastetext | selectall | searchreplace' },
            view: { title: 'View', items: 'code revisionhistory | visualaid visualchars visualblocks | spellchecker | preview fullscreen | showcomments' },
            insert: { title: 'Insert', items: 'image link media addcomment pageembed codesample inserttable | math | charmap emoticons hr | pagebreak nonbreaking anchor tableofcontents | insertdatetime' },
            format: { title: 'Format', items: 'bold italic underline strikethrough superscript subscript codeformat | styles blocks fontfamily fontsize align lineheight | forecolor backcolor | language | removeformat' },
            tools: { title: 'Tools', items: 'spellchecker spellcheckerlanguage | a11ycheck code wordcount' },
            table: { title: 'Table', items: 'inserttable | cell row column | advtablesort | tableprops deletetable' },
            help: { title: 'Help', items: 'help' }
        };
```

Sorry I can't give more info than this! Hopefully someone will know what's going on - 👍

### ✔️ Expected result
*What is the expected result of the above steps?*

Format menu drops down when "styles" and "blocks" are in the menu option.

### ❌ Actual result
*What is the actual result of the above steps?*

No drop down menu is seen.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
That's this code
https://github.com/tinymce/tinymce/blob/47f4372be1286754d1dcef8762c7eb0a645e5d24/modules/tinymce/src/core/main/ts/fmt/Preview.ts#L295-L301

So the problem is as you surmised based on the element context of your document, that's the missing key to building a replication case.

I can see an edge case the TypeScript types don't account for where `value` is undefined, that would cause this error, but a replication would really help us nail it down.

**Comment by pork1977** [comment]
Thank you for that info, that's helpful. I'm trying to replicate it at the moment.

This simple page shows the problem, maybe you can see something out of place by looking through the DOM, but I'll keep working on it and see if I can get you a way to replicate it properly soon (hopefully!)

https://paul-testing-4.bubbleapps.io/version-test/testing-5

**Comment by pork1977** [comment]
Well, I've finally narrowed it down. The problem occurs when another library loads in the page, specifically a What3Word script of:

<script defer src="https://assets.what3words.com/sdk/v3/what3words.js?key=_*_What3Words API key_*_"></script>

As soon as that's removed, all is working fine. I don't think there's anything you need to do now but thanks for the assistance.

Paul
