### ISSUE TITLE
File browser button doesn't appear when inserting image

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#974]
Description of problem:

Steps to reproduce:
1. Install Drupal 7.23, TinyMCE 3.5.8, IMCE Wysiwyg bridge 7.x-1.0, Wysiwyg at 7.x-2.2
2. Use the Filtered HTML Text Format
3. Try to add an image in an editing session
4.
5.

Expected result: see the file browser button

Actual result: no file browser button

Note: the IMCE option does not appear under Buttons and Plugins when editing the Wysiwyg profile for the Filtered HTML Text Format.

I discovered the following: the code for the browser should be added when getBrowserHTML() is called by /libraries/tinymce/jscripts/tiny_mce/plugins/advimage/js/image.js (line 63), but the call (line 51 in /libraries/tinymce/jscripts/tiny_mce/utils/form_utils.js) to
tinyMCEPopup.getParam(option, tinyMCEPopup.getParam("file_browser_callback"));
returns undefined... 

I hope this is the right place to ask about this issue!

Thanks,
Lee
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6201](http://archive.tinymce.com/develop/bugtracker_view.php?id=6201) posted by [LNakamura](http://archive.tinymce.com/profile.php?name=LNakamura)_

> _**Tags:** [firefox msie safari firefox8 msie10 safari5 drupal7 3x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
