### ISSUE TITLE
Row of toolbar icons gets wrapped in IE10 with german language pack

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#975]
Description of problem:
Row of toolbar icons containing the "save" button gets wrapped in IE10, with inline mode, small toolbar items size and the german language pack.

Steps to reproduce:
1. start tinymce with the following configuration (fiddle doesn't support language packs):
 language: 'de',
 inline: true,
 toolbar_items_size: 'small',
 plugins: ["save"],
 toolbar1: "save styleselect",
 toolbar2: "bold italic"

Expected result:
toolbar 1 should take 1 row, shouldn't get wrapped

Actual result:
toolbar 1 takes 2 rows, because it gets wrapped

Note:
This can be fixed by adding 1 pixel to the width of the div with class="mce-container-body mce-stack-layout"
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6202](http://archive.tinymce.com/develop/bugtracker_view.php?id=6202) posted by [totaleasy](http://archive.tinymce.com/profile.php?name=totaleasy)_

> _**Tags:** [msie msie10 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
