### ISSUE TITLE
<p> tags added after a Select All in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#976]
Description of problem:
&ltg;p> tags added after a "Select All" in IE

Steps to reproduce:
1.Load attached default.html
2.Open with IE
3.Press Ctrl_A
4.Type in new text (overwriting selected "blah blah")
5.Note this does not occur with FireFox

I have added the settings which should block this behaviour.
      force_br_newlines : false,
      force_p_newlines : false,
      forced_root_block : '',

Expected result:
Some new text
Actual result:
&ltg;p>Some new text&ltg;/p>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6203](http://archive.tinymce.com/develop/bugtracker_view.php?id=6203) posted by [kenmccall@gmail.com](http://archive.tinymce.com/profile.php?name=kenmccall@gmail.com)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
