### ISSUE TITLE
Image outline doesn't follow on sudden scroll/height changes

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#979]
Description of problem:
if you click directly on an image and the content position changes, for example by inserting the toolbar at 0,0 and pushing the content down dynamically - then the outline to change image size stays one the image elements old  x, y position

Steps to reproduce:
1. insert any image into an editor and mark it as to resize
2. change image position by inserting element below/above it dynamically
3. watch the outlined drag-points stay put while image moves with DOM
4.
5.

Expected result:
the drag points to resize should detect all image repositions, not just on "real" scrolls.

Actual result:
it only moves with the picture if you use the mouse scroll, not DOM changes make the image move
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6206](http://archive.tinymce.com/develop/bugtracker_view.php?id=6206) posted by [bubach](http://archive.tinymce.com/profile.php?name=bubach)_

> _**Tags:** [chrome]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
