### ISSUE TITLE
Images can not be resized in editor

### ISSUE THREAD

**Issue by dchubad** [tinymce/tinymce#9799]
I was using a slightly out of date version of TinyMCE, but yesterday I noticed my editor suddenly stopped letting me resize images in the editor. Dragging the images and setting the size manually does nothing at all. I just updated to the latest version and still the same issue. It was all working fine before, but all of a sudden it just stopped letting me resize images. 
I am halfway through some intense programming on another project, and really don't need this issue right now, does anyone know how to resolve this please.

Thank you

**Comment by lostkeys** [comment]
Hi @dchubad, you need to provide more details and some way for us to reproduce the issue, until then there is little we can do to help.

**Comment by dchubad** [comment]
It's ok now, it was a css conflict
