### ISSUE TITLE
[Image dialog] Expose recalcSize to API

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#980]
In our file manager we want to call an API method that refreshes the dimensions fields in the image dialog.

In 3.x we could have it done like so:

[code]
var win = tinyMCEPopup.getWindowArg('window');

if (typeof(win.ImageDialog) != 'undefined') {
    if (win.ImageDialog.getImageData) {
        win.ImageDialog.getImageData();
    }
}
[/code]

Obviously, since tinyMCEPopup is going away we want to avoid using it.

Being able to call something like this would be ideal:

[code]
top.tinymce.activeEditor.plugins.image.recalcDimensions();
[/code]

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6207](http://archive.tinymce.com/develop/bugtracker_view.php?id=6207) posted by [simshaun](http://archive.tinymce.com/profile.php?name=simshaun)_
> 
> _**Tags:** [image api]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
