### ISSUE TITLE
Advlist Plugin is not creating nested items 1.2.3, i.i.i, a.b.c

### ISSUE THREAD

**Issue by oarashi** [tinymce/tinymce#9805]
With advlist Plugin pressing tab in the list not creating nested items e.g. 1.2.3, i.i.i, a.b.c

<img width="1432" alt="Screenshot 2024-07-31 at 4 35 11 PM" src="https://github.com/user-attachments/assets/f8408a0a-be4d-4c5c-aead-de304cde7185">

Expected behavior:
user creates list of three points: 1, 2, 3
user press tab button on point 2. Point 2 became 1.2 with left indent.

Current behavior:
user creates list of three points: 1, 2, 3
user press tab button on point 2. Point 2 became 1 with left indent.

The same for letters.

package.json
"@tinymce/tinymce-react": "5.1.1",

TextEditor.tsx
import { Editor } from '@tinymce/tinymce-react'

<Editor
        init={{
         /* setup code */
         plugins: 'advlist lists',
         content_style: `p { margin: 0; }`,
        }}
/>

Reproduce: https://www.tiny.cloud/docs/tinymce/latest/full-featured-open-source-demo/

**Comment by lostkeys** [comment]
Hi @oarashi. This is not possible using HTML alone. You can achieve it with using CSS counters and some custom list styling. [Here is an example](https://fiddle.tiny.cloud/Twhaab/1)
