### ISSUE TITLE
Conflict Between powerpaste and markdown Plugins

### ISSUE THREAD

**Issue by abc3675878** [tinymce/tinymce#9823]
## 📝 Provide detailed reproduction steps (if any)
1. Initialize TinyMCE with both `powerpaste` and `markdown` plugins.
2. Attempt to use markdown syntax within the editor.
3. Observe that the markdown syntax is not processed and remains unformatted.

### ✔️ Expected result
Markdown syntax should be correctly interpreted and rendered within the editor.

### ❌ Actual result
Markdown syntax is not processed, and the text remains unformatted.

### ❓ Possible solution
Currently, removing the `powerpaste` plugin allows the `markdown` plugin to function correctly.

## 📃 Other details
- Browser: Chrome Version 127.0.6533.99 (Official Build) (arm64)
- OS: macOS 14.5
- First affected version: TinyMCE 7.2.1
- Worked in version: N/A (This issue occurs when both plugins are enabled)

**Comment by lostkeys** [comment]
Hi @abc3675878. Markdown and Powerpaste are premium plugins. If you are a paying customer or using TinyMCE cloud in a trial, please file your support ticket here: https://support.tiny.cloud/
