### ISSUE TITLE
Inline toolbar sometimes hides the text

### ISSUE THREAD

**Issue by LosHawlos** [tinymce/tinymce#9825]
## 📝 Provide detailed reproduction steps (if any)
See for example this fiddle: https://fiddle.tiny.cloud/ObxHRKXjpj/1
Change the size of the browser window and use the browser zoom.

It is okay on 100% zoom in the browser:
<img width="960" alt="TinyMCE_bug_100_percent_zoom" src="https://github.com/user-attachments/assets/4a675cd6-a602-4d39-bf1a-0268c9e6907a">

Text is hidden behind the toolbar in 110% zoom:
<img width="960" alt="TinyMCE_bug_110_percent_zoom" src="https://github.com/user-attachments/assets/25141079-60d7-4c28-8be7-a5206989b0f0">

### ✔️ Expected result
The toolbars will be placed properly outside the text area.

### ❌ Actual result
We are currently using version 6.8.3 which is delivered with the Pimcore CMS.
Depending on the screensize and/or zoom level of the browser the 2 lines in the toolbar can wrap into 3 lines, and then will cover the edited text because the position is not calculating in the extra line.

## 📃 Other details
- Browser: Firefox 129, Google Chrome 127
- OS: Windows 10
- First affected version: 6.4.1
- Worked in version: 6.3.2

**Comment by lostkeys** [comment]
Hi @LosHawlos! This was fixed in TinyMCE 7 so I recommend reaching out to Pimcore CMS and have them considering upgrading TinyMCE.
