### ISSUE TITLE
Merge Tags being editable after insertion

### ISSUE THREAD

**Issue by bretto36** [tinymce/tinymce#9842]
## 📝 Provide a description of the new feature or improvement
We use the Merge Tags to allow users to input values into their template, we use Twig under the hood, so there is the ability to specify filters like | date or | raw or | money. With the | date they can type a custom date format... but if we enable the merge fields plugin it doesn't allow us to edit it. 

### 🫶 What is the motivation?
Trying to make it simpler for our users to know the merge fields but still giving them flexibility to edit

### 🔗 What is the consequence of not having this feature?
Users have to type the whole merge field manually and not select from the list

### 🚦 How important would you rate the requested feature or improvement?
It's important to me, but not sure how many others

---

If you'd like to see this implemented sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
This is a premium feature, we do not offer premium support via GitHub. If you have a support subscription, you will be better served by our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
