### ISSUE TITLE
ExecCommand event doesn't trigger in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#985]
Description of problem:
The "ExecCommand" doesn't trigger in Chrome (version 28) when submitting from source code modal. It triggers in Firefox.

See tinymce fiddle attached.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6212](http://archive.tinymce.com/develop/bugtracker_view.php?id=6212) posted by [mediafreakch](http://archive.tinymce.com/profile.php?name=mediafreakch)_

> _**Tags:** [chrome chrome10 chrome11 chrome12 chrome13 4]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/uwdaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
