### ISSUE TITLE
In the case of Chinese or English input method, no matter which letter I press, I input four repeated lowercase letters. And the cursor automatically runs to the end

### ISSUE THREAD

**Issue by YeAhzjx** [tinymce/tinymce#9850]
In the case of Chinese or English input method, no matter which letter I press, I input four repeated lowercase letters. And the cursor automatically runs to the end

"tinymce": "^5.8.2"
"@tinymce/tinymce-vue": "^5.1.1"
vue3+vite
"browser": "chrome 128.0.6613.86"

I don't know where to go and how to solve this problem

**Comment by lostkeys** [comment]
Hey @YeAhzjx. We really need a replication test to be able to help out here. Please resubmit your issue, and make sure you can replicate it using standard TinyMCE to make sure it's not an issue with your implementation by using for example [TinyMCE fiddle](https://fiddle.tiny.cloud). Thanks.

**Comment by YeAhzjx** [comment]
> Hey @YeAhzjx. We really need a replication test to be able to help out here. Please resubmit your issue, and make sure you can replicate it using standard TinyMCE to make sure it's not an issue with your implementation by using for example [TinyMCE fiddle](https://fiddle.tiny.cloud). Thanks.

No, I found that this problem was caused by my use of watch to monitor textcontent, but thanks anyway
