### ISSUE TITLE
Firefox Paste Text No Color 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#986]
Description of problem: Paste any text into tinyMCE(latest) using FireFox(latest) and all text color is changed to black

Steps to reproduce:
1. Copy color text from Visual Studio
2. Paste in to tinyMCE
3. All color text is now black
4.
5.

Expected result: Keep all text colors as-is

Actual result: All text colors are black

NOTE: Paste colors works with IE9

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6213](http://archive.tinymce.com/develop/bugtracker_view.php?id=6213) posted by [Pointeman](http://archive.tinymce.com/profile.php?name=Pointeman)_
> 
> _**Tags:** [firefox paste color]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by fyrkant** [comment]
This issue is being closed due to its old age. :bug:

If you still have a problem connected to this, leave a comment and we can open it up again.

Cheers! :beer:
