### ISSUE TITLE
CDN File https://cdn.tiny.cloud/1/no-origin/tinymce/5.10.9-139/langs/en_US.js is 404.

### ISSUE THREAD

**Issue by Inakiz** [tinymce/tinymce#9865]
## 📝 Provide detailed reproduction steps
1. visit https://cdn.tiny.cloud/1/no-origin/tinymce/5.10.9-139/langs/en_US.js

**Comment by TheSpyder** [comment]
There are 3 problems here.

* Where did you get the `5.10.9-139` version from? The last release was `5.10.9-138`.
* There is no lang file for US english. It's the default editor language so the strings are inside the editor.
* The use of `no-origin` indicates you have not correctly configured your page to load the editor from our tiny cloud service.

I would also like to remind you that TinyMCE 5 is no longer supported without purchasing [LTS](https://www.tiny.cloud/long-term-support/).
