### ISSUE TITLE
Word content is cleared after paste

### ISSUE THREAD

**Issue by thiadmer** [tinymce/tinymce#9877]
## 📝 Provide detailed reproduction steps (if any)
When a Word text with bullet points is copied into TinyMCE, some list items are erased.

See https://fiddle.tiny.cloud/FeIuG5oPXg/17

1. Copy sample text in Word as provided in [paste-demo.docx](https://github.com/user-attachments/files/17023175/paste-demo.docx) to the clipboard
2. Paste the text in a TinyMCE editor
3. Check the console output

### ✔️ Expected result
All bullet points are pasted and shown in the editor

### ❌ Actual result
Bullet point 2 is missing in the text model and often not shown

### ❓ Possible solution
WordFilter `convertParagraphToLi` filters out list bullet points using:

`trimListStart(paragraphNode, /^\s*([\u2022\u00b7\u00a7\u25CF]|\w+\.)/);`

But the regexp `\w+\.` also filters out words ending with '.'.

Not sure which cases this line is supposed to handle, but If it should remove items like '1.', then `\d+\.` may be more appropriate instead of `\w+\.`.

## 📃 Other details
- Browser: any
- OS: any
- First affected version: 5.10
- Worked in version: 7

We are currently using the 5.10 branch and not able to fully upgrade TinyMCE version in our production application right now.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
TinyMCE 5 reached end of life in April 2023. If you'd like to get support for it, consider our LTS offering.
https://www.tiny.cloud/long-term-support/
