### ISSUE TITLE
Can't type the opening curved bracket { on a German Mac keyboard

### ISSUE THREAD

**Issue by ralf-krause** [tinymce/tinymce#9901]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. Take a Mac with macOS 15.0.1, 14.7.1 or 13.7 and the Safari browser. 
2. Add the German keyboard layout.
3. You should get the opening curved bracket { via option-8 on the German Mac keyboard
4. It works in TinyMCE 6 but not non TinyMCE 7.
5. I found the error in Moodle 4.5
6. I reproduced the problem on https://fiddle.tiny.cloud and on https://www.tiny.cloud/docs/tinymce/latest/full-featured-premium-demo/

### ✔️ Expected result
*What is the expected result of the above steps?*
I can't type the opening curved bracket { on a German Mac keyboard.
Everything is okay in text field without TinyMCE 7.

### ❌ Actual result
*What is the actual result of the above steps?*
Nothing.

## 📃 Other details
- Browser: Safari 18.01
- OS: macOS 15.0.1, 14.7.1 or 13.7
- First affected version: I can't say. Moodle 4.5 will be released on 20241007.
https://github.com/moodle/moodle/tree/main/lib/editor/tiny/js/tinymce
- Worked in version: Moodle 4.4.4. 
https://github.com/moodle/moodle/blob/MOODLE_404_STABLE/lib/editor/tiny/readme_moodle.md
- Issue in the Moodle tracker
https://tracker.moodle.org/browse/MDL-83257

I hove you will get a fix for this as soon as possible. 👍

Best trgards,
Ralf

Ralf Krause
moodleSCHULE e.V.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
It turns out the german keyboard shares the `keyCode` for this character with f12, and in TinyMCE 7.1 we added `alt+F12` to focus notifications. oops.

![Image](https://github.com/user-attachments/assets/97591ddd-6512-4445-b231-00444aec697b)

https://github.com/tinymce/tinymce/blob/5a10b0a3499e5dc81a97780233a97f793fe8218f/modules/tinymce/src/core/main/ts/api/NotificationManager.ts#L158-L161

While we figure out what to do about this, you can work around it by removing the shortcut:
https://fiddle.tiny.cloud/a3sdPDhyMb/0

**Comment by ralf-krause** [comment]
Hi Andrew,
thank you for your answer. I testet the opening curved bracket { on https://fiddle.tiny.cloud/a3sdPDhyMb/0 ... yes, { works for me in the new setting. 

Can you tell me if the developers at the Moodle headquarter will get the repaired code for Moodle 5.0dev?
I opened an issue in the Moodle tracker https://tracker.moodle.org/browse/MDL-83257

Best regards,
Ralf

**Comment by andrewnicols** [comment]
Thanks @TheSpyder,

@ralf-krause we can apply a fix in Moodle to disable that for Moodle 4.5 and above; and when this issue is resolved we'll revert that config change.

**Comment by TheSpyder** [comment]
Fix will be in 7.5:
#9901
