### ISSUE TITLE
Source code editor removes word "location"

### ISSUE THREAD

**Issue by sanketmahimkar** [tinymce/tinymce#9905]
## 📝 Provide detailed reproduction steps (if any)
Steps
1. …Open Tinymce editor
2. …Open Souce edtior <>
3. …Type Html tag with input as <input id="location"...>

### ✔️ Expected result
"location" word should remain

### ❌ Actual result
location gets removed automatically when source editor is closed

### ❓ Possible solution
Tinymce should give option to keep location word as Id

## 📃 Other details
- Browser: …Microsoft edge
- OS: …Windows
- First affected version: …TinyMCE version 6.8.2
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Any `id` or `name` value that matches a window property is blocked to avoid DOM clobbering.
https://en.wikipedia.org/wiki/DOM_clobbering

We do offer an option to disable sanitization, but it's not recommended.
https://www.tiny.cloud/docs/tinymce/latest/security/#turning-dompurify-off
