### ISSUE TITLE
JS error on tinymce 7.4

### ISSUE THREAD

**Issue by jetwes** [tinymce/tinymce#9915]
## 📝 Provide detailed reproduction steps (if any)
1. inject tinymce 7.4 via script tag

### ✔️ Expected result
Load tinymce Editor 

### ❌ Actual result
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at be (theme.min.js:9:4249)
    at fe (theme.min.js:9:4206)
    at Object.checkUiComponentContext (theme.min.js:9:383068)
    at Object.disabled (theme.min.js:9:296595)
    at exhibit (theme.min.js:9:77955)
    at theme.min.js:9:28522
    at we (theme.min.js:9:4468)
    at Object.exhibit (theme.min.js:9:28490)
    at theme.min.js:9:44975
## 📃 Other details
- Chrome
- OS: MacOs
- First affected version: 7.4
- Worked in version: 7.3
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @jetwes. We need more details. Can you please share your config.
— Fredrik, Product Manager

**Comment by sreichel** [comment]
Confirmed for OpenMage composer install.

**Comment by jetwes** [comment]
`tinymce.init({
            license_key: &quot;gpl&quot;,
            target: $refs.tinymce,
            selector: &quot;#tinyMCE&quot;,
            //inline: true,
            height: 400,
            mobile: {
                height: 200,
            },
            menubar: false,
            branding: false,
            language: &quot;de&quot;,
                        plugins: &quot;anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount mentions&quot;,
            mentions_fetch: mentions_fetch,
            mentions_item_type: &quot;profile&quot;,
            toolbar: &quot;undo redo | formatselect | &quot; +
                &quot;link bold italic backcolor underline forecolor | blocks fontfamily fontsize | alignleft aligncenter &quot; +
                &quot;alignright alignjustify | bullist numlist outdent indent | &quot; +
                &quot;removeformat | emoticons charmap &quot;
,            setup: function(editor) {
                editor.on(&quot;blur&quot;, function(e) {
                    value = editor.getContent()
                })

                editor.on(&quot;init&quot;, function (e) {
                    if (value != null) {
                        editor.setContent(value)
                    }
                })

                function putCursorToEnd() {
                    editor.selection.select(editor.getBody(), true);
                    editor.selection.collapse(false);
                }

                $watch(&quot;value&quot;, function (newValue) {
                    if (newValue !== editor.getContent()) {
                        editor.resetContent(newValue || &quot;&quot;);
                        putCursorToEnd();
                    }
                });
            }
        });`

**Comment by TheSpyder** [comment]
@sreichel can you provide a config that replicates the error in OpenMage? And does that break on https://fiddle.tiny.cloud/?

**Comment by TheSpyder** [comment]
@jetwes I see you're using the mentions plugin. Assuming you're a premium customer, please log a ticket with our support team: https://support.tiny.cloud/hc/en-us/requests/new

**Comment by TheSpyder** [comment]
Our analysis suggests this might be a browser caching issue. The part of `checkUiComponentContext` that calls `hasOwnProperty` is this code - we'd need a replication case to confirm that an undefined `contexts` is the issue:
https://github.com/tinymce/tinymce/blob/7db173c22d62dfbf19db6dbb2a67125c2a39edc8/modules/tinymce/src/themes/silver/main/ts/backstage/Backstage.ts#L65-L66

One way `contexts` could be undefined is if `tinymce.min.js` is an older version while `theme.min.js` was correctly updated for TinyMCE 7.4. It's part of a new feature we added in this release.

If that is the problem, you should be able to work around differences in server cache times with the `cache_suffix` setting:
https://www.tiny.cloud/docs/tinymce/latest/editor-important-options/#cache_suffix

**Comment by sreichel** [comment]
> [@sreichel](https://github.com/sreichel) can you provide a config that replicates the error in OpenMage? And does that break on https://fiddle.tiny.cloud/?

Seems to be als false report. Maybe it was cache-related. (?)  Updated to 7.4.0/7.4.1 w/o errors. Thank.

**Comment by TheSpyder** [comment]
In that case, the best we can do is log a better error message when the core and theme versions mismatch. This is something we'll consider, but it's rare that we make breaking changes to that boundary point.
