### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by closedjdk** [tinymce/tinymce#9917]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. goto website 
2.download tinymce.zip
3. open and theres no executable.
4. I create test.html and open it. blank page despite debugger running the js. 
<head>
<script src="<redacted>/Downloads/tinymce/js/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
</head>

### ✔️ Expected result
html editor
### ❌ Actual result
blank page

### ❓ Possible solution
make this as easy as `npm run` like every other project, but then i realize there is a paid product and then it makes sense why the make the free product hard to use. 

## 📃 Other details
- Browser: all major browsers
- OS:macos
- First affected version: latest
- Worked in version: none

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
TinyMCE is a library, not an application. It's used in such a wide variety of environments that we can't make any assumptions about where it might be used within the `tinymce` package, even if it would help the first-run experience.

When reading our docs, open source usage is in the "self-hosted" category. Here's the documentation page for getting started with self-hosted NPM/Yarn applications:
https://www.tiny.cloud/docs/tinymce/latest/npm-projects/
