### ISSUE TITLE
Tiny MCE v5 stripping out referrerpolicy HTML attribute from iFrame in ServiceNow after clicking Save button (was working before)

### ISSUE THREAD

**Issue by githubuser5859** [tinymce/tinymce#9927]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. Acquire a ServiceNow instance, anything forward of Utah Patch 10b.
2. Open any module that uses the HTML Editor field (aka Tiny MCE). A Knowledgebase Article is a good example to use.
3. Click the Source Code button, copy/paste a YouTube video via embed code (you can find this after clicking on "Share" for any YouTube video). The code snippet will include the referrerpolicy HTML attribute (i.e. referrerpolicy="Strict-Origin")
4. Click the Save button.
5. Click on the Source Code button again to verify the embed code and if the referrerpolicy HTML attribute has been stripped out.

### ✔️ Expected result
Embed code in the Source Code should be identical or nearly identical to what you copied, including the referrerpolicy HTML attribute.

### ❌ Actual result
Depending on the ServiceNow release, the referrerpolicy HTML attribute will be present or stripped out. If it's a release as of or newer than Utah Patch 10b, the actual result is the refererpolicy HTML attribute is stripped out. If it's earlier than Utah Patch 10b, particularly Utah Patch 9 HF1 or older, it should respect the referrerpolicy HTML attribute and not strip it out.

### ❓ Possible solution
ServiceNow's solution is to configure referrerpolicy at the global instance level, which would be system-side, as opposed to choosing when and how to incorporate the referrerpolicy at a local level. The current value of that setting is default, which means the system decides the referrerpolicy. It's always been set as default. It's never been changed. So why would the referrerpolicy HTML attribute be stripped out in newer releases? The fact that it's stripped out rather ungracefully, with no warning to the user or the system administrator via logging, suggests that it could be a defect.

Another solution for the ServiceNow system is write workflow which restores the referrerpolicy after the form has been saved. Have not tried to intercept and fix the code, client-side, after saving the Tiny MCE Source Code. But I have implemented a workaround solution using a Business Rule to restore the referrerpolicy. Of course, this workaround has nothing to do with TIny MCE.

## 📃 Other details
- This applies to ServiceNow instances. It is system-wide. Anywhere that ServiceNow leverages Tiny MCE. Ergo, any HTML Editor field in their system leverages Tiny MCE. 
- It would appear that it affects Tiny MCE v5. However, I could not find any documentation on the internal version that ServiceNow is using. v5 seems to be a safe bet, but that doesn't tell us the exact version number. It is possible they upgraded from v4 to v5 but, again, it seems like it MAY be a case where a patch of v5 broke it, as opposed to upgrading to a major version.
- First affection version: ServiceNow release Utah Patch 10b or newer.
- Worked in version: ServiceNow release Utah Patch 9 HF1 or older.
- Unconfirmed working or not working in the following versions: Utah Patch 9 HF1a, Utah Patch 9 HF1b, Utah Patch 10 HF1, Utah Patch 10a
- Reached out to ServiceNow and they said that they leverage TinyMCE for their HTML Editor and that, if it's not working as expected, there's really not much they can do, as neither they nor I today have access to a ServiceNow release where the referrerpolicy HTML attribute was being preserved.
- All of my instances are up-to-date and any test instances that I or even ServiceNow can spin up are all Utah Patch 10 or newer. I have examples in my instances where it worked because those instances, at one time, were on older ServiceNow releases. As the instances have been upgraded to stay up-to-date, it's practically impossible to reproduce the working use-case within ServiceNow. I would venture only the ServiceNow devs who incorporated TinyMCE into their platform can work to reproduce the working use-case. There is a very small possibility a fraction of customers have an older release in-use but those would likely be on-premise and not cloud-based. Practically zero. Hence, why ServiceNow responded to me that there's nothing they can do, as Tiny MCE is a 3rd-party tool.
- From ServiceNow's point-of-view, they're claiming it's not them. The question is can this issue be reproduced with Tiny MCE, external to ServiceNow? If the answer is yes, then we know it's Tiny MCE. If the answer is no, then that probably tell us how ServiceNow is incorporating Tiny MCE may be in question. Unless they can prove something is a defect, they won't declare it a defect (PRB or Problem in their system). And we currently cannot reproduce the working use-case within ServiceNow to facilitate creating a defect record. Best I can do is create an enhancement request and they may or may not act on it.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
I'd like to focus on one thing you said in particular:

> The question is can this issue be reproduced with Tiny MCE, external to ServiceNow?

This is a free open source issue tracker. The onus is on you to prove it's a TinyMCE issue, otherwise we're just going to refer you back to the software vendor (in this case ServiceNow). We provide https://fiddle.tiny.cloud to help with building clean replication cases but codesandbox or similar is also quite acceptable. If ServiceNow believe there is a TinyMCE issue we need to solve, they have contacts to report that to us directly.

In addition, if the issue cannot be reproduced in TinyMCE 7 we will be closing it as wontfix. TinyMCE 5 reached end-of-life in April 2023 and version 6 [has two weeks left](https://github.com/tinymce/tinymce/discussions/9609) before we cease open source support.

**Comment by TheSpyder** [comment]
While I would normally prefer you to use the fiddle save feature to link the replication case here, that was enough to do a quick search of the PR history. We fixed this in https://github.com/tinymce/tinymce/pull/9635.

You can replicate that change in 6 (and 5) using [extended_valid_elements](https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#extended_valid_elements). I suspect it would need to be a change in ServiceNow, however, not something you can do yourself.
