### ISSUE TITLE
tabFocus doesn't focus with multiple editors on page

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#995]
Description of problem for 3.x, have not tested 4:
Tabfocus plugin does not properly navigate through editors when multiple editors on page. The first editor is selected but the next one is skipped and the next focusable element is focused on. 

Steps to reproduce:
1. Have multiple Editors on page and at least one focusable element after the editors.
2. Tab through the elements

Expected result:
You are focused on the next editor

Actual result:
Skips the next editor and focuses on the next focusable element after the editor.

Reason for the issue:
line 29 in the editor_plugin_src.js for the tabfocus plugin: !(e.style.display == "none") && 
This check causes the textarea for the next editor to be skipped. If it is removed then the tabbing works as expected. 
Understandably this will cause an issue for any non-editor inputs that are not a hidden input but are hidden from the user. 

Possible solution would be maybe checking if the current element is an editor and returning true for focusable.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6222](http://archive.tinymce.com/develop/bugtracker_view.php?id=6222) posted by [garunski](http://archive.tinymce.com/profile.php?name=garunski)_

> _**Tags:** [firefox msie safari tabfocus]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/Vwdaab/4_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
