### ISSUE TITLE
Problem with greek numeric list

### ISSUE THREAD

**Issue by dramp-earsakeio** [tinymce/tinymce#9958]
Hello, 

When I use **greek numeric list**, the editor produces incorrectly the greek alphabet (α,β,γ,δ,ε,ζ,η,θ, ι, κ etc).
The right greek numeric list is (α,β,γ,δ,ε,**στ**,ζ,η,θ,ι,**ια**, **ιβ**, **ιγ** etc). Look here for more details: https://simple.wikipedia.org/wiki/Greek_numerals 

For example:
1 α
2 β
3 γ
4 δ
5 ε
**6 στ**
7 ζ
8 η
9 θ
**10 ια**
**11 ιβ** etc

In Greece, we use this kind of list so we need it to be fixed.

Thank you,
Dimitra

**Comment by lostkeys** [comment]
Hi @dramp-earsakeio. TinyMCE only applies `list-style-type: lower-greek;` to the ordered list element and the browser renders the greek letters. You need to bring up the issue with the browser vendors, we have no ability to change this behavior in TinyMCE without making a completely custom list function which we have no plans to do at this time.

Thanks for your understanding.
— Fredrik, Product Manager

**Comment by tethragon** [comment]
So, this is much deeper than I thought... It doesn't seem to be browser issue. Should we somehow inform W3C for this?
