### ISSUE TITLE
Can not get the whitespace at the end of a p element when getContent({format: 'html'}).

### ISSUE THREAD

**Issue by BetaZhang** [tinymce/tinymce#9977]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/SYBU1dlwLU/0) or similar.
1. Input a character such as 1.
2. Input a whitespace.
3. Input a charater such as 2.
4. Move the cursor between the whitespace and 2.
5. Press enter to add a newline.
6. Use getContent() method to get the editor content.
![Image](https://github.com/user-attachments/assets/ad923f46-11e8-4175-a9a6-3a7b17053ef7)

### ✔️ Expected result
*What is the expected result of the above steps?*
The output should keep the whitespace. In this case, output should be .
```javascript
"<p>1 </p><p>2</p>"
```

### ❌ Actual result
*What is the actual result of the above steps?*
The output doesn't have the whitespace.

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*
I have checked the source code. I found the code remove the whitespace here when getContent({format: 'html'}).
![Image](https://github.com/user-attachments/assets/ec2f2a49-e232-4368-8912-03cb73d514ab)

## 📃 Other details
- Browser: …
- OS: …
- First affected version: …
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @BetaZhang. As you found out, this isn't a bug. Please resubmit using the feature request template and pitch your idea as best as you can. Be mindful that many browsers will likely filter out stray ending spaces, the same way it collapses multiple spaces in a row.

To make sure you have a space at the end of the paragraph, you can use the [nonbreaking space plugin](https://www.tiny.cloud/docs/tinymce/latest/nonbreaking/) which adds a button where the user can explicitly insert a `nbsp;` whereever a space is required.

— Fredrik, Product Manager

**Comment by BetaZhang** [comment]
Thanks for your reply, @lostkeys.

But as you can see, the textarea and the contenteditable element will convert the whitespace to &nbsp; automatically in this case.
![Image](https://github.com/user-attachments/assets/1df06cf5-60e2-434c-a436-b288e4601cf8)
![Image](https://github.com/user-attachments/assets/51fb9848-53b7-40d9-89b9-99d1c898a27c)

And I think it will make users confused that the editor has different behavior when the users want to create the same content(just in different step). What is your opinion?
![Image](https://github.com/user-attachments/assets/a885cbf8-3080-42df-a73a-818f3610a402)

**Comment by lostkeys** [comment]
First, You shouldn't inspect the contents of the editor, you need to perform a submit and look at the outputted code. And the stripping of end tags is put there with the purpose as our opinion is that there is little reason to keep white space at the end of a line. It's good practice to remove it and that's probably why customers have asked us to add long back ago. So any changes to this needs to have a clear business benefit; what are our userbase actually solving by keeping spaces after paragraphs?

**Comment by BetaZhang** [comment]
Thanks for your reply, @lostkeys.
As you can see, I can select the whitespace(truly it is nbsp;) at the end of the paragraph in this case.
![Image](https://github.com/user-attachments/assets/78298c60-e9c3-474c-90f5-9bd38586fdcc)
But in this case, I can not select the whitespace(' ') at the end of the paragraph. The whitespace that I inputed was disappeared. It makes me confused. In my opinion, these case should create the same content, they just have different steps.
![Image](https://github.com/user-attachments/assets/ea86a919-e4aa-4949-a462-7ad1b19ad78d)

**Comment by lostkeys** [comment]
Hi again. I'm sorry, I cannot replicate what you are doing here. Pressing 1<space>2 results in two characters in the word count.

**Comment by BetaZhang** [comment]
Thanks for your reply, @lostkeys.
Maybe I didn't state the reproduction steps clearly.
### First case

1. Input 1
2. Input <space> to create a whitespace
3. Input <enter> to create a newline break
4. Input 2
5. And then you can see there are 3 characters in the wordcount. You can select the whitespace after the 1 character.
![Image](https://github.com/user-attachments/assets/db055ae3-b982-4c6a-9daa-7ec45f89abb6)

### Second case

1. Input 1
2. Input <space> to create a whitespace
3. Input 2
4. Move the cursor between the whitespace and 2.
5. Input <enter> to create a newline break
6. And then you can see there are 3 characters in the wordcount too. But I can not select the whitespace after the 1 character. The whitespace that I inputed was disappeared. 😢 
![Image](https://github.com/user-attachments/assets/20978fcd-9527-4d1f-a593-5455642bd7e5)
