### ISSUE TITLE
Bugs when deleting an <h1> tag with a <p> tag immediately after it in Chrome

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#998]
When deleting an &ltg;h1> that is immediately following by a &ltg;p>, inline styles are erroneously added to the &ltg;p>.

Steps to reproduce:
1. Go to http://fiddle.tinymce.com/lldaab/3 in Chrome
2. Delete line 1

Expected result:
The &ltg;h1> is deleted and the &ltg;p> is not touched.

Actual result:
The &ltg;h1> is deleted, and the &ltg;p> tag is turned into an &ltg;h1> with inline styles is added.

Note:
I'd swear this is very similar to a bug that was fixed before...
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6225](http://archive.tinymce.com/develop/bugtracker_view.php?id=6225) posted by [Chris Turnbull](http://archive.tinymce.com/profile.php?name=Chris Turnbull)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/lldaab/3_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
