### ISSUE TITLE
HTML for Images Encoded as CSS do not work

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#999]
Description of problem: 
- Images encoded as CSS do not work when posted via HTML.

Steps to Reproduce:
1. Open the file attached (CSS HTML) and copy all of the HTML, or find and image and encode it as CSS.
2. Go to http://www.tinymce.com/tryit/3_x/full.php
3. Click the "HTML" button (Aka 'Edit HTML Source').
4. Paste the contents from the attached file into the HTML editor
5. Click "Update".

Expected result:
- An image should be displayed

Actual result:
- An image is not displayed
- A broken image icon is displayed

Notes:
- This issue occurs on both the 3.X and 4.X versions
- If you paste the same HTML into an HTML tester (such as http://www.draac.com/htmltester.html), the image will display
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6226](http://archive.tinymce.com/develop/bugtracker_view.php?id=6226) posted by [li-kris](http://archive.tinymce.com/profile.php?name=li-kris)_

> _**Tags:** [firefox msie safari chrome opera image css embed]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
