### ISSUE TITLE
TinyMCE 6 Appends Bookmark tags to Style tags within body

### ISSUE THREAD

**Issue by hjanaarthanan** [tinymce/tinymce#9999]
## 📝 Provide detailed reproduction steps (if any)
1. TinyMCE 6.8.4 is being used as an Email editor.
2. Open a received HTML email that has <style> tags in the body
3. The email opens correctly with content styled as expected.
4. Do editor.getContent()

### ✔️ Expected result
*The resulting content string should have the <style> tag*

### ❌ Actual result
*The resulting string did not have the <style> tag*

### ❓ Possible solution
*The reason for this was found to be that TinyMCE adds a marker tag within the style tag as below and this causes the tag to be filtered when calling getContent()*
```
<style>
...
<span id="mce_marker" data-mce-type="bookmark">&#xFEFF;</span>
</style>
```

## 📃 Other details
- Browser: Chrome 130.0.6723.117
- OS: MacOS Sonoma 14.7
- First affected version: ...
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @hjanaarthanan. TinyMCE filters out style tags by default. You can enable them using the [valid_children](https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#valid_children) option. Here's an [example](https://fiddle.tiny.cloud/V4T2AEj82w/0)

**Comment by hjanaarthanan** [comment]
Hi @lostkeys, I should have said this earlier but I do have valid_children set and style tags are retained if there are more than one. But the last style tag to which the bookmark is added is always removed. The other style tags do not have this added and they are retained. I can provide more info if you require.

**Comment by lostkeys** [comment]
@hjanaarthanan Yes, you need to provide a reproduction case that we can run and inspect. Also note that any fixes will be applied to TinyMCE 7
